### ISSUE TITLE
Crash on com.google.fira.worker thread, EXC_BAD_ACCESS 0x0000000106896210

### ISSUE THREAD

**Issue by siddew201** [firebase/firebase-ios-sdk#10007]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a GitHub issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: __13.2.1___
  * Firebase SDK version: ___9.1__
  * Installation method: CocoaPods
  * Firebase Component: _____ (FirebaseDynamicLinks, FirebaseInstallations, FirebaseAnalytics, FirebaseRemoteConfig, Messaging, FirebaseCrashlytics)
  * Target platform(s): iOS 

### [REQUIRED] Step 2: Describe the problem
App is getting crash.
#### Steps to reproduce:
We are unable to reproduce crash. We have just Firebase Crashlytics logs.

What happened? How can we make the problem occur?
Crashed: com.google.fira.worker
0  TCPApp                         0x237e210 -[APMAudienceTimestampsCache init] + 19399924
1  TCPApp                         0x23b25e0 __41-[APMMeasurement(Bundle) bundleRawEvents]_block_invoke + 19613892
2  TCPApp                         0x241434c -[APMSqliteStore performTransactionWithError:block:] + 20014640
3  TCPApp                         0x2385914 -[APMDatabase performTransaction:] + 19430392
4  TCPApp                         0x23b2308 -[APMMeasurement(Bundle) bundleRawEvents] + 19613164
5  TCPApp                         0x23c3518 -[APMMeasurement uploadData] + 19683324
6  TCPApp                         0x23c9da0 __49-[APMMeasurement handleAppWillResignActiveEvent:]_block_invoke_3 + 19710084
7  TCPApp                         0x24097e0 __51-[APMScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke + 19970756
8  libdispatch.dylib              0x1e6c _dispatch_call_block_and_release + 32
9  libdispatch.dylib              0x3a30 _dispatch_client_callout + 20
10 libdispatch.dylib              0xb124 _dispatch_lane_serial_drain + 668
11 libdispatch.dylib              0xbc80 _dispatch_lane_invoke + 392
12 libdispatch.dylib              0x16500 _dispatch_workloop_worker_thread + 648
13 libsystem_pthread.dylib        0x10bc _pthread_wqthread + 288
14 libsystem_pthread.dylib        0xe5c start_wqthread + 8

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by rizafran** [comment]
Thanks for reporting, @siddew201. Could you share the full stack trace of the issue and the crash message?
