### ISSUE TITLE
Firebase Crash on runtime APMDatabase insertBundle uploadData

### ISSUE THREAD

**Issue by ttuygun** [firebase/firebase-ios-sdk#10005]
### Step 1: Describe your environment

  * Xcode version: 13.4.1
  * Firebase SDK version: 8.12.1
  * Installation method: `Carthage` (select one)
  * Firebase Component: Core, Messasing 
  * Target platform(s): `iOS`

### Step 2: Describe the problem

The application crashed in the foreground after a successful build without making any action. I think the crashed happened when the SDK send some data to the server periodical time.

#### Steps to reproduce:

I cannot say that I can produce all time. It happens without any indicator.

#### Relevant Code:
```
m 0 _pthread_kill
pthread_kill
2 abort
3 abort_message
3D 4 demangling_terminate_handler()
5 _objc_terminate()
6 std:: __terminate (void (*)())
<D> 7 std::terminate()
8 objc_terminate
) _dispatch_client_callout
10 _dispatch_lane_serial_drain
11 _dispatch_lane_invoke
m 12 _dispatch_workloop_worker_thread
mi 13 _pthread_wqthread
V Original Exception Backtrace
Thread
0 __exceptionPreprocess
1 objc_exception_throw
2 + [NSObject(NSObject) doesNotRecognizeSelector:]
3 _forwarding_
4 _CF_forwarding_prep_0
5 -[APMDatabase insertBundle:isRealtime: error: ]
8 41-[APMMeasurement (Bundle) bundleRawEvents]_block_invoke
8 7 - [APMSqliteStore performTransactionWithError: block: ]
E 8 - [APMDatabase performTransaction:]
8 9 -[APMMeasurement (Bundle) bundleRawEvents]
8 10 - [APMMeasurement uploadData]
E 11 - [APMMeasurement networkRemoteConfigFetchCompletionHandler...
8 12 35-[APMMeasurement fetchRemoteConfig]_block_invoke
m 13 _dispatch_call_block_and_release
I 14 _dispatch_client_callout
m 15 _dispatch_lane_serial_drain
mm 16 _dispatch_lane_invoke
``

**Comment by rizafran** [comment]
Thanks for reaching out, @ttuygun. Could you provide the complete stack trace of your issue?

**Comment by morganchen12** [comment]
If you can repro the issue locally (even inconsistently), can you find the selector/receiver pair that's causing this crash? It should be part of the exception message printed to console.

**Comment by ttuygun** [comment]
2022-07-16 19:12:49.253095+0300 TestProject[50675:2249567] 8.12.1 - [Firebase/Analytics][I-ACS023105] Event is not subject to real-time event count daily limit. Marking an event as real-time. Event name, parameters: screen_view (_vs), {
    ga_debug (_dbg) = 1;
    ga_event_origin (_o) = auto;
    ga_previous_class (_pc) = FirstViewController;
    ga_previous_id (_pi) = -375749665399308660;
    ga_realtime (_r) = 1;
    ga_screen_class (_sc) = SecondViewController;
    ga_screen_id (_si) = -375749665399308659;
}
2022-07-16 19:12:49.263800+0300 TestProject[50675:2249564] +[NSData gul_dataByGzippingData:error:]: unrecognized selector sent to class 0x1da864298
2022-07-16 19:12:49.268050+0300 TestProject[50675:2249564] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSData gul_dataByGzippingData:error:]: unrecognized selector sent to class 0x1da864298'
*** First throw call stack:
(0x1810b2d78 0x199d17734 0x181190ab8 0x181047988 0x181046a60 0x106242c24 0x10627a3d4 0x1062cf204 0x106240190 0x10627987c 0x1062723a0 0x106277ac4 0x106277570 0x10d74cc6c 0x10d74e7bc 0x10d7568a4 0x10d7575e0 0x10d764168 0x1f15860bc 0x1f1585e5c)
libc++abi: terminating with uncaught exception of type NSException
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/GPUTools.framework/libglInterpose.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSData gul_dataByGzippingData:error:]: unrecognized selector sent to class 0x1da864298'
terminating with uncaught exception of type NSException
(lldb)

**Comment by paulb777** [comment]
Please confirm that the GoogleUtilities.xcframework is linked and you followed the following step from the instructions:

Add $(OTHER_LDFLAGS) `-ObjC` flag to "Other Linker Flags" in "Build Settings".
