### ISSUE TITLE
DynamicLink initializer shouldn't be available from Swift

### ISSUE THREAD

**Issue by ryanwilson** [firebase/firebase-ios-sdk#10000]
There's no `init` marked as `NS_UNAVAILABLE`, so a bare initializer is currently available in Swift but shouldn't be. 

https://github.com/firebase/firebase-ios-sdk/blob/8467858fc4cee858511380ac0f9ea5a17d007b5d/FirebaseDynamicLinks/Sources/Public/FirebaseDynamicLinks/FIRDynamicLink.h#L55-L86

We'll need to determine the right strategy for this: it's a breaking change to remove it, but it doesn't work as is. Introducing an initializer that's deprecated will introduce the API for ObjC users, which we don't want either.

**Comment by andrewheard** [comment]
Note: this API is also available for ObjC users

`FIRDynamicLink *dynamicLink = [[FIRDynamicLink alloc] init];`
