### ISSUE TITLE
Internal Error 8003

### ISSUE THREAD

**Issue by ekucet** [firebase/firebase-ios-sdk#10017]
I am getting such an error from ConfigManager.

> Error Domain=com.google.remoteconfig.ErrorDomain Code=8003 "Internal Error. Status code: 503" UserInfo={NSLocalizedDescription=Internal Error. Status code: 503}

My Code is:

```
class func getCode(_ completion: @escaping (Result<String, Error>) -> ()) {
        let remoteConfig = RemoteConfig.remoteConfig()
        remoteConfig.fetch(withExpirationDuration: 3600) { status, error in
            guard error == nil else {
                print(error?.localizedDescription)
                print(error)
                completion(.failure(error!))
                return
            }
            
            remoteConfig.activate()
            let value = remoteConfig.configValue(forKey: "specialCode").stringValue
            completion(.success(value!))
        }
    }
```

**Comment by rizafran** [comment]
Thanks for reporting this, @ekucet. We're aware of the issue and the team is currently identifying what's causing this. I'll let you know once I have any news to share.

**Comment by ekucet** [comment]
> Thanks for reporting this, @ekucet. We're aware of the issue and the team is currently identifying what's causing this. I'll let you know once I have any news to share.

okay, thank you for your response. i hope they can fix this error. Because my application that on the distribution doesn’t work.

**Comment by rizafran** [comment]
@ekucet, you may check the [status dashboard](https://status.firebase.google.com/incidents/ow6oGue8BtdRaYJZdB9o) for more details regarding the issue. Apologies for any inconvenience this might have caused you.

**Comment by ekucet** [comment]
I think this problem is fixed.

**Comment by rizafran** [comment]
Thanks for letting me know, @ekucet. I've confirmed that the engineers have fixed the 5xx error. I'll now be closing this issue, but feel free to reopen or you may file a ticket to our [support channel](https://firebase.google.com/support) if the issue arises.
