### ISSUE TITLE
crash: FPRInstrument.m line 63 -[FPRInstrument registerClassInstrumentor:]

### ISSUE THREAD

**Issue by siddew201** [firebase/firebase-ios-sdk#10028]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a GitHub issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

Xcode version: 13.2.1_
Firebase SDK version: 8.4.0_
Installation method: `CocoaPods
Firebase Component: _____ (DynamicLinks, Installations, Analytics, RemoteConfig, Messaging, Crashlytics)
Target platform(s): iOS

### [REQUIRED] Step 2: Describe the problem
The app is getting crash at user's end

#### Steps to reproduce:
Since the app is getting crash at user's end, we don't have a way to reproduce it

What happened? How can we make the problem occur?
This could be a description, log/console output, etc
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x99288 __exceptionPreprocess
1  libobjc.A.dylib                0x16744 objc_exception_throw
2  CoreFoundation                 0x1a431c -[__NSCFString characterAtIndex:].cold.1
3  CoreFoundation                 0x1aa804 -[__NSSetM addObject:].cold.2
4  CoreFoundation                 0x24810 -[__NSSetM addObject:]
5  FirebasePerformance            0x12d70 -[FPRInstrument registerClassInstrumentor:] + 63 (FPRInstrument.m:63)
6  FirebasePerformance            0x18abc __51-[FPRNSURLSessionDelegateInstrument registerClass:]_block_invoke + 211 (FPRNSURLSessionDelegateInstrument.m:211)
7  libdispatch.dylib              0x3a30 _dispatch_client_callout
8  libdispatch.dylib              0x12c90 _dispatch_lane_barrier_sync_invoke_and_complete
9  FirebasePerformance            0x18a4c -[FPRNSURLSessionDelegateInstrument registerClass:] + 208 (FPRNSURLSessionDelegateInstrument.m:208)
10 FirebasePerformance            0x1ae28 __InstrumentSessionWithConfigurationDelegateDelegateQueue_block_invoke + 159 (FPRNSURLSessionInstrument.m:159)
11 TCPApp                         0x1239b4 @nonobjc NSURLSession.__allocating_init(configuration:delegate:delegateQueue:) (<compiler-generated>)
12 TCPApp                         0x123790 closure #1 in MoreView.downloadTransactionStatement() + 282 (MoreView.swift:282)
13 TCPApp                         0x8834 thunk for @escaping @callee_guaranteed () -> () (<compiler-generated>)
14 libdispatch.dylib              0x1e6c _dispatch_call_block_and_release
15 libdispatch.dylib              0x3a30 _dispatch_client_callout
16 libdispatch.dylib              0x11f48 _dispatch_main_queue_drain
17 libdispatch.dylib              0x11b98 _dispatch_main_queue_callback_4CF
18 CoreFoundation                 0x51800 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
19 CoreFoundation                 0xb704 __CFRunLoopRun
20 CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific
21 GraphicsServices               0x1374 GSEventRunModal
22 UIKitCore                      0x514648 -[UIApplication _run]
23 UIKitCore                      0x295d90 UIApplicationMain
24 TCPApp                         0xa44940 main + 39 (AppDelegate.swift:39)
25 ???                            0x108149ce4 (Missing)

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by rizafran** [comment]
Thanks for reporting, @siddew201. Could you try updating your SDK to the latest version and see if the issue is still reproducible?
