### ISSUE TITLE
In-app message was closed automatically without the user interaction while app launch.

### ISSUE THREAD

**Issue by kumareshsaran** [firebase/firebase-ios-sdk#10020]
Recently i have tried in firebase inapp messaging in our iOS application. 

In-app message was closed automatically without the user interaction while app launch.

In-app message works well app in logout mode. Issue will happens only on home screen. Please suggest me a solution for this problem.

Thanks in advance

**Comment by rizafran** [comment]
Thanks for reporting, @kumareshsaran. Please provide the details from the issue template to have a better understanding of the issue.
