### ISSUE TITLE
DynamicLinks.dynamicLinks().dynamicLink always returns nil

### ISSUE THREAD

**Issue by focus-app-dev** [firebase/firebase-ios-sdk#10023]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.4.1
  * Firebase SDK version: 8.15.0
  * Installation method: Cocoapods
  * Firebase Component: Dynamic Links
  * Target platform(s): iOS

#### Steps to reproduce:

App not installed

1. Create a link with the Dynamic link API (https://firebase.google.com/docs/dynamic-links/rest)
2. Click on the link and open App Store page
3. Install the app
4. Open the app
5. (Fail) The app is not opening the right content

What happened? How can we make the problem occur?
We noticed that the method `canParseCustomSchemeURL` always returned false, therefore the `DynamicLinks.dynamicLinks().dynamicLink` is always returning `nil`

We found a full working workaround by putting both on:

- Dynamic link create API the following `"iosCustomScheme": <custom_scheme>` in the `iosInfo` JSON object
- iOS App, the following `FirebaseOptions.defaultOptions()?.deepLinkURLScheme = "<custom_scheme>" `

We think this is not the intended way of how this should work.
Waiting for your help on this.

#### Relevant Code:

```
- (BOOL)canParseCustomSchemeURL:(nullable NSURL *)url {

  if (url.scheme.length) {

    NSString *bundleIdentifier = [NSBundle mainBundle].bundleIdentifier;

    if ([url.scheme.lowercaseString isEqualToString:_URLScheme.lowercaseString] ||

        [url.scheme.lowercaseString isEqualToString:bundleIdentifier.lowercaseString]) {

      return YES;

    }

  }

  return NO;

}
```

this code always returns false without workaround because `url.scheme.length` is always not available when defaulted (no custom values set with the `FirebaseOptions.defaultOptions()?.deepLinkURLScheme` property

**Comment by rizafran** [comment]
Thanks for reporting, @focus-app-dev. Could you share a sample app that reproduces the issue?

**Comment by focus-app-dev** [comment]
Hi, @rizafran is it fine if I provide you access to a Testflight build?

**Comment by rizafran** [comment]
Hi @focus-app-dev, for now, we preferred an [mcve](https://stackoverflow.com/help/minimal-reproducible-example) of your app to see if we could replicate the issue.
