### ISSUE TITLE
Running tests will show [BackgroundTask] Background Task 3 ("GDTCCTUploader-upload"), was created over 30 seconds ago

### ISSUE THREAD

**Issue by Jasperav** [firebase/firebase-ios-sdk#10044]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13
  * Firebase SDK version: 9
  * Installation method: `Swift Package Manager` (select one)
  * Firebase Component: Messaging + FirebaseAnalyticsSwift
  * Target platform(s): `iOS`

#### Steps to reproduce:

1. Run a test
2. Observe this in the logging (see last line):

```
Test Suite 'SignInWithAppleTest' passed at 2022-07-27 14:10:29.869.
	 Executed 4 tests, with 0 failures (0 unexpected) in 45.795 (45.797) seconds
Test Suite 'benjamin-iosTests.xctest' passed at 2022-07-27 14:10:29.869.
	 Executed 4 tests, with 0 failures (0 unexpected) in 45.795 (45.799) seconds
Test Suite 'Selected tests' passed at 2022-07-27 14:10:29.871.
	 Executed 4 tests, with 0 failures (0 unexpected) in 45.795 (45.802) seconds
2022-07-27 14:10:29.873366+0200 benjamin-ios[57122:894627] [BackgroundTask] Background Task 3 ("GDTCCTUploader-upload"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
```

**Comment by rizafran** [comment]
Thanks for reporting, @Jasperav. It seems like your issue is related to [#9859](https://github.com/firebase/firebase-ios-sdk/issues/9859#issuecomment-1151898170). Have you also encountered the same stack trace from that ticket?
