### ISSUE TITLE
Crashlytics reports are not shown on the dashboard after uploading successfully by the SDK

### ISSUE THREAD

**Issue by HimaParmar** [firebase/firebase-ios-sdk#10057]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.4.1
  * Firebase SDK version: 8.14.0
  * Installation method: CocoaPods
  * Firebase Component: Firebase/Crashlytics
  * Target platform(s):  iOS 

### [REQUIRED] Step 2: Describe the problem

We have firebase SDK integrated in our project from long time. We are facing an issue of not seeing crash report on Crashlytics dashboard. I checked in the debug logs and it shows "Packaged report with id" and "Submitting report async" but reports are not visible on dashboard after waiting for more than 48 hours. (the hours mentioned here is for manually created crash)

#### Steps to reproduce:

I tried to crash manually with following code after seeing that there were no crash reports generated for my project from last 60 days.
```
let a = [0]
let _ = a[1]
```
I can see this logs in the debug logs:
```
8.14.0 - [Firebase/Crashlytics][I-CLS000000] [Firebase/Crashlytics] Packaged report with id 'a8c3f684376545c5b9a1ced7bcf3bf83' for submission

8.14.0 - [Firebase/Crashlytics][I-CLS000000] Submitting report async
```

**Comment by rizafran** [comment]
Hi @HimaParmar, it seems like your crashes are uploading successfully based on your debug logs, but not showing in the console. With this, please file a ticket via our [support channel](https://firebase.google.com/support) so the team can investigate your project. I'll now be closing this issue.
