### ISSUE TITLE
Firestore completion handler not called after logging out and logging in as another user.

### ISSUE THREAD

**Issue by XiandWang** [firebase/firebase-ios-sdk#1005]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version:  9.2
  * Firebase SDK version: 4.10.0
  * Firebase Component: All (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: Firestore 0.10.2

#### Steps to reproduce:

After logging out the current user, and log in as another user, somehow the all the Firestore's write completion handlers are not called any more ( the write to Firestore never succeeds). I have to kill the app to make it work again.

I don't know if the problem is  personal to me, or it's a general bug. 

Thank you.

#### Relevant Code:

```
```

**Comment by morganchen12** [comment]
Is this error still present in 4.11.0? Sounds like something that was fixed recently.

Can you [set the log level](https://firebase.google.com/docs/reference/ios/firebasecore/api/reference/Classes/FIRConfiguration#/c:objc(cs)FIRConfiguration(im)setLoggerLevel:) to `FIRLogLevelDebug` and share some logs?

**Comment by mikelehen** [comment]
This may also be working by design unfortunately.  When you log out we're no longer able to get auth tokens for the previous user and so any writes that were previously queued (but not completed) are indefinitely stuck until you log in as that user again (at which point we'll start sending them again).  So if the writes are important to send right away, it's best to wait for them before signing out / back in as a new user.

**Comment by XiandWang** [comment]
@morganchen12 You are right! After upgrading to the newest SDK, the bug was gone. I think it's fixed in  4.10.1 . Thank you!
