### ISSUE TITLE
XCode: App Installation Failed: Duplicate Bundle Identifier (Carthage)

### ISSUE THREAD

**Issue by terryworona** [firebase/firebase-ios-sdk#1006]
### Environment

* Xcode version: 9.2 (9C40b)
* Firebase SDK version: 4.11.0
* Firebase Component: Auth, Core

### Setup

* Using Carthage as per these [instructions](https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md).
* My **Cartfile** contains the following:

```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAuthBinary.json"
```

* Each framework is imported and added to my target's **Linked Frameworks**:
![](https://cdn2.dropmarkusercontent.com/82157/98db692a45046bbeddd7432004587b89ed0c4c5b/carthage-firebase.png)

* I've ensured `Firebase.framework` isn't added to **Linked Frameworks** as per [these](https://github.com/firebase/firebase-ios-sdk/issues/911#issuecomment-372455235) instructions:

![](https://cdn2.dropmarkusercontent.com/82157/e7936e8098fb6b14e5e24bbbf61b550cc1773a27/xcode-firebase-linked-frameworks.png)

* I've added **-ObjC** to **Other Linker Flags**. 
* I've added the frameworks to my `/usr/local/bin/carthage copy-frameworks` run script (also tried without):

![](https://cdn2.dropmarkusercontent.com/82157/cf3a9ac53ab0d9e88b1d1cc5dd5ed90c70be7fc3/run-script.png)

### Problem

When building to device, Xcode reports: **App installation failed**: _This application or a bundle it contains has the same bundle identifier as this application or another bundle that it contains. Bundle identifiers must be unique._:

![](https://cdn2.dropmarkusercontent.com/82157/8b3f8fe624c6b8fdd6b1d38db977fedd129fe752/firebase-xcode.png)

### Questions

**Note**: My app's bundle identifier does not match anything found in Firebase. 

1. Any way to resolve this? 
2. If not, is there a better way to see the logs? I've looked @ device logs and there isn't anything available. Debug console isn't printing anything either.

**Comment by paulb777** [comment]
The Firebase frameworks should not be add to `copy-frameworks`. They contain static libraries that are linked at build time. 

Please make sure you remove all of them, clean your environment, and retry.

If you're still having the issue, you'll likely need to share a reproducible example for us to help you further.

**Comment by terryworona** [comment]
@paulb777 thanks that worked!

I previously tried removing all the Firebase* frameworks from `copy-frameworks`, but forgot the clean step. Duh. I should have known :) Rookie mistake. 

Marking resolved. Thanks again.

**Comment by sgrgrsn** [comment]
@paulb777 Could we add a comment to the Carthage.md file saying that the frameworks should NOT be added to the Carthage build phase. I was in doubt when I followed the guide today.

**Comment by sgrgrsn** [comment]
@paulb777 I've created a [pull request](https://github.com/firebase/firebase-ios-sdk/pull/1404) for adding a comment in the Carthage.md
