### ISSUE TITLE
FR: Swift Package Manager support for MLKit by Firebase team consultants

### ISSUE THREAD

**Issue by d-date** [firebase/firebase-ios-sdk#10069]
### Feature proposal

I request you that the Firebase team consultants to support MLKit for Swift PM.

MLKit was originally supported as a Firebase product, which is why `MLModelDownloader` is still in this repo.
As of March 2020, MLKit began to be offered differently from Firebase as a new standalone SDK.
This decision in itself makes sense.

However, MLKit's lack of open source code and support for CocoaPods only has hindered its migration to Swift PM.
We have also observed that the MLKit team is also struggling to support it. https://github.com/googlesamples/mlkit/issues/180
It would have been nice if it were completely independent of Firebase, but like Firebase, it relies on common libraries, including GoogleUtilities, etc., so trying to migrate only Firebase to Swift PM
This would have resulted in duplicate symbols.

I decided to support Swift PM on my own and converted the MLKit pre-built binaries to XCFramework.
However, I am encountering some problems due to the lack of serious support for Swift PM.

- Using google-toolbox-for-mac, which is not supported for Swift PM (already removed in Firebase)
- Classes derived from [Old Protobuf](https://github.com/protocolbuffers/protobuf/tree/main/objectivec) are being used. This is already supported in Firebase to use apple/SwiftProtobuf.
- It is difficult to convert from pre-built binaries to the architecture for the Arm64 simulator, and simulator builds cannot be performed on Apple Silicon Macs. This is a known problem with installations with CocoaPods.

As you know, the first and second problems have already been resolved in Firebase due to the efforts of the Firebase team to support SwiftPM.

This issue is a significant degradation of the development experience not only for MLKit users, but also for developers who use Firebase in conjunction with MLKit.

We appreciate Firebase's diligent efforts to support developers on a daily basis and ask that you consider taking action to address this issue.

**Comment by paulb777** [comment]
@d-date Sorry about the trouble and thanks for the request.  I'm going to close as out of scope. While we can help and have helped other Google teams add Swift PM support, the requirement needs to be driven through those teams.

cc: @bcdj
