### ISSUE TITLE
Xcode - really slow

### ISSUE THREAD

**Issue by haakonem** [firebase/firebase-ios-sdk#10076]
When I have tried to download the packages from the SDK here in Github, I manage to add it perfectly fine into my XCode project. Although my whole project has become really slow. Extremely slow. from taking just seconds to simulate the project, now it takes 2-4 minutes. 

Model: MacBook Pro (13-inch, M1, 2020)
Xcode: Version 13.4.1

**Comment by paulb777** [comment]
@haakonem Sorry about the trouble. We'll need more information in order to help.

Please fill out the issue template and add reproduction steps.
