### ISSUE TITLE
[APMIdentity appInstanceID] main thread hangs

### ISSUE THREAD

**Issue by linziyiwj** [firebase/firebase-ios-sdk#10080]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Xcode_13.2
  * Firebase SDK version: 8.12.0
  * Installation method: `CocoaPods` 
  * Firebase Component: Analytics (Core, Database, Firestore, Messaging, Storage, etc)
  * Target platform(s): `iOS`

#### Steps to reproduce:

Sdk version：
Firebase/Analytics 8.12.0
Google-Mobile-Ads-SDK  8.13.0

We find the problems in hangs of Xcode 14.0 organizer, it hangs the main thread for a long time. 

Key Stack Info Below：
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/39822433/183298391-2a6183ae-21c3-4c25-ada6-7fc541a9fa6c.png">

If you need more info,please reply me thanks.

**Comment by rizafran** [comment]
Hi @linziyiwj, it seems like your issue is related to #6392. Could you try updating your SDK version to 8.14.0 and see if you'll still encounter the issue?

**Comment by linziyiwj** [comment]
> 
Hi，Has the new version of 8.14.0 fixed this problem?  And there is no need to update the version in this issue for https://github.com/firebase/firebase-ios-sdk/issues/6392

**Comment by linziyiwj** [comment]
> Hi @linziyiwj, it seems like your issue is related to #6392. Could you try updating your SDK version to 8.14.0 and see if you'll still encounter the issue?

Hi @rizafran,  Has the new version of 8.14.0 fixed this problem? And there is no need to update the version in this issue for https://github.com/firebase/firebase-ios-sdk/issues/6392

**Comment by rizafran** [comment]
@linziyiwj, based on the [comment](https://github.com/firebase/firebase-ios-sdk/issues/6392#issuecomment-1057449350), the fix was included in version 8.14.0.

**Comment by linziyiwj** [comment]
> 
Thanks, We will upgrade the version and then look at the data
