### ISSUE TITLE
Firebase 9.4.0 not tagged, not available in SPM

### ISSUE THREAD

**Issue by jshier** [firebase/firebase-ios-sdk#10083]
It looks like CocoaPods got the 9.4.0 release, but there's been no general release or tag usable by SPM. Could we get one, or is this not a general release?

**Comment by paulb777** [comment]
@jshier Thanks for the report. It also looks like the zip wasn't published.

**Comment by chliangGoogle** [comment]
@jshier Thanks for filing the issue so quickly so we can address it timely. Should be fixed now. Can you test it again and see if it still happens?

**Comment by jshier** [comment]
Yep, SPM was able to find the root Firebase 9.4.0 package, thanks.

**Comment by jshier** [comment]
Looks like it still needs a release though.

**Comment by paulb777** [comment]
FYI, we had a release glitch and the SPM 9.4.0 tag matches the 9.3.0 tag. We added a 9.4.1 release tag for SPM only that now correctly matches the CocoaPods 9.4.0 tag.

**Comment by jshier** [comment]
I've picked up that tag now as well, thanks. There do seem to be some `exact` dependency versions in the `Package` which may need to be reviewed, but this works. Thanks.

**Comment by paulb777** [comment]
See the different commit hashes at https://github.com/firebase/firebase-ios-sdk/tags
