### ISSUE TITLE
Error when running iOS app on Apple Silicon Mac

### ISSUE THREAD

**Issue by ileeric** [firebase/firebase-ios-sdk#10099]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 14.0 beta 5 (14A5294e)
  * Firebase SDK version: 9.4.1
  * Installation method: Swift Package Manager
  * Firebase Component: Messaging (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Target platform(s): macOS 

#### Steps to reproduce:

When running iOS app on a Mac with apple silicon, the SDK fails to get the FCM Token.
(Apps can receive notification on iOS with the same code)

Log:
[FirebaseMessaging][I-FCM002022] APNS device token not set before retrieving FCM Token for Sender ID '(MYSENDERID)'. Notifications to this FCM Token will not be delivered over APNS.Be sure to re-retrieve the FCM token once the APNS device token is set.
[FirebaseMessaging][I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. If you'd prefer to manually integrate Firebase Messaging, add "FirebaseAppDelegateProxyEnabled" to your Info.plist, and set it to NO. Follow the instructions at:
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
to ensure proper integration.
[FirebaseMessaging][I-FCM002022] APNS device token not set before retrieving FCM Token for Sender ID '(MYSENDERID)'. Notifications to this FCM Token will not be delivered over APNS.Be sure to re-retrieve the FCM token once the APNS device token is set.
[FirebaseMessaging][I-FCM027004] Unable to save checkin info, resetting checkin preferences in memory.
Error fetching FCM registration token: Error Domain=com.google.iid Code=-34018 "(null)"

(MYSENDERID) is originally a number but I removed it for security reasons
#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by morganchen12** [comment]
The error in question is a Keychain error as described [here](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseMessaging/Sources/FIRMessagingConstants.m#L86).

The forum post [here](https://developer.apple.com/forums/thread/64699) suggests your mac app is missing a required entitlement.

**Comment by ileeric** [comment]
> The error in question is a Keychain error as described [here](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseMessaging/Sources/FIRMessagingConstants.m#L86).
> 
> The forum post [here](https://developer.apple.com/forums/thread/64699) suggests your mac app is missing a required entitlement.

Which entitlement should I be missing? 
This works correct on my iPad an my iPhone...

**Comment by ncooke3** [comment]
Hi @ileeric, are you seeing a pop-up asking for permission to access the keychain like this:

<img width="300" alt="Permissions pop-up from `Keychain Access.app`" src="https://user-images.githubusercontent.com/36927374/186549974-8a8efd8f-20b0-41cd-80b0-fc14291ecffe.png">

Additionally, could you try enabling the Keychain Sharing capability?

**Comment by ileeric** [comment]
> 

Actually, no. I am not getting that pop up

**Comment by ileeric** [comment]
> Hi @ileeric, are you seeing a pop-up asking for permission to access the keychain like this:
> 
> <img alt="Permissions pop-up from `Keychain Access.app`" width="300" src="https://user-images.githubusercontent.com/36927374/186549974-8a8efd8f-20b0-41cd-80b0-fc14291ecffe.png">
> 
> Additionally, could you try enabling the Keychain Sharing capability?

Actually, no. I am not getting that pop up

**Comment by moffatman** [comment]
I solved it by adding `com.google.iid` and `com.google.iid.checkin` to the keychain sharing groups

**Comment by ileeric** [comment]
> I solved it by adding `com.google.iid` and `com.google.iid.checkin` to the keychain sharing groups

Wow! This did the trick! Thank you so much!
