### ISSUE TITLE
FIRPerformance exception when custom FirebaseApp.configure name used

### ISSUE THREAD

**Issue by rowungiles** [firebase/firebase-ios-sdk#10092]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 14.0 beta 4 (14A5284g)
  * Firebase SDK version: 9.4.1
  * Installation method: `Swift Package Manager`
  * Firebase Component: Performance
  * Target platform(s): `iOS`

### [REQUIRED] Step 2: Describe the problem
If I try to do `Firebase.configure(name: "CUSTOM", options: "path")`, on first performance trace an exception is thrown: 
`"The default Firebase app has not yet been configured. Add [FirebaseApp configure] to your application initialization."`

If my custom name is "__FIRAPP_DEFAULT" this exception is not thrown.

If I do a `Firebase.configure()` this exception is not thrown.

I'd like to specify a custom name so I can use `Performance` in a framework and avoid clashes with other code.

#### Steps to reproduce:

Initialize Firebase using a custom name:
```
if FirebaseApp.allApps?["CUSTOM_NAME"] == nil {
    let path = try Bundle.module.path(forResource: "GoogleService-Info", ofType: "plist")
    if let file = FirebaseOptions(contentsOfFile: path) {
        FirebaseApp.configure(name: "CUSTOM_NAME", options: file)
    } else {
        throw error
    }
}
```

Then do a trace:

```
let trace = Performance.startTrace(name: "CUSTOM_TRACE_NAME")
trace.stop()
```

**Comment by rizafran** [comment]
Sorry for the trouble, @rowungiles. Per checking, it seems like Firebase Performance only works using the default `FirebaseApp.configure()` instead of the custom one.

**Comment by rowungiles** [comment]
Hi @rizafran thanks for the reply. Yes, I thought that would be the case. But it wasn't clear to me if that was an intentional design choice or accidental oversight. And if the latter if it was on the roadmap for a fix?

**Comment by jfcong** [comment]
Hi @rowungiles, the engineering team is aware of this, and we will have some discussion/investigation about whether to support custom FirebaseApp and give an update here. Thanks for raising this up!

**Comment by rowungiles** [comment]
Thanks for the update @jfcong. Looking forward to your update.

**Comment by jfcong** [comment]
Hi @rowungiles, I'd like to understand your use case a little more. Does Firebase performance clash with other code when you use the default Firebase instance? How so?

**Comment by rowungiles** [comment]
Hi @jfcong, I want to run Firebase Performance within an SDK that will be embedded in different apps. Some of those other apps have Firebase integrations themselves.

If the app has already configured their Firebase and then I try to do a Firebase.configure() in the SDK, then I'll get an exception about trying to configure twice.
```
*** Terminating app due to uncaught exception 'com.firebase.core', reason: 'Default app has already been configured.'
terminating with uncaught exception of type NSException
```

So I can work around this by providing a custom name in `FirebaseApp.configure(name: "CUSTOM_NAME", options: options)` and I can do some additional checks to avoid a re-instatiation failure later by checking `FirebaseApp.allApps?["CUSTOM_NAME"]`.

If Performance instatiates with the default config file and it's from the embedding app, then the SDK Performance events will be sent to the embedding app Firebase dashboard.

I hope that helps clarify. Please let me know if you have more questions.

**Comment by jfcong** [comment]
Hi @rowungiles, we don't currently support your use case. Even if we added support for Firebase instance with custom names and options, it would still not let you capture performance information for your SDK only. There are a couple of blockers to supporting your use case:
- Currently, Fireperf SDK assumes there's one Firebase instance for the whole app and we don't differentiate between SDK or the app. When we initialize traces, we don't attribute that to a particular Firebase instance, and we currently use a singleton to track all the traces.
- If we do differentiate them, say we have two Firebase instances, one for the SDK and one for the app, we need to find a way to differentiate performance impact between the two, and there's no easy way to do that.

Given this and the amount of investigation/effort needed, we will consider this a feature request and it will be prioritized with our other feature requests in the future. Let me know if you have any more questions!

**Comment by rowungiles** [comment]
Ok, understood. Thanks @jfcong. I'll close this issue for now.
