### ISSUE TITLE
Verify Xcode 9 - GitHub integration

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#101]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9
  * Firebase SDK version: 4.x
  * Library version: 4.x
  * Firebase Product: core

### [REQUIRED] Step 3: Describe the problem

At WWDC, Apple announced increased integration between GitHub and Xcode.  Details and demos at https://developer.apple.com/videos/play/wwdc2017/405/. We need to verify that the new workflow works well with the firebase-ios-sdk repo, cloning, opening in Xcode, etc.

**Comment by ryanwilson** [comment]
In order for this to function, there needs to be an `.xcodeproj` or `.xcworkspace` file in the *root* of the repo. Since ours is in `Example/`, it won't appear for users. Do we want to modify the layout of the repo for this?

**Comment by paulb777** [comment]
We could potentially have a separate top-level .xcworkspace that is an Example separate from the library builds and unit tests.

**Comment by ryanwilson** [comment]
What would we want to have in the root repo? Just a blank project with `FirebaseApp.configure()`, or an `.xcworkspace` with something like the quickstarts?

Maybe that's better off for the quickstarts. We could add a symlink to the `Example` directory, but it needs the `.xcworkspace` to function correctly and that is generated via `pod install`.

**Comment by paulb777** [comment]
Closing for now. Let's reopen if there are specific requests.
