### ISSUE TITLE
GitHub/CocoaPods Releases Missing (9.4.0 & 9.4.1)

### ISSUE THREAD

**Issue by Salakar** [firebase/firebase-ios-sdk#10103]
### [REQUIRED] Step 1: Describe your environment

 N/A

### [REQUIRED] Step 2: Describe the problem

Hey all, we have build failures over at https://github.com/invertase/firestore-ios-sdk-frameworks with the 9.4.x releases, not sure if you're aware but:

 - 9.4.0 is missing a GitHub release but exists on CocoaPods
 - 9.4.1 has a GitHub release but does not exist on CocoaPods 

So we're unable to use either version since either GitHub release or a CocoaPods release is missing on each.

#### Steps to reproduce:

N/A

#### Relevant Code:

N/A

**Comment by paulb777** [comment]
. Sorry about the confusion.

9.4.1 was a Swift Package Manager only release since we created the 9.4.0 tag wrong. The zip distribution is the same for either. CocoaPods-9.4.0 is equivalent to 9.4.1 https://github.com/firebase/firebase-ios-sdk/tags

**Comment by paulb777** [comment]
Would it help to make a 9.4.0 release on GitHub that exactly matches the 9.4.1 release?

**Comment by mikehardy** [comment]
I think an actual release on the 9.4.0 tag would satisfy the logic constraints in the script and it would all hook up and complete, yes

**Comment by paulb777** [comment]
Published https://github.com/firebase/firebase-ios-sdk/releases/tag/9.4.0

**Comment by mikehardy** [comment]
That did the trick! Our script is off to the races now:

> Found archive asset, downloading from url https://github.com/firebase/firebase-ios-sdk/releases/download/9.4.0/Firebase.zip ...
