### ISSUE TITLE
APMAudienceTimestampsCache init

### ISSUE THREAD

**Issue by Nehacdew** [firebase/firebase-ios-sdk#10108]
Step 0: Are you in the right place?
yes

**### [REQUIRED] Step 1: Describe your environment**

Xcode version:13.2.1
Firebase SDK version: 9.1
Installation method: CocoaPod
Firebase Component: Crashlytics
Device For Max count:i Phone 11
OS for Max count	: 15.5.0

**[REQUIRED] Step 2: Describe the problem**
App is getting crash.

**Steps to reproduce:**
Not able to reproduce. 

Crash Item	:	TCPApp -[APMAudienceTimestampsCache init]
Issue Details	:	Crashed: com.google.fira.worker
0  TCPApp                         0x237e210 -[APMAudienceTimestampsCache init] + 19399924
1  TCPApp                         0x23b25e0 __41-[APMMeasurement(Bundle) bundleRawEvents]_block_invoke + 19613892
2  TCPApp                         0x241434c -[APMSqliteStore performTransactionWithError:block:] + 20014640
3  TCPApp                         0x2385914 -[APMDatabase performTransaction:] + 19430392
4  TCPApp                         0x23b2308 -[APMMeasurement(Bundle) bundleRawEvents] + 19613164
5  TCPApp                         0x23c3518 -[APMMeasurement uploadData] + 19683324
6  TCPApp                         0x23c9da0 __49-[APMMeasurement handleAppWillResignActiveEvent:]_block_invoke_3 + 19710084
7  TCPApp                         0x24097e0 __51-[APMScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke + 19970756
8  libdispatch.dylib              0x1e6c _dispatch_call_block_and_release + 32
9  libdispatch.dylib              0x3a30 _dispatch_client_callout + 20
10 libdispatch.dylib              0xb124 _dispatch_lane_serial_drain + 668
11 libdispatch.dylib              0xbc80 _dispatch_lane_invoke + 392
12 libdispatch.dylib              0x16500 _dispatch_workloop_worker_thread + 648
13 libsystem_pthread.dylib        0x10bc _pthread_wqthread + 288
14 libsystem_pthread.dylib        0xe5c start_wqthread + 8

#### Relevant Code:
NA

**Comment by paulb777** [comment]
This is a reoccurrence of #10007 for which we haven't yet got enough information to reproduce.

**Comment by morganchen12** [comment]
The `init` method this is crashing in only calls `NSObject init` via `super` and then initializes two empty `NSMutableDictionary` instances, which should never crash. Crashing in this method may be caused by memory corruption. Have you tried enabling address sanitizer and trying to reproduce the crash?
