### ISSUE TITLE
Crashlytics : iOS : libc++abi.dylib : std::__terminate(void (*)())

### ISSUE THREAD

**Issue by Nehacdew** [firebase/firebase-ios-sdk#10107]
### Step 0: Are you in the right place?
Yes

### [REQUIRED] Step 1: Describe your environment

  * Xcode version:   13.2.1
  * Firebase SDK version: 9.1
  * Installation method:  CocoaPods
  * Firebase Component: Crashlytics
  * Target platform(s): iOS 
  * Device For Max count : Model:iPhone XR
  * OS for Max count : 15.5.0

### [REQUIRED] Step 2: Describe the problem
App is getting crash.

#### Steps to reproduce:
Not able to reproduce. 

Crash Item :-libc++abi.dylib
Issue Details : Crashed: com.google.firebase.crashlytics.ios.exception
0 FirebaseCrashlytics 0x1cd90 FIRCLSProcessRecordAllThreads + 393 (FIRCLSProcess.c:393)
1 FirebaseCrashlytics 0x1d170 FIRCLSProcessRecordAllThreads + 424 (FIRCLSProcess.c:424)
2 FirebaseCrashlytics 0x15f88 FIRCLSHandler + 34 (FIRCLSHandler.m:34)
3 FirebaseCrashlytics 0x10954 __FIRCLSExceptionRecord_block_invoke + 218 ([FIRCLSException.mm:218](http://firclsexception.mm:218/))
4 libdispatch.dylib 0x3a30 _dispatch_client_callout + 20
5 libdispatch.dylib 0x12c90 _dispatch_lane_barrier_sync_invoke_and_complete + 56
6 FirebaseCrashlytics 0x10110 FIRCLSExceptionRecord + 225 ([FIRCLSException.mm:225](http://firclsexception.mm:225/))
7 FirebaseCrashlytics 0xfe60 FIRCLSTerminateHandler() + 295 ([FIRCLSException.mm:295](http://firclsexception.mm:295/))
8 libc++abi.dylib 0x10f18 std::__terminate(void ()()) + 20
9 libc++abi.dylib 0x10eb4 std::terminate() + 64
10 libobjc.A.dylib 0x2d248 objc::DenseMapBase<objc::DenseMap<objc_class, PendingInitialize*, objc::DenseMapValueInfo<PendingInitialize*>, objc::DenseMapInfo<objc_class*>, objc::detail::DenseMapPair<objc_class*, PendingInitialize*> >, objc_class*, PendingInitialize*, objc::DenseMapValueInfo<PendingInitialize*>, objc::DenseMapInfo<objc_class*>, objc::detail::DenseMapPair<objc_class*, PendingInitialize*> >::FatalCorruptHashTables(objc::detail::DenseMapPair<objc_class*, PendingInitialize*> const*, unsigned int) const + 14
11 libdispatch.dylib 0x3a44 _dispatch_client_callout + 40
12 libdispatch.dylib 0x6eec _dispatch_continuation_pop + 500
13 libdispatch.dylib 0x1a13c _dispatch_source_invoke + 1596
14 libdispatch.dylib 0x11e9c _dispatch_main_queue_drain + 756
15 libdispatch.dylib 0x11b98 _dispatch_main_queue_callback_4CF + 44
16 CoreFoundation 0x51800 CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE + 16
17 CoreFoundation 0xb704 __CFRunLoopRun + 2532
18 CoreFoundation 0x1ebc8 CFRunLoopRunSpecific + 600
19 GraphicsServices 0x1374 GSEventRunModal + 164
20 UIKitCore 0x514648 -[UIApplication _run] + 1100
21 UIKitCore 0x295d90 UIApplicationMain + 364
22 TCPApp 0xa44940 main + 39 (AppDelegate.swift:39)
23 ??? 0x106b59ce4 (Missing)

#### Relevant Code:

NA

**Comment by rizafran** [comment]
Hi @Nehacdew, could you provide the full stack trace of the issue as this provide more information about the crash?

**Comment by morganchen12** [comment]
The Crashlytics symbols in this stack trace are crash recording calls and occur after the call to `std::terminate()`, so they're likely not the cause of the crash. You should try to reproduce this crash via standard memory debugging tools; without additional information, it's not possible for us to provide further assistance.
