### ISSUE TITLE
Update minimum supported versions across platforms

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#10100]
Xcode 14 updates to the following minimums: iOS 11, macOS 10.13, tvOS 11.

Update Firebase to the same minimums in the next major release.

**Comment by thedogrex** [comment]
LOL

**Comment by ncooke3** [comment]
@paulb777, starting work on this. I updated the title and description to remove iOS 11 requirement.

**Comment by ncooke3** [comment]
Fixed in https://github.com/firebase/firebase-ios-sdk/pull/10233
