### ISSUE TITLE
FirebaseCoreInternal - got some errors in `RingBuffer`

### ISSUE THREAD

**Issue by AditMulyadi** [firebase/firebase-ios-sdk#10115]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a GitHub issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0.1
  * Firebase SDK version: 9.4.1
  * Installation method: `Swift Package Manager`
  * Firebase Component: (Auth, Core)
  * Target platform(s): iOS 

### [REQUIRED] Step 2: Describe the problem
I got some errors in `RingBuffer.swift` when I build my project. I tried to change the installation method to Pod but still same.
![image](https://user-images.githubusercontent.com/20674084/185499902-0e9fffcc-dde8-4ac6-b450-780d634aafad.png)

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by ncooke3** [comment]
Hi @AditMulyadi, I believe the issue is related to the Xcode version being used. [Firebase 9 requires Xcode 13.3.1](https://firebase.google.com/docs/ios/setup#prerequisites).
