### ISSUE TITLE
Firebase Analytics iOS BUG

### ISSUE THREAD

**Issue by gizemgizg** [firebase/firebase-ios-sdk#10111]
Hi. We defined multiple properties in the analytics account and then disabled the Firebase Analytics account and then re-enabled it to do everything from scratch. At the moment, events that do not have equivalents on the iOS side appear, such as rHa, yFa, Fja. Can you help me?

![image](https://user-images.githubusercontent.com/64318805/185371546-b8c38152-bbe5-4024-af49-1f54145ae4a2.png)

https://github.com/firebase/flutterfire/issues/9370

**Comment by morganchen12** [comment]
Hi @gizemgizg, for project-related issues please contact [Firebase Support](https://firebase.google.com/support).
