### ISSUE TITLE
Firebase Auth TenantID is ignored when set to secondary Firebase App

### ISSUE THREAD

**Issue by bannzai** [firebase/firebase-ios-sdk#10121]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 13.4.1 (13F100
  * Firebase SDK version: 9.4.1
  * Installation method: `Swift Package Manager`
  * Firebase Component: Auth
  * Target platform(s): `iOS`

### [REQUIRED] Step 2: Describe the problem
We are [configure two Firebase Project](https://firebase.google.com/docs/projects/multiprojects) and want to use Firebase Auth with multi tenant to secondary Firebase App. 
When call authentification method with below code, however tenantID is not set on request body to send `https://www.googleapis.com/identitytoolkit/v3/relyingparty/signupNewUser?key=${API_KEY}` endpoint

```swift
let auth = Auth.auth(app: secondaryApp)
auth.tenantID = ${TENANT_ID} // <- Ignored TENANT_ID
auth.signInAnonymously()
```

Incidentally, if the tenantID is not set, signInAnonymously will succeed. There is nothing wrong for instantiate Firebase App.
And also confirms tenantID is set in the default app is no problem. Like below code.

```swift
let auth = Auth.auth() // Use default value
auth.tenantID = ${TENANT_ID} // <- TENANT_ID set to request body
auth.signInAnonymously()
```

#### Steps to reproduce:
- Prepare two Firebase Project
- Configure for multi tenancy on GCP project for secondary firebase app.
- Configure two firebase project with `FirebaseApp.configure()` and `FirebaseApp.configure(options: secondaryFirebaseAppOptoins)`
- Instantiate FirebaseApp for secondary firebase project and call to `auth.signInAnonymously()`

#### Relevant Code:
```swift
guard let filePath = Bundle.main.path(forResource: "Secondary-GoogleService-Info", ofType: "plist"),
  let options = FirebaseOptions(contentsOfFile: filePath) else {
    fatalError("Required secondary firebase project setting file")
}
FirebaseApp.configure(name: "Secondary", options: options)
```

```swift
let secondaryApp = FirebaseApp.app(name: "Secondary")!
let auth = Auth.auth(app: secondaryApp)
auth.tenantID = ${TENANT_ID}
auth.signInAnonymously()
```

**Comment by rizafran** [comment]
Hi @bannzai, it looks like this issue is related to the other ticket you filed. Just want to know if the result of the printed value of `auth.tenantID` without setting a `tenantID` into it was `nil` or still the old `tenantID`?
