### ISSUE TITLE
TenantID is not clear after logout on keychain

### ISSUE THREAD

**Issue by bannzai** [firebase/firebase-ios-sdk#10122]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 13.4.1 (13F100
  * Firebase SDK version: 9.4.1
  * Installation method: `Swift Package Manager`
  * Firebase Component: Auth
  * Target platform(s): `iOS`

### [REQUIRED] Step 2: Describe the problem

I found strange behaviour about when sign out after call `auth.signOut`, however tenantID is not clear on keychain. 
This caused problems when developing [multi-tenant configurations](https://firebase.google.com/docs/projects/multiprojects). 

My scenario: First, I develop signIn with tenantID. But I wrong to choose firebase project and use to auth. I signOut and fix code to use correct firebase project for auth and I reconfigure tenants on GCP console.
After reconfiguration for multi-tenant, I retry signIn same app however I got error for `INVALID_TENANTID`.
This has made me aware of a strange behavior.

 I ran the code and it appears that the old TenantID is restored in the below code on link.
https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseAuth/Sources/User/FIRUser.m#L351

```swift
NSString *tenantID = [aDecoder decodeObjectOfClass:[NSString class] forKey:kTenantIDCodingKey];
```

#### Steps to reproduce:
- Prepare two Firebase Project
- Configure for multi tenancy on GCP project for both firebase app.
- Configure two firebase project with FirebaseApp.configure() and FirebaseApp.configure(options: secondaryFirebaseAppOptoins)
- Instantiate FirebaseApp for **default** firebase project and set tenantID and call to auth.signInAnonymously()
- Call `auth.signOut` 
- App process kill.
- Instantiate FirebaseApp for **secondary** firebase project and set tenantID and call to auth.signInAnonymously()
  - Set tenantID is not required. But it is clearer this behaviour.
- Get INVALID_TENANTID

#### Relevant Code:
First, setup firebase apps.
```swift
FirebaseApp.configure()

guard let filePath = Bundle.main.path(forResource: "Secondary-GoogleService-Info", ofType: "plist"),
  let options = FirebaseOptions(contentsOfFile: filePath) else {
    fatalError("Required secondary firebase project setting file")
}
FirebaseApp.configure(name: "Secondary", options: options)
```

Second, call signIn and signOut for `default` firebase app.
```swift
FirebaseApp.app()!
let auth = Auth.auth()
auth.tenantID = ${DEFAULT_APP_TENANT_ID}
try await auth.signInAnonymously()
...
try auth.signOut()
```

Second, call signIn and signOut for `secondary` firebase app.
```swift
let secondaryApp = FirebaseApp.app(name: "Secondary")!
let auth = Auth.auth(app: secondaryApp)
auth.tenantID = ${DEFAULT_APP_TENANT_ID}
try await auth.signInAnonymously()
...
try auth.signOut()
````

**Comment by rizafran** [comment]
Thanks for reporting this, @bannzai. I'm currently trying to reproduce the issue. To make sure that we're on the same page, could you confirm if you're also getting this same behavior: when calling `signInAnonymously()` for the secondary project, the old uid is still being returned and the uid is not being added in the specified `tenant_id` from the console.
