### ISSUE TITLE
 Crashlytics : iOS Crash : CoreFoundation -[NSOrderedSet initWithSet:copyItems:]

### ISSUE THREAD

**Issue by Nehacdew** [firebase/firebase-ios-sdk#10125]
### Step 0: Are you in the right place?
yes

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: ___13.2__
  * Firebase SDK version: 9.2
  * Installation method: CocoaPods
  * Firebase Component: Database, Firestore, Messaging, Storage
  * Target platform(s): ios
#### Steps to reproduce:
App getting crash.
unable to reproduce the crash.

#### Relevant Code:
Crashlytics : iOS Crash : CoreFoundation -[NSOrderedSet initWithSet:copyItems:]

Crash Item	:	Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x13296c __exceptionPreprocess
1  libobjc.A.dylib                0x6028 objc_exception_throw
2  CoreFoundation                 0x30dcc -[NSOrderedSet initWithSet:copyItems:]
3  UIKitCore                      0xa72c24 -[UIResponder doesNotRecognizeSelector:]
4  CoreFoundation                 0x137048 forwarding
5  CoreFoundation                 0x1393a0 _CF_forwarding_prep_0
6  UltraSDK                       0x3a698 _hidden#2304 + 52 (_hidden#2295:52)
7  libdispatch.dylib              0x1b7c _dispatch_call_block_and_release
8  libdispatch.dylib              0x2fd8 _dispatch_client_callout
9  libdispatch.dylib              0xecc8 _dispatch_main_queue_callback_4CF
10 CoreFoundation                 0xadcc8 CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE
11 CoreFoundation                 0xa8a24 __CFRunLoopRun
12 CoreFoundation                 0xa7f40 CFRunLoopRunSpecific
13 GraphicsServices               0x3534 GSEventRunModal
14 UIKitCore                      0xa43a60 UIApplicationMain
15 TCPApp                         0xbad894 main + 39 (AppDelegate.swift:39)
16 libdyld.dylib                  0xe18 start

// TODO(you): code here to reproduce the problem
NO
```

**Comment by Nehacdew** [comment]
@rizafran  I got this crash from firebase crashlytics and these are complete stack.
  I think this crash related to CoreFoundation.

**Comment by morganchen12** [comment]
Hi @Nehacdew, the line causing your crash belongs to `UltraSDK`.

```
UltraSDK 0x3a698 _hidden#2304 + 52 (_hidden#2295:52)
```

Closing this since it's not a Firebase crash.
