### ISSUE TITLE
Unable to install app on device when adding `FirebaseAnalyticsOnDeviceConversion` via SPM

### ISSUE THREAD

**Issue by gbrixey** [firebase/firebase-ios-sdk#10126]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: `13.4.1 (13F100)`
  * Firebase SDK version: `9.4.1`
  * Installation method: `Swift Package Manager`
  * Firebase Component: `FirebaseAnalyticsOnDeviceConversion`
  * Target platform(s): `iOS`

#### Steps to reproduce:

- Integrate Firebase into the app using Swift Package Manager.
- Add `FirebaseAnalyticsOnDeviceConversion` to the app target.
- Run the app on a connected device.
- Xcode will fail to install the app on device, and will present an error message similar to the following:

```
Unable to install "(App Name)"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620375
User Info: {
    DVTErrorCreationDateKey = "2022-08-22 18:17:24 +0000";
    IDERunOperationFailingWorker = IDEInstalliPhoneLauncher;
}
--
The code signature version is no longer supported.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620375
...
```
[See the full text of the error message here.](https://github.com/firebase/firebase-ios-sdk/files/9396733/xcode_issue.txt)

This error only appears when running the app on a physical device; there is no such error when running on simulator.

This issue is similar to another one that was reported and closed recently: https://github.com/firebase/firebase-ios-sdk/issues/9938. The repro steps are slightly different for me, as I am using SPM and I am not attempting to embed `FirebaseAnalyticsOnDeviceConversion`. The Firebase SDK version is also different.

**Comment by paulb777** [comment]
Thanks for the report. It's being tracked internally at b/242914978

**Comment by morganchen12** [comment]
@gbrixey can you share your project? We suspect this issue occurs when SPM links a static dependency into your app target and then extraneously bundles it into your app bundle as well. The bundled library is unsigned, which causes errors when deploying to device (unsigned bundles can run fine on simulator).

**Comment by gbrixey** [comment]
@morganchen12 sure, I was able to reproduce the issue with a simple test project: [FirebaseSPMTest.zip](https://github.com/firebase/firebase-ios-sdk/files/9409718/FirebaseSPMTest.zip)

**Comment by morganchen12** [comment]
Thanks @gbrixey, the culprit seems to be `GoogleAppMeasurementOnDeviceConversion`, which is copied into the app bundle during the `Build target FirebaseSPMTest` stage of the build process:

```
Copy /Users/morganchen/Library/Developer/Xcode/DerivedData/FirebaseSPMTest-fyqgnspyuddtyjarwmojoxsoezpw/Build/Products/Debug-iphonesimulator/FirebaseSPMTest.app/Frameworks/GoogleAppMeasurementOnDeviceConversion.framework /Users/morganchen/Library/Developer/Xcode/DerivedData/FirebaseSPMTest-fyqgnspyuddtyjarwmojoxsoezpw/SourcePackages/artifacts/GoogleAppMeasurement/GoogleAppMeasurementOnDeviceConversion.xcframework/ios-arm64_i386_x86_64-simulator/GoogleAppMeasurementOnDeviceConversion.framework (in target 'FirebaseSPMTest' from project 'FirebaseSPMTest')
    cd /Users/morganchen/Downloads/FirebaseSPMTest
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -exclude Headers -exclude PrivateHeaders -exclude Modules -exclude \*.tbd -resolve-src-symlinks /Users/morganchen/Library/Developer/Xcode/DerivedData/FirebaseSPMTest-fyqgnspyuddtyjarwmojoxsoezpw/SourcePackages/artifacts/GoogleAppMeasurement/GoogleAppMeasurementOnDeviceConversion.xcframework/ios-arm64_i386_x86_64-simulator/GoogleAppMeasurementOnDeviceConversion.framework /Users/morganchen/Library/Developer/Xcode/DerivedData/FirebaseSPMTest-fyqgnspyuddtyjarwmojoxsoezpw/Build/Products/Debug-iphonesimulator/FirebaseSPMTest.app/Frameworks
```

I haven't figured out how to remove this copy command without excluding `FirebaseAnalyticsOnDeviceConversion` from the binary entirely, but in the short term you can test if this is the source of your build error by removing the framework from your app bundle, re-signing it, and then trying to install it to a device.
