### ISSUE TITLE
[FR]: Set chunk size on upload task

### ISSUE THREAD

**Issue by cclaan** [firebase/firebase-ios-sdk#10137]
### Description

I may be missing something very obvious, but I see no way to set the upload chunk size from swift code for a 'FIRStorageUploadTask' created via FIRStorageReference putFile.
e.g. 
```swift
let uploadTask = remoteRef.putFile(from: fileURL, metadata: metadata)
```

1. Use case: allow custom chunk sizes so resumable uploads work by default
2. Currently the chunk size seems hard coded to a large value 
3. I propose allowing custom chunk sizes

In  [FIRStorageUploadTask.m](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseStorageInternal/Sources/FIRStorageUploadTask.m#L122) the chunk size seems to be set from the constant `kGTMSessionUploadFetcherStandardChunkSize` which is set to LLONG_MAX; 

```swift
    GTMSessionUploadFetcher *uploadFetcher =
        [GTMSessionUploadFetcher uploadFetcherWithRequest:request
                                           uploadMIMEType:strongSelf->_uploadMetadata.contentType
                                                chunkSize:kGTMSessionUploadFetcherStandardChunkSize
                                           fetcherService:self.fetcherService];
```

Perhaps there is a way to modify this somewhere, but I can't find any documentation on it.

Thanks for any support.

### API Proposal

```swift
let uploadTask = remoteRef.putFile(from: fileURL, metadata: metadata, chunkSize: myChunkSize )
```

### Firebase Product(s)

Storage

**Comment by paulb777** [comment]
@cclaan Thank for the feature request.  You're correct that there's currently no way to change `chunkSize` from LLONG_MAX

We've begun work on a Swift-only V2 API for Storage in #10161. `chunkSize` could work well as a default argument in the new API.

**Comment by paulb777** [comment]
@cclaan Would you provide more description about the value of being able to set the `chunkSize`.  Why do you want to be able to manage the upload in smaller chunks?

**Comment by cclaan** [comment]
My use case is uploading ~20mb files from a phone with potentially poor network connection. Using smaller chunks is required so that the upload does not restart from scratch every time the network drops. ( Previously chunkSize was LLONG_MAX )
