### ISSUE TITLE
Crashlytics debug warnings on WatchOS

### ISSUE THREAD

**Issue by skuske** [firebase/firebase-ios-sdk#10133]
### Description

I have added Crashlytics to a WatchOS target, and now I am getting heaps of warnings, all the same conversion issues. Should I just ignore that?

<img width="1161" alt="warnings" src="https://user-images.githubusercontent.com/12996815/186376904-6b5e129e-1d24-4a51-ac33-16e65309060f.png">

### Reproducing the issue

Add Crashlytics to a WatchOS target, compile.

### Firebase SDK Version

9.4.1

### Xcode Version

13.4

### Installation Method

CocoaPods

### Firebase Product(s)

Crashlytics

### Targeted Platforms

watchOS

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml
<!--- Paste the contents of your Podfile.lock *inside* this code block.
  This will be automatically formatted into code.
--->



```

</details>

**Comment by rizafran** [comment]
Hi @skuske, yes, it's safe to ignore those warnings. They may not affect the performance of your app. I'll now be closing this ticket, but feel free to reopen if you have any questions. Thanks.

**Comment by skuske** [comment]
Thanks a lot!  :)
