### ISSUE TITLE
fatal error: 'FirebaseStorage/FirebaseStorage-Swift.h' file not found      #import <FirebaseStorage/FirebaseStorage-Swift.h>

### ISSUE THREAD

**Issue by AcxelAmbrosi** [firebase/firebase-ios-sdk#10135]
### Description

Hello, I have a problem with firebase "@react-native-firebase/storage": "^15.3.0", when running the project I have the following error,
fatal error: 'FirebaseStorage/FirebaseStorage-Swift.h' file not found
     #import <FirebaseStorage/FirebaseStorage-Swift.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

### Reproducing the issue

It won't let me build the project, I have installed the pods and nothing seems to work, I always get the same error.

My podfile 
![Screen Shot 2022-08-24 at 16 38 48](https://user-images.githubusercontent.com/76218095/186528324-56978eaf-1f5c-4e6a-8fac-8e0be716461d.png)

My package.json
![Screen Shot 2022-08-24 at 16 39 06](https://user-images.githubusercontent.com/76218095/186528353-77a497b4-1d0c-4c64-82e3-5ac1fba3b3db.png)

### Firebase SDK Version

9.4.0

### Xcode Version

13.3.1

### Installation Method

CocoaPods

### Firebase Product(s)

Storage

### Targeted Platforms

iOS

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml
<!--- Paste the contents of your Podfile.lock *inside* this code block.
  This will be automatically formatted into code.
--->
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
$FirebaseSDKVersion = '9.4.0'
platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false
$RNFirebaseAsStaticFramework = true
production = ENV["PRODUCTION"] == "1"

target 'appLarviaSupport' do
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseStorageInternal', :modular_headers => true
  pod 'FirebaseAppCheckInterop', :modular_headers => true
  pod 'FirebaseAuthInterop', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true


  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :production => production,
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'appLarviaSupportTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end



```

</details>

**Comment by rizafran** [comment]
Hi @AcxelAmbrosi, I tried to reproduce the issue on native iOS SDK, but I'm unable to get the same error. This seems like a react-native integration issue. With this, I'll be closing the ticket as this might be better to report on https://github.com/invertase/react-native-firebase/issues.

**Comment by paulb777** [comment]
See https://github.com/invertase/react-native-firebase/issues/6382

**Comment by mikehardy** [comment]
Just in case anyone sees this from react-native-firebase:

**you must use `use_frameworks!` (ideally `use_frameworks! :linkage => :static` in your `ios/Podfile` for react-native-firebase v15+**

There are many posting hacks and workarounds to this requirement, but they are not supported. And you will see errors like this if you try them.
