### ISSUE TITLE
Firebase Storage Carthage Binary 9.5.0 built with Apple Swift version 5.6 not version 5.6.1

### ISSUE THREAD

**Issue by rickpasetto** [firebase/firebase-ios-sdk#10140]
### Description

Following the instructions in https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md, and downloading the binary versions of the frameworks for version 9.5.0, I'm getting the following build error in Xcode 13.4.1:

> Failed to build module 'FirebaseStorage'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)', while this compiler is 'Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)'). Please select a toolchain which matches the SDK.

Note this appears to _only_ be a problem with **Firebase Storage**, as all the other frameworks seem to work fine.  I'm guessing it was just an oversight.

(Note also this is a problem with 9.5.0, but I discovered it is a problem in 9.4.0)

### Reproducing the issue

In Xcode 13.4.1, follow the instructions in https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md,
add this to your `Cartfile`:
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseStorageBinary.json" == 9.5.0
```
and have a trivial swift file `import FirebaseStorage`.  You'll see the error pretty quickly.

### Firebase SDK Version

9.5.0

### Xcode Version

13.4.1

### Installation Method

Carthage

### Firebase Product(s)

Storage

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Failed to build module 'FirebaseStorage'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)', while this compiler is 'Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)'). Please select a toolchain which matches the SDK.
```

**Comment by andrewheard** [comment]
Hey @rickpasetto, any chance you forgot to add `FirebaseAnalyticsBinary` to your Cartfile? Should look something like this if you're only using Firebase Storage:
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseStorageBinary.json"
```

I was able to reproduce the same error you reported when omitting `FirebaseAnalyticsBinary` but further down in the error logs it said:
```
.../DerivedData/.../Build/Products/Debug-iphonesimulator/FirebaseStorage.framework/Modules/FirebaseStorage.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:6:8: error: no such module 'FirebaseCore'
import FirebaseCore
       ^
Command EmitSwiftModule failed with a nonzero exit code
```

`FirebaseCore` (and its required frameworks) get downloaded with `FirebaseAnalyticsBinary` so it's required.

**Comment by rickpasetto** [comment]
Unfortunately, no, I am definitely including `FirebaseAnalyticsBinary.json` in my `Cartfile`.  I don't think that's the issue, because all the other libraries work fine except `FirebaseStorage`.

Were you able to confirm that `FirebaseStorageBinary` was indeed compiled with `Swift 5.6.1`?

**Comment by paulb777** [comment]
@rickpasetto FirebaseStorageBinary and everything else in the release was built with Firebase 13.3.1 and `Swift 5.6.0`.

Because of Swift module stability, binaries built on previous versions should continue to work with later versions and do in our testing.

We'll like need a reproducible example to help.

**Comment by rickpasetto** [comment]
I downgraded to a previous binary version and that worked on the version of Xcode I'm using. I'm not sure why this version had problems. I'll close this issue. Thank you for all your help!
