### ISSUE TITLE
isDefaultAppConfigured() can not be accessed anymore to detect if configuration is completed

### ISSUE THREAD

**Issue by Kondamon** [firebase/firebase-ios-sdk#10150]
### Description

Through `FirebaseApp.isDefaultAppConfigured()` you were able to check if an app is already configured to not get an error thrown if the configuration is called twice. Now this API is internal `isDefaultAppConfigured()`. https://github.com/firebase/firebase-ios-sdk/pull/9887 and https://github.com/firebase/firebase-ios-sdk/issues/9884

Due to GDPR there are different use cases that requires FireBaseApp to be disabled and enabled. Or enabled at a later time. Now it's not possible to check anymore if `Firebase.configure()` has already taken place. 

Please make `FirebaseApp.isDefaultAppConfigured()` available again!

### Reproducing the issue

Use Firebase 9.5.0 and call `FirebaseApp.isDefaultAppConfigured()`

### Firebase SDK Version

9.5.0

### Xcode Version

13.4.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Crashlytics, Firestore, Remote Config, Storage

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Type 'FirebaseApp' has no member 'isDefaultAppConfigured'
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reporting, @Kondamon. I've reproduced the issue, and I found out that `isDefaultAppConfigured` is available via `FirebaseCoreExtension` based on this [thread](https://github.com/firebase/firebase-ios-sdk/issues/8783#issuecomment-1093357014).

**Comment by paulb777** [comment]
We don't intend to support `isDefaultAppConfigured()` as part of the public API for reasons discussed in #8783.

See https://firebase.google.com/support/privacy#guides-for-enabling-opt-in-end-user-data-processing for how we document managing user privacy.

**Comment by paulb777** [comment]
Yes. See the implementation at https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseCore/Sources/FIRApp.m#L252
