### ISSUE TITLE
🐛 [cloud_firestore] collectionGroup offline cache

### ISSUE THREAD

**Issue by Shawn-sudo** [firebase/firebase-ios-sdk#10164]
### Description

Fetching documents using collectionGroup() without internet connection throws "unavailable" error in certain circumstances.

I'm from Flutter world, but as https://github.com/firebase/flutterfire/issues/9457#issuecomment-1235368130 suggests, I guess I have to open this network-related issue over here.

### Reproducing the issue

1. Turn off wifi and cellular data (no internet connection) before the app is opened
2. Launch the app
3. Call firestore.collectionGroup("helloo").whereField(...).limit(to: 1234).getDocuments()
4. [cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.

Weirdly, if I do step 1. after doing 2. and 3. (2 --> 3 --> 1 --> ...), further collectionGroup(...).getDocuments() calls don't result in the error and gets docs from the cache as expected.

### Firebase SDK Version

9.4.1

### Xcode Version

13.3.1

### Installation Method

CocoaPods

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reporting, @Shawn-sudo. First off, may I know the expected behavior you'd want to happen for your use case?

**Comment by MarkDuckworth** [comment]
Looks like there are some community defined solutions here: https://github.com/firebase/flutterfire/discussions/5708. But, we will also see if there is something we can do in the iOS SDK to help with this problem.

Can you tell us if you've enabled or disabled persistence with [enablePersistence](https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/FirebaseFirestore/enablePersistence.html) or [persistenceEnabled](https://pub.dev/documentation/cloud_firestore_platform_interface/latest/cloud_firestore_platform_interface/Settings/persistenceEnabled.html)?

Also, it sounds like you are experiencing this issue in a Flutter app targeting iOS? Are you also experiencing this issue when running your app on other platforms, Android or web?

**Comment by Shawn-sudo** [comment]
@rizafran I'm expecting firestore to read documents from cache without internet, even when using `collectionGroup`.

@MarkDuckworth I enabled persistence with [enablePersistence](https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/FirebaseFirestore/enablePersistence.html), as my app doesn't target web platforms.

On iOS simulator: the app just pauses without any alert or "force-quitting-app" behavior. 
On iOS real device: firestore throws an error (service unavailable). `try-catch` code that I wrote in flutter caught the error well, and the app didn't pause. It failed to read the documents tho
On Android simulator: firestore also throws service unavailable error
On Android real device: I don't have one for now

**Comment by MarkDuckworth** [comment]
@Shawn-sudo, the information we have now does not indicate an issue in the firebase-ios-sdk. Given the amount of activity on https://github.com/firebase/flutterfire/discussions/5708, I suspect that the issue is in the FlutterFire SDK or how it is calling firebase-ios-sdk. If there are additional logs showing the activity of the firebase-ios-sdk, we can take a look. Or if there is a minimal reproduce-able example demonstrating this issue with the firebase-ios-sdk, then we can also take another look.

**Comment by Shawn-sudo** [comment]
@MarkDuckworth Can you check if your iOS app can get documents using `collectionGroup` from cache when there's no internet connection? Just to be sure if it works on native iOS.

I have no experience in swift (native iOS) developing, so I think it would be easier if you can check whether it works or not.

**Comment by cherylEnkidu** [comment]
Hi,

By default, a get call will attempt to fetch the latest document snapshot from your database. On platforms with offline support, the client library will use the offline cache if the network is unavailable or if the request times out.

For more information you can use this link as reference: https://firebase.google.com/docs/firestore/query-data/get-data#source_options
