### ISSUE TITLE
[iOS] FireStore keep on using CPU

### ISSUE THREAD

**Issue by shohe** [firebase/firebase-ios-sdk#10168]
### Description

I'm using FireStore at my current iOS project and I realized that when generate `CollectionReference` or `DocumentReference`, FireStore starts keep on using CPU (around 10%) until app close.

I'm using
- Firebase 9.5.0
- install with SwiftPackageManager
- Xcode version 13.4.1 (13F100)

Here is sample code (same as document).
```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
    FirebaseApp.configure()
    let db = Firestore.firestore()
    db.collection("Collection").document("test").setData(["lastLoginAt":Date()], merge: true)

    // Even this code happens issue ↓
    // let ref = db.collection("Collection")

    return true
}
```

![Screen Shot 2022-09-03 at 14 28 41](https://user-images.githubusercontent.com/7777605/188257654-fae1d799-3740-4f62-9b3b-83d1d606220d.jpg)

### Firebase SDK Version

9.5.0

### Xcode Version

13.4.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

**Comment by dconeybe** [comment]
This is actually an issue that we (the Firestore SDK developers) just discovered today. The bug was added in 9.5.0. There is no workaround, except downgrading. The fix will almost certainly be in the next release, which is scheduled for mid-September 2022. Here is the fix: https://github.com/firebase/firebase-ios-sdk/pull/10170.

**Comment by dconeybe** [comment]
FYI Firebase 9.6.0 is now released with the fix.

https://firebase.google.com/support/release-notes/ios#version_960_-_september_13_2022

**Comment by h-unterp** [comment]
@dconeybe Thank you, but I am still unable to move past this bug.

in `/ios/Pods/Local Podspecs/cloud_firestore.podspec.json`
```
"dependencies": {
    "Firebase/Firestore": [
      "9.5.0"
    ]
  },
  "static_framework": true,
  "pod_target_xcconfig": {
    "GCC_PREPROCESSOR_DEFINITIONS": "LIBRARY_VERSION=\\@\\\"3.4.8\\\" LIBRARY_NAME=\\@\\\"flutter-fire-fst\\\"",
    "DEFINES_MODULE": "YES"
  }
}
```
and running build seeing:
```
    [!] CocoaPods could not find compatible versions for pod "FirebaseFirestore":
      In Podfile:
        FirebaseFirestore (from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `9.6.0`)
        cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 3.4.8, which depends on
          Firebase/Firestore (= 9.5.0) was resolved to 9.5.0, which depends on
            FirebaseFirestore (~> 9.5.0)
```
3.4.8 was released after 9.6.0 any idea why I am seeing this? Thank you

**Comment by dconeybe** [comment]
Unfortunately the maintainers of this repository do not support flutterfire. This looks like flutterfire needs to update their dependency on `Firebase/Firestore` to 9.6.0. Please log a bug against flutterfire about this.

**Comment by h-unterp** [comment]
Thank you for the quick response
