### ISSUE TITLE
[Firebase 11] Update Firebase dependencies for Firebase 11's minimum supported versions

### ISSUE THREAD

**Issue by ncooke3** [firebase/firebase-ios-sdk#10187]
### Description

The upcoming Firebase major version release will bump the minimum version for supported platforms. The following dependencies will need updating:
- GoogleUtilities **[edit: released]**
- GoogleDataTransport **[edit: released]**
- nanopb (CocoaPods only) **[edit: released]**
- AppCheckCore **[edit: released]**

### Requirements
- [x] Release new versions for each of the above dependencies. 
- [X] Address relevant outstanding issues in the GDT repos
- [x] Address relevant outstanding issues in the GoogleUtilitiesRepo
- [X] For nanopb, see https://github.com/google/nanopb-podspec/commit/0e46a3b2d88bcd675a39dda818a57eeea7cd0261.
- [X] Update each repo's `Package.swift` and `X.podspec` to reflect new minimum supported versions.
- [X] Update Firebase's dependencies on these SDKs to use the new releases for the pinned lower version.

**Comment by ncooke3** [comment]
When doing GoogleUtilities, address this issue in the major version update: https://github.com/google/GoogleUtilities/issues/40

**Comment by paulb777** [comment]
Punting to Firebase 11 since GoogleUtilities will continue to support iOS 10 past Firebase 10.
