### ISSUE TITLE
[Firebase Firestore] swift Force Load _swiftCompatabilityConcurancy

### ISSUE THREAD

**Issue by waleedkalyar** [firebase/firebase-ios-sdk#10182]
### Description

Hi sir, I have implemented flutter fire inside my flutter project. For reducing time I have added build in C++ libs in Pod file as flutter fire documentation says. But whenever I try to build its give me the error of

Undefined symbol: _swift_FORCE_LOAD$_swiftCompatabilityConcurancy

I am unable to figure out the problem.
Btw it will build if I remove
pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '9.4.0'
from my Pod file. But It will take almost one hour on my MacBook to build.

My OS is -> Mac OS big sure version 11.5.2
My Xcode version is -> 13.0.0
Its become pain in my head to use firebase Firestore. If I remove Firestore dependency build work like charm.
Please help me to sort this problem.

### Firebase SDK Version

9.4.0

### Xcode Version

13.0.0

### Installation Method

CocoaPods

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

### Relevant Log Output

```shell
`  Undefined symbols for architecture x86_64:
      "__swift_FORCE_LOAD_$_swiftCompatibilityConcurrency", referenced from:
          __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseFirestoreSwift in FirebaseFirestoreSwift(CodableErrors.o)
          __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseFirestoreSwift in FirebaseFirestoreSwift(CollectionReference+AsyncAwait.o)
          __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseFirestoreSwift in FirebaseFirestoreSwift(DocumentID.o)
          __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseFirestoreSwift in FirebaseFirestoreSwift(DocumentReference+Codable.o)
          __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseFirestoreSwift in FirebaseFirestoreSwift(DocumentReference+ReadDecodable.o)
          __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseFirestoreSwift in FirebaseFirestoreSwift(DocumentSnapshot+ReadDecodable.o)
          __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseFirestoreSwift in FirebaseFirestoreSwift(ExplicitNull.o)
          ...
         (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseFirestoreSwift)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel

    Result bundle written to path:
        /var/folders/p5/8yd8xy253g78z85733whxz900000gn/T/flutter_tools.ucU7mc/flutter_ios_build_temp_dirtj2olx/temporary_xcresult_bundle


Error (Xcode): Undefined symbol: __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency


Could not build the application for the simulator.
Error launching application on iPhone 11.
`
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

**Comment by rizafran** [comment]
Hi @waleedkalyar, could you try updating your Xcode version? It seems like Firebase 9 requires Xcode 13.3.1 based on the [doc](https://firebase.google.com/docs/ios/setup#prerequisites).

**Comment by waleedkalyar** [comment]
@rizafran  Is there any other solution then updating Xcode version Because My Current OS does not further update the Xcode.
Btw I found solution of this as
When you add an empty swift file, XCode will ask you "Create Bridging Header".

It will include to the Header Search Path on your build settings:

`$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)
$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)`

##So After adding this My Bridge file is like below

`#import "GeneratedPluginRegistrant.h"
$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)
$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)`

But now the following error occur
Error (Xcode): expected function body after function declarator
                    /Volumes/Stuff/flutter_projects/onesite/ios/Runner/Runner-Bridging-Header.h:1:16

**Comment by ncooke3** [comment]
Hi @waleedkalyar, 

Your latest he error reads like a compile time error. Could you share your `/Volumes/Stuff/flutter_projects/onesite/ios/Runner/Runner-Bridging-Header.h`?

Alternatively, rather than adding an empty Swift file and the bridging header, one potential workaround we can try is to manually add `$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)` as the *first* item in your `Header Search Paths` build settings.
