### ISSUE TITLE
Update Firebase dependencies minimum supported versions to iOS 11 etc

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#10184]
### Description

Update GoogleUtilities, GoogleDataTransport, and nanopb.

For nanopb, see https://github.com/google/nanopb-podspec/commit/0e46a3b2d88bcd675a39dda818a57eeea7cd0261.

Confirm that this should be CocoaPods only since other package managers already require iOS 11.

### Firebase SDK Version

9.5.0

### Xcode Version

13.3.1

### Installation Method

CocoaPods

### Firebase Product(s)

All

### Targeted Platforms

iOS, tvOS, watchOS, macOS, macCatalyst

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
Deferring to Firebase 11 since the dependencies will need to support iOS 10 longer than Firebase does.

**Comment by ncooke3** [comment]
Closing in favor of #10187
