### ISSUE TITLE
AnalyticsParameterItems not tracking in AnalyticsEventViewItem and AnalyticsEventSelectItem

### ISSUE THREAD

**Issue by Patrashkov** [firebase/firebase-ios-sdk#10194]
### Description

Hi, have an issue with log params items in the event view_item, you can see the response from the console
using SPM with version 8.0.0
trying log event select_item with the same parameters but in the dubug view I see all without AnalyticsParameterItems

do you have any ideas?

AnalyticsEventViewItem
```
*****[75297:1187151] 8.15.0 - [Firebase/Analytics][I-ACS023051] Logging event: origin, name, params: app,
 view_item, {
    cat = someCat;
    currency = UAH;
    ga_event_origin (_o) = app;
    ga_screen_class (_sc) = MainViewController;
    ga_screen_id (_si) = 4731318632127435877;
    is_hand_made = 0;
    items = (
        {
        "item_id" = 123456789;
    }
);
    product_id = 123456789;
    referrer = main;
    subcat = somePath;
    value = 450;
}
```

AnalyticsEventSelectItem
```
MyProject[75707:1201928] 8.15.0 - [Firebase/Analytics][I-ACS023051] Logging event: origin, name, params: app, select_item, {
    currency = UAH;
    ga_event_origin (_o) = app;
    ga_screen_class (_sc) = ProductDetailsViewController;
    ga_screen_id (_si) = 1564400909670479756;
    items = (
        {
        "item_id" = 12345678;
    }
);
    value = 2285.0;
}
```
![Screenshot 2022-09-09 at 14 40 54](https://user-images.githubusercontent.com/18269516/189342384-d6e6f0f1-a43b-49a5-a767-6b2b628b6ba5.png)
![Screenshot 2022-09-09 at 14 41 05](https://user-images.githubusercontent.com/18269516/189342448-1cec6b9c-fdc6-4d6c-a4b3-f01013e63e35.png)

### Firebase SDK Version

8.0.0

### Xcode Version

13.2.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
2022-09-09 14:17:02.496177+0300 myProject[75297:1187151] 8.15.0 - [Firebase/Analytics][I-ACS023051] Logging event: origin, name, params: app, view_item, {
    cat = cosm;
    currency = UAH;
    ga_event_origin (_o) = app;
    ga_screen_class (_sc) = MainViewController;
    ga_screen_id (_si) = 4731318632127435877;
    is_hand_made = 0;
    items = (
        {
        "item_id" = 123456789;
    }
);
    product_id = 123456789;
    referrer = main;
    subcat = toniki;
    value = 450;
}
2022-09-09 14:17:02.496846+0300 MyProject[75297:1187151] 8.15.0 - [Firebase/Analytics][I-ACS023073] Debug mode is enabled. Marking event as debug and real-time. Event name, parameters: view_item, {
    cat = cosm;
    currency = UAH;
    ga_debug (_dbg) = 1;
    ga_event_origin (_o) = app;
    ga_realtime (_r) = 1;
    ga_screen_class (_sc) = MainViewController;
    ga_screen_id (_si) = 4731318632127435877;
    is_hand_made = 0;
    items = (
        {
        "item_id" = 123456789;
    }
);
    product_id = 123456789;
    referrer = main;
    subcat = toniki;
    value = 450;
}
2022-09-09 14:17:02.503094+0300 MyProject[75297:1187151] 8.15.0 - [Firebase/Analytics][I-ACS023072] Event logged. Event name, event params: view_item, {
    cat = cosm;
    currency = UAH;
    ga_debug (_dbg) = 1;
    ga_event_origin (_o) = app;
    ga_realtime (_r) = 1;
    ga_screen_class (_sc) = MainViewController;
    ga_screen_id (_si) = 4731318632127435877;
    is_hand_made = 0;
    items = (
        {
        "item_id" = 123456789;
    }
);
    product_id = 123456789;
    referrer = main;
    subcat = toniki;
    value = 450;
}

2022-09-09 14:35:40.241997+0300 MyProject[75707:1201928] 8.15.0 - [Firebase/Analytics][I-ACS023051] Logging event: origin, name, params: app, select_item, {
    currency = UAH;
    ga_event_origin (_o) = app;
    ga_screen_class (_sc) = ProductDetailsViewController;
    ga_screen_id (_si) = 1564400909670479756;
    items = (
        {
        "item_id" = 12345678;
    }
);
    value = 2285.0;
}
```

### If using Swift Package Manager, the project's Package.resolved

{
  "object": {
    "pins": [
      {
        "package": "abseil",
        "repositoryURL": "https://github.com/firebase/abseil-cpp-SwiftPM.git",
        "state": {
          "branch": null,
          "revision": "583de9bd60f66b40e78d08599cc92036c2e7e4e1",
          "version": "0.20220203.2"
        }
      },
      {
        "package": "AppAuth",
        "repositoryURL": "https://github.com/openid/AppAuth-iOS.git",
        "state": {
          "branch": null,
          "revision": "33660c271c961f8ce1084cc13f2ea8195e864f7d",
          "version": "1.5.0"
        }
      },
      {
        "package": "AppsFlyerLib",
        "repositoryURL": "https://github.com/AppsFlyerSDK/AppsFlyerFramework.git",
        "state": {
          "branch": null,
          "revision": "3c77b7ec3ad5991868837c5ac8085882310a4cd0",
          "version": "6.8.0"
        }
      },
      {
        "package": "AssetsPickerViewController",
        "repositoryURL": "https://github.com/DragonCherry/AssetsPickerViewController.git",
        "state": {
          "branch": null,
          "revision": "288cf078a78fb9f590fc8519d88b4b87089f3103",
          "version": "2.9.7"
        }
      },
      {
        "package": "BoringSSL-GRPC",
        "repositoryURL": "https://github.com/firebase/boringssl-SwiftPM.git",
        "state": {
          "branch": null,
          "revision": "dd3eda2b05a3f459fc3073695ad1b28659066eab",
          "version": "0.9.1"
        }
      },
      {
        "package": "Facebook",
        "repositoryURL": "https://github.com/facebook/facebook-ios-sdk.git",
        "state": {
          "branch": null,
          "revision": "e14f349945ba3f9516e3292107f42be19fe9fbe5",
          "version": "12.3.2"
        }
      },
      {
        "package": "Firebase",
        "repositoryURL": "https://github.com/firebase/firebase-ios-sdk.git",
        "state": {
          "branch": null,
          "revision": "111d8d6ad1a1afd6c8e9561d26e55ab1e74fcb42",
          "version": "8.15.0"
        }
      },
      {
        "package": "GoogleAppMeasurement",
        "repositoryURL": "https://github.com/google/GoogleAppMeasurement.git",
        "state": {
          "branch": null,
          "revision": "ef819db8c58657a6ca367322e73f3b6322afe0a2",
          "version": "8.15.0"
        }
      },
      {
        "package": "GoogleDataTransport",
        "repositoryURL": "https://github.com/google/GoogleDataTransport.git",
        "state": {
          "branch": null,
          "revision": "5056b15c5acbb90cd214fe4d6138bdf5a740e5a8",
          "version": "9.2.0"
        }
      },
      {
        "package": "GoogleSignIn",
        "repositoryURL": "https://github.com/google/GoogleSignIn-iOS",
        "state": {
          "branch": null,
          "revision": "9450e779619fc184d360c9f7ce61023587f7e1f4",
          "version": "6.2.2"
        }
      },
      {
        "package": "GoogleUtilities",
        "repositoryURL": "https://github.com/google/GoogleUtilities.git",
        "state": {
          "branch": null,
          "revision": "f4abe56ce62a779e64b525eb133c8fc2a84bbc1f",
          "version": "7.7.1"
        }
      },
      {
        "package": "gRPC",
        "repositoryURL": "https://github.com/grpc/grpc-ios.git",
        "state": {
          "branch": null,
          "revision": "8440b914756e0d26d4f4d054a1c1581daedfc5b6",
          "version": "1.44.3-grpc"
        }
      },
      {
        "package": "GTMSessionFetcher",
        "repositoryURL": "https://github.com/google/gtm-session-fetcher.git",
        "state": {
          "branch": null,
          "revision": "4e9bbf2808b8fee444e84a48f5f3c12641987d3e",
          "version": "1.7.2"
        }
      },
      {
        "package": "GTMAppAuth",
        "repositoryURL": "https://github.com/google/GTMAppAuth.git",
        "state": {
          "branch": null,
          "revision": "b9d1683be336ba8c8d1c6867bafeb056a5399700",
          "version": "1.3.0"
        }
      },
      {
        "package": "Adjust",
        "repositoryURL": "https://github.com/adjust/ios_sdk",
        "state": {
          "branch": null,
          "revision": "881842eb3b8f7d2920d962de95e75b27162c83ef",
          "version": "4.31.0"
        }
      },
      {
        "package": "IQKeyboardManagerSwift",
        "repositoryURL": "https://github.com/hackiftekhar/IQKeyboardManager.git",
        "state": {
          "branch": null,
          "revision": "474f849accae40fe61b5302d9b057dd48ee073ba",
          "version": "6.5.9"
        }
      },
      {
        "package": "JVFloatLabeledTextField",
        "repositoryURL": "https://github.com/jverdi/JVFloatLabeledTextField",
        "state": {
          "branch": null,
          "revision": "69c0e80a2d0b9dac52ec37a164c9c5fe0e901038",
          "version": "1.2.5"
        }
      },
      {
        "package": "leveldb",
        "repositoryURL": "https://github.com/firebase/leveldb.git",
        "state": {
          "branch": null,
          "revision": "0706abcc6b0bd9cedfbb015ba840e4a780b5159b",
          "version": "1.22.2"
        }
      },
      {
        "package": "Lottie",
        "repositoryURL": "https://github.com/airbnb/lottie-ios",
        "state": {
          "branch": null,
          "revision": "b04b773957e3e359730590c2e7c16d8c3874ec50",
          "version": "3.4.1"
        }
      },
      {
        "package": "nanopb",
        "repositoryURL": "https://github.com/firebase/nanopb.git",
        "state": {
          "branch": null,
          "revision": "7ee9ef9f627d85cbe1b8c4f49a3ed26eed216c77",
          "version": "2.30908.0"
        }
      },
      {
        "package": "ObjectMapper",
        "repositoryURL": "https://github.com/tristanhimmelman/ObjectMapper.git",
        "state": {
          "branch": null,
          "revision": "0b96a734de3ea1c87374ae677064f86adb0716ec",
          "version": "4.2.0"
        }
      },
      {
        "package": "Promises",
        "repositoryURL": "https://github.com/google/promises.git",
        "state": {
          "branch": null,
          "revision": "3e4e743631e86c8c70dbc6efdc7beaa6e90fd3bb",
          "version": "2.1.1"
        }
      },
      {
        "package": "Reachability",
        "repositoryURL": "https://github.com/ashleymills/Reachability.swift",
        "state": {
          "branch": null,
          "revision": "c01bbdf2d633cf049ae1ed1a68a2020a8bda32e2",
          "version": "5.1.0"
        }
      },
      {
        "package": "Realm",
        "repositoryURL": "https://github.com/realm/realm-cocoa.git",
        "state": {
          "branch": null,
          "revision": "7e5c77fd7fbb30259e8e6e6a41f32289f72e0812",
          "version": "10.7.6"
        }
      },
      {
        "package": "RealmDatabase",
        "repositoryURL": "https://github.com/realm/realm-core",
        "state": {
          "branch": null,
          "revision": "018adb3469c2882904febca251778129ef4a9b70",
          "version": "10.7.2"
        }
      },
      {
        "package": "SDWebImage",
        "repositoryURL": "https://github.com/SDWebImage/SDWebImage.git",
        "state": {
          "branch": null,
          "revision": "3e48cb68d8e668d146dc59c73fb98cb628616236",
          "version": "5.13.2"
        }
      },
      {
        "package": "SideMenu",
        "repositoryURL": "https://github.com/jonkykong/SideMenu.git",
        "state": {
          "branch": null,
          "revision": "8bd4fd128923cf5494fa726839af8afe12908ad9",
          "version": "6.5.0"
        }
      },
      {
        "package": "SnapKit",
        "repositoryURL": "https://github.com/SnapKit/SnapKit",
        "state": {
          "branch": null,
          "revision": "f222cbdf325885926566172f6f5f06af95473158",
          "version": "5.6.0"
        }
      },
      {
        "package": "SwiftProtobuf",
        "repositoryURL": "https://github.com/apple/swift-protobuf.git",
        "state": {
          "branch": null,
          "revision": "e1499bc69b9040b29184f7f2996f7bab467c1639",
          "version": "1.19.0"
        }
      },
      {
        "package": "SwiftyBeaver",
        "repositoryURL": "https://github.com/SwiftyBeaver/SwiftyBeaver.git",
        "state": {
          "branch": null,
          "revision": "12b5acf96d98f91d50de447369bd18df74600f1a",
          "version": "1.9.6"
        }
      },
      {
        "package": "SwiftyJSON",
        "repositoryURL": "https://github.com/SwiftyJSON/SwiftyJSON.git",
        "state": {
          "branch": null,
          "revision": "2b6054efa051565954e1d2b9da831680026cd768",
          "version": "4.3.0"
        }
      },
      {
        "package": "SwipeCellKit",
        "repositoryURL": "https://github.com/SwipeCellKit/SwipeCellKit",
        "state": {
          "branch": null,
          "revision": "7219cad3098637176ace311510d11467dbfb9bb0",
          "version": "2.7.1"
        }
      },
      {
        "package": "ThirdPartyMailer",
        "repositoryURL": "https://github.com/vtourraine/ThirdPartyMailer.git",
        "state": {
          "branch": null,
          "revision": "779da6ce0793b461ccbbac2804755c1e29b6fa63",
          "version": "1.8.0"
        }
      }
    ]
  },
  "version": 1
}

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @Patrashkov, it seems like your data were uploading based on your logs, but not showing in the console. With this, please file a ticket through our [support channel](https://firebase.google.com/support) so the team can investigate your project. I'll now be closing this issue.
