### ISSUE TITLE
Async/await missing date when receiving document. 

### ISSUE THREAD

**Issue by alexflm** [firebase/firebase-ios-sdk#10199]
### Description

Good afternoon. 
I noticed a bug in which in some cases a document without data may come.

Brief description of actions
I am using anonymous authentication with keychain persistence. I save the data and delete the application. I re-install the application, the user id is the same as during the first installation, but the data is not loaded on the first launch of the application, the download occurs only on the second launch. When the application is first launched, the model has only the document id specified using `@DocumentID`, and all other properties are nil. 

### Reproducing the issue

**Code with a bug**

**v1**
```
@MainActor
func fetchData() async throws {
	let task: Task<(CourseCongigGQL?, FUser?), Error>(priority: .background) { 		
	        async let courseConfigGQL = apolloService.getCourseConfig()
		async let user = firestoreService.getUser()
		return try await (courseCongigGQL, user)
	}

	self.courseConfigGQL = try await task.value.0
	self.fuser = try await task.value.1
	
	task.cancel()
}
```

**v2**
```
@MainActor
func fetchData() async throws {
	async let courseConfigGQL = apolloService.getCourseConfig()
	async let fuser = firestoreService.getUser()
	self.courseConfigGQL =  try await courseConfigGQL
	self.fuser = try await fuser
}

```

**Code that does not cause problems**
```
@MainActor
func fetchData() async throws {
	self.courseConfigGQL = try await apolloService.getCourseConfig()
	self.fuser = try await firestoreService.getUser()
}
```

### Firebase SDK Version

9.5.0

### Xcode Version

13.4.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by cherylEnkidu** [comment]
Hi alexflm,

Thank you for reporting this issue! Could you please provide minimum repo code snippets or app in order to better assist you? For example, you might want to exclude apolloService in the app. Providing us your implementation of getUser()
function and including code you used to getDocument are also helpful :)

**Comment by alexflm** [comment]
I excluded the apolloService, only one firebaseService.getUser() method worked and the error still persisted. The document is loaded empty only at the first launch, after the application is deleted. At the second start, the data is already there.

I call the loadConfigAndUser() method after authentication in onAppear of the main view of the application.

Looks like I found the cause of the problem. If a delay of 2 seconds is made before the getUser() request, then the request is processed and the data arrives. It looks like the problem is that firestore does not have time to do something when the application starts, and I'm already making a request. The FirebaseApp.configure() method is called at the very beginning in the AppDelegate.


**ResourceManager**
```
    @MainActor
    func loadConfigAndUser() async throws {
        // try await Task.sleep(seconds: 1.5) - SOLVED THE PROBLEM

        async let fuser = try await self.getUser(user: user)
        self.fuser = try await fuser
    }
```

```
    func getUser(user: FirebaseAuth.User) async throws -> FUser? {
        let userInfo = try await firestoreService.getUserInfo(userId: user.uid)
        guard let userInfo = userInfo else { return nil }
        guard let learningCourseDocId = userInfo.learningCourseDocId else { return nil }
        
        async let courses = try await firestoreService.getCourses(userId: user.uid)
        async let exams = firestoreService.getExams(userId: user.uid, courseDocId: learningCourseDocId)
        async let tests = firestoreService.getTests(userId: user.uid, courseDocId: learningCourseDocId)
        
        let data = try await FUser(info: userInfo, courses: courses, exams: exams, tests: tests)
        return data
    }

```

**FirestoreService**
```
    func getCourses(userId: String) async throws -> [FCourse] {
        let snapshot = try await db.collection(.users).document(userId)
            .collection(.courses).getDocuments()
        
        let model: [FCourse] = snapshot.documents.compactMap { try? $0.data(as: FCourse.self) }
        return model
    }
    
    func getUserInfo(userId: String) async throws -> FUserInfo? {
        let model = try await db.collection(.users).document(userId).getDocument(as: FUserInfo?.self)
        return model
    }
```

**Comment by cherylEnkidu** [comment]
Hi,

Please allow me to double check with you to make sure I understand correctly.

So when the app invokes `getUser(user: FirebaseAuth.User)` in both times, the `user`s pass to the function are identical and valid. However, the first time `firestoreService.getUserInfo(userId: user.uid)` returns nil, and the second time it returns the meaning value?

**Comment by alexflm** [comment]
1. I install the app
2. User auth
3. Save some data in firestore
4. I delete the app
5. I'm running for the first time after uninstalling. The user is being authenticated, the user ID is the same.
6. UserInfo returns a document, all fields are nil except for `@DocumentID var docId: String?`

**Console:**
```
FUserInfo(_docId: FirebaseFirestoreSwift.DocumentID<Swift.String>(
     value: Optional("qP4REVTahvXtDxy3lbWrctVN7DE2")),
     id: nil, 
     createdAt: nil, 
     hasPremium: nil,
     learningCourseDocId: nil,
     lives: nil
)
```

8. I launch the application a second time. All data is in place.

**Console:**
```
FUserInfo(_docId: FirebaseFirestoreSwift.DocumentID<Swift.String>(
     value: Optional("qP4REVTahvXtDxy3lbWrctVN7DE2")),
     id: Optional("qP4REVTahvXtDxy3lbWrctVN7DE2"),
     createdAt: Optional(2022-09-09 09:25:07 +0000), 
     hasPremium: Optional(false),
     learningCourseDocId: Optional("gSqa2iNeT6uwTOp4jno5"), 
     lives: nil
)
```

**Model**
```
struct FUserInfo: Codable {
    @DocumentID var docId: String?
    let id: String?
    let createdAt: Date?
    let hasPremium: Bool?
    let learningCourseDocId: String?
    let lives: FLives?
}
```

9. The request is made in onAppear of the main view of the app. If you set a delay of 2 seconds before the request, then the request getUserInfo will contain all the data.

**Comment by cherylEnkidu** [comment]
Hi,

Thank you again for your detailed reproduce steps! The team is going to reproduce it and will keep you updated if we made any progress.

**Comment by cherylEnkidu** [comment]
Hi alexflm,

We think the reason why this is happening is due to the race condition between `Firestore getDocuments` and `Authentication`. Which means when you fetching the data, the backend Authentication might hasn't finished yet. Could you please turn on the debug log? That could also give us more clues on what's happening  here.

**Comment by cherylEnkidu** [comment]
Hi,

The reason why this block of code doesn't cause issue is because the main thread waits on `courseConfigGQL` which allow some time for `Authentication` to complete. 
```
@MainActor
func fetchData() async throws {
	self.courseConfigGQL = try await apolloService.getCourseConfig()
	self.fuser = try await firestoreService.getUser()
}
```

The other possible fix is try to wait until sign in to complete. 

```
@MainActor
    func signIn() async {
      do {
        let authDataResult = try await Auth.auth().signIn(withEmail: email, password: password)
        let user = authDataResult.user
        print("Signed in as user \(user.uid), with email: \(user.email ?? "")")
      }
      catch {
        print("There was an issue when trying to sign in: \(error)")
      }
    }
```

You can also refer to this link for further reading: https://peterfriese.dev/posts/firebase-async-calls-swift/
