### ISSUE TITLE
Firebase Version log message does not match SPM version

### ISSUE THREAD

**Issue by SwiftNativeDeveloper** [firebase/firebase-ios-sdk#10213]
### Description

Firebase 9.4.1 initializes and prints version 9.4.0 in both Crashlytics and Analytics. I assume the same is for other components but I don't use others.

I assume this is getting injected into the code based on the defines in the Package.swift
https://github.com/firebase/firebase-ios-sdk/blob/9.4.1/Package.swift#L22

Expected:
The version number printed to the system console should match the version of the swift package.

Actual:
The version number printed to the system console did NOT match the version of the swift package.

While I understand and acknowledge that the issue doesn't exist in the latest because 1.6.0 == 1.6.0, for future SPM tags, please please please, ensure the version printed in the logs reflects the actual version of the SDK.

Why does this matter? My QA team verifies our SPM integration versions (Firebase as an example) and when available, checks the SDK version logs with what we have documented as integrated. So as a dev lead I documented integration of 9.4.1, however, QA failed our SDK verification because the logs printed 9.4.0.

2022-09-14 09:53:54.692374-0500 ProcessName[3017:569038] [Firebase/Crashlytics] Version 9.4.0
2022-09-14 09:53:56.081405-0500 ProcessName[3017:569266] 9.4.0 - [FirebaseAnalytics][I-XXXXXXXXX] Analytics v.9.4.0 started

### Reproducing the issue

1. Install Firebase SPM
2. Create a Firebase Config and setup the project per Firebase instructions
3. Initialize Firebase Crashlytics and Analytics in ApplicationDelegate
4. Read the log statements that get printed to Xcode outputs / console output

2022-09-14 09:53:54.692374-0500 ProcessName[3017:569038] [Firebase/Crashlytics] Version 9.4.0
2022-09-14 09:53:56.081405-0500 ProcessName[3017:569266] 9.4.0 - [FirebaseAnalytics][I-XXXXXXXXX] Analytics v.9.4.0 started

### Firebase SDK Version

9.4.1

### Xcode Version

Xcode 14.0 Public

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Crashlytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
2022-09-14 09:53:54.692374-0500 ProcessName[3017:569038] [Firebase/Crashlytics] Version 9.4.0
2022-09-14 09:53:56.081405-0500 ProcessName[3017:569266] 9.4.0 - [FirebaseAnalytics][I-XXXXXXXXX] Analytics v.9.4.0 started
```

### If using Swift Package Manager, the project's Package.resolved

<img width="661" alt="Screenshot 2022-09-14 at 10 22 28 AM" src="https://user-images.githubusercontent.com/73653238/190196271-fc3a5c30-1665-43b2-afdb-19dc5dcb8dcb.png">

### If using CocoaPods, the project's Podfile.lock

n/a

**Comment by paulb777** [comment]
Thanks for raising this. We did not update https://github.com/firebase/firebase-ios-sdk/blob/master/Package.swift#L22 in 9.4.1. I'll leave this open to update our patch release process to do so.

**Comment by paulb777** [comment]
updated the release process docs - internal cl/521942646
