### ISSUE TITLE
Cannot install firebase-ios-sdk

### ISSUE THREAD

**Issue by AphroditeSoftware** [firebase/firebase-ios-sdk#10229]
### Description

I am starting an iOS project from scratch and am trying to add the firebase-ios-sdk according to the instructions in the console. I've selected the following setup.

<img width="459" alt="Screen Shot 2022-09-17 at 5 00 27 PM" src="https://user-images.githubusercontent.com/1252838/190879004-b0dbdc53-00e0-465d-9ff5-6ded99f2f773.png">

When I attempt to add the firebase package, I get the following errors: 

<img width="607" alt="Screen Shot 2022-09-17 at 4 54 04 PM" src="https://user-images.githubusercontent.com/1252838/190878963-38e0c3b7-bf4f-4759-9438-8de6b5bc0bb2.png">
 and 
<img width="607" alt="Screen Shot 2022-09-17 at 4 54 04 PM" src="https://user-images.githubusercontent.com/1252838/190878965-ecc18361-3efe-4acf-ba67-5fe458f1f21d.png">

If I select to add anyway, no amount of refreshing caches/updating/quitting Xcode, clearing DerivedData gets me able to move forward. I was hoping to use this for my new app. Help a dev out?

### Reproducing the issue

Create a new iOS project in Xcode, register it in the Firebase console and try to add firebase-ios-sdk package. 

### Firebase SDK Version

9.0.0

### Xcode Version

14.0

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

I cannot find this file

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by AphroditeSoftware** [comment]
I've managed to create it using Xcode 13.

**Comment by r3to** [comment]
For others having the same issue: 
I could install it with Xcode 14 by setting the minimum version to to 9.6.0
