### ISSUE TITLE
Resolve open Firestore Codable Transition issues

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#10257]
### Description

Resolve the unresolved issues when merging #9465

![Screen Shot 2022-09-23 at 3 08 50 PM](https://user-images.githubusercontent.com/73870/192063244-cedf4288-a6e1-420b-ad1e-6d5f807cc5ad.png)

### Firebase SDK Version

10.0.0

### Xcode Version

n/a

### Installation Method

Swift Package Manager

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by andrewheard** [comment]
@morganchen12 I replied on the original [PR](https://github.com/firebase/firebase-ios-sdk/pull/9465#pullrequestreview-1112939577). Most important ones are [1](https://github.com/firebase/firebase-ios-sdk/pull/9465#discussion_r981563012) and [2](https://github.com/firebase/firebase-ios-sdk/pull/9465#discussion_r981572917).
