### ISSUE TITLE
[FR]: To save developer time, SPM manifest file should _only_ use the `exact` version rule for dependencies.

### ISSUE THREAD

**Issue by mblackmon** [firebase/firebase-ios-sdk#10253]
### Description

1. Use case: Opening a Xcode project that uses the Firebase iOS SDK through SPM (Swift Package Manager) locked to a specific version.  This locking is achieved using the `exact` version rule in Xcode.  
For example:
<img width="451" alt="Screenshot_9_23_22__11_59_AM" src="https://user-images.githubusercontent.com/916776/192013531-3ee5a910-8b9b-49e6-8058-6a6eefba716a.png">

2.  Currently when opening a Xcode project specified in step 1, there is a significant delay before you can do _anything_ in the project, such as build.  On a great network, this takes around 10 seconds, but real world use cases seems to average around 30-60 second for my team.  This delay in incurred because Firebase's dependencies are not all locked to `exact` versions, preferring `ranges` and such.  Thus Xcode cannot use it's local cache, and needs to check for a new version for every non `exact` dependency. 

4. Move all dependencies possible to `exact` versions in the [Package file](https://github.com/firebase/firebase-ios-sdk/blob/master/Package.swift).  Thus, the local cache can be used by Xcode, and developers save up to a full minute _every time_ they open a project using the Firebase sdk.

References
[Swift Package Description](https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html)
[The exact rule](https://developer.apple.com/documentation/packagedescription/package/dependency/requirement-swift.enum/exact(_:))

### API Proposal

No api changes needed. 

### Firebase Product(s)

Analytics, Crashlytics

**Comment by mblackmon** [comment]
My suggestion would to give it the label:"Swift Package Manager" , but I'll defer to the other humans.

**Comment by paulb777** [comment]
Thanks for the request.  We'll need to investigate, but at first thought, we'd be hesitant for the reasons documented in the [exact link](https://developer.apple.com/documentation/packagedescription/package/dependency/requirement-swift.enum/exact(_:)) you pointed to, as well as making it harder to accept bug fixes from dependencies.

We will tighten up some of the dependency version ranges in the upcoming 10.0.0 release, but not to `exact`.

We should also investigate if some of the dependencies are significantly slower to evaluate than others.

**Comment by mblackmon** [comment]
That's a fair response.  I would hope with many of the dependencies being owned by the same organization that coordination amongst them could help achieve a better effect.  That is speculative of course.

I appreciate anything you can do to alleviate the issue this is trying to address.

**Comment by paulb777** [comment]
Are you seeing any improvement with the 10.0.0 release?
