### ISSUE TITLE
Error when using `linkWithProvider`

### ISSUE THREAD

**Issue by Lyokone** [firebase/firebase-ios-sdk#10267]
### Description

When using the `linkWithProvider` method and clicking on the "OK" button on the top left corner, the app crash with the following error:
```
Thread 34: "One of IDToken, accessToken, pendingToken, or requestURI must be supplied."
```

![simulator_screenshot_F832AC73-4A77-4405-98BA-97298BE2D5FD](https://user-images.githubusercontent.com/3680002/192483213-270550b5-ff3c-4042-a417-17324633317c.png)

If I don't click on "OK" there are no issues

First reported in https://github.com/firebase/flutterfire/issues/9615

### Reproducing the issue

```
  [currentUser
      linkWithProvider:self.authProvider
            UIDelegate:nil
            completion:^(FIRAuthDataResult *authResult, NSError *error) {
              handleAppleAuthResult(self, arguments, auth, authResult.credential, error, result);
            }];
```

The completion is never called (checked by putting a breakpoint in it

### Firebase SDK Version

9.6.0

### Xcode Version

13.4.1

### Installation Method

CocoaPods

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Thread 34: "One of IDToken, accessToken, pendingToken, or requestURI must be supplied."
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by Albertbol** [comment]
Hey, pretty crucial bug for production, is there any news on this one, basically, your app crashes every time when the user cancels authentication.

**Comment by rizafran** [comment]
Thanks for reporting this. I've tried reproducing the issue and I was able to get the same behavior. Let me check this with the team and see what we can do here.

**Comment by Albertbol** [comment]
Hey, any progress on this one? Pretty crucial bug.
Thanks

**Comment by Albertbol** [comment]
Hey, any action on this?
There was a couple of pull requests already.
https://github.com/flutter/flutter/issues/85785

**Comment by rizafran** [comment]
Sorry for the trouble, @Albertbol. Our engineers are already looking into this issue, but I'll make a follow up about this.

**Comment by rizafran** [comment]
Hello, thanks for your patience. Just to inform you that this issue has been fixed on #10407.

**Comment by Lyokone** [comment]
Thanks for following up :)

**Comment by Albertbol** [comment]
Hey, thank you very much for the fix. Could you estimate when it will be released? It's been almost a month and a half since the report and this bug actually prevents usage of fire_auth (breaks the ios app right away on cancel) so I believe it would have a high priority to be out.

**Comment by paulb777** [comment]
We plan to release it in 10.2.0 the week of November 14th
