### ISSUE TITLE
StoreKit 2 in-app purchases are not logged

### ISSUE THREAD

**Issue by ArthurAlvarez** [firebase/firebase-ios-sdk#10283]
### Description

After updating my iOS app to make in-app purchases through StoreKit 2 APIs, the in_app_purchase event is not showing on analytics.

### Reproducing the issue

- Make an in-app purchase using the new StoreKit 2 API
- Verify dashboards for in_app_purchase events

### Firebase SDK Version

9.2.0

### Xcode Version

14.0.0

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

**Comment by morganchen12** [comment]
@ArthurAlvarez please file a [support ticket](https://firebase.google.com/support) instead, and be prepared to share your project or a sample project that repros the error.
