### ISSUE TITLE
Xcode 14 build error (GoogleMobileAds)

### ISSUE THREAD

**Issue by c-villain** [firebase/firebase-ios-sdk#10298]
### Description

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_JSContext", referenced from:
      objc-class-ref in GoogleMobileAds(GADOMIDLightJSExecutor.o)
ld: symbol(s) not found for architecture x86_64

### Firebase SDK Version

9.6.0, 9.5.0

### Xcode Version

14.0.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

All

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
Please reach out to AdMob support at https://developers.google.com/admob/ios/support.
