### ISSUE TITLE
linkWithCredential does not update user token

### ISSUE THREAD

**Issue by swemail** [firebase/firebase-ios-sdk#10292]
### Description

We're using `react-native-firebase 15.6.0` to 
* Create users with `signInAnonymously`
* Upgrade user with `linkWithCredential(someEmailAndPasswordCredential)`
* Retrieve user token with `getIdToken()` on the current user 
* Send token in request to our emulated backend and there verify it via library `firebase-admin/auth 11.0.1`

Expected:
Token to be valid.

Actually:
`verifyIdToken` fails with "The Firebase ID token has been revoked"

If we after `linkWithCredential` do `signInWithCredential(someEmailAndPasswordCredential)` it works. Is this the expected behaviour? Could not find any mention of that when reading the [firebase documentation](https://firebase.google.com/docs/auth/web/anonymous-auth#convert-an-anonymous-account-to-a-permanent-account) so maybe it's a bug?

### Firebase SDK Version

9.6.0

### Xcode Version

14.0.1

### Installation Method

CocoaPods

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for the report, @swemail. Could you elaborate on what you mean by "_If we after linkWithCredential do signInWithCredential(someEmailAndPasswordCredential) it works._"?

You may also try our [Auth Quickstart](https://github.com/firebase/quickstart-ios/tree/master/authentication) app to test and compare the code for troubleshooting. Otherwise, we would need a sample native iOS app to reproduce the issue.

**Comment by swemail** [comment]
Ok, we use this library via `@react-native-firebase/auth` and maybe I was unclear about that. So we have an anonymous user that we link with email and password credentials but if we do not also signIn with those new credentials we cant use the token we already had for the anonymous user to make request to our backend. I was posting this issue to get clarity if that is the expected behaviour and if so, feel free to close it.

**Comment by rizafran** [comment]
Hi @swemail, upon checking the [doc](https://firebase.google.com/docs/auth/ios/anonymous-auth#convert-an-anonymous-account-to-a-permanent-account), you need to complete the sign-in flow for the user's authentication provider up to, but not including, calling one of the `FIRAuth.signInWith `methods. After you get the credential in `let credential = EmailAuthProvider.credential(withEmail: email, password: password)`, you need to pass the credential on `linkWithCredential:completion` method. You may also try checking the [Auth Quickstart](https://github.com/firebase/quickstart-ios/tree/master/authentication) which includes the flow of linking the Anonymous account to email/password. 

I'll be closing this for now, but feel free to comment if you have any questions.
