### ISSUE TITLE
Sign in With Apple does not contain a DisplayName

### ISSUE THREAD

**Issue by Lyokone** [firebase/firebase-ios-sdk#10306]
### Description

When using Sign In With Apple, following [this guide](https://firebase.google.com/docs/auth/ios/apple), I don't have access to the display name which is always null even if I properly added the scope for accessing the name.

I properly verified that this is the first time this user is Sign In with Apple.

First reported here: https://github.com/firebase/flutterfire/issues/9662

### Reproducing the issue

```obj-c
- (void)authorizationController:(ASAuthorizationController *)controller
    didCompleteWithAuthorization:(ASAuthorization *)authorization
    API_AVAILABLE(macos(10.15), ios(13.0)) {
  if ([authorization.credential isKindOfClass:[ASAuthorizationAppleIDCredential class]]) {
    ASAuthorizationAppleIDCredential *appleIDCredential = authorization.credential;
    NSString *rawNonce = self.currentNonce;
    NSAssert(rawNonce != nil,
             @"Invalid state: A login callback was received, but no login request was sent.");

    if (appleIDCredential.identityToken == nil) {
      NSLog(@"Unable to fetch identity token.");
      return;
    }

    NSString *idToken = [[NSString alloc] initWithData:appleIDCredential.identityToken
                                              encoding:NSUTF8StringEncoding];
    if (idToken == nil) {
      NSLog(@"Unable to serialize id token from data: %@", appleIDCredential.identityToken);
    }

    // Initialize a Firebase credential.
    FIROAuthCredential *credential = [FIROAuthProvider credentialWithProviderID:@"apple.com"
                                                                        IDToken:idToken
                                                                       rawNonce:rawNonce];

    if (self.linkWithAppleUser != nil) {
      [self.linkWithAppleUser linkWithCredential:credential
                                      completion:^(FIRAuthDataResult *authResult, NSError *error) {
                                        handleSignInWithApple(self, authResult, error);
                                      }];

    } else {
      [FIRAuth.auth signInWithCredential:credential
                              completion:^(FIRAuthDataResult *_Nullable authResult,
                                           NSError *_Nullable error) {
                                handleSignInWithApple(self, authResult, error);
                              }];
    }
  }
}

```

The `authorization` object does contain the family name and the given name, but the `FIRAuthDataResult *_Nullable authResult` has an empty displayName

### Firebase SDK Version

9.6.0

### Xcode Version

Version 14.0.1

### Installation Method

CocoaPods

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @Lyokone, it seems that your issue is related to #4393.

**Comment by peterfriese** [comment]
A video explaining how to update the display name is going live tomorrow. In the meantime, check out this code snippet (source: https://bit.ly/SiwA-updateDisplayName):

```swift
func updateDisplayName(for user: User, with appleIDCredential: ASAuthorizationAppleIDCredential, force: Bool = false) async {
    if let currentDisplayName = Auth.auth().currentUser?.displayName, !currentDisplayName.isEmpty {
      // current user is non-empty, don't overwrite it
    }
    else {
      let changeRequest = user.createProfileChangeRequest()
      changeRequest.displayName = appleIDCredential.displayName()
      do {
        try await changeRequest.commitChanges()
        self.displayName = Auth.auth().currentUser?.displayName ?? ""
      }
      catch {
        print("Unable to update the user's displayname: \(error.localizedDescription)")
        errorMessage = error.localizedDescription
      }
    }
  }
```

**Comment by GrishTad** [comment]
> A video explaining how to update the display name is going live tomorrow. In the meantime, check out this code snippet (source: https://bit.ly/SiwA-updateDisplayName):
> 
> ```swift
> func updateDisplayName(for user: User, with appleIDCredential: ASAuthorizationAppleIDCredential, force: Bool = false) async {
>     if let currentDisplayName = Auth.auth().currentUser?.displayName, !currentDisplayName.isEmpty {
>       // current user is non-empty, don't overwrite it
>     }
>     else {
>       let changeRequest = user.createProfileChangeRequest()
>       changeRequest.displayName = appleIDCredential.displayName()
>       do {
>         try await changeRequest.commitChanges()
>         self.displayName = Auth.auth().currentUser?.displayName ?? ""
>       }
>       catch {
>         print("Unable to update the user's displayname: \(error.localizedDescription)")
>         errorMessage = error.localizedDescription
>       }
>     }
>   }
> ```
there is an error saying "Value of type 'ASAuthorizationAppleIDCredential' has no member 'displayName'" in this lin
 changeRequest.displayName = appleIDCredential.displayName()

**Comment by paulb777** [comment]
Based on the comments, this seems to be fixed.
