### ISSUE TITLE
didReceiveRegistrationToken Called twice

### ISSUE THREAD

**Issue by Raja995** [firebase/firebase-ios-sdk#10318]
### Description

didReceiveRegistrationToken is being called twice on first installation, each time with a different fcmToken.

### Firebase SDK Version

9.6.0

### Xcode Version

14.0.1

### Installation Method

CocoaPods

### Firebase Product(s)

Messaging

### Targeted Platforms

iOS

**Comment by rizafran** [comment]
Thanks for reaching out, @Raja995. This seems like an intended behavior. You may check [this](https://github.com/firebase/firebase-ios-sdk/issues/6813#issuecomment-717607006) existing ticket for more info.
