### ISSUE TITLE
Auth.auth().sendSignInLink (xcode compilation error - method not available)

### ISSUE THREAD

**Issue by jyaunches** [firebase/firebase-ios-sdk#1034]
* Xcode version:  9.2
  * Firebase SDK version: 4.9.0
  * Firebase Component: Auth
  * Component version: 4.4.3

### The problem

For the Auth library, I'm unable to call sendSignInLink. I get an xcode compilation error that the method is not available.

![screen shot 2018-04-05 at 5 44 49 pm](https://user-images.githubusercontent.com/372490/38393711-b26d396c-38f9-11e8-9ecf-52c871e99147.png)

I've installed the entire Firebase suite of tools (in case it existed somewhere else?). No luck.

I've referencing this example for how it should work.

https://github.com/firebase/quickstart-ios/blob/7e1bae6dd76994c468bd7e1a1f695d8815e6f2da/authentication/AuthenticationExampleSwift/PasswordlessViewController.swift

#### Steps to reproduce:

Install current firebase Auth cocoapod. Attempt to use Auth.auth().sendSignInLink. Observe xcode compilation error that method is unavailable.

#### Relevant Code:

See above screenshot.

**Comment by paulb777** [comment]
According to the [Change Log](https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/Auth/CHANGELOG.md), `sendSignInLink` was added in FirebaseAuth 4.5.0. Please `pod update` to the latest Firebase 4.11.0 that includes FirebaseAuth 4.5.0.
