### ISSUE TITLE
Storage - new 'putFile' method implementation breaks old code

### ISSUE THREAD

**Issue by alexmomotiuk** [firebase/firebase-ios-sdk#10353]
### Description

The new implementation of 'putFile' method, breaks old code.
If I pass StorageMetadata object with set up 'contentType' to this method, I get crash with error

> FirebaseStorage/StorageUploadTask.swift:68: Fatal error: Internal error enqueueing a Storage task 

because 'path' and 'name' won't be set for metadata object from parameters.

```
  open func putFile(from fileURL: URL,
                    metadata: StorageMetadata? = nil,
                    completion: ((_: StorageMetadata?, _: Error?) -> Void)?) -> StorageUploadTask {
    var putMetadata: StorageMetadata
    if metadata == nil {
      putMetadata = StorageMetadata()
      if let path = path.object {
        putMetadata.path = path
        putMetadata.name = (path as NSString).lastPathComponent as String
      }
    } else {
      putMetadata = metadata!
    }
```

'putData' method has different implementation and works well.

```
open func putData(_ uploadData: Data,
                    metadata: StorageMetadata? = nil,
                    completion: ((_: StorageMetadata?, _: Error?) -> Void)?) -> StorageUploadTask {
    let putMetadata = metadata ?? StorageMetadata()
    if let path = path.object {
      putMetadata.path = path
      putMetadata.name = (path as NSString).lastPathComponent as String
    }
```

### Firebase SDK Version

10

### Xcode Version

14.0.1

### Installation Method

CocoaPods

### Firebase Product(s)

Storage

### Targeted Platforms

iOS

**Comment by maneesht** [comment]
@alexmomotiuk - thank you for looking into this issue and reporting it. I have merged the PR and the fix should be in the next release. In the meantime, if you initialize the metadata before passing it to the `putFile` function, you should be able to bypass the error.

**Comment by jtressle** [comment]
@maneesht how do we fix this issue while we wait for the next release?

**Comment by alexmomotiuk** [comment]
@jtressle don't pass metadata

**Comment by jtressle** [comment]
@alexmomotiuk I require the metadata so I ended up using the putData method.  Hopefully, unit tests can catch this issue in the future.  It's an inconvenience to change code because of oversight.

**Comment by maneesht** [comment]
@jtressle - if you fill the metadata with the proper path and name properties before you pass it to `putFile`, you shouldn't have any issues.
Please see https://github.com/firebase/firebase-ios-sdk/pull/10356/files#diff-8a6fda4f1d223479d5cafa7db5c6ca8f33220cbb93e59e0e3352c23eb8f7e4aeR215

**Comment by jtressle** [comment]
@maneesht can you provide an example?

I'm getting the error `Cannot assign to property: 'name' setter is inaccessible` for both the metadata name and path.  This is how I'm setting the variables.  Ref is my document reference.

`let metadata = StorageMetadata()
  metadata.name = (ref.fullPath as NSString).lastPathComponent as String
  metadata.path = ref.fullPath`

Thanks.

**Comment by maneesht** [comment]
@jtressle - I was mistaken. `name` and `path` are internal only. Please wait until the next release or roll back to a previous version. The next release should be out soon.

**Comment by mikehardy** [comment]
it is possible to make an NSMutableDictionary (alloc + init it), put a "name" entry in there that is the full path, then do initWithDictionary on the FIRStorageMetadata. The name gets copied to path and it all works. Of course that is internal stuff and a workaround and not supported and you accept responsibility etc ;-) just thought I would mention it

**Comment by maneesht** [comment]
Thanks, @mikehardy!
