### ISSUE TITLE
Some iOS Devices are not appearing on `DebugView`

### ISSUE THREAD

**Issue by michaelhenry19** [firebase/firebase-ios-sdk#10361]
### Description

Some iOS Devices are not appearing on the `DebugView` even the debug option is enabled, even they are using they same build version.

### Firebase SDK Version

9.6.0

### Xcode Version

13.3.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.
 {
        "package": "Firebase",
        "repositoryURL": "https://github.com/firebase/firebase-ios-sdk.git",
        "state": {
          "branch": null,
          "revision": "7e80c25b51c2ffa238879b07fbfc5baa54bb3050",
          "version": "9.6.0"
        }
      }
```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @michaelhenry19, please file a ticket through our [Firebase support channel](https://firebase.google.com/support) since this is a console-related issue. I'll be closing this ticket for now.
