### ISSUE TITLE
Duplicate request while the previous one is pending

### ISSUE THREAD

**Issue by NiteshVishwakarma** [firebase/firebase-ios-sdk#10362]
### Description

I have two controllers in the application. Both of them hits Remote Config to fetch data. 

**First Function -**
```swift
public func checkAppUpdates() {
        let remoteConfig = RemoteConfig.remoteConfig()
        let remoteConfigSettings = RemoteConfigSettings()
        remoteConfigSettings.minimumFetchInterval = 0
        remoteConfig.configSettings = remoteConfigSettings
        remoteConfig.fetch { (status, error) in
            if let error = error {
                print(error.localizedDescription)
                return
            }
            if status == .success {
                remoteConfig.activate { [weak self]  _, _ in
                    self?.processUpdate(remoteConfig: remoteConfig)
                }
            }
        }
    }
```
**Second function -**
```swift
func getRemoteConfig(
        completionHandler: @escaping (Result<RemoteConfig, APIError>) -> Void) {
            let remoteConfig = RemoteConfig.remoteConfig()
            let remoteConfigSettings = RemoteConfigSettings()
            remoteConfigSettings.minimumFetchInterval = 0
            remoteConfig.configSettings = remoteConfigSettings
            remoteConfig.fetch { (status, error) in
                if status == .success {
                    RemoteConfig.remoteConfig().activate { _, _ in
                        completionHandler(.success(remoteConfig))
                    }
                } else {
                    let message = error?.localizedDescription ?? StringConstants.GenericError.unknown
                    let error = APIError(
                        code: -100,
                        message: message,
                        type: .other)
                    completionHandler(.failure(error))
                }
            }
        }
```
Usually after 2-3 hits it doesn't work for the whole day.
Sometimes it doesn't work for a week.

### Reproducing the issue

Hit the above function in two class files. (Appdelegate and ViewController respectively) to fetch data. It works for 2-3 times and then it stops fetch data resulting into error.

Error Domain=com.google.remoteconfig.ErrorDomain Code=-114 "FetchError: Duplicate request while the previous one is pending" UserInfo={NSLocalizedDescription=FetchError: Duplicate request while the previous one is pending}

Please provide a solution to this.

### Firebase SDK Version

8.15.0

### Xcode Version

13.4.1

### Installation Method

CocoaPods

### Firebase Product(s)

Remote Config

### Targeted Platforms

iOS

### Relevant Log Output

```shell
[22819:414644] 8.15.0 - [Firebase/RemoteConfig][I-RCN000053] A fetch is already in progress. Ignoring duplicate request.
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

PODS:
  - CryptoSwift (1.4.1)
  - Firebase/Analytics (8.15.0):
    - Firebase/Core
  - Firebase/Core (8.15.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 8.15.0)
  - Firebase/CoreOnly (8.15.0):
    - FirebaseCore (= 8.15.0)
  - Firebase/Crashlytics (8.15.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 8.15.0)
  - Firebase/DynamicLinks (8.15.0):
    - Firebase/CoreOnly
    - FirebaseDynamicLinks (~> 8.15.0)
  - Firebase/Messaging (8.15.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 8.15.0)
  - Firebase/Performance (8.15.0):
    - Firebase/CoreOnly
    - FirebasePerformance (~> 8.15.0)
  - FirebaseABTesting (8.15.0):
    - FirebaseCore (~> 8.0)
  - FirebaseAnalytics (8.15.0):
    - FirebaseAnalytics/AdIdSupport (= 8.15.0)
    - FirebaseCore (~> 8.0)
    - FirebaseInstallations (~> 8.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/MethodSwizzler (~> 7.7)
    - GoogleUtilities/Network (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
    - nanopb (~> 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (8.15.0):
    - FirebaseCore (~> 8.0)
    - FirebaseInstallations (~> 8.0)
    - GoogleAppMeasurement (= 8.15.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/MethodSwizzler (~> 7.7)
    - GoogleUtilities/Network (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
    - nanopb (~> 2.30908.0)
  - FirebaseCore (8.15.0):
    - FirebaseCoreDiagnostics (~> 8.0)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/Logger (~> 7.7)
  - FirebaseCoreDiagnostics (8.15.0):
    - GoogleDataTransport (~> 9.1)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/Logger (~> 7.7)
    - nanopb (~> 2.30908.0)
  - FirebaseCrashlytics (8.15.0):
    - FirebaseCore (~> 8.0)
    - FirebaseInstallations (~> 8.0)
    - GoogleDataTransport (~> 9.1)
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (~> 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - FirebaseDynamicLinks (8.15.0):
    - FirebaseCore (~> 8.0)
  - FirebaseInstallations (8.15.0):
    - FirebaseCore (~> 8.0)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/UserDefaults (~> 7.7)
    - PromisesObjC (< 3.0, >= 1.2)
  - FirebaseMessaging (8.15.0):
    - FirebaseCore (~> 8.0)
    - FirebaseInstallations (~> 8.0)
    - GoogleDataTransport (~> 9.1)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/Reachability (~> 7.7)
    - GoogleUtilities/UserDefaults (~> 7.7)
    - nanopb (~> 2.30908.0)
  - FirebasePerformance (8.15.0):
    - FirebaseCore (~> 8.0)
    - FirebaseInstallations (~> 8.0)
    - FirebaseRemoteConfig (~> 8.0)
    - GoogleDataTransport (~> 9.1)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/ISASwizzler (~> 7.7)
    - GoogleUtilities/MethodSwizzler (~> 7.7)
    - nanopb (~> 2.30908.0)
  - FirebaseRemoteConfig (8.15.0):
    - FirebaseABTesting (~> 8.0)
    - FirebaseCore (~> 8.0)
    - FirebaseInstallations (~> 8.0)
    - GoogleUtilities/Environment (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
  - GoogleAnalytics (3.20.0)
  - GoogleAppMeasurement (8.15.0):
    - GoogleAppMeasurement/AdIdSupport (= 8.15.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/MethodSwizzler (~> 7.7)
    - GoogleUtilities/Network (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
    - nanopb (~> 2.30908.0)
  - GoogleAppMeasurement/AdIdSupport (8.15.0):
    - GoogleAppMeasurement/WithoutAdIdSupport (= 8.15.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/MethodSwizzler (~> 7.7)
    - GoogleUtilities/Network (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
    - nanopb (~> 2.30908.0)
  - GoogleAppMeasurement/WithoutAdIdSupport (8.15.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/MethodSwizzler (~> 7.7)
    - GoogleUtilities/Network (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
    - nanopb (~> 2.30908.0)
  - GoogleDataTransport (9.2.0):
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleSymbolUtilities (1.1.2)
  - GoogleTagManager (7.3.1):
    - FirebaseAnalytics (< 9.0, >= 7.0)
    - GoogleAnalytics (~> 3.17)
    - GoogleUtilitiesLegacy (~> 1.3)
  - GoogleUtilities/AppDelegateSwizzler (7.7.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (7.7.0):
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/ISASwizzler (7.7.0)
  - GoogleUtilities/Logger (7.7.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (7.7.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (7.7.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.7.0)"
  - GoogleUtilities/Reachability (7.7.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (7.7.0):
    - GoogleUtilities/Logger
  - GoogleUtilitiesLegacy (1.3.2):
    - GoogleSymbolUtilities (~> 1.1)
  - lottie-ios (3.4.1)
  - nanopb (2.30908.0):
    - nanopb/decode (= 2.30908.0)
    - nanopb/encode (= 2.30908.0)
  - nanopb/decode (2.30908.0)
  - nanopb/encode (2.30908.0)
  - Parchment (3.2.0)
  - PromisesObjC (2.1.1)
  - RxSwift (6.1.0)
  - SDWebImage (5.13.2):
    - SDWebImage/Core (= 5.13.2)
  - SDWebImage/Core (5.13.2)
  - SwiftLint (0.43.0)
  - WebEngage (5.2.10):
    - WebEngage/Xcode11 (= 5.2.10)
  - WebEngage/Xcode11 (5.2.10)
  - WebEngageGTM (2.0.1):
    - GoogleTagManager
    - WebEngage

DEPENDENCIES:
  - CryptoSwift (= 1.4.1)
  - Firebase/Analytics
  - Firebase/Core
  - Firebase/Crashlytics
  - Firebase/DynamicLinks
  - Firebase/Messaging
  - Firebase/Performance
  - GoogleAnalytics
  - GoogleTagManager (= 7.3.1)
  - lottie-ios
  - Parchment (~> 3.0)
  - RxSwift (= 6.1.0)
  - SDWebImage
  - SwiftLint (= 0.43.0)
  - WebEngage (= 5.2.10)
  - WebEngageGTM (= 2.0.1)

SPEC REPOS:
  trunk:
    - CryptoSwift
    - Firebase
    - FirebaseABTesting
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseCrashlytics
    - FirebaseDynamicLinks
    - FirebaseInstallations
    - FirebaseMessaging
    - FirebasePerformance
    - FirebaseRemoteConfig
    - GoogleAnalytics
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleSymbolUtilities
    - GoogleTagManager
    - GoogleUtilities
    - GoogleUtilitiesLegacy
    - lottie-ios
    - nanopb
    - Parchment
    - PromisesObjC
    - RxSwift
    - SDWebImage
    - SwiftLint
    - WebEngage
    - WebEngageGTM

SPEC CHECKSUMS:
  CryptoSwift: 0bc800a7e6a24c4fc9ebeab97d44b0d5f73a78bd
  Firebase: 5f8193dff4b5b7c5d5ef72ae54bb76c08e2b841d
  FirebaseABTesting: 10cbce8db9985ae2e3847ea44e9947dd18f94e10
  FirebaseAnalytics: 7761cbadb00a717d8d0939363eb46041526474fa
  FirebaseCore: 5743c5785c074a794d35f2fff7ecc254a91e08b1
  FirebaseCoreDiagnostics: 92e07a649aeb66352b319d43bdd2ee3942af84cb
  FirebaseCrashlytics: feb07e4e9187be3c23c6a846cce4824e5ce2dd0b
  FirebaseDynamicLinks: 1dc816ef789c5adac6fede0b46d11478175c70e4
  FirebaseInstallations: 40bd9054049b2eae9a2c38ef1c3dd213df3605cd
  FirebaseMessaging: 5e5118a2383b3531e730d974680954c679ca0a13
  FirebasePerformance: 66eb58c3e3568a0501a9be271c8ff424dea0ff34
  FirebaseRemoteConfig: 2d6e2cfdb49af79535c8af8a80a4a5009038ec2b
  GoogleAnalytics: 01e4c5a04544a3608f93e970ce0817836897c5a5
  GoogleAppMeasurement: 4c19f031220c72464d460c9daa1fb5d1acce958e
  GoogleDataTransport: 1c8145da7117bd68bbbed00cf304edb6a24de00f
  GoogleSymbolUtilities: 631ee17048aa5e9ab133470d768ea997a5ef9b96
  GoogleTagManager: 5cbafc35b0e4db6fc1687a42605eacd3db7edb39
  GoogleUtilities: e0913149f6b0625b553d70dae12b49fc62914fd1
  GoogleUtilitiesLegacy: 5501bedec1646bd284286eb5fc9453f7e23a12f4
  lottie-ios: 016449b5d8be0c3dcbcfa0a9988469999cd04c5d
  nanopb: a0ba3315591a9ae0a16a309ee504766e90db0c96
  Parchment: a43c440b22c8a60f7e0196b74339446d4d1d18ea
  PromisesObjC: ab77feca74fa2823e7af4249b8326368e61014cb
  RxSwift: a834e5c538e89eca0cae86f403f4fbf0336786ce
  SDWebImage: 72f86271a6f3139cc7e4a89220946489d4b9a866
  SwiftLint: 0c645fdc6feed3e390c1701ab3cc669f88b42752
  WebEngage: 66e26326058f16fd3125539010fe60eff1544cb2
  WebEngageGTM: cb0873913c26face60ca196a7d1c68e7ad99a28f

PODFILE CHECKSUM: c121ebab2554a23940dbe9f18b052f62df56c795

COCOAPODS: 1.11.3

**Comment by rizafran** [comment]
Thanks for reaching out, @NiteshVishwakarma. It seems like this is intended since you're calling the two `fetch()` method at the same time (AppDelegate and ViewController respectively). Have you tried making the second fetch call after the completion of the first fetch call?

**Comment by NiteshVishwakarma** [comment]
@rizafran  Thanks for replying. No The fetch requests are called in a time gap of about 1-2mins. When we try to hit from appdelegate, it takes more than 2 mins to get the response. And we also hit View Controller Remote config after 1 min(i.e after login). Still we don't receive any response from server and therefore throws Duplicate Request. I hope you are getting is a requirement on both Appdelegate and ViewController. The appdelegate is responsible to check any new version for application while View Controller get screen based data.

**Comment by rizafran** [comment]
Hi @NiteshVishwakarma, I tried calling the `checkAppUpdates()` in `AppDelegate` and trigger the `getRemoteConfig()` in my `viewController` after clicking a button, but I was able to get the response immediately. The duplicate request error only appeared when I call the two `fetch()` method at the same time. With this, could you try our [Remote Config Quickstart](https://github.com/firebase/quickstart-ios/tree/master/config) and see if the issue will persist? Otherwise, you may provide a sample app for us to reproduce the issue.

**Comment by NiteshVishwakarma** [comment]
@rizafran Hi, thank you for information. We developed a singleton class which will allow to hit remote config 60 secs apart. That resolved the issue.
