### ISSUE TITLE
Upload-symbols fail after update to Xcode14

### ISSUE THREAD

**Issue by jvannoord** [firebase/firebase-ios-sdk#10389]
### Description

After we started building with Xcode 14, the calls to `upload-symbols` started failing repeatedly on the same dSYM files.

This may be similar to https://github.com/firebase/firebase-ios-sdk/issues/10247, but there is an obviously different error.

For CI, we use Jenkins, and the call to `upload-symbols` on the Jenkins server calls `upload-symbols` from a ruby rakefile. But I can achieve the same error, once the app archive is generated, on my own commandline by calling `upload-symbols` directly.

The symbol file that fails to upload (actually, it fails to unzip in course of running `upload-symbols`) is ~220MB. When built with Xcode 13.4, this same file was ~205MB.

If given our dSYM zip file: APPNAME-VERSION.app.dSYM.zip, the output of `unzip -t` from the commandline will include
```
Archive:  dist/APPNAME-VERSION.app.dSYM.zip
    testing: BIGFRAMEWORK.framework.dSYM/   OK
    testing: BIGFRAMEWORK.framework.dSYM/Contents/   OK
    testing: BIGFRAMEWORK.framework.dSYM/Contents/Resources/   OK
    testing: BIGFRAMEWORK.framework.dSYM/Contents/Resources/DWARF/   OK
    testing: BIGFRAMEWORK.framework.dSYM/Contents/Resources/DWARF/BIGFRAMEWORK   OK
```
But while `upload-symbols` is running, the temp folder
`/var/folders/v1/swksd_hj7vn0bc_g5m79njpdc77kb5/T//dist/APPNAME-VERSION.app.dSYM.zip.unzipped/BIGFRAMEWORK.framework.dSYM/Contents/Resources/DWARF` appears to be empty.

This is happening with Firebase 10.0.0, but we also saw it with 9.6.0. The change for us happened along with Xcode 14.

### Reproducing the issue

I have a large zip file I can send, if there is a secure way to do that. I don't have a minimal reproducible case. I think the issue might be related to the size of the symbol file.

I am simply running `upload-symbols` from the command line, where the command looks like
```
../tools/upload-symbols -d -gsp ./Resources/Branding/APPNAME/GoogleService-Info.plist -p ios dist/APPNAME-VERSION.app.dSYM.zip
```

### Firebase SDK Version

10.0.0

### Xcode Version

14.0, 14.0.1, 14.1

### Installation Method

Zip

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
../tools/upload-symbols -d -gsp ./Resources/Branding/APPNAME/GoogleService-Info.plist -p ios dist/APPNAME-VERSION.app.dSYM.zip
upload-symbols 3.13 build 32

Arguments:
Debug mode enabled
Google App ID: GOOGLE_APP_ID
Platform: ios
DSYM Paths: ["dist/APPNAME-VERSION.app.dSYM.zip"]

Inspecting next path: dist/APPNAME-VERSION.app.dSYM.zip
Found archive at path: dist/APPNAME-VERSION.app.dSYM.zip
Inspecting next path: /var/folders/v1/swksd_hj7vn0bc_g5m79njpdc77kb5/T//dist/APPNAME-VERSION.app.dSYM.zip.unzipped/BIGFRAMEWORK.framework.dSYM
Found dSYM at path: /var/folders/v1/swksd_hj7vn0bc_g5m79njpdc77kb5/T//dist/APPNAME-VERSION.app.dSYM.zip.unzipped/BIGFRAMEWORK.framework.dSYM
Begin processing dSYM at /var/folders/v1/swksd_hj7vn0bc_g5m79njpdc77kb5/T//dist/APPNAME-VERSION.app.dSYM.zip.unzipped/BIGFRAMEWORK.framework.dSYM
[CoreSymbolication] In DWARF data from kCSSymbolOwnerDataFaultedFromDiskCSCppFileMemory /var/folders/v1/swksd_hj7vn0bc_g5m79njpdc77kb5/T/dist/APPNAME-VERSION.app.dSYM.zip.unzipped/BIGFRAMEWORK.framework.dSYM/Contents/Resources/DWARF/BIGFRAMEWORKCSCppFileMemory /private/var/folders/v1/swksd_hj7vn0bc_g5m79njpdc77kb5/T/dist/APPNAME-VERSION.app.dSYM.zip.unzipped/BIGFRAMEWORK.framework.dSYM/Contents/Resources/DWARF/BIGFRAMEWORK:
  .debug_line[7bb] file = 9 is not a valid index
vector -- stopping DWARF analysis of /private/var/folders/v1/swksd_hj7vn0bc_g5m79njpdc77kb5/T/dist/APPNAME-VERSION.app.dSYM.zip.unzipped/BIGFRAMEWORK.framework.dSYM/Contents/Resources/DWARF/BIGFRAMEWORK
vector -- stopping DWARF analysis of /var/folders/v1/swksd_hj7vn0bc_g5m79njpdc77kb5/T/dist/APPNAME-VERSION.app.dSYM.zip.unzipped/BIGFRAMEWORK.framework.dSYM/Contents/Resources/DWARF/BIGFRAMEWORK
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by samedson** [comment]
Hey @jvannoord - I'm taking a look at this. In the meantime to unblock yourself, can you try uploading the zipped dSYM files through the console upload flow? If you go to the Missing dSYMs page in Crashlytics we've added a web upload flow.

I believe the problem is from this line:
```
[CoreSymbolication] In DWARF data from kCSSymbolOwnerDataFaultedFromDiskCSCppFileMemory /var/folders/v1/swksd_hj7vn0bc_g5m79njpdc77kb5/T/dist/APPNAME-VERSION.app.dSYM.zip.unzipped/BIGFRAMEWORK.framework.dSYM/Contents/Resources/DWARF/BIGFRAMEWORKCSCppFileMemory /private/var/folders/v1/swksd_hj7vn0bc_g5m79njpdc77kb5/T/dist/APPNAME-VERSION.app.dSYM.zip.unzipped/BIGFRAMEWORK.framework.dSYM/Contents/Resources/DWARF/BIGFRAMEWORK:
  .debug_line[7bb] file = 9 is not a valid index
```

It would be awesome to get the affected dSYM - would you be willing to send it through [Firebase Support](https://firebase.google.com/support/troubleshooter/contact) ?

**Comment by jvannoord** [comment]
@samedson Thank you very much for taking the time. I'm currently working on getting Google Developer access for my account. And will remove this message once I have something uploaded.

**Comment by jvannoord** [comment]
@samedson A co-worker has submitted some data via support: Case 10202131.

I was able to use the web interface to upload the zip file. However, if it failed in the same way described here after the upload, I wouldn't know.

**Comment by samedson** [comment]
@jvannoord - I've reproduced it locally - thank you for sending that in. 

I'm not yet finding the root cause, but still digging into it. I'm going to explain a bit more details just to give you some context about this issue:

 - We periodically get bugs like this where the dSYM is not converting with upload-symbols. This manifests in a cSYM without file names. Right now our backend rejects this because you'd get stacktraces without file names, which would be a bad experience.
 - The problem in the dSYM file is usually a few of the symbols inside of it are malformed. We'd like to design a symbol uploader that skips over these malformed lines, but the problem actually lies in the CoreSymbolication library we depend on. CoreSymbolication provides the APIs to enumerate the files in the dSYM, but unfortunately the library handles errors by backing out entirely.
 - As an alternative solution, we built the web dSYM uploader. This uploader uses an entirely different symbol converter and has shown to skip over malformed lines without stopping dSYM conversion.
 
It's been very difficult to identify root causes to these malformed dSYMs. In some cases we even have customers report that their next app version solves the problem, without any change to Xcode version. A few things we suggest:
  - Check if the code stripping configurations for your app have changed. Code stripping shouldn't impact the dSYM's symbols in most cases
  - Try a non-beta Xcode if you're on one

**Comment by samedson** [comment]
Also, were you able to get symbolicated crash reports after uploading via the web?

**Comment by jvannoord** [comment]
@samedson Thanks for all that info! Very helpful.

I used `dwarfdump` on the dSYMS that were generated by Xcode 14.1 RC 2, and I did indeed emit a bunch of errors on a specific framework's DWARF file. So I guess the DWARF file is already messed up before it gets to you all.

I have NOT verified that we get symbolicated reports from the one framework after uploading via the web. I just haven't got that set up. But I'm guessing that we won't get reports, since the `dwarfdump` data indicates an issue. For the moment, we're still using Xcode 13.4 for all the shipping stuff because that toolchain doesn't seem to generate this error. 

Meanwhile, I'll try a few things:
  * strip symbols from other linked frameworks whose symbols may not be necessary
  * break up the framework in to smaller frameworks
  * yell at Xamarin again (we're a native iOS app that links in a xamarin library)

**Comment by jvannoord** [comment]
Versions of things, FYI:

```
jvannoord $ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

jvannoord $ dwarfdump --version
Apple LLVM version 14.0.0 (clang-1400.0.29.202)
  Optimized build.
  Default target: x86_64-apple-darwin21.6.0
  Host CPU: skylake
```

I'm running on an Intel Mac.

**Comment by jvannoord** [comment]
The more we work with this, the more it appears that the issue is not anything in particular due to Firebase Crashlytics tools as it is with Xcode 14 tooling, our build settings, and/or our own binaries. We're still looking in to it.

**Comment by jvannoord** [comment]
The issue was identified and fixed on our end. We have successfully uploaded new bits from an Xcode14-built binary.

For us, the issue appeared to be a `BCSymbolMap` folder in a third-party xcframework, which had been build with Xcode 13.x. `fastlane` uses these `BCSymbolMap`s to [help with symbol processing](https://github.com/fastlane/fastlane/blob/master/gym/lib/gym/runner.rb#L164-L222). Either the existence or the content of these BCSymbolMap files (or there was there an interesting change to `dsymutil`?) caused the dSYM problem that prompted us to open this issue.

Once we rebuilt that other xcframework using Xcode 14.1, that framework's `BCSymbolMap` folder no longer existed, and fastlane (and/or dsymutil) seems to behave.

We now have Xcode 14.1 on our CI server, and we consider this issue closed.

[samedson](https://github.com/samedson), Thank You so much for taking the time to look in to this.

**Comment by samedson** [comment]
Wow that's really interesting - thank you so much for reporting back. We've been trying to track down these types of issues for years so it's really helpful that we at least have one resolution case.

Seems like dependencies built with mismatched Xcode versions is something we need to watch out for. Seems hard for developers to follow that at the rate that major Xcode releases happen.
