### ISSUE TITLE
Sandbox blocking firebase macOS Monterey Swift

### ISSUE THREAD

**Issue by wawilliams003** [firebase/firebase-ios-sdk#10419]
### Description

I am using firebase realtime database as my backend in my IOS app. The app is working great on my older MacBook Pro 2014 (macOS Big Sur), when the app loads I am able to fetch data from firebase. But I am unable to fetch data from firebase on the new 2021 MacBook Pro 16 inches running (macOS Monterey). The app loads, but unable to fetch data from firebase, I am getting error: **[Sandbox] Could not enable Mach bootstrap, errno = 22**. I am using the latest version of firebase SDK, Any help would be appreciated.

### Firebase SDK Version

10.0

### Xcode Version

14.0.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Database

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by maneesht** [comment]
@wawilliams003 have you tried restarting the simulator?
