### ISSUE TITLE
Signing for "gRPC-C++-gRPCCertificates-Cpp" requires a development team with KMP and Cocoapods integration

### ISSUE THREAD

**Issue by mpivchev** [firebase/firebase-ios-sdk#10411]
### Description

I have the following cocoapods integration section in my shared code build.gradle. This is part of the [CocoaPods integration with KMM](https://kotlinlang.org/docs/native-cocoapods.html)

```
  cocoapods {
        summary = ""
        homepage = ""
        framework {
            baseName = "shared"
            export(libs.koin.core.get())
            export(libs.napier.get())
        }
        pod("FirebaseFirestore") {
            version = "10.0.0"
            git("https://github.com/firebase/firebase-ios-sdk.git")
        }
        ios.deploymentTarget = "16.0"
    }
```

It's not possible for me to sign this target, as the Pods project is always regenerated on every build/run.

What I tried:
- Signing manually inside {SHARED_FOLDER}/build/cocoapods/synthethic/IOS. It gets reset on every build/run.
- Adding this piece of code to the podfile inside the above-mentioned path. It gets reset on every build/run:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
end
```

### Firebase SDK Version

10.0.0

### Xcode Version

14.0.1

### Installation Method

CocoaPods

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

### Relevant Log Output

```shell
...shared/build/cocoapods/synthetic/IOS/Pods/Pods.xcodeproj: error: Signing for "gRPC-C++-gRPCCertificates-Cpp" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'gRPC-C++-gRPCCertificates-Cpp' from project 'Pods')
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
Please report to the KMP project.  The `gRPC-C++-gRPCCertificates-Cpp` file is no longer required for Firestore.

**Comment by mpivchev** [comment]
@paulb777 So it's a KMP issue? The `gRPC-C++-gRPCCertificates-Cpp` is bundled with this lib...

**Comment by paulb777** [comment]
`gRPC-C++-gRPCCertificates-Cpp` comes bundled with the gRPC dependency of Firestore. However, Firestore does not need it.

**Comment by mpivchev** [comment]
Here https://github.com/firebase/firebase-ios-sdk/issues/9184#issuecomment-1007864247 you mention that the zip builder can have a special case to not build this bundle. Has this been added. If not, can you give me some hints of possible ways to do this? Thanks.

**Comment by mpivchev** [comment]
This fixed it for me: https://youtrack.jetbrains.com/issue/KT-54161/Support-adding-extra-code-to-generated-Podfile-from-the-Kotlin-gradle-plugin
