### ISSUE TITLE
Remote Config returns old cached value when working with Charles Proxy

### ISSUE THREAD

**Issue by Yerazhas** [firebase/firebase-ios-sdk#10432]
### Description

We use remote config in our mobile app, and recently we discovered an interesting bug with caching.
We also use Charles web proxy to mock(substitute) remote config response. When we substitute the response we see updated value in config after relaunching app 1-2 times. But when we turn off proxying the remote config response it doesn't return to the original value i.e. always shows the mocked values. Firebase pod version is 8.15.0, also tried to update to version 10.0.0 but the issue remains.

MinimumFetchInterval is set to 0.
We call method fetch(), then if successful right after call the method activate().
Tried also fetch(withExpirationDuration: 0) { ... } but unsuccessful.

### Reproducing the issue

Configure remote config in a project.
Use Charles Proxy tool to proxy the request to the remote config server to mock its response with changed values.
Relaunch app and verify that you see values in config changed.
Now stop using proxy(turn off) and relaunch the app, then request the config. It returns us the mocked version of config which I think was cached locally, but not the actual values from the server.

### Firebase SDK Version

8.15.0

### Xcode Version

14.0

### Installation Method

CocoaPods

### Firebase Product(s)

Remote Config

### Targeted Platforms

iOS

### Relevant Log Output

```shell
2022-11-01 12:44:36.267340+0600 Skyapps[3622:261656] 8.15.0 - [Firebase/RemoteConfig][I-RCN000072] New config database created. Resetting user defaults.
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

- Firebase/Analytics (8.15.0):
    - Firebase/Core
  - Firebase/Core (8.15.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 8.15.0)
  - Firebase/CoreOnly (8.15.0):
    - FirebaseCore (= 8.15.0)
  - Firebase/Crashlytics (8.15.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 8.15.0)
  - Firebase/RemoteConfig (8.15.0):
    - Firebase/CoreOnly
    - FirebaseRemoteConfig (~> 8.15.0)
  - FirebaseABTesting (8.15.0):
    - FirebaseCore (~> 8.0)
  - FirebaseAnalytics (8.15.0):
    - FirebaseAnalytics/AdIdSupport (= 8.15.0)
    - FirebaseCore (~> 8.0)
    - FirebaseInstallations (~> 8.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/MethodSwizzler (~> 7.7)
    - GoogleUtilities/Network (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
    - nanopb (~> 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (8.15.0):
    - FirebaseCore (~> 8.0)
    - FirebaseInstallations (~> 8.0)
    - GoogleAppMeasurement (= 8.15.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/MethodSwizzler (~> 7.7)
    - GoogleUtilities/Network (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
    - nanopb (~> 2.30908.0)
  - FirebaseCore (8.15.0):
    - FirebaseCoreDiagnostics (~> 8.0)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/Logger (~> 7.7)
  - FirebaseCoreDiagnostics (8.15.0):
    - GoogleDataTransport (~> 9.1)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/Logger (~> 7.7)
    - nanopb (~> 2.30908.0)
  - FirebaseCrashlytics (8.15.0):
    - FirebaseCore (~> 8.0)
    - FirebaseInstallations (~> 8.0)
    - GoogleDataTransport (~> 9.1)
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (~> 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - FirebaseInstallations (8.15.0):
    - FirebaseCore (~> 8.0)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/UserDefaults (~> 7.7)
    - PromisesObjC (< 3.0, >= 1.2)
  - FirebaseRemoteConfig (8.15.0):
    - FirebaseABTesting (~> 8.0)
    - FirebaseCore (~> 8.0)
    - FirebaseInstallations (~> 8.0)
    - GoogleUtilities/Environment (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"

```

</details>

**Comment by Yerazhas** [comment]
As for the log output above, it shows the first time app installed. In consequent app launches no logs connected with Remote Config are displayed.

**Comment by rizafran** [comment]
Thanks for reporting, @Yerazhas. Could you provide a sample app that reproduces the issue?
