### ISSUE TITLE
Push notification is not receiving when the app is installed for first time.

### ISSUE THREAD

**Issue by yodagamaheshan** [firebase/firebase-ios-sdk#10461]
### Description

**expected to happen:**
 Receiving push notification even on the first app installation. 

**what actually happened:** 
 Notifications are not receiving when I send the app to the background OR close OR in foreground (even through I implemented `userNotificationCenter(_:willPresent:withCompletionHandler:)
`)  on the first installation / first app start .

But, If I open the app a second time, then notifications start receiving normally when I send notification using the console.

### Reproducing the issue

 1. install the app in a device without  disabling `Method swizzling`.
 2. press allow when requesting authorisation to send push notifications.
 3. send app to background OR close OR keep in the foreground. 
 4. send Notification to the device.

In my case I am requesting authorisation for Push Notifications and call `registerForRemoteNotifications()' in a later time. Not just after initialising firebase and setting delegates in `application(_:didFinishLaunchingWithOptions:)`

Note: 
Disabling `Method swizzling ` worked for me. 

### Firebase SDK Version

10.1.0

### Xcode Version

14.0.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Messaging

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for filing a ticket, @yodagamaheshan. I tried to reproduce the issue with a swizzling method enabled but I was able to receive notifications. Could you confirm if you're sending a notification via console or API? Also, may I know where you're calling the `registerForRemoteNotifications()` method? It would be great if you can provide a sample app to reproduce the issue.

**Comment by yodagamaheshan** [comment]
Hi @rizafran , Thanks for quick respond. yes I also noticed that I could receive Notification on first installation, If I call `registerForRemoteNotifications()` just after initialising firebase and setting messaging delegate in `application(_:didFinishLaunchingWithOptions:)`. 

But , In my case I have to wait a bit to fetch user and , based on the user type I only ask Permission to Use Notifications and register them for remote notification( call  `registerForRemoteNotifications()`).  In this case I am not getting Notification on the first install and run ( with enabling  method swizzling ). I am getting notifications if I kill the app and re lunch it. 

If this information is not enough, please let me know and I will be able to create and provide a sample project.

**Comment by rizafran** [comment]
Hi @yodagamaheshan, in order for me to reproduce it locally, could you provide a code snippet on how you're calling the `registerForRemoteNotifications()` if it's not in `application(_:didFinishLaunchingWithOptions:)`? Thanks.

**Comment by yodagamaheshan** [comment]
Hi @rizafran 

adding below code snippets inside  `application(_:didFinishLaunchingWithOptions:)` will reproduce the issue.
```

        Messaging.messaging().delegate = self
        UNUserNotificationCenter.current().delegate = self
        
        DispatchQueue.main.asyncAfter(deadline: .now() + 15.0) {
            UNUserNotificationCenter.current().requestAuthorization(options: [.alert, .sound]) { success, error in
                if let error = error {
                   print("error \(error)")
                }
                
                print("is success  \(success)")
            }
            
            UIApplication.shared.registerForRemoteNotifications()
        }
```

Note: I have added some delay to call `requestAuthorization` and `registerForRemoteNotifications` to mimic the delay that I get when I fetch users in my case ( I only need to enable push notifications based on the user, so that I have to wait until I get the current user details).

**Comment by rizafran** [comment]
Thanks for sharing your code snippet, @yodagamaheshan. I tried to use the code in my sample app, but I'm still able to receive notifications. Here are the steps I did:
1. Install the app for the first time
2. Wait for the user permission popup and click "Allow"
3. Copy paste the registration token from the logs and use it to send test message from the console

Could you confirm if you're using the same steps? You may also try our [Messaging Quickstart](https://github.com/firebase/quickstart-ios/tree/master/messaging) to use it as a baseline for your troubleshooting purposes.

**Comment by yodagamaheshan** [comment]
yes I am using the same steps. 

I think there is an another information that I need to share with you.  I used `iOS 16.`1 on iPhone 12.

I will try adding above my sample code snipes in to given QuickStart sample projects and will let you know the result. 

Thanks @rizafran for the effort you gave on this.
