### ISSUE TITLE
Deep Link does not contain valid required params + DynamicLinks == nil

### ISSUE THREAD

**Issue by IhorStasiv** [firebase/firebase-ios-sdk#10477]
### Description

DynamicLinks.dynamicLinks().handleUniversalLink(incomingURL) this method give me (dynamiclink(nil) error(nil) )
after method ends print
        2022-11-10 13:17:33.136393+0200 *****[2531:606940] 8.9.1 - [Firebase/Analytics][I-ACS023001] Deep Link does not contain valid required params. URL params: {
            "_cpb" = 1;
            "_cpt" = cpit;
            "_fpb" = "CJsFEPcCGgV1ay1VQQ==";
            "_iumchkactval" = 1;
            "_iumenbl" = 1;
            "_osl" = "https://base.*******.com/app/GViktuCnsde7LBYN6";
            "_plt" = 1159;
            "_uit" = 1706;
            apn = "com.*******";
            cid = 5025087385261509165;
            ibi = "com.********.*****";
            link = "https://*******.com/app/signals/636cc3aa4ca31c2f45e2e8f8";
        }

### Firebase SDK Version

Firebase 8.9.1 FirebaseDynamicLinks (8.9.0)

### Xcode Version

14.0.1

### Installation Method

CocoaPods

### Firebase Product(s)

DynamicLinks

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Using Diagnostic tool "No errors found"
    ---- Firebase Dynamic Links diagnostic output start ----
    Firebase Dynamic Links framework version 8.9.1
    System information: OS iOS, OS version 16.1, model iPhone
    Current date 2022-11-10 11:12:55 +0000
    Device locale uk-US (raw uk_US), timezone Europe/Kiev
    	    Specified custom URL scheme is com.*******.**** and Info.plist contains such scheme         in CFBundleURLTypes key.
    	    AppID Prefix: ********, Team ID: ********, AppId Prefix equal to Team ID: YES
    performDiagnostic completed successfully! No errors found.
    ---- Firebase Dynamic Links diagnostic output end ----
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @IhorStasiv, per checking, it's possible that your link structure is not properly configured. With this, you may try the following suggestions:

- Make sure that your [link parameter](https://firebase.google.com/docs/dynamic-links/create-manually) is correct and [URL encoded](https://en.wikipedia.org/wiki/Percent-encoding).
- Update the SDK to the [latest version](https://firebase.google.com/support/release-notes/ios). This lowers the existence of any underlying bugs that are present in the older releases.
- Debug your dynamic link as mentioned [here](https://firebase.google.com/docs/dynamic-links/debug) and make sure that your link doesn’t have any error or warning because it might affect the behavior of your links.
- You may also check this [related issue](https://github.com/firebase/quickstart-ios/issues/774).

If the issue persists, could you provide the affected device and OS version as well as the screenshot of full console logs.

**Comment by IhorStasiv** [comment]
> 

Ok? i get new version of SDK now its(10.0.0)
and now this method (DynamicLinks.dynamicLinks().handleUniversalLink(url)) returns me not 2 nil but returns nil and an error.
Error says <<<Error Domain=com.firebase.dynamicLinks Code=1 "Universal link URL could not be parsed by Dynamic Links." UserInfo={NSLocalizedFailureReason=Universal link URL could not be parsed by Dynamic Links.}>>>

**Comment by IhorStasiv** [comment]
I found your method "DynamicLinks.dynamicLinks().resolveShortLink(url)"
it works now, but I'm afraid that it may break in the future, if something becomes known with an error like mine, please write back.
thank you for your time

**Comment by rizafran** [comment]
I'm glad it's already working, @IhorStasiv. I'll be closing this ticket now, but feel free to comment here in case you encounter the issue again.

**Comment by IhorStasiv** [comment]
@rizafran 
Ok i have some new information for you,
from my link that comes to me in the method
      "application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?)" 
      i can't create "DynamicLink" - always returns nil.
But when I try to create a "DeferredLink", after installing the program from the "AppStore", the method 
      "application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any])"
is called, the link looks different there, he is not like the one who came before. And when I try to make it "DynamicLink", the link is created, but this link has no URL, and matchType == .none. So I can't work with him at all.
