### ISSUE TITLE
Authentication built-in UI in Custom Keyboard Extension

### ISSUE THREAD

**Issue by virozy** [firebase/firebase-ios-sdk#10504]
### Description

Hi, Guys. Thanks for your great works.

I'm working on Custom Keyboard Extension Project for iOS now. 
I've just seen the issue #6605. But there aren't any words related to Authentication Library.
Can I integrate and use Firebase Authentication Lib with it? Can I use pre built-in AuthUI in my custom keyboard view?
Also Realtime Database Library?

Hope to hear from you.

### Reproducing the issue

The project I'm working on has two sub projects.
Main App, Keyboard Extension

I just added FirebaseApp.configure() to my KeyboardController Class like this.

```
import FirebaseCore
class KeyboardViewController: KeyboardInputViewController {
    override func viewDidLoad() {
       ...
        super.viewDidLoad()
       FirebaseApp.configure()
   }
}
```

I want to know if this is correct snippet.

### Firebase SDK Version

9.5.0

### Xcode Version

14.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication, Database

### Targeted Platforms

iOS, App Extensions

### If using Swift Package Manager, the project's Package.resolved

I haven't got any file.

### If using CocoaPods, the project's Podfile.lock

I haven't got any file.

**Comment by paulb777** [comment]
Closing for staleness. Please comment or open a new issue to continue the discussion.
