### ISSUE TITLE
Crash in FirebaseStorage version 10.1.0

### ISSUE THREAD

**Issue by nrkrishna** [firebase/firebase-ios-sdk#10512]
### Description

We are seeing a crash on iOS in Crashlytics ever since upgrading to FirebaseStorage version 10.x.x. The code where this crash occurs hasn't changed, so I think this is something to do with FirebaseStorage itself.

Crash trace:
```
Crashed: NSOperationQueue 0x107b84e00 (QOS: UNSPECIFIED)
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000
0 FirebaseStorage
$s15FirebaseStorage0B0C24initFetcherServiceForApp33_A1F548C0F6900337354627997364394ALLySo010GTMSessiondE0CSo6FIRAppC_SSSo14FIRAuthInterop_pSo0m5CheckO0_ptFZTf4nnnnd_n + 236

1 FirebaseStorage
$s15FirebaseStorage0B0C16ensureConfigured33_A1F548C0F6900337354627997364394ALLyyF + 88

2 FirebaseStorage
$s15FirebaseStorage0B0C9referenceAA0B9ReferenceCyF + 24

3 FirebaseStorage
$s15FirebaseStorage0B0C9reference8withPathAA0B9ReferenceCSS_tF + 52
```

The specific line tied to this crash is simply creating a storage reference in Swift as follows.

`let fileReference = storage.reference(withPath: "subfolder/video.mov")`

Any pointers/help appreciated. Thanks.

### Reproducing the issue

We haven't been able to reproduce this on our end. The crash is occurring on customer devices. 

### Firebase SDK Version

10.1.0

### Xcode Version

14.0.1

### Installation Method

CocoaPods

### Firebase Product(s)

Storage

### Targeted Platforms

iOS

**Comment by paulb777** [comment]
Sorry about the trouble. It's possible that the issue you're seeing is related to #10463 that was fixed in last week's 10.2.0 release. 

Would you update to 10.2.0 and let us know?

**Comment by nrkrishna** [comment]
@paulb777 thanks for the quick reply. I'll update this thread once we find out the result of the update.

**Comment by nrkrishna** [comment]
@paulb777 sorry for delay. Yes, 10.2.0 fixed the issue! Thanks for the quick reply and followup!
