### ISSUE TITLE
Phone Auth not working in iOS 16 and above

### ISSUE THREAD

**Issue by ngoccuong11789** [firebase/firebase-ios-sdk#10527]
### Description

I'm using IOS 16.1.1 and can't login using Firebase and see the issue on this function : 

PhoneAuthProvider.provider().verifyPhoneNumber(phoneNumber, uiDelegate: nil) { (verificationID, error) in
         if let error = error {
           print("error 123\(error.localizedDescription)")
             error.localizedDescription.showToast()
           return
         }
           guard let verificationID = verificationID else {
               return
           }
           self.verifyId = verificationID
           self.performSegue(withIdentifier: "segueOPT", sender: nil)
       }

I need to verify 2 times and get the error : "An internal error has occurred, print and inspect the error details for more information."

### Firebase SDK Version

10.3.0

### Xcode Version

13.4.1

### Installation Method

CocoaPods

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reaching out, @ngoccuong11789. I tried reproducing the issue, but I'm able to verify my number and login to my app. May I know if you're using native iOS or react native app?

**Comment by ngoccuong11789** [comment]
> Thanks for reaching out, @ngoccuong11789. I tried reproducing the issue, but I'm able to verify my number and login to my app. May I know if you're using native iOS or react native app?

Thanks for reaching out me. I'm working on  native iOS, I can't pass this function : PhoneAuthProvider.provider().verifyPhoneNumber.... It always return error on IOS 16, but IOS 15.5 is OK, nps.... Here is the error message : An internal error has occurred, print and inspect the error details for more information.

Thanks,

**Comment by ncooke3** [comment]
Hi @ngoccuong11789, could you please share a snipped of where and how you configure Firebase?

**Comment by ngoccuong11789** [comment]
> Hi @ngoccuong11789, could you please share a code snippet of where and how you configure Firebase?
> 
> Additionally, have you been able to drop a breakpoint in the code and print the error details–– it might contain a clue for us as to where things are going wrong.

Hi Sir,
I can't test for now, because of this error : "Error Domain=FIRAuthErrorDomain Code=17010 "We have blocked all requests from this device due to unusual activity. Try again later." UserInfo={NSLocalizedDescription=We have blocked all requests from this device due to unusual activity. Try again later., FIRAuthErrorUserInfoNameKey=ERROR_TOO_MANY_REQUESTS}
"
I will confirm you later after Firebase unblocks my device. Thanks,

**Comment by ngoccuong11789** [comment]
> Hi @ngoccuong11789, could you please share a code snippet of where and how you configure Firebase?
> 
> Additionally, have you been able to drop a breakpoint in the code and print the error details–– it might contain a clue for us as to where things are going wrong.

Hi Sir,
I think the problem is not related to IOS 16, the problem is I sent many request on my device and my device/phone number has blocked all requests, the first message is : "An internal error has occurred, print and inspect the error details for more information." and the next error is : "We have blocked all requests from this device due to unusual activity...."
I need to wait for 1 day and can receive OTP normally.... 
So I need to close the issue. Thanks for your support.
