### ISSUE TITLE
Crash when calling signOut() from Auth

### ISSUE THREAD

**Issue by Bengua27** [firebase/firebase-ios-sdk#10546]
### Description

Calling signOut from Auth makes the app crashing

### Reproducing the issue

Calling signOut from Auth makes the app crashing.
The project has also GoogleSignIn 6.2.4 using spm, GTMSessionFetcher version remains 2.3.0 because of GoogleSignIn if I understood correctly.

### Firebase SDK Version

10.2.0

### Xcode Version

14.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

{
  "pins" : [
    {
      "identity" : "abseil-cpp-swiftpm",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/abseil-cpp-SwiftPM.git",
      "state" : {
        "revision" : "583de9bd60f66b40e78d08599cc92036c2e7e4e1",
        "version" : "0.20220203.2"
      }
    },
    {
      "identity" : "algoliasearch-client-swift",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/algolia/algoliasearch-client-swift",
      "state" : {
        "revision" : "d507e54c2f5e11134ee066727fda976d921f1c10",
        "version" : "8.16.0"
      }
    },
    {
      "identity" : "amplitude-ios",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/amplitude/Amplitude-iOS.git",
      "state" : {
        "revision" : "483ec5c74b50f0d483013fc910fe890ec34e54d2",
        "version" : "8.14.0"
      }
    },
    {
      "identity" : "analytics-connector-ios",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/amplitude/analytics-connector-ios.git",
      "state" : {
        "revision" : "b44981119e2efc0edd1d2e26831c3c4c0e0264e6",
        "version" : "1.0.0"
      }
    },
    {
      "identity" : "appauth-ios",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/openid/AppAuth-iOS.git",
      "state" : {
        "revision" : "3d36a58a2b736f7bc499453e996a704929b25080",
        "version" : "1.6.0"
      }
    },
    {
      "identity" : "boringssl-swiftpm",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/boringssl-SwiftPM.git",
      "state" : {
        "revision" : "dd3eda2b05a3f459fc3073695ad1b28659066eab",
        "version" : "0.9.1"
      }
    },
    {
      "identity" : "cache",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/hyperoslo/Cache",
      "state" : {
        "revision" : "c7f4d633049c3bd649a353bad36f6c17e9df085f",
        "version" : "6.0.0"
      }
    },
    {
      "identity" : "currencytext",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/marinofelipe/CurrencyText",
      "state" : {
        "revision" : "f2302ee2958cd76dc2b80678d2a6eb5bf6d71807",
        "version" : "2.3.1"
      }
    },
    {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk",
      "state" : {
        "revision" : "c24031ad9410c746c49deddc739fdf311a386fc7",
        "version" : "10.2.0"
      }
    },
    {
      "identity" : "googleappmeasurement",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleAppMeasurement.git",
      "state" : {
        "revision" : "71eb6700dd53a851473c48d392f00a3ab26699a6",
        "version" : "10.1.0"
      }
    },
    {
      "identity" : "googledatatransport",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleDataTransport.git",
      "state" : {
        "revision" : "5056b15c5acbb90cd214fe4d6138bdf5a740e5a8",
        "version" : "9.2.0"
      }
    },
    {
      "identity" : "googlesignin-ios",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleSignIn-iOS",
      "state" : {
        "revision" : "9c9b36af86a4dd3da16048a36cf37351e63ccfe1",
        "version" : "6.2.4"
      }
    },
    {
      "identity" : "googleutilities",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleUtilities.git",
      "state" : {
        "revision" : "6db6edb48bdd9943426562c7f042a5492de5ba3d",
        "version" : "7.10.0"
      }
    },
    {
      "identity" : "grpc-ios",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/grpc/grpc-ios.git",
      "state" : {
        "revision" : "8440b914756e0d26d4f4d054a1c1581daedfc5b6",
        "version" : "1.44.3-grpc"
      }
    },
    {
      "identity" : "gtm-session-fetcher",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/gtm-session-fetcher.git",
      "state" : {
        "revision" : "5ccda3981422a84186387dbb763ba739178b529c",
        "version" : "2.3.0"
      }
    },
    {
      "identity" : "gtmappauth",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GTMAppAuth.git",
      "state" : {
        "revision" : "6dee0cde8a1b223737a5159e55e6b4ec16bbbdd9",
        "version" : "1.3.1"
      }
    },
    {
      "identity" : "haishinkit.swift",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/shogo4405/HaishinKit.swift",
      "state" : {
        "revision" : "41dbb51885cc712994a7e4f4ab07eb828b5feab4",
        "version" : "1.3.0"
      }
    },
    {
      "identity" : "inputbaraccessoryview",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/nathantannar4/InputBarAccessoryView",
      "state" : {
        "revision" : "039a9cb3ae8c5bc4d39242a6aa688b88023633d3",
        "version" : "6.2.0"
      }
    },
    {
      "identity" : "keychainaccess",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/kishikawakatsumi/KeychainAccess",
      "state" : {
        "revision" : "84e546727d66f1adc5439debad16270d0fdd04e7",
        "version" : "4.2.2"
      }
    },
    {
      "identity" : "leveldb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/leveldb.git",
      "state" : {
        "revision" : "0706abcc6b0bd9cedfbb015ba840e4a780b5159b",
        "version" : "1.22.2"
      }
    },
    {
      "identity" : "loaf",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/schmidyy/Loaf",
      "state" : {
        "revision" : "5f78a659666fd1025579ded60960452a4c60eda6",
        "version" : "0.7.0"
      }
    },
    {
      "identity" : "logboard",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/shogo4405/Logboard.git",
      "state" : {
        "revision" : "0213f0b41c37d2e958b261657b72ce3801f472f9",
        "version" : "2.3.0"
      }
    },
    {
      "identity" : "lottie-ios",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/airbnb/lottie-ios.git",
      "state" : {
        "revision" : "b4bd0604ded9574807f41b4004b57dd1226a30a4",
        "version" : "3.5.0"
      }
    },
    {
      "identity" : "mbprogresshud",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/jdg/MBProgressHUD",
      "state" : {
        "revision" : "bca42b801100b2b3a4eda0ba8dd33d858c780b0d",
        "version" : "1.2.0"
      }
    },
    {
      "identity" : "messagekit",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/MessageKit/MessageKit",
      "state" : {
        "revision" : "14bfa7eb9f93267c3d7b8cdf58615bba27be672a",
        "version" : "4.1.1"
      }
    },
    {
      "identity" : "nanopb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/nanopb.git",
      "state" : {
        "revision" : "819d0a2173aff699fb8c364b6fb906f7cdb1a692",
        "version" : "2.30909.0"
      }
    },
    {
      "identity" : "nvactivityindicatorview",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/ninjaprox/NVActivityIndicatorView.git",
      "state" : {
        "revision" : "4a4726d15367d82bd3e9e1f01625bd76dbbb0c98",
        "version" : "4.8.0"
      }
    },
    {
      "identity" : "onesignal-xcframework",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/OneSignal/OneSignal-XCFramework",
      "state" : {
        "revision" : "b87060d4a77ab6b5e96d6655b2587d3cb05e33e5",
        "version" : "3.12.3"
      }
    },
    {
      "identity" : "photobrowser",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/JiongXing/PhotoBrowser",
      "state" : {
        "revision" : "ca262d6c24d7388d63650012320bcd6db084f713",
        "version" : "3.1.3"
      }
    },
    {
      "identity" : "promises",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/promises.git",
      "state" : {
        "revision" : "3e4e743631e86c8c70dbc6efdc7beaa6e90fd3bb",
        "version" : "2.1.1"
      }
    },
    {
      "identity" : "purchasely-ios",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/Purchasely/Purchasely-iOS.git",
      "state" : {
        "revision" : "aa1c22ae68399e33d51852fb4a65f3dff1838d08",
        "version" : "3.4.2"
      }
    },
    {
      "identity" : "purelayout",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/PureLayout/PureLayout",
      "state" : {
        "revision" : "5561683c96dc49b023c1299bfe4f6fbeed5f8199",
        "version" : "3.1.9"
      }
    },
    {
      "identity" : "reachability.swift",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/ashleymills/Reachability.swift",
      "state" : {
        "revision" : "c01bbdf2d633cf049ae1ed1a68a2020a8bda32e2",
        "version" : "5.1.0"
      }
    },
    {
      "identity" : "sdk-ios",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/applanga/sdk-ios",
      "state" : {
        "revision" : "e880191a9de0a207fcffee1f6497c37f3604b4e5",
        "version" : "2.0.161"
      }
    },
    {
      "identity" : "sdwebimage",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/SDWebImage/SDWebImage",
      "state" : {
        "revision" : "3312bf5e67b52fbce7c3caf431b0cda721a9f7bb",
        "version" : "5.14.2"
      }
    },
    {
      "identity" : "sidemenu",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/jonkykong/SideMenu.git",
      "state" : {
        "revision" : "8bd4fd128923cf5494fa726839af8afe12908ad9",
        "version" : "6.5.0"
      }
    },
    {
      "identity" : "stripe-ios",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/stripe/stripe-ios.git",
      "state" : {
        "revision" : "868cc0bcfecb016f1fd4d3a52b31623e4d88ebd9",
        "version" : "23.2.0"
      }
    },
    {
      "identity" : "swift-log",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-log.git",
      "state" : {
        "revision" : "6fe203dc33195667ce1759bf0182975e4653ba1c",
        "version" : "1.4.4"
      }
    },
    {
      "identity" : "swift-protobuf",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-protobuf.git",
      "state" : {
        "revision" : "ab3a58b7209a17d781c0d1dbb3e1ff3da306bae8",
        "version" : "1.20.3"
      }
    },
    {
      "identity" : "swiftcsv",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/swiftcsv/SwiftCSV",
      "state" : {
        "revision" : "039cc273dcc91f4c9d85e05a2514bbe63e7dde60",
        "version" : "0.6.1"
      }
    },
    {
      "identity" : "swiftyjson",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/SwiftyJSON/SwiftyJSON.git",
      "state" : {
        "revision" : "b3dcd7dbd0d488e1a7077cb33b00f2083e382f07",
        "version" : "5.0.1"
      }
    }
  ],
  "version" : 2
}

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by Bengua27** [comment]
<img width="1651" alt="Screenshot 2022-12-02 at 2 54 31 PM" src="https://user-images.githubusercontent.com/5184741/205234432-f40ca33c-1e87-47ea-9f40-9b3ca3cc51fd.png">
<img width="1657" alt="Screenshot 2022-12-02 at 2 54 57 PM" src="https://user-images.githubusercontent.com/5184741/205234451-cfabd706-2779-4d8d-9164-59e4aaa8fe06.png">

**Comment by paulb777** [comment]
This looks similar to #10507 which was a 10.2.0 regression with a fix planned for next week's 10.3.0 release. 

Does installing 10.1.0 version of Firestore resolve the issue?

**Comment by paulb777** [comment]
cc: @cherylEnkidu

**Comment by cherylEnkidu** [comment]
I can confirm this bug will be fixed by #10535 in the next release.

**Comment by MetaImi** [comment]
This issue happens for me when trying to sign in too.

**Comment by Bengua27** [comment]
> This looks similar to #10507 which was a 10.2.0 regression with a fix planned for next week's 10.3.0 release.
> 
> Does installing 10.1.0 version of Firestore resolve the issue?

Indeed, 10.1.0 does not crash. I will use it until the next version is available.
Thanks for the suggestion,

**Comment by leogiroux** [comment]
Still crashing on ios 16.1

**Comment by cherylEnkidu** [comment]
Hi @leogiroux 

Can you provide a stack trace of the crash?
