### ISSUE TITLE
Using Swift Package Manager to add Firebase on Xcode 14.1 causing multiple errors in Xcode project

### ISSUE THREAD

**Issue by kr1s0404** [firebase/firebase-ios-sdk#10543]
### Description

When I used the SPM to add Firebase SDK to my Project, it shows the following error.
But when I use Pod install to add SDK, it was working fine.
I have try reset package caches, resolve package version, and delete the derived data in the folder.

![Imgur](https://i.imgur.com/Qf7Cukz.png)
![Imgur](https://i.imgur.com/ggFRA2e.png)

### Reproducing the issue

Xcode Version: 14.1
iOS Version: 15.0

### Firebase SDK Version

9.0.0

### Xcode Version

14.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

All

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
These are possibly transitory networking issues.

Does retrying work? Are you able to access the failed URLs from a browser?

**Comment by kr1s0404** [comment]
I have created a new Xcode project and install Firebase with SPM and it was working fine.... so I guess the problem was some how have conflicts with my old project. I don't have this issue anymore, so I will close the issue, thank you for helping me out, take care stay safe. Thank you.
