### ISSUE TITLE
[FR]: Async Await FirebaseStorage observers

### ISSUE THREAD

**Issue by Faktorealchik** [firebase/firebase-ios-sdk#10574]
### Description

https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseStorage/Sources/AsyncAwait.swift 

In this file we emit StorageUploadTask, and we can't add observers, so we don't know about the progress. (e.g. putFileAsync)

Uploading large files difficult to handle without knowing status

### API Proposal

Perhaps you can add delegate and handle all observers inside, then tell that something is changed to delegate?

### Firebase Product(s)

Storage

**Comment by paulb777** [comment]
Thanks for the request. We're exploring an async/await API with Progress support in #10161.  We're somewhat hesitant to go forward with this since Apple's roadmap for `Progress` is unclear. See https://forums.swift.org/t/what-s-next-for-foundation/61939#removed-types-8

In the meantime, the original non-async/await Storage APIs continue to support Progress.

**Comment by Faktorealchik** [comment]
Hello @paulb777 

Thank you!

**Comment by paulb777** [comment]
After more thought, I believe the original APIs that return `Task` handles should be sufficient if you want to check task status. The async/await API's should only be used for fire and forget mode.

I'll close here, but feel free to continue the conversation.

**Comment by Faktorealchik** [comment]
@paulb777 Hi, yeah, I'm using original Api to check statuses now, but I want to improve my code to fit async await, and functions like delete are working well, so I thought if you can improve other methods as well, so I won't loose any functionality

**Comment by Faktorealchik** [comment]
@paulb777 Hi

Why do you think that async await API should be different from the original one?
From my perspective it should be the same. Also Apple's doing the same thing. For example you can access 'fractionCompleted' in async/await in Progress, it is easy to access via KVO. What do you think about KVO?

**Comment by JarnoRFB** [comment]
I defined an extension which takes a closure, which is called when progress happens, while the result is still returned from an async function.

```swift
extension StorageReference {
    func write(toFile url: URL, onProgress: @escaping (Double?) -> Void) async throws {
        let downloadTask = self.write(toFile: url)
        try await withCheckedThrowingContinuation { continuation in
            downloadTask.observe(.progress) {
                onProgress($0.progress?.fractionCompleted)
            }
            
            downloadTask.observe(.success) { _ in
                continuation.resume(with: .success(()))
            }
            
            downloadTask.observe(.failure) { snapshot in
                continuation.resume(with: .failure(snapshot.error ?? NSError()))
            }
        }
    }
}

// on the call site
try await reference .write(toFile: file) { progress in
    print(progress ?? 0.0)
}

``` 

That is working fine so far, but an integration of something like this into the package would be nice.
