### ISSUE TITLE
XCode Cloud unable to locate GoogleService-Info.plist

### ISSUE THREAD

**Issue by arbyruns** [firebase/firebase-ios-sdk#10570]
### Description

When using XCode cloud I get the following error `Build input cannot be found /GoogleService-Info.plist. Did you forget to declare this file as an output of a script phase or custom build rule which produces it`

### Reproducing the issue

1. Using the default XCode Cloud job
2. Add GoogleService-Info.plist to a project
3. Run XCode Cloud job

### Firebase SDK Version

8.15

### Xcode Version

14.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @arbyruns, may I know if you have tried to clean build your project? I also found a solution [here](https://stackoverflow.com/questions/73359777/xcode-error-build-input-file-cannot-be-found-users-anonym-downloads-googlese) which might fix your issue.
