### ISSUE TITLE
Issues building on MacOS - GoogleAppMeasurementOnDeviceConversion

### ISSUE THREAD

**Issue by BrettRosen** [firebase/firebase-ios-sdk#10585]
### Description

When trying to build for Mac (Apple Silicon or Intel), I encounter a compile time error listed below. I've tried toggling FirebaseAnalyticsSwift, FirebaseAnalytics and FirebaseAnalyticsOnDeviceConversion all to iOS only in Link Binary With Libraries, yet still run into issues. I can't seem to figure out how to get my project compiling for MacOS with firebase.

### Firebase SDK Version

10.3.0

### Xcode Version

14.1 Beta 3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

macOS

### Relevant Log Output

```shell
GoogleAppMeasurementOnDeviceConversion

/Users/brettrosen/Library/Developer/Xcode/DerivedData/Todo_Reimagined-baermdjxpolcftgaxsdqplfwnctf/SourcePackages/artifacts/googleappmeasurement/GoogleAppMeasurementOnDeviceConversion.xcframework:1:1 While building for macOS, no library for this platform was found in '/Users/brettrosen/Library/Developer/Xcode/DerivedData/Todo_Reimagined-baermdjxpolcftgaxsdqplfwnctf/SourcePackages/artifacts/googleappmeasurement/GoogleAppMeasurementOnDeviceConversion.xcframework'.
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
I don't think there's a way for Xcode's multiplatform target feature to support different binary Swift Package dependencies.

I believe there needs to be a separate target for each platform.
