### ISSUE TITLE
Unable to install the Firebase iOS SDK (9.0.0) through SPM in xcode 14.1

### ISSUE THREAD

**Issue by shraddha-crest** [firebase/firebase-ios-sdk#10594]
### Description

I have ios project which work fine in xcode 13.4.1, To release this application, it is require to check it in xcode 14.1 to give support of ios 16, so I have downloaded new xcode 14.1 and open existing application in it. when I build the project, it gives me lots of fire base related error. so I remove added firebase ios sdk  and add it again.

I tried to add firebase ios sdk in xcode 14.1 project using SPM, every time it show pop up with message "Communication with the service was interrupted ". It works fine in xcode 13.4.1
![Screenshot 2022-12-19 at 3 32 05 PM](https://user-images.githubusercontent.com/95080562/208399681-d8e689e8-d698-4301-8c03-276f03abab39.png)

I had created new project and had tried to add firebase ios sdk, got same error.

### Firebase SDK Version

9.0.0

### Xcode Version

14.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

All

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reporting, @shraddha-crest. I'm unable to reproduce the issue on Xcode 14.1. Have you tried to reset the Package Caches, then quit Xcode and restart your machine? I also found a solution [here](https://stackoverflow.com/a/61049144) which might fix the issue.

**Comment by shraddha-crest** [comment]
> Thanks for reporting, @shraddha-crest. I'm unable to reproduce the issue on Xcode 14.1. Have you tried to reset the Package Caches, then quit Xcode and restart your machine? I also found a solution [here](https://stackoverflow.com/a/61049144) which might fix the issue.

@rizafran Thanks for replay, Yes i did all the things you mention in replay, even I delete `gitconfig` file and build application. It did not fix the issue.

**Comment by paulb777** [comment]
Are you able to `git clone git@github.com:firebase/firebase-ios-sdk.git` in the command line outside of Xcode?

**Comment by shraddha-crest** [comment]
Yesterday, I downloaded Xcode14.2 and open my existing application in it and firebase-ios-SDK works fine in it.
I don't know why it is not working in Xcode14.1 but works fine in 14.2. it solved my problem.
Thanks for your support and immediate replay.

**Comment by rizafran** [comment]
Thanks for the update, @shraddha-crest. Good to know that it's working on 14.2. If the issue arises, feel free to comment to reopen the ticket.
