### ISSUE TITLE
Apple signing for GoogleSignIn not working with Xcode 14

### ISSUE THREAD

**Issue by Annika-EMP** [firebase/firebase-ios-sdk#10597]
### Description

[REQUIRED] Step 1: Describe your environment

Xcode version: 14.0.1 
Firebase SDK version: 10.3.0
Installation method: CocoaPods
Firebase Component: GoogleSignIn 6.2.4
[REQUIRED] Step 2: Describe the problem

I am able to archive my Mac Catalyst app and upload to App Store connect. However, I get an error message from App Store connect once uploaded:

ITMS-90284: Invalid Code Signing - The executable 'executable 'MyApp.app/Contents/Frameworks/GoogleSignIn.framework/Versions/A/Resources/GoogleSignIn.bundle' must be signed with the certificate that is contained in the provisioning profile

I build the iOS App with the same target and with this I can upload the App to AppStoreConnect. 
The Configuration of the GoogleSignIn framework you can see in the Screenshot following:
<img width="987" alt="Screenshot 2022-12-20 at 12 14 53" src="https://user-images.githubusercontent.com/94851541/208654694-a271cbd1-7200-47b5-a2d7-ccbc5582820f.png">

With a Signing Certificate "Apple Development" set for MacOS it doesn't work as well.
With Xcode 13.4.1 the configuration to "Sign to run Locally" works.

### Firebase SDK Version

10.3.0

### Xcode Version

14.0.1

### Installation Method

CocoaPods

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS, macOS

### Relevant Log Output

```shell
ITMS-90284: Invalid Code Signing - The executable 'executable 'MyApp.app/Contents/Frameworks/GoogleSignIn.framework/Versions/A/Resources/GoogleSignIn.bundle' must be signed with the certificate that is contained in the provisioning profile
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reaching out, @Annika-EMP. Your issue is possibly related to #9886.

**Comment by Annika-EMP** [comment]
Thanks @rizafran, yes it's related to the issue but I cannot solve it with this workaround. The workaround just works for iOS and not for the Mac Catalyst build.

**Comment by rizafran** [comment]
@Annika-EMP, based on the discussion there, it's a CocoaPods/Xcode issue. You may try checking https://github.com/CocoaPods/CocoaPods/issues/8891 for the possible workaround for Catalyst build.

**Comment by paulb777** [comment]
I'm going to close here. If still unresolved please follow up on the Google SignIn GitHub issue at https://github.com/google/GoogleSignIn-iOS/issues/105

**Comment by Annika-EMP** [comment]
Adding the following to the Podfile resolved the issue:

```post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle" # <--- this
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          config.build_settings["DEVELOPMENT_TEAM"] = ""
      end
    end
  end
end```

Thanks @rizafran
