### ISSUE TITLE
I got a Domain error when post data to Cloud FireStore

### ISSUE THREAD

**Issue by cdjinwei** [firebase/firebase-ios-sdk#1060]
#### my code(just same as FireBase`s document),and i have the config file "GoogleService-Info.plist",also initialzed FireBase
```
[FIRApp configure];
```
```
// Add a new document with a generated ID
__block FIRDocumentReference *ref =
    [[self.db collectionWithPath:@"users"] addDocumentWithData:@{
      @"first": @"Ada",
      @"last": @"Lovelace",
      @"born": @1815
    } completion:^(NSError * _Nullable error) {
      if (error != nil) {
        NSLog(@"Error adding document: %@", error);
      } else {
        NSLog(@"Document added with ID: %@", ref.documentID);
      }
    }];
```
#### what error i got
```
Apr 10 17:24:54  Solitaire[422] <Debug>: 4.9.0 - [Firebase/Firestore][I-FST000001] FSTWriteStream 0x15848ce0 start
Apr 10 17:24:54  Solitaire[422] <Debug>: 4.9.0 - [Firebase/Firestore][I-FST000001] Committing <FSTWriteGroup for Locally write mutations: 2 changes (365 bytes):
	  - Put [mutation: userID= batchID=49] (365 bytes)
	  - Put [document_mutation: userID= key=game_info_/8jdXb6eMIqZ9jpkbeeEM batchID=49] (0 bytes)>
Apr 10 17:24:55  Solitaire[422] <Debug>: 4.9.0 - [Firebase/Firestore][I-FST000001] FSTWriteStream 0x15848ce0 initial request: <GCFSWriteRequest 0x1583fba0>: {
	    database: "projects/solitaire-us/databases/(default)"
	}
Apr 10 17:24:55  Solitaire[422] <Debug>: 4.9.0 - [Firebase/Performance][I-PRF100009] Recording network trace: https://e.crashlytics.com/spi/v2/events
I/AudioEngine-inl.mm (359): OpenAL was initialized successfully!
V/AudioCache (311): pcm buffer was loaded successfully, total frames: 44749, total read frames: 44749, adjust frames: 0, remainingFrames: 0
Apr 10 17:24:56  Solitaire[422] <Debug>: 4.9.0 - [Firebase/Performance][I-PRF100009] Recording network trace: https://me.xdrig.com/v1/38c1feb0
Apr 10 17:24:57  Solitaire[422] <Debug>: 4.9.0 - [Firebase/Firestore][I-FST000001] FSTWriteStream 0x15848ce0 close: Error Domain=FIRFirestoreErrorDomain Code=14 "Connect Failed" UserInfo={io.grpc.TrailersKey={
	}, NSLocalizedDescription=Connect Failed}
```
#### blow 
```
platform :ios, '8.0'
target 'my_project' do
	pod 'Adjust', '~> 4.12.1'
	#pod 'Google-Mobile-Ads-SDK'
    pod 'Firebase/Core'
    pod 'Firebase/AdMob'
    pod 'Fabric', '~> 1.7.2'
    pod 'Crashlytics', '~> 3.9.3'
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Performance'
    pod 'Firebase/Firestore'
#    pod 'Firebase/Auth'
end

```

**Comment by morganchen12** [comment]
Are you able to read and write data to Firestore via the Firebase Console? If so, your network connection shouldn't be the issue.

**Comment by cdjinwei** [comment]
when im testing,all request are accessible to database
`
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write;
    }
  }
}
`

**Comment by wilhuff** [comment]
Are you by chance based out of China?

**Comment by wilhuff** [comment]
Alternatively can you verify that when you run a REST-based get you get a response from the Firestore service?

For example, if you run this (for the same document in your log above):
```
curl 'https://firestore.googleapis.com/v1beta1/projects/solitaire-us/databases/(default)/documents/game_info_/8jdXb6eMIqZ9jpkbeeEM'
```
You should see output like this:
```
{
  "error": {
    "code": 404,
    "message": "Document \"projects/solitaire-us/databases/(default)/documents/game_info_/8jdXb6eMIqZ9jpkbeeEM\" not found.",
    "status": "NOT_FOUND"
  }
}
```

**Comment by cdjinwei** [comment]
yes,im a chinese developer, and i think my network environment allow my app to connect to google

**Comment by wilhuff** [comment]
So does the `curl` request work?

**Comment by cdjinwei** [comment]
i got this 

`curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to firestore.googleapis.com:443 
`

**Comment by cdjinwei** [comment]
sorry ,i forgot something ,now i got this
```

{
  "error": {
    "code": 404,
    "message": "Document \"projects/solitaire-us/databases/(default)/documents/game_info_/8jdXb6eMIqZ9jpkbeeEM\" not found.",
    "status": "NOT_FOUND"
  }
}
```

**Comment by wilhuff** [comment]
So `FIRFirestoreErrorDomain` here is somewhat misleading. Every `NSError` should have a “domain” and a “code” and in this case, the domain is telling you that Firestore originated the error and the code 14 is that the service is “unavailable”. The underlying detail supplied by grpc indicates that what’s happening is that the client cannot connect to the server.

Meanwhile we know the service to be up so there must be something about your environment that is preventing the connection to the server.

Firestore is based on gRPC, so it’s possible there are some configuration values that could be required to make it work in your specific situation. For example, we’ve observed in certain corporate environments that require the use of an HTTP proxy to access the internet people have needed to set the `http_proxy` environment variable to make this work. This and other configuration values for grpc are [documented by the grpc team](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md).

That Analytics and Crashlytics work isn’t a strong indicator one way or the other: these services use different URLs and neither uses gRPC. It’s surprising that Firestore works for Android but not on iOS but these are also different gRPC implementations and we’ve observed differences in behavior before.

All of which is just to say that I don’t really know what’s going on here. This should Just Work and that it doesn’t makes me suspect that whatever it is you’re doing to gain access to Google isn’t quite working or needs additional configuration. I can’t really help you debug that though.

The page I linked to above includes the `GRPC_TRACE` and `GRPC_VERBOSITY` variables and setting those could help further diagnose this, but everything I’ve seen so far indicates that this is just going to tell us what we already know: that you can’t connect to the Firestore server.

**Comment by cdjinwei** [comment]
Thanks for your so long replay,it's helpful.
All of my internet request are via an HTTP proxy so they can really reach remote server,but i still cant understand why my android deivce can work,Maybe my IOS device's network got some problem.
I will check it again carefully.

**Comment by wilhuff** [comment]
My guess is that this is just a difference between the Android gRPC and iOS gRPC.

Android uses grpc-java, which in turn uses okhttp which appears to honor the system proxy settings. The iOS gRPC is based on the grpc C core, and I don't see anything in that repository that appears to interact with the system settings for http proxies. To make this work you'll need to set the http_proxy environment variable, which you can do in Xcode for testing.

**Comment by wilhuff** [comment]
I don't believe there's any action possible on our part here. If you find problems unrelated to your local network configuration we can reopen and investigate further.

**Comment by shiwanjun** [comment]
请问最后是怎么解决问题的呢？

**Comment by cdjinwei** [comment]
问题事实上并没有解决,直接硬着头皮上了,之后也能接受到用户的数据,肯定是因为网络的问题.应该有解决办法,我没找到

**Comment by cdjinwei** [comment]
ps: 测试设备使用的是真实的IOS设备(不是模拟器),能够访问google(以前测试也是翻了墙的)
