### ISSUE TITLE
There is no real-time upload event when calling the [FIRAnalytics logEventWithName:parameters:] method

### ISSUE THREAD

**Issue by Robby0318** [firebase/firebase-ios-sdk#10605]
### Description

When the [FIRAnalytics logEventWithName:parameters:] method is called every time, the event upload is not triggered immediately, and the upload will only be performed after switching to other applications。Or add -FIRDebugEnabled to the startup parameters to upload events in real time

### Reproducing the issue

1 Start the software,Call [FIRApp configure] to initialize
, click the button, and call the [FIRAnalytics logEventWithName:parameters:] method in the button click event
2 The events in [FIRAnalytics logEventWithName:parameters:] are not uploaded immediately, and will only be uploaded when switching to other applications

How can the event be uploaded immediately after calling the [FIRAnalytics logEventWithName:parameters:] method

### Firebase SDK Version

10.1.0

### Xcode Version

13.4.1

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics

### Targeted Platforms

macOS

### Relevant Log Output

```shell
2022-12-22 11:06:27.979656+0800 FireBaseTest[57944:1746431] 10.1.0 - [FirebaseAnalytics][I-ACS002002] Engagement timer scheduled to fire in approx. (s): 3600
2022-12-22 11:06:30.056015+0800 FireBaseTest[57944:1746377] GA4 Install : download#test1122
2022-12-22 11:06:30.058077+0800 FireBaseTest[57944:1746430] 10.1.0 - [FirebaseAnalytics][I-ACS023051] Logging event: origin, name, params: app, Desktop_Tools, {
    "_o" = app;
    ea = Install;
    el = "download#test1122";
    ps = "gemoo-com";
    pv = "gs-mac";
    tv = "1.0.0.4";
}
2022-12-22 11:06:30.061489+0800 FireBaseTest[57944:1746429] 10.1.0 - [FirebaseAnalytics][I-ACS023072] Event logged. Event name, event params: Desktop_Tools, {
    "_o" = app;
    ea = Install;
    el = "download#test1122";
    ps = "gemoo-com";
    pv = "gs-mac";
    tv = "1.0.0.4";
}
2022-12-22 11:06:30.065412+0800 FireBaseTest[57944:1746430] 10.1.0 - [FirebaseAnalytics][I-ACS002002] Measurement timer scheduled to fire in approx. (s): 3596.258199930191
```

### If using CocoaPods, the project's Podfile.lock

PODS:
  - Firebase/Analytics (10.1.0):
    - Firebase/Core
  - Firebase/Core (10.1.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 10.1.0)
  - Firebase/CoreOnly (10.1.0):
    - FirebaseCore (= 10.1.0)
  - FirebaseAnalytics (10.1.0):
    - FirebaseAnalytics/AdIdSupport (= 10.1.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - GoogleUtilities/Network (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (10.1.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleAppMeasurement (= 10.1.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - GoogleUtilities/Network (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseCore (10.1.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Logger (~> 7.8)
  - FirebaseCoreInternal (10.1.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseInstallations (10.1.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)
  - GoogleAppMeasurement (10.1.0):
    - GoogleAppMeasurement/AdIdSupport (= 10.1.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - GoogleUtilities/Network (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/AdIdSupport (10.1.0):
    - GoogleAppMeasurement/WithoutAdIdSupport (= 10.1.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - GoogleUtilities/Network (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/WithoutAdIdSupport (10.1.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - GoogleUtilities/Network (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleUtilities/AppDelegateSwizzler (7.8.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (7.8.0):
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/Logger (7.8.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (7.8.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (7.8.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.8.0)"
  - GoogleUtilities/Reachability (7.8.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (7.8.0):
    - GoogleUtilities/Logger
  - nanopb (2.30909.0):
    - nanopb/decode (= 2.30909.0)
    - nanopb/encode (= 2.30909.0)
  - nanopb/decode (2.30909.0)
  - nanopb/encode (2.30909.0)
  - PromisesObjC (2.1.1)

DEPENDENCIES:
  - Firebase/Analytics

SPEC REPOS:
  trunk:
    - Firebase
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreInternal
    - FirebaseInstallations
    - GoogleAppMeasurement
    - GoogleUtilities
    - nanopb
    - PromisesObjC

SPEC CHECKSUMS:
  Firebase: 444b35a9c568a516666213c2f6cccd10cb12559f
  FirebaseAnalytics: 24cb27b52b2e11ad5013528195b4ca0755dec960
  FirebaseCore: 55e7ae35991ccca4db03ff8d8df6ed5f17a3e4c7
  FirebaseCoreInternal: 96d75228e10fd369564da51bd898414eb0f54df5
  FirebaseInstallations: 99d24bac0243cf8b0e96cf5426340d211f0bcc80
  GoogleAppMeasurement: e490e248af3da95afe8fa8e7baac232dc8d020b7
  GoogleUtilities: 1d20a6ad97ef46f67bbdec158ce00563a671ebb7
  nanopb: b552cce312b6c8484180ef47159bc0f65a1f0431
  PromisesObjC: ab77feca74fa2823e7af4249b8326368e61014cb

PODFILE CHECKSUM: c30a39ad4b675d844f8cef74ad2f6a97dc6fe5c5

COCOAPODS: 1.11.3

**Comment by morganchen12** [comment]
Your client logs show this is uploading correctly and not returning any errors, so the issue is likely on your Firebase project's end. Please file a [support issue](https://firebase.google.com/support) instead of a GitHub issue so we can take a look at your project.

**Comment by morganchen12** [comment]
Hey, sorry for the misdirection on my earlier comment.

> When the [FIRAnalytics logEventWithName:parameters:] method is called every time, the event upload is not triggered immediately, and the upload will only be performed after switching to other applications。Or add -FIRDebugEnabled to the startup parameters to upload events in real time

This is intended behavior from the Analytics SDK. It batches events and chooses when to upload them based on network conditions so your app's bandwidth isn't wasted on analytics events when constrained. As you've already discovered, enabling debug mode makes them log immediately. See the [DebugView](https://firebase.google.com/docs/analytics/debugview) docs for more details.
