### ISSUE TITLE
React Native Firebase Ios 'GoogleUtilities/GULUserDefaults.h' file not found error

### ISSUE THREAD

**Issue by AntonioLi1** [firebase/firebase-ios-sdk#10629]
### Description

Hi there!
I am building a React Native application and currently trying to run it on Xcode. 
However, I am running into an error saying: 'GoogleUtilities/GULUserDefaults.h' file not found.
<img width="1142" alt="Screenshot 2022-12-31 at 4 10 34 pm" src="https://user-images.githubusercontent.com/98675667/210125802-3d0eb7b5-91fc-45c3-999b-c700452c6f33.png">
My current pod version is 1.11.3 and ruby version is 2.7.5. 
If anyone knows how to fix this issue, please let me know!!

Thanks!

### Firebase SDK Version

16.5.0

### Xcode Version

14.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication, Firestore, Storage

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
This is likely a react native configuration issue and react native's support channels may be better able to help.  The Podfile.lock file may help to diagnose the issue.
