### ISSUE TITLE
FIRAuthKeychainServices causing thread warning when calling Auth.auth().signOut() method

### ISSUE THREAD

**Issue by acwright** [firebase/firebase-ios-sdk#10620]
### Description

When calling:

`try Auth.auth().signOut()`

Xcode will issue the following thread warning "This method should not be called on the main thread as it may lead to UI unresponsiveness." in FIRAuthKeychainServices:

<img width="1313" alt="Screenshot 2022-12-29 at 2 09 30 AM" src="https://user-images.githubusercontent.com/608373/209923325-3611026b-9405-4e79-846d-3b6bd4e5428d.png">

### Reproducing the issue

I am doing the following in an `ObservableObject` class:

``` swift
    func signOut() {
        do {
            try Auth.auth().signOut()
        } catch {
            Logger.error(error.localizedDescription)
        }
    }
```

### Firebase SDK Version

9.6.0

### Xcode Version

14.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication

### Targeted Platforms

macOS

### Relevant Log Output

```shell
[Security] This method should not be called on the main thread as it may lead to UI unresponsiveness.
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reporting, @acwright. I wasn't able to get the same warning on [Auth Quickstart](https://github.com/firebase/quickstart-ios/tree/master/swiftui/PasswordlessSwiftUI). However, I found this related [Apple discussion](https://developer.apple.com/forums/thread/714467?answerId=734799022#734799022), and it seems like the issue is on `WKWebView`.

**Comment by acwright** [comment]
@rizafran There is no `WKWebView ` anywhere in my app. The app I'm building is a SwiftUI project for more info. Very vanilla project. 

I believe this may be from the method being called in an `ObservableObject` subclass that is marked with `@MainActor` which is also very common to do in a SwiftUI app. If I understand this correctly it means the function called in my `ObservableObject` (see above) is being called on the main thread therefore your `signOut()` method is being called on the main thread and thus the offending `SecItemDelete` method is being incorrectly called on the main thread hence the Xcode warning.

Hopefully this adds some clarification :)

**Comment by paulb777** [comment]
Is this still an issue in Firebase 11 and recent Xcode versions?
