### ISSUE TITLE
"APP_NAME needs to be updated" message while using carthage

### ISSUE THREAD

**Issue by Sundea** [firebase/firebase-ios-sdk#10648]
### Description

I've added the firebase via carthage. The app builds successfully and works correctly on the simulator. But I can't launch the signed .ipa file on the device. When I try to launch the app ios shows the following alert: 
"APP_NAME needs to be updated. The developer of this app needs to update it to work with this version of iOS"
Previously we have used the SPM for firebase and haven't faced any problems with launching signed .ipa.

100% this is the issue related to firebase as far as it was the atomic change. The launches normally if we use SPM only for this dependency. The app was signed with a fresh certificate and provision. 

Device iPhone 13 ios 16.1.2
Minimum deployment target: iOS 15.0

### Reproducing the issue

1. Add to cartfile 
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" "10.3.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashlyticsBinary.json" "10.3.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseRemoteConfigBinary.json" "10.3.0"
```
2. Drag and drop the following to the app with the option "Embed And Sign" and build phases link binary with libraries with "required" option.
```
CropViewController.xcframework
FBLPromises.xcframework
FirebaseABTesting.xcframework
FirebaseAnalytics.xcframework
FirebaseAnalyticsSwift.xcframework
FirebaseCore.xcframework
FirebaseCoreInternal.xcframework
FirebaseCrashlytics.xcframework
FirebaseInstallations.xcframework
FirebaseRemoteConfig.xcframework
FirebaseRemoteConfigSwift.xcframework
FirebaseSharedSwift.xcframework
GoogleAppMeasurement.xcframework
GoogleAppMeasurementIdentitySupport.xcframework
GoogleDataTransport.xcframework
GoogleUtilities.xcframework
nanopb.xcframework
```
3. Add Objc Other linker flags
3. Archive, and produce an ipa.

### Firebase SDK Version

10.3.0

### Xcode Version

14.1

### Installation Method

Carthage

### Firebase Product(s)

Analytics, Crashlytics, Remote Config

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

-

### If using CocoaPods, the project's Podfile.lock

-

**Comment by rizafran** [comment]
Thanks for reaching out, @Sundea. I wasn't able to reproduce the issue by following the steps you provided. Have you tried changing the Firebase frameworks to "Do Not Embed" instead? You may also share a sample app that reproduces the issue for this investigation.
