### ISSUE TITLE
Analytics Integration Issue - SPM, 10.3.0

### ISSUE THREAD

**Issue by mgrms** [firebase/firebase-ios-sdk#10644]
### Description

Firebase Analytics SPM integration docs does not contain step about adding "-ObjC" to "Other Linker Flags". CocoaPods do that automatically, but with SPM you need to do that manually, or Firebase Analytics won't work at all.

Just spent a few hours to find this problem.

I think it will be nice to update the docs. (https://firebase.google.com/docs/analytics/get-started?platform=ios#add-sdk)

### Reproducing the issue

Create new project, integrate FirebaseAnalytics into UIKit project via SPM.

### Firebase SDK Version

10.3.0

### Xcode Version

14.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

**Comment by rizafran** [comment]
Thanks for raising this, @mgrms. Adding `-ObjC` linker option is listed on the requirements [here](https://github.com/firebase/firebase-ios-sdk/blob/master/SwiftPackageManager.md), but I'll inform the team for this to be added as well on the docs.

**Comment by rizafran** [comment]
@mgrms, I just noticed that this step is already on our [documentation](https://firebase.google.com/docs/analytics/get-started?platform=ios#add-sdk). Please see our [installation guide](https://firebase.google.com/docs/ios/installation-methods#analytics) for more info.

**Comment by mgrms** [comment]
@rizafran 

Thanks, now I see that page you mentioned indeed contains this step.
But to be honest, I think it's still worth adding this step directly to Analytics installation page (https://firebase.google.com/docs/analytics/get-started?platform=ios#add-sdk), since it won't work without this step at all. Will be much clearer for people who use Firebase for the first time.

Reference to page you mentioned says:
_"Visit [our installation guide](https://firebase.google.com/docs/ios/installation-methods) to learn about the different ways you can add Firebase SDKs to your Apple project, including importing frameworks directly and using CocoaPods."_

So I thought it's all about different ways of installing Firebase (CocoaPods, Carthage) which was not my case, and didn't even look there.

I will close this now. Thanks for your help!

**Comment by paulb777** [comment]
I'll reopen, since I agree that we should add to the Analytics installation page.

**Comment by joshuapoq** [comment]
@paulb777 I don't believe the ObjC flag is required anymore? _Asking as it causes conflicts with 3rd parties that statically embed Firebase (which is also wrong so it's good to catch)._ But I think this issue is no longer an issue so are there plans to remove it from documentation or is it still required?

**Comment by paulb777** [comment]
@joshuapoq It's now less required. 

If the app uses an API from FirebaseAnalytics, it will be fully linked without the use of the `-ObjC` option.

If FirebaseAnalytics is used without any of its APIs, then `-ObjC` is still needed.

**Comment by paulb777** [comment]
The docs have been updated.
