### ISSUE TITLE
[FR]: DynamicLinks should support an initializer that accepts a FirebaseApp

### ISSUE THREAD

**Issue by sergiocampama** [firebase/firebase-ios-sdk#10654]
### Description

Use case: Running an app with integrations to multiple Firebase environments (projects)

Currently: `DynamicLinks.dynamicLinks()` is the only way to get an instance of DynamicLinks.

Proposal: Same as multiple other components, there should be a `DynamicLinks.dynamicLinks(app: firebaseApp)` API to get a DynamicLinks object not tied to the default app.

### API Proposal

```
/**
 * @method dynamicLinks
 * @abstract Shared instance of FIRDynamicLinks.
 * @param app The app for which to retrieve the associated `FIRDynamicLinks` instance.
 * @return Shared instance of FIRDynamicLinks.
 */
+ (instancetype)dynamicLinksWithApp:(FIRApp *)app NS_SWIFT_NAME(dynamicLinks(app:));
```

Implementation:

```
+ (instancetype)dynamicLinksWithApp:(FIRApp *)app {
  id<FIRDynamicLinksInstanceProvider> instance =
      FIR_COMPONENT(FIRDynamicLinksInstanceProvider, app.container);
  return (FIRDynamicLinks *)instance;
}
```

### Firebase Product(s)

DynamicLinks

**Comment by paulb777** [comment]
Now that [Firebase DynamicLinks is planned to shut down](https://firebase.google.com/support/dynamic-links-faq), closing its feature requests.
