### ISSUE TITLE
[auth] `creationTime` is always equal to `lastSignInTime`

### ISSUE THREAD

**Issue by Lyokone** [firebase/firebase-ios-sdk#10656]
### Description

When signing in anonymously, then linking the anonymous with an email/password credential, we always get the `creationDate` and `lastSignInDate` equals even tho we didn't create and sign in at the same time.

First reported here: https://github.com/firebase/flutterfire/issues/9640

### Reproducing the issue

```
[[FIRAuth auth] signInAnonymouslyWithCompletion:^(FIRAuthDataResult * _Nullable authResult,
                                                  NSError * _Nullable error) {
FIRAuthCredential *credential =
    [FIREmailAuthProvider credentialWithEmail:email
                                             password:password];
    [[FIRAuth auth].currentUser linkWithCredential:credential
    completion:^(FIRAuthDataResult *result, NSError *_Nullable error) {
// Expect creationDate and lastSignInDate to be different
}];

 }];

```

### Firebase SDK Version

10.3.0

### Xcode Version

14.2

### Installation Method

CocoaPods

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reporting this, @Lyokone. Per checking, I was able to reproduce the same behavior, but it seems like this is intended because when you sign in using an anonymous account, it will automatically create an account with a UUID and then it will login at the same time. If this is not the case, please share detailed steps to reproduce the issue.

**Comment by AdamBridges** [comment]
> Thanks for reporting this, @Lyokone. Per checking, I was able to reproduce the same behavior, but it seems like this is intended because when you sign in using an anonymous account, it will automatically create an account with a UUID and then it will login at the same time. If this is not the case, please share detailed steps to reproduce the issue.

Hello, I am the original poster of this issue in the flutterfire repo. 

Just to clarify on the issue, the account has already been created/linked: It's when an app is launched that the `creationTime` and `lastSignInTime` are the same. Signing out and back in will return the correct `creationTime` and `lastSignInTime` if getting the metadata directly from the firebase auth instance, but not from the listener that returns the user's metadata, so there's some sort of disconnect there.

**Comment by rizafran** [comment]
Hi @AdamBridges, regarding this statement:
> Just to clarify on the issue, the account has already been created/linked: It's when an app is launched that the creationTime and lastSignInTime are the same.

To see that we're on the same page, could you clarify the steps to replicate the issue below:
1. Sign in anonymously
2. Link to email/password account
3. Sign out
4. Sign in again using the email/pass account

If that's the case, I tested again and it's working fine on my end using the [`Auth.auth().addStateDidChangeListener`](https://firebase.google.com/docs/auth/ios/start#listen_for_authentication_state) since `userChanges().listen` is not available on native iOS.

**Comment by AdamBridges** [comment]
> Hi @AdamBridges, regarding this statement:
> > Just to clarify on the issue, the account has already been created/linked: It's when an app is launched that the creationTime and lastSignInTime are the same.
> 
> To see that we're on the same page, could you clarify the steps to replicate the issue below:
> 1. Sign in anonymously
> 2. Link to email/password account
> 3. Sign out
> 4. Sign in again using the email/pass account
> 
> If that's the case, I tested again and it's working fine on my end using the [`Auth.auth().addStateDidChangeListener`](https://firebase.google.com/docs/auth/ios/start#listen_for_authentication_state) since `userChanges().listen` is not available on native iOS.

Okay, then it's possible that the issue still lies in the firebase_auth package of the flutterfire repo.

@Lyokone should be able to clarify further.

**Comment by Lyokone** [comment]
Thanks for investigating, I'll have another look on my end
