### ISSUE TITLE
Firebase Dashboard / Crashlytics stopped working upon versioning to 10.3.0?

### ISSUE THREAD

**Issue by jack-dojo** [firebase/firebase-ios-sdk#10673]
### Description

We have versioned the firebase SDK from 8.15.0 to 10.3.0 and deployed to production, we have since, as adoption has increased, seen our daily active users falling down and realised its going to drop to zero, there are no received analytics in the analytics dashboard for the new version...

We have no idea what's causing this, is there a step we missed in this upgrade? We didnt make any other relevant code changes beyond versioning the SDK and switched it to SPM instead of Cocoapods

Thanks for any advice

### Firebase SDK Version

10.3.0

### Xcode Version

13.3.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
Did you add `-ObjC` to Other Linker Options in Build Settings? See Requirement #2 at https://github.com/firebase/firebase-ios-sdk/blob/master/SwiftPackageManager.md
