### ISSUE TITLE
Could not build Objective-C module 'Firebase' - Xcode 14.2, 

### ISSUE THREAD

**Issue by Faiz-rhm** [firebase/firebase-ios-sdk#10688]
### Description

I can build and run the app successfully in iOS on a real iphone device but when I try to archive it through the below error.

I also tried this https://github.com/firebase/firebase-ios-sdk/issues/9981#issuecomment-1175020732, it did not work.

<img width="270" alt="Screen Shot 2023-01-14 at 1 17 43 PM" src="https://user-images.githubusercontent.com/14290499/212464109-8bdcbc53-21af-45ee-9fd3-5749bf176918.png">

I have installed these:

firebase_core: ^2.4.1
firebase_messaging: ^14.2.1
firebase_analytics: ^10.1.0

### Firebase SDK Version

10.3.0

### Xcode Version

14.2

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, Messaging

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reaching out, @Faiz-rhm. Could you share your Podfile/Podfile.lock in order to reproduce the issue?

**Comment by Faiz-rhm** [comment]
This is caused by the scheme. I have set up multiple schemes. it was caused by one of them, As I changed the scheme it finally worked...

**Comment by Faiz-rhm** [comment]
This is caused by the scheme. I have set up multiple schemes. it was caused by one of them, As I changed the scheme it finally worked...
