### ISSUE TITLE
[auth] The resolver exposed in MFA is not associated to the correct app

### ISSUE THREAD

**Issue by Lyokone** [firebase/firebase-ios-sdk#10690]
### Description

When getting the `resolver` from key `"FIRAuthErrorUserInfoMultiFactorResolverKey"`, the resolver is associated with the default app name even though I signed in with an app name with a different app name.

first reported here: https://github.com/firebase/flutterfire/issues/10275

### Reproducing the issue

```obj-c
FIRAuth *auth = [FIRAuth authWithApp:app];

 [auth signInWithEmail:@"email"
               password:@"password"
             completion:^(FIRAuthDataResult *_Nullable authResult, NSError *_Nullable error) {
               if (error != nil) {
                 if (error.code == FIRAuthErrorCodeSecondFactorRequired) {
                   FIRMultiFactorResolver *resolver = (FIRMultiFactorResolver *)error.userInfo[FIRAuthErrorUserInfoMultiFactorResolverKey];
                   // here the resolver is associated with the wrong app name see screenshot

                 } else {
                   result.error(nil, nil, nil, error);
                 }
               } else {
                 result.success(authResult);
               }
             }];

```

![Screenshot 2023-01-16 at 16 23 59](https://user-images.githubusercontent.com/3680002/212714081-8ffcb1b8-66ca-4116-a228-7bc5dfe0eb39.png)

### Firebase SDK Version

10.3.0

### Xcode Version

14.2

### Installation Method

CocoaPods

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ryanwilson** [comment]
Thanks for the report, looks like this is the offending line: https://github.com/firebase/firebase-ios-sdk/blob/bdac2b87f6d6e604deae914a970a75136b3a62b5/FirebaseAuth/Sources/MultiFactor/FIRMultiFactorResolver.m#L47

**Comment by koenmuilwijk** [comment]
@ryanwilson thanks for investigating this and pointing out the possible cause.

Any idea when a fix will be available? This is blocking us from releasing MFA as we are using a custom Firebase app in our app.
