### ISSUE TITLE
Multiple constants have the same documentation comment

### ISSUE THREAD

**Issue by ryanwilson** [firebase/firebase-ios-sdk#10699]
Search `kFIRAuthErrorMessageSecondFactorRequired` and see all the duplicates (linked below).

https://github.com/firebase/firebase-ios-sdk/blob/0b3bf6124f6f9643b783c9e74aa9d38d7588b1ff/FirebaseAuth/Sources/Utilities/FIRAuthErrorUtils.m#L495-L559

**Comment by paulb777** [comment]
Can be fixed earlier, but marking to review for Firebase 11 at the latest.

**Comment by paulb777** [comment]
Fixed in Firebase 11.0.0.
