### ISSUE TITLE
Module 'Firebase' has no member named 'Analytics' in 10.3.0

### ISSUE THREAD

**Issue by varindersingh-dewsolutions-MarTech** [firebase/firebase-ios-sdk#10693]
### Description

Module 'Firebase' has no member named 'Analytics'
implementation
        Firebase.Analytics.setAnalyticsCollectionEnabled(true)

### Firebase SDK Version

10.3.0

### Xcode Version

14.2

### Installation Method

CocoaPods

### Firebase Product(s)

AB Testing, Analytics, Authentication, Crashlytics, DynamicLinks, In-App Messaging

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by varindersingh-dewsolutions-MarTech** [comment]
Got resolved by removing Firebase in front of Firebase.Analytics.setAnalyticsCollectionEnabled(true)
But where is the related doc ?

**Comment by rizafran** [comment]
Hi @varindersingh-dewsolutions-MarTech, good to hear that the issue has been resolved. Per checking, `Analytics.setAnalyticsCollectionEnabled(true)` is indicated on our [docs](https://firebase.google.com/docs/analytics/configure-data-collection?platform=ios#temporarily_disable_collection_2). I'll now be closing this ticket, but feel free to comment if you have any other questions.
