### ISSUE TITLE
[firestore] Requesting a wherefield:in: with more than 10 values result in a crash

### ISSUE THREAD

**Issue by Lyokone** [firebase/firebase-ios-sdk#10728]
### Description

Using [`wherefield:in:`](https://firebase.google.com/docs/reference/ios/firebasefirestore/api/reference/Classes/FIRQuery#-querywherefield:in:) with more than 10 values result in a crash in release mode when attaching a listener. I would expect an error to be thrown gracefully by the SDK.

First reported here: https://github.com/firebase/flutterfire/issues/10292

### Reproducing the issue

```
      [query addSnapshotListenerWithIncludeMetadataChanges:includeMetadataChanges.boolValue
                                                  listener:listener];
``` 

### Firebase SDK Version

10.3.0

### Xcode Version

14.2

### Installation Method

CocoaPods

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by MarkDuckworth** [comment]
Thanks for reporting this. I'll bring it up with the team and see if we can implement a better behavior in this scenario.

**Comment by 0xStef** [comment]
Any update on the iOS bug limiting us to 10 disjunctions instead of the 30 stated by the documentation?

From the [Firestore documentation](https://firebase.google.com/docs/firestore/query-data/queries#limits_on_or_queries):

> To prevent a query from becoming too computationally expensive, Cloud Firestore limits how many AND and OR clauses you can combine. To apply this limit, Cloud Firestore converts queries that perform logical OR operations (or, in, and array-contains-any) to [disjunctive normal form](https://en.wikipedia.org/wiki/Disjunctive_normal_form) (also known as an OR of ANDs). Cloud Firestore limits a query to a maximum of 30 disjunctions in disjunctive normal form.

**Comment by ehsannas** [comment]
@0xStef Are you experiencing this issue in the latest SDK? The limitation was removed a while ago via https://github.com/firebase/firebase-ios-sdk/pull/10449/files#diff-e11c1c8fc02726cb87283757008e935497911ea74a41f0efa93c4d2d6517d050L416-L421

**Comment by MarkDuckworth** [comment]
This limitation was removed in 10.7.0. I verified with a more recent version and I'm unable to reproduce the issue when using whererield:in: with 11 values. If there still appears to be an issue, let us know and we can re-open this.
