### ISSUE TITLE
The app references non-public selectors - Unable to upload app

### ISSUE THREAD

**Issue by aparnaredbus** [firebase/firebase-ios-sdk#10720]
### Description

We are using version 10.4.0 and get the error while uploading to AppStore:
 
"The app references non-public selectors in Payload/{app_name}.app/{app_name}: determineAppInstallationAttributionWithCompletionHandler:, lookupAdConversionDetails:"

### Firebase SDK Version

10.4.1

### Xcode Version

14.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, App Distribution, Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
@aparnaredbus Thanks for the report. Apple occasionally changes its submission criteria causing issue like this.

Those are symbols from the legacy Google Analytics product and not in Firebase.

Are you using the legacy Google Analytics or Google Tag Manager?

**Comment by tsunghung** [comment]
If you are using Google Tag Manager, please upgrade to v7.4.3.

**Comment by willbattel** [comment]
I just got this today after updating from Firebase 8.16.0 to 10.4.0. These are my dependencies:

<img width="847" alt="Screenshot 2023-01-26 at 11 20 30 PM" src="https://user-images.githubusercontent.com/13490339/215008661-9e9cebcd-136e-4a90-b57e-60eedfc760b6.png">

I'm going to try to submit for review anyways. Not sure if it will go through or not.

**Comment by willbattel** [comment]
Still getting this warning with SDK version 10.5.0. Would like to have it resolved but fortunately it does not seem to prevent app approval.

**Comment by paulb777** [comment]
@willbattel As pointed out above, we addressed this issue in GoogleTagManager 7.4.3. 

If you're seeing it in Firebase, please open another issue with the details.

**Comment by willbattel** [comment]
As mentioned in [my comment above](https://github.com/firebase/firebase-ios-sdk/issues/10720#issuecomment-1406001770), we're _not_ using GoogleTagManager (at least not directly, and it doesn't appear in our dependencies either). This issue started happening after we upgraded Firebase from 8.15.0 to 10.4.0. I'd be happy to open a new issue but it seemed like the OP of this issue was also not using GoogleTagManager, and that I was seeing the same problem, but perhaps I am misunderstanding.

**Comment by paulb777** [comment]
Here's an example of using the `nm` tool to check if a symbol is in the SPM checkout of a particular binary library:
```
~/Library/Developer/Xcode/DerivedData/ABTestingExample-gxybhvsgstennrbcutwsunxiezzv/SourcePackages/artifacts/firebase-ios-sdk/FirebaseAnalytics.xcframework/ios-arm64_armv7/FirebaseAnalytics.framework  $ nm FirebaseAnalytics | grep maxUserProperties
00000952 t -[FIRAnalytics maxUserPropertiesForOrigin:queue:callback:]
00000994 t -[FIRAnalyticsConnector maxUserProperties:]
00000b48 t ___43-[FIRAnalyticsConnector maxUserProperties:]_block_invoke
00000000000009f8 t -[FIRAnalytics maxUserPropertiesForOrigin:queue:callback:]
0000000000000b54 t -[FIRAnalyticsConnector maxUserProperties:]
0000000000000cb8 t ___43-[FIRAnalyticsConnector maxUserProperties:]_block_invoke
```
