### ISSUE TITLE
Could not resolve package graph. Cannot continue.

### ISSUE THREAD

**Issue by nolochemical** [firebase/firebase-ios-sdk#10739]
### Description

Could not resolve package graph. Cannot continue.

[DependencyResolver] derived 'firebase-ios-sdk' requirement '10.4.0..<11.0.0'

[DependencyResolver] resolving 'firebase-ios-sdk'

[DependencyResolver] resolved 'firebase-ios-sdk' @ '10.4.0'

[DependencyResolver] derived 'leveldb' requirement '1.22.2..<1.23.0'

[DependencyResolver] derived 'grpc-ios' requirement '1.44.0-grpc..<1.45.0-grpc'

[DependencyResolver] derived 'abseil-cpp-swiftpm' requirement '0.20220203.1..<0.20220204.0'

[DependencyResolver] derived 'nanopb' requirement '2.30909.0..<2.30910.0'

[DependencyResolver] derived 'gtm-session-fetcher' requirement '2.1.0..<4.0.0'

[DependencyResolver] derived 'googleutilities' requirement '7.10.0..<8.0.0'

[DependencyResolver] derived 'googledatatransport' requirement '9.2.0..<10.0.0'

[DependencyResolver] derived 'googleappmeasurement' requirement '10.4.0'

[DependencyResolver] derived 'swift-protobuf' requirement '1.19.0..<2.0.0'

[DependencyResolver] derived 'promises' requirement '2.1.0..<3.0.0'

[DependencyResolver] resolving 'leveldb'

[DependencyResolver] resolved 'leveldb' @ '1.22.2'

[DependencyResolver] resolving 'nanopb'

[DependencyResolver] resolved 'nanopb' @ '2.30909.0'

[DependencyResolver] resolving 'googleappmeasurement'

[DependencyResolver] resolved 'googleappmeasurement' @ '10.4.0'

[DependencyResolver] resolving 'abseil-cpp-swiftpm'

[DependencyResolver] resolved 'abseil-cpp-swiftpm' @ '0.20220203.2'

[DependencyResolver] resolving 'googleutilities'

[DependencyResolver] resolved 'googleutilities' @ '7.11.0'

[DependencyResolver] resolving 'googledatatransport'

[DependencyResolver] resolved 'googledatatransport' @ '9.2.1'

[DependencyResolver] resolving 'promises'

[DependencyResolver] resolved 'promises' @ '2.1.1'

[DependencyResolver] resolving 'grpc-ios'

[DependencyResolver] resolved 'grpc-ios' @ '1.44.3-grpc'

[DependencyResolver] resolving 'gtm-session-fetcher'

[DependencyResolver] resolved 'gtm-session-fetcher' @ '3.1.0'

[DependencyResolver] resolving 'swift-protobuf'

[DependencyResolver] resolved 'swift-protobuf' @ '1.20.3'

[DependencyResolver] solved 'firebase-ios-sdk' (http://github.com/firebase/firebase-ios-sdk/) at '10.4.0'

[DependencyResolver] solved 'gtm-session-fetcher' (https://github.com/google/gtm-session-fetcher.git) at '3.1.0'

[DependencyResolver] solved 'googleappmeasurement' (https://github.com/google/GoogleAppMeasurement.git) at '10.4.0'

[DependencyResolver] solved 'googledatatransport' (https://github.com/google/GoogleDataTransport.git) at '9.2.1'

[DependencyResolver] solved 'googleutilities' (https://github.com/google/GoogleUtilities.git) at '7.11.0'

[DependencyResolver] solved 'promises' (https://github.com/google/promises.git) at '2.1.1'

[DependencyResolver] solved 'swift-protobuf' (https://github.com/apple/swift-protobuf.git) at '1.20.3'

[DependencyResolver] solved 'abseil-cpp-swiftpm' (https://github.com/firebase/abseil-cpp-SwiftPM.git) at '0.20220203.2'

[DependencyResolver] solved 'grpc-ios' (https://github.com/grpc/grpc-ios.git) at '1.44.3-grpc'

[DependencyResolver] solved 'leveldb' (https://github.com/firebase/leveldb.git) at '1.22.2'

[DependencyResolver] solved 'nanopb' (https://github.com/firebase/nanopb.git) at '2.30909.0'

[DependencyResolver] solved 'temporarypackagebuild-62db112e-1440-4245-b76f-3a8cfec1a841' (/private/var/mobile/Containers/Data/Application/E89283B1-E94F-4F23-A5ED-61F8AFC59492/tmp/TemporaryPackageBuild-62DB112E-1440-4245-B76F-3A8CFEC1A841) at 'unversioned'

[DependencyResolver] dependency resolution complete!

Error Domain=NSCocoaErrorDomain Code=513 "“grpc-ios” couldn’t be removed because you don’t have permission to access it." UserInfo={NSUserStringVariant=(
    Remove
), NSFilePath=/var/mobile/Containers/Data/Application/E89283B1-E94F-4F23-A5ED-61F8AFC59492/Library/Caches/com.apple.Playgrounds/DerivedData/My App-cnzoujrlfdbbisaxhymtpguyerrj/SwiftPM/data/checkouts/grpc-ios, NSUnderlyingError=0x2804f0e10 {Error Domain=NSPOSIXErrorDomain Code=66 "Directory not empty"}}

### Reproducing the issue

On iPad create playground app 
-> click (+) add “ Swift package “
-> use http vs https url, https does not resolve at all..
http://github.com/firebase/firebase-ios-sdk/

### Firebase SDK Version

9.4.1

### Xcode Version

0.0.0.0

### Installation Method

Swift Package Manager

### Firebase Product(s)

All

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
There is likely a problem with your Xcode configuration.   Try removing the DerivedData directory and retry: `rm -rf /var/mobile/Containers/Data/Application/E89283B1-E94F-4F23-A5ED-61F8AFC59492/Library/Caches/com.apple.Playgrounds/DerivedData/My App-cnzoujrlfdbbisaxhymtpguyerrj`

**Comment by nolochemical** [comment]
Im working directly from the swift playgrounds on iPad

Moving from iPadOS 15.7.2 -> 16.3 
More to come..

**Comment by paulb777** [comment]
The last we checked there were several issues using Firebase in Swift Playgrounds - most notably that Playgrounds did not support SDKs that were implemented in Objective C.

**Comment by paulb777** [comment]
More context in #9107

**Comment by nolochemical** [comment]
Thanks seeing the challenges now, was worth a shot. 

Still hopeful about the SwiftPM semi-working the effort is apparent and appreciated. Not sure how to mark the issue if the package manager folder structure+perms issue still exists. 

Most likely use gcloud functions feature based on app events for now. Ideally working from an iPad pro and not having to code low level features was my initial ambition. 

@mortenbekditlevsen Can you share your resolution/work around, merci!

**Comment by paulb777** [comment]
Closing in favor of #9107
