### ISSUE TITLE
APM components generate a lot of crashes

### ISSUE THREAD

**Issue by linziyiwj** [firebase/firebase-ios-sdk#10749]
### Description

APM components produce many crashes, listed below：
<img width="1257" alt="WeChat5dbede1d1c9f9dae64f78d2861454192" src="https://user-images.githubusercontent.com/39822433/215374689-2a9374e6-c4f1-43fe-ad7d-92b16c55b019.png">
<img width="1256" alt="WeChate58c06e6f3cc70aef7ea214c16666921" src="https://user-images.githubusercontent.com/39822433/215374716-1c944f91-f9c0-438c-b387-a142f1d2d678.png">
<img width="1261" alt="WeChatbfb197182b8e12b5b32b78b00a911c0e" src="https://user-images.githubusercontent.com/39822433/215374721-f2c62147-792c-4f3a-afaf-080b0ce55c15.png">

Two of the problems are more serious, and the detailed stack is as follows：
1. apmpb_free_measurement_config_field
![image](https://user-images.githubusercontent.com/39822433/215375193-447f53e3-ac82-4108-ad45-3bfd9ff33333.png)

2. [APMSqliteStore ensureTableWithName:elementaryColumnInfo:addOnColumnInfo:error:] 
![image](https://user-images.githubusercontent.com/39822433/215375234-c258776d-12cc-4944-abb8-118d6d0b53af.png)

Please ask the official technical personnel to look at the problem, if you need more information, you can contact me again.

Thanks a lot!

### Firebase SDK Version

10.0.0

### Xcode Version

14.2

### Installation Method

CocoaPods

### Firebase Product(s)

AB Testing, Analytics, Crashlytics, In-App Messaging, Messaging, Remote Config

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by linziyiwj** [comment]
@rizafran 
hi, Is there any plan to fix the above crash?

**Comment by rizafran** [comment]
Thanks for reporting, @linziyiwj. Since I don't have visibility to your full stack trace, I'm wondering if your issue is related to #10495? With this, could you check if updating to the latest version fixes the issue?

**Comment by linziyiwj** [comment]
> Thanks for reporting, @linziyiwj. Since I don't have visibility to your full stack trace, I'm wondering if your issue is related to #10495? With this, could you check if updating to the latest version fixes the issue?

@rizafran According to the crash stack information, it is not the same problem as #10495

**Comment by rizafran** [comment]
@linziyiwj, could you give us the full stack trace in a `.txt` file so we can investigate this further? Thanks.

**Comment by linziyiwj** [comment]
> @linziyiwj, could you give us the full stack trace in a `.txt` file so we can investigate this further? Thanks.

@rizafran It is added to zip attachments, including the two crash issues mentioned above
[crash.zip](https://github.com/firebase/firebase-ios-sdk/files/10565649/crash.zip)

**Comment by tsunghung** [comment]
@linziyiwj Thanks for the info. To make the discussion more efficient, let's focus on the first case. Could you please provide more info?
1. What’s the version of Firebase Analytics and dependencies? Providing Package.resolved or Podfile.lock would be very helpful.
2. Did the issue happen across different iOS versions and device models? Or did it happen only on certain iOS versions or devices?
3. Did it happen after the app upgrade?
4. Can you reproduce the issue locally?

From the stack trace, the issue happened in the beginning of app launch during initialization. There are no complicated interactions. 129 crashes happened on 4 users only. I suspect they have database corruption.

**Comment by linziyiwj** [comment]
> @linziyiwj Thanks for the info. To make the discussion more efficient, let's focus on the first case. Could you please provide more info?
> 
> 1. What’s the version of Firebase Analytics and dependencies? Providing `Package.resolved` or `Podfile.lock` would be very helpful.
> 2. Did the issue happen across different iOS versions and device models? Or did it happen only on certain iOS versions or devices?
> 3. Did it happen after an app upgrade?
> 4. Can you reproduce the issue locally?
> 
> From the stack trace, the issue happened in the beginning of app launch during initialization. There are no complicated interactions. 129 crashes happened on 4 users only. I suspect they have database corruption.

At present, a total of 2 users have crashed, with a total of 200 crashes. And I can  not reproduce the issue locally
1. Firebase SDK Version：10.4.0
2. Device models and iOS versions
![image](https://user-images.githubusercontent.com/39822433/220235503-3566c05c-3baa-4e67-bb41-1cdc5f1ab100.png)
![image](https://user-images.githubusercontent.com/39822433/220235545-4a915a63-86ec-4f5e-80fc-217372697706.png)

**Comment by tsunghung** [comment]
@linziyiwj Thanks a lot for the update. However, we still don't know why it crashes. It only happens to a few users and cannot be reproduced locally. There could be many reasons, e.g. unstable jailbreak, corrupted database, memory corruption, etc. It's interesting that the user keeps on launching the app without reinstalling it? Or maybe reinstalling didn't solve the problem?
Anyway, please keep us updated if you have more insight. For now, I don't see any problem in the stacktrace code, so we can't provide a fix.

**Comment by linziyiwj** [comment]
> @linziyiwj Thanks a lot for the update. However, we still don't know why it crashes. It only happens to a few users and cannot be reproduced locally. There could be many reasons, e.g. unstable jailbreak, corrupted database, memory corruption, etc. It's interesting that the user keeps on launching the app without reinstalling it? Or maybe reinstalling didn't solve the problem? Anyway, please keep us updated if you have more insight. For now, I don't see any problem in the stacktrace code, so we can't provide a fix.

Has this crash been resolved?
> [APMSqliteStore ensureTableWithName:elementaryColumnInfo:addOnColumnInfo:error:]

**Comment by tsunghung** [comment]
I went through the callstack, and I couldn't find a problem. The strings used in [NSString appendFormat:] are hard-coded predefined strings. If something is wrong with these strings, it should always crash. Other than out of memory or memory corruption, I can't think of any reason why it would crash there.

Do you see any similarities, e.g. device models, iOS versions, app versions, SDK versions, between these crashes?

**Comment by linziyiwj** [comment]
> 

@tsunghung 
Crash occurs within 1 second of app launch

![image](https://user-images.githubusercontent.com/39822433/221495298-1dabc298-6b33-4c34-87d0-e12a0b1ab09b.png)
![image](https://user-images.githubusercontent.com/39822433/221494948-84369798-2f9d-4cf6-9937-dbd44e775ba7.png)
![image](https://user-images.githubusercontent.com/39822433/221495035-3b7a5de5-31dc-434b-b288-bbb039a3a1cb.png)

**Comment by tsunghung** [comment]
Yes, this problem also occurred during initialization.
Did all crashes occur only on iOS 16?

**Comment by linziyiwj** [comment]
> Yes, this problem also occurred during initialization. Did all crashes occur only on iOS 16?

@tsunghung ，YES, all crashes occur only on iOS 16

**Comment by linziyiwj** [comment]
> 

@tsunghung hi, Is there a solution to this problem?

**Comment by linziyiwj** [comment]
@tsunghung  hello, is there any solution?

**Comment by tsunghung** [comment]
Sorry, I don't have a solution.

_"I went through the callstack, and I couldn't find a problem. The strings used in [NSString appendFormat:] are hard-coded predefined strings. If something is wrong with these strings, it should always crash. Other than out of memory or memory corruption, I can't think of any reason why it would crash there."_

Have you seen more crashes in the same place? Are they all iOS 16?

**Comment by linziyiwj** [comment]
> Sorry, I don't have a solution.
> 
> _"I went through the callstack, and I couldn't find a problem. The strings used in [NSString appendFormat:] are hard-coded predefined strings. If something is wrong with these strings, it should always crash. Other than out of memory or memory corruption, I can't think of any reason why it would crash there."_
> 
> Have you seen more crashes in the same place? Are they all iOS 16?

@tsunghung At present, I only encountered this crash problem, and they are all in iOS16
