### ISSUE TITLE
Crashlytics command line upload-symbols finishes successfully but Firebase console still shows missing DSYM

### ISSUE THREAD

**Issue by alexeystrakh** [firebase/firebase-ios-sdk#10779]
### Description

I'm using `upload-symbols` command line to upload symbols after a successful build, but for some reason the crashes in Firebase are still not symbolicated and says that DSYM is missing. If I upload exactly the same package via Firebase Console UI, the crashes become symbolicated and the warning disappeared. Reproduced consistently with each release.

```
Pods/FirebaseCrashlytics/upload-symbols -gsp GoogleService-Info.plist -p ios mycoolapp.dSYMs.zip
```

In response I'm getting the following output

```
Successfully submitted symbols for architecture arm64 with UUID xxx in dSYM: /var/folders/xxx.dSYMs.zip.unzipped/xxx.framework.dSYM
Successfully submitted symbols for architecture arm64 with UUID xxx in dSYM: /var/folders/yyy.dSYMs.zip.unzipped/yyy.framework.dSYM
....
Successfully uploaded Crashlytics symbols
```

The DSYM package is valid because when I upload it via UI, it works.
The plist metadata is valid, freshly downloaded from the Firebase console.

### Firebase SDK Version

9.3.0

### Xcode Version

14.2

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, Crashlytics, Messaging, Remote Config

### Targeted Platforms

iOS

### Relevant Log Output

```shell
> Pods/FirebaseCrashlytics/upload-symbols -gsp GoogleService-Info.plist -p ios mycoolapp.dSYMs.zip

Successfully submitted symbols for architecture arm64 with UUID xxx in dSYM: /var/folders/xxx.dSYMs.zip.unzipped/xxx.framework.dSYM
Successfully submitted symbols for architecture arm64 with UUID xxx in dSYM: /var/folders/yyy.dSYMs.zip.unzipped/yyy.framework.dSYM
....
Successfully uploaded Crashlytics symbols
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

  - FirebaseCrashlytics (9.3.0):
    - FirebaseCore (~> 9.0)
    - FirebaseInstallations (~> 9.0)
    - GoogleDataTransport (< 10.0.0, >= 9.1.4)
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (~> 2.1)


  FirebaseCrashlytics: 65a5b349e664e986e6c7486b0a9b5ed8c11d0491
```

</details>

**Comment by jvanderwee** [comment]
We noticed the same issue with our first upload on Xcode 14.2 🤔

**Comment by rizafran** [comment]
Hi @alexeystrakh, based on your logs, the dSYMs were successfully uploaded but still missing in the console. With this, you may try the troubleshooting steps on our [docs](https://firebase.google.com/docs/crashlytics/troubleshooting?platform=ios#ios-locate-dsyms) and see if it fixes the issue. Otherwise, please file a ticket via our [support channel](https://firebase.google.com/support) so the team can investigate your project and check your configurations. I'll now be closing this issue.
