### ISSUE TITLE
[Crashlytics] [Maui] [iOS] Unable to upload symbols

### ISSUE THREAD

**Issue by mdima** [firebase/firebase-ios-sdk#10851]
### Description

Using Visual Studio per Windows when I build a Maui project for iOS the dSYM symbols are not uploaded to Google. 

In the build log I find a: 
error: Unable to read Google Service plist at path ./GoogleService-Info.plist

### Reproducing the issue

- Create a .Net MAUI project and compile it for the iOS platform. 
- Add a GoogleService-Info.plist according to the one you created from the Firebase Console.
- The GoolgeService-Info.plist should be added to the project like: 
   `<MauiAsset Include="Platforms\iOS\GoogleService-Info.plist" Link="GoogleService-Info.plist" />`
  to let Crashlytics find the file in rumtime. 
- Build the app and you will find the error above. 

### Firebase SDK Version

8.10.0.3

### Xcode Version

14.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
6>/usr/bin/codesign --verify -vvvv "-R=anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.1] exists and (certificate leaf[field.1.2.840.113635.100.6.1.2] exists or certificate leaf[field.1.2.840.113635.100.6.1.4] exists)" bin/Debug/net6.0-ios/ios-arm64/device-builds/ipad12.1-16.3.1//LifeChartApp.app
6>chmod +x upload-symbols.sh
6>'./upload-symbols.sh' -gsp './GoogleService-Info.plist' -p ios './bin/Debug/net6.0-ios/ios-arm64/device-builds/ipad12.1-16.3.1/LifeChartApp.app.dSYM'
6>[31merror: Unable to read Google Service plist at path ./GoogleService-Info.plist[0m
6>D:\Nuget\xamarin.firebase.ios.crashlytics\8.10.0.3\buildTransitive\Xamarin.Firebase.iOS.Crashlytics.targets(59,5): warning MSB3073: The command "'./upload-symbols.sh' -gsp './GoogleService-Info.plist' -p ios './bin/Debug/net6.0-ios/ios-arm64/device-builds/ipad12.1-16.3.1/LifeChartApp.app.dSYM'" exited with code 13.
6>Done building project "LifeChartApp.csproj".
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @mdima, based on the error you shared, it seems that there's something missing in the configuration of your `GoogleService-Info.plist`'s path. With this, you may double-check if the path and location of your `.plist` file is correct. 

Given that the concern requires specific implementations, the level of expertise required may be better suited to Xamarin specialists. Also, as mentioned by engineer [here](https://github.com/firebase/firebase-ios-sdk/issues/8970#issuecomment-1029293250), we don't currently have plans to support Xamarin. You could try creating an issue in [Xamarin repo](https://github.com/xamarin/XamarinComponents/issues), so they will be able to investigate this issue further. With that said, I'll be closing this issue.

**Comment by mdima** [comment]
Hi @rizafran , yes, I think this issue is Xamarin specific. I realize now that this repo is for the generic development under iOS. 

Thanks anyway,
Michele
