### ISSUE TITLE
A lot of "No such file or directory warnings"

### ISSUE THREAD

**Issue by NicolaiBure** [firebase/firebase-ios-sdk#10865]
### Description

When I add Firebase (Analytics, Chashlytics and Auth) it appears a lot of warnings like:

/Users/****/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3W36T5ZLGZ3AN/asl-MI6WZSG1PNOM.pcm: No such file or directory

/Users/***/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/2DGK31ET3OB5M/FirebaseCoreExtension-3197ZAXA5PZDX.pcm: No such file or directory

That problem is only that in the Issues navigator appears close to 90 warnings.

I added the Firebase SDK using SPM.

Is something that I can do about this?

### Reproducing the issue

I added the Firebase SDK using SPM.

### Firebase SDK Version

10.4.0

### Xcode Version

14.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Authentication, Crashlytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
/Users/****/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3W36T5ZLGZ3AN/asl-MI6WZSG1PNOM.pcm: No such file or directory

/Users/***/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/2DGK31ET3OB5M/FirebaseCoreExtension-3197ZAXA5PZDX.pcm: No such file or directory
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reporting, @NicolaiBure. I'm unable to reproduce the issue using the iOS quickstart. With this, could you try the following to see if that will fix the issue:
- Delete your Xcode's derived data
- Open File > Packages then click  Reset package caches

**Comment by Tak783** [comment]
**I've been having this problem for a week.** 
I get this `Error while fetching remote repository/{path_to_my_mac}/Developer/Xcode/DerivedData/Honeybee-grekqzbujxilgxedptygzmajjfel/SourcePackages/repositories/firebase-ios-sdk-c63c6384: An unknown error occurred. reference 'refs/remotes/origin/master' not found (-1)`

**I've tried all of the usual things in many possible orders**
* Deleting derived data
* Clean, build 
* Resolve package dependencies from terminal 
* Reset package cache from terminal 
* Update to the latest package versions
* Uninstall / re-install firebase (with the old way of setting up the run script phase, and also the new way)
* Changing the location of my derived data 
* Installing firebase only via package JSON 
* Installing older versions of the packages
* Rolling back to a time when firebase was stable in my repo (issue persists)
* Fresh clone of my repo

**Heres is what I found** 
* I did a fresh clone on my 2020 Intel mac, it worked 
* It seems to be an issue with the 2022 mac pro m2, might be an apple silicon
