### ISSUE TITLE
FIRUser Object is Equatable but Not With the Expected Logic

### ISSUE THREAD

**Issue by dooinwell** [firebase/firebase-ios-sdk#10863]
### Description

I have a piece of code that retrieves a FIRUser object through two different methods: Auth.auth().currentUser, and getStoredUser(forAccessGroup accessGroup: [String]). 

I'm comparing the two FIRUser objects to assess whether they relate to the same user account. Doing so naively with currentUser == storedUser appears to not perform the expected logic. 

currentUser == storedUser can return False while currentUser?.uid == storedUser?.uid will return True. 

I guess the FIRUser objects equality may be requiring that all the FIRUser properties are equal, but I must say this is a bit unexpected, and would be worth a warning in the documentation. 

### Reproducing the issue

 let currentUser = Auth.auth().currentUser
 let sharedUser = try Auth.auth().getStoredUser(forAccessGroup: XXXXX)
 print("Current user: \(currentUser?.uid), shared User: \(sharedUser?.uid)")
 print("Equality: \(currentUser == sharedUser)")

### Firebase SDK Version

10.3

### Xcode Version

14.1

### Installation Method

CocoaPods

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by renkelvin** [comment]
> I guess the FIRUser objects equality may be requiring that all the FIRUser properties are equal
You're right that the equality check on 2 objects requires deep comparison. Please use `currentUser?.uid == storedUser?.uid` instead. Thanks for pointing this out.
