### ISSUE TITLE
'firebase-ios-sdk' depends on 'googleappmeasurement' 10.6.0

### ISSUE THREAD

**Issue by saldous** [firebase/firebase-ios-sdk#10867]
### Description

Failed to resolve dependencies Dependencies could not be resolved because no versions of 'googleappmeasurement' match the requirement 10.6.0 and 'firebase-ios-sdk' depends on 'googleappmeasurement' 10.6.0.

Seems latest pod of googleappmeasurement is v10.5.0? So why is Firebase requiring 10.6.0?

### Reproducing the issue

Failed to resolve dependencies Dependencies could not be resolved because no versions of 'googleappmeasurement' match the requirement 10.6.0 and 'firebase-ios-sdk' depends on 'googleappmeasurement' 10.6.0.

Seems latest pod of googleappmeasurement is v10.5.0? So why is Firebase requiring 10.6.0?

### Firebase SDK Version

10.6.0

### Xcode Version

14.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

In-App Messaging

### Targeted Platforms

iOS

### Relevant Log Output

```shell
pod 'GoogleMobileAdsMediationFacebook'
pod 'FBAudienceNetwork'
pod 'GoogleMobileAdsMediationAppLovin'
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by saldous** [comment]
Cleaned build folder and it fixed!

**Comment by shobith10** [comment]
> Cleaned build folder and it fixed!

No it did not fixed for me!!

**Comment by eecklund** [comment]
Having the exact same issue.   I am only doing clean builds.

**Comment by shobith10** [comment]
> Having the exact same issue with clean builds. Also, I was building from master. Switched to 10.5.0 and seems to work again.

okey when i changed to 10.5 it worked!
