### ISSUE TITLE
FIRRemoteConfigValue.stringValue is not nullable

### ISSUE THREAD

**Issue by myihsan** [firebase/firebase-ios-sdk#10870]
### Description

FIRRemoteConfigValue.stringValue is marked `nullable` in the header file but will never return `null` as the implement.
https://github.com/firebase/firebase-ios-sdk/blob/60f9a33e7084482df67b48e16f315f4f7a6f5da9/FirebaseRemoteConfig/Sources/FIRConfigValue.m#L43-L46
It would be thankful to implement it as `nullable`, before that marking it `nonnull` would be enough.

### Firebase SDK Version

9.6.0

### Xcode Version

14.1

### Installation Method

CocoaPods

### Firebase Product(s)

Remote Config

### Targeted Platforms

iOS

**Comment by ncooke3** [comment]
Hi @myihsan,

Thanks for opening an issue. Just so I understand the issue correctly, is the issue that the implementation's return type does not have the `nullable` attribute?

So something like the below diff:
```diff
- - (NSString *)stringValue { 
+ - (nullable NSString *)stringValue { 
```

**Comment by myihsan** [comment]
Hi @ncooke3,

Thanks for the confirmation.
If I understand the implementation correctly, adding the `nullable` attribute will not solve the issue since it's already `nullable` in the header file.
https://github.com/firebase/firebase-ios-sdk/blob/60f9a33e7084482df67b48e16f315f4f7a6f5da9/FirebaseRemoteConfig/Sources/Public/FirebaseRemoteConfig/FIRRemoteConfig.h#L110


I expected it to be solved like the below:
```swift
- (NSString *)stringValue {
  // if `_data` is nil or empty return nil.
  if (!_data) {
    return nil;
  }
  return [[NSString alloc] initWithData:_data encoding:NSUTF8StringEncoding];
}
```

But it will affect `numberValue` and `boolValue`, so it may need some discussion before changing them to`nullable`.

Before that, marking `stringValue` `nonnull` would be enough for me.

```diff
- @property(nonatomic, readonly, nullable) NSString *stringValue;
+ @property(nonatomic, readonly, nonnull) NSString *stringValue;
```

**Comment by ncooke3** [comment]
I think what is going on here is that Apple's documentation is misleading. Based on [this discussion section](https://developer.apple.com/documentation/foundation/nsstring/1416374-initwithdata#:~:text=Returns%20nil%20if%20the%20initialization%20fails%20for%20some%20reason%20(for%20example%20if%20data%20does%20not%20represent%20valid%20data%20for%20encoding).) and that [Swift equivalent returns `String?`](https://developer.apple.com/documentation/foundation/nsstring/1416374-init), I think`- [NSString initWithData:encoding:]` returns a nullable string, despite it's interface saying it doesn't.

**Comment by myihsan** [comment]
>  I think - [NSString initWithData:encoding:] returns a nullable string

You are right and [the return value section](https://developer.apple.com/documentation/foundation/nsstring/1416374-initwithdata#return_value) mentioned that.

> Returns nil if the initialization fails for some reason (for example if data does not represent valid data for encoding).

However, it will not return nil in the cases below:
- `[[NSString alloc] initWithData:[[NSData alloc] init] encoding:NSUTF8StringEncoding]`
- `[[NSString alloc] initWithData:nil encoding:NSUTF8StringEncoding]`

You can verify this behavior by:

```objc
NSLog(@"%@", [[NSString alloc] initWithData:[[NSData alloc] init] encoding:NSUTF8StringEncoding] == nil ? @"True" : @"False");
NSLog(@"%@", [[NSString alloc] initWithData:nil encoding:NSUTF8StringEncoding] == nil ? @"True" : @"False");
```

**Comment by ncooke3** [comment]
Thanks @myihsan, that's interesting. Sorry, so what exactly is the issue with the current behavior? Is it that you expected `- [FIRRemoteConfigValue stringValue]` to return `nil` when `_data` is `nil`?

**Comment by myihsan** [comment]
Yes or no since I am unsure when `_data` became `nil`.
I expected `- [FIRRemoteConfigValue stringValue]` to return `nil` when no related config is set.

I want to distinguish the situations below:
- nil (there is no related config set)
- empty (there is a related config, but the value is empty)

**Comment by myihsan** [comment]
@ncooke3 
I tried to solve this issue [here](https://github.com/firebase/firebase-ios-sdk/compare/master...myihsan:fix/FIRRemoteConfigValue-stringValue-nullable), but I realised that this will at least make dataValue `nullable` and this is an API change.
Should I open another issue focusing on distinguishing the config is set as empty or not set at all.

**Comment by paulb777** [comment]
While we may progress earlier, I'll mark this as Firebase 11 to make sure we consider before our next breaking change release.
