### ISSUE TITLE
Carthage installation not working out of the box

### ISSUE THREAD

**Issue by GlebsUrtans** [firebase/firebase-ios-sdk#10885]
### Description

When the firebase is added to project via carthage, there seems to be some dependency issues.
I get an error :
**Undefined symbol: _OBJC_CLASS_$_FIRInstanceID**

As far as i understood, it refers to FirebaseInstaceID, but if i use old one, it throws an exception : Thread 1: "Firebase Instance ID is not compatible with Firebase 8.x+. Please remove the dependency from the app. See the documentation at https://firebase.google.com/docs/cloud-messaging/ios/client#fetching-the-current-registration-token."

### Reproducing the issue

binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseMessagingBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashBinary.json"

cartfile.resolved:
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" "10.6.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashBinary.json" "5.20.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseMessagingBinary.json" "10.6.0"

### Firebase SDK Version

10.6.0

### Xcode Version

14.2 M1 chip

### Installation Method

Carthage

### Firebase Product(s)

All

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Ld /Users/glebs.urtans/Library/Developer/Xcode/DerivedData/VanLanschot-diiffuclxqbcbbdkttzoxojdkdlh/Build/Products/Debug-iphonesimulator/VanLanschot-ci.app/VanLanschot-ci normal (in target 'VanLanschot-ci' from project 'VanLanschot')
    cd /Users/glebs.urtans/Documents/EVI
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios13.0-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.2.sdk -L/Users/glebs.urtans/Library/Developer/Xcode/DerivedData/VanLanschot-diiffuclxqbcbbdkttzoxojdkdlh/Build/Intermediates.noindex/EagerLinkingTBDs -L/Users/glebs.urtans/Library/Developer/Xcode/DerivedData/VanLanschot-diiffuclxqbcbbdkttzoxojdkdlh/Build/Products/Debug-iphonesimulator -L/Users/glebs.urtans/Documents/EVI/Frameworks/GoogleAnalytics/Libraries -F/Users/glebs.urtans/Library/Developer/Xcode/DerivedData/VanLanschot-diiffuclxqbcbbdkttzoxojdkdlh/Build/Intermediates.noindex/EagerLinkingTBDs -F/Users/glebs.urtans/Library/Developer/Xcode/DerivedData/VanLanschot-diiffuclxqbcbbdkttzoxojdkdlh/Build/Products/Debug-iphonesimulator -F/Users/glebs.urtans/Documents/EVI/Frameworks -F/Users/glebs.urtans/Documents/EVI/Carthage/Build/iOS -F/Users/glebs.urtans/Documents/EVI/Carthage/Build -filelist /Users/glebs.urtans/Library/Developer/Xcode/DerivedData/VanLanschot-diiffuclxqbcbbdkttzoxojdkdlh/Build/Intermediates.noindex/VanLanschot.build/Debug-iphonesimulator/VanLanschot-ci.build/Objects-normal/x86_64/VanLanschot-ci.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/glebs.urtans/Library/Developer/Xcode/DerivedData/VanLanschot-diiffuclxqbcbbdkttzoxojdkdlh/Build/Intermediates.noindex/VanLanschot.build/Debug-iphonesimulator/VanLanschot-ci.build/Objects-normal-tsan/x86_64/VanLanschot-ci_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fsanitize\=thread -Xlinker -debug_variant -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/glebs.urtans/Library/Developer/Xcode/DerivedData/VanLanschot-diiffuclxqbcbbdkttzoxojdkdlh/Build/Intermediates.noindex/VanLanschot.build/Debug-iphonesimulator/VanLanschot-ci.build/Objects-normal-tsan/x86_64/VanLanschot_ci.swiftmodule -ObjC -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/glebs.urtans/Library/Developer/Xcode/DerivedData/VanLanschot-diiffuclxqbcbbdkttzoxojdkdlh/Build/Intermediates.noindex/VanLanschot.build/Debug-iphonesimulator/VanLanschot-ci.build/VanLanschot-ci.app-Simulated.xcent -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __ents_der -Xlinker /Users/glebs.urtans/Library/Developer/Xcode/DerivedData/VanLanschot-diiffuclxqbcbbdkttzoxojdkdlh/Build/Intermediates.noindex/VanLanschot.build/Debug-iphonesimulator/VanLanschot-ci.build/VanLanschot-ci.app-Simulated.xcent.der -framework CoreTelephony -framework FBLPromises -framework FirebaseAnalytics -framework FirebaseAnalyticsSwift -framework FirebaseCore -framework FirebaseCoreInternal -framework FirebaseInstallations -framework FirebaseMessaging -framework GoogleAppMeasurement -framework GoogleAppMeasurementIdentitySupport -framework GoogleDataTransport -framework GoogleUtilities -framework FirebaseCrash -framework GoogleToolboxForMac -framework Protobuf -framework nanopb -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/glebs.urtans/Library/Developer/Xcode/DerivedData/VanLanschot-diiffuclxqbcbbdkttzoxojdkdlh/Build/Intermediates.noindex/VanLanschot.build/Debug-iphonesimulator/VanLanschot-ci.build/Objects-normal-tsan/x86_64/VanLanschot-ci_dependency_info.dat -o /Users/glebs.urtans/Library/Developer/Xcode/DerivedData/VanLanschot-diiffuclxqbcbbdkttzoxojdkdlh/Build/Products/Debug-iphonesimulator/VanLanschot-ci.app/VanLanschot-ci

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FIRInstanceID", referenced from:
      objc-class-ref in FirebaseCrash(FCRCrashUploader_0bdf1031228f85fd2ab55406b2629990.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
FirebaseCrash is a long deprecated product. Use FirebaseCrashlytics instead.

**Comment by GlebsUrtans** [comment]
I have replaced the FirebaseCrash with FirebaseCrashlytics, but now i get more errors:
ld: warning: Could not find or use auto-linked framework 'Promises'
Undefined symbols for architecture x86_64:
  "_$s8Promises3all2on_AA7PromiseCySayxGGSo17OS_dispatch_queueC_q_tSTR_AEyxG7ElementRt_r0_lF", referenced from:
      _$s16FirebaseSessions0B0C5appID16sessionGenerator11coordinator9initiator0C4Info8settings19loggedEventCallbackACSS_AA07SessionF0CAA0N19CoordinatorProtocol_pAA0N9InitiatorCAA011ApplicationiP0_pAA08SettingsP0_pys6ResultOyytAA0aB5ErrorOGctcfcyycfU0_ in FirebaseSessions(FirebaseSessions.o)
  "_$s8Promises7PromiseC4then2on_ACyxGSo17OS_dispatch_queueC_yxKctF", referenced from:
      _$s16FirebaseSessions0B0C5appID16sessionGenerator11coordinator9initiator0C4Info8settings19loggedEventCallbackACSS_AA07SessionF0CAA0N19CoordinatorProtocol_pAA0N9InitiatorCAA011ApplicationiP0_pAA08SettingsP0_pys6ResultOyytAA0aB5ErrorOGctcfcyycfU0_ in FirebaseSessions(FirebaseSessions.o)
  "_$s8Promises7PromiseC7fulfillyyxF", referenced from:
      _$s16FirebaseSessions0B0C8register10subscriberyAA0B10Subscriber_p_tF in FirebaseSessions(FirebaseSessions.o)
  "_$s8Promises7PromiseC7pendingACyxGyFZ", referenced from:
      _$s16FirebaseSessions0B0C5appID16sessionGenerator11coordinator9initiator0C4Info8settings19loggedEventCallbackACSS_AA07SessionF0CAA0N19CoordinatorProtocol_pAA0N9InitiatorCAA011ApplicationiP0_pAA08SettingsP0_pys6ResultOyytAA0aB5ErrorOGctcfcTf4nneneenn_nAA0nO0C_AA0rI0CAA0bS0CTg5Tf4ggngnngn_n in FirebaseSessions(FirebaseSessions.o)
  "_$s8Promises7PromiseCMa", referenced from:
      _$s8Promises7PromiseCyytGMa in FirebaseSessions(FirebaseSessions.o)
  "_$s8Promises7PromiseCMn", referenced from:
      _symbolic SDy__________yytGG 16FirebaseSessions0B14SubscriberNameO 8Promises7PromiseC in FirebaseSessions(FirebaseSessions.o)
      _symbolic _____yytG 8Promises7PromiseC in FirebaseSessions(FirebaseSessions.o)
      _symbolic _____y__________yytG_G SD6ValuesV 16FirebaseSessions0C14SubscriberNameO 8Promises7PromiseC in FirebaseSessions(FirebaseSessions.o)
      _symbolic _____y__________yytGG s18_DictionaryStorageC 16FirebaseSessions0D14SubscriberNameO 8Promises7PromiseC in FirebaseSessions(FirebaseSessions.o)
      _symbolic _____y__________yytGG s18_DictionaryStorageC 16FirebaseSessions0D14SubscriberNameO 8Promises7PromiseC in FirebaseSessions(RemoteSettings.o)
  "_$sSo17OS_dispatch_queueC8PromisesE8promisesABvgZ", referenced from:
      _$s16FirebaseSessions0B0C5appID16sessionGenerator11coordinator9initiator0C4Info8settings19loggedEventCallbackACSS_AA07SessionF0CAA0N19CoordinatorProtocol_pAA0N9InitiatorCAA011ApplicationiP0_pAA08SettingsP0_pys6ResultOyytAA0aB5ErrorOGctcfcyycfU0_ in FirebaseSessions(FirebaseSessions.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I did add the FBLPromises, but it's not helping.

**Comment by paulb777** [comment]
Hmm, those errors look like FBLPromises isn't properly linked. We may need a reproducible example to help.
