### ISSUE TITLE
Crashlytics `No such file or directory`

### ISSUE THREAD

**Issue by Tak783** [firebase/firebase-ios-sdk#10886]
### Description

**I've been having this problem for a week.** 
I get this `
Showing Recent Issues
/{my_directory}/Build/Intermediates.noindex/{our_app}.build/Release-iphonesimulator/{_our_app}.build/Script-8BADECAA29B0B1D8008ACB0E.sh: line 2: /Users/{my_directory}/Repos/{_our_app}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run: No such file or directory`

**I've tried all of the usual things in many possible orders**
* Deleting derived data
* Clean, build 
* Resolve package dependencies from terminal 
* Reset package cache from terminal 
* Update to the latest package versions
* Uninstall / re-install firebase (with the old way of setting up the run script phase, and also the new way)
* Changing the location of my derived data 
* Installing firebase only via package JSON 
* Installing older versions of the packages
* Rolling back to a time when firebase was stable in my repo (issue persists)
* Fresh clone of my repo
* Brand new app

**Heres is what I found** 
* I did a fresh clone on my 2020 Intel mac, it worked 
* It seems to be an issue with the 2022 mac pro m2, might be an apple silicon 

### Reproducing the issue

* Create a new xcode project 
* Install firebase with Crashlytics 
* Run the app

The app does not build as the error shows

### Firebase SDK Version

10.6.0

### Xcode Version

14.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
/{my_directory}/Build/Intermediates.noindex/{our_app}.build/Release-iphonesimulator/{_our_app}.build/Script-8BADECAA29B0B1D8008ACB0E.sh: line 2: /Users/{my_directory}/Repos/{_our_app}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run: No such file or directory`
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by samedson** [comment]
Hey @Tak783, I've setup Crashlytics on an M1 Macbook Pro and successfully run the run script using the instructions from the Firebase [Get Started with Crashlytics](https://firebase.google.com/docs/crashlytics/get-started?platform=ios) docs. I don't think there's something about Apple Silicon alone that's causing this, but maybe it combined with another factor is causing the problem.

Can you try putting `run` and `upload-symbols` on a known path in your computer, and updating the Build Phase in Xcode to point to it? I'm trying to determine if there's something wrong with the `${BUILD_DIR%/Build/*}` path expansion that we suggest in the Getting Started docs, or if there's something about your machine that doesn't recognize the `run` script. You can find `run` and `upload-symbols` [here](https://github.com/firebase/firebase-ios-sdk/tree/master/Crashlytics) if you can't find them on your computer.

A couple other things to try:
 - Make sure `run` and `upload-symbols` are executable (`chmod +x <path>`).
 - I wonder if changing the path of Derived Data is impacting this. Is it possible to reset it to the default value?
