### ISSUE TITLE
IOS doesn't receive Dynamic Links on first install (No pre-install link matched for this device)

### ISSUE THREAD

**Issue by scotch-formitable** [firebase/firebase-ios-sdk#10915]
### Description

Referencing an old issue that was closed by the bot: #7406

[#7406](https://github.com/firebase/firebase-ios-sdk/issues/7406
)

We are seeing an issue where the deferred dynamic link is not picked up when using the Skip app preview for ios.
In the console is: (No pre-install link matched for this device)

Can we reopen this old issue or look into this properly as its affecting us and undocumented.

### Reproducing the issue

Steps to reproduce:
1. App not installed previously
2. Tap Dynamic Link
3. Device show App Store page for app
4. From Xcode build and run app
5. Wait for console error "No pre-install link matched for this device"

### Firebase SDK Version

firebase_dynamic_links: ^5.0.15,  firebase_core: ^2.5.0

### Xcode Version

14.2.0

### Installation Method

CocoaPods

### Firebase Product(s)

DynamicLinks

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ruairioliverwv** [comment]
I'm stuck on this as well. I'm using a custom domain. If I use the firebase default domain it works fine. 

There are a few issues related to this and they keep getting closed. It's a valid issue.

**Comment by rizafran** [comment]
Sorry for the trouble. I've raised this issue to the FDL team, and I'll let you know once I got an update.

**Comment by ruairioliverwv** [comment]
Thanks @rizafran, much appreciated!

**Comment by paulb777** [comment]
The Firebase Dynamic Links service will be shutdown on August 25, 2025.  In the meantime, only critical or security issues will be fixed in the SDK.

More at https://firebase.google.com/support/dynamic-links-faq
