### ISSUE TITLE
Firestore Emulator Security Rule request.auth is always null even after authed

### ISSUE THREAD

**Issue by b-onc** [firebase/firebase-ios-sdk#10935]
### Description

When Firestore Emulator is used with the Firestore iOS SDK, and correctly configured to connect to it, `request.auth` is always null. This is the same issue as was reported in #5072 and was resolved by #5420

Reading resolution PR #5420, the problem was the underlying c library dropping auth header since connection was insecure, so the solution was a workaround to add auth header as metadata to request (with `authorization` name).

My best guess is that the WS library got updated and now it's smart enough to drop `authorization` metadata because connection is insecure, breaking this feature again.

![SCR-20230310-la8](https://user-images.githubusercontent.com/770464/224339485-d4a1e09c-5d87-4814-bed0-389d7c5eddbb.png)

### Reproducing the issue

Reproduction steps are the same as #5072:
1. Setup Firestore emulator as described in firestore emulator [docs](https://firebase.google.com/docs/emulator-suite/connect_firestore?hl=en#swift), configure the rules so auth is required
```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /users/{userId} {
      allow get: if request.auth != null;
    }
  }
}
```
3. Setup a simple iOS app to connect to the local emulator suite
```swift
let settings = Firestore.firestore().settings
        settings.host = "localhost:8080"
        settings.isPersistenceEnabled = false
        settings.isSSLEnabled = false
        Firestore.firestore().settings = settings
```
4. Auth and create `Firestore` entity in iOS app to observe a collection:
```swift
    @IBAction func buttonDidTap(_ sender: Any) {
        Auth.auth().signInAnonymously { (result, error) in
            assert(error == nil)
            
            guard let result = result else {
                assert(false)
                return;
            }
            
            let uid = result.user.uid
            print(uid)
            Firestore.firestore().collection("users").document(uid).getDocument { (snap, error) in
//                "snap: nil"
                print("snap: \(snap?.data())")
//                error: Optional(Error Domain=FIRFirestoreErrorDomain Code=7 "
//                false for 'get' @ L5" UserInfo={NSLocalizedDescription=
//                false for 'get' @ L5})
                print("error: \(error)")
            }
        }
    }
```

This should succeed without any errors because the user is authed and firestore security rule only checks request.auth != null and this condition is satisfied.

### Firebase SDK Version

8.10.0

### Xcode Version

14.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by MarkDuckworth** [comment]
I was not able to reproduce the issue on the latest SDK 10.6.0. If you are on v8.10.0, consider upgrading your SDK when possible.
