### ISSUE TITLE
"'FIRAnalytics.o' does not contain bitcode" when archiving tvOS app

### ISSUE THREAD

**Issue by vinivendra** [firebase/firebase-ios-sdk#10934]
### Description

_Note:_ this might be similar to #10210, but the solution there was to disable bitcode, which can't be done in this case (as explained below).

We're trying to use Firebase in a tvOS app but we're having a hard time archiving the app. In order for the archive and upload to succeed, we need to enable bitcode for both our app and the frameworks it uses (otherwise the upload fails). From Xcode's help section on the "Include bitcode" distribution option (emphasis mine):

> Include bitcode for iOS content: Includes bitcode which allows the App Store to compile your app optimized for the target devices and operating system versions, and may recompile it later to take advantage of specific hardware, software, or compiler changes. This option appears for iOS targets only. **tvOS and watchOS apps automatically include bitcode**.

However, when we try to archive the app with the FirebaseAnalytics' `Enabled Bitcode` build setting set to `YES`, we get the following error:

> ld: '/Users/vini/Library/Developer/Xcode/DerivedData/FirebaseExample-gcezrdsnuvitoccsuljmbxdlxqyi/Build/Intermediates.noindex/ArchiveIntermediates/FirebaseExample/BuildProductsPath/Release-appletvos/XCFrameworkIntermediates/FirebaseAnalytics/AdIdSupport/FirebaseAnalytics.framework/FirebaseAnalytics(FIRAnalytics.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/vini/Library/Developer/Xcode/DerivedData/FirebaseExample-gcezrdsnuvitoccsuljmbxdlxqyi/Build/Intermediates.noindex/ArchiveIntermediates/FirebaseExample/BuildProductsPath/Release-appletvos/XCFrameworkIntermediates/FirebaseAnalytics/AdIdSupport/FirebaseAnalytics.framework/FirebaseAnalytics' for architecture arm64

We managed to correctly archive and upload the app after removing all Firebase frameworks from the project, but when we include `FirebaseAnalytics` back in our Podfile the archiving error happens again.

### Reproducing the issue

I'm using Xcode 14.2 on macOS 13.2.1.

1. Create a new Xcode project called `FirebaseExample` as a tvOS app. I used my enterprise team and organization identifier, Inferface = Storyboard, Language = Swift, no Core Data or Tests.
2. On the new FirebaseExample project folder, create a Podfile and add the following:
``` ruby
target 'FirebaseExample' do
  use_frameworks!
  pod 'FirebaseAnalytics'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'YES'
    end
  end
end
```
3. Open terminal, navigate to the project folder, and run `pod install`.
4. Open `FirebaseExample2.xcworkspace`.
5. On Xcode, click on the `FirebaseExample` project, then on the `FirebaseExample` target, then on Build Settings > all. Search for "bitcode" and set the `Enable Bitcode` setting to `Yes`.
6. Set the `FirebaseExample` scheme to `Any tvOS Device (arm64)`.
7. Click the `Product` menu, then `Archive`.

The archiving process should fail.

### Firebase SDK Version

10.6.0

### Xcode Version

14.2

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics

### Targeted Platforms

tvOS

### Relevant Log Output

```shell
 ld: '/Users/vini/Library/Developer/Xcode/DerivedData/FirebaseExample-gcezrdsnuvitoccsuljmbxdlxqyi/Build/Intermediates.noindex/ArchiveIntermediates/FirebaseExample/BuildProductsPath/Release-appletvos/XCFrameworkIntermediates/FirebaseAnalytics/AdIdSupport/FirebaseAnalytics.framework/FirebaseAnalytics(FIRAnalytics.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/vini/Library/Developer/Xcode/DerivedData/FirebaseExample-gcezrdsnuvitoccsuljmbxdlxqyi/Build/Intermediates.noindex/ArchiveIntermediates/FirebaseExample/BuildProductsPath/Release-appletvos/XCFrameworkIntermediates/FirebaseAnalytics/AdIdSupport/FirebaseAnalytics.framework/FirebaseAnalytics' for architecture arm64
```

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml
PODS:
  - FirebaseAnalytics (10.6.0):
    - FirebaseAnalytics/AdIdSupport (= 10.6.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - GoogleUtilities/Network (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (10.6.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleAppMeasurement (= 10.6.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - GoogleUtilities/Network (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseCore (10.6.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Logger (~> 7.8)
  - FirebaseCoreInternal (10.6.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseInstallations (10.6.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)
  - GoogleAppMeasurement (10.6.0):
    - GoogleAppMeasurement/AdIdSupport (= 10.6.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - GoogleUtilities/Network (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/AdIdSupport (10.6.0):
    - GoogleAppMeasurement/WithoutAdIdSupport (= 10.6.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - GoogleUtilities/Network (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/WithoutAdIdSupport (10.6.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - GoogleUtilities/Network (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleUtilities/AppDelegateSwizzler (7.11.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (7.11.0):
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/Logger (7.11.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (7.11.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (7.11.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.11.0)"
  - GoogleUtilities/Reachability (7.11.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (7.11.0):
    - GoogleUtilities/Logger
  - nanopb (2.30909.0):
    - nanopb/decode (= 2.30909.0)
    - nanopb/encode (= 2.30909.0)
  - nanopb/decode (2.30909.0)
  - nanopb/encode (2.30909.0)
  - PromisesObjC (2.2.0)

DEPENDENCIES:
  - FirebaseAnalytics

SPEC REPOS:
  trunk:
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreInternal
    - FirebaseInstallations
    - GoogleAppMeasurement
    - GoogleUtilities
    - nanopb
    - PromisesObjC

SPEC CHECKSUMS:
  FirebaseAnalytics: 9f382605c5ee412b039212f054bf7a403d9850c1
  FirebaseCore: fa80ad16a62d52f67274b5b88304c3a318bbf9a4
  FirebaseCoreInternal: c7cd505e2136811096b225ac388d6254a2622362
  FirebaseInstallations: 13dde135fa0524e15bddb133ccc8465c53a1b3f3
  GoogleAppMeasurement: 686b48c3c895f3c55c70719041913d5d150b74f6
  GoogleUtilities: c2bdc4cf2ce786c4d2e6b3bcfd599a25ca78f06f
  nanopb: b552cce312b6c8484180ef47159bc0f65a1f0431
  PromisesObjC: 09985d6d70fbe7878040aa746d78236e6946d2ef

PODFILE CHECKSUM: 4703a1b75db48377e78573c98dce100e8285efa4

COCOAPODS: 1.12.0
```

</details>

**Comment by paulb777** [comment]
According to the [Xcode 14 release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes):

_Starting with Xcode 14, bitcode is no longer required for watchOS and tvOS applications, and the App Store no longer accepts bitcode submissions from Xcode 14._

As a result, Firebase removed bitcode generation in the [Firebase 10.1.0 release](https://github.com/firebase/firebase-ios-sdk/pull/10373/files).

You could use Firebase 10.0.0 or earlier, but that seems contradictory to the Xcode release notes.

**Comment by vinivendra** [comment]
Hi, sorry for the delay. Yes, it seems like these two texts (both from Xcode) are conflicting, so I’m assuming one of them must be wrong, though I’m not sure which. Our practical experience has also been conflicting: the upload fails when we try to disable bitcode everywhere, but if we enable it everywhere Xcode raises warnings about bitcode being deprecated. I’ll try to get help from the Apple developer forums next week to see if anyone can figure out what’s going on.

In the meantime, the suggestion of downgrading Firebase did work, and we were able to upload the app successfully, so thanks for the help.

**Comment by paulb777** [comment]
Thanks for the follow-up. I'll close this for now, but feel free to continue the discussion here or open a new issue.
