### ISSUE TITLE
GAD_GADPrecacheResourceMonitor_arm64_10_1_0 crash

### ISSUE THREAD

**Issue by linziyiwj** [firebase/firebase-ios-sdk#10933]
### Description

Google-Mobile-Ads-SDK happens crash 
Google-Mobile-Ads-SDK for 10.1.0
GoogleAds-IMA-iOS-SDK for 3.18.4
The crash stack is as follows, 

![image](https://user-images.githubusercontent.com/39822433/224253500-515cfd25-166b-4648-b8aa-1bf3665e941d.png)

[issue_7a454b851b0ff694ba87b5b30701a32b_crash_session_f5967c4fd8a5459aa002eb97e43db723_DNE_0_v2_stacktrace.txt](https://github.com/firebase/firebase-ios-sdk/files/10939724/issue_7a454b851b0ff694ba87b5b30701a32b_crash_session_f5967c4fd8a5459aa002eb97e43db723_DNE_0_v2_stacktrace.txt)

### Firebase SDK Version

10.4.0

### Xcode Version

14.2

### Installation Method

CocoaPods

### Firebase Product(s)

AB Testing, Analytics, Crashlytics, In-App Messaging, Messaging, Performance, Remote Config, Storage

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
Sorry about the trouble. Please report this via your Google Mobile Ads support channel.
