### ISSUE TITLE
Analytics Message: "Cannot get flag for unregistered flag. SDK name, flag name: app_measurement, session_stitching_token_feature_enabled"

### ISSUE THREAD

**Issue by SKuhlemann** [firebase/firebase-ios-sdk#10940]
### Description

When I create a new Xcode Project with an SwiftUI lifecycle and follow the integration tutorial for Firebase Analytics then I always see the following Debugger message multiple times.
For example when the app goes into inactive or background scenephase:
_MyApp[4010:1178178] 10.6.0 - [FirebaseAnalytics][I-ACS800014] Cannot get flag for unregistered flag. SDK name, flag name: app_measurement, session_stitching_token_feature_enabled_

This happens on simulator and real devices.

I added "-ObjC" as "Other Linking flags" for the target in XCode.
I also have Background modes enabled for the target:
- Background fetch
- Remote notifications
- Background processing

Below I attached the logging in debugging mode, but the above message also appear in "normal" logging mode.
I dont't see any problems with FirebaseAnalytics and everything seems to be logged fine when taking a look into the Firebase console on the website.
Nevertheless this message makes me suspicious that something is wrong.

Kind regards
Stefan

### Reproducing the issue

- Create a new XCode project
- Follow the instruction tutorial form Firebase Analytics for an iOS SwiftUI App
- Run the app and put it into scenephase inactive or background

### Firebase SDK Version

10.6.0

### Xcode Version

14.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
2023-03-11 21:37:37.822985+0100 MyApp[10869:7635154] 10.6.0 - [FirebaseAnalytics][I-ACS023087] User property set. Name, value: lifetime_user_engagement (_lte), 92873658
2023-03-11 21:37:37.823493+0100 MyApp[10869:7635154] 10.6.0 - [FirebaseAnalytics][I-ACS023087] User property set. Name, value: session_user_engagement (_se), 5620
2023-03-11 21:37:37.823989+0100 MyApp[10869:7635154] 10.6.0 - [FirebaseAnalytics][I-ACS800014] Cannot get flag for unregistered flag. SDK name, flag name: app_measurement, session_stitching_token_feature_enabled
2023-03-11 21:37:37.824550+0100 MyApp[10869:7635154] 10.6.0 - [FirebaseAnalytics][I-ACS012018] Saving bundle. size (bytes): 546
2023-03-11 21:37:37.825096+0100 MyApp[10869:7635154] 10.6.0 - [FirebaseAnalytics][I-ACS023116] Bundle added to the upload queue. BundleID, timestamp (ms): 364, 1678567057698
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

{
  "pins" : [
    {
      "identity" : "abseil-cpp-swiftpm",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/abseil-cpp-SwiftPM.git",
      "state" : {
        "revision" : "583de9bd60f66b40e78d08599cc92036c2e7e4e1",
        "version" : "0.20220203.2"
      }
    },
    {
      "identity" : "boringssl-swiftpm",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/boringssl-SwiftPM.git",
      "state" : {
        "revision" : "dd3eda2b05a3f459fc3073695ad1b28659066eab",
        "version" : "0.9.1"
      }
    },
    {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk.git",
      "state" : {
        "revision" : "60f9a33e7084482df67b48e16f315f4f7a6f5da9",
        "version" : "10.6.0"
      }
    },
    {
      "identity" : "googleappmeasurement",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleAppMeasurement.git",
      "state" : {
        "revision" : "04351180d4c757c6c16127cb57b685fff9ef260b",
        "version" : "10.6.0"
      }
    },
    {
      "identity" : "googledatatransport",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleDataTransport.git",
      "state" : {
        "revision" : "f6b558e3f801f2cac336b04f615ce111fa9ddaa0",
        "version" : "9.2.1"
      }
    },
    {
      "identity" : "googleutilities",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleUtilities.git",
      "state" : {
        "revision" : "0543562f85620b5b7c510c6bcbef75b562a5127b",
        "version" : "7.11.0"
      }
    },
    {
      "identity" : "grpc-ios",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/grpc/grpc-ios.git",
      "state" : {
        "revision" : "8440b914756e0d26d4f4d054a1c1581daedfc5b6",
        "version" : "1.44.3-grpc"
      }
    },
    {
      "identity" : "gtm-session-fetcher",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/gtm-session-fetcher.git",
      "state" : {
        "revision" : "96d7cc73a71ce950723aa3c50ce4fb275ae180b8",
        "version" : "3.1.0"
      }
    },
    {
      "identity" : "leveldb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/leveldb.git",
      "state" : {
        "revision" : "0706abcc6b0bd9cedfbb015ba840e4a780b5159b",
        "version" : "1.22.2"
      }
    },
    {
      "identity" : "nanopb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/nanopb.git",
      "state" : {
        "revision" : "819d0a2173aff699fb8c364b6fb906f7cdb1a692",
        "version" : "2.30909.0"
      }
    },
    {
      "identity" : "promises",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/promises.git",
      "state" : {
        "revision" : "ec957ccddbcc710ccc64c9dcbd4c7006fcf8b73a",
        "version" : "2.2.0"
      }
    },
    {
      "identity" : "swift-protobuf",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-protobuf.git",
      "state" : {
        "revision" : "0af9125c4eae12a4973fb66574c53a54962a9e1e",
        "version" : "1.21.0"
      }
    }
  ],
  "version" : 2
}

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by SKuhlemann** [comment]
Additionally I saw in the logs, that there is always another message relating to "app_measurement" at app start:
_MyApp[5322:1643932] 10.6.0 - [FirebaseAnalytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement_

Attached you find debug logs of a minimal reproducible example:
[firebase-log.txt](https://github.com/firebase/firebase-ios-sdk/files/10950591/firebase-log.txt)

**Comment by rizafran** [comment]
Thanks for reporting this, @SKuhlemann. I was able to reproduce the issue using the Analytics Quickstart. Let me consult this to the Analytics team, and I'll let you know once I got an update.

**Comment by tsunghung** [comment]
Thanks for the issue report.

- We will lower the log level of _"[FirebaseAnalytics][I-ACS800014] Cannot get flag for unregistered flag..."_ to make it less spammy.
- _"[FirebaseAnalytics][I-ACS800023] No pending snapshot to activate..."_ should only appear a few times after app install.

You can safely ignore these messages. They are expected and not harmful.

**Comment by SKuhlemann** [comment]
Thank you for the information.
