### ISSUE TITLE
After upgrading to 10.6 Firebase Authentication I still don't see a player name under identifier

### ISSUE THREAD

**Issue by hrkm** [firebase/firebase-ios-sdk#10967]
### Description

![image](https://user-images.githubusercontent.com/230985/226084852-4a23652a-a067-452c-8314-cd2e4d25d23b.png)

The identifier still is not populated when using the latest Firebase Auth library after Apple changed the Game Center implementation.

### Firebase SDK Version

10.6

### Xcode Version

13.2.1

### Installation Method

CocoaPods

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by hrkm** [comment]
I've used the [GameCenterAuthProvider](https://firebase.google.com/docs/reference/unity/class/firebase/auth/game-center-auth-provider) to obtain the credential for auth and it is successful for connecting with e.g. Firestore. Not sure if this method supports populating the identifier though?

**Comment by renkelvin** [comment]
Hi @hrkm, only email addresses and phone numbers are considered as identifiers. It's an expected behaviour identifier is empty on the console for Game Center.

**Comment by hrkm** [comment]
For Google Play Games it shows the display name of the profile in that service - there is a similar concept in Apple Game Center, so I thought it should be showing that? What am I missing?
