### ISSUE TITLE
Binary Makes Use of Insecure API(s)

### ISSUE THREAD

**Issue by Laluhelmi** [firebase/firebase-ios-sdk#10968]
### Description

We are using Firebase Crashlytics and Firebase Analytics in our application.
Penetration testing team have found that some insecure source code functions are being used in which is found in the firebase library in the below functions:
_strlen , _sscanf , _fopen , _strncpy , _stat , _strncat , _vsnprintf , _vsprintf, _memcpy , _sprintf , _printf , _strcpy

could you confirm if all those functions are safe and not considered a security issue?

### Firebase SDK Version

9.4.1

### Xcode Version

14.2

### Installation Method

CocoaPods

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
Duplicate of #8454.
