### ISSUE TITLE
[macOS] Upgrading from 10.4.0 to 10.5.0 results in users getting logged out

### ISSUE THREAD

**Issue by diederich** [firebase/firebase-ios-sdk#10979]
### Description

Updating the SDK in our app from 10.4.0. to 10.5.0 resulted in all users being logged out.

The [PR](https://github.com/firebase/firebase-ios-sdk/pull/10759) changing `kSecUseDataProtectionKeychain` to `true` makes Firebase Auth not find the previous entry in the keychain, thus logging out users.

### Expected
Existing keychain entry should be upgraded to use the new attributes by querying for the old attributed entry and storing its data back using the new attribute.

### Actual
Existing keychain entry is removed, user needs to login again & keychain entry is replaced.

--- 
We saw [existing migration code](https://github.com/firebase/firebase-ios-sdk/blob/60f9a33e7084482df67b48e16f315f4f7a6f5da9/FirebaseAuth/Sources/Storage/FIRAuthKeychainServices.m#L71-L71) in `FIRAuthKeychainServices.m` and wondered if this could also be applied to this change.

Internal testing showed that we can read the old keychain entry, delete it, then write the new entry with the updated attributes and thus keep the existing login.
For now, we're downgrading back to 10.4.0 and hoping for the migration to be implemented in the SDK.

Thanks for looking into this!

cc @ncooke3 since https://github.com/firebase/firebase-ios-sdk/issues/10582#issuecomment-1364628508 looks relevant

### Reproducing the issue

* launch an app with the 10.4.0 included & log in
* update the SDK to 10.5.0 
* relaunch the app & observe being logged out

(note this is the same in 10.6.0, and from looking at the changes in 10.7.0 it should be still happening)

### Firebase SDK Version

10.5.0

### Xcode Version

14.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication, Firestore, Functions, Storage

### Targeted Platforms

iOS, macOS

### Relevant Log Output

```shell
n/a
```

### If using Swift Package Manager, the project's Package.resolved

```
[...]
    {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk.git",
      "state" : {
        "revision" : "60f9a33e7084482df67b48e16f315f4f7a6f5da9",
        "version" : "10.6.0"
      }
    },
[...]
```

### If using CocoaPods, the project's Podfile.lock

n/a

**Comment by ncooke3** [comment]
Hi @diederich, thanks for opening and sorry for the issue here! I have a couple follow-up questions. 

1. Are you seeing this behavior for iOS users? Based Apple's [docs](https://developer.apple.com/documentation/security/ksecusedataprotectionkeychain#:~:text=the%20data%20protection%20key%20affects%20operations%20only%20in%20macos.%20other%20platforms%20automatically%20behave%20as%20if%20the%20key%20is%20set%20to%20true), this change should not affect iOS.
2. This code change was implemented to prevent Keychain.app permission pop-ups that users had to deal with. Was this an issue that your app was facing pre-10.5.0?

**Comment by diederich** [comment]
> Hi @diederich, thanks for opening and sorry for the issue here! [snip]

Thanks for looking into this @ncooke3! 🙏 

> 1. Are you seeing this behavior for iOS users? 

macOS only!

> 2. This code change was implemented to prevent Keychain.app permission pop-ups that users had to deal with. Was this an issue that your app was facing pre-10.5.0?

While we've seen the keychain popup before, it's never been in the context of "normal updates".
e.g. it would show up with adhoc-signed version of our app - but that's OK :-). using proper signing setup, and we're deploying with keychain access entitlement & a DeveloperID signed app, we haven't seen this in "production".

I think the change to use the new attribute is correct and great - just needs an upgrade path?

**Comment by ncooke3** [comment]
@diederich, sure thing and thanks for the response. Hmm, I'm just not sure what this upgrade path should be... because, if we check the keychain without the new flag first (to migrate), then we'd be triggering the pop-ups for clients that have been seeing them.

With regard to not seeing the pop-ups in production... I'm admittedly now confused regarding why pop-ups appear for some developers but not others.

**Comment by diederich** [comment]
Thanks @ncooke3!

To us it seems to be preferable to maybe show the popup one more time instead of forcing every user to sign in. WDYT?
Note that by checking the new keychain entry _first_, we ensure users don't see the popup unless migration is necessary.

**Comment by diederich** [comment]
🤔 At least the dialogs we've been seeing so far, all came from accessing a keychain entry that's already been there. My hunch is the popup would _not_ show in case there's no entry.

**Comment by ncooke3** [comment]
Good point, that's something that can hopefully be confirmed by manual testing. I'll look into this and see what I find. Thanks for the info so far and feel free to continue sharing anything that may be relevant!

**Comment by fischman-bcny** [comment]
@ncooke3 friendly ping / any updates? (we're currently pinning our app to earlier-than-10.5.0 and IWBN to be on the latest-and-greatest again ;) )

**Comment by ncooke3** [comment]
Hi @fischman-bcny and @diederich,

After investigating, I was not able to find a codepath to migrate keychain data from the old query to the new query while consistently avoiding the keychain pop-ups. After chatting with the team, a one-time pop-up triggered by the keychain query migration is not preferred given that we have had several issues filed about the keychain pop-ups causing a poor UX. Apologies that this is not the direction we would like to go. I would like to stress that the sign-out after update is a one-time cost and has shown promising results in eliminating keychain pop-ups across all of our Mac app developers. Firebase macOS support is still in beta and we appreciate your patience as we improve our cross platform support.
