### ISSUE TITLE
Moving from SPM to XCFramework

### ISSUE THREAD

**Issue by alokc83** [firebase/firebase-ios-sdk#11030]
### Description

I had Firebase SPM in my project. 
Due to build delayed and automation delays. I decided to go to XCFrameWork path. 

I am using Carthage to get those XCFRWK as per documentation here. 
https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md 

Even after adding all the framework to the project. I am getting `import Firebase` not found. 

There is not a single framework that is built Carthage that I have left. 

I was expecting it running out of the box. 

![Screenshot 2023-03-28 at 11 14 48 AM](https://user-images.githubusercontent.com/59144/228303462-5e749a15-ce1b-4e3d-bf41-709ce3cca576.png)

### Reproducing the issue

Create project 
Add Firebase SPM 

Import Firebase 

// compiles fine 

//Now remove SPM and add Firebase with Carthage 

// Now all the framework created by carthage 

// Compile again 

Firebase base not found error. 

### Firebase SDK Version

10.7.0

### Xcode Version

14.2

### Installation Method

Carthage

### Firebase Product(s)

All

### Targeted Platforms

iOS

### Relevant Log Output

```shell
/Users/XXXXXXX/Documents/workspace/XXXXX/modules/XXXX/XXXXX/3rdPartyServices/Firebase/FirebaseRemoteConfig.swift:8:8: error: no such module 'Firebase'
import Firebase
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @alokc83, I tried to reproduce the issue, but I was able to successfully run my sample app. May I know if you've added `FirebaseAnalyticsBinary` in your `Cartfile` since it should always be included? Thanks.

**Comment by ncooke3** [comment]
Adding on to the @rizafran's questions above, with regard to your SPM setup: were some Firebase products particularly slower than the others?

**Comment by alokc83** [comment]
@rizafran  I copied everything that was said in the Carthage file for download. 

> binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseABTestingBinary.json"
> binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAdMobBinary.json"
> binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" < --- 
> binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAppCheckBinary.json"
> binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAppDistributionBinary.json"
> binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAuthBinary.json"
> binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashlyticsBinary.json"
> binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseDatabaseBinary.json"
> binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseDynamicLinksBinary.json"
> binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseFirestoreBinary.json"
> binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseFunctionsBinary.json"
> binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseGoogleSignInBinary.json"
> binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseInAppMessagingBinary.json"
> binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseMLModelDownloaderBinary.json"
> binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseMessagingBinary.json"
> binary "https://dl.google.com/dl/firebase/ios/carthage/FirebasePerformanceBinary.json"
> binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseRemoteConfigBinary.json"
> binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseStorageBinary.json"

I have added all the frameworks, whether I used them or not, just to get started, even after adding them all. 
Yes, I have added Firebase Analytics too.

**Comment by alokc83** [comment]
@ncooke3  No SPM is fine. However, PR automation on Github is taking too long for the app to build to run tests on each PR, so I am looking into many ways to make the build faster. Right now, we are sitting for about 30 mins which is not at all practical.

**Comment by paulb777** [comment]
@alokc83 Does changing `import Firebase` to `import FirebaseCore` make a difference.

BTW, the 10.8.0 release planned for next week should speed up the SPM build.

**Comment by paulb777** [comment]
We'll likely need a repro case to further help investigate this.
