### ISSUE TITLE
"FirebaseAnalyticsTarget.o' does not contain bitcode" when trying to build iOS app for real device with Xcode 14 

### ISSUE THREAD

**Issue by ArnoldGoetzke** [firebase/firebase-ios-sdk#11067]
### Description

Per this issue, I see the recommendation is to disable BitCode.

https://github.com/firebase/firebase-ios-sdk/issues/10210

However, I need bitcode enabled locally to build an obfuscated version of our application.  Otherwise, I cannot publish our app.

How do I resolve the lack of bitcode for this issue?

FirebaseAnalytics/AdIdSupport/FirebaseAnalytics.framework/FirebaseAnalytics(FIRAEvent.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE)

### Firebase SDK Version

ios 16.4

### Xcode Version

14.2

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
We don't have plans to add bitcode support back to the SDKs, since Apple has dropped support.

If you still need it, the best option would be to use version 14.0.0 or earlier.

I'm going to close, but feel free to continue the discussion if you have additional questions.

**Comment by ArnoldGoetzke** [comment]
Alright, I’ll stick with that for now.  Though it would seem better to eliminate it in sync with Apple.   As long as there isn’t a need for me to move beyond 14.0.0, I’ll survive.   It’s tough for Apps to have competing libraries.Thanks for the quick response.ArnoldOn Apr 3, 2023, at 5:39 PM, Paul Beusterien ***@***.***> wrote:﻿
We don't have plans to add bitcode support back to the SDKs, since Apple has dropped support.
If you still need it, the best option would be to use version 14.0.0 or earlier.
I'm going to close, but feel free to continue the discussion if you have additional questions.

**Comment by ArnoldGoetzke** [comment]
Is there a Firebase 14 version?   My issue isn’t xCode, it is a version of your library that supports Bitcode., Thanks,ArnoldOn Apr 3, 2023, at 5:54 PM, Arnold Goetzke ***@***.***> wrote:﻿Alright, I’ll stick with that for now.  Though it would seem better to eliminate it in sync with Apple.   As long as there isn’t a need for me to move beyond 14.0.0, I’ll survive.   It’s tough for Apps to have competing libraries.Thanks for the quick response.ArnoldOn Apr 3, 2023, at 5:39 PM, Paul Beusterien ***@***.***> wrote:﻿
We don't have plans to add bitcode support back to the SDKs, since Apple has dropped support.
If you still need it, the best option would be to use version 14.0.0 or earlier.
I'm going to close, but feel free to continue the discussion if you have additional questions.

**Comment by paulb777** [comment]
Oops, I meant Firebase 10.0.0 or earlier. I edited the typo in my previous comment.

**Comment by ArnoldGoetzke** [comment]
Thanks!Sent from my iPhoneOn Apr 3, 2023, at 6:01 PM, Paul Beusterien ***@***.***> wrote:﻿
Oops, I meant Firebase 10.0.0 or earlier. I edited the typo in my previous comment.
