### ISSUE TITLE
Verifying and resolving package in SPM takes forever.

### ISSUE THREAD

**Issue by xCyborg** [firebase/firebase-ios-sdk#11087]
### Description

![Screenshot 2023-04-06 at 23 39 55](https://user-images.githubusercontent.com/10322873/230506759-c846f44b-5c79-4fa3-ad90-3921db6562a6.png)

### Firebase SDK Version

next major

### Xcode Version

14.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
This may be a local network issue or GitHub connectivity issue. 

Please check if you can access the hanging repository via `git clone`.

**Comment by morganchen12** [comment]
Does this happen for all SPM modules, or just Firebase?

**Comment by Kjuly** [comment]
Hi @morganchen12, only the Firebase. My other packages are fast enough to get the response. I also added the GoogleMobileAds, which waited for a while but is acceptable.

Anyway, I finally completed adding the Firebase yesterday.

I think it might be the 3rd party lib dependency analyzing and fetching that makes it really slow. I've just checked the folder "/SourcePackages/checkouts" and found that the `firebase-ios-sdk` repo is only 70.8 MB, which is not that big. However, it has several significant repo dependencies, e.g., `boringssl-SwiftPM` (144.8 MB), `grpc-ios` (368.9 MB), as well as some other 3rd party libs. Taken together, the total package size could be close to 1 GB.

**Comment by Kjuly** [comment]
Thank you @paulb777 , you're right. I was using the 9.6.0. Setting the dependency rule to "Up to Next Major Version" uses 9.0.0 as the minimum version by default.

I just tried cleaning the package cache and re-adding the Firebase. As a result, it's fast enough now. 🎉

**Comment by Kjuly** [comment]
According to the screenshot @xCyborg provided, the min version is 9.0.0 too. It should be the same case.

**Comment by paulb777** [comment]
Closing, since there aren't any defined actions for the Firebase team here. Feel free to continue the discussion.

**Comment by ncooke3** [comment]
> > Setting the dependency rule to "Up to Next Major Version" uses 9.0.0 as the minimum version by default.
> 
> Unfortunately, Xcode doesn't seem to properly sort the package tags. One would expect 10.0.0 to be the minimum version by default since that's the latest major version, but it's not the case. I filed feedback last month to get that fixed. Hopefully we see it in a future Xcode release.

Closing the loop here– I'm seeing the correct behavior in Xcode 15 Beta 1.
