### ISSUE TITLE
Need latest Firebase SDK consuming GDT version 9.2.2

### ISSUE THREAD

**Issue by PratibhaSanath** [firebase/firebase-ios-sdk#11100]
### Description

We are trying to compile our iOS project with Firebase SDK integrated on Xcode 14.3. We are currently getting errors in Google data transport SDK which is a dependant SDK for Firebase. GDT errors happening on Xcode 14.3 have been resolved in the latest version 9.2.2. Could you please provide latest Firebase SDK which consumes GDT version 9.2.2.
We are unable to build our project without resolving this issue on Xcode 14.3.

GDT fix link - https://github.com/google/GoogleDataTransport/tree/CocoaPods-9.2.2
https://github.com/google/GoogleDataTransport/pull/92

### Reproducing the issue

We are trying to compile our iOS project with Firebase SDK integrated on Xcode 14.3. We are currently getting errors in Google data transport SDK which is a dependant SDK for Firebase. GDT errors happening on Xcode 14.3 have been resolved in the latest version 9.2.2. Could you please provide latest Firebase SDK which consumes GDT version 9.2.2.
We are unable to build our project without resolving this issue on Xcode 14.3.

### Firebase SDK Version

10.5.0

### Xcode Version

14.3

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, Crashlytics

### Targeted Platforms

iOS

**Comment by paulb777** [comment]
I'm going to close, but feel free to continue the conversation here.

**Comment by PratibhaSanath** [comment]
I see below warnings, when building Firebase version 10.8.0 in Xcode 14.3. Can we please address this and provide the latest SDK,


<img width="1252" alt="Screenshot 2023-04-18 at 10 02 43 AM" src="https://user-images.githubusercontent.com/36661759/232672231-b95c4eab-7f31-4751-91a6-91839e737244.png">
