### ISSUE TITLE
Xcode linker error "symbol not found" when using -all_load linker flag

### ISSUE THREAD

**Issue by seejayuu** [firebase/firebase-ios-sdk#1110]
* Xcode version: 9.3
  * Firebase iOS SDK version: 4.13.0

When I build my Firebase app using the -all_load linker flag, I get the following error:

Undefined symbols for architecture x86_64:
  "firebase::invites::internal::InvitesReceiverInternalIos::InvitesReceiverInternalIos(firebase::App const&)", referenced from:
      firebase::invites::internal::InvitesReceiverInternal::CreateInstance(firebase::App const&, firebase::invites::internal::ReceiverInterface*) in FirebaseFirestore(invites_receiver_internal_87c34f8724c5a5d01623a76585b9c492.o)

This app used to build and run correctly under Xcode 9.2 and whatever previous version of the SDK I was using at that time (I think it was 4.10.0).

If I temporarily remove the -all_load flag, the app builds properly. I've tried all the usual things: clearing the pod cache, clearing XCode's DerivedData, etc, but the error persists.

**Comment by paulb777** [comment]
@wilhuff  Might be fixed by the M25 build system switch?

**Comment by wilhuff** [comment]
`firebase::invites::internal::InvitesReceiverInternalIos` isn't a Firestore type. It appears to be a packaging error that comes from an erroneous dependency in google3. Once we switch to source pod distribution this will go away.

**Comment by wilhuff** [comment]
@seejayuu You can work around this today by using the Firestore source pod, as [described in the README](https://github.com/firebase/firebase-ios-sdk/#examples). You can use `4.13.0` as the branch name instead of `master` to get the same version you have now, just from source.

**Comment by bwalton** [comment]
@wilhuff  If I'm getting the same error while using the [.frameworks](https://firebase.google.com/download/ios), do I just need to wait for the next release of updated static frameworks?

**Comment by salqadri** [comment]
@seejayuu, what is the reason you wanted to use -all_load?
