### ISSUE TITLE
SPM Firestore for Catalyst. No such Module.

### ISSUE THREAD

**Issue by jesus-mg-ios** [firebase/firebase-ios-sdk#11119]
### Description

Hi: 

I'm getting this error when I try to compile for catalyst (SPM 10.8.0). For iOS all works as expected.

<img width="222" alt="image" src="https://user-images.githubusercontent.com/85997060/231767812-5f6629e2-fb77-4195-930f-28e0c5da7f7a.png">

These are the dependencies of the target that on build time throw the error:

<img width="540" alt="image" src="https://user-images.githubusercontent.com/85997060/231768259-754352d6-345c-440f-b877-0cb1cbde64a4.png">

In intermediates I can see a difference between the build of Catalyst and the simulator:

<img width="828" alt="image" src="https://user-images.githubusercontent.com/85997060/231785093-40b12060-47dd-422f-b35f-fa4a944ca080.png">

<img width="883" alt="image" src="https://user-images.githubusercontent.com/85997060/231785305-d549461e-101e-464b-ba5f-cd8aa861b21f.png">

`FirebaseFirestoreSwift.build` is included on iOS simulator but not on catalyst. I don't know if it's correct or not, and the cause of it @ncooke3 

Any ideas on how to solve it?

Thanks in advance

### Firebase SDK Version

10.8.0

### Xcode Version

14.3.0

### Installation Method

Swift Package Manager

### Firebase Product(s)

Firestore

### Targeted Platforms

macCatalyst

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment]
> FirebaseFirestoreSwift.build is included on iOS simulator but not on catalyst. I don't know if it's correct or not, and the cause of it @ncooke3

Hmm, weird. I'm in the process of reproducing it now. Looking into this...

**Comment by jesus-mg-ios** [comment]
Thanks @ncooke3 for your fast response and support.

**Comment by jesus-mg-ios** [comment]
It works @ncooke3, thanks for your effort on it. 💯

**Comment by ncooke3** [comment]
Thank you for reporting! 🙂
