### ISSUE TITLE
Update the documentation to reflect the proper usage of Functions emulation in Swift

### ISSUE THREAD

**Issue by MarkUnthank** [firebase/firebase-ios-sdk#11134]
### Description

Referenced here: https://github.com/firebase/firebase-ios-sdk/issues/7537

The documentation gives `Functions.functions().useFunctionsEmulator(origin: "http://localhost:5001")` as the instruction to instrument the app for callable functions in Swift: https://firebase.google.com/docs/functions/local-emulator#instrument-functions, but this code is wrong.

The real code is buried in the git issue above: `functions.useEmulator(withHost: "http://localhost", port: 5001)`

### Firebase SDK Version

9.4.1

### Xcode Version

13.3.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Functions

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by morganchen12** [comment]
Hi @MarkUnthank, the code snippets in the issue you're referencing

```swift
let functions = Functions.functions()
functions.useEmulator(withHost: "localhost", port: 5001)
```

and the code snippet in our documentation
```swift
Functions.functions().useEmulator(withHost: "localhost", port: 5001)
```

do the same thing. Are you seeing a behavioral difference when switching between the two code snippets?

**Comment by MarkUnthank** [comment]
That's interesting. The [documentation site](https://firebase.google.com/docs/functions/local-emulator) still lists: `Functions.functions().useFunctionsEmulator(origin: "http://localhost:5001")`.

Where's the other documentation, where you found the snippet you pasted?

**Comment by morganchen12** [comment]
Ah, apologies. I had the wrong snippet.

**Comment by morganchen12** [comment]
Fixed in https://github.com/firebase/snippets-ios/pull/346. The documentation should auto-update soon.
