### ISSUE TITLE
Update GoogleDataTransport to 6.2.2

### ISSUE THREAD

**Issue by KevinColemanInc** [firebase/firebase-ios-sdk#11140]
### Description

Xcode 14.3 shows an error with firebase projects, see issue:

https://github.com/facebook/react-native/issues/36763
https://stackoverflow.com/questions/75189250/warning-a-function-declaration-without-a-prototype-is-deprecated-in-all-version

The fix has already been applied to the dependency:
https://github.com/google/GoogleDataTransport/pull/92

Can we update the podfiles to require the latest version of GoogleDataTransport?

### Reproducing the issue

Build firebase in the latest version of xcode (14.3)

### Firebase SDK Version

10.8.1

### Xcode Version

14.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

All

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment]
Hi @KevinColemanInc, could you try running `pod update`?

**Comment by KevinColemanInc** [comment]
My specific project is so old that I can't actually update anything without making the app unbuildable. 

I think `pod update` should fix the issue, but don't you want to force the version to be above 9.2.2 to prevent another package from minimizing the version?
