### ISSUE TITLE
Crashlytics uploaded dSYM successfully, But firebase console of Crashlytics still show dSYM required

### ISSUE THREAD

**Issue by jazdance** [firebase/firebase-ios-sdk#11152]
### Description

Environment: 

- xcode version: 14.2
- Mac OS: Ventura 13.2
- Installation method: cocoapods
- Firebase SDK version: 8.15.0

For the local build, the app's dSYM file locates at this folder:
/Users/myUserName/Library/Developer/Xcode/DerivedData/appName-xxxxxx/Build/Products/Debug-iphoneos/appName.app.dSYM

Then I compressed the dSYM file then uploaded the zip file to Firebase Crashlytics, during uploading, no errors,
upon successful uploading, Firebase screen says the file will be processed in 10 mins,  
so I went to back to check after 10 mins, nothing happened, the warning "dSYM file required" remains.
I tried the uploading a few times & **all dSYM files were uploaded successfully**, but 1 hour later, went back to check , always the same result, **the warning "dSYM file required" remains.**

The app in question is a dev build , not production release.

Could you please check 

- **why Firebase Crashlytics does Not give any update/warning about the dSYM files I uploaded ?**
- If the dSYM file is invalid, under the Crashlytics dSYM tab, **at least give us an update alongside the dSYM file uploaded about why the file was Not processed** , this update will be extremely useful. 

Look forward to your reply,
Thank you very much..

### Reproducing the issue

according to the instructions of this link:
https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?hl=en&authuser=0&platform=ios

I generated the App locally via Xcode and Xcode installs our app at a real iphone device, also can launch successfully,

I located dSYM file at this folder:
/Users/myUserName/Library/Developer/Xcode/DerivedData/appName-xxxxxx/Build/Products/Debug-iphoneos/appName.app.dSYM

Then compressed the dSYM file then uploaded the zip file to Firebase Crashlytics, during uploading, no errors,
upon successful uploading, Firebase screen says the file will be processed in 10 mins,  
so I went to back to check after 10 mins, nothing happened, the warning "dSYM file required" remains.

### Firebase SDK Version

8.15.0

### Xcode Version

14.2

### Installation Method

CocoaPods

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @jazdance, sorry to hear that you're having issues with your dSYMs. Please file a ticket via our [support channel](https://firebase.google.com/support) so the Crashlytics team will be able to get your app and project details and investigate it in our backend. With this, I'll now close the ticket.
