### ISSUE TITLE
HTTPMetric  

### ISSUE THREAD

**Issue by DuQuanzhong** [firebase/firebase-ios-sdk#11168]
### Description

'Firebase/Performance' ：  HTTP/HTTPS network request performance data failed to be monitored and reported;

<img width="986" alt="截屏2023-04-24 11 07 28" src="https://user-images.githubusercontent.com/5549754/233892120-bc09a5c6-2dea-4982-ae1b-bc0886e4ea83.png">

### Firebase SDK Version

8.15.0

### Xcode Version

14.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Performance

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

PODS:
  - Alamofire (5.5.0)
  - AppAuth (1.6.1):
    - AppAuth/Core (= 1.6.1)
    - AppAuth/ExternalUserAgent (= 1.6.1)
  - AppAuth/Core (1.6.1)
  - AppAuth/ExternalUserAgent (1.6.1):
    - AppAuth/Core
  - BadgeHub (1.0.0)
  - BMPlayer (1.3.2):
    - BMPlayer/Full (= 1.3.2)
  - BMPlayer/Core (1.3.2)
  - BMPlayer/Full (1.3.2):
    - BMPlayer/Core
    - NVActivityIndicatorView (~> 4.7.0)
    - SnapKit (~> 5.0.0)
  - BRPickerView (2.7.8):
    - BRPickerView/AddressPickerView (= 2.7.8)
    - BRPickerView/Base (= 2.7.8)
    - BRPickerView/DatePickerView (= 2.7.8)
    - BRPickerView/StringPickerView (= 2.7.8)
  - BRPickerView/AddressPickerView (2.7.8):
    - BRPickerView/Base
  - BRPickerView/Base (2.7.8)
  - BRPickerView/DatePickerView (2.7.8):
    - BRPickerView/Base
  - BRPickerView/StringPickerView (2.7.8):
    - BRPickerView/Base
  - CocoaAsyncSocket (7.6.5)
  - DGBase (0.3.3):
    - dsBridge (= 3.0.6)
    - Easy (~> 2.9.0)
    - MBProgressHUD (= 1.2.0)
    - MJRefresh (= 3.7.5)
    - SDWebImage (= 5.11.0)
  - DGBeta (0.2.0):
    - Easy/Session (~> 2.9.0)
    - FLEX (~> 4.6.1)
    - GDPerformanceView-Swift (~> 2.1.1)
    - OOMDetector (~> 1.3)
  - DGNetworkUtils (0.3.0):
    - Easy/Session (~> 2.9.0)
    - HandyJSON (~> 5.0.2)
  - DGSocial/Apple (0.1.0):
    - DGSocial/Core
  - DGSocial/Core (0.1.0):
    - Easy (~> 2.9.0)
  - DGSocial/FacebookLogin (0.1.0):
    - DGSocial/Core
    - FBSDKLoginKit (~> 12.3.2)
  - DGSocial/GoogleSignIn (0.1.0):
    - DGSocial/Core
    - GoogleSignIn (~> 6.1.0)
  - dsBridge (3.0.6)
  - Easy (2.9.1):
    - Easy/Core (= 2.9.1)
    - Easy/Session (= 2.9.1)
  - Easy/Core (2.9.1):
    - SnapKit (~> 5.0.1)
  - Easy/Session (2.9.1):
    - Alamofire (~> 5.5.0)
    - Easy/Core
  - EFCountingLabel (5.1.4)
  - ESTabBarController-swift (2.8.0)
  - FBAEMKit (12.3.2):
    - FBSDKCoreKit_Basics (= 12.3.2)
  - FBSDKCoreKit (12.3.2):
    - FBAEMKit (= 12.3.2)
    - FBSDKCoreKit_Basics (= 12.3.2)
  - FBSDKCoreKit_Basics (12.3.2)
  - FBSDKLoginKit (12.3.2):
    - FBSDKCoreKit (= 12.3.2)
  - FBSDKShareKit (12.3.2):
    - FBSDKCoreKit (= 12.3.2)
  - Firebase/Analytics (8.15.0):
    - Firebase/Core
  - Firebase/Core (8.15.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 8.15.0)
  - Firebase/CoreOnly (8.15.0):
    - FirebaseCore (= 8.15.0)
  - Firebase/Crashlytics (8.15.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 8.15.0)
  - Firebase/Performance (8.15.0):
    - Firebase/CoreOnly
    - FirebasePerformance (~> 8.15.0)
  - FirebaseABTesting (8.15.0):
    - FirebaseCore (~> 8.0)
  - FirebaseAnalytics (8.15.0):
    - FirebaseAnalytics/AdIdSupport (= 8.15.0)
    - FirebaseCore (~> 8.0)
    - FirebaseInstallations (~> 8.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/MethodSwizzler (~> 7.7)
    - GoogleUtilities/Network (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
    - nanopb (~> 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (8.15.0):
    - FirebaseCore (~> 8.0)
    - FirebaseInstallations (~> 8.0)
    - GoogleAppMeasurement (= 8.15.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/MethodSwizzler (~> 7.7)
    - GoogleUtilities/Network (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
    - nanopb (~> 2.30908.0)
  - FirebaseCore (8.15.0):
    - FirebaseCoreDiagnostics (~> 8.0)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/Logger (~> 7.7)
  - FirebaseCoreDiagnostics (8.15.0):
    - GoogleDataTransport (~> 9.1)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/Logger (~> 7.7)
    - nanopb (~> 2.30908.0)
  - FirebaseCrashlytics (8.15.0):
    - FirebaseCore (~> 8.0)
    - FirebaseInstallations (~> 8.0)
    - GoogleDataTransport (~> 9.1)
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (~> 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - FirebaseInstallations (8.15.0):
    - FirebaseCore (~> 8.0)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/UserDefaults (~> 7.7)
    - PromisesObjC (< 3.0, >= 1.2)
  - FirebasePerformance (8.15.0):
    - FirebaseCore (~> 8.0)
    - FirebaseInstallations (~> 8.0)
    - FirebaseRemoteConfig (~> 8.0)
    - GoogleDataTransport (~> 9.1)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/ISASwizzler (~> 7.7)
    - GoogleUtilities/MethodSwizzler (~> 7.7)
    - nanopb (~> 2.30908.0)
  - FirebaseRemoteConfig (8.15.0):
    - FirebaseABTesting (~> 8.0)
    - FirebaseCore (~> 8.0)
    - FirebaseInstallations (~> 8.0)
    - GoogleUtilities/Environment (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
  - fishhook (0.2)
  - FLEX (4.6.1)
  - FSPagerView (0.8.3)
  - GDPerformanceView-Swift (2.1.1)
  - Google-Mobile-Ads-SDK (8.12.0):
    - GoogleAppMeasurement (< 9.0, >= 7.0)
    - GoogleUserMessagingPlatform (>= 1.1)
  - GoogleAppMeasurement (8.15.0):
    - GoogleAppMeasurement/AdIdSupport (= 8.15.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/MethodSwizzler (~> 7.7)
    - GoogleUtilities/Network (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
    - nanopb (~> 2.30908.0)
  - GoogleAppMeasurement/AdIdSupport (8.15.0):
    - GoogleAppMeasurement/WithoutAdIdSupport (= 8.15.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/MethodSwizzler (~> 7.7)
    - GoogleUtilities/Network (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
    - nanopb (~> 2.30908.0)
  - GoogleAppMeasurement/WithoutAdIdSupport (8.15.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/MethodSwizzler (~> 7.7)
    - GoogleUtilities/Network (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
    - nanopb (~> 2.30908.0)
  - GoogleDataTransport (9.2.2):
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleSignIn (6.1.0):
    - AppAuth (~> 1.4)
    - GTMAppAuth (~> 1.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - GoogleUserMessagingPlatform (2.0.1)
  - GoogleUtilities/AppDelegateSwizzler (7.11.1):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (7.11.1):
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/ISASwizzler (7.11.1)
  - GoogleUtilities/Logger (7.11.1):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (7.11.1):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (7.11.1):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.11.1)"
  - GoogleUtilities/Reachability (7.11.1):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (7.11.1):
    - GoogleUtilities/Logger
  - GTMAppAuth (1.3.1):
    - AppAuth/Core (~> 1.6)
    - GTMSessionFetcher/Core (< 3.0, >= 1.5)
  - GTMSessionFetcher/Core (1.7.2)
  - HandyJSON (5.0.2)
  - IQKeyboardManagerSwift (6.5.11)
  - JTAppleCalendar (8.0.4)
  - JXPagingView/Paging (2.1.2)
  - JXPhotoBrowser (3.1.3)
  - JXSegmentedView (1.3.0)
  - KFGradientProgressView (1.5.0)
  - KTVCocoaHTTPServer (1.0.0):
    - CocoaAsyncSocket
  - KTVHTTPCache (2.0.1):
    - KTVCocoaHTTPServer
  - lottie-ios (3.2.3)
  - MBProgressHUD (1.2.0)
  - MJRefresh (3.7.5)
  - MKRingProgressView (2.3.0)
  - nanopb (2.30908.0):
    - nanopb/decode (= 2.30908.0)
    - nanopb/encode (= 2.30908.0)
  - nanopb/decode (2.30908.0)
  - nanopb/encode (2.30908.0)
  - NVActivityIndicatorView (4.7.0):
    - NVActivityIndicatorView/Presenter (= 4.7.0)
  - NVActivityIndicatorView/Presenter (4.7.0)
  - OOMDetector (1.3):
    - fishhook (= 0.2)
  - Popover (1.3.0)
  - PromisesObjC (2.2.0)
  - R.swift (6.1.0):
    - R.swift.Library (~> 5.3.0)
  - R.swift.Library (5.3.0)
  - SDWebImage (5.11.0):
    - SDWebImage/Core (= 5.11.0)
  - SDWebImage/Core (5.11.0)
  - SnapKit (5.0.1)
  - SwiftDate (6.3.1)
  - SwiftyStoreKit (0.16.1)
  - YYText (1.0.7)

DEPENDENCIES:
  - BadgeHub (= 1.0.0)
  - BMPlayer (= 1.3.2)
  - BRPickerView (= 2.7.8)
  - DGBase (= 0.3.3)
  - DGBeta (= 0.2.0)
  - DGNetworkUtils (= 0.3.0)
  - DGSocial/Apple (= 0.1.0)
  - DGSocial/FacebookLogin (= 0.1.0)
  - DGSocial/GoogleSignIn (= 0.1.0)
  - EFCountingLabel (= 5.1.4)
  - ESTabBarController-swift (= 2.8.0)
  - FBSDKShareKit (= 12.3.2)
  - Firebase/Analytics (= 8.15.0)
  - Firebase/Crashlytics (= 8.15.0)
  - Firebase/Performance (= 8.15.0)
  - FSPagerView (= 0.8.3)
  - Google-Mobile-Ads-SDK (= 8.12.0)
  - IQKeyboardManagerSwift (= 6.5.11)
  - JTAppleCalendar (= 8.0.4)
  - JXPagingView/Paging
  - JXPhotoBrowser (= 3.1.3)
  - JXSegmentedView (= 1.3.0)
  - KFGradientProgressView (= 1.5.0)
  - KTVHTTPCache (= 2.0.1)
  - lottie-ios (= 3.2.3)
  - MKRingProgressView (= 2.3.0)
  - Popover (= 1.3.0)
  - R.swift (= 6.1.0)
  - SwiftDate (= 6.3.1)
  - SwiftyStoreKit (= 0.16.1)
  - YYText (= 1.0.7)

SPEC REPOS:
  http://gitlab.bigwinepot.com:8888/app/dgspec:
    - DGBase
    - DGBeta
    - DGNetworkUtils
    - DGSocial
  https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git:
    - Alamofire
    - AppAuth
    - BadgeHub
    - BMPlayer
    - BRPickerView
    - CocoaAsyncSocket
    - dsBridge
    - Easy
    - EFCountingLabel
    - ESTabBarController-swift
    - FBAEMKit
    - FBSDKCoreKit
    - FBSDKCoreKit_Basics
    - FBSDKLoginKit
    - FBSDKShareKit
    - Firebase
    - FirebaseABTesting
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseCrashlytics
    - FirebaseInstallations
    - FirebasePerformance
    - FirebaseRemoteConfig
    - fishhook
    - FLEX
    - FSPagerView
    - GDPerformanceView-Swift
    - Google-Mobile-Ads-SDK
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleSignIn
    - GoogleUserMessagingPlatform
    - GoogleUtilities
    - GTMAppAuth
    - GTMSessionFetcher
    - HandyJSON
    - IQKeyboardManagerSwift
    - JTAppleCalendar
    - JXPagingView
    - JXPhotoBrowser
    - JXSegmentedView
    - KFGradientProgressView
    - KTVCocoaHTTPServer
    - KTVHTTPCache
    - lottie-ios
    - MBProgressHUD
    - MJRefresh
    - MKRingProgressView
    - nanopb
    - NVActivityIndicatorView
    - OOMDetector
    - Popover
    - PromisesObjC
    - R.swift
    - R.swift.Library
    - SDWebImage
    - SnapKit
    - SwiftDate
    - SwiftyStoreKit
    - YYText

SPEC CHECKSUMS:
  Alamofire: 1c4fb5369c3fe93d2857c780d8bbe09f06f97e7c
  AppAuth: e48b432bb4ba88b10cb2bcc50d7f3af21e78b9c2
  BadgeHub: b227771329f78c37a2dae7502607ec6d00a50bd4
  BMPlayer: e4b241bd088644d7b89d991a1a65d1b1615d19b3
  BRPickerView: cdc9ef25f97914df653d1cda0fd8eeb27a5620f5
  CocoaAsyncSocket: 065fd1e645c7abab64f7a6a2007a48038fdc6a99
  DGBase: 5fda5629c034d1601bd963c072ccd9219f254f25
  DGBeta: b35c76493ae6c2542f09871b653332b231fe8005
  DGNetworkUtils: ff0f06d27dadc4fa8d100f57f15853b6e778e009
  DGSocial: 45ad263f475c38610cd038e704470dd8cf3446b9
  dsBridge: 48b62ee8a411ad601a88d6f6c8cf6cb634b206b7
  Easy: ae2e7195f3f5708547166ddbe1f80beb53dd715b
  EFCountingLabel: 210620994a2d54759f53034b5bda4642255969c7
  ESTabBarController-swift: 05593a6ad64700b03c0eb60ff625916370aa4136
  FBAEMKit: 955ca52eba8219c20f90774e8c6ff8bc7b3192a3
  FBSDKCoreKit: 678f64eda3f0ff25c189c2ebbfe87b1d96a85a6d
  FBSDKCoreKit_Basics: 6bee7c1f0932432901781203fa5e587ec5099148
  FBSDKLoginKit: 56d55e23fe66a6db045826190b0b4dbc0e1ca0a0
  FBSDKShareKit: 4ef957addab76816116ea92bd872e792f7137669
  Firebase: 5f8193dff4b5b7c5d5ef72ae54bb76c08e2b841d
  FirebaseABTesting: 10cbce8db9985ae2e3847ea44e9947dd18f94e10
  FirebaseAnalytics: 7761cbadb00a717d8d0939363eb46041526474fa
  FirebaseCore: 5743c5785c074a794d35f2fff7ecc254a91e08b1
  FirebaseCoreDiagnostics: 92e07a649aeb66352b319d43bdd2ee3942af84cb
  FirebaseCrashlytics: feb07e4e9187be3c23c6a846cce4824e5ce2dd0b
  FirebaseInstallations: 40bd9054049b2eae9a2c38ef1c3dd213df3605cd
  FirebasePerformance: 66eb58c3e3568a0501a9be271c8ff424dea0ff34
  FirebaseRemoteConfig: 2d6e2cfdb49af79535c8af8a80a4a5009038ec2b
  fishhook: ea19933abfe8f2f52c55fd8b6e2718467d3ebc89
  FLEX: bbc55d197f87d7cde2454c3981aa47069b694144
  FSPagerView: 670405b2f18e2a87fa37f20b00de783e562c25a8
  GDPerformanceView-Swift: 22d964fe40b19e3d914dba2586237d064de8fd77
  Google-Mobile-Ads-SDK: fb31b6ef68ef352b551ee29585cd9ceb07230cd0
  GoogleAppMeasurement: 4c19f031220c72464d460c9daa1fb5d1acce958e
  GoogleDataTransport: 8378d1fa8ac49753ea6ce70d65a7cb70ce5f66e6
  GoogleSignIn: c90b5bec45e780f54c6a8e1e3c182a86e3dda69d
  GoogleUserMessagingPlatform: 5f8b30daf181805317b6b985bb51c1ff3beca054
  GoogleUtilities: 9aa0ad5a7bc171f8bae016300bfcfa3fb8425749
  GTMAppAuth: 0ff230db599948a9ad7470ca667337803b3fc4dd
  GTMSessionFetcher: 5595ec75acf5be50814f81e9189490412bad82ba
  HandyJSON: 9e4e236f5d2dbefad5155a77417bbea438201c03
  IQKeyboardManagerSwift: c7955c0bdbf7b2eb29bb7daaa44e3d90f55a9a85
  JTAppleCalendar: f95b02c64f56d6f938fbf6582a04dcab9d709ebd
  JXPagingView: 90924b364a2ff7e94db534fad1fa50925ff69ee4
  JXPhotoBrowser: d32e94e1226d43bf5ed83164e3f5b651fed625e0
  JXSegmentedView: fec0d335355b6e019c494fe2e030bde8a36d2df6
  KFGradientProgressView: f6c9b9c863de186c5408a139f7cf38b050b928fc
  KTVCocoaHTTPServer: df8d7b861e603ff8037e9b2138aca2563a6b768d
  KTVHTTPCache: 588c3eb16f6bd1e6fde1e230dabfb7bd4e490a4d
  lottie-ios: c058aeafa76daa4cf64d773554bccc8385d0150e
  MBProgressHUD: 3ee5efcc380f6a79a7cc9b363dd669c5e1ae7406
  MJRefresh: fdf5e979eb406a0341468932d1dfc8b7f9fce961
  MKRingProgressView: f534209b9a1edc0beb2ea613e6b953ea2195b565
  nanopb: a0ba3315591a9ae0a16a309ee504766e90db0c96
  NVActivityIndicatorView: b19ddab2576f805cbe0fb2306cba3476e09a1dea
  OOMDetector: c23f4dfc969ea9bbd68a57cf7e5a3ca2169263cd
  Popover: 10e1d9528f81d9504df984b7b3f491292bc1822d
  PromisesObjC: 09985d6d70fbe7878040aa746d78236e6946d2ef
  R.swift: ec98ff71c4ab2f6fd01dd077e5afd15e63a4834c
  R.swift.Library: 0fc583cb55a99e28901299cc451614cad1161962
  SDWebImage: 7acbb57630ac7db4a495547fb73916ff3e432f6b
  SnapKit: 97b92857e3df3a0c71833cce143274bf6ef8e5eb
  SwiftDate: 72d28954e8e1c6c1c0f917ccc8005e4f83c7d4b2
  SwiftyStoreKit: 6b9c08810269f030586dac1fae8e75871a82e84a
  YYText: 5c461d709e24d55a182d1441c41dc639a18a4849

PODFILE CHECKSUM: e26bf633815600d4a8700777e3a246641e69ecc5

COCOAPODS: 1.11.3

**Comment by DuQuanzhong** [comment]
<img width="950" alt="截屏2023-04-24 11 19 46" src="https://user-images.githubusercontent.com/5549754/233893082-3b6065eb-bb13-4593-9dc0-5199e9864770.png">

**Comment by rizafran** [comment]
Thanks for reporting, @DuQuanzhong. First off, could you confirm if you didn't [disable the collection of PerfMon](https://firebase.google.com/docs/perf-mon/disable-sdk?platform=ios) in order to let our SDK propagate the collection of data?
