### ISSUE TITLE
FirebaseCore import not working

### ISSUE THREAD

**Issue by MitchellPeck** [firebase/firebase-ios-sdk#11166]
### Description

I'm working on an app in Xcode that uses firebase analytics, and inherently firebase core. However, when I attempt to run the app, I get an error 'no such module 'FirebaseCore'. I've tried everything that I can, no luck. I've even added "pod 'FirebaseCode'" and "pod 'Firebase/Core'" to my pod file but not even that helps. Am I missing something?

### Reproducing the issue

Not really sure how to reproduce this...

### Firebase SDK Version

9.4.1

### Xcode Version

13.3.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Firestore, Messaging

### Targeted Platforms

iOS

### Relevant Log Output

```shell
No such module 'FirebaseCore'
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
Filling out the full template may help us identify the issue and we may need a reproduction example.  Please clarify if you're using Swift Package manager or CocoaPods.
