### ISSUE TITLE
Can't resolve dependencies with googleappmeasurement on iOS with Xcode 14.3

### ISSUE THREAD

**Issue by ilosqut** [firebase/firebase-ios-sdk#11162]
### Description

I have using firebase-ios-sdk.git with swift packages. It is stopped syncing, I can't build my project:
Failed to resolve dependencies Dependencies could not be resolved because no versions of 'googleappmeasurement' match the requirement 10.9.0 and 'firebase-ios-sdk' depends on 'googleappmeasurement' 10.9.0.

### Firebase SDK Version

8.1.0

### Xcode Version

14.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Messaging

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment]
Hi @ilosqut, this error hints that your dependency on Firebase is pinned to `master`. Could you check that you are pinning to a release tag rather than a branch?

**Comment by ilosqut** [comment]
Hi @ncooke3 thanks for help,
I am using this, I guess it is release?
![1111](https://user-images.githubusercontent.com/909903/233696471-4b0f9853-ef02-4a15-8e14-c158ff9d7c10.jpg)

**Comment by ncooke3** [comment]
Aha, it looks like there are two dependencies on Firebase–– and it appears that Xcode is using the `master` one.

Delete the row circled in yellow:
<img width="579" alt="Screenshot 2023-04-21 at 1 18 52 PM" src="https://user-images.githubusercontent.com/36927374/233696975-93dd4dbb-0cbb-49a7-b1cb-446a706a1171.png">

**Comment by ilosqut** [comment]
@ncooke3 Yes. it is fixing issue, thanks
