### ISSUE TITLE
Auto Logging In-App Purchases not working with StoreKit 2

### ISSUE THREAD

**Issue by ArturoLee** [firebase/firebase-ios-sdk#11173]
### Description

I am submitting this issue to report that StoreKit 2 in-app events are not being automatically logged. While I have not experienced any issues with the automatic logging until the last app update, I have noticed that in-app purchases are not showing up in the logs. This is particularly strange as in-app purchases have always been tracked automatically in my app. No changes have been made to the Firebase implementation of the app either. In fact, other automatic events such as first_open and session_start are still being logged successfully.

The only change that was implemented is the transition to using the StoreKit 2 implementation of in-app purchases. Instead of using the SKPaymentQueue, I am now calling the .purchase() method on a Product object (https://developer.apple.com/documentation/storekit/product/3791971-purchase).

### Reproducing the issue

This issue can only be reproduced when making a purchase using the StoreKit 2 implementation.

### Firebase SDK Version

10.7.0

### Xcode Version

14.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by willbattel** [comment]
We also noticed this in our app after migrating to StoreKit 2. Not seeing in-app auto-renewable subscription purchases in Firebase Analytics anymore.

**Comment by paulb777** [comment]
Similar report at #10283.

**Comment by ArturoLee** [comment]
@paulb777 I did what it said and reached out to support. Here was their response.

<img width="1420" alt="Screenshot 2023-04-24 at 6 15 00 PM" src="https://user-images.githubusercontent.com/13791726/234128333-008a60a9-ba73-4485-8651-7265a07a3f3e.png">

Below is a screenshot of the drop off. Obviously it is nothing close to the real results shown in App Store Connect. It started Feb 16 with version 8.20. 

@willbattel I think that explains why there a few IAP were tracked for me as the majority of my IAP are subscriptions.

<img width="1257" alt="Screenshot 2023-04-24 at 6 11 56 PM" src="https://user-images.githubusercontent.com/13791726/234128987-5d06e4f7-f3d5-4d8f-a272-f3c4beab4407.png">

**Comment by fzlsq88** [comment]
I have the same issues!

**Comment by athew** [comment]
Same here as well. It's not clear for me that this is an issue for every Storekit 2 user or it only affects a small number of users?

**Comment by Faydee1220** [comment]
Same problem here +1. Not work with StoreKit 2. 

```
func buy(_ product: Product) async {
        do {
            await purchase(product)
        } catch StoreError.failedVerification {
        } catch {
        }
    }

func purchase(_ product: Product) async throws -> Transaction? {
        print("purchase")
        // Begin purchasing the `Product` the user selects.
        let result = try await product.purchase()

        switch result {
        case .success(let verification):
            print("success")
            // Check whether the transaction is verified. If it isn't,
            // this function rethrows the verification error.
            let transaction = try checkVerified(verification)

            // Always finish a transaction.
            await transaction.finish()

            Analytics.logEvent(AnalyticsEventPurchase,
                               parameters: [AnalyticsParameterTransactionID: transaction.id,
                                                   AnalyticsParameterItemID: product.id])

            return transaction
        case .pending:
            print("pending")
            return nil
        case .userCancelled:
            print("userCancelled")
            return nil
        default:
            return nil
        }
    }
```

**Comment by athew** [comment]
Sry Guys, I think it's getting ridiculous that there is still no information on this...

**Comment by ArturoLee** [comment]
@athew @paulb777  
This issue appears to hold priority before we proceed with other updates. Subscription and In-App Purchase events are arguably some of the most crucial metrics in Analytics. Currently, the effectiveness of Analytics seems compromised without these.

**Comment by paulb777** [comment]
Thanks for raising. I've asked the Analytics team for an update. The issue is tracked internally at b/285603233

**Comment by ArturoLee** [comment]
Hi @paulb777 and Team,

Just checking in on the StoreKit 2 issue. Any updates?

Thanks for your efforts.

**Comment by zoumingming** [comment]
@paulb777 
Same problem

**Comment by pcfba** [comment]
Thanks for reporting this issue. We're currently working on StoreKit 2 support. Our plan is to launch in Q4.

**Comment by ddanilyuk** [comment]
+1

**Comment by tamimNumrah** [comment]
+1

**Comment by pcfba** [comment]
StoreKit 2 support has been launched in 10.17.0, M139. Thanks @ArturoLee for the initial report and the others for your comments. Release notes and documentation:

https://firebase.google.com/support/release-notes/ios#10.17.0

https://firebase.google.com/docs/analytics/measure-in-app-purchases

**Comment by tamimNumrah** [comment]
We have implemented the new update but the results in Firebase dashboard are still same. The purchases are not showing up. Anybody else facing the same issue?

**Comment by Jeanno** [comment]
> We have implemented the new update but the results in Firebase dashboard are still same. The purchases are not showing up. Anybody else facing the same issue?

Have you tried adding `Analytics.logTransaction(transaction)`? It is mentioned here. https://firebase.google.com/docs/analytics/measure-in-app-purchases

But I wouldn't consider the current implementation as "Auto". Plus, only a few transactions show up on my firebase dashboard. Understood that it is technical challenging to capture everything as iOS doesn't expose them all. But would the firebase team consider creating a document detailing each and every scenario that should work? For example, AFAIK, recurring subscriptions wouldn't be captured.

**Comment by tamimNumrah** [comment]
> Have you tried adding `Analytics.logTransaction(transaction)`? It is mentioned here. https://firebase.google.com/docs/analytics/measure-in-app-purchases

Yes, I have followed their documentation. We event unlinked and linked our GA Property from Firebase.
