### ISSUE TITLE
Firebase 2FA "PERMISSION_DENIED" when sending  ´getSessionWithCompletion´

### ISSUE THREAD

**Issue by tornikegomareli** [firebase/firebase-ios-sdk#11176]
### Description

I implemented 2FA and was testing it with real number + testing number.  It was working fine, I was receiving `verificationID` when sending `getSessionWithCompletion`. Then out of a sudden it started to use recaptcha method and I was getting this `sessionError`. I was testing via device and simulator too. problem persists on both of them.
This problem hapens only on dev environment. Staging is fine. Basically they are different firebase projects with different App ID's.

### Reproducing the issue

- Implement 2FA authentication with Firebase as per documentation
- Start sending `getSessionWithCompletion` for testing purposes, both with real number and test numbers.
- At some point you will encounter `sessionError` indicating that API_KEY_IOS_APP_BLOCKED

### Firebase SDK Version

10.3.0

### Xcode Version

14.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, App Check, App Distribution, Authentication, Crashlytics, Database, Firestore, In-App Messaging, Messaging, Remote Config

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Error Domain=FIRAuthErrorDomain Code=17062 "{"error":{"code":403,"message":"Requests from this iOS client application <empty> are blocked.","errors":[{"message":"Requests from this iOS client application <empty> are blocked.","domain":"global","reason":"forbidden"}],"status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"API_KEY_IOS_APP_BLOCKED","domain":"googleapis.com","metadata":{"service":"identitytoolkit.googleapis.com", "PROJECT_NAME", "PROJECT_ID"}}]}}"
```

### If using Swift Package Manager, the project's Package.resolved

 {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk.git",
      "state" : {
        "revision" : "dce2e1abc6c0d5e830ff1cffe3f8633fda64001e",
        "version" : "10.3.0"
      }

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @tornikegomareli, could you confirm if you have removed the API key restrictions? We need to make an API call to our server from a web view in order to render the reCAPTCHA. If the issue persists, you may file through our [support channel](https://firebase.google.com/support) so the Auth team can take a look at your project and provide more insight as to why your app's traffic is restricted.

**Comment by tornikegomareli** [comment]
@rizafran  Hi, thanks for response. 
API key is not restricted

 ![Screenshot 2023-04-25 at 17 05 38](https://user-images.githubusercontent.com/24585160/234285489-94c9b648-259f-4288-aa9c-fbcdce651d20.png)

**Comment by rizafran** [comment]
Thanks for confirming, @tornikegomareli. Could you please file a ticket via our [support channel](https://firebase.google.com/support) so that the Auth team could check your project settings? With this, I'll be closing this issue for now.
