### ISSUE TITLE
FIRCLSMetricKitManagerTests fail in Xcode 14.3

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#11199]
### Description

`./scripts/pod_lib_lint.rb FirebaseCrashlytics.podspec --platforms=ios --no-clean` fails when Xcode 14.3 is the xcode selected.

### Reproducing the issue

`./scripts/pod_lib_lint.rb FirebaseCrashlytics.podspec --platforms=ios --no-clean`

    - NOTE  | [iOS] xcodebuild:  /Users/paul/gh3/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSMetricKitManagerTests.m:221: error: -[FIRCLSMetricKitManagerTests testCPUExceptionDiagnosticHandling] : *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0] (NSInvalidArgumentException)
    - NOTE  | [iOS] xcodebuild:  /Users/paul/gh3/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSMetricKitManagerTests.m:204: error: -[FIRCLSMetricKitManagerTests testCrashDiagnosticHandling] : *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0] (NSInvalidArgumentException)
    - NOTE  | [iOS] xcodebuild:  /Users/paul/gh3/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSMetricKitManagerTests.m:230: error: -[FIRCLSMetricKitManagerTests testDiskWriteExceptionDiagnosticHandling] : *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0] (NSInvalidArgumentException)
    - NOTE  | [iOS] xcodebuild:  /Users/paul/gh3/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSMetricKitManagerTests.m:377: error: -[FIRCLSMetricKitManagerTests testEmptyDiagnosticHandling] : *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0] (NSInvalidArgumentException)
    - NOTE  | [iOS] xcodebuild:  /Users/paul/gh3/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSMetricKitManagerTests.m:239: error: -[FIRCLSMetricKitManagerTests testFullDiagnosticHandling] : *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0] (NSInvalidArgumentException)
    - NOTE  | [iOS] xcodebuild:  /Users/paul/gh3/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSMetricKitManagerTests.m:212: error: -[FIRCLSMetricKitManagerTests testHangDiagnosticHandling] : *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0] (NSInvalidArgumentException)
    - NOTE  | [iOS] xcodebuild:  /Users/paul/gh3/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSMetricKitManagerTests.m:204: error: -[FIRCLSMetricKitManagerTests testMultiplePayloadsWithCrashesHandling] : *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0] (NSInvalidArgumentException)
    - NOTE  | [iOS] xcodebuild:  /Users/paul/gh3/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSMetricKitManagerTests.m:260: error: -[FIRCLSMetricKitManagerTests testPayloadWithMultipleCrashesHandling] : *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0] (NSInvalidArgumentException)

### Firebase SDK Version

10.9.0

### Xcode Version

14.3

### Installation Method

CocoaPods

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by themiswang** [comment]
Since we bump CI to Xcode 15, gonna close this ticket.
