### ISSUE TITLE
Use "main" instead of "master" as repo's default branch

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#11212]
### Description

Use "main" instead of "master" as repo's default branch

### Firebase SDK Version

all

### Xcode Version

14.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

All

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ryanwilson** [comment]
Random note so I don't forget to bring it up later: I wonder what Xcode's support is for a SwiftPM dependency that targets the `master` branch after it's been renamed to `main`.

**Comment by paulb777** [comment]
See this[ internal doc](https://docs.google.com/document/d/1nIxliX-5bB3sInXN1VK8DlQ_EIoBpppJAbDgD33G4os/edit#heading=h.uqwl3songb48) for some guidance.

Current plan is to address this in December 2023.

**Comment by paulb777** [comment]
Key points from the linked doc:

- See https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#renaming-a-branch
- Rename the branch
- Update the GHA and other references from `main` to `master`
- Send out instructions at that link for people with local repo checkouts
- Verify FirebasePrivate mirror still works

**Comment by paulb777** [comment]
Completed today. Thanks @ncooke3
