### ISSUE TITLE
Facing issue with CCTLogWriter Firebase

### ISSUE THREAD

**Issue by Aaqibali279** [firebase/firebase-ios-sdk#11227]
### Description

com.apple.main-thread
0  libsystem_kernel.dylib         0xc84 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13b54 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13e2c mach_msg_overwrite + 540
3  libsystem_kernel.dylib         0x11c8 mach_msg + 24
4  CoreFoundation                 0x79114 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7a340 __CFRunLoopRun + 1208
6  CoreFoundation                 0x7f4dc CFRunLoopRunSpecific + 612
7  GraphicsServices               0x135c GSEventRunModal + 164
8  UIKitCore                      0x39d37c -[UIApplication _run] + 888
9  UIKitCore                      0x39cfe0 UIApplicationMain + 340
10 MyApp                           0x81ac main + 24 (AppDelegate.swift:24)
11 ???                            0x1c7decdec (Missing)
Thread
0  libsystem_pthread.dylib        0xb74 start_wqthread + 254
com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0xc84 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13b54 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13e2c mach_msg_overwrite + 540
3  libsystem_kernel.dylib         0x11c8 mach_msg + 24
4  CoreFoundation                 0x79114 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7a340 __CFRunLoopRun + 1208
6  CoreFoundation                 0x7f4dc CFRunLoopRunSpecific + 612
7  Foundation                     0x420c4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0x41fac -[NSRunLoop(NSRunLoop) runUntilDate:] + 64
9  UIKitCore                      0x4cfdac -[UIEventFetcher threadMain] + 416
10 Foundation                     0x5b634 __NSThread__start__ + 716
11 libsystem_pthread.dylib        0x16b8 _pthread_start + 148
12 libsystem_pthread.dylib        0xb88 thread_start + 8
CCTLogWriter
0  libsystem_kernel.dylib         0xc00 semaphore_wait_trap + 8
1  libdispatch.dylib              0x4448 _dispatch_sema4_wait + 28
2  libdispatch.dylib              0x4afc _dispatch_semaphore_wait_slow + 132
3  MyApp                           0x6478e4 -[GMSx_CCTPhenotypeLogTransformer transform:] + 783984
4  MyApp                           0x6664a0 -[GMSx_CCTLogWriter writeLogInternal:pseudonymousID:logDirectory:clock:logTransformers:includeAccessibilityInfo:flags:] + 909868
5  MyApp                           0x665ecc __111-[GMSx_CCTLogWriter writeLog:pseudonymousID:logDirectory:clock:logTransformers:includeAccessibilityInfo:flags:]_block_invoke + 908376
6  libdispatch.dylib              0x2320 _dispatch_call_block_and_release + 32
7  libdispatch.dylib              0x3eac _dispatch_client_callout + 20
8  libdispatch.dylib              0xb534 _dispatch_lane_serial_drain + 668
9  libdispatch.dylib              0xc0d8 _dispatch_lane_invoke + 436
10 libdispatch.dylib              0x16cdc _dispatch_workloop_worker_thread + 648
11 libsystem_pthread.dylib        0xddc _pthread_wqthread + 288
12 libsystem_pthread.dylib        0xb7c start_wqthread + 8
Thread
0  libsystem_pthread.dylib        0xb74 start_wqthread + 254
Thread
0  libsystem_pthread.dylib        0xb74 start_wqthread + 254
Crashed: com.apple.root.utility-qos
0  libobjc.A.dylib                0x4174 objc_release + 16
1  libobjc.A.dylib                0x4174 objc_release_x0 + 16
2  Sentry                         0x3f9a0 -[SentryDispatchQueueWrapper dispatchAfter:block:] + 160
3  Sentry                         0x849b8 -[SentryTracer dispatchIdleTimeout] + 260
4  Sentry                         0x85908 -[SentryTracer spanFinished:] + 424
5  Sentry                         0x7c38c -[SentrySpan finishWithStatus:] + 528
6  Sentry                         0x5ee78 -[SentryNSDataTracker finishTrackingNSData:span:] + 156
7  Sentry                         0x5de6c -[SentryNSDataTracker measureNSData:writeToFile:options:error:method:] + 192
8  Sentry                         0x5d424 __38+[SentryNSDataSwizzling swizzleNSData]_block_invoke_2.71 + 220
9  MyApp                           0x9dac24 -[GMPx_PHTHeterodyneSyncer processResponse:account:syncedScopes:requestedPackages:requestError:invalidAuthTokenIndices:authenticatedGaiaIds:callback:] + 360108
10 MyApp                           0x9d9cdc __148-[GMPx_PHTHeterodyneSyncer batchSyncWithAccounts:syncedScopes:fetchReason:throttlingCache:heterodyneSyncInfo:accountToAuthToken:lastError:callback:]_block_invoke_2 + 356196
11 libdispatch.dylib              0x2320 _dispatch_call_block_and_release + 32
12 libdispatch.dylib              0x3eac _dispatch_client_callout + 20
13 libdispatch.dylib              0x15b74 _dispatch_root_queue_drain + 956
14 libdispatch.dylib              0x16158 _dispatch_worker_thread2 + 164
15 libsystem_pthread.dylib        0xda0 _pthread_wqthread + 228
16 libsystem_pthread.dylib        0xb7c start_wqthread + 8
com.google.firebase.crashlytics.MachExceptionServer
0  libsystem_kernel.dylib         0xc84 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13b54 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13e2c mach_msg_overwrite + 540
3  libsystem_kernel.dylib         0x11c8 mach_msg + 24
4  FirebaseCrashlytics            0x1a520 FIRCLSMachExceptionServer + 104
5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
6  libsystem_pthread.dylib        0xb88 thread_start + 8
Thread
0  libsystem_kernel.dylib         0x1144 __semwait_signal + 8
1  libsystem_c.dylib              0x5888 nanosleep + 220
2  libsystem_c.dylib              0x16b1c sleep + 52
3  Sentry                         0x1b9bc monitorCachedData + 700
4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
5  libsystem_pthread.dylib        0xb88 thread_start + 8
SentryCrash Exception Handler (Secondary)
0  libsystem_kernel.dylib         0xc84 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13b54 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13e2c mach_msg_overwrite + 540
3  libsystem_kernel.dylib         0x11c8 mach_msg + 24
4  Sentry                         0x29224 handleExceptions + 172
5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
6  libsystem_pthread.dylib        0xb88 thread_start + 8
io.sentry.app-hang-tracker
0  libsystem_kernel.dylib         0x1144 __semwait_signal + 8
1  libsystem_c.dylib              0x5888 nanosleep + 220
2  Foundation                     0xb294c +[NSThread sleepForTimeInterval:] + 160
3  Sentry                         0x93ec -[SentryANRTracker detectANRs] + 772
4  Foundation                     0x5b634 __NSThread__start__ + 716
5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
6  libsystem_pthread.dylib        0xb88 thread_start + 8
com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0xc84 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13b54 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13e2c mach_msg_overwrite + 540
3  libsystem_kernel.dylib         0x11c8 mach_msg + 24
4  CoreFoundation                 0x79114 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7a340 __CFRunLoopRun + 1208
6  CoreFoundation                 0x7f4dc CFRunLoopRunSpecific + 612
7  CFNetwork                      0x2587e0 _CFURLStorageSessionDisableCache + 60900
8  Foundation                     0x5b634 __NSThread__start__ + 716
9  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
10 libsystem_pthread.dylib        0xb88 thread_start + 8
com.google.Maps.LabelingBehavior
0  libsystem_kernel.dylib         0xc84 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13b54 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13e2c mach_msg_overwrite + 540
3  libsystem_kernel.dylib         0x11c8 mach_msg + 24
4  CoreFoundation                 0x79114 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7a340 __CFRunLoopRun + 1208
6  CoreFoundation                 0x7f4dc CFRunLoopRunSpecific + 612
7  Foundation                     0x420c4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  MyApp                           0x9691b0 -[GMSx_GTMSimpleWorkerThread main] + 59104
9  Foundation                     0x5b634 __NSThread__start__ + 716
10 libsystem_pthread.dylib        0x16b8 _pthread_start + 148
11 libsystem_pthread.dylib        0xb88 thread_start + 8
CCTClearcutUploader
0  libsystem_kernel.dylib         0x132c __getattrlist + 8
1  libsystem_kernel.dylib         0x132c getattrlist + 8
2  CoreServicesInternal           0x9da8 GetattrlistRetry + 56
3  CoreServicesInternal           0x2938 DirEnumOpen + 948
4  CoreServicesInternal           0x7a20 _InitalizeDirectoryEnumerator(_CFURLEnumerator*) + 1412
5  CoreServicesInternal           0x2398 _URLEnumeratorGetNextURL + 96
6  Foundation                     0xb7968 -[NSFileManager contentsOfDirectoryAtURL:includingPropertiesForKeys:options:error:] + 212
7  MyApp                           0x669c38 +[GMSx_CCTClearcutFileUtility directoryContents:] + 924100
8  MyApp                           0x6400c0 -[GMSx_CCTClearcutUploader cleanupOldLogFiles] + 753228
9  MyApp                           0x63f8b4 -[GMSx_CCTClearcutUploader finishUploadAndCallHandlers] + 751168
10 MyApp                           0x63f5d0 -[GMSx_CCTClearcutUploader processResponse:context:logFiles:requestTime:isBatched:error:] + 750428
11 libdispatch.dylib              0x2320 _dispatch_call_block_and_release + 32
12 libdispatch.dylib              0x3eac _dispatch_client_callout + 20
13 libdispatch.dylib              0xb534 _dispatch_lane_serial_drain + 668
14 libdispatch.dylib              0xc0a4 _dispatch_lane_invoke + 384
15 libdispatch.dylib              0x16cdc _dispatch_workloop_worker_thread + 648
16 libsystem_pthread.dylib        0xddc _pthread_wqthread + 288
17 libsystem_pthread.dylib        0xb7c start_wqthread + 8
PHTFlatFilePhenotype
0  libsystem_kernel.dylib         0x1384 stat + 8
1  libsystem_kernel.dylib         0x1384 stat64 + 8
2  Foundation                     0x6c294 _NSFileExistsAtPath + 140
3  Foundation                     0x8593c _NSStandardizePathUsingCache + 2188
4  Foundation                     0x60d7c -[NSString(NSPathUtilities) _stringByStandardizingPathUsingCache:] + 128
5  Foundation                     0x60550 _NSExpandTildeInPath + 144
6  Foundation                     0x6001c -[NSString(NSPathUtilities) stringByExpandingTildeInPath] + 112
7  Foundation                     0x5ff0c NSSearchPathForDirectoriesInDomains + 228
8  Foundation                     0x5ef64 -[NSFileManager URLForDirectory:inDomain:appropriateForURL:create:error:] + 220
9  MyApp                           0x66435c +[GMSx_PHTURL localDirectoryWithError:] + 901352
10 MyApp                           0x664488 +[GMSx_PHTURL localSubDirectory:error:] + 901652
11 MyApp                           0x664578 +[GMSx_PHTURL localSubDirectory:fileName:error:] + 901892
12 MyApp                           0x6630cc +[GMSx_PHTSnapshot committedSnapshotForPackage:obfuscatedGaiaID:error:] + 896600
13 MyApp                           0x64f3d0 __65-[GMSx_PHTFlatFilePhenotype experimentTokens:accountID:callback:]_block_invoke.377 + 815452
14 libdispatch.dylib              0x2320 _dispatch_call_block_and_release + 32
15 libdispatch.dylib              0x3eac _dispatch_client_callout + 20
16 libdispatch.dylib              0xb534 _dispatch_lane_serial_drain + 668
17 libdispatch.dylib              0xc0a4 _dispatch_lane_invoke + 384
18 libdispatch.dylib              0x16cdc _dispatch_workloop_worker_thread + 648
19 libsystem_pthread.dylib        0xddc _pthread_wqthread + 288
20 libsystem_pthread.dylib        0xb7c start_wqthread + 8
Thread
0  libsystem_pthread.dylib        0xb74 start_wqthread + 254

### Reproducing the issue

in firebase sdk version 10.6 using xcode 13.4 and ios 16

### Firebase SDK Version

10.6

### Xcode Version

13.4

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, Crashlytics, DynamicLinks, Messaging, Remote Config

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reaching out, @Aaqibali279. First off, could you share your `Podfile.lock` in the issue template?

**Comment by Aaqibali279** [comment]
PODS:
  - Alamofire (5.6.4)
  - Auth0 (2.3.2):
    - JWTDecode (~> 3.0)
    - SimpleKeychain (~> 1.0)
  - AWSCore (2.30.4)
  - AWSSES (2.30.4):
    - AWSCore (= 2.30.4)
  - Differentiator (5.0.0)
  - ESPullToRefresh (2.9.3)
  - Firebase/Analytics (10.6.0):
    - Firebase/Core
  - Firebase/Core (10.6.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 10.6.0)
  - Firebase/CoreOnly (10.6.0):
    - FirebaseCore (= 10.6.0)
  - Firebase/Crashlytics (10.6.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 10.6.0)
  - Firebase/DynamicLinks (10.6.0):
    - Firebase/CoreOnly
    - FirebaseDynamicLinks (~> 10.6.0)
  - Firebase/Messaging (10.6.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 10.6.0)
  - Firebase/RemoteConfig (10.6.0):
    - Firebase/CoreOnly
    - FirebaseRemoteConfig (~> 10.6.0)
  - FirebaseABTesting (10.6.0):
    - FirebaseCore (~> 10.0)
  - FirebaseAnalytics (10.6.0):
    - FirebaseAnalytics/AdIdSupport (= 10.6.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - GoogleUtilities/Network (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (10.6.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleAppMeasurement (= 10.6.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - GoogleUtilities/Network (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseCore (10.6.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Logger (~> 7.8)
  - FirebaseCoreExtension (10.6.0):
    - FirebaseCore (~> 10.0)
  - FirebaseCoreInternal (10.6.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseCrashlytics (10.6.0):
    - FirebaseCore (~> 10.5)
    - FirebaseInstallations (~> 10.0)
    - FirebaseSessions (~> 10.5)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.8)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (~> 2.1)
  - FirebaseDynamicLinks (10.6.0):
    - FirebaseCore (~> 10.0)
  - FirebaseInstallations (10.6.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)
  - FirebaseMessaging (10.6.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Reachability (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseRemoteConfig (10.6.0):
    - FirebaseABTesting (~> 10.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseSessions (10.6.0):
    - FirebaseCore (~> 10.5)
    - FirebaseCoreExtension (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.10)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesSwift (~> 2.1)
  - FSCalendar (2.8.4)
  - GoogleAppMeasurement (10.6.0):
    - GoogleAppMeasurement/AdIdSupport (= 10.6.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - GoogleUtilities/Network (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/AdIdSupport (10.6.0):
    - GoogleAppMeasurement/WithoutAdIdSupport (= 10.6.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - GoogleUtilities/Network (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/WithoutAdIdSupport (10.6.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - GoogleUtilities/Network (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleDataTransport (9.2.1):
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleMaps (7.4.0):
    - GoogleMaps/Maps (= 7.4.0)
  - GoogleMaps/Base (7.4.0)
  - GoogleMaps/Maps (7.4.0):
    - GoogleMaps/Base
  - GooglePlaces (7.4.0)
  - GoogleUtilities/AppDelegateSwizzler (7.11.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (7.11.0):
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/Logger (7.11.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (7.11.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (7.11.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.11.0)"
  - GoogleUtilities/Reachability (7.11.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (7.11.0):
    - GoogleUtilities/Logger
  - GSKStretchyHeaderView (1.0.4)
  - IQKeyboardManager (6.5.11)
  - JWTDecode (3.0.1)
  - Kingfisher (7.6.2)
  - lottie-ios (4.1.3)
  - MDHTMLLabel (1.0.2)
  - Moya/Core (15.0.0):
    - Alamofire (~> 5.0)
  - Moya/RxSwift (15.0.0):
    - Moya/Core
    - RxSwift (~> 6.0)
  - nanopb (2.30909.0):
    - nanopb/decode (= 2.30909.0)
    - nanopb/encode (= 2.30909.0)
  - nanopb/decode (2.30909.0)
  - nanopb/encode (2.30909.0)
  - ObjectMapper (4.2.0)
  - PromisesObjC (2.2.0)
  - PromisesSwift (2.2.0):
    - PromisesObjC (= 2.2.0)
  - PullUpController (0.8.0)
  - R.swift (7.3.0)
  - RMMapper (1.1.5)
  - RxCocoa (6.5.0):
    - RxRelay (= 6.5.0)
    - RxSwift (= 6.5.0)
  - RxDataSources (5.0.0):
    - Differentiator (~> 5.0)
    - RxCocoa (~> 6.0)
    - RxSwift (~> 6.0)
  - RxRelay (6.5.0):
    - RxSwift (= 6.5.0)
  - RxSwift (6.5.0)
  - Sentry (8.3.0):
    - Sentry/Core (= 8.3.0)
    - SentryPrivate (= 8.3.0)
  - Sentry/Core (8.3.0):
    - SentryPrivate (= 8.3.0)
  - SentryPrivate (8.3.0)
  - SimpleKeychain (1.0.1)
  - SwiftMessages (9.0.6):
    - SwiftMessages/App (= 9.0.6)
  - SwiftMessages/App (9.0.6)
  - "UITextField+Max (1.0.2)"

DEPENDENCIES:
  - Auth0
  - AWSSES
  - ESPullToRefresh
  - Firebase/Analytics
  - Firebase/Core
  - Firebase/Crashlytics
  - Firebase/DynamicLinks
  - Firebase/Messaging
  - Firebase/RemoteConfig
  - FSCalendar
  - GoogleMaps
  - GooglePlaces
  - GSKStretchyHeaderView
  - IQKeyboardManager
  - Kingfisher
  - lottie-ios
  - MDHTMLLabel
  - Moya/RxSwift
  - ObjectMapper
  - PullUpController
  - R.swift
  - RMMapper
  - RxCocoa
  - RxDataSources
  - RxSwift
  - Sentry (from `https://github.com/getsentry/sentry-cocoa.git`, tag `8.3.0`)
  - SwiftMessages
  - "UITextField+Max"

SPEC REPOS:
  trunk:
    - Alamofire
    - Auth0
    - AWSCore
    - AWSSES
    - Differentiator
    - ESPullToRefresh
    - Firebase
    - FirebaseABTesting
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreExtension
    - FirebaseCoreInternal
    - FirebaseCrashlytics
    - FirebaseDynamicLinks
    - FirebaseInstallations
    - FirebaseMessaging
    - FirebaseRemoteConfig
    - FirebaseSessions
    - FSCalendar
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleMaps
    - GooglePlaces
    - GoogleUtilities
    - GSKStretchyHeaderView
    - IQKeyboardManager
    - JWTDecode
    - Kingfisher
    - lottie-ios
    - MDHTMLLabel
    - Moya
    - nanopb
    - ObjectMapper
    - PromisesObjC
    - PromisesSwift
    - PullUpController
    - R.swift
    - RMMapper
    - RxCocoa
    - RxDataSources
    - RxRelay
    - RxSwift
    - SentryPrivate
    - SimpleKeychain
    - SwiftMessages
    - "UITextField+Max"

EXTERNAL SOURCES:
  Sentry:
    :git: https://github.com/getsentry/sentry-cocoa.git
    :tag: 8.3.0

CHECKOUT OPTIONS:
  Sentry:
    :git: https://github.com/getsentry/sentry-cocoa.git
    :tag: 8.3.0

SPEC CHECKSUMS:
  Alamofire: 4e95d97098eacb88856099c4fc79b526a299e48c
  Auth0: 64da28fdc5cd499aa516dc4bfd0ace8efae2c1da
  AWSCore: 19b8233fe2d0ed3ccf5cff833a615814282cdc90
  AWSSES: bfb2c38c57911e22ddaf6a5839e2e91bf264bc0b
  Differentiator: e8497ceab83c1b10ca233716d547b9af21b9344d
  ESPullToRefresh: 0d68daa602b343c81753a1b95e09fd0bfcddfd40
  Firebase: f13680471b021937f2230ea8503c7809d8c29806
  FirebaseABTesting: cec558d2e670053b1e862c98cfecae64aecfd629
  FirebaseAnalytics: 9f382605c5ee412b039212f054bf7a403d9850c1
  FirebaseCore: fa80ad16a62d52f67274b5b88304c3a318bbf9a4
  FirebaseCoreExtension: 318e5ee9ad4092b00423c2bddd51c3f5c3585973
  FirebaseCoreInternal: c7cd505e2136811096b225ac388d6254a2622362
  FirebaseCrashlytics: ede07e7f433a0a2270112baf2d156b111cfb422d
  FirebaseDynamicLinks: 99c501143953e925681a37aade96bb2db34b30ca
  FirebaseInstallations: 13dde135fa0524e15bddb133ccc8465c53a1b3f3
  FirebaseMessaging: fd93783258c53ae5cdb9b41bf0c51606a677f2d5
  FirebaseRemoteConfig: 7ef4dd164f3066c64ca1efab0f990152a6b94fc0
  FirebaseSessions: 60e877d5159eb571a3d82df68947a7941b475a20
  FSCalendar: 2d1d0d9398f12d439f55c1fe0f01525b151b8260
  GoogleAppMeasurement: 686b48c3c895f3c55c70719041913d5d150b74f6
  GoogleDataTransport: ea169759df570f4e37bdee1623ec32a7e64e67c4
  GoogleMaps: 032f676450ba0779bd8ce16840690915f84e57ac
  GooglePlaces: 544e908d94860bf6f8fc1865b80d2c7eb6b5f937
  GoogleUtilities: c2bdc4cf2ce786c4d2e6b3bcfd599a25ca78f06f
  GSKStretchyHeaderView: 9743704c12bdc9cf7c7947bad3af8bf24f7061e3
  IQKeyboardManager: ef43ce1ba1e5aaf4adf222c0a46f39761f246879
  JWTDecode: 2eed97c2fa46ccaf3049a787004eedf0be474a87
  Kingfisher: 6c5449c6450c5239166510ba04afe374a98afc4f
  lottie-ios: d0954d3150061f662ed0adf96ef98d7421864c47
  MDHTMLLabel: 18bf09ec7d6c1ae396497345c005857c0493ee0a
  Moya: 138f0573e53411fb3dc17016add0b748dfbd78ee
  nanopb: b552cce312b6c8484180ef47159bc0f65a1f0431
  ObjectMapper: 1eb41f610210777375fa806bf161dc39fb832b81
  PromisesObjC: 09985d6d70fbe7878040aa746d78236e6946d2ef
  PromisesSwift: cf9eb58666a43bbe007302226e510b16c1e10959
  PullUpController: 2f7ccaa0f35b31b47e3efbe1854c7f781552b3c7
  R.swift: cef1c530541cb49412752721797f10dae6b32d11
  RMMapper: 21122d753c736d975f6c61e674afce8db73579af
  RxCocoa: 94f817b71c07517321eb4f9ad299112ca8af743b
  RxDataSources: aa47cc1ed6c500fa0dfecac5c979b723542d79cf
  RxRelay: 1de1523e604c72b6c68feadedd1af3b1b4d0ecbd
  RxSwift: 5710a9e6b17f3c3d6e40d6e559b9fa1e813b2ef8
  Sentry: 757565eb01e2a6ef6b26e897e4e47e8213e12f06
  SentryPrivate: 668d6ce46835769b32e61dc8b5c78ef0b6cdcef8
  SimpleKeychain: 130211269f88f038d7dc5254cf0b1b9ce978c398
  SwiftMessages: f0c7ef4705a570ad6c5e208b611f4333e660ed92
  "UITextField+Max": b7c067d0b1ff64ba5b33bdd6b8e809882b096288

PODFILE CHECKSUM: 7d93b2fb717e347c6c87d6084d4aed4201885b1ex

COCOAPODS: 1.11.2
