### ISSUE TITLE
Accessing custom claims always crashes

### ISSUE THREAD

**Issue by yusuftor** [firebase/firebase-ios-sdk#1127]
* Xcode version: 9.3
  * Firebase SDK version: 4.13.0
  * Firebase Component: Auth

Whenever I try to access the custom claims from my token, the app crashes. My code

```
Auth.auth().addStateDidChangeListener { (auth, user) in
    user?.getIDTokenResult() { tokenResult, error in
        guard tokenResult?.claims["type"] != nil else {  // Crashes on this line
            ... 
        }
}
```

At the line where it crashes it says `Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)` which isn't helpful. The claims are implemented correctly because I'm currently using a third party library to decode the claims. However, it'd be easier if I could use the newly introduced `getIDTokenResult` function.

**Comment by morganchen12** [comment]
Can you give the stack trace of the crash? `EXC_BAD_INSTRUCTION` is usually a force-unwrap error when running on iOS Simulator or Mac architectures. In your code it looks like `claims` should be an optional and the `guard` line should be

```swift
guard tokenResult?.claims?["type"] != nil else {
  // ...
}
```

**Comment by yusuftor** [comment]
@morganchen12 `claims` isn't an optional so I can't use a `?` on it in a guard (it gives me an error if I do). 
Stack trace:

```
  - 0 : "0   ???                                 0x000000012d1f17aa 0x0 + 5051979690"
  - 1 : "1   ???                                 0x000000012d1f1865 0x0 + 5051979877"
  - 2 : "2   MyApp                                0x000000010bcf48e0 main + 0"
  - 3 : "3   libswiftCore.dylib                  0x00000001156b36f0 _T0s26_forceBridgeFromObjectiveCxyXl_xmtlF + 288"
  - 4 : "4   libswiftFoundation.dylib            0x0000000115db9373 _T0s10DictionaryV10FoundationE26_forceBridgeFromObjectiveCySo12NSDictionaryC_AByxq_GSgz6resulttFZyyp_ypSpy0F1C8ObjCBoolVGtcfU_ + 323"
  - 5 : "5   libswiftFoundation.dylib            0x0000000115e8ff69 _T0s10DictionaryV10FoundationE26_forceBridgeFromObjectiveCySo12NSDictionaryC_AByxq_GSgz6resulttFZyyp_ypSpy0F1C8ObjCBoolVGtcfU_TA + 25"
  - 6 : "6   libswiftFoundation.dylib            0x0000000115db944b _T0ypypSpy10ObjectiveC8ObjCBoolVGIgiiy_yXlyXlADIyByyy_TR + 107"
  - 7 : "7   CoreFoundation                      0x000000010f2de6c2 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226"
  - 8 : "8   libswiftFoundation.dylib            0x0000000115e61d05 _T0s10DictionaryV10FoundationE26_forceBridgeFromObjectiveCySo12NSDictionaryC_AByxq_GSgz6resulttFZTf4gnn_n + 821"
  - 9 : "9   libswiftFoundation.dylib            0x0000000115daf657 _T0s10DictionaryV10FoundationE36_unconditionallyBridgeFromObjectiveCAByxq_GSo12NSDictionaryCSgFZ + 55"
  - 10 : "10 MyApp                                0x000000010bcf2e71 _T04MyApp11AppDelegateC12listenToAuth33_A6CB784D4187C53F74A105BE764D011FLLyyFySo0F0C_So4UserCSgtcfU_ySo0F11TokenResultCSg_s5Error_pSgtcfU_ + 209"
  - 11 : "11  MyApp                                0x000000010bcf5256 _T04MyApp11AppDelegateC12listenToAuth33_A6CB784D4187C53F74A105BE764D011FLLyyFySo0F0C_So4UserCSgtcfU_ySo0F11TokenResultCSg_s5Error_pSgtcfU_TA + 38"
  - 12 : "12  MyApp                                0x000000010bcf3700 _T0So15AuthTokenResultCSgs5Error_pSgIegxx_ACSo7NSErrorCSgIeyByy_TR + 128"
  - 13 : "13  libdispatch.dylib                   0x0000000116245807 _dispatch_call_block_and_release + 12"
  - 14 : "14  libdispatch.dylib                   0x0000000116246848 _dispatch_client_callout + 8"
  - 15 : "15  libdispatch.dylib                   0x000000011625192b _dispatch_main_queue_callback_4CF + 628"
  - 16 : "16  CoreFoundation                      0x000000010f31cc99 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9"
  - 17 : "17  CoreFoundation                      0x000000010f2e0ea6 __CFRunLoopRun + 2342"
  - 18 : "18  CoreFoundation                      0x000000010f2e030b CFRunLoopRunSpecific + 635"
  - 19 : "19  GraphicsServices                    0x0000000117a90a73 GSEventRunModal + 62"
  - 20 : "20  UIKit                               0x000000011243a0b7 UIApplicationMain + 159"
  - 21 : "21  MyApp                                0x000000010bcf4917 main + 55"
  - 22 : "22  libdyld.dylib                       0x00000001162c3955 start + 1"
  - 23 : "23  ???                                 0x0000000000000001 0x0 + 1"

```

**Comment by morganchen12** [comment]
Looks like the app is crashing when trying to bridge the `claims` dictionary from ObjC to Swift. Can you post the contents of the `claims` dictionary?

You may have a hard time doing this, since it'll probably crash your code on access. Otherwise, can you share a project that reproduces this issue?

**Comment by yusuftor** [comment]
Ah hold on, it looks like this user that I'm using hasn't got custom claims associated with them! I just tried and there's no claims dictionary. So it's crashing when the claims don't exist. I guess `claims` should be an optional to handle this case. Because I only recently introduced claims into the users profile, so only affects recent users.

**Comment by morganchen12** [comment]
@yusuftor can you share the ID token of one of these users? `claims` shouldn't ever be `nil`, even in the case when there are no claims. In that case it should just return an empty dictionary instead.

**Comment by yusuftor** [comment]
sure: 

eyJhbGciOiJSUzI1NiIsImtpZCI6ImZlZjg5YmE3MjEyNmU1NGZkZDUwYzkxOWI3YWRiNWUyNmYwMjk5Y2YifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcWphbS1maXJlYmFzZS1zdGFnaW5nIiwibmFtZSI6Ill1c3VmIiwicGljdHVyZSI6Imh0dHBzOi8vZmlyZWJhc2VzdG9yYWdlLmdvb2dsZWFwaXMuY29tL3YwL2IvcWphbS1maXJlYmFzZS1zdGFnaW5nLmFwcHNwb3QuY29tL28vcHJvZmlsZUltYWdlcyUyRmFJY1F0Qk9HUDRlQWdadnhoMGVtYUhHQ01OZjElMkY4OEUwNUI2Ni02MEYyLTQwMDItQjRFQy1DQzRCQURCNzNGOEIuanBnP2FsdD1tZWRpYSZ0b2tlbj1kYzZmODc3Ny0zMmIwLTQ2YmYtOWVlMS1mNDg0MDU4NmExYmYiLCJhdWQiOiJxamFtLWZpcmViYXNlLXN0YWdpbmciLCJhdXRoX3RpbWUiOjE1MjI0MzE0MjMsInVzZXJfaWQiOiJhSWNRdEJPR1A0ZUFnWnZ4aDBlbWFIR0NNTmYxIiwic3ViIjoiYUljUXRCT0dQNGVBZ1p2eGgwZW1hSEdDTU5mMSIsImlhdCI6MTUyNDA0MDU0MCwiZXhwIjoxNTI0MDQ0MTQwLCJlbWFpbCI6ImNsZXZlcnlydEBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiY2xldmVyeXJ0QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.VRle-QPsZC03fAP_JwV3AyGRcBg8FO-Oa_pY8AtOf9EhpmilkzOWhIS7bXAd-O_N9ty9C53N8dkb4Tun5CoAYPtL8DC7vljRdeCTCQNGqHEgMXZWHdWDmXku0JFlh_F2AyWPpfsojSqo5igSL7pmQPN2EQVFL7wWFRJpBsc3fyMrzIt4QgbZRJaw8tQY8n2W1g0iHlokcmxB2tTkcqob7mnpgrgzGDiVXfMxKJ_O-aZm54FGrqQS-BVHsHfAvMBS03KiyWj4XdV3MvuwWJGxcdEWYcZ-TUdo813g0gm35Z-eq0yjLpFr_MLtUr61o3LG5uB5rh6GfOQAQq-ij6nEAQ

**Comment by morganchen12** [comment]
Looks like this user token generates a valid claims dictionary just fine. Can you share your project?

**Comment by morganchen12** [comment]
We've identified the issue. The claims dictionary is annotated as a `[String: String]` type, but it may contain non-string objects.

**Comment by yusuftor** [comment]
Great, thank you!
