### ISSUE TITLE
Phone authentication with reCAPTCHA doesn't work after api key restriction to iOS bundle id

### ISSUE THREAD

**Issue by romansorochak** [firebase/firebase-ios-sdk#11287]
### Description

If restrict API to iOS app's bundle then reCAPTCHA Phone Number Authentication stops working. 
Following error:
```swift
{
   "error":{
      "code":403,
      "message":"Requests from this iOS client application <empty> are blocked.",
      "errors":[
         {
            "message":"Requests from this iOS client application <empty> are blocked.",
            "domain":"global",
            "reason":"forbidden"
         }
      ],
      "status":"PERMISSION_DENIED"
   }
}
```

I found similar issue https://github.com/firebase/firebase-ios-sdk/issues/7653 but I haven't found a solution there.
Ideally it would be that we restrict API somehow but at the same time reCAPTCHA is still working.
Also I know that if do the same restriction on `Android` side reCAPTCHA still works as expected.
Please help me figure it out.

### Reproducing the issue

Restricting firebase API key on the google cloud console for the app's bundle identifier and try the reCAPTCHA authentication flow.

### Firebase SDK Version

10.7.0

### Xcode Version

14.2

### Installation Method

Carthage

### Firebase Product(s)

App Check, Authentication, Crashlytics, Messaging, Remote Config

### Targeted Platforms

iOS

### Relevant Log Output

```shell
{
   "error":{
      "code":403,
      "message":"Requests from this iOS client application <empty> are blocked.",
      "errors":[
         {
            "message":"Requests from this iOS client application <empty> are blocked.",
            "domain":"global",
            "reason":"forbidden"
         }
      ],
      "status":"PERMISSION_DENIED"
   }
}
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reaching out, @romansorochak. Based on the related issue, as per engineer, reCAPTCHA not working when restricting the API key is an intended behavior since reCAPTCHA is a web-based flow and our web widget doesn't impersonate your iOS app. Have you tried to include the Firebase Management API in the list of allowed APIs as mentioned [here](https://firebase.google.com/docs/projects/api-keys#apply-restrictions)?
