### ISSUE TITLE
Firestore Memory Persistence outdated docs

### ISSUE THREAD

**Issue by mgrms** [firebase/firebase-ios-sdk#11286]
### Description

Hello,

Firestore documentation shows code example using `isPersistanceEnabled` property:

https://firebase.google.com/docs/firestore/manage-data/enable-offline?hl=en&authuser=0#configure_offline_persistence

This property has been deprecated in recent Firebase SDK versions and this code will show a warning in Xcode, but the docs has not been updated.

Could you please tell how to rewrite following code to disable persistance with latest SDK version?:

```
let settings = FirestoreSettings()
settings.isPersistenceEnabled = false
let db = Firestore.firestore()
db.settings = settings
```

Thank you.

### Firebase SDK Version

10.9

### Xcode Version

14.3

### Installation Method

CocoaPods

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

**Comment by cherylEnkidu** [comment]
Hi,

This block of code should be rewritten as
```swift
let settings = FirestoreSettings()
settings.cacheSettings = MemoryCacheSettings()
let db = Firestore.firestore()
db.settings = settings
```

And we are working on updating the documentation.

**Comment by mgrms** [comment]
Hello @cherylEnkidu ,

Thank you for your message.

Could you please tell if `settings.isPersistenceEnabled = false` and `settings.cacheSettings = MemoryCacheSettings()` do exactly the same internally? I'm asking because we wanna know whether we need to re-test the app after making this change. Or can we just replace this line and be sure that it will work just like as before?

**Comment by mgrms** [comment]
Hi @wu-hui @cherylEnkidu ,

I see that the docs has been updated now, but instead of `MemoryCacheSettings()`, which you suggested above, it uses `MemoryCacheSettings(garbageCollectorSettings: MemoryLRUGCSettings())`.

(https://firebase.google.com/docs/firestore/manage-data/enable-offline?hl=en&authuser=0#configure_offline_persistence)

Could you please tell what is the difference and what is the best option to use?

Thanks.

**Comment by wu-hui** [comment]
`MemoryCacheSettings()` uses a default GC strategy where documents are deleted from memory as soon as they are no longer used by any active queries. `MemoryLRUGCSettings()` overrides this behavior to use a LRU based gc, so documents will stay longer after they are not used, and when they are needed again SDK will have to re-fetch.

There are scenarios where either of these are useful, and it is hard to recommend a best option for all cases.
