### ISSUE TITLE
[FR]: Filter out exceptions from the SDK

### ISSUE THREAD

**Issue by vlazdra** [firebase/firebase-ios-sdk#11319]
### Description

At the moment there is no way of filtering issues that arise from the SDK specifically from Remote Config. So, because of that the SDK issues an exception that get's reported by Sentry.
Now the problem with that is that I can' control that and because of that more than 30k events are generated per month towards Sentry. Since it's a paid service, I will like to filter out some of those exceptions and not have them all reported to Sentry.

### API Proposal

Filter out exceptions that Remote Config SDK is throwing.

Note: This was first reported towards the Flutter SDK instead, but they have confirmed that they won't change anything unless the native SDK supports it.
Reference issue reported to Firebase Remote Config for Flutter: https://github.com/firebase/flutterfire/issues/10904

### Firebase Product(s)

Remote Config

**Comment by paulb777** [comment]
Please provide examples and details of the exceptions you're seeing.

**Comment by vlazdra** [comment]
Hey @paulb777 sure thing. You can check out the link I've added in the initial message that I have submitted to Flutter Fire repo thinking they might be able to help.

I have as well added a lot more context on the feature request I also made to the Android implementation as well, here: https://github.com/firebase/firebase-android-sdk/issues/5027

Let me know if you would need more explanation from what I already linked previously. 🙌

**Comment by paulb777** [comment]
Sorry I'm still not seeing it. The only exceptions the iOS Remote Config SDK throws are related to configuration and should only occur in development mode. They should never occur in a deployed app.

Do you see the issue with both iOS and Android apps? If so, we should follow up on the flutter issue to ask more specifically which exceptions are being mapped.

**Comment by vlazdra** [comment]
No worries, will try to add more context.

So the FlutterFire Remote Config SDK propagates the exceptions from the underlying native SDK to the Flutter app. And those exceptions are caught by Sentry because nothing is handling them.

Some of those exceptions are:
FirebaseException [firebase_remote_config/internal] A data connection is not currently allowed.
FirebaseException [firebase_remote_config/internal] cancelled
FirebaseException [firebase_remote_config/internal] Internal Error. Status code: 503
FirebaseException [firebase_remote_config/internal] internal remote config fetch error
FirebaseException [firebase_remote_config/internal] Failed to get installations token. A data connection is not currently allowed.

They are both happening on Android and iOS and as much as I could understand it's because of the native SDKs.
There is a possibility to overcome this but it's really tedious, explained here: https://github.com/firebase/firebase-android-sdk/issues/5027#issuecomment-1559066675

Regarding that statement that the iOS Remote Config SDK throws should not occur in production, is there a setting I need to turn on for that to happen or does it happen automatically?

**Comment by paulb777** [comment]
Thanks, based on your comment it looks like the Flutter SDK is converting errors logged by the iOS SDK to exceptions.

Based on that, I'll close this issue in favor of https://github.com/firebase/flutterfire/issues/10904.

Even if there is a requirement to change how the iOS SDK logs errors it should work in conjunction with the Flutter exception workflow.

**Comment by vlazdra** [comment]
Hey @paulb777 the Flutter team said they won't do anything and that it's up to the native SDKs to add/change things and the Flutter team would follow.
They also closed the ticket in question. So I'm confused as to what now?

**Comment by paulb777** [comment]
Hi @vlazdra I read https://github.com/firebase/flutterfire/issues/10904#issuecomment-1557437109 as the Flutter team does not think this feature is a priority because of how Flutter implements exceptions. I added a comment there. https://github.com/firebase/flutterfire/issues/10904#issuecomment-1562924095

cc: @russellwheatley
