### ISSUE TITLE
Application crashes when loading RemoteConfig due to SQLite error

### ISSUE THREAD

**Issue by MrCOBA** [firebase/firebase-ios-sdk#11315]
### Description

Our users regularly experience application crashes at SQLite level when loading remote config on SDK version 9.6.0.  It's worth noting that the crashes don't occur on the latest iOS versions, most crahses with versions: 15.4, 15.6, 15.7.

### Firebase SDK Version

9.6.0

### Xcode Version

14.2

### Installation Method

Zip

### Firebase Product(s)

AB Testing, Analytics, Remote Config

### Targeted Platforms

iOS

### Relevant Log Output

```shell
0   libsystem_kernel.dylib        	0x00000001bb0178f0 fsync + 8
1   libsqlite3.dylib              	0x00000001a3be1ff4 unixSync + 208 (sqlite3.c:40769)
2   libsqlite3.dylib              	0x00000001a3beb338 syncJournal + 576 (sqlite3.c:24809)
3   libsqlite3.dylib              	0x00000001a3be1a50 sqlite3PagerCommitPhaseOne + 1228 (sqlite3.c:66409)
4   libsqlite3.dylib              	0x00000001a3bcd524 sqlite3BtreeCommitPhaseOne + 168 (sqlite3.c:76444)
5   libsqlite3.dylib              	0x00000001a3b99318 sqlite3VdbeHalt + 2700 (sqlite3.c:88770)
6   libsqlite3.dylib              	0x00000001a3bc7230 sqlite3VdbeExec + 55644 (sqlite3.c:95180)
7   libsqlite3.dylib              	0x00000001a3bb88f8 sqlite3_step + 304 (sqlite3.c:92283)
8   KLFirebase                    	0x000000010160c924 -[RCNConfigDBManager insertMetadataTableWithValues:] + 1048
9   KLFirebase                    	0x000000010160c47c __70-[RCNConfigDBManager insertMetadataTableWithValues:completionHandler:]_block_invoke + 52
10  libdispatch.dylib             	0x0000000180403094 _dispatch_call_block_and_release + 24 (init.c:1517)
11  libdispatch.dylib             	0x0000000180404094 _dispatch_client_callout + 16 (object.m:560)
12  libdispatch.dylib             	0x00000001803aa73c _dispatch_lane_serial_drain$VARIANT$mp + 644 (inline_internal.h:2622)
13  libdispatch.dylib             	0x00000001803ab1f4 _dispatch_lane_invoke$VARIANT$mp + 408 (queue.c:3944)
14  libdispatch.dylib             	0x00000001803b4ec8 _dispatch_workloop_worker_thread + 632 (queue.c:6732)
15  libsystem_pthread.dylib       	0x00000001dbaace10 _pthread_wqthread + 284 (pthread.c:2599)
16  libsystem_pthread.dylib       	0x00000001dbaac93c start_wqthread + 8
```

**Comment by K1llMaven** [comment]
Hello, and thank you for helping me out with this. Ironically, I did use a later model apple device. I will try to have this resolved here shortly.

**Comment by K1llMaven** [comment]
I am actually using swift, but operating on the same hardware so I have not been able to get to the package manager

**Comment by rizafran** [comment]
Hi @MrCOBA, may I know if you're using sqlite in your code? It seems like your issue is related to #8147.

**Comment by paulb777** [comment]
Firebase expects to use the standard sqlite library provided with Apple releases and may not work correctly with other implementations.

**Comment by MrCOBA** [comment]
Okay, thanks, @paulb777. And just for the sake of interest, what is the reason for this behaviour? Is it because of the POSIX locking mechanism the [documentation](https://sqlite.org/howtocorrupt.html) talks about?

**Comment by MrCOBA** [comment]
Could the solution be to use the same version of SQLite (system version) in all frameworks?

**Comment by paulb777** [comment]
That's what I would expect. We haven't seen an issue with SQLite when only the system version is used.
