### ISSUE TITLE
Carthage Firebaser  ,Then  import Firebase, show "No such module 'Firebase"

### ISSUE THREAD

**Issue by Sato-Falisa** [firebase/firebase-ios-sdk#11354]
### Description

this is my cartfile

binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashlyticsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"

### Reproducing the issue

old project, version is "8.15.0"
xcode update. to 14.3  
and update Carthage version is 
those file need   import Firebas,
show “No such module 'Firebase”
![WechatIMG3](https://github.com/firebase/firebase-ios-sdk/assets/35557319/e78d7f65-72ed-4ce9-bfa7-5b8210e8a095)
I wonder if there is no file“Firebase.swift”. after upadting firebase-ios-sdk by carthage?
if  there is no  Firebase.swift, which file should replace of it？

### Firebase SDK Version

"10.10.0"

### Xcode Version

14.3

### Installation Method

Carthage

### Firebase Product(s)

Analytics, Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by Sato-Falisa** [comment]
I wonder if there is no file“Firebase.swift”. after upadting firebase-ios-sdk by carthage?

**Comment by paulb777** [comment]
Sorry about the trouble. The Firebase framework is deprecate and was removed from Carthage distributions in Firebase 9. Import the specific Firebase product needed instead. Do `import FirebaseCore`, `import FirebaseAnalytics`, etc.
