### ISSUE TITLE
GoogleAppMeasurementOnDeviceConversion has invalid Info.plist as for the binary framework

### ISSUE THREAD

**Issue by RomanTysiachnik** [firebase/firebase-ios-sdk#11355]
### Description

Hello,

I've recently mentioned that `GoogleAppMeasurementOnDeviceConversion.framework` is not embedded in my app while it had to be since it's a binary framework. After I embedded it with singing, I started getting the following error from `altool`:

> Invalid Bundle. The bundle **GoogleAppMeasurementOnDeviceConversion.framework** does not support the minimum OS Version specified in the Info.plist.

I've checked the Info.plist file, and it looks like the following:
```
<plist version="1.0">
<dict>
  <key>CFBundleExecutable</key>
  <string>GoogleAppMeasurementOnDeviceConversion</string>
  <key>CFBundleIdentifier</key>
  <string>com.firebase.Firebase-GoogleAppMeasurementOnDeviceConversion</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundleName</key>
  <string>GoogleAppMeasurementOnDeviceConversion</string>
  <key>CFBundlePackageType</key>
  <string>FMWK</string>
  <key>CFBundleVersion</key>
  <string>10.10.0</string>
  <key>DTSDKName</key>
  <string>iphonesimulator11.2</string>
</dict>
</plist>
```

while other binary frameworks must have the following keys as a minimum:

```
  <key>DTPlatformName</key>
  <string>iphoneos</string>
  ...
  <key>DTXcodeBuild</key>
  <string>14B47b</string>
  <key>MinimumOSVersion</key> # <---- missing key causing a signing issue
  <string>10.0</string>
  <key>UIDeviceFamily</key>
  <array>
    <integer>1</integer>
    <integer>2</integer>
  </array>
  <key>UIRequiredDeviceCapabilities</key>
  <array>
    <string>arm64</string>
  </array>
  ...
```

So my questions are:
- is it expected that  `GoogleAppMeasurementOnDeviceConversion` is a binary framework?
- should it even be embedded into the app?
- what could be the resolution for that issue?

### Firebase SDK Version

10.10

### Xcode Version

14.2

### Installation Method

Carthage

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

**Comment by htcgh** [comment]
Thanks for the report. `GoogleAppMeasurementOnDeviceConversion` is a static framework and should not be embedded. In Xcode's `General` tab under the `Frameworks, Libraries, and Embedded Content` section, it should be added as `Do Not Embed`.

**Comment by RomanTysiachnik** [comment]
Yeah, that makes sense. `Unix Executable File` kind of file confused me a little bit, but I can see that it has ar archive inside.
