### ISSUE TITLE
Why does the iOS Simulator crash with error 'QueryComparator needs to have a key ordering' while testing unit test case

### ISSUE THREAD

**Issue by nahimvegans** [firebase/firebase-ios-sdk#11364]
### Description

When I run application it runs smoothly without any crash or errors, but when I run my unit test case that time some time it runs successfully without any crash but some time it got crashed by saying "FIRESTORE INTERNAL ASSERTION FAILED: QueryComparator needs to have a key ordering"
Thanks
![Screenshot 2023-05-31 at 4 10 16 PM](https://github.com/firebase/firebase-ios-sdk/assets/127280017/9ea19955-d899-453f-8b34-3f3033da0858)

### Firebase SDK Version

8.15

### Xcode Version

14.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Thread 11: "FIRESTORE INTERNAL ASSERTION FAILED: QueryComparator needs to have a key ordering:
```

### If using Swift Package Manager, the project's Package.resolved

{
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk",
      "state" : {
        "revision" : "111d8d6ad1a1afd6c8e9561d26e55ab1e74fcb42",
        "version" : "8.15.0"
      }
    },

**Comment by tom-andersen** [comment]
@nahimvegans I think we need more information to help you.

Are you bypassing the public api of Firestore SDK by using internal functions as part of your test?

Are you able to provide a reproducible example?

Somehow your code triggers a situation considered impossible by SDK, and therefore the SDK fails the program.

**Comment by nahimvegans** [comment]
@tom-andersen I have updated firebase package to 10.10.0 and it fixed my crash issue.
Thanks.
