### ISSUE TITLE
Crash event: sqlite3MemInit

### ISSUE THREAD

**Issue by Tank-Coder14** [firebase/firebase-ios-sdk#11362]
### Description

We got a crash event in firebase console from user and we don't know how to reproduce it yet

<img width="1328" alt="image" src="https://github.com/firebase/firebase-ios-sdk/assets/67986915/a5fc7360-b6f9-4660-a286-05b174d8c2a6">
crash stack trace: 
[crash.txt](https://github.com/firebase/firebase-ios-sdk/files/11608049/crash.txt)

### Reproducing the issue

This is collected from users, we don't know how to reproduce it yet.

### Firebase SDK Version

10.5.0

### Xcode Version

14.0

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, Crashlytics, DynamicLinks

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

- Firebase/AnalyticsWithoutAdIdSupport (10.5.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics/WithoutAdIdSupport (~> 10.5.0)
  - Firebase/CoreOnly (10.5.0):
    - FirebaseCore (= 10.5.0)
  - Firebase/Crashlytics (10.5.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 10.5.0)
  - Firebase/DynamicLinks (10.5.0):
    - Firebase/CoreOnly
    - FirebaseDynamicLinks (~> 10.5.0)
  - FirebaseAnalytics/WithoutAdIdSupport (10.5.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleAppMeasurement/WithoutAdIdSupport (= 10.5.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - GoogleUtilities/Network (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseCore (10.5.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Logger (~> 7.8)
  - FirebaseCoreInternal (10.9.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseCrashlytics (10.5.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.8)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (~> 2.1)
  - FirebaseDynamicLinks (10.5.0):
    - FirebaseCore (~> 10.0)
  - FirebaseInstallations (10.9.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)

**Comment by rizafran** [comment]
Thanks for filing, @Tank-Coder14. First off, may I know if you're using your own sqlite in your code?

**Comment by Tank-Coder14** [comment]
> Thanks for filing, @Tank-Coder14. First off, may I know if you're using your own sqlite in your code?

We are using sqlite3, does that cause any problems?

**Comment by paulb777** [comment]
Firebase relies on the system sqlite3 library and it should be fine if an app doesn't override the system library with another implementation.

We've seen multiple issues where replacing sqlite3 causes problems for FirebaseAnalytics or FirebaseRemoteConfig. Searching the issues in this repo will show examples.
