### ISSUE TITLE
Crash event: APMParamDictionaryFromEventParam

### ISSUE THREAD

**Issue by Tank-Coder14** [firebase/firebase-ios-sdk#11363]
### Description

We got a crash event in firebase console from user and we don't know how to reproduce it yet

<img width="994" alt="image" src="https://github.com/firebase/firebase-ios-sdk/assets/67986915/7da7cdfb-2cdb-4e85-9a55-04b96301103d">

stack trace: 
[crash.txt](https://github.com/firebase/firebase-ios-sdk/files/11608035/crash.txt)

### Reproducing the issue

This is collected from users, we don't know how to reproduce it yet

### Firebase SDK Version

10.5.0

### Xcode Version

14.0

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, Crashlytics, DynamicLinks

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

- Firebase/AnalyticsWithoutAdIdSupport (10.5.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics/WithoutAdIdSupport (~> 10.5.0)
  - Firebase/CoreOnly (10.5.0):
    - FirebaseCore (= 10.5.0)
  - Firebase/Crashlytics (10.5.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 10.5.0)
  - Firebase/DynamicLinks (10.5.0):
    - Firebase/CoreOnly
    - FirebaseDynamicLinks (~> 10.5.0)
  - FirebaseAnalytics/WithoutAdIdSupport (10.5.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleAppMeasurement/WithoutAdIdSupport (= 10.5.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - GoogleUtilities/Network (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseCore (10.5.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Logger (~> 7.8)
  - FirebaseCoreInternal (10.9.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseCrashlytics (10.5.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.8)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (~> 2.1)
  - FirebaseDynamicLinks (10.5.0):
    - FirebaseCore (~> 10.0)
  - FirebaseInstallations (10.9.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)

**Comment by paulb777** [comment]
Same questions as #11362. This is likely another symptom related to a problem with sqlite3 usage
