### ISSUE TITLE
FirebaseCore/FIRLogger.h' file not found after adding the FirebaseInAppMessaging SDK 

### ISSUE THREAD

**Issue by jesphinpt** [firebase/firebase-ios-sdk#11385]
### Description

I am trying to add the FIAM to my project. After adding that i am getting the error as

'FirebaseCore/FIRLogger.h' file not found

My Podfile is below

  
 ```
 pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Messaging'
pod 'FirebaseInAppMessaging'
```

### Reproducing the issue

After adding pod 'FirebaseInAppMessaging' gettting the error

### Firebase SDK Version

10.7.0

### Xcode Version

14.2

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, Firestore, In-App Messaging, Messaging, Remote Config

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Pods/FirebaseInAppMessaging/Firebase/InAppMessaging/Flows/FIRIAMServerMsgFetchStorage.m:17:9: 'FirebaseCore/FIRLogger.h' file not found
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment]
Hi @jesphinpt, I believe the issue is with mixing pod names that have and don't have a `/` in them. Using the `Firebase/{PRODUCT_NAME}` is an older pattern. This older pattern is being mixed with the new pattern without the slash (`FirebaseInAppMessaging` as opposed to `Firebase/InAppMessaging`) I can recommend two options to try:

1. Change `pod 'FirebaseInAppMessaging'` → pod 'Firebase/InAppMessaging'
2. The Firebase pod is deprecated so a more "modern" Podfile setup would look like:
     ```ruby
     pod 'FirebaseRemoteConfig'
     pod 'FirebaseMessaging'
     pod 'FirebaseInAppMessaging'
     ```
     Note that the `Firebase`, `FirebaseCore`, and `/`s are removed. Personally, I would probably go with this option.

**Comment by jesphinpt** [comment]
If i try with the above facing the same error

**Comment by ncooke3** [comment]
> @ncooke3 If i change to pod 'FirebaseInAppMessaging' is it fine without beta?
> 
> * pod 'Firebase/Core'
> * pod 'Firebase/RemoteConfig'
> * pod 'Firebase/Crashlytics'
> * pod 'Firebase/Analytics'
> 
> * pod 'FirebaseCore'
> * pod 'FirebaseRemoteConfig'
> * pod 'FirebaseCrashlytics'
> * pod 'FirebaseAnalytics'
> 
> * pod 'Firebase'
> 
> * #pod 'Firebase'

I believe you need the beta. Is this what your Podfile looks like? (For example, it looks like you have `pod 'Firebase/Core'` and `pod 'FirebaseCore'`). Could you copy and paste the Firebase-specific contents?

**Comment by jesphinpt** [comment]
```
#import <FirebaseCore/FIRLogger.h>

#import "FIRCore+InAppMessaging.h"
#import "FIRIAMServerMsgFetchStorage.h"
@implementation FIRIAMServerMsgFetchStorage
- (NSString *)determineCacheFilePath {
  NSString *cachePath =
```

**Comment by jesphinpt** [comment]
I have only one set of Pods not all.

Note: I have m1 mac machine which has arm64 architecture

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'


use_frameworks!

target 'App' do

pod 'FirebaseRemoteConfig'
  pod 'FirebaseMessaging'
  pod 'FirebaseCore'
  pod 'FirebaseInAppMessaging'

end
```

**Comment by ncooke3** [comment]
Have you tried this:

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'


use_frameworks!

target 'App' do

pod 'FirebaseRemoteConfig'
  pod 'FirebaseMessaging'
  pod 'FirebaseCore'
  pod 'FirebaseInAppMessaging', "> 10.7-beta"

end
```

**Comment by jesphinpt** [comment]
@ncooke3 Yes tried it works. 

Is it good to push the app to Appstore with the beta version? Does it raise any other issues?

**Comment by ncooke3** [comment]
> I am facing `import firebase not found error`

So by using the non-slash form (`FirebaseRemoteConfig` rather than `Firebase/RemoteConfig`), you are no longer using the `Firebase.podspec` so that should explain the new error. To fix this error, try removing any `import Firebase` statements you have. If removing it gives you another error, try adding `import FirebaseCore`.

**Comment by ncooke3** [comment]
Hi @jesphinpt, were you able to address the `import Firebase` error using the suggestion from my above post?

**Comment by jesphinpt** [comment]
I have removed the Firebase and it failed with the firebasecore

**Comment by ncooke3** [comment]
Hi @jesphinpt –– could you please share a screenshot/paste of the exact error message?

**Comment by jesphinpt** [comment]
I am getting the error with my app.

**Comment by ncooke3** [comment]
Hi @jesphinpt, I think we will need a minimal reproducible example to progress with this.

**Comment by jesphinpt** [comment]
/Pods/FirebaseInAppMessaging/Firebase/InAppMessaging/Flows/FIRIAMServerMsgFetchStorage.m:17:9: 'FirebaseCore/FIRLogger.h' file not found

**Comment by jesphinpt** [comment]
The error is fixed for me. @ncooke3 Thanks for your inputs
