### ISSUE TITLE
[iOS 17][XCode 15] An attribute list cannot appear here 

### ISSUE THREAD

**Issue by Alex-Coetzee** [firebase/firebase-ios-sdk#11408]
### Description

Build Error to do with code 

`
// Public constant
ABSL_CONST_INIT extern "C" const int64_t kFIRFirestoreCacheSizeUnlimited =
    Settings::CacheSizeUnlimited;

`

### Firebase SDK Version

8.0.0

### Xcode Version

15 Beta 1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication, Crashlytics, Database, Firestore, Functions

### Targeted Platforms

iOS, macOS

### Relevant Log Output

```shell
An attribute list cannot appear here
```

**Comment by MehulSojitra16** [comment]
What's the resolution of this issue?

**Comment by Alex-Coetzee** [comment]
> What's the resolution of this issue?

It looks like they have changed this in newer builds already, I had at a build on version >= 10.0.0 and the issue is already resolved in newer versions

Update your package, be aware that there are many breaking changes if you are using any of the Beta libraries or the older Firestore.encoder

**Comment by bydevelopertr** [comment]
Hi,

I did "pod update" and it's fixed, keep in mind
