### ISSUE TITLE
Incorrect line for Swift runtime crash

### ISSUE THREAD

**Issue by ileitch** [firebase/firebase-ios-sdk#11402]
### Description

We're seeing Crashlytics report incorrect line numbers for some of our crashes, resulting in ambiguous crashes that also don't include `EXC_BREAKPOINT` diagnostic messages on the Keys tab.

Given the following crash stack in Crashlytics:
```
Crashed: com.apple.main-thread
0  MyApp                      0x148836c Channel.configure(with:) + 35 (Channel+Swift.swift:35)
...
```
Line number 35 is invalid because it corresponds to the closing brace of a function.

Using `atos` locally with the same dSYM upload to Crashlytics provides the correct line number, and also reveals the Swift runtime failure:
```
$ atos -o MyApp -arch arm64 --inlineFrames -offset 0x148836c
Swift runtime failure: Negative value is not representable (in MyApp) (<compiler-generated>:0)
specialized UnsignedInteger<>.init<A>(_:) (in MyApp) (<compiler-generated>:0)
Channel.configure(with:) (in MyApp) (Channel+Swift.swift:26)
```

Is there any reason why Crashlytics would report a different result than `atos` using the same dSYM?

### Firebase SDK Version

10.9.0

### Xcode Version

14.3.0

### Installation Method

CocoaPods

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @ileitch, it seems like your issue is related to #10174 which might be an issue with the backend side. With this, please file a ticket through our [Firebase Support](https://firebase.google.com/support) so that our Crashlytics engineers would be able to take a look at your project. I'll now be closing this ticket. Thanks.
