### ISSUE TITLE
MacOS App Sandboxing causing a crash as soon as Firebase instance is accessed

### ISSUE THREAD

**Issue by kamend** [firebase/firebase-ios-sdk#11411]
### Description

For some unknown reason, if we enable App Sandboxing (we have set Outgoing connections to enabled, File Read/Writing too) every time we try to access the Firebase default instance, the application crashes without any visible error message. 

We are using the Unity Firebase SDK: 10.7, 11.0, 11.1 and latest Unity version 2022.3.0f. We tried older Unity version too, same problem. We are using Firebase Realtime Database and Firebase Storage SDKs.

The moment we remove App Sandboxing, everything is working as expected. 

We need App Sandboxing to be able to distribute apps through Test Flight.

Anybody else having the same issue or any ideas for a solution?

### Reproducing the issue

1. Create an empty Unity project
2. Add Firebase Database SDK. 
3. Add your GoogleService-Info.plist to the project
4. Create a simple script that does just a very simple thing like:   FirebaseDatabase.DefaultInstance.SetPersistenceEnabled(false);
5. Build an XCode project for MacOS from Unity
6. Enable App Sandbox
7. Build and Run

### Firebase SDK Version

10.7, 11.0, 11.1

### Xcode Version

14.3

### Installation Method

N/A

### Firebase Product(s)

Authentication, Database, Storage

### Targeted Platforms

macOS

### Relevant Log Output

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Firebase Test 2 [10920]
Path:                  /Users/USER/*/Firebase Test 2.app/Contents/MacOS/Firebase Test 2
Identifier:            space.appear.desktop
Version:               0.1 (0)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-06-07 13:26:56.9617 +0300
OS Version:            macOS 13.3.1 (22E261)
Report Version:        12
Anonymous UUID:        0F17F8D8-9D90-BE0F-9324-2FDEE8304156

Sleep/Wake UUID:       9526B42A-4543-47BB-85B9-84E26D95EDBE

Time Awake Since Boot: 820000 seconds
Time Since Wake:       14357 seconds

System Integrity Protection: enabled

Crashed Thread:        0  tid_103  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Thread 0 Crashed:: tid_103 Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x1a7660724 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x1a7697c28 pthread_kill + 288
2   libsystem_c.dylib             	       0x1a75a5ae8 abort + 180
3   libsystem_c.dylib             	       0x1a75a4e44 __assert_rtn + 272
4   FirebaseCppApp-10_7_0.bundle  	       0x31eea03ac firebase::Semaphore::Semaphore(int) + 328
5   FirebaseCppApp-10_7_0.bundle  	       0x31ee9ef14 firebase::Semaphore::Semaphore(int) + 36
6   FirebaseCppApp-10_7_0.bundle  	       0x31ee9eda0 firebase::App::Create(firebase::AppOptions const&, char const*) + 168
7   FirebaseCppApp-10_7_0.bundle  	       0x31ee9ecec firebase::App::Create(firebase::AppOptions const&) + 36
8   FirebaseCppApp-10_7_0.bundle  	       0x31ee9ec90 firebase::App::Create() + 52
9   FirebaseCppApp-10_7_0.bundle  	       0x31ef0a64c firebase::AppCreate(firebase::AppOptions const*, char const*) + 88
10  FirebaseCppApp-10_7_0.bundle  	       0x31ef0a574 firebase::AppGetOrCreateInstance(firebase::AppOptions const*, char const*) + 140
11  FirebaseCppApp-10_7_0.bundle  	       0x31eefb0f0 firebase_App_CreateInternal__SWIG_0() + 20
12  FirebaseCppApp-10_7_0.bundle  	       0x31eefb0c0 Firebase_App_CSharp_FirebaseApp_CreateInternal__SWIG_0 + 20
13  ???                           	       0x12dc5a054 ???
14  ???                           	       0x12dc59e90 ???
15  ???                           	       0x12dc59e20 ???
16  ???                           	       0x12dc32158 ???
17  ???                           	       0x12dc31e04 ???
18  ???                           	       0x12dc2c894 ???
19  ???                           	       0x12dc2c4b0 ???
20  ???                           	       0x12dc2c370 ???
21  ???                           	       0x117776688 ???
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @kamend, based on your stack trace, it seems that your issue is related to Firebase Unity SDK. With this, please file a ticket instead on our [Unity repo](https://github.com/firebase/firebase-unity-sdk/issues). I'll now be closing this ticket.
