### ISSUE TITLE
[FR]: Add API to check if Sign in with Apple credential corresponds to an existing user in Firebase Auth

### ISSUE THREAD

**Issue by sergiocampama** [firebase/firebase-ios-sdk#11417]
### Description

Today, we have 2 buttons for users to either Sign In or Sign Up with Apple credentials. We'd like to check when Signing In if the user already exists before or if it's going to create a new user in Firebase. 

The use case is that we sometimes have users that created an account using the email sign in link, and when they get a new device, they open the app in their new phone and tap Sign in with Apple, which ends up creating a new, empty account. Confused, they contact support saying that their account was deleted, and then we have to do some forensics to find their actual account and let them know to log in with that. 

If we were able to check if an account exists based on an Apple credential before just signing in and creating an account, we could have some wording in the app to let them know that this account does not exist, and to try email sign in link instead.

### Firebase Product(s)

Authentication

**Comment by peterfriese** [comment]
Hi Sergio,

you can find out if a user's email address is already registered with any other authentication provider by calling [`fetchSignInMethodsForEmail`](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseAuth/Sources/Auth/FIRAuth.m#L671).

See [this SO answer](https://stackoverflow.com/a/45364973/281221).
