### ISSUE TITLE
File IO on Main Thread

### ISSUE THREAD

**Issue by jaykumarlaunchpadapps** [firebase/firebase-ios-sdk#11424]
### Description

UITextSelectionInteraction._handleMultiTapGesture

Transaction | UITextSelectionInteraction._handleMultiTapGestureView Full Event
Offending Span | file.read - KBLayouts_iPhone.dat

### Reproducing the issue

<img width="1674" alt="Screenshot 2023-06-12 at 11 32 57 AM" src="https://github.com/firebase/firebase-ios-sdk/assets/126231969/f93b72d6-b7e7-4569-a212-09733f3c98fa">

### Firebase SDK Version

10.10

### Xcode Version

14.3

### Installation Method

CocoaPods

### Firebase Product(s)

Authentication, Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @jaykumarlaunchpadapps, it seems that your crash is not related to Firebase. Could you provide a complete stack trace as well as the detailed steps in reproducing the issue? Thanks.
