### ISSUE TITLE
FIRDynamicLinkNetworking.m ungracefully throwing exceptions

### ISSUE THREAD

**Issue by demonar** [firebase/firebase-ios-sdk#11423]
### Description

when calling:

 [(BOOL)handleUniversalLink:(NSURL *)universalLinkURL
                 completion:(FIRDynamicLinkUniversalLinkHandler)completion](https://github.com/firebase/firebase-ios-sdk/blob/83357b6eec32f1a79a2d6fd0bffbb110aefe6f43/FirebaseDynamicLinks/Sources/FIRDynamicLinks.m#L490)

with a link that does not contain the api key, the internal calls to 

[(instancetype)initWithAPIKey:(NSString *)APIKey URLScheme:(NSString *)URLScheme](https://github.com/firebase/firebase-ios-sdk/blob/83357b6eec32f1a79a2d6fd0bffbb110aefe6f43/FirebaseDynamicLinks/Sources/FIRDynamicLinkNetworking.m#L89)

generate an exception, this exception cannot be catched as the calls are not marked as throwable

### Reproducing the issue

call [(BOOL)handleUniversalLink:(NSURL *)universalLinkURL
                 completion:(FIRDynamicLinkUniversalLinkHandler)completion](https://github.com/firebase/firebase-ios-sdk/blob/83357b6eec32f1a79a2d6fd0bffbb110aefe6f43/FirebaseDynamicLinks/Sources/FIRDynamicLinks.m#L490)
 with a link that does not contain the api key

### Firebase SDK Version

10.10.0

### Xcode Version

14.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

DynamicLinks

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
The Firebase Dynamic Links service will be shutdown on August 25, 2025.  In the meantime, only critical or security issues will be fixed in the SDK.

More at https://firebase.google.com/support/dynamic-links-faq
