### ISSUE TITLE
Firebase Analytics error - "+[FBLPromise onQueue:do:]: unrecognized selector sent to class"

### ISSUE THREAD

**Issue by 1amageek** [firebase/firebase-ios-sdk#11451]
### Description

Firebase Analytics on iOS SDK version 10.11.0 is causing the application to crash with the error message: "+[FBLPromise onQueue:do:]: unrecognized selector sent to class 0x12bc61a78 (NSInvalidArgumentException)"

The issue occurs in the following Swift code:
```swift
import XCTest
import FirebaseCore
import FirebaseAnalytics

struct A {
    func a() {
        _ = Analytics.self
    }
}

final class FirebaseXCTests: XCTestCase {
    func testExample() throws {
        let filePath = Bundle.module.path(forResource: "GoogleService-Info", ofType: "plist")!
        let options = FirebaseOptions(contentsOfFile: filePath)!
        FirebaseApp.configure(options: options)
    }
}
```

Firebase Analytics has dependencies on the following frameworks: "FBLPromises", "FirebaseAnalytics", "FirebaseAnalyticsSwift", "FirebaseCore", "FirebaseCoreInternal", "FirebaseInstallations", "GoogleAppMeasurement", "GoogleAppMeasurementIdentitySupport", "GoogleUtilities", "nanopb". While these frameworks can be built successfully, the error occurs at runtime. Commenting out the line _ = Analytics.self resolves the crash, indicating that the issue is related to Firebase Analytics.

### Reproducing the issue

1. Integrate Firebase Analytics in an iOS project as an XCFramework.
1. Run the given Swift code on iOS SDK version 10.11.0
1. The application crashes with an NSInvalidArgumentException, indicating that a certain class doesn't recognize the +[FBLPromise onQueue:do:] selector

use: https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks

```swift
import PackageDescription

let package = Package(
    name: "MyLibrary",
    platforms: [.iOS(.v11)],
    products: [
        .library(name: "MyLibrary", targets: ["MyLibraryTarget"])
    ],
    dependencies: [
        .package(
            url: "https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks.git",
            .exact("10.11.0")
        ),
    ],
    targets: [
        .target(
            name: "MyLibraryTarget",
            dependencies: [
                .product(name: "FirebaseAnalytics", package: "firebase-ios-sdk-xcframeworks")
            ]
        )
        .testTarget(
            name: "FirebaseXCTests",
            dependencies: [
                .product(name: "FirebaseAnalytics", package: "firebase-ios-sdk-xcframeworks")
            ],
            resources: [
                .copy("GoogleService-Info.plist")
            ]
        )
    ]
)
```

```swift
import XCTest
import FirebaseCore
import FirebaseAnalytics

struct A {

    func a() {
       _ = Analytics.self
    }
}


final class FirebaseXCTests: XCTestCase {
    func testExample() throws {
        let filePath = Bundle.module.path(forResource: "GoogleService-Info", ofType: "plist")!
        let options = FirebaseOptions(contentsOfFile: filePath)!
        FirebaseApp.configure(options: options)
    }
}

```

### Firebase SDK Version

10.11.0

### Xcode Version

14.3.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
FirebaseXC/Tests/FirebaseXCTests/FirebaseXCTests.swift:21 testExample(): +[FBLPromise onQueue:do:]: unrecognized selector sent to class 0x12c4eda78 (NSInvalidArgumentException)
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by 1amageek** [comment]
It seems there is an issue with the xcframework.

<img width="356" alt="スクリーンショット 2023-06-17 13 14 34" src="https://github.com/firebase/firebase-ios-sdk/assets/11146538/681b6750-7d45-46c3-ab01-973a57985f76">
<img width="593" alt="スクリーンショット 2023-06-17 13 14 17" src="https://github.com/firebase/firebase-ios-sdk/assets/11146538/d5a2c065-f33a-4196-bac4-3bb5de884555">

**Comment by paulb777** [comment]
Thanks for the report.  Here are a few initial questions: 

- is `-Objc` added to the Other Linker Flags Settings option as documented in https://github.com/firebase/firebase-ios-sdk/blob/master/SwiftPackageManager.md?
- Did this work with a previous version of Firebase?
- If so, was it also a different version of Xcode?
