### ISSUE TITLE
SDK failed to compile, Undefined symbol: _OBJC_CLASS_$_FIRSessionsDependencies

### ISSUE THREAD

**Issue by mtucaliuc-ppb** [firebase/firebase-ios-sdk#11466]
### Description

I was trying to update Firebase from 8.x.x -> 10.x.x using carthage and I've got this error:
**`Undefined symbol: _OBJC_CLASS_$_FIRSessionsDependencies`**

I noticed from the release notes from 10.6.0 version that a new dependency to Firebase sessions was added, so I added FirebaseSession.xcframework from _Carthage/Build/_ to my project. But after that, I got several more errors:
<img width="681" alt="image" src="https://github.com/firebase/firebase-ios-sdk/assets/130378284/f02100c0-1b4d-4816-aeb5-9a4a3bbd5240">

These are the frameworks we are using:
<img width="495" alt="image" src="https://github.com/firebase/firebase-ios-sdk/assets/130378284/7e6a8c00-920c-4132-9583-aeba101a1658">

Here is Cartfile
![image](https://github.com/firebase/firebase-ios-sdk/assets/130378284/85550ef9-fb76-47e8-9385-6ee59a162326)

We are using 10.5.0 for now. Using this version the project compiles without any errors.

### Firebase SDK Version

10.6.0

### Xcode Version

14.2

### Installation Method

Carthage

### Firebase Product(s)

- FirebaseAnalyticsBinary
- FirebasePerformanceBinary
- FirebaseCrashlyticsBinary

### Targeted Platforms

iOS

**Comment by paulb777** [comment]
Everything from the Carthage/Build install needs to be added, including `PromisesSwift.xcframework`.
