### ISSUE TITLE
[FR]: visionOS platform support

### ISSUE THREAD

**Issue by Dmitry-rman** [firebase/firebase-ios-sdk#11467]
### Description

Please update all Swift packages to support the visionOS (xrOS) platform. Currently, there is an error when attempting to use them for developing Apple's spatial computing apps.

### Firebase Product(s)

AB Testing, Analytics, App Check, App Distribution, Authentication, Crashlytics, Database, DynamicLinks, Firestore, Functions, In-App Messaging, Installations, ML Model Downloader, Messaging, Performance, Remote Config, Storage

**Comment by paulb777** [comment]
We plan to address most, but maybe not all, of the VisionOS build issues for the 10.12.0 release, due out the week of July 11th.

**Comment by aryan1107** [comment]
> We plan to address most, but maybe not all, of the VisionOS build issues for the 10.12.0 release, due out the week of July 11th.

Thank you so much

**Comment by borglabdetroit** [comment]
Thank you!

**Comment by aryan1107** [comment]
Hi I am using 10.12.0 I think it still doesn't support visionOS

I get error while building for visionOS no library for this platform was found.
<img width="497" alt="Screenshot 2023-07-11 at 7 52 25 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/31214277/f32dfd30-f87c-4d92-b287-6b03e699e75b">

**Comment by paulb777** [comment]
We don't yet have binary support for visionOS. See the [release note instructions](https://firebase.google.com/support/release-notes/ios) for doing a source build: 

_Developers using Firestore on visionOS must use a source Firestore distribution rather than the default binary distribution. To do this, quit Xcode and open the desired project from the command line with the FIREBASE_SOURCE_FIRESTORE environment variable:_
`open --env FIREBASE_SOURCE_FIRESTORE /path/to/project.xcodeproj`
_To go back to using the binary distribution of Firestore, quit Xcode and open Xcode like normal, without the environment variable._

**Comment by aryan1107** [comment]
@paulb777 Thank you so much will try... really helpful!

**Comment by paulb777** [comment]
Going to close this here. Initial visionOS build support was released in 10.12.0 for all products except Crashlytics and that is merged for 10.13.0.

If you see other problems, please open a specific issue about it.

**Comment by matsutakk** [comment]
> Hi I am using 10.12.0 I think it still doesn't support visionOS
> 
> I get error while building for visionOS no library for this platform was found. <img alt="Screenshot 2023-07-11 at 7 52 25 PM" width="497" src="https://user-images.githubusercontent.com/31214277/252819315-f32dfd30-f87c-4d92-b287-6b03e699e75b.png">

I also get the error using 10.12.0. Does anyone know solutions?

**Comment by ncooke3** [comment]
@matsutakk, please see Paul's answer above: https://github.com/firebase/firebase-ios-sdk/issues/11467#issuecomment-1631676289

**Comment by Takuzen** [comment]
Having the same issue with @matsutakk so did the solution suggested at [#11467](https://github.com/firebase/firebase-ios-sdk/issues/11467#issuecomment-1631676289) but still one following error left.

`application:openURL:sourceApplication:annotation:' is unavailable: not available on xrOS`

@

```
/path/to/Library/Developer/Xcode/DerivedData/[project-name]-dnuyzorbjxdworgdlqwqucnkzczd/SourcePackages/checkouts/GoogleUtilities/GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
```
