### ISSUE TITLE
[Analytics] Missing License files

### ISSUE THREAD

**Issue by jheidschwarz** [firebase/firebase-ios-sdk#11468]
### Description

When installing Firebase via CocoaPods, the LICENSE file is missing for FirebaseAnalytics and GoogleAppMeasurement

### Reproducing the issue

![Screenshot 2023-06-23 at 10 11 24](https://github.com/firebase/firebase-ios-sdk/assets/76212527/b57e8cce-80b1-4ded-bb26-f981231a893d)

### Firebase SDK Version

10.11

### Xcode Version

14.3

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
For CocoaPods the license is specified in the podspec. For example, see https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseAnalytics.podspec#L12.  FirebaseAnalytics is different from FirebaseCore because it is a binary distribution instead of a source distribution.
