### ISSUE TITLE
Cycle inside error with Xcode 15 beta2

### ISSUE THREAD

**Issue by bestwnh** [firebase/firebase-ios-sdk#11471]
### Description

When I use Xcode 15 beta1 and beta2 to build my product, Xcode show up an error message:
```

Showing All Messages
Cycle inside SaleAppDev; building could produce unreliable results.
Cycle details:
→ Target 'SaleAppDev': ExtractAppIntentsMetadata
○ That command depends on command in Target 'SaleAppDev': script phase “Run Firebase Crashlytics Framework”
○ Target 'SaleAppDev' has a command with output '/Users/galvin/Library/Developer/Xcode/DerivedData/SaleApp-bflooukvzshbnyftcyfhikcrvfzk/Build/Products/Debug-iphonesimulator/SaleAppDev.app.dSYM'
○ Target 'SaleAppDev' has process command with output '/Users/galvin/Library/Developer/Xcode/DerivedData/SaleApp-bflooukvzshbnyftcyfhikcrvfzk/Build/Products/Debug-iphonesimulator/SaleAppDev.app/Info.plist'
○ Target 'SaleAppDev' has copy command from '/Users/galvin/Library/Developer/Xcode/DerivedData/SaleApp-bflooukvzshbnyftcyfhikcrvfzk/SourcePackages/artifacts/aws-sdk-ios-spm/AWSCore/AWSCore.xcframework/ios-arm64_i386_x86_64-simulator/AWSCore.framework' to '/Users/galvin/Library/Developer/Xcode/DerivedData/SaleApp-bflooukvzshbnyftcyfhikcrvfzk/Build/Products/Debug-iphonesimulator/SaleAppDev.app/Frameworks/AWSCore.framework'


Raw dependency cycle trace:

target:  ->

node: <all> ->

command: <all> ->

node: /Users/galvin/Library/Developer/Xcode/DerivedData/SaleApp-bflooukvzshbnyftcyfhikcrvfzk/Build/Intermediates.noindex/SaleApp.build/Debug-iphonesimulator/SaleAppDev.build/Objects-normal/arm64/ExtractedAppShortcutsMetadata.stringsdata ->

command: P0:target-SaleAppDev-9158ce05fb5c3595d8f47cfea6cad708268edd9a57a401552e80349710d5b9ad-:Debug:ExtractAppIntentsMetadata ->

node: <target-SaleAppDev-9158ce05fb5c3595d8f47cfea6cad708268edd9a57a401552e80349710d5b9ad--package-copy-files-phase> ->

command: P0:::Gate target-SaleAppDev-9158ce05fb5c3595d8f47cfea6cad708268edd9a57a401552e80349710d5b9ad--package-copy-files-phase ->

CYCLE POINT ->

node: <target-SaleAppDev-9158ce05fb5c3595d8f47cfea6cad708268edd9a57a401552e80349710d5b9ad--fused-phase3-copy-files> ->

command: P0:::Gate target-SaleAppDev-9158ce05fb5c3595d8f47cfea6cad708268edd9a57a401552e80349710d5b9ad--fused-phase3-copy-files ->

node: <target-SaleAppDev-9158ce05fb5c3595d8f47cfea6cad708268edd9a57a401552e80349710d5b9ad--fused-phase2-run-firebase-crashlytics-framework> ->

command: P0:::Gate target-SaleAppDev-9158ce05fb5c3595d8f47cfea6cad708268edd9a57a401552e80349710d5b9ad--fused-phase2-run-firebase-crashlytics-framework ->

node: <execute-shell-script-9158ce05fb5c3595d8f47cfea6cad70818949a790f5e1b8e3c3cfd1c5335f867-target-SaleAppDev-9158ce05fb5c3595d8f47cfea6cad708268edd9a57a401552e80349710d5b9ad-> ->

command: P2:target-SaleAppDev-9158ce05fb5c3595d8f47cfea6cad708268edd9a57a401552e80349710d5b9ad-:Debug:PhaseScriptExecution Run Firebase Crashlytics Framework /Users/galvin/Library/Developer/Xcode/DerivedData/SaleApp-bflooukvzshbnyftcyfhikcrvfzk/Build/Intermediates.noindex/SaleApp.build/Debug-iphonesimulator/SaleAppDev.build/Script-3AE1F9A71AA6D7E600F7C8E5.sh ->

node: /Users/galvin/Library/Developer/Xcode/DerivedData/SaleApp-bflooukvzshbnyftcyfhikcrvfzk/Build/Products/Debug-iphonesimulator/SaleAppDev.app.dSYM/Contents/Resources/DWARF/SaleAppDev ->

command: P0:target-SaleAppDev-9158ce05fb5c3595d8f47cfea6cad708268edd9a57a401552e80349710d5b9ad-:Debug:GenerateDSYMFile /Users/galvin/Library/Developer/Xcode/DerivedData/SaleApp-bflooukvzshbnyftcyfhikcrvfzk/Build/Products/Debug-iphonesimulator/SaleAppDev.app.dSYM /Users/galvin/Library/Developer/Xcode/DerivedData/SaleApp-bflooukvzshbnyftcyfhikcrvfzk/Build/Products/Debug-iphonesimulator/SaleAppDev.app/SaleAppDev ->

node: /Users/galvin/Library/Developer/Xcode/DerivedData/SaleApp-bflooukvzshbnyftcyfhikcrvfzk/Build/Products/Debug-iphonesimulator/SaleAppDev.app/Info.plist ->

command: P0:target-SaleAppDev-9158ce05fb5c3595d8f47cfea6cad708268edd9a57a401552e80349710d5b9ad-:Debug:ProcessInfoPlistFile /Users/galvin/Library/Developer/Xcode/DerivedData/SaleApp-bflooukvzshbnyftcyfhikcrvfzk/Build/Products/Debug-iphonesimulator/SaleAppDev.app/Info.plist /*project path*/SaleAppDev-Info.plist ->

node: /Users/galvin/Library/Developer/Xcode/DerivedData/SaleApp-bflooukvzshbnyftcyfhikcrvfzk/Build/Products/Debug-iphonesimulator/SaleAppDev.app/Frameworks/AWSCore.framework ->

command: P0:target-SaleAppDev-9158ce05fb5c3595d8f47cfea6cad708268edd9a57a401552e80349710d5b9ad-:Debug:Copy /Users/galvin/Library/Developer/Xcode/DerivedData/SaleApp-bflooukvzshbnyftcyfhikcrvfzk/Build/Products/Debug-iphonesimulator/SaleAppDev.app/Frameworks/AWSCore.framework /Users/galvin/Library/Developer/Xcode/DerivedData/SaleApp-bflooukvzshbnyftcyfhikcrvfzk/SourcePackages/artifacts/aws-sdk-ios-spm/AWSCore/AWSCore.xcframework/ios-arm64_i386_x86_64-simulator/AWSCore.framework ->

node: <target-SaleAppDev-9158ce05fb5c3595d8f47cfea6cad708268edd9a57a401552e80349710d5b9ad--fused-phase3-copy-files>


```

This error only show up in some specific situations. My app contains some SPM libraries:
a. firebase (https://github.com/firebase/firebase-ios-sdk, 10.10.0, with Crashlytics upload script)
b. aws ios sdk (https://github.com/aws-amplify/aws-sdk-ios-spm, 2.33.0)
c. cardio (https://github.com/verygoodsecurity/CardIOSDK-iOS.git, 5.5.7)
d. some other library, not important 

For Xcode 14:
a+b+c+d: build success ✅

For Xcode 15 beta1 and beta2:
a+b+c+d: build failed, cycle inside error ❌
a+c+d: build failed, cycle inside error ❌
a+b+d: build failed, cycle inside error ❌
a+d: build success ✅
b+c+d: build success ✅
a+b+c+d, but remove the `${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}` for Crashlytics upload script in `Input Files`: build success ✅

Looks like there is a conflict with the input files of Crashlytics upload script and some xcframework library.

### Firebase SDK Version

10.10.0

### Xcode Version

15.0 beta.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

{
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk",
      "state" : {
        "revision" : "5034479ca0c4f32f299677fb0ba1fe4d3e3e20b4",
        "version" : "10.10.0"
      }
    }

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by samedson** [comment]
@bestwnh thanks for reaching out. This is interesting - `upload-symbols` / `run` should only be leaf nodes in the build process. Nothing else should depend on them, which makes it curious that it's causing a cycle.

 - Could you post your Input Files and Run Script?
 - Do you know if the AWS or Cardio SDKs have any Build Phases or extra build steps?

**Comment by bestwnh** [comment]
@samedson Thank you for helping.
Input Files:
`${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}`
`$(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)`

Run Script:
```
if [ "${PLATFORM_NAME}" != "iphonesimulator" ]; then
    "${BUILD_DIR%Build/*}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run"
fi
```

AWS is quiet complex, I'm not sure. But Cardio is so simple, just a xcframework, that is.
<img width="1096" alt="image" src="https://github.com/firebase/firebase-ios-sdk/assets/1201345/f29f03f0-d845-4a14-adec-d426f9688806">
And in xcode project target, the Crashlytics upload script is the only run script I added.


BTW, the [document](https://firebase.google.com/docs/crashlytics/get-started?platform=ios) mentions this input file is for **_process dSYMs for large apps more quickly_**, so before this issue fix, can I just remove this input file? Does it effect dSYMs upload?
<img width="741" alt="image" src="https://github.com/firebase/firebase-ios-sdk/assets/1201345/632454c3-d7a7-42cc-921a-090f5787d8b1">

**Comment by themiswang** [comment]
Hey @bestwnh 

Could you provide me the full build logs (ideally both succeeded and failed ones so I can compare) and your [build phases](https://developer.apple.com/documentation/xcode/customizing-the-build-phases-of-a-target) setup for me to take a deeper look?

Also Can you try if a+b, a+c+d and let me know the behaviour? I suspect the problem comes from when you use Firebase and AWS SDK together.

From the [Xcode trouble shooting guide](https://help.apple.com/xcode/mac/current/#/dev621201fb0), your error message states that there is a dependency cycle is between `ExtractAppIntentsMetadata` and `Crashlytics run script`.

But if you check the `Raw dependency cycle trace`, the cycle is actually start from node `target-SaleAppDev-9158ce05fb5c3595d8f47cfea6cad708268edd9a57a401552e80349710d5b9ad--fused-phase3-copy-files` which is something contributed by AWS sdk.

So there are a few questions:
- In your application build phases for `SaleAppDev`, do you have a package copy files phase? 
- If you do, Is this phase related to ASW SDK? 
- Does `Crashlytics run script` is the last item in your build phases?

**Comment by bestwnh** [comment]
@themiswang  I make a demo project to reproduce this issue. Then I found it's not the firebase library issue. But it is a issue related to `${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}` and some library like cardio or aws. 
Here is a very very simple demo. But not firebase library related anymore. So I still hope you can help to take a look, because Crashlytics still need that input files. I use cardio in this demo because it's much simpler than aws.
[FirebaseXcodeIssueDemo2.zip](https://github.com/firebase/firebase-ios-sdk/files/11929707/FirebaseXcodeIssueDemo2.zip)

And I also found out the issue is related to the dSYM file, because if I choose `DWARF` without the dSYM file output, it also build success.

**Comment by mhelenurm** [comment]
To add another voice to the choir: I'm also having the same issue for a work project. I'm seeing these exact same errors, and I have the firebase run scripts last (no other relevant external dependencies, or scripts during build); if I remove the Firebase's dependency on the DWARF dSYM, it builds fine (doesn't find a cycle). Doesn't seem directly related to firebase-ios-sdk, as @bestwnh was saying, but I'd hazard a guess that it impacts a lot of projects that depend on it. Wish there was an easy solution!

**Comment by bestwnh** [comment]
@mhelenurm I just also make a feedback by Feedback assistant. FB12519986. I will post here if any update.

**Comment by themiswang** [comment]
Hey @bestwnh, @mhelenurm,

Thank you for the feedback and following up. This is likely relate to xcode 15 beta. I have seen multiple similar issue reported in community:
- https://forums.swift.org/t/xcode-15-beta-cycle-inside-target-building-could-produce-unreliable-results/65906 
- https://developer.apple.com/forums/thread/731825
- https://developer.apple.com/forums/thread/731287 

The issue generally can be reproduced if you have a input file in run script from build output file as well as has a binary SPM package in your program. Indeed both AWS and cardIO are binary SPM. We will make a feedback to Apple as well. Meanwhile to unblock you from build, you can shorten the dSYM path to `${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF`.

**Comment by mhelenurm** [comment]
Thanks, the workaround worked perfectly! (tested on Xcode 15 beta 3) Does link-shortening this have any side effects?

**Comment by oguzhanvarsak** [comment]
@themiswang The workaround works. Same question as @mhelenurm , are there any side effects using shortened link?

**Comment by cameroncooke** [comment]
Just to chime in I'm also having the same issue, we use Firebase and AWS libraries via SPM, Xcode points to this being related to the Crashlytics build phase, but as others pointed out this might be a red herring.

**Comment by bestwnh** [comment]
Confirmed this issue fixed in Xcode 15 beta5. So it can be close now.
