### ISSUE TITLE
Installation via SPM Package Resolution Failed 

### ISSUE THREAD

**Issue by bayareahank** [firebase/firebase-ios-sdk#11504]
### Description

Installing firebase -ios-sdk via SPM failed to resolve, with error messages like this: 

Failed to resolve dependencies Dependencies could not not be resolved because no versions of 'googleappmeasurement' match the requirement 10.12.0 and 'firebase-ios-sdk' depends on 'googleappmeasurement' 10.12.0 

Interestingly, GoogleAppMeasurement updating itself looks fine: 
    'Updating from https://github.com/google/GoogleAppMeasurement.git'

The error message appears after 'promises'
    'Updating from https://github.com/google/promises.git' 

This still worked the last time I installed it via SPM on June 25. 

I believe it comes from a dependency version error of GoogleAppMeasurement. From its github page https://github.com/google/GoogleAppMeasurement/releases, GoogleAppMeasurement latest public release is 10.11.0, not 10.12.0. 

### Reproducing the issue

XCode --> File --> Add Package --> Firebase-ios-sdk, repeatable each time. 

### Firebase SDK Version

10.9

### Xcode Version

14.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, All

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for filing, @bayareahank. First off, could you share the `Package.resolved` snippet in the issue template in order to reproduce the issue?

**Comment by paulb777** [comment]
Firebase 10.12.0 is still in testing and isn't planned to release until the week of July 11th.

In the meantime, please use 10.11.0.

I'll close, but feel free to continue discussion here.

**Comment by bayareahank** [comment]
@rizafran Thanks for responding. This failed at SPM add package screen, before it even gets to Package.resolved phase. 

If it is as @paulb777 mentioned that 10.12.0 isn't planned released yet, that means somehow the main branch available to the public contains this setup before it is ready. This doesn't come from my setup. But I can wait till July 11th anyway.
