### ISSUE TITLE
will not compile in a kmm project

### ISSUE THREAD

**Issue by asiimwedismas** [firebase/firebase-ios-sdk#11505]
### Description

I have a kmm project in which I am pulling in a few firebase things using cocoapods like below: 

> cocoapods {
        summary = "Some description for the Shared Module"
        homepage = "Link to the Shared Module homepage"
        version = "1.0"
        ios.deploymentTarget = "11.0"
        framework {
            baseName = "my_firebase_sdk"
        }
        noPodspec()
        pod("FirebaseCore") {
            source = git("https://github.com/firebase/firebase-ios-sdk.git") {
                tag = "10.11.0"
            }
        }
        pod("FirebaseCrashlytics") {
            source = git("https://github.com/firebase/firebase-ios-sdk.git") {
                tag = "10.11.0"
            }
        }
        pod("FirebaseAuth") {
            source = git("https://github.com/firebase/firebase-ios-sdk.git") {
                tag = "10.11.0"
            }
        }
        pod("FirebaseFirestore") {
            source = git("https://github.com/firebase/firebase-ios-sdk.git") {
                tag = "10.11.0"
            }
        }
  }

the sync is all fine however the build fails with the following errors:

1. The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'FirebaseAppCheckInterop' from project 'Pods')
  note: Using global toolchain override 'Xcode Default'. (in target 'FirebaseAppCheckInterop' from project 'Pods')
2. The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'PromisesObjC' from project 'Pods')
  note: Using global toolchain override 'Xcode Default'. (in target 'PromisesObjC' from project 'Pods')
3. The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'GoogleUtilities' from project 'Pods')
  note: Using global toolchain override 'Xcode Default'. (in target 'GoogleUtilities' from project 'Pods')

This is for each of the firebase pods I pull in, my research has brought me to the following issue [https://github.com/CocoaPods/CocoaPods/issues/9884](url) but this won't work for me since this is in a module that is in the data layer and isn't directly exported to the ios side.

, 

### Firebase SDK Version

10.9.0 and also 10.11.0

### Xcode Version

14.3.1 (14E300c)

### Installation Method

CocoaPods

### Firebase Product(s)

All

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
Those are warnings from Xcode 14.3 related to some of Firebase's dependencies continuing to support older Xcode versions. If they are causing build failures, it may be related to the KMM integration and the issue should be reported in its support channels.
