### ISSUE TITLE
Upgrade to 10.7 Unit Test are failing with 'FIRAppNotConfigured' error even though App has FirebaseApp.configure call.

### ISSUE THREAD

**Issue by sreexamus** [firebase/firebase-ios-sdk#11521]
### Description

Upgraded App to 10.11 for remote config realtime update feature. it works fine without any issues. when i run the Unit test cases its failing with below error. I tried with 10.7, it also fails with below error for Unit tests. When i revert back the version to 8.14.0 then the test cases are working fine but i still see below exception in the logs. Is it mandatory to initialize the Firebase App for Unit tests for new releases?

"FIRAppNotConfigured: The default `FirebaseApp` instance must be configured before the default Remote Config instance can be initialized. One way to ensure this is to call `FirebaseApp.configure()` in the App Delegate's `application(_:didFinishLaunchingWithOptions:)` or the `@main` struct's initializer in SwiftUI.

### Firebase SDK Version

10.11

### Xcode Version

14.3.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
F/Source/Features/AccountModule/AccountModuleCoordinatorTests.swift:42: error: -[XXXTests.AccountModuleCoordinatorTests test_getOrder_pickupView_component] : XCTAssertNotNil failed: throwing "FIRAppNotConfigured: The default `FirebaseApp` instance must be configured before the default Remote Config instance can be initialized. One way to ensure this is to call `FirebaseApp.configure()` in the App Delegate's
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
This was an intentional change introduced in Firebase 9.0.0. Details in #9551.

Yes. It is mandatory to call `FirebaseApp.configure()`.

I'll close but feel free to continue the discussion.

**Comment by sreexamus** [comment]
@paulb777  we are using a dummy AppDelegate instead of acutal AppDelegate in order to avoid all the initial loading for the Unit Tests. I tried doing the FirebaseApp.configure() in the dummy AppDelegate didFinishLaunch then App is crashing with error '[FBLPromise firebaseInstallationID]: unrecognized selector sent to instance'. Attached screenshot for it. Want to know how to configure firebase for UnitTests?
![WhatsApp Image 2023-07-11 at 12 50 58 PM](https://github.com/firebase/firebase-ios-sdk/assets/19535708/d3394a31-7d09-4a1b-980b-17c61ee85215)

**Comment by paulb777** [comment]
The crash looks like `-ObjC` needs to be added to the Other Linker Flags Build Setting.

**Comment by paulb777** [comment]
@sreexamus Are you able to share a reproducible example via zip or GitHub?
