### ISSUE TITLE
Runtime warning in GULNetworkURLSession when running on iOS17 beta built with Xcode15 beta4

### ISSUE THREAD

**Issue by nevil** [firebase/firebase-ios-sdk#11536]
### Description

The warning:
```
The request of a upload task should not contain a body or a body stream, use `upload(for:fromFile:)`, `upload(for:from:)`, or supply the body stream through the `urlSession(_:needNewBodyStreamForTask:)` delegate method.
```

The code:
```objective-c
  } else {
    // If we cannot write to file, just send it in the foreground.
    _sessionConfig = [NSURLSessionConfiguration defaultSessionConfiguration];
    [self populateSessionConfig:_sessionConfig withRequest:request];
    session = [NSURLSession sessionWithConfiguration:_sessionConfig
                                            delegate:self
                                       delegateQueue:[NSOperationQueue mainQueue]];
--->    postRequestTask = [session uploadTaskWithRequest:request fromData:request.HTTPBody];
  }
```

As seen, the request's HTTPBody has data as it is what is being used to pass to `fromData:`.

### Reproducing the issue

Just run an app and watch the runtime warnings in Xcode.

### Firebase SDK Version

10.9.0

### Xcode Version

15 Beta4

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, Crashlytics, Messaging

### Targeted Platforms

iOS

### Relevant Log Output

```shell
The request of a upload task should not contain a body or a body stream, use `upload(for:fromFile:)`, `upload(for:from:)`, or supply the body stream through the `urlSession(_:needNewBodyStreamForTask:)` delegate method.
```
```


### If using Swift Package Manager, the project's Package.resolved

_No response_

### If using CocoaPods, the project's Podfile.lock

_No response_

**Comment by nevil** [comment]
<img width="1386" alt="image" src="https://github.com/firebase/firebase-ios-sdk/assets/36905/4b175526-c160-476c-87ca-2e91bea7ca07">

**Comment by crousselle** [comment]
Seeing this as well!

**Comment by ncooke3** [comment]
Hi everyone, the corresponding fix has been merged into the offending dependency. I'll update this thread when it is released. Thanks!

**Comment by ncooke3** [comment]
Update – the fix has now been released. It can be applied by running `pod update GoogleUtilities` for CocoaPods, or selecting `File -> Packages -> Update to Latest Package Versions` within Xcode for SwiftPM users.
