### ISSUE TITLE
FCM refreshes messaging token multiple times per day on iOS

### ISSUE THREAD

**Issue by thaolai** [firebase/firebase-ios-sdk#11535]
### Description

We have integrated FCM + SNS in our app it works. The app receives the updated fcm tokens using didReceiveRegistrationToken. However, we see the fcm token refreshes multiple times per day for part of our users. It seems start from late March/ April. 
Token refresh on update app or even just restart app. Sometimes it returns 2 different tokens at the same time on app starts. 

### Reproducing the issue

Update new version of app and check the token received in didReceiveRegistrationToken. Sometimes it happens when I just restarts the app.  

### Firebase SDK Version

10.0.0

### Xcode Version

14.3.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Messaging

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reporting this, @thaolai. I tried to reproduce the issue but I'm unable to get the same behavior. To investigate what's causing the issue in the backend side, you may try filing a ticket through our [support channel](https://firebase.google.com/support).
