### ISSUE TITLE
"Invalid manifest" when installing via Xcode 15.0 beta and SPM

### ISSUE THREAD

**Issue by adamvnovak** [firebase/firebase-ios-sdk#11556]
### Description

I can install other packages without a problem, but for some reason it's only firebase-ios-sdk that's giving me this invalid manifest issue. I've tried [resetting package caches and clearing derived data](https://stackoverflow.com/questions/58816416/xcode-swift-package-manager-error-the-repository-could-not-be-found) and that didn't work.

Here's the error message:

Invalid manifest (compiled with: ["/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc", "-vfsoverlay", "/var/folders/cx/3mbml2912n5c6qvxvsmn8xnc0000gn/T/TemporaryDirectory.Mj1VfT/vfs.yaml", "-L", "/Applications/Xcode-beta.app/Contents/PlugIns/IDESwiftPackageCore.framework/Versions/A/Frameworks/SwiftPM.framework/SharedSupport/ManifestAPI", "-lPackageDescription", "-Xlinker", "-rpath", "-Xlinker", "/Applications/Xcode-beta.app/Contents/PlugIns/IDESwiftPackageCore.framework/Versions/A/Frameworks/SwiftPM.framework/SharedSupport/ManifestAPI", "-target", "arm64-apple-macos13.0", "-sdk", "/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk", "-swift-version", "5", "-I", "/Applications/Xcode-beta.app/Contents/PlugIns/IDESwiftPackageCore.framework/Versions/A/Frameworks/SwiftPM.framework/SharedSupport/ManifestAPI", "-sdk", "/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk", "-package-description-version", "5.6.0", "-Xfrontend", "-serialize-diagnostics-path", "-Xfrontend", "/Users/adamvnovak/Library/Caches/org.swift.swiftpm/manifests/ManifestLoading/firebase-ios-sdk.dia", "/Package.swift", "-disallow-use-new-driver", "-o", "/var/folders/cx/3mbml2912n5c6qvxvsmn8xnc0000gn/T/TemporaryDirectory.zdDp1k/firebase-ios-sdk-manifest"])

In the [Xcode 15.0 beta notes 4](https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes), Apple says that "Macros are implemented in separate programs, which are executed by the Swift compiler. The Swift Package Manager’s manifest provides a new macro target type to describe macros." Could this be why?

### Reproducing the issue

Create new Xcode project with Xcode 15.0 beta.
Add Firebase packages via Swift Package Manager.

### Firebase SDK Version

10.12.0

### Xcode Version

15.0 beta

### Installation Method

Swift Package Manager

### Firebase Product(s)

All

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Invalid manifest (compiled with: ["/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc", "-vfsoverlay", "/var/folders/cx/3mbml2912n5c6qvxvsmn8xnc0000gn/T/TemporaryDirectory.Mj1VfT/vfs.yaml", "-L", "/Applications/Xcode-beta.app/Contents/PlugIns/IDESwiftPackageCore.framework/Versions/A/Frameworks/SwiftPM.framework/SharedSupport/ManifestAPI", "-lPackageDescription", "-Xlinker", "-rpath", "-Xlinker", "/Applications/Xcode-beta.app/Contents/PlugIns/IDESwiftPackageCore.framework/Versions/A/Frameworks/SwiftPM.framework/SharedSupport/ManifestAPI", "-target", "arm64-apple-macos13.0", "-sdk", "/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk", "-swift-version", "5", "-I", "/Applications/Xcode-beta.app/Contents/PlugIns/IDESwiftPackageCore.framework/Versions/A/Frameworks/SwiftPM.framework/SharedSupport/ManifestAPI", "-sdk", "/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk", "-package-description-version", "5.6.0", "-Xfrontend", "-serialize-diagnostics-path", "-Xfrontend", "/Users/adamvnovak/Library/Caches/org.swift.swiftpm/manifests/ManifestLoading/firebase-ios-sdk.dia", "/Package.swift", "-disallow-use-new-driver", "-o", "/var/folders/cx/3mbml2912n5c6qvxvsmn8xnc0000gn/T/TemporaryDirectory.zdDp1k/firebase-ios-sdk-manifest"])
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

{
  "pins" : [
    {
      "identity" : "abseil-cpp-swiftpm",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/abseil-cpp-SwiftPM.git",
      "state" : {
        "revision" : "583de9bd60f66b40e78d08599cc92036c2e7e4e1",
        "version" : "0.20220203.2"
      }
    },
    {
      "identity" : "boringssl-swiftpm",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/boringssl-SwiftPM.git",
      "state" : {
        "revision" : "dd3eda2b05a3f459fc3073695ad1b28659066eab",
        "version" : "0.9.1"
      }
    },
    {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk",
      "state" : {
        "revision" : "5c4893c55f9d6114e2bb7c691d7ffd81208ac713",
        "version" : "10.0.0"
      }
    },
    {
      "identity" : "googleappmeasurement",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleAppMeasurement.git",
      "state" : {
        "revision" : "e3dd02f390cae79a7073b46dfb0cb6b60c48401b",
        "version" : "10.0.0"
      }
    },
    {
      "identity" : "googledatatransport",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleDataTransport.git",
      "state" : {
        "revision" : "98a00258d4518b7521253a70b7f70bb76d2120fe",
        "version" : "9.2.4"
      }
    },
    {
      "identity" : "googleutilities",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleUtilities.git",
      "state" : {
        "revision" : "58d03d22beae762eaddbd30cb5a61af90d4b309f",
        "version" : "7.11.3"
      }
    },
    {
      "identity" : "grpc-ios",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/grpc/grpc-ios.git",
      "state" : {
        "revision" : "8440b914756e0d26d4f4d054a1c1581daedfc5b6",
        "version" : "1.44.3-grpc"
      }
    },
    {
      "identity" : "gtm-session-fetcher",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/gtm-session-fetcher.git",
      "state" : {
        "revision" : "5ccda3981422a84186387dbb763ba739178b529c",
        "version" : "2.3.0"
      }
    },
    {
      "identity" : "leveldb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/leveldb.git",
      "state" : {
        "revision" : "0706abcc6b0bd9cedfbb015ba840e4a780b5159b",
        "version" : "1.22.2"
      }
    },
    {
      "identity" : "nanopb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/nanopb.git",
      "state" : {
        "revision" : "819d0a2173aff699fb8c364b6fb906f7cdb1a692",
        "version" : "2.30909.0"
      }
    },
    {
      "identity" : "phonenumberkit",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/marmelroy/PhoneNumberKit",
      "state" : {
        "revision" : "9bc965a326df8d5115f0b7bb77f09c542b8ec417",
        "version" : "3.6.6"
      }
    },
    {
      "identity" : "promises",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/promises.git",
      "state" : {
        "revision" : "ec957ccddbcc710ccc64c9dcbd4c7006fcf8b73a",
        "version" : "2.2.0"
      }
    },
    {
      "identity" : "swift-protobuf",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-protobuf.git",
      "state" : {
        "revision" : "f25867a208f459d3c5a06935dceb9083b11cd539",
        "version" : "1.22.0"
      }
    },
    {
      "identity" : "swiftmessages",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/SwiftKickMobile/SwiftMessages",
      "state" : {
        "revision" : "b29dd21090b708aa0ae9ecbaf6e2d0487028dc3f",
        "version" : "9.0.6"
      }
    }
  ],
  "version" : 2
}


```

</details>

**Comment by paulb777** [comment]
`Swift Packages -> Update to latest Package Versions` might help.

Firebase is currently at 10.12.0 and the `Package.resolved` is showing 10.0.0

**Comment by adamvnovak** [comment]
Ah I should have mentioned—at that moment the version was 10.0.0 because I was experimenting with different versions, seeing if 10.12.0 was the problem.

The same problem occurs for me when I use "Up to Next Major Version" which refers to 10.12.0.

**Comment by paulb777** [comment]
Hmm, I'm not sure if this is it or not but Firebase requires at least Xcode 15 Beta 2. See https://firebase.google.com/support/release-notes/ios

**Comment by adamvnovak** [comment]
This was the solution. Thank you!
