### ISSUE TITLE
app_version field on the tvOS analytics

### ISSUE THREAD

**Issue by ANLopatin** [firebase/firebase-ios-sdk#11567]
### Description

app_version field should be passed automatically along with other default fields, but in some cases, this field comes empty

### Firebase SDK Version

10.12.0

### Xcode Version

14.3.1

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics

### Targeted Platforms

tvOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reporting this, @ANLopatin. Could you confirm if you're referring to the Analytics dashboard or the raw data? You may also share a screenshot of the issue for better understanding.
