### ISSUE TITLE
No such module 'Firebase'

### ISSUE THREAD

**Issue by JamieShaneRainbird** [firebase/firebase-ios-sdk#11589]
### Description

I'm on Xcode Beta 4; I have installed the Firebase dependencies on the packages (https://github.com/firebase/firebase-ios-sdk), yet I receive this error of "No such module 'Firebase'" when trying to import Firebase into my project. 

It shows up as typing but does not function and Xcode throws the error continuously.

### Firebase SDK Version

10.12

### Xcode Version

15.0 Beta 4

### Installation Method

Swift Package Manager

### Firebase Product(s)

All

### Targeted Platforms

All

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
One thing to try would be to import the specific Firebase products you need - like `import FirebaseMessaging` instead of `import Firebase`. If you're still stuck please update the issue with the `Package.resolved` file.
