### ISSUE TITLE
Cannot find type 'Firestore' in scope

### ISSUE THREAD

**Issue by jonnyholland** [firebase/firebase-ios-sdk#11593]
### Description

The project is a shared app (macOS, iOS, etc). I'm using the SPM (_up to next minor: 10.12.0_) and have imported Firestore & FirestoreSwift for the project, among others. When I build for macOS, there's no issues. When I move to target an iOS device, everything breaks. Perhaps I'm missing something but I've:
- imported the SPM and targeted the project.
- verified Firestore is imported. 
- reset package caches. 
- deleted derived data and then reset package caches.
- restarted Xcode. 
- tried various variations of the other steps.

*Note: I haven't been able to find `Package.swift` or `Package.resolved`*

<img width="348" alt="Screenshot 2023-07-24 at 1 26 59 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/26751945/76c3fbea-47ec-4b33-8a0d-4e7c338daf39">
<img width="1126" alt="Screenshot 2023-07-24 at 1 26 39 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/26751945/27a7e1dd-11c9-4920-99d7-d503960e2278">

### Reproducing the issue

- Open/start a shared project that targets multiple OSes and import Firebase SPM.
- Write code to get a database instance, such as: `let db = Firestore.firestore()`
- Target an iOS device.
- Notice the compiler warnings.

### Firebase SDK Version

10.12

### Xcode Version

14.3.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS, macOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
Does the file with the build error have `import FirebaseFirestore` in it?

**Comment by jonnyholland** [comment]
Yes. But I believe it's an Xcode issue because after doing another round of toggling SPM and resolving package versions, it's now building without errors 🤷🏼‍♂️
