### ISSUE TITLE
[FR]: FirebaseInstallations Carthage support

### ISSUE THREAD

**Issue by b-onc** [firebase/firebase-ios-sdk#11612]
### Description

Currently, experimental Carthage support is not including Firebase Installations SDK. The Carthage.md file doesn't list a binary path for Installations SDK, and `FirebaseInstallationsBinary.json` path fails with 404.

Are there any plans to support it?

### Firebase Product(s)

Installations

**Comment by paulb777** [comment]
Thanks for the request. While it's not available via a top-level install, Installations is currently installable along with FirebaseAnalytics.

**Comment by paulb777** [comment]
Closing since we have no plans to have a separate Carthage installation for Installations since it is available with Analytics and can be selected from that download.
