### ISSUE TITLE
APMAnalytics causes a crash when accessing SKPaymentQueue.transactionObservers

### ISSUE THREAD

**Issue by fumito-ito** [firebase/firebase-ios-sdk#11622]
### Description

In an environment using the Firebase Apple SDK, accessing to `SKPaymentQueue.transactionObservers` with Swift's Array element method (e.g. `forEach` or `map`) will definitely crash.

The crash log records the following

```
Fatal error: NSArray element failed to match the Swift Array Element type
Expected SKPaymentTransactionObserver but found APMAnalytics 
```

### Reproducing the issue

A minimal reproduction of the code would look like this

```swift
// Assuming the Firebase Apple SDK has been imported and `FirebaseApp.configure()` has been run beforehand.
import StoreKit

SKPaymentQueue.default().transactionObservers.forEach { 
    print($0)
}
```

### Firebase SDK Version

10.12.0

### Xcode Version

14.3.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by morganchen12** [comment]
If you manually edit the `APMAnalytics.h` header and add the `SKPaymentTransactionObserver` conformance there, does the crash go away?

**Comment by fumito-ito** [comment]
hi @morganchen12 , thanks for your reply. I cannot find APMAnalytics.h in this project. Are the steps I should actually take to do the following?

1. dump the `APMAnalytics.h` file from https://github.com/chuiizeet/stickers-daily-headers/blob/master/Headers/APMAnalytics.h
2. put it into my project
3. run the minimal reproduction code

**Comment by morganchen12** [comment]
I did some investigating and the fundamental issue is `APMAnalytics` is a private type, so Swift can't coerce the type into an instance of `id<SKPaymentTransactionObserver>` because it doesn't have any visibility into the type's protocol conformances.

For the time being, you can work around this crash with the following:

```swift
(SKPaymentQueue.default().transactionObservers as [AnyObject]).forEach {
    print($0)
}
```

Fixing this may be challenging due to the nature of GoogleAppMeasurement's always-private headers.

**Comment by fumito-ito** [comment]
thanks @morganchen12 ! Your workaround works for me.

> Fixing this may be challenging due to the nature of GoogleAppMeasurement's always-private headers.

I think that is certainly true. Since a workaround has been provided and the problem has been resolved, I will close this Issue.
