### ISSUE TITLE
FieldValue.serverTimestamp() is not currently supported inside array

### ISSUE THREAD

**Issue by axiom-media** [firebase/firebase-ios-sdk#1164]
* Xcode version: 9.3
  * Firebase SDK version: 4.13
  * Firebase Component: Firestore
  * Component version: 0.11.0

I am trying to update a document within a transaction and I'm calling 

``` swift
transaction.updateData(editedList, forDocument: listRef)
```

where editedList is a Dictionary and listRef is a DocumentReference to the appropriate list.

The contents of the editedList dictionary are as follows:

``` swift
let editedList:[String:Any] = [
                                    "title": newTitle, // String
                              "description": newDescription, // String
                                     "tags": newTagsDictionary, // Dictionary of [String:Any]
                                 "listType": newListType, // String
                             "hasListImage": hasListImage, // Bool
                                "updatedAt": FieldValue.serverTimestamp()
        ]

```
If I include the last argument, my app crashes with the following error:

> *** Terminating app due to uncaught exception 'FIRInvalidArgumentException', reason: 'FieldValue.serverTimestamp() is not currently supported inside arrays'

However, there are no arrays being used in this case so I'm not sure if this is a bug or something I am doing incorrectly.  I have another section of code where I call setData and include the same fields and the serverTimestamp and it does not create any issues.  I also have another section of code that uses updateData and includes just two key/value pairs (one of which is serverTimestamp) without any problems.

For now, I'm getting around the issue by removing the "updatedAt":FieldValue.serverTimestamp() argument from my editedList dictionary, calling updateData(editedList...), and then doing a second call with just updateData("updatedAt": FieldValue.serverTimestamp()) and this seems to work.  But I'm assuming this will double my write operations and cost me more over time, so it would be useful if the bug could be fixed.

Thanks,
Kent

**Comment by mikelehen** [comment]
I was unable to reproduce this error with the following code against the 4.13.0 Firebase iOS SDK:

```
    let editedList:[String:Any] = [
      "title": "new title", // String
      "description": "new description", // String
      "tags": ["tag": "value"],
      "listType": "new list type", // String
      "hasListImage": true, // Bool
      "updatedAt": FieldValue.serverTimestamp()
    ]

    db!.runTransaction({ (txn, error) -> Any? in
      txn.updateData(editedList, forDocument:self.db!.collection("foo").document("bar"));
    }) { (result, error) in
      print("Transaction completed: \(error)")
    }
```

The transaction succeeded and the expected values (including the server timestamp) showed up in the Firebase Console data viewer. Could you provide more detail on how you are reproducing this issue?

**Comment by axiom-media** [comment]
Here is some example code, with the problematic line being the last key/value pair in the "editedItem" dictionary:

```` swift
let editedItem:[String:Any] = [
                            "title": newTitle as Any, // String
                      "description": newDescription as Any, // String
                             "tags": newTagsDictionary, // Dictionary with String:Bool
                     "hasItemImage": hasItemImage, // Bool
                      "updatedAt": FieldValue.serverTimestamp()
]

db.runTransaction({ (transaction, errorPointer) -> Any? in
            let listDoc: DocumentSnapshot
            do {
                try listDoc = transaction.getDocument(listRef)
            } catch let fetchError as NSError {
                errorPointer?.pointee = fetchError
                return nil
            }
            
            guard let orderedItems = listDoc.data()?["orderedItems"] as? NSMutableArray else {
                let error = NSError(
                    domain: "AppErrorDomain",
                    code: -1,
                    userInfo: [
                        NSLocalizedDescriptionKey: "Unable to retrieve orderedItems from snapshot \(listDoc)"
                    ]
                )
                errorPointer?.pointee = error
                return nil
            }
            
            //add new item to "Items" collection
            transaction.updateData(editedItem, forDocument: itemRef)
            // transaction.updateData(["updatedAt": FieldValue.serverTimestamp()], forDocument: itemRef) // this row is necessary after removing "updatedAt" from the editedItems dictionary
            
            //update orderedItems array within the Lists document
            for item in orderedItems {
                if (item as! NSDictionary).value(forKey: "itemID") as! String? == self.itemID {
                    (item as! NSDictionary).setValuesForKeys(editedItem)
                    break
                }
            }
            transaction.updateData(["orderedItems": orderedItems, "updatedAt": FieldValue.serverTimestamp()], forDocument: listRef) // this reference to "updatedAt" works fine
            
            return nil
        }) { (object, error) in
            if let error = error {
                print("Transaction failed: \(error)")
            } else {
                //Transaction successfully committed
                self.progress.animate(toAngle: 360, duration: 0.2, completion: nil)
                
                DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) {
                    self.dismiss(animated: true, completion: nil)
                }
            }
        }

````

**Comment by mikelehen** [comment]
@axiom-media Ahh...  Yes, it looks like you are storing FieldValue.serverTimestamp() inside an updatedAt field that's part of a dictionary that's stored in your orderedItems array, and as the error says, FieldValue.serverTimestamp() is not currently supported in arrays.  We will hopefully relax this in the future, but currently it is not feasible (FieldValue.serverTimestamp() is implemented by "transforming" a specific field in your data, but the wire protocol currently doesn't have a way to reference specific fields within an array, so there's no way to apply the server timestamp once you are inside an array).

Sorry for the inconvenience, but this is currently a known limitation.

**Comment by axiom-media** [comment]
@mikelehen thanks for your reply.  This was a silly oversight on my part as I forgot I was using "editedItem" for two purposes (one inside an array and one outside) and was convinced the error was coming from the second case (i.e. outside an array).  Sorry about that!

**Comment by mikelehen** [comment]
@axiom-media No worries! Glad we could get it resolved. :-)
