### ISSUE TITLE
Clarify Firebase Storage thread-safety

### ISSUE THREAD

**Issue by dwrss** [firebase/firebase-ios-sdk#11653]
### Description

Judging by the docstrings in the codebase you'd think that Firebase Storage is thoroughly non-thread-safe:
- [Storage](https://github.com/firebase/firebase-ios-sdk/blob/d4beb349ad5bb628808de89b2060b47ef3f7197a/FirebaseStorage/Sources/Storage.swift#L32) states that: ```Instances of `Storage` are not thread-safe.```
- Similar note on [StorageTask](https://github.com/firebase/firebase-ios-sdk/blob/d4beb349ad5bb628808de89b2060b47ef3f7197a/FirebaseStorage/Sources/StorageTask.swift#L29): ```This class is not thread safe, so only call methods on the main thread.``` (I'm finding this a little unclear in itself, as "not thread safe" and "only on the main queue" aren't the same thing?)
- [StorageDownloadTask](https://github.com/firebase/firebase-ios-sdk/blob/d4beb349ad5bb628808de89b2060b47ef3f7197a/FirebaseStorage/Sources/StorageDownloadTask.swift#L31C34-L31C45) is even more explicit: `Currently all downloads must be initiated and managed on the main queue.`
- None of these classes are `Sendable`

However:
- An internal queue is used to manage work, which would imply some degree of thread-safety (but I haven't audited all the classes).
-  The [5.12.0 release notes](https://firebase.google.com/support/release-notes/ios#cloud-storage_29) state that: `Storage operations can now be scheduled and controlled from any thread`.

So, I find myself a little confused: Is Firebase Storage thread safe or not? If it isn't thread-safe, is it safe to protect it with a serial `DispatchQueue`/wrap it in an `actor` or can I only use it on the main thread?

### Firebase Product(s)

Storage

**Comment by paulb777** [comment]
Thanks for the request. Yes, it looks like #1981 significantly improved thread safety without updating the docs. @morganchen12 would you take a look?
