### ISSUE TITLE
xcodebuild error using both firebase-ios-sdk & recaptcha-enterprise-mobile-sdk 

### ISSUE THREAD

**Issue by EverGod** [firebase/firebase-ios-sdk#11719]
### Description

If using the new version 10.14.0 I get:

```
xcodebuild: error: Could not resolve package dependencies:
  multiple products named 'RecaptchaInterop' in: 'interop-ios-for-google-sdks', 'recaptcha-enterprise-mobile-sdk'
```

Aside from using "firebase-ios-sdk" we are also using the "recaptcha-enterprise-mobile-sdk".

### Reproducing the issue

Use via Swift package manager both firebase-ios-sdk (v10.14.0) & recaptcha-enterprise-mobile-sdk.

### Firebase SDK Version

10.14.0

### Xcode Version

14.3.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication, Crashlytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
xcodebuild: error: Could not resolve package dependencies:
  multiple products named 'RecaptchaInterop' in: 'interop-ios-for-google-sdks', 'recaptcha-enterprise-mobile-sdk'
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by EverGod** [comment]
Thanks @paulb777. 
I forgot to mention I did update also recaptcha-enterprise-mobile-sdk to the latest version 18.3.0 (along with the latest firebase-ios-sdk 10.14.0).

I can also add that the issue:
```
xcodebuild: error: Could not resolve package dependencies:
  multiple products named 'RecaptchaInterop' in: 'interop-ios-for-google-sdks', 'recaptcha-enterprise-mobile-sdk'
```
Was seen only in Release type builds (for the App Store) and not in Debug development ones.

**Comment by paulb777** [comment]
@EverGod I'm not able to reproduce. Are you able to share a reproducible example?
