### ISSUE TITLE
firebase-ios-sdk could not be resolved

### ISSUE THREAD

**Issue by bodasooqa** [firebase/firebase-ios-sdk#11713]
### Description

I get this when I try to install firebase-ios-sdk via Swift Package Manager

<img width="1078" alt="screenshot" src="https://github.com/firebase/firebase-ios-sdk/assets/34233108/8fd3929b-3504-46d7-a3e2-f1046cb48c37">

### Reproducing the issue

Go to "File > Add package"

Then put "https://github.com/firebase/firebase-ios-sdk.git" into the search field

And then get an error

### Firebase SDK Version

10.13.0 (Up to Next Major Version)

### Xcode Version

15.0 beta (15A5160n)

### Installation Method

Swift Package Manager

### Firebase Product(s)

Installations

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by bodasooqa** [comment]
Ok, I will update my Xcode and repeat to install it
then I will write here about my result

**Comment by MunirehHosseinzada** [comment]
I have the exact issue. My Xcode version is 14.3.1

**Comment by ncooke3** [comment]
If you select `Add Anyway`, does it give more info as to why the package resolution is failing? The logs should be in the left side pane within Xcode:

<img width="530" alt="Screenshot 2023-08-22 at 1 09 30 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/36927374/ab20c72f-a393-4f8f-baba-5fce9f48f589">

**Comment by bodasooqa** [comment]
Ok, I updated my XCode to Version 15.0 beta 6 (15A5219j) and it helped

I successfully installed firebase-ios-sdk 10.14.0
