### ISSUE TITLE
Crashlytics warning with XCode 15 beta 

### ISSUE THREAD

**Issue by dpyy** [firebase/firebase-ios-sdk#11710]
### Description

warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase

### Reproducing the issue

After following the steps of setting up the symbol upload step in build phases, it currently builds but now with a warning

### Firebase SDK Version

master

### Xcode Version

15

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reporting, @dpyy. To have a better understanding of the issue, could you provide the detailed steps to reproduce it?

**Comment by kim-f** [comment]
Hello, thank you for reporting this warning for xCode 15 beta. Since this warning does not prevent the app from building successfully, our team is not planning to actively work on addressing this warning at this time. If you encounter any other issues or we misunderstood your report, please let us know!

**Comment by dpyy** [comment]
> For other folks running into this, the crashlytics run script is expected to run every build, so we recommend unchecking, "Based on dependency analysis".
> 
> ![Screenshot 2023-08-22 at 2 19 26 PM](https://user-images.githubusercontent.com/555046/262446291-1719b7b5-a43f-4874-9477-fcc493d90237.png)

I already have that checked that's the issue:
<img width="815" alt="Screenshot 2023-08-22 at 2 55 06 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/19830772/82d13df1-7f70-4d13-a5da-071d767d1d7a">

<img width="311" alt="Screenshot 2023-08-22 at 2 55 19 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/19830772/0d746c52-5ec8-41bf-810c-1fdac4326538">
