### ISSUE TITLE
@DocumentId and @ServerTimestamp property wrappers not compatible with the new @Observable

### ISSUE THREAD

**Issue by rderimay** [firebase/firebase-ios-sdk#11724]
### Description

When trying the compile with the Xcode 15 leveraging the use of the `@Observable` macro instead on the former `ObservableObject` protocol, the compiler throws 
`Property wrapper cannot be applied to a computed property` 
on properties decorated with `@DocumentID` or `@ServerTimestamp`

This is due to the `@Observable` macro rewriting all properties to set / get computed properties.

Is there any workaround?

Thanks!

### Reproducing the issue

Pre Xcode 15:
```
class Test1: ObservableObject {
    @DocumentID var id: String?
    @ServerTimestamp var _createdAt: Date?
    
    var name: String?
}
```

Xcode 15 not compiling:
```
@Observable class Test2 {
    @DocumentID var id: String?
    @ServerTimestamp var _createdAt: Date?
    
    var name: String?
}
```

![image](https://github.com/firebase/firebase-ios-sdk/assets/12871929/17bc8b13-5ea3-4974-8be0-10f8c7e86c2b)

### Firebase SDK Version

10.9

### Xcode Version

15.x

### Installation Method

Swift Package Manager

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS, macOS

**Comment by milaGGL** [comment]
Hi @rderimay, thank you for reporting this issue. A workaround for this could be creating a view model (and make it observable), and make the view model hold one (or multiple) instances of the data object (which would not be observable). 

Or, if you really want to make the data objects observable, one option might be to mark the @DocumentId property as @ObservationIgnore: [https://developer.apple.com/documentation/observation/observationignored()](https://developer.apple.com/documentation/observation/observationignored%28%29)

**Comment by rderimay** [comment]
Thanks a lot for your answer!
