### ISSUE TITLE
FPRNSURLSessionInstrument.m - Line 307 -InstrumentDataTaskWithRequestCompletionHandler_block_invoke_2

### ISSUE THREAD

**Issue by salvatoreboemia** [firebase/firebase-ios-sdk#11732]
### Description

Hi,

I'm having a problem with firebase

This is the log

<img width="487" alt="Screenshot 2023-08-28 at 12 17 37" src="https://github.com/firebase/firebase-ios-sdk/assets/20614870/2d26444c-2f91-41b8-9184-03c7ca6e656e">

any ideas on how to fix it? (as well as trying to update your firebase version)

Thanks

### Reproducing the issue

Random user

### Firebase SDK Version

10.10

### Xcode Version

14.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
0 | Mon Aug 28 2023 12:09:28 GMT+0200 (Central European Summer Time) | safelyReturnCurrentPatterns empty
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reporting, @salvatoreboemia. Could you provide your full stack trace to see what's causing the issue?

**Comment by rizafran** [comment]
Thanks for sharing your stack trace, @salvatoreboemia. It looks like the issue might be related to #11421. Could you try updating to 10.13.0 and see if the issue will persist?
