### ISSUE TITLE
Use github action and fastlane upload dSYM file success but Firebase console shows dSYM required

### ISSUE THREAD

**Issue by karthuszY** [firebase/firebase-ios-sdk#11735]
### Description

I use github action and fastlane for iOS package:
```
      upload_symbols_to_crashlytics(
                            dsym_path: dsym_path,
                            gsp_path: "./aistro-ios/GoogleService-Info.plist",
                            binary_path: binary_path
                          )
```

```
[06:38:03]: --- Step: upload_symbols_to_crashlytics ---
[06:38:03]: -------------------------------------------
[06:38:03]: Uploading '/Users/runner/work/aistro-ios/aistro-ios/aistro-ios.app.dSYM.zip'...
[06:38:17]: Successfully uploaded dSYM files to Crashlytics 💯
[06:38:17]: -----------------------------------
```

But on Firebase console, the version shows unknown and when carsh on a specific version, it still shows dSYM required

<img width="779" alt="image" src="https://github.com/firebase/firebase-ios-sdk/assets/13864988/ec251787-c977-45dd-80cc-8169d204666e">

### Firebase SDK Version

10.9

### Xcode Version

14.3.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reporting, @karthuszY. Based on your logs, your dSYM files were successfully uploaded, but still showing missing dSYMs in the Crashlytics dashboard. With this, you may try to check the troubleshooting steps [here](https://firebase.google.com/docs/crashlytics/troubleshooting?platform=ios#ios-locate-dsyms). If the issue persists, you may reach out through our [Firebase support](https://firebase.google.com/support/troubleshooter/crashlytics) so they could investigate your dSYMs and project. 

I'll now be closing this ticket.
