### ISSUE TITLE
Firebase Remote Config fetchAndActivate completion block not executed

### ISSUE THREAD

**Issue by LauraLopezAragoneses** [firebase/firebase-ios-sdk#11738]
### Description

The completion block of fetchAndActivate is not being executed sometimes although it worked fine before, using FirebaseRemoteConfig 10.5.0.
We are using real-time Remote Config, so each time we change something in the Firebase console, we close the app and open it again, it'll work and the changes are applied correctly, but then if we open the app after the `minimumFetchInterval`, the completion is not executed.
It looks like we are experimenting some throttle issues although we don't get any throttle status or error.

### Reproducing the issue

We are first configuring the RemoteConfig instance:

```
public func configureRemoteConfig(isSecondaryApp: Bool) {
        let app = isSecondaryApp ? FirebaseApp.app(name: FirebaseConfiguration.secondaryApp) : FirebaseApp.app()
        if let app {
            remoteConfig = RemoteConfig.remoteConfig(app: app)
        }
        let settings = RemoteConfigSettings()
        settings.minimumFetchInterval = 30
        remoteConfig.configSettings = settings
        remoteConfig.setDefaults(fromPlist: "remote_config_defaults")
    }
```

And then we fetch the Remote Config and subscribe to real-time changes:

```
public func fetchRemoteConfig(completion: @escaping ((Result<Void, Error>) -> Void)) {
        self.remoteConfig.fetchAndActivate { status, error in
            switch status {
            case .error:
                completion(Result.failure(error ?? FirebaseError.generic))
                
            case .successFetchedFromRemote, .successUsingPreFetchedData:
                completion(Result.success(()))
                
            default:
                completion(Result.failure(error ?? FirebaseError.generic))
            }
        }
        
        remoteConfig.addOnConfigUpdateListener { update, error in
            if let error {
                Logger.log("Remote Config: update error: \(error)", level: .error)
            }
            if let update {
                Logger.log("Remote Config: some keys have been updated: \(String(describing: update.updatedKeys))", level: .debug)
            }
        }
    }

```

We've tried with different minimumFetchInterval, but is the same, after that time the fetch won't work.

### Firebase SDK Version

10.14.0

### Xcode Version

14.3

### Installation Method

CocoaPods

### Firebase Product(s)

Remote Config

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

{
  "object": {
    "pins": [
      {
        "package": "Alamofire",
        "repositoryURL": "https://github.com/Alamofire/Alamofire.git",
        "state": {
          "branch": null,
          "revision": "8dd85aee02e39dd280c75eef88ffdb86eed4b07b",
          "version": "5.6.2"
        }
      },
      {
        "package": "AlgoliaSearchClient",
        "repositoryURL": "https://github.com/algolia/algoliasearch-client-swift",
        "state": {
          "branch": null,
          "revision": "3ae3deec2fedc375047bf789983c3d608c861dcd",
          "version": "8.18.0"
        }
      },
      {
        "package": "Boomerang",
        "repositoryURL": "https://github.com/synesthesia-it/Boomerang",
        "state": {
          "branch": "master",
          "revision": "a0ee6d294d1ba28be476345de48dce0248c6c28f",
          "version": null
        }
      },
      {
        "package": "Facebook",
        "repositoryURL": "https://github.com/facebook/facebook-ios-sdk",
        "state": {
          "branch": null,
          "revision": "c46ba480e9b176a950c428b1a1ec3fd57810f8fe",
          "version": "11.2.1"
        }
      },
      {
        "package": "INSPhotoGallery",
        "repositoryURL": "https://github.com/m1entus/INSPhotoGallery",
        "state": {
          "branch": null,
          "revision": "f0a89f5d83dd47a0f109ae40c84c9567a5643165",
          "version": "1.2.9"
        }
      },
      {
        "package": "InstantSearch",
        "repositoryURL": "https://github.com/algolia/instantsearch-ios",
        "state": {
          "branch": null,
          "revision": "d34ff55926d70649e597260593839126feabcaf9",
          "version": "7.25.0"
        }
      },
      {
        "package": "InstantSearchTelemetry",
        "repositoryURL": "https://github.com/algolia/instantsearch-telemetry-native",
        "state": {
          "branch": null,
          "revision": "d9861ceb2fe25899a31672fb7c648ae8036d3221",
          "version": "0.1.3"
        }
      },
      {
        "package": "BranchSDK",
        "repositoryURL": "https://github.com/BranchMetrics/ios-branch-sdk-spm",
        "state": {
          "branch": null,
          "revision": "7fbe3085821c8e60241a2037098c6eed76fd2798",
          "version": "2.2.0"
        }
      },
      {
        "package": "Airship",
        "repositoryURL": "https://github.com/urbanairship/ios-library",
        "state": {
          "branch": null,
          "revision": "2a953b4f4f6a2e5d41afcdf9eb0e914a66bee431",
          "version": "17.0.3"
        }
      },
      {
        "package": "KeychainAccess",
        "repositoryURL": "https://github.com/kishikawakatsumi/KeychainAccess",
        "state": {
          "branch": null,
          "revision": "84e546727d66f1adc5439debad16270d0fdd04e7",
          "version": "4.2.2"
        }
      },
      {
        "package": "Kingfisher",
        "repositoryURL": "https://github.com/onevcat/Kingfisher",
        "state": {
          "branch": null,
          "revision": "af4be924ad984cf4d16f4ae4df424e79a443d435",
          "version": "7.6.2"
        }
      },
      {
        "package": "Lottie",
        "repositoryURL": "https://github.com/airbnb/lottie-ios",
        "state": {
          "branch": null,
          "revision": "b4bd0604ded9574807f41b4004b57dd1226a30a4",
          "version": "3.5.0"
        }
      },
      {
        "package": "Pageboy",
        "repositoryURL": "https://github.com/uias/Pageboy",
        "state": {
          "branch": null,
          "revision": "5522aa6ae88633f6c23cf504e9cd684e963822f1",
          "version": "4.0.2"
        }
      },
      {
        "package": "Pulley",
        "repositoryURL": "https://github.com/52inc/Pulley",
        "state": {
          "branch": null,
          "revision": "355bb7c53d4d430334422ad05a97fbe43ce326db",
          "version": "2.9.1"
        }
      },
      {
        "package": "RxDataSources",
        "repositoryURL": "https://github.com/RxSwiftCommunity/RxDataSources.git",
        "state": {
          "branch": null,
          "revision": "90c29b48b628479097fe775ed1966d75ac374518",
          "version": "5.0.2"
        }
      },
      {
        "package": "RxGesture",
        "repositoryURL": "https://github.com/RxSwiftCommunity/RxGesture.git",
        "state": {
          "branch": null,
          "revision": "1b137c576b4aaaab949235752278956697c9e4a0",
          "version": "4.0.4"
        }
      },
      {
        "package": "RxSwift",
        "repositoryURL": "https://github.com/ReactiveX/RxSwift.git",
        "state": {
          "branch": null,
          "revision": "b4307ba0b6425c0ba4178e138799946c3da594f8",
          "version": "6.5.0"
        }
      },
      {
        "package": "swift-log",
        "repositoryURL": "https://github.com/apple/swift-log.git",
        "state": {
          "branch": null,
          "revision": "32e8d724467f8fe623624570367e3d50c5638e46",
          "version": "1.5.2"
        }
      },
      {
        "package": "SwiftProtobuf",
        "repositoryURL": "https://github.com/apple/swift-protobuf.git",
        "state": {
          "branch": null,
          "revision": "f25867a208f459d3c5a06935dceb9083b11cd539",
          "version": "1.22.0"
        }
      },
      {
        "package": "SwiftRichString",
        "repositoryURL": "https://github.com/malcommac/SwiftRichString",
        "state": {
          "branch": null,
          "revision": "9bf4b5af6bb4386865636fc504d6c588c2b65040",
          "version": "3.7.2"
        }
      },
      {
        "package": "Tabman",
        "repositoryURL": "https://github.com/uias/Tabman",
        "state": {
          "branch": null,
          "revision": "6a87a2825939f5da06cf52a6582d67a646488cff",
          "version": "3.0.1"
        }
      },
      {
        "package": "Zip",
        "repositoryURL": "https://github.com/marmelroy/Zip",
        "state": {
          "branch": null,
          "revision": "bd19d974e8a38cc8d3a88c90c8a107386c3b8ccf",
          "version": "2.1.1"
        }
      }
    ]
  },
  "version": 1
}

### If using CocoaPods, the project's Podfile.lock

PODS:
  - Analytics (4.1.6)
  - AppAuth (1.6.2):
    - AppAuth/Core (= 1.6.2)
    - AppAuth/ExternalUserAgent (= 1.6.2)
  - AppAuth/Core (1.6.2)
  - AppAuth/ExternalUserAgent (1.6.2):
    - AppAuth/Core
  - FirebaseABTesting (10.14.0):
    - FirebaseCore (~> 10.0)
  - FirebaseAnalytics (10.12.0):
    - FirebaseAnalytics/AdIdSupport (= 10.12.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (10.12.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleAppMeasurement (= 10.12.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseCore (10.12.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Logger (~> 7.8)
  - FirebaseCoreExtension (10.14.0):
    - FirebaseCore (~> 10.0)
  - FirebaseCoreInternal (10.14.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseCrashlytics (10.12.0):
    - FirebaseCore (~> 10.5)
    - FirebaseInstallations (~> 10.0)
    - FirebaseSessions (~> 10.5)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.8)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (~> 2.1)
  - FirebaseInstallations (10.14.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)
  - FirebasePerformance (10.12.0):
    - FirebaseCore (~> 10.5)
    - FirebaseInstallations (~> 10.0)
    - FirebaseRemoteConfig (~> 10.0)
    - FirebaseSessions (~> 10.5)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/ISASwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseRemoteConfig (10.14.0):
    - FirebaseABTesting (~> 10.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseRemoteConfigSwift (10.12.0):
    - FirebaseRemoteConfig (~> 10.0)
    - FirebaseSharedSwift (~> 10.0)
  - FirebaseSessions (10.14.0):
    - FirebaseCore (~> 10.5)
    - FirebaseCoreExtension (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.10)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesSwift (~> 2.1)
  - FirebaseSharedSwift (10.14.0)
  - Gigya (1.5.2)
  - google-cast-sdk (4.7.0):
    - google-cast-sdk/Core (= 4.7.0)
    - Protobuf (~> 3.13)
  - google-cast-sdk/Core (4.7.0):
    - Protobuf (~> 3.13)
  - Google-Mobile-Ads-SDK (10.9.0):
    - GoogleAppMeasurement (< 11.0, >= 7.0)
    - GoogleUserMessagingPlatform (>= 1.1)
  - GoogleAds-IMA-iOS-SDK (3.18.4)
  - GoogleAppMeasurement (10.12.0):
    - GoogleAppMeasurement/AdIdSupport (= 10.12.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/AdIdSupport (10.12.0):
    - GoogleAppMeasurement/WithoutAdIdSupport (= 10.12.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/WithoutAdIdSupport (10.12.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleDataTransport (9.2.5):
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleMaps (6.2.1):
    - GoogleMaps/Maps (= 6.2.1)
  - GoogleMaps/Base (6.2.1)
  - GoogleMaps/Maps (6.2.1):
    - GoogleMaps/Base
  - GoogleSignIn (7.0.0):
    - AppAuth (~> 1.5)
    - GTMAppAuth (< 3.0, >= 1.3)
    - GTMSessionFetcher/Core (< 4.0, >= 1.1)
  - GoogleUserMessagingPlatform (2.1.0)
  - GoogleUtilities (7.11.1):
    - GoogleUtilities/AppDelegateSwizzler (= 7.11.1)
    - GoogleUtilities/Environment (= 7.11.1)
    - GoogleUtilities/ISASwizzler (= 7.11.1)
    - GoogleUtilities/Logger (= 7.11.1)
    - GoogleUtilities/MethodSwizzler (= 7.11.1)
    - GoogleUtilities/Network (= 7.11.1)
    - "GoogleUtilities/NSData+zlib (= 7.11.1)"
    - GoogleUtilities/Reachability (= 7.11.1)
    - GoogleUtilities/SwizzlerTestHelpers (= 7.11.1)
    - GoogleUtilities/UserDefaults (= 7.11.1)
  - GoogleUtilities/AppDelegateSwizzler (7.11.1):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (7.11.1):
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/ISASwizzler (7.11.1)
  - GoogleUtilities/Logger (7.11.1):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (7.11.1):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (7.11.1):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.11.1)"
  - GoogleUtilities/Reachability (7.11.1):
    - GoogleUtilities/Logger
  - GoogleUtilities/SwizzlerTestHelpers (7.11.1):
    - GoogleUtilities/MethodSwizzler
  - GoogleUtilities/UserDefaults (7.11.1):
    - GoogleUtilities/Logger
  - GTMAppAuth (2.0.0):
    - AppAuth/Core (~> 1.6)
    - GTMSessionFetcher/Core (< 4.0, >= 1.5)
  - GTMSessionFetcher/Core (3.1.1)
  - INSNibLoading (1.0.2)
  - nanopb (2.30909.0):
    - nanopb/decode (= 2.30909.0)
    - nanopb/encode (= 2.30909.0)
  - nanopb/decode (2.30909.0)
  - nanopb/encode (2.30909.0)
  - OneTrust-CMP-XCFramework (202304.1.0.0)
  - ownid-core-ios-sdk (2.1.0)
  - ownid-gigya-ios-sdk (2.1.0):
    - Gigya
    - ownid-core-ios-sdk (= 2.1.0)
  - pop (1.0.12)
  - PromisesObjC (2.3.1)
  - PromisesSwift (2.3.1):
    - PromisesObjC (= 2.3.1)
  - Protobuf (3.23.0)
  - SCSDKCameraKit (1.24.0)
  - SCSDKCameraKitReferenceSwiftUI (1.24.0):
    - SCSDKCameraKitReferenceUI (~> 1.24.0)
  - SCSDKCameraKitReferenceUI (1.24.0):
    - SCSDKCameraKit (~> 1.24.0)
  - SnapSDK/SCSDKCoreKit (2.4.0)
  - SnapSDK/SCSDKCreativeKit (2.4.0):
    - SnapSDK/SCSDKCoreKit
  - TTTAttributedLabel (2.0.0)
  - YouboraAVPlayerAdapter (6.7.0):
    - YouboraAVPlayerAdapter/Default (= 6.7.0)
    - YouboraLib (~> 6.5)
  - YouboraAVPlayerAdapter/Default (6.7.0):
    - YouboraLib (~> 6.5)
  - YouboraIMAAdapter (6.6.3):
    - GoogleAds-IMA-iOS-SDK (~> 3.13)
    - GoogleAds-IMA-tvOS-SDK (~> 4.3)
    - YouboraLib (~> 6.5)
  - YouboraLib (6.7.1)

DEPENDENCIES:
  - Analytics
  - FirebaseAnalytics (~> 10.12.0)
  - FirebaseCore (~> 10.12.0)
  - FirebaseCrashlytics (~> 10.12.0)
  - FirebasePerformance (~> 10.12.0)
  - FirebaseRemoteConfigSwift (~> 10.12.0)
  - Gigya (= 1.5.2)
  - google-cast-sdk (= 4.7.0)
  - Google-Mobile-Ads-SDK (~> 10.9.0)
  - GoogleAds-IMA-iOS-SDK (= 3.18.4)
  - GoogleMaps
  - GoogleSignIn (~> 7.0.0)
  - GoogleUtilities
  - INSNibLoading
  - OneTrust-CMP-XCFramework (~> 202304.1.0.0)
  - ownid-gigya-ios-sdk (= 2.1.0)
  - pop
  - SCSDKCameraKit
  - SCSDKCameraKitReferenceSwiftUI
  - SnapSDK/SCSDKCreativeKit (= 2.4.0)
  - TTTAttributedLabel
  - YouboraAVPlayerAdapter (= 6.7.0)
  - YouboraIMAAdapter

SPEC REPOS:
  trunk:
    - Analytics
    - AppAuth
    - FirebaseABTesting
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreExtension
    - FirebaseCoreInternal
    - FirebaseCrashlytics
    - FirebaseInstallations
    - FirebasePerformance
    - FirebaseRemoteConfig
    - FirebaseRemoteConfigSwift
    - FirebaseSessions
    - FirebaseSharedSwift
    - Gigya
    - google-cast-sdk
    - Google-Mobile-Ads-SDK
    - GoogleAds-IMA-iOS-SDK
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleMaps
    - GoogleSignIn
    - GoogleUserMessagingPlatform
    - GoogleUtilities
    - GTMAppAuth
    - GTMSessionFetcher
    - INSNibLoading
    - nanopb
    - OneTrust-CMP-XCFramework
    - ownid-core-ios-sdk
    - ownid-gigya-ios-sdk
    - pop
    - PromisesObjC
    - PromisesSwift
    - Protobuf
    - SCSDKCameraKit
    - SCSDKCameraKitReferenceSwiftUI
    - SCSDKCameraKitReferenceUI
    - SnapSDK
    - TTTAttributedLabel
    - YouboraAVPlayerAdapter
    - YouboraIMAAdapter
    - YouboraLib

SPEC CHECKSUMS:
  Analytics: eefe524436f904b8bb3f8c8c3425280e43b34efc
  AppAuth: 3bb1d1cd9340bd09f5ed189fb00b1cc28e1e8570
  FirebaseABTesting: e1535073fac4ff55c7537a6e041155c72d9e6906
  FirebaseAnalytics: 0270389efbe3022b54ec4588862dabec3477ee98
  FirebaseCore: f86a1394906b97ac445ae49c92552a9425831bed
  FirebaseCoreExtension: 976638051b1a46b503afce7ec80277f9161f2040
  FirebaseCoreInternal: d558159ee6cc4b823c2296ecc193de9f6d9a5bb3
  FirebaseCrashlytics: c4d111b7430c49744c74bcc6346ea00868661ac8
  FirebaseInstallations: f672b1eda64e6381c21d424a2f680a943fd83f3b
  FirebasePerformance: 1a63c51c9d14fc1190b0970d5aab96672cb0bce6
  FirebaseRemoteConfig: e22a706fa7ecc64135325f4c430a15af1e795535
  FirebaseRemoteConfigSwift: 80d458558440af70fa77979fda2c921a127b7499
  FirebaseSessions: f145e7365d36bec0d724c4574a8750e6f82fa6c8
  FirebaseSharedSwift: 0eec812f08b6ec9e03196fc27635739781513028
  Gigya: 030de6ed660df58730b0e188ea981cad02d82681
  google-cast-sdk: 6731e9a206ce43e0f4433d15598ad8a19f0371d5
  Google-Mobile-Ads-SDK: e81e8b009a182dc8dd14951782efdbb30a5e4510
  GoogleAds-IMA-iOS-SDK: b01284e3bf3d64ba948de6692ffda531452c3713
  GoogleAppMeasurement: 2d800fab85e7848b1e66a6f8ce5bca06c5aad892
  GoogleDataTransport: 54dee9d48d14580407f8f5fbf2f496e92437a2f2
  GoogleMaps: 20d7b12be49a14287f797e88e0e31bc4156aaeb4
  GoogleSignIn: b232380cf495a429b8095d3178a8d5855b42e842
  GoogleUserMessagingPlatform: dce302b8f1b84d6e945812ee7a15c3f65a102cbf
  GoogleUtilities: 9aa0ad5a7bc171f8bae016300bfcfa3fb8425749
  GTMAppAuth: 99fb010047ba3973b7026e45393f51f27ab965ae
  GTMSessionFetcher: e8647203b65cee28c5f73d0f473d096653945e72
  INSNibLoading: 0244d5b9c30d4642c77b31469cbfd905e8b1efb3
  nanopb: b552cce312b6c8484180ef47159bc0f65a1f0431
  OneTrust-CMP-XCFramework: 6ba009d173203f5e74bb33708df5ddac6f3edc1c
  ownid-core-ios-sdk: 42096cb0aea330c8163ec29291290e8ad874f8ad
  ownid-gigya-ios-sdk: c6c5112a0eccab4d1831e82145f233b60bfb1e64
  pop: d582054913807fd11fd50bfe6a539d91c7e1a55a
  PromisesObjC: c50d2056b5253dadbd6c2bea79b0674bd5a52fa4
  PromisesSwift: 28dca69a9c40779916ac2d6985a0192a5cb4a265
  Protobuf: 43e3764cdf3609fdd00417649561565703437fdc
  SCSDKCameraKit: 7f8864857d4510a75bc08f83ff8ee4f7ea833959
  SCSDKCameraKitReferenceSwiftUI: 6d841cd23ce860a79dba4c13897022eee314d168
  SCSDKCameraKitReferenceUI: a6e2f239c2561799cda69eb49711cbfb7be9ae4d
  SnapSDK: e832716ff024b17b448f9bca5feeac5a3daed3ff
  TTTAttributedLabel: 8cffe8e127e4e82ff3af1e5386d4cd0ad000b656
  YouboraAVPlayerAdapter: f48516d2e5862e3f6b183471993be165cc8e8c77
  YouboraIMAAdapter: aed03e9cebc611875ba769315d6348dc040f9fd6
  YouboraLib: bec896cbfc74ce4a2243a6a55da099e7843f1242

PODFILE CHECKSUM: e3691c39eb4c4199f5f5c7ce7f4d0486ae69c5d5

COCOAPODS: 1.12.1

**Comment by ehyche** [comment]
I would appreciate if this issue can be confirmed and if so, to know if there is any workaround.

**Comment by rizafran** [comment]
That's great to hear, @LauraLopezAragoneses. 

Hi @ehyche, may I know if the fix in https://github.com/firebase/firebase-ios-sdk/issues/11738#issuecomment-1698704995 also works for you? If not, then it's possible that your issue might be different with this issue. That said, could you file a new separate ticket for better tracking?

**Comment by ehyche** [comment]
@rizafran : we are already calling `RemoteConfig.fetch()` from our main app target, so the fix that @LauraLopezAragoneses mentions doesn't work for us.  I will be glad to file a separate Github issue on this.
