### ISSUE TITLE
firebase dynamic link on iOS16.6 gets canadias://google/link/?dismiss=1&is_weak_match=1 when first installed (Objected C)

### ISSUE THREAD

**Issue by paul-zhengtianyuan** [firebase/firebase-ios-sdk#11753]
### Description

I’m using ios app to parse the dynamic link which is generated by REST API，and the case is when the user has already installed the app, it can get the deep link properly, but when the user doesn’t have the app, it will go to the app store. After installing the app, it means the user the first time to enter into the app, but sadly my ios app can’t get the deep link. I use the code which is instructed by the documention which is the following:
`- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(nullable NSString *)sourceApplication annotation:(id)annotation {
FIRDynamicLink *dynamicLink = [[FIRDynamicLinks dynamicLinks] dynamicLinkFromCustomSchemeURL:url];
  if (dynamicLink) {
    if (dynamicLink.url) {
      // Handle the deep link. For example, show the deep-linked content,
      // apply a promotional offer to the user's account or show customized onboarding view.
      // ...
        NSLog(@"dynamicLink.url:%@",dynamicLink.url);
        NSLog(@"dynamicLink.utm_content:%@",dynamicLink.utmParametersDictionary);
    } else {
      // Dynamic link has empty deep link. This situation will happens if
      // Firebase Dynamic Links iOS SDK tried to retrieve pending dynamic link,
      // but pending link is not available for this device/App combination.
      // At this point you may display default onboarding view.
    }
    return YES;`

What I’m getting is:

<schema>//google/link/?dismiss=1&is_weak_match=1

### Firebase SDK Version

8.9.1

### Xcode Version

14.2

### Installation Method

CocoaPods

### Firebase Product(s)

DynamicLinks

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @paul-zhengtianyuan, the Firebase Dynamic Links service will be shutdown on August 25, 2025. In the meantime, only critical or security issues will be fixed in the SDK.

See https://firebase.google.com/support/dynamic-links-faq for more details.
