### ISSUE TITLE
Undefined symbol: OBJC_CLASS_$_FIRApp | OBJC_CLASS_$_FIRMessaging when building Xcode Project

### ISSUE THREAD

**Issue by DeiMartinez** [firebase/firebase-ios-sdk#11754]
### Description

I was given an Xcode Project built in an outdated Firebase Version. So i Upgraded both my Xcode Version and my Firebase Dependencies. 
When doing so I ended up with Xcode 13.4 and Firebase 10.14.0

I updated every Class in my project to be compiled by Swift5 and everything seems to work when building but these two errors.
I only import FirebaseDatabase, FirebaseAnalytics and FirebaseMessaging frameworks. I did it manually by downloading the folder from github and including them on my project. I didnt use cocoapods nor other helpers.

### Reproducing the issue

Build the project and I get the error when executing FirebaseApp.configure()

### Firebase SDK Version

10.14.0

### Xcode Version

13.4

### Installation Method

Zip

### Firebase Product(s)

Analytics, Database, Messaging

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FIRApp", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_FIRMessaging", referenced from:
      objc-class-ref in LoginController.o
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by DeiMartinez** [comment]
I am building for simulator and I veryfied that the libraries that the project uses to build are for x86_64.

**Comment by ncooke3** [comment]
Hi @DeiMartinez, could you instead on Xcode 14.1? Firebase requires Xcode 14.1.

A few other things to check:
- Is the `FirebaseCore.xcframework` visible in your project navigator (and added as a framework dependency in your build settings)? See the README.md in the zip archive for the integration instructions.
- Is `FirebaseCore` imported into `AppDelegate.swift`?

**Comment by DeiMartinez** [comment]
Hey I couldn't run Xcode 14.1 on my device that's why 13.4. I got a workaround, using the Xcode Swift Package Manager the error disappears. Yeah, I had FirebaseCore, FirebaseAnalytics and FirebaseMessaging all imported into AppDelegate.swift and the error ocurred.
