### ISSUE TITLE
I can't add Firebase to Xcode 

### ISSUE THREAD

**Issue by FBukovina** [firebase/firebase-ios-sdk#11752]
### Description

Hi, when I tried to add package depencies to Xcode (package https://github.com/firebase/firebase-ios-sdk.git) Xcode told me this:Received invalid response at https://github.com/firebase/firebase-ios-sdk.git. Please make sure it is a package collection URL.
How can I import Firebase? ZIP didn't work too.
Thanks

### Firebase SDK Version

10.14.0

### Xcode Version

15 beta 8

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS, macOS

### Relevant Log Output

```shell
Received invalid response at https://github.com/firebase/firebase-ios-sdk.git. Please make sure it is a package collection URL.
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @FBukovina, I tried to reproduce the issue, but I was able to successfully add the SDK in SPM. Have you tried using other network/machine or tried restarting the Xcode?

**Comment by FBukovina** [comment]
I tried network and restarting Xcode too. I can't use other machine

**Comment by rizafran** [comment]
Thanks for the update, @FBukovina. Could you try the following to see if that will fix the issue:

- Delete your Xcode's derived data
- Open File > Packages then click Reset package caches

If the issue persists, you may share a reproducible sample app to investigate.

**Comment by ncooke3** [comment]
Hi @FBukovina– in addition to @rizafran's suggestions above, I would also try verifying that you can manually clone the Firebase repo with success.

**Comment by FBukovina** [comment]
Hi @ncooke3 . I tried @rizafran suggestion to delete the package caches and it doesn't worked. How to clone Firebase manually? Thank you :)

**Comment by paulb777** [comment]
From the command line `git clone https://github.com/firebase/firebase-ios-sdk.git`
