### ISSUE TITLE
Firestore Crash with Empty Blob field

### ISSUE THREAD

**Issue by harry-dickson** [firebase/firebase-ios-sdk#11773]
### Description

I have a Document with a Blob field that is ~~null~~ empty.
In my Flutter app, when I fetch the document there is a crash.

The crash occurs in `Firestore/core/src/nanopb/nanopb_util.h`:

```obj-c
// line 181
inline NSData* _Nonnull MakeNSData(const pb_bytes_array_t* _Nullable data) {
  return [[NSData alloc] initWithBytes:data->bytes length:data->size];
}
```

The `data` is declared as being nullable, null is passed in and then dereferenced without any attempt to check it.
The return type is not nullable, making reasonable behavior difficult. Either it should return something in the face of null, or it should never be called with null in the first place. Allowing the app to crash is not a cool outcome.

This is the calling code in `FSTUserDataWriter.mm`:

```obj-c
// line 81
- (id)convertedValue:(const google_firestore_v1_Value &)value {
  switch (GetTypeOrder(value)) {
    case TypeOrder::kMap:
      return [self convertedObject:value.map_value];
    case TypeOrder::kArray:
      return [self convertedArray:value.array_value];
    case TypeOrder::kReference:
      return [self convertedReference:value];
    case TypeOrder::kTimestamp:
      return [self convertedTimestamp:value.timestamp_value];
    case TypeOrder::kServerTimestamp:
      return [self convertedServerTimestamp:value];
    case TypeOrder::kNull:
      return [NSNull null];
    case TypeOrder::kBoolean:
      return value.boolean_value ? @YES : @NO;
    case TypeOrder::kNumber:
      return value.which_value_type == google_firestore_v1_Value_integer_value_tag
                 ? @(value.integer_value)
                 : @(value.double_value);
    case TypeOrder::kString:
      return MakeNSString(MakeStringView(value.string_value));
    case TypeOrder::kBlob:
      return MakeNSData(value.bytes_value);  // <<============= Here: value.bytes_value is nil
    case TypeOrder::kGeoPoint:
      return MakeFIRGeoPoint(
          GeoPoint(value.geo_point_value.latitude, value.geo_point_value.longitude));
    case TypeOrder::kMaxValue:
      // It is not possible for users to construct a kMaxValue manually.
      break;
  }

  UNREACHABLE();
}
```

### Reproducing the issue

Store a document with a null Blob field. Now read it.

### Firebase SDK Version

10.12

### Xcode Version

14.2

### Installation Method

CocoaPods

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

N/A

### If using CocoaPods, the project's Podfile.lock

N/A

**Comment by ehsannas** [comment]
thanks for reporting @harry-dickson . I'll take a look

**Comment by ehsannas** [comment]
@harry-dickson , can you please share the code snippet you're using to store and read back the null blob?

I expected a field value of null to fall under
```
    case TypeOrder::kNull:
      return [NSNull null];
```

**Comment by harry-dickson** [comment]
I'll take a closer look tomorrow, but it's Flutter/Dart and I believe it's set though an update:
```dart
  DocumentRef<Stuff> ref;
  ref.update({"blob": null});
```
I think I can prevent this in the case of null as a workaround - and fix the handful of broken documents 
(the field is an optional, encoded profile picture)

The read is coming through a subscription: 
```dart
  DocumentRef<Stuff> ref;
  ref.snapshots().listen(...)
```
The initial load that's triggered by the listen causes the crash before it gets near the flutter code.

**Comment by harry-dickson** [comment]
> I'll take a closer look tomorrow, but it's Flutter/Dart and I believe it's set though an update:
> ... 
> 
> The initial load that's triggered by the listen causes the crash before it gets near the flutter code.

That's not right. If it is null in the source, it is simply omitted in the Map provided to the update. 
It can be an empty byte array however. Is it possible the Blob handling would transmute that into a null?

It seems plausible from a simple text search in xcode: 

`nanopb_utils.cc`:
```c++
pb_bytes_array_t* _Nullable MakeBytesArray(const void* _Nullable data,
                                           size_t size) {
  if (size == 0) return nullptr;

  // Handle non-empty data...
}
```

Called from MakeByteString() nanopb_util.h line 170
Called from parseScalarValue() FSTUserDataReader.mm line 519

```obj-c
  } else if ([input isKindOfClass:[NSData class]]) {
    NSData *inputData = input;
    return [self encodeBlob:(nanopb::MakeByteString(inputData))];
  }
```
I will try and stop writing empty arrays in my code as a workaround.

**Comment by harry-dickson** [comment]
I also get this crash for data that looks like this in the firebase console:

```
  foo: "value"         (string)
  bar: 99              (number)
  blob:                (blob)
```
And not just:

```
  foo: "text"          (string)
  bar: 37              (number)
  blob: null           (blob)
```
That is, the field is present, but void/empty. 
Not quite sure how/when I store null vs void

**Comment by harry-dickson** [comment]
Something did change back in May/June time: firebase/flutterfire#11096
I ended up staring at the same code then: FSTUserDataReader/Writer.

**Comment by tom-andersen** [comment]
Fix will be part of next release.
