### ISSUE TITLE
Failed to initiate on-device conversion measurement - GoogleAppMeasurementOnDeviceConversion dependency not linked in.

### ISSUE THREAD

**Issue by ChanBasha-MSIL** [firebase/firebase-ios-sdk#11787]
### Description

I have installed Firebase SDK through cocoapods and its version is 10.5.0 , followed the all the steps mentioned here https://firebase.google.com/docs/tutorials/ads-ios-on-device-measurement/step-1 .
Still facing the issue and getting this log from the console . Have added flags as well in build settings 
<img width="678" alt="Screenshot 2023-09-08 at 9 13 52 AM" src="https://github.com/firebase/firebase-ios-sdk/assets/92305363/1490236e-3bf6-498b-b31c-206e6cff8db2">

Getting following log  from console

<img width="888" alt="Screenshot 2023-09-07 at 12 59 19 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/92305363/a476b5db-62fd-455a-86a2-36da98e45410">

Expected output is [FirebaseAnalytics][I-ACS023229] On-device conversion measurement found a match

### Firebase SDK Version

10.5

### Xcode Version

14.3.1

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using CocoaPods, the project's Podfile.lock

 - Firebase/Analytics (10.5.0):
    - Firebase/Core
  - Firebase/Core (10.5.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 10.5.0)
  - Firebase/CoreOnly (10.5.0):
    - FirebaseCore (= 10.5.0)
  - Firebase/Crashlytics (10.5.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 10.5.0)
  - Firebase/DynamicLinks (10.5.0):
    - Firebase/CoreOnly
    - FirebaseDynamicLinks (~> 10.5.0)
  - Firebase/Messaging (10.5.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 10.5.0)
  - Firebase/Performance (10.5.0):
    - Firebase/CoreOnly
    - FirebasePerformance (~> 10.5.0)
  - Firebase/RemoteConfig (10.5.0):
    - Firebase/CoreOnly
    - FirebaseRemoteConfig (~> 10.5.0)
  - FirebaseABTesting (10.14.0):
    - FirebaseCore (~> 10.0)
  - FirebaseAnalytics (10.5.0):
    - FirebaseAnalytics/AdIdSupport (= 10.5.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - GoogleUtilities/Network (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (10.5.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleAppMeasurement (= 10.5.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - GoogleUtilities/Network (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseAuth (10.5.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/Environment (~> 7.8)
    - GTMSessionFetcher/Core (< 4.0, >= 2.1)
  - FirebaseCore (10.5.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Logger (~> 7.8)
  - FirebaseCoreInternal (10.14.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseCrashlytics (10.5.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.8)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (~> 2.1)
  - FirebaseDynamicLinks (10.5.0):
    - FirebaseCore (~> 10.0)
  - FirebaseInstallations (10.14.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)
  - FirebaseMessaging (10.5.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Reachability (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebasePerformance (10.5.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - FirebaseRemoteConfig (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/ISASwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseRemoteConfig (10.5.0):
    - FirebaseABTesting (~> 10.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - Flutter (3.7.1200)
  - FlutterLibraryDebug (0.0.245)
  - FSCalendar (2.8.4)
  - GoogleAppMeasurement (10.5.0):
    - GoogleAppMeasurement/AdIdSupport (= 10.5.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - GoogleUtilities/Network (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/AdIdSupport (10.5.0):
    - GoogleAppMeasurement/WithoutAdIdSupport (= 10.5.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - GoogleUtilities/Network (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/WithoutAdIdSupport (10.5.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - GoogleUtilities/Network (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleDataTransport (9.2.5):
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/AppDelegateSwizzler (7.11.5):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (7.11.5):
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/ISASwizzler (7.11.5)
  - GoogleUtilities/Logger (7.11.5):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (7.11.5):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (7.11.5):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.11.5)"
  - GoogleUtilities/Reachability (7.11.5):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (7.11.5):
    - GoogleUtilities/Logger
  - GTMSessionFetcher/Core (3.1.1)

**Comment by rizafran** [comment]
Thanks for reporting, @ChanBasha-MSIL. Based on your `Podfile.lock`, it seems that `FirebaseAnalyticsOnDeviceConversion` is missing, which is needed to integrate as mentioned on the [docs](https://firebase.google.com/docs/tutorials/ads-ios-on-device-measurement/step-2#integrate_the_for_firebase_sdk). Could you try adding `FirebaseAnalyticsOnDeviceConversion` in your pods and see if the issue will persist?
