### ISSUE TITLE
Error saving test devices: The provided token is invalid

### ISSUE THREAD

**Issue by Noothan-am** [firebase/firebase-ios-sdk#11805]
### Description

when i tried to send notification from firebase it throws error, even I tried with new token. but it didn't work error.  

### Reproducing the issue

![image](https://github.com/firebase/firebase-ios-sdk/assets/100135382/2b640caf-21a1-42a0-beef-8cd564e9245c)

### Firebase SDK Version

-

### Xcode Version

-

### Installation Method

Swift Package Manager

### Firebase Product(s)

Messaging

### Targeted Platforms

All

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reaching out, @Noothan-am. For console-related issues, please file a ticket through our [support channel](https://firebase.google.com/support) so the team would be able to check what's causing the issue in the backend.
