### ISSUE TITLE
Ignoring duplicate libraries: '-lc++', '-lsqlite3', '-lz'

### ISSUE THREAD

**Issue by gpfister-oskey** [firebase/firebase-ios-sdk#11818]
### Description

On Xcode 15 RC, when building an app using firebase-ios-sdk 10.15.0, a warning is raised on duplicated libraries:

```
Ignoring duplicate libraries: '-lc++', '-lsqlite3', '-lz'
```

### Reproducing the issue

Build any project that requires Firebase

### Firebase SDK Version

10.15.0

### Xcode Version

15.0 RC

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, App Check, Authentication, Crashlytics, Firestore, Functions, Storage

### Targeted Platforms

iOS

### Relevant Log Output

```shell
ld: warning: ignoring duplicate libraries: '-lc++', '-lsqlite3', '-lz'
```
```


### If using Swift Package Manager, the project's Package.resolved

<!--- Look below for instructions on how to share your Package.resolved. --->

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

The package inside another swift package (which contains the whole Cloud API of the app.

```swift
// swift-tools-version:5.8.1

import PackageDescription

let package = Package(
    name: "CloudKit",
    platforms: [.iOS(.v15), .macOS(.v12), .watchOS(.v8)],
    products: [
        .library(
            name: "CloudKit",
            targets: ["CloudKit"]
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/firebase/firebase-ios-sdk.git", .upToNextMajor(from: "10.15.0")),
    ],
    targets: [
        .target(
            name: "CloudKit",
            dependencies: [
                .product(name: "FirebaseAnalytics", package: "firebase-ios-sdk", condition: .when(platforms: [.iOS, .macOS])),
                .product(name: "FirebaseAppCheck", package: "firebase-ios-sdk", condition: .when(platforms: [.iOS, .macOS])),
                .product(name: "FirebaseAuth", package: "firebase-ios-sdk"),
                .product(name: "FirebaseCrashlytics", package: "firebase-ios-sdk", condition: .when(platforms: [.iOS, .macOS])),
                .product(name: "FirebaseFunctions", package: "firebase-ios-sdk"),
                .product(name: "FirebaseFirestore", package: "firebase-ios-sdk", condition: .when(platforms: [.iOS, .macOS])),
                .product(name: "FirebaseFirestoreSwift", package: "firebase-ios-sdk", condition: .when(platforms: [.iOS, .macOS])),
                .product(name: "FirebaseStorage", package: "firebase-ios-sdk"),
            ]
        ),
        .testTarget(
            name: "CloudKitTests",
            dependencies: [
                "CloudKit",
            ]
        ),
    ]
)
```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by morganchen12** [comment]
Can you share the whole build log?

**Comment by paulb777** [comment]
I can reproduce this.  I'm not sure we'll be able to fix in the near term, since we want to continue to support Xcode 14 as long as the App Store supports it. (Spring 2024)

**Comment by gpfister** [comment]
@paulb777 It will be a problem for those that configured `ld` to turn warnings into errors (I'm not one of those).

**Comment by jakedunc** [comment]
Can always trust Firebase to not be ready for a new Xcode version... surely this was known ahead of time with the beta and RC's being available for so long? Nothing worse than warnings in a project that can't be fixed...

**Comment by paulb777** [comment]
To reiterate, the reason this issue wasn't addressed was not that we didn't know about it. We haven't yet found a solution that enables us to still support Xcode 14 developers. Open to suggestions.

**Comment by jakedunc** [comment]
Could we have a version we could manually point to for now, for XCode 15 specifically, until the issue is properly addressed?

**Comment by ricky-stone** [comment]
> For anyone needing to silence this warning in their project you can update OTHER_LDFLAGS in your build settings to include `-Xlinker -no_warn_duplicate_libraries`
> 
> <img alt="Screenshot 2023-09-20 at 1 29 08 PM" width="585" src="https://user-images.githubusercontent.com/8225090/269369409-5ba4a7a7-56af-4c45-ac49-e21d0fc00dd0.png">

Thank you! Nothing worse than seeing that hazard sign!

**Comment by martinni87** [comment]
Hi. Same issue but I found this on homebrew github: https://github.com/orgs/Homebrew/discussions/4794

Adding '-Wl,-ld_classic' in "Other Linker Flags" worked for me.

![image](https://github.com/firebase/firebase-ios-sdk/assets/30123957/12b09a2f-dbcd-47a2-b3b4-dbf9270bd24b)

**Comment by allenhumphreys** [comment]
That fundamentally changes the build to use the old linker I believe.

**Comment by hoangquangbao** [comment]
> > -Xlinker -no_warn_duplicate_libraries
> 
> FYI, Not working
> 
> > Hi. Same issue but I found this on homebrew github: https://github.com/orgs/Homebrew/discussions/4794
> > Adding '-Wl,-ld_classic' in "Other Linker Flags" worked for me.
> > ![image](https://user-images.githubusercontent.com/30123957/273399009-12b09a2f-dbcd-47a2-b3b4-dbf9270bd24b.png)
> 
> And, Thanks @martinni87 ,
> 
> > '-Wl,-ld_classic'
> 
> This work for me. Thanks for the solution. XCode: Version 15.0 (15A240d) Mac mini 2023: Sonoma 14.0 (23A344)

@mparmar-covantex 
2 solutions not working for me. 
Clean Build, Pod update, reopen Xcode,.. still get a warning: FirebaseCrashlytics - ignoring duplicate libraries: '-lc++’
Does anyone know any other solutions?

**Comment by yosi199** [comment]
> That fundamentally changes the build to use the old linker I believe.

how does this affect the linking process? is this something I should avoid

**Comment by edutgn75** [comment]
Same problem... 
Ignoring duplicate libraries: '-lc++', '-lsqlite3', '-lz'
With XCODE 15.0 and Sonoma 14.0

**Comment by allenhumphreys** [comment]
> That fundamentally changes the build to use the old linker I believe.

@yosi199 I should've elaborated. With Xcode 15, Apple re-wrote the linker. From the WWDC 2023 state of the union:
> The linker has been redesigned from the ground up, bringing massive improvements in link speed.

They didn't get rid of the old linker, though. You can still use it by providing the flag `-ld_classic`.

All of this stuff is in the `ld` man page on macOS. Just do `man ld` in terminal. That's actually how I found the flag I used.

<img width="598" alt="Screenshot 2023-10-24 at 4 06 03 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/8225090/7955191c-f320-4ef9-b6f1-6f78a0da9c2b">

**Comment by PatrickGaissert** [comment]
We also have the issue with library version 10.16.0. Ignoring the duplicate libraries warning helped for now.

**Comment by mcat345** [comment]
so how critical this is? can it be ignored?

**Comment by allenhumphreys** [comment]
> so how critical this is? can it be ignored?

As far as I understand it, nothing has changed. The libraries were passed into the linker multiple times before Xcode 15. They just added a warning in the new linker.

**Comment by emarashliev** [comment]
> > so how critical this is? can it be ignored?
> 
> As far as I understand it, nothing has changed. The libraries were passed into the linker multiple times before Xcode 15. They just added a warning in the new linker.

But it shouldn't be fixed? I mean it seems at least inefficient, and this will affect negatively the compile time.

**Comment by paulb777** [comment]
After some investigation, we can only partly address this, since it's fundamentally an Apple bug. One example that if you link two different libraries that include C++, Apple's tools will add multiple `-lc++` options to the link command. As a result, we're going to close and recommend following up with Apple on the issue.

The workaround from @allenhumphreys of `-Xlinker -no_warn_duplicate_libraries` is recommended while the issue remains outstanding in Apple's tools.

More context at https://indiestack.com/2023/10/xcode-15-duplicate-library-linker-warnings/

**Comment by allenhumphreys** [comment]
That's entirely reasonably. We shouldn't forget that these flags didn't change, the linker's reaction to emit a warning changed. I've been seeing duplicate -lc++ in build logs for 10 years.

**Comment by YahefuYusufu** [comment]
Hi, thanks for useful info,
i have a question, why i can not find (Other-links-flag) in my Build Setting ?

**Comment by dhamodharan-b** [comment]
> https://github.com/apple/swift-protobuf

What is the fix for this?

**Comment by dhamodharan-b** [comment]
> ### Description
> On Xcode 15 RC, when building an app using firebase-ios-sdk 10.15.0, a warning is raised on duplicated libraries:
> 
> ```
> Ignoring duplicate libraries: '-lc++', '-lsqlite3', '-lz'
> ```
> 
> ### Reproducing the issue
> Build any project that requires Firebase
> 
> ### Firebase SDK Version
> 10.15.0
> 
> ### Xcode Version
> 15.0 RC
> 
> ### Installation Method
> Swift Package Manager
> 
> ### Firebase Product(s)
> Analytics, App Check, Authentication, Crashlytics, Firestore, Functions, Storage
> 
> ### Targeted Platforms
> iOS
> 
> ### Relevant Log Output
> ```shell
> ld: warning: ignoring duplicate libraries: '-lc++', '-lsqlite3', '-lz'
> ```
> 
> ```
> 
> 
> ### If using Swift Package Manager, the project's Package.resolved
> 
> 
> 
> <details>
> <summary>Expand <code>Package.resolved</code> snippet</summary>
> <br>
> 
> The package inside another swift package (which contains the whole Cloud API of the app.
> 
> ```swift
> // swift-tools-version:5.8.1
> 
> import PackageDescription
> 
> let package = Package(
>     name: "CloudKit",
>     platforms: [.iOS(.v15), .macOS(.v12), .watchOS(.v8)],
>     products: [
>         .library(
>             name: "CloudKit",
>             targets: ["CloudKit"]
>         ),
>     ],
>     dependencies: [
>         .package(url: "https://github.com/firebase/firebase-ios-sdk.git", .upToNextMajor(from: "10.15.0")),
>     ],
>     targets: [
>         .target(
>             name: "CloudKit",
>             dependencies: [
>                 .product(name: "FirebaseAnalytics", package: "firebase-ios-sdk", condition: .when(platforms: [.iOS, .macOS])),
>                 .product(name: "FirebaseAppCheck", package: "firebase-ios-sdk", condition: .when(platforms: [.iOS, .macOS])),
>                 .product(name: "FirebaseAuth", package: "firebase-ios-sdk"),
>                 .product(name: "FirebaseCrashlytics", package: "firebase-ios-sdk", condition: .when(platforms: [.iOS, .macOS])),
>                 .product(name: "FirebaseFunctions", package: "firebase-ios-sdk"),
>                 .product(name: "FirebaseFirestore", package: "firebase-ios-sdk", condition: .when(platforms: [.iOS, .macOS])),
>                 .product(name: "FirebaseFirestoreSwift", package: "firebase-ios-sdk", condition: .when(platforms: [.iOS, .macOS])),
>                 .product(name: "FirebaseStorage", package: "firebase-ios-sdk"),
>             ]
>         ),
>         .testTarget(
>             name: "CloudKitTests",
>             dependencies: [
>                 "CloudKit",
>             ]
>         ),
>     ]
> )
> ```
> 
> ### If using CocoaPods, the project's Podfile.lock
> Expand `Podfile.lock` snippet

@gpfister-oskey am not getting what is the fix for this?
