### ISSUE TITLE
Runtime warning in FPRNSURLSessionInstrument when running on iOS 17 RC built with Xcode 15 RC

### ISSUE THREAD

**Issue by TAATHub** [firebase/firebase-ios-sdk#11821]
### Description

Similar to https://github.com/firebase/firebase-ios-sdk/issues/11536, a runtime warning as below occurs when running on iOS 17 RC built with Xcode 15 RC.

Warning:
```
The request of a upload task should not contain a body or a body stream, use `upload(for:fromFile:)`, `upload(for:from:)`, or supply the body stream through the `urlSession(_:needNewBodyStreamForTask:)` delegate method.
```
Code:
```c
/** Instruments -uploadTaskWithRequest:fromData:.
 *
 *  @param instrument The FPRNSURLSessionInstrument instance.
 *  @param instrumentor The FPRClassInstrumentor to add the selector instrumentor to.
 */
FOUNDATION_STATIC_INLINE
NS_EXTENSION_UNAVAILABLE("Firebase Performance is not supported for extensions.")
void InstrumentUploadTaskWithRequestFromData(FPRNSURLSessionInstrument *instrument,
                                             FPRClassInstrumentor *instrumentor) {
    ...
    NSURLSessionUploadTask *uploadTask =
        ((OriginalImp)currentIMP)(session, selector, request, bodyData); // This line causes the warning
    if (uploadTask.originalRequest) {
      FPRNetworkTrace *trace =
          [[FPRNetworkTrace alloc] initWithURLRequest:uploadTask.originalRequest];
      [trace start];
      trace.requestSize = bodyData.length;
      [trace checkpointState:FPRNetworkTraceCheckpointStateInitiated];
      [FPRNetworkTrace addNetworkTrace:trace toObject:uploadTask];
    }
    return uploadTask;
  }];
}
```

### Reproducing the issue

Run an app and check the runtime warnings on Xcode.

### Firebase SDK Version

10.9.0 (also occurred with 10.15.0)

### Xcode Version

15.0 (15A240d)

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, App Distribution, Authentication, Crashlytics, DynamicLinks, Performance

### Targeted Platforms

iOS

### Relevant Log Output

```shell
The request of a upload task should not contain a body or a body stream, use `upload(for:fromFile:)`, `upload(for:from:)`, or supply the body stream through the `urlSession(_:needNewBodyStreamForTask:)` delegate method.
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by TAATHub** [comment]
![runtime_warning](https://github.com/firebase/firebase-ios-sdk/assets/83394375/6689c83e-d64d-46d8-a0d3-cb4ad2d93080)

**Comment by UjjwalNepal** [comment]
Yeah same on ios 17.0

**Comment by skywalkerlw** [comment]
I can see exactly the same warning here.
App crash rating increases, not sure related to it or not.

<img width="488" alt="image" src="https://github.com/firebase/firebase-ios-sdk/assets/2090084/632151ad-5c50-442c-bdc3-14d98c4cbd9a">

**Comment by paulb777** [comment]
@skywalkerlw The fix is staged for our next 10.16.0 release planned for next week.

**Comment by garethlloyd1994** [comment]
We are still seeing this warning in 10.16.0 - did the fix get released with this change?

![Screenshot 2023-10-06 at 4 30 36 pm](https://github.com/firebase/firebase-ios-sdk/assets/122424426/7af2cdc5-a55b-4d28-8a96-c10e8867cbc0)
![Screenshot 2023-10-06 at 4 30 27 pm](https://github.com/firebase/firebase-ios-sdk/assets/122424426/d0d432fb-f542-4670-85a8-d3d8c37d8cdd)

**Comment by paulb777** [comment]
The fix got deployed in the `InstrumentUploadTaskWithRequestFromData` function, but it looks like the same issue is still in `InstrumentUploadTaskWithStreamedRequest`.

thanks for the report. We'll put this on this list for the next release.
