### ISSUE TITLE
persistentCacheIndexManager in Firebase Firestore Swift

### ISSUE THREAD

**Issue by SamipflightXplorer** [firebase/firebase-ios-sdk#11820]
### Description

persistentCacheIndexManager warning for FirebaseFirestoreSwift 

### Reproducing the issue

Yellow warning on Xcode when compiling project. When removing FirebaseFirestoreSwift library from project, error disappears. Tried it with a new project and warning persists. Installed only FirebaseFirestoreSwift and warning still there .

### Firebase SDK Version

10.15.0

### Xcode Version

14.3.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

### Relevant Log Output

```shell
ld: warning: method '-persistentCacheIndexManager' in category from /Users/XXX/Library/Developer/Xcode/DerivedData/XXX/Build/Products/Debug-iphonesimulator/FirebaseFirestore.framework/FirebaseFirestore(FIRFirestore.o) overrides method from class in /Users/XXX/Library/Developer/Xcode/DerivedData/XXX/Build/Products/Debug-iphonesimulator/FirebaseFirestore.framework/FirebaseFirestore(FIRFirestore.o)
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by sonnv106** [comment]
I also had the same problem

**Comment by SamipflightXplorer** [comment]
I did get the issue fixed by updating to newest macOS and Xcode. I don't get that error. Maybe try that and see if that helps you.

**Comment by paulb777** [comment]
OK, I'll close. Please comment or open a new issue if it shows up on Firebase 10.17.0 or later.
