### ISSUE TITLE
Restore check_framework_firestore_symbols tests

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#11849]
### Description

Disabled test after it caused failure in #11848 because of #11846. The test depends on SPM and CocoaPods using the same gRPC version.

We should get the versions re-aligned and restore this test before adding too many other Firestore changes since we don't have thorough SPM testing.

### Reproducing the issue

Nightly zip tests

### Firebase SDK Version

10.16

### Xcode Version

14.2

### Installation Method

Zip

### Firebase Product(s)

Firestore

### Targeted Platforms

All

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by dconeybe** [comment]
@paulb777 Should we just downgrade SPM as well as CocoaPods then? Otherwise, it is unknown when we can get SPM and CocoaPods grpc versions back in sync because there are some issues with upgrading to the latest grpc version: something to do with linking problems and cyclic header dependencies (@wu-hui is looking into this).

**Comment by paulb777** [comment]
Good point, but I think downgrading in a short time period is more risky than keeping SPM stable.

I see some inconsistencies with abseil dependencies that should be sorted out. If we can't upgrade gRPC in the M139 timeframe, let's work through pulling it back then.

**Comment by paulb777** [comment]
Our podspecs (and Package.swift) are already defined to allow patch dependency updates, so developers would need to run `pod update` to get the fix.

**Comment by paulb777** [comment]
It's normal workflow for CocoaPods users wanting to update to newer versions.
