### ISSUE TITLE
FirebaseFunctions.podspec is missing the public_header_files entry

### ISSUE THREAD

**Issue by nbransby** [firebase/firebase-ios-sdk#11862]
### Description

The [FirebaseFunctions.podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/c/5/4/FirebaseFunctions/10.5.0/FirebaseFunctions.podspec.json) is missing the `public_header_files` entry when compared to [Firestore](https://github.com/CocoaPods/Specs/blob/master/Specs/0/9/f/FirebaseFirestore/10.5.0/FirebaseFirestore.podspec.json#L24C4-L24C23).

Im assuming this is why I can't reference the Functions error code enum/consts while in Firestore I can.

### Firebase SDK Version

10.5.0

### Xcode Version

N/A

### Installation Method

CocoaPods

### Firebase Product(s)

Functions

### Targeted Platforms

All

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
FirebaseFunctions is implemented in Swift, so there is no reason to specify public headers.  Public error codes are defined in https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseFunctions/Sources/FunctionsError.swift.

What is the problem?

**Comment by nbransby** [comment]
I see, issue is with using FirebaseFunction from https://github.com/GitLiveApp/firebase-kotlin-sdk, we can't 'see' these definitions from kotlin but we can see the identical one from firestore presumably because they are defined in good ol' objective c and the kotlin cinterop doesn't play so nicely with swift

**Comment by paulb777** [comment]
Thanks for the follow up. I recommend following up in a Kotlin channel, especially since Firebase will increasingly be implemented in Swift going forward.
