### ISSUE TITLE
After updating to 10.15 firebase Storage can not download more then 370 files in one go

### ISSUE THREAD

**Issue by Granluke** [firebase/firebase-ios-sdk#11870]
### Description

I have a loop that iterates through images to download (calls the function that is shown below). Before updating to 10.15.0 (I was on 9.6) there was no problem in downloading all the images (very small sizes 10kb) ~1000 images.  Now I get only aroung 370 images at once before having to manually start over or crashing the app.

```
func download_pic_firebase(key: String, vc: StartViewController) {

    let storage = Storage.storage(url: getStorageURL())
    let storageRef = storage.reference()

    let imageRef = storageRef.child("img/" + key + ".png")
    
    print("Start Downloading", key)
    
    // Create local filesystem URL

    let documentsURL = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!
    let localURL = documentsURL.appendingPathComponent(key + ".png")
    let filePath = localURL.path
    let fileManager = FileManager.default
    if fileManager.fileExists(atPath: filePath) {
        print("downloaded Already", key)
        vc.counter += 1
        vc.countLabel.text = "Downloaded:" + String(vc.counter) + "/" + String(vc.counter2)
        if vc.counter == vc.counter2 {
            vc.downloadingInProgress = false
            vc.download_ended()
        }
    } else {
        let downloadTask = imageRef.write(toFile: localURL)
        downloadTask.observe(.progress) { snapshot in
            // Download reported progress
            let percentComplete = 100.0 * Double(snapshot.progress!.completedUnitCount)
                / Double(snapshot.progress!.totalUnitCount)
            vc.countLabel.text = "Downloaded:" + String(vc.counter) + "/" + String(vc.counter2)
            // Update the progress indicator
            vc.progressView.progress = Float(percentComplete)/100.0
            vc.progressLabel.text = String(percentComplete.rounded()) + "% / 100%"
        }

        downloadTask.observe(.success) { _ in
            // Download completed successfully
            vc.counter += 1
            print("successfully downloaded", key)
            if vc.counter == vc.counter2 {
                vc.downloadingInProgress = false
                vc.download_ended()
            }

        }
        // Errors only occur in the "Failure" case
        downloadTask.observe(.failure) { snapshot in
            // An error occurred!
            print("error downloading", key)
            vc.counter += 1
            if vc.counter == vc.counter2 {
                vc.downloadingInProgress = false
                vc.download_ended()
            }
        }
    }

}
```

### Reproducing the issue

Restarting the app downloads or continuing them manually with a button after a while. 

### Firebase SDK Version

10.15.0

### Xcode Version

15.0

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication, Crashlytics, Database, Storage

### Targeted Platforms

iOS, macOS, macCatalyst

### If using Swift Package Manager, the project's Package.resolved

{
  "pins" : [
    {
      "identity" : "abseil-cpp-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/abseil-cpp-binary.git",
      "state" : {
        "revision" : "bfc0b6f81adc06ce5121eb23f628473638d67c5c",
        "version" : "1.2022062300.0"
      }
    },
    {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk",
      "state" : {
        "revision" : "8a8ec57a272e0d31480fb0893dda0cf4f769b57e",
        "version" : "10.15.0"
      }
    },
    {
      "identity" : "googleappmeasurement",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleAppMeasurement.git",
      "state" : {
        "revision" : "03b9beee1a61f62d32c521e172e192a1663a5e8b",
        "version" : "10.13.0"
      }
    },
    {
      "identity" : "googledatatransport",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleDataTransport.git",
      "state" : {
        "revision" : "5056b15c5acbb90cd214fe4d6138bdf5a740e5a8",
        "version" : "9.2.0"
      }
    },
    {
      "identity" : "googleutilities",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleUtilities.git",
      "state" : {
        "revision" : "871d43135925cde39ef7421d8723ce47edfdcc39",
        "version" : "7.11.1"
      }
    },
    {
      "identity" : "grpc-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/grpc-binary.git",
      "state" : {
        "revision" : "f1b366129d1125be7db83247e003fc333104b569",
        "version" : "1.50.2"
      }
    },
    {
      "identity" : "gtm-session-fetcher",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/gtm-session-fetcher.git",
      "state" : {
        "revision" : "5ccda3981422a84186387dbb763ba739178b529c",
        "version" : "2.3.0"
      }
    },
    {
      "identity" : "inputbaraccessoryview",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/nathantannar4/InputBarAccessoryView",
      "state" : {
        "revision" : "e5da8c5e3c6ff2740ec2b721dd71e2cf24053001",
        "version" : "6.1.0"
      }
    },
    {
      "identity" : "interop-ios-for-google-sdks",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/interop-ios-for-google-sdks.git",
      "state" : {
        "revision" : "2d12673670417654f08f5f90fdd62926dc3a2648",
        "version" : "100.0.0"
      }
    },
    {
      "identity" : "leveldb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/leveldb.git",
      "state" : {
        "revision" : "0706abcc6b0bd9cedfbb015ba840e4a780b5159b",
        "version" : "1.22.2"
      }
    },
    {
      "identity" : "messagekit",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/MessageKit/MessageKit",
      "state" : {
        "revision" : "77695e1a2001288a903d1fa2c1c72214b018f070"
      }
    },
    {
      "identity" : "nanopb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/nanopb.git",
      "state" : {
        "revision" : "819d0a2173aff699fb8c364b6fb906f7cdb1a692",
        "version" : "2.30909.0"
      }
    },
    {
      "identity" : "promises",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/promises.git",
      "state" : {
        "revision" : "3e4e743631e86c8c70dbc6efdc7beaa6e90fd3bb",
        "version" : "2.1.1"
      }
    },
    {
      "identity" : "swift-protobuf",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-protobuf.git",
      "state" : {
        "revision" : "fa0fcd43f272a260e7f734f23e6dc55e16fcae0a",
        "version" : "1.19.1"
      }
    },
    {
      "identity" : "typesense-swift",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/typesense/typesense-swift",
      "state" : {
        "branch" : "master",
        "revision" : "5805d864429e2c28c7949081b6cc029916b7831c"
      }
    }
  ],
  "version" : 2
}

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by morganchen12** [comment]
What crash do you get?

**Comment by Granluke** [comment]
None, that is the weird thing. I reproduced the issue on 3 different apps. With firebase 9.6.0 it was ok, with 10.15.0 it stopped working after updating firebase via the spm. I tried removing and adding firebase storage, still the same. 
In the files I am trying to download some of them are not available in storage so I get a 404 (which is expected) can it be that the connection times out/cuts off after I have a couple of 404s? 
In the firebase storage usage I also only get the around 360 downloads, and none of the other "triggerd" downloads appear there. not as blocked and not as a connection at all, even though they are triggered (verified through the logs)

**Comment by Granluke** [comment]
Any updated here? I am getting issues with uploading to the appstore because the download process gets stuck and the app is not getting approved.

**Comment by rizafran** [comment]
Sorry for the late revert, @Granluke. Could you provide a sample app that reproduces the issue to investigate what's causing it? Thanks.

**Comment by Brooksie18** [comment]
Having problems with keyboard not suggesting the right auto fill on clipboard. Having to click letters 2 times to get it respond.
  Still getting aggressive text messages complying that I have miraculous files or app to immediately take action. 
 Got text message in sting on the camera is infected and data leak remove or risk data leakage. 
   Siri isn't working properly.  Doesn't respond to voice recognition, doesn't come to screen when addressed. 
 Google chrome is crashing and iOS has crashed 2 times today to my knowledge.
