### ISSUE TITLE
Anonymous Auth Verify Can't Connect Account for Email / Password

### ISSUE THREAD

**Issue by mikaelacaron** [firebase/firebase-ios-sdk#11911]
### Description

# Expected
Using Firebase anonymous authentication, and allowing a user to sign up with email / password to create their "permanent account"

# Actual
Using Firebase anonymous authentication I am able to have an anonymous user, but then using Email / Password sign up and connecting the anonymous user to this info, it fails with the error "Please verify the new email before changing email"

### Reproducing the issue

I was mostly following this example Firebase code, the `auth-account-linking` example, but when trying to sign in I would get the error "Please verify the new email before changing email" Sorry I don't have a full test project at the moment.

I was only doing anonymous auth and Email / password, not using Sign in With Apple or Google

[Favourites.zip](https://github.com/firebase/firebase-ios-sdk/files/12838400/Favourites.zip)

### Firebase SDK Version

10.15

### Xcode Version

15.0

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
See #11886 for a duplicate, explanation and workaround.

I'll leave this issue open to track updating the samples.

**Comment by paulb777** [comment]
Reopened since #11925 was reverted.
