### ISSUE TITLE
Issue not reolved

### ISSUE THREAD

**Issue by pandashashwat97** [firebase/firebase-ios-sdk#11944]
On Updating the version to 10.16.0 - 11.0.0
many other dependencies are starting to go missing.
![image](https://user-images.githubusercontent.com/82383705/275224890-dcb63e56-2920-44f6-8fe2-def1d7f0b464.png)

**Comment by ncooke3** [comment]
Hi @pandashashwat97, have you tried resetting Xcode's package caches?

In Xcode, go to File → Packages → Reset Package Caches

**Comment by pandashashwat97** [comment]
Hi @ncooke3 thank you so much

**Comment by pandashashwat97** [comment]
its resolved now
