### ISSUE TITLE
[FR]: FCM for macOS

### ISSUE THREAD

**Issue by nidegen** [firebase/firebase-ios-sdk#11964]
### Description

Pretty straightforward: Why can't we sent FCM to macOS? 

Is that a business decision or are there some technical limitations?

### API Proposal

Nothing would need to change as the API already exists for registering tokens:)

### Firebase Product(s)

Messaging

**Comment by paulb777** [comment]
According to https://firebase.google.com/docs/ios/learn-more#firebase_library_support_by_platform, FCM should work on macOS.  Do you have details on what is not working?

**Comment by nidegen** [comment]
I never get messages delivered and found this:
<img width="767" alt="Screenshot 2023-10-20 at 10 28 30" src="https://github.com/firebase/firebase-ios-sdk/assets/8779423/f9e23c47-ef7e-464f-90d2-62a183fd90ab">
https://stackoverflow.com/questions/68626936/integration-firebase-messaging-with-mac-os-apps-notifications

**Comment by andrewheard** [comment]
Hey @nidegen, have you tried integrating without using [method swizzling](https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in)? I didn't investigate deeply but my hypothesis is that we might only swizzle `application(_:didRegisterForRemoteNotificationsWithDeviceToken:)` in [`UIApplicationDelegate`](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622958-application) (macOS Catalyst) and not in [`NSApplicationDelegate`](https://developer.apple.com/documentation/appkit/nsapplicationdelegate/1428766-application) (macOS native).

The section "[Swizzling disabled: mapping your APNs token and registration token](https://firebase.google.com/docs/cloud-messaging/ios/client#token-swizzle-disabled)" also has more details about the setup process without swizzling.

**Comment by nidegen** [comment]
Not sure that is the issue. ` func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?) {` gets called anyways, so swizzling should work, right?

But even with manually registering (without swizzling) notifications do not arrive. That is, I did obtain a token, but sending any message to it does nothing on the receiving end.

**Comment by nidegen** [comment]
Nevermind, it did end up arriving after some delay!:)

**Comment by andrewheard** [comment]
@nidegen Just to clarify, did it work for you both with and without swizzling (after some delay)?

**Comment by nidegen** [comment]
Now I am confused. Trying to test it again this happened:

I was getting user notifications even after I uninstalled the app through a clean build (it disappeared from the push notification settings in system settings). So far so good.

But after re-building and launching the app (registration of token succeeds, it's actually still the same) I try to send a test message from the console again, but it never arrives. The app being running or not, it does not matter.

In the settings, permission are given for all like before I removed the app.

I do not have enough time to further investigate ATM unfortunately.

**Comment by nidegen** [comment]
Seems like at least one push not made it through after a lot of delay (5 mins? or even 15mins? not sure). 

Is the delay expected?

**Comment by andrewheard** [comment]
@nidegen Would you be willing to share your App Delegate? I tried to reproduce the issue with the following `NSApplicationDelegate` and notifications were delivered within seconds:

```
import AppKit
import FirebaseCore
import FirebaseMessaging
import UserNotifications

class AppDelegate: NSObject, NSApplicationDelegate {
  func applicationDidFinishLaunching(_ notification: Notification) {
    FirebaseApp.configure()

    Messaging.messaging().delegate = self

    UNUserNotificationCenter.current().delegate = self

    let authOptions: UNAuthorizationOptions = [.alert, .badge, .sound]
    UNUserNotificationCenter.current().requestAuthorization(
      options: authOptions,
      completionHandler: { _, _ in }
    )

    NSApplication.shared.registerForRemoteNotifications()
  }

  func application(_ application: NSApplication,
                   didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
    print("Registered for remote notifications.")

    // With swizzling disabled you must let Messaging know about the APNs token
    Messaging.messaging().apnsToken = deviceToken
  }

  func application(_ application: NSApplication,
                   didFailToRegisterForRemoteNotificationsWithError error: Error) {
    print("Failed to register for remote notifications: \(error)")
  }
}

extension AppDelegate: MessagingDelegate {
  func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?) {
    guard let fcmToken = fcmToken else {
      print("Invalid FCM token received.")
      return
    }

    print("FCM token: \(fcmToken)")
  }
}

extension AppDelegate: UNUserNotificationCenterDelegate {
  func userNotificationCenter(
    _ center: UNUserNotificationCenter,
    didReceive response: UNNotificationResponse
  ) async {
    let userInfo = response.notification.request.content.userInfo

    // Print message ID.
    if let messageID = userInfo["gcm.message_id"] {
      print("Message ID: \(messageID)")
    }

    // With swizzling disabled you must let Messaging know about the message
    Messaging.messaging().appDidReceiveMessage(userInfo)

    // Print full message.
    print(userInfo)
  }
}
```

This was in a macOS SwiftUI application with swizzling disabled (`FirebaseAppDelegateProxyEnabled` set to `NO` in the app's `Info.plist`).

**Comment by andrewheard** [comment]
> Maybe the SwiftUI lifecycle breaks it?

@nidegen This sounds quite plausible to me. Could you try moving the Firebase and APNs related code from `init()` to[ `applicationDidFinishLaunching(_:)`](https://developer.apple.com/documentation/appkit/nsapplicationdelegate/1428385-applicationdidfinishlaunching) in `AppDelegate`? I think it should look something like:

```
func applicationDidFinishLaunching(_ notification: Notification) {
  FirebaseApp.configure()
  registerForNotifications(application: NSApplication.shared)
  let center = UNUserNotificationCenter.current()
  center.removeAllDeliveredNotifications()
  requestNotificationPermission()
}
```
