### ISSUE TITLE
[FR]: Add CI to catch new public headers to Firestore

### ISSUE THREAD

**Issue by ncooke3** [firebase/firebase-ios-sdk#11971]
### Description

In #11954, the Firestore podspec was changed to include Swift code and headers that re-export public headers from an underlying FirebaseFirestoreInternal module. For each public header in the FirebaseFirestoreInternal module, there is a public header Firestore to export it. This can get out of sync so there are two options:

- Generate these re-exporting headers as a pre-build command
- Add a CI job to warn the PR author to add/remove a re-exporting header

### Firebase Product(s)

Firestore

**Comment by morganchen12** [comment]
We added a similar check to prevent new public headers not being correctly added to the umbrella header via Danger: https://github.com/firebase/firebase-ios-sdk/blob/master/Dangerfile#L204

Maybe this could be applicable here as well.
