### ISSUE TITLE
subs errorThe operation couldn’t be completed. No APNS token specified before fetching FCM Token

### ISSUE THREAD

**Issue by H0neyHunter** [firebase/firebase-ios-sdk#11984]
### Description

I get the following error when subscribing to version 10.16.0 Cloud messaging. This error does not occur in 10.11.0 and you can subscribe. Is there a problem in 10.16.0?

### Reproducing the issue

I get the following error when subscribing to version 10.16.0 Cloud messaging. This error does not occur in 10.11.0 and you can subscribe. Is there a problem in 10.16.0?

### Firebase SDK Version

10.16.0

### Xcode Version

15

### Installation Method

Swift Package Manager

### Firebase Product(s)

Messaging

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
@H0neyHunter FCM has only had minor changes in the version range and none of them would explain the issue you're seeing.

**Comment by H0neyHunter** [comment]
It’s definitely version-related. There is no issue with version 10.11.0, and furthermore, there is no issue with versions lower than 10.16.0.

**Comment by H0neyHunter** [comment]
> @H0neyHunter FCM has only had minor changes in the version range and none of them would explain the issue you're seeing.

It’s definitely version-related. There is no issue with version 10.11.0, and furthermore, there is no issue with versions lower than 10.16.0.

**Comment by H0neyHunter** [comment]
problem solution: FirebaseAppDelegateProxyEnabled true

**Comment by yunsanch** [comment]
i still this issue,  
`oh no erro to subscribe to topic Error Domain=com.google.fcm Code=505 "No APNS token specified before fetching FCM Token" UserInfo={NSLocalizedFailureReason=No APNS token specified before fetching FCM Token} 
Firebase registration token: Optional("dZv17moOFkY7sjURK1RBdo:APA91bEGorkt69KE2X80rkqvXv-ZcR0BNErdwadhvmIo7_IMD4gpY8ELcIVbquZ5MPz4cR1kmpN5Yx_Wm1W8Zhj1AMTy4OG03OC7ad6FOO8PUvUyX-SOwPHOQQxRpUFdNRqb0s_gK2rm")
2023-11-24 08:57:30.282690-0500 Tailored[8823:3717372] 10.17.0 - [FirebaseMessaging][I-FCM002010] The subscription operation failed due to an error getting the FCM token: Error Domain=com.google.fcm Code=505 "No APNS token specified before fetching FCM Token" UserInfo={NSLocalizedFailureReason=No APNS token specified before fetching FCM Token}.`


` final class AppDelegate: NSObject, UIApplicationDelegate {
    let gcmMessageIDKey = "gcm.message_id"
    lazy var synchronizationService = SynchronizationService()
    let networkService = NetworkMonitorService.shared // Use the shared instance
    var cancellables: Set<AnyCancellable> = []
    lazy var networkMonitor = NWPathMonitor()
    var timer: Timer?
    @Published var isConnected: Bool = false
//    private var backgroundTaskIdentifier: UIBackgroundTaskIdentifier = .invalid
       
    // Set this property to control internet simulation
        var simulateNoInternet: Bool = true

    
    func application(_ application: UIApplication,didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil ) -> Bool {


        configureFirebase()
        setupNetworkMonitoring()
       
        return true
    }
    func registerForRemoteNotifications() {
           UIApplication.shared.registerForRemoteNotifications()
       }
    
    func configureFirebase() {
        FirebaseApp.configure()
        
        // [START set_messaging_delegate]
           Messaging.messaging().delegate = self
           // [END set_messaging_delegate]
        // Register for remote notifications. This shows a permission dialog on first run, to
           // show the dialog at a more appropriate time move this registration accordingly.
           // [START register_for_notifications]

           UNUserNotificationCenter.current().delegate = self
        let authOptions: UNAuthorizationOptions = [.alert, .badge, .sound]
        
        UNUserNotificationCenter.current()
            .requestAuthorization(options: authOptions) { _, _ in
                
                
                }
        registerForRemoteNotifications()
        // [END register_for_notifications]

        Messaging.messaging().subscribe(toTopic: "tailored") { error in
            if let err = error {
                print("oh no erro to subscribe to topic \(err) ")
            } else {
                print("Subscribed to tailored topic")
            }
            
        }
    }
    
    func setupNetworkMonitoring() {
           networkService.$isConnected
               .sink { [weak self] isConnected in
                   self?.handleNetworkStatusChange(isConnected)
               }
               .store(in: &cancellables)
       }
       
       func handleNetworkStatusChange(_ isConnected: Bool) {
           print("Network status updated: \(isConnected ? "Connected" : "Disconnected")")
           if isConnected {
               BackEndFirebaseService.backgroundSync()
               self.synchronizationService.synchronizeWithFirebase()
           }
       }
     
    func application(_ application: UIApplication,
                     didReceiveRemoteNotification userInfo: [AnyHashable: Any]) {
      // If you are receiving a notification message while your app is in the background,
      // this callback will not be fired till the user taps on the notification launching the application.
      // TODO: Handle data of notification

      // With swizzling disabled you must let Messaging know about the message, for Analytics
      // Messaging.messaging().appDidReceiveMessage(userInfo)

      // Print message ID.
      if let messageID = userInfo[gcmMessageIDKey] {
        print("Message ID: \(messageID)")
      }

      // Print full message.
      print(userInfo)
    }
    
    // [START receive_message]
    func application(_ application: UIApplication,
                     didReceiveRemoteNotification userInfo: [AnyHashable: Any]) async
      -> UIBackgroundFetchResult {
      // If you are receiving a notification message while your app is in the background,
      // this callback will not be fired till the user taps on the notification launching the application.
      // TODO: Handle data of notification

      // With swizzling disabled you must let Messaging know about the message, for Analytics
      // Messaging.messaging().appDidReceiveMessage(userInfo)

      // Print message ID.
      if let messageID = userInfo[gcmMessageIDKey] {
        print("Message ID: \(messageID)")
      }

      // Print full message.
      print(userInfo)

      return UIBackgroundFetchResult.newData
    }

    // [END receive_message]

    func application(_ application: UIApplication,
                       didFailToRegisterForRemoteNotificationsWithError error: Error) {
        print("Unable to register for remote notifications: \(error.localizedDescription)")
      }

      // This function is added here only for debugging purposes, and can be removed if swizzling is enabled.
      // If swizzling is disabled then this function must be implemented so that the APNs token can be paired to
      // the FCM registration token.
      func application(_ application: UIApplication,
                       didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        print("APNs token retrieved: \(deviceToken)")

        // With swizzling disabled you must set the APNs token here.
        // Messaging.messaging().apnsToken = deviceToken
      }
    
    func fetchFCMToken() {
        Messaging.messaging().token { (token, error) in
            if let error = error {
                print("Error fetching FCM token: \(error.localizedDescription)")
            } else if let token = token {
                print("FCM token: \(token)")
            }
        }
    }

} `

` extension AppDelegate: UNUserNotificationCenterDelegate {
  // Receive displayed notifications for iOS 10 devices.
  func userNotificationCenter(_ center: UNUserNotificationCenter,
                              willPresent notification: UNNotification) async
    -> UNNotificationPresentationOptions {
    let userInfo = notification.request.content.userInfo

    // With swizzling disabled you must let Messaging know about the message, for Analytics
//     Messaging.messaging().appDidReceiveMessage(userInfo)

    // ...

    // Print full message.
        // Print message ID.
           if let messageID = userInfo[gcmMessageIDKey] {
             print("Message ID: \(messageID)")
           }
        print("whats this \(userInfo)")

    // Change this to your preferred presentation option
        return [[.banner, .sound,.badge,.list]]
  }

  func userNotificationCenter(_ center: UNUserNotificationCenter,
                              didReceive response: UNNotificationResponse) async {
      let userInfo = response.notification.request.content.userInfo
      
      // ...
      
      // With swizzling disabled you must let Messaging know about the message, for Analytics
//       Messaging.messaging().appDidReceiveMessage(userInfo)
      print ("user info is : \(userInfo)")
      // Print full message.
      if let messageID = userInfo[gcmMessageIDKey] {
          print("Message ID: \(messageID)")
      }
      
  }

    
}`

`extension AppDelegate: MessagingDelegate {
    // [START refresh_token]
    func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?) {
      print("Firebase registration token: \(String(describing: fcmToken))")

      let dataDict: [String: String] = ["token": fcmToken ?? ""]
      NotificationCenter.default.post(
        name: Notification.Name("FCMToken"),
        object: nil,
        userInfo: dataDict
      )
      // TODO: If necessary send token to application server.
      // Note: This callback is fired at each app startup and whenever a new token is generated.
    }
    // [END refresh_token]

    func application(application: UIApplication,
                     didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
      Messaging.messaging().apnsToken = deviceToken
        print("did it register? \(deviceToken)")
    }
}`

`@main
struct sastrerApp: App {
    
    @UIApplicationDelegateAdaptor(AppDelegate.self) var appDelegate
    @StateObject var sessionService = SessionServiceImpl()
    @StateObject var launchScreenManager = LaunchScreenManager()
    @StateObject var model = Model()
    @State var text = ""
    
    let persistenController = TailorPersistentController.shared
    
    var body: some Scene {
        WindowGroup {
            ZStack {
                switch sessionService.state {
                case .loggedIn:
                    if launchScreenManager.state != .completed {
                        LaunchScreenView()
                            .onAppear {
                                DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
                                    withAnimation(.easeOut(duration: 0.5)) {
                                        launchScreenManager.dismiss()
                                    }
                                }
                            }
                    } else {
                        ContentView(text: $text)
                    }
                case .loggedOut:
                    if launchScreenManager.state != .completed {
                        LaunchScreenView()
                            .onAppear {
                                DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
                                    withAnimation(.easeOut(duration: 0.5)) {
                                        launchScreenManager.dismiss()
                                    }
                                }
                            }
                    } else {
                        ModalView()
                    }
                case .loading:
                    LaunchScreenView()
                }
            }
            .environmentObject(sessionService)
            .environmentObject(model)
            .environmentObject(persistenController)
            .environmentObject(launchScreenManager)
        }
    }
    
}`
