### ISSUE TITLE
[Cocoapods] [FirebaseInAppMessaging] - Wrong version fetch

### ISSUE THREAD

**Issue by xav42mac** [firebase/firebase-ios-sdk#11990]
### Description

When no version set in Podfile:
<img width="226" alt="FirebaseInAppMessaging" src="https://github.com/firebase/firebase-ios-sdk/assets/57002749/26edc9ad-6f6a-4732-8c3b-9a5db94bc9ca">

It download the version 0.13.0 of FirebaseInAppMessaging instead of 10.13.0 (?)
<img width="307" alt="FirebaseInAppMessaging version problem" src="https://github.com/firebase/firebase-ios-sdk/assets/57002749/7096a37c-225a-4a31-907f-427d580a9df7">

### Reproducing the issue

Put FirebaseInAppMessaging in a Podfile with no version indicated and do a "pod install".

### Firebase SDK Version

10.13.0

### Xcode Version

15

### Installation Method

CocoaPods

### Firebase Product(s)

In-App Messaging

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
InAppMessaging is in beta and the beta must be specified in the Podfile:

`pod 'FirebaseInAppMessaging', '> 10.13-beta'`
