### ISSUE TITLE
[FR]: A/B Testing still in beta

### ISSUE THREAD

**Issue by henryglendening-hh** [firebase/firebase-ios-sdk#12003]
### Description

I've noticed that Firebase A/B Testing feature is currently in beta. I had first started looking at this feature in June of 2021 while it was in beta then too.

Is there a roadmap for this feature or any plans for its 1.0 release, or is there any possibility of it being sunsetted at some point as well? I'd like to consider working with this, but am a bit hesitant with how long is has been stuck in a Beta status.

Any information about its future would be helpful. Thank you!

### Firebase Product(s)

AB Testing

**Comment by Brooksie18** [comment]
I have just recently joined beta only a little over a week. I didn't know it was stuck

**Comment by karenyz** [comment]
Hi, we know the product has been in Beta for a long time and we appreciate your patience.  Firebase A/B testing is still under active development--we recently released a new form of statistical inference.  We anticipate moving A/B Testing to General Availability status within the foreseeable future. Hope this helps!
