### ISSUE TITLE
Trigger ‘screen_view’ event failed through GoogleTagManager

### ISSUE THREAD

**Issue by percival888** [firebase/firebase-ios-sdk#12018]
### Description

Our iOS project attempted to trigger an event named 'screen_view' through GoogleTagManager. By the log, the event had been triggered, but we couldn't find the corresponding event in debugView. Once we changed the event name, such as 'test_screen_view', it would trigger successfully

### Firebase SDK Version

10.16.0

### Xcode Version

14.3

### Installation Method

CocoaPods

### Firebase Product(s)

AB Testing, Analytics, DynamicLinks, Messaging, Performance, Remote Config

### Targeted Platforms

iOS

### Relevant Log Output

```shell
10.16.0 - [FirebaseAnalytics][I-ACS023072] Event logged. Event name, event params: screen_view, {
    device_id = ***;
    ga_debug (_dbg) = 1;
    ga_event_origin (_o) = app+gtm;
    ga_realtime (_r) = 1;
    region_name = ***;
    screen_class = ***;
    screen_name = ***;
    user_role = ***;
}
...
...
10.16.0 - [FirebaseAnalytics][I-ACS023072] Event logged. Event name, event params: test_screen_view, {
    device_id = ***;
    ga_debug (_dbg) = 1;
    ga_event_origin (_o) = app+gtm;
    ga_realtime (_r) = 1;
    region_name = ***;
    screen_class = ***;
    screen_name = ***;
    user_role = ***;
}
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

    pod 'Firebase/Core'
    pod 'Firebase/RemoteConfig'
    pod 'FirebaseABTesting'
    pod 'Firebase/Messaging'
    pod 'Firebase/Performance'
    pod 'Firebase/DynamicLinks'
    pod 'Firebase/Analytics' 
    pod 'GoogleIDFASupport', '~> 3.14.0'
    pod 'GoogleTagManager'

```

</details>

**Comment by rizafran** [comment]
Hi @percival888, based on your logs, it appears that the event is being logged, but is not showing in your DebugView in the Analytics dashboard. Upon testing, it seems that the screen_view event is successfully showing in the DebugView when using Analytics only. With this, this may be reported to [Google Tag Manager](https://support.google.com/tagmanager/community?hl=en) so they could investigate.

**Comment by Brooksie18** [comment]
Okay. I will definitely send this go Google now. Thank you
