### ISSUE TITLE
Don't know where to store documents on visionOS.

### ISSUE THREAD

**Issue by leokangmh** [firebase/firebase-ios-sdk#12023]
### Description

When I try to import firestore in visionOS. I got this error.
![截圖 2023-10-31 中午12 25 21](https://github.com/firebase/firebase-ios-sdk/assets/97867876/c8f11081-4bcb-42e7-9e66-a92d87aa2dcc)

### Firebase SDK Version

10.17

### Xcode Version

15.1 beta

### Installation Method

Swift Package Manager

### Firebase Product(s)

Firestore

### Targeted Platforms

visionOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by leokangmh** [comment]
I tried commenting it out, and it ran successfully. It seems like we also need to make a judgment on visionOS here.

**Comment by paulb777** [comment]
Thanks for the report. We'll get a fix into the next release.
