### ISSUE TITLE
Firebase/Analytics App crash for some event data [SIGSEGV exception]

### ISSUE THREAD

**Issue by priyam-swiggy** [firebase/firebase-ios-sdk#12040]
### Description

App crashing on prod build.

`XCode:` 14.2
`SDK version:` 8.14.0
`Platform:` iOS

<img width="1235" alt="Screenshot 2023-11-02 at 7 53 54 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/81305124/8fc6b856-0e5d-46ba-8a07-80daf2a6ec7d">

### Reproducing the issue

Not able to reproduce the crash in the debug environment.

### Firebase SDK Version

8.14.0

### Xcode Version

14.2

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Crashed: com.swiggy.analytics
0  libobjc.A.dylib                0x3a7c objc_retain + 16
1  libobjc.A.dylib                0x3a7c objc_retain_x0 + 16
2  libswiftCore.dylib             0x402e8c objcRetainAndReturn(void*) + 32
3  libswiftCore.dylib             0x395e84 initializeWithCopy for Character + 32
4  libswiftCore.dylib             0x3d5974 swift::metadataimpl::ValueWitnesses<swift::metadataimpl::OpaqueExistentialBox<0u> >::initializeWithCopy(swift::OpaqueValue*, swift::OpaqueValue*, swift::TargetMetadata<swift::InProcess> const*) + 128
5  libswiftCore.dylib             0xbeadc _SwiftDeferredNSDictionary.bridgeValues() + 620
6  libswiftCore.dylib             0xbf374 _SwiftDeferredNSDictionary.getObjects(_:andKeys:count:) + 472
7  libswiftCore.dylib             0xca038 @objc _SwiftDeferredNSDictionary.getObjects(_:andKeys:count:) + 72
8  CoreFoundation                 0x28874 -[NSDictionary allKeys] + 128
9  swiggy                         0x1d1558c FIRAnalyticsCheckForClass + 4371568012
10 swiggy                         0x1d15810 FIRAnalyticsCheckForUnbridgeableSwiftType + 4371568656
11 swiggy                         0x1d15b68 +[FIRAnalytics logEventWithOrigin:name:parameters:] + 4371569512
12 swiggy                         0x1d15878 +[FIRAnalytics logEventWithName:parameters:] + 4371568760
13 swiggy                         0xeedc98 GTMService.pushEvent(eventType:dict:) + 66 (GTMService.swift:66)
14 swiggy                         0x151c828 SwGTMServiceQueue.sendEvent(_:sid:) + 171 (SwGTMServiceQueue.swift:171)
15 swiggy                         0x151d290 closure #1 in SwGTMServiceQueue.initializeLoadEvent(_:name:value:position:context:extraParams:) + 4363211408
16 swiggy                         0x152c264 partial apply for closure #1 in SwGTMServiceQueue.initializeLoadEvent(_:name:value:position:context:extraParams:) + 4363272804
17 swiggy                         0xb7b60 thunk for @escaping @callee_guaranteed () -> () + 4341824352 (<compiler-generated>:4341824352)
18 libdispatch.dylib              0x2320 _dispatch_call_block_and_release + 32
19 libdispatch.dylib              0x3eac _dispatch_client_callout + 20
20 libdispatch.dylib              0xb534 _dispatch_lane_serial_drain + 668
21 libdispatch.dylib              0xc0a4 _dispatch_lane_invoke + 384
22 libdispatch.dylib              0x16cdc _dispatch_workloop_worker_thread + 648
23 libsystem_pthread.dylib        0xddc _pthread_wqthread + 288
24 libsystem_pthread.dylib        0xb7c start_wqthread + 8
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

**Comment by morganchen12** [comment]
This Analytics method is not thread-safe. You can likely fix this crash by calling `logEventWithName:parameters:` on the main thread.

**Comment by priyam-swiggy** [comment]
Already calling the block in a private queue. Will that make any difference? 

Also if we use main thread, will it hamper any performance?

```
private(set) lazy var queue = DispatchQueue(label: "com.gtm.queue",
                                           qos: .utility,
                                           target: nil)
queue.async {
   Analytics.logEvent(event, parameters: data)
}
```

**Comment by morganchen12** [comment]
Yes, calling this method on a private queue makes a difference. It must be called on the main queue. Using the main queue will not noticeably affect performance unless you have a very large number of events to log. You can always use Xcode Instruments to check the impact of calling any method on the main queue.

**Comment by priyam-swiggy** [comment]
@morganchen12 yes we have a large number of events and since our app has multiple listing screens the event generation is also aggressive. Can you suggest any alternate way to drive this?

**Comment by morganchen12** [comment]
Have you tried moving the events to the main thread? What was the framerate impact? Can you share an Instruments trace if it significantly lowered performance?

**Comment by priyam-swiggy** [comment]
@morganchen12 I have checked the performance. Found no significant drop in framerate. Will be adding the fix and check if the crashes get mitigated.

Thanks you!

**Comment by paulb777** [comment]
Great news! I'll close the issue. Feel free to comment or create a new issue if it reoccurs.
