### ISSUE TITLE
[iOS/Swift] Firestore - nil value never will be update Codable

### ISSUE THREAD

**Issue by nikitaskobelkin** [firebase/firebase-ios-sdk#12046]
### Description

```swift
1. struct FirebaseObject: Codable {
   let value: String?
   let date: Timestamp?
}

2. let data = FirebaseObject(value: "updated", date: nil)

3. document.reference.updateData(data)
```

## Problem
1. This **Codable** model is used, for example, for transferring data between the **iOS** app and **Firestore**.
2. When you want to update `date` or `value` field to `nil` - **Firestore** just ignores it

## Expexted result
`date` or `value` will be update no `nil/null` on **Firestore** side

### Reproducing the issue

1. Send any object to Firestore
2. Update optional field of this object and send updates to Firestore

### Firebase SDK Version

10.17

### Xcode Version

15.01

### Installation Method

Swift Package Manager

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS, tvOS, watchOS, macOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by MarkDuckworth** [comment]
I think you need to use `@ExplicitNull`

> The default behavior for encoding optionals that have a nil value is to just omit them. `@ExplicitNull` gives us some control over how Swift optionals are handled when encoding them: by flagging an optional property as `@ExplicitNull`, we can tell Cloud Firestore to write this property to the document with a null value if it contains a value of nil.

From https://firebase.google.com/docs/firestore/solutions/swift-codable-data-mapping
