### ISSUE TITLE
Firestore listeners miss events when app put in the background

### ISSUE THREAD

**Issue by mathone1** [firebase/firebase-ios-sdk#12052]
### Description

Using a snapshot listener, if a document is updated while the app is in the background, this update will not be retrieved.
However, if the app is back in the foreground, the listener continues to work.
Only updates that occurred while the app was in the background are lost.

This means manually implementing a wrapper to detect the state change, closing the listener when the app goes to background and reopening it when it returns to background to make sure you don't miss any updates.
This generates a cost when reopening the listener (if no update has taken place).
Can this mechanism be avoided?

### Reproducing the issue

Initiate a snapshot listener, put the application in the background, modify a document and put the application back in the foreground.

### Firebase SDK Version

10.15.0

### Xcode Version

15.0.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by MarkDuckworth** [comment]
@mathone1, I was unable to reproduce the behavior you are experiencing.

I attached a listener using `addSnapshotListener`, put my ios app in the background, modified a document in another app, and saw that the listener was not called when the app was in the background, but when I bring my app back to the foreground, my listener is called with a snapshot that includes all updates. This was the case for snapshot listeners on a single document and on a collection.

Can you provide us with additional information to help us understand how to reproduce what you're seeing?

**Comment by mathone1** [comment]
Hi, thank you for your prompt reply.

Indeed, I may not have been precise enough, I apologize.

The listener is initiated as such:
```
db.collection("users").document(userId).collection(collection)
            .whereField("requestHash", isEqualTo: hash)
            .order(by: "lastUpdate", descending: true)
            .limit(to: 1)
            .addSnapshotListener { }
```

I have exactly the same behavior, except that when the app returns to the foreground, the listener is not called.
It's only called when I perform a new update with the app still in foreground.
The problem may lie in the "limit" (uninformed assumption).

I thank you in advance

**Comment by MarkDuckworth** [comment]
@mathone1, Thanks, that code is helpful. Is it possible that you can also provide a sample document and and a sample document update, so that I can be most effective when trying to reproduce the issue?

Also, do you see this behavior on a simpler query in your app? For example, with `db.collection("users").document(userId).collection(collection).addSnapshotListener { }`, does the listener get called after the app comes back to the foreground?

**Comment by mathone1** [comment]
Hi,

Thank you for your continued assistance.

I've tested with a simpler query structure and found that it works as expected. (This query updates even when the app is in the background):

```
listenerPath
    .order(by: "lastUpdate", descending: true)
    .addSnapshotListener { }
```
However, the issue persists in the following scenario within a Task:

```
db.collection("users").document(userId).collection(collection)
    .whereField("requestHash", isEqualTo: hash)
    .order(by: "lastUpdate", descending: true)
    .limit(to: 1)
    .addSnapshotListener { }
```
    
Regarding the document structure, it's quite straightforward and includes three fields: request, result, and lastUpdate. A document is initially created with request and lastUpdate. Subsequently, a Google Cloud Function (GCF) adds a result field and updates lastUpdate. This process works flawlessly with the other listener, which shares the same structural setup.

It seems the issue might be related to the combination of the whereField, order, and limit methods in the query. If you have any insights or suggestions based on this additional information, I would greatly appreciate it.

Thanks again for your help in troubleshooting this issue.
