### ISSUE TITLE
Not receiving any data for latest version - FIRDebugEnabled says [FirebaseCore][I-COR000033] Data Collection flag is not set.

### ISSUE THREAD

**Issue by visskiss** [firebase/firebase-ios-sdk#12060]
### Description

I released v1.8 of by app  on Nov 3rd with 10.17.0 Firebase analytics and have received no data since then. I checked a debug build on my device with FIRDebugEnabled checked and I am getting:

10.16.0 - [FirebaseCore][I-COR000033] Data Collection flag is not set.

or 

10.17.0 - [FirebaseCore][I-COR000033] Data Collection flag is not set.

depending on which version I use (Swift Package Manager)

I have changed nothing about my app and three lines of code that constitutes the entirety of my Firebase code is:

`import FirebaseCore`

and inside my delegate: 

```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
        FirebaseApp.configure()
}
```

### Firebase SDK Version

10.17.0

### Xcode Version

15.0.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
10.16.0 - [FirebaseCore][I-COR000033] Data Collection flag is not set.
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

{
  "pins" : [
    {
      "identity" : "abseil-cpp-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/abseil-cpp-binary.git",
      "state" : {
        "revision" : "bfc0b6f81adc06ce5121eb23f628473638d67c5c",
        "version" : "1.2022062300.0"
      }
    },
    {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk",
      "state" : {
        "revision" : "8872dbd7d947acf757abab933da10e83c1842280",
        "version" : "10.17.0"
      }
    },
    {
      "identity" : "googleappmeasurement",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleAppMeasurement.git",
      "state" : {
        "revision" : "6b332152355c372ace9966d8ee76ed191f97025e",
        "version" : "10.17.0"
      }
    },
    {
      "identity" : "googledatatransport",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleDataTransport.git",
      "state" : {
        "revision" : "aae45a320fd0d11811820335b1eabc8753902a40",
        "version" : "9.2.5"
      }
    },
    {
      "identity" : "googleutilities",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleUtilities.git",
      "state" : {
        "revision" : "1cd556b33550982ec17f80e358253d905e756f0f",
        "version" : "7.11.6"
      }
    },
    {
      "identity" : "grpc-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/grpc-binary.git",
      "state" : {
        "revision" : "a673bc2937fbe886dd1f99c401b01b6d977a9c98",
        "version" : "1.49.1"
      }
    },
    {
      "identity" : "gtm-session-fetcher",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/gtm-session-fetcher.git",
      "state" : {
        "revision" : "d415594121c9e8a4f9d79cecee0965cf35e74dbd",
        "version" : "3.1.1"
      }
    },
    {
      "identity" : "interop-ios-for-google-sdks",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/interop-ios-for-google-sdks.git",
      "state" : {
        "revision" : "2d12673670417654f08f5f90fdd62926dc3a2648",
        "version" : "100.0.0"
      }
    },
    {
      "identity" : "leveldb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/leveldb.git",
      "state" : {
        "revision" : "9d108e9112aa1d65ce508facf804674546116d9c",
        "version" : "1.22.3"
      }
    },
    {
      "identity" : "nanopb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/nanopb.git",
      "state" : {
        "revision" : "819d0a2173aff699fb8c364b6fb906f7cdb1a692",
        "version" : "2.30909.0"
      }
    },
    {
      "identity" : "promises",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/promises.git",
      "state" : {
        "revision" : "e70e889c0196c76d22759eb50d6a0270ca9f1d9e",
        "version" : "2.3.1"
      }
    },
    {
      "identity" : "swift-protobuf",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-protobuf.git",
      "state" : {
        "revision" : "07f7f26ded8df9645c072f220378879c4642e063",
        "version" : "1.25.1"
      }
    }
  ],
  "version" : 2
}


```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment]
Hi @visskiss, sorry for the trouble. Could you please confirm if the project's `GooglerService-Info.plist` is setting the data collection flag? https://firebase.google.com/docs/analytics/configure-data-collection?platform=ios#temporarily_disable_collection_2

**Comment by visskiss** [comment]
This is the entirety of my plist file excluding PII

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CLIENT_ID</key>
	<string>redacted.apps.googleusercontent.com</string>
	<key>REVERSED_CLIENT_ID</key>
	<string>com.googleusercontent.apps.redacted</string>
	<key>API_KEY</key>
	<string>redacted</string>
	<key>GCM_SENDER_ID</key>
	<string>redacted</string>
	<key>PLIST_VERSION</key>
	<string>1</string>
	<key>BUNDLE_ID</key>
	<string>com.redacted</string>
	<key>PROJECT_ID</key>
	<string>redacted</string>
	<key>STORAGE_BUCKET</key>
	<string>redacted.appspot.com</string>
	<key>IS_ADS_ENABLED</key>
	<false></false>
	<key>IS_ANALYTICS_ENABLED</key>
	<false></false>
	<key>IS_APPINVITE_ENABLED</key>
	<true></true>
	<key>IS_GCM_ENABLED</key>
	<true></true>
	<key>IS_SIGNIN_ENABLED</key>
	<true></true>
	<key>GOOGLE_APP_ID</key>
	<string>1:redacted:ios:redacted</string>
</dict>
</plist>
```

Which I double checked before posting. Has not changed this version, but analytics is false (different tag)

**Comment by ncooke3** [comment]
Were you seeing Analytics data before upgrading to 10.16.0 or was Firebase 10.16.0 the first version ever included by your project?

**Comment by paulb777** [comment]
To clarify, the data collection flag is set in the app's `Info.plist` not `GoogleService-Info.plist`. https://firebase.google.com/docs/analytics/configure-data-collection?platform=ios#temporarily_disable_collection_2

**Comment by visskiss** [comment]
Thanks for your reply. I don't have that key set in the apps info.plist. That should be correct? Again, I haven't changed it.

I was seeing analytics just fine until the latest release. First package.resolved version for 1.0 was 10.7.0. App version 1.7 was recording just fine and "successfully released" according to analytics. That used version 10.16.0.  Latest version 1.8 is showing zero stats and the version doesn't exist. That firebase SDK version is 10.17

In attempting to debug this, I have been trying the older 10.16 and looking for real time feedback in Firebase. So far I haven't seen any real time feedback. Maybe there's a better way to debug? I am not seeing any "Events" being sent with FirDebugEnabled flag set in build arguments.  I have added no "custom" events.

**Comment by ncooke3** [comment]
> I don't have that key set in the apps info.plist. That should be correct?

I was just double checking that the key wasn't unintentionally set to turn off Analytics. That doesn't seem to be the case though.

> I was seeing analytics just fine until the latest release. First package.resolved version for 1.0 was 10.7.0. App version 1.7 was recording just fine and "successfully released" according to analytics. That used version 10.16.0. Latest version 1.8 is showing zero stats and the version doesn't exist in the Analytics dashboard filter. That firebase SDK version is 10.17

Was app version 1.7 using Swift Package Manager or another dependency manager like CocoaPods? 

> In attempting to debug this, I have been trying the older 10.16 and looking for real time feedback in Firebase. So far I haven't seen any real time feedback. Maybe there's a better way to debug? I am not seeing any "Events" being sent with FirDebugEnabled flag set in build arguments. I have added no "custom" events.

When debugging Analytics related things, try passing the `-FIRAnalyticsDebugEnabled` flag to see Analytics-related logs. Please try that and let me know if that makes a difference in what you see.

<img width="509" alt="Screenshot 2023-11-07 at 1 23 41 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/36927374/49d59570-bbc1-405d-93fc-5fe9b72d1431">

**Comment by visskiss** [comment]
I had already added that flag. It made no difference. I get one single message. I'm building for release on a device (not simulator).

10.17.0 - [FirebaseCore][I-COR000001] Configuring the default app.

**Comment by ncooke3** [comment]
Okay, understood. I have a few more questions to further narrow things down:

1. Do you recall whether your app version 1.7 was using Swift Package Manager or another dependency manager like CocoaPods?
2. Which Analytics-related dependencies are listed in the _Frameworks, Libraries, and Embedded Content_ section in your app target's _General_ settings?
3. Do you explicitly import `FirebaseAnalytics` or `FirebaseAnalyticsSwift` anywhere in your app? You're correct that this isn't necessary for general analytics collections, but the answer here helps me determine if there is an issue with how Analytics is being integrated when using SwiftPM.

**Comment by visskiss** [comment]
1. Swift Package Manager only since the start
2. Only Firebase related library is "FirebaseAnalytics" which is not what was released. I released with FirebaseAnalyticsSwift which is what I have always released. I read that was deprecated so I changed to FirebaseAnalytics (no swift). 
3. I explicitly only import FirebaseCore as I pasted in the original issue description. No other firebase related imports anywhere.

**Comment by ncooke3** [comment]
Ah, I understand the issue. The `-ObjC` flag needs to be passed to your project target's `Other Linker Flags`.
<img width="568" alt="Screenshot 2023-11-07 at 2 39 31 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/36927374/4ac39013-e385-4b7d-ae9e-78072f6bd298">

This is documented in the general Firebase docs [here](https://firebase.google.com/docs/ios/installation-methods#analytics), but not on the Firebase Analytics specific docs [here](https://firebase.google.com/docs/analytics/get-started?platform=ios#add-sdk)– which I will fix.

The reason this is surfacing in your project now is because the pre-10.17.0 contents of FirebaseAnalyticsSwift programmatically forced the FirebaseAnalytics framework to link. With that code moved into the FirebaseAnalytics module in 10.17.0, this programmatic link has broken.

Please try adding the `-ObjC` flag to your target's _Other Linker Flags_ settings, and let me know if that addresses the issue for you.

**Comment by visskiss** [comment]
Gotcha, that is now working. Debug entries are there and realtime console is showing the device.

**Comment by ncooke3** [comment]
Great to hear! 🙂
