### ISSUE TITLE
[FR]: Break out `FirebaseSharedSwift` as it's own package

### ISSUE THREAD

**Issue by brianmichel** [firebase/firebase-ios-sdk#12062]
### Description

1. Currently the `FirebaseSharedSwift` target has no dependencies on an of the other Firebase targets, but trying to use just this package on Windows/Linux does not work since Swift on Windows cannot handle all of the binary targets that get triggered to download when adding the firebase-ios-sdk package as a dependency.
2. Currently the Firebase SDK lists all targets in one Package.swift file
3. I would propose either creating an additional package file that has a limited number of targets which work across all platforms (Darwin, Windows, Linux), or better yet to have different repos which can have their own package files.

### Firebase Product(s)

Database

**Comment by paulb777** [comment]
Thanks for the feature request. Restructuring our repos to support non-Apple platform development is not likely to be a priority for us in the near-term.

**Comment by paulb777** [comment]
Closing since there are no upvotes and no foreseeable plans.
