### ISSUE TITLE
Firebase Messaging makes a false assumption about the location of the GoogleService-Info.plist file

### ISSUE THREAD

**Issue by mbernson** [firebase/firebase-ios-sdk#12078]
## Steps to reproduce

I've configured Firebase in my iOS application as follows:

```swift
class AppDelegate: NSObject, UIApplicationDelegate {
    private var appConfiguration = AppConfiguration()

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil) -> Bool {
        let filePath = Bundle.main.path(forResource: appConfiguration.firebaseConfigurationFilename, ofType: "plist")!
        let options = FirebaseOptions(contentsOfFile: filePath)!
        FirebaseApp.configure(options: options)

        // Rest of the app configuration...
    }
}
```

The `AppConfiguration` type is some custom code that determines the environment the app was built for. And it configures Firebase using a different GoogleService-Info file depending on that.

As you can see, I use the initialiser `FirebaseOptions.init(contentsOfFile:)` from the Firebase SDK.

## Expected result

The FIROptions that I've provided to the Firebase SDK are used everywhere in the SDK.

## Actual result

Firebase Messaging tries to construct its own FIROptions and unjustly throws an error: `[I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'`

## Additional information

I've debugged the problem to find the cause. I'm seeing that when Firebase Messaging is starting up, it does a check internally in `-[FIRMessagingTokenInfo isFreshWithIID:]`.
In there, it constructs a FIRMessagingFirebaseAppID in order to determine if the app ID has changed:

https://github.com/firebase/firebase-ios-sdk/blob/09c264423d09fec915a40d1af5b5a07a1cc6bb29/FirebaseMessaging/Sources/Token/FIRMessagingTokenInfo.m#L97-L99

Drilling down into that function, we see that it tries to construct a FIROptions object with the default options:

https://github.com/firebase/firebase-ios-sdk/blob/09c264423d09fec915a40d1af5b5a07a1cc6bb29/FirebaseMessaging/Sources/FIRMessagingUtilities.m#L94-L96

...which in turn tries to use the default GoogleService-Info.plist path. This is incorrect for my application. This file doesn't exist. Therefore the path is `nil` and the error mentioned above is thrown:

https://github.com/firebase/firebase-ios-sdk/blob/09c264423d09fec915a40d1af5b5a07a1cc6bb29/FirebaseCore/Sources/FIROptions.m#L134-L137

### Firebase SDK Version

10.16.0

### Xcode Version

14.5

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Crashlytics

### Targeted Platforms

iOS

**Comment by mbernson** [comment]
Looking at the code of the Firebase SDK, this problem also exists in version 10.17.0.

My workaround will be to rename the `GoogleService-Info-Prod.plist` file in my app to just `GoogleService-Info.plist`. This will cause the production version of my app to always use the production Firebase config.

**Comment by paulb777** [comment]
Sorry about the trouble. This issue is related to #11975.  Messaging only supports the default FIRApp configuration.

**Comment by paulb777** [comment]
Closing in favore of #11975. Please continue the conversation there.
