### ISSUE TITLE
[FR]: NSSecureCoding support

### ISSUE THREAD

**Issue by Juan2662** [firebase/firebase-ios-sdk#12075]
### Description

Hi guys, I notice that some chunks in the code in iOS (like FirebaseMessaging) is using NSCoding protocol
I know you are working on that incrementally, but I would like to know when can we have full support for NSSecureCoding in all products?

### Firebase Product(s)

Messaging

**Comment by paulb777** [comment]
A `git grep` shows the following `NSCoding` occurrences in Messaging and Database:
```
 $ git grep NSCoding
FirebaseDatabase/Sources/Persistence/FPendingPut.h:@interface FPendingPut : NSObject <NSCoding>
FirebaseDatabase/Sources/Persistence/FPendingPut.h:@interface FPendingPutPriority : NSObject <NSCoding>
FirebaseDatabase/Sources/Persistence/FPendingPut.h:@interface FPendingUpdate : NSObject <NSCoding>
FirebaseMessaging/Sources/Token/FIRMessagingAPNSInfo.h:@interface FIRMessagingAPNSInfo : NSObject <NSCoding, NSCopying>
FirebaseMessaging/Sources/Token/FIRMessagingAPNSInfo.m:#pragma mark - NSCoding
FirebaseMessaging/Sources/Token/FIRMessagingTokenInfo.h:@interface FIRMessagingTokenInfo : NSObject <NSCoding>
FirebaseMessaging/Sources/Token/FIRMessagingTokenInfo.m:#pragma mark - NSCoding
```

**Comment by paulb777** [comment]
Only updating Messaging for now. FPendingPut in RTDB does not have tests and may only be used in an outdated code path.
