### ISSUE TITLE
FirebaseAnalytics Crash

### ISSUE THREAD

**Issue by xdozorx** [firebase/firebase-ios-sdk#12086]
### Description

IOS 17, Xcode 15
I have crash on running app. (maybe a few second after running app)

10.17.0 - [FirebaseAnalytics][I-ACS030000] Exception on worker queue. Block ID=APMMeasurement:1683. Exception: -[APMMeasurement uploadData]: -[GULNetwork postURL:headers:payload:queue:usingBackgroundSession:completionHandler:]: unrecognized selector sent to instance 0x600001749900

### Firebase SDK Version

10.17.0

### Xcode Version

15.0.1

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by revolter** [comment]
I fixed this by updating the `GoogleUtilities` that I have explicitly defined in my `Podfile` due to https://github.com/CocoaPods/CocoaPods/issues/8206#issuecomment-696754566
