### ISSUE TITLE
iOS11：__ZTISt18bad_variant_access

### ISSUE THREAD

**Issue by XingChen-GitHub** [firebase/firebase-ios-sdk#12103]
### Description

"GoogleAppMeasurementOnDeviceConversion.xcframework" crashes on iOS 11, prompting "dyld: Symbol not found: dyld: Symbol not found: __ZTISt18bad_variant_access
   Referenced from: /var/containers/Bundle/Application/72E6079A-DF24-42E5-9C85-52BBCC9230F9/Test.app/Test
   Expected in: /usr/lib/libc++.1.dylib
  in /var/containers/Bundle/Application/72E6079A-DF24-42E5-9C85-52BBCC9230F9/Test.app/Test”

### Firebase SDK Version

10.17.0

### Xcode Version

14.2

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>
/

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by morganchen12** [comment]
Have you linked the required `libc++` into your project?

**Comment by XingChen-GitHub** [comment]
> Have you linked the required `libc++` into your project?

I have added libc++.1.tbd to the project, and configured -ObjC and -lc++, but there is still a crash.

**Comment by XingChen-GitHub** [comment]
> Hi @XingChen-GitHub, could you provide the full stack trace as well as the detailed steps to reproduce the issue?

I'm using this project:
https://github.com/firebase/quickstart-ios

Start the project in the directory:
quickstart-ios-master => analytics => LegacyAnalyticsQuickstart => AnalyticsExample.xcworkspace

And added the following configuration to the Podfile:

pod 'FirebaseAnalytics'
pod 'FirebaseAnalyticsOnDeviceConversion'


Finally added libc++.tbd and -lc++,


When running on iOS11.4.1 (iPhone 6), the startup crashes and the log prints:

dyld: Symbol not found: __ZTISt18bad_variant_access
   Referenced from: /var/containers/Bundle/Application/8039EF72-4A9A-4F91-A178-2FF96A8D0CA8/AnalyticsExample.app/AnalyticsExample
   Expected in: /usr/lib/libc++.1.dylib
  in /var/containers/Bundle/Application/8039EF72-4A9A-4F91-A178-2FF96A8D0CA8/AnalyticsExample.app/AnalyticsExample

Please try to reproduce it, thank you

**Comment by XingChen-GitHub** [comment]
> Hi @XingChen-GitHub, could you provide the full stack trace as well as the detailed steps to reproduce the issue?

By the way, I'm integrating "Tutorial: Measure Google Ads conversions from your iOS app campaigns" at https://firebase.google.com/docs/tutorials/ads-ios-on-device-measurement?hl=en -cn

**Comment by XingChen-GitHub** [comment]
> > Have you linked the required `libc++` into your project?
> 
> I have added libc++.1.tbd to the project, and configured -ObjC and -lc++, but there is still a crash.

By the way, I'm integrating "Tutorial: Measure Google Ads conversions from your iOS app campaigns" at https://firebase.google.com/docs/tutorials/ads-ios-on-device-measurement?hl=en -cn

**Comment by tsunghung** [comment]
It works with my test environment:
- Xcode 14.1
- iPhone SE iOS 14.0.1 simulator
- FirebaseAnalytics & FirebaseAnalyticsOnDeviceConversion 10.18.0

Unfortunately, I don't have iOS 11 simulators to test. Please help to test:
1. Could you please try iOS 14/16/17 simulators? Are they also have the same issue?
2. What's your CocoaPods version, `pod --version`? Please use `gem install cocoapods` to update your CocoaPods and try again with `pod deintegrate && pod install`.
3. You don't need to add `libc++.tbd`, `-lc++`, or `-ObjC` manually. Recent versions of CocoaPods should work automatically.

**Comment by tsunghung** [comment]
Just FYI, a related discussion:
https://stackoverflow.com/questions/52310835/xcode-10-call-to-unavailable-function-stdvisit

You may try to add a cpp file
```
#include <variant>

const char* std::bad_variant_access::what() const noexcept {
  return "bad_variant_access";
}
```

**Comment by XingChen-GitHub** [comment]
> It works with my test environment:
> 
> * Xcode 14.1
> * iPhone SE iOS 14.0.1 simulator
> * FirebaseAnalytics & FirebaseAnalyticsOnDeviceConversion 10.18.0
> 
> Unfortunately, I don't have iOS 11 simulators to test. Please help to test:
> 
> 1. Could you please try iOS 14/16/17 simulators? Are they also have the same issue?
> 2. What's your CocoaPods version, `pod --version`? Please use `gem install cocoapods` to update your CocoaPods and try again with `pod deintegrate && pod install`.
> 3. You don't need to add `libc++.tbd`, `-lc++`, or `-ObjC` manually. Recent versions of CocoaPods should work automatically.

just only in iOS11 , other system normal, thank you
