### ISSUE TITLE
Targets under main project have same SPM package which depends on Firebase sdk crash when launching

### ISSUE THREAD

**Issue by joseewu** [firebase/firebase-ios-sdk#12118]
### Description

Our project is under modularisation process. 

We want to extract performance monitoring to a module (as an SPM package) so this module needs to install `FirebasePerformance`. 

We also have a target (is in charge of some features) under main project. However, when add the performance monitor module to both main project and the targets, the app crashes immediately at launching time. 

And it complaints about `FirebaseApp` has not yet configured. 
You can see the reproduce steps below:

### Reproducing the issue

With a demo project as `xcworkspace`
1. add a target (called it B-module) under your main target
2. create a local package with dependency of FirebaseCrashlytics looks like this
```
.package(url: "https://github.com/firebase/firebase-ios-sdk.git", exact: "10.12.0")
```
3. We have another `Performance` package is in charge of using `FirebasePerformance` to monitor task time. It also depends on same version if firebase sdk 
4. Both B-module and main target need `Performance` because we need to measure some task time on both places.
5. when add the Performance to B-module, the app crashes at launching, the crash says
```
*** Terminating app due to uncaught exception 'com.firebase.perf', reason: 'The default Firebase app has not yet been configured. Add [FirebaseApp configure] to your application initialization.'
*** First throw call stack:
```
I already make sure that `FirebaseApp.configure()` is called right after `didFinishLaunchingWithOptions` in AppDelegate. I also try to move `FirebaseApp.configure()` in `init()` in AppDelegate, but it does not fix the crash.

I also try to update the sdk version from v8.8.1 to v10.12.0, does not work as well.

Can someone help me with this issue? 

### Firebase SDK Version

8.8.1

### Xcode Version

14.3.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Performance

### Targeted Platforms

iOS

### Relevant Log Output

```shell
*** Terminating app due to uncaught exception 'com.firebase.perf', reason: 'The default Firebase app has not yet been configured. Add [FirebaseApp configure] to your application initialization.'
	3   FirebasePerformance_-2CF195E89D74AA 0x0000000124eb0c90 -[FIRPerformance traceWithName:] + 140
	4   FirebasePerformance_-2CF195E89D74AA 0x0000000124eb0ba0 +[FIRPerformance startTraceWithName:] + 88
	5   Performance_-79AFB3AFDFEAA983_Packa 0x000000010623eac8 $s11Performance14FirebaseTracerC5startyySSF + 132
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment]
Does refactoring your SPM targets to link dynamically help any? See solution in https://github.com/firebase/firebase-ios-sdk/issues/12025#issuecomment-1814789733.

**Comment by visumickey** [comment]
This is interesting. Based on my initial analysis it looks like the default notification center is not able to propagate notifications to the newly created `ThridParty` library (which depends on FirebasePerformance). The FirebasePerformance library depends on the notifications that happens on the default notification center for its initialization. Since that is broken, FirebasePerformance is not getting initialized successfully causing the above errors.

I'm working internally towards what could be an ideal fix to this scenario. Will keep this group posted as I have a solution.

**Comment by visumickey** [comment]
Since this is a special setup, I'm marking this as a feature request.

**Comment by joseewu** [comment]
Thanks for the reply :) And small question, if I added FirebaseAnalytics to `ThridParty library` the crash won't happen anymore. Is this something i can go for now as temporary workaround?

**Comment by joseewu** [comment]
@visumickey Nice! it works, just a bit confused, I thought the default type is `.dynamic` but I was wrong 😭

**Comment by paulb777** [comment]
Closing based on the resolution. Feel free to continue to discuss here.

**Comment by joseewu** [comment]
So the problem is that the our target is static and link the Performance statically -> and the FirebasePerformance can not configure statically? 🤔

**Comment by paulb777** [comment]
FirebasePerformance can configure statically, but it needs to happen after `FirebaseApp.configure()`
