### ISSUE TITLE
FirebaseRemoteConfig lates version function are not include 

### ISSUE THREAD

**Issue by KavinduDissanayake** [firebase/firebase-ios-sdk#12124]
### Description

When I try to install pod with "pod 'GoogleMLKit/ImageLabeling Custom', '4.0.0' pod 'GoogleMLKit/Link Firebase' "
The  FirebaseRemoteConfig (9.6.0)
version is (9.6.0) an. But that version doesn't include remoteConfig.addOnConfigUpdateListener  {}. this function. So I'm really struggling now 

### Firebase SDK Version

9.6.0

### Xcode Version

15

### Installation Method

CocoaPods

### Firebase Product(s)

Remote Config

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @KavinduDissanayake, based on the release notes, `addOnConfigUpdateListener` is available on [10.7.0](https://firebase.google.com/support/release-notes/ios#remote-config_2). Did you try to run `pod update` instead of `pod install`? If the issue persists, please share your `Podfile` to check what's causing the issue.

**Comment by paulb777** [comment]
MLKitFirebase explicitly depends on Firebase major version 9. See https://github.com/CocoaPods/Specs/blob/master/Specs/7/7/e/MLKitLinkFirebase/3.0.0/MLKitLinkFirebase.podspec.json#L5.

To use Firebase 10 and its new APIs, an update from MLKitLinkFirebase is needed, or the app needs to drop the dependency on it.

**Comment by paulb777** [comment]
Closing since there's nothing actionable for Firebase, beyond requesting an update for MLKit. Feel free to continue the discussion here.

**Comment by KavinduDissanayake** [comment]
> Hi @KavinduDissanayake, based on the release notes, `addOnConfigUpdateListener` is available on [10.7.0](https://firebase.google.com/support/release-notes/ios#remote-config_2). Did you try to run `pod update` instead of `pod install`? If the issue persists, please share your `Podfile` to check what's causing the issue.

`# Uncomment the next line to define a global platform for your project
#platform :ios, '15.0'  # For example, change from '14.0' to '15.0'

target 'myApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Clicklife
  # Firebase
  pod 'FirebaseAnalytics'
  pod 'FirebaseMessaging'
  pod 'Firebase/Crashlytics'
  # RemoteConfig
  pod 'FirebaseRemoteConfig'
  # AzureB2C
  pod 'MSAL'
  # Network request
  pod 'Alamofire'
  # Connection checker
  pod 'Connectivity'
  # Web image
  pod 'SDWebImageSwiftUI'
  # Live chat
  pod 'LiveChat'
  # Image cropper
  pod 'Mantis'
  # Fortune wheel
  pod 'SwiftFortuneWheel'
  # Animation
  pod 'lottie-ios'
  pod 'MijickPopupView'

  # MLKit
  pod 'GoogleMLKit/ImageLabelingCustom', '4.0.0'
  pod 'GoogleMLKit/LinkFirebase'
#  
  # post-install actions
  post_install do |installer|
    # Fix for Xcode 15 DT_TOOLCHAIN_DIR issue
    installer.aggregate_targets.each do |target|
      target.xcconfigs.each do |variant, xcconfig|
        xcconfig_path = target.client_root + target.xcconfig_relative_path(variant)
        IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
      end
    end
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.base_configuration_reference.is_a? Xcodeproj::Project::Object::PBXFileReference
          xcconfig_path = config.base_configuration_reference.real_path
          IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        end
        
        # Adjustments for GoogleDataTransport
        if target.name.start_with? "GoogleDataTransport"
          target.build_configurations.each do |config|
            config.build_settings['CLANG_WARN_STRICT_PROTOTYPES'] = 'NO'
          end
        end
      end
    end
  end
end`
here is my pod file please help me to fixed that  issue

**Comment by KavinduDissanayake** [comment]
when I'm running pod update it automatically happens like this, why you close my issue without considering what I say ,
![Screenshot 2023-11-22 at 09 16 48](https://github.com/firebase/firebase-ios-sdk/assets/51842810/d51627a9-2fb8-4807-90fb-2dd78c787064)
@paulb777

**Comment by paulb777** [comment]
Did `pod update` successfully update to 10.18.0? If so, what is the issue?

**Comment by KavinduDissanayake** [comment]
first time i remove the pod 'GoogleMLKit/ImageLabelingCustom'
 pod 'GoogleMLKit/LinkFirebase' these two and then , That time it updates to 10.18.0 after uncommenting above two ,again it comes to firebase 9.6.0, That is the firebase issues that i facing now

**Comment by paulb777** [comment]
Right, the latest MLKit podspecs specifically require Firebase 9.x.

**Comment by KavinduDissanayake** [comment]
any thing can I do for resolved that problem ?
