### ISSUE TITLE
Crashlytics SDK upload-symbols successed，but missing bundle version

### ISSUE THREAD

**Issue by cao903775389** [firebase/firebase-ios-sdk#12137]
### env:
upload-symbols:  **3.16 build 35**
FirebaseCrashlytics:  10.18.0

### build setting
<img width="1394" alt="image" src="https://github.com/firebase/firebase-ios-sdk/assets/8541526/3900b3f9-5aad-43ac-818f-91ca1422f776">
<img width="651" alt="image" src="https://github.com/firebase/firebase-ios-sdk/assets/8541526/16ab9f10-bca4-46c1-8df3-1ee609be7665">

### build logs
<img width="651" alt="image" src="https://github.com/firebase/firebase-ios-sdk/assets/8541526/483cb142-b674-4345-832d-fcf0bdf17dc0">

### Crashlytics management
<img width="956" alt="image" src="https://github.com/firebase/firebase-ios-sdk/assets/8541526/bdd06303-6770-4157-92d2-2d54fe2bf81c">

### Firebase SDK Version

10.18.0

### Xcode Version

15.0.1、14.1

### Installation Method

Zip

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by cao903775389** [comment]
**this is my build phrase input files**
<img width="1478" alt="image" src="https://github.com/firebase/firebase-ios-sdk/assets/8541526/3fc4774e-a944-4bcc-9584-048b31dcc43b">

**Comment by cao903775389** [comment]
some build logs
<img width="1581" alt="image" src="https://github.com/firebase/firebase-ios-sdk/assets/8541526/eefc4d70-5f7d-41d6-a6a8-94cb15cdc9dd">

**Comment by rizafran** [comment]
Hi @cao903775389, based on your info, it seems like you're having an issue with the bundle version in the Crashlytics dashboard. As the issue is related to the console, please file a ticket via our [support channel](https://firebase.google.com/support) so the Crashlytics team will be able to get your project details and investigate it in our backend. With this, I'll now close the ticket.
