### ISSUE TITLE
undeclared function 'GULGetLoggerLevel'

### ISSUE THREAD

**Issue by shayanaghajan** [firebase/firebase-ios-sdk#12138]
### Description

An error in the FIRLogger file regarding the `Call to undeclared function 'GULGetLoggerLevel'; ISO C99 and later do not support implicit function declarations` prevented me from building the project.

### Firebase SDK Version

10.18.0

### Xcode Version

15.0.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Crashlytics, In-App Messaging, Installations, Performance, Remote Config

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

{
        "package": "Firebase",
        "repositoryURL": "https://github.com/firebase/firebase-ios-sdk",
        "state": {
          "branch": null,
          "revision": "5de0369ee79ad096c164eb3afeb7921d92a43b58",
          "version": "10.18.0"
        }
      }

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by shayanaghajan** [comment]
After a couple of resetting packages, this issue disappeared. 
@rizafran I think this issue can be closed now.

**Comment by paulb777** [comment]
Yep, make sure a recent version of GoogleUtilities is installed.
