### ISSUE TITLE
Unable to Sign In with Apple after converting an Anonymous Account

### ISSUE THREAD

**Issue by davidarice** [firebase/firebase-ios-sdk#12146]
### Description

When a user Signs In with Apple I first try to link the anonymous account with the credential created using `Auth.auth().currentUser?.link(with: credential)`. On first sign up this works fine.

For my testing, I immediately sign out. The app then creates a new anonymous user. I then try to sign back in using Sign In With Apple.

If I receive the error `This credential is already associated with a different user account.` I know the user exists already, I then try to sign in using `Auth.auth().signIn(with: credential)`, but this is getting an error: `Duplicate credential received. Please try again with a new credential.`

Do I need to invalidate the credential somehow? 

### Firebase SDK Version

10.17.0

### Xcode Version

15.0

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication, Firestore, Storage

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by morganchen12** [comment]
Can you share the whole error? Does the `userInfo` dictionary contain a new credential under the `AuthErrorUserInfoUpdatedCredentialKey` key?

**Comment by davidarice** [comment]
This is the error that confirms the user exists (redacted apple id email):

` - Error Domain=FIRAuthErrorDomain Code=17025 "This credential is already associated with a different user account." UserInfo={FIRAuthErrorUserInfoNameKey=ERROR_CREDENTIAL_ALREADY_IN_USE, FIRAuthErrorUserInfoEmailKey=email@me.com, FIRAuthErrorUserInfoUpdatedCredentialKey=<FIROAuthCredential: 0x280ce0820>, NSLocalizedDescription=This credential is already associated with a different user account.}`

And this is the error I believe you're looking for, once I try to sign in:

`- Error Domain=FIRAuthErrorDomain Code=17094 "Duplicate credential received. Please try again with a new credential." UserInfo={NSLocalizedDescription=Duplicate credential received. Please try again with a new credential., FIRAuthErrorUserInfoNameKey=ERROR_MISSING_OR_INVALID_NONCE}`

**Comment by morganchen12** [comment]
When you retried signing in with Apple, did you use a new nonce or re-use the old one?

**Comment by davidarice** [comment]
When the user hits the Sign In with Apple button it starts the auth flow with `handleSignInWithAppleRequest(request: ASAuthorizationAppleIDRequest)` which creates a new nonce using `randomNonceString()`.

**Comment by davidarice** [comment]
Maybe I'm missing something? But, shouldn't I be creating a new nonce each time the user tries to login with apple?

**Comment by davidarice** [comment]
For what it's worth, I implemented the same flow with 'Sign in with Google' with expected results. So thats good!

**Comment by NhienLam** [comment]
Have you tried https://github.com/firebase/firebase-ios-sdk/issues/4434#issuecomment-564776016? This is also documented in https://firebase.google.com/docs/auth/ios/apple#reauthentication_and_account_linking.


> Sign in with Apple will not allow you to reuse an auth credential to link to an existing account. If you want to link a Sign in with Apple credential to another account, you must first attempt to link the accounts using the old Sign in with Apple credential and then examine the error returned to find a new credential. The new credential will be located in the error's userInfo dictionary and can be accessed via the AuthErrorUserInfoUpdatedCredentialKey key.

**Comment by davidarice** [comment]
Thank you @NhienLam. On first attempt, this indeed seems to be the solution. 

`let authError = error as? AuthErrorCode`
`guard let newCredential = authError?.userInfo[AuthErrorUserInfoUpdatedCredentialKey] as? OAuthCredential else { return }`
`try await Auth.auth().signIn(with: newCredential)`
