### ISSUE TITLE
The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff

### ISSUE THREAD

**Issue by arashgm** [firebase/firebase-ios-sdk#12153]
### Description

This is an old topic that happens time to time for lots of our users on our Flutter App. there are some threads regarding this issue but almost all of them are not answered properly or closed. i first raised this issue on FlutterFire plugin , but it seems that Flutter Engineers beleives that issue comes from underlying SDK.
https://github.com/firebase/flutterfire/issues/11943

I am facing this right now on iOS simulator but with the same branch, same network , same user , it does not happen for android real device or emulator.
if i wait for some seconds or retry multiple times, the app initialization which reitrives configuration documents from firestore passes successfully.
i tried different approach like disabling the localPersistance on the setting or changing source on GetOptions of the DocumentReference but none of them works.
when i clear the state of the app and opening the app again (for example on e2e test), same error throws.

Honestly its like that firebase engineers expects this error but cannot do anything regarding that other than telling users to try again, by trying again definitly the data is fetched but its a bit late and cause bad user experience

### Reproducing the issue

Hard to reproduce as the problem happens time to time.

### Firebase SDK Version

10.15.0

### Xcode Version

15.0.1

### Installation Method

CocoaPods

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

### Relevant Log Output

```shell
flutter: [cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.
flutter: 	#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
flutter: 	#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
flutter: 	<asynchronous suspension>
flutter: 	#2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:510:43)
flutter: 	<asynchronous suspension>
flutter: 	#3      MethodChannelDocumentReference.get (package:cloud_firestore_platform_interface/src/method_channel/method_channel_document_reference.dart:69:42)
flutter: 	<asynchronous suspension>
flutter: 	#4      _JsonDocumentReference.get (package:cloud_firestore/src/document_reference.dart:148:7)
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by Ggayane** [comment]
I'm using react native and from yesterday my production app started behaving the same way you described, and again android side everything is working properly, but on iOS users can't even log-in... I'm getting these errors:
`[firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.`
`[auth/internal-error] An internal error has occurred, please try again.`

And the thing is it stated behave like this out of nowhere from yesterday, nothing has been changed from the code.

**Comment by Ggayane** [comment]
@arashgm my case resolved, turned out there were set some referrer restrictions on my API key, which shouldn't be there.

**Comment by arashgm** [comment]
> @arashgm my case resolved, turned out there were set some referrer restrictions on my API key, which shouldn't be there.

thanks for your input, restriction on Firebase API key usually leads to 403 and forbidden exception , maybe its just resolved for now in your case not always! but anyway my problem is also mentioned by others on different threads and the error comes and go and retrying the get calls, fix the issue so its not related definitly to Api retrictions for Us.

**Comment by cherylEnkidu** [comment]
Hi,

Sorry for your experience. This error is more likely coming from Flutter wrapper. However without a reproduction code, it is hard for Firestore or Flutter team to investigate the underlining cause. Could you please try to provide a minimum reproduction code?
