### ISSUE TITLE
Firebase Token is not getting fetched for the second time when the location is not provided in Swift

### ISSUE THREAD

**Issue by AswinMRathees** [firebase/firebase-ios-sdk#12150]
### Description

Hi, I am facing an issue with firebase token getting expired and signing out when the location services are turned off with swift. I have use schedulers internally to fetch the token. But its not getting updated. Also I have removed Firestore dependency as part of my project requirement

### Firebase SDK Version

10.16.0

### Xcode Version

15.0.1

### Installation Method

CocoaPods

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by morganchen12** [comment]
Can you share an example app that reproduces this issue?
