### ISSUE TITLE
Insecure functions `memcpy` and `malloc` used

### ISSUE THREAD

**Issue by patrickdunsheecubic** [firebase/firebase-ios-sdk#12157]
### Description

Use of functions `memcpy` and `malloc` create security vulnerabilities. Replacing those with `memcpy_s` and `calloc`, respectively, should close the security gaps.

### Firebase SDK Version

10.16.0

### Xcode Version

15.0.1

### Installation Method

CocoaPods

### Firebase Product(s)

All

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

Not relevant

### If using CocoaPods, the project's Podfile.lock

Not relevant

**Comment by paulb777** [comment]
Please search this issue list for specific instances of concern. We've analyzed multiple instances of these in the past and found no vulnerabilities. If you don't find it, open an issue that refers to a specific usage(s).
