### ISSUE TITLE
Support for Vision OS

### ISSUE THREAD

**Issue by AhsanAli65** [firebase/firebase-ios-sdk#12161]
### Description

Required Vision OS Support

### API Proposal

Support for All Firebase Products in Vision Platform

### Firebase Product(s)

Firestore

**Comment by paulb777** [comment]
Thanks for the feature request. There is currently community support for many of the Firebase products and have no near term plans to support all of Firebase products.  Please open a specific feature request for each product that you would like supported. I can leave this open to track updating our docs at https://firebase.google.com/docs/ios/learn-more#firebase_library_support_by_platform for visionOS

**Comment by paulb777** [comment]
Docs are now updated https://firebase.google.com/docs/ios/learn-more#firebase_library_support_by_platform.
