### ISSUE TITLE
Firestore Crashing

### ISSUE THREAD

**Issue by kiranb47** [firebase/firebase-ios-sdk#1216]
![screen shot 2018-05-03 at 4 02 08 pm](https://user-images.githubusercontent.com/13976093/39572072-70afe9a4-4eeb-11e8-84b6-9d724d26af2a.png)

Tried using Cocos Pod & Manually. Same issue. But working on a empty project without any other 3rd Party SDK's. My project is a game contains Facebook integration, Fabric, IronSrc, UnityAds, FAN, Admob & Cocos2dx.

**Comment by gsoltis** [comment]
Hi, can you provide the version of the Firestore SDK you're using? And can you try narrowing down which other SDK it's conflicting with (try an empty project with half of them, then the other half if that works)?

**Comment by kiranb47** [comment]
Hi, I’m using the most updated version available for download. I spent some time today by removing some sdks. But no luck. I will try some tomorrow.

**Comment by gsoltis** [comment]
Can you provide a copy of your `Podfile.lock` ?

**Comment by kiranb47** [comment]
Yes, Attached.

**Comment by gsoltis** [comment]
Hmm, it appears the attachment is not coming through. You might have to use the github web interface to do it?

**Comment by kiranb47** [comment]
[pod.zip](https://github.com/firebase/firebase-ios-sdk/files/1971869/pod.zip)

**Comment by kiranb47** [comment]
@gsoltis attached.

**Comment by kiranb47** [comment]
@gsoltis attached crashlog from fabric.
[games.spearmint.linesandhexa_issue_97_crash_9f7dcc3cf46445e481f73d4c335ce8e3_DNE_0_v2.txt](https://github.com/firebase/firebase-ios-sdk/files/1971878/games.spearmint.linesandhexa_issue_97_crash_9f7dcc3cf46445e481f73d4c335ce8e3_DNE_0_v2.txt)

**Comment by gsoltis** [comment]
Got it, thanks. I'll take a look. I'm looking to the possibility that you are hitting this issue, but I'm not sure yet: https://github.com/grpc/grpc/issues/6111

**Comment by kiranb47** [comment]
Definitely issue is coming from BoringSSL. Might be a OpenSSL conflicting issue.

**Comment by gsoltis** [comment]
Do you have a copy of openssl also being loaded by one of the other SDKs? I don't see it as an explicit dependency in your `Podfile`...

**Comment by gsoltis** [comment]
Ah, that looks like the culprit.

**Comment by gsoltis** [comment]
Yup, that makes sense. Unfortunately, your best bet may be to follow the instructions in the `gRPC` issue to cause it to build against OpenSSL.

**Comment by kiranb47** [comment]
Ok i will try. @gsoltis You know Cocos2dx is a widely using game engine. I hope you guys find a easy solution.

**Comment by kiranb47** [comment]
ok, thank you

**Comment by gsoltis** [comment]
@kiranb47 I'm going to close this issue in favor of the re-opened gRPC issue, as it's more properly addressed there.

I'll update your cocos2d issue as well with the link.
