### ISSUE TITLE
[FR]: Required Reason API Privacy manifest declaration

### ISSUE THREAD

**Issue by kgunderman** [firebase/firebase-ios-sdk#12163]
### Description

According to the apple docs: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

Starting in spring of 2024, libraries must declare the reasons they are using required reason API within the privacy manifest. As a library that uses the required reason API, are there plans to update the privacy manifest to include this reasoning?

### Firebase Product(s)

Firestore

**Comment by stoutatnerdery** [comment]
+1 on this

**Comment by ncooke3** [comment]
Hi, thanks for filing. This is already being tracked by https://github.com/firebase/firebase-ios-sdk/issues/11490. We are actively working on this and will have more to share in 2024. Please follow #11490 for updates.

**Comment by mikehardy** [comment]
Ah great thanks @ncooke3 - wasn't aware of the dupe it didn't turn up with the search terms I was using. I'll alter the related react-native-firebase issue where this came up so it's lined up
