### ISSUE TITLE
Thread Sanitizer data race warning

### ISSUE THREAD

**Issue by nthrussell** [firebase/firebase-ios-sdk#12183]
### Description

Hi Firebase team, recently I am getting this Thread Sanitizer Data Race warning from Xcode. When I run the app on simulator sometimes it gets freezes, it dosen't happen in real device although I am concerned it will be an issue in the real device as well. I am guessing this is from firebase sdk. Could you please have a look ?

<img width="1728" alt="Screenshot 2023-12-11 at 12 35 41 AM" src="https://github.com/firebase/firebase-ios-sdk/assets/10279255/37f8987d-393f-4b16-8ea2-0875b7ce57f8">

### Firebase SDK Version

10.15.0

### Xcode Version

15.0.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, App Check, Authentication, Crashlytics, Messaging

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by visumickey** [comment]
@nthrussell We tried reproducing this issue and we were not successful in replicating it. I tried this with an empty app written in Objective C and Swift integrated with both Cocoapods and Swift Package Manager - but with all these 4 cases, I'm unable to reproduce this. Can you please share a sample app where I can see this issue?

Note: I tried this on XCode 15.2 running on the most recent version of Firebase Performance.
