### ISSUE TITLE
Unable archive iOS app and error  'grpc/support/port_platform.h' file not found

### ISSUE THREAD

**Issue by surasit-int-trueid** [firebase/firebase-ios-sdk#12192]
### Description

I got an error as attachment file when I archive ios app that I want to prepare to upload appstore.
In this case I would like to add pod `FirebaseFirestore`  to the project on Xcode15.1 but I can't go next.

I did all the steps below to clean still not work for me
- clean build
- pod cache clean
- remove Derived Data
- remove Pods folder
- pod deintegrate and pod install

![Screenshot 2566-12-13 at 18 05 59](https://github.com/firebase/firebase-ios-sdk/assets/113904334/9e313eea-f0dc-45a2-9b32-b9bfddf9bfd1)

![Screenshot 2566-12-13 at 18 06 07](https://github.com/firebase/firebase-ios-sdk/assets/113904334/5c74eeed-3471-41e2-aee5-546404b2a5fd)

### Firebase SDK Version

10.18.0

### Xcode Version

15.1

### Installation Method

CocoaPods

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

**Comment by paulb777** [comment]
From the screenshot, it looks like the problem may be related to EFCMark. Perhaps namespace collisions between it and Firestore's grpc dependency.
