### ISSUE TITLE
"Position and width are ambiguous" runtime layout issue for UIInputSetHostView

### ISSUE THREAD

**Issue by liorazi** [firebase/firebase-ios-sdk#12207]
### Description

A layout issue appearing as a purple exclamation mark of a layout issue on a what appears to be a Firebase related view -
`UIInputSetHostView`.
It appears randomly when breaking using the "View Debug Hierarchy" option.
Note: Appeared on previous version also (10.3.0)

### Reproducing the issue

1. Run the app with the latest Firebase SDK installed (10.19.0)
2. Tap the "View Debug Hierarchy" button
3. Watch the layout issue displayed as a purple exclamation mark on 
`UITextEffectsWindow` -> `UIInputWindowController` -> `UIInputSetContainerView` -> `UIInputSetHostView`
4. Hover on the purple exclamation mark and watch the tooltip message: "Position and width are ambiguous"

![Screenshot 2023-12-18 at 17 46 29](https://github.com/firebase/firebase-ios-sdk/assets/2930153/094dece6-dce0-4210-b41c-49e08b39cd16)

### Firebase SDK Version

10.9.0

### Xcode Version

15.0.1

### Installation Method

CocoaPods

### Firebase Product(s)

All

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
@liorazi Sorry about the trouble. I'm not sure we can help, since there is nothing about Firebase described in the report. Please describe a problem with a specific Firebase API and fill out the issue template.

**Comment by liorazi** [comment]
my bad @paulb777 , is a Firebase hook/swizzle not enough?

**Comment by paulb777** [comment]
Firebase has very little interaction with UIKit. While it's possible there's an underlying Firebase issue, there is not enough info here to help us find it. We'll likely need a reproducible test case that demonstrates the issue.

**Comment by morganchen12** [comment]
@liorazi is this in FirebaseInAppMessaging?
