### ISSUE TITLE
Minified FirebaseFirestore datatypes (Map, List, etc.) in release mode (Flutter Web)

### ISSUE THREAD

**Issue by Nico1911** [firebase/firebase-ios-sdk#12212]
### Description

Every Firestore data I got in my flutter web (as e.g. in the stream below) were minified in release mode. In detail the runtimeTypes Map, List and Timestamp become "minified:...". In reference to the example below: Already the values of the DocumentSnapshot fields of snapshot.data are minified. I don't get any errors or special log output.

I´ve the newest Version of flutter, dart and android studio. My temporary workaround is to launch the website with:
flutter build web --profile --dart-define=Dart2jsOptimization=O0 --no-tree-shake-icons

but of course this is neither a solution to the problem nor a permanent method.
Thank you very much for your comments!

<img width="905" alt="Bildschirmfoto 2023-12-21 um 17 00 59" src="https://github.com/firebase/firebase-ios-sdk/assets/82755433/56921bcf-7a8f-439b-accc-8749ca41d44e">

### Reproducing the issue

I wish I knew exactly how this error came about. It occurs as soon as I simulate the website in release mode or publish it.

### Firebase SDK Version

10.7.1

### Xcode Version

15.1

### Installation Method

N/A

### Firebase Product(s)

App Check, Authentication, Firestore, Functions, Messaging, Performance, Storage

### Targeted Platforms

N/A

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment]
Hi @Nico1911, I think this issue is better suited for the https://github.com/firebase/flutterfire repo. Depending on what your dependency graph looks like, I'd recommend opening an issue either there or the https://github.com/firebase/firebase-js-sdk repo.

**Comment by ncooke3** [comment]
@Nico1911, since your description mentions Flutter– is the firebase-ios-sdk being built in this particular deployment you are having the issue with?

**Comment by Nico1911** [comment]
Hey ncooke3, thanks for your quick feedback. This is the first time I've posted a bug on Github (I'm not that familiar with it yet), so I obviously put it in the wrong section (I thought you post bugs in a central place for all sections of github). Thanks for your links, I will post the bug there!

**Comment by ncooke3** [comment]
No worries at all!
