### ISSUE TITLE
crashlytics crash report not displaying the userid on the firebase crashlytics dashboard

### ISSUE THREAD

**Issue by BitByAVampire** [firebase/firebase-ios-sdk#12211]
### Description

attached is the stacktrace from a crash report found with no userid set.  
[stacktrace.txt](https://github.com/firebase/firebase-ios-sdk/files/13732232/stacktrace100.txt)
It appears the crash is to do with something a 3rd party sdk is doing, and we have reason to believe we have already set this user's userid on crashlytics within the app's crashlytics sdk, and so we would like to ask to figure out what the possible issue is, if there's something that can be addressed on the crashlytics' side of things. 

the crash in the stacktrace is at line "Crashed: com.google.firebase.crashlytics.ios.exception"
### Reproducing the issue

no way imaginable for the crashlytics team to reproduce. 

### Firebase SDK Version

10.9.0

### Xcode Version

15.0.1

### Installation Method

CocoaPods

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reporting, @BitByAVampire. Based on the stack trace you shared, Crashlytics sometimes blames its own crash processing thread, but the crash is not actually caused by Crashlytics. WIth this, you may try catching this crash with an exception breakpoint if you can reproduce it locally.

**Comment by BitByAVampire** [comment]
My concern is that in the firebase craslytics dasboard i do not see the user id in the crash report for this crash but we believe the user for this user has been set to crashlytics.

**Comment by Dekay99** [comment]
> ### Description
> 
> attached is the stacktrace from a crash report found with no userid set.  
> [stacktrace.txt](https://github.com/firebase/firebase-ios-sdk/files/13732232/stacktrace100.txt)
> It appears the crash is to do with something a 3rd party sdk is doing, and we have reason to believe we have already set this user's userid on crashlytics within the app's crashlytics sdk, and so we would like to ask to figure out what the possible issue is, if there's something that can be addressed on the crashlytics' side of things. 
> 
> the crash in the stacktrace is at line "Crashed: com.google.firebase.crashlytics.ios.exception"
> ### Reproducing the issue
> 
> no way imaginable for the crashlytics team to reproduce. 
> 
> ### Firebase SDK Version
> 
> 10.9.0
> 
> ### Xcode Version
> 
> 15.0.1
> 
> ### Installation Method
> 
> CocoaPods
> 
> ### Firebase Product(s)
> 
> Crashlytics
> 
> ### Targeted Platforms
> 
> iOS
> 
> ### Relevant Log Output
> 
> _No response_
> 
> ### If using Swift Package Manager, the project's Package.resolved
> 
> 
> 
> <details>
> <summary>Expand <code>Package.resolved</code> snippet</summary>
> <br>
> 
> ```json
> 
> Replace this line with the contents of your Package.resolved.
> 
> ```
> 
> </details>
> 
> 
> ### If using CocoaPods, the project's Podfile.lock
> 
> 
> 
> <details>
> <summary>Expand <code>Podfile.lock</code> snippet</summary>
> <br>
> 
> ```yml
> 
> Replace this line with the contents of your Podfile.lock!
> 
> ```
> 
> </details>
> 

I found deep extensive documentation on this. Even had apple lie to my face at genuis bar and make a account on my Mac not tell me and supringly enough his shift just ended and also forgot the password he put in twice?

**Comment by BitByAVampire** [comment]
> > ### Description
> > attached is the stacktrace from a crash report found with no userid set.
> > [stacktrace.txt](https://github.com/firebase/firebase-ios-sdk/files/13732232/stacktrace100.txt)
> > It appears the crash is to do with something a 3rd party sdk is doing, and we have reason to believe we have already set this user's userid on crashlytics within the app's crashlytics sdk, and so we would like to ask to figure out what the possible issue is, if there's something that can be addressed on the crashlytics' side of things.
> > the crash in the stacktrace is at line "Crashed: com.google.firebase.crashlytics.ios.exception"
> > ### Reproducing the issue
> > no way imaginable for the crashlytics team to reproduce.
> > ### Firebase SDK Version
> > 10.9.0
> > ### Xcode Version
> > 15.0.1
> > ### Installation Method
> > CocoaPods
> > ### Firebase Product(s)
> > Crashlytics
> > ### Targeted Platforms
> > iOS
> > ### Relevant Log Output
> > _No response_
> > ### If using Swift Package Manager, the project's Package.resolved
> > 
> > 
> > Expand `Package.resolved` snippet
> > 
> > ```json
> > Replace this line with the contents of your Package.resolved.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > ### If using CocoaPods, the project's Podfile.lock
> > 
> > 
> > Expand `Podfile.lock` snippet
> > 
> > ```yaml
> > Replace this line with the contents of your Podfile.lock!
> > ```
> 
> I found deep extensive documentation on this. Even had apple lie to my face at genuis bar and make a account on my Mac not tell me and supringly enough his shift just ended and also forgot the password he put in twice?

sorry i don't think you answered my question

**Comment by rizafran** [comment]
Hi @BitByAVampire, I tried reproducing the issue by adding `Crashlytics.crashlytics().setUserID()` in my code, but the userID is showing in my Crashlytics dashboard. Is it possible for you to provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue?

**Comment by BitByAVampire** [comment]
@rizafran the stacktrace is caused by one of our 3rd party sdks, i cannot give you much info except that it is occurring due to a data recovery job on their end.

**Comment by themiswang** [comment]
Hey @BitByAVampire,

Without a reproduce strategy there will be less can do on our side. The stack trace does not contain any information about userID. One thing might be easier to help us debugging on your side, can you try:
- Add `-FIRDebugEnabled` argument to your debug run to enable debug log for Firebase. 
- Then search `Root:` on your console log, this will show you the root path for all your reports.
- Once you have updated userID, can you check under the root path: `v5/reports/active/SESSION_ID` your `internal_incremental_kv.clsrecored` has been updated?
