### ISSUE TITLE
Occasional permission errors in Firestore after addIDTokenDidChangeListener callback is called

### ISSUE THREAD

**Issue by fbarbat** [firebase/firebase-ios-sdk#12220]
### Description

Occasionally, with very low frequency, I see a `Missing or insufficient permissions (FIRFirestoreErrorDomain code 7)` error after a `addIDTokenDidChangeListener` callback execution.

It looks like Firestore is trying to refresh the token but something goes wrong and all document and query listeners start failing. We have retries and, while they actually solve the issue most of the time, we sometimes still hit the errors after 2 minutes of retries, leaving our app unusable so we crash.

### Reproducing the issue

Unfortunately, I don't have steps to reproduce the issue since this only happens in prod.

### Firebase SDK Version

10.11.0

### Xcode Version

14.2

### Installation Method

Zip

### Firebase Product(s)

Authentication, Firestore

### Targeted Platforms

macOS

### Relevant Log Output

```shell
This happens in prod so I don't have Firebase log output. This is part of the Sentry issues we have though. I removed many other listeners errors and their retries for simplicity. All the mentioned errors are Error Domain=FIRFirestoreErrorDomain Code=7 "Missing or insufficient permissions." UserInfo={NSLocalizedDescription=Missing or insufficient permissions. 

error
No retries available for the underlying AsyncThrowableStream. Aborting. Context: TeammatesQuery
Info
01:48:56

warning
Error detected on the underlying AsyncThrowableStream. Retrying. Context: TeammatesQuery
Info
01:48:02

warning
Error detected on the underlying AsyncThrowableStream. Retrying. Context: TeammatesQuery
Info
01:47:15

warning
Error detected on the underlying AsyncThrowableStream. Retrying. Context: TeammatesQuery
Info
01:46:45

warning
Error detected on the underlying AsyncThrowableStream. Retrying. Context: TeammatesQuery
Info
01:46:24

warning
Error detected on the underlying AsyncThrowableStream. Retrying. Context: TeammatesQuery
Info
01:46:04

warning
Error detected on the underlying AsyncThrowableStream. Retrying. Context: TeammatesQuery
Info
01:45:57

warning
Error detected on the underlying AsyncThrowableStream. Retrying. Context: TeammatesQuery
Info
01:45:56

login
IDTokenDidChange
{
idTokenDidChangeCount: 6, 
IDTokenHashValue: -5216570979953512000, 
user?.uid: *
}
Info
01:45:56

http
POST https://securetoken.googleapis.com/v1/token [200]
{
http.query: key=*, 
reason: no error, 
request_body_size: 230, 
response_body_size: 0
}
Info
01:45:56

login
IDTokenDidChange
{
idTokenDidChangeCount: 5, 
IDTokenHashValue: 6302277720668576000, 
user?.uid: *
}
Info
00:50:36

http
POST https://securetoken.googleapis.com/v1/token [200]
{
http.query: key=*, 
reason: no error, 
request_body_size: 230, 
response_body_size: 0
}
Info
00:50:36

login
IDTokenDidChange
{
idTokenDidChangeCount: 4, 
IDTokenHashValue: -1038857926168298900, 
user?.uid: *
}
Info
20:03:50

http
POST https://securetoken.googleapis.com/v1/token [200]
{
http.query: key=*, 
reason: no error, 
request_body_size: 230, 
response_body_size: 0
}
Info
20:03:50
```

**Comment by MarkDuckworth** [comment]
@fbarbat,

Since we don't have a reproduction or logs, can you provide some additional information for us.

- In your IDTokenDidChange listener, can you log any additional information on the token, such as the `expirationDate`, `authDate`, and `issuedAtDate`? Verify that these dates look accurate and are not expired when you encounter the issue.
- Are you using Firebase App Check? If so, we may have to investigate the App Check token.
- It is possible for you to update to the latest version of the Firebase SDK? This would give us confidence we are not working on an issue that is already fixed.

**Comment by fernando-remotion** [comment]
Thanks for the quick response. Absolutely, I can provide more information.

- I just started logging exp, auth_time, iat and other fields to verify what you suggested.
- We are not using App Check yet. We have the transitive dependency and it is monitoring on background as far as I understand it, but we haven't used it yet. 
- I just updated Firebase to the latest version (10.19.0)

I will update this issue once we hit this issue again.

Thank you.

**Comment by fbarbat** [comment]
I can get more information but it will take more than 5 days. Should I
reopen it once I have the new information?

**Comment by MarkDuckworth** [comment]
No problem. We will remove the "needs-info" label and keep the issue open.

**Comment by fbarbat** [comment]
Hey, after around two weeks of using Firebase 10.19.0 in prod in our app, we haven't hit this issue. We would hit this at least once per week so I think this was fixed. We did receive an issue from a client that hadn't updated yet, so that gives me more confidence that it was fixed. 
If we ever hit it again I will update this issue.
Thank you!
