### ISSUE TITLE
FirebaseFirestoreSwift & FirebaseFirestore imports not recognised in Xcode 14.1 resulting in code compiling errors.

### ISSUE THREAD

**Issue by ElrB** [firebase/firebase-ios-sdk#12275]
### Description

I am currently facing two issues in my code. 
1.  Consider below code snippet:
```swift
FirebaseReference(.Messages).document(documentId).collection(collectionId).whereField(kDATE, isGreaterThan: lastMessageDate).addSnapshotListener({ (querySnapshot, error) in
            guard let snapshot = querySnapshot else { return }
            for change in snapshot.documentChanges {
                if change.type == .added {
                    do {
                          let message = try change.document.data(as: LocalMessage.self) // Compiler error: "Argument passed to call that takes no arguments"


                     } catch {

                     }
                 }
            }
})
```

Regarding above code, I am getting error: Argument passed to call that takes no arguments, when I create a message obj.

2. Consider below code snippet:

```swift
do {                                                                                          
            try FirebaseReference(.Messages).document(channel.id).collection(channel.id).document(message.id).setData(from: message, encoder: Firestore.Encoder.init(), completion: { (error) in
                if let error = error {
                    let state = UIApplication.shared.applicationState
                    if state != .active {
                        NotificationManager.shared.scheduleNotification(title: "Message couldn't be sent", body: "\(message.message)")
                    }
                    completion(error)
                } else {

                   completion(nil)
               }
         })
} catch let error {
      print("catch block reached")
     completion(error) 
}
```

Regarding above code I get two compiler errors: 
 - Cannot find type 'Firestore' in scope @ code Firestore.Encoder.init()
 - No exact matches in call to instance method 'setData' @ code setData(from: 

Additional comments:
I am able to build and run the app successfully even with excode showing errors in code which is weird. 
This is code that previously use to work without a problem or errors when I use to use cocoa pods. 
This started happening when I started using swift package. 
I am unable to go back to cocoapods as I get error like: 
Error installing BoringSSL-GRPC
[!] /usr/bin/git clone https://github.com/google/boringssl.git /var/folders/z6/n1_2ll8n0k5gjc_7btxz1ffc0000gn/T/d20240114-27622-myg710 --template=.

In my file I do import
- FirebaseFirestore
- FirebaseFirestoreSwift
I have researched around any everyone seem to point to import the above but issue persists for me.

I have read prior issues opened here, but their final solution are somehow unclear. Although there is one solution that seem to point towards upgrading excode. Unfortunately, I am unable to do this as it would require me to update/buy a newer laptop that supports latest Xcode, which I cannot afford. Currently I use Xcode 14.1, the newest version my Mac can support.

### Firebase SDK Version

9.6.0

### Xcode Version

14.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Authentication, Crashlytics, Firestore, Functions, Messaging

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by andrewheard** [comment]
Hi @ElrB, are you able to reproduce this issue with Firebase 10.x (9.6.0 is from September, 2022)?

Note: You may be able to upgrade from Xcode 14.1 to 14.2, it is also supported on macOS 12 Monterey.

**Comment by paulb777** [comment]
Also, note that with recent versions, it is no longer necessary to import FirebaseFirestoreSwift. All the APIs are included in FirebaseFirestore.

**Comment by ElrB** [comment]
Thanks for the insights guys, much appreciated. I will be updating my Xcode to 14.2 (just checked that my Mac can take it). 

I will also try to get latest version with solution pointed out here (I tried to update normal way but could work) https://stackoverflow.com/questions/75718028/with-swift-package-manager-how-to-update-firebase-sdk-version

I will be back to let you know if I had some success with get the errors go away. Thanks again.

**Comment by ElrB** [comment]
Thanks guys. I updated Xcode to 14.2, and firebase package to 10.19 (updating firebase is what mainly resolved the issue). 

Side note: I firstly updated to 10.2 and issue why still there. Updating to newer resolved issue. 

You may close issue. Thanks again.

**Comment by ElrB** [comment]
Apologies for coming back to this one again. 
Although my code for adding codable objects to db is now working fine as before. The second issue I raised is not working as before, see code below:

FirebaseReference(.Recent).whereField(kCHATROOMID, isEqualTo: chatRoomId).getDocuments { (querySnapshot, error) in
            guard let documents = querySnapshot?.documents else {
                return
            }
            print("documents count: ", documents.count)
            let recents = documents.compactMap { (queryDocumentSnapshot) -> Recent? in
                return try? queryDocumentSnapshot.data(as: Recent.self)
            }
            
            print("recent count: ", recents.count)

}

The first print output is  2 documents, but when I try print out recents count is zero. 
queryDocumentSnapshot.data(as: doesn't seem to be working as before. The object Recent has the exact properties the objects retrieved from the database. 

Kindly assist me. Thanks.

**Comment by paulb777** [comment]
@ElrB Would you create a new Issue along with the Podfile.lock or Package.resolved file?
