### ISSUE TITLE
[FR]: Update CI to build for visionOS

### ISSUE THREAD

**Issue by andrewheard** [firebase/firebase-ios-sdk#12298]
### Description

After Xcode 15.2 is available on GitHub Actions (https://github.com/actions/runner-images/issues/9139), we should update our CI to build / test on visionOS.

This should allow us to produce xcframeworks with visionOS slices in the future (requested in #12024) and ensure that our existing SPM distribution (community-level support) continues to build.

### Targeted Platforms

visionOS

**Comment by paulb777** [comment]
Based on https://github.com/google/gtm-session-fetcher/pull/382, this may be doable now that macos-14 is available on GHA.

**Comment by paulb777** [comment]
See also https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/ and https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/

**Comment by paulb777** [comment]
Don in #12578 and #12608
