### ISSUE TITLE
While building for visionOS Simulator, no library for this platform was found in

### ISSUE THREAD

**Issue by JazKingX** [firebase/firebase-ios-sdk#12308]
### Description

When I am trying to add Apple Vision as a destination I am getting the following errors.

Error Message

While building for visionOS Simulator, no library for this platform was found in '/Users/name/Library/Developer/Xcode/DerivedData/app-dkslnywtifcaqzeiiiifmgmxxaqm/SourcePackages/artifacts/firebase-ios-sdk/FirebaseFirestoreInternal/FirebaseFirestoreInternal.xcframework'.

<img width="1511" alt="Screenshot 2024-01-23 at 00 08 00" src="https://github.com/firebase/firebase-ios-sdk/assets/21957803/a7fe64e9-8f47-4eaa-add3-ca7c2a7d9a73">

### Reproducing the issue

Create new VisionOS project, add firebase-ios-sdk via SPM, Run

### Firebase SDK Version

10.20.0

### Xcode Version

15.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Firestore

### Targeted Platforms

visionOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
See the instructions for building Firestore for visionOS at https://github.com/firebase/firebase-ios-sdk?tab=readme-ov-file#visionos

**Comment by naticio** [comment]
I opened my project from the terminal with the env variable and still didn't work! 

open --env FIREBASE_SOURCE_FIRESTORE=YES /path/to/your/project.xcodeproj

**Comment by paulb777** [comment]
@naticio  Please create a new issue with a filled out template.

**Comment by JazKingX** [comment]
@naticio This happened to me, however you need to close Xcode first not just the project. Then run the terminal command
