### ISSUE TITLE
Add XCFrameworks to all Firebase podspecs

### ISSUE THREAD

**Issue by lionel-alves** [firebase/firebase-ios-sdk#12314]
### Description

Hi,

A lot of the podspecs don't specify a XCFrameworks but they should all be available. 
Could we modify the podspec to add those, that will help a lot with build time.

Thanks!

### Firebase SDK Version

10.20

### Xcode Version

15.2

### Installation Method

CocoaPods

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

**Comment by paulb777** [comment]
@lionel-alves Thanks for the feature request

For most of Firebase we don't consider the build-time speedup worth the extra release and usage complexity.

Firestore is the one exception for which there is an externally supported solution at https://github.com/invertase/firestore-ios-sdk-frameworks (that is currently broken after 10.17.0)

**Comment by lionel-alves** [comment]
Hey @paulb777, thank you for your answer.

In [the firebase docs](https://firebase.google.com/docs/ios/installation-methods#integrate-manually) it is possible to download a zip with all the XCFrameworks.

I cannot use that unfortunately because I have other dependencies that that conflicts with those. (example: GoogleUtilities which is a dependency of many projects).

I am probably missing something obvious but why can't the podspec link those?

Thanks

**Comment by paulb777** [comment]
Binary podspecs are less flexible than source podspecs. For example, there's no way to support both Xcode and visionOS with a binary podspec.

**Comment by paulb777** [comment]
Going to close, since with more development moving to Swift Package Manager and no active development on CocoaPods, we do not want to increase our CocoaPods product surface area.
