### ISSUE TITLE
`Auth.auth().currentUser` always returns a user

### ISSUE THREAD

**Issue by danfar93** [firebase/firebase-ios-sdk#12321]
### Description

I’m using “Sign in with Apple” & `Auth.auth().currentUser` in the below code snippet always returns a user `(<FIRUser: 0x600002c18000>)` even after taking the following steps:

- Uninstalling the app & fresh install
- Removing the app from my allowed apps for Sign in with Apple
- Removing the user from the Firebase console.

```
 func userLoggedIn() -> Bool {
      if Auth.auth().currentUser != nil {
        return true
      } else {
        return false
      }
    }
```

### Firebase SDK Version

10.20.0

### Xcode Version

15.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json
{
  "pins" : [
    {
      "identity" : "abseil-cpp-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/abseil-cpp-binary.git",
      "state" : {
        "revision" : "bfc0b6f81adc06ce5121eb23f628473638d67c5c",
        "version" : "1.2022062300.0"
      }
    },
    {
      "identity" : "app-check",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/app-check.git",
      "state" : {
        "revision" : "3e464dad87dad2d29bb29a97836789bf0f8f67d2",
        "version" : "10.18.1"
      }
    },
    {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk.git",
      "state" : {
        "revision" : "b880ec8ec927a838c51c12862c6222c30d7097d7",
        "version" : "10.20.0"
      }
    },
    {
      "identity" : "googleappmeasurement",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleAppMeasurement.git",
      "state" : {
        "revision" : "ceec9f28dea12b7cf3dabf18b5ed7621c88fd4aa",
        "version" : "10.20.0"
      }
    },
    {
      "identity" : "googledatatransport",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleDataTransport.git",
      "state" : {
        "revision" : "a732a4b47f59e4f725a2ea10f0c77e93a7131117",
        "version" : "9.3.0"
      }
    },
    {
      "identity" : "googleutilities",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleUtilities.git",
      "state" : {
        "revision" : "bc27fad73504f3d4af235de451f02ee22586ebd3",
        "version" : "7.12.1"
      }
    },
    {
      "identity" : "grpc-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/grpc-binary.git",
      "state" : {
        "revision" : "a673bc2937fbe886dd1f99c401b01b6d977a9c98",
        "version" : "1.49.1"
      }
    },
    {
      "identity" : "gtm-session-fetcher",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/gtm-session-fetcher.git",
      "state" : {
        "revision" : "115f75e43851774934d695449a4836123c3246e1",
        "version" : "3.2.0"
      }
    },
    {
      "identity" : "interop-ios-for-google-sdks",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/interop-ios-for-google-sdks.git",
      "state" : {
        "revision" : "2d12673670417654f08f5f90fdd62926dc3a2648",
        "version" : "100.0.0"
      }
    },
    {
      "identity" : "leveldb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/leveldb.git",
      "state" : {
        "revision" : "9d108e9112aa1d65ce508facf804674546116d9c",
        "version" : "1.22.3"
      }
    },
    {
      "identity" : "nanopb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/nanopb.git",
      "state" : {
        "revision" : "819d0a2173aff699fb8c364b6fb906f7cdb1a692",
        "version" : "2.30909.0"
      }
    },
    {
      "identity" : "promises",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/promises.git",
      "state" : {
        "revision" : "e70e889c0196c76d22759eb50d6a0270ca9f1d9e",
        "version" : "2.3.1"
      }
    },
    {
      "identity" : "stripe-ios-spm",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/stripe/stripe-ios-spm",
      "state" : {
        "revision" : "20a5c91e76a671baaea4140b5359dfccc716a478",
        "version" : "23.21.1"
      }
    },
    {
      "identity" : "swift-protobuf",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-protobuf.git",
      "state" : {
        "revision" : "65e8f29b2d63c4e38e736b25c27b83e012159be8",
        "version" : "1.25.2"
      }
    }
  ],
  "version" : 2
}
```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
Does it help to call the `User.delete` API? 

https://firebase.google.com/docs/auth/ios/manage-users#delete_a_user

**Comment by danfar93** [comment]
Hey @paulb777 - I haven't tried that but I'm more trying to understand how it's holding onto the user after uninstalling the app & removing it from the Firebase console. I'm trying to determine when to display the "Sign In" screen and I would have assumed the user would need to login again after upon a fresh install? (especially if that user no longer exists in the console)

Also, if the user uninstalls the app I won't have the opportunity to call `User.delete`

Thanks!

**Comment by peterfriese** [comment]
Hi Dan,

Firebase Auth uses the keychain to persist authentication state across app restarts.

* Uninstalling the app & fresh install
It is my understanding that the auth information survives this scenario, and that is also what I would expect from an app - keep in mind iOS might offload the app - when the user taps on the app icon to re-install it, they expect the app to be in the same state as before, specifically their login state and any data they've stored in the app

* Removing the app from my allowed apps for Sign in with Apple
Can you provide more details on how you did this? When the user decides to delete their user account, you should revoke their auth tokens. See [Token revocation](https://firebase.google.com/docs/auth/ios/apple#token_revocation) for more details. 

To detect the case where the user went into their Apple ID dashboard and removed the app from the list of apps allowed to use Sign in Apple, you need to implement [token revocation detection](https://firebase.google.com/docs/auth/admin/manage-sessions#detect_id_token_revocation) on the client

* Removing the user from the Firebase console.
Same as above, implement [token revocation detection](https://firebase.google.com/docs/auth/admin/manage-sessions#detect_id_token_revocation) on the client

I covered most of this in a video - [Deleting user accounts (including Sign in with Apple token revocation) - YouTube](https://youtu.be/U1PIrZBgv0U?).

Let me know if this helps!

**Comment by danfar93** [comment]
Great, thanks @peterfriese ! That makes a lot of sense about keychain causing it to persist across app installs.

For removing the app from my allowed apps for Sign in with Apple:
- On the iOS Device, go to Apple ID Settings > Sign in & Security > Sign in with Apple

I'm actually less concerned about that case and I was more curious when I was looking into the issue behaviour by keychain but I'll look at implementing [Token revocation](https://firebase.google.com/docs/auth/ios/apple#token_revocation) in the future.

Thanks again!
