### ISSUE TITLE
[FR]: Privacy Manifest 

### ISSUE THREAD

**Issue by StartingZhou** [firebase/firebase-ios-sdk#12329]
### Description

Apple need Firebase SDK to provide an privacy manifest file and sign the sdk:
[Third Party List](https://developer.apple.com/support/third-party-SDK-requirements/)

When this feature will be included in new version?

Also, if firebase does not supply this file, can I summary the firebase used apis, and include these information to my app's `PrivacyInfo.xcprivacy` file?

Sorry for my poor english
Thanks for your effort

### Firebase Product(s)

Analytics, Crashlytics, DynamicLinks, Messaging

**Comment by paulb777** [comment]
This is a duplicate of #11490.

We're actively working on it now. Please follow progress at #11490

**Comment by StartingZhou** [comment]
> e actively working on it now. Please follow p

Ok Thank you
