### ISSUE TITLE
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason '+[FBLPromise onQueue:do:]: unrecognized selector sent to class 0x103bd0510'

### ISSUE THREAD

**Issue by shravanteegala** [firebase/firebase-ios-sdk#12331]
### Description

Hi team,
iam getting below exception .
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason '+[FBLPromise onQueue:do:]:bunrecognized selector sent to class 0x103bd0510'

### Reproducing the issue

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason '+[FBLPromise onQueue:do:]:bunrecognized selector sent to class 0x103bd0510'

### Firebase SDK Version

10.16

### Xcode Version

15.2

### Installation Method

Carthage

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

**Comment by paulb777** [comment]
Did you add the `-ObjC` flag as documented at https://github.com/firebase/firebase-ios-sdk/blob/main/Carthage.md?

**Comment by shravanteegala** [comment]
yes i added -Objc flag. but getting same issue.

**Comment by paulb777** [comment]
The flag is actually `-ObjC`. It is case sensitive.
