### ISSUE TITLE
Xcode 15.2 compoile issue

### ISSUE THREAD

**Issue by kushdixit** [firebase/firebase-ios-sdk#12346]
### Description

Hi team
I updated my MacOS SONOMA and xcode 15.2 and now I am facing following compile issue:Call to undeclared function - 'OSAtomicCompareAndSwapPtrBarrier'; ISO C99 and later do not support implicit function declarations**
Declaration of 'OSAtomicCompareAndSwapPtrBarrier' must be imported from module 'Darwin.libkern.OSAtomic' before it is required
and many more.

Pod version: Installing FirebaseMessaging (4.7.1)

### Firebase SDK Version

4.7.1

### Xcode Version

15.2

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, Messaging, Remote Config

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @kushdixit, based on the info you shared, it seems like you're using an outdated SDK version. Does updating the [SDK](https://firebase.google.com/support/release-notes/ios) make any difference?

**Comment by kushdixit** [comment]
I am supporting iOS 11 for my app so I did not update SDK. Let me try for that.
