### ISSUE TITLE
No such module "FirebaseAnalytics"

### ISSUE THREAD

**Issue by ivanBalychev** [firebase/firebase-ios-sdk#12361]
### Description

No such module "FirebaseAnalytics" when install it via cocoapods

<img width="385" alt="Снимок экрана 2024-02-06 в 15 40 19" src="https://github.com/firebase/firebase-ios-sdk/assets/18113448/0ede0abc-747f-44ac-8df6-8c11aa5b990a">
<img width="271" alt="Снимок экрана 2024-02-06 в 15 41 19" src="https://github.com/firebase/firebase-ios-sdk/assets/18113448/beba7155-8701-4d17-94d8-2edeabc846fd">
<img width="1163" alt="Снимок экрана 2024-02-06 в 15 41 35" src="https://github.com/firebase/firebase-ios-sdk/assets/18113448/903a319e-2250-45a0-bde9-288944c1cbca">

### Firebase SDK Version

10.20

### Xcode Version

15.2

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
The Xcode static analysis isn't always accurate. Please try to build the project. Also, share the `Podfile` and `Podfile.lock`.

**Comment by ivanBalychev** [comment]
Podfile
`source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'

use_frameworks!

def shared
  
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'TTTAttributedLabel'
  pod 'TPKeyboardAvoiding'
  
  pod 'Shimmer'
  
  pod 'SwiftyMarkdown'
  
  pod 'Siren'
  
  pod 'CCBottomRefreshControl'
  
  pod 'FacebookCore'
  pod 'FirebaseCore'
  pod 'FirebaseAnalytics'
  pod 'FirebaseCrashlytics'
  
  pod 'SelligentMobileSDK', :git => 'https://github.com/SelligentMarketingCloud/MobileSDK-iOS.git', :tag => '2.6.2'
  
end

target '---' do
  shared
end

target '---' do
  shared
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
        xcconfig_path = config.base_configuration_reference.real_path
        xcconfig = File.read(xcconfig_path)
        xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
        File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
      end
    end
  end
end
`

**Comment by ivanBalychev** [comment]
Podfile.lock

`PODS:
  - Alamofire (5.8.1)
  - CCBottomRefreshControl (0.5.2)
  - FacebookCore (0.9.0):
    - FBSDKCoreKit (~> 5.0)
  - FBSDKCoreKit (5.15.1):
    - FBSDKCoreKit/Basics (= 5.15.1)
    - FBSDKCoreKit/Core (= 5.15.1)
  - FBSDKCoreKit/Basics (5.15.1)
  - FBSDKCoreKit/Core (5.15.1):
    - FBSDKCoreKit/Basics
  - FirebaseAnalytics (10.20.0):
    - FirebaseAnalytics/AdIdSupport (= 10.20.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (10.20.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleAppMeasurement (= 10.20.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseCore (10.20.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.12)
    - GoogleUtilities/Logger (~> 7.12)
  - FirebaseCoreExtension (10.20.0):
    - FirebaseCore (~> 10.0)
  - FirebaseCoreInternal (10.20.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseCrashlytics (10.20.0):
    - FirebaseCore (~> 10.5)
    - FirebaseInstallations (~> 10.0)
    - FirebaseSessions (~> 10.5)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.8)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (~> 2.1)
  - FirebaseInstallations (10.20.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)
  - FirebaseSessions (10.20.0):
    - FirebaseCore (~> 10.5)
    - FirebaseCoreExtension (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.10)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesSwift (~> 2.1)
  - GoogleAppMeasurement (10.20.0):
    - GoogleAppMeasurement/AdIdSupport (= 10.20.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/AdIdSupport (10.20.0):
    - GoogleAppMeasurement/WithoutAdIdSupport (= 10.20.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/WithoutAdIdSupport (10.20.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleDataTransport (9.3.0):
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/AppDelegateSwizzler (7.12.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (7.12.0):
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/Logger (7.12.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (7.12.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (7.12.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.12.0)"
  - GoogleUtilities/Reachability (7.12.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (7.12.0):
    - GoogleUtilities/Logger
  - Kingfisher (7.10.2)
  - nanopb (2.30909.1):
    - nanopb/decode (= 2.30909.1)
    - nanopb/encode (= 2.30909.1)
  - nanopb/decode (2.30909.1)
  - nanopb/encode (2.30909.1)
  - PromisesObjC (2.3.1)
  - PromisesSwift (2.3.1):
    - PromisesObjC (= 2.3.1)
  - SelligentMobileSDK (2.6.2):
    - SelligentMobileSDK/Core (= 2.6.2)
  - SelligentMobileSDK/Core (2.6.2)
  - Shimmer (1.0.2)
  - Siren (5.7.1)
  - SwiftyMarkdown (1.2.4)
  - TPKeyboardAvoiding (1.3.5)
  - TTTAttributedLabel (2.0.0)

DEPENDENCIES:
  - Alamofire
  - CCBottomRefreshControl
  - FacebookCore
  - FirebaseAnalytics
  - FirebaseCore
  - FirebaseCrashlytics
  - Kingfisher
  - SelligentMobileSDK (from `https://github.com/SelligentMarketingCloud/MobileSDK-iOS.git`, tag `2.6.2`)
  - Shimmer
  - Siren
  - SwiftyMarkdown
  - TPKeyboardAvoiding
  - TTTAttributedLabel

SPEC REPOS:
  https://github.com/CocoaPods/Specs.git:
    - Alamofire
    - CCBottomRefreshControl
    - FacebookCore
    - FBSDKCoreKit
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreExtension
    - FirebaseCoreInternal
    - FirebaseCrashlytics
    - FirebaseInstallations
    - FirebaseSessions
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleUtilities
    - Kingfisher
    - nanopb
    - PromisesObjC
    - PromisesSwift
    - Shimmer
    - Siren
    - SwiftyMarkdown
    - TPKeyboardAvoiding
    - TTTAttributedLabel

EXTERNAL SOURCES:
  SelligentMobileSDK:
    :git: https://github.com/SelligentMarketingCloud/MobileSDK-iOS.git
    :tag: 2.6.2

CHECKOUT OPTIONS:
  SelligentMobileSDK:
    :git: https://github.com/SelligentMarketingCloud/MobileSDK-iOS.git
    :tag: 2.6.2

SPEC CHECKSUMS:
  Alamofire: 3ca42e259043ee0dc5c0cdd76c4bc568b8e42af7
  CCBottomRefreshControl: 389780b4488321c91d18f66a6da5ef9606df6de5
  FacebookCore: ba86524b66cfa86d0f8e65d08faa8504a9f732dd
  FBSDKCoreKit: 1d5acf7c9d7a2f92bb1a242dc60cae5b7adb91df
  FirebaseAnalytics: a2731bf3670747ce8f65368b118d18aa8e368246
  FirebaseCore: 28045c1560a2600d284b9c45a904fe322dc890b6
  FirebaseCoreExtension: 0659f035b88c5a7a15a9763c48c2e6ca8c0a2977
  FirebaseCoreInternal: efeeb171ac02d623bdaefe121539939821e10811
  FirebaseCrashlytics: 81530595edb6d99f1918f723a6c33766a24a4c86
  FirebaseInstallations: 558b1da7d65afeb996fd5c814332f013234ece4e
  FirebaseSessions: 2f348975f6d1c139231c180e12194161da2e0cd6
  GoogleAppMeasurement: bb3c564c3efb933136af0e94899e0a46167466a8
  GoogleDataTransport: 57c22343ab29bc686febbf7cbb13bad167c2d8fe
  GoogleUtilities: 0759d1a57ebb953965c2dfe0ba4c82e95ccc2e34
  Kingfisher: 99edc495d3b7607e6425f0d6f6847b2abd6d716d
  nanopb: d4d75c12cd1316f4a64e3c6963f879ecd4b5e0d5
  PromisesObjC: c50d2056b5253dadbd6c2bea79b0674bd5a52fa4
  PromisesSwift: 28dca69a9c40779916ac2d6985a0192a5cb4a265
  SelligentMobileSDK: d061119b81c9c9b6ec900ecbbcf85d7af18c749e
  Shimmer: c5374be1c2b0c9e292fb05b339a513cf291cac86
  Siren: 76ac728f4f2f4a3576c322272e94a0e37955664f
  SwiftyMarkdown: 7cdec87c6ab5cd9ea0e22ced288e889960649ba5
  TPKeyboardAvoiding: d55b3ea7b362540af8fcf36aa3ed2e87bf210cc6
  TTTAttributedLabel: 8cffe8e127e4e82ff3af1e5386d4cd0ad000b656

PODFILE CHECKSUM: cc30b8049978046908ff9030ca43b587cef42bee

COCOAPODS: 1.15.1
`

**Comment by paulb777** [comment]
Thanks for sharing. 

Looks like you're running into a CocoaPods regression with the latest release. https://github.com/CocoaPods/CocoaPods/issues

Please use CocoaPods 1.14.3 or earlier.

**Comment by lexuanquynh** [comment]
@paulb777  thanks.

**Comment by paulb777** [comment]
CocoaPods 1.15.2 is now available with the fix.
