### ISSUE TITLE
Why does Firebase/Messaging import AddressBook if it doesn't use it?

### ISSUE THREAD

**Issue by cyupa** [firebase/firebase-ios-sdk#1236]
I just noticed that the Firebase Messaging podspec links AddressBook but it doesn't use it.
Is there any reason behind it?
https://github.com/firebase/firebase-ios-sdk/blob/38824e721ebaa3f50e443e1ea4b47d34030e4703/FirebaseMessaging.podspec#L39

**Comment by morganchen12** [comment]
@chliangGoogle seems like we can remove this reference.
