### ISSUE TITLE
[FIR configure]. why  we  use this method called in Main Thread. is it possible to run Background Thread.?.

### ISSUE THREAD

**Issue by shravanteegala** [firebase/firebase-ios-sdk#12382]
### Description

[FIR configure]. why  this method called in Main Thread. is it possible to run Background Thread.
when i run it in Main Thread it freezes the UI some times. so is it any way or any chances to move to Back ground thread.
please help me.

### Firebase SDK Version

10.16

### Xcode Version

15.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

All

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by shravanteegala** [comment]
using my Firebase Version: 7.4.0

**Comment by paulb777** [comment]
The Firebase products are designed for `configure` to run on the main thread at start up.

However, it's an issue if there's a lag. If you can share a reproducible test case of a laggy startup or an Instruments log, we can investigate.

**Comment by shravanteegala** [comment]
<img width="1435" alt="AppLaunch1" src="https://github.com/firebase/firebase-ios-sdk/assets/13646977/0ebc66dc-ec65-44c6-b59a-7d375eef65cf">

**Comment by shravanteegala** [comment]
<img width="1435" alt="AppLaunch1" src="https://github.com/firebase/firebase-ios-sdk/assets/13646977/2dd0abd3-8f81-4bbc-8709-4fdf42dbdc10">

**Comment by paulb777** [comment]
Thanks for the Instruments log.

The delay looks related to Crashlytics start up or reporting. Assigning to the Crashlytics team to determine if this is expected or not and if it's something that could be done off of the main thread.

**Comment by morganchen12** [comment]
@shravanteegala the version of Firebase you're using is very old. Is this reproducible on the latest Firebase version (10.x)?

**Comment by shravanteegala** [comment]
@morganchen12 ,  i will check and confirm after updating latest version.
