### ISSUE TITLE
[FR]: Apple privacy manifest file

### ISSUE THREAD

**Issue by sborovikov-belkacar** [firebase/firebase-ios-sdk#12389]
### Description

1. Having this manifest will be a requirement from Apple starting in spring 2024. 
https://developer.apple.com/support/third-party-SDK-requirements/

### Firebase Product(s)

AB Testing, Analytics, Authentication, Crashlytics, DynamicLinks, Firestore, Installations, Messaging, Remote Config

**Comment by peterfriese** [comment]
Duplicate of #11490
