### ISSUE TITLE
Xcode 15.3b3: app installation failed due to missing Info.plist

### ISSUE THREAD

**Issue by doroshenko** [firebase/firebase-ios-sdk#12390]
### Description

Installing an app on a simulator or a device using the latest Xcode beta fails due a missing `Info.plist` with Firebase version `10.21.0`. The problem is solved when downgrading to `10.19.0`. I assume it's related to the removal of this file mentioned in the release notes here: https://firebase.google.com/support/release-notes/ios#version_10200_-_january_16_2023

The framework is included through SPM. I've tried clearing project and SPM caches, and resetting the simulator, but the issue persists.

### Firebase SDK Version

10.21.0

### Xcode Version

15.3b3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Please try again later. Failed to load Info.plist from bundle at path /Users/<snip>/Library/Developer/CoreSimulator/Devices/FE2E39CC-56A1-41B2-AB52-8C7E3F4B0483/data/Library/Caches/com.apple.mobile.installd.staging/temp.WoIC6R/extracted/Payload/<snip>.app/Frameworks/GoogleAppMeasurement.framework; Extra info about "/Users/<snip>/Library/Developer/CoreSimulator/Devices/FE2E39CC-56A1-41B2-AB52-8C7E3F4B0483/data/Library/Caches/com.apple.mobile.installd.staging/temp.WoIC6R/extracted/Payload/<snip>.app/Frameworks/GoogleAppMeasurement.framework/Info.plist": Couldn't stat /Users/<snip>/Library/Developer/CoreSimulator/Devices/FE2E39CC-56A1-41B2-AB52-8C7E3F4B0483/data/Library/Caches/com.apple.mobile.installd.staging/temp.WoIC6R/extracted/Payload/<snip>.app/Frameworks/GoogleAppMeasurement.framework/Info.plist: No such file or directory
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
@doroshenko Thanks for the report. 

Did you also clear the project's DerivedData? Does it make a difference to use an earlier version of Xcode?

**Comment by ncooke3** [comment]
In addition to Paul's above recommendations, I recommend cleaning the SwiftPM cache at `~/Library/Caches/org.swift.swiftpm/repositories`

**Comment by doroshenko** [comment]
I've done another series of tests, making sure to clear SPM caches and DerivedData folders between every run.

The issue is not present in Xcode 15.1 (stable). The app builds and runs fine with the framework version `10.21.0`
The issue is present in Xcode 15.3 beta 2 and beta 3. The app builds fine, but I get an error mentioning `Info.plist` when attempting to install and run it on a device. Same framework version `10.21.0`

**Comment by paulb777** [comment]
Thanks for sharing the investigation @doroshenko.

We're working on restoring the Info.plist files for the next release.

**Comment by kushsolitary** [comment]
Hello, any updates on this? I am also facing the same issue.

**Comment by ncooke3** [comment]
Hi @kushsolitary, could you try updating to 10.2**2**.0? The issue should be fixed on that version.

**Comment by kushsolitary** [comment]
> Hi @kushsolitary, this issue will be fixed in the upcoming 10.2**2**.0 release. Until then, downgrading to 10.19.0 should unblock your workflow.

thank you, downgrading to 10.19.0 worked!

**Comment by kushsolitary** [comment]
@ncooke3 BTW, I am using SPM and the version 10.22.0 is not available there.

**Comment by ChrisGarmanJD** [comment]
FYI Also occurring on Xcode 15.3 RC - the tip to downgrade worked!

**Comment by Wallman** [comment]
Works great with 10.22, thanks

**Comment by brntbeer** [comment]
As someone just learning Swift, it's great to find issues like this to remind myself that after new xcode releases, i may have to right-click to `update package` 😃 

Thanks!

**Comment by diamont1001** [comment]
Works great with 10.22+, thanks
