### ISSUE TITLE
We'll likely need repro steps to investigate this crash. The object being released in `objc_release` would be very helpful.

### ISSUE THREAD

**Issue by anilMakhijaEnphase** [firebase/firebase-ios-sdk#12392]
We'll likely need repro steps to investigate this crash. The object being released in `objc_release` would be very helpful.

_Originally posted by @morganchen12 in https://github.com/firebase/firebase-ios-sdk/issues/12076#issuecomment-1802437446_

**Comment by rizafran** [comment]
This seems like a duplicate of #12393. I'll be closing this as a duplicate.
