### ISSUE TITLE
Random crash [TAGRuntime evaluateEvent:]

### ISSUE THREAD

**Issue by qaasx** [firebase/firebase-ios-sdk#12406]
### Description

I sending events to Analytics, but random crashes appear for regardless of the event or parameters.
I am also using 'GoogleTagManager', '7.4.3' in my project

Thread 1 Queue : com.apple.main-thread (serial)
com.apple.uikit.eventfetch-thread (6)com.apple.NSURLConnectionLoader (11)Thread 25Thread 32Thread 33Thread 34Thread 35 Queue : TagManagerContainerQueue (serial)
#0	0x0000000280018020 in 0x280018020 ()
#1	0x00000001959e3848 in JSC::Interpreter::executeCall(JSC::JSObject*, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) ()
#2	0x000000019529d36c in JSObjectCallAsFunction ()
#3	0x0000000195204b24 in -[JSValue invokeMethod:withArguments:] ()
#4	0x0000000104cd71bc in -[TAGRuntime evaluateEvent:] ()
#5	0x0000000104cc9c08 in __29-[TAGContainer processEvent:]_block_invoke ()
#6	0x000000010a9f80f0 in _dispatch_call_block_and_release ()
#7	0x000000010a9f993c in _dispatch_client_callout ()
#8	0x000000010aa01bd8 in _dispatch_lane_serial_drain ()
#9	0x000000010aa0291c in _dispatch_lane_invoke ()
#10	0x000000010aa0f2f8 in _dispatch_root_queue_drain_deferred_wlh ()
#11	0x000000010aa0e754 in _dispatch_workloop_worker_thread ()
#12	0x0000000109f9b924 in _pthread_wqthread ()
Enqueued from TagManagerQueue (Thread 34) Queue : TagManagerQueue (serial)
#0	0x000000010a9fec68 in dispatch_async ()
#1	0x0000000104cc9aa8 in -[TAGContainer processEvent:] ()
#2	0x0000000104cd5744 in __39-[TAGManager maybeLoadDefaultContainer]_block_invoke_3 ()
#3	0x000000010a9f80f0 in _dispatch_call_block_and_release ()
#4	0x000000010a9f993c in _dispatch_client_callout ()
#5	0x000000010aa01bd8 in _dispatch_lane_serial_drain ()
#6	0x000000010aa0291c in _dispatch_lane_invoke ()
#7	0x000000010aa0f2f8 in _dispatch_root_queue_drain_deferred_wlh ()
#8	0x000000010aa0e754 in _dispatch_workloop_worker_thread ()
#9	0x0000000109f9b924 in _pthread_wqthread ()
#10	0x0000000109f9a6e4 in start_wqthread ()
Enqueued from com.google.fira.worker (Thread 35) Queue : com.google.fira.worker (serial)
#0	0x000000010a9fec68 in dispatch_async ()
#1	0x0000000104cd55f8 in __39-[TAGManager maybeLoadDefaultContainer]_block_invoke_2 ()
#2	0x0000000104c65738 in -[APMMeasurement logEventOnWorkerQueueWithOrigin:isPublicEvent:name:parameters:timestamp:enabled:ignoreEnabled:ignoreInterceptor:interceptor:addedScreenParameters:] ()
#3	0x0000000104c65498 in __151-[APMMeasurement logEventWithOrigin:isPublicEvent:name:parameters:timestamp:enabled:ignoreEnabled:ignoreInterceptor:interceptor:addedScreenParameters:]_block_invoke ()
#4	0x0000000104cba5fc in __51-[APMScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke ()
#5	0x000000010a9f80f0 in _dispatch_call_block_and_release ()
#6	0x000000010a9f993c in _dispatch_client_callout ()
#7	0x000000010aa01bd8 in _dispatch_lane_serial_drain ()
#8	0x000000010aa0291c in _dispatch_lane_invoke ()
#9	0x000000010aa0f2f8 in _dispatch_root_queue_drain_deferred_wlh ()
#10	0x000000010aa0e754 in _dispatch_workloop_worker_thread ()
#11	0x0000000109f9b924 in _pthread_wqthread ()
#12	0x0000000109f9a6e4 in start_wqthread ()
Thread 36Thread 37Thread 38Thread 39Thread 40com.google.Maps.LabelingBehavior (41)Thread 42Thread 43Thread 44Thread 45Thread 46Thread 47Thread 48JavaScriptCore libpas scavenger (49)

### Firebase SDK Version

10.21.0

### Xcode Version

15.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
This looks like a GoogleTagManager crash. Please file a report with that [product](https://support.google.com/tagmanager/community).
