### ISSUE TITLE
Remote Config not producing throttling error accurately

### ISSUE THREAD

**Issue by aj2109** [firebase/firebase-ios-sdk#12435]
### Description

In trying to add non fatal logging specifically for throttling I have discovered what appears to be a bug.  Whilst the error status of the connection is 429, as shown in the logs, and the catch let error as RemoteConfig hitting, its error code is never that of throttling (8002), its always internal errors code (8003).  (minimumFetchInterval = 0 seconds btw)

Thanks!

### Reproducing the issue

```
func forceThrottle() async {
        let RemoteConfig = RemoteConfig.remoteConfg()
       do {
       for i in 0...1000 {
          let foo = try await remoteConfig.fetchAndActivate()
       }
       } catch let error as RemoteConfigError {
       //prints false
           print("Error code is correct: \(error.code == .throttled)")
       } catch {}
}

```
### Firebase SDK Version

10.21.0

### Xcode Version

15.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

AB Testing, Analytics, App Distribution, Crashlytics, Performance, Remote Config

### Targeted Platforms

iOS

### Relevant Log Output

```shell
10.21.0 - [FirebaseRemoteConfig][I-RCN000026] RCN fetch failure. Response http error code: 429
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reporting, @aj2109. I tried to reproduce the issue and I was able to get the same error code (8003). I'll be raising this to our engineers to investigate.

**Comment by paulb777** [comment]
Internally tracked at b/327637888
