### ISSUE TITLE
Mac Catalyst - FirebaseFirestoreSwift file error - No such module 'FirebaseFirestore'

### ISSUE THREAD

**Issue by JazKingX** [firebase/firebase-ios-sdk#12461]
### Description

Only when building for Mac Catalyst I am getting the following error for FirebaseFirestoreSwift file. 

<img width="1223" alt="Screenshot 2024-03-04 at 00 12 40" src="https://github.com/firebase/firebase-ios-sdk/assets/21957803/1b6b4486-14f8-416b-a9e1-a2bb1990a6d4">

I have made sure the libraries are included both all platforms

<img width="1059" alt="Screenshot 2024-03-04 at 00 17 55" src="https://github.com/firebase/firebase-ios-sdk/assets/21957803/69193934-5ce1-4e9c-9e69-de8fb9b11653">
 

### Firebase SDK Version

10.21

### Xcode Version

15.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Firestore

### Targeted Platforms

macCatalyst

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment]
@JazKingX, could you try removing the the project's dependency on FirebaseFirestore**Swift**? The module is no longer needed if you depend on FirebaseFirestore.

**Comment by JazKingX** [comment]
@ncooke3 I have removed FirebaseFirestoreSwift from Frameworks, Libraries and embedded frameworks, as well as only selected iOS when included but still no luck. On adding Firebase via SPM I have selected not include the module but that didn't work either.

**Comment by JazKingX** [comment]
@ncooke3 I have removed FirebaseFirestoreSwift from Frameworks, Libraries and embedded frameworks, as well as only selected iOS when included but still no luck. On adding Firebase via SPM I have selected not include the module but that didn't work either.

**Comment by paulb777** [comment]
@JazKingX After removing FirebaseFirestoreSwift, what error are you seeing? The one in the OP is from FirebaseFirestoreSwift.
