### ISSUE TITLE
Xcode 15 is't able to identify Privacy file 

### ISSUE THREAD

**Issue by manohara347** [firebase/firebase-ios-sdk#12470]
### Description

I have added GoogleDataTransport.xcframework to the project and generate privacy report I am still getting error like "The archive does not contain any PrivacyInfo.xcprivacy files"
Any solution for this? Also I noticed you guys have added "GoogleDataTransport_Privacy.bundle" but when I archive it's not added in the final bundle of the app. I am using Xcode 15.

some of the frameworks are distributed as static frameworks do we need to add privacy-file in the app for those?

Any recommendations?

### Reproducing the issue

1. create any sample app  2. Add the GoogleDataTransport.xcframework in framework section and archive the project and generate privacy report and it throws error like "The archive does not contain any PrivacyInfo.xcprivacy files" even though i see GoogleDataTransport_Privacy.bundle contains the privacy file.

### Firebase SDK Version

10.22.0

### Xcode Version

15

### Installation Method

Zip

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
"The archive does not contain any PrivacyInfo.xcprivacy files"
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by manohara347** [comment]
I am able to see report after adding the Embed & Sign. But this is static framework why we have to Embed & Sign this results into bump in the bundle size?

**Comment by manohara347** [comment]
Thanks for the response, If we are integrating this using cocoapods then we don't have option to change to Embed & Sign how to solve for that scenarios?

**Comment by ncooke3** [comment]
>  If we are integrating this using cocoapods then we don't have option to change to Embed & Sign how to solve for that scenarios?

For CocoaPods that vend a static framework, there is workaround where you can specify a resource bundle in the podspec and that will ensure the resource bundle is embedded in the app bundle. In this case, only the resource bundle in the podspec will be embedded as CocoaPods will not embed the static framework vended by the pod.

**Comment by manohara347** [comment]
Thanks for the response. Is Apple ok with adding resources in bundle? is any documentation from apple regarding this? How you guys taking care of this for Swift Package manager we don't have option to add resources in binary binaryTarget(name:path:), binaryTarget(name:url:checksum:)?

**Comment by ncooke3** [comment]
> Is Apple ok with adding resources in bundle? is any documentation from apple regarding this?

From what I've heard, this approach is acceptable. I don't think there is official Apple documentation about privacy manifests and resource bundles though. I do not know anything about how Apple will enforce the specifics on a technical level.

> How you guys taking care of this for Swift Package manager we don't have option to add resources in binary binaryTarget(name:path:), binaryTarget(name:url:checksum:)?

There was an undocumented, subtle behavior change in Xcode 15.3 where binary targets vending static xcframeworks will be automatically embedded.

**Comment by ManoharaReddyP** [comment]
Thanks @ncooke3, All my queries are resolved.
