### ISSUE TITLE
Events are not getting tracked properly- Analytics Dashboard

### ISSUE THREAD

**Issue by gupta515** [firebase/firebase-ios-sdk#12486]
### Description

We utilize Firebase Analytics to monitor events within our app. However, we've observed that certain crucial events are not appearing on the analytics dashboard and for few events we don't see appropriate numbers.

We attempted to debug this issue and verified that the events are indeed being sent to the Firebase console. We can observe them in the Debug view as well.

![image](https://github.com/firebase/firebase-ios-sdk/assets/5191294/ea687b9b-f04b-459b-9914-4230b037f217)

![image](https://github.com/firebase/firebase-ios-sdk/assets/5191294/a998abed-49bf-4498-979d-a822d5cc41e1)

Few such events

### Reproducing the issue

Initiated various events from our application, and some are not being recorded or tracked. This has been the ongoing issue for the past few months.

### Firebase SDK Version

10.11.0

### Xcode Version

15.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

{
  "identity": "firebase-ios-sdk",
  "kind": "remoteSourceControl",
  "location": "git@github.com:firebase/firebase-ios-sdk.git",
  "state": {
    "revision": "e700a8f40c87c31cab7984875fcc1225d96b25bf",
    "version": "10.11.0"
  }
}
</details>

**Comment by morganchen12** [comment]
Since the SDK is sending them to Firebase correctly, this is likely a project/console issue. You should [file a support ticket](https://firebase.google.com/support/troubleshooter/analytics/help) instead so Firebase staff can examine your project information.
