### ISSUE TITLE
Firebase 5.0.0 will not compile when Cocoapods `use_modular_headers!` is enabled

### ISSUE THREAD

**Issue by stevenp** [firebase/firebase-ios-sdk#1248]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.3
  * Firebase SDK version: 5.0.0
  * Firebase Component: Core, Auth
  * Component version: 5.0.0
  * Cocoapods 1.5.0

### [REQUIRED] Step 3: Describe the problem

When including the Auth pod for version 5.0.0, in Coocapods 1.5.0, a header error occurs and the project can't be compiled. This happens when the new `use_modular_headers!` directive is enabled in the Podfile.

`/Users/xxxx/TestFirebaseInstall/Pods/FirebaseAuth/Firebase/Auth/Source/FIRAuthAPNSTokenManager.m:19:9: 'FirebaseCore/FIRLogger.h' file not found`

#### Steps to reproduce:

Add `Firebase/Auth` to a project using Cocoapods 1.5.0.
Make sure `use_modular_headers!` is enabled.
Install the pod and attempt to build the project. The compile will fail.

#### Relevant Code:
Example project attached:

[TestFirebaseInstall.zip](https://github.com/firebase/firebase-ios-sdk/files/1986829/TestFirebaseInstall.zip)

**Comment by paulb777** [comment]
@stevenp Thanks for the report!

The short answer is to wait for CocoaPods 1.5.1.

You're seeing https://github.com/CocoaPods/CocoaPods/issues/7596. The 1.5.0 modular headers implementation changed the semantics of private headers and that got [fixed for 1.5.1](https://github.com/CocoaPods/CocoaPods/issues/7599).

There are some [other serious issues](https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md) `use_modular_headers!` in 1.5.0, so if you want to use it now, I recommend using [CocoaPods master](https://github.com/CocoaPods/CocoaPods) or its [1.5 stable branch](https://github.com/CocoaPods/CocoaPods/tree/1-5-stable).

Hopefully 1.5.1 will be published in the next few days.

**Comment by paulb777** [comment]
Actually the new patch release is CocoaPods 1.5.2. 

It's now available for install and I confirmed it fixes this issue.
