### ISSUE TITLE
Privacy Manifest file is missing for FirebasePerformance

### ISSUE THREAD

**Issue by lakshmankreditbee** [firebase/firebase-ios-sdk#12488]
### Description

When updating to version 10.22.0 of the Firebase Performance SDK, it seems that the manifest file for this SDK is missing. Additionally, the SDK uses "NSUserDefaults" API for some specific reason which requires a manifest. [https://developer.apple.com/documentation/foundation/nsuserdefaults]()

### Firebase SDK Version

10.22.0

### Xcode Version

15.0

### Installation Method

CocoaPods

### Firebase Product(s)

AB Testing, Analytics, Authentication, Crashlytics, Installations, Messaging, Performance, Remote Config

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment]
Thank for reporting. Firebase 10.22.0 only published manifests for SDKs named by Apple on [this list](https://developer.apple.com/support/third-party-SDK-requirements/). We're still working on the Firebase SDKs that are not on that list.

**Comment by jesus-mg-ios** [comment]
@ncooke3, Is Firestore using any data listed in NSPrivacyAccessedAPICategoryFileTimestamp?

**Comment by ncooke3** [comment]
Hi @jesus-mg-ios, no–– not in the latest release.

**Comment by jayeshkawli** [comment]
@ncooke3 Thanks for the input. Do you know if there is an issue or a PR to keep track of progress? I am a user of FirebasePerformance library and want to check in if the privacy info is indeed needed for it and if we could somehow get notified of the progress.

**Comment by ncooke3** [comment]
Are folks on this thread using package managers other than CocoaPods? And, if you are using CocoaPods, are you using `use_frameworks!` or `use_frameworks! :link=>:static` in your Podfile?

**Comment by Digipom** [comment]
I'm using Swift PM on my end (via Xcode's package dependencies)

**Comment by jayeshkawli** [comment]
@ncooke3 I am using CocoaPods with `use_frameworks!` in the podfile.

**Comment by lakshmankreditbee** [comment]
@ncooke3  using CocoaPods with `use_frameworks!` in the podfile.

**Comment by jayeshkawli** [comment]
@ncooke3 Any updates on this? Thanks!
