### ISSUE TITLE
Firebase and GoogleAdsMobile Migration To SPM for Privacy Manifest

### ISSUE THREAD

**Issue by vonghiep** [firebase/firebase-ios-sdk#12493]
### Description

As you know, starting from 1/5/2024, if you using SDK in your project you need to have a Privacy Manifest to get your app approved. From [Firebase 10.22](https://github.com/firebase/firebase-ios-sdk/issues/11490), App Privacy Manifest is supported. And I'm updating my current Firebase to 10.22

According to the [Release Note](https://firebase.google.com/support/release-notes/ios#version_10220_-_march_4_2024) seem like the privacy manifests only added in the SPM version. Correct me if I misunderstand this.

So I migrate it from Cocoapods to SPM.
But the problem is here, my Project using Firebase, Google Mobile Ads and mediation: GoogleMobileAdsMediationUnity. I can easily migrate Firebase and Google Mobile Ads to SPM, but GoogleMobileAdsMediationUnity is not supported 

```
Key Point: Mediation adapter libraries are not yet available on Swift Package Manager. If you use [mediation](https://developers.google.com/admob/ios/mediation), we recommend integrating with CocoaPods.
```

As a result, it remains in the pods, but when using it, a dependency will be added: PromiseObjC, to be specify the module `module FBLPromises` will be created. And in SPM, Firebase will also installed Promise which also created the module `module FBLPromises`, this trigger an IDE Error `Redefinition of module 'FBLPromises'`

Anyone facing the same problem? And what is your approaching to solve it?

### Firebase SDK Version

10.22

### Xcode Version

15.0.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Crashlytics, DynamicLinks, Messaging, Remote Config

### Targeted Platforms

iOS

**Comment by paulb777** [comment]
Thanks for the report. This looks like a documentation problem in the release notes. Privacy Manifests are supported with CocoaPods.

And it's not supported to mix CocoaPods and SPM.

@ncooke3 @morganchen12  Please correct the release notes.

**Comment by paulb777** [comment]
The release notes are now correct - https://firebase.google.com/support/release-notes/ios

Sorry for the confusion @vonghiep and thanks for letting us know!
