### ISSUE TITLE
[FR]: Request build to "Do Not Embed"

### ISSUE THREAD

**Issue by bforrose** [firebase/firebase-ios-sdk#12495]
### Description

We have confirmed that the privacy manifests update has been made in Firebase 10.22.0 version.
I read README.md and it says to build by choosing "Embed & Sign".
If this happens, I think the framework will be duplicated into the app. Because the Firebase SDK appears to be a static framework.
(Add to .app and Copy to .app/Frameworks/)

How do I apply xcframework as "Do Not Embed"?
If I build to "Do Not Embed", the Privacy Report does not have a Firebase Report.

### Firebase Product(s)

Analytics, Crashlytics

**Comment by ncooke3** [comment]
Hi @bforrose, embedding a static framework on Xcode 15 functions differently than in previous Xcode versions.

> I think the framework will be duplicated into the app

If you inspect the app bundle, you may see a `FirebaseCrashlytics.framework/FirebaseCrashlytics` executable but this is actually an empty dylib that Xcode swaps the static archive in for during a build phase. This can be checked by running `file /path/to/app/Frameworks/FirebaseCrashlytics.framework/FirebaseCrashlytics` and `nm -gU /path/to/app/Frameworks/FirebaseCrashlytics.framework/FirebaseCrashlytics` (should output that there are no symbols). The empty dylib shouldn't significantly affect app size.

From https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes:
> Fixed: Embedding a static framework using a Copy Files build phase **now removes the static archive from the framework when it is embedded in the target bundle**. The REMOVE_STATIC_EXECUTABLES_FROM_EMBEDDED_BUNDLES build setting can be set to NO to opt out of this behavior. The COPY_RESOURCES_FROM_STATIC_FRAMEWORKS build setting, previously used in the legacy build system to extract and copy the resources from a static framework to the target bundle, no longer has any effect with the new build system as the entire framework is copied instead (minus the static archive as described above). (47164939)

**Comment by bforrose** [comment]
I understand what you shared, and thank you.
