### ISSUE TITLE
Archive Release fails again with 10.22.1

### ISSUE THREAD

**Issue by houmie** [firebase/firebase-ios-sdk#12507]
### Description

This is the the same issue that was reported here: https://github.com/firebase/firebase-ios-sdk/issues/12441, sadly closed and can't be reopened.

Despite following the instructions and installing the latest `10.22.1` version, I still get this error message, when trying to Archive for release:

<img width="693" alt="Screenshot 2024-03-09 at 14 25 29" src="https://github.com/firebase/firebase-ios-sdk/assets/1832933/a0759f4a-190a-40d9-9b04-337c5b096841">

```
2024-03-09 14:31:51 +0000 [MT] Upload for archive iOS-Release had issues:
(
    "<IDEDistributionIssue: severity(error), error(Error Domain=ContentDelivery Code=90208 \"Asset validation failed\" UserInfo={IDEDistributionIssueSeverity=3, NSLocalizedDescription=Asset validation failed, NSLocalizedRecoverySuggestion=Invalid Bundle. The bundle xxx.app/Frameworks/GoogleMobileAds.framework does not support the minimum OS Version specified in the Info.plist. (ID: 6ca59c66-6b9b-4ea3-899d-3fcc75156cbf)})>",
    "<IDEDistributionIssue: severity(error), error(Error Domain=ContentDelivery Code=90208 \"Asset validation failed\" UserInfo={IDEDistributionIssueSeverity=3, NSLocalizedDescription=Asset validation failed, NSLocalizedRecoverySuggestion=Invalid Bundle. The bundle xxx.app/Frameworks/UserMessagingPlatform.framework does not support the minimum OS Version specified in the Info.plist. (ID: 878656ec-0ad1-46c5-94d2-6eb3d76ffce8)})>"
)
```

It is possible that this is causing a side effect due to UMP (Google's User Messaging Platform) for handling GDPR.

### Reproducing the issue

Product -> Archive -> Release in Xcode.

### Firebase SDK Version

10.22.1

### Xcode Version

Version 15.3 (15E204a)

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Crashlytics

### Targeted Platforms

iOS

### Relevant Log Output

2024-03-09 14:31:51 +0000 [MT] Upload for archive iOS-Release had issues:
(
    "<IDEDistributionIssue: severity(error), error(Error Domain=ContentDelivery Code=90208 \"Asset validation failed\" UserInfo={IDEDistributionIssueSeverity=3, NSLocalizedDescription=Asset validation failed, NSLocalizedRecoverySuggestion=Invalid Bundle. The bundle xxx.app/Frameworks/GoogleMobileAds.framework does not support the minimum OS Version specified in the Info.plist. (ID: 6ca59c66-6b9b-4ea3-899d-3fcc75156cbf)})>",
    "<IDEDistributionIssue: severity(error), error(Error Domain=ContentDelivery Code=90208 \"Asset validation failed\" UserInfo={IDEDistributionIssueSeverity=3, NSLocalizedDescription=Asset validation failed, NSLocalizedRecoverySuggestion=Invalid Bundle. The bundle xxx.app/Frameworks/UserMessagingPlatform.framework does not support the minimum OS Version specified in the Info.plist. (ID: 878656ec-0ad1-46c5-94d2-6eb3d76ffce8)})>"
)
```

### If using Swift Package Manager, the project's Package.resolved
```
{
  "pins" : [
    {
      "identity" : "abseil-cpp-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/abseil-cpp-binary.git",
      "state" : {
        "revision" : "df308b8b46607675f2b9ec8e569109008f9155ce",
        "version" : "1.2022062300.1"
      }
    },
    {
      "identity" : "app-check",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/app-check.git",
      "state" : {
        "revision" : "3e464dad87dad2d29bb29a97836789bf0f8f67d2",
        "version" : "10.18.1"
      }
    },
    {
      "identity" : "cocoalumberjack",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/CocoaLumberjack/CocoaLumberjack",
      "state" : {
        "revision" : "4b8714a7fb84d42393314ce897127b3939885ec3",
        "version" : "3.8.5"
      }
    },
    {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk",
      "state" : {
        "revision" : "be49849dcba96f2b5ee550d4eceb2c0fa27dade4",
        "version" : "10.22.1"
      }
    },
    {
      "identity" : "googleappmeasurement",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleAppMeasurement.git",
      "state" : {
        "revision" : "482cfa4e5880f0a29f66ecfd60c5a62af28bd1f0",
        "version" : "10.22.1"
      }
    },
    {
      "identity" : "googledatatransport",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleDataTransport.git",
      "state" : {
        "revision" : "a637d318ae7ae246b02d7305121275bc75ed5565",
        "version" : "9.4.0"
      }
    },
    {
      "identity" : "googleutilities",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleUtilities.git",
      "state" : {
        "revision" : "26c898aed8bed13b8a63057ee26500abbbcb8d55",
        "version" : "7.13.1"
      }
    },
    {
      "identity" : "grpc-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/grpc-binary.git",
      "state" : {
        "revision" : "ea4cb5cc0c39c732b85386263116d2e2fdbbdc61",
        "version" : "1.49.2"
      }
    },
    {
      "identity" : "gtm-session-fetcher",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/gtm-session-fetcher.git",
      "state" : {
        "revision" : "76135c9f4e1ac85459d5fec61b6f76ac47ab3a4c",
        "version" : "3.3.1"
      }
    },
    {
      "identity" : "interop-ios-for-google-sdks",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/interop-ios-for-google-sdks.git",
      "state" : {
        "revision" : "2d12673670417654f08f5f90fdd62926dc3a2648",
        "version" : "100.0.0"
      }
    },
    {
      "identity" : "keychainaccess",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/kishikawakatsumi/KeychainAccess",
      "state" : {
        "branch" : "master",
        "revision" : "e0c7eebc5a4465a3c4680764f26b7a61f567cdaf"
      }
    },
    {
      "identity" : "leveldb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/leveldb.git",
      "state" : {
        "revision" : "43aaef65e0c665daadf848761d560e446d350d3d",
        "version" : "1.22.4"
      }
    },
    {
      "identity" : "nanopb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/nanopb.git",
      "state" : {
        "revision" : "b7e1104502eca3a213b46303391ca4d3bc8ddec1",
        "version" : "2.30910.0"
      }
    },
    {
      "identity" : "nvactivityindicatorview",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/ninjaprox/NVActivityIndicatorView",
      "state" : {
        "revision" : "bcb52371f2259254bac6690f92bb474a61768c47",
        "version" : "5.1.1"
      }
    },
    {
      "identity" : "promises",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/promises.git",
      "state" : {
        "revision" : "540318ecedd63d883069ae7f1ed811a2df00b6ac",
        "version" : "2.4.0"
      }
    },
    {
      "identity" : "swift-log",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-log",
      "state" : {
        "revision" : "e97a6fcb1ab07462881ac165fdbb37f067e205d5",
        "version" : "1.5.4"
      }
    },
    {
      "identity" : "swift-package-manager-google-mobile-ads",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/googleads/swift-package-manager-google-mobile-ads.git",
      "state" : {
        "revision" : "ef8d21fc890eed1727195632d63a9333b9949253",
        "version" : "11.1.0"
      }
    },
    {
      "identity" : "swift-package-manager-google-user-messaging-platform",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/googleads/swift-package-manager-google-user-messaging-platform.git",
      "state" : {
        "revision" : "668673ea23b3e71b9f2540d8fb9464c4dc32ecc0",
        "version" : "2.2.0"
      }
    },
    {
      "identity" : "swift-protobuf",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-protobuf.git",
      "state" : {
        "revision" : "65e8f29b2d63c4e38e736b25c27b83e012159be8",
        "version" : "1.25.2"
      }
    },
    {
      "identity" : "tun2sockskit",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/EbrahimTahernejad/Tun2SocksKit",
      "state" : {
        "revision" : "48ed2dafaf41c02caaacdcb7007f7e8d646f41b2",
        "version" : "3.6.7"
      }
    },
    {
      "identity" : "wireguard-apple",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/mullvad/wireguard-apple",
      "state" : {
        "branch" : "mullvad-master",
        "revision" : "11a00c20dc03f2751db47e94f585c0778c7bde82"
      }
    }
  ],
  "version" : 2
}
```

### If using CocoaPods, the project's Podfile.lock

N/A

**Comment by paulb777** [comment]
GoogleMobileAds and UserMessagingPlatform are not part of Firebase. 

Please follow the open issue at https://github.com/googleads/swift-package-manager-google-mobile-ads/issues/62.
