### ISSUE TITLE
Firestore build warnings

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#12516]
### Description

    - WARN  | xcodebuild:  FirebaseFirestoreInternal/Firestore/core/src/local/index_backfiller.cc:61:48: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'int' [-Wshorten-64-to-32]
    - WARN  | xcodebuild:  FirebaseFirestoreInternal/Firestore/core/src/local/index_backfiller.cc:64:36: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'int' [-Wshorten-64-to-32]
    - WARN  | xcodebuild:  FirebaseFirestoreInternal/Firestore/core/src/remote/bloom_filter.cc:81:10: warning: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'int32_t' (aka 'int') [-Wshorten-64-to-32]

### Reproducing the issue

Build and check warnings

### Firebase SDK Version

10.23.0

### Xcode Version

15.3

### Installation Method

CocoaPods

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by cherylEnkidu** [comment]
https://github.com/firebase/firebase-ios-sdk/pull/12536
