### ISSUE TITLE
 Heap corruption detected, free list is damaged

### ISSUE THREAD

**Issue by oglerma** [firebase/firebase-ios-sdk#12518]
### Description

Our firebase crashlytics produced these errors that we can't seem to reproduce but we have a few reported on our console. 

<img width="1005" alt="Screenshot 2024-03-11 at 12 56 23 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/28022602/d2155dd5-d658-4ec1-a01b-fbfac70afd07">
<img width="1232" alt="Screenshot 2024-03-11 at 12 56 04 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/28022602/d6c74016-b8c0-4f6b-ae95-19ac5e21b086">

Stack trace:
[stackTrace.txt](https://github.com/firebase/firebase-ios-sdk/files/14564060/stackTrace.txt)

### Reproducing the issue

N/A

### Firebase SDK Version

10.22.1

### Xcode Version

15.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Storage

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
Is this still an issue with Firebase 11.x?

**Comment by oglerma** [comment]
I am not seeing this issue anymore i will close this ticket.
