### ISSUE TITLE
Blank Unity app with Firebase Podfile dependency crashing on startup

### ISSUE THREAD

**Issue by puddleglum56** [firebase/firebase-ios-sdk#12523]
### Description

I have been struggling for a while trying to get a Unity app on iOS with ARCore Extensions working. Firebase is a dependency of ARCore Extensions.

I believe I've tracked the issue down to a minimal environment with:
- A blank Unity build for iOS based on their 3D template
- Firebase installed via Podfile

I created this environment by building the blank 3D template as an iOS project in Unity, moving a Podfile with Firebase dependency into the built project, `pod install`, and building with Xcode.

I don't seem to be getting a crash log for this minimal environment in iOS Analytics, but I'm attaching the crash log .ips for a previous iteration, along with a previous app's log. Both of these apps were build from Unity projects fully configured with ARCore Extensions. The crash has always been due to a segmentation fault.

Fully configured project log:
[app_log.txt](https://github.com/firebase/firebase-ios-sdk/files/14567308/app_log.txt)

Fully configured project .ips log:
[ips_log.txt](https://github.com/firebase/firebase-ios-sdk/files/14567319/ips_log.txt)

### Reproducing the issue

[Minimal repro Xcode project folder](https://drive.google.com/drive/folders/11Rh2FaiowbbHLtuy-Tw9I3hMUjrzZYOR?usp=sharing)
[Minimal repro deployment folder](https://drive.google.com/drive/folders/1_XJnBy5r2ISvzeOPNYppPQDKh3ZnvdBx?usp=sharing)
[ARCore extensions and Firebase fully configured project ipa](https://drive.google.com/drive/folders/1RSn4PirlLTqaTkOzu_4jy3xeKVZ8KldB?usp=drive_link)

### Firebase SDK Version

10.22.0

### Xcode Version

15.2

### Installation Method

CocoaPods

### Firebase Product(s)

All

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

PODS:
  - Firebase (10.22.0):
    - Firebase/Core (= 10.22.0)
  - Firebase/Core (10.22.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 10.22.0)
  - Firebase/CoreOnly (10.22.0):
    - FirebaseCore (= 10.22.0)
  - FirebaseAnalytics (10.22.0):
    - FirebaseAnalytics/AdIdSupport (= 10.22.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (10.22.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleAppMeasurement (= 10.22.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - FirebaseCore (10.22.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.12)
    - GoogleUtilities/Logger (~> 7.12)
  - FirebaseCoreInternal (10.22.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseInstallations (10.22.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)
  - GoogleAppMeasurement (10.22.0):
    - GoogleAppMeasurement/AdIdSupport (= 10.22.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - GoogleAppMeasurement/AdIdSupport (10.22.0):
    - GoogleAppMeasurement/WithoutAdIdSupport (= 10.22.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - GoogleAppMeasurement/WithoutAdIdSupport (10.22.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - GoogleUtilities/AppDelegateSwizzler (7.13.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
    - GoogleUtilities/Privacy
  - GoogleUtilities/Environment (7.13.0):
    - GoogleUtilities/Privacy
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/Logger (7.13.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Privacy
  - GoogleUtilities/MethodSwizzler (7.13.0):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/Network (7.13.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Privacy
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.13.0)":
    - GoogleUtilities/Privacy
  - GoogleUtilities/Privacy (7.13.0)
  - GoogleUtilities/Reachability (7.13.0):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/UserDefaults (7.13.0):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - nanopb (2.30910.0):
    - nanopb/decode (= 2.30910.0)
    - nanopb/encode (= 2.30910.0)
  - nanopb/decode (2.30910.0)
  - nanopb/encode (2.30910.0)
  - PromisesObjC (2.4.0)

DEPENDENCIES:
  - Firebase

SPEC REPOS:
  trunk:
    - Firebase
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreInternal
    - FirebaseInstallations
    - GoogleAppMeasurement
    - GoogleUtilities
    - nanopb
    - PromisesObjC

SPEC CHECKSUMS:
  Firebase: 797fd7297b7e1be954432743a0b3f90038e45a71
  FirebaseAnalytics: 8d0ff929c63b7f72260f332b86ccf569776b75d3
  FirebaseCore: 0326ec9b05fbed8f8716cddbf0e36894a13837f7
  FirebaseCoreInternal: bca337352024b18424a61e478460547d46c4c753
  FirebaseInstallations: 763814908793c0da14c18b3dcffdec71e29ed55e
  GoogleAppMeasurement: ccefe3eac9b0aa27f96066809fb1a7fe4b462626
  GoogleUtilities: d053d902a8edaa9904e1bd00c37535385b8ed152
  nanopb: 438bc412db1928dac798aa6fd75726007be04262
  PromisesObjC: f5707f49cb48b9636751c5b2e7d227e43fba9f47

PODFILE CHECKSUM: 8eb5d9779943356726afcf7311dd07da7acd8da2

COCOAPODS: 1.15.2

**Comment by rizafran** [comment]
Hi @puddleglum56, per checking, it seems like your issue is related to Firebase Unity SDK. Please file a ticket on the [Unity repository](https://github.com/firebase/firebase-unity-sdk/issues) and provide the needed information. I'll now be closing this.

**Comment by puddleglum56** [comment]
Hi @rizafran, maybe you could help me understand the problem more. Basically, whenever I add the [ARCore Extensions package for Unity](https://github.com/google-ar/arcore-unity-extensions) and configure it for iOS it adds a Podfile with Firebase dependencies. I am not importing any packages from the Firebase Unity SDK, rather, I think these are purely Podfile dependencies. Whenever I tried to make an MRE, I ended up with a blank Unity project (again, with no Firebase Unity SDK packages installed) and a Podfile with the Firebase dependency. I made an issue here as opposed to the Unity repo because, from my understanding, these dependencies are being added and handled outside of Unity by Cocoapods.
