### ISSUE TITLE
Prebuilt frameworks for 10.22.1

### ISSUE THREAD

**Issue by spqw** [firebase/firebase-ios-sdk#12529]
### Description

I am expecting to find prebuilt frameworks under the Github release `Firebase Apple 10.22.1`
I don't see any
Where can I find them?

### Firebase SDK Version

10.22.1

### Xcode Version

15.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Crashlytics

### Targeted Platforms

iOS, macOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
We did not republish the zip distribution in 10.22.1. It will be available with 10.23.0.

the workaround is to access the corrected GoogleAppMeasurementOnDeviceConversion xcframework from the link in the podspec - https://github.com/firebase/firebase-ios-sdk/blob/main/GoogleAppMeasurementOnDeviceConversion.podspec#L20. (or to use Xcode 15.2 or earlier)
