### ISSUE TITLE
Asset Validation (Invalid Minimum OSVersion) Issue persists in 10.22.1

### ISSUE THREAD

**Issue by sharva89** [firebase/firebase-ios-sdk#12521]
### Description

While submission of the app the error of Asset Validation continue to persist - 

**Asset Validation Failed**
Invalid minimumOSVersion. Apps that only support 64-bit devices must specify a deployment target of 8.0 or later.  MinimumOSVersion in 'My App.app/Frameworks/abseil.framework' is "."

**Asset Validation Failed**
Invalid minimumOSVersion. Apps that only support 64-bit devices must specify a deployment target of 8.0 or later.  MinimumOSVersion in 'My App.app/Frameworks/BoringSSL-GRPC.framework' is "."

and so on...

### Firebase SDK Version

10.22.1

### Xcode Version

15.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

All

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment]
From https://github.com/firebase/firebase-ios-sdk/issues/12475#issuecomment-1988694462:

Please update your SPM workspace to pull in the below dependencies:

abseil v1.2022062300.1 (abseil: https://github.com/google/abseil-cpp-binary.git @ 1.2022062300.1
gRPC: https://github.com/google/grpc-binary.git @ 1.49.2

**Comment by sharva89** [comment]
worked for me ! thanks
