### ISSUE TITLE
10.22.1 not available on Cocoapods

### ISSUE THREAD

**Issue by tdroback** [firebase/firebase-ios-sdk#12546]
### Description

The latest version available on Cocoapods is still 10.22.0

### Firebase SDK Version

10.22.1

### Xcode Version

15.0.1

### Installation Method

CocoaPods

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
10.22.1 was a limited patch release that only changed the FirebaseAnalyticsOnDeviceConversion pod. 

Details at https://firebase.google.com/support/release-notes/ios
