### ISSUE TITLE
[FR]: vision os is still not supported??

### ISSUE THREAD

**Issue by kotran88** [firebase/firebase-ios-sdk#12541]
### Description

I added dependency...and have error saying 
Firebase Firestore's binary SPM distribution does not support visionOS

I updated xcode to latest version. but still have problem. 

### Firebase Product(s)

Database

**Comment by ncooke3** [comment]
Hi @kotran88, you're correct that visionOS is not supported in the binary distribution. Firebase's binary distributions (including the Firestore one you are trying to use) is still being built with Xcode 14. Please follow updates in #12024.
