### ISSUE TITLE
Crash on GoogleDataTransport's version 9.3, while using firebase sdk to catch crash log, [GDTCORDirectorySizeTracker calculateDirectoryContentSize] 

### ISSUE THREAD

**Issue by ZGilbert** [firebase/firebase-ios-sdk#12544]
### Description

![20240313-204519](https://github.com/firebase/firebase-ios-sdk/assets/6862142/99d87eb3-49e9-4000-b4ef-86acd3d3f94a)

### Firebase SDK Version

10.20.0

### Xcode Version

15.2

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, Crashlytics, DynamicLinks, Performance

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml
[Podfile.lock.zip](https://github.com/firebase/firebase-ios-sdk/files/14587872/Podfile.lock.zip)


```

</details>

**Comment by paulb777** [comment]
We may need a reproducible test case to help with this. What is version 9.2?

**Comment by ZGilbert** [comment]
@paulb777 thank you, the lib GoogleDataTransport, which is a dependency of FirebaseCrashlytics, you can download the  file podfile.lock by the urll https://github.com/firebase/firebase-ios-sdk/files/14587872/Podfile.lock.zip to see more of it

**Comment by paulb777** [comment]
OK I see. The requirement for GoogleDataTransport from Firebase is a minimum of 9.2, but 9.3 is actually used.

**Comment by ZGilbert** [comment]
So it is, and now it is catched 13 crashes.
![image](https://github.com/firebase/firebase-ios-sdk/assets/6862142/1da0e190-20af-4c90-a6f4-d91e21b34857)

**Comment by ZGilbert** [comment]
Some Infos of The crashes may help:
device: iPhone 13 Pro Max
device_os: iOS 16.3.1
RAM:  255.88 MB
thanks a lot

**Comment by ncooke3** [comment]
Hi @ZGilbert, are you able to share a complete stack trace? I'm curious what the other threads are doing at the time of the crash.
