### ISSUE TITLE
Cocoapods and Apple Privacy Manifest

### ISSUE THREAD

**Issue by vonghiep** [firebase/firebase-ios-sdk#12542]
### Description

this is a brief of my pod file
```
platform :ios, '15.0'

def firebase_common
  pod 'Firebase/Analytics', '7.7.0'
  pod 'Firebase/Crashlytics', '7.7.0'
end

def firebase_messaging
  pod 'Firebase/Messaging', '7.7.0'
end

target 'Main' do 
  # other pods go here

  firebase_common
  firebase_messaging
end

target 'Extension1' do
  firebase_common
end

target 'Extension2' do
  firebase_messaging
end
```
After migrate everything to '8.15.0' and do a Archive, then Generate Privacy Report from that Archive like Apple state in WWDC, but I can't see any Privacy Info relate to Firebase. 
Even checking Pods's Firebase after running ` pod install --repo-update`, I still can't see any PrivacyInfo.xcprivacy file in there, is there something wrong with the way I embedded Firebase in my project?

Note: 
I did change `Firebase/Analytics` to `FirebaseAnalytics` and the outcome still the same, no PrivacyInfo.xcprivacy files

### Firebase SDK Version

10.22

### Xcode Version

15.0.1

### Installation Method

CocoaPods

### Firebase Product(s)

AB Testing, Analytics, Crashlytics, DynamicLinks, Messaging, Remote Config

### Targeted Platforms

iOS

**Comment by ncooke3** [comment]
Thank for reporting. Firebase 10.22.0 only published manifests for SDKs named by Apple on [this list](https://developer.apple.com/support/third-party-SDK-requirements/). We're still working on assessing Firebase SDKs that are not on that list.

You should however be seeing manifests for Messaging and Crashlytics. Are you able to see those when updating?

**Comment by vonghiep** [comment]
> Thank for reporting. Firebase 10.22.0 only published manifests for SDKs named by Apple on [this list](https://developer.apple.com/support/third-party-SDK-requirements/). We're still working on assessing Firebase SDKs that are not on that list.
> 
> You should however be seeing manifests for Messaging and Crashlytics. Are you able to see those when updating?

I still dont see any xcprivacy file on Pod's Firebase... its kinda weird because seem like people getting privacy manifest file appear. So I'm doubting about my way of embedded Firebase

**Comment by vonghiep** [comment]
For additional informations. After update to `8.15.0`, others dependencies of Firebase seem to have PrivacyInfo.xcprivacy file:
Example: `GoogleDataTransport`, `GoogleUtilities`, `PromisesObjC`, `AppAuth`
But not Firebase

**Comment by ncooke3** [comment]
> After update to 8.15.0

Firebase only started adding privacy manifests in 10.22.0. The following release notes should help when upgrading across major versions (v8 -> v10):
- Firebase 9 breaking changes: https://firebase.google.com/support/release-notes/ios#version_900_-_may_3_2022
- Firebase 10 breaking changes: https://firebase.google.com/support/release-notes/ios#version_1000_-_october_10_2022

**Comment by vonghiep** [comment]
> > After update to 8.15.0
> 
> Firebase only started adding privacy manifests in 10.22.0. The following release notes should help when upgrading across major versions (v8 -> v10):
> 
> * Firebase 9 breaking changes: https://firebase.google.com/support/release-notes/ios#version_900_-_may_3_2022
> * Firebase 10 breaking changes: https://firebase.google.com/support/release-notes/ios#version_1000_-_october_10_2022

First, thank for your reply, so when I delete '7.7.0' on the podfile I expected it to fetch the newest(10.22.0) but it fetched 8.15, I though 8.15 is the newest, but turn out it got limited by the dependency of Google-Tag-Manager and other stuffs likethat.

I can confirm that I did update to 10.22 and as a result PrivacyInfo.xcprivacy did showup. 
Thats all I need for now. ^^!

**Comment by zhouhao27** [comment]
> Thank for reporting. Firebase 10.22.0 only published manifests for SDKs named by Apple on [this list](https://developer.apple.com/support/third-party-SDK-requirements/). We're still working on assessing Firebase SDKs that are not on that list.
> 
> You should however be seeing manifests for Messaging and Crashlytics. Are you able to see those when updating?

I found `PrivacyInfo.xcprivacy` in `Messaging`, `RemoteConfig` and `FirebaseInstallations` but can not find it in `Crashlytics`. Why?
