### ISSUE TITLE
When sending a proper universal link as ActionCodeSetting to sendEmailVerification, the backend returns a DYNAMIC_LINK_NOT_ACTIVATED but it can't be addressed now that dyn links are deprecated

### ISSUE THREAD

**Issue by e7711bbear** [firebase/firebase-ios-sdk#12556]
### Description

When sending a proper universal link as ActionCodeSetting to sendEmailVerification, the backend returns a DYNAMIC_LINK_NOT_ACTIVATED but it can't be addressed now that dyn links are deprecated

### Reproducing the issue

Try adding a properly config-ed universal link to sendemailverification (including whitelist the domain), and get the error

### Firebase SDK Version

10.21

### Xcode Version

15.0

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Error Domain=FIRAuthErrorDomain Code=17999 "An internal error has occurred, print and inspect the error details for more information." UserInfo={FIRAuthErrorUserInfoNameKey=ERROR_INTERNAL_ERROR, NSLocalizedDescription=An internal error has occurred, print and inspect the error details for more information., NSUnderlyingError=0x600000cd90e0 {Error Domain=FIRAuthInternalErrorDomain Code=3 "(null)" UserInfo={NSUnderlyingError=0x600000d10e40 {Error Domain=com.google.HTTPStatus Code=400 "(null)" UserInfo={data={length = 288, bytes = 0x7b0a2020 22657272 6f72223a 207b0a20 ... 5d0a2020 7d0a7d0a }, data_content_type=application/json; charset=UTF-8}}, FIRAuthErrorUserInfoDeserializedResponseKey={
    code = 400;
    errors =     (
                {
            domain = global;
            message = "DYNAMIC_LINK_NOT_ACTIVATED : FDL domain is not configured";
            reason = invalid;
        }
    );
    message = "DYNAMIC_LINK_NOT_ACTIVATED : FDL domain is not configured";
}}}}
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by NhienLam** [comment]
Hi [e7711bbear](https://github.com/e7711bbear), thanks for reaching out!

Our team is aware of Firebase Dynamic Link deprecation. We're working to ensure `sendEmailVerification` and other Auth methods continue to function after FDL's shutdown. Meanwhile, you can enable FDL in the Firebase Console to address the `DYNAMIC_LINK_NOT_ACTIVATED` error. 

I'm going to close this for now. If you continue to experience the issue, please feel free to re-open it.

**Comment by e7711bbear** [comment]
I can't enable FDL in the console. The control aren't here. I presume because I created my account after the deprecation. So this is blocking me completely.

**Comment by paulb777** [comment]
Reopening.

**Comment by paulb777** [comment]
Inadvertent reopen. closing now.
