### ISSUE TITLE
FirebaseAnalytics  Upgrade to consent mode v2,After the simulated user agrees, the permission cannot be displayed '' in the log,such as xx is granted

### ISSUE THREAD

**Issue by lpwlpw** [firebase/firebase-ios-sdk#12559]
### Description

I followed the [link](https://developers.google.com/tag-platform/security/guides/app-consent?platform=ios&consentmode=basic#upgrade-consent-v2) to Upgrade to consent mode v2

1、Update your app's info.plist to include:

<key>GOOGLE_ANALYTICS_DEFAULT_ALLOW_AD_USER_DATA</key> <true/>
<key>GOOGLE_ANALYTICS_DEFAULT_ALLOW_AD_PERSONALIZATION_SIGNALS</key> <true/>

2、Update your consent calls to include the parameters for ad user data and ad personalization:

[FIRAnalytics setConsent:@{
  FIRConsentTypeAnalyticsStorage : FIRConsentStatusGranted,
  FIRConsentTypeAdStorage : FIRConsentStatusGranted,
  FIRConsentTypeAdUserData : FIRConsentStatusGranted,
  FIRConsentTypeAdPersonalization : FIRConsentStatusGranted,
}];

3、 Product > Scheme > Edit scheme，Select Run from the left menu.Select the Arguments tab.In the Arguments Passed On Launch section, add -FIRAnalyticsVerboseLoggingEnabled.

4、For example, if Ad storage are enabled, you'll see the following message:

ad_storage is granted.

but，I can't see this message, I'm not sure what is the problem

mycode：
- (void)buttonPressed{

    [FIRAnalytics setConsent:@{
        FIRConsentTypeAnalyticsStorage : FIRConsentStatusDenied,
        FIRConsentTypeAdStorage : FIRConsentStatusGranted,
        FIRConsentTypeAdUserData : FIRConsentStatusGranted,
        FIRConsentTypeAdPersonalization : FIRConsentStatusGranted,
    }];

    

    NSMutableDictionary *params =[[NSMutableDictionary alloc] init];
    [params setObject:@"a" forKey:@"bbb"];
    [FIRAnalytics logEventWithName:kFIREventAddToCart
                        parameters:params];
    
    
}
Here is my log output：

10.22.0 - [FirebaseInstallations][I-FIS002000] -[FIRInstallationsIDController createGetInstallationItemPromise], appName: __FIRAPP_DEFAULT
10.22.0 - [GULReachability][I-REA902003] Monitoring the network status
10.22.0 - [GULReachability][I-REA902003] Monitoring the network status
10.22.0 - [FirebaseAnalytics][I-ACS024000] Debug mode is on
10.22.0 - [FirebaseAnalytics][I-ACS023007] Analytics v.10.22.0 started
10.22.0 - [FirebaseAnalytics][I-ACS023008] To disable debug logging set the following application argument: -noFIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
10.22.0 - [FirebaseAnalytics][I-ACS023009] Debug logging enabled
10.22.0 - [FirebaseAnalytics][I-ACS023207] To enable verbose logging set the following application argument: -FIRAnalyticsVerboseLoggingEnabled (see http://goo.gl/RfcP7r)
10.22.0 - [FirebaseAnalytics][I-ACS044000] GoogleAppMeasurementIdentitySupport dependency is linked.
10.22.0 - [FirebaseAnalytics][I-ACS044002] The AdSupport Framework is not currently linked. Some features will not function properly. Learn more at http://goo.gl/9vSsPb
10.22.0 - [GoogleUtilities/AppDelegateSwizzler][I-SWZ001008] Successfully created App Delegate Proxy automatically. To disable the proxy, set the flag GoogleUtilitiesAppDelegateProxyEnabled to NO (Boolean) in the Info.plist
10.22.0 - [FirebaseCore][I-COR000033] Data Collection flag is not set.
10.22.0 - [GULReachability][I-REA902004] Network status has changed. Code:2, status:Connected
10.22.0 - [GULReachability][I-REA902004] Network status has changed. Code:2, status:Connected
10.22.0 - [FirebaseInstallations][I-FIS002001] -[FIRInstallationsIDController installationWithValidAuthTokenForcingRefresh:0], appName: __FIRAPP_DEFAULT
10.22.0 - [FirebaseAnalytics][I-ACS031010] Tracking view controller. Class, ID: ViewController, 1914870173179502872
10.22.0 - [FirebaseAnalytics][I-ACS002002] APMExperimentAlarm scheduled to fire in approx. (s): 7488.066936969757
10.22.0 - [FirebaseAnalytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
10.22.0 - [FirebaseAnalytics][I-ACS029014] Successfully parsed a configuration. Version: 1697489695300743
10.22.0 - [FirebaseAnalytics][I-ACS023016] Analytics is ready to receive events
10.22.0 - [FirebaseAnalytics][I-ACS032014] AdServices framework is not linked. Search Ad Attribution Reporter is disabled.
10.22.0 - [FirebaseAnalytics][I-ACS002002] Engagement timer scheduled to fire in approx. (s): 3600
10.22.0 - [FirebaseAnalytics][I-ACS023012] Analytics collection enabled
10.22.0 - [FirebaseAnalytics][I-ACS023220] Analytics screen reporting is enabled. Call Analytics.logEvent(AnalyticsEventScreenView, parameters: [...]) to log a screen view event. To disable automatic screen reporting, set the flag FirebaseAutomaticScreenReportingEnabled to NO (boolean) in the Info.plist
10.22.0 - [FirebaseAnalytics][I-ACS023012] Analytics collection enabled
10.22.0 - [FirebaseAnalytics][I-ACS023220] Analytics screen reporting is enabled. Call Analytics.logEvent(AnalyticsEventScreenView, parameters: [...]) to log a screen view event. To disable automatic screen reporting, set the flag FirebaseAutomaticScreenReportingEnabled to NO (boolean) in the Info.plist
10.22.0 - [FirebaseAnalytics][I-ACS023051] Logging event: origin, name, params: auto, screen_view (_vs), {
    ga_event_origin (_o) = auto;
    ga_screen_class (_sc) = ViewController;
    ga_screen_id (_si) = 1914870173179502872;
}
10.22.0 - [FirebaseAnalytics][I-ACS023073] Debug mode is enabled. Marking event as debug and real-time. Event name, parameters: screen_view (_vs), {
    ga_debug (_dbg) = 1;
    ga_event_origin (_o) = auto;
    ga_realtime (_r) = 1;
    ga_screen_class (_sc) = ViewController;
    ga_screen_id (_si) = 1914870173179502872;
}
10.22.0 - [FirebaseAnalytics][I-ACS023072] Event logged. Event name, event params: screen_view (_vs), {
    ga_debug (_dbg) = 1;
    ga_event_origin (_o) = auto;
    ga_realtime (_r) = 1;
    ga_screen_class (_sc) = ViewController;
    ga_screen_id (_si) = 1914870173179502872;
}
10.22.0 - [FirebaseAnalytics][I-ACS002002] Measurement timer scheduled to fire in approx. (s): 0.8415650129318237
10.22.0 - [FirebaseAnalytics][I-ACS002001] Measurement timer fired
10.22.0 - [FirebaseAnalytics][I-ACS002003] Measurement timer canceled
10.22.0 - [FirebaseAnalytics][I-ACS023105] Event is not subject to real-time event count daily limit. Marking an event as real-time. Event name, parameters: screen_view (_vs), {
    ga_conversion (_c) = 1;
    ga_debug (_dbg) = 1;
    ga_event_origin (_o) = auto;
    ga_realtime (_r) = 1;
    ga_screen_class (_sc) = ViewController;
    ga_screen_id (_si) = 1914870173179502872;
}
10.22.0 - [FirebaseAnalytics][I-ACS012018] Saving bundle. size (bytes): 391
10.22.0 - [FirebaseAnalytics][I-ACS023116] Bundle added to the upload queue. BundleID, timestamp (ms): 12, 1710471927867
10.22.0 - [FirebaseAnalytics][I-ACS023039] Measurement data sent to network. Timestamp (ms), data: 1710471928952, <APMPBMeasurementBatch: 0x60000001c920>
10.22.0 - [FirebaseAnalytics][I-ACS900000] Uploading data. Host: https://app-measurement.com/a
10.22.0 - [FirebaseAnalytics][I-ACS901006] Received SSL challenge for host. Host: https://app-measurement.com/a
10.22.0 - [FirebaseAnalytics][I-ACS023044] Successful upload. Got network response. Code, size: 204, -1
10.22.0 - [FirebaseAnalytics][I-ACS002002] Measurement timer scheduled to fire in approx. (s): -1.199742913246155
10.22.0 - [FirebaseAnalytics][I-ACS002003] Measurement timer canceled
10.22.0 - [FirebaseAnalytics][I-ACS023087] User property set. Name, value: _npa, 0
10.22.0 - [FirebaseAnalytics][I-ACS023051] Logging event: origin, name, params: app, add_to_cart, {
    bbb = a;
    ga_event_origin (_o) = app;
    ga_screen_class (_sc) = ViewController;
    ga_screen_id (_si) = 1914870173179502872;
}
10.22.0 - [FirebaseAnalytics][I-ACS023073] Debug mode is enabled. Marking event as debug and real-time. Event name, parameters: add_to_cart, {
    bbb = a;
    ga_debug (_dbg) = 1;
    ga_event_origin (_o) = app;
    ga_realtime (_r) = 1;
    ga_screen_class (_sc) = ViewController;
    ga_screen_id (_si) = 1914870173179502872;
}
10.22.0 - [FirebaseAnalytics][I-ACS023072] Event logged. Event name, event params: add_to_cart, {
    bbb = a;
    ga_debug (_dbg) = 1;
    ga_event_origin (_o) = app;
    ga_realtime (_r) = 1;
    ga_screen_class (_sc) = ViewController;
    ga_screen_id (_si) = 1914870173179502872;
}
10.22.0 - [FirebaseAnalytics][I-ACS002002] Measurement timer scheduled to fire in approx. (s): 0.9939899444580078
10.22.0 - [FirebaseAnalytics][I-ACS002001] Measurement timer fired
10.22.0 - [FirebaseAnalytics][I-ACS002003] Measurement timer canceled
10.22.0 - [FirebaseAnalytics][I-ACS023105] Event is not subject to real-time event count daily limit. Marking an event as real-time. Event name, parameters: add_to_cart, {
    bbb = a;
    ga_conversion (_c) = 1;
    ga_debug (_dbg) = 1;
    ga_event_origin (_o) = app;
    ga_realtime (_r) = 1;
    ga_screen_class (_sc) = ViewController;
    ga_screen_id (_si) = 1914870173179502872;
}
10.22.0 - [FirebaseAnalytics][I-ACS012018] Saving bundle. size (bytes): 407
10.22.0 - [FirebaseAnalytics][I-ACS023116] Bundle added to the upload queue. BundleID, timestamp (ms): 13, 1710471932063
10.22.0 - [FirebaseAnalytics][I-ACS023039] Measurement data sent to network. Timestamp (ms), data: 1710471933163, <APMPBMeasurementBatch: 0x60000001c3c0>
10.22.0 - [FirebaseAnalytics][I-ACS900000] Uploading data. Host: https://app-measurement.com/a
10.22.0 - [FirebaseAnalytics][I-ACS901006] Received SSL challenge for host. Host: https://app-measurement.com/a
10.22.0 - [FirebaseAnalytics][I-ACS023044] Successful upload. Got network response. Code, size: 204, -1
10.22.0 - [FirebaseAnalytics][I-ACS002002] Measurement timer scheduled to fire in approx. (s): -0.8403080701828003
10.22.0 - [FirebaseAnalytics][I-ACS002003] Measurement timer canceled

### Reproducing the issue

[FirebaseD.zip](https://github.com/firebase/firebase-ios-sdk/files/14610232/FirebaseD.zip)

1、Info.plist
	<key>FIREBASE_ANALYTICS_COLLECTION_ENABLED</key>
	<true/>
	<key>GOOGLE_ANALYTICS_DEFAULT_ALLOW_AD_PERSONALIZATION_SIGNALS</key>
	<true/>
	<key>GOOGLE_ANALYTICS_DEFAULT_ALLOW_AD_STORAGE</key>
	<false/>
	<key>GOOGLE_ANALYTICS_DEFAULT_ALLOW_ANALYTICS_STORAGE</key>
	<true/>
2、AppDelegate.m

    [FIRApp configure];
    [FIRAnalytics setAnalyticsCollectionEnabled:YES];

3、Simulated user consent
- (void)buttonPressed{

    [FIRAnalytics setConsent:@{
        FIRConsentTypeAnalyticsStorage : FIRConsentStatusDenied,
        FIRConsentTypeAdStorage : FIRConsentStatusGranted,
        FIRConsentTypeAdUserData : FIRConsentStatusGranted,
        FIRConsentTypeAdPersonalization : FIRConsentStatusGranted,
    }];

    

    NSMutableDictionary *params =[[NSMutableDictionary alloc] init];
    [params setObject:@"a" forKey:@"bbb"];
    [FIRAnalytics logEventWithName:kFIREventAddToCart
                        parameters:params];
    
    
}

### Firebase SDK Version

10.22.0

### Xcode Version

15.3

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Here is my log output：

10.22.0 - [FirebaseInstallations][I-FIS002000] -[FIRInstallationsIDController createGetInstallationItemPromise], appName: __FIRAPP_DEFAULT
10.22.0 - [GULReachability][I-REA902003] Monitoring the network status
10.22.0 - [GULReachability][I-REA902003] Monitoring the network status
10.22.0 - [FirebaseAnalytics][I-ACS024000] Debug mode is on
10.22.0 - [FirebaseAnalytics][I-ACS023007] Analytics v.10.22.0 started
10.22.0 - [FirebaseAnalytics][I-ACS023008] To disable debug logging set the following application argument: -noFIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
10.22.0 - [FirebaseAnalytics][I-ACS023009] Debug logging enabled
10.22.0 - [FirebaseAnalytics][I-ACS023207] To enable verbose logging set the following application argument: -FIRAnalyticsVerboseLoggingEnabled (see http://goo.gl/RfcP7r)
10.22.0 - [FirebaseAnalytics][I-ACS044000] GoogleAppMeasurementIdentitySupport dependency is linked.
10.22.0 - [FirebaseAnalytics][I-ACS044002] The AdSupport Framework is not currently linked. Some features will not function properly. Learn more at http://goo.gl/9vSsPb
10.22.0 - [GoogleUtilities/AppDelegateSwizzler][I-SWZ001008] Successfully created App Delegate Proxy automatically. To disable the proxy, set the flag GoogleUtilitiesAppDelegateProxyEnabled to NO (Boolean) in the Info.plist
10.22.0 - [FirebaseCore][I-COR000033] Data Collection flag is not set.
10.22.0 - [GULReachability][I-REA902004] Network status has changed. Code:2, status:Connected
10.22.0 - [GULReachability][I-REA902004] Network status has changed. Code:2, status:Connected
10.22.0 - [FirebaseInstallations][I-FIS002001] -[FIRInstallationsIDController installationWithValidAuthTokenForcingRefresh:0], appName: __FIRAPP_DEFAULT
10.22.0 - [FirebaseAnalytics][I-ACS031010] Tracking view controller. Class, ID: ViewController, 1914870173179502872
10.22.0 - [FirebaseAnalytics][I-ACS002002] APMExperimentAlarm scheduled to fire in approx. (s): 7488.066936969757
10.22.0 - [FirebaseAnalytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
10.22.0 - [FirebaseAnalytics][I-ACS029014] Successfully parsed a configuration. Version: 1697489695300743
10.22.0 - [FirebaseAnalytics][I-ACS023016] Analytics is ready to receive events
10.22.0 - [FirebaseAnalytics][I-ACS032014] AdServices framework is not linked. Search Ad Attribution Reporter is disabled.
10.22.0 - [FirebaseAnalytics][I-ACS002002] Engagement timer scheduled to fire in approx. (s): 3600
10.22.0 - [FirebaseAnalytics][I-ACS023012] Analytics collection enabled
10.22.0 - [FirebaseAnalytics][I-ACS023220] Analytics screen reporting is enabled. Call Analytics.logEvent(AnalyticsEventScreenView, parameters: [...]) to log a screen view event. To disable automatic screen reporting, set the flag FirebaseAutomaticScreenReportingEnabled to NO (boolean) in the Info.plist
10.22.0 - [FirebaseAnalytics][I-ACS023012] Analytics collection enabled
10.22.0 - [FirebaseAnalytics][I-ACS023220] Analytics screen reporting is enabled. Call Analytics.logEvent(AnalyticsEventScreenView, parameters: [...]) to log a screen view event. To disable automatic screen reporting, set the flag FirebaseAutomaticScreenReportingEnabled to NO (boolean) in the Info.plist
10.22.0 - [FirebaseAnalytics][I-ACS023051] Logging event: origin, name, params: auto, screen_view (_vs), {
    ga_event_origin (_o) = auto;
    ga_screen_class (_sc) = ViewController;
    ga_screen_id (_si) = 1914870173179502872;
}
10.22.0 - [FirebaseAnalytics][I-ACS023073] Debug mode is enabled. Marking event as debug and real-time. Event name, parameters: screen_view (_vs), {
    ga_debug (_dbg) = 1;
    ga_event_origin (_o) = auto;
    ga_realtime (_r) = 1;
    ga_screen_class (_sc) = ViewController;
    ga_screen_id (_si) = 1914870173179502872;
}
10.22.0 - [FirebaseAnalytics][I-ACS023072] Event logged. Event name, event params: screen_view (_vs), {
    ga_debug (_dbg) = 1;
    ga_event_origin (_o) = auto;
    ga_realtime (_r) = 1;
    ga_screen_class (_sc) = ViewController;
    ga_screen_id (_si) = 1914870173179502872;
}
10.22.0 - [FirebaseAnalytics][I-ACS002002] Measurement timer scheduled to fire in approx. (s): 0.8415650129318237
10.22.0 - [FirebaseAnalytics][I-ACS002001] Measurement timer fired
10.22.0 - [FirebaseAnalytics][I-ACS002003] Measurement timer canceled
10.22.0 - [FirebaseAnalytics][I-ACS023105] Event is not subject to real-time event count daily limit. Marking an event as real-time. Event name, parameters: screen_view (_vs), {
    ga_conversion (_c) = 1;
    ga_debug (_dbg) = 1;
    ga_event_origin (_o) = auto;
    ga_realtime (_r) = 1;
    ga_screen_class (_sc) = ViewController;
    ga_screen_id (_si) = 1914870173179502872;
}
10.22.0 - [FirebaseAnalytics][I-ACS012018] Saving bundle. size (bytes): 391
10.22.0 - [FirebaseAnalytics][I-ACS023116] Bundle added to the upload queue. BundleID, timestamp (ms): 12, 1710471927867
10.22.0 - [FirebaseAnalytics][I-ACS023039] Measurement data sent to network. Timestamp (ms), data: 1710471928952, <APMPBMeasurementBatch: 0x60000001c920>
10.22.0 - [FirebaseAnalytics][I-ACS900000] Uploading data. Host: https://app-measurement.com/a
10.22.0 - [FirebaseAnalytics][I-ACS901006] Received SSL challenge for host. Host: https://app-measurement.com/a
10.22.0 - [FirebaseAnalytics][I-ACS023044] Successful upload. Got network response. Code, size: 204, -1
10.22.0 - [FirebaseAnalytics][I-ACS002002] Measurement timer scheduled to fire in approx. (s): -1.199742913246155
10.22.0 - [FirebaseAnalytics][I-ACS002003] Measurement timer canceled
10.22.0 - [FirebaseAnalytics][I-ACS023087] User property set. Name, value: _npa, 0
10.22.0 - [FirebaseAnalytics][I-ACS023051] Logging event: origin, name, params: app, add_to_cart, {
    bbb = a;
    ga_event_origin (_o) = app;
    ga_screen_class (_sc) = ViewController;
    ga_screen_id (_si) = 1914870173179502872;
}
10.22.0 - [FirebaseAnalytics][I-ACS023073] Debug mode is enabled. Marking event as debug and real-time. Event name, parameters: add_to_cart, {
    bbb = a;
    ga_debug (_dbg) = 1;
    ga_event_origin (_o) = app;
    ga_realtime (_r) = 1;
    ga_screen_class (_sc) = ViewController;
    ga_screen_id (_si) = 1914870173179502872;
}
10.22.0 - [FirebaseAnalytics][I-ACS023072] Event logged. Event name, event params: add_to_cart, {
    bbb = a;
    ga_debug (_dbg) = 1;
    ga_event_origin (_o) = app;
    ga_realtime (_r) = 1;
    ga_screen_class (_sc) = ViewController;
    ga_screen_id (_si) = 1914870173179502872;
}
10.22.0 - [FirebaseAnalytics][I-ACS002002] Measurement timer scheduled to fire in approx. (s): 0.9939899444580078
10.22.0 - [FirebaseAnalytics][I-ACS002001] Measurement timer fired
10.22.0 - [FirebaseAnalytics][I-ACS002003] Measurement timer canceled
10.22.0 - [FirebaseAnalytics][I-ACS023105] Event is not subject to real-time event count daily limit. Marking an event as real-time. Event name, parameters: add_to_cart, {
    bbb = a;
    ga_conversion (_c) = 1;
    ga_debug (_dbg) = 1;
    ga_event_origin (_o) = app;
    ga_realtime (_r) = 1;
    ga_screen_class (_sc) = ViewController;
    ga_screen_id (_si) = 1914870173179502872;
}
10.22.0 - [FirebaseAnalytics][I-ACS012018] Saving bundle. size (bytes): 407
10.22.0 - [FirebaseAnalytics][I-ACS023116] Bundle added to the upload queue. BundleID, timestamp (ms): 13, 1710471932063
10.22.0 - [FirebaseAnalytics][I-ACS023039] Measurement data sent to network. Timestamp (ms), data: 1710471933163, <APMPBMeasurementBatch: 0x60000001c3c0>
10.22.0 - [FirebaseAnalytics][I-ACS900000] Uploading data. Host: https://app-measurement.com/a
10.22.0 - [FirebaseAnalytics][I-ACS901006] Received SSL challenge for host. Host: https://app-measurement.com/a
10.22.0 - [FirebaseAnalytics][I-ACS023044] Successful upload. Got network response. Code, size: 204, -1
10.22.0 - [FirebaseAnalytics][I-ACS002002] Measurement timer scheduled to fire in approx. (s): -0.8403080701828003
10.22.0 - [FirebaseAnalytics][I-ACS002003] Measurement timer canceled
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by lpwlpw** [comment]
name: FirebaseAnalytics

**Comment by lpwlpw** [comment]
# FirebaseAnalytics

**Comment by rizafran** [comment]
Hi @lpwlpw, I was able to reproduce the issue using your MCVE, but the "x is granted" was being logged when I added the `-FIRAnalyticsVerboseLoggingEnabled` in the app's scheme. Could you try to add it as well and see if the issue will persist?

**Comment by lpwlpw** [comment]
solved
