### ISSUE TITLE
Latest Firebase Release is missing XCFrameworks

### ISSUE THREAD

**Issue by tareksabry1337** [firebase/firebase-ios-sdk#12569]
### Description

It looks like the latest Firebase Release 10.22.1 is missing the binaries in the release assets, it doesn't contain Firebase.zip like all the other previous releases this is causing an internal script of ours to fail since we are using XCFrameworks exclusively, Is this intended to be removed or that's a mistake?

Thanks!

### Firebase SDK Version

10.22.1

### Xcode Version

15.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

All

### Targeted Platforms

iOS

**Comment by paulb777** [comment]
This was intentional. More details in the duplicate #12529.
