### ISSUE TITLE
[FR]: FirebaseCrashlytics 10.22.0 uses privacy impacting sdks on versions without the privacy manifest requirement?

### ISSUE THREAD

**Issue by BitByAVampire** [firebase/firebase-ios-sdk#12573]
### Description

when i upgrade to the 10.22.0 version of crashlytics that has the privacy. manifest support i notice in the podfile.lock that it uses older versions of privacy impacting sdks (as listed by Apple):  
```
FirebaseCore (~> 10.5)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesObjC (~> 2.1)
```
   that don't have support for privacy manifest requirement. 
I am looking for confirmation if this will raise any issue by Apple, or if just the privacy manifest at the top level sdk is sufficient. 

### Firebase Product(s)

Crashlytics

**Comment by paulb777** [comment]
Make sure you run `pod update`. If you're still having trouble, please share the Podfile.

**Comment by BitByAVampire** [comment]
even after updating the crashlytics dependencies are still the same. my podfile is pod 
```
'Firebase/RemoteConfig', '10.22.0'
  pod 'Firebase/Crashlytics',  '10.22.0'
  pod 'Firebase/Analytics',    '10.22.0'
  pod 'FirebaseMessaging',     '10.22.0'
  pod 'FirebasePerformance',   '10.22.0'
```

**Comment by paulb777** [comment]
Remove the "/" - `pod 'FirebaseCrashlytics',  '10.22.0'`

**Comment by BitByAVampire** [comment]
to be clear my issue is not with crashlytics but with the sub depdencies of crashlytics

**Comment by paulb777** [comment]
The Podflie.lock should explain why the dependencies are not getting updated. If you'd like our help, please fill out the full issue template with the `Podfile` and `Podfile.lock`.

**Comment by BitByAVampire** [comment]
It seems like crashlytics need FirebaseInstallations (~> 10.0), GoogleDataTransport (~> 9.2), nanopb (< 2.30911.0, >= 2.30908.0), PromisesObjC (~> 2.1) with these versions specifically. Im asking if this complies with apples privacy requirement, as these versions don't have the privacy manifest, even if the crashlytics version has it.

**Comment by paulb777** [comment]
The latest versions available of all of those dependencies include privacy manifests.

Since manifests are not yet required, we're not requiring the update for those that want to continue to use the older versions.

**Comment by BitByAVampire** [comment]
And the privacy manifest discloses **everything**, including how crshalytics uses its sub dependencies? (im not sure how closely apple will look at this)

**Comment by paulb777** [comment]
Our intent is to comply with Apple's requirements. As you imply, there are still open questions about what exactly that means, and we plan to update if necessary.

**Comment by BitByAVampire** [comment]
Ok thank you. Appreciate your support.
