### ISSUE TITLE
It would be nice if FirebaseCommunity supports Analytics

### ISSUE THREAD

**Issue by chandrashekharhm** [firebase/firebase-ios-sdk#126]
Do we have any roadmap on supporting Firebase/Analytics in FirebaseCommunity

**Comment by paulb777** [comment]
@chandrashekharhm See instructions at https://github.com/firebase/firebase-ios-sdk/tree/master/BuildFrameworks for integrating FirebaseCommunity sources with Analytics.  We're working with the CocoaPods team so that we can eventually integrate via CocoaPods. See https://github.com/CocoaPods/CocoaPods/pull/6811

**Comment by chandrashekharhm** [comment]
@paulb777 Thanks for the update.  In the script I'm seeing only below frameworks supported: 

"FirebaseAuth": [.iOS, .macOS],
  | "FirebaseCore": [.iOS, .macOS],
  | "FirebaseDatabase": [.iOS, .macOS],
  | "FirebaseMessaging": [.iOS],
  | "FirebaseStorage": [.iOS, .macOS]

I'm looking similar support for Analytics. If you have any info or docs to integrate Analytics through firebaseCommunity would be great.

**Comment by paulb777** [comment]
@chandrashekharhm Yep, the script create builds from the git repo that are inter-operable with the FirebaseAnalytics (and the rest of Firebase's) binary releases.

While we do plan to open source more of the Firebase components, we likely won't be able to publish the plans in advance of it actually happening.  I can say that Analytics is _NOT_ near the top of the list.

**Comment by x-cray** [comment]
@paulb777 Would be nice to see at least rough list in Roadmap. I'm particularly interested in DynamicLinks

**Comment by samuelsainz** [comment]
@paulb777 Once we have support for static frameworks with this feature (CocoaPods/CocoaPods#6811) Firebase should release a new version so we can integrate Analytics via CocoaPods, right?

**Comment by paulb777** [comment]
@samuelsainz Yes, we plan to set up dependencies on FirebaseAnalytics in FirebaseCommunity  sometime after the GA release of CocoaPods 1.4.0. Timing may be further out for Firebase.

**Comment by alfonsodev** [comment]
I see [CocoaPods/CocoaPods#6811](https://github.com/CocoaPods/CocoaPods/pull/6811) was merged, is there a way now to use Analytics on *macos* ? 
What should be added to the Podfile ? 
This my current Podfile 
```
target 'myapp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  platform :osx, '10.12'
  pod 'FirebaseCore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :tag => '5.0.0'
  pod 'FirebaseAuth', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :tag => '5.0.0'
  pod 'FirebaseDatabase', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :tag => '5.0.0'
end
```
Thanks

**Comment by ryanwilson** [comment]
@alfonsodev Unfortunately Firebase Analytics does not support macOS.
