### ISSUE TITLE
Build failure when installing 10.23.0 via cocoapods without use_frameworks!

### ISSUE THREAD

**Issue by macdrevx** [firebase/firebase-ios-sdk#12605]
### Description

Build fails with error:
```
Pods/FirebaseCrashlytics/Crashlytics/Crashlytics/Controllers/FIRCLSRolloutsPersistenceManager.m:25:9 'FirebaseCrashlytics/FirebaseCrashlytics-Swift.h' file not found
```

### Reproducing the issue

1. Create a new xcode project
2. Add the podfile shared below and `$ pod install`
3. Try to build the project

### Firebase SDK Version

10.23.0

### Xcode Version

15.2

### Installation Method

CocoaPods

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

platform :ios, '15.0'
use_modular_headers!

target 'CrashlyticsErrorDemo' do
  pod 'Firebase/Crashlytics', '10.23.0'
end

```

</details>

**Comment by paulb777** [comment]
`use_frameworks!` is required since Firebase 9.0. More details in the release notes - https://firebase.google.com/support/release-notes/ios.

**Comment by paul-lavoine** [comment]
Hello, I have the same problem.

But since the version 10.22.1 everything worked well. 
I've never included `use_frameworks!` but I included `use_modular_headers!` instead and until the version 10.22.1 it was working,

Did something change ?
