### ISSUE TITLE
[FIRASqliteStore recordsForQuery:parameterValues:error:withFilter:] bug

### ISSUE THREAD

**Issue by kaannesinn** [firebase/firebase-ios-sdk#1260]
### [REQUIRED] Step 2: Describe your environment

Xcode version: 9.3 (ObjC)
Firebase SDK version: 4.13.0
Firebase Component: FirebaseAnalytics (4.2.0),  FirebaseCore (4.0.20), FirebaseInstanceID (2.0.10)

### [REQUIRED] Step 3: Describe the problem

Hi,
In our ios application, we use Firebase for event logging and show native and interstitial ad banners with  Google-Mobile-Ads-SDK (7.30.0). After adding Firebase and GAD libraries and updating our app on AppStore, this crash is occured http://crashes.to/s/e5bc42b17e5 

I think the prefix of FIRA belongs to Firebase or may be GAD classes. I cant reproduce the issue with simulator or test devices but on the production platform (appstore version), this crash is occured with an iPhone 5S 11.3.0 device. The crash has a little count now but I am wondering what the reason of it. It is related to another issue of our GAD crashes  (http://crashes.to/s/5f40366342d)? Or the new version of Firebase?

#### Steps to reproduce:

The crash might be when the application is on background or when sending an event on purchasing step. Dont know the exact step.

#### Relevant Code:

Pod I am using;

Using AFNetworking (3.2.0)
Using CNPPopupController (0.3.3)
Using Crashlytics (3.10.1)
Using EAIntroView (2.12.0)
Using EARestrictedScrollView (1.1.0)
Using FLAnimatedImage (1.0.12)
Using Fabric (1.7.6)
Using Firebase (4.13.0)
Using FirebaseAnalytics (4.2.0)
Using FirebaseCore (4.0.20)
Using FirebaseInstanceID (2.0.10)
Using Google-Mobile-Ads-SDK (7.30.0)
Using GoogleAnalytics (3.17.0)
Using GoogleToolboxForMac (2.1.4)
Using HCSStarRatingView (1.5)
Using IQKeyboardManager (5.0.8)
Using SDWebImage (4.3.3)
Using SMPageControl (1.2)
Using UICKeyChainStore (2.1.1)
Using nanopb (0.3.8)

You can download the app from https://itunes.apple.com/us/app/translate-assistant/id1348751689?mt=8

Thanks

**Comment by baolocdo** [comment]
Tracked internally at b/79920348

**Comment by kaannesinn** [comment]
It is related with the new issue https://github.com/firebase/firebase-ios-sdk/issues/1487

**Comment by morganchen12** [comment]
@kaannesinn can you try updating to Firebase 5.0+ and seeing if the crash still occurs?

The first crash appears to be a crash in the Google Mobile Ads SDK, and the second crash has 0 occurrences.

**Comment by kaannesinn** [comment]
@morganchen12 I updated 5.0+ after 1 week from this issue and updated our app on AppStore. Most of the crashes are gone yes. 

Yes I know it is from GAD. The 2nd crash doesnt occur again but the 1st one exists on the new version of the app with #1487 issue.

I am closing this issue and we can continue with the new one. 

Thanks
