### ISSUE TITLE
compile error：Could not find or use auto-linked library 'swiftCompatibility50': library 'swiftCompatibility50' not found

### ISSUE THREAD

**Issue by ibabyblue** [firebase/firebase-ios-sdk#12603]
### Description

Hello, I manually updated the relevant SDK in the Objective-c project, and the compilation error is as follows:
`ld: warning: Could not find or use auto-linked library 'swiftCompatibility50': library 'swiftCompatibility50' not found`
`ld: warning: Could not find or use auto-linked library 'swiftCompatibility51': library 'swiftCompatibility51' not found` 
`ld: warning: Could not find or use auto-linked library 'swiftCompatibilityConcurrency': library 'swiftCompatibilityConcurrency' not found`
`ld: warning: Could not find or use auto-linked library 'swiftCompatibilityDynamicReplacements': library 'swiftCompatibilityDynamicReplacements' not found`
`ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found`
`ld: Undefined symbols:`
  `_OBJC_CLASS_$_FIRHeartbeatController, referenced from:`
       `in FirebaseCore[13](FIRHeartbeatLogger.o)`
   `__swift_FORCE_LOAD_$_swiftCompatibility50, referenced from:`
   `__swift_FORCE_LOAD_$_swiftCompatibility50_$_FirebaseAnalytics in FirebaseAnalytics[17](Analytics+StoreKit.o)`
   `__swift_FORCE_LOAD_$_swiftCompatibility51, referenced from:`
   `__swift_FORCE_LOAD_$_swiftCompatibility51_$_FirebaseAnalytics in FirebaseAnalytics[17](Analytics+StoreKit.o)`
   `__swift_FORCE_LOAD_$_swiftCompatibilityConcurrency, referenced from:`
   `__swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseAnalytics in FirebaseAnalytics[17](Analytics+StoreKit.o)`
   `__swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements, referenced from:`
   `__swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_FirebaseAnalytics in FirebaseAnalytics[17](Analytics+StoreKit.o)`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`
What can I do to solve this problem？Thank you for your help！

![image](https://github.com/firebase/firebase-ios-sdk/assets/13377910/1b494582-74b6-4f29-b9bb-cf14167d9328)
![image](https://github.com/firebase/firebase-ios-sdk/assets/13377910/eb9d02c1-460e-4ca2-b39e-510f246251a2)
上图是更新的相关SDK。

### Firebase SDK Version

10.23.0 

### Xcode Version

15.2

### Installation Method

Zip

### Firebase Product(s)

Analytics, Crashlytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
ld: warning: Could not find or use auto-linked library 'swiftCompatibility50': library 'swiftCompatibility50' not found
ld: warning: Could not find or use auto-linked library 'swiftCompatibility51': library 'swiftCompatibility51' not found
ld: warning: Could not find or use auto-linked library 'swiftCompatibilityConcurrency': library 'swiftCompatibilityConcurrency' not found
ld: warning: Could not find or use auto-linked library 'swiftCompatibilityDynamicReplacements': library 'swiftCompatibilityDynamicReplacements' not found
ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
ld: Undefined symbols:
  _OBJC_CLASS_$_FIRHeartbeatController, referenced from:
       in FirebaseCore[13](FIRHeartbeatLogger.o)
  __swift_FORCE_LOAD_$_swiftCompatibility50, referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_FirebaseAnalytics in FirebaseAnalytics[17](Analytics+StoreKit.o)
  __swift_FORCE_LOAD_$_swiftCompatibility51, referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_FirebaseAnalytics in FirebaseAnalytics[17](Analytics+StoreKit.o)
  __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency, referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseAnalytics in FirebaseAnalytics[17](Analytics+StoreKit.o)
  __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements, referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_FirebaseAnalytics in FirebaseAnalytics[17](Analytics+StoreKit.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
Make sure you follow the zip distribution's README instructions. It looks like `FirebaseCoreInternal` is missing from the Analytics folder.

**Comment by MarkingQ** [comment]
AutoPlay

**Comment by TranTrieuLamQuynh** [comment]
@ibabyblue 

You can try as commented below.

(https://github.com/facebookarchive/react-native-fbsdk/issues/755#issuecomment-644528297)

**Comment by ibabyblue** [comment]
Thank you very much for your reply, I have done it again according to README, but there is still one error, that is: 
ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
![image](https://github.com/firebase/firebase-ios-sdk/assets/13377910/30f51da4-aac1-45cf-853c-31968825e09d)

To solve this problem, deleting '-ObjC' from Other Linker Flags in Build Settings will compile, but in my project '-ObjC' is required. How do I deal with this? Thank you!

**Comment by ibabyblue** [comment]
After I removed $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME) from LIBRARY_SEARCH_PATHS, the compilation was successful, which is to prevent loss of Swift system libraries 
Added when the symbolic linker was wrong, now it must be deleted to work... On the one hand to add, on the other hand to delete, dizzy, but still want to thank the reply ~
