### ISSUE TITLE
EXC_BAD_ACCESS crash when decoding data from Firestore

### ISSUE THREAD

**Issue by fanwgwg** [firebase/firebase-ios-sdk#12620]
### Description

Sometimes when decoding data from Firestore, I'd encounter this EXC_BAD_ACCESS  crash. 

```
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x000000010724421c in -[FSTUserDataWriter convertedValue:] ()
#1	0x0000000107244344 in -[FSTUserDataWriter convertedObject:] ()
#2	0x0000000107244288 in -[FSTUserDataWriter convertedValue:] ()
#3	0x000000010720a08c in -[FIRDocumentSnapshot dataWithServerTimestampBehavior:] ()
#4	0x000000010720a544 in -[FIRQueryDocumentSnapshot dataWithServerTimestampBehavior:] ()
#5	0x000000010720a4a0 in -[FIRQueryDocumentSnapshot data] ()
```

![image](https://github.com/firebase/firebase-ios-sdk/assets/14089267/c1a21ba7-604b-4151-8d3f-d5bee2794e01)

### Reproducing the issue

The issue occurs sporadically during data decoding from Firestore. Notably, the data contains a blob/Data field that can occasionally be empty, though not nil. This blob field stores protobuf data. Typically, data assignment to `firestoreModel.data` is performed as `protoBufMessage.serializedData()`. When all values in the protobuf match their default, the serialized data is Data() with 0 bytes.

Furthermore, crashes seem to manifest only when decoding documents with `hasPendingWrites = true` within snapshot listeners, indicating local writes. However, once a document has been successfully written to the server, subsequent decoding operations on the same document succeed consistently, whether from snapshot listeners or direct queries.

I'm also seeing similar crash reports at 
- https://github.com/firebase/firebase-ios-sdk/issues/11978
- https://github.com/firebase/firebase-ios-sdk/issues/10514
- https://github.com/firebase/flutterfire/issues/11528
- https://github.com/firebase/firebase-ios-sdk/issues/11773

e.g., 

```
struct FirestoreModel: Codable {
  @DocumentID var id: String?
  var data: Data
}
```
![image](https://github.com/firebase/firebase-ios-sdk/assets/14089267/313771d5-f852-4187-8bab-f166de821f26)

### Firebase SDK Version

10.23.0

### Xcode Version

15.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by tom-andersen** [comment]
Thank you for the report. I will look into this as soon as possible.

**Comment by tom-andersen** [comment]
Hi @fanwgwg!

I took the time to repro the bug. With your good observations and explanation this was quite easy. Thank you!

I am working on a fix, but I also want to be sure there aren't any unforeseen consequences.

**Comment by tom-andersen** [comment]
Fix will be part of next release.
