### ISSUE TITLE
Cloud Messaging no FCM token being created

### ISSUE THREAD

**Issue by ian-sayles** [firebase/firebase-ios-sdk#12628]
### Description

When I deploy my app to the App Store or TestFlight I no longer get any FCM tokens, works perfectly when running on connected device from within  Xcode.   Also no issue with Android version of my app, works ok in development and from the released app in Play Store.   

### Reproducing the issue

The App delegate:

final class AppDelegate: NSObject, UIApplicationDelegate {
     
    func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions _: [UIApplication.LaunchOptionsKey: Any]? = nil
    ) -> Bool {
           
        FirebaseApp.configure()
        Messaging.messaging().delegate = self
        UNUserNotificationCenter.current().delegate = self

        let authOptions: UNAuthorizationOptions = [.alert, .badge, .sound]

        UNUserNotificationCenter.current().requestAuthorization(options: authOptions) { granted, error in
            if let error = error {
                print("Error requesting notification authorization: \(error)")
            } else if granted {
                print("Notification authorization granted")
            } else {
                print("Notification authorization denied")
            }
        }
        
        application.registerForRemoteNotifications()
        return true
    }
    
    func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
      print("Failed to register for remote notifications with error: \(error)")
    }
}

This following code is never fired when the app is from the App Store or TestFlight, in the full code I save the token so can be used in other parts of the app:

extension AppDelegate: MessagingDelegate {
    @objc func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?) {
        guard let token = fcmToken else { return }
        
        }
}

### Firebase SDK Version

10.23.0

### Xcode Version

15.3 (15E204a)

### Installation Method

Swift Package Manager

### Firebase Product(s)

Messaging

### Targeted Platforms

iOS, macOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reporting, @ian-sayles. Could you confirm if you've set the APS Environment key to production instead of sandbox/development in the Entitlements file?

**Comment by ian-sayles** [comment]
Thanks @rizafran I checked by entitlement file and it was set for development, edited the file and changed it production, submitted new app and tried it in TestFlight with same issue, I also checked the entitlement file to make sure Xcode had not changed it back, and it was still set for production.

**Comment by rizafran** [comment]
Thanks for the update, @ian-sayles. May I know if you have uploaded your production APNs certificate to the Firebase console?

**Comment by ian-sayles** [comment]
Thanks @rizafran I have used the APNs Authentication Key not the APN certificate, do you have to use the certificate or should it work with just the authentication key?

**Comment by rizafran** [comment]
@ian-sayles, you can use either the APNs authentication key or APNs certificate.
