### ISSUE TITLE
Subject: Inquiry Regarding Use of "statfs" API in FirebaseCrashlytics SDK

### ISSUE THREAD

**Issue by KKakadiyaKashyap** [firebase/firebase-ios-sdk#12627]
### Description

I hope this message finds you well. I am writing to you as a developer who utilizes the FirebaseCrashlytics SDK within my iOS application. Recently, during the app submission process, Apple flagged the use of the "statfs" API within the SDK. According to Apple's guidelines, the use of this API requires a detailed explanation and a manifest file to be uploaded alongside the application, detailing the rationale for its usage.

Understanding the importance of compliance with Apple's policies to ensure uninterrupted service for app developers and users, I wanted to bring this matter to your attention. Could you provide guidance on the intended use of the "statfs" API within FirebaseCrashlytics SDK? Additionally, if there are any specific steps or documentation that you recommend including in the manifest file to satisfy Apple's requirements, that information would be invaluable.

Your assistance in this matter not only helps in ensuring compliance but also supports the developer community in maintaining a seamless user experience across our applications.

Thank you for your time and understanding. I look forward to your response and any guidance you can provide.

### Firebase SDK Version

10.22.0

### Xcode Version

14.3

### Installation Method

CocoaPods

### Firebase Product(s)

Crashlytics

### Targeted Platforms

macOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @KKakadiyaKashyap. Based on the [release notes](https://firebase.google.com/support/release-notes/ios#crashlytics_1), it looks like the calls to `statfs` have been removed in v10.22.0 to comply with Apple Privacy Manifests.
