### ISSUE TITLE
App fails to install on simulator/device 'Info.plist: No such file or directory' Xcode 15.3 SDK v10.23.0

### ISSUE THREAD

**Issue by thomas151** [firebase/firebase-ios-sdk#12622]
### Description

Updated Xcode to 15.3 & updated to latest firebase packages for the new privacy manifest and am getting an install failure due to 'Info.plist: No such file or directory'. Using Crashlytics/Analytics.

### Firebase SDK Version

10.23.0

### Xcode Version

15.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reporting, @thomas151. Have you tried deleting the derived data and tried running the app again?

**Comment by ElSebbo** [comment]
hi, i have the same bug and deleted derived data.

**Comment by paulb777** [comment]
Additionally, please share more context around the error message.

**Comment by thomas151** [comment]
Here is the error details:

`App installation failed: Unable to Install “Quiz Word”
Domain: IXUserPresentableErrorDomain
Code: 1
Failure Reason: Please try again later.
Recovery Suggestion: Failed to load Info.plist from bundle at path /Users/thomasmolinari/Library/Developer/CoreSimulator/Devices/168C3574-B0F3-45F9-8741-2504F70D567A/data/Library/Caches/com.apple.mobile.installd.staging/temp.DMPUyB/extracted/Quiz Word.app/Frameworks/GoogleMobileAds.framework; Extra info about "/Users/thomasmolinari/Library/Developer/CoreSimulator/Devices/168C3574-B0F3-45F9-8741-2504F70D567A/data/Library/Caches/com.apple.mobile.installd.staging/temp.DMPUyB/extracted/Quiz Word.app/Frameworks/GoogleMobileAds.framework/Info.plist": Couldn't stat /Users/thomasmolinari/Library/Developer/CoreSimulator/Devices/168C3574-B0F3-45F9-8741-2504F70D567A/data/Library/Caches/com.apple.mobile.installd.staging/temp.DMPUyB/extracted/Quiz Word.app/Frameworks/GoogleMobileAds.framework/Info.plist: No such file or directory
User Info: {
    DVTErrorCreationDateKey = "2024-03-25 21:17:20 +0000";
    IDERunOperationFailingWorker = IDELaunchiPhoneSimulatorLauncher;
    SimCallingSelector = "installApplication:withOptions:error:";
}
--
App installation failed: Unable to Install “Quiz Word”
Domain: IXUserPresentableErrorDomain
Code: 1
Failure Reason: Please try again later.
Recovery Suggestion: Failed to load Info.plist from bundle at path /Users/thomasmolinari/Library/Developer/CoreSimulator/Devices/168C3574-B0F3-45F9-8741-2504F70D567A/data/Library/Caches/com.apple.mobile.installd.staging/temp.DMPUyB/extracted/Quiz Word.app/Frameworks/GoogleMobileAds.framework; Extra info about "/Users/thomasmolinari/Library/Developer/CoreSimulator/Devices/168C3574-B0F3-45F9-8741-2504F70D567A/data/Library/Caches/com.apple.mobile.installd.staging/temp.DMPUyB/extracted/Quiz Word.app/Frameworks/GoogleMobileAds.framework/Info.plist": Couldn't stat /Users/thomasmolinari/Library/Developer/CoreSimulator/Devices/168C3574-B0F3-45F9-8741-2504F70D567A/data/Library/Caches/com.apple.mobile.installd.staging/temp.DMPUyB/extracted/Quiz Word.app/Frameworks/GoogleMobileAds.framework/Info.plist: No such file or directory
User Info: {
    IDERunOperationFailingWorker = IDELaunchiPhoneSimulatorLauncher;
    SimCallingSelector = "installApplication:withOptions:error:";
}
--
Unable to Install “Quiz Word”
Domain: IXUserPresentableErrorDomain
Code: 1
Failure Reason: Please try again later.
Recovery Suggestion: Failed to load Info.plist from bundle at path /Users/thomasmolinari/Library/Developer/CoreSimulator/Devices/168C3574-B0F3-45F9-8741-2504F70D567A/data/Library/Caches/com.apple.mobile.installd.staging/temp.DMPUyB/extracted/Quiz Word.app/Frameworks/GoogleMobileAds.framework; Extra info about "/Users/thomasmolinari/Library/Developer/CoreSimulator/Devices/168C3574-B0F3-45F9-8741-2504F70D567A/data/Library/Caches/com.apple.mobile.installd.staging/temp.DMPUyB/extracted/Quiz Word.app/Frameworks/GoogleMobileAds.framework/Info.plist": Couldn't stat /Users/thomasmolinari/Library/Developer/CoreSimulator/Devices/168C3574-B0F3-45F9-8741-2504F70D567A/data/Library/Caches/com.apple.mobile.installd.staging/temp.DMPUyB/extracted/Quiz Word.app/Frameworks/GoogleMobileAds.framework/Info.plist: No such file or directory
--
Failed to load Info.plist from bundle at path /Users/thomasmolinari/Library/Developer/CoreSimulator/Devices/168C3574-B0F3-45F9-8741-2504F70D567A/data/Library/Caches/com.apple.mobile.installd.staging/temp.DMPUyB/extracted/Quiz Word.app/Frameworks/GoogleMobileAds.framework; Extra info about "/Users/thomasmolinari/Library/Developer/CoreSimulator/Devices/168C3574-B0F3-45F9-8741-2504F70D567A/data/Library/Caches/com.apple.mobile.installd.staging/temp.DMPUyB/extracted/Quiz Word.app/Frameworks/GoogleMobileAds.framework/Info.plist": Couldn't stat /Users/thomasmolinari/Library/Developer/CoreSimulator/Devices/168C3574-B0F3-45F9-8741-2504F70D567A/data/Library/Caches/com.apple.mobile.installd.staging/temp.DMPUyB/extracted/Quiz Word.app/Frameworks/GoogleMobileAds.framework/Info.plist: No such file or directory
Domain: MIInstallerErrorDomain
Code: 35
User Info: {
    FunctionName = "-[MIBundle _validateWithError:]";
    LegacyErrorString = PackageInspectionFailed;
    SourceFileLine = 64;
}
--

Event Metadata: com.apple.dt.IDERunOperationWorkerFinished : {
    "device_model" = "iPhone16,1";
    "device_osBuild" = "17.0.1 (21A342)";
    "device_platform" = "com.apple.platform.iphonesimulator";
    "dvt_coredevice_version" = "355.24";
    "dvt_mobiledevice_version" = "1643.100.58";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 1;
    "launchSession_targetArch" = arm64;
    "operation_duration_ms" = 5928;
    "operation_errorCode" = 1;
    "operation_errorDomain" = IXUserPresentableErrorDomain;
    "operation_errorWorker" = IDELaunchiPhoneSimulatorLauncher;
    "operation_name" = IDERunOperationWorkerGroup;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 1;
    "param_debugger_type" = 3;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.iphonesimulator";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 1;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_checker_tpc_enable" = 1;
    "param_diag_gpu_frameCapture_enable" = 0;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 0;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 1;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 0;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;
    "param_install_style" = 0;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 0;
    "param_launcher_substyle" = 0;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.application";
    "param_structuredConsoleMode" = 1;
    "param_testing_launchedForTesting" = 0;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "iphonesimulator17.4";
    "sdk_osVersion" = "17.4";
    "sdk_variant" = iphonesimulator;
}
--


System Information

macOS Version 14.4 (Build 23E214)
Xcode 15.3 (22618) (Build 15E204a)
Timestamp: 2024-03-26T08:17:20+11:00`

**Comment by paulb777** [comment]
Looks like an issue with GoogleMobileAds. Please make sure you're using its latest version and follow up on their support channels if there are still issues.

**Comment by thomas151** [comment]
Yes @rizafran I've tried a few different solutions including deleting the derived data, nothing has work so far.
