### ISSUE TITLE
Error Domain=com.google.fcm Code=505 "No APNS token specified before fetching FCM Token" UserInfo={NSLocalizedFailureReason=No APNS token specified before fetching FCM Token}

### ISSUE THREAD

**Issue by Kejiasir** [firebase/firebase-ios-sdk#12637]
### Description

I followed the official documentation and used Cocopods to connect to the `Firebase SDK`

```Swift
pod 'Firebase/Messaging'
pod 'Firebase/Crashlytics'
pod 'Firebase/Analytics'
```

The following code is implemented in `AppDelegate`:
```Swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    facebook(application, didFinishLaunchingWithOptions: launchOptions)
    didFinishLaunchingWithOptions(launchOptions)
    
    FirebaseApp.configure()
    
    UNUserNotificationCenter.current().delegate = self
    
    let authOptions: UNAuthorizationOptions = [.alert, .badge, .sound]
    UNUserNotificationCenter.current().requestAuthorization(
        options: authOptions,
        completionHandler: { _, _ in }
    )
    
    application.registerForRemoteNotifications()
    
    Messaging.messaging().delegate = self
    return true
}
```

```Swift
extension AppDelegate: UNUserNotificationCenterDelegate {
    
    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        log("APNS token: \(deviceToken)")
        Messaging.messaging().apnsToken = deviceToken
        
        Messaging.messaging().token { token, error in
            if let error = error {
                log("Error fetching FCM registration token: \(error)")
            } else if let token = token {
                log("FCM registration token: \(token)")
            }
        }
    }
  
```
    
```Swift
    extension AppDelegate: MessagingDelegate {
        
        func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?) {
            log("Firebase registration token: \(String(describing: fcmToken))")
            
            let dataDict: [String: String] = ["token": fcmToken ?? ""]
            NotificationCenter.default.post(
                name: Notification.Name("FCMToken"),
                object: nil,
                userInfo: dataDict
            )
        }
    }
```
    
`Messaging` does not work as expected, 
`func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?)` method is not called, 
and `Messaging.messaging().token {}` calls back `Error Domain=com.google .fcm Code=505 "No APNS token specified before fetching FCM Token" UserInfo={NSLocalizedFailureReason=No APNS token specified before fetching FCM Token}` Error!
        
        
I have created the project in Firebase backend and uploaded the apns certificate, tried a lot but still can't find a solution.

### Firebase SDK Version

10.23.0

### Xcode Version

15.1

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, Crashlytics, Messaging

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @Kejiasir, per checking, there was a change implemented on [v10.4.0](https://firebase.google.com/support/release-notes/ios#fcm_6) onwards. During app startup, an APNs token must be provided to the SDK before retrieving an FCM token, otherwise an error will be returned as part of the completion in which you have encountered. We are now declining vending an FCM token until an APNS token is provided. You may check this [ticket](https://github.com/firebase/firebase-ios-sdk/issues/10679#issuecomment-1402776795) for more info. Also, I found this [related post](https://stackoverflow.com/questions/58246620/apns-device-token-not-set-before-retrieving-fcm-token-for-sender-id-react-nati/69316428#69316428) that would possibly resolve the issue.

**Comment by anomaddev** [comment]
Chances are a lot of people are getting this error in the Simulator

**Comment by rizafran** [comment]
You may check this [comment](https://github.com/firebase/firebase-ios-sdk/issues/10679#issuecomment-1402776795) for more info about testing in simulator.
