### ISSUE TITLE
Malformed Framework on 10.23.0 version while send to App Store Connect an MacOS Catalyst app

### ISSUE THREAD

**Issue by daviorze** [firebase/firebase-ios-sdk#12643]
### Description

App Store Connect invalidate the binary after sending a new version of the app with Firebase 10.23.0 version.
![Screenshot 2024-03-27 at 15 19 00](https://github.com/firebase/firebase-ios-sdk/assets/11349098/5c1bd9dd-8dc5-4d1c-8fcb-6f754021feb4)

### Reproducing the issue

1) Build and send an new MacOS Catalyst app version to App Store Connect
2) Wait the binary invalidation

### Firebase SDK Version

10.23.0

### Xcode Version

15.3 (15E204a)

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Messaging

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment]
Hi @daviorze, we have a fix for this coming in Firebase 10.24.0 (week of April 9th). See #12587 for more details.
