### ISSUE TITLE
App archive fails validation due to invalid plist file on Xcode 15.3

### ISSUE THREAD

**Issue by baptistedajon** [firebase/firebase-ios-sdk#12642]
### Description

When we try to validate our IPA through AppStoreConnect upload on Xcode 15.3, the binary is rejected.

![Screenshot 2024-03-27 at 16 47 05](https://github.com/firebase/firebase-ios-sdk/assets/1397461/96374c45-a5a8-4ab4-bea3-816e0a6abd20)

### Reproducing the issue

With Xcode 15.3 create an archive of a project with the firebase SDK built in, when you try to validate the IPA, you encounter the issue described earlier.

### Firebase SDK Version

10.22.1

### Xcode Version

15.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Crashlytics, DynamicLinks, Performance

### Targeted Platforms

iOS

**Comment by paulb777** [comment]
GoogleAnalytics and GoogleTagManager are not Firebase SDKs. Please make sure you update them to their latest releases and report on their support channels if the failure still remains.
