### ISSUE TITLE
Archive fails: GoogleMobileAds.framework does not support the minimum OS Version specified in the Info.plist

### ISSUE THREAD

**Issue by jc-paris** [firebase/firebase-ios-sdk#12651]
### Description

An issue (https://github.com/googleads/swift-package-manager-google-mobile-ads/issues/62) have been fixed in Google Mobile Ads SDK 11.2.0 (and UMP SDK 2.3.0), but latest release of Firebase (10.23.0) doesn't ship those SDK version.

Would it be possible to update those framework shipped in the `Firebase.zip` asset of the release ? (or at least to mention than using the release asset framework for Google Ads will lead to this issue..)

### Firebase SDK Version

10.23.0

### Xcode Version

14.3

### Installation Method

Zip

### Firebase Product(s)

Installations

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment]
Hi @jc-paris, thanks for raising. The `Firebase.zip` RC for 10.23 was likely built too early to pull down the Google Mobile Ads SDK 11.2.0 and UMP SDK 2.3.0 SDKs. I can see that those versions are now being included for the upcoming 10.24 release (due out the week of April 9th).
