### ISSUE TITLE
M2 Mac , simulator build error: Unsupported Swift architecture

### ISSUE THREAD

**Issue by fangyuxi** [firebase/firebase-ios-sdk#12650]
### Description

M2 Mac , simulator build error: Unsupported Swift architecture

### Reproducing the issue

M2 Mac , simulator build error: Unsupported Swift architecture
![111](https://github.com/firebase/firebase-ios-sdk/assets/1756038/760e6bdb-9cf1-45ab-a708-45aecc648d68)

### Firebase SDK Version

10.23

### Xcode Version

15.3

### Installation Method

CocoaPods

### Firebase Product(s)

Storage

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by taimoorsuleman** [comment]
facing the same issue on the M1 machine as well.
Not able to run on the Simulator, but it works fine on the device.

**Comment by paulb777** [comment]
@taimoorsuleman Strange that there are build errors for the x86_64 simulator on an M1 machine. Something might be misconfigured.

@fangyuxi We're not able to reproduce and will likely need more information to help.

**Comment by taimoorsuleman** [comment]
> @taimoorsuleman Strange that there are build errors for the x86_64 simulator on an M1 machine. Something might be misconfigured.
> 
> @fangyuxi We're not able to reproduce and will likely need more information to help.

@paulb777  I am getting x86_64 error after updating to firebase latest version.
in previous version its fine. i checked all relevant setting and looks fine.

**Comment by ciriousjoker** [comment]
I have the same issue, also running on an M2 chip. For us this happens when trying to build our watch OS app. On the M3 Pro of a coworker the same code runs fine.

**Comment by ciriousjoker** [comment]
Apparently apple differentiates between "via iphone" and a regular watch simulator. I just went with the default Xcode simulators. After creating a fresh simulator that's paired with an iphone simulator, everything works fine. I just need to run it on the watchOS simulator (not the via iphone one).

![CleanShot 2024-04-18 at 20 43 17@2x](https://github.com/firebase/firebase-ios-sdk/assets/16866223/0e0940a7-8a36-4835-82f7-93abcb2fa275)
