### ISSUE TITLE
Invalid Mac & Catalyst Framework Bundles

### ISSUE THREAD

**Issue by pmacro** [firebase/firebase-ios-sdk#12668]
### Description

I'm unable to create an archive of my Mac Catalyst app due to the Framework Bundles not being correctly setup (please see the attached log snippets).

The problem is that the bundles are supposed to use symlinks, but instead they include three copies of the binary, `Modules`, `Resources`, and `PrivateHeaders`. Taking the example of `GoogleAppMeasurement.xcframework`, this makes it almost twice as large as it needs to be overall, and makes the included macOS and Catalyst `.framework`s three times larger than they should be.

According to [Apple](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkAnatomy.html), the top level entries should symlink to `Versions/Current`, which should in turn symlink to `Versions/A` (or `Versions/Whatever`).

#### Workaround

```
# resolve packages as a separate step
xcodebuild -resolvePackageDependencies -workspace My.xcworkspace -scheme MyScheme -derivedDataPath build -destination generic/platform\=macOS,variant\=Mac\ Catalyst

cd build/SourcePackages/artifacts

# Fixes the "Current" symlink. This makes the archive succeed.
find -P . -regex ".*\.framework/\Versions/\Current" -execdir rm -rf {} \; -execdir ln -s A {} \;
# Find the top-level symlinks and fix those too. The archive succeeds without this, but is rejected by Apple.
# I haven't scripted this yet, but `ln -s ` all top-level entries to the matching Versions/Current/blah entry.

# Create the archive as normal, but avoid touching the packages.
xcodebuild -skipPackageUpdates -workspace My.xcworkspace -scheme MyScheme -derivedDataPath build -destination generic/platform\=macOS,variant\=Mac\ Catalyst archive
```

#### Reproduce errors

- Create a Mac Catalyst (or probably Mac, too) app.
- Add some Firebase dependencies, like FirebaseAnalytics.
- Create an archive using xcodebuild. You should see errors. 

#### Inspect incorrect Framework Bundles

- Download one of the binaries, such as [the analytics one](https://dl.google.com/firebase/ios/swiftpm/10.23.1/FirebaseAnalytics.zip) 
- Compare the Catalyst or Mac frameworks with [Apple's docs](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkAnatomy.html). Also observe the unnecessary copies and wasted bandwidth/CI/storage this causes for Google as well as Firebase users.

### Firebase SDK Version

10.23.1

### Xcode Version

15.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Crashlytics

### Targeted Platforms

macCatalyst

### Relevant Log Output

```shell
Couldn't resolve framework symlink for '/Users/username/dev/MyApp/build/SourcePackages/artifacts/googleappmeasurement/GoogleAppMeasurement/GoogleAppMeasurement.xcframework/ios-arm64_x86_64-maccatalyst/GoogleAppMeasurement.framework/Versions/Current': readlink(/Users/username/dev/MyApp/build/SourcePackages/artifacts/googleappmeasurement/GoogleAppMeasurement/GoogleAppMeasurement.xcframework/ios-arm64_x86_64-maccatalyst/GoogleAppMeasurement.framework/Versions/Current): Invalid argument (22) (in target 'MyApp' from project 'MyApp')
    Couldn't resolve framework symlink for '/Users/username/dev/MyApp/build/SourcePackages/artifacts/firebase-ios-sdk/FirebaseAnalytics/FirebaseAnalytics.xcframework/ios-arm64_x86_64-maccatalyst/FirebaseAnalytics.framework/Versions/Current': readlink(/Users/username/dev/MyApp/build/SourcePackages/artifacts/firebase-ios-sdk/FirebaseAnalytics/FirebaseAnalytics.xcframework/ios-arm64_x86_64-maccatalyst/FirebaseAnalytics.framework/Versions/Current): Invalid argument (22) (in target 'MyApp' from project 'MyApp')
    Couldn't resolve framework symlink for '/Users/username/dev/MyApp/build/SourcePackages/artifacts/googleappmeasurement/GoogleAppMeasurementIdentitySupport/GoogleAppMeasurementIdentitySupport.xcframework/ios-arm64_x86_64-maccatalyst/GoogleAppMeasurementIdentitySupport.framework/Versions/Current': readlink(/Users/username/dev/MyApp/build/SourcePackages/artifacts/googleappmeasurement/GoogleAppMeasurementIdentitySupport/GoogleAppMeasurementIdentitySupport.xcframework/ios-arm64_x86_64-maccatalyst/GoogleAppMeasurementIdentitySupport.framework/Versions/Current): Invalid argument (22) (in target 'MyApp' from project 'MyApp')
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

      {
        "package": "Firebase",
        "repositoryURL": "https://github.com/firebase/firebase-ios-sdk",
        "state": {
          "branch": null,
          "revision": "888f0b6026e2441a69e3ee2ad5293c7a92031e62",
          "version": "10.23.1"
        }
      },
      {
        "package": "GoogleAppMeasurement",
        "repositoryURL": "https://github.com/google/GoogleAppMeasurement.git",
        "state": {
          "branch": null,
          "revision": "c7a5917ebe48d69f421aadf154ef3969c8b7f12d",
          "version": "10.23.1"
        }
      },
      {
        "package": "GoogleDataTransport",
        "repositoryURL": "https://github.com/google/GoogleDataTransport.git",
        "state": {
          "branch": null,
          "revision": "a637d318ae7ae246b02d7305121275bc75ed5565",
          "version": "9.4.0"
        }
      },
      {
        "package": "GoogleUtilities",
        "repositoryURL": "https://github.com/google/GoogleUtilities.git",
        "state": {
          "branch": null,
          "revision": "26c898aed8bed13b8a63057ee26500abbbcb8d55",
          "version": "7.13.1"
        }
      },

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by pmacro** [comment]
I missed that this is essentially a duplicate of https://github.com/firebase/firebase-ios-sdk/issues/12587

**Comment by ncooke3** [comment]
`zip -r` is used to compress the XCFrameworks for SwiftPM binary distros. It looks like this is does not preserve the symlinks when unzipping.

**Comment by ncooke3** [comment]
The release tooling is being updated to zip with the `--symlinks` flag in 10.24.0 to preserve the symlinks and avoid the unneeded extra directories.

**Comment by cdebortoliWebedia** [comment]
It seems linked, I cannot push on git the updated frameworks (from Cocoapods). There is no problem with the 10.22.0 version.

> fatal: pathspec 'Pods/FirebaseAnalytics/Frameworks/FirebaseAnalytics.xcframework/ios-arm64_x86_64-maccatalyst/FirebaseAnalytics.framework/Headers/FIRAnalytics+AppDelegate.h' is beyond a symbolic link

**Comment by stopthatnoise** [comment]
the problem with 

> fatal: pathspec 'QR_BarcodeScanner/Pods/FirebaseAnalytics/Frameworks/FirebaseAnalytics.xcframework/ios-arm64_x86_64-maccatalyst/FirebaseAnalytics.framework/Headers/FIRAnalytics+AppDelegate.h' is beyond a symbolic link

still exist in 10.24. I cannot stage pods for git. 10.22 works fine

**Comment by stopthatnoise** [comment]
the problem with

fatal: pathspec '/Pods/FirebaseAnalytics/Frameworks/FirebaseAnalytics.xcframework/ios-arm64_x86_64-maccatalyst/FirebaseAnalytics.framework/Headers/FIRAnalytics+AppDelegate.h' is beyond a symbolic link

still exist in 10.24. I cannot stage pods for git. 10.22 works fine

**Comment by appfrilans** [comment]
Get similar issues with Xcode 15.3 and Firebase 10.24:

```
/Users/xxxx/Library/Developer/Xcode/DerivedData/.....x.app: code object is not signed at all
In subcomponent: /Users/xxxx/Library/Developer/Xcode/DerivedData/projectx-cysskpexycpatifcnhjfjwtdldad/Build/Products/Debug-maccatalyst/x.app/Contents/Frameworks/GoogleAppMeasurement.framework
```

**Comment by ncooke3** [comment]
> the problem with
> 
> > fatal: pathspec '/Pods/FirebaseAnalytics/Frameworks/FirebaseAnalytics.xcframework/ios-arm64_x86_64-maccatalyst/FirebaseAnalytics.framework/Headers/FIRAnalytics+AppDelegate.h' is beyond a symbolic link
> 
> still exist in 10.24. I cannot stage pods for git. 10.22 works fine

@stopthatnoise, could you please open a new issue with more details on the error, including how to reproduce?

--- 

@appfrilans, could you please open a new issue with more details on how the `code object is not signed at all` error appeared?

**Comment by mushyoom** [comment]
@ncooke3 (@stopthatnoise )

> the problem with
> 
> >fatal: pathspec '/Pods/FirebaseAnalytics/Frameworks/FirebaseAnalytics.xcframework/ios-arm64_x86_64-maccatalyst/FirebaseAnalytics.framework/Headers/FIRAnalytics+AppDelegate.h' is beyond a symbolic link
> 
> still exist in 10.24. I cannot stage pods for git. 10.22 works fine

Hi, I have opened an [issue](https://github.com/firebase/firebase-ios-sdk/issues/12801) to describle the detail .
Looking forward to your confirmation and response :)
