### ISSUE TITLE
Non-sendable type Query / CollectionReference cause warnings in any actor-isolated context 

### ISSUE THREAD

**Issue by SwiftfulThinking** [firebase/firebase-ios-sdk#12666]
### Description

Any time I try to use Firestore in an actor-isolated context (ie. within an Actor or a class on the MainActor), there are warnings that `Non-sendable type... cannot cross actor boundary`. This applies to `Query` and `CollectionReference`. Is there an approach to avoid this or can these classes become `Sendable`?

Notes: 
- These warnings appear after setting **Strict Concurrency Checking** to **Complete**.
- I wasn't sure whether to label this as a bug and I couldn't find anything in the documentation explaining how to avoid this.

### Reproducing the issue

![Screenshot 2024-03-29 at 7 40 24 PM](https://github.com/firebase/firebase-ios-sdk/assets/44950578/074e6604-b527-4b5c-8a66-852815220a13)

### Firebase SDK Version

10.23.0

### Xcode Version

15.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by wu-hui** [comment]
The firestore API was designed before swift actors existed. We do intend to improve the situation, but this needs to be carefully examined as the SDK is written in C++. I will add this to our todo list, but we also won't have capacity to address in the near future.

Thanks for the report though!

**Comment by mortenbekditlevsen** [comment]
One suggestion is to do the parsing while still on the background thread, then just passing a parsed (Sendable, plain value type) model back to the main thread.
Would that work for you?
