### ISSUE TITLE
Create GitHub release for 10.23.1 to match Firebase documentation and 10.23.1 tag picked up by Swift Package Manager

### ISSUE THREAD

**Issue by SwiftNativeDeveloper** [firebase/firebase-ios-sdk#12674]
### Description

@paulb777 

I noticed Swift Package Manager updated Firebase to 10.23.1 today, but that was not listed as a release on GitHub. It is however documented as a release on Firebase release notes page.

Since you publish releases on GitHub it would be great to keep these in sync within a reasonable time frame.

### Reproducing the issue

Visit https://github.com/firebase/firebase-ios-sdk/releases and observe there is no listing for 10.23.1 but it was tagged and becomes part of SBOM for developers using 'up to next major' or 'up to next minor' SEMVER + Swift Package Manager logic.

https://github.com/firebase/firebase-ios-sdk/releases/tag/10.23.1

### Firebase SDK Version

10.23.x

### Xcode Version

15.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

All

### Targeted Platforms

iOS

### Relevant Log Output

```shell
N/A
```

### If using Swift Package Manager, the project's Package.resolved

N/A

### If using CocoaPods, the project's Podfile.lock

N/A

**Comment by paulb777** [comment]
@SwiftNativeDeveloper Thanks for the callout. Done at https://github.com/firebase/firebase-ios-sdk/releases/tag/10.23.1
