### ISSUE TITLE
'FirebaseCrashlytics/FirebaseCrashlytics-Swift.h' file not found

### ISSUE THREAD

**Issue by ayang229** [firebase/firebase-ios-sdk#12676]
### Description

When update to Lastest version 10.23.1, build failed with error : 'FirebaseCrashlytics/FirebaseCrashlytics-Swift.h' file not found

### Firebase SDK Version

10.23.1

### Xcode Version

15.3

### Installation Method

CocoaPods

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @ayang229, this seems related to #12611 and the fix will be released in [Firebase 10.24.0](https://github.com/firebase/firebase-ios-sdk/issues/12611#issuecomment-2028821390). That being said, I'll now be closing this ticket as dupe.
