### ISSUE TITLE
UITest fails to launch with Xcode 15.3

### ISSUE THREAD

**Issue by tristangrichard** [firebase/firebase-ios-sdk#12689]
### Description

I have a project with Firebase 10.22.1 running on Xcode 15.2.

When updating to Xcode 15.3 I get the following error when running UITests (No issues with Unittest or running the app):
```
App installation failed: Unable to Install MyApp
	MyApp encountered an error (Failed to install or launch the test runner. (Underlying Error: App installation failed: Unable to Install MyApp. Please try again later. MyApp.app/Frameworks/GoogleAppMeasurement.framework is missing its bundle executable. Please check your build settings to make sure that a bundle executable is produced at the path "MyApp.app/Frameworks/GoogleAppMeasurement.framework/GoogleAppMeasurement". (Underlying Error: Unable to Install MyApp. Please try again later. MyApp.app/Frameworks/GoogleAppMeasurement.framework is missing its bundle executable. Please check your build settings to make sure that a bundle executable is produced at the path "MyApp.app/Frameworks/GoogleAppMeasurement.framework/GoogleAppMeasurement". (Underlying Error: MyApp.app/Frameworks/GoogleAppMeasurement.framework is missing its bundle executable. Please check your build settings to make sure that a bundle executable is produced at the path "MyApp.app/Frameworks/GoogleAppMeasurement.framework/GoogleAppMeasurement". (Underlying Error: lstat of /Users/vm1/Library/Developer/CoreSimulator/Devices/ED358040-6D56-47FC-8586-5D5F87AA56B4/data/Library/Caches/com.apple.mobile.installd.staging/temp.ni39kN/extracted/MyApp.app/Frameworks/GoogleAppMeasurement.framework/GoogleAppMeasurement failed: No such file or directory)))))
```
Updating to Firebase 10.23.1, clearing derived data  does not help.

Can anyone help?

### Firebase SDK Version

10.22.1

### Xcode Version

15.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics, Analytics, Performance

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @tristangrichard, I tried to reproduce but I was able to run UITest successfully using v10.22.1 on Xcode 15.3. Could you share a sample app so I could reproduce the issue?

**Comment by tristangrichard** [comment]
Hi @rizafran, 
I cannot reproduce it myself by running the tests directly from Xcode. They seem to only fail when executed by our ADO pipeline.
The unit tests runs fine but ui tests fails to launch.

**Comment by waylybaye** [comment]
This error occurs when executing via the command line:

```
xcodebuild test -scheme DemoScheme -project DemoScheme.xcodeproj -destination "platform=iOS Simulator,name=iPhone 15"
```

**Comment by paulb777** [comment]
We'll need a fully reproducible example to help.

**Comment by waylybaye** [comment]
Xcode 15.4 RC has fixed this issue.
