### ISSUE TITLE
[FR]: Add privacy manifest to GoogleAppMeasurementOnDeviceConversion

### ISSUE THREAD

**Issue by ben-p-commits** [firebase/firebase-ios-sdk#12684]
### Description

It appears that `GoogleAppMeasurementOnDeviceConversion` was missed when privacy manifests were added to the various modules in this repository.

I see usage of `lstat` and `stat` in the binary [that will require this ](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api) be handled for applications using this dependency.

Note: I used this tool to spot this issue: https://github.com/Wooder/ios_17_required_reason_api_scanner 

### Firebase Product(s)

Analytics

**Comment by ncooke3** [comment]
Hi @ben-p-commits, what version of `GoogleAppMeasurementOnDeviceConversion` are you using?

**Comment by ben-p-commits** [comment]
`.product(name: "FirebaseAnalyticsOnDeviceConversion", package: "firebase-ios-sdk"),`
from:
`.package(url: "https://github.com/firebase/firebase-ios-sdk", exact: "10.22.1"),`

**Comment by ncooke3** [comment]
10.24.0 is now available and features the removal of `lstat` and `stat` from the `GoogleAppMeasurementOnDeviceConversion` binary.

**Comment by ben-p-commits** [comment]
@ncooke3, thanks so much for the quick turnaround!

Small nitpick in case it was missed: the [10.24 changelog doesn't seem to mention this](https://firebase.google.com/support/release-notes/ios#version_10240_-_april_9_2024) for 10.24.0.

**Comment by ncooke3** [comment]
Hi @ben-p-commits, no problem! For the release note, GoogleAppMeasurementOnDeviceConversion is part of Google Analytics for Firebase, so this required reasons cleanup was tied to "Internal code cleanup." from https://firebase.google.com/support/release-notes/ios#analytics
