### ISSUE TITLE
[FR]: Add privacy manifest to InAppMessaging&Sessions

### ISSUE THREAD

**Issue by tetsu888** [firebase/firebase-ios-sdk#12698]
### Description

It appears that InAppMessaging & Sessions was missed when privacy manifests were added to the various modules in this repository.
I was expecting to see at least one entry for NSPrivacyAccessedAPICategoryUserDefaults. 

FirebaseInAppMessaging:
https://github.com/search?q=repo%3Afirebase%2Ffirebase-ios-sdk+UserDefaults+path%3A%2F%5EFirebaseInAppMessaging%5C%2FSources%5C%2F%2F&type=code

FirebaseSessions:
https://github.com/firebase/firebase-ios-sdk/blob/ed28962222d9122a9cf3d642832dafef2d7c28fe/FirebaseSessions/Sources/Settings/SettingsCacheClient.swift#L51

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc

### Firebase Product(s)

In-App Messaging

**Comment by paulb777** [comment]
Similar to #12488, so far we've only published manifests for SDKs named by Apple on [this list](https://developer.apple.com/support/third-party-SDK-requirements/). We're still working on the Firebase SDKs that are not on that list.

**Comment by ncooke3** [comment]
To eliminate required reasons impact, all required reason symbols have been removed from Sessions (#12752) and Performance (#12757). This will be released in the next Firebase release, 10.25.0.
