### ISSUE TITLE
Implicit declaration of function 'pb_release' is invalid in C99 - GDTCCTUploader

### ISSUE THREAD

**Issue by ykhandelwal913** [firebase/firebase-ios-sdk#12699]
### Description

 error: call to undeclared function 'pb_release'; ISO
      C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  pb_release(gdt_client_metrics_ClientMetrics_fields, &clientMetricsProto);

The following build commands failed:
	CompileC /Users/xxxxx/test/iOS/output/aws/Build/Intermediates.noindex/GoogleDataTransport.build/Debug-iphoneos/GoogleDataTransport.build/Objects-normal/arm64/GDTCORMetrics+GDTCCTSupport.o /Users/xxxxx/test/iOS/output/aws/SourcePackages/checkouts/GoogleDataTransport/GoogleDataTransport/GDTCCTLibrary/GDTCORMetrics+GDTCCTSupport.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'GoogleDataTransport' from project 'GoogleDataTransport')

I see similar issue reported https://github.com/firebase/firebase-ios-sdk/issues/6741.

@chanuuuu  how did you resolve this issue with fastlane?

### Firebase SDK Version

10.23.1

### Xcode Version

15.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
As discussed in #6741 and [stackoverflow](https://stackoverflow.com/a/55892511/556617), this is an issue with fastlane and not Firebase. If the answers on those links don't help you, please follow up on stackoverflow or with fastlane.
