### ISSUE TITLE
Phone auth not working

### ISSUE THREAD

**Issue by StrelnikovEugene** [firebase/firebase-ios-sdk#127]
Sms with a code does not arrive. Everything looks normal, no errors in debug mode. I get the verificationId, but not the SMS. Two days ago everything worked fine, with the same code.

**Comment by paulb777** [comment]
Thanks for the report. We'll likely need more details, but will check with the auth team before closing.

**Comment by StrelnikovEugene** [comment]
* Xcode version: 8.3.2 (8E2002)
 * FirebaseAuth (4.0.0)
 * Russia

**Comment by XiangtianDai** [comment]
@StrelnikovEugene Please try again, and then send me the phone number in question, the mobile carrier for this phone number, and the approximate time and date (with time zone) for the phone number auth request to my email address, so I can file an internal ticket to investigate. 

Thanks for using Firebase.

**Comment by StrelnikovEugene** [comment]
suddenly started to work. I hope there won't be any other problems

**Comment by paulb777** [comment]
@StrelnikovEugene Thanks for checking. I'll close the issue. If it reoccurs, please create another issue and send the above requested information to @XiangtianDai
