### ISSUE TITLE
FirebaseApp.configure() Blocks the main thread for too long

### ISSUE THREAD

**Issue by lucasmarcal-faire** [firebase/firebase-ios-sdk#12717]
### Description

While running `FirebaseApp.configure()` the main thread gets blocked for more than `100ms` on iPhone 15 Pro Max and it's causing our App Startup time to grown.

![Screenshot 2024-04-05 at 8 31 09 PM](https://github.com/firebase/firebase-ios-sdk/assets/127062836/95722d59-0dc5-4cc2-bdf8-0ae8ef67034e)

``` 
* Configures a default Firebase app. Raises an exception if any configuration step fails. The
 * default app is named "__FIRAPP_DEFAULT". This method should be called after the app is launched
 * and before using Firebase services. This method should be called from the main thread and
 * contains synchronous file I/O (reading GoogleService-Info.plist from disk).
 ```

It should have be a better solution than running synchronous file I/O on main thread, as some apps usually call it while initializing.

While evaluating the option to use `+ (void)configureWithOptions:(FIROptions *)` noticed the following comment:

```
/**
 * Configures the default Firebase app with the provided options. The default app is named
 * "__FIRAPP_DEFAULT". Raises an exception if any configuration step fails. This method should be
 * called from the main thread.
 *
 * @param options The Firebase application options used to configure the service.
 */
```
So no alternatives since we use Firebase Analytics.

Any ideas of how to improve the configuration time in this case?

### Firebase SDK Version

10.11

### Xcode Version

15.3

### Installation Method

Carthage

### Firebase Product(s)

All

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
Please share a reproducible example or details of what's in `firebaseStartup` including the call of what's actually blocking.

**Comment by nashysolutions** [comment]
We've encountered a similar issue with blocking on the main thread, leading to increased startup times in our application as well. Our measurements indicate substantial delays that seem out of the ordinary for what one would expect during app initialisation. We've taken a deep dive into the startup process and have isolated the problem to a specific line of code that we believe is the culprit.

If it's helpful for diagnostic purposes, we can provide additional details on the exact line and the observed behavior in our codebase. Collaboratively, we hope to find a resolution that reduces the blocking time, potentially through asynchronous loading or another optimised approach. Looking forward to more discussion on this and potential solutions.

<img width="1530" alt="Screenshot 2024-04-18 at 15 49 40" src="https://github.com/firebase/firebase-ios-sdk/assets/64097812/078cfd13-1b1d-4e12-bd20-980901a1e4e6">

**Comment by paulb777** [comment]
@nashysolutions Two areas for deeper investigation:

- The Promises SDK is a dependency of several Firebase products. Can you isolate which library/call leads to the hang?
- I notice the FirebasePerformance InstrumentorForClass method. Does removing FirebasePerformance impact the hang?
