### ISSUE TITLE
Missing Privacy manifest declaration for NSPrivacyAccessedAPICategorySystemBootTime usage

### ISSUE THREAD

**Issue by naveengaur800** [firebase/firebase-ios-sdk#12727]
### Description

It seems Apple is not picking up the privacy manifest when submitting an app with FirebaseCrashlytics integrated. I am using the 10.23.1 version of the SDK and it doesn't seems to work. 

I can see the usage of `mach_absolute_time` in `FIRCLSProfiling.c` file which might be the root cause of this issue. Can we please look into this and if needed update the SDK with updated manifest to silence the warning from Apple.

### Firebase SDK Version

10.23.0

### Xcode Version

15.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
Usages of `mach_absolute_time` were removed in #12664 and is being released in today's 10.24.0 release.
