### ISSUE TITLE
[FR]: Add privacy manifest to Installations&Messaging

### ISSUE THREAD

**Issue by tetsu888** [firebase/firebase-ios-sdk#12721]
### Description

It appears that Installations & Messaging was missed when privacy manifests were added to the various modules in this repository.
I was expecting to see at least one entry for NSPrivacyAccessedAPICategoryUserDefaults.

FirebaseInstallations:
https://github.com/search?q=repo%3Afirebase%2Ffirebase-ios-sdk++userDefaults+path%3AInstallation&type=code

FirebaseMessaging:
https://github.com/search?q=repo%3Afirebase%2Ffirebase-ios-sdk++userDefaults+path%3A%2F%5EFirebaseMessaging%5C%2F%2F&type=code

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc

### Firebase Product(s)

Installations, Messaging

**Comment by ncooke3** [comment]
Hi @tetsu888, thanks for opening. Could you please re-open an issue using the [bug template](https://github.com/firebase/firebase-ios-sdk/issues/new?assignees=&labels=&projects=&template=BUG_REPORT.yml)? That template will include other information that will be helpful in triaging this.

In Firebase 10.22.0, privacy manifests were added for both of these products:
- https://github.com/firebase/firebase-ios-sdk/tree/10.22.0/FirebaseMessaging/Sources/Resources
- https://github.com/firebase/firebase-ios-sdk/tree/10.22.0/FirebaseInstallations/Source/Library/Resources
