### ISSUE TITLE
10.23.1 use host:  https://app-analytics-services-att.com that considered malicious by Virustota

### ISSUE THREAD

**Issue by IdoMDigiBank** [firebase/firebase-ios-sdk#12720]
### Description

In firebase iOS SDK ver 10.23.1 we see this host:  https://app-analytics-services-att.com that considered malicious by Virustota

### Reproducing the issue

1. call to `FirebaseApp.configure()`
2. go to background
3. return from background 
get the logs:
 Uploading data. Host: https://app-analytics-services-att.com/a

### Firebase SDK Version

10.23.1

### Xcode Version

15.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
[FirebaseAnalytics][I-ACS900000] Uploading data. Host: https://app-analytics-services-att.com/a
[FirebaseAnalytics][I-ACS901006] Received SSL challenge for host. Host: https://app-analytics-services-att.com/a
 [FirebasePerformance][I-PRF100009] Logging network request trace - https://app-analytics-services-att.com/a, Response code: 204, 209.1050m
```

**Comment by ncooke3** [comment]
Hi @IdoMDigiBank, thanks for reporting. That is a Google Analytics for Firebase domain. The team is working with VirusTotal to address this  false positive.
