### ISSUE TITLE
Requested Entity Not Found for recently received token

### ISSUE THREAD

**Issue by remstos** [firebase/firebase-ios-sdk#12736]
### Description

We received invalid push registration token via the delegate method.

We receive the registration token in `func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?)`, send it to our backend. At every app launch.
And a moment later when the backend tries to send a notification to that token, it gets a `Requested Entity was not found` error.
The device/user continue to receive the same registration token after, so it keeps failing.

Eventually fixed by having the user reinstalling the app.

### Evidence 1

Log of the ios app sending a registration to our backend. This is using the token directly received from `didReceiveRegistrationToken`

<img width="622" alt="Screenshot 2024-04-08 at 18 50 08" src="https://github.com/firebase/firebase-ios-sdk/assets/4311124/79c2b415-22b3-4937-8fab-1b56e27fe6c0">

### Evidence 2

<img width="658" alt="Screenshot 2024-04-08 at 18 50 23" src="https://github.com/firebase/firebase-ios-sdk/assets/4311124/baf6fced-d1d5-4ba7-bea2-c57f02c77541">

We had this issue, updated sdk to 10.23.1 and still reproduce.

### Reproducing the issue

Implement `didReceiveRegistrationToken` to receive registration token on app launch.

```
func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?) {
      FirebaseMessagingHelper.shared.didReceiveFCMRegistrationToken(fcmToken) // Our code to send to backend
}
```

Try to send a notification to that token.

Happens after some time (few hours) living on the same registration token.

### Firebase SDK Version

10.23.1

### Xcode Version

15.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

In-App Messaging

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

{
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk",
      "state" : {
        "revision" : "888f0b6026e2441a69e3ee2ad5293c7a92031e62",
        "version" : "10.23.1"
      }
    }

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by aymericbeaumet** [comment]
We are also facing the same issue. Are we missing something obvious here @ncooke3 @paulb777? Thanks 🙏

**Comment by rizafran** [comment]
Hi @remstos, as discussed with the team, please file a ticket to our [Firebase Support](https://firebase.google.com/support) so the team could be able to assist you in checking your project and affected token in the backend. Thanks.

**Comment by remstos** [comment]
@rizafran that makes sense, I’ve reached out the the Support. Thanks.
