### ISSUE TITLE
The host https://app-analytics-services-att.com is considered malicious by Norton 360 when backgrounding the app, Apple Transparency Tracking set to "Ask app not to Track"

### ISSUE THREAD

**Issue by RGG-jayoung** [firebase/firebase-ios-sdk#12735]
### Description

If 10.23.0, 10.23.1 are included in the app and Norton 360 is installed on the device, `https://app-analytics-services-att.com` and `https://app-analytics-services.com` are flagged as malicious by Norton. (see screenshot). 

### When you use the app using 10.23.0:

- `NSPrivacyTracking` set to `YES`
- `https://app-analytics-services-att.com` and `https://app-analytics-services.com` included in `NSPrivacyTrackingDomains`

The Norton warning appears in multiple places:

1. on app launch
2. while using the app generating events
3. when backgrounding the app

### When you use the app using 10.23.1:

- `NSPrivacyTracking` set to `YES`
- `https://app-analytics-services-att.com` and `https://app-analytics-services.com` included in `NSPrivacyTrackingDomains`

The Norton warning is reduced, appearing:

3. when backgrounding the app

<img width="723" alt="image" src="https://github.com/firebase/firebase-ios-sdk/assets/53495188/41a5ceef-3889-44f8-8c47-9dd23f5c4c81">

It is unclear to us what the actual effect of the privacy manifest(s) should be having on this URL. Even after following guidance, adding these problematic URLs to the list, we still see the issue. The latest SDK update has some improvement, but not a complete fix.

### Reproducing the issue

1. Install Norton 360 on iOS 16.5, iOS 17 (we have multiple reports spanning across all these versions).
5. Open an app that used Firebase Analytics.
6. When the Apple Tracking Transparency Prompt appears, select "Allow".
7. Traffic will be submitted `https://app-analytics-services-att.com` if you audit the traffic. When it is set to "Don't track" https://app-analytics-services.com is called instead and there is no issue.

<img width="723" alt="image" src="https://github.com/firebase/firebase-ios-sdk/assets/53495188/41a5ceef-3889-44f8-8c47-9dd23f5c4c81">

Notes:
We build a special versions of our apps with various Firebase components removed to narrow this down, as long as Firebase Analytics is set up traffic is called.

In 

### Firebase SDK Version

10.23.0-10.23.1

### Xcode Version

15.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Crashlytics, Performance

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by RGG-jayoung** [comment]
This feels closely related to:
https://github.com/firebase/firebase-ios-sdk/issues/12720

**Comment by RGG-jayoung** [comment]
After studying this more, we only see the `app-analytics-services-att.com` traffic if `FirebaseApp.configure()` is called in code.

**Comment by Jerry-Fields** [comment]
For the Firebase Team-  Do you know when the Firebase Team may have a resolution to this issue?

Also, do you know why other applications are not seeing the issue?

Is there a recommendation of any type of code adjustment we should make on our end?

**Comment by Jerry-Fields** [comment]
is there any reason to think there is real security exposure to using Firebase right now?

**Comment by Jerry-Fields** [comment]
@ncooke3 Hello.  On the Norton site, Norton now rates this url http://app-analytics-services-att.com/ as safe, but mobile users with Norton AV installed on their mobile device still recieve an "unsafe site" warning when shopping our sites.  Can Firebase reach out to Norton to determine what needs to be done so a memebr/customer won't see a warning message?
![Norton Screenshot 2024-04-12 ](https://github.com/firebase/firebase-ios-sdk/assets/166658553/c5970c57-11f5-4d7b-933a-30cd813f2643)

**Comment by paulb777** [comment]
This should now be addressed with Norton. Please let us know if it's still occurring.
