### ISSUE TITLE
Remote config's condition doesn't work for Welsh language

### ISSUE THREAD

**Issue by carlchung** [firebase/firebase-ios-sdk#12742]
### Description

In firebase remote config, we created a condition that applies if languages is in Welsh. We uses this condition in a remote config parameter, it always falls through to default value if this is the only condition or falls through to the next condition.

We have tried condition with other language (Spanish) which works. Unfortunately we do need Welsh for our language-specified functionality.

### Reproducing the issue

Firebase console remote config project:
1. Create a remote config condition: Applies if "Languages" is in "Welsh"
2. Click Save condition button
3. Create a new parameter, put in parameter name
4. Click Add new button to add condition , click conditional value and select the new condition 
5. Put in a value for this new condition
6. Put in a value as default
7. Click Save button

### Firebase SDK Version

10.20.0

### Xcode Version

15.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Remote Config

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

{
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk.git",
      "state" : {
        "revision" : "b880ec8ec927a838c51c12862c6222c30d7097d7",
        "version" : "10.20.0"
      }
    }

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ddnan** [comment]
Thanks for reporting, @carlchung . Did you see any estimation number of users showing up after selected "Languages" is in "Welsh" when creating the condition? If no, I think for now condition does not support Welsh.

**Comment by carlchung** [comment]
It shows "Fewer than 100 users match this condition"

**Comment by ddnan** [comment]
Hi, @carlchung . Looks this is not iOS specific, would you please file a support case here (https://firebase.google.com/support/troubleshooter/contact)? So, we can investigate internally.

**Comment by carlchung** [comment]
I got this when I visit the link and click sign on

> We are sorry, but you do not have access to Google Developers. Some reasons why you may not have access:
> - Your account is managed by an organisation that has this service turned off for its users.

I will submit the support case using my personal gmail

Thank you for looking into this.

**Comment by paulb777** [comment]
Closing since its being addressed by a support request for the backend.
