### ISSUE TITLE
[Sessions Integration Tests] fail running on macos-14

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#12771]
### Description

The tests fail. Fix and update session-integration-tests.yml to use macos-14

Testing failed:
	UITests_iOS-Runner (93978) encountered an error (The test runner failed to initialize for UI testing. (Underlying Error: Timed out while loading Accessibility.))

** TEST FAILED **

### Reproducing the issue

https://github.com/firebase/firebase-ios-sdk/actions/runs/8638279486/job/23682376410

### Firebase SDK Version

10.24.0

### Xcode Version

15.3

### Installation Method

CocoaPods

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by themiswang** [comment]
Seems like it related to the performance issue for xcode15? I am seeing many discussions within the community: https://github.com/orgs/community/discussions/68807,  https://discuss.circleci.com/t/severe-performance-problems-with-xcode-15/49205/47

**Comment by themiswang** [comment]
Hmmmm reran the job seems works this time https://github.com/firebase/firebase-ios-sdk/actions/runs/8638279486/job/24694636170, it references the head commit of [this change](https://github.com/firebase/firebase-ios-sdk/commit/fb6bc825c96b1ee42c26bdc96ff87fe158e0342d), old job could be flaky.

**Comment by ncooke3** [comment]
Some more evidence that the flakes are runner specific– [actions/runner-images/#9591](https://github.com/actions/runner-images/issues/9591) 

I haven't investigated, but it is interesting that certain SDKs are failing (and then successfully re-running) consistently.
