### ISSUE TITLE
ld: Undefined symbols:     _FBLPromiseErrorDomain

### ISSUE THREAD

**Issue by sylvia-tencent-wmt** [firebase/firebase-ios-sdk#12772]
### Description

Xcode version: 15.2
Min deployment target: iOS 12
Firebase SDK version: 10.22.0

Error: ld: Undefined symbols:
    _FBLPromiseErrorDomain, referenced from:
        ___62-[GULKeychainStorage getObjectForKey:objectClass:accessGroup:]_block_invoke in GoogleUtilities[8](GULKeychainStorage.o)
    _OBJC_CLASS_$_FBLPromise, referenced from:
         in FirebaseCrashlytics[arm64][18](FIRCLSDataCollectionArbiter.o)
    _OBJC_CLASS_$_FIRHeartbeatController, referenced from:
         in FirebaseCore[13](FIRHeartbeatLogger.o)
  clang: error: linker command failed with exit code 1 (use -v to see invocation)

Integrated all the frameworks in the FirebaseAnalytics folder into Xcode project.
Added -ObjC and -lc++ in other linker flags, the issue still exists.

### Reproducing the issue

I build it on a pipeline. 

### Firebase SDK Version

10.22.0

### Xcode Version

15.2

### Installation Method

Zip

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
Please confirm that FirebaseCoreInternal.xcframework and PromisesSwift.xcframework are copied and linked.
