### ISSUE TITLE
Data injection vulnerability

### ISSUE THREAD

**Issue by piars777** [firebase/firebase-ios-sdk#12789]
### Description

We use fortify to detect vulnerability and in RCNConfigDBManager.m, the method loadMetadataTableWithBundleIdentifier:namespace:() writes unvalidated input into JSON. This call could allow an attacker to inject arbitrary elements or attributes into the JSON entity.The method writes unvalidated input into JSON. This call could allow an attacker to inject arbitrary elements or attributes into the JSON entity.
Before serializing to json, a check must be performed to verify that any untrusted data is properly delimited and escaped

### Reproducing the issue

we reproduce this issue with the last sdk version

### Firebase SDK Version

10.9

### Xcode Version

15.3

### Installation Method

CocoaPods

### Firebase Product(s)

Remote Config

### Targeted Platforms

iOS

**Comment by morganchen12** [comment]
There's no calls to `NSJSONSerialization` in the `loadMetadataTableWithBundleIdentifier:namespace:` method. Other JSON serialization calls in this method serialize and deserialize configs that are fetched from Firebase, and use those configs for not particularly sensitive operations (rollouts and personalization). Can you describe what exactly the vulnerability is here?
