### ISSUE TITLE
Privacy manifest is missing for FirebaseAnalyticsOnDeviceConversion

### ISSUE THREAD

**Issue by gaurav-gupta7** [firebase/firebase-ios-sdk#12786]
### Description

Privacy manifest is missing for FirebaseAnalyticsOnDeviceConversion. podspec doesn't mention any bundle resource

### Firebase SDK Version

10.24.0

### Xcode Version

15.2

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, All

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
FirebaseAnalyticsOnDeviceConversion doesn't have a privacy manifest because it doesn't use any required reason APIs.
