### ISSUE TITLE
Compiler version

### ISSUE THREAD

**Issue by galgrien** [firebase/firebase-ios-sdk#12794]
### Description

Hey! When I'm integrated `.xcframework`s and trying compile project got this error message:

<img width="690" alt="Screenshot 2024-04-15 at 18 42 40" src="https://github.com/firebase/firebase-ios-sdk/assets/167118408/226ae0ff-8751-4ea7-bdaa-a2ab718c5a02">

### Firebase SDK Version

10.24.0

### Xcode Version

15.3

### Installation Method

Zip

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

**Comment by paulb777** [comment]
Closing in favor of the more detailed #12800
