### ISSUE TITLE
[FR]: Change name request, code with name that exactly matches with "required reason API description"

### ISSUE THREAD

**Issue by jesus-mg-ios** [firebase/firebase-ios-sdk#12795]
### Description

As you know is mandatory for apps and third parties to describe the use of certain APIs in an XCPrivacy report.
The request is simple, change properties and methods that can match them to prevent false positives in repository scans.

### API Proposal

For example "creationDate" of Auth metadata could be like in the web sdk API "creationTime" or "creationTimestamp" 

### Firebase Product(s)

AB Testing, Analytics, App Check, App Distribution, Authentication, Crashlytics, Database, DynamicLinks, Firestore, Functions, In-App Messaging, Installations, ML Model Downloader, Messaging, Performance, Remote Config, Storage, Vertex AI

**Comment by paulb777** [comment]
@jesus-mg-ios Thanks for the feature request. We'll consider once Apple's requirements and tooling stabilize.

In the meantime, the `nm` tool on a built binary is an alternative.

**Comment by paulb777** [comment]
Closing, since no upvotes and no plans for this.
