### ISSUE TITLE
After upgrade to 10.24.0 version to became compiler error 

### ISSUE THREAD

**Issue by MRSorokinMaxim** [firebase/firebase-ios-sdk#12797]
### Description

Compile logs:

**Showing All Messages**
SwiftEmitModule normal arm64 Emitting\ module\ for\ GTMAppAuth (in target 'GTMAppAuth' from project 'GTMAppAuth')
    cd /Users/m.sorokin/ios-app-trading-1234/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/GTMAppAuth
    builtin-swiftTaskExecution -- /Applications/Xcode-15.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -emit-module -experimental-skip-non-inlinable-function-bodies-without-types /Users/m.sorokin/ios-app-trading-1234/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/GTMAppAuth/Derived/Sources/TuistBundle+GTMAppAuth.swift /Users/m.sorokin/ios-app-trading-1234/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/GTMAppAuth/GTMAppAuth/Sources/AuthSession.swift /Users/m.sorokin/ios-app-trading-1234/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/GTMAppAuth/GTMAppAuth/Sources/AuthSessionDelegate.swift /Users/m.sorokin/ios-app-trading-1234/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/GTMAppAuth/GTMAppAuth/Sources/AuthSessionStore.swift /Users/m.sorokin/ios-app-trading-1234/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/GTMAppAuth/GTMAppAuth/Sources/KeychainStore/GTMOAuth2Compatibility.swift /Users/m.sorokin/ios-app-trading-1234/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/GTMAppAuth/GTMAppAuth/Sources/KeychainStore/KeychainAttribute.swift /Users/m.sorokin/ios-app-trading-1234/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/GTMAppAuth/GTMAppAuth/Sources/KeychainStore/KeychainHelper.swift /Users/m.sorokin/ios-app-trading-1234/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/GTMAppAuth/GTMAppAuth/Sources/KeychainStore/KeychainStore.swift -target arm64-apple-ios15.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -stack-check -sdk /Applications/Xcode-15.0.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.0.sdk -I /Users/m.sorokin/Library/Developer/Xcode/DerivedData/FBS-chhvhwutxtcnzwdrdbbgpzyvggjz/Build/Products/Debug-iphoneos -F /Users/m.sorokin/Library/Developer/Xcode/DerivedData/FBS-chhvhwutxtcnzwdrdbbgpzyvggjz/Build/Products/Debug-iphoneos -F /Applications/Xcode-15.0.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks -no-color-diagnostics -suppress-warnings -enable-testing -g -module-cache-path /Users/m.sorokin/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity\=checked -Onone -D SWIFT_PACKAGE -D DEBUG -serialize-debugging-options -const-gather-protocols-file /Users/m.sorokin/Library/Developer/Xcode/DerivedData/FBS-chhvhwutxtcnzwdrdbbgpzyvggjz/Build/Intermediates.noindex/GTMAppAuth.build/Debug-iphoneos/GTMAppAuth.build/Objects-normal/arm64/GTMAppAuth_const_extract_protocols.json -enable-bare-slash-regex -empty-abi-descriptor -validate-clang-modules-once -clang-build-session-file /Users/m.sorokin/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -Xcc -working-directory -Xcc /Users/m.sorokin/ios-app-trading-1234/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/GTMAppAuth -resource-dir /Applications/Xcode-15.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -Xcc -fmodule-map-file\=/Users/m.sorokin/ios-app-trading-1234/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/GTMAppAuth/../AppAuth-iOS/Sources/AppAuthCore/AppAuthCore.modulemap -Xcc -fmodule-map-file\=/Users/m.sorokin/ios-app-trading-1234/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/GTMAppAuth/../gtm-session-fetcher/Sources/Core/Public/GTMSessionFetcherCore.modulemap -Xcc -ivfsstatcache -Xcc /Users/m.sorokin/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphoneos17.0-21A325-0c021f108d5741006311bd1f5257b6a2.sdkstatcache -Xcc -I/Users/m.sorokin/Library/Developer/Xcode/DerivedData/FBS-chhvhwutxtcnzwdrdbbgpzyvggjz/Build/Intermediates.noindex/GTMAppAuth.build/Debug-iphoneos/GTMAppAuth.build/swift-overrides.hmap -Xcc -I/Users/m.sorokin/Library/Developer/Xcode/DerivedData/FBS-chhvhwutxtcnzwdrdbbgpzyvggjz/Build/Products/Debug-iphoneos/include -Xcc -I/Users/m.sorokin/ios-app-trading-1234/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/AppAuth-iOS/Sources/AppAuthCore -Xcc -I/Users/m.sorokin/ios-app-trading-1234/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/gtm-session-fetcher/Sources/Core/Public -Xcc -I/Users/m.sorokin/Library/Developer/Xcode/DerivedData/FBS-chhvhwutxtcnzwdrdbbgpzyvggjz/Build/Intermediates.noindex/GTMAppAuth.build/Debug-iphoneos/GTMAppAuth.build/DerivedSources-normal/arm64 -Xcc -I/Users/m.sorokin/Library/Developer/Xcode/DerivedData/FBS-chhvhwutxtcnzwdrdbbgpzyvggjz/Build/Intermediates.noindex/GTMAppAuth.build/Debug-iphoneos/GTMAppAuth.build/DerivedSources/arm64 -Xcc -I/Users/m.sorokin/Library/Developer/Xcode/DerivedData/FBS-chhvhwutxtcnzwdrdbbgpzyvggjz/Build/Intermediates.noindex/GTMAppAuth.build/Debug-iphoneos/GTMAppAuth.build/DerivedSources -Xcc -DDEBUG\=1 -Xcc -DSWIFT_PACKAGE\=1 -module-name GTMAppAuth -disable-clang-spi -target-sdk-version 17.0 -target-sdk-name iphoneos17.0 -external-plugin-path /Applications/Xcode-15.0.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.0.sdk/usr/lib/swift/host/plugins\#/Applications/Xcode-15.0.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.0.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode-15.0.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.0.sdk/usr/local/lib/swift/host/plugins\#/Applications/Xcode-15.0.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.0.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode-15.0.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/lib/swift/host/plugins\#/Applications/Xcode-15.0.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode-15.0.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/local/lib/swift/host/plugins\#/Applications/Xcode-15.0.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/swift-plugin-server -plugin-path /Applications/Xcode-15.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Applications/Xcode-15.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/lib/swift/host/plugins -emit-module-doc-path /Users/m.sorokin/Library/Developer/Xcode/DerivedData/FBS-chhvhwutxtcnzwdrdbbgpzyvggjz/Build/Intermediates.noindex/GTMAppAuth.build/Debug-iphoneos/GTMAppAuth.build/Objects-normal/arm64/GTMAppAuth.swiftdoc -emit-module-source-info-path /Users/m.sorokin/Library/Developer/Xcode/DerivedData/FBS-chhvhwutxtcnzwdrdbbgpzyvggjz/Build/Intermediates.noindex/GTMAppAuth.build/Debug-iphoneos/GTMAppAuth.build/Objects-normal/arm64/GTMAppAuth.swiftsourceinfo -emit-objc-header-path /Users/m.sorokin/Library/Developer/Xcode/DerivedData/FBS-chhvhwutxtcnzwdrdbbgpzyvggjz/Build/Intermediates.noindex/GTMAppAuth.build/Debug-iphoneos/GTMAppAuth.build/Objects-normal/arm64/GTMAppAuth-Swift.h -serialize-diagnostics-path /Users/m.sorokin/Library/Developer/Xcode/DerivedData/FBS-chhvhwutxtcnzwdrdbbgpzyvggjz/Build/Intermediates.noindex/GTMAppAuth.build/Debug-iphoneos/GTMAppAuth.build/Objects-normal/arm64/GTMAppAuth-master-emit-module.dia -emit-dependencies-path /Users/m.sorokin/Library/Developer/Xcode/DerivedData/FBS-chhvhwutxtcnzwdrdbbgpzyvggjz/Build/Intermediates.noindex/GTMAppAuth.build/Debug-iphoneos/GTMAppAuth.build/Objects-normal/arm64/GTMAppAuth-master-emit-module.d -o /Users/m.sorokin/Library/Developer/Xcode/DerivedData/FBS-chhvhwutxtcnzwdrdbbgpzyvggjz/Build/Intermediates.noindex/GTMAppAuth.build/Debug-iphoneos/GTMAppAuth.build/Objects-normal/arm64/GTMAppAuth.swiftmodule -emit-abi-descriptor-path /Users/m.sorokin/Library/Developer/Xcode/DerivedData/FBS-chhvhwutxtcnzwdrdbbgpzyvggjz/Build/Intermediates.noindex/GTMAppAuth.build/Debug-iphoneos/GTMAppAuth.build/Objects-normal/arm64/GTMAppAuth.abi.json

/Users/m.sorokin/ios-app-trading-1234/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/GTMAppAuth/GTMAppAuth/Sources/AuthSession.swift:86:38: error: cannot find type 'OIDAuthState' in scope
  convenience public init(authState: OIDAuthState) {
                                     ^~~~~~~~~~~~
/Users/m.sorokin/ios-app-trading-1234/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/GTMAppAuth/GTMAppAuth/Sources/AuthSession.swift:106:16: error: cannot find type 'OIDAuthState' in scope
    authState: OIDAuthState,
               ^~~~~~~~~~~~
/Users/m.sorokin/ios-app-trading-1234/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/GTMAppAuth/GTMAppAuth/Sources/AuthSession.swift:37:31: error: cannot find type 'OIDAuthState' in scope
  @objc public let authState: OIDAuthState
                              ^~~~~~~~~~~~
/Users/m.sorokin/ios-app-trading-1234/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/GTMAppAuth/GTMAppAuth/Sources/AuthSession.swift:76:41: error: cannot find type 'GTMSessionFetcherServiceProtocol' in scope
  @objc public weak var fetcherService: GTMSessionFetcherServiceProtocol? = nil
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/m.sorokin/ios-app-trading-1234/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/GTMAppAuth/GTMAppAuth/Sources/AuthSession.swift:421:56: error: cannot find type 'OIDServiceConfiguration' in scope
  @objc public static func configurationForGoogle() -> OIDServiceConfiguration {
                                                       ^~~~~~~~~~~~~~~~~~~~~~~
/Users/m.sorokin/ios-app-trading-1234/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/GTMAppAuth/GTMAppAuth/Sources/AuthSession.swift:32:43: error: cannot find type 'GTMSessionFetcherAuthorizer' in scope
public final class AuthSession: NSObject, GTMSessionFetcherAuthorizer, NSSecureCoding {
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~

/Users/m.sorokin/ios-app-trading-1234/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/GTMAppAuth/GTMAppAuth/Sources/AuthSession.swift:86:38: Cannot find type 'OIDAuthState' in scope

/Users/m.sorokin/ios-app-trading-1234/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/GTMAppAuth/GTMAppAuth/Sources/AuthSession.swift:106:16: Cannot find type 'OIDAuthState' in scope

/Users/m.sorokin/ios-app-trading-1234/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/GTMAppAuth/GTMAppAuth/Sources/AuthSession.swift:37:31: Cannot find type 'OIDAuthState' in scope

/Users/m.sorokin/ios-app-trading-1234/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/GTMAppAuth/GTMAppAuth/Sources/AuthSession.swift:76:41: Cannot find type 'GTMSessionFetcherServiceProtocol' in scope

/Users/m.sorokin/ios-app-trading-1234/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/GTMAppAuth/GTMAppAuth/Sources/AuthSession.swift:421:56: Cannot find type 'OIDServiceConfiguration' in scope

/Users/m.sorokin/ios-app-trading-1234/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/GTMAppAuth/GTMAppAuth/Sources/AuthSession.swift:32:43: Cannot find type 'GTMSessionFetcherAuthorizer' in scope

### Firebase SDK Version

10.24.0

### Xcode Version

15.0.0

### Installation Method

Swift Package Manager

### Firebase Product(s)

AB Testing, Analytics, App Distribution, Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
There is nothing in this report related to Firebase.

It looks like something related to GTMAppAuth, GTMSessionFetcher and/or Tuist. I recommend further isolating the issue and following up on one of those support channels.
