### ISSUE TITLE
Firestore uses the File timestamp APIs but has not provided a reason in the privacy manifest.

### ISSUE THREAD

**Issue by edisonlin77** [firebase/firebase-ios-sdk#12803]
### Description

I found that Firestore uses the `stat` function in the File timestamp APIs, please add reason for use in privacy manifest.

### Firebase SDK Version

10.24.0

### Xcode Version

15.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment]
Hi @edisonlin77, Firestore does not directly use that API, but does depend on dependencies that do. Those dependencies have privacy manifests to justify the usage of the API, but the privacy manifests are not being evaluated by the App Store Connect validator. Let's continue the conversation in #12557.
