### ISSUE TITLE
Privacy Manifest for GoogleAppMeasurementOnDeviceConversion required reasons use

### ISSUE THREAD

**Issue by sarodger** [firebase/firebase-ios-sdk#12804]
### Description

Hi, we have noticed that **GoogleAppMeasurementOnDeviceConversion** does not yet contain a privacy manifest file. However we can see that it is calling lstat & stat which requires a reason to be declared against it (specifically for NSPrivacyAccessedAPICategoryFileTimestamp) and will block our app submissions post May 1st as per Apple's latest privacy manifest requirements.

Can this be added ASAP? Alternatively can you provide the reason now so that we can add this to our own privacy manifest file?

NSPrivacyAccessedAPICategoryFileTimestamp
lstat
stat

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

### Reproducing the issue

Submission to the App Store flags warning for NSPrivacyAccessedAPICategoryFileTimestamp

### Firebase SDK Version

10.22.0

### Xcode Version

15.0.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @sarodger, this seems related to #12684. With this, you may try updating your SDK to v10.24.0. I'll now be closing this ticket but feel free to comment if you still encounter any issues. Thanks.
