### ISSUE TITLE
SDK Error - 10.24.0 -  Fetching newest settings failed with error: InstallationIDError - FirebaseSessionsError - 3

### ISSUE THREAD

**Issue by thereallee** [firebase/firebase-ios-sdk#12809]
### Description

I'm troubleshooting why I'm not seeing realtime Remote Config updates and noticed this log:

10.24.0 - [FirebaseSessions][I-SES000000] [Settings] Fetching newest settings failed with error: InstallationIDError("The operation couldn’t be completed. (FirebaseSessions.FirebaseSessionsError error 3.)")

When continuing to investigate, I see that in this callback 

 `remoteConfig.fetchAndActivate { status, error in ...`

these values:  

error is `nil` and status is `successFetchedFromRemote`

Realtime updates were working earlier this week.

### Reproducing the issue

It's reproducible 100% of the time by restarting the app which does these init-y things (relevant code only):

`var remoteConfig = RemoteConfig.remoteConfig()`
        
`remoteConfig.setDefaults(fromPlist: "RemoteConfigDefaults")`
        
`        DispatchQueue.global(qos: .utility).async { `       
`            self.remoteConfig.fetchAndActivate { status, error in`

...

`            }`
            
`            self.remoteConfig.addOnConfigUpdateListener { [weak self] configUpdate, error in`

...

`            }`

The error log is consistently written after this code executes.

### Firebase SDK Version

10.24.0

### Xcode Version

15.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, App Check, Crashlytics, Database, Remote Config

### Targeted Platforms

iOS

### Relevant Log Output

```shell
2024-04-17 17:31:16.601664-0500 ..... 10.24.0 - [FirebaseSessions][I-SES000000] [Settings] Fetching newest settings failed with error: InstallationIDError("The operation couldn’t be completed. (FirebaseSessions.FirebaseSessionsError error 3.)")


This is the only firebase session log.

It was also happening in 10.23.1.
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

{
  "originHash" : "c67ad1ad9417546e3b22eba8143e3ab5544df617a0aa1a63e577e428242b11b7",
  "pins" : [
    {
      "identity" : "abseil-cpp-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/abseil-cpp-binary.git",
      "state" : {
        "revision" : "748c7837511d0e6a507737353af268484e1745e2",
        "version" : "1.2024011601.1"
      }
    },
    {
      "identity" : "anytask",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/KaneCheshire/AnyTask",
      "state" : {
        "revision" : "b6a9da80164ccab46640e36857b205c59478a613",
        "version" : "1.0.0"
      }
    },
    {
      "identity" : "app-check",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/app-check.git",
      "state" : {
        "revision" : "7d2688de038d5484866d835acb47b379722d610e",
        "version" : "10.19.0"
      }
    },
    {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk",
      "state" : {
        "revision" : "42eae77a0af79e9c3f41df04a23c76f05cfdda77",
        "version" : "10.24.0"
      }
    },
    {
      "identity" : "googleappmeasurement",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleAppMeasurement.git",
      "state" : {
        "revision" : "51ba746a9d51a4bd0774b68499b0c73ef6e8570d",
        "version" : "10.24.0"
      }
    },
    {
      "identity" : "googledatatransport",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleDataTransport.git",
      "state" : {
        "revision" : "a637d318ae7ae246b02d7305121275bc75ed5565",
        "version" : "9.4.0"
      }
    },
    {
      "identity" : "googleutilities",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleUtilities.git",
      "state" : {
        "revision" : "26c898aed8bed13b8a63057ee26500abbbcb8d55",
        "version" : "7.13.1"
      }
    },
    {
      "identity" : "grpc-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/grpc-binary.git",
      "state" : {
        "revision" : "e9fad491d0673bdda7063a0341fb6b47a30c5359",
        "version" : "1.62.2"
      }
    },
    {
      "identity" : "gtm-session-fetcher",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/gtm-session-fetcher.git",
      "state" : {
        "revision" : "bc8972686f8797713af26b8eb24e85e2a6b972a3",
        "version" : "3.4.0"
      }
    },
    {
      "identity" : "interop-ios-for-google-sdks",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/interop-ios-for-google-sdks.git",
      "state" : {
        "revision" : "2d12673670417654f08f5f90fdd62926dc3a2648",
        "version" : "100.0.0"
      }
    },
    {
      "identity" : "leveldb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/leveldb.git",
      "state" : {
        "revision" : "a0bc79961d7be727d258d33d5a6b2f1023270ba1",
        "version" : "1.22.5"
      }
    },
    {
      "identity" : "nanopb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/nanopb.git",
      "state" : {
        "revision" : "b7e1104502eca3a213b46303391ca4d3bc8ddec1",
        "version" : "2.30910.0"
      }
    },
    {
      "identity" : "promises",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/promises.git",
      "state" : {
        "revision" : "540318ecedd63d883069ae7f1ed811a2df00b6ac",
        "version" : "2.4.0"
      }
    },
    {
      "identity" : "purchases-ios",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/RevenueCat/purchases-ios.git",
      "state" : {
        "revision" : "3ad7fab62d44dd7053d6531d5b0bc90e0e4724a7",
        "version" : "4.18.0"
      }
    },
    {
      "identity" : "swift-package-manager-google-mobile-ads",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/googleads/swift-package-manager-google-mobile-ads.git",
      "state" : {
        "revision" : "9ab66e38f5f0c2d02f2b024b1babd880130f19bf",
        "version" : "11.3.0"
      }
    },
    {
      "identity" : "swift-package-manager-google-user-messaging-platform",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/googleads/swift-package-manager-google-user-messaging-platform.git",
      "state" : {
        "revision" : "cfe8b2ae16b9bc81f4cdf1d1a12a01a452489c32",
        "version" : "2.3.0"
      }
    },
    {
      "identity" : "swift-protobuf",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-protobuf.git",
      "state" : {
        "revision" : "9f0c76544701845ad98716f3f6a774a892152bcb",
        "version" : "1.26.0"
      }
    }
  ],
  "version" : 3
}

```

</details>

**Comment by paulb777** [comment]
@rizafran Are you able to reproduce?

**Comment by rizafran** [comment]
@paulb777, I'm unable to reproduce the issue using v10.24.0.

**Comment by ncooke3** [comment]
That [error](https://github.com/firebase/firebase-ios-sdk/blob/020264b84212d20cdb44c0485e4b86db867dbf33/FirebaseSessions/Sources/FirebaseSessionsError.swift#L24C7-L24C40) code indicates the Installations token request timed out. @thereallee, is it possible there were network issues when the problem first appeared?

**Comment by thereallee** [comment]
I can’t say with certainty as I wasn’t looking for it specifically. This happened on device and simulator. And while troubleshooting I was searching around the web for resolution ideas. That leads me to believe network wasn’t an issue. 

That being said… how does one detect and recover  from this programmatically?

**Comment by ncooke3** [comment]
> That being said… how does one detect and recover from this programmatically?

Based on how the error is bubbling up to the Remote Config method call, there may not be a way to recover.

@thereallee, are you still reliably reproduce it? Could you try reproducing with the thread sanitizer on? See https://developer.apple.com/documentation/xcode/diagnosing-memory-thread-and-crash-issues-early for profiling tips.

**Comment by thereallee** [comment]
Thanks.  I can't repro it today at all.  Seems it was transient.

It would be nice to have a means to retry or recover programmatically.  FWIW I came to know about the issue when a tester noticed that a feature I had behind a flag wasn't working.  After digging in, I saw realtime wasn't firing client side which lead me to find this log entry and eventually create this issue.

**Comment by paulb777** [comment]
Thanks for letting us know. I'll close for now, but happy to reopen if it reoccurs.
