### ISSUE TITLE
‘FIRAnalytics+AppDelegate.h' is beyond a symbolic link (from Cocoapods in ver10.24.0) 

### ISSUE THREAD

**Issue by mushyoom** [firebase/firebase-ios-sdk#12801]
### Description

Hi,

 I am unable to push the updated frameworks to Git after updating Firebase SDK from version 10.22.0 to 10.24.0 using Cocoapods. 
There were no issues with version 10.22.0. 

The error message is as follows:
> error: 'Pods/FirebaseAnalytics/Frameworks/FirebaseAnalytics.xcframework/ios-arm64_x86_64-maccatalyst/FirebaseAnalytics.framework/Headers/FIRAnalytics+AppDelegate.h' is beyond a symbolic link
> fatal: Unable to process path Pods/FirebaseAnalytics/Frameworks/FirebaseAnalytics.xcframework/ios-arm64_x86_64-maccatalyst/FirebaseAnalytics.framework/Headers/FIRAnalytics+AppDelegate.h

<img width="1726" alt="スクリーンショット 2024-04-17 15 32 13" src="https://github.com/firebase/firebase-ios-sdk/assets/39396370/9b7d6b74-830c-4ae9-ae8b-372ff4a7c339">

the same error I found in other issues:
https://github.com/firebase/firebase-ios-sdk/issues/12668#issuecomment-2031579447
https://github.com/firebase/firebase-ios-sdk/issues/12668#issuecomment-2046712364

Is any solution to avoid it ?

### Reproducing the issue

1. Modify the Podfile by changing the version from 10.22.0 to 10.24.0 as follows::
<img width="748" alt="スクリーンショット 2024-04-17 15 38 56" src="https://github.com/firebase/firebase-ios-sdk/assets/39396370/3a614c93-4116-4b4a-9e2d-facccae5efb7">

2. Execute the command :
`pod install`

3. Build the app to confirm that there are no build problems 
4. Commit the code. <---error is here. 

### Firebase SDK Version

10.24.0

### Xcode Version

15.0

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
Xcode 15.3 started requiring symlinks in frameworks and Firebase updated accordingly. More context at #12505 and #12587

It looks like however you're using git needs to be updated to handle symlinks. See https://stackoverflow.com/q/14783847/556617 and https://stackoverflow.com/a/18791647/556617.

If you're still stuck and can reproduce in the git command line, we can take a deeper look.

**Comment by mushyoom** [comment]
@paulb777 
Thank you for your response. 
I referred to the link you provided (https://stackoverflow.com/questions/14783847/git-file-is-beyond-a-symbolic-link) and resolved the error. （just execute "git add ." before commit it in github GUI）
It's kind of you.

**Comment by iOSDev33** [comment]
I first started seeing this issue with version 10.23 ( I am currently using 10.25) using sourcetree to stage the files. I opened the project in terminal and ran "git add ." and that fixed the issue for me. It maybe an issue with sourcetree.

**Comment by enriqueg** [comment]
Same here: Error: 'Pods/FirebaseAnalytics/Frameworks/FirebaseAnalytics.xcframework/ios-arm64_x86_64-maccatalyst/FirebaseAnalytics.framework/Headers/FIRAnalytics+AppDelegate.h' is beyond a symbolic link
fatal: Unable to process path Pods/FirebaseAnalytics/Frameworks/FirebaseAnalytics.xcframework/ios-arm64_x86_64-maccatalyst/FirebaseAnalytics.framework/Headers/FIRAnalytics+AppDelegate.h
