### ISSUE TITLE
[FR]: Add Apple privacy manifest for FirebaseAppCheck

### ISSUE THREAD

**Issue by skyfoxa** [firebase/firebase-ios-sdk#12802]
### Description

FirebaseAppCheck uses UserDefaults, it has to contain PrivacyInfo manifest, check [Apple doc](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278401)

### API Proposal

Add Privacy manifest supporting UserDefaults privacy reason type, https://developer.apple.com/support/third-party-SDK-requirements/

### Firebase Product(s)

App Check

**Comment by paulb777** [comment]
This was addressed by #12773 that removed UserDefaults usage from AppCheck. It will be released in the next Firebase release due out the week of April 29th.
