### ISSUE TITLE
Firebase-related Required Reason API warning email (ITMS-91053: Missing API declaration)

### ISSUE THREAD

**Issue by bforrose** [firebase/firebase-ios-sdk#12811]
### Description

I've confirmed that the location of the Firebase SDK's `.xcprivacy` file is as follows:
`.xcframework/ios-arm64/.framework/.bundle/.xcprivacy`

Additionally, I found that it's necessary to add the Firebase's `.bundle` with Embed & Sign to include it. However, when we add the Firebase SDK to our sample app and upload it to the AppStore Review, we receive a warning email(_ITMS-91053: Missing API declaration_) from AppStore Review. When uploading to the AppStore Review in various ways, we came to the following conclusion.

1. Dynamic Framework + Embed & Sign
: No warning email from the AppStore Review regarding the Required Reason API defined in `.xcframework/ios-arm64/.framework/.xcprivacy` or `.xcframework/ios-arm64/.framework/.bundle/.xcprivacy`.

2. Static Framework + Embed & Sign
: A warning email(_ITMS-91053: Missing API declaration_) from the AppStore Review about the Required Reason API defined in `.xcframework/ios-arm64/.framework/.xcprivacy` or `.xcframework/ios-arm64/.framework/.bundle/.xcprivacy`.
: Adding `.xcprivacy` to the app's main target(`Sample.app/.xcprivacy`) prevents the warning email from the AppStore Review regarding the Required Reason API.

It seems that the definition of `.bundle/.xcprivacy` does not work because the current Firebase SDK is a Static XCFramework. Should we merge the xcprivacy content defined in Firebase into the main target(`Sample.app/.xcprivacy`)?
Please confirm.

### Firebase SDK Version

10.24.0

### Xcode Version

15.1

### Installation Method

Zip

### Firebase Product(s)

Analytics, Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
See https://github.com/firebase/firebase-ios-sdk/issues/12557#issuecomment-2057319060

**Comment by paulb777** [comment]
Closing in favor of #12557. Updating the app-level privacy manifest may be a workaround, but the ultimate fix will need to come from App Store Connect.
