### ISSUE TITLE
Firebase Storage Upload/Download Failures

### ISSUE THREAD

**Issue by KunalxBhandari** [firebase/firebase-ios-sdk#12812]
### Description

I'm using firebase storage in order to upload some files and download those files later. I'm using the code down below in order to download the files from firebase storage.

func downloadFileFromFirebase(fireBasePath: String, localURL: String) {
  let fireBaseStorage =  Storage.storage().reference()
  let storeRef =  fireBaseStorage.child("\(String(describing: fireBasePath))")
  let downloadTask = storeRef.write(toFile: localURL)
		
  downloadTask.observe(.progress) { snapshot in
    // Updating the progress bar 
  }

  downloadTask.observe(.success) { snapshot in
    //Updating the UI
  }
}

Here, what I noticed is that my downloadTask.observe closures are not invoking and I did some digging in the framework and found out that my task is never enqueued and the StorageDownloadTask is deallocated before that.

<img width="988" alt="Screenshot 2024-04-18 at 2 28 45 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/78612606/cdf61e69-f80b-4e92-9276-e35c8fe64ff1">

Line 110 is never executed.

<img width="984" alt="Screenshot 2024-04-18 at 2 33 44 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/78612606/40cf4457-1d21-4865-9b2f-e9c94931e50f">

Here in StorageReference on Line 204 we are creating a strong reference cycle with StorageDownloadTask but still it is deallocating before the enqueue implementation I don't know why. So, in order to confirm that issue is happening due to this deallocation reason, I deliberately created a retain cycle in StorageReference and made sure that the StorageDownloadTask is not deallocated.

<img width="989" alt="Screenshot 2024-04-18 at 2 40 37 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/78612606/2950acbe-abac-4f32-92d4-d9cdd17659ff">

<img width="987" alt="Screenshot 2024-04-18 at 2 41 23 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/78612606/c558c1fb-b48d-4537-bd78-20a6ec7281f4">

And after creating this retain cycle my downloadTask.observe closures are invoking and I'm able to download the media from firebase storage. But this is not a solution to the problem as it will create retain cycle. Can somebody help with this problem and tell me why this is happening?

This problem started coming after 10.2.0 versions. Currently, I'm using the 10.24.0 version.

### Firebase SDK Version

10.24.0

### Xcode Version

15.3

### Installation Method

CocoaPods

### Firebase Product(s)

Storage

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
Sorry about the trouble @KunalxBhandari. I'm not able to reproduce. The only possible impacting change since 10.2.0 I see is https://github.com/firebase/firebase-ios-sdk/pull/10492 and I'm not sure why that would matter.

I'm not sure how the task could be deallocated between the `StorageDownloadTask` init and the `task.enqueue()` call.

Does adding a wait or sleep to the bottom of `downloadFileFromFirebase` make a difference?

 Are you able to share a sample app that reproduces the issue?

**Comment by KunalxBhandari** [comment]
@paulb777 I'm using putData, delete, putFile, getMetadata, downloadURL functions of Storage and all of these are working fine expect the write function which I'm using for downloading the file from firebase storage. But on using sleep it's working fine. Is there any particular reason why this function is behaving like this?

**Comment by klinkert0728** [comment]
Hello, I'm facing a similar issue, where the `downloadProgressBlock` never gets called
line `134` never gets executed.

![Screenshot 2024-04-29 at 17 04 34](https://github.com/firebase/firebase-ios-sdk/assets/6820828/64f8189d-c599-4133-89e0-13857161b3bb)

Any idea what could cause this ?

**Comment by klinkert0728** [comment]
nor the `fetcherCompletion` 
![Screenshot 2024-04-29 at 17 48 53](https://github.com/firebase/firebase-ios-sdk/assets/6820828/3d837517-21f3-4bd8-8021-9d517c1dfaa5)

**Comment by paulb777** [comment]
Does the app finish before the `write` completes?

**Comment by KunalxBhandari** [comment]
I used the Thread.sleep(0.1) before my function body ends and now code is working fine. But like I explained, I was not getting the callback because the firebase object was deallocating. I don't know why that was happening but for now thread sleep seems to have worked for me.

**Comment by paulb777** [comment]
I'm still not able to reproduce. When I add the code above into an app, I see the breakpoint in `enqueueImplementation` hit before the deallocation.

Would you share a fully reproducible example?

**Comment by klinkert0728** [comment]
I would love to but unfortunately I can't.
