### ISSUE TITLE
An unknown error occurred. http parser error: stream ended at an unexpected time (-1)

### ISSUE THREAD

**Issue by denysooz** [firebase/firebase-ios-sdk#12828]
### Description

I want to install firebase into my project and i have that error:

Showing Recent Errors Only
github.com: https://github.com/firebase/firebase-ios-sdk: An unknown error occurred. http parser error: stream ended at an unexpected time (-1)

### Reproducing the issue

File -> Add package dependencies... -> https://github.com/firebase/firebase-ios-sdk 
That's it

<img width="652" alt="Screenshot 2024-04-22 at 09 53 08" src="https://github.com/firebase/firebase-ios-sdk/assets/155985909/13977ece-fb5f-4437-99ed-0c1f3eaaeaa2">

And than in project i have this

<img width="1107" alt="Screenshot 2024-04-22 at 14 22 09" src="https://github.com/firebase/firebase-ios-sdk/assets/155985909/667c9f71-31e8-428d-884e-1323212cda93">

Tried to reinstall Xcode and that instructions:

Close XCode. rm -rfv ~/Library/Caches/org.swift.swiftpm/ and rm -rfv ~/Library/Developer/Xcode/DerivedData and rm -rfv <Project Path>/DerivedData

Nothing happend

### Firebase SDK Version

10.9 , 10.24

### Xcode Version

15.3 , 15.4 beta

### Installation Method

Swift Package Manager

### Firebase Product(s)

All

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Showing Recent Errors Only
github.com: https://github.com/firebase/firebase-ios-sdk: An unknown error occurred. http parser error: stream ended at an unexpected time (-1)
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
This is likely a network configuration issue. See https://forums.developer.apple.com/forums/thread/123380

**Comment by denysooz** [comment]
Thank you for answer <3

I didn't do any of the instructions described
After a day of downtime XCode solved the problem by itself)
