### ISSUE TITLE
Signature cannot be verified

### ISSUE THREAD

**Issue by adsantos** [firebase/firebase-ios-sdk#12838]
### Description

I updated to Firebase 10.24.0 and consequently updated GoogleDataTransport, GoogleUtilities and nanopb using the xcframeworks you provide. For these three frameworks, I got an error saying that the signature cannot be verified, so the project doesn't build. Could you please check if this is an issue on your side?
<img width="396" alt="Screenshot 2024-04-23 at 12 38 39" src="https://github.com/firebase/firebase-ios-sdk/assets/705513/deba95a9-c427-42a4-a472-88419ccb62a9">

### Firebase SDK Version

10.24.0

### Xcode Version

15.0

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
This may be related to #12740. Please take a look.

Also, please clarify the information in the issue template. The Swift Package Manager distribution distributes those three packages as source, not as xcframeworks.

**Comment by adsantos** [comment]
I used `cp -rfP` as suggested in [#12740](https://github.com/firebase/firebase-ios-sdk/issues/12740).
Instead of three frameworks having a signature that cannot be verified, now it's only one: `nanopb.xcframework`. Is there anything else I could try?
My flow was to download the `xcframeworks` from https://github.com/firebase/firebase-ios-sdk/releases/tag/10.24.0
Then I added them into our internal SPM.

**Comment by adsantos** [comment]
<img width="330" alt="Screenshot 2024-04-25 at 17 13 00" src="https://github.com/firebase/firebase-ios-sdk/assets/705513/0b8c7a99-8fad-45f5-b9d8-fcc22432b903">
Here is a screenshot of the framework added to the project, which isn't working.

**Comment by ncooke3** [comment]
If the new version frameworks are being placed at the same path of where the old version frameworks, I believe this might happen. Xcode must have some cache and may be thinking that the old version's signature has been compromised when the new version is copied.

I would recommend doing a fresh install (remove the dependency from the app target), delete derived data, and try re-adding the dependencies.

**Comment by adsantos** [comment]
@ncooke3 I tried that, but I continue having the same error. I also tried with a different simulator and deleted any old version of the app from the simulator.
Besides deleting derived data, can you think of anything else I might need to delete to make sure I'm in a clean state?

**Comment by ncooke3** [comment]
@adsantos, there are some SPM caches they may also need to be cleared. Take a look at this answer: https://stackoverflow.com/a/72838880/9331576

**Comment by olejnjak** [comment]
Well Carthage distribution suffers this issue as well, but not sure those solutions are actually applicable 🤔

**Comment by ncooke3** [comment]
@olejnjak, are the solutions in https://github.com/firebase/firebase-ios-sdk/issues/12740 helpful?

**Comment by olejnjak** [comment]
As I am thinking a bit more about it, it might be connected to our caching tool, that zips and unzips the framework. I will eventually report back if I found other problems.

**Comment by adsantos** [comment]
@ncooke3 I deleted the SPM caches, derived data, I renamed the dependency in Package.swift and I added another framework just to make the structure change. Nothing seems to work. I managed to update FirebaseAnalytics, FriebaseCrashlytics, FirebaseMessaging and FirebasePerformance. However, GoogleSignIn is always giving the 'signature not verified' error.
If I add the frameworks directly into the project, then the signatures are valid, but not when I add them via SPM.
I'm running out of ideas. Does anyone have any more suggestions?

**Comment by adsantos** [comment]
These are the frameworks I deleted:
```
rm -r FBLPromises.xcframework
rm -r FirebaseABTesting.xcframework
rm -r FirebaseAnalytics.xcframework
rm -r FirebaseCore.xcframework
rm -r FirebaseCoreExtension.xcframework
rm -r FirebaseCoreInternal.xcframework
rm -r FirebaseCrashlytics.xcframework
rm -r FirebaseInstallations.xcframework
rm -r FirebaseMessaging.xcframework
rm -r FirebasePerformance.xcframework
rm -r FirebaseRemoteConfig.xcframework
rm -r FirebaseRemoteConfigInterop.xcframework
rm -r FirebaseSessions.xcframework
rm -r FirebaseSharedSwift.xcframework
rm -r GoogleAppMeasurement.xcframework
rm -r GoogleAppMeasurementIdentitySupport.xcframework
rm -r GoogleDataTransport.xcframework
rm -r GoogleUtilities.xcframework
rm -r GTMAppAuth.xcframework
rm -r GTMSessionFetcher.xcframework
rm -r nanopb.xcframework
rm -r Promises.xcframework
```

I then added them in two ways, but none of them worked: `rsync -a` and `cp -rfP`.

**Comment by paulb777** [comment]
We don't support a mix of the binary distribution and SPM, so will likely need a fully reproducible example to help.

**Comment by suganrajs** [comment]
We are using Azure Artiacts to upload .xcfrmawork and have scripts to download into code base. When trying to upgrade firebase analytics to 10.25.0 getting the same error. Did you find any solution  @adsantos  ?

**Comment by ncooke3** [comment]
One tip may be to ensure that the XCFrameworks don't contain a `.DS_Store` file. The file will sometimes appear when manually/programmatically opening the XCFrameworks. If any file is added/changed/deleted, the signature will break.

**Comment by adsantos** [comment]
@suganrajs yes. In our case, we were using Artifactory. For some reason, pulling from Artifactory was causing issues with the signature. Instead, we are now pulling directly from our internal github and everything works fine.
We didn't look into how to make it work via Artifactory yet.
