### ISSUE TITLE
After upgrading from version 10.3.0 to 10.24.0, crash logs could not be uploaded unless a VPN was enabled on the mobile network, which then allowed the Firebase backend to retrieve the crash logs. The older version 10.3.0 did not require a VPN for this purpose.

### ISSUE THREAD

**Issue by qianlifei** [firebase/firebase-ios-sdk#12850]
### Description

we have only utilized two features of Firebase: FirebaseCrashlytics and FirebaseAnalytics. After updating the Firebase version from the old version 10.3.0 to a version greater than or equal to 10.23.0, we found that the crash logs could not be uploaded to the Firebase backend and could not be retrieved from there. However, the analytics statistics for daily active users were still accessible. After several rounds of verification, it was determined that a VPN must be enabled on the phone in order to facilitate the upload, and only then could the crash logs be queried in the Firebase backend.

It's worth noting that before the upgrade, we were using the old version 10.3.0, which did not require the phone to have a VPN enabled. The crash logs were being properly collected and the Firebase backend was able to display them normally.

### Firebase SDK Version

10.24.0

### Xcode Version

15.3

### Installation Method

Zip

### Firebase Product(s)

Analytics, Crashlytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
10.24.0 - [FirebaseSessions][I-SES000000] [Settings] Fetching newest settings failed with error: InstallationIDError("未能完成操作。（FirebaseSessions.FirebaseSessionsError错误3。）")
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!
11
```

</details>

**Comment by rizafran** [comment]
Thanks for reporting, @qianlifei. Do you have a complete error logs when trying to use v10.24.0 without VPN?

**Comment by qianlifei** [comment]
> Thanks for reporting, @qianlifei. Do you have a complete error logs when trying to use v10.24.0 without VPN?
Yes, I have exported all the Firebase logs and placed them in the attached txt file, please check it out.
[firebase complete error logs.txt](https://github.com/firebase/firebase-ios-sdk/files/15124274/firebase.complete.error.logs.txt)
