### ISSUE TITLE
[FR]: Add @objc support to FirebaseMLModelDownloader

### ISSUE THREAD

**Issue by jordond** [firebase/firebase-ios-sdk#12852]
### Description

I am attempting to add `FirebaseMLModelDownloader` to my Kotlin Multiplatform project. But Kotlin Multiplatform doesn't support pure Swift modules yet and requires being exporting to objective-c, see [here](https://kotlinlang.org/docs/native-objc-interop.html#usage)

### Firebase Product(s)

ML Model Downloader

**Comment by paulb777** [comment]
Thanks for the request.

Sorry, while we have no plans to remove existing Objective-C APIs, we don't plan to add any additional ones. The future is Swift.
