### ISSUE TITLE
Undefined symbols FirebaseAnalytics 10.24.0

### ISSUE THREAD

**Issue by Minhvv94** [firebase/firebase-ios-sdk#12854]
### Description

ld: warning: Could not find or use auto-linked library 'swiftCompatibility50': library 'swiftCompatibility50' not found
ld: warning: Could not find or use auto-linked library 'swiftCompatibility51': library 'swiftCompatibility51' not found
ld: warning: Could not find or use auto-linked library 'swiftCompatibility56': library 'swiftCompatibility56' not found
ld: warning: Could not find or use auto-linked library 'swiftCompatibilityConcurrency': library 'swiftCompatibilityConcurrency' not found
ld: warning: Could not find or use auto-linked library 'swiftCompatibilityDynamicReplacements': library 'swiftCompatibilityDynamicReplacements' not found
ld: warning: Could not find or use auto-linked library 'swiftCompatibilityPacks': library 'swiftCompatibilityPacks' not found
ld: Undefined symbols:
  __swift_FORCE_LOAD_$_swiftCompatibility50, referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_FirebaseAnalytics in FirebaseAnalytics[17](Analytics+StoreKit.o)
  __swift_FORCE_LOAD_$_swiftCompatibility51, referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_FirebaseAnalytics in FirebaseAnalytics[17](Analytics+StoreKit.o)
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_FirebaseCoreInternal in FirebaseCoreInternal[4](_ObjC_HeartbeatController.o)
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_RxSwift in RxSwift[4](AddRef.o)
  __swift_FORCE_LOAD_$_swiftCompatibility56, referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_FirebaseCoreInternal in FirebaseCoreInternal[4](_ObjC_HeartbeatController.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_RxSwift in RxSwift[4](AddRef.o)
  __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency, referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseAnalytics in FirebaseAnalytics[17](Analytics+StoreKit.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseCoreInternal in FirebaseCoreInternal[4](_ObjC_HeartbeatController.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_RxSwift in RxSwift[4](AddRef.o)
  __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements, referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_FirebaseAnalytics in FirebaseAnalytics[17](Analytics+StoreKit.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Firebase SDK Version

10.24.0

### Xcode Version

15.3

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
ld: warning: Could not find or use auto-linked library 'swiftCompatibility50': library 'swiftCompatibility50' not found
ld: warning: Could not find or use auto-linked library 'swiftCompatibility51': library 'swiftCompatibility51' not found
ld: warning: Could not find or use auto-linked library 'swiftCompatibility56': library 'swiftCompatibility56' not found
ld: warning: Could not find or use auto-linked library 'swiftCompatibilityConcurrency': library 'swiftCompatibilityConcurrency' not found
ld: warning: Could not find or use auto-linked library 'swiftCompatibilityDynamicReplacements': library 'swiftCompatibilityDynamicReplacements' not found
ld: warning: Could not find or use auto-linked library 'swiftCompatibilityPacks': library 'swiftCompatibilityPacks' not found
ld: Undefined symbols:
  __swift_FORCE_LOAD_$_swiftCompatibility50, referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_FirebaseAnalytics in FirebaseAnalytics[17](Analytics+StoreKit.o)
  __swift_FORCE_LOAD_$_swiftCompatibility51, referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_FirebaseAnalytics in FirebaseAnalytics[17](Analytics+StoreKit.o)
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_FirebaseCoreInternal in FirebaseCoreInternal[4](_ObjC_HeartbeatController.o)
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_RxSwift in RxSwift[4](AddRef.o)
  __swift_FORCE_LOAD_$_swiftCompatibility56, referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_FirebaseCoreInternal in FirebaseCoreInternal[4](_ObjC_HeartbeatController.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_RxSwift in RxSwift[4](AddRef.o)
  __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency, referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseAnalytics in FirebaseAnalytics[17](Analytics+StoreKit.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseCoreInternal in FirebaseCoreInternal[4](_ObjC_HeartbeatController.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_RxSwift in RxSwift[4](AddRef.o)
  __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements, referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_FirebaseAnalytics in FirebaseAnalytics[17](Analytics+StoreKit.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by saadzarif** [comment]
I also have the same issue. And the part that pains me is that, it works in one project completely fine. But not in another project. I tried making a fully new project and it didn't work there too.
And I had the same version in all of them, but the project it was working on, would install version 10.20.0 for all the firebase pods. While the project it didn't work on, woudl install version 10.25.0 and the Analytics folder was looking different too.
I copied it from the working project to the not working project and it worked. And it frustrates me to not know the reason behind all this.
