### ISSUE TITLE
Firestore: setting `includeMetadataChanges = true` does not result in receiving `isFromCache = false` after first run.

### ISSUE THREAD

**Issue by TarekkMA** [firebase/firebase-ios-sdk#12869]
### Description

When querying documents using the options:
 *  `source` set to `FIRListenSourceDefault`
 *  `includeMetadataChanges` set to `true`\
  
The expected behavior is to receive two results. The first result should have `isFromCache` marked as `YES`, and the second should have `isFromCache` marked as `NO`. _However, the actual behavior observed is that only one result is returned with `isFromCache` marked as `NO`._

**Reference:**
- Original issue reported here: [Issue #12722 on GitHub](https://github.com/firebase/flutterfire/issues/12722)

### Reproducing the issue

1. Set up a document query with `source` as `FIRListenSourceDefault`.
2. Enable `includeMetadataChanges`.
3. Observe the results.

### Firebase SDK Version

10.24.0

### Xcode Version

15.3

### Installation Method

CocoaPods

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by milaGGL** [comment]
Hi @TarekkMA, thank you for reporting this issue. `includeMetadataChanges` is working as expected in my local test environment. Would it be possible to provide a minimal reproduction app?

**Comment by ramsayamarin** [comment]
@milaGGL It works as expected when listening to a query the first time, but if you recreate the query or restart the app on the same exact data, it will not work as expected; it will return the cached data and never isFromCache == false until the data is updated again or the app storage cleared. This issue only happened after I updated to the latest version.

**Comment by milaGGL** [comment]
I have tested the below:
1. create a snapshot listener -> receives 2 snapshots where `isFromCache=true`, and then `isFromCache=false`
2. attach a second snapshot listener -> receives only 1 snapshot where  `isFromCache=false` as expected.

1. create a snapshot listener -> receives 2 snapshots where `isFromCache=true`, and then `isFromCache=false`
2. remove the snapshot listener
3. re-create a snapshot listener -> receives 2 snapshots where `isFromCache=true`, and then `isFromCache=false` 

Both of them are working as expected in the SDK tests. Could you please provide a repro app?

**Comment by ramsayamarin** [comment]
@milaGGL Are you using the latest version of cloud firestore (4.17.2) on a device? The query has to be on the same exact data @TarekkMA seems to have successfully recreated the bug, I hope he can post it here. Otherwise I can try recreating it in a new project tomorrow.

**Comment by milaGGL** [comment]
I am testing it on firebase-ios-sdk v10.25.0 on iOS simulator.

**Comment by ramsayamarin** [comment]
@milaGGL I have never ran my projects on the iOS simulator therefore this might be the issue. As for the SDK version you are using, I do not know which iOS SDK version cloud firestore (4.17.2) internally uses so this might be another cause why the error is not reproducing on your side.

**Comment by milaGGL** [comment]
The most recent change to snapshot listener is introduced in ios sdk v10.23.0, which maps to cloud_firestore 4.17.0. 

Could you please provide a repro app on native iOS, not flutter, to narrow down the bug into the firebase-ios-sdk?

**Comment by milaGGL** [comment]
@TarekkMA, i am trying to reproduce the error on xcode. Meanwhile, could you please update the `ViewController.m` file line 38 to use the `optionsWithSourceAndMetadata` instead of `options` and try again?

**Comment by milaGGL** [comment]
> Test1
> 1. create a snapshot listener -> receives 2 snapshots where `isFromCache=true`, and then `isFromCache=false`
> 2. attach a second snapshot listener -> receives only 1 snapshot where  `isFromCache=false` as expected.
> 
> Test 2:
> 1. create a snapshot listener -> receives 2 snapshots where `isFromCache=true`, and then `isFromCache=false`
> 2. remove the snapshot listener
> 3. re-create a snapshot listener -> receives 2 snapshots where `isFromCache=true`, and then `isFromCache=false`
> 

I tried the test1( creating a second snapshot listener) with the debug app, and it is working as expected. 

Could you please add one more button to remove the snapshot listener, so that we can try the test2, re-create a listener? I tried to add the button, but iOS app is not my strong suit.

**Comment by TarekkMA** [comment]
@milaGGL, thank you! It was an issue on our part. The problem was that we were not using optionsWithSourceAndMetadata; instead, we used options.

Now I'm getting 2 results, which solves our issue:
```
snapshot: isFromCache: 1
snapshot: isFromCache: 0
```
