### ISSUE TITLE
iOS returns the FCM token, but the cloud uses firebase-admin and it shows UNREGISTERED. How can I fix this problem?

### ISSUE THREAD

**Issue by songzhiming** [firebase/firebase-ios-sdk#12860]
### Description

`extension PushKit: MessagingDelegate {
    // fcm回调
    public func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?) {
        guard let token = fcmToken else {
            return
        }
        Log.info("PushKit", "FCMToken---\(token)")`
   this token upload to server，but server  uses firebase-admin and it shows UNREGISTERED。
   
   and  server   firebase-admin verision  is 9.0.0

        
 

### Firebase SDK Version

10.23.0

### Xcode Version

15.1

### Installation Method

CocoaPods

### Firebase Product(s)

AB Testing, Analytics, Crashlytics, Performance, Remote Config

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by songzhiming** [comment]
![img_v3_02ac_2d4a47b7-0898-461f-ba44-c202e41f020g](https://github.com/firebase/firebase-ios-sdk/assets/7426040/737c2d4d-313d-47ed-8023-51823c7bb2bd)
this is  cloud log

**Comment by rizafran** [comment]
Hi @songzhiming, with the unregistered error, the existing registration token can be rendered invalid in the following scenarios:

- If the client app unregisters with FCM.
- If the client app is automatically unregistered, which can happen if the user uninstalls the application. For example, on iOS, if the APNS Feedback Service reported the APNS token as invalid
- If the registration token expires (for example, Google might decide to refresh registration tokens, or the APNS token has expired for iOS devices).
- If the client app is updated but the new version is not configured to receive messages.

For these cases, you may remove this registration token from the app server and stop using it to send messages.

If the issue persists, it's possible that this might be a backend issue. In this case, please file a ticket through our [support channel](https://firebase.google.com/support) so the team could investigate your project.
