### ISSUE TITLE
leveldb-library does not contain a binary artifact

### ISSUE THREAD

**Issue by joshuaLareta** [firebase/firebase-ios-sdk#12865]
### Description

I'm using the prebuilt firebase sdk v10.24. 

I'm having difficulty in building the project

```
local binary target 'leveldb-library' at 'Firebase/FirebaseFirestore/leveldb-library.xcframework' does not contain a binary artifact.
```

### Reproducing the issue

Download the latest prebuilt version from this: https://firebase.google.com/download/ios

### Firebase SDK Version

10.24

### Xcode Version

15.0

### Installation Method

Swift Package Manager

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

### Relevant Log Output

```shell
local binary target 'leveldb-library' at 'Firebase/FirebaseFirestore/leveldb-library.xcframework' does not contain a binary artifact.
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
Can you be more specific about the issue? Are you using Swift Package Manager or the binary distribution?

The leveldb binary shows up in the binary download from  https://firebase.google.com/download/ios:

<img width="891" alt="Screenshot 2024-04-29 at 8 47 03 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/73870/c4fecd98-f32e-4c3b-bac1-4eb3e642872e">

**Comment by joshuaLareta** [comment]
closing this. redownloaded the firebase iOS sdk and it fixes the issue.
