### ISSUE TITLE
[FR]:  PrivacyManifest missing in Firebase Performance

### ISSUE THREAD

**Issue by AswinMRathees** [firebase/firebase-ios-sdk#12861]
### Description

PrivacyManifest is missing in FirebasePerformance library and Apple's deadline for the same ends on 1st of May, when can we expect to get it updated

### Firebase Product(s)

Performance

**Comment by rizafran** [comment]
Hi @AswinMRathees, this seems related to #12488. Based on https://github.com/firebase/firebase-ios-sdk/issues/12488#issuecomment-2080288294, we'll eliminate the usage of required reasons in FirebasePerformance on v10.25.0.
