### ISSUE TITLE
[FirebaseCrashlytics] This SDK is not supported by the compiler Xcode 15.3

### ISSUE THREAD

**Issue by galgrien** [firebase/firebase-ios-sdk#12877]
### Description

Integrating `.xcframeworks` and when trying build project got this error message:

`Failed to build module 'FirebaseCrashlytics'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)', while this compiler is 'Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)'). Please select a toolchain which matches the SDK.`

Can you pls resolve it as soon as possible 🙏🏻 Today 1 May, and new rules in AppStoreConnect are already in effect, but we can't update Firebase SDK with latest Privacy Manifest files. Maybe you can prepare ZIP with `.xcframeworks` built on last Xcode 15.3? Thanks!

### Firebase SDK Version

10.25.0

### Xcode Version

15.3

### Installation Method

Zip

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Failed to build module 'FirebaseCrashlytics'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)', while this compiler is 'Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)'). Please select a toolchain which matches the SDK.
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
We don't reproduce this in our tests. Would you share a fully reproducible example?

**Comment by dawilliams-gpsw** [comment]
We have this issue as well using Xcode 15.3. Is this related to not setting `BUILD_LIBRARY_FOR_DISTRIBUTION`? https://stackoverflow.com/a/70562356/5101375

**Comment by paulb777** [comment]
Yes, it's important to delete old copies when updating. That likely explains the issue and agreed that it's a strange way to signal it. We do build with the `BUILD_LIBRARY_FOR_DISTRIBUTION` flag
