### ISSUE TITLE
Crashlytics: Multiple Firebase projects at runtime and DSYMs files for them

### ISSUE THREAD

**Issue by ppave** [firebase/firebase-ios-sdk#12870]
### Description

Currently we use multiple Firebase projects that we connect to at runtime. 
Let's say **_eu_** and **_us_** with corresponding **_GoogleService-Info_** and **_GoogleService-Info-us_** plists.
And we get auto-uploading DSYMs working only for the eu Firebase project, as I understand cause **_GoogleService-Info_** plist is used for DSYM by default if no explicit mentioning.

```
Build Phases script:
"${BUILD_DIR%Build/*}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run"
Input Files:
${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
$(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)
```

Following [current DSYM instructions](https://firebase.google.com/docs/crashlytics/get-started?platform=ios#set-up-dsym-uploading), even if I add paths to the both **_GoogleService-Info_** and **_GoogleService-Info-us_** in Input Files, it doesn't work.

Any ways how to get it working? Thanks.

### Firebase SDK Version

10.23.0

### Xcode Version

15

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reporting, @ppave. Could you share the complete run script you're using or a reproducible app?

**Comment by ppave** [comment]
All the above.
It works good for the default GoogleService-Info plist.

But the app has several GoogleService-Info plist files and user chooses one to connect at runtime.
But looks like DSYM configuration happens only for one GoogleService-Info plist file at compile time.

**Comment by themiswang** [comment]
Hey @ppave,

Thank you for reaching our, currently Crashlytics only [supports for Firebase default app](https://github.com/firebase/firebase-ios-sdk/blob/main/Crashlytics/Crashlytics/FIRCrashlytics.m#L239). You might get confused with DSYM upload process vs crash uploading process. For DSYM upload there is a way you can upload your symbol files to multiple firebase project but I don't think it is related to you problem. For crash uploading all crashes will upload to the GoogleService-Info associated to your default Firebase app. An alternative I can think about is to [add custom key](https://firebase.google.com/docs/crashlytics/customize-crash-reports?_gl=1*w4ui0v*_up*MQ..*_ga*ODkxNzY1MDg5LjE3MTQ2NzY0ODM.*_ga_CW55HF8NVT*MTcxNDY3NjQ4My4xLjAuMTcxNDY3NjQ4My4wLjAuMA..&platform=ios#add-keys) to mark which region the user belongs to for a certain crash. If you need more complicated analysis you can leverage on [BigQuery](https://firebase.google.com/docs/crashlytics/bigquery-export?_gl=1*y524c4*_up*MQ..*_ga*ODkxNzY1MDg5LjE3MTQ2NzY0ODM.*_ga_CW55HF8NVT*MTcxNDY3NjQ4My4xLjAuMTcxNDY3NjQ4My4wLjAuMA..#understanding_the_schema_in_bigquery) for that.

**Comment by ppave** [comment]
Thanks @themiswang for details, let me check
