### ISSUE TITLE
'FIRHeartbeatsPayload' for instance message is a forward declaration

### ISSUE THREAD

**Issue by Spatel91111** [firebase/firebase-ios-sdk#12891]
### Description

Updating latest pods getting this error 'FIRHeartbeatsPayload' for instance message is a forward declaration

<img width="314" alt="Screenshot 2024-05-03 at 10 25 45 AM" src="https://github.com/firebase/firebase-ios-sdk/assets/116056959/a3ebb038-a31d-4e1c-89d5-b2845ddca076">

### Firebase SDK Version

10.25.0

### Xcode Version

15.0

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, Crashlytics, Messaging, Performance, Remote Config

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by Spatel91111** [comment]
Hello @ncooke3 

Before I have used as below pods installed

pod 'Firebase/Core', '8.12.1'
  pod 'Firebase/Crashlytics', '8.12.1'
  pod 'Firebase/Analytics', '10.24.0'
  pod 'Firebase/Messaging', '8.12.1'
  pod 'Firebase/Performance','8.12.1'
  pod 'Firebase/RemoteConfig','8.12.1'
  
  Now update my podfile with below code
  
  pod 'Firebase/Core'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/Performance'
  pod 'Firebase/RemoteConfig'
  
  
  and pod update command and build project getting above error.

**Comment by paulb777** [comment]
@Spatel91111 The mix of 8.x and 10.x versions in the first could be problematic. Please also share the resulting Podfile.lock
