### ISSUE TITLE
Firebase missing DSYMs files - Xcode 15.3 

### ISSUE THREAD

**Issue by salvatoreboemia** [firebase/firebase-ios-sdk#12907]
### Description

Hi 

I have some issues with DSYMs files

In my Firebase console, I have a lot of missing, in the screen 3 versions should have had automatic upload via a script, but it is missing.

<img width="400" alt="Screenshot 2024-05-07 at 09 48 47" src="https://github.com/firebase/firebase-ios-sdk/assets/20614870/53db35ec-b173-4327-946e-8c49b15baed4">

I also updated the script as per the guide

- https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=ios#check-input-files-setup

This is my config

<img width="273" alt="Screenshot 2024-05-07 at 10 10 49" src="https://github.com/firebase/firebase-ios-sdk/assets/20614870/ecf7bceb-0ebe-4b98-962a-fd5fc5d0c04d">

Inside the Firebase Script:

<img width="1028" alt="Screenshot 2024-05-07 at 10 11 59" src="https://github.com/firebase/firebase-ios-sdk/assets/20614870/638a7459-4291-4fab-ae3a-f9d036abb9ee">

Do you have any idea?

Thanks

### Firebase SDK Version

10.24

### Xcode Version

15.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @salvatoreboemia, you may try the troubleshooting steps indicated on our docs [here](https://firebase.google.com/docs/crashlytics/troubleshooting?platform=ios#ios-locate-dsyms) regarding the missing dSYMs. If the issue persists, please file a ticket through our [support channel](https://firebase.google.com/support) so the team could check your project. Thanks.

**Comment by salvatoreboemia** [comment]
> Hi @salvatoreboemia, you may try the troubleshooting steps indicated on our docs [here](https://firebase.google.com/docs/crashlytics/troubleshooting?platform=ios#ios-locate-dsyms) regarding the missing dSYMs. If the issue persists, please file a ticket through our [support channel](https://firebase.google.com/support) so the team could check your project. Thanks.

I'm using this command

`mdfind -name .dSYM | while read -r line; do dwarfdump -u "$line"; done`

and I got correctly all DSYM file, the script is the one posted before. 

But still missing file on Firebase console.

I will proceed to open a ticket

thanks

**Comment by wickyou23** [comment]
Hello, @salvatoreboemia 

Do you resolve this issue, I got the same one. Could you help me share your solution with me?

Thanks.
