### ISSUE TITLE
macOS Email Link Authentication

### ISSUE THREAD

**Issue by MattTimmons** [firebase/firebase-ios-sdk#1291]
* Xcode version: 9.3.1
  * Firebase SDK version: 5.0
  * Firebase Component: Auth

Hello! I have been working with the v5.0 SDK in macOS in trying to get email link authentication to work. I do know that the DynamicLink SDK does not appear to be available in macOS. That's fine.

I have everything functional properly...except the fact that the firebase backend is seeing this as "desktop" behavior.

Using the Firebase DynamicLink debug view, I am able to view the deep link and see that it will open my macApp and I have my Mac app seeing the deeplink url upon clicking that "deep link" link.

Problem is that because the Mac is a "desktop", firebase bypasses this and sends it to the website end url. 

Is there anyway to get around this. Perhaps and un-dcoumented setting in FIRActionCodeSettings to trick the user agent ?

I know this is not supported, but, hey, it would be pretty cool to have for my customers.
Thank you so much Firebase team!

**Comment by dmandar** [comment]
This is currently not supported, but have added a new feature request for the same. Thanks for the feedback!
