### ISSUE TITLE
Firebase Dynamic Links: App preview page for IOS not showing the broken logo

### ISSUE THREAD

**Issue by aliahmad-dev** [firebase/firebase-ios-sdk#12932]
### Description

App preview page not showing the logo and by checking more we found that the logo URL responding 403 while visiting the preview page.

### Reproducing the issue

![IMG_9667](https://github.com/firebase/firebase-ios-sdk/assets/43981395/65137a4d-841b-4aac-ab73-3f97f707fb4d)

![Screenshot 2024-05-10 at 17 08 44](https://github.com/firebase/firebase-ios-sdk/assets/43981395/2c046d4b-2dd6-4c66-b232-a7c7dff23ae5)

### Firebase SDK Version

N/A

### Xcode Version

N/A

### Installation Method

Swift Package Manager

### Firebase Product(s)

DynamicLinks

### Targeted Platforms

iOS

**Comment by rizafran** [comment]
Hi @aliahmad-dev, please note that the Firebase Dynamic Links service will be shutdown on August 25, 2025. In the meantime, only critical or security issues will be fixed in the SDK. See https://firebase.google.com/support/dynamic-links-faq for details.

**Comment by aliahmad-dev** [comment]
even if it's going to shutdown at least you can provide more information about the issue as we have our application in production and our influencer raising that issue while sharing the URL with users. @rizafran
