### ISSUE TITLE
 Invalid version number in '-target x86_64-apple-ios10.15-macabi'

### ISSUE THREAD

**Issue by stoope** [firebase/firebase-ios-sdk#12967]
### Description

After updating to `Xcode 15.4` and `Firebase 10.26.0`, I get the error when building the release archive for macCatalyst. Everything works fine for the iOS target.

<img width="488" alt="Screenshot 2024-05-14 at 21 26 51" src="https://github.com/firebase/firebase-ios-sdk/assets/17287557/f9d9b199-745d-422b-9dcc-138cc4a8b960">

### Firebase SDK Version

10.26.0

### Xcode Version

15.4

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, In-App Messaging

### Targeted Platforms

macCatalyst

### Relevant Log Output

```shell
note: Injecting stub binary into codeless framework
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -dynamiclib -Xlinker -adhoc_codesign -x c /dev/null -o /Users/stoope/Library/Developer/Xcode/DerivedData/.../Contents/Frameworks/GoogleAppMeasurementIdentitySupport.framework/Versions/A/GoogleAppMeasurementIdentitySupport -target arm64-apple-ios10.15-macabi -target x86_64-apple-ios10.15-macabi
clang: error: invalid version number in '-target x86_64-apple-ios10.15-macabi'
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment]
Thanks @stoope , the issue description mentions Xcode 15.3, but the value for the Xcode question is Xcode 15.4. Was the issue happening on both?

**Comment by stoope** [comment]
Hey @ncooke3,
fixed the version in the description, it is happening in Xcode 15.4, I haven't checked with Xcode 15.3.
I should also mention that I updated macOS to 14.5 since it could be related.

**Comment by ncooke3** [comment]
Is it only for GoogleAppMeasurement and FirebaseAnalytics?

**Comment by stoope** [comment]
`GoogleAppMeasurementIdentitySupport.framework`, `GoogleAppMeasurement.framework ` and `FirebaseAnalytics.framework`

**Comment by bravelocation** [comment]
Just to confirm I'm pretty certain this is an Xcode 15.4 issue, as I'm still on 10.24.0 and seeing the same error for my Mac Catalyst build

It's only started failing after I upgraded Xcode 😞

**Comment by paulb777** [comment]
Going to close since this looks like an Apple issue for which Firebase cannot address.

Feel free to continue the conversation.
