### ISSUE TITLE
Account linking stopped working with the new Facebook limited login

### ISSUE THREAD

**Issue by Daniel3711997** [firebase/firebase-ios-sdk#12976]
### Description

Recently https://github.com/facebook/facebook-ios-sdk created a new release which conforms with Apple Privacy Manifest but now the token returned from the limited login no longer works to link a user to an account.

- android works correctly

(on IOS - FB LIMITED LOGIN) For example if i login with my gmail and then i login with my facebook which uses the same email and want to link with credential i receive this error: Duplicate credential received. Please try again with a new credential

### Firebase SDK Version

10.26

### Xcode Version

15.4

### Installation Method

CocoaPods

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reporting, @Daniel3711997. I tried linking a Google account to a Facebook account with the same email, but I wasn't able to get the duplicate credential error. I just want to clarify if you're trying to link the Facebook account to an email/password or to a Google account through Google Sign-In?

**Comment by Daniel3711997** [comment]
i got the duplicate error after i logged in with google signin and after that tried to link the facebook account

**Comment by Daniel3711997** [comment]
> Thanks for clarifying, @Daniel3711997. I tried to link the Google Sign-In credential to Facebook account, but the issue is not reproducible. Is it possible for you to share an MCVE or detailed steps to reproduce the issue?

the issue still persists, link the facebook account to a google account (but with limited login from Facebook)

**Comment by Taifur23** [comment]
Hello, This is Shohag. I am a professional Ethical Hacker,
Security Specialist as well as Penetration Tester. I can test the following vulnerability and I will provide you with a perfect assessment of your website security
which makes your website safe and sound.

My Experience:
💗. Recovering Hacked WordPress Website
💗. Full Vulnerability Scan and WordPress website malware removal
💗. Vulnerability Assessment
💗. Antispam protection
💗. Analysis of database servers
💗. Restore a hacked website
💗. Ethical Hacking(White Hat Hacker)
💗. Hacked account recovery
💗. Password recovery
💗. Decode encrypted files
💗. Vulnerability Testing
💗....my WhatsApp number +8801315423936

**Comment by Hiteshboricha-Pomelo** [comment]
@google-oss-bot, recently I have integrated Facebook limited login now I am getting error **(Duplicate credential received. Please try again with a new credential.)** with firebase auth Facebook limited login. Please help me to fix this error.


let idTokenString = AuthenticationToken.current?.tokenString
let nonce = self.generateNonce().sha256()
self.authCredential = OAuthProvider.credential(
withProviderID: SignInMethod.facebook.provider,
idToken: idTokenString!,
rawNonce: nonce
)

guard let authCredential = authCredential else {
            return
        }
 Auth.auth().signIn(with: authCredential) { (user, error) in
            if let error = error {
                print(error.localizedDescription)
                self.handleAuthError(error: error, signInMethod: signInMethod)
            }
           }
           
<img width="853" alt="Screenshot 2024-06-25 at 2 07 43 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/152582994/fac21fa9-6f76-4f70-8102-2869aa6c349d">

**Comment by rizafran** [comment]
@Hiteshboricha-Pomelo, may I know if you're generating a new nonce every sign in? You may also check [this](https://github.com/firebase/firebase-ios-sdk/issues/4434#issuecomment-564776016) related issue.

**Comment by Hiteshboricha-Pomelo** [comment]
yes I was generating a new nonce every sign in. I read the document again for limited login and now it's fixed. Issue with Nonce only. Thanks for the quickly response

**Comment by Daniel3711997** [comment]
still happening

**Comment by rizafran** [comment]
@Daniel3711997 please provide a sample app that can reproduce the issue to investigate.

**Comment by Daniel3711997** [comment]
> @google-oss-bot, recently I have integrated Facebook limited login now I am getting error **(Duplicate credential received. Please try again with a new credential.)** with firebase auth Facebook limited login. Please help me to fix this error.
> 
> let idTokenString = AuthenticationToken.current?.tokenString let nonce = self.generateNonce().sha256() self.authCredential = OAuthProvider.credential( withProviderID: SignInMethod.facebook.provider, idToken: idTokenString!, rawNonce: nonce )
> 
> guard let authCredential = authCredential else { return } Auth.auth().signIn(with: authCredential) { (user, error) in if let error = error { print(error.localizedDescription) self.handleAuthError(error: error, signInMethod: signInMethod) } }
> 
> <img alt="Screenshot 2024-06-25 at 2 07 43 PM" width="853" src="https://private-user-images.githubusercontent.com/152582994/342648052-fac21fa9-6f76-4f70-8102-2869aa6c349d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzUwMTYsIm5iZiI6MTcyMTEzNDcxNiwicGF0aCI6Ii8xNTI1ODI5OTQvMzQyNjQ4MDUyLWZhYzIxZmE5LTZmNzYtNGY3MC04MTAyLTI4NjlhYTZjMzQ5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQxMjU4MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTQwNTBkODE3YzNkZTI1NWZhZDc3ZjUxNTlhODU4MjFhZmZiODY5YWQ1ZWYwMDRmM2ZiN2UzN2M5N2QyOGVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.efIvsxdg19N9vMoYisIkgrjeB4xKA37OBXTdvK7FQno">

he already provided one

**Comment by rizafran** [comment]
@Daniel3711997, I tried to login using my Google account and then link to my Facebook account with the same email using Facebook limited login by following the steps [here](https://firebase.google.com/docs/auth/ios/facebook-login#implement_facebook_limited_login), but it's not reproducible on my end. Could you confirm if we're on the same page? Also, could you provide your `Podfile.lock` file?
