### ISSUE TITLE
 Linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by zhsuperman** [firebase/firebase-ios-sdk#12982]
### Description

ld: warning: Could not find or use auto-linked library 'swiftCompatibility50': library 'swiftCompatibility50' not found
ld: warning: Could not find or use auto-linked library 'swiftCompatibility51': library 'swiftCompatibility51' not found
ld: warning: Could not find or use auto-linked library 'swiftCompatibility56': library 'swiftCompatibility56' not found
ld: warning: Could not find or use auto-linked library 'swiftCompatibilityConcurrency': library 'swiftCompatibilityConcurrency' not found
ld: warning: Could not find or use auto-linked library 'swiftCompatibilityDynamicReplacements': library 'swiftCompatibilityDynamicReplacements' not found
ld: warning: Could not find or use auto-linked library 'swiftCompatibilityPacks': library 'swiftCompatibilityPacks' not found
ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
Undefined symbols for architecture arm64:
  "__swift_FORCE_LOAD_$_swiftCompatibility50", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_FirebaseAnalytics in FirebaseAnalytics[17](Analytics+StoreKit.o)
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_FirebaseCoreInternal in FirebaseCoreInternal[4](_ObjC_HeartbeatController.o)
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_FirebaseCrashlytics in FirebaseCrashlytics[85](CrashlyticsRemoteConfigManager.o)
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_FirebaseRemoteConfig in FirebaseRemoteConfig[18](Codable.o)
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_FirebaseRemoteConfigInterop in FirebaseRemoteConfigInterop[4](RemoteConfigConstants.o)
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_FirebaseSessions in FirebaseSessions[6](ApplicationInfo.o)
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_FirebaseSharedSwift in FirebaseSharedSwift[4](FirebaseDataEncoder.o)
      ...
  "__swift_FORCE_LOAD_$_swiftCompatibility51", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_FirebaseAnalytics in FirebaseAnalytics[17](Analytics+StoreKit.o)
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_FirebaseCoreInternal in FirebaseCoreInternal[4](_ObjC_HeartbeatController.o)
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_FirebaseCrashlytics in FirebaseCrashlytics[85](CrashlyticsRemoteConfigManager.o)
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_FirebaseRemoteConfig in FirebaseRemoteConfig[18](Codable.o)
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_FirebaseRemoteConfigInterop in FirebaseRemoteConfigInterop[4](RemoteConfigConstants.o)
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_FirebaseSessions in FirebaseSessions[6](ApplicationInfo.o)
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_FirebaseSharedSwift in FirebaseSharedSwift[4](FirebaseDataEncoder.o)
      ...
  "__swift_FORCE_LOAD_$_swiftCompatibility56", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_FirebaseAnalytics in FirebaseAnalytics[17](Analytics+StoreKit.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_FirebaseCoreInternal in FirebaseCoreInternal[4](_ObjC_HeartbeatController.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_FirebaseCrashlytics in FirebaseCrashlytics[85](CrashlyticsRemoteConfigManager.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_FirebaseRemoteConfig in FirebaseRemoteConfig[18](Codable.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_FirebaseRemoteConfigInterop in FirebaseRemoteConfigInterop[4](RemoteConfigConstants.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_FirebaseSessions in FirebaseSessions[6](ApplicationInfo.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_FirebaseSharedSwift in FirebaseSharedSwift[4](FirebaseDataEncoder.o)
      ...
  "__swift_FORCE_LOAD_$_swiftCompatibilityConcurrency", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseAnalytics in FirebaseAnalytics[17](Analytics+StoreKit.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseCoreInternal in FirebaseCoreInternal[4](_ObjC_HeartbeatController.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseCrashlytics in FirebaseCrashlytics[85](CrashlyticsRemoteConfigManager.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseRemoteConfig in FirebaseRemoteConfig[18](Codable.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseRemoteConfigInterop in FirebaseRemoteConfigInterop[4](RemoteConfigConstants.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseSessions in FirebaseSessions[6](ApplicationInfo.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseSharedSwift in FirebaseSharedSwift[4](FirebaseDataEncoder.o)
      ...
  "__swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_FirebaseAnalytics in FirebaseAnalytics[17](Analytics+StoreKit.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_FirebaseCoreInternal in FirebaseCoreInternal[4](_ObjC_HeartbeatController.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_FirebaseCrashlytics in FirebaseCrashlytics[85](CrashlyticsRemoteConfigManager.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_FirebaseRemoteConfig in FirebaseRemoteConfig[18](Codable.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_FirebaseRemoteConfigInterop in FirebaseRemoteConfigInterop[4](RemoteConfigConstants.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_FirebaseSessions in FirebaseSessions[6](ApplicationInfo.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_FirebaseSharedSwift in FirebaseSharedSwift[4](FirebaseDataEncoder.o)
      ...
ld: symbol(s) not found for architecture arm64

Showing Recent Errors Only
Undefined symbol: __swift_FORCE_LOAD_$_swiftCompatibility50

Undefined symbol: __swift_FORCE_LOAD_$_swiftCompatibility51

Undefined symbol: __swift_FORCE_LOAD_$_swiftCompatibility56

Undefined symbol: __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency

Undefined symbol: __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements

Linker command failed with exit code 1 (use -v to see invocation)
我使用cocospods 升级firebase到10.25.0版本 报错 

我按照readme 操作Other Linker Settings 天际了-ObjC和-lc++ 也添加了空的swift文件 依然解决不了我的问题,希望能解决我的问题

### Reproducing the issue

Showing Recent Errors Only
Undefined symbol: __swift_FORCE_LOAD_$_swiftCompatibility50

Undefined symbol: __swift_FORCE_LOAD_$_swiftCompatibility51

Undefined symbol: __swift_FORCE_LOAD_$_swiftCompatibility56

Undefined symbol: __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency

Undefined symbol: __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements

Linker command failed with exit code 1 (use -v to see invocation)

### Firebase SDK Version

10.25.0

### Xcode Version

15.4

### Installation Method

CocoaPods

### Firebase Product(s)

AB Testing, Analytics, Crashlytics, DynamicLinks, Installations, ML Model Downloader, Remote Config

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Showing Recent Errors Only
Undefined symbol: __swift_FORCE_LOAD_$_swiftCompatibility50

Undefined symbol: __swift_FORCE_LOAD_$_swiftCompatibility51

Undefined symbol: __swift_FORCE_LOAD_$_swiftCompatibility56

Undefined symbol: __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency

Undefined symbol: __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements

Linker command failed with exit code 1 (use -v to see invocation)
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by kunal08pandey** [comment]
I am also facing the same issue

**Comment by paulb777** [comment]
Please see if anything in the discussion at #12603 helps.

**Comment by zhsuperman** [comment]
在项目中添加一个swift文件就可以了
