### ISSUE TITLE
ビルドエラー「FirebaseCore/FirebaseCore.h」ファイルが見つかりません。

### ISSUE THREAD

**Issue by oohashi-shigenori** [firebase/firebase-ios-sdk#12985]
### Description

After adding [Cordova-plugin-push](https://github.com/havesource/cordova-plugin-push) ,during the build process, 'FirebaseCore/FirebaseCore.h' file not found. occurs.

/...appdirectory/platforms/ios/Pods/Firebase/CoreOnly/Sources/Firebase.h:19 error: 'FirebaseCore/FirebaseCore.h' file not found
#import <FirebaseCore/FirebaseCore.h>
^
/...appdirectory/Plugins/@havesource/cordova-plugin-push/PushPlugin.m:33 error: Module 'FirebaseCore' not found
@import FirebaseCore;

I opened  "App.xcworkspace/" not  "App.xcodeproj/".
I have the following, but it did not resolve the issue.
close Xcode
`rm -rf ~/Library/Developer/Xcode/DerivedData/`
`pod deintegrate`
`pod install`
restart Xcode

I have tried  [#2233](https://github.com/firebase/firebase-ios-sdk/issues/2233) , but the issue is not resolved.

### Reproducing the issue

After adding [Cordova-plugin-push](https://github.com/havesource/cordova-plugin-push) ,during the build process, 'FirebaseCore/FirebaseCore.h' file not found. occurs.

Podfile
-----
DO NOT MODIFY -- auto-generated by Apache Cordova
source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'
use_frameworks!
target 'app name' do
        project 'appname.xcodeproj'
	pod 'Firebase/Messaging', '~> 8.1.1'
end

### Firebase SDK Version

8.1.1

### Xcode Version

15.2

### Installation Method

CocoaPods

### Firebase Product(s)

Messaging

### Targeted Platforms

iOS

### Relevant Log Output

```shell
After adding [Cordova-plugin-push](https://github.com/havesource/cordova-plugin-push) ,during the build process, 'FirebaseCore/FirebaseCore.h' file not found. occurs.

/...appdirectory/platforms/ios/Pods/Firebase/CoreOnly/Sources/Firebase.h:19 error: 'FirebaseCore/FirebaseCore.h' file not found
#import <FirebaseCore/FirebaseCore.h>
^
/...appdirectory/Plugins/@havesource/cordova-plugin-push/PushPlugin.m:33 error: Module 'FirebaseCore' not found
@import FirebaseCore;
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

PODS:
  - Firebase/CoreOnly (8.1.1):
    - FirebaseCore (= 8.1.0)
  - Firebase/Messaging (8.1.1):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 8.1.0)
  - FirebaseCore (8.1.0):
    - FirebaseCoreDiagnostics (~> 8.0)
    - GoogleUtilities/Environment (~> 7.4)
    - GoogleUtilities/Logger (~> 7.4)
  - FirebaseCoreDiagnostics (8.15.0):
    - GoogleDataTransport (~> 9.1)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/Logger (~> 7.7)
    - nanopb (~> 2.30908.0)
  - FirebaseInstallations (8.15.0):
    - FirebaseCore (~> 8.0)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/UserDefaults (~> 7.7)
    - PromisesObjC (< 3.0, >= 1.2)
  - FirebaseMessaging (8.1.0):
    - FirebaseCore (~> 8.0)
    - FirebaseInstallations (~> 8.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.4)
    - GoogleUtilities/Environment (~> 7.4)
    - GoogleUtilities/Reachability (~> 7.4)
    - GoogleUtilities/UserDefaults (~> 7.4)
  - GoogleDataTransport (9.4.1):
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/AppDelegateSwizzler (7.13.3):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
    - GoogleUtilities/Privacy
  - GoogleUtilities/Environment (7.13.3):
    - GoogleUtilities/Privacy
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/Logger (7.13.3):
    - GoogleUtilities/Environment
    - GoogleUtilities/Privacy
  - GoogleUtilities/Network (7.13.3):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Privacy
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.13.3)":
    - GoogleUtilities/Privacy
  - GoogleUtilities/Privacy (7.13.3)
  - GoogleUtilities/Reachability (7.13.3):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/UserDefaults (7.13.3):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - nanopb (2.30908.0):
    - nanopb/decode (= 2.30908.0)
    - nanopb/encode (= 2.30908.0)
  - nanopb/decode (2.30908.0)
  - nanopb/encode (2.30908.0)
  - PromisesObjC (2.4.0)

DEPENDENCIES:
  - Firebase/Messaging (~> 8.1.1)

SPEC REPOS:
  trunk:
    - Firebase
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseInstallations
    - FirebaseMessaging
    - GoogleDataTransport
    - GoogleUtilities
    - nanopb
    - PromisesObjC

SPEC CHECKSUMS:
  Firebase: 4bb49ae87756034cef870fa3c4006235eb46f475
  FirebaseCore: 389c4ce9a7cce4a7e25eb22326b4bee0050557b2
  FirebaseCoreDiagnostics: 92e07a649aeb66352b319d43bdd2ee3942af84cb
  FirebaseInstallations: 40bd9054049b2eae9a2c38ef1c3dd213df3605cd
  FirebaseMessaging: c8871b0907dcf4e76de81241eb6a62be6d657d2f
  GoogleDataTransport: 6c09b596d841063d76d4288cc2d2f42cc36e1e2a
  GoogleUtilities: ea963c370a38a8069cc5f7ba4ca849a60b6d7d15
  nanopb: a0ba3315591a9ae0a16a309ee504766e90db0c96
  PromisesObjC: f5707f49cb48b9636751c5b2e7d227e43fba9f47

PODFILE CHECKSUM: 5053f317d83cfd61683cafa4fa184069332fc0ee

COCOAPODS: 1.15.2

**Comment by paulb777** [comment]
Sorry about the trouble. We're not able to help with Cordova questions here. Please report to Cordova support channels.

Note that the version is several years old. The latest Firebase release for CocoaPods is 10.25.0.
