### ISSUE TITLE
Crash in -[FIRASqliteStore endTransaction]

### ISSUE THREAD

**Issue by moontecholabs** [firebase/firebase-ios-sdk#1299]
0 | libsystem_kernel.dylib | fsync + 8
-- | -- | --
1 | libsqlite3.dylib | (null) + 59100
2 | libsqlite3.dylib | (null) + 2236
3 | libsqlite3.dylib | (null) + 56892
4 | libsqlite3.dylib | (null) + 21904
5 | libsqlite3.dylib | (null) + 3472
6 | libsqlite3.dylib | (null) + 61016
7 | libsqlite3.dylib | sqlite3_step + 2708
8 | libsqlite3.dylib | sqlite3_exec + 536
9 | | -[FIRASqliteStore endTransaction] + 4304000580
10 | | -[FIRASqliteStore performTransaction:] + 4303999748
11 |  | -[FIRAMeasurement writeEventOnWorkerQueue:] + 4304123572
12 |  | -[FIRAMeasurement handleEventOnWorkerQueue:] + 4304121764
13 |  | __52-[FIRAScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke + 4304198644
14 | libdispatch.dylib | _dispatch_call_block_and_release + 24
15 | libdispatch.dylib | _dispatch_client_callout + 16
16 | libdispatch.dylib | _dispatch_queue_serial_drain$VARIANT$mp + 528
17 | libdispatch.dylib | _dispatch_queue_invoke$VARIANT$mp + 340
18 | libdispatch.dylib | _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 404
19 | libdispatch.dylib | _dispatch_workloop_worker_thread$VARIANT$mp + 644
20 | libsystem_pthread.dylib | _pthread_wqthread + 932
21 | libsystem_pthread.dylib | start_wqthread + 4

**Comment by mrpuzzler** [comment]
got same bug, don't know how to reproduce

**Comment by moontecholabs** [comment]
Yes, using C++ SDK

**Comment by morganchen12** [comment]
Is this still an issue on the latest version of Firebase?

Can either of you provide a sample that reproduces the issue, even inconsistently?

**Comment by mrpuzzler** [comment]
With latest 5.x - I don't see it.

**Comment by moontecholabs** [comment]
@markbouchard 
Yes, seems fixed now.

Thanks
