### ISSUE TITLE
Add Firebase in iOS Custom Keyboard Extension

### ISSUE THREAD

**Issue by khatri6168** [firebase/firebase-ios-sdk#12992]
### Description

Hello Team, 

I'm working on Custom Keyboard Extension Project for iOS now.
Can I integrate and use Realtime Database in customer Keybord.  

But I it's not working in Keybord Extension. could you please check the issue. 

Thank. 

### Reproducing the issue

I just added FirebaseApp.configure() to my KeyboardController Class like this.

  if (FirebaseApp.app() == nil) {
          FirebaseApp.configure()
        }

![Screenshot 2024-05-18 at 12 25 30 PM](https://github.com/firebase/firebase-ios-sdk/assets/20636325/ec53288d-a786-43a7-b5cf-f568e3319855)

but in log showing the message 

10.26.0 - [FirebaseCore][I-COR000003] The default Firebase app has not yet been configured. Add `FirebaseApp.configure()` to your application initialization. This can be done in in the App Delegate's application(_:didFinishLaunchingWithOptions:)` (or the `@main` struct's initializer in SwiftUI). Read more: https://goo.gl/ctyzm8.

![Screenshot 2024-05-18 at 12 26 42 PM](https://github.com/firebase/firebase-ios-sdk/assets/20636325/8c2bb7a5-9df8-4924-8c28-9af7f023f377)

So can you please let me know how can I add FirebaseApp.configure() and access the Realtime Database in my Custom Keyboard Extension app. 

I have also add then "GoogleService-Info.plist into this target as well." 

Thank you! 

### Firebase SDK Version

10.26.0

### Xcode Version

15.3 

### Installation Method

Swift Package Manager

### Firebase Product(s)

Database

### Targeted Platforms

iOS

### Relevant Log Output

```shell
10.26.0 - [FirebaseCore][I-COR000003] The default Firebase app has not yet been configured. Add `FirebaseApp.configure()` to your application initialization. This can be done in in the App Delegate's application(_:didFinishLaunchingWithOptions:)` (or the `@main` struct's initializer in SwiftUI). Read more: https://goo.gl/ctyzm8.
```

**Comment by khatri6168** [comment]
Hello @rizafran  yes I have add **FirebaseApp.configure()** in Custom Keyboard Extension main file and in the main project  **AppDelegate** 

in the main project when I call it's working and access the Realtime Database but when I open Keybord Extension so in this class showing firebase error this and not access the Realtime Database

**Comment by khatri6168** [comment]
@rizafran also when I check this in simulator the it’s working but when I check in device so not working this

**Comment by khatri6168** [comment]
Hello @rizafran any update?

**Comment by rizafran** [comment]
Hi @khatri6168, keyboard extension works in other products (see this test [app](https://github.com/charlotteliang/firebase-ios-app-extensions) for sample). For Realtime Database, I've consulted with an engineer if keyboard extension can work, and I'll let you know once I got an update. For the meantime, could you provide a sample app that reproduces the issue since your error is related to the initialization of Firebase app?

**Comment by auteur-dreams** [comment]
Hi @rizafran I'm running into the same error when I open try to open the custom keyboard extension.

Main App:
class AppDelegate: NSObject, UIApplicationDelegate {
  func application(_ application: UIApplication,
                   didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
    print("Auteur application is starting up. ApplicationDelegate didFinishLaunchingWithOptions.")
    FirebaseApp.configure()
    return true
  }
}

@main
struct auteurApp: App {
    // register app delegate for Firebase setup
    @UIApplicationDelegateAdaptor(AppDelegate.self) var delegate
    
    // Initialize the Core Data stack
    let persistentContainer = CoreDataStack.shared.persistentContainer
    
    var body: some Scene {
        WindowGroup {
            ContentView()
                .environment(\.managedObjectContext, persistentContainer.viewContext)
        }
    }
}

And then I also have this in the custom keyboard extension
// Configure Firebase
if FirebaseApp.app() == nil {
     FirebaseApp.configure()
     print("Firebase configured in KeyboardViewController")
     } else {
          print("Firebase already configured in KeyboardViewController")
     }
