### ISSUE TITLE
Add the file privacy manifet policies in that version

### ISSUE THREAD

**Issue by anhpt1adr** [firebase/firebase-ios-sdk#12996]
### Description

I was reported to upgrade the version to 10.24.0 while the current application is 10.26.0, you can add the file privacy manifet policies in that version

![image (2)](https://github.com/firebase/firebase-ios-sdk/assets/148935156/337e59df-b740-4e2e-98e7-6311f4118ba1)

### Firebase SDK Version

10.26.0

### Xcode Version

15.4

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @anhpt1adr, if you've updated your SDK to 10.26.0, I think there's no action needed as this is only a warning. Also, Analytics doesn't have a privacy manifest as it doesn't use any required reason APIs, but there was a fix in [10.24.0](https://github.com/firebase/firebase-ios-sdk/issues/12684#issuecomment-2046066616) which is the removal of `lstat` and `stat`.
