### ISSUE TITLE
Update GoogleUtilities major version along with Firebase 11

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#13004]
### Description

- [X]  Update minimum platform version to Xcode 15 minimums - iOS 12, etc.
- [x] Clean up deprecated code in Google Utilities
- [X]  Investigate modules that should move into Firebase
- [X]  Consider removing GULSecureCoding
- [X] Cleanup Heartbeat code
- [X]  Eliminate Promises dependency
~- [ ]  Move GULKeychain storage to Installations~ Also used by AppCheckCore
- [x]  Make GULUserDefaults a pure wrapper
- [X]  Review and update 1P dependents

### Firebase Product(s)

Many

**Comment by ncooke3** [comment]
podspec command:

```
sed -i '' -E "s/(GoogleUtilities\/[^\s]+)~>(.*)/\1~> 8.0'/g" *.podspec
```

**Comment by ncooke3** [comment]
> - [ ]  Make GULUserDefaults a pure wrapper

I have a branch: https://github.com/google/GoogleUtilities/pull/new/nc/user-defaults

But the following test is still failing:

<img width="1092" alt="Screenshot 2024-06-21 at 3 26 44 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/36927374/93212e66-31db-40ac-b6ad-3860b1444204">

**Comment by paulb777** [comment]
Seems like it should be ok, since that test is making sure the separate class (that is no longer needed) isn't getting notifications.

Based on https://github.com/google/GoogleUtilities/blob/main/GoogleUtilities/UserDefaults/Public/GoogleUtilities/GULUserDefaults.h#L19, the test seems directly related to the bug we now believe to be fixed.

**Comment by ncooke3** [comment]
Thanks for taking a look. Makes sense– the notification still sends with user defaults, but the crashes as a result were fixed.  I'll open the PR.

**Comment by ncooke3** [comment]
> * Clean up deprecated code in Google Utilities

Regarding this, I think we can now check this off. The move to os_log will remove some deprecated code, and so the only other deprecated source code left is described here: https://github.com/google/GoogleUtilities/issues/176#issuecomment-2190018910
