### ISSUE TITLE
FIRFirestoreErrorDomain

### ISSUE THREAD

**Issue by shiwanjun** [firebase/firebase-ios-sdk#1300]
我在中国使用firestore服务(iOS),但是每次请求时，都会出现FSTWriteStream 0x608000301b90 close: Error Domain=FIRFirestoreErrorDomain Code=13 "(null)" 错误，我想知道我该怎么处理和解决相关的问题，谢谢

**Comment by wilhuff** [comment]
Google Translate said this was what you said:

> I use the firestore service (iOS) in China, but FSTWriteStream 0x608000301b90 will appear on every request. close: Error Domain=FIRFirestoreErrorDomain Code=13 "(null)" error, I want to know how I can handle and solve related problems, thanks

As far as we know, Firestore will not work in China, because our hostname `"firestore.googleapis.com"` is blocked. See more here:

https://stackoverflow.com/questions/42605566/can-firebase-be-used-as-a-realtime-database-in-china-now/42620514

There's nothing we can do about this, sorry.

**Comment by shiwanjun** [comment]
目前我们使用ShadowsocksX 也不能使用firestore吗？因为我们使用的用户群体是非中国用户。是不是有什么其他方法，可以链接到firestore

**Comment by shiwanjun** [comment]
![image](https://user-images.githubusercontent.com/3345618/40337695-960acfa4-5da3-11e8-9699-2fcfee4fe0b4.png)

**Comment by morganchen12** [comment]
Shadowsocks 和 Firestore 应该不会有冲突，您目前的问题可能是 Shadowsocks 配置的问题。

**Comment by shiwanjun** [comment]
那我怎么配置Shadowsocks才能链接上去呢？

**Comment by wilhuff** [comment]
Unfortunately, we cannot help you with this kind of problem here because we cannot help anyone circumvent a government-imposed network block.

**Comment by shiwanjun** [comment]
好的，谢谢

**Comment by dubiao** [comment]
@shiwanjun 建议在国外的热门项目上提issue时使用英文，一来可以使项目成员可以很快了解到情况，二来可以让其它对项目关心的人也知道相关情况，而不至于提出重复的问题。如果你不写英文，会操作的人可能会用翻译工具来知道你要表达的意思，但是这会大大降低项目成员的工作效率。如果英文不太好，可以利用翻译工具，比如 [Googel翻译](translate.google.cn)。当然像 @wilhuff 这样给出双语的版本，更好。
也能提升你的英文水平。
代表开源团队谢谢你。

Hi, @shiwanjun .
We always hope you will file an issue in English in order the project's member can receive your advice as soon as possible, as well as the people who care with this project, avoid them to file a duplicated issue. 
When you file an issue in Chinese, they may use translator tools but this makes their work inefficient. 
If your are poor in English, you can use something like  [Googel翻译](translate.google.cn) to help you. It works perfectly. This makes it friendly in open source world. And like @wilhuff , he gave a bilingual--version. He is sooo nice. (Thank you, @wilhuff )
And this can improve your English skills.
Thank you.

**Comment by wilhuff** [comment]
@dubiao you give me too much credit. I’m also using Google Translate :-).

**Comment by chandlerding** [comment]
I’d suggest a workaround for this case but need firebase team to allow SDK users set a customize api URL .
Then user can host a reverse proxy under their own domain name and configure the SDK to send all api request to their own reverse proxy.

**Comment by wilhuff** [comment]
You can set the host name via settings on the main Firestore object: https://firebase.google.com/docs/reference/ios/firebasefirestore/api/reference/Classes/FIRFirestoreSettings#host
