### ISSUE TITLE
License of FirebaseAnalytcs and GoogleAppMeasurement in Podspec vs SPM

### ISSUE THREAD

**Issue by lucatorella** [firebase/firebase-ios-sdk#13020]
### Description

The Podspecs for `FirebaseAnalytics` and `GoogleAppMeasurement` are marked with a “Copyright 202x Google” license in the Podspec ([link](https://github.com/CocoaPods/Specs/blob/master/Specs/e/3/b/GoogleAppMeasurement/10.25.0/GoogleAppMeasurement.podspec.json#L9)). 

The same dependencies, in SPM, are marked as Apache 2.0 ([GitHub - google/GoogleAppMeasurement](https://github.com/google/GoogleAppMeasurement) ).

In this [other issue](https://github.com/firebase/firebase-ios-sdk/issues/11468#issuecomment-1604369552), it was mentioned that because these 2 libraries are distributed as binaries they can't be Apache 2.0. I'm not an expert, but is this true? If it is shouldn't you change the SPM license?

### Firebase SDK Version

10.26

### Xcode Version

15.4

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

**Comment by paulb777** [comment]
@lucatorella Thanks for the report. We'll get the fix into the next GoogleAppMeasurement release after today's.

**Comment by ncooke3** [comment]
> @lucatorella Thanks for the report. We'll get the fix into the next GoogleAppMeasurement release after today's.

Hi @lucatorella– you can actually expect this fix a little earlier. Due to the timing of things, this fix will actually release this week (planned for tomorrow). Thanks again!

**Comment by lucatorella** [comment]
thanks!

Can you also fix FirebaseAnalytics? It has the same problem: https://github.com/CocoaPods/Specs/blob/master/Specs/e/2/1/FirebaseAnalytics/10.25.0/FirebaseAnalytics.podspec.json

**Comment by paulb777** [comment]
I'll reopen, since it will take a bit more thought. SPM doesn't provide a good way to describe different sets of licenses for different include products from the same repo. BTW all Firebase licenses are concatenated in https://github.com/firebase/firebase-ios-sdk/blob/main/CoreOnly/NOTICES

**Comment by paulb777** [comment]
On further research, it seems the LICENSE in the repository refers to the code in the repository to enable Swift Package Manager which is Apache licensed.

The License in the podspec refers to the binary pointed to by the podspec.

**Comment by lucatorella** [comment]
I see, thanks for the clarification 👍
