### ISSUE TITLE
FirebaseMessageing Application Startup  Cash:[NSError messagingErrorWithCode:failureReason:]: unrecognized selector sent to class 0x1dfc727b8'

### ISSUE THREAD

**Issue by ws745630** [firebase/firebase-ios-sdk#13028]
### Description

When I imported the framework, I crashed when I started the application. The crash log is as follows. 
`
'+[NSError messagingErrorWithCode:failureReason:]: unrecognized selector sent to class 0x1dfc727b8'
`
Here's` the SDK that I use in my App
<img width="312" alt="企业微信截图_a30a8015-85a3-4f8a-bce9-666da971d1cb" src="https://github.com/firebase/firebase-ios-sdk/assets/17795164/931c41c5-747d-4871-b7bc-e3c90ebb86a1">

I have tried SDK 4.23.0 to 4.24 with this problem, may I ask which libraries I have omitted

### Firebase SDK Version

10.23.0

### Xcode Version

15.2

### Installation Method

Zip

### Firebase Product(s)

Messaging

### Targeted Platforms

iOS

### Relevant Log Output

```shell
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSError messagingErrorWithCode:failureReason:]: unrecognized selector sent to class 0x1dfc727b8'
*** First throw call stack:
(0x18ea1e678 0x186ccfc80 0x18eaaee84 0x18e963d88 0x18eaa4950 0x10449525c 0x1052d0f50 0x1052d2b34 0x1052e2fec 0x1052e2ba0 0x18e968f9c 0x18e965ca8 0x18e9653f8 0x1d1eeb4f8 0x190d8b8a0 0x190d8aedc 0x1044509d8 0x1b16b2dcc)
libc++abi: terminating due to uncaught exception of type NSException
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
It looks like you missed the instruction about adding the `-ObjC` option. Please see the details in the zip README.
