### ISSUE TITLE
GoogleAppTransport issue, using Carthage

### ISSUE THREAD

**Issue by amnmh2** [firebase/firebase-ios-sdk#13032]
### Description

I am ebedding Firebase using carthage in my framework. Framework is embeded in my application.
Apple denys app saying GoogleAppTransport in my framework is missing signature.

Carthge 0.39.1, xCode15.3.

When embedding Firebase directly in my app (not in framework), Apple does not complain.
Is there any chance I can embed Firebase in my framework, and apple doesn not complain in main project?

I have also tried to import Firebase manually in my framework, but Apple then complains about FirebaseCrashlytics.

### Firebase SDK Version

10.25

### Xcode Version

15.3

### Installation Method

Carthage

### Firebase Product(s)

Analytics, Crashlytics, Messaging

### Targeted Platforms

iOS

### Relevant Log Output

```shell
ITMS-91065: Missing signature - Your app includes �€œFrameworks/RAMEWORKNAME.framework/RAMEWORKNAME�€, which includes GoogleDataTransport, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. If a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a signature file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a signature. For details about verifying the code signature for a third-party SDK, visit:


ITMS-91065: Missing signature - Your app includes �€œFrameworks/FRAMEWORKNAME.framework/FRAMEWORKNAME�€, which includes FirebaseCrashlytics, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. If a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a signature file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a signature. For details about verifying the code signature for a third-party SDK, visit:


I am using following in Cartfile:
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashlyticsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseMessagingBinary.json"
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment]
Hi @amnmh2, when embedding Firebase XCframeworks into your framework, is there an option to _embed without signing_?

**Comment by amnmh2** [comment]
Hi @ncooke3 , yes, that option is already set for Firebase XCframeworks.

This works ok if Adding Firebase in simple project (using Carthage), but when embedding into Framework that embeddes Firebase using Carhage, and adding mentioned Framework into another project, we recieve that GoogleDataTransport is missing signature.

**Comment by ncooke3** [comment]
Thanks, did you try embedding Firebase into another framework and using _embed **and sign**_? 

In Xcode 15, Apple does some things behind the scenes when embedding frameworks so it's hard to pinpoint the right way for more complex cases like this.

**Comment by amnmh2** [comment]
I have tried Embed and sign in framework, but. when validating for store, I receive: No architectures in the binary. Lipo failed to detect any architectures in the bundle executable.

When using DO not embbed in framework, Store returns missing signature for GoogleDataTransport.

Same in another framework.

**Comment by amnmh2** [comment]
I have tried to use Swift Package Manager, and it is all same.
I have embedded Firebase in Framework using SPM. Framework is embedded into the project (build using Carthage).
Apple says FirebaseCrashlytics is missing signature.

**Comment by paulb777** [comment]
@amnmh2 Embedding named frameworks could be contrary to Apple policy. It could be worth checking on an Apple forum or Apple feedback.

**Comment by amnmh2** [comment]
I've endded up adding Firebase in main project, and removing from framework. Will contact Apple as well.

**Comment by paulb777** [comment]
Going to close. We can reopen if there is something for Firebase to address.
