### ISSUE TITLE
I want to downgrade the Firebase sdk

### ISSUE THREAD

**Issue by ilyon** [firebase/firebase-ios-sdk#13039]
### Description

Previously, I was using version 8.14.0 of Firebase. When I upgraded Firebase to 10.25.0, the dependent library AppAuth also got upgraded. After the upgrade, a crash occurred in AppAuth. Due to the urgency of the issue, I want to quickly resolve it. I am now considering downgrading Firebase back to version 8.14.0. Will there be any issues with this downgrade, such as compatibility problems with the data stored in Firebase? I hope to get your response. Thanks🙏🏻!

### Firebase SDK Version

10.25.0

### Xcode Version

15.4

### Installation Method

CocoaPods

### Firebase Product(s)

All

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
We don't test downgrading. 

There may be a few issues, so I would recommend testing your app. For data stored in Firebase, I would suspect all the products would be fine except possibly Firestore. However, multiple products may have issues retrieving data encoded and stored on device.

**Comment by dconeybe** [comment]
If you don't have persistence enabled for Firestore by calling `enableIndexedDbPersistence()` then there is a good chance that the downgrade would be fine (for Firestore, anyways); however, if your app _does_ enable persistence then that downgrade would likely result in failure to read the persistent data, which you could probably work around by calling `clearIndexedDbPersistence()`. But, as @paulb777 mentioned, this is not a supported use case and we can only give best effort support for this.

**Comment by ilyon** [comment]
@paulb777 @dconeybe Thank you for your reply. We don't use Firestore. The data storage I mentioned refers to some data stored in the local sandbox of the device by multiple Firebase products. According to @paulb777 , there may be problems here.

**Comment by paulb777** [comment]
I'm going to close since we don't have plans to officially support backversioning, but feel free to continue the conversation
