### ISSUE TITLE
Firebase Authentication "survives" uninstall and reinstall

### ISSUE THREAD

**Issue by dkbast** [firebase/firebase-ios-sdk#13049]
### Description

This issue happens with the flutter firebase plugin, which to my understanding is based on this native implementation.

When uninstalling an app where a user is authenticated using firebase auth (e.g. email + pw) and reinstalls the app, the user is directly signed in with the old credentials.

Expected behaviour:
When uninstalling the app, the credentials are also wiped. "Nobody" logs out before uninstalling an app. And especially in cases where the user want to avoid somebody else gaining access to their account and "just uninstalls" the app thats a huge red flag.

This has already been discussed here:
https://github.com/firebase/flutterfire/issues/4661 but no solution has been found - the issue was closed with just updating the docs saying that this can happen, but thats not a good fix for the user.

### Firebase SDK Version

flutterfire core 2.24.2, auth 4.15.3

### Xcode Version

15.1

### Installation Method

N/A

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
Some ideas for a workaround or solution if it's decided to change this behavior from https://forums.developer.apple.com/forums/thread/36442

**Comment by jesus-mg-ios** [comment]
IMHO this is the behavior expected, I mean, if users want to be logged out, they must do the action.
If you want to solve this issue in your particular case I would try to flush the keychain the first time you open the app after reinstalling it.
