### ISSUE TITLE
[FR]: Support FIRAppCheckTokenProtocol to remove FIRAppCheckToken not available in Interop error

### ISSUE THREAD

**Issue by allyligoogle** [firebase/firebase-ios-sdk#13041]
### Description

We get an error with the token request API in FIRAppCheckProtocol because the FIRAppCheckToken class is in not in the Interop SDK.

### Firebase Product(s)

App Check

**Comment by andrewheard** [comment]
Context: https://github.com/firebase/firebase-ios-sdk/pull/11864 added [`FIRAppCheckProtocol`](https://github.com/firebase/firebase-ios-sdk/blob/02d963ce64a2f2187a058a3746e9ea8fa4ace986/FirebaseAppCheck/Interop/Public/FirebaseAppCheckInterop/FIRAppCheckProtocol.h#L23-L56) and [`FIRAppCheck`](https://github.com/firebase/firebase-ios-sdk/blob/02d963ce64a2f2187a058a3746e9ea8fa4ace986/FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRAppCheck.h#L41) conforms to it _but_ the `FIRAppCheckToken` returned in https://github.com/firebase/firebase-ios-sdk/blob/02d963ce64a2f2187a058a3746e9ea8fa4ace986/FirebaseAppCheck/Interop/Public/FirebaseAppCheckInterop/FIRAppCheckProtocol.h#L40-L42

is only available in the FirebaseAppCheck SDK. `FIRAppCheckToken` is [forward declared](https://github.com/firebase/firebase-ios-sdk/blob/02d963ce64a2f2187a058a3746e9ea8fa4ace986/FirebaseAppCheck/Interop/Public/FirebaseAppCheckInterop/FIRAppCheckProtocol.h#L19) in the `FIRAppCheckProtocol` so it compiles but integrators can't inspect the [`token`](https://github.com/firebase/firebase-ios-sdk/blob/02d963ce64a2f2187a058a3746e9ea8fa4ace986/FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRAppCheckToken.h#L25-L26) without the class definition.

Proposal: Add a new protocol `FIRAppCheckTokenProtocol` that [`FIRAppCheckToken`](https://github.com/firebase/firebase-ios-sdk/blob/02d963ce64a2f2187a058a3746e9ea8fa4ace986/FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRAppCheckToken.h#L23) conforms to and use that type in `FIRAppCheckProtocol` instead. Working sample in https://github.com/firebase/firebase-ios-sdk/pull/13035.

Next Steps: API review and tests
