### ISSUE TITLE
The signature cannot be verified error on v10.24.0 when using Azure Artifacts to download and integrate

### ISSUE THREAD

**Issue by suganrajs** [firebase/firebase-ios-sdk#13050]
### Description

Team,

I'm using Firebase iOS SDK v10.22.0 and when trying to upgrade to latest v10.24.0 getting an error as "The signature cannot be verified". I'm using Azure Artifacts to upload .xcframeworks and have a script to download it.  

It works if I download .xcframeworks and add manually to the project.

Same issue as 
[The Code signature validation failed on v10.24.0 #12740
](https://github.com/firebase/firebase-ios-sdk/issues/12740)
https://github.com/firebase/firebase-ios-sdk/issues/12838

Note: 
I have tried upgrading to V10.27.0(latest) but still not working.
![Screenshot 2024-06-03 at 4 24 56 PM](https://github.com/firebase/firebase-ios-sdk/assets/168576535/57bb5852-411c-4dda-bc83-87b0a8b90019)
![Screenshot 2024-06-03 at 4 25 14 PM](https://github.com/firebase/firebase-ios-sdk/assets/168576535/2c870ca5-6d24-4bdc-bed9-fe2fbce56f18)

![Screenshot 2024-06-03 at 4 56 36 PM](https://github.com/firebase/firebase-ios-sdk/assets/168576535/1ec85d8c-cd59-49d9-b1d6-a85b874738a2)
![Screenshot 2024-06-03 at 4 57 04 PM](https://github.com/firebase/firebase-ios-sdk/assets/168576535/2f6d41b2-644a-4523-8341-1ced4f5f0699)

### Firebase SDK Version

10.24.0

### Xcode Version

15.4

### Installation Method

Zip

### Firebase Product(s)

AB Testing, Analytics, Remote Config

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
This sounds like an issue with the Azure Artifacts workflow, so it's not clear we can do anything to help.

stackoverflow or an Azure channel might be a better place to report.

**Comment by suganrajs** [comment]
@paulb777 The Older version of SDK working without any issues through Azure Artifacts. It only happens after Firebase enabled code signing in v 10.24.0. Thanks for the suggestion I'll check in Azure channel as well
