### ISSUE TITLE
[Firebase 11] Revert #13062 once 10.29.0 releases

### ISSUE THREAD

**Issue by ncooke3** [firebase/firebase-ios-sdk#13063]
### Description

See TODO comment added in #13062

### Firebase SDK Version

10.28.0

### Xcode Version

15.2

### Installation Method

N/A

### Firebase Product(s)

AB Testing

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
Updated to 10.29.0 now that we plan to do 10.29.0 before 11.0.0

**Comment by ncooke3** [comment]
Already done in https://github.com/firebase/firebase-ios-sdk/commit/d05cd88315f4f4173a685cfd6ef46ba20748fcca
