### ISSUE TITLE
Fix deprecated keyWindow usage in Performance

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#13067]
### Description

 /Users/runner/work/firebase-ios-sdk/firebase-ios-sdk/FirebasePerformance/Sources/Instrumentation/UIKit/FPRUIViewControllerInstrument.m:74:85: warning: 'keyWindow' is deprecated: first deprecated in iOS 13.0 - Should not be used for applications that support multiple scenes as it returns a key window across all connected scenes [-Wdeprecated-declarations]

### Reproducing the issue

Build in the release-11.0 branch

### Firebase SDK Version

11.0

### Xcode Version

15.4

### Installation Method

CocoaPods

### Firebase Product(s)

Performance

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by themiswang** [comment]
Merged the code, gonna close this ticket!
