### ISSUE TITLE
Update Firebase Pods break Boring SSL and generate build error

### ISSUE THREAD

**Issue by Rovel** [firebase/firebase-ios-sdk#1309]
My Xcode app can't build anymore after a pod update Firebase to get the latest
Swift 4
Xcode: Version 9.3.1 (9E501)

**Error:**
<img width="1440" alt="screen shot 2018-05-22 at 14 02 42" src="https://user-images.githubusercontent.com/2469500/40378080-e5f6052c-5dc8-11e8-9a88-1f8ffcdfbcec.png">

**Efforts to solve** 
- [x] Clean project - no result
- [x] Update pods again - no result
- [x] Edit/Force Podfile to use BoringSSL (~> 9.1) - works, issue can have a workaround but impacts need to be  evaluated.

I have the following pods in my Podfile
**Pods**
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'SDWebImage'

**Pod Versions**
PODS:
  - BoringSSL (10.0.2):
    - BoringSSL/Implementation (= 10.0.2)
    - BoringSSL/Interface (= 10.0.2)
  - BoringSSL/Implementation (10.0.2):
    - BoringSSL/Interface (= 10.0.2)
  - BoringSSL/Interface (10.0.2)
  - Firebase/Auth (5.0.1):
    - Firebase/CoreOnly
    - FirebaseAuth (= 5.0.0)
  - Firebase/Core (5.0.1):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 5.0.0)
  - Firebase/CoreOnly (5.0.1):
    - FirebaseCore (= 5.0.1)
  - Firebase/Database (5.0.1):
    - Firebase/CoreOnly
    - FirebaseDatabase (= 5.0.0)
  - Firebase/Firestore (5.0.1):
    - Firebase/CoreOnly
    - FirebaseFirestore (= 0.12.1)
  - Firebase/Messaging (5.0.1):
    - Firebase/CoreOnly
    - FirebaseMessaging (= 3.0.0)
  - Firebase/Storage (5.0.1):
    - Firebase/CoreOnly
    - FirebaseStorage (= 3.0.0)
  - FirebaseAnalytics (5.0.0):
    - FirebaseCore (~> 5.0)
    - FirebaseInstanceID (~> 3.0)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - nanopb (~> 0.3)
  - FirebaseAuth (5.0.0):
    - FirebaseCore (~> 5.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseCore (5.0.1):
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
  - FirebaseDatabase (5.0.0):
    - FirebaseCore (~> 5.0)
    - leveldb-library (~> 1.18)
  - FirebaseFirestore (0.12.1):
    - FirebaseCore (~> 5.0)
    - FirebaseFirestore/abseil-cpp (= 0.12.1)
    - gRPC-ProtoRPC (~> 1.0)
    - leveldb-library (~> 1.18)
    - Protobuf (~> 3.1)
  - FirebaseFirestore/abseil-cpp (0.12.1):
- FirebaseCore (~> 5.0)
    - gRPC-ProtoRPC (~> 1.0)
    - leveldb-library (~> 1.18)
    - Protobuf (~> 3.1)
  - FirebaseInstanceID (3.0.0):
    - FirebaseCore (~> 5.0)
  - FirebaseMessaging (3.0.0):
    - FirebaseCore (~> 5.0)
    - FirebaseInstanceID (~> 3.0)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - Protobuf (~> 3.1)
  - FirebaseStorage (3.0.0):
    - FirebaseCore (~> 5.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - GoogleToolboxForMac/Defines (2.1.4)
  - GoogleToolboxForMac/Logger (2.1.4):
    - GoogleToolboxForMac/Defines (= 2.1.4)
  - "GoogleToolboxForMac/NSData+zlib (2.1.4)":
    - GoogleToolboxForMac/Defines (= 2.1.4)
  - gRPC (1.12.0):
    - gRPC-RxLibrary (= 1.12.0)
    - gRPC/Main (= 1.12.0)
  - gRPC-Core (1.12.0):
    - gRPC-Core/Implementation (= 1.12.0)
    - gRPC-Core/Interface (= 1.12.0)
  - gRPC-Core/Implementation (1.12.0):
    - BoringSSL (~> 10.0)
    - gRPC-Core/Interface (= 1.12.0)
    - nanopb (~> 0.3)
  - gRPC-Core/Interface (1.12.0)
  - gRPC-ProtoRPC (1.12.0):
    - gRPC (= 1.12.0)
    - gRPC-RxLibrary (= 1.12.0)
    - Protobuf (~> 3.0)
  - gRPC-RxLibrary (1.12.0)
  - gRPC/Main (1.12.0):
    - gRPC-Core (= 1.12.0)
    - gRPC-RxLibrary (= 1.12.0)
  - GTMSessionFetcher/Core (1.1.15)
  - leveldb-library (1.20)
  - nanopb (0.3.8):
    - nanopb/decode (= 0.3.8)
    - nanopb/encode (= 0.3.8)
  - nanopb/decode (0.3.8)
  - nanopb/encode (0.3.8)
  - Protobuf (3.5.0)
- gRPC-RxLibrary (1.12.0)
  - gRPC/Main (1.12.0):
    - gRPC-Core (= 1.12.0)
    - gRPC-RxLibrary (= 1.12.0)
  - GTMSessionFetcher/Core (1.1.15)
  - leveldb-library (1.20)
  - nanopb (0.3.8):
    - nanopb/decode (= 0.3.8)
    - nanopb/encode (= 0.3.8)
  - nanopb/decode (0.3.8)
  - nanopb/encode (0.3.8)
  - Protobuf (3.5.0)
  - SDWebImage (4.3.3):
    - SDWebImage/Core (= 4.3.3)
  - SDWebImage/Core (4.3.3)

**Comment by wilhuff** [comment]
I haven't been able to reproduce this yet, though I'm on Xcode 9.3.

What's the location of the other declaration of that function?

**Comment by Rovel** [comment]
no, just a standard xcode single page app, in a brand new project it wont happen. I don't have nothing special on this project that builds the error, is there a chance that In app purchase or other https calls that maybe use open ssl is conflicting with boring ssl?

**Comment by baolocdo** [comment]
For Firebase Analytics: there is no In-app purchase calls or https call that use openSSL

**Comment by Rovel** [comment]
since the last update for firebase 5.2.0 and boring ssl 10.0.5 the bug disappeared.

thanks
