### ISSUE TITLE
didReceiveRemoteNotification is not called 

### ISSUE THREAD

**Issue by DemetAkyolKapar** [firebase/firebase-ios-sdk#13108]
### Description

We received the June 20, 2024 the legacy Firebase Cloud Messaging (FCM) APIs will be discontinued email. 
<dependency>
 <groupId>com.google.firebase</groupId>
 <artifactId>firebase-admin</artifactId>
 <version>8.1.0</version>
 </dependency>
we added this to the backend side and    we updated pod version to pod 'Firebase/Messaging' , '10.24.0'

In this case, when the pod version is notified with the old API, func application( _ application: UIApplication,
 didReceiveRemoteNotification userInfo: [AnyHashable: Any],
 fetchCompletionHandler handler: @escaping (UIBackgroundFetchResult) -> Void)
is being called
but It is not called in its new state

### Firebase SDK Version

10.24.0

### Xcode Version

15.0.1 

### Installation Method

CocoaPods

### Firebase Product(s)

Messaging

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by DemetAkyolKapar** [comment]
{"message":{"notification":{"title":"Test","body":"Feed"},"data":{"message":"Feed"},"apns":{"headers":{"apns-priority":"10"},"payload":{"aps":{"badge":1,"collapse_key":"FCM_Sender","content_available":true,"time_to_live":90,"sound":"default"}}},"token":"c........"}}
Data sent to mobile is like this

**Comment by rizafran** [comment]
Thanks for reporting, @DemetAkyolKapar. May I know if you tapped the notification so the [didReceiveRemoteNotification](https://firebase.google.com/docs/cloud-messaging/ios/receive#handle_silent_push_notifications) will be called? Also, could you provide your `Podfile.lock` file?

**Comment by DemetAkyolKapar** [comment]
@rizafran  didReceiveRemoteNotification was not called when I tapped notification ,didReceiveRemoteNotification never called.
Podfile.lock :
PODS:
  - Alamofire (5.2.0)
  - AZSClient (0.2.6)
  - BSImagePicker (3.3.1)
  - Charts (3.2.1):
    - Charts/Core (= 3.2.1)
  - Charts/Core (3.2.1)
  - Firebase/Analytics (10.24.0):
    - Firebase/Core
  - Firebase/Core (10.24.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 10.24.0)
  - Firebase/CoreOnly (10.24.0):
    - FirebaseCore (= 10.24.0)
  - Firebase/Crashlytics (10.24.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 10.24.0)
  - Firebase/Messaging (10.24.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 10.24.0)
  - FirebaseAnalytics (10.24.0):
    - FirebaseAnalytics/AdIdSupport (= 10.24.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (10.24.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleAppMeasurement (= 10.24.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - FirebaseCore (10.24.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.12)
    - GoogleUtilities/Logger (~> 7.12)
  - FirebaseCoreExtension (10.24.0):
    - FirebaseCore (~> 10.0)
  - FirebaseCoreInternal (10.24.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseCrashlytics (10.24.0):
    - FirebaseCore (~> 10.5)
    - FirebaseInstallations (~> 10.0)
    - FirebaseRemoteConfigInterop (~> 10.23)
    - FirebaseSessions (~> 10.5)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.8)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesObjC (~> 2.1)
  - FirebaseInstallations (10.24.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)
  - FirebaseMessaging (10.24.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.3)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Reachability (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - FirebaseRemoteConfigInterop (10.24.0)
  - FirebaseSessions (10.24.0):
    - FirebaseCore (~> 10.5)
    - FirebaseCoreExtension (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.10)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesSwift (~> 2.1)
  - GoogleAppMeasurement (10.24.0):
    - GoogleAppMeasurement/AdIdSupport (= 10.24.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - GoogleAppMeasurement/AdIdSupport (10.24.0):
    - GoogleAppMeasurement/WithoutAdIdSupport (= 10.24.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - GoogleAppMeasurement/WithoutAdIdSupport (10.24.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - GoogleDataTransport (9.4.1):
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleMaps/Base (2.4.0)
  - GooglePlaces (2.4.0):
    - GoogleMaps/Base (= 2.4.0)
  - GoogleUtilities/AppDelegateSwizzler (7.13.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
    - GoogleUtilities/Privacy
  - GoogleUtilities/Environment (7.13.0):
    - GoogleUtilities/Privacy
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/Logger (7.13.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Privacy
  - GoogleUtilities/MethodSwizzler (7.13.0):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/Network (7.13.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Privacy
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.13.0)":
    - GoogleUtilities/Privacy
  - GoogleUtilities/Privacy (7.13.0)
  - GoogleUtilities/Reachability (7.13.0):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/UserDefaults (7.13.0):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - IQKeyboardManagerSwift (6.5.11)
  - MaterialComponents (36.0.0):
    - MaterialComponents/ActivityIndicator (= 36.0.0)
    - MaterialComponents/AnimationTiming (= 36.0.0)
    - MaterialComponents/AppBar (= 36.0.0)
    - MaterialComponents/BottomAppBar (= 36.0.0)
    - MaterialComponents/BottomSheet (= 36.0.0)
    - MaterialComponents/ButtonBar (= 36.0.0)
    - MaterialComponents/Buttons (= 36.0.0)
    - MaterialComponents/CollectionCells (= 36.0.0)
    - MaterialComponents/CollectionLayoutAttributes (= 36.0.0)
    - MaterialComponents/Collections (= 36.0.0)
    - MaterialComponents/Dialogs (= 36.0.0)
    - MaterialComponents/FeatureHighlight (= 36.0.0)
    - MaterialComponents/FlexibleHeader (= 36.0.0)
    - MaterialComponents/HeaderStackView (= 36.0.0)
    - MaterialComponents/Ink (= 36.0.0)
    - MaterialComponents/MaskedTransition (= 36.0.0)
    - MaterialComponents/NavigationBar (= 36.0.0)
    - MaterialComponents/OverlayWindow (= 36.0.0)
    - MaterialComponents/PageControl (= 36.0.0)
    - MaterialComponents/Palettes (= 36.0.0)
    - MaterialComponents/private (= 36.0.0)
    - MaterialComponents/ProgressView (= 36.0.0)
    - MaterialComponents/ShadowElevations (= 36.0.0)
    - MaterialComponents/ShadowLayer (= 36.0.0)
    - MaterialComponents/Slider (= 36.0.0)
    - MaterialComponents/Snackbar (= 36.0.0)
    - MaterialComponents/Tabs (= 36.0.0)
    - MaterialComponents/TextFields (= 36.0.0)
    - MaterialComponents/Themes (= 36.0.0)
    - MaterialComponents/Typography (= 36.0.0)
  - MaterialComponents/ActivityIndicator (36.0.0):
    - MaterialComponents/ActivityIndicator/ColorThemer (= 36.0.0)
    - MaterialComponents/ActivityIndicator/Component (= 36.0.0)
    - MaterialComponents/Palettes
    - MaterialComponents/private/Application
    - MaterialComponents/private/RTL
  - MaterialComponents/ActivityIndicator/ColorThemer (36.0.0):
    - MaterialComponents/ActivityIndicator/Component
    - MaterialComponents/Palettes
    - MaterialComponents/private/Application
    - MaterialComponents/private/RTL
    - MaterialComponents/Themes
  - MaterialComponents/ActivityIndicator/Component (36.0.0):
    - MaterialComponents/Palettes
    - MaterialComponents/private/Application
    - MaterialComponents/private/RTL
  - MaterialComponents/AnimationTiming (36.0.0)
  - MaterialComponents/AppBar (36.0.0):
    - MaterialComponents/AppBar/ColorThemer (= 36.0.0)
    - MaterialComponents/AppBar/Component (= 36.0.0)
  - MaterialComponents/AppBar/ColorThemer (36.0.0):
    - MaterialComponents/AppBar/Component
    - MaterialComponents/Themes
  - MaterialComponents/AppBar/Component (36.0.0):
    - MaterialComponents/FlexibleHeader
    - MaterialComponents/HeaderStackView
    - MaterialComponents/NavigationBar
    - MaterialComponents/private/Application
    - MaterialComponents/private/Icons/ic_arrow_back
    - MaterialComponents/private/RTL
    - MaterialComponents/ShadowElevations
    - MaterialComponents/ShadowLayer
    - MaterialComponents/Typography
  - MaterialComponents/BottomAppBar (36.0.0):
    - MaterialComponents/Buttons
    - MaterialComponents/NavigationBar
    - MaterialComponents/private/Math
    - MaterialComponents/private/RTL
  - MaterialComponents/BottomSheet (36.0.0):
    - MaterialComponents/private/KeyboardWatcher
    - MaterialComponents/private/Math
  - MaterialComponents/ButtonBar (36.0.0):
    - MaterialComponents/ButtonBar/ColorThemer (= 36.0.0)
    - MaterialComponents/ButtonBar/Component (= 36.0.0)
    - MaterialComponents/Buttons
    - MaterialComponents/private/RTL
  - MaterialComponents/ButtonBar/ColorThemer (36.0.0):
    - MaterialComponents/ButtonBar/Component
    - MaterialComponents/Buttons
    - MaterialComponents/NavigationBar/Component
    - MaterialComponents/private/RTL
    - MaterialComponents/Themes
  - MaterialComponents/ButtonBar/Component (36.0.0):
    - MaterialComponents/Buttons
    - MaterialComponents/private/RTL
  - MaterialComponents/Buttons (36.0.0):
    - MaterialComponents/Buttons/ColorThemer (= 36.0.0)
    - MaterialComponents/Buttons/Component (= 36.0.0)
    - MaterialComponents/Buttons/TitleColorAccessibilityMutator (= 36.0.0)
    - MaterialComponents/Ink
    - MaterialComponents/private/Math
    - MaterialComponents/ShadowElevations
    - MaterialComponents/ShadowLayer
    - MaterialComponents/Typography
    - MDFTextAccessibility
  - MaterialComponents/Buttons/ColorThemer (36.0.0):
    - MaterialComponents/Buttons/Component
    - MaterialComponents/Ink
    - MaterialComponents/private/Math
    - MaterialComponents/ShadowElevations
    - MaterialComponents/ShadowLayer
    - MaterialComponents/Themes
    - MaterialComponents/Typography
    - MDFTextAccessibility
  - MaterialComponents/Buttons/Component (36.0.0):
    - MaterialComponents/Ink
    - MaterialComponents/private/Math
    - MaterialComponents/ShadowElevations
    - MaterialComponents/ShadowLayer
    - MaterialComponents/Typography
    - MDFTextAccessibility
  - MaterialComponents/Buttons/TitleColorAccessibilityMutator (36.0.0):
    - MaterialComponents/Buttons/Component
    - MaterialComponents/Ink
    - MaterialComponents/private/Math
    - MaterialComponents/ShadowElevations
    - MaterialComponents/ShadowLayer
    - MaterialComponents/Typography
    - MDFTextAccessibility
  - MaterialComponents/CollectionCells (36.0.0):
    - MaterialComponents/CollectionLayoutAttributes
    - MaterialComponents/Ink
    - MaterialComponents/Palettes
    - MaterialComponents/private/Icons/ic_check
    - MaterialComponents/private/Icons/ic_check_circle
    - MaterialComponents/private/Icons/ic_chevron_right
    - MaterialComponents/private/Icons/ic_info
    - MaterialComponents/private/Icons/ic_radio_button_unchecked
    - MaterialComponents/private/Icons/ic_reorder
    - MaterialComponents/private/Math
    - MaterialComponents/private/RTL
    - MaterialComponents/Typography
  - MaterialComponents/CollectionLayoutAttributes (36.0.0)
  - MaterialComponents/Collections (36.0.0):
    - MaterialComponents/CollectionCells
    - MaterialComponents/CollectionLayoutAttributes
    - MaterialComponents/Ink
    - MaterialComponents/ShadowElevations
    - MaterialComponents/ShadowLayer
    - MaterialComponents/Typography
  - MaterialComponents/Dialogs (36.0.0):
    - MaterialComponents/Dialogs/ColorThemer (= 36.0.0)
    - MaterialComponents/Dialogs/Component (= 36.0.0)
  - MaterialComponents/Dialogs/ColorThemer (36.0.0):
    - MaterialComponents/Dialogs/Component
    - MaterialComponents/Themes
  - MaterialComponents/Dialogs/Component (36.0.0):
    - MaterialComponents/Buttons
    - MaterialComponents/private/KeyboardWatcher
    - MaterialComponents/private/RTL
    - MaterialComponents/ShadowElevations
    - MaterialComponents/ShadowLayer
  - MaterialComponents/FeatureHighlight (36.0.0):
    - MaterialComponents/FeatureHighlight/ColorThemer (= 36.0.0)
    - MaterialComponents/FeatureHighlight/Component (= 36.0.0)
  - MaterialComponents/FeatureHighlight/ColorThemer (36.0.0):
    - MaterialComponents/FeatureHighlight/Component
    - MaterialComponents/Themes
  - MaterialComponents/FeatureHighlight/Component (36.0.0):
    - MaterialComponents/private/Math
    - MaterialComponents/Typography
    - MDFTextAccessibility
  - MaterialComponents/FlexibleHeader (36.0.0):
    - MaterialComponents/FlexibleHeader/ColorThemer (= 36.0.0)
    - MaterialComponents/FlexibleHeader/Component (= 36.0.0)
    - MaterialComponents/private/Application
    - MDFTextAccessibility
  - MaterialComponents/FlexibleHeader/ColorThemer (36.0.0):
    - MaterialComponents/FlexibleHeader/Component
    - MaterialComponents/private/Application
    - MaterialComponents/Themes
    - MDFTextAccessibility
  - MaterialComponents/FlexibleHeader/Component (36.0.0):
    - MaterialComponents/private/Application
    - MDFTextAccessibility
  - MaterialComponents/HeaderStackView (36.0.0):
    - MaterialComponents/HeaderStackView/ColorThemer (= 36.0.0)
    - MaterialComponents/HeaderStackView/Component (= 36.0.0)
  - MaterialComponents/HeaderStackView/ColorThemer (36.0.0):
    - MaterialComponents/HeaderStackView/Component
    - MaterialComponents/Themes
  - MaterialComponents/HeaderStackView/Component (36.0.0)
  - MaterialComponents/Ink (36.0.0):
    - MaterialComponents/Ink/ColorThemer (= 36.0.0)
    - MaterialComponents/Ink/Component (= 36.0.0)
  - MaterialComponents/Ink/ColorThemer (36.0.0):
    - MaterialComponents/Ink/Component
    - MaterialComponents/Themes
  - MaterialComponents/Ink/Component (36.0.0)
  - MaterialComponents/MaskedTransition (36.0.0):
    - MotionAnimator (~> 1.0)
    - MotionInterchange (~> 1.0)
    - MotionTransitioning (~> 3.3)
  - MaterialComponents/NavigationBar (36.0.0):
    - MaterialComponents/NavigationBar/ColorThemer (= 36.0.0)
    - MaterialComponents/NavigationBar/Component (= 36.0.0)
  - MaterialComponents/NavigationBar/ColorThemer (36.0.0):
    - MaterialComponents/NavigationBar/Component
    - MaterialComponents/Themes
  - MaterialComponents/NavigationBar/Component (36.0.0):
    - MaterialComponents/ButtonBar/Component
    - MaterialComponents/private/Math
    - MaterialComponents/private/RTL
    - MaterialComponents/Typography
    - MDFTextAccessibility
  - MaterialComponents/OverlayWindow (36.0.0):
    - MaterialComponents/private/Application
  - MaterialComponents/PageControl (36.0.0):
    - MaterialComponents/PageControl/ColorThemer (= 36.0.0)
    - MaterialComponents/PageControl/Component (= 36.0.0)
  - MaterialComponents/PageControl/ColorThemer (36.0.0):
    - MaterialComponents/PageControl/Component
    - MaterialComponents/Themes
  - MaterialComponents/PageControl/Component (36.0.0)
  - MaterialComponents/Palettes (36.0.0)
  - MaterialComponents/private (36.0.0):
    - MaterialComponents/private/Application (= 36.0.0)
    - MaterialComponents/private/Icons (= 36.0.0)
    - MaterialComponents/private/KeyboardWatcher (= 36.0.0)
    - MaterialComponents/private/Math (= 36.0.0)
    - MaterialComponents/private/Overlay (= 36.0.0)
    - MaterialComponents/private/RTL (= 36.0.0)
    - MaterialComponents/private/ShapeLibrary (= 36.0.0)
    - MaterialComponents/private/Shapes (= 36.0.0)
    - MaterialComponents/private/ThumbTrack (= 36.0.0)
  - MaterialComponents/private/Application (36.0.0)
  - MaterialComponents/private/Icons (36.0.0):
    - MaterialComponents/private/Icons/Base (= 36.0.0)
    - MaterialComponents/private/Icons/ic_arrow_back (= 36.0.0)
    - MaterialComponents/private/Icons/ic_check (= 36.0.0)
    - MaterialComponents/private/Icons/ic_check_circle (= 36.0.0)
    - MaterialComponents/private/Icons/ic_chevron_right (= 36.0.0)
    - MaterialComponents/private/Icons/ic_info (= 36.0.0)
    - MaterialComponents/private/Icons/ic_radio_button_unchecked (= 36.0.0)
    - MaterialComponents/private/Icons/ic_reorder (= 36.0.0)
  - MaterialComponents/private/Icons/Base (36.0.0)
  - MaterialComponents/private/Icons/ic_arrow_back (36.0.0):
    - MaterialComponents/private/Icons/Base
  - MaterialComponents/private/Icons/ic_check (36.0.0):
    - MaterialComponents/private/Icons/Base
  - MaterialComponents/private/Icons/ic_check_circle (36.0.0):
    - MaterialComponents/private/Icons/Base
  - MaterialComponents/private/Icons/ic_chevron_right (36.0.0):
    - MaterialComponents/private/Icons/Base
  - MaterialComponents/private/Icons/ic_info (36.0.0):
    - MaterialComponents/private/Icons/Base
  - MaterialComponents/private/Icons/ic_radio_button_unchecked (36.0.0):
    - MaterialComponents/private/Icons/Base
  - MaterialComponents/private/Icons/ic_reorder (36.0.0):
    - MaterialComponents/private/Icons/Base
  - MaterialComponents/private/KeyboardWatcher (36.0.0):
    - MaterialComponents/private/Application
  - MaterialComponents/private/Math (36.0.0)
  - MaterialComponents/private/Overlay (36.0.0)
  - MaterialComponents/private/RTL (36.0.0)
  - MaterialComponents/private/ShapeLibrary (36.0.0):
    - MaterialComponents/private/Math
    - MaterialComponents/private/Shapes
  - MaterialComponents/private/Shapes (36.0.0):
    - MaterialComponents/private/Math
    - MaterialComponents/ShadowLayer
  - MaterialComponents/private/ThumbTrack (36.0.0):
    - MaterialComponents/Ink
    - MaterialComponents/private/Math
    - MaterialComponents/private/RTL
    - MaterialComponents/ShadowElevations
    - MaterialComponents/ShadowLayer
    - MaterialComponents/Typography
  - MaterialComponents/ProgressView (36.0.0):
    - MaterialComponents/ProgressView/ColorThemer (= 36.0.0)
    - MaterialComponents/ProgressView/Component (= 36.0.0)
  - MaterialComponents/ProgressView/ColorThemer (36.0.0):
    - MaterialComponents/ProgressView/Component
    - MaterialComponents/Themes
  - MaterialComponents/ProgressView/Component (36.0.0):
    - MaterialComponents/private/Math
    - MaterialComponents/private/RTL
  - MaterialComponents/ShadowElevations (36.0.0)
  - MaterialComponents/ShadowLayer (36.0.0):
    - MaterialComponents/ShadowElevations
  - MaterialComponents/Slider (36.0.0):
    - MaterialComponents/Slider/ColorThemer (= 36.0.0)
    - MaterialComponents/Slider/Component (= 36.0.0)
  - MaterialComponents/Slider/ColorThemer (36.0.0):
    - MaterialComponents/Slider/Component
    - MaterialComponents/Themes
  - MaterialComponents/Slider/Component (36.0.0):
    - MaterialComponents/private/ThumbTrack
  - MaterialComponents/Snackbar (36.0.0):
    - MaterialComponents/AnimationTiming
    - MaterialComponents/Buttons
    - MaterialComponents/OverlayWindow
    - MaterialComponents/private/Application
    - MaterialComponents/private/KeyboardWatcher
    - MaterialComponents/private/Overlay
    - MaterialComponents/Typography
  - MaterialComponents/Tabs (36.0.0):
    - MaterialComponents/Tabs/ColorThemer (= 36.0.0)
    - MaterialComponents/Tabs/Component (= 36.0.0)
  - MaterialComponents/Tabs/ColorThemer (36.0.0):
    - MaterialComponents/Tabs/Component
    - MaterialComponents/Themes
  - MaterialComponents/Tabs/Component (36.0.0):
    - MaterialComponents/AnimationTiming
    - MaterialComponents/Ink
    - MaterialComponents/private/Math
    - MaterialComponents/private/RTL
    - MaterialComponents/Typography
  - MaterialComponents/TextFields (36.0.0):
    - MaterialComponents/TextFields/ColorThemer (= 36.0.0)
    - MaterialComponents/TextFields/Component (= 36.0.0)
  - MaterialComponents/TextFields/ColorThemer (36.0.0):
    - MaterialComponents/TextFields/Component
    - MaterialComponents/Themes
  - MaterialComponents/TextFields/Component (36.0.0):
    - MaterialComponents/AnimationTiming
    - MaterialComponents/Palettes
    - MaterialComponents/private/Math
    - MaterialComponents/private/RTL
    - MaterialComponents/Typography
  - MaterialComponents/Themes (36.0.0)
  - MaterialComponents/Typography (36.0.0):
    - MaterialComponents/private/Application
  - MDFTextAccessibility (1.2.0)
  - MotionAnimator (1.1.2):
    - MotionInterchange
  - MotionInterchange (1.1.0)
  - MotionTransitioning (3.3.0)
  - nanopb (2.30910.0):
    - nanopb/decode (= 2.30910.0)
    - nanopb/encode (= 2.30910.0)
  - nanopb/decode (2.30910.0)
  - nanopb/encode (2.30910.0)
  - PromisesObjC (2.4.0)
  - PromisesSwift (2.4.0):
    - PromisesObjC (= 2.4.0)
  - Realm (2.8.3):
    - Realm/Headers (= 2.8.3)
  - Realm/Headers (2.8.3)
  - RealmSwift (2.8.3):
    - Realm (= 2.8.3)
  - Stripe (19.4.1)
  - SwiftyJSON (5.0.1)

DEPENDENCIES:
  - Alamofire (= 5.2.0)
  - AZSClient (= 0.2.6)
  - BSImagePicker (= 3.3.1)
  - Charts (= 3.2.1)
  - Firebase/Analytics (= 10.24.0)
  - Firebase/Crashlytics (= 10.24.0)
  - Firebase/Messaging (= 10.24.0)
  - GooglePlaces (= 2.4.0)
  - IQKeyboardManagerSwift (= 6.5.11)
  - MaterialComponents (= 36.0.0)
  - RealmSwift (= 2.8.3)
  - Stripe (= 19.4.1)
  - SwiftyJSON (= 5.0.1)

SPEC REPOS:
  trunk:
    - Alamofire
    - AZSClient
    - BSImagePicker
    - Charts
    - Firebase
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreExtension
    - FirebaseCoreInternal
    - FirebaseCrashlytics
    - FirebaseInstallations
    - FirebaseMessaging
    - FirebaseRemoteConfigInterop
    - FirebaseSessions
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleMaps
    - GooglePlaces
    - GoogleUtilities
    - IQKeyboardManagerSwift
    - MaterialComponents
    - MDFTextAccessibility
    - MotionAnimator
    - MotionInterchange
    - MotionTransitioning
    - nanopb
    - PromisesObjC
    - PromisesSwift
    - Realm
    - RealmSwift
    - Stripe
    - SwiftyJSON

SPEC CHECKSUMS:
  Alamofire: c1ca147559e730bfb2182c8c7aafbdd90a867987
  AZSClient: efd576cabf56f97e38cb1b614739f4b0c1906392
  BSImagePicker: 0fe04b574d4d6b81093785d2af6c26227efc8428
  Charts: bcdcf49d3806f864b794c18e8818015ba01f4a1f
  Firebase: 91fefd38712feb9186ea8996af6cbdef41473442
  FirebaseAnalytics: b5efc493eb0f40ec560b04a472e3e1a15d39ca13
  FirebaseCore: 11dc8a16dfb7c5e3c3f45ba0e191a33ac4f50894
  FirebaseCoreExtension: af5fd85e817ea9d19f9a2659a376cf9cf99f03c0
  FirebaseCoreInternal: bcb5acffd4ea05e12a783ecf835f2210ce3dc6af
  FirebaseCrashlytics: af38ea4adfa606f6e63fcc22091b61e7938fcf66
  FirebaseInstallations: 8f581fca6478a50705d2bd2abd66d306e0f5736e
  FirebaseMessaging: 4d52717dd820707cc4eadec5eb981b4832ec8d5d
  FirebaseRemoteConfigInterop: 6c349a466490aeace3ce9c091c86be1730711634
  FirebaseSessions: 2651b464e241c93fd44112f995d5ab663c970487
  GoogleAppMeasurement: f3abf08495ef2cba7829f15318c373b8d9226491
  GoogleDataTransport: 6c09b596d841063d76d4288cc2d2f42cc36e1e2a
  GoogleMaps: 8436ab5d1c25e36915b2f7416d0c8e3fa2e76c61
  GooglePlaces: aafe5990fa7951e98e078761bbdaaf236d7e0c65
  GoogleUtilities: d053d902a8edaa9904e1bd00c37535385b8ed152
  IQKeyboardManagerSwift: c7955c0bdbf7b2eb29bb7daaa44e3d90f55a9a85
  MaterialComponents: b8c1c51c79d1ff882a7bcbaba6db7a95c2e12d1c
  MDFTextAccessibility: 94098925e0853551c5a311ce7c1ecefbe297cdb6
  MotionAnimator: 5a1893b58fcf7a4664d81d69c9a09a0078c67e06
  MotionInterchange: b600100244df56c4f462bdacbcd11c44e6305d05
  MotionTransitioning: caaa488e0469d93f004793b96a2ed04447af808d
  nanopb: 438bc412db1928dac798aa6fd75726007be04262
  PromisesObjC: f5707f49cb48b9636751c5b2e7d227e43fba9f47
  PromisesSwift: 9d77319bbe72ebf6d872900551f7eeba9bce2851
  Realm: 3601ef091c8c499a31101d8563b991e75546cdce
  RealmSwift: 8183818515471b01a99abdd2970f8e4fd52b6f4a
  Stripe: 5914399ac5878056b985d56b409cb4bb1e7fc7e8
  SwiftyJSON: 2f33a42c6fbc52764d96f13368585094bfd8aa5e

PODFILE CHECKSUM: 64baf7704e9601d39b0d9b6923ff28d6b6385e06

COCOAPODS: 1.14.2
