### ISSUE TITLE
find: dSYM_directory: No such file or directory

### ISSUE THREAD

**Issue by JazKingX** [firebase/firebase-ios-sdk#13113]
### Description

My entire project was working fine until I updated Firebase to 10.27.0 & MacOS to 14.5 (I'm using Xcode 15.4). 

Now when trying to build the app now I get the following 

    Unable to read Google Service plist at path
    find: dSYM_directory: No such file or directory

I can still Build and Run for iOS and create an Archive for AppStoreConnect, but the Build fails for MacOS and VisionOS.

### Reproducing the issue

I have gone through the following steps. 

**Step 1)** 

- Install Firebase via SPM 
- Download google-service.plist from Firebase. 
- Copy to project folder, check target
- Add to Target > Build Settings > Copy Bundle Resources

**Errors:** 

    Unable to read Google Service plist at path /Users/approot/Shared/GoogleService-Info.plist

    find: dSYM_directory: No such file or directory

    Sandbox: cp(38870) deny(1) file-read-data /Users/approot/Shared/GoogleService-Info.plist

**Step 2) Ensure File Permissions:**

Verify that the GoogleService-Info.plist file has the correct permissions.

    chmod 644 /Users/approot/Shared/GoogleService-Info.plist

**Step 3) Create a new "Run Script Phase" to copy the file**

    bash
    Copy code
    SRC="${SRCROOT}/Shared/GoogleService-Info.plist"
    DEST="${BUILT_PRODUCTS_DIR}/${EXECUTABLE_NAME}.app/GoogleService-Info.plist"
    
    echo "Source path: $SRC"
    echo "Destination path: $DEST"
    
    if [ -f "$SRC" ]; then
        echo "Copying $SRC to $DEST"
        cp "$SRC" "$DEST"
        if [ $? -ne 0 ]; then
            echo "Error copying file."
            exit 1
        fi
    else
        echo "File not found: $SRC"
        exit 1
    fi

**Step 4) Check File System Access:**

Ensure that Xcode has full disk access. This can sometimes resolve sandbox-related issues.
Go to System Preferences > Security & Privacy > Privacy tab.
Select Full Disk Access and make sure Xcode is added to the list of applications with full disk access.

[![enter image description here][1]][1]

**Step 5) Check Derived Data:**

Delete the derived data folder.
Example Run Script Phase with Debugging

Here’s an enhanced version of the script to include more detailed debugging information:

    bash
    Copy code
    #!/bin/bash
    
    SRC="${SRCROOT}/Shared/GoogleService-Info.plist"
    DEST="${BUILT_PRODUCTS_DIR}/${EXECUTABLE_NAME}.app/GoogleService-Info.plist"
    
    echo "Source path: $SRC"
    echo "Destination path: $DEST"
    
    if [ -f "$SRC" ]; then
        echo "File exists. Copying $SRC to $DEST"
        cp "$SRC" "$DEST"
        if [ $? -ne 0 ]; then
            echo "Error copying file."
            exit 1
        fi
    else
        echo "File not found: $SRC"
        exit 1
    fi

**Step 6) Restart Xcode**

 - Re-indexed Project
 - Closed Xcode
 - deleted derived data
 - reopened the project to allow
 - Reinstalled packaages
 - Reinstall Xcode
 - Restart MacOS
 - Jump out a window

I've repeated these steps 250+ times, the file is in the project, it has the target checked, I've added to bundle resources, it literally worked before updating macOS. I even have the previous iOS build uploaded to AppStoreConnect, we just needed latest version and upload MacOS app. 

  [1]: https://i.sstatic.net/nyluagPN.png

### Firebase SDK Version

10.27.0

### Xcode Version

15.4

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, App Check, App Distribution, Authentication, Crashlytics, Database, DynamicLinks, Firestore, Functions, In-App Messaging, Installations, ML Model Downloader, Messaging, Performance, Remote Config, Storage, VertexAI, All, Infrastructure

### Targeted Platforms

macCatalyst, visionOS

### Relevant Log Output

```shell
Sandbox: cp(38870) deny(1) file-read-data /Users/approot/Shared/GoogleService-Info.plist
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
What is the reason for copying the `GoogleService-Info.plist` file?  The general practice is to add it to the relevant Xcode targets statically.
