### ISSUE TITLE
Swift Errors: Remove 'Code' suffix from Installations and App Check errors

### ISSUE THREAD

**Issue by ncooke3** [firebase/firebase-ios-sdk#13122]
### Description

This is pretty minor, but wanted to document it nonetheless.

The 'Code' suffix does not convey any salient information and diverges from other Firebase errors.

https://github.com/firebase/firebase-ios-sdk/blob/03189348b7798fe94b892a35883f1dc745814fe0/FirebaseInstallations/Source/Library/Public/FirebaseInstallations/FIRInstallationsErrors.h#L21-L35

https://github.com/firebase/firebase-ios-sdk/blob/03189348b7798fe94b892a35883f1dc745814fe0/FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRAppCheckErrors.h#L22-L39

### API Proposal

s/InstallationsErrorCode/InstallationsError/

s/AppCheckErrorCode/AppCheckError/

### Firebase Product(s)

App Check, Installations

**Comment by ncooke3** [comment]
I'm going to add this to the Firebase 11 milestone, mainly so it doesn't get lost and can roll into the next Firebase 12 milestone

**Comment by paulb777** [comment]
Not worth a breaking change for this - so closing for now.
