### ISSUE TITLE
Custom keys being mixed between non-fatal reports

### ISSUE THREAD

**Issue by luqas11** [firebase/firebase-ios-sdk#13124]
### Description

When sending two non fatal reports with the `recordError` method and some custom keys, the first report has the keys of the second in the Crashlytics dashboard.

For example, if I do the following sequence:
1. Set key `some_attribute` with value `value1`
2. Send a non-fatal exception with the `recordError` method
3. Set key `some_attribute` with value `value2`
4. Send another non-fatal exception with the `recordError` method
5. Restart the app

Both non-fatal errors are shown in the Crashlytics dashboard with the `some_attribute` key set to `value2`.

### Reproducing the issue

To make an isolated test of this issue, I cloned the [Firebase Quickstarts for iOS](https://github.com/firebase/quickstart-ios/tree/main) repo, set up the [Crashlytics example](https://github.com/firebase/quickstart-ios/tree/main/crashlytics), and modified the view to have two buttons that sends non-fatal exceptions with different keys:

```Swift
struct CrashButtonView: View {
  var body: some View {
    NavigationView {
        VStack {
            Button(action: {
                let crashlyticsReference = Crashlytics.crashlytics()
                crashlyticsReference.setCustomValue("value1", forKey: "some_attribute")
                crashlyticsReference.setCustomValue("value", forKey: "another_attribute")
                let error = NSError(domain: NSURLErrorDomain, code: -1001, userInfo: nil)
                Crashlytics.crashlytics().record(error: error)
            }) {
                Text("Send Error 1")
            }
            Button(action: {
                let crashlyticsReference = Crashlytics.crashlytics()
                crashlyticsReference.setCustomValue("value2", forKey: "some_attribute")
                let error = NSError(domain: NSURLErrorDomain, code: -1002, userInfo: nil)
                Crashlytics.crashlytics().record(error: error)
            }) {
                Text("Send Error 2")
            }
        }
      .navigationTitle("Crashlytics Example")
    }
  }
}
```

If I open the app, press the "Send Error 1" button, then press the "Send Error 2" button, and restart the app, I get the following reports on the Crashlytics dashboard:

#### For Error 1:
![image](https://github.com/firebase/firebase-ios-sdk/assets/30007451/0b4f9ddb-c668-4ae0-8a14-50926b447cac)

#### For Error 2:
![image](https://github.com/firebase/firebase-ios-sdk/assets/30007451/46b8489e-16b3-488f-a9e4-8ddecd356ea9)

As can be seen, both reports have the `some_attribute` key set to `value2`, despite it's being set to `value1` right before sending the first one.

I can't find this behavior documented in the [Customize crash reports](https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=ios) docs. Is this intentional, or an SDK bug?
Thanks in advance.

### Firebase SDK Version

10.27.0

### Xcode Version

15.0

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

{
  "pins" : [
    {
      "identity" : "abseil-cpp-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/abseil-cpp-binary.git",
      "state" : {
        "revision" : "748c7837511d0e6a507737353af268484e1745e2",
        "version" : "1.2024011601.1"
      }
    },
    {
      "identity" : "app-check",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/app-check.git",
      "state" : {
        "revision" : "076b241a625e25eac22f8849be256dfb960fcdfe",
        "version" : "10.19.1"
      }
    },
    {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk.git",
      "state" : {
        "revision" : "8bcaf973b1d84e119b7c7c119abad72ed460979f",
        "version" : "10.27.0"
      }
    },
    {
      "identity" : "googleappmeasurement",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleAppMeasurement.git",
      "state" : {
        "revision" : "70df02431e216bed98dd461e0c4665889245ba70",
        "version" : "10.27.0"
      }
    },
    {
      "identity" : "googledatatransport",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleDataTransport.git",
      "state" : {
        "revision" : "a637d318ae7ae246b02d7305121275bc75ed5565",
        "version" : "9.4.0"
      }
    },
    {
      "identity" : "googleutilities",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleUtilities.git",
      "state" : {
        "revision" : "57a1d307f42df690fdef2637f3e5b776da02aad6",
        "version" : "7.13.3"
      }
    },
    {
      "identity" : "grpc-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/grpc-binary.git",
      "state" : {
        "revision" : "e9fad491d0673bdda7063a0341fb6b47a30c5359",
        "version" : "1.62.2"
      }
    },
    {
      "identity" : "gtm-session-fetcher",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/gtm-session-fetcher.git",
      "state" : {
        "revision" : "0382ca27f22fb3494cf657d8dc356dc282cd1193",
        "version" : "3.4.1"
      }
    },
    {
      "identity" : "interop-ios-for-google-sdks",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/interop-ios-for-google-sdks.git",
      "state" : {
        "revision" : "2d12673670417654f08f5f90fdd62926dc3a2648",
        "version" : "100.0.0"
      }
    },
    {
      "identity" : "leveldb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/leveldb.git",
      "state" : {
        "revision" : "a0bc79961d7be727d258d33d5a6b2f1023270ba1",
        "version" : "1.22.5"
      }
    },
    {
      "identity" : "nanopb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/nanopb.git",
      "state" : {
        "revision" : "b7e1104502eca3a213b46303391ca4d3bc8ddec1",
        "version" : "2.30910.0"
      }
    },
    {
      "identity" : "promises",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/promises.git",
      "state" : {
        "revision" : "540318ecedd63d883069ae7f1ed811a2df00b6ac",
        "version" : "2.4.0"
      }
    },
    {
      "identity" : "reachability.swift",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/ashleymills/Reachability.swift.git",
      "state" : {
        "revision" : "7cbd73f46a7dfaeca079e18df7324c6de6d1834a",
        "version" : "5.2.3"
      }
    },
    {
      "identity" : "swift-protobuf",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-protobuf.git",
      "state" : {
        "revision" : "9f0c76544701845ad98716f3f6a774a892152bcb",
        "version" : "1.26.0"
      }
    }
  ],
  "version" : 2
}


```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reporting, @luqas11. I was able to get the same behavior when I tried the steps you shared. But if I clicked the button 1, restart the app, then clicked the button 2, and restart the app, I got the correct key values. It looks like Crashlytics gets the value of the last button being clicked. With this, I'll consult this to our engineer to confirm if it's intended.

**Comment by luqas11** [comment]
Thanks for the quick response!
I'm glad that my example steps were useful. I will wait for the confirmation then.

**Comment by rizafran** [comment]
Hi @luqas11, the Crashlytics engineer confirmed that this is an intended behavior. Unfortunately, there's a difference in behavior between Android and iOS in this, and Android can handle this but Apple doesn't. 

That being said, we would be happy to take this as a feature request.

**Comment by luqas11** [comment]
@rizafran ok, I understand.
I will create a feature request for the behavior unification then.
Thanks for the assistance in understanding the issue!
