### ISSUE TITLE
Callable function getting DEADLINE EXCEEDED

### ISSUE THREAD

**Issue by jesus-mg-ios** [firebase/firebase-ios-sdk#13131]
### Description

I'm getting random times an error when I call a callable function.
`Domain: com.firebase.functions.com.firebase.functions, 4 Code: 4 NSLocalizedDescription: DEADLINE EXCEEDED`

I have no more details about it, and I want to know which is the root cause of the error ... Seems to be a bug, Maybe is it on the iOS SDK side?

### Firebase SDK Version

10.25.0

### Xcode Version

15.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Functions

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @jesus-mg-ios, please file a ticket through our [support channel](https://firebase.google.com/support/) so the team could investigate your Firebase project and check what's causing the issue. Thanks.
