### ISSUE TITLE
My Mac Game was rejected because Google Sign in does web based login? Can I do anything other than removing Google on Mac?

### ISSUE THREAD

**Issue by andytriboletti** [firebase/firebase-ios-sdk#13146]
### Description

My Mac Game Open Space was rejected from TestFlight because it uses Google login, which does browser sign-in. Do I have to remove Google sign-in? I already have Apple sign-in as well as Google.

Guideline 4.0 - Design

The user is taken to the default web browser to sign in or register (Google) for an account, which provides a poor user experience.

Next Steps

To resolve this issue, revise the submission to enable users to sign in or register for an account in the app or extension.

The whole reason I added Google sign in on my TestFlight was that Apple sign in wouldn't work on my Mom's macbook air, while Google does.

### Firebase SDK Version

current

### Xcode Version

15.4

### Installation Method

CocoaPods

### Firebase Product(s)

Authentication

### Targeted Platforms

macOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by andytriboletti** [comment]
I am using FirebaseAuthUI

**Comment by paulb777** [comment]
Is the rejection due to Firebase Auth UI code or to Google Sign In code? If so, this issue might be better addressed on those issue trackers.

**Comment by andytriboletti** [comment]
> Is the rejection due to Firebase Auth UI code or to Google Sign In code? If so, this issue might be better addressed on those issue trackers.

I'm not sure. Can you please transfer the ticket to the one u think is right.

**Comment by ncooke3** [comment]
Hi @andytriboletti, I investigated and this issues belongs in the Google Sign In repo. Instead of moving it though, I will close it as there is an already an issue filed there about this: https://github.com/google/GoogleSignIn-iOS/issues/388

I recommend reading through it as some developers reported success after reaching out to Apple about the review feedback.
