### ISSUE TITLE
Some crashes with firebase sdk

### ISSUE THREAD

**Issue by Lingyj** [firebase/firebase-ios-sdk#1317]
I got some crashes with firebase sdk recently, here are some infomations. How to fix that?

the crashes list:
![375e26ad-55cf-4bc7-924d-bf84b974e386](https://user-images.githubusercontent.com/3283295/40400669-c5ad75ae-5e75-11e8-915e-f2fd97b8dfcd.png)
![b6532a3f-c3f0-4643-8993-8f67c2b0a067](https://user-images.githubusercontent.com/3283295/40400672-c83654bc-5e75-11e8-8f99-08474c9dfda9.png)
![73b26326-9447-47c5-ac4e-651adb400a2d](https://user-images.githubusercontent.com/3283295/40400673-ca5c7ad2-5e75-11e8-80d2-1860d93aef59.png)
![65281ed9-416f-4f50-b3f7-2d7019390e74](https://user-images.githubusercontent.com/3283295/40400775-4099f8c8-5e76-11e8-9420-f0a06e605755.png)

the details:
![aec1a151-8a23-4c74-867c-f9c996099d34](https://user-images.githubusercontent.com/3283295/40401019-3339806c-5e77-11e8-82a5-8e0e6cc54613.png)
![4d1509d7-127c-4fe2-82c7-b41b33bb9c96](https://user-images.githubusercontent.com/3283295/40401024-36a40088-5e77-11e8-8d7c-20fb2b0a9f67.png)
![a0820ed7-e32e-4391-a06f-1beccc31e436](https://user-images.githubusercontent.com/3283295/40401025-38c56532-5e77-11e8-947d-dc6c046b5150.png)
![5cbdea4b-043c-468a-a11d-217f75ee5f12](https://user-images.githubusercontent.com/3283295/40401027-3aa52220-5e77-11e8-9184-59c902bdcbf6.png)
![6ae7b460-d686-4c0e-887e-fd8b12aa0ca8](https://user-images.githubusercontent.com/3283295/40401029-3c5fe168-5e77-11e8-9ab6-fbd23121c8dd.png)

the sdk & version:
![9ebc0b27-51f4-4dec-89a6-b84903a1ba8a](https://user-images.githubusercontent.com/3283295/40400675-ce5edc56-5e75-11e8-9a29-9d8acb210328.png)

**Comment by morganchen12** [comment]
For each stack trace posted, can you expand the full stack trace to show the hidden symbols (click on the triangle icons on the left side of the stack trace)?

**Comment by baolocdo** [comment]
Do you know which iOS versions caused the crashes?

**Comment by Lingyj** [comment]
11.3.1 (15E302) iPhone 7
11.2.5 (15D60) iPhone 7 Plus
11.3.1 (15E302) 7 Plus

![f8426044-a10f-4eec-adf4-af98aa8692ce](https://user-images.githubusercontent.com/3283295/40463070-995b4618-5f45-11e8-9960-0dbe75c525eb.png)
![7c80cdeb-d89a-43ac-9157-07f14c0dae87](https://user-images.githubusercontent.com/3283295/40463072-9b269772-5f45-11e8-80f0-6bf7848297f0.png)

**Comment by Lingyj** [comment]
11.2.1 (15C153) iPhone 7
11.3.1 (15E302) iPhone X
11.3.1 (15E302) iPhone 6

![c4f25d40-bf20-4e01-960a-cd124408c4f5](https://user-images.githubusercontent.com/3283295/40463146-10b224fc-5f46-11e8-933a-2a433f663363.png)
![eabb4e5c-df9f-4f58-b7a5-6be5414cf575](https://user-images.githubusercontent.com/3283295/40463150-132c0f0e-5f46-11e8-8ef2-92b10bc0eb03.png)

**Comment by Lingyj** [comment]
11.2.5 (15D60) iPhone 7 Plus
11.3.0 (15E216) iPhone 7

![d2905d18-2092-434b-8800-5c88068afd8b](https://user-images.githubusercontent.com/3283295/40463210-846de7a0-5f46-11e8-9da3-ab17c25e8fa1.png)

**Comment by Lingyj** [comment]
11.2.5 (15D60) iPhone 7 Plus

![d336d3d5-d576-4d06-9255-e4de952a36e3](https://user-images.githubusercontent.com/3283295/40463281-0308d9b2-5f47-11e8-84f1-14386647bb59.png)
![8a8d43f0-bc40-4f25-a7ed-8a56e063b4d0](https://user-images.githubusercontent.com/3283295/40463284-0567c790-5f47-11e8-9fa2-e127d91ed700.png)

**Comment by Lingyj** [comment]
11.2.5 (15D60) iPhone 7 Plus

![53ebd5ff-81bc-44c2-a8bc-8d85a679ae9e](https://user-images.githubusercontent.com/3283295/40463365-73425a50-5f47-11e8-8071-e5e80d87d9ca.png)
![c4e9ad44-fc90-4a8b-afa4-9ca90e80ff70](https://user-images.githubusercontent.com/3283295/40463367-7455f4a6-5f47-11e8-851a-043842bc5b18.png)

**Comment by morganchen12** [comment]
The crashes here are all in methods that shouldn't crash (like `+[NSDate date]`) or in `retain`/`release`. They may not be issues related to Firebase, and we likely won't be able to debug them without repro.

**Comment by morganchen12** [comment]
@Lingyj can you try updating to Firebase 5 and seeing if these are still present?

**Comment by Lingyj** [comment]
I catght it just now but only once. I opened the Zombie Objects and run the project, the crash occured.


![83f2a5bc-a4d0-4758-86c4-95cb1810df77](https://user-images.githubusercontent.com/3283295/41466779-47453724-70d6-11e8-924f-1b886813995c.png)

**Comment by Lingyj** [comment]
An other one

![4896eca1-02b3-423b-ab8d-95582e7ea8d8](https://user-images.githubusercontent.com/3283295/41469802-3aeebb5c-70e1-11e8-80a7-84ae41d1abc8.png)
![771746a0-8279-4374-ae21-5ab4f5eeb96d](https://user-images.githubusercontent.com/3283295/41469806-404aa12e-70e1-11e8-8e33-c8556e9512be.png)
![89beb7ef-b6ac-4e0d-9201-b1f543dbbde1](https://user-images.githubusercontent.com/3283295/41469808-417bdfae-70e1-11e8-8cd1-1831605df9a2.png)

**Comment by Lingyj** [comment]
I guess the crash `[FIRASearchAdReporter scheduleSearchAdReport] ` because of `nonatomic`. `nonatomic` is not thread-safe. In the other thread, the method is executing and coursed the crash. You can read [this link](https://www.jianshu.com/p/b075bfd67899).

![973a0c55-ebaf-4dbf-bf31-500f5a4bd377](https://user-images.githubusercontent.com/3283295/41496100-cdeef380-7169-11e8-8896-5f1de96487ec.png)
![2ca99081-0eda-4ead-983f-bd6135b1a95b](https://user-images.githubusercontent.com/3283295/41496101-ce9806aa-7169-11e8-8e3c-03204e40bed9.png)
![361c4a58-76de-4f7e-be3e-c7f5db92248b](https://user-images.githubusercontent.com/3283295/41496102-cfc1361e-7169-11e8-8e92-c3830e10dcc6.png)

**Comment by baolocdo** [comment]
I think the `self` in the **async** block might have been deallocated. We should check whether `self` has been nil in the async call block. Can someone fix the `FIRMutableDictionary` and  `FIRNetwork`? @morganchen12 @ryanwilson 

Regarding the screenshot of FIRAMonitor, please upgrade to the latest version and use the flag `UseCFPreferencesLibrary=YES` in the Info.plist? Please let us know whether you see the crash again. Thanks

**Comment by morganchen12** [comment]
@Lingyj are you able to capture the same zombie crash with an exception breakpoint enabled (or are you able to share the exception message with the backtrace)? The stack traces provided end in `__dealloc_zombie`, which IIRC is not indicative of a bad access when zombies are enabled.

**Comment by Lingyj** [comment]
`FIRMutableDictionary` seem only happened with Zombie Objects. I closed Zombie Objects and 
cannot reappearance. 
What about `[FIRASearchAdReporter scheduleSearchAdReport]`, I got 18 crashes in the last 7 days. Any suggestion? We will have a new release in a few days. I did update to the latest sdk and add `UseCFPreferencesLibrary `.

**Comment by baolocdo** [comment]
I'll try to fix `FIRASearchAdReporter` but the scheduled release won't be out until next month. Sorry for keeping you waiting.

**Comment by Lingyj** [comment]
Hello, I got a serious problem with the lastest sdk.  `[FIRAMeasurement monitor] ` crash 140 times in two days, most on iOS11.4.0. Old crashes seems have been fixed in the lastest sdk.


![image](https://user-images.githubusercontent.com/3283295/41948038-7a58d452-79ed-11e8-899c-012129dffcfc.png)
![image](https://user-images.githubusercontent.com/3283295/41948051-8e86dc8a-79ed-11e8-9b1f-abf1d0280e69.png)
![image](https://user-images.githubusercontent.com/3283295/41948075-ab42219a-79ed-11e8-90ca-7f60c3150379.png)
![image](https://user-images.githubusercontent.com/3283295/41948091-b8f46c76-79ed-11e8-97cc-f2ee2fcbea5b.png)


![image](https://user-images.githubusercontent.com/3283295/41948140-ebcc104a-79ed-11e8-8f8c-f5a075069d9f.png)
![image](https://user-images.githubusercontent.com/3283295/41948152-f5ff1a8a-79ed-11e8-9a59-a32531a4268b.png)
![image](https://user-images.githubusercontent.com/3283295/41948172-0686518e-79ee-11e8-8cf0-ad198c33cf68.png)
![image](https://user-images.githubusercontent.com/3283295/41948181-10a80392-79ee-11e8-8526-ed1f834c61c4.png)





Here the sdk version:
> Using Firebase (5.3.0)
> Using FirebaseAnalytics (5.0.1)
> Using FirebaseCore (5.0.4)
> Using FirebaseInstanceID (3.1.1)
> Using FirebaseMessaging (3.0.2)
> Using FirebasePerformance (2.0.1)
> Using FirebaseSwizzlingUtilities (2.0.0)

**Comment by Lingyj** [comment]
Seems there have a singleton with `FIRAMeasurement`. When the signleton init, it calls `[FIRAUserDefaults synchronize]`, and `FIRAUserDefaults` recall the singleton before the singleton finish.

**Comment by baolocdo** [comment]
@Lingyj : I have filed internal bug at b/110876085. The fix should be in the next release of Firebase Analytics. Thanks for reporting

**Comment by ryanwilson** [comment]
The fix was shipped in Firebase 5.5.0 last week.
