### ISSUE TITLE
In app messaging doesn't work in version 10.28.1

### ISSUE THREAD

**Issue by Tulakshana** [firebase/firebase-ios-sdk#13191]
### Description

In app messaging doesn't work in version 10.28.1

### Reproducing the issue

Steps to reproduce

1. Install Firebase version 10.28.1 using cocoapods
`pod 'Firebase/Messaging', '10.28.1'
pod 'Firebase/RemoteConfig', '10.28.1'
pod 'Firebase/Auth', '10.28.1'
pod 'Firebase/Crashlytics', '10.28.1'
pod 'Firebase/Analytics', '10.28.1'
pod 'Firebase/InAppMessaging', '10.28.1' #beta
pod 'Firebase/Performance', '10.28.1'`
2. Go to in app messaging in the firebase console and create a new in app messaging campaign
3. Install the new version of the app with Firebase 10.28.1 in a real device
4. Run the app
5. Copy the firebase installation id
`Installations.installations().installationID { [weak self] (id, error) in }`
6. Use the copied installation id to send a test in app message using the campaign you created in step 2

Expected result
Receive the in app message

Actual result
Does not receive the in app message

### Firebase SDK Version

10.28.1

### Xcode Version

15.3

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, Authentication, Crashlytics, In-App Messaging, Messaging, Performance, Remote Config

### Targeted Platforms

iOS

### If using CocoaPods, the project's Podfile.lock

platform :ios, '15.0'

inhibit_all_warnings!

use_frameworks!

pod 'Firebase/Messaging', '10.28.1'
pod 'Firebase/RemoteConfig', '10.28.1'
pod 'Firebase/Auth', '10.28.1'
pod 'Firebase/Crashlytics', '10.28.1'
pod 'Firebase/Analytics', '10.28.1'
pod 'Firebase/InAppMessaging', '10.28.1' #beta
pod 'Firebase/Performance', '10.28.1'

target 'MyApp' do
end

target 'MyAppTests' do
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
  end
end

**Comment by Tulakshana** [comment]
Yes

**Comment by rizafran** [comment]
Thanks for the reply, @Tulakshana. I can't seem to reproduce the issue. Could you confirm if it's also reproducible using a simulator on your end?

**Comment by Tulakshana** [comment]
Mmm… it worked fine on the simulator. The simulator I used was iPhone 15 Pro (iOS 17.4). My real device is an iPhone XR running iOS 16.2. I tested an iPhone XR simulator (iOS 16.2) too and it worked fine. I’m using Xcode 15.3. The only way I can get the message on my real device is by switching to version 10.28.0

**Comment by Tulakshana** [comment]
@paulb777 
[podfile.md](https://github.com/user-attachments/files/16168924/podfile.md)

**Comment by Tulakshana** [comment]
The issue seems to be fixed in version 10.29.0
