### ISSUE TITLE
Excessive Crashes on Remote Config Fetch after updating to 10.24.0

### ISSUE THREAD

**Issue by SatabdiDas27** [firebase/firebase-ios-sdk#13204]
### Description

We are seeing a huge number of crashes generating from Remote config after we updated the SDK to 10.24.0 . We have not seen this before we updated , we were on 10.11.0 before

What is the best path forward? Our crash free rate in production is dropping by the minute. I saw a similar issue posted by another person.

exception
EXC_BAD_ACCESS: getCharacters:range: >
KERN_INVALID_ADDRESS at 0x8000000000000008

### Firebase SDK Version

10.24

### Xcode Version

15.3

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, Crashlytics, Remote Config

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Crashed: com.apple.root.default-qos
0  libswiftCore.dylib             0x4065b4 swift_isUniquelyReferenced_nonNull_native + 38
1  SharedResources                0x1dc41c $s15SharedResources18FeatureFlagManagerC3set_9withValueyAA0cD0O_SbtF + 228
2  PetSmart                       0x41533c closure #1 in closure #1 in FeatureFlagManager.configureRemoteConfig(_:) + 94 (FeatureFlagExtension.swift:94)
3  PetSmart                       0x3d1c00 thunk for @escaping @callee_guaranteed (@unowned Bool, @guaranteed Error?) -> () + 4306820096 (<compiler-generated>:4306820096)
4  libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
5  libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
6  libdispatch.dylib              0x6f6c _dispatch_queue_override_invoke + 928
7  libdispatch.dylib              0x15894 _dispatch_root_queue_drain + 392
8  libdispatch.dylib              0x1609c _dispatch_worker_thread2 + 156
9  libsystem_pthread.dylib        0x48f8 _pthread_wqthread + 228
10 libsystem_pthread.dylib        0x10cc start_wqthread + 8
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
@SatabdiDas27 The backtrace doesn't show anything from Firebase. FeatureFlagExtension.swift is not part of the product.
