### ISSUE TITLE
Facing signature change error with the latest 10.28.0 version 

### ISSUE THREAD

**Issue by jesphinpt** [firebase/firebase-ios-sdk#13212]
### Description

I am working with manually adding the sdk for crashlytics and analytics. I ma getting the error for the crashlytics and analytics sdks as below. Can I accept this change?

Does it impact anything?

<img width="495" alt="Screenshot 2024-07-02 at 5 38 35 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/67142639/f055b6fb-6f07-459c-8fc7-f0591c570d61">

### Reproducing the issue

Updated the version from 10.25.0 to 10.28.0

### Firebase SDK Version

10.28.0

### Xcode Version

15.4

### Installation Method

Zip

### Firebase Product(s)

Analytics, Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment]
Hi @jesphinpt, thanks for filing and sorry for the trouble. I investigated and many of the XCFrameworks in the 10.28.0 Firebase.zip are unsigned, including the `GoogleDataTransport.xcframework` you pointed out. As long as you downloaded the zip from the GitHub release page or Firebase website, the artifacts should be secure. However, using unsigned artifacts may cause issues during app store submission. 

I would recommend falling back to 10.27.0 until a fix is released in the next release, 10.29.0.

**Comment by jesphinpt** [comment]
I have downloaded it from here https://github.com/firebase/firebase-ios-sdk/releases/download/10.28.0/Firebase.zip. Is it good to go with this? But it not shows any signature available like any popup.

How can I confirm that signature is available for this?

**Comment by ncooke3** [comment]
If you inspect the zipped `Firebase/` directory with `find /path/to/Firebase -type d -name _CodeSignature`. It should list many directories where each maps to a XCFramework.

```
% find /Users/nickcooke/Downloads/Firebase -type d -name _CodeSignature 
/Users/nickcooke/Downloads/Firebase/FirebaseDynamicLinks/FirebaseDynamicLinks.xcframework/_CodeSignature
/Users/nickcooke/Downloads/Firebase/FirebaseCrashlytics/Promises.xcframework/_CodeSignature
/Users/nickcooke/Downloads/Firebase/FirebaseCrashlytics/FirebaseSessions.xcframework/_CodeSignature
<more output...>
```

I would recommend 10.28.0 just because it's a more recent release.
