### ISSUE TITLE
Failed to verify code signature of grpcpp.framework

### ISSUE THREAD

**Issue by hrabkin** [firebase/firebase-ios-sdk#13214]
### Description

I use xcframeworks packaged into FirebaseBinaries package, [see gist here](https://gist.github.com/hrabkin/9bb1edbbfed1b7f32bc0a2e13b6e65d0)

I use [version 10.28.0](https://github.com/firebase/firebase-ios-sdk/releases/download/10.28.0/Firebase.zip)

It builds fine but when I run install on a device it fails
`Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.fIqW2t/extracted/*.app/Frameworks/grpcpp.framework : 0xe8008001 (An unknown error has occurred.)`

iOS 17.5.1
![Screenshot 2024-07-02 at 10 04 58 PM](https://github.com/firebase/firebase-ios-sdk/assets/2230377/8ca90167-3efd-4cf7-b50b-1e758c48579d)

I've been on 10.23.0 and failed in exact same way so I tried to update to 10.28.0 but it didn't help

Xcode 15.4

I bet its not Firebase but the Xcode update because everything worked fine before the 15.4 update
`codesign --verify -dvvv --strict ` ->
```
Identifier=grpcpp
Format=bundle
CodeDirectory v=20200 size=198 flags=0x0(none) hashes=1+3 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha1=57e80f153bff147db71d9e44905c5228404fba6e
CandidateCDHashFull sha1=57e80f153bff147db71d9e44905c5228404fba6e
CandidateCDHash sha256=ddf7a0080340a03cdf4c85127d82dbfe561fce4d
CandidateCDHashFull sha256=ddf7a0080340a03cdf4c85127d82dbfe561fce4dc2ae87fce59d86e0919d904c
Hash choices=sha1,sha256
CMSDigest=90b8ac4111ab8952cb8491f23f40bc56c6ee1758d5b596ad710126250a9e24a5
CMSDigestType=2
CDHash=ddf7a0080340a03cdf4c85127d82dbfe561fce4d
Signature size=9142
Authority=Developer ID Application: Google LLC (EQHXZ8M8AV)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=12 Jun 2024 at 10:22:51 PM
Info.plist entries=3
TeamIdentifier=EQHXZ8M8AV
Sealed Resources version=2 rules=10 files=7872
Internal requirements count=1 size=168
```

I tried to resign 
`codesign --force --sign "My Identity" --deep --preserve-metadata=identifier,entitlements,flags --timestamp=none`
didn't help

### Firebase SDK Version

10.28.0

### Xcode Version

15.4

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Authentication, Crashlytics, Firestore, Messaging, Remote Config

### Targeted Platforms

iOS 16.1+, macOS

### Relevant Log Output

```shell
FirebaseABTesting.xcframework' does not contain a binary artifact.
```

**Comment by ncooke3** [comment]
Hi @hrabkin, there could be an issue with the gist. Could you please try redownloading the Firebase.zip from the releases page? I'm seeing the 10.28.0 Firebase.zip to contain the ABTesting binary for the three iOS related slices:

<img width="1032" alt="Screenshot 2024-07-02 at 3 57 07 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/36927374/bb4cfc2a-62b1-417e-9b18-d54559260f83">

**Comment by hrabkin** [comment]
I had this "Run Script" which created the issue.

```
TARGET_MIN_OS_VERSION="16.1"
FRAMEWORKS_DIR="${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}"

update_framework_plists() {
  local path="$1"
  echo "Updating Info.plist files in $path"
  
  find "$path" -name Info.plist | while read plist; do
    local normalized_plist_path=$(realpath "$plist")
    
    echo "Updating $normalized_plist_path"
    /usr/libexec/PlistBuddy -c "Add :MinimumOSVersion string $TARGET_MIN_OS_VERSION" "$plist" &>/dev/null || /usr/libexec/PlistBuddy -c "Set :MinimumOSVersion $TARGET_MIN_OS_VERSION" "$plist"
    
    if [ $? -eq 0 ]; then
      echo "Successfully set MinimumOSVersion to $TARGET_MIN_OS_VERSION in $normalized_plist_path"
    else
      echo "Failed to set MinimumOSVersion in $normalized_plist_path"
    fi
  done
}

update_framework_plists "$FRAMEWORKS_DIR"
```
