### ISSUE TITLE
Please tell me the cause of NSInternalInconsistencyException

### ISSUE THREAD

**Issue by kyeongmipak** [firebase/firebase-ios-sdk#13219]
### Description

There have been many crashes since the release of myApp with Google Mobile Ads SDK 10.13.0 (pod) and Firebase SDK 10.27.0 (SPM).

Please let me know what causes it.

The crash log from firebase crashlytics is shared as follows.

# Crashlytics - Stack trace
# Platform: apple

Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x83f20 __exceptionPreprocess
1  libobjc.A.dylib                0x16018 objc_exception_throw
2  CoreAutoLayout                 0x12224 _NSConstraintBasedLayoutDeferOptimization
3  CoreAutoLayout                 0x589c -[NSISEngine _optimizeWithoutRebuilding]
4  CoreAutoLayout                 0x2208 -[NSISEngine optimize]
5  CoreAutoLayout                 0x1f94 -[NSISEngine performPendingChangeNotifications]
6  UIKitCore                      0x10d1c -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
7  UIKitCore                      0x248c7c -[_UILabelLayer layoutSublayers]
8  QuartzCore                     0x7e3b4 CA::Layer::layout_if_needed(CA::Transaction*)
9  QuartzCore                     0x7df38 CA::Layer::layout_and_display_if_needed(CA::Transaction*)
10 QuartzCore                     0xd90e0 CA::Context::commit_transaction(CA::Transaction*, double, double*)
11 QuartzCore                     0x4e028 CA::Transaction::commit()
12 QuartzCore                     0x22f3c8 CA::Transaction::release_thread(void*)
13 libsystem_pthread.dylib        0x4f18 _pthread_tsd_cleanup
14 libsystem_pthread.dylib        0x4c88 _pthread_exit
15 libsystem_pthread.dylib        0x4c34 _pthread_exit
16 libsystem_pthread.dylib        0x49bc _pthread_wqthread
17 libsystem_pthread.dylib        0x10cc start_wqthread

com.apple.main-thread
0  libsystem_kernel.dylib         0x1808 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x5008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4f20 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4d60 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  GraphicsServices               0x11a8 GSEventRunModal + 164
8  UIKitCore                      0x40a90c -[UIApplication _run] + 888
9  UIKitCore                      0x4be9d0 UIApplicationMain + 340
10 UIKitCore                      0x638384 keypath_get_selector_hoverStyle + 11024
11 myApp                    	  0x321640 main + 4381218368 (AppDelegate.swift:4381218368)
12 ???                            0x1c580de4c (누락)

com.apple.root.default-qos
0  libsystem_kernel.dylib         0x1808 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x5008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4f20 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4d60 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  Foundation                     0xc7e4c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0xc7d20 -[NSRunLoop(NSRunLoop) run] + 64
9  myApp                          0xf65db8 __25-[MTGLogQueue setupTimer]_block_invoke + 4672836
10 libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
11 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
12 libdispatch.dylib              0x6f6c _dispatch_queue_override_invoke + 928
13 libdispatch.dylib              0x15894 _dispatch_root_queue_drain + 392
14 libdispatch.dylib              0x1609c _dispatch_worker_thread2 + 156
15 libsystem_pthread.dylib        0x48f8 _pthread_wqthread + 228
16 libsystem_pthread.dylib        0x10cc start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1590 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x4980 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x10cc start_wqthread + 8

com.apple.root.default-qos
0  libsystem_kernel.dylib         0x1808 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x5008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4f20 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4d60 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  Foundation                     0xc7e4c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0xc7d20 -[NSRunLoop(NSRunLoop) run] + 64
9  myApp                          0xf65db8 __25-[MTGLogQueue setupTimer]_block_invoke + 4672836
10 libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
11 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
12 libdispatch.dylib              0x6f6c _dispatch_queue_override_invoke + 928
13 libdispatch.dylib              0x15894 _dispatch_root_queue_drain + 392
14 libdispatch.dylib              0x1609c _dispatch_worker_thread2 + 156
15 libsystem_pthread.dylib        0x48f8 _pthread_wqthread + 228
16 libsystem_pthread.dylib        0x10cc start_wqthread + 8

com.apple.root.default-qos
0  libsystem_kernel.dylib         0x1808 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x5008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4f20 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4d60 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  Foundation                     0xc7e4c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0xc7d20 -[NSRunLoop(NSRunLoop) run] + 64
9  myApp                    	  0xe2b544 __40-[MTGLogQueueManager startTimerIfNeeded]_block_invoke + 3384528
10 libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
11 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
12 libdispatch.dylib              0x6f6c _dispatch_queue_override_invoke + 928
13 libdispatch.dylib              0x15894 _dispatch_root_queue_drain + 392
14 libdispatch.dylib              0x1609c _dispatch_worker_thread2 + 156
15 libsystem_pthread.dylib        0x48f8 _pthread_wqthread + 228
16 libsystem_pthread.dylib        0x10cc start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1590 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x4980 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x10cc start_wqthread + 8

com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x1808 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x5008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4f20 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4d60 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  Foundation                     0xc7e4c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0xc7c9c -[NSRunLoop(NSRunLoop) runUntilDate:] + 64
9  UIKitCore                      0x41e640 -[UIEventFetcher threadMain] + 420
10 Foundation                     0xde718 __NSThread__start__ + 732
11 libsystem_pthread.dylib        0x606c _pthread_start + 136
12 libsystem_pthread.dylib        0x10d8 thread_start + 8

Crashed: com.google.firebase.crashlytics.ios.exception
0  myApp                    	  0x4c2a8c FIRCLSProcessRecordAllThreads + 392 (FIRCLSProcess.c:392)
1  myApp                    	  0x4c2e6c FIRCLSProcessRecordAllThreads + 423 (FIRCLSProcess.c:423)
2  myApp                    	  0x4d0fa0 FIRCLSHandler + 34 (FIRCLSHandler.m:34)
3  myApp                          0x4d0da4 __FIRCLSExceptionRecord_block_invoke + 240 (FIRCLSException.mm:240)
4  libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
5  libdispatch.dylib              0x132c4 _dispatch_lane_barrier_sync_invoke_and_complete + 56
6  myApp                    	  0x4cfd20 FIRCLSExceptionRecord + 242 (FIRCLSException.mm:242)
7  myApp                    	  0x4d0868 FIRCLSExceptionRecordNSException + 126 (FIRCLSException.mm:126)
8  myApp                    	  0x4cf928 FIRCLSTerminateHandler() + 407 (FIRCLSException.mm:407)
9  libc++abi.dylib                0x14068 std::__terminate(void (*)()) + 16
10 libc++abi.dylib                0x1735c __cxa_get_exception_ptr + 86
11 libc++abi.dylib                0x172a0 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) + 306
12 libobjc.A.dylib                0x16180 objc_exception_throw + 420
13 CoreAutoLayout                 0x12224 _NSConstraintBasedLayoutDeferOptimization + 326
14 CoreAutoLayout                 0x589c -[NSISEngine _optimizeWithoutRebuilding] + 72
15 CoreAutoLayout                 0x2208 -[NSISEngine optimize] + 96
16 CoreAutoLayout                 0x1f94 -[NSISEngine performPendingChangeNotifications] + 104
17 UIKitCore                      0x10d1c -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2248
18 UIKitCore                      0x248c7c -[_UILabelLayer layoutSublayers] + 560
19 QuartzCore                     0x7e3b4 CA::Layer::layout_if_needed(CA::Transaction*) + 504
20 QuartzCore                     0x7df38 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 148
21 QuartzCore                     0xd90e0 CA::Context::commit_transaction(CA::Transaction*, double, double*) + 464
22 QuartzCore                     0x4e028 CA::Transaction::commit() + 648
23 QuartzCore                     0x22f3c8 CA::Transaction::release_thread(void*) + 228
24 libsystem_pthread.dylib        0x4f18 _pthread_tsd_cleanup + 620
25 libsystem_pthread.dylib        0x4c88 _pthread_exit + 84
26 libsystem_pthread.dylib        0x4c34 _pthread_exit + 62
27 libsystem_pthread.dylib        0x49bc _pthread_wqthread + 424
28 libsystem_pthread.dylib        0x10cc start_wqthread + 8

com.apple.root.default-qos
0  libsystem_kernel.dylib         0x1808 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x5008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4f20 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4d60 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  Foundation                     0xc7e4c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0xc7d20 -[NSRunLoop(NSRunLoop) run] + 64
9  myApp                    	  0xf65db8 __25-[MTGLogQueue setupTimer]_block_invoke + 4672836
10 libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
11 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
12 libdispatch.dylib              0x6f6c _dispatch_queue_override_invoke + 928
13 libdispatch.dylib              0x15894 _dispatch_root_queue_drain + 392
14 libdispatch.dylib              0x1609c _dispatch_worker_thread2 + 156
15 libsystem_pthread.dylib        0x48f8 _pthread_wqthread + 228
16 libsystem_pthread.dylib        0x10cc start_wqthread + 8

Thread
0  libsystem_pthread.dylib        0x10c4 start_wqthread + [8573026498](tel:(857)%20302-6498)

com.apple.root.default-qos
0  libsystem_kernel.dylib         0x1808 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x5008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4f20 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4d60 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  Foundation                     0xc7e4c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0xc7d20 -[NSRunLoop(NSRunLoop) run] + 64
9  myApp                    	  0xf65db8 __25-[MTGLogQueue setupTimer]_block_invoke + 4672836
10 libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
11 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
12 libdispatch.dylib              0x6f6c _dispatch_queue_override_invoke + 928
13 libdispatch.dylib              0x15894 _dispatch_root_queue_drain + 392
14 libdispatch.dylib              0x1609c _dispatch_worker_thread2 + 156
15 libsystem_pthread.dylib        0x48f8 _pthread_wqthread + 228
16 libsystem_pthread.dylib        0x10cc start_wqthread + 8

com.buadsdk.permanent.5.6.0.5.thread
0  libsystem_kernel.dylib         0x1808 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x5008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4f20 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4d60 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  Foundation                     0xc7e4c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0xc7d20 -[NSRunLoop(NSRunLoop) run] + 64
9  myApp                    	  0x126e8ac -[PAGThreadMonitor threadEntryPoint:] + 30 (PAGThreadMonitor.m:30)
10 Foundation                     0xde718 __NSThread__start__ + 732
11 libsystem_pthread.dylib        0x606c _pthread_start + 136
12 libsystem_pthread.dylib        0x10d8 thread_start + 8

JavaScriptCore libpas scavenger
0  libsystem_kernel.dylib         0x71cc __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x36e4 _pthread_cond_wait + 1228
2  JavaScriptCore                 0x155b0a4 scavenger_thread_main + 1512
3  libsystem_pthread.dylib        0x606c _pthread_start + 136
4  libsystem_pthread.dylib        0x10d8 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x1590 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x4980 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x10cc start_wqthread + 8

com.apple.root.default-qos
0  libsystem_kernel.dylib         0x1808 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x5008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4f20 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4d60 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  Foundation                     0xc7e4c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0xc7d20 -[NSRunLoop(NSRunLoop) run] + 64
9  myApp                    	  0xe2b544 __40-[MTGLogQueueManager startTimerIfNeeded]_block_invoke + 3384528
10 libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
11 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
12 libdispatch.dylib              0x6f6c _dispatch_queue_override_invoke + 928
13 libdispatch.dylib              0x15894 _dispatch_root_queue_drain + 392
14 libdispatch.dylib              0x1609c _dispatch_worker_thread2 + 156
15 libsystem_pthread.dylib        0x48f8 _pthread_wqthread + 228
16 libsystem_pthread.dylib        0x10cc start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1590 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x4980 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x10cc start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1590 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x4980 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x10cc start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1590 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x4980 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x10cc start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1590 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x4980 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x10cc start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1590 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x4980 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x10cc start_wqthread + 8

com.google.firebase.crashlytics.MachExceptionServer
0  libsystem_kernel.dylib         0x1808 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x5008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4f20 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4d60 mach_msg + 24
4  myApp                    	  0x4d155c FIRCLSMachExceptionServer + 194 (FIRCLSMachException.c:194)
5  libsystem_pthread.dylib        0x606c _pthread_start + 136
6  libsystem_pthread.dylib        0x10d8 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x1590 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x4980 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x10cc start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1590 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x4980 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x10cc start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1590 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x4980 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x10cc start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1590 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x4980 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x10cc start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1590 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x4980 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x10cc start_wqthread + 8

com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x1808 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x5008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4f20 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4d60 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  CFNetwork                      0xfdc90 _CFHostIsDomainTopLevel + 108176
8  Foundation                     0xde718 __NSThread__start__ + 732
9  libsystem_pthread.dylib        0x606c _pthread_start + 136
10 libsystem_pthread.dylib        0x10d8 thread_start + 8

### Firebase SDK Version

10.27.0

### Xcode Version

15.0.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Database, DynamicLinks, In-App Messaging, Messaging, Remote Config

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Firebase 10.27.0
GoogleAppMeasurement 10.27.0
GoogleDataTransport 9.4.0
GoogleUtilities 7.13.3

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

  pod 'Google-Mobile-Ads-SDK', '10.13.0'

```

</details>

**Comment by rizafran** [comment]
Hi @kyeongmipak, per checking, it looks like there's no Firebase-related logs in the stack trace. The `com.google.firebase.crashlytics.ios.exception` thread only captures exceptions thrown elsewhere in order to record crash information. With this, we'll need more information to be able to help.
