### ISSUE TITLE
Non fatal errors and crashes and logs are a tiny sample 

### ISSUE THREAD

**Issue by jesus-mg-ios** [firebase/firebase-ios-sdk#13228]
### Description

We are 100% sure that non fatals and errors are a sample of the what is happening in the product. We'll see around 2% of the non fatals that must be logged and about crashes our hipothesis is that they are a tiny sample aswell. 

Nothing on documentation about the sample rate.

Is this a bug or a known behaviour?

### Reproducing the issue

Add on a widget on the start of it a record of a non fatal, after that make a call to count the number oftimes the non fatal should be recorded and double check it on dashboard.

### Firebase SDK Version

10.25.0

### Xcode Version

15.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS, macCatalyst

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by themiswang** [comment]
Hey @jesus-mg-ios,

Crashlytics only stores the most recent eight exceptions in a given app session. The documentation is [here](https://firebase.google.com/docs/crashlytics/customize-crash-reports?_gl=1*egdiya*_up*MQ..*_ga*NDQ0NjYwMjY0LjE3MjAxMDQ5MTc.*_ga_CW55HF8NVT*MTcyMDEwNDkxNi4xLjAuMTcyMDEwNDkxNi4wLjAuMA..&platform=ios) 
![image](https://github.com/firebase/firebase-ios-sdk/assets/16548721/fb67e1a6-5158-4f12-a1c7-eb3701cd1c7d)
Let me know if this is match your observation, Thanks!

**Comment by jesus-mg-ios** [comment]
Not at all.

**Comment by mrober** [comment]
@jesus-mg-ios can you please explain why @themiswang's explanation does not match your observation? It looks to me like it explains what you described in "Reproducing the issue" perfectly. If you log and count 100 non-fatals in a session, then end the session by crashing or restarting the app, you should expect only the most recent 8 non-fatals get uploaded in that report.

**Comment by jesus-mg-ios** [comment]
Sure, What I've seen is for example 1000 users entering in the app and a record at the init is done. If the case you are describing would happen, at the end of the 1000 users sessions, I have at least 1000 non fatals, isn't it? But what i'm seeing is like 20 - 14 non fatals, no more.

**Comment by jesus-mg-ios** [comment]
No more info

**Comment by rizafran** [comment]
Thanks for sharing your scenario, @jesus-mg-ios. The docs mentioned that Crashlytics only stores the most recent eight exceptions in a given app session, and seems like it applies to "per app session", which means that if those 100 users experience the same crash, all of those should be up in the Crashlytics dashboard, as long as all of them restart the app and have internet access. Since this is related to the backend side, could you file a ticket through our [support channel](https://firebase.google.com/support) to investigate the cause of the issue? You can also provide your detailed steps on how you reproduce the issue as well as your project ID.
