### ISSUE TITLE
Getting new_app_user event logged automatically in Firebase Analytics version 10.25.0

### ISSUE THREAD

**Issue by Vikrant2411** [firebase/firebase-ios-sdk#13234]
### Description

I have integrated the firebase analytics in the iOS app with version of Firebase Analytics 10.25.0.
Here when ever any event got logged the new_app_user event which we have not added in the code of our app, on search in project it is no where in app is getting logged in debug_view of the Firebase console.

### Reproducing the issue

Every time when I am checking events log in debug_view it is logging event automatically with name new_app_user.
![Screenshot 2024-07-05 at 17 35 05](https://github.com/firebase/firebase-ios-sdk/assets/88380070/b8baaa49-c266-4f0f-be60-9686eda61887)

### Firebase SDK Version

10.25.0

### Xcode Version

15.3

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reporting, @Vikrant2411. I wasn't able to reproduce the issue. Could you check if you have created the `new_app_user` event in the Events dashboard?

**Comment by Vikrant2411** [comment]
Hi @rizafran ,
Yes I have checked the Events dashboard there are logs of the new_app_user events but how can i get this is created by someone or it available by default?

**Comment by rizafran** [comment]
@Vikrant2411, I think you'll identify if the events are created by someone if you click the modify event and shows the list of custom events. You may also check these list of [automatically collected events](https://support.google.com/analytics/answer/9234069?hl=en&ref_topic=13367566&sjid=9106466232615930752-AP) and [recommended events](https://support.google.com/analytics/answer/9267735?hl=en&ref_topic=13367566&sjid=9106466232615930752-AP).

**Comment by Vikrant2411** [comment]
@rizafran ,
I have checked there is no event created by me or anyone.
![Screenshot 2024-07-10 at 09 26 51](https://github.com/firebase/firebase-ios-sdk/assets/88380070/6fab03c7-028d-4301-8ef0-bd1f014c0190)

Is it possible it is because of we have previously other project where we have used the same bundle id because the app is the part of the group. Now we have created a separate project in firebase for this with same bundle id. 
So, is it possible new_app_user is logging because of this?

**Comment by rizafran** [comment]
@Vikrant2411, the `new_app_user` event shouldn't be logging in your new created project with the same bundle ID since they're using a different `GoogleService-Info.plist` file. With this, have you tried checking if you're currently using the `GoogleService-Info.plist` file of your new project?

**Comment by Vikrant2411** [comment]
Yes, I have verified it, GoogleService_Info.plist file is of the new project.

**Comment by Vikrant2411** [comment]
Hi @rizafran ,
Any answer for this? We are getting so much noise for this event, want to resolve this ASAP. 
Please if you can help in this.

**Comment by rizafran** [comment]
Sorry for the late revert, @Vikrant2411. You mentioned above that you have checked your Events dashboard and there are logs of the `new_app_user` events. May I know if you're referring to your old project?

**Comment by Vikrant2411** [comment]
@rizafran ,
I am referring to our new project on Firebase. In our new project we are facing this `new_app_user` event.
In old app it is not appearing for us.

**Comment by rizafran** [comment]
Thanks for confirming, @Vikrant2411. As discussed, could you file a ticket to our [support channel](https://firebase.google.com/support/) so the team could be able to check your project? You may share this GitHub ticket along with your project number and verbose logs to investigate.
