### ISSUE TITLE
Issue compiling cct.nanopb.c : missing GoogleDataTransport/GDTCCTLibrary/Protogen/nanopb/compliance.nanopb.h

### ISSUE THREAD

**Issue by timothy-moonware** [firebase/firebase-ios-sdk#13255]
### Description

Getting this compiliation error on CI :
/Users/distiller/project/halo/Pods/GoogleDataTransport/GoogleDataTransport/GDTCCTLibrary/Protogen/nanopb/cct.nanopb.h:24:10: 'GoogleDataTransport/GDTCCTLibrary/Protogen/nanopb/compliance.nanopb.h' file not found

Here is my Podfile.lock :
PODS:
  - Firebase (10.14.0):
    - Firebase/Core (= 10.14.0)
  - Firebase/Core (10.14.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 10.14.0)
  - Firebase/CoreOnly (10.14.0):
    - FirebaseCore (= 10.14.0)
  - FirebaseABTesting (10.25.0):
    - FirebaseCore (~> 10.0)
  - FirebaseAnalytics (10.14.0):
    - FirebaseAnalytics/AdIdSupport (= 10.14.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (10.14.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleAppMeasurement (= 10.14.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseCore (10.14.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Logger (~> 7.8)
  - FirebaseCoreInternal (10.25.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseInstallations (10.25.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)
  - FirebaseMessaging (10.14.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Reachability (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseRemoteConfig (10.14.0):
    - FirebaseABTesting (~> 10.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - Google-Maps-iOS-Utils (4.2.2):
    - Google-Maps-iOS-Utils/Clustering (= 4.2.2)
    - Google-Maps-iOS-Utils/Geometry (= 4.2.2)
    - Google-Maps-iOS-Utils/GeometryUtils (= 4.2.2)
    - Google-Maps-iOS-Utils/Heatmap (= 4.2.2)
    - Google-Maps-iOS-Utils/QuadTree (= 4.2.2)
    - GoogleMaps (~> 7.3)
  - Google-Maps-iOS-Utils/Clustering (4.2.2):
    - Google-Maps-iOS-Utils/QuadTree
    - GoogleMaps (~> 7.3)
  - Google-Maps-iOS-Utils/Geometry (4.2.2):
    - GoogleMaps (~> 7.3)
  - Google-Maps-iOS-Utils/GeometryUtils (4.2.2):
    - GoogleMaps (~> 7.3)
  - Google-Maps-iOS-Utils/Heatmap (4.2.2):
    - Google-Maps-iOS-Utils/QuadTree
    - GoogleMaps (~> 7.3)
  - Google-Maps-iOS-Utils/QuadTree (4.2.2):
    - GoogleMaps (~> 7.3)
  - GoogleAppMeasurement (10.14.0):
    - GoogleAppMeasurement/AdIdSupport (= 10.14.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/AdIdSupport (10.14.0):
    - GoogleAppMeasurement/WithoutAdIdSupport (= 10.14.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/WithoutAdIdSupport (10.14.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleDataTransport (9.4.1):
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleMaps (7.3.0):
    - GoogleMaps/Maps (= 7.3.0)
  - GoogleMaps/Base (7.3.0)
  - GoogleMaps/Maps (7.3.0):
    - GoogleMaps/Base
  - GoogleUtilities (7.13.2):
    - GoogleUtilities/AppDelegateSwizzler (= 7.13.2)
    - GoogleUtilities/Environment (= 7.13.2)
    - GoogleUtilities/ISASwizzler (= 7.13.2)
    - GoogleUtilities/Logger (= 7.13.2)
    - GoogleUtilities/MethodSwizzler (= 7.13.2)
    - GoogleUtilities/Network (= 7.13.2)
    - "GoogleUtilities/NSData+zlib (= 7.13.2)"
    - GoogleUtilities/Privacy (= 7.13.2)
    - GoogleUtilities/Reachability (= 7.13.2)
    - GoogleUtilities/SwizzlerTestHelpers (= 7.13.2)
    - GoogleUtilities/UserDefaults (= 7.13.2)
  - GoogleUtilities/AppDelegateSwizzler (7.13.2):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
    - GoogleUtilities/Privacy
  - GoogleUtilities/Environment (7.13.2):
    - GoogleUtilities/Privacy
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/ISASwizzler (7.13.2):
    - GoogleUtilities/Privacy
  - GoogleUtilities/Logger (7.13.2):
    - GoogleUtilities/Environment
    - GoogleUtilities/Privacy
  - GoogleUtilities/MethodSwizzler (7.13.2):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/Network (7.13.2):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Privacy
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.13.2)":
    - GoogleUtilities/Privacy
  - GoogleUtilities/Privacy (7.13.2)
  - GoogleUtilities/Reachability (7.13.2):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/SwizzlerTestHelpers (7.13.2):
    - GoogleUtilities/MethodSwizzler
  - GoogleUtilities/UserDefaults (7.13.2):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - MapboxCommon (24.4.0)
  - MapboxCoreMaps (11.4.0):
    - MapboxCommon (~> 24.4)
  - MapboxMaps (11.4.0):
    - MapboxCommon (= 24.4.0)
    - MapboxCoreMaps (= 11.4.0)
    - Turf (= 2.8.0)
  - nanopb (2.30909.1):
    - nanopb/decode (= 2.30909.1)
    - nanopb/encode (= 2.30909.1)
  - nanopb/decode (2.30909.1)
  - nanopb/encode (2.30909.1)
  - PostHog (3.0.0)
  - PromisesObjC (2.4.0)
  - Realm (10.50.0):
    - Realm/Headers (= 10.50.0)
  - Realm/Headers (10.50.0)
  - RealmSwift (10.50.0):
    - Realm (= 10.50.0)
  - Turf (2.8.0)

DEPENDENCIES:
  - Firebase (= 10.14.0)
  - FirebaseCore (= 10.14.0)
  - FirebaseMessaging (= 10.14.0)
  - FirebaseRemoteConfig (= 10.14.0)
  - Google-Maps-iOS-Utils (= 4.2.2)
  - GoogleMaps (= 7.3.0)
  - GoogleUtilities
  - MapboxMaps (= 11.4.0)
  - PostHog (~> 3.0.0)
  - Realm
  - RealmSwift

SPEC REPOS:
  https://github.com/CocoaPods/Specs.git:
    - Firebase
    - FirebaseABTesting
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreInternal
    - FirebaseInstallations
    - FirebaseMessaging
    - FirebaseRemoteConfig
    - Google-Maps-iOS-Utils
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleMaps
    - GoogleUtilities
    - MapboxCommon
    - MapboxCoreMaps
    - MapboxMaps
    - nanopb
    - PostHog
    - PromisesObjC
    - Realm
    - RealmSwift
    - Turf

SPEC CHECKSUMS:
  Firebase: 6c1bf3f534bc422d52af2e41fe0d50bf08b6b773
  FirebaseABTesting: e6e3c3e0e35813874f571d1b7bdae2aab319dd38
  FirebaseAnalytics: 5c6d58814afa4db82cf7fdbc02b0b0e2fa3d43ff
  FirebaseCore: 6fc17ac9f03509d51c131298aacb3ee5698b4f02
  FirebaseCoreInternal: 910a81992c33715fec9263ca7381d59ab3a750b7
  FirebaseInstallations: 91950fe859846fff0fbd296180909dd273103b09
  FirebaseMessaging: 1077a4499f0c0a140b9a2e34fe08a1acc806b36d
  FirebaseRemoteConfig: e22a706fa7ecc64135325f4c430a15af1e795535
  Google-Maps-iOS-Utils: f77eab4c4326d7e6a277f8e23a0232402731913a
  GoogleAppMeasurement: 7fee012a868315d418f365fbc8d394d8e020e749
  GoogleDataTransport: 6c09b596d841063d76d4288cc2d2f42cc36e1e2a
  GoogleMaps: a146f275ee429d14822178c7a841c03366ec92a1
  GoogleUtilities: c56430aef51a1aa57b25da78c3f8397e522c67b7
  MapboxCommon: 6acbd8ff41d66abf498e1558b0739f25c562945a
  MapboxCoreMaps: f306bb1b10ebe995a2247b40e99322ab7f9b8071
  MapboxMaps: 82044383ae19ec124ff444ec4b5d3ce82cb36ba5
  nanopb: d4d75c12cd1316f4a64e3c6963f879ecd4b5e0d5
  PostHog: ce38cb62a50eda5c8975faef57fcc3e6c9dac2b3
  PromisesObjC: f5707f49cb48b9636751c5b2e7d227e43fba9f47
  Realm: a0a6a99e3dfa8959358a95c3c05845b5e5d6af30
  RealmSwift: fa111fb98e092a4dff1d0785ad0c3483feda607a
  Turf: aa2ede4298009639d10db36aba1a7ebaad072a5e

PODFILE CHECKSUM: dc771c21b462dd2907f2c0ee886a7b0af8e6bce6

COCOAPODS: 1.15.2

### Reproducing the issue

Use the Podfile.lock above and attempt to build the Pods.

### Firebase SDK Version

10.14.0

### Xcode Version

15.4

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, In-App Messaging, Messaging, Remote Config

### Targeted Platforms

iOS

### Relevant Log Output

```shell
[02:14:03]: ▸ Compiling cct.nanopb.c
[02:14:03]: ▸ ❌  /Users/distiller/project/halo/Pods/GoogleDataTransport/GoogleDataTransport/GDTCCTLibrary/Protogen/nanopb/cct.nanopb.h:24:10: 'GoogleDataTransport/GDTCCTLibrary/Protogen/nanopb/compliance.nanopb.h' file not found
[02:14:03]: ▸ #include "GoogleDataTransport/GDTCCTLibrary/Protogen/nanopb/compliance.nanopb.h"
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

{
  "originHash" : "e861f69ab05b22e3946f185e9e1c0a7cee3e23296b3d2fc909b9561370baf252",
  "pins" : [
    {
      "identity" : "abseil-cpp-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/abseil-cpp-binary.git",
      "state" : {
        "revision" : "748c7837511d0e6a507737353af268484e1745e2",
        "version" : "1.2024011601.1"
      }
    },
    {
      "identity" : "app-check",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/app-check.git",
      "state" : {
        "revision" : "3b62f154d00019ae29a71e9738800bb6f18b236d",
        "version" : "10.19.2"
      }
    },
    {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk",
      "state" : {
        "revision" : "eca84fd638116dd6adb633b5a3f31cc7befcbb7d",
        "version" : "10.29.0"
      }
    },
    {
      "identity" : "googleappmeasurement",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleAppMeasurement.git",
      "state" : {
        "revision" : "fe727587518729046fc1465625b9afd80b5ab361",
        "version" : "10.28.0"
      }
    },
    {
      "identity" : "googledatatransport",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleDataTransport.git",
      "state" : {
        "revision" : "a637d318ae7ae246b02d7305121275bc75ed5565",
        "version" : "9.4.0"
      }
    },
    {
      "identity" : "googleutilities",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleUtilities.git",
      "state" : {
        "revision" : "57a1d307f42df690fdef2637f3e5b776da02aad6",
        "version" : "7.13.3"
      }
    },
    {
      "identity" : "grpc-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/grpc-binary.git",
      "state" : {
        "revision" : "e9fad491d0673bdda7063a0341fb6b47a30c5359",
        "version" : "1.62.2"
      }
    },
    {
      "identity" : "gtm-session-fetcher",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/gtm-session-fetcher.git",
      "state" : {
        "revision" : "a2ab612cb980066ee56d90d60d8462992c07f24b",
        "version" : "3.5.0"
      }
    },
    {
      "identity" : "interop-ios-for-google-sdks",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/interop-ios-for-google-sdks.git",
      "state" : {
        "revision" : "2d12673670417654f08f5f90fdd62926dc3a2648",
        "version" : "100.0.0"
      }
    },
    {
      "identity" : "keychainaccess",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/kishikawakatsumi/KeychainAccess.git",
      "state" : {
        "branch" : "master",
        "revision" : "e0c7eebc5a4465a3c4680764f26b7a61f567cdaf"
      }
    },
    {
      "identity" : "leveldb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/leveldb.git",
      "state" : {
        "revision" : "a0bc79961d7be727d258d33d5a6b2f1023270ba1",
        "version" : "1.22.5"
      }
    },
    {
      "identity" : "lottie-ios",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/airbnb/lottie-ios.git",
      "state" : {
        "revision" : "769b88d83a42ca8d5572b020c96f47e3690b3796",
        "version" : "4.4.3"
      }
    },
    {
      "identity" : "nanopb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/nanopb.git",
      "state" : {
        "revision" : "b7e1104502eca3a213b46303391ca4d3bc8ddec1",
        "version" : "2.30910.0"
      }
    },
    {
      "identity" : "promises",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/promises.git",
      "state" : {
        "revision" : "540318ecedd63d883069ae7f1ed811a2df00b6ac",
        "version" : "2.4.0"
      }
    },
    {
      "identity" : "swift-protobuf",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-protobuf.git",
      "state" : {
        "revision" : "d57a5aecf24a25b32ec4a74be2f5d0a995a47c4b",
        "version" : "1.27.0"
      }
    }
  ],
  "version" : 3
}

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

PODS:
  - Firebase (10.14.0):
    - Firebase/Core (= 10.14.0)
  - Firebase/Core (10.14.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 10.14.0)
  - Firebase/CoreOnly (10.14.0):
    - FirebaseCore (= 10.14.0)
  - FirebaseABTesting (10.25.0):
    - FirebaseCore (~> 10.0)
  - FirebaseAnalytics (10.14.0):
    - FirebaseAnalytics/AdIdSupport (= 10.14.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (10.14.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleAppMeasurement (= 10.14.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseCore (10.14.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Logger (~> 7.8)
  - FirebaseCoreInternal (10.25.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseInstallations (10.25.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)
  - FirebaseMessaging (10.14.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Reachability (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseRemoteConfig (10.14.0):
    - FirebaseABTesting (~> 10.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - Google-Maps-iOS-Utils (4.2.2):
    - Google-Maps-iOS-Utils/Clustering (= 4.2.2)
    - Google-Maps-iOS-Utils/Geometry (= 4.2.2)
    - Google-Maps-iOS-Utils/GeometryUtils (= 4.2.2)
    - Google-Maps-iOS-Utils/Heatmap (= 4.2.2)
    - Google-Maps-iOS-Utils/QuadTree (= 4.2.2)
    - GoogleMaps (~> 7.3)
  - Google-Maps-iOS-Utils/Clustering (4.2.2):
    - Google-Maps-iOS-Utils/QuadTree
    - GoogleMaps (~> 7.3)
  - Google-Maps-iOS-Utils/Geometry (4.2.2):
    - GoogleMaps (~> 7.3)
  - Google-Maps-iOS-Utils/GeometryUtils (4.2.2):
    - GoogleMaps (~> 7.3)
  - Google-Maps-iOS-Utils/Heatmap (4.2.2):
    - Google-Maps-iOS-Utils/QuadTree
    - GoogleMaps (~> 7.3)
  - Google-Maps-iOS-Utils/QuadTree (4.2.2):
    - GoogleMaps (~> 7.3)
  - GoogleAppMeasurement (10.14.0):
    - GoogleAppMeasurement/AdIdSupport (= 10.14.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/AdIdSupport (10.14.0):
    - GoogleAppMeasurement/WithoutAdIdSupport (= 10.14.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/WithoutAdIdSupport (10.14.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleDataTransport (9.4.1):
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleMaps (7.3.0):
    - GoogleMaps/Maps (= 7.3.0)
  - GoogleMaps/Base (7.3.0)
  - GoogleMaps/Maps (7.3.0):
    - GoogleMaps/Base
  - GoogleUtilities (7.13.2):
    - GoogleUtilities/AppDelegateSwizzler (= 7.13.2)
    - GoogleUtilities/Environment (= 7.13.2)
    - GoogleUtilities/ISASwizzler (= 7.13.2)
    - GoogleUtilities/Logger (= 7.13.2)
    - GoogleUtilities/MethodSwizzler (= 7.13.2)
    - GoogleUtilities/Network (= 7.13.2)
    - "GoogleUtilities/NSData+zlib (= 7.13.2)"
    - GoogleUtilities/Privacy (= 7.13.2)
    - GoogleUtilities/Reachability (= 7.13.2)
    - GoogleUtilities/SwizzlerTestHelpers (= 7.13.2)
    - GoogleUtilities/UserDefaults (= 7.13.2)
  - GoogleUtilities/AppDelegateSwizzler (7.13.2):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
    - GoogleUtilities/Privacy
  - GoogleUtilities/Environment (7.13.2):
    - GoogleUtilities/Privacy
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/ISASwizzler (7.13.2):
    - GoogleUtilities/Privacy
  - GoogleUtilities/Logger (7.13.2):
    - GoogleUtilities/Environment
    - GoogleUtilities/Privacy
  - GoogleUtilities/MethodSwizzler (7.13.2):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/Network (7.13.2):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Privacy
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.13.2)":
    - GoogleUtilities/Privacy
  - GoogleUtilities/Privacy (7.13.2)
  - GoogleUtilities/Reachability (7.13.2):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/SwizzlerTestHelpers (7.13.2):
    - GoogleUtilities/MethodSwizzler
  - GoogleUtilities/UserDefaults (7.13.2):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - MapboxCommon (24.4.0)
  - MapboxCoreMaps (11.4.0):
    - MapboxCommon (~> 24.4)
  - MapboxMaps (11.4.0):
    - MapboxCommon (= 24.4.0)
    - MapboxCoreMaps (= 11.4.0)
    - Turf (= 2.8.0)
  - nanopb (2.30909.1):
    - nanopb/decode (= 2.30909.1)
    - nanopb/encode (= 2.30909.1)
  - nanopb/decode (2.30909.1)
  - nanopb/encode (2.30909.1)
  - PostHog (3.0.0)
  - PromisesObjC (2.4.0)
  - Realm (10.50.0):
    - Realm/Headers (= 10.50.0)
  - Realm/Headers (10.50.0)
  - RealmSwift (10.50.0):
    - Realm (= 10.50.0)
  - Turf (2.8.0)

DEPENDENCIES:
  - Firebase (= 10.14.0)
  - FirebaseCore (= 10.14.0)
  - FirebaseMessaging (= 10.14.0)
  - FirebaseRemoteConfig (= 10.14.0)
  - Google-Maps-iOS-Utils (= 4.2.2)
  - GoogleMaps (= 7.3.0)
  - GoogleUtilities
  - MapboxMaps (= 11.4.0)
  - PostHog (~> 3.0.0)
  - Realm
  - RealmSwift

SPEC REPOS:
  https://github.com/CocoaPods/Specs.git:
    - Firebase
    - FirebaseABTesting
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreInternal
    - FirebaseInstallations
    - FirebaseMessaging
    - FirebaseRemoteConfig
    - Google-Maps-iOS-Utils
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleMaps
    - GoogleUtilities
    - MapboxCommon
    - MapboxCoreMaps
    - MapboxMaps
    - nanopb
    - PostHog
    - PromisesObjC
    - Realm
    - RealmSwift
    - Turf

SPEC CHECKSUMS:
  Firebase: 6c1bf3f534bc422d52af2e41fe0d50bf08b6b773
  FirebaseABTesting: e6e3c3e0e35813874f571d1b7bdae2aab319dd38
  FirebaseAnalytics: 5c6d58814afa4db82cf7fdbc02b0b0e2fa3d43ff
  FirebaseCore: 6fc17ac9f03509d51c131298aacb3ee5698b4f02
  FirebaseCoreInternal: 910a81992c33715fec9263ca7381d59ab3a750b7
  FirebaseInstallations: 91950fe859846fff0fbd296180909dd273103b09
  FirebaseMessaging: 1077a4499f0c0a140b9a2e34fe08a1acc806b36d
  FirebaseRemoteConfig: e22a706fa7ecc64135325f4c430a15af1e795535
  Google-Maps-iOS-Utils: f77eab4c4326d7e6a277f8e23a0232402731913a
  GoogleAppMeasurement: 7fee012a868315d418f365fbc8d394d8e020e749
  GoogleDataTransport: 6c09b596d841063d76d4288cc2d2f42cc36e1e2a
  GoogleMaps: a146f275ee429d14822178c7a841c03366ec92a1
  GoogleUtilities: c56430aef51a1aa57b25da78c3f8397e522c67b7
  MapboxCommon: 6acbd8ff41d66abf498e1558b0739f25c562945a
  MapboxCoreMaps: f306bb1b10ebe995a2247b40e99322ab7f9b8071
  MapboxMaps: 82044383ae19ec124ff444ec4b5d3ce82cb36ba5
  nanopb: d4d75c12cd1316f4a64e3c6963f879ecd4b5e0d5
  PostHog: ce38cb62a50eda5c8975faef57fcc3e6c9dac2b3
  PromisesObjC: f5707f49cb48b9636751c5b2e7d227e43fba9f47
  Realm: a0a6a99e3dfa8959358a95c3c05845b5e5d6af30
  RealmSwift: fa111fb98e092a4dff1d0785ad0c3483feda607a
  Turf: aa2ede4298009639d10db36aba1a7ebaad072a5e

PODFILE CHECKSUM: dc771c21b462dd2907f2c0ee886a7b0af8e6bce6

COCOAPODS: 1.15.2

```

</details>

**Comment by timothy-moonware** [comment]
I upgraded my Pods to use Firebase 10.29.0, and I am getting a different missing file on compilation :
[18:57:22]: ▸ Compiling cct.nanopb.c
[18:57:22]: ▸ ❌  /Users/distiller/project/halo/Pods/GoogleDataTransport/GoogleDataTransport/GDTCCTLibrary/Protogen/nanopb/cct.nanopb.h:24:10: 'GoogleDataTransport/GDTCCTLibrary/Protogen/nanopb/compliance.nanopb.h' file not found
[18:57:22]: ▸ #include "GoogleDataTransport/GDTCCTLibrary/Protogen/nanopb/compliance.nanopb.h"

**Comment by paulb777** [comment]
There may be an issue in the Xcode project configuration. We'll likely need a reproducible example to help.

**Comment by timothy-moonware** [comment]
What can I provide to you? Would you need github access?

**Comment by paulb777** [comment]
Ideally a minimally reproducible example with step-by-step instructions that demonstrates the issue.

**Comment by timothy-moonware** [comment]
So, after further investigation, this may be an issue with Cocoapods.
On a fresh install on an M1 machine, files are missing from GoogleDataTransport after first pod install.
Once you run `pod deintegrate` and `pod install` again, the files get downloaded.

**Comment by timothy-moonware** [comment]
Just to update pod deintegrate has solved this issue for me. Closing...
