### ISSUE TITLE
Not getting events logs on the DebugView for the build downloaded from the testFlight

### ISSUE THREAD

**Issue by Vikrant2411** [firebase/firebase-ios-sdk#13260]
### Description

I have uploaded UAT environment build to testflight to test the Firebase logs on debug view, but I am not able to get the event logs on the Debug view of the firebase. 

### Reproducing the issue

Create a build of the app of the test environment and upload it to testFlight by integrating firebase analytics and adding the event logs code and when downloading the build from the testflight it is not displaying events logs on Debug view.

### Firebase SDK Version

10.25.0

### Xcode Version

15.3

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by morganchen12** [comment]
DebugView requires you run your app in a development environment with the `-FIRDebugEnabled` launch parameter. You will not be able to pass this parameter in when launching a TestFlight build from the home screen of your device.

**Comment by Vikrant2411** [comment]
Is there a way with which I can test the event's logs with development environment on testFlight build or any other way with which I can test this without launching the build from the xcode directly?

**Comment by morganchen12** [comment]
You can log events as you would normally and wait a day for them to show up in console. Realtime event logging is supported only via DebugView.
