### ISSUE TITLE
Module 'FirebaseRemoteConfigInterop' not found

### ISSUE THREAD

**Issue by AnKoCare** [firebase/firebase-ios-sdk#13279]
### Description

Firebase SDK Version: Unity 12.1.0 
Xcode Version: 15.4 
Installation Method: CocoaPods
 Firebase Product: Remote Config 
Targeted Platform: iOS

Issue: I got an error: Module 'FirebaseRemoteConfigInterop' not found.

I tried cleaning the build folder, reinstalling pods, and reimporting the Remote Config in the Unity project, but I still got this error.
<img width="770" alt="Screenshot 2024-07-14 at 15 31 44" src="https://github.com/user-attachments/assets/2a26b359-e6e5-4da8-805c-c4b4f73b8ff8">
<img width="1395" alt="Screenshot 2024-07-14 at 15 34 11" src="https://github.com/user-attachments/assets/542b5f21-95b1-4c40-8101-5085ecd36984">
<img width="385" alt="Screenshot 2024-07-14 at 16 08 05" src="https://github.com/user-attachments/assets/df2b8775-15d8-4e4d-8311-8ba7f7cc2cf5">

### Reproducing the issue

I build the game in Unity and open it in Xcode. I ran pod install --repo-update in the game build folder.

### Firebase SDK Version

12.1.0

### Xcode Version

15.4

### Installation Method

CocoaPods

### Firebase Product(s)

Remote Config

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Pods/FirebaseRemoteConfig/FirebaseRemoteConfig/Sources/RCNConfigFetch.m:28:9 Module 'FirebaseRemoteConfigInterop' not found
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @AnKoCare, I tried to reproduce the issue in native iOS, but I'm unable to get the same error. With this, please file a ticket to [Unity SDK repo](https://github.com/firebase/firebase-unity-sdk/issues) as this could be a Unity-related issue. Thanks.
