### ISSUE TITLE
SPM: Binary frameworks seem to be with no stripped symbols 

### ISSUE THREAD

**Issue by jesus-mg-ios** [firebase/firebase-ios-sdk#13270]
### Description

I notice that maybe binaries have no stripped symbols. For example:

https://dl.google.com/firebase/ios/swiftpm/10.25.0/FirebaseAnalytics.zip -> Size without strip 169Ks and after strip 149Ks
`strip -rSTx`

Taking in consideration DSYMs would be generated before stripping and after stripping frameworks must be signed, I'm wondering if it's possible do it for all frameworks, and delivering DSYMs anywhere

Thanks in advance.

### Firebase SDK Version

10.25.0

### Xcode Version

15.0

### Installation Method

Swift Package Manager

### Firebase Product(s)

AB Testing, Analytics, App Check, App Distribution, Authentication, Crashlytics, Database, DynamicLinks, Firestore, Functions, In-App Messaging, Installations, ML Model Downloader, Messaging, Performance, Remote Config, Storage, VertexAI, All, Infrastructure

### Targeted Platforms

All

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
@jesus-mg-ios Would you say more about the use case and why the dSyms are needed?

**Comment by jesus-mg-ios** [comment]
I stripped the DSYMs from the frameworks on my own.
