### ISSUE TITLE
session_start event is not getting triggered every time the user opens the app

### ISSUE THREAD

**Issue by Vikrant2411** [firebase/firebase-ios-sdk#13271]
### Description

As I was testing it is not getting triggered every time I am opening the app, it only logs for the first install or after 30 minutes, it is getting logged for me.

### Reproducing the issue

session_start is not getting triggered on every time app got opened. 

### Firebase SDK Version

10.25.0

### Xcode Version

15.3

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
This is working as intended. From https://support.google.com/analytics/answer/12798876?sjid=8807791687769879121-NC, a session lasts for 30 minutes.

**Comment by Vikrant2411** [comment]
Hi @paulb777 ,
Is it possible we can add this event on every login in our app and also on every time app returns to foreground from background or from terminated state?

**Comment by rizafran** [comment]
Hi @Vikrant2411, the `session_start` event will automatically be collected as long as there's no current session or if the app was in the foreground for more than 10 seconds. You may check this [blog](https://firebase.blog/posts/2018/12/new-changes-sessions-user-engagement) for more info.

**Comment by Vikrant2411** [comment]
Hi @rizafran ,
I got this. But I have a query, that if user logs out form app and log_in again to the app, still the session count remains one if user did it within 30 minutes time frame, or it will log session_start  event again on every login?

**Comment by rizafran** [comment]
@Vikrant2411, yes the session count will remain as one if a user did it within 30 minutes. You may also check this [doc](https://support.google.com/analytics/answer/9191807) regarding Analytics sessions.
