### ISSUE TITLE
Firebase Crashlytics exhibits a hanging behavior after tapping any button or user interaction upon launching the app in SwiftUI - Logs from Instrument

### ISSUE THREAD

**Issue by pranavansp** [firebase/firebase-ios-sdk#13311]
### Description

Firebase Crashlytics exhibits a hanging behaviour after tapping any button or user interaction upon launching the app in SwiftUI - The screenshot from the Instrument I have attached, It's says the problem with `FIRCLSBinaryImageRecordLibraryFrameworkInfo`

<img width="1322" alt="Screenshot 2024-07-18 at 5 23 05 PM" src="https://github.com/user-attachments/assets/78df77c4-59ff-4ff7-9516-ea2cc34abb39">

### Reproducing the issue

Integrate Crashlytics with SwiftUI code Launch it and tap any button or user interaction components only upon launching the app in SwiftUI.

### Firebase SDK Version

10.24.0

### Xcode Version

15.4

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
599.00 ms   22.4%	0 s	 	        FIRCLSProcessBinaryImageChange
598.00 ms   22.3%	0 s	 	         FIRCLSBinaryImageRecordSlice
447.00 ms   16.7%	0 s	 	          FIRCLSBinaryImageRecordLibraryFrameworkInfo
74.00 ms    2.7%	0 s	 	          FIRCLSMachOSliceGetExecutablePath
38.00 ms    1.4%	0 s	 	          FIRCLSBinaryImageRecordDetails
16.00 ms    0.5%	0 s	 	          FIRCLSFileWriteHashEntryString
6.00 ms    0.2%	0 s	 	          FIRCLSFileWriteSectionEnd
6.00 ms    0.2%	0 s	 	          FIRCLSFileWriteHashEnd
6.00 ms    0.2%	0 s	 	          FIRCLSFileWriteSectionStart
4.00 ms    0.1%	0 s	 	          FIRCLSFileWriteHashStart
1.00 ms    0.0%	0 s	 	          FIRCLSFileClose
1.00 ms    0.0%	1.00 ms	 	         FIRCLSBinaryImageStoreNode
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
Please try updating to 10.29.0.  There have been some related fixes in recent releases.

**Comment by pranavansp** [comment]
Thank you for the quick update, I could not be reproducible on 10.29.0.
