### ISSUE TITLE
Potential data race in Storage method

### ISSUE THREAD

**Issue by jesus-mg-ios** [firebase/firebase-ios-sdk#13369]
### Description

<img width="1103" alt="image" src="https://github.com/user-attachments/assets/5a6e70f0-0033-41cd-88f8-726241f8179c">

### Reproducing the issue

Define a storage instance and call `storage.reference(forURL: String)` from multiple threads and sometimes the warn in Xcode happened.
<img width="755" alt="image" src="https://github.com/user-attachments/assets/413d2c23-cfc4-4418-a5b3-7639b69b8d73">

```
 let task = Task {
            try await withCheckedThrowingContinuation { continuation in
                let storageReference = self.storage.reference(forURL: referencePath)
                storageReference.getData() { data, error in
                    if let error {
                        continuation.resume(throwing: error)
                        return
                    }
                    guard let data, !data.isEmpty else {
                        continuation.resume(throwing: Error.error)
                        return
                    }
                    continuation.resume(returning: data)
                }
            } as Data
        }

 return await task.value

```

### Firebase SDK Version

10.25.0

### Xcode Version

15.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Storage

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
@jesus-mg-ios Thanks for the report. Would you check if #13381 fixes your test case?

**Comment by paulb777** [comment]
Nevermind. `static` methods in an actor aren't thread safe. A fix will take more investigation.

**Comment by jesus-mg-ios** [comment]
Maybe a dispatch queue async with a  barrier flag could do the trick.
