### ISSUE TITLE
Remote config fetch never returns on first app install #11770 in 10.25.0

### ISSUE THREAD

**Issue by jesus-mg-ios** [firebase/firebase-ios-sdk#13370]
### Description

Same issue reproduced with simulator in 10.25.0 #11770 

### Firebase SDK Version

10.25.0

### Xcode Version

15.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Remote Config

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
@jesus-mg-ios Thanks for reporting. Are you able to share a reproduction?

**Comment by jesus-mg-ios** [comment]
Not, right now I'm not able to share a repro code, but I notice it happens when the Mac storage (for iOS simulator) is full or almost full. I don't know if it makes sense for you.

**Comment by paulb777** [comment]
cc: @htcgh ^

**Comment by MichaelVerdon** [comment]
I think it can be expected to get strange behaviour from any application when device storage is near-full or full. Can you try clearing up some space and seeing if the issue is still there?
