### ISSUE TITLE
Error/Warning messages still use goo.gl shortener, which is being retired

### ISSUE THREAD

**Issue by bgrzesiak-fetch** [firebase/firebase-ios-sdk#13382]
### Description

Some SDK warnings still use goo.gl as the URL shortener for "Read more" links. [This service is being retired](https://developers.googleblog.com/en/google-url-shortener-links-will-no-longer-be-available/). The messages need to use unshortened URLs, or they need to use a different shortening service.

### Reproducing the issue

For example, install the SDK into an iOS app and **don't** call `FirebaseApp.configure()`. You should get a message like:

```
[FirebaseCore][I-COR000003] The default Firebase app has not yet been configured. Add `FirebaseApp.configure()` to your application initialization. This can be done in in the App Delegate's application(_:didFinishLaunchingWithOptions:)` (or the `@main` struct's initializer in SwiftUI). Read more: https://goo.gl/ctyzm8.
```

I've confirmed this on 10.22.1, but this particular message is still on [`main`](https://github.com/firebase/firebase-ios-sdk/blob/main/FirebaseCore/Sources/FIRApp.m#L235)

### Firebase SDK Version

10.22.1

### Xcode Version

15.4

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
10.22.1 - [FirebaseCore][I-COR000003] The default Firebase app has not yet been configured. Add `FirebaseApp.configure()` to your application initialization. This can be done in in the App Delegate's application(_:didFinishLaunchingWithOptions:)` (or the `@main` struct's initializer in SwiftUI). Read more: https://goo.gl/ctyzm8.
```

**Comment by paulb777** [comment]
Thanks for the report. I've started a PR to fix in #13383
