### ISSUE TITLE
currentUser not returning nil after deleting the app

### ISSUE THREAD

**Issue by vcGF** [firebase/firebase-ios-sdk#1340]
* Xcode version: 9
  * Firebase SDK version: 5
  * Firebase Component: Auth
  * Component version: ??

#### Steps to reproduce:

- log in using fb
- delete the app from simulator
- try to check for existing user

Issue : After deleting the app, the currentUser returned is not nil, hence giving the impression that the user is still logged in. 

I tried to check with 

> Auth.auth().currentUser?.reload(completion: { (error) in
                if let error = error {
                    print("checkIfUserSignedIn \(error.localizedDescription)")
                }
            })

but this is still not returning an error.

#### Relevant Code:

> func check() {
        
        if Auth.auth().currentUser != nil {
            
            
            Auth.auth().currentUser?.reload(completion: { (error) in
                if let error = error {
                    print("checkIfUserSignedIn \(error.localizedDescription)")

                }
            })
            
            // User is signed in.
            // ...
            print("checkIfUserSignedIn : User ok")
            if ((FBSDKAccessToken.current()) != nil) {
                print("User is logged with FB")
            }
            
        } else {
            //not signed in -> insert landing
            print("checkIfUserSignedIn : User nok")
            self.insertLandingScreen()
        }
    }

**Comment by vcGF** [comment]
Do we really need to rely on such tricks ?

[https://stackoverflow.com/questions/4747404/delete-keychain-items-when-an-app-is-uninstalled](url)

**Comment by vcGF** [comment]
Really ?

But it seems fairly basic but essential that when the app gets deleted, the credentials go away as well.

At the moment, after deletion, the currentUser is returning the previous object , hence need to use some tricks to figure out if this data is actually valid.

Bit odd no ?

**Comment by morganchen12** [comment]
The data is no more or less valid than a user loaded from Keychain without an app reinstall. Firebase Auth doesn't validate logins at app start when loading users from Keychain. See [this comment](https://github.com/firebase/firebase-ios-sdk/issues/198#issuecomment-324400360) for more details.

It may also be impractical to implement this new behavior of erasing keychain users on uninstall, since iOS doesn't provide any uninstall code execution hooks (for good reason).

**Comment by paulb777** [comment]
Similar issue and answer as #198
