### ISSUE TITLE
Code=40 "Message too long" Error

### ISSUE THREAD

**Issue by yildirimatcioglu** [firebase/firebase-ios-sdk#13415]
### Description

my app is uploading videos to Firebase storage and it was working fine until 1 hour ago. Now it is giving error that says "Code=40 'Message too long'". I did not change anything and the video I want to upload is 15 seconds and 1.2 mb. 

### Firebase SDK Version

10.29.0

### Xcode Version

15.4

### Installation Method

Swift Package Manager

### Firebase Product(s)

Storage

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Task <68C7A14A-0620-40E0-A095-72DE0A62A9A8>.<1> finished with error [40] Error Domain=NSPOSIXErrorDomain Code=40 "Message too long" UserInfo={_NSURLErrorFailingURLSessionTaskErrorKey=BackgroundUploadTask <68C7A14A-0620-40E0-A095-72DE0A62A9A8>.<1>, _kCFStreamErrorDomainKey=1, NSErrorPeerAddressKey={length = 16, bytes = 0x100201bbacd9116a0000000000000000}, _kCFStreamErrorCodeKey=40, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "BackgroundUploadTask <68C7A14A-0620-40E0-A095-72DE0A62A9A8>.<1>",
    "LocalUploadTask <68C7A14A-0620-40E0-A095-72DE0A62A9A8>.<1>"
)}
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reporting, @yildirimatcioglu. It's possible that this might be an intermittent issue. May I know if you're still seeing the same issue? If so, is the issue also reproducible using other network or device? A reproducible example would also be great in order investigate.
