### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_FIRAppAssociationRegistration Undefined symbol: _kFIRLoggerMLKit

### ISSUE THREAD

**Issue by kusainovaka** [firebase/firebase-ios-sdk#13421]
### Description

After updating from 7 version to 10
Has error project didn't build 
```
Undefined symbol: _OBJC_CLASS_$_FIRAppAssociationRegistration
Undefined symbol: _kFIRLoggerMLKit
Linker command failed with exit code 1 (use -v to see invocation)
```

### Reproducing the issue

<img width="429" alt="Снимок экрана 2024-07-29 в 16 25 57" src="https://github.com/user-attachments/assets/ed7257b5-96dc-4fba-98af-88949b316a22">

### Firebase SDK Version

10.29

### Xcode Version

15.4

### Installation Method

Swift Package Manager

### Firebase Product(s)

AB Testing, Analytics, App Distribution, Crashlytics, In-App Messaging, ML Model Downloader

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

{
  "originHash" : "c038abf2cef981f5fe7efeec7c8be5baaddd143e1c59c873459563097b47d427",
  "pins" : [
   
    {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk",
      "state" : {
        "revision" : "eca84fd638116dd6adb633b5a3f31cc7befcbb7d",
        "version" : "10.29.0"
      }
    },
  
    {
      "identity" : "google-api-objectivec-client-for-rest",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/google-api-objectivec-client-for-rest",
      "state" : {
        "revision" : "a8c1e0b1173659d0be452680582c28556372ef74",
        "version" : "3.5.5"
      }
    },
    {
      "identity" : "googleappmeasurement",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleAppMeasurement.git",
      "state" : {
        "revision" : "fe727587518729046fc1465625b9afd80b5ab361",
        "version" : "10.28.0"
      }
    },
    {
      "identity" : "googledatatransport",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleDataTransport.git",
      "state" : {
        "revision" : "a637d318ae7ae246b02d7305121275bc75ed5565",
        "version" : "9.4.0"
      }
    },
    {
      "identity" : "googleutilities",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleUtilities.git",
      "state" : {
        "revision" : "8e5d57ed87057cd7b0e4e8f474d9e78f73eb85f7",
        "version" : "7.13.2"
      }
    },
    {
      "identity" : "grpc-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/grpc-binary.git",
      "state" : {
        "revision" : "e9fad491d0673bdda7063a0341fb6b47a30c5359",
        "version" : "1.62.2"
      }
    },
    {
      "identity" : "gtm-session-fetcher",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/gtm-session-fetcher.git",
      "state" : {
        "revision" : "a2ab612cb980066ee56d90d60d8462992c07f24b",
        "version" : "3.5.0"
      }
    },
    {
      "identity" : "interop-ios-for-google-sdks",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/interop-ios-for-google-sdks.git",
      "state" : {
        "revision" : "2d12673670417654f08f5f90fdd62926dc3a2648",
        "version" : "100.0.0"
      }
    },
   
    {
      "identity" : "swift-protobuf",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-protobuf.git",
      "state" : {
        "revision" : "d57a5aecf24a25b32ec4a74be2f5d0a995a47c4b",
        "version" : "1.27.0"
      }
    },

  ],
  "version" : 3
}

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by kusainovaka** [comment]
we don't use CocoaPods, only spm

**Comment by Sagar1upa** [comment]
I am still facing the same problem with upgrading Firebase from 9.0.0 to 10.29.0 using Swift Package Manager, and I am stuck. Please find the screenshot of the issue attached.
![grfd](https://github.com/user-attachments/assets/e960f222-3bbf-4533-8351-15f20d833cc1)

**Comment by kusainovaka** [comment]
@Sagar1upa  in my keys we use locally  old frameworks FirebaseMLVision.framework, MLVisionHelpers(googleToolboxForMac, firebaseMLCommon, firebaseMLVision) we refused from this framework, delete them and problem resolved.

**Comment by Sagar1upa** [comment]
Please guide me on which framework I need to delete because I haven't used any of the frameworks you mentioned in my project.

**Comment by paulb777** [comment]
@kusainovaka Glad you worked it out!

@Sagar1upa You likely have a different issue related to not linking FirebaseCore. Please open a separate issue with the template filled out if you need additional assistance.

**Comment by Sagar1upa** [comment]
@paulb777  This issue is related to Firebase. If I remove or downgrade the Firebase version to 9.0.0, it works correctly.
