### ISSUE TITLE
Fortify static scan issues

### ISSUE THREAD

**Issue by spraveenk91** [firebase/firebase-ios-sdk#13422]
### Description

I am using FirebaseCrashlytics through Cocoapods in my project, version details mentioned below:

>   pod 'Firebase/Crashlytics', '10.18.0'
>   pod 'Firebase/Analytics', '10.18.0'

We have [Fortify Static Code Analyzer](https://www.opentext.com/products/fortify-static-code-analyzer) integrated to our application and it has pointed several issues as mentioned below in different categories:

### Insecure Transport: Weak SSL Protocol

Not using TLS version 1.2 or above version caused this issue in below places

1. Pods/FirebaseCrashlytics/Crashlytics/Shared/FIRCLSNetworking/FIRCLSFABNetworkClient.m - Line no: 37
2. Pods/GoogleDataTransport/GoogleDataTransport/GDTCCTLibrary/GDTCCTUploadOperation.m - Line no: 117
3. Pods/GoogleUtilities/GoogleUtilities/Network/GULNetworkURLSession.m - Line no: 149
4. Pods/GoogleUtilities/GoogleUtilities/Network/GULNetworkURLSession.m - Line no: 157
5. Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsAPIService.m - Line no: 73
6. Pods/GoogleUtilities/GoogleUtilities/Network/GULNetworkURLSession.m - Line no: 210

----

### Insecure Storage: Lacking Data Protection

No file protection for the data stored using `NSFileManager`

1. Pods/FirebaseCrashlytics/Crashlytics/Crashlytics/Models/FIRCLSFileManager.m - Line no: 64
2. Pods/FirebaseCrashlytics/Crashlytics/Crashlytics/Models/FIRCLSFileManager.m - Line no: 260
3. Pods/GoogleUtilities/GoogleUtilities/Environment/GULHeartbeatDateStorage.m - Line no: 150
4. Pods/GoogleUtilities/GoogleUtilities/Network/GULNetworkURLSession.m - Line no: 75
5. Pods/FirebaseCoreInternal/FirebaseCore/Internal/Sources/HeartbeatLogging/Storage.swift - Line no: 78
6. Pods/FirebaseCoreInternal/FirebaseCore/Internal/Sources/HeartbeatLogging/Storage.swift - Line no: 58

----

Do firebase have any plans to fix them in near future to overcome these issues?

### Firebase SDK Version

10.18

### Xcode Version

15.2

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

  - Firebase/Analytics (10.18.0):
    - Firebase/Core
  - Firebase/Core (10.18.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 10.18.0)
  - Firebase/CoreOnly (10.18.0):
    - FirebaseCore (= 10.18.0)
  - Firebase/Crashlytics (10.18.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 10.18.0)
  - FirebaseAnalytics (10.18.0):
    - FirebaseAnalytics/AdIdSupport (= 10.18.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (10.18.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleAppMeasurement (= 10.18.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseCore (10.18.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.12)
    - GoogleUtilities/Logger (~> 7.12)
  - FirebaseCoreExtension (10.27.0):
    - FirebaseCore (~> 10.0)
  - FirebaseCoreInternal (10.27.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseCrashlytics (10.18.0):
    - FirebaseCore (~> 10.5)
    - FirebaseInstallations (~> 10.0)
    - FirebaseSessions (~> 10.5)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.8)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (~> 2.1)
  - FirebaseInstallations (10.27.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)
  - FirebaseSessions (10.27.0):
    - FirebaseCore (~> 10.5)
    - FirebaseCoreExtension (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.13)
    - GoogleUtilities/UserDefaults (~> 7.13)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesSwift (~> 2.1)
  - GoogleAppMeasurement (10.18.0):
    - GoogleAppMeasurement/AdIdSupport (= 10.18.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/AdIdSupport (10.18.0):
    - GoogleAppMeasurement/WithoutAdIdSupport (= 10.18.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/WithoutAdIdSupport (10.18.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleDataTransport (9.4.1):
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/AppDelegateSwizzler (7.13.3):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
    - GoogleUtilities/Privacy
  - GoogleUtilities/Environment (7.13.3):
    - GoogleUtilities/Privacy
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/Logger (7.13.3):
    - GoogleUtilities/Environment
    - GoogleUtilities/Privacy
  - GoogleUtilities/MethodSwizzler (7.13.3):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/Network (7.13.3):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Privacy
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.13.3)":
    - GoogleUtilities/Privacy
  - GoogleUtilities/Privacy (7.13.3)
  - GoogleUtilities/Reachability (7.13.3):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/UserDefaults (7.13.3):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy

```

</details>

**Comment by paulb777** [comment]
According to https://support.apple.com/en-qa/guide/security/sec100a75d12/web, after iOS 12.2, TLS 1.3 is used by default.

Please provide more detail about the concern.

**Comment by spraveenk91** [comment]
Hello @paulb777 

Please, find the attachment of the code snippet where it is pointing TLS version 1.0 on couple of files:

* FIRCLSFABNetworkClient.m

![Screenshot 2024-08-05 at 3 46 43 PM](https://github.com/user-attachments/assets/19b9f167-af7f-4f8e-8cde-dfd61a2135d6)

* GDTCCTUploadOperation.m

![Screenshot 2024-08-05 at 3 47 13 PM](https://github.com/user-attachments/assets/60f5696a-e945-409c-913e-c863ccb52771)

**Comment by paulb777** [comment]
That is the minimum version supported by the code. According to the link I shared above, it actually uses 1.3

**Comment by paulb777** [comment]
Closing since there are no clear actions.

**Comment by spraveenk91** [comment]
@paulb777 I understand that the link provided mentions `1.3`, but shouldn't it explicitly point to `1.2` as the minimum protocol?
