### ISSUE TITLE
[FR]: Support mocking for StorageReference

### ISSUE THREAD

**Issue by mjyip-retro** [firebase/firebase-ios-sdk#13452]
### Description

Because it looks like FirebaseStorage is an [open class](https://blog.eidinger.info/subclassing-an-open-swift-class-is-not-always-possible), I cannot subclass StorageReference (because init is not public) for mocking purposes. The compiler throws an error that I cannot call super.init() because it is not accessible. 

The ideal solution would be to make the init() method in StorageReference public so I can mock the class.

Please let me know if there is a better workaround for mocking StorageReference / Firebase storage uploading data.

```
class MockStorageReference: StorageReference {
   override init() {
       super.init() // 'StorageReference' initializer is inaccessible due to 'internal' protection level error
   }
}
```

### Firebase Product(s)

Storage

**Comment by paulb777** [comment]
Thanks for the FR and link.  The [conclusion](https://blog.eidinger.info/subclassing-an-open-swift-class-is-not-always-possible#heading-conclussion) is convincing that we should do one or the other?

As a workaround, what about `@testable import FirebaseStorage`?

**Comment by mjyip-retro** [comment]
Thanks for the suggestion for the workaround! I wasn't aware of `@testable`annotation. I ended up creating a MockClient wrapper as a workaround. Thanks!
