### ISSUE TITLE
[FR]: When we transfer an app on the App Store, what actions need to be taken for Sign in With Apple?

### ISSUE THREAD

**Issue by fangyuxi** [firebase/firebase-ios-sdk#13456]
### Description

After we transfer an app on the App Store, if the old users use Sign in With Apple again, a new identifier will be generated according to Apple's documentation, resulting in a new user. How should this be resolved?

### Firebase Product(s)

Authentication

**Comment by aligermiyanoglu** [comment]
hello there, 
We recently had app transfer, this blog posts gives some insights actually also specific to Firebase as well
https://medium.com/@hell-io/a-great-migration-transfer-your-ios-app-without-losing-firebase-users-91252c431acf
Hope it helps
