### ISSUE TITLE
Firebase installation issue 11.0.0

### ISSUE THREAD

**Issue by zoraiz-WOL** [firebase/firebase-ios-sdk#13467]
### Description

[!] Error installing Firebase
[!] /usr/bin/git clone https://github.com/firebase/firebase-ios-sdk.git /var/folders/wt/_g4gd3cd7zg5x0p3p71ywqp00000gn/T/d20240808-79687-1wowsur --template= --single-branch --depth 1 --branch CocoaPods-11.0.0

### Reproducing the issue

when I run pod install it give this error
[!] Error installing Firebase
[!] /usr/bin/git clone https://github.com/firebase/firebase-ios-sdk.git /var/folders/wt/_g4gd3cd7zg5x0p3p71ywqp00000gn/T/d20240808-79687-1wowsur --template= --single-branch --depth 1 --branch CocoaPods-11.0.0

### Firebase SDK Version

11.0.0

### Xcode Version

15.3

### Installation Method

CocoaPods

### Firebase Product(s)

Remote Config

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reporting, @zoraiz-WOL. Could you provide the complete error logs you encountered as well as the steps to reproduce the issue?
