### ISSUE TITLE
app crash at the -[GULAppDelegateSwizzler application:donor_didRegisterForRemoteNotificationsWithDeviceToken:]

### ISSUE THREAD

**Issue by ShanzhiZhuang** [firebase/firebase-ios-sdk#13465]
### Description

this is the follow-up to #1317 ,I have't figured out the crash for past one month
if following the alternative Firebase instructions for using the products without swizzling have an impact on the following [GA4] Automatically collected events
app_exception(app)
app_update(app)
error(app)
first_open(app)
first_visit(app, web)
in_app_purchase(app)
notification_dismiss(app)
notification_foreground(app)
notification_open(app)
notification_receive(app)
page_view(web)
screen_view(app)
session_start(app, web)
user_engagement(app, web)

### Firebase SDK Version

10.24.0

### Xcode Version

15.0

### Installation Method

CocoaPods

### Firebase Product(s)

Messaging

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @ShanzhiZhuang, this seems unrelated to the issue you shared. Could you provide your complete stack trace as well as the detailed steps to reproduce the issue?
