### ISSUE TITLE
in_app_purchase event is not being automatically reported

### ISSUE THREAD

**Issue by juanmasilf** [firebase/firebase-ios-sdk#13461]
### Description

I've noticed that `in_app_purchases` event stopped being auto reported by Firebase from July 18th. 

The report of events was normal until that day, after that we are only receiving in_app_purchases events from Android devices. I checked and all others automatic events are being reported properly.

I checked [this similar issue ](https://github.com/firebase/firebase-ios-sdk/issues/13392)but we are not currently using StoreKit 2 for our in-app purchases.

### Firebase SDK Version

10.0.29

### Xcode Version

15.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @juanmasilf, I understand that your `in_app_purchase` event is not being reported in the dashboard. It seems that your project needs to be checked by our Firebase support. With this, please file a ticket through our [support channel](https://firebase.google.com/support/) to investigate.
