### ISSUE TITLE
FirebaseFirestoreSwift causes RecaptchaEnterprise crash

### ISSUE THREAD

**Issue by leszko11-heetch** [firebase/firebase-ios-sdk#13471]
### Description

Hello 👋 

We recently updated Firebase to `10.29.0` and wanted to use Firestore. After the update, RecaptchaEnterprise started to crash when we call
```
try await Recaptcha.getClient(withSiteKey: "KEY_ID")
```
https://cloud.google.com/recaptcha/docs/instrument-ios-apps#integrate_app

This crash does not happen, when we downgrade Firebase below `10.17.0` where FirebaseFirestoreSwift [was moved to Firebase](https://firebase.google.com/support/release-notes/ios#10.17.0)
Adding FirebaseFirestoreSwift package is causing the crash

What's interesting, this crash exists only in builds distributed by firebase. TestFlight builds are not affected.

Is this issue connected to https://github.com/firebase/firebase-ios-sdk/pull/13254 ?

### Firebase SDK Version

10.29.0

### Xcode Version

15.4

### Installation Method

Swift Package Manager

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json
{
  "pins" : [
    {
      "identity" : "abseil-cpp-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/abseil-cpp-binary.git",
      "state" : {
        "revision" : "194a6706acbd25e4ef639bcaddea16e8758a3e27",
        "version" : "1.2024011602.0"
      }
    },
    {
      "identity" : "app-check",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/app-check.git",
      "state" : {
        "revision" : "3b62f154d00019ae29a71e9738800bb6f18b236d",
        "version" : "10.19.2"
      }
    },
    {
      "identity" : "facebook-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/facebook/facebook-ios-sdk",
      "state" : {
        "revision" : "9ed465ccd73c231144d49a9c681774577c616f34",
        "version" : "17.0.2"
      }
    },
    {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk.git",
      "state" : {
        "revision" : "eca84fd638116dd6adb633b5a3f31cc7befcbb7d",
        "version" : "10.29.0"
      }
    },
    {
      "identity" : "googleappmeasurement",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleAppMeasurement.git",
      "state" : {
        "revision" : "fe727587518729046fc1465625b9afd80b5ab361",
        "version" : "10.28.0"
      }
    },
    {
      "identity" : "googledatatransport",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleDataTransport.git",
      "state" : {
        "revision" : "a637d318ae7ae246b02d7305121275bc75ed5565",
        "version" : "9.4.0"
      }
    },
    {
      "identity" : "googleutilities",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleUtilities.git",
      "state" : {
        "revision" : "26c898aed8bed13b8a63057ee26500abbbcb8d55",
        "version" : "7.13.1"
      }
    },
    {
      "identity" : "grpc-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/grpc-binary.git",
      "state" : {
        "revision" : "e9fad491d0673bdda7063a0341fb6b47a30c5359",
        "version" : "1.62.2"
      }
    },
    {
      "identity" : "gtm-session-fetcher",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/gtm-session-fetcher.git",
      "state" : {
        "revision" : "a2ab612cb980066ee56d90d60d8462992c07f24b",
        "version" : "3.5.0"
      }
    },
    {
      "identity" : "interop-ios-for-google-sdks",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/interop-ios-for-google-sdks.git",
      "state" : {
        "revision" : "2d12673670417654f08f5f90fdd62926dc3a2648",
        "version" : "100.0.0"
      }
    },
    {
      "identity" : "ios-maps-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/googlemaps/ios-maps-sdk",
      "state" : {
        "revision" : "bd392d7d844b49ec6795871a3c25edd01ab839f2",
        "version" : "8.4.0"
      }
    },
    {
      "identity" : "ios-navigation-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/googlemaps/ios-navigation-sdk",
      "state" : {
        "revision" : "965025bf5b2a1ce5be487c26c422bd84dadeb55c",
        "version" : "5.4.0"
      }
    },
    {
      "identity" : "ios-places-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/googlemaps/ios-places-sdk",
      "state" : {
        "revision" : "2a9c7305a0e5f83b9acdccfc74eb545ffeb476c3",
        "version" : "8.5.0"
      }
    },
    {
      "identity" : "leveldb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/leveldb.git",
      "state" : {
        "revision" : "43aaef65e0c665daadf848761d560e446d350d3d",
        "version" : "1.22.4"
      }
    },
    {
      "identity" : "nanopb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/nanopb.git",
      "state" : {
        "revision" : "819d0a2173aff699fb8c364b6fb906f7cdb1a692",
        "version" : "2.30909.0"
      }
    },
    {
      "identity" : "promises",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/promises.git",
      "state" : {
        "revision" : "540318ecedd63d883069ae7f1ed811a2df00b6ac",
        "version" : "2.4.0"
      }
    },
    {
      "identity" : "swift-protobuf",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-protobuf.git",
      "state" : {
        "revision" : "9f0c76544701845ad98716f3f6a774a892152bcb",
        "version" : "1.26.0"
      }
    }
  ],
  "version" : 2
}

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
@leszko11-heetch Thanks for the report. 

I don't see recaptcha-entrerprise in the `Package.resolved`. See the instructions at https://cloud.google.com/recaptcha/docs/instrument-ios-apps#swift-package-manager.

What is the crash that you see?

#13254 is related to stabilizing 11.0.0 and should not have any impact on 10.x releases.

**Comment by leszko11-heetch** [comment]
Oh right. Initially, we added recaptcha [manually as xcframework](https://cloud.google.com/recaptcha/docs/instrument-ios-apps#direct-download). The first thing I did after we discovered the crash was updating the recaptcha and moving it to spm, but it changed nothing

The crash is `EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000380000000021`
crashlog attached
[crash_session.txt](https://github.com/user-attachments/files/16549502/crash_session.txt)

**Comment by paulb777** [comment]
That trace is showing a crash at `HeetchRecaptchaProvider.getToken() + 11`. I don't see Firebase?

**Comment by leszko11-heetch** [comment]
Yes, this is what I mentioned in the issue description. The existence of `FirebaseFirestoreSwift` in the project causes this crash

**Comment by ncooke3** [comment]
Firestore does not depend on Recaptcha so I'm unsure why `FirebaseFirestoreSwift` is seemingly causing the crash. Is the `-ObjC` flag being used as an "Other Linker Flag" for your app target?

**Comment by leszko11-heetch** [comment]
Yes, it was a bit of a surprise when we found the cause, but adding `FirebaseFirestoreSwift` caused it. 
And what is happening on our side is:
- Between versions `10.0.0` and `10.16.0` (I checked a few of them) Recaptcha does not crash, but it needs `FirebaseFirestoreSwift` to be added to project
- If I add `FirebaseFirestoreSwift` dependency and use any version below `10.17.0` app crashes
- From version `10.17.0` Recaptcha starts to crash.

We use `-ObjC` flag

**Comment by paulb777** [comment]
What iOS version are you running? And does changing it make a difference?

**Comment by leszko11-heetch** [comment]
Observed on iOS 17.5.1. I'll try to test using device with a lower version

**Comment by paulb777** [comment]
What about simulator? Or does it only occur on device?

**Comment by leszko11-heetch** [comment]
Checked on iPhone iOS 16.3.1 - also crashes.

On our end, it crashes only on builds distributed by Firebase Distribution. Testflight builds are not affected
Simulator builds, or debug builds run on device are not crashing

**Comment by paulb777** [comment]
Weird, I'm not sure what would be different between Testflight and Firebase App Distribution builds.

Does building with Firebase 11.0.0 make any difference?

**Comment by leszko11-heetch** [comment]
Build with Firebase 11.0.0 also crashes.

I can prepare demo project if that would help

**Comment by paulb777** [comment]
Yes, a project that reproduces the issue would be very helpful. Thanks!

**Comment by leszko11-heetch** [comment]
Hey guys!

I resolved the issue. Not sure what was the cause of the crash, but:
- Our previous setup was something like
App - app target importing A and B
Framework A - framework importing Firebase
Framework B - framework importing Recaptcha

With setup, Recaptcha was crashing, but when I moved Recaptcha from separate package:
App - app target importing A
Framework A - framework importing Firebase and Recaptcha
Framework B - removed

It's all good 🆗 

Thanks for your time 🙏
