### ISSUE TITLE
AuthAPNSTokenManager.getToken() fatal error unwrapping nil

### ISSUE THREAD

**Issue by snapxo** [firebase/firebase-ios-sdk#13470]
### Description

When performing `PhoneAuthProvider.provider().verifyPhoneNumber` and getting a timeout, the app crashes since `AuthAPNSTokenManager` runs into a nil unwrapping fatal error.

To my understanding, there is an issue in the commit **[auth-swift] Finish Transition to async-await for RPC calls (#11557)** from 19 Jul 2023.

Indeed the design of the callback in `getTokenInternal(callback: @escaping (AuthAPNSToken?, Error?) -> Void)` lacks consistency in my opinion.
It takes a tuple of two optional `(AuthAPNSToken?, Error?)` instead of using more appropriate structures such as `Result<AuthAPNSToken, Error>`.

It is probably envisioned by the developer that "it will never happen that both are nil at the same time", and thus we come with the implementation of `getToken() async throws AuthAPNSToken` which force unwraps `error` in the case of `token` being `nil`. See `AuthAPNSTokenManager` lines 76 to 86.

What strikes me is that in the case of a timeout, this callback (through the call of `self.callback` which gets over all the pending callbacks in the array which was set line 61) is called with `(nil, nil)` !

So it comes with not so much surprise that line 82 leads to a fatal error by force unwrapping a nil value.

<img width="1627" alt="Screenshot 2024-08-08 at 15 39 31" src="https://github.com/user-attachments/assets/172048d3-4969-4fcd-b0e7-7c256a4028bb">

### Reproducing the issue

1. configure Firebase
2. call PhoneAuthProvider.provider().verifyPhoneNumber
3. get a timeout after 5 sec
4. app crashes

### Firebase SDK Version

11.0.0

### Xcode Version

15.4

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Not applicable.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Not applicable.

```

</details>

**Comment by paulb777** [comment]
@snapxo Thanks for the report and sharing the investigation.

We'll work on a fix for the next release.

**Comment by ncooke3** [comment]
Thanks again for the report, @snapxo. A fix has been staged for next release.

**Comment by snapxo** [comment]
@ncooke3 thanks for being so quick to respond to this issue. Looks good with `Result` in #13472.
Only thing I'm wondering, is that with `AuthErrorUtils.missingAppTokenError(underlyingError: nil)` the user of the SDK has no mean to know that the request timed out, apart from implementing a timeout logic on their side, right?

Would it be a solution to add an underlying timeout Error?

But the most important is that it doesn't crash 💥, which it shouldn't 👍
