### ISSUE TITLE
Missing FirebaseFirestoreSwift Module in Latest SDK Versions

### ISSUE THREAD

**Issue by Stp155906** [firebase/firebase-ios-sdk#13478]
### Description

Hi Firebase Team,

I’ve been working on a project that relies heavily on the `FirebaseFirestoreSwift` module for integrating Firestore with Swift's `Codable` protocol. This module was available in previous versions of the Firebase iOS SDK and is still mentioned in the official Firebase documentation.

However, after updating to the latest SDK version, I noticed that `FirebaseFirestoreSwift` seems to be missing. I’ve checked the repository and searched through the documentation but couldn’t find any references indicating whether this module has been moved, renamed, or deprecated.

Could you please clarify:

1. Has the `FirebaseFirestoreSwift` module been renamed or merged into another module in the latest SDK versions?
2. If it has been deprecated or removed, what is the recommended way to handle `Codable` support for Firestore in Swift in the current SDK?
3. Are there any alternative modules or methods provided by Firebase to achieve similar functionality?

I’ve tried rolling back to an older version of the SDK, but this has caused dependency resolution issues in Xcode. I’m hoping to find a clear path forward with the latest stable SDK version.

Thank you for your assistance.

Best regards,
Shantalia

### Reproducing the issue

**Expected Behavior:**
- The `FirebaseFirestoreSwift` module should be available for import, allowing the use of Swift's `Codable` protocol with Firestore.

**Actual Behavior:**
- The `FirebaseFirestoreSwift` module is not found, resulting in a build error.
- Attempts to use older SDK versions lead to package resolution errors in Xcode.

### Firebase SDK Version

main /default version | latest

### Xcode Version

Xcode Version: 16 beta 4

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication, Firestore

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
The Firestore Swift extensions are now part of the FirebaseFirestore library. FirebaseFirestoreSwift has been discontinued.

See the [Release Notes](https://firebase.google.com/support/release-notes/ios) for more details.
