### ISSUE TITLE
Firebase Analytics iOS - integer event parameters aren't sent

### ISSUE THREAD

**Issue by volodymyr-ivanyshyn-ja** [firebase/firebase-ios-sdk#13499]
### Description

When triggering event with integer parameter this parameter is sent with null value in result. Here is sample code:

```
protocol AnalyticsParamTypeCompliant {}
extension String: AnalyticsParamTypeCompliant {}
extension Int: AnalyticsParamTypeCompliant {}
extension Double: AnalyticsParamTypeCompliant {}

var params: [String: AnalyticsParamTypeCompliant] = [:]
params += ["int_param": 1]
FirebaseAnalytics.Analytics.logEvent("my_event", parameters: params)
```

### Reproducing the issue

Use the sample code from the issue description, trigger it and check on Goggle Analytics dashboard

### Firebase SDK Version

10.23

### Xcode Version

15.4

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reporting, @volodymyr-ivanyshyn-ja. I tried reproducing the issue but I'm able to get the value of my event parameters. Could you share a sample app that reproduces the issue? Also, have you tried adding a value manually in your params and see if this will send in your Analytics dashboard?
