### ISSUE TITLE
App Check token is invalid

### ISSUE THREAD

**Issue by tomerbeil** [firebase/firebase-ios-sdk#13513]
### Description

On my iPhone, all Firebase-related requests in my app (Storage, Vertex AI, Cloud Functions) with enforced App Check are declined due to an invalid Firebase App Check token.

This issue occurs in the following scenarios:

- When the app is installed from the App Store (other users have not experienced this issue yet).
- When the app is installed from Xcode (using the AppCheckDebugProviderFactory in debug mode).

As of now, the error consistently occurs, and I can't prevent it without disabling App Check enforcement. This problem didn't exist until today.

Recently, I enabled Xcode Cloud and upgraded the Firebase SDK from version 10.29.0 to 11.0.0. However, I'm uncertain if these changes are related to the issue, as it occurs even with the published App Store build.

### Reproducing the issue

I don't know how to reproduce it because I don't know the reason why it's happening.

In App init:
```
#if DEBUG
        let providerFactory = AppCheckDebugProviderFactory()
#else
        let providerFactory = FlexiAppCheckProviderFactory()
#endif
        AppCheck.setAppCheckProviderFactory(providerFactory)
```

class FlexiAppCheckProviderFactory: NSObject, AppCheckProviderFactory {
    
    func createProvider(with app: FirebaseApp) -> AppCheckProvider? {
        return AppAttestProvider(app: app)
    }
    
}

### Firebase SDK Version

11.0

### Xcode Version

15.4

### Installation Method

Swift Package Manager

### Firebase Product(s)

App Check

### Targeted Platforms

iOS

### Relevant Log Output

```shell
[FirebaseVertexAI] Response payload: {
  "error": {
    "code": 401,
    "message": "Firebase App Check token is invalid.",
    "status": "UNAUTHENTICATED"
  }
}
```

**Comment by ncooke3** [comment]
Hi @tomerbeil, thanks for the report and apoliges for the trouble here. So just to confirm, this issue started occurring with no key changes (e.g. changed App Check integration code, updated dependencies, etc.) ?

Are you able to get a picture of whether this issue is affecting certain OS versions more than others?

**Comment by paulb777** [comment]
While it would be nice to know what was happening, we're not likely to find a solution with reproducing - so I'll close.

Thanks for letting us know and glad it's now working for you.
