### ISSUE TITLE
 crash in firebase's crashed system no report ，crash in Apple's crashed system report 

### ISSUE THREAD

**Issue by TttGggVv** [firebase/firebase-ios-sdk#13514]
### Description

I have a crash no report in firebase forever, but in apple is top1 crash 
[2024-08-14_22-56-25.2469_-0400-0d8c03c7d7dd4c160de27983b8c4b61570855167.crash.zip](https://github.com/user-attachments/files/16655415/2024-08-14_22-56-25.2469_-0400-0d8c03c7d7dd4c160de27983b8c4b61570855167.crash.zip)

### Firebase SDK Version

10.29.0

### Xcode Version

15.4

### Installation Method

CocoaPods

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment]
Hi @TttGggVv, this crash looks unrelated to Firebase. The `Termination Reason: FRONTBOARD 0xbaadca11` indicates it was done by the system. Take a look at https://developer.apple.com/documentation/xcode/sigkill:
> 0xbaadca11 (3131951633) — pronounced “bad call”
The operating system terminated the app for failing to report a [CallKit](https://developer.apple.com/documentation/CallKit) call in response to a [PushKit](https://developer.apple.com/documentation/PushKit) notification.

**Comment by TttGggVv** [comment]
If it is a system-triggered crash, might Firebase Crashlytics not be able to collect it? I want to know what kinds of crashes Firebase does not collect?

**Comment by ncooke3** [comment]
Based on the trace, it looks like the system crashed the app before Crashlytics had time to start up.
