### ISSUE TITLE
[CocoaPods-10.29.0] Undefined symbols  _APMAnalyticsConfiguration while using cocoapods

### ISSUE THREAD

**Issue by ZGilbert** [firebase/firebase-ios-sdk#13526]
### Description

platform :ios, '12.4'
  pod 'FirebaseCrashlytics'
  pod 'FirebasePerformance'
  pod 'FirebaseAnalytics'
  pod 'FirebaseDynamicLinks'
  
  
 Pod installation complete. I build the project and it report like this:
ld: Undefined symbols:
  _APMAnalyticsConfiguration, referenced from:
      +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics[10](FIRAnalytics.o)
  _APMAppMeasurementOriginFirebase, referenced from:
      +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics[10](FIRAnalytics.o)
  _APMConsentSettings3P, referenced from:
      +[FIRAnalytics setConsent:] in FirebaseAnalytics[10](FIRAnalytics.o)
  _APMFormattedEventName, referenced from:
      +[FIRAnalytics logEventWithOrigin:name:parameters:] in FirebaseAnalytics[10](FIRAnalytics.o)
  _APMFormattedUserPropertyName, referenced from:
      +[FIRAnalytics setUserPropertyString:forName:] in FirebaseAnalytics[10](FIRAnalytics.o)
  _APMIsAnalyticsCollectionDeactivated, referenced from:
      +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics[10](FIRAnalytics.o)
  _APMIsAnalyticsCollectionEnabled, referenced from:
      +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics[10](FIRAnalytics.o)
  _APMMonitorLogTagOptionKey, referenced from:
      +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics[10](FIRAnalytics.o)
  _APMUserDataFieldEmailAddress, referenced from:
      +[FIRAnalytics initiateOnDeviceConversionMeasurementWithEmailAddress:] in FirebaseAnalytics[10](FIRAnalytics.o)
  _APMUserDataFieldHashedEmailAddress, referenced from:
      +[FIRAnalytics initiateOnDeviceConversionMeasurementWithHashedEmailAddress:] in FirebaseAnalytics[10](FIRAnalytics.o)
  _APMUserDataFieldHashedPhoneNumber, referenced from:
      +[FIRAnalytics initiateOnDeviceConversionMeasurementWithHashedPhoneNumber:] in FirebaseAnalytics[10](FIRAnalytics.o)
  _APMUserDataFieldPhoneNumber, referenced from:
      +[FIRAnalytics initiateOnDeviceConversionMeasurementWithPhoneNumber:] in FirebaseAnalytics[10](FIRAnalytics.o)
  _OBJC_CLASS_$_APMAdExposureReporter, referenced from:
      _OBJC_CLASS_$_FIRAAdExposureReporter in FirebaseAnalytics[3](FIRAAdExposureReporter.o)
  _OBJC_CLASS_$_APMAnalytics, referenced from:
       in FirebaseAnalytics[10](FIRAnalytics.o)
  _OBJC_CLASS_$_APMConditionalUserProperty, referenced from:
      _OBJC_CLASS_$_FIRAConditionalUserProperty in FirebaseAnalytics[4](FIRAConditionalUserProperty.o)
  _OBJC_CLASS_$_APMConditionalUserPropertyController, referenced from:
      _OBJC_CLASS_$_FIRAConditionalUserPropertyController in FirebaseAnalytics[5](FIRAConditionalUserPropertyController.o)
  _OBJC_CLASS_$_APMEvent, referenced from:
      _OBJC_CLASS_$_FIRAEvent in FirebaseAnalytics[7](FIRAEvent.o)
  _OBJC_CLASS_$_APMIdentifiers, referenced from:
      _OBJC_CLASS_$_FIRAIdentifiers in FirebaseAnalytics[8](FIRAIdentifiers.o)
  _OBJC_CLASS_$_APMIdentity, referenced from:
       in FirebaseAnalytics[10](FIRAnalytics.o)
  _OBJC_CLASS_$_APMMeasurement, referenced from:
       in FirebaseAnalytics[9](FIRAMeasurement.o)
      _OBJC_CLASS_$_FIRAMeasurement in FirebaseAnalytics[9](FIRAMeasurement.o)
  _OBJC_CLASS_$_APMScreenViewReporter, referenced from:
       in FirebaseAnalytics[12](FIRAScreenViewReporter.o)
      _OBJC_CLASS_$_FIRAScreenViewReporter in FirebaseAnalytics[12](FIRAScreenViewReporter.o)
  _OBJC_CLASS_$_APMUserAttribute, referenced from:
      _OBJC_CLASS_$_FIRAUserAttribute in FirebaseAnalytics[13](FIRAUserAttribute.o)
  _OBJC_CLASS_$_APMValue, referenced from:
      _OBJC_CLASS_$_FIRAValue in FirebaseAnalytics[14](FIRAValue.o)
  _OBJC_METACLASS_$_APMAdExposureReporter, referenced from:
      _OBJC_METACLASS_$_FIRAAdExposureReporter in FirebaseAnalytics[3](FIRAAdExposureReporter.o)
  _OBJC_METACLASS_$_APMConditionalUserProperty, referenced from:
      _OBJC_METACLASS_$_FIRAConditionalUserProperty in FirebaseAnalytics[4](FIRAConditionalUserProperty.o)
  _OBJC_METACLASS_$_APMConditionalUserPropertyController, referenced from:
      _OBJC_METACLASS_$_FIRAConditionalUserPropertyController in FirebaseAnalytics[5](FIRAConditionalUserPropertyController.o)
  _OBJC_METACLASS_$_APMEvent, referenced from:
      _OBJC_METACLASS_$_FIRAEvent in FirebaseAnalytics[7](FIRAEvent.o)
  _OBJC_METACLASS_$_APMIdentifiers, referenced from:
      _OBJC_METACLASS_$_FIRAIdentifiers in FirebaseAnalytics[8](FIRAIdentifiers.o)
  _OBJC_METACLASS_$_APMMeasurement, referenced from:
      _OBJC_METACLASS_$_FIRAMeasurement in FirebaseAnalytics[9](FIRAMeasurement.o)
  _OBJC_METACLASS_$_APMScreenViewReporter, referenced from:
      _OBJC_METACLASS_$_FIRAScreenViewReporter in FirebaseAnalytics[12](FIRAScreenViewReporter.o)
  _OBJC_METACLASS_$_APMUserAttribute, referenced from:
      _OBJC_METACLASS_$_FIRAUserAttribute in FirebaseAnalytics[13](FIRAUserAttribute.o)
  _OBJC_METACLASS_$_APMValue, referenced from:
      _OBJC_METACLASS_$_FIRAValue in FirebaseAnalytics[14](FIRAValue.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I want to know which pod should be imported into my project to correct the error. tks.

### Firebase SDK Version

10.29.0

### Xcode Version

15.2

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, Crashlytics, DynamicLinks, Performance

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
Please complete the template with the Podfile.lock

**Comment by ZGilbert** [comment]
> Please complete the template with the Podfile.lock

Tks.I find it and now my project is running.
