### ISSUE TITLE
Undefined symbols: Linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by kalathiyanilesh1** [firebase/firebase-ios-sdk#13559]
### Description

I'm getting this error "Undefined symbols: Linker command failed with exit code 1 (use -v to see invocation)" after updating the firebase from 10.29.0 to 11.1.0

![1](https://github.com/user-attachments/assets/c0007d06-98e6-4313-9af1-10f2dca79717)

### Firebase SDK Version

11.1.0

### Xcode Version

15.0.1

### Installation Method

CocoaPods

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml
```

</details>

**Comment by paulb777** [comment]
Please show the full error message and fill out the full issue template.

**Comment by kalathiyanilesh1** [comment]
You can see this video

https://github.com/user-attachments/assets/bfeb0b6a-ec20-4091-8d93-e83c920dc0be

**Comment by ncooke3** [comment]
Select the below icon and click on the build logs for the failing build. The undefined symbols should appear when expanding the failing build command.
<img width="279" alt="Screenshot 2024-08-30 at 10 13 16 AM" src="https://github.com/user-attachments/assets/8a467ae7-a1c3-4116-9f11-e38275fb5973">

**Comment by kalathiyanilesh1** [comment]
https://github.com/user-attachments/assets/9e1e2911-aa45-4d15-97b2-dec1578c7d9c

**Comment by paulb777** [comment]
Firebase requires at least Xcode 15.2. See the [release notes](https://firebase.google.com/support/release-notes/ios).
