### ISSUE TITLE
FirebaseCrashlytics deployment target inconsistency iOS 12 or 13

### ISSUE THREAD

**Issue by Igor-Palaguta** [firebase/firebase-ios-sdk#13578]
### Description

Our iOS application has iOS 12 as minimum deployment target (platform :ios, '12.0' in Podfile).

In our Podfile we have:

`pod 'Firebase/Crashlytics', '~> 11.0'`

It fails as in Firebase.podspec Crashlytics subspec has iOS 13
```
  s.subspec 'Crashlytics' do |ss|
    ss.ios.deployment_target = '13.0'
  end
```

But if we add to Podfile
`pod 'FirebaseCrashlytics', '~> 11.0'`

It works, because in FirebaseCrashlytics.podspec iOS 12 is specified
`ios_deployment_target = '12.0'`

Probably iOS 12 can be specified in both places?

Thanks

### Firebase SDK Version

11.1

### Xcode Version

15.4

### Installation Method

CocoaPods

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
[!] CocoaPods could not find compatible versions for pod "Firebase/Crashlytics":
  In Podfile:
    Firebase/Crashlytics (~> 11.0)

Specs satisfying the `Firebase/Crashlytics (~> 11.0)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by paulb777** [comment]
@Igor-Palaguta Thanks for the report. We'll fix in 15.2 or 15.3. In the meantime, the workaround is to use the recommended `pod 'FirebaseCrashlytics', '~> 11.0'`
