### ISSUE TITLE
Logs are not displayed in firebase analytics on ios18 beta

### ISSUE THREAD

**Issue by tanukki2929** [firebase/firebase-ios-sdk#13598]
### Description

I can't see any logs in realtime analytics and debugview in firebase analytics on ios18beta.

It is displayed on versions prior to iOS 18. Also, the event log is not displayed in the xcode console on iOS 18.

Can you please tell us the cause of this problem?

### Firebase SDK Version

11.1.0

### Xcode Version

15.2

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @tanukki2929, just to confirm, may I know if you're unable to get the event logs both in the Xcode console and Analytics dashboard?

**Comment by tanukki2929** [comment]
> Hi @tanukki2929, just to confirm, may I know if you're unable to get the event logs both in the Xcode console and Analytics dashboard?

The Xcode console log was not getting the event log.
Analytics Dashboard appears to be getting it. (I am not sure if all the event logs are working, but it looks like most of them are.)
Realtime Analytics and DebugView are not logging at all.

The only thing I noticed is that on rare occasions, I would get the message “Number of real-time events is over the real-time event count daily limit. Event is no longer real-time. Event is no longer real-time. However, I did not log anything that would cause the daily limit to be exceeded, and no logs were output when I tried another day.

**Comment by ncooke3** [comment]
Hi @tanukki2929, could you please share what version of GoogleUtilities is recorded in your Podfile.lock?

**Comment by NC-KitagawaYusuke** [comment]
I mentioned that Realtime Analytics does not show it, but I tried it today and it does.
It may have just not been reflected due to timing.

Also, as for debugview, I had set it in the source code before Firebase initialization, but this method did not seem to work from IOS18.
The debugview was displayed by adding “-FIRDebugEnabled” to the Arguments during RUN.

```
    var args = ProcessInfo.processInfo.arguments
    args.append(“-FIRDebugEnabled”)
    ProcessInfo.processInfo.setValue(args, forKey: “arguments”)

FirebaseApp.configure()

```

**Comment by tanukki2929** [comment]
I mentioned that Realtime Analytics does not show it, but I tried it today and it does.
It may have just not been reflected due to timing.

Also, as for debugview, I had set it in the source code before Firebase initialization, but this method did not seem to work from IOS18.
The debugview was displayed by adding “-FIRDebugEnabled” to the Arguments during RUN.
```

    var args = ProcessInfo.processInfo.arguments
    args.append("-FIRDebugEnabled")
    ProcessInfo.processInfo.setValue(args, forKey: "arguments")

FirebaseApp.configure()
```

**Comment by ncooke3** [comment]
Hi @tanukki2929, there was a logging issue on recent versions of GoogleUtilities. Please double check that your project is using GoogleUtilities 8.0.2 or higher.

**Comment by tanukki2929** [comment]
@ncooke3 
I checked the version of GoogleUtilities, we were using 8.0.2.
When I installed FirebaseSDK11.1.0, 8.0.2 was automatically installed.

**Comment by ncooke3** [comment]
Thanks, @tanukki2929. It sounds like there could have been a timing issue with setting the env var in code. As you saw, it's better to set up in the scheme's run arguments as it will insure timing is not an issue.
