### ISSUE TITLE
[FR]: please stop firebase my jacks and Grindr accounts

### ISSUE THREAD

**Issue by Jayokqwr** [firebase/firebase-ios-sdk#13612]
### Description

Each time I do factory reset. My app interactions and people I've interacted with via text aren't able to reply via my text or web messages. I have these features. I set up a firebase account while ago. Since chrome has rolled out new features, I'm having difficulty receiving any calls text or functions in my third party apps. I want this to end. I'm no longer interested 

### API Proposal

[Process] mobi.jackd.android: 88224 kb / 201262 kb
[Service] mobi.jackd.android/com.google.firebase.sessions.SessionLifecycleService: 88224 kb / 201262 kb
![Screenshot_20240909-211429](https://github.com/user-attachments/assets/af2b1e68-cae2-4c30-8ba4-aa5fbf7f6938)
 Please allow all my messages to come directly to me. I don't want any clouds 

### Firebase Product(s)

Messaging

**Comment by rizafran** [comment]
Hi @Jayokqwr, based on your screenshot, it seems that the email came from Google Cloud Shell, which is a GCP product. As this repo handles Firebase SDK-related issues, I'd recommend reaching out to [GCP support](https://cloud.google.com/contact). If you think that this is a Firebase-related issue, you may reach out to our [Firebase support](https://firebase.google.com/support/) to check your project/account.
