### ISSUE TITLE
[FR]: Alternative of signInWithPopup and signInWithRedirect but for expo or react native. 

### ISSUE THREAD

**Issue by iawaiscode** [firebase/firebase-ios-sdk#13613]
### Description

> Browser based Outh flow implementation for expo react native firebase js sdk.

> firebase js sdk have signinwithcredentials and fot the oautg flows you need to rely on native modules and 3rd party libraries. 

> firebase should include a signInWithBrowser or something similar that will use expo browser for the oauth flow without relying on native modules on 3rd party libraries. 

### Firebase Product(s)

Authentication

**Comment by paulb777** [comment]
Please reach out to the react native or expo communities with the feature request. This repo is for Swift and Objective-C developers.
