### ISSUE TITLE
Crash report FPRNetworkTrace.m - Line 253

### ISSUE THREAD

**Issue by Odobush1** [firebase/firebase-ios-sdk#13623]
### Description

I see SIGABRT (ABORT) crash in my Crashlytics after update to v11.1.0.

`FPRNetworkTrace.m - Line 253 - [FPRNetworkTrace didCompleteRequestWithResponse:error:] + 253`

Which belong to firebase Performance SDK.

I saw that users had this crash before, but the issue was closed
https://github.com/firebase/firebase-ios-sdk/issues/10807

### Reproducing the issue

I have never received these crashes while working on project running on my device so I was not able to reproduce them but I see them in Crashlytics in firebase dashboard.

### Firebase SDK Version

11.1.0

### Xcode Version

15.4

### Installation Method

Swift Package Manager

### Firebase Product(s)

Performance

### Targeted Platforms

iOS

### Relevant Log Output

```shell
# Crashlytics - Stack trace
# Application: com.ebaykleinanzeigen.ebc
# Platform: apple
# Version: 100.19.1 (24.254.7319279)
# Issue: 41b61afa8c63168ac078827dc5574441
# Session: 9a0a46ecc49f4e59be2714cae961cddc_DNE_1_v2
# Date: Tue Sep 10 2024 20:27:35 GMT+0200 (Central European Summer Time)

com.apple.main-thread
0  Kleinanzeigen                  0x186bb84 GAD_GADMediaView_arm64_11_7_0 + 1224
1  UIKitCore                      0x3ba788 -[UIClassSwapper initWithCoder:] + 1544
2  UIFoundation                   0x13804 UINibDecoderDecodeObjectForValue + 684
3  UIFoundation                   0x1398c UINibDecoderDecodeObjectForValue + 1076
4  UIFoundation                   0x13458 -[UINibDecoder decodeObjectForKey:] + 312
5  UIKitCore                      0x3b7c7c -[UIView initWithCoder:] + 800
6  Kleinanzeigen                  0x1867928 GAD_GADNativeAdView_arm64_11_7_0 + 288
7  Kleinanzeigen                  0xd19d94 @objc AdvertisementUnifiedNativeAdView.init(coder:) + 12 (AdvertisementUnifiedNativeAdView.swift:12)
8  Kleinanzeigen                  0xd17500 @objc AdvertisementFeedCustomRendering.init(coder:) + 10 (AdvertisementFeedCustomRendering.swift:10)
9  UIKitCore                      0x3ba788 -[UIClassSwapper initWithCoder:] + 1544
10 UIFoundation                   0x13804 UINibDecoderDecodeObjectForValue + 684
11 UIFoundation                   0x13458 -[UINibDecoder decodeObjectForKey:] + 312
12 UIKitCore                      0x3b737c -[UIRuntimeConnection initWithCoder:] + 92
13 UIFoundation                   0x13804 UINibDecoderDecodeObjectForValue + 684
14 UIFoundation                   0x1398c UINibDecoderDecodeObjectForValue + 1076
15 UIFoundation                   0x13458 -[UINibDecoder decodeObjectForKey:] + 312
16 UIKitCore                      0x3ba934 -[NSCoder(UIIBDependencyInjectionInternal) _decodeObjectsWithSourceSegueTemplate:creator:sender:forKey:] + 292
17 UIKitCore                      0x4a1f04 -[UINib instantiateWithOwner:options:] + 768
18 UIKitCore                      0x4c1134 -[NSBundle(UINSBundleAdditions) loadNibNamed:owner:options:] + 116
19 Kleinanzeigen                  0xcf6838 closure #6 in LibertyBootstrap.buildCustomRenderingNetwork() + 145 (LibertyBootstrap+CustomRendering.swift:145)
20 Kleinanzeigen                  0xd5a988 CustomRenderingConfiguration.prepare<A>(with:attributionCode:trackInfo:context:) + 141 (CustomRenderingConfiguration.swift:141)
21 Kleinanzeigen                  0xd5c9ac specialized CustomRenderingNetwork.createView(from:attributionCode:trackInfo:context:page:market:isBackfill:) + 28 (CustomRenderingNetwork.swift:28)
22 Kleinanzeigen                  0xd5c798 protocol witness for LibertyNetwork.createView(from:attributionCode:trackInfo:context:page:market:isBackfill:) in conformance CustomRenderingNetwork<A> + 24 (<compiler-generated>:24)
23 Kleinanzeigen                  0xdc9884 partial apply for implicit closure #2 in implicit closure #1 in AnyNetwork.init<A>(_:) + 60 (LibertyNetwork.swift:60)
24 Kleinanzeigen                  0xdc9440 AnyNetwork.createView(from:attributionCode:trackInfo:context:page:market:isBackfill:) + 46 (LibertyNetwork.swift:46)
25 Kleinanzeigen                  0xdc2b28 LibertyController.createAdvertisementView(for:backFillConfiguration:attributionCode:trackInfo:incrementGroup:context:page:appVersion:hidePlaceholder:) + 208 (LibertyController.swift:208)
26 Kleinanzeigen                  0xdc1dd0 LibertyController.advertisementView(page:category:position:incrementGroup:context:hidePlaceholder:) + 123 (LibertyController.swift:123)
27 Kleinanzeigen                  0xd032c4 protocol witness for LibertyProtocol.advertisementView(page:category:position:incrementGroup:context:hidePlaceholder:) in conformance <A> LibertyController<A> + 56 (<compiler-generated>:56)
28 Kleinanzeigen                  0x455f78 EBKActivityFeedModel.createSponsoredAdviewForSlot(_:) + 166 (EBKActivityFeedModel.swift:166)
29 Kleinanzeigen                  0x4555f4 EBKActivityFeedModel.sponsoredAdView(at:complete:) + 129 (EBKActivityFeedModel.swift:129)
30 Kleinanzeigen                  0x44546c EBKActivityFeedDataSource.collectionView(_:cellForItemAt:) + 237 (EBKActivityFeedDataSource.swift:237)
31 Kleinanzeigen                  0x446a5c @objc EBKActivityFeedDataSource.collectionView(_:cellForItemAt:) + 136 (<compiler-generated>:136)
32 UIKitCore                      0x2a1ce8 -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:notify:] + 1000
33 UIKitCore                      0x2a1714 -[UICollectionView _createVisibleViewsForSingleCategoryAttributes:limitCreation:fadeForBoundsChange:] + 1116
34 UIKitCore                      0x3d950c -[UICollectionView _createVisibleViewsForAttributes:fadeForBoundsChange:notifyLayoutForVisibleCellsPass:] + 300
35 UIKitCore                      0x1ca064 -[UICollectionView _updateVisibleCellsNow:] + 3060
36 UIKitCore                      0x335af8 -[UICollectionView layoutSubviews] + 304
37 UIKitCore                      0x10918 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1528
38 QuartzCore                     0x7f26c CA::Layer::layout_if_needed(CA::Transaction*) + 504
39 QuartzCore                     0x7edf0 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 148
40 QuartzCore                     0xd9fd8 CA::Context::commit_transaction(CA::Transaction*, double, double*) + 464
41 QuartzCore                     0x4eee0 CA::Transaction::commit() + 648
42 QuartzCore                     0x98c34 CA::Transaction::flush_as_runloop_observer(bool) + 88
43 UIKitCore                      0xb9ee8 _UIApplicationFlushCATransaction + 52
44 UIKitCore                      0xb7660 _UIUpdateSequenceRun + 84
45 UIKitCore                      0xb72a4 schedulerStepScheduledMainSection + 172
46 UIKitCore                      0xb8148 runloopSourceCallback + 92
47 CoreFoundation                 0x56834 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
48 CoreFoundation                 0x567c8 __CFRunLoopDoSource0 + 176
49 CoreFoundation                 0x54298 __CFRunLoopDoSources0 + 244
50 CoreFoundation                 0x53484 __CFRunLoopRun + 828
51 CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
52 GraphicsServices               0x11a8 GSEventRunModal + 164
53 UIKitCore                      0x40aae8 -[UIApplication _run] + 888
54 UIKitCore                      0x4bed98 UIApplicationMain + 340
55 Kleinanzeigen                  0x87dc main + 10 (KAAppDelegate.swift:10)
56 ???                            0x1c901f154 (Missing)

com.apple.CoreMotion.MotionThread
0  libsystem_kernel.dylib         0x16c8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x4ec8 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4de0 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4c20 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  CoreFoundation                 0xc0f04 CFRunLoopRun + 64
8  CoreMotion                     0xfe3c (Missing UUID 5d6e7429116638b3807bdfad246f9132)
9  libsystem_pthread.dylib        0x606c _pthread_start + 136
10 libsystem_pthread.dylib        0x10d8 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x1450 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x4980 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x10cc start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1450 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x4980 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x10cc start_wqthread + 8

Thread
0  libsystem_pthread.dylib        0x10c4 start_wqthread + 8625889474

com.apple.NSURLSession-delegate
0  libsystem_malloc.dylib         0xa0c8 nanov2_calloc + 12
1  CoreFoundation                 0x1515c __CFAllocateObject + 20
2  CoreFoundation                 0x143dc __NSArrayI_new + 92
3  Foundation                     0x4973c newJSONValue + 1328
4  Foundation                     0x475b0 newJSONObject + 572
5  Foundation                     0x493fc newJSONValue + 496
6  Foundation                     0x49620 newJSONValue + 1044
7  Foundation                     0x475b0 newJSONObject + 572
8  Foundation                     0x493fc newJSONValue + 496
9  Foundation                     0x471ec -[_NSJSONReader parseData:options:error:] + 1256
10 Kleinanzeigen                  0xdab038 LibertyConfigurationService.loadConfiguration(with:withNetworks:) + 100 (LibertyConfigurationService.swift:100)
11 Kleinanzeigen                  0xdaae30 LibertyConfigurationService.fallbackConfiguration.getter + 90 (LibertyConfigurationService.swift:90)
12 Kleinanzeigen                  0xdab568 LibertyConfigurationService.unFlagFallbackConfiguration() + 123 (LibertyConfigurationService.swift:123)
13 Kleinanzeigen                  0xdab82c closure #1 in LibertyConfigurationService.loadConfigurationFromProvider() + 161 (LibertyConfigurationService.swift:161)
14 Kleinanzeigen                  0xda9e2c closure #1 in HTTPLibertyConfigurationProvider.retrieveConfiguration(completionHandler:) + 61 (LibertyConfigurationProvider.swift:61)
15 Kleinanzeigen                  0xd41874 thunk for @escaping @callee_guaranteed @Sendable (@guaranteed Data?, @guaranteed NSURLResponse?, @guaranteed Error?) -> () + 144 (<compiler-generated>:144)
16 Kleinanzeigen                  0x592a18 __InstrumentDataTaskWithRequestCompletionHandler_block_invoke_2 + 307 (FPRNSURLSessionInstrument.m:307)
17 Kleinanzeigen                  0x592a18 __InstrumentDataTaskWithRequestCompletionHandler_block_invoke_2 + 307 (FPRNSURLSessionInstrument.m:307)
18 CFNetwork                      0x6ac70 CFHTTPCookieCreateWithResponseHeaderFields + 62444
19 CFNetwork                      0x6aa44 CFHTTPCookieCreateWithResponseHeaderFields + 61888
20 libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
21 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
22 libdispatch.dylib              0xb400 _dispatch_lane_serial_drain + 748
23 libdispatch.dylib              0xbf64 _dispatch_lane_invoke + 432
24 libdispatch.dylib              0x16cb4 _dispatch_root_queue_drain_deferred_wlh + 288
25 libdispatch.dylib              0x16528 _dispatch_workloop_worker_thread + 404
26 libsystem_pthread.dylib        0x4934 _pthread_wqthread + 288
27 libsystem_pthread.dylib        0x10cc start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1450 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x4980 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x10cc start_wqthread + 8

com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x16c8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x4ec8 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4de0 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4c20 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  Foundation                     0xc7b5c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0xc79ac -[NSRunLoop(NSRunLoop) runUntilDate:] + 64
9  UIKitCore                      0x41e81c -[UIEventFetcher threadMain] + 420
10 Foundation                     0xde428 __NSThread__start__ + 732
11 libsystem_pthread.dylib        0x606c _pthread_start + 136
12 libsystem_pthread.dylib        0x10d8 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x1450 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x4980 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x10cc start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1450 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x4980 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x10cc start_wqthread + 8

Crashed: com.apple.NSURLSession-delegate
0  libsystem_kernel.dylib         0xc2ec __pthread_kill + 8
1  libsystem_pthread.dylib        0x7c0c pthread_kill + 268
2  libsystem_c.dylib              0x75ba0 abort + 180
3  libsystem_malloc.dylib         0x9588 malloc_vreport + 896
4  libsystem_malloc.dylib         0x6430 malloc_zone_error + 104
5  libsystem_malloc.dylib         0x1fd4 _szone_free + 480
6  CoreFoundation                 0x84ec __CFStringDeallocate + 196
7  CoreFoundation                 0x7888 _CFRelease + 292
8  CFNetwork                      0xcaa94 CFHostCreateWithName + 117928
9  Kleinanzeigen                  0x58c2f4 -[FPRNetworkTrace didCompleteRequestWithResponse:error:] + 253 (FPRNetworkTrace.m:253)
10 Kleinanzeigen                  0x5929ec __InstrumentDataTaskWithRequestCompletionHandler_block_invoke_2 + 306 (FPRNSURLSessionInstrument.m:306)
11 CFNetwork                      0x6ac70 CFHTTPCookieCreateWithResponseHeaderFields + 62444
12 CFNetwork                      0x6aa44 CFHTTPCookieCreateWithResponseHeaderFields + 61888
13 libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
14 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
15 libdispatch.dylib              0xb400 _dispatch_lane_serial_drain + 748
16 libdispatch.dylib              0xbf64 _dispatch_lane_invoke + 432
17 libdispatch.dylib              0x16cb4 _dispatch_root_queue_drain_deferred_wlh + 288
18 libdispatch.dylib              0x16528 _dispatch_workloop_worker_thread + 404
19 libsystem_pthread.dylib        0x4934 _pthread_wqthread + 288
20 libsystem_pthread.dylib        0x10cc start_wqthread + 8

Thread
0  libsystem_pthread.dylib        0x10c4 start_wqthread + 8625889474

Thread
0  libsystem_pthread.dylib        0x10c4 start_wqthread + 8625889474

Thread
0  libsystem_pthread.dylib        0x10c4 start_wqthread + 8625889474

com.google.firebase.crashlytics.MachExceptionServer
0  libsystem_kernel.dylib         0x16c8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x4ec8 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4de0 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4c20 mach_msg + 24
4  Kleinanzeigen                  0x51c1c0 FIRCLSMachExceptionServer + 192 (FIRCLSMachException.c:192)
5  libsystem_pthread.dylib        0x606c _pthread_start + 136
6  libsystem_pthread.dylib        0x10d8 thread_start + 8

com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x16c8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x4ec8 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4de0 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4c20 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  CFNetwork                      0xfdc7c _CFHostIsDomainTopLevel + 108176
8  Foundation                     0xde428 __NSThread__start__ + 732
9  libsystem_pthread.dylib        0x606c _pthread_start + 136
10 libsystem_pthread.dylib        0x10d8 thread_start + 8

JavaScriptCore libpas scavenger
0  libsystem_kernel.dylib         0x708c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x36e4 _pthread_cond_wait + 1228
2  JavaScriptCore                 0x15672a4 scavenger_thread_main + 1512
3  libsystem_pthread.dylib        0x606c _pthread_start + 136
4  libsystem_pthread.dylib        0x10d8 thread_start + 8
```

### If using Swift Package Manager, the project's Package.resolved

{
        "package": "Firebase",
        "repositoryURL": "https://github.com/firebase/firebase-ios-sdk.git",
        "state": {
          "branch": null,
          "revision": "9118aca998dbe2ceac45d64b21a91c6376928df7",
          "version": "11.1.0"
        }
},

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reporting, @Odobush1. Could you provide the full stack trace of your issue to see what's causing it?

**Comment by Odobush1** [comment]
> Thanks for reporting, @Odobush1. Could you provide the full stack trace of your issue to see what's causing it?

Done.

**Comment by sc0rch** [comment]
Same crash, reverting my app to 11.0.0 for now:

#0	0x000000020df3f4e4 in _platform_strstr ()
#1	0x0000000104f41e90 in ___lldb_unnamed_symbol96 ()
#2	0x0000000104f2f8d8 in ___lldb_unnamed_symbol54 ()
#3	0x0000000186c3e0f4 in __invoking___ ()
#4	0x0000000186c3d144 in -[NSInvocation invoke] ()
#5	0x000000011535f25c in -[ADJRequestHandler signWithSigV2PluginWithParams:activityKind:clientSdk:] at /Users/sc0rch/Documents/Develop/EWA/EWA-ios/Pods/Adjust/Adjust/ADJRequestHandler.m:744
#6	0x000000011535aec4 in -[ADJRequestHandler sendPackageByPOST:sendingParameters:] at /Users/sc0rch/Documents/Develop/EWA/EWA-ios/Pods/Adjust/Adjust/ADJRequestHandler.m:94
#7	0x0000000115356924 in -[ADJPackageHandler sendFirstI:] at /Users/sc0rch/Documents/Develop/EWA/EWA-ios/Pods/Adjust/Adjust/ADJPackageHandler.m:293
#8	0x0000000115356a9c in -[ADJPackageHandler sendNextI:] at /Users/sc0rch/Documents/Develop/EWA/EWA-ios/Pods/Adjust/Adjust/ADJPackageHandler.m:308
#9	0x000000011535544c in __37-[ADJPackageHandler sendNextPackage:]_block_invoke at /Users/sc0rch/Documents/Develop/EWA/EWA-ios/Pods/Adjust/Adjust/ADJPackageHandler.m:115
#10	0x00000001153782d4 in __42+[ADJUtil launchInQueue:selfInject:block:]_block_invoke at /Users/sc0rch/Documents/Develop/EWA/EWA-ios/Pods/Adjust/Adjust/ADJUtil.m:803
#11	0x0000000105bd4a30 in _dispatch_call_block_and_release ()
#12	0x0000000105bd671c in _dispatch_client_callout ()
#13	0x0000000105bde5e8 in _dispatch_lane_serial_drain ()
#14	0x0000000105bdf360 in _dispatch_lane_invoke ()
#15	0x0000000105bec5f0 in _dispatch_root_queue_drain_deferred_wlh ()
#16	0x0000000105bebc00 in _dispatch_workloop_worker_thread ()
#17	0x000000020dfefc7c in _pthread_wqthread ()
Enqueued from com.apple.NSURLSession-delegate (Thread 22) Queue : com.apple.NSURLSession-delegate (serial)
#0	0x0000000105bdb390 in dispatch_async ()
#1	0x00000001153781f8 in +[ADJUtil launchInQueue:selfInject:block:] at /Users/sc0rch/Documents/Develop/EWA/EWA-ios/Pods/Adjust/Adjust/ADJUtil.m:798
#2	0x00000001153553ac in -[ADJPackageHandler sendNextPackage:] at /Users/sc0rch/Documents/Develop/EWA/EWA-ios/Pods/Adjust/Adjust/ADJPackageHandler.m:112
#3	0x00000001153552d0 in -[ADJPackageHandler responseCallback:] at /Users/sc0rch/Documents/Develop/EWA/EWA-ios/Pods/Adjust/Adjust/ADJPackageHandler.m:103
#4	0x000000011535bcc4 in __73-[ADJRequestHandler sendNSURLSessionRequest:responseData:methodTypeInfo:]_block_invoke at /Users/sc0rch/Documents/Develop/EWA/EWA-ios/Pods/Adjust/Adjust/ADJRequestHandler.m:233
#5	0x0000000115febca8 in __InstrumentDataTaskWithRequestCompletionHandler_block_invoke_2 at /Users/sc0rch/Documents/Develop/EWA/EWA-ios/Pods/FirebasePerformance/FirebasePerformance/Sources/Instrumentation/Network/FPRNSURLSessionInstrument.m:306
#6	0x0000000115febca8 in __InstrumentDataTaskWithRequestCompletionHandler_block_invoke_2 at /Users/sc0rch/Documents/Develop/EWA/EWA-ios/Pods/FirebasePerformance/FirebasePerformance/Sources/Instrumentation/Network/FPRNSURLSessionInstrument.m:306
#7	0x0000000188156a18 in __40-[__NSURLSessionLocal taskForClassInfo:]_block_invoke ()
#8	0x00000001881567d4 in __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke_2 ()
#9	0x0000000105bd4a30 in _dispatch_call_block_and_release ()
#10	0x0000000105bd671c in _dispatch_client_callout ()
#11	0x0000000105bde5e8 in _dispatch_lane_serial_drain ()
#12	0x0000000105bdf394 in _dispatch_lane_invoke ()
#13	0x0000000105bec5f0 in _dispatch_root_queue_drain_deferred_wlh ()
#14	0x0000000105bebc00 in _dispatch_workloop_worker_thread ()
#15	0x000000020dfefc7c in _pthread_wqthread ()
#16	0x000000020dfec488 in start_wqthread ()
Enqueued from com.apple.NSURLSession-work (Thread 2) Queue : com.apple.NSURLSession-work (serial)
#0	0x0000000105bdb390 in dispatch_async ()
#1	0x0000000188132d04 in __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke ()
#2	0x0000000188132194 in -[__NSCFURLSessionDelegateWrapper task:didFinishCollectingMetrics:completionHandler:] ()
#3	0x0000000188132180 in -[__NSCFURLSessionDelegateWrapper task:didFinishCollectingMetrics:completionHandler:] ()
#4	0x0000000188131f90 in -[NSURLSessionTaskMetrics collectWithCompletionHandler:queue:] ()
#5	0x000000018813199c in -[__NSCFLocalSessionTask _task_onqueue_didFinish] ()
#6	0x00000001881b472c in -[__NSCFLocalSessionTask connection:didFinishLoadingWithError:] ()
#7	0x00000001881b4638 in __51-[__NSCFURLLocalSessionConnection _task_sendFinish]_block_invoke ()
#8	0x00000001881b395c in -[__NSCFURLLocalSessionConnection withDelegateAndPendingCompletion:] ()
#9	0x00000001881b38b8 in -[__NSCFURLLocalSessionConnection _tick] ()
#10	0x0000000105be7844 in _dispatch_block_async_invoke2 ()
#11	0x0000000105bd671c in _dispatch_client_callout ()
#12	0x0000000105bde5e8 in _dispatch_lane_serial_drain ()
#13	0x0000000105bdf394 in _dispatch_lane_invoke ()
#14	0x0000000105bec5f0 in _dispatch_root_queue_drain_deferred_wlh ()
#15	0x0000000105bebc00 in _dispatch_workloop_worker_thread ()
#16	0x000000020dfefc7c in _pthread_wqthread ()
#17	0x000000020dfec488 in start_wqthread ()
Enqueued from com.apple.NSURLSession-work (Thread 2) Queue : com.apple.NSURLSession-work (serial)
#0	0x0000000105bdb390 in dispatch_async ()
#1	0x00000001881bd454 in -[__NSCFURLSessionConnection withWorkQueueAsync:] ()
#2	0x00000001881bd280 in -[__NSCFURLLocalSessionConnection afterDelegateWithTick:] ()
#3	0x00000001881b6108 in __50-[__NSCFURLLocalSessionConnection _tick_finishing]_block_invoke_2 ()
#4	0x00000001881b5b4c in -[__NSCFLocalSessionTask connection:willCacheResponse:responseCallback:] ()
#5	0x00000001881b5a7c in __50-[__NSCFURLLocalSessionConnection _tick_finishing]_block_invoke ()
#6	0x00000001881b395c in -[__NSCFURLLocalSessionConnection withDelegateAndPendingCompletion:] ()
#7	0x00000001881b38b8 in -[__NSCFURLLocalSessionConnection _tick] ()
#8	0x00000001881b37c4 in -[__NSCFURLLocalSessionConnection _tick] ()
#9	0x00000001881b395c in -[__NSCFURLLocalSessionConnection withDelegateAndPendingCompletion:] ()
#10	0x00000001881b48e4 in -[__NSCFURLLocalSessionConnection _didFinishWithError:] ()
#11	0x00000001881b320c in invocation function for block in SessionConnectionLoadable::withLoaderClientAsync(void (LoaderClientInterface*) block_pointer) ()
#12	0x0000000105be7844 in _dispatch_block_async_invoke2 ()
#13	0x0000000105bd671c in _dispatch_client_callout ()
#14	0x0000000105bde5e8 in _dispatch_lane_serial_drain ()
#15	0x0000000105bdf394 in _dispatch_lane_invoke ()
#16	0x0000000105bec5f0 in _dispatch_root_queue_drain_deferred_wlh ()
#17	0x0000000105bebc00 in _dispatch_workloop_worker_thread ()
#18	0x000000020dfefc7c in _pthread_wqthread ()
#19	0x000000020dfec488 in start_wqthread ()
Enqueued from com.apple.NSURLSession-work (Thread 2) Queue : com.apple.NSURLSession-work (serial)
#0	0x0000000105bdb390 in dispatch_async ()
#1	0x00000001881bd454 in -[__NSCFURLSessionConnection withWorkQueueAsync:] ()
#2	0x00000001881bd3d4 in SessionConnectionLoadable::withLoaderClientAsync ()
#3	0x00000001881bdcf4 in URLConnectionLoader::protocolDidFinishLoading ()
#4	0x00000001881ba950 in invocation function for block in URLConnectionInstanceData::withWorkQueueAsync(void () block_pointer) const ()
#5	0x0000000105bd4a30 in _dispatch_call_block_and_release ()
#6	0x0000000105bd671c in _dispatch_client_callout ()
#7	0x0000000105bde5e8 in _dispatch_lane_serial_drain ()
#8	0x0000000105bdf394 in _dispatch_lane_invoke ()
#9	0x0000000105bec5f0 in _dispatch_root_queue_drain_deferred_wlh ()
#10	0x0000000105bebc00 in _dispatch_workloop_worker_thread ()
#11	0x000000020dfefc7c in _pthread_wqthread ()
#12	0x000000020dfec488 in start_wqthread ()
Enqueued from com.apple.CFNetwork.Connection (Thread 5) Queue : com.apple.CFNetwork.Connection (serial)
#0	0x0000000105bdb390 in dispatch_async ()
#1	0x00000001881bd578 in URLConnectionInstanceData::withWorkQueueAsync ()
#2	0x0000000188135f50 in non-virtual thunk to URLConnectionLoader_Classic::protocolDidFinishLoading() ()
#3	0x0000000188135d44 in URLProtocol::sendDidFinishLoading ()
#4	0x00000001881054fc in HTTPProtocol::handleStreamEvent ()
#5	0x0000000188105180 in HTTPTransaction::_onqueue_invokeHandler ()
#6	0x0000000188104d94 in HTTPConnection::_onqueue_responseDataArrived ()
#7	0x0000000188144320 in HTTPEngine::_readBodyFinish ()
#8	0x0000000188102ff8 in HTTPEngine::_deliverBodyBytes ()
#9	0x0000000188106f70 in HTTPEngine::_getBodyIntelligently ()
#10	0x0000000188106c94 in HTTPEngine::_readBodyStartNextRead ()
#11	0x0000000188102ec4 in invocation function for block in HTTPEngine::_getBodyIntelligently(void (NSObject<OS_dispatch_data>*, CFStreamError, bool) block_pointer) ()
#12	0x0000000105bd4a30 in _dispatch_call_block_and_release ()
#13	0x0000000105bd671c in _dispatch_client_callout ()
#14	0x0000000105bde5e8 in _dispatch_lane_serial_drain ()
#15	0x0000000105bdf394 in _dispatch_lane_invoke ()
#16	0x0000000105be0b20 in _dispatch_workloop_invoke ()
#17	0x0000000105bec5f0 in _dispatch_root_queue_drain_deferred_wlh ()
#18	0x0000000105bebc00 in _dispatch_workloop_worker_thread ()
#19	0x000000020dfefc7c in _pthread_wqthread ()
#20	0x000000020dfec488 in start_wqthread ()

**Comment by MichaelVerdon** [comment]
Hi there, are you still experiencing this issue on the latest SDK version?
