### ISSUE TITLE
None of my third party apps are running. Only play services and Google sponsored apps help

### ISSUE THREAD

**Issue by Jayokqwr** [firebase/firebase-ios-sdk#13637]
### Description

Ice asked you guys to please stop restricting and disabling my device interactions. Why can't I receive web text via my Google voice like normal. Seems each day I can't text with certain individuals. Urls are associated with individuals phone numbers. Please stop this. How can I restore to default and leave the god awful firebase hosting. I promise there is litigations being filled for this negligence. I can care less about security or privacy. In addition, I paid months fee of service, which I can not use because you guys have my device configured and secured to space. This is ridiculous 
[bugreport-T434D-UP1A.231005.007-2024-09-13-14-41-02-dumpstate_log-12762.txt](https://github.com/user-attachments/files/16998512/bugreport-T434D-UP1A.231005.007-2024-09-13-14-41-02-dumpstate_log-12762.txt)
[dumpstate-stats.txt](https://github.com/user-attachments/files/16998513/dumpstate-stats.txt)
![screenshot-2024-09-13-14-41-02-default](https://github.com/user-attachments/assets/8d66b5cb-efa7-49fb-9c4b-2efc3be2c709)
[bugreport-T434D-UP1A.231005.007-2024-09-13-14-41-02.zip](https://github.com/user-attachments/files/16998514/bugreport-T434D-UP1A.231005.007-2024-09-13-14-41-02.zip)
![Screenshot_20240913-150909](https://github.com/user-attachments/assets/42315f3c-3a6a-4845-8a56-ccf036c2cc85)

### Reproducing the issue

![Screenshot_20240913-150105](https://github.com/user-attachments/assets/cd800a83-e276-41d7-9a1c-7dc9cbc19faf)
![Screenshot_20240913-150932](https://github.com/user-attachments/assets/75238feb-61c6-4468-8391-a4d7d6dde640)
Pl
![Screenshot_20240913-150938](https://github.com/user-attachments/assets/08de0191-8a7a-4367-b280-87e041c9bab1)
![Screenshot_20240913-150922](https://github.com/user-attachments/assets/146e1e14-540b-48cb-9404-e13e160812f3)

### Firebase SDK Version

Not sure

### Xcode Version

Not sure

### Installation Method

Swift Package Manager

### Firebase Product(s)

App Distribution, Authentication, Database

### Targeted Platforms

All, N/A

### Relevant Log Output

```shell
Why aren't I receiving and able to send web messages from various individuals I've texted with prior days ago. It something you guys are doing that's changing the strip strings or whatever else it could be. I have no idea. All I know is I want basic dns enable with capabilities to receive all calls text and notifications to my phone. I do not appreciate these changes taking place. Why aren't I able t have consistent dialogue via text. Only Google sponsored apps are running.why aren't my background apps running constantly freely
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>
Help

**Comment by paulb777** [comment]
See https://github.com/firebase/firebase-ios-sdk/issues/13612#issuecomment-2340280929
