### ISSUE TITLE
[FR]: I do not own or operate apple phone 

### ISSUE THREAD

**Issue by Jayokqwr** [firebase/firebase-ios-sdk#13641]
### Description

Please delete and remove codes associated. I already having issues receiving messages and apps aren't running in my background. Is this affecting me

### API Proposal

Pass individuals I've web text with aren't responding. Is the string, JavaScript, misconfigured 

### Firebase Product(s)

In-App Messaging, Performance

**Comment by paulb777** [comment]
Closing after discussion in https://github.com/firebase/firebase-ios-sdk/issues/13612
