### ISSUE TITLE
Error showing @_implementationOnly import GoogleUtilities in HeartbeatsPayload

### ISSUE THREAD

**Issue by SriAgrawal** [firebase/firebase-ios-sdk#13655]
### Description

When try to run the application with updated version of firebase 11.2.0.
Application showing error on one of the class of firebase package.
<img width="1396" alt="Screenshot 2024-09-17 at 3 30 30 PM" src="https://github.com/user-attachments/assets/36898a30-bff4-48fc-8842-c57ee963a06f">

### Reproducing the issue

Try to run the application with firebase version 11.2.0 in XCODE - 15.3.
Event will occurred.

### Firebase SDK Version

11.2.0

### Xcode Version

15.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

All

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment]
Hi @SriAgrawal, this is unexpected since Xcode should be setting SWIFT_PACKAGE when building SPM libraries. Have you tried deleting derived data, the package cache, resolving package versions to ensure it's not some transient Xcode behavior?

**Comment by SriAgrawal** [comment]
Hi @ncooke3 As you suggested i tried to cleaned all the things like derived data, the package cache but still issue exists.
I also observed one more thing that when i tried to installed pod, after installation i observed two instance of firebase and googleutilities pod is installing.
Please find in the attached screenshot of pod file installation of terminal.
I like to inform you, just i moved into new mac system which M3, previously in M1 it's working fine.
<img width="362" alt="Screenshot 2024-09-18 at 11 08 51 AM" src="https://github.com/user-attachments/assets/5c81cfb3-ddec-4c7c-8f0b-749d38e7254e">

**Comment by paulb777** [comment]
@SriAgrawal The two versions is definitely a problem. The Podfile.lock file should provide details about why the old versions are being installed and point to a resolution in the Podfile.

**Comment by SriAgrawal** [comment]
Hi Team,
After analysis and clear all the thing i found some details in it.
This issue happening when we trying to install pod "FirebaseMessaging".
I am attaching three screen shots in which you will see difference when we trying to installing "FirebaseMessaging".
We are getting two instance of GoogleUtilities and Firebase old version
1- When we install single "firebase" 
-> No issue found please find screenshot 
<img width="1228" alt="Firebase-Single-FilePod" src="https://github.com/user-attachments/assets/bb2ca3c2-303f-49b5-ae07-22dae08672ea">
 2 - When we install with "Firebase" & "FirebaseCrashlytics"
 -> No issue found please find screenshot 
<img width="1228" alt="Firebase-FirebaseCrashlytics-Pod_File" src="https://github.com/user-attachments/assets/7da81c17-cf64-4b61-b939-7dd1d52eec5d">
3 - **Now When we install with "Firebase"  "FirebaseCrashlytics" & 'FirebaseMessaging'
- Issue occurred two GoogleUtilities and Firebase old version please find screenshot**
<img width="1228" alt="Firebase-FirebaseCrashlytics-FirebaseMessaging-PodFile" src="https://github.com/user-attachments/assets/811e4af3-f873-484f-af0f-8b6cbb21b848">
As requested i am also attaching the Pod.Lock file, please check and let us know.
[Podfile.lock.zip](https://github.com/user-attachments/files/17163790/Podfile.lock.zip)
Thanks

**Comment by SriAgrawal** [comment]
Hi,
When i trying as per your suggestion, i am getting error while installing the pod file.
It was happening only when i am trying to install FirebaseMessaging.
And when i removed this pod name from pod file then pod installing properly.
So, I said previously that this FirebaseMessaging creating issue.
Kindly please refer the screenshot for the same.
<img width="568" alt="Screenshot 2024-09-30 at 5 08 49 PM" src="https://github.com/user-attachments/assets/f3a0447d-3a8d-47df-8964-298f07fe73fd">

**Comment by paulb777** [comment]
That explains the issue. Firebase 11 requires at least iOS 13, with the exception of Analytics and Crashlytics.

Update the iOS version from 12 to 13 in the Podfile.

**Comment by SriAgrawal** [comment]
Hi [paulb777](https://github.com/paulb777)
As per your suggestion and we understood that firebase version 11 support iOS platform 13 and It's working fine now.
Thanks for support, now i am closing this tickets.
Gracias
Buen día
