### ISSUE TITLE
Firestore will not compile on Xcode 9.2 or earlier

### ISSUE THREAD

**Issue by wilhuff** [firebase/firebase-ios-sdk#1366]
Xcode 9.2 sees ambiguities in our `FormatArg` in `util/string_format.h` because `std::is_base_of<NSObject, T>{}` does not enable overloads that handle Objective-C types.

Xcode 8.3.3 sees static assertion failures in our specializations of `RankedInvokeHash` in `util/hashing.h` because `std::hash<T>` is defined for all `T`--it's just that it's an error to use the generic specialization of std::hash for anything that's not an enumeration type.

**Comment by paulb777** [comment]
FYI, there's a good chance we'll drop Xcode 8 support in the next few months since [Apple will require all apps include iOS 11 support](https://developer.apple.com/news/?id=05072018a)

**Comment by wilhuff** [comment]
I figured as much, but we haven’t dropped support yet :-).

Also this fix is likely the right thing to do anyway since depending on the standard library to behave in some specific way in cases that are undefined by the standard is unlikely to be portable.
