### ISSUE TITLE
`upload-symbols` gatekeeper issue on macOS 15

### ISSUE THREAD

**Issue by TheNightmanCodeth** [firebase/firebase-ios-sdk#13665]
### Description

upload-symbols runs are failing with `Illegal instruction: 4` on Xcode cloud builds. Confirmed the binary cannot be executed locally on latest macOS version due to gatekeeper: `Apple could not verify "upload-symbols" is free of malware that may harm your Mac or compromise your privacy`. 

![Screenshot 2024-09-18 at 4 36 36 PM](https://github.com/user-attachments/assets/c7c88b80-abdd-4721-9258-bba3e75b09ba)

### Reproducing the issue

Download `upload-symbols` directly from main branch, `chmod +x` it and execute on latest macOS (15)

### Firebase SDK Version

latest

### Xcode Version

latest

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by themiswang** [comment]
Hey @TheNightmanCodeth,

`upload-symbols` should be correctly notarized and you can check by doing `spctl -a -vvv -t install <Path>`. Wonder have you followed instruction in [Apple documentation](https://support.apple.com/en-ca/102445) to enabled it from `Privacy & Security` section in System Settings?
