### ISSUE TITLE
Unable to Connect to Firestore on iOS 18 devices.

### ISSUE THREAD

**Issue by MagicFlow29** [firebase/firebase-ios-sdk#13668]
### Description

App cannot connect to Firestore or other services after building to an iOS 18 target. 

App does connect when deploying to iOS17.5 device. 

Existing app (from app store) still connects.

This is experienced only on new builds to iOS 18 devices. The issue DOES NOT occur when deploying to an iOS 17.5 device / simulator.

11.2.0 - [FirebaseFirestore][I-FST000001] Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.
 This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.

### Reproducing the issue

Upgrade device / xcode to latest. 
XCODE: Version 16.0 (16A242d)
DEVICE: iOS 18.0

Build app - attempt to query firestore.

### Firebase SDK Version

11.20

### Xcode Version

16.0

### Installation Method

Swift Package Manager

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

### Relevant Log Output

```shell
11.2.0 - [FirebaseFirestore][I-FST000001] Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.
 This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by cherylEnkidu** [comment]
Hi @MagicFlow29 ,

I tested iOS 18 on Xcode simulator with latest version of Xcode and Firebase SDK. The app connects to backend successfully. Could you please upgrade the Xcode and SDK, and check the Internet connection on your device or/and simulator? Please let me know if you are still running into problems.

**Comment by cherylEnkidu** [comment]
Hi @MagicFlow29 ,

Could you please enable debug logging and share it with us? Also can you create a simple repo app to see if the problem also exists in the new app?

**Comment by MagicFlow29** [comment]
A fresh app did in fact connect successfully. Were you able to see anything in the logs? I'll start stripping the existing / production code base down to figure out what's caused it.... but feel it could be a setting somewhere that perhaps Apple isn't upgrading on pre-Xcode 16 apps...

**Comment by MagicFlow29** [comment]
OK thanks for your help... realising this must be something specific to my app and not firebase, I did find that a memory leak within SwiftUI was introduced when deploying to iOS 18 devices which subsequently caused the issue with Firebase not being able to connect.
