### ISSUE TITLE
Error installing Firebase

### ISSUE THREAD

**Issue by Jerry8135** [firebase/firebase-ios-sdk#13681]
### Description

when install firebase from pod it always show error,when use swift package manager,it always show can not download it

### Reproducing the issue

after do pod install,it still show the issue
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: xxxxx bytes of body are still expected

### Firebase SDK Version

11.2.0

### Xcode Version

16.0

### Installation Method

CocoaPods

### Firebase Product(s)

Messaging

### Targeted Platforms

iOS

### Relevant Log Output

```shell
pod install --repo-update
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing Firebase (11.2.0)

[!] Error installing Firebase
[!] /usr/bin/git clone https://github.com/firebase/firebase-ios-sdk.git /var/folders/55/xntm2cmx56d3fpnv4vyqf6jh0000gn/T/d20240920-43350-1wq1o3 --template= --single-branch --depth 1 --branch CocoaPods-11.2.0

Cloning into '/var/folders/55/xntm2cmx56d3fpnv4vyqf6jh0000gn/T/d20240920-43350-1wq1o3'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: 8178 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

target 'App' do
  capacitor_pods
  # Add your Pods here
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
end

**Comment by rizafran** [comment]
Hi @Jerry8135, I wasn't able to reproduce the issue. This might be related to internet connection issue. May I know if you've tried using other network?

**Comment by anton-alekseev-amo** [comment]
I have troubles downloading dependencies via SPM on CI for more than 2 days
`2024-09-19 23:59:10.780 xcodebuild[5073:16051] Writing error result bundle to /var/folders/7p/99t0qd9n3s778kb4451spsp40000gn/T/ResultBundle_2024-19-09_23-59-0010.xcresult
xcodebuild: error: Could not resolve package dependencies:
  failed downloading 'https://dl.google.com/firebase/ios/swiftpm/11.1.0/FirebaseAnalytics.zip' which is required by binary target 'FirebaseAnalytics': downloadError("The network connection was lost.")
  failed downloading 'https://dl.google.com/firebase/ios/bin/firestore/11.2.0/rc0/FirebaseFirestoreInternal.zip' which is required by binary target 'FirebaseFirestoreInternal': downloadError("The network connection was lost.")
  failed downloading 'https://dl.google.com/firebase/ios/bin/grpc/1.65.1/rc1/grpc.zip' which is required by binary target 'grpc': downloadError("The network connection was lost.")
  fatalError`
  Other SPM packages are downloading well, so the internet connection is not the case. Does not happen all the time.

**Comment by paulb777** [comment]
@anton-alekseev-amo That sounds like a different issue that we've also been seeing in Firebase CI the last few days that SPM binary dependencies are failing in GitHub Actions. The best workaround we've found is to serialize jobs, that often, but not always works around the GHA networking issue.

**Comment by ryanmcdonald77** [comment]
Been getting the same as anton-alekseev-amo in our self hosted GitHub Actions runner since about 12 hours ago. Doesn't seem flakey as never successful even with jobs serialized

**Comment by paulb777** [comment]
Using the cache action is looking like a promising resolution to the binary Swift Package Manager network failures we were seeing. https://github.com/firebase/data-connect-ios-sdk/pull/16

**Comment by Jerry8135** [comment]
> Hi @Jerry8135, I wasn't able to reproduce the issue. This might be related to internet connection issue. May I know if you've tried using other network?
hi,thank you for your reply,i also think its netowrk issue,i use vpn and my mobile hotpoint,but it still the same result,i am not sure,i search it in google and try many options,now its ok ,maybe its my vpn not stable

**Comment by Jerry8135** [comment]
@rizafran hello,thank you for your reply,i also think its netowrk issue,i use vpn and my mobile hotpoint,but it still the same result,i am not sure,i search it in google and try many options,now its ok ,maybe its my vpn not stable
