### ISSUE TITLE
version 11.0.0 AuthBackendRPCIssuerImplementation.asyncCallToURL keep crashing

### ISSUE THREAD

**Issue by ajunjunandtmac** [firebase/firebase-ios-sdk#13680]
### Description

Hi Firebase team
Our released version using Firebase 11.0.0 and GoogleSignIn 8.0.0 and it keeps crashing now
almost the same issue with #13650, but the stack trace was different, please see the attachment
Our app was written in pure swift, packaged by Xcode 11.3, and SwiftUI was used to build UI
[firebase-11.0.0.txt](https://github.com/user-attachments/files/17068436/firebase-11.0.0.txt)

### Reproducing the issue

I cannot reproducing it, but really causes a lot of crashes in our latest release version

### Firebase SDK Version

11.0.0

### Xcode Version

15.3

### Installation Method

CocoaPods

### Firebase Product(s)

Authentication, Crashlytics, Database

### Targeted Platforms

iOS, App Extensions

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ssv9216** [comment]
This is issue is still happening in version 11.2.0

**Comment by rizafran** [comment]
Thanks for reporting, @ajunjunandtmac. Based on the [related issue](https://github.com/firebase/firebase-ios-sdk/issues/13650#issuecomment-2356853089), the fix would be included in the next v11.3.0 release.

**Comment by ajunjunandtmac** [comment]
> Thanks for reporting, @ajunjunandtmac. Based on the [related issue](https://github.com/firebase/firebase-ios-sdk/issues/13650#issuecomment-2356853089), the fix would be included in the next v11.3.0 release.

Thanks very much, when the new version will release?

**Comment by dibasdauliya** [comment]
getting same issue

**Comment by paulb777** [comment]
See the duplicate issue at #13650 for additional details.
