### ISSUE TITLE
Add Crashlytics SDK and Release Notes to Main Firebase SDK Download

### ISSUE THREAD

**Issue by BranchS** [firebase/firebase-ios-sdk#1368]
Now that Crash Reporter is all but dead, it would be nice if A) the Crashlytics SDK/frameworks were bundled with the main Firebase iOS SDK download. I know many people use Cocoapods making this irrelevant, but for those that don't, it would be nice. Also, once that's done, having the Crashlytics release notes here: https://firebase.google.com/support/release-notes/ios would be nice.

Thanks!

**Comment by paulb777** [comment]
cc: @tkburner

**Comment by BranchS** [comment]
@paulb777 @TKBurner

any update on this? would be so nice to only have one zip to download, and to be able to see Crashlytics release notes with all the others! Doesn't seem like it'd be too hard to just throw them in there.

**Comment by paulb777** [comment]
@BranchS No updates, we're still pursuing. Feel free to also reach out on one of the [official support channels for Crashlytics](https://firebase.google.com/support/). We try to help on non-open source repo Firebase issues here, but can't make any commitments.

**Comment by BranchS** [comment]
As per v5.6 iOS release notes: "Updates to the Crash Reporting SDK documentation to reflect deprecation status."

It would be great now more than ever to bundle the Crashlytics SDK download with the Firebase iOS SDK zip download, and to add its release notes alongside the others.

**Comment by BranchS** [comment]
In addition, Fabric is shutting down in 2019. Without their site, there would be no way to download the SDK of Crashlytics, unless the SDK is added to Firebase's download.

**Comment by paulb777** [comment]
@BranchS We're working on it. No specifics that I can share other than we'll try to have some progress on this well before Firebase 6.

**Comment by BranchS** [comment]
Hi! Any progress on this @paulb777?

Thanks!

**Comment by paulb777** [comment]
@BranchS Thanks for the ping. We are making progress, but nothing I can share yet.

**Comment by paulb777** [comment]
This is now implemented as part of the Crashlytics open sourcing and will roll out along with Firebase 6.15.0
