### ISSUE TITLE
Xcode 16 SPM Cannot be Found

### ISSUE THREAD

**Issue by vncsnts** [firebase/firebase-ios-sdk#13682]
### Description

Running Update Packages will not be able to find firebase sdk

### Reproducing the issue

Packages -> Update to Latest Package versions

Gets error: https://github.com/firebase/firebase-ios-sdk.git: The repository could not be found. Make sure a valid repository exists at the specified location and try again.

### Firebase SDK Version

17.0.0

### Xcode Version

16.0

### Installation Method

Swift Package Manager

### Firebase Product(s)

All

### Targeted Platforms

iOS

### Relevant Log Output

```shell
https://github.com/firebase/firebase-ios-sdk.git: The repository could not be found. Make sure a valid repository exists at the specified location and try again.
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by vncsnts** [comment]
yes @rizafran the ':' was from the logs.

**Comment by paulb777** [comment]
Are you able to open https://github.com/firebase/firebase-ios-sdk.git from a browser?

**Comment by vncsnts** [comment]
> Are you able to open https://github.com/firebase/firebase-ios-sdk.git from a browser?

yep thats why i was able to post issue here :)

**Comment by paulb777** [comment]
There is no version 17.0.0. The current latest release is 11.2.0

**Comment by gabors** [comment]
I think this is an issue with Xcode 16.0 itself as this happens with all other SPM dependencies in my projects.
I tried Xcode 16.1 Beta 2 where "Update Package" appears to be fixed and working properly as in Xcode 15.x

**Comment by paulb777** [comment]
Thanks for sharing. I'll close, since it's unlikely we can do anything from a Firebase perspective.

**Comment by gabors** [comment]
yeah I wish I can find a workaround for Xcode 16.0 for now, nothing works to update a package for me. 
maybe only deleting and adding the package again.

**Comment by bestwnh** [comment]
@gabors Try to add `www.` before `github.com`, I have the similar issue and fix by adding the `www`. So new url should be`https://www.github.com/firebase/firebase-ios-sdk.git`

**Comment by vncsnts** [comment]
> @gabors Try to add `www.` before `github.com`, I have the similar issue and fix by adding the `www`. So new url should be`https://www.github.com/firebase/firebase-ios-sdk.git`

this works! thank you

**Comment by gabors** [comment]
> @gabors Try to add `www.` before `github.com`, I have the similar issue and fix by adding the `www`. So new url should be`https://www.github.com/firebase/firebase-ios-sdk.git`

Yeah that works! So weird.
How did you think of this workaround?
