### ISSUE TITLE
Getting "Received invalid response at https://github.com/firebase/firebase-ios-sdk.git. Please make sure it is a package collection URL." When attempting to add firebase sdk in SPM

### ISSUE THREAD

**Issue by rufflestiltzken** [firebase/firebase-ios-sdk#13690]
### Description

Getting this error message when trying to add firebase sdk to Xcode project through SPM."Received invalid response at https://github.com/firebase/firebase-ios-sdk.git. Please make sure it is a package collection URL."

Xcode Version 16.0

### Reproducing the issue

File-> Add Package dependencies 
Click "+" button lower left of Collections list
Click "Add Package Collection"
Paste link in Add Package Collection Text Input: https://github.com/firebase/firebase-ios-sdk.git
Click Load
Opens dialog reading: Received invalid response at https://github.com/firebase/firebase-ios-sdk.git. Please make sure it is a package collection URL.

### Firebase SDK Version

10.9

### Xcode Version

16.0

### Installation Method

Swift Package Manager

### Firebase Product(s)

All

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Received invalid response at https://github.com/firebase/firebase-ios-sdk.git. Please make sure it is a package collection URL
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
You should use the `Add Package Dependency` (the + in the UI) not `Add Package Collection`.

**Comment by rufflestiltzken** [comment]
Got it.  Yeah, the plus sign lower left is for collections. Needed to paste the link in the top right and click Add Package.  New UI for 16 maybe?
<img width="2098" alt="image" src="https://github.com/user-attachments/assets/c1353b03-937b-45d2-863d-313eccf4c0b9">
