### ISSUE TITLE
Device token is not generated 

### ISSUE THREAD

**Issue by sumit-vts** [firebase/firebase-ios-sdk#13717]
### Description

we updated our firebase sdk from 6.34.0 to 11.1.0. after update the SDK the device token in not generated even delegate method  func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String) even not called

code in 
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        FirebaseApp.configure()
        
        Messaging.messaging().delegate = self

        UNUserNotificationCenter.current().delegate = self
        
        return true
    }

### Firebase SDK Version

11.1.0

### Xcode Version

15.3

### Installation Method

CocoaPods

### Firebase Product(s)

Messaging

### Targeted Platforms

iOS

**Comment by ncooke3** [comment]
Hi @sumit-vts, does https://github.com/firebase/firebase-ios-sdk/issues/10679#issuecomment-1402776795 help explain this behavior?

**Comment by sumit-vts** [comment]
Hi I still facing the same issue. and device token delegate method is not called

**Comment by sumit-vts** [comment]
also when user logout that time we delete the previous token and try to regenerate new token but some time its not provide toen ad give error 

 func deleteAndUpdateToken() {
        Installations.installations().delete { error in
            if let error = error {
                logger.error(error.localizedDescription)
            } else {
                Installations.installations().authTokenForcingRefresh(true) { result, error in
                    if result != nil {
                        Messaging.messaging().deleteToken { error in
                            if let error = error {
                                logger.error(error.localizedDescription)
                            } else {
                                logger.info("FCM TOKEN DELETED")
                                Messaging.messaging().token { token, error in
                                    if let token = token {
                                        logger.info("NEW FCM TOKEN GENERATED")
                                        self.credentials.deviceToken = token
                                    }
                                    if let error = error {
                                        logger.error("ERROR WHILE GENERATING NEW FCM TOKEN")
                                        logger.error(error.localizedDescription)
                                    }
                                }
                            }
                        }
                    } else if let error = error {
                        logger.error(error.localizedDescription)
                    }
                }
            }
        }
    }

**Comment by sumit-vts** [comment]
hi any update on this

**Comment by rizafran** [comment]
Hi @sumit-vts, I wasn't able to reproduce the issue. May I know if your swizzling is enabled? Also, make sure that you're using the correct APNs Auth key in the console.
