### ISSUE TITLE
FR: field mask support in Firestore query

### ISSUE THREAD

**Issue by tonysung** [firebase/firebase-ios-sdk#1372]
* Firebase SDK version: master
* Firebase Component: Firestore

There is no support for field mask / select() in FIRQuery as in the Firestore Node.js API.

Reference: https://cloud.google.com/nodejs/docs/reference/firestore/0.14.x/Query#select

> select
> select(...fieldPaths) returns Query
> 
> Creates and returns a new Query instance that applies a field mask to the result and returns only the specified subset of fields. You can specify a list of field paths to return, or use an empty list to only return the references of matching documents.

**Comment by wilhuff** [comment]
Thanks for your interest, but this omission is intentional.

See here for rationale:
https://github.com/firebase/firebase-js-sdk/issues/212
