### ISSUE TITLE
Dependency Conflict

### ISSUE THREAD

**Issue by trvon** [firebase/firebase-ios-sdk#13741]
### Description

There is a dependency conflict in this library affecting other packages. For example, [FirebaseAnalytics](https://github.com/firebase/firebase-ios-sdk/blob/main/FirebaseAnalytics.podspec) depends on

```
s.dependency 'nanopb', '~> 3.30910.0'
```

But in the package's top-level package.swift there is 

```
    .package(
      url: "https://github.com/firebase/nanopb.git",
      "2.30910.0" ..< "2.30911.0"
    ),
```
Other examples include: [FirebaseSessions](https://github.com/firebase/firebase-ios-sdk/blob/91e6f2b9c4e0b98110b4f572eb07213cda8b0e5f/FirebaseSessions.podspec#L48), [GoogleAppMeasurement](https://github.com/firebase/firebase-ios-sdk/blob/91e6f2b9c4e0b98110b4f572eb07213cda8b0e5f/GoogleAppMeasurement.podspec#L35), [FirebasePerformance](https://github.com/firebase/firebase-ios-sdk/blob/91e6f2b9c4e0b98110b4f572eb07213cda8b0e5f/FirebasePerformance.podspec#L70), [FirebaseMessaging](https://github.com/firebase/firebase-ios-sdk/blob/91e6f2b9c4e0b98110b4f572eb07213cda8b0e5f/FirebaseMessaging.podspec#L71), [FirebaseStoreInternal](https://github.com/firebase/firebase-ios-sdk/blob/91e6f2b9c4e0b98110b4f572eb07213cda8b0e5f/FirebaseFirestoreInternal.podspec#L110), [FirebaseCrashanalytics](https://github.com/firebase/firebase-ios-sdk/blob/91e6f2b9c4e0b98110b4f572eb07213cda8b0e5f/FirebaseCrashlytics.podspec#L69), and [FirebaseInAppMessaging](https://github.com/firebase/firebase-ios-sdk/blob/91e6f2b9c4e0b98110b4f572eb07213cda8b0e5f/FirebaseInAppMessaging.podspec#L88). 

I believe the top-level swift file's use of the firebase/nanopb library is correct. This is seen in how other Firebase libraries use the internally maintained nanopb library. I am unsure why there are other podspec files using different versions and libraries.

### Firebase SDK Version

11.2

### Xcode Version

16

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, Crashlytics, In-App Messaging

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
Those two versions are equivalent across CocoaPods and SPM.  The CocoaPods nanopb version required a major version update with Firebase 11 because it handles minimum platform specifications differently from Swift Package Manager
