### ISSUE TITLE
Crashlytics doc generation

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#13763]
### Description

Product -> Build Documentation for Crashlytics generates many build warnings and incomplete docs:

![Screenshot 2024-10-01 at 10 41 48 AM](https://github.com/user-attachments/assets/35dfd9f1-ab8a-465e-9074-baca88b0ffc8)

### Reproducing the issue

Product -> Build Documentation 

### Firebase SDK Version

11.3

### Xcode Version

16.1

### Installation Method

CocoaPods

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by themiswang** [comment]
For SPM I only see warning from package Promise, this is probably not something we can fix in Crashlytics:
![Image](https://github.com/user-attachments/assets/390fefe1-118a-4e5b-830c-40a3d80a13d6)

For CocoaPods the only warning we have is: `ld: warning: ignoring duplicate libraries: '-lc++'` but seems like it is expected. 
<img width="268" alt="Image" src="https://github.com/user-attachments/assets/1d47cc27-5507-4017-bafd-6a34908cb6c5" />
We probably need to set deployment target from other dependency podspec.

**Comment by paulb777** [comment]
Confirmed. I'm not sure if I had a bad state before or Xcode 16.2 fixed something. Thanks for taking a look.
