### ISSUE TITLE
[App Check] Unable to sign in using a test phone number

### ISSUE THREAD

**Issue by xmollv** [firebase/firebase-ios-sdk#13774]
### Description

Hello! We enabled App Check yesterday on our app and everything seems to be working as expected, both for production builds and for debug ones expect for using test phone numbers. After enabling App Check, we can't seem to be able to log in with our test phone numbers defined in Firebase > Authentication > Phone > Test Phone Numbers. Is there any workaround?

We only allow users to sign in in our app using phone numbers, which means that not being able to use test phone numbers puts us in a very bad position to develop the app. Is there any workaround? Should that work and it doesn't (meaning its a bug) or does that work as intended? I didn't see anything about test phone numbers becoming invalid under App Check!

The error we get when we try to use a test phone number: 

```
The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section.
```

With a real phone number, it just works, so not sure what's up!

Thanks!

### Firebase SDK Version

11.3.0

### Xcode Version

16.0

### Installation Method

Swift Package Manager

### Firebase Product(s)

App Check, Authentication, Firestore

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

{
  "pins" : [
    {
      "identity" : "abseil-cpp-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/abseil-cpp-binary.git",
      "state" : {
        "revision" : "194a6706acbd25e4ef639bcaddea16e8758a3e27",
        "version" : "1.2024011602.0"
      }
    },
    {
      "identity" : "app-check",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/app-check.git",
      "state" : {
        "revision" : "21fe1af9be463a359aaf8d96789ef73fc3760d09",
        "version" : "11.0.1"
      }
    },
    {
      "identity" : "facebook-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/facebook/facebook-ios-sdk",
      "state" : {
        "revision" : "c0273540e9426606fc8bc3cf8e7c702f38e76cfc",
        "version" : "17.2.0"
      }
    },
    {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk.git",
      "state" : {
        "revision" : "f909f901bfba9e27e4e9da83242a4915d6dd64bb",
        "version" : "11.3.0"
      }
    },
    {
      "identity" : "giphy-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/Giphy/giphy-ios-sdk",
      "state" : {
        "revision" : "cdefbedc9f99d40cc64667a2bfaae67a1cf36fbb",
        "version" : "2.2.12"
      }
    },
    {
      "identity" : "googleappmeasurement",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleAppMeasurement.git",
      "state" : {
        "revision" : "93406fd21b85e66e2d6dbf50b472161fd75c3f1f",
        "version" : "11.3.0"
      }
    },
    {
      "identity" : "googledatatransport",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleDataTransport.git",
      "state" : {
        "revision" : "617af071af9aa1d6a091d59a202910ac482128f9",
        "version" : "10.1.0"
      }
    },
    {
      "identity" : "googleutilities",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleUtilities.git",
      "state" : {
        "revision" : "53156c7ec267db846e6b64c9f4c4e31ba4cf75eb",
        "version" : "8.0.2"
      }
    },
    {
      "identity" : "grpc-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/grpc-binary.git",
      "state" : {
        "revision" : "f56d8fc3162de9a498377c7b6cea43431f4f5083",
        "version" : "1.65.1"
      }
    },
    {
      "identity" : "gtm-session-fetcher",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/gtm-session-fetcher.git",
      "state" : {
        "revision" : "a2ab612cb980066ee56d90d60d8462992c07f24b",
        "version" : "3.5.0"
      }
    },
    {
      "identity" : "instabug-sp",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/Instabug/Instabug-SP",
      "state" : {
        "revision" : "09b1ba4d9ebad410661f0ba160d0c46dd0c1ae91",
        "version" : "13.4.2"
      }
    },
    {
      "identity" : "interop-ios-for-google-sdks",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/interop-ios-for-google-sdks.git",
      "state" : {
        "revision" : "2d12673670417654f08f5f90fdd62926dc3a2648",
        "version" : "100.0.0"
      }
    },
    {
      "identity" : "ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/spotify/ios-sdk",
      "state" : {
        "revision" : "5bd49e227145dee4871b1667bf81a2b896590176",
        "version" : "2.1.7"
      }
    },
    {
      "identity" : "leveldb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/leveldb.git",
      "state" : {
        "revision" : "a0bc79961d7be727d258d33d5a6b2f1023270ba1",
        "version" : "1.22.5"
      }
    },
    {
      "identity" : "libwebp-xcode",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/SDWebImage/libwebp-Xcode",
      "state" : {
        "revision" : "b2b1d20a90b14d11f6ef4241da6b81c1d3f171e4",
        "version" : "1.3.2"
      }
    },
    {
      "identity" : "lnextensionexecutor",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/LeoNatan/LNExtensionExecutor.git",
      "state" : {
        "revision" : "c0226dcd7d653d4c22dd16ccd72619c86b610c2d",
        "version" : "1.3.0"
      }
    },
    {
      "identity" : "lottie-spm",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/airbnb/lottie-spm",
      "state" : {
        "revision" : "b842598f1295f3ffa1475b1580672d1fe5b83580",
        "version" : "4.5.0"
      }
    },
    {
      "identity" : "mixpanel-swift",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/mixpanel/mixpanel-swift",
      "state" : {
        "revision" : "48d6668ceaaefc338f94e2b084c3cf77b90182f8",
        "version" : "4.3.0"
      }
    },
    {
      "identity" : "nanopb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/nanopb.git",
      "state" : {
        "revision" : "b7e1104502eca3a213b46303391ca4d3bc8ddec1",
        "version" : "2.30910.0"
      }
    },
    {
      "identity" : "phonenumberkit",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/marmelroy/PhoneNumberKit",
      "state" : {
        "revision" : "c107075aa8d394be7aced273a46e944afe8b321b",
        "version" : "3.8.0"
      }
    },
    {
      "identity" : "promises",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/promises.git",
      "state" : {
        "revision" : "540318ecedd63d883069ae7f1ed811a2df00b6ac",
        "version" : "2.4.0"
      }
    },
    {
      "identity" : "sdwebimage",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/SDWebImage/SDWebImage",
      "state" : {
        "revision" : "8a1be70a625683bc04d6903e2935bf23f3c6d609",
        "version" : "5.19.7"
      }
    },
    {
      "identity" : "snap-kit-spm",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/Snapchat/snap-kit-spm",
      "state" : {
        "revision" : "6c44e89e330e8b37ea3f7405d75c9a161d4f8281",
        "version" : "2.5.0"
      }
    },
    {
      "identity" : "socket.io-client-swift",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/socketio/socket.io-client-swift",
      "state" : {
        "revision" : "42da871d9369f290d6ec4930636c40672143905b",
        "version" : "16.1.1"
      }
    },
    {
      "identity" : "starscream",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/daltoniam/Starscream",
      "state" : {
        "revision" : "c6bfd1af48efcc9a9ad203665db12375ba6b145a",
        "version" : "4.0.8"
      }
    },
    {
      "identity" : "swift-protobuf",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-protobuf.git",
      "state" : {
        "revision" : "edb6ed4919f7756157fe02f2552b7e3850a538e5",
        "version" : "1.28.1"
      }
    }
  ],
  "version" : 2
}

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reporting, @xmollv. AFAIK, test phone numbers should also work with App Check. I also tried to reproduce the issue, but I was able to login using my test phone number from the console. I'm wondering if you didn't limit the use of SMS to a specific region as mentioned [here](https://stackoverflow.com/a/78227184).

**Comment by xmollv** [comment]
> Thanks for reporting, @xmollv. AFAIK, test phone numbers should also work with App Check. I also tried to reproduce the issue, but I was able to login using my test phone number from the console. I'm wondering if you didn't limit the use of SMS to a specific region as mentioned [here](https://stackoverflow.com/a/78227184).

Thanks for the reply! We do have limited the SMS deliverability to some regions, but the phone number I'm using is indeed from one of those regions. The test phone number I'm testing with is `+1 111-111-1111`, which should work based on this filters, right?

<img width="973" alt="image" src="https://github.com/user-attachments/assets/751a301c-5cd0-43a4-8749-01ca8776cee7">

**Comment by rizafran** [comment]
Thanks for the update, @xmollv. Yep, based on your filter, it should work as long as you select your region. I also tried this and it's working on my end too. Just to confirm, I'm wondering if you have tried double-checking your `GoogleService-Info.plist` if it matches the correct Firebase project you're using?

**Comment by xmollv** [comment]
> Thanks for the update, @xmollv. Yep, based on your filter, it should work as long as you select your region. I also tried this and it's working on my end too. Just to confirm, I'm wondering if you have tried double-checking your `GoogleService-Info.plist` if it matches the correct Firebase project you're using?

Yes, it does! If I use a non-test phone, I can sign in just fine. If I use a test phone, it fails. Here's a quick demo where the only difference is the phone number being used (test one vs non test one):

https://github.com/user-attachments/assets/d271e027-0f33-40bd-8d36-e94ec223c3c6

**Comment by rizafran** [comment]
Thanks for sharing your demo, @xmollv. I was able to reproduce the issue by using the same test number. I've informed the engineers about this for investigation.

**Comment by xmollv** [comment]
> Thanks for sharing your demo, @xmollv. I was able to reproduce the issue by using the same test number. I've informed the engineers about this for investigation.

@rizafran awesome, thank you! You mentioned that for you it worked with a test phone number, would you mind sharing which one it was? Asking because we're blocked on this, but if there's a test phone number that works, I'll remove `+1 111-111-1111` from our list of test phone numbers and add the one that worked for you! 🙏🏼

**Comment by rizafran** [comment]
Hi @xmollv, you could try the following test numbers that I used:
- +1 234-567-8901
- +1 650-555-4567

**Comment by xmollv** [comment]
> Hi @xmollv, you could try the following test numbers that I used:
> 
> * +1 234-567-8901
> * +1 650-555-4567

@rizafran both of them work! tysm for unblocking us ❤️

**Comment by rizafran** [comment]
You're welcome, @xmollv :)
