### ISSUE TITLE
Delete User Error: This operation is sensitive and requires recent authentication. Log in again before retrying this request.

### ISSUE THREAD

**Issue by occassionally** [firebase/firebase-ios-sdk#13810]
### Description

I've configured Apple as a sign-in provider with Firebase, and provided all necessary information on the console to enable OAuth code flow.

When deleting a user account, I exactly followed the docs example [here](https://firebase.google.com/docs/auth/ios/apple#token_revocation):

```ts
func authorizationController(controller: ASAuthorizationController,
                             didCompleteWithAuthorization authorization: ASAuthorization) {
  guard let appleIDCredential = authorization.credential as? ASAuthorizationAppleIDCredential
  else {
    print("Unable to retrieve AppleIDCredential")
    return
  }

  guard let _ = currentNonce else {
    fatalError("Invalid state: A login callback was received, but no login request was sent.")
  }

  guard let appleAuthCode = appleIDCredential.authorizationCode else {
    print("Unable to fetch authorization code")
    return
  }

  guard let authCodeString = String(data: appleAuthCode, encoding: .utf8) else {
    print("Unable to serialize auth code string from data: \(appleAuthCode.debugDescription)")
    return
  }

  Task {
    do {
      try await Auth.auth().revokeToken(withAuthorizationCode: authCodeString)
      try await user?.delete()
      self.updateUI()
    } catch {
      self.displayError(error)
    }
  }
}
```

The flow is:

1. The user requests deletion of their account.
2. I ask the user to Sign in with Apple again.
3. If the sign-in was successful (see above code), first revoke the token, then delete the Firebase account.

After the third step, I got this error:

```ts
This operation is sensitive and requires recent authentication. Log in again before retrying this request.
```

I know this error is being thrown by this line:

```ts
try await user?.delete()
```

I know this because I got an email from Apple Support notifying me that my app has revoked my tokens, and that I will need to sign in again the next time I try to use the app.

The [docs](https://firebase.google.com/docs/reference/ios/firebaseauth/api/reference/Enums/FIRAuthErrorCode#:~:text=password%20more%20than-,5%20minutes,-after%20signing%20in) mention that the user needs to have re-authenticated within 5 minutes:

> [FIRAuthErrorCodeRequiresRecentLogin](https://firebase.google.com/docs/reference/ios/firebaseauth/api/reference/Enums/FIRAuthErrorCode#/c:@E@FIRAuthErrorCode@FIRAuthErrorCodeRequiresRecentLogin)
>Indicates the user has attempted to change email or password more than 5 minutes after signing in.

In the case of my app, it was within seconds.

### Reproducing the issue

Please see the code above for a minimal reproducible example.

### Firebase SDK Version

11.3.0

### Xcode Version

16.0

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### Relevant Log Output

```shell
This operation is sensitive and requires recent authentication. Log in again before retrying this request.
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment]
Hi @occassionally, is this a flow you are implementing for the first time, or something that was working in a previous Firebase version before upgrading to 11.3?

**Comment by occassionally** [comment]
@ncooke3 Thanks for the quick response! This is the first time I've attempted it, so unfortunately I'm not sure if it was working before or not.

**Comment by occassionally** [comment]
I got it to work, but I didn't do anything differently.

I didn't think it could be the case, but I thought maybe there is an issue with trying to delete a user after the tokens have been revoked.

```ts
try await Auth.auth().revokeToken(withAuthorizationCode: authCodeString)
try await user?.delete()
```

I tested it with only `revokeToken`, and it worked. Then I tested it with only `delete`, and it worked.

Then, just to confirm, I tested it again with both, and to my surprise, it worked. I tested it a few more times and it's worked each time since.

I made no changes at all, though. It's great that its working, but it's a little concerning still, since I don't know if or when it could happen again.

**Comment by ncooke3** [comment]
@occassionally, glad to hear it's working now. I'm unsure what was going wrong earlier. 

I tested this with a test app and didn't run into this. The implementation is a little different from the sample code
- https://github.com/firebase/firebase-ios-sdk/blob/a366d6c4982df6d724c95f4ed399fe444593e9e5/FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/UserViewController.swift#L229-L627
- https://github.com/firebase/firebase-ios-sdk/blob/main/FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/UserViewController.swift#L357-L381

Mainly, the reauthentication gets called right before the delete request:
https://github.com/firebase/firebase-ios-sdk/blob/a366d6c4982df6d724c95f4ed399fe444593e9e5/FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/UserViewController.swift#L255C1-L262C32
