### ISSUE TITLE
[FirebaseAuth] Error 17006, The given sign-in provider is disabled

### ISSUE THREAD

**Issue by dobreandl** [firebase/firebase-ios-sdk#13831]
### Description

Hello!

Today, we encountered an issue with Firebase Authentication. When I attempt to verify a phone number using the PhoneAuthProvider.provider().verifyPhoneNumber method, I consistently receive the following error: "The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section."

I want to confirm that the phone sign-in provider is indeed enabled in the Firebase console, and SMS verification is activated for all regions.

Everything was functioning perfectly until today, and we haven't made any changes. However, the error started occurring unexpectedly.

Additionally, we discovered that the verification works correctly for US phone numbers, but it fails for Hungary numbers, producing the error mentioned above. We also attempted to add Hungary to the SMS verification regions list directly, but it didn’t resolve the issue.

We would appreciate your assistance in resolving this matter. It seems like it could be a bug.

Thank you!

### Reproducing the issue

Integrate the iOS SDK, try to login with a HU number.

### Firebase SDK Version

10.24.0

### Xcode Version

 15.2 (15C500b)

### Installation Method

CocoaPods

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Error Domain=FIRAuthErrorDomain Code=17006 "The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section." UserInfo={NSLocalizedDescription=The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section., FIRAuthErrorUserInfoNameKey=ERROR_OPERATION_NOT_ALLOWED}
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

  - Firebase/Analytics (10.24.0):
    - Firebase/Core
  - Firebase/Core (10.24.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 10.24.0)
  - Firebase/CoreOnly (10.24.0):
    - FirebaseCore (= 10.24.0)
  - Firebase/Crashlytics (10.24.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 10.24.0)
  - Firebase/DynamicLinks (10.24.0):
    - Firebase/CoreOnly
    - FirebaseDynamicLinks (~> 10.24.0)
  - Firebase/Messaging (10.24.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 10.24.0)
  - FirebaseAnalytics (10.24.0):
    - FirebaseAnalytics/AdIdSupport (= 10.24.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (10.24.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleAppMeasurement (= 10.24.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - FirebaseAppCheckInterop (10.24.0)
  - FirebaseAuth (10.24.0):
    - FirebaseAppCheckInterop (~> 10.17)
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/Environment (~> 7.8)
    - GTMSessionFetcher/Core (< 4.0, >= 2.1)
    - RecaptchaInterop (~> 100.0)
  - FirebaseCore (10.24.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.12)
    - GoogleUtilities/Logger (~> 7.12)
  - FirebaseCoreExtension (10.24.0):
    - FirebaseCore (~> 10.0)
  - FirebaseCoreInternal (10.24.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseCrashlytics (10.24.0):
    - FirebaseCore (~> 10.5)
    - FirebaseInstallations (~> 10.0)
    - FirebaseRemoteConfigInterop (~> 10.23)
    - FirebaseSessions (~> 10.5)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.8)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesObjC (~> 2.1)
  - FirebaseDynamicLinks (10.24.0):
    - FirebaseCore (~> 10.0)
  - FirebaseInstallations (10.24.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)
  - FirebaseMessaging (10.24.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.3)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Reachability (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - FirebaseRemoteConfigInterop (10.24.0)
  - FirebaseSessions (10.24.0):
    - FirebaseCore (~> 10.5)
    - FirebaseCoreExtension (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.10)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesSwift (~> 2.1)

**Comment by cvance** [comment]
@dobreandl were you able to resolve this issue? I had the same problem but using Peru phone numbers. Fortunately I was able to resolve (workaround) it by going to the Authentication settings in the firebase console, selecting SMS region policy, switching from Deny to Allow and then adding my supported countries explicitly. 

Not sure what changed in the past week for Firebase that broke this. Also they should fix the error code because 17006 is not accurate based on the error message. Also a test phone number should always work regardless of SMS region policy.

**Comment by dobreandl** [comment]
@cvance Not really, it was likely an issue on their backend. I've seen other posts mentioning that certain phone numbers didn't work, mainly due to problems with the third-party services Firebase uses for sending SMS messages.

**Comment by dobreandl** [comment]
@rizafran this error still occurs I have some test phone numbers that don't work, obviously I don't want to make them public, is there a way to send them your way for you to test?
