### ISSUE TITLE
InApp Messaging image sizes confusion

### ISSUE THREAD

**Issue by saldous** [firebase/firebase-ios-sdk#13847]
### Description

In the Firebase console, trying to set an In App Messaging campaign, I'm having trouble with the image sizes.
<img width="475" alt="image" src="https://github.com/user-attachments/assets/932fd384-55b3-403c-81f7-03daa7f6fb30">
Portrait image URL (aspect ratio 3:2). 3:2 is not a portrait aspect ratio!
If I try and upload a 2:3, I get an error saying the image is too tall.

Can you please clarify what the correct image sizes should be for both portrait and landscape? Thank you

### Firebase SDK Version

11.3

### Xcode Version

15.4

### Installation Method

CocoaPods

### Firebase Product(s)

In-App Messaging

### Targeted Platforms

iOS

**Comment by yakovmanshin** [comment]
@saldous What you’re seeing in the console is technically correct (though confusing, of course).

“Portrait image URL” actually means “the image used when *the device* is in portrait orientation.”

And indeed, the image has a 3:2 aspect ratio in portrait mode, and 1:1 in landscape.

<img width="512" src="https://github.com/user-attachments/assets/1649586f-5d3a-467f-a560-3f01114b83b5">
<img width="680" src="https://github.com/user-attachments/assets/9323f4db-ad63-4afc-a8e7-1f70077e8cd5">

**Comment by saldous** [comment]
@yakovmanshin thank you! That helps a lot.
