### ISSUE TITLE
Can't upgrade to Firebase 5.1.0 with GoogleTagManager 6.0.0

### ISSUE THREAD

**Issue by welshm** [firebase/firebase-ios-sdk#1384]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.4
  * Firebase SDK version: 5.1.0
  * Firebase Component: Core, Messaging, DynamicLinks
  * Component version: 5.1.0

### [REQUIRED] Step 3: Describe the problem

[!] CocoaPods could not find compatible versions for pod "FirebaseAnalytics":
  In Podfile:
    Firebase/Core (= 5.1.0) was resolved to 5.1.0, which depends on
      FirebaseAnalytics (= 5.0.1)

    GoogleTagManager (= 6.0.0) was resolved to 6.0.0, which depends on
      FirebaseAnalytics (~> 4.0)

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Create a project that has both Firebase and TagManager with pods

e.g.
```
  def googleLibs
    pod 'Firebase/Core', '5.1.0'
    pod 'Firebase/DynamicLinks', '5.1.0'
    pod 'Firebase/Messaging', '5.1.0'
    pod 'GoogleSignIn', '4.1.2'
    pod 'GoogleTagManager', '6.0.0'
    pod 'Fabric', '1.7.7'
    pod 'Crashlytics', '3.10.1'
  end
```

#### Relevant Code:

`pod update`

**Comment by morganchen12** [comment]
Thanks for filing this, I've asked the GoogleTagManager team to update their pod and will keep this ticket updated with details.

**Comment by morganchen12** [comment]
Tracked internally at b/109888889.

**Comment by paulb777** [comment]
Version 7.0.0 of GoogleTagManager has been pushed that has been updated to depend on FirebaseAnalytics 5.x - https://github.com/CocoaPods/Specs/blob/master/Specs/9/5/6/GoogleTagManager/7.0.0/GoogleTagManager.podspec.json#L4
