### ISSUE TITLE
Package Resolution failed on first installation.

### ISSUE THREAD

**Issue by azizyuldashev95** [firebase/firebase-ios-sdk#13881]
### Description

Since yesterday I have been encountering this issue when trying to add Firebase to my app in xCode.
This is my first time using Firebase on anything in xCode.

Expected to simply be able to add the firebase sdk. Instead, I kept getting this error:
<img width="1087" alt="Screenshot 2024-10-12 at 10 51 25" src="https://github.com/user-attachments/assets/fb5e0194-8450-45d6-96c2-91091cc4b9ff">

Things I tried so far:
I tried using different links in the SPM like "https://github.com/firebase/firebase-ios-sdk" or "https://github.com/firebase/firebase-ios-sdk.git", which made no difference.
Restarted xCode, laptop, deleted and remade my Firebase project file. Still the same.

**Small update:**
After cleaning the build folder, deleting Derived data and Archives there seemed to be a little progress:
<img width="1084" alt="Screenshot 2024-10-12 at 12 42 00" src="https://github.com/user-attachments/assets/3f90f677-0a71-4faf-9e95-b94e42e2d583">
The bar would always go to 15-20% and restarrt from 0% again.

But then the result is still the same...
<img width="1084" alt="Screenshot 2024-10-12 at 12 48 32" src="https://github.com/user-attachments/assets/6ab86757-e19c-44c1-b063-375a017e16ab">

### Reproducing the issue

xCode > File > Add Package Dependencies > searched for "https://github.com/firebase/firebase-ios-sdk" > Clicked Add Package > Thats when the screenshot above happens.

### Firebase SDK Version

11.3.0 Up to next major

### Xcode Version

16

### Installation Method

Swift Package Manager

### Firebase Product(s)

All

### Targeted Platforms

iOS

**Comment by azizyuldashev95** [comment]
Seems like it was a very weird connection issue (even though I have a stable connection). I solved it by connecting to a different internet source. Closing this issue.

**Comment by minon250** [comment]
Unfortunatley I'm still facing this issue

**Comment by QaziAmmar** [comment]
Same her I am trying to add firebase SMP [github.com/firebase/firebase-ios-sdk.git](https://github.com/firebase/firebase-ios-sdk.git) to Xcode 16 and keep showing me the same issue. I have changed my network, delete the drive data, restart the computer and xCode but nothing works. 
![Screenshot 2024-10-28 at 3 26 06 PM](https://github.com/user-attachments/assets/7a5d293d-0129-45a6-8e5f-03f52f3668db)

**Comment by burak-initialcode** [comment]
Same here!
