### ISSUE TITLE
unity ios custom image via firebase cloud messages

### ISSUE THREAD

**Issue by jedai7** [firebase/firebase-ios-sdk#13948]
### Description

I have android and ios build from unity 2021.3.24. And i want to send push notification with image. In Android it works fine
![image](https://github.com/user-attachments/assets/1530dd98-8359-46be-b504-e0f9ed011633)
but on ios its dont work. Image missing
![image](https://github.com/user-attachments/assets/79bda526-643b-47b5-bbd6-4692307381b5)
Original thread created at unity repository https://github.com/firebase/firebase-unity-sdk/issues/1123
<img width="958" alt="image" src="https://github.com/user-attachments/assets/186e2cb1-3c85-41ee-9479-9de9bbc503e2">

### Firebase SDK Version

10.28.1

### Xcode Version

16.0

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics, In-App Messaging, Messaging, Remote Config

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @jedai7, we're unable to reproduce the issue. May I know if you have added the [notification service extension](https://firebase.google.com/docs/cloud-messaging/ios/send-image?hl=en&authuser=0) in your app?

**Comment by jedai7** [comment]
Hi @rizafran  sorry for long pause. I created
NotificationService.h with code
`//
//  NotificationService.h
//  NotificationExtention
//
//  Created by n1090 on 11.10.2024.
//

#import <UserNotifications/UserNotifications.h>

@interface NotificationService : UNNotificationServiceExtension

@end
`

I created NotificationService.m
`//
//  NotificationService.m
//  NotificationExtention
//
//  Created by n1090 on 11.10.2024.
//

#import "NotificationService.h"
@import FirebaseMessaging;

@interface NotificationService () <NSURLSessionDelegate>
@property(nonatomic) void (^contentHandler)(UNNotificationContent *contentToDeliver);
@property(nonatomic) UNMutableNotificationContent *bestAttemptContent;
@end

@implementation NotificationService

- (void)didReceiveNotificationRequest:(UNNotificationRequest *)request withContentHandler:(void (^)(UNNotificationContent * _Nonnull))contentHandler {
    self.contentHandler = contentHandler;
    self.bestAttemptContent = [request.content mutableCopy];

    // Modify the notification content here as you wish
    self.bestAttemptContent.title = [NSString stringWithFormat:@"%@ [modified]",
    self.bestAttemptContent.title];

  // Call FIRMessaging extension helper API.
  [[FIRMessaging extensionHelper] populateNotificationContent:self.bestAttemptContent
                                            withContentHandler:contentHandler];
}


- (void)serviceExtensionTimeWillExpire {
    // Called just before the extension will be terminated by the system.
    // Use this as an opportunity to deliver your "best attempt" at modified content, otherwise the original push payload will be used.
    self.contentHandler(self.bestAttemptContent);
}

@end
`

Both file put in Assets/Plugins/iOS in unity project and made build. Trying send messages with icon and result the same

**Comment by rizafran** [comment]
Sorry for the late revert, @jedai7. As discussed with the team, this seems to be a Unity-related issue since it's not reproducible in native iOS. With this, the original issue you filed in Unity SDK repo will be reopened to investigate. Thanks.
