### ISSUE TITLE
com.google.remoteconfig.update.ErrorDomain Code=8001

### ISSUE THREAD

**Issue by harveyHW** [firebase/firebase-ios-sdk#13968]
### Description

Optional<Error>
  - some : Error Domain=com.google.remoteconfig.update.ErrorDomain Code=8001 "[{
  "error": {
    "code": 403,
    "message": "Permission denied: Consumer 'api_key:-----------------------------------------' has been suspended.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "CONSUMER_SUSPENDED",
        "domain": "googleapis.com",
        "metadata": {
          "service": "firebaseremoteconfigrealtime.googleapis.com",
          "consumer": "projects/441037940741"
        }
      }
    ]
  }
}
]" UserInfo={NSLocalizedDescription=[{
  "error": {
    "code": 403,
    "message": "Permission denied: Consumer 'api_key:-----------------------------------------' has been suspended.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "CONSUMER_SUSPENDED",
        "domain": "googleapis.com",
        "metadata": {
          "service": "firebaseremoteconfigrealtime.googleapis.com",
          "consumer": "projects/441037940741"
        }
      }
    ]
  }
}
]}

### Reproducing the issue

Online users  and debug catch this errors

### Firebase SDK Version

10.9

### Xcode Version

15

### Installation Method

CocoaPods

### Firebase Product(s)

AB Testing, Analytics, Remote Config

### Targeted Platforms

iOS

### Relevant Log Output

```shell
 - some : Error Domain=com.google.remoteconfig.update.ErrorDomain Code=8001 "[{
  "error": {
    "code": 403,
    "message": "Permission denied: Consumer 'api_key:-----------------------------------------' has been suspended.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "CONSUMER_SUSPENDED",
        "domain": "googleapis.com",
        "metadata": {
          "service": "firebaseremoteconfigrealtime.googleapis.com",
          "consumer": "projects/441037940741"
        }
      }
    ]
  }
}
]" UserInfo={NSLocalizedDescription=[{
  "error": {
    "code": 403,
    "message": "Permission denied: Consumer 'api_key:-----------------------------------------' has been suspended.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "CONSUMER_SUSPENDED",
        "domain": "googleapis.com",
        "metadata": {
          "service": "firebaseremoteconfigrealtime.googleapis.com",
          "consumer": "projects/441037940741"
        }
      }
    ]
  }
}
]}

```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @harveyHW, per checking, it seems that you're having a payment issue with your project account. With this, please file a ticket to our [support channel](https://firebase.google.com/support/) so that they could investigate your account.

I'll now be closing this issue.
