### ISSUE TITLE
firebase_message:Invalid fetch response, expected 'token' or 'Error' key 

### ISSUE THREAD

**Issue by YashSherla** [firebase/firebase-ios-sdk#13969]
### Description

I am getting this error in flutter app

### Firebase SDK Version

13.0.2

### Xcode Version

15.2

### Installation Method

N/A

### Firebase Product(s)

Messaging

### Targeted Platforms

iOS

### Relevant Log Output

```shell
FLTFirebaseMessaging: An error occurred while calling method Messaging#getToken, errorOrNil => {
    NSLocalizedFailureReason = "Invalid fetch response, expected 'token' or 'Error' key";
}
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for reporting, @YashSherla. Your issue seems related to #10679. Have you tried updating your SDK and see if the issue persists?

**Comment by Manuito83** [comment]
@rizafran I just started getting this also in Flutter when using getToken(). It was certainly not happening before.

**Comment by hdbookie** [comment]
I got it too, I'm on SDK 11.2.0 still, will try upgrading and report back

**Comment by hotdang-ca** [comment]
We have this also, in Flutter; the iOS SDK version is 11.4.0 (released this morning?). 11.3.0 did work for some of our developers, if clearing the iOS Simulator profile, however, this is still a problem for me (running on a fresh iOS Simulator).

**Comment by paulb777** [comment]
Since the report all seem to be Flutter related and nothing has changed on the core iOS SDK recently, this very likely could be a flutter specific issue and may be better handled at https://github.com/firebase/flutterfire/issues

**Comment by itsabu** [comment]
having the same issue. codebase didn't change but now receiving this error running on ios simulator

**Comment by toanleviet95** [comment]
I had the same issue in `@react-native-firebase/messaging` anyone can help ?

Error: [messaging/unknown] Invalid fetch response, expected 'token' or 'Error' key

**Comment by doing-dfe** [comment]
same @itsabu 
tried to update/downgrade dependencies but still the same problem...
anyone found the solution ?

**Comment by hdbookie** [comment]
So it works fine when testing on a physical device, it's just the emulator that's getting that error for me.

**Comment by iluvdadong** [comment]
I am experiencing the same issue. After successfully installing firebase_messaging versions ^15.1.3 and ^15.0.1, calling `getToken` on` iOS results in the error: flutter: Failed to get FCM token: [firebase_messaging/unknown] An unknown error` has occurred. Both versions are not working.
```

[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-arm64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.94.2)
[✓] Connected device (5 available)
    ! Error: Browsing on the local area network for Dahye의 iPhone. 
      Ensure the device is unlocked and attached with a cable or 
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect 
      wirelessly. (code -27)
[✓] Network resources
```

**Comment by paulb777** [comment]
Based on https://github.com/firebase/flutterfire/issues/13558#issuecomment-2447261489, this seems to be a flutterfire specific issue.

**Comment by oussamamth1** [comment]
this error FLTFirebaseMessaging: An error occurred while calling method Messaging#getToken, errorOrNil => {
    NSLocalizedFailureReason = "Invalid fetch response, expected 'token' or 'Error' key";
}
 is from the firebase package use those   firebase_core: 2.11.0

  firebase_messaging: 14.2.5

**Comment by oussamamth1** [comment]
Hi ,this issue its realated to firebase messages in your pub .yml

**Comment by oussamamth1** [comment]
+21620640783 Whatsapp me
