### ISSUE TITLE
Generated types are not Sendable

### ISSUE THREAD

**Issue by SergioB-dev** [firebase/firebase-ios-sdk#13962]
**Expected**

To be able to run the generated SDK as is (even in my Swift 6 project that has the strictest concurrency checks enabled)

**Actual**

Newly generated types produce this error:
```swift
Non-sendable type 'OperationResult<Last10storyPrimersByCategoryQuery.Data>' returned by implicitly asynchronous
 call to nonisolated function cannot cross actor boundary
```

**Question**
Are there any plans concerning this? My workaround has just been annotating generated types with MainActor to get a prototype up and running. I'd be happy to take this on.

**Comment by aashishpatil-g** [comment]
We are investigating a fix. In the meantime, you could use the `@preconcurrency` annotation before the Data Connect import

```
@preconcurrency import FirebaseDataConnect
@preconcurrency import MyGeneratedConnector
```

**Comment by aashishpatil-g** [comment]
Quick update: 
Some of the changes to code generation were released in https://github.com/firebase/firebase-tools/releases/tag/v13.23.1  (Data Connect local toolkit 1.6.0)

Other changes to the base (core) SDK for Data Connect will go out next week but you might be able to try out the codegen today.
