### ISSUE TITLE
The execution time of +[APMAEU isFAS] suddenly increased significantly

### ISSUE THREAD

**Issue by sunhr** [firebase/firebase-ios-sdk#13963]
### Description

Our app's startup time significantly increased starting around 0:00 UTC on October 17th. Using the Launches Report feature in Xcode 16, we found that the execution time of `+[APMAEU isFAS]` began to spike during the same period. Due to the app release, the subsequent data after Oct 17th can be ignored. 

However, we noticed that the execution time decreased back to its original level starting on Oct 22nd. Do you know what caused this increase in execution time?
![Xnip2024-10-24_13-27-52](https://github.com/user-attachments/assets/1a90e875-e419-41e7-8737-1347e280f843)

### Firebase SDK Version

10.29.0

### Xcode Version

15.2

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, Crashlytics, Performance

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

  - Firebase/Analytics (= 10.29.0)
  - Firebase/Core (= 10.29.0)
  - Firebase/Crashlytics (= 10.29.0)
  - Firebase/Performance (= 10.29.0)
  - FirebaseAnalyticsOnDeviceConversion (= 10.29.0)

```

</details>

**Comment by rizafran** [comment]
Apologies for the late revert, @sunhr. Per checking the [status dashboard](https://ads.google.com/status/publisher/summary), I can't seem to find any issues related to Analytics during that time. What I only noticed is the [SDK update](https://firebase.google.com/support/release-notes/ios#analytics) last October that includes internal code cleanup and optimizations.

I'll now be closing this ticket. If you encounter the issue again, feel free to comment here or create a new one. Thanks.
