### ISSUE TITLE
Can't set app group id in FirebaseOptions

### ISSUE THREAD

**Issue by b95505017** [firebase/firebase-ios-sdk#13972]
### Description

We want to use same fid with Widget and main app, but  crash while setting app group id with FirebaseOptions.

### Firebase SDK Version

11.4.0

### Xcode Version

16.0

### Installation Method

Swift Package Manager

### Firebase Product(s)

Installations

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by b95505017** [comment]
@rizafran  ![截圖 2024-10-25 14 01 04](https://github.com/user-attachments/assets/36060a3a-6a01-44c2-a861-4c089114ca71)

**Comment by rizafran** [comment]
Hi @b95505017, per checking, it seems that the error code -34018 means that the entitlement is missing in your app. With this, have you tried enabling the [Keychain Sharing](https://developer.apple.com/documentation/bundleresources/entitlements/keychain-access-groups) capability in your Xcode? You may also check this [doc](https://developer.apple.com/documentation/security/sharing-access-to-keychain-items-among-a-collection-of-apps) for more info.
