### ISSUE TITLE
5.2.0 - [Firebase/Messaging][I-FCM002024] Format '/topics/news' is deprecated. Only '/topics/news' should be used in subscribeToTopic.

### ISSUE THREAD

**Issue by zapjonny** [firebase/firebase-ios-sdk#1397]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.4
  * Firebase SDK version: 5.2.0
  * Firebase Component: Messaging
  * Component version: Not sure... if needed... ask again

### [REQUIRED] Step 3: Describe the problem

Getting this in the logs:

> 5.2.0 - [Firebase/Messaging][I-FCM002024] Format '/topics/news' is deprecated. Only '/topics/news' should be used in subscribeToTopic.

This error message is confusing. I did exactly what it suggested, but it says that exact same way is deprecated. Is the error message incorrect?

#### Steps to reproduce:

    Messaging.messaging().subscribe(toTopic: "/topics/news")

#### Relevant Code:

```
    Messaging.messaging().subscribe(toTopic: "/topics/news")
```

**Comment by zapjonny** [comment]
Note: 

Unsubscribing the same way gives a similarly confusing error message:

    Messaging.messaging().unsubscribe(fromTopic: "/topics/news")

> 5.2.0 - [Firebase/Messaging][I-FCM002024] Format '/topics/news' is deprecated. Only '/topics/news' should be used in unsubscribeFromTopic.

**Comment by paulb777** [comment]
Looks like a problem with #1312. cc: @alexames @morganchen12

**Comment by zapjonny** [comment]
Btw if I change to `Messaging.messaging().unsubscribe(fromTopic: "news")` which seems to be the correct way since updating to 5.2.0 (no actual build time heads up notice of that unfortunately), the warning goes away. So the error message just seems to be incorrect.

**Comment by chliangGoogle** [comment]
Yeah the right format should be "news" instead of "/topic/news" and the warning is trying to warn you that. But we print the warning wrong which confuses people. We will send out a PR soon for the fix.
