### ISSUE TITLE
Failure to fetch token fails to report server error

### ISSUE THREAD

**Issue by richardcrichardc** [firebase/firebase-ios-sdk#13997]
### Description

Failure to fetch token fails to report server error. 

I.e. error message 'Invalid fetch response, expected 'token' or 'Error' key' is shown, instead of the error after the 'Error' key returned by the FCM service.

### Reproducing the issue

This issue is evident for some or all of the problems indicated by this issue in the Flutter Firebase library: https://github.com/firebase/flutterfire/issues/13558

The error can be found by inspecting the code here:

https://github.com/firebase/firebase-ios-sdk/blob/00674c85bd73f88d9e10e10fb541a29a5ffa7cf4/FirebaseMessaging/Sources/Token/FIRMessagingTokenFetchOperation.m#L148

The error key is parsed into errorValue on out on line 146. Lines 148-176 do not assign the error to responseError in all cases, including when errorValue is the string 'TOO_MANY_REGISTRATIONS'. Lines 177-183 then report the key 'Error' was not set.

### Firebase SDK Version

latest

### Xcode Version

n/a

### Installation Method

CocoaPods

### Firebase Product(s)

Messaging

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
Looks like it may be related to #13969

**Comment by leojaygoogle** [comment]
Thanks for the report! I agree that the error message can be improved to make it easier to debug fetch token failures. I will send out a PR to fix that.
