### ISSUE TITLE
Implicit FirebasePerformanceTarget dependency

### ISSUE THREAD

**Issue by rofle100lvl** [firebase/firebase-ios-sdk#13998]
### Description

Hello, Firebase team. Recently, I've been working extensively on identifying and eliminating implicit dependencies. I discovered one such dependency in your repository. In the SPM manifest, the [FirebasePerformance library](https://github.com/firebase/firebase-ios-sdk/blob/45a5a4da09cee94e4a1c3d5a0da2344ba50cbad9/Package.swift#L113) includes a target named FirebasePerformanceTarget, which lists FirebasePerformance as a dependency. Upon review, it appears that no one is directly using FirebasePerformanceTarget; instead, all users simply import FirebasePerformance. I recommend removing FirebasePerformanceTarget. Perhaps I missed something; if so, I would appreciate it if you could clarify.

### Firebase SDK Version

10.9

### Xcode Version

15.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Performance

### Targeted Platforms

iOS, macOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
"FirebasePerformance" is a Swift Package Manager `library` and "FirebasePerformanceTarget" is the Swift Package manager `target` that provides the implementation for "FirebasePerformance"
