### ISSUE TITLE
[auth] anonymous auth missing 'firebase' providerData

### ISSUE THREAD

**Issue by Salakar** [firebase/firebase-ios-sdk#140]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: Any
  * Firebase SDK version: 4.0.2
  * Library version: Any
  * Firebase Product: auth (auth, database, storage, core, messaging, etc)

### [REQUIRED] Step 3: Describe the problem

`FIRUser.providerData` array is empty when signed in anonymously, however the android sdk returns 1 array item when signed in anonymously with the following properties in the map/dictionary:

![image](https://user-images.githubusercontent.com/5347038/28282747-72db4e8c-6b23-11e7-9136-1ea30d5c79a3.png)

#### Steps to reproduce:
Sign in anonymously. See code below.

#### Relevant Code:

```objective-c
FIRApp *firApp = [FIRApp appNamed:@"foobar"];

[[FIRAuth authWithApp:firApp] signInAnonymouslyWithCompletion:^(FIRUser *user, NSError *error) {
  // user.providerData array is empty
}];
```

Have found this issue whilst working on the react native firebase implementation, library specific code is as follows:
 - [Android](https://github.com/invertase/react-native-firebase/blob/multi-apps/android/src/main/java/io/invertase/firebase/auth/RNFirebaseAuth.java#L1014)
- [iOS](https://github.com/invertase/react-native-firebase/blob/multi-apps/ios/RNFirebase/auth/RNFirebaseAuth.m#L936)

**Comment by XiangtianDai** [comment]
@Salakar I'm sorry that Firebase Auth's implementations for the list of providers are inconsistent between platforms. On both iOS and Web this implied "firebase" provider (which is represented as the user object itself) is omitted from the array, while on Android it is listed as an explicit provider in the array. At this moment I don't see how we can change any of the implementations without breaking existing developer code that may have already depended on them, so my suggestion is:

-  If you are on Android and want iOS behavior, filter out the "firebase" provider from the result array returned by`getProviderData()` method.
- If you are on iOS and want Android behavior, add the `FIRUser` instance itself to the beginning of the result array returned by `providerData` property getter.

**Comment by Salakar** [comment]
@XiangtianDai ok, makes sense, will work around it to match the ios & web implementations I guess,

Another couple inconsistency queries if I may:
 - `FIROptions` vs `FirebaseOptions`:
    - On the iOS implementation (FIROptions) it's possible to get and set the `clientId`.
    - On the android implementation (FirebaseOptions) there's **no** way to get the `clientId` on an initialised app, and, there's also no way to set the `clientId` via `FirebaseOptions.Builder`.
 - `FIRApp` vs `FirebaseApp`:
    - On the iOS implementation (FIRApp) it's possible to delete an initialised app via `deleteApp`.
    - On the android implementation (FirebaseApp) there's **no** way, or at least a documented way of deleting an initialised app.

I have quite a few other inconsistency issues between ios & android that have been piling up and am unsure where to address these? Right now though the ones above are my main concern - could you perhaps advise on solutions / workarounds?

Currently these are holding back the multi app implementation for [`react-native-firebase`](https://github.com/invertase/react-native-firebase/tree/multi-apps), for example the tests fail on android as there's no way to delete an app.

**Comment by XiangtianDai** [comment]
@davidair for FirebaseCore

**Comment by Salakar** [comment]
@XiangtianDai @davidair any updates on my previous comments?

**Comment by morganchen12** [comment]
@Salakar there's no workarounds for the two things you mentioned. It's likely that we can change Android to suit iOS behavior as a non-breaking change, since it just involves adding API stuff.

This is tracked internally at b/67354438, and isn't likely to be a priority for the time being.

**Comment by ryanwilson** [comment]
@protocol86 - can you address whether or not the Android solution or iOS solution is the correct one here? If iOS is correct, we should close this bug and address it internally on the Android side since there's no actionable items for this repo.

**Comment by protocol86** [comment]
The iOS library exhibits the expected functionality. A bug has been filed against the Android SDK, who will release it as soon as is feasible (though they are somewhat limited due to this being a breaking change).
