### ISSUE TITLE
Crash from AuthBackend.swift file.

### ISSUE THREAD

**Issue by ElrB** [firebase/firebase-ios-sdk#14005]
### Description

Please see crashlytics report below. It has been happening quite a few times. 
Using Firebase version 11.2.0 (swift package)

![Screenshot 2024-10-31 at 8 28 45 PM](https://github.com/user-attachments/assets/4850865b-e65e-4cf5-93ad-a203087881c9)

### Firebase SDK Version

11.2.0

### Xcode Version

15.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication, Crashlytics, Database, Firestore, Messaging

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment]
Hi @ElrB, please update to 11.4.0. The crash was resolved in 11.4.0 ([fix](https://github.com/firebase/firebase-ios-sdk/commit/143c16921c7db4935ccb43e090db69e057e1bd95)). For more details, see discussion in #13761.
