### ISSUE TITLE
Crashed in background

### ISSUE THREAD

**Issue by SMYdamao** [firebase/firebase-ios-sdk#14003]
### Description

when i open in xcode, this is the thread infomation:
![image](https://github.com/user-attachments/assets/9929d54e-9217-4a21-a14f-6c3ef57bc261)

Thread 0 name:
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x00000001e8604728 mach_msg2_trap + 8 (:-1)
1   libsystem_kernel.dylib        	0x00000001e8607e38 mach_msg2_internal + 80 (mach_msg.c:201)
2   libsystem_kernel.dylib        	0x00000001e8607d50 mach_msg_overwrite + 424 (mach_msg.c:0)
3   libsystem_kernel.dylib        	0x00000001e8607b9c mach_msg + 24 (mach_msg.c:323)
4   CoreFoundation                	0x00000001987c17cc __CFRunLoopServiceMachPort + 160 (CFRunLoop.c:2617)
5   CoreFoundation                	0x00000001987c0e78 __CFRunLoopRun + 1212 (CFRunLoop.c:3001)
6   CoreFoundation                	0x00000001987c05b8 CFRunLoopRunSpecific + 572 (CFRunLoop.c:3414)
7   GraphicsServices              	0x00000001e42561c4 GSEventRunModal + 164 (GSEvent.c:2196)
8   UIKitCore                     	0x000000019b3165f0 -[UIApplication _run] + 816 (UIApplication.m:3820)
9   UIKitCore                     	0x000000019b3c510c UIApplicationMain + 340 (UIApplication.m:5472)
10                        	0x00000001041b6c20 main + 96 (main.mm:17)
11  dyld                          	0x00000001bdf93d34 start + 2724 (dyldMain.cpp:1334)

### Firebase SDK Version

11.2.0

### Xcode Version

15.4

### Installation Method

CocoaPods

### Firebase Product(s)

Remote Config

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment]
Hi @SMYdamao, do you also have the full stack trace to share? It could be helpful in determining what the other threads are doing at the time of the crash.
