### ISSUE TITLE
Crashes in FPRScreenTraceTracker 

### ISSUE THREAD

**Issue by johnqh** [firebase/firebase-ios-sdk#1402]
* Xcode version: 9.3.1
  * Firebase SDK version: 5.1.0
  * Firebase Component: Core, Analytics, Performance
  * Component version: 
- Firebase/Core (5.1.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 5.0.1)
  - Firebase/CoreOnly (5.1.0):
    - FirebaseCore (= 5.0.2)
  - Firebase/Performance (5.1.0):
    - Firebase/Core
    - FirebasePerformance (= 2.0.0)
  - FirebaseAnalytics (5.0.1):
    - FirebaseCore (~> 5.0)
    - FirebaseInstanceID (~> 3.0)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - nanopb (~> 0.3)
  - FirebaseCore (5.0.2):
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"

We have some Firebase crashes tracked in Crashlytics:
-[FPRScreenTraceTracker stopScreenTraceForViewController:currentTotalFrames:currentFrozenFrames:currentSlowFrames:]

Stack:

#0Crashed: com.google.FPRScreenTraceTrackerEXC_BREAKPOINT 0x000000000000defe Raw Text
--
0 | CoreFoundation | _CFRelease + 1369
1 | CoreFoundation | -[__NSDictionaryI dealloc] + 112
2 | CoreFoundation | -[__NSDictionaryI dealloc] + 112
3 | libobjc.A.dylib | objc_object::sidetable_release(bool) + 238
4 | Indeed Jobs | -[FPRScreenTraceTracker stopScreenTraceForViewController:currentTotalFrames:currentFrozenFrames:currentSlowFrames:] + 3072815
5 | Indeed Jobs | __52-[FPRScreenTraceTracker viewControllerDidDisappear:]_block_invoke + 3074073
6 | libdispatch.dylib | _dispatch_call_block_and_release + 10
7 | libdispatch.dylib | _dispatch_queue_serial_drain + 242
8 | libdispatch.dylib | _dispatch_queue_invoke + 886
9 | libdispatch.dylib | _dispatch_queue_override_invoke + 282
10 | libdispatch.dylib | _dispatch_root_queue_drain + 326
11 | libdispatch.dylib | _dispatch_worker_thread3 + 106
12 | libsystem_pthread.dylib | _pthread_wqthread + 1040
13 | libsystem_pthread.dylib | start_wqthread + 8

Some in -[FPRCounterList counters]. I think they are related:

#0Crashed: com.google.FPRScreenTraceTrackerEXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000000524c561e Raw Text
--
0 | libobjc.A.dylib | objc_msgSend + 21
1 | CoreFoundation | +[__NSDictionaryI __new:::::] + 460
2 | CoreFoundation | -[__NSDictionaryM copyWithZone:] + 256
3 | Indeed Jobs | -[FPRCounterList counters] + 2968133
4 | Indeed Jobs | -[FIRTrace counters] + 2964677
5 | Indeed Jobs | -[FPRScreenTraceTracker stopScreenTraceForViewController:currentTotalFrames:currentFrozenFrames:currentSlowFrames:] + 2880269
6 | Indeed Jobs | __52-[FPRScreenTraceTracker viewControllerDidDisappear:]_block_invoke + 2881561
7 | libdispatch.dylib | _dispatch_call_block_and_release + 10
8 | libdispatch.dylib | _dispatch_queue_serial_drain + 242
9 | libdispatch.dylib | _dispatch_queue_invoke + 886
10 | libdispatch.dylib | _dispatch_queue_override_invoke + 282
11 | libdispatch.dylib | _dispatch_root_queue_drain + 326
12 | libdispatch.dylib | _dispatch_worker_thread3 + 106
13 | libsystem_pthread.dylib | _pthread_wqthread + 1040
14 | libsystem_pthread.dylib | start_wqthread + 8

We have not seen it in our own testing, only saw the Crashlytics reports. They happen with iOS 9 and 10 only, with all device types (iPhone, iPod Touch and iPad)

**Comment by johnqh** [comment]
btw, this happened with Firebase 5.0 too, but didn't happen with 4.X. 4.X has its own different random crashes in iOS9 only but those crashes are gone. 95% of the crashes in 5.0 are one of those two

**Comment by eshiehz** [comment]
We're aware of the issue and a fix will be available in the next release. Thanks for filing!

**Comment by johnqh** [comment]
I see 5.3.0 in releases 7 days ago, but cocoa pod still only installs 5.1.0.

**Comment by paulb777** [comment]
@johnqh The [5.3.0 milestone](https://github.com/firebase/firebase-ios-sdk/milestone/7) still being open indicates we are still stabilizing and haven't published yet. It should be soon.

5.2.0 is available now though. Possibly you need to add the `--repo-update` option to the `pod install` command.

**Comment by zeqinjie** [comment]
This bug is present also in 5.2.0

**Comment by alihen** [comment]
@zeqinjie, this should have been resolved in 5.3.0 - please update your pod if possible 👍

**Comment by zeqinjie** [comment]
ok, thx

**Comment by zeqinjie** [comment]
but when i update to 5.4.0 or 5.3.0.it must crash in iOS8.[iussue](https://github.com/firebase/firebase-ios-sdk/issues/1540)

**Comment by glennposadas** [comment]
April 2019, happened to me. 

`-FPRScreenTraceTracker startScreenTraceForViewController:currentTotalFrames:currentFrozenFrames:currentSlowFrames:]`
