### ISSUE TITLE
Expose Swift classes  of Data Connect to Objective c by annotating them with @objc

### ISSUE THREAD

**Issue by fethij** [firebase/firebase-ios-sdk#14020]
### Description

We are unable to use the swift classes of Data Connect in an objective c, because they are not annotated with @objc

### Firebase Product(s)

Database

**Comment by aashishpatil-g** [comment]
Thank you for the feature request. 

At this point we don't have plans to add Obj C support to Data Connect given the direction of iOS development. We will consider revisiting the issue if we see sufficient feedback and interest from the community.
