### ISSUE TITLE
ServerTimestamp<T> could be sendable if T is Sendable

### ISSUE THREAD

**Issue by jesus-mg-ios** [firebase/firebase-ios-sdk#14042]
### Description

ServerTimestamp is not sendable, while T generic parameter like Date could be sendable.

### Firebase SDK Version

11.2.0

### Xcode Version

16.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

### Relevant Log Output

```shell
.
```

**Comment by milaGGL** [comment]
Hi @jesus-mg-ios, thank you for raising this issue. Could you please provide more details on it?

**Comment by jesus-mg-ios** [comment]
Sure,  imagine that you got a variable  `var serverTimestamp: ServerTimestamp<Date>` to decode a response using Firestore, then ServerTimestamp is marked as Non Sendable ...

So it would be nice, that if Date, (that it is ) is sendable, then ServerTimestamp could be Sendable

Something like this `extension ServerTimestamp: Sendable where T: Sendable {}` Because in this case ServerTimestamp can be Sendable if T it is

**Comment by paulb777** [comment]
Reopening since we are investigating better Swift Concurrency support across Firebase and we can consider this request in that effort.

**Comment by ncooke3** [comment]
@jesus-mg-ios, thanks again for the report! This will go out in the next release. I'll be continuing to improve the Swift 6 experience in future releases (e.g. https://github.com/firebase/firebase-ios-sdk/pull/14163, etc.).
