### ISSUE TITLE
FCM Topic push: messages are lost, and some users do not receive them.

### ISSUE THREAD

**Issue by wang1925** [firebase/firebase-ios-sdk#14055]
### Description

When using FCM Topic messaging, some users receive notifications while others do not. However, those who do not receive notifications via Topic can still receive them through individual fcmToken push notifications.

### Firebase SDK Version

11.4.0

### Xcode Version

15.4

### Installation Method

CocoaPods

### Firebase Product(s)

Messaging

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

PODS:
  - AAInfographics (9.1.0)
  - Alamofire (5.10.1)
  - AppAuth (1.7.5):
    - AppAuth/Core (= 1.7.5)
    - AppAuth/ExternalUserAgent (= 1.7.5)
  - AppAuth/Core (1.7.5)
  - AppAuth/ExternalUserAgent (1.7.5):
    - AppAuth/Core
  - AppCheckCore (11.2.0):
    - GoogleUtilities/Environment (~> 8.0)
    - GoogleUtilities/UserDefaults (~> 8.0)
    - PromisesObjC (~> 2.4)
  - Apple-Cocoapod-KochavaCore (7.6.0)
  - Apple-Cocoapod-KochavaTracker (7.6.0):
    - Apple-Cocoapod-KochavaCore (~> 7.6.0)
  - AppLovinMediationFacebookAdapter (6.15.2.1):
    - AppLovinSDK (>= 13.0.0)
    - FBAudienceNetwork (= 6.15.2)
  - AppLovinMediationFyberAdapter (8.3.2.1):
    - AppLovinSDK (>= 13.0.0)
    - Fyber_Marketplace_SDK (= 8.3.2)
  - AppLovinMediationGoogleAdapter (11.11.0.0):
    - AppLovinSDK (>= 13.0.0)
    - Google-Mobile-Ads-SDK (= 11.11.0)
  - AppLovinMediationInMobiAdapter (10.7.8.0):
    - AppLovinSDK (>= 13.0.0)
    - InMobiSDK (= 10.7.8)
  - AppLovinMediationIronSourceAdapter (8.4.0.0.0):
    - AppLovinSDK (>= 13.0.0)
    - IronSourceSDK (= 8.4.0.0)
  - AppLovinMediationMintegralAdapter (7.7.3.0.0):
    - AppLovinSDK (>= 13.0.0)
    - MintegralAdSDK (= 7.7.3)
    - MintegralAdSDK/BidSplashAd (= 7.7.3)
  - AppLovinMediationSmaatoAdapter (22.9.1.0):
    - AppLovinSDK (>= 13.0.0)
    - smaato-ios-sdk (= 22.9.1)
    - smaato-ios-sdk/InApp (= 22.9.1)
  - AppLovinMediationUnityAdsAdapter (4.12.4.0):
    - AppLovinSDK (>= 13.0.0)
    - UnityAds (= 4.12.4)
  - AppLovinMediationVerveAdapter (3.1.2.0):
    - AppLovinSDK (>= 13.0.0)
    - HyBid (= 3.1.2)
  - AppLovinMediationVungleAdapter (7.4.2.1):
    - AppLovinSDK (>= 13.0.0)
    - VungleAds (= 7.4.2)
  - AppLovinSDK (13.0.1)
  - ATOM-Standalone (3.3.2)
  - DatePickerDialog (4.0)
  - FBAEMKit (17.0.3):
    - FBSDKCoreKit_Basics (= 17.0.3)
  - FBAudienceNetwork (6.15.2)
  - FBSDKCoreKit (17.0.3):
    - FBAEMKit (= 17.0.3)
    - FBSDKCoreKit_Basics (= 17.0.3)
  - FBSDKCoreKit_Basics (17.0.3)
  - FBSDKLoginKit (17.0.3):
    - FBSDKCoreKit (= 17.0.3)
  - FirebaseAnalytics (11.4.0):
    - FirebaseAnalytics/AdIdSupport (= 11.4.0)
    - FirebaseCore (~> 11.0)
    - FirebaseInstallations (~> 11.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 8.0)
    - GoogleUtilities/MethodSwizzler (~> 8.0)
    - GoogleUtilities/Network (~> 8.0)
    - "GoogleUtilities/NSData+zlib (~> 8.0)"
    - nanopb (~> 3.30910.0)
  - FirebaseAnalytics/AdIdSupport (11.4.0):
    - FirebaseCore (~> 11.0)
    - FirebaseInstallations (~> 11.0)
    - GoogleAppMeasurement (= 11.4.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 8.0)
    - GoogleUtilities/MethodSwizzler (~> 8.0)
    - GoogleUtilities/Network (~> 8.0)
    - "GoogleUtilities/NSData+zlib (~> 8.0)"
    - nanopb (~> 3.30910.0)
  - FirebaseCore (11.4.2):
    - FirebaseCoreInternal (< 12.0, >= 11.4.2)
    - GoogleUtilities/Environment (~> 8.0)
    - GoogleUtilities/Logger (~> 8.0)
  - FirebaseCoreExtension (11.4.1):
    - FirebaseCore (~> 11.0)
  - FirebaseCoreInternal (11.4.2):
    - "GoogleUtilities/NSData+zlib (~> 8.0)"
  - FirebaseCrashlytics (11.4.0):
    - FirebaseCore (~> 11.4)
    - FirebaseInstallations (~> 11.0)
    - FirebaseRemoteConfigInterop (~> 11.0)
    - FirebaseSessions (~> 11.0)
    - GoogleDataTransport (~> 10.0)
    - GoogleUtilities/Environment (~> 8.0)
    - nanopb (~> 3.30910.0)
    - PromisesObjC (~> 2.4)
  - FirebaseInstallations (11.4.0):
    - FirebaseCore (~> 11.0)
    - GoogleUtilities/Environment (~> 8.0)
    - GoogleUtilities/UserDefaults (~> 8.0)
    - PromisesObjC (~> 2.4)
  - FirebaseMessaging (11.4.0):
    - FirebaseCore (~> 11.0)
    - FirebaseInstallations (~> 11.0)
    - GoogleDataTransport (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 8.0)
    - GoogleUtilities/Environment (~> 8.0)
    - GoogleUtilities/Reachability (~> 8.0)
    - GoogleUtilities/UserDefaults (~> 8.0)
    - nanopb (~> 3.30910.0)
  - FirebaseRemoteConfigInterop (11.4.0)
  - FirebaseSessions (11.4.0):
    - FirebaseCore (~> 11.4)
    - FirebaseCoreExtension (~> 11.4)
    - FirebaseInstallations (~> 11.0)
    - GoogleDataTransport (~> 10.0)
    - GoogleUtilities/Environment (~> 8.0)
    - GoogleUtilities/UserDefaults (~> 8.0)
    - nanopb (~> 3.30910.0)
    - PromisesSwift (~> 2.1)
  - Fyber_Marketplace_SDK (8.3.2)
  - Google-Mobile-Ads-SDK (11.11.0):
    - GoogleUserMessagingPlatform (>= 1.1)
  - GoogleAppMeasurement (11.4.0):
    - GoogleAppMeasurement/AdIdSupport (= 11.4.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 8.0)
    - GoogleUtilities/MethodSwizzler (~> 8.0)
    - GoogleUtilities/Network (~> 8.0)
    - "GoogleUtilities/NSData+zlib (~> 8.0)"
    - nanopb (~> 3.30910.0)
  - GoogleAppMeasurement/AdIdSupport (11.4.0):
    - GoogleAppMeasurement/WithoutAdIdSupport (= 11.4.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 8.0)
    - GoogleUtilities/MethodSwizzler (~> 8.0)
    - GoogleUtilities/Network (~> 8.0)
    - "GoogleUtilities/NSData+zlib (~> 8.0)"
    - nanopb (~> 3.30910.0)
  - GoogleAppMeasurement/WithoutAdIdSupport (11.4.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 8.0)
    - GoogleUtilities/MethodSwizzler (~> 8.0)
    - GoogleUtilities/Network (~> 8.0)
    - "GoogleUtilities/NSData+zlib (~> 8.0)"
    - nanopb (~> 3.30910.0)
  - GoogleDataTransport (10.1.0):
    - nanopb (~> 3.30910.0)
    - PromisesObjC (~> 2.4)
  - GoogleSignIn (8.0.0):
    - AppAuth (< 2.0, >= 1.7.3)
    - AppCheckCore (~> 11.0)
    - GTMAppAuth (< 5.0, >= 4.1.1)
    - GTMSessionFetcher/Core (~> 3.3)
  - GoogleUserMessagingPlatform (2.7.0)
  - GoogleUtilities/AppDelegateSwizzler (8.0.2):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
    - GoogleUtilities/Privacy
  - GoogleUtilities/Environment (8.0.2):
    - GoogleUtilities/Privacy
  - GoogleUtilities/Logger (8.0.2):
    - GoogleUtilities/Environment
    - GoogleUtilities/Privacy
  - GoogleUtilities/MethodSwizzler (8.0.2):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/Network (8.0.2):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Privacy
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (8.0.2)":
    - GoogleUtilities/Privacy
  - GoogleUtilities/Privacy (8.0.2)
  - GoogleUtilities/Reachability (8.0.2):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/UserDefaults (8.0.2):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GTMAppAuth (4.1.1):
    - AppAuth/Core (~> 1.7)
    - GTMSessionFetcher/Core (< 4.0, >= 3.3)
  - GTMSessionFetcher/Core (3.5.0)
  - HandyJSON (5.0.2)
  - HyBid (3.1.2):
    - HyBid/ATOM (= 3.1.2)
    - HyBid/Banner (= 3.1.2)
    - HyBid/Core (= 3.1.2)
    - HyBid/FullScreen (= 3.1.2)
    - HyBid/Native (= 3.1.2)
    - HyBid/RewardedVideo (= 3.1.2)
  - HyBid/ATOM (3.1.2):
    - ATOM-Standalone (~> 3.3.0)
    - HyBid/Core
  - HyBid/Banner (3.1.2):
    - HyBid/Core
  - HyBid/Core (3.1.2)
  - HyBid/FullScreen (3.1.2):
    - HyBid/Core
  - HyBid/Native (3.1.2):
    - HyBid/Core
  - HyBid/RewardedVideo (3.1.2):
    - HyBid/Core
  - InMobiSDK (10.7.8)
  - IronSourceSDK (8.4.0.0)
  - Kingfisher (7.12.0)
  - MintegralAdSDK (7.7.3):
    - MintegralAdSDK/BannerAd (= 7.7.3)
    - MintegralAdSDK/BidBannerAd (= 7.7.3)
    - MintegralAdSDK/BidInterstitialVideoAd (= 7.7.3)
    - MintegralAdSDK/BidNativeAd (= 7.7.3)
    - MintegralAdSDK/BidNewInterstitialAd (= 7.7.3)
    - MintegralAdSDK/BidRewardVideoAd (= 7.7.3)
    - MintegralAdSDK/InterstitialVideoAd (= 7.7.3)
    - MintegralAdSDK/NativeAd (= 7.7.3)
    - MintegralAdSDK/NewInterstitialAd (= 7.7.3)
    - MintegralAdSDK/RewardVideoAd (= 7.7.3)
  - MintegralAdSDK/BannerAd (7.7.3):
    - MintegralAdSDK/NativeAd
  - MintegralAdSDK/BidBannerAd (7.7.3):
    - MintegralAdSDK/BannerAd
    - MintegralAdSDK/BidNativeAd
  - MintegralAdSDK/BidInterstitialVideoAd (7.7.3):
    - MintegralAdSDK/BidNativeAd
    - MintegralAdSDK/InterstitialVideoAd
  - MintegralAdSDK/BidNativeAd (7.7.3):
    - MintegralAdSDK/NativeAd
  - MintegralAdSDK/BidNewInterstitialAd (7.7.3):
    - MintegralAdSDK/BidNativeAd
    - MintegralAdSDK/NewInterstitialAd
  - MintegralAdSDK/BidRewardVideoAd (7.7.3):
    - MintegralAdSDK/BidNativeAd
    - MintegralAdSDK/RewardVideoAd
  - MintegralAdSDK/BidSplashAd (7.7.3):
    - MintegralAdSDK/BidNativeAd
    - MintegralAdSDK/SplashAd
  - MintegralAdSDK/InterstitialVideoAd (7.7.3):
    - MintegralAdSDK/NativeAd
  - MintegralAdSDK/NativeAd (7.7.3)
  - MintegralAdSDK/NewInterstitialAd (7.7.3):
    - MintegralAdSDK/InterstitialVideoAd
    - MintegralAdSDK/NativeAd
  - MintegralAdSDK/RewardVideoAd (7.7.3):
    - MintegralAdSDK/NativeAd
  - MintegralAdSDK/SplashAd (7.7.3):
    - MintegralAdSDK/NativeAd
  - nanopb (3.30910.0):
    - nanopb/decode (= 3.30910.0)
    - nanopb/encode (= 3.30910.0)
  - nanopb/decode (3.30910.0)
  - nanopb/encode (3.30910.0)
  - PromisesObjC (2.4.0)
  - PromisesSwift (2.4.0):
    - PromisesObjC (= 2.4.0)
  - RSKPlaceholderTextView (8.0.0)
  - SDWebImage (5.20.0):
    - SDWebImage/Core (= 5.20.0)
  - SDWebImage/Core (5.20.0)
  - smaato-ios-sdk (22.9.1):
    - smaato-ios-sdk/Full (= 22.9.1)
  - smaato-ios-sdk/Banner (22.9.1):
    - smaato-ios-sdk/Modules/Banner
    - smaato-ios-sdk/Modules/Core
    - smaato-ios-sdk/Modules/RichMedia
  - smaato-ios-sdk/Full (22.9.1):
    - smaato-ios-sdk/Banner
    - smaato-ios-sdk/Interstitial
    - smaato-ios-sdk/Native
    - smaato-ios-sdk/Outstream
    - smaato-ios-sdk/RewardedAds
  - smaato-ios-sdk/InApp (22.9.1):
    - smaato-ios-sdk/Modules/Core
  - smaato-ios-sdk/Interstitial (22.9.1):
    - smaato-ios-sdk/Modules/Interstitial
    - smaato-ios-sdk/Modules/RichMedia
    - smaato-ios-sdk/Modules/Video
  - smaato-ios-sdk/Modules/Banner (22.9.1):
    - smaato-ios-sdk/Modules/Core
  - smaato-ios-sdk/Modules/Core (22.9.1)
  - smaato-ios-sdk/Modules/Interstitial (22.9.1):
    - smaato-ios-sdk/Modules/Core
  - smaato-ios-sdk/Modules/Native (22.9.1):
    - smaato-ios-sdk/Modules/Core
  - smaato-ios-sdk/Modules/OpenMeasurement (22.9.1):
    - smaato-ios-sdk/Modules/Core
  - smaato-ios-sdk/Modules/Outstream (22.9.1):
    - smaato-ios-sdk/Modules/Banner
    - smaato-ios-sdk/Modules/Core
    - smaato-ios-sdk/Modules/RichMedia
  - smaato-ios-sdk/Modules/RewardedAds (22.9.1):
    - smaato-ios-sdk/Modules/Core
  - smaato-ios-sdk/Modules/RichMedia (22.9.1):
    - smaato-ios-sdk/Modules/Core
    - smaato-ios-sdk/Modules/OpenMeasurement
  - smaato-ios-sdk/Modules/Video (22.9.1):
    - smaato-ios-sdk/Modules/Core
    - smaato-ios-sdk/Modules/OpenMeasurement
  - smaato-ios-sdk/Native (22.9.1):
    - smaato-ios-sdk/Modules/Core
    - smaato-ios-sdk/Modules/Native
  - smaato-ios-sdk/Outstream (22.9.1):
    - smaato-ios-sdk/Modules/Outstream
  - smaato-ios-sdk/RewardedAds (22.9.1):
    - smaato-ios-sdk/Modules/RewardedAds
    - smaato-ios-sdk/Modules/Video
  - SnapKit (5.6.0)
  - Then (3.0.0)
  - Toast-Swift (5.1.1)
  - UnityAds (4.12.4)
  - VungleAds (7.4.2)
  - Zip (2.1.2)

DEPENDENCIES:
  - AAInfographics
  - Alamofire
  - Apple-Cocoapod-KochavaTracker
  - AppLovinMediationFacebookAdapter
  - AppLovinMediationFyberAdapter
  - AppLovinMediationGoogleAdapter
  - AppLovinMediationInMobiAdapter
  - AppLovinMediationIronSourceAdapter
  - AppLovinMediationMintegralAdapter
  - AppLovinMediationSmaatoAdapter
  - AppLovinMediationUnityAdsAdapter
  - AppLovinMediationVerveAdapter
  - AppLovinMediationVungleAdapter
  - AppLovinSDK
  - DatePickerDialog
  - FBSDKLoginKit (= 17.0.3)
  - FirebaseAnalytics
  - FirebaseCrashlytics
  - FirebaseMessaging
  - GoogleSignIn
  - HandyJSON
  - Kingfisher (~> 7.0)
  - RSKPlaceholderTextView
  - SDWebImage
  - SnapKit (~> 5.6.0)
  - Then
  - Toast-Swift
  - Zip

SPEC REPOS:
  trunk:
    - AAInfographics
    - Alamofire
    - AppAuth
    - AppCheckCore
    - Apple-Cocoapod-KochavaCore
    - Apple-Cocoapod-KochavaTracker
    - AppLovinMediationFacebookAdapter
    - AppLovinMediationFyberAdapter
    - AppLovinMediationGoogleAdapter
    - AppLovinMediationInMobiAdapter
    - AppLovinMediationIronSourceAdapter
    - AppLovinMediationMintegralAdapter
    - AppLovinMediationSmaatoAdapter
    - AppLovinMediationUnityAdsAdapter
    - AppLovinMediationVerveAdapter
    - AppLovinMediationVungleAdapter
    - AppLovinSDK
    - ATOM-Standalone
    - DatePickerDialog
    - FBAEMKit
    - FBAudienceNetwork
    - FBSDKCoreKit
    - FBSDKCoreKit_Basics
    - FBSDKLoginKit
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreExtension
    - FirebaseCoreInternal
    - FirebaseCrashlytics
    - FirebaseInstallations
    - FirebaseMessaging
    - FirebaseRemoteConfigInterop
    - FirebaseSessions
    - Fyber_Marketplace_SDK
    - Google-Mobile-Ads-SDK
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleSignIn
    - GoogleUserMessagingPlatform
    - GoogleUtilities
    - GTMAppAuth
    - GTMSessionFetcher
    - HandyJSON
    - HyBid
    - InMobiSDK
    - IronSourceSDK
    - Kingfisher
    - MintegralAdSDK
    - nanopb
    - PromisesObjC
    - PromisesSwift
    - RSKPlaceholderTextView
    - SDWebImage
    - smaato-ios-sdk
    - SnapKit
    - Then
    - Toast-Swift
    - UnityAds
    - VungleAds
    - Zip

SPEC CHECKSUMS:
  AAInfographics: a71bedb2ad93526c2cfdca608f11d5c698d716b8
  Alamofire: 840d2a1ad82355b536ec6ba5f97e5bfa54600ca3
  AppAuth: 501c04eda8a8d11f179dbe8637b7a91bb7e5d2fa
  AppCheckCore: cc8fd0a3a230ddd401f326489c99990b013f0c4f
  Apple-Cocoapod-KochavaCore: b28f817d162ff95e913d29c228df7a58a90e1c02
  Apple-Cocoapod-KochavaTracker: f9bf2ec1be118512f747e2350f4355a54994e246
  AppLovinMediationFacebookAdapter: a569c3015e24b5e00049a46bb344ba00894b3541
  AppLovinMediationFyberAdapter: 5fa1488a43fd8359f028a07f4fbf091835eee8ba
  AppLovinMediationGoogleAdapter: a40f301fda2e26efa96ec754d4f85fcaca56de73
  AppLovinMediationInMobiAdapter: e21ac5d93bec66d8b03f5d914190078e66368540
  AppLovinMediationIronSourceAdapter: 780e901f72f69bade8e53a645a9c07bb220a8f01
  AppLovinMediationMintegralAdapter: 97d210078a2de1d2f5c922346010ab844e046271
  AppLovinMediationSmaatoAdapter: 0aa8426ec9114adf9886dd1d3347049afcf4ce3a
  AppLovinMediationUnityAdsAdapter: d3d2c0def05e24d9d00119ced77dc0813cc40f34
  AppLovinMediationVerveAdapter: 02aac86d86d306d7ad16e329faf909ab1045f393
  AppLovinMediationVungleAdapter: c21018a07aeca248d8cca28cf027e6d620a7fe1d
  AppLovinSDK: fdae6a4361c9c9b09f8d7d18ede792368221d987
  ATOM-Standalone: 176675fcd627e44ab1997581b1047e7048ca1550
  DatePickerDialog: ccff2f91ff7a018057a4d72fa5ad6de49c8cb0cd
  FBAEMKit: 9900b2edd99a2d21629a6277e6166f14c6215799
  FBAudienceNetwork: 2457a89b45e2596241fd81b0c2fd8cb6f6053869
  FBSDKCoreKit: 0791f8f68a8630931a4c12aa23a56cc021551596
  FBSDKCoreKit_Basics: 46d6b472c0dd0a5a7e972c025033d1c567f54eb4
  FBSDKLoginKit: b4a4eba1d62eb452544411824f41689adabd5bd2
  FirebaseAnalytics: 3feef9ae8733c567866342a1000691baaa7cad49
  FirebaseCore: 6b32c57269bd999aab34354c3923d92a6e5f3f84
  FirebaseCoreExtension: f1bc67a4702931a7caa097d8e4ac0a1b0d16720e
  FirebaseCoreInternal: 35731192cab10797b88411be84940d2beb33a238
  FirebaseCrashlytics: 41bbdd2b514a8523cede0c217aee6ef7ecf38401
  FirebaseInstallations: 6ef4a1c7eb2a61ee1f74727d7f6ce2e72acf1414
  FirebaseMessaging: f8a160d99c2c2e5babbbcc90c4a3e15db036aee2
  FirebaseRemoteConfigInterop: e76f46ffa4d6a65e273d4dfebb6a79e588cec136
  FirebaseSessions: 3f56f177d9e53a85021d16b31f9a111849d1dd8b
  Fyber_Marketplace_SDK: 215c2020efd507c0e97f40871e96a26918f8986e
  Google-Mobile-Ads-SDK: 6d2fc31d83b7b13a7dee3d622f1538fa3324958a
  GoogleAppMeasurement: 987769c4ca6b968f2479fbcc9fe3ce34af454b8e
  GoogleDataTransport: aae35b7ea0c09004c3797d53c8c41f66f219d6a7
  GoogleSignIn: ce8c89bb9b37fb624b92e7514cc67335d1e277e4
  GoogleUserMessagingPlatform: a8b56893477f67212fbc8411c139e61d463349f5
  GoogleUtilities: 26a3abef001b6533cf678d3eb38fd3f614b7872d
  GTMAppAuth: f69bd07d68cd3b766125f7e072c45d7340dea0de
  GTMSessionFetcher: 5aea5ba6bd522a239e236100971f10cb71b96ab6
  HandyJSON: 9e4e236f5d2dbefad5155a77417bbea438201c03
  HyBid: 8002537754c02740c30b19b1f9018c41f41021ad
  InMobiSDK: ee53561ba1fd21787b1eb82f02da9b93067ffc8e
  IronSourceSDK: 557a0edad39c2a48a225af07b491c672ca5acd36
  Kingfisher: 53a10ea35051a436b5fb626ca2dd8f3144d755e9
  MintegralAdSDK: 217cca20529055c8791c82985dd7a74864e49fd0
  nanopb: fad817b59e0457d11a5dfbde799381cd727c1275
  PromisesObjC: f5707f49cb48b9636751c5b2e7d227e43fba9f47
  PromisesSwift: 9d77319bbe72ebf6d872900551f7eeba9bce2851
  RSKPlaceholderTextView: 85cb165bfbfe160a2e7bfb6bcd77a21100ce1b52
  SDWebImage: 73c6079366fea25fa4bb9640d5fb58f0893facd8
  smaato-ios-sdk: cb9939713a4906a7901730aaa531b4004912c95d
  SnapKit: e01d52ebb8ddbc333eefe2132acf85c8227d9c25
  Then: 844265ae87834bbe1147d91d5d41a404da2ec27d
  Toast-Swift: 7a03a532afe3a560d4044bc7c237e2864d295173
  UnityAds: df29459d94ca7c0676cdd9ba96ef6420670ffbfa
  VungleAds: d7cf66a6dfd390a583ea2b2cfb9af1043b686e58
  Zip: b3fef584b147b6e582b2256a9815c897d60ddc67

PODFILE CHECKSUM: 3eae141d78313d8fdd52f50d8066c7418cecbca3

COCOAPODS: 1.15.2

**Comment by aybarska** [comment]
we have the same problem. Everyone can receive via token but on topic's some users are not receiving the notification.

**Comment by rizafran** [comment]
Thanks for reporting. For us to narrow down the possible pain point of the issue, could you provide the additional information:

- Confirmation if you're using [Topic Conditions](https://firebase.google.com/docs/cloud-messaging/send-message#:~:text=example%2C%20the%20following-,condition,-will%20send%20messages)
- Confirmation if these tokens are valid ([not unregistered or not invalid](https://firebase.google.com/docs/cloud-messaging/manage-tokens#detect-invalid-token-responses-from-the-fcm-backend)) and these tokens are subscribed to these [topics](https://developers.google.com/instance-id/reference/server#:~:text=relations%20associated%20with%20the%20token.%20For%20example%2C%20a%20list%20of%20topic%20subscriptions) you're targeting (You could utilize the[ get info method ](https://developers.google.com/instance-id/reference/server#get_information_about_app_instances)from the instance ID API for this.)
- Complete sample payload request and response

**Comment by aybarska** [comment]
In the console's Messaging tab, we ran 2 test campaigns using our test topic. 4 of our test devices were subscribed to this topic, but only one of them received the notification. I’ll add a screenshot below
<img width="1160" alt="Screenshot 2024-11-11 at 09 13 35" src="https://github.com/user-attachments/assets/cc035e07-806d-44c7-b3bb-e970a60543e2">

**Comment by haibozha** [comment]
We found a bug in FCM server that impacts a small subset of newly minted FCM tokens for their topic messaging. We are working on a fix and anticipate deploying it within the next few days.
To assist us in confirming the root cause of this issue, please submit a support case to Firebase and include a few sample FCM tokens. We will provide an update as the fix is rolled out.

**Comment by aybarska** [comment]
@haibozha Will this solution require an update on the iOS SDK side? I'm asking so we can plan our release schedule. Additionally, let me inform you that this issue is also occurring on the Android side. Thanks in advance

**Comment by dpa99c** [comment]
This issue also seems to occur when targeting via user segment, as well as topic:

Our iOS app has had no code changes and was previously receiving topic and user-segmented notifications just fine.
But now notifications sent from the Firebase Console targetting a topic or user segment are not received.
But if we send a test notification using the FCM token on the device, the notification is always received.

We have raised this with Firebase Support.

**Comment by meor9zcu12** [comment]
This issue also be occurred in our Android app.

We contacted Firebase Support nearly a week ago and provided necessary information to them.
However, we didn't get more information from them after that.

Would Firebase team update information on [Firebase Status Dashboard](https://status.firebase.google.com/summary) for better transparency?

**Comment by haibozha** [comment]
Thank you for your feedback. We are updating the information regarding this issue at https://status.firebase.google.com/.

We appreciate your patience as we work to fully restore the service.

**Comment by haibozha** [comment]
As of 11/25, our fix has rolled out to 100% of the affected registrations.
