### ISSUE TITLE
NSInvalidArgumentException', reason: '+[NSData gul_dataByGzippingData:error:]: unrecognized selector sent to class 0x1f88ab900'

### ISSUE THREAD

**Issue by shokarta** [firebase/firebase-ios-sdk#14072]
### Description

upon app startup, this is the crash... its always only when upgrading the app or installing new fresh (after previous uninstall)... second start is good... users occasinaly reported another crash on startup after several apps open

Generating the project via Cmake, after project ocnfigure i open xcproject from xcode and build it.
I dont know what changed, but month ago was everything fine... didnt change anything.
I cant say for sure, but its appearing to crash on first startup when the common popup to approve notifications permisison opens... so it does not continue till i click accept/reject and it crash in meanwhile

![image](https://github.com/user-attachments/assets/51b6db80-3287-4643-bbd1-d42286fa8ead)

### Firebase SDK Version

c++ 12.2.0, ios 11.3.0

### Xcode Version

16.1 (latest)

### Installation Method

N/A

### Firebase Product(s)

Messaging

### Targeted Platforms

iOS

### Relevant Log Output

```shell
FCM: Loading UIApplication FIRFCM category
[FirebaseCore] [I-COR000005] No app has been configured yet.
[FirebaseCore] [I-COR000005] No app has been configured yet.
Setting up ios 10 message delegate.
[FirebaseCore] [I-COR000005] No app has been configured yet.
11.3.0 [FirebaseCore] [I-COR000003] The default Firebase app has not yet been configured. Add *FirebaseApp.configure() to your application initialization. This can be done in in the App Delegate's application(_: did FinishLaunchingWithOptions:) (or the @main struct's initializer in SwiftUI). Read more: https://firebase.google.com/docs/ios/setup#initialize_firebase_in_your_app
11.3.0 [FirebaseCore][I-COR000005] No app has been configured yet.
11.3.0 [FirebaseMessaging] [I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. If you'd prefer to manually integrate Firebase Messaging, add "FirebaseAppDelegateProxyEnabled" to your Info.plist, and set it to NO. Follow the instructions at: https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging to ensure proper integration.
stale focus object 0x0, doing manual update
Errors found! Invalidating cache...
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
FCM: Initialize Firebase Messaging FCM: Using FCM senderID 933253518766
FCM: Retrieve registration token
OnTokenReceived xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
FCM: new registration token received.
FCM: Retrieve registration token
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSData gul_dataByGzippingData: error:]: unrecognized selector sent to class 0x1f88ab900'
*** First throw call stack:
(0x194af87cc 0x191dcb2e4 0x194bfe75c 0x194a96b08 0x194a96430 0x102645848 0x102644f38 0x1026441b8 0x10263ac9c 0x10265ea18 0x10265ec08 0x10264c824 0x102636bb0 0x109568a30 0x10956a71c 0x10957f010 0x10957f618 0x21cfd3c40 0x21cfd0488)
libc++abi: terminating due to uncaught exception of type NSException
```

**Comment by shokarta** [comment]
in Testflight crash reports, i always see this only case reason:
![image](https://github.com/user-attachments/assets/1a277827-d020-4bf8-a0e1-4a7d80001fdc)

**Comment by shokarta** [comment]
And I also see which is strange, that it always fails on SECOND retrieving of FCM token... why it retries twice?
second run is again OK, it just make two different registration tokens

**Comment by shokarta** [comment]
i tried to kill the app when it crashes the first time (before i approve/reject notification permittion), so i force second start to pop it up again... so it does pop it up again on second start and all works fine... no crash... so its not realy the popup window for permititon as i expected

**Comment by shokarta** [comment]
11.4.0 has no difference

**Comment by paulb777** [comment]
Make sure that you link with the `-ObjC` option.  If that doesn't help, please open an issue at  https://github.com/firebase/firebase-cpp-sdk. We're not able to help with cmake build problems here.
