### ISSUE TITLE
issue with appcheck and googlesign in

### ISSUE THREAD

**Issue by yunsanch** [firebase/firebase-ios-sdk#14073]
### Description

**Describe the bug**
getting this error when trying to login with google
Unexpected API response: <NSHTTPURLResponse: 0x60000037fa40> { URL: https://firebaseappcheck.googleapis.com/v1/oauthClients/(null):exchangeDebugToken } { Status Code: 404, Headers {
    "Alt-Svc" =     (
        "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"
    );
    "Cache-Control" =     (
        private
    );
    "Content-Encoding" =     (
        gzip
    );
    "Content-Length" =     (
        160
    );
    "Content-Type" =     (
        "application/json; charset=UTF-8"
    );
    Date =     (
        "Sun, 10 Nov 2024 21:05:19 GMT"
    );
    Server =     (
        ESF
    );
    Vary =     (
        Origin,
        "X-Origin",
        Referer
    );
    "x-content-type-options" =     (
        nosniff
    );
    "x-frame-options" =     (
        SAMEORIGIN
    );
    "x-xss-protection" =     (
        0
    );
} }, body: {
  "error": {
    "code": 404,
    "message": "com.google.apps.framework.request.NotFoundException: Resource not found: oauthClients/(null)",
    "status": "NOT_FOUND"
  }
}

**To Reproduce**
1. set up appcheck and try to sing in with google

**Expected behavior**
 that it send verified requests
 
**Screenshots**
![Image](https://github.com/user-attachments/assets/da97e6dc-bfcc-4e06-a0ce-6fc57228d75a)

![Image](https://github.com/user-attachments/assets/d682b0cb-417c-44be-adf5-c7c9dc97c25f)
![Image](https://github.com/user-attachments/assets/e8d7974b-60d0-4183-8186-9bd7265316f3)

**Environment**
- Device: [ iPhone 16 ]
- OS: [ e.g. iOS 18 ]

**Additional context**
everyhting is set up as it is suppoed to in firebase, and google console, while all storage, firesotore, and auth show that they are getitng verified request, trying to log in with google does not provided a verified request bc it cant find the authclients even tho they are there

### Reproducing the issue

1. set up appcheck and try to sing in with google

### Firebase SDK Version

11.30.0

### Xcode Version

16

### Installation Method

Swift Package Manager

### Firebase Product(s)

App Check, Authentication

### Targeted Platforms

iOS

### Relevant Log Output

```shell
body: {
  "error": {
    "code": 404,
    "message": "com.google.apps.framework.request.NotFoundException: Resource not found: oauthClients/(null)",
    "status": "NOT_FOUND"
  }
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
Closing in favor of https://github.com/google/GoogleSignIn-iOS/issues/493
