### ISSUE TITLE
FR: Provide data messages delivered by APNs via FIRMessagingDelegate

### ISSUE THREAD

**Issue by wnagrodzki** [firebase/firebase-ios-sdk#1409]
### Environment

  * Xcode version: Version 9.4 (9F1027a)
  * Firebase SDK version: 5.2.0
  * Firebase Component: Messaging
  * Component version: 3.0.2

### Feature Proposal

I have noticed that data messages with the content-available flag set to yes are always delivered via APNs.
However with the current state of Firebase API, we are forced to handle those data messages as notifications in `application(_ application:, didReceiveRemoteNotification:, fetchCompletionHandler:)` method.

Wouldn't it be a good idea to make Firebase intercept this notification and deliver via `MessagingDelegate`'s `messaging(_:, didReceive:)` method?

This way we would be able to handle all data messages (conveyed via APNs and via direct channel) in one place. Please let me know what you think.

**Comment by morganchen12** [comment]
It's not entirely possible to do this currently without changing the method signature of `MessagingDelegate`'s `messaging(_:didReceive:)` method since the fetch completion handler must also be passed along.

**Comment by chliangGoogle** [comment]
data message can be delivered in both APNS or direct channel depending on which server API you are using, for instance if you are using HTTP v1 API, your message is delivered through APNS and if you use legacy API, it's using direct channel.

And yes for iOS 9 and below, FCM handles message in application(_ application:, didReceiveRemoteNotification:, fetchCompletionHandler:) method. 
And for iOS 10 and above, FCM handles data message in MessagingDelegate's messaging(_:, didReceive:) method.

And This is on top of our feature requests to support all OS versions for delivery data message in FIRMessagingDelegate messaging:didReceiveMessage:. And we can deprecate the other one during I/O breaking API change.

**Comment by chliangGoogle** [comment]
We are thinking of separating the data message delivery via APNS and via direct channel so it's less confusing for people. So we will adjust the data message delivered in direct channel to use FIRMessagingDelegate messaging:didReceiveMessage:. while message delivered in APNS channel to use application(_ application:, didReceiveRemoteNotification:, fetchCompletionHandler:). 

Let us know what you think.

**Comment by wnagrodzki** [comment]
When I was reading [About FCM Messages](https://firebase.google.com/docs/cloud-messaging/concept-options) documentation I learned that FCM works with two kinds of messages: _notification message_ and _data message_. On this level of abstraction, _notification message_ is a message visible to user (it may convey some data), and _data message_ is invisible to him (must convey data).

Let's step one level abstraction down, to iOS platform. Provided with _data message_ definition, I assumed that there are two possible forms of it. First, a message delivered via direct channel that conveys only data, second message delivered as silent push notification via APNS (note that both fit to data message definition).

Provided that FCM works with _notification messages_ and _data messages_, I expected iOS Framework to utilize the same level of abstraction. Currently, _data message_ manifests in both `ApplicationDelegate` and `MessagingDelegate` - it looks to me like abstraction is leaking.

If _notification message_ and _data message_ definitions were removed, data message delivery via APNS and via direct channel separated, it may actually render FCM easier to understand.

---
A small digression: if _data message_ was non-leaking abstraction client would not have to specify `content-available` flag under `apns` key in JSON payload at all. Firebase would figure out which way to use, direct channel or APNS. For instance, if a direct channel to a device is opened it would use it, otherwise APNS. This way, APNS (implementation detail) would not leak outside FCM abstraction.

---
This is my subjective opinion, thus it may be worth asking other uses what they think.

**Comment by chliangGoogle** [comment]
That's very good suggestion. We are also thinking of improving the documentations to clarify the concepts of data message in two different delivery channels.

The reason we can't do data message manifest in just Apple delegate is that for message sent in direct channel in iOS 10+, we can't modify UNNotification object so we can't use Apple's UNUserNotificationCenter, hence, we created a messagingDelegate. 

And since we are creating a messagingDelegate anyway, it would make sense to let direct channel message to use the messagingDelegate for all iOS versions. And another benefit is that when use direct channel message, developers can use the FIRMessagingRemoteMessage object and access more information about the FCM message.

We like to hear from you of your thoughts so feel free to propose features you would like to have. Thanks again!

**Comment by chliangGoogle** [comment]
Close this issue for now. Feel free to open if you have more arguments on this.
