### ISSUE TITLE
Running into function signature issue for Functions.function(app:) after updating from 8.15 

### ISSUE THREAD

**Issue by mshresthasentri** [firebase/firebase-ios-sdk#14097]
### Description

Running into `Argument passed to call that takes no arguments` when passing instance of `FIRApp` to `Functions.functions(app:).` 
Above functions seems to be working fine in Swift when using SDK version 8.15 but updating FirebaseSDK above that throws the error. The possible workaround for us was to create instance of Functions using Objective C but we have not been able to navigate the issue for Swift. 

### Firebase SDK Version

10.22.0

### Xcode Version

15.3

### Installation Method

CocoaPods

### Firebase Product(s)

Functions

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment]
Hi @mshresthasentri, could you please add a small snippet to help us reproduce the problem?

**Comment by mshresthasentri** [comment]
Objective C code
```
NSString *filePath = [[NSBundle mainBundle] pathForResource:@"ChatAppExample-Info" ofType:@"plist"];
FIROptions *chatOptions = [[FIROptions alloc] initWithContentsOfFile:filePath];
[FIRApp configureWithName:@"mychatappname" options:chatOptions];
chatFirebaseApp = [FIRApp appNamed:@"mychatappname"];
return chatApp

```
Swift code
```
let chatFirebaseApp = above objective c function returns the app
let functions = Functions.functions(app: chatApp!)
```

this last line complains about `Argument passed to call that takes no arguments`

**Comment by paulb777** [comment]
Thanks, but I'm still not able to reproduce. The following builds fine for me:

 `var functions = Functions.functions(app: FirebaseApp.app(name: "abc")!)`

We'll likely need a reproducible example to help.

**Comment by mshresthasentri** [comment]
<img width="985" alt="Screenshot 2024-11-14 at 6 30 23 AM" src="https://github.com/user-attachments/assets/b0d29a1e-2b05-49fd-8899-f58862242b21">
This is what i see on my end. If I jump to definition I can see the method signature exists. Not exactly sure why it does not pick up the method.

<img width="827" alt="Screenshot 2024-11-14 at 6 30 33 AM" src="https://github.com/user-attachments/assets/c303c378-5c09-4dfd-97a1-366fcf3b900e">
