### ISSUE TITLE
Facing crash on iOS 18+ after updating to version 11.4.1

### ISSUE THREAD

**Issue by SURYAKANTSHARMA** [firebase/firebase-ios-sdk#14118]
### Description

Getting crash on suspend resume partial function for HeartbeatController.flushAsync()
Crashlytics version - 11.4.1
crash is only on iOS 18 100% 
Attaching crash logs as well. Can we please look into this 
<img width="1454" alt="Screenshot 2024-11-14 at 6 47 23 PM" src="https://github.com/user-attachments/assets/a7ef9bcf-bb71-4316-8eb6-e9433ef38d44">
[bike.rapido.customer_issue_0a0a3d8ea03578487b6d95752d876803_crash_session_01222b12b28b4b1ca0229c69af222942_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/17749089/bike.rapido.customer_issue_0a0a3d8ea03578487b6d95752d876803_crash_session_01222b12b28b4b1ca0229c69af222942_DNE_0_v2_stacktrace.txt)

### Reproducing the issue

Not able to reproduce on local machine yet will try to add in future

### Firebase SDK Version

11.4.1

### Xcode Version

16

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

  - Firebase/Analytics (11.4.1):
    - Firebase/Core
  - Firebase/Auth (11.4.1):
    - Firebase/CoreOnly
    - FirebaseAuth (~> 11.4.0)
  - Firebase/Core (11.4.1):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 11.4.0)
  - Firebase/CoreOnly (11.4.1):
    - FirebaseCore (= 11.4.1)
  - Firebase/Crashlytics (11.4.1):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 11.4.0)
  - Firebase/Database (11.4.1):
    - Firebase/CoreOnly
    - FirebaseDatabase (~> 11.4.0)
  - Firebase/Firestore (11.4.1):
    - Firebase/CoreOnly
    - FirebaseFirestore (~> 11.4.0)
  - Firebase/Messaging (11.4.1):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 11.4.0)
  - Firebase/Performance (11.4.1):
    - Firebase/CoreOnly
    - FirebasePerformance (~> 11.4.0)
  - Firebase/RemoteConfig (11.4.1):
    - Firebase/CoreOnly
    - FirebaseRemoteConfig (~> 11.4.0)
  - FirebaseABTesting (11.4.0):
    - FirebaseCore (~> 11.0)
  - FirebaseAnalytics (11.4.0):
    - FirebaseAnalytics/AdIdSupport (= 11.4.0)
    - FirebaseCore (~> 11.0)
    - FirebaseInstallations (~> 11.0)
  - FirebaseAnalytics/AdIdSupport (11.4.0):
    - FirebaseCore (~> 11.0)
    - FirebaseInstallations (~> 11.0)
  - FirebaseAppCheckInterop (11.4.0)
  - FirebaseAuth (11.4.0):
    - FirebaseAppCheckInterop (~> 11.0)
    - FirebaseAuthInterop (~> 11.0)
    - FirebaseCore (~> 11.4)
    - FirebaseCoreExtension (~> 11.4)
  - FirebaseAuthInterop (11.4.0)
  - FirebaseCore (11.4.1):
    - FirebaseCoreInternal (~> 11.4)
  - FirebaseCoreExtension (11.4.1):
    - FirebaseCore (~> 11.0)
  - FirebaseCoreInternal (11.4.0):
  - FirebaseCrashlytics (11.4.0):
    - FirebaseCore (~> 11.4)
    - FirebaseInstallations (~> 11.0)
    - FirebaseRemoteConfigInterop (~> 11.0)
    - FirebaseSessions (~> 11.0)
  - FirebaseDatabase (11.4.0):
    - FirebaseAppCheckInterop (~> 11.0)
    - FirebaseCore (~> 11.0)
    - FirebaseSharedSwift (~> 11.0)
    - GoogleUtilities/UserDefaults (~> 8.0)
    - leveldb-library (~> 1.22)
  - FirebaseFirestore (11.4.0):
    - FirebaseCore (~> 11.4)
    - FirebaseCoreExtension (~> 11.4)
    - FirebaseFirestoreInternal (= 11.4.0)
    - FirebaseSharedSwift (~> 11.0)
  - FirebaseFirestoreInternal (11.4.0):
    - abseil/algorithm (~> 1.20240116.1)
    - abseil/base (~> 1.20240116.1)
    - abseil/container/flat_hash_map (~> 1.20240116.1)
    - abseil/memory (~> 1.20240116.1)
    - abseil/meta (~> 1.20240116.1)
    - abseil/strings/strings (~> 1.20240116.1)
    - abseil/time (~> 1.20240116.1)
    - abseil/types (~> 1.20240116.1)
    - FirebaseAppCheckInterop (~> 11.0)
    - FirebaseCore (~> 11.0)
    - "gRPC-C++ (~> 1.65.0)"
    - gRPC-Core (~> 1.65.0)
    - leveldb-library (~> 1.22)
    - nanopb (~> 3.30910.0)
  - FirebaseInstallations (11.4.0):
    - FirebaseCore (~> 11.0)
    - GoogleUtilities/Environment (~> 8.0)
    - GoogleUtilities/UserDefaults (~> 8.0)
    - PromisesObjC (~> 2.4)
  - FirebaseMessaging (11.4.0):
    - FirebaseCore (~> 11.0)
    - FirebaseInstallations (~> 11.0)
    - GoogleDataTransport (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 8.0)
    - GoogleUtilities/Environment (~> 8.0)
    - GoogleUtilities/Reachability (~> 8.0)
    - GoogleUtilities/UserDefaults (~> 8.0)
    - nanopb (~> 3.30910.0)
  - FirebasePerformance (11.4.0):
    - FirebaseCore (~> 11.0)
    - FirebaseInstallations (~> 11.0)
    - FirebaseRemoteConfig (~> 11.0)
    - FirebaseSessions (~> 11.0)
    - GoogleDataTransport (~> 10.0)
    - GoogleUtilities/Environment (~> 8.0)
    - GoogleUtilities/MethodSwizzler (~> 8.0)
    - GoogleUtilities/UserDefaults (~> 8.0)
    - nanopb (~> 3.30910.0)
  - FirebaseRemoteConfig (11.4.0):
    - FirebaseABTesting (~> 11.0)
    - FirebaseCore (~> 11.0)
    - FirebaseInstallations (~> 11.0)
    - FirebaseRemoteConfigInterop (~> 11.0)
    - FirebaseSharedSwift (~> 11.0)
    - GoogleUtilities/Environment (~> 8.0)
    - "GoogleUtilities/NSData+zlib (~> 8.0)"
  - FirebaseRemoteConfigInterop (11.4.0)
  - FirebaseSessions (11.4.0):
    - FirebaseCore (~> 11.4)
    - FirebaseCoreExtension (~> 11.4)
    - FirebaseInstallations (~> 11.0)
    - GoogleDataTransport (~> 10.0)
    - GoogleUtilities/Environment (~> 8.0)
    - GoogleUtilities/UserDefaults (~> 8.0)
    - nanopb (~> 3.30910.0)
    - PromisesSwift (~> 2.1)
  - FirebaseSharedSwift (11.4.0)

```

</details>

**Comment by ncooke3** [comment]
Hi @SURYAKANTSHARMA, thanks for the report and apologies for the trouble. Could you try updating to 11.5.0? The crashing code was rewritten in 11.5.0 to use traditional completion handler based code rather than async/await.

**Comment by SuryakantRapido** [comment]
@ncooke3 We have upgraded to the latest version 11.5.0 of firebase. Still seeing this crash can you please check this on priority?

**Comment by ncooke3** [comment]
@SuryakantRapido, could you please share a stack trace from a device running 11.5.0? The reason being is that the trace should be at least a little different than the one in the original post.

This is because the `HeartbeatController.flushAsync()` line maps to a method that is named differently in 11.5.0 (and does not use async/await).

**Comment by SuryakantRapido** [comment]
@ncooke3 it looks like the version was not updated yet. Will update the version and get back. 
Thanks for bringing us in notice. 
<img width="1194" alt="Screenshot 2024-11-21 at 6 10 14 PM" src="https://github.com/user-attachments/assets/e8315fa7-99e2-4532-a0de-66c81625a403">

Can you please elaborate as well if this is a swift concurrency issue in general or Firebase SDK issue ? I see the flush method implementation has changed back to completion handler.

**Comment by ncooke3** [comment]
> Can you please elaborate as well if this is a swift concurrency issue in general or Firebase SDK issue ? I see the flush method implementation has changed back to completion handler.

It seemed like a Swift concurrency issue that was being surfaced by mixing async/await with GCD queue code. So, the fix was to keep everything GCD for now.

**Comment by SuryakantRapido** [comment]
Thanks @ncooke3 crash is fixed after the update. Thanks for sharing valuable information.
