### ISSUE TITLE
Phone Authentication Error

### ISSUE THREAD

**Issue by ElrB** [firebase/firebase-ios-sdk#14136]
### Description

I am currently experiencing a phone authentication error that I was not before. Please see error below:

Optional(Error Domain=FIRAuthErrorDomain Code=17999 "An internal error has occurred, print and inspect the error details for more information." UserInfo={NSLocalizedDescription=An internal error has occurred, print and inspect the error details for more information., FIRAuthErrorUserInfoNameKey=ERROR_INTERNAL_ERROR, NSUnderlyingError=0x1250c6d40 {Error Domain=FIRAuthInternalErrorDomain Code=3 "(null)" UserInfo={NSUnderlyingError=0x10767bbd0 {Error Domain=com.google.HTTPStatus Code=503 "(null)" UserInfo={data={length = 207, bytes = 0x7b0a2020 22657272 6f72223a 207b0a20 ... 5d0a2020 7d0a7d0a }, data_content_type=application/json; charset=UTF-8}}, FIRAuthErrorUserInfoDeserializedResponseKey={
    code = 503;
    errors =     (
                {
            domain = global;
            message = "Error code: 39";
            reason = backendError;
        }
    );
    message = "Error code: 39";
}}}})

Code:

let configuration = Configuration(requestCode: { phone, completion in
     PhoneAuthProvider.provider().verifyPhoneNumber(phone, uiDelegate: nil, completion: completion)
}, signIn: { verificationID, verificationCode, completion in
     let credential = PhoneAuthProvider.provider().credential(withVerificationID: verificationID, verificationCode: verificationCode)
     Auth.auth().signIn(with: credential) { _, error in completion(error) }
})

Billing level:

![Screenshot 2024-11-17 at 6 46 11 PM](https://github.com/user-attachments/assets/0d642367-4ecc-4a0e-88a0-87b8ba825901)

### Firebase SDK Version

11.4

### Xcode Version

15.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Authentication, Crashlytics, Firestore, Functions, Messaging, Storage

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Thanks for filing, @ElrB. Per checking, this is possibly related to a blocked region or carrier. Since I don't have a visibility to project specific, please file a ticket through our [support channel](https://firebase.google.com/support) for investigation. That being said, I'll go ahead and close the issue.
