### ISSUE TITLE
Discrepancy in FCM REST API documentation for APNS parameters

### ISSUE THREAD

**Issue by johsu** [firebase/firebase-ios-sdk#14159]
### Description

The documentation for the new live activity support through FCM displays `live_activity_token` in lower snake case: 
https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#ApnsConfig
https://firebase.google.com/docs/cloud-messaging/ios/live-activity#start-live-activity

However in practice, and as suggested by the [FCM REST API Explorer](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages/send), the apns body accepts `liveActivityToken` in camel case. The same goes for fcm_options vs fcmOptions.
![Screenshot 2024-11-21 at 11 24 43 AM](https://github.com/user-attachments/assets/7c4efded-e1dd-4aab-98f9-f40aac9aa2b4)

### Firebase SDK Version

N/A

### Xcode Version

N/A

### Installation Method

N/A

### Firebase Product(s)

Messaging

### Targeted Platforms

iOS

**Comment by rizafran** [comment]
Thanks for reaching out, @johsu. Per checking with the engineer, both the camel case and snake case are supported, so it's fine to use either of the two.
