### ISSUE TITLE
firebase auth ios device error [web-internal-error]

### ISSUE THREAD

**Issue by heshesh2010** [firebase/firebase-ios-sdk#14160]
### Description

Hello , 

i'm using flutter and when i try to send otp to my phone number I see the re captcha is loading and then closing and the error is web-internal-error 

I'm sure the google cloud keys is Don't restrict key 

and I have enabled the appAppttest  and device check and still got the same error 

### Reproducing the issue

Hello , 

i'm using flutter and when i try to send otp to my phone number I see the re captcha is loading and then closing and the error is web-internal-error 

I'm sure the google cloud keys is Don't restrict key 

and I have enabled the appAppttest  and device check and still got the same error 

### Firebase SDK Version

5.3.3

### Xcode Version

15.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @heshesh2010, could you provide the full error logs you encountered?

**Comment by paulb777** [comment]
This may be an issue with your specific project. Would you please file a ticket through our [support channel](https://firebase.google.com/support) for investigation?
