### ISSUE TITLE
Int values being sent to Firebase is being converted to a Double

### ISSUE THREAD

**Issue by huishanreed** [firebase/firebase-ios-sdk#14174]
### Description

When we send events through to Firebase where the parameters are Integers, they are converted to a double. For example, the job_id parameter being sent to Firebase is 36442820:
`11.1.0 - [FirebaseAnalytics][I-ACS023105] Event is not subject to real-time event count daily limit. Marking an event as real-time. Event name, parameters: save_job, {
    af_id = xxxxxxxxx;
    apple_app_id = xxxxxxx;
    content_group = search_results;
    data_element = save_job;
    data_element_action = tap;
    data_key_metric = true;
    data_screen_category = search_results;
    data_screen_component = job_card;
    dev_key = xxxxxxxx;
    ga_debug (_dbg) = 1;
    ga_event_origin (_o) = app+gtm;
    ga_realtime (_r) = 1;
    job_age = 4;
    job_card_position = 14;
    job_easy_apply_status = Easy Apply Job: Internal + Screening Question;
    job_id = 36442820;
    job_location = East Lyng;
    job_sector = ;
    job_title = Test job 22/11/2024 13:37:02;
    job_type = contract;
    job_view_status = featured_job, skills;
    recruiter_ECID = 12345678;
    recruiter_OUID = 123456;
    recruiter_type = recruitment_consultancy;
    search_term = ;
}`

### Reproducing the issue

Using the Firebase Analytics SDK, send analytics through as an integer. If you check the DebugView for the results, it is not the same number as what was being sent. 

### Firebase SDK Version

11.1

### Xcode Version

15.4

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by huishanreed** [comment]
Hi @rizafran , thanks for looking into it. Here is a code snippet of my parameters:
`        let customData = [
            "job_type": job.type.rawValue,
            "job_age": job.jobPostedDaysCount,
            "job_title": job.title,
            "job_location": job.location?.displayLocation,
            "job_id": job.jobId
        ] as [String: GoogleAnalyticsRepresentable?]`
Where the jobId is declared as an Int.
In our GoogleAnalyticsRepresentable protocol:
`public protocol GoogleAnalyticsRepresentable {
    var analyticsRepresentation: Any { get }
}`
`extension Int: GoogleAnalyticsRepresentable {
    public var analyticsRepresentation: Any {
        return NSNumber(value: self)
    }
}`

**Comment by rizafran** [comment]
Thanks for sharing your code snippet, @huishanreed. One of my colleagues also tried to reproduce the issue but they were able to get the same int value in the DebugView. I'm wondering if it has something to do with the protocol that converts the value to Double? Could you try debugging it by manually setting the value of the job_id or by printing out the actual value being returned by the protocol?

**Comment by huishanreed** [comment]
Hi @rizafran I looked into this further and if you try it with an int that is a small number, eg 100 it is fine. Please can you try and reproduce it with a large number like 33937797 ?

**Comment by rizafran** [comment]
@huishanreed, I'm still unable to reproduce the issue with a large number.
<img width="286" alt="Screenshot 2024-12-17 at 3 39 38 AM" src="https://github.com/user-attachments/assets/d91622d7-bde1-4383-8d67-2c6d4a41e74a" />
