### ISSUE TITLE
[Unity] Problems with upgrading to Firebase 11

### ISSUE THREAD

**Issue by Misterkuul** [firebase/firebase-ios-sdk#14197]
### Description

I need to upgrade my firebase to version 11 to prevent crashes (https://github.com/firebase/firebase-ios-sdk/issues/13945) problem is that when I do that with ARCore Unity package 1.40 I get the error:  

```
[!] CocoaPods could not find compatible versions for pod "Firebase/RemoteConfig":
  In Podfile:
    ARCore/Geospatial (= 1.46) was resolved to 1.46.0, which depends on
      ARCore/GARSession (= 1.46.0) was resolved to 1.46.0, which depends on
        Firebase/RemoteConfig (< 11.0, >= 8.0)


    Firebase/RemoteConfig (> 11.0)

[Error when updating package to 1.46.txt](https://github.com/user-attachments/files/17979765/Error.when.updating.package.to.1.46.txt)

Specs satisfying the `Firebase/RemoteConfig (> 11.0), Firebase/RemoteConfig (< 11.0, >= 8.0)` dependency were found, but they required a higher minimum deployment target.

```
And when I upgrade the package I still can't upgrade via the Terminal and when I try to build I get the problem marked down in this file: [Error when updating package to 1.46.txt](https://github.com/user-attachments/files/17979779/Error.when.updating.package.to.1.46.txt)

This could be a stupid questions thanks to my inexperience with this system, but what version would I need to make ARCore play nice with Firebase 11? How would my podfile look like then?

A sincere thank you for your time.

### Firebase SDK Version

10.29.0

### Xcode Version

15.2

### Installation Method

CocoaPods

### Firebase Product(s)

Infrastructure

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

platform :ios, '17.0'

use_modular_headers!

source 'https://github.com/CocoaPods/Specs.git'

project '/Users/developer/Desktop/mooi/Unity-iPhone.xcodeproj'

target 'Unity-iPhone' do
  pod 'Firebase/Analytics', '< 11.0'
  pod 'Firebase/Auth', '< 11.0'
  pod 'Firebase/Database', '< 11.0'
  pod 'Firebase/RemoteConfig', '< 11.0'
  pod 'ARCore/Geospatial', '1.46'

  inhibit_all_warnings!
end


```

</details>

I also tried with specific firebase functions

**Comment by paulb777** [comment]
@Misterkuul Sorry about the trouble. Please file an issue with ARCore requesting an update that is compatible with Firebase 11.x.
