### ISSUE TITLE
FIRAuthSettings should remove FIR prefix in Swift.

### ISSUE THREAD

**Issue by ryanwilson** [firebase/firebase-ios-sdk#1423]
https://github.com/firebase/firebase-ios-sdk/blob/22a943708d156712a97d29dcd11ee903cb9d8494/Firebase/Auth/Source/Public/FIRAuthSettings.h#L22

Unfortunately we missed this one in review, it's an easy fix but will have to wait for the next breaking change.

**Comment by renkelvin** [comment]
Fix `FIRAuthSettings`: https://github.com/firebase/firebase-ios-sdk/pull/2722

**Comment by ryanwilson** [comment]
Fixed and will be released with Firebase 6 - see the milestone to see if it's been released or not (as of this writing, it has not released).
