### ISSUE TITLE
iOS App using Firebase SDK unintentionally triggering website request when organically opening the app 

### ISSUE THREAD

**Issue by lindsayok** [firebase/firebase-ios-sdk#14256]
### Description

App Details: 

- App ID: [1174047097](https://apps.apple.com/us/app/coolblue/id1174047097) (Issue is iOS specific, not happening on Android)
- GMP App ID: 1:16212101609:ios:ffd6c252371e0605
- Firebase Project: coolblue-mobile-app

**Issue Summary:** 

The customer is seeing this behavior (see attached video called 'unexpected behavior) when some users open their app vs. just opening the app and not being re-directed anywhere (see attached video 'expected behavior). In the cases we know of, this unexpected behavior is happening directly as the app was opened, and not after clicking anything. The customer is unable to replicate the issue on the spot, but users  are continuing to report it (note the issue is not happening on the newest version of the app)

The Customer is only using the Firebase SDK, and is not using any marketing tags or pixels. However, when looking at their App logs, they are seeing [calls to Google tag manager](https://screenshot.googleplex.com/AQmRR6TQCvcRAY3), so it's odd that this is happening. 

**Debugging on customer side:**

- Turned off all ad manager banners
- Removed any custom HTML from GTM that included this URL
- Debugged the last updates in
- The app - the previous update relating to anything tracking/Google/Campaign Manager was months before
- Updated to the newest version of the Firebase SDK
- Looked at the new banner creations - saw no issues there
- Looked into any web views that could be triggered , they saw iFrames with Ad Interest Groups being loaded within their gtag script 
- Compared the last few versions of the app - there were no changes that could have caused this. Their latest update was enabling dark mode... so no relation to web views or tracking.
- In their codebase they don't have any hardcoded webviews.  If the user has the app installed and tries to open any Coolblue website page that starts with https://www.coolblue.nl/ , we are going to try to open it in the app. The app is responsible for the way this page is gonna be presented to the user and the navigation to this page.
- It's not Firebase dynamic links related, as it's happening right when opening the app from the iPhone home screen. 

**Debugging on support side:** 

- The 1547 entry is a request to [www.coolblue.nl/winkelmandje](http://www.coolblue.nl/winkelmandje). This suggests it's related to the [Coolblue website](https://screenshot.googleplex.com/3gjszdENM9AaUBw).
- Customer confirmed that GTM is being used on the website (but not in the app), which would explain why we see entries [1554/1555](https://screenshot.googleplex.com/3oW4YpRSbpU6vKs).
- We know that the problematic URL is "https://www.coolblue.nl/winkelmandje?initialAppCall=1" ([SS](https://screenshot.googleplex.com/AavqahHBnPVhjgg)) and the core question is what is triggering the website request. The customer has web views in the app, however this also happened on the homepage where there was no web view.
- One theory we had is that in their website GTM set-up, they’ve added an exception to prevent it from firing on this page. However, the customer doesn’t want to block the 'winkelmandje' (add to cart) page, but they could enable a trigger to block with 'initalAppCall' URLs.
- Somehow the app, through some sort of connection (and a Google connection is honestly the only conclusion we have) is triggering an iframe or website URL from our app

**Question**: What is triggering the website request, and how can they remove it? 

### Firebase SDK Version

10.27.0

### Xcode Version

15.4

### Installation Method

Swift Package Manager

### Firebase Product(s)

Infrastructure

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
@lindsayok Thanks for filing the issue. This may be challenging to investigate without a reproduction example. I don't think that anything in Firebase redirects to links other than Dynamic Links.

To help narrow the scope, would you update the issue with the Firebase products linked into the project via SPM?

**Comment by paulb777** [comment]
Hi @lindsayok Here is the list of products from the Issue template:

<img width="313" alt="Screenshot 2024-12-17 at 9 22 00 AM" src="https://github.com/user-attachments/assets/320238cb-74ae-4232-b8c6-cbd58664378e" />

When the project was set up in Swift Package Manager (SPM) a subset of those products was chosen.
