### ISSUE TITLE
Action Required: Apple Push Notification Service Server Certificate Update

### ISSUE THREAD

**Issue by songzhiming** [firebase/firebase-ios-sdk#14293]
### Description

[https://developer.apple.com/news/?id=09za8wzy&utm_campaign=iOS%20Dev%20Weekly&utm_medium=web&utm_source=iOS%20Dev%20Weekly%20Issue%20683](url)
Does FCM support this?

### Firebase SDK Version

10.23.0

### Xcode Version

15.1

### Installation Method

CocoaPods

### Firebase Product(s)

Remote Config, AB Testing, Analytics, Crashlytics, Messaging, Performance

### Targeted Platforms

iOS

### Relevant Log Output

```shell

```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
The link in the issue does not work. If you mean https://developer.apple.com/news/?id=09za8wzy, yes, the Firebase backend has been updated.
