### ISSUE TITLE
Invalid Shift

### ISSUE THREAD

**Issue by squm** [firebase/firebase-ios-sdk#1443]
https://github.com/firebase/firebase-ios-sdk/blob/137ce37363d72ac1d643ea9f93bc6e6665367e57/Firebase/Database/Api/FIRDatabaseQuery.m#L256

Left shift of 1 by 31 places cannot be represented in type 'long'

https://developer.apple.com/documentation/code_diagnostics/undefined_behavior_sanitizer/invalid_shift

**Comment by paulb777** [comment]
Thanks for the reports @squm! This and #1444 will be fixed in the next release #1445 and we'll add sanitizers to our regular testing - #1447
