### ISSUE TITLE
How to get 'No connection failed' error for FIRDatabaseReference.observeSingleEventOfType?

### ISSUE THREAD

**Issue by yunsun330** [firebase/firebase-ios-sdk#1457]
I am using 
   * Xcode 9.2
   * Firebase SDK
         Using Firebase (5.3.0)
         Using FirebaseAnalytics (5.0.1)
         Using FirebaseCore (5.0.4)
         Using FirebaseDatabase (5.0.1)
         Using FirebaseInstanceID (3.1.1)
         Using FirebaseStorage (3.0.0)

I have integrated Firebase on my iOS project and use the Realtime database and Storage.
I want to get the JSON data and image files from Firebase using the following code.

    FIRDatabaseReference *images = [[FIRDatabase database] child:kImagesKey];
    [images observeSingleEventOfType:FIRDataEventTypeValue withBlock:^(FIRDataSnapshot * _Nonnull snapshot) {
            FIRStorageReference *imagesRef = [[FIRStorage storage] child:kImagesKey];
            for (NSString *path in snapshot.valueInExportFormat) {
                NSURL *localURL = [self localURLForStoragePath:path];
                [[imagesRef child:path] writeToFile:localURL completion:^(NSURL *URL, NSError *error) {
                     // Display Image here
                }];
            }
    } withCancelBlock:^(NSError * _Nonnull error) {
        [self showErrorMessage:error];
    }];

It works good when the connection is good, but when there is no connection, for ex, when the app launches in airplane mode, no callback is called.
I want to show the connection error alert when there is no connection.
Please help me about it.
Thanks

**Comment by morganchen12** [comment]
RTDB doesn't surface connection state in its public API. You can use [SCNetworkReachability](https://developer.apple.com/documentation/systemconfiguration/scnetworkreachability) to detect connection state like airplane mode.

It's unlikely this will be added to RTDB in the near future.
