### ISSUE TITLE
App crash in FirebaseABTesting Framework

### ISSUE THREAD

**Issue by 0x8badf00d** [firebase/firebase-ios-sdk#1478]
### Environment

  * Xcode version: 9.4.1
  * Firebase SDK version: 4.13.0
  * Firebase Component: RemoteConfig (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 

  - Firebase/Core (4.13.0):
    - FirebaseAnalytics (= 4.2.0)
    - FirebaseCore (= 4.0.20)
  - FirebaseABTesting (1.0.0):
    - FirebaseCore (~> 4.0)
    - Protobuf (~> 3.1)
  - FirebaseAnalytics (4.2.0):
    - FirebaseCore (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - nanopb (~> 0.3)
  - FirebaseCore (4.0.20):
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
  - FirebaseInstanceID (2.0.10):
    - FirebaseCore (~> 4.0)
  - FirebaseRemoteConfig (2.1.3):
    - FirebaseABTesting (~> 1.0)
    - FirebaseAnalytics (~> 4.1)
    - FirebaseCore (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - Protobuf (~> 3.5)

### Problem:
We're seeing App crashes where stacktrace points to 
ABTExperimentPayload_ExperimentOverflowPolicy_IsValidValue + 4373920116

#### Steps to reproduce:

What happened? How can we make the problem occur? - Cannot reproduce the issue. But we're seeing about 400 of crashes with this stacktrace.
This could be a description, log/console output, etc.

Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000

Crashed: com.apple.main-thread
0  CoreFoundation                 0x18315c444 CFArrayGetCount + 84
1  THDConsumer                    0x102a87974 ABTExperimentPayload_ExperimentOverflowPolicy_IsValidValue + 4373920116
2  THDConsumer                    0x102a8774c ABTExperimentPayload_ExperimentOverflowPolicy_IsValidValue + 4373919564
3  THDConsumer                    0x102a870b0 ABTExperimentPayload_ExperimentOverflowPolicy_IsValidValue + 4373917872
4  THDConsumer                    0x102a8afa8 ABTExperimentPayload_ExperimentOverflowPolicy_IsValidValue + 4373933992
5  THDConsumer                    0x102a8ae84 ABTExperimentPayload_ExperimentOverflowPolicy_IsValidValue + 4373933700

**Comment by morganchen12** [comment]
Unfortunately, we'll have a hard time investigating this issue without repro steps. The crash is in a protobuf C method that shouldn't show up multiple times consecutively in a stack trace like the one you've posted.

**Comment by morganchen12** [comment]
We haven't been able to make any progress on this issue. I'll close it for now, but if you have repro steps please comment here and I'll reopen the issue.
