### ISSUE TITLE
Value of type 'StorageMetadata' has no member 'downloadURL'

### ISSUE THREAD

**Issue by Rovel** [firebase/firebase-ios-sdk#1488]
Hi,

I'm adding a brand new image upload in IOS 11.4, XCode 9.4.1, and Firebase/Storage (5.3.0) FirebaseStorage (= 3.0.0) as the Docs:
https://firebase.google.com/docs/storage/ios/upload-files?authuser=0
```
// Data in memory
let data = Data()

// Create a reference to the file you want to upload
let riversRef = storageRef.child("images/rivers.jpg")

// Upload the file to the path "images/rivers.jpg"
let uploadTask = riversRef.putData(data, metadata: nil) { (metadata, error) in
  guard let metadata = metadata else {
    // Uh-oh, an error occurred!
    return
  }
  // Metadata contains file metadata such as size, content-type, and download URL.
  let downloadURL = metadata.downloadURL
}
```
it throws this error:
`Value of type 'StorageMetadata' has no member 'downloadURL'`

Am I missing something? When I use the autocomplete of the metadata it shows no url option the closest I got was `metadata.path` or `metadata.storageReference`

Thanks

**Comment by mono0926** [comment]
The API had changed at version 5.0.0, so you should `StorageReference`'s `downloadURL` method.
 
> Removed downloadURLs property on StorageMetadata. Use StorageReference.downloadURL(completion:) to obtain a current download URL.
> [Firebase iOS SDK Version 5.0.0](https://firebase.google.com/support/release-notes/ios#5.0.0)

**Comment by Rovel** [comment]
thanks @mono0926, Are the docs updated?

**Comment by paulb777** [comment]
Looks like the docs were not updated. I'll reopen to track fixing the docs.

**Comment by morganchen12** [comment]
The docs have been updated. Thanks for filing!
