### ISSUE TITLE
App opens dynamic link content a second time following app uninstall

### ISSUE THREAD

**Issue by thienpham234** [firebase/firebase-ios-sdk#1489]
* Xcode version: 9.3.1
  * Firebase SDK version: 5.0.1
  * Firebase Component: Dynamic Links
  * Component version: 3.0.0

I implemented Dynamic links in project. I have a problem, I don't know the behavior that is true. Could you help me resolve it?

Steps to reproduce: 
1.  Install App from App store.
2. Share a link for project.
3. Delete App on device.
4. Tap an link share at above (2)
5. Move to App store and install again app. 
6. App receiver the content of link shared from Dynamic links.
7. Delete App on device. 
8. Open App store and install again app, (Move to App store not via dynamic links)
9. App still receiver the content of link shared from Dynamic links.

The function
 - (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary *)options
it's alway return the link for share when i removed and install app again.

At step 9 : "App still receiver the content of link shared. " , In my opinion, i think that is wrong. 

Let me know your opinion and If it's wrong , please help me resolve this.

**Comment by thienpham234** [comment]
I temporarily resolved this problem but I not sure this is root core.
I used property "mathType" to check. 
@property(nonatomic, assign, readonly) FIRDLMatchType matchType;

FIRDynamicLink *dynamicLink = [[FIRDynamicLinks dynamicLinks] dynamicLinkFromCustomSchemeURL:url];
 if (dynamicLink) {
       if (dynamicLink.url && dynamicLink.matchType == FIRDLMatchTypeUnique) {
             // to check App install when tap an link shared.
       } 
       if (dynamicLink.url && dynamicLink.matchType == FIRDLMatchTypeWeak) {
             // to check App install via App store (not tap an link shared).
       } 
}

**Comment by richardliveraise** [comment]
I'm having this issue as well. I didn't have this issue until recently though. Perhaps they're caching the IP for the tracking? 
Any chance this could be related to this ticket?
https://github.com/firebase/firebase-ios-sdk/issues/1244

**Comment by richardliveraise** [comment]
@morganchen12 @dmandar any update on this? Any drawback of checking if dynamicLink.matchType == FIRDLMatchTypeUnique ?

Thanks!

**Comment by thienpham234** [comment]
@richardliveraise  Thank you for reporting. I will try to reproduce this in my app.

**Comment by thienpham234** [comment]
@richardliveraise I reproduced to steps of you but i seen it still return matchType == FIRDLMatchTypeUnique.

**Comment by dmandar** [comment]
This should be fixed in the backend now. Please reopen if still occuring.
