### ISSUE TITLE
didReceiveRemoteNotification is not called with FCM Implementation 

### ISSUE THREAD

**Issue by mosn** [firebase/firebase-ios-sdk#149]
### [READ] Step 1: Are you in the right place?
I think so 

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: Xcode Version 9.0 beta 3
  * Firebase SDK version: 4.0.4
  * Library version: _____
  * Firebase Product: messaging/auth (auth, database, storage, core, messaging, etc)

### [REQUIRED] Step 3: Describe the problem
According to the documentation, When setting up the `Firebase Phone Authentication`,  it is necessary to implement `didReceiveRemoteNotification` delegate so that we can detect the push notification that was received for validation of phone auth process, However, with the new `UNUserNotificationCenter`, `didReceiveRemoteNotification` is only called when the app is in the background and user interacts with the notification directly. So in case of phone auth this method is never called. 

The problem is `didReceiveRemoteNotification` is not called with the FCM Notification implementation and the documentation does not suggest any alternatives

#### Steps to reproduce:

Run the example Messaging app

#### Relevant Code:
Code can found in the example app

**Comment by rsattar** [comment]
Hmm, by the Firebase Phone Authentication docs, I'm assuming you're talking about [this documentation](https://firebase.google.com/docs/auth/ios/phone-auth#receive-notifications-without-swizzling)?

Firebase Phone Authentication uses silent notifications, not display notifications, to do its verification. `UNUserNotificationCenter` is not involved with it at all. 

If you have both: 
1. `application:didReceiveRemoteNotification:fetchCompletionHandler`
2. `application:didReceiveRemoteNotification:`

defined in your app delegate, only (1) gets called ( (2) is deprecated, and never called if (1) is defined in the app delegate).

Are you combining the Messaging sample app with Auth? The messaging sample app currently doesn't have either method defined. It relies on method swizzling so the FCM library generally takes care of it. I'm considering adding the method to the messaging iOS sample only to print that a silent notification was received

**Comment by mosn** [comment]
Thanks for quick response, 

If I understand correct you are suggesting that (1) need to be called in order for Authetincation to work, `application:didReceiveRemoteNotification:fetchCompletionHandler` is only called when the app is configured with non-token based notification. That leads me to believe, in order to have Authentication and Cloud Messaging, I need to have both Token-Bases and Certificate based notifications enabled in my app, Which is currently not possible because FIR Dashboard only allows inserting of one of those. 

Any suggestion ?

**Comment by rsattar** [comment]
Could you clarify what you mean by:
> application:didReceiveRemoteNotification:fetchCompletionHandler is only called when the app is configured with non-token based notification.

Whether a server uses an auth-key or a certificate to authenticate its notification request to APNs, it does not matter on the iOS receiving side; iOS does not know or care about auth-key-based or certificate based auth.

Auth does not use the FCM SDK, and uses your APNs token directly to send a silent notification to your device. On iOS 10 and above, user notifications are not delivered to `application:didReceiveRemoteNotification:`, etc.) if the `UNUserNotificationCenterDelegate` is set.

Questions:
1) Are you disabling swizzling in Firebase? If not, then you shouldn't have to worry about anything.
2) Are you using the FCM SDK and the Firebase Auth SDK?
3) What the exact situation where something is not working?

Thanks!

**Comment by mosn** [comment]
Well that clarifies it now. I though I needed to have FCM Cloud Messaging implemented in order for the Authetincation to work, at least that hows the documentation is communicating. 

1. Swizzling is not disable 
2. I used both for Phone authentication and cloud messaging 
3. Everything is working :) , It was only a bit confusing in the documentation, 
_STEP 2 : Start receiving APNs notifications_

**Comment by rsattar** [comment]
Great! Glad I could help clarify it! 👍

**Comment by midhun-narayan** [comment]
guys i had a situation like FCM is coming for all devices under ios 10, But in case of iphone 8 only the notifications are coming in background condition  in my appdelegate


extension AppDelegate : MessagingDelegate {
   
    func messaging(_ messaging: Messaging, didReceive remoteMessage: MessagingRemoteMessage) {
        print("Received data message 10 +: \(remoteMessage)")
        NotificationCenter.default.post(name: NSNotification.Name(rawValue: messageKey), object: nil, userInfo: remoteMessage.appData)
    }
    
}

But the notification observer not getting these notification please help

**Comment by NALAWALAMURTUZA** [comment]
how to get a notification with image payload.
