### ISSUE TITLE
Messaging Component - Support for iOS Extensions

### ISSUE THREAD

**Issue by 5fcgdaeb** [firebase/firebase-ios-sdk#1490]
Version 5.2.0 does restore the 4.x level support for extensions; it fixes the issue in the Auth component. However, same issue also exists in the Messaging component. With the configuration below, it is not possible to include FirebaseMessaging component from an iOS extension. It fails with the error: "sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead".

  * Xcode version: 9.4.1
  * Firebase SDK version: 5.4.0
  * Firebase Component: Messaging
  * Component version: 3.0.3

Can we apply the same patch that you have applied to Auth component to the Messaging component?

Related Issue: https://github.com/firebase/firebase-ios-sdk/issues/1357
Related Pull Request: https://github.com/firebase/firebase-ios-sdk/pull/1358

Thanks!

**Comment by chliangGoogle** [comment]
We are working making FIRMessaging compile with app extension. In the meantime, you can remove the FIRMessaging from your app extension target in Podfile. 

Normally you can't receive push notification from app extensions, so FIRMessaging should be installed in your host app even if you want to use notification extensions. Any reason you need to build them inside your app extension app?

**Comment by 5fcgdaeb** [comment]
That is right; one shouldn't ideally need the Messaging component in their extensions. In my case, I have already removed the dependency.

I have created the issue so that Firebase offers a standard behavior across all of its modules.

**Comment by spyroseth** [comment]
Hello. I have the same issue here. In my case, I build a framework that handles push notification using FirebaseMessaging component. Through the notification extension, I want to delegate the methods provided to the framework.

**Comment by paulb777** [comment]
Fixed in the upcoming M30 release by #1503
