### ISSUE TITLE
success while build in simulator but failed while archiving

### ISSUE THREAD

**Issue by ferdinandharmaputra** [firebase/firebase-ios-sdk#1491]
When I am building the app in simulator it works, but when I archive the project to upload, it's showing error

this is the screenshot

<img width="854" alt="screen shot 2018-07-03 at 9 51 11 pm" src="https://user-images.githubusercontent.com/34279128/42256213-1a34ee0c-7f7a-11e8-89f9-458b5746e613.png">

**Comment by paulb777** [comment]
@ferdinandharmaputra This looks like an issue with an Alamofire API and is out of scope for the Firebase issue tracker.
