### ISSUE TITLE
Update source snapshot README for M30 changes

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#1535]
Update the instructions at https://github.com/firebase/firebase-ios-sdk#accessing-firebase-source-snapshots to describe how to handle the `GoogleUtilities` and the `FirebaseAuthInterop` pods.

In the meantime, a workaround is to add those two pods with the appropriate branch specifier.

**Comment by ryanwilson** [comment]
`GoogleUtilities` will be released out of band, closing this issue.
