### ISSUE TITLE
Firestore queries extremly slow on the last 2 weeks

### ISSUE THREAD

**Issue by darkylmnx** [firebase/firebase-ios-sdk#1539]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: _____
  * Firebase SDK version: _____ 5.0.4
  * Firebase Component: _____ (Auth + Firestore)
  * Component version: _____

### [REQUIRED] Step 3: Describe the problem
Queries seems to be extremly slow since the last two weeks, even on small sets of data, this makes the user experience not good enough and also the development experience since firebase doesn't have a "dev env"

![image](https://user-images.githubusercontent.com/1426357/42737460-0bcaeaee-8874-11e8-8e00-69f93c69d3b9.png)

#### Steps to reproduce:
Just try some queries on a collection or document

**Comment by paulb777** [comment]
I don't see anything here indicating an iOS SDK issue. Perhaps, it should be filed to https://github.com/firebase/firebase-js-sdk/issues?

Either way, we'll likely need more information about reproducing the issue.

**Comment by jdimond** [comment]
We deployed a fix to the backends today that should bring down querying times. Please re-open the issue if it's still reproducible.
