### ISSUE TITLE
iOS8  [NSLock updateTraceWithCurrentSession]: unrecognized selector sent to instance 0x7fa0f8cf5b50

### ISSUE THREAD

**Issue by zeqinjie** [firebase/firebase-ios-sdk#1540]
[READ] Step 1: Are you in the right place?
YES

[REQUIRED] Step 2: Describe your environment
Xcode version: 9.3
Cocopod update : 
 Installing Firebase 5.4.0 (was 5.2.0)
Installing FirebaseCore 5.0.5 (was 5.0.3 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)
Installing FirebaseMessaging 3.0.3 (was 3.0.2 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)
Installing FirebasePerformance 2.0.1 (was 2.0.0 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)

[REQUIRED] Step 3: Describe the problem
on iOS8  crash after  update the SDK version

Crash Log:
[NSLock updateTraceWithCurrentSession]: unrecognized selector sent to instance 0x7fa0f8cf5b50

**Comment by morganchen12** [comment]
Can you share the full stack trace?

**Comment by zeqinjie** [comment]
@morganchen12   
<_NSCallStackArray 0x7fe1b6546350>(
0   ???                                 0x000000012501a130 0x0 + 4915831088,
1   houseApp                           0x000000010e3b3c40 main + 0,
2   CoreFoundation                      0x000000011348327c ___forwarding___ + 988,
3   CoreFoundation                      0x0000000113482e18 _CF_forwarding_prep_0 + 120,
4   CoreFoundation                      0x00000001134f3cec __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12,
5   CoreFoundation                      0x00000001133f38a4 _CFXNotificationPost + 2484,
6   Foundation                          0x000000011195f6b8 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66,
7   houseApp                            0x000000010eeddef7 -[FPRSessionManager updateSessionId:] + 225,
8   CoreFoundation                      0x00000001134f3cec __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12,
9   CoreFoundation                      0x00000001133f38a4 _CFXNotificationPost + 2484,
10  Foundation                          0x000000011195f6b8 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66,
11  UIKit                               0x0000000113de6ff3 -[UIApplication _stopDeactivatingForReason:] + 362,
12  UIKit                               0x0000000113dfb905 -[UIApplication _handleNonLaunchSpecificActions:forScene:withTransitionContext:] + 2619,
13  FrontBoardServices                  0x0000000118b002a3 __31-[FBSSerialQueue performAsync:]_block_invoke + 16,
14  CoreFoundation                      0x000000011345953c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12,
15  CoreFoundation                      0x000000011344f285 __CFRunLoopDoBlocks + 341,
16  CoreFoundation                      0x000000011344ea43 __CFRunLoopRun + 851,
17  CoreFoundation                      0x000000011344e486 CFRunLoopRunSpecific + 470,
18  GraphicsServices                    0x00000001194ce9f0 GSEventRunModal + 161,
19  UIKit                               0x0000000113dec420 UIApplicationMain + 1282,
20  houseApp                            0x000000010e3b3caf main + 111,
21  libdyld.dylib                       0x0000000117761145 start + 1
)

**Comment by visumickey** [comment]
This will be fixed in the upcoming release of Firebase Performance.

**Comment by ryanwilson** [comment]
Firebase Performance was updated in Firebase 5.5.0.

**Comment by zeqinjie** [comment]
thx
