### ISSUE TITLE
SMS Verification message not customizable

### ISSUE THREAD

**Issue by businessengine** [firebase/firebase-ios-sdk#1559]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.4
  * Firebase SDK version: 5.4.0
  * Firebase Component: Auth
  * Component version: _____

#### Steps to reproduce:

We always got `Your Firebase App verification code is xxx` instead of what we set in the Template setting _%LOGIN_CODE% is your verification code for %APP_NAME%._

Any ideas guys?

**Comment by morganchen12** [comment]
We can use this issue for tracking, but since this isn't an SDK issue, can you file it at our [troubleshooting channel](https://firebase.google.com/support/contact/?category=troubleshooting)?

**Comment by businessengine** [comment]
Thanks @morganchen12 . The support team is working on this matter.
