### ISSUE TITLE
[!] Error installing nanopb - 503 Service Unavailable

### ISSUE THREAD

**Issue by GuilhermeMachado** [firebase/firebase-ios-sdk#156]
Xcode version: 8.3.3
  Firebase SDK version: 4.0.4
  Firebase Product: FirebaseCore (4.0.4)

### The problem

Firebase core has the nanopb as [dependency](https://github.com/CocoaPods/Specs/blob/master/Specs/8/b/d/FirebaseCore/4.0.4/FirebaseCore.podspec.json). When i run pod install command can not clone the repository because it is offline.

[]( http://koti.kapsi.fi)
 
I try with the most actually version of cocoapods (beta3) and 1.2.1 version.

```
[!] Error installing nanopb
[!] /usr/bin/curl -f -L -o /var/folders/31/4qx125qs6wg0k8m8n6fyjsx80000gq/T/d20170727-2933-4u9uhv/file.tgz http://koti.kapsi.fi/~jpa/nanopb/download/nanopb-0.3.8.tar.gz --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   330  100   330    0     0    522      0 --:--:-- --:--:-- --:--:--   522
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 503 Service Unavailable
```

#### Steps to reproduce:

run pod repo update
run pod install

**Comment by devbriguy** [comment]
Also to add if you run `pod update`

**Comment by GuilhermeMachado** [comment]
I already did that to. The big problem is the nanopd repository is offline.

**Comment by paulb777** [comment]
We're working on the issue and hope to have a solution later today. In the meantime, a workaround would be back-revving to Firebase 4.0.3

**Comment by devbriguy** [comment]
No I meant to add as another **step to reproduce**, sorry to confuse.

**Comment by davidair** [comment]
The issue has been addressed with https://github.com/google/nanopb-podspec/commit/d7efa2f0e735c57193a78e0552dd61638b2bbbe2, the nanopb pod should be now available.
