### ISSUE TITLE
fetcherCompletion is assign

### ISSUE THREAD

**Issue by ToFind1991** [firebase/firebase-ios-sdk#1565]
`@property(readonly) GTMSessionFetcherCompletionHandler fetcherCompletion;`

This property is using default assign, so fetcherCompletion will may be released to case a wild pointer and `EXC_BAD_ACCESS` crash.

In the file `FIRStorageDownloadTask.m`, there is a assignment for `fetcherCompletion` :
```
_fetcherCompletion = ^(NSData *data, NSError *error) {
      ......
};
```

And at the end of this scope, there is a fetch: 
```
[self.fetcher beginFetchWithCompletionHandler:^(NSData *data, NSError *error) {
    weakSelf.fetcherCompletion(data, error);
  }];
```
Because this fetch is async, when ` weakSelf.fetcherCompletion` calls, the temporary scope in which fetcherCompletion is assigned has gone. `fetcherCompletion` become a bad memory.

**Comment by paulb777** [comment]
@ToFind1991 Sorry for the delayed response.

Are you seeing a demonstrable issue with this code?

My understanding is that the `weakSelf` takes care of the issue that you're describing. When fetcherCompletion is deallocated along with its containing object, `weakSelf` will be set to nil and the function call will be a no-op.

**Comment by morganchen12** [comment]
To clarify the object being deallocated here isn't self, it's the `fetcherCompletion` closure. This should be `copy` and not `assign`.

**Comment by morganchen12** [comment]
`strong` will do too, but `assign` is hazardous since it doesn't provide any guarantees for ownership or deallocation.

**Comment by andrewehab** [comment]
let downloadImageRef = self.storage.reference().child(uid).child("Profile Picture")
        
        let downloadtask = downloadImageRef.getData(maxSize: 1024 * 1024 * 12) { (data, error) in
            if let data = data {
                let image = UIImage(data: data)
                completion(image ?? UIImage())
            }
            print(error ?? "NO ERROR")
        }
        
        downloadtask.observe(.progress) {[weak self] (snapshot) in
            guard let self = self else {return}
            print(snapshot.progress ?? "NO MORE PROGRESS")
        }
        
        downloadtask.resume()




now it give me the same problem 
and i don't know how to fix it ??

**Comment by BlakeBoxberger** [comment]
It looks like this issue has somehow re-manifested itself. Even with the `copy` attribute, I'm getting EXC_BAD_ACCESS on this exact line.
