### ISSUE TITLE
FCM Token Nil Error code 1003

### ISSUE THREAD

**Issue by jcyu0208** [firebase/firebase-ios-sdk#1573]
### Environment

  * Xcode version: 9.4.1
  * Firebase SDK version: 5.4.0
  * Firebase Component: Messaging
  * Component version: 3.0.3

### Problem

I keep receiving a 1003 Error and always get nil when trying to get the FCM token. I assume that I've setup my APNs correctly and I'm using the correct GoogleService file since I was able to authenticated via Phone Number without seeing the recaptcha. 

Also, none of the delegate's functions get called. 

I tried using `messaging.retrieveFCMToken(forSenderID:) ` and it provided me the fcm token. I used the token I received from the handler to send a message using Firebase Console and I didn't receive anything. However, I tried using another service (PushTry) using the Server Key and the FCM token and I got the notification.

**Important**: My Application setup separates my Firebase dependencies in another Cocoa Touch framework which might be the cause of the problem?

#### Steps to reproduce:

Follow the steps in the guide: 
1. Configure the Firebase App
2. Register for remote notificaitons
3. Set the messaging delegate
4. Add a listener for the Instance ID

#### Relevant Code:

```
InstanceID.instanceID().instanceID { (result, error) in
                if let error = error {
                    print("Error fetching remote instance ID: \(error)")
                } else if let result = result {
                    print("FCM Token: \(result.token)")
                }
```

or

```
Messaging.messaging().fcmToken
```

However, this one returns an FCM Token
```
Messaging.messaging().retrieveFCMToken(forSenderID:)
```

**Comment by chliangGoogle** [comment]
Error 1003 is a upstream error when you try to send a upstream message with empty to address. 
https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/Messaging/NSError%2BFIRMessaging.h#L45

Can you send me your debug log so I can take a look?

**Comment by paulb777** [comment]
Closing for now. Will reopen with a log or more info.
