### ISSUE TITLE
_OBJC_CLASS_$_GULAppEnvironmentUtil

### ISSUE THREAD

**Issue by marinofaggiana** [firebase/firebase-ios-sdk#1585]
`Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GULAppEnvironmentUtil", referenced from:
      objc-class-ref in FirebaseCoreDiagnostics(FIRDiagnostics_afb9975b7573ce8caa0e4380e6bfbe31.o)
  "_OBJC_CLASS_$_GULNetwork", referenced from:
      objc-class-ref in FirebaseCoreDiagnostics(FIRClearcutLogger_45763904baa6658ff86b47cac2ab23e7.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

I use Firebase without CocoaPods Xcode 9.4.1 with Other Linker Flags -Objc as  this guide : https://firebase.google.com/docs/ios/setup#frameworks

Where is the issue ?

Thanks a lot

**Comment by morganchen12** [comment]
Your app is missing the `GoogleUtilities` framework.

**Comment by paulb777** [comment]
@marinofaggiana Are you integrating from the zipfile?  There might have been a packaging failure in creating the 5.4.1 zipfile.

If so, a workaround could be removing FirebaseCoreDiagnostics from the set of libraries added to the project.

@morganchen12 Firebase usage of the GoogleUtilities framework has not released yet.

**Comment by marinofaggiana** [comment]
thanks @paulb777 I have remove FirebaseCoreDiagnostics and the issue is closed, but without FirebaseCoreDiagnostics exists a few future problem ? We use Firebase only for push notification  (Analytics and messaging).

**Comment by paulb777** [comment]
@marinofaggiana There should not be problems for you.

I'll work on publishing a corrected zip in the next day or two so others do not run into the problem and will keep this issue open until then.

**Comment by marinofaggiana** [comment]
Thanks a lot @paulb777 for your job.

**Comment by paulb777** [comment]
The zip has now been updated. The correct version has an `ls -l` size of 455024108.

**Comment by otondin** [comment]
I was in pain for a week with this issue! Thank a lot for the fix @paulb777! I owe you a cup of coffee! 😄 ☕️

**Comment by denis-shienkov** [comment]
Hi guys, 

I'm too faced with this issue then I have upgraded OSX to Sierra 10.13.6 and XCode to 9.4.1 (with previous Sierra 10.12.6 && XCode 9.2 were all fine). 

From where I need to remove the 'FirebaseCoreDiagnostics'? I use only following firebase libraries:

    # Linking for required firebase POD's frameworks.
    FCM_PODS_PATH = $$(GOOGLE_FIREBASE_PODS)
    message("FCM_PODS_PATH = $$FCM_PODS_PATH")

    LIBS += \
        -F$$FCM_PODS_PATH/Messaging \
        -F$$FCM_PODS_PATH/Analytics \
        -framework FirebaseCore \
        -framework FirebaseInstanceID \
        -framework FirebaseMessaging \
        -framework Protobuf

    # Linking for required firebase C++ SDK libraries.
    FCM_SDK_LIBS_PATH = $$(GOOGLE_FIREBASE_SDK)/libs/ios/universal
    message("FCM_SDK_LIBS_PATH = $$FCM_SDK_LIBS_PATH")

    LIBS += \
        -L$$FCM_SDK_LIBS_PATH \
        -lfirebase_app \
        -lfirebase_messaging

so, I don't use the 'FirebaseCoreDiagnostics' at all... 

How to fix this issue?

**Comment by denis-shienkov** [comment]
UPD: Seems I need to add and:

-framework GoogleUtilities

from the Analytics directory... O_o
