### ISSUE TITLE
Cocoapods: Installing 'Firebase/Messaging' together with 'google-cast-sdk' produces a lot of 'Class <XxXXx> is implemented in both' warnings

### ISSUE THREAD

**Issue by ElectroBuddha** [firebase/firebase-ios-sdk#1590]
* Xcode version: 9.4.1
  * Firebase SDK version: 5.4.1
  * Firebase Component: Messaging
  * Component version: 3.0.3

### DESCRIPTION:

When framework  'Firebase/Messaging' (version 3.0.3) is installed together with 'google-cast-sdk' (version 4.3.0), building the app produces massive amount of these messages in debug console: 

`Class GPBInt32Array is implemented in both /[PATH_TO_APP]/Frameworks/Protobuf.framework/Protobuf and /[PATH_TO_APP]/Frameworks/GoogleCast.framework/GoogleCast. One of the two will be used. Which one is undefined.`

This warning is shown for approximately 100 of different classes from Protobuf framework.

#### Steps to reproduce:

Just install these pods in any project:
pod 'Firebase/Messaging'
pod 'google-cast-sdk'

**Comment by morganchen12** [comment]
Looks like GoogleCast packages Protobuf instead of pulling it in via CocoaPods.

**Comment by morganchen12** [comment]
Filed b/111884913 to the GoogleCast folks.

**Comment by wilhuff** [comment]
It looks like https://issuetracker.google.com/72219403 was already filed about this issue and we're just waiting on a new release of the cast SDK.
