### ISSUE TITLE
Support for Codable JSON parsing with JSONDecoder

### ISSUE THREAD

**Issue by SheldonWangRJT** [firebase/firebase-ios-sdk#1594]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: _Version 9.4.1 (9F2000)_
  * Firebase SDK version: __4.11.0___
  * Firebase Component: __Database___ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: _____

### [REQUIRED] Step 3: Describe the problem
Lack of data in the response to support for `Codable` JSON parsing with `JSONDecoder`. 

The whole idea of parsing response from firebase / database is not that smart any more. I think it will be super helpful if we can access the `data` as a property under `snapshot.value` or just from `snapshot` to allow us to use Codable protocol for easier JSON parsing.

#### Steps to reproduce:
NA

#### Relevant Code:
```
Database.database().reference()
            .child("path")
            .observeSingleEvent(of: .value) { (snapshot) in
                guard let value = snapshot.value as? NSArray else { return }
            print(value) // cannot easily parse the value (Array of dictionary into Array of Object)
        }
```

**Comment by paulb777** [comment]
Closing for staleness.

Firestore now has codable support.

We're not likely to add support in RTDB, although we would still consider a PR.
