### ISSUE TITLE
Deleted App's Database Being Returned

### ISSUE THREAD

**Issue by dylancopeland** [firebase/firebase-ios-sdk#160]
After getting a database reference and deleting the associated app, Firebase will always return the same instance to the initial database for an app's lifecycle.

The issue lies within `FIRDatabase`: https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/Database/Api/FIRDatabase.m#L122.

The `instances` array will hold an outdated reference of the database. The outdated database can point to a then deleted `FIRApp`. Perhaps when a `FIRApp` is deleted, any databases it owns should be removed from the `instances` array.

  * Xcode version: Version 8.3.3 (8E3004b)
  * Firebase SDK version: 4.0.4
  * Library version: 4.0.0
  * Firebase Product: database

#### Steps to reproduce:

1.) Create a Firebase app with a specific name.
2.) Authenticate against the app.
3.) Get a Firebase database reference.
4.) Sign out.
5.) Delete the Firebase app.
6.) Create a Firebase app using the same name used in step 1.
7.) Authenticate against the Firebase app created in step 6.
8.) Get a Firebase database reference with `databaseForApp:` using the app created in step 6.

The final Firebase database reference's app will actually point to the app created in step 1. This causes the database's authentication chain to break. Since the user is authenticated with the app created in step 6, the user will not be able to use the database.

**Comment by ryanwilson** [comment]
Sorry, was on vacation the past week. Getting back to this now!

**Comment by ryanwilson** [comment]
@dylancopeland the PR should fix the issue but I wanted to check - what's the use case / reason for deleting `FIRApp` and recreating it?

**Comment by dylancopeland** [comment]
@ryanwilson Awesome, thank you!

Our data is sharded across a few Firebase projects. We were hoping to delete an old `FIRApp` that a user may have used from a previous session. The whole point of that was just to free up local & Firebase resources.

**Comment by ryanwilson** [comment]
Okay great, thanks for the reply. I created a new issue (#202) to investigate some of the other SDKs as well to make sure we're cleaning up properly.

For your use case, I'd just suggest making sure that when you delete the `FIRApp` ensure that all existing instances are cleared out (any properties, local variables, etc).

Thanks for reporting this! I'll close it when #194 is closed.

**Comment by ryanwilson** [comment]
Thanks again for reporting, @dylancopeland.
