### ISSUE TITLE
Sign up with email crashes the app

### ISSUE THREAD

**Issue by den330** [firebase/firebase-ios-sdk#1615]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: _9.4.1____
  * Firebase SDK version: __4.1.1___
  * Firebase Component: _FirebaseAuthUI____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: _____

### [REQUIRED] Step 3: Describe the problem
Sign up with email crashes the app right after you click "save" on "create account"
Sign up with Facebook and gmail account are working fine.
#### Steps to reproduce:

```
2018-08-01 08:41:11.568072-0400 spc-ios[48668:3868537] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[FIRAuthDataResult profileChangeRequest]: unrecognized selector sent to instance 0x604000a326c0'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010d7e51e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x000000010ce82031 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010d866784 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010d767898 ___forwarding___ + 1432
	4   CoreFoundation                      0x000000010d767278 _CF_forwarding_prep_0 + 120
	5   spc-ios                             0x0000000103f453b4 __75-[FUIPasswordSignUpViewController signUpWithEmail:andPassword:andUsername:]_block_invoke + 115
	6   spc-ios                             0x0000000103efa770 __64-[FIRAuth signInFlowAuthDataResultCallbackByDecoratingCallback:]_block_invoke.791 + 48
	7   libdispatch.dylib                   0x000000010eae97ab _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x000000010eaea7ec _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x000000010eaf58cf _dispatch_main_queue_callback_4CF + 628
	10  CoreFoundation                      0x000000010d7a7c99 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	11  CoreFoundation                      0x000000010d76bea6 __CFRunLoopRun + 2342
	12  CoreFoundation                      0x000000010d76b30b CFRunLoopRunSpecific + 635
	13  GraphicsServices                    0x00000001102d1a73 GSEventRunModal + 62
	14  UIKit                               0x000000010abcb057 UIApplicationMain + 159
	15  spc-ios                             0x0000000103e18e57 main + 55
	16  libdyld.dylib                       0x000000010eb67955 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by ryanwilson** [comment]
Hi @den330,

Firebase 4.1.1 was released back in August of 2017 and the Auth API has been updated quite a bit since then. Are you able to update Firebase and see if this issue still persists?

**Comment by bgolson** [comment]
I'm having this same crash using Firebase 5.9.0 with FirebaseAuth 5.0.4 & FirebaseUI 4.1.1

Only crashes when registering with email/password (using AuthUI)

'NSInvalidArgumentException', reason: '-[FIRAuthDataResult profileChangeRequest]: unrecognized selector sent to instance 0x6000031c93c0'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010c38129b __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010b91d735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010c39ffa4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010c385fb6 ___forwarding___ + 1446
	4   CoreFoundation                      0x000000010c387e88 _CF_forwarding_prep_0 + 120
	5   appname                     0x0000000106556ae4 __75-[FUIPasswordSignUpViewController signUpWithEmail:andPassword:andUsername:]_block_invoke + 115
	6   appname                     0x0000000106509d20 __64-[FIRAuth signInFlowAuthDataResultCallbackByDecoratingCallback:]_block_invoke.748 + 48
	7   libdispatch.dylib                   0x000000010d4ae5d1 _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x000000010d4af63e _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x000000010d4bc9d6 _dispatch_main_queue_callback_4CF + 1541
	10  CoreFoundation                      0x000000010c2e47f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	11  CoreFoundation                      0x000000010c2dee86 __CFRunLoopRun + 2342
	12  CoreFoundation                      0x000000010c2de221 CFRunLoopRunSpecific + 625
	13  GraphicsServices                    0x000000010f77a1dd GSEventRunModal + 62
	14  UIKitCore                           0x0000000115552115 UIApplicationMain + 140
	15  appname                     0x00000001064841b4 main + 68
	16  libdyld.dylib                       0x000000010d525551 start + 1
	17  ???                                 0x0000000000000001 0x0 + 1
)

**Comment by paulb777** [comment]
@bgolson This looks a bit different.  Would you create a new issue?

**Comment by bgolson** [comment]
The issue, exception and stack trace are identical. @den330 did you find a solution?

**Comment by den330** [comment]
@bgolson  Yes, I used an old version Firebase SDK.  The issue was gone right after I updated the SDK to the latest version.

**Comment by bgolson** [comment]
@den330 thanks so much for following up! For some reason 'pod update' didn't actually update Firebase. For anyone else with the issue, I had to do the following:

1. remove the firebase references from the podfile
2. pod install
3. add back the firebase references
4. pod install

Now all is well. Thanks again!
