### ISSUE TITLE
Dynamic links not working on first launch

### ISSUE THREAD

**Issue by sjavora** [firebase/firebase-ios-sdk#1616]
* Xcode version: 9.4
  * Firebase SDK version: 5.4.1
  * Firebase Component: FirebaseDynamicLinks
  * Component version: 3.0.1

iOS 11.4

1. tap on dynamic link
2. app store opens
3. install app through Xcode
4. App Delegate `application(_:open:options:)` is called
5. `url` is always `<scheme>://google/link/?dismiss=1&is_weak_match=1`
6. Tried switching cellular/wifi, tried different devices, tried downgrading Firebase - still not working
7. When opening the link through `application(_:continue:restorationHandler:)`, everything always works fine.

**Comment by nikeshakya** [comment]
this issue is same as https://github.com/firebase/firebase-ios-sdk/issues/1403 
it has been open for so long...
why aren't you guys taking care of this ?
this is critical...!!!!

**Comment by nikeshakya** [comment]
@ryanwilson when will fix for this come ?
been waiting for months now...

**Comment by dmandar** [comment]
@nikeshakya The openUrl option is to be used only on iOS 8 and lower - can you confirm you are testing with the same?. Also, please make sure you have followed all steps mentioned here: https://firebase.google.com/docs/dynamic-links/ios/receive and reopen bug if it still reproes for you. Thanks.

**Comment by nikeshakya** [comment]
@ryanwilson @dmandar any update on this issue ?

**Comment by yahmad** [comment]
@dmandar We are also following the steps in the documentation, but having the same issue.
Only difference is we don't support iOS 8, so we are checking if there is a dynamic link present directly in the iOS 9 `open url` function, rather than passing it through to the function taking `sourceApplication` as a param.

Are there any other steps required to handle dynamic links coming through the store? They work fine once the app is already installed.

**Comment by yahmad** [comment]
We are on Firebase v5.4. It looks like v5.5 has some issues resolved for Dynamic Links, though can't tell what those are. From the sounds of it, the backend fix shouldn't need the latest version of the Firebase SDK?

**Comment by yahmad** [comment]
Update: Turns out we were just not handling custom url scheme URL's correctly - debugging our live build helped discover the issue. Apologies for any inconvenience!

(Still using v5.4 but should work fine now.)

**Comment by morganchen12** [comment]
@yahmad, is there an area in our docs that lead to your mishandling of the URLs?

**Comment by yahmad** [comment]
Honestly, it was probably just an oversight whilst trying to rapidly implement dynamic links for the first time. 😬 

I don't think the documentation necessarily needs updated. This code had been replicated without having implementing the handling of the deep link:

    func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
      if let dynamicLink = DynamicLinks.dynamicLinks().dynamicLink(fromCustomSchemeURL: url) {
        // Handle the deep link. For example, show the deep-linked content or
        // apply a promotional offer to the user's account.
        // ...
        return true
      }
      return false
    }
