### ISSUE TITLE
FirebaseApp.configure() memory leak

### ISSUE THREAD

**Issue by AndriyGo** [firebase/firebase-ios-sdk#1636]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.4.1
  * Firebase SDK version: 5.5.0
  * Firebase Component: Core
  * Component version: 5.1.0

#### Steps to reproduce:

I have added `FirebaseApp.configure()` to `didFinishLaunchingWithOptions`. Now if I push another view controller I get the following leak:

<img width="1025" alt="screen shot 2018-08-05 at 16 17 36" src="https://user-images.githubusercontent.com/7107815/43686325-35f9ca2a-98cc-11e8-965e-0f65cb10ac42.png">

If I do not move from the first view controller which is presented, the leak does not occur.

#### Relevant Code:

You can check the [sample project which I created on GitHub](https://github.com/AndriyGo/firebaseMemoryLeak). For security reasons, I omitted GoogleService-Info.plist, so you'll need to add it prior to running the project.

For some reason, instruments call tree is not populated for this trial project in the same way as for my original project, but the leak is still there and it is the same leak. Also, I've had some runs when the leak would not occur. From my experience, to reproduce it you need:

1) Attach to target and wait for the first leaks check which should be successful
2) Now click on "Trigger leak button". The second check should fail.

**Comment by baolocdo** [comment]
I could reproduce this. Tracked internally at b/112265892. I have a fix for it and will have the fix in the next release

**Comment by baolocdo** [comment]
The fix should be released in Analytics 5.1.1. Please update and let us know whether you still see the leak. Thanks for reporting.
