### ISSUE TITLE
Cannot build app for distribution due to MLVisionTextModel not being bitcode compatible

### ISSUE THREAD

**Issue by joaomelo81** [firebase/firebase-ios-sdk#1643]
Environment:

  * Xcode version: 9.4 (9F1027a)
  * Firebase SDK version: 5.5.0
  * Firebase Component: MLVisionTextModel
  * Component version: 5.5.0 ?

Problem description:

When trying to build for app submission, with "Enable Bitcode" setting = true, I get this error and can't build for release.

ld: '/Firebase/MLVisionTextModel/TextDetector.framework/TextDetector' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Firebase/MLVisionTextModel/TextDetector.framework/TextDetector' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

NOTE: I was able to build app for submission with Firebase 5.4.0 and "Enable Bitcode" setting = true

Looks like the issue here is that you guys are not building the MLVisionTextModel Framework with the -fembed-bitcode flag. Could you please include it in the very next beta release?

**Comment by morganchen12** [comment]
Tracked by b/112281263 internally.

**Comment by bcdj** [comment]
Hi joaomelo81,

Have you tried to build the following Quick Start mlvision demo app with bitcode enabled?:

https://github.com/firebase/quickstart-ios/tree/master/mlvision

You can clone the above sample app using:

git clone https://github.com/firebase/quickstart-ios.git

I've tried building that app with the latest Firebase 5.5.0 release and bitcode enabled.  The app builds and runs on-device text detection without any issue.

**Comment by bcdj** [comment]
My environment is:

Xcode version: 9.3.1 (9E501)
Firebase SDK version: 5.5.0
Firebase Component: MLVisionTextModel
Component version: 0.11.0

**Comment by morganchen12** [comment]
@joaomelo81, I wasn't able to reproduce this by building or archiving the quickstart app with bitcode enabled. Can you try running `pod deintegrate` and deleting your CocoaPods cache and then re-running `pod install`?

**Comment by joaomelo81** [comment]
Indeed works when building the app sample you mentioned with Bit code enabled. However it uses CocoaPods for integration with the Firebase. In my case, my solution is integrating Firebase without CocoaPods. I've downloaded the .zip file containing the latest Firebase SDK 5.5.0 and manually integrated with my project. Looks like the MLVisionTextModel.framework (v.0.11.0) within the .zip file was not built with the -fembed-bitcode flag since I was able to integrate the MLVisionTextModel.framework v.0.10.0 within the Firebase SDK 5.3.0 zip file.
Anyway, thanks for your attention!

**Comment by joaomelo81** [comment]
BTW: I've downloaded the Firebase SDK .zip file from here: https://firebase.google.com/download/ios

**Comment by joaomelo81** [comment]
@morganchen12 could you please update the internal ticket b/112281263 with the information I've provided? My apologies for not mentioning earlier that I was not using CocoaPods integration.

**Comment by morganchen12** [comment]
Updated. Can you quickly check the checksums for the `TextDetector` framework downloaded via CocoaPods and the same framework extracted from the .zip file? IIRC they should be the same binary.

**Comment by paulb777** [comment]
Thanks for your persistence @joaomelo81 in working on this issue with us. We've discovered an issue packaging the GoogleMobileVision *Detector frameworks and are working on a solution. 

In the meantime, a workaround is using the frameworks extracted from the CocoaPods distribution instead of the zip distribution.

**Comment by bcdj** [comment]
We have released a new version of the zip file.  Please download the latest version, Firebase SDK version 5.6.0, from [https://firebase.google.com/download/ios](https://firebase.google.com/download/ios) to see if the issue is fixed.
