### ISSUE TITLE
Memory leak in [RCNConfigFetch URLSessionDataTaskWithContent:completionHandler:]

### ISSUE THREAD

**Issue by marat643** [firebase/firebase-ios-sdk#1647]
### [READ] Step 1: Are you in the right place?
YES

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.4.1
  * Firebase SDK version: 5.4.1
  * Firebase Component: FirebaseRemoteConfig 
  * Component version: 3.0.0

### [REQUIRED] Step 3: Describe the problem
Memory leak in [RCNConfigFetch URLSessionDataTaskWithContent:completionHandler:]
(retain cycle)
![screen shot 2018-08-07 at 11 07 51](https://user-images.githubusercontent.com/2828034/43777808-2b11552c-9a54-11e8-87d2-e9a6ff6febcb.png)

#### Steps to reproduce:
Executing Firebase config initialization and fetching of remote config data

#### Relevant Code:

In application:didFinishLaunchingWithOptions:
[FIRApp configure];
 self.remoteConfig = [FIRRemoteConfig remoteConfig];
 FIRRemoteConfigSettings *remoteConfigSettings = [[FIRRemoteConfigSettings alloc] initWithDeveloperModeEnabled:YES];
 self.remoteConfig.configSettings = remoteConfigSettings;

 long expirationDuration =  3600;
    __weak typeof (self)weakSelf = self;
    [self.remoteConfig fetchWithExpirationDuration:expirationDuration completionHandler:^(FIRRemoteConfigFetchStatus status, NSError *error) {
        __strong typeof (weakSelf) strongSelf = weakSelf;
        if (status == FIRRemoteConfigFetchStatusSuccess) 
            [strongSelf.remoteConfig activateFetched];
    }];

**Comment by morganchen12** [comment]
This looks like an issue that was reported [here](https://github.com/firebase/quickstart-ios/issues/488) and subsequently fixed, but has not yet been released. @chliangGoogle can you make sure this makes its way into M31?

**Comment by chliangGoogle** [comment]
I think this has just released in M30.

**Comment by marat643** [comment]
Yes, 
Thank you very much, it solved the issue, there is another leak in **[APMUserDefaults objectForKey:]**, but I saw that you are handling it in another opened issue, so I'll wait for the next release.

Thank you once again :)

**Comment by edwardmp** [comment]
I concur that there still is another leak in `[APMUserDefaults objectForKey:]`
