### ISSUE TITLE
Move `GULLogger` to `os_log` for iOS 10+

### ISSUE THREAD

**Issue by ryanwilson** [firebase/firebase-ios-sdk#1650]
Currently we use `asl_log` for all logging within `GULLogger`, but it's deprecated. `os_log` was introduced in iOS 10 as a faster and more robust logging solution.

We should move to `os_log` for all iOS versions above iOS 10, and use the old `asl_log` for iOS 8 and 9 until we drop support for those versions.

**Comment by morganchen12** [comment]
Unassigning bstpierr since he no longer works on Firebase.

**Comment by paulb777** [comment]
Alternative would be to directly use os_log from the product SDKs and deprecate FIRLogger and GULLogger.

First step will be to review https://developer.apple.com/documentation/os/logging and come up with a design

**Comment by mortenbekditlevsen** [comment]
Just providing another alternative - in case running on non-Darwin platforms were a goal - and for the frameworks that are already in Swift. :-)

https://github.com/apple/swift-log

Which could then on Darwin platforms be used to log to os_log through:

https://github.com/chrisaljoudi/swift-log-oslog
And on other platforms, another logging client could be injected. 

Just a thought   😊

**Comment by paulb777** [comment]
Deprioritizing for Firebase 10 in favor of thinking about a logging strategy that is Swift first
