### ISSUE TITLE
Firestore crash when setting a document

### ISSUE THREAD

**Issue by alexichristakis** [firebase/firebase-ios-sdk#1661]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.4.1
  * Firebase SDK version: 5.3.0
  * Firebase Component: Firestore
  * Component version: 0.12.4

### [REQUIRED] Step 3: Describe the problem
App crashes upon setting a document to firestore. Xcode logs the following error:
```
2018-08-08 14:04:23.002244-0700 sesh[11461:139254] *** Assertion failure in -[GRPCHost setTLSPEMRootCerts:withPrivateKey:withCertChain:error:], /Users/alexic/react-native/sesh/ios/Pods/gRPC/src/objective-c/GRPCClient/private/GRPCHost.m:179
2018-08-08 14:04:23.026151-0700 sesh[11461:139254] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not read gRPCCertificates.bundle/roots.pem. This file, with the root certificates, is needed to establish secure (TLS) connections. Because the file is distributed with the gRPC library, this error is usually a sign that the library wasn't configured correctly for your project. Error: Error Domain=NSCocoaErrorDomain Code=258 "The file name is invalid."'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000116af41e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x000000011557e031 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000116af9472 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00000001109b5652 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   sesh                                0x000000010f0ac968 -[GRPCHost setTLSPEMRootCerts:withPrivateKey:withCertChain:error:] + 744
	5   sesh                                0x000000010f0ad650 -[GRPCHost newChannel] + 192
	6   sesh                                0x000000010f0ac399 -[GRPCHost unmanagedCallWithPath:serverName:timeout:completionQueue:] + 281
	7   sesh                                0x000000010f0aff71 -[GRPCWrappedCall initWithHost:serverName:path:timeout:] + 417
	8   sesh                                0x000000010f0a967f -[GRPCCall startCallWithWriteable:] + 223
	9   sesh                                0x000000010f0a9a99 -[GRPCCall startWithWriteable:] + 601
	10  sesh                                0x000000010ec9e936 -[FSTStream resumeStartWithToken:] + 1478
	11  sesh                                0x000000010eca69da ___ZZ31-[FSTStream startWithDelegate:]ENK3$_0clEN8firebase9firestore4util8StatusOrINS1_4auth5TokenEEE_block_invoke + 42
	12  sesh                                0x000000010ebac6d4 _ZZ51-[FSTDispatchQueue dispatchAsyncAllowingSameQueue:]ENK3$_2clEv + 36
	13  sesh                                0x000000010ebac69d _ZNSt3__128__invoke_void_return_wrapperIvE6__callIJRZ51-[FSTDispatchQueue dispatchAsyncAllowingSameQueue:]E3$_2EEEvDpOT_ + 45
	14  sesh                                0x000000010ebac469 _ZNSt3__110__function6__funcIZ51-[FSTDispatchQueue dispatchAsyncAllowingSameQueue:]E3$_2NS_9allocatorIS2_EEFvvEEclEv + 41
	15  sesh                                0x000000010eba8b7b _ZNKSt3__18functionIFvvEEclEv + 123
	16  sesh                                0x000000010eb4516c _ZN8firebase9firestore4util10AsyncQueue15ExecuteBlockingERKNSt3__18functionIFvvEEE + 476
	17  sesh                                0x000000010eb47af7 _ZZN8firebase9firestore4util10AsyncQueue4WrapERKNSt3__18functionIFvvEEEENK3$_0clEv + 39
	18  sesh                                0x000000010eb47abd _ZNSt3__128__invoke_void_return_wrapperIvE6__callIJRZN8firebase9firestore4util10AsyncQueue4WrapERKNS_8functionIFvvEEEE3$_0EEEvDpOT_ + 45
	19  sesh                                0x000000010eb47879 _ZNSt3__110__function6__funcIZN8firebase9firestore4util10AsyncQueue4WrapERKNS_8functionIFvvEEEE3$_0NS_9allocatorISB_EES7_EclEv + 41
	20  sesh                                0x000000010eba8b7b _ZNKSt3__18functionIFvvEEclEv + 123
	21  sesh                                0x000000010eb559f1 _ZZN8firebase9firestore4util8internal13DispatchAsyncEPU28objcproto17OS_dispatch_queue8NSObjectONSt3__18functionIFvvEEEENK3$_0clEPv + 33
	22  sesh                                0x000000010eb559c8 _ZZN8firebase9firestore4util8internal13DispatchAsyncEPU28objcproto17OS_dispatch_queue8NSObjectONSt3__18functionIFvvEEEEN3$_08__invokeEPv + 24
	23  libdispatch.dylib                   0x000000011833b7ec _dispatch_client_callout + 8
	24  libdispatch.dylib                   0x0000000118343be5 _dispatch_queue_serial_drain + 1305
	25  libdispatch.dylib                   0x00000001183444fa _dispatch_queue_invoke + 328
	26  libdispatch.dylib                   0x0000000118340344 _dispatch_queue_override_invoke + 726
	27  libdispatch.dylib                   0x000000011834736c _dispatch_root_queue_drain + 664
	28  libdispatch.dylib                   0x0000000118347076 _dispatch_worker_thread3 + 132
	29  libsystem_pthread.dylib             0x0000000118866169 _pthread_wqthread + 1387
	30  libsystem_pthread.dylib             0x0000000118865be9 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

#### Relevant Code:
Setting any document results in this error and crashes the app.

**Comment by wilhuff** [comment]
You've managed to build gRPC without including its certificate bundle. This has nothing to do with Firestore specifically, but how your Xcode project is configured. If you're using Cocoapods this should just work.

If you're building with Carthage, you should follow our instructions here: https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md

**Comment by alexichristakis** [comment]
I am using Cocoapods, any idea as to how it could have been misconfigured? I tried deleting my pods folder and reinstalling my dependencies and it still doesn't work.

**Comment by alexichristakis** [comment]
or--how can i configure it correctly

**Comment by wilhuff** [comment]
In general with cocoapods you shouldn't have to do anything. Make sure you're using the workspace and not your original project and everything should be good to go. Within the workspace and in the Pods project you should see that the gRPC target has a build phase that includes copying the bundle.

![screen shot 2018-08-08 at 2 22 34 pm](https://user-images.githubusercontent.com/10249104/43865185-ae59def0-9b16-11e8-9571-c9fc55c61a15.png)

**Comment by alexichristakis** [comment]
Mine actually doesn't have that phase:
![Uploading Screen Shot 2018-08-08 at 2.27.33 PM.png…]()

**Comment by TwistedMinda** [comment]
I was so happy to see that you are in the exact same state as I am...
Was so disappointed to see no response :(

I've been searching all day long to make that gRPC's gRPCCertificates.bundle build in the directory with the other Pods...

**Comment by paulb777** [comment]
@TwistedMinda For static library pod installations, the resource copy happens in the app build phase instead of the Pod build phase -

![screen shot 2018-11-01 at 1 10 45 pm](https://user-images.githubusercontent.com/73870/47876905-ba69c080-ddd7-11e8-8df3-56d703564241.png)

**Comment by TwistedMinda** [comment]
Yes I know that for sure!

But still the file "$(PODS_CONFIGURATION_BUILD_DIR)/gRPC/gRPCCertificates.bundle" can't be found because it is created in my : Staging-iphoneos/ instead of Release-iphoneos/, and this is the only file doing that, all my other Pods build as I want in my Release-iphoneos/

therefore "$(PODS_CONFIGURATION_BUILD_DIR)", which points towards my Release-iphoneos/, won't find the Staging-iphoneos/gRPC/gRPCCertificates.bundle...

And i'm stuck here. I have no way to choose where GRPC will "pop" the certificate.bundle

Help me please

**Comment by paulb777** [comment]
@TwistedMinda This sounds more like an issue with your particular project or perhaps CocoaPods usage or installation than with Firebase. Your description might be sufficient to get an answer on stackoverflow. 

Either way, you may to share a reproducible example to get more help.

**Comment by TwistedMinda** [comment]
Well, finally I got it to work, I was missing the part of creating a new scheme, I was only creating a new build configuration and was not enough, but I still have the same problem as the creator of this conversation had...

It crashes whenever i call firebase.firestore(), but NOT when i call firebase.messaging(), this must be a Firebase issue, no?

Thanks again for your answers, i feel less alone in this desperate situation!
