### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by tbaranes** [firebase/firebase-ios-sdk#1663]
I was wondering if it would be possible to add macOS support to the project? It doesn't seems to complex since some developers made working [example](https://github.com/tabvn/fireshot) just by making a custom pod spec.

Is there a reason that it has been added yet?

**Comment by tbaranes** [comment]
Duplicate of #1294

**Comment by paulb777** [comment]
@tbaranes In case you missed it, see https://github.com/firebase/firebase-ios-sdk#macos-and-tvos
