### ISSUE TITLE
Release 5.5 on Carthage

### ISSUE THREAD

**Issue by fotiDim** [firebase/firebase-ios-sdk#1664]
Carthage only fetches 5.4 for now. Please publish it for Carthage. Unfortunately CocoaPods is too bloated to use these days.

**Comment by paulb777** [comment]
@fotiDim Thanks for the request.

The Carthage distribution is still experimental and will occasionally lag the CocoaPods and zip releases. Currently, Carthage is still at 5.4.0 versus 5.5.0 for the official releases. I'm hoping to get Carthage back in sync within the next week.

**Comment by paulb777** [comment]
A Carthage distribution for Firebase 5.6.0 has been published. See https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md for usage details.
