### ISSUE TITLE
Automated builds fail after OTHER_CFLAGS got deleted from Podspec on newer FirebaseCore versions

### ISSUE THREAD

**Issue by puelocesar** [firebase/firebase-ios-sdk#1687]
### Describe your environment

  * Xcode version: 9
  * Firebase SDK version: 5.5.0
  * Firebase Component: Core
  * Component version: '5.1.0'

### Describe the problem

Automated builds fail after OTHER_CFLAGS got deleted from Podspec on newer FirebaseCore versions

#### Steps to reproduce:

Add `pod 'FirebaseCore'` to your Podfile, run `pod install`. Building on Xcode works fine, but automated archive is broke since commit 77227f58a03ac1383237f7239a337a7c061b5227

#### Relevant Code:

I also commented on the exact commit that broke my automated builds: https://github.com/firebase/firebase-ios-sdk/commit/77227f58a03ac1383237f7239a337a7c061b5227#diff-9b05a5d46c246c52a9f0757aa5c8b24e

```

[08:40:02]: ▸ ❌  /usr/local/var/buildkite-agent/builds/cimini-2.local-1/picmonkey/mobile-pic-ios/ios/Piote/Pods/FirebaseCore/Firebase/Core/FIRVersion.m:18:2: "Firebase_VERSION is not defined: add -DFirebase_VERSION=... to the build invocation"
--
  | [08:40:02]: ▸ #error "Firebase_VERSION is not defined: add -DFirebase_VERSION=... to the build invocation"
  | [08:40:02]: ▸ ^
  | [08:40:02]: ▸ ❌  /usr/local/var/buildkite-agent/builds/cimini-2.local-1/picmonkey/mobile-pic-ios/ios/Piote/Pods/FirebaseCore/Firebase/Core/FIRVersion.m:22:2: "FIRCore_VERSION is not defined: add -DFIRCore_VERSION=... to the build invocation"
  | [08:40:02]: ▸ #error "FIRCore_VERSION is not defined: add -DFIRCore_VERSION=... to the build invocation"
  | [08:40:02]: ▸ ^
  | [08:40:02]: ▸ ** ARCHIVE FAILED **
  | [08:40:02]: ▸ The following build commands failed:
  | [08:40:02]: ▸ CompileC /Users/admin/Library/Developer/Xcode/DerivedData/Piote-dkpcuujaqhmvtobsjasinskwffbc/Build/Intermediates.noindex/ArchiveIntermediates/Piote/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/FirebaseCore.build/Objects-normal/armv7/FIRVersion.o FirebaseCore/Firebase/Core/FIRVersion.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler

```

My makefile will run:
`xcodebuild -allowProvisioningUpdates -exportArchive -exportOptionsPlist export_testfairy.plist -archivePath archive-build/Piote.xcarchive -exportPath archive-build/Piote-adhoc`

**Comment by paulb777** [comment]
@puelocesar Thanks for the analysis and the report. I suspect that the failure stems from a setting in your project. What is happening with `GCC_PREPROCESSOR_DEFINITIONS`? Perhaps a `$inherited` is missing?

Are you able to share a reproducible example? Or at least `export_testfairy.plist`?

**Comment by paulb777** [comment]
Will reopen with more information

**Comment by puelocesar** [comment]
Yes, I have an `$(inherited)` in `GCC_PREPROCESSOR_DEFINITIONS`, otherwise it would fail when building in Xcode. Right now I'm using the older version of Firebase and it's fine. It really only stopped working after that commit
