### ISSUE TITLE
Missing frameworks after update from 5.4.0 to 5.6.0

### ISSUE THREAD

**Issue by josemssilva** [firebase/firebase-ios-sdk#1701]
* Xcode version: 9.4.1
  * Firebase SDK version: 5.6.0 (updated from 5.4.0)
  * Firebase Component: Messaging
  * Component version: 

Missing `FirebaseNanoPB` and `GoogleToolboxForMac`, and I'm unable to build the project without those. Everything worked great before updating to `5.6.0`

#### Steps to reproduce:

Simply update dependencies using Carthage.

**Comment by paulb777** [comment]
In addition to deleting frameworks that no longer exist, the following new frameworks will always need to be added to the Xcode project:

- GoogleUtilities.framework
- GoogleAppMeasurement.framework
- MeasurementNanoPB.framework

**Comment by Banck** [comment]
@paulb777 Hello!
When I ran "sudo carthage update --platform iOS"
I get this message:
error: unable to open '***/Carthage/Build/iOS/Protobuf.framework/Protobuf': No such file or directory.
As I can see there is Protobuf.framework in Carthage/Build/iOS.
With 5.4.0 all the fine.

**Comment by paulb777** [comment]
@Banck  See https://github.com/firebase/firebase-ios-sdk/issues/9#issuecomment-393339765
