### ISSUE TITLE
Error GTMSessionFetcher unrecognized when login and sign-up

### ISSUE THREAD

**Issue by bank18651** [firebase/firebase-ios-sdk#1718]
#### Describe your environment

  * Swift
  * iOS version: 11.4
  * Firebase (5.6.0)
  * FirebaseAuth (5.0.3)
  * GoogleSignIn (4.1.2)
#### Describe the problem
Currently, The project use   `Firebase (5.0.1), Firebase/Auth (5.0.1), GoogleSignIn (4.1.2` and it working well but after update to `Firebase (5.6.0), FirebaseAuth (5.0.3)` I got the issue.

#### Steps to reproduce:

  Auth.auth().fetchProviders(forEmail: email)
  
#### Observed Results:

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[GTMSessionFetcher setFetcher:forTask:]: unrecognized selector sent to instance 0x7f9952cc5410'
  *** First throw call stack:
(
	0   CoreFoundation                      0x000000010e6811e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x000000010dd1e031 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010e702784 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010e603898 ___forwarding___ + 1432
	4   CoreFoundation                      0x000000010e603278 _CF_forwarding_prep_0 + 120
	5   GTMSessionFetcher                   0x0000000109966cec -[GTMSessionFetcherService fetcherDidBeginFetching:] + 396
	6   GTMSessionFetcher                   0x0000000109941d2d -[GTMSessionFetcher beginFetchMayDelay:mayAuthorize:] + 10845
	7   GTMSessionFetcher                   0x000000010993e260 -[GTMSessionFetcher beginFetchWithCompletionHandler:] + 320
	8   Pomelo                              0x0000000104478a28 -[FIRAuthBackendRPCIssuerImplementation asyncPostToURLWithRequestConfiguration:URL:body:contentType:completionHandler:] + 1000
	9   Pomelo                              0x000000010447bfae -[FIRAuthBackendRPCImplementation postWithRequest:response:callback:] + 1070
	10  Pomelo                              0x0000000104478d46 -[FIRAuthBackendRPCImplementation createAuthURI:callback:] + 294
	11  Pomelo                              0x0000000104477969 +[FIRAuthBackend createAuthURI:callback:] + 121
	12  Pomelo                              0x000000010445ed06 __45-[FIRAuth fetchProvidersForEmail:completion:]_block_invoke + 230
	13  libdispatch.dylib                   0x000000010fe747ab _dispatch_call_block_and_release + 12
	14  libdispatch.dylib                   0x000000010fe757ec _dispatch_client_callout + 8
	15  libdispatch.dylib                   0x000000010fe7dbe5 _dispatch_queue_serial_drain + 1305
	16  libdispatch.dylib                   0x000000010fe7e4fa _dispatch_queue_invoke + 328
	17  libdispatch.dylib                   0x000000010fe7a344 _dispatch_queue_override_invoke + 726
	18  libdispatch.dylib                   0x000000010fe8136c _dispatch_root_queue_drain + 664
	19  libdispatch.dylib                   0x000000010fe81076 _dispatch_worker_thread3 + 132
	20  libsystem_pthread.dylib             0x000000011039f1ca _pthread_wqthread + 1387
	21  libsystem_pthread.dylib             0x000000011039ec4d start_wqthread + 13
)
```

**Comment by morganchen12** [comment]
Looks like you may be missing an `-ObjC` in your `Other Linker Flags` build setting. Are you overriding any CocoaPods default build settings? What version of GTMSessionFetcher are you using?

**Comment by bank18651** [comment]
```
  - GTMOAuth2 (1.1.6):
    - GTMSessionFetcher (~> 1.1)
  - GTMSessionFetcher (1.2.0):
    - GTMSessionFetcher/Full (= 1.2.0)
  - GTMSessionFetcher/Core (1.2.0)
  - GTMSessionFetcher/Full (1.2.0):
    - GTMSessionFetcher/Core (= 1.2.0)
```
Unfortunately, I cannot share the project.

**Comment by morganchen12** [comment]
Can you reproduce this issue in a smaller project and share it?

**Comment by bank18651** [comment]
I try to reproduce with other project but it's not happen.
I will find out the way for reproduce it and update.
Do you have anything to suggest me for this?

**Comment by morganchen12** [comment]
Not sure. It's difficult to diagnose given it shouldn't be an issue in your linker flags. You can try updating your pods to see if there's a newer version of GTMSessionFetcherService or update your CocoaPods rubygem and reinstall your pods.

**Comment by bank18651** [comment]
After updated to Firebase/Auth (5.8.0) I got stuck from this line from fetch providers.
<img width="1167" alt="screen shot 2561-09-17 at 6 42 31 pm" src="https://user-images.githubusercontent.com/5292061/45621210-c0b31000-baa9-11e8-97a8-51e75b28d63c.png">

**Comment by morganchen12** [comment]
Can you share a stack trace at the hang?

**Comment by bank18651** [comment]
`'NSInvalidArgumentException', reason: '-[GTMSessionFetcher setFetcher:forTask:]: unrecognized selector sent to instance 0x7ffce5ccb480'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010bee41e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x000000010b447031 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010bf65784 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010be66898 ___forwarding___ + 1432
	4   CoreFoundation                      0x000000010be66278 _CF_forwarding_prep_0 + 120
	5   GTMSessionFetcher                   0x00000001075d6cec -[GTMSessionFetcherService fetcherDidBeginFetching:] + 396
	6   GTMSessionFetcher                   0x00000001075b1d2d -[GTMSessionFetcher beginFetchMayDelay:mayAuthorize:] + 10845
	7   GTMSessionFetcher                   0x00000001075ae260 -[GTMSessionFetcher beginFetchWithCompletionHandler:] + 320
	8   Pomelo                              0x0000000101ff83b8 -[FIRAuthBackendRPCIssuerImplementation asyncPostToURLWithRequestConfiguration:URL:body:contentType:completionHandler:] + 1000
	9   Pomelo                              0x0000000101ffb93e -[FIRAuthBackendRPCImplementation postWithRequest:response:callback:] + 1070
	10  Pomelo                              0x0000000101ff86d6 -[FIRAuthBackendRPCImplementation createAuthURI:callback:] + 294
	11  Pomelo                              0x0000000101ff72f9 +[FIRAuthBackend createAuthURI:callback:] + 121
	12  Pomelo                              0x0000000101fde686 __45-[FIRAuth fetchProvidersForEmail:completion:]_block_invoke + 230
	13  libdispatch.dylib                   0x000000010d8f47ab _dispatch_call_block_and_release + 12
	14  libdispatch.dylib                   0x000000010d8f57ec _dispatch_client_callout + 8
	15  libdispatch.dylib                   0x000000010d8fdbe5 _dispatch_queue_serial_drain + 1305
	16  libdispatch.dylib                   0x000000010d8fe4fa _dispatch_queue_invoke + 328
	17  libdispatch.dylib                   0x000000010d8fa344 _dispatch_queue_override_invoke + 726
	18  libdispatch.dylib                   0x000000010d90136c _dispatch_root_queue_drain + 664
	19  libdispatch.dylib                   0x000000010d901076 _dispatch_worker_thread3 + 132
	20  libsystem_pthread.dylib             0x000000010de1f1ca _pthread_wqthread + 1387
	21  libsystem_pthread.dylib             0x000000010de1ec4d start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException`

<img width="663" alt="screen shot 2561-09-18 at 10 27 55 am" src="https://user-images.githubusercontent.com/5292061/45662805-8e4af680-bb2d-11e8-8cf6-507a0249f642.png">

**Comment by nonesc** [comment]
I also got this issue.

**Comment by bank18651** [comment]
After update library I got error at `GTMSessionFetcherService.m` line number 438
`Using Firebase (5.9.0)
Using FirebaseABTesting (2.0.0)
Using FirebaseAnalytics (5.2.0)
Using FirebaseAuth (5.0.4)
Using FirebaseAuthInterop (1.0.0)
Using FirebaseCore (5.1.4)
Using GTMOAuth2 (1.1.6)
Using GTMSessionFetcher (1.2.0)
`
<img width="1215" alt="screen shot 2561-10-03 at 11 28 58" src="https://user-images.githubusercontent.com/5292061/46390068-22a58380-c700-11e8-9537-1c2f8f3ab3e4.png">

**Comment by nicopuri** [comment]
I got the same error at the same file. The main difference is that I have 1 target with 2 different Build configurations, it falls only in one configuration. Could it be a Google configuration error?

**Comment by morganchen12** [comment]
@nicopuri can you share a project where it crashes?

**Comment by morganchen12** [comment]
Please comment when you have more information.

**Comment by otiasj** [comment]
I just had the exact same error, it turns out the NewRelic sdk was the culprit.
After removing the NewRelic pod I was able to login using Firebase without crashing.

**Comment by nicopuri** [comment]
Thanks @otiasj , the latest version of NewRelic fixed the issue.
Sorry @morganchen12 for the really late response.

**Comment by Nishant-goibibo** [comment]
> the latest version of NewRelic fixed the issue.

We are getting same issue with firebase and Newrelic. If i commented below line then its working.

[NewRelicAgent startWithApplicationToken:@"AA4ce5739c605560abb2e408f71b8021b6a1928aea"];

**Comment by Nishant-goibibo** [comment]
> Thanks @otiasj , the latest version of NewRelic fixed the issue.
> Sorry @morganchen12 for the really late response.
I am facing the exact same error, it turns out the NewRelic sdk was the culprit.
After removing the below line I was able to login using Firebase without crashing.
 [NewRelicAgent startWithApplicationToken:@<Token>""];

**Comment by siliconprime-manhnguyen** [comment]
The issue still exist in the latest version of NewRelic (6.6.0) and Firebase  (6.1.0) and FirebaseStorage  (3.2.1)

<img width="1281" alt="Screen Shot 2019-06-11 at 11 53 41 AM" src="https://user-images.githubusercontent.com/42996953/59244661-96a90b80-8c3f-11e9-8d41-bf1e09d4badc.png">
