### ISSUE TITLE
Missing or insufficient permissions when adding addSnapshotListener callback.

### ISSUE THREAD

**Issue by henrytkirk** [firebase/firebase-ios-sdk#1719]
* Xcode version: 9.x or 10.x Beta
  * Firebase SDK version: Using FirebaseFirestore (0.13.1)
  * Firebase Component: Firestore (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: ?

### [REQUIRED] Step 3: Describe the problem
I'm having permission denied issues when trying to add a listener to a document. I can create or read the document just fine, except when I add a listener, it immediately returns insufficient permissions.

#### Steps to reproduce:
Code should cover it.

#### Relevant Code:

Security rule:
```
service cloud.firestore {
  match /databases/{database}/documents {
    match /projects/{project} {
      allow create: if exists(/databases/$(database)/documents/users/$(request.auth.uid))
      allow read, write, delete: if request.auth.uid == resource.data.user_id;
    }
  }
}
```
Listener code:
```
    FIRCollectionReference *projectsRef = [self.database collectionWithPath:@"project"];
    FIRDocumentReference *projectRef = [projectsRef documentWithPath:@"my_first_project"];
    [projectRef addSnapshotListener:^(FIRDocumentSnapshot * _Nullable snapshot, NSError * _Nullable error) {
      // Error here always is: Domain=FIRFirestoreErrorDomain Code=7
    }];
```
Error returned in block is "Error Domain=FIRFirestoreErrorDomain Code=7 "Missing or insufficient permissions." UserInfo={NSLocalizedDescription=Missing or insufficient permissions.}"

I can read, create, or update existing projects no problem. Once I tried adding the listener, it failed. Am I doing something wrong?

**Comment by henrytkirk** [comment]
Was a typo on my part! Should have used a constant for the collection name. :)

**Comment by wilhuff** [comment]
Phew! :-)
