### ISSUE TITLE
Push Notification is not working in iOS 10 but yes in iOS 11

### ISSUE THREAD

**Issue by jmorgaz** [firebase/firebase-ios-sdk#1723]
### Describe your environment

  * Xcode version: 9.4
  * Firebase SDK version: Last in CocoaPods
  * Firebase Component: Messaging
  * Component version: Last in CocoaPods

### [REQUIRED] Step 3: Describe the problem

iOS 10.3 device can't receive push notification fired from our custom backend.

#### Steps to reproduce:

First the project has been configured for push notifications and the device FCM is sent and registered in backend properly.

Then there are two scenarios:

a) Push is sended to a token id from the testing Firebase Messaging Console.

- iOS 10.3 devices receive the push (notification is displayed and UNUserNotificationCenterDelegate methods are fired)
 - iOS 11.4 devices receive the push (notification is displayed and UNUserNotificationCenterDelegate methods are fired)

b) Push is sended to a token id from the backend.

- iOS 10.3 devices does not receive the push (notification is not displayed and UNUserNotificationCenterDelegate methods are not fired)
 - iOS 11.4 devices receive the push (notification is displayed and UNUserNotificationCenterDelegate methods are fired)

The code for both iOS versions is the same and the way to manage push notifications in iOS 10 and 11 is the same so we can't find what is wrong.

Thanks.

**Comment by morganchen12** [comment]
What payload are you sending from the backend?

**Comment by jmorgaz** [comment]
{
    "apns": {
        "payload": {
            "aps": {
                "alert": {
                    "title": "You have a new message"
                },
                "mutable-content": 1
            }
        }
    },
    "token": "TOKEN HERE",
    "notification": {
        "title": "You have a new message"
    }
}

**Comment by jmorgaz** [comment]
```
{
  "apns": {
    "payload": {
      "aps": {
        "alert": {
          "title": "You have a new message"
        },
        "mutable-content": 1
      }
    }
  }
}
```

**Comment by StarbuckBG** [comment]
I have the same problem. I am using the old API. I have no idea why but if I send notification to single fcm token it is not working. It is not even displaying the notifications.

**Comment by morganchen12** [comment]
Are you able to send directly through APNs? This will help us isolate whether or not it's an issue in the client or an issue in FCM.

**Comment by jmorgaz** [comment]
@morganchen12 Yes I am able to send through APNs.

**Comment by StarbuckBG** [comment]
Check if Method swizzling is on in the Info.plist. If it is on, turn it off.

**Comment by jmorgaz** [comment]
@StarbuckBG do you mean FirebaseAppDelegateProxyEnabled key?

**Comment by StarbuckBG** [comment]
Yes.

**Comment by jmorgaz** [comment]
We do not have this key in the app info.plist, so, it should be off by default, right?

**Comment by adrivernetta** [comment]
After a lot of testing, we've discovered that for iOS10 at least it's mandatory to send the "body" parameter in the payload when sending a dictionary in the "alert" field. Otherwise, the notification is considered empty by the notifications center and therefore ignores it.

So this payload will not work for iOS10:
```
{
  "apns": {
    "payload": {
      "aps": {
        "alert": {
          "title": "You have a new message"
        },
        "mutable-content": 1
      }
    }
  }
}
```
But this one will:
```
{
  "apns": {
    "payload": {
      "aps": {
        "alert": {
          "title": "You have a new message",
          "body": "Tap to see it"
        },
        "mutable-content": 1
      }
    }
  }
}
```

In iOS11, no body in the alert seem to be fine.

**Comment by morganchen12** [comment]
@jmorgaz swizzling is enabled by default. You can disable it as described in our docs [here](https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in).

**Comment by jmorgaz** [comment]
With the change in the payload we have fix this issue.

Thank you all!
