### ISSUE TITLE
Undefined symbols Carthage approach

### ISSUE THREAD

**Issue by aabanaag** [firebase/firebase-ios-sdk#1745]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.4.1
  * Firebase SDK version: 5.6.0
  * Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: _____

### [REQUIRED] Step 3: Describe the problem
Having issues with building using Firebase with Carthage.

![image](https://user-images.githubusercontent.com/2245822/44592362-de66bf80-a7f2-11e8-8fdc-19a9058fd1a2.png)

#### Steps to reproduce:

Output
![image](https://user-images.githubusercontent.com/2245822/44592271-a6f81300-a7f2-11e8-8b73-612800b512f3.png)

#### Relevant Code:
Here is my Cartfile

```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAuthBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseInvitesBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseFirestoreBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashBinary.json"
```

**Comment by paulb777** [comment]
Hi @aabanaag 

`MeasurementNanoPB.framework` should be added to the included frameworks.

**Comment by aabanaag** [comment]
Thanks! But if there is a document stating which frameworks should be included might be great.
