### ISSUE TITLE
[firebase-talk]importing firebase/app imports all firebase services 

### ISSUE THREAD

**Issue by udielenberg** [firebase/firebase-ios-sdk#1760]
### Describe your environment

  * Firebase SDK version: 5.3.1
  * Firebase Component: Auth / Firestore / app
  * Bundled with Webpack 4
  * React Application (self customized, **not** `create-react-app`

### Describe the problem
I get this warning message: 
When l `import firebase from 'firebase/app'`, I still get all of firebase services, **and not just the `app`**.

![screen shot 2018-08-29 at 12 20 32](https://user-images.githubusercontent.com/39482108/44778650-37817b00-ab86-11e8-9d9a-c3944441fd73.png)

#### Steps to reproduce:
I created this simple app: https://stackblitz.com/edit/react-b1hykn
notice that every few page refreshes you get to see the import imported all firebase services.

Is it a caching problem?

**Comment by paulb777** [comment]
This does not look like a firebase-ios-sdk issue. Perhaps you meant to open an issue at https://github.com/firebase/firebase-js-sdk/issues?
