### ISSUE TITLE
[bug?] leveldb-library incorrect version

### ISSUE THREAD

**Issue by mohonish** [firebase/firebase-ios-sdk#1761]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.0beta4
  * Firebase SDK version: Firebase/Core (5.7.0)
  * Firebase Component: FirebaseFirestore (= 0.13.2) (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 0.13.2

#### Steps to reproduce:

Added `pod 'Firebase/Firestore'` to Podfile and `pod install`.

#### Relevant Code:

For `Firestore-0.13.2` tag again, if you go to file 
`firebase-ios-sdk/Firestore/core/src/firebase/firestore/local/leveldb_util.cc`
note line numbers 33 and 34 as given below:

    if (status.IsNotSupportedError()) return FirestoreErrorCode::Unimplemented;
    if (status.IsInvalidArgument()) return FirestoreErrorCode::InvalidArgument;

The corresponding methods for `IsNotSupportedError()` and `IsInvalidArgument()` have been added since the `1.19` version of leveldb and do not exist in the `1.18` version, and hence throws an error while building the project.

For reference:

Check for `v1.19` the methods exist at line 64 and 67
(https://github.com/google/leveldb/blob/v1.19/include/leveldb/status.h)

Check for `v1.18` the methods are missing
(https://github.com/google/leveldb/blob/v1.18/include/leveldb/status.h)

For `Firestore-0.13.2` tag (latest release) in the `FirebaseFirestore.podspec` the dependency version for `leveldb-library` is listed as `1.18` as below.
`s.dependency 'leveldb-library', '~> 1.18'`
and **hence the above methods are not available.**

Please confirm if I am wrong, and if I need to do anything else to fix the above error. Is this error already accounted for in some upcoming dot release?

**Comment by paulb777** [comment]
@mohonish Thanks for the investigation and report.  It looks like we missed updating the `leveldb-library` dependency version in the FirebaseFirestore.podspec.  We'll get this fixed in the next update. 

In the meantime, you should be able to workaround by updating to version 1.20 of level_db-library. You may need to edit or delete `Podfile.lock` to do so.

**Comment by wilhuff** [comment]
Note that while the version floor is incorrect Firestore has declared a floating dependency on leveldb-library such that CocoaPods should have picked up 1.20. Indeed, my Podfile.lock contains:

```
  - leveldb-library (1.20)
```

Something else is going on here and I don't think #1762 is going to address it.

**Comment by wilhuff** [comment]
Ah, that totally fits the facts. Nevermind and please carry on :-).

**Comment by mohonish** [comment]
Hi Guys,

Thanks for the quick response. Yes indeed my project had an existing library that had listed `v1.18` of leveldb-library as it's dependency on it's podspec. That probably caused the issue. I was able to update the dependency version by forking that repo.

This surprised me too as for firestore the pod dependency was noted as `(~> 1.18)` which means it is okay to pick up updated versions up to but not including/exceeding any version 2.0 onwards.

Nevertheless i've been able to workaround this.

Thanks!

**Comment by ykabbara** [comment]
Hi Guys 

I have a Flutter Project
and after I've made a 'pod update', I am trying to 'pod install'
But I'm having the following error.

Installing leveldb-library (1.22)

[!] Error installing leveldb-library
[!] /usr/bin/git clone https://github.com/google/leveldb.git /var/folders/ct/89dtp1r12jb6xn6h85f1jfz00000gn/T/d20190913-53195-1ye8psk --template= --single-branch --depth 1 --branch 1.22

Cloning into '/var/folders/ct/89dtp1r12jb6xn6h85f1jfz00000gn/T/d20190913-53195-1ye8psk'...
error: could not lock config file /private/var/folders/ct/89dtp1r12jb6xn6h85f1jfz00000gn/T/d20190913-53195-1ye8psk/.git/config: Too many open files in system
fatal: could not set 'remote.origin.fetch' to '+refs/tags/1.22:refs/tags/1.22'

Your Support is highly appreciated!

**Comment by paulb777** [comment]
@ykabbara  https://stackoverflow.com/questions/15375454/why-does-git-fail-on-push-fetch-with-too-many-open-files might be helpful
