### ISSUE TITLE
Is it able to run ML Kit in Xcode 8.3

### ISSUE THREAD

**Issue by zhouhao27** [firebase/firebase-ios-sdk#1791]
I'm wondering if it's possible to run ML Kit in my Xcode 8.3 project? It's an enterprise application. Thanks,

**Comment by paulb777** [comment]
Firebase dropped support for Xcode 8.3 earlier this summer when Apple started requiring Xcode 9 for building apps to publish to the App store.

I don't know of a reason that Xcode 8.3 wouldn't work right now - but it could break at any time in the future without warning.

**Comment by zhouhao27** [comment]
@paulb777 Thanks. I migrated my code to Xcode 9 already.
