### ISSUE TITLE
Is it possible to reduce the size if I only need to recognise the English text?

### ISSUE THREAD

**Issue by zhouhao27** [firebase/firebase-ios-sdk#1797]
I developed an application to do the text recognition by using ML Kit iOS. I only need to recognise in English. Is it possible to reduce the size of the package? Currently it's over 350 MB.

**Comment by morganchen12** [comment]
There's no way of reducing the binary size besides the linker's dead code stripping and App Store app slicing. However, these two methods combined should be able to significantly reduce the size of your binary (by upwards of 75%).

You should be able to see roughly the final size by installing a Testflight binary to a device and examining the app package there.
