### ISSUE TITLE
Error  Unable to generate/load/remove RSA keypair

### ISSUE THREAD

**Issue by r9hacks** [firebase/firebase-ios-sdk#1800]
Sep 11 08:20:57 <Error>: 5.7.0 - [Firebase/InstanceID][I-IID010003] Unable to generate keypair.
Sep 11 08:20:57 <Error>: 5.7.0 - [Firebase/InstanceID][I-IID010009] Keypair could not be loaded from Keychain. Error: Error Domain=com.firebase.iid Code=-34018 "(null)"
Sep 11 08:20:57 <Warning>: 5.7.0 - [Firebase/Analytics][I-ACS020001] Failed to get InstanceID: Error Domain=com.firebase.iid Code=-34018 "(null)"
Sep 11 08:20:57 <Error>: 5.7.0 - [Firebase/InstanceID][I-IID009001] Error removing keypair status: -34018
Sep 11 08:20:57 <Error>: 5.7.0 - [Firebase/InstanceID][I-IID010007] Unable to remove RSA keypair

I'm using FirebaseUI to Authenticate anonymous user with FUIPhoneAuth.
but an error message keep showing (Ref:https://github.com/firebase/FirebaseUI-iOS/issues/508)
and I think the error above is the main reasons.

running on iPhone 6 iOS 9.0.2

**Comment by morganchen12** [comment]
Can you share your Firebase versions and some sample code to reproduce this issue?

**Comment by morganchen12** [comment]
-34018 is a missing entitlement error. Make sure you've [enabled remote notifications under background modes](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_updates_to_your_app_silently?language=objc) so Auth can send the silent push to verify your device.

**Comment by r9hacks** [comment]
Using Firebase (5.7.0)
Using FirebaseAnalytics (5.1.1)
Using FirebaseAuth (5.0.3)
Using FirebaseAuthInterop (1.0.0)
Using FirebaseCore (5.1.2)
Using FirebaseDatabase (5.0.2)
Using FirebaseInstanceID (3.2.1)
Using FirebaseUI (5.2.1)

on iphone 6 iOS 9.0.2

I do enabled remote notification under background modes.
This is sample of my code.

func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        
        FirebaseApp.configure()
        if Auth.auth().currentUser != nil{
            
            if notFirstUse == false && !(Auth.auth().currentUser!.isAnonymous) {
                do {
                    try Auth.auth().signOut()
            
                } catch let error as NSError {
                        print(error.localizedDescription)
                }
            }
        }
        return true
    }

override func viewDidLoad() 
{
        super.viewDidLoad()
	if Auth.auth().currentUser == nil 
	{
	            //User Not logged in
	            Auth.auth().signInAnonymously() { (user, error) in
	                if error == nil{
	                 //   
	                }else{
	                    print(error.debugDescription)
	                    print(error?.localizedDescription)
	                }
	            }

	 }
}
	
func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) 
{
	tableView.deselectRow(at: indexPath, animated: true)
	if Auth.auth().currentUser != nil {
	      if Auth.auth().currentUser!.isAnonymous {

	   		 let phoneProvider = FUIAuth.defaultAuthUI()?.providers.first as! FUIPhoneAuth
	         phoneProvider.signIn(withPresenting: self, phoneNumber: nil)
		  }
	}
}

**Comment by r9hacks** [comment]
Using Firebase (5.7.0)
Using FirebaseAnalytics (5.1.1)
Using FirebaseAuth (5.0.3)
Using FirebaseAuthInterop (1.0.0)
Using FirebaseCore (5.1.2)
Using FirebaseDatabase (5.0.2)
Using FirebaseInstanceID (3.2.1)
Using FirebaseUI (5.2.1)

on iphone 6 iOS 9.0.2

I do enabled remote notification under background modes.
This is sample of my code.
`func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {

    FirebaseApp.configure()
    if Auth.auth().currentUser != nil{
        
        if notFirstUse == false && !(Auth.auth().currentUser!.isAnonymous) {
            do {
                try Auth.auth().signOut()
        
            } catch let error as NSError {
                    print(error.localizedDescription)
            }
        }
    }
    return true
}
override func viewDidLoad()
{
super.viewDidLoad()
if Auth.auth().currentUser == nil
{
//User Not logged in
Auth.auth().signInAnonymously() { (user, error) in
if error == nil{
//
}else{
print(error.debugDescription)
print(error?.localizedDescription)
}
}

 }
}

func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath)
{
tableView.deselectRow(at: indexPath, animated: true)
if Auth.auth().currentUser != nil {
if Auth.auth().currentUser!.isAnonymous {

   		 let phoneProvider = FUIAuth.defaultAuthUI()?.providers.first as! FUIPhoneAuth
         phoneProvider.signIn(withPresenting: self, phoneNumber: nil)
	  }
}
}`

**Comment by morganchen12** [comment]
Are you able to reproduce this with the [FirebaseUI sample](https://github.com/firebase/FirebaseUI-iOS/tree/master/samples/swift)?

**Comment by r9hacks** [comment]
I can't run the sample because its requires CocoaPods version `>= 1.5.0`, which is not satisfied by your current version, `1.4.0`.

but I found something interesting. As long as I run the app from Xcode as Debug mode on my iPhone I can reproduce the error. and sometimes even the Auth.auth().signInAnonymously() function return the same error. And when I run the app on my iPhone directly without using Xcode all the errors gone.
Could it be a Debug issus ? I'm using Xcode v9.2

**Comment by morganchen12** [comment]
There was some simulator keychain bug a while ago, but I don't think this is the same issue. Can you try updating your CocoaPods installation and reproducing the issue with the FirebaseUI sample?

**Comment by r9hacks** [comment]
I updated my CocoaPods to 1.5.3 and my xCode to version 10.0 and test the Auth on my application on both simulator and device also test Auth using the FirebaseUI sample.
All the error is gone, with keychain sharing enable and disable.

I think it was xCode and CocoaPods issue in previous versions.
Now for the keychain sharing do you preferred to be enabled or disabled ?

**Comment by morganchen12** [comment]
Keychain sharing should be disabled if you're not using it (you can always enable it later).
