### ISSUE TITLE
Zip File instructions do not mention including some Apple libraries that are needed

### ISSUE THREAD

**Issue by bstpierr** [firebase/firebase-ios-sdk#1806]
While creating a new app from scratch, I ran into many build errors when following the given instructions.

We should mention libc++ somewhere in the readme.

**Comment by bstpierr** [comment]
We also need to link in sqlite3, as well as StoreKit (for some SDKs anyway).

**Comment by bstpierr** [comment]
And also icucore.

**Comment by paulb777** [comment]
It's kind of there, but definitely could be more clear:

https://cs.corp.google.com/piper///depot/google3/googlemac/iPhone/Firebase/BuildScripts/TarballDistribution/README.md?g=0&l=60

It's especially confusing because Xcode's automatic linking seems to be random.

**Comment by morganchen12** [comment]
This will also break if for whatever reason the user has module imports disabled, right?

It may be worth adding a few lines about this on our devsite docs.

**Comment by paulb777** [comment]
Presumably. Missing libraries is also one of the issues that has affected Carthage users.
