### ISSUE TITLE
FCM Data messages stop working

### ISSUE THREAD

**Issue by vdmdar** [firebase/firebase-ios-sdk#1813]
### Describe your environment

  * Xcode version: 9.4.1
  * Firebase SDK version: 5.7
  * Firebase Component: Messaging 
  * Component version: 3.1.1

### Describe the problem
I use FCM both for notification and data messages. When notification payload is included in message body, FCM delivery works perfectly, but there is a problem with data messages.
I catch data messages in MessagingDelegate protocol's method and set `shouldEstablishDirectChannel` to true. Also payload is extremely simple and I didn't set content-available or any other properties.

After fresh app installation data messages do arrive, but after some time they unexpectedly stop arriving and never arrive again, until I reinstall the app.
I thought that a problem could be in my implementation, but I have tried to send messages to a sample app almost identical to [this](https://github.com/firebase/firebase-ios-sdk/blob/master/Example/Messaging/Sample/iOS/AppDelegate.swift) and the result was the same.

I have checked if the problem could be that fcmToken has changed or socket has lost connection (isDirectChannelEstablished is false), but everything was ok. 
Also I tried setting breakpoints in FCM's code and noticed that when data messages stop working, the only messages the socket receives are GtalkHeartbeatAck.
Server side is also ok: FCM returns response with no errors
For testing I used [Node FCM package](https://www.npmjs.com/package/fcm-push)

#### Steps to reproduce:
1. Install an app with firebase and notifications set up.
2. Send some data messages
3. Put the app in background mode and wait around 10-15 minutes (varies)
4. Eventually, only messages that can be received are messages with notification payload included. Others just never arrive.

#### Relevant Code:
To make sure that it is not me doing something wrong, as written above I tested it with [sample project](https://github.com/firebase/firebase-ios-sdk/blob/master/Example/Messaging/Sample/iOS/AppDelegate.swift) with minor changes like uncommenting `shouldEstablishDirectChannel`, etc

**Comment by morganchen12** [comment]
Can you share the message payload you're sending to FCM? This sounds like it may not be a client issue.

**Comment by vdmdar** [comment]
Thanks for your reply.

The payload looks like this:
`curl -X POST \
 https://fcm.googleapis.com/fcm/send \
 -H 'Authorization: key=*****************' \
 -H 'Cache-Control: no-cache' \
 -H 'Content-Type: application/json' \
 -d '{
   "data": {
       "section": "payments"
   },
   "to": "fBxnwkjEFUk:APA91bH15Z745MwxXKt8hW9GrjpipXF5KKWnFCTjh6FwbNIQC4g-N5OAl7zaRDwnXtAkO1od04zPqS51jaOORZ7RlELUJ3bfAY6Y5bf5XbOSuyHeiZ0mfXOJy-Sr0vaVEgK1-1DdW18D"
}'`

Also, today we discovered that token (A) received in 
`        Messaging.messaging().retrieveFCMToken(forSenderID: "firebaseProjectSenderID") { token, error in

        }
`
differs from the one (B) received in `func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String)`

So, data messages are still received when sent to token A, but not when sent to token B.
Also, notification messages are received when sent to B, but not to A.

Is this expected behavior?

**Comment by vdmdar** [comment]
No, they don't.  As far as I know sender ID always stays the same as we using just one firebase project to send messages.

`    func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String) {
        log.debug("Firebase registration token: \(fcmToken)")
        Messaging.messaging().shouldEstablishDirectChannel = true
        sendTokenToServer(token: fcmToken)
    }`

**Comment by morganchen12** [comment]
Hm, sounds like it might be a bug in the client SDK. @chliangGoogle can you take a look? I'm traveling currently, but can take a look at it next week.

**Comment by chliangGoogle** [comment]
It sounds like you are using multiple sender ID for difference purpose(data/notification), which should work as expected.

However you should only use one token instead of two. Are you using two differnt senderID (project ID) for FCM?

**Comment by vdmdar** [comment]
Hi
No, we are using just one sender ID
We discovered that this inconsistency happens when we set `        Messaging.messaging().apnsToken = deviceToken
`
and then we receive several different tokens to `func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String)` method.

(Note: this inconsistency happens not every time we set APNS token to `Messaging`, but after some time application spent resting in background)

One (A) of them accepts just messages with notification payload and ignores data messages. Other (B) accepts data messages, but also if we send notification message to that token (B), we still receive them in `func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String)`.
Could this be a bug?

**Comment by chliangGoogle** [comment]
If you are using one senderID, there should only be one token generated. This is a bug. 

Is the sender ID in retrieveFCMTokenForSenderID: method the same as the one inside your GoogleService-Info.plist? This method is used only if you want to use a different senderID. Any idea why you need to call this instead of getting token from the func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String)?

**Comment by vdmdar** [comment]
Yes, the sender ID is exactly the same. 
Initially, we didn't have intentions to use that method, we started using it because of the problem described above (that data messages stop working when sent to token received in `func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String)` method)
So we use this method as temporary workaround to be able to receive data messages, hopefully when this bug is fixed we will switch back to using `func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String)` only

**Comment by chliangGoogle** [comment]
You should only get one token even if you call the retrieveFCMTokenForSenderID:, unless you pass in a different sender ID.

What's the error you are getting when you firstly failed sending data message to token A?

**Comment by vdmdar** [comment]
There's no error
I get successful response such as
```
{"
 multicast_id":7119903945149749395,"
 success":1,
 "failure":0,
 "canonical_ids":0,
 "results":[
     {
       "message_id":"0:1537502249595713%4d34f077f9fd7bcd"
     }
  ]
}
```

**Comment by DAKZH** [comment]
Any updates?

**Comment by chliangGoogle** [comment]
We will need your debug log. Our devrel person is on vacation, can you DM me your debug log on how you generate two different tokens with the same sender ID?

**Comment by morganchen12** [comment]
Closed due to inactivity.

**Comment by indy1981** [comment]
it was closed, but still the same, works for a while and then stops for no reason

**Comment by ts95** [comment]
I also have this problem

**Comment by wolfraam** [comment]
For what it's worth: I had the same issue and solved it by moving some logic from didFinishLaunchingWithOptions() to applicationDidBecomeActive(). Apparently when didFinishLaunchingWithOptions() takes too long (database access etc. which is a bad idea anyway) the FCM messaging breaks.

**Comment by chliangGoogle** [comment]
For data message to receive make sure you set shouldEstablishDirectChannel and useMessagingDelegateForDirectChannel to true.

and implement the following method:
- (void)messaging:(FIRMessaging *)messaging
    didReceiveMessage:(FIRMessagingRemoteMessage *)remoteMessage
and handle your data message inside.
