### ISSUE TITLE
Crash in FPREventsQueue (iOS 9, iOS 10)

### ISSUE THREAD

**Issue by naveen-c** [firebase/firebase-ios-sdk#1824]
Describe your environment

  * Xcode version: 9.4
  * Firebase SDK version: 5.6.0
  * Firebase Component: Performance
  * Component version: 2.1.1

Describe the problem

We are using Firebase Performance tool for performance monitoring of the app. We have observed a crash in FPREventsQueue. The issue is observed in iOS 9 and iOS 10.

Crashed: com.google.perf.FPREventsQueue
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000000752c898d

The complete stack trace that we get from firebase is as follows:
```
Crashed: com.google.perf.FPREventsQueue
0  libobjc.A.dylib                0x23affa76 objc_msgSend + 21
1  Flipkart                       0x9d3937 -[FIRTrace backgroundTraceState] + 48
2  Flipkart                       0x9c2af3 __22-[FPRClient logTrace:]_block_invoke + 176
3  libdispatch.dylib              0x23ec5823 _dispatch_call_block_and_release + 10
4  libdispatch.dylib              0x23ed2423 _dispatch_queue_drain$VARIANT$mp + 1758
5  libdispatch.dylib              0x23ed1a61 _dispatch_queue_invoke$VARIANT$mp + 284
6  libdispatch.dylib              0x23ed45e9 _dispatch_root_queue_drain + 1560
7  libdispatch.dylib              0x23ed3fcd _dispatch_worker_thread3 + 96
8  libsystem_pthread.dylib        0x24089b29 _pthread_wqthread + 1024
9  libsystem_pthread.dylib        0x24089718 start_wqthread + 8
```

**Comment by mikehaney24** [comment]
We're looking into it.

**Comment by visumickey** [comment]
Just curious - Has this crash ever occurred in the past versions of Firebase performance?

**Comment by naveen-c** [comment]
Yes, the crash has been there at least from 4.12.0

**Comment by felixdkatt** [comment]
Any word on this yet?

**Comment by mikehaney24** [comment]
Nothing yet, I've been out of town on business, but promise to look at this
today. Sorry for the delay!

**Comment by mikehaney24** [comment]
I've been trying to reproduce, but I need more information. Would it be possible for you to create a test xcodeproj that demonstrates the issue?

**Comment by naveen-c** [comment]
@mikehaney24 we also do not have concrete steps to reproduce the issue. We just have the crash stack trace from firebase, that I have already shared :(

**Comment by mikehaney24** [comment]
Are you aware of what conditions seem to trigger the crash, or workarounds you've done that seem to fix it?

**Comment by mikehaney24** [comment]
Can't continue without additional information.
