### ISSUE TITLE
Read/write methods resulting in error claiming incorrect required number of segments for reference

### ISSUE THREAD

**Issue by moopoints** [firebase/firebase-ios-sdk#1825]
* Xcode version: 9.4.1
  * Firebase SDK version: 5.8.0
  * Firebase Component: Firestore 
  * Component version: 0.13.3 (Not sure if that's the correct version number. To be safe I updated my pods before writing this ticket)

It appears that once I get deeper into collections/documents and past 3 levels of collections, any request (e.g. updateData, getDocuments) currently will result in an error message like this: 

"Terminating app due to uncaught exception 'FIRInvalidArgumentException', reason: 'Invalid document reference. Document references must have an even number of segments, but users/gkN9E1kSVOOTsssl6cgGpFKEp8h2/decks/NkVgPRq7ocJTyAjD78KF/autoSaveDeck/OjmalMPxIRZ8w9ZD1TwS/cards has 7'"

#### Steps to reproduce:

Read/write method for nested collections going past 3 levels of collections. See example below. 

#### Relevant Code:
        db.collection("users").document(uid).collection("decks").document(deckId).collection("autoSaveDeck").document(autoSaveDeckId).collection("cards").document(cardId).updateData(dictionary, completion: { (err) in
                if let err = err {
                    print("Failed updating autoSaveCard: ", err)
                } else {
                    print("Successfully updated autoSaveCard")
                }
        })

**Comment by moopoints** [comment]
Turns out the error was a result of a missing value. So the request handling is just fine, the error message is a bit misleading.

**Comment by wilhuff** [comment]
Could you say a bit more about what you mean by "missing"? Was one of them `nil`?

**Comment by moopoints** [comment]
That's correct, one of the values was nil. I am passing (I didn't copy that part in my snippet above) values such as deckId and autoSaveDeckId as well as cardId. In this case cardId was nil which then caused the above error message.

**Comment by wilhuff** [comment]
I've double-checked and both document and collection now throw invalid argument, e.g.

/Users/mcg/src/firebase/ios-sdk/Firestore/Example/Tests/API/FIRCollectionReferenceTests.mm:44: error: -[FIRCollectionReferenceTests testNilElements] : failed: caught "FIRInvalidArgumentException", "Document path cannot be nil."
