### ISSUE TITLE
Update Carthage Specs to Version 5.8.0

### ISSUE THREAD

**Issue by leedsalex** [firebase/firebase-ios-sdk#1826]
* Xcode version: 10.0
  * Firebase SDK version: 5.6.0
  * Firebase Component: Core, Analytics, Performance
  * Component version: 5.6.0

**Problem:**

The Carthage specs for Firebase have not been updated since version 5.6.0. Could you please update them so they point to the latest SDK versions?

**Steps to reproduce:**

Follow the steps to implement the Firebase SDK & Components using Carthage: https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md

**Comment by paulb777** [comment]
5.8.0 is now available on Carthage. Thanks for the ping @leedsalex

**Comment by fschaus** [comment]
Could this also be the case for Cocoapods? As of Friday 9/14, version 5.6.0 is the last pod available (and v0.13.1 for Firestore). Thanks!

**Comment by paulb777** [comment]
@fschaus 5.8.0 was pushed to CocoaPods two days ago. Make sure you update your CocoaPods repo - `pod update`

**Comment by fschaus** [comment]
Ok works now. What threw me off was that when trying to do a clean install (i.e. pod install Firebase/Core) it would install v.5.6.0 and not 5.8.0 (and refuse to install 5.8.0 even when I specified "pod install Firebase/Core", "5.8.0")...

Running the pod update on that 5.6.0 doesn't work though. Thanks!
