### ISSUE TITLE
`GoogleUtilities.podspec` iOS deployment version should be higher than 6.0

### ISSUE THREAD

**Issue by pyrosphere** [firebase/firebase-ios-sdk#1829]
`GoogleUtilities.podspec` specifies the [iOS deployments target to be 6.0](https://github.com/firebase/firebase-ios-sdk/blob/f151178392de45eebf2aaa16c259fc9879200992/GoogleUtilities.podspec#L19). However that's probably a mistake as `GoogleUtilities` use several methods and classes only available from iOS 7.0 such as `NSURLSession`.

**Comment by paulb777** [comment]
The 6.0 is intentional since the pod has a client that supports 6.x and uses runtime checks to avoid the GoogleUtilities calls on 6.x.

I'll add a comment to the podspec.

**Comment by pyrosphere** [comment]
Thank you for the clarification.

It's a shame since Xcode throws a bunch of `'NSURLSession' is only available on iOS 7.0 or newer` warnings. 😞

**Comment by paulb777** [comment]
Good point. We'll investigate adding pragmas or @available checks to suppress those warnings.  (Note they also don't occur if the Podfile has `use_frameworks!` on.)

Thanks for the report @pyrosphere
