### ISSUE TITLE
Blocked the main thread

### ISSUE THREAD

**Issue by a455455b** [firebase/firebase-ios-sdk#1831]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.3
  * Firebase SDK version: 5.4.1
  * Firebase Component: FirebaseAnalytics
  * Component version: 5.0.1

#### Steps to reproduce:
When our app is in a weak network, Firebase will block our main thread during the initialization process.

#### Relevant Code:

```
libsystem_kernel.dylib          0x10f7c5432 __ulock_wait + 10
libdispatch.dylib               0x10f2e0283 _dispatch_gate_wait_slow + 78
libdispatch.dylib               0x10f2e0d45 dispatch_once_f + 162
banggood                        0x103734a50 +[FIRAMeasurement monitor] + 45
banggood                        0x10376365d __51-[FIRAScreenViewReporter setCurrentViewController:]_block_invoke + 525
libdispatch.dylib               0x10f2df848 _dispatch_client_callout + 8
libdispatch.dylib               0x10f2e65b8 _dispatch_queue_barrier_sync_invoke_and_complete + 374
banggood                        0x1037633d7 -[FIRAScreenViewReporter setCurrentViewController:] + 136
banggood                        0x103762ce7 -[FIRAScreenViewReporter viewControllerDidAppear:] + 390
banggood                        0x1037645be -[UIViewController(FIRAScreenClassName) fira_viewDidAppear:] + 84
UIKit                           0x12d8b99ae -[UIViewControllerAccessibility viewDidAppear:] + 67
UIKit                           0x109fb7a19 -[UITabBarController viewDidAppear:] + 53
banggood                        0x102d10b6e -[BGMainTabBarViewController viewDidAppear:] + 110
banggood                        0x102cb0f8e pmy_viewDidAppear + 222
UIKit                           0x109f58ebf -[UIViewController _setViewAppearState:isAnimating:] + 697
UIKit                           0x109f5bcfb __64-[UIViewController viewDidMoveToWindow:shouldAppearOrDisappear:]_block_invoke + 42
UIKit                           0x109f5a03f -[UIViewController _executeAfterAppearanceBlock] + 78
UIKit                           0x109dba64f _runAfterCACommitDeferredBlocks + 634
UIKit                           0x109da977e _cleanUpAfterCAFlushAndRunDeferredBlocks + 388
UIKit                           0x109dc92d7 __34-[UIApplication _firstCommitBlock]_block_invoke_2 + 155
CoreFoundation                  0x105b90b0c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
CoreFoundation                  0x105b752db __CFRunLoopDoBlocks + 331
CoreFoundation                  0x105b74a84 __CFRunLoopRun + 1284
CoreFoundation                  0x105b7430b CFRunLoopRunSpecific + 635
GraphicsServices                0x11043fa73 GSEventRunModal + 62
UIKit                           0x109daf0b7 UIApplicationMain + 159
banggood                        0x10267187f main + 111
libdyld.dylib                   0x10f35c955 start + 1
```

**Comment by paulb777** [comment]
Perhaps related to https://github.com/invertase/react-native-firebase/issues/1469#issuecomment-419679192?

**Comment by a455455b** [comment]
@paulb777 It may not be the problem you quoted,i found the keyword '_dispatch_gate_wait_slow' happened in the case of a deadlock.

**Comment by morganchen12** [comment]
@a455455b are you able to reproduce the bug in the same network conditions using one of the quickstart apps?

**Comment by a455455b** [comment]
It is accidental, not every time, very consistent with the emergence of deadlock.

**Comment by a455455b** [comment]
@morganchen12 A week has passed, I found that the probability of this crash is extremely low. Maybe we can ignore it.
