### ISSUE TITLE
Error with link multiple auth providers

### ISSUE THREAD

**Issue by olegshamin** [firebase/firebase-ios-sdk#1838]
Environment

  * Xcode version: 9.3-10
  * Firebase SDK version: 5.8.0
  * Firebase Component: Auth, UI
  * Component version: Auth 5.0.3; UI 5.2.2

#### Steps to reproduce:

1. Sign in with phone number
2. Try to link Google account to my firebase user
3. When I pressed on button first time - nothing happens. When I pressed second time - all work correctly. OR If I move back to previous screen and than return back and pressed same button again - everything works correct.
4. When I try to link Facebook or Twitter - everything works fine (for other social networks I used same method but instead of **FUIGoogleAuth()** I use **FUIFacebookAuth()** or **FUITwitterAuth()**

#### Relevant Code:

For sign in with phone number I used next code:
a) verify phone number
```
PhoneAuthProvider.provider().verifyPhoneNumber(request.phoneNumber, uiDelegate: nil) { (verificationId, error) in
....
}
```
b) send verification code:
```
        let credential = PhoneAuthProvider.provider().credential(
            withVerificationID: request.verificationId,
            verificationCode: request.verificationCode)

        Auth.auth().signInAndRetrieveData(with: credential) { [weak self] (authResult, error) in 
             .....
        }
```
After that I try to link Google account by tapped ob button:
```
FUIGoogleAuth().signIn(withDefaultValue: nil, presenting: nil) { [weak self] (credential, error, _) in
      ......  
 }
```
And nothing happens in first time. But everything fine after second tap.

I found that problem inside FUIGoogleAuth.m: nothing happens when calling
```
- (void)signInWithDefaultValue:(nullable NSString *)defaultValue
      presentingViewController:(nullable UIViewController *)presentingViewController
                    completion:(nullable FIRAuthProviderSignInCompletionBlock)completion {
        ....
        [signIn signIn];
}
```
but this method should be called:
```
- (void)signIn:(GIDSignIn *)signIn
    didSignInForUser:(GIDGoogleUser *)user
           withError:(NSError *)error 
```

**Comment by morganchen12** [comment]
@olegshamin sorry for the slow response here. Calling the `signIn:didSignInForUser:withError:` method that you mentioned is a responsibility of the GoogleSignIn SDK, not Firebase or FirebaseUI.

Please comment here if this is still an issue.
