### ISSUE TITLE
DynamicLink doesn't work after first installation from store

### ISSUE THREAD

**Issue by AbyssDevil** [firebase/firebase-ios-sdk#1844]
Environment:
- Xcode version: 9.4.1
- Swift: 3.1 (At this moment there is no a budget for the conversion to swift 4)
- Minimum iOS deployment target: 9.3
- Firebase SDK version: 3.17.0
- Firebase Component: FirebaseDynamicLinks
- Component version: 1.4.0
- Other components version:
          Using Firebase (3.17.0)
          Using FirebaseAnalytics (3.9.0)
          Using FirebaseCore (3.6.0)
          Using FirebaseCrash (1.1.6)
          Using FirebaseDynamicLinks (1.4.0)
          Using FirebaseInstanceID (1.0.10)
          Using FirebaseMessaging (1.2.3)
          Using FirebaseRemoteConfig (1.3.4)
          Using Google (3.1.0)
          Using GoogleAnalytics (3.17.0)

The command from terminal "pod update" does not update beyond these versions, even specifying the minimum version required.

Steps:
- tap on dynamic link in iMessage
- safari opens on a gray page and a popUp with app store link
- app store opens (in another application's page - According to the documentation, this is not important.-)
- install app through Xcode
- application(_:didFinishLauncingWithOptions) is called and return true
- application(_:applicationDidBecomeActive) is called
- application(_:openurl:options) isn't called and neither application(_:open:sourceApplication:annotation)

I tried to set:
FIROptions.default().deepLinkURLScheme =  //appBundleId//
FIROptions.default().deepLinkURLScheme =  "dlscheme"

- The DynamicLink is generated from BackEnd with Firebase API and work fine on Android.
- When opening the link with app installed through application(_:continue:restorationHandler:), everything always works fine.

I remain at your disposal for further details and waiting for kind feedback. Thank you.

**Comment by paulb777** [comment]
We can reopen if it reoccurs on Firebase 5.x.
