### ISSUE TITLE
Firebase causing app to crash on initial load

### ISSUE THREAD

**Issue by richaricrew** [firebase/firebase-ios-sdk#1850]
### [READ] Step 1: Are you in the right place?

App crashes on load

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10 GM
  * Firebase SDK version: 5.8.0
  * Firebase Component: Core, Performance (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: Core -> 5.1.3, Performance -> 2.1.1

### [REQUIRED] Step 3: Describe the problem

After installing the Firebase pod and adding the configuration to our app delegate, the app crashes out trying to make some network calls. It's difficult to get exactly what the issue is, but definitely related to the new Xcode.

#### Steps to reproduce:

Install Cocoa pods
Add .configure() to app delegate
Run app

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulb777** [comment]
@richaricrew There isn't enough information here for us to reproduce and investigate the issue.  Please update and we can reopen.

**Comment by richaricrew** [comment]
@paulb777 what more information would you like. There is no stack trace, and it seems to be crashing out when trying to make an API call on a background thread. Not sure if it is clashing with other pods we are using, but I can supply the list if that helps?

**Comment by paulb777** [comment]
@richaricrew We need some way to reproduce the crash, since it is not something that shows up in our tests.

Can you share an example that reproduces the issue - by sharing your app, a minimized version of it, or adding elements to a[ sample app](https://github.com/firebase/quickstart-ios).

**Comment by richaricrew** [comment]
@paulb777 ok Ill see what I can narrow it down to to give more perspective

**Comment by richaricrew** [comment]
@paulb777 We do use a bunch of swift static libraries. Could that be a potential cause?

**Comment by paulb777** [comment]
@richaricrew Possibly, but not necessarily. It depends on what they do. Since the crash is at load time, it could be related to a bad interaction between code that runs in `+load` functions.

**Comment by richaricrew** [comment]
@paulb777 there seems to be some issues around NSZombie mode. here is the exact output we receive: 

objc[24079]: Class _NSZombie_FIRInstanceIDStringEncoding is implemented in both ?? (0x604000326790) and ?? (0x604000356fd0). One of the two will be used. Which one is undefined.

It's not causing the crash, but zombie mode is crashing.

**Comment by paulb777** [comment]
@richaricrew Are you linking multiple static libraries that depend upon Firebase into separate dynamic libraries?

**Comment by richaricrew** [comment]
Right now firebase lives within the main app. I am currently not referencing Firebase outside of the AppDelegate

**Comment by morganchen12** [comment]
@richaricrew can you share a stack trace?
