### ISSUE TITLE
Firestore - No data with FXForms pod

### ISSUE THREAD

**Issue by wimbledon** [firebase/firebase-ios-sdk#1856]
* Xcode version: __9.4.1 (9F2000)___
  * iOS: 11.4.1
  * Firebase SDK version: _5.8.1____
  * Firebase Component: Firestore only
  * Component version: _0.13.3_

### Describe the problem

When using [FXForms](https://github.com/nicklockwood/FXForms) pod with Firestore, Firestore is unable to write, get and listen to any data in a document. No error is thrown or shown in the console.

Podfile:  
  pod 'FXForms'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

Using BoringSSL (10.0.6)
**Using FXForms (1.2.14)**
Using Firebase 5.8.1
Using FirebaseAnalytics (5.1.4)
Using FirebaseAuthInterop (1.0.0)
Using FirebaseCore (5.1.3)
Using FirebaseFirestore (0.13.3)
Using FirebaseInstanceID (3.2.1)
Using GoogleAppMeasurement (5.1.4)
Using GoogleUtilities 5.3.0
Using Protobuf (3.6.1)
Using gRPC (1.14.0)
Using gRPC-C++ (0.0.3)
Using gRPC-Core (1.14.0)
Using gRPC-ProtoRPC (1.14.0)
Using gRPC-RxLibrary (1.14.0)
Using leveldb-library (1.20)
Using nanopb (0.3.8)

#### Relevant Code:

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // Override point for customization after application launch.
    [FIRApp configure];
    self.firestore = [FIRFirestore firestore];
    
    FIRDocumentReference *docRef =
    [[self.firestore collectionWithPath:@"cities"] documentWithPath:@"SF"];
    [docRef getDocumentWithCompletion:^(FIRDocumentSnapshot *snapshot, NSError *error) {
        if (snapshot.exists) {
            // Document data may be nil if the document exists but has no keys or values.
            NSLog(@"Document data: %@", snapshot.data);
        } else {
            NSLog(@"Document does not exist");
        }
    }];
    
    [[[self.firestore collectionWithPath:@"cities"] documentWithPath:@"LA"]
     addSnapshotListener:^(FIRDocumentSnapshot *snapshot, NSError *error) {
         if (snapshot == nil) {
             NSLog(@"Error fetching document: %@", error);
             return;
         }
         NSLog(@"Current data: %@", snapshot.data);
     }];
    
    
    
    [[[self.firestore collectionWithPath:@"cities"] documentWithPath:@"SF"] setData:@{
                                                                                      @"name": @"Los Angeles",
                                                                                      @"state": @"CA",
                                                                                      @"country": @"USA",
                                                                                      @"beats" : @[@"Hello0"]
                                                                                      } merge:YES
                                                                         completion:^(NSError * _Nullable error) {
                                                                             if (error != nil) {
                                                                                 NSLog(@"Error writing document: %@", error);
                                                                             } else {
                                                                                 NSLog(@"Document successfully written!");
                                                                             }
                                                                         }];
    return YES;
}
```

**Comment by wilhuff** [comment]
I'm missing something. The code you've included seems straight out of the Firestore documentation and is known working. In particular it doesn't seem to have anything to do with FXForms. Or is it merely the inclusion of the FXForms pod in your project at all that causes the problem?

You can get more clues about what's going on by enabling debug logging:

```objc
[FIRFirestore enableLogging:YES];
```

**Comment by wimbledon** [comment]
@wilhuff, Yes! Merely including FXForms pod in the project cause the problem. Just try it yourself. 

No relevant error/info is given from:
```
[FIRFirestore enableLogging:YES];
or
[[FIRConfiguration sharedInstance] setLoggerLevel:FIRLoggerLevelDebug];
```

**Comment by rsgowman** [comment]
The problem is that FXForms injects a few methods into NSObject via obj-c categories here: 
https://github.com/nicklockwood/FXForms/blob/2b7f025e4bd83c72033fb5f0718f1082629ede78/FXForms/FXForms.h#L94
https://github.com/nicklockwood/FXForms/blob/2b7f025e4bd83c72033fb5f0718f1082629ede78/FXForms/FXForms.m#L1804
