### ISSUE TITLE
FR: Officially support Carthage release

### ISSUE THREAD

**Issue by Nonnus** [firebase/firebase-ios-sdk#1862]
As it is obvious this is not really an issue but I really wanted to leave some feedback about your experimental carthage integration as I really hope it ends up being officially supported!

ps: feel free to close this issue :)

pps: sorry if I am abusing the issues guidelines, I hope the end justified the means ;)

**Comment by morganchen12** [comment]
No problem!

**Comment by paulb777** [comment]
The Carthage distribution is still experimental and we're not promising to make every minor release available via Carthage.

Even if the latest distribution is not available via Carthage, the latest binary frameworks are always available at https://firebase.google.com/docs/ios/setup#frameworks.

We're continuing to improve the release process and hope to make Carthage official and in sync with the rest of the release in the future.

**Comment by techmehra** [comment]
Where is the development process to support carthage

**Comment by paulb777** [comment]
@techmehra See https://github.com/firebase/firebase-ios-sdk/tree/master/ZipBuilder for the zip and Carthage libraries are build scripts.  There is additional internal code for deploying the libraries to Google servers.

**Comment by mmalesevic** [comment]
@paulb777  when will "make Carthage official and in sync with the rest of the release in the future" happen? Mid 19 or End 19? As Fabric.io isn't a optiona any longer i have to know how to handle future projects... and pods is not a option as we are using carthage in most of our projects...

**Comment by ffittschen** [comment]
Linking this issue as cross-reference, because it should be taken into consideration when providing official Carthage support: https://github.com/Carthage/Carthage/issues/2777

**Comment by Hantok** [comment]
Just moved Firebase from pods to carthage in one project.
Is it possible to use specific Firebase version in carthage to be sure all things work fine?

**Comment by mortenbekditlevsen** [comment]
Yes, you can specify the dependency in the Cartfile as follows:
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseDatabaseBinary.json" == 6.2.0

**Comment by paulb777** [comment]
Closing. Now that Swift Package Manager is the future (see #3136), we no longer plan to officially support Carthage. We will continue Carthage updates and support as experimental until SPM migration is ready.

**Comment by AlexisQapa** [comment]
Since you don't plan on open sourcing all you frameworks isn't Carthage the best bet for now ? Using SPM with binary isn't even drafted

**Comment by paulb777** [comment]
We plan to continue existing CocoaPods, zip, and Carthage support.  After WWDC 2019, we think that investing in a swiftPM solution is better than further Carthage improvements.

**Comment by AlexisQapa** [comment]
Nice to know, we will definitely move to SPM when available too. I was just worried you would drop Carthage support right now as we spent quite a lot of time investing in Carthage related tooling.

**Comment by mendesbarreto** [comment]
I'd really like to see this support come true, because even though SPM is already being adopted for you guys, it still does not have the support for Binaries Distribution which ultimately reduces compilation time. 

I'd to invite you to compare the diferences between a medium-sized project based on cocoapods and SPM and one which has prebuilt carthage frameworks, you will notice the difference and I can guarantee that it is not a small one and because that I think Carthage is a big deal yet.

Thanks for everything you ever did for us that still use carthage!
