### ISSUE TITLE
ld: library not found for -lBVLinearGradient

### ISSUE THREAD

**Issue by newbieee1011** [firebase/firebase-ios-sdk#1878]

**Comment by paulb777** [comment]
This does not look like a Firebase issue. It seems related to React Native and not Firebase: https://stackoverflow.com/questions/43106124/warning-native-component-for-bvlineargradient-does-not-exist
https://github.com/react-native-community/react-native-linear-gradient/tree/master/BVLinearGradient.xcodeproj

Please use stackoverflow or reach out to that community.
