### ISSUE TITLE
Firebase Fabric Crashlytics not sending data to server

### ISSUE THREAD

**Issue by muthukrishnanOCS** [firebase/firebase-ios-sdk#1879]
I think I've done the integration correctly. Everything looks ok. However data doesn't get sent (or received). I think the problem is in this message that I get in the debug console (Xcode).

```[Fabric] failed to download settings Error Domain=FABNetworkError Code=-5 "(null)" UserInfo={status_code=403, type=2, request_id=2ee223feb3c7053579a2136db09a5749, content_type=application/json; charset=utf-8}```

please give some solution

**Comment by muthukrishnanOCS** [comment]
Hi @TKBurner , Do you have any idea for a issue?
Please let me know ASAP.
Thanks

**Comment by muthukrishnanOCS** [comment]
@paulb777 any update for this?

**Comment by muthukrishnanOCS** [comment]
it doesn't work please give more details. i followed the below steps and getting error on console firebase.google.com/docs/crashlytics/get-started

**Comment by paulb777** [comment]
Created b/117209779 to reach out more broadly internally

**Comment by TKBurner** [comment]
Thanks. Can you let me know the affected bundle ID or package name? I suspect this is related to the individual apps status in our system.

**Comment by muthukrishnanOCS** [comment]
@TKBurner Here is the bundle ID `fr.appsolute.Roole`. please check & let me know once fixed

**Comment by muthukrishnanOCS** [comment]
Hi @TKBurner i'm waiting for your reply. kindly help me to fix the issue

**Comment by TKBurner** [comment]
Thanks. Usually this relates to having linked from Fabric and then having removed the API key. Do you still have the API key in place if you came from Fabric? You should re-add it.

**Comment by NadzeyaStsepanchuk** [comment]
Hi @TKBurner, I am having the same issue. Have tried to remove Fabric API key from .plist, also tried with Fabric API key in .plist. Not receiving any crashes to Firebase Crashlytics :(.
Kindly, help.

**Comment by TKBurner** [comment]
Thanks @NadzeyaStsepanchuk it looks like crashes are now appearing. I noticed you have two copies of the app in our system. One is linked to Firebase the other isn't. Might that be what's causing this issue? 

Can you generate this URL for yourself and refollow the linking flow?

https://fabric.io/remove_firebase_crashlytics?clientId=ios:com.sample.app&projectId=project-slug

**Comment by NadzeyaStsepanchuk** [comment]
Hi @TKBurner, actually there are two different apps on our Firebase account:
com.translate.me and com.translate.onair. And crashes are not coming for the latest releases :(.

Unfortunately I don't have credentials from Fabric account, so I can't re-link it.
Please suggest, what can be done in this situation?

**Comment by NadzeyaStsepanchuk** [comment]
Hi @TKBurner,
re-linking really worked like a charm! Thanks you so much!

**Comment by muthukrishnanOCS** [comment]
Hi @TKBurner , 
I generated & tried this URL. But, getting this error. kindly suggest me please.
And I've this issue as very long time. Unable to check the crashes and issue only for iOS

**Comment by ludivinefafournoux** [comment]
I have the same issue, my app ID is com.eu.tessa.NetCabDev

**Comment by jutei** [comment]
Hi @TKBurner 
I'm facing the same issue. Initialisation is ok but then I've got the error for downloading settings
I tried to unlink the app (it worked) than re-linked it but still the same download settingd error...

My app id is com.truckfly.truckflyapp

Can you help me please?

**Comment by xiao99xiao** [comment]
Same here. Tried all methods mentioned above. 
Only the crashlytics part is not working. Analytics works like a charm.

**Comment by adamsinger** [comment]
This is happening for my app as well.

One thing to note: the last version that has any analytics showing up in the Fabric console is 1.3.x, but my app is now at 2.0.2 (2.0 is when I attempted to transition from Fabric only to Firebase). 

I tried doing the un-link and re-link flow, and selected that I was adding the integration to an existing Crashlytics app. Could the fact that the versions don't line up mean something?

It appears that the analytics in the Firebase console look correct, but nothing is going to the Fabric console. No crashes seem to be going through.

**Comment by kenji21** [comment]
> It was happening to my app as well. It had previously used Fabric Crashlytics, and I may have conflated the installation instructions. It is a bit confusing.
> 
> It should be clarified that if you are a legacy Fabric user, that you need to keep the API tokens in the Build Phase script, and also (presumably) in your Info.plist

@morganchen12 can you clarify this point, I'm having the issue... using Carthage (because it is better than CocoaPods from my point of view: quicker CI builds for exemple), and I don't have "full configuration state" of the project to rely on

**Comment by kenji21** [comment]
Ok fixed via 

```
    [Fabric with:@[CrashlyticsKit]];
    [FIRApp configure];
```

and keeping the IDs on the run script build phase calling the run command from Fabric.framework

**Comment by samwize** [comment]
Relinking did not work for me.

I contacted Firebase support and was told that the Fabric setup (the keys to run and in Info.plist) is still needed. https://fabric.io/kits/ios/crashlytics/install
