### ISSUE TITLE
Multiple Authentification

### ISSUE THREAD

**Issue by smartphone-pro** [firebase/firebase-ios-sdk#1884]
I am making a shopping app using Firebase.
Email and Facebook login methods have been implemented.
It's working well.

I'd like to implement a phone authentication to get users to upload new products.

https://firebase.google.com/docs/auth/ios/account-linking
I followed the guidelines in Firebase.
Phone authentication will only be used to authenticate the user, not as login method.

Code

        Auth.auth().signIn(withEmail: username, password: password, completion: { (authResult, error) in
        })

        ...

        let credential = PhoneAuthProvider.provider().credential(withVerificationID: verificationID, verificationCode: verificationCode)
        if let prevUser = Auth.auth().currentUser {
            Auth.auth().signInAndRetrieveData(with: credential) { (result, error) in
                if let error = error {
                    // error handling
                } else {
                    // success
                }
            }
        }

The problem is how to log back in to the Email Credential that was already logged in after signInAndRetrieveData(with: credential).
After the above method  is successful, Auth.auth().currentUser is logged in by phone number.

Is there any way to check for correct phone authentication code without logging in?

Please help.
Regards!

**Comment by morganchen12** [comment]
Firebase doesn't provide any auth providers that allow you to authenticate without also allowing you to sign in. If you'd like to link an email account with a phone auth account, you can do so via [this method](https://firebase.google.com/docs/reference/ios/firebaseauth/api/reference/Classes/FIRUser#/c:objc(cs)FIRUser(im)linkAndRetrieveDataWithCredential:completion:).

**Comment by smartphone-pro** [comment]
Thank you for message.

I have already used `linkWithCredentials:compensation:`
However, at the time of call for this method, Auth.auth().currentUser is already linked to the Email provider.
The result will fail.

It is also pointed out in Firebase's document.
https://firebase.google.com/docs/auth/ios/account-linking

_The call to linkWithCredential:completion: will fail if the credentials are already linked to another user account. In this situation, you must handle merging the accounts and associated data as appropriate for your app:_

So I am using multiple authentication.

Thanks again.

**Comment by smartphone-pro** [comment]
Thanks for your message.
May I ask some sample code?
Regards!
