### ISSUE TITLE
Error After updating FirebaseCore to 5.0

### ISSUE THREAD

**Issue by samsidd** [firebase/firebase-ios-sdk#1885]
i was unable to get the array contains function in firestore so I have update pod FirebaseCore -> 5.0 , now it is giving these errors:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FIRAppEnvironmentUtil", referenced from:
      objc-class-ref in FirebaseCoreDiagnostics(FIRDiagnostics_ccb5c62e0dad2a941440a982722cac92.o)
  "_kFIRNetworkHTTPStatusCodeNotModified", referenced from:
      -[FIRAMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in FirebaseAnalytics(FIRAMeasurement_418014fbcaf09024bdaab2e8210da204.o)
  "_kFIRNetworkHTTPStatusCodeNotFound", referenced from:
      -[FIRAMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in FirebaseAnalytics(FIRAMeasurement_418014fbcaf09024bdaab2e8210da204.o)
  "_kFIRNetworkHTTPStatusOK", referenced from:
      -[FIRAMeasurement networkUploadCompletionHandlerWithResponse:error:] in FirebaseAnalytics(FIRAMeasurement_418014fbcaf09024bdaab2e8210da204.o)
      -[FIRAMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in FirebaseAnalytics(FIRAMeasurement_418014fbcaf09024bdaab2e8210da204.o)
  "_kFIRNetworkHTTPStatusNoContent", referenced from:
      -[FIRAMeasurement networkUploadCompletionHandlerWithResponse:error:] in FirebaseAnalytics(FIRAMeasurement_418014fbcaf09024bdaab2e8210da204.o)
      -[FIRAMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in FirebaseAnalytics(FIRAMeasurement_418014fbcaf09024bdaab2e8210da204.o)
  "_kFIRNetworkHTTPStatusCodeUnavailable", referenced from:
      -[FIRAMeasurement networkUploadCompletionHandlerWithResponse:error:] in FirebaseAnalytics(FIRAMeasurement_418014fbcaf09024bdaab2e8210da204.o)
      -[FIRAMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in FirebaseAnalytics(FIRAMeasurement_418014fbcaf09024bdaab2e8210da204.o)
  "_kFIRNetworkHTTPStatusCodeCannotAcceptTraffic", referenced from:
      -[FIRAMeasurement networkUploadCompletionHandlerWithResponse:error:] in FirebaseAnalytics(FIRAMeasurement_418014fbcaf09024bdaab2e8210da204.o)
      -[FIRAMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in FirebaseAnalytics(FIRAMeasurement_418014fbcaf09024bdaab2e8210da204.o)
  "_OBJC_CLASS_$_FIRNetwork", referenced from:
      objc-class-ref in FirebaseAnalytics(FIRAAppDelegateProxy_492d6b8d87dfb426a9a9828dfc4c327e.o)
      objc-class-ref in FirebaseAnalytics(FIRAnalytics_f4b98ee05d91ac1a012acad5e8bfd283.o)
      objc-class-ref in FirebaseAnalytics(FIRAMeasurement_418014fbcaf09024bdaab2e8210da204.o)
      objc-class-ref in FirebaseCoreDiagnostics(FIRClearcutLogger_aae964e21ad546f95d93b470b019d620.o)
  "_OBJC_CLASS_$_FIRMutableDictionary", referenced from:
      objc-class-ref in FirebaseAnalytics(FIRAAppDelegateProxy_492d6b8d87dfb426a9a9828dfc4c327e.o)
      objc-class-ref in FirebaseAnalytics(FIRARemoteConfig_7c67d68a4d265447afbb2db960e98ff4.o)
ld: symbol(s) not found for architecture x86_64

**Comment by paulb777** [comment]
It looks like there is a mix of incompatible versions. Make sure you clean the environment and rebuild. 

If you're still stuck, share your Podfile and Podfile.lock.

**Comment by samsidd** [comment]
[Archive.zip](https://github.com/firebase/firebase-ios-sdk/files/2427118/Archive.zip)

**Comment by paulb777** [comment]
Two strange things about the project:
- It's using several-month old Pod versions
- Those missing symbols should be in the old version of FirebaseCore which seems to be installed.

I recommend running `pod update` instead of `pod install` to update to the latest version of all Pods.

**Comment by morganchen12** [comment]
Closing due to staleness, please try updating your pods and comment here if you have any new issues.

**Comment by ulaserdegor** [comment]
Same problem
My pods 
Using Firebase (5.10.0)
Using FirebaseAnalytics (5.2.0)
Using FirebaseCore (5.1.5)
Using FirebaseInstanceID (3.2.2)
Using FirebaseMessaging (3.2.0)

`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_GULUserDefaults", referenced from:
      objc-class-ref in FirebaseInstanceID(FIRInstanceIDStore_d561cdee2d9f8fc26566b1c545e02875.o)
      objc-class-ref in FirebaseInstanceID(FIRInstanceIDCheckinPreferences_306fdb082ecca463aff31a603a452ec5.o)
      objc-class-ref in FirebaseInstanceID(FIRInstanceIDUtilities_e6b1b6e92e6be2bfdc1b4326e55da04d.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by paulb777** [comment]
@ulaserdegor Make sure that GoogleUtilities (5.3.0 or newer) is being built and linked.

**Comment by ulaserdegor** [comment]
My podfile and versions . Still same error log
![s1](https://user-images.githubusercontent.com/12948351/46788921-ebf4ec00-cd43-11e8-9423-1fa7cbb03857.jpg)
![s2](https://user-images.githubusercontent.com/12948351/46788922-ec8d8280-cd43-11e8-9b87-d9d279d10a3a.jpg)

**Comment by paulb777** [comment]
What version of CocoaPods? `$ pod --version`

**Comment by ulaserdegor** [comment]
1.5.3, and i solved this problem. Thanks for your help. @paulb777

**Comment by masahironukui0523** [comment]
@ulaserdegor 
How did you soleved?

**Comment by SPopenko** [comment]
@ulaserdegor what was the solution for you? Could you share that, please?
