### ISSUE TITLE
Firebase.configure() leaks

### ISSUE THREAD

**Issue by paulsUsername** [firebase/firebase-ios-sdk#1892]
### [REQUIRED] Step 2: Describe your environment

Launching an app with Firebase added through cocoa pods, and then calling FirebaseApp.configure() causes many leaks.

If I don't call Firebase.configure() I get no leaks. If I call Firebase.configure() but I don't make any other calls to firebase I still get the same leaks.

### [REQUIRED] Step 3: Describe the problem

Creat app, add firebase, call FirebaseApp.configure() in didFinishLaunchingWithOptions

**Comment by paulb777** [comment]
@paulsUsername Please be more specific. What steps are you following to see the leaks? With Instruments? What are the leaks that you're seeing?

**Comment by paulsUsername** [comment]
Sorry, Paul I don't I had attached more detail.

To see the problem, I am calling  FirebaseApp.configure() in the didFinishLaunchingWithOptions.

```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        FirebaseApp.configure()
        
        return true
    }
```

If I remove that call to FirebaseApp.configure()  I get no leaks. I am identifying the leaks through instruments in Leaks. I am running the app through my iPhone X. I am making no other calls to Firebase after calling FirebaseApp.configure(). The leaks I am seeing are:

<img width="1277" alt="screen shot 2018-09-30 at 22 04 30" src="https://user-images.githubusercontent.com/32492218/46262703-de966100-c4fc-11e8-9416-85772ee65986.png">

<img width="1286" alt="screen shot 2018-09-30 at 22 04 19" src="https://user-images.githubusercontent.com/32492218/46262706-f968d580-c4fc-11e8-917b-6cdd029fa04f.png">


With FirebaseApp.configure() removed I get:

<img width="1278" alt="screen shot 2018-09-30 at 22 03 18" src="https://user-images.githubusercontent.com/32492218/46262704-f0780400-c4fc-11e8-8767-d704205a3861.png">


I have the following Firebase PODs added:

Using Firebase (5.9.0)
Using FirebaseAnalytics (5.2.0)
Using FirebaseAuth (5.0.4)
Using FirebaseAuthInterop (1.0.0)
Using FirebaseCore (5.1.4)
Using FirebaseDatabase (5.0.3)
Using FirebaseInstanceID (3.2.2)
Using FirebaseMessaging (3.1.2)
Using FirebaseStorage (3.0.2)

**Comment by paulb777** [comment]
I'm not able to reproduce by adding those pods to one of the quickstarts.

Are the leaks specific to ios12 and/or iPhone X?

**Comment by morganchen12** [comment]
Possibly #1917

**Comment by paulsUsername** [comment]
I'm not seeing the same (or any) leaks on my iPad on 11.4.1 or my iPhone 7 11.4.1. Still seeing them on iPhone X 12.0.
