### ISSUE TITLE
FIRESTORE INTERNAL ASSERTION FAILED: Invalid path (CoreData co-existence)

### ISSUE THREAD

**Issue by moflo** [firebase/firebase-ios-sdk#1898]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.0
  * Firebase SDK version: 5.9.0
  * Firebase Component: Firestore
  * Component version: 0.13.4

### [REQUIRED] Step 3: Describe the problem

Hi, we're trying to migrate existing users from a CoreData based app to a Firestore solution. Our app therefore uses both CoreData and Firestore concurrently. However, Firestore crashes upon app launch due to the HARD_ASSERT call in `resource_path.cc`; is there a work around?

FIRESTORE INTERNAL ASSERTION FAILED: Invalid path, model/resource_path.cc:37

```
2018-10-02 09:56:29.248359-0700 yyyy[5364:1614553] *** Assertion failure in static firebase::firestore::model::ResourcePath firebase::firestore::model::ResourcePath::FromString(const absl::string_view)(), /Users/xxxx/Developer/GroupTalent/yyyy/zzz/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/model/resource_path.cc:37
2018-10-02 09:56:29.252182-0700 yyyy[5364:1614553] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'FIRESTORE INTERNAL ASSERTION FAILED: Invalid path (x-coredata://ED782A94-9723-4FAF-8943-3A5279A10D86/Team/p3). Paths must not contain // in them. (expected path.find("//") == std::string::npos)'
*** First throw call stack:
(0x1d72dbef8 0x1d64a9a40 0x1d71f006c 0x1d7d2ac30 0x102eb899c 0x102eb8e3c 0x102ecfba0 0x102d6ad64 0x102ad9be8 0x102bd8d48 0x102bd9b80 0x20425752c 0x204257c10 0x203e53d28 0x203e549e8 0x203e55ce8 0x203de7e30 0x20423d998 0x1db8bda34 0x1db8c29c4 0x1db8219d4 0x1db8502f4 0x203ba9cfc 0x1d726a408 0x1d7269d08 0x1d7264cfc 0x1d72645b8 0x1d94d8584 0x203b8f558 0x102b32dfc 0x1d6d24b94)
```

#### Steps to reproduce:

Looks like this crash is only caused on a device, not on the simulator, when users upgrade from an older app version which contains legacy CoreData tables. These tables evidently contain resource paths with double slashes (//) in them, which I recall is an Apple standard URL format for CoreData resources. Can this restriction (HARD_ASSERT) be relaxed?
 
#### Relevant Code:

```
  AppDelegate.swift:   
        FirebaseApp.configure()
        let db = Firestore.firestore()
        let settings = db.settings
        settings.areTimestampsInSnapshotsEnabled = true
        db.settings = settings

resource_path.cc
       HARD_ASSERT(path.find("//") == std::string::npos,
              "Invalid path (%s). Paths must not contain // in them.", path);

```

**Comment by moflo** [comment]
This looks like an application specific issue, sorry.

**Comment by mikelehen** [comment]
Hey @moflo, can you elaborate on how you hit this?  Even if this was a application issue, we probably should have provided a better error message. In general it should be impossible to hit "FIRESTORE INTERNAL ASSERTION FAILED" errors.
