### ISSUE TITLE
addDocument with Network off doesn't return closure Swift

### ISSUE THREAD

**Issue by jimijon** [firebase/firebase-ios-sdk#1900]
* Xcode version: 10.0
  * Firebase SDK version: 5.90
  * Firebase Component: Firestore
  * Component version: 0.13.4

#### Steps to reproduce:

Turn off communications to Internet, add document

#### Relevant Code:

```
 var ref: DocumentReference? = nil
            ref = db.collection(Constants.fbShoppingListRoot)
                .document(shoppingListId)
                .collection("items")
                .addDocument(data: data) { err in
                    if let err = err {
                        print("Shopping List Item Error adding document: \(err)")
                    } else {
                        print("Shopping List Item Document added with ID: \(ref!.documentID)")
                        db.collection(Constants.fbShoppingListRoot)
                            .document(shoppingListId)
                            .collection("items")
                            .document(ref!.documentID)
                            .updateData(["id":ref!.documentID])
                        
                        self.dismiss(animated:false)
                        NotificationCenter.default.post(name: NSNotification.Name(rawValue: "UpdateList"), object: nil)
                    }
            }
```

**Comment by mikelehen** [comment]
addDocument() will only call its completion callback once the document has been written to the backend.  So if you are offline or call .disableNetwork(), then the callback won't be called until you come back online.  So I think this is probably working as intended, unless I've misunderstood what you're seeing or what you're expecting.

**Comment by jimijon** [comment]
Ok, so I am debugging with network off. 
So why does it need a completion at all? Is that for when persistence is off?

**Comment by jimijon** [comment]
I thought it was async so I can’t do the following:

 var ref: DocumentReference? = nil
            ref = db.collection(Constants.fbShoppingListRoot)
                .document(shoppingListId)
                .collection("items")
                .addDocument(data: data) { err in
                    if let err = err {
                        print("Shopping List Item Error adding document: \(err)")
                    } else {
                        print("Shopping List Item Document added with ID: \(ref!.documentID)")
                        db.collection(Constants.fbShoppingListRoot)
                            .document(shoppingListId)
                            .collection("items")
                            .document(ref!.documentID)
                            .updateData(["id":ref!.documentID])
                        
                    }
            }



Are you that addDocument is synchronous when network is off otherwise it is async?

**Comment by jimijon** [comment]
Thank you. That was a very helpful answer.
