### ISSUE TITLE
Compilation Error in Xcode With 5.3.1 version

### ISSUE THREAD

**Issue by haroldsati** [firebase/firebase-ios-sdk#1906]
Xcode version: 10
Firebase SDK version: 5.3.1
Firebase Component: Auth

I built a clean version from the 5.3.1 version and there is a compilation problem in Xcode. There is no much information about the error, just that code.

![screen shot 2018-10-03 at 4 45 25 pm](https://user-images.githubusercontent.com/1820917/46441890-8befbb80-c72d-11e8-9d7e-66d5904cb92e.png)

**Comment by paulb777** [comment]
Sorry - we don't support Firebase Unity issues here. 

Please refile at https://firebase.google.com/support/ or  https://github.com/firebase/quickstart-unity/issues
