### ISSUE TITLE
Firebase crashlytics

### ISSUE THREAD

**Issue by navaranjithavelladurai** [firebase/firebase-ios-sdk#1909]
I followed the basic steps to integrate the firebase crashlytics,&  i uploaded the run scripts steps.
here are my run scripts

GOOGLE_APP_ID = MyApp ID

"${PODS_ROOT}"/FirebaseCrash/upload-sym-util.bash "${PROJECT_DIR}/My File Key path"

i Uploaded the `Debug Info Format` as DWARF with dsym file in Built settings & i added the Google info plist too in my project

& i  Uploaded the missing required dSYMs file in firebase dashboard too, even though its asking again and again `missing required dSYMs` 

![screen shot 2018-10-04 at 12 05 21 pm](https://user-images.githubusercontent.com/43840824/46456851-e2acd200-c7cd-11e8-8662-6224604cf01d.png)
![screen shot 2018-10-04 at 12 05 39 pm](https://user-images.githubusercontent.com/43840824/46456855-e6405900-c7cd-11e8-8bc6-19b03ad358f5.png)

Kindly provide the suggestion to solve the issue

**Comment by crane-hiromu** [comment]
i have a same problem

**Comment by morganchen12** [comment]
If you're using bitcode, Apple will occasionally rebuild your app from bitcode in the App Store. You'll have to upload new dSYMs each time this happens, which you can download from the Apple developer center.

**Comment by navaranjithavelladurai** [comment]
Yes i downloaded the dSYMs file from the Apple developer account, still i have the same issue

**Comment by morganchen12** [comment]
I think this is what you're trying to say, but to make sure, have you also uploaded those new dSYMs to Crashlytics?
