### ISSUE TITLE
Move FirebaseMessaging to `GULUserDefaults`

### ISSUE THREAD

**Issue by ryanwilson** [firebase/firebase-ios-sdk#1919]
Currently Messaging uses `NSUserDefaults` for some persistent storage, but it should move to `GULUserDefaults` to avoid the crashing bug in iOS 11 due to UI being updated on the wrong thread by iOS.

**Comment by morganchen12** [comment]
@ryanwilson can we close this issue?

**Comment by ryanwilson** [comment]
Looks like it's still outstanding and relevant. Should be a very quick fix, though.
