### ISSUE TITLE
Possible race condition with iOS Firestore and security permissions on new document's sub-collection

### ISSUE THREAD

**Issue by adamjack** [firebase/firebase-ios-sdk#1940]
I wrote this first here, not knowing if it was my poor choice of permissions approach:

https://stackoverflow.com/questions/52673952/missing-or-insufficient-permissions-on-newly-created-documents-sub-collection

... but since it works on Android and when iOS is offline, I am starting to suspect a bug.

  * Xcode version: 10.0
  * Firebase SDK version: 5.9.0
  * Firebase Component: Firestore
  * Component version: 0.13.4

The code creates a document then (upon segue) immediately attempts to query/listen to a subcollection of that document, and it fails with a permissions error. Upon immediate retry it works. It works when offline (and it also works with Android.)

#### Steps to reproduce:

- Setup permissions as below
- Create a document in /events
- Attempt to query/listen to a subcollection /events/{ID}/notes (which does not yet exist.)
- Fails with permissions problems
- Retry ... and it works (although it still does not exist) but gets updates when added to.

#### Relevant Code:

```
// Access granted... via ownership
function accessGranted() {
  return resource.data.userId == request.auth.uid;
}
function accessGrantedTo(container,rootId) {
  return get(/databases/$(database)/documents/$(container)/$(rootId)).data.userId == request.auth.uid;
}

// Events...
match /events/{event} {
  allow read, update, delete: if accessGranted();
  allow create: if request.auth.uid != null;
}
match /events/{event}/notes/{note} {
  allow read, update, delete: if accessGrantedTo("events",event);
  allow create: if accessGrantedTo("events",event);
}
```

**Comment by morganchen12** [comment]
Hey, sorry for the late response on this. This is almost definitely a bug, but it may not be an iOS one. Can you move it over to [Firebase Support](https://firebase.google.com/support/contact/?category=troubleshooting)?
