### ISSUE TITLE
FIrebase says that i am blocked, and my requests are forbidden, please help!

### ISSUE THREAD

**Issue by AlexGZC** [firebase/firebase-ios-sdk#1941]
I have got an issue from Firebase:

**Error Domain=FIRAuthErrorDomain Code=17999 "An internal error has occurred, print and inspect the error details for more information." UserInfo={error_name=ERROR_INTERNAL_ERROR, NSLocalizedDescription=An internal error has occurred, print and inspect the error details for more information., NSUnderlyingError=0x28208da10 {Error Domain=FIRAuthInternalErrorDomain Code=3 "(null)" UserInfo={FIRAuthErrorUserInfoDeserializedResponseKey={
    code = 403;
    errors =     (
                {
            domain = global;
            message = "Requests to this API identitytoolkit method google.firebase.auth.v1.IdentityIdaasAuthenticationService.SignInWithIdp are blocked.";
            reason = forbidden;
        }
    );
    message = "Requests to this API identitytoolkit method google.firebase.auth.v1.IdentityIdaasAuthenticationService.SignInWithIdp are blocked.";
    status = "PERMISSION_DENIED";
}}}}**

Does someone know how to solve it?

**Comment by morganchen12** [comment]
Please [file a support ticket](https://firebase.google.com/support/contact/?category=troubleshooting) so they can look at your project information. What you're facing is most likely not an iOS SDK bug.
