### ISSUE TITLE
Failed to send push with Recipient time zone (iOS)

### ISSUE THREAD

**Issue by Ramesik** [firebase/firebase-ios-sdk#1946]
Environment

  * Xcode version: Any
  * Firebase SDK version: 5.10.0
  * Firebase Component: Messaging
  * Component version: 3.2.0

Problem

Failed to send  "Recipient time zone" push on devices with non 24-hours locale.

How to reproduce:

Send push on device with non 24-hours locale with recipient time zone enabled from Messaging console.

**Comment by paulb777** [comment]
Fixed by #1947
