### ISSUE TITLE
FCM token not refreshed after installing on new device

### ISSUE THREAD

**Issue by fschaus** [firebase/firebase-ios-sdk#1952]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: XCode 10.0
  * Firebase SDK version: 5.8.1
  * Firebase Component: Auth, Core , Database, Firestore, Messaging, Storage
  * Component version: FCM (3.1.2)

### [REQUIRED] Step 3: Describe the problem

One of my users recently changed to a new iPhone and reinstalled my app on his new phone. He successfully logged-in etc. but now he doesn't receive FCM notifications anymore. 

Prior to the phone switch he never had any issue and I didn't make any changes to my notification handling. For testing purposes I also tried to send him a notifications using the FCM console and it doesn't work either. I am also sure that my database correctly gets his latest token (as I deleted it from the DB and asked him to re-login on his phone and saw it being correctly re-added to the DB).

So the bug/ issue seems to come from the FCM token and its association with his APN token. 

Few questions:
• Could it be possible that the token did not get properly refreshed as he switched phone and that as such his "current" token is actually still associated with his old phone? 
• If this can happen, what's the right way to handle these exceptions? Notifications are the core building block of my app and I want as fail-proof a solution as possible. 
• To address my 2nd point, can I manually trigger a token refresh at every app re-start and if so how?

#### Steps to reproduce:

User switched phone. Reinstalled app on new phone. Re-logged in using Firebase Auth and pushed a token to the server. This token doesn't seem to match his phone as sending messages to it using cloud functions or the FCM console doesn't work. Notifications are properly enabled on his phone and my APN server is properly configured (i.e., works for all other users).

#### Relevant Code:

// Implementing Messaging Delegate at App start-up (in App Delegate)
```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
                
        FirebaseApp.configure()
        let db = Firestore.firestore()
        let settings = db.settings
        settings.isPersistenceEnabled = true
        settings.areTimestampsInSnapshotsEnabled = true
        db.settings = settings
        
        
        remoteNotif = launchOptions?[UIApplication.LaunchOptionsKey.remoteNotification] as? NSDictionary
        
        ReachabilityManager.shared.startMonitoring()
        
        Messaging.messaging().delegate = self
        Messaging.messaging().shouldEstablishDirectChannel = false
        UNUserNotificationCenter.current().delegate = self
        
// Done at other point in the app life-cycle
        //        if #available(iOS 10.0, *) {
        //            // For iOS 10 display notification (sent via APNS)
//                    UNUserNotificationCenter.current().delegate = self
        //
        //            let authOptions: UNAuthorizationOptions = [.alert, .badge, .sound]
        //            UNUserNotificationCenter.current().requestAuthorization(
        //                options: authOptions,
        //                completionHandler: {_, _ in })
        //        } else {
        //            let settings: UIUserNotificationSettings =
        //                UIUserNotificationSettings(types: [.alert, .badge, .sound], categories: nil)
        //            application.registerUserNotificationSettings(settings)
        //        }
        
 application.registerForRemoteNotifications()

        let center  = UNUserNotificationCenter.current()
        center.delegate = self
        return true
    }
```
// Get refresh token
```
    func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String) {
        print("Firebase registration token: \(fcmToken)")
        guard AuthService.instance.authToken != "" else {return}
        guard let userID = Auth.auth().currentUser?.uid else {return}
        UserDataService.instance.updateTokenToLatest(userID: userID)        
    }
```

// Update token on Server - I also call this method when the user log-ins and I download user's details from the server (so at start-up)
```
    func updateTokenToLatest(userID: String?) {
        guard let userID = userID else {return}
        let userRef = FbDB.collection("users").document(userID)

        InstanceID.instanceID().instanceID { [weak self](result, error) in
            
            if let error = error {
                print("Error fetching remote instange ID: \(error)")
                self?.pushNotificationToken = ""
                userRef.setData(["pushNotificationToken": self!.pushNotificationToken as Any], merge: true)
            } else if let result = result {
                print("Remote instance ID token: \(result.token)")
                
                let userToken = result.token
                self?.pushNotificationToken = userToken
                userRef.setData(["pushNotificationToken": self!.pushNotificationToken as Any], merge: true)
            }
        }
    }
```

**Comment by morganchen12** [comment]
It doesn't look like there's anything wrong with your code, though you could just directly set the FCM token in the didReceiveRegistrationToken callback instead of making another remote call.

Can you [file a support ticket](https://firebase.google.com/support/contact/?category=troubleshooting) and add the instance ID token that's not receiving notifications?

**Comment by fschaus** [comment]
Thanks @morganchen12! Filled a ticket and the FCM was not associated with an APN - turn out I had a corner case when I would not register properly for remotenotification (if a user declined authorization in my app but then manually turn notifications on in their phone's settings menu - my notif registration logic was only executed after a user granted authorization from the prompt).

I changed it and it now works great. Thanks again!
