### ISSUE TITLE
crash with report "Unlock of an os_unfair_lock not owned by current thread" in iOS12

### ISSUE THREAD

**Issue by dongfanggugu** [firebase/firebase-ios-sdk#1966]
* Xcode version: Version 10.0 (10A255)
  * Firebase SDK version: 4.11.0

### Describe the problem

crash with report "Unlock of an os_unfair_lock not owned by current thread " in iOS12

### trace
libsystem_platform.dylib	_os_unfair_lock_unowned_abort + 36
1	libsystem_platform.dylib	_os_unfair_lock_unlock_slow + 144
2	libsqlite3.dylib	sqlite3_snprintf + 3296
3	libsqlite3.dylib	sqlite3_snprintf + 2592
4	libsqlite3.dylib	sqlite3_free_table + 48616
5	libsqlite3.dylib	sqlite3_free_table + 63388
6	libsqlite3.dylib	sqlite3_free_table + 61260
7	libsqlite3.dylib	sqlite3_step + 28796
8   libsqlite3.dylib	sqlite3_step + 432
9	-[FIRASqliteStore executeSQLStatement:error:] + 4328945824

**Comment by paulb777** [comment]
Crashing issues with FIRASqliteStore have been fixed in Firebase 5.x. Please `pod update` to the latest version.

**Comment by zhouyantongiosDev** [comment]
@paulb777 
How to fix this problem?
iOS 12  _os_unfair_lock_unowned_abort
