### ISSUE TITLE
  Firebase 5.10.0's crash on iOS12   [TAGHitStore addPendingEvent:] 

### ISSUE THREAD

**Issue by zeqinjie** [firebase/firebase-ios-sdk#1978]
1)  when i update Firebase version to  5.10.0's crash. only iOS12
Crash LOG: [TAGHitStore addPendingEvent:]_block_invoke + 500  

Firebase 5.10.0
FirebaseAnalytics 5.2.0
FirebaseMessage 3.2.0
FirebasePerformace 2.1.2
GoogleTagManager 7.1.1
GTMSessionFetcher 1.2.1
GoogleAnalytics 3.17.0

2)
  * Xcode version: ___9.4.1__
  * Firebase SDK version: ___5.10.0__
 

3)

**Comment by paulb777** [comment]
Internally reported at b/118118795

**Comment by morganchen12** [comment]
@zeqinjie can you add the full crash log?

**Comment by morganchen12** [comment]
@zeqinjie is this still an issue?

**Comment by zeqinjie** [comment]
@morganchen12 yes. still crash on Firebase version 5.15.0


0	libsystem_platform.dylib
__os_unfair_lock_recursive_abort + 36
1	libsystem_platform.dylib
__os_unfair_lock_lock_slow + 276
2	libsqlite3.dylib
sqlite3_snprintf + 3124
3	libsqlite3.dylib
sqlite3_snprintf + 2592
4	libsqlite3.dylib
sqlite3_free_table + 48616
5	libsqlite3.dylib
sqlite3_free_table + 63388
6	libsqlite3.dylib
sqlite3_free_table + 61260
7	libsqlite3.dylib
sqlite3_step + 28916
8	libsqlite3.dylib
sqlite3_step + 432
9	house591
___31-[TAGHitStore addPendingEvent:]_block_invoke + 500
10	libdispatch.dylib
__dispatch_call_block_and_release + 24
11	libdispatch.dylib
__dispatch_client_callout + 16
12	libdispatch.dylib
__dispatch_lane_serial_drain$VARIANT$armv81 + 548
13	libdispatch.dylib
__dispatch_lane_invoke$VARIANT$armv81 + 412
14	libdispatch.dylib
__dispatch_workloop_worker_thread + 584
15	libsystem_pthread.dylib
_pthread_wqthread + 312

**Comment by paulb777** [comment]
Is this still an issue in Firebase 6.x?
