### ISSUE TITLE
Analytics setUserProperty is not recorded, no results when filter applied in console.

### ISSUE THREAD

**Issue by ugenlik** [firebase/firebase-ios-sdk#1980]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.0
  * Firebase SDK version: FirebaseAnalytics (5.2.0)
  * Firebase Component: FirebaseAnalytics (5.2.0)
  * Component version: (5.2.0)

### [REQUIRED] Step 3: Describe the problem

I did setup a User Property in the Firebase Console, then everytime a user logs in to the app I set the user role in the code and enable the Analytics.

It seems all the other events are recorded correctly but If I try to filter them by user property , there is no events recorded.

I have about 15 people testing the app, and it should have enough events to pass the threshold by now.....

#### Steps to reproduce:

1. Set the property in the console:

<img width="291" alt="screen shot 2018-10-22 at 11 07 52 am" src="https://user-images.githubusercontent.com/1995917/47300968-cbeae580-d5eb-11e8-844b-9a4ae378fd18.png">

2.  Set the user role in the app.

```
let userRole = "userRole"
Analytics.setUserProperty(userRole, forName: "Admin")
```

3. Make sure analytics are enabled.

```
AnalyticsConfiguration.shared().setAnalyticsCollectionEnabled(true)
```

4. Debug the stream view to make sure userRole property is getting set correctly.

<img width="1032" alt="screen shot 2018-10-22 at 10 58 23 am" src="https://user-images.githubusercontent.com/1995917/47301107-2126f700-d5ec-11e8-8ad5-bc59612d1972.png">

5.  Make sure enough events logged in to pass the threshold over couple of days.

<img width="791" alt="screen shot 2018-10-22 at 11 03 08 am" src="https://user-images.githubusercontent.com/1995917/47301150-3ef45c00-d5ec-11e8-9b94-8f8d01621a80.png">

6. After a couple days usage by testers go to console, filter by userRole property

<img width="738" alt="screen shot 2018-10-22 at 10 59 45 am" src="https://user-images.githubusercontent.com/1995917/47301217-6814ec80-d5ec-11e8-8b85-980e677aff1d.png">

RESULT: 

No events recorded when filter is applied:

<img width="747" alt="screen shot 2018-10-22 at 11 01 19 am" src="https://user-images.githubusercontent.com/1995917/47301323-9eeb0280-d5ec-11e8-999d-8174a918fc0f.png">

<img width="833" alt="screen shot 2018-10-22 at 11 02 52 am" src="https://user-images.githubusercontent.com/1995917/47301232-6fd49100-d5ec-11e8-804d-cf984ad7d0b3.png">

**Comment by paulb777** [comment]
Internally tracked at b/118396733

**Comment by htcgh** [comment]
Just for clarification, "userRole" is the user property name and "Admin" is the value, correct? If so, then  the call to Analytics should be `Analytics.setUserProperty("Admin", forName: "userRole")`.

**Comment by ugenlik** [comment]
@paulb777  @htcgh  

Oh boy, Dont I feel really stupid...... 

I wish the method was something like this

`Analytics.setUserProperty(value:"Admin", forKey: "userRole")`

for some reason when I read this section in Firebase code I thought yeah what I am doing is correct.
```
/// @param value The value of the user property. Values can be up to 36 characters long. Setting the
///     value to nil removes the user property.
/// @param name The name of the user property to set. Should contain 1 to 24 alphanumeric characters
///     or underscores and must start with an alphabetic character. The "firebase_", "google_", and
///     "ga_" prefixes are reserved and should not be used for user property names.
+ (void)setUserPropertyString:(nullable NSString *)value forName:(NSString *)name
    NS_SWIFT_NAME(setUserProperty(_:forName:));
```
