### ISSUE TITLE
Memory leaks on [FIRClearcutLogger sendNextPendingRequestWithCompletionHandler:]

### ISSUE THREAD

**Issue by agordeev** [firebase/firebase-ios-sdk#1994]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.0 (10A255)
  * Firebase SDK version: 5.10.0
  * Firebase Component: Core
  * Component version: 5.1.5

### [REQUIRED] Step 3: Describe the problem

Lots of memory leaks on [FIRClearcutLogger sendNextPendingRequestWithCompletionHandler:]. Is it possible to apply the same fix as here: https://github.com/firebase/firebase-ios-sdk/issues/1917?

#### Steps to reproduce:

Happens after calling FirebaseApp.configure()

Here's a typical stack trace:

```
    0 libsystem_malloc.dylib malloc_zone_realloc
    1 libsystem_malloc.dylib realloc
    2 CoreFoundation __CFSafelyReallocate
    3 Foundation _NSMutableDataGrowBytes
    4 Foundation -[NSConcreteMutableData appendBytes:length:]
    5 GoogleUtilities 0x1036c664f
    6 GoogleUtilities 0x1036c1753
    7 App -[FIRClearcutLogger sendNextPendingRequestWithCompletionHandler:]
    8 App -[FIRClearcutLogger sendLogsWithCompletionHandler:]
    9 libdispatch.dylib _dispatch_call_block_and_release
   10 libdispatch.dylib _dispatch_client_callout
   11 libdispatch.dylib _dispatch_lane_serial_drain$VARIANT$mp
   12 libdispatch.dylib _dispatch_lane_invoke$VARIANT$mp
   13 libdispatch.dylib _dispatch_workloop_worker_thread
   14 libsystem_pthread.dylib _pthread_wqthread
   15 libsystem_pthread.dylib start_wqthread
```

Get about 100 leaks on each launch.

**Comment by paulb777** [comment]
@agordeev Thanks for the report. What version of GoogleUtilities do you have installed? Version 5.3.4 includes a fix (#1970) for a crash from `FIRClearcutLogger` (#1964), that could be related.

**Comment by morganchen12** [comment]
Also, it seems the two calls to GoogleUtilities are unsymbolicated. Can you get a fully symbolicated stack trace?

**Comment by agordeev** [comment]
GoogleUtilities was updated to the latest (5.3.4) version as well.

>Also, it seems the two calls to GoogleUtilities are unsymbolicated. Can you get a fully symbolicated stack trace?

How to I do that? That's not the crash log, I was browsing through Xcode's Object graph

**Comment by yonomitt** [comment]
I think I'm seeing something similar. If it helps, my calls to GoogleUtilities are symbolicated:

   0 libsystem_malloc.dylib malloc_zone_malloc
   1 CoreFoundation _CFRuntimeCreateInstance
   2 CoreFoundation __CFStringCreateImmutableFunnel3
   3 CoreFoundation CFStringCreateWithBytes
   4 Foundation +[NSString stringWithUTF8String:]
   5 Foundation -[__NSConcreteUUID UUIDString]
   6 CFNetwork -[__NSCFURLSession initWithConfiguration:delegate:delegateQueue:]
   7 CFNetwork -[__NSURLSessionLocal initWithConfiguration:delegate:delegateQueue:]
   8 CFNetwork +[NSURLSession sessionWithConfiguration:delegate:delegateQueue:]
   9 Discovery -[GULNetworkURLSession sessionIDFromAsyncPOSTRequest:completionHandler:]
  10 Discovery -[GULNetwork postURL:payload:queue:usingBackgroundSession:completionHandler:]
  11 Discovery -[FIRClearcutLogger sendNextPendingRequestWithCompletionHandler:]
  12 Discovery -[FIRClearcutLogger sendLogsWithCompletionHandler:]
  13 libdispatch.dylib _dispatch_call_block_and_release
  14 libdispatch.dylib _dispatch_client_callout
  15 libdispatch.dylib _dispatch_lane_serial_drain
  16 libdispatch.dylib _dispatch_lane_invoke
  17 libdispatch.dylib _dispatch_workloop_worker_thread
  18 libsystem_pthread.dylib _pthread_wqthread
  19 libsystem_pthread.dylib start_wqthread

**Comment by paulb777** [comment]
Thanks @yonomitt, but the latest GoogleUtilities didn't make Firebase 5.11.0 - see https://github.com/firebase/firebase-ios-sdk/releases. It will be in the next zip download release.

**Comment by Jay-iTechPioneer** [comment]
@paulb777 I have also same issue with latest pod version.

**Comment by paulb777** [comment]
@Jay-iTechPioneer To confirm, do you still have the issue with the Google Utilities 5.3.5 that released yesterday?

**Comment by Jay-iTechPioneer** [comment]
@paulb777 in 5.3.5 it is fixed and works fine.
Thank you !!

**Comment by Jay-iTechPioneer** [comment]
> @Jay-iTechPioneer To confirm, do you still have the issue with the Google Utilities 5.3.5 that released yesterday?

@paulb777 in 5.3.5 it is fixed and works fine.
Thank you !!
