### ISSUE TITLE
Crash in +[GAI threadMain:]

### ISSUE THREAD

**Issue by insidegui** [firebase/firebase-ios-sdk#200]
* Xcode version: 8.3.3
  * Firebase SDK version: 3.12
  * Firebase Product: Analytics (I think)

### [REQUIRED] Step 3: Describe the problem

We are experiencing hundreds of crashes in `+[GAI threadMain:]`, it looks like they happen mostly when the app is in the background.

#### Steps to reproduce:

We don't know how to reproduce it, we're only seeing reports on Crashlytics.

I have attached the crash log.
[crashlog.txt](https://github.com/firebase/firebase-ios-sdk/files/1228338/com.peixeurbano.peixeurbanoapp_issue_12147_crash_ce38135e280d4de9b67516caaa70d0fb_1584e9e1828611e7aa2056847afe9799_0_v2.txt)

**Comment by rsattar** [comment]
Thanks for the crash report, that's really helpful! From reading it, two things are sticking out:

1) The device has "< 1%" disk space. Could this possibly be an extreme case when nothing can be written to anything?
2) As you said, this seems to happen mostly when the app is in the background. The FirebaseInstanceID is attempting to read/write to the Keychain during this time.

We just released a new version of the FirebaseInstanceID SDK (2.0.1)  that adjusts the accessibility of some items to be available while the device is locked. When you next update your app, would you mind updating to the latest SDK, to see if that gets rid of the issue?

Finally if it's possible to share the public link to a particular crash report that would be extra useful. Thanks!

**Comment by insidegui** [comment]
> The device has "< 1%" disk space. Could this possibly be an extreme case when nothing can be written to anything?

I noticed that, but not every crash report shows that characteristic, just the sample one I sent you.

> this seems to happen mostly when the app is in the background

Yes, currently only about 13% of the crashes happen with the app in focus.

> When you next update your app, would you mind updating to the latest SDK, to see if that gets rid of the issue?

Sure, will do and let you know.

**Comment by paulb777** [comment]
This looks like a Google Analytics crash. Please open an issue at https://issuetracker.google.com/issues?q=componentid:187400
