### ISSUE TITLE
Crashlytics support for tvOS?

### ISSUE THREAD

**Issue by ninokierulf** [firebase/firebase-ios-sdk#2009]
Was trying Crashlytics in tvOS but I can't even get the **firebase** crashlytics setup to be successful. (I've been using Fabric Crashlytics for tvOS for about 2 years)
I ran in my tvOS application and it seems nothing is being sent to google's server.

I found a [tweet conversation](https://twitter.com/fabric/status/1040671020837949441) stating that crashlytics will be supported for tvOS. Is it available now or for 2019? I'm asking because Fabric will be sunset on November 30, 2018.

PS: I've done a quick setup in iOS and can confirm that it works as I receive the successful setup and initial crash confirmation, so I'm pretty sure that tvOS doesn't work when I tried.

_Originally posted by @ninokierulf in https://github.com/firebase/firebase-ios-sdk/issues/10#issuecomment-433266598_

**Comment by paulb777** [comment]
Crashlytics for tvOS is documented at https://docs.fabric.io/apple/crashlytics/tvos.html and support will continue after the Fabric app sunset on November 30, 2018.

Firebase console and analytics integrations do not currently exist.

**Comment by ninokierulf** [comment]
Thank you for the reply, I failed to mention that I'm already using Crashlytics for tvOS via Fabric for about 2 years now. I was just exploring the migration to Firebase as the end of Fabric is inevitable. Even if Crashlytics will be supported after the app sunset on Nov 30, 2018, Fabric is still planned to end by mid 2019 so I need to make sure I've done my due diligence on the matter. Eventually I still need to find out how to use Crashlytics with Firebase for tvOS.

**Comment by paulb777** [comment]
@ninokierulf Peripherally, yes. We can't share most progress since Crashlytics is not currently part of the open source part of Firebase on GitHub.

**Comment by sergiou87** [comment]
I've been using Crashlytics for tvOS via Fabric for a few years now too, now trying to do the migration but we can't migrate it because the iOS app shares the same bundle identifier. Looking forward to migrate the tvOS app to Firebase too!

**Comment by NikKovIos** [comment]
Here says that TvOS is included in Firebase https://twitter.com/fabric/status/1040701431379124224
But still i can't make it work :(

**Comment by samedson** [comment]
Hey sorry we didn't update this. You can use Crashlytics on macOS and tvOS in the Firebase Console now. You need to set up the app as an iOS app in the console, but if you install:
```
pod 'Crashlytics'
pod 'FirebaseCore'
```

You can follow the instructions at https://firebase.google.com/docs/crashlytics/get-started?platform=ios to install it fully

**Comment by rojas** [comment]
What should I do if my iOS and tvOS app uses the same bundle identifier? How can I setup both on the same Firebase project?

**Comment by samedson** [comment]
Right now we have a limitation that if they have the same bundle ID, they can't be in the same Firebase project. We recommend using separate projects for now.

**Comment by rojas** [comment]
Is this limitation on the road map? Do you think Firebase will support this case before Fabric deprecation on March 31st? Just trying to avoid creating new projects if possible.

**Comment by ArtFeel** [comment]
It's a pity that we still can't migrate correctly and compare iOS and tvOS analytics in single project.

**Comment by idrougge** [comment]
Two years ago, we ruled out Firebase because it wasn't supported on tvOS. I really, really would have expected tvOS support to be a given by now.
