### ISSUE TITLE
Remove "static_framework" from open-source pods

### ISSUE THREAD

**Issue by SebastianSingle99** [firebase/firebase-ios-sdk#2022]
Some podspec files like FirebaseCore.podspec or FirebaseMessaging.podspec have set `s.static_framework = true`, although they are now open sourced and could be used as dynamic framework (use_frameworks!).
Cocoapods says:
`[!] The 'Pods-xxx target has transitive dependencies that include static frameworks: (FirebaseMessaging)`

Setting `static_framework` to false works as expected. Could `static_framework` be removed? 
Then each developer can decide if he wants to use dymanic frameworks or use the newer `use_modular_headers`-feature to build static libraries.

**Comment by paulb777** [comment]
@SebastianSingle99 Thanks for the suggestion! 

There are a few bugs with CocoaPods 1.5.x that prevent this, but it should be doable with CocoaPods 1.6.x. Also it would be a breaking change for Firebase. 

I've added it to the next major release milestone for deeper investigation.

**Comment by paulb777** [comment]
My biggest concern about this change would be causing some developers to have several more dynamic frameworks along with a potential performance impact. 

We might want to wait for this until CocoaPods has the capability to pick and choose which pods are built dynamically and statically.

**Comment by paulb777** [comment]
This is a bigger change than we want to make for the default Firebase use case.  

Likely we'll wait for better CocoaPods support.

If anyone wants this in the meantime, they can use modified podspec version.

**Comment by paulb777** [comment]
Reconsider for Firebase 7 since CocoaPods 1.9.0 adds the ability for Podfile's to specify static or dynamic at an individual pod granularity.

**Comment by paulb777** [comment]
CocoaPods 1.9.0 only added more flexibility on the `use_frameworks!` directive and pushed out the proposal to provide granularity at the individual pod.

**Comment by rickrvo** [comment]
I would like to upvote this request. Having static framework causes great limitation over architecture decisions of modular apps. The best scenario, for us users, would be for Firebase to have both options, if you insist of having a static framework. But I know that maintaining both projects could complicate a lot. This request goes to all Google's static frameworks, like GoogleMaps... but those are relatively easy to workaround... but frameworks like FirebaseMessaging that need to be on the AppDelegate are the ones that really limit our options if we are using dynamic frameworks on the project

**Comment by jamesyorke** [comment]
I too would like to upvote this request.

**Comment by paulb777** [comment]
Adding back to the Firebase 7 milestone for consideration at the next breaking change release.  The `use_frameworks! :linkage => :static` option introduced in CocoaPods 1.9.0 provides an option that should enable most apps to still choose to get static frameworks.  Unfortunately, they still would lose the ability to have Firebase be static and other Pods be dynamic - but possibly that would be ok.

**Comment by mironal** [comment]
I too would like to upvote this request.

**Comment by paulb777** [comment]
Now fixed by #6557 and will release with Firebase 7.0.0.

**Comment by awaisiosdev** [comment]
Thank you soo much for this.

**Comment by Gladkov-Art** [comment]
Thanks you! Do you have any suggestions how to use Firebase as dynamic frameworks without CocoaPods?

**Comment by paulb777** [comment]
@Gladkov-Art We will only support dynamic frameworks from CocoaPods in the near-term, but the source is available in this repo to use however you like.
