### ISSUE TITLE
Firebase download error Error Domain=FIRStorageErrorDomain Code=-13000

### ISSUE THREAD

**Issue by ilyon** [firebase/firebase-ios-sdk#2040]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.4.1
  * Firebase SDK version: 5.9.0
  * Firebase Component: Auth,Storage
  * Component version: _____

### [REQUIRED] Step 3: Describe the problem
I am trying to download an data from Firebase, I get fail only on iOS 8 devices, other devices run good, I'm getting this error::

> Optional - Some : Firebase download error Error Domain=FIRStorageErrorDomain Code=-13000 "An unknown error occurred, please check the server response." UserInfo=0x1471bf10 {ResponseErrorDomain=NSURLErrorDomain, NSErrorFailingURLKey=https://firebasestorage.googleapis.com/v0/b/api-project-xxxxxxxxxxx.appspot.com/o/xxxxxxxxxxxxxxxxx%2Fdata.xx?alt=media, object=xxxxxxxxxxxxxxxxx/data.xx, NSErrorFailingURLStringKey=https://firebasestorage.googleapis.com/v0/b/api-project-xxxxxxxxxxxx.appspot.com/o/xxxxxxxxxxxxxxxxxx%2Fdata.xx?alt=media, ResponseErrorCode=-1100, bucket=api-project-xxxxxxxxxxxxx.appspot.com, NSLocalizedDescription=An unknown error occurred, please check the server response.}

here is the detail:https://stackoverflow.com/questions/53112383/firebase-download-error-error-domain-firstorageerrordomain-code-13000

**Comment by paulb777** [comment]
See https://github.com/firebase/firebase-ios-sdk/issues/1888#issuecomment-431544373 and the successive comment
