### ISSUE TITLE
Notification Service Extension does not handle data messages when using Firebase Data Message

### ISSUE THREAD

**Issue by yigitserin** [firebase/firebase-ios-sdk#2048]
Firebase **data** notifications do not trigger Notification Service Extensions didReceive method.
I am using latest version and this is my payload.
```
{
  "registration_ids": [
        "...",
        "..."
    ],
  "mutable_content": true,
  "content_available": true,
  "data": {
    "click_action": "AndroidIntent"
    "message": "Notification Body",
    "myDataField": "11",
    "location": "3",
    "imageurl": "http://image.com/13fd.png"
  }
}
```
If I add a "notification" object to this payload, it works in iOS but that breaks android functionality. So I would like to avoid that.

**Comment by morganchen12** [comment]
This is Apple functionality, not Firebase. Notification extensions cannot modify silent notifications (the notification must be configured to display an alert).

https://developer.apple.com/documentation/usernotifications/unnotificationserviceextension
