### ISSUE TITLE
I cant see the data saved in the control tab , but native app can show the new data created . why.

### ISSUE THREAD

**Issue by smartPiz** [firebase/firebase-ios-sdk#2054]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: _____
  * Firebase SDK version: _____
  * Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by wilhuff** [comment]
Hi! Please fill out the details of the form above. It really helps us help you. As it stands I can't even tell which product you're using.

Also please give details describing how to reproduce the problem in considerably more detail. Describe the steps you took, what you expected to see and what you actually saw.

As it stands I can't help you with this issue.
