### ISSUE TITLE
Memory leak in GULNetwork.m

### ISSUE THREAD

**Issue by RamblinWreck77** [firebase/firebase-ios-sdk#2060]
### Step 2: Describe your environment

  * Xcode version: 10.1
  * Firebase SDK version: 5.12.0
  * Firebase Component: GoogleUtilities
  * Component version:  5.3.4

### Steps to reproduce:

-Setup a scheme to detect memory leaks by:
1) Scheme/edit/run/diagnostics
2) enable Malloc Scribble, Guard Edges, and Malloc

-Make a test project app that:
1) Calls FirebaseApp.configure() in App Delegate, setup info.plist etc
2) In your single-view controller, fire "Analytics.logEvent("blah_blah", parameters: ["AppVersion" : "blah blah"])" in viewDidAppear. Maybe do 5-10 randoms for good measure.

-Now go to the debug navigator, lick the top right icon in the window and select "View memory graph hierarchy"

-Observe leaks:

<img width="1421" alt="screen shot 2018-11-08 at 11 13 40 am" src="https://user-images.githubusercontent.com/22692130/48211451-7fbbd700-e347-11e8-9281-d4e4f4e8ef71.png">

<img width="1058" alt="screen shot 2018-11-08 at 11 15 17 am" src="https://user-images.githubusercontent.com/22692130/48211533-ae39b200-e347-11e8-89e3-c00181a37ce0.png">

**Comment by morganchen12** [comment]
Fixed in #2061.

**Comment by RamblinWreck77** [comment]
@morganchen12 Thank you so much!
