### ISSUE TITLE
Just updated pod, didReceiveRegistrationToken is not called anymore

### ISSUE THREAD

**Issue by FlorentPottevin** [firebase/firebase-ios-sdk#2063]
* Xcode version: 10.1
  * Firebase SDK version: 5.12.0
  * Firebase Component: Messaging
  * Component version: 3.2.1

I've simply updated the pods and it stopped working.
It worked fine until now and nothing has changed.

Why is didReceiveRegistrationToken not called anymore?

**Comment by morganchen12** [comment]
There's not enough information here to debug the issue. Please show how you've integrated Messaging in code, then reopen the issue.

**Comment by paulb777** [comment]
Also, let us know what version you updated from.  5.12.0 had no changes for Messaging.
