### ISSUE TITLE
FR: Mac OS + Apple Extension support

### ISSUE THREAD

**Issue by jxy4769** [firebase/firebase-ios-sdk#2072]
### Environment
  * Xcode version: Version 10.1
  * Firebase SDK version: 5.1.7
  * Firebase Component: Crashlytics
  * Component version: 3.11.1

### THE PROBLEM
The issue is to integrate Crashlytics to Mac OS Apple Extensions. I was trying to implement
Crashlytics but it is not officially supported. I wonder if there is a hack/workout to allow Apple Extensions to work with Crashlytics! In addition, Apple extension applications do not call the defined app delegate so the initialization of FIRapp may be needed to placed else where.

```
Firebase/Core][I-COR000028] tvOS and macOS SDK support is not part of the official Firebase product. Instead they are community supported. Details at https://github.com/firebase/firebase-ios-sdk/blob/master/README.md.

**Comment by ryanwilson** [comment]
Hi @jxy4769 - so we can better understand the use case, what App Extensions were you trying to integrate with?

**Comment by ryanwilson** [comment]
Going to close this since we don't know which extensions were requested and there hasn't been any other activity - please re-open if there's still a request for macOS extensions support. Thanks!
