### ISSUE TITLE
Extra argument 'toFile' in call

### ISSUE THREAD

**Issue by jr00n** [firebase/firebase-ios-sdk#2080]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.1
  * Firebase SDK version: 5.12.0
  * Firebase Component:  Storage
  * Component version: 3.0.3

### [REQUIRED] Step 3: Describe the problem
Can't Build project
Extra argument 'toFile' in call  -> refrence.write(toFile: localURL)

#### Steps to reproduce:
Build code -> Can't compile!

Error message: Extra argument 'toFile' in call

#### Relevant Code:

        let storage = Storage.storage()
        let storageRef = storage.reference()
        
        let islandRef = storageRef.child("audio/track01.mp3")
        let localURL = URL(string: "path/to/track01.mp3")!
       
        
        // Download to the local filesystem
        let downloadTask = islandRef.write(toFile: localURL) { url, error in
            if let error = error {
                print(String(describing: error))
            } else {
                self.audioPlayer = try AVAudioPlayer(contentsOf: url)
                self.audioPlayer.play()
            }
        }

**Comment by morganchen12** [comment]
Looks like this is a bad error thrown by Swift. The compiler error is there because you're not handling the error thrown by the `try` statement when initializing your `AVAudioPlayer`. If you handle or ignore the error either using a `catch` statement or a `try?`/`try!` the error goes away.
