### ISSUE TITLE
Just a heads up, it appears 5.13.0 did not release to Cocoapods

### ISSUE THREAD

**Issue by RamblinWreck77** [firebase/firebase-ios-sdk#2082]
Hello! I Noticed

Utilities-5.3.6

when running pod outdated and when checking the releases tab I saw 5.13.0 had *also* released but wasn't available on cocoapods. Just thought I'd let you know as it's easy to forget.

Thanks for all your hard work!

**Comment by paulb777** [comment]
Thanks - 5.13.0 is still being tested and not yet pushed to CocoaPods.

**Comment by paulb777** [comment]
A good way to check the status of a release is to check the corresponding [milestone](https://github.com/firebase/firebase-ios-sdk/milestones).  We'll close the milestone after publishing to CocoaPods.
