### ISSUE TITLE
Fatal Error for getDocuments(): NSArray element failed to match the Swift Array Element type

### ISSUE THREAD

**Issue by rs-georg** [firebase/firebase-ios-sdk#2085]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.0
  * Firebase SDK version: Latest Carthage binary (5.13.0)
  * Firebase Component: Firestore
  * Component version: 0.15.0

### [REQUIRED] Step 3: Describe the problem

When requesting all documents of a collection the app crashes with a fatal error: `Thread 1: Fatal error: NSArray element failed to match the Swift Array Element type`

#### Steps to reproduce:
Create a document:
```swift
let db = Firestore.firestore()
db.collection("chats").addDocument(data: [
	"id": "some-id",
	"sender": "my-name",
	"text": "lorem ipsum"
])
```

Then retrieve the document again:
```swift
let db = Firestore.firestore()
db.collection("chats").getDocuments { snapshot, error in
	if let error = error {
		print("Error. \(error)")
	} else {
		for document in snapshot!.documents {
			print("\(document.documentID) => \(document.data())")
		}
	}
}
```

The error occurs in the line `for document in snapshot!.documents {`

**Comment by mikelehen** [comment]
I can't reproduce this with the latest Firebase pods.  I notice you're using carthage, so perhaps that is related.  I am also a little confused by the version numbers you shared:

> Firebase SDK version: Latest Carthage binary (5.13.0)
> Firebase Component: Firestore
> Component version: 0.15.0

The latest version I see in https://dl.google.com/dl/firebase/ios/carthage/FirebaseFirestoreBinary.json is 5.12.0, and I think the latest Firestore component version is 0.14.0.

@paulb777 Any ideas?  Else, @rs-georg Can you try using CocoaPods and see if you can reproduce?  That way we can verify if this is carthage-specific.

**Comment by paulb777** [comment]
There are no component versions in the Carthage version. Everything is versioned with the Firebase version.  5.13.0 has not released for either CocoaPods or Carthage, so 5.12.0 is the latest available version.

**Comment by morganchen12** [comment]
I don't think this is a packaging issue. This sort of error occurs if you have an array that Swift assumes is homogenous and contains only a certain type, but is actually not homogenous. 

Can you try going through your code sample and adding explicit type declarations for all of the variables? Also, can you include what your database contents are? I suspect if you try this with an empty db the error won't reproduce.

**Comment by morganchen12** [comment]
@rs-georg, please comment here again if this is still an issue and I'll reopen it.

**Comment by zdnk** [comment]
I am encountering this issue right now.
https://stackoverflow.com/questions/56201501/firestore-nsarray-to-swift-array-match-error

**Comment by morganchen12** [comment]
@zdnk can you share a sample Firestore collection that reproduces this issue?

**Comment by zdnk** [comment]
I figured it out. The issue is that I had Firebase dependency in multiple targets in Podfile. I need it in my framework and in the main target for the app. It caused that Firebase was eventually linked twice so the there were two signatures of the same classes from Firebase.

However it sucks you cannot link firebase in multiple targets via Cocoapods.

**Comment by paulb777** [comment]
You cannot link Firebase, or any static libraries, from multiple dynamic library targets.  However, you can link Firebase from multiple static library targets.
