### ISSUE TITLE
Firebase/Performance 5.12.0 conflicts with NearbyMessages 1.1.1

### ISSUE THREAD

**Issue by stonesam92** [firebase/firebase-ios-sdk#2094]
We're unable to build a project that includes the latest versions of `Firebase/Performance` (5.12.0) and Google `NearbyMessages` (1.1.1) due to a duplicate symbol linker error.

#### Describe your environment

- Xcode version: 10.1
- Firebase SDK version: 5.12.0
- Firebase Component: Performance
- Firebase/Performance version: 5.12.0
- NearbyMessages version: 1.1.1
- CocoaPods version: 1.5.3

#### Steps to reproduce:

- Create a Cocoapods project with `Firebase/Performance` 5.12.0 and `NearbyMessages` 1.1.1 defined as dependencies. 
- When you try to build we get the following linker error:

`duplicate symbol _kuint128max in:
    /Users/samstone/projects/ios/MobileApp/Pods/NearbyMessages/Libraries/libGNSMessages.a(int128.o)
    /Users/samstone/projects/ios/MobileApp/Pods/FirebasePerformance/Frameworks/FirebasePerformance.framework/FirebasePerformance(int128_9709c16cf10a95a527774d514a8bda0e.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by paulb777** [comment]
Confirmed:

```
~/qs/quickstart-ios/messaging/Pods/NearbyMessages/Libraries (master) $ nm libGNSMessages.a | grep kuint128max
---------------- S _kuint128max
                 U _kuint128max

~/qs/quickstart-ios/messaging/Pods/FirebasePerformance/Frameworks/FirebasePerformance.framework (master) $ nm FirebasePerformance | grep kuint128max
---------------- S __ZN4absl11kuint128maxE
---------------- S _kuint128max
```

**Comment by paulb777** [comment]
Internally tracked at b/119758936

**Comment by allright** [comment]
The same issue (but only in DEBUG)
duplicate symbol __ZNSt3__114numeric_limitsIN4absl7uint128EE8digits10E in:
    /Users/allright/Library/Developer/Xcode/DerivedData/TimePhone-fdjnayfcnyckukapeqmsvoqkvcdu/Build/Products/Debug-iphoneos/FirebaseFirestore/FirebaseFirestore.framework/FirebaseFirestore(int128.o)
    /Users/allright/TimePhone/timephone/TimePhone/Pods/FirebasePerformance/Frameworks/FirebasePerformance.framework/FirebasePerformance(int128_cf14b946969ae14548ab5ca0a450fcfb.o)
