### ISSUE TITLE
Error when adding Firebase to my iOS project without CocoaPods.

### ISSUE THREAD

**Issue by scourgy** [firebase/firebase-ios-sdk#2103]
I am trying to add Firebase to my project and especially their barcode reader frameworks (Vision). I have followed these instructions:

https://www.mokacoding.com/blog/setting-up-firebase-without-cocoapods/

I have added the folder that contains what I want - MLVision with all the frameworks there. I have imported the header files, also did @import GoogleMobileVision in my main file.

The problem is that I am getting the following error when trying to run my project:

```
Undefined symbols for architecture arm64:
  "_kFIRLoggerMLKit", referenced from:
      _FIRMLKitLog in FirebaseMLCommon(FIRMLKitLogger_1ae3a68aef0eb3884b887b653b700305.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any ideas how to solve this one? Thanks in advance.

Here is a screenshot of what I have added:
[https://i.imgur.com/ttqplc0.png](https://i.imgur.com/ttqplc0.png)

**Comment by paulb777** [comment]
`FIRMLKitLog` is defined in FirebaseMLCommon.framework. Make sure you've included that framework in your link.

```
~/sample/Carthage/Build/iOS/FirebaseMLCommon.framework (master) $ nm FirebaseMLCommon | grep FIRMLKitLog
                 U _FIRMLKitLog
FirebaseMLCommon(FIRMLKitLogger_4a96f641767bb7a6a0ec53c79b8453a7.o):
---------------- T _FIRMLKitLog
```

**Comment by paulb777** [comment]
Locking for additional comments since this is a question and also asked at https://stackoverflow.com/questions/53410037/error-when-adding-firebase-to-my-ios-project-without-cocoapods/53415028
