### ISSUE TITLE
FirebaseStorage adding white stripe to my images

### ISSUE THREAD

**Issue by Idomo** [firebase/firebase-ios-sdk#2104]
* Xcode version: 10.1
  * Firebase SDK version: 5.4.1
  * Using FirebaseAuth (5.0.2)
  * Using FirebaseCore (5.0.6)
  * Using FirebaseStorage (3.0.0)

#### Description:

When uploading image via FirebaseStorage, it'll add some white stripes (like border) on some sides of it.
*Notice that if you'll look at the photo before uploading it won't include those stripes.
The result of uploading full black image (open it on black screen, e.g in Chrome or photoshop):
![img_1839](https://user-images.githubusercontent.com/26777129/48863449-15d51000-edd2-11e8-96f7-7552effdbddd.JPG)

#### Relevant Code:
This is my function to upload an image: 
```
static func uploadImage(_ image: UIImage, to folder: Folder, progressBlock: @escaping (_ percentage: Double) -> Void = { _ in }, completionBlock: @escaping (_ url: String?, _ error: String?) -> Void) {
        let storage = Storage.storage()
        let storageReference = storage.reference()

        let imageName = "\(Int(image.size.height))\(Int(image.size.width))\(Date().millisecondsSince1970).jpg" // Uniqu name
        let imageReference = storageReference.child(folder.description).child(userId!).child(imageName)

        let imageSizeToCalculate = max(image.size.width, image.size.height)
        let percentage: CGFloat = imageSizeToCalculate > 1200 ? 1200 / imageSizeToCalculate : 1.0

        if let imageData = image.resizeTo(percentage: percentage).jpegData(compressionQuality: 0.8) {
            let metadata = StorageMetadata()
            metadata.contentType = "image/jpeg"
            let uploadtask = imageReference.putData(imageData, metadata: metadata) { _, error in
                imageReference.downloadURL { url, error in
                    guard let url = url else {
                        return print("Error: \(String(describing: error))")
                    }
                    DispatchQueue.main.async {
                        completionBlock(url.absoluteString, nil)
                    }
                }
            }
            ...
        } else {
            completionBlock(nil, "Image couldn't be converted to Data")
        }
    }
```

**Comment by Idomo** [comment]
@paulb777 Any progress with this issue? it's very annoying.

**Comment by morganchen12** [comment]
Hey @Idomo, is this the case for images uploaded via Firebase Console? My guess is there's a rounding issue in the image size calculation in your upload code.

**Comment by Idomo** [comment]
@morganchen12 Looks like it doesn't happen when uploading from Firebase Console.
May you help me to find out what can cause this issue?

This is my code of resizing the image:
```
/// Resize the image to specific percentage of it (1.0 = 100%)
func resizeTo(percentage: CGFloat) -> UIImage {
        let canvasSize = CGSize(width: size.width * percentage, height: size.height * percentage)
        UIGraphicsBeginImageContextWithOptions(canvasSize, false, scale)
        defer { UIGraphicsEndImageContext() }
        draw(in: CGRect(origin: .zero, size: canvasSize))
        guard let resizedImage = UIGraphicsGetImageFromCurrentImageContext() else {
            print("Error with UIGraphics in resizeTo(percentage:)")
            return self
        }
        return resizedImage
}
```

**Comment by morganchen12** [comment]
Looks similar to [this issue](https://github.com/AliSoftware/UIImage-Resize/issues/3). Maybe you could apply the same fix to your code?

**Comment by Idomo** [comment]
> Looks similar to [this issue](https://github.com/AliSoftware/UIImage-Resize/issues/3). Maybe you could apply the same fix to your code?

Unfortunately it doesn't seems to fix the problem for me... (tried also use ceil())

**Comment by morganchen12** [comment]
@Idomo looks like this happens when your image dimensions are non-integer values. This code seems to fix the issue:

```swift
extension UIImage {
  /// Resize the image to specific percentage of it (1.0 = 100%)
  func resizeTo(percentage: CGFloat) -> UIImage {
    let canvasSize = CGSize(width: floor(size.width * percentage), height: floor(size.height * percentage))
    UIGraphicsBeginImageContextWithOptions(canvasSize, false, scale)
    defer { UIGraphicsEndImageContext() }
    draw(in: CGRect(origin: .zero, size: canvasSize))
    guard let resizedImage = UIGraphicsGetImageFromCurrentImageContext() else {
      print("Error with UIGraphics in resizeTo(percentage:)")
      return self
    }
    return resizedImage
  }

}
```

I'll close this issue since it's not a Firebase issue, but if you still have issues feel free to keep commenting (or consider posting a StackOverflow question).

**Comment by Idomo** [comment]
@morganchen12 This is what I've done after the link you sent before.
Like I said, it did made the stripes thinner, but there are still visible on black image (If you'll play with it's size on black background you'll see it)

**Comment by morganchen12** [comment]
Looks like you can avoid this issue by using a scale of 1 for all image resizing, though I'm not sure that's the behavior you want. IIRC The white bar on the side is a result of anti-aliasing when drawing the image for screen scales greater than 1. Here's an updated code snippet.

```swift
extension UIImage {
  /// Resize the image to specific percentage of it (1.0 = 100%)
  func resizeTo(percentage: CGFloat) -> UIImage {
    let hasAlpha = cgImage.flatMap {
      let alphaInfo = $0.alphaInfo
      return (alphaInfo != .none && alphaInfo != .noneSkipFirst && alphaInfo != .noneSkipLast)
    } ?? false
    let canvasSize = size.applying(CGAffineTransform(scaleX: percentage, y: percentage))
    // Always using 1 here since the image isn't necessarily going to be displayed on this device.
    UIGraphicsBeginImageContextWithOptions(canvasSize, false, 1)
    defer { UIGraphicsEndImageContext() }
    draw(in: CGRect(origin: .zero, size: canvasSize))
    guard let resizedImage = UIGraphicsGetImageFromCurrentImageContext() else {
      print("Error with UIGraphics in resizeTo(percentage:)")
      return self
    }
    return resizedImage
  }

}
```

**Comment by Idomo** [comment]
@morganchen12 The `floor` solution was better, with this code the stripes looks like they looks without the `floor`.
Thank you very much for your time, at least you helped me to make this look better then before [=
