### ISSUE TITLE
Dynamic Links shouldn't read from `defaultOptions`

### ISSUE THREAD

**Issue by ryanwilson** [firebase/firebase-ios-sdk#2112]
https://github.com/firebase/firebase-ios-sdk/blob/c724f9d1e8c3d2f7a44b8959983e1ebaa3eaa5cb/Firebase/DynamicLinks/FDLURLComponents/FIRDynamicLinkComponentsKeyProvider.m#L29

Currently Dynamic Links reads from the defaultOptions plist to get the API key - this should be fetched from `FIRApp` incase developers manually set options.

This was discovered by @forsen in #230.

**Comment by doddyth** [comment]
Any update for this issue? Right now, we're stuck. Any help will be appreciated. Thank you.

**Comment by ryanwilson** [comment]
I'll try to take a look today to see how invasive the change will be - hopefully it's easy to pipe through.

**Comment by ryanwilson** [comment]
This was fixed and will be out in the next release.

**Comment by doddyth** [comment]
Wow, thank you for the fast fixed! May I know when 5.14 release come out?

**Comment by ryanwilson** [comment]
You're very welcome 😄 by policy, we don't commit to dates for upcoming releases, but I will say that we are hoping to get 5.14.0 out with this issue fixed next week.
