### ISSUE TITLE
GADRewardBasedVideoAd dismissed presenting controller when skipping ad

### ISSUE THREAD

**Issue by aplusm** [firebase/firebase-ios-sdk#2118]
* Xcode version: 9.4.1
  * Firebase SDK version: 5.13
  * Firebase Component:  AdMob
  * Component version: Firebase/AdMob (5.13.0) Google-Mobile-Ads-SDK (~> 7.35)
  * Mediation stack: AdMob, Unity Ads

#### Steps to reproduce:

I have a **UITabBarController** hosting multiple view controllers, and present rewarded ads from one of this VC.

I present ads using the basic:
```
GADRewardBasedVideoAd.sharedInstance().present(fromRootViewController: self)
```

and when asking for an early skip of the ad, the **presenting view controller AND UITabBarController are dismissed too.**

I implemented GADRewardBasedVideoAdDelegate, but did nothing UI-related in these methods (presentation of dismissal of view controllers).

**Comment by paulb777** [comment]
Tracked internally at b/120135407

**Comment by UIowaEABurns** [comment]
Hello,

Could you provide a Charles log from a session that is causing the issue? It would help debug to see the ad request and response, since this could be an issue specific to certain creatives. Thanks!

**Comment by aplusm** [comment]
Hello,

Yes, sure i can provide you a Charles log of this issue. 
However i would prefer not make it public. How can we proceed ?

**Comment by aplusm** [comment]
Hi,

How can we proceed to move forward on this bug ?

**Comment by UIowaEABurns** [comment]
Hello,

Sorry for the late response-- I missed this notification. Yes, a private zip is fine. Feel free to send an email to me.

Thanks!

**Comment by macah1** [comment]
Hi! I'm having the same issue.

- Using Firebase (5.15.0)
- Using FirebaseAnalytics (5.4.0)
- Using FirebaseAnalyticsInterop (1.1.0)
- Using FirebaseCore (5.1.10)
- Using FirebaseInstanceID (3.3.0)
- Using FirebaseMessaging (3.2.2)

- Xcode Version 10.1 (10B61)

Mediation stack: AdMob, using rewarded ads

Thanks!

**Comment by UIowaEABurns** [comment]
Hello,

We've pushed our creative JS fix, which is expected to resolve the issue without any further action. Please let us know if the issue is ongoing. Thanks!
