### ISSUE TITLE
No such module 'FirebaseMLVision'

### ISSUE THREAD

**Issue by sivaerusappan** [firebase/firebase-ios-sdk#2129]
I got No such module 'FirebaseMLVision' error, how do fix it, I downloaded quickstart-ios samples, I have used mlvison sample for my analysis. kindly let me know how to fix it

**Comment by ryanwilson** [comment]
@sivaerusappan thanks for the report - can you share the Podfile? Are you trying to use `@import FirebaseMLVision` or `@import Firebase`?

**Comment by sivaerusappan** [comment]
> @sivaerusappan thanks for the report - can you share the Podfile? Are you trying to use `@import FirebaseMLVision` or `@import Firebase`?

@ryanwilson Yes i tried to use @import FirebaseMLVision, this is the import library mentioned in code. 
Here is My Pod entry, Its referred in firebase [ML Kit](https://firebase.google.com/docs/ml-kit/ios/recognize-text):

platform :ios, "11.0"
use_frameworks!
target 'MLVisionExample' do
pod 'Firebase/Core'

pod 'Firebase/MLVisionTextModel'
end

Please help me to fix the issue. Thanks for your reply

**Comment by ryanwilson** [comment]
Based on the instructions, you also need to include `pod 'Firebase/MLVision'` in your Podfile as that contains the library necessary - the `Firebase/MLVisionTextModel` only contains the model used by `Firebase/MLVision`. 

I noticed the instructions weren't very clear in this regard, and it may be reasonable to have `MLVision` as a dependency for `MLVisionTextModel`. I'll chat with the MLKit folks and figure out a good solution here, but hopefully that helps!

**Comment by sivaerusappan** [comment]
Thanks for your quick response, issue fixed!!! pod repo update fixed the issue, i got all dependencies after repo update.
