### ISSUE TITLE
Firebase/Performance pod causing UI API called on a background thread

### ISSUE THREAD

**Issue by ljaderman** [firebase/firebase-ios-sdk#213]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: __Version 9.0 beta 6 (9M214v)___
  * Firebase SDK version: _Firebase 4.0.4, ____
  * Library version: _FirebasePerformance (1.0.3)____
  * Firebase Product: _____ Performance Monitoring

### [REQUIRED] Step 3: Describe the problem
Including Firebase/Performance causes Main Thread Checker to flag a "UI API called on a background thread" error.

#### Steps to reproduce:
Install performance monitoring:  pod 'Firebase/Performance'
Running the app causes the following backtrace (below).  Remove the Performance pod, rebuild and run and main thread checker issue does not occur.

Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 600, TID: 236079, Thread name: (none), Queue name: com.google.firebase.auth.serialTaskQueue, QoS: 0
Backtrace:
4   App                                 0x00000001015c6ac4 -[FPRTraceBackgroundActivityTracker init] + 116
5   App                                 0x00000001015ccf2c -[FPRNetworkTrace start] + 96
6   App                                 0x00000001015d10cc __InstrumentDataTaskWithRequest_block_invoke + 120
7   App                                 0x000000010128c5e4 -[GTMSessionFetcher beginFetchMayDelay:mayAuthorize:] + 8948
8   App                                 0x0000000101289474 -[GTMSessionFetcher beginFetchWithCompletionHandler:] + 388
9   App                                 0x00000001014df400 -[FIRAuthBackendRPCIssuerImplementation asyncPostToURL:body:contentType:completionHandler:] + 496
10  App                                 0x00000001014e0d28 -[FIRAuthBackendRPCImplementation postWithRequest:response:callback:] + 384
11  App                                 0x00000001014dff30 -[FIRAuthBackendRPCImplementation secureToken:callback:] + 204
12  App                                 0x00000001014decf8 +[FIRAuthBackend secureToken:callback:] + 100
13  App                                 0x00000001014d6a18 -[FIRSecureTokenService requestAccessToken:] + 264
14  App                                 0x00000001014d64e4 __65-[FIRSecureTokenService fetchAccessTokenForcingRefresh:callback:]_block_invoke + 204
15  App                                 0x00000001014d5ff0 __38-[FIRAuthSerialTaskQueue enqueueTask:]_block_invoke + 116
16  libdispatch.dylib                   0x0000000102de149c _dispatch_call_block_and_release + 24
17  libdispatch.dylib                   0x0000000102de145c _dispatch_client_callout + 16
18  libdispatch.dylib                   0x0000000102df0110 _dispatch_queue_serial_drain + 692
19  libdispatch.dylib                   0x0000000102de49a4 _dispatch_queue_invoke + 332
20  libdispatch.dylib                   0x0000000102deff30 _dispatch_queue_serial_drain + 212
21  libdispatch.dylib                   0x0000000102de49a4 _dispatch_queue_invoke + 332
22  libdispatch.dylib                   0x0000000102df1104 _dispatch_root_queue_drain_deferred_wlh + 424
23  libdispatch.dylib                   0x0000000102df8100 _dispatch_workloop_worker_thread + 652
24  libsystem_pthread.dylib             0x000000018663efe0 _pthread_wqthread + 932
25  libsystem_pthread.dylib             0x000000018663ec30 start_wqthread + 4
2017-08-23 14:02:48.833133-0700 App[600:236079] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 600, TID: 236079, Thread name: (none), Queue name: com.google.firebase.auth.serialTaskQueue, QoS: 0
Backtrace:
4   App                                 0x00000001015c6ac4 -[FPRTraceBackgroundActivityTracker init] + 116
5   App                                 0x00000001015ccf2c -[FPRNetworkTrace start] + 96
6   App                                 0x00000001015d10cc __InstrumentDataTaskWithRequest_block_invoke + 120
7   App                                 0x000000010128c5e4 -[GTMSessionFetcher beginFetchMayDelay:mayAuthorize:] + 8948
8   App                                 0x0000000101289474 -[GTMSessionFetcher beginFetchWithCompletionHandler:] + 388
9   App                                 0x00000001014df400 -[FIRAuthBackendRPCIssuerImplementation asyncPostToURL:body:contentType:completionHandler:] + 496
10  App                                 0x00000001014e0d28 -[FIRAuthBackendRPCImplementation postWithRequest:response:callback:] + 384
11  App                                 0x00000001014dff30 -[FIRAuthBackendRPCImplementation secureToken:callback:] + 204
12  App                                 0x00000001014decf8 +[FIRAuthBackend secureToken:callback:] + 100
13  App                                 0x00000001014d6a18 -[FIRSecureTokenService requestAccessToken:] + 264
14  App                                 0x00000001014d64e4 __65-[FIRSecureTokenService fetchAccessTokenForcingRefresh:callback:]_block_invoke + 204
15  App                                 0x00000001014d5ff0 __38-[FIRAuthSerialTaskQueue enqueueTask:]_block_invoke + 116
16  libdispatch.dylib                   0x0000000102de149c _dispatch_call_block_and_release + 24
17  libdispatch.dylib                   0x0000000102de145c _dispatch_client_callout + 16
18  libdispatch.dylib                   0x0000000102df0110 _dispatch_queue_serial_drain + 692
19  libdispatch.dylib                   0x0000000102de49a4 _dispatch_queue_invoke + 332
20  libdispatch.dylib                   0x0000000102deff30 _dispatch_queue_serial_drain + 212
21  libdispatch.dylib                   0x0000000102de49a4 _dispatch_queue_invoke + 332
22  libdispatch.dylib                   0x0000000102df1104 _dispatch_root_queue_drain_deferred_wlh + 424
23  libdispatch.dylib                   0x0000000102df8100 _dispatch_workloop_worker_thread + 652
24  libsystem_pthread.dylib             0x000000018663efe0 _pthread_wqthread + 932
25  libsystem_pthread.dylib             0x000000018663ec30 start_wqthread + 4

**Comment by paulb777** [comment]
Thanks for the report. 

This issue is not part of the open source repo and being tracked internally as b/64213975. 

The fix is targeted for an upcoming FirebasePerformance release.

We'll update here when the release goes out.

**Comment by ljaderman** [comment]
Thanks, Paul. We're hoping this and the other critical bugs will be resolved prior to the general release of iOS11, as we (and I'm sure many others) are hoping to use firebase for several production apps targeted for the iOS11 general release.

**Comment by paulb777** [comment]
The fix was released with Firebase 4.1.1 and FirebasePerformance 1.0.4.

**Comment by longhoang2984** [comment]
It still happen on v2.0.1
