### ISSUE TITLE
Firestore: Completion blocks don't return if networking has been disabled

### ISSUE THREAD

**Issue by AlbertRenshaw** [firebase/firebase-ios-sdk#2134]
#### Environment:

  * Xcode version: 10.1
  * Firebase SDK version: 5.13.0
  * Firebase Component: Firestore
  * Component version: 5.13.0

#### Problem:

If networking is disabled on an instance of firestore, network calls will fail but their method's completion blocks do not return an error (in-fact they don't return _anything_ at all, which lead to an infinite loading screen in our app)

We had a member of our team disable networking for our sharedFirestore instance somewhere else in the app for performance reasons, a different member of our team was randomly having firestore network calls load forever (because no completion block or error block was being called) and had no ability to diagnose why (because of the lack of an error callback in the firestore request). This was baffling until we eventually got everyone talking together and found out what had happened. All that said, I think it might be helpful to others in future scenarios if completionBlocks were always called back, in the event of a network call stopping due to networking being disabled an error should be returned saying "Networking has been manually disabled with disableNetworkWithCompletion:"

#### Steps to reproduce:

1) Disable networking (see code below) on your shared firestore instance. 
2) Try to setData on a collection/document, even though it fails (presumably?), completion block will never be called, so you do not know it's failed. 

#### Relevant Code:

`[_sharedFirestore disableNetworkWithCompletion:nil];`

`[[[_sharedFirestore collectionWithPath:collectionPath] documentWithPath:document] setData:dictionary completion:^(NSError * _Nullable error) { /*This is never called, no error is returned*/ }];`

**Comment by ryanwilson** [comment]
Thanks for the report, I'm digging in to see if I can find out why this is happening.

**Comment by ryanwilson** [comment]
One thing in case you haven't tried yet - have you created a completion handler for the `disableNetworkWithCompletion:` and called the `setData:` within that? Off the top of my head, I'm wondering if there's a race condition where something gets queued and killed along the way.

The completion handler should still get called, but thought I'd check if there's a workaround in the meantime while we track the issue down.

**Comment by wilhuff** [comment]
Hi, this behavior is intended. Our [docs](https://firebase.google.com/docs/reference/ios/firebasefirestore/api/reference/Classes/FIRDocumentReference#-setdatacompletion) describe the completion handler like this:

> A block to execute once the document has been successfully written to the server. This block will not be called while the client is offline, though local changes will be visible immediately.

Firestore locally queues writes and already guarantees that your operations are serialized even without waiting on the completion handler. That is, in the absence of any other things modifying your data, the following works:

```objc
FIRDocument *document = ...;
[document setData:dictionary];
[document getDocumentWithCompletion:^(FIRDocumentSnapshot *snapshot, NSError *error) {
  XCTAssertEqual(dictionary, snapshot.data);
}];
```

We definitely realize that this is a nonstandard arrangement, but we're also trying to accommodate online-mostly applications that want a definite signal that a write has been accepted by the server.

This means that for offline-tolerant applications the completion handler should not be used to chain the next operation.

**Comment by AlbertRenshaw** [comment]
I understand and that's a reasonable stance. Even still, with no clues it was very hard for us to debug until finally our coders from different buildings got on the phone and were able to talk and uncover what had happened. Might I suggest that in the event a server call is made while networking has been disabled it at least NSLogs a hint like 'p.s. you have manually disabled networking, this call will not complete until it is re-enabled'?

**Comment by elprl** [comment]
I spent hours trying to figure this one out also. I'm using the RxFirebase library with Swift and this issue renders that library pretty useless for me. What's the suggested architectural approach here, that we do Reachability tests beforehand, then run setData() with a fire & forget approach if offline?

**Comment by wilhuff** [comment]
Our suggested approach is that unless you specifically care about waiting for the commit at the server, you just always fire and forget calls to setData. You don't need to test for reachability first.
