### ISSUE TITLE
FirebaseCrash to support macOS - moving from Fabric

### ISSUE THREAD

**Issue by guidedways** [firebase/firebase-ios-sdk#2149]
I realize macOS support isn't there, but given the community has provided support for macOS (somewhat), is there a way to make FirebaseCrash work with macOS? I'm porting my code over from Fabric to Firebase given Fabric is on its last leg and the Google wants us to move us all to Firebase. I'm surprised the support for macOS isn't there as it was in Fabric.

What are we supposed to do when Fabric dies in 2019?

**Comment by ryanwilson** [comment]
Hi @guidedways - FirebaseCrash was deprecated in favor of Crashlytics. You can find the documentation [here](https://firebase.google.com/docs/crashlytics/).

We're working on tightening the integration on the SDK side, and in the meantime you can depend on the `FirebaseCore` pod directly (instead of `Firebase/Core`) for macOS projects.

Let me know if that's what you're looking for, or you have more questions.

**Comment by guidedways** [comment]
Thanks Ryan

In that case, the instructions are confusing. There's conflicting implied information in the docs. I realise it mentions we need to be using Crashlytics, however the "Crash Free Users" section in Firebase instructs us to use Firebase.

I also dislike using Pods (it won't work in our setup) and the manual process of including Frameworks hasn't quite worked. There's in fact no `@import Firebase` (which the docs point to everywhere) but instead `@import FirebaseCore` worked for me. I couldn't get the manually imported framework to work with macOS either as a sub-framework is looking for `UIApplication` and the compiler stops at that point, with an unresolved reference to this symbol.

**Comment by guidedways** [comment]
On top of this, we were already using `GTMAuth` in one of our frameworks which then uses `GTMFetcherSession`. If I now try and include `FirebasePerformance` into our iOS variant, the app won't compile given there are now dozens of duplicate symbols. It's not going to be easy removing `GTMFetcherSession` from being included in our build given `GTMAuth` depends on it. I'm sort of stuck in a cyclic reference loop (apart from issues with macOS not compiling `FirebaseCore`).

I wish Google would improve upon Fabric instead of this unsolicited exodus towards Firebase. I don't want to be using any other Firebase functionality.

**Comment by guidedways** [comment]
Furthermore, I tried setting this up for another macOS project just now (using cocoa pods) and I get this:

`[!] The platform of the target `BusyCal MAS` (macOS 10.11) is not compatible with `Firebase/Core (5.14.0)`, which does not support `osx`.`

**Comment by ryanwilson** [comment]
This is great feedback, thanks for all the info.

For the "Crash Free Users" section, are you referring to [this page](https://support.google.com/firebase/answer/7245318?hl=en#), or a different doc? I see a deprecation notice at the top, but we could have other documentation that hasn't been updated. Any help tracking down old or outdated docs would be greatly appreciated!

Re: no `@import Firebase` available - pulling from the zip file integration instructions, you should be able to drag the `module.modulemap` file into your project and update your User Header Search Paths to contain the directory that contains your module map. If that doesn't work, let us know and we can see what's broken about it.

> I couldn't get the manually imported framework to work with macOS either as a sub-framework is looking for UIApplication and the compiler stops at that point, with an unresolved reference to this symbol.

I'd be interested to know which sub-framework was looking for `UIApplication` - do you know off hand what framework it was, or are you able to find out? We should be wrapping our own code to ensure it's not trying to use `UIApplication` when it's not. There was a bug not too long ago where one usage accidentally slipped through - I wonder if it was at the same time or it's a different issue. One related note: Analytics does not currently support macOS, so only include the `FirebaseCore.framework` framework from the Analytics directory.

Re: `GTMSessionFetcher` and `FirebasePerformance`- unfortunately that's one of the downsides of manually integrating frameworks 😞one way to find a common version that works:

1. Create a blank project that uses CocoaPods,
2. Install the `GTMAppAuth` and `FirebasePerformance` pods (optionally locking the `GTMAppAuth` to the current version you're using),
3. Look at the `Podfile.lock` and see what version `GTMSessionFetcher`, `FirebasePerformance`, and `GTMAppAuth` resolves to,
4. Get those versions and include them in your app.

Note: You'll also need to make sure the `FirebaseCore` version is from the same umbrella `Firebase` version.

Re: your last setup, the `Firebase` pod itself doesn't support macOS, but you can use `pod FirebaseCore` to include Core and that should work.

**Comment by guidedways** [comment]
Thanks a lot Ryan! I've now undone all of my changes (since I spent an hour trying to get it to work), so I don't remember what framework it was that complained about `UIApplication`, however since I was only trying to manually import `Firebase/Crash` and `Firebase/Analytics`, it should be easy to reproduce at your end. I suppose it might have been `Firebase/Analytics` in case that isn't yet supported.

Regarding "Crash Free Users", no I'm referring to this image below. I see this in my dashboard and there's no metrics available for this. If this isn't supported, and if Firebase still uses Crashlytics behind the scenes, why do we have to 'link' our Fabric apps to Firebase and let go of Fabric? Is it because Fabric as a whole will simply cease to exist by mid-2019? I also don't see a number of other metrics anymore, such as Analytics in our iOS app after linking with Firebase.

![screenshot 2018-12-05 at 17 55 26](https://user-images.githubusercontent.com/202437/49518172-70349d00-f8b7-11e8-90bb-1409952d44ab.png)

**Comment by morganchen12** [comment]
Can you share your Podfile?

**Comment by guidedways** [comment]
Sure

```
project '../OurProject.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :osx, '10.11'

def myPods
  pod 'FirebaseCore'
  #not available for macOS
  #pod 'Firebase/Performance'
end

use_frameworks!

target 'OurApp Release' do
  myPods
end
```

**Comment by guidedways** [comment]
But as I mentioned, the duplicate class message isn't because there's a duplicate within your frameworks - we have a complex web of internal frameworks we use, and one of our internal frameworks already uses `GTMAppAuth` (as source) which already contains `GTMSessionFetcher`. There's no easy way around this as we cannot remove the dependency we have already (we've got a few modifications on top of the `GTMAppAuth` library as it's broken (by Google) a few times this year and our modifications make sure a broken implementation does not break our app (again).

**Comment by morganchen12** [comment]
Since your internal framework isn't managing its dependencies through CocoaPods, you won't be able to resolve this issue via CocoaPods. The easiest way to avoid the duplicate class dependencies is to just rename all the Google classes in your internal framework so they won't conflict with Firebase's version. Unfortunately any cleaner solution will be difficult since you're essentially mixing dependency management systems (manual and CocoaPods).

**Comment by jhoughjr** [comment]
I'm not holding my breath. About to talk to my client about switching from Firebase as I've wasted hours chasing the incorrect documentation only to still fail to get the most basic functionality to work.
I expected better support from google for a paid service.

**Comment by joseines** [comment]
Any news on Firebase Crashlytics support for MacOS?

**Comment by garsdle** [comment]
I think with SwifUI there will be an influx of native macOS apps. For now I'm sticking to the old Crashlytics but when it sunsets (March of 2020) if Firebase doesn't support macOS I'll have to find an alternative.

**Comment by samedson** [comment]
Hey sorry we didn't update this. You can use Crashlytics on macOS and tvOS in the Firebase Console now. You need to set up the app as an iOS app in the console, but if you install: 
```
pod 'Crashlytics'
pod 'FirebaseCore'
```

You can follow the instructions at https://firebase.google.com/docs/crashlytics/get-started?platform=ios to install it fully

**Comment by leandrodemarco** [comment]
I'm having this exact same issue:
> I now have our mac app connected and configured with FirebaseCore however the online Console still thinks we haven't connected the app to the SDK
