### ISSUE TITLE
Firebase - GoogleAppMeasurement dependency crash 

### ISSUE THREAD

**Issue by code-surf** [firebase/firebase-ios-sdk#2151]
* Xcode version: 10.1
  * Firebase SDK version: 5.11.0
  * Firebase Component: Core
  * Component version: 5.11.0

It looks like you have updated the cocoapod for GoogleAppMeasurement to version 5.4.0. This makes app using Firebase 5.11.0 crash with console log: 

*** Terminating app due to uncaught exception 'FIRAnalyticsVersionMismatch', reason: 'Google Analytics for Firebase version (50300000) does not match with Google App Measurement (50400000) version. Please update.'

Investigating Podfile.lock file:

  - Firebase/Core (5.11.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 5.3.0)

  - FirebaseAnalytics (5.3.0):
    - FirebaseCore (~> 5.1)
    - FirebaseInstanceID (~> 3.3)
    - GoogleAppMeasurement (~> 5.3)
    - GoogleUtilities/AppDelegateSwizzler (~> 5.2)
    - GoogleUtilities/MethodSwizzler (~> 5.2)
    - GoogleUtilities/Network (~> 5.2)
    - "GoogleUtilities/NSData+zlib (~> 5.2)"
    - nanopb (~> 0.3)

  - GoogleAppMeasurement (5.4.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 5.2)
    - GoogleUtilities/MethodSwizzler (~> 5.2)
    - GoogleUtilities/Network (~> 5.2)
    - "GoogleUtilities/NSData+zlib (~> 5.2)"
    - nanopb (~> 0.3)

As you can see - your FirebaseAnalytics podspec is dependent on GoogleAppMeasurement (~> 5.3), which currently resolves to 5.4

**Comment by paulb777** [comment]
Hi @code-surf Thanks for the report

We fixed the issue of making the CocoaPods dependency of FirebaseAnalytics lock to the GoogleAppMeasurement version in Firebase 5.14.0 along with versions 5.4.0 of FirebaseAnalytics and GoogleAppMeasurement. 

The recommended solution is to run `pod update` to update the latest version of all Firebase pods.

If you want to stick to Firebase 5.11.0, you should lock the version of GoogleAppMeasurement to 5.3.0 in the Podfile with  `pod 'GoogleAppMeasurement', '5.3.0'

**Comment by code-surf** [comment]
Hi @paulb777 ,

thank you for the update. I didn't see the release notes of 5.14.0 here: https://firebase.google.com/support/release-notes/ios
 so I didn't notice the fix. Thank you for the update

**Comment by paulb777** [comment]
Looks like there's a delay in publishing the release notes. We'll follow up on that.  Thanks for letting us know.
