### ISSUE TITLE
FIRDatabase reference always returns nil for Apple TV works fine for iOS

### ISSUE THREAD

**Issue by dipen-apptrait** [firebase/firebase-ios-sdk#2157]
When we try to initialise FIRDatabase reference for Apple TV it always returns nil and it works totally fine for iOS version. 
We use below syntax. We do configure firebase in appdelegate file and also confirmed the config file.
`self.ref = [[FIRDatabase database] reference];`

Also please note that we use the example code provided with this repository.

**Comment by ryanwilson** [comment]
Hi @dipen-apptrait,

1. Can you please check if `[FIRDatabase database]` is nil or not in this situation?
2. Are any errors or warnings logged in the console?

Thanks!

**Comment by dipen-apptrait** [comment]
There is no error on console. And yes 

> [FIRDatabase database]

 is 

> nil 
![screen shot 2018-12-07 at 10 36 40 am](https://user-images.githubusercontent.com/17145241/49628853-9ddf2a80-fa0c-11e8-95c6-352517af3ebd.png)
![screen shot 2018-12-07 at 10 37 28 am](https://user-images.githubusercontent.com/17145241/49628854-9ddf2a80-fa0c-11e8-9312-01a685b85da9.png)

**Comment by ryanwilson** [comment]
Hmm, that's definitely a bug. Thanks for finding this! We recently changed around how we handle the singleton, I'll poke around and see what I can find.
