### ISSUE TITLE
FirebaseCoreDiagnostics was built for archive which is not the architecture being linked (arm64)

### ISSUE THREAD

**Issue by scalessec** [firebase/firebase-ios-sdk#2161]
* Xcode version: 10.1 (10B61)
  * Firebase SDK version: 5.14.0
  * Firebase Component: Core

Currently seeing this log when building for a device:

`ld: warning: ignoring file /web/mobile-iossdk/Carthage/Build/iOS/FirebaseCoreDiagnostics.framework/FirebaseCoreDiagnostics, file was built for archive which is not the architecture being linked (arm64): /web/mobile-iossdk/Carthage/Build/iOS/FirebaseCoreDiagnostics.framework/FirebaseCoreDiagnostics`

We're currently integrating with Carthage and, at the moment, this is the only Firebase dependency in the `Cartfile`:
`binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" == 5.14.0`

FWIW, we were also seeing this with `5.13.0`. Everything appears fine when we remove `FirebaseCoreDiagnostics.framework` from being linked, but I'm unsure of the implications of that.

**Comment by morganchen12** [comment]
The wrong architecture is not going to be linked in anyway, so removing that framework for now has no negative effects beyond what the missing architecture is already doing.

**Comment by paulb777** [comment]
Thanks for the report @scalessec.  I've reproduced and will investigate.

**Comment by paulb777** [comment]
There was a regression in the Carthage build process that has been addressed and will be available with the 5.15.0 release. Thanks for the report.
