### ISSUE TITLE
"Checking if app has communicated.." on macOS

### ISSUE THREAD

**Issue by guidedways** [firebase/firebase-ios-sdk#2163]
I've gone through the process of including `FirebaseCore` into a macOS app. I realize this is community supported, however I am also under the impression that since `FirebaseCore` is supported, the Firebase console should be able to recognise our app communicating with the servers?

I am only seeing this on the `Add Firebase to your iOS apps` (except, I'm adding it to a macOS app)

`Checking if the app has communicated with our servers. You may need to uninstall and reinstall your app.`

Is this supposed to work? 

`[FIRApp configure]` seems to be working, all I see in the console is this message at launch:

```
[Firebase/Core][I-COR000028] tvOS and macOS SDK support is not part of the official Firebase product. Instead they are community supported. Details at https://github.com/firebase/firebase-ios-sdk/blob/master/README.md.
```

**Comment by paulb777** [comment]
It's supposed to work. Is there something not working beyond the confusing log message?

**Comment by guidedways** [comment]
Well, the linking page keeps spinning suggesting the app never communicated. I can see crashes appear but those should come through crashlytics anyway. I guess I’m not even sure why we have to link our apps to Firebase from Fabric. What benefit am I getting out of this linkage when a) it won’t link, b) if it did, I don’t know what to look out for.

**Comment by paulb777** [comment]
Closing for now - will reopen with more info.
