### ISSUE TITLE
Using Firebase/Performance via CocoaPods, A runtime error occurred in the project with application target and app extension target.

### ISSUE THREAD

**Issue by roothybrid7** [firebase/firebase-ios-sdk#2165]
### [READ] Step 1: Are you in the right place?

   Yes.

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.1 (10B61)
  * Firebase SDK version: 5.13.0
  * Firebase Component: Performance
  * Component version: 2.2.1

### [REQUIRED] Step 3: Describe the problem

When run the app, then the following things happened.

```
dyld: Symbol not found: _OBJC_CLASS_$_GULObjectSwizzler
  Referenced from: /Users/foo/Library/Developer/CoreSimulator/Devices/5DCBF093-41D4-41EF-BF97-3D3216FF41EE/data/Containers/Bundle/Application/EB0CBD52-29C5-4C4B-BDFD-3F2117F64D45/App.app/App
  Expected in: /Users/foo/Library/Developer/CoreSimulator/Devices/5DCBF093-41D4-41EF-BF97-3D3216FF41EE/data/Containers/Bundle/Application/EB0CBD52-29C5-4C4B-BDFD-3F2117F64D45/App.app/Frameworks/GoogleUtilities.framework/GoogleUtilities
 in /Users/foo/Library/Developer/CoreSimulator/Devices/5DCBF093-41D4-41EF-BF97-3D3216FF41EE/data/Containers/Bundle/Application/EB0CBD52-29C5-4C4B-BDFD-3F2117F64D45/App.app/App
```

#### Steps to reproduce:

If you use firebase SDK in the project with application target and app extension target.

#### Relevant Code:

This is Podfile:

```Podfile
# Podfile
platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

target 'App' do
    pod 'Fabric'
    pod 'Crashlytics'
# [...]
    pod 'Firebase'
    pod 'Firebase/Auth'
    pod 'Firebase/Messaging'
    pod 'Firebase/DynamicLinks'
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Database'
    pod 'FirebaseABTesting'
    pod 'FirebasePerformance'
end

target 'AppNotificationService' do
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Firebase'
end
```
I have found quick-fix solution currently, it is to use `-weak_framework` for  GoogleUtilities. 

```

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            # Rewrite xcconfigs
            case target.name
            when /App$/, /AppTests$/
                xcconfig_path = config.base_configuration_reference.real_path
                build_settings = Hash[*File.read(xcconfig_path).lines.map {|l| l.split(/\s*=\s*/, 2) }.flatten]
                build_settings['OTHER_LDFLAGS'].sub!('-framework "GoogleUtilities"', '-weak_framework "GoogleUtilities"')
                File.open(xcconfig_path, "w") {|f| f.puts build_settings.map {|k, v| "#{k} = #{v}" } }
            end
        end
    end
end
```

**Comment by paulb777** [comment]
Remove `pod 'Firebase'` from the app extension target.

This is likely an instance of the CocoaPods issue - https://github.com/CocoaPods/CocoaPods/issues/8206. Workarounds include using the old build system or making sure that requested subspecs match between extension and main targets.

However, to take a step back, I don't know of a reason to include `pod 'Firebase'` in an app extension target, so I recommend removing it and avoiding the CocoaPods bug completely.

**Comment by roothybrid7** [comment]
If I remove `pod 'Firebase'`, I think that I can't use **Analytics**  in the app extension target.

**Comment by paulb777** [comment]
True, but Analytics is not very well supported in app extensions because of appID ambiguity and short extension lifetimes.  Have you found it to meet your needs?

**Comment by roothybrid7** [comment]
Yes,  I hope I can roughly measure total amounts of receiving notifications by Analytics.
So there is no problem for now.
And then I split `GoogleService-Info.plist` for each the application target and the app extension target.

**Comment by paulb777** [comment]
OK. Then for this issue, CocoaPods 1.6.0 is the solution.  However, for #2166, you would either need to use the old build system or update the Podfile to match the GoogleUtilities subspecs between the app and the extension.

**Comment by roothybrid7** [comment]
OK. thanks.
