### ISSUE TITLE
On new build system, build failed for archive because of Multiple commands produce 

### ISSUE THREAD

**Issue by roothybrid7** [firebase/firebase-ios-sdk#2166]
### [READ] Step 1: Are you in the right place?

  Yes.

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.1 (10B61)
  * Firebase SDK version: 5.13.0
  * Firebase Component: Performance
  * Component version: 2.2.1

**same as #2165**

### [REQUIRED] Step 3: Describe the problem
 
following log when building for archive:
```
error: Multiple commands produce '/Users/foo/.ghq/github.com/org/ios/DerivedData/App/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleUtilities.framework':
1) Target 'GoogleUtilities-ac14cd06' has create directory command with output '/Users/foo/.ghq/github.com/org/ios/DerivedData/App/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleUtilities.framework'
2) Target 'GoogleUtilities-00567490' has create directory command with output '/Users/foo/.ghq/github.com/org/ios/DerivedData/App/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleUtilities.framework'
```

#### Steps to reproduce:

To run archive on new build system with the environment of #2165.

**Comment by aceisScope** [comment]
In our case, this issue can be solved by removing Firebase from the pod subspec of the unit test target. But then it complains "fail to find Firebase module", the solution of which is described in issue #16.

**Comment by morganchen12** [comment]
Closing this since it's not actionable here.
