### ISSUE TITLE
Authentication doesn't work within share extension, even with Keychain sharing enabled

### ISSUE THREAD

**Issue by AlecZadikian9001** [firebase/firebase-ios-sdk#2179]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.4.1 
  * Firebase SDK version: 5.14.0
  * Firebase Component: Auth
  * Component version: ? Latest

### [REQUIRED] Step 3: Describe the problem

You aren't logged into Firebase within a share extension, making it difficult to send authenticated requests to your own server. There are unofficial workarounds around the Internet, but they either involve hacks or complicated custom token minting. For example, users Googling this issue will go here first: https://gist.github.com/hhyyg/c1481853bcac27a678f707c0d1afd0f4

1. Create an iPhone app with Firebase Auth, with users authenticating by email, phone, etc. Successfully log in with it.
2. Add a share extension to the app.
3. Enable keychain sharing for both the app target and the share extension target.
4. Create a copy of GoogleService-Info.plist that belongs to the share extension target, changing the bundle ID in it.
5. Run the main app, and log in.
6. Run the share extension. It'll fail to log in.

Showing that the share extension fails to log in:

```
FirebaseApp.configure()
let user = Auth.auth().currentUser
print("user = \(user)")
```
will print "user = nil". There aren't any errors about Firebase in the log (which there were before when I had the wrong bundle ID in my plist).

I'm guessing this is more of a feature request than a bug since the docs don't seem to mention using auth within share extensions, and a recent patch fixed an issue where FIRAuth wouldn't even build within an extension.

**Comment by AlecZadikian9001** [comment]
Confirmed that the hacky method in the gist works. So all that's needed is a copy of the keychain data from the main app, and keychain sharing has to be enabled.

**Comment by renkelvin** [comment]
Extension support with Keychain Sharing is introduced in v6.0.
https://firebase.google.com/docs/auth/ios/single-sign-on

**Comment by jamieomatthews** [comment]
@renkelvin I'm not able to authenticate in an app extension.  It would be good if the docs could explain how that is supposed to work.  When I call `Auth.auth().useUserAccessGroup(...)` in the app extension, it throws an error.  Similarly, Auth.auth().currentUser returns nil.

**Comment by tolmekian1453** [comment]
Wonderful. I wonder if it works in the JavaScript version if you're using React Native.

**Comment by renkelvin** [comment]
@jamesdaniels Please create a separate issue with detailed steps to reproduce.

**Comment by tolmekian1453** [comment]
Confirmed this doesn't work in React Native. Here's my ugly workaround: https://gist.github.com/tolmekian1453/6785e85f4dd88f950fcfc20d95d44dd3
