### ISSUE TITLE
SDK Download stuck at 5.14

### ISSUE THREAD

**Issue by BranchS** [firebase/firebase-ios-sdk#2205]
Please update the manual iOS SDK download to Firebase 5.15. Thanks! cc @paulb777

**Comment by ryanwilson** [comment]
Sorry about that! We'll fix that ASAP. In the meantime, the zip is also uploaded in GitHub Releases - you can find it at https://github.com/firebase/firebase-ios-sdk/releases/tag/5.15.0

**Comment by paulb777** [comment]
Thanks for the report @BranchS. 

We've fixed the link at https://firebase.google.com/docs/ios/setup#frameworks
