### ISSUE TITLE
style.sh does not handle file names with spaces

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#2223]
The shell script currently splits a list of generated files by spaces so that file's that include spaces in their names do not get processed.

**Comment by paulb777** [comment]
Closing since this is a low priority, since we'll likely avoid source files with spaces in their paths

**Comment by paulb777** [comment]
Reopening since Auth added several files with spaces and style.sh is generating `No such file or directory` for each file.  cc: @renkelvin

**Comment by renkelvin** [comment]
Removed spaces from auth file paths https://github.com/firebase/firebase-ios-sdk/pull/2798
