### ISSUE TITLE
Unable to Use Crashlytics - FAB Network Error

### ISSUE THREAD

**Issue by gundadittu** [firebase/firebase-ios-sdk#2230]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.1
  * Firebase SDK version: 5.15.0
  * Firebase Component: Crashlytics 
  * Component version: Whatever latest version is as of Jan 3, 2019 

### [REQUIRED] Step 3: Describe the problem
Keep getting the below error when trying to follow the Crashlytics set up. App was not linked to Fabric before. Made sure the bundle IDs match. Still get error. 

[Fabric] failed to download settings Error Domain=FABNetworkError Code=-5 "(null)" UserInfo={status_code=403, type=2, request_id=56de4910359598073e41c0632e2f96bb, content_type=application/json; charset=utf-8}

#### Steps to reproduce:

What happened? How can we make the problem occur?

Just run the app after following the get started steps for crashlytics (https://firebase.google.com/docs/crashlytics/get-started?authuser=0#ios)

#### Relevant Code:
N/A

**Comment by morganchen12** [comment]
@gundadittu can you file this at [Firebase Support](https://firebase.google.com/support/contact/?category=troubleshooting)? This way they'll be able to take a look at what's going on in your Fabric/Firebase project.
