### ISSUE TITLE
[Messaging] message delegate not calling didReceiveRegistrationToken from 5.10.0 -> 5.11.0

### ISSUE THREAD

**Issue by M2Bas** [firebase/firebase-ios-sdk#2240]
### Describe your environment

  * Xcode version: 10.1 (10B61)
  * Firebase SDK version: 5.11.0 and higher
  * Firebase Component: Messaging 
  * Component version: 3.2.1 and higher

### Describe the problem

After updating firebase to version 5.11.0 or higher the messaging delegate function `didReceiveRegistrationToken` is not called.
This issue is rather similar to https://github.com/firebase/firebase-ios-sdk/issues/1339

#### Context 
In my project I have extracted my push notification handling outside of the AppDelegate and also the delegate handling for messaging to get the FCM token and handle any possible changes.

#### Current scenario
Below scenario works in version <= 5.10.0, but stopped working in >5.11.0

In the AppDelegate, I have a property that handles the notifications. Which I provide the information from received notifications in the AppDelegate.
```
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    private let pushNotificationHandler: PushNotificationHandler = PushNotificationHandler()

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        FirebaseApp.configure()
        return true
    }

    func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any]) {
        pushNotificationHandler.handleMessage(userInfo: userInfo)
    }
}
```
Simplified code of the PushNotificationHandler:
```
class PushNotificationHandler: NSObject, MessagingDelegate {

    override init() {
        super.init()
        Messaging.messaging().delegate = self
    }

    func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String) {
        debugPrint("📌 - Did receive FCM token: \(fcmToken)")
    }

    func handleMessage(userInfo: [AnyHashable: Any]) {
        debugPrint("Handle the notification: \(userInfo)")
    }
}
```
#### Steps to reproduce:

Current scenario:
```
    private let pushNotificationHandler: PushNotificationHandler = PushNotificationHandler()

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        FirebaseApp.configure()
        return true
    }
```
With above code, the delegate would be set, but it will never call `didReceiveRegistrationToken`

Workaround:
```
    private var pushNotificationHandler: PushNotificationHandler?

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        FirebaseApp.configure()
        pushNotificationHandler = PushNotificationHandler()
        return true
    }
```
After changing it to the workaround, the delegate is called again in version >5.11.0

So something changed in the behavior of setting the:
```
        Messaging.messaging().delegate = self
``` 
Between 5.10.0 to 5.11.0, which causes a breaking change for my project and as it seems in different ways for other people.

**Comment by morganchen12** [comment]
@chliangGoogle can you take a look at what changed in the 5.11.0 release?

**Comment by chliangGoogle** [comment]
I've looked at the release changes and no changes has related to this. Looks like dev is modifying to have their own FIRMessagingDelegate, which I think the workaround is the ideal way of doing it as FIRMessaging delegate should be initialized after FIRApp.configure().

The previous solution should probably not work at the first place.

**Comment by M2Bas** [comment]
@chliangGoogle I think you are dismissing the issue a bit to quick here.

Yes I created my own way of handling the delegate, but I feel like there is an underlaying issue in the way the Messaging instance is created and how it is returned as the singleton in follow up calls.

In the implementation I can see calling `Messaging.messaging()` returns the static property `static FIRMessaging *sMessaging;` 

However if you would create a property on the AppDelegate just creating a reference to the shared instance of FIRMessaging it will be in an invalid state, any following calls now returns that same invalid state, where you will not be able to set the delegate correctly. Which is where my initial problem lays.

Even though it's not recommended to make a property of the shared messaging instance, it previously was possible and users might have used it that way. And other bug reports of users saying the delegate is not working either could be a result of this underlaying issue.

### Steps to reproduce:

Setting the delegate after the `FirebaseApp.configure()` with the Messaging shared instance being in an invalid state:
```
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?
    let messaging = Messaging.messaging()

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        FirebaseApp.configure()
        messaging.delegate = self //Using the stored property of messaging, delegate not called
       // Messaging.messaging().delegate = self //Using the shared instance, delegate not called
        return true
    }
```
Both ways of setting the delegate don't work, either by accessing the property or by getting it returned by `Messaging.messaging()`
### My request:

Please have another look into what changes where made from 5.10.0 to 5.11.0 that could cause the shared instance to be in an invalid state. This will not help my problem, but it could highlight and fix issues other people are facing.

My personal guess is that certain requirements have changed, causing the FIRMessage instance to not be able to be created correctly internally.

**Comment by paulb777** [comment]
@M2Bas Sorry about the confusion.

There were changes in 5.11.0 related to how `FirebaseApp.configure()` initialized Messaging.

Setting the delegate before ` FirebaseApp.configure()` was previously undefined behavior.  The delegate should be set after to be deterministic.

`Messaging.messaging().delegate = self` should happen after `FirebaseApp.configure()`

You can see the differences between 5.10.0 and 5.11.0 in the github repo with:

`git diff origin/release-5.10.0 origin/release-5.11.0 -- Firebase/Messaging/`

**Comment by morganchen12** [comment]
The pattern we've been using in other SDKs is to assert if initialization-dependent classes have been accessed before Firebase was initialized. I'm not sure if there's a good reason for why we haven't done that for Messaging, but previously accessing `Messaging.messaging()` before `FirebaseApp.configure()` only worked out of coincidence.

It's a pretty unpleasant technicality, but undefined behavior that worked or was useful breaking after a new release is not a breaking change, since that behavior was never supposed to work in the first place.

@chliangGoogle can we add an assert to the FIRMessaging singleton access?

**Comment by paulb777** [comment]
Is this still an issue?

**Comment by morganchen12** [comment]
This should be fixed now with the new FIRApp configure registration infrastructure.
