### ISSUE TITLE
[macos] Using the SDK on XCode 10

### ISSUE THREAD

**Issue by vladvarna** [firebase/firebase-ios-sdk#2248]
### [REQUIRED] Step 2: Describe your environment

Xcode version: 10.1 (10B61)
Firebase SDK version: 5.1.10
Firebase Component: Database
Component version: FirebaseDatabase (5.0.4)

#### Steps to reproduce:
I tried using the SDK with XCode 10 on Mojave.
The authorization work fine, but when trying to get an instance of the Database, I get a NULL.

#### Relevant Code:

```
let RTDBref = Database.database() // <- this is null
```

**Comment by vladvarna** [comment]
Hello,
           I tried using the SDK with XCode 10 on Mojave. 
Xcode version: 10.1 (10B61)
Firebase SDK version: 5.1.10
Firebase Component:  Database
Component version: FirebaseDatabase (5.0.4)
           The pod I am using is :
___________________________________________________________________________________
platform :osx, '10.11'
target '####' do
  use_frameworks!
  #use_modular_headers!
  # Pods 
  pod 'FirebaseCore'	#Prerequisite libraries and Analytics
  pod 'FirebaseAuth'
  pod 'FirebaseDatabase'	#Realtime Database
end
___________________________________________________________________________________

The authorization work fine, but when trying to get an instance of the Database, I get a NULL.
let RTDBref = Database.database() // <- this is null

**Comment by ryanwilson** [comment]
@vladvarna sorry you’re having issues - are you calling ‘FirebaseApp.configure()’ before this?

Is anything logged to the console at all? It would be helpful if you could copy any Firebase related logs from the console so we can better understand what the issue is.

**Comment by paulb777** [comment]
This might be the issue with CocoaPods 1.5.3 not adding `-ObjC` to the `OTHER_LDFLAGS` Build Setting.

The workaround is using the CocoaPods 1.6.0 prerelease or adding `-ObjC` manually to the Build Settings.

**Comment by vladvarna** [comment]
Hi,
    Thanks for the reply, yes I am calling the FirebaseApp.configure(), and
also doing the authentication, which works ok, I can see the user in the
Firebase Console, In the completion handler of the authentication functions
I am trying to instantiate a Realtime Database object, which returns NULL,
and there is nothing shown in the console. I've also tried putting a sleep
to make sure the authentication is finished.
    I have attached the workspace minus the GoogleService-Info.plist (I
have tried using two account, one with rules set to all true, and they both
behaved the same) and the pods folder (a pod install should recreate them,
if not I can try sending them in a larger archive)
https://www.dropbox.com/s/bd3ejms1qoo8dkn/SMOtest%20copy.zip?dl=0

**Comment by vladvarna** [comment]
> This might be the issue with CocoaPods 1.5.3 not adding `-ObjC` to the `OTHER_LDFLAGS` Build Setting for OSX targets.
> 
> The workaround is using the CocoaPods 1.6.0 prerelease or adding `-ObjC` manually to the Build Settings.

Thanks, this was the problem
