### ISSUE TITLE
FirebaseInstanceID 3.4 not available

### ISSUE THREAD

**Issue by netizen01** [firebase/firebase-ios-sdk#2261]
Newly published pod spec for Messaging references FirebaseInstanceID 3.4, which is not available as a pod yet.

**Comment by paulb777** [comment]
The latest published FirebaseMessaging podspec still references FirebaseInstanceID 3.0.  See https://github.com/CocoaPods/Specs/blob/master/Specs/2/d/6/FirebaseMessaging/3.2.2/FirebaseMessaging.podspec.json#L40.

The next release that references 3.4 is being stabilized.  FirebaseInstanceID 3.4.0 is staged at https://github.com/firebase/SpecsStaging, but we do not recommend that be used for anything except testing until it posted to the master CocoaPods Specs repo.

**Comment by paulb777** [comment]
Closing now. We can reopen if my answer is missing something.
