### ISSUE TITLE
Firestore Fatal Error on reading query snapshot document changes

### ISSUE THREAD

**Issue by Thomas-Cartotto** [firebase/firebase-ios-sdk#2265]
* Xcode version: 10.1
  * Firebase SDK version: 5.15.0
  * Firebase Component: Firestore
  * Component version: 0.16.1

I am trying to loop through an array of document changes retrieved from a QuerySnapshot. When attempting to access an element from the [DocumentChange] array or loop through them (ie. snapshot.documentChanges.forEach) this fatal error occurs: "NSArray element failed to match the Swift Array Element type". 

This code can be used to recreate the error which occurs on line: snapshot.documentChanges.forEach

```swift
        let query: Query
        private var profileListener: ListenerRegistration?

        self.profileListener = query.addSnapshotListener
        {
            (querySnapshot: QuerySnapshot?, error: Error?) in
                    
            guard let snapshot = querySnapshot else
            {
                print("Error fetching snapshots: \(error?.localizedDescription ?? "")")
                return
            }
            
            snapshot.documentChanges.forEach
            {
                (diff: DocumentChange) in
                
                let document = diff.document
            }
        }
```

**Comment by mikelehen** [comment]
Please see https://github.com/firebase/firebase-ios-sdk/issues/2085#issuecomment-439586294 for a possible explanation. If you're not sure why it's happening, please provide the info that @morganchen12 asked for there. Thanks!

**Comment by wilhuff** [comment]
@morganchen12 I've taken this code and annotated it in a project I have lying around:

```swift
        let query: Query
        private var profileListener: ListenerRegistration?

        self.profileListener = query.addSnapshotListener
        {
            (querySnapshot: QuerySnapshot?, error: Error?) in
                    
            guard let snapshot: QuerySnapshot = querySnapshot else
            {
                print("Error fetching snapshots: \(error?.localizedDescription ?? "")")
                return
            }
            
            snapshot.documentChanges.forEach
            {
                (diff: DocumentChange) in
                
                let document: QueryDocumentSnapshot = diff.document
                print("Document id: \(document.documentID)")
            }
        }
```

This looks reasonable to me. However, I also can't reproduce the problem you're describing: the changes come through just fine (my small addition shows all the document IDs for all the changes).

I've also tried to figure out how we could conceivably end up with an element in the array that isn't a `DocumentChange` but I can't see it by inspection either. The `documentChanges` property is [computed on demand here](https://github.com/firebase/firebase-ios-sdk/blob/fa2aa4f301bab04746b3f19cdfe53958aa3e8bd7/Firestore/Source/API/FIRQuerySnapshot.mm#L159) and its contents are populated either [here in the initial case](https://github.com/firebase/firebase-ios-sdk/blob/fa2aa4f301bab04746b3f19cdfe53958aa3e8bd7/Firestore/Source/API/FIRDocumentChange.mm#L74) or [here in the update case](https://github.com/firebase/firebase-ios-sdk/blob/fa2aa4f301bab04746b3f19cdfe53958aa3e8bd7/Firestore/Source/API/FIRDocumentChange.mm#L110). Neither seem capable of adding anything other than a `DocumentChange` to the `NSMutableArray`.

@Thomas-Cartotto can you confirm that these are the types you're seeing? Does this happen for all queries you run? Does the first time? Subsequent times?

**Comment by wilhuff** [comment]
I can't reproduce the underlying issue, and without more information on this there's really nothing I can do. @morganchen12 or @Thomas-Cartotto if you're able to reproduce this please let us know and we'll reopen and investigate further.
