### ISSUE TITLE
FIRGeoPoint return null

### ISSUE THREAD

**Issue by alkharaz** [firebase/firebase-ios-sdk#2270]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: Version 10.1 (10B61)
  * Firebase SDK version: Firebase/Core (5.15.0)
  * Firebase Component: Firestore
  * Component version: Firebase/Firestore (5.15.0)

### [REQUIRED] Step 3: Describe the problem

Using Objective-c lang

I have [mkmapview annotations] which is array of MKPointAnnotation
I try to convert MKPointAnnotation to FIRGeoPoint : 

```
for (MKPointAnnotation *point in annotationsArray) {
        FIRGeoPoint *FirAnnotations;
        FirAnnotations = [FirAnnotations initWithLatitude:point.coordinate.latitude longitude:point.coordinate.longitude];
        NSLog(@"FirAnnotations: %@",FirAnnotations);
    }
```
annotationsArray is [mkmapview annotations]

always get null

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by ryanwilson** [comment]
The code sample you gave has a bug in it: you're attempting to use the pointer to call `init` but it's `nil` and you should be using the `FIRGeoPoint` there. 

If you use:

```
for (MKPointAnnotation *point in annotationsArray) {
        FIRGeoPoint *annotations;
        annotations = [[FIRGeoPoint alloc] initWithLatitude:point.coordinate.latitude 
                                                  longitude:point.coordinate.longitude];
        NSLog(@"annotations: %@",annotations);
}
```

That should do the trick!

**Comment by ryanwilson** [comment]
Closing for now but feel free to re-open if the code snippet doesn't solve your issue.
