### ISSUE TITLE
FirebaseCore Lexical or preprocessor issue

### ISSUE THREAD

**Issue by Smiller193** [firebase/firebase-ios-sdk#2281]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.0
  * Firebase SDK version: 5.15.0
  * Firebase Component: Core (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: _____

#### Steps to reproduce:

So I am having an issue with compiling my project with firebase. This issue started the minuted I updated all my firebase pods. Ever since i updated the pods I have been getting this error

Lexical or preprocessor issue and then when I go to what the error is it says this 'GoogleUtilities/GULAppEnvironmentUtil.h' file not found

Has anyone faced this problem or have any idea how to fix it?

I have tried uninstalling and installing, I have tried changing the scheme and rebuilding, I have tried cleaning and building and nothing has worked.

I have included a picture of what I can see in Xcode.

<img width="1280" alt="screen shot 2019-01-17 at 7 49 06 pm" src="https://user-images.githubusercontent.com/16108750/51359440-c5a6c100-1a95-11e9-8f2e-6857c193a818.png">

Here is the text representation of my podfile

    workspace 'Eventful'
    target 'Eventful' do
        #project '/Users/BandManFabo/Desktop/EventfulApp/EventfulApp1/Eventful/Eventful.xcodeproj'
        # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
        workspace 'Eventful'
        use_frameworks!
        pod 'FirebaseCore'
        pod 'FirebaseAuth’
        pod 'FirebaseDatabase’
        pod 'FirebaseStorage’
        pod 'FirebaseMessaging’
        pod 'BPStatusBarAlert'
        pod 'Alamofire'
        pod 'AlamofireImage'
        pod 'AlamofireNetworkActivityIndicator'
        pod ‘SVProgressHUD’
        pod 'SwiftLocation'
        pod 'IGListKit', :git => 'https://github.com/Instagram/IGListKit.git', :branch => 'master'
        pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git'
        pod 'Fabric'
        pod 'Crashlytics'
        
        pod 'NotificationBannerSwift', :git => 'https://github.com/Daltron/NotificationBanner', :branch => 'master'
        pod 'MarqueeLabel/Swift', '3.2.0'
        pod 'GooglePlaces'
        pod 'GooglePlacePicker'
        pod 'GoogleMaps'
        pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git', :branch => 'master'
        pod 'RevealingSplashView'
        pod "RecordButton"
        pod 'DTPagerController'
        pod 'SimpleImageViewer', '~> 1.1.1'
        pod 'IQKeyboardManagerSwift'
        pod 'SwipeCellKit',:git => 'https://github.com/SwipeCellKit/SwipeCellKit.git', :branch => 'master'
        pod 'XLActionController/Twitter'
        pod 'Instabug'
        pod 'InstantSearch'
        pod 'YNSearch'
        pod 'AMPopTip'
        
        pod 'AZDialogView'
        pod 'SwiftEntryKit', :git => 'https://github.com/huri000/SwiftEntryKit', :branch => 'master'
    
        pod 'Eureka'
        pod 'ImageRow', '~> 3.0'
        pod 'TokenRow'
        pod 'TableRow'
        pod 'ViewRow', :git => 'https://github.com/EurekaCommunity/ViewRow'
    
        pod 'AlgoliaSearch-Client-Swift'
        pod 'Kingfisher'
        pod 'DZNEmptyDataSet'
        pod 'Segmentio', :git => 'https://github.com/Yalantis/Segmentio', :branch => 'master'
        pod 'TransitionButton'
        pod 'DropDown', :git => 'https://github.com/AssistoLab/DropDown', :branch => 'master'
        pod "TLPhotoPicker"
        pod 'CRRefresh'
    
    
        pod 'AFDateHelper'
        pod 'ColorSlider'
        pod 'SnapSliderFilters'
        
        pod 'YPImagePicker'
    #    pod 'OneSignal', '>= 2.6.2', '< 3.0'
        pod 'SnapKit', '~> 4.2.0'
    
        pod 'Parchment',:git => 'https://github.com/rechsteiner/Parchment', :branch => 'master'
        pod 'TagListView', '~> 1.0'
    
        
        # Pods for Eventful
    end

**Comment by paulb777** [comment]
The `Firebase Core 2` scheme looks suspicious.  Does the GoogleUtilities file actually exist?  `pod deintegrate` and `pod install` might help.

**Comment by Smiller193** [comment]
When I run pod install I see this regardless of whether or not I remove or add firebase it is kinda weird
<img width="336" alt="screen shot 2019-01-17 at 8 37 08 pm" src="https://user-images.githubusercontent.com/16108750/51359933-bc1e5880-1a97-11e9-95a1-fffee7b354ba.png">

**Comment by Smiller193** [comment]
however when I search it up I can't find it

**Comment by Smiller193** [comment]
yeah that didn't work

**Comment by Smiller193** [comment]
There seems to be an issue with FIreLogger.m

**Comment by Smiller193** [comment]
I just want to work on my project again and this is making it very hard lol @paulb777

**Comment by paulb777** [comment]
@Smiller193 It looks similar to #2100. If you're still stuck after looking at that one, please share your `Podfile.lock`.

**Comment by Smiller193** [comment]
> PODS:
  - AFDateHelper (4.2.7)
  - Alamofire (4.8.1)
  - AlamofireImage (3.5.0):
    - Alamofire (~> 4.8)
  - AlamofireNetworkActivityIndicator (2.3.0):
    - Alamofire (~> 4.7)
  - AlgoliaSearch-Client-Swift (5.1.7)
  - AMPopTip (3.5.0)
  - AZDialogView (1.3.0)
  - BPStatusBarAlert (0.1.6)
  - CLTokenInputView (2.3.0)
  - ColorSlider (4.3)
  - Crashlytics (3.12.0):
    - Fabric (~> 1.9.0)
  - CRRefresh (1.1.3)
  - DropDown (2.3.12)
  - DTPagerController (2.0.2)
  - DZNEmptyDataSet (1.8.1)
  - Eureka (4.3.1)
  - Fabric (1.9.0)
  - Firebase/CoreOnly (5.15.0):
    - FirebaseCore (= 5.1.10)
  - Firebase/Database (5.15.0):
    - Firebase/CoreOnly
    - FirebaseDatabase (= 5.0.4)
  - FirebaseAnalyticsInterop (1.1.0)
  - FirebaseAuth (5.2.0):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 5.1)
    - GoogleUtilities/Environment (~> 5.2)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseAuthInterop (1.0.0)
  - FirebaseCore (5.1.10):
    - GoogleUtilities/Logger (~> 5.2)
  - FirebaseDatabase (5.0.4):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 5.1)
    - leveldb-library (~> 1.18)
  - FirebaseInstanceID (3.3.0):
    - FirebaseCore (~> 5.1)
    - GoogleUtilities/Environment (~> 5.3)
    - GoogleUtilities/UserDefaults (~> 5.3)
  - FirebaseMessaging (3.2.2):
    - FirebaseAnalyticsInterop (~> 1.1)
    - FirebaseCore (~> 5.1)
    - FirebaseInstanceID (~> 3.0)
    - GoogleUtilities/Environment (~> 5.2)
    - GoogleUtilities/Reachability (~> 5.2)
    - Protobuf (~> 3.1)
  - FirebaseStorage (3.0.3):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 5.1)
    - GTMSessionFetcher/Core (~> 1.1)
  - GeoFire (3.0.0):
    - Firebase/Database (~> 5.0)
  - GoogleMaps (2.7.0):
    - GoogleMaps/Maps (= 2.7.0)
  - GoogleMaps/Base (2.7.0)
  - GoogleMaps/Maps (2.7.0):
    - GoogleMaps/Base
  - GooglePlacePicker (2.7.0):
    - GoogleMaps (= 2.7.0)
    - GooglePlaces (= 2.7.0)
  - GooglePlaces (2.7.0):
    - GoogleMaps/Base (= 2.7.0)
  - GoogleUtilities/Environment (5.3.7)
  - GoogleUtilities/Logger (5.3.7):
    - GoogleUtilities/Environment
  - GoogleUtilities/Reachability (5.3.7):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (5.3.7):
    - GoogleUtilities/Logger
  - GTMSessionFetcher/Core (1.2.1)
  - IGListKit (3.4.0):
    - IGListKit/Default (= 3.4.0)
  - IGListKit/Default (3.4.0):
    - IGListKit/Diffing
  - IGListKit/Diffing (3.4.0)
  - ImageRow (3.2.0):
    - Eureka (~> 4.3)
  - Instabug (8.0.17)
  - InstantSearch (3.1.3):
    - InstantSearch/UI (= 3.1.3)
  - InstantSearch/UI (3.1.3):
    - InstantSearchCore (~> 4.0)
  - InstantSearchClient (6.1.1)
  - InstantSearchCore (4.0.0):
    - InstantSearchClient (~> 6.0)
  - IQKeyboardManagerSwift (6.2.0)
  - JTAppleCalendar (7.1.6)
  - Kingfisher (5.1.0)
  - leveldb-library (1.20)
  - MarqueeLabel/Swift (3.2.0)
  - NotificationBannerSwift (2.0.1):
    - MarqueeLabel/Swift (~> 3.2.0)
    - SnapKit (~> 4.2.0)
  - Parchment (1.5.0)
  - Protobuf (3.6.1)
  - PryntTrimmerView (3.0.0)
  - QuickLayout (2.1.1)
  - RecordButton (1.0.2)
  - RevealingSplashView (0.6.0)
  - Segmentio (3.3)
  - SimpleImageViewer (1.1.1)
  - SnapKit (4.2.0)
  - SnapSliderFilters (2.0)
  - SteviaLayout (4.4.3)
  - SVProgressHUD (2.2.5)
  - SwiftEntryKit (0.8.8):
    - QuickLayout (= 2.1.1)
  - SwiftLocation (3.2.3):
    - SwiftyJSON (~> 4.0.0-alpha.1)
  - SwiftyJSON (4.0.0)
  - SwipeCellKit (2.5.1)
  - TableRow (0.3.1):
    - Eureka (~> 4.3)
  - TagListView (1.3.2)
  - TLPhotoPicker (1.8.0)
  - TokenRow (1.3.0):
    - CLTokenInputView (~> 2.0)
    - Eureka (~> 4.0)
  - TransitionButton (0.5.2)
  - ViewRow (0.3.0):
    - Eureka (>= 4.0.0)
  - XLActionController/Core (4.1.1)
  - XLActionController/Twitter (4.1.1):
    - XLActionController/Core
  - YNSearch (2.3.2)
  - YPImagePicker (3.5.3):
    - PryntTrimmerView (~> 3.0.0)
    - SteviaLayout (~> 4.4.1)

DEPENDENCIES:
  - AFDateHelper
  - Alamofire
  - AlamofireImage
  - AlamofireNetworkActivityIndicator
  - AlgoliaSearch-Client-Swift
  - AMPopTip
  - AZDialogView
  - BPStatusBarAlert
  - ColorSlider
  - Crashlytics
  - CRRefresh
  - DropDown (from `https://github.com/AssistoLab/DropDown`, branch `master`)
  - DTPagerController
  - DZNEmptyDataSet
  - Eureka
  - Fabric
  - FirebaseAuth
  - FirebaseDatabase
  - FirebaseMessaging
  - FirebaseStorage
  - GeoFire (from `https://github.com/firebase/geofire-objc.git`)
  - GoogleMaps
  - GooglePlacePicker
  - GooglePlaces
  - IGListKit (from `https://github.com/Instagram/IGListKit.git`, branch `master`)
  - ImageRow (~> 3.0)
  - Instabug
  - InstantSearch
  - IQKeyboardManagerSwift
  - JTAppleCalendar (from `https://github.com/patchthecode/JTAppleCalendar.git`, branch `master`)
  - Kingfisher
  - MarqueeLabel/Swift (= 3.2.0)
  - NotificationBannerSwift (from `https://github.com/Daltron/NotificationBanner`, branch `master`)
  - Parchment (from `https://github.com/rechsteiner/Parchment`, branch `master`)
  - RecordButton
  - RevealingSplashView
  - Segmentio (from `https://github.com/Yalantis/Segmentio`, branch `master`)
  - SimpleImageViewer (~> 1.1.1)
  - SnapKit (~> 4.2.0)
  - SnapSliderFilters
  - SVProgressHUD
  - SwiftEntryKit (from `https://github.com/huri000/SwiftEntryKit`, branch `master`)
  - SwiftLocation
  - SwipeCellKit (from `https://github.com/SwipeCellKit/SwipeCellKit.git`, branch `master`)
  - TableRow
  - TagListView (~> 1.0)
  - TLPhotoPicker
  - TokenRow
  - TransitionButton
  - ViewRow (from `https://github.com/EurekaCommunity/ViewRow`)
  - XLActionController/Twitter
  - YNSearch
  - YPImagePicker

SPEC REPOS:
  https://github.com/cocoapods/specs.git:
    - AFDateHelper
    - Alamofire
    - AlamofireImage
    - AlamofireNetworkActivityIndicator
    - AlgoliaSearch-Client-Swift
    - AMPopTip
    - AZDialogView
    - BPStatusBarAlert
    - CLTokenInputView
    - ColorSlider
    - Crashlytics
    - CRRefresh
    - DTPagerController
    - DZNEmptyDataSet
    - Eureka
    - Fabric
    - Firebase
    - FirebaseAnalyticsInterop
    - FirebaseAuth
    - FirebaseAuthInterop
    - FirebaseCore
    - FirebaseDatabase
    - FirebaseInstanceID
    - FirebaseMessaging
    - FirebaseStorage
    - GoogleMaps
    - GooglePlacePicker
    - GooglePlaces
    - GoogleUtilities
    - GTMSessionFetcher
    - ImageRow
    - Instabug
    - InstantSearch
    - InstantSearchClient
    - InstantSearchCore
    - IQKeyboardManagerSwift
    - Kingfisher
    - leveldb-library
    - MarqueeLabel
    - Protobuf
    - PryntTrimmerView
    - QuickLayout
    - RecordButton
    - RevealingSplashView
    - SimpleImageViewer
    - SnapKit
    - SnapSliderFilters
    - SteviaLayout
    - SVProgressHUD
    - SwiftLocation
    - SwiftyJSON
    - TableRow
    - TagListView
    - TLPhotoPicker
    - TokenRow
    - TransitionButton
    - XLActionController
    - YNSearch
    - YPImagePicker

EXTERNAL SOURCES:
  DropDown:
    :branch: master
    :git: https://github.com/AssistoLab/DropDown
  GeoFire:
    :git: https://github.com/firebase/geofire-objc.git
  IGListKit:
    :branch: master
    :git: https://github.com/Instagram/IGListKit.git
  JTAppleCalendar:
    :branch: master
    :git: https://github.com/patchthecode/JTAppleCalendar.git
  NotificationBannerSwift:
    :branch: master
    :git: https://github.com/Daltron/NotificationBanner
  Parchment:
    :branch: master
    :git: https://github.com/rechsteiner/Parchment
  Segmentio:
    :branch: master
    :git: https://github.com/Yalantis/Segmentio
  SwiftEntryKit:
    :branch: master
    :git: https://github.com/huri000/SwiftEntryKit
  SwipeCellKit:
    :branch: master
    :git: https://github.com/SwipeCellKit/SwipeCellKit.git
  ViewRow:
    :git: https://github.com/EurekaCommunity/ViewRow

CHECKOUT OPTIONS:
  DropDown:
    :commit: 91aa1f16920a6c3dc3e1bdf7eaf300df8f6ec559
    :git: https://github.com/AssistoLab/DropDown
  GeoFire:
    :commit: 7bc124db5d7c428bffe7ee4bd10ea9ad55f54523
    :git: https://github.com/firebase/geofire-objc.git
  IGListKit:
    :commit: 36d1b8b21061741e262ee52e3de804dfd10d14ff
    :git: https://github.com/Instagram/IGListKit.git
  JTAppleCalendar:
    :commit: 1db39cd4c2eea1df7cbb844c0b6a2e453d7da4b0
    :git: https://github.com/patchthecode/JTAppleCalendar.git
  NotificationBannerSwift:
    :commit: 17badd31e450b0a35917cf1a877dee7a77d9ae4f
    :git: https://github.com/Daltron/NotificationBanner
  Parchment:
    :commit: 1ac102af54ae6c2bad21c869225f25164175d22d
    :git: https://github.com/rechsteiner/Parchment
  Segmentio:
    :commit: 22f992062348ca2877a1e66fdd673e62d4bb7543
    :git: https://github.com/Yalantis/Segmentio
  SwiftEntryKit:
    :commit: ac09b88f84dd6d6148a865c18c0f89fc51a7f4b8
    :git: https://github.com/huri000/SwiftEntryKit
  SwipeCellKit:
    :commit: cd5984ae43a9f55691a0cc5cbd415f3eb6eec27c
    :git: https://github.com/SwipeCellKit/SwipeCellKit.git
  ViewRow:
    :commit: 3a1d4a9d157f275ad3db12f6909974523ad564ee
    :git: https://github.com/EurekaCommunity/ViewRow

SPEC CHECKSUMS:
  AFDateHelper: 4ad66fb19503041fbba8a3018cb7ef9c71b2ff88
  Alamofire: 16ce2c353fb72865124ddae8a57c5942388f4f11
  AlamofireImage: 1aea346f4dda2f6c67622fa5a89fcbb80d79cc16
  AlamofireNetworkActivityIndicator: 18346ff6d770d9513d0ac6f2d99706f40f93dbaa
  AlgoliaSearch-Client-Swift: 13f8abe012615ed3ccc35dc61ce0401a191be0ff
  AMPopTip: 871ae0570b68fe396e714922b3f7d8ed6a36bb71
  AZDialogView: 9301351cb2e12d36f2757ccdaec56f016d89575d
  BPStatusBarAlert: 6da5d5194da3a02a9e5e529f1c49a78b694e336b
  CLTokenInputView: 9dc1ffb7c9d2d81787e69a63c75bd97b0b2d1e76
  ColorSlider: 83fb6f174a13d7235ef100d8d5fee1f71adf2182
  Crashlytics: 07fb167b1694128c1c9a5a5cc319b0e9c3ca0933
  CRRefresh: 1415d4ae06837fa7bb064c44f2e102f3ef517044
  DropDown: 0bcc278799ec11a3d34ce1aac9367fbbaf5423d9
  DTPagerController: c462532a15498d168904ed5f6ded1674e34f1330
  DZNEmptyDataSet: 9525833b9e68ac21c30253e1d3d7076cc828eaa7
  Eureka: 28ea296f06710f6745266b71f17862048941a32d
  Fabric: f988e33c97f08930a413e08123064d2e5f68d655
  Firebase: 8bb9268bff82374f2cbaaabb143e725743c316ae
  FirebaseAnalyticsInterop: e5f21be9af6548372e2f0815834ff909bff395a2
  FirebaseAuth: 02e969ff430e156d99d4cb842d77b806b71ad7bb
  FirebaseAuthInterop: 0ffa57668be100582bb7643d4fcb7615496c41fc
  FirebaseCore: 35747502d9e8c6ee217385ad04446c7c2aaf9c5c
  FirebaseDatabase: 0621689f77528d62b47e1c06ca737c4c19275d1a
  FirebaseInstanceID: e2fa4cb35ef5558c200f7f0ad8a53e212215f93e
  FirebaseMessaging: b412996f6a09337d232bb3a6676ce4d1f353d024
  FirebaseStorage: 3d22c041370593e639fba013d1eb698a8dae2881
  GeoFire: e3ae6f4be3f2466c3467ef6c1c203db3af935c59
  GoogleMaps: f79af95cb24d869457b1f961c93d3ce8b2f3b848
  GooglePlacePicker: 59ea44db173c58486ad6123993e81feefcbce9c3
  GooglePlaces: 3d06e6c99654545b4738ce49648745779c25f2ef
  GoogleUtilities: 111a012f4c3a29c9e7c954c082fafd6ee3c999c0
  GTMSessionFetcher: 32aeca0aa144acea523e1c8e053089dec2cb98ca
  IGListKit: 7a5d788e9fb746bcd402baa8e8b24bc3bd2a5a07
  ImageRow: 03681b3ef8034b5a649440325f5d5ba7b22c1b0a
  Instabug: 399f0ce0ac407adcd157c4a0693918442b13d9c3
  InstantSearch: c5ec1dd67f2d68b68026dd8086ad858659b5a2cd
  InstantSearchClient: 8e3754ff154e2d65b0a391671a2a36f045a9bf5a
  InstantSearchCore: d7213fee88c766297624c54f8257cff987cd1037
  IQKeyboardManagerSwift: b07ccf9d8cafe993dcd6cb794eb4ba34611a0c4e
  JTAppleCalendar: abb30678f42a4ef8a340a932b1dcb8c85a33dac2
  Kingfisher: fcec238063d17404fca89bf0a850583211c4cbf6
  leveldb-library: 08cba283675b7ed2d99629a4bc5fd052cd2bb6a5
  MarqueeLabel: 440a502b91a9179bd98f9fff00ba1150650a1c0e
  NotificationBannerSwift: 007774aa590cc9680647b92b2f217bef5c00c32c
  Parchment: 5a8c9c73549a6d73a7c1b606c27246910d2e5720
  Protobuf: 1eb9700044745f00181c136ef21b8ff3ad5a0fd5
  PryntTrimmerView: 53ac64053c7ce63cb3e27f54090f52da0734891d
  QuickLayout: 9af2b7fd89a6552828f51a5aba28d1bcdb8b340c
  RecordButton: 76677be0f4b94f8a387454a23b4b64bd9b6c0e51
  RevealingSplashView: 40c5a770894459736acdc95655eeba0dd30ce91c
  Segmentio: 4ff49aa4f4c916998c0d886c549ce62ca9eae251
  SimpleImageViewer: 34c3a2cde2d9ac022146772cefc27fca14b0c8b1
  SnapKit: fe8a619752f3f27075cc9a90244d75c6c3f27e2a
  SnapSliderFilters: 7f571683b05cf70b8d398e4a0e45691bd9f03a33
  SteviaLayout: ae5ee66101e03607a93c9b3773b84ab7ba7b3d17
  SVProgressHUD: 1428aafac632c1f86f62aa4243ec12008d7a51d6
  SwiftEntryKit: c50f25a14772713ded1591c852d1c1dc74c95b9e
  SwiftLocation: a3c3bc2023118171ef3572188a31def94aa0892c
  SwiftyJSON: 070dabdcb1beb81b247c65ffa3a79dbbfb3b48aa
  SwipeCellKit: 30fd6a4f8a8b8ac864ea389c8b4c8bac5ba5471a
  TableRow: b5f19082db9e884e0ebab868035d57e7b19193c8
  TagListView: 0c7e9c26b9aff858224ee6b155f5fcacd9e27c83
  TLPhotoPicker: e68572b74b5c36ccf146493b7d71568984c239d1
  TokenRow: 1fd9b57805c1229656282a0823a0188039d9af22
  TransitionButton: fb271583d9c9e4bb116b97103047e5157653f233
  ViewRow: e278428ff53da5eab18b191d3e19a16f3e299fc1
  XLActionController: d2ab12a967ae0fee0b4563b8d809c8fb13ebc636
  YNSearch: 2e19952c0d0845bf9c6ec2f2d53eca6e57143ac6
  YPImagePicker: 5dd3814b47b1208e9c8cc8f6ef77fe90db3723b6

PODFILE CHECKSUM: 6ddc5a5cb5ab8311a5ff74c9e3fe66d4057b0e19

COCOAPODS: 1.6.0.beta.1

**Comment by Smiller193** [comment]
@paulb777  see podfile.lock above

**Comment by paulb777** [comment]
Closing for now. Will reopen with more details.

**Comment by dfiggtns** [comment]
After reading many solutions, what worked for me was doing a pod update:

    cd platforms/ios; pod update; cd ../..

That brought all the versions into line. Occams razor, I guess.

**Comment by lukemmtt** [comment]
Thanks @dfiggtns for following up. I just had the same issue that was also fixed by a pod update.
