### ISSUE TITLE
UITest crash when use both Alamofire and Firebase

### ISSUE THREAD

**Issue by linhCrystal** [firebase/firebase-ios-sdk#2294]
### [READ] Step 1: Are you in the right place?

  Yes

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.1
  * Firebase SDK version: 5.15
  * Firebase Component: Core, MLVision, MLVisionBarcodeModel (5.15)

### [REQUIRED] Step 3: Describe the problem

Crash when run UITest

```
  ProjUITests-Runner[42121:216520] The bundle “ProjUITests” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
  2019-01-19 17:28:06.652360+0800 ProjUITests-Runner[42121:216520] (dlopen_preflight(/Users/macone/Library/Developer/Xcode/DerivedData/Proj-gphlirwtphdbneghkglpczywguev/Build/Products/Debug-iphonesimulator/ProjUITests-Runner.app/PlugIns/ProjUITests.xctest/ProjUITests): Library not loaded: @rpath/libswiftSwiftOnoneSupport.dylib
  Referenced from: /Users/macone/Library/Developer/Xcode/DerivedData/Proj-gphlirwtphdbneghkglpczywguev/Build/Products/Debug-iphonesimulator/ProjUITests-Runner.app/PlugIns/ProjUITests.xctest/Frameworks/Alamofire.framework/Alamofire
  Reason: image not found)
```

#### Steps to reproduce:
I create new Proj with UI, unit test -> Add pod to Proj target (not test target):
```
pod 'Alamofire'
pod 'Firebase/Core'
pod 'Firebase/MLVision'
pod 'Firebase/MLVisionBarcodeModel'
```
Then I run UI test and it crash.
But it not crash when I only use Alamofire or only use Firebase.

My full Podfile:
```
platform :ios, '11.0'

target 'Proj' do
  use_frameworks!

  # Pods for Proj
  pod 'Alamofire'
  pod 'Firebase/Core'
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionBarcodeModel'

  target 'ProjTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProjUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

**Comment by paulb777** [comment]
Thanks for the report @linhCrystal 

`inherit! :search_paths` should not be used with UITests.  Details at https://github.com/CocoaPods/CocoaPods/pull/8423. 

Let us know if removing it fixes the crash.

**Comment by linhCrystal** [comment]
> Thanks for the report @linhCrystal
> 
> `inherit! :search_paths` should not be used with UITests. Details at [CocoaPods/CocoaPods#8423](https://github.com/CocoaPods/CocoaPods/pull/8423).
> 
> Let us know if removing it fixes the crash.

It still crash. And still remove pod Alamofire fix the crash.

When I remove `inherit! :search_paths`, there's a warning `target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES``. I tried delete "Always embed..." but it still crash.

**Comment by paulb777** [comment]
Does un-nesting the UITests target or one of the other workarounds at https://stackoverflow.com/questions/34990175/test-target-x-encountered-an-error-early-unexpected-exit-operation-never-finis help?

**Comment by linhCrystal** [comment]
I fix the crash by do the following:
- remove `inherit! :search_paths` in UITest
- move test target to outside of Proj target
- delete `Always Embed Swift Standard Libraries`
