### ISSUE TITLE
dyld: Symbol not found: after integrating with Carthage

### ISSUE THREAD

**Issue by agordeev** [firebase/firebase-ios-sdk#2295]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode Version 10.1 (10B61)
  * Firebase SDK version: 5.15.0
  * Firebase Component: Auth, Core, Firestore
  * Component version: 5.15.0

#### Steps to reproduce:

My Cartfile:

```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAuthBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseFirestoreBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseStorageBinary.json"
```

Frameworks included:
<img width="1305" alt="screenshot 2019-01-20 at 17 28 15" src="https://user-images.githubusercontent.com/2883524/51440493-d004cd00-1cd8-11e9-829c-34597d135293.png">

Crash after launching the app:

dyld: Symbol not found: _DAAccountFolderContentsChangedNotification
  Referenced from: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/Message.framework/Message
  Expected in: /Users/xxx/Library/Developer/Xcode/DerivedData/Xxx-bgpessbtpiqmcjeckxjgrekdsxjz/Build/Products/Debug-iphonesimulator/DataAccess.framework/DataAccess
 in /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/Message.framework/Message

Also is that really necessary to pull all the 21 frameworks (including StoreKit) just to do few reads/writes into the Firestore?

**Comment by paulb777** [comment]
I'm not able to reproduce. From Googling a bit, it looks like `_DAAccountFolderContentsChangedNotification` was a symbol in older iOS versions in `Message.framework`, `Messages.framework` or `DataAccess.framework`.

Perhaps, you need a clean build or `rm -rf ~/Library/Developer/DerivedData`?

Regarding the number of frameworks:`RxSwift.framework` is not related to Firebase and can be removed.  

Firestore leverages multiple technologies so does require several contributing frameworks. However, we don't have quite the configuration capability in Carthage as we do with CocoaPods and a few of the frameworks from `FirebaseAnalyticsBinary.json` are not required if you're not interested in using Firebase Analytics. We'll reorganize this and update the docs in an upcoming release(#2296). In the meantime, you can remove frameworks from that json as long as the app continues to link.

**Comment by agordeev** [comment]
Thanks for your comment.
Clean build and cleaning DerivedData doesn't help. This started to happen after I added all of these frameworks required by Firebase

**Comment by agordeev** [comment]
Haha, that was funny. I figured out what's going on there.

My target name was `DataAccess` and it's a framework I use in the main app. The name conflicts with the private framework `DataAccess.framework`.

All works good now after I renamed my target to `DataAccessLayer`.

Thanks for trying to help Paul.
