### ISSUE TITLE
User crashes , [FIRMessagingConnection connectToSocket:]

### ISSUE THREAD

**Issue by Formerly** [firebase/firebase-ios-sdk#2309]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version:9.4.1
  * Firebase SDK version:
 - Firebase/Core (5.15.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 5.4.0)
  - Firebase/CoreOnly (5.15.0):
    - FirebaseCore (= 5.1.10)
  - Firebase/Messaging (5.15.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (= 3.2.2)
  - Firebase/RemoteConfig (5.15.0):
    - Firebase/Core
    - FirebaseRemoteConfig (= 3.1.0)
  - FirebaseABTesting (2.0.0):
    - FirebaseCore (~> 5.0)
    - Protobuf (~> 3.5)
  - FirebaseAnalytics (5.4.0):
    - FirebaseCore (~> 5.1)
    - FirebaseInstanceID (~> 3.3)
    - GoogleAppMeasurement (= 5.4.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 5.2)
    - GoogleUtilities/MethodSwizzler (~> 5.2)
    - GoogleUtilities/Network (~> 5.2)
    - GoogleUtilities/NSData+zlib (~> 5.2)
    - nanopb (~> 0.3)
  - FirebaseAnalyticsInterop (1.1.0)
  - FirebaseCore (5.1.10):
    - GoogleUtilities/Logger (~> 5.2)
  - FirebaseInstanceID (3.3.0):
    - FirebaseCore (~> 5.1)
    - GoogleUtilities/Environment (~> 5.3)
    - GoogleUtilities/UserDefaults (~> 5.3)
  - FirebaseMessaging (3.2.2):
    - FirebaseAnalyticsInterop (~> 1.1)
    - FirebaseCore (~> 5.1)
    - FirebaseInstanceID (~> 3.0)
    - GoogleUtilities/Environment (~> 5.2)
    - GoogleUtilities/Reachability (~> 5.2)
    - Protobuf (~> 3.1)
  - FirebaseRemoteConfig (3.1.0):
    - FirebaseABTesting (~> 2.0)
    - FirebaseAnalytics (~> 5.3)
    - FirebaseCore (~> 5.1)
    - FirebaseInstanceID (~> 3.3)
    - GoogleUtilities/Environment (~> 5.2)
    - GoogleUtilities/NSData+zlib (~> 5.2)
    - Protobuf (~> 3.5)

### [REQUIRED] Step 3: Describe the problem
Online user appears crash, crash log:
http://crashes.to/s/d0a128be7f7
It turns out they're all jailbroken users

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

See the crash log above

#### Relevant Code:

```
 [[FIRMessaging messaging] connectWithCompletion:^(NSError *_Nullable error) {
        if (error != nil) {
            NSLog(@"Unable to connect to FCM. %@", error);
        } else {
            NSLog(@"Connected to FCM.");
            NSString *refreshedToken = [FIRMessaging messaging].FCMToken;
            if ([BGLStringUtils isNotEmpty:refreshedToken]) {
                IUSER.firebasePushToken = refreshedToken;
            }
        }
    }];
```

**Comment by morganchen12** [comment]
Can you include the missing symbols from `XoaInfoPlug1.dylib` in the stack trace? The stack trace ends in an array out-of-bounds exception, but the Firebase Messaging method called at the top of the stack trace doesn't do any array indexing. Also, the crash seems to occur only on jailbroken devices.

**Comment by Formerly** [comment]
I tried to find `XoaInfoPlug1.dylib` and I didn't find this. My recent version of the iteration is to do pods upgrade. The previous pods version is as follows:- Firebase/Core (5.4.1):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 5.0.1)
  - Firebase/CoreOnly (5.4.1):
    - FirebaseCore (= 5.0.6)
  - Firebase/Messaging (5.4.1):
    - Firebase/CoreOnly
    - FirebaseMessaging (= 3.0.3)
  - Firebase/RemoteConfig (5.4.1):
    - Firebase/Core
    - FirebaseRemoteConfig (= 3.0.0)
  - FirebaseABTesting (2.0.0):
    - FirebaseCore (~> 5.0)
    - Protobuf (~> 3.5)
  - FirebaseAnalytics (5.0.1):
    - FirebaseCore (~> 5.0)
    - FirebaseInstanceID (~> 3.0)
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
    - nanopb (~> 0.3)
  - FirebaseCore (5.0.6):
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseInstanceID (3.1.1):
    - FirebaseCore (~> 5.0)
  - FirebaseMessaging (3.0.3):
    - FirebaseCore (~> 5.0)
    - FirebaseInstanceID (~> 3.0)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - Protobuf (~> 3.1)
  - FirebaseRemoteConfig (3.0.0):
    - FirebaseABTesting (~> 2.0)
    - FirebaseAnalytics (~> 5.0)
    - FirebaseCore (~> 5.0)
    - FirebaseInstanceID (~> 3.0)
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
    - Protobuf (~> 3.5)

After the upgrade, it seems that these crashes have occurred. Previously, there was no such crash log, and these crashes only occurred on jailbroken users.

**Comment by morganchen12** [comment]
It's hard to say for sure, but I'm guessing updating Firebase broke something jailbreak-related that's now crashing your app. If you downgrade your pods, the crashes may go away, or they might go away whenever the jailbroken devices update their jailbreak software.

Closing this for now since it doesn't seem to be a Firebase issue. **Please let us know if there are any non-jailbroken devices experiencing the same crash.**
