### ISSUE TITLE
Cannot import Firebase 5.16.0 from .mm (Objective-C++) files

### ISSUE THREAD

**Issue by ortekka** [firebase/firebase-ios-sdk#2324]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.1
  * Firebase SDK version: 5.16.0
  * Firebase Component: MLNaturalLanguage
  * Component version: 5.16.0?

### [REQUIRED] Step 3: Describe the problem

Upgrading my project from version 5.15.0 to 5.16.0 of the Firebase iOS SDK broke my build. The problem is in the new MLNaturalLanguage frameworks that were just added in 5.16.0.  They use @import directives that are not compatible with importing <Firebase.h> from .mm (Objective-C++) files, *unless* you set both the -fmodules and -fcxx-modules compiler flags, which I'd rather avoid doing if possible, since AFAIK -fcxx-modules is an experimental and not fully supported feature of the clang compiler.

**Comment by paulb777** [comment]
@ortekka Thanks for the report. We'll work on a solution.

In the meantime, a workaround seems to be removing   pod 'Firebase/MLNLLanguageID' from the `Podfile`

**Comment by paulb777** [comment]
Other workaround is editing the import in `./Pods/FirebaseMLNLLanguageID/Frameworks/FirebaseMLNLLanguageID.framework/Headers/FIRNaturalLanguage+LanguageID.h` to `#import <FirebaseMLNaturalLanguage/FirebaseMLNaturalLanguage.h>`
