### ISSUE TITLE
Deprecated Crash and Invites should be removed from Firebase pod

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#2339]
The deprecated Crash and Invites subspecs should be removed from Firebase pod at the next major release.

**Comment by BranchS** [comment]
As well as from the SDK download!

**Comment by BranchS** [comment]
Hi! Please remove these from the SDK download too (as well as from the ReadMe in the download)! Also, the website text should be updated to reflect it's now more of a ~1.6GB file, rather than 500MB.

**Comment by paulb777** [comment]
The SDK download was updated as you can see if you look at the details of #2668.  As noted, the Firebase 6 milestone this PR is in is still in progress.

The `ls -l` of the zip file from 5.20.1 is  690239833.

**Comment by BranchS** [comment]
Ah, so it'll be removed from the download when Firebase 6 rolls out? (I still see it in there now).

Thanks so much.
