### ISSUE TITLE
Missing or insufficient permissions regardless of rule.

### ISSUE THREAD

**Issue by KonsoltCorp** [firebase/firebase-ios-sdk#2342]
* Xcode version: 10.1
  * Firebase SDK version: 5.16.0 also in 5.15.0
  * Firebase Component: Firestore
  * Component version: 1.0.0

### [REQUIRED] Step 3: Updates/additions to documents always fail with the error in the subject. I have even tried to open up the rules and the outcome is the same. The only way the error does not show is if I open up the entire database (match /{document=**} {allow read, write: if request.auth.uid != null; } ) which will not work for my use case.

Rules
```
     match /Objects/{document=**} {
     	  allow read;
          allow write;
     }
```

#### Steps to reproduce:

Create a collection ("Objects") and set the access rules. In my case, even opening up the read/write rules still fails... Then create a batch operation in code that writes a new document in the collection.

#### Relevant Code:

From the iOS SDK, I am doing the following
```
let postObjectDocument = db.document(model.path)
                let favUserDoc = db.collection("Objects").document(user.id)
                let now = Date().timeIntervalString(format: .shortDateOnly)

                let favoriteObject:[String:Any] = [
                    "x": now,
                    "y": model.id,
                    "u": user.id,
                    "d": model.dictionary()
                ]
                
                // Get new write batch
                let batch = db.batch()
                let likes = model.dictionary()

                batch.updateData(likes, forDocument: postObjectDocument )

                if isAddition {
                    batch.setData(favoriteObject, forDocument: favUserDoc, merge:true)
                }else {
                    batch.deleteDocument(favUserDoc)
                }
                
                // Commit the batch
                batch.commit() { error in
                    if let error = error {
                        fatalError(error.localizedDescription)
                    }                    
                }
```

**Comment by wilhuff** [comment]
Did you intend to close this issue?
