### ISSUE TITLE
StorageReference.putFile completion never called (if file errors)

### ISSUE THREAD

**Issue by simonbengtsson** [firebase/firebase-ios-sdk#2350]
* Xcode version: 10.1
  * Firebase SDK version: 5.16
  * Firebase Component: Storage
  * Component version: 3.1.0

When using `StorageReference.putFile` errors such as "no such file" gets silenced and the completion block is never called. 

**Relevant Code/Steps to reproduce**

```
let localFile = URL(string: "non/existing/file/url")!
let ref = Storage.storage().reference(withPath: "folder/file")
ref.putFile(from: localFile, metadata: nil) { metadata, error in
    print("I would expect this to be called with an error but it never does")
}
```

At first glance it seems like https://github.com/firebase/firebase-ios-sdk/issues/1888 is related, but there it seemed like people had troubles uploading existing files as well.

**Comment by maksymmalyhin** [comment]
Note: The same issue happens when the file ULR points to an empty file.

**Comment by maksymmalyhin** [comment]
BTW, I am not sure if uploading an empty file makes sense here... @ryanwilson @schmidt-sebastian, Do you think it does?

It looks like we can throw a validation error in case of the empty file as well, then the issue can be closed by a single PR in the Firebase repo, so `GTMSessionUploadFetcher` can be fixed later.

**Comment by schmidt-sebastian** [comment]
I don't think we should reject empty files. After all, this API is going to be user with user-provided files and we should handle all file sizes gracefully for our developers. Supporting empty files is certainly not a high priority but we should support it in the long term.

**Comment by Black-riddle** [comment]
Is anyone facing the same problem even when the file is not empty (an image in my case)
PS: I am 
Using Firebase (5.14.0)
Using FirebaseAuth (5.2.0)
Using FirebaseAuthInterop (1.0.0)
Using FirebaseCore (5.1.9)
Using FirebaseStorage (3.0.3)

**Comment by maksymmalyhin** [comment]
@Black-riddle your Firebase looks a bit old. Would it be possible to test your issue with Firebase 
 5.19.0?

**Comment by Black-riddle** [comment]
@maksymmalyhin  Thank you now it works :)

**Comment by maksymmalyhin** [comment]
The issue should be completely fixed by the fix of https://github.com/google/gtm-session-fetcher/issues/140
