### ISSUE TITLE
FR: proxy support

### ISSUE THREAD

**Issue by da351hon** [firebase/firebase-ios-sdk#2364]
### Environment
  * Xcode version: 10.1
  * Firebase SDK version: 5.7.0
  * Firebase Component: Database
  * Component version: 5.0.2

### Problem
My application tried to access Firebase Realtime DB behind corporate HTTP(S) proxy, but failed. FIRAuth returned user information (AuthDataResult), but FIRDatabase did not returned any data. 
I'm afraid FIRDatabase does not use HTTP(S) but webSocket.
Could it be supported to access the DB behind the proxy?

I'm using iOS - Swift to build my application. AuthDataResult is defined as follows: https://firebase.google.com/docs/reference/swift/firebaseauth/api/reference/Classes/AuthDataResult?hl=ja

**Comment by wilhuff** [comment]
Unfortunately, the Realtime Database does not support HTTP(S) proxies and we've shifted our development focus to Firestore.

Firestore uses gRPC for transport, and that does support proxies. You can set one by setting the `http_proxy` environment variable. We don't yet directly support reading proxy configuration from the system, but this is something that's straightforward to wire together using an approach like this one: https://stackoverflow.com/a/11540930/6253640.
