### ISSUE TITLE
Push notifications working only once in IOS

### ISSUE THREAD

**Issue by tezine** [firebase/firebase-ios-sdk#2372]
Hi, Firebase Push Notifications works only once - on the first launch, after install from XCode. 
If I relaunch the app again, messages are not received. All attempts using Postman return "NotRegistered". It's really weird. 
I'm using Firebase C++ sdk (downloaded yesterday), Qt and CocoaPods. CocoaPods install the following versions:

  * Xcode version:10.1
  * Firebase SDK version: 5.16.0
  * Firebase Component: Messaging, Core, InstanceID
  * Component version: FirebaseCore 5.2.0, Messaging 3.3.0, InstanceID 3.4.0

C++ OnTokenReceived is fired every time the app is launched and sent to the server. 
If I retrieve the token manually and try to send a message directly using Postman and https://fcm.googleapis.com/fcm/send to the device, I get "NotRegistered".
While running for the first time, I can send messages successfully.
Push notifications and background remote notifications are enabled in XCode and the app is marked as allowed to receive notifications in iOS. 
The same problem happens If I try to send the message using Firebase Console. I'm using GoogleService-Info.plist and I had uploaded the APN Auth-key with key-code and team-code using Firebase Console.
Whenever I run the app, the messages below are displayed (FBListener is my C++ class):
```
(FBListener)Trying to initialize Firebase Messaging...
2019-02-09 19:40:14.751792-0200 MyApp[1121:633165] (FBListener) Module initialized. Waiting on messaging initialization
2019-02-09 19:40:14.941892-0200 MyApp[1121:633165] FCM: Initialize Firebase Messaging
2019-02-09 19:40:14.941929-0200 MyApp[1121:633165] FCM: Using FCM senderID XXX...
2019-02-09 19:40:14.942023-0200 MyApp[1121:633165] FCM: Retrieve registration token
2019-02-09 19:40:14.942217-0200 MyApp[1121:633165] (FBListener)Token received: [ XXX... ]
2019-02-09 19:40:14.942812-0200 MyApp[1121:633165] FCM: new registration token received.
2019-02-09 19:40:14.942831-0200 MyApp[1121:633165] FCM: Retrieve registration token
```

Follow my AppDelegate.m below:
```

#import <FirebaseCore/FirebaseCore.h>
#import <FirebaseMessaging/FirebaseMessaging.h>
#import <FirebaseInstanceID/FirebaseInstanceID/FirebaseInstanceID.h>
#import <UIKit/UIKit.h>
#import <UserNotifications/UserNotifications.h>
  
@interface QIOSApplicationDelegate
@end
//! Add a category to QIOSApplicationDelegate
@interface QIOSApplicationDelegate (QFacebookApplicationDelegate) //<UNUserNotificationCenterDelegate>
@end

NSString *const kGCMMessageIDKey = @"gcm.message_id";

//Codigo de exemplo em https://github.com/firebase/quickstart-ios/blob/master/messaging/MessagingExample/AppDelegate.m

@implementation QIOSApplicationDelegate (QFacebookApplicationDelegate)

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
	// Override point for customization after application launch.
	NSLog( @"Firebase configured.==============================================" );
    [FIRApp configure];
    
    // [START set_messaging_delegate]
    [FIRMessaging messaging].delegate = self;
    // [END set_messaging_delegate]
    
    // Register for remote notifications. This shows a permission dialog on first run, to
    // show the dialog at a more appropriate time move this registration accordingly.
    // [START register_for_notifications]
    if ([UNUserNotificationCenter class] != nil) {
        // iOS 10 or later
        // For iOS 10 display notification (sent via APNS)
        [UNUserNotificationCenter currentNotificationCenter].delegate = self;
        UNAuthorizationOptions authOptions = UNAuthorizationOptionAlert |
        UNAuthorizationOptionSound | UNAuthorizationOptionBadge;
        [[UNUserNotificationCenter currentNotificationCenter]
         requestAuthorizationWithOptions:authOptions
         completionHandler:^(BOOL granted, NSError * _Nullable error) {
             // ...
         }];
    } else {
        // iOS 10 notifications aren't available; fall back to iOS 8-9 notifications.
        UIUserNotificationType allNotificationTypes =
        (UIUserNotificationTypeSound | UIUserNotificationTypeAlert | UIUserNotificationTypeBadge);
        UIUserNotificationSettings *settings =
        [UIUserNotificationSettings settingsForTypes:allNotificationTypes categories:nil];
        [application registerUserNotificationSettings:settings];
    }
    
    [application registerForRemoteNotifications];
    // [END register_for_notifications]
	return YES;
}

// [START receive_message]
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo {
    // If you are receiving a notification message while your app is in the background,
    // this callback will not be fired till the user taps on the notification launching the application.
    // TODO: Handle data of notification
    
    // With swizzling disabled you must let Messaging know about the message, for Analytics
    // [[FIRMessaging messaging] appDidReceiveMessage:userInfo];
    
    // Print message ID.
    if (userInfo[kGCMMessageIDKey]) {
        NSLog(@"Message ID: %@ didReceiveRemoteNotification1", userInfo[kGCMMessageIDKey]);
    }
    
    // Print full message.
    NSLog(@"%@", userInfo);
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo
fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler {
    // If you are receiving a notification message while your app is in the background,
    // this callback will not be fired till the user taps on the notification launching the application.
    // TODO: Handle data of notification
    
    // With swizzling disabled you must let Messaging know about the message, for Analytics
    // [[FIRMessaging messaging] appDidReceiveMessage:userInfo];
    
    // Print message ID.
    if (userInfo[kGCMMessageIDKey]) {
        NSLog(@"Message ID: %@ didReceiveRemoteNotification2", userInfo[kGCMMessageIDKey]);
    }
    
    // Print full message.
    NSLog(@"%@", userInfo);
    
    completionHandler(UIBackgroundFetchResultNewData);
}
// [END receive_message]

// [START ios_10_message_handling]
// Receive displayed notifications for iOS 10 devices.
// Handle incoming notification messages while app is in the foreground.
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
       willPresentNotification:(UNNotification *)notification
         withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler {
    NSDictionary *userInfo = notification.request.content.userInfo;
    
    // With swizzling disabled you must let Messaging know about the message, for Analytics
    // [[FIRMessaging messaging] appDidReceiveMessage:userInfo];
    
    // Print message ID.
    if (userInfo[kGCMMessageIDKey]) {
        NSLog(@"Message ID: %@ willPresentNotification", userInfo[kGCMMessageIDKey]);
    }
    
    // Print full message.
    NSLog(@"%@", userInfo);
    
    // Change this to your preferred presentation option
    completionHandler(UNNotificationPresentationOptionNone);
}

// Handle notification messages after display notification is tapped by the user.
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
didReceiveNotificationResponse:(UNNotificationResponse *)response
         withCompletionHandler:(void(^)(void))completionHandler {
    NSDictionary *userInfo = response.notification.request.content.userInfo;
    if (userInfo[kGCMMessageIDKey]) {
        NSLog(@"Message ID: %@ didReceiveNotificationResponse (clicou na notificacao)", userInfo[kGCMMessageIDKey]);
    }
    
    // Print full message.
    NSLog(@"%@", userInfo);
    
    completionHandler();
}

// [START refresh_token]
- (void)messaging:(FIRMessaging *)messaging didReceiveRegistrationToken:(NSString *)fcmToken {
    NSLog(@"FCM registration token: %@", fcmToken);
    // Notify about received token.
    NSDictionary *dataDict = [NSDictionary dictionaryWithObject:fcmToken forKey:@"token"];
    [[NSNotificationCenter defaultCenter] postNotificationName:
     @"FCMToken" object:nil userInfo:dataDict];
    // TODO: If necessary send token to application server.
    // Note: This callback is fired at each app startup and whenever a new token is generated.
}
// [END refresh_token]

// [START ios_10_data_message]
// Receive data messages on iOS 10+ directly from FCM (bypassing APNs) when the app is in the foreground.
// To enable direct data messages, you can set [Messaging messaging].shouldEstablishDirectChannel to YES.
- (void)messaging:(FIRMessaging *)messaging didReceiveMessage:(FIRMessagingRemoteMessage *)remoteMessage {
    NSLog(@"Received data message: %@", remoteMessage.appData);
}
// [END ios_10_data_message]

- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error {
    NSLog(@"Unable to register for remote notifications: %@", error);
}

// This function is added here only for debugging purposes, and can be removed if swizzling is enabled.
// If swizzling is disabled then this function must be implemented so that the APNs device token can be paired to
// the FCM registration token.
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
    NSLog(@"APNs device token retrieved: %@", deviceToken);
    
    // With swizzling disabled you must set the APNs device token here.
    // [FIRMessaging messaging].APNSToken = deviceToken;
}

@end
```

**Comment by ryanwilson** [comment]
Thanks for the detailed report @tezine - does reverting to `5.15.0` solve your problem? I'm wondering if it's related to #2365.

**Comment by paulb777** [comment]
Closing for now.  Will reopen if it's different from #2365

**Comment by ranipanimisha94** [comment]
I am facing similar issue.

**Comment by zolomatok** [comment]
I have the same problem.
I was using Firebase **5.18**, reverted back to **5.15.0** and now it's working again.

**Comment by Dalein** [comment]
Firebase 5.19.0
FirebaseMessaging 3.4.0

Same issue

**Comment by gobetti** [comment]
to everyone having this after 5.15, please see issue #2438 because that seems to be the currently open one related to this problem

**Comment by PurnimaNaik** [comment]
I was facing the same issue. Here is how I fixed it (iOS specific, android was working out of the box)-

 1. Uninstall the app from your phone
 2. Clear ALL the tokens stored in your database for this particular account(or however you have set it up in your backend. In my case, tokens are tied to the account)
 3. In componentDidmount-

```
      async componentDidMount() {
        this.checkPermission();
        this.createNotificationListeners();
      }
```

4.

      async checkPermission() {
        const enabled = await firebase.messaging().hasPermission();
        if (enabled) {
          this.getToken();
        } else {
          this.requestPermission();
        }
      }

      async requestPermission() {
        try {
          await firebase.messaging().requestPermission();
          // User has authorised
          this.getToken();
        } catch (error) {
          // User has rejected permissions
          console.log('permission rejected');
        }
      }

      async getToken() {
        try {
          const enabled = await firebase.messaging().hasPermission();
          if (!enabled) {
            await firebase.messaging().requestPermission();
          }
    
          const fcmToken = await firebase.messaging().getToken();
          if (fcmToken) {
            console.log("got token");
            console.log('fcm token:', fcmToken); //-->use this token from the console to send a post request via postman
            this.setState({ fcmToken });
            return fcmToken;
          }
        } catch (error) {
          console.warn('notification token error', error);
        }
      }

5.

     async createNotificationListeners() {
        /*
        * Triggered when a particular notification has been received in foreground
        * */
        this.notificationListener = firebase.notifications().onNotification((notification) => {
            const { title, body } = notification;
            this.showAlert(title, body);
        });
      
        /*
        * If your app is in background, you can listen for when a notification is clicked / tapped / opened as follows:
        * */
        this.notificationOpenedListener = firebase.notifications().onNotificationOpened((notificationOpen) => {
            const { title, body } = notificationOpen.notification;
            this.showAlert(title, body);
        });
      
        /*
        * If your app is closed, you can check if it was opened by a notification being clicked / tapped / opened as follows:
        * */
        const notificationOpen = await firebase.notifications().getInitialNotification();
        if (notificationOpen) {
            const { title, body } = notificationOpen.notification;
            this.showAlert(title, body);
        }
        /*
        * Triggered for data only payload in foreground
        * */
        this.messageListener = firebase.messaging().onMessage((message) => {
          //process data message
          console.log(JSON.stringify(message));
        });
      }

6. Finally, use the token that you see in the console as a value for the "to" key in your post request. You should no longer see the "notRegistered" error and should be getting push notifications.
Done!!

Citations-https://medium.com/@anum.amin/react-native-integrating-push-notifications-using-fcm-349fff071591

**Comment by sorazz** [comment]
I am having the same related issues. In my case the notification is received for some time then after some time it stop to come notification.But when I hit the notification from fire base it work for some time and after that same issue occur..
