### ISSUE TITLE
Crash in [FSRRunLoopThread main] (FSRWebSocket.m:1839)

### ISSUE THREAD

**Issue by shachar-silbert** [firebase/firebase-ios-sdk#2373]
I got a crash in crashlytics that seems to lead streight to a problem in FIRWebSocket.

### ENV:

  * Xcode version: 10.1
  * Firebase Versions and use:
- Firebase/Auth (5.12.0):
    - Firebase/CoreOnly
    - FirebaseAuth (= 5.0.5)
  - Firebase/Core (5.12.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 5.3.0)
  - Firebase/CoreOnly (5.12.0):
    - FirebaseCore (= 5.1.7)
  **- Firebase/Database (5.12.0):**
    - Firebase/CoreOnly
    - FirebaseDatabase (= 5.0.3)
  * NOTE: Also  using, in parallel, Firestore V0.14

### Problem:
I got a crash that I cannot reproduce, and cannot find the reason.
Happened once, in my production env app, some details from crashlytics:
Model: iPhone 5
Version: 10.3.3 (14G60)

Happened on opening of app, before any screens or anything.

com.squareup.SocketRocket.NetworkThread 👍 com.google.fira.worker :
```
0
libsystem_kernel.dylib
mach_msg_trap + 20
1
libsystem_kernel.dylib
mach_msg + 44
2
CoreFoundation
__CFRunLoopServiceMachPort + 144
3
CoreFoundation
__CFRunLoopRun + 1436
4
CoreFoundation
CFRunLoopRunSpecific + 470
5
CoreFoundation
CFRunLoopRunInMode + 104
6
Foundation
<redacted> + 258
7
MY-APP
FSRWebSocket.m - Line 1839
-[_FSRRunLoopThread main]
8
Foundation
<redacted> + 1122
9
libsystem_pthread.dylib
_pthread_body + 216
10
libsystem_pthread.dylib
_pthread_start + 234
11
libsystem_pthread.dylib
thread_start + 8
```

Other possibly related threads:
com.google.fira.worker:
```

0
libcorecrypto.dylib
ccn_sub + 93
1
(Missing)
2
libcorecrypto.dylib
cczp_sqr_ws + 50
3
libcorecrypto.dylib
cczp_power_ssma_ws + 244
4
libcorecrypto.dylib
cczp_power_ssma + 76
5
libcorecrypto.dylib
ccprime_rabin_miller + 240
6
libcorecrypto.dylib
ccrsa_generate_probable_prime_from_auxilary_primes + 476
7
libcorecrypto.dylib
ccrsa_generate_probable_prime + 528
8
libcorecrypto.dylib
ccrsa_generate_fips186_prime_factors + 242
9
libcorecrypto.dylib
ccrsa_generate_fips186_key_trace + 224
10
libcorecrypto.dylib
ccrsa_generate_fips186_key + 26
11
Security
SecRSAPrivateKeyInit + 456
12
Security
SecKeyCreate + 106
13
Security
SecRSAKeyGeneratePair + 34
14
Security
SecKeyGeneratePair + 198
15
MY-APP
+[FIRInstanceIDKeyPair generateRSA2048KeyPairWithPrivateTag:publicTag:error:] + 562
16
MY-APP
-[FIRInstanceIDKeyPairStore generateAndSaveKeyWithSubtype:creationTime:error:] + 138
17
MY-APP
-[FIRInstanceIDKeyPairStore loadKeyPairWithError:] + 664
18
MY-APP
-[FIRInstanceIDKeyPairStore appIdentityWithError:] + 24
19
MY-APP
-[FIRInstanceID(Private) appInstanceID:] + 50
20
MY-APP
-[APMIdentity firebaseInstanceID] + 112
21
MY-APP
-[APMMeasurement createRawEventMetadataWithUserAttributes:] + 562
22
MY-APP
__42-[APMMeasurement writeEventOnWorkerQueue:]_block_invoke.1144 + 584
23
MY-APP
-[APMSqliteStore performTransaction:] + 146
24
MY-APP
-[APMMeasurement writeEventOnWorkerQueue:] + 1464
25
MY-APP
-[APMMeasurement handleEventOnWorkerQueue:] + 1356
26
MY-APP
__51-[APMScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke + 92
27
libdispatch.dylib
_dispatch_call_block_and_release + 10
28
libdispatch.dylib
_dispatch_queue_serial_drain + 854
29
libdispatch.dylib
_dispatch_queue_invoke + 886
30
libdispatch.dylib
_dispatch_root_queue_drain + 326
31
libdispatch.dylib
_dispatch_worker_thread3 + 106
32
libsystem_pthread.dylib
_pthread_wqthread + 1040
33
libsystem_pthread.dylib
start_wqthread + 8
```

**Comment by paulb777** [comment]
@shachar-silbert Did you, by chance, transpose the line number in your bug report?  Is this the same crash as #2485?

**Comment by shachar-silbert** [comment]
@paulb777 I did not, and I looked in the bug you sent, it seems quite different, with different classes on the way, and different final crash reasons.

**Comment by paulb777** [comment]
@shachar-silbert Looking more closely at the second thread, I see 'FIRInstanceID' and 'APMSqliteStore', both of which fixes for rare, sporadic crashes in recent release. Would you try Firebase 5.19.0 to see if the issue still occurs and send us updated traces?

**Comment by shachar-silbert** [comment]
Sure, will update if happens in further versions

**Comment by paulb777** [comment]
Closing for now. Will reopen on new data.

**Comment by neemssoni** [comment]
@shachar-silbert, I am also facing the same issue, did you find the solution for this?

**Comment by shachar-silbert** [comment]
@neemssoni I updated the version of the FIR and had no crashes since, yet...
