### ISSUE TITLE
FireBase Phone Number Auth on iOS-11.+

### ISSUE THREAD

**Issue by RajaReddyiOS** [firebase/firebase-ios-sdk#2375]
Getting 403 error (Permission_Denied)

{"error":{"code":403,"message":"Requests from this ios client application <empty> are blocked.","errors":[{"message":"Requests from this ios client application <empty> are blocked.","domain":"global","reason":"forbidden"}],"status":"PERMISSION_DENIED"}}

Not sure when i was checking on ios 12 its working fine and when i try same in ios 11. Am getting 403 error code.

**Comment by ryanwilson** [comment]
@RajaReddyiOS can you please list what SDK version you're using? It'll help us track down any changes that may have been made.

**Comment by paulb777** [comment]
Closing for now. Will reopen with more information.
