### ISSUE TITLE
Custom UI using FirebaseInAppMessagingDisplay crashes app at FirebaseApp.configure()

### ISSUE THREAD

**Issue by animeshp** [firebase/firebase-ios-sdk#2386]
* Xcode version: __10.1 (10B61)__
  * Firebase SDK version: __5.16.0__
  * Firebase Component: __In-App Messaging__
  * Component version: __0.12.0__

App crashes as soon as it starts with the following exception:

__Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[FIRAnalyticsConnector unregisterAnalyticsListenerWithOrigin:]: unrecognized selector sent to instance 0x281a8f100'__
#### Steps to reproduce:

I'm using local pod 'FirebaseInAppMessagingDisplay' for showing my custom UI for in-app message by following instruction listed here:
https://firebase.google.com/docs/in-app-messaging/customize-messages

This is the relevant pod entry:

```
pod 'Firebase/Core', '5.16.0'
    pod 'Firebase/RemoteConfig'
    pod 'FirebaseInAppMessagingDisplay', :path => '/Users/monty/Documents/GitHub/firebase-ios-sdk'
    pod 'FirebaseInAppMessaging', :path => '/Users/name/Documents/GitHub/firebase-ios-sdk'
    pod 'FirebaseAnalyticsInterop', :path => '/Users/name/Documents/GitHub/firebase-ios-sdk'
```

**Comment by ryanwilson** [comment]
Hey @animeshp - thanks for the report. We recently updated the `FIRAnalyticsConnector` code to use a new method introduced in `FirebaseAnalyticsInterop` but the `FirebaseAnalytics` SDK that implements the method hasn't been released yet. 

We have a version that works staged right now on https://github.com/Firebase/SpecsStaging which you can use for testing, but should *not* use this for your product. A public and more well tested version should be ready in our next release.

**Comment by animeshp** [comment]
Thanks @ryanwilson for replying.

So I wanted to use `FirebaseInAppMessagingDisplay` for implementing my custom UI as per instructions provided [here](https://firebase.google.com/docs/in-app-messaging/customize-messages). But following instructions leads to local pod not being able to find `FIRInAppMessagingRendering.h`, so I had to include `pod 'FirebaseInAppMessaging'`.

This further leads to including `pod 'FirebaseAnalyticsInterop'` pointing to local path because one of the other files is also not found.

So may be I'm missing something here or the instructions are incomplete for implementing custom UI.

After doing all of the above I got the above crash.

**Comment by ryanwilson** [comment]
Ahh, I was not aware of our instructions to do so. Apologies! One thing you can do in the meantime is instead of relying on master, use the latest release. If you checkout the `5.16.0` branch that should get you back up and running.

**Comment by ryanwilson** [comment]
cc: @christibbs @paulb777 - looks like we need to be more careful about temporarily breaking master.

**Comment by animeshp** [comment]
Thanks @ryanwilson for suggesting to use `5.16.0` branch. I got my implementation for custom UI working in test build.

Do you have any idea if `5.16.0` branch is safe to use in production? Or any timeline to get everything working in master?

**Comment by paulb777** [comment]
The `5.16.0` branch matches the current published release and is safe to use for production. 

The docs should be updated to give instructions to point at the last release branch. The master branch is not recommended for production.

**Comment by christibbs** [comment]
I sent our technical writer a note to update this, will close when the docs are updated.

**Comment by paulb777** [comment]
@christibbs Please add an internal bug number so that other Googlers can track.

**Comment by christibbs** [comment]
Internal bug number is 128939308.

**Comment by christibbs** [comment]
Documentation has been updated.
