### ISSUE TITLE
FirebaseApp.configure() -> [FIRDynamicLinks checkForPendingDynamicLink] memory leak

### ISSUE THREAD

**Issue by nitinalabur** [firebase/firebase-ios-sdk#2387]
### [READ] Step 1: Are you in the right place?
 Yes

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: Version 10.1 (10B61)
  * Firebase SDK version: 5.16.0
  * Firebase Component: Firebase/DynamicLinks
  * Component version: FirebaseDynamicLinks(3.4.0)
  * Swift version: 4.2

#### Steps to reproduce:
following is in my pod file of a new project
```
  pod 'Firebase/Core'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig' 
```

When FirebaseApp.configure() is called from didFinishLaunching() in the AppDelegate, there are 4 memory leaks reported (using Leaks tool in Instruments)

#### Relevant Code:

Add the pods listed above

and Appdelegate
```
import UIKit
import Firebase

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?


    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        FirebaseApp.configure()
        return true
    }
  }
}
```

Build for profiling.

Use the Leaks instrument to record the run. 

You'll see the leak reported as soon the app is done launching

<img width="1267" alt="screen shot 2019-02-12 at 5 13 16 pm" src="https://user-images.githubusercontent.com/1986214/52730209-d9f0b780-2f88-11e9-8c70-5ad56bc69d7b.png">

This looks very similar to #1636 and #1892 but is probably related to DynamicLinks

**Comment by dmandar** [comment]
Thanks for the feedback. Looks like the issue has been around for a while. We have an internal bug tracking this and will update here once addressed.

**Comment by paulb777** [comment]
@dmandar Please add the internal bug number reference so other Googlers can track and keep open here until it is fixed.

**Comment by dmandar** [comment]
123259278

**Comment by maksymmalyhin** [comment]
We've looked into the issue and found the reason. 

Firebase/DynamicLinks uses `WKWebView` under the hood. `WKWebView` is the reason of the leak. There is a related reported issue: [radar://45854674](http://www.openradar.me/45854674) `WKWebViewConfiguration` is the actually leaking class (an instance of `WKWebViewConfiguration` is required to initialize a `WKWebView`)

The leak can be easily reproduced:

```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        WKWebViewConfiguration()
        return true
    }
```

We will evaluate the impact of the leak and ways to fix it.

**Comment by ahmedAlmasri** [comment]
+1

**Comment by morganchen12** [comment]
Looks like the only way to fix this is to not use WKWebView.
