### ISSUE TITLE
Dynamic links: application(_:continue:restorationHandler:) as suggested in doc never called

### ISSUE THREAD

**Issue by vitalii-tym** [firebase/firebase-ios-sdk#2390]
* Xcode version: 10.1
  * Firebase SDK version: 5.16.0
  * Firebase Component: DynamicLinks
  * Component version: 3.4.0

This call never called:
```
func application(_ application: UIApplication, continue userActivity: NSUserActivity,
                 restorationHandler: @escaping ([Any]?) -> Void) -> Bool {
  let handled = DynamicLinks.dynamicLinks().handleUniversalLink(userActivity.webpageURL!) { (dynamiclink, error) in
    // ...
  }

  return handled
}
```

#### Steps to reproduce:

Set up dynamic links according to the documentation by copy-pasting the suggested code snippets. https://firebase.google.com/docs/dynamic-links/ios/receive
Result: the links are not handled by the application. The Xcode gives "nearly matches" warning and suggests a fix, which doesn't help when applied.

**Comment by vitalii-tym** [comment]
Answering my own problem: the call has changed and the new one looks a bit different now.

It was (and still suggested by current doc at https://firebase.google.com/docs/dynamic-links/ios/receive):

```
func application(_ application: UIApplication, 
                               continue userActivity: NSUserActivity,
                               restorationHandler: @escaping ([Any]?) -> Void) -> Bool

```
And the correct one is:

```
func application(_ application: UIApplication, 
                               continue userActivity: NSUserActivity, 
                               restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool
```

I personally had the older one in my legacy code and dynamic links simply have stopped working at some point.

This might not be an issue for anyone who adds the method by typing it and accepting Xcode's auto-fill, however this might be a big issue for anyone who attempts to copy-paste suggested snippets, because following Xcode's suggestion in the warning won't help at all:

<img width="1292" alt="screenshot 2019-02-14 15 14 57" src="https://user-images.githubusercontent.com/5410835/52789043-7be8d080-306b-11e9-9432-9e8315e9e857.png">

It would be good to update this piece of code in the doc and prevent many people from spending hours of debugging.

**Comment by morganchen12** [comment]
This was fixed in March. Thanks for reporting!

**Comment by Milap-Kundalia** [comment]
I am facing the same issue
I have written the new method in app delegate but still, it's not getting called when the dynamic link is clicked.

```
func application(_ application: UIApplication, 
                               continue userActivity: NSUserActivity, 
                               restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool

```

I am testing in iOS 13 


let me know if anyone is having any solution for this.
