### ISSUE TITLE
shouldEstablishDirectChannel issue

### ISSUE THREAD

**Issue by eitanaviv** [firebase/firebase-ios-sdk#2403]
* Xcode version: 10.1
  * Firebase SDK version: 5.16.0 (latest)
  * Firebase Component: Messaging
  * Component version: 3.3.0

#### Steps to reproduce:

I'm building an app for displaying the user real time data updates using firebase messaging notifications. I've implemented all of the required code from the quick start and set `Messaging.messaging().shouldEstablishDirectChannel = true`.

Everything works fine, but my issue is the queuing feature the comes with the direct channel enabled.
Is there any way to disable this specific feature? My use case is notifying the user without asking for notifications permission as i don't show the user any notification once received - just UI updates in foreground mode only.

#### Relevant Code:

```
class AppDelegate: UIResponder, UIApplicationDelegate {
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        FirebaseApp.configure()
        
        Messaging.messaging().delegate = self
        Messaging.messaging().shouldEstablishDirectChannel = true
        
        return true
    }
}

extension AppDelegate: MessagingDelegate {
    func messaging(_ messaging: Messaging, didReceive remoteMessage: MessagingRemoteMessage) {
        print("Push received")
        print("Push data: \(remoteMessage.appData["title_data"] ?? "")")
    }
    
    func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String) {
        print("Firebase registration token: \(fcmToken)")
    }
}
```

#### JSON data sent:
```
{
  "to": "/topics/test",
  "data": {
    "title_data": "This is a Firebase Cloud Messaging Topic Message!"
  }
}
```

**Comment by morganchen12** [comment]
@eitanaviv what queueing feature are you referring to specifically?

**Comment by eitanaviv** [comment]
@morganchen12 I would like to use the `Direct FCM channel messages` to `reliably receive silent, data-only messages directly from FCM, bypassing APNs when the app is in the foreground` (as the docs says), but i'm also getting this queuing feature as described in the docs `With the direct channel enabled, the FCM backend uses a reliable message queue to keep track of pending messages when the app is in the background or closed`.
This queuing feature i would like to disable, for just getting the data payload from the notification when in foreground mode only.

**Comment by morganchen12** [comment]
There's no way to disable that feature unfortunately. Have you considered using Firestore and observing a document? That way you could change the document every time you wanted to show a new message and then in the client display the contents of the document. Whenever you wanted to not listen to updates, you could just detach the listener.

Alternatively, you can implement a timeout on your client for the messages you're receiving from FCM so stale messages could just be ignored.

**Comment by eitanaviv** [comment]
@morganchen12 I don't want to use firestore/real-time database so it won't cost me.

> Alternatively, you can implement a timeout on your client for the messages you're receiving from FCM so stale messages could just be ignored.

How can i reach that?

**Comment by morganchen12** [comment]
You can add a timestamp as a parameter to all your FCM sends, and then on the client just compute the time that's elapsed since each send and ignore messages that are too old.

Closing this for now since this isn't a feature we plan on adding, but feel free to continue discussion on this issue.
