### ISSUE TITLE
Disable sending idfa to Firebase

### ISSUE THREAD

**Issue by Anhelme** [firebase/firebase-ios-sdk#2408]
Hello, how we can disable sending idfa in iOS Firebase SDK?
We found that we can disable it for Android, but there is no such information about iOS: https://firebase.google.com/support/guides/disable-analytics

**Comment by allenktv** [comment]
Hi Anhelme,

Firebase Analytics by default does not send the IDFA and it only sends it if you have the AdSupport framework linked. If you have AdSupport previously linked, you will need to unlink it and have your users update their apps. 

For more information, please take a look at: https://firebase.google.com/support/guides/analytics-adsupport

**Comment by allenktv** [comment]
Test comment, please ignore
