### ISSUE TITLE
Linker errors  - Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by chanuuuu** [firebase/firebase-ios-sdk#2418]
### My environment
* Xcode version: 10.1
* Firebase Component: Analytics

### The problem

I am having linker issues while integrating Firebase using Carthage. I have included FirebaseAnalyticsBinary in my Cart file and linked following frameworks from Carthage/Build/iOS into the target:

<img width="990" alt="screen shot 2019-02-21 at 2 54 16 pm" src="https://user-images.githubusercontent.com/6045047/53208018-39367380-35ea-11e9-8fe4-791f08324ea9.png">

I have added libc++.tbd, sqlite3.tbd, StoreKit.framework libraries as well based on the documentation.

My linker issues are as following:

<img width="1091" alt="screen shot 2019-02-21 at 2 52 17 pm" src="https://user-images.githubusercontent.com/6045047/53208127-8e728500-35ea-11e9-8292-0abd2dd36f92.png">
 
Please let me know what I am missing?

**Comment by chanuuuu** [comment]
@paulb777 any suggestions on how to fix this?

**Comment by paulb777** [comment]
Looks like nanopb.framework is missing.

**Comment by chanuuuu** [comment]
Thanks. That resolved my issue.
