### ISSUE TITLE
Connecting Firebase SDK to Xcode (tvOS) project

### ISSUE THREAD

**Issue by MattThomas1989** [firebase/firebase-ios-sdk#2432]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.1
  * Firebase SDK version: _____
  * Firebase Component: Core (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: _____

### [REQUIRED] Step 3: Describe the problem

I am trying to connect my tvOS project to my Firebase database.

I have downloaded the tvOS open source CocoPods for "FirebaseCore, FirebaseDatabase" however when setting up the SDK in the firebase console I am unable to connect between my FirebaseApp and Xcode project.

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem

AppDelegate.swift

import UIKit
import CoreData
import FirebaseCore

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?


    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        FirebaseApp.configure()
        return true
    }





```

**Comment by paulb777** [comment]
Make sure that `-ObjC` is included in the `Other Linker Flags` in Build Settings
