### ISSUE TITLE
EXC_Bad_Access on GULMutableDictionnary (Google Utilities)

### ISSUE THREAD

**Issue by fschaus** [firebase/firebase-ios-sdk#2439]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: XCode 10.1
  * Firebase SDK version: 5.15.0
  * Firebase Component: Auth, Core, Database, Firestore, Messaging, Storage, Performance
  * Component version: 5.15.0

### [REQUIRED] Step 3: Describe the problem

When running our app in debug mode on the Simulator (tested iPhone 8), the app crashes right away due to an Exc_Bad_Access error. Based on the XCode log report the issue seems to be here in Google Utilities/ Network/ GULMutableDictionnary:

`- (void)removeObjectForKey:(id)key {
  dispatch_async(_queue, ^{
    [self->_objects removeObjectForKey:key];
  });
}`

I noticed a memory corruption bug in our app in production that highlighted a pointer being freed that was not allocated. Given that the above happens at launch, it could very well be the same issue (i.e., object not initiated but being deallocated).

#### Steps to reproduce:

Running firebase SKD v5.15.0 and launching an app on iPhone 8 simulator. Given the memory corruption issue noticed in production, I turned on the Zombie Object debugging in my debug scheme, which is the one I run. When I turn Zombie Object debugging off in my scheme, the app runs fine (but I suspect the memory corruption still happens, just undetected).

Problem only occurs when running on the Xcode simulator (tried using iPhone 8 simulator), NOT on the physical device. Only tested in debug mode.

#### Relevant Code:

Not particular code to reproduce the problem. The EXC_bad_Access is being triggered in the GoogleUtilities pod and highlight the following code (line 61): 
`- (void)removeObjectForKey:(id)key {
  dispatch_async(_queue, ^{
    [self->_objects removeObjectForKey:key]; <== Line highlighted
  });
}`

Thanks for the help!

**Comment by ryanwilson** [comment]
Thanks for the report @fschaus - can you please share a Podfile or list of frameworks you're including with the project that causes this to happen?

A stack trace would be extremely helpful as well, giving us the full stack to see where the call to `removeObjectForKey:` originated from.

If you update to the latest Firebase (`5.17.0` as of this writing) does it happen still?

**Comment by morganchen12** [comment]
This is the same as the new crash reported in the comments in https://github.com/firebase/firebase-ios-sdk/issues/1624.

**Comment by paulb777** [comment]
Closing for staleness. Please open a new issue if this reoccurs in a recent release.
