### ISSUE TITLE
handleUniversalLink returns nil for dynamicLink.url when the dynamicLink has space in iOS

### ISSUE THREAD

**Issue by Animaxx** [firebase/firebase-ios-sdk#2447]
FirebaseDynamicLinks version: 3.4.0
Xcode: 10.1
Firebase Component: Core, DynamicLinks, Messaging

1.  generate the dynamic link includes space, here is the short link example:
    [https://c9kk4.app.goo.gl/p97R](https://c9kk4.app.goo.gl/p97R?d=1)
    Here is the whole link same as the short link:
    https://c9kk4.app.goo.gl/?link=https://videochat.cccis.com/?pin%3D378259%26session%3Dd2d27f5bfad1bbd08676b0983fc1d8fa49480145%26claimId%3Dvideochat%26lastName%3DMax%26agent%3Dmyagent+displayname%26company%3Dcompany&apn=com.cccis.quickest.video&isi=1294350093&ibi=com.cccis.quickest.video

    Since the link part is URL encode from Java, the "myagent displayname" convert to "myagent+displayname"

2. when the app open the URL, handleUniversalLink function get called, **FIRNetworkRequestCompletionHandler** response return "agent=myagent displayname"
    https://github.com/firebase/firebase-ios-sdk/blob/7cc0a9bc9881c858fdfc5cc06bcb008f4b193b2f/Firebase/DynamicLinks/FIRDynamicLinkNetworking.m#L120

    Here is response JSON:
> {
>   "deepLink": "https://videochat.cccis.com/?pin=378259&session=d2d27f5bfad1bbd08676b0983fc1d8fa49480145&claimId=videochat&lastName=Max&agent=myagent displayname&company=company",
>   "resolvedLink": "https://c9kk4.app.goo.gl/?link=https://videochat.cccis.com/?pin%3D378259%26session%3Dd2d27f5bfad1bbd08676b0983fc1d8fa49480145%26claimId%3Dvideochat%26lastName%3DMax%26agent%3Dmyagent+displayname%26company%3Dcompany&apn=com.cccis.quickest.video&isi=1294350093&ibi=com.cccis.quickest.video"
> }

3. When Firebase try to create the NSURL from the link with space, it fail and return nil:
    https://github.com/firebase/firebase-ios-sdk/blob/7cc0a9bc9881c858fdfc5cc06bcb008f4b193b2f/Firebase/DynamicLinks/FIRDynamicLink.m#L36

As result, handleUniversalLink function returns nil for dynamicLink.url.

------------------------------------------

I notice the older version is working fine, because the response includes "+" instead of covert to space.

Here is the request body from version (3.2.0) 
> {link: "https://xxxx"}

In the latest version(3.4.0), request body like this:
> {
>     "bundle_id" = "bundle id";
>     requestedLink = "link";
>     "sdk_version" = "3.4.0";
> }

the response for the old version is:
> {
>   "deepLink": "xxxx&agent=**myagent+displayname**&xxxx",
>   "durableLinkAnalyticsData": {
>     "source": "firebase",
>     "medium": "dynamic_link",
>     "campaign": "",
>     "linkId": "temp_link_id",
>     "appCode": "c9kk4",
>     "requestedLink": {
>           "type": "DDL_LONG","value": "[original link]"
>     },
>     "domainUriPrefix": "https://c9kk4.app.goo.gl"
>   }
> }

and the response for the new version is:
> {
>   "deepLink": "xxxxx&agent=**myagent displayname**&xxxxx",
>   "resolvedLink": "[original link]"
> }

**Comment by dmandar** [comment]
Thanks for reporting . Internal bug 137687937 tracking this.

**Comment by morganchen12** [comment]
This bug should be fixed now (was a backend fix, so no SDK update). Please comment here if it's still reproducible.
