### ISSUE TITLE
Error installing BoringSSL-GRPC

### ISSUE THREAD

**Issue by jyounus** [firebase/firebase-ios-sdk#2448]
* Xcode version: 10.1
  * Firebase SDK version: Tag 5.17.0
  * Firebase Component: Firestore

I'm trying to add FirebaseFirestoreSwift to my project and I get the following error:
```
Installing BoringSSL-GRPC (0.0.2)

[!] Error installing BoringSSL-GRPC
[!] /usr/bin/git clone https://github.com/google/boringssl.git /var/folders/k3/8phztphs11d0hbtshqcxx9hr0000gn/T/d20190226-73853-1azgtd4 --template=

Cloning into '/var/folders/k3/8phztphs11d0hbtshqcxx9hr0000gn/T/d20190226-73853-1azgtd4'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

The same happens if I go for the FirebaseFirestore pod. Anyone got any ideas? 

EDIT
I should mention that this is the first time I'm trying to add this pod to my project. I've added Auth, Core, Database, Messaging and Analytics in the past into this project without issues. It's only when I try adding the Firestore pod.

```
pod 'FirebaseAnalytics', '5.6.0'
pod 'FirebaseAuth', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :tag => '5.17.0'
pod 'FirebaseCore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :tag => '5.17.0'
pod 'FirebaseDatabase', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :tag => '5.17.0'
pod 'FirebaseMessaging', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :tag => '5.17.0'
pod 'FirebaseFirestoreSwift', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :tag => '5.17.0'
```

**Comment by wilhuff** [comment]
`FirebaseFirestoreSwift` has nothing public within it yet and hasn't been released. We're not supporting it (yet).

With that said, it should still be possible to use FirebaseFirestore. Our [recommended instructions](https://firebase.google.com/docs/firestore/quickstart) are to use these pods:

pod 'Firebase/Core'
pod 'Firebase/Firestore'

It's likely that you're just seeing a really, really old dependency on Firestore this way. Within your current set up try changing `'FirebaseFirestoreSwift'` to `'FirebaseFirestore'`.
