### ISSUE TITLE
FR: analytics to accept param type of array of strings

### ISSUE THREAD

**Issue by julio-rivera** [firebase/firebase-ios-sdk#2451]
It would be great if the Analytics SDK supported sending an array of strings as a parameter in the method `logEvent`. If I send  { teachers :["Teacher Name 1", "Teacher Name 2"] }, I see an error in the console log "Invalid extra param structure. Must be a dictionary. Parameters: Teacher Name 1, Teacher Name 2" and the parameter is not logged in the DebugView.

  * Firebase SDK version: 5.5.0

**Comment by allenktv** [comment]
Unfortunately we do not support this currently. It may not be exactly what you want, but as an alternative I would suggest turning the array into a comma separated string and logging that as the parameter.

**Comment by paulb777** [comment]
Going to close since there is an alternative and no plans to add the feature.
