### ISSUE TITLE
Remove deprecated API in Firebase Auth.

### ISSUE THREAD

**Issue by Yue-Wang-Google** [firebase/firebase-ios-sdk#2481]
we should remove deprecated APIs such as 

- FIRAuthUpdatedCredentialKey and FIRAuthErrorNameKey in FIRAuthErrors.h 
- FIREmailPasswordAuthProviderID and FIREmailPasswordAuthProvider in FIREmailAuthProvider.h

in the next major release.

**Comment by ryanwilson** [comment]
@Yue-Wang-Google please make sure this is completed by EOD Tuesday (before we cut the release branch).

**Comment by Yue-Wang-Google** [comment]
#2723 already removed all of those in public interface. I'm going to send another PR to clean up tests and implementation which has those fields.

**Comment by Yue-Wang-Google** [comment]
#2759 submitted.

closing this bug

**Comment by ryanwilson** [comment]
Thank you!
