### ISSUE TITLE
Crash in FIDRenderingWindowHelper.m - Line 27 unrecognized selector sent to instance

### ISSUE THREAD

**Issue by gogoout** [firebase/firebase-ios-sdk#2498]
* Xcode version: 10.1
  * Firebase SDK version: 5.18.0
  * Firebase Component: In-App Messaging
  * Component version: 0.13.0

### [REQUIRED] Step 3: Describe the problem
When implemented UIApplicationDelegate, `window` is optional, thus may crash when in-app messaging trying to show a message. 

#### Steps to reproduce:
Just open the app will crash

#### Relevant Code:
from https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/InAppMessagingDisplay/FIDRenderingWindowHelper.m

```obj-c
 UIWindow *appWindow = [[[UIApplication sharedApplication] delegate] window];
```

**Comment by christibbs** [comment]
@gogoout could you clarify what you mean by "When implemented UIApplicationDelegate"? I tried running this on a sample app and didn't get a crash.

**Comment by gogoout** [comment]
> @gogoout could you clarify what you mean by "When implemented UIApplicationDelegate"? I tried running this on a trivial sample app and didn't get a crash.

Hi, thanks for the quick responding. Actually I'm running a Nativescript project so I barely knows about obj-c so allow me to just quote from others. 

The most similar bug that I found is this one https://github.com/NativeScript/ios-runtime/issues/430#issuecomment-162327186

>  It seems that -[ZDKCreateRequestViewController shouldEnableAttachments] calls [UIApplication sharedApplication].delegate.window. The default UIApplicationDelegate that ships with NativeScript does not implement the window property because it is required for storyboards and NativeScript does not use storyboards at this time.
>
> This is a bug in the Zendesk SDK - it is entirely possible that the application delegate does not implement the window property, or that there isn't an application delegate in the first place. The Zendesk SDK fails to account for these scenarios and tries to access the key window using the application delegate, instead of the +[UIWindow keyWindow] accessor which is far more appropriate.

So long story short, when In-app Messenging trying to call  [UIApplication sharedApplication].delegate.window, it's not there.


Another similar example I found is this https://github.com/cezarywojcik/CWStatusBarNotification/issues/62

**Comment by christibbs** [comment]
@gogoout crash should be resolved in the next release (mid to late next week).
