### ISSUE TITLE
FirebaseInvitesBinary version 5.8.0 missing

### ISSUE THREAD

**Issue by bratxdy** [firebase/firebase-ios-sdk#2503]
* Xcode version: 10.1
  * Firebase SDK version: 5.8.0
  * Firebase Component: Invites
  * Component version: 5.8.0

#### Steps to reproduce:

We have been using FirebaseInvitesBinary version 5.8.0 through Carthage for a couple months now. As of yesterday it seems that that version, as well as every other version other than 5.18.1, has disappeared. If you take a look at https://dl.google.com/dl/firebase/ios/carthage/FirebaseInvitesBinary.json you can see that there is only one version listed.

Here is the Carthage error: 
```No available version for binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseInvitesBinary.json" satisfies the requirement: == 5.8.0```

**Comment by paulb777** [comment]
The json files were temporarily corrupted yesterday, but have now been restored.  You may need to clear your Carthage cache.

**Comment by bratxdy** [comment]
Thanks @paulb777, it is fixed now!
