### ISSUE TITLE
Use @YES and @NO instead of @true and @false

### ISSUE THREAD

**Issue by chingjun** [firebase/firebase-ios-sdk#252]
in FRepo.m line 516 and 520, we should use `@YES` and `@NO` instead of `@true` and `@false` to create the boolean values. `@YES` and `@NO` are always mapped to `kCFBooleanTrue` and `kCFBooleanFalse`, so we can use it to determine if the value is a BOOL or an int. `@true`, however, will be treated as an integer.

Changes here: https://github.com/chingjun/firebase-ios-sdk/commit/a07b9237de9311ef54e9d1edff5145550f8b3d18

**Comment by schmidt-sebastian** [comment]
This looks like the proper solution, but it modifies the existing behavior of the SDK in a way that constitutes a breaking change (by changing the type of the value we pass to the user-visible .info/connected callback). 
We generally only make breaking changes during major releases and hence this PR will likely have to wait until such a release is scheduled.

**Comment by paulb777** [comment]
Closed by #1049
