### ISSUE TITLE
FirebaseFirestore - Value Conversion Issue - Implicit conversion loses integer precision

### ISSUE THREAD

**Issue by willbattel** [firebase/firebase-ios-sdk#2525]
### Environment

  * Xcode version: 10.1 (10B61)
  * Firebase SDK version: 5.17.0
  * Firebase Component: Firestore (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 1.0.1

### Describe the problem

I've been seeing this warning for the past few versions of the SDK (starting around 5.15 or so). I've ignored it but am curious if the Firebase team is aware of it.

`Pods/FirebaseFirestore/Firestore/Source/Local/FSTLevelDB.mm:375:10: Implicit conversion loses integer precision: 'int64_t' (aka 'long long') to 'size_t' (aka 'unsigned long')`

<img width="269" alt="Screen Shot 2019-03-12 at 1 38 03 PM" src="https://user-images.githubusercontent.com/13490339/54226558-19e58480-44cc-11e9-880b-bb12cf5edd23.png">

#### Steps to reproduce:

Install Firestore via Cocoapods, build project.

#### Relevant Code:
N/A

**Comment by wilhuff** [comment]
Are you building for a 32-bit target by chance?

**Comment by willbattel** [comment]
I only see it when **Building** without a device, i.e., Command+B without a device connected. As you suggest, it does disappear when **Building and Running** (Command+R) on iOS 11/12 devices (all of which are 64 bit)
