### ISSUE TITLE
'GULLoggerLevel.h' file not found

### ISSUE THREAD

**Issue by AndrewBarba** [firebase/firebase-ios-sdk#2555]
Yesterdays GoogleUtilities 5.4.0 release broke a handful of file dependencies, ex: https://github.com/firebase/firebase-ios-sdk/issues/2551

I upgraded to 5.4.1 this morning and am still seeing a similar issue with `GULLoggerLevel.h`.

The issue is fixed by downgrading to 5.3.7:

`pod 'GoogleUtilities', '~> 5.3.7'`

**Comment by paulb777** [comment]
@AndrewBarba Thanks for the report and sorry about the breakage. So far I'm not able to reproduce.  It looks like only comments have changed in `GULLoggerLevel.h` - ` git diff feadeec161b15ee8b17c6d22ce471e7282a18403 --  ./GoogleUtilities/Logger/Public/GULLoggerLevel.h`

Can you share more about reproducing?  What version of CocoaPods and Xcode? Is `use_frameworks!` in the Podfile? Does Xcode clean help? Or `rm -rf ~/Library/Developer/Xcode/DerivedData`?

**Comment by AndrewBarba** [comment]
I'm using CocoaPods 1.7.0-beta.2 (I know it's a beta, but was working fine before yesterday). 

I tried cleaning the build, removing derived data, and `pod deintegrate; pod install`

Here's the Podfile:

```ruby
source "https://cdn.jsdelivr.net/cocoa/"
source "https://github.com/brightcove/BrightcoveSpecs.git"

install! "cocoapods",
  :disable_input_output_paths => true,
  :generate_multiple_pod_projects => true,
  :incremental_installation => true

inhibit_all_warnings!

project "App.xcodeproj"
workspace "App.xcworkspace"

target "App" do
    platform :ios, "10.0"
    use_frameworks!

    pod "Firebase/Core", "~> 5.0"
end
```

**Comment by paulb777** [comment]
Hmm, are you seeing the error in the Xcode before or after building?  If before, the ModuleCache may need to be rebuilt.

**Comment by AndrewBarba** [comment]
The build fails with the error `'GULLoggerLevel.h' file not found`. How would I clear the module cache? I feel like any of the steps I tried previously would have done that

**Comment by paulb777** [comment]
Yep deleting DerivedData will erase the ModuleCache.

Can you share the full error from the Build Failure in the Xcode Report Navigator?

**Comment by AndrewBarba** [comment]
<img width="1026" alt="Screen Shot 2019-03-14 at 12 47 09 PM" src="https://user-images.githubusercontent.com/1316152/54375380-4e397c00-4657-11e9-8e6d-296684a02fcc.png">

**Comment by paulb777** [comment]
Thanks. I'm still not able to reproduce, but the directory structure organization in GoogleUtilities is questionable and may be the root cause.  

Given this and the other issue, we're going to rollback the os_log changes in GoogleUtilities and implement it sometime more incrementally sometime in the future.

We plan to publish GoogleUtilities 5.5.0 that exactly matches 5.3.7 and hope to get that out later today. Follow #2556 for progress.

**Comment by paulb777** [comment]
The rollback to 5.3.7 (== 5.5.0) is live
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  GoogleUtilities (5.5.0) successfully published
 📅  March 14th, 15:10
 🌎  https://cocoapods.org/pods/GoogleUtilities
 👍  Tell your friends!
--------------------------------------------------------------------------------

**Comment by AndrewBarba** [comment]
@paulb777 My guess is this I related to the new option in CocoaPods 1.7:

`:generate_multiple_pod_projects => true`

They have a warning about it:

> **Warning:** Switching your project to use multiple .xcodeproj may result in some compiler errors if your pods have relied on importing headers using the quote syntax for its dependencies. For example `#import "PDDebugger.h"` will no longer work in a pod that depends on PonyDebugger. Instead, we highly suggest you update your headers to correctly import the framework and its associated header: `#import <PonyDebugger/PDDebugger.h>`. This is intentional since this feature is currently opt-in.

http://blog.cocoapods.org/CocoaPods-1.7.0-beta/

**Comment by paulb777** [comment]
That sounds highly likely. Thanks @AndrewBarba!

**Comment by o15a3d4l11s2** [comment]
I can give some additional information regarding missing files.

As @AndrewBarba describes I can confirm this is related to the new multiple pod projects setting.

I see that there are commits from few hours ago that already take care of imports of files like `FIRLoggerLevel.h` with the appropriate project, i.e. `FirebaseCore` or `FirebaseInstanceId`, so I am anxious to see it live soon and use the new features of Cocoapods 1.7.0.

**Comment by alfredcc** [comment]
same issues, now Cocoapods 1.7.0 is released, if some one use the feature `generate_multiple_pod_projects` this will error happen. @paulb777

**Comment by alfredcc** [comment]
checkout  [https://github.com/firebase/firebase-ios-sdk/pull/2751](url)
