### ISSUE TITLE
Auth does not restore the previous user when launching the app.

### ISSUE THREAD

**Issue by j-jorge** [firebase/firebase-ios-sdk#2586]
* Xcode version: 10.1
  * Firebase SDK version: 5.17.0
  * Firebase Component: Auth
  * Component version: 5.3.1

### Describe the problem

My app uses Firebase Auth to authenticate the user via Facebook, Google or Phone. The UI is provided by FirebaseUI and the authentication works flawlessly for these three providers. 

The problem is that the authenticated user is lost when I restart the app (i.e. `[ [ FIRAuth auth ] currentUser ]` is null, so is the value passed to the listener registered with `[ [ FIRAuth auth ] addAuthStateDidChangeListener`). However, this behavior occurs only on a real device. Everything works as expected in the simulator.

At first I thought it was [a consequence of a delay in the initialization of Firebase](https://stackoverflow.com/questions/55183311/will-firauth-addauthstatedidchangelistener-wait-until-the-end-of-the-initializat/55184833), in the sense that I would request the user too soon. Thus I have inserted a 5 seconds delay between the initialization of Firebase and the first time I request the user. The issue remained.

I also tried to blame a misconfiguration of the keychain access. I understood that it was required for Facebook, is it required for the others? In any case, the Keychain Access is enabled in Xcode as well as the push notifications. The notifications are also enabled in the provisioning profile and the entitlements file contains this (here with `{symbolic placeholders}`):

    <key>aps-environment</key>
    <string>development</string>

    <key>keychain-access-groups</key>
    <array>
      <string>$(AppIdentifierPrefix){PackageID}</string>
    </array>

One can see in the profile embedded in the ipa:

    <key>Entitlements</key>
        <dict>
                <key>keychain-access-groups</key>
                <array>
                        <string>{TeamID}.*</string>           
                </array>
                <key>get-task-allow</key>
                <true/>
                <key>application-identifier</key>
                <string>{TeamID.PackageID}</string>
                <key>com.apple.developer.team-identifier</key>
                <string>{TeamID}</string>
                <key>aps-environment</key>
                <string>development</string>
        </dict>

Everythings seems good to me and I am out of ideas. Is it a bug in Auth? How can I have the user restored when launching the app?

**Comment by j-jorge** [comment]
Not sure if it is relevant but there are two these two lines in the log (reformatted for GitHub):

```
default 17:38:49.244151 +0100   securityd   inserted
<
  genp,
  rowid=21661,
  cdat=2019-03-20 16:38:49 +0000,
  mdat=2019-03-20 16:38:49 +0000,
  desc=null,
  icmt=null,
  crtr=null,
  type=null,
  scrp=null,
  labl=null,
  alis=null,
  invi=null,
  nega=null,
  cusi=null,
  prot=null,
  acct=firebase_auth_1___FIRAPP_DEFAULT_firebase_user,
  svce=firebase_auth_1:423484051800:ios:840a79b51a1a577e,
  gena=null,
  data=132b:070000000A901B0A...|1d76e2e0679073e5,
  agrp={TeamID}.{PackageID},
  pdmn=cku,
  sync=0,
  tomb=0,
  sha1=46DB644197B4C2B5DC06B893F8E1348960DF8809,
  vwht=null,
  tkid=null,
  v_Data=<?>,
  v_pk=C00B534BC5EB095554CCE7B2486F70AD70DE11DA,
  accc=null,
  u_Tomb=null,
  musr=,
  UUID=59BE48D2-C72D-4FD2-9DAD-45A3638C152C,
  sysb=null,
  pcss=null,
  pcsk=null,
  pcsi=null,
  persistref=
>
```

and later

```
default 17:39:19.545497 +0100   securityd   deleted
<
  genp,
  rowid=21661,
  cdat=2019-03-20 16:38:49 +0000,
  mdat=2019-03-20 16:38:49 +0000,
  desc=null,
  icmt=null,
  crtr=null,
  type=null,
  scrp=null,
  labl=null,
  alis=null,
  invi=null,
  nega=null,
  cusi=null,
  prot=null,
  acct=firebase_auth_1___FIRAPP_DEFAULT_firebase_user,
  svce=firebase_auth_1:423484051800:ios:840a79b51a1a577e,
  gena=null,
  data=132b:070000000A901B0A...|1d76e2e0679073e5,
  agrp={TeamID}.{PackageID},
  pdmn=cku,
  sync=0,
  tomb=0,
  sha1=46DB644197B4C2B5DC06B893F8E1348960DF8809,
  vwht=null,
  tkid=null,
  v_Data=<?>,
  v_pk=C00B534BC5EB095554CCE7B2486F70AD70DE11DA,
  accc=310D300B0C0470726F740C03636B75,
  u_Tomb=null,
  musr=,
  UUID=59BE48D2-C72D-4FD2-9DAD-45A3638C152C,
  sysb=null,
  pcss=null,
  pcsk=null,
  pcsi=null,
  persistref=
> from <SecDbConnection rw open>
```

The first one seems to be related to the serialization of the user in the keychain and the second one seems to be the deletion of this user. Am I right? I don't know why the user would be deleted thought.

**Comment by j-jorge** [comment]
Apparently the user is reset when we call `[ [ FIRApp defaultApp ] deleteApp: [] ( BOOL ) -> void {} ];` on the application's termination. If we remove this line the user is effectively restored on the next launch.

Is this a bug or a feature? Calling `deleteApp` when the application is shutting down seems natural. Am I missing something?

**Comment by morganchen12** [comment]
This is working as intended. You don't have to delete the Firebase app when shutting down. Auth has no way of knowing whether or not you'll re-initialize an app after it's deleted.
