### ISSUE TITLE
Auth does not delete anonymous user 

### ISSUE THREAD

**Issue by rayyanfaris** [firebase/firebase-ios-sdk#2587]
* Xcode version: 10.1
  * Firebase SDK version: 5.18.0
  * Firebase Component: Auth
  * Component version: 5.4.0

### Describe the problem
Attempting to delete a signed in anonymous user returns a '17999' internal error.

#### Steps to reproduce:

1. Authenticate an anonyomous user 
2. Attempt to delete user using the delete() method

#### Relevant Code:
```swift

Auth.auth().currentUser == nil {
            signInAnonymously()
        }

if let user = Auth.auth().currentUser else {

     user.delete { (error) in
            if let error = error as? NSError{
              print("Error deleting user \(error.code) \(error.localizedDescription)")
            } else {
              print("User deleted")
            }
        }

}
```

**Comment by Yue-Wang-Google** [comment]
cannot reproduce. The following code works fine:

```
  [auth signInAnonymouslyWithCompletion:^(FIRAuthDataResult *_Nullable result,
                                                       NSError *_Nullable error) {
  }];
  FIRUser *user = [auth currentUser];
  [user deleteWithCompletion:^(NSError *_Nullable error) {
    if (error) {
      [self logFailure:@"delete account failed" error:error];
    }
  }];
```

**Comment by Yehudshe** [comment]
maybe as in my case the Anonymous sign-in enable in the console page(console-> Authentication -> sign-in methods) : 
https://console.firebase.google.com/project/fir-startproject/authentication/providers
was disabled 
change it to enable
