### ISSUE TITLE
LICENSE warning in FirebaseMessaging pod

### ISSUE THREAD

**Issue by tfonfara** [firebase/firebase-ios-sdk#2590]
### Describe your environment

  * Xcode version: 10.1 (10B61)
  * Firebase SDK version: 5.19.0
  * Firebase Component: Messaging
  * Component version: 3.4.0

### Describe the problem
Seems that LICENSE file isn't integrated properly

#### Steps to reproduce:
- Integrate Firebase Messaging via Cocoapods
- Receive warning: `[!] Unable to read the license file LICENSE for the spec FirebaseMessaging (3.4.0)`

**Comment by paulb777** [comment]
@tfonfara I'm not able to reproduce.   The pod was just published so I wonder if you have something out of sync in your configuration.

Would you try `pod cache clean FirebaseMessaging` and retry?

**Comment by tfonfara** [comment]
@paulb777 that fixed it! 👍
