### ISSUE TITLE
Firebase Performance SDK crashes on Simulator

### ISSUE THREAD

**Issue by avitruk** [firebase/firebase-ios-sdk#2593]
Xcode version: 10.1 / 10.2 Beta
Firebase SDK version: 5.19 / 5.18
Firebase Component: Performance
Component version: 5.19 / 5.18

When we adding "Firebase/Performance" component, the application crashes on the simulators, but works fine on the real devices.
Please check the screenshots: 
![first](https://image.prntscr.com/image/1edojkndTomnpTHDaGbhpA.png)
![second](https://image.prntscr.com/image/bcQ8gEZtQWeCYo4Gd4KAcA.png)

**Comment by visumickey** [comment]
@avitruk Do you have a sample app where I can try reproducing this? Would be curious to see your podfile.lock if this issue is happening in a specific combination of pods.

**Comment by morganchen12** [comment]
Closed due to inactivity.
