### ISSUE TITLE
Memory Leak on addSnapshotListener for Firestore

### ISSUE THREAD

**Issue by ugenlik** [firebase/firebase-ios-sdk#2607]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.1
  * Firebase SDK version: 
```
- Firebase/Auth (5.18.0):
    - Firebase/CoreOnly
    - FirebaseAuth (= 5.4.0)
  - Firebase/Core (5.18.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 5.7.0)
  - Firebase/CoreOnly (5.18.0):
    - FirebaseCore (= 5.3.1)
  - Firebase/Firestore (5.18.0):
    - Firebase/CoreOnly
    - FirebaseFirestore (= 1.0.2)
  - Firebase/Messaging (5.18.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (= 3.3.2)
  - Firebase/RemoteConfig (5.18.0):
    - Firebase/Core
    - FirebaseRemoteConfig (= 3.1.0)
  - Firebase/Storage (5.18.0):
    - Firebase/CoreOnly
    - FirebaseStorage (= 3.1.0)
  - FirebaseABTesting (2.0.0):
    - FirebaseCore (~> 5.0)
    - Protobuf (~> 3.5)
  - FirebaseAnalytics (5.7.0):
    - FirebaseCore (~> 5.3)
    - FirebaseInstanceID (~> 3.6)
    - GoogleAppMeasurement (= 5.7.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 5.2)
    - GoogleUtilities/MethodSwizzler (~> 5.2)
    - GoogleUtilities/Network (~> 5.2)
    - GoogleUtilities/NSData+zlib (~> 5.2)
    - nanopb (~> 0.3)
  - FirebaseAnalyticsInterop (1.2.0)
  - FirebaseAuth (5.4.0):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 5.2)
    - GoogleUtilities/Environment (~> 5.2)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseAuthInterop (1.0.0)
  - FirebaseCore (5.3.1):
    - GoogleUtilities/Logger (~> 5.2)
  - FirebaseFirestore (1.0.2):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 5.2)
    - FirebaseFirestore/abseil-cpp (= 1.0.2)
    - gRPC-C++ (= 0.0.6)
    - leveldb-library (~> 1.20)
    - nanopb (~> 0.3.901)
    - Protobuf (~> 3.1)
  - FirebaseFirestore/abseil-cpp (1.0.2):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 5.2)
    - gRPC-C++ (= 0.0.6)
    - leveldb-library (~> 1.20)
    - nanopb (~> 0.3.901)
    - Protobuf (~> 3.1)
  - FirebaseInstanceID (3.7.0):
    - FirebaseCore (~> 5.2)
    - GoogleUtilities/Environment (~> 5.2)
    - GoogleUtilities/UserDefaults (~> 5.2)
  - FirebaseMessaging (3.3.2):
    - FirebaseAnalyticsInterop (~> 1.1)
    - FirebaseCore (~> 5.2)
    - FirebaseInstanceID (~> 3.6)
    - GoogleUtilities/Environment (~> 5.3)
    - GoogleUtilities/Reachability (~> 5.3)
    - GoogleUtilities/UserDefaults (~> 5.3)
    - Protobuf (~> 3.1)
  - FirebaseRemoteConfig (3.1.0):
    - FirebaseABTesting (~> 2.0)
    - FirebaseAnalytics (~> 5.3)
    - FirebaseCore (~> 5.1)
    - FirebaseInstanceID (~> 3.3)
    - GoogleUtilities/Environment (~> 5.2)
    - GoogleUtilities/NSData+zlib (~> 5.2)
    - Protobuf (~> 3.5)
  - FirebaseStorage (3.1.0):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 5.2)
    - GTMSessionFetcher/Core (~> 1.1)
```

### [REQUIRED] Step 3: Describe the problem

When adding a delegate to Snapshot Listener, it causes a retain cycle.

I have a `Viewcontroller` that has a `weak delegate` to firestore listener class. If listener class calls the weak delegate reference when `Viewcontroller` class get destroyed. 

firestore listener class's deinit is never called.

#### Relevant Code:

```
import Foundation
import Firebase


protocol TicketDetailsManagerDelegate:class {
    func ticketDetailsModified(_ ticket:Ticket)
    func customerDetailsModified(_ customer:Customer)
}

class TicketDetailsManager: NSObject {
    
    weak var delegate:TicketDetailsManagerDelegate?
    var isFirestoreRequestInProgress:Bool = false
    
    weak var ticketReference:ListenerRegistration? //does weak do anything here
    weak var customerReference:ListenerRegistration?
    
    let docPath:String = "tickets"
    let collectionPath:String = "tickets_list"
    
    deinit {
        print("TicketDetailsManager deinit called")
    }
    
    convenience init(_ ticketId:String , _ delegate:TicketDetailsManagerDelegate?) {
        self.init()
        self.delegate = delegate
        self.getFirestoreTicket(ticketId)
    }
    
    /// Requests a ticket from Firestore
    func getFirestoreTicket(_ ticketId:String)
    {
        DispatchQueue.global(qos: .userInitiated).async {
            guard let portalId:String = LoginData.sharedInstance.getPortalId() else { return }
            guard let modelDelegate = self.delegate else {return}
            
            let db:Firestore = Firestore.firestore()
            let ticketRef = db.collection(portalId).document(self.docPath).collection(self.collectionPath).document(ticketId)
            
            self.ticketReference = ticketRef.addSnapshotListener { [unowned self] querySnapshot, err in
                guard let snapshot = querySnapshot else {
                    log.error("Error fetching snapshots: \(err!)")
                    return
                }
                
                guard let ticketData = snapshot.data()
                    else {
                        log.error("Ticket data was empty, can't update ticket details")
                        return
                }
                
                
                //get customer details thru foreignkey , aka document reference
                let ticket = Ticket(ticketData as NSDictionary)                
                //modelDelegate.ticketDetailsModified(ticket)
                
            }
            
        }
        
    }
```

Above example works fine because `modelDelegate` is commented out.

Result is
**TicketDetailsManager deinit called**

when this line is uncommented `modelDelegate.ticketDetailsModified(ticket)`  deinit is never get called, thus causing a retain cycle. 

in debuggin mode while  `TicketDetailsManager` class allocated graph looks like

![Screen Shot 2019-03-21 at 3 30 51 PM](https://user-images.githubusercontent.com/1995917/54780268-b7893400-4bef-11e9-83db-4287a149fe9f.png)

then when view is destroyed  and a new one pushed to the stack. you can see that previous one has not been destroyed because of addsnapshot listener

![Screen Shot 2019-03-21 at 3 33 24 PM](https://user-images.githubusercontent.com/1995917/54780343-dc7da700-4bef-11e9-8b56-093bad871ab0.png)

![Screen Shot 2019-03-21 at 3 51 46 PM](https://user-images.githubusercontent.com/1995917/54780882-4cd8f800-4bf1-11e9-85ad-de899ead1025.png)

**Comment by wilhuff** [comment]
This is working as designed. Some applications intend to fire and forget listeners, so `ListenerRegistration.dealloc()` does not destroy the listener.

You need to call `ListenerRegistration.remove()` on the listener registration when you're done with it. Either once you've gotten the data you need or in this class's `deinit`.

Using `weak` for your `ListenerRegistration` members doesn't do anything interesting. Firestore doesn't keep a strong reference to the `ListenerRegistration` proper, we only keep a strong reference to the implementation. As a result, your weak references will become nil and actually prevent you from calling `remove()`.

**Comment by ugenlik** [comment]
@wilhuff that is the problem `deinit` in my sample call is never called..... 

I am actively listening changes in firestore , it is not fire and forget so I cannot call `ListenerRegistration.remove()`

**Comment by ugenlik** [comment]
@wilhuff nevermind, reading carefully, you are right, this is a my bad. Misusage of `weak var delegate`

**Comment by wilhuff** [comment]
Based on the graph I assume that `TicketDetailsManagerDelegate` is actually implemented by `TicketDetailsViewModel`.

Your first problem is that your delegate is strongly retained by the block, even though your class goes out of its way to keep a weak reference. The difference between the working case and the non-working case is that when you uncomment `modelDelegate` in the Firestore listener you're capturing a strong reference to it. It's likely that `TicketDetailsViewModel` has a strong reference to  `TicketDetailsManager` which is what keeps it alitve.

**Comment by wilhuff** [comment]
Even after you deal with the delegate, your second problem is that when your view is going it away it really should notify the manager to stop listening. Otherwise we'll just keep delivery snapshots into that block even though the delegate has gone away.
