### ISSUE TITLE
InAppMessaging is displayed even if specified app's version changes after auto-update

### ISSUE THREAD

**Issue by TakahiroTsuchiya** [firebase/firebase-ios-sdk#2611]
InAppMessaging is displayed after the iOS app is auto updated.
The trigger conditions are based on the previous version of the app.
Expected result is that the in-app message cannot be displayed.

[READ] Step 1: Are you in the right place?
Yes

[REQUIRED] Step 2: Describe your environment

Xcode version: 10.1
Firebase SDK version: 5.14
Firebase Component: InAppMessagingDisplay
Component version: 0.12.2

[REQUIRED] Step 3: Describe the problem

Steps to reproduce:

 1. login to web console (https://console.firebase.google.com/)
 
 2. Grow > In-App Messaging, select
 
 3. Target > App(iOS), and "Version" (https://console.firebase.google.com/project/${PROJCET ID}/inappmessaging/compose)
     ex) this settings "include" version. 3.3.6
 
 4. Scheduling : "Now" and "No end date"
 
 5. Trigger : "app_lunch"
 
 6. Publish, campain
 
 7. the app's (version. 3.3.6) install and show In-App Messaging
 
 8. the app's new version (version. 4.0.0) release / TestFlight release.
 
 9. my iPhone "Settings" appli, iTunes Store & App Store > Updates "ON"

10. the app's updated (version. 4.0.0)

11. the app's lunch, show In-App Messaging

![Screen Shot 2019-03-22 at 16 09 20](https://user-images.githubusercontent.com/480329/54806303-f46f2c80-4cbc-11e9-8a64-760fdbe9fdfa.png)

**Comment by morganchen12** [comment]
@christibbs can you update this issue?

**Comment by christibbs** [comment]
Couldn't actually reproduce this.
