### ISSUE TITLE
[MLKit] FIRVisionTextBlock.text does not contain newline characters unlike Android counterpart

### ISSUE THREAD

**Issue by dov11** [firebase/firebase-ios-sdk#2615]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.1
  * Firebase SDK version: 5.16
  * Firebase Component: MLVisionTextModel
  * Component version: 5.16

### [REQUIRED] Step 3: Describe the problem

Hello, we are using MLKit in React Native library [react-native-camera](https://github.com/react-native-community/react-native-camera), and recently one of the users [reported](https://github.com/react-native-community/react-native-camera/issues/2161#issue-424357040) differences in textBlock values on iOS and Android. 

Specifically, the string obtained from `FIRVisionTextBlock.text` does not contain newline characters for a multi-line text, while `FirebaseVisionText.TextBlock.getText()` does.
I have checked native [Firebase example](https://github.com/firebase/quickstart-ios/tree/master/mlvision) for iOS, and the newline characters are absent there as well, so it does not look like it is a problem with our implementation for react native.

I was wondering if this observation is correct and if there are plans to unify this behaviour for two platforms?

#### Steps to reproduce:

Easiest way to reproduce the issue that I found (outside React Native) is use [Firebase example](https://github.com/firebase/quickstart-ios/tree/master/mlvision) for iOS, add logging after [this line](https://github.com/firebase/quickstart-ios/blob/d879fa74ef2e5c2ac999ae4a5b18d15087c80df9/mlvision/MLVisionExample/ViewController.swift#L516) and detect text in image [from here](https://github.com/react-native-community/react-native-camera/issues/2161#issue-424357040)
Detection works fine, 3 lines are detected, but the logged textBlock text value does not have newline characters in it.

**Comment by temrich** [comment]
Hey Daniil, thank you for the detailed description! Will take a look and see what's going on.

**Comment by temrich** [comment]
We were able to identify the root cause of the discrepancy between Android and iOS and will be applying the fix in the next release.

In the meantime if anyone is currently blocked by this, the `VisionTextBlock` class has a [`lines`](https://firebase.google.com/docs/reference/swift/firebasemlvision/api/reference/Classes/VisionTextBlock#lines) property that you can iterate through to construct the block text with newlines, for example:

```
textRecognizer?.process(visionImage) { text, error in
  for block in text.blocks {
    let blockText = block.lines.joined(separator: "\n")
  }
}
```

Thank you!

**Comment by dov11** [comment]
Great! Thanks, @temrich! 
I indeed [suggested](https://github.com/react-native-community/react-native-camera/issues/2161#issuecomment-475967122) using line elements as an alternative for now.
