### ISSUE TITLE
App crash with MLVision

### ISSUE THREAD

**Issue by MestevMYnov** [firebase/firebase-ios-sdk#2630]
Hello i got this error with firebase in my app : 

Xcode version : 10.1
Firebase SDK version : 5.17.0
Firebase MLVisionText

Error : 

`F0325 21:33:09.189833       3 mobile_lstm_recognizer.cc:834] Check failed: codes.size() == 1 (2 vs. 1) `

This app crash when the function of object vision "onDeviceTextRecognizer" is called.

Thanks you in advance for help

**Comment by maksymmalyhin** [comment]
@JimmyMYnov Thank you for reporting the issue. Would you be able to share a sample project and steps to reproduce the issue, please.

**Comment by JimmyMYnov** [comment]
@maksymmalyhin We can't share my projet, but we can reproduce this with https://github.com/firebase/quickstart-ios/tree/master/mlvision

**Comment by maksymmalyhin** [comment]
@JimmyMYnov Thank you for sharing this. 
I was not able to reproduce the issue myself. I assume, there are some details I am missing. 

Will it be possible to share your `Podfile` and `Podfile.lock`? Also, do you have the crash on a particular image? If yes, could you share it as well?

**Comment by maksymmalyhin** [comment]
@JimmyMYnov Another note - the most recent version of Firebase is 5.19.0. If you are able to update Firebase version and check the issue?

**Comment by JimmyMYnov** [comment]
@maksymmalyhin 

I missing that point : For two project i use carthage
This error is made with a camera, so no matter the picture.
I have already try to upgrade to 5.19.0 but this error is still same

**Comment by mikengyn** [comment]
This started happening to me too randomly, will report back if I can figure out the issue

**Comment by MestevMYnov** [comment]
Yes this error is happened and generalized in my app when i make an archive

**Comment by temrich** [comment]
@MestevMYnov Can you please provide a stack trace or log file that shows the error/crash?

**Comment by MestevMYnov** [comment]
<img width="575" alt="Capture d’écran 2019-03-27 à 21 32 42" src="https://user-images.githubusercontent.com/18066154/55110239-ea439880-50d7-11e9-8049-f09274c4d7fa.png">

**Comment by temrich** [comment]
@MestevMYnov Thank you! We can definitely locate where the error is coming from, but the error could happen for many reasons. Are you able to provide the full crash log, which will help us determine which code path is leading to this check failure?

**Comment by MestevMYnov** [comment]
`2019-03-27 21:22:40.928841+0100 XXXXXX[6886:1248850] 5.17.0 - <AppMeasurement>[I-ACS036000] Found unknown associated object: APMScreen
2019-03-27 21:22:42.238366+0100 XXXXXX[6886:1248850] 5.17.0 - <AppMeasurement>[I-ACS036000] Found unknown associated object: APMScreen
F0327 21:22:43.661897       3 mobile_lstm_recognizer.cc:834] Check failed: codes.size() == 1 (2 vs. 1) `
I can't provide full crash log, because it's entreprise project. But only these line is pertinent, other log it is about layout constraint and other, no relation with Firebase
@temrich

**Comment by MestevMYnov** [comment]
@temrich And yes i'm in 5.17.0, but error is same in 5.19.0 @temrich

**Comment by morganchen12** [comment]
@MestevMYnov Please provide the stack trace (not the console log) where you've redacted your company's proprietary symbols. Firebase and UIKit symbols should remain in the stack trace.

**Comment by MestevMYnov** [comment]
`(lldb) bt
* thread #16, stop reason = signal SIGABRT
  * frame #0: 0x00000002060f7104 libsystem_kernel.dylib`__pthread_kill + 8
    frame #1: 0x0000000206173020 libsystem_pthread.dylib`pthread_kill$VARIANT$mp + 380
    frame #2: 0x000000020604ed78 libsystem_c.dylib`abort + 140
    frame #3: 0x0000000106986a6c MonProjet`___lldb_unnamed_symbol13917$$MonProjet + 24
    frame #4: 0x0000000106986a8c MonProjet`___lldb_unnamed_symbol13918$$MonProjet + 12
    frame #5: 0x00000001069ba044 MonProjet`___lldb_unnamed_symbol15150$$MonProjet + 2940
    frame #6: 0x00000001069ba774 MonProjet`___lldb_unnamed_symbol15152$$MonProjet + 152
    frame #7: 0x0000000106cacec8 MonProjet`___lldb_unnamed_symbol27584$$MonProjet + 16
    frame #8: 0x0000000106655c60 MonProjet`___lldb_unnamed_symbol232$$MonProjet + 44
    frame #9: 0x0000000106d99ca8 MonProjet`___lldb_unnamed_symbol32483$$MonProjet + 296
    frame #10: 0x0000000106d99d98 MonProjet`___lldb_unnamed_symbol32484$$MonProjet + 164
    frame #11: 0x0000000106ac9608 MonProjet`___lldb_unnamed_symbol19282$$MonProjet + 16
    frame #12: 0x0000000106ad7de4 MonProjet`___lldb_unnamed_symbol19357$$MonProjet + 44
    frame #13: 0x0000000106cb9a60 MonProjet`___lldb_unnamed_symbol28010$$MonProjet + 340
    frame #14: 0x0000000106cb3bdc MonProjet`___lldb_unnamed_symbol27820$$MonProjet + 416
    frame #15: 0x000000020617c25c libsystem_pthread.dylib`_pthread_body + 128
    frame #16: 0x000000020617c1bc libsystem_pthread.dylib`_pthread_start + 48
    frame #17: 0x000000020617fcf4 libsystem_pthread.dylib`thread_start + 4
(lldb) `

**Comment by MestevMYnov** [comment]
@temrich @morganchen12

**Comment by morganchen12** [comment]
This stack trace contains no information since the symbols aren't visible. Can you upload a sample that reproduces this issue?

**Comment by bcdj** [comment]
Hi MestevMYnov, you mentioned that you can reproduce this with https://github.com/firebase/quickstart-ios/tree/master/mlvision.  Could you provide detailed steps of how to reproduce this crash using the quickstart mlvision app, including any customization you might have made to the app, and any particular test image you have used for reproducing the crash?  Thanks!

**Comment by MestevMYnov** [comment]
@morganchen12 
Hello, 

After testing, I can say that the bug comes from "./Carthage/Build/iOS/FaceDetector.framework/GoogleMVFaceDetectorResources.bundle".
I deleted the reference in "Build Phase" and added it again and it's work.

So now, for the moment i don't have this crash again, but where does he come from ???

**Comment by paulb777** [comment]
Internally tracked at b/130737011
