### ISSUE TITLE
FIRDocumentSnapshot Internal -> Public

### ISSUE THREAD

**Issue by radvansky-tomas** [firebase/firebase-ios-sdk#2654]
Hi everyone, please is there a chance to make this header public: FIRDocumentSnapshot+Internal.h

If you look at trouble it causes on flutter https://github.com/flutter/flutter/issues/23618

You might understand my frustration. All we need is to have simple way for pagination.
Current solution is quite hideous how it is...I still dont understand why We cannot use documentId in startAtDocument method. Anyhow on other platforms, because of your access control settings, We cannot construct FIRDocumentSnapshot object, as there are no public constructors.

Therefore We cannot use pagination methods startAtDocument, etc...

Flutter SDK or other platforms can obviously serialise any kind of data and send it back to native IOS SDK, but there is not way currently to pass that data to make FIRQuery.

Some snippets, in this piece of code I have my documentID, but I can have whole NSDictionary filled with documentSnapshot data, coming from Dart/Flutter or other platforms...but still I cannot construct document snapshot.

```
  id startAtDocument = parameters[@"startAtDocument"];
  if (startAtDocument) {
    NSString *startAtId = startAtDocument;
    query = [query queryStartingAtDocument:snapshot???];
  }
```

But if you look into internal method:
```
+ (instancetype)snapshotWithFirestore:(FIRFirestore *)firestore
                          documentKey:(firebase::firestore::model::DocumentKey)documentKey
                             document:(nullable FSTDocument *)document
                            fromCache:(BOOL)fromCache;
```

It might be possible to pass those variables from flutter/dart SDK.

If not, could you please suggest workaround ? LIke passing documentID, path, firestore instance etc and use it for paging ? Only thing in my mind is to use REST approach

https://firebase.google.com/docs/firestore/reference/rest/v1beta1/StructuredQuery 

And try to create Cursor object with referenceValue insde. I am not even sure it this could work

**Comment by radvansky-tomas** [comment]
Specially if you are not really using documentSnapshot content, as per your method

`- (FSTBound *)boundFromSnapshot:(FIRDocumentSnapshot *)snapshot isBefore:(BOOL)isBefore`

You are passing some internal key which is used for sorting...

**Comment by radvansky-tomas** [comment]
Or is there a way to order collection by documentId and then pass documentId to startAt (values)

```
 id startAtDocument = parameters[@"startAtDocument"];
  if (startAtDocument) {
    NSArray *startAtValues = startAt;
    query = [query queryOrderedByFieldPath:FIRFieldPath.documentID descending:YES];
    query = [query queryStartingAfterValues:startAtValues];
  }
```

**Comment by radvansky-tomas** [comment]
So last solution is not supported (DESC), and even if it was...documentID is not chronological key in firestore :(

**Comment by radvansky-tomas** [comment]
Only option which actually works is to use documentID in native code and perform extra reading to get documentSnapshot and pass this into query.

```
   id startAtDocument = parameters[@"startAtDocument"];
    if (startAtDocument) {
      NSArray *startAtValues = startAtDocument;
      FIRDocumentReference* ref = [[getFirestore(arguments) collectionWithPath:arguments[@"path"]] documentWithPath:startAtValues[0]];
      [ref addSnapshotListener:^(FIRDocumentSnapshot * _Nullable snapshot, NSError * _Nullable error) {
         query = [query queryStartingAtDocument:snapshot];
        return handler(query);
      }];
    }
```

Which is kind of insane...as I already have this

**Comment by morganchen12** [comment]
DocumentSnapshot, unlike DocumentReference, contains document existence state, and thus isn't suitable for constructing on the client. What you should do instead is fetch a query limited to some number of items and then use the last document in the query snapshot in your next `startingAt(_:)` call. What you're trying to do instead is not supported and will probably not ever be supported, since there's no way of guaranteeing a document snapshot created without a server fetch is a valid snapshot for a given query.

If you want your query to be chronologically descending, add a server timestamp field to your document and use an ordered query (via `order(by:)`).

**Comment by radvansky-tomas** [comment]
@morganchen12 Thank you for reply, but you did not understand the problem.

First of all, I am using official Firestore plugin for flutter, which is basically wrapper around Firestore iOS & Android SDK. What it does is to expose your methods to flutter/dart. So in my code I obviously have DocumentSnapshot coming from query, with all states etc. But this object has been parsed and transferred to Dart. 

Now when We need to perform another query and pass this object back, we cannot construct it back from data coming from flutter/dart.

Second part of statement is wrong as well, my query is already chronologically sorted, I have my created unix property there and its sorted by it. Problem is that for some unknown reason firebase API + SDK needs document snapshot object to make another query to perform paging. Why would you need any state there...there will be new data coming from server anyway, only thing you need is to have documentId, sortBy field and path to collection (+ firestore instance)

**Comment by wilhuff** [comment]
The fix is to make flutter retain the underlying FIRDocumentSnapshot so that when you transfer it back across the dart / Objective-C boundary you can reuse the snapshot that already exists.  

We don't allow snapshots to be constructed arbitrarily because there's too much underlying complexity that we don't want to expose.

**Comment by mikelehen** [comment]
It's also worth noting that `startAtDocument()` is just a convenience method to perform the equivalent `startAt()` call.

`collection.orderBy('x').orderBy('y').startAtDocument(someDoc)` is basically shorthand for `collection.orderBy('x').orderBy('y').orderBy(FieldPath.documentId()).startAt(someDoc.get('x'), someDoc.get('y'), someDoc.documentId)`

So you can certainly do pagination without having the `startAtDocument()` method.

**Comment by radvansky-tomas** [comment]
@mikelehen finally something useful, could you please rewrite your answer as I really dont understand this bit "someDoc.get('x')" Could you try write it in objc/swift/java/kotlin ?

**Comment by mikelehen** [comment]
@radvansky-tomas These two (Swift) queries are equivalent:

```
  let someDoc: DocumentSnapshot
  query = collection.order(by: "x").order(by: "y").start(atDocument: someDoc)
  query = collection.order(by: "x").order(by: "y").order(by: FieldPath.documentID()).start(at: [someDoc.get("x"), someDoc.get("y"), someDoc.documentID])
```

Does that help?

**Comment by radvansky-tomas** [comment]
@mikelehen YES. Will do changes and test on my side. And if its going to work, we will be able to close this issue. But then I really suggest to put this snipped into documentation, as there is no reference to it!

**Comment by mikelehen** [comment]
Thanks for the feedback!  I've opened an internal bug to improve the reference docs for startAtDocument() to make this clearer.

Please do let us know if this works for you and then we can close the issue.  Thanks!

**Comment by radvansky-tomas** [comment]
@mikelehen Thank you very much for your help. It seems to be working fine. I will have to do more complex tests. But for now you can close the issue. I will update cloud_firestore plugin for flutter to support this approach.

**Comment by mikelehen** [comment]
Sounds good, thanks for the quick follow-up!
