### ISSUE TITLE
Firebase Docs should stop recommending Firebase/Core inclusion

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#2659]
Users should be explicit about asking for Firebase/Analytics

**Comment by paulb777** [comment]
Along with the docs, all of the [quickstart sample](https://github.com/firebase/quickstart-ios) Podfiles should be changed from Firebase/Core to Firebase/Analytics.  Since this does not change any functionality, it can be rolled out immediately.

**Comment by paulb777** [comment]
Quickstart PR at https://github.com/firebase/quickstart-ios/pull/685

**Comment by paulb777** [comment]
Quickstarts are updated. Documentation updates is now a nice to have for 6.0.0, but not a blocker.

**Comment by syvertsj** [comment]
Using Firebase/Analytics pod I get linker error for FIRBundleUtil.o expected in FirebaseCore:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_GULAppEnvironmentUtil", referenced from:
      objc-class-ref in FirebaseCore(FIRBundleUtil.o)
```

The Firebase/Analytics pod wraps the GoogleAppMeasurement, FirebaseAnalytics, FirebaseCoreDiagnostics, and FIRAnalyticsConnector frameworks, all of which was linked. 

I saw in another thread the "linker" (compiler) flag -fprofile-arcs providing a workaround. 
This made no difference.

**Comment by ryanwilson** [comment]
Documentation is up to date. Feel free to re-open if you find a link to the Firebase site that still uses `Firebase/Core`.
