### ISSUE TITLE
Unable to install Firebase through cocoa pods if version specified

### ISSUE THREAD

**Issue by hanumanAbacus** [firebase/firebase-ios-sdk#2674]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2
  * Firebase SDK version: 5.1.1
  * Firebase Component: Auth, Core, Database, Firestore, Storage
  * Component version: 5.1.1

### [REQUIRED] Step 3: Describe the problem

Podfile:
```
platform :ios, 8.0
    pod 'Firebase/Database', '~> 5.1.1'
    pod 'Firebase/Auth', '~> 5.4.1'
    pod 'Firebase/Core', '~> 5.4.0'
    pod 'Firebase/Firestore', '~> 1.1.0'
    pod 'Firebase/Storage', '~> 3.1.1'

```
```
[!] CocoaPods could not find compatible versions for pod "Firebase/Database":
  In Podfile:
    Firebase/Database (~> 5.1.1)

None of your spec sources contain a spec satisfying the dependency: `Firebase/Database (~> 5.1.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

```

I tried doing pod repo update but no luck
I am using 1.6.1 of pods

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulb777** [comment]
The Podfile is asking for subspecs from the Firebase pod with versions from the specific library pods.

If you want to specify FirebaseDatabase version 5.1.1, do 

`pod 'FirebaseDatabase', '~> 5.1.1'`

No **slash**.

**Comment by hanumanAbacus** [comment]
@paulb777 I am doing the same, but it doesn't not find
