### ISSUE TITLE
FR: watchOS Support

### ISSUE THREAD

**Issue by mknippen** [firebase/firebase-ios-sdk#269]
With the release of watchOS 4 and an LTE Apple Watch, there’s no better time to plan support for Apple Watch. The Series 3 Watch has significantly more power, and applications will want to connect to Firebase.

**Comment by salqadri** [comment]
Hi Matthew! Yes WatchOS4 looks awesome and we are keeping a close watch (pun intended) on this platform. We will continue to evaluate officially supporting the platform as it grows in apps and users, but until we do, we welcome any community contributions in this area.

**Comment by boblepepeur** [comment]
I'm In !

**Comment by coolioxlr** [comment]
+1

**Comment by robpeach** [comment]
+1

**Comment by dyah10** [comment]
+1

**Comment by wipnick** [comment]
+1

**Comment by ugenlik** [comment]
+1

**Comment by Lawris** [comment]
+1

**Comment by polok** [comment]
+1

**Comment by thattyson** [comment]
+1

**Comment by AsteaDevelopment** [comment]
+1

**Comment by GioPalusa** [comment]
Watch OS 5 is here, and an addition with Firebase to WatchOS would be greatly appreciated! +1

**Comment by zhgchgli0718** [comment]
+1

**Comment by mikemike396** [comment]
Any update on this?

**Comment by mariohahn** [comment]
+1

**Comment by Supertecnoboff** [comment]
2019 and still no watchOS support 😢

**Comment by sotrosh** [comment]
just watched firebase 2019. Added wearOS support. No watchOS support still.

**Comment by pepejeria** [comment]
I guess that this won't be an issue anymore with watchOS 6 since apps are independent?

**Comment by mknippen** [comment]
I think this will be a much bigger issue. Hopefully with all of the streaming data and network framework, we can make this available ASAP!

**Comment by Supertecnoboff** [comment]
> I think this will be a much bigger issue. Hopefully with all of the streaming data and network framework, we can make this available ASAP!
> […](#)

Surely you can add watchOS support because presumably watchOS 6 has the CFNetwork framework?

**Comment by robbiet480** [comment]
My _assumption_ is that watchOS won't be supported until Google Analytics is supported which is gonna be a long time since we don't have UIKit for watchOS and at this point it's unlikely we ever will with the introduction of SwiftUI.

**Comment by ryanwilson** [comment]
Started some investigation into this and kicked off the attempt with GoogleUtilities since it has no dependencies and is a dependency of all other Firebase SDKs - a few hurdles to start:

- `OCMock` isn't available for watchOS, meaning a majority of our tests won't work
- A larger hurdle (after disabling the `test_spec` in the podspec) the [`SystemConfiguration` framework](https://developer.apple.com/documentation/systemconfiguration) isn't available in watchOS. 
  - This affects three subspecs: `Reachability`, `Network`, and `AppDelegateSwizzler`, which in turn affects Auth, Messaging, and Analytics.

It looks like it may be possible to add support for individual subspecs and maybe that's the way to pare it down further, but unfortunately this won't be as easy as just adding `s.watchos.deployment_target = '5.0'`

If anyone else wants to make an attempt in the meantime, you may be able to start adding support for each subspec and then creating a new watchOS target in the [Example Xcode project](https://github.com/firebase/firebase-ios-sdk/tree/master/GoogleUtilities/Example/GoogleUtilities.xcodeproj).

**Comment by morganchen12** [comment]
@ryanwilson watchOS tests running on simulator are compiled against the iOS simulator target. This might change with standalone watch apps, but afaik hasn't yet in watchOS 6. iOS simulator testing + build targeting watchOS should be sufficient for watchOS for the time being. I made a PR to OCMock to [add watchOS support](https://github.com/erikdoe/ocmock/pull/374), but it shouldn't be a blocker for testing.

**Comment by ryanwilson** [comment]
@morganchen12 makes sense, the issue I ran into was using `pod lib lint` and `pod gen` - the watchOS bit choked when getting to the test spec that depended on the OCMock pod. I disabled the test spec to generate the project instead.

Re: `SystemConfiguration` not being available, it looks like `[WatchConnectivity](https://developer.apple.com/documentation/watchconnectivity/wcsessiondelegate/1615662-sessionreachabilitydidchange) has a reachability function we can use to replace the one in `SystemConfiguration`.

**Comment by larryonoff** [comment]
It would be really appreciated to do watchOS support at least from 6.0.

**Comment by morganchen12** [comment]
Additional FR #3453

**Comment by sotrosh** [comment]
any updates on this issue? watchOS 6 has released.

**Comment by morganchen12** [comment]
watchOS support was merged into OCMock today. In preparation for this feature, we can start running tests on watchOS simulator once OCMock makes a new release.

**Comment by kajensen** [comment]
Any movement on this issue?

**Comment by paulb777** [comment]
Progressing at #4016

**Comment by paulb777** [comment]
Now that #4016 has merged with support for FirebaseMessaging and watchOS and will be part of the first release of 2020, I'm going to close this is umbrella issue.

Please open additional issues for any additional specific requested functionality for watchOS.

**Comment by mknippen** [comment]
@paulb777 Is this supporting the Firebase Database on independent watch apps, or just Firebase Messaging? The original ticket here was so that we can make read/writes to the Realtime Database in watchOS

**Comment by paulb777** [comment]
@mknippen It's just Firebase Messaging so far. 

Going back and looking at the OP, I don't see the Firebase Database mention.

How about creating another issue specifically for Database and watchOS? A similar issue could be created for any other requested Firebase libraries for watchOS.  That will help us prioritize.

BTW, if anyone wants to work on this, the approach would be to update the relevant podspec's like #4016, working though any build issues, validating, and sending a PR.

**Comment by n3at18** [comment]
@paulb777 @mknippen I've created a separate feature request for Realtime Database support: https://github.com/firebase/firebase-ios-sdk/issues/4556

**Comment by jroets** [comment]
I've created feature requests for Firebase Analytics and Firebase Crashlytics on watchOS: #4557 and #4558, respectively.
