### ISSUE TITLE
Unable to build project: Undefined symbol _GRPC_SHADOW_SSL_SESSION_up_ref

### ISSUE THREAD

**Issue by agordeev** [firebase/firebase-ios-sdk#2692]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2
  * Firebase SDK version: 5.20.1
  * Firebase Component: the one that requires gRPC?

#### Steps to reproduce:

I use Carthage 0.32.0
After updating dependencies I no more able to build my project due to compile errors:

```
Undefined symbols for architecture x86_64:
  "_GRPC_SHADOW_SSL_SESSION_up_ref", referenced from:
      tsi::(anonymous namespace)::BoringSslCachedSession::CopySession() const in gRPC-Core(ssl_session_boringssl.o)
  "_GRPC_SHADOW_HMAC_CTX_new", referenced from:
      aes_gcm_derive_aead_key(unsigned char*, unsigned char const*, unsigned char const*) in gRPC-Core(aes_gcm.o)
  "_GRPC_SHADOW_HMAC_Init_ex", referenced from:
      aes_gcm_derive_aead_key(unsigned char*, unsigned char const*, unsigned char const*) in gRPC-Core(aes_gcm.o)
  "_GRPC_SHADOW_HMAC_Update", referenced from:
      aes_gcm_derive_aead_key(unsigned char*, unsigned char const*, unsigned char const*) in gRPC-Core(aes_gcm.o)
  "_GRPC_SHADOW_EVP_DecryptFinal_ex", referenced from:
      gsec_aes_gcm_aead_crypter_decrypt_iovec(gsec_aead_crypter*, unsigned char const*, unsigned long, iovec const*, unsigned long, iovec const*, unsigned long, iovec, unsigned long*, char**) in gRPC-Core(aes_gcm.o)
  "_GRPC_SHADOW_EVP_EncryptInit_ex", referenced from:
      gsec_aes_gcm_aead_crypter_encrypt_iovec(gsec_aead_crypter*, unsigned char const*, unsigned long, iovec const*, unsigned long, iovec const*, unsigned long, iovec, unsigned long*, char**) in gRPC-Core(aes_gcm.o)
.....
```

<img width="697" alt="Screenshot 2019-03-31 at 17 34 59" src="https://user-images.githubusercontent.com/2883524/55290384-56c1de80-53db-11e9-9a61-cb4ebb863aaf.png">

**Comment by mikelehen** [comment]
@agordeev Could you let us know the last Firebase SDK version that worked correctly for you?  That will help us isolate the issue and resolve it faster.  Thanks.

**Comment by agordeev** [comment]
@mikelehen readding all the frameworks helped. Thanks
