### ISSUE TITLE
OSX pod issue

### ISSUE THREAD

**Issue by iceman201** [firebase/firebase-ios-sdk#2700]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.10
  * Firebase SDK version: _____
  * Firebase Component: Auth, Core, Database, Firestore, Messaging, Storage
  * Component version: _____

### [REQUIRED] Step 3: Describe the problem
Just want to confirm that is Firebase no longer support even single feature on macOS platform?
looks like I cant install any of them.
![image](https://user-images.githubusercontent.com/5027957/55367366-3b74e180-5549-11e9-858a-08eea41abdd9.png)
![image](https://user-images.githubusercontent.com/5027957/55367420-66f7cc00-5549-11e9-95ef-47dc35549062.png)

especially this one: 
The FirebaseFirestore without it, I couldn't config my application
![image](https://user-images.githubusercontent.com/5027957/55369134-cb1e8e00-5551-11e9-90b6-c05a04c54602.png)

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

**Comment by paulb777** [comment]
Please see the instructions at https://github.com/firebase/firebase-ios-sdk#macos-and-tvos. The Firebase pod is not supported.  Both Firestore and Functions added osx support in more recent versions than requested. Perhaps you need a `pod update`. 

If you're still having trouble, please share the Podfile and Podfile.lock.
