### ISSUE TITLE
Linking Firebase dynamic frameworks on iOS 

### ISSUE THREAD

**Issue by vmanot** [firebase/firebase-ios-sdk#2707]
I have an app `Foo` and a framework `Bar`. 

Both targets `Foo` and `Bar` link `Firebase` and related frameworks (`Auth`, `Storage`, `Firestore` etc.) in their respective `Link Binary With Libraries` build phases (in Xcode).

`Foo.app` depends on `Bar.framework` (i.e. links it in its own build phase). 

When I run my app, I run into a myriad of runtime warnings, almost all of them in the format of:

```Class SomeFirebaseClass is implemented in both .../Foo and .../Bar```

How should I go about resolving this?

Note: I'm using Carthage.

**Comment by paulb777** [comment]
Firebase's binary frameworks are static and cannot be depended upon by multiple dynamic frameworks.  Other frameworks that depend upon Firebase must also be static.

**Comment by vmanot** [comment]
@paulb777 is there any workaround?

**Comment by paulb777** [comment]
@vmanot Nothing simple that I know of. If you're only using open source parts of Firebase, you could rebuild as dynamic frameworks. I don't know Carthage well enough to describe how to define a static framework depending on another static framework.
