### ISSUE TITLE
Crash on [FIRInstanceIDTokenOperation start] + 435

### ISSUE THREAD

**Issue by mackoj** [firebase/firebase-ios-sdk#2732]
### Describe your environment

  * Xcode version: 10.1 (10B61)
  - Firebase/Core (5.19.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 5.8.0)
  - Firebase/CoreOnly (5.19.0):
    - FirebaseCore (= 5.4.0)
  - Firebase/Performance (5.19.0):
    - Firebase/Core
    - FirebasePerformance (= 2.2.4)
  - Firebase/RemoteConfig (5.19.0):
    - Firebase/Core
    - FirebaseRemoteConfig (= 3.1.0)
  - FirebaseABTesting (2.0.0):
    - FirebaseCore (~> 5.0)
    - Protobuf (~> 3.5)
  - FirebaseAnalytics (5.8.0):
    - FirebaseCore (~> 5.4)
    - FirebaseInstanceID (~> 3.8)
    - GoogleAppMeasurement (= 5.8.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 5.2)
    - GoogleUtilities/MethodSwizzler (~> 5.2)
    - GoogleUtilities/Network (~> 5.2)
    - "GoogleUtilities/NSData+zlib (~> 5.2)"
    - nanopb (~> 0.3)
  - FirebaseCore (5.4.0):
    - GoogleUtilities/Environment (~> 5.2)
    - GoogleUtilities/Logger (~> 5.2)
  - FirebaseInstanceID (3.8.0):
    - FirebaseCore (~> 5.2)
    - GoogleUtilities/Environment (~> 5.2)
    - GoogleUtilities/UserDefaults (~> 5.2)
  - FirebasePerformance (2.2.4):
    - FirebaseAnalytics (~> 5.8)
    - FirebaseInstanceID (~> 3.8)
    - FirebaseRemoteConfig (~> 3.1)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - GoogleUtilities/ISASwizzler (~> 5.2)
    - GoogleUtilities/MethodSwizzler (~> 5.2)
    - GTMSessionFetcher/Core (~> 1.1)
    - Protobuf (~> 3.5)
  - FirebaseRemoteConfig (3.1.0):
    - FirebaseABTesting (~> 2.0)
    - FirebaseAnalytics (~> 5.3)
    - FirebaseCore (~> 5.1)
    - FirebaseInstanceID (~> 3.3)
    - GoogleUtilities/Environment (~> 5.2)
    - "GoogleUtilities/NSData+zlib (~> 5.2)"
    - Protobuf (~> 3.5)

### Step 3: Describe the problem

Sometime the app crash at startup.

#### The crash is on this thread.
```
Thread 20 Queue : com.google.iid-token-operations (QOS: UTILITY) (concurrent)
#0	0x000000011ad6c2c6 in __pthread_kill ()
#1	0x000000011adbfbf1 in pthread_kill ()
#2	0x000000011ab2ec45 in abort ()
#3	0x0000000119c565b1 in abort_message ()
#4	0x0000000119c5674d in default_terminate_handler() ()
#5	0x0000000118588a9d in _objc_terminate() ()
#6	0x0000000119c6265e in std::__terminate(void (*)()) ()
#7	0x0000000119c626d3 in std::terminate() ()
#8	0x0000000118588a22 in objc_terminate ()
#9	0x000000011a9d255f in _dispatch_client_callout ()
#10	0x000000011a9d4f70 in _dispatch_continuation_pop ()
#11	0x000000011a9d45dd in _dispatch_async_redirect_invoke ()
#12	0x000000011a9e1491 in _dispatch_root_queue_drain ()
#13	0x000000011a9e1cfb in _dispatch_worker_thread2 ()
#14	0x000000011adbc6b3 in _pthread_wqthread ()
#15	0x000000011adbc3fd in start_wqthread ()
```

```
2019-04-05 14:28:24.688219+0200 PagesJaunes[99979:2788611] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Cannot fetch token invalid checkin state'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010bf8f1bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000118588735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010bf8ef42 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010d53d940 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 166
	4   PagesJaunes                         0x00000001061944d3 -[FIRInstanceIDTokenOperation start] + 435
	5   Foundation                          0x000000010d5aac4b __NSOQSchedule_f + 227
	6   libdispatch.dylib                   0x000000011a9d14e1 _dispatch_call_block_and_release + 12
	7   libdispatch.dylib                   0x000000011a9d254b _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x000000011a9d4f70 _dispatch_continuation_pop + 453
	9   libdispatch.dylib                   0x000000011a9d45dd _dispatch_async_redirect_invoke + 827
	10  libdispatch.dylib                   0x000000011a9e1491 _dispatch_root_queue_drain + 355
	11  libdispatch.dylib                   0x000000011a9e1cfb _dispatch_worker_thread2 + 97
	12  libsystem_pthread.dylib             0x000000011adbc6b3 _pthread_wqthread + 583
	13  libsystem_pthread.dylib             0x000000011adbc3fd start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

#### Steps to reproduce:

This is the complicated part I don't know how to reproduce it. It happened from time to time.

**Comment by maksymmalyhin** [comment]
@mackoj Thank you for reporting the issue. From the logs provided, it looks you encounter an assertion failure which leads to crash only under DEBUG builds. On a release configuration you the crash should not happen, though an internal error may still occur.

From a brief review of related code I found out following:
- the error if happen, should eventually lead to the operation retry
- it looks like the reason of the possible inconsistency has been fixed in #2631. The fix is available from version 5.20.0

Would you be able to update Firebase SDK and confirm if you still have the issue?

**Comment by mackoj** [comment]
Ok I will try thanks

**Comment by mackoj** [comment]
It seem to have fixed the bug.

**Comment by choiks14** [comment]
is it solved??
