### ISSUE TITLE
FR: Pure Swift Firestore Implementation using SwiftGRPCNIO

### ISSUE THREAD

**Issue by funcsatish** [firebase/firebase-ios-sdk#2733]
Pure Swift Firestore Implementation using SwiftGRPCNIO Pros:

1. Swift Package Manager Support
2. Server Side Swift Support

**Comment by rsgowman** [comment]
This would be pretty neat, but re-writing our SDK in swift isn't likely to be something we'd want to tackle any time soon. (We're trying to keep the number of implementations at a minimum, as much as possible.)
