### ISSUE TITLE
-[FIRVerifyAssertionRequest unencodedHTTPRequestBodyWithError:] exception

### ISSUE THREAD

**Issue by shrekShih** [firebase/firebase-ios-sdk#2748]
### Environment
  * Xcode version: 10.2
  * Firebase SDK version:   Firebase/Core (5.20.1):
  * Firebase Component: 
Core/Auth/Firestore/Storage/Performance/
Fabric/Crashlytics
  * Component version: 
  - Firebase/Core (5.20.1):
  - Firebase/Firestore (5.20.1):
  - Firebase/Storage (5.20.1):
  - FirebaseAuth (5.4.2):
    - FirebasePerformance (= 2.2.4)

### [REQUIRED] Describe the problem
Crashed when trying to register FB user. 

#### Steps to reproduce:

1. Use ```FBSDKLoginButton``` to log in
2.```[[[FBSDKGraphRequest alloc] initWithGraphPath:@"me"
                                       parameters:@{@"fields": @"email"}]```
3.  ```FIRAuthCredential *credential =
         [FIRFacebookAuthProvider
          credentialWithAccessToken:[FBSDKAccessToken currentAccessToken].tokenString];
         [[FIRAuth auth] signInAndRetrieveDataWithCredential:credential
                                                  completion:^(FIRAuthDataResult * _Nullable authResult,
                                                               NSError * _Nullable error)```

Then it crashed at first time user logging in.
Log attached. 

#### Relevant Code:

```
- (void)loginButton:(FBSDKLoginButton *)loginButton didCompleteWithResult:(FBSDKLoginManagerLoginResult *)result error:(NSError *)error
{
  if(result.token != nil && !result.isCancelled && [result.grantedPermissions containsObject:@"email"]) {
    [[[FBSDKGraphRequest alloc] initWithGraphPath:@"me"
                                       parameters:@{@"fields": @"email"}]
     startWithCompletionHandler:^(FBSDKGraphRequestConnection *connection, id result, NSError *error) {
       if (error) {
         return;
       } else {
         self.loginButton.alpha = 0;
         FIRAuthCredential *credential =
         [FIRFacebookAuthProvider
          credentialWithAccessToken:[FBSDKAccessToken currentAccessToken].tokenString];
         [[FIRAuth auth] signInAndRetrieveDataWithCredential:credential
                                                  completion:^(FIRAuthDataResult * _Nullable authResult,
                                                               NSError * _Nullable error)
          {
            if (error || !authResult) {
              return;
            }
```
[appDsyms.zip](https://github.com/firebase/firebase-ios-sdk/files/3052078/appDsyms.zip)

**Comment by morganchen12** [comment]
Can you upload a stack trace for the crash?

**Comment by shrekShih** [comment]
I have attached the dsYM file in the attachment.

**Comment by morganchen12** [comment]
Please include the log output of the crashing session, including the exception message.

**Comment by shrekShih** [comment]
I was not able to reproduce under debug mode, will try and report back.

**Comment by shrekShih** [comment]
2019-04-10 16:49:43.379212-0700 Lexi
<img width="1680" alt="Screen Shot 2019-04-10 at 4 49 37 PM" src="https://user-images.githubusercontent.com/4226543/55921236-c6d91d00-5bb0-11e9-9e9a-e4f0a8b1dd7b.png">
[880:1283054] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'One of IDToken, accessToken, pendingToken, or requestURI must be supplied.'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000113f366fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000112950ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000113f36555 +[NSException raise:format:] + 197
	3   Lexi                                0x000000010d2b9793 -[FIRVerifyAssertionRequest unencodedHTTPRequestBodyWithError:] + 723
	4   Lexi                                0x000000010d284fb6 -[FIRAuthBackendRPCImplementation postWithRequest:response:callback:] + 182
	5   Lexi                                0x000000010d28330a -[FIRAuthBackendRPCImplementation verifyAssertion:callback:] + 282
	6   Lexi                                0x000000010d2818cb +[FIRAuthBackend verifyAssertion:callback:] + 123
	7   Lexi                                0x000000010d26f729 -[FIRAuth internalSignInAndRetrieveDataWithCredential:isReauthentication:callback:] + 2057
	8   Lexi                                0x000000010d26ed30 __58-[FIRAuth signInAndRetrieveDataWithCredential:completion:]_block_invoke + 112
	9   libdispatch.dylib                   0x00000001149e2d7f _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x00000001149e3db5 _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x00000001149eb225 _dispatch_lane_serial_drain + 778
	12  libdispatch.dylib                   0x00000001149ebe9c _dispatch_lane_invoke + 425
	13  libdispatch.dylib                   0x00000001149f5ea3 _dispatch_workloop_worker_thread + 733
	14  libsystem_pthread.dylib             0x0000000114dc060b _pthread_wqthread + 409
	15  libsystem_pthread.dylib             0x0000000114dc0405 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by shrekShih** [comment]
Sorry my bad, closing this issue. I realized we have log out user programmatically when user comes back to the screen.
