### ISSUE TITLE
Assertion failure in -[FSTSerializerBeta encodedMutation:]

### ISSUE THREAD

**Issue by nlhien** [firebase/firebase-ios-sdk#2753]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2
  * Firebase SDK version: 5.4.1
  * Firebase Component: Firestore
  * Component version: 1.2.1

### [REQUIRED] Step 3: Describe the problem
`*** Assertion failure in -[FSTSerializerBeta encodedMutation:]() *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'FIRESTORE INTERNAL ASSERTION FAILED: Unknown mutation type FSTSetMutation'`

#### Steps to reproduce:
1. Create a new Cocoa Touch Framework and implement the code below.
2. From the Application project, import the framework and call the API to execute the code.

#### Relevant Code:

```
let bundle: Bundle = Bundle(identifier: "com.example.FS")!
let filePath = bundle.path(forResource: "GoogleService-Info", ofType: "plist")

guard let fileopts = FirebaseOptions(contentsOfFile: filePath!)
    else { assert(false, "Couldn't load config file") }

FirebaseApp.configure(name: FRAMEWORK_APP, options: fileopts)

// Retrieve a previous created named app.
guard let APP = FirebaseApp.app(name: FRAMEWORK_APP)
    else { assert(false, "Could not retrieve APP") }

Firestore.firestore(app: APP).collection("test").addDocument(data: [
    "key1": "value 1",
])
```

**Comment by paulb777** [comment]
FirebaseFirestore and all Firebase CocoaPods are built as static library frameworks. Therefore they are not supported to be linked into a dynamic framework. Any framework that depends upon Firebase must also be static.

**Comment by wilhuff** [comment]
The issue in this specific case is that you're loading two copies of the `FSTSetMutation` class and so you can end up with some instances not matching `-isKindOfClass:[FSTSetMutation class]`.

There should have been warnings at startup (from the Objective-C run-time) about duplicate classes.
