### ISSUE TITLE
Remove deprecated FDL methods

### ISSUE THREAD

**Issue by ryanwilson** [firebase/firebase-ios-sdk#2760]
https://github.com/firebase/firebase-ios-sdk/blob/da3c019f8e5954bc727a379ce3cb1ef41f546cda/Firebase/DynamicLinks/Public/FDLURLComponents.h#L520

and

https://github.com/firebase/firebase-ios-sdk/blob/da3c019f8e5954bc727a379ce3cb1ef41f546cda/Firebase/DynamicLinks/Public/FDLURLComponents.h#L536

**Comment by dmandar** [comment]
Fixed: https://github.com/firebase/firebase-ios-sdk/pull/2768
