### ISSUE TITLE
Standardize on GoogleUtilities Swizzler - improvements

### ISSUE THREAD

**Issue by maksymmalyhin** [firebase/firebase-ios-sdk#2766]
Caused by #2591

There are several improvements related to using GoogleUtilities Swizzler:
- Messaging: update swizzling of UNUserNotificationCenter
- GULAppDelegateSwizzler - add macOS support (#2706)
- Use private header in tests instead of [this](https://github.com/firebase/firebase-ios-sdk/blob/cd507af5590bb3eb1be5341b8a0f616202fe542d/Example/Messaging/Tests/FIRMessagingRemoteNotificationsProxyTest.m#L125)

**Comment by ryanwilson** [comment]
Most of the cleanup is done. Due to issues with swizzling with SwiftUI, consider moving away from swizzling where we can and investigate alternate approaches.
