### ISSUE TITLE
DataMatrix barcode not recognized

### ISSUE THREAD

**Issue by skogsbaer** [firebase/firebase-ios-sdk#2823]
### Environment

  * Xcode version: 10.2
  * Firebase SDK version: 5.4.1 (FirebaseCore
  * Firebase Component: FirebaseMLCommon
  * Component version: 0.15.0

### Problem

I'm following closely the instructions in the documentation to scan DataMatrix barcodes.

    FIRVisionBarcodeDetectorOptions *options =
        [[FIRVisionBarcodeDetectorOptions alloc]
         initWithFormats: FIRVisionBarcodeFormatDataMatrix];
    FIRVision *vision = [FIRVision vision];
    self.detector = [vision barcodeDetectorWithOptions:options];

     // and later
    UIImage *img = [UIImage imageWithCGImage:cgImage];
    FIRVisionImage *vImg = [[FIRVisionImage alloc] initWithImage:img];
    [self.detector detectInImage:vImg completion:^(NSArray<FIRVisionBarcode *> *barcodes,
                                                   NSError *error)
    {
        if (error != nil) {
            return;
        } else if (barcodes != nil) {
            for (FIRVisionBarcode *barcode in barcodes) {
                NSString *displayValue = barcode.displayValue;
                FRNote(@"Firebase detected barcode %@", displayValue);
            }
        }
    }

With this code, I'm able to scan DataMatrix barcodes from time to time, but the scanning works very unreliable. For example, here is an image where the ML kit does not recognize the barcode:

![CaptureImageIPhone](https://user-images.githubusercontent.com/567524/56057764-f24e3a00-5d5f-11e9-8ce4-fee146d96ecc.jpg)

For me, the image looks good and I do not know what to improve.

**Comment by paulb777** [comment]
Internally tracked at b/130734326

**Comment by skogsbaer** [comment]
Is there any progress on this issue?

**Comment by morganchen12** [comment]
Sorry for the long wait, this issue should be fixed in the latest Firebase release. Please re-open if it regresses.

Thanks for reporting!

**Comment by morganchen12** [comment]
Sorry for the slow update, this fix was released some time ago.
