### ISSUE TITLE
Installation not being verified in the console (macOS)

### ISSUE THREAD

**Issue by sebastiaanweytjens** [firebase/firebase-ios-sdk#2838]
Environment:

  * Xcode version: 10.1
  * Firebase Component: Core
  * Component version: 5.4.1

I have a project with 3 targets: 1 for iOS, 1 for WatchOS and 1 for OSX.
I added a GoogleService-Info.plist file to the iOS target and one to the OSX target. 

Problem description:

I tried adding my OSX app to Firebase. But the last step in the process (Checking for communication between servers) just keeps loading.

1. Installed the pod FirebaseCore.
2. In AppDelegate.swift
`import FirebaseCore`
3. In applicationDidFinishLaunching(_ aNotification: Notification)
`FirebaseApp.configure()`

**Comment by ryanwilson** [comment]
@sebastiaanweytjens thanks for the feedback! This is a known issue - that functionality depends on a call from FirebaseAnalytics which isn't compatible with macOS at the moment. The rest of your SDK should work as expected but you may see that red dot beside your project for a long time :(

**Comment by paulb777** [comment]
@ryanwilson Presumably iOS apps that don't include FirebaseAnalytics have the same issue? Please add the internal bug number for the console issue here.
