### ISSUE TITLE
Getting framework(MLVision/MLVisionTextModel) not found issue when Integration firebase SDKs without using Cocoa pods

### ISSUE THREAD

**Issue by dineshsharmaskycore** [firebase/firebase-ios-sdk#2848]
Hi,
**I am working on integration firebase ML vision kit without using the cocoa pods:**
I am getting below error when adding SDK frameworks(MLVision and MLVisionTextModel) in app :
    `ld: symbol(s) not found for architecture x86_64`
    `clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Point 1:** 
My steps as I followed in app to integrate these SDK's framework :
1. Downloaded firebase SDK 5.20.2.
2. Followed the steps as defined inside the Readme.md file. 
First, I added all framework from 'Analytics' directory into project navigator pane and do same thing for Firebase.h file. 
Added the -ObjC flag to "Other Linker Settings
In AppDelegate.m , I add `#import "Firebase.h"` and   `[FIRApp configure];`. 

      Project build successfully without any error.

3. For text recognition, I added  MLVision and MLVisionTextModel in app as defined the step 5 in Readme.md for require framework and resource. 
**When I build this project I am getting below error in app:**

`Undefined symbols for architecture x86_64:`
  `"std::__1::basic_iostream<char, std::__1::char_traits<char> >::~basic_iostream()", referenced from:
      l59875 in TextDetector`
  `"typeinfo for std::__1::basic_iostream<char, std::__1::char_traits<char> >", referenced from:
      l59875 in TextDetector`
   `ld: symbol(s) not found for architecture x86_64`
    `clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Point 2:** 
Sometimes I was trying same thing adding SDK's framework by 'Link Binaries With Libraries' in Build Phases for Analytics, MLVision and MLVisionTextModel.

I was getting below error as

`ld: framework not found FirebaseMLVisionTextModel`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Note:** The framework FirebaseMLVisionTextModel doesn't have FirebaseMLVisionTextModel.h file. It doesn't exist header folder which is missing in FirebaseMLVisionTextModel framework:
I am getting same issue for TextDetector.framework which doesn't have any header folder.

Firebase.h : FirebaseMLVisionTextModel.h file deceleration:

```
#if __has_include(<FirebaseMLVisionTextModel/FirebaseMLVisionTextModel.h>)
#import <FirebaseMLVisionTextModel/FirebaseMLVisionTextModel.h>
#endif
```

**Pls suggest how do I fix this problem.
How do I use FirebaseMLVisionTextModel and TextDetector framework which are doesn't have any header , these framework only exec file?**

Xcode version: 10.1
Firebase SDK version: 5.20.2
Firebase Component: ML Kit (text recognition)
Component version:

**Comment by paulb777** [comment]
Internally tracked at b/130735001

**Comment by dineshsharmaskycore** [comment]
Hi @paulb777 ,
I didn't understand  your comment as you posted that 'Internally tracked at b/130735001' .
Please share link or provide your suggestion on issue.
Thanks

**Comment by paulb777** [comment]
@dineshsharmaskycore FirebaseML is not developed in this repository, so I added the issue to the bug tracking system that team uses and a reference here.

With the additional information you provided, I do have a suggestion now:

It looks like the system C++ libraries are not being linked.  That can happen with an incorrect Xcode module cache.  Do `rm -rf ~/Library/Developer/Xcode/DerivedData` to reset. If that doesn't work, see https://github.com/firebase/firebase-ios-sdk/issues/911#issuecomment-372675694

**Comment by dineshsharmaskycore** [comment]
Thanks @paulb777 
Its working after adding the C++ libraries.
One point pls let me know that which repository has developed FirebaseML so I can use in my app, please share link to me.

**Comment by paulb777** [comment]
@dineshsharmaskycore I'm glad to hear that it's working. FirebaseML is not currently developed in a publicly visible repository.
