### ISSUE TITLE
Error installing Firebase - curl (77) error

### ISSUE THREAD

**Issue by gemix95** [firebase/firebase-ios-sdk#2849]
* Xcode version: 10.2
  * Firebase SDK version: 5.7.0
  * Firebase Component: Auth, Core, Database, Messaging
  * Component version: 5.7.0

Hello to everyone, I'm having a problem installing and updating the Firebase pod in my project, once I do **pod install** or **pod updated** this is the output I receive.
What can be the problem ?

[!] Error installing Firebase
[!] /usr/bin/curl -f -L -o /var/folders/j6/lmbp5v993fj8r_k4tg21mrqm0000gn/T/d20190417-98318-1r5e1js/file.tgz https://dl.google.com/dl/cpdc/b436813e8becca75/Firebase-5.20.2.tar.gz --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
**curl: (77) error** setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none

**Comment by alessioarsuffi** [comment]
I'm having the same error too. Any updates?

**Comment by gemix95** [comment]
I solved in that way:

**Solution**: This error message indicates that curl is not able to establish a secure connection using openssl. A reinstall of openssl should fix the problem. To temporarily make use of an insecure connection for both curl and git to download any necessary files, run:

```
echo insecure >> ~/.curlrc
git config --global http.sslVerify false
```
Then, install or reinstall openssl and curl:

`HOMEBREW_CURLRC=1 brew reinstall openssl curl`

Finally, undo the security changes to make curl and git use secure connections again:

```
sed -i '/^insecure$/d' ~/.curlrc
git config --global http.sslVerify true
```
