### ISSUE TITLE
Long Dynamic Link Invalid with Missing Slash (App Store)

### ISSUE THREAD

**Issue by Averylamp** [firebase/firebase-ios-sdk#2866]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2.1 
  * Firebase SDK version: 
Firebase/Core (5.20.1):
Firebase/Auth (5.20.1):
  * Firebase Component: DynamicLinks
  * Component version: Firebase/DynamicLinks (5.20.1):

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Creating a redirect url, with a deep link, with the behavior to open the App Store page for the app if the app is not installed, with the app preview page enabled, the preview page redirects to an invalid url.  

Looking into the long dynamic link generated, it is 
`https://getpear.com/go?link=https://getpear.com&isi=1454832133&ibi=com.getpear.pear`, which does not escape properly as the dynamic link prefix is `https://getpear.com/go/`, whereas the long dynamic link generated is missing the slash before the `?`.  Adding the slash in manually does correctly redirect to the expected App Store page.

#### Relevant Code:

```
firebase.json config file
{
  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint"
    ]
  },
  "hosting": {
    "public": "build",
    "appAssociation": "AUTO",
    "rewrites": [ { "source": "/go/**", "dynamicLinks": true },
                  { "source": "/event/**", "dynamicLinks": true },
                  { "source": "/group/**", "dynamicLinks": true },
                  { "source": "/promo/**", "dynamicLinks": true },
                  { "source": "/tag/**", "dynamicLinks": true },
                  { "source": "/privacy-policy", "destination": "/index.html", "type": 301 },
                  { "source": "/terms-of-use", "destination": "/index.html", "type": 301 }
                ]
  }
}
```

**Comment by joelaguero** [comment]
Hi! I'm also experiencing this issue.

**Comment by dmandar** [comment]
Thanks for highlighting the issue. We are investigating a solution.

**Comment by dmandar** [comment]
Can you also enumerate what domain(s) you have added in your info.plist file?

**Comment by Averylamp** [comment]
This is not an issue on the iOS side, but it occurs on the web side when the app has not already been downloaded

**Comment by joelaguero** [comment]
Just curious - are there any updates on this issue? It is significantly hindering our ability to do referral codes/unique links for growth. Thanks!

**Comment by joelaguero** [comment]
Sorry, this actually appears to be resolved now. There is no longer a missing slash.

**Comment by morganchen12** [comment]
Thanks all, if anyone is still running into this issue, please comment here and I'll reopen it.
