### ISSUE TITLE
Getting frameworks(GoogleMobileVision/FirebaseMLCommon) issue when integrate firebase SDK without using Cocoa pods

### ISSUE THREAD

**Issue by dineshsharmaskycore** [firebase/firebase-ios-sdk#2873]
Hi,
Getting below error when adding firebase SDK in app:

> Undefined symbols for architecture x86_64:
"_OBJC_CLASS_$_LAContext", referenced from:
objc-class-ref in FirebaseMLCommon(MDMPasscodeCache_ac345e06741a76a3aefe61adde149175.o)
objc-class-ref in GoogleMobileVision
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Xcode version: 10.1
Firebase SDK version: 5.20.2
Firebase Component: ML Kit (text recognition)
Component version:

Any help is appreciated. Thanks

**Comment by paulb777** [comment]
Same answer as https://github.com/firebase/firebase-ios-sdk/issues/2848#issuecomment-484511022 except add LocalAuthentication.framework instead of libc++ to the Link Binary with Libraries Build Phase.

**Comment by dineshsharmaskycore** [comment]
Hi @paulb777,
Thanks for support. It's working.
