### ISSUE TITLE
GoogleAppMeasurement 5.8.1    obfuscated code reject

### ISSUE THREAD

**Issue by githhhh** [firebase/firebase-ios-sdk#2874]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: _____
  * Firebase SDK version: _____
  * Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulb777** [comment]
Please provide more context and information about the issue.

**Comment by githhhh** [comment]
Two apps were released last week, and GoogleAppMeasurement 5.8.1 was updated and rejected.  The previous version relied on 5.8.0 is normal.

**Comment by paulb777** [comment]
Will you share the exact error message? How do you know that the problem came from GoogleAppMeasurement?

Does going back to GoogleAppMeasurement resolve the issue?

`pod 'GoogleAppMeasurement',  '5.8.0'`

**Comment by mbanasiewicz** [comment]
I guess what @githhhh tries to say is that apps are getting rejected by Apple due to obfuscated code.
This is the message people get https://twitter.com/steipete/status/1088443539065720832

**Comment by paulb777** [comment]
@mbanasiewicz That twitter message does not identify the offending pod
