### ISSUE TITLE
Problem while connecting Auth with Firebase

### ISSUE THREAD

**Issue by Gfuentes99** [firebase/firebase-ios-sdk#2875]
+
  * Xcode version: 10.1
  * Firebase SDK version: 5.20
  * Firebase Component: Auth, Core
  * Component version: Most recent

### [REQUIRED] Step 3: Describe the problem

In several times, I have tried to make a login app with Firebase and Swift and I'm a beginner in this so I think it was my fault but after some failed projects, I decided to make a simple one with a button that makes all the time the same user and the user still doesnt appear in my Firebase project so it's make nothing, this is my log after pushing the button

`2019-04-20 18:34:33.305062+0200 ProyectoJuegos[71889:3275296] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C5.1:2][0x7fbb87d13680] get output frames failed, state 8196
2019-04-20 18:34:33.305247+0200 ProyectoJuegos[71889:3275296] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C5.1:2][0x7fbb87d13680] get output frames failed, state 8196
2019-04-20 18:34:33.306162+0200 ProyectoJuegos[71889:3275296] TIC Read Status [5:0x0]: 1:57
2019-04-20 18:34:33.306404+0200 ProyectoJuegos[71889:3275296] TIC Read Status [5:0x0]: 1:57
`

I think the first 2 logs make the error its like it can't communicate with the server I have read sometimes in post but never seen a real solution, so please I would be very grateful if you can say what can be wrong? The app connects to firebase in a good way while I configure it.

#### Relevant Code:

`import UIKit
import FirebaseAuth
class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
    }

    @IBAction func p(_ sender: Any) {
        Auth.auth().createUser(withEmail: "aaa@gmail.com", password: "aaaa")
        
    }
    
}
`

**Comment by paulb777** [comment]
The logs are not helpful in diagnosing - they're not Firebase related. See https://github.com/firebase/firebase-ios-sdk/issues/2188#issuecomment-467115665.

You might want to work through the Auth quickstart example at https://github.com/firebase/quickstart-ios/tree/master/authentication

**Comment by Gfuentes99** [comment]
> The logs are not helpful in diagnosing - they're not Firebase related. See [#2188 (comment)](https://github.com/firebase/firebase-ios-sdk/issues/2188#issuecomment-467115665).
> 
> You might want to work through the Auth quickstart example at https://github.com/firebase/quickstart-ios/tree/master/authentication

I have seen this post yet, but it can be the error?

**Comment by Gfuentes99** [comment]
> The logs are not helpful in diagnosing - they're not Firebase related. See [#2188 (comment)](https://github.com/firebase/firebase-ios-sdk/issues/2188#issuecomment-467115665).
> 
> You might want to work through the Auth quickstart example at https://github.com/firebase/quickstart-ios/tree/master/authentication

Can i download the project in that link?

**Comment by morganchen12** [comment]
The log posted cannot be the error. You can (and should) download the linked project and try running it.
