### ISSUE TITLE
Cleanup GoogleUtilities iOS 6 compatibility conditions

### ISSUE THREAD

**Issue by maksymmalyhin** [firebase/firebase-ios-sdk#2881]
Cleanup conditions like [#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 70000](https://github.com/firebase/firebase-ios-sdk/blob/ec92f243e84ec42abf6c1e5932e0cb6693e93ceb/GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m#L59) from the source code and the tests.

Caused by #2876

**Comment by paulb777** [comment]
Adding to Firebase 7 milestone for evaluation.
