### ISSUE TITLE
GULAppEnvironmentUtil.h is private in headers of GoogleUtilities

### ISSUE THREAD

**Issue by nikolaytw** [firebase/firebase-ios-sdk#2887]
### [READ] Step 1: Are you in the right place?
YES

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: Version 10.2 (10E125)
  * Firebase SDK version: 5.20.2
  * Firebase Component: Core, GoogleUtilities/Environment
  * Component version:  "FirebaseCore": "5.4.1", GoogleUtilities: "5.7.0"

### [REQUIRED] Step 3: Describe the problem

Here is podspec file: 
https://github.com/firebase/firebase-ios-sdk/blob/master/GoogleUtilities.podspec
Line 29 and 30:
```
    es.public_header_files = 'GoogleUtilities/Environment/third_party/*.h'
    es.private_header_files = 'GoogleUtilities/Environment/third_party/*.h'
```
You actually adding the same file to private and to public. And for me they were resolved to private, which means this line
```
#import <GoogleUtilities/GULAppEnvironmentUtil.h>
```
in file: https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/Core/FIRLogger.m
can't work. And this actually breaking my build atm.

#### Steps to reproduce:

1. Create project with Firebase dependencies in podfile
2. Pod install
2. Open in xcode 10.2
3. Search for GULAppEnvironmentUtil.h file 

Expected result: should be marked as public in xcode inspector
Actual result: it is private, which means, no copy to public headers and no availability outside of GoogleUtilities

**Comment by paulb777** [comment]
In CocoaPods and Xcode, private headers are available via the module map. Internal headers have no availability outside their module.

See the [instructions in this repo](./Pods/Target Support Files/GoogleUtilities-iOS/GoogleUtilities-iOS.modulemap) for examples.

if you're still having problems, please share your Xcode version, CocoaPods version, and a reproducible example.

**Comment by paulb777** [comment]
See the podspec docs at https://guides.cocoapods.org/syntax/podspec.html#private_header_files - private headers should be specified in BOTH the public_header_files and private_header_files attributes:

"private_header_files
A list of file patterns that should be used to mark private headers.

These patterns are matched against the public headers (or all the headers if no public headers have been specified) to exclude those headers which should not be exposed to the user project and which should not be used to generate the documentation. When the library is built, these headers will appear in the build directory.

Header files that are not listed as neither public nor private will be treated as private, but in addition will not appear in the build directory at all."

I agree about CocoaPods/CocoaPods#8206 being an ugly bug, but the workaround of adding the multiple subspec subset to the relevant targets in the Podfile is relatively straight-forward.

**Comment by nikolaytw** [comment]
@paulb777 thanks for your help 👏  . After I worked around pods bug, it appears that issue with header was because of double framework, header search happened in framework(duplicate), which I manually removed in post pods step. So I will close it.
