### ISSUE TITLE
Crash in `APMParseVersion` (rare)

### ISSUE THREAD

**Issue by aleh** [firebase/firebase-ios-sdk#2889]
### [READ] Step 1: Are you in the right place?

Yes, a crash in a component in this repo.

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.1 (10B61)
  * Firebase SDK version: 5.5.0
  * Firebase Component: FirebaseAnalytics
  * Component version: 5.1.0

  * iOS: 12.2.0 (16E227)
  * iPhone 6 Plus

### [REQUIRED] Step 3: Describe the problem

We have a rare crash in `APMParseVersion` which happened multiple times for a single user lately. It seems to be vaguely related to the one we reported earlier: https://github.com/firebase/firebase-ios-sdk/issues/2304

#### Steps to reproduce:

According to our logs the user has successfully signed in with Firebase anonymously and started getting some updates from Firestore documents. Shortly after that the app has crashed.

#### Stack Trace:

```
EXC_BAD_INSTRUCTION 0x0000000001f72c84

Crashed: com.google.fira.worker
0  <redacted>                     0x100ee8c38 APMParseVersion + 1422188
1  <redacted>                     0x100eb91ec -[APMMeasurement reportFirstOpenOnWorkerQueue] + 1227040
2  <redacted>                     0x100eb8834 __47-[APMMeasurement startMeasurementOnWorkerQueue]_block_invoke + 1224552
3  libdispatch.dylib              0x19cf3d7d4 _dispatch_client_callout + 16
4  libdispatch.dylib              0x19cee0eb4 _dispatch_once_callout + 28
5  <redacted>                     0x100eb8084 -[APMMeasurement startMeasurementOnWorkerQueue] + 1222584
6  <redacted>                     0x100eb7bf4 -[APMMeasurement setEnabledOnWorkerQueue:] + 1221416
7  <redacted>                     0x100ed08ec __51-[APMScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke + 1323040
8  libdispatch.dylib              0x19cf3ca38 _dispatch_call_block_and_release + 24
9  libdispatch.dylib              0x19cf3d7d4 _dispatch_client_callout + 16
10 libdispatch.dylib              0x19cee6320 _dispatch_lane_serial_drain$VARIANT$mp + 592
11 libdispatch.dylib              0x19cee6e3c _dispatch_lane_invoke$VARIANT$mp + 428
12 libdispatch.dylib              0x19ceef4a8 _dispatch_workloop_worker_thread + 596
13 libsystem_pthread.dylib        0x19d11d114 _pthread_wqthread + 304
14 libsystem_pthread.dylib        0x19d11fcd4 start_wqthread + 4
```

**Comment by paulb777** [comment]
@aleh Thanks for the report. Your Firebase version is from July 2018.  Does updating to a more recent version make a difference?

**Comment by aleh** [comment]
@paulb777 Oh, I thought I've updated it recently :) Will try, thanks!
