### ISSUE TITLE
ABTExperimentsToSetFromPayloads crash

### ISSUE THREAD

**Issue by simonbengtsson** [firebase/firebase-ios-sdk#2894]
Our most common crash now is a a crash in what seems to be something related to remote config. In crashlytics its title is `ABTExperimentsToSetFromPayloads` and this is the message:

```
Fatal Exception: NSGenericException
*** Collection <__NSArrayM: 0x281ca66d0> was mutated while being enumerated.
ABTExperimentsToSetFromPayloads
```

We are unable to reproduce it ourselves, but the crash happens just after users start the app according to our logs. We sometimes get a few logs such as `session_started` so its most likely not at the very start, but just after it. There seems to be no pattern of iOS version or device type etc. 

The first crash I can find regarding this was with the firebase sdk `5.2.1`. But could have started before that version as well. We are seeing this crash more frequently now, but most likely related to more users on our platform.

### Stacktrace
```
Fatal Exception: NSGenericException
0  CoreFoundation                 0x2251d4518 __exceptionPreprocess
1  libobjc.A.dylib                0x2243af9f8 objc_exception_throw
2  CoreFoundation                 0x2251d3de0 -[__NSSingleObjectEnumerator initWithObject:]
3  Equilab                        0x10325946c ABTExperimentsToSetFromPayloads
4  Equilab                        0x103259c54 -[FIRExperimentController updateExperimentsInBackgroundQueueWithServiceOrigin:events:policy:lastStartTime:payloads:]
5  Equilab                        0x103259b14 __99-[FIRExperimentController updateExperimentsWithServiceOrigin:events:policy:lastStartTime:payloads:]_block_invoke
6  libdispatch.dylib              0x224c14a38 _dispatch_call_block_and_release
7  libdispatch.dylib              0x224c157d4 _dispatch_client_callout
8  libdispatch.dylib              0x224bf8afc _dispatch_root_queue_drain
9  libdispatch.dylib              0x224bf9248 _dispatch_worker_thread2
10 libsystem_pthread.dylib        0x224df51b4 _pthread_wqthread
11 libsystem_pthread.dylib        0x224df7cd4 start_wqthrea
```

### Environment

  * Xcode version: 10.2
  * Firebase SDK version: 5.20.2
  * Firebase Component: Remote config? Not sure which component it is.
  * Component version: N/A But we are running latest version of all components under main lib version 5.20.2.

**Comment by morganchen12** [comment]
A fix for this has been submitted internally and will be released in the next next release. Patch number is cr/252846485.
