### ISSUE TITLE
iOS Push Notifications not working

### ISSUE THREAD

**Issue by harjotsingh007** [firebase/firebase-ios-sdk#2895]
Xcode 10.2.1
Firebase (5.20.2)
FirebaseAnalytics (5.8.1)
FirebaseAnalyticsInterop (1.2.0)
FirebaseCore (5.4.1)
FirebaseInstanceID (3.8.1)
FirebaseMessaging (3.5.0)

Push notifications not working on iOS at all, tried many things with mulitple demo projects. FCM token is coming in the console. Tried with send message push notification multiple times.

```
FirebaseApp.configure()
        Messaging.messaging().delegate = self

        if #available(iOS 10.0, *) {
            let center = UNUserNotificationCenter.current()
            center.delegate = self
            center.requestAuthorization(options: [.badge, .alert, .sound]) {
                (granted, error) in
                if granted {
                    DispatchQueue.main.async {
                        application.registerForRemoteNotifications()
                        //UIApplication.shared.registerForRemoteNotifications()
                    }
                } else {
                    //print("APNS Registration failed")
                    //print("Error: \(String(describing: error?.localizedDescription))")
                }
            }
        } else {
            let type: UIUserNotificationType = [UIUserNotificationType.badge, UIUserNotificationType.alert, UIUserNotificationType.sound]
            let setting = UIUserNotificationSettings(types: type, categories: nil)
            application.registerUserNotificationSettings(setting)
            application.registerForRemoteNotifications()
            //UIApplication.shared.registerForRemoteNotifications()
        }

```

```
@available(iOS 10, *)
extension AppDelegate : UNUserNotificationCenterDelegate {
    
    // Receive displayed notifications for iOS 10 devices.
    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                willPresent notification: UNNotification,
                                withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
        let userInfo = notification.request.content.userInfo
        
        // With swizzling disabled you must let Messaging know about the message, for Analytics
        // Messaging.messaging().appDidReceiveMessage(userInfo)
        
        // Print message ID.
        if let messageID = userInfo["gcm.message_id"] {
            print("Message ID: \(messageID)")
        }
        
        // Print full message.
        print(userInfo)
        
        // Change this to your preferred presentation option
        completionHandler([.alert])
    }
    
    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                didReceive response: UNNotificationResponse,
                                withCompletionHandler completionHandler: @escaping () -> Void) {
        let userInfo = response.notification.request.content.userInfo
        // Print message ID.
        if let messageID = userInfo["gcm.message_id"] {
            print("Message ID: \(messageID)")
        }
        
        // Print full message.
        print(userInfo)
        
        completionHandler()
    }
}
```

Note:

- I have tried it on real device no push notifications so far.
- I have double checked the certificates and regenerated the provisioning file after turning on the push notifications in capabilities.
- I have also added background modes -> remote notifications on.
- I have tried with legacy build also no luck.
- I have tried reinstalling apps many times not working.
- FirebaseAppDelegateProxyEnabled is set to NO in plist still no luck.
- Also updated the pods still no luck.
- .p12 certificate is at the firebase console, still not working.

**Comment by morganchen12** [comment]
@harjotsingh007 are you able to send directly through APNs?

**Comment by chliangGoogle** [comment]
Have you tried using sender API or just console? Does any of those return any error when trying to send push notification?

**Comment by harjotsingh007** [comment]
@morganchen Yes i have tried not working, i am not receiving notifications at all.

@chliangGoogle Yes i have tried everything console as well as backend to send push notifications, still no luck.

**Comment by morganchen12** [comment]
If your sends are failing through APNs, it means you've misconfigured push notifications. FCM uses APNs to send remote notifications on iOS. If APNs isn't set up correctly, FCM will not be able to send remote notifications.

**Comment by harjotsingh007** [comment]
@morganchen12 sorry i have not tried with APNs, but the APNs is configured correctly, we are sending the push notifications through FCM token but not going through. I tried every possible method, can you share link for sending directly through APNs.

**Comment by itumeleng-mabote** [comment]
Here is the curl for APN 
`curl --http2 --cert ./myapp-push-cert.pem \
-H "apns-topic: com.example.yourapp.bundleID" \
-d '{"aps":{"alert":"Hello from APNs!","sound":"default"}}' \
https://api.development.push.apple.com/3/device/ab8293ad24537c838539ba23457183bfed334193518edf258385266422013ac0d`

You can read more at this link https://firebase.googleblog.com/2017/01/debugging-firebase-cloud-messaging-on.html

**Comment by harjotsingh007** [comment]
hi @itumeleng-mabote  thanks i have tried with APN directly the notification is working but now i have changed the FirebaseAppDelegateProxyEnabled to YES in plist, notifications started working strangely because the fcm token is being uploaded to the firebase servers.

When the FirebaseAppDelegateProxyEnabled is set to NO, instance ID will generate the fcm token locally before uploading it to server so i think in my it is not syncing with server the fcm token, i have implemented all possible methods and delegate also still no success manually, so i guess i have to swizzle the methods to get the notification.

**Comment by morganchen12** [comment]
Looks like you (most likely) forgot to manually set the APNs token with swizzling disabled.

**Comment by harjotsingh007** [comment]
@morganchen12 I did set the APNS token to messaging still the method was not getting called here how i have added.

```
    private func application(application: UIApplication,
                     didRegisterForRemoteNotificationsWithDeviceToken deviceToken: NSData) {
        
        Messaging.messaging().apnsToken = deviceToken as Data
        let deviceTokenString = deviceToken.hexString
        UserDefaults.standard.setValue(deviceTokenString, forKey: self.globalR.devicetoken)
        print("Registered Notification")

    }
```
