### ISSUE TITLE
InAppMessaging - Not working

### ISSUE THREAD

**Issue by MWessel27** [firebase/firebase-ios-sdk#2899]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Describe your environment

*Xcode version: 10.1
*Firebase SDK version: 5.20.0
*Firebase Component: InAppMessaging
*Component version: 5.20.0

### [REQUIRED] Step 3: Describe the problem

On a brand new XCode project, InAppMessaging campaigns are not working on simulator or device. Analytics are working just fine and no errors are reported. I am even seeing messages in the queue (mentioned in logs) but they never appear on screen.

#### Steps to reproduce:

1. Create brand new xcode project
2. Connect to Firebase and include analytics as well as InAppMessaging
3. Configure Firebase as appropriate for project
4. Create InAppMessaging Campaign and Select "Test"
5. Get the instance ID for simulator or physical device from the console
6. Hit test on device

Analytics will work correctly, no errors in console or log, no InAppMessage will ever be shown.

**Comment by MWessel27** [comment]
This issue is occurring and reproducible on any test project as well as an App that I have on the app store.

**Comment by christibbs** [comment]
For testing on device: you may have to background and foreground the app to see the message. Could you try that?

For the published App Store app: what's the trigger type? (Foreground, app launch, etc.)

**Comment by MWessel27** [comment]
Hi @christibbs, appreciate your response. I wrote out a very detailed summary of what was happening with screenshots walking through the setup step-by-step.

**Strangely**, everything worked! 

I have one last question because this could be a bug. If the image included in the modal InAppMessage cannot resolve/is not at that URL, will the Modal not appear at all?

**Comment by christibbs** [comment]
@MWessel27 Funny how that always happens.

The modal won't appear in the case that the image fails to load. You should see an error message in your logs if that happens: `Error in loading image data for the message.`

**Comment by cruisediary** [comment]
Dear @christibbs 
I have a some question about FIAM.
**Q: Is there a FIAM no working scenario even though FCM working fine?**
Firebase Cloud Messaging use firebase token including `InstanceID`. so it means InstanceID is valid but FIAM is not working. It also same occur issue after updating latest SDK (6.10.0) but re-installing make it fine.

**Comment by christibbs** [comment]
@cruisediary FCM working should rule out any instance ID issues, but there could be something else. Could you try [adding the verbose debugging flag](https://firebase.google.com/docs/in-app-messaging/get-started#send_a_test_message) and searching for `[Firebase/InAppMessaging]` in the logs to see if there's a more specific error.
