### ISSUE TITLE
Firebase updateChildValues operation blocks other Firebase operations.

### ISSUE THREAD

**Issue by fawzirifai** [firebase/firebase-ios-sdk#2907]
* Xcode version: latest
  * Firebase SDK version: latest
  * Firebase Component: Database
  * Component version: latest

I'm using updateChildValues operation to update values for 500 students in the database, when I trigger it and try to trigger another Firebase operation like observe, the second operation (observe) will not performed and will keeps waiting until the first operation (updateChildValues) completes, which takes nearly 15 seconds.

This is my code for updateChildValues:

```
@IBAction func menu(_ sender: Any) {
        let storeRecord = UIAlertAction(title: "Store attendance record", style: .default) { action in
            var attendanceTimesDict = [String: Int]()
            var absenceTimesDict = [String: Int]()
            for student in self.students { // 500 students
                if self.attendanceRecord[student.identifier] == true {
                    student.attendanceCount += 1
                    attendanceTimesDict["\(student.identifier)/attendance"] = student.attendanceCount
                } else {
                    student.absenceCount += 1
                    absenceTimesDict["\(student.identifier)/absence"] = student.absenceCount
                }
            }
            Database.database().reference().child("class").child("CS101").child("records").child("27-4-2019").updateChildValues(self.attendanceRecord)
            Database.database().reference().child("class").child("CS101").child("students").updateChildValues(attendanceTimesDict)
            Database.database().reference().child("class").child("CS101").child("students").updateChildValues(absenceTimesDict)
        }
}
```

And this is my code for observe function:

```
func getStudentsList() {
        Database.database().reference().child("class").child("CS101").child("students").observeSingleEvent(of: .value) { snapshot in
            for child in snapshot.children.allObjects as! [DataSnapshot] {
                let studentObject = child.value as? [String: Any]
                if let name = studentObject?["name"] as? String {
                    let student = Student(identifier: child.key, name: name)
                    self.students.append(student)
                }
            }
          self.tableView.reloadData()
        }
}
```

**Comment by fawzirifai** [comment]
Nearly 2 days without any answer.

**Comment by paulb777** [comment]
@fawzirifai It's unlikely anyone will be available to investigate on a weekend.  Also, you may have better luck on stackoverflow, since this may be closer to a usability question and not necessarily a functionality issue or iOS specific.

If it is an iOS specific issue, all of the code is available if you'd like to debug yourself and send a PR.

**Comment by fawzirifai** [comment]
@paulb777 sorry for my rush, I forgot about the weekend.

**Comment by fawzirifai** [comment]
8 days without any answer!

**Comment by morganchen12** [comment]
Hey @fawzirifai, changing the order of listener updates/writes may be non-trivial and is unlikely to be addressed by the Firebase team soon. Have you considered using a [Cloud Function](https://firebase.google.com/docs/functions) instead of updating 500 records on the client?

**Comment by fawzirifai** [comment]
No I’m new to Firebase, so this is normal in Firebase that it takes 30 seconds to update 500 children and blocks other functions while it is updating?

**Comment by morganchen12** [comment]
RTDB operations are dependent on a number of factors, like the speed of your network and the speed of your device. It's very possible for 500 updates to take 15 seconds.
