### ISSUE TITLE
FCM & iOS - One Token for 2 different apps on same device

### ISSUE THREAD

**Issue by anilabsinc-ajay** [firebase/firebase-ios-sdk#2925]
We have multiple iOS apps under one single project in firebase, but in random case we are getting some device token (FCMToken) for different App, which is causing error with badge count for apps

**Comment by morganchen12** [comment]
@anilabsinc-ajay please file this at [Firebase support](https://firebase.google.com/support). They'll be able to look at the instance ID and tell you why the same ID was generated for both apps.
