### ISSUE TITLE
Remove `[FIRLibrary configureWithApp:]` calls.

### ISSUE THREAD

**Issue by ryanwilson** [firebase/firebase-ios-sdk#2933]
This structure made sense before when a notification was fired, but doesn't make sense in the current world. If SDKs need to know the instant an app is configured, they should use [`FIRInstantiationTimingAlwaysEager` or `FIRInstantiationTimingEagerInDefaultApp`](https://github.com/firebase/firebase-ios-sdk/blob/9ec1da028e92cdd3e32c07ba88e8ca6fa30b420f/Firebase/Core/Private/FIRComponent.h#L39) to be configured. This will prevent any singleton use in the `configureWithApp:` call and clean up testing as well. Note: all libraries (internal and external) will need to remove this call in order for it to be removed from `FIRLibrary`. 

The definition is found here:
https://github.com/firebase/firebase-ios-sdk/blob/9ec1da028e92cdd3e32c07ba88e8ca6fa30b420f/Firebase/Core/Private/FIRLibrary.h#L38

**Comment by paulb777** [comment]
Adding to be addressed in the Firebase 7 milestone.

**Comment by ryanwilson** [comment]
Delaying from Firebase 7 to avoid breaking downstream dependencies, specifically RN in the issue linked above.

**Comment by ryanwilson** [comment]
Moving to the next major version, will reach out to the RN folks to coordinate with larger lead time in the future.

**Comment by paulb777** [comment]
There is still a usage in FIAM at https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseInAppMessaging/Sources/FIRInAppMessaging.m#L71

**Comment by ryanwilson** [comment]
Punting again, will re-evaluate for next breaking change.

**Comment by paulb777** [comment]
Punting again, will re-evaluate for next breaking change.

**Comment by paulb777** [comment]
Looks like FIAM is the only client of configureWithApp and the old notification system.

**Comment by ncooke3** [comment]
@paulb777, do you recall the external clients that https://github.com/firebase/firebase-ios-sdk/pull/9394#issuecomment-1093342289 references?

**Comment by paulb777** [comment]
I believe it's only https://github.com/invertase/react-native-firebase/issues/4241

**Comment by mikehardy** [comment]
Just poking my head over here a moment to say that with a big assist from @ncooke3 on https://github.com/invertase/react-native-firebase/pull/7837 we will be good to go over in react-native-firebase - thanks for the patience

**Comment by ncooke3** [comment]
Marking closed via #13147.
