### ISSUE TITLE
After transferring of app, all push tokens in FCM are invalid and users have to reinstall app in order for push to work

### ISSUE THREAD

**Issue by JakobMaaloe** [firebase/firebase-ios-sdk#2934]
**[REQUIRED] Step 2: Describe your environment**
IOS app & Firebase Console

**[REQUIRED] Step 3: Describe the problem**

We are facing the same problem as described in issue 2125

We have just tried the following:
1. Reinstall the app on a device
2. Push message from our server to the FCM token -> The user receives the message
3. Change APN auth key to an old one
4. Change APN auth key back to the new one
5. Delete the FCM token on our server
6. App requests new FCM token on startup and receives the same FCM token as before it was deleted
7. Push message from our server to the FCM token -> The user doesn't receive the message

We have transferred the IOS app to a new account and now we can only push to our IOS users after the remove and install the app again.

Please, any advice on what to do will be greatly appreciated! Having to communicate to ALL IOS users that they have to reinstall their app is devastating!

Thanks in advance!

_Originally posted by @JakobMaaloe in https://github.com/firebase/firebase-ios-sdk/issues/2125#issuecomment-489226348_

**Comment by morganchen12** [comment]
Hey @JakobMaaloe, please file this [here](https://firebase.google.com/support?category=troubleshooting) so we can look at your Firebase project and instance IDs.

**Comment by JakobMaaloe** [comment]
Hi Morganchen12.

Support case has been created with the APNs (from apple console - I hope this can be used)

We've just tried the following:
1. Reinstall the app on a device
2. Push message from our server to the FCM token -> The user receives the message
3. Change APN auth key to an old one
4. Change APN auth key back to the new one
5. Delete the FCM token on our server
6. App requests new FCM token on startup and receives the same FCM token as before it was deleted
7. Push message from our server to the FCM token -> The user doesn't receive the message
One solution could be if we could force all users FCM token to refresh... Any way that's possible?
I can send you the APNS token from Apple console in a support ticket if you still need it.

We cannot update the production app unfortunately.

Thanks!

**Comment by JakobMaaloe** [comment]
Hi @morganchen12  ,

Any news on this?

Our users don't get push messages so it's vital for us to find a solution asap...

Br.
Jakob Maaløe

**Comment by morganchen12** [comment]
Hi @JakobMaaloe, the Firebase support team doesn't work on weekends. Normally, when the APNs key is changed or invalidated, the tokens on the client should invalidate and reset over a short period of time. The clients should then regenerate new tokens that work when sending notifications. We're looking into why this isn't happening as expected.

**Comment by JakobMaaloe** [comment]
Ok, thank you for the update. Fingers crossed that the invalidation can happen soon.

Br.
Jakob Maaløe

**Comment by JTJLabs** [comment]
@morganchen12 

Any news on this issue? 

Thanks.

Br.
Jakob Maaløe

**Comment by morganchen12** [comment]
Hi Jakob, please respond to the support email:

> Could you also share the debug logs when you switch Apple accounts on the console and Xcode certificates at the first time the app is re-opened after these APNs changes (and APNs token change) has occurred?

**Comment by JTJLabs** [comment]
Hi Morgan Chen,

Thx for getting back to me!

Unfortunately I'm not experienced in the Apple Development / publishing -
we have moved to the new account as the dedicated Apple developer exited
from the company.

How do I retrieve the debug logs and do you mean from within the app on the
phone, from the Apple console or from xcode?

Same question goes for the certificates.

In the meantime, could you invalidate the FCM tokens that haven't been
invalidated during the so our users have push messages working again?

Thanks.

Br.
Jakob Maaløe

Den ons. 15. maj 2019 kl. 17.59 skrev Morgan Chen <notifications@github.com

**Comment by morganchen12** [comment]
You can get the debug logs from Xcode console when running the app with the debugger attached. The certificates are generated from your Apple Developer account in the developer center.

**Comment by JakobMaaloe** [comment]
@morganchen12 
Responded with the log to firebase-help@google.com

Again, could you invalidate the FCM tokens that haven't been
invalidated during the so our users have push messages working again?

**Comment by morganchen12** [comment]
We're looking into it.

**Comment by JTJLabs** [comment]
Thanks! :-)

- Jakob Maaløe

**Comment by morganchen12** [comment]
Unfortunately, we can't manually invalidate all of your app's tokens. However, you can do this manually by shipping an update that [deletes the stored instance ID](https://firebase.google.com/docs/reference/ios/firebaseinstanceid/api/reference/Classes/FIRInstanceID#/c:objc(cs)FIRInstanceID(im)deleteIDWithHandler:) on first app launch.
