### ISSUE TITLE
Xcode linker failures with Firebase/Core pod

### ISSUE THREAD

**Issue by syvertsj** [firebase/firebase-ios-sdk#2946]
Xcode version: 10.1

Using the documented (from the firebase console) Firebase/Core or Firebase/Analytics pod I get linker error for FIRBundleUtil.o expected in FirebaseCore:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_GULAppEnvironmentUtil", referenced from:
      objc-class-ref in FirebaseCore(FIRBundleUtil.o)

```
The Firebase/Analytics pod wraps the GoogleAppMeasurement, FirebaseAnalytics, FirebaseCoreDiagnostics, and FIRAnalyticsConnector frameworks, all of which was linked.

I saw in another thread the "linker" (compiler) flag -fprofile-arcs providing a workaround.
This made no difference.

**Comment by paulb777** [comment]
The missing symbol should come from the GoogleUtilities framework.

If you'd like more assistance, please share your Podfile and Podfile.lock.

**Comment by syvertsj** [comment]
Thank you. 
I see a GoogleAppMeasurement folder and it has a frakework, and a GoogleUtilities folder, the latter which does not contain one. 

[podfiles.zip](https://github.com/firebase/firebase-ios-sdk/files/3149922/podfiles.zip)

**Comment by paulb777** [comment]
`GoogleUtilities` shows up in the attached `Podfile.lock`.

**Comment by syvertsj** [comment]
yes, but there is no framework under it. 

![Screen Shot 2019-05-06 at 5 45 11 PM](https://user-images.githubusercontent.com/1047505/57257197-bb99d580-7026-11e9-8930-752ca248e8d2.png)

**Comment by paulb777** [comment]
@syvertsj GoogleUtilities is a source CocoaPod (just like FirebaseCore) and should be built in the workspace.

**Comment by syvertsj** [comment]
I figured... what settings in Xcode needed to build GoogleUtilities?

**Comment by paulb777** [comment]
It should be automatic in CocoaPods since it's a dependency of Pods that are already being built. You could take a look at one of the [quickstarts](https://github.com/firebase/quickstart-ios/tree/master/analytics) and see what's different about your project.

**Comment by paulb777** [comment]
Closing for now. Will reopen on more info.
