### ISSUE TITLE
travis_retry does not work with Firestore emulator

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#2952]
travis_retry fails with the error `Firestore emulator already running as PID 5962`. See the bottom of https://travis-ci.org/firebase/firebase-ios-sdk/jobs/529126354.

Should `"${firestore_emulator}" stop` be called before `"${firestore_emulator}" start` in scripts/build.sh so that travis_restart will work?

**Comment by wilhuff** [comment]
I saw this while working on the the sanitizer failures. I have a fix in the works.
