### ISSUE TITLE
Getting Fatal Error on DynamicLinkComponents.

### ISSUE THREAD

**Issue by asn111** [firebase/firebase-ios-sdk#2961]
* Xcode version: 10.1
  * Firebase SDK version: 6.0.0
  * Firebase Component: Firebase/DynamicLinks
  * Component version: 4.0.0

Hi, Thank you for this awesome library, I am stuck at a point when dealing with deep linking, it has been enabled before and was working fine, then God knows how did I got ShortUrl nil, after some RND, I did managed to update pods and then all happens that when instancing  `DynamicLinkComponents` with its initialiser, 
`            let components = DynamicLinkComponents(link: urlLink, domainURIPrefix: AppConstants.kDynamicLink_Domain)!
`  
both `urlLink` and `AppConstants.kDynamicLink_Domain`  have values in them but still getting app crashed, with Fatal error that nil found while unwrapping.
I have no idea why its happening. but I have seen some other issues which does not relate to mine so I believe its not duplicate.

**Comment by morganchen12** [comment]
Hi @asn111, can you share the parameters that you're passing into the initializer? The initializer will return nil if the link is not https or the domain URI prefix is not a valid URL.

**Comment by asn111** [comment]
Thank you for response, Yes,
for the `urlLink` i am passing **https://marcotest.azurewebsites.net/api/Groups/204** and  for `domainURIPrefix` its **marcoapp.page.link**. and it was working fine before with same parameters.

**Comment by asn111** [comment]
Hi @morganchen12  is there anything i need to change, let me know kindly. its been stuck for two days already, thanks.

**Comment by maksymmalyhin** [comment]
@asn111 According to the `DynamicLinkComponents(link:domainURIPrefix:)` [docs](https://github.com/firebase/firebase-ios-sdk/blob/fc6074e1126298d5aa13492aea49ec66561b8d07/Firebase/DynamicLinks/Public/FDLURLComponents.h#L530) the domain URI prefix must start with a valid HTTPS scheme (https://). Do you pass `"marcoapp.page.link"` or `"https://marcoapp.page.link"` as `domainURIPrefix`?

**Comment by asn111** [comment]
@maksymmalyhin  no i am just passing `marcoapp.page.link` like this but it was also the same when it was working. let me try with **https://**

**Comment by asn111** [comment]
It is working fine now with this, `"https://marcoapp.page.link"` it was my mistake to not look into the documentations, Thanks for your help.
