### ISSUE TITLE
After install Firebase/Firestore via pod I am getting error

### ISSUE THREAD

**Issue by GireshD** [firebase/firebase-ios-sdk#2973]
I am getting "grpc/support/port_platform.h' file not found" error after I install pod 'Firebase/Firestore' in pod file in current project.

  * Xcode version: __10.1___
  * Firebase SDK version: ____5.15.0_
  * Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: _____

![Screenshot 2019-05-09 at 4 45 52 PM](https://user-images.githubusercontent.com/32384820/57449570-e92a8d00-7279-11e9-8782-6d6aa248a769.png)

I have alredy so many pod files 

![Screenshot 2019-05-09 at 5 25 29 PM](https://user-images.githubusercontent.com/32384820/57451704-a9ff3a80-727f-11e9-8fdd-56a2adf54d39.png)

**Comment by wilhuff** [comment]
This isn't anything I've seen before. It smells like something in your project is misconfigured somehow.

Firebase 5.15 is quite old now, so before you start, please update and try again. The latest release is Firebase 6.0, which does include some breaking changes for products other than Firestore. If you can't take that change yet, at least upgrade to 5.20.2, which was the last release in the 5.x series. See [the release notes](https://firebase.google.com/support/release-notes/ios) for more details.

Aside from that you might try getting into a clean state:

  * Remove your `~/Library/Developer/Xcode/DerivedData` folder
  * Remove your `Pods` folder
  * `pod install` again

If that doesn't clear up your problem, please share a copy of your project. If you're not open source, you can share project with me privately at mcg@firebase.com.

**Comment by GireshD** [comment]
@wilhuff after updating to 5.20.2 version I am getting error
"Cyclic dependency in module 'Darwin': Darwin -> grpc -> Darwin"
please find image:

![Screenshot 2019-05-10 at 10 26 57 AM](https://user-images.githubusercontent.com/32384820/57503599-5ee03880-730e-11e9-86b0-b1583e2f0b6c.png)

and my gRCP-c++ and gRCP-Core supporting file looks like this

![Screenshot 2019-05-10 at 10 29 40 AM](https://user-images.githubusercontent.com/32384820/57503663-b2528680-730e-11e9-8c6e-140f4884b609.png)

![Screenshot 2019-05-10 at 10 29 57 AM](https://user-images.githubusercontent.com/32384820/57503668-b7afd100-730e-11e9-868f-62830b6ed3cd.png)

**Comment by wilhuff** [comment]
In that case, something must be terribly wrong with your project. There's no way Darwin can depend on gRPC. If you search for [Cyclic dependency in module 'Darwin'](https://www.google.com/search?q=Cyclic+dependency+in+module+%27Darwin%27) you'll see plenty of other other issues similar to this one that all indicate project misconfiguration.

I suspect this is a problem with your `HEADER_SEARCH_PATHS` setting. You've set it in such a way that two headers with the same name are available with what looks like the same name and this is confusing your build. See advice I [gave here](https://github.com/firebase/firebase-ios-sdk/issues/2260#issuecomment-461601816) to others where experiencing other nonsensical build problems.

Alternatively, it's possible that one of the other pods you're using is very aggressive about adding to `HEADER_SEARCH_PATHS` itself. Try pulling your pods out and adding them back incrementally to see if one of them is causing the problem.

As I mentioned earlier, you're welcome to share your project with me, but absent that there's not much more we can do for you here.
