### ISSUE TITLE
Flaky GDT end-to-end test

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#2982]
The flakiness of -[GDTIntegrationTest testEndToEndEvent] frequently causes Travis failures.

See https://travis-ci.org/firebase/firebase-ios-sdk/jobs/530603139 for an example.

**Comment by mikehaney24** [comment]
Looking into it.

**Comment by mikehaney24** [comment]
I can't find any particular reason for this test harness crashing, and I haven't been able to repro locally. Perhaps I can just remove this test from travis and hope that it becomes more clear in the future why this is happening.

**Comment by mikehaney24** [comment]
Memory usage is ~43MB, disk usage is in the low 10s of KB. This test startS up a local HTTP server in the simulator. The details of the crash are captured in a log on the machine, but travis doesn't seem to give us access to those logs.

**Comment by paulb777** [comment]
Thanks for investigating. One option is to move the test to the allow_failures section of travis https://github.com/firebase/firebase-ios-sdk/blob/master/.travis.yml#L300 so you can still see the results but it doesn't break others' integration builds.
