### ISSUE TITLE
When app first launch instanceID token works fine, but some time later token becomes invalid

### ISSUE THREAD

**Issue by kunwang** [firebase/firebase-ios-sdk#3005]
### [READ] Step 1: Are you in the right place?
    Yes
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2.1
  * Firebase SDK version: 5.20.2
  * Firebase Component: Messaging
  * Component version: 5.20.2

### [REQUIRED] Step 3: Describe the problem
   when  app first launch, the firebase token works fine, close app and some time later, the token become invalid.When we send notification, we receive "NotRegistered" error.

#### Relevant Code:

```
   func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
    FirebaseApp.configure()
    NotificationCenter.default.addObserver(self, selector: #selector(refreshToken), name: .MessagingRegistrationTokenRefreshed, object: nil)
    let authOptions: UNAuthorizationOptions = [.alert, .badge, .sound]
    UNUserNotificationCenter.current().requestAuthorization(
        options: authOptions,
        completionHandler: {_, _ in })
   application.registerForRemoteNotifications()
    return true
}

  @objc
  public func refreshToken() {
        InstanceID.instanceID().instanceID(handler: {(result, error) in
            if let refreshedToken = result?.token {
                NotificationRequests.regFIRTokenAndDeviceID(refreshedToken)
            }
        })
    }

   public func setAPNSToken(_ deviceToken: Data) {
        Messaging.messaging().apnsToken = deviceToken
        refreshToken()
   }
```

**Comment by chliangGoogle** [comment]
Seems like a similar issue like #2438.

https://github.com/firebase/firebase-ios-sdk/pull/2860
should fix the issue. which coming in the next release. Please try it out and reopen if this issue still occur to you.

**Comment by kunwang** [comment]
@chliangGoogle   Thanks
