### ISSUE TITLE
Unable to create release on flutter project with firebase iOS

### ISSUE THREAD

**Issue by danysz** [firebase/firebase-ios-sdk#3015]
* Xcode version: Version 10.2.1 (10E1001)
  * Firebase SDK version: from flutter project
  firebase_admob: ^0.9.0
  firebase_auth: ^0.11.0
  firebase_analytics: ^3.0.1
  firebase_core: ^0.4.0
  firebase_crashlytics: ^0.0.4+3

Pod.lock created based on the relevant flutter versions
  - Firebase/AdMob (6.0.0):
    - Firebase/CoreOnly
    - Google-Mobile-Ads-SDK (~> 7.43)
  - Firebase/Analytics (6.0.0):
    - Firebase/Core
  - Firebase/Auth (6.0.0):
    - Firebase/CoreOnly
    - FirebaseAuth (~> 6.0.0)
  - Firebase/Core (6.0.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.0.0)
  - Firebase/CoreOnly (6.0.0):
    - FirebaseCore (= 6.0.0)
  - Firebase/Firestore (6.0.0):
    - Firebase/CoreOnly
    - FirebaseFirestore (~> 1.3.0)
  - firebase_admob (0.0.1):
    - Firebase/AdMob
    - Firebase/Core
    - Flutter
  - firebase_analytics (0.0.1):
    - Firebase/Analytics (~> 6.0)
    - Firebase/Core
    - Flutter
  - firebase_auth (0.0.1):
    - Firebase/Auth (~> 6.0)
    - Firebase/Core
    - Flutter
  - firebase_core (0.0.1):
    - Firebase/Core
    - Flutter
  - firebase_crashlytics (0.0.1):
    - Crashlytics
    - Fabric
    - Firebase/Core
    - Flutter
  - FirebaseAnalytics (6.0.0):
    - FirebaseCore (~> 6.0)
    - FirebaseInstanceID (~> 4.0)
    - GoogleAppMeasurement (= 6.0.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 0.3)
  - FirebaseAuth (6.0.0):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 6.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/Environment (~> 6.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseAuthInterop (1.0.0)
  - FirebaseCore (6.0.0):
    - GoogleUtilities/Environment (~> 6.0)
    - GoogleUtilities/Logger (~> 6.0)
  - FirebaseFirestore (1.3.0):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 6.0)
    - FirebaseFirestore/abseil-cpp (= 1.3.0)
    - "gRPC-C++ (= 0.0.8)"
    - leveldb-library (~> 1.20)
    - nanopb (~> 0.3.901)
    - Protobuf (~> 3.1)
  - FirebaseFirestore/abseil-cpp (1.3.0):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 6.0)
    - "gRPC-C++ (= 0.0.8)"
    - leveldb-library (~> 1.20)
    - nanopb (~> 0.3.901)
    - Protobuf (~> 3.1)
  - FirebaseInstanceID (4.0.0):
    - FirebaseCore (~> 6.0)
    - GoogleUtilities/Environment (~> 6.0)
    - GoogleUtilities/UserDefaults (~> 6.0)

Added from the "firebase" the GoogleService-Info.plist

Everything is running properly when I am running the debug version.
When I try to build an archive to release the iOS version I got error :
Could not find an option named "track-widget-creation".

Failed to build /Users/dan...../client_flutter/fitk_app.
error: Could not get GMP_APP_ID in Google Services file from build environment 

Any ideas how can I take care to have the GMP_APP_ID ?
And why is required only on Release ?

Thanks

**Comment by danysz** [comment]
> I found a few problems with this issue:
> 
> * I couldn't figure out how to label this issue, so I've labeled it for a human to triage. Hang tight.
> * This issue does not seem to follow the issue template. Make sure you provide all the required information.

The issue is related to the build system and not to the code itself.

**Comment by emildesign** [comment]
+1

**Comment by paulb777** [comment]
This looks like https://github.com/flutter/flutter/issues/26279. 

Even if it's not, that's probably a better issue tracker for this bug since it looks to be a problem with the flutter infrastructure and not something in the iOS SDK.

**Comment by danysz** [comment]
> This looks like [flutter/flutter#26279](https://github.com/flutter/flutter/issues/26279).
> 
> Even if it's not, that's probably a better issue tracker for this bug since it looks to be a problem with the flutter infrastructure and not something in the iOS SDK.

Hi

No, the issue with "track-widget-creation" is solved by making `"flutter build iOS --release". The problem remains even after that. It looks that the code from FirebaseId is looking for this parameter somewhere. I tried even to put this parameter in the "GoogleServiceInfo.plist" but it still doesn't find it.

From where this parameter should come ?

Thanks

**Comment by paulb777** [comment]
As far as I can tell, the string "GMP_APP_ID" does not exist in the iOS SDK or its build system.  I still suspect the problem is related to the flutter integration.

**Comment by danysz** [comment]
> As far as I can tell, the string "GMP_APP_ID" does not exist in the iOS SDK or its build system. I still suspect the problem is related to the flutter integration.

Probably you are right, but Firebase SDK is looking for this parameter. Where Firebase expects to find it ?

**Comment by paulb777** [comment]
It might be one of the existing keys in the GoogleService-Info.plist, but it depends what the flutter build system is using it for.

**Comment by danysz** [comment]
> It might be one of the existing keys in the GoogleService-Info.plist, but it depends what the flutter build system is using it for.

1. in GoogleServices plist there is no parameter like this 
2. I created one with this code and put the Google app id in the value and I still have the same error.

**Comment by ryanwilson** [comment]
I've reached out to someone on the Flutter team and asked them to have a look, hopefully they have some more insight. Based on the lack of reference to "GMP_APP_ID" anywhere in these SDKs (the Objective-C implementations for iOS) I'm inclined to believe it's something to do with the way Flutter packages the project.

**Comment by calindru** [comment]
Rolled-back to

**Comment by ryanwilson** [comment]
Aha! Thank you very much @calindru for the information - looks like this is part of the `upload_symbols` script in Crashlytics. cc @samedson 

We'll try to get it fixed shortly!

**Comment by samedson** [comment]
Hey @danysz, the error message is misspelled - it's GOOGLE_APP_ID instead of GMP_APP_ID. You shouldn't need any custom fields in your GoogleService file - the one downloaded from Firebase should work.

What's most likely happening is the Crashlytics run script can't find your GoogleService file when it builds for release. I just tried setting up a new Flutter project with firebase_crashlytics and archiving it from xcode, and it seems to work.

Could you try adding the `--debug` flag after `run` to see if Xcode gives you more information in the build output?

**Comment by teameh** [comment]
I'm also seeing `Could not get GMP_APP_ID in Google Services file from build environment` when building my non-flutter iOS project on our CI. 

On macOS 10.14, Xcode 10.2.1, using:
- Crashlytics: 3.13.1
- Fabric: 1.10.1
- Firebase/Core: 5.6.0

Downgrading to:
- Crashlytics: 3.12.0
- Fabric: 1.9.0

Gives me:

```
Fabric: Configuration Issue

Fabric API key not valid. Your Fabric run script build phase should contain your API key:
./Fabric.framework/run INSERT_YOUR_API_KEY INSERT_YOUR_BUILD_SECRET
```

**Comment by teameh** [comment]
I did not read the docs properly and missed: 

> Note: Make sure your new build phase is the project's last build phase, otherwise Crashlytics won't initialize properly.

Also: 

> Xcode 10 only: Add your app's built Info.plist location to the Build Phase's Input Files field:
> $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)

This fixed it: 🎉

**Comment by loolooii** [comment]
@teameh could you explain the first thing?

**Comment by loolooii** [comment]
@teameh I think your suggestion works for non-Flutter projects. I'm still stuck @ryanwilson any suggestion how to (temporarily) fix this for Flutter projects?

**Comment by harumidiv** [comment]
I tried the crashlytics ios sample app and the same error occurs

**Comment by sperochon** [comment]
I had the same error

> Could not get GOOGLE_APP_ID in Google Services file from build environment

but the solution was this one
https://stackoverflow.com/a/45318508/5553628

**Comment by phattranky** [comment]
I got the same error

```
error: Could not get GMP_APP_ID in Google Services
```

Because I added 

```
${PODS_ROOT}/Fabric/run
$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)
```

In wrong place, I added in existing `Run Script`

We must create new `Run Script` . Please check my screenshot for more detail.

<img width="1138" alt="Runner xcodeproj 2019-06-28 06-01-04" src="https://user-images.githubusercontent.com/6443154/60306473-7e88fa00-996a-11e9-881d-bd3fd00492ac.png">

I'm using `firebase_crashlytics: ^0.0.4+8` and it's woring well

**Comment by paulb777** [comment]
Looks like there are working solutions above
