### ISSUE TITLE
macOS Firestore Initialization

### ISSUE THREAD

**Issue by visdyn** [firebase/firebase-ios-sdk#3032]
* Xcode version: 10.2.1
  * platform: macOS 10.14.5
  * Firebase SDK version: 6.0.0
  * Firebase Component: Firestore 

Issue:
Building a Firestore app on macOS, the initialization sequence is different than on iOS & crashes if the sequence is the same as iOS. Documentation should be edited.

The issue lies in initializing Firestore on macOS - I'll do a comparison from iOS to macOS.

In iOS, Firestore is initialized like this

```
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        FirebaseApp.configure()
```

then in the initial viewController we have a class var to reference Firestore and initialize it in viewDidLoad like this

```
class ViewController: UIViewController {
    var db: Firestore!

    override func viewDidLoad() {
        super.viewDidLoad()
        self.db = Firestore.firestore()
        let settings = self.db.settings
        self.db.settings = settings
    }
```

however, in macOS, applicationDidFinishLaunching is called after the viewController is initialized so this will not work

```
    func applicationDidFinishLaunching(_ aNotification: Notification) 
        FirebaseApp.configure()
```

if the class var db is initialized in viewDidLoad (or literally anywhere in the NSViewController init process (viewDidLoad, viewDidAppear etc), the app builds and runs but the UI never loads and shows the following error in console

> 2019-05-18 11:09:40.693417-0400 FirestoreTest[6485:169285] 6.0.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
> 2019-05-18 11:09:40.693660-0400 FirestoreTest[6485:169145] Failed to set (contentViewController) user defined inspected property on (NSWindow): Failed to get FirebaseApp instance. Please call FirebaseApp.configure() before using Firestore

To fix this, the Firestore initialization needs to be moved from didFinishLaunchingWithOptions to viewDidLoad with the rest of the init code. That should probably be documented if that's the intention.

```
override func viewDidLoad() {
    super.viewDidLoad()
    FirebaseApp.configure()
    self.db = Firestore.firestore()
    let settings = self.db.settings
    self.db.settings = settings
}
```

**Comment by visdyn** [comment]
Since there is a solution, and it's not a bug but more of a documentation issue, I am closing.

**Comment by wilhuff** [comment]
Firestore depends upon the completion of `FirebaseApp.configure()`. Our documentation recommends taking these steps one right after the next: https://firebase.google.com/docs/firestore/quickstart#initialize.

The sequence you're using on iOS happens to work there but as you've observed, if events happen in a different order you'll end up failing. It doesn't much matter where you make these calls but it's safest if you do them together.

**Comment by visdyn** [comment]
@wilhuff 

Thanks! Good to know.

Our project(s) are/were based on the example code provided here

[Cloud Firestore iOS Examples](https://github.com/firebase/quickstart-ios)

and the initialization looks like this for the iOS Cloud Firestore example:

```
import UIKit
import Firebase

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

  var window: UIWindow?

  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    FirebaseApp.configure()

    let db = Firestore.firestore()
    let settings = db.settings
    settings.areTimestampsInSnapshotsEnabled = true
    db.settings = settings
    return true
  }
}
```

However, that code will not work for an macOS app to initialize Firestore throughout the app because the loading sequence is different.

With iOS the loading sequence is this

```
application(_:didFinishLaunchingWithOptions:)
viewDidLoad()
```

and with macOS the loading sequence is this

```
viewDidLoad()
applicationDidFinishLaunching(_:)
```

so you cannot use the iOS Firestore init code in macOS applicationDidFinishLaunching and then try to access Firestore within viewDidLoad (or the first viewController) because it's not initialized yet. So on macOS, the initialization should be within viewDidLoad.

```
var db: Firestore!

override func viewDidLoad() {
    super.viewDidLoad()
    FirebaseApp.configure()
    self.db = Firestore.firestore()
    let settings = self.db.settings
    self.db.settings = settings
}
```

Hopefully that will save future readers some time.
