### ISSUE TITLE
user.isAnonymous should be set to false after unlinking all other providers

### ISSUE THREAD

**Issue by colbylwilliams** [firebase/firebase-ios-sdk#3045]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2.1
  * Firebase SDK version: latest
  * Firebase Component: Auth (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 5.4.2

#### Steps to reproduce:

1. Sign in using anonymous auth.
```swift
Auth.auth().currentUser.isAnonymous // true
```

2. Sign in with Phone Auth (linking the anonymous auth).
```swift
Auth.auth().currentUser.isAnonymous // false
```

3. Unlink the Phone Auth.
```swift
Auth.auth().currentUser.isAnonymous // false - should be true
```

I'm pretty sure there needs to be a check for `providerData` then add `self.anonymous = YES` somewhere around [this line in FIRUser.m](https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/Auth/Source/User/FIRUser.m#L1294), but I don't know enough Obj-C to know exactly what's going on there.

#### Relevant Code:
```swift
Auth.auth().signInAnonymously { authResult, _ in
    print(authResult.user!.isAnonymous) // true
}

// for simplicity, using FirebaseUI for phone auth 
phoneProvider.signIn(withPresenting: presentingViewController, phoneNumber: nil)

print(authResult.user!.isAnonymous) // false

Auth.auth().currentUser?.unlink(fromProvider: provider) { user, _ in {
    print(user!.isAnonymous) // false
    // user!.isAnonymous should be true here as user.providerData.count == 0
    // also the Firebase portal shows as anonymous at this point
}
```

**Comment by renkelvin** [comment]
@colbylwilliams This is intentional. Non-anonymous user can no longer be anonymous even all providers are unlinked, because the developers are still able to track the user.
