### ISSUE TITLE
I can't generate new token after delete when i open the application second time.

### ISSUE THREAD

**Issue by lukiruki** [firebase/firebase-ios-sdk#3051]
## [READ] Step 1: Are you in the right place?
Yes

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2
  * Firebase SDK version: 6.0.0
  * Firebase Component: FirebaseInstanceID (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 4.0

### [REQUIRED] Step 3: Describe the problem

I can't generate new token after delete when i open the application second time. I use "InstanceId.instanceID().instance" when I log in to application and ""InstanceId.instanceID().delete" when I log out from application.

#### Steps to reproduce:

I created two buttons. One for generate token Instance.instance().instance and second for delete (InstanceId.instanceID().delete with callback). When I first run app I can delete and next generate new token. Problem is when I kill application process and open app again. I can first create token but when I delete I can't generate new token.

#### Relevant Code:

I have two method: to register token and unregister token with delete instanceId. Second method is to configure Firebase with plist.

func registerFirebase() {
        
        InstanceID
            .instanceID()
            .instanceID(handler: { (result, error) in
                
                if let _ = error {
                    log.error("Error fetching remote firebase ID")
                } else if let result = result {
                    log.info("Properly saved token in database")
                }
            })
        
    }
    
    func unRegisterFirebase() {
        
       InstanceID.instanceID().deleteID { (error) in
            if let _ = error {
                log.error("Can't unregister from Firebase")
            } else {
                log.info("Successful unregister from Firebase")
            }
        }
        
    }

private func configureFirebase() {

        #if RELEASE
            googlePlistFilePath = Bundle.main.path(forResource: "GoogleService-Info-Prod", ofType: "plist")
        #else
            googlePlistFilePath = Bundle.main.path(forResource: "GoogleService-Info-Dev", ofType: "plist")
        #endif
        
        if let googlePlistFilePath = googlePlistFilePath, let fileopts = FirebaseOptions(contentsOfFile: googlePlistFilePath) {
            FirebaseApp.configure(options: fileopts)
        } else {
            log.error("Couldn't load config file")
        }
    
    }

**Comment by morganchen12** [comment]
Instead of ignoring the error when failing to fetch a new token, can you print out the error description and share it here?

**Comment by lukiruki** [comment]
Thanks for your response ;) Unfortunately i can't even get error because I don't any response from callback when I want generate a new token. I always can delete token and only receive getID ;) From some reason when I delete token I can't get new token again.

**Comment by lukiruki** [comment]
Today I have downloaded the newest version release (6.1.0) but it did not solve my problem ;)

**Comment by morganchen12** [comment]
@chliangGoogle the case where the callback wasn't invoked sounds like a bug that may have been fixed recently. Do you know if this was released?

**Comment by chliangGoogle** [comment]
I can't reproduce right now. FYI, normally when deleting the token with deleteID call and if developer keeps the autoInitEnabled flag on, token will be refreshed automatically. You need to turn it off if you don't want token automatically refresh.

@lukiruki can you share with us the debug log with -FIRDebugEnabled argument?

**Comment by lukiruki** [comment]
So, I generated two logs. In first log file I properly generated token, delete and generate again.
In second file I generate new token, delete and in this moment I can't receive token again.
[Invalid_generate_tokens.docx](https://github.com/firebase/firebase-ios-sdk/files/3209519/Invalid_generate_tokens.docx)
[Properly_generate_tokens.docx](https://github.com/firebase/firebase-ios-sdk/files/3209520/Properly_generate_tokens.docx)

**Comment by lukiruki** [comment]
Sory but I used docx format ;)

**Comment by chliangGoogle** [comment]
Looks like you are not configuring your project correctly, especially your bundle ID seems not consistent with the one in GoogleService-Info.plist. Please fix that and see if that resolves the issue.

The project's Bundle ID is inconsistent with either the Bundle ID in 'GoogleService-Info.plist', or the Bundle ID in the options if you are using a customized options. To ensure that everything can be configured correctly, you may need to make the Bundle IDs consistent. To continue with this plist file, you may change your app's bundle identifier to 'io.calamari.mobile.ios.dev'. Or you can download a new configuration file that matches your bundle identifier from https://console.firebase.google.com/ and replace the current one.
2019-05-23 00:13:39.183826+0200 Push_Instance[2471:507150] 6.1.0 - [Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.

**Comment by lukiruki** [comment]
Yeah, thanks Chen ! This was a problem. I used two different plist. One for Dev and second for Prod environment :) Now I use only for Production with default name 'GoogleService-Info.plist' ;) Thanks again :)
