### ISSUE TITLE
Authentication- Microsoft authentication sign out is not clearing user credentials

### ISSUE THREAD

**Issue by yugandh** [firebase/firebase-ios-sdk#3062]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: Version 10.2 (10E125)
  * Firebase SDK version: 6.1.0 (latest version)
  * Firebase Component:  Auth
  * Component version: GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1 FIRAuth_VERSION=6.0.0 FIRAuth_MINOR_VERSION=6.0

### [REQUIRED] Step 3: Describe the problem
Microsoft authentication sign out feature is not working.
#### Steps to reproduce:
install latest firebase-ios-sdk(this github repo)
add your googleinfo.plist file(you can get it from your firebase project console)
run pod install for this project path
click on signIn button and you will see a list of providers and select Microsoft authentication
WebView will open and give your Microsoft email and password and after successful authentication, user will go to a new screen where sign out button and token refresh button will be there.
Click on sign out button and user will go to sign in page.
Actual:
click on sign in button and select  Microsoft provider and WebView will open and without adding your email and password it is automatically taking you to the sign out page.

Expected:
After sign out button clicked, user need to start enter his credentials for sign in again.

**To reproduce issue you need to sign in and sign out and again sign in and it will not ask to add username and password.**

Another issue: sign in with microsoft authentication and you will on new signout screen and delete the app and install you will be on sign out page instead of sign in page.

#### Relevant Code:

  @IBAction func didTapSignOut(_ sender: AnyObject) {
    // [START signout]
    let firebaseAuth = Auth.auth()
    do {
      try firebaseAuth.signOut()
    } catch let signOutError as NSError {
      print ("Error signing out: %@", signOutError)
    }
    // [END signout]
  }

**Comment by yugandh** [comment]
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/14207417/58280940-a6c37e80-7d56-11e9-8521-0965bb43e2c5.gif)

please see attached video to reproduce the issue.

**Comment by Yue-Wang-Google** [comment]
We don't preserve the credentials. Once you signed out, all the credential / tokens are cleared from memory and disk. 

On the other hand, Microsoft (and other log in services such as Google) will retain your cookies for the browser --- Remember you are using the Safari service, so the broswer keeps the cache and cookie. Next time when you sign in using another app (either Firebase or not), you no longer need to retype the user name and password. 

What you have demoed is the expected behavior.
