### ISSUE TITLE
Application freezes only on first analytics logEvent call after fresh application install

### ISSUE THREAD

**Issue by geoffclifton** [firebase/firebase-ios-sdk#3066]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.1
  * Firebase SDK version: 6.0.0 (latest)
  * Firebase Component: Analytics
  * Component version: 6.0.0

### [REQUIRED] Step 3: Describe the problem
We are trying to configure our application to use Firebase Analytics and GoogleTagManager to report analytics events.

After a fresh install of the application, when trying to log a custom event, the application hangs. In subsequent launches of the application, the events are always logged without problem.

Deleting the app and installing fresh will often result in the first custom event logged to firebase to cause an app freeze.

#### Steps to reproduce:

1. Configure your application to use Firebase Analytics along with Google Tag Manager.
Install them both via cocoapods by adding the following to your podfile.

```
use_frameworks!
platform :ios, '12.0'

def import_pods
    pod 'Firebase/Analytics'
    pod 'GoogleTagManager'
end
```

2. execute `pod install` to setup project
3. Add Firebase supplied GoogleService-Info.plist to the Xcode project
4. Download and add the configured GoogleTagManager container to the Xcode project
5. Initialize Firebase in application AppDelegate via call to `FirebaseApp.configure()`
6. Perform call to log custom firebase analytics event by `Analytics.logEvent(_ name: String, parameters: [String : Any]?)`

After first logEvent call, application will hang but will not crash. 
When running via simulator the following output can be scene with debug enabled (-FIRDebugEnabled)

```
2019-05-23 14:57:05.049719-0400 AppName[20939:1116742] [BoringSSL] nw_protocol_boringssl_input_finished(1543) [C4.1:2][0x7fb8b3d39080] Peer disconnected during the middle of a handshake. Sending errSSLClosedNoNotify(-9816) alert
2019-05-23 14:57:05.058921-0400 AppName[20939:1116742] TIC TCP Conn Failed [4:0x600000ea5800]: 3:-9816 Err(-9816)
2019-05-23 14:57:05.060957-0400 AppName[20939:1116742] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9816)
2019-05-23 14:57:05.061082-0400 AppName[20939:1116742] Task <0F5152F7-86F3-4356-A4E0-11337A42BF3F>.<1> HTTP load failed (error code: -1200 [3:-9816])
2019-05-23 14:57:05.061274-0400 AppName[20939:1116809] Task <0F5152F7-86F3-4356-A4E0-11337A42BF3F>.<1> finished with error - code: -1200
```

When running on a physical device, the same app freeze is seen but the boringssl logs are not logged.

**Comment by geoffclifton** [comment]
After further debugging, it is found this issue only occurs when GoogleTagManager is used in conjunction with Firebase analytics.

When removing GTM from the podfile, building the pods and re-running the tests, the issue is never encountered.

**Comment by geoffclifton** [comment]
Hello,
I was wondering if this issue has been investigated?

**Comment by paulb777** [comment]
@geoffclifton Thanks for the report and sorry about the delayed response.  There's no update yet. This issue is being tracked internally at b/134524065.

**Comment by htcgh** [comment]
@geoffclifton Was your GoogleTagManager container configured to be triggered by that particular custom event?

**Comment by geoffclifton** [comment]
@htcgh yes the GoogleTagManager is configured to be triggered for the custom events fired.

The issue is not specific to a certain one of the events, but happens only on the first trigger of a custom event after app install. After relaunching the app, custom events are sent without issue.

If the user deletes the app, and reinstalls, the problem will be encountered again on first fire of a custom event.

**Comment by htcgh** [comment]
@geoffclifton Can you share a sample project that reproduces the hang? I can't seem to reproduce it.

**Comment by geoffclifton** [comment]
@htcgh I will have to try to replicate this problem in a sample project.

Is there anything unique which only occurs on the first custom event firing after install which could point us in the right direction?

**Comment by htcgh** [comment]
@geoffclifton On the first launch after install, both GoogleTagManager and FirebaseAnalytics create their own SQLite database files and GTM downloads the latest version of the container. Aside from that, the logic on the first and subsequent app launches is the same.

**Comment by geoffclifton** [comment]
@htcgh thanks for the information. 

I’m currently working to create a sample app which demonstrates the issue. 
Thanks.

**Comment by morganchen12** [comment]
It may also be helpful to run the time profiler and seeing what's causing the hang on the main thread.

**Comment by AnthonyMillerSF** [comment]
I am seeing this same issue using `Firebase/Analytics` and `GTMSessionFetcher` currently.

**Comment by morganchen12** [comment]
Anthony, can you share an Instruments time profiler trace?

**Comment by AnthonyMillerSF** [comment]
Next time I can get this to repro again I will!
