### ISSUE TITLE
AnalyticsEventEcommercePurchase is not logged correctly

### ISSUE THREAD

**Issue by mattiacantalu** [firebase/firebase-ios-sdk#3074]
Describe your environment

* Xcode version: 10.2.1
* Components
```
Firebase (5.11.0)
FirebaseABTesting (2.0.0)
FirebaseAnalytics (5.3.0)
FirebaseCore (5.1.6)
FirebaseInstanceID (3.3.0)
FirebasePerformance (2.2.0)
FirebaseRemoteConfig (3.1.0)
```

Describe the problem
FireBase Analytics does not log correctly `AnalyticsEventEcommercePurchase` ("ecommerce_purchase") event. In particular the Debug View, using iOS Simulator, shows correctly the event marked as conversion one (green flag); using real devices it logs the event as general one (blue hand).
On Android SDK FirebaseAnalytics logs correctly the event, showing the green flag (conversion event).

#### Steps to reproduce:

It's possibile reproduce the bug using iOS Simulator and iOS devices triggering "ecommerce_purchase" event.

**Comment by paulb777** [comment]
Please try with a more recent 6.x version of Firebase and FirebaseAnalytics.

**Comment by mattiacantalu** [comment]
@paulb777 thank you for immediate response. Unfortunately the issue is not solved with the last versione of SDK.

**Comment by paulb777** [comment]
@mattiacantalu Thanks for the report. Tracked internally at b/133458289

**Comment by baolocdo** [comment]
Can you provide the XCode log when you turn on the debug mode and run on the device? I'm interested in the `ecommerce_purchase` event information when it is logged. Thanks

**Comment by mattiacantalu** [comment]
@baolocdo @paulb777 👇🏻:
```
2019-05-24 17:43:45.406526+0200 XXX[4440:940805] 5.11.0 - [Firebase/Analytics][I-ACS023033] Starting data upload
2019-05-24 17:43:45.410694+0200 XXX[4440:940735] 5.11.0 - [Firebase/Analytics][I-ACS023105] Event is not subject to real-time event count daily limit. Marking an event as real-time. Event name, parameters: ecommerce_purchase, {
    currency = EUR;
    firebase_conversion (_c) = 1;
    firebase_debug (_dbg) = 1;
    firebase_event_origin (_o) = app;
    firebase_realtime (_r) = 1;
    firebase_screen_class (_sc) = CheckoutCartViewController;
    firebase_screen_id (_si) = 7211253396316809040;
    value = 49;
}
2019-05-24 17:43:45.418299+0200 XXX[4440:940735] 5.11.0 - [Firebase/Analytics][I-ACS023105] Event is not subject to real-time event count daily limit. Marking an event as real-time. Event name, parameters: user_engagement (_e), {
    engagement_time_msec (_et) = 4369;
    firebase_debug (_dbg) = 1;
    firebase_event_origin (_o) = auto;
    firebase_realtime (_r) = 1;
    firebase_screen_class (_sc) = CheckoutCartViewController;
    firebase_screen_id (_si) = 7211253396316809040;
}
2019-05-24 17:43:45.419969+0200 XXX[4440:940735] 5.11.0 - [Firebase/Analytics][I-ACS023105] Event is not subject to real-time event count daily limit. Marking an event as real-time. Event name, parameters: screen_view (_vs), {
    firebase_debug (_dbg) = 1;
    firebase_event_origin (_o) = auto;
    firebase_previous_class (_pc) = CheckoutCartViewController;
    firebase_previous_id (_pi) = 7211253396316809040;
    firebase_realtime (_r) = 1;
    firebase_screen_class (_sc) = CheckoutThankYouViewController;
    firebase_screen_id (_si) = 7211253396316809045;
}
```

**Comment by baolocdo** [comment]
It seems like the SDK logs the event as conversion `firebase_conversion (_c) = 1;` correctly. This looks like a bug on the front-end to me and in the debug view

**Comment by paulb777** [comment]
Internal tracking bug has been closed with "Intended Behavior"
