### ISSUE TITLE
Authentication- unable to access the Microsoft provider access token according to firebase documentation

### ISSUE THREAD

**Issue by yugandh** [firebase/firebase-ios-sdk#3076]
### [REQUIRED] Step 1: Describe your environment

Xcode version: Version 10.2 (10E125)
Firebase SDK version: 6.1.0 (latest version)
Firebase Component: Auth
Component version: GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1 FIRAuth_VERSION=6.0.0 FIRAuth_MINOR_VERSION=6.0

### [REQUIRED] Step 2: Describe the problem
Using the OAuth access token, you can call the Microsoft Graph API.
For example, to get basic profile information, you can call the REST API, passing the access token in the Authorization header:

https://graph.microsoft.com/v1.0/me

**Reference: https://firebase.google.com/docs/auth/ios/microsoft-oauth**
According to above reference we need to retrieve access token in below mentioned code. But i am unable to read the property of accessToken (// credential.accessToken) to get access token

In firebase documentation it was mentioned we can retrieve access token using above steps but in that closure block i am unable to access the property of accessToken
#### Steps to reproduce:

https://github.com/firebase/quickstart-ios/tree/master/authentication

In this git repo search for below  Relevant Code and try to access the access token and it will not be available

#### Relevant Code:

```
   provider.getCredentialWith(nil) { credential, error in
      if error != nil {
        // Handle error.
      }
      if credential != nil {
        Auth().signIn(with: credential) { authResult, error in
          if error != nil {
            // Handle error.
          }
          // User is signed in.
          // IdP data available in authResult.additionalUserInfo.profile.
          // OAuth access token can also be retrieved:
          // credential.accessToken
        }
      }
    }
    
```

**Comment by Yue-Wang-Google** [comment]
Sorry AuthDataResult.credential.accessToken is in private header for now: https://github.com/firebase/firebase-ios-sdk/pull/2916/files 

We are in the process of releasing it to the public soon. Probably you can access it in the next month. 

If you really need to use it you can get it by importing the private header. But we provide no support nor guarantee for now.

**Comment by luciilucii** [comment]
Any updates on this issue already?

**Comment by RJPDeanlo** [comment]
I've been patiently waiting for this update as well.
(I would rather not import the private headers as described)

**Comment by Yue-Wang-Google** [comment]
It may take another few weeks before this can launch to public. In the mean time, you can create an FIROAuthCredential  extension in your project

**Comment by RJPDeanlo** [comment]
Is there a sample in swift on how to do this? (sorry ... I'm a C# coder so I'm new to swift)

**Comment by morganchen12** [comment]
@RJPDeanlo here's some reference material from [StackOverflow](https://stackoverflow.com/a/16345028).

**Comment by Yue-Wang-Google** [comment]
create a bridging header (.h file) like this. add it to your project
```
#import "FIRAuthDataResult.h"
@class FIROAuthCredential;
@interface FIRAuthDataResult (Unreleased)
@property(nonatomic, readonly, nullable) FIROAuthCredential *credential;
@end 

```

then in swift, you can access it via `result?.credential.accessToken`

**Comment by RJPDeanlo** [comment]
That worked! I can access the token.
Thank you for that code snippet!!

**Comment by Yue-Wang-Google** [comment]
Glad to know it works for you. you can safely remove the header once we release the feature to the public next month.

**Comment by luciilucii** [comment]
Worked for me too, thanks!

**Comment by cakesterman** [comment]
I have been trying to figure out why I couldn’t get my access token from Microsoft. Hopefully that code snippet will help.

**Comment by cakesterman** [comment]
Can someone explain where the result? is coming from.  I have been learning swift for about 5 days now so I am still learning.

**Comment by morganchen12** [comment]
`result` in this case is an `AuthDataResult`. See the original snippet at the top of this issue (where the variable is named `authResult`):

```swift
    provider.getCredentialWith(nil) { credential, error in
      if error != nil {
        // Handle error.
      }
      if credential != nil {
        Auth().signIn(with: credential) { authResult, error in // <-- authResult
          if error != nil {
            // Handle error.
          }
          // User is signed in.
          // IdP data available in authResult.additionalUserInfo.profile.
          // OAuth access token can also be retrieved:
          // credential.accessToken
        }
      }
    }
```

**Comment by cakesterman** [comment]
"Error getting access token from microsoft.com, OAuth2 redirect uri is: **, response: OAuth2TokenResponse{params: error=invalid_client&error_description=AADSTS70002

My codes does not get past the Auth.auth().signIn part and has the error listed above.
`if let x = credential {
                Auth.auth().signIn(with: x) { authResult, error in
                    if error != nil {
                        
                        //Handle error
                        print(error?.localizedDescription)
                    }`

**Comment by cakesterman** [comment]
"Error getting access token from microsoft.com, OAuth2 redirect uri is: **, response: OAuth2TokenResponse{params: error=invalid_client&error_description=AADSTS70002

My codes does not get past the Auth.auth().signIn part and has the error listed above.
`
if let x = credential {
                Auth.auth().signIn(with: x) { authResult, error in
                    if error != nil {
                        
                        //Handle error
                        print(error?.localizedDescription)
                    }
`

**Comment by morganchen12** [comment]
@cakesterman Your client secret is invalid and you'll need to generate a new one via Microsoft's website. Please use StackOverflow for your general programming issues, since this is not a Firebase issue.

**Comment by morganchen12** [comment]
This was released a while ago.
