### ISSUE TITLE
too many arguments for https callable function

### ISSUE THREAD

**Issue by giorgio80** [firebase/firebase-ios-sdk#3082]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: _____
  * Firebase SDK version: _____
  * Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by giorgio80** [comment]
hello, 

having latest sdk version.   I'm trying to call a function from my code and have to pass lot of text parameters using data :


>  functions.httpsCallable("updateStripeConnectHost").call(["CompanyExternalAcccount": self.companyIBAN.text, "CompanyName":self.companyName.text,"CompanyAddress":self.companyAddress.text,"CompanyCity":self.companyCity.text,"CompanyPostalCode":self.companyPostalCode.text,"CompanyTaxId":self.companyTaxNumber.text,"CompanyType":self.companyTypeField.text,"OwnerName":self.companyOwnerName.text,"OwnerSurname":self.companyOwnerSurname.text,"OwnerBirthDate":self.companyOwnerBirthDate.text,"OwnerCity":self.companyOwnerCity.text,"OwnerAddress":self.companyOwnerAddress.text,"OwnerPostalCode":self.companyOwnerPostalCode.text,"DirectorName":self.companyDirectrName.text,"DirectorSurname":self.companyDirectorSurname.text,"OwnerIDFile":ownerIDfile,"DirectorIDFile":directorIDfile])
                    { result, error in
                    if let error = error as NSError? {
                        if error.domain == FunctionsErrorDomain {
                            _ = FunctionsErrorCode(rawValue: error.code)
                            _ = error.localizedDescription
                            _ = error.userInfo[FunctionsErrorDetailsKey]
                        }
                        print(result as Any)
                        print(error)
                        // ...
                    }
                    if let text = (result?.data as? [String: Any])?["text"] as? String {
                        print(text)
                    }
                }

unfortunately compiler hangs exactly on this function call saying it is requesting to much time to compile .   Any suggestion on best way to pass arguments?  need to prepare the json prior to call?  
I'm using same example as per google documents

**Comment by ryanwilson** [comment]
@giorgio80 It's likely having trouble parsing the nested statements and inferring the types for each one. Assuming they're all strings, the best way would be to break it out like this:

```
// Have the parameters separate, explicitly saying the type is [String: String].
let parameters: [String: String] = 
    ["CompanyExternalAcccount": self.companyIBAN.text,
     "CompanyName": self.companyName.text,
      /* rest of the parameters */
     "DirectorIDFile": directorIDFile]

// Call the function.
functions.httpsCallable("updateStripeConnectHost").call(parameters) { result, error in
  // .. Implementation of the callback
}
```

Let me know if that works!

**Comment by giorgio80** [comment]
@ryanwilson I managed out and seems to work with this approach.  btw I had to update pods first.

btw thanks

**Comment by ryanwilson** [comment]
Glad it worked for you!
