### ISSUE TITLE
Linking Firebase SDK with Obj-C Cocoa Touch Framework

### ISSUE THREAD

**Issue by joaomelo81** [firebase/firebase-ios-sdk#3095]
Is there a way of linking Firebase with an Objective-C Cocoa Touch Framework?

I have made some experiments by linking the necessary Firebase modules for MLKit in a custom Cocoa Touch Framework. In this way the Firebase dependencies are embedded within my custom framework. This works fine when I embed the custom framework into a target app, however the target app already has some Firebase modules embedded on it which causes duplicate embedded frameworks (in the app and my custom framework).

I'd like to use some modules of MLKit inside my custom framework and link them on my custom framework's target app in a way that the Firebase frameworks will be embedded in the target app instead of in the custom framework.

Thoughts?

**Comment by paulb777** [comment]
The Firebase CocoaPods are comprised of static frameworks. Thus, they should not be dependencies of dynamic frameworks.  Any framework that links them should also be linked statically.

**Comment by joaomelo81** [comment]
OK. In this case should I distribute my custom framework as static (fake) framework?

**Comment by morganchen12** [comment]
@joaomelo81 yes. Or you can distribute them as a CocoaPod.
