### ISSUE TITLE
memory leak :NSNotificationCenter defaultCenter

### ISSUE THREAD

**Issue by kartikartik** [firebase/firebase-ios-sdk#3104]
![Screenshot 2019-05-28 at 4 37 20 PM](https://user-images.githubusercontent.com/28666702/58529009-ab74b080-81f6-11e9-8950-4161a480e25e.png)

**Comment by ryanwilson** [comment]
Closing, see https://github.com/firebase/firebase-ios-sdk/issues/3108#issuecomment-496967699 for more info.
