### ISSUE TITLE
memory leak: FIRApp sendNoticationsToSDKS:app

### ISSUE THREAD

**Issue by kartikartik** [firebase/firebase-ios-sdk#3105]
![Screenshot 2019-05-28 at 4 37 47 PM](https://user-images.githubusercontent.com/28666702/58529078-f262a600-81f6-11e9-9dc7-00ce7bec2732.png)

**Comment by ryanwilson** [comment]
Closing, see https://github.com/firebase/firebase-ios-sdk/issues/3108#issuecomment-496967699 for more info.
