### ISSUE TITLE
memory leak: [FIRApp configureWithName: KFIRDeafultAppName options:options]

### ISSUE THREAD

**Issue by kartikartik** [firebase/firebase-ios-sdk#3106]
![Screenshot 2019-05-28 at 4 38 13 PM](https://user-images.githubusercontent.com/28666702/58529169-52f1e300-81f7-11e9-9f03-f5ff267bb221.png)

**Comment by ryanwilson** [comment]
Closing, see https://github.com/firebase/firebase-ios-sdk/issues/3108#issuecomment-496967699 for more info.
