### ISSUE TITLE
memory leak: [FIRApp configureWithOptions:options]

### ISSUE THREAD

**Issue by kartikartik** [firebase/firebase-ios-sdk#3107]
![Screenshot 2019-05-28 at 4 39 18 PM](https://user-images.githubusercontent.com/28666702/58529383-268a9680-81f8-11e9-9ed1-f7763ad3da44.png)

**Comment by ryanwilson** [comment]
Closing, see https://github.com/firebase/firebase-ios-sdk/issues/3108#issuecomment-496967699 for more info.
