### ISSUE TITLE
Swift File in Objective C POD Files of firebase-ios-sdk

### ISSUE THREAD

**Issue by Meet1313** [firebase/firebase-ios-sdk#311]
How to use my swift project files in firebase-ios-sdk objective c code?

**Comment by paulb777** [comment]
Currently we require that firebase-ios-sdk be written in Objective C, so that Objective C apps that want to use Firebase don't need to pay the Swift size increase penalty.

Firebase has full support for Swift apps. See the documentation at https://firebase.google.com/docs/ios/setup
