### ISSUE TITLE
Every time after app update cannot receive FCM token after first run only

### ISSUE THREAD

**Issue by noangel** [firebase/firebase-ios-sdk#3112]
* Xcode version: 10.2.1
  * Firebase SDK version: 5.20
  * Firebase Component: Messaging
  * Component version: umm, it's a binary from iOS SDK 5.20

#### Steps to reproduce:

I call
**[FIRApp configure];**
in **application didFinishLaunchingWithOptions**.
Then, when when user goes to in-app settings, (s)he wants to enable or disable remote notifications for my app. I need FCM token to send it to server and check. I use

```
[[FIRInstanceID instanceID] instanceIDWithHandler:^(FIRInstanceIDResult* _Nullable result, NSError * _Nullable error) {
			if (error != nil) {
				//NSLog(@"Error fetching remote instance ID: %@", error);
				token = "error";
			} else {
				//NSLog(@"Remote instance ID token: %@", result.token);
				token = [result.token cStringUsingEncoding:NSUTF8StringEncoding];
			}
			gettokenstarted = false;
		}];
```
and `return token.c_str();`.
It works fine... Well it actually fails... only every time... after user gets an update for my app.
User installs an update and runs app, then **instanceIDWithHandler** called but somehow it's callback doesn't called, neither error nor token are returned.
Workaround is close app and run it again. From second run it works, but on next update it happens again... It's PITA. Please tell me if You have some workaround, or how long do I need to wait until it fixed? I have it for 3 months already since I migrated to FCM.
Android version works fine, but on iOS some strange things happening here.

**Comment by ryanwilson** [comment]
Hi @noangel - can you provide a bit more of the code here? Specifically the declaration of `token` and the return statement, and anything in between (feel feel free to redact any private code). If you're calling the return statement after the completion handler but not waiting for the completion handler to run, `token` will be `nil` since `instanceIDWithHandler` is an asynchronous method.

**Comment by noangel** [comment]
```
namespace ... {
std::string token = "error";
bool gettokenstarted = false;

void GetTokenIOS() {
		FIRApp* firapp = [FIRApp defaultApp];
		if(firapp == nil) {
			token = "error";
			gettokenstarted = false;
			return;
		}
		[[FIRInstanceID instanceID] instanceIDWithHandler:^(FIRInstanceIDResult* _Nullable result,
															NSError * _Nullable error) {
			if (error != nil) {
				//NSLog(@"Error fetching remote instance ID: %@", error);
				token = "error";
			} else {
				//NSLog(@"Remote instance ID token: %@", result.token);
				token = [result.token cStringUsingEncoding:NSUTF8StringEncoding];
			}
			gettokenstarted = false;
		}];
	}

const char* GetTokenResultIOS() {
		if(gettokenstarted) return "";
		return token.c_str();
	}
}
```

**Comment by noangel** [comment]
there is a function runs from main thread:

```
namespace ... {
void GetTokenStart() {
gettokenstarted = true;
#ifdef __APPLE_CC__
GetTokenIOS();
...
}
```

this function runs from some background thread:
```
namespace ... {
const char* GetTokenResult() {
#ifdef __APPLE_CC__
return GetTokenResultIOS();
}
```

**Comment by noangel** [comment]
@ryanwilson Hi!
My code main parts are above.
In crossplatform(iOS/Android) app, I have two threads, switching every fixed time interval.
These threads waiting for each other, never run simultaneously. One thread is "main" thread, which is, on iOS, a thread, where it's safe to call UI APIs.
Second thread is some script engine.

When I need FCM token I call some "gettoken()" from script, the call goes to C++ code.
In C++ code I put that "command"(like GET_TOKEN) into thread safe queue(every read/write is locked by mutex).
Then I have some Update() on main loop. It checks if queue is empty.
If queue is not empty, it takes a "command"(GET_TOKEN) from queue and removes it from queue.
After that GetTokenStart() is called on this, same main thread.

Then it's all about instanceIDWithHandler, especially it's callback.
It(callback) will be called some day, right? I believe it will.
So from second thread I polling GetTokenResult(). It usually returns FCM token, when it ready, or "error", or ""(empty string) when it trying hard to get a token.
My implementation is not ideal, but it works most of time.

The problem is: only on iOS and only on first run after app update, instanceIDWithHandler is called, but its callback does not. Never. I tried to wait for 5 minutes, tried to call instanceIDWithHandler again many times, callback still not called.
But if I close app, and run it again, I can very easily get my FCM token. Every run except first app run after update has no problem, it all works.
Then some day I need to update my app again, and it happens: on first run all 100000+ iOS users cannot receive remote notifications after update, until they restart an app just once more...

**Comment by ryanwilson** [comment]
Thanks for the info.

Two things: I can't immediately tell from the sample code, are these functions within a class or just in the namespace? If they're not in a class, the completion handler may not be retained after the `GetTokenIOS()` function completes and the callback wouldn't be called. You'll have to retain the completion block somehow, either in a class instance or a variable in the same namespace (similar to `gettokenstarted`.

Another thing I just noticed- you're running an older version of the Firebase SDKs. If the above comment doesn't help, it's not too much trouble can you please update to the latest Firebase SDK and see if the issue persists?

**Comment by noangel** [comment]
@ryanwilson Thank You for suggestions! Will try to retain completion handler and use latest SDK and report results here, probably next Monday.

**Comment by noangel** [comment]
@ryanwilson I tried to reproduce it using latest SDK and moved GetTokenIOS() source to singleton class. Seems to be fixed for me. Thank You for helpful tips! Closing it for now.

**Comment by noangel** [comment]
@ryanwilson Sorry I checked it again and got same result (can't receive token after reinstall, run app once more fixes it). Using latest SDK.

**Comment by noangel** [comment]
```
namespace <...> {
	std::string token = "error";
	bool gettokenstarted = false;
}

@interface myfirebase : NSObject {}
+(myfirebase*)sharedinstance;
@end

@implementation myfirebase

+(myfirebase*)sharedinstance {
	static dispatch_once_t once;
	static myfirebase* instance;
	dispatch_once(&once,^{
		instance=[[self alloc] init];
	});
	return instance;
}

-(id)init {
	self=[super init];
	return self;
}

-(void)firebaseinit {
	FIRApp* firapp = [FIRApp defaultApp];
	if(firapp != nil) return;
	[FIRApp configure];
}

-(void)gettoken {
	FIRApp* firapp = [FIRApp defaultApp];
	if(firapp == nil) {
		<...>::token = "error";
		<...>::gettokenstarted = false;
		return;
	}
	[[FIRInstanceID instanceID] instanceIDWithHandler:^(FIRInstanceIDResult* _Nullable result,
														NSError * _Nullable error) {
		if (error != nil) {
			//NSLog(@"Error fetching remote instance ID: %@", error);
			<...>::token = "error";
		} else {
			//NSLog(@"Remote instance ID token: %@", result.token);
			<...>::token = [result.token cStringUsingEncoding:NSUTF8StringEncoding];
		}
		<...>::gettokenstarted = false;
	}];
}

@end

namespace <...> {

	void InitIOS() {
		[[myfirebase sharedinstance] firebaseinit];
	}

	void GetTokenIOS() {
		[[myfirebase sharedinstance] gettoken];
	}

	const char* GetTokenResultIOS() {
		if(gettokenstarted) return "";
		return token.c_str();
	}

}


```

**Comment by morganchen12** [comment]
@noangel can you try updating to the latest version of Firebase? Also, does `gettoken` print any errors to console?

**Comment by noangel** [comment]
@morganchen12 I'll try to confirm again on recently released 6.2.0 SDK. I checked device system log for error messages, and there were no messages from SDK, only some system "garbage", but I'll look again in system log and app debug log (in Xcode) under latest SDK.

**Comment by noangel** [comment]
I updated to Firebase SDK 6.2.0 and tried again.
6.1.0 works better(thought it fixed but still can reproduce in 20-30% cases on first run) than 5.2.0(my issue occurs in almost 100% cases on first run), and 6.2.0 seems to be even better (reproduced 0 times, but need a few days to confirm). I hope it fixed by SDK update 6.2.0, but still need a time to check it good enough to close ticket.

**Comment by morganchen12** [comment]
@noangel were you able to reproduce this issue on 6.2.0?

**Comment by noangel** [comment]
@morganchen12 Yes, but I tested only: rollback to 5.2.0 -> reproduce -> reinstall app with 6.2.0, and sometimes I cannot get token on 6.2.0. I want to check if I can reproduce it when upgrade app with 6.2.0 to app with same SDK version, but I need more time to make next version, planning to comfirm it next week.

**Comment by noangel** [comment]
@morganchen12 I checked it again with 6.2.0 -> 6.2.0 version upgrade, and can reproduce it by following steps:
I have 2 app versions 1 and 2, both have FCM SDK 6.2.0. both are same app, only bundle version number is different.
0. install newer app version(2). no issues here.
1. downgrade app to previous version(1), cannot get token on first start.
2. close and restart an app(still ver1), no issue, can get token again.
3. upgrade app to version(2), cannot get token on first run.
it's very strange...

**Comment by noangel** [comment]
After trying debug in Xcode cannot reproduce any more on same device. But it happens on another iPod touch.

**Comment by morganchen12** [comment]
How are you sending your notifications?

**Comment by noangel** [comment]
@morganchen12 We have a "MyServerNameHere", and "MySDKNameHere", which(SDK) has API for FCM. When I need to send a message to some user, I pass user ID to "MySDKNameHere". Request goes to "MyServerNameHere", which(server) gets FCM token from user ID and sends message via Firebase.
FCM token may change some day, so I need to check a token every time app starts. When I get token I call "MySDKNameHere" method for setting token for user ID.
So I have Firebase SDK only for getting token. I use [FIRApp configure](from UIApplication didFinishLaunchingWithOptions) and [[FIRInstanceID instanceID] instanceIDWithHandler] for getting token. instanceIDWithHandler has a callback function parameter, which must be called every time I need token, with error set, or FIRInstanceIDResult.token set. The problem is instanceIDWithHandler doesn't call a callback after app upgrade on first run. Maybe [FIRApp configure] fails but [FIRApp defaultApp] != nil.

**Comment by morganchen12** [comment]
You should be handling token refreshes via the [FIRMessagingDelegate](https://firebase.google.com/docs/reference/swift/firebasemessaging/api/reference/Protocols/MessagingDelegate.html#/c:objc(pl)FIRMessagingDelegate(im)messaging:didReceiveRegistrationToken:) protocol instead of manually fetching a new instance ID on every app launch. This method will be called whenever the token is refreshed.

**Comment by noangel** [comment]
@morganchen12 thanks, I'll try it!

**Comment by noangel** [comment]
@morganchen12 Used FIRMessagingDelegate and can get a token now. Fixed!

**Comment by soundbites** [comment]
Hi,
we are currently having the exact same issue. We're on FireBase 6.8.1. And after installing our app we do not get a token, either through FIRMessagingDelegate or InstanceID...

After launching the app for a second time (or after some minutes/hours) we finally get a token.

We are btw seeing a lot of errors occurring? Does this mean the service that registers tokens is down?

[Firebase/InstanceID][I-IID007000] Device checkin HTTP fetch error. Error Code: -999
[Firebase/InstanceID][I-IID005003] Failed to checkin device Error Domain=NSURLErrorDomain Code=-999 "geannuleerd" UserInfo={NSErrorFailingURLStringKey=https://device-provisioning.googleapis.com/checkin, NSLocalizedDescription=geannuleerd, NSErrorFailingURLKey=https://device-provisioning.googleapis.com/checkin}
[Firebase/InstanceID][I-IID005001] Checkin error Error Domain=NSURLErrorDomain Code=-999 "geannuleerd" UserInfo={NSErrorFailingURLStringKey=https://device-provisioning.googleapis.com/checkin, NSLocalizedDescription=geannuleerd, NSErrorFailingURLKey=https://device-provisioning.googleapis.com/checkin}.
