### ISSUE TITLE
New InstanceID test flake

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#3114]
This flake has started showing up in the last few days:

Failing tests:
	-[FIRInstanceIDTokenManagerTest testDeleteTokenFailure]
** TEST FAILED **

See https://travis-ci.org/firebase/firebase-ios-sdk/jobs/539060759

**Comment by paulb777** [comment]
cc: @chliangGoogle

**Comment by maksymmalyhin** [comment]
Seems to be fixed.
