### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by demosthese** [firebase/firebase-ios-sdk#315]
With FirebaseInstanceID 2.0.3 push notifications don't work, but with 2.0.0 they do.

**Comment by flash23** [comment]
Xcode 9 cant make it work also! tried messaging 2.0.0, 2.0.2 and 2.0.3

**Comment by morganchen12** [comment]
Can you both include more information on how you've set up Messaging?

**Comment by flash23** [comment]
This solved the problem 

-(void)registerForPush
{
    UNAuthorizationOptions authOptions = UNAuthorizationOptionAlert | UNAuthorizationOptionSound | UNAuthorizationOptionBadge;
    [[UNUserNotificationCenter currentNotificationCenter] requestAuthorizationWithOptions:authOptions completionHandler:^(BOOL granted, NSError * _Nullable error) {
        if(granted && !error )
        {
            dispatch_async(dispatch_get_main_queue(), ^{
                [[UIApplication sharedApplication] registerForRemoteNotifications];
                [UNUserNotificationCenter currentNotificationCenter].delegate = self;
                
                [[PushManager sharedInstance] registerNotificationCategories];
                
                if([FIRApp defaultApp] == nil)
                {
                    [FIRApp configure];
                }
                [FIRMessaging messaging].delegate = self;
                
                DDLogDebug( @"Push registration success." );
            });
        }
        else
        {
            DDLogDebug( @"Push registration FAILED" );
        }
    }];
} 

Before this blokc was outside 

if([FIRApp defaultApp] == nil)
{
               [FIRApp configure];
 }
 [FIRMessaging messaging].delegate = self;

like this

-(void)registerForPush
{
    if([FIRApp defaultApp] == nil)
    {
        [FIRApp configure];
    }
    [FIRMessaging messaging].delegate = self;
    
    UNAuthorizationOptions authOptions = UNAuthorizationOptionAlert | UNAuthorizationOptionSound | UNAuthorizationOptionBadge;
    [[UNUserNotificationCenter currentNotificationCenter] requestAuthorizationWithOptions:authOptions completionHandler:^(BOOL granted, NSError * _Nullable error) {
        if(granted && !error )
        {
            dispatch_async(dispatch_get_main_queue(), ^{
                [[UIApplication sharedApplication] registerForRemoteNotifications];
                [UNUserNotificationCenter currentNotificationCenter].delegate = self;
                
                [[PushManager sharedInstance] registerNotificationCategories];
                
                DDLogDebug( @"Push registration success." );
            });
        }
        else
        {
            DDLogDebug( @"Push registration FAILED" );
        }
    }];
}

it worked with XCode 8 and lower versions. There is some thread thing going on maybe....

**Comment by rsattar** [comment]
[There is a bug](https://github.com/firebase/firebase-ios-sdk/issues/254) which has been fixed internally but hasn't been released yet, that is likely causing the issue. 

For now, as a workaround you should always just call `[[UIApplication sharedApplication] registerForRemoteNotifications];` as early as possible (this does not create a user permissions dialog, and should always give you an APNs token).

**Comment by flash23** [comment]
thx

**Comment by Aurazion** [comment]
Also fixed for me, thanks !

**Comment by berlininsomniac** [comment]
It's not fixing it for me. The messages don't get delivered if the app is in the background on iOS 11.

**Comment by Aurazion** [comment]
@berlininsomniac Here is my fix in Swift if it can help you : 

```swift
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        
        // [START set_messaging_delegate]
        Messaging.messaging().delegate = self
        // [END set_messaging_delegate]
        
        // Register for remote notifications. This shows a permission dialog on first run, to
        // show the dialog at a more appropriate time move this registration accordingly.
        // [START register_for_notifications]
        if #available(iOS 10.0, *) {
            // For iOS 10 display notification (sent via APNS)
            UNUserNotificationCenter.current().delegate = self
            
            let authOptions: UNAuthorizationOptions = [.alert, .badge, .sound]
            UNUserNotificationCenter.current().requestAuthorization(
                options: authOptions,
                completionHandler: {_, _ in })
        } else {
            let settings: UIUserNotificationSettings =
                UIUserNotificationSettings(types: [.alert, .badge, .sound], categories: nil)
            application.registerUserNotificationSettings(settings)
        }
        
        application.registerForRemoteNotifications()
        // [END register_for_notifications]
        
        FirebaseApp.configure()

        return true
    }
```

**Comment by rsattar** [comment]
@berlininsomniac Not receiving messages in the background usually indicates an issue with the app configuration for APNs (i.e. check if `application:didRegisterForRemoteNotificationsWithDeviceToken:` is being called in your app delegate), or perhaps you are making a non-APNs request to the FCM API (i.e. if you are _not_ sending a `notification` payload, and not including `content_available=1`).

There is also a known issue in iOS 11.0 where silent notifications (`content_available=1`) are arriving on the device, but not actually being delivered to the app.

**Comment by Aurazion** [comment]
@rsattar It doesn't work anymore, without changing my code ... Waiting the fix release ....
Thanks

**Comment by PaulRBerg** [comment]
@Aurazion Confirming that FirebaseInstanceID@2.0.0 is fully operational when you add `application.registerForRemoteNotifications()` as the first line in `didFinishLaunchingWithOptions`.

Waiting for the final fix though, kinda ugly solution.

**Comment by rsattar** [comment]
FWIW, if you're locking temporarily to `2.0.0` you don't need to also call `application.registerForRemoteNotifications()` on app start.

**Comment by berlininsomniac** [comment]
I can confirm that downgrading FirebaseInstanceID to 2.0.0 reenables pushes on iOS 11.

**Comment by priyankamistry09** [comment]
How to downgrade the FirebaseInstanceID?
I am just adding 
`  pod 'Firebase/Core', '4.0.1'
  pod 'Firebase/Messaging'
`
if I do 
`  pod 'Firebase/Core', '4.0.1'
  pod 'Firebase/Messaging', '2.0.0'
  pod 'Firebase/InstanceID', '2.0.0'
`
Which doesn't allow me to install pod.
Any idea?

**Comment by PaulRBerg** [comment]
Try `pod 'FirebaseInstanceID`

**Comment by JussiSuojanen** [comment]
`pod 'FirebaseInstanceID', '2.0.0'`, fixed the problem for me. Thanks for everyone in this feed. Saved my day :)

**Comment by Aurazion** [comment]
Same for me with ```pod 'FirebaseInstanceID', '2.0.0'```
Thanks

**Comment by paulb777** [comment]
Fix released today in Firebase 4.3.0, FirebaseMessaging 2.0.4, and FirebaseInstanceID 2.0.4

**Comment by dgaedcke** [comment]
I'm hitting this same issue today on:
Using Firebase (4.6.0)
Using FirebaseAnalytics (4.0.5)
Using FirebaseAuth (4.3.2)
Using FirebaseCore (4.0.11)
Using FirebaseDatabase (4.1.1)
Using FirebaseInstanceID (2.0.6)
Using FirebaseMessaging (2.0.6)

**Comment by PaulRBerg** [comment]
Indeed, it came back again

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'FIRESTORE INTERNAL ASSERTION FAILED: Can't handle server close in non-started state.'
```

**Comment by morganchen12** [comment]
Please don't add 'me too' comments to closed issues. If you'd like to indicate you're also suffering from the same open issue, use GitHub's add a reaction feature. If it's a closed issue, try the solutions that have been listed and comment with what steps you took and what errors occurred.

@dgaedcke, your issue is not related to this issue and does not contain enough information to debug. 

@PaulRBerg, your issue is not related to this issue. See #490
