### ISSUE TITLE
Cocoapods installing outdated versions of pods

### ISSUE THREAD

**Issue by yusuftor** [firebase/firebase-ios-sdk#3151]
I have the following in my podfile:

```
  pod 'FirebaseCore'
  pod 'FirebaseDynamicLinks'
  pod 'FirebaseFirestore'
  pod 'FirebaseAuth'
  pod 'FirebaseDatabase'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Facebook'
  pod 'FirebaseUI/Twitter'
```

For some reason, this installs the following frameworks:

```
Installing Firebase 6.2.0
Installing FirebaseAnalyticsInterop (1.2.0)
Installing FirebaseAuth 6.1.1
Installing FirebaseAuthInterop (1.0.0)
Installing FirebaseCore 6.0.2
Installing FirebaseDatabase 6.0.0
Installing FirebaseDynamicLinks 4.0.0
Installing FirebaseFirestore 1.3.2
Installing FBSDKCoreKit (5.0.2)
Installing FBSDKLoginKit (4.44.1)
Installing TwitterKit (2.8.1)
```

The `FBSDKLoginKit` and `TwitterKit` that it installs is outdated and so my project can't run. Why!?

**Comment by paulb777** [comment]
Please do a `pod update` and examine the contents of the `Podfile.lock` for an explanation of why each version was installed.  If you're still having trouble, share the contents of `Podfile.lock` here.

**Comment by paulb777** [comment]
@morganchen12 @renkelvin Is there a release note or other documentation about transitioning from the TwitterKit deprecation?

**Comment by morganchen12** [comment]
TwitterKit is deprecated. Use Firebase OAuth to support Twitter login instead. [Here's an example of what replacing TwitterKit with OAuth looks like](https://github.com/firebase/quickstart-ios/commit/5b5e274c25b9dbb728935b38011289792404400f).
