### ISSUE TITLE
Firestore (Mac OS) doesn't return anything

### ISSUE THREAD

**Issue by ohokay** [firebase/firebase-ios-sdk#3158]
### [REQUIRED] Describe your environment

  * Xcode version: 10.2.1
  * Firebase SDK version: Auth (6.1.1), Core (6.0.2), Firestore (1.3.2)
  * Firebase Component: Auth, Core, Firestore

### Describe the problem

Attempting to retrieve data from Firestore returns no results, errors or anything at all. Firebase Auth works fine, and is full integrated.

#### Relevant Code:

```
Firestore.firestore().collection("downloads").getDocuments { (snap, err) in
  print(snap)
}
```

If I try and log the firestore instance to the console I instantly get a crash.

Any ideas? Hopefully this is the right place to ask.

Thanks!

**Comment by paulb777** [comment]
One possibility - Make sure `-ObjC` is set in the `OTHER_LD_FLAGS` Build Setting.  Older versions of CocoaPods did not automatically set it for macOS.

**Comment by wilhuff** [comment]
When you say "If I try and log the firestore instance to the console I instantly get a crash", do you mean something like `NSLog(Firestore.firestore())`? That shouldn't be happening but it's also not going to do anything useful.

A better way to get more information is to enable Firestore's debug logging: https://gist.github.com/katowulf/0475fb7a5907ed757f687aab6ed15878.

**Comment by ohokay** [comment]
@paulb777 Nailed it. I was using Cocoapods 1.5, but just upgraded to the latest (1.7.1) and it now works.

Thank you!
