### ISSUE TITLE
Auth not working properly 

### ISSUE THREAD

**Issue by OkiRules** [firebase/firebase-ios-sdk#3159]
* Xcode version: 11
  * Firebase SDK version: Latest
  * Firebase Component: Auth
  * Component version: Latest

When I sign in a user of Firebase Auth (latest version) for some reason the CurrentUser object is still nil, it works on Xcode 10 with iOS 12 but not with Xcode 11 with iOS 13. Any idea why and is there a fix?

**Comment by morganchen12** [comment]
Is this reproducible for all users consistently on iOS 13? Do you get any errors in console when logging in?

**Comment by OkiRules** [comment]
No errors, just this object: Auth.auth().currentUser is nil. I don’t know if this happens for others but I have tested it on two different devices running iOS 13 and it is still nil.

--
Oscar Gorog

**Comment by OkiRules** [comment]
I found out what the issue was and I fixed it, it had to do with my code (because of some changed API's in iOS 13).

Sorry :)
Oscar

P.S This is 100% not a Firebase Auth Issue
