### ISSUE TITLE
Specs satisfying the `Firebase/Functions` dependency were found, but they required a higher minimum deployment target.

### ISSUE THREAD

**Issue by SamboVisal** [firebase/firebase-ios-sdk#3160]
I was trying to install `pod Firebase/Functions` but got following error

`[!] CocoaPods could not find compatible versions for pod "Firebase/Functions":
  In Podfile:
    Firebase/Functions

Specs satisfying the `Firebase/Functions` dependency were found, but they required a higher minimum deployment target.`

`# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'vKclub2.0.1' do
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Functions'
  pod 'GoogleMaps'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Phone'
  pod 'ImageSlideshow', '~> 1.6'
  pod 'DZNEmptyDataSet'
  pod 'SDWebImage'
  pod 'SDWebImage/WebP'
 
  pod 'paper-onboarding'
 
  pod 'JVFloatLabeledTextField'
  pod 'PhoneNumberKit'
  pod 'ProgressHUD'

end
`

**Comment by morganchen12** [comment]
This means you need to bump your minimum deployment target to a newer version. FirebaseFunctions supports [iOS 8.0 and above](https://github.com/CocoaPods/Specs/blob/master/Specs/c/5/4/FirebaseFunctions/2.5.1/FirebaseFunctions.podspec.json#L17).
