### ISSUE TITLE
Dynamic GoogleService-Info.plist results in a compile-time crash with latest (Carthage) version of Crashlytics and Firebase

### ISSUE THREAD

**Issue by mpaulsonco** [firebase/firebase-ios-sdk#3179]
### [REQUIRED] Step 2: Describe your environment
  * Xcode version: 10.1
  * Firebase SDK version: 6.2.0
  * Firebase Component: Analytics, Fabric, Crashlytics
  * Component version: Analytics `6.2.0`, Fabric `1.10.1`, Crashlytics `3.13.1`

#### Steps to reproduce:

1. Set up a project that has multiple, uniquely-named `GoogleService-Info.plist` files
- `GoogleService-Dev.plist`, `GoogleService-Stage.plist`, etc.

2. Use Xcode Schemes for defining build variants (https://bit.ly/2xEjn9B)
* Note, this is different than the target-based approach described in the Firebase documentation but is has been previously working for us prior to the introduction of the Input File step in the Run Script for Fabric. We use a single target for our build variants and use Schemes and .xcconfig to define the different build variants, so we cannot use the target-based approach outlined in the documentation since we have a single target. 

3. Experience the following error when trying to compile:
![image](https://user-images.githubusercontent.com/7143252/59382158-a9484100-8d22-11e9-9469-191b961d217b.png)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

This happens consistently when trying to build without a file explicitly named `GoogleService-Info.plist`, however, we are able to configure the rest of Firebase just fine using the method `FIROptions.init(contentsOfFile:)` when initializing Firebase. 

We have tried adding `GOOGLE_APP_ID` and `GMP_APP_ID` (see screenshot) to our app's `Info.plist` which uses the dynamic value from the scheme's `.xcconfig`, but this did not resolve the compiler exception. 

* Note: A workaround seems to be to include a dummy `GoogleService-Info.plist` file in your project, and then still call `init(contentsOfFile` programmatically when using Firebase. We have not tested this to see if Fabric Crash Reports are being reported to the correct target, but it does allow the project to compile. 

#### Relevant Code:
```
// This code works fine until we install Fabric and the run script executes, causing the compile-time exception since there isn't a file named `GoogleService-Info.plist`. 
if let googlePlistName = Bundle.main.infoDictionary?[Constant.googlePlistNameKey] as? String,
            let googlePlistPath = Bundle.main.path(forResource: googlePlistName, ofType: "plist"),
            let firebaseOptions = FirebaseOptions(contentsOfFile: googlePlistPath) {
            FirebaseApp.configure(options: firebaseOptions)
        }
```

**Comment by morganchen12** [comment]
To clarify, the workaround you mentioned still results in a compiler error?

Can you try adding a Run Script phase to your build phases before the Crashlytics script runs and replace the dummy GoogleService-Info.plist with your intended plist on a per-target basis?

**Comment by mpaulsonco** [comment]
@morganchen12 The workaround resolves the compiler error, but doesn't pass the right values. I will add the additional run script to replace the dummy `GoogleServices-Info.plist` file with the scheme-specific actual file and let you know if this works. Thanks!

**Comment by mpaulsonco** [comment]
Hi @morganchen12 I tried the other workaround you suggested, and it is working. 

Are there plans to align the Crashlytics requirements for `GoogleService-Info.plist` with the implementation of the rest of Firebase?

I'm adding some notes for anyone else who has having this problem. We have added these user-defined settings:
- `PATH_TO_GOOGLE_SERVICE_DIR` The path to the folder relative to `PROJECT_DIR` where we store the `.plist`
- `GOOGLE_PLIST_NAME` The name of the `.plist` file for a given `.xcconfig` 

Here is the Run Script: 
```
PATH_TO_GOOGLE_PLISTS="${PROJECT_DIR}/${PATH_TO_GOOGLE_SERVICE_DIR}/${GOOGLE_PLIST_NAME}.plist"

cp -r "$PATH_TO_GOOGLE_PLISTS" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/GoogleService-Info.plist"
```

**Comment by morganchen12** [comment]
Looks good. You may be able to streamline this using Xcode's Copy Bundle Resources phase and storing all the files with the same GoogleService-Info.plist name in different directories. Each target would then need to copy a different plist into their bundle resources.

We're trying to smooth out all the warts in Crashlytics integration before the migration deadline. Thanks for bringing this to our attention!

**Comment by morganchen12** [comment]
Filed b/135188384 for internal tracking. @TKBurner FYI

**Comment by mpaulsonco** [comment]
@morganchen12 Since are using `.xcconfig` and schemes for each build variant (under a single target -- the application), that approach wouldn't work for us. 

We are receiving Analytics in Firebase, but even with the latest script we aren't seeing crash reports come in to the Firebase console. Is there any specific information we can help provide for debugging the issue? Thanks

**Comment by morganchen12** [comment]
You should [file a support issue](https://support.google.com/firebase/contact/support?page=). The support staff will be able to look at your project data and config files and make sure it isn't something like a console bug.

**Comment by morganchen12** [comment]
Closing the loop on this: Setting up Crashlytics without a GoogleService-Info.plist file is something the team is looking to add support for in a quarter or two.
