### ISSUE TITLE
'unicode/utf8.h' file not found [Catalyst UIKit for macOS]

### ISSUE THREAD

**Issue by appfrilans** [firebase/firebase-ios-sdk#3189]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.0 beta 1
  * Firebase SDK version: 6.2.0
  * Firebase Component: FirebaseCore (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 6.0.2

### [REQUIRED] Step 3: Describe the problem
I get an error 

 fatal error: 'unicode/utf8.h' file not found when running. 

#### Steps to reproduce:

I am trying to integrate macOS in my Catalyst/ UIKit for Mac app. Using Cocoapods 1.7.2. With this pod file:

target 'xxxxxMac' do
  platform :macos, '10.15'
  
  use_frameworks!
  
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'FirebaseDatabase'
  pod 'FirebaseStorage'
end

Error is:

Library/Developer/Xcode/DerivedData/projectx-gjaanasqdnycapdqrcipkyxevoec/Build/Intermediates.noindex/Pods.build/Debug-uikitformac/FirebaseDatabase-iOS.build/Objects-normal/x86_64/FSRWebSocket.o

....../Users/xxxx/xxx/xxxx/Pods/FirebaseDatabase/Firebase/Database/third_party/SocketRocket/FSRWebSocket.m:28:9: fatal error: 'unicode/utf8.h' file not found
#import <unicode/utf8.h>
        ^~~~~~~~~~~~~~~~
1 error generated.

#### Relevant Code:

#if targetEnvironment(UIKitForMac)
import FirebaseCore
#else
import Firebase
#endif

**Comment by morganchen12** [comment]
While our support for Catalyst is non-existent as of right now, this unicode header is one that should be present on every platform that Apple supports. Looks like this header is part of the WebKit framework. Does the error go away if you add WebKit to your target's linked frameworks?

**Comment by appfrilans** [comment]
Adding WebKit did not help. Even if Catalyst support is not existing, would it not be possible to add it anyway as Firebase has macOS support? 


Here is my Build phases/Link Binary with libraries after adding WebKit. However, setting the firebase frameworks to iOS + Mac gives me another error.

<img width="899" alt="Skärmavbild 2019-06-16 kl  09 49 16" src="https://user-images.githubusercontent.com/4116199/59561092-0e9a7b80-901c-11e9-999e-deb9360f19bb.png">

"Building for UIKit for Mac, but the linked framework 'FBSDKLoginKit.framework' was built for <unknown>. You may need to restrict the platforms for which this framework should be linked in the target editor."

**Comment by Jason-Morcos** [comment]
Could this perhaps be because of changes apple is making to web handling with Catalyst? I know they deprecated UIWebView and don't have a Catalyst equivalent of UIWebView (forcing the use of WKWebView). Perhaps they have made deprecating changes to WebKit in general and are enforcing these deprecations in Catalyst? Just a thought

**Comment by ryanwilson** [comment]
This may also be related to CocoaPods not having support for Catalyst - they have an Issue open tracking it now. https://github.com/CocoaPods/CocoaPods/issues/8892

**Comment by morganchen12** [comment]
>Even if Catalyst support is not existing, would it not be possible to add it anyway as Firebase has macOS support?

See #3144

**Comment by appfrilans** [comment]
Could this be relevant? An answer from Apple but also a comment about getting one framework working with UIKit-for-mac:

https://forums.developer.apple.com/message/362577

**Comment by ryanwilson** [comment]
Responded in the other issue https://github.com/firebase/firebase-ios-sdk/issues/3144#issuecomment-503124024

General Catalyst related progress and updates should be posted there.

> "Building for UIKit for Mac, but the linked framework 'FBSDKLoginKit.framework' was built for . You may need to restrict the platforms for which this framework should be linked in the target editor."

It's also worth noting that `FBSDKLoginKit` is a Facebook SDK, not a Firebase one 😃
