### ISSUE TITLE
DynamicLink Url returning jSON serialize error.

### ISSUE THREAD

**Issue by asn111** [firebase/firebase-ios-sdk#3199]
Xcode version: 10.1
Firebase SDK version: 6.0.0
Firebase Component: Firebase/DynamicLinks
Component version: 4.0.0

Hi, Thank you for this awesome library, May be its more of a question than a issue, I am stuck at a point when dealing with Dynamic linking, all is good when making a link, but i am getting error on the link which is like this 

```
<ExceptionMessage>
The 'ObjectContent`1' type failed to serialize the response body for content type 'application/json; charset=utf-8'.
</ExceptionMessage>
<InnerException>
<Message>An error has occurred.</Message>
<ExceptionMessage>
Object reference not set to an instance of an object.
</ExceptionMessage>
<ExceptionType>System.NullReferenceException</ExceptionType>
```
and link which is generated [https://marcoapp.page.link/T4Ye]() is here which is having issue.
i know that is error where someone would say it's from backend , but no same things worked before and even Android level of application is still working fine with same parameters. And i didn't get what is wrong thing i am sending or not sending which is causing this issue. Below mentioned is the code.

#### Relevant Code:

```
 guard let components: DynamicLinkComponents = DynamicLinkComponents(link: urlLink, domainURIPrefix: "https://marcoapp.page.link") else {
                return ""
            }
```
in here **urlLink** = [https://marcotest.azurewebsites.net/api/Groups/(Int)](url)

**Comment by dmandar** [comment]
Hi.. Will follow up soon. In the meantime can you try fixing the reported issues with this link? You can append a query parameters of ?d=1 to the URL to find out more. https://marcoapp.page.link/T4Ye?d=1
