### ISSUE TITLE
dynamic_link_first_open reported on every open

### ISSUE THREAD

**Issue by antonholmquist** [firebase/firebase-ios-sdk#320]
### Environment
  * Xcode version: 9
  * Deployment target: iOS 10
  * Firebase SDK version: 4.2.0
  * Firebase Product: DynamicLinks

### Problem

For some reason it seems like the iOS SDK is reporting many more `dynamic_link_first_open` than `first_open`. The first open seems to be correct but the dynamic link first open seems way to high. The screenshots below are from the same iOS app over the same period (last week). It seems to me that dynamic_link_first_open should never be higher than first_open, and also count per user is 3.6 which is incorrect. According to the logs below it seems every app open triggers a dynamic_link_first_open.

first_open: (Seems correct)
![first_open](https://user-images.githubusercontent.com/505089/30975737-47b61956-a473-11e7-9119-3f619fd609fc.png)

dynamic_link_first_open (seems way to high) 
![dynamic_link_first_open](https://user-images.githubusercontent.com/505089/30975672-1d0310ec-a473-11e7-8d8e-598ca4cd2f3e.png)

### Code

````
func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
        
    // Dynamic Links
    if let dynamicLink = DynamicLinks.dynamicLinks()?.dynamicLink(fromCustomSchemeURL: url) {
        return true
    }
        
    return false
}

func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([Any]?) -> Void) -> Bool {
        if let dynamicLinks = DynamicLinks.dynamicLinks(), let webpageURL = userActivity.webpageURL {
            
        let handled = dynamicLinks.handleUniversalLink(webpageURL) { (dynamiclink, error) in
        }
            
        return handled
    }

    return false
}
````

### Logs

Running the app in debug mode shows this on every open: 

````
[Firebase/Analytics][I-ACS023051] Logging event: origin, name, params: fdl, dynamic_link_first_open, {
    firebase_event_origin (_o) = fdl;
    firebase_screen_class (_sc) = UINavigationController;
    firebase_screen_id (_si) = 8799172281864402952;
}
````

**Comment by antonholmquist** [comment]
Is the source code of Dynamic Links for iOS available? Couldn't find it in this repo.

**Comment by paulb777** [comment]
@antonholmquist The Dynamic Links source has not yet been open sourced.

**Comment by OleksiyA** [comment]
@antonholmquist Firebase Dynamic Links will use NSUserDefaults flag to store state, that "Application did received pending dynamic link or dynamic link not available". This flag is set inside dynamicLink(fromCustomSchemeURL: url). Looking at your code, this should work correctly. If this flag is not set, FDL SDK will try to retrieve pending dynamic link on next App start.

Do you perform any custom manipulations with NSUserDefaults?

To help debug the issue:

Please add logging to your methods application:openURL:options: and application:continueUserActivity:restorationHandler: and print URL that being passed there.

Also, please run DynamicLinks.performDiagnostics(completion: nil) and paste output to this issue. Alternatively, feel free to email myself at oleksiyi _at_ google.com with this data.

**Comment by antonholmquist** [comment]
OK, I think the problem is that no flag is being set.

The url passed on `application:openURL:options:` is`<bundle_id>://google/link/?dismiss=1&is_weak_match=1`. After this a dynamic_link_first_open event is sent, but looking in the user defaults I can't find the flag. What's the name of it? I can see `"/google/measurement/debug_mode": 1` when I'm debugging but no other Google or Firebase flag.

`application:continueUserActivity:restorationHandler:` is not called.

Diagnostics output:

```
---- Firebase Dynamic Links diagnostic output start ----
Firebase Dynamic Links framework version 2.1.0
System information: OS iOS, OS version 11.0, model iPhone
Current date 2017-10-13 07:59:08 +0000
AutomaticRetrievalEnabled: YES
WARNING: iOS Simulator does not support Universal Links. Firebase Dynamic Links SDK functionality will be limited. Some FDL features may be missing or will not work correctly.
	Specified custom URL scheme is <bundle_id> and Info.plist contains such scheme in CFBundleURLTypes key.
performDiagnostic completed successfully! No errors found.
---- Firebase Dynamic Links diagnostic output end ----
```

**Comment by OleksiyA** [comment]
Two NSUserDefaults flags FDL is using:

@"com.google.appinvite.openURL" : this is set when we tried to retrieve pending dynamic link and we found link, or we did not found link. This only set if we was able to connect to then server successfully.

@"com.google.appinvite.readDeeplinkAfterInstall" : this is set when we passed dynamic link to application, and application called dynamicLink(fromCustomSchemeURL: url). 

You can use those flag for debugging purposes. Please do not rely on their values in prod. We can update/remove them at any time without notice.

If you set both of those flags to YES, FDL will stop passing link to openURL: method on next App start. Let me know if this works for you.

Another thing to check: do you have IPv6 connectivity? This may affect how this code performs. Can you try Installing App and first launching App while connected to WiFi and Cellular. Is there different results?

**Comment by SandraShen** [comment]
Having almost same problem here.
The difference is that FDL reports dynamic_link_first_open ONLY even the app is already installed.
The dynamic_link_open is never reported.

I found both two NSUserDefaults flags were set to "FALSE".

**Comment by gylippus** [comment]
FWIW, we've been having similar issues. We have been unable to get anything to trigger `restorationHandler` since iOS11.

**Comment by antonholmquist** [comment]
@OleksiyA Yes, setting "com.google.appinvite.openURL" and "com.google.appinvite.readDeeplinkAfterInstall" to true stopped link passing to openURL: method on the next launch. So when the keys are there they seem to work as expected.

Wifi or Cellular doesn't make a difference. They keys are never set.

**Comment by Udomomo** [comment]
Having same issue as @SandraShen.
I'm a newbie for Swift, and don't know how to check the NSDefaults flag's value.

**Comment by antonholmquist** [comment]
@OleksiyA Still seeing the same behavior in 4.6.0, unfortunately.

**Comment by OleksiyA** [comment]
@antonholmquist That is quite weird. I did quite heavy refactoring in Firebase Dynamic  Links 2.2.0 (main Firebase pod 4.6.0).
Any chance you can repro this issue in Firebase quickstart App https://github.com/firebase/quickstart-android/tree/master/dynamiclinks ?

**Comment by OleksiyA** [comment]
To all people in this thread:
Commenting "I have the same  issue" may complicate matters as if you see similar results does not means that reasons are the same. I would recommend opening separate issues. Please be specific about what works, what does not works, what you are seeing. Please include output of the DynamicLinks.performDiagnostics(completion: nil) to issues you create. Feel free to open Firebase support tickets to share information privately.

Please take a look at questions in stackoverflow as your issue may be answered there https://stackoverflow.com/questions/tagged/firebase-dynamic-links
If your question/issue has generic nature, I recommend using stackoverflow for asking questions. Stackoverflow is quite good for searching for answers, so answer on your question will help fellow developers as well.

I believe this thread has mix of issues:
Original issue seems to be "Firebase Dynamic Links calling application:openURL:options: on each App start, not only first App start".
Other issues: "Firebase Dynamic Links do not return pending dynamic link when I expected to have pending dynamic link" (pending here is the link that user tapped when your App was not installed on device yet.)

One more note: If you see link <bundle_id>://google/link/?dismiss=1&is_weak_match=1 this means that Firebase Dynamic Links tried to fetch pending dynamic link, was successful in connecting to the server, but pending dynamic link is not available for your app/device combination.

**Comment by antonholmquist** [comment]
@OleksiyA Ah, now I get it. I tried with 4.6.0 again and dynamic_link_first_open is no longer sent! So the error seem to have been that the event was sent even though there was no pending dynamic link. That would explain the huge numbers. So good this seems to be resolved!

**Comment by OleksiyA** [comment]
@antonholmquist Thats good to hear! 
BTW, I am planning to devote more time to open-sourcing the Firebase Dynamic Links iOS SDK. With @paulb777 help I expect we can move this process forward.

@SandraShen @gylippus @Udomomo Please update to latest Firebase (or Firebase Dynamic Links) pods and re-test. If your issue still exists see my previous comment.
