### ISSUE TITLE
FIRIAMDisplayExecutor messageClicked crash when url is set

### ISSUE THREAD

**Issue by RuiVarela** [firebase/firebase-ios-sdk#3207]
Xcode version: 10.2.1
Firebase SDK version: 6.0.0
Firebase Component: InAppMessagingDisplay
Component version: 0.14.0

Problem:
Modal Button Action crashes the app when tapped. The Modal can be dismissed. but if an url is set the app crashes when it is tapped

```
2019-06-18 10:18:04.881799+0100 BigRoomSurfing-beta[710:1513143] -[FIRIAMDisplayExecutor messageClicked:]: unrecognized selector sent to instance 0x1c04b5d20
2019-06-18 10:18:04.882447+0100 BigRoomSurfing-beta[710:1513143] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[FIRIAMDisplayExecutor messageClicked:]: unrecognized selector sent to instance 0x1c04b5d20'
*** First throw call stack:
(0x1823aed8c 0x1815685ec 0x1823bc098 0x1823b42d4 0x18229a41c 0x1003ab4a0 0x1003ace80 0x18c0de6c8 0x18c1ff8a4 0x18c0e477c 0x18c21a1dc 0x18c161a48 0x18c1568f8 0x18c155238 0x18c936c0c 0x18c9391b8 0x18c932258 0x182357404 0x182356c2c 0x18235479c 0x182274da8 0x184257020 0x18c25578c 0x10031423c 0x181d05fc0)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

Steps to reproduce:
Follow the setup steps on https://firebase.google.com/docs/in-app-messaging/get-started
Send a Modal message with a action button, use the url https://google.com
Tap the button

**Comment by ryanwilson** [comment]
Hi @RuiVarela - thanks for the report. Are you able to reproduce on the latest version? 0.15.0 is currently the latest version.

**Comment by RuiVarela** [comment]
@ryanwilson it is fixed on the latest version, sorry for the confusion

**Comment by ryanwilson** [comment]
No worries, happy to hear!
