### ISSUE TITLE
FR: Be able to call observeSingleEventOfType but ignore local cache when online with persistence enabled

### ISSUE THREAD

**Issue by lukegeiger** [firebase/firebase-ios-sdk#321]
* Xcode version: 9.0
  * Firebase SDK version: any version
  * Library version: any version
  * Firebase Product: database 

### [REQUIRED]  Describe the problem

I think it would be a incredibly useful feature if we were able to call observeSingleEventOfType on a query but have the option to ignore the local cache. It seems as if observeSingleEventOfType does not always get the most up to date data from firebase and honors the local cache always. This is incredibly frustrating to the way I want to use firebase, because in my application I very rarely want to have an open connection on an endpoint, I usually just want to fetch the latest data once, and go on with my code. 

#### Steps to reproduce:

1. Enable Persistence 
2. Input data at a specific endpoint through a different medium other than your app (such as the web application version of your app)
3. Call observeSingleEventOfType on a query from your app, the app will not return anything because you are connected to the internet with persistence enabled and by default it seems to be pulling from the cache.

#### Example

`            
[query observeSingleEventOfType:FIRDataEventTypeValue withBlock:^(FIRDataSnapshot * _Nonnull snapshot) {

}];
`

I am basically requesting that the following code above add the functionality to always pull the latest data available from firebase and not depend on the local cache, and the block will run regardless of if there is data at the endpoint or not.

**Comment by schmidt-sebastian** [comment]
This is the default behavior for Firestore's get() calls. We are not currently intending to port this feature back to the RTDB.
