### ISSUE TITLE
User is logged out automatically when app gets killed on Release Build Config.

### ISSUE THREAD

**Issue by jeandavid** [firebase/firebase-ios-sdk#3215]
### Step 2: Describe your environment

  * Xcode version: 10.2.1
  * Firebase SDK version: 6.2.0
  * Firebase Component: Auth
  * Component version: 6.1.1

### Step 3: Describe the problem

On Release Build Config only, whenever the app gets killed (background && not running), the user gets logged out automatically. This doesn't happen with the Debug Build Config. 

#### Steps to reproduce:

User can log in with phone. When logged in, and the app goes to background but is still running, then the user is kept logged in. However, if the app gets killed by the system or by the user himself, then the user is logged out automatically. He needs to log in again on future app launch. THIS IS NOT INTENDED. 
This doesn't happen with the Debug Build Config. This is a new behavior that also happens with previous build that weren't affected in the past.

**Comment by ryanwilson** [comment]
Thanks for the report and sorry you're having issues, that sounds strange.

Can you give a bit more information here, specifically:

- Which method of sign in are you using?
- Can you share a bit of example code for your sign in (removing any private info)
- When you say the when the app is killed, this could be both from swiping the app away in multitasking AND when the system decides to kill the app?
- Does this happen on specific OS versions, or specific devices?
- Can you reproduce this on your own phone in release mode?

Hoping we can get down to the bottom of this quickly and resolve it for you.

**Comment by jeandavid** [comment]
Thank you @ryanwilson for your quick answer. Below the additional info you requested: 

- The app uses exclusively the sign in with phone method provided by Firebase UI. 
 ```
// In SignUpViewController
func showPhoneEntry() {
      let authUI = FUIAuth.defaultAuthUI()
      let phoneProvider = FUIPhoneAuth.init(authUI: authUI)
      authUI.providers = [phoneProvider]
      phoneProvider.signIn(withPresenting: self, phoneNumber: nil) 
}

// in HomeViewController
override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
     
        let auth = FUIAuth.defaultAuthUI()
        if auth?.auth?.currentUser == nil {
            // show SignUpViewController
        }
}
```

I have tried to use the authListener as well but with no success. 

```
// in HomeViewController
var authStateDidChangeHandle: AuthStateDidChangeListenerHandle?
var auth: Auth {
     didSet {
          if auth.currentUser == nil {
               // show SignUpViewController
          }
     }
}

override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
     
        self.auth = Auth.auth()
        self.authStateDidChangeHandle = auth.addStateDidChangeListener({
              (auth, user) in
              self?.auth = auth
         })
 }
```

- When I say that the app is killed, I mean it is not running after a swipe away in multitasking. I don't know how to trigger a system kill. 

- It happens on iOS 12.1, on iPhone 8, X and XR.

- It only happens with release version of the app (downloaded from TestFlight), which I can reproduce on all our phones. The debug version works fine.

**Comment by morganchen12** [comment]
Are there any errors printed in console? Auth should attempt to fetch the stored credentials from Keychain and print an error on a failed fetch.

**Comment by jeandavid** [comment]
When I run the release config build on my phone, the console prints the same error message whether it's a first launch (app wasn't installed on device before) or after a kill (app was installed on device but not running following a user swipe away). 

```
6.2.0 - [Firebase/Auth][I-AUT000001] Error loading saved user when starting up:
Error Domain=FIRAuthErrorDomain Code=17995 "An error occurred when accessing the keychain.
The @c NSLocalizedFailureReasonErrorKey field in the @c NSError.userInfo dictionary
will contain more information about the error encountered"
UserInfo={FIRAuthErrorUserInfoNameKey=ERROR_KEYCHAIN_ERROR,
NSLocalizedFailureReason=SecItemCopyMatching (0),
NSLocalizedDescription=An error occurred when accessing the keychain. 
The @c NSLocalizedFailureReasonErrorKey field in the
@c NSError.userInfo dictionary will contain more information about the error encountered}
```

When I run the debug config build on my phone, there is no message printed to the console and indeed the app works as expected.

**Comment by renkelvin** [comment]
@jeandavid Do you use a shared keychain? https://firebase.google.com/docs/auth/ios/single-sign-on

**Comment by jeandavid** [comment]
I do have the Keychain Sharing capability turned on but I am not using it for Firebase Single Sign on.

**Comment by renkelvin** [comment]
@jeandavid My guess is that there is issue with your entitlements file for release build to access the sharing ketchain. Please double check in the Building settings.

**Comment by jeandavid** [comment]
@renkelvin resetting the entitlements file for the release config build did the job. Thanks for your help!

**Comment by srikanthsrnvs** [comment]
I'm having the same issue. Entitlements fix did not work for me..
