### ISSUE TITLE
InAppMessaging - InAppMessagingDisplayDelegate messageClicked:withAction: behaves weird

### ISSUE THREAD

**Issue by xiao99xiao** [firebase/firebase-ios-sdk#3228]
* Xcode version: 10.2.1
  * Firebase SDK version: 6.3.0
  * Firebase Component: FirebaseInAppMessaging
  * Component version: 0.15.1

#### Steps to reproduce:

First, I use `FirebaseInAppMessaging` without `FirebaseInAppMessagingDisplay` . So I have my customized `InAppMessagingDisplay` class instance.

In the customized `InAppMessagingDisplay` class, I need to call the following methods after a message is tapped, according to the docs.

`displayDelegate.messageClicked?(message, with: InAppMessagingAction(actionText: action.buttonText, actionURL: actionURL))`

The result of this method leads to very weird behavior:
* If the method is called within several seconds(like 3 sec) after the InAppMessage arrived, nothing will happen.
* But, if the method is called after a long time(like 20 sec) after the InAppMessage arrived, the actionURL will be opened(by calling application.openURL).

My Question: Why does the method sometimes opens actionURL and sometimes doesn't?

Currently the only way for me to avoid the weird behavior is to use the deprecated method `messageClicked:` instead, and open the actionURL manually.

**Comment by christibbs** [comment]
@xiao99xiao could you share your code snippet for the handler method that gets called when you tp your button? I tried reproducing this with a sample app but I'm seeing normal behavior.

My method looks like:
```
let buttonAction = InAppMessagingAction(actionText:self.iam.primaryActionButton.buttonText, actionURL: self.iam.primaryActionURL)
self.delegate.messageClicked!(self.iam, with: buttonAction)
```

Where `iam` is an instance of `InAppMessagingCardDisplay`.
