### ISSUE TITLE
FIRAnalyticsVersionMismatch

### ISSUE THREAD

**Issue by bryan1anderson** [firebase/firebase-ios-sdk#3238]
* Xcode version: Version 10.2.1 (10E1001)
  * Firebase SDK version: 
Firebase 6.3.0
  * Firebase Component 
FirebaseAnalytics (6.0.2)
FirebaseCore (6.0.3)
FirebaseInstanceID (4.2.0)
GoogleAppMeasurement (6.0.2)
GoogleUtilities (6.2.0)

### [REQUIRED] Step 3: Describe the problem

I can't launch my app.

I realize this might be duplicated by #2151 but that issue is closed, and it was for different versions

`Terminating app due to uncaught exception 'FIRAnalyticsVersionMismatch', reason: 'Google Analytics for Firebase version (60001000) does not match with Google App Measurement (60002000) version. Please update.'
`
#### Steps to reproduce:

I updated pods and now this happens. I was using Fabric but that stopped working today so I moved over to finally use Firebase. Total fail

**Comment by maksymmalyhin** [comment]
@bryan1anderson Thank you for sharing your issue. Could you provide a bit more detail on it. I was not able reproduce it locally. Here are the [Podfile and Podfile.lock](https://github.com/firebase/firebase-ios-sdk/files/3315486/Podfile.zip) I used. 

Could you please do following:
1. Check if a particular version of  FirebaseAnalytics or GoogleAppMeasurement is locked in you `Podfile`.
2. Share your Podfile and Podfile.lock or, ideally, a sample project to reproduce the issue. 
3. Version of Cocoapods you are using.

**Comment by paulb777** [comment]
Other things to try include an Xcode clean and removal of DerivedData.

**Comment by bryan1anderson** [comment]
Xcode Clean and removal of derived data didn't do the trick

@maksymmalyhin Here is my podifle.lock

Mysteriously, running off the same branch on a different machine does not cause me this issue. It only began after I updated my pods. I reverted all changes made to an older branch, then ran the older branch off a different machine. Still fails on the original machine though
```
PODS:
  - Crashlytics (3.13.2):
    - Fabric (~> 1.10.2)
  - Fabric (1.10.2)
  - Firebase/Core (6.3.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.0.2)
  - Firebase/CoreOnly (6.3.0):
    - FirebaseCore (= 6.0.3)
  - FirebaseAnalytics (6.0.2):
    - FirebaseCore (~> 6.0)
    - FirebaseInstanceID (~> 4.2)
    - GoogleAppMeasurement (= 6.0.2)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 0.3)
  - FirebaseCore (6.0.3):
    - GoogleUtilities/Environment (~> 6.0)
    - GoogleUtilities/Logger (~> 6.0)
  - FirebaseInstanceID (4.2.0):
    - FirebaseCore (~> 6.0)
    - GoogleUtilities/Environment (~> 6.0)
    - GoogleUtilities/UserDefaults (~> 6.0)
  - GoogleAppMeasurement (6.0.2):
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 0.3)
  - GoogleUtilities/AppDelegateSwizzler (6.2.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (6.2.0)
  - GoogleUtilities/Logger (6.2.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (6.2.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (6.2.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (6.2.0)"
  - GoogleUtilities/Reachability (6.2.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (6.2.0):
    - GoogleUtilities/Logger
COCOAPODS: 1.7.2

```

**Comment by maksymmalyhin** [comment]
@bryan1anderson The `Podfile.lock` content looks correct (consistent version of `FirebaseAnalytics` and `GoogleAppMeasurement`). It looks like the Cocoapods repos ended up in an inconsistent state on your machine for some reason. 
You may try:
1. If you use a repo CDN, then switch back to the main repo (use `source 'https://github.com/CocoaPods/Specs'` in your `Podfile`)
2. [remove](https://guides.cocoapods.org/terminal/commands.html#pod_repo_remove) and [re-add](https://guides.cocoapods.org/terminal/commands.html#pod_repo_add) your Cocoapods repos.
3. If you commit your `Pods` folder to your project repo, you can run `pod deintegrate` then `pod update` to make sure that the `Pods` folder content corresponds to the `Podfile.lock` versions.

**Comment by allenktv** [comment]
@bryan1anderson Definitely sounds like a caching issue. One thing you may try is to run the following:
```
rm -fr Pods/ Podfile.lock; pod cache clean --all
```

Then re-run `pod install --repo-update`

**Comment by bryan1anderson** [comment]
@allenktv That did the trick. This can be closed. Was definitely a caching issue. I've never seen this error with a pod before, should have tried that first.
