### ISSUE TITLE
iOS 12 logEvent crash

### ISSUE THREAD

**Issue by alfonsomestre** [firebase/firebase-ios-sdk#3255]
### [REQUIRED] Step 2: Describe your environment
  * Xcode version: 10.2
  * Firebase SDK version: 6.2.0
  * Firebase Component:
   FirebaseAnalytics 6.0.1 
   FirebaseCore 6.0.2
   FirebaseInAppMessaging 0.15.0
   FirebaseInstanceID 4.1.1
   FirebaseMessaging 4.0.2
   FirebaseRemoteConfig 4.0.0
  * Component version: (FirebaseAnalytics) 6.0.1

### [REQUIRED] Step 3: Describe the problem
App crashes sometimes with users of **iOS 12**

![image](https://user-images.githubusercontent.com/12146194/60118415-b4539600-9752-11e9-9447-1d9b1b18e3ec.png)

The crash is the following:
![image](https://user-images.githubusercontent.com/12146194/60118965-c71a9a80-9753-11e9-8667-d0ed2babedd0.png)

#### Steps to reproduce:

What happened? How can we make the problem occur?
This does not always happen, and it does not have a patter. I leave the crash report:

```
Fatal Exception: NSGenericException
0  CoreFoundation                 0x1f6ec23a8 __exceptionPreprocess
1  libobjc.A.dylib                0x1f60c7d00 objc_exception_throw
2  CoreFoundation                 0x1f6ec1c10 -[__NSSingleObjectEnumerator initWithObject:]
3  libobjc.A.dylib                0x1f60da4a0 objc_enumerationMutation
4  _                  	 		  0x102cd7fa4 +[APMEvent normalizedParametersForParameters:isPublicEvent:]
5  _                              0x102cd8aac -[APMEvent initWithOrigin:isPublic:name:timestamp:previousTimestamp:parameters:]
6  _                              0x102bfd324 __62-[FIRAnalyticsConnector registerAnalyticsListener:withOrigin:]_block_invoke
7  _                              0x102c98c78 +[APMAnalytics notifyEventListenersOnSerialQueue:]
8  _                              0x102c95b00 +[APMAnalytics logEventsOnWorkerQueue:notifyEventListeners:]
9  _                              0x102c96780 +[APMAnalytics logEventOnSerialQueueWithOrigin:isPublicEvent:name:parameters:timestamp:ignoreEnabled:ignoreInterceptor:addedScreenParameters:]
10 _                   			  0x102c96068 __65+[APMAnalytics logEventWithOrigin:isPublicEvent:name:parameters:]_block_invoke_3
11 libdispatch.dylib              0x1f68d0304 _dispatch_call_block_and_release
12 libdispatch.dylib              0x1f68d1884 _dispatch_client_callout
13 libdispatch.dylib              0x1f68d8dd4 _dispatch_lane_serial_drain
14 libdispatch.dylib              0x1f68d9918 _dispatch_lane_invoke
15 libdispatch.dylib              0x1f68e1cc0 _dispatch_workloop_worker_thread
16 libsystem_pthread.dylib        0x1f6acca98 _pthread_wqthread
17 libsystem_pthread.dylib        0x1f6ad2dc4 start_wqthread
```

#### Relevant Code:

There is no relevant code, i just call : `Analytics.logEvent(eventName, parameters: parameters)`

Thanks!

**Comment by paulb777** [comment]
Thanks for the report. Opened internal issue at b/136009423

**Comment by paulb777** [comment]
Thanks again for the report @alfonsomestre. The fix is staged for the next Firebase release milestone - M51 (6.4.0)

**Comment by alfonsomestre** [comment]
Thank you @paulb777! Really appreciate, we will look forward to the next release!

**Comment by at-binhdo** [comment]
@alfonsomestre Is this issue fixed after 6.4.0 release. It seem still happens on our app, which import 6.5.0

**Comment by alfonsomestre** [comment]
Yes @at-binhdo, you are right. It still happens in version 6.5.0

**Comment by paulb777** [comment]
We have a fix coming in next week's 6.7.0

**Comment by alfonsomestre** [comment]
Thanks, @paulb777 !!

**Comment by bogdannedelcu** [comment]
Hello, I am using Firebase with Flutter and I struggle with this error. I have latest version of Firebase and even disabled Analytics but still crashed randomly. The issue is detailed here: https://github.com/flutter/flutter/issues/42599

Thank you!

**Comment by paulb777** [comment]
@bogdannedelcu We are unlikely to be able to help without a reproducible example or a backtrace of the crash - neither of which I see at the flutter issue. If you can get one of those, please open another issue in this repo and we'll investigate.
