### ISSUE TITLE
Calling Storage.reference(...).putFile throws EXC_BAD_ACCESS.

### ISSUE THREAD

**Issue by SujeathPareddy** [firebase/firebase-ios-sdk#3282]
* Xcode version: 10
  * Firebase SDK version: 6
  * Firebase Component: Storage
  * Component version: All of them

Calling `Storage.reference(...).putFile` throws EXC_BAD_ACCESS with a reference to 
```
 - (void)dispatchAsync:(void (^)(void))block {
  dispatch_async(self.dispatchQueue, block);
}
```

The correct way to call this is `Storage.storage().reference()`. Lots of people are pretty confused. See [this post](https://stackoverflow.com/questions/53274252/thread-1-exc-bad-access-trying-to-upload-images-to-firebase/56813181#56813181) and [this](https://stackoverflow.com/questions/49119944/ios-firebase-storage-file-upload-object-does-not-exist).

I feel like a runtime warning would be appropriate if it can be done. I think the self variable is null in this case.

**Comment by schmidt-sebastian** [comment]
@SujeathPareddy Thanks for filing this! I will see what we can do to improve the observed behavior.

**Comment by schmidt-sebastian** [comment]
When #3294 gets merged, we will throw an assertion for calls to `Storage()`, which will prompt the user to use one of the defined API endpoints.
