### ISSUE TITLE
Issue with Remote Config Initialisation 

### ISSUE THREAD

**Issue by mohammedshahid** [firebase/firebase-ios-sdk#3285]
### [READ] Step 1: Are you in the right place?

  Issue with Initialising Remote Config Object in iOS app. 

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2.1 
  * Firebase SDK version: 6.3.0
  * Firebase Component: FirebaseRemoteConfig (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 4.1.0

#### Steps to reproduce:

We run the app in Release mode with Firebase Release Configuration.
We get "RemoteConfig.remoteConfig()" as "uninitialized"

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem

class RemoteConfig : NSObject
{
    fileprivate let firebase = RemoteConfig.remoteConfig()
    
    @objc static let sharedInstance : CTRemoteConfig = {
        let instance = RemoteConfig()
        return instance
    }()
}

```

**Comment by paulb777** [comment]
Was ` FirebaseApp.configure()` invoked previously?

**Comment by mohammedshahid** [comment]
Yes , FirebaseApp.configure() is invoked in didFinishLaunchingWithOptions , and I am sure its invoked before initiating RemoteConfig.

**Comment by paulb777** [comment]
Do any errors get logged in the console?

**Comment by mohammedshahid** [comment]
No errors were logged , it's just that RemoteConfig object is not initialised.
We had to fall back to old version 6.2.0 in which this issue is not observed.

And one more strange thing to note is - It does not affect our debug build configuration. It happens only for our release config.

**Comment by paulb777** [comment]
Also, please confirm that `FirebaseApp.configure()` is actually called before the call to `RemoteConfig()`.  The class static may get called earlier at load time.

**Comment by mohammedshahid** [comment]
Hey Paul, just verified that we are indeed calling FirebaseApp.configure() later. You are right. My Bad.
But it kind of handles gracefully in previous versions(6.2.0)
Anyways I hope calling FirebaseApp.configure() before RemoteConfig() should fix it.
Thanks for helping out.

**Comment by paulb777** [comment]
Thanks for working through it with me @mohammedshahid. We're making initialization changes in 6.4.0 that should make it harder for this error to happen or at least more noticeable when it does.
