### ISSUE TITLE
FIRDocumentChange newIndex not being set as NSNotFound

### ISSUE THREAD

**Issue by Ehesp** [firebase/firebase-ios-sdk#3298]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2.1
  * Firebase SDK version: 5.20.2
  * Firebase Component: Firestore
  * Component version: 5.20.2 (I think)

### [REQUIRED] Step 3: Describe the problem

When removing documents from a collection, the document changes for those removed documents contain the wrong value for the `newIndex`. The code states it should be equal to `NSNotFound`, however it's returning `-1` which gets converted to `4294967295`. 

It's worth noting that `oldIndex` returns the correct value of `NSNotFound`.

#### Steps to reproduce:

1. Add a document to a collection.
2. Remove the document.
3. View the `newIndex` of that document withing document changes.

![image](https://user-images.githubusercontent.com/842078/60605852-2c086d00-9db2-11e9-8a1a-295001aaaafd.png)

**Comment by wilhuff** [comment]
It looks like we broke this in #2608 and there's apparently no test that validates these values. For now the workaround would be to test if the value is >= `NSNotFound`. We'll put together a fix in the meantime.

**Comment by Ehesp** [comment]
Thanks @wilhuff!

**Comment by wilhuff** [comment]
The fix for this will go out with the next release.

**Comment by Salakar** [comment]
Thanks for the quick fix & release @wilhuff 🎉
