### ISSUE TITLE
Firebase/Crashlytics dSYM upload failed when multiple GoogleService-Info / 1 target

### ISSUE THREAD

**Issue by agiguere** [firebase/firebase-ios-sdk#3299]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2.1
  * Firebase SDK version: 6.1.0
  * Firebase Component: Crashlytics
  * Component version: 3.13.1

We installed the Firebase dependancy manually and not with Cocopads

Simple app with 1 target but backend systems are defined in the app settings (settings bundle)

Dev              --> GoogleInfo-Service-dev.plist
Quality .      --> GoogleInfo-Service-dev.plist
Production  --> GoogleInfo-Service.plist

### [REQUIRED] Step 3: Describe the problem
In our app, we have different system we can connect, these backend systems need to be map to the correct Firebase Projects, our systems (dev, quality, production) could be choosen in the app settings (settings.bundle). We have configure 2 projects and map them using the proper google-service file in the appDelegate with FirebaseApp.configure(options: ...)

everybody are talking about changing the GoogleService-Info file in the build phase, but this is not our case so we need to read the settings bundle in the app delegate and initialize the FirebaseApp with the correct GoogleService-Info.plist, with all that said, the problem I found is this.

if we run the app for production (it will used the GoogleInfo-Service.plist), crashes will be reported correctly

but for dev & quality, it's looking for GoogleInfo-Service.plist and not GoogleInfo-Service-dev.plist, so we have to upload the dSYM files manually, 

I was wondering why the dSYM upload when I used GoogleInfo-Service.plist, but not an other name like GoogleInfo-Service-dev.plist

I can see these warnings:
the AdSupport Framework is not currently linked. Some features will not function properly.
Analytics requires Google App ID from GoogleService-Info.plist. Your data may be lost. Google App ID has been changed

thanks

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
        let fileName = isProductionSelectedInSettings() ? "GoogleService-Info" : "GoogleService-Info-dev"
        
        guard let filePath = Bundle.main.path(forResource: fileName, ofType: "plist"),
            let firebaseOptions = FirebaseOptions(contentsOfFile: filePath) else { return }
        
        FirebaseApp.configure(options: firebaseOptions)
```

**Comment by paulb777** [comment]
Internally tracked at b/136680744

**Comment by samedson** [comment]
@agiguere are you using the Fabric Run Script to upload dSYMs? Eg. `${PODS_ROOT}/Fabric/run` in your Run Script Build Phases?

If so, that script automatically grabs the default GoogleService file in your project. Wou'll want to update the script to pass the path to the GoogleService file for each environment of your app.

This is pseudocode (not real shell scripting):
```
if debug then
   `${PODS_ROOT}/Fabric/run --debug --google-service-plist "${PROJECT_DIR}/<path-to-debug-plist>"`
elif quality then
   `${PODS_ROOT}/Fabric/run --debug --google-service-plist "${PROJECT_DIR}//<path-to-quality-plist>"`

... etc.

fi
```

**Comment by agiguere** [comment]
> @agiguere are you using the Fabric Run Script to upload dSYMs? Eg. `${PODS_ROOT}/Fabric/run` in your Run Script Build Phases?
> 
> If so, that `run` script automatically grabs the default GoogleService file in your project if you don't pass the `--google-service-plist` argument. You'll want to update the Run Script Build Phase to pass the path to the GoogleService file for each environment of your app.
> 
> This is pseudocode (not real shell scripting):
> 
> ```
> if debug then
>    `${PODS_ROOT}/Fabric/run --debug --google-service-plist "${PROJECT_DIR}/<path-to-debug-plist>"`
> elif quality then
>    `${PODS_ROOT}/Fabric/run --debug --google-service-plist "${PROJECT_DIR}/<path-to-quality-plist>"`
> 
> ... etc.
> 
> fi
> ```

this is exactly what I was searching for, it make sense, in my case it's an enterprise application and the system (dev, qa, production) could be change in the app settings (settings bundle), so at each build phase I should upload both. Yes I have the build phase config but I am not using CocoaPods,

if I add a second line for sending my dSYM with my GSP-dev file, I got an error

```
"${PROJECT_DIR}/Fabric.framework/run"
"${PROJECT_DIR}/Fabric.framework/run --google-service-plist '${PROJECT_DIR}/OnHand/GoogleService-Info-dev.plist'"
```

OnHand is the name of my app, and this is where the GSP-dev file is, when I ran this I got this error

/Users/alexandregiguere/Documents/Dollarama/Apps/OnHand/Fabric.framework/run --google-service-plist '/Users/alexandregiguere/Documents/Dollarama/Apps/OnHand/OnHand/GoogleService-Info-dev.plist': No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

upload symbols was run in validation mode

thanks

**Comment by samedson** [comment]
Ah this is a quirk of bash syntax. Try out:

"${PROJECT_DIR}/Fabric.framework/run" --google-service-plist '${PROJECT_DIR}/OnHand/GoogleService-Info-dev.plist'

What I did is move the closing double quote from the end of .plist to after `run`. For whatever reason Xcode doesn't like it at the end (I think it's treating everything inside "" as the path to an script / executable).

Hope that helps!

**Comment by agiguere** [comment]
> Ah this is a quirk of bash syntax. Try out:
> 
> "${PROJECT_DIR}/Fabric.framework/run" --google-service-plist '${PROJECT_DIR}/OnHand/GoogleService-Info-dev.plist'
> 
> What I did is move the closing double quote from the end of .plist to after `run`. For whatever reason Xcode doesn't like it at the end (I think it's treating everything inside "" as the path to a script / executable).
> 
> Hope that helps!

awesome that works, I am able to build without errors, let me test it by processing a crash and if everything is good I will close the issue!
