### ISSUE TITLE
Issue with integration Firebase in sub-project

### ISSUE THREAD

**Issue by vishal91** [firebase/firebase-ios-sdk#3304]
* Xcode version: 10.2.1
  * Firebase SDK version: 6.3.0
  * Firebase Component: Analytics and Performance 
  * Component version: 

> I am trying to add Firebase Analytics and Performance to the subproject, Can I even do that? 
Facing issue on 
![Screenshot 2019-07-05 at 1 30 32 PM](https://user-images.githubusercontent.com/3819785/60707339-1cf7fb00-9f29-11e9-9313-ae14408bc790.png)

> Not using Cocoapods, Adding it manually. 

Please help here.

**Comment by ryanwilson** [comment]
Hi @vishal91 thanks for the report.

What exactly do you mean by "subproject"?

For some reason the `modulemap` in GoogleUtilities isn't picking up a required framework, `StoreKit`. If you go to the target options in Xcode, go to the "Build Phases" tab and expand the "Link Binary With Libraries" section you can click the + sign and add `StoreKit`.

Let me know if that works!

**Comment by vishal91** [comment]
@ryanwilson By sub-project, I mean dynamic framework.

**Comment by paulb777** [comment]
The Firebase pods are static frameworks and cannot be dependencies of dynamic frameworks. They can be dependencies of other static frameworks.
