### ISSUE TITLE
document.setData not marked as possibly throwing error

### ISSUE THREAD

**Issue by SujeathPareddy** [firebase/firebase-ios-sdk#3310]
### Environment

  * Xcode version: All
  * Firebase SDK version: All
  * Firebase Component: Firestore (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: All

### Problem

Firestore.firestore().document("...").setData() can throw errors, including ones like `'FIRInvalidArgumentException', reason: 'Nested arrays are not supported'`. However, the Swift function is not marked as throwing, which makes using do/try/catch problematic because the compiler says `No calls to throwing functions occur within 'try' expression` and `'catch' block is unreachable because no errors are thrown in 'do' block`.

#### Steps to reproduce:

```
do {
      try Firestore.firestore().document("...").setData([])
}
catch {
 ...
}
```

**Comment by wilhuff** [comment]
Firestore throws Objective-C exceptions, not Swift errors so you can’t catch these in Swift even if we marked the method `throws`.

Objective-C exceptions don't guarantee resources are cleaned up when thrown so it’s best to treat these as fatal and avoid attempting to recover from them.

In any case, we only throw such exceptions when you’ve made a programming error. In this case you’ve attempted to write data with directly nested arrays, and that will never work.
