### ISSUE TITLE
Domain=FIRAuthErrorDomain Code=17999

### ISSUE THREAD

**Issue by warteruzannan** [firebase/firebase-ios-sdk#3316]
* Xcode version:10.1 (10B61)
  * Firebase SDK version:3.6.0
  * Firebase Component: Auth
  * Component version: 3.1.1

i'm try login with email and password using firebase/auth

The code :
FIRAuth.auth()?.signIn(withEmail: email!, password: senha!) { (user, error) in
       .......      
}

* The email and password is correct.
* Method email/password is activated.
* i has FIRApp.configure() in didFinishLaunchingWithOptions

But always returns the following error..

Error Domain=FIRAuthErrorDomain Code=17999 "An internal error has occurred, print and inspect the error details for more information." UserInfo={error_name=ERROR_INTERNAL_ERROR, NSLocalizedDescription=An internal error has occurred, print and inspect the error details for more information., NSUnderlyingError=0x600000b213e0 {Error Domain=FIRAuthInternalErrorDomain Code=4 "(null)" UserInfo={FIRAuthErrorUserInfoDeserializedResponseKey={}...

The app was working in production  but stopped working yesterday..

**Comment by morganchen12** [comment]
Can you print the whole error?

**Comment by warteruzannan** [comment]
Yes...

Optional(Error Domain=FIRAuthErrorDomain Code=17999 "An internal error has occurred, print and inspect the error details for more information." UserInfo={error_name=ERROR_INTERNAL_ERROR, NSLocalizedDescription=An internal error has occurred, print and inspect the error details for more information., NSUnderlyingError=0x600002489b30 {Error Domain=FIRAuthInternalErrorDomain Code=4 "(null)" UserInfo={FIRAuthErrorUserInfoDeserializedResponseKey={
    displayName = "";
    email = "adelinojatai@gmail.com";
    expiresIn = 3600;
    idToken = "<omited>";
    kind = "identitytoolkit#SignInWithPasswordResponse";
    localId = "<omited>";
    refreshToken = ""<omited>"0";
    registered = 1;
}}}})

**Comment by warteruzannan** [comment]
Yes

Optional(Error Domain=FIRAuthErrorDomain Code=17999 "An internal error has occurred, print and inspect the error details for more information." UserInfo={error_name=ERROR_INTERNAL_ERROR, NSLocalizedDescription=An internal error has occurred, print and inspect the error details for more information., NSUnderlyingError=0x600002489b30 {Error Domain=FIRAuthInternalErrorDomain Code=4 "(null)" UserInfo={FIRAuthErrorUserInfoDeserializedResponseKey={
    displayName = "";
    email = "wscagora@gmail.com";
    expiresIn = 3600;
    idToken = "value";
    kind = "identitytoolkit#SignInWithPasswordResponse";
    localId = "value";
    refreshToken = ""value";
    registered = 1;
}}}})

**Comment by morganchen12** [comment]
@renkelvin looks like Auth is producing an error here despite a successful response. Can you investigate?

**Comment by dkiktenko** [comment]
Check API key restrictions - produced same error with FirebaseAuth only to realize that the iOS key was restricted only to two services (Maps and Firestore).

**Comment by warteruzannan** [comment]
@dkiktenko, 
i check in Google Cloud Platform Console -> credentials ->  iOS key (auto created by Firebase) 
that has no restrictions

**Comment by paulb777** [comment]
@warteruzannan Firebase 3.x is three years old and we're currently at Firebase 6.4.0. I suggest updating to something more recent.

**Comment by Sun3** [comment]
I had the same issue and upgrading to the latest iOS SDK and changing lot's of code does work.

**Comment by paulb777** [comment]
Closing for now. Please open a new issue if it recurs on Firebase 6.x.

**Comment by warteruzannan** [comment]
i fix the issue updating sdk to 4.0.1.  I did not upgrade to the latest version because I would have to change a lot of code... Thanks
