### ISSUE TITLE
Issue while using firebase events inside framework

### ISSUE THREAD

**Issue by mallika2019** [firebase/firebase-ios-sdk#3328]
I have an xcode project. GoogleService-Info.plist is kept in resources.

Scenario 1 (Parent project)
---------------------------
Firebase is configured in AppDelegate as given below.
// Configure Firebase
// ------------------
if FIRApp.defaultApp() == nil {
   FIRApp.configure()            
}

After that, logEvent method is called in a click(click1).
Events got successfully logged and we can view it in Firebase console DebugView.

Scenario 2 (Parent project with TestFrame)
----------------------------------------------
Added a framework named TestFrame. Firebase dependency is added by pod install.GoogleService-Info.plist is added in the root path of the framework.
The framework contains two methods. One to configure Firebase and second one to logEvent.
Now, both configure and logEvent is called from another click (click2).
The result is that, for click2, events got successfully logged and we can view it in Firebase console DebugView. But click1 as described in Scenario 1, doesn't log any events.

Scenario 3(Parent project with TestFrame and AFrame)
-----------------------------------------------------------
Added another framework named AFrame. Firebase dependency is added by pod install.GoogleService-Info.plist is added in the root path of the framework.
The framework contains two methods. One to configure Firebase and second one to logEvent.
Now, both configure and logEvent is called from another click (click3).
The result is that, for click1 and click3, no events got logged. However, 
events got successfully logged for click2(scenario2) and we can view it in Firebase console. 

Scenario 4(Parent project with TestFrame, AFrame and UFrame)
---------------------------------------------------------------------
Added one more framework named UFrame. Firebase dependency is added by pod install.GoogleService-Info.plist is added in the root path of the framework.
The framework contains two methods. One to configure Firebase and second one to logEvent.
Now, both configure and logEvent is called from another click (click4).
The result is that, for click1,click2, and click3, no events got logged. However, events got successfully logged for click4(scenario4) and we can view it in Firebase console.

So, firebase behaves in such a way that it considers only the embedded frameworks (if present) for logging events and that also in the alphabetical order.  That is, only the events specified in the last framework in alphabetical order is considered. In this case UFrame.

Can anyone help me detailing how to solve this issue?

**Comment by paulb777** [comment]
The Firebase pods are static frameworks and do not work as dependencies of dynamic frameworks. A framework that depends on Firebase must also be linked statically.
