### ISSUE TITLE
Auth - shared keychain: other running apps don't get notified about user changes

### ISSUE THREAD

**Issue by Johnson145** [firebase/firebase-ios-sdk#3353]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2.1
  * Firebase SDK version: 6.4.0
  * Firebase Component: Auth
  * Component version: 6.2.0

### [REQUIRED] Step 3: Describe the problem
I got a group of apps set up to use the same auth state by accessing a shared keychain. If only one of those apps is running, everything works as expected: If I login a user in that app and start another app of the group afterwards, both apps use the same user.

However, it does not work correctly, if another app is running in the background already. When I change the user in the foreground app and switch back to the other one, the latter is not informed about the new user. Neither the `authStateChangeListener` is triggered nor does the global user instance reflect the change.

As a workaround, this issue can be fixed by re-setting the user access group each time the app gets back into the foreground

```swift
func applicationWillEnterForeground(_ application: UIApplication) {
..
Auth.auth().useUserAccessGroup(KEYCHAIN_ACCESS_GROUP_KEY)
..
}
```

#### Steps to reproduce:
- set up (at least) two apps to use the same shared keychain
- open the first app and login with user A
(do not close the first app, but minimize it)
- open the second app. user A is logged in there, too. switch to user B
- minimize the second app and re-open the first one
- user A is still logged in there, although user B should be logged in

**Comment by renkelvin** [comment]
This is an intended behavior.

The Auth instance only check the stored user once when the app is launched. The reason is that there could be pending changes with the signed in user. Firebase Auth won't automatically switch the user on behalf of the developers.

`authStateChangeListener` get triggered after the user is actually changed.

**Comment by Johnson145** [comment]
In that case this behavior should at least be explained in the docs, shouldn't it?
E.g. [the docs say that the shared keyshain allows to:](https://firebase.google.com/docs/auth/ios/single-sign-on)

> Sign in once and be signed in across all apps that belong to the same access group.
> Sign out once and be signed out across all apps that belong to the same access group.

So I guess the described behavior isn't what one may have in mind after reading this.

**Comment by morganchen12** [comment]
I'll add a note to the docs.

**Comment by morganchen12** [comment]
cr/260180033
