### ISSUE TITLE
Firebase dynamic links -- iOS manual URL construction

### ISSUE THREAD

**Issue by dloic** [firebase/firebase-ios-sdk#3354]
Hi there,

We're building dynamic links manually, using the following documentation: https://firebase.google.com/docs/dynamic-links/create-manually?authuser=0

On our Firebase projects, we have a set of 8 iOS apps, each one using a different bundle id.
For iOS, the documentation says we need to use the **ibi** parameter to specify "the bundle id of the iOS app to use to open the link". 

Unfortunately, the behavior we see is the following when opening a dynamic link, either from simulator or real device (tested on iOS 12.X and iOS 13.X):
- giving the **ibi** parameter does not ensure to open the proper application
- giving no **ibi** parameter still open app
- we saw that the application opened on device (a device where all the 8 apps are installed) is the first defined in the **apple-app-site-association**, no matter what we provide as **ibi**
- if we remove from the device the first app listed in **apple-app-site-association**, then the dynamic links will open the second one from **apple-app-site-association**, etc.

Our projects are well configured, with a custom url scheme set to **bundle identifier**

So app _A with com.app.A_ defines the custom url scheme _com.app.A://_ and _app B with com.app.B_ defines the custom url scheme _com.app.B://_, which are working fine if tested from Safari.

  * Xcode version: 10.X, 11.X
  * iOS version: 12.X, 13.X
  * Firebase SDK version: 6.40
  * Firebase Component: Dynamic links
  * Component version: 6.40

Is it something broken or a known issue on Firebase team?

Thanks for your help.

**Comment by dmandar** [comment]
If your app is already installed, it will be opened using iOS universal links (using the appids mentioned in the app site association file.) If this is a custom domain, you can try editing the app-site-association-file to include paths specific to each of your apps.

**Comment by dloic** [comment]
Hi @dmandar,

Thanks for your suggestion. It was my guess that **IBI** would not be used, now this is confirmed. Could be good to add this in the documentation for others.

We'll try with custom domain and manual edit of the app-site-association-file, as described here: https://github.com/firebase/firebase-tools/issues/1169
