### ISSUE TITLE
FCM v1 push payload not invoking service extension iOS

### ISSUE THREAD

**Issue by amitlad** [firebase/firebase-ios-sdk#3368]
We are using FCM as a backend for push notification with new HTTP v1 
POST https://fcm.googleapis.com/v1/projects/myproject-b5ae1/messages:send

We have followed this link to setup the server https://firebase.google.com/docs/cloud-messaging/migrate-v1

push payload is as follows:
```
{
  "message": {
    "token": "",
    "notification": {
      "title": "",
      "body": "Notification"
    },
    
    "android": {
      "notification": {
        "click_action": "android.intent.action.MAIN"
      }
    },
    "apns": {
      "headers": {
        "apns-priority": "10",
      },
      "payload": {
        "aps": {
          "badge": 1
        },
        
                  "mutable_content": 1,
          "content_available" : 1,
        "data": {
          "title": "",
          "body": "",
          "image": "",
        }
      }
    }
  }
}
```

Everything is working fine on Android however FCM with iOS is not invoking the service extension for rich push notificatio if we use Http v1 mechanism.
Service Extension is invoked if we use the old FCM massaging  mechanism POST https://fcm.googleapis.com/fcm/send

How to fix this problem? Can anyone let us know what is going wrong with iOS?

**Comment by morganchen12** [comment]
If you're sending the same notification payload, the behavior on the client should be the same regardless of whether or not you're sending via HTTP legacy or HTTP v1. Can you log the receiverd payload on the client and post the results here?

**Comment by amitlad** [comment]
I am sharing the details about both Http & Http v1 api request details from
ARC tool & received payload on iOS for rich push notifications using iOS service extension mechanism.

**1. Legacy Http - https://fcm.googleapis.com/fcm/send with legacy request payload
Request:**
{
 "to" : "iOS device token",
  "content_available" : true,
    "mutable_content": true,
    "priority" : "high",
    "category" : "myCategory",
 "data" : {
   	"body" : "notification",
     "title": "Ricoh Arena",
     "link": "value",
     "web_link": "value1",
   	 "image": "https://ibin.co/2t1lLdpfS06F.png",
   	 "media_type":"image",
   	 "category" : "myCategory",
     "actions": [{
            "action": "yes",
            "title": "Yes",
            "image": "https://green_tick.png"
        }, {
            "action": "dismiss",
            "title": "Dismiss",
            "image": "https://red_cross.png"
        }]
 },
 "notification":
    {
       "body": "notification",
       "sound": "default",
       "title":"Arena",
       "category" : "myCategory"
    }
}

**Response: 200

Push payload as received on iOS:**
[AnyHashable("glide_link"): "value", AnyHashable("actions"): [{"image":"https:\/\/green_tick.png","action":"yes","title":"Yes"},{"image":"https:\/\/red_cross.png","action":"dismiss","title":"Dismiss"}], AnyHashable("gcm.notification.category"): myCategory, AnyHashable("web_link"): , AnyHashable("google.c.a.e"): 1, AnyHashable("body"): Want Cheaper Parking This Weekend?, AnyHashable("category"): myCategory, AnyHashable("media_type"): image, AnyHashable("gcm.message_id"): 1563345549404639, AnyHashable("title"):  Arena, AnyHashable("image"): https://ibin.co/2t1lLdpfS06F.png, AnyHashable("aps"): {
    alert =     {
        body = "notification";
        title = "Arena";
    };
    "content-available" = 1;
    "mutable-content" = 1;
    sound = default;
}]

**2. Http - https://fcm.googleapis.com/v1/projects/glide-newpark/messages:send with new message request payload
Request:**
{
  "message": {
    "token": "device token",
    "notification": {
      "title": "",
      "body": "Notification from FCM"
    },
     "data": {
          "title": "Glide",
          "body": "Cheaper Parking?",
          "internal_url": "glide",
          "category": "myCategory",
          "external_url": "glide",
          "image": "glide",
          "actions": "[{\"Name\":\"yes\",\"Title\":\"Yes\",\"Image\":\"glide\"}]"
        },
    "android": {
      "notification": {
        "click_action": "android.intent.action.MAIN"
      }
    },
    "apns": {
      "headers": {
        "apns-priority": "10",
      },
      "payload": {
        "aps": {
          "badge": 1
        },
        "mutable_content": true,
        "content_available" : true,
       
      }
    }
  }
}

**Response: 200

Push payload as received on iOS:**
[AnyHashable("data"): {
    actions = "[{\"Name\":\"yes\",\"Title\":\"Yes\",\"Image\":\"glide\"}]";
    body = "Cheaper Parking?";
    category = myCategory;
    "external_url" = glide;
    image = glide;
    "internal_url" = glide;
    title = Glide;
}, AnyHashable("content_available"): 1, AnyHashable("mutable_content"): 1, AnyHashable("aps"): {
    alert =     {
        body = "Notification from FCM";
    };
    badge = 1;
}, AnyHashable("google.c.a.e"): 1, AnyHashable("gcm.message_id"): 1563345620973328]


**3. Legacy Http - https://fcm.googleapis.com/fcm/send with message request payload
Request**
{
  "message": {
    "token": "cD4-Ieo-L0U:APA91bHR7rsTtpoeaM88cjyk9En36YVsckF2khsAvbCXFt1YyEZMQRsS8VS5GKwYZzqEFGqE9KHV_RamVgfxeqcoavsIhsxHkkQIWVLr1tl99s7ceXuKwCD04oXdpTLe_ZWzDzt1Y_TG",
    "notification": {
      "title": "",
      "body": "Notification from FCM"
    },
    
    "android": {
      "notification": {
        "click_action": "android.intent.action.MAIN"
      }
    },
    "apns": {
      "headers": {
        "apns-priority": "10",
      },
      "payload": {
        "aps": {
          "badge": 1
        },
        "mutable_content": true,
        "content_available" : true,
        "data": {
          "title": "Glide",
          "body": "Cheaper Parking?",
          "internal_url": "glide",
          "category": "myCategory",
          "external_url": "glide",
          "image": "glide",
          "actions": "[{\"Name\":\"yes\",\"Title\":\"Yes\",\"Image\":\"glide\"}]"
        }
      }
    }
  }
}

**Response: 400 Bad Request**

**4.  Http - https://fcm.googleapis.com/v1/projects/glide-newpark/messages:send with legacy request payload
Request:**
{
 "to" : "iOS device token",
  "content_available" : true,
    "mutable_content": true,
    "priority" : "high",
    "category" : "myCategory",
 "data" : {
   	"body" : "Want Cheaper Parking This Weekend?",
     "title": "Ricoh Arena",
     "link": "",
     "web_link": "",
   	 "image": "https://ibin.co/2t1lLdpfS06F.png",
   	 "media_type":"image",
   	 "category" : "myCategory",
     "actions": [{
            "action": "yes",
            "title": "Yes",
            "image": "https://green_tick.png"
        }, {
            "action": "dismiss",
            "title": "Dismiss",
            "image": "https://red_cross.png"
        }]
 },
 "notification":
    {
       "body": "notification",
       "sound": "default",
       "title":"Arena",
       "category" : "myCategory"
    }
}

**Response: 400 Bad Request
{**
"error": {
"code": 400,
"message": "Invalid JSON payload received. Unknown name "to": Cannot find field. Invalid JSON payload received. Unknown name "content_available": Cannot find field. Invalid JSON payload received. Unknown name "mutable_content": Cannot find field. Invalid JSON payload received. Unknown name "priority": Cannot find field. Invalid JSON payload received. Unknown name "category": Cannot find field. Invalid JSON payload received. Unknown name "data": Cannot find field. Invalid JSON payload received. Unknown name "notification": Cannot find field.",
"status": "INVALID_ARGUMENT",
"details": [
  {
"@type": "type.googleapis.com/google.rpc.BadRequest",
"fieldViolations": [
  {
"description": "Invalid JSON payload received. Unknown name "to": Cannot find field."
},
  {
"description": "Invalid JSON payload received. Unknown name "content_available": Cannot find field."
},
  {
"description": "Invalid JSON payload received. Unknown name "mutable_content": Cannot find field."
},
  {
"description": "Invalid JSON payload received. Unknown name "priority": Cannot find field."
},
  {
"description": "Invalid JSON payload received. Unknown name "category": Cannot find field."
},
  {
"description": "Invalid JSON payload received. Unknown name "data": Cannot find field."
},
  {
"description": "Invalid JSON payload received. Unknown name "notification": Cannot find field."
}
],
}
],
}
}

**Comment by amitlad** [comment]
I figured out what was the issue "mutable_content" should be "mutable-content" and "content_available" should be "content-available". 
Also update the apns tag as "apns": { "payload": { "aps": { "mutable-content": 1, "content-available" : 1 } }
