### ISSUE TITLE
Remote Config Permission Denied Error

### ISSUE THREAD

**Issue by aodhol** [firebase/firebase-ios-sdk#3378]
### Environment

  * Xcode version: 10.2.1
  * Firebase SDK version: 6.4.0
  * Firebase Component: Remote Config & Auth
  * Component version: 4.2.0 / 6.2.0

### Describe the problem

Remote Config fetch results in an error:
 
```Error Domain=com.google.remoteconfig.ErrorDomain Code=8003 "RCN Fetch Failure: Server returned error:code: 403. Status: PERMISSION_DENIED. Message: Requests to this API firebaseremoteconfig.googleapis.com method google.firebase.remoteconfig.v1.RemoteConfigService.FetchRemoteConfig are blocked." UserInfo={NSLocalizedDescription=RCN Fetch Failure: Server returned error:code: 403. Status: PERMISSION_DENIED. Message: Requests to this API firebaseremoteconfig.googleapis.com method google.firebase.remoteconfig.v1.RemoteConfigService.FetchRemoteConfig are blocked.}```

The same issue is occurring for Auth.

#### Steps to reproduce:

Launch the App.

Note, prior to updating to the latest, from 4.0.0 all seemed fine and the live App is using that version...

**Comment by morganchen12** [comment]
I suspect this is a project-scoped issue. You should file a ticket at [Firebase Support](https://firebase.google.com/support) and they'll be able to look at your project logs, including detailed error messages for why your requests are returning 403.

**Comment by aodhol** [comment]
@morganchen12 Thanks - I suspected as much and filed a ticket with them - the error might want to indicate though this so that I wouldn't waste your time here :)

**Comment by aodhol** [comment]
@morganchen12 Unfortunately, The support team said the project is fine...

**Comment by morganchen12** [comment]
Interesting. Are you able to reproduce this project using a different Firebase account in the same Xcode project?

**Comment by aodhol** [comment]
@morganchen12 Potentially but what if it was paid for by the same card?

**Comment by morganchen12** [comment]
I don't think payment method should affect this issue. Can you share your project, or a sample repro?

**Comment by aodhol** [comment]
@morganchen12 I can't, however, support has this info: #00002225

**Comment by morganchen12** [comment]
Support only has the AppDelegate and your config files, all of which look fine. I was able to copy-paste your AppDelegate into the [ABTesting quickstart](https://github.com/firebase/quickstart-ios/tree/master/abtesting) after removing Branch, Braintree, and Crashlytics (and adding Auth and Messaging) and it ran without error.

Can you create a sample project that reproduces this or share a zip of your full project?

**Comment by dmandar** [comment]
@aodhol can you confirm if your bundleID in your googleservice-info.plist file is the same as the app you are making fetch requests from? Also, are you using Perf SDK as well?

**Comment by aodhol** [comment]
@dmandar Yes, they're the same and I'm not using the Perf SDK.

**Comment by morganchen12** [comment]
Have you set any [key restrictions](https://developers.google.com/maps/api-key-best-practices#restrict_apikey) on your API keys in Cloud console?

**Comment by Kukiwon** [comment]
I resolved this by replacing the existing GoogleService-Info.plist with a new one downloaded from Firebase (Project Settings -> Download latest Config file). 

Looking at the changes between the old and the new file, I noticed that they API keys is different from my older version. This might be the cause of the 403 errors.

**Comment by dmandar** [comment]
@aodhol are you still seeing the issue? Can you make sure you have the latest GoogleServicePlist.info file as @Kukiwon  mentioned?

**Comment by aodhol** [comment]
@dmandar It's not happening anymore and even without downloading the latest GoogleService-Info.plist so that may be a red-herring. I would like to get to the bottom of it, however..

**Comment by dmandar** [comment]
Thanks for confirming. Pls reopen if you are able to repro again.
