### ISSUE TITLE
fcmToken is nil, even though FCM_swizzle_appDidRegisterForRemoteNotifications ran

### ISSUE THREAD

**Issue by bcattle** [firebase/firebase-ios-sdk#338]
I'm running the code in this repository, commit cfef233. 

### Step 2: Describe your environment

  * Xcode version:  9.0 (9A235)
  * Firebase SDK version: commit cfef233
  * Firebase Component: Messaging
  * Component version: ?

### Step 3: Describe the problem

After registering for APNS notifications, the `Messaging.messaging().fcmToken` is nil, and the delegate method `messaging(_ messaging: Messaging, didRefreshRegistrationToken fcmToken: String)` is never called. 

#### Steps to reproduce:

1. I am running Firebase Messaging with method swizzling on. The `FirebaseAppDelegateProxyEnabled` is set to `YES` in my `Info.plist` file.
2. I register for remote notifications, and put a breakpoint in my `application( _ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data )` function.
3. When my code stops on that breakpoint, I can see that the method swizzling correctly ran, because the `FCM_swizzle_appDidRegisterForRemoteNotifications` method is in the call stack:

<img width="333" alt="screen shot 2017-10-05 at 6 00 34 pm" src="https://user-images.githubusercontent.com/620058/31258872-4701cf58-a9f7-11e7-8788-8a7a0eb3a7b5.png">

4. At that point in execution, the `Messaging.messaging().fcmToken` value is nil. 
5. The `messaging(_ messaging: Messaging, didRefreshRegistrationToken fcmToken: String)` delegate method is never called
6. Pressing run, then pausing the app again 60 seconds later, the `Messaging.messaging().fcmToken` value is still nil.

**Comment by bcattle** [comment]
Also, if I try to explicitly request a token with a specific senderID, the callback function never runs. 

```
Messaging.messaging().retrieveFCMToken(forSenderID: "server") { (fcmToken, error) in
    print("Got token \(fcmToken)")                     // <-- Never gets here
}
```

**Comment by paulb777** [comment]
Will you try with the latest master, the 0.1.3 tag, or the published latest FirebaseCommunity pod?

There were fixes to both FirebaseMessaging and FirebaseInstanceID after the cfef233 commit

**Comment by bcattle** [comment]
After digging into this a little bit more, the specific problem appears to be at FIRMessagingInstanceIDProxy.m [lines 83-86](https://github.com/firebase/firebase-ios-sdk/blob/31a2acb7497eaaeae38b7ceb17edcab09d7f2866/Firebase/Messaging/FIRMessagingInstanceIDProxy.m#L83-86):

<img width="680" alt="screen shot 2017-10-05 at 6 25 15 pm" src="https://user-images.githubusercontent.com/620058/31259361-f32a5dba-a9fa-11e7-99d4-935cd6b61d05.png">

This code is failing silently and returning because `proxy` is nil.

**Comment by bcattle** [comment]
Trying tag 0.1.3, same behavior as described -- both `fcmToken` and `proxy` is nil
Trying master, same behavior as described -- both `fcmToken` and `proxy` is nil

**Comment by bcattle** [comment]
I initialize the code with 

```
        FirebaseApp.configure()
        Messaging.messaging().delegate = self
```

**Comment by paulb777** [comment]
Did you rerun pod update to get the latest FirebaseInstanceID?

**Comment by bcattle** [comment]
I edited my Podfile to contain 
```
    pod 'FirebaseCommunity/Core', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'master'
    pod 'FirebaseCommunity/Storage', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'master'
    pod 'FirebaseCommunity/Auth', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'master'
    pod 'FirebaseCommunity/Database', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'master'
    pod 'FirebaseCommunity/Messaging', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'master'
```
And then ran `pod update`.

How do I know if I have the latest `FirebaseInstanceID`?
Thanks.

**Comment by paulb777** [comment]
Ah, looks like a documentation issue for FirebaseCommunity.

For FirebaseCommunity/Messaging to work properly, FirebaseInstanceID must also be linked into the app. The Podfile should have a line like https://github.com/firebase/firebase-ios-sdk/blob/master/Example/Podfile#L117.

Once CocoaPods 1.4.0 is available, we'll be able to define the correct dependencies in the podspec for FirebaseMessaging.

**Comment by bcattle** [comment]
Thanks Paul, that fixed it. Want me to add an assertion? If so, where should it be? On that `instanceIDProxy` value?

**Comment by paulb777** [comment]
@bcattle Thanks for raising this issue! I made #343 to fix the docs. 

We'll follow up on the best code change. Once CocoaPods 1.4.0 comes out, we'll have a build time dependency.

**Comment by bcattle** [comment]
Thanks Paul!
