### ISSUE TITLE
dynamic link with custom domain doesn't work with the first launch of the application after iOS Application installed

### ISSUE THREAD

**Issue by AJereli** [firebase/firebase-ios-sdk#3380]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2.1 
  * Firebase SDK version: 4.13.0
  * Firebase Component:  Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: Core - 4.0.20, FirebaseDynamicLinks - 2.3.2

### [REQUIRED] Step 3: Describe the problem

First, I connected my domain in Firebase Hosting and created Dynamic Links with a custom domain. 
I set up my firebase dynamic links for iOS application step by step with the official tutorial. The link works as expected except in one case. When the application is not installed, a transition occurs in the AppStore, the application is installed, but when it is opened, the function application: openURL: options: is not called (Deployment target 9.3). As a result, it is impossible to call the necessary code when you first open the application after installing it by link.
But same code work in the case, when I use standard firebase suffix domain (xxx.page.link). Codebase and parameters of link do not change in this case, only link suffix (from custom to standard)

#### Steps to reproduce:

1. Create a dynamic link with the custom domain in the firebase console.
2. Setup iOS application for this link.
3. Remove application
4. Go to created dynamic link 
5. Go to AppStore
6. Install application from XCode, simulating installation from AppStore.
7. Open app.

#### Relevant Code:

Output of dynamic link diagnostic:
```
---- Firebase Dynamic Links diagnostic output start ----
Firebase Dynamic Links framework version 2.3.2
System information: OS iOS, OS version 12.3.1, model iPhone
Current date 2019-07-18 09:39:44 +0000
Device locale en-US (raw en_US), timezone Europe/Moscow
	Specified custom URL scheme is com.xxx.XXX and Info.plist contains such scheme in CFBundleURLTypes key.
	AppID Prefix: P6A385CN94, Team ID: P6A385CN94, AppId Prefix equal to Team ID: YES
performDiagnostic completed successfully! No errors found.
---- Firebase Dynamic Links diagnostic output end ----
```

Debug mode of dynamic link give only one warning:
```
There is no configuration to prevent phishing on this domain. Setup URL patterns to whitelist in the Firebase Dynamic Links console.
```

apple-app-site-association file exists and meets requirements
```
{"applinks":{"apps":[],"details":[{"appID":"P6A385CN94.com.xxx.XXX","paths":["NOT /_/*","/*"]}]}}
```

**Comment by paulb777** [comment]
@AJereli Thanks for the report. Please try a more recent version of Firebase. The version you're using is a year and a half old and the latest is now Firebase 6.4.0.

**Comment by AJereli** [comment]
@paulb777 
Seem like a can't update this pod. Can it be related to that I use obj-c project?

**Comment by paulb777** [comment]
@AJereli It's likely related to something in your Podfile that doesn't work with Firebase 6. You can see the details by examining the generated `Podfile.lock`.
