### ISSUE TITLE
FR: Add 'cacheThenServer' to read from cache first

### ISSUE THREAD

**Issue by uuunk** [firebase/firebase-ios-sdk#3393]
For times where there is slow network access or the datasets are large, on snapshotListeners and document gets it would be great to be able to be able to set a `cacheThenServer` flag to be able to read from the local cache first, then to update with server data. If new/different data exists, the event would fire again.

Referencing the discussion here:
https://github.com/flutter/flutter/issues/19078

I apologize if this is a duplicate, couldn't find a discussion here though.

**Comment by wilhuff** [comment]
What you’re asking for is exactly how snapshot listeners work. They read from cache and return an initial snapshot. When data is available from the server more snapshots are generated.

Note that any local changes that affect the query will also generate snapshots so if you’re interested in waiting until you have a snapshot from the server, add your snapshot listener with include metadata changes enabled. Keep listening until you get a snapshot whose metadata indicates `fromCache` is false.
