### ISSUE TITLE
Issue on fetching data using  getDocuments - "Missing or insufficient permissions."

### ISSUE THREAD

**Issue by bishalg** [firebase/firebase-ios-sdk#3399]
**Overview of the Issue** 
Getting Error Code 7 - Missing Permissions for Get request.

**Motivation for or Use Case**
Same query using **_ListenerRegistration_** is working

**Browsers and Operating System**
iPhone - iOS 12, 
FirebaseCore 6.0.4

**Reproduce the Error**
```
import Firebase

class FireStore {
  var db: Firestore! 
}

class DebtsInfoFireStore: FireStore {
  
  class func shared() -> DebtsInfoFireStore {
    return sharedManager
  }
  
  private let storeName = "DebtsInfo"
  
  private static let sharedManager: DebtsInfoFireStore = {
    let manager = DebtsInfoFireStore()
    let settings = FirestoreSettings()
    Firestore.firestore().settings = settings
    manager.db = Firestore.firestore()
    return manager
  }()

  public func store(debts: Parameters) {
    let collection = Firestore.firestore().collection(storeName)
    guard let user = Auth.auth().currentUser else { return }
    var userData = debts
    userData["userID"] = user.uid
    collection.addDocument(data: userData) { (error) in
      print("Error \(String(describing: error))")
    }
  }
  
  public func fetchAllDebts(completion: @escaping (_ result: [DebtsInfo]?) -> ()) {
    db.collection(storeName).getDocuments { (snapshot, error) in
      guard let snapshot = snapshot else {
        print("Error fetching snapshot results: \(error!)")
        return
      }
      let models = snapshot.documents.map { (document) -> DebtsInfo? in
        if let model = DebtsInfo(dictionary: document.data()) {
          return model
        } else {
          print("Unable to initialize type \(DebtsInfo.self) with dictionary \(document.data())")
          return nil
        }
      }
      completion(models as? [DebtsInfo])
    }
  }
  
}
```

**Database Rule** 
```
service cloud.firestore {
  match /databases/{database}/documents {
  
    match /DebtsInfo/{debtsInfo} {
      allow read: if request.auth != null
        						&& request.auth.uid == request.resource.data.userID;
      allow create: if request.auth != null;
      allow write: if request.auth != null 
                     && request.auth.uid == request.resource.data.userID;
    }
 }
}
```

**Sample Code - Similar to above** 
[Code](https://github.com/firebase/snippets-ios/blob/bf623dcd8eb9c2832d2b324bcca6abd88e39de40/firestore/swift/firestore-smoketest/ViewController.swift#L808-L816)

**Issue** 
Error Domain=FIRFirestoreErrorDomain Code=7 "Missing or insufficient permissions."

**Fire Store Screenshot**
<img width="1041" alt="Debts Info Collection" src="https://user-images.githubusercontent.com/805689/61504131-0312e980-a9fa-11e9-9a92-8a9312951026.png">

**Comment by morganchen12** [comment]
Please correct me if I'm wrong--it looks like you're querying the entire collection and expecting security rules to exclude all the documents that cannot be read. This is [explicitly not a feature of security rules](https://firebase.google.com/docs/firestore/security/rules-conditions#rules_are_not_filters); you should be using a filtered query instead. Something like

```swift
db.collection(storeName).filter(whereField: "userID", isEqualTo: user.userID)
```

**Comment by bishalg** [comment]
@morganchen12 : Yes as per Security Rules Link you have provided it states - **Security Rules are not filters**. But in my security concern is simple **only the users who write the data should be able to read it**. 

If I change the rule - 
```
match /DebtsInfo/{debtsInfo} {
      allow read: if request.auth != null;
      allow create: if request.auth != null;
      allow write: if request.auth != null 
                     && request.auth.uid == request.resource.data.userID;
}
```

The iOS fetching code works but as you have  suggested that would need to filter out other users data on client side. 

For which the code is like 
```
 db.collection(storeName).whereField("userID", isEqualTo: user.uid)
      .getDocuments { (snapshot, error) in
```

But my requirements is I just need to fetch the data written users and not other users so its is rather a case of security rules and not a filter.
Right now I am manually adding User ID field to each of the written data for filtering users data. Which again I think is not the proper way for securing user data.

So can you suggest me the simple **Security Rules** which allows read only data written by a users who have written the data.

**Comment by bishalg** [comment]
So I think I solved the issue with change of security rules as follows - 

```
match /DebtsInfo/{debtsInfo} {
      allow read: if request.auth != null
      	&& request.auth.uid == resource.data.userID;
      allow create: if request.auth != null;
      allow write: if request.auth != null 
          && request.auth.uid == request.resource.data.userID;
}
```

The change I made is - 

Previously it was 
 `request.auth.uid == request.resource.data.userID;`
Now it is 
`request.auth.uid == resource.data.userID;`

So I think if is added as an example on documentation it would be helpful to others as well.
Also if there is already the resource on the difference about `resource.data` vs `request.resource` on read vs write it would be helpful.

**Comment by morganchen12** [comment]
That's documented [here](https://firebase.google.com/docs/reference/rules/rules.firestore.Request). I'll take a look at updating the docs to make it more clear. In the meantime, I'll close this issue since it seems your issue is resolved.

Thanks for filing!
