### ISSUE TITLE
[FIRApp configure] crashes app on ios simulator

### ISSUE THREAD

**Issue by mjmaix** [firebase/firebase-ios-sdk#340]
* Xcode version: Version 9.0 (9A235)
  * Firebase SDK version: Firebase/Core (4.3.0)
  * Firebase Component: Core
  * Component version: _____

#### Steps to reproduce:

Running my RN app with `react-native run-ios` is working until integrating firebase on `ios/AppDelegate.m` file. After adding, the app crashes after showing (> 1 sec)

(did `pod update` and/or `pod install` after manually removing `Pods` folder)

See this this recording: http://recordit.co/Ry74pTUpmC

I'm using iPhone 6 (iOS 11.0) simulator

This is the system log
```

Oct  6 16:14:54 Michael-MBP com.apple.CoreSimulator.SimDevice.D1B5DE36-2EA8-4AB5-A760-73F98649F1B3[19245] (com.apple.videosubscriptionsd[20973]): Service exited with abnormal code: 1
Oct  6 16:14:55 Michael-MBP com.apple.CoreSimulator.SimDevice.D1B5DE36-2EA8-4AB5-A760-73F98649F1B3[19245] (com.apple.videosubscriptionsd): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Oct  6 16:14:56 Michael-MBP RNFirebase3[20976]: assertion failed: 17A365 15A372: libxpc.dylib + 69578 [D870A237-D3A7-31F5-AAD4-CE880C0C8E7B]: 0x7d
Oct  6 16:15:05 Michael-MBP com.apple.CoreSimulator.SimDevice.D1B5DE36-2EA8-4AB5-A760-73F98649F1B3[19245] (com.apple.videosubscriptionsd[20977]): Service exited with abnormal code: 1

```

#### Relevant Code:

see commit on my sample app https://github.com/mjmaix/RNFirebase3/commit/4040fffc504f3fb002d76f146c717598b267dcba and https://github.com/mjmaix/RNFirebase3/commit/a95959c7cee519319ac82bdbb2951592dd1ef7cb

#### other info:

`GoogleService-Info.plist` exists on local repo but ignored on commit

```
gem which cocoapods
/Users/mick/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-1.3.1/lib/cocoapods.rb
```

```
npm --version
5.4.2
```

**Comment by ryanwilson** [comment]
Hey @mjmaix - instead of `import <Firebase.h>` try `import <Firebase/Firebase.h>`.  Let me know how that goes!

**Comment by mjmaix** [comment]
@ryanwilson 

Thank you for checking. Just tried `#import <Firebase/Firebase.h>` with `react-native run-ios` but it's still now starting as expected

system log
```
Oct  6 22:39:39 Michael-MBP com.apple.CoreSimulator.SimDevice.D1B5DE36-2EA8-4AB5-A760-73F98649F1B3[22099] (com.apple.videosubscriptionsd[22703]): Service exited with abnormal code: 1
Oct  6 22:39:41 Michael-MBP RNFirebase3[22706]: assertion failed: 17A365 15A372: libxpc.dylib + 69578 [D870A237-D3A7-31F5-AAD4-CE880C0C8E7B]: 0x7d
```

**Comment by ryanwilson** [comment]
Hmm thanks for trying. Is there anything above that in the log about where in the process it fails? I haven't used React Native before so trying to figure out where this is failing.

**Comment by mjmaix** [comment]
None, cause I cleared the system log before `react-native run-ios`. Do you
want to see the startup logs? It's quite long though

**Comment by ryanwilson** [comment]
If you could share the stack trace where it crashes from the system log, that'd be great! I guess this can be done [like this](https://facebook.github.io/react-native/docs/debugging.html#accessing-console-logs) (apologies if you already knew this, I'm learning this as we go 😛 )

**Comment by mjmaix** [comment]
I'll also check this more tomorrow, I'll post updates

**Comment by ryanwilson** [comment]
Looks like you should still be able to grab them from the simulator log (from [this comment](https://github.com/wix/detox/issues/158#issuecomment-307242513): 
    
    tail -100 -f ~/Library/Logs/CoreSimulator/{simulator udid}/system.log

Should grab the last 100 lines of the log. If you have more than one simulator, you can get the UDID by running `instruments -s devices`.

Sounds good, keep me in the loop!

**Comment by mjmaix** [comment]
I did some experiments by creating xcode project with firebase pod install. It's not crashing like in react-native. Maybe this is not a problem on firebase-ios-sdk?

**Comment by mjmaix** [comment]
Fixed it, I opened the project on xcode using `.xcworkspace`, run the app 
By doing this, the logs would remain even after the app crashed.

```
*** Terminating app due to uncaught exception 'com.firebase.core', reason: '`[FIRApp configure];` (`FirebaseApp.configure()` in Swift) could not find a valid GoogleService-Info.plist in your project. Please download one from https://console.firebase.google.com/.'
```
Missing `GoogleService-Info.plist`
Apparently, I have to use Xcode's Add files to project instead of copy pasting it on the folder.

**Comment by ryanwilson** [comment]
@mjmaix thanks for the update, glad you figured it out!

**Comment by xstable** [comment]
I have the same error... means I got no error, but if I remove `[FIRApp configure];` from `AppDelegate.m`, the up starts.
If I add it, the app stop at the Splash-Screen. Here is a short Video which shows it: http://somup.com/cFX1iGn15J
