### ISSUE TITLE
When unlink email account,  Error Domain=FIRAuthErrorDomain Code=17016 "User was not linked to an account with the given provider."

### ISSUE THREAD

**Issue by Hamada-Yuji** [firebase/firebase-ios-sdk#3405]
Environment
  * Xcode version: 10.2.1
  * Firebase SDK version: 6.5.0
  * Firebase Component: Auth
  * Component version: 6.5.0
  *swift 5.0.1

I tried to unlink email account. like below code.
```
Auth.auth().currentUser?.unlink(fromProvider: EmailAuthProviderID) { (user, error) in
    if let error = error {
        print(error)
    }
}
```
but I got an error, 
```
Error Domain=FIRAuthErrorDomain Code=17016 "User was not linked to an account with the given provider." UserInfo={NSLocalizedDescription=User was not linked to an account with the given provider., FIRAuthErrorUserInfoNameKey=ERROR_NO_SUCH_PROVIDER}
```

I also tried
```
let user = Auth.auth().currentUser!
let providerData = user.providerData
for provider in providerData {
    Auth.auth().currentUser?.unlink(fromProvider: provider.providerID) { (user, error) in
        if let error = error {
            print(error)
        }
    }
}
```
And I got the same error.
I tried to unlink after reauthenticate the email, but the same result.

GoogleAuthProviderID and FacebookAuthProviderID worked successfully, but only EmailAuthProviderID not worked. 
How can I unlink EmailAuthProvider?

**Comment by morganchen12** [comment]
Is this the case for every user or just one user in particular?

**Comment by Hamada-Yuji** [comment]
@morganchen12 Yes, I tried multiple accounts, But every user got the same error.

**Comment by Hamada-Yuji** [comment]
I also tried on [`quickstart-ios/authentication/`](https://github.com/firebase/quickstart-ios/tree/master/authentication), and I got the same error.

I changed
* GoogleService-Info.plist
* Bundle Identifier
* Associated Domains
* actionCodeSettings.url

Is my Firebase account broken?

**Comment by morganchen12** [comment]
No, your Firebase account isn't broken; it's most likely a bug in Firebase Auth.

**Comment by renkelvin** [comment]
@Hamada-Yuji I'm not able to reproduce the issue. Could you share the full steps how to reproduce? (including how the user is created and linked)

**Comment by Hamada-Yuji** [comment]
@renkelvin 
In my code

```
// EmailLoginViewController.swift
@IBAction func sendAuth(_ sender: Any) {
  let actionCodeSettings = ActionCodeSettings()
  actionCodeSettings.url = URL(string: "https://www.example.com") // replace my own link
  actionCodeSettings.handleCodeInApp = true
  actionCodeSettings.setIOSBundleID(Bundle.main.bundleIdentifier!)
  Auth.auth().sendSignInLink(toEmail: mailTextField.text!, actionCodeSettings: actionCodeSettings) { error in

      if let error = error {
          print(error)
          return
      }
      UserDefaults.standard.set(self.mailTextField.text, forKey: "email")
  }
}
```

```
// AppDelegate.swift
func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
    guard let url = userActivity.webpageURL else { return true }
    let handled = DynamicLinks.dynamicLinks().handleUniversalLink(url) { [weak self] (link, _) in
        guard let linkURL = link?.url else { return }
        self?.handlePasswordlessSignIn(withURL: linkURL)
    }
    return handled
}

func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
    if DynamicLinks.dynamicLinks().dynamicLink(fromCustomSchemeURL: url) != nil {
        // Handle the deep link. For example, show the deep-linked content or
        // apply a promotional offer to the user's account.
        return true
    }
    return false
}

func handlePasswordlessSignIn(withURL url: URL) {
    let link = url.absoluteString
    if Auth.auth().isSignIn(withEmailLink: link) {
            Auth.auth().signIn(withEmail: UserDefaults.standard.string(forKey: "email")!, link: link) { (result, error) in
                if let error = error {
                    print(error)
                    return
                }
            }
        }
    }
}
```
This is my code.
And I also reproduce this issue on [`quickstart-ios/authentication/`](https://github.com/firebase/quickstart-ios/tree/master/authentication). 
I wrote the steps above comment.

Are there any wrong steps?

**Comment by Hamada-Yuji** [comment]
I debugged the sdk, and I found two problems here.
https://github.com/firebase/firebase-ios-sdk/blob/99ffc721e443ba269290d8b58af6ee679b5a3ab6/Firebase/Auth/Source/User/FIRUser.m#L1255-L1267

* `_hasEmailPasswordCredential` is always false. Maybe when Authenticate with Firebase Using Email Link,  It doesn't have any password?
* `setAccountInfoRequest.deleteAttributes = @[ FIRSetAccountInfoUserAttributePassword ];` is not working. I tried `setAccountInfoRequest.deleteAttributes = @[ FIRSetAccountInfoUserAttributeEmail ];` . It works

I feel it seems to be sdk bugs. Do you have any idea?

**Comment by renkelvin** [comment]
Fixed here: https://github.com/firebase/firebase-ios-sdk/pull/3442

**Comment by Hamada-Yuji** [comment]
Thank you for fixing it, I found no error when I unlink email auth on iOS device.

But after I unlink email with this pull-request, I found the email auth on the firebase console, and I can log in with the email again. It seems to be not unlinked correctly. 

Is it still fixing ( the server-side)?

**Comment by renkelvin** [comment]
Yeah, the fix will be rolled out when Firebase v6.6.0 is released.

**Comment by paulb777** [comment]
@renkelvin 6.6.0 is now published. Please confirm the server side fix has rolled out and close.

**Comment by renkelvin** [comment]
Unfortunately, the backend fix is delayed. I'll update here once it's available.

**Comment by Hamada-Yuji** [comment]
@renkelvin how is backend release going?

**Comment by renkelvin** [comment]
@Hamada-Yuji It should be on prod from yesterday.
