### ISSUE TITLE
Using FirebaseApp.delete() results in unusable Messaging singleton

### ISSUE THREAD

**Issue by cooksimo** [firebase/firebase-ios-sdk#3411]
### Describe your environment

  * Xcode version: 10.2.1
  * Firebase SDK version: 6.5.0
  * Firebase Component: Messaging
  * Component version: 4.1.1

### Describe the problem
We have several projects set up, representing different environments for remote config. We use Messaging to enable real time remote config updates. When a user switches the firebase environment within the app, we delete the default app, and attempt to recreate it.

```
FirebaseApp.delete({ _ in })
FirebaseApp.configure(options: options)
```

Once this has been done any interaction with Messaging will not work. We have encountered this because we were running a very old version of Firebase (4.13.0) & Messaging (2.2.0) and we're trying to update to the latest. This approach worked in those versions.

This problem looks to be in the implementation of `messaging()`, there is a `dispatch_once` block to actually set everything up, this doesn't make sense if the singleton object can actually be deallocated and recreated.

I have attempted to solve this by calling `start` manually, and this seems to fix some things, but the new Messaging instance never gets notified of the `fcmToken` being available so cannot subscribe to anything.

**Comment by morganchen12** [comment]
IIRC this has never been an officially supported use case, though we also don't explicitly label `deleteApp:` as unrecoverable. We can revisit this behavior in API review, but in the meantime, what use case are you trying to accomplish by deleting and reconstructing the Firebase app?

**Comment by cooksimo** [comment]
Our use case is to have production, staging and sandbox environments for Firebase, with an in-app option to toggle between these environments for debug builds.

**Comment by cooksimo** [comment]
I have managed to workaround this and get it working again, but it's very hacky.

When we switch environments we do this:
```
var oldMessaging: Messaging? = nil
if FirebaseApp.app() != nil {
    oldMessaging = Messaging.messaging()
}

...

// If we are switching environments, we need to delete the old FirebaseApp and recreate a new one
if let app = FirebaseApp.app() {
    app.delete({ _  in })

    FirebaseApp.configure(options: options)

    if oldMessaging != nil {
        Messaging.messaging().perform(Selector("start"))
        let notification = Notification(name: Notification.Name(rawValue: "com.firebase.iid.notif.fcm-token"), object: Messaging.messaging().fcmToken, userInfo: nil) // The Messaging instance does know its token, things just didn't get wired back up properly
        NotificationQueue.default.enqueue(notification, postingStyle: .asap)
        Messaging.messaging().delegate = oldMessaging?.delegate
        Messaging.messaging().apnsToken = oldMessaging?.apnsToken
    }
}
else {
    FirebaseApp.configure(options: options)
}
```

**Comment by ryanwilson** [comment]
Thanks @cooksimo for the detailed write-up and investigation into what the cause was!

**Comment by nordfogel** [comment]
Is it intended not taking the delegate into account by recreating the Messaging singleton after a FirebaseApp is deleted and recreated?

`@property(nonatomic, weak, nullable) id<FIRMessagingDelegate> delegate;`
