### ISSUE TITLE
Unable to see debugview logs in Analytics [Firebase console]

### ISSUE THREAD

**Issue by sampathkumar1988** [firebase/firebase-ios-sdk#3413]
* Xcode version: 10.2.1
  * Firebase SDK version: 6.5.0
  * Firebase Component:  Analytics
  * Component version: 6.5.0

Note: This is similar to the issue [https://github.com/firebase/firebase-ios-sdk/issues/143]
Problem: I have added firebase analytics in my project. Added some events. I couldn't see those logs in debug view of the console. But I can see the events in Stream view. I have enabled -FIRDebugEnabled and/or -FIRAnalyticsDebugEnabled. Also made "IS_ANALYTICS_ENABLED" in googleservice plist to YES. 

In the Xcode console, I'm seeing `2019-07-23 13:20:44.571284+1000 SamFirebaseAnalyticsTest[46728:277243] 6.5.0 - [Firebase/Analytics][I-ACS023009] Debug logging enabled
2019-07-23 13:20:44.808171+1000 SamFirebaseAnalyticsTest[46728:277242] 6.5.0 - [Firebase/Analytics][I-ACS023051] Logging event: origin, name, params: auto, session_start (_s), { "[Firebase/Analytics][I-ACS031010] Tracking view controller." 2019-07-23 12:34:58.983482+1000 SamFirebaseAnalyticsTest[44855:245373] 6.5.0 - [Firebase/Analytics][I-ACS024000] Debug mode is on 2019-07-23 12:34:59.974433+1000 SamFirebaseAnalyticsTest[44855:245369] 6.5.0 - [Firebase/Analytics][I-ACS023073] Debug mode is enabled. Marking event as debug and real-time. Event name, parameters: first_open (_f), {`

So this means my setup is fine? Then why I'm not seeing the device in the Firebase console - > analytics -> DebugView "no devices available".

Please help me

**Comment by sampathkumar1988** [comment]
#143

**Comment by morganchen12** [comment]
Assuming you followed everything in [this document](https://support.google.com/firebase/answer/7201382?hl=en), your app should be set up correctly. Can you share a screenshot of your scheme configuration?

**Comment by sampathkumar1988** [comment]
@morganchen12 I can able to see the logs in debug view when I tried to create a new sample app with the same configuration as mentioned above. Working fine now. I can close the issue.

I have one more query. I created some events yesterday and in the stream view, i was seeing all the events logged. But today my console looks like new. no data of yesterday. From the Top date menu, i selected yesterday/ this weeks. Still i couldn't see the logs. Please help where i can find the those  ?

**Comment by morganchen12** [comment]
For your second question, you should file a [support issue](https://firebase.google.com/support). The support team will be able to take a look at your project and tell you why your data is not visible.

**Comment by sampathkumar1988** [comment]
Thanks will reach them.
