### ISSUE TITLE
In App messaging doesn't compile with last Xcode 10.3

### ISSUE THREAD

**Issue by jaumard** [firebase/firebase-ios-sdk#3414]
I just updated to the last Xcode version and get error from in app messaging.

  * Xcode version: 10.3
  * Firebase SDK version: 6.1.0
  * Firebase Component: In App messaging
  * Component version: 0.15.2

#### Steps to reproduce:
Add in app messaging on your app, open Xcode and try to compile it

Interface Builder Storyboard Compiler Error Group on FIRInAppMessageDisplayStoryboard.storyboard

![Capture d’écran 2019-07-23 à 11 05 36](https://user-images.githubusercontent.com/2970449/61698714-d7fe0200-ad39-11e9-8298-f5f91d7376d2.png)

Any workaround would be appreciated as I can't compile anymore :/

**Comment by garyodonoghue** [comment]
Hey @jaumard, funnily enough the old 'turn it off and on again' trick worked for me here, was having the same issue and just restarted my mac, all good now!

**Comment by jaumard** [comment]
Thx for the tips @garyodonoghue ! look like it was that ! Mac OS look more and more like windows lool
