### ISSUE TITLE
Cannot get ID token on getIDTokenForcingRefresh

### ISSUE THREAD

**Issue by skyfoxa** [firebase/firebase-ios-sdk#3417]
### [READ] Step 1: Are you in the right place?

YES

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2.1
  * Firebase SDK version: 6.5.0
  * Firebase Component: Auth, Core, Database, Analytics
  * Component version: 6.2.1, 6.1.0, 6.0.0, 6.0.4

#### Steps to reproduce:

I cannot refresh ID token for signed in user when app's lunching. I've found some closed issues https://github.com/firebase/firebase-ios-sdk/issues/3111 and https://github.com/firebase/FirebaseUI-iOS/issues/729 but they look closed and solved for Firebase SDK version 6.4.0. I updated all components and the Firebase SDK is 6.5.0 now, but I'm still receiving this error.

#### Relevant Code:

My code:
```
func getToken(force: Bool) -> Promise<String>
    {
        return Promise { resolve, reject in

            self.getIDTokenForcingRefresh(force, completion: { token, error in
                
                if let error = error {
                    reject(error)
                    return
                }
                
                guard let token = token else {
                    reject(ErrorManager.build("Unable to authenticate, Firebase error"))
                    return
                }
                
                resolve(token)
            })
        }
    }
```

Response:
```
Error Domain=FIRAuthErrorDomain Code=17999 "An internal error has occurred, print and inspect the error details for more information." UserInfo={FIRAuthErrorUserInfoNameKey=ERROR_INTERNAL_ERROR, NSLocalizedDescription=An internal error has occurred, print and inspect the error details for more information., NSUnderlyingError=0x283f78300 {Error Domain=FIRAuthInternalErrorDomain Code=3 "(null)" UserInfo={FIRAuthErrorUserInfoDeserializedResponseKey={
    code = 400;
    details =     (
                {
            "@type" = "type.googleapis.com/google.rpc.Help";
            links =             (
                                {
                    description = "Google developers console";
                    url = "https://console.developers.google.com";
                }
            );
        }
    );
    message = "API key not valid. Please pass a valid API key.";
    status = "INVALID_ARGUMENT";
}}}}
```

**Comment by morganchen12** [comment]
Are you getting 400 errors on any other Firebase SDK requests?

**Comment by skyfoxa** [comment]
@morganchen12 no, I don't receive any other 400 errors, I use some firebase observers and they are working fine, but I can't fetch new ID token.

I've also tried re-downloading the **GoogleService-Info.plist** file, the API_KEY is/was there, but it didn't help.

**Comment by morganchen12** [comment]
Does swapping the GoogleService-Info.plist for one from a different Firebase project repro the issue? If not, it may be an issue with your Firebase project.

**Comment by skyfoxa** [comment]
@morganchen12 it looks like it fires only on early app lunching, like if it's called in **applicationDidBecomeActive** when app is lunching. When I trigger the call later it looks it's working. Can it happens because Firebase needs some time to configure first? But I think **applicationDidBecomeActive** happens after **didFinishLaunchingWithOptions**

Not sure if it may be helpful but here is our flow:

On the backend side we are using https://firebase.google.com/docs/auth/web/password-auth#sign_in_a_user_with_an_email_address_and_password and https://firebase.google.com/docs/reference/admin/node/admin.auth.Auth.html#createcustomtoken methods to login the user. 

On sign in the backend is using **signInWithEmailAndPassword(email, password)** method to get the user, then it uses **.auth().createCustomToken(uid)** and sends back **custom_token** to the iOS app when the user is successfully signed in. Then the custom token is used to sign in to Firebase on app side. 

Later when the session token expires or on lunch the app checks if the it is still valid and if not it calls **getIDTokenForcingRefresh**

**Comment by morganchen12** [comment]
Can you share your AppDelegate file?

**Comment by skyfoxa** [comment]
@morganchen12 I saw **6.5.0 - [Firebase/Auth][I-AUT000004] Token auto-refresh scheduled in 55:00 for the new token.** in my logs too, but I can't see any documentation for it. Is there now any process that will auto-refresh the token?

**Comment by morganchen12** [comment]
Chuan, can you answer the last question about token refresh?

**Comment by skyfoxa** [comment]
@morganchen12 I discovered that this error happened when I was storing the **User** reference to keychain and then I used it during relaunching to get new Token ID if it was invalid. Do you know why this happen?

**Comment by renkelvin** [comment]
@skyfoxa Are you storing the User yourself? Could you please describe the full steps to reproduce.

**Comment by skyfoxa** [comment]
@renkelvin Yes, I was storing it myself. I had a custom object, **LocalUser**  with some properties needed in our app and with  property `var actualFirebaseUserRef: User?`. Once the app received the **User** object in `Auth.auth().addStateDidChangeListener` it would assign this object to **LocalUser** property. Then the **LocalUser** was encoded via `NSKeyedUnarchiver.archiveObject` and stored to the keychain using KeychainAccess pod. This **LocalUser** is like singleton and whenever it is accessed in the app it is loaded from Keychain. 

```
static var main: LocalUser? {
        guard let encoded = Keychain()[data: LocalUser._userKeychainKey] else { return nil }
        let user = LocalUser(encoded: encoded)        
        return user
}
```

I was playing with it for a while, I removed the logic responsible for storing the **User** object to the keychain, then I switched between several git branches several times and today I tried to revert to the commit with the logic responsible for storing the **User** to the keychain and I didn't see the error in the console anymore. Not sure why the error is gone, probably the pods didn't update properly last time or the pods were cached. 




> I saw **6.5.0 - [Firebase/Auth][I-AUT000004] Token auto-refresh scheduled in 55:00 for the new token.** in my logs too, but I can't see any documentation for it. Is there now any process that will auto-refresh the token?
@renkelvin  is there any documentation for this feature?

**Comment by renkelvin** [comment]
OK, thanks for providing the details. There is additional internal mechanism to handle the API key and tokens. This should explain the API key error you received. My recommendation is to always keep `LocalUser` updated with `FIRAuth.auth.currentUser` to avoid such errors.
