### ISSUE TITLE
[RCNConfigContent copyFromDictionary:toSource:forNamespace:] crash

### ISSUE THREAD

**Issue by daidongon** [firebase/firebase-ios-sdk#3447]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version:  10.2.1
  * Firebase SDK version:  6.4.0 ~ 6.5.0
  * Firebase Component: RemoteConfig
  * Component version: 4.2.1

### [REQUIRED] Step 3: Describe the problem

We're seeing some crashes in the wild, with stack trace:

```
Crashed: com.google.GoogleConfigService.FIRRemoteConfig
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000010

0  CoreFoundation                 0x1f11cb2b0 -[__NSDictionaryM setObject:forKeyedSubscript:] + 500
1  our app                       0x102a35518 -[RCNConfigContent copyFromDictionary:toSource:forNamespace:] + 4375057688
2  our app                       0x102a31b00 __49-[FIRRemoteConfig activateWithCompletionHandler:]_block_invoke + 4375042816
3  libdispatch.dylib              0x1f0d14a38 _dispatch_call_block_and_release + 24
4  libdispatch.dylib              0x1f0d157d4 _dispatch_client_callout + 16
5  libdispatch.dylib              0x1f0cf0dec _dispatch_lane_serial_drain$VARIANT$armv81 + 548
6  libdispatch.dylib              0x1f0cf192c _dispatch_lane_invoke$VARIANT$armv81 + 408
7  libdispatch.dylib              0x1f0cf9e08 _dispatch_workloop_worker_thread + 584
8  libsystem_pthread.dylib        0x1f0ef6114 _pthread_wqthread + 304
9  libsystem_pthread.dylib        0x1f0ef8cd4 start_wqthread + 4
```

crash happen at:

```
-[RCNConfigContent copyFromDictionary:toSource:forNamespace:] + 4375057688
```

**Comment by dmandar** [comment]
Hi..we are trying to repro this. In the meantime, would be useful to know if any others are seeing this.
Few questions:
a. Are you integrating with the FirePerf SDK?
b. Can you share the code snippet of how/where you integrate with RC?
c. Are you able to repro this by yourself? If so, repro steps would be useful.
d. Is it possible to know how frequent and the devices on which this is failing?

**Comment by bajtyngier** [comment]
Seeing this crash as well.
a. Yes
b. Below
c. No luck so far
d. So far we have seen crashes on iOS 12.3.1 and 12.4 on various devices iPhone7+

```
RemoteConfig.remoteConfig().activate { _ in
    RemoteConfig.remoteConfig().setDefaults(<dictionary here>)
    RemoteConfig.remoteConfig().fetch(withExpirationDuration: 60) { status, _ in
        guard status == .success else { return }
        RemoteConfig.remoteConfig().activate(completionHandler: { _ in
            <our logic here>
        })
    }
}
```

**Comment by dmandar** [comment]
We do not have a repro yet, but have some overall stability improvements which should hopefully fix this issue. Please retry with the upcoming Firebase release (next week) and reopen if still an issue.
