### ISSUE TITLE
BUG - Auth and Captcha

### ISSUE THREAD

**Issue by sharpwitz** [firebase/firebase-ios-sdk#3451]
* Xcode version: __10.3___
  * Firebase SDK version: __6.5.0___
  * Firebase Component: _Auth____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: _____

### [REQUIRED] Step 3: Describe the problem
Captcha verify image screen has an user interface error

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

When users going through the SMS Auth activation process, they have to do a captcha challenge.  

However, the Firebase captcha challenge is a bit messed up.  It gives the user several images and a Verify button.  The problem with the current set up is that if the user taps on the correct answers and press Verify, captcha tells them they are wrong.  The reason for this is because captcha actually has 2 more screens of image verification for the user to answer before they are suppose to press the Verify button.

After getting the incorrect answer alert, the user answers a second set of correct captcha images and press Verify, and they get another wrong answer alert.  The user does not realize there are a total of 3 screens of image selection before they should press verify.

At this point, the user uninstalls the App out of absolute frustration thinking the App is broken, when in fact it is Captcha that is broken.

This is a serious problem.  User App acquisition is difficult and in this moment, captcha is losing the customer.

maybe you should hide the verify button and also let user know they have to select more images when new images re-appear for them to select on screen 2 and screen 3, and then give them the verify button on the 3rd screen.  however, this could be tricky because some people may not notice the verify button re-appearing on screen 3 since users tend not to be observant.  Maybe a red Verify button?

![13934](https://user-images.githubusercontent.com/538437/62011837-ea1ddd00-b14b-11e9-94d6-ab9e5dbb8f2b.jpg)

**Comment by renkelvin** [comment]
reCaptcha flow is rarely triggered on physical devices. See https://firebase.google.com/docs/auth/ios/phone-auth#enable-app-verification

For improvement suggestions on reCaptcha, please reach out to https://developers.google.com/recaptcha/
