### ISSUE TITLE
Dynamic link is received every first launch after reinstalling the App

### ISSUE THREAD

**Issue by taylorwrynn** [firebase/firebase-ios-sdk#3455]
* Xcode version: 10.2
  * Firebase SDK version: 6.1.0
  * Firebase Component: DynamicLinks
  * Component version: 6.1.0

Once I open the dynamic link to install the app from App Store, the deep-link will be receive and show my onboarding view. 
Then, I reinstall the app, without open dynamic link, the deep-link is received again.

#### Steps to reproduce:
1. Make sure the app have not installed.
2. Open dynamic link (I was click it in Notes.)
3. Following the guide to install the app from App Store
4. Launch the app, received the deep-link and show the onboarding view.
5. Uninstall the app, and reinstall it from App Store directly, without open dynamic link.
6. Launch the app, received the deep-link again.
7. Repeat steps 5, 6.  it would happen again.

#### Relevant Code:

```
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> *)options
    var onboardingUrl = url;
    let firebaseDynamicLink = [[FIRDynamicLinks dynamicLinks] dynamicLinkFromCustomSchemeURL:url];
    if (firebaseDynamicLink) {
        if (firebaseDynamicLink.url) {
            onboardingUrl = firebaseDynamicLink.url;
        } else {
            return NO;
        }
    }
    // show the onboarding view
    return YES;
}
```

**Comment by morganchen12** [comment]
I suspect this is an artifact of how we're doing link matching. The match quality is most likely weaker for the subsequent installs.

Basically, if the user taps on the dynamic link and goes to the App Store, but then cancels their download and opens the App Store on their own to install the app, Dynamic Links can't distinguish that the user broke the dynamic link flow and went back to the App Store on their own. This is kind of a contrived example, but you can try to check for this on the client and ignore it if it's a weak match.
