### ISSUE TITLE
Firebase storage "unexpected response data" when `put` called while device is offline

### ISSUE THREAD

**Issue by gbhall** [firebase/firebase-ios-sdk#35]
* Xcode version: 8.3.2
  * Firebase Product: storage

**To reproduce:**
Initiate `.put` when device has no connectivity, then reenable device connectivity.
E.g. `let uploadTask = photoRef.put(compressedData, metadata: metadata) { (metadata, error) in`

**Issue:**
`.put` closure is not executed. 

**Output example:**
```
2017-05-26 23:17:56.047225+0800 Xxx[2078:602872] unexpected response data (uploading to the wrong URL?)
{
  "name": "xxx",
  "bucket": "xxx.appspot.com",
  "generation": "1495811875731000",
  "metageneration": "1",
  "contentType": "image/jpeg",
  "timeCreated": "2017-05-26T15:17:55.540Z",
  "updated": "2017-05-26T15:17:55.540Z",
  "storageClass": "STANDARD",
  "size": "358088",
  "md5Hash": "LmNPvUNrVuJoCcJUkr8BiQ==",
  "contentEncoding": "identity",
  "contentDisposition": "inline; filename*=utf-8''xxx",
  "crc32c": "r4VjGA==",
  "etag": "CLjsg7ztjdQCEAE=",
  "downloadTokens": "87fc826a-5b44-4a17-ad06-128a2eb06fa5"
}
2017-05-26 23:17:56.047700+0800 Xxx[2078:602872] Premature failure: upload-status:"final"  location:(null)
```
**Expected result:**
`.put` closure to execute, and no error message in logs. 

Note:
Despite the error, the content is still being uploaded after the device resumes connectivity and `uploadTask.observe(.progress) { snapshot in` continues to fire away. Also `uploadTask.observe(.failure) { snapshot in` is never executed.

**Comment by gbhall** [comment]
Just saw that this may be the wrong place to submit bugs for the Firebase release pods, and https://firebase.google.com/support/contact/bugs-features/ exists. Please let me know if this is the wrong area.

**Comment by mcdonamp** [comment]
Here is probably fine, though we're probably working that process out.

The closure version simply wraps `.success` and `.failure` (https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/Storage/FIRStorageReference.m#L178-L189), so I assume one of them is going to fire... 

In general, I think we do have a little work to do to persist the upload URI and do background uploads/downloads. I believe we can get this out of the box with GTMSessionFetcher (https://github.com/google/gtm-session-fetcher/blob/master/Source/GTMSessionFetcher.h#L79-L115), but it'll require some hooks into the App Delegate. If you're interested in poking around, I'm happy to provide guidance :)

**Comment by gbhall** [comment]
Adding:
```
            uploadTask.observe(.failure) { snapshot in
                print("Failure")
            }
            
            uploadTask.observe(.success) { snapshot in
                print("Success")
            }
```

neither closure is called. That's what I thought too, surely the closure in `.put` would be called. Essentially there is no way with this error to determine that something went wrong, hence why I am sure this is a bug and reported it. 

Though `.progress` is called, and the image is still uploaded. 

I am actually in the process right now of switching to uploading manually to Google Cloud Storage using `URLSession`. I already upload to GCS using a signed URL in an Android app. So unfortunately, even though using Firebase Storage on iOS was super easy to use, it would be awesome if it supported offline and background uploads.

**Comment by schmidt-sebastian** [comment]
First off, sorry for the long response time. As Mike already pointed out, reporting issues here is fine.

Can you let us know how you are initializing your upload? I have tried to recreate the issue you described, but am unable to do so:

```
storage.maxUploadRetryTime = 10.0;
FIRStorageReference *ref = [storage referenceWithPath:@"path"];

NSData *data = [@"data" dataUsingEncoding:NSUTF8StringEncoding];
  
FIRStorageUploadTask* uploadTask = [ref putData:data metadata:nil];
[uploadTask observeStatus:FIRStorageTaskStatusFailure handler:^(FIRStorageTaskSnapshot *snapshot) {
    NSLog(@"fail");
}];

[uploadTask observeStatus:FIRStorageTaskStatusSuccess handler:^(FIRStorageTaskSnapshot *snapshot) {
   NSLog(@"success");
}];
```

Depending on how long the device is offline for, one of these callbacks gets executed. Please note that you can adjust the timeouts using maxUploadRetryTime.

**Comment by schmidt-sebastian** [comment]
Closing this as not reproducible. Please let us know should you want us to continue to investigate.
