### ISSUE TITLE
Dynamic links not working on first launch

### ISSUE THREAD

**Issue by thiagomacauba88** [firebase/firebase-ios-sdk#3501]
Xcode version: 10.2
Firebase (6.2.0)
FirebaseAnalytics (6.0.1)
FirebaseAnalyticsInterop (1.2.0)
FirebaseCore (6.0.2)
FirebaseDynamicLinks (4.0.0)
FirebaseInstanceID (4.1.1)
FirebaseMessaging (4.0.2)
GoogleAppMeasurement (6.0.1)
GoogleUtilities (6.2.0)
Domain: applinks:vistaclient.page.link

tap on dynamic link
app store opens
install app through Store.

I already tried with a short link: https://vistaclient.page.link/thiago
and long link: https://vistaclient.page.link/?link=http://vista.com/dynamicLink&isi=1455754841&ibi=br.com.VistaClient

but always the same problem.

When I try to debug returns the warnings:

The dynamic link has 7 warning(s)
There is no log option set for custom domain. Learn more.
The custom parameter (link) is a reserved parameter. Learn more.
The custom parameter (ibi) is a reserved parameter. Learn more.
The custom parameter (isi) is a reserved parameter. Learn more.
iOS app 'br.com.Vista-Client' lacks App ID Prefix. UniversalLinks is not enabled for the app. Learn more.
There is no configuration to prevent phishing on this domain https://vistaclient.page.link. Setup URL patterns to whitelist in the Firebase Dynamic Links console. Learn more.

The problem only happens when is a fresh install, I don't know what is wrong, any help?

**Comment by morganchen12** [comment]
Have you tried fixing the seven warnings returned from the debug link?

**Comment by thiagomacauba88** [comment]
> Have you tried fixing the seven warnings returned from the debug link?

About the warnings:

There is no log option set for custom domain. Learn more.
R: I don't know what is that log.

The custom parameter (link) is a reserved parameter. Learn more.
R: The link was generated by firebase.

The custom parameter (ibi) is a reserved parameter. Learn more.
R: The link was generated by firebase, and just appear in long link.

The custom parameter (isi) is a reserved parameter. Learn more.
iOS app 'br.com.Vista-Client' lacks App ID Prefix. UniversalLinks is not enabled for the app. Learn more.
R: Maybe here is the problem, but where I can enable that?

There is no configuration to prevent phishing on this domain https://vistaclient.page.link. Setup URL patterns to whitelist in the Firebase Dynamic Links console. Learn more.
R: I don't know what is that.


I need fix this soon as possible, thanks for reply.

**Comment by morganchen12** [comment]
Set the app ID prefix (Team ID) in Firebase console. See [this doc](https://firebase.google.com/docs/dynamic-links/ios/create) for the other parameters.

**Comment by thiagomacauba88** [comment]
Hi Morgan!

I create other link: https://vistaclient.page.link/novoteste5

The url: https://vistaclient.page.link/?ibi=br.com.VistaClient&isi=1455754841

and now I have 3 warnings:

Param 'link' should not be on FDL domain. Learn more.
iOS app 'br.com.Vista-Client' lacks App ID Prefix. UniversalLinks is not enabled for the app. Learn more.
There is no configuration to prevent phishing on this domain https://vistaclient.page.link. Setup URL patterns to whitelist in the Firebase Dynamic Links console. Learn more.

I already set the app ID prefix (Team ID) in Firebase console.

What can I do now?

**Comment by morganchen12** [comment]
Each of the `Learn more` links should open a document that explains the warnings and how to resolve them.

**Comment by thiagomacauba88** [comment]
I have tried so many times to solve based on this learn more, but nothing yet.
Do you have an example of url that works?  I already tried the firebase example too.

**Comment by morganchen12** [comment]
Can you share your project?

**Comment by thiagomacauba88** [comment]
sure! What email?

**Comment by morganchen12** [comment]
You can send it to me at morganchen at google.

**Comment by thiagomacauba88** [comment]
I just sent, can you check please?
tks

**Comment by morganchen12** [comment]
I haven't received it yet; did you send it to `morganchen [at] google.com`?

**Comment by thiagomacauba88** [comment]
I just sent again, and now?

**Comment by morganchen12** [comment]
Can you share your codebase (not your Firebase project)?

**Comment by thiagomacauba88** [comment]
yes, I just sent.

**Comment by morganchen12** [comment]
Hey @thiagomacauba88, sorry for the slow response--looking through your codebase, there doesn't seem to be any issues with your implementation. We've made some improvements recently to the dynamic link debug view, so please try appending `?d=1` to the end of your links and seeing if there's anything wrong.
