### ISSUE TITLE
Refresh token when signing into Microsoft account?

### ISSUE THREAD

**Issue by crspybits** [firebase/firebase-ios-sdk#3505]
Like the access token (https://github.com/firebase/firebase-ios-sdk/issues/3076), is it possible to get the OAuth refresh token when signing into a Microsoft account using Firebase Auth? Thanks,
Chris.

**Comment by crspybits** [comment]
Ok, forget it! :). Digging around I see that property on `FIRUser`.

**Comment by RJPDeanlo** [comment]
I just did an update to all my FB pods.
Is this accessToken not in the authResult anymore?
I can's seem to find the newly exposed token in the authResult or user (Auth.auth().currentUser)
