### ISSUE TITLE
Crashlytics in tvOS for Apps without Fabric App

### ISSUE THREAD

**Issue by bjimenezned** [firebase/firebase-ios-sdk#3511]
Is there a way to use Crashlytics in a new tvOS app.  Since now you can't create a new Fabric app, #2009 solution is not possible anymore.

I tried integrating it as a new iOS App but test crashes are not showing up in the console (yes, I did read/follow the Firebase Crashlytic integration instructions for new apps step by step, and the firebase integration is working since I can use FirebaseDatabase without issues)

Most issues in here seems to apply to older apps with a Fabric app already created, but how does it work for a new Firebase tvOS App?

**Comment by paulb777** [comment]
Tracked internally at b/139003562

**Comment by TKBurner** [comment]
At this time you can still create new apps in the Fabric console. This is the recommended path. I have let the team know . :)

**Comment by bjimenezned** [comment]
> At this time you can still create new apps in the Fabric console. This is the recommended path. I have let the team know . :)
Do you mean the dashboard in https://fabric.io/settings/apps ? beacause if I click the add button it redirects me to the home page https://fabric.io/kits

![dashboard](https://user-images.githubusercontent.com/32678245/62637254-17674980-b909-11e9-8a2d-b263b0cc4e2a.png)

**Comment by samedson** [comment]
Hey @bjimenezned, it sounds like you got the setup right. I took a look at this and think there is an issue in the backend. I'm gonna work on getting this fixed and then update this bug.

**Comment by samedson** [comment]
Hey @bjimenezned, can you try onboarding your app in Firebase again? The issue should be resolved now.

For future tv and macOS onboarders, my recommendation is to follow the onboarding steps for an iOS app, and include the following in your Podfile if you want Crashlytics:

```
  pod 'FirebaseCore'
  pod 'Crashlytics'
```

**Comment by bjimenezned** [comment]
Seems to be working now, I managed to link and receive crash reports in firebase console. 

Thanks!
