### ISSUE TITLE
FIRConfiguration setLoggerLevel() has no impact on console logging

### ISSUE THREAD

**Issue by dtrenz** [firebase/firebase-ios-sdk#3516]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.3
  * Firebase SDK version: 6.5.0
  * Firebase Component: Core
  * Component version: 6.5.0

### [REQUIRED] Step 3: Describe the problem

iOS SDK: FirebaseConfiguration.shared.setLoggerLevel() has no impact when using FirebaseApp.configure(options:). .min and .max result in the exact same amount of logging in the console.

#### Steps to reproduce:

1. In AppDelegate `didFinishLaunchingWithOptions`, set the logger level to `.min` then configure `FirebaseApp` via `configure(options:)`.
2. Run the app attached to the debugger.

##### Expected
Console logging from the Firebase SDK should be at minimum level.

##### Actual
Console logging is unaffected. Logging looks identical to `.max`.

#### Relevant Code:
```swift
FirebaseConfiguration.shared.setLoggerLevel(.min)
FirebaseApp.configure(options: fileOptions)
```

**Comment by ryanwilson** [comment]
Thanks for the report, we'll look into this shortly.

**Comment by paulb777** [comment]
Related is https://stackoverflow.com/a/44438819/556617

**Comment by ryanwilson** [comment]
Tried to reproduce this with Xcode 11.2.1 running iOS 13, latest version of FirebaseCore (at master) and was not able to reproduce - `.min` and `.max` have vastly different logging counts with `.min` working as expected.

If this is still an issue you see, please let us know how to reproduce it and I'll re-investigate!

**Comment by paulb777** [comment]
See #5124
