### ISSUE TITLE
Add support for GoogleSignIn 5

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#3609]
GoogleSignIn released a major update today and it causes build failures like 

❌  /Users/travis/build/firebase/firebase-ios-sdk/Example/Auth/Sample/GoogleAuthProvider.m:38:62: cannot find protocol declaration for 'GIDSignInUIDelegate'; did you mean 'GIDSignInDelegate'?
@interface GoogleAuthDelegate : NSObject <GIDSignInDelegate, GIDSignInUIDelegate, OpenURLDelegate>
                                                               ^
❌  /Users/travis/build/firebase/firebase-ios-sdk/Example/Auth/Sample/GoogleAuthProvider.m:85:38: no visible @interface for 'GIDSignIn' declares the selector 'handleURL:sourceApplication:annotation:'
  return [[GIDSignIn sharedInstance] handleURL:url
          ^
❌  /Users/travis/build/firebase/firebase-ios-sdk/Example/Auth/Sample/GoogleAuthProvider.m:117:10: property 'uiDelegate' not found on object of type 'GIDSignIn *'; did you mean 'delegate'?
  signIn.uiDelegate = delegate;
          ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~

See full log at https://travis-ci.org/firebase/firebase-ios-sdk/jobs/572459687

**Comment by renkelvin** [comment]
Fixed in https://github.com/firebase/firebase-ios-sdk/pull/3611
