### ISSUE TITLE
Unable to authenticate with UK phone number

### ISSUE THREAD

**Issue by junhohong** [firebase/firebase-ios-sdk#3617]
### Environment

  * Xcode version: 10.2.1
  * Firebase SDK version: 6.6.0
  * Firebase Component: Auth 
  * Component version: 6.2.2

### Problem

When attempting to authenticate via a UK phone number using `verifyPhoneNumber` method in `PhoneAuthProvider.provider()`, the method throws the following error:

>The format of the phone number provided is incorrect. Please enter the phone number in a format that can be parsed into E.164 format. E.164 phone numbers are written in the format [+][country code][subscriber number including area code].

When investigating the network requests, I found that the SDK calls to `http://www.googleapis.com/identitytoolkit/v3/relyingparty/sendVerificationCode`, with `recaptchaToken` and `phoneNumber`. I've double-confirmed here that the `phoneNumber` passed into this request, is indeed, in E.164 format. The request throws the following error: 

```
{
    "error": {
        "code": 400,
        "message": "INVALID_PHONE_NUMBER",
        "errors": {
            "message": "INVALID_PHONE_NUMBER",
            "domain": "global",
            "reason": "invalid"
        }
    }
}
```

If you pass in `+441234512345` as `phoneNumber`, the SDK will still throw the same E.164 formatting error message, even though it is correctly formatted. 

Adding `+441234512345` as one of the "Phone numbers for testing" on Firebase console resolves this issue for that particular number. 

There are two things I'm thinking about: 
1. The SDK is displaying an incorrect error message. It may somehow be an invalid phone number, but it is not incorrectly formatted. 
2. We have no indicator of why the phone number might be invalid. We are testing with real UK phone numbers (+441234512345 is a dummy example).

To be clear, it is not affecting our USA phone number authentications, just UK. 

Any help/thoughts would be appreciated.

**Comment by renkelvin** [comment]
@junhohong It seems a project-specific issue. Please submit a ticket on https://firebase.google.com/support so we can more details of your project.
