### ISSUE TITLE
Issues embedding Firebase inside other framework

### ISSUE THREAD

**Issue by hixfield** [firebase/firebase-ios-sdk#3626]
* Xcode version: 10.3
  * Firebase SDK version: 6.6.0
  * Firebase Component: analytics, firestore
  * Component version: 6.6.0

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/9302613/63257516-3b684a80-c27a-11e9-9777-a5f585fe6bf0.png">

We have our own swift framework `REFFramework` that is using carthage to import Firebase (analytics and firestore). This is the cartfile in `REFFramework`:

```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseFirestoreBinary.json"
```

The `REFFramework` is used in the `app` also using carthage to import it.
In addition the `app` itself also imports other modules from firebase (remote config).
This is the cartfile of the app:

```
git ".../REFFramework"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseFirestoreBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseRemoteConfigBinary.json"
```

As far as I know carthage is designed to fully support this kind of structure. We use other frameworks also embedded in `REFFramework` like this such as `Alamofire`.
However we notice a crash in the app that does not happen when we remove the Firebase out of the `REFFramework`.
So it's clearly todo with the embedding of Firebase in an intermediate Framework.
The crash is happening in "`0 __pthread_kill`", here is a screenshot of the debugger in xCode 10.3:

![image](https://user-images.githubusercontent.com/9302613/63262611-b59ecc00-c286-11e9-865e-43e4375ecfbb.png)

I see a remark in the documentation: 

> Note that the Firebase frameworks in the distribution include static libraries. While it is fine to link these into apps, it will generally not work to depend on them from wrapper dynamic frameworks.

Not sure if this is releated to this issue?

**Comment by paulb777** [comment]
Yep, the documentation you found is relevant.

The Firebase frameworks are static. They can only be dependencies of other static frameworks and the last I checked, Carthage only supports static frameworks as binaries.

The actual backtrace that you're showing looks related to finding the resource bundle necessary for Firestore.

**Comment by paulb777** [comment]
Going to close since there's nothing actionable. We can continue the conversation if there's more questions.

**Comment by hixfield** [comment]
@paulb777 what is the proposed solution in this scenario (cfr drawing)?

**Comment by paulb777** [comment]
@hixfield Nothing too easy. Here are a few paths:
- Convert your framework to binary static framework Carthage component
- Contribute source static framework support to Carthage
- If you don't need Analytics, and only open source Firebase components, set up Carthage for the Firebase sources.
- Switch to CocoaPods (and you'd still need to link your framework statically)

**Comment by hixfield** [comment]
@paulb777 thanks for the ideas. Unfortunately these do not match our timeframe so we have decided to take all Firebase related code out of our own REFFramework building (step), but leaving it in the git repo. The app using the REFFramework will have to import the actual source code files from the Carthage/checkout folder in xCode. Not an ideal solution but it will allow us the share the code between different apps and keep it in sync (using the existing Carthage tool).
