### ISSUE TITLE
SDWebImage not loading image only for first app launch

### ISSUE THREAD

**Issue by gmineebates** [firebase/firebase-ios-sdk#3629]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2.1
  * Firebase SDK version: 6.0.0
  * Firebase Component: Performance
  * Component version: 3.0.0
  * SDWebImage version: 4.4.2

### [REQUIRED] Step 3: Describe the problem

When our app launches on a fresh install, the images that are loaded using SDWebImage fails to load. The NSURLSession delegate is never called and it is being swizzled to class with prefix of `FIR`. However, this only happens once on first app launch.

#### Steps to reproduce:

- Install SDWebImage version 4.4.2. Install Firebase SDK 6.0.0 and Performance version 3.0.0.
- Freshly install an app and load an image from a web URL
- The image does not load

**Comment by maksymmalyhin** [comment]
@gmineebates Most likely the root cause of the issue is the same as for #2201 which was fixed in 6.6.0. Will you have a chance to update Firebase and check if the issue has been solved?

**Comment by gmineebates** [comment]
@maksymmalyhin Thanks for the quick response, I'm glad it was fixed. We had to disable Firebase and won't have chance to bring it back for a while.
