### ISSUE TITLE
FIRStorageDownloadTask crash when first launch after delete app

### ISSUE THREAD

**Issue by ErmaCKoK** [firebase/firebase-ios-sdk#365]
Hi,
I have crash, but can't find out how I can fixed it.

  * Xcode version: 9
  * Firebase SDK version: 4.3.0
  * Firebase Component:
```
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'Firebase/Auth'
    pod 'Firebase/Messaging'
    pod 'Firebase/Crash'
    pod 'Firebase/RemoteConfig'
```

```
  - FirebaseAnalytics (4.0.4):
  - FirebaseAuth (4.2.1):
  - FirebaseCore (4.0.8):
  - FirebaseCrash (2.0.2):
  - FirebaseDatabase (4.1.0):
  - FirebaseInstanceID (2.0.4)
  - FirebaseMessaging (2.0.4):
  - FirebaseRemoteConfig (2.0.3):
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseStorage (2.0.2):
    - GTMSessionFetcher/Core (~> 1.1)
```

### Step
1. install and log in
2. delete app
3. install again and launch 
4. Crash see screenshot

This happen only one time after delete app and first launch

<img width="1390" alt="2017-10-11 0 27 59" src="https://user-images.githubusercontent.com/4175273/31427380-e41cf9ac-ae1b-11e7-97a3-91b99942da3b.png">

**Comment by mcdonamp** [comment]
Looks like an issue with GTMSessionFetcher. I'm curious what percentage of end users experience this issue (how many are deleting and re-installing the app). If it's low (like I suspect it is), this will likely be low priority for us to identity/fix.

**Comment by akshetpandey** [comment]
This is an important crash because a common support solution for users experiencing app issues is to tell them to uninstall and reinstall the app.

**Comment by mcdonamp** [comment]
@ErmaCKoK can you provide a sample app exhibiting this behavior so we can test it out?

**Comment by ErmaCKoK** [comment]
@mcdonamp Sorry, but I can't provide a sample app for this crash

**Comment by schmidt-sebastian** [comment]
We have not seen any recent reports of this crash. Please re-open if appropriate.
