### ISSUE TITLE
BuildFrameworks Fails

### ISSUE THREAD

**Issue by movilidadSoporte** [firebase/firebase-ios-sdk#366]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.0
  * Firebase SDK version: 0.1.3
  * Firebase Component: All (Auth, Core, Database, Firestore, Messaging, Storage, etc)

#### Steps to reproduce:

1. Run 'pod install' at BuildFrameworks directory (OK)
2. Run './build.swift -f FirebaseCore' at BuildFrameworks directory (FAILS):

```
./build.swift:143:10: error: expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions
  return [buildDir + "/Release" + (multisdk ? "-\(sdk)" : "") + "/" + framework + schemeSuffix + "/lib" + framework + schemeSuffix + ".a"]
```

**Comment by paulb777** [comment]
@movilidadSoporte Thanks for the report! We hadn't yet tested build.swift with Xcode 9. Fixed in #369.
