### ISSUE TITLE
FirebaseRemoteConfig RemoteConfigSettings fetchTimeout not working as intended

### ISSUE THREAD

**Issue by domagojb** [firebase/firebase-ios-sdk#3662]
* Xcode version: 10.3
  * Firebase SDK version: 6.5.0
  * Firebase Component: Remote Config

### Description

Setting fetchTimeout on RemoteConfigSettings has no effect. 

#### Steps to reproduce:

I'm setting the new fetch timeout on the firebase remote config settings as follows:

FIRRemoteConfigSettings *settings = [[FIRRemoteConfigSettings alloc] init];
settings.fetchTimeout = 3.0;
[FIRRemoteConfig remoteConfig].configSettings = settings;

After that, I'm calling fetchAndActivateWithCompletionHandler: which still succeeds even if the request takes longer than 3 seconds. I've been testing this with the network link conditioner on iOS to mimic bad requests (for instance setting a big DNS delay, or in/out request delays) and even requests that take up to 20 seconds still succeed in the end.

Looking at the code that has been opensourced a day ago it's visible that the settings when updated on FIRRemoteConfig, are never updated on the RCNConfigFetch object which uses the timeout and sets it on the NSURLSession.

**Comment by dmandar** [comment]
Thanks for reporting. This is fixed and should be available in the upcoming release.
