### ISSUE TITLE
Clarify differences/recommendations between this and the "official" SDK

### ISSUE THREAD

**Issue by js** [firebase/firebase-ios-sdk#367]
It's not particular clear what Firebase/Googles intentions are with this particular SDK ("FirebaseCommunity") when reading the README. 

- is this intended to replace the "official" SDK?
- Which SDKs gets bug fixes/security updates first?
- Which should we use? When should we use one over the other?

Since this isn't published in the main cocoapods repo, I'm guessing it's not yet officially supported (?), but would be nice with some clarifications on the above questions, which I'm sure a lot of casual observers who comes across this repo considers

**Comment by paulb777** [comment]
@js Thanks for the question. We attempted to provide context and answer those questions with the contents in the [README](https://github.com/firebase/firebase-ios-sdk/blob/master/README.md) and [ROADMAP](https://github.com/firebase/firebase-ios-sdk/blob/master/ROADMAP.md).

Here are answers to your specific questions:

_Is this intended to replace the "official" SDK?_

FirebaseCommunity is not intended to replace the official Firebase SDK. It is expected that they will converge.  We plan for FirebaseCommunity to become a proper subset of Firebase. In addition to providing some of the source in this repository, we eventually plan to provide the product build here as well.

_Which SDKs gets bug fixes/security updates first?_

For the Firebase components that are in this repository, this is the source of truth, so any changes will happen here first. However, they won't be an officially supported build of them until they're published in the official Firebase release.

_Which should we use? When should we use one over the other?_

If after reading about FirebaseCommunity and Firebase, there are any doubts, we recommend you use the officially supported [Firebase CocoaPod](https://cocoapods.org/pods/Firebase). BTW, FirebaseCommunity is published to [CocoaPods](https://cocoapods.org/pods/FirebaseCommunity) as well with 0.x versioning to emphasize its unofficial status.

Let us know if you have suggestions about improving the documentation clarity.

**Comment by js** [comment]
Thanks, I still think it puts a lot of effort on the casual observer to interpret the relationship between this and the official SDK, in particular the opening phrase

> This repository contains a subset of the Firebase iOS SDK source

Contains some "tribal" language that may not be clear to outsiders and casual observers/users of the SDK. Does it mean it's the same code as in the other SDK or a subset of features, subset of support etc.

Would be nice to have to above written out in clearer copy, since this repository is the initial hit on "firebase ios". At least it was confusing to me and a few other devs…

As for CocoaPods, apparently it has suboptimal commandline search:
```
$ pod search FirebaseCommunity
[!] Unable to find a pod with name, author, summary, or description matching `FirebaseCommunity` 
```

**Comment by paulb777** [comment]
@js Thanks for the feedback. I've added a redirect at the top of the README that will hopefully pop out to casual users in #374 

Regarding `pod search`, perhaps you need to do a `pod repo update`? It works for me:

> -> FirebaseCommunity (0.1.3)
>    Firebase Open Source Libraries for iOS.
>    pod 'FirebaseCommunity', '~> 0.1.3'
>    - Homepage: https://firebase.google.com
>    - Source:   https://github.com/firebase/firebase-ios-sdk.git
>    - Versions: 0.1.3, 0.1.2, 0.1.1, 0.1.0, 0.0.1 [master repo]
>    - Subspecs:
>      - FirebaseCommunity/Root (0.1.3)
>      - FirebaseCommunity/Core (0.1.3)
>      - FirebaseCommunity/Auth (0.1.3)
>      - FirebaseCommunity/Database (0.1.3)
>      - FirebaseCommunity/Messaging (0.1.3)
>      - FirebaseCommunity/Storage (0.1.3)
