### ISSUE TITLE
[Messaging] didReceiveRemoteNotification does not working in background

### ISSUE THREAD

**Issue by Vetalyo** [firebase/firebase-ios-sdk#368]
### Environment

  * Xcode version: _9.0_
  * Firebase SDK version: _FBSDKLoginKit (4.27.1)_
  * Firebase Component: _Messaging_
  * Component version: _FirebaseCommunity (0.1.3)_
  * iOS: _11.0.2, also tested on 9.3.5_

### The problem

I download Example, run the project and find out that `didReceiveRemoteNotification` callback works always when phone connected to mac (by cable or wireless debugging), in this case it works in foreground, background and on locked screen as well. But if phone does not connected to mac, the `didReceiveRemoteNotification` callback fires only when app in foreground.

To check this I added simple request to server in `didReceiveRemoteNotification`, which send current time to database.
Here is my code:
```
func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
    print("application:didReceiveRemoteNotification:fetchCompletionHandler: called, with notification:")

    let date = Date()
    let formatter = DateFormatter()
    formatter.dateFormat = "dd.MM.yyyy hh:mm:ss"
    let result = formatter.string(from: date)

    // prepare json data
    let json: [String: Any] = ["title": result]

    let jsonData = try? JSONSerialization.data(withJSONObject: json)

    // create post request
    let url = URL(string: "https://testfirebase-5d1ab.firebaseio.com/testCollection.json")!
    var request = URLRequest(url: url)
    request.httpMethod = "PUT"

    // insert json data to the request
    request.httpBody = jsonData

    let task = URLSession.shared.dataTask(with: request) { data, response, error in
        guard let data = data, error == nil else {
            print(error?.localizedDescription ?? "No data")
            return
        }
        let responseJSON = try? JSONSerialization.jsonObject(with: data, options: [])
        if let responseJSON = responseJSON as? [String: Any] {
            print(responseJSON)
        }
    }

    task.resume()

    print("\(userInfo.jsonString ?? "{}")")
    completionHandler(.newData)
  }
```

My notification payload to FCM is:
```
{
 "to": "device_id",
   "content_available": true,
   "priority": "high",
   "data": {
       "someParam": true
   }
}
```

In firebase console, I set up my APNs Authentication Key.
In xCode in project capabilities Enabled Push Notification and Background Modes->Remote notification.

For simple testing I create firebase database, you can login by this account
```
testfirebase1110@gmail.com
zxc123zxc
```

#### Steps to reproduce:

1. Change `didReceiveRemoteNotification` according to my example.
2. Run app on device
3. Unplug cable
4. Move app to background
5. Send remote notification as described above
6. Check database for changes

**Comment by rsattar** [comment]
There is a known issue in iOS 11.0 where iOS is not processing silent notifications often. [This is fixed in iOS 11.1 beta 1](http://www.redmondpie.com/ios-11.1-beta-1-release-notes-changelog-and-all-changes-in-one-place/). 

In my own testing on iOS 11.0, I've noticed this issue on my test devices. Are you able to see if this is fixed in 11.1?

If you are receiving the silent notification sometimes, it generally means that your FCM API calls / FCM SDK integration is working fine. If it was broken it would never work.

If this is happening also in iOS 9.3.5, keep in mind that silent notifications are disabled by iOS if:

1. User force quits the app (Stopping debugging in Xcode is ok), until next app start
1. User turns on low-power mode
1. User disables background refresh
1. User restarts phone, until next app start

**Comment by Vetalyo** [comment]
@rsattar, I've tested it on 9.3.5 again and find out that it works when app in foreground and background but only when connected with cable.
When I disconnect cable and move app to the background - nothing happens, the same situation like with iOS 11.0.2.

I checked this by following all of the items listed below:

- [+] User force quits the app (Stopping debugging in Xcode is ok), until next app start
- [+] User turns on low-power mode
- [+] User disables background refresh
- [+] User restarts phone, until next app start

**Comment by Vetalyo** [comment]
I try to use [PushNotificationIOS](https://facebook.github.io/react-native/docs/pushnotificationios.html) on iOS 9.3.5 and 11.0.2 by APNs. So I find out that on 9.3.5 it works in background without connected cable, `didReceiveRemoteNotification` fired each time well. But it didn't work on 11.0.2, it works like I described above.

**Comment by rsattar** [comment]
@Vetalyo In your app are you registering for the `UNNotificationCenterDelegate`? If so, then you don't receive `didReceiveRemoteNotification`, it'll arrive in `center:willPresentNotification:completionHandler:`.

**Comment by Vetalyo** [comment]
@rsattar, I can't found this method in your sample project. Could you please explain your answer in more detail?
Why it should not work with this method `didReceiveRemoteNotification`, if it's works well with cable?

**Comment by morganchen12** [comment]
He's talking about [this UNUserNotificationCenterDelegate method](https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/1649518-usernotificationcenter).

In your case, silent notifications may be getting throttled in the background (see the notice under "Configuring a Silent Notification" [here](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH10-SW1)).

**Comment by Vetalyo** [comment]
@morganchen12 , thanks for reply!
No, I'm not using `UNNotificationCenterDelegate` in my app.

> In your case, silent notifications may be getting throttled in the background (see the notice under "Configuring a Silent Notification" here).
Can you please help me figured out. How to make it work correctly ? I really need this functionality in my app 😭
While testing I send only one notification, but it doesn't work. As I understand notification will be throttled when sending a lot of notification at short time. 

Also I tested your example on iOS 10.3.3 - the same result - it works only when iPhone connected to cable. When cable disconnected - `didReceiveRemoteNotification` callback does not work.

**Comment by morganchen12** [comment]
I'm not entirely certain the extent of Apple's silent notification throttling, but their [documentation](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application) states:

>The system tracks the elapsed time, power usage, and data costs for your app’s background downloads. Apps that use significant amounts of power when processing remote notifications may not always be woken up early to process future notifications.

Your callback code does several relatively expensive things, which could be deferred to reduce the cost of the callback and potentially the amount you're getting throttled.

- Don't initialize a `DateFormatter` in the callback. Initializing `DateFormatter`s is expensive--instead you should initialize the `DateFormatter` once either lazily or upon `AppDelegate` initialization, then store it in a property and reference that property throughout your file.
- `JSONSerialization` and `URLSession`: Instead of serializing the small amount of JSON and immediately uploading it, try enqueueing these tasks somewhere and processing them when the app is foregrounded.

**Comment by Vetalyo** [comment]
@morganchen12, thank you for reply! 
I already delete this from my code and leave only simple post request.
Result the same.
Are you sure that it works on iOS 9-10 without connected cable?

**Comment by morganchen12** [comment]
Yes, FCM does not do any of its own client-side throttling. If you remove the post request as well so the method stub is completely empty aside from calling the completion handler, is there any change?

**Comment by Vetalyo** [comment]
Okay, could you please provide me, how to check that it works if I remove the post request?
Sorry for stupid question, I'm working with react-native and I'm newbie in Swift.
Thank you for help.

**Comment by morganchen12** [comment]
You can just add a log statement.

**Comment by Vetalyo** [comment]
How I gonna see NSLog() or print(), when device not connected to Mac?

**Comment by morganchen12** [comment]
You can find the logs retroactively by plugging in the phone. Alternatively you can opt for something simpler, like presenting a UILocalNotification.

**Comment by Vetalyo** [comment]
Could you please explain how to check the logs retroactively by plugging in the phone?
Because when I connect phone to mac I found only the way to see logs which start right after connection, without retroactively logs.
Thank you, very appreciate your help!

**Comment by morganchen12** [comment]
You're right, looks like Xcode's organizer doesn't show previous log statements. Can you try the UILocalNotification route instead? You can modify your app's badge number to make distinguishing easier.

**Comment by Vetalyo** [comment]
Okay, It's works with `UILocalNotification`, badge changing always correctly. But in documentation I saw that I can use silent notifications to make request and update data.
I need to get data from phone and save it to server.

**Comment by morganchen12** [comment]
You'll still be able to do that--what we were trying to measure by reducing the logic in your application callback was how much the system is throttling your silent notifications. Instead of directly sending the upload requests in the notification handler, you should queue them somewhere and have your app upload them all at once when foregrounded. 

I'm going to close this issue as it seems we've appropriately diagnosed your problem, but if you have any other questions feel free to continue commenting.

**Comment by Vetalyo** [comment]
That's great, but that's have no sense for me. Because I need to get this data from user on receiving the silent notification, that's why I'm sending silent notification. 
I can send this data from user without any push/silent notification's at all. 
Just make this request on event - app comes to foreground.
So that's not a solution for me.
I need to send it in moment when silent notification comes 😭
Thank you for reply!

**Comment by matiasvillaverde** [comment]
Hi, I am using the same silence push notifications to schedule local push notifications for a calendar app. 

1) The server notifies by a silence push that there is a new event in the calendar.
2) The client must use that silence push to schedule reminders for that event using local push notifications.

But I can only receive this push when I am in foreground. Is possible to receive them when I am in background or the app is killed? In android this feature is working.

**Comment by Tabassumbanu786** [comment]
Hi, I am using the same silence push notifications to schedule local push notifications for app.
I can only receive this push when I am in foreground and background . it Is possible to receive them when  app is killed? for ios??

**Comment by morganchen12** [comment]
iOS will not send silent notifications if the user manually force-quits your app. Unfortunately this is a platform behavior.

**Comment by Tabassumbanu786** [comment]
thanks for quick reply :)
i am totally new in swift so plz help me out
 let notification = UILocalNotification()
        notification.fireDate = NSDate(timeIntervalSinceNow: 1) as Date
        print("hello")
        notification.alertTitle = userInfo["title"] as? String
        notification.alertBody = userInfo["message"] as? String
        notification.alertAction = "Ok" //  used in UIAlert button or 'slide to unlock...' slider in place of unlock
        notification.soundName = UILocalNotificationDefaultSoundName
        notification.userInfo = userInfo // Array of custom parameters
        notification.applicationIconBadgeNumber = 1
        UIApplication.shared.scheduleLocalNotification(notification)

i m using this local notification so 
it is not possible to get notification when app was killed?

**Comment by morganchen12** [comment]
If this local notification code is in a silent notification handler, it won't get called when the app has been force-quit by the user.
