### ISSUE TITLE
Application hangs on startup

### ISSUE THREAD

**Issue by proxi** [firebase/firebase-ios-sdk#3697]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.3
  * Firebase SDK version: 6.70
  * Firebase Component: Analytics
  * Component version: 6.1.1

#### Steps to reproduce:

Sometimes app hangs on launch. If paused, the following stack trace originatinc from `APMMeasurement load` is visible:

<img width="272" alt="Zrzut ekranu 2019-08-22 o 11 56 33" src="https://user-images.githubusercontent.com/107399/63761595-bad0cc00-c8c1-11e9-94c4-785a9b374a60.png">

**Comment by proxi** [comment]
Here you go:

[Podfile.lock.zip](https://github.com/firebase/firebase-ios-sdk/files/3547037/Podfile.lock.zip)

**Comment by morganchen12** [comment]
Closing this since we haven't been able to repro the issue and it's originating from a UIKit call.
