### ISSUE TITLE
Deep linking is not working in iOS 10.4

### ISSUE THREAD

**Issue by NayanBhut** [firebase/firebase-ios-sdk#3699]
here is the code for link creation 
      
    guard let link = URL(string: "XXXXXXX.XXXX/?XXXX=20") else { return true }
        let dynamicLinksDomainURIPrefix = "https://XXXXX.page.link"
        guard let linkBuilder = DynamicLinkComponents(link: link, domainURIPrefix: dynamicLinksDomainURIPrefix) else{return true}
        linkBuilder.iOSParameters = DynamicLinkIOSParameters(bundleID: "XXX.XXXXX")
        linkBuilder.iOSParameters?.appStoreID = "XXXXXXXX"
        linkBuilder.androidParameters = DynamicLinkAndroidParameters(packageName: "XXX.XXXXXX")
        
        
        linkBuilder.shorten(completion: { (url, war, error) in
            guard let url = url else{return}
//            print(url)
       }
Here is the log of dynamic link creation.

---- Firebase Dynamic Links diagnostic output start ----
Firebase Dynamic Links framework version 4.0.3
System information: OS iOS, OS version 10.2.1, model iPhone
Current date 2019-08-27 11:19:08 +0000
Device locale en-US (raw en_US), timezone Asia/Kolkata
	Specified custom URL scheme is com.XXXXXXXX and Info.plist contains such scheme in CFBundleURLTypes key.
	AppID Prefix: XXXXXXXXX, Team ID: XXXXXXXX, AppId Prefix equal to Team ID: YES
performDiagnostic completed successfully! No errors found.
---- Firebase Dynamic Links diagnostic output end ----

The dynamic link working fine in ios 11.0 and other os but it's not working in 10.0

I implemented all methods for getting data like this but that link open AppStore URL instead of the app

please help thanks 

    func application(_ application: UIApplication, continue userActivity:NSUserActivity,restorationHandler: @escaping ([UIUserActivityRestoring]?) ->Void) -> Bool {
        let handled = DynamicLinks.dynamicLinks().handleUniversalLink(userActivity.webpageURL!) { (dynamiclink, error) in
            // ...
            print(dynamiclink?.url?.query)
            
        }
        
        return handled
     }
    
    func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any]) -> Bool {
        return application(app, open: url,
                           sourceApplication: options[UIApplication.OpenURLOptionsKey.sourceApplication] as? String,
                           annotation: "")
    }
    
    func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
        if let dynamicLink = DynamicLinks.dynamicLinks().dynamicLink(fromCustomSchemeURL: url) {
            // Handle the deep link. For example, show the deep-linked content or
            // apply a promotional offer to the user's account.
            // ...
            return true
        }
        return false
    }

**Comment by NayanBhut** [comment]
Hello @ryanwilson and @morganchen12 

As par your comment I checked in notes on shared link and I can see an option "one in myApp" but I share the link on facebook and try to open that link but it does not redirect in my app
kindly guide me

Thanks and regards

**Comment by NayanBhut** [comment]
![Screen Shot 2019-08-28 at 10 19 56 am](https://user-images.githubusercontent.com/38653553/63827455-d18a2800-c980-11e9-93d2-e2d932d3b720.png)
here is the attachment from notes

**Comment by NayanBhut** [comment]
![Screen Shot 2019-08-28 at 10 19 56 am](https://user-images.githubusercontent.com/38653553/63827543-20d05880-c981-11e9-82a7-f8d9bb566195.png)
here is the attachment with a long tap in notes

Thanks and regards

**Comment by NayanBhut** [comment]
Hello @morganchen12 
greetings of the day

as per your comment, we checked it and if we tap on open app it's working fine but while sharing a link on facebook it's redirecting to Appstore, not our app please guide us

Thanks and regards,

**Comment by morganchen12** [comment]
When opening the link from Facebook is it opening the preview page in Facebook's in-app browser?

**Comment by NayanBhut** [comment]
Hello @morganchen12 
greetings of the day

yes once I tap on the link in facebook, it is open in facebook's in-app browser!

Thanks and regards,

**Comment by morganchen12** [comment]
That's a Facebook app-specific behavior. Can you test it in a different app like Messages?

**Comment by NayanBhut** [comment]
Hello @morganchen12 
thanks for your response it's working fine in messages and notes so **as per your comment this isn't worked on Facebook.**

so now we've to find why it's not working on facebook.

**Comment by morganchen12** [comment]
It's deliberate behavior by Facebook; if you install other apps that support universal links you'll note that the Facebook app doesn't open their apps either.

Closing this as it's not a Firebase issue and there isn't much we can do about Facebook's hostile in-app browser behavior.
