### ISSUE TITLE
Could not find auto-linked framework 'Firebase'

### ISSUE THREAD

**Issue by Tapestes** [firebase/firebase-ios-sdk#3708]
* Xcode version: 10.3
  * Firebase SDK version: 
  * Firebase Component: Database

### Describe the problem
Import Firebase works fine, but once I include FirebaseApp.configure() in the AppDelegate's didFinishLaunchingWithOptions, the application crashes indicating it can't find Firebase.  

```
ld: warning: Could not find auto-linked framework 'Firebase'
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FIRApp", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

As instructed, I removed Firebase from Link Binary with Libraries in the Build Phases.

**Comment by paulb777** [comment]
The `Could not find auto-linked framework 'Firebase'` warning should be harmless.
