### ISSUE TITLE
Manual constructed Dynamic Link without app preview page (i.e. efr=1) fails fingerprint match on initial app install. 

### ISSUE THREAD

**Issue by marktrobinson** [firebase/firebase-ios-sdk#3719]
### Environment

  * Xcode version: 10.3
  * iOS version: 12.2
  * Firebase SDK version: 6.0.0
  * Firebase Component: DynamicLinks
  * Component version: 4.0.0

### Problem

I have created a manually constructed dynamic link as follows:

```
https://my.link/
?link=universal_link
&apn=android_apn
&amv=android_min_version
&ibi=app_bundle_id
&isi=app_identifier
&efr=1
&utmSource=domain
&utmMedium=dynamic_link
&utmCampaign=dynamic_link
&utmTerm=search_query
&ct=dynamic_link
&mt=8
&pt=provider_token
```

I have certified that all of the above is correct.  All Dynamic Links work as they should _except_ the initial app install.

### Steps to reproduce 

- Tapping on a Dynamic Link with the above format
- I do not have the app installed
- I am not in safari or in an incognito mode
- I tap "Open" and am taken to the app store
- I side load the app via Xcode
- `application(_:open:options:)` called
- Dynamic Link is not found: `app_bundle_id://google/link/?dismiss=1&is_weak_match=1`

### Other notes
- Strangely i got it to work yesterday _once_ when disconnecting from wifi and using 4G after reading another Github issue on how the fingerprinting works. - haven't gotten it to work since though trying to reproduce that. (source: https://github.com/firebase/firebase-ios-sdk/issues/233#issuecomment-329293196)
- If app preview page is enabled (i.e efr=0), it _always_ works - which makes sense, given the explanation here: https://firebase.google.com/docs/dynamic-links/link-previews#app_preview_pages

The Link above specifies: 
> Note that without the app preview page, Dynamic Links cannot be received as unique matches on iOS

Dynamic Links _always_ work without the app preview page except initial app install.  Does this mean that app preview page _must_ be enabled for iOS apps to ensure the Dynamic Link is found on initial app install?

Any ideas?

**Comment by morganchen12** [comment]
iirc this is intended behavior, since Dynamic Links uses the preview page for initial fingerprinting. The fingerprint data is then used to establish if the device that clicked the dynamic link is the same device launching the app after installing it. @dmandar can you confirm?

**Comment by marktrobinson** [comment]
Thanks @morganchen12.  If that's the case, why does it work in the other scenarios? i.e.

1. App is installed and in background
2. App is installed and not in background

**Comment by dmandar** [comment]
If the app is installed, FDL will use iOS universal links to open the target app. For first app installs, it is recommended to use the app preview page because fingerprinting may not work reliably in all scenarios (depending on a variety of factors). App preview pages solve this by copying the link to the pasteboard as mentioned here: https://firebase.google.com/docs/dynamic-links/link-previews

**Comment by marktrobinson** [comment]
Awesome, thanks @dmandar for the clarification.
