### ISSUE TITLE
Using Firebase Phone Authentication without swizzling

### ISSUE THREAD

**Issue by marknf94** [firebase/firebase-ios-sdk#372]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 8.3.1
  * Firebase SDK version: 4.2.0
  * Firebase Component: Auth
  * Component version: 4.2.0

#### Steps to reproduce:

I'm currently implementing firebase phone Authentication, and can successfully implement the phone authentication using the firebase UI without swizzling, but from my research it seems that implementing firebase phone authentication without swizzling requires the user to allow notifications. I know that firebase sends a silent notification that does not need to be approved through allowing notifications but it seems the only way to get that notification without swizzling is to ask the user to allow notification. Does anyone know how or if its possible to do this without swizzling and without asking the user for notification permissions?

I have added to push notification certificates to firebase, and have added all the needed function listed in the firebase phone ui docs.

Without asking the user for to allow notifications this function listed from the phone auth docs does not get called (the user also has to select allow)

```
func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
  // Pass device token to auth
  Auth.auth().setAPNSToken(deviceToken, type: AuthAPNSTokenTypeProd)

  // Further handling of the device token if needed by the app
  // ...
}
```
If this functions is not called the setAPNSToken is not set, I will not get the silent notification to continue with phone auth, and I will get the generic error

> Authentication error: There seems to be a problem with your project's Firebase phone number authentication set-up, please make sure to follow the instructions found at https://firebase.google.com/docs/auth/ios/phone-auth

#### Relevant Code:

```
```

**Comment by XiangtianDai** [comment]
@marknf94 On iOS 8 and above, because Firebase Auth uses silent notifications, it does not require explicit user permission for notifications to sign in with phone numbers. This is unrelated to whether swizzling is enabled or disabled. The user is not even prompted for notifications in the first place. I wonder why the user sees the prompt for allowing notification in your app? Was it on iOS 7?

Also, if `application(_:didRegisterForRemoteNotificationsWithDeviceToken:)` is somehow not called, can you check wether `application(_:didFailToRegisterForRemoteNotificationsWithError:)` is called or not, and if so, what is the error?

**Comment by marknf94** [comment]
@XiangtianDai Thanks for the response, Im aware that they should not be prompted in the first place which is part of my confusion. Only when prompting the user to allow notification though then I am able to get `application(_:didRegisterForRemoteNotificationsWithDeviceToken:)` to be called. 

I added `application(_:didFailToRegisterForRemoteNotificationsWithError:)` to my project and it was not called either.

**Comment by XiangtianDai** [comment]
@marknf94 Please allow me to understand more about the issue:

- This happens on a real device, not on a simulator, correct?
- Which iOS version is it, or does the issue appears on all iOS versions?
- Does your app, or any of the libraries your app uses, call `UIApplication`'s `registerForRemoteNotifications(matching:)`? How about `UNUserNotificationCenter`'s `requestAuthorization(options:)`?
- Does enabling swizzling (i.e., removing `FirebaseAppDelegateProxyEnabled` from plist or setting its value to `YES`) make a difference?

**Comment by marknf94** [comment]
@XiangtianDai 
- Yes this happens on a real device
- I tested it across 2 devices 1 on iOS 11 and another on iOS 10, same issue on both
- I call `registerForRemoteNotifications(matching:)` , calling `UNUserNotificationCenter's requestAuthorization(options:)` request notification permission from the user so I do not want to call that on the login screen but it is called later once they have logged in
- No, I tried to enable swizzling but still the same issue arrises

**Comment by XiangtianDai** [comment]
@marknf94 What if you don't call either `registerForRemoteNotifications(matching:)` or `UNUserNotificationCenter`'s `requestAuthorization(options:)`? When you start the phone auth sign in flow FirebaseAuth automatically calls `registerForRemoteNotifications()`, which unlike the two previous methods, does not show any user prompt.

**Comment by marknf94** [comment]
@XiangtianDai if FirebaseAuth automatically calls `registerForRemoteNotifications()` then my breakpoint in `application(_:didRegisterForRemoteNotificationsWithDeviceToken:)` or `application(_:didFailToRegisterForRemoteNotificationsWithError:)` and then in `func application(_ application: UIApplication, didReceiveRemoteNotification notification: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult)` should be hit then correct? They currently do not, with and without swizzling enabled

**Comment by marknf94** [comment]
@XiangtianDai  An update: 

I turned swizzling back off, and I am now receiving the notification in 

`func application(_ application: UIApplication, didReceiveRemoteNotification notification: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult)`

but it does not let phoneAuth go through because 

```

func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        
        Auth.auth().setAPNSToken(deviceToken, type: .unknown)

    }
```

is not getting called first.

**Comment by XiangtianDai** [comment]
@marknf94 In your implementation of `application(_:didReceiveRemoteNotification:fetchCompletionHandler:)` did you call `Auth.auth().canHandleNotification(_:)` with the notification you have received? Before attempting to get APNs token, FirebaseAuth tests whether your app delegate forwards notifications to itself, and returns `"ERROR_NOTIFICATION_NOT_FORWARDED"` if the test failed.

**Comment by marknf94** [comment]
@XiangtianDai Yes my function appears like this and does handle the notification 

```
    func application(_ application: UIApplication, didReceiveRemoteNotification notification: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        if Auth.auth().canHandleNotification(notification) {
            completionHandler(UIBackgroundFetchResult.noData)
            return
        }
        // This notification is not auth related, developer should handle it.
    }
```

I believe the main issue now is that 

```
func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        
        Auth.auth().setAPNSToken(deviceToken, type: .unknown)

    }
```

nor 

`func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error)`

is getting called, even though I have added `        UIApplication.shared.registerForRemoteNotifications()
`
before `FirebaseApp.configure() ` in `didFinishLaunchingWithOptions`

**Comment by XiangtianDai** [comment]
@marknf94 So neither of your implementations of `application(_:didRegisterForRemoteNotificationsWithDeviceToken:) nor that of `application(_:didFailToRegisterForRemoteNotificationsWithError:)` is called after you explicitly call `UIApplication.shared.registerForRemoteNotifications()`? Then it looks your app does not have APNs set up correctly. Please double check the following:
- "Push notifications" is enabled in "Capabilities" of your app in Xcode settings.
- "Background Modes" is enabled in "Capabilities" of your app in Xcode settings and under it "Remote notifications" is checked.
- Your app ID registered on apple developer site has push notification enabled.
- (less likely but just in case) "Background refresh" is not disabled on the device or for your app in iOS Settings, and the network is available when testing.

If any of above needs to be change, please delete the app completely from the device before re-compile and run it again, otherwise the change may fail to be picked up by the device.

**Comment by marknf94** [comment]
@XiangtianDai The issue was this point 

- "Background Modes" is enabled in "Capabilities" of your app in Xcode settings and under it 
   "Remote notifications" is checked.

Then deleted the app and reinstalled and it worked!

Thanks for the help!

**Comment by morganchen12** [comment]
Thanks for confirming, @marknf94!
