### ISSUE TITLE
UIWebView usage and ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by dloic** [firebase/firebase-ios-sdk#3722]
As of Thursday, August 29, 2019, AppStoreConnect is providing a warning for uploaded applications that use UIWebViews APIs:

> Dear Developer,
> 
> We identified one or more issues with a recent delivery for your app, "XXX Dev" A.B.C (X.Y.Z). Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
> 
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.
> 
> Best regards,
> The App Store Team

I did have a look at Firebase and Dynamic Links component is still making use of UIWebView for iOS version 7.X. I'm not sure what is the lowest iOS version Firebase wants to support, but I'm pretty sure the AppStoreConnect warning will turn soon into an error.

This will avoid people to upload apps that are making use of DynamicLinks.

  * Firebase SDK version: All
  * Firebase Component: Dynamic Links

**Comment by paulb777** [comment]
Fixed by #3723
