### ISSUE TITLE
I hope GDTEvent can be renamed

### ISSUE THREAD

**Issue by zengqingf** [firebase/firebase-ios-sdk#3729]
I hope GDTEvent can be renamed as it conflicts with tencent mobile advertising，
https://d3g.qq.com/gdt/sdk/ios/release/GDT_iOS_SDK_4.10.8.zip
Tencent mobile advertising is very famous in China, so I had to choose one or the other

**Comment by ryanwilson** [comment]
@zengqingf thank you very much for bringing this to our attention! Looking into it now.

**Comment by mikehaney24** [comment]
I'm working through a couple proposals to solve this problem
