### ISSUE TITLE
Push Does Not Arrive For iOS10 app

### ISSUE THREAD

**Issue by mazz** [firebase/firebase-ios-sdk#373]
hi all I have an iOS10 app, using firebaseinstanceID 2.0.3 installed via cocoapods and I’m getting a FCM token OK at startup. but when I enter that token in the Firebase web console by sending to Single Device, the push never arrives. Once, on October 6, the push arrived, but never after that.

I feel it is safe to assume the token I used was still valid. It was generated a couple of minutes before I sent the push.

I re-installed the app and tried again many times since Oct 6, never saw a push by an FCM token since then. The push will arrive if I use the APNS token via NodeJS-based script, so it is definitely the Firebase infrastructure that is the issue here.

Any suggestions? I have also done things like registering for notifications as early in the applicationDidFinishLaunching callback, reverting to FirebaseInstanceID 2.0.0 and these have had no effect.

**Comment by paulb777** [comment]
@mazz Please update to FirebaseInstanceID 2.0.4 and FirebaseMessaging 2.0.4 and retry.

**Comment by FaithfulAudio** [comment]
@paulb777 thanks, that seems to have remedied the situation. Thanks.

BTW: for Xcode 9 users who are upgrading to 2.0.4, you need to set your Build Settings > Swift Version to 4.0 for 2.0.4 to compile.

**Comment by paulb777** [comment]
@mazz Glad it's working now. Thanks for reporting back.

BTW, the Firebase code is all Objective C, son nothing about Firebase itself should require Swift Version setting changes.
