### ISSUE TITLE
Saving and deleting a document in one batch crashes the application and breaks the local database forever

### ISSUE THREAD

**Issue by petrovi4** [firebase/firebase-ios-sdk#3733]
* Xcode version: Version 10.3 (10G8)
  * Firebase SDK version: 6.7.1
  * Firebase Component: Firestore
  * Component version: 6.7.1

Preparatory stage. Create and save the document in Firestore. Get a reference for this document.
1. Create batch
2. Add saving of document data to the batch
3. Add document deletion to the batch
4. Make a commit.
The application is crashing. All subsequent start attempts will result in a "signal SIGABRT" error (based on the stacktrace in [FIRFirestore collectionWithPath] method)

```swift
var db: Firestore

...

let batch = db.batch()

var docRef = db.collection("SOME_COLLECTION").document("SOME_EXISTING_DOC_ID")
batch.setData(["Foo": "bar"], forDocument: docRef, merge: true);

...

batch.deleteDocument(docRef)

...

batch.commit(completion: ...)
```

Yes, we can argue that saving and deleting within one batch is not the right logic. But this should not lead to the fact that the application can no longer run, and only need to reinstall it.

Besides, the problem is that the batch doesn't contain any information about the fact that it has already been added before, and you can't change the previously added save or delete transactions. This would solve the problem. Although the current bug, I think, should be fixed as well.

**Comment by wilhuff** [comment]
Agreed this shouldn't be happening.

Could you paste the stack trace you get?

**Comment by petrovi4** [comment]
Unfortunately (or fortunately :) I have continued my work and already added my code to the existing batch, which allows me to accumulate transactions and track duplicates, so I can't go back to the wrong code so quickly. 
Besides, there was only [FIRFirestore collectionWithPath] in the whole stack of readable calls. If it helps to localize the problem, I will roll back my code a bit later and send the stack.

**Comment by wilhuff** [comment]
Hrm. The case you're describing is one we cover explicitly with an integration test:

https://github.com/firebase/firebase-ios-sdk/blob/master/Firestore/Example/Tests/Integration/FSTTransactionTests.mm#L337

This means there's something else going on that could be specific to your configuration. I'll try to reproduce given the code you're suggesting above.
