### ISSUE TITLE
Remote Config returns outdated values for deleted config keys

### ISSUE THREAD

**Issue by GoodBadVlad** [firebase/firebase-ios-sdk#3745]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: Xcode 11 beta 7
  * Firebase SDK version: 6.7.0
  * Firebase Component: Remote Config
  * Component version: 4.3.0

### [REQUIRED] Step 3: Describe the problem

When I delete a config key/value from the console, the app keeps on getting the deleted value for that key, instead of the default one.

#### Steps to reproduce:

1. The app supplies a config key "testKey" with default value "local". That key is not yet defined in Firebase console. Next time the app fetches and activates the remote config, it gets value "local" for key "testKey".

2. Add the config key "testKey" to the RemoteConfig console with value "remote" and publish the changes. Next time the app fetches and activates the remote config, it gets value "remote".

3. Delete the key "testKey" from the Firebase console by tapping on "testKey" and then tapping on the trash bin icon. Publish the changes. Next time the app fetches and activates the remote config, it gets value "local", as expected.

4. Without making any changes in the Firebase console, start the app again and let it fetch and activate the config. This time the app gets value "remote" for key "testKey", although this value has been deleted. The expected config value is "local", as in step 3.

**Comment by dmandar** [comment]
Thanks for reporting. We will try to repro and fix as appropriate.

**Comment by dmandar** [comment]
Fixed in #3926 and available in the next release.
