### ISSUE TITLE
Dynamic link handling only succeeding every second time

### ISSUE THREAD

**Issue by yahmad** [firebase/firebase-ios-sdk#3746]
### Environment
  * Xcode version: 10.3
  * Firebase SDK version: 6.3
  * Firebase Component: DynamicLinks
  * Component version: 4.0.0
  * Device: iPhone 7

### Problem
We are using Firebase dynamic links in our mobile apps, and have noticed a bug in the iOS app whereby opening multiple dynamic links in succession causes the SDK to error when trying to handle the second link. 

The issue is easily reproducible on the current device. Any ideas what we could be doing wrong here, or is this an internal SDK/service issue?

#### Steps to reproduce:
1. Obtain two dynamic links for the same app
2. Open the first dynamic link _(handled successfully)_
3. Open the second dynamic link **_(SDK returns "cancelled" error)_**

The `handleUniversalLink()` function returns a nil dynamic link, and an error with the following userInfo:
```
{
    NSErrorFailingURLKey = "https://firebasedynamiclinks.googleapis.com/v1/reopenAttribution?key=XXXX";
    NSErrorFailingURLStringKey = "https://firebasedynamiclinks.googleapis.com/v1/reopenAttribution?key=XXXX";
    NSLocalizedDescription = cancelled;
    NSUnderlyingError = "Error Domain=kCFErrorDomainCFNetwork Code=-999 \"(null)\" UserInfo={_kCFStreamErrorCodeKey=89, _kCFStreamErrorDomainKey=1}";
    "_kCFStreamErrorCodeKey" = 89;
    "_kCFStreamErrorDomainKey" = 1;
}
```

#### Relevant Code:

```
    func continueWithUniversalLink(url: URL, completion: (() -> Void)? = nil) -> Bool {
        return dynamicLinks.handleUniversalLink(url, completion: { [weak self] (dynamicLink, error) in
            guard let dynamicLink = dynamicLink, let self = self else {
                print(error?.localizedDescription ?? NSError(domain: "Unknown dynamic link error", code: 0, userInfo: nil))
                completion?()
                return
            }
            
            if let dynamicLinkURL = dynamicLink.url {
                self.handleDynamicLink(url: dynamicLinkURL)
            }
            completion?()
        })
    }
```

**Comment by dmandar** [comment]
Thanks for reporting. We were able to repro the issue and are investigating. ATM, it seems related to https://github.com/AFNetworking/AFNetworking/issues/4279

**Comment by morganchen12** [comment]
See #2303 for previous discussion

**Comment by yahmad** [comment]
Cleaning this up, since it looks like a third-party networking library issue.
