### ISSUE TITLE
FirebaseInAppMessagingDisplay - Failed to render and update auto layout

### ISSUE THREAD

**Issue by uddinr** [firebase/firebase-ios-sdk#3748]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.3
  * Firebase SDK version: 6.7.0
  * Firebase Component: Messaging (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 0.15.4

#### Steps to reproduce:

When using cocoapods to add 'Firebase/InAppMessagingDisplay' it seems when i open any storyboard files, i get the following error

<img width="757" alt="Screenshot 2019-09-02 at 13 47 00" src="https://user-images.githubusercontent.com/18418023/64115680-2adec680-cd88-11e9-9c0d-c9531ee2a401.png">

This error occurs when opening any storyboard file, after which the storyboard is unusable ie. no changes to the storyboard appear.

The only way we can workaround this error is by removing 'Firebase/InAppMessagingDisplay' from our pod file.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulb777** [comment]
We might need a reproducible example. I tried adding the pod to a sample app in Xcode 10.3 and was able to open the storyboard:

![Screen Shot 2019-09-02 at 8 27 02 AM](https://user-images.githubusercontent.com/73870/64124295-7e86eb00-cd5b-11e9-8a8b-118c15fb4e86.png)

**Comment by uddinr** [comment]
hi, whilst attempting to create a sample app, it seems the error in question is not occurring now, not sure what if anything i did, i will close this for now, if it reoccurs i will create an example project. thanks.

**Comment by CentrumGuy** [comment]
This is happening to me with the latest version of Xcode. I think this issue should be reopened because after installing FirebaseInAppMessaging on my project, my storyboards no longer layout and update. I get this error:
file:///.../Alerts.storyboard: error: IB Designables: Failed to render and update auto layout status for CustomNotification (Pg5-Wi-G39): dlopen(FirebaseInAppMessagingDisplay.framework, 1): no suitable image found.  Did find:
	FirebaseInAppMessagingDisplay.framework: unknown file type, first eight bytes: 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A

**Comment by rfarbod** [comment]
why is this closed when it's STILL not fixed??? 
i have the exact same problem and it's giving me a headache

**Comment by uddinr** [comment]
this is still happening for me, but i am unable to get this to occur in a test project, so i have disabled FirebaseInAppMessageDisplay pod in my project when working on any ui changes

**Comment by uddinr** [comment]
> why is this closed when it's STILL not fixed???
> i have the exact same problem and it's giving me a headache

can you provide an example project so it can be looked at

**Comment by CentrumGuy** [comment]
Yeah! In my project: [Xcode Archive Bug](https://github.com/CentrumGuy/Xcode-Archive-Bug), if you go to Main.storyboard you will see a UIViewController with a pink (custom @IBDesignable) view in the middle of it. If you try to move the pink view around or do anything in that storyboard, the storyboard won't update and you will get this error: 

file:///Users/.../FirestoreExample/Base.lproj/Main.storyboard: error: IB Designables: Failed to render and update auto layout status for UIViewController (aST-AI-4Ns): dlopen(FirebaseInAppMessagingDisplay.framework, 1): no suitable image found.  Did find:
	FirebaseInAppMessagingDisplay.framework: unknown file type, first eight bytes: 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A

**Comment by uddinr** [comment]
i can confirm the issue is present in the above example project.

@paulb777 can we please get this looked at? as i have had to disable the pod
