### ISSUE TITLE
Firebase remote config gets failure randomly

### ISSUE THREAD

**Issue by pradipaub36** [firebase/firebase-ios-sdk#3758]
### [READ] Step 1: Are you in the right place?

  Yes

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2
  * Firebase SDK version: 6.7.0
  * Firebase Component: 
- Firebase (6.7.0)
-  FirebaseABTesting (3.1.0)
-  FirebaseAnalytics (6.1.1)
-  FirebaseAnalyticsInterop (1.4.0)
-  FirebaseAuth (6.2.3)
-  FirebaseAuthInterop (1.0.0)
- FirebaseCore (6.2.1) 
- FirebaseCoreDiagnostics (1.0.1)
-  FirebaseCoreDiagnosticsInterop (1.0.0)
-  FirebaseDatabase (6.1.0)
-  FirebaseFirestore 1.4.5
-  FirebaseInAppMessaging (0.15.3)
-  FirebaseInAppMessagingDisplay (0.15.4)
-  FirebaseInstanceID (4.2.3)
-  FirebaseMessaging (4.1.3)
-  FirebaseRemoteConfig (4.3.0) (Auth, Core, Database, Firestore, Messaging, Storage, etc)

  * Component version: _____

### [REQUIRED] Step 3: Describe the problem
Firebase remote config gets failure randomly, not getting value from the reference key.
#### Steps to reproduce:
It happens randomly not able to identify the steps

**Comment by morganchen12** [comment]
Hey @pradipaub36, thanks for filing this issue. With no repro steps or error log, it will be difficult for us to debug this.

Does this issue reproduce in older versions of Remote Config?

**Comment by pradipaub36** [comment]
Yes, We faced the same issue in the older version as well. We have an app that is created for iOS and Android and we are facing the same issue in both randomly.

Let me try to identify the error logs. I'll let you know further details I get.

**Comment by pradipaub36** [comment]
Hello, @morganchen12  I have reviewed the logs and found the Remote config unable to retrieve the value from keys. getting blank("") value for all the keys randomly. Could you please help?

**Comment by paulb777** [comment]
@pradipaub36 As @morganchen12, this will be difficult to investigate without a reproducible example. Please share one. Are you able to reproduce with https://github.com/firebase/quickstart-ios/tree/master/config?
