### ISSUE TITLE
Cloud Messaging without swizzling calling appDidReceiveMessage from didReceive

### ISSUE THREAD

**Issue by ruralcoder** [firebase/firebase-ios-sdk#3776]
In the firebase documentation `appDidReceiveMessage` should be called when swizzling is disabled.

```
    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                willPresent notification: UNNotification,
                                withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
        let userInfo = notification.request.content.userInfo


        // With swizzling disabled, you must let Messaging know about the message, for Analytics
        Messaging.messaging().appDidReceiveMessage(userInfo)
```
Given the events `willPresent` and `didReceive` are fired at different times, I feel `appDidReceiveMessage` should also be called in `didReceive` despite Firebase documentation.

When `didReceive` is called, `willPresent` does not, thus missing out on an `appDidReceiveMessage`,

**Comment by chliangGoogle** [comment]
I think we swizzle didReceive as well: https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/Messaging/FIRMessagingRemoteNotificationsProxy.m#L31

And call appDidReceiveMessage in the swizzling: 
https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/Messaging/FIRMessagingRemoteNotificationsProxy.m#L548

Does that not work you? @ruralcoder
