### ISSUE TITLE
FirebaseCore Private header cleanup

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#3777]
The private headers FIRErrors.h and FIRErrorCode.h is no longer being used and should be deleted in the next major release.

Some of the other headers are internal and should be moved out of private and repackaged as internal.

**Comment by ryanwilson** [comment]
Just to confirm, moving out of private and repackaged as internal will match SwiftPM style, right?

**Comment by paulb777** [comment]
Yes, both CocoaPods and SwiftPM support internal headers.

If SwiftPM doesn't add support for private, we'll likely also have to convert private headers to public - but that's outside the scope of this issue.

**Comment by paulb777** [comment]
FIRBundleUtil.h and FIRVersion.h are the only private headers not currently used outside of Core.

**Comment by paulb777** [comment]
FIRBundleUtil.h and FIRVersion.h are addressed in #4590

The header removal should still happen with Firebase 7

**Comment by paulb777** [comment]
The reorganization is addressed in #5759. The FIRError.h cleanup still requires cleanup in internal Remote Config sources.

Related to b/147219276

**Comment by paulb777** [comment]
Fixed by #6439 and will release with Firebase 7.
