### ISSUE TITLE
getDocumentsWithCompletion execution time is very high

### ISSUE THREAD

**Issue by agordeev** [firebase/firebase-ios-sdk#378]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.0 (9A235)
  * Firebase SDK version: 4.3.0
  * Firebase Component: Firestore
  * Component version: 0.8.0

### [REQUIRED] Step 3: Describe the problem

`getDocumentsWithCompletion` executes very very very long time (more than 5 mins) on almost empty database. 

This happens only if you call it in `completionHandler` of another `getDocumentsWithCompletion`. So, basically, two consecutive requests causes this issue.

**Comment by morganchen12** [comment]
Does this happen consistently, or intermittently? Can you share the console logs when making the consecutive requests?

**Comment by forbidden404** [comment]
It's been happening to me too, I'd like to know how to get the console logs for this, because I don't get any error, the call just takes forever.

**Comment by agordeev** [comment]
This stopped happening for me without any reason. Looks very weird.

**Comment by morganchen12** [comment]
Next time this happens, can you make sure to capture your device logs and also double check that there's no server incidents ongoing? I'll keep this issue open for the time being.

**Comment by wilhuff** [comment]
The issue you're describing exactly matches an ongoing issue in the backend where a small percentage of queries get stuck. Any write will unstick them. A fix is slated to roll out to production soon, but I can't promise exactly when it would happen.

**Comment by agordeev** [comment]
@wilhuff thank you for pointing this out!

**Comment by morganchen12** [comment]
@agordeev, is this still reproducible?
