### ISSUE TITLE
Undefined Symbols error in FirebaseMLCommon 0.17.0

### ISSUE THREAD

**Issue by seanvancity** [firebase/firebase-ios-sdk#3782]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2.1
  * Firebase SDK version: 6.7.0
  * Firebase Component: FirebaseMLCommon
  * Component version: 0.17.0

#### Steps to reproduce:

Updated Cocoapods to latest version, now getting Undefined Symbol errors when building in Xcode:

:-1: Undefined symbol: _OBJC_CLASS_$_FBMLx_GPBEnumArray
:-1: Undefined symbol: _OBJC_CLASS_$_FBMLx_GMVBarcodeInitializationOptions

**Comment by paulb777** [comment]
Firebase 6.8.0 along with FirebaseMLCommon 0.18.0 released today.  Please update to see if the problem is resolved. If not, please share the Podfile and Podfile.lock.

**Comment by seanvancity** [comment]
Looks to be resolved, thanks
