### ISSUE TITLE
Is Firebase/Core required for iOS or not?

### ISSUE THREAD

**Issue by GoldenJoe** [firebase/firebase-ios-sdk#3798]
#### Problem:

The documentation at https://firebase.google.com/docs/ios/setup states:

> You no longer need to add the iOS pod Firebase/Core. This SDK included the Firebase SDK for Google Analytics. Now, to use Analytics (or any of the Firebase products that require or recommend the use of Analytics), you need to explicitly add the Analytics pod: Firebase/Analytics.

This is apparently untrue, as I cannot read from Firebase without the Core pod.

#### Environment:

  * Xcode version: 10.3 (10G8)
  * Firebase SDK version: 6.8.0
  * Firebase Component: Firestore/Core
  * Component version: (how to find this? updated to latest pod as of writing)

#### Steps to reproduce:

Install Firebase without the Core pod. Try read from Firebase.

#### Relevant Code:

Podfile:
```
platform :ios, '11.0'
target 'MyProject' do
use_frameworks!

pod 'Firebase/Auth'
#pod 'Firebase/Core' #without this, you will be able to compile and run, but Firestore won't initialize
pod 'Firebase/Firestore'
end

target 'MyProjectTests' do
use_frameworks!
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Firestore'
end
```

Accessing Firebase:
```
FirebaseApp.configure()
let db = Firestore.firestore() // this is where we fail
db.collection("testCollection").getDocuments { (querySnapshot, err) in
    if let err = err {
         print("Error getting documents: \(err)")
    } else {
         for document in querySnapshot!.documents {
             let data = document.data()
             print("\(document.documentID) => \(document.data())")
         }
    }
}
```

**Comment by morganchen12** [comment]
Can you share your `Podfile.lock`? The FirebaseCore pod should still be getting pulled in as a dependency, and still needs to be initialized at app launch for Firestore and Auth to work.

**Comment by GoldenJoe** [comment]
I'm sorry, but after posting the question, I removed all pods and reinstalled with Core. I supposed I could just remove it and submit the lock, but that would be the same as following the reproduction steps.

Also, it never works in a unit testing target but I'll have to post a separate issue for that.

**Comment by morganchen12** [comment]
Are you getting a bunch of duplicate class definition warnings in console when running unit tests? That issue is usually caused by two conflicting definitions of FIRApp.

**Comment by GoldenJoe** [comment]
No, if you just use `inherit! :search_paths` instead of adding the Firebase pods to the unit test target, there will be no duplicates. Everything will compile and appear to work correctly, but no actual read/write operations will occur. No errors thrown, it just fails to initialize properly and fails silently.

**Comment by paulb777** [comment]
Any clues in the console logs?

**Comment by GoldenJoe** [comment]
No, nothing related appears in the console log.


________________________________

**Comment by paulb777** [comment]
Please share a reproducible example. We have plenty of tests that verify that Firestore works without FirebaseAnalytics - which is the only difference you should see in the `Podfile.lock` when adding `Firebase/Core`.
