### ISSUE TITLE
GDTEvent class conflict

### ISSUE THREAD

**Issue by arthurchenjs** [firebase/firebase-ios-sdk#3800]
GDTEvent class conflict

duplicate symbol _OBJC_CLASS_$_GDTEvent in:
.........SDK/Frameworks/GDT/libGDTMobSDK.a(GDTEvent.o)
.........Build/Products/Debug-iphoneos/GoogleDataTransport/libGoogleDataTransport.a(GDTEvent.o)

**Comment by morganchen12** [comment]
Duplicate of #3729
