### ISSUE TITLE
Remove configureWithoutSendingNotification call.

### ISSUE THREAD

**Issue by ryanwilson** [firebase/firebase-ios-sdk#381]
https://github.com/firebase/firebase-ios-sdk/blob/2b40693be4c9aa2c94b668fb144c6993f557b8d6/Firebase/Core/Private/FIRAppInternal.h#L159

This is not referenced internally or externally.

**Comment by ryanwilson** [comment]
Does this need to be part of a future major release? @davidair

**Comment by davidair** [comment]
Since it's internal, it can be released in a patch.

**Comment by ryanwilson** [comment]
Fixed with #383
