### ISSUE TITLE
GDTAssert.h not being copied when installing version 6.8.1

### ISSUE THREAD

**Issue by jakobmygind** [firebase/firebase-ios-sdk#3815]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.3
  * Firebase SDK version: 6.8.1
  * Firebase Component: GoogleDataTransport
  * Component version: 1.1.2

### [REQUIRED] Step 3: Describe the problem

When using latest firebase release (6.8.1) GoogleDataTransport/GDTAssert.h is missing and thus failing the build

#### Steps to reproduce:

1. use this pod file in a totally clean environment (found this on a CI):

```
platform :ios, '11.4'

target 'xx' do
 
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Google-Mobile-Ads-SDK'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.13.4'
  pod 'Firebase/Performance'
  pod 'Firebase/Messaging'

end
```

2 run pod install

3. build project

4. observe build fails due to <GoogleDataTransport/GDTAssert.h> missing

5. Look in GoogleDataTransport and observe file is indeed missing

```

**Comment by ryanwilson** [comment]
Hi @jakobmygind - I wasn't able to reproduce this in either Xcode 10.1 or Xcode 10.3 using the same Podfile.

Are you able to reproduce this locally? A compilation error would also be helpful to find out where the error surfaced.

Thanks!

**Comment by jakobmygind** [comment]
Hi @ryanwilson Yes, we were two people on different machines able to reproduce locally, let me get back to you with more info.

Thanks for response!

**Comment by jakobmygind** [comment]
@ryanwilson I am sorry, it turned out to be ghost pods in the repo, sorry for the inconvenience! Closing.

**Comment by ryanwilson** [comment]
No problem at all, I’m happy it wasn’t a real issue :) thanks for reporting.

**Comment by dishasyno** [comment]
> @ryanwilson I am sorry, it turned out to be ghost pods in the repo, sorry for the inconvenience! Closing.
@jakobmygind  can you please tell how you have got that issue resolved?
I am having the same issue in my code and we are also working two people on the same code.
