### ISSUE TITLE
BoringSSL-GRPC modulemap not found

### ISSUE THREAD

**Issue by vlazdra** [firebase/firebase-ios-sdk#3816]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.3
  * Firebase SDK version: 6.8.1
  * Firebase Component: Core, Analytics, Performance, RemoteConfig, Messaging, Auth, Firestore
  * Component version:
  - Firebase/Analytics 6.1.1
  - Firebase/Core 6.8.1
  - Firebase/Messaging 4.1.4
  - Firebase/Performance 3.1.4
  - Firebase/RemoteConfig 4.4.0
  - Firebase/Firestore 1.4.3
  - Firebase/Auth 6.2.3

### [REQUIRED] Step 3: Describe the problem
While trying to build the project the build fails every time complaining about a missing modulemap file.

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
`Module map file '/Users/me/Documents/project-ios/Pods/Headers/Private/openssl_grpc/BoringSSL-GRPC.modulemap' not found`

**Comment by paulb777** [comment]
The versions listed seem inconsistent. For example, Firebase 5.8.1 [requires FirebaseFirestore 1.5.0](https://github.com/CocoaPods/Specs/blob/master/Specs/0/3/5/Firebase/6.8.1/Firebase.podspec.json#L251). 

Please make sure `pod update` updates everything and if you're still having problems, share the `Podfile.lock`

**Comment by wilhuff** [comment]
You might also try removing your `Pods` or `~/Library/Developer/Xcode/DerivedData` folders and re-running `pod update`.

**Comment by vlazdra** [comment]
> You might also try removing your Pods or ~/Library/Developer/Xcode/DerivedData folders and re-running pod update.

Tried, to na avail. DerivedData, restart, removed pods folder, podfile.lock, different cocoapods versions. Nothing helped. @wilhuff 

> The versions listed seem inconsistent. For example, Firebase 6.8.1 requires FirebaseFirestore 1.5.0.

Sorry my bad, it was 1.5.0 from the start.

> Please make sure pod update updates everything and if you're still having problems, share the Podfile.lock

I did, I explecetly removed the versions for all Firebase pods, and always run pod update.

Here's the **Podfile.lock** contents @paulb777 
PODS:
  - Alamofire (4.8.0)
  - Apollo (0.15.1):
    - Apollo/Core (= 0.15.1)
  - Apollo/Core (0.15.1)
  - AWSCore (2.10.2)
  - AWSIoT (2.10.2):
    - AWSCore (= 2.10.2)
  - Bolts (1.9.0):
    - Bolts/AppLinks (= 1.9.0)
    - Bolts/Tasks (= 1.9.0)
  - Bolts/AppLinks (1.9.0):
    - Bolts/Tasks
  - Bolts/Tasks (1.9.0)
  - BoringSSL-GRPC (0.0.3):
    - BoringSSL-GRPC/Implementation (= 0.0.3)
    - BoringSSL-GRPC/Interface (= 0.0.3)
  - BoringSSL-GRPC/Implementation (0.0.3):
    - BoringSSL-GRPC/Interface (= 0.0.3)
  - BoringSSL-GRPC/Interface (0.0.3)
  - Branch (0.27.1):
    - Branch/Core (= 0.27.1)
  - Branch/Core (0.27.1)
  - Crashlytics (3.13.4):
    - Fabric (~> 1.10.2)
  - Fabric (1.10.2)
  - FBSDKCoreKit (4.34.0):
    - Bolts (~> 1.7)
  - FBSDKLoginKit (4.34.0):
    - FBSDKCoreKit
  - FBSDKShareKit (4.34.0):
    - FBSDKCoreKit (~> 4.34.0)
  - Firebase/Analytics (6.8.1):
    - Firebase/Core
  - Firebase/Auth (6.8.1):
    - Firebase/CoreOnly
    - FirebaseAuth (~> 6.2.3)
  - Firebase/Core (6.8.1):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.1.1)
  - Firebase/CoreOnly (6.8.1):
    - FirebaseCore (= 6.2.3)
  - Firebase/Firestore (6.8.1):
    - Firebase/CoreOnly
    - FirebaseFirestore (~> 1.5.0)
  - Firebase/Messaging (6.8.1):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 4.1.4)
  - Firebase/Performance (6.8.1):
    - Firebase/CoreOnly
    - FirebasePerformance (~> 3.1.4)
  - Firebase/RemoteConfig (6.8.1):
    - Firebase/CoreOnly
    - FirebaseRemoteConfig (~> 4.4.0)
  - FirebaseABTesting (3.1.1):
    - FirebaseAnalyticsInterop (~> 1.3)
    - FirebaseCore (~> 6.1)
    - Protobuf (~> 3.8)
  - FirebaseAnalytics (6.1.1):
    - FirebaseCore (~> 6.2)
    - FirebaseInstanceID (~> 4.2)
    - GoogleAppMeasurement (= 6.1.1)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 0.3)
  - FirebaseAnalyticsInterop (1.4.0)
  - FirebaseAuth (6.2.3):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 6.2)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.2)
    - GoogleUtilities/Environment (~> 6.2)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseAuthInterop (1.0.0)
  - FirebaseCore (6.2.3):
    - FirebaseCoreDiagnostics (~> 1.0)
    - FirebaseCoreDiagnosticsInterop (~> 1.0)
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/Logger (~> 6.2)
  - FirebaseCoreDiagnostics (1.0.1):
    - FirebaseCoreDiagnosticsInterop (~> 1.0)
    - GoogleDataTransportCCTSupport (~> 1.0)
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/Logger (~> 6.2)
  - FirebaseCoreDiagnosticsInterop (1.0.0)
  - FirebaseFirestore (1.5.0):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 6.2)
    - FirebaseFirestore/abseil-cpp (= 1.5.0)
    - "gRPC-C++ (= 0.0.9)"
    - leveldb-library (~> 1.22)
    - nanopb (~> 0.3.901)
    - Protobuf (~> 3.1)
  - FirebaseFirestore/abseil-cpp (1.5.0):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 6.2)
    - "gRPC-C++ (= 0.0.9)"
    - leveldb-library (~> 1.22)
    - nanopb (~> 0.3.901)
    - Protobuf (~> 3.1)
  - FirebaseInstanceID (4.2.5):
    - FirebaseCore (~> 6.0)
    - GoogleUtilities/Environment (~> 6.0)
    - GoogleUtilities/UserDefaults (~> 6.0)
  - FirebaseMessaging (4.1.4):
    - FirebaseAnalyticsInterop (~> 1.3)
    - FirebaseCore (~> 6.2)
    - FirebaseInstanceID (~> 4.1)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.2)
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/Reachability (~> 6.2)
    - GoogleUtilities/UserDefaults (~> 6.2)
    - Protobuf (~> 3.1)
  - FirebasePerformance (3.1.4):
    - FirebaseCore (~> 6.2)
    - FirebaseInstanceID (~> 4.2)
    - FirebaseRemoteConfig (~> 4.4)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/ISASwizzler (~> 6.2)
    - GoogleUtilities/MethodSwizzler (~> 6.2)
    - GTMSessionFetcher/Core (~> 1.1)
    - Protobuf (~> 3.9)
  - FirebaseRemoteConfig (4.4.0):
    - FirebaseABTesting (~> 3.1)
    - FirebaseAnalyticsInterop (~> 1.4)
    - FirebaseCore (~> 6.2)
    - FirebaseInstanceID (~> 4.2)
    - GoogleUtilities/Environment (~> 6.2)
    - "GoogleUtilities/NSData+zlib (~> 6.2)"
    - Protobuf (~> 3.9)
  - google-cast-sdk-no-bluetooth (4.4.4):
    - google-cast-sdk-no-bluetooth/Core (= 4.4.4)
    - Protobuf (~> 3.0)
  - google-cast-sdk-no-bluetooth/Core (4.4.4):
    - Protobuf (~> 3.0)
  - GoogleAppMeasurement (6.1.1):
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 0.3)
  - GoogleDataTransport (1.2.0)
  - GoogleDataTransportCCTSupport (1.0.3):
    - GoogleDataTransport (~> 1.2)
    - nanopb
  - GoogleToolboxForMac/Defines (2.2.1)
  - GoogleToolboxForMac/Logger (2.2.1):
    - GoogleToolboxForMac/Defines (= 2.2.1)
  - "GoogleToolboxForMac/NSData+zlib (2.2.1)":
    - GoogleToolboxForMac/Defines (= 2.2.1)
  - GoogleUtilities/AppDelegateSwizzler (6.2.5):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (6.2.5)
  - GoogleUtilities/ISASwizzler (6.2.5)
  - GoogleUtilities/Logger (6.2.5):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (6.2.5):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (6.2.5):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (6.2.5)"
  - GoogleUtilities/Reachability (6.2.5):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (6.2.5):
    - GoogleUtilities/Logger
  - "gRPC-C++ (0.0.9)":
    - "gRPC-C++/Implementation (= 0.0.9)"
    - "gRPC-C++/Interface (= 0.0.9)"
  - "gRPC-C++/Implementation (0.0.9)":
    - "gRPC-C++/Interface (= 0.0.9)"
    - gRPC-Core (= 1.21.0)
    - nanopb (~> 0.3)
  - "gRPC-C++/Interface (0.0.9)"
  - gRPC-Core (1.21.0):
    - gRPC-Core/Implementation (= 1.21.0)
    - gRPC-Core/Interface (= 1.21.0)
  - gRPC-Core/Implementation (1.21.0):
    - BoringSSL-GRPC (= 0.0.3)
    - gRPC-Core/Interface (= 1.21.0)
    - nanopb (~> 0.3)
  - gRPC-Core/Interface (1.21.0)
  - GTMSessionFetcher/Core (1.2.2)
  - Kingfisher (5.7.1)
  - Leanplum-iOS-SDK (2.5.1)
  - leveldb-library (1.22)
  - MarkdownView (1.6.0)
  - MopinionSDKWeb (0.3.1)
  - nanopb (0.3.901):
    - nanopb/decode (= 0.3.901)
    - nanopb/encode (= 0.3.901)
  - nanopb/decode (0.3.901)
  - nanopb/encode (0.3.901)
  - Protobuf (3.9.0)
  - ReachabilitySwift (4.3.1)
  - RxAlamofire (5.0.0):
    - RxAlamofire/Core (= 5.0.0)
  - RxAlamofire/Core (5.0.0):
    - Alamofire (~> 4.8)
    - RxSwift (~> 5.0)
  - RxCocoa (5.0.0):
    - RxRelay (~> 5)
    - RxSwift (~> 5)
  - RxGesture (3.0.0):
    - RxCocoa (~> 5.0)
    - RxSwift (~> 5.0)
  - RxRelay (5.0.0):
    - RxSwift (~> 5)
  - RxSwift (5.0.0)
  - SnapKit (5.0.1)
  - SwiftLint (0.34.0)
  - SwiftyBeaver (1.7.0)
  - Swinject (2.6.2)
  - TealiumIOS (5.5.5)
  - TealiumIOSLifecycle (5.5.0)

DEPENDENCIES:
  - Alamofire (= 4.8.0)
  - Apollo (= 0.15.1)
  - AWSIoT (= 2.10.2)
  - Branch (= 0.27.1)
  - Crashlytics (= 3.13.4)
  - Fabric (= 1.10.2)
  - FBSDKCoreKit (= 4.34.0)
  - FBSDKLoginKit (= 4.34.0)
  - FBSDKShareKit (= 4.34.0)
  - Firebase/Analytics
  - Firebase/Auth
  - Firebase/Core
  - Firebase/Firestore
  - Firebase/Messaging
  - Firebase/Performance
  - Firebase/RemoteConfig
  - google-cast-sdk-no-bluetooth (~> 4.4)
  - Kingfisher (= 5.7.1)
  - Leanplum-iOS-SDK (= 2.5.1)
  - MarkdownView (= 1.6.0)
  - MopinionSDKWeb (= 0.3.1)
  - ReachabilitySwift (= 4.3.1)
  - RxAlamofire (= 5.0.0)
  - RxCocoa (= 5.0.0)
  - RxGesture (= 3.0.0)
  - RxSwift (= 5.0.0)
  - SnapKit (= 5.0.1)
  - SwiftLint (= 0.34.0)
  - SwiftyBeaver (= 1.7.0)
  - Swinject (= 2.6.2)
  - TealiumIOS (= 5.5.5)
  - TealiumIOSLifecycle (= 5.5.0)

SPEC REPOS:
  trunk:
    - Alamofire
    - Apollo
    - AWSCore
    - AWSIoT
    - Bolts
    - BoringSSL-GRPC
    - Branch
    - Crashlytics
    - Fabric
    - FBSDKCoreKit
    - FBSDKLoginKit
    - FBSDKShareKit
    - Firebase
    - FirebaseABTesting
    - FirebaseAnalytics
    - FirebaseAnalyticsInterop
    - FirebaseAuth
    - FirebaseAuthInterop
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseCoreDiagnosticsInterop
    - FirebaseFirestore
    - FirebaseInstanceID
    - FirebaseMessaging
    - FirebasePerformance
    - FirebaseRemoteConfig
    - google-cast-sdk-no-bluetooth
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleDataTransportCCTSupport
    - GoogleToolboxForMac
    - GoogleUtilities
    - "gRPC-C++"
    - gRPC-Core
    - GTMSessionFetcher
    - Kingfisher
    - Leanplum-iOS-SDK
    - leveldb-library
    - MarkdownView
    - MopinionSDKWeb
    - nanopb
    - Protobuf
    - ReachabilitySwift
    - RxAlamofire
    - RxCocoa
    - RxGesture
    - RxRelay
    - RxSwift
    - SnapKit
    - SwiftLint
    - SwiftyBeaver
    - Swinject
    - TealiumIOS
    - TealiumIOSLifecycle

SPEC CHECKSUMS:
  Alamofire: 3ec537f71edc9804815215393ae2b1a8ea33a844
  Apollo: faad3e64ac3f12642757329146318e8439c8f8e5
  AWSCore: 2e91f89187d1238be35ce8c57aac98c42def640f
  AWSIoT: 3d0c23fec589a57b32c46c8fd8ad087405366264
  Bolts: ac6567323eac61e203f6a9763667d0f711be34c8
  BoringSSL-GRPC: db8764df3204ccea016e1c8dd15d9a9ad63ff318
  Branch: 1ace77c04b6e3efbf982bf4364f0662bfac156a0
  Crashlytics: 2dfd686bcb918dc10ee0e76f7f853fe42c7bd552
  Fabric: 706c8b8098fff96c33c0db69cbf81f9c551d0d74
  FBSDKCoreKit: 0ff57f093b85c8c9d5aba697d3edf68a8960ce78
  FBSDKLoginKit: 8c78f57a145afb756e4755e69195ebe08a42466e
  FBSDKShareKit: 511d1dfc71204c0a8d69e6c5e3c964dcf0d4f3d9
  Firebase: 9cbe4e5b5eaafa05dc932be58b7c8c3820d71e88
  FirebaseABTesting: 662e8de812ceb5d57ad66381f6402f4d28dc5c91
  FirebaseAnalytics: 843c7f64a8f9c79f0d03281197ebe7bb1d58d477
  FirebaseAnalyticsInterop: d48b6ab67bcf016a05e55b71fc39c61c0cb6b7f3
  FirebaseAuth: e7f86c2dfc57281cd01f7da5e4b40e01e4510a4a
  FirebaseAuthInterop: 0ffa57668be100582bb7643d4fcb7615496c41fc
  FirebaseCore: e9d9bd1dae61c1e82bc1e0e617a9d832392086a0
  FirebaseCoreDiagnostics: 4c04ae09d0ab027c30179828c6bb47764df1bd13
  FirebaseCoreDiagnosticsInterop: 6829da2b8d1fc795ff1bd99df751d3788035d2cb
  FirebaseFirestore: c5873e279490fbe02239ab2cdfb91c2d546261cc
  FirebaseInstanceID: 550df9be1f99f751d8fcde3ac342a1e21a0e6c42
  FirebaseMessaging: 9483ac438b7b223c09dad8712310e9ee7d562c99
  FirebasePerformance: a28490ad3b116380ff2d8300a67051626d01d09e
  FirebaseRemoteConfig: a1b49ebfddeaccda10d76fd8dc2cc1aa215f9c43
  google-cast-sdk-no-bluetooth: e0af19280673fba052f7fc3ddde6116c733ce505
  GoogleAppMeasurement: 86a82f0e1f20b8eedf8e20326530138fd71409de
  GoogleDataTransport: 8f9897b8e073687f24ca8d3c3a8013dec7d2d1cc
  GoogleDataTransportCCTSupport: 51134d81fca795c60cc247d1cb6af63c3d67b8d8
  GoogleToolboxForMac: b3553629623a3b1bff17f555e736cd5a6d95ad55
  GoogleUtilities: e7dc37039b19df7fe543479d3e4a02ac8d11bb69
  "gRPC-C++": 9dfe7b44821e7b3e44aacad2af29d2c21f7cde83
  gRPC-Core: c9aef9a261a1247e881b18059b84d597293c9947
  GTMSessionFetcher: 61bb0f61a4cb560030f1222021178008a5727a23
  Kingfisher: 176d377ad339113c99ad4980cbae687f807e20fe
  Leanplum-iOS-SDK: 4ab495e9f5199457a4d742e1d52751f0bfe6a17f
  leveldb-library: 55d93ee664b4007aac644a782d11da33fba316f7
  MarkdownView: 25c1c2d7ff9706624a575556296e188be3dd3f6b
  MopinionSDKWeb: e4594d3e01bc213ecf90f20d6ab9a4926df606f4
  nanopb: 2901f78ea1b7b4015c860c2fdd1ea2fee1a18d48
  Protobuf: 1097ca58584c8d9be81bfbf2c5ff5975648dd87a
  ReachabilitySwift: 4032e2f59586e11e3b0ebe15b167abdd587a388b
  RxAlamofire: e7875a012aff55345672d0f70a2a9cd6aeb0f211
  RxCocoa: fcf32050ac00d801f34a7f71d5e8e7f23026dcd8
  RxGesture: 0cd8e37ff9a266e1c31f46bcaed6de1c536bc81e
  RxRelay: 4f7409406a51a55cd88483f21ed898c234d60f18
  RxSwift: 8b0671caa829a763bbce7271095859121cbd895f
  SnapKit: 97b92857e3df3a0c71833cce143274bf6ef8e5eb
  SwiftLint: 79d48a17c6565dc286c37efb8322c7b450f95c67
  SwiftyBeaver: 4cc0080d2e23f980652e28978db11a5c9da39165
  Swinject: cf7458774b1b00323080a9c67e47a1ee7f9d2af1
  TealiumIOS: 1a47e040db22ddc6df14ab73c777c98e5877662d
  TealiumIOSLifecycle: fad624b46544a3a09cd8fa6c76142759dd0f5cc4

PODFILE CHECKSUM: 686ead75bc80c8702f5ceef3144f2774dca61710

COCOAPODS: 1.8.0.beta.2

**Comment by paulb777** [comment]
I don't know what is happening, but here are two ideas to explore?

Does adding or removing `use_frameworks!` to the Podfile make a difference?

What does `find . | grep BoringSSL-GRPC | grep modulemap` show?  Is there an architecture specific one like `./Pods/Target Support Files/BoringSSL-GRPC-iOS/BoringSSL-GRPC-iOS.modulemap`?

**Comment by vlazdra** [comment]
I did indeed tried to set the `use_frameworks!` flag, but then other stuff started to fall apart other than Firebase related libs.

And the find command printed this:
./Pods/Target Support Files/BoringSSL-GRPC/BoringSSL-GRPC.modulemap
./Pods/BoringSSL-GRPC/include/openssl/BoringSSL.modulemap

If it helps, here's the module-map=file setup in the project when install via CocoaPods:
-fmodule-map-file="${PODS_ROOT}/Headers/Private/grpc/gRPC-Core.modulemap"
-fmodule-map-file="${PODS_ROOT}/Headers/Private/openssl_grpc/BoringSSL-GRPC.modulemap"
-fmodule-map-file="${PODS_ROOT}/Headers/Public/grpcpp/gRPC-C++.modulemap"

-isystem
"${PODS_ROOT}/Headers/Public/BoringSSL-GRPC"
-isystem
"${PODS_ROOT}/Headers/Public/gRPC-C++"
-isystem
"${PODS_ROOT}/Headers/Public/gRPC-Core"

Also if it's worth noting I did try with the previous stable version of CocoaPods as well, nothing changed the issue was still present, so don't think anything happened between the 1.7.4 and 1.8.0.beta.2 versions.

**Comment by momamene** [comment]
The problem also happens to me.

In my case, copcoapods 1.6.1 can build my project successfully with using `use_modular_headers!` without `use_frameworks!` in Podfile.
but It should be required to add `use_frameworks!` when I use cocoapods 1.7 or above versions.

**Comment by paulb777** [comment]
It looks like CocoaPods [does not currently support custom module maps for static libraries](https://github.com/CocoaPods/CocoaPods/issues/9266#issuecomment-542880242).  If the project is Objective C, no `use_frameworks!` would be an option. Otherwise it looks like `use_frameworks!` is required for Swift apps to use Firestore because of the BoringSSL dependency.

**Comment by paulb777** [comment]
Closing since this requires a new CocoaPods feature. Please follow up in the CocoaPods community.  It should get better with CocoaPods 1.9.0 which is adding the capability to specify dynamic/static linkage for each pod in the Podfile.

**Comment by paulb777** [comment]
Use `use_frameworks! :linkage => :static` instead of `use_modular_headers!`
