### ISSUE TITLE
Remote Config: fetchAndActivateWithCompletionHandler fails to call Completion Handler

### ISSUE THREAD

**Issue by ehlersd** [firebase/firebase-ios-sdk#3818]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: Version 10.2.1 (10E1001)
  * Firebase SDK version: 6.8.1
  * Firebase Component: Remote Config (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 4.4.0

### [REQUIRED] Step 3: Describe the problem

When calling [FIRRemoteConfig.remoteConfig fetchAndActivateWithCompletionHandler:] in my AppDelegate, the completion handler is never called. 

#### Steps to reproduce:

 I debugged it thru the source code and tracked it down to the -fetchWithUserPropertiesCompletionHandler: method in RCNFetch.m file (Line 227).  In that method, the call to the Analytics engine getUserPropertiesWithCallback: method never calls the completionHandler, which in turns causes all of the completion handlers upstream to never be called.

#### Relevant Code:

```
    [FIRRemoteConfig.remoteConfig fetchAndActivateWithCompletionHandler:
     ^(FIRRemoteConfigFetchAndActivateStatus status, NSError* _Nullable error)
    {
        // This is never called
    }];
```
RCNFetch.m (Line 227):
```
    [analytics getUserPropertiesWithCallback:completionHandler];
```

**Comment by ehlersd** [comment]
Oh, absolutely FirebaseAnalytics is installed.  The actual code in the RCNFetch.m is:

```
  id<FIRAnalyticsInterop> analytics = self->_analytics;
  if (analytics == nil) {
    completionHandler(@{});
  } else {
    [analytics getUserPropertiesWithCallback:completionHandler];
  }
```

So, if FirebaseAnalytics was NOT installed, it would bypass the call and directly call the completionHandler.

**Comment by paulb777** [comment]
Agreed. Thanks. Any clues in the console logs?

**Comment by ehlersd** [comment]
Nothing that I can find....but to get anything from Firebase in the logs, I had to go back and enable "OS_ACTIVITY_MODE", which adds a lot of OS trash in there...

**Comment by ehlersd** [comment]
After more digging, it appears there was an error about [FIRApp configure]; not being called....of course, it was called.  So I dug more, and found the errors about duplicates caused by using dynamic frameworks.  I'm currently working under the assumption that this is the cause of my problem, and will update when I can confirm.

**Comment by paulb777** [comment]
Definitely could be related to using dynamic frameworks.

**Comment by ehlersd** [comment]
Okay, changing my dynamic frameworks to static resolve the duplicate errors in the logs and the completionHandler is now being called without issue.  Consider this issue closed.
