### ISSUE TITLE
Usage of "FIRActionCodeSettings"

### ISSUE THREAD

**Issue by hansemannn** [firebase/firebase-ios-sdk#382]
* Xcode version: 9.0
  * Firebase SDK version: 4.3.0
  * Firebase Component: Auth
  * Component version: 4.2.1

#### Steps to reproduce:

Try to use the `sendPasswordResetWithEmail:actionCodeSettings:completion` API.

#### Question

Where do I get an instance of the `FIRActionCodeSettings` for the `actionCodeSettings` parameter? I cannot find anything that returns one in the public API. I noticed [this docs](https://firebase.google.com/docs/auth/ios/passing-state-in-email-actions), but important properties like `iOSBundleID` and `androidPackageName` are read-only (which would make sense if it's returned based on the app-bundle, but then the other platform (in this case Android) would not make sense. Thanks!

**Comment by protocol86** [comment]
Hi  @hansemannn,

You can create an instance of FIRActionCodeSettings yourself using the default initializer and use the properties and methods exposed on the class to configure that instance.

For example:
`FIRActionCodeSettings *actionCodeSettings = [[FIRActionCodeSettings alloc] init];
  actionCodeSettings.URL = _actionCodeURL;
 actionCodeSettings.handleCodeInApp = YES;
 [actionCodeSettings setIOSBundleID:[NSBundle mainBundle].bundleIdentifier];
`
For a more elaborate example (and a swift version) please take a look at the example code under the **Passing state/continue URL in email actions** section of the documentation.

-Z

**Comment by protocol86** [comment]
Closing this issue, if the issue persists please feel free to re-open it.

**Comment by hansemannn** [comment]
Looks great, thank you!
