### ISSUE TITLE
Using app_spec's requires CocoaPods 1.7.x

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#3824]
Using the CocoaPods app_spec feature requires CocoaPods 1.7.x. 

We probably shouldn't change the CocoaPods version requirement until at least a major release update.

Perhaps, we need to parameterize the podspec for development versus release?

See the cron build failure at https://travis-ci.org/firebase/firebase-ios-sdk/jobs/583489654

**Comment by mikehaney24** [comment]
What's a "a major release update"?

**Comment by paulb777** [comment]
Firebase 7.0.0

**Comment by mikehaney24** [comment]
Oh ok, a Firebase major release update, not a Cocoapods one. Got it. We'll have to figure out a mechanism to help define development environments. For now, I can comment out the app_spec from GDT.
