### ISSUE TITLE
FirebaseCoreDiagnostic Compile Errors 

### ISSUE THREAD

**Issue by halinebr** [firebase/firebase-ios-sdk#3830]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.3
  * Firebase SDK version: 6.8.1
  * Firebase Component: FirebaseCoreDiagnostics (?)
  * Component version: 1.0.1 ?

### [REQUIRED] Step 3: Describe the problem

When I go to archive my project (using Legacy build system because of [this issue](https://stackoverflow.com/questions/50718018/xcode-10-error-multiple-commands-produce) that still looks unresolved) - I get the following compile error:
<img width="650" alt="Screen Shot 2019-09-11 at 4 48 59 PM" src="https://user-images.githubusercontent.com/11284259/64734149-14391d80-d4b4-11e9-908d-91f9d7b2d10c.png">

<img width="474" alt="Screen Shot 2019-09-11 at 4 49 30 PM" src="https://user-images.githubusercontent.com/11284259/64734185-261ac080-d4b4-11e9-92f7-d0b45d4cd9ff.png">

#### Steps to reproduce:

See above.

**Comment by paulb777** [comment]
Looks similar to #2166 (except new build system). 

It could also be related to corrupt DerivedData when switching between build systems. Try `rm -rf ~/Library/Developer/Xcode/DerivedData/`

Otherwise the workarounds at https://github.com/CocoaPods/CocoaPods/issues/8206 might be helpful.

If you're still stuck, please share the `Podfile` and `Podfile.lock` and we can take a deeper look.
