### ISSUE TITLE
Crash in FIRInstanceIDCheckinService.m on iOS 13 when app is a new install

### ISSUE THREAD

**Issue by kevinchau** [firebase/firebase-ios-sdk#3842]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11 GM
  * Firebase SDK version: 6.8.1

> Installing Firebase (6.8.1)
> Installing FirebaseABTesting (3.1.1)
> Installing FirebaseAnalytics (6.1.1)
> Installing FirebaseAnalyticsInterop (1.4.0)
> Installing FirebaseCore (6.2.3)
> Installing FirebaseCoreDiagnostics (1.0.1)
> Installing FirebaseCoreDiagnosticsInterop (1.0.0)
> Installing FirebaseInstanceID (4.2.5)
> Installing FirebaseMessaging (4.1.4)
> Installing FirebaseRemoteConfig (4.4.0)
> Installing Google-Mobile-Ads-SDK (7.49.0)
> Installing GoogleAppMeasurement (6.1.1)
> Installing GoogleDataTransport (1.2.0)
> Installing GoogleDataTransportCCTSupport (1.0.4)
> Installing GoogleMobileAdsMediationFacebook (5.5.0.0)
> Installing GoogleUtilities (6.2.5)

### [REQUIRED] Step 3: Describe the problem

Crashes on Launch

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/4261683/64829966-54b39c80-d583-11e9-8629-d00452211b69.png">

<img width="582" alt="image" src="https://user-images.githubusercontent.com/4261683/64829970-5bdaaa80-d583-11e9-8c8e-11970205e8f4.png">

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by kevinchau** [comment]
Just a note, I'm able build and run using the iOS 12 SDK on Xcode 10.3. It works fine there.

**Comment by chliangGoogle** [comment]
@kevinchau Is it only happening on real devices? I can't reproduce on simulators.

**Comment by kevinchau** [comment]
@chliangGoogle both. It's only happening on new installs though.

**Comment by chliangGoogle** [comment]
@morganchen12  FCM with InstanceID works without crash, unlikely a regression. Seems like a complication with the new remote config and perf, I will do more testing on that.

**Comment by chliangGoogle** [comment]
I'm not able to reproduce yet, can you share with me your sample code? especially the way you call remote config during app start?

**Comment by chliangGoogle** [comment]
I'm not sure this is a InstanceID issue, from the stack trace, looks like issues are happening inside remote config thread, although @kevinchau manually highlighted the IID thread.

I only see errors occur inside RC call here:
* thread #4, queue = 'com.google.GoogleConfigService.FIRRemoteConfig', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

**Comment by kevinchau** [comment]
@chliangGoogle I can send you some code samples, I'd prefer not posting it to the public.

**Comment by chliangGoogle** [comment]
SG, feel free to DM me.

**Comment by dmandar** [comment]
@kevinchau is it possible to repro without the Perf SDK?

**Comment by kevinchau** [comment]
@chliangGoogle looks like Github doesn't have  DM feature anymore, have an email?

**Comment by kevinchau** [comment]
I can't repro it anymore - I was having a build issue with Xcode 11 and had to Pod deintegrate and reinstall. It appears to have went away.

Thanks for the help, and sorry it was not an bug on your end.

**Comment by paulb777** [comment]
Glad it's gone.

Might have been a variation of #3344 if you had old pods before deintegrating.
