### ISSUE TITLE
Protobuf Xcode upload error

### ISSUE THREAD

**Issue by balutaeugen** [firebase/firebase-ios-sdk#3855]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

I think so

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.3
  * Firebase SDK version: 6.8.1
  * Firebase Component: Core, RemoteConfig, Performance
  * Component version: 
Firebase/Core - 6.2.3
Firebase/RemoteConfig - 4.4.0
Firebase/Performance - 3.1.4

#### Steps to reproduce:

Tried to upload my app to the App Store Connect
Expected to upload successfully, instead, Xcode gave me this error
![image](https://user-images.githubusercontent.com/30663151/64920597-5cad4f80-d7c2-11e9-839f-23dbdf018117.png)

#### Relevant Code:

It's not really the code

**Comment by morganchen12** [comment]
We've seen this issue exactly once before with a different framework and were not able to arrive at a good solution then. Can you try contacting Apple support?

**Comment by paulb777** [comment]
Removing `use_frameworks!` from the Podfile (or replacing with `use_modular_headers!`) to link Protobuf at build time might be a workaround.

**Comment by balutaeugen** [comment]
> Removing `use_frameworks!` from the Podfile (or replacing with `use_modular_headers!`) to link Protobuf at build time might be a workaround.

As a workaround this works perfectly, thank you a lot :3
