### ISSUE TITLE
Firebase unlink EmailAuthProvider Identifier issue

### ISSUE THREAD

**Issue by AnhToof** [firebase/firebase-ios-sdk#3858]
### [READ] Step 1: Are you in the right place?
- The issue that I think it related https://github.com/firebase/firebase-ios-sdk/issues/300

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.3
  * Firebase SDK version: 5.2.0
  * Firebase Component: Auth
  * Component version: _____

### [REQUIRED] Step 3: Describe the problem
I sign in by phone number then link with email and password by use EmailAuthProvider and
user.link(with: credential, completion: { (user, error) in }
and it works successfully and the identifier in my backend authentication section changes to the newly set account email. That is fine, but whenever I unlink the account using

user.unlink(fromProvider: provider) { (user, error) in }
The email that linked still exists in identifier. So, in case I logged out then I want to login with that email to receive the error is email not exists or somethings (to check email is in the system) but not email already exists.
#### Steps to reproduce:
+849000000001 (phone number) -- identifier = "+849000000001"
Now I linked abc@gmail.com (Email and passwird) -- identifier = "abc@gmail.com" and "+849000000001"
But when I unlink the email, the identifier should now be "+849000000001"
Here is the issue the identifier doesn't remove "abc@gmail.com" as it should. It remains "+849000000001" even though email is unlinked.
On android every thing works perfectly and identifier is removed. The issue is only in iOS.
#### Relevant Code:

```
user.link(with: credential, completion: { (user, error) in }
user.unlink(fromProvider: provider) { (user, error) in }
```

**Comment by morganchen12** [comment]
@AnhToof can you try upgrading to Firebase 6+ and seeing if the issue is still reproducible?

**Comment by renkelvin** [comment]
@AnhToof Unlink will only remove the email provider from the user (user is no longer able to sign in with email password again) but keep the email address as an identifier. You use `updateEmail:` to set the email to nil.

**Comment by AnhToof** [comment]
> @AnhToof Unlink will only remove the email provider from the user (user is no longer able to sign in with email password again) but keep the email address as an identifier. You use `updateEmail:` to set the email to nil.

Thanks
