### ISSUE TITLE
Is it possible to mimic the firebase links preview page behavior, without it?

### ISSUE THREAD

**Issue by liorJuice** [firebase/firebase-ios-sdk#3860]
as we approach developing deep linking into our apps a question about the firebase dynamic links preview page came up.

if we want to use a link to the native apps inside our website, do we still have to use the preview page to get the most reliable user identification results on ios? can't we just mimic it's behavior in our js code?

copying the link to the clipboard is rather simple. is that the only thing it does? i didnt find any documentation about it and it seems rather odd we don't have a way to build our own preview page or building it's functionality into our existing web pages. is there a greater cause for this?

thanks.

**Comment by dmandar** [comment]
Hi..currently this is not supported. You can though add more content to your app preview page. https://firebase.google.com/docs/dynamic-links/link-previews
