### ISSUE TITLE
UIWebView components still present in Firebase SDK

### ISSUE THREAD

**Issue by RobBernardini** [firebase/firebase-ios-sdk#3862]
This PR is related to the use of UIWebView in the Firebase SDK. 

  * Xcode version: Xcode 10.3
  * Firebase SDK version: 6.8.1
  * Firebase Components: Analytics, AdMob.
  * Components versions: 
    * FirebaseAnalytics: 6.1.1
    * FirebaseCore: 6.2.3
    * Google-Mobile-Ads-SDK: 7.49.0
    * GoogleAppMeasurement: 6.1.1
    * GoogleUtilities: 6.2.5
    * nanopb: 0.3.901

The latest two releases are meant to have removed UIWebView and UIWebViewDelegate usage from the Firebase SDK but after having updated each component to the latest versions, building the app and searching for any UIWebView reference using `nm "our_app_name" | grep UIWebView` the following output was produced:
<img width="525" alt="Screen Shot 2019-09-16 at 10 23 01 pm" src="https://user-images.githubusercontent.com/10274232/64959665-f7964e80-d8d4-11e9-9252-eb0bf2906e82.png">

It seems that there is still usage of UIWebView in one or some of the Firebase SDK components. I am thinking that this is specifically related to the Google Mobile Ads component although I am not 100% sure.

**Comment by paulb777** [comment]
Yes, the symbols still exist in the latest Google Mobile Ads. Internally tracked at b/140559063.  

Recent releases have fixed FirebaseDynamicLinks and Crashlytics. FirebaseML is also still outstanding.

**Comment by RobBernardini** [comment]
Do any of the other components that I have listed above still make reference to UIWebView and UIWebViewDelegate other than Google Mobile Ads?

**Comment by paulb777** [comment]
Of the listed pods, only Google-Mobile-Ads-SDK.

**Comment by dydyistc** [comment]
I only need Crashlytics in my project. How can I avoid components related to UIWebView?

**Comment by RobBernardini** [comment]
The latest version of Crashlytics does not use UIWebView. I installed it and Fabric last week and the UIWebView references have already been removed.

**Comment by RobBernardini** [comment]
@paulb777 , I was wondering if the latest Firebase released yesterday has also resolved this issue as it has with Firebase ML.
Thanks for your time.

**Comment by paulb777** [comment]
@RobBernardini Yes. The issue should be resolved in Firebase 5.10.0 for everything except Google Mobile Ads.

**Comment by RobBernardini** [comment]
Actually Google Mobile Ads is specifically what I need solved. Hopefully it will be fixed by next release.

**Comment by andreimateiro** [comment]
found a reference also in PersonalizedAdConsent

**Comment by cegonzal1991** [comment]
Also I have the problem with PersonalizedAdConsent

**Comment by vmalyi** [comment]
@paulb777, I think this issue needs broader attention because starting from today Apple marks the presence of UIWebView in the binary as an issue when uploading to TestFlight:

> TMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

I was able to find its traces in:
- FIRAuthWebView.m
- FIRAuthWebViewController.m

Thanks!

**Comment by paulb777** [comment]
@vmalyi The FirebaseAuth UIWebView API references were [removed in August](https://github.com/firebase/firebase-ios-sdk/commit/f8414971288a6b6cc463ef6089482c989bb9b9ef#diff-1e041fc44a93526ef08576f1bc1a975d).  Please make sure you've updated to a more recent version.

**Comment by andreimateiro** [comment]
@paulb777 , I have the same issue for a while. I use the pod:

` pod 'PersonalizedAdConsent'`

without any version

and the podfile.lock reports PersonalizedAdConsent (1.0.3) (same as in https://cocoapods.org/pods/PersonalizedAdConsent)

**Comment by paulb777** [comment]
@andreimateiro Yep, the Ads' Pods still have the problem - although `'PersonalizedAdConsent'` is outside the scope of what we track here in Firebase.

**Comment by RobBernardini** [comment]
@paulb777 what is the progress of removing the UIWebView components from Google Mobile Ads? The removal from other SDKs in Firebase seemed quite rapid, taking only a few weeks after Apple's announcement, but it's already 2 months since I raised this issue (3 months after Apple's announcement) and it is still open.

**Comment by paulb777** [comment]
@RobBernardini The transition is more complicated for Ads because of WKWebView bugs that impact functionality on older iOS versions.  The team is working to have a solution before Apple actually starts rejections.

**Comment by RobBernardini** [comment]
@paulb777 I appreciate the update. 
I wish the team good luck and look forward to seeing the final result.

**Comment by irfankaya1988** [comment]
@paulb777 Hey Paul, I have the same problem with Google Mobile Ads, any good news?

**Comment by paulb777** [comment]
@irfankaya1988 Still in progress.

**Comment by paulb777** [comment]
From https://developer.apple.com/news/?id=12232019b:

`The App Store will no longer accept new apps using UIWebView as of April 2020 and app updates using UIWebView as of December 2020.`

**Comment by RobBernardini** [comment]
@paulb777 Thanks for the sharing this news.
You are confident that this ticket will be resolved and closed before April 2020?

**Comment by paulb777** [comment]
@RobBernardini By policy, we don't talk about future plans, but I can say that it is a high priority to make it so.

**Comment by RobBernardini** [comment]
@paulb777 Understood and thank you.

**Comment by rizafran** [comment]
Hi @RobBernardini, UIWebView has been removed on Google Mobile Ads. You may refer on the release notes [here](https://developers.google.com/admob/ios/rel-notes).

**Comment by RobBernardini** [comment]
@paulb777, @rizafran, thank you for all the hard work getting this out the door. We appreciate it!

**Comment by RobBernardini** [comment]
@paulb777 @rizafran . I finally updated to using the new Google Mobile Ads framework, as well as other Firebase frameworks, and I ran grep to verify that there are no more references to UIWebView in my app but this is what was discovered.

<img width="486" alt="Screen Shot 2020-03-10 at 9 32 18 am" src="https://user-images.githubusercontent.com/10274232/76263163-4b955500-62b2-11ea-82d6-7eb035d8df2b.png">

This is similar to the output discovered last year. I would like to verify that all references to UIWebView have definitely been removed from Mobile Ads. The reference may be due to another framework.

**Comment by morganchen12** [comment]
What version of GoogleMobileAds are you running?

**Comment by RobBernardini** [comment]
Hi @morganchen12 , I am running version 7.55.1, this is the latest version bundled into Firebase 6.18.0.

**Comment by morganchen12** [comment]
Interesting. Looks like the references were removed from GoogleMobileAds' codebase internally at the end of January, and I wasn't able to find any references to UIWebView in the current codebase. Can you try again with GoogleMobileAds 7.56.0? It's possible the UIWebView removal slipped past the code freeze for 7.55.1, but if UIWebView is still present in the latest version then there's likely something strange going on with the release process.

**Comment by RobBernardini** [comment]
I just updated to 7.56.0, ran it on a device and called grep on the app. Here is the whole output:

<img width="481" alt="Screen Shot 2020-03-10 at 11 52 29 am" src="https://user-images.githubusercontent.com/10274232/76269454-da5f9d00-62c5-11ea-93a5-9d9f8794ef2d.png">

The other SCORVCE reference is another framework called `ComScore` but I am wondering if the UIWebView specific reference is with GADOMIDUIWebViewJSExecutor in the Mobile Ads framework. Seems to me like it could be.

**Comment by paulb777** [comment]
I don't see it in the admob quickstart:

```
~/qs/200305/quickstart-ios/admob (master) $ pod install
Analyzing dependencies
Downloading dependencies
Installing Firebase (6.18.0)
Installing FirebaseAnalytics (6.3.0)
Installing FirebaseCore (6.6.3)
Installing FirebaseCoreDiagnostics (1.2.1)
Installing FirebaseCoreDiagnosticsInterop (1.2.0)
Installing FirebaseInstallations (1.1.0)
Installing Google-Mobile-Ads-SDK (7.56.0)
Installing GoogleAppMeasurement (6.3.0)
Installing GoogleDataTransport (4.0.1)
Installing GoogleDataTransportCCTSupport (1.4.1)
Installing GoogleUtilities (6.5.1)
Installing PromisesObjC (1.2.8)
Installing nanopb (0.3.9011)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `AdMobExample.xcworkspace` for this project from now on.
Pod installation complete! There are 2 dependencies from the Podfile and 13 total pods installed.
~/qs/200305/quickstart-ios/admob (master) $ nm Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.framework/GoogleMobileAds | grep UIWebVi
                 U _OBJC_CLASS_$_GADOMIDUIWebViewJSExecutor
Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.framework/GoogleMobileAds(GADOMIDUIWebViewJSExecutor_756cbedfcadc00b64a868c185cab1ab0.o):
---------------- t -[GADOMIDUIWebViewJSExecutor .cxx_destruct]
---------------- t -[GADOMIDUIWebViewJSExecutor initWithWebView:]
---------------- t -[GADOMIDUIWebViewJSExecutor injectJavaScriptFromString:]
---------------- t -[GADOMIDUIWebViewJSExecutor jsEnvironment]
---------------- t -[GADOMIDUIWebViewJSExecutor supportBackgroundThread]
---------------- D _OBJC_CLASS_$_GADOMIDUIWebViewJSExecutor
---------------- D _OBJC_IVAR_$_GADOMIDUIWebViewJSExecutor._webView
---------------- D _OBJC_METACLASS_$_GADOMIDUIWebViewJSExecutor
```

**Comment by morganchen12** [comment]
`GADOMIDUIWebViewJSExecutor` doesn't actually reference UIWebView anymore, it's just a holdover name from when it used to. Can you try checking a project without comScore?

**Comment by RobBernardini** [comment]
@morganchen12 
I apologise for taking a while to reply. So I removed `ComScore`, built the app and ran grep and the following output is obtained:
<img width="482" alt="Screen Shot 2020-03-23 at 8 54 03 pm" src="https://user-images.githubusercontent.com/10274232/77304490-a1eda380-6d48-11ea-9e0c-bcd6b50b9474.png">

There is still this reference being shown to UIWebView. If Mobile Ads no longer has any reference do we know why this could be appearing? It seems sandwiched between the `GADOMIDUIWebViewJSExecutor`. Could it be due to something else?

@irfankaya1988, have you installed the new version of GMA? Are you still finding a reference to UIWebView or is everything clear?

**Comment by paulb777** [comment]
@RobBernardini Can you be more specific about which library the reference is coming from?  See the commands used in https://github.com/firebase/firebase-ios-sdk/issues/3862#issuecomment-596850809

**Comment by RobBernardini** [comment]
@paulb777 
I ran the command as you did and got the same output without any reference to UIWebView in the SDK. As shown below:
<img width="968" alt="Screen Shot 2020-03-24 at 9 41 10 pm" src="https://user-images.githubusercontent.com/10274232/77416978-ca44d300-6e18-11ea-926b-63a5368a12e8.png">

The command I originally ran was on the application file (`.app`) found in the `/Library/Developer/Xcode/DerivedData/**app_name-xxxxxxx**/Build/Products/Debug-iphoneos/**app_name**.app`
This is where I generated the output with the reference to the UIWebView. I am not sure why it is doing this and why it relates it to the Google Mobile Ads SDK if there is no reference to UIWebView in the SDK. Could Google Mobile Ads be referencing a library that injects UIWebView into the built app file?

**Comment by paulb777** [comment]
That seems to indicate that the undefined UIWebView symbol is coming from another archive than the one from the Google-Mobile-Ads-SDK.

Are you able to isolate the pod from which the undefined UIWebView symbol is being linked from into the app?

**Comment by RobBernardini** [comment]
No. I thought it was coming from Google Mobile Ads or a dependency because of how it is listed when calling grep. We know that the ComScore SDK also has UIWebView references but I isolated that SDK and the report just above still showed a reference to UIWebView. We have suspicions that it could also be due to RxSwift but are unsure. We will be investigating this. I've run a few tests in a new project and can't seem to find a reference to any UIWebView when including the Google Mobile Ads SDK but I have not been able to thoroughly test this or replicate to full extent how it works in our app. 

I guess for now we can close this ticket unless other Mobile Ads users have found references to UIWebView in their builds. Hopefully the reference we are finding in our app build is due to another SDK.

Thanks to everyone for all your help in relation to this issue.

**Comment by morganchen12** [comment]
No problem. I'll close this issue now, but if it regresses please comment here and I'll reopen the issue.

**Comment by bengottlieb** [comment]
I just downloaded v7.57.0, and ran nm on it. I see the following: 

```
nm GoogleMobileAdsSdkiOS-7.57-2.0/GoogleMobileAds.framework/GoogleMobileAds | grep -i UIWebView
                 U _OBJC_CLASS_$_GADOMIDUIWebViewJSExecutor
GoogleMobileAdsSdkiOS-7.57.0/GoogleMobileAds.framework/GoogleMobileAds(GADOMIDUIWebViewJSExecutor_756cbedfcadc00b64a868c185cab1ab0.o):
---------------- t -[GADOMIDUIWebViewJSExecutor .cxx_destruct]
---------------- t -[GADOMIDUIWebViewJSExecutor initWithWebView:]
---------------- t -[GADOMIDUIWebViewJSExecutor injectJavaScriptFromString:]
---------------- t -[GADOMIDUIWebViewJSExecutor jsEnvironment]
---------------- t -[GADOMIDUIWebViewJSExecutor supportBackgroundThread]
---------------- D _OBJC_CLASS_$_GADOMIDUIWebViewJSExecutor
---------------- D _OBJC_IVAR_$_GADOMIDUIWebViewJSExecutor._webView
---------------- D _OBJC_METACLASS_$_GADOMIDUIWebViewJSExecutor
```

**Comment by morganchen12** [comment]
`GADOMIDUIWebViewJSExecutor` doesn't reference UIWebView anymore, even though it has UIWebView in its name. You can ignore those symbols.

**Comment by bengottlieb** [comment]
@morganchen12 I can ignore them just fine, but Apple's sniffers may not :-)

**Comment by morganchen12** [comment]
Filed b/152796373 internally for renaming GADOMIDUIWebViewJSExecutor.
