### ISSUE TITLE
Crash in Xcode workspace when using firebase

### ISSUE THREAD

**Issue by kubwensu** [firebase/firebase-ios-sdk#3869]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.3
  * Firebase SDK version: 6.8.1
  * Firebase Component: Firebase module (fails 
at initial build)
  * Component version: _____

### [REQUIRED] Step 3: Describe the problem
I followed all installation procedures: 
entered appbundle id 

downloads google plist file
 
-installed cocoapods

-initialized podfile 

-pasted in(# add the Firebase pod for Google Analytics
 pod 'Firebase/Analytics'

-pod install 

-opened to workspace

-imported firebase module in appDelegate

-added FirebaseApp.configure() to didfinishLaunching above return true line

However at initial build it fails reason being, GoogleDataTransportCCTSupport found two issues. 

One a semantic issue "Cannot find interface declaration for 'NSObject', superclass of 'PodsDummy_GoogleDataTransportCCTSupport'"

and the second a class issue "Cannot find interface declaration for 'NSObject', superclass of 'PodsDummy_GoogleDataTransportCCTSupport'"

it says I add a superclass to fix the problem. Is it something wrong with the installation or software. I'm running Mac Os Mojave on VM ware.

Steps to reproduce:
Just set up the app as initially described.

Please help

[Screenshot 2019-09-17 at 09 16 02](https://user-images.githubusercontent.com/55430220/65019736-15db6900-d92c-11e9-99bb-2ef2ba9a1b5d.png)

**Comment by mikehaney24** [comment]
Are you trying to use Firebase from HEAD?

**Comment by paulb777** [comment]
Might be corrupt Xcode state.

Try cleaning and `rm -rf ~/Library/Developer/Xcode/DerivedData/`
