### ISSUE TITLE
Verification SMS does not delivered to user for specific provider.

### ISSUE THREAD

**Issue by khoren93** [firebase/firebase-ios-sdk#387]
### Environment description
  * Xcode version: 9.0
  * Firebase SDK version: 4.4.0
  * Firebase Component: Auth, Core, FirebaseUI
  * Component version: 4.3.0, 4.0.9, 4.4.0

### Problem Description
After verifying phone number with [FIRPhoneAuthProvider provider] user doesn't get an sms for sining in with credentials. The verification code (sms) doesn't sent to user's phone and It depends on concrete provider (vivacell mts Armenia). All other Armenian providers work correctly. 
This has been tested in different projects with almost 10 different phone numbers of the concrete local provider (vivacell mts Armenia). The problem is not stable, it can work rarely.

#### Steps to reproduce:
1. using Firebase UI
In "Enter phone number" screen user enter phone number. After pressing verify button the "Verify phone number" screen appears but user doesn't get an sms to continue the verification flow.
Resend code functionality does not change the situation.

2. using Custom UI
The same problem as described above.

**Comment by morganchen12** [comment]
cc @yramanchuk this affects FirebaseUI, though I don't think it's caused by FirebaseUI code.

**Comment by samtstern** [comment]
@khoren93 thanks for filing this issue.  SMS delivery problems can depend on a multitude of factors and are almost never issues with the SDK code so this repository is not the best place to file them.

Please contact Firebase Support who can better help you troubleshoot this issue:
https://firebase.google.com/support/contact/troubleshooting/
