### ISSUE TITLE
Low Fruit: FIRDocumentSnapshot.h references nonexistent dataWithOptions

### ISSUE THREAD

**Issue by jwyld** [firebase/firebase-ios-sdk#3873]
The header for FIRDocumentSnapshot tells the developer to use dataWithOptions() to alter the behavior of timestamps.  The correct method is dataWithServerTimestampBehavior.

**Comment by wilhuff** [comment]
Thanks for the report! You wouldn't by chance be able to send a PR with a fix, would you? :-D

No worries if not.

**Comment by jwyld** [comment]
Sorry, I'm not set up to build Firestore
