### ISSUE TITLE
Error Domain=FIRAuthErrorDomain Code=17057  

### ISSUE THREAD

**Issue by sombizbuzzz** [firebase/firebase-ios-sdk#3874]
hi I am `getting` this error FIRPhoneAuthProvider providerWithAuth

````
[[FIRPhoneAuthProvider providerWithAuth:[FIRAuth authWithApp:firApp]] verifyPhoneNumber:phoneNumber UIDelegate:nil completion:^(
      NSString *_Nullable verificationID,
      NSError *_Nullable error)
``` {
    if (error) {
     
    } else {
      NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
      [defaults setObject:verificationID forKey:@"authVerificationID"];
      
    }
  }];`


Error Domain=FIRAuthErrorDomain Code=17057 "User interaction is still ongoing, another view cannot be presented." UserInfo={NSLocalizedDescription=User interaction is still ongoing, another view cannot be presented., FIRAuthErrorUserInfoNameKey=ERROR_WEB_CONTEXT_ALREADY_PRESENTED}

  pod 'Firebase/Auth', '~> 6.3.0'


@morganchen12 
https://stackoverflow.com/questions/57985815/firphoneauthprovider-providerwithauth-not-working-ios

**Comment by morganchen12** [comment]
Please share a repro example or post this question on StackOverflow.

**Comment by sombizbuzzz** [comment]
> Please share a repro example or post this question on StackOverflow.

https://stackoverflow.com/questions/57985815/firphoneauthprovider-providerwithauth-not-working-ios added here

**Comment by morganchen12** [comment]
Related to https://github.com/invertase/react-native-firebase/issues/2594, https://github.com/invertase/react-native-firebase/issues/2576

**Comment by sombizbuzzz** [comment]
> Related to [invertase/react-native-firebase#2594](https://github.com/invertase/react-native-firebase/issues/2594), [invertase/react-native-firebase#2576](https://github.com/invertase/react-native-firebase/issues/2576)

both are same issue

**Comment by morganchen12** [comment]
Closing this since I haven't been able to repro the issue. If you have a sample project to share, please comment with the project and I'll reopen the issue.
