### ISSUE TITLE
Can't install FirebaseStorage from cocoa pods

### ISSUE THREAD

**Issue by elu697** [firebase/firebase-ios-sdk#3877]
* Xcode version: 10.3
  * Firebase SDK version: 6.8.1
  * Firebase Component: Storage
  * Component version: 3.4.1

Cant install FirebaseStorage.
the error massage is "[!] Unable to read the license file `LICENSE` for the spec `FirebaseStorage (3.4.1)`"
its screen shot.
![image](https://user-images.githubusercontent.com/20719474/65166124-120a2c80-da7b-11e9-929b-aec997f6ccd6.png)

1st, edit Podfile and insert 'pod 'Firebase/Storage'.
2nd, run "pod install"

**Comment by paulb777** [comment]
Try `pod install  --repo-update`

**Comment by elu697** [comment]
@paulb777 thanks, but I already try.

**Comment by morganchen12** [comment]
If you run `pod install --verbose`, is there a more complete error message?

**Comment by elu697** [comment]
@morganchen12 There was no change.

**Comment by elu697** [comment]
`
#!/usr/bin/env bash

rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update`

I solved it by running this script
