### ISSUE TITLE
InAppMessaging - Failed restful api request to fetch in-app messages 400

### ISSUE THREAD

**Issue by nrj** [firebase/firebase-ios-sdk#3887]
### [READ] Step 1: Are you in the right place?

yes

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2
  * Firebase SDK version: 5.20.2
  * Firebase Component: InAppMessaging + InAppMessagingDisplay
  * Component version: 0.13.0 + 0.13.1

### [REQUIRED] Step 3: Describe the problem

Reopening #2816 - I cannot receive test messages on device or simulator.

#### Steps to reproduce:

Add the following to your Podfile:
```
  pod 'Firebase'
  pod 'Firebase/InAppMessagingDisplay'
  pod 'Firebase/Analytics'
```
- Run `pod install`
- Build and run the app in the simulator or on a device.
- Open Firebase Console and create a new In-App Messaging campaign with style: _Modal_.
- Under options select Test on Device, add your `InstanceID`, and click Test.
- Background the running app, then open it again.

The following error is logged to the Xcode console:
```
2019-09-19 15:17:02.421473+0200 My App[6754:458265] 5.20.0 - [Firebase/InAppMessaging][I-IAM130004] Failed restful api request to fetch in-app messages: seeing http status code as 400 with body as {
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT"
  }
}
``` 

#### Relevant Code:

None

**Comment by christibbs** [comment]
This should be fixed in an upcoming release of the `InstanceID`SDK. Will close this at that time.

**Comment by pimnijman** [comment]
@christibbs where can we follow progress on this issue in the InstanceID SDK?

I've noticed that this problem only occurs when I update from a previous version of my app with a different version number. If I implement InAppMessaging without updating the version or build numbers, or do a clean install, everything works as expected.

**Comment by christibbs** [comment]
@pimnijman  thanks for the additional context. The InstanceID work is complete, we have to do some work on our end to integrate. This should happen in a near-term upcoming release, I'll close this when the work is done.

**Comment by christibbs** [comment]
Thanks for your patience everyone. This should be fixed in the next release of the Firebase iOS SDK.
