### ISSUE TITLE
Twitter Login not working with SwiftUI in iOS 13

### ISSUE THREAD

**Issue by jlxc106** [firebase/firebase-ios-sdk#3890]
###  Environment

  * Xcode version: 11.0 beta 6 (11M392q)
  * Firebase SDK version: 6.8.1
  * Firebase Component: Auth
  * Component version: 6.2.3
  * iOS 13.0+

###  Describe the problem
Once the user authenticates with a valid twitter account, the webview turns into a blank white page. The url changes to "about:blank" and the webview is never dismissed. Pressing "Done" results in error: "The interaction was canceled by the user."

Affects both physical devices & simulators running iOS 13.
Both SwiftUI + Storyboard projects are affected.
Using Cocoapods.
Not using FirebaseUI or TwitterKit.
Doesn't affect simulators running iOS 12.2/12.4

#### Steps to reproduce:
0. Use a simulator/physical device running iOS 13
1. Follow guide here: https://firebase.google.com/docs/auth/ios/twitter-login
2. Sign in with valid Twitter account.

**Comment by renkelvin** [comment]
@jlxc106 Could you reproduce the issue with UIKit on iOS 13?

**Comment by paulb777** [comment]
Related to #3706 and #3521

**Comment by jlxc106** [comment]
@renkelvin works with UIKit on iOS 13, so its really a problem with SwiftUI then.

**Comment by renkelvin** [comment]
@jlxc106 Could you help try the fix on the brach "swift-ui"?

You can do that by changing your podfile to
`pod 'FirebaseAuth', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'swift-ui'`

Please let me know if the fix works for you, and please confirm that the fix doesn't affect your existing code.

**Comment by renkelvin** [comment]
The latest release (FirebaseAuth 6.4.1, GoogleUtilities 6.4.0) should fix this issue.

**Comment by kevinparalta** [comment]
I am experiencing the problems OP had with the updated FirebaseAuth 6.4.1.

**Comment by vamshi-gloify** [comment]
> @renkelvin works with UIKit on iOS 13, so its really a problem with SwiftUI then.

with UIKit also not working for me. After login with valid credentials its loading continuously.
