### ISSUE TITLE
FirebaseCoreDiagnostics has unspecified dependency on nanopb 0.3.901

### ISSUE THREAD

**Issue by acruis** [firebase/firebase-ios-sdk#3911]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2.1
  * Firebase SDK version: 6.8.1
  * Firebase Component: CoreDiagnostics
  * Component version: 1.1.0

### [REQUIRED] Step 3: Describe the problem

`FIRCoreDiagnosticsLog` calls `pb_release`, but this symbol can be missing, causing a linker error.

`FIRCoreDiagnosticsLog` calls `pb_release` upon dealloc ([this line](https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m#L139)).

`pb_release` is only exposed in nanopb's header if the compiler flag `PB_ENABLE_MALLOC` is set ([this line](https://github.com/nanopb/nanopb/blob/master/pb_decode.h#L110)).

However, `PB_ENABLE_MALLOC=1` is only set in nanopb 0.3.901 ([0.3.901 podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/6/1/e/nanopb/0.3.901/nanopb.podspec.json#L20)). nanopb 0.3.8 and below do not set this flag ([0.3.8 podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/6/1/e/nanopb/0.3.8/nanopb.podspec.json#L19)).

As a result, for a project that is currently using nanopb 0.3.8 and below, upgrading Firebase from e.g. 5.x.x to 6.8.1 (to be exact, any Firebase version above 6.3.0) would not upgrade nanopb version unless explicitly required to.

This results in a linker error as `FIRCoreDiagnosticsLog` tries to call `pb_release` but this symbol will be missing (due to the missing compiler flag, causing `pb_release` to not be exposed in the `pb_decode.h` header).

#### Steps to reproduce:

On a fresh project, setup the Podfile to use Firebase 6.8.1 and nanopb 0.3.8, as in the snippet below. Run `pod install` and trigger a build.

The linker step will fail (cannot find symbol `_pb_release`).

#### Relevant Code:

(Podfile)
```
pod 'Firebase', '6.8.1'
pod 'nanopb', '0.3.8'
```

**Comment by nikolay-kapustin** [comment]
The same issue!

**Comment by ryanwilson** [comment]
Apologies for the issues, and thanks for the detailed report pointing this out! We'll get this resolved ASAP.

**Comment by ryanwilson** [comment]
Re-opening until a release is made.

**Comment by acruis** [comment]
Cool, thanks for the quick response! :+1:
