### ISSUE TITLE
Firebase Analytics Event upload Fail With Version-6.9.0

### ISSUE THREAD

**Issue by JackeyChen1015** [firebase/firebase-ios-sdk#3912]
#### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.3
  * Firebase SDK version: 6.9.0
  * Firebase Component: FirebaseAnalytics 
  * Component version: 6.1.2

### [REQUIRED] Step 3: Describe the problem
Call [FIRAnalytics logEventWithName: parameters:]  Log Successful upload ,But Control center Not Show Custom Event . Test Firebase Version-6.8.1 No problem .
#### Steps to reproduce:
 [Firebase/Analytics][I-ACS033003] Scheduling user engagement timer
6.9.0 - [Firebase/Analytics][I-ACS002002] Engagement timer scheduled to fire in approx. (s): 3600
6.9.0 - [Firebase/Analytics][I-ACS023051] Logging event: origin, name, params: auto,
6.9.0 - [Firebase/Analytics][I-ACS023073] Debug mode is enabled. Marking event as debug and real-time. Event name, parameters:
6.9.0 - [Firebase/Analytics][I-ACS023072] Event logged. Event name, event params:
6.9.0 - [Firebase/Analytics][I-ACS002002] Measurement timer scheduled to fire in approx.
6.9.0 - [Firebase/Analytics][I-ACS023028] Upload task scheduled to be executed in approx.
6.9.0 - [Firebase/Analytics][I-ACS002001] Measurement timer fired
6.9.0 - [Firebase/Analytics][I-ACS002003] Measurement timer canceled
6.9.0 - [Firebase/Analytics][I-ACS023033] Starting data upload
6.9.0 - [Firebase/Analytics][I-ACS023105] Event is not subject to real-time event count daily limit. Marking an event as real-time. Event name, parameters:
6.9.0 - [Firebase/Analytics][I-ACS012018] Saving bundle. size (bytes):
6.9.0 - [Firebase/Analytics][I-ACS023116] Bundle added to the upload queue. BundleID, timestamp (ms): 3, 1569321978396
6.9.0 - [Firebase/Analytics][I-ACS023038] Uploading events. Elapsed time since last successful upload (s): 99.13560771942139
6.9.0 - [Firebase/Analytics][I-ACS023039] Measurement data sent to network. Timestamp (ms), data: 
6.9.0 - [Firebase/Analytics][I-ACS900000] Uploading data. Host: 
6.9.0 - [Firebase/Analytics][I-ACS901006] Received SSL challenge for host. Host: https://
6.9.0 - [Firebase/Analytics][I-ACS023044] Successful upload. Got network response. Code, size: 204, -1

#### Relevant Code:
[FIRApp configure];
[FIRAnalytics logEventWithName:@"even" parameters:(NSDictionary *)dict];
Xcode Arguments Passed On Launch Set -FIRAnalyticsDebugEnabled

**Comment by paulb777** [comment]
Tracked internally at b/141537580

**Comment by allenktv** [comment]
Hi @JackeyChen1015, what do you mean by "Control Center". By that do you mean the Firebase Console?

Also the logs that you provided seem to suggest that everything is normal. Could you provide more of your code and also a screenshot of your launch arguments?

**Comment by JackeyChen1015** [comment]
@allenktv Sorry, because there have been other FireBase apps in the past, there are two identical <GoogleService-Info.plist> files in the project, which caused the event not to be successfully reported. It is successful to delete one of the duplicate files.
