### ISSUE TITLE
Dynamic Links doesn't work properly on iOS13.

### ISSUE THREAD

**Issue by jcooperation0137** [firebase/firebase-ios-sdk#3918]
### Test environment

  * Xcode version: 11.0
  * Firebase SDK version: 5.20.2
  * Firebase Component: FirebaseDynamicLinks
  * Component version: 3.4.3

### What is the problem?
1. If app was not launched and you click a dynamic link, app is launched and get the dynamic link correctly on iOS 12, but on iOS 13, app is launched, but doesn't get the dynamic url.
2. If app was in background and you click a dynamic link, app is launched and get the dynamic link correctly on both of iOS 12 and iOS 13.
So my problem is that app doesn't get the dynamic link when app was not launched on iOS 13.

**Comment by morganchen12** [comment]
In both the scenarios you described dynamic links should be using the system universal link callbacks. Can you share the code you're using to fetch the dynamic link?

**Comment by re-ckart** [comment]
Also it seems that you do not get redirected to the app store if the app is not installed.
On iOS12 this works, iOS13 redirects to the fallback link. The app can be installed on iOS13 devices using the AppStore.

**Comment by jcooperation0137** [comment]
@morganchen12 @ryanwilson thanks for your response.
This is what I use to fetch a dynamic link
```
func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        if let dynamicLink = DynamicLinks.dynamicLinks().dynamicLink(fromCustomSchemeURL: url) {
            self.handlIncomingDynamicLink(dynamicLink)
        }
        Branch.getInstance().application(app, open: url, options: options)
        let handled = ApplicationDelegate.shared.application(app, open: url, options: options)
        return handled
    }

func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
        Branch.getInstance().continue(userActivity)
        
        if let incomingUrl = userActivity.webpageURL {
            let linkHandled = DynamicLinks.dynamicLinks().handleUniversalLink(incomingUrl, completion: { [weak self] (link, erorr) in
                guard let stongSelf = self else { return }
                if let dynamicLink = link, let _ = dynamicLink.url {
                    stongSelf.handlIncomingDynamicLink(dynamicLink)
                }
            })
            return linkHandled
        }
        return false
    }
```

@re-ckart app had been already installed on the device when I'd tried to above 2 scenarios.

**Comment by jlubeck** [comment]
I'm seeing this problem myself. 

`func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool` is just never called

**Comment by jlubeck** [comment]
Ok, I found my problem. You might want to update your documentation. 

In my case, I started a brand new project on Xcode 11 which uses `SceneDelegate` as well as `AppDelegate`

Looks like UniversalLinks (and probably several other APIs) use this callback on the `SceneDelegate`:

    func scene(_ scene: UIScene, continue userActivity: NSUserActivity) { }

Instead of this callback on the `AppDelegate`:

    func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool { }

Once I implemented the one on `SceneDelegate` everything started working as expected again. I haven't tried it, but I'm assuming that if you are targeting iOS 12 and below, you might need to implement both methods.

Hope this helps

**Comment by paulb777** [comment]
Thanks for the investigation and analysis @jlubeck!

@dmandar Please take a look.

**Comment by dmandar** [comment]
Thanks for reporting. @re-ckart we are not seeing any issues redirecting links to the app store in iOS 13. Can you confirm by clicking the link from Notes app? Also, you can debug dynamic links by appending the ?d=1 query param. Please reopen if still an issue.
@jlubeck thanks for finding this out. We will investigate and document accordingly.

**Comment by jkopi11** [comment]
We are seeing an issue where if you share a link with the Messages app in iOS 13 and wait long enough or cancel the share and try again, the link eventually opens the fallback url before it is shared. Anyone else notice this?

**Comment by Mangi91** [comment]
Thanks @jlubeck! I was having the exact same issue and couldn't figure out why.
