### ISSUE TITLE
Crash in GULLogBasic when running test plan with Localization Screenshots option

### ISSUE THREAD

**Issue by abotkin-cpi** [firebase/firebase-ios-sdk#3928]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.0 (11A420a)
  * Firebase SDK version: 6.8.0
  * Firebase Component: GoogleUtilities
  * Component version: 6.2.5

### [REQUIRED] Step 3: Describe the problem

When an Xcode 11 test plan has the "Localization Screenshots" option enabled, Google Utilities will crash the app shortly after launch in attempting to log that analytics have started.  This does not occur if the test plan changes the "Localization Screenshots" option to off.

```
(lldb) bt
* thread #5, queue = 'APMMonitorQueue', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
    frame #0: 0x00000001298c7f22 UIAccessibility`-[NSPlaceholderStringAccessibility initWithFormat:locale:arguments:] + 55
  * frame #1: 0x0000000108805821 GoogleUtilities`GULLogBasic(level=GULLoggerLevelNotice, service=@"[Firebase/Analytics]", forceLog=NO, messageCode=@"I-ACS023007", message=@"Analytics v.60101000 started", args_ptr=0x0000000000000000) at GULLogger.m:164:22
    frame #2: 0x0000000107a5dbc6 TestPlanFail`-[APMASLLogger logMessage:logTag:messageCode:withLogLevel:] + 208
    frame #3: 0x0000000107a358b4 TestPlanFail`__44-[APMMonitor logToConsole:message:logLevel:]_block_invoke + 91
    frame #4: 0x0000000109511888 libdispatch.dylib`_dispatch_call_block_and_release + 12
    frame #5: 0x00000001095127f9 libdispatch.dylib`_dispatch_client_callout + 8
    frame #6: 0x0000000109518566 libdispatch.dylib`_dispatch_lane_serial_drain + 707
    frame #7: 0x0000000109518f9c libdispatch.dylib`_dispatch_lane_invoke + 388
    frame #8: 0x000000010952306c libdispatch.dylib`_dispatch_workloop_worker_thread + 626
    frame #9: 0x0000000109989763 libsystem_pthread.dylib`_pthread_wqthread + 290
    frame #10: 0x00000001099895c3 libsystem_pthread.dylib`start_wqthread + 15
```

![Screen Shot 2019-09-25 at 3 38 57 PM](https://user-images.githubusercontent.com/25309848/65645105-19659480-dfab-11e9-83a4-60ec4049602a.png)
![Screen Shot 2019-09-25 at 3 42 56 PM](https://user-images.githubusercontent.com/25309848/65645150-3b5f1700-dfab-11e9-980a-ca5579e16650.png)

#### Steps to reproduce:

1) Create an app that uses Firebase & give it a test plan
2) In the test plan, modify the "Localization Screenshots" option to On
3) Attempt to run your UI tests and note how the app will crash out on GULLogBasic

This can be worked around by raising the logging level of GoogleUtilities logging so it doesn't log at all.

#### Relevant Code:

Attached is a sample project that shows this off.  The GoogleService-Info.plist has been removed - please update the bundle ID, run "pod install", and add your own GoogleService-Info.plist to run this.

[TestPlanFail.zip](https://github.com/firebase/firebase-ios-sdk/files/3655120/TestPlanFail.zip)

If you switch to the test tab and try to run the tests, you'll see the crash.

**Comment by ryanwilson** [comment]
Thank you very much for the detailed report and sample project, @abotkin-cpi! We'll dig into this and see how we can resolve it.
