### ISSUE TITLE
RemoteConfig  bug with user property

### ISSUE THREAD

**Issue by theo68hh** [firebase/firebase-ios-sdk#3961]
Xcode version: 11.1 GM Seed
Firebase SDK version: 6.9.0
Firebase Component: [RemoteConfig]

### Describe the problem
The conditions in Remote Config do not seems to work for the users properties that we create ourselves.

Example: I put the email condition contains "tests@gmail.com" and despite that I send in the user properties "tests@gmail.com" the conditions do not work and it takes the default value.

To initialize the email property I use the following code 
`Analytics.setUserProperty(connectedUser.lastKnownInfo.email, forName: UserProperties.Email) `
When I look at the debugView we also see that the property is sent to Firebase.

<img width="904" alt="Capture d’écran 2019-09-30 à 15 48 11" src="https://user-images.githubusercontent.com/55985282/65884783-bc4a5400-e399-11e9-95ed-dfbe0d336155.png">

After creating user property, when fetching and retrieving information from RemoteConfig with :
`RemoteConfig.remoteConfig().fetchAndActivate` and `RemoteConfig.remoteConfig().configValue(forKey: key.rawValue).stringValue`

The retrieved information are not the same as the configured condition for the instantiated user property.
The condition in Remote Config is 

<img width="824" alt="Capture d’écran 2019-10-01 à 09 19 51" src="https://user-images.githubusercontent.com/55985282/65942011-ab96ee00-e42c-11e9-81e8-2710d7c5577c.png">

**Comment by Bexcode-iOS** [comment]
When can we expect this to be completed?

**Comment by wojteklu** [comment]
Same issue happens for me in version 6.14.0.

**Comment by wojteklu** [comment]
@dmandar @paulb777 Do you need steps or sample code for the issue? It's critical error that prevents to update the library.

**Comment by rizafran** [comment]
Hi @wojteklu, yes, providing steps or sample code would help us to easily replicate the issue.

**Comment by wojteklu** [comment]
@theo68hh @dmandar @rizafran In my case, I was using Carthage builds and the problem was missing `FIRAnalyticsConnector` in `Link binary with libraries`. Since after carthage update, you have to add new libraries by hand in Xcode. It is not validated by `FirebaseAnalytics` if `FIRAnalyticsConnector` is added to target so it was hard to find the issue.

**Comment by paulb777** [comment]
Thanks for the update @wojteklu.  

We'll think about ways to make it less tricky to find issues like this.  It's a bit tricky since it is intentional for Analytics usage to be optional with Firebase.
