### ISSUE TITLE
Download a file from storage without download uri

### ISSUE THREAD

**Issue by swftvsn** [firebase/firebase-ios-sdk#3962]
Hi,

I've tried to read code and documentation but can't really find an answer to this: are the iOS storage file downloads, done using `FIRStorageReference.dataWithMaxSize` still using the download uri approach under the hood, that uses the unguessable token at the end of the uri?

My requirements forbid us to expose such urls to world, so:

1. Is this download secured by the security rules? and
2. Does this download generate the unguessable url for the file?

Thanks you for the answers!

Link to Stackoverflow question:
https://stackoverflow.com/questions/58197787/firebase-storage-download-a-file-from-storage-without-download-uri

**Comment by schmidt-sebastian** [comment]
@swftvsn All up- and download operations that are built into the Firebase Storage SDKs (such as dataWithMaxSize) are evaluated against your rules and do not rely on public download URLs.

**Comment by swftvsn** [comment]
Thank you for the answer @schmidt-sebastian ! (And thanks for the great stack!)
