### ISSUE TITLE
Failed to open DB: LOCK: already held by process

### ISSUE THREAD

**Issue by jzaccone** [firebase/firebase-ios-sdk#3967]
Full error:
```
Fatal Exception: NSInternalInconsistencyException
Failed to open DB: Internal: Failed to open LevelDB database at 
/var/mobile/Containers/Data/Application/D5EA17E8-B506-4E84-84C2-
10A92D7A0AA4/Documents/firestore/__FIRAPP_DEFAULT/xxx/main: LevelDB
 error: IO error: lock /var/mobile/Containers/Data/Application/D5EA17E8-B506-4E84-84C2-
10A92D7A0AA4/Documents/firestore/__FIRAPP_DEFAULT/xxx/main/LOCK: 
already held by process
```

Xcode version: 10.3
Using Firebase (6.6.0)
Using FirebaseAnalytics (6.1.0)
Using FirebaseAnalyticsInterop (1.3.0)
Using FirebaseAuth (6.2.2)
Using FirebaseAuthInterop (1.0.0)
Using FirebaseCore (6.2.0)
Using FirebaseCoreDiagnostics (1.0.1)
Using FirebaseCoreDiagnosticsInterop (1.0.0)
Using FirebaseDatabase (6.0.0)
Using FirebaseDynamicLinks (4.0.2)
Using FirebaseFirestore (1.4.3)
Using FirebaseInstanceID (4.2.3)
Using FirebaseMessaging (4.1.2)
Using FirebaseStorage (3.4.0)
Using FirebaseUI (8.0.4)

Can't reproduce this problem. I am not deleting FIRApp instances, I'm only accessing the database via `Firestore.firestore()` or `[[FIRFirestore firestore]` which should provide the same instance back. The only thing I can think of is `[FIRApp configure];` getting called twice with thread race, but that is supposed to be thread-safe as well.

Found this in another issue #3778 from Will. @wilhuff Is there any other scenarios which might cause this error?

> @ChristianVinterly your case is different. Somehow you've managed to open Firestore more than once in a single process and the second one failed to open its database because the first one still had the database locked.
> 
> Normally, the Firestore SDK keeps a map of active instances so that [FIRFirestore firestore] will return the same instance. The only way I can think of that you might have encountered this is if you deleted FIRApp and then managed to create a new one and a new Firestore instance before the old one shut down.
> 
> If you're at all able to reproduce this, please create a new issue with the details of what you're doing--this is unrelated to the "Operation Not Permitted" issue going on in this discussion.

**Comment by wilhuff** [comment]
Are you possibly accessing Firestore from multiple threads very early in your application?

**Comment by jzaccone** [comment]
Yes, right on launch on querying data from HealthKit, then saving the result into Firestore. This is sometimes called multiple times. Should I be making accessing my Firestore instance from the main thread in this scenario?

**Comment by wilhuff** [comment]
It *should* be the case that this is all thread-safe, but given your description it seems like there may be a race in the initialization somewhere. I'll see if I can reproduce based on that.

This suggests that a workaround for now would be to call `Firestore.firestore()` (or `[[FIRFirestore firestore]`) once (likely early on the main thread) and reuse that instance. If the crash goes away after that it would also confirm the hypothesis.

**Comment by jzaccone** [comment]
OK I will call once and reuse instance like you suggest and will let you know if the crash goes away.

**Comment by wilhuff** [comment]
I haven't been able to reproduce this issue locally, but tracing through the initialization logic I did find a race and I've proposed a fix in #3984.

You can try that out by adding the following to your `Podfile`:

```
pod 'FirebaseCore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'pull/3984/head'
```

Note that any existing lines for `Firebase/Core` should remain unchanged.

**Comment by simonbengtsson** [comment]
We released a new version yesterday and now this is our most common crash appearing for at least 1% of users.

Our new release contains three things related to this:

1. Upgraded firebase sdk form `6.8.1` to `6.9.0`
2. First build with Xcode 11
3. Migrated parts of database from realtime to firestore

Based on environment posted in issue and above comments I would guess its #3 then since we also are using firestore early in the application.

**Comment by wilhuff** [comment]
@simonbengtsson have you been able to reproduce the issue locally? If so, does applying the fix as [described above](https://github.com/firebase/firebase-ios-sdk/issues/3967#issuecomment-537738275) address it?

**Comment by simonbengtsson** [comment]
I have not been able to reproduce, but we will release a new version in a few days so can confirm then if noone have been able to before that.

**Comment by wilhuff** [comment]
OK. We haven't been able to reproduce either. The fix is based on inspection and the result is strictly better than what came before. My worry is that this may not have been the only cause. Please do let us know what you see.

In the meantime this fix will end up in the next Firebase release.

**Comment by jzaccone** [comment]
I have running a new version in production with the PR fix and I have yet to see the crash come up. This resolved the crashes I was seeing
