### ISSUE TITLE
Silent push notification not working iOS 13

### ISSUE THREAD

**Issue by pajtimid** [firebase/firebase-ios-sdk#3985]
Silent push notification not working in iOS 13. But works fine in iOS 12.4. Any solution?

**Comment by chliangGoogle** [comment]
Can you provide an example of payload you send for silent push notification?

**Comment by pajtimid** [comment]
I updated to the iOS 13, the app no longer  receiving push notifications. I deleted the app and reinstalled it, after that I can receive push notifications.
Is there any changes on iOS, that affected the push notifications (token or anything else ) ?

Thank you!

**Comment by chliangGoogle** [comment]
Shouldn't be, we handled the iOS 13 updates on the payload so technically you shouldn't have to change anything. Not sure why reinstall the app matters for this case. If you can still reproduce the issue, please send us 
a. the token
b. let us know which sender API you use to send the notification. 
c. the payload you sent
d. the response you get after you sent the payload

**Comment by tomokitakahashi** [comment]
Hi, I had same issue. 
I tried to solve using`apns-push-type` , but I couldn't .
Is there any other good way?

https://forums.developer.apple.com/thread/121568

**Comment by tomokitakahashi** [comment]
I found patterns of iOS 13 bug.
Maybe you have set empty string to `aps` properties ?

I checked using legacy API :) ↓

|<img width="235" alt="スクリーンショット 2019-10-04 14 52 03" src="https://user-images.githubusercontent.com/16111788/66184366-caa8b080-e6b6-11e9-9f20-116eb6462fba.png">|<img width="252" alt="スクリーンショット 2019-10-04 14 51 51" src="https://user-images.githubusercontent.com/16111788/66184384-d6947280-e6b6-11e9-9588-722a6f3179c7.png">|<img width="241" alt="スクリーンショット 2019-10-04 14 50 41" src="https://user-images.githubusercontent.com/16111788/66184393-dd22ea00-e6b6-11e9-90b9-3cdf60bd2497.png">|
|---|---|---|
|iOS12:⭕️| iOS12:⭕️|iOS12:⭕️|
|iOS13:⭕️| iOS13:❌|iOS13:⭕️|

**Comment by chliangGoogle** [comment]
I'm not able to reproduce for the case when notification field is empty (second scenario), what response do you get when it failed?

**Comment by tomokitakahashi** [comment]
I got no fail response.  It was success response😥

**Comment by chliangGoogle** [comment]
I'm able to reproduce, @chong-shao did we silent the message when notification body is empty?

**Comment by chliangGoogle** [comment]
Actually this only happens in legacy API, not the new http v1 API. We are not currently adding new support for legacy API and encourage developers to migrate to http v1 API. @sampson-chen

**Comment by chliangGoogle** [comment]
@tomokitakahashi can you try sending the failed case above using apns token directly without fcm? 

I'm not sure how Apple handle such payload especially you set content-available to true, meaning it's a hidden message, but then it has a body field.
We think maybe the iOS 13 apple re-enforce on apns-push-type that such payload might not be supported.

**Comment by carloskekwa** [comment]
any news on this concern? I am having problems receiving push notifications ios13!
silent push not always received don't know why!
also i don't know why when i add this method  

- (void)application:(UIApplication *)application
didReceiveRemoteNotification:(NSDictionary *)userInfo
fetchCompletionHandler:(void (^)(UIBackgroundFetchResult result))completionHandler{

    NSLog(@"- silent push:%@", userInfo);
   //  completionHandler(UIBackgroundFetchResultNewData);
}

- (void)userNotificationCenter:(UNUserNotificationCenter *)center
       willPresentNotification:(UNNotification *)notification
         withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler
{} stops working! 

and also silent push are never received

**Comment by chliangGoogle** [comment]
@carloskekwa can you try sending the silent push using apns token directly without fcm?
You can try using this suggestion here: https://github.com/firebase/firebase-ios-sdk/issues/4042#issuecomment-542359566

**Comment by carloskekwa** [comment]
hello @chliangGoogle,

will try and let you know ! 

thanks for your fast answer

**Comment by morganchen12** [comment]
Hey @carloskekwa, the provided script tries to send a notification directly through APNs, bypassing FCM. 

You'll need to serialize the binary response and print its details to see exactly what error you're running into. This [document](https://developer.apple.com/library/archive/technotes/tn2265/_index.html) may help.
