### ISSUE TITLE
Cloud Functions Error

### ISSUE THREAD

**Issue by h36ahmed** [firebase/firebase-ios-sdk#4004]
Lately, I have been receiving a lot of issues regarding network connection lost:
 User info dictionary: 
 _kCFStreamErrorCodeKey: 54 
 NSUnderlyingError: Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={_kCFStreamErrorCodeKey=54, _kCFStreamErrorDomainKey=1} 
 _NSURLErrorFailingURLSessionTaskErrorKey: LocalDataTask <944971F4-03A5-4959-9E05-6E62AF83859C>.<1> 
 _NSURLErrorRelatedURLSessionTaskErrorKey: (
    "LocalDataTask <944971F4-03A5-4959-9E05-6E62AF83859C>.<1>"
) 
 NSLocalizedDescription: The network connection was lost. 

This is after I updated Firebase to 6.9.0. Could you please let me know what is causing this? I am calling cloud functions from my iOS app. The issue happens on iOS 13 and iOS 12 on all types of devices.

**Comment by morganchen12** [comment]
This kind of network error is a result of your device losing network connection in the middle of a request. It's unlikely that this was caused by updating Firebase in your app. We'll need a sample app demonstrating this issue to debug it effectively.

**Comment by h36ahmed** [comment]
This never happened before though. I never added any changes to Cloud functions calls. They have remained the same for months. I have only updated Firebase versions. Although this is happening for some users and not all users, I have not been able to replicate on my end. Only that users have started to complain about this in the past week. I will ask more information about the behaviour.

**Comment by h36ahmed** [comment]
I spoke to a couple of users, a call is made to the cloud function and there is a waiting period for few seconds. After some time, it gives an error. All of the cloud functions fail not just one. They keep giving an error. The function retries but same result. All of the users have LTE internet connection.

**Comment by h36ahmed** [comment]
I am suspecting this change may be caused it. "Transitive GoogleDataTransport dependency incremented to v2.0.0"

**Comment by paulb777** [comment]
@h36ahmed Why do you suspect GoogleDataTransport?  What was the previous version you were on before 6.9.0?

**Comment by h36ahmed** [comment]
6.8.1.

**Comment by h36ahmed** [comment]
I am downgrading it to 6.8.1 to further test my hypothesis. At the moment, all I can say is that on WIFI, Cloud functions work fine but not on LTE.

**Comment by h36ahmed** [comment]
I tested with 6.8.1 and that didn't work either. It's same the issue. For LTE, the error is DEADLINE EXCEEDED. For Wifi, it works fine.

**Comment by h36ahmed** [comment]
I tested with 6.8.0 and that worked for both LTE and WIFI

**Comment by h36ahmed** [comment]
Here is another issue I get when I am trying to connect to my cloud functions using cellular data: An SSL error has occurred and a secure connection to the server cannot be made.

**Comment by radarcontact** [comment]
I’m having the same issue. Only reproducible on cellular. I can take a video of it and submit it someone. Please let me know where to send it.

**Comment by radarcontact** [comment]
@h36ahmed have you been able to solve it by downgrading firebase SDKs?

**Comment by h36ahmed** [comment]
@radarcontact nope. I think ever since I built it with XCode 11, thats when this happened. I thought it would be Firebase changes but I downgraded it 6.7.0 and it still gives me the same error. So I am not sure what is causing this.

**Comment by radarcontact** [comment]
Feels like an SSL error given the error messages. I’m curious if a Google engineer could look into this on their side. Maybe a certificate authentication issue?

@h36ahmed have you been able to downgrade to iOS 10 or Xcode? I last updated our app like 12 days ago. I believe it was compiled with Xcode 10. Curious if it is the software on our side but it feels like this is a google infrastructure issue. 

Would be great to hear more from a google engineer on status updates on what is being done. Can paid support help with finding a remedy? This is highly impacting our users and causing lots of issues.

**Comment by h36ahmed** [comment]
I have not installed old Xcode to test if the issue is XCode 11 build.

**Comment by vukrado** [comment]
I am experiencing the same issue using httpsCallable

**Comment by h36ahmed** [comment]
Hi Google Team, please make this fix urgent. I am getting a lot of complaints from my users about app not working. It is impacting UX of our app.

**Comment by ryanwilson** [comment]
This should be resolved now with no action needed from folks - please test and let us know if things are back to normal or more investigation is needed.

**Comment by Kieranshb** [comment]
It looks to be working on our end! Thank you!
