### ISSUE TITLE
gRPC-Core file not found (Mac Catalyst)

### ISSUE THREAD

**Issue by michael-mansour** [firebase/firebase-ios-sdk#4007]
###  Describe your environment

  * Xcode version: 11.1
  * Firebase SDK version: 6.3.0
  * Firebase Component: Firestore 
  * Component version: 1.5.1

### Describe the problem
When I archive my project for MacCatalyst I get the following errors:

> 'openssl_grpc/ssl.h' file not found
> 'openssl_grpc/bn.h' file not found
> 'openssl_grpc/rsa.h' file not found
> 'openssl_grpc/bio.h' file not found

I have no issues when I run the project.

#### Steps to reproduce:
Choose target >Generic iOS Device then Product > Archive
(This is a Mac Catalyst project)

**Comment by paulb777** [comment]
@michael-mansour Thanks for the report

I'm able to reproduce with `pod gen FirebaseFirestore.podspec --local-sources=./ --auto-open`, updating the signing and archiving `App-iOS`:
```

In file included from /Users/paulbeusterien/firebase-ios-sdk/gen/FirebaseFirestore/gRPC-Core/src/core/tsi/ssl/session_cache/ssl_session_openssl.cc:21:
/Users/paulbeusterien/firebase-ios-sdk/gen/FirebaseFirestore/gRPC-Core/src/core/tsi/ssl/session_cache/ssl_session.h:29:10: fatal error: 'openssl_grpc/ssl.h' file not found
#include <openssl_grpc/ssl.h>
         ^~~~~~~~~~~~~~~~~~~~
/Users/paulbeusterien/firebase-ios-sdk/gen/FirebaseFirestore/gRPC-Core/src/core/tsi/ssl/session_cache/ssl_session.h:29:10: note: did not find header 'ssl.h' in framework 'openssl_grpc' (loaded from '/Users/paulbeusterien/Library/Developer/Xcode/DerivedData/FirebaseFirestore-aykjikkkdlsmpdfclnuanluioqmr/Build/Intermediates.noindex/ArchiveIntermediates/App-iOS/BuildProductsPath/Release-maccatalyst/BoringSSL-GRPC-iOS')
1 error generated.
```

It does seem like the file is there:

```
$ head /Users/paulbeusterien/Library/Developer/Xcode/DerivedData/FirebaseFirestore-aykjikkkdlsmpdfclnuanluioqmr/Build/Intermediates.noindex/ArchiveIntermediates/App-iOS/BuildProductsPath/Release-maccatalyst/BoringSSL-GRPC-iOS/openssl_grpc.framework/Modules/module.modulemap 
  framework module openssl {
    umbrella header "umbrella.h"
    textual header "arm_arch.h"
    export *
    module * { export * }
  }
$ head /Users/paulbeusterien/Library/Developer/Xcode/DerivedData/FirebaseFirestore-aykjikkkdlsmpdfclnuanluioqmr/Build/Intermediates.noindex/ArchiveIntermediates/App-iOS/BuildProductsPath/Release-maccatalyst/BoringSSL-GRPC-iOS/openssl_grpc.framework/Versions/A/Headers/umbrella.h 
  #include "ssl.h"
  #include "crypto.h"
  #include "aes.h"
  /* The following macros are defined by base.h. The latter is the first file included by the    
     other headers. */    
  #if defined(OPENSSL_ARM) || defined(OPENSSL_AARCH64)    
  #  include "arm_arch.h"   
  #endif
  #include "asn1.h"
  #include "asn1_mac.h"
$ ls -l  /Users/paulbeusterien/Library/Developer/Xcode/DerivedData/FirebaseFirestore-aykjikkkdlsmpdfclnuanluioqmr/Build/Intermediates.noindex/ArchiveIntermediates/App-iOS/BuildProductsPath/Release-maccatalyst/BoringSSL-GRPC-iOS/openssl_grpc.framework/Versions/A/Headers/ssl.h
-rw-r--r--  1 paulbeusterien  staff  219812 Oct  5 08:16 /Users/paulbeusterien/Library/Developer/Xcode/DerivedData/FirebaseFirestore-aykjikkkdlsmpdfclnuanluioqmr/Build/Intermediates.noindex/ArchiveIntermediates/App-iOS/BuildProductsPath/Release-maccatalyst/BoringSSL-GRPC-iOS/openssl_grpc.framework/Versions/A/Headers/ssl.h
```

More investigation required ....

**Comment by paulb777** [comment]
Created https://github.com/grpc/grpc/issues/20500 on the gRPC repo.

**Comment by michael-mansour** [comment]
I know that you are working actively on the issue and I wanted to thank you for that. However I really have to ship my app.  While waiting to find the source of the problem, would you have any idea of a workaround so that I can still distribute my app ? 
Thanks a lot

**Comment by paulb777** [comment]
@michael-mansour See the discussion at grpc/grpc#20500 for instructions about manually creating a symbolic link to workaround.

**Comment by michael-mansour** [comment]
@paulb777 thanks ! Unfortunately I am not really familiar with the process of manually adding a symbolic link. Would it be possible to share more details ? (Like a more detailed step by step explanation ?) thanks a lot !

**Comment by paulb777** [comment]
@michael-mansour Steps listed at grpc/grpc#20500

**Comment by appfrilans** [comment]
Any progress here? It's been 6 months!

**Comment by JuLink** [comment]
Is there any news regarding this issue? It's still present with the last version of Xcode (11.4.1).

**Comment by EliteTechnicalCare** [comment]
Problem still exists in Xcode 12, is there any timeline this will be resolved so I don't have to play Simon says with files like im trying to defuse a bomb.

**Comment by paulb777** [comment]
The CocoaPods fix is in https://github.com/CocoaPods/CocoaPods/pull/10224 and targeted for CocoaPods 1.10.2.  Please track it there.
