### ISSUE TITLE
SSL Connection Error With Newer iPhones on Cellular

### ISSUE THREAD

**Issue by radarcontact** [firebase/firebase-ios-sdk#4008]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.0
  * Firebase SDK version: Newest (just updated all frameworks to the latest version as of 10/6/2019)
  * Firebase Component: Functions
  * Component version: _____

I recently updated the function and all of my firebase libraries by deleting the Pods folder and workspace and running "pod install" again. 

### [REQUIRED] Step 3: Describe the problem

My functions are experiencing a  SSL connection error. This only happens on iOS and what seems like the iPhone X. Maybe the iPhone 11 (haven't explicitly tested). Additionally, it goes away on WiFi but it happens with Cellular. Some of our users have reported that they can get it to work on cellular if the connection is really strong. 

This is the output I'm seeing:
2019-10-06 09:17:56.585907-0700 ShinePay[1987:838931] Task <3929B79B-207A-4EC1-8634-555987BF6F3B>.<2> HTTP load failed, 0/0 bytes (error code: -1200 [3:-9858])
2019-10-06 09:17:56.587045-0700 ShinePay[1987:838931] Task <3929B79B-207A-4EC1-8634-555987BF6F3B>.<2> finished with error [-1200] Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSErrorFailingURLStringKey=https://serverurl.cloudfunctions.net/checkToSVersionForUser, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <3929B79B-207A-4EC1-8634-555987BF6F3B>.<2>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <3929B79B-207A-4EC1-8634-555987BF6F3B>.<2>"
), NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://serverurl.net/checkToSVersionForUser, NSUnderlyingError=0x281316790 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9858, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9858}}, _kCFStreamErrorCodeKey=-9858}
2019-10-06 09:17:56.589309-0700 ShinePay[1987:838759] Charge Error2: **An SSL error has occurred and a secure connection to the server cannot be made.**
2019-10-06 09:18:06.663875-0700 ShinePay[1987:838931] [] tcp_input [C5.1:3] flags=[R.] seq=784245452, ack=4118356890, win=849 state=FIN_WAIT_2 rcv_nxt=784245452, snd_una=4118356890
2019-10-06 09:18:06.664906-0700 ShinePay[1987:838931] [] tcp_input [C6.1:3] flags=[R.] seq=4269184132, ack=3001977007, win=849 state=FIN_WAIT_2 rcv_nxt=4269184132, snd_una=3001977007

#### Steps to reproduce:

Call the function

#### Relevant Code:

```

```
-(void) checkToSVersion
{
    
    
    
    NSDictionary *data = nil;
    
    [[_functions HTTPSCallableWithName:@"checkToSVersionForUser"] callWithObject:data
        completion:^(FIRHTTPSCallableResult * _Nullable result, NSError * _Nullable error) {
            
            
            if (error) {
                if (error.domain == FIRFunctionsErrorDomain) {
                    ;
                }
                
                [self.spinner stopAnimating];
                NSLog(@"Charge Error2: %@", error.localizedDescription);
                return;
                
            }
            
            
            bool tosOutcome=  [result.data[@"outcome"] boolValue];
            if(tosOutcome)
            {
                [self checkForTosAgreement];
            }
            else
            {
                [self transitionToMainView];
                
                
            }
            
            
            
            
            
            
            
            
        }];

    
    
    
}
```

```

**Comment by paulb777** [comment]
Looks similar to #4004

**Comment by radarcontact** [comment]
Thanks @paulb777. It is. What is being done? This is highly impacting our users.

**Comment by radarcontact** [comment]
Hi @paulb777 This is causing some serious trouble for us we need resolved ASAP. Can you update? 

Im happy to pay for a support plan if it helps move this along faster. We *really* need this resolved.

**Comment by radarcontact** [comment]
Could it be something simple like an expired SSL certificate?

**Comment by vukrado** [comment]
<img width="484" alt="Screen Shot 2019-10-06 at 8 15 57 PM" src="https://user-images.githubusercontent.com/33791641/66279319-616f9b80-e876-11e9-85fe-922639b4aee5.png">
Allowing Arbitrary Loads removes these errors

**Comment by Kieranshb** [comment]
I am having a similar issue using the flutter firebase cloud_functions plugin as well. Users on cellular networks using iOS cannot use us the cloud functions plugins. It works fine on every other platform and when connected to wifi, but this has caused several complaints from customers.

**Comment by nielswh** [comment]
Our Team is also having the problem with specific iOS devices when using Cellular.  The last week we have had a huge up tick in supports calls of people who could not use the app. Pin pointed the problem to iOS devices on cellular networks.  When making a call to cloud functions, these devices would throw and exception that they are unable to connect.  If on wifi or Android devices, its not an issue.

**Comment by morganchen12** [comment]
Hey all, looks like this is a server issue on our end. We're working to have a fix up as soon as possible. Resolving this issue will not require a binary update.

Googlers, see incident number 16293

**Comment by ryanwilson** [comment]
This should be resolved now with no action needed from folks - please test and let us know if things are back to normal or more investigation is needed.
