### ISSUE TITLE
App crash when calling Firestore.firestore(app: secondaryApp)

### ISSUE THREAD

**Issue by rmdan90** [firebase/firebase-ios-sdk#4009]
I'm trying to access another firestore project to read a document, here is the code:

```swift
let secondaryOptions = FirebaseOptions(googleAppID: "1:123:ios:123abc", gcmSenderID: "123123123123")
secondaryOptions.bundleID = "com.project.secondary"
secondaryOptions.apiKey = "api-key"
secondaryOptions.clientID = "****.apps.googleusercontent.com"
secondaryOptions.databaseURL = "https://secondary.firebaseio.com"
secondaryOptions.storageBucket = "secondary.appspot.com"
       
FirebaseApp.configure(name: "secondary", options: secondaryOptions)

guard let secondary = FirebaseApp.app(name: "secondary") else { return }
let secondaryAuth = Auth.auth(app: secondary)
if secondaryAuth.currentUser == nil {
  signInWithCustomToken(secondary)
} else {
  fireStoreDb = Firestore.firestore(app: secondary) //Crash happens here
}
```

  * Xcode version: Xcode 11 . 
  * Firebase SDK version: Firebase (6.5.0) . 
  * Firebase Component:  (Firestore) . 
  * Component version: FirebaseCore (6.1.0) FirebaseFirestore (1.4.2) . 

the crash happens when i try to create an instance of firestore for the secondary app(project)
and it points at string_apple.cc 
at line 30 `CFIndex num_chars = CFStringGetLength(str);` 
with Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)

Note that i had implemented this on android and it works like a charm, but i don't know how to fix it on IOS. been stuck at this for a day.

**Comment by wilhuff** [comment]
It appears that our validation isn’t very friendly here and we’re crashing when we should be giving you a more helpful error message. In this case the issue is that your options object is missing the Google Cloud project ID.

**Comment by rmdan90** [comment]
Thank you, it worked.
and also this should be said in the firebase documentation too [Here](https://firebase.google.com/docs/projects/multiprojects)

**Comment by wilhuff** [comment]
Could you possibly share the full stack trace you see when you get this failure?

As far as I can tell we are actually validating a missing projectID. A new test I wrote passes https://github.com/firebase/firebase-ios-sdk/pull/4073.

(It's catching the [exception thrown here](https://github.com/firebase/firebase-ios-sdk/blob/master/Firestore/Source/API/FSTFirestoreComponent.mm#L84)).

**Comment by rmdan90** [comment]
I made a test app, and it now shows that the reason is a missing projectID

`FirestoreTest[11011:43449] *** Terminating app due to uncaught exception 'FIRInvalidArgumentException', reason: 'FIROptions.projectID must be set to a valid project ID.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23baa1ee __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50864b20 objc_exception_throw + 48
	2   FirestoreTest                       0x0000000105a09884 _ZN8firebase9firestore3api4impl20ThrowInvalidArgumentERKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEE + 52
	3   FirestoreTest                       0x00000001058dedb6 _ZN8firebase9firestore3api20ThrowInvalidArgumentIJEEEvPKcDpRKT_ + 38
	4   FirestoreTest                       0x0000000105992134 -[FSTFirestoreComponent firestoreForDatabase:] + 324
	5   FirestoreTest                       0x00000001059596b1 +[FIRFirestore firestoreForApp:database:] + 321
	6   FirestoreTest                       0x00000001059594db +[FIRFirestore firestoreForApp:] + 155
	7   FirestoreTest                       0x00000001057fe770 $s13FirestoreTest14ViewControllerC10initializeSo12FIRFirestoreCyF + 1040
	8   FirestoreTest                       0x00000001057fe2b1 $s13FirestoreTest14ViewControllerC11viewDidLoadyyF + 129
	9   FirestoreTest                       0x00000001057fe34b $s13FirestoreTest14ViewControllerC11viewDidLoadyyFTo + 43
	10  UIKitCore                           0x00007fff46f03d96 -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled] + 83
	11  UIKitCore                           0x00007fff46f08cef -[UIViewController loadViewIfRequired] + 1084
	12  UIKitCore                           0x00007fff46f0910c -[UIViewController view] + 27
	13  UIKitCore                           0x00007fff475b0241 -[UIWindow addRootViewControllerViewIfPossible] + 150
	14  UIKitCore                           0x00007fff475af8f5 -[UIWindow _updateLayerOrderingAndSetLayerHidden:actionBlock:] + 232
	15  UIKitCore                           0x00007fff475b09b5 -[UIWindow _setHidden:forced:] + 362
	16  UIKitCore                           0x00007fff475c3d61 -[UIWindow _mainQueue_makeKeyAndVisible] + 42
	17  UIKitCore                           0x00007fff477cac91 -[UIWindowScene _makeKeyAndVisibleIfNeeded] + 202
	18  UIKitCore                           0x00007fff46b172ea +[UIScene _sceneForFBSScene:create:withSession:connectionOptions:] + 1405
	19  UIKitCore                           0x00007fff475751a2 -[UIApplication _connectUISceneFromFBSScene:transitionContext:] + 1018
	20  UIKitCore                           0x00007fff475754e4 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 304
	21  UIKitCore                           0x00007fff470ec535 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 361
	22  FrontBoardServices                  0x00007fff364e0361 -[FBSSceneImpl _callOutQueue_agent_didCreateWithTransitionContext:completion:] + 442
	23  FrontBoardServices                  0x00007fff365065f8 __86-[FBSWorkspaceScenesClient sceneID:createWithParameters:transitionContext:completion:]_block_invoke.154 + 102
	24  FrontBoardServices                  0x00007fff364eae41 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 220
	25  FrontBoardServices                  0x00007fff36506289 __86-[FBSWorkspaceScenesClient sceneID:createWithParameters:transitionContext:completion:]_block_invoke + 355
	26  libdispatch.dylib                   0x000000010889cd6c _dispatch_client_callout + 8
	27  libdispatch.dylib                   0x000000010889fcdd _dispatch_block_invoke_direct + 300
	28  FrontBoardServices                  0x00007fff3652c49e __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
	29  FrontBoardServices                  0x00007fff3652c18c -[FBSSerialQueue _queue_performNextIfPossible] + 441
	30  FrontBoardServices                  0x00007fff3652c69b -[FBSSerialQueue _performNextFromRunLoopSource] + 22
	31  CoreFoundation                      0x00007fff23b0d271 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	32  CoreFoundation                      0x00007fff23b0d19c __CFRunLoopDoSource0 + 76
	33  CoreFoundation                      0x00007fff23b0c9cc __CFRunLoopDoSources0 + 268
	34  CoreFoundation                      0x00007fff23b0767f __CFRunLoopRun + 1263
	35  CoreFoundation                      0x00007fff23b06e66 CFRunLoopRunSpecific + 438
	36  GraphicsServices                    0x00007fff38346bb0 GSEventRunModal + 65
	37  UIKitCore                           0x00007fff47578dd0 UIApplicationMain + 1621
	38  FirestoreTest                       0x00000001057ff76b main + 75
	39  libdyld.dylib                       0x00007fff516ecd29 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) `

**Comment by wilhuff** [comment]
That's good news--sort of. That still leaves the question of how you got `EXC_BAD_ACCESS` around `CFStringGetLength(str)`. That shouldn't ever be happening. If you can reproduce that just be removing the fix you made earlier it would be helpful.

**Comment by rmdan90** [comment]
I will once i get a chance to.
Note that i've tried multiple scenarios on this test project and didn't get the earlier mentioned error.
