### ISSUE TITLE
GDTCORUploadCoordinator uploadTargets

### ISSUE THREAD

**Issue by bmh1990** [firebase/firebase-ios-sdk#4019]
* Xcode version: 10.2
  * Firebase SDK version: 6.9.0
Using FirebaseAnalytics (6.1.2)
Using FirebaseAuth (6.2.3)
Using FirebaseAuthInterop (1.0.0)
Using FirebaseCore (6.3.0)
Using FirebaseCoreDiagnostics (1.1.0)
Using FirebaseCoreDiagnosticsInterop (1.0.0)
Using FirebaseDatabase (6.1.0)
Using FirebaseInstanceID (4.2.5)
Using FirebaseStorage (3.4.1)
Using GoogleDataTransport (2.0.0)
Using GoogleDataTransportCCTSupport (1.1.0)

User have started to have crashes on:
GDTCORUploadCoordinator.m line 111
__52-[GDTCORUploadCoordinator uploadTargets:conditions:]_block_invoke

Here is Crashlytics report:
[com.firstduesizeup.fdsu_issue_crash_0b591ccc63a844cf961b2f9c23709081_DNE_0_v2.txt](https://github.com/firebase/firebase-ios-sdk/files/3702751/com.firstduesizeup.fdsu_issue_crash_0b591ccc63a844cf961b2f9c23709081_DNE_0_v2.txt)

**Comment by bmh1990** [comment]
@maksymmalyhin, Thank's for answer so quickly. The crashes occurred on production and i haven't been able to reproduce it. I don't have a sample app either , but i will update the pods and let you know if this resolves the issue.

**Comment by mikehaney24** [comment]
This is because the ivar is being set and read/written at the same time (see: reading a non-whole value). This happens because the encoders/decoders are not on the queue, whereas the reads and writes are. I'll look into how I can queue the setting of this ivar without creating a deadlock.

**Comment by mikehaney24** [comment]
GoogleDataTransport 3.0.1 and GoogleDataTransportCCTSupport 1.2.1 were just pushed and they should address this issue. Because this is an out-of-band release, please report back quickly if you encounter any issues!
