### ISSUE TITLE
Messaging on iOS 13 not working 

### ISSUE THREAD

**Issue by Almaz5200** [firebase/firebase-ios-sdk#4026]
* Xcode version: 11.0
  * Firebase SDK version: 6.9.0
  * Firebase Component: Messaging
  * Component version: 6.9.0

I’m trying to send push notification on iOS 13 via legacy api and getting success response but there’s no push notification on my device. Same code doing well on iOS 12

**Comment by chliangGoogle** [comment]
This seems like a duplicate issue as #3985.

**Comment by Almaz5200** [comment]
Thanks! I've actually solved my problem, I've got a problem on my side with APNS registration
