### ISSUE TITLE
GoogleDataTransportCCTSupport error after pod update

### ISSUE THREAD

**Issue by JhonnyTawk** [firebase/firebase-ios-sdk#4027]
On iOS 13, errors inside GoogleDataTransport 

Xcode version: 11.0
Firebase SDK version: 6.10.0
Firebase Component: Core
Component version: latest
I am getting this error 

**Pods/GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTUploader.m:119:65: runtime error: null pointer passed as argument 1, which is declared to never be null**

**Pods/GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/GDTCCTLibrary/Private/GDTCCTNanopbHelpers.h:110:52: note: _Nonnull type annotation specified here**

Any solution ?

**Comment by cambronjay** [comment]
I will second this issue. This too occurs with the manual installation of the SDK. When will this be fixed? Apps are breaking in iOS 13.

**Comment by mikehaney24** [comment]
Working on it right now.

**Comment by mikehaney24** [comment]
GoogleDataTransport 3.0.1 and GoogleDataTransportCCTSupport 1.2.1 were just pushed and they should address this issue. Because this is an out-of-band release, please report back quickly if you encounter any issues!

**Comment by cambronjay** [comment]
thanks @mikehaney24 I will check to see if the build will work. I implement the sdk in my cordova plugin https://www.npmjs.com/package/cordova-firebase-plugin

**Comment by cambronjay** [comment]
@mikehaney24  I am using the current release 6.11.0 from here https://firebase.google.com/docs/ios/setup#frameworks, which i believe has your changes in it. However, I am now seeing another issue. See the attached screenshot.
<img width="1400" alt="firebase-errors" src="https://user-images.githubusercontent.com/10892549/67421743-1efccd00-f59f-11e9-8eb5-20a5d850a7ba.png">

**Comment by paulb777** [comment]
@cambronjay Please verify that the project is actually linking GoogleDataTransport.framework and it's the version from the 6.11.0 release.

**Comment by cambronjay** [comment]
@paulb777 it is using the 6.11.0 release and the GoogleDataTransport.framwork is included with the  analytics portion of the SDK. I don't how else it would/could be linked. The past version worked with no errors. These past two releases have not worked.

**Comment by cambronjay** [comment]
@mikehaney24  i am still experiencing an issue in 6.11.0 Any chance there will be a fix soon?

**Comment by paulb777** [comment]
@cambronjay 6.12.0 was released yesterday.  However, since no one else has reported this problem that would break any zip distribution usage, it seems highly likely that there is something going on with your particular configuration.

**Comment by cambronjay** [comment]
@paulb777 The issue has been reported in a different thread, but i believe you have closed it. I will retest with 6.12.0 and see if the issue is resolved.
