### ISSUE TITLE
Update Firebase Auth + GoogleSignIn docs

### ISSUE THREAD

**Issue by ZachOrr** [firebase/firebase-ios-sdk#4034]
Hey there - I see Firebase Authentication on iOS got [updated to support GoogleSignIn 5.0.0](https://github.com/firebase/firebase-ios-sdk/issues/3609), but [the docs](https://firebase.google.com/docs/auth/ios/google-signin) haven't been updated. Would it be possible to update the documentation to reflect the necessary changes for the new version of the library?

Thanks!

**Comment by morganchen12** [comment]
Fixed in cr/284802577 (internal link)
