### ISSUE TITLE
Firebase/Firestore can not work with SVGKit. it wil build error.

### ISSUE THREAD

**Issue by LipYoung** [firebase/firebase-ios-sdk#4035]
* Xcode version:  11
  * Firebase SDK version: Firebase/Firestore 6.7.0
  * Firebase Component: 

```
  pod 'Firebase/Firestore'
```
 * pod version:  1.8.1
 * macos version: 10.14.6 

### [REQUIRED] Step 3: Describe the problem

If I add the `Firestore` edit to the newly created project, an error will occur. If you remove the `Firestore` edit, it will be fine.

如果我在新创建的工程中添加`Firestore`编辑就会出现错误。如果移除`Firestore`编辑就正常了。

#### Steps to reproduce:

1 use xcode 11.0(11A420a) create new ios project. 
2 use podfile. 
3 run pod install. 
4 run command + b.

#### Relevant Code:

podfile content:

```
platform :ios, '10.0'
inhibit_all_warnings!

target 'TestFirebase' do
  use_frameworks!
  pod 'SVGKit', '3.0.0-beta1'
  pod 'Firebase/Firestore'
end
```

**Comment by paulb777** [comment]
What is the error?

Please share the created project.

**Comment by LipYoung** [comment]
![image](https://user-images.githubusercontent.com/15086314/66534240-3ae88380-eb48-11e9-8345-2b917e97b1f4.png)

This is error info.

**Comment by LipYoung** [comment]
[TestFirebase.zip](https://github.com/firebase/firebase-ios-sdk/files/3710193/TestFirebase.zip)

i uploading this test project.

**Comment by var-const** [comment]
Quick update: `SVGKit` accidentally imports a header file from `Firestore` instead of its own header. One of the reason it happens is that `SVGKit` imports using short file names, and the file name is really common (`Document.h`). The issue appears to be related to header maps. I'll post another update once I have it -- I'll continue investigating the issue.

**Comment by var-const** [comment]
@LipYoung #4054 is a workaround for the issue; it will be a part of the next release, but if you'd like to try it out sooner, you can use the commit with the workaround in your `Podfile`:
```
pod 'FirebaseFirestore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'pull/4054/head'
```
(notice no slash in `FirebaseFirestore` -- that's the name of the development pod).

**Comment by LipYoung** [comment]
@var-const thx. This it help for me.
