### ISSUE TITLE
Firestore <uninitialized>

### ISSUE THREAD

**Issue by hberson** [firebase/firebase-ios-sdk#4036]
* Xcode version: Xcode Version 11.0 (11A419c)
  * Firebase SDK version: 6.9.0
  * Firebase Component: Firestore
  * Component version: 6.9.0

### [REQUIRED] Step 3: Describe the problem

The code snippet bellow is how I configure firebase because the app I am working on contains three type of configurations; development, staging, and production configuration/environment. 

```
class FirebaseService: NSObject, AppDelegateService {
    
    private let appData: AppData
    
    init(appData: AppData = AppData()) {
        self.appData = appData
    }
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
        
        let firebaseGoogleServiceAppNameKey = AppDataKey(value: Constants.AppDataKeys.firebaseGoogleServiceAppName)
        let firebaseGoogleServiceFileKey = AppDataKey(value: Constants.AppDataKeys.firebaseGoogleServiceFile)
        
        guard let googleFileName = self.appData.infoDictionary?[firebaseGoogleServiceFileKey.value] as? String,
            let appName = self.appData.infoDictionary?[firebaseGoogleServiceAppNameKey.value] as? String,
            let googleFilePath = Bundle.main.path(forResource: googleFileName, ofType: "plist"),
            let firebaseOptions = FirebaseOptions(contentsOfFile: googleFilePath) else {
                fatalError("Failed to configure firebase")
        }
        FirebaseApp.configure(name: appName, options: firebaseOptions)
        return true
    }
}
```

The problem that I encounter is when I invoke `Firestore.firestore(app: app)` Firestore is nil. And if I print the command to the console, then it prints `<uninitialized>`. 

The weird thing about this is that I can authenticate via phone number because I can instantiate an Auth object by passing in the app.

#### Steps to reproduce:

Configure firebase with a `FirebaseOptions` and pass it the `GoogleService.plist` file. Invoke any a process on `Firestore` or put a break point and log the firestore instance to the console.

```
func setGenericInfo(completion: @escaping ServiceResponseHandler) {
        self.firestore?.collection("testCollection")
            .addDocument(data: ["username" : "foobar"]) { (error) in
                if let error = error {
                    completion(.failure(error.localizedDescription))
                } else {
                    print("Success")
                }
        }
    }
```

**Comment by ryanwilson** [comment]
Hi @hberson, thanks for the report.

A set of questions that should help track this further: where, how, and when does `self.firestore?` get initialized?

Thanks!

**Comment by var-const** [comment]
Thanks for the bug report! Unfortunately, we would need additional information to investigate the issue. I cannot reproduce it in a new project, so there must be something specific to your configuration or environment that makes the issue manifest. `Firestore.firestore(app:)` should never return `nil`, even upon bad input (it would throw instead), so something must go wrong in the implementation of that method.

The two parts that `Firestore.firestore(app:)` implementation that could in theory result in returning `nil` are this:

https://github.com/firebase/firebase-ios-sdk/blob/046e2997ef0506d9e26015a2fb86826e0dea7bdb/Firestore/Source/API/FIRFirestore.mm#L121-L123

and this:

https://github.com/firebase/firebase-ios-sdk/blob/046e2997ef0506d9e26015a2fb86826e0dea7bdb/Firestore/Source/API/FSTFirestoreComponent.mm#L117

The best theory I can come up with at the moment is that `provider` ends up being `nil`. Here's a couple of things to check:

* `FirebaseApp.configure()` must be called in `application: didFinishLaunching` and before trying to initialize `Firestore`. Can you confirm that's the case, i.e. that your app isn't trying to initialize `Firestore` before the Firebase app is configured?
* there was an [issue with similar sympthoms](https://github.com/firebase/firebase-ios-sdk/issues/2419#issuecomment-467517533) where the solution was to add `-ObjC` flag to `Other Linker Flags`. Could you please check to see that your build settings do contain this flag?

If none of the above helps, here's some information that would be helpful for us to continue investigating this issue:
* if you could come up with a minimal repro case, that would be most useful! (make sure to remove any sensitive information);
* do you see any Firestore-related errors in the [logs](https://gist.githubusercontent.com/katowulf/0475fb7a5907ed757f687aab6ed15878/raw/07bcf462caa22c92f05831552504edd042153d48/enable_debug_logging.swift)?
* If you could set breakpoints at the lines mentioned above and see whether `provider` or `firestore` are nil, it would be very helpful. My strong suspicion is that `provider` is nil.

**Comment by hberson** [comment]
Hey @var-const when I have the bandwidth to create a simple repo mirroring the configurations I will do so, but I was able to add `-ObjC` flag to `Other Linker Flags` and now running the app I got the  following `Assertion failure`.

```
2019-10-11 22:50:09.190125-0400 ios-room-service[52157:2861009] *** Assertion failure in std::string firebase::firestore::remote::LoadGrpcRootCertificate()(), /Volumes/BuildData/tmpfs/tmp/FirebaseZipRelease/project/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/remote/grpc_root_certificate_finder_apple.mm:181
FIRESTORE INTERNAL ASSERTION FAILED: Could not load root certificates from the bundle. SSL cannot work. (expected path)
(null)
```

**Comment by var-const** [comment]
@hberson The issue with certificates usually happens when adding Firestore to the project manually or through Carthage. Can you please clarify how your app is getting the Firestore dependency, do you use CocoaPods or something else? Normally, the certificates are supposed to come as part of the `gRPC-C++` pod (in its resources bundle).

**Comment by hberson** [comment]
@var-const I apologize for not updating you sooner, but I forgot to mention that I was using Carthage and when I scrolled down on the documents page I realized that I forgot that step. The project is working as expected and connecting to `Firestore`. Thank you for the help!

**Comment by var-const** [comment]
Glad that helped!
