### ISSUE TITLE
GDTCORStorage Null pointer exception

### ISSUE THREAD

**Issue by JhonnyTawk** [firebase/firebase-ios-sdk#4039]
On iOS 13, errors inside GDTCORStorage

Xcode version: 11.0
Firebase SDK version: 6.10.0
Firebase Component: Core
Component version: latest
I am getting this error

Getting Null pointer passed as argument 2, which is declared to never be null **on** 

`[NSKeyedUnarchiver unarchivedObjectOfClass:[GDTCORStorage class] fromData:data error:&error]; in line 220`

<img width="1299" alt="Screen Shot 2019-10-10 at 10 41 45 AM" src="https://user-images.githubusercontent.com/38781782/66548837-b0555380-eb4a-11e9-8fe2-c6a2e1875992.png">

**Comment by jeffvstudio** [comment]
Same error for me

**Comment by mikehaney24** [comment]
GoogleDataTransport 3.0.1 and GoogleDataTransportCCTSupport 1.2.1 were just pushed and they should address this issue. Because this is an out-of-band release, please report back quickly if you encounter any issues!
