### ISSUE TITLE
App crashes while running XCUItest on XCODE , crashes with com.google.FPRScreenTraceTracker error

### ISSUE THREAD

**Issue by abhilnay** [firebase/firebase-ios-sdk#4062]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.0
  * Firebase SDK version: 6.0.0
  * Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by visumickey** [comment]
@abhilnay Can you share some more details about the error here?

1. Can you share the kind of test to make sure we understand the scenario?
2. Can you share the version of the Firebase Performance SDK used?
3. Can you share some more information about the error? Any information would make it easier for us.
4. What is the version of XCode/iOS you are performing this test?
