### ISSUE TITLE
Firestore with secondary FirebaseApp not yielding results

### ISSUE THREAD

**Issue by RuiAAPeres** [firebase/firebase-ios-sdk#4080]
### [READ] Step 1: Are you in the right place?

Yes.

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.1
  * Firebase SDK version: 6.10.0
  * Firebase Component: Firestore
  * Component version: 1.6.0

#### Steps to reproduce:

I am currently using a secondary `FirebaseApp` for Firestore. I load said app via another plist. I made sure it works by printing its information via `app.options.`, so the right plist is picked up.

Using the [example provided here ](https://firebase.google.com/docs/firestore/query-data/get-data), doesn't yield any results (the callback is never executed). I know that the data is accessible, since the Android counterpart is able to fetch said information. 

#### Relevant Code:

```swift
let path = Bundle.main.path(forResource: "AppConfiguration", ofType: "plist")!
let options = FirebaseOptions(contentsOfFile: path)!
let app = FirebaseApp.configure(name: "App", options: options)
let db = Firestore.firestore(app: app)

let docRef = db.collection("myCollection").document("aDocument")

docRef.getDocument { (document, error) in
    if let document = document, document.exists {
        let dataDescription = document.data().map(String.init(describing:)) ?? "nil"
        print("Document data: \(dataDescription)")
    } else {
        print("Document does not exist")
    }
}
```

In this case, the closure passed to `getDocument` never gets called.

**Comment by RuiAAPeres** [comment]
The secondary FirestoreApp was being initialized in the App Module and then calls being made from a Module B. This was the culprit. I moved this:

```
let app = FirebaseApp.configure(name: "App", options: options)
let db = Firestore.firestore(app: app)
```

To Module B, so the FirebaseApp is configured in Module B and now things work. Is this documented behaviour?

**Comment by wu-hui** [comment]
I tried reproduce this by creating `db` in App Module, and then calling `db.collection().document().getDocument` as you described, from a unit testing module, and it works for me. I hope I get your description right? Can you elaborate a bit more on your setup?

Also `FirebaseApp.configure` returns `Void` so you code does not compile, just to confirm, you meant
```Swift
FirebaseApp.configure(name: "App", options: options)
let app = FirebaseApp.app(name: "App")
let db = Firestore.firestore(app: app)
```
Right?

**Comment by wu-hui** [comment]
I believe you were also asking for Swift Codable? 

Codable is not officially released yet. You'd have to try it from our repository for now, here is the pod spec `FirebaseFirestoreSwift.podspec`, it's under repository root. 

Note we might still change the API as it is not released yet.

**Comment by wu-hui** [comment]
I tried reproducing it with a separate library module, instead of a unit test module, and still cannot reproduce what you saw. We'd appreciate if you can give a bit more details about your setup when you see the issue.

Thanks.

**Comment by RuiAAPeres** [comment]
Two different Firebase Apps configured in the first module. Passed the secondary FirebaseApp to a second module. Initialised a Firestore with said app and it didn't work. As in, no callback.

**Comment by wu-hui** [comment]
Hi RuiAAPeres,

I tried again and still could not reproduce. 

In your first module, when you configure both apps, do they have same bundle ID?

I have tried with both different ID and same ID, the callback is called as expected though.

At this point I could not move forward without more details.

Thanks

**Comment by morganchen12** [comment]
@RuiAAPeres, can you share a project that reproduces this issue?

**Comment by RuiAAPeres** [comment]
@wu-hui I really appreciate your thorough review and investigation. I am afraid I can't provide any more detail than the one I already have. They did have the same bundle id, but on the meantime it's working, so it's no longer a blocker. 😞

**Comment by RuiAAPeres** [comment]
@morganchen12 unfortunately I can't.

**Comment by morganchen12** [comment]
No problem, thanks for helping us investigate! If you still have the logs from the time the error was reproducible, please post them here, and if the issue resurfaces let us know and we'll re-open the issue.

**Comment by RuiAAPeres** [comment]
@morganchen12 that was really the issue, there weren't any at all. 😥
