### ISSUE TITLE
RemoteConfig.remoteConfig().fetch return .success while the app is offline

### ISSUE THREAD

**Issue by julienbodet** [firebase/firebase-ios-sdk#4100]
### Describe your environment

  * Xcode version: 11.0 (11A420a)
  * Firebase SDK version: 6.10.0
  * Firebase Component: Remote Config
  * Component version: 6.10.0

### Describe the problem
`RemoteConfig.remoteConfig().fetch` returns a `.success` status (`FIRRemoteConfigFetchStatus`) even though I disabled the internet connection.

Note: I never configured defaults via `setDefaults`, and I ran the app for the first time to be sure no previous config was cached.

#### Steps to reproduce:
- Create a new project importing Firebase/RemoteConfig through Cocoapods
- Follow this [guide](https://firebase.google.com/docs/remote-config/use-config-ios) by skipping the step 2 consisting of setting in-app defaults. 
- Disable the internet connection
- Run the app, the remote config is fetched

What happened? How can we make the problem occur?
I got a `.success` status and a `nil` error even though the app is offline and I didn't set any defaults. I expect to get an error instead.

**Comment by rizafran** [comment]
Thanks for reporting @julienbodet. I was able to get the same behavior, and I'll file this internally to see what's causing the issue. I'll let you know once I have an update.
