### ISSUE TITLE
This file should only be included when compiling with MSVC.

### ISSUE THREAD

**Issue by tejas-ardeshna** [firebase/firebase-ios-sdk#412]
* Xcode version: 9.0
  * Firebase SDK version: 4.4.0
  * Firebase Component: Auth, Core, Database
  * Component version:
     - FirebaseAnalytics, 4.0.4
      - FirebaseCore, 4.0.9
      - FirebaseDatabase, 4.1.1
      - FirebaseInstanceID, 2.0.5
 * Project language: Obj-C

We were using firebase 4.0.0. Everything working fine but once we updated there is wired issue happening. Everything broke, even we can't run that app. (Like compiling with MSVC http://prntscr.com/h25kvo)

Steps to reproduce:

Update pod from 4.0.0 to 4.4.0

PS: we are facing slow data reading from firebase real-time database so we have updated pods. If we can get fast data from real-time database then there is no need to update pod file. Also, we have set persistent storage true.

**Comment by paulb777** [comment]
The problem is likely related to something in the configuration causing the `leveldb` dependency pod to get built with the wrong options.

Please try `pod deintegrate`, removing ` ~/Library/Developer/Xcode/DerivedData/`, `pod install`, and rebuilding.

**Comment by tejas-ardeshna** [comment]
@paulb777 No luck, same issue.

**Comment by paulb777** [comment]
@tejas-ardeshna Are you able to share a reproducible example? If not, you could investigate how your project differs from the [FirebaseDatabase QuickStart](https://github.com/firebase/quickstart-ios/tree/master/database).

**Comment by morganchen12** [comment]
This looks like a project configuration issue. We won't be able to debug this unless there's a project that reproduces this issue. Please re-open once you've got a project you're able to share.
