### ISSUE TITLE
Firestore slow queries

### ISSUE THREAD

**Issue by jenjia** [firebase/firebase-ios-sdk#413]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: Version 9.0.1 (9A1004)
  * Firebase SDK version: 4.4.0
  * Firebase Component: Firestore
  * Component version: 0.9.0

### [REQUIRED] Step 3: Describe the problem

Goal: mobile (testing on iOS) offline data access.

As the title says queries in Firestore are really slow, memory hungry and CPU.
My user case is a collection of 35.000 documents, each document has ~50 fields, 7 of them being of type Object with 6 of them having one child and 1 having 2 child's
A simple query (eg .whereField("name", isEqualTo: "xxxxxxxx")) takes 30 sec, 100% cpu, up to 1GB memory usage.
(Here is a gif showing the usage over time in xCode: https://giphy.com/gifs/3ov9jGSQVNmwUrFYaY)

#### Steps to reproduce:

Use the example "Friendly Eats" provided by Firebase. 
Change the populate function to populate 20.000 examples (not more, or you will cap the write ops - if you have a free account) wait for all the data to be uploaded to Firebase cloud. Then you can start filtering using the example and the slowness will also be there.

**Comment by wilhuff** [comment]
This kind of use case is outside the intended performance envelope of the beta SDKs. Right now the iOS SDK [does a linear scan of documents in the offline cache](https://github.com/firebase/firebase-ios-sdk/blob/f9b2f91da109d2b74f7076e8b6b6d8ced73a5e27/Firestore/Source/Local/FSTLevelDBRemoteDocumentCache.mm#L104) with the expectation that the number of documents people actually use is small.

The Javascript SDK is slightly better in that the query is [restricted by parent path](https://github.com/firebase/firebase-js-sdk/blob/f2c4e6dbbcc32adc475545166801ef2006ea6b69/packages/firestore/src/local/indexeddb_remote_document_cache.ts#L63) but this wouldn't really help in this case where you're hoping to get 35k documents in a single collection.

We intend to implement indexing for GA, though I can't promise what that timeline will be.

**Comment by fleitz** [comment]
Can you add to the documents that Firestore isn't actually intended for use? 

Like maybe, wording such as if you have more than 5 documents in a collection, don't use this as it will be slow as molasses. I have 10 documents in a DB and the queries are taking 2-5 seconds to return.

**Comment by morganchen12** [comment]
@fleitz that's a bug. Do you have any sample data or code that reproduces this issue?

**Comment by hoangvuanhdevelopervn** [comment]
Me too. Firestore very very very slow. I just call 10 documents each time but it's take 5, 6 minutes to finish. My netwok is strong, i also using another back-end server and it's fast, firestore is too slow, worst back-end i ever use.

**Comment by lonelydatum** [comment]
I'm experiencing the same thing. It takes 3 seconds to get the data. Please improve the speed.

**Comment by slopSurfer** [comment]
Im using ADMIN SDK in node.js AWS lambda function.  RDS Postgres will return 280 rows in ~300 millseconds (from a table that contains millions of rows), Dynamodb takes about 1100 ms for same query, Firestore is taking on average 3- 4.5 seconds to return 2 documents! The collection only contains 4 documents.  In an Android app the performance is similar.  Im in Sydney Australia.  Surely there must be some explanation beyond distance?  I like Firestore but cant use it the moment because of this issue.  I have been experimenting with it for a couple of weeks

**Comment by jdimond** [comment]
@slopSurfer some of this latency may be attributed to slow-start problems: It takes some time to setup the correct connections between the backends from Australia. For backend/admin operations it's usually recommended to co-locate the code with where your data lives. Are you able to execute the lambda functions in us-central1? This should drastically improve latency.

**Comment by slopSurfer** [comment]
@jdimond You are correct.  The issue appears to be slow initial database connection time.  After some brief investigation it appears about 75% of the 'query' time is attributed to the connection process.  After the connection latter queries are significantly faster.  I looked at a connection and query to Firebase and it was about 30% faster then Firestore, but once again the initial connection was the cause of the slow initial query.  I will do the experiment to move the lambda's to us-central1 and get some metrics.  Thanks for the feedback.

**Comment by jenjia** [comment]
> We intend to implement indexing for GA, though I can't promise what that timeline will be.

@wilhuff sorry to bother you, a year as passed, and I cannot find if this is already implemented. Can you tell me? or guide me to where I can find the doc of implementation of features likes this?

Thank you.
