### ISSUE TITLE
Firebase frameworks added manually fail unit tests to check for extra values - performance, analytics and (com) Crashlytics 

### ISSUE THREAD

**Issue by valerianaGit** [firebase/firebase-ios-sdk#4138]
### [READ] Step 1: Are you in the right place?
Yes

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.3
  * Firebase SDK version: manually added latest versions
   CocoaPod            | Version
 
FirebaseAnalytics               | 6.1.3
FirebasePerformance             | 3.1.5
FirebaseRemoteConfig            | 4.4.2

  * Firebase Component: _____ analytics, performance, Crashlytics (com) and 
  * Component version: failing unit tests. ran on device and simulator (iOS 12.4) 
DEVICE - iPhone XR - iOS 12.4
Simulator - iPhone 8 - iOS 12.4

### [REQUIRED] Step 3: Describe the problem
Before
Manually added the folders for Analytics, crashlytics and remoteConfig, last updated in June.  Worked fine.

Now 
 1 Deleted old firebase folders.
 2 Added Analytics, performance, remote config and com from latest update. Com does not have a README, but the    last update is September 9th 2019 for Crashlytics and June 17th 2019 for Fabric. 

   These frameworks map to these versions of the Firebase SDKs in Cocoapods
     CocoaPod            | Version
 
FirebaseAnalytics               | 6.1.3
FirebasePerformance             | 3.1.5
FirebaseRemoteConfig            | 4.4.2

 3 Added frameworks to both targets : app and tests. 
 4 Checked all paths are fine on build settings. 

Project builds fine, but Fail unit tests. The test it fails is : 

Failed test
Test: 
- (void)testCrashlyticsIsTheDefaultAttributesReporter
{
    // NOTE: Intentionally NOT |XCTAssertEqualObjects|.
    // We legitimately want pointer equality (the same object), not semantic equality, for once.
    XCTAssertEqual(crashReporter.attributesReporter, (id<AttributesReporter>)Crashlytics.sharedInstance, @"|userInfoReporter| %@ should default to |Crashlytics.sharedInstance| %@.", crashReporter.attributesReporter, Crashlytics.sharedInstance);
}

Crash message:

((crashReporter.attributesReporter) equal to ((id<AttributesReporter>)Crashlytics.sharedInstance)) failed: ("<******** 00600000>") is not equal to ("<******** 00600000>") - |userInfoReporter| <Crashlytics: 0x600000*******> should default to |Crashlytics.sharedInstance| <Crashlytics: 0x600000******>.

These are in fact, different values. 
-----

I don’t know what could be causing this. And when I tried to merge to my main branch, we crashed on app launch, upon initializing Firebase. So Initializing Firebase is somehow double initializing, maybe?  

#### Steps to reproduce:

 1 Deleted old firebase folders.
 2 Added Analytics, performance, remote config and com from latest update. Com does not have a README, but the    last update is September 9th 2019 for Crashlytics and June 17th 2019 for Fabric. 

   These frameworks map to these versions of the Firebase SDKs in Cocoapods
     CocoaPod            | Version
 
FirebaseAnalytics               | 6.1.3
FirebasePerformance             | 3.1.5
FirebaseRemoteConfig            | 4.4.2

 3 Added frameworks to both targets : app and tests. 
 4 Checked all paths are fine on build settings. 

Project builds fine, but Fail unit tests. The test it fails is : 

#### Relevant Code:

above
// TODO(you): code here to reproduce the problem
I need to safely add these frameworks manually.

**Comment by morganchen12** [comment]
Looks like you've included Firebase twice in your test target. How are your frameworks being linked into your tests?

**Comment by valerianaGit** [comment]
@morganchen12. here is the step by step breakdown: 
1 -  I dragged the folders to the project navigator 
2 - then this option popped up 
![Screen Shot 2019-10-23 at 10 48 00 AM](https://user-images.githubusercontent.com/42816552/67411057-a6881300-f582-11e9-9f0f-d76214b9fac8.png)
3 - I selected the project and tests targets 
4 - clicked on Add. 

5 - then I arranged them all in one folder, called it Firebase. 
And from that , it is giving me that . What do you think it could be?  is that not how we should do it?  thanks!

**Comment by morganchen12** [comment]
Dragging them into Xcode should automatically add them to the Link Binary with Libraries phase under your target's Build Phases. If Firebase is added to both the test and main app target and the test target embeds the main app, then you will have duplicate Firebase symbols in your test target.

Please check your build targets to make sure you don't have Firebase linked in both.
