### ISSUE TITLE
Version 0.1.5 not available on CocoaPods spec source

### ISSUE THREAD

**Issue by cristianomatte** [firebase/firebase-ios-sdk#415]
* Xcode version: 9.0
  * FirebaseCommunity SDK version: 0.1.5
  * Firebase Component: Messaging

The 0.1.5 version of the firebase-ios-sdk is already available through GitHub, but hasn't been uploaded to the [CocoaPods specs source repository](https://cocoapods.org/pods/FirebaseCommunity).

This makes it impossible to release frameworks that depends on the 0.1.5 of the firebase sdk version through CocoaPods, which gives the following error:
`None of your spec sources contain a spec satisfying the dependency: FirebaseCommunity/Messaging (= 0.1.5).`

It is possible to use the 0.1.5 version in a Podfile by specifying the source in the `pod` line. But Podspecs files don't allow specs sources to be defined.

To reproduce the problem, just a `podspec` file with the following line is required:
`s.dependency 'FirebaseCommunity/Messaging', '0.1.5'`

Then, when running the `pod spec lint` command the reported error occurs.

**Comment by paulb777** [comment]
I hope to get 0.1.5 pushed later today. If you need to go sooner, you could go back to 0.1.4.  I'll update this issue after the push.

**Comment by paulb777** [comment]
Pushed:

--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  FirebaseCommunity (0.1.5) successfully published
 📅  October 30th, 13:27
 🌎  https://cocoapods.org/pods/FirebaseCommunity
 👍  Tell your friends!
--------------------------------------------------------------------------------
