### ISSUE TITLE
Firebase/Analytics Crash

### ISSUE THREAD

**Issue by Bilonik** [firebase/firebase-ios-sdk#4157]
App is crashing after updating to Firebase Analytics 6.11.0

Xcode 11.1
iOS: 13.1

6.11.0 - [Firebase/Analytics][I-ACS029016] Cannot retrieve configuration data from database. Error: Error Domain=com.google.gmp.measurement.ErrorDomain Code=2 "Remote config data is corrupted" UserInfo={NSLocalizedDescription=Remote config data is corrupted}

**Comment by paulb777** [comment]
@Bilonik If you have nanopb 0.3.904 installed, would you do a `pod update`?  This might be related to #4154

**Comment by Bilonik** [comment]
Just updated nanopb from 0.3.904 to  0.3.9011  with pod update, still same issue.

Console:
 6.11.0 - [Firebase/Analytics][I-ACS029016] Cannot retrieve configuration data from database. Error: Error Domain=com.google.gmp.measurement.ErrorDomain Code=2 "Remote config data is corrupted" UserInfo={NSLocalizedDescription=Remote config data is corrupted}


![Screen Shot 2019-10-24 at 11 37 50 AM](https://user-images.githubusercontent.com/33837719/67506509-c71f9e00-f652-11e9-9b87-efb41bb31985.png)

**Comment by morganchen12** [comment]
@Bilonik can you share the full stack trace of the crash or a project that reproduces the issue?

**Comment by Bilonik** [comment]
Does this helps?
Its crash after ~10 secs of opening the app. this is after a complete wipe of the emulator.

![Screen Shot 2019-10-24 at 12 31 03 PM](https://user-images.githubusercontent.com/33837719/67510347-5ed4ba80-f65a-11e9-979e-d45b88060262.png)

**Comment by paulb777** [comment]
The log message doesn't look related to the backtrace?

**Comment by morganchen12** [comment]
@Bilonik, when the debugger stops at the line where the crash occurs, can you run `bt all` in the debugger and paste the results here?

**Comment by Heltisace** [comment]
I guess I'm having a similar issue.
To reproduce, try launching an application with nanopb 0.3.901 and after it updating application to nanopb 0.3.904. It looks like some sort of compatibility issue.

Updating to 0.3.9011 and then completely rebuilding the project seems to solve the problem, though.

**Comment by PetrVasilev** [comment]
I have the same error

**Comment by nachourpi** [comment]
The same for me and I'm not finding any way to even disable Firebase Analytics

**Comment by AbbanMustafa** [comment]
@Bilonik did you find a solution?

**Comment by vincenzo-favara** [comment]
Same problem here. no update?

**Comment by morganchen12** [comment]
If you're running into the same crash, please share a stack trace of the crash.
