### ISSUE TITLE
"Could not build module 'nanopb'

### ISSUE THREAD

**Issue by DallasHoelscher** [firebase/firebase-ios-sdk#417]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: _____
  * Firebase SDK version: _4.5____
  * Firebase Component: __Firestore___ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: __0.9.1___

### [REQUIRED] Step 3: Describe the problem
When trying to build I get errors: 
ERROR "Could not build module 'nanopb'
And "Unknown type name 'FOUNDATION_EXPORT'"
My project will build if I don't include firestore in my pod file.

#### Relevant Code:
Podfile: 
```
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
```

![image](https://user-images.githubusercontent.com/14352622/32210909-1e88bdca-bdde-11e7-8227-19aa31c1578e.png)

**Comment by paulb777** [comment]
Thanks to this [stackoverflow answer](https://stackoverflow.com/a/47033890/556617).

Firestore requires at least CocoaPods 1.2.0 because of its gRPC dependency which depends on the fix for https://github.com/CocoaPods/CocoaPods/issues/6024
