### ISSUE TITLE
Hi,  reCAPTCHA flow on ios 13 is not working on lastest sdk.

### ISSUE THREAD

**Issue by AbubakerMajeed** [firebase/firebase-ios-sdk#4177]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: _____
  * Firebase SDK version: _____
  * Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by rizafran** [comment]
Hi @AbubakerMajeed, thanks for filing a report. However, I couldn't identify what's causing the issue here. To replicate, please provide the following information required from the template:

- Firebase SDK version used / Podfile.lock file
- Detailed steps to reproduce the issue
- Screenshot / complete error logs (if any)
- Relevant code / [MCVE](https://stackoverflow.com/help/mcve) that I can run locally

**Comment by AbubakerMajeed** [comment]
Firebase sdk : Firebase/Auth (6.11.0)
 ReCaptcha is not working, go to simulator, try using phone auth , it will take user to safariviewcontroller, then after ReCaptcha autoverifcation. screen stays there. 

PhoneAuthProvider.provider(auth: Auth.auth())
        PhoneAuthProvider.provider().verifyPhoneNumber(phoneNumber, uiDelegate: nil) { (result, error) in
            if let _ = error {
                completion(false, nil , nil )
                return
            }
            completion(true , phoneNumber , result)
        }

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-10-28 at 14 35 36](https://user-images.githubusercontent.com/5495809/67686477-93c57200-f9b8-11e9-80b9-02668b2d6562.png)

**Comment by morganchen12** [comment]
@AbubakerMajeed, the code you've shared is not enough to reproduce the issue. Please upload a sample project that exhibits the error you're describing.

**Comment by AbubakerMajeed** [comment]
@morganchen12  this is exactly the code, when you implement firebase otp service, you need to verify number first. above sample code is doing same. but problem is after ReCaptcha verification, screen stay there not take user back to application.

**Comment by rizafran** [comment]
Hi @AbubakerMajeed Upon investigating, I was able to replicate the issue which it didn't automatically take back to the app. However, based on the [documentation](https://firebase.google.com/docs/auth/ios/phone-auth#appendix:-using-phone-sign-in-without-swizzling), I added the following code in SceneDelegate.swift to handle redirect URL and the issue has gone:
```
func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
for urlContext in URLContexts {
     let url = urlContext.url
     Auth.auth().canHandle(url)
     }
}
```
You may try to add it in your SceneDelegate.swift file and see if it works on your end.

**Comment by AbubakerMajeed** [comment]
But i am not using swift UI, my app support ios 11 to onwards. This issue can be duplicated on ios12 too.

**Comment by rizafran** [comment]
@AbubakerMajeed Could you try to check if you have a SceneDelegate.swift in your project file? If so, you may add the code snippet I provided [here](https://github.com/firebase/firebase-ios-sdk/issues/4177#issuecomment-547476399) and see if the issue persists.

**Comment by AbubakerMajeed** [comment]
Did you try on simulator? recapctha process is not working in any case.

**Comment by AbubakerMajeed** [comment]
My project is running from last 4 years. and it start with xcode older version. I do added "SceneDelegate.swift" of you request. Although it specifically requires me available check. but its not working in simulator. It stuck on white screen. As shown above.

**Comment by rizafran** [comment]
Hi @AbubakerMajeed thanks for clarifying. Yes, I'm using a simulator (iOS 12 and 13). I tried running the [Auth quickstart for iOS](https://github.com/firebase/quickstart-ios/tree/master/authentication) which doesn't have a SceneDelegate.swift file, but I can't seem to get the same issue. It would be great if you can share a [minimal repro](https://stackoverflow.com/help/mcve) of your app that I can run locally to reproduce the issue.

**Comment by AbubakerMajeed** [comment]
strange it quick easy to produce, I will share a repo with you today. Although i shifted to another otp sms solution. but it great if we have a fix.

**Comment by rizafran** [comment]
Hi @AbubakerMajeed apologies, but I can't reproduce the behavior you encountered so I asked for an [MCVE](https://stackoverflow.com/help/mcve) in order to replicate it on my end and determine what's causing it.

**Comment by AbubakerMajeed** [comment]
[testfirebase.zip](https://github.com/firebase/firebase-ios-sdk/files/3826574/testfirebase.zip)

here is demo code, just run app and click on "SignIn with defaultnumber".

**Comment by rizafran** [comment]
Thanks for sharing an MCVE @AbubakerMajeed.

I tried running your app and the reCAPTCHA didn't show. However, when I tried to change the GoogleService-Info.plist file with the copy from my project, the reCAPTCHA worked as intended. I'll consult this internally to see what's causing the issue.

**Comment by rizafran** [comment]
@AbubakerMajeed May I know if you have tried to re-download and update your GoogleService-Info.plist file?

**Comment by AbubakerMajeed** [comment]
this is latest download googleservicer-info plist. For above code(recaptch point) please run on any simulator, not on device.

**Comment by rizafran** [comment]
Hi @AbubakerMajeed, apologies for the late response. May I know if you're not using [Google Identity Toolkit](https://developers.google.com/identity/toolkit)?

**Comment by AbubakerMajeed** [comment]
No, i am not using identity toolkit. Using only firebase phoneauth.

**Comment by rizafran** [comment]
Thanks for the info @AbubakerMajeed. I've forwarded this to the Auth team, and will let you know once I have an update.

**Comment by juergengunz** [comment]
any update on this?

**Comment by Nodirbek-Sharipov** [comment]
I had similar issue, try using VPN. Firebase seems to have some limitations to users trying to spam from same IP, default sign up quota is 100 times/hr, but not sure about default login quota for same device with same IP

**Comment by paulb777** [comment]
The conversation looks to be dropped here. Sorry about that. Is this still an issue?

**Comment by AbubakerMajeed** [comment]
no solved; being ignore... move to another service...

**Comment by morganchen12** [comment]
For anyone running into a similar issue, please try the steps mentioned above:

- Implement the [SceneDelegate method](https://github.com/firebase/firebase-ios-sdk/issues/4177#issuecomment-547476399) to handle URL redirects
- Re-download your GoogleService-Info.plist file

If both of these steps fail, please file an issue to [Firebase Support](http://firebase.google.com/support).

Given the limited number of reports and our inability to reproduce the issue with the sample project from @AbubakerMajeed and our own quickstart, I'm going to _tentatively_ conclude that this was a configuration issue and does not require SDK code changes, but again if you're encountering this issue please file a ticket at support and we'll take a look.
