### ISSUE TITLE
Firestore cloud function not available on  Location

### ISSUE THREAD

**Issue by Abhishek-kumar09** [firebase/firebase-ios-sdk#4187]
I am setting a new Firebase Firestore cloud for my project. I am from India and requires South-Asia1 for location But this location is having problem like cloud functions not enabled. 
What should I do now, Should I go with my SouthAsia1 or change to nearest CloudFunctions location.
[![Deploying a function to this location is not available][1]][1]

  [1]: https://i.stack.imgur.com/TXBHt.png

What does it mean that  Deploying a function to this location is not yet available.
I am using firebase on android with flutter.

**Comment by rizafran** [comment]
Hi @Abhishek-kumar09, it means that Cloud Functions is not yet available in "[asia-south1](https://cloud.google.com/about/locations/?tab=asia-pacific)" location. If you're going to use Cloud Functions, the nearest region that can be used for it is "asia-east2". You may check out this [documentation](https://firebase.google.com/docs/functions/locations#selecting-regions_firestore-storage) for more info. 

You may also file on [Firebase Support page](https://firebase.google.com/support/) to better assist you with questions regarding this.

**Comment by Abhishek-kumar09** [comment]
So I should go with SouthAsia1 or asia-east2.As it is saying once i pick a location that cannot be changed

**Comment by Abhishek-kumar09** [comment]
Can I have my firestore location and cloud function location different
thanks @rizafran

**Comment by rizafran** [comment]
Hi @Abhishek-kumar09, as I've mentioned earlier, if you're going to use Cloud Functions, you'll need to use "asia-east2" which is the [nearest region](https://firebase.google.com/docs/functions/locations#selecting-regions_firestore-storage) available in "asia-south1" (Mumbai). Take note that you could potentially experience increased latency and billing costs if your function and resource are in different locations.

If you're going to use Firestore only, then you can go with "asia-south1".
