### ISSUE TITLE
[BUG] RemoteConfig fetched wrong values

### ISSUE THREAD

**Issue by VedranVClover** [firebase/firebase-ios-sdk#4206]
### [READ] Step 1: Are you in the right place?

Yes.

### [REQUIRED] Step 2: Describe your environment

Xcode: Version 11.1 (11A1027)
iOS version: 13.1.3
A released application on the Apple App store.

### [REQUIRED] Step 3: Describe the problem

We have an application in the App Store that uses Remote Config to fetch feature flags and it seems some users filed issues with certain features being disabled, even though they shouldn't be.
As a way of debugging this, we created event logging using Mixpanel, and indeed it seems for certain users the values aren't correct.
Moving on, we created a .plist file holding default values, ensuring the flags are enabled by default, however, this only works until RemoteConfig fetches values from remote, which doesn't help if RemoteConfig fetches incorrect values from remote.

We get: successFetchedFromRemote from remote status, but all the flags fetched are false when querying the RemoteConfig.remoteConfig() object. This is visible to us in the Mixpanel.

#### Steps to reproduce:

This is a though one, because we haven't encountered this issues when debugging applications from Xcode. Also, it seems that RemoteConfig works fine for certain users. Also the effected users have various devices, the iOS version on the devices is 13.1.3, however there are also users with the same iOS devices that aren't encountering this issues.

#### Relevant Code:

This function is called at each app start.
```
   func fetchValues() {
       self.remoteConfig.fetchAndActivate { status, error in
           if let error = error {
               NSLog("RemoteConfig fetching error: \(error.localizedDescription) ")
           }

           var statusString: String!

           switch status {
           case .successFetchedFromRemote:
               self.remoteConfigFetched()
               statusString = "sucess fetched from remote"
           case .successUsingPreFetchedData:
               statusString = "sucess using pre-fetched data"
           case .error:
               statusString = "error fetching"
           }

         // This code created Data to be sent to Mixpanel, with flag updates, the constants are just strings
           let currentValues = [RemoteConfigManager.featureFlagA : self.remoteConfig[RemoteConfigManager.featureFlagA].boolValue,
                                RemoteConfigManager.featureFlagB : self.remoteConfig[RemoteConfigManager.featureFlagB].boolValue,
                                RemoteConfigManager.featureFlagC : self.remoteConfig[RemoteConfigManager.featureFlagC].boolValue]

           NSLog("\(kKatanaLogPrefix) RemoteConfig fetched with status: \(statusString!)")
           MixpanelManager.instance.onRemoteConfigFetched(status: statusString, values: currentValues)
       }
   }
```

**Comment by dmandar** [comment]
Hi, what is the RemoteConfig SDK version? Can you share the podfile lock?

**Comment by VedranVClover** [comment]
I can share snippets from podfile.lock relevant:

PODS:
  - Alamofire (4.9.0)
  - Bolts (1.9.0):
    - Bolts/AppLinks (= 1.9.0)
    - Bolts/Tasks (= 1.9.0)
  - Bolts/AppLinks (1.9.0):
    - Bolts/Tasks
  - Bolts/Tasks (1.9.0)
  - BoringSSL-GRPC (0.0.3):
    - BoringSSL-GRPC/Implementation (= 0.0.3)
    - BoringSSL-GRPC/Interface (= 0.0.3)
  - BoringSSL-GRPC/Implementation (0.0.3):
    - BoringSSL-GRPC/Interface (= 0.0.3)
  - BoringSSL-GRPC/Interface (0.0.3)
  - Crashlytics (3.11.1):
    - Fabric (~> 1.8.1)
  - Fabric (1.8.2)
  - FBSDKCoreKit (4.44.1):
    - Bolts (~> 1.9)
  - FBSDKLoginKit (4.44.1):
    - FBSDKCoreKit
  - Firebase/Analytics (6.10.0):
    - Firebase/Core
  - Firebase/Auth (6.10.0):
    - Firebase/CoreOnly
    - FirebaseAuth (~> 6.3.0)
  - Firebase/Core (6.10.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.1.3)
  - Firebase/CoreOnly (6.10.0):
    - FirebaseCore (= 6.3.1)
  - Firebase/Database (6.10.0):
    - Firebase/CoreOnly
    - FirebaseDatabase (~> 6.1.1)
  - Firebase/Firestore (6.10.0):
    - Firebase/CoreOnly
    - FirebaseFirestore (~> 1.6.0)
  - Firebase/InAppMessagingDisplay (6.10.0):
    - Firebase/CoreOnly
    - FirebaseInAppMessagingDisplay (~> 0.15.5)
  - Firebase/Messaging (6.10.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 4.1.6)
  - Firebase/Performance (6.10.0):
    - Firebase/CoreOnly
    - FirebasePerformance (~> 3.1.5)
  - Firebase/RemoteConfig (6.10.0):
    - Firebase/CoreOnly
    - FirebaseRemoteConfig (~> 4.4.2)
  - Firebase/Storage (6.10.0):
    - Firebase/CoreOnly
    - FirebaseStorage (~> 3.4.1)
  - FirebaseABTesting (3.1.2):
    - FirebaseAnalyticsInterop (~> 1.3)
    - FirebaseCore (~> 6.1)
    - Protobuf (>= 3.9.2, ~> 3.9)
  - FirebaseAnalytics (6.1.3):
    - FirebaseCore (~> 6.3)
    - FirebaseInstanceID (~> 4.2)
    - GoogleAppMeasurement (= 6.1.3)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 0.3.901)
  - FirebaseAnalyticsInterop (1.4.0)
  - FirebaseAuth (6.3.1):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 6.2)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.2)
    - GoogleUtilities/Environment (~> 6.2)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseAuthInterop (1.0.0)
  - FirebaseCore (6.3.1):
    - FirebaseCoreDiagnostics (~> 1.0)
    - FirebaseCoreDiagnosticsInterop (~> 1.0)
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/Logger (~> 6.2)
  - FirebaseCoreDiagnostics (1.1.1):
    - FirebaseCoreDiagnosticsInterop (~> 1.0)
    - GoogleDataTransportCCTSupport (~> 1.0)
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/Logger (~> 6.2)
    - nanopb (~> 0.3.901)
  - FirebaseCoreDiagnosticsInterop (1.0.0)
  - FirebaseDatabase (6.1.1):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 6.0)
    - leveldb-library (~> 1.22)
  - FirebaseFirestore (1.6.0):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 6.2)
    - FirebaseFirestore/abseil-cpp (= 1.6.0)
    - "gRPC-C++ (= 0.0.9)"
    - leveldb-library (~> 1.22)
    - nanopb (~> 0.3.901)
    - Protobuf (>= 3.9.2, ~> 3.9)
  - FirebaseFirestore/abseil-cpp (1.6.0):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 6.2)
    - "gRPC-C++ (= 0.0.9)"
    - leveldb-library (~> 1.22)
    - nanopb (~> 0.3.901)
    - Protobuf (>= 3.9.2, ~> 3.9)
  - FirebaseInAppMessaging (0.15.5):
    - FirebaseAnalyticsInterop (~> 1.3)
    - FirebaseCore (~> 6.2)
    - FirebaseInstanceID (~> 4.0)
    - GoogleDataTransportCCTSupport (~> 1.0)
  - FirebaseInAppMessagingDisplay (0.15.5):
    - FirebaseCore (~> 6.2)
    - FirebaseInAppMessaging (>= 0.15.0)
  - FirebaseInstanceID (4.2.6):
    - FirebaseCore (~> 6.0)
    - GoogleUtilities/Environment (~> 6.0)
    - GoogleUtilities/UserDefaults (~> 6.0)
  - FirebaseMessaging (4.1.6):
    - FirebaseAnalyticsInterop (~> 1.3)
    - FirebaseCore (~> 6.2)
    - FirebaseInstanceID (~> 4.1)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.2)
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/Reachability (~> 6.2)
    - GoogleUtilities/UserDefaults (~> 6.2)
    - Protobuf (>= 3.9.2, ~> 3.9)
  - FirebasePerformance (3.1.5):
    - FirebaseCore (~> 6.3)
    - FirebaseInstanceID (~> 4.2)
    - FirebaseRemoteConfig (~> 4.4)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/ISASwizzler (~> 6.2)
    - GoogleUtilities/MethodSwizzler (~> 6.2)
    - GTMSessionFetcher/Core (~> 1.1)
    - Protobuf (~> 3.9)
  - FirebaseRemoteConfig (4.4.2):
    - FirebaseABTesting (~> 3.1)
    - FirebaseAnalyticsInterop (~> 1.4)
    - FirebaseCore (~> 6.2)
    - FirebaseInstanceID (~> 4.2)
    - GoogleUtilities/Environment (~> 6.2)
    - "GoogleUtilities/NSData+zlib (~> 6.2)"
    - Protobuf (>= 3.9.2, ~> 3.9)
  - FirebaseStorage (3.4.1):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 6.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - GoogleAppMeasurement (6.1.3):
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 0.3.901)
  - GoogleDataTransport (3.0.1)
  - GoogleDataTransportCCTSupport (1.2.1):
    - GoogleDataTransport (~> 3.0)
    - nanopb (~> 0.3.901)

...

DEPENDENCIES:
  - Alamofire (~> 4.7)
  - Bolts (~> 1.0)
  - Crashlytics (~> 3.11.1)
  - Fabric (~> 1.8.2)
  - FBSDKCoreKit (~> 4.0)
  - FBSDKLoginKit (~> 4.0)
  - Firebase/Analytics
  - Firebase/Auth (~> 6.0)
  - Firebase/Core (~> 6.0)
  - Firebase/Database (~> 6.0)
  - Firebase/Firestore
  - Firebase/InAppMessagingDisplay
  - Firebase/Messaging (~> 6.0)
  - Firebase/Performance (~> 6.0)
  - Firebase/RemoteConfig (~> 6.0)
  - Firebase/Storage (~> 6.0)
  - GoogleMaps (~> 3.0)
  - GooglePlaces (~> 3.0)
  - GoogleSignIn (~> 4.0)
  - KeychainSwift (~> 16.0)
  - Mixpanel-swift (~> 2.0)
  - PhoneNumberKit (~> 2.1)
  - SDWebImage (~> 3.8)
  - Stripe (~> 14.0)
  - SwiftyJSON (from `https://github.com/SwiftyJSON/SwiftyJSON.git`)
  - TwitterKit (~> 3.0)

The issue appeared only on version 13.1.3 so far, however not for all users. Target conditions, meaning versions?

**Comment by dmandar** [comment]
Hi, we are not able to repro this yet. Is everyone able to repro only using 13.1.3? Also, is everybody using the same fetchAndActive API? Note that a fetchWithCOmpletionHandler call returns success even if the request has been served from cache.
