### ISSUE TITLE
CurrentUser is Anonymous with ProviderData after linking with phone

### ISSUE THREAD

**Issue by vince105** [firebase/firebase-ios-sdk#421]
### Environment

  * Xcode version: 9.1
  * Firebase SDK version: 4.5.0
  * Firebase Component: Auth
  * Component version: 4.3.1

### Problem

I have a user signed in anonymously. After getting a `verificationID` and a `verificationCode`, I link a phone credential to the user. After the credential is successfully linked, the user remains anonymous but has `providerData` with a `providerID` "phone.

This is fixed if the user signs out then signs in with `Auth.auth().signIn(with: _, completion: _)`.

#### Steps to reproduce:

According to the [docs](https://firebase.google.com/docs/auth/ios/anonymous-auth), in order to convert a user from anonymous to permanent a credential must be linked.

So I sign the user in anonymously, link a valid phone credential and get a success message. But when the user is checked, they have `providerData` for the phone and is still anonymous.

I have also tried downgrading the auth SDK to 4.2.1 with no luck.

#### Relevant Code:
```
import FirebaseAuth

let credential = PhoneAuthProvider.provider().credential(withVerificationID: verificationID, verificationCode: verificationCode)

Auth.auth().currentUser?.link(with: credential, completion: { [weak self] (user, error) in
     // Link is successful but user is still anonymous and there is provider data
})
```

**Comment by protocol86** [comment]
Hi @vince105,

Thanks for pointing this issue out, a fix is already in review.

**Comment by vince105** [comment]
@protocol86 That's great! Thank you for the quick fix.

**Comment by morganchen12** [comment]
This fix was released today.
