### ISSUE TITLE
【FIRDynamicLink】How to fetch user-added custom parameters?

### ISSUE THREAD

**Issue by fangyuxi** [firebase/firebase-ios-sdk#4215]
FIRDynamicLink

I have created a Dynamiclink in the FIRDynamicLink Console, for example

https://xxx.page.link/XktS

But if I want the user to pass a custom parameter when user click, for example https://xxx.page.link/XktS?a=b,

I want to get the value of the parameter named a, value b, how to do it? I checked all the relevant documentation and instructional videos and didn't get an answer.

I know that I can set parameters through my own domain （https://www.xxx.com/index.html?a=b）, but once this parameter is set in the console, it can't be modified. But I want the user to pass some custom information.

Sorry for using the wrong format, thank you.

**Comment by morganchen12** [comment]
When building a custom dynamic link, your user can attach normal parameters to the end of the link that can then be fetched from the query in iOS's universal link handler. 

```swift
func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([Any]?) -> Void) -> Bool {
    if userActivity.activityType == NSUserActivityTypeBrowsingWeb {
        guard let url = userActivity.webpageURL,
              let components =  URLComponents(url: url, resolvingAgainstBaseURL: false) else {
            // Unable to parse URL components.
            return false
        }

        if let queryItems = components.queryItems {
            // Fetch the custom parameters from the URL's query items.
            // See Apple's docs: https://developer.apple.com/documentation/foundation/urlcomponents/1779966-queryitems
        } else {
            // No query items for this URL.
        }
        return true
    }

    return false
}
```

It's worth noting this is all non-Firebase functionality, just iOS's default universal links functionality.

**Comment by fangyuxi** [comment]
@morganchen12 

Thank you , I know user can attach normal parameters to the end of the link that can then be fetched from the query in iOS's universal link handler.


But when user launch app first time (https://xxx.page.link/XktS?a=b,),

this method will be called. 
```
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication
         annotation:(id)annotation {
    
    
    
  FIRDynamicLink *dynamicLink = [[FIRDynamicLinks dynamicLinks] dynamicLinkFromCustomSchemeURL:url];

  if (dynamicLink) {
    if (dynamicLink.url) {
      // Handle the deep link. For example, show the deep-linked content,
      // apply a promotional offer to the user's account or show customized onboarding view.
      // ...
    } else {
      // Dynamic link has empty deep link. This situation will happens if
      // Firebase Dynamic Links iOS SDK tried to retrieve pending dynamic link,
      // but pending link is not available for this device/App combination.
      // At this point you may display default onboarding view.
    }
    return YES;
  }
  return NO;
}
```

I can not grab custom(a=b)  parameters this time.
Only the following parameters can be obtained

```
{
    "deep_link_id" = "https://xxx.com/index.html?d=1";
    "match_message" = "Best (of many) pre-install links matched for this device.";
    "match_type" = weak;
    "request_ip_version" = "IP_V4";
    "utm_medium" = "dynamic_link";
    "utm_source" = firebase;
}
```

I tried using a full link, similar

```
https://xxx.page.link/?link=https://xx.com/index.html?d%3D1&isi=234324234&ibi=com.xx.xxx&efr=1&a=b
```

When using the full link, as you said, I can get the custom parameter of a=b through the universal link, but the first time app launch  I still can't get it (a=b).

**Comment by fangyuxi** [comment]
I have a solution.
First, give the user a webpage that we developed ourselves. When the user clicks into the webpage, use the restful api to dynamically create a specific dynamic link. Then the user clicks on the link and then opens the AppStore to download the app.

**Comment by morganchen12** [comment]
In either case, is the full deep link (including parameters) stored in `deep_link_id`?

**Comment by fangyuxi** [comment]
If the app is not installed, then when the user clicks on full link or short link, firebase will record user feature information. When the app is first installed and opened, firebase will collect the same user information to compare with google server. If the comparison is successful, Then it means the same user, then call [sourceApplication:(NSString *)sourceApplication] .. method. At this time, other parameters cannot be carried because the comparison is not 100% accurate.

When the app is already installed, if the user clicks on the full link, then the iOS's universal link is actually working. If you add other parameters after the full link, you can get it by the app handle.

If the app is already installed, when the user clicks on the short link, the same is true, iOS's universal link is working, but if you add a custom parameter after the short link, it cannot be obtained by the handle because When the short link is passed to the app, the firebase sdk will get the parameters through the short link path to the firebase, so it don't include our custom parameters.

If you want to add a custom parameter to the short link, you need an intermediate page, use the restful api to generate a short link for the information related to the user who clicked. Then place a button in the middle page to guide the user to click, click on the button The short link generated by the restful api will be called, so that when the user downloads the app, the custom parameter can be obtained.

Hope to help

**Comment by morganchen12** [comment]
@dmandar is there a more direct way to achieve the same functionality?

**Comment by dmandar** [comment]
Hi, you can maybe use the FDL builder API to dynamically create FDL URLs in your app with all the necessary params? FDL short URLs are not intended to be modified or appended to.
