### ISSUE TITLE
FR: Firestore NOT operator in WHERE query

### ISSUE THREAD

**Issue by spourteymour** [firebase/firebase-ios-sdk#4216]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.0
  * Firebase SDK version: 6.5.0
  * Firebase Component: Firestore (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 6.5.0

#### Steps to reproduce:
When we are querying the content of a collection, we can't compare a value that is not the value in question. 

it would be great if we could do the query like:

```
var collectionRef = Firestore.firestore().collection("collection").whereField("fieldValue", isNotEqualTo: "Random String")
```
#### Relevant Code:

```
var collectionRef = Firestore.firestore().collection("collection").whereField("fieldValue", isEqualTo: "Random String")
```

**Comment by rockwotj** [comment]
Hello! Thanks for your suggestion, since the Firestore backend doesn't support this behavior, the clients can't either. Can you open up a Feature Request  against the backend [here](https://issuetracker.google.com/issues/new?component=530136&template=0)?
