### ISSUE TITLE
`FIRInAppMessagingCampaignInfo` missing `NS_SWIFT_NAME`

### ISSUE THREAD

**Issue by ryanwilson** [firebase/firebase-ios-sdk#4218]
`FIRInAppMessagingCampaignInfo` should be fixed with `NS_SWIFT_NAME` in order to remove the `FIR` prefix at the next breaking change.

https://github.com/firebase/firebase-ios-sdk/blob/b5b836670aa459b62be3ecdddf8f87e52dca9d08/Firebase/InAppMessaging/Public/FIRInAppMessagingRendering.h#L94

**Comment by morganchen12** [comment]
Moving to a minor release since FIAM is still on major version 0.

**Comment by paulb777** [comment]
@morganchen12 6.14.0 is already branched and passed code freeze. I reset to M62.
