### ISSUE TITLE
gRPC-Core Apple Mach O-Linker Errors after Xcode 9 Update

### ISSUE THREAD

**Issue by famAlex** [firebase/firebase-ios-sdk#423]
Hello there, 
starting with a clean new project, I used cocoapods to install the following:

`platform :ios, '8.0'
target 'My App' do
  use_frameworks!
  # Pods for My app
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'FirebaseUI/Auth', '~> 4.0'
    pod 'FirebaseUI/Google', '~> 4.0'
    pod 'FirebaseUI/Phone', '~> 4.0'
`

everything works fine, but adding `pod 'FirebaseFirestore', '~> 0.9'` results on errors you can see below. 

<img width="1012" alt="schermata 2017-11-03 alle 12 15 48" src="https://user-images.githubusercontent.com/13166743/32372009-622cacd2-c093-11e7-97bd-68236e7d908c.png">

I tried with several combinations of:
deleting Derived Data, 
Clean + Clean Build Folder
Enable Bitcode --> No

but nothing changed. Anyone else is experiencing the same issue or maybe am I making something wrong?
Kind regards
Alessandro

  * Xcode version: 9.0 and 9.1
  * Firebase SDK version: 4.5
  * Firebase Component: _____ (Auth, Core, Firestore, FirebaseUI)
  * Component version: 0.9.1

**Comment by paulb777** [comment]
Those missing symbols should be built as part of the grpc-Core build. For example -

> Pods/gRPC-Core/src/core/lib/support/string.c:int gpr_ltoa(long value, char *string) {

What version of CocoaPods are you using? At least 1.2.0 is required.

`pod --version`

**Comment by famAlex** [comment]
my pod version is 1.2.0

**Comment by goalguy10** [comment]
I am having the same exact issue. My pod version is 1.3.1

**Comment by morganchen12** [comment]
Can one of you upload a project that reproduces this?

**Comment by famAlex** [comment]
https://mega.nz/#!E9lVVLZJ!Q4uvfnYtOK6h9QoVCXkAOe7L2eGBeCYC0FRZAqr2W0U

I just created a new project, 
pod init,
added the pods ,
pod install
and run

But if you remove firestore pod, everything works again

**Comment by adornoventura** [comment]
I can confirm I'm having this same problem with both CocoaPods v. 1.2.0 and 1.3.1

**Comment by Lukaris** [comment]
I guess its just missing some coding in the grpc-core ..  I have the same problem XCode 9.2 Beta

**Comment by morganchen12** [comment]
Looks like an issue in gRPC-Core. For the time being you can work around this by putting

```ruby
pod 'gRPC', `1.6.5`
```

at the top of your Podfile.

**Comment by muxi** [comment]
gRPC has resolved the problem; the problem was due to inadvertent duplicated named ref 'v1.7.0' in gRPC repo. For those of you who had this problem, you can clean Cocoapods cache on gRPC related pods (gRPC-Core, gRPC, gRPC-ProtoRPC, gRPC-RxLibrary) then `pod install` again.

**Comment by paulb777** [comment]
gRPC 1.7.1 is now available that fixes the issue.

Thanks to everyone for the reports and to @muxi for the quick turnaround on the fix!
