### ISSUE TITLE
[NSKeyedArchiver archivedDataWithRootObject:requiringSecureCoding:error:] crash in [GDTCORStorage appWillBackground:]

### ISSUE THREAD

**Issue by xspyhack** [firebase/firebase-ios-sdk#4237]
### Environment
  * Xcode version: Xcode 10.3
  * Firebase SDK version: 6.10.0
  * Firebase Component: Messaging, Analytics
  * Component version: 6.10.0
  * GDT version: 3.0.1

### Problem
`Fatal Exception: NSInvalidArgumentException +[NSKeyedArchiver archivedDataWithRootObject:requiringSecureCoding:error:]: unrecognized selector sent to class  __35-[GDTCORStorage appWillBackground:]_block_invoke `

Guess the same as https://github.com/firebase/firebase-ios-sdk/issues/4209

**Comment by morganchen12** [comment]
@xspyhack can you share your iOS version as well? Is this issue consistently reproducible?

**Comment by xspyhack** [comment]
@morganchen12 This is iOS 11 only issue, and I don't think it is consistently reproducible.

**Comment by morganchen12** [comment]
Does it occur on jailbroken devices only?

**Comment by xspyhack** [comment]
Nope, most devices are iPhone 6 and in background.

**Comment by paulb777** [comment]
According to #4209, this issue only occurred on a beta version of iOS 11.  Please check that the issue occurs on a production version.

**Comment by xspyhack** [comment]
Thanks @paulb777, I'm pretty sure this issue only occurred on beta version of iOS 11.0(15A5327g).

**Comment by wwwhackcom** [comment]
Same issue,  crash every time, I am using iOS 11.0(15A5341f)

**Comment by hamedh** [comment]
i can confirm its happening on iOS 11.0.0 (15A5341f) as well
