### ISSUE TITLE
Firebase Performance logs too much when data collection disabled

### ISSUE THREAD

**Issue by xiao99xiao** [firebase/firebase-ios-sdk#4238]
* Xcode version: 11.2
  * Firebase SDK version: 6.11.0
  * Firebase Component: Preformance
  * Component version: 3.1.5

#### Steps to reproduce:

I have `isInstrumentationEnabled` & `isDataCollectionEnabled` set to false, then run the app from Xcode in Debug mode, Performance begins infinite logging complaining things like below
```
[Firebase/Performance][I-PRF100013] Dropping event since data collection is disabled.
```
One or two logs like that are usually ok. But currently, I got this line log **every 1 seconds**. Maybe it's because I have a timer that sends a network request every 1 seconds and Performance manages to monitor the request, but then find it should not collect the data, so it complains. Anyway, It makes log console in Xcode completely useless. 

#### Relevant Code:

in `func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool`
```
Performance.sharedInstance().isInstrumentationEnabled = false
Performance.sharedInstance().isDataCollectionEnabled = false
```

**Comment by visumickey** [comment]
@xiao99xiao Currently these are log messages that are displayed only on one of the higher levels of verbosity. Can you double check if you have a high level of verbosity. Check for environment variable "-FIRInfoEnabled" in your app's scheme definition?

When set to -FIRDebugEnabled, these load of log messages should not be seen.

**Comment by xiao99xiao** [comment]
@visumickey You are right, I set `-FIRDebugEnabled` and then the log was gone. Even after I removed that flag, the log still stays neat now.
Thanks you so much!
