### ISSUE TITLE
Crash at line -[GDTStorage encodeWithCoder:] in GDTStorage.m, line 268

### ISSUE THREAD

**Issue by alekseitsyss** [firebase/firebase-ios-sdk#4239]
Xcode version: 10.3

**Podfile.lock contents related to the Firebase:**
  - Firebase/Core (6.11.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.1.3)
  - Firebase/CoreOnly (6.11.0):
    - FirebaseCore (= 6.3.2)
  - Firebase/Firestore (6.11.0):
    - Firebase/CoreOnly
    - FirebaseFirestore (~> 1.6.1)
  - Firebase/Messaging (6.11.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 4.1.7)
  - FirebaseAnalytics (6.1.3):
    - FirebaseCore (~> 6.3)
    - FirebaseInstanceID (~> 4.2)
    - GoogleAppMeasurement (= 6.1.3)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 0.3.901)

**Problem:**
Multiple crashes in the Crashlytics.
GDTStorage.m line 268
-[GDTStorage encodeWithCoder:]

[crash.txt](https://github.com/firebase/firebase-ios-sdk/files/3808607/crash.txt)

**Comment by rizafran** [comment]
Seems related to #3623

**Comment by alekseitsyss** [comment]
> Seems related to #3623

That's right. The issue was expected to be addressed in 6.7.0. The other day 6.12 was released, but the issue is still there.

**Comment by paulb777** [comment]
GDTStorage was renamed to GDTCORStorage several releases ago.  Please make sure to update to a recent version of the GoogleDataTransport pod.

**Comment by alekseitsyss** [comment]
> GDTStorage was renamed to GDTCORStorage several releases ago. Please make sure to update to a recent version of the GoogleDataTransport pod.

Thank you!
