### ISSUE TITLE
FR: FirebaseInstanceID macOS support

### ISSUE THREAD

**Issue by gregbzh** [firebase/firebase-ios-sdk#424]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.0.1
  * Firebase SDK version: n/a
  * Firebase Component: Messaging
  * Component version:

#### Steps to reproduce:

I am currently porting Messaging on macOS. Unfortunately the FirebaseInstanceID has not been compiled for macOS. Since FirebaseInstanceID is not open source, it could be nice to add macOS support to FirebaseInstanceID.

**Comment by paulb777** [comment]
Should be easily feasible after #186

**Comment by morganchen12** [comment]
Fixed in #2880.
