### ISSUE TITLE
Crashed: com.google.GDTCCTPrioritizer

### ISSUE THREAD

**Issue by peacemoon** [firebase/firebase-ios-sdk#4240]
### [READ] Step 1: Are you in the right place?
yes

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.1
  * Firebase SDK version: 6.9.0
  * Firebase Component: Core, Messaging, Analytics, InAppMessaging
  * Component version: 6.9.0

#### Steps to reproduce:
We have a lot of crash report regarding com.google.GDTCCTPrioritizer
````
Crashed: com.google.GDTCCTPrioritizer
0  libdyld.dylib                  0x1b53056c0 dyld3::closure::ObjCStringTable::hash(char const*, unsigned long) const + 16
1  libdyld.dylib                  0x1b5305cd4 dyld3::closure::ObjCStringTable::getIndex(char const*) const + 52
2  libdyld.dylib                  0x1b5305b54 dyld3::closure::ObjCClassOpt::forEachClass(char const*, dyld3::Array<std::__1::pair<unsigned long, unsigned long> > const&, void (void*, bool, bool*) block_pointer) const + 52
3  libdyld.dylib                  0x1b53124f8 dyld3::AllImages::forEachObjCClass(char const*, void (void*, bool, bool*) block_pointer) const + 132
4  libobjc.A.dylib                0x1b5244c38 getPreoptimizedClass + 148
5  libobjc.A.dylib                0x1b522f8d8 getClassExceptSomeSwift(char const*) + 20
6  libobjc.A.dylib                0x1b5230784 look_up_class + 100
7  CoreFoundation                 0x1b545c19c __NSSetEnumerate + 136
8  CoreFoundation                 0x1b53f14fc -[NSSet objectsWithOptions:passingTest:] + 196
9  xxxxxxx                        0x102f3d370 -[GDTCCTPrioritizer logEventsOkToSendOnMobileData] + 4311847792
10 xxxxxxx                        0x102f3d134 __49-[GDTCCTPrioritizer uploadPackageWithConditions:]_block_invoke + 4311847220
11 libdispatch.dylib              0x1b51ce184 _dispatch_client_callout + 16
12 libdispatch.dylib              0x1b51b1dd8 _dispatch_lane_barrier_sync_invoke_and_complete + 56
13 xxxxxxx                        0x102f3d0cc -[GDTCCTPrioritizer uploadPackageWithConditions:] + 4311847116
14 xxxxxxx                        0x102f4845c __52-[GDTCORUploadCoordinator uploadTargets:conditions:]_block_invoke + 4311893084
15 libdispatch.dylib              0x1b51cd610 _dispatch_call_block_and_release + 24
16 libdispatch.dylib              0x1b51ce184 _dispatch_client_callout + 16
17 libdispatch.dylib              0x1b51ab73c _dispatch_lane_serial_drain$VARIANT$armv81 + 564
18 libdispatch.dylib              0x1b51ac154 _dispatch_lane_invoke$VARIANT$armv81 + 400
19 libdispatch.dylib              0x1b51b543c _dispatch_workloop_worker_thread + 576
20 libsystem_pthread.dylib        0x1b521dfa4 _pthread_wqthread + 276
21 libsystem_pthread.dylib        0x1b5220ae0 start_wqthread + 8
````

#### Relevant Code:

It seems to be an iOS 13 issue only according to Crashlytics.

**Comment by mikehaney24** [comment]
Make sure to update your cocopoads, also, which specific version of iOS 13?

**Comment by peacemoon** [comment]
We install Firebase manually.

In the screenshot are the distribution of iOS 13 where the crashes occur.

![Screenshot 2019-11-06 at 22 53 29](https://user-images.githubusercontent.com/478757/68341220-4ba8fc80-00e8-11ea-90ba-af1410c0056d.png)

**Comment by mikehaney24** [comment]
Ok, make sure to update your libraries.

Thanks for showing us the distribution, but you need to update to the latest version of GoogleDataTransport and GoogleDataTransportCCTSupport before I look more into this.

**Comment by mikehaney24** [comment]
After updating the libraries, is this still an issue?

**Comment by peacemoon** [comment]
We have just updated the libs to the newest version and waiting for release. I need some days to gather the logs.

**Comment by peacemoon** [comment]
Ok, I have updated all libs to 6.12.0 release. And our newly released app is still reporting the same error

    Crashed: com.google.GDTCCTPrioritizer
    0  libdyld.dylib                  0x19f6c96c0 dyld3::closure::ObjCStringTable::hash(char const*, unsigned long) const + 16
    1  libdyld.dylib                  0x19f6c9cd4 dyld3::closure::ObjCStringTable::getIndex(char const*) const + 52
    2  libdyld.dylib                  0x19f6c9b54 dyld3::closure::ObjCClassOpt::forEachClass(char const*, dyld3::Array<std::__1::pair<unsigned long, unsigned long> > const&, void (void*, bool, bool*) block_pointer) const + 52
    3  libdyld.dylib                  0x19f6d64f8 dyld3::AllImages::forEachObjCClass(char const*, void (void*, bool, bool*) block_pointer) const + 132
    4  libobjc.A.dylib                0x19f608c38 getPreoptimizedClass + 148
    5  libobjc.A.dylib                0x19f5f38d8 getClassExceptSomeSwift(char const*) + 20
    6  libobjc.A.dylib                0x19f5f4784 look_up_class + 100
    7  CoreFoundation                 0x19f82019c __NSSetEnumerate + 136
    8  CoreFoundation                 0x19f7b54fc -[NSSet objectsWithOptions:passingTest:] + 196
    9  PAYBACK                        0x1012fd23c -[GDTCCTPrioritizer logEventsOkToSendOnMobileData] + 4374811196
    10 PAYBACK                        0x1012fd050 __49-[GDTCCTPrioritizer uploadPackageWithConditions:]_block_invoke + 4374810704
    11 libdispatch.dylib              0x19f592184 _dispatch_client_callout + 16
    12 libdispatch.dylib              0x19f544c44 _dispatch_lane_barrier_sync_invoke_and_complete + 56
    13 xxxx                        0x1012fcfe8 -[GDTCCTPrioritizer uploadPackageWithConditions:] + 4374810600
    14 xxxxx                        0x101308d68 __52-[GDTCORUploadCoordinator uploadTargets:conditions:]_block_invoke + 4374859112
    15 libdispatch.dylib              0x19f591610 _dispatch_call_block_and_release + 24
    16 libdispatch.dylib              0x19f592184 _dispatch_client_callout + 16
    17 libdispatch.dylib              0x19f53e464 _dispatch_lane_serial_drain$VARIANT$mp + 608
    18 libdispatch.dylib              0x19f53ee58 _dispatch_lane_invoke$VARIANT$mp + 420
    19 libdispatch.dylib              0x19f548340 _dispatch_workloop_worker_thread + 588
    20 libsystem_pthread.dylib        0x19f5e1fa4 _pthread_wqthread + 276
    21 libsystem_pthread.dylib        0x19f5e4ae0 start_wqthread + 8

**Comment by mikehaney24** [comment]
Are you running into this issue in iOS 13.2? After looking into this more, it looks like this might be an iOS known issue.

https://forums.developer.apple.com/thread/122858

https://stackoverflow.com/questions/58215486/debugging-sporadic-app-crashes-with-dylib-in-ios13-ipados-13

https://forums.developer.apple.com/thread/123728

https://forums.developer.apple.com/message/384064#384064

**Comment by peacemoon** [comment]
It seems to be legit. Our app has Data protection enabled. 
You can close the ticket if you want because I also have no idea how to really reproduce the crash.

**Comment by mikehaney24** [comment]
Hard to say, there's a lot of different repro steps in all those links. I'd start with the simplest I found:

> 1. When app is running, lock the phone
> 
> 2. Do mobile call and receive on device
> 
> 3. The app goes to background and crash.

If that works, then that SO link might provide a solution that you can verify.
