### ISSUE TITLE
Firebase Analytics + GTM unexpected behaviour 

### ISSUE THREAD

**Issue by cooksimo** [firebase/firebase-ios-sdk#4247]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.3
  * Firebase SDK version: 6.8.1
  * Firebase Component: Analytics + GTM
  * Component version: 6.8.1

### [REQUIRED] Step 3: Describe the problem

When using Firebase Analytics + GTM we are seeing some strange behaviour. Specifically, firing an event that triggers a tag that includes a Firebase User Property variable that currently has no value (eg the user id, when a user isn't logged in). The resulting analytics hit sends "undefined" as the value to GA. When using an Event Parameter in a tag any parameters with no value are stripped out of the GA hit.

I would have expected this behaviour to be consistent, is this a bug or is that how it is intended to work?

Secondly, when using GTM via Firebase there seems to be no way to control the logging that GTM sends out, and there is a lot of logging going on (especially with the Firebase automatic screen reporting enabled). Is there a way to change the log level or suppress these messages?

**Comment by paulb777** [comment]
Is this still an issue with Firebase 7.x?
