### ISSUE TITLE
error installing on device via Carthage

### ISSUE THREAD

**Issue by pives** [firebase/firebase-ios-sdk#4255]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: Version 11.2 
  * Firebase SDK version:  latest via carthaeg binaries as of Nov 5 
  * Firebase Component: MLVision (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: _____

#### Steps to reproduce:

Error installing on Device or Simulator. (via Carthage builds found https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md) 

my cartfile: 
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAuthBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseMLVisionAutoMLBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseMLVisionBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseMLVisionLabelModelBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseMLVisionObjectDetectionBinary.json"
```
#### Relevant Code:

```
Found bundle at /Users/****/Library/Developer/CoreSimulator/Devices/0B410098-621C-4E87-A4A6-8114F3696173/data/Library/Caches/com.apple.mobile.installd.staging/temp.0P5Ot4/extracted/MeetKaiApp.app/Frameworks/FirebaseMLVisionObjectDetection.framework with the same identifier (com.firebase.Firebase) as bundle at /Users/****/Library/Developer/CoreSimulator/Devices/0B410098-621C-4E87-A4A6-8114F3696173/data/Library/Caches/com.apple.mobile.installd.staging/temp.0P5Ot4/extracted/MeetKaiApp.app/Frameworks/FirebaseMLVisionLabelModel.framework
```
installed via Carthage. 
it seems that both these frameworks have teh same identifier

**Comment by paulb777** [comment]
I suspect this step was missed in the instructions:

- Please note that you shouldn't add the Firebase frameworks to the Carthage build phase (copy-frameworks). The frameworks contain static libraries that are linked at build time.

**Comment by pives** [comment]
I thought it was only the Firebase.framework that should not be added.. Is this not the case? @paulb777

**Comment by pives** [comment]
@paulb777 you are correct one of the framework files snuck into my copy frameworks script on last build. :/
