### ISSUE TITLE
[BUG] FirebaseApp.allApps returns only apps configured within the same module

### ISSUE THREAD

**Issue by valzevul** [firebase/firebase-ios-sdk#4263]
### [READ] Step 1: Are you in the right place?
Yes.

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.1
  * Firebase SDK version: 6.1.0
  * Firebase Component: Core
  * Component version: 6.1.0

#### Steps to reproduce:

`FirebaseApp.allApps` returns only apps configured within the same module. So if there are multiple modules (`moduleMain`, `moduleNetwork`, `moduleAuth`) and the FIR instance is created in `moduleMain`, calling `FirebaseApp.allApps` returns `nil` when called from `moduleNetwork` or `moduleAuth`.

#### Expected behaviour:
`FirebaseApp.allApps` should return all apps instantiated within the project, not a module.

**Comment by paulb777** [comment]
What exactly do you mean by "module"?

**Comment by valzevul** [comment]
@paulb777 module as in a separate framework within the project which incapsulates some app's logic (in the example above all network related code is stored in a `moduleNetwork`, which was created as File -> New -> Target... -> Framework and is getting imported by other modules whenever I need to make a network call).

**Comment by paulb777** [comment]
@valzevul Firebase is a linked statically and can only be linked once into an app. It cannot be linked into multiple dynamic frameworks.

**Comment by valzevul** [comment]
@paulb777 I see, thanks for the clarification. 

It also seems that the answer in #4080 contradicts with yours, as there the comment mentions that using the same FIR instance from different frameworks actually works:
> I tried reproducing it with a separate library module, instead of a unit test module, and still cannot reproduce what you saw.

> I have tried with both different ID and same ID, the callback is called as expected though.

Would you have any advice on working around that issue?

**Comment by paulb777** [comment]
Having multiple copies of Firebase linked can lead to non-deterministic behavior.

To use Firebase in multiple modules, they should be statically linked so that Firebase only gets included once in the app.

**Comment by valzevul** [comment]
@paulb777 thank you for the explanation. I think this issue is resolved then.
