### ISSUE TITLE
Firestore crashing with`FIRQueryDocumentSnapshot `.

### ISSUE THREAD

**Issue by RuiAAPeres** [firebase/firebase-ios-sdk#4271]
### [READ] Step 1: Are you in the right place?
Yes

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: Xcode 11.2
  * Firebase SDK version: 6.12.0
  * Firebase Component: Firestore
  * Component version: 1.7.0

#### Steps to reproduce:

I am doing a simple query to Firestore and getting a runtime crash:

```
Precondition failed: NSArray element failed to match the Swift Array Element type
Expected FIRQueryDocumentSnapshot but found FIRQueryDocumentSnapshot: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-1100.2.274.2/swift/stdlib/public/core/ArrayBuffer.swift, line 354
2019-11-08 17:14:26.097113+0000 App[40195:45138882] Precondition failed: NSArray element failed to match the Swift Array Element type
Expected FIRQueryDocumentSnapshot but found FIRQueryDocumentSnapshot: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-1100.2.274.2/swift/stdlib/public/core/ArrayBuffer.swift, line 354
```

#### Relevant Code:

```swift
          store
            .collection(ChatReadingService.Collection.conversations)
            .document(id)
            .collection(ChatReadingService.Collection.messages)
            .order(by: ChatReadingService.Field.createdAt, descending: true)
            .limit(to: 1)
            .addSnapshotListener { (snapshot: QuerySnapshot?, error: Error?) in
             
             guard error == nil else {
                return
              }
              
              guard let unwrapped = snapshot else {
                return
              }
              
              let documents: [MyEntity] = unwrapped.documents.compactMap { (value: QueryDocumentSnapshot) in
                return try? value.data(as: MyEntity.self)
              }

           }
```

The crash is happening at `unwrapped.documents`.

**Comment by mikelehen** [comment]
Hrm.  From the error I am wondering if you're somehow getting two different definitions of FIRQueryDocumentSnapshot in your app.  Can you maybe try clearing your Pods directory and Podfile.lock, and running "pod install" fresh?  And if you still see the error can you share your Podfile.lock file?

**Comment by RuiAAPeres** [comment]
Hi @mikelehen! In fact those two issues are related. I was linking Firebase in multiple internal frameworks that I have. I think it would be advisable (unless I missed it completely), to put a warning in the documentation.

**Comment by mikelehen** [comment]
@RuiAAPeres Thanks for following up!  It sounds like this issue is resolved so I'm going to go ahead and close it.

That said I'm happy to try to get the docs improved to help out future folks.  Do you happen to have any suggestion of where we could document this so that you would have seen it?  I'm not sure how common it is for people to run into this and where we can best document it, but I can follow up with docs folks to see what we can do.  cc/ @paulb777 @ryanwilson
