### ISSUE TITLE
Impossible to extract Timestamp from Firestore

### ISSUE THREAD

**Issue by RuiAAPeres** [firebase/firebase-ios-sdk#4274]
### [READ] Step 1: Are you in the right place?

Yes. 

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.2
  * Firebase SDK version: 6.10.1
  * Firebase Component: Firestore
  * Component version: 1.6.1

### [REQUIRED] Step 3: Describe the problem

I have a model object that resembles:

```swift
public struct MyResponse: Equatable, Codable {
  public let title: String
  let createdAt: Timestamp
}
```

I am fetching values via `addSnapshotListener` and then manipulating a `DocumentSnapshot`. So:

```swift
import Firebase

.addSnapshotListener { (snapshot: DocumentSnapshot?, error: Error?) in
              
    guard error == nil else {
        return
     }
              
     guard let data = snapshot?.data() else { return }
```

The `data` printed on the console looks like this:

```
["createdAt": <FIRTimestamp: seconds=1572977015 nanoseconds=863000000> "title": "Ahaha"]
```

The problem is that I have no way to extract this `createdAt`. If I try via the canonical way of `data["createdAt"]` and try to cast it to `Timestamp` it fails. If I try to `Date`, it fails. I tried multiple approaches via FirebaseFirestoreSwift:

```swift
let model = try snapshot!.data(as: MyResponse.self)
```

It doesn't work either and I get:

```
typeMismatch(Swift.Dictionary<Swift.String, Any>, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "createdAt", intValue: nil)], debugDescription: "Not a dictionary", underlyingError: nil))
```

I even tried https://github.com/alickbass/CodableFirebase, but to no avail. 

At this point I have no idea how to extract a `Timestamp`. 😭 

PS: I am initialising a FirebaseApp in one framework (Authentication Framework) and passing a reference of it, to a different framework (Chat) so a Firestore is created. Could this be the issue?

**Comment by mikelehen** [comment]
`data["createdAt"]` should return a `Timestamp` so I'm surprised the cast fails...  in fact I bet this is related to your other issue (#4271) and you are somehow getting incompatible versions of `Timestamp`.

I'm not super familiar with Swift / iOS packaging stuff, but it could be related to the multiple frameworks you mentioned.  I would try to take a close look at the build configurations / dependencies and see if you can figure out a way they could be pulling in multiple versions of the Firebase SDK or something.  If you can't figure it out, perhaps you can provide a minimal repro project of some kind so we can help investigate?  Good luck!

**Comment by ryanwilson** [comment]
Regarding packaging: "To use Firebase in multiple modules, they should be statically linked so that Firebase only gets included once in the app."  https://github.com/firebase/firebase-ios-sdk/issues/4263#issuecomment-551209077

**Comment by mikelehen** [comment]
@RuiAAPeres Based on your comment in https://github.com/firebase/firebase-ios-sdk/issues/4271 I think this is resolved? I'm closing for now, but feel free to reopen if you're still running into difficulties. Thanks!
