### ISSUE TITLE
Firestore Podfile inconsistent access for FirebaseCore and GoogleUtilities

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#4310]
The Firestore [Podfile can access FirebaseCore locally but GoogleUtilities from a release](https://github.com/firebase/firebase-ios-sdk/blob/master/Firestore/Example/Podfile#L64). This causes CI breakages when FirebaseCore depends on a new feature from GoogleUtilities.

Specifically, it's causing a CI problem in #4098

**Comment by wilhuff** [comment]
I've left notes on the resolution in https://github.com/firebase/firebase-ios-sdk/pull/4098#pullrequestreview-316631059.
