### ISSUE TITLE
Firebase Message Create issue with Video recording 

### ISSUE THREAD

**Issue by leimo2011** [firebase/firebase-ios-sdk#4314]
* Xcode version: 11.2.1
  * Firebase SDK version: 6.12.0
  * Firebase Component: Messaging 

The problem:
when i set message delegate self, it affect on recording video, the cancel button when recording video will disappear and after stop recording video Retake and Use Video also disappear and app freeze 

Relevant Code:
Messaging.messaging().delegate = self

if #available(iOS 10.0, *) {
            // For iOS 10 display notification (sent via APNS)
            UNUserNotificationCenter.current().delegate = self
            let authOptions: UNAuthorizationOptions = [.alert, .badge, .sound]
            UNUserNotificationCenter.current().requestAuthorization(
                options: authOptions,
                completionHandler: {_, _ in })
            // For iOS 10 data message (sent via FCM)
            Messaging.messaging().delegate = self
        }

To reproduce the problem:
// Messaging.messaging().delegate = self

 all i done is hint the code but this create new issue i do not receive Token key so notification not working in this case 

![BD071826-F37A-4BDB-B6C5-139A3FA70304](https://user-images.githubusercontent.com/44530157/68835765-d7fb8680-06c9-11ea-949b-0b68308097c1.jpg)
![8C910F18-19E1-480F-AB71-CE8FBCDE2276](https://user-images.githubusercontent.com/44530157/68835777-dd58d100-06c9-11ea-8b3d-4b5527df75f7.jpg)

**Comment by morganchen12** [comment]
What object have you chosen as your messaging delegate? Can you share a full sample project?

**Comment by leimo2011** [comment]
//
//  LeimoNotificationManager.swift
//
//  Created by Mahmoud Elmoghazy on 6/18/19.
//  Copyright © 2019 Mawaqaa. All rights reserved.
//

import UIKit
import Foundation
import UserNotifications
import FirebaseFirestore
import Firebase
import FirebaseInstanceID
import FirebaseMessaging

class LeimoNotificationManager: NSObject, MessagingDelegate, UNUserNotificationCenterDelegate {
    
    let userID: String
    init(userID: String) {
        self.userID = userID
        super.init()
    }
    
    func registerForPushNotifications() {
        if #available(iOS 10.0, *) {
            // For iOS 10 display notification (sent via APNS)
            UNUserNotificationCenter.current().delegate = self
            let authOptions: UNAuthorizationOptions = [.alert, .badge, .sound]
            UNUserNotificationCenter.current().requestAuthorization(
                options: authOptions,
                completionHandler: {_, _ in })
            // For iOS 10 data message (sent via FCM)
            //Messaging.messaging().delegate = self
        } else {
            let settings: UIUserNotificationSettings =
                UIUserNotificationSettings(types: [.alert, .badge, .sound], categories: nil)
            UIApplication.shared.registerUserNotificationSettings(settings)
        }
        UIApplication.shared.registerForRemoteNotifications()
        updateFirestorePushTokenIfNeeded()
        updateBadgeCount()
    }
    
    func updateFirestorePushTokenIfNeeded() {
        if let token = Messaging.messaging().fcmToken {
            print("Firebase registration token: \(token)")
            let usersRef = Firestore.firestore().collection("users_table").document(userID)
            usersRef.setData(["fcmToken": token], merge: true)
        }
    }
    
    func messaging(_ messaging: Messaging, didReceive remoteMessage: MessagingRemoteMessage) {
        print(remoteMessage.appData)
    }
    
    func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String) {
        updateFirestorePushTokenIfNeeded()
        
        print("Firebase registration token: \(fcmToken)")
        GlobalVariablesManager.sharedManager.firebaseMessageTokenKey = fcmToken
        let dataDict:[String: String] = ["token": fcmToken]
        NotificationCenter.default.post(name: Notification.Name("FCMToken"), object: nil, userInfo: dataDict)
        
        LeimoDoLocalize.LeimoDoExchange()
    }
    
    @available(iOS 10.0, *)
    func userNotificationCenter(_ center: UNUserNotificationCenter,  willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (_ options: UNNotificationPresentationOptions) -> Void) {
        
        // Reading message body
        var messageBody:String?
        var messageTitle:String?
        let dict = notification.request.content.userInfo["aps"] as! NSDictionary
        
        if let alertDict = dict["alert"] as? Dictionary<String, String> {
            messageBody = alertDict["body"]!
            messageTitle = alertDict["title"]!
            if alertDict["title"] != nil {
                messageTitle  = alertDict["title"]!
            }
        }
        else{
            messageBody = dict["alert"] as? String
        }
        
        completionHandler([.alert,.sound, .badge])
        updateBadgeCount()
    }
    
    @available(iOS 10.0, *)
    func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void) {
        
        // Reading message body
        var messageBody:String?
        var messageTitle:String?
        let dict = response.notification.request.content.userInfo["aps"] as! NSDictionary
        
        if let alertDict = dict["alert"] as? Dictionary<String, String> {
            messageBody = alertDict["body"]!
            messageTitle = alertDict["title"]!
            if alertDict["title"] != nil {
                messageTitle  = alertDict["title"]!
            }
        }
        else{
            messageBody = dict["alert"] as? String
        }
        updateBadgeCount()
    }
    
    func updateBadgeCount(){
        var badgeCount = UIApplication.shared.applicationIconBadgeNumber
        if badgeCount > 0{
            badgeCount = 0
        }
        UIApplication.shared.applicationIconBadgeNumber = badgeCount
    }
}

// when ever want to push notifications to other users from device use this
//let sender = LeimoNotificationSenderManager()
//sender.sendPushNotification(to: GlobalVariablesManager.sharedManager.firebaseMessageTokenKey, title: "Notification title", body: "Notification body")

class LeimoNotificationSenderManager {
    func sendPushNotification(to token: String, title: String, body: String) {
        let urlString = "https://fcm.googleapis.com/fcm/send"
        let url = NSURL(string: urlString)!
        let paramString: [String : Any] = ["to" : token,
                                           "notification" : ["title" : title, "body" : body],
                                           "data" : ["user" : "test_id"]
        ]
        let request = NSMutableURLRequest(url: url as URL)
        request.httpMethod = "POST"
        request.httpBody = try? JSONSerialization.data(withJSONObject:paramString, options: [.prettyPrinted])
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue(GlobalVariablesManager.sharedManager.FCMServerKey, forHTTPHeaderField: "Authorization")
        let task =  URLSession.shared.dataTask(with: request as URLRequest)  { (data, response, error) in
            do {
                if let jsonData = data {
                    if let jsonDataDict  = try JSONSerialization.jsonObject(with: jsonData, options: JSONSerialization.ReadingOptions.allowFragments) as? [String: AnyObject] {
                        NSLog("Received data:\n\(jsonDataDict))")
                    }
                }
            } catch let err as NSError {
                print(err.debugDescription)
            }
        }
        task.resume()
    }
}


in AppDelegate

import Firebase

func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
                
        //Firebase notification
        FirebaseApp.configure()
        let pushManager = LeimoNotificationManager(userID: "")
        pushManager.registerForPushNotifications()
        
        return true
    }

**Comment by morganchen12** [comment]
Messaging code shouldn't be interacting with video capture or camera code in any way, so if it is that's a bug. The sample code you shared doesn't include any camera-related code.

Can you try profiling the freeze when the bug happens to see what method call is causing the freeze?

**Comment by leimo2011** [comment]
Actually before Xcode 11 i never face this issue with  same application and same codes was working very fine, after upgrade Xcode to version 11, i find out this issue and i never thought it will be because firebase messaging, i was looking what make this issue in many files in the project and i was too surprised when i hint messaging delegate line and find out record video return work fine as should be, and to be clear it is not make app freeze as freeze but it remove cancel button, use video button and retake button and at this point user stuck and this lead user to close the application and open it again

**Comment by morganchen12** [comment]
The sample code you shared doesn't include any camera-related code.

Can you try profiling the freeze when the bug happens to see what method call is causing the freeze?
