### ISSUE TITLE
Empty snapshot instead of error when offline and no cache

### ISSUE THREAD

**Issue by simonbengtsson** [firebase/firebase-ios-sdk#4317]
* Xcode version: 11.2.1
  * Firebase SDK version: 6.11
  * Firebase Component: Firestore
  * Component version: 1.6.1

I interpret the below documentation section that I should get an error if I'm offline and no cache exists. Instead I get a success call with an empty snapshot. This makes it hard to differentiate  between empty state and error state.

> If you get a document while the device is offline, Cloud Firestore returns data from the cache. If the cache does not contain data for that document, or the document does not exist, the get call returns an error.

https://firebase.google.com/docs/firestore/manage-data/enable-offline

#### Steps to reproduce:

1. Delete app from device (to make sure no cache exists)
2. Turn off internet (I'm using Network Link Conditioner, 100% loss setting in simulator)
3. Run app and query a random collection on start up
4. Wait about a minute for call to return
5. I get a snapshot result with 0 documents when I expect an error 

Sample code used where I get the 0 documents result

        Firestore.firestore()
            .collection("randomCollection")
            .limit(to: 10)
            .getDocuments(source: .default) { snap, error in
                if let snap = snap {
                    print("SUCCESS \(snap.documents.count)")
                } else {
                    print("ERROR \(error!.localizedDescription)")
                }
            }

**Comment by rizafran** [comment]
Thanks for reporting, @simonbengtsson. I was able to get the same behavior which returns 0 document result upon getting data when the simulator is offline. I'll clarify with the team if what specific error does the doc refers to.

**Comment by schmidt-sebastian** [comment]
@simonbengtsson The behavior you are seeing is as designed (but maybe not as documented). 

- If you issue a Collection Query against an empty cache, we will raise an empty snapshot.
- If you fetch a document via `DocumentReference.get()`, we will raise an error if we do not have a cached copy and the device is offline.

The document snippet you provided attempts to convey this information, but it does not explicitly call out that it targets single document fetches. I will ping our documentation team and ask them to rewrite this section.

Thank you for your report!

**Comment by simonbengtsson** [comment]
Thanks for reply! Just to make sure, that means there is no way to detect difference between no internet vs no documents when persistence is enabled with firestore? This would mean we could never show empty state screens?

**Comment by schmidt-sebastian** [comment]
You can use Query.get(Source.SERVER), which will return an error if we are not able to connect to the backend within 10 seconds.

**Comment by simonbengtsson** [comment]
We very much enjoy using the cache. But wanted to show an error state when there is no cache and no internet instead of a empty state that would worry users who actually might have content. 

Knowing that this is how it is designed we will ignore it and show empty state anyway. We might explore double querying with server and cache in the future.

**Comment by mikelehen** [comment]
@simonbengtsson You should be able to use `snap.metadata.fromCache` to determine if the resulting snapshot came from our cache (which would indicate that the client is offline / has no internet).

**Comment by simonbengtsson** [comment]
True! A better experience for our users would probably be to display error state instead of empty state when we get an empty snapshot back from a cache query which we can detect with `fromCache`. This since it's relatively uncommon for users to be offline after all.

That said, when we get a empty snapshot from cache we could still not differentiate between:
1. Collection never fetched so we have no idea if it has documents
2. Collection was fetched from server before and we can assume it has no documents

**Comment by mikelehen** [comment]
@simonbengtsson Yes, you are exactly right.  We discussed this a bit yesterday and it would be feasible for us to detect case 1 and surface an error instead of an empty snapshot, but since this would be a breaking change I'm not sure when we'd be able to make this change.

FWIW- What we typically recommend folks do is use a snapshot listener instead of a single getDocuments() call to populate their UI and keep it up-to-date.  Then while snapshot.metadata.fromCache is true, you can show a spinner or "waiting for network..." indicator or similar so that the user understands that the data may be empty / incomplete because it is still syncing.

**Comment by simonbengtsson** [comment]
Good point! The reason we went with getDocuments() is that we have a lot of infinite scrolling lists in our apps. After brief examination it felt like a hassle to work with snapshot listeners for this since we thought we needed to juggle removing listeners etc. But now that I give it second thought it would probably not be so bad. We could simply remove the listener for previous page whenever we fetch the next one. We'll explore it further! Thanks again!

**Comment by simonbengtsson** [comment]
Will explore this UX:

When we get results with `fromCache = true` from a snapshot listener:
- Keep showing loading indicator with "connecting..." message
- Show the user potentially cached results, but never show empty state

When `fromCache = false`:
- Hide loading indicator
- Show results or empty state
- Show error state if no snapshot returned or error

This would also mean we could get rid of our hacky "no connection" warning bar.

**Comment by mikelehen** [comment]
@simonbengtsson Sounds very reasonable!  One minor thing to be aware of is if that you'll likely want to pass `includeMetadataChanges: true` when you create your listener.  This will ensure you get an event even if the only thing that changed was metadata (so you can e.g. hide the loading indicator when fromCache goes from true to false).
