### ISSUE TITLE
Firebase does not use Secure Enclave features introduced with iOS 13

### ISSUE THREAD

**Issue by ssavchenko** [firebase/firebase-ios-sdk#4327]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.2.1
  * Firebase SDK version: 6.13.0
  * Firebase Component: FirebaseInstanceID
  * Component version: 6.13.0

### [REQUIRED] Step 3: Describe the problem

Firebase uses Apple's Security framework to generate cryptographic key pairs (SecKeyGeneratePair), but does not leverage the frameworks' Secure Enclave features introduced with iOS 13, to securely store private keys.

Starting with iOS 13, developers can add an extra layer of security by leveraging the hardware based key manager located in the Secure Enclave, available in any iOS devices with an A7 chip or newer.

When a private key is stored in the Secure Enclave, the key never actually leaves the Secure Enclave and your App or the OS itself never has to store a plain text version of the key in memory, in order to use it. Instead, your App instructs the Secure Enclave to create the key, securely store it, and perform cryptographic operations with it, and then only receives the output of these operations (such as encrypted data, or the result of a signature verification).

Please refer to Apple's official documentation at https://developer.apple.com/documentation/security/certificate_key_and_trust_services/keys/storing_keys_in_the_secure_enclave for more details.

**Comment by chliangGoogle** [comment]
Thank you for filling this, we will take a look at this one.

**Comment by paulb777** [comment]
Closing since Firebase Instance ID has been replaced by Firebase Installations.
