### ISSUE TITLE
Need frameworks compiled with Swift 5.1.2

### ISSUE THREAD

**Issue by scalessec** [firebase/firebase-ios-sdk#4329]
We're using Carthage, and we're currently blocked from using Xcode 11.2 and iOS 13.2 because there are no available frameworks compiled with Swift 5.1.2. Do you have an ETA on when those will be available?

**Comment by paulb777** [comment]
What exactly is the problem you're seeing?

All of the Firebase frameworks distributed in Carthage are Objective C, so the Swift version should not matter.

**Comment by scalessec** [comment]
My apologies, the error we were seeing was related to a different compiled framework.
