### ISSUE TITLE
Error: Sign in with Apple on Mac Catalyst

### ISSUE THREAD

**Issue by lisindima** [firebase/firebase-ios-sdk#4335]
### [READ] Step 1: Are you in the right place?

  Yes, seems to me in the right place.

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.3 beta (11C24b)
  * Firebase SDK version: 6.13.0
  * Firebase Component: Auth
  * Component version: 6.4.0

### [REQUIRED] Step 3: Describe the problem

1. Add GoogleService-Info.plist
2. Install pods
3. Use this instruction: https://firebase.google.com/docs/auth/ios/apple?authuser=0

When trying to authenticate through apple in the mac catalyst application, an error appears:

`2019-11-18 09:13:37.359204+0700 АлтГТУ[43471:1174191] [core] No window got from UINSSharedApplicationDelegate`

`2019-11-18 09:13:41.270412+0700 АлтГТУ[43471:1174243] [core] Authorization failed: Error Domain=AKAuthenticationError Code=-7071 "(null)"`

Meanwhile, on iOS, this code works great!

**Comment by rizafran** [comment]
Hi @lisindima Sign in with Apple on Mac Catalyst is not officially supported. iOS libraries could work on Catalyst directly, but there might be bugs.

Details about Catalyst support [here](https://github.com/firebase/firebase-ios-sdk#tvos-macos-and-catalyst).

**Comment by lisindima** [comment]
I close the problem, the error was caused in my improper implementation of the code from the documentation in my catalyst application.
