### ISSUE TITLE
Crashlytics data can only be seen under enabling debug mode

### ISSUE THREAD

**Issue by boaass** [firebase/firebase-ios-sdk#4336]
* Xcode version: 11.1
  * Firebase SDK version: 6.1.0
  * Firebase Component: Analytics, Remote Config, A/B Testing, Crashlytics

Describe the problem:
Crashlytics data can only be seen when enabling debug mode ?
Android: adb shell setprop debug.firebase.analytics.app package_name
iOS: -FIRDebugEnabled

**Comment by jasonhu-g** [comment]
Hi @boaass ,

First of all, thank you for using our SDK. 

May you expand on what you mean by Crashlytics data is only seen when enabling debug mode? Do you not see the crash reported in the Firebase Crashlytics console? The debug flag should not change the functionality of the SDKs, but adds debug logs.

Would you be able to share the logs from the output window in XCode in the unexpected behavior scenario for:
1. The original app launch
2. The re-launch of the app after a crash has occurred

**Comment by boaass** [comment]
Thank you for reply. I think there's something wrong with my code. Now I can see the crash log.

> Hi @boaass ,
> 
> First of all, thank you for using our SDK.
> 
> May you expand on what you mean by Crashlytics data is only seen when enabling debug mode? Do you not see the crash reported in the Firebase Crashlytics console? The debug flag should not change the functionality of the SDKs, but adds debug logs.
> 
> Would you be able to share the logs from the output window in XCode in the unexpected behavior scenario for:
> 
> 1. The original app launch
> 2. The re-launch of the app after a crash has occurred

Thank you for reply. I think there's something wrong with my code. Now I can see the crash log.
