### ISSUE TITLE
FR: Invoke authStateDidChange listener when user metadata changes

### ISSUE THREAD

**Issue by IgorRosocha** [firebase/firebase-ios-sdk#4339]
### Environment:

  * Xcode version: 11.2
  * Firebase SDK version: 6.13.0
  * Firebase Component: Auth
  * Component version: 6.13.0

#### Steps to reproduce:

After registration of a new user via Firebase Auth, I call ` User.createProfileChangeRequest()` to set the `displayName` of given `User`. However, even if the `displayName` is set up correctly, `stateDidChangeListener` is not being triggered. 

It would be really nice if `stateDidChangeListener` would get triggered when setting up/changing `User`'s `displayName`, so that the change of `User`'s information/profile could be easily handled in the app. AFAIK, Android has the same exact issue.

#### Implementation of createProfileChangeRequest():

```swift
let request = user.createProfileChangeRequest()
request.displayName = name
request.commitChanges { error in
  if let error = error {
    // Handle error
  } else {
    // Success logic
  }
}
```

#### Implementation of stateDidChangeListener:

```swift
Auth.auth().addStateDidChangeListener { _, user in
  // Change of displayName doesn't trigger the listener
}
```

**Comment by morganchen12** [comment]
IIRC auth state change refers to changes in sign in and sign out, not changes in the user's profile. @renkelvin can you confirm?

**Comment by renkelvin** [comment]
@morganchen12 Yeah, that's correct.

**Comment by morganchen12** [comment]
@IgorRosocha, is there a significant difference between handling the user metadata change in the `commitChanges` callback versus the `authStateDidChange` callback?
