### ISSUE TITLE
FR: macOS Firestore support

### ISSUE THREAD

**Issue by PierBover** [firebase/firebase-ios-sdk#434]
As per Salman Qadri's suggestion I'm opening this FR.

**Comment by GetyUp** [comment]
With Firestore going GA yesterday, macOS support would be fantastic!

**Comment by wilhuff** [comment]
Until Firebase more broadly supports macOS, macOS support is a community endeavor. That said, #2241 made the required changes and added support in the podspec.

This FR remains open because we still haven't gotten this integrated with our CI environment, but it should work.

**Comment by wilhuff** [comment]
OK tests working (#2641) and running on Travis (#2645) is good enough to call this done.
