### ISSUE TITLE
App Crash on reading primaryActionURL for FIRInAppMessagingCardDisplay

### ISSUE THREAD

**Issue by whizbuff** [firebase/firebase-ios-sdk#4340]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.1
  * Firebase SDK version: 6.9.0
  * Firebase Component: 
  * Firebase/InAppMessaging (6.9.0):
         - Firebase/CoreOnly
         - FirebaseInAppMessaging (~> 0.15.4)

### [REQUIRED] Step 3: 
Using Custom Display components rather than Firebase DisplayUI for InAppMessaging

#### Steps to reproduce:
Create a InAppMessage campaign : Card Style
Configure Primary button text and mark it as "Use dismiss as the action"

App Crashes when trying to read actionURL in implementation

even though interface file of inAppMessagingCardDisplay, says primaryActionURL cannot be nil
```@property(nonatomic, nonnull, readonly) NSURL *primaryActionURL;```

#### Relevant Code:

```
func handleInAppMessageCardDisplay(with inAppMessagingCardDisplay: InAppMessagingCardDisplay) {
        
                self.rightInAppMessagingAction = InAppMessagingAction(actionText: inAppMessagingCardDisplay.primaryActionButton.buttonText, actionURL: inAppMessagingCardDisplay.primaryActionURL)

}

```

**Comment by whizbuff** [comment]
Hi @morganchen12 , any update ?

I have workaround which I would like to remove soon..
guard let url = inAppMessagingCardDisplay.primaryActionURL as? URL else  { return }
though I have warning: Conditional cast from 'URL' to 'URL' always succeeds

**Comment by whizbuff** [comment]
@christibbs  hi..
Hope you have some update for me  🤞 .

**Comment by christibbs** [comment]
@whizbuff Sorry for the delay. We will need to make primaryActionURL nullable (for the case where dismiss is the action). Hoping to get this into the next release.
