### ISSUE TITLE
Fix FIAM to work with OCMock 3.5.0

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#4349]
From https://travis-ci.org/firebase/firebase-ios-sdk/jobs/613701590

FIRIAMFetchFlowTests
  testAlwaysFetchForNewlyInstalledMode, failed: caught "NSInternalInconsistencyException", "Mock object was not used in OCMVerify. Did you accidentally use a real object?"
  /Users/travis/build/firebase/firebase-ios-sdk/InAppMessaging/Example/Tests/FIRIAMFetchFlowTests.m:279
  ```
  // we expect that the message cache is checked for app launch messages
  OCMVerify([self.flow checkForAppLaunchMessage]);

**Comment by ryanwilson** [comment]
Did a bit of research on this one and it's in fact a real object that we're trying to call `OCMVerify` on.

A quick fix would be to create an `OCMPartialMock` of `self.flow` and stub out that method, but that method just calls a singleton and a single method on it so we could probably inject that as well like all the other mocks in that class.
