### ISSUE TITLE
FR: Expose update delta from FSyncTree in FIRDataSnapshot

### ISSUE THREAD

**Issue by akshetpandey** [firebase/firebase-ios-sdk#435]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.1
  * Firebase SDK version: 4.2.0
  * Firebase Component: Database
  * Component version: 4.2.0

### [REQUIRED] Step 3: Describe the problem

Based on reading the FSyncTree code, it looks like the client receives delta updates from the server
but eventListeners on the ref receive FIRDataSnapshot that only contains the complete updated tree under that ref.

It would be very useful from a performance perspective if the delta change is also exposed in the FIRDataSnapshot so we can only update that part of our UI and we don't need to calculate delta again.

My use case if for gamestates where it is not practical to add a eventLister to ever child key in the base gamestate and figuring out the delta change immensely help with only updating that UI component without doing costly diffs and deep equality checks.

I may eventually end up creating a PR for this if there is interest but it will take me a while because it feels like this is dealing with internal parts of the code that I am not familiar with and firebase may not want touched without a spec review.

**Comment by schmidt-sebastian** [comment]
This is a feature we are providing with Firestore (https://firebase.google.com/docs/firestore/reference/ios/firestore/api/reference/Classes/FIRQuerySnapshot#/c:objc(cs)FIRQuerySnapshot(py)documentChanges). We currently don't have plans to add it to the RTDB, but welcome contributions. We would need to figure out how we can provide the same feature surface for Android and iOS.
