### ISSUE TITLE
[QUESTION] Multiple collection listeners

### ISSUE THREAD

**Issue by filipealva** [firebase/firebase-ios-sdk#4356]
Hey guys,

Sorry if this is not the right place to ask this but:

Let's assume that I have two different screens presenting the data from the same collection, but presenting it differently. I have two different view models that will process the data differently to make it ready for each screen to present.

In this case, would it be recommended to have only one listener and write a mechanism to notify both view models using this firebase listener? Or is it fine to setup two different firebase listeners for each view model? 

Thanks so much for all the hard work.

**Comment by morganchen12** [comment]
Can you clarify if this is Firestore or RTDB? Based on your mention of collections and listeners I suspect it's Firestore, but it would be good to confirm.

**Comment by filipealva** [comment]
@morganchen12 yes, it's Firestore

**Comment by wilhuff** [comment]
From a billing perspective, each query is distinct. In the local cache and for network purposes updates to documents that match both queries are deduplicated.

So in short: it would be slightly cheaper to use a single listener and perform your own filtering but not any more performant.

**Comment by mikelehen** [comment]
@filipealva Just as a point of clarification, are both listeners listening to an identical query (i.e. the same collection, the same "where" filters, and the same OrderBy)?  Or are they performing distinct queries against the same collection?

**Comment by filipealva** [comment]
> So in short: it would be slightly cheaper to use a single listener and perform your own filtering but not any more performant.

Cool. I would imagine that it would be slightly cheaper, but I think that it compensates not having to deal with the code to perform our own filtering. 

> Just as a point of clarification, are both listeners listening to an identical query (i.e. the same collection, the same "where" filters, and the same OrderBy)? Or are they performing distinct queries against the same collection?

The queries are exactly the same. 

Just to give more context: we are deciding some details about dealing with Firebase internally and, as I said before, for me it worth it to avoid adding more code to "re-handle" listeners if the only disadvantage is that it would cost a little bit more for us. I mean, one of the points of using Firebase is to speed up the process and get rid of complexities, so...

**Comment by wilhuff** [comment]
The Firestore SDK will completely deduplicate identical queries. The previous answer covers the case where you're running two queries over the same data with different filters or orderBys.

**Comment by filipealva** [comment]
So it wouldn't even be more expensive to use two listeners for this case?

**Comment by wilhuff** [comment]
For completely identical queries we only issue the query to the backend once. That's what you get billed for--so yes, it doesn't even cost you more.
