### ISSUE TITLE
[GDTCORDataFuture initWithCoder:] Crash

### ISSUE THREAD

**Issue by JianweiWangs** [firebase/firebase-ios-sdk#4381]
### [READ] Step 1: Are you in the right place?

```
0
libsystem_platform.dylib
_os_unfair_lock_recursive_abort + 36
4
CoreFoundation
+[NSException exceptionWithName:reason:userInfo:] + 68
5
osee2unifiedRelease
_xad_handle_signal(int, __siginfo*, void*) + 4336328344
6
libsystem_platform.dylib
_sigtramp + 44
14
Foundation
-[NSKeyedUnarchiver decodeObjectOfClasses:forKey:] + 428
15
osee2unifiedRelease
GDTCORDataFuture.m - 第 58 行
-[GDTCORDataFuture initWithCoder:] + 58
16
Foundation
_decodeObjectBinary + 2000
19
Foundation
-[NSKeyedUnarchiver decodeObjectOfClasses:forKey:] + 428
20
osee2unifiedRelease
GDTCORStoredEvent.m - 第 75 行
-[GDTCORStoredEvent initWithCoder:] + 75
21
Foundation
_decodeObjectBinary + 2000
28
Foundation
-[NSKeyedUnarchiver decodeObjectOfClasses:forKey:] + 428
29
osee2unifiedRelease
GDTCORStorage.m - 第 294 行
__31-[GDTCORStorage initWithCoder:]_block_invoke + 294
30
libdispatch.dylib
_dispatch_client_callout + 20
31
libdispatch.dylib
_dispatch_lane_barrier_sync_invoke_and_complete + 60
32
osee2unifiedRelease
GDTCORStorage.m - 第 291 行
-[GDTCORStorage initWithCoder:] + 291
33
Foundation
_decodeObjectBinary + 2000
40
Foundation
+[NSKeyedUnarchiver unarchivedObjectOfClass:fromData:error:] + 112
41
osee2unifiedRelease
GDTCORStorage.m - 第 221 行
-[GDTCORStorage appWillForeground:] + 221
42
osee2unifiedRelease
GDTCORLifecycle.m - 第 93 行
-[GDTCORLifecycle applicationWillEnterForeground:] + 93
43
Foundation
__57-[NSNotificationCenter addObserver:selector:name:object:]_block_invoke_2 + 28
50
Foundation
-[NSNotificationCenter postNotificationName:object:userInfo:] + 72
51
osee2unifiedRelease
GDTCORPlatform.m - 第 176 行
-[GDTCORApplication iOSApplicationWillEnterForeground:] + 176
52
Foundation
__57-[NSNotificationCenter addObserver:selector:name:object:]_block_invoke_2 + 28
81
UIKitCore
UIApplicationMain + 216
82
osee2unifiedRelease
main.m - 第 13 行
main + 13
83
libdyld.dylib
start + 4
```

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.1
  * Firebase SDK version: 6.13.0
  * Firebase Component: Crashlytics 3.14.0  Fabric 1.10.2 GoogleDataTransport 3.1.0 GoogleDataTransportCCTSupport 1.2.1

**Comment by ryanwilson** [comment]
Hi @JianweiWangs thanks for the report. I'm not able to reproduce this based on just the stack trace given (blank project, backgrounding the app, pulling it back up, each `GDTCORStoredEvent` unarchives successfully (Xcode 11.1, iOS 13 simulator).

A few questions before we can move forward with this:

- Do you have more information about the exception (like the text of the exception, saying why it threw)?
- Have you been able to reproduce this? If so, how?
- Is this happening on a specific iOS version?
- Is this a one-off crash or have you seen a large number of these crashes?

The encoding here is pretty straight forward (just two URLs) so I'm curious as to why it would be throwing an exception, potentially an object of a different type is being encoded.

Thanks!

**Comment by JianweiWangs** [comment]
Hi @ryanwilson  thanks for your reply. 
1. 
```
已崩溃：com.google.GDTCORStorage
EXC_BREAKPOINT 0x00000001897461a4
```
it's only info I get.
2. I can't reproduce it, we get this crash from firebase, only  times per day, we have about 3M active users online per day.
3. Not specific iOS version, from 10 to 13
4. not one-off but few

Thanks for your help!

**Comment by ryanwilson** [comment]
Thanks for getting back to me! Hmm, this is going to be a tough one to debug without other information or a repro but we can keep trying.

Two more quick questions if you don't mind - is there a specific device model this is happening on (i.e. iPhone 5S)? I want to make sure it's not a 32 vs 64 bit issue. Other thing would be (if you are able to find out) are the crashes the same device crashing over and over again or does each device typically only crash once?

Thanks!

**Comment by morganchen12** [comment]
@ryanwilson, could it be related to this line [here](https://github.com/firebase/firebase-ios-sdk/blob/18e2721c1dbb1fc33812c82e4a79da1344d18f54/GoogleDataTransport/GDTCORLibrary/GDTCORDataFuture.m#L56)?

AFAIK the `initWithCoder:` initializer should be calling `super initWithCoder:` and passing in the same decoder. I'm not familiar with NSCoding internals, but the `_os_unfair_lock_recursive_abort` in this case may indicate some bad state in the decoder as a result of it not being passed to `super`.

**Comment by ryanwilson** [comment]
@morganchen12 since the superclass in this case is `NSObject`, and `NSObject` doesn't conform to `NSCoding` so it shouldn't call `super initWithCoder:` as far as I'm aware.
