### ISSUE TITLE
Storage upload error

### ISSUE THREAD

**Issue by Harryjeffs** [firebase/firebase-ios-sdk#4391]
* Xcode version:  11.2.1
  * Firebase SDK version: 6.13.0
  * Firebase Component:  Storage - 3.4.2
  * Component version: _____

### The problem

Trying to upload images to firebase storage terminates errors within the pod files.
 In `FIRStorageUploadTask.m`, line 109 -     `NSDictionary *queryParams = @{@"uploadType" : @"resumable", @"name" : self.uploadMetadata.path};` crashes with this error message; 

> Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]'

Here is my code,
for singleImage in onboaringData.photos{
            let imageId = UUID().uuidString
            
            let imagePath = storageRef.child(postId + "/" + imageId + ".png")
            dispatchGroup.enter()
            
            if let uploadData = singleImage.jpegData(compressionQuality: 0.8) {
                let metadata = StorageMetadata()
                metadata.contentType = "image/jpeg"
                storageRef.putData(uploadData, metadata: nil) { (metadata, error) in
                    if error != nil {
                        self.imagePathArray.append(error.debugDescription)
                    } else {
                        self.storageRef.downloadURL(completion: { (url, error) in
                            print("Uploaded: ",url?.absoluteString)
                            self.imagePathArray.append(url?.absoluteString ?? "")
                        })
                    }
                    dispatchGroup.leave()
                }
            }
        }

**Comment by ryanwilson** [comment]
Hi @Harryjeffs - sorry for the troubles.

One thing I notice with the code snippet is the `StorageMetadata` you created isn't actually used, and `nil` is passed instead:
`storageRef.putData(uploadData, metadata: /* HERE */ nil) { (metadata, error) in`

Should be: 
`storageRef.putData(uploadData, metadata: metadata) { (metadata, error) in`

Does that fix your issue? If not, please let us know and we'll try to get it resolved.

**Comment by Harryjeffs** [comment]
Hey. Messing around with the metadata was part of my debugging process, wether it’s included or not still returns this error.

**Comment by Harryjeffs** [comment]
Was passing the wrong variable into `.putData()`! Got there eventually.
