### ISSUE TITLE
Installation of the latest version of AdMob in Xcode 10.1

### ISSUE THREAD

**Issue by Sunrise17** [firebase/firebase-ios-sdk#4392]
### Environment

  * Xcode version: 10.1
  * Firebase SDK version: 6.13.0
  * Firebase Component: Auth, Core, Database, Firestore, Messaging
  * Component version: 

### Problem

During the installation of Pods to the latest version, following dependencies are updated successfully as shown below. 

![Ekran Resmi 2019-11-25 16 52 37](https://user-images.githubusercontent.com/26038249/69546045-0586e080-0fa4-11ea-9311-12b2a838eda6.png)

Unfortunately, following 5 dependencies below, could not updated to latest version.

![Ekran Resmi 2019-11-25 15 16 01](https://user-images.githubusercontent.com/26038249/69546106-25b69f80-0fa4-11ea-8a03-a874d4377f99.png)

The version of the installed cocoapods is 1.8.4. 

I have deintegrated Pods , remove pod (& .lock) file and clean cache inside ~/Library/Caches/CocoaPods/, uninstall and re-install cocoaPods but it did not work.

**Comment by ryanwilson** [comment]
Hi @Sunrise17 - thank you for the report. Can you please share your full Podfile? That will help us figure out if there are any dependencies that are preventing the pods from updating.

I do know one thing - Firestore is depending on `gRPC-C++ 0.0.9` directly here: https://github.com/firebase/firebase-ios-sdk/blob/7481e8b97f1d22b2195ca8907542329e18d5881e/FirebaseFirestore.podspec#L73

It looks like 12 days ago the gRPC team went directly from `0.0.9` to `1.25.0` (cc @wilhuff) so we should investigate and fix that, but it's thankfully not incredibly out of date like the versions may indicate :) 
 
https://github.com/CocoaPods/Specs/blob/master/Specs/c/8/7/gRPC-C%2B%2B/1.25.0/gRPC-C%2B%2B.podspec.json

**Comment by Sunrise17** [comment]
This is the podFile of the Project.

platform :ios, '12.1'

target 'AppName' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # project 'AppName.xcodeproj'

  # Pods for Firebase
	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/AdMob'
  pod 'Firebase/Functions'

  # Pods for FacebookLogin
  pod 'FBSDKLoginKit'

end

**Comment by paulb777** [comment]
The pod installation is working as intended. 

As @ryanwilson noted, Firestore has a hard dependency on `gRPC-C++ 0.0.9`. That explains the BoringSSL and gRPC dependencies. Work to integrate 1.25.0 is in progress at #4312.  I suspect a similar situation for abseil. Firestore is being explicit about the dependency versions that it is tested and supported with.

For `Protobuf`, CocoaPods will only update to a beta or rc version if the Podfile explicitly asks for it. While we don't expect there to be any issues with `3.11.0-rc2`, we wouldn't recommend using it for production code.

The invalid bitcode issue is indicative of a binary Pod being built with an Xcode version later than 10.1.  We'll take a look to see if something went wrong in the release process.

**Comment by paulb777** [comment]
I'm able to successfully archive on Xcode 10.1 with the Firebase and Facebook Pods listed above. I suspect the bitcode problem is from another Pod specified in the Podfile.

**Comment by Sunrise17** [comment]
@paulb777, thanks for your feedback. Is "Enable Bitcode" setting enabled in your Build Settings? I do not have any other Pod installed except the list above. Now, i have disabled "Enable Bitcode" setting and trying to archive again, i will let you know about the result.

**Comment by Sunrise17** [comment]
With Disabled Bitcode setting, i have successfully archived the Project.

**Comment by paulb777** [comment]
Oh, right - the bitcode setting was off in my sample project. Good catch!

I now can reproduce the issue and I isolated to that the Google-Mobile-Ads pod stopped being built with Xcode 10.1 with version 7.46.

The workaround is to force it back to 7.45.0 like

```
 # pod 'Firebase/AdMob'
  pod 'Firebase/Core', '~> 6.0'
  pod 'Google-Mobile-Ads-SDK', '7.45.0'
```

**Comment by paulb777** [comment]
Internally tracked at b/145126610

**Comment by paulb777** [comment]
@Sunrise17 A better workaround than changing the Podfile would be using a more recent version of Xcode.

**Comment by paulb777** [comment]
Leaving this open since the `Google-Mobile-Ads-SDK` pod is not compliant with the Firebase documentation to support back to Xcode 10.1.  See above for workarounds.

**Comment by paulb777** [comment]
Unlike the rest of Firebase, the Google-Mobile-Ads-SDK CocoaPods binary is built with Xcode 10.2.1. We're planning to be better coordinated on Xcode versions in the future, but not planning to go back and fix this one.
