### ISSUE TITLE
Performance Monitoring 'HTTPMetric' returns 'nil'

### ISSUE THREAD

**Issue by zippi-MD** [firebase/firebase-ios-sdk#4397]
* Xcode version: 11.2
  * Firebase SDK version: 6.13
  * Firebase Component: Performance Monitoring

I just updated my project to Firebase 6.13 (no cocoapods). After doing this, and trying to add monitoring for custom network requests following this example [Add monitoring for custom network requests](https://firebase.google.com/docs/perf-mon/https_traces?platform=ios#add-custom-https-requests) I get a nil from calling 'HTTPMetric(url: <URL>, httpMethod: <HTTPMethod>)'

```swift
        let testURL = URL(string: "https://www.google.com")!
        let metric = HTTPMetric(url: testURL, httpMethod: .post)
```

After calling this code 'metric' has a nil value.

**Comment by visumickey** [comment]
@zippi-MD Can you please share the console logs when this happens? Whenever any trace creation fails, there should some information on the logs mentioning the reason for the failure.

**Comment by zippi-MD** [comment]
This is the only log that I think might be related to the problem

2019-11-26 12:36:31.851588-0600 AppName[3887:76479] 6.13.0 - [Firebase/Performance][I-PRF200004] Dropping Event since Performance SDK is disabled.

**Comment by visumickey** [comment]
@zippi-MD Were you trying this on simulator? The reason for the question is sometimes network requests do not successfully complete on the simulator. Firebase performance expects a successful remote configuration fetch to happen to make sure it starts collecting events. May be you are caught in such a race condition.

Can you also let us know if this is sporadic or is this consistent?

**Comment by zippi-MD** [comment]
Yes, I was trying it on the simulator. I switch to a device and the problem is gone. Thanks 😊 

On the simulator the behavior is consistent.

**Comment by visumickey** [comment]
@zippi-MD Awesome, that is good to know that the issue is resolved. We will make sure to resolve this on the simulator as well. Appreciate your time for the feedback.

**Comment by lukicmarko** [comment]
I have same problem on the device.

**Comment by paulb777** [comment]
Is this still an issue?

**Comment by iamoncall** [comment]
Leaving this bug closed as last activity was over 6 months ago. Please reopen it if you experience similar issue.
