### ISSUE TITLE
Crash on -[FPRRemoteConfigFlags cachedValueForConfigFlag:]

### ISSUE THREAD

**Issue by dongshuju** [firebase/firebase-ios-sdk#4400]
### [READ] Step 1: Are you in the right place?

Crash

### [REQUIRED] Step 2: Describe your environment

  * Xcode version:  Xcode 11.2.1
  * Firebase SDK version:  6.13.0
  * Firebase Component:  Core
  * Component version: 6.13.0

### [REQUIRED] Step 3: Describe the problem

We upgrade to lateast SDK version 6.13.0, Crashed on `[FPRRemoteConfigFlags cachedValueForConfigFlag:] `

#### Steps to reproduce:

It's crashed on com.hackemist.SDWebImageDownloader thread, but we do not use SDWebImage with FireBase. 

Here is the Crash Info:

```
#0Crashed: com.hackemist.SDWebImageDownloader (QOS: UNSPECIFIED)EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000d80f10780 Raw Text
--
0 | libobjc.A.dylib | objc_msgSend + 16
1 | ** | -[FPRRemoteConfigFlags cachedValueForConfigFlag:] + 4377850916
2 | ** | -[FPRRemoteConfigFlags getStringValueForFlag:defaultValue:] + 4377851512
3 | ** | -[FPRRemoteConfigFlags sdkDisabledVersionsWithDefaultValue:] + 4377852196
4 | ** | -[FPRConfigurations sdkDisabledVersions] + 4377844816
5 | ** | -[FPRConfigurations sdkEnabled] + 4377844576
6 | ** | -[FPRNetworkTrace initWithURLRequest:] + 4377893596
7 | ** | __InstrumentDataTaskWithRequestCompletionHandler_block_invoke + 4377925080
8 | SDWebImage | SDWebImageDownloaderOperation.m line 162-[SDWebImageDownloaderOperation start] + 162
9 | Foundation | __NSOQSchedule_f + 276
17 | libsystem_pthread.dylib | start_wqthread + 4
```

**Comment by visumickey** [comment]
@dongshuju Thanks for the report. The reason why you are seeing SDWebImage as a part of the request is because Firebase Performance tries to measure the performance of all the network requests that happen. 

With regards to the crash, we will take a look at it and rollout a fix for this very soon. 

Are there any specific pattern you see in the crashes? (Eg. OS Version, Application state)

**Comment by maksymmalyhin** [comment]
@dongshuju In order to capture performance information of the network requests Firebase Performance needs to swizzle some object (e.g. `NSURLSession`). In your case the crash happens while a `NSURLRequest` created by `SDWebImageDownloader` is instrumented. 

As a workaround you may temporary disable features of Firebase Performance requiring swizzling while investigating and fixing the issue by setting [Performance.isInstrumentationEnabled](https://firebase.google.com/docs/reference/swift/firebaseperformance/api/reference/Classes/Performance#isinstrumentationenabled) to `false` before calling `FirebaseApp.configure()`:

```
Performance. sharedInstance().isInstrumentationEnabled = false
FirebaseApp.configure()
```

**Comment by visumickey** [comment]
@dongshuju Can you share the complete stack trace for this crash? I'm guessing a possible race condition triggering this issue and I would like to make sure we have other parts of the stack trace available for us to ascertain and look at this issue.

**Comment by BaluNaik** [comment]
@visumickey  recently we included this SDK in-app and getting the same crash. Here some more information
```
Crashed: com.google.perf.FPREventsQueue
0  libobjc.A.dylib                0x1e7422f70 objc_msgSend + 16
1  Namshi                         0x101174238 -[FPRRemoteConfigFlags cachedValueForConfigFlag:] + 4369203768
2  Namshi                         0x10117448c -[FPRRemoteConfigFlags getStringValueForFlag:defaultValue:] + 4369204364
3  Namshi                         0x101174738 -[FPRRemoteConfigFlags sdkDisabledVersionsWithDefaultValue:] + 4369205048
4  Namshi                         0x101172a64 -[FPRConfigurations sdkDisabledVersions] + 4369197668
5  Namshi                         0x101172974 -[FPRConfigurations sdkEnabled] + 4369197428
6  Namshi                         0x101177130 -[FPRClient processAndLogEvent:] + 4369215792
7  Namshi                         0x101176a34 __22-[FPRClient logTrace:]_block_invoke + 4369214004
8  libdispatch.dylib              0x1e7c13b9c _dispatch_call_block_and_release + 32
9  libdispatch.dylib              0x1e7c15134 _dispatch_client_callout + 20
10 libdispatch.dylib              0x1e7c1c78c _dispatch_lane_serial_drain + 872
11 libdispatch.dylib              0x1e7c1d194 _dispatch_lane_invoke + 368
12 libdispatch.dylib              0x1e7c25480 _dispatch_workloop_worker_thread + 588
13 libsystem_pthread.dylib        0x1e7e16b20 _pthread_wqthread + 316
14 libsystem_pthread.dylib        0x1e7e1cdd4 start_wqthread + 4
``` 
```
Xcode version: Xcode 11.2.1
Firebase SDK version: 6.13.0
Firebase Component: Core
Component version: 6.13.0
```

```
iOS 11.0.1
iOS 12.x
```

**Comment by Vitalik13** [comment]
@visumickey I getting the same crash. Here some more information

```
Crashed: com.google.perf.FPREventsQueue
0 libobjc.A.dylib objc_object::release() + 16
1 MyApp -[FPRRemoteConfigFlags cachedValueForConfigFlag:] + 4376156408
2 MyApp -[FPRRemoteConfigFlags getBoolValueForFlag:defaultValue:] + 4376157316
3 MyApp -[FPRConfigurations sdkEnabled] + 4376149432
4 MyApp -[FPRClient processAndLogEvent:] + 4376168192
5 MyApp __22-[FPRClient logTrace:]_block_invoke + 4376166436
6 libdispatch.dylib _dispatch_call_block_and_release + 24
7 libdispatch.dylib _dispatch_client_callout + 16
8 libdispatch.dylib _dispatch_queue_serial_drain$VARIANT$armv81 + 904
9 libdispatch.dylib _dispatch_queue_invoke$VARIANT$armv81 + 328
10 libdispatch.dylib _dispatch_root_queue_drain_deferred_wlh$VARIANT$armv81 + 332
11 libdispatch.dylib _dispatch_workloop_worker_thread$VARIANT$armv81 + 612
12 libsystem_pthread.dylib _pthread_wqthread + 860
13 libsystem_pthread.dylib start_wqthread + 4
```

```
Xcode version: Xcode 11.3
Firebase SDK version: 6.14.0
Firebase Component: Core
Component version: 6.14.0
```

```
iOS 11.4.1
```

**Comment by visumickey** [comment]
@Vitalik13 @BaluNaik Can you share all the threads that were active during the time of crash? We are guessing a probable race condition in fetching a cached value that is leading to this crash.

**Comment by BaluNaik** [comment]
@visumickey Please find the attached crash log.

[CrashLog.txt](https://github.com/firebase/firebase-ios-sdk/files/4086641/CrashLog.txt)

**Comment by visumickey** [comment]
Based on the information we have narrowed down the issue and have proposed a fix for the same. Hopefully this fixes the crash. The fix will be shipped in the upcoming release.

**Comment by visumickey** [comment]
Unfortunately we could not roll out the fix in this release. Though the changes were done, because of a broken internal dependency, we could not make it to this release. We are looking forward to roll this out in the upcoming release (ETA in 2 weeks).

**Comment by BaluNaik** [comment]
> Unfortunately we could not roll out the fix in this release. Though the changes were done, because of a broken internal dependency, we could not make it to this release. We are looking forward to roll this out in the upcoming release (ETA in 2 weeks).

Thanks, @visumickey for now, we disable this in-app. Please let us know when this fix rollout.

**Comment by visumickey** [comment]
This is all scheduled for a rollout early next week.
