### ISSUE TITLE
RemoteConfig fails to fetch data but reports success

### ISSUE THREAD

**Issue by olejnjak** [firebase/firebase-ios-sdk#4417]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.2.1
  * Firebase SDK version: 6.13.0
  * Firebase Component: RemoteConfig
  * Component version: 6.13.0 

### [REQUIRED] Step 3: Describe the problem

Ocassionally we experience a problem when Remote Config reports that its fetch succeeded, but after activating it all data is empty. And even reloading the config doesn't fix the problem (even if the cache period expires).

Is this some kind of known issue?

#### Steps to reproduce:

1. fetch config
2. check its data

We do not have much information about other conditions.

#### Relevant Code:

All our app does is that it calls 
```swift
Firebase.RemoteConfig.remoteConfig()fetch(withExpirationDuration: 43200) { _, _ in
    switch config.lastFetchStatus {
    case .success:
        Firebase.RemoteConfig.remoteConfig().activate()
        notifyNewConfigAvailable()
    case .failure:
        logRemoteConfigError(error)
    case .noFetchYet, .throttled: break
    @unknown default: break
    }
}
```

Then if observers determine that there is no data in config we record non-fatal error to Crashlytics.

```swift
if newConfigIsEmpty {
    let firConfig = Firebase.RemoteConfig.remoteConfig()

    // only keys with "homepage_" prefix are relevant for this case
    let configDict = firConfig.keys(withPrefix: "homepage_")
        .map { [$0: firConfig.configValue(forKey: $0).jsonValue] }
        .reduce([:]) { $0.merging($1) { x, _ in x } }

    var logDict: [String: Any] = configDict.nilsRemoved // `nilsRemoved` filters out keys with `nil` value
    logDict["fetch_status"] = firConfig.lastFetchStatus.rawValue

    let error = NSError(domain: "DISCOVER_EMPTY", code: 1, userInfo: nil)
    Crashlytics.sharedInstance().recordError(error, withAdditionalUserInfo: logDict)
}
```

We then we have in Crashlytics errors that say that config is empty (no keys are visible in Crashlytics) but `fetch_status` is 1 which corresponds with [success](https://firebase.google.com/docs/reference/ios/firebaseremoteconfig/api/reference/Enums/FIRRemoteConfigFetchStatus#/c:@E@FIRRemoteConfigFetchStatus@FIRRemoteConfigFetchStatusSuccess)

**Comment by dmandar** [comment]
Thanks for reporting. There is an issue with RC SDK returning success when the network is offline. https://github.com/firebase/firebase-ios-sdk/issues/4100. Also, to note, fetch calls return success today even if data was available in cache. You need to check for the return status of the subsequent activate call which will return false if the last fetched data (cached) was already activated. (We have an internal bug tracking this to make fetch return status more granular, current ETA is around next I/O time) You might also want to use the new fetchAndActivate call which returns granular success status: successFromRemote and successFromPrefetchedData.

**Comment by olejnjak** [comment]
Well, actually we don't really care if data is cached or not. The issue is that we then never receive the actual config...

**Comment by dmandar** [comment]
#4100 could have such symptoms since the fetch would have succeeded without fetching any config. Please retry once this fix lands. https://github.com/firebase/firebase-ios-sdk/pull/4438

**Comment by paulb777** [comment]
Closing and marking for M61 - 6.14.0
