### ISSUE TITLE
Performance SDK build error on Carthage: Undefined symbol: _OBJC_CLASS_$_GULObjectSwizzler

### ISSUE THREAD

**Issue by Johnson145** [firebase/firebase-ios-sdk#4419]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.0
  * Firebase SDK version: 6.13.0
  * Firebase Component: Performance
  * Component version: 6.13.0

### [REQUIRED] Step 3: Describe the problem
I'm trying to migrate my existing Firebase integration **from Cocoapods to Carthage**. I've managed to migrate all components except the **Performance SDK**.  The following build error occurs: `Undefined symbol: _OBJC_CLASS_$_GULObjectSwizzler`.

As far as I can see, this is a part of `GoogleUtilities.framework`, which I've already included though.

The only remaining idea I got is that it's an incompatibility with `Firebase **UI**`. As the latter doesn't support Carthage in the first place, I'm still including it via Cocoapods. It's not causing any issues with one of the other Firebase Components (Analytics, Storage, Firestore, AdMob..) though. I've already updated it to the latest version, too.

Any help is appreciated very much!

**Comment by paulb777** [comment]
yep the `_OBJC_CLASS_$_GULObjectSwizzler` should come with the `GoogleUtilities.framework`. Make sure that framework is actually being linked - it's in the `Link Binary With Libraries` Build Phase.

**Comment by Johnson145** [comment]
Added it the same way as all other frameworks: by dragging the file from the finder to the `Frameworks` section in XCode. Afterwars, I've selected the right targets. I can confirm it's in the `Link Binary With Libraries` section of the target's build phase, too.

**Comment by paulb777** [comment]
Hmm. Is the symbol actually there?

```
$ nm ./Carthage/Build/iOS/GoogleUtilities.framework/GoogleUtilities | grep _OBJC_CLASS_\$_GULObjectSwizzler
0000000000000768 S _OBJC_CLASS_$_GULObjectSwizzler
                 U _OBJC_CLASS_$_GULObjectSwizzler
```

**Comment by Johnson145** [comment]
Good idea. However, it's in there:
```
..
00000000000004f9 t -[GULObjectSwizzler isSwizzlingProxyObject]
0000000000000328 t -[GULObjectSwizzler setAssociatedObjectWithKey:value:association:]
0000000000000447 t -[GULObjectSwizzler swizzle]
00000000000004e5 t -[GULObjectSwizzler swizzledObjectHasBeenDeallocatedWithGeneratedSubclass:]
                 U _NSStringFromClass
0000000000000768 S _OBJC_CLASS_$_GULObjectSwizzler
                 U _OBJC_CLASS_$_GULSwizzledObject
                 U _OBJC_CLASS_$_NSObject
                 U _OBJC_CLASS_$_NSString
..
```

**Comment by Johnson145** [comment]
`GoogleUtilities` also seems to be added by Firebase UI. Extract from my `Podfile.lock`:

```
PODS:
..
  - Firebase/Auth (6.13.0):
    - Firebase/CoreOnly
    - FirebaseAuth (~> 6.4.0)
  - Firebase/CoreOnly (6.13.0):
    - FirebaseCore (= 6.4.0)
  - FirebaseAuth (6.4.0):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 6.2)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.2)
    - GoogleUtilities/Environment (~> 6.2)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseAuthInterop (1.0.0)
  - FirebaseCore (6.4.0):
    - FirebaseCoreDiagnostics (~> 1.0)
    - FirebaseCoreDiagnosticsInterop (~> 1.0)
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/Logger (~> 6.2)
  - FirebaseCoreDiagnostics (1.1.2):
    - FirebaseCoreDiagnosticsInterop (~> 1.0)
    - GoogleDataTransportCCTSupport (~> 1.0)
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/Logger (~> 6.2)
    - nanopb (~> 0.3.901)
  - FirebaseCoreDiagnosticsInterop (1.1.0)
  - FirebaseUI/Auth (8.4.0):
    - Firebase/Auth (~> 6.0)
    - GoogleUtilities/UserDefaults
  - FirebaseUI/Email (8.4.0):
    - FirebaseUI/Auth
  - FirebaseUI/Facebook (8.4.0):
    - FBSDKLoginKit (~> 5.0)
    - FirebaseUI/Auth
  - FirebaseUI/Google (8.4.0):
    - FirebaseUI/Auth
    - GoogleSignIn (~> 5.0)
  - FirebaseUI/Phone (8.4.0):
    - FirebaseUI/Auth
  - GoogleDataTransport (3.2.0)
  - GoogleDataTransportCCTSupport (1.2.2):
    - GoogleDataTransport (~> 3.2)
    - nanopb (~> 0.3.901)
  - GoogleSignIn (5.0.2):
    - AppAuth (~> 1.2)
    - GTMAppAuth (~> 1.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - GoogleUtilities/AppDelegateSwizzler (6.3.2):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (6.3.2)
  - GoogleUtilities/Logger (6.3.2):
    - GoogleUtilities/Environment
  - GoogleUtilities/Network (6.3.2):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (6.3.2)"
  - GoogleUtilities/Reachability (6.3.2):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (6.3.2):
    - GoogleUtilities/Logger
  - GTMAppAuth (1.0.0):
    - AppAuth/Core (~> 1.0)
    - GTMSessionFetcher (~> 1.1)
  - GTMSessionFetcher (1.3.0):
    - GTMSessionFetcher/Full (= 1.3.0)
  - GTMSessionFetcher/Core (1.3.0)
  - GTMSessionFetcher/Full (1.3.0):
    - GTMSessionFetcher/Core (= 1.3.0)
  - nanopb (0.3.9011):
    - nanopb/decode (= 0.3.9011)
    - nanopb/encode (= 0.3.9011)
  - nanopb/decode (0.3.9011)
  - nanopb/encode (0.3.9011)
  - PersonalizedAdConsent (1.0.3)

DEPENDENCIES:
  - Crashlytics (~> 3.12.0)
  - Fabric (~> 1.9.0)
  - FirebaseUI/Auth
  - FirebaseUI/Email
  - FirebaseUI/Facebook
  - FirebaseUI/Google
  - FirebaseUI/Phone
  - PersonalizedAdConsent

SPEC REPOS:
  trunk:
    - AppAuth
    - Crashlytics
    - Fabric
    - FBSDKCoreKit
    - FBSDKLoginKit
    - Firebase
    - FirebaseAuth
    - FirebaseAuthInterop
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseCoreDiagnosticsInterop
    - FirebaseUI
    - GoogleDataTransport
    - GoogleDataTransportCCTSupport
    - GoogleSignIn
    - GoogleUtilities
    - GTMAppAuth
    - GTMSessionFetcher
    - nanopb
    - PersonalizedAdConsent

SPEC CHECKSUMS:
  AppAuth: 73574f3013a1e65b9601a3ddc8b3158cce68c09d
  Crashlytics: 07fb167b1694128c1c9a5a5cc319b0e9c3ca0933
  Fabric: f988e33c97f08930a413e08123064d2e5f68d655
  FBSDKCoreKit: 5aada61a229054694810f3cee231f986004b3c49
  FBSDKLoginKit: 0e4572e0279e477103b57978e3ea05fac1dd673d
  Firebase: 458d109512200d1aca2e1b9b6cf7d68a869a4a46
  FirebaseAuth: 7d0f84873926f6648bbd1391a318dfb1a26b5e4f
  FirebaseAuthInterop: 0ffa57668be100582bb7643d4fcb7615496c41fc
  FirebaseCore: 307ea2508df730c5865334e41965bd9ea344b0e5
  FirebaseCoreDiagnostics: 511f4f3ed7d440bb69127e8b97c2bc8befae639e
  FirebaseCoreDiagnosticsInterop: e9b1b023157e3a2fc6418b5cb601e79b9af7b3a0
  FirebaseUI: 433550cb9e3d03ec7ee2c25f87493f76358d9b68
  GoogleDataTransport: 8e9b210c97d55fbff306cc5468ff91b9cb32dcf5
  GoogleDataTransportCCTSupport: ef79a4728b864946a8aafdbab770d5294faf3b5f
  GoogleSignIn: 7137d297ddc022a7e0aa4619c86d72c909fa7213
  GoogleUtilities: 547a86735c6f0ee30ad17e94df4fc21f616b71cb
  GTMAppAuth: 4deac854479704f348309e7b66189e604cf5e01e
  GTMSessionFetcher: 43b8b64263023d4f32caa0b40f4c8bfa3c5f36d8
  nanopb: 18003b5e52dab79db540fe93fe9579f399bd1ccd
  PersonalizedAdConsent: b50a8a5d6065b6db23121e8fcc0dce2ae983f6ea

PODFILE CHECKSUM: 7059d11e48261a448805bb674fc86c4fe3c73c5c

COCOAPODS: 1.8.4
```

**Comment by paulb777** [comment]
That could explain it.  There are likely two copies of GoogleUtilities in the app - one statically linked with `_OBJC_CLASS_$_GULObjectSwizzler` and one dynamically linked without it.

A workaround to get it to build might be to add `pod 'GoogleUtilities/ISASwizzler'` to the Podfile.  However, it's risky to have two copies of the same library in the same app, so the recommended next step would be to remove the static GoogleUtilities.framework from the app and add any other necessary GoogleUtilities subspecs to the CocoaPods version.

**Comment by Johnson145** [comment]
Unfortunately, this doesn't prevent the error either.

There is no way to do it the other way around, is it? So dropping the redundant (nested) dependencies from Cocoa and using only the `.framework` files from Carthage?

**Comment by Johnson145** [comment]
A full ´pod 'GoogleUtilities'´ works though :)

**Comment by paulb777** [comment]
Great! I'll close this out now since it looks like a resolution, but feel free to continue the conversation.

**Comment by Johnson145** [comment]
Yes, I guess the original issue is solved that way. Thanks for your help!

Just a quick follow up on my previous thought:
> There is no way to do it the other way around, is it? So dropping the redundant (nested) dependencies from Cocoa and using only the .framework files from Carthage?

Because of Firebase UI not supporting Carthage, I'm now actually including quite a lot of Firebase components as CocoaPods instead of using their existing Carthage dependency. That's quite unsatisfying. Any thoughts on this?

As this isn't exactly about the original issue anymore and I think this may boil down to a general (non-Firebase-specific) problem, [I've asked a new question on stackoverflow](https://stackoverflow.com/questions/59156287/replace-nested-cocoapods-with-carthage-dependency-firebase-ui-and-firebase-comp).

**Comment by paulb777** [comment]
One option in the near future is the CocoaPods -> binary zip builder that we're almost done with. See https://github.com/firebase/firebase-ios-sdk/pull/4422 and https://github.com/firebase/firebase-ios-sdk/blob/master/ZipBuilder/ZipBuilderV2Plan.md
