### ISSUE TITLE
Firebase 6.13.0 Not Loading, no visible error log. 

### ISSUE THREAD

**Issue by quinamatics** [firebase/firebase-ios-sdk#4443]
Hi, my app (Xcode 11.2.1, Firebase 6.13.0) simply outputs a blank screen on the simulator (and also ios 13 iphone) upon running. This problem has happened twice today, often after hours of working without issue or code changes. No Crashlytics or console reports.  Don't know how to fix this. My bundle identifiers are consistent across GoogleService-info.plist and in Target. I also configure FirebaseApp.configure() properly. 

I also have phone number authentication in the App, but even after hardcoding true for isAppVerificationDisableForTesting, the app still shows a blank screen. My code is as follows:

<img width="781" alt="Screen Shot 2019-12-05 at 2 50 47 AM" src="https://user-images.githubusercontent.com/28470823/70214804-0ccb8e00-170a-11ea-9da6-ff25eebb1aeb.png">

This is a massive problem as I don't want users to have this problem when I deploy the app.

Here is the console log: 
<img width="420" alt="Screen Shot 2019-12-05 at 2 32 32 AM" src="https://user-images.githubusercontent.com/28470823/70213511-7eeea380-1707-11ea-9232-25184f47d12a.png">

 
And here is my screen when I load 
<img width="465" alt="Screen Shot 2019-12-05 at 2 32 56 AM" src="https://user-images.githubusercontent.com/28470823/70213542-8d3cbf80-1707-11ea-9cb3-c530d2d44757.png">

**Comment by rizafran** [comment]
Thanks for reporting this issue, @quinamatics. Upon checking your logs, looks like it's not related to the issue you're having in which your app loads a blank page. To clarify, may I know the steps that lead to the blank page?

**Comment by quinamatics** [comment]
Actually, upon reseting the app and running again, inputting my phone number into the simulator gives the following error in the Firebase popup: If app delegate swizzling is disabled, remote notifications received by UIApplicationDelegate need to be forwarded to FIRAuth's canHandleNotificaton: method.

I tried following the tutorial for enabling reCAPTCHA here: https://firebase.google.com/docs/auth/ios/phone-auth

but when I try to handle push notification the Xcode compiler outputs "notification not found". The notification variable corresponds to this following code segment. 

<img width="652" alt="Screen Shot 2019-12-05 at 1 07 05 PM" src="https://user-images.githubusercontent.com/28470823/70261308-25ff2980-1760-11ea-9412-96992320276d.png">

What's weirder is that my code has compiled without fault for a few hours and suddenly when I run it as was the screen became blank. It has stayed blank ever since.

**Comment by quinamatics** [comment]
Hi, upon logging in from a different network there appears to be an error log now. Here it is:

<img width="436" alt="Screen Shot 2019-12-05 at 5 05 20 PM" src="https://user-images.githubusercontent.com/28470823/70278048-818ddf00-1781-11ea-88c1-729a3e43e015.png">

**Comment by rizafran** [comment]
Hi @quinamatics, please allow me to understand the issue:
1. Is this also happening to real device?
2. Does the issue appear in all iOS versions?
3. Originally, are you using reCAPTCHA flow or silent APNs notif to verify phone number?

It would also be helpful if you could provide a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) that I can run locally.
