### ISSUE TITLE
157239639: dynamic_link_app_open and dynamic_link_first_open events are swapped

### ISSUE THREAD

**Issue by pmendesTekever** [firebase/firebase-ios-sdk#4461]
I'm tracking events on DebugView and I noticed this:

**dynamic_link_app_open** is sent when the user opens the app for the first time through a DL.
**dynamic_link_first_open** is sent when the user opens the app through a DL (if it already had the app installed)

I debugged the issue and found that on **FIRDynamicLinks.m**, isFirstOpen is the following:

`BOOL isFirstOpen = ![_userDefaults boolForKey:kFIRDLReadDeepLinkAfterInstallKey];
`

and it should be:
`BOOL isFirstOpen = [_userDefaults boolForKey:kFIRDLReadDeepLinkAfterInstallKey]; `

Is there anything regarding this?
Thank you.

**Comment by dmandar** [comment]
Hi, the code seems ok as is. kFIRDLReadDeepLinkAfterInstallKey is created upon install and is present thereafter. Hence, isFirstOpen will be true only when the key is absent (the first app open). Please reopen if you are still seeing issues with this behavior.

**Comment by pmendesTekever** [comment]
Exactly, **isFirstOpen** should be **false** for users that have already used the app.
Every time my users open the app through a DL, firebase sends a **dynamic_link_first_open**.

![Screenshot 2020-01-31 at 14 29 25](https://user-images.githubusercontent.com/57406749/73547095-336e2280-4436-11ea-9189-b0dd25a199ef.png)

**Comment by morganchen12** [comment]
The code snippet is fine, but it looks like something else is causing the dynamic links SDK to send a dynamic_link_first_open multiple times for the same app. `isFirstOpen` should be set to false if user defaults returns true, so either the bool is not being set or it's being set to false somewhere else after being set to true.

@dmandar, can you take another look?

**Comment by morganchen12** [comment]
@rizafran, can you try to repro this issue? If it does repro, can you share the repro project here?

**Comment by rizafran** [comment]
Noted on this, @morganchen12.

**Comment by rizafran** [comment]
Hi @morganchen12, the current behavior on my end is that both `dynamic_link_first_open` and `dynamic_link_app_open` were logged on my Analytics dashboard when I opened the app for the first time from FDL. Based on my understanding [here](https://firebase.google.com/docs/dynamic-links/analytics#google-analytics), `dynamic_link_app_open` should be logged when a user re-opens the app through FDL, but it was logged even on opening the app for the first time. I'm just using quickstart for Dynamic Link.

**Comment by morganchen12** [comment]
@dmandar looks like there's a bug in the first open logic.

**Comment by ibuda** [comment]
@pmendesTekever Hi, may I ask you what is the app/service you are using to see user's interactive events ordered consecutively on a timeline?

**Comment by pmendesTekever** [comment]
It's on my firebase console ->DebugView

**Comment by paulb777** [comment]
Closing for staleness. Please comment or open a new issue to reopen.
