### ISSUE TITLE
Error message shows when configuring default Firebase manually

### ISSUE THREAD

**Issue by bofeizhu** [firebase/firebase-ios-sdk#4467]
#### Environment:
  * Xcode version: 11.2
  * Firebase SDK version: 6.13.0
  * Firebase Component: Core
  * Component version: 6.13.0

#### Problem:
Error message ``` The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization.``` shows when configuring Firebase using `FirebaseApp.configure(options: options)`.

#### Steps to reproduce:
Configure Firebase using `FirebaseApp.configure(options: options)` in `application( _ :didFinishLaunchingWithOptions:)` instead of `Firebase.configure()`.

**Comment by morganchen12** [comment]
Can you check your app's console log output to make sure there's no duplicate symbols at runtime? Also, how are you integrating the Firebase frameworks?
