### ISSUE TITLE
Undefined symbols for architecture x86_64:   "absl::lts_2019_08_08::AlphaNum" When building

### ISSUE THREAD

**Issue by UMAD** [firebase/firebase-ios-sdk#4472]
* Xcode version: 11.2.1
  * Firebase SDK version: 6.13.0?
  * Firebase Component: Firestore
  * Component version: 6.13.0

I use Firebase on iOS (mainly for Firestore) and have been working fine. Today I have updated Firebase with Carthage to version 6.13.0 and now my project fails to build with the following errors:

```
Undefined symbols for architecture x86_64:
  "absl::lts_2019_08_08::AlphaNum::AlphaNum(absl::lts_2019_08_08::Hex)", referenced from:
      firebase::firestore::nanopb::PrintHeader(int, absl::lts_2019_08_08::string_view, void const*) in FirebaseFirestore(pretty_printing.o)
  "absl::lts_2019_08_08::Base64Escape(absl::lts_2019_08_08::string_view, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)", referenced from:
      firebase::firestore::local::DescribeKey(leveldb::Slice) in FirebaseFirestore(leveldb_key.o)
  "absl::lts_2019_08_08::StrAppend(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, absl::lts_2019_08_08::AlphaNum const&, absl::lts_2019_08_08::AlphaNum const&, absl::lts_2019_08_08::AlphaNum const&, absl::lts_2019_08_08::AlphaNum const&)", referenced from:
      firebase::firestore::remote::Datastore::GetWhitelistedHeadersAsString(std::__1::multimap<grpc::string_ref, grpc::string_ref, std::__1::less<grpc::string_ref>, std::__1::allocator<std::__1::pair<grpc::string_ref const, grpc::string_ref> > > const&) in FirebaseFirestore(datastore.o)
  "absl::lts_2019_08_08::AlphaNum::AlphaNum(absl::lts_2019_08_08::Hex)", referenced from:
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > firebase::firestore::util::StringFormat<firebase::firestore::remote::RemoteStore*>(char const*, firebase::firestore::remote::RemoteStore* const&) in FirebaseFirestore(remote_store.o)
```

<img width="1269" alt="Screenshot 2019-12-10 at 14 54 18" src="https://user-images.githubusercontent.com/84855/70535225-f6d02a00-1b5c-11ea-81b3-604ddba48eef.png">

<img width="1245" alt="Screenshot 2019-12-10 at 14 52 11" src="https://user-images.githubusercontent.com/84855/70535148-cd170300-1b5c-11ea-97ad-417426ee881f.png">

My cart file looks like this:

```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseFirestoreBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseFunctionsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAuthBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseStorageBinary.json"
binary "https://building42.github.io/Specs/Carthage/iOS/Fabric.json"
binary "https://building42.github.io/Specs/Carthage/iOS/Crashlytics.json"
```

Is this a bug or is there something that has changed that I am not aware of? Thanks in advance!

**Comment by paulb777** [comment]
@UMAD It looks like you didn't add in the absl.framework that is now installed with Firestore.

**Comment by UMAD** [comment]
@paulb777 That was indeed the issue. Thanks! I didn't notice that this abseil.framework was downloaded when I did an update. Is there a newsletter or somewhere I can subscribe or some feed where I can see the release notes? Downloading updates that break builds then having to fish around for "what's new" doesn't seem to be idle.

**Comment by paulb777** [comment]
@UMAD Glad that worked!

The release notes are here - https://firebase.google.com/support/release-notes/ios.

Making a newsletter/mailing list/subscription for the release notes is a great suggestion. @morganchen12 what do you think?

**Comment by morganchen12** [comment]
We used to have a twitter feed, but that stopped being updated when Alex moved off the team. @samtstern should we revive it?

**Comment by wilhuff** [comment]
Given the technical part of this issue is resolved, I'm going to close the issue. If there's further discussion about how best to publicize this feel free to continue discussion here or create a new issue.

@UMAD note that it's usually worth taking a spin through the release notes when upgrading anyway. Besides changes to dependencies this is a good way to see if there are fixes that might affect you or find out about new features.
