### ISSUE TITLE
Crashlytics Veracode Issue on FABNetworkClient.m

### ISSUE THREAD

**Issue by robimoltewhp** [firebase/firebase-ios-sdk#4475]
Hello,

I am using Veracode Tool for code static analysis
https://www.veracode.com
and I am facing one security issue on Crashlytics component

Xcode version: 10.3
Firebase SDK version: 6.13.0
Firebase Component: Crashlytics
Version: 3.13.2
The issue says:

File - FABNetworkClient.m: 189

"Description: In this call to FABNetworkClient.completionHandler:(), host-specific certificate data is not validated or is incorrectly validated. Failing to validate the certificate makes the SSL session susceptible to a man-in-the-middle attack.
Remediation: Verify that the certificate is valid, matches the requested site, and is signed by a trusted root authority. Generate an error and destroy the connection if any of these conditions are not met."

**Comment by samedson** [comment]
See https://github.com/firebase/firebase-ios-sdk/issues/4478#issuecomment-564728528
