### ISSUE TITLE
Crashlytics Veracode Issue on FABCLSUserDefaults.m

### ISSUE THREAD

**Issue by robimoltewhp** [firebase/firebase-ios-sdk#4476]
Hello,

I am using Veracode Tool for code static analysis
https://www.veracode.com
and I am facing one security issue on Crashlytics component

Xcode version: 10.3
Firebase SDK version: 6.13.0
Firebase Component: Crashlytics
Version: 3.13.2
The issue says:

File - FABCLSUserDefaults.m: 232

"Description: This call to NSFileManager.setAttributes:ofItemAtPath:error:() exposes potentially sensitive data. This could allow private data such as cryptographic keys or other sensitive information to be erroneously exposed.
Remediation: Ensure that the application protects all sensitive data from unnecessary exposure."

**Comment by samedson** [comment]
Crashlytics does not save sensitive data to disk. In addition, users should never log sensitive data through Crashlytics.

The reason we are modifying file contents is to capture crashes that happen when a phone is locked. Without this, if your app crashed while the user had the phone locked, we wouldn't be able to generate a crash report.
