### ISSUE TITLE
Crashlytics Veracode Issue on ANSUploader.m

### ISSUE THREAD

**Issue by robimoltewhp** [firebase/firebase-ios-sdk#4478]
Hello,

I am using Veracode Tool for code static analysis
https://www.veracode.com
and I am facing one security issue on Crashlytics component

Xcode version: 10.3
Firebase SDK version: 6.13.0
Firebase Component: Crashlytics
Version: 3.13.2
The issue says:

File - ANSUploader.m: 343

"Description: In this call to ANSUploader.completionHandler:(), host-specific certificate data is not validated or is incorrectly validated. Failing to validate the certificate makes the SSL session susceptible to a man-in-the-middle attack.
Remediation: Verify that the certificate is valid, matches the requested site, and is signed by a trusted root authority. Generate an error and destroy the connection if any of these conditions are not met"

**Comment by samedson** [comment]
Crashlytics uses certificate pinning to ensure we're always sending the crashes to the right SSL endpoint using `SecTrustSetAnchorCertificates`, `SecTrustSetAnchorCertificatesOnly`, and `SecTrustEvaluate`. Veracode does not seem to pick this up.
