### ISSUE TITLE
Remove deprecated sync -[FIRInstanceID appInstanceID:] method

### ISSUE THREAD

**Issue by maksymmalyhin** [firebase/firebase-ios-sdk#4486]
The method must be removed and [[FIRInstanceID appInstanceID:] ](https://github.com/firebase/firebase-ios-sdk/blob/0831e2d677be376495fe1fcb8fbb0e282afc505b/Firebase/InstanceID/Private/FIRInstanceID%2BPrivate.h#L59), all usages must be replaced the the async alternative.

**Comment by chliangGoogle** [comment]
If other SDKs like analytic stop using this, we should remove it. Thanks for filing this!

**Comment by maksymmalyhin** [comment]
All Firebase SDKs (except FCM so far) have been updated to use FIS directly, but the method may still be used in some 1P tests.

**Comment by chliangGoogle** [comment]
I think it's okay to remove it. I couldn't find any 1P depending on it anymore.

**Comment by paulb777** [comment]
We need to wait for Firebase 7 - because earlier Firebase 6 versions of other pods allow minor version updates of IID. If an old version of Firebase Analytics updates and this API is removed, the build will break.
