### ISSUE TITLE
handleUniversalLink completion handler does not get called when dynamic link has a space in it

### ISSUE THREAD

**Issue by MarkBorazio** [firebase/firebase-ios-sdk#4487]
_I have looked through the similar issue faced [here](https://github.com/firebase/firebase-ios-sdk/issues/2447) and found no help._
### Environment

  * Xcode version: 11.1
  * Firebase SDK version: 6.10.0
  * Firebase Component: DynamicLinks
  * Component version: 4.0.5

### Description

I am finding that the function `handleUniversalLink` is not having its completion handler called when the given url has a space (`%20` symbol) in it. The function also returns `false` in this case.

Here is an example URL I am using:
```
https://example.page.link/?link=https%3A%2F%2Fexample.org%2Fdeeplinks%2Fpatients%2Fconnect%3FpracticeId%3DP0tzaE2XXU33uLDjmUuf%26clinicianId%3DKbLDL07O02M5vhX6vKORcREQdDl1%26name%3Dal%20mond%26dobDay%3D05%26dobMonth%3D02%26dobYear%3D1985&apn=au.org.example2&isi=1111111111&ibi=au.org.example
```
_Note the `%20` between 'al' and 'mond' for the `name` parameter._

The dynamic link is setup in the Firebase project with the appropriate domain.
We are manually constructing the link parameter with the appropriate parameters (such as `name`) and manually creating the dynamic link.

When the link is tapped, the app automatically opens, and we receive the `webpageURL` to pass into the `handleUniversalLink` function. This function then returns false and the completion handler is never called.

When I inspect `webpageURL`, I can see that the `%20` symbols are still there. As far as I know, these should be converted to `%2B`, which is the `+` symbol. **The really interesting part here is that this only occurs if the app was automatically opened when tapping the link.** 
If the app is not yet installed, and tapping the link opened Safari where the user the user then proceeds to install the app, the received url in `AppDelegate` has its `%20` symbols replaced already. In fact, I even noticed this when the app was installed, tapping the link took me to Safari, but tapping the 'open' button in the preview page opened the app (I have no idea why the app didn't open automatically in the first place).

#### Steps to reproduce:

1. Install app
2. Tap on dynamic link
3. Make sure app opens automatically (not in Safari) 
4. Observe that `userActivity.webpageURL` still has `%20` symbols in it
5. Observe that `handleUniversalLink(userActivity.webpageURL)` returns false and its completion handler is not called

#### Relevant Code:

```
    func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
        guard let webpageURL = userActivity.webpageURL else {
            return false
        }
        
        let handled = DynamicLinks.dynamicLinks().handleUniversalLink(webpageURL) { (dynamicLink, error) in
            guard error == nil, let dynamicLinkURL = dynamicLink?.url else {
                return
            }
            print(dynamicLink)
        }
        
        print("handled: \(handled)")
        return handled
    }
```

**Comment by rizafran** [comment]
Thanks for reporting, @MarkBorazio. I'll try to reproduce the issue on my end, and I'll let you know with my findings.

**Comment by rizafran** [comment]
@MarkBorazio By following the steps to reproduce and using your sample URL, I noticed that the `userActivity.webpageURL` is still having `%20` symbols, but the `handleUniversalLink(userActivity.webpageURL)` returns true. I'm using the [latest SDK version](https://firebase.google.com/support/release-notes/ios).

**Comment by rizafran** [comment]
@MarkBorazio I just figured out why `handleUniversalLink(userActivity.webpageURL)` returns false on your end. The reason might be `https%3A%2F%2Fexample.org` doesn't recognized as a valid URL. When you try to add it in your console, you'll get an error "Please enter a valid URL starting with http:// or https://" (see attached screenshot).

![fdl](https://user-images.githubusercontent.com/56452638/70928360-da0b8900-206b-11ea-8df1-43a7fafac1f1.png)

**Comment by morganchen12** [comment]
@rizafran you may need to undo the percent-escaping.

**Comment by mbuchetics** [comment]
I have the same issue as the original poster.

**Comment by dmandar** [comment]
Hi @MarkBorazio FDL returns an NSURL constructed out of a string by removing percent encoding. Since NSURL does not allow spaces in the string being passed, unfortunately, this will not work as is. You might want to try double encoding your string, but i believe the console might want you to prepend an extra https to consider it a valid URL and things could get complicated. I will also chat up with the team for adding an extra constraint in the FDL create link page so it is apparent that spaces are not supported on iOS.
