### ISSUE TITLE
[AB Testing] Test devices not getting desired value

### ISSUE THREAD

**Issue by tspecht** [firebase/firebase-ios-sdk#4497]
* Xcode version: 11.2.1
  * Firebase SDK version: 6.13.0
  * Firebase Component: RemoteConfig
  * Component version: 6.13.0

When trying to use test devices with Firebase RemoteConfig on iOS, the device referenced in the console by it's Instance ID does not receive any value other than the control.  

#### Steps to reproduce:

When using the code below, the test device in use (both simulator as well as physical device), does not receive the test cohort configured for it in the A/B testing console.

#### Relevant Code:

```
        let remoteConfig = RemoteConfig.remoteConfig()
        remoteConfig.setDefaults(remoteConfigDefaults)

        let expirationDuration: TimeInterval
        #if DEBUG || FEATURE || BETA
        expirationDuration = 0
        #else
        expirationDuration = 3600
        #endif

        #if DEBUG || FEATURE || BETA
        InstanceID.instanceID().instanceID { (result, error) in
            if let error = error {
                print("Error fetching remote instance ID: \(error)")
            } else if let result = result {
                print("Remote Firebase instance ID token: \(result.token)")
            }
        }
        #endif

        remoteConfig.fetch(withExpirationDuration: expirationDuration) { (_, error) in
            if let error = error {
                print("🚨 Firebase Remote Config Error 🚨 -> \(error)", error.humanReadableDescription)
            }
            remoteConfig.activateFetched()

            for key in remoteConfig.keys(withPrefix: nil) {
                // This here contains the default value and not the one set for the test device in the A/B testing console
                print("Remote config \(key): \(remoteConfig.configValue(forKey: key).stringValue)")
            }
        }
```

**Comment by morganchen12** [comment]
Hey @tspecht. The AB Testing SDK is pretty tiny and doesn't do that much, so I suspect this is an issue with the backend. To be sure, though, can you share the debug logs from running your app and reproducing the error?

**Comment by morganchen12** [comment]
Looks like there's potentially a backend issue that could be causing experiments to not be loaded properly. Currently under investigation by oncall (Googlers see b/146220296)

**Comment by clp93** [comment]
Hey @tspecht thanks for the report. As @morganchen12 this looks like a backend issue. There's a rollback in flight

**Comment by tspecht** [comment]
@clp93 thanks for the update. Is there an ETA on when the rollback should be complete?

**Comment by clp93** [comment]
@tspecht Rollback should be complete within ~15min. At that point, changing **any** ABT experiment should get all experiments in bad states out of those bad states

**Comment by clp93** [comment]
We're also gonna fix any experiments that ended up in that bad state. 

https://status.firebase.google.com/incident/AB%20Testing/19002 has more in depth info

**Comment by clp93** [comment]
All experiments that were in the bad state have been fixed.

@tspecht I'm going to go ahead and close out the issue. Please reopen if necessary. Thanks for working with us  on this!

**Comment by tspecht** [comment]
@clp93 thanks for the fix, seems to be working better now, we'll continue testing. I just wanted to point out that this issue seemingly existed for the last roughly 2 weeks, maybe that helps investigating internally.

**Comment by clp93** [comment]
Thanks for the info. I'll forward it on to the A/B Testing team
