### ISSUE TITLE
I see the problem now. Thanks for your patience. I should have remembered this one sooner.

### ISSUE THREAD

**Issue by CVRamana** [firebase/firebase-ios-sdk#4502]
I see the problem now. Thanks for your patience. I should have remembered this one sooner.

These are warnings generated by the Protobuf CocoaPod when it is built as a static library because of clang bug with file name casing - see https://github.com/google/protobuf/issues/3218.

It's an error for you because your Podfile is treating all warnings as errors.

Workarounds include allowing warnings for the Protobuf library build or adding `use_frameworks!` to the Podfile.

_Originally posted by @paulb777 in https://github.com/firebase/firebase-ios-sdk/issues/1419#issuecomment-399455175_

it will give the warning with the import.
Solution=> Fix the warning by replacing  " &lt Firebase &gt"  with  'Firebase'

**Comment by paulb777** [comment]
It's not clear what the issue is here since it quotes an old resolved issue.
