### ISSUE TITLE
Getting Deprecated API Usage Warning after adding firebase plugin(ITMS-90809)

### ISSUE THREAD

**Issue by Sagarkhenat** [firebase/firebase-ios-sdk#4531]
I am using a hybrid ionic-cordova app for which after adding the cordova-plugin-firebase plugin I am getting the warning mail regarding the deprecated UIWebView usage in my app. I searched for the UIWebView code by doing grep -r "UIWebView" . for which I received the binary files,
Binary file ./Plugins/cordova-plugin-firebase/Crashlytics.framework/Crashlytics matches
Binary file ./Plugins/cordova-plugin-firebase/FirebaseAuth.framework/FirebaseAuth matches.
I wanted to know how to update the podfiles if the updated pods have removed the UIWebView code. The Crashlytics and FirebaseAuth are causing for the warning flag to be raised. Any kind of help will be appreciated.

**Comment by rizafran** [comment]
Hi @Sagarkhenat, UIWebview was removed from the previous releases of Firebase iOS SDK. I'm not sure with cordova-plugin-firebase plugin, but as far as I know, this plugin is developed by the community and not an official Firebase SDK. You may try to file directly to [cordova-plugin-firebase Github issue](https://github.com/arnesson/cordova-plugin-firebase/issues).

**Comment by samedson** [comment]
Hey @Sagarkhenat make sure the Crashlytics SDK is at version `3.14.0`. We removed all UIWebView code at that version

**Comment by Sagarkhenat** [comment]
@samedson, @rizafran  Thanks for the help, do you know how I can check for the version of Crashlytics SDK in a specific plugin, and if I want to update the SDK version, how I am able to do that?

**Comment by rizafran** [comment]
@Sagarkhenat, If you're using Pods to install Firebase SDK, you can check your dependencies' versions to Podfile.lock file. To update to the latest version, run `pod update` command.

For the Cordova plugins, I'm not familiar on how to check version of Crashlytics SDK in a specific plugin. As per [cordova-plugin-firebase docs](https://www.npmjs.com/package/cordova-plugin-firebase), looks like their latest version was published a year ago.
