### ISSUE TITLE
Insecure Storage: Unspecified Keychain Access Policy

### ISSUE THREAD

**Issue by gopalchinnadurai** [firebase/firebase-ios-sdk#4542]
We have used FirebaseInstanceID 4.2.5 as per our need. Some VAPT points are mentioned in below picture. Kindly help us asap.

**Issue Summary:**
On line 100 of FIRInstanceIDKeychain.m, the method ^{}() stores data in the Keychain without specifying an accessibility level.The identified method stores data in the Keychain without specifying an accessibility level.

**Issue Screenshot**

<img width="622" alt="Screenshot 2019-12-23 at 4 44 02 PM" src="https://user-images.githubusercontent.com/55129685/71355249-74a42480-25a4-11ea-96fe-c709a4e205fc.png">

**Comment by morganchen12** [comment]
@chliangGoogle from what I understand the IID data in keychain is not sensitive data, but it may still be good to explicitly set an access level.

**Comment by maksymmalyhin** [comment]
@gopalchinnadurai Thank you for sharing this finding!

Could you double check FirebaseInstanceID version you are using when running the VAPT tool? I could not find the specified code in the version 4.2.5. (not sure maybe it is modified by the tool before printing somehow).

In the most recent FirebaseInstanceID version [4.2.8](https://github.com/firebase/firebase-ios-sdk/releases/tag/InstanceID-4.2.8) the access level is explicitly specified [here](https://github.com/firebase/firebase-ios-sdk/blob/20ab31fe130e9a1d22a75b35ba7046cfba0e5a47/Firebase/InstanceID/FIRInstanceIDAuthKeyChain.m#L196), so this should not be a concern.

Will it be possible to run the analysis with 4.2.8? Please let us know if you keep getting any issues with FirebaseInstanceID.
