### ISSUE TITLE
Firebase dynamic link stopped working in some case.

### ISSUE THREAD

**Issue by Narendra-Pandey** [firebase/firebase-ios-sdk#4543]
* Xcode version: 11.1
  * Firebase SDK version: 5
    Dynamic Link

###  The problem

 I am using Firebase Dynamic link, Followed steps like added DNS host server, (adding txt key)
created dynamic link and shared. it works perfect.

But when I delete application and check in safari. it go to App Store. -> This is perfect.

now again I installed the applications and check that link in safari it always navigate to App Store.

this is not persistent as I try multiple times around 1 hour and after dynamic link works automatically without changing a single line of code.

#### Steps to reproduce:

1. Create dynamic link
2. Assuming that app is installed
3. copy the link in safari and tap on open 
4. it will navigate to application
5. Now delete the app and go to safari
6. it will navigate to App Store
7. Again install the app
8. go to safari and click on open app
9. now onwards it will navigate to App Store always despite of app installed, then also

**Comment by rizafran** [comment]
Thanks for the report, @Narendra-Pandey. I'll try to reproduce the issue on my end, and I'll let you know with my findings.

**Comment by Narendra-Pandey** [comment]
@google-admin @rizafran  here is the Screen shot when I try to open link in safari from simulator. 
![Simulator Screen Shot - iPhone 11 Pro - 2019-12-23 at 17 58 52](https://user-images.githubusercontent.com/59040935/71358171-1714d580-25ae-11ea-98bf-907ab2df1a26.png)

Kindly information: This was working since one month and stopped working from yesterday, Also after trying 3 hour, started working again. Now today it's stopped working. 

seems weird.

**Comment by Narendra-Pandey** [comment]
@google-oss-bot  @rizafran Also I have tested in Actual device this always go to App Store.

seems like something issue with firebase server.

**Comment by Narendra-Pandey** [comment]
@gabrc @google-oss-bot @rizafran @jeremydurham @mbleigh Also I have diagnosed the dynamic link with this 

`[FIRDynamicLinks performDiagnosticsWithCompletion:nil];
`
and got this :

**WARNING: iOS Simulator does not support Universal Links. Firebase Dynamic Links SDK functionality will be limited. Some FDL features may be missing or will not work correctly.
	Specified custom URL scheme is dlscheme and Info.plist contains such scheme in CFBundleURLTypes key.
performDiagnostic completed successfully! No errors found.**

**Comment by rizafran** [comment]
@Narendra-Pandey I can't seem to replicate the same behavior using the [iOS quickstart](https://github.com/firebase/quickstart-ios/tree/master/dynamiclinks) running on actual device. May I know if you're using the [latest version of SDK](https://firebase.google.com/support/release-notes/ios)? What iOS version you're using? You may also provide a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) that I run locally.

Additionally, make sure that you have setup the following:
1. Associated Domains entitlements - `applinks:mydomain.page.link`
2. Verify that the AASA file is correct at https://sample.domain.com/apple-app-site-association
3. Verify that your team ID is properly set in the Firebase console.

As for the warning, looks like it only shows when running in simulator. When you're running in actual device, what message did you get in` [FIRDynamicLinks performDiagnosticsWithCompletion:nil];`?

**Comment by Narendra-Pandey** [comment]
@rizafran  Thanks for the comments.

yes I have added all three steps. As it was already working from one month. Also the same issue was there on 2 days before. 

but from yesterday it completely stopped working. may be this is the issue from firebase server. or something else from domain side. 

no idea why this happened.

**Comment by morganchen12** [comment]
@Narendra-Pandey, are you able to long-press the `Open` link and open it in the installed app? You may be running into an iOS system behavior.

**Comment by Narendra-Pandey** [comment]
@morganchen12    @gabrc  @google-oss-bot  @rizafran  @morganchen12  @mbleigh  it's weird behaviour, I have installed in 12.4 device (iPhone 6). 

This app was already installed, created dynamic link and checked in safari it's works.

But when I checked in iPhone 13.0 OS. it doesn't work at all. 

For confirmation of OS, I have checked in older I.e 12.4 simulator, but no luck. didn't working there also.

**Comment by Narendra-Pandey** [comment]
@rizafran @gabrc @google-admin @morganchen12 @mbleigh 

This is the actual devices, This [FIRDynamicLinks performDiagnosticsWithCompletion:nil]; gives us this log.

**---- Firebase Dynamic Links diagnostic output start ----
Firebase Dynamic Links framework version 3.4.3
System information: OS iOS, OS version 12.4.3, model iPhone
Current date 2019-12-24 09:41:36 +0000
Device locale en-US (raw en_US), timezone Pacific/Honolulu
	Specified custom URL scheme is dlscheme and Info.plist contains such scheme in CFBundleURLTypes key.
	AppID Prefix: NP7DTFPFD7R, Team ID: NP7DTFPFD7R, AppId Prefix equal to Team ID: YES
performDiagnostic completed successfully! No errors found.**

**Comment by Narendra-Pandey** [comment]
@google-oss-bot @rizafran @morganchen12 @mbleigh 

one thing I have checked, https://[Domain]/apple-app-site-association

this gives me the empty team name in details. Now I don't know how to update this association.

{"applinks":{"apps":[],"details":[]}}

**Comment by Narendra-Pandey** [comment]
@google-oss-bot  @google-oss-bot @rizafran @morganchen12 @mbleigh 

I was thinking, the association file creating this issue. but I have updated new Domain and there association file uploaded when I created link using this domain, then also no luck. 

same behaviour at all.

> {"applinks":{"apps":[],"details":[{"appID":"NP7DTFPFD7R.com.test.ios.app","paths":["NOT /_/*","/*"]}]}}

Now I get confused by seeing this behaviour.

Please help

**Comment by morganchen12** [comment]
Please stop @-mentioning people in your replies.

Are you able to long-press the dynamic link and open it in your already-installed app? If so, then iOS's universal link function is working as intended. Otherwise, you'll need to upload a reproducible example for us to help you debug.

Most of the team will be on vacation in the next few weeks, so replies may be delayed.

**Comment by Narendra-Pandey** [comment]
only activity I have seen when dynamic link stopped working is, the apple-app-site-association became blank like this

{"applinks":{"apps":[],"details":[]}}

this is the only case when dynamic link stop working. but I don't know the case when it get blank. 

Please let me know the case where association file get blanked and if it get blank then how to update the details.
