### ISSUE TITLE
Undefined symbols UISceneWillConnectNotification

### ISSUE THREAD

**Issue by Shebuka** [firebase/firebase-ios-sdk#4547]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.3 (10G8)
  * iOS SDK: 12.4
  * Firebase SDK version: 6.14.0
  * Firebase Component: GoogleUtilities
  * Component version: latest

#### Steps to reproduce:

Failing to build a project that I'm updating from Fabric Answers to Google Analytics.

Added all the requested frameworks and updated the code that builds perfectly, but the linker is failing with this error:
```
Undefined symbols for architecture armv7:
  "_UISceneWillConnectNotification", referenced from:
      ___47+[GULAppDelegateSwizzler proxyOriginalDelegate]_block_invoke in GoogleUtilities(GULAppDelegateSwizzler.o)
  "_OBJC_CLASS_$_UIScene", referenced from:
      objc-class-ref in GoogleUtilities(GULAppDelegateSwizzler.o)
  "___isPlatformVersionAtLeast", referenced from:
      ___47+[GULAppDelegateSwizzler proxyOriginalDelegate]_block_invoke in GoogleUtilities(GULAppDelegateSwizzler.o)
      +[GULAppDelegateSwizzler handleSceneWillConnectToNotification:] in GoogleUtilities(GULAppDelegateSwizzler.o)
      -[GULAppDelegateSwizzler scene:openURLContexts:] in GoogleUtilities(GULAppDelegateSwizzler.o)
```

I've traced that [this pull request](https://github.com/firebase/firebase-ios-sdk/pull/4380) introduced use of `UISceneWillConnectNotification` a couple of weeks ago.

#### Relevant Code:

```
        [[NSNotificationCenter defaultCenter]
            addObserver:self
               selector:@selector(handleSceneWillConnectToNotification:)
                   name:UISceneWillConnectNotification
                 object:nil];
```

**Comment by maksymmalyhin** [comment]
@Shebuka Usage of  `UISceneWillConnectNotification` is protected by [UISCENE_SUPPORTED flag](https://github.com/firebase/firebase-ios-sdk/blob/20ab31fe130e9a1d22a75b35ba7046cfba0e5a47/GoogleUtilities/AppDelegateSwizzler/Internal/GULAppDelegateSwizzler_Private.h#L22) that is set only when `_IPHONE_OS_VERSION_MAX_ALLOWED >= 130000` which should be `false` for Xcode 10.3. 

I've tried to compile [Analytics quickstart app](https://github.com/firebase/quickstart-ios/tree/master/analytics) with Xcode 10.3 an didn't get the compilation error. Could you please share a sample project to reproduce the issue (I assume it can be the quickstart project with the specific `Podfile` and `Podfile.lock`)?

**Comment by Shebuka** [comment]
I'm not using podfile, direct zip download and add to the project.

**Comment by maksymmalyhin** [comment]
@Shebuka Ah, I see. Yeah, our recent zip files are built with Xcode 11.0. Using them with Xcode 10.3 explains the issue. 

As a workaround you may use older zip file version like [6.11.0](https://github.com/firebase/firebase-ios-sdk/releases/tag/6.11.0) built with Xcode 10.1. Let us know if it works for you.

We will get back to you when we have a better solution.

**Comment by maksymmalyhin** [comment]
Another thing I would like to note is that it is expected that Apple AppStore will require Xcode 11 for application updates in several month, so we would recommend to migrate your project to Xcode 11 as a long-term solution.

**Comment by paulb777** [comment]
Yep, according to the [release note](url)s, the zip and Carthage distributions started requiring Xcode 11 in the 6.12.0 release.

**Comment by Shebuka** [comment]
I see. Thank you for such a prompt solution, I'm downloading the  6.11.0 right now.
We are currently working on a solution for our business logic code to work correctly with iOS SDK 13, but in the meantime, we are stuck with Xcode 10 and iOS SDK 12...
