### ISSUE TITLE
BuildFrameworks generates frameworks that cannot be signed

### ISSUE THREAD

**Issue by paulcbetts** [firebase/firebase-ios-sdk#455]
### Describe your environment

  * Xcode version: 9.1.0
  * Firebase SDK version: master
  * Firebase Component: n/a
  * Component version: n/a

#### Steps to reproduce:

BuildFrameworks's `build.swift` generates Framework folders that have a number of problems in practice:

* The naming convention is not usable out-of-the-box, the linker will go looking for `FirebaseCore_macOS/FirebaseCore_macOS` while the actual binary is `FirebaseCore/FirebaseCore`. This is perhaps a documentation issue, but the error that `ld` throws is very broad and Googling will lead you down many incorrect paths

* The generated Frameworks are manually put-together via `build.swift` and don't have a `Versions` folder. `clang` and `ld` don't seem to mind this, but `codesign` on Xcode 9.x seems to barf on these binaries, trying to find a `Versions/A` folder

* codesign relies on `Resources/Info.plist` to exist and be at least somewhat correctly filled out, or it doesn't know which actual file to sign

**Comment by morganchen12** [comment]
@paulb777 is this still necessary with CocoaPods 1.4.x and higher's `static_framework` rule?

**Comment by paulcbetts** [comment]
@morganchen12 Is it 100% necessary to use this with Cocoapods? I'm trying to just vendor the built frameworks (we use Carthage for our project)

**Comment by paulb777** [comment]
@paulcbetts I suspect the core problem is that you're trying to treat the Firebase static framework CocoaPods as dynamic frameworks in Carthage and you're running into something like https://github.com/Carthage/Carthage/issues/1936

Have you tried with the instructions in the "Integrate without CocoaPods" section at https://firebase.google.com/docs/ios/setup? I suspect you'd have exactly the same problem.

@morganchen12 Yes, the build.swift script is going away in the upcoming #444 that will make the open source Firebase interoperable with the released version of Firebase.

Firebase working with Carthage is being tracked at #9.

**Comment by paulcbetts** [comment]
@paulb777 This is entirely possible, I'll look into the ObjC linker flag. To be clear, I'm not using Carthage with Firebase in any way, I'm simply dropping the output of `BuildFrameworks` into a folder then attempting to point the compiler at it

**Comment by paulb777** [comment]
@paulcbetts Ah, ok. I misunderstood your comment about Carthage. You could take a look at how CocoaPods links vendored static frameworks as a reference.

**Comment by morganchen12** [comment]
Ah, yeah, understandable. @paulb777 has a PR that removes the build script, but I think we should keep it around if we're going to just rewrite it anyway for future Carthage support. 

We do vendor official binary downloads that are (of course) built in Google without any open-source scripting. Is this an issue with those binaries as well?

Out of curiosity, what are the integration steps with Carthage? From what I understand all we need is a json file associating binaries with versions and then everything should just work, despite our framework module requiring static linking.

**Comment by paulcbetts** [comment]
> We do vendor official binary downloads that are (of course) built in Google without any open-source scripting. Is this an issue with those binaries as well?

I'm trying to use the unofficial macOS support which is why I have to build my own, I'd definitely love to be out of that game and use prebuilt binaries!

**Comment by paulb777** [comment]
@paulcbetts One approach would be to make a Podfile with all of the FirebaseCommunity subspecs you need and grab the resulting intermediate FirebaseCommunity framework.

**Comment by morganchen12** [comment]
This is really indirect, though, and CocoaPods modifies the xcodeproj file which is what Carthage was basically specifically built to avoid. I think keeping a build script around for binary installations of the unofficial macOS release is reasonable.

**Comment by paulcbetts** [comment]
Closing this since build.swift is going away
