### ISSUE TITLE
FR: Firestore support for watchOS.

### ISSUE THREAD

**Issue by kajensen** [firebase/firebase-ios-sdk#4559]
Please add support for Firestore for watchOS apps/targets. Thanks!

**Comment by hohteri** [comment]
Also one would need @CocoaPodsAtGoogle to add watchOS deployment target to https://github.com/CocoaPods/Specs/blob/master/Specs/a/d/a/leveldb-library/1.22/leveldb-library.podspec.json

**Comment by hohteri** [comment]
One would also need to add 

`s.watchos.deployment_target = '6.0'`

To 

> 	FirebaseAuth.podspec
	FirebaseAuthInterop.podspec
	FirebaseDatabase.podspec
	FirebaseFirestore.podspec
	FirebaseFirestoreSwift.podspec

And add
`unit_tests.platforms = {:ios => '8.0', :osx => '10.11', :tvos => '10.0'}`
to

> FirebaseAuth.podspec

As shown in https://github.com/firebase/firebase-ios-sdk/pull/4016

I did also add watchOS target to Firestore/Example/Firestore.xcodeproj and got PLATFORM=watchos pod update to be executed by modifying Firestore/Example/Podfile but Build Phase [CP] Embed Pods Frameworks did not appear into my watchOS target but [CP] Copy Pods Resources did. I'm not a CocoaPods guy, so I don't know what's wrong. I did manually copy and modify [CP] Embed Pods Frameworks from iOS target but it fails with missing variable:

> firebase-ios-sdk/Firestore/Example/Pods/Target Support Files/Pods-Firestore_Example_watchOS/Pods-Firestore_Example_watchOS-frameworks.sh: line 43: source: unbound variable

You can see my changes at https://github.com/hohteri/firebase-ios-sdk/commit/c9b873ad6325ddcabc502c9cb4f76a8295a70eaf

**Comment by paulb777** [comment]
@hohteri Thanks for taking a look. 

 I would recommend going in the order Auth, Database, and Firestore because the dependencies get progressively harder to manage. 

The leveldb podspec is managed at https://github.com/firebase/leveldb-library-podspec

**Comment by hohteri** [comment]
With https://github.com/hohteri/firebase-ios-sdk/commit/27b11cb2ed2509417a51aee0b641a088f5b36edd I was able to sign in with email and password in an app. I haven't yet tested any other sign-in methods. Please note that my previous commit hohteri@c9b873a has podspec changes for FirebaseAuth.podspec

Doing Database doesn't make much sense as Firestore has no dependencies to it (afaik). I also got Firestore to compile but gRPC-Core fails but I also had issues with header search paths.

**Comment by hohteri** [comment]
Okay search paths were mostly fixed with a custom script using guidance from gRPC-Core podspec

>  The `src_root` value of `$(PODS_ROOT)/gRPC-Core` assumes Cocoapods is installing this pod from
>   its remote repo. For local development of this library, enabled by using `:path` in the Podfile,
>   that assumption is wrong. In such case, the following settings need to be reset with the
>   appropriate value of `src_root`. This can be accomplished in the `pre_install` hook of the
>   Podfile; see `src/objective-c/tests/Podfile` for an example.

Happy to inform you that my latest commit adds some fixes to Auth to allow Firestore to compile:
https://github.com/hohteri/firebase-ios-sdk/commit/1eebd5746099c3ecb108451814bf59494cd82b20

For firestore you need also need the podspec from the initial commit hohteri/firebase-ios-sdk@c9b873a and Firestore fixes from https://github.com/hohteri/firebase-ios-sdk/commit/808b1217b5e2cafb6e4cda5780a18859aa8e26b2

With all these in place, I'm able to sign-in with email and password and read data from Firestore with a watch simulator.

**Comment by hohteri** [comment]
A question @paulb777 (or whom it may concern): The master of grpc is at 1.27.0-dev and if my pull request https://github.com/grpc/grpc/pull/21569 gets merged, Firestore would need to upgrade from 0.09 to 1.27 eventually when creating a PR for this. Is it a problem?

**Comment by paulb777** [comment]
Firestore will upgrade the gRPC dependency sometime after the issues discovered in #4312 are addressed.

**Comment by paulb777** [comment]
After more conversation with the team back from the holidays, this feature will be more work than initially thought. Firestore relies on Reachability APIs that may not be available on watchOS. After solving that, it will be a challenge to maintain the different code paths with the limited testing infrastructure available for watchOS.

**Comment by hohteri** [comment]
Apple provides in iOS 12 and watchOS 6 Network framework which has NWPathMonitor https://developer.apple.com/documentation/network/nwpathmonitor, a most likely suitable for reachability replacement. While I believe your team is right regarding the Firebase dependence on reachability, there is a lower lever online status tracker in grpc which is based on polling DNS server if I’ve understood correctly. At least that is currently preventing to run firestore in a real device as it uses getaddrinfo which should be replaced with dnssd but ...

A bigger issue with Firestore and a real device running watchOS is that Network framework, and underlying lower-level networking APIs (like dnssd, possibly CFStream used by grpc) are only available to streaming apps (I.e. background mode music streaming) and under an audio session. See the last post in https://forums.developer.apple.com/thread/89827 and the referenced WWDC 2019 session Streaming Audio on watchOS 6 https://developer.apple.com/videos/play/wwdc2019/716/

**Comment by wilhuff** [comment]
Apple's recommendation is that to make network requests other than for audio streaming you pretty much have to use `NSURLSession`. This would be a fair amount of work and would also lose the ability to listen to documents and queries. We can't prioritize building this kind of SDK now.

If you want to get to Firestore data from watchOS, your best bet is to use our REST API directly.

We'll reconsider if a future version of watchOS lifts these restrictions.
