### ISSUE TITLE
Integrating GoogleSignIn with Firebase for Mac Catalyst

### ISSUE THREAD

**Issue by girishw** [firebase/firebase-ios-sdk#4568]
I am looking to implement GoogleSignIn with Firebase Authentication for my app on Mac Catalyst.
GoogleSignIn does not support Catalyst yet. 

As a temporary workaround,  can I use GTMAppAuth (https://github.com/google/GTMAppAuth) and integrate with the open source FirebaseAuth SDK using the signIn(withCustomToken:completion:) method? 

If not, are there any other workarounds?

**Comment by paulb777** [comment]
@morganchen12 @renkelvin Are there any alternatives to waiting for https://github.com/googlesamples/google-services/issues/420?

**Comment by girishw** [comment]
@morganchen12 @renkelvin @paulb777 Any updates on this?

**Comment by renkelvin** [comment]
I'm not familiar with GTMAppAuth, while sign in with custom token always works as long as the token is valid. But the auth provider may not be considered as Google.

**Comment by girishw** [comment]
@renkelvin Thanks. Any other works you can suggest?

**Comment by meroelyth** [comment]
I found this https://github.com/elsesiy/GAppAuth and I use the iOS version to make it works with MacCatalyst.

I have only this problem:
When I share the authorization code with my server, I get the "invalid_grant" error (400 bad request). 
I hope anyone can help me.

**Comment by girishw** [comment]
@meroelyth I am trying GAppAuth but I am unable to get the redirect working. I added the URL scheme to info.plist. However, after authentication, it switches to Safari instead of opening the app. 

How did you get redirect working in Catalyst?

**Comment by meroelyth** [comment]
> @meroelyth I am trying GAppAuth but I am unable to get the redirect working. I added the URL scheme to info.plist. However, after authentication, it switches to Safari instead of opening the app.
> 
> How did you get redirect working in Catalyst?

I get the example code for iOS and add it into my app. It works well. After sign in it launch the callback passed to "GAppAuth.shared.authorize" method. I hope it helps.

**Comment by girishw** [comment]
@meroelyth  Thanks, got client-side authentication working using GAppAuth. 

My next hurdle is cross-client authentication. Ran into the issue here: https://github.com/elsesiy/GAppAuth/issues/13

**Comment by ondrejhanak** [comment]
@girishw can you please share how did you manage to get the redirect working with `GAppAuth`? 

I am also ending in Safari, although app does receive callback with auth info. Same with `FacebookLogin` BTW.

**Comment by girishw** [comment]
@ondrejhanak No, the redirect is switching the user to Safari. However, authentication is successful. This seems to be a bug with Catalyst/MacOS : https://github.com/openid/AppAuth-iOS/issues/507

I did get cross-client authentication working by modifying GAppAuth to include "audience" in additionalParameters. This sends back the correct serverAuthCode that I use on the server side.

**Comment by jlaws** [comment]
Any updates on this?

**Comment by yuchenshi** [comment]
I've filed a feature request internally as b/160626909.

**Comment by paulb777** [comment]
See https://github.com/googlesamples/google-services/issues/420#issuecomment-661961707

**Comment by girishw** [comment]
@paulb777 @petea Any updates?

**Comment by girishw** [comment]
@meroelyth Did you ever solve the invalid_grant/Bad Request error?

**Comment by paulb777** [comment]
GoogleSignIn 6.0.0 is now released and open source.  Catalyst has not been validated, but it might just work. Please try with 6.0.0 and follow up at https://github.com/google/GoogleSignIn-iOS/issues with any outstanding issues.
