### ISSUE TITLE
Getting error when uploading files to firebase storage 

### ISSUE THREAD

**Issue by md-rubel** [firebase/firebase-ios-sdk#4569]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.3
  * Firebase SDK version: 6.14.0
  * Firebase Component: (Auth, Core, Database, Firestore, Messaging, Storage, RemoteConfig)
  * Component version: latest

### [REQUIRED] Step 3: Describe the problem

I found issues when uploading Data (actually image of some kilobytes) to firebase storage.  
Here is the snippet of my code:

```swift
func uploadImage(newImage : Data) {
        guard let uid = defaults.string(forKey: "receivedUID") else{return}
        // Create a reference to the file you want to upload
        let imageRef = storage.child("\(uid).png")
        
        let uploadTask = imageRef.putData(newImage, metadata: nil) { (metadata, error) in
            
            imageRef.downloadURL { (url, error) in
                guard let downloadURL = url else {
                    // Uh-oh, an error occurred!
                    return
                }
                print("IMG URL: \(downloadURL)")
                self.imageUrl = "\(downloadURL)"
                
            }
        }
        // Listen for state changes, errors, and completion of the upload.
        
        uploadTask.observe(.progress) { snapshot in
            self.progressView.isHidden = false
            // Upload reported progress
            let percentComplete = 100.0 * Double(snapshot.progress!.completedUnitCount)
                / Double(snapshot.progress!.totalUnitCount)
            DispatchQueue.main.async {
                self.progressView.setProgress(Float(percentComplete), animated: true)
            }
        }
        uploadTask.observe(.success) { snapshot in
            
            // Upload completed successfully . 
            // This block is not triggering 

        }
        
        uploadTask.observe(.failure) { snapshot in
            if let error = snapshot.error as NSError? {
                DispatchQueue.main.async {
                    self.progressView.isHidden = true
                    print(error)
                    self.customAlert(title: "Upload Failed", message: "Check your internet connection", time: 3)
                }
                
                switch (StorageErrorCode(rawValue: error.code)!) {
                case .objectNotFound:
                    print("File doesn't exist")
                    break
                case .unauthorized:
                    print("User doesn't have permission to access file")
                    break
                case .cancelled:
                    print("User canceled the upload")
                    break
                    
                    /* ... */
                    
                case .unknown:
                    print("Unknown error occurred, inspect the server response")
                    // This block is triggering 
                    break
                default:
                    print("A separate error occurred. This is a good place to retry the upload.")
                    break
                }
            }
        }
    }
```

Here is the error i got from console:

`2019-12-31 14:42:23.116694+0600 APP_NAME[3697:143683] Connection 5: received failure notification
2019-12-31 14:42:23.117159+0600 APP_NAME[3697:143683] Connection 5: failed to connect 3:-9816, reason -1
2019-12-31 14:42:23.117821+0600 APP_NAME[3697:143683] Connection 5: encountered error(3:-9816)
2019-12-31 14:42:23.127520+0600 APP_NAME[3697:143683] Task <CC61FA70-DFD9-4368-A9FD-75E1FC4E6C1C>.<1> HTTP load failed, 0/0 bytes (error code: -1200 [3:-9816])
2019-12-31 14:42:23.133936+0600 APP_NAME[3697:143581] Task <CC61FA70-DFD9-4368-A9FD-75E1FC4E6C1C>.<1> finished with error [-1200] Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSErrorFailingURLStringKey=https://firebasestorage.googleapis.com/v0/b/my_project_id.appspot.com/o/user_profiles%2Ffile_name.png?uploadType=resumable&name=user_profiles%2Ffile_name.png, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <CC61FA70-DFD9-4368-A9FD-75E1FC4E6C1C>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <CC61FA70-DFD9-4368-A9FD-75E1FC4E6C1C>.<1>"
), NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://firebasestorage.googleapis.com/v0/b/my_project_id.appspot.com/o/user_profiles%2Ffile_name.png?uploadType=resumable&name=user_profiles%2Ffile_name.png, NSUnderlyingError=0x600001d26040 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9816, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9816}}, _kCFStreamErrorCodeKey=-9816}
Unknown error occurred, inspect the server response`

**Comment by md-rubel** [comment]
Hello Paul, 
Could you please figure out this issue? 
@paulb777

**Comment by rizafran** [comment]
Hi @md-rubel, thanks for the report. Could you provide the following info:
1. Does the issue occur in all iOS versions?
2. Is this happening all the time? If so, what location are you in?
3. Do you have any restrictions in your network?
4. Have you tried to connect to other network?

I tried to reproduce this on my end, but I successfully uploaded a file in my storage.

**Comment by md-rubel** [comment]
> Hi @md-rubel, thanks for the report. Could you provide the following info:
> 
> 1. Does the issue occur in all iOS versions?
> 2. Is this happening all the time? If so, what location are you in?
> 3. Do you have any restrictions in your network?
> 4. Have you tried to connect to other network?
> 
> I tried to reproduce this on my end, but I successfully uploaded a file in my storage.



Hello,
1. I tried in both iOS 12 and 13, but faced the same problem.
2. It is happening for last 5/6 days, i'm from bangladesh, but my storage bucket is us-central-1
3. I have checked, there is no restrictions
4. I have tried from different networks.

**Comment by rizafran** [comment]
Thanks for the information, @md-rubel. I've seen similar reports about issues in accessing Cloud Storage for Firebase at the moment. I got an update from our engineering team, and we believe that this might be caused by networking conditions in Bangladesh, rather than Google's infrastructure. Unfortunately, we can't do much with this kind of problem, and we can't help you with a workaround  as this is out of our control.
