### ISSUE TITLE
FIRFunctions.m not handing error code properly

### ISSUE THREAD

**Issue by coolcool1994** [firebase/firebase-ios-sdk#4570]
In my Firebase Cloud Function in Node.js, I do
```response.status(501).send('error message')```

And the error message here cannot be retrieved from iOS SDK, because before it gets to [NSJSONSerialization JSONObjectWithData:data options:0 error:&error] that prints out "error message" above, it gets to this instead: error = FUNErrorForResponse(error.code, data, serializer).

FUNErrorForResponse returns useless data such as "UNIMPLEMENTED" or "INTERNAL" (it is showing unimplemented when you send back above example!). I really think you guys meant to return [NSJSONSerialization JSONObjectWithData:data options:0 error:&error] first and then return FUNErrorForResponse second, not the other way around the way it is implemented now. Look at FIRFunctions.m function callFunction:withObject:timeout:context:completion where the error is handled FUNSerializer... beginFetchWithCompletionHandler. There is no reason why the iOS SDK should return this useless error message "UNIMPLEMENTED" or "INTERNAL" than the custom error message sent back from the server. Right now in the project level, there is no way to see the error message sent from the Cloud Functions server because of this flaw. I hope you guys change this because I am editing the pod file (the only thing I am editing) in the meanwhile which is a very unpleasant thing to do.

**Comment by coolcool1994** [comment]
Actually my workaround doesn't fix it. But the problem here you can't see server sent error message. If you could would fix.

**Comment by morganchen12** [comment]
Looks like we're not correctly deserializing the response in [this method](https://github.com/firebase/firebase-ios-sdk/blob/master/Functions/FirebaseFunctions/FUNError.m#L144).

**Comment by bklimt** [comment]
Hi @coolcool1994. `FUNErrorForResponse` is not a public API, but an internal method that is subject to change, so I wouldn't recommend relying on it.

It sounds like you wrote an HTTPS trigger (`functions.https.onRequest`), but are calling it from the SDK as though it's an "HTTPS callable" (`functions.https.onCall`). The easiest fix would be to change the function to be a callable: https://firebase.google.com/docs/functions/callable

But if you really want to keep it as an http request, we did publish the http specification for callable functions, so if you put the response in the proper format, it should work with the SDK: https://firebase.google.com/docs/functions/callable-reference

**Comment by paulb777** [comment]
Going to close based on the above suggestion. Feel free to continue the conversation here with additional related questions.

**Comment by coolcool1994** [comment]
So you guys are saying that Firebase iOS SDK does not support HTTPS triggers, because there is no way to log the error code or error message from Cloud function.

So I am implementing other functions as callable functions and realized that you need to throw an error from Cloud function in order for the client to receive that error. All my cloud functions are async and have try and catch wrapped. So when I throw to send error to the client, instead async catch will catch it and I am unable to pass in the error code to the client.

Please enlighten me, because sending back error from Cloud function to at least iOS SDK seems to be bugged. 

Meanwhile whenever there is an error in callable function, I could instead return success response every time due to this limitation and have errorDescription key in the response object. This is inconvenient but doable.

**Comment by bklimt** [comment]
Hi @coolcool1994 

Throwing an `HttpsError` from a callable function _should_ work. If it's not, I'd have to take a look at the function itself to make a guess why it might be broken. One way to check it would be to call the endpoint from a tool such as `curl` and verify that the response has the expected format.

If you want to return a specific error code and message from an https trigger created with `functions.https.onRequest`, you need to do the following:

1. Return a non-200 http status.
2. Include a header setting the content type as `Content-Type: application/json; charset=utf-8`.
3. Format the body of the response like this:

```
{
    "error": {
        "message": "This is your custom message.",
        "status": "INVALID_ARGUMENT",
        "details": {
            "some-key": "some-value"
        }
    }
}
```

This format is documented here: https://firebase.google.com/docs/functions/callable-reference

When you throw an `HttpsError` from a callable function, it should be generating that same format of response. If your function isn't returning something like that, then the problem is with the function. If it _is_ returning something like that, and the iOS SDK isn't handling it correctly, then that would be an SDK bug.

**Comment by coolcool1994** [comment]
Hi, I am not able to get the error object (error object is nil) when I make the callable function a async and do this:
try {
     throw new functions.https.HttpsError('invalid-argument', 'The error)
}
catch {
}

The error object in iOS Firebase SDK is nil. When I throw outside of the try and catch block, error is not nil and works as expected. But how do I keep and async and try and catch block AND somehow throw the error so the client receives the error object? Thanks I’m advance.

**Comment by bklimt** [comment]
It's hard to help without seeing more of the function, but in general, you aren't going to be able to send back an error that you already caught in your function. You either need to rethrow the error from the catch block or leave the catch block off entirely.
