### ISSUE TITLE
Deprecated calls to archiveRootObject:toFile: in GDTCORStorage

### ISSUE THREAD

**Issue by nickplennox** [firebase/firebase-ios-sdk#4572]
* Xcode version: 11.3
  * Firebase SDK version: 6.14.0
  * Firebase Component: Firebase/Messaging
  * Component version: 4.1.10

### Describe the problem:
Updated pods on a working project and the updated project does not compile because of four calls to archiveRootObject:toFile: in GDTCStorage. The archiveRootObject:toFile: method is now deprecated, preventing compilation

#### Steps to reproduce:

1. Run `pod update` command on existing project

Output:

```
Update all pods
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing Firebase 6.14.0 (was 6.13.0)
Installing FirebaseCore 6.5.0 (was 6.4.0 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
Installing FirebaseInstanceID 4.2.8 (was 4.2.7 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
Installing FirebaseMessaging 4.1.10 (was 4.1.9 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
Installing GoogleDataTransportCCTSupport 1.2.3 (was 1.2.2 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
Installing GoogleUtilities 6.4.0 (was 6.3.2)
Installing Protobuf 3.11.2 (was 3.11.1 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
Generating Pods project
Integrating client project
Pod installation complete! There are 2 dependencies from the Podfile and 13 total pods installed.
```

2. In Xcode, Clean the project, then Build the project.

**Expected**: The project builds and runs.

**Actual:** In Xcode Issues navigator, the calls to archiveRootObject:toFile: at lines 129, 225, 249 & 268 are marked `'unarchiveObjectWithFile:' is deprecated: first deprecated in iOS 12.0 - Use +unarchivedObjectOfClass:fromData:error: instead`

I will try reverting to an older version to allow progress on my project, but as I followed the instructions on the Firebase page and am not doing anything custom at all, it could be that there are many more users about to be impacted when they do an update?

**Comment by paulb777** [comment]
Looks like https://stackoverflow.com/questions/59132330/cannot-compile-ios-app-with-firebase-because-of-deprecated-nskeyedarchiver-archi

We may need a reproducible example to make progress since this doesn't reproduce with Xcode 10 or 11 in our examples.

**Comment by mikehaney24** [comment]
This code will also soon be removed in favor of a sqlite storage mechanism.

**Comment by jstheoriginal** [comment]
I had this issue and resolved it by removing this from my Podfile:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
```

**Comment by nickplennox** [comment]
As @mikehaney24 has stated that this is being removed, I guess I will close this issue.
