### ISSUE TITLE
Terminating app due to uncaught exception 'FABException', reason: '[Fabric] Value of Info.plist key "Fabric" must be a NSDictionary.'

### ISSUE THREAD

**Issue by MelanyG** [firebase/firebase-ios-sdk#4578]
I want to migrate existing project that uses Crashlytics with Fabric to Firebase (as it is going not be supported soon). After searching and following instructions I thought I managed to configure it, but it crashes when  I try to configure Firebase.
```
 [FIRApp configure];
 [Fabric with:@[[Crashlytics class]]];
```

My pod file looks like this:
```
use_frameworks!

platform :ios, '10.0'

workspace 'Fifi24'

project 'xoxo/xoxo.xcodeproj'
project 'fifi/fifi.xcodeproj'


def common_pods
    
    pod 'GoogleAnalytics'
    pod 'Google-Mobile-Ads-SDK'
    pod 'GoogleAds-IMA-iOS-SDK-For-AdMob', '~> 3.2.1'
    pod 'GoogleIDFASupport'
    pod 'Fabric', '~> 1.10.2'
    pod 'Crashlytics', '~> 3.14.0'
   
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Firebase/AppIndexing'
    pod 'Firebase/Analytics'

end

target :xoxoPresentation do
    
    pod 'Google-Mobile-Ads-SDK'
    pod 'GoogleAds-IMA-iOS-SDK-For-AdMob', '~> 3.2.1'
    pod 'GoogleIDFASupport'
    pod 'Crashlytics', '~> 3.14.0'
    pod 'Fabric', '~> 1.10.2'
    pod 'Firebase/Core'

    project 'xoxo/xoxo.xcodeproj'
end

target :xoxoCommon do
    pod 'GoogleAnalytics'
    pod 'Fabric', '~> 1.10.2'
    pod 'Crashlytics', '~> 3.14.0'
    pod 'Firebase/Analytics'

    project 'xoxo/xoxo.xcodeproj'
end

target :xoxoDomain do

    pod 'Crashlytics', '~> 3.14.0'

    project 'xoxo/xoxo.xcodeproj'
end

target :xoxoPersistence do

    pod 'Fabric', '~> 1.10.2'
    pod 'Crashlytics', '~> 3.14.0'
    project 'xoxo/xoxo.xcodeproj'
end


target :fifi do
    common_pods
    
    pod 'GoogleSignIn'
    pod 'TwitterKit'

    project 'fifi/fifi.xcodeproj'
end

target :fifiDev do
    common_pods
    
    pod 'GoogleSignIn'
    pod 'TwitterKit'
    
    project 'fifi/fifi.xcodeproj'
end
```
I added GoogleService-Info.plist to the project

What i did:
I had in Info.plist as it was needed previously 
```
	<key>Fabric</key>
	<dict>
		<key>APIKey</key>
		<string>**key generated**</string>
		<key>Kits</key>
		<array>
			<dict>
				<key>KitInfo</key>
				<dict/>
				<key>KitName</key>
				<string>Crashlytics</string>
			</dict>
		</array>
	</dict>
```
Now:
I removed it

then in Build Phases Run script
"${PODS_ROOT}/Fabric/run" <Fabric API Key> <Build secret>

I left "${PODS_ROOT}/Fabric/run", removed both keys

in Input files section, I added : $(BUILT_PRODUCTS_DIR)/GoogleService-Info.plist (I use Xcode 11.3)

So when I try to run the project it builds successfully but crashes at  [FIRApp configure];
 this step.
I suppose I am missing smth
<img width="990" alt="Screen Shot 2020-01-01 at 23 13 06" src="https://user-images.githubusercontent.com/16033996/71646174-4df49500-2cec-11ea-85f5-56e81cd0547f.png">
and I am still on this step inside Firebase console
Please help or give an advice whats wrong 
Thanks in advance

**Comment by MelanyG** [comment]
Thank you very much for clear explanation, we decided not to migrate but start from stretch with Crashlitics and Firebase

**Comment by rizafran** [comment]
Hi. I'm going to close this issue since there's no action needed from us. If you're still experiencing this issue and want to continue the discussion, feel free to leave a comment here and we're happy to re-open this. Thanks.
