### ISSUE TITLE
Log spam 6.14.0 - [Firebase/Performance][I-PRF200004] Trace feature is disabled.

### ISSUE THREAD

**Issue by beschrich-is4it** [firebase/firebase-ios-sdk#4585]
Hello Devs,
for my own testing I disable Firebase performance and I got log spam with FirebaseLoggerLevel.error. Even if I set to FirebaseLoggerLevel.min, I got a lot of uninteresting log entries but the spam stops. I think one log entry is enough :)

6.14.0 - [Firebase/Performance][I-PRF200004] Trace feature is disabled.

Best Regards

        // prevent console log spam by Google frameworks
        FirebaseConfiguration.shared.setLoggerLevel(FirebaseLoggerLevel.error)

        // No database debug logging
        Database.setLoggingEnabled(false)

        // configure Google Firebase App framework
        FirebaseApp.configure()

        // Enable/Disable data collection
        FirebaseApp.app()?.isDataCollectionDefaultEnabled = false

        // Disable Firebase performance analysis
        Performance.sharedInstance().isInstrumentationEnabled = false
        Performance.sharedInstance().isDataCollectionEnabled = false

**Comment by paulb777** [comment]
@beschrich-is4it Please show an example of the logs you're seeing.
