### ISSUE TITLE
FR: Add FIRStorage Interop

### ISSUE THREAD

**Issue by leisurehound** [firebase/firebase-ios-sdk#4599]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.3
  * Firebase SDK version: 6.14.0
  * Firebase Component: Storage
  * Component version: 3.4.3

### [REQUIRED] Step 3: Describe the problem

In attempting to build a SwiftLog implementation that posts client logs to Firebase Cloud Storage buckets as a Firebase Extended library, the SwiftLog impl will depend on Firebase Cloud Storage, however it should only depend on the storage object configured by Client App and not create its own object.  As suggested by Ryan Wilson, adding a FIRStorageInterop is the right solution to manage the dependency cleanly.

#### Steps to reproduce:
n/a

#### Relevant Code:
n/a see forthcoming PR

**Comment by paulb777** [comment]
@leisurehound Is this still needed/planned?

**Comment by leisurehound** [comment]
So, I've implemented around the need for this, tho this pushes more cognitive load on the client to use the solution.  I'm about to release the library on GitHub next week, so can we look at adoption and/or pushback on whether a more seamless solution to the client developer is warranted?

**Comment by paulb777** [comment]
So you mean leave this open pending feedback on next week's release?

**Comment by leisurehound** [comment]
yes, if that is possible.

**Comment by paulb777** [comment]
SG - let me or @ryanwilson know if you'd like to come back to this. There have been some Interop structural changes since this PR was created.

**Comment by leisurehound** [comment]
hmm...maybe it would be better then to just start a new PR if the need warrants it.

**Comment by paulb777** [comment]
Perhaps. Maybe close #4600 and leave this feature request open?

**Comment by leisurehound** [comment]
ah, yes, we can close that PR.  Will do so now.

**Comment by paulb777** [comment]
Closing for staleness. Can reopen if the need re-arises.
