### ISSUE TITLE
Silent push notification not received in iOS 13

### ISSUE THREAD

**Issue by Riedi2070** [firebase/firebase-ios-sdk#4605]
Hi anyone, I've a problem to received silent push notification since iOS 13. I send the silent push notification at the bottom from backend to iOS clients.

Environment:
- iPhone 8+ with iOS 13.3
- Xcode 11.3 (11C29)
- Firebase/Core (6.14.0)
- Firebase/Messaging (6.14.0)
- Capabilities Background fetch enabled
- Capabilities Remote notification enabled
- Capabilities Background processing enabled

In iOS 12 the notifications always received, even when app is in background or after a device restart.
In iOS 13 the message only received when app is in foreground. Sometime also when app is in background, but only in 1 of 10 notifications. The big problem is that I get a response where delivery confirmed which a successful flag.

The remote push notification (see below) is always received, also when app is closed or in background.
Sometime when I sent a silent notification and 2 minutes later a remote notification. Both notifications (silent and the remote) are received, but also only sometimes.

Does someone else confirm this behaviour?

Silent push notification not received:
```
[POST] https://fcm.googleapis.com/fcm/send
{
    "to" : "dH3bUzO....",
    "content_available":true,
    "mutable_content":true,
    "priority":"high",
    "data": {
        "id":"68f75319-c736-4b4c-df3f-08d792b6d1b0"
    }
}
```
Response:
```
{
    "multicast_id": 8461388093675580396,
    "success": 1,
    "failure": 0,
    "canonical_ids": 0,
    "results": [
        {
            "message_id": "1578378985314824"
        }
    ]
}
```

Remote push notification works fine:
```
[POST] https://fcm.googleapis.com/fcm/send
{
	"to" : "dH3bUzO....",
	"notification" : {
		"body" : "This is an FCM notification message!",
		"title" : "FCM Message"
	}
}
```

**Comment by morganchen12** [comment]
This may be related to the changed requirements for priority for silent notifications in iOS 13 (see [this WWDC session](https://developer.apple.com/videos/play/wwdc2019/707/?time=799)).

Can you try adding an explicit priority and apns type to your notification?

```
"apns":{
  "headers":{
    "apns-priority":"5",
    "apns-push-type":"background"
  }
},
```

**Comment by Riedi2070** [comment]
@morganchen12 Thank you for the WWDC link. Yes of cause, I can try. But what happens with the "priority":"high" attribute outside apns? Will it override the apns-priority?

Or should I send without outter priority like the following request?

```
[POST] https://fcm.googleapis.com/fcm/send
{
    "to" : "dH3bUzO....",
	"content_available":true,
	"data": {
		"id":"68f75319-c736-4b4c-df3f-08d792b6d1b0"
	},
	"apns":{
		"headers":{
			"apns-priority":"5",
			"apns-push-type":"background"
		}
	}
}
```

**Comment by Riedi2070** [comment]
Now at first I've changed to new HTTP v1 API such [issue 3985](https://github.com/firebase/firebase-ios-sdk/issues/3985). But it is the same behaviour with the following request:

```
[POST] https://fcm.googleapis.com/v1/projects/..../messages:send
{
   "message":{
      "token":"dH3bUzO....",
      "data":{
         "id":"68f75319-c736-4b4c-df3f-08d792b6d1b0"
      }
   }
}
```

Response:
```
{
  "name": "projects/...../messages/1578399575241757"
}
```

When I try to set the apns attributes, I get an 400 with bad request, but the token is the same.

```
[POST] https://fcm.googleapis.com/v1/projects/..../messages:send
{
   "message":{
      "token":"dH3bUzO....",
      "data":{
         "id":"68f75319-c736-4b4c-df3f-08d792b6d1b0"
      }
   }
}
```

Response:
```
{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.firebase.fcm.v1.FcmError",
        "errorCode": "INVALID_ARGUMENT"
      },
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "field": "message.token",
            "description": "Invalid registration token"
          }
        ]
      }
    ]
  }
}
```

**Comment by morganchen12** [comment]
Having `"priority":"high"` outside of the APNS header should not override the apns-priority field. Check your registration token on the client; it may have been invalidated. You can also delete the InstanceID on the client and force a new token refresh, and then try to send to the new token.

**Comment by Riedi2070** [comment]
I explicit create a new token at client side, but always the same issue. When adding the specific apns attribute to the request, the response is a 400 with Invalid registration token. When drop the specific apns attribute, I get 200 without errors - both of them send to the same token.

Next function is calling when the app starts.
```swift
func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String)
```

Next function is also calling when the app starts.
```swift
func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        logDebugMessage(message: "Token received: \(deviceToken)")
        Messaging.messaging().apnsToken = deviceToken
}
``` 

**First request with APNs attribute: FAILED with 400 Bad Request**
[POST] https://fcm.googleapis.com/v1/projects/..../messages:send
```json
{
   "message":{
      "token":"fEMqvr5zBR4:APA91bErotVEaj2-35TTkmXJ9HjM_MvDAa9BJsQA5Hl6DadD33myaGUvj_nVJ_m0Lw43_V6DA5rru8NPfHiR5a8L6IkHaptfIgsTFdoT_5v6fub_1yVL-_gcgI6utH6C2BLx3S7Ln1Rd",
      "data":{
         "id":"bfc99b04-5e71-435f-323f-08d7847a16d1"
      },
      "apns":{
         "headers":{
            "apns-priority":"5",
            "apns-push-type":"background"
         }
      }
   }
}
```

RESPONSE:
```json
{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.firebase.fcm.v1.FcmError",
        "errorCode": "INVALID_ARGUMENT"
      },
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "field": "message.token",
            "description": "Invalid registration token"
          }
        ]
      }
    ]
  }
}
```

**Second request without APNs attribute: OK with 200**
[POST] https://fcm.googleapis.com/v1/projects/..../messages:send
```json
{
   "message":{
      "token":"fEMqvr5zBR4:APA91bErotVEaj2-35TTkmXJ9HjM_MvDAa9BJsQA5Hl6DadD33myaGUvj_nVJ_m0Lw43_V6DA5rru8NPfHiR5a8L6IkHaptfIgsTFdoT_5v6fub_1yVL-_gcgI6utH6C2BLx3S7Ln1Rd",
      "data":{
         "id":"bfc99b04-5e71-435f-323f-08d7847a16d1"
      }
   }
}
```

RESPONSE 200 OK:
```json
{
  "name": "projects/.../messages/1578652278080434"
}
```

Does anyone see a mistake?

**Comment by Riedi2070** [comment]
I explicit create a new token at client side, but always the same issue. When adding the specific apns attribute to the request, the response is a 400 with Invalid registration token. When drop the specific apns attribute, I get 200 without errors - both of them send to the same token.

Next function is calling when the app starts.
```swift
func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String)
```

Next function is also calling when the app starts.
```swift
func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        logDebugMessage(message: "Token received: \(deviceToken)")
        Messaging.messaging().apnsToken = deviceToken
}
``` 

**First request with APNs attribute: FAILED with 400 Bad Request**
[POST] https://fcm.googleapis.com/v1/projects/..../messages:send
```json
{
   "message":{
      "token":"fEMqvr5zBR4:APA91bErotVEaj2-35TTkmXJ9HjM_MvDAa9BJsQA5Hl6DadD33myaGUvj_nVJ_m0Lw43_V6DA5rru8NPfHiR5a8L6IkHaptfIgsTFdoT_5v6fub_1yVL-_gcgI6utH6C2BLx3S7Ln1Rd",
      "data":{
         "id":"bfc99b04-5e71-435f-323f-08d7847a16d1"
      },
      "apns":{
         "headers":{
            "apns-priority":"5",
            "apns-push-type":"background"
         }
      }
   }
}
```

RESPONSE:
```json
{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.firebase.fcm.v1.FcmError",
        "errorCode": "INVALID_ARGUMENT"
      },
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "field": "message.token",
            "description": "Invalid registration token"
          }
        ]
      }
    ]
  }
}
```

**Second request without APNs attribute: OK with 200**
[POST] https://fcm.googleapis.com/v1/projects/..../messages:send
```json
{
   "message":{
      "token":"fEMqvr5zBR4:APA91bErotVEaj2-35TTkmXJ9HjM_MvDAa9BJsQA5Hl6DadD33myaGUvj_nVJ_m0Lw43_V6DA5rru8NPfHiR5a8L6IkHaptfIgsTFdoT_5v6fub_1yVL-_gcgI6utH6C2BLx3S7Ln1Rd",
      "data":{
         "id":"bfc99b04-5e71-435f-323f-08d7847a16d1"
      }
   }
}
```

RESPONSE 200 OK:
```json
{
  "name": "projects/.../messages/1578652278080434"
}
```

Does anyone see a mistake?

**Comment by Riedi2070** [comment]
After some hours with Google, I've now the right syntax for the request:

```json
{
   "message":{
      "token":"fEMqvr5zBR4:APA91bErotVEaj2-35TTkmXJ9HjM_MvDAa9BJsQA5Hl6DadD33myaGUvj_nVJ_m0Lw43_V6DA5rru8NPfHiR5a8L6IkHaptfIgsTFdoT_5v6fub_1yVL-_gcgI6utH6C2BLx3S7Ln1Rd",
      "data":{
         "id":"68f75319-c736-4b4c-df3f-08d792b6d1b0"
      },
      "apns":{
         "headers":{
            "apns-priority":"5",
            "apns-push-type":"background"
         },
         "payload":{
            "aps":{
               "content-available":1
            }
         }
      }
   }
}
```
-> RESPONSE 200 OK

**Back to begin**
Now I am back to my first problem, that 8 of 10 messages are not receiving, when the app is in the background. Even not when I set `"apns-priority": "5"` and `"apns-push-type":"background"` 

Did someone have any idea, what can I do, to increase the success rate?

**Comment by morganchen12** [comment]
If some but not all of the background messages are being received, but all of the foreground messages are being received, it's most likely a result of iOS throttling your app's background wakeups to conserve power. Apple's docs are very nebulous on this behavior but you can possibly reduce the throttling by reducing the amount of work done in your background execution and ending background execution as quickly as possible.

**Comment by morganchen12** [comment]
Closing this bug since it seems to be not actionable on the Firebase side. If you have any other questions, feel free to continue commenting and I'll try to answer them in this thread.

**Comment by devSC** [comment]
I have the same issue in iOS 13 devices, how to solve it?

**Comment by chliangGoogle** [comment]
@devSC Please share with us how you sent the message with payload and error message.
