### ISSUE TITLE
I CAN'T INSTALL FIREBASE/MLNLTRANSLATE, PLEASE HELP ME?

### ISSUE THREAD

**Issue by vanhiep184** [firebase/firebase-ios-sdk#4606]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: _____
  * Firebase SDK version: _____
  * Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by rizafran** [comment]
Hi @vanhiep184, thanks for reporting, however, we won't be able to identify the cause of the issue without enough information. Could you please complete the given template including the SDK versions used, detailed steps to reproduce the issue, a minimal repro of your code and complete error logs.

**Comment by vanhiep184** [comment]
I'm using Cocoapods 1.9.0.beta.2
when I add `pod 'Firebase/MLNLTranslate'` in my podfile
then `pod install`, I got this error
-------This my error--------
[!] CocoaPods could not find compatible versions for pod "Firebase/MLNLTranslate":
  In Podfile:
    Firebase/MLNLTranslate

None of your spec sources contain a spec satisfying the dependency: `Firebase/MLNLTranslate`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

----------------------

**Comment by rizafran** [comment]
Hi @vanhiep184, thanks for sharing. I can't seem to replicate the same output. Have you tried to update with `pod repo update` as stated in your error message?

**Comment by ryanwilson** [comment]
Hi @vanhiep184 - one more thing that would help us debug this: can you please share your entire Podfile? It could be the case that a different Firebase pod is locked to an older version and there's no overlap with the `MLNLTranslate` subspec.

**Comment by morganchen12** [comment]
Also, make sure you have up-to-date pod sources by running `pod repo update`.
