### ISSUE TITLE
Sign In with Apple can't link to Anonymous user, Help!

### ISSUE THREAD

**Issue by fangyuxi** [firebase/firebase-ios-sdk#4620]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.3
  * Firebase SDK version: 6.14.0
  * Firebase Component: Auth
  * Component version: AppAuth (1.3.0) FirebaseAuth (~> 6.4.1) FirebaseUI/Auth (= 8.4.0)

### [REQUIRED] Step 3: Describe the problem

Sign In with Apple can't link to Anonymous user.

#### Steps to reproduce:

<img width="1224" alt="10" src="https://user-images.githubusercontent.com/1756038/71946095-cc2ccc00-3203-11ea-87a4-9460b7d85a21.png">

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by fangyuxi** [comment]
I am using a temporary solution now, if an anonymous user is using Apple login, then hide Apple login Button.

**Comment by morganchen12** [comment]
Looks like the same issue as #4434, though this is using FirebaseUI. We should definitely fix the flow in FirebaseUI so it works automatically, but in the meantime you should be able to link users manually using the flow described [here](https://github.com/firebase/firebase-ios-sdk/issues/4434#issuecomment-564776016).

**Comment by fangyuxi** [comment]
I think this may be a cause of the problem, but I am using FirebaseUI. When an anonymous user is upgraded to a user logged in by Apple, _currentUser is nil, which causes autoUpgrade to not be called normally.
