### ISSUE TITLE
Programmatic FirebaseApp initialisation — Analytics works but logs "Could not locate configuration file: 'GoogleService-Info.plist'"

### ISSUE THREAD

**Issue by ruisilvestre** [firebase/firebase-ios-sdk#4635]
Hi,

### Environment
* Xcode version: 11.2.1 (11B500)
* Firebase SDK version: 6.13.0
* Firebase Component: Analytics
* Component version: v.60106000 

Running on simulator.

### Describe the problem
I'm initialising Firebase programatically using custom FirebaseOptions, which seems to be working since I can see the analytics events appearing on the Firebase Console DebugView, but the Core component logs that the plist cannot be found and the Analytics components logs that a Google App ID is "required" even though this is being passed in with the FirebaseOptions — if Google App ID is incorrect FirebaseApp.configure(options: options) would fail.

The problem is I don't know what log messages to trust, are these incorrectly logged messages? Things seem to be working as expected otherwise.

I do not have any GoogleService-Info.plist in the project.

### Steps to reproduce
1 - Initialise the FirebaseApp using the static method *configure(options:)*
2 - Check the logs on the Xcode console for Firebase/Core and Firebase/Analytics messages immediately after the initialiser is called

*Console output:*
```
[Firebase/Core][I-COR000001] Configuring the default app.
[Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.
[Firebase/Analytics][I-ACS024000] Debug mode is on
[Firebase/Analytics][I-ACS020006] Google App ID from GoogleService-Info.plist is empty. Please, define GOOGLE_APP_ID in GoogleService-Info.plist for Analytics to work reliably. See https://goo.gl/txkZbE
...
[Firebase/Analytics][I-ACS025020] Analytics requires Google App ID from GoogleService-Info.plist. Your data may be lost. Google App ID has been changed. Original, new ID: (nil), <the google app id specified programatically appears here>
[Firebase/Analytics][I-ACS023007] Analytics v.60106000 started
...
[Firebase/Analytics][I-ACS029014] Successfully parsed a configuration. Version: 1576101031902724
...
[Firebase/Analytics][I-ACS023016] Analytics is ready to receive events
```

### Relevant code
*Initialise Firebase first thing on app delegate*
```
let firebaseConfig = config.firebaseSDK
let options = FirebaseOptions(googleAppID: firebaseConfig.googleAppId,
                              gcmSenderID: firebaseConfig.gcmSenderId)
options.clientID = firebaseConfig.clientId
options.apiKey = firebaseConfig.apiKey
options.bundleID = firebaseConfig.bundleId
options.projectID = firebaseConfig.projectId
options.storageBucket = firebaseConfig.storageBucket
options.databaseURL = firebaseConfig.databaseUrl

FirebaseApp.configure(options: options)
```
Just to clarify that the options properties are correctly being set with the given values or else nothing would work.

Is this expected? I was initially interpreting this as "all the analytics will fail to work", but the events seem to be going out ok, so I'm a bit confused. Are these just incorrectly logged messages from the SDK?

Thanks

**Comment by morganchen12** [comment]
If you initialize FirebaseAnalytics without the GoogleService-Info.plist, you may miss out on some very early lifecycle events. @allenktv can probably explain in more detail.

**Comment by ruisilvestre** [comment]
It would be great to understand the flow of that since it's not clear from the docs what we are missing when using a programmatic approach.

From what you say it seems the SDK, when a config plist is present, starts doing things before configure() is called, which is acceptable, but in terms of iOS lifecycle events, the fact that we call configure right at the start of application:didFinishLaunching should also imply we're initialising a the earliest possible moment, so no subsequent lifecycle events would be lost, but it seems there's more to it.

**Comment by allenktv** [comment]
Hi @ruisilvestre,

We require the use of the GoogleService-info.plist currently for Analytics since we read the data from there in different parts of our code. That being said, if the events are logging correctly for you and you can see them in debug mode, it may be fine for a limited use case. However we do not have guarantees that all of our features will work properly without the file.

**Comment by ruisilvestre** [comment]
Thanks @allenktv,
There's no point in pursuing this programmatic approach if there's no guarantee it works / will work for all of Firebase SDK and underlying components, specially with Analytics, which is the most 'traditional' use for for it; is this something that the team has on the roadmap to eventually work as expected?
The fact that the configuration methods are there to use makes it feel it's supported, and there's nothing documented otherwise, it's just not clear what underlying components don't actually respect that. If there are any docs / info available where this is explained in more detail just point the way.

**Comment by allenktv** [comment]
@ruisilvestre You have a good point about that, I will be sure to forward having clearer documentation about this to the proper channels. Thanks!

**Comment by ryanwilson** [comment]
Note: This is also being tracked in #230.

**Comment by rborquezdiaz** [comment]
I'm facing a very similar issue. I'm in a position where I need to setup Firebase at runtime, possibly through MDM configuration. This renders the `GoogleService-Info.plist` file route useless unless it's possible to have a **Main Configuration** configured through the plist and a **Secondary Configuration** running alongside it made programatically. 

@morganchen12 @ryanwilson  I would love some clarification if this is something that can be done. On that note, `Analytics.logEvent` doesn't seem to require invoking an instance of `FirebaseApp`, am I correct to assume that calling logEvent will automatically send logged events to both **Main** and **Secondary**.

Thanks!

**Comment by morganchen12** [comment]
From what I understand if you try to configure two apps Analytics will ignore the secondary app and only log events to the main app.

**Comment by paulb777** [comment]
Closing in favor of #230
