### ISSUE TITLE
FirebaseFirestoreSwift supports for Carthage

### ISSUE THREAD

**Issue by xentokyo** [firebase/firebase-ios-sdk#4644]
I know it's working in progress for support Swift Package Manager but I hope FirebaseFirestoreSwift will support Carthage.

**Comment by wilhuff** [comment]
We still support Swift 4.2, which is prior to the ABI stability improvements in Swift 5.0 and 5.1. Until we make that our support floor, it's just too complicated to provide binary distributions for this pod.

**Comment by anatoliykant** [comment]
We need support for Swift 5 cage.
If you can’t do it now, then leave Fabric and Beta working.

**Comment by paulb777** [comment]
While we're not yet publishing a binary version of FirebaseFirestoreSwift,  the ZipBuilder [here](https://github.com/firebase/firebase-ios-sdk/tree/master/ZipBuilder) now supports building a binary framework of FirebaseFirestoreSwift with a desired Xcode version.

**Comment by anatoliykant** [comment]
> While we're not yet publishing a binary version of FirebaseFirestoreSwift, the ZipBuilder [here](https://github.com/firebase/firebase-ios-sdk/tree/master/ZipBuilder) now supports building a binary framework of FirebaseFirestoreSwift with a desired Xcode version.

thx, Paul!
Let's see how it works.

**Comment by mozeryansky** [comment]
@paulb777  I was unable to use ZipBuilder. I filed the ticket mentioned above.

**Comment by paulb777** [comment]
@mozeryansky Thanks for investigating. FirebaseFirestoreSwift should be buildable with Xcode versions before 11.4 or with the fixes introduced in #5294

**Comment by paulb777** [comment]
Closing in favor of the more recent and encompassing #7819
