### ISSUE TITLE
It's doesn't work on Multi-Target in Cocoapod

### ISSUE THREAD

**Issue by lostseaway** [firebase/firebase-ios-sdk#465]
* Xcode version:  9.1
  * Firebase SDK version: Firebase/Core (4.4.0)
  * Firebase Component: Core

I try to adopt Firebase into my project that has multi-targets in 1 project.
The target that I created is ```Cocoa Touch Framework```

This is my ```podfile```
```
platform :ios, '9.0'
use_frameworks!

workspace 'FirebaseProve.xcworkspace'

target 'FirebaseProve' do
    
end

target 'SomeTarget' do
    pod 'Firebase/Core'
end
```

Next, I run my project and It show out the ```log ```
```
objc[39848]: Class FIRAIdentifiers is implemented in both xxx/FirebaseProve-gnlkwtltwmkpqgdfrahtyedtphzu/Build/Products/Debug-iphonesimulator/SomeTarget.framework/SomeTarget (0x10a645498) 
and xxx/FirebaseProve.app/FirebaseProve (0x1098a6640).
One of the two will be used. Which one is undefined.
...
```
It's not only ```FIRAIdentifiers``` class but show many class from Firebase.

After that the application is crash.

I'm not sure that is a bug from Firebase or Cocoapod but It's work with other lib in Cocoapod. So I try to reported here.

**Comment by paulb777** [comment]
The Firebase CocoaPods are static frameworks and cannot be linked into app libraries.

**Comment by morganchen12** [comment]
Firebase will continue to not support being embedded in dylibs for the time being, since shipping Firebase as a dynamic library has app launch time tradeoffs for all of our users.
