### ISSUE TITLE
Crash prevention in FIRCLSNetworkClient

### ISSUE THREAD

**Issue by GUserx** [firebase/firebase-ios-sdk#4659]
- Xcode version: Version 11.3 (11C29)
- Firebase SDK version: deepens on component, not using the full sdk
- Firebase Component: Crashlytics
- Component version: Installed via cocoaPods

Hi everyone,
I would like to make a few changes in FIRCLSNetworkClient to make a code a little bit more safety :)
So the changes over here: https://github.com/firebase/firebase-ios-sdk/commit/bbc59fa45bca5c7de21925dfb32b776147f1ae66

I've seen that ReportManager passes nonnull block inside the networkClient but at some day any another client can pass a nil over here.

So may I create a pull request for this changes?
Also, FirebaseCrashlytics-Unit Tests successfully passed :)

**Comment by paulb777** [comment]
Thanks @GUserx and sorry but we need the PR first, along with a CLA (contributors license agreement), in order to discuss the proposed code changes.

Please do that and we can follow up.

**Comment by GUserx** [comment]
Hi @paulb777 !
Thank you for your response.
I've created the PR: https://github.com/firebase/firebase-ios-sdk/pull/4661
CLA provided as well.

**Comment by paulb777** [comment]
Thanks @GUserx ! It looks good to me.  

Someone from the Crashlytics team should follow up with you in more detail soon.
