### ISSUE TITLE
[Messaging] didReceiveRemoteNotification does not working in background 

### ISSUE THREAD

**Issue by matiasvillaverde** [firebase/firebase-ios-sdk#466]
### Environment 

  * Xcode version: Version 9.1 
  * Firebase SDK version: 
Using Firebase (4.6.0)
Using FirebaseAnalytics (4.0.5)
Using FirebaseCore (4.0.11)
Using FirebaseInstanceID (2.0.6)
Using FirebaseMessaging (2.0.6)
  * Firebase Component: Core, Messaging
   *  iOS: 11.1

### The problem

I am building a calendar app, where the reminders of the events are local push notifications. Every time there is a new event in the calendar, the server notifies the client with a silence push notification. In the didReceiveRemoteNotification I create and schedule the local push notifications for that event **but** the callback works always when phone connected to mac (by cable or wireless debugging), in this case it works in foreground, background and on locked screen as well. But if phone does not connected to mac, the didReceiveRemoteNotification callback fires only when app in foreground 

#### Steps to reproduce:

1) Can be reproduced in the iOS example app
2) Change didReceiveRemoteNotification according to my example.
3) Run app on device
4) Unplug cable
5) Kill the app and open it again
6) Move app to background
7) Send remote notification as described above
8) No local notification is schedule

##### Payload to firebase

```json
            {
                "to": "device_id",
                "content_available": true,
                "priority": "high",
                "data": {
                    "body": "Message",
                    "somevalue": "true"
                    
                }
            }
```

``` swift
    func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        
        // For test propuses I will add a local push notification in 1 second
        addNotificationForNow(body: userInfo["body"] as? String ?? "Error: No body in notification")
    }
    
    func addNotificationForNow(body: String) {
        // Get center
        let appDelegate = UIApplication.shared.delegate as! AppDelegate
        let center = UNUserNotificationCenter.current()
        center.delegate = appDelegate
        
        let content = UNMutableNotificationContent()
        content.body = body
        content.sound = UNNotificationSound.default()
        
        // Trigger
        let trigger = UNTimeIntervalNotificationTrigger.init(timeInterval: 1, repeats: false)
        let id = "1234" // For test proposes
        let request = UNNotificationRequest(identifier:id, content: content, trigger: trigger)
        center.add(request) { (error) in
            guard let errorToPrint = error else { return }
            print("Error adding localpush from remote: \(errorToPrint.localizedDescription)")
        }
    }
```

**Comment by morganchen12** [comment]
Usually when this happens (unplugging the cable results in silent notifications not being delivered reliably) the system is throttling your silent notifications to reduce resource usage. Silent notifications should still be delivered sometimes, though not necessarily immediately.

Make sure to call the `fetchCompletionHandler` in your implementation of `application(_:didReceiveRemoteNotification:fetchCompletionHandler:)`. This tells the system that your app is done processing in the background and therefore won't require more resources.

**Comment by matiasvillaverde** [comment]
@morganchen12 thanks for the quick reply.
* I am unplugging the cable and launching the app again, should not be this. 
* There was a mistake in the code I uploaded, but I am calling fetchCompletionHandler after the local push is schedule. 
* I waited sevar hours, with the phone fully charged but no silence push arrived. 
* They only arrive at the moment I launch the app again.

**Comment by morganchen12** [comment]
Silent notifications will stop being delivered when the user manually force-quits your app (also when low-power mode is enabled, and upon a device reboot until the app is launched again). This is normal system behavior.

Are silent notifications not delivered when the app is backgrounded?

**Comment by matiasvillaverde** [comment]
@morganchen12 They are also not delivered when the app is backgrounded. Only when the app enter foreground or when is in foreground.

**Comment by morganchen12** [comment]
Does sending regular (non-silent) notifications through FCM work when the app is backgrounded?

**Comment by matiasvillaverde** [comment]
Yes, it works perfect. Also if I include the content_available = true: 
The app calls didReceiveRemoteNotification when is backgrounded and in foreground. But is not calling this method when is killed.

**Comment by morganchen12** [comment]
From what it sounds like, there's nothing wrong with your implementation if you're able to receive all notifications when a charger is connected. I'm still not sure why you're unable to get any (even throttled) notifications in the background when the device isn't charging, but being able to receive normal notifications in this situation means your FCM setup is correct. Apple's docs are deliberately unclear about the extent of their notification throttling.

Silent notifications (content_available=true) will stop being delivered when your app is force-quit by the user, but non-silent ones will not.

**Comment by MauriceArikoglu** [comment]
From a recent project of mine: If I remember correctly the notification aps payload needs to contain `mutable-content: 1` next to `content-available:1` to wake a killed app.

This is allegedly related to battery saving measurements of iOS

**Comment by morganchen12** [comment]
If that behavior is undocumented Apple may change it in an OS update, so try not to depend on it.

**Comment by sacrificar** [comment]
Hello, is this issue solved? I have a same problem with @matiasvillaverde and couldn't find the solution yet. Could some one tell me how to solve this problem.
