### ISSUE TITLE
Won't connect to firebase

### ISSUE THREAD

**Issue by Jbarbe-Kaliop** [firebase/firebase-ios-sdk#4665]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version:  11.3
  * Firebase SDK version: 6.17
  * Firebase Component: Core
  * Component version: 6.5.0

### [REQUIRED] Step 3: Describe the problem

Firebase project setup phase is stuck at "Run your app yo verify installation" ( worked fine with Android for the same project ).

#### Steps to reproduce:

Actually I can't reproduce the bug as it happens only with a single firebase project.

We created a project in firebase and configure it as explained in firecasts tutorials with Xcode project for dynamic links.

I tried many things  :
-> Clean / Delete Derived Data / restart device 

Nothing did it atm.

I've also sent a message to firebase support as I don't know if it should be reported here, or firebase support.

**Comment by rizafran** [comment]
Hi @Jbarbe-Kaliop, thank for reporting. The final step on project setup in Console is optional, so you could try to skip it for now.

If you're still running into issue connecting to any Firebase Service, let them know in order for them to assist you better and to provide you any updates regarding this.
