### ISSUE TITLE
Firebase/InstanceID Couldn't add item to Keychain OSStatus: -25299

### ISSUE THREAD

**Issue by vokruttabtale** [firebase/firebase-ios-sdk#4676]
Hi! Sporadically I can't fetch remote config, I found next lines in logs. And a request for remote config goes with null app_instance_id and token.

default	20:09:44.105082+0100	fall	6.13.0 - [Firebase/InstanceID][I-IID023001] Couldn't add item to Keychain OSStatus: -25299
default	20:09:44.105132+0100	fall	6.13.0 - [Firebase/RemoteConfig][I-RCN000020] Failed to register InstanceID with error : Error Domain=com.google.iid Code=-25299 "(null)".

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.13.0
  * Firebase Component: Analytics, RemoteConfig

**Comment by rizafran** [comment]
Hi @vokruttabtale, could you provide the following details to see what's happening:

- Detailed steps that lead to the issue
- [Minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) or sample code of your app that I can reproduce locally
- Complete error logs
