### ISSUE TITLE
Restore system backup gives problem

### ISSUE THREAD

**Issue by SergeShkurko** [firebase/firebase-ios-sdk#4677]
### Environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.14.0
  * Firebase Component: FirebaseRemoteConfig
  * Component version: 4.4.6

### Description

I having an app with integrated Firebase remote config. I take a backup of all application and restore it again in the same iPhone/other iPhone. After the restoring backup, Firebase remote config is stopped working until the reinstall app again from AppStore, So some depended functions are not working in the live app.

The app is working normally after reinstalling from AppStore.

Getting error from Firebase Remote config is The operation couldn't be completed. (com.google.remoteconfig.ErrorDomain error 8003.)

Same issue [on stackoverflow](https://stackoverflow.com/questions/56495163/firebase-remote-config-is-stopped-working-after-restore-the-backup-in-iphone)

#### Steps to reproduce:

- Run app (remote config fetched success)
- Backup ios system
- Restore backup ios system
- Run app (remote config gives 0 keys)

**Comment by rizafran** [comment]
Hi @SergeShkurko, apologies for the  late response.  I have filed this issue internally tracked at (b/148386739).

**Comment by Goseong** [comment]
We are also experiencing this problem, any updates here? We have some key app feature relying on a valid remote config.

**Comment by rizafran** [comment]
@Goseong, I'm sorry to hear if this issue is negatively affecting your users. I have made a follow up internally, and we'll inform you as soon as we have an update.

**Comment by rizafran** [comment]
Hi all, this issue has been fixed in the latest release of SDK as shown [here](https://firebase.google.com/support/release-notes/ios#remote-config). Feel free to comment here if you're still experiencing an issue on restoring your backup, and we'll reopen this thread to continue investigating it.

**Comment by Goseong** [comment]
Great, thank you for the work!
