### ISSUE TITLE
Pod version 6.15.0 - Apple Mach-O Linker Error (10 items)

### ISSUE THREAD

**Issue by itsector-esanti** [firebase/firebase-ios-sdk#4685]
Describe your environment

  * Xcode version: 11.2.1
  * Firebase SDK version: 6.15.0
  * Firebase Component: Firebase/Analytics
  * Component version: 6.15.0

Describe the problem
I installed `pod 'Firebase/Analytics', '6.15.0' ` and I am facing a lot of problems that you can see below:

Undefined symbols for architecture x86_64:
  "_GULResetLogger", referenced from:
      _FIRResetLogger in FirebaseCore(FIRLogger.o)
  "_GULIsLoggableLevel", referenced from:
      _FIRIsLoggableLevel in FirebaseCore(FIRLogger.o)
  "_GULSetLoggerLevel", referenced from:
      _FIRSetLoggerLevel in FirebaseCore(FIRLogger.o)
  "_GULLoggerRegisterVersion", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_GULLoggerInitializeASL", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_GULLogBasic", referenced from:
      _FIRLogBasic in FirebaseCore(FIRLogger.o)
  "_GULLoggerEnableSTDERR", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_GULLoggerForceDebug", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_OBJC_CLASS_$_GULAppEnvironmentUtil", referenced from:
      objc-class-ref in FirebaseCore(FIRApp.o)
      objc-class-ref in FirebaseCore(FIRBundleUtil.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I already have tried to change to another old versions, but that problem happens too.

That is my **Podfile**:
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

def firebase_pods
  pod 'Firebase/Analytics', '6.15.0'
end

target 'MyTarget' do
  firebase_pods
end

**Comment by rizafran** [comment]
Hi @itsector-esanti, can you share your Podfile and Podfile.lock file to check the versions?

**Comment by itsector-esanti** [comment]
Hi @rizafran 

I have attached here!

[Podfile.txt](https://github.com/firebase/firebase-ios-sdk/files/4064523/Podfile.txt)
[Podfile.lock.txt](https://github.com/firebase/firebase-ios-sdk/files/4064524/Podfile.lock.txt)

**Comment by rizafran** [comment]
@itsector-esanti, I wasn't able to reproduce the issue on my end. Could you provide detailed steps to replicate it as well as the iOS version used? You may also share the complete stack trace.

**Comment by ryanwilson** [comment]
@itsector-esanti I noticed the `Podfile` you gave in the first comment is different from the attached `Podfile` - can you please confirm which one is causing you trouble? 

Also, a `pod update` may be required to ensure all recent dependencies are being pulled in.

**Comment by itsector-esanti** [comment]
Hello @ryanwilson 

Yes, you noticed well. It's because I just changed my local branch. But I am having the same problem.

**Comment by ryanwilson** [comment]
Does `pod update` help at all? We're unable to reproduce the issue on our end. If it doesn't, trying a blank project and seeing if it works for you would help determine if it's a machine specific problem or a project specific problem.

**Comment by itsector-esanti** [comment]
I did `pod update` and the error still happens when build the project.

Here my steps:

`pod update` in terminal and I got this information:

> Update all pods
> Updating local specs repositories
>   $ /usr/bin/git -C
>   /Users/itsector/.cocoapods/repos/gitlab-ebankit-ebankit-pod-specs fetch origin
>   --progress
>   warning: redirecting to https://gitlab.com/ebankIT/ebankIT-Pod-Specs.git/
>   $ /usr/bin/git -C
>   /Users/itsector/.cocoapods/repos/gitlab-ebankit-ebankit-pod-specs rev-parse
>   --abbrev-ref HEAD
>   master
>   $ /usr/bin/git -C
>   /Users/itsector/.cocoapods/repos/gitlab-ebankit-ebankit-pod-specs reset --hard
>   origin/master
>   HEAD is now at 3e0e959 Update ebankITUIComponents.podspec v4.5.2 with new source url
> Analyzing dependencies
> Downloading dependencies
> Generating Pods project
> Integrating client project
> Pod installation complete! There are 4 dependencies from the Podfile and 17 total pods installed.
> 
> [!] The `ebankIT Private [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-ebankIT Private/Pods-ebankIT Private.debug.xcconfig'. This can lead to problems with the CocoaPods installation
>     - Use the `$(inherited)` flag, or
>     - Remove the build settings from the target.
> 
> [!] The `ebankIT Private [QA]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-ebankIT Private/Pods-ebankIT Private.qa.xcconfig'. This can lead to problems with the CocoaPods installation
>     - Use the `$(inherited)` flag, or
>     - Remove the build settings from the target.
> 
> [!] The `ebankIT Private [CI4]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-ebankIT Private/Pods-ebankIT Private.ci4.xcconfig'. This can lead to problems with the CocoaPods installation
>     - Use the `$(inherited)` flag, or
>     - Remove the build settings from the target.
> 
> [!] The `ebankIT Private [CI6]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-ebankIT Private/Pods-ebankIT Private.ci6.xcconfig'. This can lead to problems with the CocoaPods installation
>     - Use the `$(inherited)` flag, or
>     - Remove the build settings from the target.
> 
> [!] The `ebankIT Private [CI5]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-ebankIT Private/Pods-ebankIT Private.ci5.xcconfig'. This can lead to problems with the CocoaPods installation
>     - Use the `$(inherited)` flag, or
>     - Remove the build settings from the target.
> 
> [!] The `ebankIT Private [CI3]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-ebankIT Private/Pods-ebankIT Private.ci3.xcconfig'. This can lead to problems with the CocoaPods installation
>     - Use the `$(inherited)` flag, or
>     - Remove the build settings from the target.
> 
> [!] The `ebankIT Private [CI2]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-ebankIT Private/Pods-ebankIT Private.ci2.xcconfig'. This can lead to problems with the CocoaPods installation
>     - Use the `$(inherited)` flag, or
>     - Remove the build settings from the target.
> 
> [!] The `ebankIT Private [CI1]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-ebankIT Private/Pods-ebankIT Private.ci1.xcconfig'. This can lead to problems with the CocoaPods installation
>     - Use the `$(inherited)` flag, or
>     - Remove the build settings from the target.
> 
> [!] The `ebankIT Private [PROD]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-ebankIT Private/Pods-ebankIT Private.prod.xcconfig'. This can lead to problems with the CocoaPods installation
>     - Use the `$(inherited)` flag, or
>     - Remove the build settings from the target.

After it, I cleaned and build the project again, and I got these erros:
![Captura de Tela 2020-01-15 às 16 19 23](https://user-images.githubusercontent.com/52241324/72450863-f1e14480-37b2-11ea-9efd-1c4c92228779.png)

**Comment by paulb777** [comment]
I suspect the CocoaPods warning about `OTHER_LDFLAGS` is related to the problem. 

Perhaps a `$inherited` needs to be added to the project settings

**Comment by itsector-esanti** [comment]
Yes, it was.

People, thank you very much for you help!
