### ISSUE TITLE
Out of sync release notes

### ISSUE THREAD

**Issue by revolter** [firebase/firebase-ios-sdk#4686]
The latest [6.15.0 release](https://github.com/firebase/firebase-ios-sdk/releases/tag/6.15.0) says:

> The Firebase iOS SDK (v6.15.0) is now available. For more details, see the [Firebase iOS SDK release notes](https://firebase.google.com/support/release-notes/ios#6.15.0).

But that link doesn't have the release notes for it. And I think that this happens for every release. You should somehow ensure that the releases and the release notes are always in sync, maybe via a script or cron job or something.

**Comment by ryanwilson** [comment]
Thanks for the report @revolter - we're working to get the notes out ASAP. We appreciate the feedback and will try to do better here in the future.

**Comment by ryanwilson** [comment]
The 6.15.0 release notes are now live at [the link in the release](https://firebase.google.com/support/release-notes/ios#6.15.0). Thanks again for the report, I'll close this for now but we'll continue to work on getting these more in sync for future releases.

**Comment by revolter** [comment]
6.14.0 is gone though.

**Comment by ryanwilson** [comment]
Shoot sorry about that, I'll get them added again ASAP.

**Comment by ryanwilson** [comment]
The 6.14.0 release notes are back. Sorry again and thank you for catching it!
