### ISSUE TITLE
Make sure CI runs dependent SDKs tests after a dependency change

### ISSUE THREAD

**Issue by maksymmalyhin** [firebase/firebase-ios-sdk#4688]
Currently we manually update [if_changed.sh](https://github.com/firebase/firebase-ios-sdk/blob/8cd933b74e517180ca67a0d0502d89c65c519925/scripts/if_changed.sh) to make sure the tests for dependent projects are run for PRs. Ideally, we should update the scripts so, that the dependency are calculated based on the SDK podspecs.

**Comment by ryanwilson** [comment]
It's not ideal but the cron job is likely enough. Running every product's CI for a change in something like Core would be expensive and slow, so we likely won't make changes here and depend on the cron job to catch things within 24 hours.
