### ISSUE TITLE
Firestore: iOS Bypassing Security Rules for FIRDocumentSnapshot()

### ISSUE THREAD

**Issue by brianhiss** [firebase/firebase-ios-sdk#469]
### Environment
* Xcode version: Xcode 9.1, Simulator: iOS 11.1 iPhone 6
* Firebase SDK version: 4.6.0 (including 4.5.0)
* Firebase Component: Firestore
 * Component version: 0.9.2 (including 0.9.1)
* Development Operating System: MacOS Sierra 10.12.6

### Issue

I was having an issue with Firestore on iOS bypassing security rules on a collection when I converted from a `get()`, to a `onSnapshot()` listener.

I have confirmed my rules are working correctly via the `get()` in iOS, and both the `get()` and `onSnapshot()` listener work correctly in the Firebase JS SDK and Android SDK.

I don't believe this is an offline cached data issue, as I'm able to get updated data, along with data the user would never had access to.

### Note

I noticed on the [Firestore Security Rules](https://firebase.google.com/docs/firestore/security/get-started) there is a Note:

> Note: Because the server client libraries authenticate through Google Application Default Credentials, they bypass any Cloud Firestore Security Rules you set up. If you are using the server client libraries or the REST or RPC APIs, make sure to set up Cloud Identity and Access Management for Cloud Firestore.

I'm not sure, but does the iOS SDK require Cloud Identity since it makes use of the gRPC library?

### My Security Rules
Again, these work correctly on the Firebase JS SDK, Android SDK and for `get()` on iOS, but not for `onSnapshot()`.
```
service cloud.firestore {
  match /databases/{database}/documents {

     match /orders/{orderId=**} {
        allow read: if request.auth.uid == resource.data.user.id;
        allow write: if false;
      }

   }
}
```

#### get() on JS SDK
```
firestore.collection('orders')
            .where('user.id', '==', user.uid)
            .get().then(snapshot => {

                console.log('Snapshot: ', snapshot);

            }, function(err) {

                console.log('Error: ', err);

            })
```
#### get() on IOS SDK
```
[[[self.db collectionWithPath:@"orders"] queryWhereField:@"user.id" isEqualTo:@"myUserId"]
    getDocumentsWithCompletion:^(FIRQuerySnapshot *snapshot, NSError *error) {
      if (error != nil) {
        NSLog(@"Error getting documents: %@", error);
      } else {
        for (FIRDocumentSnapshot *document in snapshot.documents) {
          NSLog(@"%@ => %@", document.documentID, document.data);
        }
      }
    }];
```
#### onSnapshot() on JS SDK
```
firestore.collection('orders')
            //.where('user.id', '==', user.uid)
            .onSnapshot(snapshot => {

                console.log('Snapshot: ', snapshot);

            }, function(err) {

                console.log('Error: ', err);

            })
```

### ByPassed Security Rules (Should fail like JS SDK)
This should fail since I did not specifiy a `user.id`, as required by the rules. Instead, this gives me all the orders. This does correctly return `Error: Missing or insufficient permissions.` on the Firebase JS & Android SDK.

One odd note, is it does fire both the `snapshot` sending the data, but then it does sometimes call `err` and give the error. But, it always sends the data regardless.

#### FIRDocumentSnapshot() on iOS SDK
```
[[self.db collectionWithPath:@"orders"]
    addSnapshotListener:^(FIRQuerySnapshot *snapshot, NSError *error) {
      if (snapshot == nil) {
        NSLog(@"Error fetching documents: %@", error);
        return;
      }
      NSMutableArray *orders = [NSMutableArray array];
      for (FIRDocumentSnapshot *document in snapshot.documents) {
        [orders addObject:document.data[@"id"]];
      }
      NSLog(@"Current orders: %@", orders);
    }];
```

**Comment by mikelehen** [comment]
This is very strange as the Android, iOS, and JS SDKs all talk to the backend in the same way and so rules should behave exactly identically. Additionally, this would represent a severe security issue, but I haven't heard any other reports.  The only reason I can think of why you'd get results from the query is if there's previously-cached data on the device and so you get an event containing this cached data.  Note that this should be followed by a "permission denied" error once the client talks to the backend and the rules reject the query.

If you believe something else is going on, can you please provide a standalone way to reproduce this issue? Or can you capture a log where you get up-to-date data back (guaranteed not to be from cache) by calling Firestore.enableLogging(true)?  You can provide the repro / logs directly to me at michael@firebase.com. Thanks!

**Comment by brianhiss** [comment]
@mikelehen Thank you for the detailed response.

I assumed they behaved exactly the same, but seeing as the iOS library used gRPC, I didn't know if there was something that might have been missed.

I did enable `Firestore.enableLogging(true)`, but it's not pulling fresh data. I've been able to hack around and see that there is some data in there that was cached, but I was able to reproduce the issue at least once with a fresh install. Not sure if deleting the app from the iOS simulator also clears the cached data, but I assumed so. That might not have been the cache.

Regardless, after a `pod update`, I'm able to have consistent results now and the rules seem to behave as expected. 

I'll keep you apprised if I run into any further inconsistencies and able to provide you a reproducible example.

**Comment by mikelehen** [comment]
Sounds good. Thanks for following up!  FYI- The Android client also uses GRPC.  The Web client does not, but it _shouldn't_ make a difference, since the transport layer is pretty isolated from rules evaluation.  So this probably isn't an iOS-specific bug...  but there could be an inconsistent difficult-to-reproduce bug.  Definitely holler if you see anything more suspicious.  Thanks!

**Comment by zkdzegede** [comment]
I think I'm getting the same issue with the Golang SDK.   
I am using these [Golang examples](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/firestore/apiv1beta1/firestore_client_example_test.go)

I am able to read information for documents even when I shouldn't be able to.

# Rules
```
match /device/{document=**} {
    allow read, write: if request.auth.uid == resource.data.owner;
}
```

Even with the above rules I can read all my "devices" from golang, but only read the ones with the correct owner through the JS SDK.

**Comment by mikelehen** [comment]
@zkdzegede The server client libraries bypass all Cloud Firestore Security Rules and instead authenticate through Google Application Default Credentials. If you are using the server client libraries or the REST or RPC APIs, make sure to set up Cloud Identity and Access Management for Cloud Firestore.

**Comment by zkdzegede** [comment]
@mikelehen 

I'm trying to use golang for an embedded "client" not as a "server client".  
In that case would I still want to use IAM for something I am distributing to end users?

When I was looking at the Access Management for Cloud documentation it seemed like the controls were not for user level access controls the same way the Cloud Firestore Security Rules did, but rather at the developer/service/group/suite level.

The fact that my golang code could completely bypass all the database access rules just by knowing the project-id seems a bit dangerous.  Or did I miss a setting that would prevent that from happening without the proper IAM authentication. 🤔

**Comment by zkdzegede** [comment]
Sorry I just realized that this issue is under firebase-ios-sdk, but it sounded so close to what I was experiencing I thought I should add it here after reading ``` Definitely holler if you see anything more suspicious ```
