### ISSUE TITLE
Firebase Installations: throw exception on missing FIROptions.projectID or invalid API Key

### ISSUE THREAD

**Issue by maksymmalyhin** [firebase/firebase-ios-sdk#4692]
**Background:**
- `FIROptions.projectID` is needed for Firebase Installations SDK(FIS SDK) to be sent with API requests
- FIS SDK is a dependency for Firebase Instance ID SDK (IID SDK) (starting from IID SDK 4.3.0)
- IID SDK does not require `FIROptions.projectID`. It means that introducing a new dependency enforcing `projectID` to IID SDK technically is a breaking change and should not be introduced until a major release. 

**Workaround:**
FIS SDK uses `FIROptions. GCMSenderID` in case if `FIROptions.projectID` is missing to avoid breaking changes. (see #4683)

**To be done:**
- Update FIS SDK to enforce `FIROptions.projectID` for the next major release (Firebase 7)
- Enforce API Key format to filter non-Firebase API keys accident use (b/147712985)

**Comment by ryanwilson** [comment]
Is there a downside to using the `GCMSenderID` on the server side? Just wondering if it's necessary to break eventually if `GCMSenderID` has no downsides.

**Comment by maksymmalyhin** [comment]
I think @andirayo can provide the best answer here. As far as I know using `GCMSenderID` for this purpose is a bit of a hack and is fine to use just until we can do breaking changes. Also `GCMSenderID` is considered to be deprecated, so we should promote using it.
