### ISSUE TITLE
Argument labels '(_:, in:)' do not match error in Firestore compound query using 'IN' operator

### ISSUE THREAD

**Issue by hiteshinfostride** [firebase/firebase-ios-sdk#4712]
**Environment :**
  * Xcode version: 11.1
  * Firebase SDK version: 6.2.0
  * Firebase Component: Firestore
  * Component version: 6.6.0

**Problem :** 
I am getting the error - Argument labels '(_:, in:)' do not match any available overloads while using compound query using 'IN' operator as stated in the docs - https://firebase.google.com/docs/firestore/query-data/queries

**Relevant Code:**

let citiesRef = db.collection("cities")
citiesRef.whereField("country", in: ["USA", "Japan"])

**Comment by rizafran** [comment]
Hi @hiteshinfostride, looks like the IN operator was added on 6.12.0 as stated [here](https://firebase.google.com/support/release-notes/ios#cloud-firestore_4). Could you try to update your SDK version and see if the issue persist?

**Comment by hiteshinfostride** [comment]
@rizafran thank you, i updated the SDK version and the issue is resolved now.

**Comment by rizafran** [comment]
You're most welcome, @hiteshinfostride. I'm happy to hear that the issue is resolved now.
