### ISSUE TITLE
[InAppMessaging] Banner message display overlaps status bar on iPad Pro 11"

### ISSUE THREAD

**Issue by xaphod** [firebase/firebase-ios-sdk#4714]
### [READ] Step 1: Are you in the right place?

According to @christibbs yup

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.15.0
  * Firebase Component: InAppMessaging
 * Component version: 0.16.0, InAppMessagingDisplay is 0.15.5

### [REQUIRED] Step 3: Describe the problem

Banner message overlaps with status bar text, looks awful. See photo:

![72654704-b4211f00-395e-11ea-8d85-caa7e1464adb](https://user-images.githubusercontent.com/3776302/72834645-41ae8880-3c57-11ea-90fd-84015c646884.png)

#### Steps to reproduce:

Display a banner style message on iPad Pro 11" (2018 model, the only one I think), running iOS 13.3

**Comment by rizafran** [comment]
Thanks for reporting the issue, @xaphod. I was able to replicate this using the sample quickstart. I filed this internally (b/148132944) and I'll let you know once I have an update.

**Comment by christibbs** [comment]
Sorry for the delay, this will be fixed in an upcoming release. Will close when code is complete.
