### ISSUE TITLE
[FirebaseAuth] Unexpected expansion of `uid` to `user_id` inside of `claims` variable, class AuthTokenResult

### ISSUE THREAD

**Issue by isupremedyou** [firebase/firebase-ios-sdk#4716]
* Xcode version: Version 11.3.1 (11C505)
  * Firebase SDK version: 6.13.0
  * Firebase Component: Auth
  * Component version: 6.4.0

When unpacking the `claims` dictionary after calling `getIDTokenResult(forcingRefresh:completion:)` on an instance of `FIRUser` we are getting unexpected behavior for the key `user_id`. We are using `user_id` in our additional claims of our custom auth token. It appears that the `uid` from our custom JWT is being expanded to `user_id` inside of the `FirebaseAuth` SDK.

1. Generate a JWT according to the instructions given on this page:
https://firebase.google.com/docs/auth/admin/create-custom-tokens

2. Note that there are specific keys reserved and `user_id` is not listed in the documentation as a one reserved by the SDK (see highlighted section "Firebase tokens comply with the OpenID Connect JWT spec..."): 
https://firebase.google.com/docs/auth/admin/create-custom-tokens#create_custom_tokens_using_the_firebase_admin_sdk

**Sample Decoded Payload from our custom JWT**
```
{
  "iss": **REDACTED**,
  "sub": **REDACTED**,
  "aud": "https://identitytoolkit.googleapis.com/google.identity.identitytoolkit.v1.IdentityToolkit",
  "iat": 1579642678,
  "exp": 1579642738,
  "uid": "1",
  "claims": {
    "user_id": 7482,
    "premium_account": true
  }
}
```

3. From the iOS SDK use the generated token with this method `Auth.Auth().signIn(withCustomToken:)`.

4. After successful sign in, use the following method so you can obtain the additional claims that you passed via a custom JWT auth token:
```
Auth.auth().currentUser.getIDTokenResult(forcingRefresh: false, completion: { (tokenResult, error) in
  guard let tokenResult = tokenResult else {
    print("Error while getting Firbase Auth tokenResult:", error!)
    return .failure(error!)
  }
  let claims = tokenResult.claims
  print(claims)
}
```

In this example `claims["user_id"]` is equal to `uid` from the JWT (`1`), instead of being equal to what we passed inside of `claims` from our JWT (`7482`).

**Desired/Expected Behavior**
We expected the use of `user_id` to be safe, because we did not use any of the reserved keys inside our additional claims, as suggested in documentation:

```
Firebase tokens comply with the OpenID Connect JWT spec, which means the following claims are reserved and cannot be specified within the additional claims:

acr
amr
at_hash
aud	
auth_time
azp
cnf
c_hash	
exp
firebase
iat
iss	
jti
nbf
nonce
sub
```

I would like the top level `uid` key to **not be expanded** to `user_id` so I can make use of `user_id` inside the additional claims.

**Comment by morganchen12** [comment]
@renkelvin, is this expected behavior? If so, we should add it to the list of reserved keys in the documentation.

**Comment by isupremedyou** [comment]
@renkelvin, any updates on whether this is expected (undocumented) behavior?

**Comment by morganchen12** [comment]
Sorry for the delay, he's out of office until Monday.

**Comment by renkelvin** [comment]
It's a tricky case to fix. My suggestion is to use something like "custom_user_id".

**Comment by isupremedyou** [comment]
Is there a reason this is undocumented? If the key is invalid for use, we at least want to know that in the docs that I mentioned. Thanks for your response?

**Comment by morganchen12** [comment]
@isupremedyou this should definitely be documented, and the key is not valid for use. Sorry for the confusion!

**Comment by isupremedyou** [comment]
Thanks! Also that ‘?’ was accidental!

I meant: thank you for your response!

**Comment by MeghaB** [comment]
For internal tracking, b/156545273 for the relevant doc updates

**Comment by morganchen12** [comment]
Docs update change number (Googlers-only): cl/324094754
