### ISSUE TITLE
Unable upload the APNS Key

### ISSUE THREAD

**Issue by venkatesh513** [firebase/firebase-ios-sdk#4721]
After Adding APNS key and team Id its showing nothing, just loading and closing.
Can anyone help me?

**Comment by venkatesh513** [comment]
I resolved myself.

**Comment by rizafran** [comment]
@venkatesh513, I'm glad to hear that the issue has resolved. I'm going to close this now. If you're still having an issue, just leave a comment here and we're happy to re-open this.
