### ISSUE TITLE
Revert FIAMDisplay Zip Builder workaround

### ISSUE THREAD

**Issue by maksymmalyhin** [firebase/firebase-ios-sdk#4728]
Revert the FIAMDisplay Zip Builder workaround #4727 once [FirebaseInAppMessagingDisplay](https://github.com/firebase/firebase-ios-sdk/blob/48aa5ed5ee30d01a184e757df806169195df00df/FirebaseInAppMessagingDisplay.podspec) is removed.

**Comment by paulb777** [comment]
I believe this could be sooner than Firebase 7 because FIAM is still in beta.
