### ISSUE TITLE
Veracode Issue in RCNConfigSettings.m

### ISSUE THREAD

**Issue by smandrusk** [firebase/firebase-ios-sdk#4735]
Hi,

I am using Veracode for code analysis and a security issue has been raised in the following file:
File: RCNConfigSettings.m: 218
Function: -[RCNConfigSettings updateExponentialBackoffTime]

The issue in Veracode states:
"Description: Standard random number generators do not provide a sufficient amount of entropy when used for security purposes. Attackers can brute force the output of pseudorandom number generators such as rand()."

  * Xcode version: 11.2.1
  * Firebase SDK version: 6.15.0
  * Firebase Component: RemoteConfig
  * Component version: 4.4
  * Installation method: CocoaPods

**Comment by morganchen12** [comment]
The code referenced is [here](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseRemoteConfig/Sources/RCNConfigSettings.m#L218) and is not used for security.
