### ISSUE TITLE
Firebase 6.6 reports error Unable to find module header

### ISSUE THREAD

**Issue by chawatvish** [firebase/firebase-ios-sdk#4741]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3
  * Firebase SDK version: Firebase 6.15
  * Firebase Component: Core
  * Component version: 6.6.0
  * Installation method: `CocoaPods` (select one)

### [REQUIRED] Step 2: Describe the problem

I try to update version of your dependencies and we founded the error build message below.

`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FIRHeartbeatInfo", referenced from:
      objc-class-ref in FirebaseInstallations(FIRInstallationsAPIService.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`"

And then I try again with a fix version of FirebaseCore to 6.5.0. It's work fine.

**Comment by paulb777** [comment]
The current version is 6.15.0.  Please update.  There may be some intra-Firebase version dependency problems with some of the older releases.

**Comment by paulb777** [comment]
Sorry, looking more carefully at the description, I see that you're referring to the FirebaseCore version which is up to date.

However, we'll still need more info about what is going on since `FIRHeartbeatInfo` is defined here https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseCore/Sources/FIRHeartbeatInfo.m.

`pod deintegrate` and `pod update` might help.

**Comment by chawatvish** [comment]
> The current version is 6.15.0. Please update. There may be some intra-Firebase version dependency problems with some of the older releases.

Sorry, I mean Firebase Core 6.6.0.

**Comment by chawatvish** [comment]
> Sorry, looking more carefully at the description, I see that you're referring to the FirebaseCore version which is up to date.
> 
> However, we'll still need more info about what is going on since `FIRHeartbeatInfo` is defined here https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseCore/Sources/FIRHeartbeatInfo.m.
> 
> `pod deintegrate` and `pod update` might help.

I try to deintegrate and update. It doesn't work and show same error.

**Comment by morganchen12** [comment]
Can you share a project that reproduces this issue?

**Comment by chawatvish** [comment]
Sorry, I can't 😅

**Comment by morganchen12** [comment]
Unfortunately we won't be able to make progress on this issue without a way to reproduce it. Can you create a reduced sample project that replicates the issue and share that instead?

**Comment by chawatvish** [comment]
> Unfortunately we won't be able to make progress on this issue without a way to reproduce it. Can you create a reduced sample project that replicates the issue and share that instead?

I got it, I try to create a new project and install dependencies similar to my main project. It's work
