### ISSUE TITLE
[Remote Config] non-"atomic" update crash

### ISSUE THREAD

**Issue by schlossm** [firebase/firebase-ios-sdk#4750]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: **Xcode 11.3.1**
  * Firebase SDK version: **6.14 (latest at time of writing ticket)**
  * Firebase Component: **RemoteConfig**
  * Component version: **6.14**
  * Installation method: **CocoaPods**

### [REQUIRED] Step 2: Describe the problem

TL;DR: When the initial view controller is listening to `UserDefaults.didChangeNotification` in order to reset some UI which needs remote config values, a remote config download causes the notification to fire before the remote config values are properly loaded into memory.  This causes an unsafe access which ultimately crashes the app.

--

The crash specifically occurs in `-[FIRRemoteConfig configValueForKey:namespace:]`.  Crashlytics reports the crash as happening on line 378.

When the app is started, we dispatch an async call to fetch the latest remote config values.  While that's occurring, the initial view controller has appeared and registered itself for UserDefault changes.  For context: our app contains a debug panel when built in `DEBUG` mode that allows internal users to change various settings, some of which are stored in UserDefaults.

Upon successful download of remote config values, it looks like `RCNFetch` stores the metadata into `UserDefaults`.  This triggers a call to `UserDefaultsDidChangeNotification`, which in turn executes our listener.  This listener asks `RemoteConfig` for a key's value in order to update some UI, which remote config in turn doesn't have in memory yet.  This occurs synchronously due to the `[_userDefaults synchronize]` call in `RCNUserDefaultsManager.m` on Line 211.

As a stopgap, we've moved away from `NotificationCenter` to our own basic homegrown solution.  However, we would like to help prevent other teams from encountering this issue in the future.

My line of thought is that this should be an "atomic" operation, in which the remote config data is fully ready before the metadata save calls out to `UserDefaults`, which internally posts to `NotificationCenter`, which triggers external code.

#### Steps to reproduce:

1. On app startup the following actions happen pretty much simultaneously:
    1. initialize firebase sdk and call `RemoteConfig.fetch()`
    2. initial VC is loaded onto the screen.  In `viewDidLoad`, register for `UserDefaults.didChangeNotification`
2. `RemoteConfig` fetch completes, storing metadata into `UserDefaults` before passing up download completion
3. Step 2 triggers a synchronous `UserDefaults.didChangeNotification` post which calls the Selector registered in Step 1.2
4. Selector from Step 1.2 asks for some data from `RemoteConfig`
5. Data is not "ready" yet, thus crashing the app

#### Relevant Code:

Easiest to reproduce on the first install
[FirebaseTestProject.zip](https://github.com/firebase/firebase-ios-sdk/files/4113145/FirebaseTestProject.zip)

Linking @vinceis1337 for our team visibility/tracking

**Comment by dmandar** [comment]
Hi..thanks for reporting. Looks like your notification for userDefaultsChanged is getting triggered from the internal serial queue used for synchronization and a subsequent call to configValueForKey triggers a dispatch_sync, causing a crash. Given that using a serial queue is the current synchronization mechanism and changing this would take time, pls consider the following recommended option is such a case: Wait on ensureInitialized to make sure initialization is completed. ( https://firebase.google.com/docs/reference/swift/firebaseremoteconfig/api/reference/Classes/RemoteConfig#/c:objc(cs)FIRRemoteConfig(im)ensureInitializedWithCompletionHandler: ). 

Please reopen if adding ensureInitialized still does not solve the issue for you.
