### ISSUE TITLE
Firebase/InAppMessaging - Message display component is not present yet. No display should happen.

### ISSUE THREAD

**Issue by AngeloGiurano** [firebase/firebase-ios-sdk#4768]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 10.2.1
  * Firebase SDK version: 6.15.0
  * Firebase Component: InAppMessaging
  * Component version: 0.16.0
  * Installation method: `CocoaPods 1.7.5`
  * iOS version: 13.3

### [REQUIRED] Step 2: Describe the problem

I can not test the in app messages since they won't simply render, seems like there is an error in the rendering phase, since the message seems to be received:

```
- [Firebase/InAppMessaging][I-IAM160001] There are 0 test messages and 1 regular messages and 0 Firebase Analytics events to watch after resetting the message cache
2020-01-29 13:36:16.936724+0100 THX[4380:774803] 6.15.0 - [Firebase/InAppMessaging][I-IAM150004] Persistent file path for fetch response data is /var/mobile/Containers/Data/Application/FF2FE6BE-95BB-4680-A3B2-6DB3A2BFFB7C/Library/Caches/firebase-iam-messages-cache
2020-01-29 13:36:16.936801+0100 THX[4380:774803] 6.15.0 - [Firebase/InAppMessaging][I-IAM240002] Fetch is done. Start message rendering flow.
2020-01-29 13:36:16.948518+0100 THX[4380:774803] [Answers] Finished transmission of '3D8CC612-4857-47D3-AD8D-ED9DEBEB4DA4'.
2020-01-29 13:36:17.472539+0100 THX[4380:774901] 6.15.0 - [Firebase/InAppMessaging][I-IAM400027] Message display component is not present yet. No display should happen.
```

#### Steps to reproduce:
Simply followed the documentation on https://firebase.google.com/docs/in-app-messaging/get-started

Tried both test on device and simply triggering a campaign but both of them fail on the render execution

#### Relevant Code:
Not applicable

**Comment by ryanwilson** [comment]
Hi @AngeloGiurano - thanks for the report. The instructions have been updated for the latest version of InAppMessaging (released yesterday) where the Display component is now part of `Firebase/InAppMessaging` where previously it was in a separate component, `InAppMessagingDisplay`. 

Please make sure you run `pod update` to get the latest version of Firebase, it should be `6.16.0` with `FirebaseInAppMessaging` being version `0.17.0`.

Let us know if that helps!

**Comment by AngeloGiurano** [comment]
@ryanwilson First of all thanks for the quick reply and flawless solution.

I have been heavily testing to get back to you today, I've been able to display the In-App Messages but came up with a doubt

The limit of one message per day to be displayed regards all In-App messages or just one per campaign?

Because even if I create multiple campaigns with different names I'm getting this message

`THX[5255:963182] 6.16.0 - [Firebase/InAppMessaging][I-IAM400003] Minimal display interval of 86400.000000 seconds has not been reached yet.
`

Please let me know if it is the desired outcome or I shall create another issue.

Thanks once again and wish you a lovely day!

**Comment by ryanwilson** [comment]
I'm not sure personally but I'll reach out to the InAppMessaging team and get them to respond when they can, thanks!

**Comment by MeghaB** [comment]
Hey Angelo!
Thanks for your question - we allow only 1 *on app foreground or app launch* campaign a day - this is to prevent you from accidentally overwhelming your users with non-contextually appropriate messages. However, if you use the contextual triggers (ie: Analytics event or problematically triggered FIAM campaigns), there is no daily rate limit.

**Comment by AngeloGiurano** [comment]
Hi @MeghaB, thank you for your reply and explanation, now everything is clear :)
