### ISSUE TITLE
How to track firebase dynamic link

### ISSUE THREAD

**Issue by Narendra-Pandey** [firebase/firebase-ios-sdk#4775]
i have added UTM parameter using FIRDynamicLinkGoogleAnalyticsParameters

```
FIRDynamicLinkGoogleAnalyticsParameters *analyticsParams =
  [FIRDynamicLinkGoogleAnalyticsParameters parametersWithSource:Source
                                                         medium:Medium
                                                       campaign:Campaign];
  analyticsParams.term = Term;
  analyticsParams.content = Content;
  components.analyticsParameters = analyticsParams;
```

Now i want to track the dynamic link like this,

if i have shared on Facebook, any one tap on that link then it will go to application if there else it will go to App Store.

After i need to show message based upon it’s source i.e welcome from Facebook like message. 

So can we track dynamic link and check from where the link has been tapped and show relevant message based upon i’t source.

**Comment by morganchen12** [comment]
You can't track where the link was tapped from unless you create a custom link (or add custom parameters) for each source, but even then this will result in mismatches if a user ever copies a link and shares it to a different source.

**Comment by Narendra-Pandey** [comment]
@morganchen12  You mean to say if I create a campaign, using **FIRDynamicLinkGoogleAnalyticsParameters** when one tap on Facebook I will pass **Facebook** in dynamic Link campaign.  Then can track this link ?

Also one confusion I have for getting campaign from **first_open**  i.e installing from App Store and opening first time.

Steps:
1. Create dynamic link, add campaign based on tapped platform. i.e Facebook, twitter, instagram.
2. Someone tapped on link from Facebook, install application from link.
3. Can I get campaign, source, medium , terms, content while first_open ?

I got to know pending link via this code:

   `  FIRDynamicLink *dynamicLink = [[FIRDynamicLinks dynamicLinks] dynamicLinkFromCustomSchemeURL:url];
`

As this code will be written in open url block

```
- (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)url
            options:(NSDictionary<NSString *, id> *)options;
```

@morganchen12  Please let me know does I am going in right direction?  or something I need to correct or add here.

**Comment by morganchen12** [comment]
You're headed in the right direction, but be aware that if a user copies your link from Facebook and shares it to a different website, the Facebook parameters will still be present and you will misattribute some percentage of your link opens.

Also, when filing new issues please follow the issue template.
