### ISSUE TITLE
firebase.configure crash in second target in workspace 

### ISSUE THREAD

**Issue by MohmmadSawalha-ios** [firebase/firebase-ios-sdk#4776]
### [REQUIRED] Step 1: Describe your environment
  * Xcode version: _____ 11.0
  * Firebase SDK version: _____Latest
  * Firebase Component: _____Messaging, instanceID, analytics
  * Component version: _____Latest
  * Installation method: `CocoaPods | Carthage | Zip file` (CocoaPod)
`  pod 'FirebaseInstanceID'
    pod 'Firebase/Analytics'
    pod 'Firebase/Messaging'`

#### Steps to reproduce:
I have two targets in the workspace, one of my targets that i implemented firebase in first works fine, the  crashes giving this log

`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[FIRInstanceIDCheckinPreferences preferencesFromKeychainContents:]: unrecognized selector sent to class 0x10f525108'`

Inside this function : `(FIRInstanceIDCheckinPreferences *)cachedCheckinPreferences`
This file: `FIRInstanceIDCheckinStore.m`

**Comment by rizafran** [comment]
Thanks for reporting this issue, @MohmmadSawalha-ios. Have you tried to update your Cocoapods? You may also check out this [post](https://stackoverflow.com/a/42218599) which might help you to fix the issue.

**Comment by MohmmadSawalha-ios** [comment]
Hey @rizafran  thanks for replying, yes i did actually followed every step with no hope, i even changed the project on firebase console made separated one same issue .

**Comment by MohmmadSawalha-ios** [comment]
I also deleted the app multiple times, clean build, changed devices that i test on .. same issue.

**Comment by maksymmalyhin** [comment]
@MohmmadSawalha-ios The issue looks very similar to #4711 because you also experience a crash with `unrecognized selector` exception for a method defined in an Objective C category in Firebase SDK. 

I would start from verifying `-ObjC` flag presence in "Other Linker Settings" of the failing target. If that doesn't help, could you please try follow the troubleshooting steps  from #4711 and let us know the result.

**Comment by MohmmadSawalha-ios** [comment]
It is i've seen that thread `-ObjC` flag is there since before, i will troubleshoot this again and give you the results .

**Comment by MohmmadSawalha-ios** [comment]
@maksymmalyhin  
Same issue i have degenerated pod file with the steps, tried to separate the target pods, updated cocoapods, compared build settings, clean project, deleted derived, legacy build nothing worked.

**Comment by rizafran** [comment]
Thanks for sharing your findings, @MohmmadSawalha-ios. Is it possible for you to share a simplified project that I can run locally? This way, it would be great for us to debug the issue.

If not possible, you could reproduce it with one of our quickstart samples [here](https://github.com/Firebase/quickstart-ios) and share it to us to identify if it's project specific or not.

**Comment by mvpscottjon** [comment]
I have same problem ,too 

I was use firebase version 6.14.0, second target was fine, but after I update to 6.17.0, 
app will crash after launch.

btw, I use   auth、 storage 、 analytics、 dynamicLink、 message
