### ISSUE TITLE
No such module 'Firebase'

### ISSUE THREAD

**Issue by DKalachniuk** [firebase/firebase-ios-sdk#4777]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.16.0
  * Firebase Component: Analytics; Performance (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 6.2.2; 3.1.12
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem
I have a framework that uses Firebase. I can build this framework- everything is good. When I use my framework as a POD in a project, I can't compile it. The error says -> No such module 'Firebase'
If i comment out usage of firebase in MY framework and use it only in the project -> it is ok
#### Steps to reproduce:
1. Have a target that builds a framework. It should use Firebase
2. In other Target that is view-based app use target 1 as a pod. It should also use Firebase
3. Try to compile the view-based app
What happened? How can we make the problem occur?
No such module 'Firebase' error in my local framework

podfile:

```
source 'https://github.com/CocoaPods/Specs.git'
source 'ssh://git@bitbucket.*:7999/mobile/ios-*-specs.git'

platform :ios, '13.0'
inhibit_all_warnings!
use_frameworks!
abstract_target 'AbstractTarget' do
    pod 'Firebase/Analytics'
    pod 'Firebase/Performance'
    pod 'Firebase'

        target 'MyLocalFramework' do

	end

        target 'MyApp' do
        pod 'GoogleAnalytics', '3.17'
        pod 'Fabric'
        pod 'Crashlytics'
        end
end
```

So I can use Firebase in MyApp. I can even use it in MyLocalFramework but it compiles only if i choose this target. When I choose to run MyApp the error is appearing  No such module 'Firebase' (in MyLocalFramework)

**Comment by rizafran** [comment]
Seems related to this one #4769.

**Comment by morganchen12** [comment]
It sounds like you're trying to link Firebase into an app and a framework at the same time, and then include the framework into the main app. If you succeed with compilation, you'll likely run into duplicate class definitions at runtime. What you're trying to do is mostly unsupported but will work if you use static frameworks instead of dynamic frameworks.

To fix the compilation error, the you need to add `inherit! :search_paths` to the `MyApp` target in your Podfile.

**Comment by DKalachniuk** [comment]
> Seems related to this one #4769.

tried everything from that thread. didn't work




> It sounds like you're trying to link Firebase into an app and a framework at the same time, and then include the framework into the main app. If you succeed with compilation, you'll likely run into duplicate class definitions at runtime. What you're trying to do is mostly unsupported but will work if you use static frameworks instead of dynamic frameworks.
> 
> To fix the compilation error, the you need to add `inherit! :search_paths` to the `MyApp` target in your Podfile.

didn't work :( MyApp started to complain on other modules that it is using... The error is "can not find different classes from other modules" (I also have other pods declared in abstract target)

**Comment by morganchen12** [comment]
Unfortunately without manually poking at your project it will be difficult for us to debug build errors via comment thread, but here's more or less what your Podfile and Xcode project hierarchy need to achieve:

```
App
|  \
|    Framework
|  /
Firebase
```

Firebase must be linked into `Framework` and not `App`, but Firebase's headers must be visible to `App`. The most common way of achieving this in a Podfile is something like this:

```ruby
target 'Framework' do
  # pods

  target 'App' do
    inherit! :search_paths
    # pods

    target 'AppTests' do
      inherit! :search_paths
    end
  end
end
```
