### ISSUE TITLE
[FirebaseCrashlytics 4.0.0-beta.2] fails to compile as a cocoapods dependency

### ISSUE THREAD

**Issue by bi1zi1** [firebase/firebase-ios-sdk#4785]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1 (11C504)
  * Firebase SDK version: 6.16.0
  * Firebase Component: FirebaseCrashlytics
  * Component version: 4.0.0-beta.2
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

The project does not compile with the given Podfile configuration and when using FirebaseCrashlytics.
Error message: .../FIRCLSDataCollectionArbiter.m:23:9: 'FIRApp.h' file not found

![image](https://user-images.githubusercontent.com/13077009/73531207-3b1fce00-441a-11ea-9e92-eaf553a05d20.png)

#### Steps to reproduce:

- Create a new project in XCode.
- Add the Podfile contents.
- Initialize pods.
- Try to build the project (workspace).
- Build fails.

Changing `#import  "FIRApp.h"` to `#import <FirebaseCore/FIRApp.h>` inside `FIRCLSDataCollectionArbiter.m` solved the issue for me.

Sample project with the Pods installed:
[FirebasePodsBuildIssue.zip](https://github.com/firebase/firebase-ios-sdk/files/4138769/FirebasePodsBuildIssue.zip)

#### Relevant Code:

Podfile contents:

> use_frameworks!
> platform :ios, '9.0'
> 
> inhibit_all_warnings!
> 
> install! 'cocoapods',
>          :generate_multiple_pod_projects => true,
>          :incremental_installation => true
> 
> def mainPodPackage
> 	pod 'Firebase', '6.16.0'
>     pod 'FirebaseCrashlytics', '4.0.0-beta.2'
> end
> 
> target 'FirebasePodsBuildIssue' do
> 	mainPodPackage
> end

**Comment by samedson** [comment]
Hey thanks for the report @bi1zi1 - just reproduced this! Going to work on a fix.

**Comment by samedson** [comment]
@bi1zi1 - we just shipped a hotfix to FirebaseCrashlytics. If you update to `4.0.0-beta.3` the issue should be resolved
