### ISSUE TITLE
[Crashlytics] Not receiving crash reports

### ISSUE THREAD

**Issue by tspecht** [firebase/firebase-ios-sdk#4798]
### Step 1: Describe your environment

  * Xcode version: 11.2.1
  * Firebase SDK version: 6.16.0
  * Firebase Component: Crashlytics (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 4.0.0-beta1
  * Installation method: `CocoaPods`

### Step 2: Describe the problem

After upgrading to the new Firebase Crashlytics SDK, we are not receiving crash reports for either debug or release builds. We verified the installation & correct usage of the GoogleService-Info.plist. When forcing a crash locally using `fatalError`, on the next execution `Crashlytics.crashlytics().didCrashDuringPreviousExecution()` always returns `false`.

#### Steps to reproduce:

Force a simple crash using `fatalError`

#### Relevant Code:

in `didFinishLaunching`
```
print(Crashlytics.crashlytics().didCrashDuringPreviousExecution())
DispatchQueue.main.asyncAfter(deadline: .now() + 35) {
   fatalError()
 }
```

**Comment by tspecht** [comment]
I enabled debug logs and was also able to pull the following log and am receiving crash reports from debug builds. However, we are still missing our production data although we reuploaded our dSym files manually:

```
2020-02-02 10:57:03.861823-0500 Dopesmash[37287:3148758] [Firebase/Crashlytics] Version 4.0.0-beta.1
2020-02-02 10:57:04.063879-0500 Dopesmash[37287:3149022] [Firebase/Crashlytics] Packaged report with id '8d8c5a2203ec4e3e9fa624dcd483d9d6' for submission
```

**Comment by rizafran** [comment]
Hi @tspecht, thanks for reporting this issue. Can you confirm if you are receiving `[Crashlytics:Crash] report submission successful` in your logs? Also, are you seeing a "Missing dsYM" message in your Firebase Crashlytics dashboard? Make sure that you have followed all the steps [here](https://firebase.google.com/docs/crashlytics/get-started-new-sdk).

I'll try to replicate this on my end and I'll let you know with my findings.

**Comment by tspecht** [comment]
@rizafran I have not observed a log output stating anything about the actual submission besides the packaging mentioned above. All dSyms were uploaded, both manually and by hand just in case, still no change for over 48h. However, I'm now seeing the following error when presumably trying to submit the data after ugprading to `beta-3`

```
2020-02-03 08:10:10.521494-0500 MyApp[9414:3835384] 6.16.0 - [Firebase/Crashlytics][I-CLS000000] Failed to remove file /Users/myUser/Library/Developer/CoreSimulator/Devices/989DCD15-D852-4139-98CF-C1E55D904C67/data/Containers/Data/Application/C17F8BBD-05AC-489B-960E-094296068BEA/Library/Caches/com.crashlytics.data/com.mobilemotion.dubsmash/v4/reports/prepared/563CD1E6-0E42-4981-8CF5-EAD739865A37.multipartmime: Error Domain=NSCocoaErrorDomain Code=4 "“563CD1E6-0E42-4981-8CF5-EAD739865A37.multipartmime” couldn’t be removed." UserInfo={NSUserStringVariant=(
), NSFilePath=/Users/myUser/Library/Developer/CoreSimulator/Devices/989DCD15-D852-4139-98CF-C1E55D904C67/data/Containers/Data/Application/C17F8BBD-05AC-489B-960E-094296068BEA/Library/Caches/com.crashlytics.data/com.mobilemotion.dubsmash/v4/reports/prepared/563CD1E6-0E42-4981-8CF5-EAD739865A37.multipartmime, NSUnderlyingError=0x600001c7de30 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
2020-02-03 08:10:10.522247-0500 MyApp[9414:3835384] 6.16.0 - [Firebase/Crashlytics][I-CLS000000] Unable to remove packaged submission
```

**Comment by TKBurner** [comment]
The team is actively looking into this issue and we will follow up shortly :)

**Comment by jasonhu-g** [comment]
@tspecht - 

Taking a look at the backend logs for your report (8d8c5a2203ec4e3e9fa624dcd483d9d6), it looks like it was successfully processed. How long did you wait between triggering a crash and trying to view it on the dashboard? Depending how many crashes the backend is processing, it may take some time before crashes appear on the dashboard. 

May you go take a look at the dashboard again, update the time window and see if that crash now appears?

**Comment by tspecht** [comment]
@jasonhu-g thanks for checking in! I am able to see my debug logs on the dashboard, however none of my production ones are appearing. We just released an update containing a bump of the Firebase Crashlytics SDK to `beta-3` and are waiting for any reports to come in. Is there any way the firebase team could verify the proper processing of our production appliacation?

**Comment by jasonhu-g** [comment]
@tspecht - If you are able to share a report submission id from your production app, then we can do a quick search. If you see crashes from a build and they are not being displayed because of missing symbols (dsym), then it will show up in the dsym tab from the Crashlytics page. There were very minor changes between beta1->beta3.

**Comment by tspecht** [comment]
@jasonhu-g what would be your advise on best pulling this from a production build where `-FIRDebugEnabled` can not be utilized?

**Comment by jasonhu-g** [comment]
The log message for the report id will still be outputted without the FIRDebugEnabled flag. That implementation decision was made for helping debug potential missing crash reports like this.

**Comment by tspecht** [comment]
@jasonhu-g I was able to pull the package ID from the logs as you requested. The steps to obtain those were as follows (in order to ensure identical behavior as our app store version): 

0. Add a button to the app forcing a crash using `fatalError` 
1. Archive as release version and upload to TestFlight
2. Install from TestFlight
4. Connect device & Open in Console, put in filter for "Firebase"
3. Start the app and force the crash
5. Restart the app and observe logs

```
[Firebase/Crashlytics] Version 4.0.0-beta.3
[Firebase/Crashlytics] Packaged report with id '7d7ecfb6387d4b7ab22821ec76e9d831' for submission
```

**Comment by jasonhu-g** [comment]
@tspecht  - For the production crash, the backend is still missing symbols for the build. How are you getting the dsym for your production app? Did you take the dsym from the xcarchive that you uploaded to the AppStore?

**Comment by tspecht** [comment]
@jasonhu-g we tried both uploading from local as well as downloading it from AppstoreConnect which is what we did for Fabric successfully. After uploading to the UI, it shows as a successful upload, so unsure on why the crash reports are still not showing. Are there any limitations on the dSym support, maybe regarding bitcode or something similar?

<img width="950" alt="Screen Shot 2020-02-04 at 10 22 38" src="https://user-images.githubusercontent.com/603144/73758232-5f401f80-4738-11ea-9980-31799567fe04.png">

**Comment by jasonhu-g** [comment]
@tspecht - Thanks for sharing the information. 

Report 7d7ecfb6387d4b7ab22821ec76e9d831  is associated to the UUID DSYM that ends up 37DDC (which seems to have been uploaded ~5 hours ago). May you try triggering one more crash and see if the crash shows up? 

If that doesn't work, please upload the dsym with upload-symbols:
https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=ios&authuser=0

Uploading dSYMS from the console is being deprecated on March 1, 2020. It is being replaced with an uploader script. You can use the upload script as shown above.

**Comment by tspecht** [comment]
@jasonhu-g thanks, uploading via script magically made the logs appear, guess the console is just broken. FYI, the documentation still references the `Fabric` folder in the `Pods` directory, while the script is now located under `FirebaseAnalytics`

**Comment by morganchen12** [comment]
Thanks for flagging, I'll update the docs.

**Comment by morganchen12** [comment]
The up-to-date paths are in [this doc](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports-new-sdk?platform=ios), and not the one Jason linked.
