### ISSUE TITLE
Firebase iOS 6.16.0 manual linking missing symbol

### ISSUE THREAD

**Issue by nidegen** [firebase/firebase-ios-sdk#4800]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.16.0
  * Firebase Component: Analytics
  * Installation method:Zip file

#### Steps to reproduce:

- Manually install firebase from the zip.

- Build it.

Output:
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FIRHeartbeatInfo", referenced from:
      objc-class-ref in FirebaseInstallations(FIRInstallationsAPIService.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by rizafran** [comment]
Thanks for reporting the issue, @nidegen. I'll try to replicate this on my end and I'll update you with my findings.

It would also be great if you could share a sample project that will reproduce the issue.

**Comment by nidegen** [comment]
Yes I agree. 

Currently, I switched my setup to 6.14. As that works there without problems. This hints with a specific bug of 6.16, so I skipped building a sample project for now.

**Comment by maksymmalyhin** [comment]
@nidegen Could you please double check that you have `FirebaseCore.framework` version from 6.16.0 in your project? 
`FIRHeartbeatInfo` is a relatively new class but it was introduced in `FirebaseCore` before 6.14.0. The class was not used by Analytics or its dependencies before 6.15.0, that can explain why you don't have the issue on 6.14.0.

**Comment by nidegen** [comment]
I am pretty sure as i downloaded the entire zip, and didnt touch 6.14 until after, but If needed i can double check with a sample project. but probably not before this weekend

**Comment by nidegen** [comment]
I made an example repo, but hit the issue of #4819 on the way there. see https://github.com/nidegen/Sketcher/tree/firebase

**Comment by rizafran** [comment]
Hi @nidegen, I can't seem to find the page. Looks like the repo was set to private.

**Comment by nidegen** [comment]
oh, sorry I had assumed it was already public

**Comment by paulb777** [comment]
I'm having trouble reproducing
![Screen Shot 2020-02-11 at 2 47 33 PM](https://user-images.githubusercontent.com/73870/74286819-76a17e80-4cdd-11ea-9c3e-22dfebd37a7e.png)

**Comment by nidegen** [comment]
oh these are unused submodules. `git submodule update --init` or pull the newest commit, i removed the refs

**Comment by trr-amsiq** [comment]
I can reproduce with 6.17.0 as well

**Comment by paulb777** [comment]
@nidegen Thanks for the repro. 

After working around #4819, the app links successfully for me. I don't see the problem with `_OBJC_CLASS_$_FIRHeartbeatInfo`.

**Comment by nidegen** [comment]
yep, my repro case does fork after 4819 fix (while also linking to sqlite3). I'll doublecheck on the heartbeatinfo

**Comment by trr-amsiq** [comment]
I can confirm that adding `FirebaseInstallation.framework` and `PromiseObjC.framework` fixes the issue

**Comment by nidegen** [comment]
yep tried at 6.17 and it works fine. Didn't investigate what was the `missing link`

**Comment by nidegen** [comment]
it popped up again. maybe it just a caching issue, but clean build and rm DerivedData didn't solve. doesn't happen on the example project, so no need for reopening currently
