### ISSUE TITLE
Unable to make Dynamic Links feature work

### ISSUE THREAD

**Issue by iharandreyev** [firebase/firebase-ios-sdk#4803]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1 (11C504)
  * Firebase SDK version: 6.16.0
  * Firebase Component: Dynamic Links
  * Component version: 4.0.6
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

I've created a project in the Firebase console and set it up according to instructions.
Here are my [bundle ID, team ID and associated links feature enabled](https://pasteboard.co/IT06plW.png). One may see that I have exact same ids set up [in the project settings](https://pasteboard.co/IT07u4V.png). 

Then I've created URL prefix `sumo.page.link` and [tested it](https://pasteboard.co/IT08wbZ.png). Seems to work fine.

Then I've set up XCode project with [bundle id](https://pasteboard.co/IT09bAz.png), [domain](https://pasteboard.co/IT09nX3.png), [URL scheme](https://pasteboard.co/IT09AgQ.png) and other bare necessities.

Self-test [is passed successfully](https://pasteboard.co/IT09QsM.png). But I am [unable](https://pasteboard.co/IT0aJPd.jpg) to open the app by clicking `https://sumo.page.link/` (I use Notes app).

The [test project](https://gofile.io/?c=3qZJHx) is run on iPhone SE with iOS 13.3.

**Comment by morganchen12** [comment]
If you add `?d=1` to the end of your dynamic link, does it give you a more detailed explanation?

**Comment by iharandreyev** [comment]
@morganchen12 Nope, the [result is the same](https://pasteboard.co/IT5zYnC.jpg). I've also discovered a small [oddity](https://pasteboard.co/IT5Ahjb.png). Not sure if it's related to the issue though.

**Comment by iharandreyev** [comment]
For some reason the Associated Domain was configured only for release configuration. Therefore things didn't work in debug mode. Sorry for bothering you folks.
