### ISSUE TITLE
Firebase/Messaging Unable to Install for watchOS

### ISSUE THREAD

**Issue by jakeholland** [firebase/firebase-ios-sdk#4807]
### Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.16.0
  * Firebase Component: Messaging
  * Component version: 4.2.0
  * Installation method: `CocoaPods`

### Step 2: Describe the problem
It is my understanding that starting with [6.15.0](https://firebase.google.com/support/release-notes/ios#fcm), FCM supports watchOS. I have been trying to install that pod in my standalone watch app but I am running into problems immediately. Adding the pod to the podfile and running `pod install` leads to the following error:
```
[!] The platform of the target `Example WatchKit App Extension` (watchOS 6.0) is not compatible with `Firebase/Messaging (6.16.0)`, which does not support `watchOS`.
```

#### Steps to reproduce:

1. Create a project with a standalone watch app. 
2. Run `pod init`
3. Update the pod file to include `Firebase/Messaging` for the watch app extension
4. Run `pod install`

#### Relevant Code:

**Podfile**
```
inhibit_all_warnings!
use_frameworks!

target 'Example' do
  platform :ios, '12.0'
  pod 'Firebase/Messaging'
end

target 'Example WatchKit App Extension' do
  platform :watchos, '6.0'
  pod 'Firebase/Messaging'
end
```
**Example Project**
[Example.zip](https://github.com/firebase/firebase-ios-sdk/files/4150219/Example.zip)

**Comment by chliangGoogle** [comment]
@jakeholland  can you try pod FirebaseMessaging to see if it works for you?

@paulb777  I wonder if it's the subspec setting for 'pod Firebase/Messaging' not setup properly. But 'pod FirebaseMessaging' should work.

**Comment by jakeholland** [comment]
@chliangGoogle - Looks like that did the trick! Thank you 😊

**Comment by paulb777** [comment]
Yes the Firebase pod likely needs to be updated to accept watchos for the Messaging subspec

I'll reopen to track.
