### ISSUE TITLE
157239542: FR: Possibility to modify app preview page (Firebase Dynamic Links)

### ISSUE THREAD

**Issue by iharandreyev** [firebase/firebase-ios-sdk#4810]
### Feature proposal

* Firebase Component: Firebase Dynamic Links

When opening a dynamic link, the app preview page has `Save my place in the app...` checkbox pre-selected. If we'd like to pass some kind of bonus codes through the dynamic link, there's a slight possibility for security breach since the link is copied into the iOS pasteboard, and might be accessed by any other app through `paste` command.

Now, I'd like to either make this checkbox deselected by default, or be given an opportunity to remove the checkbox altogether with no copying to pasteboard happening. I do realize that `matchType` will most likely be `.weak`, but for some security-sensitive data I could live with that.

**Comment by rizafran** [comment]
Hi @iharandreyev, based on the [docs](https://firebase.google.com/docs/dynamic-links/link-previews#app_preview_pages), it seems that you can bypass the app preview page by specifying the dynamic link parameter `efr=1`. Note that without the app preview page, Dynamic Links can't be received as unique matches on iOS. In the Firebase console, you may also check the "Skip the app preview page" when creating a Dynamic Link (see attached image). Could you confirm if that fits well with your use case? 
<img width="1318" alt="Screen Shot 2021-03-19 at 12 16 45 AM" src="https://user-images.githubusercontent.com/56452638/111659739-706ac380-8848-11eb-9b8d-9f33fbc74dda.png">
