### ISSUE TITLE
FR: Include Google Tag Manager in Firebase framework

### ISSUE THREAD

**Issue by RobBernardini** [firebase/firebase-ios-sdk#4827]
### Feature proposal

* Firebase Component: Google Tag Manager

In our project we currently manually install Firebase frameworks as we normally use Carthage instead of CocoaPods. We were using an older version of Google Tag Manager and Google Analytics which we could manually download and install both frameworks but as we are now forced to upgrade to create a new container using Firebase Analytics we also need to upgrade to the more recent Google Tag Manager, the problem is that a standalone framework does not exist and the only way to obtain it is by downloading the framework using CocoaPods in another project and then extrapolating Google Tag Manager and its resources bundle and installing it in our actual project. I have followed the information as explained [here](https://medium.com/@okan.erdogan02/ios-firebase-analytics-gtm-implementation-using-carthage-9c5a62ef1b8c) but I am still receiving the following error and I am unable to resolve it.
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_GSDK_GTMStringEncoding", referenced from:
      objc-class-ref in GoogleTagManager(TAGJSExportedInstructions_152f65793e933650a0e71b0bce043c37.o)
  "_GSDK_NSClassFromString", referenced from:
      -[TAGJSExportedInstructions callCustomFunctionClassName:parameters:] in GoogleTagManager(TAGJSExportedInstructions_152f65793e933650a0e71b0bce043c37.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
It is of extreme importance to our company that we can use Google Tag Manager because we use it for important analytics data but we really cannot replace Carthage with CocoaPods for certain reasons. I hope that a standalone framework can be added to Firebase or that someone can help me install Google Tag Manager and its resources manually.

**Comment by paulb777** [comment]
Thanks for the feature request. We'll follow up with the Google Tag Manager on the feasibility.

In the meantime, you might get a bit further by including the binary from the GoogleUtilitiesLegacy CocoaPods - see https://github.com/CocoaPods/Specs/blob/master/Specs/9/5/6/GoogleTagManager/7.1.2/GoogleTagManager.podspec.json#L6.

**Comment by paulb777** [comment]
After talking to the Google Tag Manager, it's unlikely we'll do this integration.  

Regarding the specific issue, it looks like one of GTM dependencies might be missing. Perhaps GoogleSymbolUtilities?

**Comment by RobBernardini** [comment]
@paulb777 I have added the libraries like you mentioned but now I am getting this error. Am I missing another library? Since there will never be any standalone Tag Manager included in the Firebase framework hopefully someone can help me out.

<img width="275" alt="Screen Shot 2020-03-08 at 11 05 10 am" src="https://user-images.githubusercontent.com/10274232/76154290-0e07bf00-612e-11ea-9ce8-62a46fd10eb5.png">

**Comment by paulb777** [comment]
@RobBernardini Looks like missing symbols from the iOS AddressBook.framework. Add it to the `Link Binary with Libraries` Build Phase.

**Comment by RobBernardini** [comment]
Hi @paulb777 . I appreciate all your help with this! 

I still haven't found a solution but I believe that it may be due to our use of an older `GoogleAnayticsServices.a` library. I see that we also also have an `AdIdAccess.a` library and I believe that they are part of the legacy Tag Manager and Google Analytics frameworks. 

<img width="113" alt="Screen Shot 2020-03-10 at 9 39 51 am" src="https://user-images.githubusercontent.com/10274232/76265474-b0ec4480-62b8-11ea-8705-7735ec9d27db.png">

I am assuming that we should be using the newer `libGoogleAnalytics.a` as part of the new Tag Manager. What I would like to verify is that the `AdIdAccess` is not required by the new tag manager framework so that I can remove it. I think it keeps referencing the older Google Analytics Services library. 

Also, I tested updating the older library to the newer one and removing AdIdAccess to see if it built but for some reason it says "cannot find -lGoogleAnalytics". I found it strange that the file is named `libGoogleAnalytics.a` but the linker is looking for `lGoogleAnalytics.a`. Is there a mapping somewhere where it looks for a different name? I renamed it and then got another error but I found this strange.

**Comment by morganchen12** [comment]
I'm not sure about the requirements for the new library, but:

>Also, I tested updating the older library to the newer one and removing AdIdAccess to see if it built but for some reason it says "cannot find -lGoogleAnalytics". I found it strange that the file is named libGoogleAnalytics.a but the linker is looking for lGoogleAnalytics.a. Is there a mapping somewhere where it looks for a different name? I renamed it and then got another error but I found this strange.

This is likely just a stale linker flag somewhere in your build configuration. If you search your build files (and config files, if you're using any) for `-lGoogleAnalytics` you may be able to find the culprit.

**Comment by RobBernardini** [comment]
That's what I thought. I still haven't found it but I'll keep searching. Thanks!
