### ISSUE TITLE
`setScreenName:screenClass:` not setting screen name

### ISSUE THREAD

**Issue by nikitaame** [firebase/firebase-ios-sdk#4838]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: `11.3.1 (11C504)`
  * Firebase SDK version: `6.16.0`
  * Firebase Component: `Analytics`
  * Component version: `6.16.0`
  * Installation method: `CocoaPods`

### [REQUIRED] Step 3: Describe the problem

I am using SwiftUI. I am trying to set the screen name for Analytics but am seeing the following message:

```
[Firebase/Analytics][I-ACS031003] setScreenName:screenClass: must be called after a view controller has appeared
```

even though I am calling the function from the content body's `onAppear`. Is this wrong? There isn't much documentation for usage with SwiftUI.

#### Relevant Code:

```
struct Home: View {
  var body: some View {
    EmptyView()
      .onAppear { 
        Analytics.logEvent("screen_name", parameters: nil) 
      }
  }
}
```

**Comment by maksymmalyhin** [comment]
Internally tracked at b/149018279

**Comment by maksymmalyhin** [comment]
@nikitaame It looks like [UIHostingController](https://developer.apple.com/documentation/swiftui/uihostingcontroller) `viewDidAppear` method is called after [View.onAppear()](https://developer.apple.com/documentation/swiftui/view/3278614-onappear) and the current version of Firebase Analytics doesn't handle it correctly this case.

While we are working on a solution for this you may try a workaround like delaying the `setScreen` call in the `onAppear` method, e.g.
```
DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + DispatchTimeInterval.milliseconds(500)) {
          Analytics.setScreenName("screen_name", screenClass:"Home")
        }
```

**Comment by cschelly** [comment]
@maksymmalyhin This is still not working for me even after trying your suggested workaround. Anything else I can try?

![image](https://user-images.githubusercontent.com/12465747/79693688-05240600-8221-11ea-92b4-1b3012b87073.png)

Thanks

**Comment by allenktv** [comment]
Hi @cschelly, thanks for your report! This is something we are actively working on solving and we will update this issue once it is resolved!

**Comment by jgale** [comment]
Hi folks, just wanted to see if there was any update on this. I found that the workaround does actually work for me, so I'll use that for now, but it would be nice not to have to. e.g. in onAppear:

```swift
DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
  Analytics.setScreenName("todo_tab", screenClass: String(describing: type(of: self)))
}
```

**Comment by lmunck** [comment]
I'm also experiencing this issue and cannot get the work-around to work. I'm up to six seconds delay and still get the same message. I have added below to my root view, and have tested other Analytics.logEvent with success. It is is only below that fails:

`.onAppear {
            DispatchQueue.main.asyncAfter(deadline: .now() + 6) {
              Analytics.setScreenName("test", screenClass: String(describing: type(of: self)))
            }
        }`

Shouldn't it be possible to make a custom UIViewController representable to make this work or am I missing something?

**Comment by allenktv** [comment]
Hi @lmunck, we have released a new way to manually log screen view events and you no longer need to wait for a ViewController to log them. Please see the [blog post](https://firebase.googleblog.com/2020/08/google-analytics-manual-screen-view.html).
