### ISSUE TITLE
downloadurl not getting executed

### ISSUE THREAD

**Issue by harrymash2006** [firebase/firebase-ios-sdk#4839]
I am trying the following code

func downloadURL(_ url:String){
        let ref = Storage.storage().reference().child(url)
        ref.downloadURL { url, error in
          if let error = error {
            // Handle any errors
          } else {
            // Get the download URL for 'images/stars.jpg'
            print("url:::")
          }
        }
    }
    
    func uploadFile(fileURL:URL){
        
        ActivityIndicatorVC.sharedInstance.startIndicator()

    
        print("uploadfile::"+fileURL.absoluteString)
        let extensio = NSURL(fileURLWithPath: fileURL.absoluteString).pathExtension
        var storagePath = "files/"
        var sourceType = 4;
        let uti = UTTypeCreatePreferredIdentifierForTag(
        kUTTagClassFilenameExtension,
        extensio! as CFString,
        nil)
        
        if UTTypeConformsTo((uti?.takeRetainedValue())!, kUTTypeImage) {
            storagePath = "images/"
            sourceType = 3;
        }
        
        let storage = Storage.storage()
        let storageRef = storage.reference()
        let time = Int64(NSDate().timeIntervalSince1970*1000)
        let strTimeStamp: String = "\(time)"
        let pathStr = storagePath+strTimeStamp+"."+(extensio ?? "")
        print("pathstr::"+pathStr)
        
        let pathRef = storageRef.child(pathStr)
        let uploadTask = pathRef.putFile(from: fileURL, metadata: nil){ metadata, error in
            
        }

        
        uploadTask.observe(.success) { snapshot in
          // Upload completed successfully
            print("upload success:")
            uploadTask.removeAllObservers()
            ActivityIndicatorVC.sharedInstance.stopIndicator()
            self.downloadURL(pathStr)

            
        }
        
        uploadTask.observe(.failure) { snapshot in
              if let error = snapshot.error as? NSError {
              ActivityIndicatorVC.sharedInstance.stopIndicator()

              switch (StorageErrorCode(rawValue: error.code)!) {
              case .objectNotFound:
                self.showAlert(message: "file does not exist")
                break
              case .unauthorized:
                self.showAlert(message: "User doesn't have permission to access file")
                // User doesn't have permission to access file
                break
              case .cancelled:
                self.showAlert(message: "User canceled the upload")
                // User canceled the upload
                break

              /* ... */

              case .unknown:
                self.showAlert(message: "Unknown error occurred")
                // Unknown error occurred, inspect the server response
                break
              default:
                // A separate error occurred. This is a good place to retry the upload.
                break
              }
                uploadTask.removeAllObservers()

          }
        }
    }

Please help. Thanks in advance

**Comment by rizafran** [comment]
Thanks for filing a report, @harrymash2006. To have a better understanding of the issue, could you provide the following information:

- SDK version you're using (You may share your Podfile.lock file)
- Detailed steps to reproduce the issue
- Screenshot(s) of error encountered (if any)
- A sample project that I can run to reproduce the issue

**Comment by harrymash2006** [comment]
I am using iOS 12.0 and following is my Pod file

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'De Brand' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for De Brand

pod 'Alamofire'
pod 'SDWebImage'
pod 'IQKeyboardManagerSwift'
pod 'Tabman'
pod 'GrowingTextView'
pod 'LGSideMenuController'
pod 'AMScrollingNavbar'
pod 'SkyFloatingLabelTextField'
pod 'IQDropDownTextField'
pod "ImageSlideshow"
pod "ImageSlideshow/SDWebImage"
pod 'XLPagerTabStrip'
pod "ImageSlideshow/Kingfisher"
pod 'LUExpandableTableView'
pod ‘youtube-ios-player-helper’, ‘~> 0.1’
pod 'Firebase/Database'
pod 'NetworkEye'
pod 'UITextView+Placeholder'
pod 'AlamofireImage', '~> 3.3'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/DynamicLinks'
pod 'Firebase/Storage'

end

**Comment by rizafran** [comment]
Thanks for the infornation, @harrymash2006. However, it doesn't include the SDK versions. In order for us to identify what's causing the issue, please provide the information I asked from the previous comment.

**Comment by harrymash2006** [comment]
Firebase Core: 5.1.2
Firebase Storage: 3.0.1

**Comment by harrymash2006** [comment]
Firebase (5.7.0)
FirebaseAnalytics (5.1.1) 
FirebaseCore (5.1.2) 
FirebaseDatabase (5.0.2) 
FirebaseDynamicLinks (3.0.2) 
FirebaseInstanceID (3.2.1) 
FirebaseMessaging (3.1.1)
FirebaseStorage (3.0.1)

**Comment by rizafran** [comment]
@harrymash2006, looks like you're using an older version of Firebase SDK. Could you try to update to the latest version(see the release notes [here](https://firebase.google.com/support/release-notes/ios)) and see if the issue persists?
