### ISSUE TITLE
Update minimum supported iOS version to 10

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#4847]
We're planning to update the minimum supported ios version to 10 in the next Firebase major release. 

Also do a scrub to remove unnecessary pre-iOS 10 code like removing NSNotificationCenter observers in dealloc's. See cl/307613047.

```
- (void)dealloc {
  [[NSNotificationCenter defaultCenter] removeObserver:self];
}
```

Update the AdMob dependency in the Firebase pod past 7.63. See #6355

Please comment here if you have any question or concerns.

**Comment by lisindima** [comment]
When do you plan to release this update?

**Comment by paulb777** [comment]
@lisindima We don't announce release future dates, but historically our major release updates have happened annually around May.

**Comment by paulb777** [comment]
As you've probably guessed, it will be later this year ....

**Comment by paulb777** [comment]
Closing with merge onto firebase7-main branch. Will release with Firebase 7.0.0.
