### ISSUE TITLE
Realm crash after adding Firebase SDK

### ISSUE THREAD

**Issue by YanxiFeng** [firebase/firebase-ios-sdk#4850]
###  Describe your environment

  * Xcode version: 11.2
  * Firebase SDK version: 6.13
  * Firebase Component: Firebase/Analytics, Firebase/Performance
  * Component version: 6.13
  * Installation method: CocoaPods

###  Describe the problem
After adding Firebase, realm crash often.

#### Steps to reproduce:
```
0	libobjc.A.dylib	class_getSuperclass + 4
1	ChopeDashboard	RLMUtil.hpp line 72 RLMIsObjectSubclass + 72
2	ChopeDashboard	RLMSchema.mm line 105 RLMRegisterClassLocalNames(objc_class**, unsigned long) + 105
3	ChopeDashboard	memory line 2942 +[RLMSchema sharedSchema] + 2942
4	ChopeDashboard	RLMRealm.mm line 492 +[RLMRealm realmWithConfiguration:error:] + 492
5	ChopeDashboard	RLMRealm.mm line 190 +[RLMRealm defaultRealm] + 190
6	ChopeDashboard	RLMObject.mm line 141 +[RLMObject objectsWithPredicate:] + 141
```
#### Relevant Code:
Init Firebase in `AppDelegate`
```
[FIRApp configure];
```

**Comment by paulb777** [comment]
Two suggestions:
- Update to the latest Firebase version - currently 6.16.0
- Isolate which Firebase pod triggers the issue - does it still occur if you remove FirebasePerformance from the Podfile?

**Comment by morganchen12** [comment]
Related: https://github.com/realm/realm-cocoa/issues/5618, https://github.com/firebase/firebase-ios-sdk/issues/2376

**Comment by paulb777** [comment]
Based on those two issues, adding Performance tag.
