### ISSUE TITLE
nanopb error at Xcode 11.4 beta

### ISSUE THREAD

**Issue by nebiros** [firebase/firebase-ios-sdk#4855]
### Step 1: Describe your environment

  * Xcode version: 11.4 beta
  * Firebase SDK version: 6.16.0
  * Firebase Component: nanopb
  * Component version: 0.3.9011
  * Installation method: CocoaPods

#### Steps to reproduce:

It throws an error at Xcode 11.4 beta, here's the error:

```
ld: -sectalign and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together
```

**Comment by paulb777** [comment]
@nebiros Thanks for the report.  

I'm not able to reproduce in a sample app with `Version 11.4 beta (11N111s)`

Where does the `-sectalign` option get set?

**Comment by wilhuff** [comment]
This isn't specific to nanopb: https://twitter.com/search?q=sectalign. It seems like a bug in the Xcode release that sectalign is now on by default.

That discussion seems to indicate that the best workaround right now is to disable bitcode.

**Comment by RetepV** [comment]
FYI, I'm encountering the same problem.

**Comment by htjohn** [comment]
Encountering the same issue as well.

**Comment by paulb777** [comment]
Going to close since it seems to be an Xcode beta issue
