### ISSUE TITLE
I cannot get crash report from xcode 11.3.1

### ISSUE THREAD

**Issue by abhaytli** [firebase/firebase-ios-sdk#4861]
**Step 1: Describe your environment**
Xcode version: 11.3.1
Firebase SDK version: 6.14.0
Firebase Component: Crashlytics
Component version: 3.14.0
Installation method: Carthage
macOS: 10.15.3

**Step 2: Describe the problem**
i am using carthage to install all the framework, and initializing Firebase like below,
```
   if let filePath = Bundle.main.path(forResource: "GoogleService-Info", ofType: "plist"),
                let options = FirebaseOptions(contentsOfFile: filePath) {
                FirebaseApp.configure(options: options)
            } else {
                fatalError("GoogleService-Info-debug.plist is missing!")
            }
```
i did set ` dwarf-with-dsym ` on debug info format, please suggest what am i missing to get crash reports

**Comment by morganchen12** [comment]
@abhaytli it doesn't look like there's anything wrong with your code. Be aware that you're using two GoogleService-Info.plist file names in your initialization logic flow (`GoogleService-Info.plist` and `GoogleService-Info-debug.plist`), but this shouldn't affect crash reporting.

Can you share your Cartfile.resolved?

**Comment by matkuznik** [comment]
Hi all.

We have similar issue. Previously we have used the Fabric Crashlytics and in the last release of our app we have switched to the Firebase Crashlytics. Now we can not see the reports of the crashes. The Version of the Firebase SDK is 6.17.0. 
The interesting thing is when we tested, on the debug target of our app, the crashes were available in the Firebase Console. One of the differences between prod and stage is bitcode enabled on the production. The dSYMS files where uploaded manually via the Firebase Console. 
Other interesting think is when I builded and ran the product version locally, the crash also appeared.
I've double check the configuration and a proper GoogleService-Info.plist file is used.

Is this possible that the dSYMS are missing/invalid and this is the reason? The dSYMs tab on the Firebase Console doesn't show any missing files for this build.

**Comment by morganchen12** [comment]
@matkuznik can you [file a support ticket](https://firebase.google.com/support/troubleshooter/crashlytics/missing)? This way the support team will be able to look at your project info.

**Comment by TKBurner** [comment]
Agree with Morgan here. I think we are going to have better luck troubleshooting through support.

Thanks :)

**Comment by andreaslindahl** [comment]
I'm also having this problem. Recently switched from Fabric Crashlytics to Firebase Crashlytics and removed all references to Fabric in my project. No crashes, or logs, appear in the Firebase Console for my latests builds, using Firebase Crashlytics.

Using cocoapods, by the way.

**Comment by morganchen12** [comment]
Hey Andreas, please see [my other comment](https://github.com/firebase/firebase-ios-sdk/issues/4861#issuecomment-587139373). The support team will be able to better help you with this issue since they can look at your project directly.
