### ISSUE TITLE
Getting crash on UserContinuity

### ISSUE THREAD

**Issue by mBilal5674** [firebase/firebase-ios-sdk#4869]
<!-- DO NOT DELETE
validate_template=true
template_path=.github/ISSUE_TEMPLATE/bug_report.md
2 GoogleUtilities   0x7d2c (-0x104b5c000 + 4374019372)
3  UIKitCore         -[UIApplication activityContinuationManager:continueUserActivity:]
4  UIKitCore         -[UIActivityContinuationManager _continueUserActivity:]
5  UIKitCore         ___72-[UIActivityContinuationManager handleActivityContinuation:isSuspended:]_block_invoke_3
6  UIKitCore         ___74-[UIApplication activityContinuationManager:hideProgressUIWithCompletion:]_block_invoke
7  UIKitCore         -[_UIApplicationModalProgressController _callAndClearDismissalHandlerWasDismissedByUser:]
8  UIKitCore         -[_UIApplicationModalProgressController hideAfterMinimumUptimeWithDismissalHandler:]
9  UIKitCore         -[UIApplication activityContinuationManager:hideProgressUIWithCompletion:]
10 UIKitCore         -[UIActivityContinuationManager _endCurrentActivityContinuationWithCompletion:]
11 UIKitCore         ___72-[UIActivityContinuationManager handleActivityContinuation:isSuspended:]_block_invoke_2
12 libdispatch.dylib __dispatch_call_block_and_release
13 libdispatch.dylib __dispatch_client_callout
14 libdispatch.dylib __dispatch_main_queue_callback_4CF
15 CoreFoundation    ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
16 CoreFoundation    ___CFRunLoopRun
17 CoreFoundation    _CFRunLoopRunSpecific
18 GraphicsServices  _GSEventRunModal
19 UIKitCore         _UIApplicationMain
20 LunchON           _mh_execute_header (LunchON)
21 libdyld.dylib     _start

Thread 1
0  libsystem_kernel.dylib  ___semwait_signal
1  libsystem_c.dylib       _nanosleep
2  Foundation              +[NSThread sleepForTimeInterval:]
3  Foundation              ___NSOPERATION_IS_INVOKING_MAIN__
4  Foundation              -[NSOperation start]
5  Foundation              ___NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__
6  Foundation              ___NSOQSchedule_f
7  libdispatch.dylib       __dispatch_call_block_and_release
8  libdispatch.dylib       __dispatch_client_callout
9  libdispatch.dylib       __dispatch_continuation_pop
10 libdispatch.dylib       __dispatch_async_redirect_invoke
11 libdispatch.dylib       __dispatch_root_queue_drain
12 libdispatch.dylib       __dispatch_worker_thread2
13 libsystem_pthread.dylib __pthread_wqthread

Thread 2
0 libsystem_kernel.dylib  _semaphore_wait_trap
1 libdispatch.dylib       __dispatch_sema4_wait
2 libdispatch.dylib       __dispatch_semaphore_wait_slow
3 Branch                  BranchClassInitializeLog
4 libdispatch.dylib       __dispatch_call_block_and_release
5 libdispatch.dylib       __dispatch_client_callout
6 libdispatch.dylib       __dispatch_lane_serial_drain
7 libdispatch.dylib       __dispatch_lane_invoke
8 libdispatch.dylib       __dispatch_workloop_worker_thread
9 libsystem_pthread.dylib __pthread_wqthread

Thread 3
0 libsystem_kernel.dylib  ___workq_kernreturn
1 libsystem_pthread.dylib __pthread_wqthread

Thread 4
0  libsystem_kernel.dylib   ___ulock_wake
1  libsystem_platform.dylib __os_unfair_lock_unlock_slow
2  libsqlite3.dylib         _sqlite3_sourceid
3  libsqlite3.dylib         _sqlite3_sourceid
4  libsqlite3.dylib         _sqlite3_snprintf
5  libsqlite3.dylib         _sqlite3_vfs_find
6  libsqlite3.dylib         _sqlite3_open_v2
7  LunchON                  GMSx_AbslInternalSpinLockWake (LunchON)
8  libdispatch.dylib        __dispatch_call_block_and_release
9  libdispatch.dylib        __dispatch_client_callout
10 libdispatch.dylib        __dispatch_lane_serial_drain
11 libdispatch.dylib        __dispatch_lane_invoke
12 libdispatch.dylib        __dispatch_workloop_worker_thread
13 libsystem_pthread.dylib  __pthread_wqthread

Thread 5

Thread 6
0  libsystem_kernel.dylib  _fsync
1  libsqlite3.dylib        _sqlite3_free_table
2  libsqlite3.dylib        _sqlite3_free_table
3  libsqlite3.dylib        _sqlite3_value_text
4  libsqlite3.dylib        _sqlite3_finalize
5  libsqlite3.dylib        _sqlite3_step
6  libsqlite3.dylib        _sqlite3_step
7  libsqlite3.dylib        _sqlite3_exec
8  LunchON                 _mh_execute_header (LunchON)
9  LunchON                 _mh_execute_header (LunchON)
10 LunchON                 _mh_execute_header (LunchON)
11 LunchON                 _mh_execute_header (LunchON)
12 LunchON                 _mh_execute_header (LunchON)
13 LunchON                 _mh_execute_header (LunchON)
14 LunchON                 _mh_execute_header (LunchON)
15 libdispatch.dylib       __dispatch_client_callout
16 libdispatch.dylib       __dispatch_once_callout
17 LunchON                 _mh_execute_header (LunchON)
18 LunchON                 _mh_execute_header (LunchON)
19 LunchON                 _mh_execute_header (LunchON)
20 LunchON                 _mh_execute_header (LunchON)
21 libdispatch.dylib       __dispatch_call_block_and_release
22 libdispatch.dylib       __dispatch_client_callout
23 libdispatch.dylib       __dispatch_lane_serial_drain
24 libdispatch.dylib       __dispatch_lane_invoke
25 libdispatch.dylib       __dispatch_workloop_worker_thread
26 libsystem_pthread.dylib __pthread_wqthread

Thread 7

Thread 8
0  libsystem_kernel.dylib  _mach_msg_trap
1  libsystem_kernel.dylib  _mach_msg
2  CoreFoundation          ___CFRunLoopServiceMachPort
3  CoreFoundation          ___CFRunLoopRun
4  CoreFoundation          _CFRunLoopRunSpecific
5  Foundation              -[NSRunLoop(NSRunLoop) runMode:beforeDate:]
6  Foundation              -[NSRunLoop(NSRunLoop) runUntilDate:]
7  UIKitCore               -[UIEventFetcher threadMain]
8  Foundation              -[NSThread main]
9  Foundation              ___NSThread__start__
10 libsystem_pthread.dylib __pthread_start

Thread 9
0 libsystem_kernel.dylib  ___workq_kernreturn
1 libsystem_pthread.dylib __pthread_wqthread

Thread 10
0 libsystem_kernel.dylib  _mach_msg_trap
1 libsystem_kernel.dylib  _mach_msg
2 libsystem_kernel.dylib  _thread_suspend
3 Bugsnag                 ksmachexc_i_handleExceptions
4 libsystem_pthread.dylib __pthread_start

Thread 11

Thread 12

Thread 13
0 libsystem_kernel.dylib  ___workq_kernreturn
1 libsystem_pthread.dylib __pthread_wqthread

Thread 14

Thread 15

Thread 16
0 libsystem_kernel.dylib  _mach_msg_trap
1 libsystem_kernel.dylib  _mach_msg
2 CoreFoundation          ___CFRunLoopServiceMachPort
3 CoreFoundation          ___CFRunLoopRun
4 CoreFoundation          _CFRunLoopRunSpecific
5 CFNetwork               0x1836cc564 (-0x20144000 + 7038109028)
6 Foundation              -[NSThread main]
7 Foundation              ___NSThread__start__
8 libsystem_pthread.dylib __pthread_start

Thread 17
0 libsystem_kernel.dylib  ___psynch_cvwait
1 libsystem_pthread.dylib __pthread_cond_wait
2 libc++.1.dylib          std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >)
3 JavaScriptCore          std::__1::cv_status std::__1::condition_variable_any::wait_until<std::__1::unique_lock<bmalloc::Mutex>, std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::unique_lock<bmalloc::Mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&)
4 JavaScriptCore          bmalloc::Scavenger::threadRunLoop()
5 JavaScriptCore          bmalloc::Scavenger::threadEntryPoint(bmalloc::Scavenger*)
6 JavaScriptCore          void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(bmalloc::Scavenger*), bmalloc::Scavenger*> >(void*)
7 libsystem_pthread.dylib __pthread_start

**Comment by rizafran** [comment]
Hi @mBilal5674, we won't be able to identify the cause of the issue without enough information. Could you provide more details which are also included in the issue template:

- SDK versions used (Please share your Podfile / Podfile.lock)
- Screenshot or copy of the error encountered / error logs
- Detailed steps to reproduce the issue
- Sample project that I can run locally

**Comment by morganchen12** [comment]
AFAIK UserContinuity is not a symbol in any Firebase SDK. @mBilal5674 please add more information and we'll re-open this issue, or consider asking on StackOverflow.
