### ISSUE TITLE
VeraCode issue on CrashlyticsKit/Helpers/CLSAllocate.c

### ISSUE THREAD

**Issue by security-v** [firebase/firebase-ios-sdk#4870]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3
  * Firebase SDK version: 6.13.0
  * Firebase Component: Crashlytics(Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 3.14.0
  * Installation method: `CocoaPods ` 

#### Steps to reproduce:

VeraCode has found a low severity issues in CrashlyticsKit/Helpers/CLSAllocate.c, called **"Unchecked error condition "**. The issue states that return value from malloc() is not been checked before been used in subsequent call. 

#### Relevant Code:
<code>
Users/crashlytics/buildAgent/work/7e5c596e59839c6e/apple/CrashlyticsKit/CrashlyticsKit/Helpers/CLSAllocate.c [Path 1: CLSAllocatorSafeAllocateFromRegion, line 162 (1 step)] 
</code>

<code>
Users/crashlytics/buildAgent/work/7e5c596e59839c6e/apple/CrashlyticsKit/CrashlyticsKit/Helpers/CLSAllocate.c [Path 1: CLSAllocatorSafeAllocate, line 177 (1 step)] 
</code>

<code>
Users/crashlytics/buildAgent/work/7e5c596e59839c6e/apple/CrashlyticsKit/CrashlyticsKit/Helpers/CLSAllocate.c  [Path 1: CLSAllocatorSafeAllocate, line 182 (1 step)]
</code>

**Comment by jasonhu-g** [comment]
This issue has been fixed in:
https://github.com/firebase/firebase-ios-sdk/pull/4669
