### ISSUE TITLE
VeraCode issues on GDTCCTNanopbHelpers.m 

### ISSUE THREAD

**Issue by security-v** [firebase/firebase-ios-sdk#4871]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3
  * Firebase SDK version:  6.13.0
  * Firebase Component: GoogleDataTransportCCTSupport (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 1.2.1
  * Installation method: `CocoaPods ` 

#### Steps to reproduce:

VeraCode has found a low severity issues in GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m, called "Unchecked error condition ". The issue states that return value from malloc() is not been checked before been used in subsequent call.

#### Relevant Code:

<code>
  GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m [Path 1: GDTCCTEncodeData, line 41 (1 step)]
GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m [Path 1: GDTCCTConstructBatchedLogRequest, line 74 (1 step)]
GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m [Path 1: GDTCCTConstructLogRequest, line 104 (1 step)]
</code>

**Comment by morganchen12** [comment]
I'm pretty sure we just OOM crash in this scenario, which is a perfectly ok failure mode. @mikehaney24 I'll close this issue as won't fix, feel free to re-open if you find it actionable.

**Comment by mikehaney24** [comment]
I can address this easily.
