### ISSUE TITLE
VeraCode issue in CLSBetaUpdate.m (Information Exposure) 

### ISSUE THREAD

**Issue by security-v** [firebase/firebase-ios-sdk#4874]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3
  * Firebase SDK version: 6.13.0
  * Firebase Component:  Crashlytics (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 3.14.0
  * Installation method: `CocoaPods `

#### Steps to reproduce:

VeraCode has reported that application calls the NSURL.URLWithString:() function, which will result in data being transferred out of the application (via the network or another medium). This data contains sensitive information. %s

#### Relevant Code:

<code>
CrashlyticsKit/CrashlyticsKit/Beta/CLSBetaUpdate.m [Path 1: -[CLSBetaUpdate initWithDictionary:], line 39 (1 step)]
</code>

#
PS: I couldn't find affected file in your source base but anyway I raised an issue in this project based on folder name in build path.

**Comment by jasonhu-g** [comment]
This file has been removed in the new Firebase Crashlytics SDK.
