### ISSUE TITLE
Remote Config test regressions

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#4877]
#4844 introduced test flakes that cause the travis RemoteConfigCron tests too many retries and time out with the following occasional test failures:

    - NOTE  | [tvOS] xcodebuild:  /Users/travis/build/firebase/firebase-ios-sdk/FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m:305: error: -[RCNRemoteConfigTest testFetchAndActivate] : ((_configInstances[i].lastFetchStatus) equal to (FIRRemoteConfigFetchStatusSuccess)) failed: ("0") is not equal to ("1")
    - NOTE  | [tvOS] xcodebuild:  /Users/travis/build/firebase/firebase-ios-sdk/FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m:306: error: -[RCNRemoteConfigTest testFetchAndActivate] : ((error) == nil) failed: "Error Domain=com.google.remoteconfig.ErrorDomain Code=8003 "Failed to get InstanceID token. Error : Error Domain=com.firebase.installations Code=0 "The server responded with an error. HTTP response: <NSHTTPURLResponse: 0x600000633aa0> { URL: https://firebaseinstallations.googleapis.com/v1/projects/abc-xyz-123/installations/ } { status code: 400, headers {
    - NOTE  | [tvOS] xcodebuild:  /Users/travis/build/firebase/firebase-ios-sdk/FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m:312: error: -[RCNRemoteConfiFeb 10 05:35:10  AppHost-FirebaseRemoteConfig-Unit-Tests[11584] <Debug>: 6.16.0 - [Firebase/Installations][I-FIS001004] Unexpected API response: <NSHTTPURLResponse: 0x600000633aa0> { URL: https://firebaseinstallations.googleapis.com/v1/projects/abc-xyz-123/installations/ } { status code: 400, headers {
    - NOTE  | [tvOS] xcodebuild:  /Users/travis/build/firebase/firebase-ios-sdk/FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m:313: error: -[RCNRemoteConfigTest testFetchAndActivate] : ((_configInstances[i][key2].stringValue) equal to (value2)) failed: ("") is not equal to ("value2-2")
    - NOTE  | [tvOS] xcodebuild:  /Users/travis/build/firebase/firebase-ios-sdk/FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m:320: error: -[RCNRemoteConfigTest testFetchAndActivate] : ((status) equal to (FIRRemoteConfigFetchAndActivateStatusSuccessFetchedFromRemote)) failed: ("2") is not equal to ("0") - Callback of first successful config fetchAndActivate status must equal to FIRRemoteConfigFetchAndStatusSuccessFromRemote.
    - NOTE  | [tvOS] xcodebuild:  /Users/travis/build/firebase/firebase-ios-sdk/FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m:324: error: -[RCNRemoteConfigTest testFetchAndActivate] : ((_configInstances[i].lastFetchTime.timeIntervalSince1970) greater than (0)) failed: ("0") is not greater than ("0") - last fetch time interval should be set.

It's failed every night since the PR has merged. For example, see https://travis-ci.org/firebase/firebase-ios-sdk/jobs/648244386

**Comment by dmandar** [comment]
https://stackoverflow.com/questions/53261197/how-to-partial-mock-objects-of-the-same-class-twice-in-ocmock-3-4-2

**Comment by dmandar** [comment]
SHould be addressed for now with a workaround.
