### ISSUE TITLE
Crash in GDTCORClock.m 

### ISSUE THREAD

**Issue by mohammedshahid** [firebase/firebase-ios-sdk#4883]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3
  * Firebase SDK version: 6.16.0
  * Firebase Component: RemoteConfig
  * Component version: 6.16.0
  * Installation method: `CocoaPods`

#### Steps to reproduce:

Crash on iOS App launch with Firebase pods installed in the iOS app. 

Crash happens in all most all OS versions and devices.

EXCEPTION - SIGSEGV

#### Relevant Code:

We have got crash reports , could not reproduce it on code.

New relic Crash report: 

```
// TODO(you): code here to reproduce the problem

Crash, GDTCORClock.m line 86 in [GDTCORClock init]

```

**Comment by morganchen12** [comment]
Please share the full stack trace of the crash.

**Comment by mohammedshahid** [comment]
[Cleartrip-iOS-crashreport-02-11-2020_0639+0530.crash.zip](https://github.com/firebase/firebase-ios-sdk/files/4184474/Cleartrip-iOS-crashreport-02-11-2020_0639%2B0530.crash.zip)

**Comment by morganchen12** [comment]
Here's the thread of interest: 

```
Thread 13 name:
Thread 13 Crashed:
0   libobjc.A.dylib                	 0x00000001b51d2088 objc_msgSend (libobjc.A.dylib)
1   CoreFoundation                 	 0x00000001b5387684 -[__NSDictionaryM objectForKey:] (CoreFoundation)
2   hookkeyboard.dylib             	 0x0000000106029c70 0x106000000 + 171120
3   hookkeyboard.dylib             	 0x000000010600de30 0x106000000 + 56880
4   CoreFoundation                 	 0x00000001b54c9b4c CFTimeZoneCopySystem (CoreFoundation)
5   Cleartrip                      	 0x0000000102f6552c -[GDTCORClock init] (GDTCORClock.m:86)
6   Cleartrip                      	 0x0000000102f6557c +[GDTCORClock snapshot] (GDTCORClock.m:94)
7   Cleartrip                      	 0x0000000102f655a0 +[GDTCORClock clockSnapshotInTheFuture:] (GDTCORClock.m:99)
8   Cleartrip                      	 0x0000000102f6bc4c -[GDTCORUploadPackage initWithTarget:] (GDTCORUploadPackage.m:43)
9   Cleartrip                      	 0x0000000102f6d334 -[GDTCCTPrioritizer uploadPackageWithConditions:] (GDTCCTPrioritizer.m:61)
10  Cleartrip                      	 0x0000000102f6b218 __52-[GDTCORUploadCoordinator uploadTargets:conditions:]_block_invoke (GDTCORUploadCoordinator.m:118)
11  libdispatch.dylib              	 0x00000001b517a610 _dispatch_call_block_and_release (libdispatch.dylib)
12  libdispatch.dylib              	 0x00000001b517b184 _dispatch_client_callout (libdispatch.dylib)
13  libdispatch.dylib              	 0x00000001b5127404 _dispatch_lane_serial_drain$VARIANT$mp (libdispatch.dylib)
14  libdispatch.dylib              	 0x00000001b5127df8 _dispatch_lane_invoke$VARIANT$mp (libdispatch.dylib)
15  libdispatch.dylib              	 0x00000001b5131314 _dispatch_workloop_worker_thread (libdispatch.dylib)
16  libsystem_pthread.dylib        	 0x00000001b51cab88 _pthread_wqthread (libsystem_pthread.dylib)
17  libsystem_pthread.dylib        	 0x00000001b51cd760 start_wqthread (libsystem_pthread.dylib)
```

[Here](https://github.com/firebase/firebase-ios-sdk/blob/18e2721c1dbb1fc33812c82e4a79da1344d18f54/GoogleDataTransport/GDTCORLibrary/GDTCORClock.m#L79) is the init method that supposedly is causing the crash. It doesn't contain anything immediately suspicious.

It looks like there's two symbols that were not properly symbolicated that may not be part of your app's code, originating from `hookkeyboard.dylib`.

```
2   hookkeyboard.dylib             	 0x0000000106029c70 0x106000000 + 171120
3   hookkeyboard.dylib             	 0x000000010600de30 0x106000000 + 56880
```

Is this app running on a jailbroken device?

**Comment by mohammedshahid** [comment]
Oh , yeah. It looks like. Thanks for the bringing to this attention. 
I guess our crash reports are specific to Jailbroken devices only. 
Will close the thread. 

Thanks for helping on this :)

**Comment by morganchen12** [comment]
No problem!
