### ISSUE TITLE
dyld: Library not loaded: @rpath/FBLPromises.framework/FBLPromises

### ISSUE THREAD

**Issue by Vladbruno** [firebase/firebase-ios-sdk#4889]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.17
  * Firebase Component: Auth, Core, Database, Firestore, Crashlytics
  * Component version: _____
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

My project build with no errors but when I start app on iPhone (13.3.1) I have error:

dyld: Library not loaded: @rpath/FBLPromises.framework/FBLPromises
  Referenced from: /private/var/containers/Bundle/Application/076940F6-97CC-4755-995C-026834FC0065/Help Driver.app/Help Driver
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/076940F6-97CC-4755-995C-026834FC0065/Help Driver.app/Frameworks/FBLPromises.framework/FBLPromises: code signature invalid for '/private/var/containers/Bundle/Application/076940F6-97CC-4755-995C-026834FC0065/Help Driver.app/Frameworks/FBLPromises.framework/FBLPromises'

	/private/var/containers/Bundle/Application/076940F6-97CC-4755-995C-026834FC0065/Help Driver.app/Frameworks/FBLPromises.framework/FBLPromises: stat() failed with errno=25
	/private/var/containers/Bundle/Application/076940F6-97CC-4755-995C-026834FC0065/Help Driver.app/Frameworks/FBLPromises.framework/FBLPromises: code signature invalid for '/private/var/containers/Bundle/Application/076940F6-97CC-4755-995C-026834FC0065/Help Driver.app/Frameworks/FBLPromises.framework/FBLPromises'

	/private/var/containers/Bundle/Application/076940F6-97CC-4755-995C-026834FC0065/Help Driver.app/Frameworks/FBLPromises.framework/FBLPromises: stat() failed with errno=1
	/private/var/containers/Bundle/Application/076940F6-97CC-4755-995C-026834FC0065/Help Driver.app/Frameworks/FBLPromises.framework/FBLPromises: code signature invalid for '/private/var/containers/Bundle/Application/076940F6-97CC-4755-995C-026834FC0065/Help Driver.app/Frameworks/FBLPromises.framework/FBLPromises'

	/private/var/containers/Bundle/Application/076940F6-97CC-4755-995C-026834FC0065/Help Driver.app/Frameworks/FBLPromises.framework/FBLPromises: stat() failed with errno=1
(lldb) 

I tried to change _use_frameworks!_ to  _use_modular_headers!_ in podfile but firebase not works.
Anyone know how to fix this issue?

**Comment by rizafran** [comment]
Thanks for the report, @Vladbruno. Looks like Apple made something on iOS 13.3.1. Your error seems related to this [Apple developer forum](https://forums.developer.apple.com/thread/128435). This issue also happens to other frameworks.

After updating your Podfile, could you try to do a pod update, clean, run, and see if the issue persists?

I'll also try this on my end and I'll let you know of my findings.

**Comment by rizafran** [comment]
Hi @Vladbruno, I tried to replicate the issue but I can't seem to get the same error. Can you share your Podfile so I can test with the same content on my end?

**Comment by Vladbruno** [comment]
@rizafran Hi! As I understood this issue appears only on free accounts. I also tried to run on simulator and everything works fine on it.

> After updating your Podfile, could you try to do a pod update, clean, run, and see if the issue persists?

Yes, issue still persist. 
I attached podfile.

[Podfile.zip](https://github.com/firebase/firebase-ios-sdk/files/4193075/Podfile.zip)

**Comment by morganchen12** [comment]
In the past when this issue has come up it's usually code signing / cache related. Can you try (in any order):

- Deleting derived data
- Using a different cert and provisioning profile to sign your app when running on device
- Restarting your computer

**Comment by Vladbruno** [comment]
Looks like whe only way to avoid error on free account is use ios 13.3, because even in iOS 13.4 beta apple didn't fix it.

**Comment by paulb777** [comment]
I'm going to close since this is an iOS 13.3.1 issue with multiple discussions and workarounds available on stackoverflow.

The best workaround might be to use all static frameworks via a new CocoaPods 1.9.0 feature:

`use_frameworks! :linkage => :static`
