### ISSUE TITLE
Remove InAppMessagingDisplay subspec from Firebase pod

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#4900]
The FirebaseInAppMessagingDisplay pod was merged into the FirebaseInAppMessaging pod, but we're keeping the Firebase pod subspec around to help with transitioning.

Remove at next major breaking version.

**Comment by prakhar1989** [comment]
t

**Comment by prakhar1989** [comment]
app

**Comment by paulb777** [comment]
Marking as fixed by #6438. It will land in master with Firebase 7.
