### ISSUE TITLE
Batch Write after creating document automatically deleting created document

### ISSUE THREAD

**Issue by otymartin** [firebase/firebase-ios-sdk#4902]
@paulb777 @wilhuff @ryanwilson 

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: __11.3.1___
  * Firebase SDK version: __1.10.2___
  * Firebase Component: __Firestore___ )
  * Component version: _____
  * Installation method: `CocoaPods 

### [REQUIRED] Step 2: Describe the problem

When I call `setData` to create a document, I noticed that it's created and deleted at the same time. I can see it get created in my database for a split second before turning red and getting deleted. On my client I get a callback in my listener first saying it was added locally then saying it was modified/removed remotely on server. I have no code deleting anything in my firebase database anywhere in my app.

I noticed that this problem only exists if I add a completion handler to my `setData` call. Without it, the object is created as expected. Also if I do add a completion handler, it works as long as I have no code in the completion handler 

### Update
I think it might be a problem with a batch write I'm performing immediately after creating my document.

1. I create a chatRoom using `setData`
2. I perform a batchWrite adding a`Message` document in a subcollection of the chatRoom, I also update the charmRoom object's fields - updatedAt.
3. When I perform the batchWrite immediately after creating the chatRoom, the chatRoom is deleted from the database.

Why?

### Update 2
I performed the entire operation `setData` to create ChatRoom + `batchWrite` to create `Message` in sub collection + update `ChatRoom` document as a single batchWrite operation and that appears fine. I still don't understand why doing it the way I had originally should cause my document to automatically get deleted on the database.

Worth a look for the engineering team.

**Comment by wu-hui** [comment]
Hi @otymartin 

Thanks for reporting this issue! I could not reproduce the issue however, is it possible to provide a minimum reproduction of the issue. Some code snippets would be really helpful.

**Comment by otymartin** [comment]
Hi @wu-hui 

This is basically a recreation of my implementation. it would work. I have a listener listening for all chatRooms created/updated e.t.c. However, by the time that listener call's back with the object, it's been removed so when trying to decode the document data in my native swift `ChatRoom` object, the decoder would fail saying something like no key found for "status" with "Int value". Stuff like that implying the object just doesn't exist.

I would also observe the chatroom get created in the database and instantly get deleted. The message wouldn't get created at all.

```swift
open class FirebaseClient {
    
    var settings: FirestoreSettings {
        let settings = FirestoreSettings()
        settings.isPersistenceEnabled = true
        return settings
    }
     
    var db: Firestore {
        let db = Firestore.firestore()
        db.settings = settings
        return db
    }
    
    func addChatRoom() {
        db.collection("chatRoom").document("room101").setData(["status": 0, "createdAt": FieldValue.serverTimestamp(), "updatedAt" : FieldValue.serverTimestamp()]) { [weak self] (error) in
            if let error = error {
                print(error)
            } else {
                let batch = self?.db.batch()
                let messageRef = self?.db.collection("chatRoom").document("room101").collection("messages").document("message1")
                batch?.setData(["senderId": "user101", "receiverId": "user102", "text": "hello world", "createdAt": FieldValue.serverTimestamp()], forDocument: messageRef!)
                let chatRoomRef = self?.db.collection("chatRoom").document("room101")
                batch?.setData(["updatedAt": FieldValue.serverTimestamp(), "status": 1], forDocument: chatRoomRef!)
                batch?.commit(completion: { (error) in
                    if let error = error {
                        print(error)
                    }
                })
            }
        }
    }
}
```

**Comment by otymartin** [comment]
@wu-hui 

So I found the problem and it was half my fault - The `setData` call in my `batchWrite` is technically supposed to update my `chatRoom` document instead without `merge = true` it was technically deleting it. I should be using `updateData` instead which I'm now and it works but I'm still confused why `setData` should totally delete the object and not just `overwrite` as the documentation states here  unless overrite means something else 

`If the document does not exist, it will be created. If the document does exist, its contents will be overwritten with the newly provided data, unless you specify that the data should be merged into the existing document, as follows:  - [LINK](https://firebase.google.com/docs/firestore/manage-data/add-data)`

```swift
         let chatRoomRef = self?.db.collection("chatRoom").document("room101")
                
                batch?.setData(["updatedAt": FieldValue.serverTimestamp(),
                                "status": 1], forDocument: chatRoomRef!)
```

**Comment by wu-hui** [comment]
Hmm, I still cannot reproduce the problem. 

What I see that `chatRoomRef` is set correctly to be 

``` JSON
{updateAt: <expected timestamp>, status: 1}
```

after the batch commits, it is not deleted with `setData` even without `merge`.

Something is not right here, at this point I'd have to ask you for a full reproduction before I can proceed, can you setup an XCode project with your minimal repo code, and maybe share via github or any other means you find convenient? 

Thanks.

**Comment by otymartin** [comment]
Will so and post link to recreation.
