### ISSUE TITLE
Veracode scan found CWE ID 331 and 201 in Firestore and Auth clients

### ISSUE THREAD

**Issue by psimonazzi** [firebase/firebase-ios-sdk#4904]
We are using the Firestore library in an environment that requires static security scans. The scan tool (VeraCode) found vulnerability CWE 331 (Insufficient Entropy) in:
`Firebase/Auth/Source/Utilities/FIRAuthWebUtils.m`
`Firestore/core/src/firebase/firestore/util/secure_random_arc4random.cc`
VeraCode support says it is most probably related to the use of not completely random generators (arc4random).

And CWE 201 (Information Exposure Through Sent Data) in:
`Firebase/Auth/Source/Backend/RPC/FIRSecureTokenRequest.m` method `requestURL`

Since these could be security flaws and can block adoption of the library in regulated environments, please consider fixing.

Alternatively, if these use cases do not result in a security flaw, if you could provide a clarification on the intended usage of the random generator (for 331) and the url builder (for 201), it may be enough to conclude that it is acceptable for this use case or it is a false positive.

  * Firebase Component: Firestore
  * Installation method: CocoaPods

**Comment by wilhuff** [comment]
Veracode is wrong in this case. On Apple platforms, `arc4random` is a high quality source of random numbers and is recommended. Note that this does not actually use the RC4 cipher anymore.

From the man page:
> The original version of this random number generator used the RC4 (also known as ARC4) algorithm.  In OS X 10.12 it was replaced with the NIST-approved AES cipher, and it may be replaced again in the future as cryptographic techniques advance.

Other platforms have also migrated away from actually using RC4: https://security.stackexchange.com/a/172905
