### ISSUE TITLE
FirebaseCoreDiagnostic.framework is a not a valid framework bundle.

### ISSUE THREAD

**Issue by tmspzz** [firebase/firebase-ios-sdk#4917]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 10.2
  * Firebase SDK version: 6.9.0
  * Firebase Component: FirebaseCoreDiagnostic
  * Component version: N/A
  * Installation method: `Carthage`

#### Steps to reproduce:

Binary distribution with carthage is not working. The framework bundle is missing it's Info.plist

#### Relevant Code:

<img width="315" alt="Screenshot 2020-02-17 at 23 01 38" src="https://user-images.githubusercontent.com/196761/74688945-82a7a780-51d9-11ea-9411-fc005f513aeb.png">

**Comment by paulb777** [comment]
I see that the Info.plist is missing, but our tests are still passing without it.  What issue are you seeing?

Did you see the instruction about  not adding any of the Firebase frameworks to the Carthage build phase at https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md?

**Comment by tmspzz** [comment]
@patm1987 Thanks for the quick response. You're definitely right, this doesn't happen on the current carthage release.

I have already added a workaround to the upcoming `xcframework` support branch. However the workaround is speculative as carthage will try to read the macho filetype of `FirebaseCoreDiagnostic` and default to `.framework` on success.

The issue is that there no good way for carthage to tell what kind of bundle it's dealing with if there is no `Info.plist`.

Adding the `.plist` would make distributing Firebase via carthage more resilient.

**Comment by paulb777** [comment]
@tmpspzz Point taken.  FirebaseCoreDiagnostic should be consistent with the other frameworks and have an Info.plist. We'll investigate. Thanks!

**Comment by paulb777** [comment]
There's a logic issue in the code:

Info.plist is added at https://github.com/firebase/firebase-ios-sdk/blob/master/ZipBuilder/Sources/ZipBuilder/CarthageUtils.swift#L74

but then the CoreDiagnostics framework is overridden below https://github.com/firebase/firebase-ios-sdk/blob/master/ZipBuilder/Sources/ZipBuilder/CarthageUtils.swift#L97

**Comment by DevAndArtist** [comment]
Just run into the similar issue. I was trying if I can drop pods in our project and use `Crashlytics/Analytics` trough Carthage until we can use SPM. Cocoapods give me too many headaches.

**Comment by paulb777** [comment]
@DevAndArtist While it's clear there's a consistency problem, we haven't seen the issue prevent anything from working.  How is it not working for you?

**Comment by DevAndArtist** [comment]
@paulb777 when I try running the project in the simulator I get an error prompt from Xcode 11.3.1 before it can launch the app that this particular framework is missing the `Info.plist` file. It compiles, but I can't run the application if I use this setup.

**Comment by paulb777** [comment]
@DevAndArtist Thanks. We'll take a look. It might be something with the recent Xcode version.  In the meantime a workaround might be to exclude FirebaseCoreDiagnostic.framework.

**Comment by paulb777** [comment]
Fixed and will be available in the upcoming 6.21.0 release.
