### ISSUE TITLE
Firebase with CocoaPods' generate_multiple_pod_projects option does not work on Case Sensitive FS

### ISSUE THREAD

**Issue by sinoru** [firebase/firebase-ios-sdk#4925]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Xcode 11.3.1
  * Firebase SDK version: 5.17.0
  * Firebase Component: Analytics, DynamicLinks, RemoteConfig
  * Component version: _____
  * Installation method: CocoaPods

#### Steps to reproduce:

1. Add generate_multiple_pod_projects option on Podfile
2. Trying to build with Firebase

Error occured by [importing protobuf in ABTesting](https://github.com/firebase/firebase-ios-sdk/blob/3b0ed0ee4af4e47712fe759feaec1343c08d1e2e/FirebaseABTesting/Sources/Protos/developers/mobile/abt/proto/ExperimentPayload.pbobjc.h)

Which CocoaPods produces protobuf as `protobuf` but ABTesting try to import `Protobuf` module.

**Comment by rizafran** [comment]
Hi @sinoru, thanks for reporting the issue. Can you share a copy or screenshot of the error you're encountering? You may also consider updating your SDK version to the [latest one](https://firebase.google.com/support/release-notes/ios#version_6170_-_february_11_2020) and see if the issue persists.

**Comment by paulb777** [comment]
This is https://github.com/protocolbuffers/protobuf/issues/6803. The fix has been merged to master and is planned to be available when Protobuf 3.12.0 releases. 

In the meantime, see the workarounds discussed in that issue.

**Comment by sinoru** [comment]
I never think about protobuf itself had issue. Thanks to let me know it :)
