### ISSUE TITLE
CocoaPods could not find compatible versions for pod "Firebase/Crashlytics"

### ISSUE THREAD

**Issue by atereshkov** [firebase/firebase-ios-sdk#4927]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.2.1
  * Firebase SDK version: IDK
  * Firebase Component: Firestore, Core, Storage, Auth, FirebaseMessaging
  * Component version: '~> 6.7.0'
  * Installation method: `CocoaPods`

#### Steps to reproduce:

Add to Podfile (according to the docs):

```
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
```

**run pod repo update**
**run pod install**

**Output error:**

[!] CocoaPods could not find compatible versions for pod "Firebase/Crashlytics":
  In Podfile:
    Firebase/Crashlytics

None of your spec sources contain a spec satisfying the dependency: `Firebase/Crashlytics`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**I have ran pod repo update, also tried pod install --repo-update but no luck.**

Full Podfile Firebase pods:

```
  pod 'Firebase/Firestore', '~> 6.7.0'
  pod 'Firebase/Core', '~> 6.7.0'
  pod 'Firebase/Storage', '~> 6.7.0'
  pod 'FirebaseMessaging', '~> 4.1'

  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
```

**Comment by atereshkov** [comment]
Ok I was able to solve it by using following set of dependencies:

```
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
```

**Comment by rizafran** [comment]
Hi @atereshkov, I'm glad to hear that the issue has been resolved. Feel free to comment here if you'll still encounter an issue so we can reopen it and continue on investigating the issue.
