### ISSUE TITLE
[Firebase Database] Crash in RealtimeDatabase

### ISSUE THREAD

**Issue by RajeshBudhiraja** [firebase/firebase-ios-sdk#4928]
###  Step 1: Describe your environment

  * Xcode version: 11.1
  * Firebase SDK version: 6.17.0
  * Firebase Component: Database
  * Component version: 6.1.4
  * Installation method: CocoaPods

###  Step 2: Describe the problem
I am getting this crash with given exception:

Error initializing persistence: Error Domain=APLevelDBErrorDomain Code=0 "IO error: /var/mobile/Containers/Data/Application/119026DD-314C-487C-8B0F-05534DC57594/Documents/firebase/Consult/company/server_data/MANIFEST-000001: Operation not permitted" UserInfo={NSLocalizedDescription=IO error: /var/mobile/Containers/Data/Application/119026DD-314C-487C-8B0F-05534DC57594/Documents/firebase/Consult/company/server_data/MANIFEST-000001: Operation not permitted}

#### Steps to reproduce:
Not able to reproduce it.

What happened? How can we make the problem occur?
It's IO error. As discussed in: https://github.com/firebase/firebase-ios-sdk/issues/4493

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:
- (void)saveUserOverwrite:(id<FNode>)node
                   atPath:(FPath *)path
                  writeId:(NSUInteger)writeId {
    NSDictionary *write = @{
        kFUserWriteId : @(writeId),
        kFUserWritePath : [path toStringWithTrailingSlash],
        kFUserWriteOverwrite : [node valForExport:YES]
    };
    NSError *error = nil;
    NSData *data = [NSJSONSerialization dataWithJSONObject:write
                                                   options:0
                                                     error:&error];
    NSAssert(data, @"Failed to serialize user overwrite: %@, (Error: %@)",
             write, error);
    [self.writesDB setData:data forKey:writeRecordKey(writeId)];
}

```
Not able to reproduce it
```

**Comment by rizafran** [comment]
Hi @RajeshBudhiraja, this is similar to #4493. Feel free to contribute any significant info that might help to investigate the issue on that thread.
