### ISSUE TITLE
Silent Push should not show title if app is in background or application is killed by user.

### ISSUE THREAD

**Issue by pritikum1994** [firebase/firebase-ios-sdk#4942]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.13.0
  * Firebase Component: Messaging
  * Component version:  4.1.9
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem
When silent push notification is received, notification title is shown even is `content_available = true` is set. Ideally it should not show the notification.

One other issue we are facing is if we don't set `notification` and `title` key in the payload. Notification is not received on iPhone.

#### Relevant Code:
this is below json sent to https://fcm.googleapis.com/fcm/send .
if we dont send `notification` dict, we does not receive any push notification.
As per the messaging docs https://firebase.google.com/docs/cloud-messaging/http-server-ref , 'notification' is optional. but in our case, we don't receive any push if we don't sent 'notification' object?
{ 
	"notification": 
	{
               "title": "test"
	},
	"content_available": true,
        "priority":"high",
	"to" : "et-5ne9wY3o:APA91..."
 }
 
We have tested on iOS 12 and 13.

Note: when app is running, silent push works fine.

**Comment by morganchen12** [comment]
It looks like you're describing a system behavior on iOS and somehow your silent push is not being sent as a silent push. Can you try sending via APNs and including the `content-available` key?

**Comment by chliangGoogle** [comment]
If you sent silent push notification, "notification" section should NOT be set. 
If app is killed by users, Apple system might not be able to delivery the notification. https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application
If app is in background, you should be able to receive the notification.
