### ISSUE TITLE
For observer Event Value Changed, does the data of entire returned snapshot contribute to Real time database billing?

### ISSUE THREAD

**Issue by coolcool1994** [firebase/firebase-ios-sdk#4943]
1. When I have a user node:

userId:
____name: coolcool
____phoneNumber: 1231231234
____money: 10000
____otherData1: adsfnsaklfnaksdjn
____otherData2: asdfasd;lfjkads
________otherData2SubField: asdfasdfasdf

2. and I set up observer event FIRDataEventTypeValue for the userId node

[[baseRef child:userId]observeEventType:FIRDataEventTypeValue withBlock:^(FIRDataSnapshot * _Nonnull snapshot) {
 }]

3. If money field gets updated and the entire userId is returned as snapshot in the observeEvent function above, does clients download the entire userId including all subNodes or just download the updated money field and append to the rest of the local data (such as name, phone number etc.)? I want to know this because I am trying to optimize costs in Real time Database, so if observeEvent cause the entire node to be redownloaded including the subnodes that did not change, I would want to then set up 5 separate observeEvent for the 5 subfields in the example above, instead of setting one observeEvent for the userId node. I am trying to reduce the GB downloaded to reduce the bill.

**Comment by rizafran** [comment]
Hi @coolcool1994, though I'm not an expert on this issue, I would like to share this [documentation](https://firebase.google.com/docs/database/usage/billing#optimize_usage) on how to optimize database usage.

**Comment by coolcool1994** [comment]
Hi, I read the documentation multiple times, but the answer is not there. Could we wait for someone who has the answer before closing?

**Comment by morganchen12** [comment]
@coolcool1994 yes, RTDB will download the entire subnode, so downloading userId will fetch name, phoneNumber, and all the other fields (and their children).

**Comment by coolcool1994** [comment]
Wow. So if I were to set up observer to every field of userId instead of userId it self, would it reduce the GB downloaded for same amount of data changed, right? For example, in the above example, I should set up the observer so like:

[[[baseRef child:userId] child: name] observeEventType:FIRDataEventTypeValue withBlock:^(FIRDataSnapshot * _Nonnull snapshot) {
}]
[[[baseRef child:userId] child: phoneNumber] observeEventType:FIRDataEventTypeValue withBlock:^(FIRDataSnapshot * _Nonnull snapshot) {
}]
[[[baseRef child:userId] child: money] observeEventType:FIRDataEventTypeValue withBlock:^(FIRDataSnapshot * _Nonnull snapshot) {
}]
[[[baseRef child:userId] child: ____otherData2] observeEventType:FIRDataEventTypeValue withBlock:^(FIRDataSnapshot * _Nonnull snapshot) {
}]

Would this cause there to be more total GB download because of perhaps the protocol overhead? Setting observeEvent for every leaf of the Json tree seems like arduous take, but I can do it if it can reduce costs.

**Comment by morganchen12** [comment]
If you set up an observer for every field of a node you would end up downloading almost exactly the same amount of data. You can reduce the amount of data you download by structuring your data in RTDB to be less nested and then downloading only the data you need for a particular use case.

See [this document] for more details.

**Comment by coolcool1994** [comment]
Thank you for the details. Just to check one last thing: when you call set up childChanged observer/listener does RTDB download the entire parent node or just that child? For example, in the above example, if I set childChanged to the ref pointing to userId, and the value of name changes, would RTDB download just the value of name or the entire userId node?

**Comment by morganchen12** [comment]
It downloads the entire child node, but not the parent.

**Comment by morganchen12** [comment]
Closing this issue since that's all of the questions--let me know if you have any other questions and I'll re-open the issue.
