### ISSUE TITLE
FR: InAppMessaging Doesn't show localised message in iOS

### ISSUE THREAD

**Issue by srini2dl** [firebase/firebase-ios-sdk#4952]
I am using the FirebaseInAppMessaging (0.17.0)
the InAppMessagingDisplay is showing but the localized test is not shown instead of default text show up.

I try to debug in the FIRIAMFetchResponseParser.m file, I am able to see the localized text inside a dictionary but while paring the message body is only initialized to 
`body = modalNode[@"body"][@"text"];` and it's not taking the  text from `modalNode[@"body"][@"localizations"]`

![Screenshot 2020-02-21 at 4 31 30 PM](https://user-images.githubusercontent.com/7899221/75042774-a44dab00-54c7-11ea-8608-36a10c315d65.png)

**Comment by christibbs** [comment]
@srini2dl Looking into this currently, localization should be working on iOS.

**Comment by christibbs** [comment]
This issue will be fixed in an upcoming in-app messaging release. Will close when code is complete.

**Comment by christibbs** [comment]
Update: this will be fixed by a server-side change that won't require an update to the in-app messaging SDK. I'll close this when the server-side change is fully rolled out.

**Comment by christibbs** [comment]
This has been fixed on the server.
