### ISSUE TITLE
Getting rejected on iOS App Store due to non-public api

### ISSUE THREAD

**Issue by christopherspence** [firebase/firebase-ios-sdk#4971]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11
  * Firebase SDK version: 6.5.1
  * Firebase Component: Analytics (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 6.2.1 (xam ver)
  * Installation method: Xamarin SDK  (select one)

### [REQUIRED] Step 2: Describe the problem

I've embedded the Firebase iOS SDK in my Xamarin app, and I'm getting the following rejection notice from the App Store

`ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/FirebaseCoreDiagnostics.framework/FirebaseCoreDiagnostics: initWithFileName:. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/`

#### Steps to reproduce:

Run the following 
`nm -Umo path/to/GoogleUtilities.framework/GoogleUtilities | grep initWithFileName
GoogleUtilities: 0000000000004c8f (__TEXT,__text) non-external -[GULHeartbeatDateStorage initWithFileName:]`

#### Relevant Code:

Thanks in advance

PS: For reference, I filed a bug on the Xamarin repo for Firebase https://github.com/xamarin/GoogleApisForiOSComponents/issues/374

**Comment by morganchen12** [comment]
You should appeal this rejection via the email in Apple's response. The method referenced is a Firebase method (defined in the Firebase SDK), and not part of any private Apple API. Also, that selector name is generic enough to be in several non-Firebase APIs.
