### ISSUE TITLE
FR: Update Carthage support to latest Firebase SDK version

### ISSUE THREAD

**Issue by rus64** [firebase/firebase-ios-sdk#4977]
### Feature proposal

When including the FirebaseAnalytics framework binary in a project on Xcode >= 11.3 I get the following error:

```
*** Downloading binary-only framework FirebaseAnalyticsBinary at "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
Incompatible Swift version - framework was built with 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9) and the local version is 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15).
```

Suggesting that the framework is built with an earlier version of swift than the one shipped with the latest version of Xcode (11.3.1).

It looks like the latest release of the Firebase SDK is `6.18.0` but the last version supported with Carthage installation is `6.9.0`. Please consider updating Carthage support.

**Comment by paulb777** [comment]
Carthage is available for up to `6.17.0`. `6.18.0` should be available soon.  Try `carthage update`.

The other error is strange since there should be no Swift in our Carthage distribution.

**Comment by rus64** [comment]
> The other error is strange since there should be no Swift in our Carthage distribution.
I think it may have been a Carthage specific error when bootstrapping dependencies. (Using the binary file without Carthage was fine).

> Carthage is available for up to 6.17.0
Ah, great thanks. Is there somewhere I can follow releases with Carthage support?

**Comment by paulb777** [comment]
They're typically available without a day of the release showing up at https://github.com/firebase/firebase-ios-sdk/releases

**Comment by rus64** [comment]
Thanks for your help @paulb777!
