### ISSUE TITLE
Firebase dynamic links diagnosticString ERROR: UIApplication delegate %@ does not implements selector "

### ISSUE THREAD

**Issue by jerrypm** [firebase/firebase-ios-sdk#4986]
**Describe environment**

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.18.0
  * Firebase Component: Dynamic link 
  * Component version: 4.0.7
  * Installation method: `CocoaPods 

 **Describe the problem**
- I found an error in firebase dynamic link

 **Steps to reproduce:**
- After installing pod build Xcode, build not failed but in pod file "FIRDynamicLinks.m" I found some error 
- I try to running a project It is succeeded. Just error in pod dynamic link

```
[diagnosticString appendFormat:@"ERROR: UIApplication delegate %@ does not implements selector "
                                   @"%@. FDL depends on this implementation to retrieve pending "
                                   @"dynamic link.\n",
                                   applicationDelegate,
                                   NSStringFromSelector(@selector(application:openURL:options:))];
```

<img width="1096" alt="Screen Shot 2020-02-27 at 10 46 17" src="https://user-images.githubusercontent.com/15967964/75410766-7e088f00-594f-11ea-97bd-7487bff9d8dd.png">

**Comment by rizafran** [comment]
Hi @jerrypm, I can't seem to replicate this issue using [iOS quickstart](https://github.com/firebase/quickstart-ios/tree/master/dynamiclinks). Is it possible for you to try using our quickstart and see if the issue is reproducible?
