### ISSUE TITLE
Unable to receive FCM while ios app is in background or suspended state using Messaging.messaging().shouldEstablishDirectChannel = true & if I don't use this , unable to receive message in foreground too.

### ISSUE THREAD

**Issue by ShreeSoftech-Bhuj** [firebase/firebase-ios-sdk#4996]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.18.0
  * Firebase Component: Messaging 
  * Installation method: `CocoaPods` 

#### 
AppDelegate.swift

import UIKit
import CoreData
import GoogleSignIn
import Firebase
import UserNotifications
import FirebaseInstanceID
import FirebaseMessaging
import FBSDKCoreKit
import GoogleMobileAds
import Firebase

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate,GIDSignInDelegate ,UNUserNotificationCenterDelegate, MessagingDelegate {
    
    var window: UIWindow?
    var backgroundTask: UIBackgroundTaskIdentifier?
    let varSys = SystemConfig()
    let gcmMessageIDKey = "gcm.message_id"
    var imgURL = URL(string: "")
    var isImgAttached = false
    var subtitle : String = ""
    var title : String = ""
    var body : String = ""
    var type : String = ""
    var category : [String] = []
    
       func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        
        //firebase configuration
        GADMobileAds.sharedInstance().start(completionHandler: nil)
        FirebaseApp.configure()
        Messaging.messaging().delegate = self
        GIDSignIn.sharedInstance().clientID = FirebaseApp.app()?.options.clientID
        ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)
                
        //check app is log in or not if not than navigate to login view controller
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        if UserDefaults.standard.bool(forKey: "isLogedin") {
            // if app is loged in then navigate to menuview controller
            self.window = UIWindow(frame: UIScreen.main.bounds)
            let initialViewController = storyboard.instantiateViewController(withIdentifier: "ViewController")
            // navigationController
            self.window?.rootViewController = initialViewController
            self.window?.makeKeyAndVisible()
        }else{
            // if app is not loged in than navigate to loginview controller
            self.window = UIWindow(frame: UIScreen.main.bounds)
            let initialViewController = storyboard.instantiateViewController(withIdentifier: "LoginView")
            //let initialViewController = storyboard.instantiateViewController(withIdentifier: "SignUpView")//for testing only
            self.window?.rootViewController = initialViewController
            self.window?.makeKeyAndVisible()
        }
        
        if #available(iOS 10.0, *) {
          // For iOS 10 display notification (sent via APNS)
          UNUserNotificationCenter.current().delegate = self
          let authOptions: UNAuthorizationOptions = [.alert, .badge, .sound]
          UNUserNotificationCenter.current().requestAuthorization(
            options: authOptions,
            completionHandler: {_, _ in })
        } else {
          let settings: UIUserNotificationSettings =
          UIUserNotificationSettings(types: [.alert, .badge, .sound], categories: nil)
          application.registerUserNotificationSettings(settings)
        }
        application.registerForRemoteNotifications()
        
        if let userInfo = launchOptions?[UIApplicationLaunchOptionsKey.remoteNotification] {
            NSLog("[RemoteNotification] didFinishLaunchingWithOptions : \(userInfo)")
            //TODO: Handle background notification
        }
        //set badge
        if Apps.badgeCount > 0 {
             application.applicationIconBadgeNumber = Apps.badgeCount
        }else{ //clear badge
            application.applicationIconBadgeNumber = 0
        }
       // UserDefaults.standard.synchronize()
       Messaging.messaging().shouldEstablishDirectChannel = true
              
        let token = Messaging.messaging().fcmToken ?? "none"
        Apps.FCM_ID = token
                
        //to get system configurations parameters as per requirement
       varSys.ConfigureSystem()
       varSys.getNotifications()

        return true
    }
    //to preview notification in foreground
    func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
        print(Apps.badgeCount)
        completionHandler([.alert,.badge,.sound])
    }
    
    //func called when user tap on notification
    func userNotificationCenter(_ center: UNUserNotificationCenter,didReceive response: UNNotificationResponse,withCompletionHandler completionHandler: @escaping () -> Void) {
        let userInfo = response.notification.request.content.userInfo
        //deduct 1 from badgeCount As user opens notification
        if Apps.badgeCount > 0 {
             Apps.badgeCount -= 1
             UserDefaults.standard.set(Apps.badgeCount, forKey: "badgeCount")
        }
         actionAccordingToData()
        print(" user info - \(userInfo)")
        completionHandler()
    }
    private func application(application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: NSError) {
            // The token is not currently available.
        print("Remote notification support is unavailable due to error: \(error.localizedDescription)")
    }
    func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any],fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        
        Messaging.messaging().appDidReceiveMessage(userInfo)
        switch application.applicationState {

         case .inactive:
             print("Inactive")
             //Show the view with the content of the push
             completionHandler(.newData)

         case .background:
             print("Background")
             //Refresh the local model
             completionHandler(.newData)

         case .active:
             print("Active")
             //Show an in-app banner
             completionHandler(.newData)
         }

        print("USER INFO ",userInfo)
        completionHandler(UIBackgroundFetchResult.newData)
    }
    private func application(application: UIApplication,didRegisterForRemoteNotificationsWithDeviceToken deviceToken: NSData) {
        Messaging.messaging().apnsToken = deviceToken as Data
        print("token \(deviceToken)")
    }
    func messaging(_ messaging: Messaging, didRefreshRegistrationToken fcmToken: String) {
      print(fcmToken)
    }
    func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String) {
      print("Firebase registration token: \(fcmToken)")
      
      let dataDict:[String: String] = ["token": fcmToken]
      NotificationCenter.default.post(name: Notification.Name("FCMToken"), object: nil, userInfo: dataDict)
        //send token to application server.
         Apps.FCM_ID = fcmToken
         varSys.updtFCMToServer()
    }
    func messaging(_ messaging: Messaging, didReceive remoteMessage: MessagingRemoteMessage) {
        print("Received data message: \(remoteMessage.appData)")
               
        if (remoteMessage.appData["notification"] as? [String:Any]) != nil { //cloud message - firebase
            print(remoteMessage.appData["notification"]!)
            let notif = remoteMessage.appData["notification"] //receive from Firebase
            guard let DATA = notif as? [String:Any] else{
                               return
                           }
             title = DATA["title"]  as! String
            guard let s_title = DATA["subtitle"] else {
                return
            }
             subtitle = s_title as! String
             body = DATA["body"]  as! String
            showNotification(title,body) //showNotification(title,body)
            
        }else if (remoteMessage.appData["data"] as? [String:Any]) != nil {
            print("data of type ANY - \(remoteMessage.appData["data"] ?? "")")
        }else if (remoteMessage.appData["data"]) != nil { //app message check
            let notif = remoteMessage.appData["data"] //receive from API - Server
            print(notif!)
            let str : String = remoteMessage.appData["data"] as! String
            //fragmentRemoteData(str)
            fragmentTestData(str) //just for testing @ https://demo.androidhive.info/firebase/notifications/
            if  isImgAttached == true {
                DispatchQueue.main.asyncAfter(deadline: .now() + 7.0, execute: {
                    self.showNotificationWithAttachment(self.title,self.body,self.imgURL!) //showNotification(title,body,img)
                })
            }else{
                showNotification(title,body)
            }
        }else{
               print("There is No Pending messages / Notifications !!")
        }
    }
    
   // Google Sign In
   func sign(_ signIn: GIDSignIn!, didSignInFor user: GIDGoogleUser!, withError error: Error!) {
       
   }

    func applicationWillResignActive(_ application: UIApplication) {
        
        print("called resignActive")
        // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when the user quits the application and it begins the transition to the background state.
        // Use this method to pause ongoing tasks, disable timers, and invalidate graphics rendering callbacks. Games should use this method to pause the game.
    }
    
    func applicationDidEnterBackground(_ application: UIApplication) {
         print("@ background")
          // call function when app is gone to background to quit battle
         NotificationCenter.default.post(name: Notification.Name("QuitBattle"), object: nil)
    }
    
    func applicationWillEnterForeground(_ application: UIApplication) {
         print("back again")
        
        //call function when app is live again to check opponent again
        NotificationCenter.default.post(name: Notification.Name("CheckBattle"), object: nil)
    }
    
    func applicationDidBecomeActive(_ application: UIApplication) {
        // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
    }
    
    func applicationWillTerminate(_ application: UIApplication) {
        // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
        // Saves changes in the application's managed object context before the application terminates.
        self.saveContext()
        application.applicationIconBadgeNumber = Apps.badgeCount
    }

**Comment by morganchen12** [comment]
Are you able to receive APNs messages (without FCM)?

**Comment by chliangGoogle** [comment]
Can you try adding "content_available" in your payload to it can deliver in apns?

**Comment by ShreeSoftech-Bhuj** [comment]
> Are you able to receive APNs messages (without FCM)?

No

**Comment by ShreeSoftech-Bhuj** [comment]
@chliangGoogle  I have tested adding content_available in my payload but there is no effect.

**Comment by ShreeSoftech-Bhuj** [comment]
& if i remove Messaging.messaging().shouldEstablishDirectChannel = true
I am unable to receive firebase cloud messages even when app is In foreground state.

**Comment by morganchen12** [comment]
If you're unable to receive messages through APNs without FCM, then FCM won't work either since FCM depends on APNs. Please make sure you've setup APNs correctly.

**Comment by ShreeSoftech-Bhuj** [comment]
@morganchen12 
I have added APNs Authentication Key in Firebase project & checked App ID & other associated certificates as well if APN might not configured well then how can I be able to receive FCM while app is in foreground?

**Comment by chliangGoogle** [comment]
can you show us how you send your notification? e.g. which sender API  you use and what the payload looks like.

**Comment by ShreeSoftech-Bhuj** [comment]
I am sending from Firebase Cloud Messaging & response is -> [AnyHashable("notification"): {
    body = "notification message";
    e = 1;
    image = "https://www.arenaflowers.co.in/blog/wp-content/uploads/2017/09/Summer_Flowers_Lotus.jpg";
    tag = "campaign_collapse_key_1331110581228237463";
    title = "notification title";
}, AnyHashable("collapse_key"): online.quiz, AnyHashable("from"): 814090722059]
func messaging(_ messaging: Messaging, didReceive **remoteMessage**: MessagingRemoteMessage)

**Comment by ShreeSoftech-Bhuj** [comment]
In updated PODs i.e. **Firebase 6.18.0** 
**shouldEstablishDirectChannel** is deprecated & 
**'appData'** of remoteMessage.appData used in func messaging(_ messaging: Messaging, didReceive remoteMessage: MessagingRemoteMessage) is also deprecated.
then what should we use to receive message / response from firebase or API servers?

**Comment by chliangGoogle** [comment]
from the notification, it seems like you are sending display notification, which doesn't use direct channel at all. Enable direct channel will only consume your phone's battery for no reason.

you should stop using direct channel and use Apple's API to handle message response since you are using APNS channel to display visible notifications.

Here's the documentation where you can handle received message using APNS: https://firebase.google.com/docs/cloud-messaging/ios/receive

**Comment by ShreeSoftech-Bhuj** [comment]
@chliangGoogle 
Thanks for guidance 
but I have already followed  https://firebase.google.com/docs/cloud-messaging/ios/receive
some of it's functions are deprecated.
 just willPresent notification (works with foreground messages only) & didReceive withCompletionHandler function works only
didReceiveRemoteNotification & didReceiveRemoteNotification fetchCompletionHandler completionHandler both are never called in my specifications -> Firebase  6.18.0 & FirebaseMessaging 4.3.0 with Xcode Version 11.3.1 (11C504) & testing on iOS 13.3.1
 I am just not able to receive messages even in Foreground if I remove direct channel.
As I receive firebase cloud messages and pass remoteMessage to local notifications to display alert to users.

**Comment by chliangGoogle** [comment]
Let's clarify:
Are you 
A: sending display notification directly from your backend? Or 
B: sending data messages to device and device schedule local notification to display to users?

**Comment by ShreeSoftech-Bhuj** [comment]
As I am not having any function to receive remote notification directly for now. so, I am using messaging to receive message & I am scheduling local notification to display that received message to end users.

**Comment by morganchen12** [comment]
Hey @ShreeSoftech-Bhuj, as mentioned earlier, the only way to receive messages in the background is via APNs, since the direct channel is not available when the app is suspended. If your app is unable to receive APNs messages, then FCM will not work in the background because FCM depends on APNs to deliver background messages.

This also means that in order to receive background messages you will need to implement the iOS notification handlers, since those methods will be called instead of the messaging delegate method.

There are various resources online for sending APNs messages directly, for example [this blog post](https://industrial-binaries.co/send-push-notification-from-terminal/).

**Comment by ShreeSoftech-Bhuj** [comment]
Hi @morganchen12 ,

**Comment by morganchen12** [comment]
Happy to help! Let us know if you have any more questions.

**Comment by ShreeSoftech-Bhuj** [comment]
Thanks for Support !
