### ISSUE TITLE
Crashlytics: I do not get crash reports from users

### ISSUE THREAD

**Issue by Elshad** [firebase/firebase-ios-sdk#4997]
When i compile app with release config i get crash reports from my phone, but when i release app, there are not any crash reports from users which use my app. They inform me, but i cannot see any crash report

**Comment by morganchen12** [comment]
Please fill out the issue template.

**Comment by zebganzo** [comment]
Any news about this? We are experiencing the same since when we changed to the new version of the SDK.

**Comment by morganchen12** [comment]
@zebganzo this type of issue is best suited for [Firebase support](https://firebase.google.com/support), since they can look at your project and better diagnose why crashes aren't being displayed. Please report the issue there instead of here.

**Comment by Elshad** [comment]
@zebganzo if you upload dSYMs' from firebase dashboard then problem was there. I started upload with upload script and everything now ok.
Run the script directly from your terminal:
`/path/to/pods/directory/FirebaseCrashlytics/upload-symbols -gsp /path/to/GoogleService-Info.plist -p ios /path/to/dSYMs`

**Comment by zebganzo** [comment]
Thanks @Elshad
