### ISSUE TITLE
Crashed: com.google.fira.worker EXC_BAD_ACCESS KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by MIyulong** [firebase/firebase-ios-sdk#4998]
this crash reported from production on Crashlytics in the last 7 days for iOS 13.0.0 version
and then i check issue with #4038, my projecte installed nanopb version with 0.3.9011, but I still got this crash

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.12.0
  * Firebase Component:  Core,  Crashlytics
  * Component version: 6.12.0
  * Installation method: CocoaPods

#### Steps to reproduce:

What happened? How can we make the problem occur?
![image](https://user-images.githubusercontent.com/8175565/75648366-d8c12400-5c8a-11ea-884a-e0aa448c4966.png)

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
#8. Crashed: com.google.fira.worker
0x19e3b0fc0 objc_msgSend + 32
0x1014cd9e4 __42-[APMMeasurement writeEventOnWorkerQueue:]_block_invoke.1283 + 5076612
0x1014f7500 -[APMSqliteStore performTransaction:] + 5247392
0x1014cc5b4 -[APMMeasurement writeEventOnWorkerQueue:] + 5071444
0x1014cbb30 -[APMMeasurement handleEventOnWorkerQueue:] + 5068752
0x1014e0bf4 __51-[APMScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke + 5154964
0x19e340b7c _dispatch_call_block_and_release + 32
0x19e341fd8 _dispatch_client_callout + 20
0x19e348450 _dispatch_lane_serial_drain + 568
x19e348e7c _dispatch_lane_invoke + 368
0x19e351f20 _dispatch_workloop_worker_thread + 580
0x19e3a76d0 _pthread_wqthread + 280
0x19e3ad9e8 start_wqthread + 8

--

#0. com.apple.main-thread
0  libsystem_malloc.dylib         0x19e382598 small_free_list_remove_ptr_no_clear + 492
1  libsystem_malloc.dylib         0x19e3839f8 free_small + 896
2  libsystem_malloc.dylib         0x19e387640 nanov2_free_definite_size + 128
3  libsystem_malloc.dylib         0x19e38e6a0 default_zone_free_definite_size + 84
4  libsystem_malloc.dylib         0x19e38c194 free + 592
```

**Comment by morganchen12** [comment]
Can you try updating to 6.18.0 and seeing if the issue still occurs?

**Comment by MIyulong** [comment]
> Can you try updating to 6.18.0 and seeing if the issue still occurs?

Next production version we will update to 6.18.0, and keep seeing..., at now debug version doesn't occurs this bug with 6.18.0

**Comment by morganchen12** [comment]
Thanks, please keep this issue updated after releasing with the new Firebase version.
