### ISSUE TITLE
Dynamic links generated using the rest api endpoint stopped working

### ISSUE THREAD

**Issue by adkaushik** [firebase/firebase-ios-sdk#5000]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.2.1
  * Firebase SDK version: -
```ruby
Firebase/DynamicLinks (6.13.0):
    - Firebase/CoreOnly
    - FirebaseDynamicLinks (~> 4.0.5)
```
  * Firebase Component: `Dynamiclinks`
  * Component version: _____
  * Installation method: `CocoaPods`

### [REQUIRED] Step 2: Describe the problem

The dynamic links created using the rest end point open the iOS app but don't get resolved into respective deeplink urls.

Using this guide for generating dynamic links using rest endpoint:
reference: https://firebase.google.com/docs/reference/dynamic-links/link-shortener
```
POST https://firebasedynamiclinks.googleapis.com/v1/shortLinks?key=${key}
{
      dynamicLinkInfo: {
        domainUriPrefix: 'domain',
        link: url,
        androidInfo: {
          androidPackageName: 'android'
        },
        iosInfo: {
          iosBundleId: 'ios',
          iosAppStoreId: 'id'
        }
      },
      suffix: {
        option: 'SHORT'
      }
    }
```
After debugging the code inside FIRDynamicLinkNetworking.m found this method

FIRNetworkRequestCompletionHandler resolveLinkCallback = ^(NSData *data, NSError *error) {

This method gets called after the firebase sdk makes a post call to an endpoint with the dynamic link
and app bundle identifier, and the response (data) should be

{
    "deepLink": 'the deep link',
    "resolvedLink": "the shortlink that is resolved"
}
But instead the data is an empty object {} with no deepLink or resolvedLink.

However when the dynamic link is created manually in the firebase console, it works perfectly fine.
I also debugged the dynamic links using d=1 query param, and there is no error. The links also work in the browser (resolve with the original url).

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by dmandar** [comment]
Thanks for reporting. Is there a dynamic link you can share? Internal bug b/ tracking this.

**Comment by adkaushik** [comment]
@dmandar 
Leaving a dynamic link here for reference:
```https://by9nq.app.goo.gl/E6DM6hnrmXSXAX88A```

**Comment by dmandar** [comment]
We are not able to repro the issue on our end. Can you try fixing the warnings in your FDL link for iOS?  https://by9nq.app.goo.gl/E6DM6hnrmXSXAX88A/?d=1

**Comment by adkaushik** [comment]
Hey @dmandar all the warnings are related to an old iOS and android package names that we no longer.  I donot think that they are causing the issue as the links created using the console work just fine, except for the ones that are made using the rest endpoint

**Comment by morganchen12** [comment]
Hey @adkaushik, sorry for the slow response. Here's some guidance from the dynamic links backend team:

>1. Clean up the registered apps under their firebase project. Ideally, the registered apps under firebase console should match the registered app on google cloud project console, sometimes they are out of sync.

This suggestion will likely not directly resolve your issue, but it will remove some irrelevant errors, which will make it easier for us to debug.

>2. Check your iOS bundle id specified in their FDL link. This should match the app's bundle id; we have seen four different bundle ids here:
>
>  com.mojo.reads.ios.app.dev
>  com.mojo.reads.ios.app.staging
>  com.mojo.reads.ios.app
>  com.log.os.ios.app
