### ISSUE TITLE
iOS app build failure

### ISSUE THREAD

**Issue by andesappal** [firebase/firebase-ios-sdk#5024]
https://github.com/flutter/flutter/issues/52020

**Comment by paulb777** [comment]
I don't see anything to indicate that this is an iOS SDK issue. It looks like a flutter integration or app configuration problem.  We can reopen if it reproduces by installing a Firebase pod.

**Comment by andesappal** [comment]
Thanks Paul. I'll see what I can do with my code, and talk to the Flutter team if need be.
