### ISSUE TITLE
RemoteConfig crash when fetching before setting up the rootViewController

### ISSUE THREAD

**Issue by nandodelauni** [firebase/firebase-ios-sdk#504]
### Describe your environment

  * Xcode version: Xcode 9.1
  * Firebase SDK version: 4.6.0
  * Firebase Component: FirebaseRemoteConfig
  * Component version: 2.1.0

### Describe the problem

When I try to fetch the remote config when the app starts it crashes.

#### Steps to reproduce:

When I call `fetchWithCompletionHandler:` and the rootViewController has not been yet set in the current window (because I'm doing so once the completion handler is called in the fetch, to have updated the config values) it crashes with the following error:

> *** Assertion failure in -[UIApplication _runWithMainScene:transitionContext:completion:]

I'm not using the library in the good way? The documentation doesn't say any requirement for `fetchWithCompletionHandler:` tho.

**Comment by morganchen12** [comment]
Please post the full stack trace along with the code that causes the issue.
