### ISSUE TITLE
Missing symbols on Build

### ISSUE THREAD

**Issue by nidegen** [firebase/firebase-ios-sdk#5045]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.18.0
  * Firebase Component: Analytics
  * Installation method:Zip file

#### Steps to reproduce:

- Manually install firebase from the zip.

- Build it.

Output:
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FIRHeartbeatInfo", referenced from:
      objc-class-ref in FirebaseInstallations(FIRInstallationsAPIService.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

As already reported on #4800, we get linking errors since trying to update above 6.14.

I could not reproduce it on a fresh project, and it seemed to work for me once, but it popped up again.

I stripped down the existing project, keeping the build error.

**Comment by nidegen** [comment]
just run `sh setup.sh` to dl the zippped firebase

**Comment by maksymmalyhin** [comment]
@nidegen Could you make sure you remove all old Firebase framework versions and copy the new ones? Also you may clean the build folder and Derived Data folder in case the first doesn't help. 

From you particular error it looks like your project picks  an old `FirebaseCore.framework` version.

**Comment by nidegen** [comment]
That is what i was thinking. I have tried those things, but let me double check. Maybe search paths were wrong.

**Comment by nidegen** [comment]
yep, there was the old version in the carthage build folder 😖 thanks for the trigger:D

**Comment by maksymmalyhin** [comment]
I'm glad it was fixed for you!
