### ISSUE TITLE
Add Query equality function

### ISSUE THREAD

**Issue by willbattel** [firebase/firebase-ios-sdk#5049]
### Feature proposal

* Firebase Component: Firestore

Our team would like to see a built-in function added to the Query object that allows us to compare it with another Query object for logical equality. I've nosed around and haven't found this functionality built into the SDK, though there are workarounds possible on our side. This would be a low priority nice-to-have for us if you agree in its appropriateness. Thanks!

**Comment by wilhuff** [comment]
I believe this is already present: `FIRQuery` implements `isEqual:`:

https://github.com/firebase/firebase-ios-sdk/blob/master/Firestore/Source/API/FIRQuery.mm#L132

Or were you looking for something else?

**Comment by willbattel** [comment]
@wilhuff you're right. I had a weird issue in Xcode where some functions appeared not to exist. Restarting Xcode and cleaning the build resolved the issue. The implementation of `isEqual` should give us exactly what we want. Thank you!
