### ISSUE TITLE
[Catalyst] Invalid Code Signing for uploaded apps

### ISSUE THREAD

**Issue by EliteTechnicalCare** [firebase/firebase-ios-sdk#5053]
After jumping through 1000 hoops I was able to get my project to compile, and after another 1000 hoops I was able to get it to achieve, but then when I finally uploaded it to the App Store I was hit with:

> ITMS-90284: Invalid Code Signing - The executable 'EliteBiller.app/Contents/Frameworks/grpcpp.framework/Versions/A/Resources/gRPCCertificates-Cpp.bundle' must be signed with the certificate that is contained in the provisioning profile.

This is currently what I have for signing:
![image](https://user-images.githubusercontent.com/12222977/76331069-029acc00-62c5-11ea-8f64-061125fbb7e8.png)

Is this an issue on my end? Or ongoing Catalyst issues?

**Comment by morganchen12** [comment]
Can you check the code signatures of the gRPC bundle and your main application bundle? You can grab the certificate information with the following commands:

```
# Examine code signing information, outputting the certificate to $(pwd)
$ codesign -dvvvv --extract-certificates /path/to/resourceOrApp.bundle
# Examine the certificate data using openssl
$ openssl x509 -inform DER -in codesign0 -text
```

This is to figure out if the two bundles have separate signing certificates. If they do, you should then
- Re-sign the gRPC bundle with the same certificate and signing identity that you used for the main app bundle, then resubmit to the App Store and hope it passes
- Figure out why Xcode is not doing this by default.
