### ISSUE TITLE
'../AppEvents/Internal/ViewHierarchy/FBSDKViewHierarchy.h' file not found

### ISSUE THREAD

**Issue by WillLewis** [firebase/firebase-ios-sdk#5062]
###  environment
  *Cocoapods 1.9.1
  * Xcode version: 11.3.1
  * Firebase SDK version: 6.2
  * Firebase Component: FBSDKCoreKit + Internal.h
  * Component version: 6.6.0
  * Installation method: CocoaPods 

### problem
'../AppEvents/Internal/ViewHierarchy/FBSDKViewHierarchy.h' file not found

<img width="1584" alt="Screen Shot 2020-03-10 at 6 45 46 PM" src="https://user-images.githubusercontent.com/789554/76368801-617d3700-62ff-11ea-986f-76e0669d4805.png">

### to reproduce:**Actual Issue**
CompileC /Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKLoginKit.build/Objects-normal/x86_64/FBSDKLoginError.o /Users/WL/Desktop/NANO/OnParApp/OnPar/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/Internal/FBSDKLoginError.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'FBSDKLoginKit' from project 'Pods')
    cd /Users/WL/Desktop/NANO/OnParApp/OnPar/Pods
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target x86_64-apple-ios8.0-simulator -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu11 -fobjc-arc -fobjc-weak -fmodules -gmodules -fmodules-cache-path=/Users/WL/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/WL/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -fmodule-name=FBSDKLoginKit -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DPOD_CONFIGURATION_DEBUG=1 -DDEBUG=1 -DCOCOAPODS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -fobjc-abi-version=2 -fobjc-legacy-dispatch -index-store-path /Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Index/DataStore -iquote /Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKLoginKit.build/FBSDKLoginKit-generated-files.hmap -I/Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKLoginKit.build/FBSDKLoginKit-own-target-headers.hmap -I/Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKLoginKit.build/FBSDKLoginKit-all-non-framework-target-headers.hmap -ivfsoverlay /Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKLoginKit.build/all-product-headers.yaml -iquote /Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKLoginKit.build/FBSDKLoginKit-project-headers.hmap -I/Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Products/Debug-iphonesimulator/FBSDKLoginKit/include -I/Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKLoginKit.build/DerivedSources-normal/x86_64 -I/Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKLoginKit.build/DerivedSources/x86_64 -I/Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKLoginKit.build/DerivedSources -F/Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Products/Debug-iphonesimulator/FBSDKLoginKit -F/Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Products/Debug-iphonesimulator/FBSDKCoreKit -include /Users/WL/Desktop/NANO/OnParApp/OnPar/Pods/Target\ Support\ Files/FBSDKLoginKit/FBSDKLoginKit-prefix.pch -MMD -MT dependencies -MF /Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKLoginKit.build/Objects-normal/x86_64/FBSDKLoginError.d --serialize-diagnostics /Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKLoginKit.build/Objects-normal/x86_64/FBSDKLoginError.dia -c /Users/WL/Desktop/NANO/OnParApp/OnPar/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/Internal/FBSDKLoginError.m -o /Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKLoginKit.build/Objects-normal/x86_64/FBSDKLoginError.o

In file included from /Users/WL/Desktop/NANO/OnParApp/OnPar/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/Internal/FBSDKLoginError.m:21:
/Users/WL/Desktop/NANO/OnParApp/OnPar/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/FBSDKCoreKit+Internal.h:102:9: fatal error: '../AppEvents/Internal/ViewHierarchy/FBSDKViewHierarchy.h' file not found
#import "../AppEvents/Internal/ViewHierarchy/FBSDKViewHierarchy.h"
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

### Relevant code...Below is my podfile
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Messaging'
pod 'Firebase/InAppMessaging'
pod 'Firebase/Storage'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/RemoteConfig'
pod 'FirebaseUI'

target 'FriendlyChatSwift' do
end

### And here is the output from a pod update:
The following pod updates are available:
- FBSDKLoginKit 4.44.1 -> 5.15.1 (latest version 6.2.0)
- Firebase 6.15.0 -> (unused) (latest version 6.19.0)
- FirebaseAnalytics 6.2.1 -> 6.3.1 (latest version 6.3.1)
- FirebaseCore 6.6.0 -> 6.6.4 (latest version 6.6.4)
- FirebaseCoreDiagnostics 1.2.1 -> 1.2.2 (latest version 1.2.2)
- FirebaseInAppMessaging 0.16.0 -> 0.19.0 (latest version 0.19.0)
- FirebaseMessaging 4.2.1 -> 4.3.0 (latest version 4.3.0)
- FirebaseStorage 3.5.0 -> 3.6.0 (latest version 3.6.0)
- FirebaseUI 4.1.1 -> 8.4.2 (latest version 8.4.2)
- GoogleAppMeasurement 6.2.1 -> 6.3.1 (latest version 6.3.1)
- GoogleDataTransport 4.0.1 -> 5.0.0 (latest version 5.0.0)
- GoogleDataTransportCCTSupport 1.4.1 -> 2.0.0 (latest version 2.0.0)
- GoogleSignIn 4.4.0 -> 5.0.2 (latest version 5.0.2)
- SDWebImage 4.4.8 -> 5.6.0 (latest version 5.6.0)
- TwitterCore 2.8.0 -> (unused) (latest version 3.2.0)
- TwitterKit 2.8.1 -> (unused) (latest version 3.4.2)
```

```

**Comment by paulb777** [comment]
Looks like a [Facebook SDK problem](https://cocoapods.org/pods/FBSDKCoreKit). Please report it there. We can reopen if it's something about Firebase triggering it.

**Comment by KFMONGF2P** [comment]
@WillLewis 
can you try this solution, see if it works for you or not as I have tried so many ways and this solved my problem?
https://github.com/roughike/flutter_facebook_login/issues/201#issuecomment-543282475

**Comment by WillLewis** [comment]
@KFMONGF2P 
I'm not using flutter but a modified version of that worked for me...

- From terminal project directory run `pod cache clean --all`
- Remove `ios/Podfile.lock` file 
- Go to the `Podfile` file and ensure it reads `platform :ios, '11.0'`
- From terminal project directory run `pod install`
- Run the project again

Thanks
