### ISSUE TITLE
FIRRemoteConfig crash ios 13 with latest SDK 6.18.0

### ISSUE THREAD

**Issue by daisy1754** [firebase/firebase-ios-sdk#5066]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.18.0
  * Installation method: ` Carthage`

cartfile.resolved:
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" "6.18.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAuthBinary.json" "6.18.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseDynamicLinksBinary.json" "6.18.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseFirestoreBinary.json" "6.18.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebasePerformanceBinary.json" "6.18.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseRemoteConfigBinary.json" "6.18.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseStorageBinary.json" "6.18.0"
```

### [REQUIRED] Step 2: Describe the problem
Seeing around 3% of session crashes per crashlytics. cannot reproduce on my iphone.

stacktrace:
```
Crashed: com.google.GoogleConfigService.FIRRemoteConfig
0  libdispatch.dylib              0x1a382eb20 __DISPATCH_WAIT_FOR_QUEUE__ + 452
1  ???                            0x0 (Missing)
2  ???                            0x0 (Missing)
3  cocalero-client                0x102c230c4 -[FPRRemoteConfigFlags sessionSamplingRate] + 446748
4  cocalero-client                0x102c22724 -[FPRConfigurations sessionsSamplingPercentage] + 444284
5  cocalero-client                0x102c1db08 -[FPRSessionManager isGaugeCollectionEnabledForSessionId:] + 424800
6  cocalero-client                0x102c1d9b8 -[FPRSessionManager updateSessionId:] + 424464
7  cocalero-client                0x102c1d720 -[FPRSessionManager initWithNotificationCenter:] + 423800
8  cocalero-client                0x102c1d67c __35+[FPRSessionManager sharedInstance]_block_invoke + 423636
9  libdispatch.dylib              0x1a3821fd8 _dispatch_client_callout + 20
10 ???                            0x10615d01a3823700 (Missing)
11 ???                            0x0 (Missing)
12 cocalero-client                0x102c2db44 -[FPRNetworkTrace start] + 490396
13 cocalero-client                0x102c34afc __InstrumentDataTaskWithRequestCompletionHandler_block_invoke + 518996
14 cocalero-client                0x102c34a78 __InstrumentDataTaskWithRequestCompletionHandler_block_invoke + 518864
15 cocalero-client                0x102c199ec -[RCNConfigFetch URLSessionDataTaskWithContent:completionHandler:] + 408132
16 cocalero-client                0x102c1860c -[RCNConfigFetch fetchWithUserProperties:completionHandler:] + 403044
17 libdispatch.dylib              0x1a3820b7c _dispatch_call_block_and_release + 32
18 ???                            0x0 (Missing)
19 ???                            0x0 (Missing)
20 ???                            0x0 (Missing)
21 ???                            0x0 (Missing)
22 ???                            0x127bfb01a3887700 (Missing)
23 ???                            0x2b149101a388da00 (Missing)
```

`BUG IN CLIENT OF LIBDISPATCH: dispatch_sync called on queue already owned by current thread`

I've seen various related issue like https://github.com/firebase/firebase-ios-sdk/issues/3929 and tried the latest SDK but it seems we still have this issue

**Comment by morganchen12** [comment]
Looks like this was also reported on FlutterFire in September (https://github.com/FirebaseExtended/flutterfire/issues/225) and may be a regression of #3929. @daisy1754 if you have a fully symbolicated crash report that'd be helpful, but even without it the cause of this crash is pretty clear. Fixing it may be non-trivial though.

**Comment by visumickey** [comment]
Thanks for re-surfacing this issue. We will debug this again to see if we could et anyways around this. Internally tracked at b/151214123.

**Comment by daisy1754** [comment]
Thanks for prompt response! Do you have any recommendation on workaround while we are waiting for fix? Would removing FirebasePerformance help?

**Comment by visumickey** [comment]
@daisy1754 As we were looking at this, the method in the stack trace has been removed a few releases ago (in the context of fixing a crash similar to this). Can you verify if this crash is occurring the latest version of your app (that contains 6.18.0 version of Firebase)? If it crashes, can you share the stack trace from the latest version of your app?

**Comment by daisy1754** [comment]
hm interesting let me check with team

**Comment by daisy1754** [comment]
Hey @visumickey we believe you were right. We released the new version and verified the latest version of our app contained 6.18.0. Since launching the new version we no longer see the issue! thanks for your help!!!
