### ISSUE TITLE
Firestore v6.19.0 is not available via Carthage

### ISSUE THREAD

**Issue by Gagnant** [firebase/firebase-ios-sdk#5071]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.18.0(?)
  * Firebase Component: Firestore
  * Component version: 6.18.0(?)
  * Installation method: Carthage

### [REQUIRED] Step 2: Describe the problem

Firestore 6.19.0 version is not available through the Carthage. All other firebase components are ok. Dependency is listed as `binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseFirestoreBinary.json"` in `Cartfile`

**Comment by ryanwilson** [comment]
Hey @Gagnant - can you clear out any caches and try again? Downloading that file directly I see:

```
"6.19.0": "https://dl.google.com/dl/firebase/ios/carthage/6.19.0/FirebaseFirestore-7e8e2fa05c5f7aa3.zip",
```

and that direct link allows me to download the `6.19.0` version of Firestore.

Let me know if you're still having troubles with it and I can re-open.
