### ISSUE TITLE
Not found run script in FirebaseCrashlytics via Carthage

### ISSUE THREAD

**Issue by d-date** [firebase/firebase-ios-sdk#5074]
* Xcode version: 11.3.1
  * Firebase SDK version: 6.19.0
  * Firebase Component: Crashlytics
  * Component version: v4.0.0-beta 5
  * Installation method: `Carthage`

As described in [your document](https://firebase.google.com/docs/crashlytics/get-started-new-sdk?platform=ios), we need to run Build Script but we cannot find `FirebaseCrashlytics/run` and `FirebaseCrashlytics/upload-symbols` under `FirebaseCrashlytics.framework` via Carthage

<img width="453" alt="Screen Shot 2020-03-11 at 20 52 33" src="https://user-images.githubusercontent.com/20222809/76414255-47fced80-63da-11ea-863b-c8d6f61ff611.png">

#### Steps to reproduce:

1. Add `binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashlyticsBinary.json"` in your `Cartfile`
1. Run `carthage update`

**Comment by ryanwilson** [comment]
Hi @d-date - thanks for the report.

Check out the [Carthage instructions](https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md#carthage-usage) and at the very bottom there's a section for Crashlytics specific instructions. Copied here:

>   - To automatically upload your app's symbols so your app's crashes are symbolicated, download
     [upload-symbols](https://github.com/firebase/firebase-ios-sdk/raw/master/Crashlytics/upload-symbols)
     and [run](https://github.com/firebase/firebase-ios-sdk/raw/master/Crashlytics/run).
     Then follow the [Crashlytics documentation](https://firebase.google.com/docs/crashlytics/get-started-new-sdk?platform=ios)
     to add a new run script phase in your Xcode project.

There are packaging limitations we face with Carthage and Crashlytics so you'll have go grab the tools separately when using Carthage.

Let us know if this solves things for you!

**Comment by d-date** [comment]
I missed to read this document and get solved this issue.
Thank you for your help.

**Comment by ahmedelmoughazy** [comment]
> I missed to read this document and get solved this issue.
> Thank you for your help.

could you please tell me where to put the upload-symbols as i'm stuck here

**Comment by samedson** [comment]
@ahmedelmoughazy you may put `run` and `upload-symbols` anywhere under your Xcode project directory, as long as the Run Script Build Phase points to it. It will help to use the `${PROJECT_DIR}` macro in the Run Script Build Phase. Eg, for a project I'm using, I'm putting the tools in a `scripts` folder in my project directory:

![Screen Shot 2020-03-19 at 1 29 02 PM](https://user-images.githubusercontent.com/555046/77096479-c3b3f700-69e5-11ea-944f-aef7f003fe8b.png)


So my Run Script Build Phase that I set up is `"${PROJECT_DIR}/scripts/run"`:

![Screen Shot 2020-03-19 at 1 31 37 PM](https://user-images.githubusercontent.com/555046/77096629-fa8a0d00-69e5-11ea-82e5-2bd212eee044.png)

**Comment by nugmanoff** [comment]
@ahmedelmoughazy Don't forget to add appropriate input files on top of what @samedson provided you.

(I am talking about this one basically)
`${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}`

**Comment by ahmedelmoughazy** [comment]
Thanks you very much, it worked ! ...
