### ISSUE TITLE
`-[FIRRemoteConfig ensureInitializedWithCompletionHandler:]` method uses DISPATCH_QUEUE_PRIORITY_LOW

### ISSUE THREAD

**Issue by nikolaykasyanov** [firebase/firebase-ios-sdk#5083]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.17.0
  * Firebase Component: Remote Config
  * Component version: 4.4.7
  * Installation method: `CocoaPods`

### [REQUIRED] Step 2: Describe the problem

We've encountered an issue where remote config initialization doesn't complete in a timely manner when the app is launched in background (by a significant location change, for example).

I'm not sure this is the exact reason but `-[FIRRemoteConfig ensureInitializedWithCompletionHandler:]` uses low priority queue and I suspect that might be a deciding factor when app is started in background.

Even if it's not, all other calls to `dispatch_async` use `DISPATCH_QUEUE_PRIORITY_DEFAULT`, would be nice if the initialization method were doing the same.

https://github.com/firebase/firebase-ios-sdk/blob/31385e0f6fd183704b39a49e582ad6c7b057e5e7/FirebaseRemoteConfig/Sources/FIRRemoteConfig.m#L197

#### Steps to reproduce:

1. Create an iOS app using Firebase Remote Config and utilizing significant location changes to be woken up in background by the OS.
2. Add logging to observe remote config initialization
3. Make the app be started due to a significant location change (please note that the issue doesn't occur when the change is triggered by revoking and then granting location permissions again, it only reproduces consistently if a real location change happens while device is locked in my poclet).

Expected result: `-[FIRRemoteConfig ensureInitializedWithCompletionHandler:]` calls completion handler.
Actual result: `-[FIRRemoteConfig ensureInitializedWithCompletionHandler:]` doesn't call completion handler.

**Comment by maksymmalyhin** [comment]
@nikolaykasyanov Thank you for bringing this up. Changing the priority will not necessary guarantee fetching remote config in the background within the iOS provided timeframe. If fetching the config is critical for your logic you should consider **requesting additional background time** by [beginning a background task](https://developer.apple.com/documentation/uikit/uiapplication/1623051-beginbackgroundtask) before fetching the config and [ending the task](https://developer.apple.com/documentation/uikit/uiapplication/1622970-endbackgroundtask) once the config fetched and processed. In this case you also should keep in mind proper background task expiration handling (especially on iOS 13+).

**Comment by maksymmalyhin** [comment]
@nikolaykasyanov Could you please try this approach and let us know if it works for your case. Feel free to reopen the ticket if more actions are required from our side.

**Comment by nikolaykasyanov** [comment]
@maksymmalyhin thanks for your reply and hint. It's turned out that the app had enough backround time, the actual issue is #5085.
