### ISSUE TITLE
[FIRApp configure] changes context of AppDelegate bundle

### ISSUE THREAD

**Issue by mreddyamwell** [firebase/firebase-ios-sdk#5092]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.19.0
  * Firebase Component: Core/Analytics
  * Component version: Analytics v.60301000
  * Installation method: `Zip file`

#### Steps to reproduce:

What happened? How can we make the problem occur?
This is a bit of a strange one and hoping someone here can help. This also only seems to happen on a real device. Works fine on the simulator.

When we call `[FIRApp configure]` in `didFinishLaunchingWithOptions`, it seems to change the context of `AppDelegate`'s bundle.

Before the call it'll be something like this:
`NSBundle </var/containers/Bundle/Application/<unique identifier>/<app name>.app/Frameworks/<our framework.framework>`

After the call it changes to:
`NSBundle </private/var/containers/Bundle/Application/<unique identifier>/<app name>.app>`

This causes our app to crash on anything that relies on that bundle in `AppDelegate` (like loading a nib from a storyboard). The bundle seems to only change for `AppDelegate`, as all other files are fine. When `[FIRApp configure]` is removed/commented out, app runs normally without issues.

**Comment by morganchen12** [comment]
Can you share a sample project that repros this issue?

**Comment by mreddyamwell** [comment]
Adding `FirebaseAppDelegateProxyEnabled` set to `NO` in the `info.plist` and manually implementing the delegation handlers in `AppDelegate` seems to have done the trick.

**Comment by ryanwilson** [comment]
@mreddyamwell if you were able to reproduce this in a quickstart it would be very helpful to figure out if this is a project-specific issue or a general issue - having the `AppDelegateProxy` enabled should work as intended and not affect the bundle.

Glad you're unblocked at the very least!

**Comment by mreddyamwell** [comment]
@ryanwilson I was not able to repro this in the quickstart projects as none of them have a similar setup to ours. Our project has our common codebase (`AppDelegate` included) brought in as a framework. I'm thinking because `AppDelegate`'s relative path is different from the norm is what is causing the issue.
