### ISSUE TITLE
Remote config conditionals created with user properties does not work

### ISSUE THREAD

**Issue by adrianortuzar** [firebase/firebase-ios-sdk#5099]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.18.0
  * Firebase Component: RemoteConfig
  * Component version: 6.18.0
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

Remote config conditionals created with user properties does not work.

#### Steps to reproduce:

We create a user property called `version_code` is a integer.
We also create a conditional based on this property, `exact matches`
Our app does not catch the correct condition.
We tested through the `debug view` and the property  `version_code` is set up correctly.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by dmandar** [comment]
Thanks for reporting. Can your enable logs with debug mode for analytics (https://firebase.google.com/docs/analytics/debugview) and post those here? Also note that analytics sdk might take a while to log events to the backend. You can make sure events are uploaded by backgrounding and foregrounding the app. The upload details will also be logged.

**Comment by adrianortuzar** [comment]
thanks @dmandar ,
did not found better way to paste the logs here than in a picture. Better way to do it, please let me know.

<img width="1017" alt="Screenshot 2020-03-17 at 11 04 51" src="https://user-images.githubusercontent.com/649600/76846663-24ee9580-6841-11ea-973c-97fb530166ee.png">

**Comment by adrianortuzar** [comment]
Hi, after some testing I discovered that when 
`Analytics.setAnalyticsCollectionEnabled(false)`
Remote config conditions does not work.

**Comment by paulb777** [comment]
@adrianortuzar Thanks for sharing your investigation.

@dmandar @morganchen12 Does documentation need to be improved?

**Comment by morganchen12** [comment]
This sounds like intended behavior @dmandar can you confirm? If so I'll update the docs.

**Comment by dmandar** [comment]
Yes please. User properties and audiences only work when analytics is enabled.

**Comment by morganchen12** [comment]
Thanks, I'll update the docs.

**Comment by morganchen12** [comment]
Googlers-only: docs updated in internal change cl/324093625.
