### ISSUE TITLE
[Messaging] Not retrieving FCM Token

### ISSUE THREAD

**Issue by cristianomatte** [firebase/firebase-ios-sdk#511]
### Describe your environment

  * Xcode version: 9.1
  * Firebase Component: Messaging
  * Component version: 0.1.5

### Step 3: Describe the problem

I have an iOS framework that had a dependency on the Firebase/Messaging framework. Since I have migrated to FirebaseCommunity/Messaging, the `didReceiveRegistrationToken` from the `MessagingDelegate` is never called, and the `fcmToken` is always `nil`.

The quite strange part of this issue is that if I run my framework sample directly from Xcode with _Automatically_ launch, the delegate is called and I can retrieve an `fcmToken`. However, if I change the launch to `Wait for executable to be launched`, the delegate is never called and the `fcmToken` is always `nil`. The same happens if I do not launch the sample directly from Xcode or download the sample from Testflight.

It is important to emphasize that the framework only requires to receive messages when the app is in foreground, and thus there is no APNS and remote configuration set up. The aim is to use only the FCM direct channel.

Another information that may be relevant is that the method swizzling is disabled and the configuration is done by code, and not by adding the `GoogleService-Info.plist` file to the project. This is required because is a framework (and not and app) that is integrating with Firebase.

#### Steps to reproduce:

- Create a framework that depends upon `FirebaseCommunity/Messaging`, and a sample that uses this framework
- Create a `MessagingDelegate` instance and initialize it with the framework
- The `didReceiveRegistrationToken` delegate method is called if testing directly from Xcode and with _Automatically_ launch
- In all other scenarios, the `fcmToken` is always `nil` and the `didReceiveRegistrationToken` delegate method is never called

**Comment by paulb777** [comment]
I suspect that your Podfile is not including FirebaseInstanceID that is required for Messaging to work.

See https://github.com/firebase/firebase-ios-sdk#firebase-messaging

**Comment by cristianomatte** [comment]
I have the `FirebaseInstanceID` in my Podfile.

**Comment by morganchen12** [comment]
@cristianomatte this is going to be low priority for the team since FirebaseCommunity will be deprecated soon.

Hopefully with the removal of much of our reflection cruft these errors will go away.

**Comment by morganchen12** [comment]
@cristianomatte FirebaseCommunity no longer exists since CocoaPods now supports static framework integration. Please try integrating with the latest version of Firebase using CocoaPods 1.4.0 or higher and reopen this issue if it resurfaces.
