### ISSUE TITLE
FR: Permit batch operations >500

### ISSUE THREAD

**Issue by GoldenJoe** [firebase/firebase-ios-sdk#5111]
### Feature proposal

* Firebase Component: Database

Sometimes it is necessary to store complex objects that if stored as a flat document, would go over the 1MB limit. As such, it can become necessary to store many documents in sub-collections. When doing this, it's very easy to run into the arbitrary 500 operation transactional limit. This appears to be in place to enforce best practices for typical use, but it creates a real problem when you have a one-time large transaction. There should be an option in place that ensures atomicity for any number of writes.

**Comment by wilhuff** [comment]
Hi @GoldenJoe, thanks for writing in.

Firestore provides simple per-operation pricing where you don't have to reserve or manage an instance at an hourly rate. A key part of making this pricing model work is that we have to bound the complexity and duration of each operation.

In a transaction, the likelihood of contention goes up as the number of participants increases. When two transactions contend one of them gets retried, increasing the cost of the operation. The upper limit on the number of documents in a transaction preserves our ability to provide the service at a reasonable fixed unit cost. 

While it's possible that we might raise the 500 document limit slightly in the future, there's no way we can make this unbounded without radically altering the product and the way we price it.

**Comment by GoldenJoe** [comment]
@wilhuff I understand that this is largely based on the pricing model, and I can agree that a limit is a good idea, but you need to understand that "sorry that's just how it is" doesn't make programs work. Could you at least provide some kind of workaround, preferably in the docs themselves? Surely you don't expect me to believe there is a tangible increase in cost between storing the indices for a collection of documents vs a single large array in a master document with all the waste that comes with transferring back and forth. Why not just have some sort of toll-free bridging between arrays and subcollections, perhaps with a strict limitation on document size?

**Comment by samtstern** [comment]
@GoldenJoe it's worth noting that even if we raised the 500 item limit you're very likely to run into the 10MB per write operation limit:
https://firebase.google.com/docs/firestore/quotas#writes_and_transactions

That limit is more fundamental and comes from the Firestore storage backend which has to maintain global strong consistency.

**Comment by GoldenJoe** [comment]
@samtstern the 500 document and 10MB limits are completely different. It's very easy to imagine a case where you would write 1000 documents without even hitting 1MB, such as a record of coordinates, timestamps paired with an identifier, etc.

Again, I read the documentation and I understand their business model. I'm not here to debate their reasoning. I'm here for solutions, but I seem to be the only person suggesting any. Here's another: idempotency tokens. 

Unfortunately it seems I am expected to simply accept the limitations of Firestore. If that's the case, I certainly won't be recommending it to future clients. The idea of being "easily scalable" with such strict limitations is humorous, but not appealing for use.

**Comment by wilhuff** [comment]
> @wilhuff I understand that this is largely based on the pricing model, and I can agree that a limit is a good idea, but you need to understand that "sorry that's just how it is" doesn't make programs work.

I'm completely sympathetic that this makes things harder, but all systems have limits and when you come up against them you have to design around it. There are no databases that allow unlimited transaction sizes. In any case, this is a limit we can't reasonably change.

> Could you at least provide some kind of workaround, preferably in the docs themselves?

Workarounds depend a lot on your application and why you might want to write a large number of documents at the same time. Some ideas:

  * Write in groups and just accept that the bulk update isn't atomic
  * Write to a separate collection as above, and then update a single document that changes the collection from which clients read
  * Partition the data around some client attribute that allows you to update each client's view atomically without needing to update all clients together

You get the idea.

> Surely you don't expect me to believe there is a tangible increase in cost between storing the indices for a collection of documents vs a single large array in a master document with all the waste that comes with transferring back and forth. Why not just have some sort of toll-free bridging between arrays and subcollections, perhaps with a strict limitation on document size?

Documents already have a limit of 1 MB.

The shape of the data (arrays or documents) is reflected in the physical storage of data. They can't really be exchanged for each other. As a developer you need to trade-off between these representations based on your needs.
