### ISSUE TITLE
FR: Vulnerabilities check fail in GoogleUtilities/AppDelegateSwizzler:6.5.1

### ISSUE THREAD

**Issue by RameshIDPal** [firebase/firebase-ios-sdk#5113]
We are using below dependencies in our projects
'FirebaseCore', '6.6.4'
'FirebaseMessaging', '4.3.0'
'FirebaseAnalytics','6.3.1'

We ran the Dependency checker to find the vulnerabilities in GoogleUtilities/AppDelegateSwizzler:6.5.1. Is this will be fixed in the future release.

**Comment by paulb777** [comment]
@RameshIDPal Which dependency checker and what vulnerabilities?  Please provide more detail to help us investigate.

**Comment by RameshIDPal** [comment]
We are using OWASP Dependency checker and attached the screenshot below,

![Screenshot 2020-03-16 at 8 21 50 PM](https://user-images.githubusercontent.com/45414029/76770486-0b5b3880-67c4-11ea-8eda-11555b04faa3.png)

**Comment by paulb777** [comment]
Thanks, but we still need the specifics of what vulnerabilities you'd like to see fix. You're also welcome to send a PR with the desired changes.

**Comment by RameshIDPal** [comment]
@paulb777 The vulnerabilities are

![Screenshot 2020-03-16 at 8 41 06 PM](https://user-images.githubusercontent.com/45414029/76772418-dd2b2800-67c6-11ea-80b6-51d351f9a47f.png)

**Comment by paulb777** [comment]
These messages don't refer to specific code. We will likely need file and line numbers to be able to progress.

**Comment by wilhuff** [comment]
Your dependency checker is mistaken. Those vulnerabilities refer to DeleGate, a network proxy. They were also issued in 2005, years before this software even existed.
