### ISSUE TITLE
157239669: dynamicLink nil upon first app install

### ISSUE THREAD

**Issue by nunepradeepkumar** [firebase/firebase-ios-sdk#5122]
Xcode version: 11.3.1
Firebase SDK version: 6.19
Firebase Component: DynamicLinks

I tried to create dynamicLink at Firebase console to navigate user to download my app at appStore,
and when they launch app for the first time I keep getting DynamicLink object with nil url.
func application(_ application: UIApplication, continue userActivity: NSUserActivity,
restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool{

    let handled = DynamicLinks.dynamicLinks().handleUniversalLink(userActivity.webpageURL!) { (dynamiclink, error) in
        // Redirect user to specific screen according to requirement.
        DynamicLinks.performDiagnostics(completion: nil)
        print("dynamic link :: \(String(describing: dynamiclink))")

        print("Dynamic link : \(String(describing: dynamiclink?.url))")
        if dynamiclink?.url != nil{
            //                self.logFirebaseAnaylyticsEvent(url: dynamiclink!.url!)
            self.logFirebaseAnaylyticsReopenEvent(url: dynamiclink!.url!)
        }

        //            let path = dynamiclink?.url?.path
        //            if path == "/home" {
        //                print("Redirect to home screen")
        //            }else{
        //                print("Redirect to another screen")
        //            }

    }

    if !handled {

        // Show the deep link URL from userActivity.
        let message = "continueUserActivity webPageURL:\n\(userActivity.webpageURL?.absoluteString ?? "")"
        showDeepLinkAlertView(withMessage: message)

    }
    if handled == false{
        UserDefaultStore.DeepLinkingURL = ""
    }
    return handled
}
Optional(<FIRDynamicLink: 0x28205af80, url [(null)], match type: unique, minimumAppVersion: N/A, match message: (null)>)

**Comment by nunepradeepkumar** [comment]
Xcode version: 11.3.1
Firebase SDK version: 6.19
Firebase Component: DynamicLinks

I tried to create dynamicLink at Firebase console to navigate user to download my app at appStore,
and when they launch app for the first time I keep getting DynamicLink object with nil url.
 func application(_ application: UIApplication, continue userActivity: NSUserActivity,
                     restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool{

        let handled = DynamicLinks.dynamicLinks().handleUniversalLink(userActivity.webpageURL!) { (dynamiclink, error) in
            // Redirect user to specific screen according to requirement.
            DynamicLinks.performDiagnostics(completion: nil)
            print("dynamic link :: \(String(describing: dynamiclink))")

            print("Dynamic link : \(String(describing: dynamiclink?.url))")
            if dynamiclink?.url != nil{
                //                self.logFirebaseAnaylyticsEvent(url: dynamiclink!.url!)
                self.logFirebaseAnaylyticsReopenEvent(url: dynamiclink!.url!)
            }


            //            let path = dynamiclink?.url?.path
            //            if path == "/home" {
            //                print("Redirect to home screen")
            //            }else{
            //                print("Redirect to another screen")
            //            }

        }

        if !handled {

            // Show the deep link URL from userActivity.
            let message = "continueUserActivity webPageURL:\n\(userActivity.webpageURL?.absoluteString ?? "")"
            showDeepLinkAlertView(withMessage: message)

        }
        if handled == false{
            UserDefaultStore.DeepLinkingURL = ""
        }
        return handled
    }

Optional(<FIRDynamicLink: 0x28205af80, url [(null)], match type: unique, minimumAppVersion: N/A, match message: (null)>)

**Comment by DracoRubi** [comment]
I got exactly this same issue, I've been trying to solve it since yesterday.

The `handleUniversalLink` method returns true, but in the completion closure the `dynamiclink.url` property is nil.

**Comment by morganchen12** [comment]
AFAIK there have been no recent changes in the client SDK. @dmandar, are you aware of any backend changes that could be causing pending links to not be matched properly?

**Comment by dmandar** [comment]
No recent changes in the client. Morgan, can you file a bug for Max to take a look at? Thanks.

**Comment by morganchen12** [comment]
Will do. In the meantime, @DracoRubi @nunepradeepkumar can you confirm that dynamic links work correctly otherwise? (i.e. when clicking a link with the app already installed, the link is correctly populated)

**Comment by morganchen12** [comment]
Filed b/151846783

**Comment by DracoRubi** [comment]
In my case, the following happens:

If the dynamic link is clicked from a native iOS application, like Safari, Notes or the camera (reading a QR containing the link), it doesn't work.
In this case, this method is invoked in the AppDelegate:
`func application(_ application: UIApplication, continue userActivity: NSUserActivity,
                     restorationHandler: @escaping ([Any]?) -> Void) -> Bool`
And as per your documentation, the link is processed with:
`DynamicLinks.dynamicLinks().handleUniversalLink(userActivity.webpageURL)`
But it fails somehow and the result is nil, as indicated above.

However, if I use another application (Firefox, for example), it does work.
In this case, this method is invoked in the AppDelegate:
`func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool`
And as per your documentation, the link is processed with:
`DynamicLinks.dynamicLinks().dynamicLink(fromCustomSchemeURL: url)`

**Comment by nunepradeepkumar** [comment]
> Will do. In the meantime, @DracoRubi @nunepradeepkumar can you confirm that dynamic links work correctly otherwise? (i.e. when clicking a link with the app already installed, the link is correctly populated)

when clicking a link with the app already installed, the link is correctly populated but received dynamic URL is 
Optional(<FIRDynamicLink: 0x280455740, url [(null)], match type: unique, minimumAppVersion: N/A, match message: (null)>)

**Comment by amaurydavid** [comment]
Same issue here.
Clicking on a dynamic link from the Notes app with the app already installed results in the Firebase SDK to send me a `FIRDynamicLink` containing a nil url.

The app triggering the dynamic link doesn't seem to have an impact for me:
- from Notes it opens my app with a nil FIRDynamicLink.url
- from Messenger or duckduckgo it opens a web page with an "open" button redirecting to my app wtih a nil FIRDynamicLink.url

**Comment by eternalstorms** [comment]
same issue here (<FIRDynamicLink: 0x280455740, url [(null)], match type: unique, minimumAppVersion: N/A, match message: (null)>)

**Comment by morganchen12** [comment]
We saw issue when the end user opts out save my place in the app (the check box) for pasteboard. @amaurydavid @nunepradeepkumar @DracoRubi can you make sure the user testing this feature hasn't opted out on the app preview page?

Also, when the link is handled, can you check the device's pasteboard contents to see if the dynamic link is present?

**Comment by DracoRubi** [comment]
No opting-out, the issue still happens.

And when the link is handled, the pasteboard isn't altered

**Comment by morganchen12** [comment]
To clarify, the checkbox needs to be filled: 
![image](https://user-images.githubusercontent.com/4529021/77111249-3ae88b80-69e4-11ea-9097-c833d852a5c0.png)

Can you check that it's filled in?

**Comment by amaurydavid** [comment]
Where did you get this screenshot from ? I don't remember seeing this page.

**Comment by DracoRubi** [comment]
> Where did you get this screenshot from ? I don't remember seeing this page.

It should open if you use the dynamic link without your app installed, or if you press down the link for a while and then select "Open in Safari".

**Comment by LifeEternal** [comment]
> To clarify, the checkbox needs to be filled:
> ![image](https://user-images.githubusercontent.com/4529021/77111249-3ae88b80-69e4-11ea-9097-c833d852a5c0.png)
> 
> Can you check that it's filled in?

what if we tell the dynamic link to skip this page?

**Comment by morganchen12** [comment]
Then the dynamic link will always fall back to a weak match.

**Comment by DracoRubi** [comment]
> Then the dynamic link will always fall back to a weak match.

What if that page isn't shown? For example, if the user already has the app installed, Safari will automatically open the app without showing that page. Will it fall back to a weak match?

**Comment by morganchen12** [comment]
@DracoRubi in that case it'll open the app directly through the system universal link behavior and you'll be able to get the URL from the system callbacks. Dynamic Links rely on the preview page to guarantee strong matching, and it does so by copying the URL to clipboard which the SDK then inspects when the app is opened.

**Comment by amaurydavid** [comment]
So if we check "skip app preview app" in the links settings, we will never be able to get the actual url from FIRDynamicLink ?
Also, could you define "strong match" and "weak match" ?

**Comment by morganchen12** [comment]
@dmandar, can you answer these questions?

**Comment by purnendu-roy** [comment]
> > Will do. In the meantime, @DracoRubi @nunepradeepkumar can you confirm that dynamic links work correctly otherwise? (i.e. when clicking a link with the app already installed, the link is correctly populated)
> 
> when clicking a link with the app already installed, the link is correctly populated but received dynamic URL is
> Optional(<FIRDynamicLink: 0x280455740, url [(null)], match type: unique, minimumAppVersion: N/A, match message: (null)>)

I'm getting the same issue. Any idea how to resolve this.

**Comment by purnendu-roy** [comment]
did anyone know how to solve this issue?

**Comment by DracoRubi** [comment]
> @DracoRubi in that case it'll open the app directly through the system universal link behavior and you'll be able to get the URL from the system callbacks. Dynamic Links rely on the preview page to guarantee strong matching, and it does so by copying the URL to clipboard which the SDK then inspects when the app is opened.

In that case... We should be adding code to manually handle the URL if `handleUniversalLink` returns false?

**Comment by DracoRubi** [comment]
I'd love an answer to my previous question, if possible:

> > @DracoRubi in that case it'll open the app directly through the system universal link behavior and you'll be able to get the URL from the system callbacks. Dynamic Links rely on the preview page to guarantee strong matching, and it does so by copying the URL to clipboard which the SDK then inspects when the app is opened.
> 
> In that case... Should we add code to manually handle the URL if `handleUniversalLink` returns false?

**Comment by dmandar** [comment]
Hi..looks like there are a couple of issues being discussed here. That said, we are not yet able to repro either of those (qualified below) and need some help in narrowing down the issue. 
1. First app install case: This is handled entirely by dynamic links. Using an app preview page (option presented when you create a dynamic link) is highly recommended. This copies the link to the pasteboard and is used by the FDL SDK to resolve. 
a. Are folks using the app preview page also not able to resolve the dynamic link? 
b. If you do not use the app preview page, we will fall back to fingerprinting to resolve the link. If you are seeing this issue, please add details on your device / iOS version.
2. App already installed case: Please refer to #4914

**Comment by StefanTheIOSDeveloper** [comment]
Hi, any update on this issue.

im having the same problem FDL works perfect when app is installed but as soon as you click the link and have to install app first on open it returns nil.

really need this to work as we use this for marketing and affiliate tracking on our apps.

**Comment by xieliweiparkman** [comment]
First app install case doesnt work, I disabled the preview link. The SDK is always returning weak link. We have two apps, one is using the default link then it works perfectly, another one is using custom URL and that has problem. The iOS version is 13.4.1, and it's not working for all our test devices. iPhone 6S, iPhone 7 Plus, iPhone X, iPhone XS Max. Any update here, from the requirement we dont want to use the preview page, but is that the only solution here?

**Comment by xieliweiparkman** [comment]
More information, for the one project with custom URL, I have tested with the default firebase dynamic link, `appname.page.link` and it's working. So I think the problem here is, dynamic link with custom url like `get.appname.com` is not working without preview page, for new install case. Hopefully this information helps!

**Comment by david-kollectin** [comment]
I have the same issue.
Please check dynamic link with custom url.

**Comment by cristoppotelli** [comment]
Hello there, any update on this issue?

I' am also experiencing the same problem, so I think I may avoid opening a new issue.

As far as the app is in the background, handling the dynamic links perfectly works, the problematic use case is the first app install / opening the app from a killed state. That case gives me a nil dynamic link URL.

I am using Xcode 11.6, Firebase Dynamic Links 4.2.0.

Any help greatly appreciated.

**Comment by CeccoCQ** [comment]
Same issue here.

**Comment by cristoppotelli** [comment]
> @nunepradeepkumar Did you ever figure it out? I have spent hours trying to figure out why it's returning nil.

Nope, I ended up doing it manually, which is WAY faster than hoping the framework to do it for you. Your comment hints that is still not fixed, which after so long seems a little bit of a shame.

Just use the UIPasteboard API to retrieve the URL in the items dictionary and handle it as you would've if fed from SDK.

Hope it helps.

**Comment by andrewfashion** [comment]
@cristoppotelli Yea no matter what I do, the dynamic links always are nil. Can you can explain what you mean with uipasteboard? Thanks!

**Comment by Nolkeg** [comment]
I also have this issue but with the default page.link domain

**Comment by andrewfashion** [comment]
I couldn't figure it out after 5 days.

Solution: Branch.io deep linking was a breeze. Sorry Firebase, but I use 15 of your other services and pay for your plan :)

**Comment by eldhosembabu** [comment]
Could you please try to reproduce this issue in our [quick start app](https://github.com/firebase/quickstart-ios/tree/master/dynamiclinks) and let us know? Also try using the latest SDK version for FDL.

I've tried reproducing this and was not able to.

**Comment by rizafran** [comment]
Hi all, I would like to know if you have tried reproducing the issue using our [quickstart app for FDL](https://github.com/firebase/quickstart-ios/tree/master/dynamiclinks) with the latest SDK version?
