### ISSUE TITLE
library not found for -lGoogleAnalytics

### ISSUE THREAD

**Issue by marwanDevTest** [firebase/firebase-ios-sdk#5123]
### Step 1: 

  * Xcode version: 11.2.1
  * Firebase SDK version: __6.19.0__
  * Firebase Component: __Analytics__
  * Component version: __6.19.0__
  * Installation method: `CocoaPods (v1.9.1)`

### Step 2:

I am trying to integrate `FirebaseAnalytics` and I am following [this link](https://firebase.google.com/docs/analytics/get-started?platform=ios) in the documentation. I am using CocoaPods this is my `Podfile`

```ruby
platform :ios, '12.0'

inhibit_all_warnings!

target 'FoodTime' do
  use_frameworks!

  pod 'OneSignal', '>= 2.11.2', '< 3.0'
    
  pod 'Firebase/Analytics', '~> 6.19.0'

  target 'FoodTimeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoodTimeUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignal', '>= 2.11.2', '< 3.0'
end

# Workaround for Cocoapods issue #7606
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
```
When I run, I keep getting the __ERROR:__ `ld: library not found for -lGoogleAnalytics
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

I cleaned up the derived data and updated CocoaPods to the lates version __(1.9.1)__. still the same issue.

Please help

**Comment by paulb777** [comment]
Your project may have lingering references to `GoogleAnalytics` instead of `FirebaseAnalytics`. Try `pod deintegrate` and searching the Build Settings for referencs to `GoogleAnalytics`.

**Comment by marwanDevTest** [comment]
You are right, I had a successful build.
Thank you soooo much!!! 😄
