### ISSUE TITLE
Firebase without analytics dependency

### ISSUE THREAD

**Issue by UberMC** [firebase/firebase-ios-sdk#5130]
### [READ] Guidelines

When filing a feature request please make sure the issue title starts with "FR:".

A good feature request ideally
* is either immediately obvious (i.e. "Add Sign in with Apple support"), or
* starts with a use case that is not achievable with the existing Firebase API and
  includes an API proposal that would make the use case possible. The proposed API
  change does not need to be very specific.

Once you've read this section, please delete it and fill out the rest of the template.

### Feature proposal

* Firebase Component: Core (Auth, Core, Database, Firestore, Messaging, Storage, etc)

Describe your use case and/or feature request here.
FirebaseCore without analytics dependency. Is it possible to have FirebaseCore without analytics being included

Podfile.lock
  - Firebase/Core (6.13.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.1.6)

Our app is being rejected for having an google analytics SDK, we have to remove all analytics.

**Comment by paulb777** [comment]
Remove `Firebase/Core` from the Podfile to exclude the `FirebaseAnalytics` pod.

If you'd like to share more details about the app rejection, we'll share with the Analytics team to investigate a solution that would let you keep Analytics capabilities in the app.

**Comment by morganchen12** [comment]
In this case you can use the [`Firebase/CoreOnly` subspec](https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase.podspec#L38) or depend on `FirebaseCore` directly.

**Comment by wilhuff** [comment]
Is it possible this has to do with Apple Arcade? My understanding is that those apps have strict prohibitions on analytics of any kind.

**Comment by UberMC** [comment]
Kids section app

**Comment by UberMC** [comment]
The app rejection is this: remove idfa functionality, remove the code from the implementation, not just disable use of idfa

Are there any recommendations without removing FirebaseCore and using directly  Firebase/CoreOnly subspec

**Comment by paulb777** [comment]
Adding FirebaseCore (or Firebase/CoreOnly) to the Podfile is a no-op.  All the other Firebase pods will pull it in as a dependency.

**Comment by morganchen12** [comment]
You could use the direct podspecs for each pod, right?

**Comment by paulb777** [comment]
The current recommendation is to specify the pods desired via the Firebase pod - like `pod Firebase/Messaging`.   There is typically no reason to specify FirebaseCore.

**Comment by UberMC** [comment]
Hey guys,

Thanks, as morganchen12 mentioned to just simply replace dependencies Core to CoreOnly worked.

Required I forked https://github.com/invertase/react-native-firebase/ and changed each package pod spec to CoreOnly. Seems to work. Analytics pod was removed succesfully.
