### ISSUE TITLE
DynamicLinks uses AssetsLibrary [Catalyst]

### ISSUE THREAD

**Issue by 666tos** [firebase/firebase-ios-sdk#5139]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4 beta 3
  * Firebase SDK version: 5.15.1
  * Firebase Component: DynamicLinks
  * Component version: 4.0.7
  * Installation method: `CocoaPods`

#### Steps to reproduce:

DynamicLinks uses AssetsLibrary which is deprecated for Catalyst apps

**Comment by 666tos** [comment]
@maksymmalyhin спасибо!

**Comment by maksymmalyhin** [comment]
> @maksymmalyhin спасибо!

@666tos  Пожалуйста! 😄
