### ISSUE TITLE
The x button should partially overlap the corner of the image.

### ISSUE THREAD

**Issue by myCols** [firebase/firebase-ios-sdk#5151]
Environment :

  * Xcode version: 13
  * Firebase SDK version: _____
  * Firebase Component: in-app messaging (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 6.17 for Core and InApp Messaging

  * Installation method: `CocoaPods | Carthage | Zip file` (select one)

Problem

The x button should partially overlap the corner of the image.

![WhatsApp Image 2020-03-18 at 17 14 25](https://user-images.githubusercontent.com/62376265/77048171-4f1d9000-69c6-11ea-9182-cb9de5e2b041.jpeg)

<img width="420" alt="Schermafbeelding 2020-03-19 om 09 42 16" src="https://user-images.githubusercontent.com/62376265/77048090-2a291d00-69c6-11ea-8650-ec0036a765fd.png">

**Comment by christibbs** [comment]
@myCols Are you [customizing the in-app message UI](https://firebase.google.com/docs/in-app-messaging/customize-messages?platform=ios#modify_message_look_and_feel)? This doesn't look like it was built with our default in-app messaging UI.

**Comment by christibbs** [comment]
@myCols Ah, I see. So it's the image only template.

Will investigate.

**Comment by christibbs** [comment]
@myCols It looks like there's some whitespace at the top and the right of this image that's causing the X button to float off of it. Try cropping it to remove this whitespace, I used the attached image and ended up with the attached screenshot.

![Uploading cropped_image.png…]()
![Uploading screenshot_with_cropped_image.png…]()
