### ISSUE TITLE
FR:advertisingIdentifierString reason for apple rejection.

### ISSUE THREAD

**Issue by UberMC** [firebase/firebase-ios-sdk#5153]
### [READ] Guidelines

When filing a feature request please make sure the issue title starts with "FR:".

### Feature proposal

* Firebase Component: Analytics? (Auth, Core, Database, Firestore, Messaging, Storage, etc)

Describe your use case and/or feature request here.

Apple:
As we discussed, we continue to find that your Kids app includes third-party analytics with the ability to collect and transmit IDFA. Specifically, in the "APMIdentity class", there is a selector "advertisingIdentifierString" 

So I create an breakpoint 
and it results in APMASIdentifierManager not APMIdentity as apple says.
-[APMASIdentifierManager advertisingIdentifierString]

I see it gets disabled when I modify info.plist 
<key>FIREBASE_ANALYTICS_COLLECTION_DEACTIVATED</key>
<true/>
<key>GOOGLE_ANALYTICS_DEFAULT_ALLOW_AD_PERSONALIZATION_SIGNALS</key>
<false/>

However I also see there is absolutely no stack trace to what calls the thread with APMASIdentifierManager, so something? I'm guessing an unmodifiable library calls it. and apple is telling us it's impossible to disable.

So is apple right, are my efforts to try and keep Firebase analytics in the app impossible with:
IDFA disabled
In a way apple trusts it's disabled.

**Comment by paulb777** [comment]
Thanks for sharing the details from the Apple rejection. We'll investigate.

**Comment by lopsae** [comment]
Current version of `Firebase/Analytics` (`6.20.0`) uses `GoogleAppMeasurement` which in turns shows up when searching for `ASIdentifierManager`:

```
# from xcode project directory
> grep -r ASIdentifierManager .
Binary file ./Pods/GoogleAppMeasurement/Frameworks/GoogleAppMeasurement.framework/GoogleAppMeasurement matches
```

We are getting rejections from the Apple App Store for a similar issue. Our kids app is being flagged as possibly using IDFA. Communicating with Apple directly they have stated that they want the app to contain absolutely no IDFA code, regardless of if it is called or not.

Seems like `GoogleAppMeasurement` is the only place where that is still being found, and we have found no way to use Firebase without including it too. Unless Apple changes their position we cannot ship with `Firebase/Analytics` in our code.

**Comment by wilhuff** [comment]
Can you post your Podfile.lock?

**Comment by morganchen12** [comment]
Filed b/152062046 internally.

**Comment by lopsae** [comment]
This is my Podfile.lock when only using `Firebase/Analytics`:

```
PODS:
  - Firebase/Analytics (6.20.0):
    - Firebase/Core
  - Firebase/Core (6.20.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.3.1)
  - Firebase/CoreOnly (6.20.0):
    - FirebaseCore (= 6.6.4)
  - FirebaseAnalytics (6.3.1):
    - FirebaseCore (~> 6.6)
    - FirebaseInstallations (~> 1.1)
    - GoogleAppMeasurement (= 6.3.1)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (= 0.3.9011)
  - FirebaseCore (6.6.4):
    - FirebaseCoreDiagnostics (~> 1.2)
    - FirebaseCoreDiagnosticsInterop (~> 1.2)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
  - FirebaseCoreDiagnostics (1.2.2):
    - FirebaseCoreDiagnosticsInterop (~> 1.2)
    - GoogleDataTransportCCTSupport (~> 2.0)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
    - nanopb (~> 0.3.901)
  - FirebaseCoreDiagnosticsInterop (1.2.0)
  - FirebaseInstallations (1.1.0):
    - FirebaseCore (~> 6.6)
    - GoogleUtilities/UserDefaults (~> 6.5)
    - PromisesObjC (~> 1.2)
  - GoogleAppMeasurement (6.3.1):
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (= 0.3.9011)
  - GoogleDataTransport (5.0.0)
  - GoogleDataTransportCCTSupport (2.0.0):
    - GoogleDataTransport (~> 5.0)
    - nanopb (~> 0.3.901)
  - GoogleUtilities/AppDelegateSwizzler (6.5.2):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (6.5.2)
  - GoogleUtilities/Logger (6.5.2):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (6.5.2):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (6.5.2):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (6.5.2)"
  - GoogleUtilities/Reachability (6.5.2):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (6.5.2):
    - GoogleUtilities/Logger
  - nanopb (0.3.9011):
    - nanopb/decode (= 0.3.9011)
    - nanopb/encode (= 0.3.9011)
  - nanopb/decode (0.3.9011)
  - nanopb/encode (0.3.9011)
  - PromisesObjC (1.2.8)

DEPENDENCIES:
  - Firebase/Analytics

SPEC REPOS:
  https://github.com/cocoapods/specs.git:
    - Firebase
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseCoreDiagnosticsInterop
    - FirebaseInstallations
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleDataTransportCCTSupport
    - GoogleUtilities
    - nanopb
    - PromisesObjC

SPEC CHECKSUMS:
  Firebase: fe7f74012742ab403451dd283e6909b8f1fb348a
  FirebaseAnalytics: 572e467f3d977825266e8ccd52674aa3e6f47eac
  FirebaseCore: ed0a24c758a57c2b88c5efa8e6a8195e868af589
  FirebaseCoreDiagnostics: e9b4cd8ba60dee0f2d13347332e4b7898cca5b61
  FirebaseCoreDiagnosticsInterop: 296e2c5f5314500a850ad0b83e9e7c10b011a850
  FirebaseInstallations: 575cd32f2aec0feeb0e44f5d0110a09e5e60b47b
  GoogleAppMeasurement: c29d405ff76e18551b5d158eaba6753fda8c7542
  GoogleDataTransport: a857c6a002d201b524dd4bc2ed7e7355ed07e785
  GoogleDataTransportCCTSupport: 32f75fbe904c82772fcbb6b6bd4525bfb6f2a862
  GoogleUtilities: ad0f3b691c67909d03a3327cc205222ab8f42e0e
  nanopb: 18003b5e52dab79db540fe93fe9579f399bd1ccd
  PromisesObjC: c119f3cd559f50b7ae681fa59dc1acd19173b7e6

PODFILE CHECKSUM: 53bd9c0a8c62c5aac2288b6566531d68bece65ac

COCOAPODS: 1.5.3
```

**Comment by eburley** [comment]
Would you mind emailing me at eburley@google.com? I'd like to follow up on a few details.

**Comment by mjlee250** [comment]
I am having the same issue? Did you find a workaround?

**Comment by nishitsplashmath** [comment]
Same issue.. Our app got rejected because of the same. Also on removing firebase/analytics didn't removed the app measurement.

**Comment by paulb777** [comment]
GoogleAppMeasurement is also a [dependency of Google-Mobile-Ads-SDK](https://github.com/CocoaPods/Specs/blob/master/Specs/5/9/a/Google-Mobile-Ads-SDK/7.57.0/Google-Mobile-Ads-SDK.podspec.json#L4).

**Comment by frantxesco** [comment]
> Would you mind emailing me at [eburley@google.com](mailto:eburley@google.com)? I'd like to follow up on a few details.

Please let us know if you come up with any solution. Thanks.

**Comment by geekydiamond** [comment]
Our app was also rejected for 'made for kids' category. Just waiting on details from Apple, but would expect this is due to the same issue as we use Firebase for databases.
Any solutions/hacks very gratefully received.

**Comment by paulb777** [comment]
@geekydiamond We don't know of any rejections due to Firebase databases - only FirebaseAnalytics.

**Comment by geekydiamond** [comment]
But Firebase/Core (which databases needs) brings in FirebaseAnalytics as a dependency doesn't it? Apologies if this is not the case, but I looked at the Pod dependencies and this seems to be true.

**Comment by paulb777** [comment]
`Firebase/Core` is not a dependency and no longer recommended to be added to Podfiles. Instead, add the pods your app needs to the Podfile and those pods will make sure they have the right dependencies.

**Comment by eburley** [comment]
We're looking at a fix that makes it clearer that the FirebaseAnalytics pod only uses AdSupport framework if it's linked. 

For commentors on the issue who have experienced app store rejection, could you please email me at eburley@google.com. I'd like to get some more details on your specific rejections.

**Comment by divinemery** [comment]
Our app was also rejected for 'made for kid' category. 
Apple said "there is still Third-party analytics or third-party advertising with the ability to collect, transmit or share identifiable information, including, for example, IDFA." 

We are using flutter to build our iOS App. And we are using these flutter plugins:
"firebase_core", 
"firebase_auth",
"google_sign_in" 

So our dependencies are not added from the iOS pod file but from flutter (pubspec.yaml).

1-What is the solution in this case as we don't have the "firebase/CoreOnly" from flutter?
2-Is there any solution around this?

**Comment by gmilano** [comment]
Hi guys this is being a big issue for using Firebase SDK on really important projects. At least in our case we removed the use of Firebase because Apple was rejecting our application because the reference to advertisingIdentifier.
We followed https://firebase.google.com/docs/analytics/configure-data-collection?platform=ios&hl=en#disable_idfa_collection but still Apple see the reference (I think through static analysis) 

This was a big issue for our app that was integrating Exposure Notifications for our country. We still are having this problem and at this moment the solution was to remove Firebase SDK in this first release.

We think the problem is with the reference (https://github.com/CocoaPods/Specs/blob/master/Specs/e/3/b/GoogleAppMeasurement/6.6.0/GoogleAppMeasurement.podspec.json) 

Hope we can have a special version of Firebase SDK without this code .

**Comment by frantxesco** [comment]
> We're looking at a fix that makes it clearer that the FirebaseAnalytics pod only uses AdSupport framework if it's linked.
> 
> For commentors on the issue who have experienced app store rejection, could you please email me at [eburley@google.com](mailto:eburley@google.com). I'd like to get some more details on your specific rejections.

Hi there, this is going to be a huge issue as starting July 1st Apple will reject all apps in the "made for kids" category that reference AdSupport even if they do not use it.

Did you find any solution?

**Comment by eburley** [comment]
FirebaseAnalytics only collects IDFA if the AdSupport framework is linked ([source](https://firebase.google.com/support/guides/analytics-adsupport))

The class and methods used to conditionally access IDFA had names that overlapped with AdSupport's class and method names, which caused App Store reviewers to misclassify applications. The next version of FirebaseAnalytics uses different class and method names, which should solve this issue.

**Comment by ryanwilson** [comment]
The new version of FirebaseAnalytics that uses different class and method names has been released. Thank you for your patience and please re-open this issue if this doesn't resolve the issue at hand.
