### ISSUE TITLE
Precondition failed: NSArray element failed to match the Swift Array Element type Expected FIRQueryDocumentSnapshot but found FIRQueryDocumentSnapshot: file

### ISSUE THREAD

**Issue by IniongunIsaac** [firebase/firebase-ios-sdk#5162]
### Step 0: Are you in the right place?

  Yes

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.2
  * Firebase SDK version: 6.19.0
  * Firebase Component: Firestore
  * Component version: 1.11.2
  * Installation method: `CocoaPods `

### [REQUIRED] Step 2: Describe the problem

I have firebase dependencies added in both my app's target and other internal targets.
I have a RemoteAPI internal target that handles everything that has to do with backend services and in this case, I'm relying solely on Firebase to power the app's backend. When I make a call to get data from firestore and decode it into my struct, the conversion fails for some reason. However, when I write the same piece of code in my main app target, it runs successfully but then breaks my entire application architecture.

It is worthy to note that I've passed in all firebase (auth, firestore, etc) instance from the main app target to the RemoteAPI target via Swinject dependency injection.
Podfile Screenshot:
![image](https://user-images.githubusercontent.com/21115262/77175625-3646d480-6ac3-11ea-8b71-8db15d79ee25.png)

#### Steps to reproduce:

Try to successfully use firestore in a project with multiple internal dependencies.

Precondition failed: NSArray element failed to match the Swift Array Element type
Expected FIRQueryDocumentSnapshot but found FIRQueryDocumentSnapshot: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-1100.2.280/swift/stdlib/public/core/ArrayBuffer.swift, line 354
2020-03-20 15:08:21.326763+0100 Buy Ticket[8998:300708] Precondition failed: NSArray element failed to match the Swift Array Element type
Expected FIRQueryDocumentSnapshot but found FIRQueryDocumentSnapshot: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-1100.2.280/swift/stdlib/public/core/ArrayBuffer.swift, line 354

#### Relevant Code:

```
func rxGetDocuments<T: Codable>(type: T.Type) -> Observable<[T]> {
        
        return Observable<[T]>.create { observer in
            
            self.getDocuments { snapshot, error in
                
                if let error = error {
                    observer.onError(error)
                } else if let snapshot = snapshot {
                    
                    let result = Result {
                        try snapshot.documents.compactMap {
                            try $0.data(as: type)
                        }
                    }

                    switch result {
                    case .success(let docs):
                        observer.onNext(docs)
                        observer.onCompleted()
                    case .failure(let error):
                        observer.onError(error)
                    }
                    
                }
            }
            return Disposables.create()
        }
        
    }
```

**Comment by wu-hui** [comment]
This is likely the same cause of #2085.

In short, you are probably getting two Firebase static libs linked, and hence two `FIRQueryDocumentSnapshot`.

**Comment by IniongunIsaac** [comment]
So is there a way around this? What can I do?

**Comment by morganchen12** [comment]
If `RemoteAPI` is a dependency of `Buy Ticket`, link Firestore into only the `RemoteAPI` target and not `Buy Ticket` and then expose the Firestore headers to `Buy Ticket` so it will still compile.

**Comment by wilhuff** [comment]
Also note that with CocoaPods 1.9 you may be able to use statically linked frameworks too:

```
use_frameworks! :linkage => :static
```

**Comment by IniongunIsaac** [comment]
> If `RemoteAPI` is a dependency of `Buy Ticket`, link Firestore into only the `RemoteAPI` target and not `Buy Ticket` and then expose the Firestore headers to `Buy Ticket` so it will still compile.

I understand the "link Firestore into only the RemoteAPI target" aspect but what I don't understand is how to "expose the Firestore headers to Buy Ticket" so please to you mind explaining that a bit more? A link on  how to do that can also be useful. Thank you

**Comment by IniongunIsaac** [comment]
> :linkage => :static

I just applied `:linkage => :static` on the targets in my Podfile but I got the same crash result. I'm I doing it wrongly? Please see attached

![image](https://user-images.githubusercontent.com/21115262/77204687-8e95ca80-6af3-11ea-8a48-72a7a86f93f5.png)

**Comment by paulb777** [comment]
Possibly a problem is linking the Firebase libraries into both a dynamic framework and the app.  The Firebase podspec's force them to be static no matter what is specified by `use_frameworks!`.

**Comment by IniongunIsaac** [comment]
> Possibly a problem is linking the Firebase libraries into both a dynamic framework and the app. The Firebase podspec's force them to be static no matter what is specified by `use_frameworks!`.

Yes that's the problem I think (based on all that I've gathered). Now trying to find a working solution to the problem not just for this project but for future projects as well. I'm thinking of returning the project to a single monolithic app without multiple internal targets but a solution to the current problem would be best suited.

**Comment by paulb777** [comment]
Three options come to mind:
- Use multiple static library framework targets instead of dynamic library framework targets
- Make all Firebase calls from one library
- Single monolithic app
