### ISSUE TITLE
Swiftlint error in FirebaseFirestoreSwift (FirestoreEncoder.swift)

### ISSUE THREAD

**Issue by kainjinez** [firebase/firebase-ios-sdk#5177]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 11.3.1 (11C505)
  * Firebase SDK version: Newest with `pod install`
  * Firebase Component: Firestore
  * Component version: Newest with `pod install`
  * Installation method: `CocoaPods` (select one)

#### Steps to reproduce:
I want to use custom object to add data to Firestore.
Via Get started here (https://firebase.google.com/docs/firestore/quickstart):
- I tried to add this to pod file
```
pod 'Firebase/Firestore'
# Optionally, include the Swift extensions if you're using Swift.
pod 'FirebaseFirestoreSwift'
```
- Quit project, use `pod install` to add `FirebaseFirestoreSwift`
- Open project with `.xcworkspace` then build app.
Then it shown error in `FirestoreEncoder.swift`

#### Screenshot
<img width="940" alt="Screen Shot 2020-03-24 at 6 40 54 PM" src="https://user-images.githubusercontent.com/15605788/77422081-7aa5dd80-6dff-11ea-9570-32f0c8bbe8cb.png">

I solved it by disable Swiftlint. But i think you should check it out. Thanks.

**Comment by wu-hui** [comment]
Hi,

Thanks for reporting the issue. Those force casts are actually required. We will push a change to disable the force_cast checks for these lines. 

We are not using swiftlint for our repository yet, so it's might be time to actually add some checks as well.

Thank you!

**Comment by morganchen12** [comment]
In the meantime, you can disable [SwiftLint checking for your dependencies](https://github.com/realm/SwiftLint/issues/1423).

**Comment by paulb777** [comment]
Closing for staleness. Please comment or open a new issue if it's still occurring.
