### ISSUE TITLE
FR: allow sending unsymbolicated stack traces in custom exception models.

### ISSUE THREAD

**Issue by barakwei** [firebase/firebase-ios-sdk#5182]
### Feature proposal

* Firebase Component: Crashlytics

This is in continuation to #4706 where I describe our use case in length.

First of all thanks for adding `[FIRCrashlytics recordExceptionModel:]` it will help us a lot. My problem with the current API is that in order to create the stack trace inside the exception model, I must use the `[FIRStackFrame initWithSymbol:file:line:]` method, so my stack trace must be symbolicated. As you know, we usually don't have symbols in production, so I would like to ask if the `[FIRStackFrame stackFrameWithAddress:]` can be made public, that way I could send my own unsymbolicated stack traces, which can be done now with the Fabric SDK.

**Comment by samedson** [comment]
Thank you for the feedback and info! Have a couple quesions:

 - How do you construct the unsymbolicated stacktrace?
    - Are you using [NSThread's callStackReturnAddresses](https://developer.apple.com/documentation/foundation/nsthread/1409565-callstackreturnaddresses?language=objc)? This is what the [recordError](https://firebase.google.com/docs/reference/ios/firebasecrashlytics/api/reference/Classes/FIRCrashlytics#-recorderror:) API uses to construct stacktraces
 - Do you find that the constructed stacktraces are successfully symbolicated in the Crashlytics backend?

**Comment by barakwei** [comment]
`NSThread` gives you the stack of the current thread. We use low level API to walk the stack of other threads and "manually" build the stacktrace.
The sent stacktraces, are symbolicated in the backend.

**Comment by Thomas-Vos** [comment]
In the old Crashlytics, `recordCustomExceptionName ` is used by [CrashKiOS](https://github.com/touchlab/CrashKiOS) to report exceptions in Kotlin code to Crashlytics.

The Kotlin framework generates a Kotlin exception which contains a stack trace. This exception and its stack trace are uploaded manually to Crashlytics. For more information see: https://github.com/touchlab/CrashKiOS

In the new Crashlytics it is not possible to record unsymbolicated stack traces. Could `[FIRStackFrame stackFrameWithAddress:]` be made public?

**Comment by samedson** [comment]
Ok thanks for the feedback folks. We'll work on addressing this in FIRCrashlytics.

**Comment by viteinfinite** [comment]
Hi @samedson, thank you for taking care about this! 
Do you have an update? Fabric should be closed now (well, it actually isn't) and this feature is still not implemented :(

**Comment by jiehu5114** [comment]
mark

**Comment by HJTXX** [comment]
mark

**Comment by ChenMengqi** [comment]
Still don't have this API

**Comment by elenadoty** [comment]
We've added this API to a branch that should be going out in the next release.

**Comment by paulb777** [comment]
Marked with the `6.32.0 - M79` milestone

**Comment by barakwei** [comment]
Thanks for making this work.
