### ISSUE TITLE
Firebase/messaging: Timeline for upstream messaging feature removal

### ISSUE THREAD

**Issue by urjitbhatia** [firebase/firebase-ios-sdk#5184]
Is there a timeline for fully deprecating upstream messages? The changelog doesn't say when the support will be removed

cc @blakeanderson @Kaspik

**Comment by morganchen12** [comment]
@chliangGoogle do you know when support will end? We should update the docs with the sunset date.

**Comment by Kaspik** [comment]
Our current issue right now is:
- we use direct channel for downstream messages (we can easily switch to APNS only) - so we see a lot of deprecated warnings
- we use upstream message to handle push notifications token registration - so we see another deprecated warning

Problem with the 2nd one is that for receiving upstream messages, our server needs to use XMPP (https://firebase.google.com/docs/cloud-messaging/server). But there is completely no info about deprecating that. So XCode says "switch to Firestore or any other servis" but documentation on Firebase Docs about upstream messages doesn't say anything - https://firebase.google.com/docs/cloud-messaging/receive-upstream

Thanks for any info about either sunset of this, or about options for us to migrate!

**Comment by chliangGoogle** [comment]
@Kaspik Thank you for reaching out. Sorry that we didn't provide enough information regarding the sunset. So based on your use case, you can store the token in your own way or talk to your server directly. If you can't build that now, you can also try other tools. You can also use Firebase real time database or cloud function to connect to your server in communications on handling tokens.

You can continue to use MCS APIs until we remove them from our client SDK, which will happen in the next Firebase breaking change release (we do not know the date yet). So as long as you don't update to the new version, you can continue to use the service. The MCS backend will not be shutdown yet to support older SDK versions but we still encourage you to move on from it as it can break in the future without much support.

Hope the information helps and let us know if you have more questions.
