### ISSUE TITLE
Firebase Does Not Properly Implement Swift Module Stability on iOS

### ISSUE THREAD

**Issue by ryan-cbs** [firebase/firebase-ios-sdk#5192]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: __11.4__
  * Firebase SDK version: __6.21.0__
  * Firebase Component: __ALL__ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: __6.21.0__
  * Installation method: `Carthage`

#### Steps to reproduce:
Add Firebase to Cartfile

`# Firebase
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" == 6.21.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashBinary.json" == 5.20.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAuthBinary.json" == 6.21.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseFirestoreBinary.json" == 6.21.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseRemoteConfigBinary.json" == 6.21.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebasePerformanceBinary.json" == 6.21.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseFunctionsBinary.json" == 6.21.0`

What happened? How can we make the problem occur?
Carthage build fails.

`*** Downloading FirebaseAnalyticsBinary.framework binary at "6.21.0"
Incompatible Swift version - framework was built with 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15) and the local version is 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29).`

#### Relevant Code:

I believe the simulator and device cases need to return 
`["SKIP_INSTALL=NO",
                "BUILD_LIBRARIES_FOR_DISTRIBUTION=YES"]`

In order to enable module stability for iOS.

https://github.com/firebase/firebase-ios-sdk/blob/master/ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift#L47
```
/// Arguments that should be included as part of the build process for each target platform.
    func extraArguments() -> [String] {
      let base = ["-sdk", rawValue]
      switch self {
      case .catalyst:
        return ["SKIP_INSTALL=NO",
                "BUILD_LIBRARIES_FOR_DISTRIBUTION=YES",
                "SUPPORTS_UIKITFORMAC=YES"]
      case .simulator, .device:
        // No extra arguments are required for simulator or device builds.
        return base
      }
    }
```

**Comment by paulb777** [comment]
@ryan-cbs Thanks for the report.

Some initial questions:
- Is going back to Xcode 11.3.1 or earlier a workaround?
- Why is Carthage checking the Swift build version when there is no Swift in the library?
- Is the problem only in FirebaseAnalytics (and FirebasePerformance) which have a different build process than the one you reference?

**Comment by paulb777** [comment]
I'm not able to reproduce with Xcode 11.4.1, so will need more information to progress.
