### ISSUE TITLE
Thats Weird, my dynamic link has no URL on iOS Help me

### ISSUE THREAD

**Issue by purnendu-roy** [firebase/firebase-ios-sdk#5200]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version:  pod 'Firebase/DynamicLinks', '5.11.0'
  * Firebase Component: DynamicLinks
  * Component version: 5.11.0
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem
  this is my https://xyz.page.link/refer dynamic link and it has deep-link to https://www.xyz.abc/refer and it doesn't work. previously like 4-5 months back it was working with the same code same process. please help me

#### Steps to reproduce:

I am getting this  <FIRDynamicLink: 0x28131e6c0, url [(null)], match type: unique, minimumAppVersion: N/A, match message: (null)>

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
func handleIncomingDynamicLink(_ dynamicLink: DynamicLink, _ parameter: String = ""){
        guard let url = dynamicLink.url else {
            print("Thats Weird, my dynamic link has no URL")
            return
        }
}
```

**Comment by ghus86** [comment]
yes there is something strange with dynamic links and iOS
https://github.com/firebase/firebase-ios-sdk/issues/4914
@dmandar @ryanwilson can you please help

the code stoped working in iOS 13.3 for newer devices
but in my iphone SE with the latest iOS it still works :/

**Comment by filipealva** [comment]
Guys, I'm having this issue too. But only when the users share the link through some very specific way, e.g. SMS. 

The link comes out without an URL an opens on the browser as this: 

```
https://ny9cs.app.goo.gl/s?socialDescription=Click+to+load+this+route+into+Circuit.&socialImageUrl&socialTitle=Circuit:+Columbus+Ga
```

**Comment by DracoRubi** [comment]
This issue happens to me, universal dynamic links aren't working in my application (even below iOS 13).

I've been trying to solve this contacting to support and in this issue: https://github.com/firebase/firebase-ios-sdk/issues/5122

But nothing. It still doesn't work.

**Comment by dmandar** [comment]
Please refer and contribute to issues #4914 and #5122 for latest updates.

**Comment by purnendu-roy** [comment]
Guys this issue for me still not solved.  Please help me. @firebase-ops @firebase-db-ci @firebase-ios-github-robot @firebase-promo

**Comment by morganchen12** [comment]
@purnendu-roy please file an issue at [Firebase Support](http://firebase.google.com/support) instead of spamming a bunch of GitHub users.
