### ISSUE TITLE
FirebaseInstallations will not work correctly with current version of Firebase Instance ID

### ISSUE THREAD

**Issue by JasonSa1993** [firebase/firebase-ios-sdk#5213]
###  Step 1: Describe your environment

  * Xcode version: 11.3.1 
  * Firebase SDK version: 6.21.0
  * Firebase Component: Firebase (FirebaseInstanceID & FirebaseInstallations)
  * Component version: 6.21.0
  * Installation method: CocoaPods
  * Deployment info: 13.1

#### Steps to reproduce:

After doing a pod update, the application throws an error and closes immediately, due to a conflict between the Firebase dependencies, which previously in the version (6.19.0) that we had did not occur.

> Terminating app due to uncaught exception 'com.firebase.installations', reason: 'FirebaseInstallations will not work correctly with current version of Firebase Instance ID. Please update your Firebase Instance ID version.'

It should be noted that it only happens since you did the pod update.

We also have a homemade pod that uses frameworks that in turn also use firebase within them, but all of this worked without problem before the update.

![image](https://user-images.githubusercontent.com/22629210/77704992-19f3dd80-6f84-11ea-91de-deda06eec892.png)

**Comment by paulb777** [comment]
@JasonSa1993 Thanks for the report.  Please share the `Podfile.lock` to help the investigation.

**Comment by sasojadrovski** [comment]
@paulb777 , 

I have the same issue with the Carthage installation. Please let me know what can I provided in order to help you resolve this as soon as possible.

Best regards,
Sasho

**Comment by paulb777** [comment]
Please share the project's `Podfile.lock`.

**Comment by sasojadrovski** [comment]
@paulb777, thanks for the prompt reply. I do not have a `Podfile.lock` file since I am using Carthage.

**Comment by JasonSa1993** [comment]
This is my Podfile.lock

confirm me if this is helpful?
regards

[Podfile.lock.zip](https://github.com/firebase/firebase-ios-sdk/files/4397935/Podfile.lock.zip)

**Comment by JasonSa1993** [comment]
we had to download the version to 6.14.0 to make our project work again

**Comment by paulb777** [comment]
@JasonSa1993 The Podfile.lock is for 6.14.0, but the issue is reported on 6.21.0?

@sasojadrovski I recommend you delete all Firebase frameworks from your project and reinstall the latest from scratch to insure the installation is consistent.

**Comment by sasojadrovski** [comment]
@paulb777 I was actually updating all dependencies in my project, meaning I deleted the Carthage folder and the `Cartfile.resolved` files. 

The frameworks in the project are added from the Carthage/Build folder so since I already deleted them, it’s like I added them all over again. Not sure if deleting and re-adding them again would make any difference 🙁

**Comment by JasonSa1993** [comment]
> @JasonSa1993 The Podfile.lock is for 6.14.0, but the issue is reported on 6.21.0?
> 
> @sasojadrovski I recommend you delete all Firebase frameworks from your project and reinstall the latest from scratch to insure the installation is consistent.

As I told you, currently I go down to version 6.14.0 so that my project will work again, that is, the problem occurs with version 6.21.0, 6.20.0, 6.19.0, 6.18.0 and so on until version 6.15 .0, already in the version that brings the Podfile.lock that I sent you, which is 6.14.0, the project works correctly.

It seems very strange to me that before updating I had the Firebase to 6.19.0, Update, it did not work, and I had to go back not to 6.19.0 but until 6.14.0 for it to work again.

I hope you i had explained better, for the moment I will have to leave the project in version 6.14.0 for it to compile and work.

Greetings.

**Comment by sasojadrovski** [comment]
Hey @paulb777,

It's a good thing you asked me to remove all Firebase frameworks and add them again, because by doing that I have realized that for some of the required frameworks, the project was using old references from the time when I was not using Carthage (since there was no official support) and the frameworks were added manually.

I corrected their paths, i.e. used the latest ones that were checked out and built using Carthage and now everything works!

Once again, thank you very much for opening my eyes, I really appreciate it! 

Cheers!

**Comment by paulb777** [comment]
@sasojadrovski Glad you got it working!

@JasonSa1993 There's a good chance there was something similarly wrong with your CocoaPods configuration when you updated to 6.21.0.  It's unlikely we'll be able to help without knowing more about the configuration that didn't work for you.

**Comment by yuzushioh** [comment]
## Step 1: Describe your environment
- Xcode version: 11.4
- Firebase SDK version: 6.21.0
- Firebase Component: 
  - FirebaseAnalytics
  - FirebaseAuthBinary
  - FirebaseDynamicLinks
  - FirebaseMessaging
  - FirebaseStorage
- Component version: 6.21.0
- Installation method: Carthage
- Deployment info: 13.0

## Step 2: Describe the problem
It gives me an error right after app launches. The description is 
`*** Terminating app due to uncaught exception 'com.firebase.installations', reason: 'FirebaseInstallations will not work correctly with current version of Firebase Instance ID. Please update your Firebase Instance ID version.'`

`Cartfile` is 
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" ~> 6.0.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAuthBinary.json" ~> 6.0.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseDynamicLinksBinary.json" ~> 6.0.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseMessagingBinary.json" ~> 6.0.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseStorageBinary.json" ~> 6.0.0
```

`Cartfile.resolved` is 
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" "6.21.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAuthBinary.json" "6.21.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseDynamicLinksBinary.json" "6.21.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseMessagingBinary.json" "6.21.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseStorageBinary.json" "6.21.0"
```

**Comment by paulb777** [comment]
@yuchenshi Please also remove all Firebase frameworks from the Xcode project and reinstall from the Carthage download.

**Comment by yuzushioh** [comment]
@paulb777 I tried it and it was the same result.

**Comment by yuzushioh** [comment]
For some reason it works fine now. I'm not sure about the cause.

**Comment by yuchenshi** [comment]
@paulb777 I think you meant to mention @yuzushioh instead of me (Yuchen). I have no context on this but good luck :)

**Comment by peymankh** [comment]
Having the same issue on 6.21.0.

Using the following with Carthage.

- FirebaseAnalytics
- FirebaseRemoteConfig

The FirebaseInstanceID seems to have been removed from 6.21.0 json binaries but it is showing up in FirebaseRemoteConfig binaries.

Checkout the contents of the binaries here.

https://dl.google.com/dl/firebase/ios/carthage/6.21.0/FirebaseAnalytics-211716d7b9c9b9b7.zip
https://dl.google.com/dl/firebase/ios/carthage/6.21.0/FirebaseRemoteConfig-3f2b8ebad8d5e1d0.zip

Previous versions, FirebaseInstanceID didn't use to even exist in RemoteConfig, surprised that it is now there.

**Comment by paulb777** [comment]
@peymankh FirebaseInstanceId was removed as a dependency of FirebaseAnalytics in 6.21.0, but remained a dependency of FirebaseRemoteConfig. FirebaseRemoteConfig had been previously relying upon the version installed with FirebaseAnalytics.

**Comment by peymankh** [comment]
@paulb777 that does make sense. 

My wildest guess is that Installations is looking for something inside InstanceID to verify it as a legit dependency BUT the version of InstanceID inside RemoteConfig is not providing that hence Installations throwing an exception. 

Could it be that we need to ensure InstanceID needs to be updated in RemoteConfig or elsewhere for that matter?

**Comment by paulb777** [comment]
As pointed out above, the most likely cause is that the Xcode project points to a mix of Firebase libraries from different releases.

**Comment by peymankh** [comment]
@paulb777 Yes that has been true in the past but I have tried this with a fresh install of Firebase and still getting the same issue. Obviously cleared all possible caches. DerivedData, Carthage Cache, etc. 

In fact if you look at the code [here](https://github.com/firebase/firebase-ios-sdk/blob/f0d6f5a9ff3af91406d11c79c04e2557c35eb747/FirebaseInstallations/Source/Library/FIRInstallations.m#L235), where the exception is generated, you can see that `FIRInstallations` is expecting a `useFIS` from `FIRInstanceID`. 

```ObjC
+ (BOOL)isIIDVersionCompatible {
  Class IIDClass = NSClassFromString(@"FIRInstanceID");
  if (IIDClass == nil) {
    // It is OK if there is no IID at all.
    return YES;
  }
  // We expect a compatible version having the method `+[FIRInstanceID usesFIS]` defined.
  BOOL isCompatibleVersion = [IIDClass respondsToSelector:NSSelectorFromString(@"usesFIS")];
  return isCompatibleVersion;
}
```

And if we look at `FIRInstanceID.h` [here](https://github.com/firebase/firebase-ios-sdk/blob/6.21.0/Firebase/InstanceID/Public/FIRInstanceID.h) We can see that `useFIS` function is not provided in the header file 🤷🏼‍♂️

**Comment by peymankh** [comment]
The files are from v6.21.0 tag.

**Comment by paulb777** [comment]
It's not in a header file, but it is defined [here](https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/InstanceID/FIRInstanceID+Private.m#L52).

An additional thing to clear are the references to Firebase frameworks in the Xcode project.  It's likely the Xcode project still has references to old frameworks.

**Comment by paulo-bc** [comment]
Adding this as it may help someone else:
In my case this issue started after removing CocoaPods from my project with `pod deintegrate`,  the solution was to add ` -ObjC` to `Other Linker Flags` in `Build Settings` (just like described in `https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md`). The flag was previously present in CocoaPods `.xcconfig` files that were removed when `deintegrate` was executed.

**Comment by alvincrisuy** [comment]
Hi, I still have the same issue after executing pod deintegrate.

**Comment by fallenleafLu** [comment]
I have the same issue after updating FirebaseInstallations to 1.1.1. I downgrade FirebaseInstallations to 1.1.0 and it works fine.

**Comment by catt-stefano** [comment]
I'm having the same problem, I'm using cocoapods. I'm using XCode 11.4.
I cleaned the project, I cleared derived data and I cleared cocoapod's cache (the global cache). I ran pod deintegrate, updated all firebase pods to the latest version.
I don't know if it might help but I'm also using the Firebase Crashlytics beta.

If I browse the code in Pods/FirebaseInstanceID and look for the `FIRInstanceID+Private.m` file, I can see that the code:
```
+ (BOOL)usesFIS {
  return YES;
}
```
Nonetheless, the app still crashes as soon as it configures the FirebaseApp

**Comment by Saranjithpk** [comment]
We have downgraded Firebase Version to 6.14.0 to make our project work again.

**Comment by peymankh** [comment]
Same here.

**Comment by Mobilityappsinc** [comment]
Steps to fix:

1- pod deintegrate
2- pod cache clean --all
3- Pod install

4- in Podfile put pod 'Firebase' without specifying any version, and for you to install the latest 6.22.0

5- When compiling the application, a FirebaseInstanceID error will appear

6- Open Podfile and specify pod 'FirebaseInstallations', '1.1.0'

7- Pod update

8- re compile and run the project

**Comment by JasonSa1993** [comment]
Steps to fix:

1- pod deintegrate
2- pod cache clean --all
3- Pod install

4- in Podfile put pod 'Firebase' without specifying any version, and for you to install the latest 6.22.0

5- When compiling the application, a FirebaseInstanceID error will appear

6- Open Podfile and specify pod 'FirebaseInstallations', '1.1.0'

7- Pod update

8- re compile and run the project

Regards

**Comment by JasonSa1993** [comment]
Steps to fix:

1- pod deintegrate

2- pod cache clean --all

3- in Podfile put pod 'Firebase' without specifying any version, and for you to install the latest 6.22.0

4- Pod install

5- When compiling the application, a FirebaseInstanceID error will appear

6- Open Podfile and specify pod 'FirebaseInstallations', '1.1.0'

7- Pod update

8- re compile and run the project

Regards

**Comment by dpmedeiros** [comment]
Hi, I am having this problem as well.

Compiling against tvOS 13.4, using static linking. Have to set frameworks to optional to get past fatal dyld errors at app startup

**Comment by maksymmalyhin** [comment]
@dpmedeiros As mentioned above Firebase Installations SDK expects [[FIRInstanceID usesFIS]](https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/InstanceID/FIRInstanceID+Private.m#L52) to be defined to validate a compatibility of Firebase Instance ID SDK. I can see a couple reasons why this check may fail:

1. An old version of FirebaseInstanceID is locked in Podfile. **Solution:** FirebaseInstanceID version should be updated to 4.3.0 or higher
2. An old version of FirebaseInstanceID is bundled into another framework. In this case you should see the following warnings in the console:
```
objc[40943]: Class FIRInstanceID is implemented in both
~/Library/Developer/Xcode/DerivedData/FrameworkTest-apqjxlyrxvkbhhafhaypsbdquref/Build/Products/Debug-iphonesimulator/DynamicFramework.framework/DynamicFramework
(0x10b2a87f8) and
~/Library/Developer/CoreSimulator/Devices/4821F959-24A6-4D78-A102-4C5703103D99/data/Containers/Bundle/Application/F017D210-113A-4DAF-9E17-BDE455E71E06/FrameworkTest.app/FrameworkTest
(0x10ad2d348). One of the two will be used. Which one is undefined.
```
**Solution:** This issue should be solved by the framework developer. Firebase should be used as a dependency and never be bundled into another framework. The framework should be removed from the app until the issue is fixed.

3. `-ObjC` flag is not set in `Other Linker Flags` in `Build Settings` of your application target. Usually Cocoapods sets this flag by default, but it may be missing in some cases.  In this case you may see other random crashes with `unrecognized selector` exception for methods that are defined in Objective C categories.  **Solution:** make sure the `-ObjC` flag is set.

If you have a different kind of problem please share a sample project where the issue is reproducible so we can investigate and suggest a solution.
