### ISSUE TITLE
[Ignore, false alarm]iOS RTDB crashes my app every time at launch

### ISSUE THREAD

**Issue by coolcool1994** [firebase/firebase-ios-sdk#5215]
PLEASE IGNORE THIS POST. YOU MAY DELETE IT. THERE IS NO PROBLEM WITH RTDB. THIS WAS TOTALLY MY FAULT NOT RTDB'S. THE BUG HAPPENED BECAUSE OF MY LOGIC AND I CHANGED THE DICTIONARY VALUE INTO AN INT, CAUSING BELOW CRASH as I tried to iterate through int as if it is a dictionary lol. If you are a Google Developer, please delete this post :)

I have a child field changed listener, and when one of the child field changed, my app crashed with the error. Every time I run/open the app again, it crashes with the same error.

The error shown in Xcode is:
2020-03-27 04:54:06.877411-0700 Project[] -[__NSCFNumber countByEnumeratingWithState:objects:count:]: unrecognized selector sent to instance 0x283a3bee0
2020-03-27 04:54:06.878218-0700 Project[] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber countByEnumeratingWithState:objects:count:]: unrecognized selector sent to instance 0x283a3bee0'

Screenshots:
<img width="1207" alt="Screen Shot 2020-03-27 at 4 55 52 AM" src="https://user-images.githubusercontent.com/23645054/77754075-dd59cd80-6fe7-11ea-8998-1ebe394b2e74.png">
<img width="1194" alt="Screen Shot 2020-03-27 at 4 56 14 AM" src="https://user-images.githubusercontent.com/23645054/77754078-ddf26400-6fe7-11ea-86da-6ffeae63e40e.png">
<img width="1197" alt="Screen Shot 2020-03-27 at 4 56 18 AM" src="https://user-images.githubusercontent.com/23645054/77754090-e054be00-6fe7-11ea-83c5-5a20584cbcd7.png">
<img width="1204" alt="Screen Shot 2020-03-27 at 4 56 22 AM" src="https://user-images.githubusercontent.com/23645054/77754093-e2b71800-6fe7-11ea-96b7-116cf956cc39.png">
<img width="1181" alt="Screen Shot 2020-03-27 at 4 56 29 AM" src="https://user-images.githubusercontent.com/23645054/77754102-e5197200-6fe7-11ea-9ebf-017c8684ff74.png">
<img width="1086" alt="Screen Shot 2020-03-27 at 4 56 47 AM" src="https://user-images.githubusercontent.com/23645054/77754110-e6e33580-6fe7-11ea-8ccd-f29bbd6be9cc.png">

**Comment by maksymmalyhin** [comment]
@coolcool1994 Thank you for sharing your issue and updating the ticket once you figured out the reason. I hope the ticket will help other developers that encounter similar issues.
