### ISSUE TITLE
Remove Messaging direct channel and Upstream API at next major change release

### ISSUE THREAD

**Issue by chliangGoogle** [firebase/firebase-ios-sdk#5216]
Firebase Messaging direct channel and upstream API have been deprecated and will be removed at the Firebase 7 major release.

**Comment by rosariopfernandes** [comment]
Hi @chliangGoogle 
I'm curious: Why did upstream message get removed from the iOS SDK, but is [still available on Android](https://firebase.google.com/docs/cloud-messaging/android/upstream)?

**Comment by chliangGoogle** [comment]
Because upstream message uses direct channel. It is available in Android because it's the default channel. Now Firebase Messaging iOS only uses APNS channel for message delivery.

**Comment by rosariopfernandes** [comment]
@chliangGoogle Ah, I see.. Thanks for clarifying.
