### ISSUE TITLE
Firebase not respecting Cocoapods configuration setting

### ISSUE THREAD

**Issue by Axadiw** [firebase/firebase-ios-sdk#5217]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.21.0
  * Firebase Component: Crashlytics
  * Component version: 4.0.0-beta.6
  * Installation method: `CocoaPods`

#### Steps to reproduce:

Add Crashlytics to Podfile
run `pod install`
Run `Archive` action in Xcode

#### Relevant Code:

I've added 

```pod 'Firebase/Crashlytics', '6.21.0', :configurations => ['Debug_dev', 'Release_dev']```

to my Podfile, in order to have Crashlytics added only to selected 'Debug_dev' and 'Release_dev' configurations, but instead they are visible in the built .ipa file.

It looks like a bug for me, rest of the pods that are filtered out using `configurations` keyword are not visible in the result .ipa file

**Comment by paulb777** [comment]
@Axadiw This might be a CocoaPods subspec issue.  Does specifying the FirebaseCrashlytics pod directly work instead of via the Firebase subspec?

`pod 'FirebaseCrashlytics', '4.0.0-beta.6', :configurations => ['Debug_dev', 'Release_dev']`

**Comment by Axadiw** [comment]
Nope, the same issue with `FirebaseCrashlytics` pod. I'll post this issue on cocoapods repo then.

Thanks!

**Comment by morganchen12** [comment]
Closing in favor of the CocoaPods issue.
