### ISSUE TITLE
Link email sign-in with an account crash

### ISSUE THREAD

**Issue by mfrohman123** [firebase/firebase-ios-sdk#5222]
Hello,

I am attempting to link the Email Auth Provider with an existing account, and it crashes with the error:

"Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSURLComponents initWithString:]: nil URLString parameter'"

I am using Firebase iOS with version 6.20.0 with Xcode 11.2.1. Below is the code:

`let email = Auth.auth().currentUser?.email
        
        //authenticates with firebase
        let credential = EmailAuthProvider.credential(withEmail: email!, link: newPassword.text!)
        
        //links accounts
        Auth.auth().currentUser?.link(with: credential, completion: { (authResult, error) in
            
            if error != nil {
                // failed...
            } else {
                // success...
            }
        })`

**Comment by ryanwilson** [comment]
Hi @mfrohman123 - sorry you're facing this issue. Can you please provide the full stacktrace of the crash? It's tough to tell exactly where the bug is occurring just by the code sample.

Thanks!

**Comment by mfrohman123** [comment]
Yep, @ryanwilson it is below. Please let me know if I can provide anything more!

2020-04-02 11:56:05.739467-0400 Resistance [40318:27105514] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSURLComponents initWithString:]: nil URLString parameter'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c4f02e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50b97b20 objc_exception_throw + 48
	2   Foundation                          0x00007fff2578c672 -[__NSConcreteURLComponents URL] + 0
	3   Foundation                          0x00007fff2578e160 +[NSURLComponents componentsWithString:] + 45
	4   Resistance                         0x00000001092e5b52 +[FIRAuthWebUtils parseURL:] + 98
	5   Resistance                         0x000000010930d6a8 __56-[FIRUser linkAndRetrieveDataWithCredential:completion:]_block_invoke_3 + 440
	6   Resistance                         0x000000010930c0e2 __51-[FIRUser internalGetTokenForcingRefresh:callback:]_block_invoke + 338
	7   Resistance                         0x00000001092ff170 __65-[FIRSecureTokenService fetchAccessTokenForcingRefresh:callback:]_block_invoke_2 + 160
	8   Resistance                         0x00000001092ff8e8 __44-[FIRSecureTokenService requestAccessToken:]_block_invoke + 488
	9   Resistance                         0x00000001092d2060 __56-[FIRAuthBackendRPCImplementation secureToken:callback:]_block_invoke + 128
	10  Resistance                         0x00000001092d4262 __69-[FIRAuthBackendRPCImplementation postWithRequest:response:callback:]_block_invoke + 2658
	11  GTMSessionFetcher                   0x000000010c66d6c3 __71-[GTMSessionFetcher invokeFetchCallbacksOnCallbackQueueWithData:error:]_block_invoke + 51
	12  GTMSessionFetcher                   0x000000010c66d3c8 __66-[GTMSessionFetcher invokeOnCallbackQueue:afterUserStopped:block:]_block_invoke + 552
	13  libdispatch.dylib                   0x000000010e7fddd4 _dispatch_call_block_and_release + 12
	14  libdispatch.dylib                   0x000000010e7fed48 _dispatch_client_callout + 8
	15  libdispatch.dylib                   0x000000010e805799 _dispatch_lane_serial_drain + 1214
	16  libdispatch.dylib                   0x000000010e80617f _dispatch_lane_invoke + 422
	17  libdispatch.dylib                   0x000000010e811a4e _dispatch_workloop_worker_thread + 719
	18  libsystem_pthread.dylib             0x00007fff51bfd611 _pthread_wqthread + 421
	19  libsystem_pthread.dylib             0x00007fff51bfd3fd start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by renkelvin** [comment]
`let credential = EmailAuthProvider.credential(withEmail: email!, **link**: newPassword.text!)`
Hi @mfrohman123 , you're calling sign in with email link instead of signing in with email password.

**Comment by mfrohman123** [comment]
That was the fix! I must've totally overlooked the parameters @renkelvin
