### ISSUE TITLE
 _GAD_GADWebKitWebViewController_arm64_7_55_1   It will jam the main thread for a while

### ISSUE THREAD

**Issue by wangjunhua1** [firebase/firebase-ios-sdk#5230]
It will jam the main thread for a while 
pod 'Google-Mobile-Ads-SDK', '7.55.1'
Xcode version :11.3.1
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/11474284/77979660-d01a4700-7337-11ea-9e6c-8457973022bd.png">

<img width="585" alt="image" src="https://user-images.githubusercontent.com/11474284/77979746-1b345a00-7338-11ea-9165-a046859e24b9.png">

**Comment by morganchen12** [comment]
How long does it stall the main thread? It looks like the code here is just initializing a webview, which should not take very long on newer devices.

**Comment by wangjunhua1** [comment]
More than 3 s

**Comment by morganchen12** [comment]
Does this only occur on older devices?
