### ISSUE TITLE
 _GAD_GADWebViewJSContext_arm64_7_55_1  There are some notsmooth frames in the main thread

### ISSUE THREAD

**Issue by wangjunhua1** [firebase/firebase-ios-sdk#5231]
pod 'Google-Mobile-Ads-SDK', '7.55.1'
<img width="966" alt="image" src="https://user-images.githubusercontent.com/11474284/77979906-7c5c2d80-7338-11ea-9e83-9c8de410a8da.png">

The details are as follows：
libobjc.A.dylib | method_getName + 4
-- | --
1 UIKitCore | __classWithImplementationOfSelector + 124
2 UIKitCore | _PushNextClassForSettingIMP + 332
3 UIKitCore | ___workaround10030904InvokeWithTarget_block_invoke + 28
4 UIKitCore | +[UIView _performSystemAppearanceModifications:] + 68
5 UIKitCore | _workaround10030904InvokeWithTarget + 720
6 UIKitCore | _applyInvocationsToTarget + 1248
7 UIKitCore | +[_UIAppearance _applyInvocationsTo:window:matchingSelector:onlySystemInvocations:] + 1528
8 UIKitCore | ___88-[UIView(Internal) _performUpdatesForPossibleChangesOfIdiom:orScreen:traverseHierarchy:]_block_invoke + 76
9 UIKitCore | -[UIView(Internal) _performUpdatesForPossibleChangesOfIdiom:orScreen:traverseHierarchy:] + 200
10 UIKitCore | -[UIView(Internal) _didChangeFromIdiomOnScreen:traverseHierarchy:] + 176
11 UIKitCore | -[UIView(Internal) _didMoveFromWindow:toWindow:] + 1328
12 UIKitCore | ___45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke + 156
13 UIKitCore | -[UIView(Hierarchy) _postMovedFromSuperview:] + 760
14 UIKitCore | -[UIView(Internal) _addSubview:positioned:relativeTo:] + 1740
15 BluedInternational | _GAD_GADWebViewJSContext_arm64_7_55_1 + 624
16 BluedInternational | _GADDispatchAsyncSafeMainQueue + 56
17 BluedInternational | _GAD_GADWebViewJSContext_arm64_7_55_1 + 304
18 BluedInternational | _GAD_GADSDKCoreContext_arm64_7_55_1 + 468
19 BluedInternational | _GADLoadSDKCoreSynchronously + 4892
20 libdispatch.dylib | __dispatch_call_block_and_release + 24
21 libdispatch.dylib | __dispatch_client_callout + 16
22 libdispatch.dylib | __dispatch_main_queue_callback_4CF$VARIANT$mp + 1068
23 CoreFoundation | 0x000000018fbaa000 + 699168
24 CoreFoundation | 0x000000018fbaa000 + 678488
25 CoreFoundation | CFRunLoopRunSpecific + 436
26 GraphicsServices | GSEventRunModal + 104
27 UIKitCore | UIApplicationMain + 212
28 BluedInternational | main (main.m:13)
29 libdyld.dylib | _start + 4

**Comment by morganchen12** [comment]
Do you mean the view update calls are causing frame drops?

**Comment by wangjunhua1** [comment]
> Do you mean the view update calls are causing frame drops?
YES

**Comment by morganchen12** [comment]
If you're able to reproduce this, can you profile the view update via Instruments to see what's taking up the most time? Since these are calls to UIView, they cannot be moved off of the main thread. The only way to reduce the amount of stuttering is to try to distribute the view updates across more runloop invocations or reduce the number of view updates.
