### ISSUE TITLE
Firestore: After a while snapshotListener does not get called in newer SDK anymore

### ISSUE THREAD

**Issue by Ninakadin** [firebase/firebase-ios-sdk#5235]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4
  * Firebase SDK version: 6.21.0
  * Firebase Component: All (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 6.21.0
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem
I discovered a buggy behaviour since I updated to the latest SDK (6.21.0) a few days ago using 'pod update'. And I was able to confirm that the problem disappeared, as soon as I switched back to 6.16.0.

What happens: I have two apps communicating via a field in a document. Therefore both apps add a snaphotListener to this document. After a longer passive period of time without changes to this document (> 30 mins, iPads not going into sleep mode), the listener of app 1 does not get called anymore when app 2 changes the document. This only changes, when app 1 makes changes to the document itself. Then the listener is "back in game" and gets called again if app 2 makes any change.

I verified in Firebase console that the document in fact was changed. The app no longer being called when the document is changed is a mature app in AppStore since half a year.

#### Steps to reproduce:

I'm not sure how to make this generally reproduceable. It's about adding a listener, then not changing the document for quite a while. The app must stay open and the iOS device must be set to "Never" sleep.

#### Relevant Code:
	mainDocumentListener = db.collection(kSessionsCollection).document(sessionID).addSnapshotListener { documentSnapshot, error in
		guard let document = documentSnapshot else
		{
			print("### Error fetching document: \(error!)")
			return
		}
		if let session = document.data()
		{
			self.checkForRemoteEvents(session)	// Does not get called anymore
		}

Attached is the podfile working and the podfile used (and executed 'pod update') when problem shows.

[Podfile-making-problems.txt](https://github.com/firebase/firebase-ios-sdk/files/4411025/Podfile-making-problems.txt)
[Podfile-working.txt](https://github.com/firebase/firebase-ios-sdk/files/4411026/Podfile-working.txt)

**Comment by dconeybe** [comment]
Hello @Ninakadin and thank you for reporting this issue.  I'm sorry it is causing trouble for you.

I will be looking into this and I'm going to start by trying to reproduce.  If you happen to have an app that I could use to reproduce the issue then please show it to me so I can use it as well.

Also, it sounds like you are reporting the issue on real devices. Do you know if you see this issue with the simulator as well?

**Comment by morganchen12** [comment]
Also, if you're able to reproduce this locally, can you share your app's Firebase logs with [verbose logging enabled](https://firebase.google.com/docs/reference/ios/firebasecore/api/reference/Classes/FIRConfiguration#/c:objc(cs)FIRConfiguration(im)setLoggerLevel:)? Non-Firebase logs can be omitted.

**Comment by Ninakadin** [comment]
No, we found that problem when doing long term acceptance tests on real devices.
I was glad everything worked fine again, when downgrading the Firebase/Firestore sdk.
But I can for test purposes create a buggy app again and commit the logs. Will take a day.

**Comment by dconeybe** [comment]
FYI I was not able to reproduce the issue. 

Here is what I tried.  I created the smallest possible iOS application where the only interesting code is the following in my `AppDelegate` class:

```swift
  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    FirebaseApp.configure()
    let db = Firestore.firestore()

    db.collection("restaurants").document("1YkESDBLGz9vEmphIUFJ").addSnapshotListener { [unowned self] (snapshot, error) in
      guard let snapshot = snapshot else {
        print("zzyzx ERROR: fetching snapshot failed: \(error!)")
        return
      }
      print("zzyzx \(snapshot.data())")
    }

    return true
  }
```

I launched the app from Xcode.  Then I waited for 30 minutes.  The screen remained turned on the entire time.  Then, I made a change to the document in the Firebase console, and the `print` statement was correctly executed.

My dev environment is:
- Xcode 11.3.1
- iPhone 6S with iOS 13.2

And here is the "test app" I used: https://github.com/dconeybe/firestore-ios-headless-app

If you can provide a reproducible scenario, even if it is not 100% reproducible, please let us know so that we can investigate further.  Logs would be helpful also.  Otherwise, I'll see if I can think of anything else to try.

**Comment by Ninakadin** [comment]
Sorry to have bothered you. When making the test setup with verbose mode and new SDK again, it turned out, there was a miscommunication between QA and Devs. The problem was located elsewhere.

**Comment by dconeybe** [comment]
No problem.  Thank you for closing this issue and letting us know what happened.  All the best!
