### ISSUE TITLE
Firebase Storage Security Rule Bug when setting request.resource.size

### ISSUE THREAD

**Issue by coolcool1994** [firebase/firebase-ios-sdk#5260]
```
match /images/{imageId} {
      allow read, write: if request.auth != null && request.resource.size < 5.0 * 1024.0 * 1024.0;
    }
```
if I set request.resource.size < 5.0 * 1024.0 * 1024.0 for Firebase Storage security rule in the console, and then upload an 1.5MB image with iOS SDK, image gets uploaded. But the downloadURLWithCompletion does not succeed - the error returned is "NSLocalizedDescription=User does not have permission to access". When I delete the image using [storageRef deleteWithCompletion], this fails as well with the same error User does not have permission to access. But if I remove request.resource.size < 5.0 * 1024.0 * 1024.0 from the security rule, everything works just fine. I can reproduce this every time, and this is a bug.

**Comment by coolcool1994** [comment]
I can also put request.resource.contentType.matches('image/.*') instead of request.resource.size < 5.0 * 1024.0 * 1024.0, the image doesn't even get uploaded.

**Comment by coolcool1994** [comment]
I know the security rule is the only issue here because I implemented the security rule today and everything worked fine before. Also if I do not call request.resource.etc. in the security rule, everything just works fine too. Very weird.

**Comment by schmidt-sebastian** [comment]
@coolcool1994 Thanks for filing this.

`request.resource.size` applies only to the file you are uploading (the file that is part of the request). In a read or delete request, you will want to use `resource.size` to refer to the existing file.
