### ISSUE TITLE
Error: 'GoogleDataTransport/GDTCORConsoleLogger.h' file not found

### ISSUE THREAD

**Issue by shtnkgm** [firebase/firebase-ios-sdk#5280]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3
  * Firebase SDK version: 6.21.0
  * Firebase Component: Core
  * Component version: 6.21.0
  * Installation method: `CocoaPods`（1.8.4）

### [REQUIRED] Step 2: Describe the problem
The following error occurred.
> 'GoogleDataTransport/GDTCORConsoleLogger.h' file not found

![image](https://user-images.githubusercontent.com/16917697/78403791-f68dfa00-7637-11ea-9206-0ae99394e7b4.png)

`Pods/GoogleDataTransport/` directory is empty.

#### Steps to reproduce:

 1. make Podfile to install Firebase/Core
 2. `pod install` 
 3. open .xcworkspace file
 4. build project

#### Relevant Code:

Here is the repository that contains the minimal code to reproduce the error.
https://github.com/shtnkgm/FirebaseIssue

This is my Podfile.
```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseIssue' do
  use_frameworks!

  pod 'Firebase/Core'

end
```

**Comment by shtnkgm** [comment]
I solved this problem myself.
The header file was imported successfully by executing the following command.

```bash
sudo rm -fr ~/Library/Caches/CocoaPods/
pod install
```

**Comment by morganchen12** [comment]
Thanks for updating! Feel free to comment here if the issue resurfaces and we'll try to help.
