### ISSUE TITLE
 Insecure Communication: Overly Broad Certificate Trust

### ISSUE THREAD

**Issue by divyaKalusulingam** [firebase/firebase-ios-sdk#5288]
We have used 'Firebase/Core' 6.3.1 podfile as per our need. Here We have attached the image  for your reference:  Kindly help us asap.

<img width="1028" alt="Screenshot 2020-04-05 at 3 35 47 PM" src="https://user-images.githubusercontent.com/63187061/78472118-1581ae80-7754-11ea-847c-52743782bba8.png">

<img width="1000" alt="Screenshot 2020-04-05 at 4 02 21 PM" src="https://user-images.githubusercontent.com/63187061/78472494-e6207100-7756-11ea-8d02-b796e439b45e.png">

<img width="1009" alt="Screenshot 2020-04-05 at 3 36 26 PM" src="https://user-images.githubusercontent.com/63187061/78472123-1adef900-7754-11ea-8cc0-dea4767428c2.png">

**Comment by paulb777** [comment]
Please `pod update` to the latest release.  The referenced code (in FirebaseInstanceID) is no longer a dependency of `Firebase/Core`.
