### ISSUE TITLE
Type Mismatch: Signed to Unsigned

### ISSUE THREAD

**Issue by divyaKalusulingam** [firebase/firebase-ios-sdk#5289]
We have used the 'Firebase/Core' 4.2.5  podfile as per our swift need . Here We have attached the image for your reference: Kindly help us asap.

**Issue Summary:**
The function encode:() in FIRInstanceIDStringEncoding.m is declared to return an unsigned value, but on line 138 it returns a signed value.The function is declared to return an unsigned number but returns a signed value.

<img width="995" alt="Screenshot 2020-04-05 at 9 22 39 PM" src="https://user-images.githubusercontent.com/63187061/78503340-9e640e80-7783-11ea-9a31-62b83d416026.png">
<img width="999" alt="Screenshot 2020-04-05 at 9 22 48 PM" src="https://user-images.githubusercontent.com/63187061/78503341-a15eff00-7783-11ea-8a44-cd0c1afd2780.png">

**Comment by paulb777** [comment]
The referenced file `FIRInstanceIDStringEncoding.m` was deleted in February.  Please run `pod update` to update your installation.
