### ISSUE TITLE
Type Mismatch: Negative to Unsigned

### ISSUE THREAD

**Issue by divyaKalusulingam** [firebase/firebase-ios-sdk#5290]
We have used the FireBase podfile as per our Need. Here we have attached the image for your reference. Kindly help us asap.

**Issue Summary:**
The function init() in **GDTCORUploadCoordinator.m** is declared to return an unsigned value, but on line 45 it returns a negative value.The function is declared to return an unsigned value, but in some cases it returns a negative value.

**Environment:**

  * Xcode version: _____ 11.3.1 
  * Firebase SDK version: _____ 3.0.1 
  * Firebase Component: _____ ( Core, GoogleDataTransport)
  * Installation method: `CocoaPods 

 
<img width="1018" alt="Screenshot 2020-04-05 at 9 44 45 PM" src="https://user-images.githubusercontent.com/63187061/78503829-b4270300-7786-11ea-8b3e-1a03c2debee3.png">
<img width="985" alt="Screenshot 2020-04-05 at 9 44 53 PM" src="https://user-images.githubusercontent.com/63187061/78503832-b9844d80-7786-11ea-8264-7e2c08494e5f.png">

**Comment by paulb777** [comment]
I don't see the referenced code in the [current source](https://github.com/firebase/firebase-ios-sdk/blob/master/GoogleDataTransport/GDTCORLibrary/GDTCORUploadCoordinator.m).  And it's not clear what version 3.0.1 refers to.  Please check `Podfile.lock` to find the correct versions for your installation.

**Comment by divyaKalusulingam** [comment]
hi paulb777:

 GoogleDataTransport Version is 3.0.1

**Comment by paulb777** [comment]
Thanks @divyaKalusulingam. The issue looks resolved in the current version of 5.1.0
