### ISSUE TITLE
Privacy Violation: HTTP GET

### ISSUE THREAD

**Issue by divyaKalusulingam** [firebase/firebase-ios-sdk#5291]
We have used the Firebase Podfile as per our need, Here we have attached the Screenshots for your Reference, Kindly help us asap.

**Issue Summary:** 

The call to sessionIDFromAsyncGETRequest:completionHandler:() at GULNetwork.m line 206 uses the HTTP GET instead of POST method to send data to the server.The identified call uses the HTTP GET instead of POST method to send data to the server.

 Step 1: Describe your environment

  * Xcode version:  11.3.1 
  * Firebase SDK version:  6.3.1
  * Firebase Component: (Googleutilities - Version : 6.3.1 )
   * Installation method: `CocoaPods'

Step 2: Describe the problem
<img width="1015" alt="Screenshot 2020-04-05 at 10 20 45 PM" src="https://user-images.githubusercontent.com/63187061/78504581-ceafab00-778b-11ea-84c8-3566c1ff920b.png">

**Recommendation**
Use the HTTP POST method in conjunction with HTTPS to send data to the server. This limits the exposed data in the request to the URL. Request parameters should be sent in the POST body. Sensitive data should not be placed in URL request parameters as they will still be exposed in HTTP POST requests.
Avoid using NSURLRequest and explicitly set the HTTP method to POST when making HTTP requests.

**Comment by paulb777** [comment]
This GoogleUtilities API is currently only used by FirebaseAnalytics so we'll investigate with that team.

**Comment by paulb777** [comment]
The Analytics team took a look and verified that `GET` is only used for fetching data. `POST` is always used for sending data.
