### ISSUE TITLE
Insecure Storage: Unspecified Keychain Access Policy

### ISSUE THREAD

**Issue by divyaKalusulingam** [firebase/firebase-ios-sdk#5292]
We have used the  Firebase Podfile For our need. Here we  have attached the Screenshots for your reference. Kindly help us asap.

**Step 1: Describe your environment**

  * Xcode version:  11.3.1 
  * Firebase SDK version: 6.3.1 
  * Firebase Component:  FirebaseInstanceID
  * Installation method: `CocoaPods '

**Step 2: Describe the problem**

On line 100 of FIRInstanceIDKeychain.m, the method ^{}() stores data in the Keychain without specifying an accessibility level.The identified method stores data in the Keychain without specifying an accessibility level.

<img width="1065" alt="Screenshot 2020-04-05 at 10 52 06 PM" src="https://user-images.githubusercontent.com/63187061/78505285-29e39c80-7790-11ea-8409-50e7dff40053.png">
<img width="1046" alt="Screenshot 2020-04-05 at 10 52 23 PM" src="https://user-images.githubusercontent.com/63187061/78505286-2bad6000-7790-11ea-8821-86fef2d76c4e.png">

**Comment by paulb777** [comment]
Please label with the correct version and check the current sources at https://github.com/firebase/firebase-ios-sdk before filing issues like this.

**Comment by wilhuff** [comment]
FIRInstanceIDKeychain is a utility used by other parts of the code, and those callers are responsible for specifying this attribute. For example, [here](https://github.com/firebase/firebase-ios-sdk/blob/e4456c011b0724257d26e8d5ff93d09c6e81d53f/Firebase/InstanceID/FIRInstanceIDAuthKeyChain.m#L197). If you have a specific concern about a caller that's not specifying the attribute, please let us know.
