### ISSUE TITLE
Privacy Violation

### ISSUE THREAD

**Issue by divyaKalusulingam** [firebase/firebase-ios-sdk#5293]
We have used the FireBase podfile as per our Need .Here we have attached the Screenshots for your reference. Kindly help us asap.

**Step 1: Describe your environment**

  * Xcode version: 11.3.1 
  * Firebase SDK version: 6.3.1 
  * Firebase Component: FIrebaseinstanceID version : 4.2.5 
  * Installation method: `CocoaPods' 

**Step 2: Describe the problem**

The function checkinWithExistingCheckin:completion:() in FIRInstanceIDCheckinService.m mishandles confidential information on line 92. The program could compromise user privacy.The identified function mishandles confidential information. This program could compromise user privacy.

<img width="1014" alt="Screenshot 2020-04-05 at 11 36 24 PM" src="https://user-images.githubusercontent.com/63187061/78506367-ac6f5a80-7796-11ea-9672-a50d59398dbd.png">

<img width="1020" alt="Screenshot 2020-04-05 at 11 37 10 PM" src="https://user-images.githubusercontent.com/63187061/78506342-919ce600-7796-11ea-9c0d-d9c503938de6.png">

Other areas of concern for maintaining the privacy of user data arise when a device has been lost or stolen. Once in possession of an iOS device, an attacker may access a great deal of data by connecting the device by USB. Files such as iOS Property Lists (plists) and SQLite databases are easily accessed and can disclose personal information. As a general rule, privacy related information should not be stored unprotected on the file system.

<img width="1016" alt="Screenshot 2020-04-05 at 11 40 26 PM" src="https://user-images.githubusercontent.com/63187061/78506403-e2acda00-7796-11ea-90b7-945c01a41f31.png">

**Comment by paulb777** [comment]
The current version of FirebaseInstanceID is 4.3.2.

**Comment by paulb777** [comment]
While the referenced FIRInstanceIDCheckInPreferences.m code has substantially changed, the `setHTTPBody` call is still at line 92 of FIRInstanceIDCheckinService.m. 

We'll take a look.

**Comment by chliangGoogle** [comment]
@divyaKalusulingam  thanks for filing the request, we are in the process of removing checkin as it is no longer used to login critical user information. In the meantime, can you update your description based on the latest code base as some info is outdated.
