### ISSUE TITLE
VeraCode Unchecked Error Condition FIRCoreDiagnostics.m

### ISSUE THREAD

**Issue by security-v** [firebase/firebase-ios-sdk#5297]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.17
  * Firebase Component: Core (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: (~> 1.0)
  * Installation method: `CocoaPods ` (select one)

#### Steps to reproduce:

The result of this call to malloc() is not checked for success before being used. This can result in application instability or crashing if memory is not available.

#### Relevant Code:

```
 FirebaseCoreDiagnostics/Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m:513
```

**Comment by paulb777** [comment]
Old code version.
