### ISSUE TITLE
FIRCreateError is largely unused

### ISSUE THREAD

**Issue by ryanwilson** [firebase/firebase-ios-sdk#530]
Although they're surfaced as a private header, `FIRCreateError` is only referenced within `Core` and unused elsewhere.

https://github.com/firebase/firebase-ios-sdk/blob/31a2acb7497eaaeae38b7ceb17edcab09d7f2866/Firebase/Core/Private/FIRErrors.h#L43

Is it worth removing this from the API?

**Comment by paulb777** [comment]
Looks like FIRError.* could be completely removed safely.
