### ISSUE TITLE
Crash on retrieve whitelist from plist

### ISSUE THREAD

**Issue by jserrafindster** [firebase/firebase-ios-sdk#5304]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.20.0
  * Firebase Component: Performance
  * Component version: 3.1.10
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem
User had a crash on his iphone 5 just as the app started

#### Steps to reproduce:

```
com.twitter.crashlytics.ios.work-queue :: NSOperation 0x178241e0 (QOS: DEFAULT)
0  CoreFoundation                 0x1cb99b80 CFHash + 1
1  CoreFoundation                 0x1cb964e8 CFBasicHashFindBucket + 216
2  CoreFoundation                 0x1cb963b5 CFDictionaryGetValue + 100
3  CoreFoundation                 0x1cc28db1 _copyQueryTable + 158
4  CoreFoundation                 0x1cc28635 _copyResourceURLsFromBundle + 256
5  CoreFoundation                 0x1cbd2f71 _CFBundleCopyFindResources + 884
6  CoreFoundation                 0x1cbd2bf1 CFBundleCopyResourceURL + 32
7  CoreFoundation                 0x1cbda60b CFBundleGetLocalInfoDictionary + 80
8  Foundation                     0x1d53b429 <redacted> + 26
9  Foundation                     0x1d53b3d7 <redacted> + 24
10 OurApp                  0x48437f __42-[FPRURLFilter retrieveWhitelistFromPlist]_block_invoke + 5133183
11 libdispatch.dylib              0x1c35d783 _dispatch_client_callout + 22
12 libdispatch.dylib              0x1c35e253 dispatch_once_f + 42
13 OurApp                  0x4842cb -[FPRURLFilter retrieveWhitelistFromPlist] + 5133003
14 OurApp                   0x4840c9 -[FPRURLFilter isURLWhitelisted:] + 5132489
15 OurApp                   0x483f7b -[FPRURLFilter shouldInstrumentURL:] + 5132155
16 OurApp                   0x487833 -[FPRNetworkTrace initWithURLRequest:] + 5146675
17 OurApp                   0x48edb3 __InstrumentUploadTaskWithRequestFromFile_block_invoke + 5176755
18 OurApp                   0x48ed37 __InstrumentUploadTaskWithRequestFromFile_block_invoke + 5176631
19 OurApp                   0x40d41d -[CLSNetworkClient startNewUploadRequest:filePath:] + 204 (CLSNetworkClient.m:204)
20 OurApp                   0x40d961 __77-[CLSNetworkClient checkSession:forTasksMatchingDescription:completionBlock:]_block_invoke + 264 (CLSNetworkClient.m:264)
21 CFNetwork                      0x1d3359d9 __46-[NSURLSession getTasksWithCompletionHandler:]_block_invoke_2 + 194
22 CFNetwork                      0x1d28662f __67-[__NSURLBackgroundSession _onqueue_getTasksWithCompletionHandler:]_block_invoke + 14
23 Foundation                     0x1d5b5b01 <redacted> + 8
24 Foundation                     0x1d50baef <redacted> + 146
25 Foundation                     0x1d4fdfe7 <redacted> + 770
26 Foundation                     0x1d5b7d39 <redacted> + 190
27 libdispatch.dylib              0x1c36a59d _dispatch_queue_serial_drain + 854
28 libdispatch.dylib              0x1c360b71 _dispatch_queue_invoke + 886
29 libdispatch.dylib              0x1c36c1b5 _dispatch_root_queue_drain + 326
30 libdispatch.dylib              0x1c36c00f _dispatch_worker_thread3 + 106
31 libsystem_pthread.dylib        0x1c51287d _pthread_wqthread + 1040
32 libsystem_pthread.dylib        0x1c51245c start_wqthread + 8
```

**Comment by yalunqin** [comment]
Hi @jserrafindster,

We tried reproducing the issue with the latest version of Fireperf SDK on iOS 9 and above and we are not able to reproduce this.

This issue states that it happens on device iPhone 5. We need some information to see if we can debug this further.
1. What versions of iOS are you seeing this issue?
2. Have you been able to reproduce this issue? If so, are you seeing this on Simulator or Device or both?
3. What is the volume of this crash you are seeing? If so, apart of app start time, do you see any other patterns of issue occurring on particular devices/particular iOS versions more often than other?

**Comment by jserrafindster** [comment]
@yalunqin 
1.  
**Device**
Model: iPhone 5
Orientation: Unknown
RAM free: 94.54 MB
Disk free: 53.73 GB

**Operating System**
Version: 10.3.4 (14G61)
Orientation: Portrait
Jailbroken: No

**Crash**
Date: Mar 30, 2020, 10:41:00 AM
App version: 2.4.0 

2. i have not been able to reproduce it either, im seeing it happen on device on our users
3. we had to pull the version out. for 1% of our users we had 1 crash

Also I suspect something might be happening on apple side after the archives are built and uploaded.

**Comment by paulb777** [comment]
@jserrafindster This sounds like a 32 bit device specific issue. Would you confirm the Xcode version? The report says 11.3.1 - but there is a known Xcode 11.4 issue. See https://forums.swift.org/t/crashes-on-32-bit-after-xcode-11-4/35035

**Comment by jserrafindster** [comment]
yes we are not using 11.4 we are using 11.3.1 but meanwhile we are having several issues and talking with apple. But it seems theres a new release 11.4.1 GM 2 days ago

**Comment by paulb777** [comment]
@jserrafindster There is a report at https://forums.swift.org/t/crashes-on-32-bit-after-xcode-11-4/35035/10 that Xcode 11.4.1 does not fix the 32 bit optimization bug.

**Comment by paulb777** [comment]
@jserrafindster Any updates you can share about Xcode versions or what you learned from Apple?

**Comment by navyseai** [comment]
> @jserrafindster Any updates you can share about Xcode versions or what you learned from Apple?

just that there is a new xcode version release that solve some issues, but i haven't had any time to test it and i wont be able to do it any time soon since im unable to replicate it and its happening to our users in production. 

I guess this issue is stalled right now
