### ISSUE TITLE
157240295: Handle universal link isn't working

### ISSUE THREAD

**Issue by DracoRubi** [firebase/firebase-ios-sdk#5314]
### Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 4.9.0 and 6.21.0
  * Firebase Component: DynamicLinks
  * Component version: 4.9.0 and 6.21.0
  * Installation method: CocoaPods

### Step 2: Describe the problem

There's an issue with the **handleUniversalLink** method. It returns true, but later in the closure the DynamicLink object has nil url.

This issue is happening even below iOS 13, and doesn't fully match the descriptions in the other current open issues.
In #4914, apparently the dynamic link doesn't open the app.
In #5122, it only mentions the first open after install.

#### Steps to reproduce:

I can provide a minimal reproducible example by giving access to my private repository where I have the project stored.
The Firebase support ticket 00043830 is related to this issue. I also provided the minimal reproducible example there.

In order to reproduce the issue, install the application, then exit it. Then, if you open the dynamic link using Safari:

If you're testing with DynamicLinks 4.9.0, the following would happen:
- handleUniversalLink returns true
- handleUniversalLink callback never gets executed

If you're testing with DynamicLinks 6.21.0:
- handleUniversalLink returns false
- handleUniversalLink callback never gets executed

#### Relevant Code:

```
func application(_ application: UIApplication, continue userActivity: NSUserActivity,
                   restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
    let handled = DynamicLinks.dynamicLinks().handleUniversalLink(userActivity.webpageURL!) { (dynamiclink, error) in
      // [START_EXCLUDE]
        /**
        NOTES:
         Notice that this callback is never called.
         In my original application, I always expect this callback to be executed, and I never do anything if handled value is false. Should I be doing something?
         */
        self.showDeepLinkAlertView(withMessage: "handleUniversalLink callback with \(String(describing: dynamiclink?.url))")
    // [END_EXCLUDE]
    }

    // But handled is FALSE. Why?
    // [START_EXCLUDE silent]
    if !handled {
        // Show the deep link URL from userActivity.
        let message = "Handled returned false. Why? The url is: \n \(String(describing: userActivity.webpageURL))"
        showDeepLinkAlertView(withMessage: message)
    }
    // [END_EXCLUDE]
    return handled
  }
```

#### Additional info:
- Currently I'm working with a workaround that manually processes the url contained in the userActivity, since handleUniversalLink doesn't give me the url.
- This issue only happens when the app is already installed. If the app isn't installed, and the user uses the dynamic link, goes through the installation and opens the app, it works just fine (because it uses `dynamicLink(fromCustomSchemeURL)`)
- Also, it only gives issues with Safari (or opening the link in Notes), because opening the dynamic link with Firefox, Chrome or others opens the application from `dynamicLink(fromCustomSchemeURL)`.

**Comment by iMacHumphries** [comment]
- Firebase/DynamicLinks (6.22.0):
- Using short links
- handled is true
- dynamicLink.url is nil

Inside of handleUniversalLink:
```
let handled = DynamicLinks.dynamicLinks().handleUniversalLink(url) { (dynamicLink, error) in

}
```
```
(lldb) po dynamicLink
▿ Optional<FIRDynamicLink>
  - some : <FIRDynamicLink: 0x282d07c40, url [(null)], match type: unique, minimumAppVersion: N/A, match message: (null)>
(lldb) po error
nil
```

I noticed this log:
`6.22.0 - [Firebase/Analytics][I-ACS023000] Deep Link Web URL query is empty`

**Comment by iMacHumphries** [comment]
Maybe related:
https://forums.developer.apple.com/thread/123554

Possible new format for apple-site-app-association in iOS 13:
https://developer.apple.com/documentation/safariservices/supporting_associated_domains_in_your_app?language=objc

**Comment by DracoRubi** [comment]
The issue is happening in versions below iOS 13, so probably not related?

**Comment by fastcoretux** [comment]
I'm facing second described problem in SDK version 6.2.0 and iOS 13.5.1
- handleUniversalLink returns false
- handleUniversalLink callback never gets executed

There is any progress or adition info of this issue?

Thank you!

**Comment by mostafaesmaiel-mamo** [comment]
I had the same issue. Add the `FirebaseDynamicLinksCustomDomains` as array in your info.plist and add your base url for the dynamic link that you have configured in the associated domains. 
Should be working properly after that :)

**Comment by jan-scorl** [comment]
> I had the same issue. Add the `FirebaseDynamicLinksCustomDomains` as array in your info.plist and add your base url for the dynamic link that you have configured in the associated domains.
> Should be working properly after that :)

I'm facing the same issue and doing this didn't resolve it. Does anyone have other suggestions for how to solve this?

**Comment by idsky2** [comment]
Check the Firebase API Key restrictions in *Google* Console -- mine was restricted to not allow Dynamic Links API calls from back when we first started using firebase for other things.  I wish the API call had given a permission error instead of a 'success' response with a null link!

**Comment by sergey-sivchenko** [comment]
@yannxaver were you able to solve your issue?

**Comment by yannxaver** [comment]
> @yannxaver were you able to solve your issue?

Yes, I was able to resolve it but I can't tell you exactly what eliminated the problem because it's been awhile.

**Comment by eldhosembabu** [comment]
Hi @DracoRubi , @fastcoretux , others

Is this issue reproducible in the latest FDL SDK?

If yes, could you please provide the FDL link used for reproducing the issue?
