### ISSUE TITLE
Can't connect to Firestore anymore

### ISSUE THREAD

**Issue by Ryan-Gadhi** [firebase/firebase-ios-sdk#5326]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.22.0
  * Firebase Component: Firestore
  * Component version: not sure (but sure I have latest [removed and installed again])
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

Can't connect to firestore. Can't read data. 

#### Steps to reproduce:

What happened? How can we make the problem occur?

this is enough to make the problem occur
`FirebaseApp.configure() `
I did `pod update` with no luck, the following is the error stack trace:

`****[14875:781917] [GoogleDataTransport][I-GDTCOR001006] There was an error reading extension bytes from disk: Error Domain=NSCocoaErrorDomain Code=260 "The file “event-5660938629709599763” couldn’t be opened because there is no such file." UserInfo={NSFilePath=***/Developer/CoreSimulator/Devices/24E1E711-47A4-4048-841F-C7BAFA14B833/data/Containers/Data/Application/D01B42C8-7503-486D-96FC-42F725EB3CC2/Library/Caches/google-sdks-events/event-5660938629709599763, NSUnderlyingError=0x600003e49cb0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
2020-04-09 15:29:28.978481+0300 BJ_HouseOwner[14875:781919] [GoogleDataTransport][I-GDTCOR001006] (/***/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m:152) : There was an error removing an event file: Error Domain=NSCocoaErrorDomain Code=4 "“event-5660938629709599763” couldn’t be removed." UserInfo={NSUserStringVariant=(
    Remove
), NSFilePath=***/Developer/CoreSimulator/Devices/24E1E711-47A4-4048-841F-C7BAFA14B833/data/Containers/Data/Application/D01B42C8-7503-486D-96FC-42F725EB3CC2/Library/Caches/google-sdks-events/event-5660938629709599763, NSUnderlyingError=0x600003eab300 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}`
#### Relevant Code:

```
FirebaseApp.configure()
```

Here is my firebase access rules

`rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if  true ;
    }
  }
}`

**Comment by Ryan-Gadhi** [comment]
I solved this issue by making more space available in the iOS simulator. I deleted some of the apps that I developed in the past, and now it is working fine. I will close this issue now.

**Comment by wilhuff** [comment]
@mikehaney24 FYI

**Comment by wilhuff** [comment]
@Ryan-Gadhi Thanks for the report! Indeed this does look like an internal component was unable to write to disk because you were out of space.
