### ISSUE TITLE
Add new target/project on podfile cause "Terminating app due to uncaught exception 'com.firebase.installations'"

### ISSUE THREAD

**Issue by Dsanabriabr** [firebase/firebase-ios-sdk#5328]
### Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.18.0
  * Firebase Component: Analytics, Messaging
  * Component version: (= 6.3.0), (~> 4.3.0)
  * Installation method: `CocoaPods`

#### Steps to reproduce:

The app was working normally before even when the SwiftSignalRClient was available just in the main target, but when I add the new target on podfile I receive this strange error about FirebaseApp.configure()! And I haven't changed anything on AppDelegate!

What happened? 

> *** Terminating app due to uncaught exception 'com.firebase.installations', reason: 'The default FirebaseApp instance must be configured before the defaultFirebaseApp instance can be initialized. One way to ensure that is to call `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) in the App Delegate's `application:didFinishLaunchingWithOptions:` (`application(_:didFinishLaunchingWithOptions:)` in Swift).'

How can we make the problem occur?

Add to podfile a new target, sample:
>target 'Notifications' do
    project 'Modules/Notifications/Notifications'
    pod 'SwiftSignalRClient'
  end

#### Relevant Code:

> *** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c710bc +[NSException raise:format:] + 188
	3   Notifications                       0x0000000103f9d716 +[FIRInstallations installations] + 118
	4   Notifications                       0x0000000103f8bf45 +[FIRAnalytics updateFirebaseInstallationID] + 31
	5   Notifications                       0x0000000103f8be86 +[FIRAnalytics startWithConfiguration:options:] + 543
	6   #TemMeuVoto                         0x0000000103613b44 -[FIRApp configureCore] + 452
	7   #TemMeuVoto                         0x000000010361366f +[FIRApp addAppToAppDictionary:] + 127
	8   #TemMeuVoto                         0x0000000103612865 +[FIRApp configureWithName:options:] + 1301
	9   #TemMeuVoto                         0x000000010361220f +[FIRApp configureWithOptions:] + 143
	10  #TemMeuVoto                         0x0000000103612165 +[FIRApp configure] + 165
	11  #TemMeuVoto                         0x000000010360598a $s11_TemMeuVoto11AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0l6LaunchK3KeyaypGSgtF + 154
	12  #TemMeuVoto                         0x0000000103606204 $s11_TemMeuVoto11AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0l6LaunchK3KeyaypGSgtFTo + 212
	13  UIKitCore                           0x00007fff48089ad8 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 232
	14  UIKitCore                           0x00007fff4808b460 -[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:] + 3980
	15  UIKitCore                           0x00007fff48090f05 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1226
	16  UIKitCore                           0x00007fff477c57a6 -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] + 179
	17  UIKitCore                           0x00007fff4808d514 -[UIApplication _compellApplicationLaunchToCompleteUnconditionally] + 59
	18  UIKitCore                           0x00007fff4808d813 -[UIApplication _run] + 754
	19  UIKitCore                           0x00007fff48092d4d UIApplicationMain + 1621
	20  #TemMeuVoto                         0x000000010360aa6b main + 75
	21  libdyld.dylib                       0x00007fff5227ec25 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

#### Podfile:
> platform :ios, '10.0'
 workspace 'TemMeuVoto'
 target 'TemMeuVoto' do
  use_frameworks!
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'SwiftSignalRClient'
  target 'TemMeuVotoTests' do
    inherit! :search_paths
    # Pods for testing
  end
  target 'TemMeuVotoUITests' do
    # Pods for testing
  end
  target 'Notifications' do
    use_frameworks!
    project 'Modules/Notifications/Notifications'
    pod 'SwiftSignalRClient'
  end
 end

#### Podfile.lock
[Podfile.lock.txt](https://github.com/firebase/firebase-ios-sdk/files/4456926/Podfile.lock.txt)

**Comment by morganchen12** [comment]
Can you share the app logs? Do you have duplicate class definition warnings when running your app?

**Comment by Dsanabriabr** [comment]
yeah, i got something about class implemented in both module....

> Class` GDTCCTUploader is implemented in both /Users/danielsanabria/Library/Developer/Xcode/DerivedData/TemMeuVoto-gzpbperkuqexnbcktugsvsqaaenz/Build/Products/Debug-iphonesimulator/Notifications.framework/Notifications (0x104387520) and /Users/danielsanabria/Library/Developer/CoreSimulator/Devices/222AE993-2487-43B0-9F10-B583F97AEA53/data/Containers/Bundle/Application/036A7D1F-AD9A-4564-B872-5926C22C5E23/#TemMeuVoto.app/#TemMeuVoto (0x103a09348). One of the two will be used. Which one is undefined.

After that:
> 2020-04-09 18:10:48.407438-0300 #TemMeuVoto[10655:215137] 6.18.0 - [Firebase/Analytics][I-ACS023007] Analytics v.60300000 started
2020-04-09 18:10:48.410398-0300 #TemMeuVoto[10655:215137] 6.18.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2020-04-09 18:10:48.418188-0300 #TemMeuVoto[10655:214945] *** Terminating app due to uncaught exception 'com.firebase.installations', reason: 'The default FirebaseApp instance must be configured before the defaultFirebaseApp instance can be initialized. One way to ensure that is to call `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) in the App Delegate's `application:didFinishLaunchingWithOptions:` (`application(_:didFinishLaunchingWithOptions:)` in Swift).'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c7127e

**Comment by morganchen12** [comment]
This means you have two copies of Firebase linked into your app. You'll need to remove one of the copies. Are you trying to use Firebase from a dynamic framework target?

**Comment by Dsanabriabr** [comment]
My installation method was CocoaPods and I installed in podfile like the official guide!
Don't make sense to me! Why, if i install another target even without declaring the pod, they copied the Firebase framework?
Sorry if I'm boring you! I really want to learn,  cause this kind of detail wasn't in the official guide!

#### podfile:
> platform :ios, '10.0'
workspace 'TemMeuVoto'
target 'TemMeuVoto' do
use_frameworks!
pod 'Firebase/Analytics'
pod 'Firebase/Messaging'
pod 'SwiftSignalRClient'
target 'TemMeuVotoTests' do
inherit! :search_paths
end
target 'TemMeuVotoUITests' do
end
target 'Notifications' do
use_frameworks!
project 'Modules/Notifications/Notifications'
pod 'SwiftSignalRClient'
end
end

**Comment by morganchen12** [comment]
Can you try adding `inherit! :search_paths` to the `Notifications` target in your Podfile? Also, what version of CocoaPods are you running?
