### ISSUE TITLE
Firebase InstanceID invalid when entered in Firebase ABTesting test device

### ISSUE THREAD

**Issue by jc-paris** [firebase/firebase-ios-sdk#5335]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 11.4 (11E146)
  * Firebase SDK version: 6.21.0
  * Firebase Component: RemoteConfig / ABTesting
  * Component version: RemoteConfig (4.4.9) / ABTesting (3.2.0)
  * Installation method: `file`

#### Steps to reproduce:

- Use code snipped to retrieve the Instance ID Token (see next section)
- Go in firebae console and enter this Instance ID Token in Manage test device for an ab test.
- See the following error:
<img width="336" alt="Screenshot 2020-04-10 at 09 33 04" src="https://user-images.githubusercontent.com/6810502/78972937-2b55f180-7b0f-11ea-84a6-3e2c7e374b4c.png">

#### Relevant Code:

```swift
        InstanceID.instanceID().instanceID { (result, error) in
            if let error = error {
                print("Error fetching remote instance ID: \(error)")
            } else if let result = result {
                print("Remote instance ID token: [\(result.token)]")
            }
        }
```

**Comment by paulb777** [comment]
@jc-paris Thanks for the report.  @christibbs Would you take a look?  Perhaps an ABTesting console issue?

**Comment by christibbs** [comment]
Investigating today, will keep you posted @jc-paris.

**Comment by christibbs** [comment]
@jc-paris I tested this out and couldn't reproduce the bug. One counter-intuitive thing I noticed about the sample code was that it prints the instance ID in brackets, f/e: `[this_is_my_fake_instanceID]`. Could you try it removing the the brackets?

**Comment by jc-paris** [comment]
This was due to a backend issue that has been resolved during the weekend. Your team replied to me by email and confirmed there were getting several feedback 😉
