### ISSUE TITLE
'GoogleDataTransport/GDTCORUploader.h' file not found

### ISSUE THREAD

**Issue by QuanHuynhM** [firebase/firebase-ios-sdk#5336]
* Xcode version: 11.2.1
 * Firebase SDK version: 6.22.0
 * Firebase Component: Auth, Core, Remote Config, Crashlytics
 * Installation method: CocoaPods

 When I build my application, I get a notification
'GoogleDataTransport / GDTCORUploader.h' file not found
'GoogleDataTransport / GDTCORClock.h' file not found

And here is my pod file

  pod 'Crashlytics'
  pod 'Fabric'
  pod 'FBSDKCoreKit'
  pod 'FBSDKGamingServicesKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/RemoteConfig'
  pod 'GoogleMobileAdsMediationFacebook'
  pod 'Google-Mobile-Ads-SDK'

Does anyone know what this is? And how to fix it

**Comment by paulb777** [comment]
@QuanHuynhM Thanks for the report. This might be the result of the Xcode project being in a bad state. Please check if https://stackoverflow.com/a/58543307/556617 helps.

**Comment by QuanHuynhM** [comment]
@paulb777 Thank you. I have updated the pod and have successfully built it
