### ISSUE TITLE
FR: Expose user UID in linkWithCredential FIRAuthErrorCodeCredentialAlreadyInUse error

### ISSUE THREAD

**Issue by willbattel** [firebase/firebase-ios-sdk#5342]
### Feature proposal

* Firebase Component: Auth

When we encounter the `FIRAuthErrorCodeCredentialAlreadyInUse` error when using `linkWithCredential`, we want to get back the UID of the existing user that owns the credential. We need the UID in order to handle account merging in a "safe" manner. We want to merge user data **before** we complete `signIn(with:)` so that we can do the [Firestore] data migration still authenticated as the anonymous user.

I'm linking the FirebaseUI issue I filed before realizing FIRAuth itself doesn't expose the UID. Originally I thought it was a limitation of FirebaseUI, but after looking at the source I see that FIRAuth does not offer the UID in any capacity. Inside this issue I give the full reasoning for wanting the UID to handle merging accounts. 
https://github.com/firebase/FirebaseUI-iOS/issues/851

Alternatively, though I don't know if this is any more feasible, another solution would be to have a function that takes a `FIRAuthCredential` and returns the associated UID without signing in.

**Comment by willbattel** [comment]
I've looked at the FIRAuth source and as far as I can tell, the subject code is internal and therefore not something I can make a PR for.

**Comment by morganchen12** [comment]
Yep, this needs to go through some Firebase-internal API review. Our Auth work has been delayed by some internal stuff so it will be a bit before we're able to get that API review started, but once it's begun it should be a relatively light addition.

**Comment by willbattel** [comment]
@morganchen12 Thank you for the info! Please keep us informed of any progress. For now we'll be using what I would consider to be a "hacky" workaround, so we're eager to have this feature to create a robust merging flow.

**Comment by willbattel** [comment]
Hey @morganchen12, at your convenience, would you mind reporting any progress (or lack thereof, I know you're busy!) on this request? Thanks!

**Comment by morganchen12** [comment]
No progress has been made yet, but while we're waiting for some bandwidth we can talk about what sort of API would be ideal in this scenario.

Would it be sufficient to expose the linked and current accounts in the userInfo dictionary be sufficient? Something like

```swift
[
  "FIRAuthAccountBeingLinkedUID": "uid1", // account of provider being linked
  "FIRAuthLinkingAccountUID": "uid2" // currently signed in account
]
```

**Comment by willbattel** [comment]
Hi Morgan, thanks for the update. I think your proposal would suffice- though we only really need the value of the first key (we should already know the value of the second key) and I'd suggest calling the first key `FIRAuthExistingAccountUID` instead. But yes- providing the key in the `userInfo` dictionary would do the trick.

Additionally you could consider the idea of adding an entirely new function we could call that returns the UID associated with the provided `FIRAuthCredential` without signing in. This function could be used in this case and may have additional uses elsewhere.

**Comment by willbattel** [comment]
We should also discuss how this will carry over into the other client SDKs. My team is currently focused on iOS, but we'll be looking for the equivalent API in the Android and Web SDKs in the near future. I'm assuming that, like the iOS SDK, this feature is not currently met by the other SDKs. Would the implementation ultimately be the same across SDKs, or are there additional platform-specific considerations that need to be discussed?

**Comment by willbattel** [comment]
Hey @morganchen12 just wanted to check in again. I can see the team is still focused on numerous other priorities, so I'm wondering if we might see some bandwidth for this in July or August- or if you think it will be longer before that happens. Thanks!

**Comment by morganchen12** [comment]
Thanks for your patience Will. 

@rosalyntan, can you put together a cross-platform API proposal based on the comments [here](https://github.com/firebase/firebase-ios-sdk/issues/5342#issuecomment-634161961)?

**Comment by rosalyntan** [comment]
Yup, I'll work on putting together an API proposal. Filed b/160903269 for internal tracking.

**Comment by rosalyntan** [comment]
Hi @willbattel , thanks again for your patience! I chatted with the team about your use case, and would discourage migrating user data before the user signs into the destination account, as this opens up a possible abuse vector. In order to securely migrate data, this migration should occur using the identity tokens of the original account and the destination account.

In firebase/FirebaseUI-iOS#851 you mention the concern of data loss, should the migration fail. To add resilience to the user upgrade flow, you can keep the previous user in memory and retry the migration if it fails. These docs have some guidance on how to do this.

You can also consider setting up 2 `FIRApp`s in your application and using the second one to log the user in with the second credential. That would give you the tokens for the destination user account, allowing you to submit tokens (and not UIDs) to your callable cloud function. As a result, rogue calls to your cloud function won’t allow malicious actors to seed existing accounts with spurious data.

**Comment by willbattel** [comment]
Hey @rosalyntan thanks for those details. We'll look into your proposed alternative. (also, I think the docs link you mentioned in the second paragraph is broken or wasn't inserted correctly). Simply retrying the operation would help but doesn't sufficiently satisfy the degree of resiliency we're hoping for. Using a second `FIRApp` is an interesting idea we can play with.

As a followup- something that would be beneficial in multiple scenarios (including but not limited to this one) would be the ability to retain the anonymous user instead of discarding it upon non-anonymous sign-in. This is an excerpt from a feature request I previously submitted through the Firebase Support site:

> Our app does not force users to sign in with a non-anonymous provider when the use the app. Instead, we authenticate them anonymously until they choose to sign in. Additionally, devices in our app are treated as first-class citizens, whereas the user structure is merely a bridge between the devices owned by end-users. After signing into a non-anonymous provider, the user can at any later date choose to remove their device (read: sign out) from that account. When this happens, the user has two choices: they can either sign into a different non-anonymous account, or they can proceed anonymously as they did originally.

> When anonymous users sign into non-anonymous accounts, the Firebase SDK discards their anonymous credentials and abandons the account. This probably makes sense in most apps. However, in the context of our app, we would really like it if we could configure the Authentication module to retain the anonymous credentials. We want users to be able to sign back into their original anonymous account, instead of Firebase creating a new anonymous account.

The rep that responded indicated that the request made sense and may be possible, and that they filed the request internally- but I have not heard further. @morganchen12 could I also get your opinion on this idea? Being able to restore the original anonymous user may be a good way for us to "fall back" if the account merge migration fails for any reason.

If you think this is a reasonable request, I can open a different FR issue for it- as it's related but markedly different from this one.

**Comment by morganchen12** [comment]
In the case where your user represents an installation of your app on a device, could you just store all of that user's data locally and skip authentication state completely?

**Comment by willbattel** [comment]
We use anonymous auth to securely access Cloud Functions and Cloud Firestore. I'm not sure how we could do that without using FIRAuth. Unless you're referring to the non-anonymous auth state? In which case, your idea would work in terms of data organization, but I don't know how we would go about authenticating non-anonymous credentials in order to verify account ownership.

**Comment by morganchen12** [comment]
Yeah, that's a good point. _Probably_ the right thing to do is to use a second FIRApp to keep the anonymous user around until the sign-in and linking flow is complete, and if the account linking fails you still have the signed-in anonymous user to fall back on. Our developer materials don't really cover this well, though.

**Comment by willbattel** [comment]
I opened a new issue for the anonymous account retention, because I believe it has value beyond the scenario discussed in this issue.
