### ISSUE TITLE
Re-open: "Crashlytics upload dSYM successfully, But firebase console of Crashlytics still show dSYM required"

### ISSUE THREAD

**Issue by ZaVyLoN** [firebase/firebase-ios-sdk#5349]
I still have this problem.
Closed issue: https://github.com/firebase/firebase-ios-sdk/issues/5327

Xcode version: 11.4  (has been updated)
CocoaPods (pod --version 1.9.1): 
- Crashlytics (3.14.0)  - has been updated
- Firebase (6.18.0) - has been updated

<img width="506" alt="Screen Shot 2020-04-12 at 21 39 30" src="https://user-images.githubusercontent.com/3078481/79076923-21e2aa00-7d06-11ea-9a86-d19046083e8f.png">
<img width="682" alt="Screen Shot 2020-04-12 at 21 19 50" src="https://user-images.githubusercontent.com/3078481/79076828-ae409d00-7d05-11ea-8f4e-0ddf22288baf.png">

**Comment by paulb777** [comment]
@ZaVyLoN Thanks for the report. It's possible that running `pod update` to update Firebase to the current 6.22.0 version will help.

**Comment by samedson** [comment]
We are having a slowdown of replayed crashes. When crashes are uploaded to Crashlytics before the dSYM is uploaded, we are seeing a delay in those crashes making it to the dashboard. It is a backend issue and the team is working on fixing it.

 - If you run into this, please wait 24 hours for your crashes to show up. If they still don't show up after that, reach out to Firebase support and we can look into it more deeply.

**Comment by ZaVyLoN** [comment]
@paulb777, @samedson  thanks. 

Firebase updated to 6.22.0 version and tried to load dSYM again. An hour has passed. It did not bring any result. I will wait 24 hours.

**Comment by JasonSa1993** [comment]
I saw this error and after searching a lot, I came to the following solution:

1- pod deintegrate

2- pod cache clean --all

3- In the podfile install these versions of the following pod's

         `pod 'Firebase'`
         `pod 'FirebaseInstallations', '1.1.0'`
         `pod 'Fabric', '~> 1.10.2'`
         `pod 'Crashlytics', '~> 3.14.0'`
         `pod 'Firebase / Analytics'`

4- pod install

5- In your Build phases file

![image](https://user-images.githubusercontent.com/22629210/79280749-ca178080-7e76-11ea-82cc-32cac6346264.png)

`"${PODS_ROOT}/Fabric/run"`
`$(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)`

6-  FirebaseApp.configure() in your App delegate didFinishLaunchingWithOptions

7- Run your app

8- Make your app crash

Hope it helps

**Comment by ndreisg** [comment]
I wanted to note that I'm also facing this issue since yesterday.
Uploads were still working last week without any problems.
My first unsuccessful upload attempt is more than 24 hours ago.
I also tried to update my Pods and to download a new GoogleService-Info.plist from Firebase console but still no luck.

**Comment by viniciussoares** [comment]
Same issue here.

**Comment by jrustonapps** [comment]
I am also experiencing this. It worked fine last week.

**Comment by BruceZhang2017** [comment]
I have same problem.

**Comment by SudhaChandranBC** [comment]
Same issue here.

**Comment by TKBurner** [comment]
Thanks. We have become aware of an issue with dSYM processing and are currently looking into it. Some affected users should already see their issues resolved.

Please note:

- If you linked your app via the [Firebase Migration](https://fabric.io/firebase_migration) flow, and are using the Fabric Crashlytics SDK (v3.x), please continue to pass your legacy Fabric API Key to upload-symbols and run, not your GoogleService-info.plist.
- If you’re using the Firebase/Crashlytics SDK (v4.x) or onboarded for the first time in Firebase on v3.x, pass your GoogleService-info.plist

We will update as we receive updates from the team :)

**Comment by ZaVyLoN** [comment]
Closed, because open original issue:
https://github.com/firebase/firebase-ios-sdk/issues/5327
