### ISSUE TITLE
iOS Crash FIRConnectorUtils isUserPropertyAllowed:withOrigin:

### ISSUE THREAD

**Issue by darkjoin** [firebase/firebase-ios-sdk#5350]
![WechatIMG412](https://user-images.githubusercontent.com/20415509/79113113-bd315900-7db2-11ea-8558-29e1e99ac199.jpeg)

```
       do {
            detectedFaces = try faceDetector.results(in: image)
        } catch let error {
            print("Failed to detect faces with error: \(error.localizedDescription).")
            
        }
```

**Comment by paulb777** [comment]
@darkjoin Thanks for the report. We'll likely need more information to help. Please provide the Firebase versions installed (from Podfile.lock if installing via CocoaPods).  Also provide the full backtrace of the crash - not just a screen shot.

**Comment by darkjoin** [comment]
The versions we used:

```
- Firebase/Core (6.5.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.0.4)
  - Firebase/CoreOnly (6.5.0):
    - FirebaseCore (= 6.1.0)
  - Firebase/MLVision (6.5.0):
    - Firebase/CoreOnly
    - FirebaseMLVision (~> 0.17.0)
  - Firebase/MLVisionFaceModel (6.5.0):
    - Firebase/CoreOnly
    - FirebaseMLVisionFaceModel (~> 0.17.0)
  - FirebaseAnalytics (6.0.4):
    - FirebaseCore (~> 6.1)
    - FirebaseInstanceID (~> 4.2)
    - GoogleAppMeasurement (= 6.0.4)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 0.3)
  - FirebaseCore (6.1.0):
    - GoogleUtilities/Environment (~> 6.0)
    - GoogleUtilities/Logger (~> 6.0)
  - FirebaseInstanceID (4.2.2):
    - FirebaseCore (~> 6.0)
    - GoogleUtilities/Environment (~> 6.0)
    - GoogleUtilities/UserDefaults (~> 6.0)
  - FirebaseMLCommon (0.17.0):
    - FirebaseCore (~> 6.0)
    - FirebaseInstanceID (~> 4.2)
    - GoogleUtilities/UserDefaults (~> 6.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseMLVision (0.17.0):
    - FirebaseCore (~> 6.0)
    - FirebaseMLCommon (~> 0.17)
    - GoogleAPIClientForREST/Core (~> 1.3)
    - GoogleAPIClientForREST/Vision (~> 1.3)
    - GoogleMobileVision/Detector (~> 1.4)
  - FirebaseMLVisionFaceModel (0.17.0):
    - GoogleMobileVision/FaceDetector (~> 1.4)
```

The problem is : 
we use the below code in out project to detect face:

```
let faceDetector = vision.faceDetector(options: options)

var detectedFaces: [VisionFace]? = nil
do {
    detectedFaces = try faceDetector.results(in: image)
} catch let error {
    print("Failed to detect faces with error: \(error.localizedDescription).")
}
```

Then in the crash log, we saw the report:

```
Thread 7
0 +[FIRConnectorUtils isUserPropertyAllowed:withOrigin:]
1 +[FIRConnectorUtils isUserPropertyAllowed:withOrigin:]
2 +[FIRConnectorUtils isUserPropertyAllowed:withOrigin:]
3 +[FIRConnectorUtils isUserPropertyAllowed:withOrigin:]
...
19 +[FIRConnectorUtils isUserPropertyAllowed:withOrigin:]
20 -[FIRVisionFaceDetector detectedFacesInImage:error]
21 -[FIRVisionFaceDetector resultsInImage:error]
```

And Next, we looked up the document [FIRVisionFaceDetector](https://firebase.google.com/docs/reference/ios/firebasemlvision/api/reference/Classes/FIRVisionFaceDetector) and [Docs](https://firebase.google.com/docs/ml-kit/ios/detect-objects), still can't find the reason.

**Comment by ryanwilson** [comment]
The `FIRConnectorUtils` is part of Analytics, but has been updated several times since the version you have.  Can you please update to the latest version and see if you still see the issue? Also, is this reproducible 100% of the time?

Thanks!

**Comment by darkjoin** [comment]
There are very few crashes, it isn't  reproducible 100% of the time, and we didn't  reproducible in our project, just found it in the crash log.

In addition, we encountered such problems in the review:

Try to execute the code below, the error didn't been catched, it crashed...

```
DispatchQueue.main.async {
    var detectedFaces: [VisionFace]? = nil
    do {
        detectedFaces = try faceDetector.results(in: image)
    } catch let error {
        print("Failed to detect faces with error: \(error.localizedDescription).")
    }
}
```

According to the [FIRVisionFaceDetector](https://firebase.google.com/docs/reference/ios/firebasemlvision/api/reference/Classes/FIRVisionFaceDetector), the code should throw an error and it did threw, the problem is I didn't catch the thrown error, is there anything wrong i wrote?

It just crashed:

```
Thread 1: Exception: "This method must be called on a background thread."
```

Continue to dig deeper，I found a blog [Swift Error Handling and Objective-C Interop in Depth](http://blog.benjamin-encz.de/post/swift-error-handling-and-objective-c-interop-in-depth/), and I'm not sure if it is related to the problem I encountered？

We wonder is there any possible that  If an Objective-C method produces an `NSError` *and* returns a value the `catch` blocks is not invoked and the error cannot be retrieved as said in the blog?

**Comment by morganchen12** [comment]
Swift's try-catch syntax will catch errors thrown by functions. It will not catch Objective-C exceptions, which (when thrown by Firebase and most other SDKs) are always fatal.

The method in your stack trace should never recurse in the latest version of Firebase, so if you're still encountering the issue after upgrading Analytics something strange is going on in your project.

**Comment by darkjoin** [comment]
Thanks a lot
