### ISSUE TITLE
Token in messaging:didReceiveRegistrationToken: should be nullable

### ISSUE THREAD

**Issue by chliangGoogle** [firebase/firebase-ios-sdk#5355]
#5339 fixes an issue when token is deleted, the `MessagingDelegate messaging:didReceiveRegistrationToken:` should be triggered with a nil token returned. Hence the token can be nullable. 
This is a breaking API that should be done in the next Firebase breaking change release.

**Comment by ryanwilson** [comment]
@chliangGoogle tagging so we don't miss this in Firebase 7
