### ISSUE TITLE
Memory continues to increase

### ISSUE THREAD

**Issue by mafaming** [firebase/firebase-ios-sdk#5361]
I am a developer in Mainland China. It seems that Firebase sdk is doing some work when the VPN debugging is turned on, which causes the memory to keep increasing. The console log is as follows screenshot
![image](https://user-images.githubusercontent.com/11641379/79212946-f46b3d00-7e7a-11ea-8b75-df4d77d05b9a.png)

If you don't open the vpn, memory will be much smaller. The screenshot of the Firebase log in the console:
![image](https://user-images.githubusercontent.com/11641379/79214703-7fe5cd80-7e7d-11ea-9126-b66cb559228f.png)

All Firebase SDKs in the project：
- Firebase/AdMob (6.21.0):
    - Firebase/CoreOnly
    - Google-Mobile-Ads-SDK (~> 7.50)
  - Firebase/Analytics (6.21.0):
    - Firebase/Core
  - Firebase/Core (6.21.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.4.0)
  - Firebase/CoreOnly (6.21.0):
    - FirebaseCore (= 6.6.5)
  - Firebase/DynamicLinks (6.21.0):
    - Firebase/CoreOnly
    - FirebaseDynamicLinks (~> 4.0.8)
  - Firebase/Messaging (6.21.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 4.3.0)
  - Firebase/MLVision (6.21.0):
    - Firebase/CoreOnly
    - FirebaseMLVision (~> 0.19.0)
  - Firebase/MLVisionLabelModel (6.21.0):
    - Firebase/CoreOnly
    - FirebaseMLVisionLabelModel (~> 0.19.0)
  - Firebase/Performance (6.21.0):
    - Firebase/CoreOnly
    - FirebasePerformance (~> 3.1.11)
  - Firebase/RemoteConfig (6.21.0):
    - Firebase/CoreOnly
    - FirebaseRemoteConfig (~> 4.4.9)
  - FirebaseABTesting (3.2.0):
    - FirebaseAnalyticsInterop (~> 1.3)
    - FirebaseCore (~> 6.1)
    - Protobuf (>= 3.9.2, ~> 3.9)
  - FirebaseAnalytics (6.4.0):
    - FirebaseCore (~> 6.6)
    - FirebaseInstallations (~> 1.1)
    - GoogleAppMeasurement (= 6.4.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (= 0.3.9011)
  - FirebaseAnalyticsInterop (1.5.0)
  - FirebaseCore (6.6.5):
    - FirebaseCoreDiagnostics (~> 1.2)
    - FirebaseCoreDiagnosticsInterop (~> 1.2)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
  - FirebaseCoreDiagnostics (1.2.2):
    - FirebaseCoreDiagnosticsInterop (~> 1.2)
    - GoogleDataTransportCCTSupport (~> 2.0)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
    - nanopb (~> 0.3.901)
  - FirebaseCoreDiagnosticsInterop (1.2.0)
  - FirebaseDynamicLinks (4.0.8):
    - FirebaseAnalyticsInterop (~> 1.3)
    - FirebaseCore (~> 6.2)
  - FirebaseInstallations (1.1.1):
    - FirebaseCore (~> 6.6)
    - GoogleUtilities/UserDefaults (~> 6.5)
    - PromisesObjC (~> 1.2)
  - FirebaseInstanceID (4.3.2):
    - FirebaseCore (~> 6.6)
    - FirebaseInstallations (~> 1.0)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/UserDefaults (~> 6.5)
  - FirebaseMessaging (4.3.0):
    - FirebaseAnalyticsInterop (~> 1.5)
    - FirebaseCore (~> 6.6)
    - FirebaseInstanceID (~> 4.3)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.5)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Reachability (~> 6.5)
    - GoogleUtilities/UserDefaults (~> 6.5)
    - Protobuf (>= 3.9.2, ~> 3.9)
  - FirebaseMLCommon (0.19.0):
    - FirebaseCore (~> 6.3)
    - FirebaseInstanceID (~> 4.2)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - "GoogleToolboxForMac/NSDictionary+URLArguments (~> 2.1)"
    - GoogleUtilities/UserDefaults (~> 6.0)
    - GTMSessionFetcher/Core (~> 1.1)
    - Protobuf (~> 3.5)
  - FirebaseMLVision (0.19.0):
    - FirebaseCore (~> 6.3)
    - FirebaseMLCommon (~> 0.19)
    - GoogleAPIClientForREST/Core (~> 1.3)
    - GoogleAPIClientForREST/Vision (~> 1.3)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - GTMSessionFetcher/Core (~> 1.1)
    - Protobuf (~> 3.5)
  - FirebaseMLVisionLabelModel (0.19.0):
    - FirebaseMLVision (~> 0.19)
  - FirebasePerformance (3.1.11):
    - FirebaseCore (~> 6.6)
    - FirebaseInstallations (~> 1.1)
    - FirebaseRemoteConfig (~> 4.4)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/ISASwizzler (~> 6.2)
    - GoogleUtilities/MethodSwizzler (~> 6.2)
    - GTMSessionFetcher/Core (~> 1.1)
    - Protobuf (~> 3.9)
  - FirebaseRemoteConfig (4.4.9):
    - FirebaseABTesting (~> 3.1)
    - FirebaseAnalyticsInterop (~> 1.4)
    - FirebaseCore (~> 6.2)
    - FirebaseInstanceID (~> 4.2)
    - GoogleUtilities/Environment (~> 6.2)
    - "GoogleUtilities/NSData+zlib (~> 6.2)"
    - Protobuf (>= 3.9.2, ~> 3.9)

**Comment by mafaming** [comment]
When the VPN is turned on, the iPhone 6 running the app without doing any operation will increase the memory to more than 500 M, and if it is not turned on, it is more than 200

**Comment by paulb777** [comment]
@mfaming Thanks for the report. Are you able to identify which Firebase pod is causing the issue? For example, if you remove `Firebase/Performance` from the Podfile, does the issue still occur?

**Comment by ryanwilson** [comment]
If you a project to reproduce this (or sample code you could share) that would be very helpful as well!

**Comment by morganchen12** [comment]
If you can share an Allocations trace from Xcode Instruments that would be helpful as well.

**Comment by mafaming** [comment]
> If you can share an Allocations trace from Xcode Instruments that would be helpful as well.
The file is too big so I put it on my git.
https://github.com/mafaming/file/raw/master/Instruments.trace.zip

**Comment by mafaming** [comment]
> @mafaming Thanks for the report. Are you able to identify which Firebase pod is causing the issue? For example, if you remove `Firebase/Performance` from the Podfile, does the issue still occur?

I am trying this way

**Comment by mafaming** [comment]
@morganchen12  I uploaded two trace  files on git. Expect good results.
https://github.com/mafaming/file.git

**Comment by mafaming** [comment]
@paulb777  After repeated tests of adding and removing various firebase libraries, one or more of these libraries had memory problems associated with our project：
Firebase (6.21.0)
FirebaseCore (6.6.5)
FirebaseCoreDiagnostics (1.2.2)
FirebaseCoreDiagnosticsInterop (1.2.0)
FirebaseInstallations (1.1.1)
GoogleDataTransport (5.1.0)
GoogleDataTransportCCTSupport (2.0.1)
GoogleUtilities (6.5.2)

When running the app when the memory keeps increasing, the console keeps outputting：
2020-04-15 17:09:33.192277+0800 MojiPop[2628:575320] 6.21.0 - [Firebase/Installations][I-FIS002000] -[FIRInstallationsIDController createGetInstallationItemPromise], appName: __FIRAPP_DEFAULT
2020-04-15 17:09:33.193862+0800 MojiPop[2628:575320] 6.21.0 - [Firebase/Installations][I-FIS002001] -[FIRInstallationsIDController installationWithValidAuthTokenForcingRefresh:0], appName: __FIRAPP_DEFAULT

**Comment by paulb777** [comment]
@mafaming Thanks for the additional data. That log data looks like a good clue ...

**Comment by maksymmalyhin** [comment]
Potentially related to b/150481713

**Comment by paulb777** [comment]
@maksymmalyhin So does that mean you suspect an invalid `GoogleService-Info.plist`?

**Comment by maksymmalyhin** [comment]
My original guess was:
- In some conditions Installations and Perf may trigger a feedback loop when Perf requests FID from Installations, Installations sends a registration request, Perf requests FID to track the request. If FID registration requests fail then Perf may trigger sending them again and again. It may be a reason of increasing the memory consumption.

After investigating the [provided traces](https://github.com/mafaming/file.git) and taking into account the [comment](https://github.com/firebase/firebase-ios-sdk/issues/5361#issuecomment-613951916) I don't think it is a primary reason.

Observations I made so far:
1. A significant amount of new objects is allocated in `-[SKProductsRequest _handleReply:]` handler block. See screenshots below.
 
<img width="1974" alt="Screen Shot 2020-04-15 at 10 38 19 AM" src="https://user-images.githubusercontent.com/1841926/79353214-c3d1e480-7f08-11ea-9b91-22345af2f1af.png">
<img width="1974" alt="Screen Shot 2020-04-15 at 10 57 17 AM" src="https://user-images.githubusercontent.com/1841926/79353259-d2200080-7f08-11ea-9bf3-0c6def61520b.png">

2.  It looks like multiple `SKProductsRequests` are send over and over again. Increasing memory usage points to a potential memory leak in the related code.
<img width="1974" alt="Screen Shot 2020-04-15 at 10 39 22 AM" src="https://user-images.githubusercontent.com/1841926/79353480-17dcc900-7f09-11ea-848a-3f8636a049b3.png">

3. The traces are not symbolicated so I cannot really see how much Firebase contributes to the memory leaks.

4. Big amount of Firebase logs can be explained by Firebase Perf tracking the requests mentioned above. 

@mafaming Taking into account the observations I would suggest to check if sending so many `SKProductsRequest` is intended and if related code contains memory leaks. 

Please let us know the results so we continue investigation from our side if needed.

**Comment by morganchen12** [comment]
@mafaming note that you can use Instruments' Leaks tool to check for leaks as well (instead of just logging all allocations).

**Comment by mafaming** [comment]
@maksymmalyhin Maybe SKProductsRequest has a problem here. But I remove all the sdk of firebase. The maximum memory is more than 300 M. If I add the sdk of firebase to the project, the memory will reach more than 500 M.

**Comment by mafaming** [comment]
@maksymmalyhin Your analysis is correct.
The situation is now:
1. Remove the SKProductsRequest related code, add firebase SDK memory 200M
2. Add SKProductsRequest related code, remove firebase sdk, memory is more than 300 M
3. Add SKProductsRequest related code, add firebase sdk memory will reach 500M
So it can be concluded that the SKProductsRequest related code has a memory problem. It is a bit strange that the memory problem is magnified after adding firebase sdk.

**Comment by maksymmalyhin** [comment]
@mafaming It is hard to say without more information. Additional memory usage with Firebase may be explained by e.g. Firebase Performance trace objects associated with each network request which may be noticeable in the case of a big amount of active requests. 

To help us with further investigation you may examine memory graph of your app (see the [guide](https://developer.apple.com/documentation/xcode/improving_your_app_s_performance/reducing_your_app_s_memory_use/gathering_information_about_memory_use?language=objc)). If you can spot a big amount of Firebase created objects and share it with us it will help us to improve our memory characteristics. Note: most of Firebase classes have `FIR` prefix so you may use it to filter memory graph:

<img width="2115" alt="Screen Shot 2020-04-16 at 9 33 50 AM" src="https://user-images.githubusercontent.com/1841926/79462942-31901600-7fc6-11ea-9873-e07e948ecbdd.png">

**Comment by mafaming** [comment]
Probably found the cause of the memory problem, FBSDKPaymentObserver has a problem here. I commented out [FBSDKPaymentObserver startObservingTransactions], the memory looks normal, no matter if I add firebase sdk or not. The memory problem is only related to whether the FBSDKPaymentObserver works, which is why the memory problem is related to vpn. I see that the console keeps outputting logs with Firebase, thinking that there is something wrong with the firebase sdk. Thank you very much for your patience and help. @maksymmalyhin @ paulb777 Interested in watching FBSDKPaymentObserver? If I'm a Facebook SDK developer, I don't know how to fix this problem.

**Comment by maksymmalyhin** [comment]
@mafaming Thank you for the update. It's great to hear the issue was resolved!
