### ISSUE TITLE
Firestore iOS SDK "Could not reach Cloud Firestore backend " on iOS simulator behind socks5 proxy. 

### ISSUE THREAD

**Issue by jerrypainter** [firebase/firebase-ios-sdk#5377]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4
  * Firebase SDK version: 6.20.0
  * Firebase Component: Firestore
  * Component version: 1.11.2
  * Installation method: `CocoaPods | Carthage | Zip file` (select one)
CocoaPods

### [REQUIRED] Step 2: Describe the problem
Everything works fine on real device. Cannot connect to firestore backend on iOS simulator.
My mac and iPhone are both using same socks5 proxy service. When i run the app on device, everything works fine, but error showed on iOS simulator. 

I did some research, maybe the reason is that gRPC doesn't support socks5 proxy. Is there any way to solve this? I really don't get it why it works on device but not on simulator. Many thanks!

I'm in China, so I have to use proxy to call google service.

#### Steps to reproduce:
turn socks5 proxy on on your mac (shadowsocks or v2net, eg)
run any firebase project on simulator

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
`[Firebase/Firestore][I-FST000001] Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: failed to connect to all addresses
 This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.`
If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

**Comment by wilhuff** [comment]
@jerrypainter, thanks for writing in!

As you suspected, gRPC does not support SOCKS5 proxies. I can't really explain why it would work on a real device but not on a simulator--Firestore and gRPC aren't doing anything to connect to the local SOCKS server.

The latest discussion I can find on this is a [mailing list conversation from 2017](https://groups.google.com/d/topic/grpc-io/G09W1UJl8Ac/discussion). gRPC does support traditional HTTP proxies, and you can configure this with [environment variables](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md).

Unfortunately, without support for this from gRPC, there isn't anything we can do in the Firestore client to support your use case.
