### ISSUE TITLE
FR: Add support for filtering by target in Crashlytics console

### ISSUE THREAD

**Issue by morganchen12** [firebase/firebase-ios-sdk#5380]
This is necessary for viewing crash trends for targets with relatively fewer users, whose trends would be otherwise lost in the overwhelming amount of crashes from a more popular target. 

Originally discussed as part of #5126

**Comment by samedson** [comment]
Hey @morganchen12 - we've made strides towards filtering. Now when you set a custom key you can filter on it. We'd recommend devs set their target in a key and use that to filter.
