### ISSUE TITLE
FR: Allow snapshot listeners to be paused

### ISSUE THREAD

**Issue by bsod88** [firebase/firebase-ios-sdk#5390]
### Feature proposal

* Firebase Component: Firestore

**Problem:** To stop a snapshot listener from performing when the client is in the background, the listener must be removed. To resume listening, the listener must be re-initialized with a new closure. However, extra steps must be taken to preserve references to objects that have subscribed their completion handlers to the original closure.

**Solution:** Allow snapshot listeners to be paused and resumed (individually and/or collectively).

**Comment by wilhuff** [comment]
Hi! Thanks for the feature request.

Our API is already pretty large and while I can appreciate this could make some tasks easier, it seems like it's straightforward enough to capture your closure separately if you want to:

```swift
let listener = { snap, error in ... }
var registration = db.addSnapshotListener(listener)

// pause your listener
registration.remove()

// resume listening
registration = db.addSnapshotListener(listener)
```

Also note that it's already possible to effectively pause all listeners. If you call `disableNetwork`, Firestore will shut down all of its listeners (but also pause sending any outbound writes).
