### ISSUE TITLE
Crash file marker to indicate that a crash has occurred not working

### ISSUE THREAD

**Issue by SayaliMalekar** [firebase/firebase-ios-sdk#5393]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3
  * Firebase SDK version: 6.22.0
  * Firebase Component: Crashlytics 
  * Component version: 4.0.0-beta.6
  * Installation method: `CocoaPods'

### [REQUIRED] Step 2: Describe the problem
Api Crashlytics.crashlytics().didCrashDuringPreviousExecution() is not working.

#### Steps to reproduce:
Application  requirement is to check if app had crashed for previous  app launch.

Steps:
- Launch app.
- Force crash
-  Launch app again.
- Observer  Crashlytics.crashlytics().didCrashDuringPreviousExecution() returns false.
In this I was expecting  api should  return true.

Observation is that FIRCLSCreateCrashedMarkerFile(); is not called

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by morganchen12** [comment]
Potentially related to some of the issues that @samedson was investigating.

**Comment by samedson** [comment]
Hey thanks for reaching out. Could you share an xcode project or code that crashes that reproduces this?

**Comment by SayaliMalekar** [comment]
Application code is  same as https://github.com/firebase/quickstart-ios/tree/master/crashlytics. 

My build script: `"${PODS_ROOT}/FirebaseCrashlytics/run"
"find ${DWARF_DSYM_FOLDER_PATH}" -name "*.dSYM" | xargs -I \{\} "$PODS_ROOT/FirebaseCrashlytics/upload-symbols" -gsp "${PROJECT_DIR}/GoogleService-Info.plist" -p ios \{\}`

Investigation is that https://github.com/firebase/firebase-ios-sdk/blob/master/Crashlytics/Crashlytics/FIRCrashlytics.m#L133 is always false. 
This is as because "previously-crashed" file is never created. Also manually verified the path "crashedMarkerFileFullPath" and found that folder has never created.

I have tested this on Crashlytics 4.0.0

Also crash is not reported immediately on console.

My requirement is to check if app was crash in previous application launch.

Tried following code : 
```
  let crashlytics = Crashlytics.crashlytics()
        FirebaseConfiguration.shared.setLoggerLevel(.max)
        crashlytics.setCrashlyticsCollectionEnabled(false)
        
        crashlytics.checkForUnsentReports { (hasUnsent) in
           
            if hasUnsent {
                crashlytics.sendUnsentReports()
            } else {
                crashlytics.deleteUnsentReports()
            }
        }
        let x =  Crashlytics.crashlytics().didCrashDuringPreviousExecution()
        print("didCrashDuringPreviousExecution = \(x)")
```

**Comment by morganchen12** [comment]
@SayaliMalekar what target platform are you running on (simulator, device, iOS version)? Are you able to see any file writing errors in the device's logs?

**Comment by SayaliMalekar** [comment]
Hi,
With following steps,  able to see correct output:
- Build application
- Stop application in Xcode. [Debugger shouldn't be attached].
- launch application, crash it.
- Open application , observe Crashlytics.crashlytics().didCrashDuringPreviousExecution() returns true.

This issue can reproduce in following case :
- Firebase Crashlytics framework is configured in main project, it is configured in  internal framework. 
- If your main project has any Firebase product dependency.
- In this case main project as well as internal framework will require to call [FIRApp config].
- This will result in creation of two Crashlytics object https://github.com/firebase/firebase-ios-sdk/blob/master/Crashlytics/Crashlytics/Public/FIRCrashlytics.h#L31.
- So here one of the Crashlytic object will always return false as other has already cleared "previously-crashed" file. Most likely in internal framework.

**Comment by morganchen12** [comment]
Are you seeing duplicate class definition warnings in console when running your app?

**Comment by SayaliMalekar** [comment]
Can see following Warning:
` objc Class FIRCrashlytics is implemented in both "Framework" and "APP" One of the two will be used. Which one is undefined.`

**Comment by paulb777** [comment]
@SayaliMalekar The "undefined" log is indicative of two copies of Crashlytics in the app. It should be restructured so Crashlytics is not linked twice.

**Comment by SayaliMalekar** [comment]
By restructuring the code solved my issue.  Will there be a work around to decide which Crashlytics to be in use?

@paulb777 @morganchen12 @samedson Thank you for listening and helping to solve the issue.

**Comment by morganchen12** [comment]
It is not really possible to work around the duplicate class definitions at runtime issue in the SDK code itself, since it results in undefined behavior. Please let us know if you have any more questions and we'll continue to answer them in this thread.

Thanks!

**Comment by paulb777** [comment]
In the next major Firebase release, we're planning to remove the `static_framework` constraint from the pods sources in this repo so that the Podfile can determine whether they get linked statically or dynamically.  That should mitigate some of the "duplicate class definition" occurrences. See #2022
