### ISSUE TITLE
Integrate FirebaseCrashlytic sdk without CocoaPods and without.xcFramework

### ISSUE THREAD

**Issue by vijayviswas** [firebase/firebase-ios-sdk#5394]
I am integrating FrirebaseCrashlytics SDK in iOS without cocopods. I downloaded their xcFramework. But I can't use the xcFramework as the project is not compatible as my project as "legacy build settings" so I drag and drop ios-armv7_arm64 framework inside xcFramework to project and added Firebase.h and module.modulemap (my project uses both objc and swift). Also, I specified the Firebase.h in the bridging header. I get below error when I build.

Showing Recent Errors Only

/Users/xxxxx/Code/ios/tvOSApplications/App/App/Firebase.h:15:9: 'FirebaseCore/FirebaseCore.h' file not found

Showing Recent Errors Only

/Users/xxxxx/Code/ios/tvOSApplications/App/App/App-tvOS-Bridging-Header.h:27:9: Could not build module 'Firebase'

**Comment by paulb777** [comment]
@vijayviswas Thanks for the report.  The zip distribution requires Xcode 11 and the new Xcode build system. More about this question at https://stackoverflow.com/a/61217246/556617

If you need to stick with pre-Xcode 11 or the old build system, one option could be to integrate Crashlytics 3.x.

**Comment by vijayviswas** [comment]
@paulb777 If I use Crashlytics 3.x. then will I able to see the "Crash free user" data in Firebase dashboard?

**Comment by morganchen12** [comment]
Yes, you should be able to see crash-free users with Crashlytics 3.x.

**Comment by vijayviswas** [comment]
@morganchen12  Thanks I will try with Crashlytics 3.x as mean reason for me to move from Fabric& crashlytic sdk to FrirebaseCrashlytic is "Crash free users" data is not displayed in Firebase dashboard

**Comment by morganchen12** [comment]
Crashlytics 3.x is the old Fabric Crashlytics SDK, which can be used with either the Firebase console if you have already migrated or the Fabric console if you have not.

**Comment by ryanwilson** [comment]
Hey @vijayviswas, another option if you're okay with using Xcode 11 is to pull the regular `.framework` files from Carthage (or use Carthage itself).

The reason Xcode 11 is required still is because the binaries were built with Xcode 11 and bitcode support hasn't been backwards compatible in our experience (Xcode 10 doesn't handle binaries built with Xcode 11 well).

The links for versions can be found here: https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashlyticsBinary.json

Let us know if that helps as well!

**Comment by vijayviswas** [comment]
@ryanwilson  - I am able to download the .framework file. I will try in iOS project. 
Question- Does this framework works for tvOS?

**Comment by ryanwilson** [comment]
Unfortunately it does not, nor does the current zip file (XCFramework). The only SDK support for tvOS at the moment is through CocoaPods. 

You can +1 the request in #4550, as mentioned in this comment it's probably not too difficult to add tvOS support in our ZipBuilder tool if you wanted to package tvOS frameworks yourself (CocoaPods would need to be installed, but not used for the project) https://github.com/firebase/firebase-ios-sdk/issues/4550#issuecomment-599811239

**Comment by vijayviswas** [comment]
@ryanwilson I have downloaded the FirebaseCrashlytic.framework from below link
https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashlyticsBinary.json

I imported the #import <FirebaseCrashlytics/FirebaseCrashlytics.h> in appdelegate 
But  [FIRApp configure]; throw errors "Use of undeclared identifier 'FIRApp'" 
Do I need to add any supporting frameworks? 
NOTE: I removed the olf fabrics and crashlytics sdk from workspace before I add FirebaseCrashlytic.framework

**Comment by morganchen12** [comment]
You'll need to include all of Crashlytics' dependencies. It may be simpler for you to just use Carthage and install an older version of Firebase, including FirebaseCrashlytics. You can do so by following the instructions in the [Carthage guide](https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md).

**Comment by vijayviswas** [comment]
@morganchen12 - I installed the carthage  and added all the dependency frameworks. But I couldnt find the FirebaseCrashlytics/run" script in carthage "FirebaseCrashlytics.framework"

**Comment by paulb777** [comment]
See the Crashlytics specific instructions at the bottom of the section -https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md#carthage-usage

**Comment by vijayviswas** [comment]
@paulb777  @morganchen12  @ryanwilson  Thanks for the help. I am able to integrate the sdk in iOS project.  
Hope similar solution would be avilable soon for tvOS #4550

**Comment by morganchen12** [comment]
No problem @vijayviswas. I'll close this issue now to mark it as resolved, but if you have further questions feel free to continue commenting on the closed issue.
