### ISSUE TITLE
I can't upgrade GoogleDataTransportCCTSupport to 3.0.0

### ISSUE THREAD

**Issue by demonnboy** [firebase/firebase-ios-sdk#5395]
I can't upgrade GoogleDataTransportCCTSupport to 3.0.0, but firebase was already 6.22.0,please help me, because my app often crash,

 pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Analytics'
  pod 'Firebase/Performance'

**Comment by paulb777** [comment]
GoogleDataTransportCCTSupport 3.0.0 has not yet published to CocoaPods. It's still be stabilized along with Firebase 6.23.0 and targeted to release next week.

**Comment by morganchen12** [comment]
@demonnboy I'll close this issue for the time being since GoogleDataTransportCCTSupport 3.0.0 isn't released yet, but if you are still unable to upgrade after Firebase 6.23.0 is released please comment and I'll re-open the issue.
