### ISSUE TITLE
Automatic merge when existing account with email&password provider on Firebase

### ISSUE THREAD

**Issue by TheJonk** [firebase/firebase-ios-sdk#5400]
Step 1: Describe your environment

  * Xcode version: 11.4
  * Firebase SDK version: react-native-firebase 5.6.0
  * Firebase Component: Auth (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 6.15.0
  * Installation method: CocoaPods

Step 2: Describe the problem

Hi! I've been using invertase@react-native-apple-authentication to implement Sign in with Apple combined with firebase authentication.

When I perform this code snippet and choosing "Share my Email" and I already have an existing “email & password-provider” on Firebase with the same email as the one I have on my Apple ID, the providers **automatically merge**, instead of throwing an error after calling _firebase.auth().signInWithCredential(credential)_ - which is against Apple's guidelines that require an app to ask for permission before connecting another auth provider with the Apple auth provider. 

```
import appleAuth, { AppleAuthRequestScope, AppleAuthRequestOperation } from '@invertase/react-native-apple-authentication'

const appleAuthRequestResponse = await appleAuth.performRequest({
				requestedOperation: AppleAuthRequestOperation.LOGIN,
				requestedScopes: [AppleAuthRequestScope.EMAIL, AppleAuthRequestScope.FULL_NAME],
})
const { nonce, identityToken } = appleAuthRequestResponse
const appleCredential = firebase.auth.AppleAuthProvider.credential(identityToken, nonce)
const userCredential = await firebase.auth().signInWithCredential(appleCredential)
```

If I instead were to use for example Facebook sign in through react-native-fbsdk to sign in with these lines: 

```
const credential = firebase.auth.FacebookAuthProvider.credential(accessToken)
firebase.auth().signInWithCredential(credential)
```

the auth module correctly throws an error ‘auth/account-exists-with-different-credentials’ since it detects that an account already occupies the email-address on firebase.

The issue is that I cannot stop the merge from happening during the sign in flow, unless I manually prevent it by looking up the authenticated Apple email's firebase login providers in-between the request and the sign-in. 

I’d wish to be able to handle an error such as auth/account-exists-with-different-credentials even when signing in with Apple, but unfortunately nothing gets thrown.

Is this behaviour intended?

Kind regards, Jonathan

**Comment by ryanwilson** [comment]
@renkelvin can you please take a look and see if this is intended behaviour?

**Comment by renkelvin** [comment]
@TheJonk This is intended behaviour. Verified federation provider (Google, Apple etc.) will be auto linked while unverified federation provider (Facebook) won't.
As for Apple's guidelines, we have confirmed with legal team. But please let us know if you encount into any problem.
