### ISSUE TITLE
FirebaseProtobufBinary.json file returns 404

### ISSUE THREAD

**Issue by joalbright** [firebase/firebase-ios-sdk#5401]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: NA
  * Firebase SDK version: NA
  * Firebase Component: Protobuf
  * Component version: All
  * Installation method: Carthage (Binary File)

#### Steps to reproduce:

Going to the [Binary URL](https://dl.google.com/dl/firebase/ios/carthage/FirebaseProtobufBinary.json) produces a 404 error, which results in the inability to use it with Carthage.

#### Relevant Code:

```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseProtobufBinary.json"
```

**Comment by paulb777** [comment]
@joalbright Thanks for the report.  This is an example of us prematurely updating the docs before next week's release.  For Firebase 6.22.0 and earlier, `Protobuf.framework` is included in other directories and `FirebaseProtobufBinary.json` should not be included.

**Comment by joalbright** [comment]
@paulb777 No worries at all. Thanks for the heads up. I am implementing FirebaseRemoteConfig and I am trying to troubleshoot what it is missing for it. I will continue my search. :)
