### ISSUE TITLE
Upgrading Frameworks to XCFrameworks requires Mac app distribution certification for codesigning

### ISSUE THREAD

**Issue by kevinfarst-earnin** [firebase/firebase-ios-sdk#5403]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.2.1
  * Firebase SDK version: 6.22.0
  * Firebase Component: Analytics, Core, Crashlytics, RemoteConfig
  * Component version: 6.4.1, 6.6.6, 4.0.0-beta.7, 4.4.9
  * Installation method: Zip file

#### Steps to reproduce:

Previously using manual `.framework` distributions with no issues.

1. Downloaded latest ZIP release of frameworks
2. Replaced listed components and their dependencies with the new `.xcframework` binaries
3. Opened each `.xcframework` and removed the `ios-x86_64-maccatalyst` architecture as well as its entry in the `'Info.plist` in `AvailableLibraries`
4. Compiles and builds fine locally
5. Codesigning for distribution to the App Store now requires the Mac app distribution certificate which we neither have nor use.

#### Relevant Code:

```
xcodebuild -exportArchive -exportOptionsPlist /path/to/options.plist -archivePath /path/to/debug.xcarchive -exportPath /path/to/export/folder
...
Error Domain=IDECodesignResolverErrorDomain Code=1 "No signing certificate "Mac App Distribution" found" UserInfo={IDEDistributionIssueSeverity=3, NSLocalizedRecoverySuggestion=No "Mac App Distribution" signing certificate matching team ID "teamID" with a private key was found., IDEProvisioningError_UserInfoKey_IDEProvisioningErrorSpecifier=Mac App Distribution, NSLocalizedDescription=No signing certificate "Mac App Distribution" found, IDEProvisioningError_UserInfoKey_IDEProvisioningErrorPlatform=com.apple.platform.macosx, IDEProvisioningError_UserInfoKey_IDEProvisioningErrorAction=5, IDEProvisioningError_UserInfoKey_IDEProvisioningErrorTeam=<IDEProvisioningBasicTeam: 0x7fc0a8f65d80; teamID='teamID', teamName='(null)'>}
```

**Comment by morganchen12** [comment]
To work around this, you can remove the `.framework` bundles from the subfolders of the XCFrameworks and use them directly.

Also double check your project configuration doesn't have any references to Catalyst or macOS.

**Comment by paulb777** [comment]
Yep, it sounds strange since the `.frameworks` embedded in the `.xcframeworks` should be exactly the same as before.  Another workaround would be to collect the frameworks from a [Carthage install](https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md).

Thanks for the report @kevinfarst-earnin.  We want to hear about any usability issues caused by the transition to xcframeworks.

**Comment by kevinfarst-earnin** [comment]
@morganchen12 Since the frameworks are built for separate architectures, this would require additional configuration between building for the Simulator and a physical device correct?

Additionally, it looks like the only references we have in our build config related to macOS/Catalyst is the build setting `SUPPORTS_MACCATALYST = NO`. One other item to note, for our Release schema we have `Build Active Architecture Only` set to `No`.

@paulb777 I'll attempt to pull the frameworks in through Carthage and see if we have any success through that as well.

**Comment by morganchen12** [comment]
You're right, the frameworks in the xcframework bundle should only contain one architecture slice each.

Are you using Automatic Signing in Xcode? If so, can you try manually signing your release bundle?

**Comment by kevinfarst-earnin** [comment]
@paulb777 @morganchen12 The issue was due to the `upload-symbols` script being moved into a module that is code signed on release. Previously this was located in the `Pods` module within the Fabric SDK. I removed both the `run` and `upload-symbols` scripts as well as the Build Phases script because we upload our dSYMs through the Fastlane command `upload_symbols_to_crashlytics`. 

One final question if you don't mind, I realize this prevents symbols from being uploaded during development, but does removing this script cause any impact on a production build, even though we are uploading the dSYMs through Fastlane? Thanks!

**Comment by morganchen12** [comment]
It should not. The `upload-symbols` and `run` scripts are not supposed to be bundled in your app (and I think on iOS bundling executables like `upload-symbols` is not allowed).

If you're worried, you could add a custom script to Xcode to export your dSYMs on each build to a directory on disk and then upload them to Firebase later if console says you're missing dSYM files.

**Comment by paulb777** [comment]
I'm going to close since the original issue seems to be resolved. We can continue the conversation here or in another issue if there are additional questions.

**Comment by 1277990891** [comment]
@paulb777 @morganchen12, I also encountered this problem "requires Mac app distribution certification for codesigning after upgrading Frameworks to XCFrameworks", Then I remove the .framework of ios-x86_64-maccatalyst from the subfolders of the XCFrameworks and use them directly. our build config related to macOS/Catalyst is the build_setting SUPPORTS_MACCATALYST = NO. while the FirebaseCrashlytics sdk works well, but when we make build by jenkins, it also prompt this error. Is there any other way？Thanks.

**Comment by morganchen12** [comment]
You should check how your app is being bundled on jenkins. If `upload-symbols` is being bundled into your app, you need to remove it from the Copy Resources phase of your build.

**Comment by 1277990891** [comment]
> You should check how your app is being bundled on jenkins. If `upload-symbols` is being bundled into your app, you need to remove it from the Copy Resources phase of your build.

Thanks ,it works for me.
