### ISSUE TITLE
InAppMessaging does not build in extension targets

### ISSUE THREAD

**Issue by koxon** [firebase/firebase-ios-sdk#5404]
### Feature proposal

* Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)

FirebaseInAppMessaging doesn't support "sharedApplication".

Version: 0.19.2

As a result we can't compile the application and can't use this feature.

Please advise
thank you

**Comment by morganchen12** [comment]
Hey @koxon, what's the use case you're trying to support here? In-app modal dialogues are out of place in many extension use cases.
