### ISSUE TITLE
[!] Unable to find a specification for `GoogleDataTransport (~> 5.1)` depended upon by `GoogleDataTransportCCTSupport`

### ISSUE THREAD

**Issue by benv33** [firebase/firebase-ios-sdk#5415]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4.1
  * Firebase SDK version: 6.22.0
  * Firebase Component: -
  * Component version: -
  * Installation method: `CocoaPod

### [REQUIRED] Step 2: Describe the problem

When running pod install or pod update I have this issue:
[!] Unable to find a specification for `GoogleDataTransport (~> 5.1)` depended upon by `GoogleDataTransportCCTSupport`

GoogleDataTransportCCTSupport has been updated this week independently from Firebase:
Installing GoogleDataTransportCCTSupport 2.0.3 (was 2.0.2 and source changed to `https://cdn.cocoapods.org/` from `trunk`)

#### Steps to reproduce:

run pod install

#### Relevant Code:

Pod file :
platform :ios, '11.4'
use_frameworks!
    pod 'Firebase/Auth'
    pod 'Firebase/Messaging'
    pod 'Firebase/Firestore'
    pod 'Firebase'

**Comment by benv33** [comment]
pod repo update

or 

pod repo remove master
pod setup

does not solve the issue

**Comment by paulb777** [comment]
@benv33 Thanks for the report. GoogleDataTransport > 5.1 should be available on CocoaPods trunk. See https://github.com/CocoaPods/Specs/tree/master/Specs/0/6/a/GoogleDataTransport.

Would you share the exact error message you're getting from `pod update`?

**Comment by benv33** [comment]
[!] Unable to find a specification for `GoogleDataTransport (~> 5.1)` depended upon by `GoogleDataTransportCCTSupport`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by paulb777** [comment]
Strange! Perhaps something else about your configuration. Another thing to try is `rm -rf ~/.cocoapods`

**Comment by benv33** [comment]
Thanks it works now!

**Comment by chinghoi** [comment]
> Strange! Perhaps something else about your configuration. Another thing to try is `rm -rf ~/.cocoapods`
Thanks
