### ISSUE TITLE
FR: Specify dispatchQueue per FIRStorageUploadTask

### ISSUE THREAD

**Issue by yams93** [firebase/firebase-ios-sdk#5417]
### Feature proposal

* Firebase Component: Storage

Hello,

All Firebase storage uploads seem to share the same dispatch queue (the dispatch queue that is created in the FIRStorage object). I am using a NSOperationQueue with maxConcurrentOperationCount set as NSOperationQueueDefaultMaxConcurrentOperationCount to allow the system to manage how many uploads can happen concurrently. I wanted to pass in the dispatch queue that each NSOperation is using into the FIRStorageUploadTask initializer:

```
FIRStorageUploadTask *task = [[FIRStorageUploadTask alloc] initWithReference:self
                                         fetcherService:_storage.fetcherServiceForApp
                                          dispatchQueue:_storage.dispatchQueue
                                                               file:fileURL
                                                           metadata:metadata];
 ```
But the initializer is not exposed in the FIRStorageUploadTask.h file. If I have to use the public API (i.e putFile:), is there a way I can change the queue that the uploads will happen on? Is there a reason why we cannot specify the queue the uploads will occur on? Does the Firebase storage SDK handle concurrent batch uploads without any additional work on my part?  

If you can shed some light on this or direct me to the documentation discussing these issues that would be great. Thanks in advance.

**Comment by paulb777** [comment]
I'm going to close since there hasn't been a thumbs-up or comment. If you're interested, please comment to reopen or create a new issue referring to this one.
