### ISSUE TITLE
Fetch timeout not working as expected

### ISSUE THREAD

**Issue by kushalpal17** [firebase/firebase-ios-sdk#5422]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 'Firebase/RemoteConfig', '6.21.0' pod version
  * Firebase Component: Remote Config
  * Component version: 6.21.0
  * Installation method: CocoaPods 

### [REQUIRED] Step 2: Describe the problem

I read that if fetchTimeout  is 0 then it will always load new data from Remote Config.

#### Steps to reproduce:

Step-1 I called FirebaseApp.configure()
Step-2 I configured RemoteConfigSettings
Step-3 call fetchAndActivate

#### Relevant Code:
         FirebaseApp.configure()
         let settings = RemoteConfigSettings()
        
        #if DEBUG
            settings.minimumFetchInterval = 0
            settings.fetchTimeout = 0
        #else
            settings.fetchTimeout = 3.0
            settings.minimumFetchInterval = 3600
        #endif
        
        RemoteConfig.remoteConfig().configSettings = settings

         fetchAndActivate { _ , error in
            completion?(error)
         }

**Comment by morganchen12** [comment]
This is most likely a result of the behavior specified [here](https://github.com/firebase/firebase-ios-sdk/issues/4740#issuecomment-577970315).

**Comment by kushalpal17** [comment]
@morganchen12 I will really appreciate to provide correct documentation, I can refer that. Currently I am referring https://firebase.googleblog.com/2019/08/remote-config-v2-sdk-update.html

**Comment by paulb777** [comment]
I'm going to close this in favor of #4740. Let's continue the conversation there.
