### ISSUE TITLE
FirebaseApp.configure() crash the app

### ISSUE THREAD

**Issue by Mark-Thabit** [firebase/firebase-ios-sdk#5425]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4
  * Firebase SDK version: 6.22.0
  * Firebase Component: Core
  * Component version: 6.22.0 (It work just fine with version 6.17.0)
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem
<img width="1440" alt="Screen Shot 2020-04-21 at 5 08 57 PM" src="https://user-images.githubusercontent.com/56033650/79882530-0dcc3600-83f3-11ea-9317-7c0dc041250a.png">

App just crashes when it hit that Line `FirebaseApp.configure()`

*** Terminating app due to uncaught exception 'com.firebase.installations', reason: 'The default FirebaseApp instance must be configured before the defaultFirebaseApp instance can be initialized. One way to ensure that is to call `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) in the App Delegate's `application:didFinishLaunchingWithOptions:` (`application(_:didFinishLaunchingWithOptions:)` in Swift).'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e3dcce __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50b3b9b2 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23e3db0c +[NSException raise:format:] + 188
	3   Application                         0x000000010569a04e +[FIRInstallations installations] + 110
	4   Application                         0x0000000105688def +[FIRAnalytics updateFirebaseInstallationID] + 31
	5   Application                         0x0000000105688d2a +[FIRAnalytics startWithConfiguration:options:] + 555
	6   eGamers Beta                        0x0000000100bbe942 -[FIRApp configureCore] + 386
	7   eGamers Beta                        0x0000000100bbe4bf +[FIRApp addAppToAppDictionary:] + 127
	8   eGamers Beta                        0x0000000100bbd764 +[FIRApp configureWithName:options:] + 1284
	9   eGamers Beta                        0x0000000100bbd11f +[FIRApp configureWithOptions:] + 143
	10  eGamers Beta                        0x0000000100bbd06d +[FIRApp configure] + 157
	11  eGamers Beta                        0x00000001004497e5 $s12eGamers_Beta11AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0k6LaunchJ3KeyaypGSgtF + 9845
	12  eGamers Beta                        0x000000010044a1f3 $s12eGamers_Beta11AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0k6LaunchJ3KeyaypGSgtFTo + 211
	13  UIKitCore                           0x00007fff48c0fecc -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 232
	14  UIKitCore                           0x00007fff48c1186b -[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:] + 3985
	15  UIKitCore                           0x00007fff48c1742d -[UIApplication _runWithMainScene:transitionContext:completion:] + 1226
	16  UIKitCore                           0x00007fff48322a61 -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] + 122
	17  UIKitCore                           0x00007fff4882d065 _UIScenePerformActionsWithLifecycleActionMask + 83
	18  UIKitCore                           0x00007fff48323573 __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke + 198
	19  UIKitCore                           0x00007fff48322f82 -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:] + 296
	20  UIKitCore                           0x00007fff483233a0 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 818
	21  UIKitCore                           0x00007fff48322c35 -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:] + 345
	22  UIKitCore                           0x00007fff48327226 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke_2 + 178
	23  UIKitCore                           0x00007fff48743415 +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:] + 852
	24  UIKitCore                           0x00007fff4884b7c2 _UISceneSettingsDiffActionPerformChangesWithTransitionContext + 240
	25  UIKitCore                           0x00007fff48326f41 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke + 153
	26  UIKitCore                           0x00007fff4884b6c5 _UISceneSettingsDiffActionPerformActionsWithDelayForTransitionContext + 84
	27  UIKitCore                           0x00007fff48326daf -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] + 381
	28  UIKitCore                           0x00007fff4817a968 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke + 657
	29  UIKitCore                           0x00007fff48179527 -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 253
	30  UIKitCore                           0x00007fff4817a692 -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 210
	31  UIKitCore                           0x00007fff48c15975 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 512
	32  UIKitCore                           0x00007fff4876a160 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 361
	33  FrontBoardServices                  0x00007fff36c6091e -[FBSSceneImpl _callOutQueue_agent_didCreateWithTransitionContext:completion:] + 419
	34  FrontBoardServices                  0x00007fff36c869b1 __86-[FBSWorkspaceScenesClient sceneID:createWithParameters:transitionContext:completion:]_block_invoke.154 + 102
	35  FrontBoardServices                  0x00007fff36c6b347 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 220
	36  FrontBoardServices                  0x00007fff36c86642 __86-[FBSWorkspaceScenesClient sceneID:createWithParameters:transitionContext:completion:]_block_invoke + 355
	37  libdispatch.dylib                   0x0000000106739e8e _dispatch_client_callout + 8
	38  libdispatch.dylib                   0x000000010673cda2 _dispatch_block_invoke_direct + 300
	39  FrontBoardServices                  0x00007fff36cac2d9 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
	40  FrontBoardServices                  0x00007fff36cabfc7 -[FBSSerialQueue _queue_performNextIfPossible] + 441
	41  FrontBoardServices                  0x00007fff36cac4d6 -[FBSSerialQueue _performNextFromRunLoopSource] + 22
	42  CoreFoundation                      0x00007fff23da1c71 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	43  CoreFoundation                      0x00007fff23da1b9c __CFRunLoopDoSource0 + 76
	44  CoreFoundation                      0x00007fff23da1374 __CFRunLoopDoSources0 + 180
	45  CoreFoundation                      0x00007fff23d9bf6e __CFRunLoopRun + 974
	46  CoreFoundation                      0x00007fff23d9b884 CFRunLoopRunSpecific + 404
	47  GraphicsServices                    0x00007fff38b5ac1a GSEventRunModal + 139
	48  UIKitCore                           0x00007fff48c19220 UIApplicationMain + 1605
	49  eGamers Beta                        0x000000010045758b main + 75
	50  libdyld.dylib                       0x00007fff519b910d start + 1
)

#### Steps to reproduce:

it happens upon application start.
we are using Crashlytics, and Analytics, Cloud Messaging, In-App Messaging, AdMob, GoogleMaps, and GooglePlaces as well

**Comment by Mark-Thabit** [comment]
@maksymmalyhin Thanks for your reply

I am using 

```
pod 'Google-Mobile-Ads-SDK'
pod 'Firebase/Analytics'
```

in a dynamic framework (I think) because when I removed these dependencies, the app works just fine without any crash

**Comment by morganchen12** [comment]
Do you have warnings about duplicate class implementations in your app's runtime logs?

**Comment by Mark-Thabit** [comment]
Yes, I had those logs

**Comment by morganchen12** [comment]
Unfortunately, you'll either have to abandon the dynamic framework approach and link all dependencies directly into your app or you'll have to change your dynamic framework into a static one. What you were doing before was technically undefined behavior, even though it didn't crash. A recent change in Firebase recently exposed this undefined behavior in apps by causing them to crash on launch.

Read [Maksym's doc](Using Firebase from a Framework or a library) for more details.

**Comment by Mark-Thabit** [comment]
I had to remove all dependencies from my framework and now it's working fine,
Thanks for the heads up👌, didn't expect that my framework was the problem, 

This even fix another weird behavior I had which was the change of firebase token used for push notification more frequently, it was changing two different times each time I open the app which is a weird thing to happen

Thanks guys, Really appreciate your help

**Comment by morganchen12** [comment]
Glad we could help! I'll close this issue to mark it as resolved, but if you have any more questions feel free to continue commenting or open a new issue.
