### ISSUE TITLE
VeraCode Unchecked Error Condition FIRCLSReportAdapter.m

### ISSUE THREAD

**Issue by YessineM** [firebase/firebase-ios-sdk#5428]
**Environment**

Xcode version: 11.3.1
Firebase SDK version: 6.21.0
Firebase Component: Crashlytics
Installation method: CocoaPods 

**Description:** 

The result of this call to malloc() is not checked for success before being used. This can result in application instability or crashing if memory is not available.

**Relevant Code:**

../Record/FIRCLSReportAdapter.m 159

 .../Record/FIRCLSReportAdapter.m 234

**Comment by morganchen12** [comment]
Thanks for reporting @YessineM, a fix is up at #5431.
