### ISSUE TITLE
Memory Leak Firebase/Admob 6.23.0

### ISSUE THREAD

**Issue by Sunrise17** [firebase/firebase-ios-sdk#5436]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4.1
  * Firebase SDK version: 6.23.0
  * Firebase Component: Google-Mobile-Ads-SDK
  * Component version: (~> 7.50)
  * Installation method: `CocoaPods`

### [REQUIRED] Step 2: Describe the problem

As soon as i have loaded GADRequest `rewardedAd.load(GADRequest())` in viewDidLoad, memory leak occurs as follows;

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Monitoring is made on real iPhone device, iOS version 12.4.5.

<img width="1414" alt="Ekran Resmi 2020-04-22 13 11 21" src="https://user-images.githubusercontent.com/26038249/79970936-5986ea00-849c-11ea-9844-607a91038f05.png">

Without loading GADRequest, there is no leak;
<img width="1410" alt="Ekran Resmi 2020-04-22 13 17 59" src="https://user-images.githubusercontent.com/26038249/79970919-525fdc00-849c-11ea-8645-5bdf41e213b8.png">

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulb777** [comment]
Tracked internally at b/154712386

**Comment by morganchen12** [comment]
@Sunrise17 this retain cycle is manually broken after an ad load is finished and should persist only for the duration of the ad load. If you run the leaks instrument for longer, are you able to see the leaks disappear, or do they continue to accumulate over time?

**Comment by Sunrise17** [comment]
@morganchen12, yes leaks happened during the load of the ad and it is not accumulating over time. Now, i have tested again, and even during the loading of the ad, i have not seen any leaks, you can see the graph following below. I have even played the ad and its reloaded again and it should not be seen any leak.

<img width="1417" alt="Ekran Resmi 2020-04-24 17 19 21" src="https://user-images.githubusercontent.com/26038249/80222616-cd1d2880-864f-11ea-8f02-41746b021981.png">
