### ISSUE TITLE
Deprecations in FIRAuth.m and FIRAuthNotificationManager.m

### ISSUE THREAD

**Issue by tfonfara** [firebase/firebase-ios-sdk#5437]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4.1
  * Firebase SDK version: 6.23.0
  * Firebase Component: Auth
  * Component version: 6.5.1
  * Installation method: CocoaPods

#### Steps to reproduce:

Just compile.

#### Relevant Code (incl. suggested fix):

FIRAuth.m:1523
```
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-implementations"
- (void)application:(UIApplication *)application
    didReceiveRemoteNotification:(NSDictionary *)userInfo {
  [self canHandleNotification:userInfo];
}
#pragma clang diagnostic pop
```

FIRAuth.m:1534
```
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-implementations"
- (BOOL)application:(UIApplication *)application
              openURL:(NSURL *)url
    sourceApplication:(nullable NSString *)sourceApplication
           annotation:(id)annotation {
  return [self canHandleURL:url];
}
#pragma clang diagnostic pop
```

FIRAuthNotificationManager.m:118
```
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
    } else if ([self->_application.delegate
                   respondsToSelector:@selector(application:didReceiveRemoteNotification:)]) {
      [self->_application.delegate application:self->_application
                  didReceiveRemoteNotification:proberNotification];
#pragma clang diagnostic pop
```

**Comment by paulb777** [comment]
@tfonfara Thanks for the report. Would you share the build configuration?  

We're not able to reproduce since with a standard CocoaPods installation, the FirebaseAuth podspec causes the iOS Deployment version for the FirebaseAuth pod build to be set to 8.0.

**Comment by tfonfara** [comment]
@paulb777 my deployment target is set to 11.0, there the issue appears. As the `#pragma clang diagnostic` statements are not available in the code I would see this as expected, as the mentioned methods are deprecated from 10.0+ (check here: https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623117-application?language=objc)

**Comment by paulb777** [comment]
@tfonfara How is the deployment target set to 11.0? When CocoaPods does an install for a pod, it uses the version from the podspec here - https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseAuth.podspec#L20

**Comment by tfonfara** [comment]
@paulb777 Apple used to refuse apps with different deployment targets in app and frameworks some time ago, that's why I had to add this line in the Podfile:
```
if target.platform_name == :ios
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $platformTarget_iOS
end
```
After that fix AppStoreConnect accepted my binaries (this fix came from somewhere in the CocoaPods Github project). This sets the deployment target up to my app's deployment target.

**Comment by paulb777** [comment]
Interesting.  That Podfile patch shouldn't be necessary for static frameworks like Firebase that link at build time and aren't part of the deployment package.

Nonetheless, it should be harmless for us to address those warnings, so we'll investigate.

Here's the full list when setting deployment target to iOS 13:

![Screen Shot 2020-04-22 at 8 56 41 AM](https://user-images.githubusercontent.com/73870/80004526-4ada0c00-8477-11ea-9fd5-7361d13072e4.png)
