### ISSUE TITLE
GADJSONSafeDictionary + 1881124 crash 

### ISSUE THREAD

**Issue by wangjunhua1** [firebase/firebase-ios-sdk#5446]
pod 'Google-Mobile-Ads-SDK', '7.57.0'
    pod 'Fabric', '1.10.2'
    pod 'Crashlytics', '3.14.0'
    pod 'FirebaseAnalytics','6.4.0'
    pod 'FirebaseAuth','6.5.1'
    pod 'Firebase','6.21.0'
    pod 'FirebaseCore','6.6.5'
    pod 'GoogleAppMeasurement','6.4.0'
    pod 'GoogleUtilities','6.5.2'
    pod 'FirebaseAuthInterop', '1.1.0'
    pod 'FirebaseCoreDiagnostics', '1.2.2'
    pod 'FirebaseCoreDiagnosticsInterop', '1.2.0'
    pod 'PromisesObjC', '1.2.8'
    pod 'FirebaseInstallations', '1.1.1'
    pod 'GoogleDataTransport', '5.1.0'
    pod 'GoogleDataTransportCCTSupport', '2.0.1'

<img width="818" alt="image" src="https://user-images.githubusercontent.com/11474284/80057296-c495f680-8558-11ea-88e7-4008ece3478e.png">

**Comment by paulb777** [comment]
@wangjunhua1 Thanks for the report.  Would you provide us additional context about the crash. What is the frequency? What types of devices? What OS versions?

**Comment by morganchen12** [comment]
This looks like a potential memory corruption issue. You can try running your app with address sanitizer, guard malloc, or zombies enabled to see if that turns up any findings.
