### ISSUE TITLE
Push notification not working on some device (Unexpected behaviour)

### ISSUE THREAD

**Issue by ankitjaiswal1994** [firebase/firebase-ios-sdk#5448]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4
  * Firebase SDK version: 5.14.0
  * Firebase Component: Messaging
  * Component version: 3.2.2
  * Installation method: CocoaPods 

### [REQUIRED] Step 2: 
Push notification not working on some device even after restarting and reinstalling app. Also it is successfully generating the token, when we send push from "https://fcm.googleapis.com/fcm/send" api it shows success but notification wont come. Also we tried from firebase console messaging section to sent globally and with the specific token too. It is only for some devices and even on the same device one day it will work and another day wont.

#### Steps to reproduce:

Random behaviour so unable to reproduce. Only thing is common sometimes it works on the same device and sometimes it wont.

**Comment by anshumandash1995** [comment]
Experiencing the same issue

**Comment by vishvabhatt** [comment]
Same, I've tried from PushTry and every other platform to test on my iOS device only with one specific correct token but still facing same issue.

**Comment by ankitjaiswal1994** [comment]
Just observed one behaviour, few hours ago device A is getting the notification but device B is not. But after 1 hour on the same build when tried to send global notification from firebase console device B starts getting the notification but now device A is not getting.

**Comment by ryanwilson** [comment]
Thanks for the report. 

@ankitjaiswal1994 the version of Firebase you're using is well over a year old - we're currently on Firebase 6.23.0.

@vishvabhatt  and @anshumandash1995 can you please share which version of Firebase you're using?

Without specific reproduction steps it'll be hard to track anything down here. It could be an issue with the backend or APNS itself.

@chliangGoogle do you know of any backend issues recently?

**Comment by ankitjaiswal1994** [comment]
@ryanwilson Thanks for your response.

I was using the exact same latest version 6.23.0. But in this thread someone mentioned that downgrading the version works fine https://github.com/firebase/firebase-ios-sdk/issues/2438

In conclusion, I am facing the same issue on latest and older version both.

**Comment by ryanwilson** [comment]
Do you have device logs you could share? Without logs and without a repro there's likely nothing we can do to make progress on this.

**Comment by ankitjaiswal1994** [comment]
@ryanwilson I don't what logs will help you. But I can give you the token which is not working. Here it is :
ctimO_nsM4I:APA91bGZtrZBFYvjfzvNgjfL0ioRcLDR2cVVNhGJPJEKwijK1Gqv2_kHaITCMCvjryQL5a_hWoW_gOACVggcZ66z5xR1OFqje3xZtF1VVKchatxXYhdTCIB3nrGzoTUKnZGoD84zaCf2

I hope using this token you can debug what is actually going wrong.

**Comment by morganchen12** [comment]
Hey all, if you're running into Messaging issues that you cannot reproduce but you are able to isolate individual Instance IDs that fail to receive messages, please [file a support issue](http://firebase.google.com/support) so the Firebase staff will be able to look directly at your project information.

**Comment by charlie8093** [comment]
Hi all, I am having the same issue myself using **Messaging 6.16.0.** So far the issue only seems to affect **iOS 13** devices (tested on 13.3 - 13.4.1), never happened on an older version so far.   The first difference I noticed between iOS 12 and 13 is that while for iOS 12 the framework returns nil as the fcmToken at fresh install, for iOS 13 I get the token from the previous app install until the defaultToken is downloaded.  Maybe this caching behaviour for the token could cause the issue?  

I am using **https://fcm.googleapis.com/fcm/send** from Postman to send the notification.
Instance ID: **dr1JrjVysEzBgHJOXSaIQ5**
Token: "dr1JrjVysEzBgHJOXSaIQ5:APA91bFqaOz1fqdeWVtHQH_mNCvDXckIv_XnWuNTy4B3T8C3SziwevFHlgSsBLPNSha0XCySjg9BhEiHBTCB5Rx4EtJrqRNs0aAHG6klUhXmbFVEzhTW4c4Pr3QQguWIQdS5_KR2H-jH"

P.S. If I try to send a push using a cached token (from a previous app install on the same device), I don't receive "error:NotRegistered" but a success. In the past, using an old token from the same device would give the mentioned error.
In order to get notifications working again on those devices, I had to do several reinstalls of the app.

**Comment by hohteri** [comment]
I'm having the same issue with 6.14.0 and watchOS. It used to work fine, what I have done meanwhile is upgraded to watchOS 6.2.5 beta. Something I noticed, is that instance ID (?) part of the token is 22 characters long compared to my iOS token, which is 11 (and contains an underscore).

Also I found out if I use the old sendToDevice() function firebase-admin (on Cloud Functions) the push notification is sent, if I use the send(), it fails either on invalid-arguments or not-registered depending if the token is new or not accordingly.

The watchOS push messaging is interesting as I'm not 100% sure which GoogleService-Info.plist I need to provide. In the watch extension I use watchkitextension plist but Firebase complains about it on startup (I've tried to use watchkitapp plist, but it doesn't affect the messaging outcome, it does not complain about the plist though):

`[Firebase/Core][I-COR000008] The project's Bundle ID is inconsistent with either the Bundle ID in 'GoogleService-Info.plist', or the Bundle ID in the options if you are using a customized options. To ensure that everything can be configured correctly, you may need to make the Bundle IDs consistent. To continue with this plist file, you may change your app's bundle identifier to 'xxx.yyy.zzz.watchkitapp.watchkitextension'. Or you can download a new configuration file that matches your bundle identifier from https://console.firebase.google.com/ and replace the current one.`

**Comment by chliangGoogle** [comment]
@charlie8093 your issue seems different than the one filed, can you file a new issue so we can follow up separately?

**Comment by chliangGoogle** [comment]
@ankitjaiswal1994 Can you provide debug log or file a customer support issue so we can follow up with you on the token query internally with our teams.

Here's how you collect the debugLog following the steps:
 Enable "debugLog" by adding -FIRDebugEnabled flag on your xcode scheme: more details here https://firebase.google.com/docs/analytics/debugview
