### ISSUE TITLE
Crashlytics Veracode Issue on ANSSettings.m

### ISSUE THREAD

**Issue by eugeneheckert** [firebase/firebase-ios-sdk#5457]
Greetings, 

I am using Veracode Tool for code static analysis
https://www.veracode.com
and I am facing one security issue on Crashlytics component

  * Xcode version: 11.3
  * Firebase SDK version: 6.18
  * Firebase Component: Crashlytics 
  * Component version: 3.14
  * Installation method: `CocoaPods`

the issue is: 
File - ANSSettings.m: 39

Description:  The application calls the NSURL.URLWithString:() function, which will result in data being transferred out of the application (via the network or another medium). This data contains sensitive information. 

Remediation: Ensure that the transfer of the sensitive data is intended and that it does not violate application security policy. This flaw is categorized as low severity because it only impacts confidentiality, not integrity or availability. However, in the context of a mobile application, the significance of an information leak may be much greater, especially if misaligned with user expectations or data privacy policies.

I have seen that Firebase has been updated for some Veracode issues already but I didn't see a fix/issue for this file and wanted to bring it up.

**Comment by samedson** [comment]
Hey thanks for reaching out @eugeneheckert - we've fixed these in the FirebaseCrashlytics SDK (version 4.0+). Check out the new version.
