### ISSUE TITLE
FirebaseCore not included in zip distribution

### ISSUE THREAD

**Issue by canatella** [firebase/firebase-ios-sdk#5462]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.2.1
  * Firebase SDK version: 6.23.0
  * Firebase Component: Firestore, Core
  * Component version: _____
  * Installation method: `Zip file` (select one)

#### Steps to reproduce:

It seems that the FirebaseCore library is not in the zip package, when linking I get missing symbol errors 
```
Undefined symbols for architecture arm64:
  "_FIRLogWarning", referenced from:
      ___70-[FIRAuthNotificationManager checkNotificationForwardingWithCallback:]_block_invoke in FirebaseAuth(FIRAuthNotificationManager.o)
      ___62-[FIRPhoneAuthProvider verifyClientWithUIDelegate:completion:]_block_invoke_3 in FirebaseAuth(FIRPhoneAuthProvider.o)
  "_OBJC_CLASS_$_FIRComponent", referenced from:
      objc-class-ref in FirebaseAuth(FIRAuth.o)
  "_OBJC_CLASS_$_GULSceneDelegateSwizzler", referenced from:
      objc-class-ref in FirebaseAuth(FIRAuth.o)
  "_FIRLogDebug", referenced from:
```

Which seems to be located in the FirebaseCore component but the zip has no such component. I can't use the cocoapods here because I'm using the sdk as part of the cpp sdk. I got it working by compiling the iOS SDK myself using a podfile in a throwaway project and adding the by products to the content of the zip file.

**Comment by paulb777** [comment]
FirebaseCore is included in the `Analytics` folder of the zip distribution. See #5 of the [instructions](https://github.com/firebase/firebase-ios-sdk/blob/master/ZipBuilder/Template/README.md#integration-instructions).

I'm going to close the issue, but feel free to continue the conversation here if you have additional questions.

**Comment by canatella** [comment]
Sorry, I skimmed over that file, my bad. Thank you!
