### ISSUE TITLE
Crash due to FirebasePerformance that affects Realm

### ISSUE THREAD

**Issue by kylebrowning** [firebase/firebase-ios-sdk#5469]
### Describe your environment

  * Xcode version: 11.4
  * Firebase SDK version: 6.23
  * Firebase Component: Performance
  * Component version: 3.1.11
  * Installation method: `CocoaPods`

### Describe the problem
Crash happening due to firebase performance being enabled, disabling it causes the crash to go away

#### Steps to reproduce:
Im afraid I can't reproduce the issue locally, I only see the crashes rising in Crashlytics

#### Relevant Crash:

```
Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x183e843d8 class_getSuperclass + 4
1  Realm                          0x1019a8dac RLMIsObjectSubclass + 72 (RLMUtil.hpp:72)
2  Realm                          0x101a23d1c RLMRegisterClassLocalNames(objc_class**, unsigned long) + 105 (RLMSchema.mm:105)
3  Realm                          0x101a24568 +[RLMSchema sharedSchema] + 2941 (memory:2941)
4  Realm                          0x101a188d0 +[RLMRealm realmWithConfiguration:error:] + 494 (RLMRealm.mm:494)
5  RealmSwift                     0x101ecdb80 Realm.init() + 4390902656 (<compiler-generated>:4390902656)
```

#### Other notes:
Related issues that have been opened.
- https://github.com/realm/realm-cocoa/issues/5618
- https://github.com/firebase/firebase-ios-sdk/issues/4850

Could this be related to all of the swizzling FirebasePerformance is doing?

**Comment by maksymmalyhin** [comment]
@kylebrowning Thank you for the report. 

This may be related to the way Performance doing ISA swizzling for some objects which may conflict with Realm scanning runtime. Concerns from #3300 may be relevant in this case. 

@kylebrowning I wonder if Realm is initialized after Firebase in your app? Taking into account a possible nature of the issue, changing Realm/Firebase order may be a workaround. I would suggest trying to initialize Real first and then Firebase. Could you please try it and let us know the result?

**Comment by kylebrowning** [comment]
Thanks, @maksymmalyhin yes Realm comes second, Firebase is the first thing we initialize. Will change the order and see if this resolves it.
