### ISSUE TITLE
Firebase Crashlytics Carthage Integration Docs are Wrong

### ISSUE THREAD

**Issue by Blackjacx** [firebase/firebase-ios-sdk#5472]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11
  * Firebase SDK version: newest
  * Firebase Component: Crashlytics
  * Component version: newest
  * Installation method: `Carthage`

#### Steps to reproduce:

1. Go to https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md
1. Scroll down to the Firebase Crashlytics section
1. The filepath `$(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)` doesn't exist on any computer. 

SRCROOT and BUILT_PRODUCTS_DIR are 2 completely different directories on a mac. They cannot be concatenated. I think you mean `${BUILT_PRODUCTS_DIR}/${INFOPLIST_PATH}`.

Should be fixed in the official documentation too.

**Comment by samedson** [comment]
Thanks for catching that @Blackjacx - gonna put up the fix
