### ISSUE TITLE
FR: Query `in` operator

### ISSUE THREAD

**Issue by nitrag** [firebase/firebase-ios-sdk#549]
It would be really really nice if we could query this in this SDK. Currently I'm having to store `room` references in my `/users/` Documents

Firestore Data Model for Chat app:
```
/users/
/users/{userId}/
/users/{userId}/rooms    (this is a DocumentReference Array of rooms)
/users/{userId}/first_name
/users/{userId}/last_name
/users/{userId}/last_active

/rooms/
/rooms/{roomId}/
/rooms/{roomId}/created
/rooms/{roomId}/last_updated
/rooms/{roomId}/users    (this is an String Array of userIds)
/rooms/{roomId}/messages/...
```

Server-side Rules:
`allow read, write: if request.auth.uid in resource.data.users;`

Proposed:
`roomsRef.where("users", "in", currentUserId)`

**Comment by wilhuff** [comment]
Thanks for writing in.

This is something we're looking at doing. Unfortunately I can't promise when it's going to happen, nor can I really promise if the design we land on will necessarily exactly match what you're asking for.

This specific use case (array of group members) is a specific requirement for adding this.

**Comment by wilhuff** [comment]
While we're still _very_ interested in this feature, there's little value in tracking this separately for just iOS. The canonical issue for this is firebase/firebase-js-sdk#321. I'll close this one as a duplicate.

**Comment by rockwotj** [comment]
@wilhuff this is `array-contains` no?

https://firebase.googleblog.com/2018/08/better-arrays-in-cloud-firestore.html

**Comment by mikelehen** [comment]
@wilhuff is OOO this week, but I think you're right @rockwotj.  array-contains should solve @nitrag's use case!

**Comment by nitrag** [comment]
I had been using this, do I need the `get()` if the match is already for the same level object?

```
service cloud.firestore {
  match /databases/{database}/documents {
    match /rooms/{roomId} {
      allow read, write: if request.auth.uid in get(/databases/$(database)/documents/rooms/$(roomId)).data.users;
      allow create: if request.auth != null;
    }
  }
}
```

**Comment by rockwotj** [comment]
You can't use `{roomId}` for queries in rules because we don't know what document IDs that will be returned at the time of rules evaluation.

For queries we populate the `resource` property with the minimal document guaranteed to be returned by all query results.

You want this rule:

`allow read, write: if request.auth.uid in resource.data.users`
