### ISSUE TITLE
[Crashlytics] Expose library & offset properties in FIRStackFrame

### ISSUE THREAD

**Issue by Aure77** [firebase/firebase-ios-sdk#5501]
### Feature proposal

* Firebase Component: Crashlytics

Expose `library` & `offset` properties in `FIRStackFrame`.

Why:
In previous Crashlytics lib (from Fabric), we can use `CLSStackFrame` `setLibrary` & `setOffset` methods to fill a stacktrace/frame. In this version, FIRStackFrame `library` & `offset` properties are present but not exposed in public API. There is a particular reason ? How can I set this properties from client side ?

```
FIRStackFrame *frame = [FIRStackFrame stackFrameWithSymbol:@"fn" file:@"file" line:200];
[frame setLibrary:@"lib"]; // should allow to set library
[frame setOffset:20]; // should allow to set offset
```

**Comment by samedson** [comment]
Hey thanks for the proposal @Aure77. I want to ask a couple questions to gauge how customers use these APIs:

1. For `library`, where do you see the value in the Crashlytics Console when you set it?

1. For `offset`, do you find this impacts the stacktrace you get in Crashlytics?
