### ISSUE TITLE
Add Firebase-Light (13 dependencies are way too much)

### ISSUE THREAD

**Issue by soryncrash13** [firebase/firebase-ios-sdk#5518]
### Feature proposal

* Firebase Component: Firebase/Analytics

Describe your use case and/or feature request here.

Hello there. I'll try to keep it as short as possible.
I only use firebase in my ios project because I need to use the crashlytics feature. If i don't install the firebase pod I don't get any crash reports in the console.firebase platform. There was used an old dependency (pod 'Firebase/Core', '~> 3.17.0') and I've just updated to pod 'FirebaseCore', '~> 6.6.7' but to my surprise there was no Firebase module anymore so for some reason I need to install pod 'Firebase/Analytics', '~> 6.23.0' to also get the "Firebase" module. I don't use any insights or analytics features whatsoever so I only need that main module. I'm curious why should i keep on using the latest version since it's still in objective c and now i have 13 dependencies in total just from Firebase/Analytics. I don't want to have 30 dependencies to compile each time just for this service. Couldn't you please add a more light-weighted version of firebase? I only use FirebaseApp.configure() so just for that no, I don't really plan on keeping this pod with a total of 13 DEPENDENCIES! No offence but this is really outraging, not to mention all firebase's documentation is outdated, old, not well explained and fabric was straightforward to use. If google doesn't afford this request of mine than I do not know who else will...
I'm really looking forward to hearing from you.

**Comment by paulb777** [comment]
@soryncrash13 Thanks for the report. I can understand how the output of `pod install` for Firebase can seem daunting.

Firebase has several features and is architected with multiple small libraries so that it is possible to make minimal installations for any selected set of features.  So, actually the intent of the many libraries is to enable lightweight installations.

The best way to get the Firebase module for a Crashlytics only installation is including `pod 'Firebase/Crashlytics'` in the Podfile.  If you also want Analytics capabilities, add `pod 'Firebase/Analytics'`. Usage of `pod 'Firebase/Core'` is deprecated and equivalent to `pod 'Firebase/Analytics'`.

If you have specific examples about poor or outdated documentation, please let us know and we'll address.

**Comment by soryncrash13** [comment]
Hello @paulb777 . Thank you so much for taking time to reply. Please, I want you to understand that I'm pissed on the situation not on any members or persons from anywhere, still I cannot help it but feel a bit frustrated.
I can see and understand how we have a granular approach over firebase in terms of installing only the desired set of features, but what concerns me is why do I have to install 13 dependencies for just one thing? I mean the old v3 and v4 "only" installs like 6-7 dependencies so I really don't want to get the newer version which drags over double the files. The project I'm working on I've almost finished re-writing and it used to have over 50 dependencies and it was a mess so I don't like dragging external libraries only if absolutely necessary (like firebase and stripe for example).
I tried installing like you've suggested above the 'Firebase/Crashlytics' pod but it also installs a lot of dependencies. I'm sure in the near future i won't have any choice since for the moment I still have the manually imported crashlytics and fabric frameworks from back in the day. It's frustrating thinking about dragging over a lot of files for something that used to only require 2 files.
Do you think there will ever be created a version of firebase library in swift or if there will be like a light version of firebase with less files?
Thank you very much. I'm looking forward to hearing from you.

**Comment by morganchen12** [comment]
Firebase is broken out into more dependencies in some cases to enable code-sharing between libraries, which has the overall effect of reducing code size rather than increasing it even though the number of dependency packages increases. If you're concerned about your app's build times or download size, you can profile your app bundle to see if Firebase is taking up a significant amount of space.

**Comment by soryncrash13** [comment]
Now it won't take so much to compile since i've got rid of at least 20 libs, but there are still quite some dependencies.
I still have another question and i don't find it documented anywhere in your docs. Why by using v3.x or v4.x i can just go in app delegate import Firebase and start using it, although using your latest version 6.x when i type import Firebase it says no such module Firebase?
Right now i'm using v4.x, but i don't have a bridging header even though i can use and import Firebase and it's working.
Thank you in advance.

**Comment by paulb777** [comment]
@soryncrash13, What's in the Podfile? See the description of how to include the Firebase module above.

**Comment by soryncrash13** [comment]
So besides other libraries that i'm using i also have this: pod 'Firebase/Core', '~> 4.0.3'. With this dependency I can go in app delegate and just straight up import Firebase and start using FirebaseApp.configure(options: ). If i remove this pod and i type in like this pod 'Firebase/Analytics', '~> 6.23.0', (even Firebase/Crashlytics) it does update the firebase dependencies, but i get an error in app delegate saying there's no such module 'Firebase'. Thing is right now i don't have any objc bridging header and i'd like to keep it this way. Even though in the official doc the steps are installing the pod and importing firebase, there seems to be working without this error and without mentioning anything about a bridging header.
Thank you.

**Comment by paulb777** [comment]
Does the  `no such module 'Firebase'.` error happen after trying to build in Xcode? An initial build is needed to prime the Xcode module cache.

**Comment by soryncrash13** [comment]
I've also tried cleaning and deleting the derived data and then building but same thing happened.

**Comment by morganchen12** [comment]
What version of CocoaPods are you using? Can you try to reproduce this build error in a new project and share that project with us?

**Comment by soryncrash13** [comment]
I'm using cocoapods version 1.9.1. Ok sure, i'll try it with a new project and send the repo via a comment here. Thank you.

**Comment by soryncrash13** [comment]
I cannot reproduce the error on a newly created app. I'm sorry for the long delay but I had a lot of work to do, but I haven't forgot for a second about this ticket. If it's ok, I'm gonna close this ticket. Could you please, before that, tell me if there's gonna be a "lighter" version of firebase crashlytics with less sub-dependencies? Thank you very much.

**Comment by paulb777** [comment]
We're investigating some ideas to eliminate and consolidate some of the dependencies, but no firm plans yet.

**Comment by soryncrash13** [comment]
Thank you very much. I hope it goes well. Take care. Have a great day.
