### ISSUE TITLE
Cannot send push notifications to iOS 13 devices (even with official example from quickstart repo)

### ISSUE THREAD

**Issue by nicoletapopepix** [firebase/firebase-ios-sdk#5519]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4.1
  * Firebase SDK version: 6.23.0
  * Firebase Component: Messaging
  * Component version: 4.3.1
  * Installation method: `CocoaPods`

#### Steps to reproduce:

Hi,

I cannot receive push notifications from Firebase at all. I did all necessary setup and I also double checked my code with a previous working project and it seems like I've reached a dead end. Tried both certificates and APN keys, double checked for typos and I couldn't find anything wrong. Then it crossed my mind to copy paste the code from quickstart repo and same result. Important to mention is that I've tested the APN token with an app (Pushever) and also on online websites and it seems I've managed to receive a push notification on the APN token alone. Also, in the code, the FCM token is generated in the same way as in my previous working project used as an example but I think the problem lies in the FCM token received from Firebase.

iOS project target: 13.0
I've updated to the newest Xcode only at the end of the day and it didn't work previously either.

#### Relevant Code:

--PushNotificationsManager class

internal class PushNotificationsManager: NSObject {
    
    // MARK: - Properties -
    
    private let userService = ServiceFactory.userService()
    
    // MARK: - Public Methods -
    
    func registerForPushNotifications(on viewController: UIViewController & AlertPresenter) {
        let authOptions: UNAuthorizationOptions = [.alert, .badge, .sound]
        
        self.setDelegates()
        
        UNUserNotificationCenter.current().requestAuthorization (
            options: authOptions,
            completionHandler: { authorized, error in
                
                guard authorized else {
                    DispatchQueue.main.async {
                        viewController.showAreYouSureAlert(title: "You don't have permission for push notifications!", message: "Please update it on Settings > App > Notifications.", yesMessage: Constants.SETTINGS) { _ in
                            UIApplication.shared.open(URL(string:UIApplication.openSettingsURLString)!)
                        }
                    }

                    return
                }
            
                if error == nil {
                    DispatchQueue.main.async {
                        InstanceID.instanceID().instanceID { (result, error) in
                            if let error = error {
                                print("Error fetching remote instance ID: \(error)")
                            } else if let result = result {
                                print("Remote instance ID token: \(result.token)")
                            }
                        }
                        
                        UIApplication.shared.registerForRemoteNotifications()
                        
                        self.updateFirestorePushTokenIfNeeded()
                        
                        App.userDefaults.set(true, forKey: "registeredAPN")
                    }
                }
            })
    }
    
    func arePushNotificationsAuthorized(completion: @escaping (_ authorized: Bool) -> Void) {
        let center = UNUserNotificationCenter.current()
        center.getNotificationSettings { (settings) in
            completion(settings.authorizationStatus == .authorized)
        }
    }
    
    func unregisterForPushNotifications() {
        UIApplication.shared.unregisterForRemoteNotifications()
    }
    
    func arePushNotificationsEnabled() -> Bool {
        return UIApplication.shared.isRegisteredForRemoteNotifications
    }
    
    func setDelegates() {
        Messaging.messaging().delegate = self
        UNUserNotificationCenter.current().delegate = self
    }
}

// MARK: - Private Methods -

private extension PushNotificationsManager {
    func updateFirestorePushTokenIfNeeded() {
        if let token = Messaging.messaging().fcmToken, let userId = App.authController.currentUID {   
            self.userService.update(field: "fcmToken", value: token, id: userId) { error in
                print("Error: \(error)")
            }
        }
    }
}

// MARK: - MessagingDelegate methods -

extension PushNotificationsManager: MessagingDelegate {
    func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String) {
        self.updateFirestorePushTokenIfNeeded()
    }
}

// MARK: - UNUserNotificationCenterDelegate methods -

extension PushNotificationsManager: UNUserNotificationCenterDelegate {
    func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void) {
        print("response: \(response)")
    }
    
    func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
        print("kind of notification: \(notification.request.content.title)")
        completionHandler([.alert, .sound, .badge])
    }
}

--- relevant AppDelegate methods

func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
FirebaseApp.configure()
...
pushNotificationsManager.setDelegates()
}

the registerForPushNotifications method is called after login result and the didReceiveRegistrationToken is called after every app launch.

If you need more details please let me know.

Thank you so much for your attention!

**Comment by nicoletapopepix** [comment]
I have changed the implementation by disabling method swizzling because I had to integrate Performance SDK and I found out that it could interfere with this method, and I have to say that now it's working perfectly! But I think this issue still needs attention, since I guess a lot of people would use method swizzling in the first place.

**Comment by chliangGoogle** [comment]
@nicoletapopepix You are saying with the same code/set up your notification will work if disable method swizzling? The same with quickstart sample?

**Comment by nicoletapopepix** [comment]
@chliangGoogle That's right.

**Comment by dickysuryos** [comment]
@chliangGoogle not working for me , after update to firebase sdk 6.23.0

**Comment by chliangGoogle** [comment]
@dickysuryos Are you using quickstart as well or your own app. If it's your own app, can you paste the related code part so we can take a look?

@nicoletapopepix @dickysuryos I will test on quickstart sample, but in the meantime, our [sample app](https://github.com/firebase/firebase-ios-sdk/tree/master/FirebaseMessaging/Apps/Sample) works for me and feel free to test it on your side. The messaging sample app is much up to date and might be a better reference at this point.

**Comment by chliangGoogle** [comment]
@nicoletapopepix Also can you share what exactly did you do when disable swizzling? Including plist file and source code update.

**Comment by chliangGoogle** [comment]
FYI, quickstart also works for me without doing any extra steps on swizzling. Please let us know your steps of disabling so we can help.

**Comment by nicoletapopepix** [comment]
@chliangGoogle sorry for the late reply. All I did was adding didReceiveMessage method in willPresent UN delegate method and application's didReceiveRemoteNotification:
 func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
        print("kind of notification: \(notification.request.content.title)")
        //swizzling disabled
        let userInfo = notification.request.content.userInfo
        Messaging.messaging().appDidReceiveMessage(userInfo)
        completionHandler([.alert, .sound, .badge])
    }

Also, in didRegisterForRemoteNotification I've added Messaging.messaging().apnsToken = deviceToken and in plist file I've set FirebaseAppDelegateProxyEnabled to NO.

I couldn't manage to test again the first solution cause I had a lot of work to do but as soon as I manage to do this, I'll let you know.

Thank you for all the help and support!

**Comment by chliangGoogle** [comment]
the first method is the reason. Without it (especially completionHandler([.alert, .sound, .badge])_, you will not see notification displayed when app is in foreground, making it look like it's not received.

Please reopen if you still have any further questions.

**Comment by nicoletapopepix** [comment]
I know that, but I didn't receive notifications in background either @chliangGoogle

**Comment by nicoletapopepix** [comment]
> the first method is the reason. Without it (especially completionHandler([.alert, .sound, .badge])_, you will not see notification displayed when app is in foreground, making it look like it's not received.
> 
> Please reopen if you still have any further questions.

the problem didn't lie in the way I received my notifications unfortunately

**Comment by chliangGoogle** [comment]
did you implement AppDelegate application:didReceiveRemoteNotification:fetchCompletionHandler:? without it, you won't receive in background either.

Again can you try again to see if you can reproduce on quickstart?

**Comment by nicoletapopepix** [comment]
Yes, I did implement that method. I'll let you know in a few hours if I managed to reproduce it on the quickstart project.

**Comment by nicoletapopepix** [comment]
Now it's working just fine. Thank you!
