### ISSUE TITLE
Several crashes seen for iOS 10 users.

### ISSUE THREAD

**Issue by pepejeria** [firebase/firebase-ios-sdk#5522]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4.1
  * Firebase SDK version: 6.23.0
  * Firebase Component: Not sure
  * Component version: _____
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

Seeing a lot of crashes lately in Firebase Crashlytics. Uploaded all dsyms but it still says that some optional are missing. 

**Crash 1)**

FSRWebSocket.m line 1845
-[_FSRRunLoopThread main]

Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_PROTECTION_FAILURE 0x00000000393d4000

**Crash 2)**

libobjc.A.dylib
objc_object::sidetable_release(bool)

Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_PROTECTION_FAILURE 0x0000000000e6d22c
objc_object::sidetable_release(bool)

#### Steps to reproduce:

**Note:** these crashes only affect iOS 10 users. 

Sorry for not providing a proper stack trace, I uploaded all dsyms but I still get this:
  ???                            0xe42160 (Missing)

etc

This started to happen about 2 weeks ago.

**Comment by p-nicolaou** [comment]
We've observed several crashes in our app as well. All of them on iOS 10 devices

**Comment by ryanwilson** [comment]
Thanks for the report and sorry for the troubles.

Do you have a device breakdown as well or only iOS version? This is likely an issue related to an Xcode 11.4 bug with 32 bit code generation, see existing issues that were also affected here: https://github.com/Firebase/firebase-ios-sdk/issues?q=label%3A%22Xcode+11.4+-+32+bit%22+

From the [Xcode 11.5 Beta release notes](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_5_beta_release_notes): Fixed an issue with incorrect code generation when targeting armv7 devices. (61901594)

I'll leave this open briefly to ensure that it is in fact 32 bit devices affected, a known workaround is to use Xcode 11.3 for the time being until Xcode 11.5 is released.

**Comment by p-nicolaou** [comment]
@ryanwilson Thank you for coming back to this so quickly.

For our case, I can see several crashes origin from iPhone 5c and iPad 4 devices. I will search further but looks like an Xcode bug, as you said.

**Comment by paulb777** [comment]
Since it seems to be the known Xcode 11.4 bug, I'll close for now, but can reopen if it turns out to be something else.
