### ISSUE TITLE
No updated credential when Sign in with Apple with the nonce.

### ISSUE THREAD

**Issue by Aymenworks** [firebase/firebase-ios-sdk#5529]
### [REQUIRED] Step 1: Describe your environment
Firebase SDK version: 6.13.0
Firebase Component: Auth
Component version: 6.4.0
  * Xcode version: 11.2.1
  * Firebase SDK version: __
  * Firebase Component: Auth
  * Component version: 6.5.2
  * Installation method: `CocoaPods` 

#### Steps to reproduce:

Good morning 👍 :)

My issue is very identical to what has been experienced in this other issue ticket https://github.com/firebase/firebase-ios-sdk/issues/4434

The difference is that the solution https://github.com/firebase/firebase-ios-sdk/issues/4434#issuecomment-564776016 is not OK on my side since the error is not returning any FIRAuthErrorUserInfoUpdatedCredentialKey information. But let's recap!

In our current setup, users are always logged in anonymously, then they can deicide to login/sign in, at which point we either link the anonymous user to the used provider or sign in.

```
return self.context.rx
                .link(user: user, toCredentials: providerCredential.credentials())
                .catchError { error -> PrimitiveSequence<CompletableTrait, Never> in
                    return self.context.rx.signIn(withCredential: providerCredential.credentials())
                        .concat(self.context.rx.delete(user: user))
                }
                .do(onCompleted: { [weak self] in
                    PersistenceStore.signInMethod = providerCredential.signInMethod
                    self?.context.dispatch {
                        $0.emit(.didLogin)
                    }
                })
```

In the case the user is currently signed In anonymously and already signed in before, calling the link method will return an error saying that the email address is already in use:

```
Error Domain=FIRAuthErrorDomain Code=17007 "The email address is already in use by another account." UserInfo={NSLocalizedDescription=The email address is already in use by another account., FIRAuthErrorUserInfoNameKey=ERROR_EMAIL_ALREADY_IN_USE}
```

When it happens, I sign in the user with the signIn(credentials) which returns:
```
Error Domain=FIRAuthErrorDomain Code=17094 "Duplicate credential received. Please try again with a new credential." UserInfo={NSLocalizedDescription=Duplicate credential received. Please try again with a new credential., FIRAuthErrorUserInfoNameKey=ERROR_MISSING_OR_INVALID_NONCE}
```

Why? It's because I am using the nonce for the credentials. For when we call the link method, I suppose that this nonce value becomes not reusable, so when trying to sign in just after, we are currently using the same nonce ( same AuthCredentials ) which generate this error.

The solution exposed there  https://github.com/firebase/firebase-ios-sdk/issues/4434#issuecomment-564776016 somehow is not working for me because I cannot find any `FIRAuthErrorUserInfoUpdatedCredentialKey` key in the error.

Any ideas?

Thank you for your time and effort building this SDK :).

**Comment by morganchen12** [comment]
Are you re-using the nonce for both requests?

**Comment by Aymenworks** [comment]
The link request needs credentials.
To be able to get the Apple credentials, I show the Sign in with Apple sheet with the nonce X.

After the link requests fails, I do the Sign in requests with the same credentials, so the nonce X is reused since it's the same credentials, which I think is what trigger the request.

But based on https://github.com/firebase/firebase-ios-sdk/issues/4434#issuecomment-564776016, it seems that we are supposed to receive an updated credentials in the error.

**Comment by morganchen12** [comment]
You need to generate a new nonce for the second request.

**Comment by Aymenworks** [comment]
I will do that then if there is no other options!
Thank you for the confirmation!

**Comment by morganchen12** [comment]
No problem, let us know if this is still an issue and I'll reopen it.
