### ISSUE TITLE
FR: Dynamic framework option

### ISSUE THREAD

**Issue by pedro-nadolny** [firebase/firebase-ios-sdk#5534]
### Feature proposal

* Firebase Component: All

Would it be possible for us to have the option between Firebase as a static or dynamic framework? This would still make it possible to support iOS 7 but would make it easier to integrate with apps with target versions higher than that, especially if you have a modular architecture where you are using Firebase from different modules. I don't know the challenges of doing that, so I would be pleased do be clarified on that.

**Comment by paulb777** [comment]
@pedro-nadolny Thanks for the request.  

We're planning to remove the static framework restriction for the Firebase pods that are developed in this repo in the next major Firebase version. See #2022

**Comment by paulb777** [comment]
I'm going to close this issue for now in favor of #2022, but can continue the conversation in either place.
