### ISSUE TITLE
Crash reports are not submitted to the Firebase Website

### ISSUE THREAD

**Issue by stherold** [firebase/firebase-ios-sdk#5538]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4
  * Firebase SDK version: ...
  * Firebase Component: Crashlytics
  * Component version: 6.24.0
  * Installation method: `Carthage`

#### Steps to reproduce:

I use crashlytics in conjunction wth analytics. I let our app crash by implementing an alert and prepare the ok button with the crash. I stop Xcode debugger and restart the app from the phone. Then I let the app crash via the alert and restart the app so the report can be submitted. Sometimes the submission works and sometimes not. It feels very random. Non-Fatal errors do not make it at all to the website by executing `Crashlytics.crashlytics().record()`...

We use analytics opt-in, so we set the following in our info.plist:

![Screenshot 2020-05-06 at 21 01 29](https://user-images.githubusercontent.com/64915710/81217354-c3df7480-8fdc-11ea-829c-07d4b3d8e0e6.png)

Then on app start we log the output of the following - which are both `true`:
```
Crashlytics.crashlytics().isCrashlyticsCollectionEnabled()
FirebaseApp.app()?.isDataCollectionDefaultEnabled
```

I don't really find a solution to this. Do the properties we disable in the PLSIT somehow influence the crash reporting? If crash reporting is linked to data collection or analytics, we sadly cannot use it since analytics (`Firebase.Analytics.setAnalyticsCollectionEnabled()`) is currently disabled for our users. So would be crash reporting.

Any Ideas?

**Comment by paulb777** [comment]
If this is just in the last few days, it could be related to ttps://status.firebase.google.com/incident/Crashlytics/20003

**Comment by morganchen12** [comment]
The incident causing Crashlytics crash processing to stop temporarily has now been resolved. Can you check your crash dashboard to see if the crashes are showing up as expected?

**Comment by stherold** [comment]
Yep it was related to this issue by Facebook 👍
