### ISSUE TITLE
Crashlytics doesn't send crashes to console from real iOS device

### ISSUE THREAD

**Issue by subdan** [firebase/firebase-ios-sdk#5541]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4.1 (11E503a)
  * Firebase SDK version: 6.24.0
  * Firebase Component: Crashlytics
  * Component version: 6.24.0
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

Crashlytics doesn't send crashes to console from real iOS device.

I add this line of code `fatalError("Test")` to test crashes.
I run my app several times on a simulator and on a real iPhone device.
Crashes from simulator successfully appears in the console. But crashes from iPhone device does not.

In the console I see a lot of errors:
```
6.24.0 - [Firebase/Crashlytics][I-CLS000000] [Crashlytics:Crash:Reports] completed submission of /var/mobile/Containers/Data/Application/EE87C79A-979B-4146-A016-523492FA1274/Library/Caches/com.crashlytics.data/ru.rt.key.enterprise/v5/reports/prepared-legacy/1380DBF6-58F1-4B56-BD41-F8BBBA507543.multipartmime
6.24.0 - [Firebase/Crashlytics][I-CLS000000] [Crashlytics:Crash] report submission failed with error Error Domain=FIRCLSNetworkError Code=-4 "(null)" UserInfo={status_code=202, type=1, request_id=, content_type=}
6.24.0 - [Firebase/Crashlytics][I-CLS000000] [Crashlytics:Crash:Reports] completed submission of /var/mobile/Containers/Data/Application/EE87C79A-979B-4146-A016-523492FA1274/Library/Caches/com.crashlytics.data/ru.rt.key.enterprise/v5/reports/prepared-legacy/1380DBF6-58F1-4B56-BD41-F8BBBA507543.multipartmime
6.24.0 - [Firebase/Crashlytics][I-CLS000000] [Crashlytics:Crash] report submission failed with error Error Domain=FIRCLSNetworkError Code=-4 "(null)" UserInfo={status_code=202, type=1, request_id=, content_type=}
6.24.0 - [Firebase/Crashlytics][I-CLS000000] [Crashlytics:Crash:Reports] completed submission of /var/mobile/Containers/Data/Application/EE87C79A-979B-4146-A016-523492FA1274/Library/Caches/com.crashlytics.data/ru.rt.key.enterprise/v5/reports/prepared-legacy/2794474D-2B9B-4D28-B073-EFEFE2E5A6F7.multipartmime
6.24.0 - [Firebase/Crashlytics][I-CLS000000] [Crashlytics:Crash] report submission failed with error Error Domain=FIRCLSNetworkError Code=-4 "(null)" UserInfo={status_code=202, type=1, request_id=, content_type=}
```

Why Crashlytics unable to send crash log to Console?

**Comment by ryanwilson** [comment]
If this is something you're seeing right now and not previously - iOS crashes are suspended right now due to a server outage.

You can follow along at https://status.firebase.google.com/incident/Crashlytics/20003

**Comment by subdan** [comment]
Okay... I will be waiting for the resolution.

**Comment by paulb777** [comment]
I'm going to close here since nothing to do in the SDK. Feel free to continue the discussion.
