### ISSUE TITLE
GoogleUtilities GULAppDelegateSwizzler.m:826 crashes app

### ISSUE THREAD

**Issue by ghowen** [firebase/firebase-ios-sdk#5543]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4.1
  * Firebase SDK version: 6.24.0
  * Firebase Component: not sure as GoogleUtilities crashes that came in via a Firebase component
  * Component version: GoogleUtilities
  * Installation method: `CocoaPods` (select one)

### [REQUIRED] Step 2: Describe the problem

After I implemented Core Data Spotlight search in my Swift app, the app started to crash when the user searches Spotlight on device and selects any item of the app that was found.

The app launches briefly and then crashes in `GULAppDelegateSwizzler.m` in `line 826` with the message `Thread 1: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value`.

![Bildschirmfoto 2020-05-07 um 13 57 19](https://user-images.githubusercontent.com/390784/81297108-b7a1f880-906a-11ea-863d-2fd4acc5453f.png)

The crash happens only if the user selects a core data spotlight search result from the app and the app is NOT running in the background. So far I can reproduce the crash only in the iOS simulator (iPhone 11, iOS 13.4.1) when the app is NOT running in the background.

If the app is running in the background, it opens correctly, calls the link handler and processes the userActivity. If the app is NOT running in the background, it launches and then crashes in the line above.

One of the Firebase pods must have introduced the GoogleUtilities and AppSwizzler as a dependency that is now crashing the app. 

#### Steps to reproduce:

Tricky one. I seems to work on device but it could also be a race condition somewhere in the GoogleUtilities that just happens on simulator.

When I put a breakpoint in the respective line, I see nothing obvious. But once I step over, the app crashes:

![Bildschirmfoto 2020-05-07 um 13 53 48](https://user-images.githubusercontent.com/390784/81296843-6abe2200-906a-11ea-9a09-59f9758fc431.png)

**Comment by ryanwilson** [comment]
Sorry for the troubles and thanks for the report.

Does your AppDelegate have the `application:continueUserActivity:restorationHandler:` (`application(_:continue:restorationHandler:)
`) function?  It looks like the Swizzler is trying to call the original method which it thinks is there but potentially isn't.

**Comment by ghowen** [comment]
@ryanwilson Yes, ist does. This function is the entry point for the core data spotlight search events as well as for universal links.

**Comment by morganchen12** [comment]
It's interesting that the crash error is a Swift optional unwrap failure but the crashing line Xcode highlights is a bit of Objective-C. If you clean out your `application:continueUserActivity:restorationHandler:` method implementation and leave it as an empty method, does it still crash?

**Comment by ghowen** [comment]
@morganchen12 Nice one! There was a race condition in my code, and I even fixed it before filing this bug report. But the app kept on crashing after the fix, so I reported. 

What I found out just now was that if you set your run scheme for Xcode to wait for the executable to be launched and then attach the debugger, changes in code are actually not recompiled and put on device until you launch the app at least once "automatically" again. Until then Xcode ignores changes and waits for the stale executable to start up. Therefore the app kept crashing even though the bug was already fixed in code.

@ryanwilson I apologize for the false report! Thanks for looking and for listening!
