### ISSUE TITLE
[[GoogleDataTransport][I-GDTCOR001006]] There was an error saving the new counter value to disk.

### ISSUE THREAD

**Issue by annasnotfunny** [firebase/firebase-ios-sdk#5549]
* Xcode version: 11.4.1
  * Firebase SDK version: (6.24.0)
  * Firebase Component: Core, Firestore
  * Component version: Core (6.7.0), Firestore (1.13.0) (GoogleDataTransport (6.1.0))
  * Installation method: Cocoapods (1.9.1)

I'm new to IOS development and this is my first time using Firebase. I've been going through the process of setting the SDK up. I've followed all of the steps exactly, but I'm incapable of passing the "Run your app to verify installation" step. I feel that it might be connected to this error I get whenever I run my app:

```
[GoogleDataTransport][I-GDTCOR001006]
/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCOREvent.m:59) : There was an error saving the new counter value to disk.
```

The error doesn't crash my app, and it doesn't fail the build either. It just appears in the console whenever I run my app. I've tried uninstalling and reinstalling Cocoapods several times, I've also tried making an entirely new project and attaching it to Firebase, but this error persists. If it helps, this is the specific GDTCOREvent.m:59 section it refers to:

```
  __block NSNumber *result;
  dispatch_sync(eventIDQueue, ^{
    result = @(nextEventID);
    nextEventID++;
    NSError *error;
    [[result stringValue] writeToFile:counterPath
                           atomically:YES
                             encoding:NSUTF8StringEncoding
                                error:&error];
    GDTCORAssert(error == nil, @"There was an error saving the new counter value to disk.");
  });
```
How do I fix this error, and would it at all help the problem of communication between my app and the servers?

**Comment by mikehaney24** [comment]
Can you edit the line `    GDTCORAssert(error == nil, @"There was an error saving the new counter value to disk.");` to be `    GDTCORAssert(error == nil, @"There was an error saving the new counter value to disk: %@", error);` and then give me the error message? My fault for not printing out the error.

**Comment by annasnotfunny** [comment]
I edited the line and I got:
`
[GoogleDataTransport][I-GDTCOR001006]
(.../Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCOREvent.m:59) : There was an error saving the new counter value to disk: Error Domain=NSCocoaErrorDomain Code=4 "The folder “count” doesn’t exist." UserInfo={NSFilePath=/Users/.../Library/Developer/CoreSimulator/Devices/952AAB79-4301-4138-9553-2C21718DB828/data/Containers/Data/Application/1275C964-3F92-4D8B-8565-9808743ABEC3/Library/Caches/google-sdks-events/count, NSUserStringVariant=Folder, NSUnderlyingError=0x600000098750 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
`

**Comment by pwightman** [comment]
I'm also getting this error FWIW. No new information, same versions of everything. Re-running the app and the errors are gone, but this isn't working (from what I can tell), not sure if it's related. https://d.pr/i/aBwHq0

**Comment by mikehaney24** [comment]
I'm looking into it--it shouldn't have any effect on your app, but it's a problem that should be fixed.
