### ISSUE TITLE
Firebase Email Login Throws ERROR_INVALID_ACTION_CODE

### ISSUE THREAD

**Issue by ordinaryman09** [firebase/firebase-ios-sdk#5550]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.2.1
  * Firebase SDK version: 6.23.0
  * Firebase Component: Auth
  * Component version: 6.5.2
  * Installation method: CocoaPods

#### Steps to reproduce:

User request for passwordless login. They get the link, click the link, but couldn't proceed. We weren't able to reproduce it, and this does not happen to most users, but when it happens, they got stuck, try requesting another email, and get the same error. 
```
(
        {
        "error_code" = 17030;
        "error_domain" = FIRAuthErrorDomain;
        "user_info" =         {
            FIRAuthErrorUserInfoNameKey = "ERROR_INVALID_ACTION_CODE";
            NSLocalizedDescription = "The action code is invalid. This can happen if the code is malformed, expired, or has already been used.";
        };
    }
)
```

#### Relevant Code:

```
if ([[FIRAuth auth] isSignInWithEmailLink:link] && email && ![email isEmpty]) {
        [SVProgressHUD show];
        [[FIRAuth auth] signInWithEmail:email link:link completion:^(FIRAuthDataResult * _Nullable authResult, NSError * _Nullable error) {

            if(error) {
                [SVProgressHUD showErrorWithStatus:@"Authentication Failed"];
                return;
            }
        }];}
```

**Comment by scottcrossen** [comment]
Hi! We can't debug this without steps to reproduce or case-specific information that you shouldn't give out on a public forum. Please bring this through out support channels instead so they can assist with solving your particular case.

https://firebase.google.com/support
