### ISSUE TITLE
FirebaseFirestoreSwift: Issue Decoding Timestamps

### ISSUE THREAD

**Issue by P7S1** [firebase/firebase-ios-sdk#5555]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4 (11E146)
  * Firebase SDK version: 6.24.0
  * Firebase Component: FirebaseFirestoreSwift 
  * Component version: 0.2
  * Installation method: `CocoaPods`

### [REQUIRED] Step 2: Describe the problem
When I receive data from a callable HTTP cloud function and try to decode the data with the firestore decoder I get a strange error.

The decoder works perfectly fine everywhere else but for some reason, such as with queries. It's only causing problems with the cloud functions.
#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

`keyNotFound(TimestampKeys(stringValue: "seconds", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "userData", intValue: nil), _FirestoreKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "creationDate", intValue: nil)], debugDescription: "No value associated with key TimestampKeys(stringValue: \"seconds\", intValue: nil) (\"seconds\").", underlyingError: nil))`

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:
here is how I'm decoding data

`extension Decodable {
  /// Initialize from data. Return nil on failure
     init?(data value: [String:Any]){
        
        do {
            let newValue = try Firestore.Decoder().decode(Self.self, from: value)
            self = newValue
        } catch let err {
            print("decoding error : \(err)")
            return nil
        }
      
    }
  
}`

```
// TODO(you): code here to reproduce the problem
```

**Comment by wilhuff** [comment]
Unfortunately, Cloud Functions does not materialize Firestore timestamps in a way that's compatible with Firestore's decoder. This isn't something we can automatically fix either because the encoding of the timestamp is ambiguous: either it could be a timestamp represented as its parts or a someone intending to store seconds and nanoseconds separately outside of a Firestore timestamp :-(.

My advice for this situation is to run a pre-conversion step where you take known timestamp fields, convert them to `Timestamp`, and then run the decoder.

**Comment by P7S1** [comment]
I just have a question, theoretically, would setting all the Timestamp fields within my data model as optionals prevent this problem? I've tried that but I receive the same error.

**Comment by fobass** [comment]
Got same problem :-(
