### ISSUE TITLE
Remote config fetch callback not called on iOS 10

### ISSUE THREAD

**Issue by ahmadmabrouk** [firebase/firebase-ios-sdk#5558]
* Xcode version: 11.4.1
  * Firebase SDK version: 6.24.0
  * Firebase Component: Remote Config
  * Installation method: CocoaPods

I'm facing an issue in my project, everything used to work completely fine, but recently while the app is live, we suddenly started facing crashes and those crashes are only on iOS 10 devices! I debugged the code to try to figure out the problem, and I discovered that the Remote Config values are not being fetched at all on iOS 10! While everything is working totally fine on the newer iOS versions. I don't exactly know if the Remote Config case is what caused the crashes.

The fetch callback of "RemoteConfig.remoteConfig().fetch(withExpirationDuration:)" is not being called at all, and this is only on iOS 10 devices.

Below is a sample of my code....

    static var loadingDoneCallback: (() -> Void)?
    static var fetchComplete = false
    static private let config = RemoteConfig.remoteConfig()
    
    class func fetchCloudValues() {
        
        let fetchDuration: TimeInterval = 0
        config.configSettings = RemoteConfigSettings.init()
        config.fetch(withExpirationDuration: fetchDuration) { (_, error) in
            if let error = error {
                AnalyticsManager.logEventToFireBase(eventName: "ios_remote_config_fetching_error", parameters: ["error":error.localizedDescription])
                return
            }
            config.activate { (err) in
                if let err = err {
                    AnalyticsManager.logEventToFireBase(eventName: "ios_remote_config_activation_error", parameters: ["error":err.localizedDescription])
                }
                fetchComplete = true
                loadingDoneCallback?()
            }
        }
    }

Please help, Thanks a lot!

**Comment by paulb777** [comment]
This might be an incarnation of an Xcode 11.4.* armv7 optimizer bug. More details in #5233 

The workaround is building with any non-Xcode 11.4.* version.

**Comment by ahmadmabrouk** [comment]
Firstly, Thank you so much for your help.

I downloaded Xcode 11.3.1 and build it and everything worked completely fine!
As a developer, the last thing I would expect is to face a bug like that on Xcode. I'm so thankful that the problem is solved.
