### ISSUE TITLE
Unreleased Resource: Remote Config

### ISSUE THREAD

**Issue by divyaKalusulingam** [firebase/firebase-ios-sdk#5573]
The function updateMetadataTableWithOption:andValues:() in RCNConfigDBManager.m sometimes fails to release a database resource allocated by prepareSQL:() on line 598.The program can potentially fail to release a database resource.
 
Step 1: Describe your environment

  * Xcode version: 11.3
  * Firebase SDK version: 6.6.7
  * Firebase Component: Core, Messaging
  * Installation method: `CocoaPods 

### [REQUIRED] Step 2: Describe the problem

Resource leaks have at least two common causes:

- Error conditions and other exceptional circumstances.

- Confusion over which part of the program is responsible for releasing the resource.

Most unreleased resource issues result in general software reliability problems. However, if an attacker can intentionally trigger a resource leak, the attacker may be able to launch a denial of service attack by depleting the resource pool.

**Comment by ryanwilson** [comment]
@karenyz - it won't let me assign to you, but please take a look.

**Comment by paulb777** [comment]
As far as I can tell, all return paths after line 598 include a call to `sqlite3_finalize`. 

I'll close and can reopen with a demonstration that that's not the case.
