### ISSUE TITLE
Firebase UIWebView is still present 

### ISSUE THREAD

**Issue by veerChauhan** [firebase/firebase-ios-sdk#5574]
Appstore rejected application due to UIWebView present in Firebase/Auth. also i have removerd pod cache and updated with the latest pod.

**Comment by ryanwilson** [comment]
Hi @veerChauhan, can you please paste the contents of your `Podfile.lock` so we can see which version is being included? Also your `Podfile` to see if there are any version limitations included there.

There shouldn't be any more references to `UIWebView` in the source anymore:

```
$ git grep UIWebView
FirebaseDynamicLinks/CHANGELOG.md:- [fixed] Removed references to UIWebViewDelegate to comply with App Store Submission warning. (# 3722)
FirebaseDynamicLinks/CHANGELOG.md:- [fixed] Removed references to UIWebView to comply with App Store Submission warning. (# 3722)
```

**Comment by veerChauhan** [comment]
here is the content of podfile.lock

PODS:
  - Alamofire (4.8.2)
  - AppAuth (1.3.0):
    - AppAuth/Core (= 1.3.0)
    - AppAuth/ExternalUserAgent (= 1.3.0)
  - AppAuth/Core (1.3.0)
  - AppAuth/ExternalUserAgent (1.3.0)
  - CardIO (5.4.1)
  - Charts (3.3.0):
    - Charts/Core (= 3.3.0)
  - Charts/Core (3.3.0)
  - CircleProgressView (1.2.0)
  - CometChatPro (2.0.8-Xcode11.4)
  - DropDown (2.3.13)
  - Fabric (1.8.2)
  - FBSDKCoreKit (7.0.0):
    - FBSDKCoreKit/Basics (= 7.0.0)
    - FBSDKCoreKit/Core (= 7.0.0)
  - FBSDKCoreKit/Basics (7.0.0)
  - FBSDKCoreKit/Core (7.0.0):
    - FBSDKCoreKit/Basics
  - FBSDKLoginKit (7.0.0):
    - FBSDKLoginKit/Login (= 7.0.0)
  - FBSDKLoginKit/Login (7.0.0):
    - FBSDKCoreKit (~> 7.0.0)
  - Firebase/Analytics (6.24.0):
    - Firebase/Core
  - Firebase/Core (6.24.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.5.0)
  - Firebase/CoreOnly (6.24.0):
    - FirebaseCore (= 6.7.0)
  - Firebase/Messaging (6.24.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 4.4.0)
  - FirebaseAnalytics (6.5.0):
    - FirebaseCore (~> 6.7)
    - FirebaseInstallations (~> 1.2)
    - GoogleAppMeasurement (= 6.5.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 1.30905.0)
  - FirebaseAnalyticsInterop (1.5.0)
  - FirebaseCore (6.7.0):
    - FirebaseCoreDiagnostics (~> 1.3)
    - FirebaseCoreDiagnosticsInterop (~> 1.2)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
  - FirebaseCoreDiagnostics (1.3.0):
    - FirebaseCoreDiagnosticsInterop (~> 1.2)
    - GoogleDataTransportCCTSupport (~> 3.1)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
    - nanopb (~> 1.30905.0)
  - FirebaseCoreDiagnosticsInterop (1.2.0)
  - FirebaseInstallations (1.2.0):
    - FirebaseCore (~> 6.6)
    - GoogleUtilities/Environment (~> 6.6)
    - GoogleUtilities/UserDefaults (~> 6.6)
    - PromisesObjC (~> 1.2)
  - FirebaseInstanceID (4.3.4):
    - FirebaseCore (~> 6.6)
    - FirebaseInstallations (~> 1.0)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/UserDefaults (~> 6.5)
  - FirebaseMessaging (4.4.0):
    - FirebaseAnalyticsInterop (~> 1.5)
    - FirebaseCore (~> 6.6)
    - FirebaseInstanceID (~> 4.3)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.5)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Reachability (~> 6.5)
    - GoogleUtilities/UserDefaults (~> 6.5)
    - Protobuf (>= 3.9.2, ~> 3.9)
  - GoogleAppMeasurement (6.5.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 1.30905.0)
  - GoogleDataTransport (6.1.0)
  - GoogleDataTransportCCTSupport (3.1.0):
    - GoogleDataTransport (~> 6.1)
    - nanopb (~> 1.30905.0)
  - GoogleSignIn (5.0.2):
    - AppAuth (~> 1.2)
    - GTMAppAuth (~> 1.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - GoogleUtilities/AppDelegateSwizzler (6.6.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (6.6.0):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/Logger (6.6.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (6.6.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (6.6.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (6.6.0)"
  - GoogleUtilities/Reachability (6.6.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (6.6.0):
    - GoogleUtilities/Logger
  - GTMAppAuth (1.0.0):
    - AppAuth/Core (~> 1.0)
    - GTMSessionFetcher (~> 1.1)
  - GTMSessionFetcher (1.4.0):
    - GTMSessionFetcher/Full (= 1.4.0)
  - GTMSessionFetcher/Core (1.4.0)
  - GTMSessionFetcher/Full (1.4.0):
    - GTMSessionFetcher/Core (= 1.4.0)
  - IQKeyboardManagerSwift (6.4.2)
  - JDropDownAlert (1.3.0)
  - Kingfisher (5.13.4):
    - Kingfisher/Core (= 5.13.4)
  - Kingfisher/Core (5.13.4)
  - MaterialComponents/AnimationTiming (109.2.0)
  - MaterialComponents/Availability (109.2.0)
  - MaterialComponents/Buttons (109.2.0):
    - MaterialComponents/Elevation
    - MaterialComponents/Ink
    - MaterialComponents/private/Math
    - MaterialComponents/Ripple
    - MaterialComponents/ShadowElevations
    - MaterialComponents/ShadowLayer
    - MaterialComponents/Shapes
    - MaterialComponents/Typography
    - MDFInternationalization
    - MDFTextAccessibility
  - MaterialComponents/Elevation (109.2.0):
    - MaterialComponents/Availability
    - MaterialComponents/private/Color
    - MaterialComponents/private/Math
  - MaterialComponents/Ink (109.2.0):
    - MaterialComponents/Availability
    - MaterialComponents/private/Color
    - MaterialComponents/private/Math
  - MaterialComponents/Palettes (109.2.0)
  - MaterialComponents/private/Application (109.2.0)
  - MaterialComponents/private/Color (109.2.0):
    - MaterialComponents/Availability
  - MaterialComponents/private/Math (109.2.0)
  - MaterialComponents/Ripple (109.2.0):
    - MaterialComponents/AnimationTiming
    - MaterialComponents/Availability
    - MaterialComponents/private/Color
    - MaterialComponents/private/Math
  - MaterialComponents/ShadowElevations (109.2.0)
  - MaterialComponents/ShadowLayer (109.2.0):
    - MaterialComponents/ShadowElevations
  - MaterialComponents/Shapes (109.2.0):
    - MaterialComponents/private/Color
    - MaterialComponents/private/Math
    - MaterialComponents/ShadowLayer
  - MaterialComponents/TextFields (109.2.0):
    - MaterialComponents/AnimationTiming
    - MaterialComponents/Buttons
    - MaterialComponents/Elevation
    - MaterialComponents/Palettes
    - MaterialComponents/private/Math
    - MaterialComponents/Typography
    - MDFInternationalization
  - MaterialComponents/Typography (109.2.0):
    - MaterialComponents/private/Application
    - MaterialComponents/private/Math
  - MDFInternationalization (2.0.0)
  - MDFTextAccessibility (2.0.0)
  - nanopb (1.30905.0):
    - nanopb/decode (= 1.30905.0)
    - nanopb/encode (= 1.30905.0)
  - nanopb/decode (1.30905.0)
  - nanopb/encode (1.30905.0)
  - ObjectMapper (3.5.2)
  - PayPal-iOS-SDK (2.18.1):
    - PayPal-iOS-SDK/CardIO (= 2.18.1)
    - PayPal-iOS-SDK/Core (= 2.18.1)
  - PayPal-iOS-SDK/CardIO (2.18.1):
    - CardIO (~> 5.4.1)
  - PayPal-iOS-SDK/Core (2.18.1)
  - PromisesObjC (1.2.8)
  - Protobuf (3.11.4)
  - Stripe (19.0.1)
  - SwiftLint (0.34.0)
  - SwiftMessages (7.0.1):
    - SwiftMessages/App (= 7.0.1)
  - SwiftMessages/App (7.0.1)
  - SwiftyJSON (5.0.0)

DEPENDENCIES:
  - Alamofire (~> 4.8.2)
  - Charts (~> 3.3.0)
  - CircleProgressView (~> 1.2.0)
  - CometChatPro (= 2.0.8-Xcode11.4)
  - DropDown (~> 2.3.13)
  - Fabric (~> 1.8.2)
  - FBSDKCoreKit
  - FBSDKLoginKit
  - Firebase/Analytics
  - Firebase/Core
  - Firebase/Messaging
  - GoogleSignIn
  - IQKeyboardManagerSwift (~> 6.4.2)
  - JDropDownAlert (~> 1.3.0)
  - Kingfisher (~> 5.13.3)
  - MaterialComponents/TextFields
  - ObjectMapper (~> 3.5.2)
  - PayPal-iOS-SDK
  - Stripe (~> 19.0.1)
  - SwiftLint (~> 0.34.0)
  - SwiftMessages (~> 7.0.1)
  - SwiftyJSON (~> 5.0.0)

SPEC REPOS:
  trunk:
    - Alamofire
    - AppAuth
    - CardIO
    - Charts
    - CircleProgressView
    - CometChatPro
    - DropDown
    - Fabric
    - FBSDKCoreKit
    - FBSDKLoginKit
    - Firebase
    - FirebaseAnalytics
    - FirebaseAnalyticsInterop
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseCoreDiagnosticsInterop
    - FirebaseInstallations
    - FirebaseInstanceID
    - FirebaseMessaging
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleDataTransportCCTSupport
    - GoogleSignIn
    - GoogleUtilities
    - GTMAppAuth
    - GTMSessionFetcher
    - IQKeyboardManagerSwift
    - JDropDownAlert
    - Kingfisher
    - MaterialComponents
    - MDFInternationalization
    - MDFTextAccessibility
    - nanopb
    - ObjectMapper
    - PayPal-iOS-SDK
    - PromisesObjC
    - Protobuf
    - Stripe
    - SwiftLint
    - SwiftMessages
    - SwiftyJSON

SPEC CHECKSUMS:
  Alamofire: ae5c501addb7afdbb13687d7f2f722c78734c2d3
  AppAuth: 73574f3013a1e65b9601a3ddc8b3158cce68c09d
  CardIO: 56983b39b62f495fc6dae9ad7cf875143df06443
  Charts: e0dd4cd8f257bccf98407b58183ddca8e8d5b578
  CircleProgressView: 6b5b091d59dc5e5d2fda84e637a40498cdc39937
  CometChatPro: aafdd9f36cb5e1fc620c5b6e4d96e61320ce91ed
  DropDown: 8a2116376c1981888557f72ec2ffc9a5e0e456ec
  Fabric: d2b22f443ba195d8a7cc204da230977c72733b40
  FBSDKCoreKit: 8ad31cd09f793d1d7e84cf20fd6cebfe80ad318d
  FBSDKLoginKit: 5d1e321dc45ab1fa09198b77fc17c32a06f008c0
  Firebase: b28e55c60efd98963cd9011fe2fac5a10c2ba124
  FirebaseAnalytics: 7386fc2176e3f93ad8ef34b5b1f2b33a891e4962
  FirebaseAnalyticsInterop: 3f86269c38ae41f47afeb43ebf32a001f58fcdae
  FirebaseCore: e610482f64097b0e9f056cd97bc6b33dfabcbb6a
  FirebaseCoreDiagnostics: 4a773a47bd83bbd5a9b1ccf1ce7caa8b2d535e67
  FirebaseCoreDiagnosticsInterop: 296e2c5f5314500a850ad0b83e9e7c10b011a850
  FirebaseInstallations: 2119fb3e46b0a88bfdbf12562f855ee3252462fa
  FirebaseInstanceID: cef67c4967c7cecb56ea65d8acbb4834825c587b
  FirebaseMessaging: 58cb17277641a0084d98d4951ba1f1fb0588c8c6
  GoogleAppMeasurement: 4c644d86835d827bab30ab6aabb9ecaf1f500735
  GoogleDataTransport: f6f8eba931df03ebd2232ff4645aa85f8f47b5ab
  GoogleDataTransportCCTSupport: d70a561f7d236af529fee598835caad5e25f6d3d
  GoogleSignIn: 7137d297ddc022a7e0aa4619c86d72c909fa7213
  GoogleUtilities: 39530bc0ad980530298e9c4af8549e991fd033b1
  GTMAppAuth: 4deac854479704f348309e7b66189e604cf5e01e
  GTMSessionFetcher: 6f5c8abbab8a9bce4bb3f057e317728ec6182b10
  IQKeyboardManagerSwift: 79a3ec200dfb41cb66a89b8575417b5378107c5d
  JDropDownAlert: fd2aec99b685cb35530283b34f36c7cb46d44170
  Kingfisher: d2279a7abece3c7f25a80cd2b7f363ca5cf3f44c
  MaterialComponents: 59bfbfe08fc1ac204b21ba69100beabb932e3699
  MDFInternationalization: 010097556d6b09d2c4ea38e0820ea6d37be6a314
  MDFTextAccessibility: 85c09a1bd9c321f494348e632a25063bcda35a53
  nanopb: c43f40fadfe79e8b8db116583945847910cbabc9
  ObjectMapper: b53ae947d370bf89423e86be7d4e2d2b2a8d3f40
  PayPal-iOS-SDK: 70d56697aef502c130b9840e31dea5c6b8a350e1
  PromisesObjC: c119f3cd559f50b7ae681fa59dc1acd19173b7e6
  Protobuf: 176220c526ad8bd09ab1fb40a978eac3fef665f7
  Stripe: 03313f9520a0786e2c00d9a7a2672c11e08821af
  SwiftLint: 79d48a17c6565dc286c37efb8322c7b450f95c67
  SwiftMessages: b577dc7043be8b299857ab35bb663dbff6483bd0
  SwiftyJSON: 36413e04c44ee145039d332b4f4e2d3e8d6c4db7

PODFILE CHECKSUM: fa8c649c0d59e13f26be6f1b63a2fa02de723af2

COCOAPODS: 1.8.4

**Comment by veerChauhan** [comment]
also content of podfile is below ::


# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# ignore all warnings from all dependencies
#inhibit_all_warnings!
target 'BlocEdu' do

  platform :ios, '11.3'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
  # Pods for BlocEdu
  pod 'Alamofire' , '~> 4.8.2'
  pod 'SwiftyJSON' , '~> 5.0.0'
  pod 'MaterialComponents/TextFields'
  pod 'IQKeyboardManagerSwift' , '~> 6.4.2'
  pod 'Fabric', '~> 1.8.2'
  pod 'SwiftLint', '~> 0.34.0'
  pod 'JDropDownAlert', '~> 1.3.0'
  pod 'SwiftMessages', '~> 7.0.1'
  pod 'DropDown', '~> 2.3.13'
  pod 'Kingfisher', '~> 5.13.3'
  pod 'ObjectMapper', '~> 3.5.2'
  pod 'Firebase/Messaging' 
  pod 'CircleProgressView', '~> 1.2.0'
  pod 'Charts', '~> 3.3.0'
  pod 'Stripe', '~> 19.0.1'
  pod 'PayPal-iOS-SDK'
  pod 'CometChatPro', '2.0.8-Xcode11.4'
  pod 'Firebase/Core'

  # Social login - Google
  pod 'GoogleSignIn' 

  # Social login - Facebook
  pod 'FBSDKCoreKit' #6.3.0
  pod 'FBSDKLoginKit' #6.3.0
  
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics' #6.4.0
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  
  target 'BlocEduTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BlocEduUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

**Comment by veerChauhan** [comment]
git grep UIWebView
Pods/AppAuth/README.md:for the auth request. `UIWebView` and `WKWebView` are explicitly *not*
Pods/AppAuth/Source/AppAuth.h:    for the auth request. `UIWebView` and `WKWebView` are explicitly *not*
Binary file Pods/Fabric/upload-symbols matches
Pods/GoogleSignIn/CHANGELOG.md:- Supports sign-in via UIWebView rather than app switching to a browser,

**Comment by ryanwilson** [comment]
This looks like a problem with AppAuth, not FirebaseAuth - https://github.com/openid/AppAuth-iOS/issues/529

It looks like a new release [1.3.1](https://github.com/openid/AppAuth-iOS/releases/tag/1.3.1) is available that removes the `UIWebView` from the comment in the header. I recommend updating there and if you have further issues, please comment on the AppAuth repository.
