### ISSUE TITLE
[ML Text Recognition] Different result on different iOS device

### ISSUE THREAD

**Issue by artemsivcev** [firebase/firebase-ios-sdk#5575]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4.1
  * Firebase SDK version: idk
  * Firebase Component: FirebaseMLVision, FirebaseMLVisionTextModel
  * Component version: 0.19.0
  * Installation method: `CocoaPods` (and cinterop, kotlin multiplatform)

#### Steps to reproduce:

Hey there! I have 2 same images and 2 iPhones: 8 and X. UIImage have scale set to 1 and cropped width and height by app. Then I send this image in onDeviceTextRecognizer() and get 2 different maps with all different results. Why so? Is there some scale dependence in ML KIT library?
Images is not too small. height = 2048, width = 1383.
I have same result without cropping image.

**Comment by artemsivcev** [comment]
For tests, I compressed the image to 1280px, but still have different result, for different iPhones...

**Comment by artemsivcev** [comment]
Now I took [image](https://firebase.google.com/docs/ml-kit/images/examples/Wege_der_parlamentarischen_Demokratie.jpg) from example and there is still different result for iPhone 8 and X. 
| Prop  | iPhone 8 | iPhone X |
| ------------- | ------------- | ------------- |
| Height | 1536.0  | 1536.0  |
| Width  | 1024.0  | 1024.0  |
| Scale  | 1.0  | 1.0  |
| Wege der  | [(410, 666) - (631, 643)][(414, 710) - (636, 688)]  | [(410, 667) - (631, 644)][(414, 713) - (636, 691)]  |
| parlamentarischen  | [(287, 738) - (743, 686)][(292, 785) - (748, 733)]  | [(287, 738) - (742, 685)][(292, 785) - (747, 733)]   |
| Demokratie  | [(372, 786) - (651, 754)][(376, 825) - (655, 794)]  | [(372, 785) - (650, 754)][(376, 825) - (654, 794)] |

As you can see there is some mismatch for text coordinates for same image on different devices. But why and how to avoid this?

**Comment by artemsivcev** [comment]
Sorry missclick...

**Comment by paulb777** [comment]
@artemsivcev Thanks for the report. We're tracking internally at b/156483920

**Comment by artemsivcev** [comment]
@paulb777 is there any chance for hotfix to this issue?

**Comment by artemsivcev** [comment]
Now I tested version 0.12.0 and 0.18.0 for this bug and there it is, but with different coordinates. 
In ver.12 there is more accuracy between devices:
| Prop  | iPhone 8 | iPhone X |
| ------------- | ------------- | ------------- |
| Height | 1536.0  | 1536.0  |
| Width  | 1024.0  | 1024.0  |
| sclae  | 1.0  | 1.0  |
| Wege der  | [(412, 665) - (633, 645)][(416, 713) - (637, 694)]   |[(410, 665) - (633, 645)][(414, 713) - (637, 694)]  |
| parlamentarischen  | [(287, 739) - (743, 688)][(292, 784) - (748, 734)]  | [(287, 739) - (743, 688)][(292, 784) - (748, 734)]   |
| Demokratie  | [(372, 785) - (650, 754)][(376, 824) - (654, 794)] | [(372, 785) - (651, 754)][(376, 824) - (655, 794)]  |


And in ver.18 same result as ver.19

**Comment by artemsivcev** [comment]
@paulb777 Hi! Any progress?

**Comment by paulb777** [comment]
@artemsivcev Sorry, not yet. I repinged the MLKit team.

**Comment by artemsivcev** [comment]
@paulb777 sorry for trying, but... Still nothing? We are used this solution on production and this is really major issue...

**Comment by artemsivcev** [comment]
@paulb777 Hi! Any progress?) I can help if you need it.

**Comment by artemsivcev** [comment]
@morganchen12 ok, I can ping you instead)) I'm really want to resolve this issue and help!

**Comment by morganchen12** [comment]
Hey, sorry for the delay @artemsivcev. I'll take a look at this today. Are you receiving different results on different devices if you use the exact same image (not just two separate images downscaled to the same size)?

**Comment by artemsivcev** [comment]
@morganchen12 yes, I sent on 2 iPhones 1 image via AirDrop. Then I open it with UIImage and compare all meta info and it was exactly the same. Where can I check downscaled info?

**Comment by morganchen12** [comment]
Your approach should be sufficient. I'll investigate.

**Comment by morganchen12** [comment]
I haven't been able to identify a root cause yet. I'll try reproducing this issue in the quickstart and continue from there.

**Comment by artemsivcev** [comment]
Ok, if you need any info or help let me know

**Comment by artemsivcev** [comment]
Some update, on all simulators same result for coordinates, problem only on real devices

**Comment by morganchen12** [comment]
Thanks @artemsivcev, I was also unable to reproduce the issue on simulator. Due to the work from home situation, I'm not immediately able to acquire another iOS device to test this on, so I'm going to have to ask for your help for on-device testing.

ML Kit's text recognition uses GoogleMobileVision under the hood. Can you try running text detection directly through GMV via the instructions in [this doc](https://developers.google.com/vision/ios/text-overview) and letting us know if the results differ per-device?

**Comment by artemsivcev** [comment]
@morganchen12 yeah of course, I'll try it right now

**Comment by artemsivcev** [comment]
I'm not really iOS developer, did you have swift example to use GoogleMobileVision? Or example project?

**Comment by artemsivcev** [comment]
Running it, looking for iPhoneX...

**Comment by artemsivcev** [comment]
Same test image, same test devices. 
Prop | iPhone 8 | iPhone X
-- | -- | --
Height | 1536.0 | 1536.0
Width | 1024.0 | 1024.0
scale | 1.0 | 1.0
Wege der | [410.0, 644.0, 229.0, 68.0] | [410.0, 645.0, 229.0, 67.0]
parlamentarischen\nDemokratie | [287.0, 688.0, 467.0, 147.0] | [288.0, 688.0, 465.0, 146.0]

**Comment by morganchen12** [comment]
Thanks, I'll pass this info on to the GMV team. In the meantime, what version of GMV are you using? Does the behavior change if you switch to an older version?

**Comment by artemsivcev** [comment]
@morganchen12 I get GMV from CocoaPods, think that was last one. Without issue in GMV repo(there is one?) it's dead end... Whom I suppose to ping? =D Need a solution for this...

**Comment by morganchen12** [comment]
You can manually pin an older version of a CocoaPod by explicitly listing it in your Podfile with the `=` operator. Don't worry about pinging the GMV team, I've done that for you (their issue tracker is Google-internal).

```ruby
pod 'GoogleMobileVision', `= 1.5.0`
```

**Comment by artemsivcev** [comment]
Only 1.5.0 need to check? And how to see all a available version on pods?

**Comment by morganchen12** [comment]
You should hopefully only need to check 1.5.0. You can check which versions of a pod are available by looking at the podspecs on GitHub: https://github.com/CocoaPods/Specs/tree/master/Specs/0/4/2/GoogleMobileVision

**Comment by artemsivcev** [comment]
@morganchen12 
GMV 1.5.0 test. There is only one line for iPhoneX... Still different result, but something new!

Prop	|iPhone 8	|iPhone X
-- | -- | --
Height	|1536.0	|1536.0
Width	|1024.0	|1024.0
scale	|1.0	|1.0
Wege der	|[414.0, 643.0, 233.0, 69.0]|	[-]
parlamentarischen\nDemokratie	|[290.0, 687.0, 468.0, 155.0]|	[-]
Wege der parlamentarischen Demokratie	|[-]	|[284.0, 635.0, 471.0, 205.0]

**Comment by morganchen12** [comment]
Thanks, looks like this behavior has been broken for some time now. I'll keep this updated with the GMV team's response, which may take a week or two. In the meantime let's try to find a workaround for your use case.

What are you using text recognition for and why is it important that text recognition is consistent across different devices?

**Comment by artemsivcev** [comment]
I'm using it for detect table data. Some photo contains problems with degree angle for text. I try to use angle of bottom line of each block to detect average angle and create a straight line between blocks. And I create the best solution and it works, but only on iPhone 8. Now I found some workaround and used only longest blocks for detect angle. It's pretty close, but still have some issues...

**Comment by artemsivcev** [comment]
@morganchen12 hey there! Any progress?

**Comment by morganchen12** [comment]
I have not been able to pin down why GMV returns different results on different devices. I'll let you know if I'm able to find a root cause.

**Comment by artemsivcev** [comment]
@morganchen12 Hello! Still nothing? GMV team keep silent?

**Comment by morganchen12** [comment]
Nothing yet. I've pinged the internal bug for you.

**Comment by artemsivcev** [comment]
That would be nice) And what they say?

**Comment by morganchen12** [comment]
They have yet to respond.

**Comment by morganchen12** [comment]
The Firebase ML Kit text recognition API has been deprecated since all on-device ML Kit features are no longer a part of Firebase. You should move to using the Google standalone ML Kit instead by following the migration guide [here](https://developers.google.com/ml-kit/migration).

Sorry for the bad news.
