### ISSUE TITLE
Can't collect any data to Firebase neither nor  BigQuery.

### ISSUE THREAD

**Issue by lynulzy** [firebase/firebase-ios-sdk#5576]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4.0
  * Firebase SDK version: 6.22.0
  * Firebase Component: Performance, Analytics,Crashlytics
  * Component version:6.22.0
  * Installation method: `CocoaPods

#### Steps to reproduce:

We used to upload dsym file to Fabric but In our latest version the Fabric was stopped, So we refered to the doc [there](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=ios&authuser=1). After that we found there is no result in Quality/Crashlytics neither nor in Big Query. 

#### Relevant Code:

```
 pod 'Fabric'
  pod 'Crashlytics', '~> 3.14' 
  pod 'Firebase/Analytics', '6.22.0'
  pod 'Firebase/Performance', '6.22.0'
```

**Comment by morganchen12** [comment]
Hey @lynulzy, please file this issue at [Firebase Support](http://firebase.google.com/support) instead. They'll be able to look at your project and see why no reports are showing up.
