### ISSUE TITLE
Log Forging

### ISSUE THREAD

**Issue by divyaKalusulingam** [firebase/firebase-ios-sdk#5587]
**Summary**
The function beginFetchMayDelay:mayAuthorize:() in GTMSessionFetcher.m writes unvalidated user input to the log on line 856. An attacker could take advantage of this behavior to forge log entries or inject malicious content into the log.The identified function writes unvalidated user input to the log. An attacker could take advantage of this behavior to forge log entries or inject malicious content into the log.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.6.7
  * Firebase Component: Core,Messaging
  * Installation method: `CocoaPods 

### [REQUIRED] Step 2: Describe the problem
Explanation
Log forging vulnerabilities occur when:

1. Data enters an application from an untrusted source.

In this case, the data enters at initWithSuiteName:() in RCNUserDefaultsManager.m at line 86.

2. The data is written to an application or system log file.

In this case, the data is logged by NSLog() in GTMSessionFetcher.m at line 856.

Applications typically use log files to store a history of events or transactions for later review, statistics gathering, or debugging. Depending upon the nature of the application, log files can be reviewed manually as required, or culled automatically by tools that search the logs for important data points or trends.

Examination of the log files can be hindered or conclusions based on log data can be wrong if an attacker is allowed to supply data to the application that is subsequently logged verbatim. An attacker might insert false entries into the log file by including log entry separator characters in their data. If the log file is processed automatically, the attacker may be able to render the file unusable by corrupting the format of the file or injecting unexpected characters. A more subtle attack might involve skewing the log file statistics. Forged or otherwise, corrupted log files can be used to cover an attacker's tracks or even to implicate another party in the commission of a malicious act [1]. In the worst case, an attacker injects code or other commands into the log file and takes advantage of a vulnerability in the log processing utility [2].

**Comment by morganchen12** [comment]
This is essentially a duplicate of #5577.
