### ISSUE TITLE
Type Mismatch: Negative to Unsigned 

### ISSUE THREAD

**Issue by divyaKalusulingam** [firebase/firebase-ios-sdk#5589]
**Summary**
The function in FIRMessagingSecureSocket.m is declared to return an unsigned value, but on line 31 it returns a negative value.The function is declared to return an unsigned value, but in some cases it returns a negative value.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.6.7
  * Firebase Component: Core, Messaging
  * Installation method: `CocoaPods 

#### Steps to reproduce:
**Explanation**
It is dangerous to rely on implicit casts between signed and unsigned numbers because the result can take on an unexpected value and violate weak assumptions made elsewhere in the program.

**Comment by chliangGoogle** [comment]
Thanks for your feedback.
"The function in FIRMessagingSecureSocket.m is declared to return an unsigned value" can you specify which funciton?
[Line 31](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseMessaging/Sources/FIRMessagingSecureSocket.m#L31) is a parameter that we assigned negative. So I am not sure which function you mena.
