### ISSUE TITLE
Type Mismatch: Signed to Unsigned 

### ISSUE THREAD

**Issue by divyaKalusulingam** [firebase/firebase-ios-sdk#5590]
Summary
The function GDTCCTNetworkConnectionInfoNetworkMobileSubtype() in GDTCCTNanopbHelpers.m is declared to return an unsigned value, but on line 253 it returns a signed value.The function is declared to return an unsigned number but returns a signed value.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.6.7
  * Firebase Component:  Core,  Messaging
  * Installation method: `CocoaPods 

### [REQUIRED] Step 2: Describe the problem
**Explanation**
It is dangerous to rely on implicit casts between signed and unsigned numbers because the result can take on an unexpected value and violate weak assumptions made elsewhere in the program.

**Comment by mikehaney24** [comment]
Hello, thanks for the report. Can you explain how you found and/or see this problem?

gdt_cct_NetworkConnectionInfo_MobileSubtype is an enum type, which is a signed int in C.

From https://en.wikipedia.org/wiki/Enumerated_type#C 

> C exposes the integer representation of enumeration values directly to the programmer. Integers and enum values can be mixed freely, and all arithmetic operations on enum values are permitted. It is even possible for an enum variable to hold an integer that does not represent any of the enumeration values. In fact, according to the language definition, the above code will define Clubs, Diamonds, Hearts, and Spades as constants of type int, which will only be converted (silently) to enum cardsuit if they are stored in a variable of that type.
