### ISSUE TITLE
openssl_grpc/x509.h file not found during archive of Catalyst App

### ISSUE THREAD

**Issue by JuLink** [firebase/firebase-ios-sdk#5591]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4.1 (11E503a)
  * Firebase SDK version: 6.24.0
  * Firebase Component: Auth, Firestore, Crashlytics and Function
  * Component version: 6.24.0
  * Installation method: `CocoaPods`

### [REQUIRED] Step 2: Describe the problem

After creating my iOS app, I've tried to make it a Catalyst App. To do that I had to sign the gRPC Resource target as explained in the GitHub page. Works great for development and deploy in debug mode. But when Archiving my app to publish it the project doesn't compile. During the compilation of the Pod target I get this error: 
<img width="293" alt="Screenshot 2020-05-13 at 09 55 18" src="https://user-images.githubusercontent.com/1457215/81786424-e94e1000-94ff-11ea-94ea-ef27e541e98a.png">

I know that there was previous issue with archiving and grpc but it doesn't appear to be the same error, at least it's not the same error message.

#### Steps to reproduce:

Create a Catalyst app, add Auth, Firestore, Crashlytics and Function with Cocoapods. Sign the gRPC Resource Target to make it build in Debug mode. Try to archive the application.

**Comment by thebrianchen** [comment]
@JuLink I tried reproducing the issue locally but I was unable to do so. Could you provide a repo that reproduces this issue?

There's currently an open [issue](https://github.com/grpc/grpc/issues/20500) with grpc-core archiving that hasn't been fixed yet. I'm not sure if yours is the same issue, but perhaps the [workaround](https://github.com/grpc/grpc/issues/20500#issuecomment-6048899190) mentioned can help you.

**Comment by JuLink** [comment]
Sure here is the repo : https://github.com/JuLink/FirebaseIssueCatalyst

I'm aware of the grpc-core but since the message was not quite the same I figured it was something else 😅 

With the workaround I can make it work with this project but unfortunately with my real project it archive properly but when launching the exported app it crashes immediately. I will try to understand in more detail what's happening.

**Comment by thebrianchen** [comment]
@JuLink Based on the workaround, it seems like the error in the repo is the same as the one I linked above in grpc-core. I hope you're able to troubleshoot your project! Marking this issue as closed, but feel free to reopen if you run into other related issues.
