### ISSUE TITLE
Unreleased Resource: Database 

### ISSUE THREAD

**Issue by divyaKalusulingam** [firebase/firebase-ios-sdk#5592]
**Summary**
The function updateMetadataTableWithOption:andValues:() in RCNConfigDBManager.m sometimes fails to release a database resource allocated by prepareSQL:() on line 598.The program can potentially fail to release a database resource.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.6.7
  * Firebase Component: Core, Database, Firestore, Messaging
  * Component version: FirebaseREmoteConfig - 4.4.9
  * Installation method: `CocoaPods 

### [REQUIRED] Step 2: Describe the problem

**Explanation**
Resource leaks have at least two common causes:

- Error conditions and other exceptional circumstances.

- Confusion over which part of the program is responsible for releasing the resource.

Most unreleased resource issues result in general software reliability problems. However, if an attacker can intentionally trigger a resource leak, the attacker may be able to launch a denial of service attack by depleting the resource pool.

**Comment by paulb777** [comment]
Closing as duplicate of #5573
