### ISSUE TITLE
Insecure Storage: HTTP Response Cache Leak

### ISSUE THREAD

**Issue by divyaKalusulingam** [firebase/firebase-ios-sdk#5594]
**Summary**
On line 75 of FIRInstallationsAPIService.m, the method initWithAPIKey:projectID:() performs a URL request without configuring the URL loading system to prevent the caching of HTTP(S) responses.The identified method performs a URL request without configuring the URL loading system to prevent the caching of HTTP(S) responses.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.6.7
  * Firebase Component: Auth, Core, Database, Firestore, Messaging
  * Installation method: `CocoaPods 

### [REQUIRED] Step 2: Describe the problem
**Explanation**
The HTTP(S) responses may contain sensitive data such as session cookies and API tokens. The URL loading system will cache all the HTTP(S) responses for performance reasons, storing them unencrypted in the {app ID}/Library/Caches/com.mycompany.myapp/Cache.db* files.

**Comment by morganchen12** [comment]
This issue is a little inaccurate, as the `initWithAPIKey:projectID:` method doesn't actually immediately perform a URL request.

The cached URL data does not contain any sensitive information, though it is infrequently run and likely does not need to be cached.
