### ISSUE TITLE
Password Management: Hardcoded Password  

### ISSUE THREAD

**Issue by divyaKalusulingam** [firebase/firebase-ios-sdk#5596]
**Summary**
Hardcoded passwords may compromise system security in a way that cannot be easily remedied.Hardcoded passwords may compromise system security in a way that cannot be easily remedied.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.6.7
  * Firebase Component: Auth, Core, Database, Firestore, Messaging
  * Component version: _____
  * Installation method: `CocoaPods | Carthage | Zip file` (select one)

### [REQUIRED] Step 2: Describe the problem
**Explanation**
It is never a good idea to hardcode a password. Not only does hardcoding a password allow all of the project's developers to view the password, it also makes fixing the problem extremely difficult. After the code is in production, the password cannot be changed without patching the software. If the account protected by the password is compromised, the owners of the system must choose between security and availability.

In this case, the password was used to access a resource at in FIRAuthProtoStartMFAPhoneRequestInfo.m at line 39.

**Comment by paulb777** [comment]
@divyaKalusulingam From my review of the code `kreCAPTCHATokenKey` is a dictionary key. I'll close for now, but can reopen with more detail.
