### ISSUE TITLE
Can not login with Microsoft

### ISSUE THREAD

**Issue by nirav98** [firebase/firebase-ios-sdk#5598]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3
 
Getting error when trying to login with  Microsoft. 

Error Domain=FIRAuthErrorDomain Code=17004 "Error getting access token from microsoft.com, OAuth2 redirect uri is: https://.firebaseapp.com/__/auth/handler, response: OAuth2TokenResponse{params: error=invalid_request&error_description=AADSTS90023:%20Public%20clients%20can't%20send%20a%20client%20secret.%0D%0ATrace%20ID:%2004f4ab60-440a-4273-8849-821ebcb91d00%0D%0ACorrelation%20ID:%20bd03dc97-7b60-43c5-a196-0ce985ba9a3d%0D%0ATimestamp:%202020-05-13%2014:25:02Z&timestamp=2020-05-13%2014:25:02Z&trace_id=04f4ab60-440a-4273-8849-821ebcb91d00&correlation_id=bd03dc97-7b60-43c5-a196-0ce985ba9a3d, httpMetadata: HttpMetadata{status=400, cachePolicy=NO_CACHE, cacheDurationJava=null, cacheImmutable=false, staleWhileRevalidate=null, filename=null, lastModified=null, retryAfter=null, headers=HTTP/1.1 200 OK

**Comment by MeghaB** [comment]
Hi @nirav98 - We're not seeing any issues across the board, and this might be specific to your project or integration... If [you could file a support ticket](https://firebase.google.com/support/troubleshooter/contact), we can follow up and investigate further!
