### ISSUE TITLE
Crashlytics doesn't work in China

### ISSUE THREAD

**Issue by RoCry** [firebase/firebase-ios-sdk#5599]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 11.3.1 (11C504)
  * Firebase SDK version: 6.24.0
  * Firebase Component: Crashlytics
  * Component version: 6.24.0
  * Installation method: `Carthage` (select one)

### [REQUIRED] Step 2: Describe the problem

The settings will always failed if no VPN in China

#### Relevant Code:

```
6.24.0 - [Firebase/Crashlytics][I-CLS000000] Failed to download settings Error Domain=FIRCLSNetworkError Code=-6 "(null)" UserInfo={retryLimit=1, NSErrorFailingURLStringKey=https://firebase-settings.crashlytics.com/spi/v2/platforms/ios/gmp/1:xxxx:ios:xxxx/settings?build_version=20243&display_version=3.0.5&instance=xxxx&source=1}
```

**Comment by morganchen12** [comment]
We're looking into it and will post an update on this thread when it's available. Thanks for reporting this issue!

**Comment by TKBurner** [comment]
Thanks folks. The team has not seen similar problems when diving into our logs, they are adding extra logging to verify and I will add details when I get an update.

**Comment by RoCry** [comment]
And I could see the analytics events, but no crash report, don't know if its because of the setting problem.

**Comment by colin1994** [comment]
Firebase SDK version: 6.23.0
Firebase Component: Crashlytics
Component version: 6.23.0

Also in China, when we used VPN, the crash failed to report.

**1. No VPN**
The settings will always be failed, but we can see the crash in our dashboard.

```
[Firebase/Crashlytics] Packaged report with id 'xxxxxxxx' for submission
```
```
6.23.0 - [Firebase/Crashlytics][I-CLS000000] Failed to download settings Error Domain=FIRCLSNetworkError Code=-6 "(null)" UserInfo={retryLimit=1, NSErrorFailingURLStringKey=https://firebase-settings.crashlytics.com/spi/v2/platforms/ios/gmp/xxxx}
```

**2. Use VPN**
After we use VPN, ping **settings.crashlytics.com** is feasible, and at the same time will not receive the log of failed to download settings.

But after that, **the crash report will always fail, and we can't see it in the dashboard. Even after turning off the VPN, it will continue to fail.**

```
[Firebase/Crashlytics] Packaged report with id 'xxxxxxxx' for submission
```
```
Submitted Activity: com.apple.CFNetwork-cc-88-53-Task <xxxxxxxxxx>.<com.google.firebase.crashlytics.ios.crash.background-session>.<1>:754255 at priority 90 <private>
```

```
com.apple.CFNetwork-cc-88-53-Task <xxxxxxxxxx>.<com.google.firebase.crashlytics.ios.crash.background-session>.<1>:754255:[
	{name: ApplicationPolicy, policyWeight: 5.000, response: {Decision: Can Proceed, Score: 0.01}}
	{name: DeviceActivityPolicy, policyWeight: 10.000, response: {Decision: Can Proceed, Score: 0.39}}
 ] sumScores:24.607143, denominator:35.700000, FinalDecision: Can Proceed FinalScore: 0.689276}
```

```
'com.apple.CFNetwork-cc-88-53-Task <xxxxxxxxxx>.<com.google.firebase.crashlytics.ios.crash.background-session>.<1>:754255' DecisionToRun:1 (Bypasses Predictions)
```
```
NO LONGER RUNNING com.apple.CFNetwork-cc-88-53-Task <xxxxxxxxxx>.<com.google.firebase.crashlytics.ios.crash.background-session>.<1>:754255 ...Tasks running in group [<private>] are 0!
```

This confuses me. Can you help me to take a look?

**Comment by morganchen12** [comment]
@TKBurner, please attach a bug number to this issue.

**Comment by pro648** [comment]
Firebase SDK version: 6.25.0
Firebase Component: Firebase/Crashlytics Firebase/Analytics
Component version: 6.25.0

When app launch after it crashed, Firebase try to visit 

- https://firebase-settings.crashlytics.com
- https://firebaseinstallations.googleapis.com
- https://firebaselogging-pa.googleapis.com

And all these connections time out, only follow url succeed:

- https://crashlyticsreports-pa.googleapis.com

Did every crash report upload to https://crashlyticsreports-pa.googleapis.com ?

**Comment by YangPeiqiu** [comment]
Crashlytics doesn't work in China
I also found that only using VPN is good

Otherwise,

```
UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://firebaselogging-pa.googleapis.com/v1/firelog/legacy/batchlog
```

```
UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://settings.crashlytics.com/spi/v2/platforms/ios/apps/
```

**Comment by colin1994** [comment]
> Firebase SDK version: 6.23.0
> Firebase Component: Crashlytics
> Component version: 6.23.0
> 
> Also in China, when we used VPN, the crash failed to report.
> 
> **1. No VPN**
> The settings will always be failed, but we can see the crash in our dashboard.
> 
> ```
> [Firebase/Crashlytics] Packaged report with id 'xxxxxxxx' for submission
> ```
> 
> ```
> 6.23.0 - [Firebase/Crashlytics][I-CLS000000] Failed to download settings Error Domain=FIRCLSNetworkError Code=-6 "(null)" UserInfo={retryLimit=1, NSErrorFailingURLStringKey=https://firebase-settings.crashlytics.com/spi/v2/platforms/ios/gmp/xxxx}
> ```
> 
> **2. Use VPN**
> After we use VPN, ping **settings.crashlytics.com** is feasible, and at the same time will not receive the log of failed to download settings.
> 
> But after that, **the crash report will always fail, and we can't see it in the dashboard. Even after turning off the VPN, it will continue to fail.**
> 
> ```
> [Firebase/Crashlytics] Packaged report with id 'xxxxxxxx' for submission
> ```
> 
> ```
> Submitted Activity: com.apple.CFNetwork-cc-88-53-Task <xxxxxxxxxx>.<com.google.firebase.crashlytics.ios.crash.background-session>.<1>:754255 at priority 90 <private>
> ```
> 
> ```
> com.apple.CFNetwork-cc-88-53-Task <xxxxxxxxxx>.<com.google.firebase.crashlytics.ios.crash.background-session>.<1>:754255:[
> 	{name: ApplicationPolicy, policyWeight: 5.000, response: {Decision: Can Proceed, Score: 0.01}}
> 	{name: DeviceActivityPolicy, policyWeight: 10.000, response: {Decision: Can Proceed, Score: 0.39}}
>  ] sumScores:24.607143, denominator:35.700000, FinalDecision: Can Proceed FinalScore: 0.689276}
> ```
> 
> ```
> 'com.apple.CFNetwork-cc-88-53-Task <xxxxxxxxxx>.<com.google.firebase.crashlytics.ios.crash.background-session>.<1>:754255' DecisionToRun:1 (Bypasses Predictions)
> ```
> 
> ```
> NO LONGER RUNNING com.apple.CFNetwork-cc-88-53-Task <xxxxxxxxxx>.<com.google.firebase.crashlytics.ios.crash.background-session>.<1>:754255 ...Tasks running in group [<private>] are 0!
> ```
> 
> This confuses me. Can you help me to take a look?


In more detail, 
when we are **not using VPN,** the reported request is `https://crashlyticsreports-pa.googleapis.com/v1/firelog/legacy/batchlog`. At this time, the crash was reported normally.

But when we **use VPN**, the reported request is `https://reports.crashlytics.com/sdk-api/v1/platforms/ios/apps/xxxxx/reports.` At this time, the dashboard cannot see the corresponding crash.

How to solve this, is it my configuration problem? 
This has troubled us for a long time...

**Comment by fenjuly** [comment]
I found that there was also a bug in Android Crashlytics.
sometime it works, sometimes doesn't work.
I believe it could be a server bug, some servers can't be accessed in mainland China.
Is there any plan to fix this issue?

**Comment by pedped** [comment]
we have same problem in Iran, my app reports crashes to server very well, but before three days ago, there was no report and after investigation, I found that it works well with VPN. 

I am using latest google Firebase Crashlytics . hope that fixed soon

**Comment by AlessandroMulloni** [comment]
I am having the same issue in Austria. Is there any update on this? My error message:

Task <A40D6C15-088F-4879-8D73-B7EC2D1FCD58>.<2> finished with error [-1001] Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x280148f90 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://crashlyticsreports-pa.googleapis.com/v1/firelog/legacy/batchlog, NSErrorFailingURLKey=https://crashlyticsreports-pa.googleapis.com/v1/firelog/legacy/batchlog, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}

I cannot see any crash reports in my console.

**Comment by morganchen12** [comment]
@AlessandroMulloni @pedped please file [support tickets](https://firebase.google.com/support) instead of commenting here.
