### ISSUE TITLE
Database returning wrong values 

### ISSUE THREAD

**Issue by ssiddi28** [firebase/firebase-ios-sdk#56]
* Xcode version: 8.3.2
  * Firebase SDK version: Using cocoapod

An issue started occurring last night with a production app. It seems the firebase database values that are being returned are incorrect. What should be an array is being returned as a Dictionary.

**Here is a screenshot of the database**
![screen shot 2017-06-02 at 4 57 20 am](https://cloud.githubusercontent.com/assets/4510613/26721080/22759610-4750-11e7-9f8f-b75c182521d6.png)
 
**Here is a screen shot of the console printout of the returned value**
![screen shot 2017-06-02 at 4 59 08 am](https://cloud.githubusercontent.com/assets/4510613/26721115/4b68d9ce-4750-11e7-95ca-0c26f2da4bdb.png)

##  **The highlighted area in the picture above shows that what should be returned as elements in an array are being returned as keys in a dictionary.**

**Heres a screenshot of the exported json file**
![screen shot 2017-06-02 at 5 01 35 am](https://cloud.githubusercontent.com/assets/4510613/26721188/9d81d2ce-4750-11e7-8cbd-d28507e19f6b.png)

Why is this being returned incorrectly all of a sudden??
Again the apps been in production for the past month with no issues, and this problem started occurring last night with no changes made in my code or on the database. 

Heres a screenshot of the code
![screen shot 2017-06-02 at 5 03 02 am](https://cloud.githubusercontent.com/assets/4510613/26721295/fac11f1c-4750-11e7-87ae-08d38243b593.png)

**Comment by morganchen12** [comment]
Are there any items in your array with a non-numeric key? Can you share the full export in a gist?

**Comment by paulb777** [comment]
Closing due to lack of response. Please reopen if it's still an issue and you have more data.
