### ISSUE TITLE
Auth apparently uses Google API that is shutdown on May 30th 2020

### ISSUE THREAD

**Issue by nerdaliciousCH** [firebase/firebase-ios-sdk#5606]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4.1
  * Firebase SDK version: 6.24.0
  * Firebase Component: Auth
  * Component version:  6.5.3
  * Installation method: CocoaPods

#### Steps to reproduce:

This SDK seems to use [this](https://developers.google.com/identity/toolkit/web/reference/relyingparty/) API which is said to be discontinued on May 30th 2020. This could be observed and verified by using a proxy to see the encrypted communication in plain text and verify that all calls to the firebase-ios-sdk, at least in our project, resulted in network traffic targeting the googleapis.com/identitytoolkit/v3/relyingparty endpoints. I also altered the code in the corresponding Firebase/Auth Pods and got the sign in requests to go to a news-website, so I was sure that's the actual code effecting this.

This SDK is used in the most up-to-date version 6.24.0 in [RNFirebase](https://rnfirebase.io/auth/usage) for react-native. I already made [an issue](https://github.com/invertase/react-native-firebase/issues/3646) there, because I wasn't sure if this a misuse of your SDK or an issue here.

So the question is: Are those endpoints really discontinued ("shutdown" as it says on the API doc linked above). Are those endpoints maybe redirected and then not actually "shutdown"? Does the SDK somehow fall back to the new Identity Platform endpoints? Or maybe an issue at RNFirebase's side still?

At the end, this seems way too scary. We are 3 weeks away of this deadline and it seems like we are facing a complete shutout of our App.

And of course, maybe I am missing something and am actually making a fool out of myself :D

#### Relevant Code:

Use mitmproxy to see where the requests go to on an iPhone using the latest firebase-ios-sdk

**Comment by MeghaB** [comment]
Hi @nerdaliciousCH. 

The shutdown on May 30th is for GITKit SDK (the sdk prior to Firebase Auth). **The endpoints listed in your link won't be affected.
Our iOS SDK is using both versions of the endpoints. We have no plan to shutdown either of them.**

I'm sorry we worried you here - I'm looking into updating the shutdown wording to be more clear so we prevent these scares as we get closer to May 30!

**Comment by nerdaliciousCH** [comment]
Hi!

So it is still a bit confusing for me. If I want to get an idToken in a Web client, I can on June 1st 2020 still call https://googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword, despite the fact it says it will be shut down? So the REST Api will work? And then of course I assume the firebase-ios-sdk will still work, because it uses that same REST Api?

Thank you for the response, Cheers
