### ISSUE TITLE
Debug View issue on iOS - Firebase v6.1.0

### ISSUE THREAD

**Issue by bluelagon** [firebase/firebase-ios-sdk#5608]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11
  * Firebase SDK version: 6.1.0
  * Firebase Component: Core (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 6.0.1
  * Installation method: `CocoaPods`

### [REQUIRED] Step 2: Describe the problem

I followed this page: `https://firebase.google.com/docs/analytics/debugview#ios`
I set the flag `-FIRDebugEnabled` in app's scheme.
The debugView doesn't display my device.

I added: `Analytics.setAnalyticsCollectionEnabled(true)` when configuring Firebase.
Didn't work.

I tried with `-FIRAnalyticsDebugEnabled`. Didn't work.

I added `IS_ANALYTICS_ENABLED` to YES in the GoogleService-info.plist.
Still didn't work.

#### Steps to reproduce:

In the console, I have these kind of messages:
`Debug mode is enabled. Marking event as debug and real-time....`
`Event logged. Event name, event params: screen_view`
But nothing appears in debug View.

**Comment by yuriramocan** [comment]
+1 I am using `Firebase/Analytics` version `6.24.0` and am also experiencing this issue. I tried reverting back to `6.23.0`, but that didn't help.

**Comment by asos-christianr** [comment]
I'm experiencing the same issue when trying to upgrade to 6.24.0. I tried the same with our existing version of 6.19.0, which also doesn't work anymore.

**Comment by max-vyshnevskyi** [comment]
Same here. SDK version `6.23.0`

**Comment by ryanwilson** [comment]
cc @eburley (since I can't assign you for whatever reason)

**Comment by allenktv** [comment]
Hi @bluelagon, since the update, are you able to see any new events on BigQuery or the Firebase Console?

**Comment by bluelagon** [comment]
Hi @allenktv, I also updated to the latest version of Firebase (6.24.0) and I also have no devices in the debugView.

**Comment by bluelagon** [comment]
I just tested with the simulator and it worked with the 6.0.1 and the 6.24.0. 

<img width="286" alt="Capture d’écran 2020-05-16 à 09 05 31" src="https://user-images.githubusercontent.com/32433902/82113232-c49ea600-9754-11ea-9e2e-83bd29dab2e7.png">

Thank you.

**Comment by dtrenz** [comment]
This is also working for me now. Must have been a server-side issue.
