### ISSUE TITLE
FR: Firestore @propertyWrapper that indicates a property should NOT be encoded/decoded

### ISSUE THREAD

**Issue by xaphod** [firebase/firebase-ios-sdk#5609]
* Firebase Component: Firestore

Currently with FirebaseFirestoreSwift pod we have the ability to use `@propertyWrapper` like `@DocumentID`, `@ServerTimestamp` etc.

**tl;dr**: the ability to easily exclude a few variables from being encoded/decoded by FirestoreEncoder.

**deets**
Rather than have to explicitly list out a long list of `CodingKey` just to exclude a single value from being written-to/read-from Firestore, it would be great if you could add a `@propertyWrapper` such as **@NotFirestored** (silly name I know), which simply causes the `FirestoreEncoder` to skip over the variable. This would of course imply that either this variable is optional, or has an initial value specified.

Thanks for continuing to make Firestore more and more awesome when used with Swift!

**Comment by thebrianchen** [comment]
@xaphod From what I've gathered, it currently does not seem possible to exclude properties from Codable (see [discussion](https://forums.swift.org/t/excluding-properties-from-automatic-codable/13816/5)), and I haven't been able to find any other sources that indicate otherwise. However, we could add a `@propertyWrapper` such as `@Ignore` that would set the field to `nil`. Would you find such a feature useful?

**Comment by xaphod** [comment]
Interesting thanks - would that only work for optional values, or would it work for non-optionals too? Either way, yes I would find that useful.

**Comment by wilhuff** [comment]
Optional values that are `nil` are already omitted when encoding--you don't need a special property wrapper for that. This is why we have `@ExplicitNull` to force the key to exist.

**Comment by thebrianchen** [comment]
At the present moment, there is no way to exclude certain properties from being encoded by Codable with a `@propertyWrapper`. I believe what you are requesting is mentioned in this [thread](https://forums.swift.org/t/codable-improvements-and-refinements/19426/4) as a feature request for Codable. However, we will look into getting an `@Ignore` wrapper into the SDK -- thanks for the suggestion!
