### ISSUE TITLE
Getting issue while pod update.

### ISSUE THREAD

**Issue by webkul-ramakant** [firebase/firebase-ios-sdk#5618]
Installing GoogleUtilities 6.6.0 (was 5.8.0)

[!] Error installing GoogleUtilities
[!] /usr/bin/git clone https://github.com/firebase/firebase-ios-sdk.git /var/folders/70/rxvp7g552f3b7xwxsnjl2pn00000gr/T/d20200516-71577-1ju50k9 --template= --single-branch --depth 1 --branch Utilities-6.6.0

Cloning into '/var/folders/70/rxvp7g552f3b7xwxsnjl2pn00000gr/T/d20200516-71577-1ju50k9'...
remote: Internal Server Error.
remote: 
fatal: unable to access 'https://github.com/firebase/firebase-ios-sdk.git/': The requested URL returned error: 500

**Comment by paulb777** [comment]
@webkul-ramakant Thanks for the report. This is almost certainly an intermittent network failure. Please retry.  

I'm going to close. If the problem continues for more than a few hours without other network issues, comment and we'll reopen.

**Comment by tahir-jamil** [comment]
```
[!] Error installing FirebaseRemoteConfig
[!] /usr/local/bin/git clone https://github.com/firebase/firebase-ios-sdk.git /var/folders/n_/jzw8b4fj3hdd25xwjmcjj3140000gn/T/d20200527-7532-ci70tj --template= --single-branch --depth 1 --branch RemoteConfig-4.4.11

Cloning into '/var/folders/n_/jzw8b4fj3hdd25xwjmcjj3140000gn/T/d20200527-7532-ci70tj'...
fatal: unable to access 'https://github.com/firebase/firebase-ios-sdk.git/': LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

'pod install' command failed.
```
