### ISSUE TITLE
To attach and then detach one child event, do you have to detach all child events afterwards?

### ISSUE THREAD

**Issue by coolcool1994** [firebase/firebase-ios-sdk#5619]
According to this https://github.com/firebase/firebase-android-sdk/issues/1551, when you add any one of childListener such as childAdded, childMoved, childDeleted, or childChanged, iOS Firebase SDK would internally set up all child listener for all child events, resulting in the bill for data downloaded ($1 per 1GB) for all childEvents for that node.

My question is if you add childAddedListener and detach that childAddedListener at that path and handle ID using removeObserverWithHandle, would all childEventListeners be detached so it doesn't cost anymore for data downloaded? Or do you have to detach childMoved, childDeleted, and ChildChanged as well even though you only previously attached childAddedListener. I ask this question because the Firebase client SDK sets up all child event listeners internally when when you attach just one child event listener.

There is no way for me to test / log this so I ask this question here. In android, you attach one childEventListener and detach one childEventListener all times (they are all grouped together).

**Comment by schmidt-sebastian** [comment]
@coolcool1994 Thanks for asking this question!

The SDK only syncs data for locations with active listeners. That means that we will stop listening if you detach all listeners for a specific location. If you attach a single childAddedListener, no data will be transferred when that listener is removed. If you attach a childAddedListener and a childDeletedListener, you have to remove both. Removing just one out of the two listeners will not reduce data transfers.
