### ISSUE TITLE
156914582: Firebase In App Messaging not showing the modal

### ISSUE THREAD

**Issue by app-web-dev** [firebase/firebase-ios-sdk#5624]
When I try to test the in app messaging on IOS app based on Firebase doc. I do get the following on my console:

Min impression time has been reached.
2020-05-16 15:03:34.619338+0100 Didar[9503:2251336] 6.17.0 - [Firebase/InAppMessaging][I-IAM400011] A test message. Record the test message impression event.

but the modal is not displaying on the app?

```

**Comment by christibbs** [comment]
@app-web-dev I couldn't reproduce this. Is it possible for you to upgrade to the latest in-app messaging SDK? I believe you're on 0.17.0.
