### ISSUE TITLE
Sign in with Apple doesn't throw .MissingOrInvalidNonce

### ISSUE THREAD

**Issue by savelii** [firebase/firebase-ios-sdk#5626]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4 (11E146)
  * Firebase SDK version: 6.24.0
  * Firebase Component: Auth
  * Component version: 6.24.0
  * Installation method: Carthage

### [REQUIRED] Step 2: Describe the problem
I implemented sign in with Apple according to "Authenticate Using Apple on iOS" firebase [tutorial](https://firebase.google.com/docs/auth/ios/apple). I decide to test wrong nonce but account was successfully created. 
I tried several times, tried deleting account in Firebase Auth console, removing Apple Sign In in iPhone settings, reinstalling app and checked that I am not already logged in and test clear run from scratch.

#### Steps to reproduce:

1. Implement "Authenticate Using Apple on iOS" according [tutorial](https://firebase.google.com/docs/auth/ios/apple)
2. Change 'nonce' to any wrong String when creating: 
OAuthProvider.credential(withProviderID: "apple.com", IDToken: idTokenString, rawNonce: nonce)

#### Relevant Code:

```
let credential = OAuthProvider.credential(withProviderID: "apple.com", idToken: idTokenString, rawNonce: "AnyStringThatNotTheRightNonce")

Auth.auth().signIn(with: credential) { (authResult, error) in
    if let error = error {
        // Error. If error.code == .MissingOrInvalidNonce, make sure
        // you're sending the SHA256-hashed nonce as a hex string with
        // your request to Apple.
        print(error.localizedDescription) // NEVER GET HERE DESPITE WRONG NONCE
        return
    }
    // User is signed in to Firebase with Apple.
    // ...
}
```

**Comment by morganchen12** [comment]
Thanks @savelii, this looks like a bug.

**Comment by MeghaB** [comment]
For internal tracking: b/156932868

**Comment by bojeil-google** [comment]
Is there an actual nonce in the Apple ID token? Please inspect your Apple ID token claims (you can use jwt.io). If there is no nonce in the ID token, then we ignore the check.

**Comment by bojeil-google** [comment]
This part specifically:

```
let request = appleIDProvider.createRequest()
request.requestedScopes = [.fullName, .email]
// Nonce needs to be set.
request.nonce = sha256(nonce)
```

**Comment by bojeil-google** [comment]
We tried to reproduce it and it failed when we passed an incorrect `rawNonce`:
"ERROR_MISSING_OR_INVALID_NONCE" received.

I speculate, you are not setting it correctly in the Apple ID token to begin with.

**Comment by savelii** [comment]
I was thinking check always take place, independly nil or not nonce in jwt.
Yes I inspecting token and nonce is missing, error was with custom sha256 function that return nil, my fault.
Thanks for help, I close issue.
