### ISSUE TITLE
Requests to this API identitytoolkit method google.cloud.identitytoolkit.v1.AuthenticationService.SignUp are blocked.

### ISSUE THREAD

**Issue by takauser** [firebase/firebase-ios-sdk#5628]
```
Error Domain=FIRAuthErrorDomain Code=17999 "An internal error has occurred, print and inspect the error details for more information." UserInfo={FIRAuthErrorUserInfoNameKey=ERROR_INTERNAL_ERROR, NSLocalizedDescription=An internal error has occurred, print and inspect the error details for more information., NSUnderlyingError=XXX {Error Domain=FIRAuthInternalErrorDomain Code=3 "(null)" UserInfo={FIRAuthErrorUserInfoDeserializedResponseKey={
    code = 403;
    errors =     (
                {
            domain = global;
            message = "Requests to this API identitytoolkit method google.cloud.identitytoolkit.v1.AuthenticationService.SignUp are blocked.";
            reason = forbidden;
        }
    );
    message = "Requests to this API identitytoolkit method google.cloud.identitytoolkit.v1.AuthenticationService.SignUp are blocked.";
    status = "PERMISSION_DENIED";
}}}}



Firebase Installation registration failed for app with name: __FIRAPP_DEFAULT, error: Error Domain=com.firebase.installations Code=0 "The server responded with an error. HTTP response: <NSHTTPURLResponse: 0x600002e202c0> { URL: https://firebaseinstallations.googleapis.com/v1/projects/XXX/installations/ } { Status Code: 403, Headers {
    "Cache-Control" =     (
        private
    );
    "Content-Encoding" =     (
        gzip
    );
    "Content-Length" =     (
        319
    );
    "Content-Type" =     (
        "application/json; charset=UTF-8"
    );
    Date =     (
        "Mon, 18 May 2020 07:14:45 GMT"
    );
    Server =     (
        ESF
    );
    Vary =     (
        Origin,
        "X-Origin",
        Referer
    );
    "alt-svc" =     (
        XXX
    );
    "x-content-type-options" =     (
        nosniff
    );
    "x-frame-options" =     (
        SAMEORIGIN
    );
    "x-xss-protection" =     (
        0
    );
} }
```
<img width="576" alt="スクリーンショット 2020-05-18 16 22 17" src="https://user-images.githubusercontent.com/56075596/82185291-f87bf600-9923-11ea-8ebe-af4c27966d77.png">

Tell me how to solve this problem.

**Comment by maksymmalyhin** [comment]
@takauser The error most likely indicates the project misconfiguration (invalid API key, API key restriction or API key to project ID mismatch, etc.). Could you please make sure:
1. you are using the most recent version of `GoogleServices-Info.plist` in your application
2. The API key restrictions for the key from `GoogleServices-Info.plist` are configured correctly (you may follow [these steps](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseInstallations/API_KEY_RESTRICTIONS.md))

If you still have issues I would suggest:
1. Test your iOS app with another Firebase project `GoogleServices-Info.plist`.
  - If the issue occurs only for a specific Firebase Project please contact Firebase Support.
  - If the issue still occurs please make sure you configure Firebase following steps from the [guide](https://firebase.google.com/docs/ios/setup).

**Comment by takauser** [comment]
Thanks for your help. I created another Firebase project and it worked well.
I don't know why it happened.
