### ISSUE TITLE
gRPCCertificates-Cpp.bundle is none

### ISSUE THREAD

**Issue by CatLuck2** [firebase/firebase-ios-sdk#5629]
Editor:Xcode
language:Swift

I downloaded Firebase framworks by Carthage.

<img width="632" alt="スクリーンショット 2020-05-18 19 06 29" src="https://user-images.githubusercontent.com/43905123/82201121-d80b6600-993a-11ea-9d16-c3a6edaafdda.png">
<img width="337" alt="スクリーンショット 2020-05-18 19 06 38" src="https://user-images.githubusercontent.com/43905123/82201131-db9eed00-993a-11ea-83c4-c60ab7194814.png">

But, gRPCCertificates-Cpp.bundle isn't founded, so I can't use Firebase by Carthage. 

Please, tell me solution.

**Comment by CatLuck2** [comment]
I solved this to find gRPCCertificates-Cpp.bundle.

**Comment by wilhuff** [comment]
Since the [Firebase 6.13.0 release](https://firebase.google.com/support/release-notes/ios#version_6130_patch_release_-_november_19_2019), Firestore no longer uses `gRPCCertificates-Cpp.bundle`. If you're using at least this version, you shouldn't need this for building with Carthage.
