### ISSUE TITLE
FirebaseCrashlytics does not send reports if AdMob is added to the project

### ISSUE THREAD

**Issue by pruinis** [firebase/firebase-ios-sdk#5642]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4.1
  * Firebase SDK version: 6.24.0
  * Firebase Component: AdMob, Analytics, Crashlytics
  * Component version: Analytics (6.24.0), Crashlytics (6.24.0), AdMob (6.24.0)
  * Installation method: CocoaPods

#### Steps to reproduce:

If `[FIRApp configure]` inside `didFinishLaunchingWithOptions:`
When AdMob is added to the project, Crashlytics log stops at "_Unsent reports will be uploaded at startup_" and no saved crash reports are sent.

If `[FIRApp configure]` inside `GADMobileAds` completionHandler all saved crash reports sent as usual with message: "_report submission successful_"
```
[[GADMobileAds sharedInstance] startWithCompletionHandler:^(GADInitializationStatus * _Nonnull status) {
        [FIRApp configure];
 }];
```

**Comment by pruinis** [comment]
Xcode console log if `[FIRApp configure]` inside `didFinishLaunchingWithOptions:`
 
<img width="493" alt="Screen Shot 2020-05-19 at 16 30 23" src="https://user-images.githubusercontent.com/3088252/82334398-976e2400-99f0-11ea-9f77-b34be9348136.png">

**Comment by pruinis** [comment]
Example project:
[TestAdMobCrashlytics.zip](https://github.com/firebase/firebase-ios-sdk/files/4650942/TestAdMobCrashlytics.zip)

**Comment by samedson** [comment]
Thanks for reaching out @pruinis. This is likely a problem where multiple crash reporters have trouble registering exception handlers.

Can you try the following setting with the AdMob SDK when your app starts up:

```
  GADMobileAds.disableSDKCrashReporting()

```

From https://developers.google.com/admob/ios/global-settings#crash_reporting

**Comment by pruinis** [comment]
@samedson Thank you for your reply!
As I understand it, my code should look like this?
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
        
    [[GADMobileAds sharedInstance] disableSDKCrashReporting];
    [FIRApp configure];
    
    return YES;
}
```

It was somewhat unexpected for me that the component that should be used for advertising (AdMob) could block the component that is responsible for collecting crash repots (Crashlytics).
Is this the right interaction between these components?
If yes, I did not find a mention of this in the [Crashlytics Integration guide](https://firebase.google.com/docs/crashlytics/get-started?platform=ios)

**Comment by samedson** [comment]
I believe that's right (though you might need to remove the `sharedInstance` call from GADMobileAds).

Yeah it's definitely unintuitive - this is great feedback. I'll look into improving our documentation or seeing if there's a technical way we can improve this.

Did disabling calling `disableSDKCrashReporting` fix the problem?

**Comment by pruinis** [comment]
@samedson 

> I believe that's right (though you might need to remove the sharedInstance call from GADMobileAds).

![Screen_Shot_2020-05-20_at_23_00_28](https://user-images.githubusercontent.com/3088252/82491846-eb126780-9aed-11ea-9fe2-cfa3382fb103.jpg)

**Comment by pruinis** [comment]
> Did disabling calling disableSDKCrashReporting fix the problem?
Yes, thank you very much!

**Comment by samedson** [comment]
Awesome! Thank you for the report!
