### ISSUE TITLE
Why static library nanopb is deployment target still iOS4.3?

### ISSUE THREAD

**Issue by jormungand2006** [firebase/firebase-ios-sdk#5651]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.25.0
  * Firebase Component: FirebaseAnalytics
  * Component version: 6.5.1
  * Installation method: `CocoaPods

### [REQUIRED] Step 2: Describe the problem

When I install Firebase/Analytics by Pods (static), then build my project for iOS simulator, I notice that Xcode show the following warning.

"The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 4.3, but the range of supported deployment target versions is 8.0 to 13.2.99."

Actually  nanopb deployment target is set iOS4.3.

However when I install by Pods (dynamic), nanopb deployment target is iOS8.0.

So my question is that is intended build configuration? I want to fix the warning even with static If I can.

**Comment by morganchen12** [comment]
nanopb has almost no dependencies, which means it can support iOS 4.3 without significant effort on the library maintainers' behalf. It's also open source, so you can check out the code for yourself: https://github.com/nanopb/nanopb
