### ISSUE TITLE
[FIRStorageUploadTask] putData completion is not called when internet connection is offline

### ISSUE THREAD

**Issue by Masataka-n** [firebase/firebase-ios-sdk#5652]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4.1
  * Firebase SDK version: 6.25.0
  * Firebase Component: Storage
  * Component version: 3.6.1
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

Completion of putData of FIRStorageReference is not executed when uploading to storage when the terminal is offline (airplane mode).

#### Steps to reproduce:
Put your device in airplane mode and run the code below.

```
let reference: StorageReference = self.storageReference
let task: StorageUploadTask = reference.putData(data, metadata: metadata) { (metadata, error) in
    // Not called                
}
```

**Comment by schmidt-sebastian** [comment]
@Masataka-n Thanks for taking the time to open this issue!

The Storage SDK retries uploads. When your device goes back online, `putData` will execute and the callback will be called. If this behavior does not suit your needs, you need to manually verify the network status before invoking any Storage APIs.
