### ISSUE TITLE
When downloading dependency to FirebaseCrashlytics via Carthage, upload_symbols script is missing

### ISSUE THREAD

**Issue by Cronay** [firebase/firebase-ios-sdk#5653]
* Xcode version: most recent
  * Firebase SDK version: most recent
  * Firebase Component: Crashlytics (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: most recent
  * Installation method: Carthage

#### Steps to reproduce:

Create a new empty directory and place a Cartfile in it with a 'binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashlyticsBinary.json"'. Then fetch the binary via 'carthage update'. I'd expect the resulting directory 'Carthage/Build/iOS/FirebaseCrashLytics.framework' to contain the upload_symbols script, but it doesn't in my case.

**Comment by maksymmalyhin** [comment]
This is an intentional behaviour. Please follow the Crashlytics specific steps from the [Carthage guide](https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md). 

I'm closing the ticket but feel free to reopen if you still have issues.

**Comment by marcelofabri** [comment]
@maksymmalyhin How would one know that the script have changed? Should we compare it every time we update Crashlytics? That seems very error-prone 😱

**Comment by maksymmalyhin** [comment]
@marcelofabri I agree, the process doesn't look ideal. With the current setup you should update the scripts each time you update Firebase to be on the safe side. 
The motivation for the current process is explained [here](https://github.com/firebase/firebase-ios-sdk/issues/4720#issuecomment-577213858).
