### ISSUE TITLE
Firebase Fabric Crashlytics not sending data to server

### ISSUE THREAD

**Issue by anush-shenoy** [firebase/firebase-ios-sdk#5659]
bundleID: com.mobileuat.nsdlpb
Xcodeversion :11.4.1
Crashlytics:4.0.0
Firebace:6.23.0

Getting the following error log:
[Firebase/Crashlytics][I-CLS000000] Failed to download settings Error Domain=FIRCLSNetworkError Code=-5 "(null)" UserInfo={status_code=404, type=2, request_id=, content_type=text/html; charset=utf-8}

**Comment by morganchen12** [comment]
Please fill out the issue template. Are you able to isolate the cause of the network failure at all?

**Comment by anush-shenoy** [comment]
tried this on multiple networks there is no change. i get the same error across..

**Comment by morganchen12** [comment]
Can you reproduce this issue in a sample project and send it to us?

**Comment by rostopira** [comment]
I'm not getting crash-reports, and no errors in logs as well
