### ISSUE TITLE
GoogleDataTransport][I-GDTCOR001006] Error?

### ISSUE THREAD

**Issue by makinggainz** [firebase/firebase-ios-sdk#5661]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 11.4.1
  * Firebase SDK version: _____
  * Firebase Component: Database (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: _____
  * Installation method: `**CocoaPods** | Carthage | Zip file` (select one) = CocoaPods

### [REQUIRED] Step 2: Describe the problem
II had been working on my project like normal when all of a sudden I got this error: 

    > 2020-05-20 01:42:40.798198-0400 [10404:4763011] [GoogleDataTransport][I-GDTCOR001006] There was an error reading extension bytes from disk: Error Domain=NSCocoaErrorDomain Code=260 "The file “event-16738913419221216480” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/var/mobile/Containers/Data/Application/B3D1204C-A52F-496C-89D8-388D4A75C102/Library/Caches/google-sdks-events/event-16738913419221216480, NSUnderlyingError=0x2838cdbf0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

The error occures in the file seen bellow. 

[![enter image description here][1]][1]
The specific line error is:

 
    
    > Thread 1: EXC_BAD_ACCESS (code=2, address=0x16bcfffb0)

For the second line here: 

    NSString *pathString = [self
    decodePath:[NSString stringWithFormat:@"/%@", originalPathString]]; //this line
    FPath *path = [[FPath alloc] initWith:pathString];
    FRepoInfo *repoInfo = [[FRepoInfo alloc] initWithHost:host
                                                 isSecure:secure
                                            withNamespace:namespace];

    FFLog(@"I-RDB095002", @"---> Parsed (%@) to: (%@,%@); ns=(%@); path=(%@)",
          url, [repoInfo description], [repoInfo connectionURL],
          repoInfo.namespace, [path description]);

    FParsedUrl *parsedUrl = [[FParsedUrl alloc] init];
    parsedUrl.repoInfo = repoInfo;
    parsedUrl.path = path;

    return parsedUrl;

I tried removing my pods and re-installing them. This did not change anything. 

I have also tried restarting my computer.

I also tried pod update. 

**How can I solve this problem?**

  [1]: https://i.stack.imgur.com/uF53N.png
#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by ryanwilson** [comment]
Hi @makinggainz, thanks for the report and sorry for the trouble.

This appears to be two different things you're seeing - one is a warning log from GoogleDataTransport that can be found here: 
https://github.com/firebase/firebase-ios-sdk/blob/78ee63dab3591da1287830024ab7ab1cce103bfa/GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m#L157-L161

and the other may be a crash in FirebaseDatabase.

A few questions:
- Are you able to reliably reproduce the crash with Database? If so, does it reproduce in our sample project or is there a project you could share that reproduces it?
- Can you please share a screenshot the full stack trace from Xcode?
- What version of the libraries are you using? Since you're using CocoaPods, sharing your Podfile.lock file would be sufficient.

When you get back to us with those answers we can dig in further. Thanks!

**Comment by makinggainz** [comment]
Thanks, @ryanwilson. 

- Are you able to reliably reproduce the crash with Database? If so, does it reproduce in our sample project or is there a project you could share that reproduces it?
I have tried reproducing but have not been successful. 
- Can you please share a screenshot the full stack trace from Xcode?
https://imgur.com/DfQVVNT
- What version of the libraries are you using? Since you're using CocoaPods, sharing your Podfile.lock file would be sufficient.

I was able to find this: 
`(base) Name@Names-MBP nonMapYubi % pod outdated
Updating spec repo `trunk`
Analyzing dependencies
The color indicates what happens when you run `pod update`
<green>	 - Will be updated to the newest version
<blue>	 - Will be updated, but not to the newest version because of specified version in Podfile
<red>	 - Will not be updated because of specified version in Podfile

The following pod updates are available:
- abseil 0.20200225.0 -> (unused) (latest version 1.20200225.0)
- BoringSSL-GRPC 0.0.7 -> 0.0.7 (latest version 0.0.8)
- Crashlytics 3.13.4 -> 3.13.4 (latest version 3.14.0)
- FBSDKCoreKit 5.15.1 -> 5.15.1 (latest version 7.0.0)
- FBSDKLoginKit 5.15.1 -> 5.15.1 (latest version 7.0.0)
- gRPC-C++ 1.28.2 -> 1.28.2 (latest version 1.29.0)
- gRPC-Core 1.28.2 -> 1.28.2 (latest version 1.29.0)
- Nuke 7.6.3 -> 7.6.3 (latest version 9.0.0)
(base) Name@Name-MBP nonMapYubi % pod --version
1.9.1
(base) Name@Name-MBP nonMapYubi % 
`

**Comment by makinggainz** [comment]
Update: 

After further testing, I found that the error occurs in various files within the firebaseDatabase folder, I also was able to isolate it to one query to the database found in multiple files. However under files after un-commenting it, it began working as before again. Given the number of queries however I still have the issue.

**Comment by mikehaney24** [comment]
As for the GoogleDataTransport console log warning, GDT versions >= 6.1.0 resolve that issue. I'm not sure about the issue regarding the EXC_BAD_ACCESS in FUtilities.m

**Comment by paulb777** [comment]
@makinggainz Please share the Podfile.lock and backtrace from the crash.
