### ISSUE TITLE
FIRInstanceID identifier not found

### ISSUE THREAD

**Issue by rahul-inspired-iosdeveloper** [firebase/firebase-ios-sdk#5662]
### Step 0: Are you in the right place?

  * Checked in all sources

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: _11.4____
  * Firebase SDK version: __6.24.0___
  * Firebase Component: __FirebaseRemoteConfig___ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: __4.4.10___
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem
I have a objective-c project, after updating firebase and other components the project is showing "FIRInstanceID" as unknown identifier.
#### Steps to reproduce:

After updating firebase pod repos in my objective-c project.

#### Relevant Code:

[[FIRInstanceID instanceID] instanceIDWithHandler:^(FIRInstanceIDResult * _Nullable result,
                                                        NSError * _Nullable error) {}];

**Comment by ryanwilson** [comment]
Hi @rahul-inspired-iosdeveloper - are you using the InstanceID in your own project, or are you trying to get it to trigger for Firebase purposes?

In version 4.4.10 the Remote Config SDK now depends on the FirebaseInstallations SDK instead of InstanceID. https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseRemoteConfig/CHANGELOG.md#v4410

If you explicitly need InstanceID still you can include it in your Podfile, otherwise migrating to FirebaseInstallations (FIS) for your own calls is recommended. Recently InstanceID switched to using the FIS implementation under the hood so the values coming back should be identical if you're upgrading from a recent version of Firebase (and IID).

**Comment by rahul-inspired-iosdeveloper** [comment]
> Hi @rahul-inspired-iosdeveloper - are you using the InstanceID in your own project, or are you trying to get it to trigger for Firebase purposes?
> 
> In version 4.4.10 the Remote Config SDK now depends on the FirebaseInstallations SDK instead of InstanceID. https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseRemoteConfig/CHANGELOG.md#v4410
> 
> If you explicitly need InstanceID still you can include it in your Podfile, otherwise migrating to FirebaseInstallations (FIS) for your own calls is recommended. Recently InstanceID switched to using the FIS implementation under the hood so the values coming back should be identical if you're upgrading from a recent version of Firebase (and IID).

I am using FIRInstanceID for my own debugging purpose, can I replace this with the library you mentioned?

**Comment by ryanwilson** [comment]
Yes, the respective call would be:

```
[[FIRInstallations installations] installationIDWithCompletion:]
```

Thanks! I'll close this for now but feel free to keep commenting as needed.

**Comment by maksymmalyhin** [comment]
> I am using FIRInstanceID for my own debugging purpose, can I replace this with the library you mentioned?

Absolutely. You can find some example of FirebaseInstallations usage at our [Quickstart repo](https://github.com/firebase/quickstart-ios), e.g. [Objective-C example](https://github.com/firebase/quickstart-ios/blob/d93daf59e83e8c16aca5a3b7d9c6c5932fc7bdda/installations/InstallationsExample/ViewController.m#L54). Let us know if it covers your use case or you need more information.

**Comment by rahul-inspired-iosdeveloper** [comment]
> > I am using FIRInstanceID for my own debugging purpose, can I replace this with the library you mentioned?
> 
> Absolutely. You can find some example of FirebaseInstallations usage at our [Quickstart repo](https://github.com/firebase/quickstart-ios), e.g. [Objective-C example](https://github.com/firebase/quickstart-ios/blob/d93daf59e83e8c16aca5a3b7d9c6c5932fc7bdda/installations/InstallationsExample/ViewController.m#L54). Let us know if it covers your use case or you need more information.

Thanks @maksymmalyhin let me try FirebaseInstallations, I will come here if I need any more assistance.

**Comment by rahul-inspired-iosdeveloper** [comment]
> Yes, the respective call would be:
> 
> ```
> [[FIRInstallations installations] installationIDWithCompletion:]
> ```
> 
> Thanks! I'll close this for now but feel free to keep commenting as needed.

Thanks @ryanwilson let me try this.

**Comment by rahul-inspired-iosdeveloper** [comment]
> Yes, the respective call would be:
> 
> ```
> [[FIRInstallations installations] installationIDWithCompletion:]
> ```
> 
> Thanks! I'll close this for now but feel free to keep commenting as needed.

@ryanwilson I need your help in one more thing

In the previous implementation parameter type was **FIRInstanceIDResult**

[[FIRInstanceID instanceID] instanceIDWithHandler:^(FIRInstanceIDResult * _Nullable result,
NSError * _Nullable error) {}];


when I am using this new library method **[[FIRInstallations installations] installationIDWithCompletion:^(NSString * _Nullable identifier, NSError * _Nullable error) {
        
    }];** its showing this method information 
"The method creates or retrieves an installation ID. The installation ID is a stable identifier
 * that uniquely identifies the app instance. NOTE: If the application already has an existing
 * FirebaseInstanceID then the InstanceID identifier will be used."

I got confused with both **FIRInstanceIDResult** and **identifier**

**Comment by maksymmalyhin** [comment]
@rahul-inspired-iosdeveloper Let me try to clear up the confusion. 
-  `identifier` returned by `[[FIRInstallations installations] installationIDWithCompletion:]` method is an equivalent of `FIRInstanceIDResult.instanceID` returned by `FIRInstanceID`
- `FIRInstallations` migrates the legacy instance ID and uses it as an Installation ID, so in most of the cases `identifier` and `FIRInstanceIDResult.instanceID` will be the same string for a device.

**Comment by rahul-inspired-iosdeveloper** [comment]
> @rahul-inspired-iosdeveloper Let me try to clear up the confusion.
> 
> * `identifier` returned by `[[FIRInstallations installations] installationIDWithCompletion:]` method is an equivalent of `FIRInstanceIDResult.instanceID` returned by `FIRInstanceID`
> * `FIRInstallations` migrates the legacy instance ID and uses it as an Installation ID, so in most of the cases `identifier` and `FIRInstanceIDResult.instanceID` will be the same string for a device.

Thanks @maksymmalyhin thank you very much, its all clear now.
