### ISSUE TITLE
157237503: InAppMessagingDisplayResources.bundle not included in framework 

### ISSUE THREAD

**Issue by laurenmarshallVS** [firebase/firebase-ios-sdk#5663]
### Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.24.0
  * Firebase Component: In-App Messaging
  * Component version: 0.20.0
  * Installation method: CocoaPods (1.9.1) and Rome (1.0.1)

### Step 2: Describe the problem
When following the steps in the [Rome setup](https://github.com/firebase/firebase-ios-sdk/blob/master/Rome.md) instructions, then the bundle does not exist in `Rome/FirebaseInAppMessaging.framework/InAppMessagingDisplayResources.bundle`.
No bundle is created.

NOTE: If I use CocoaPods 1.6.2, then the bundle is created properly.

#### Steps to reproduce:
Run `bundle exec pod install` with the Podfile listed below. No bundle is created in the `FirebaseInAppMessaging.framework`. Without the bundle, the app is not able to use the framework.

#### Relevant Code:

Podfile
```
platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

# ------------------------- COCOAPODS ROME PLUGIN -------------------------

plugin 'cocoapods-rome', {
    dsym: false,
    configuration: 'Release'
}

# ------------------------- CUSTOM PODS IMPORT -------------------------

def Firebase_pod(version)
    pod 'Firebase/Core', version
    pod 'Firebase/InAppMessaging', version
end

# ------------------------- TARGET -------------------------

target '{PROJECT_NAME}' do
  Firebase_pod('6.24.0')
end
```

Gemfile

```
gem 'cocoapods', '1.9.1'
gem 'cocoapods-rome', '1.0.1'
```

**Comment by paulb777** [comment]
@laurenmarshallVS Thanks for the report. We'll take a deeper look in the next week or two. In the meantime, a workaround would be installing `InAppMessagingDisplayResources.bundle` via one of the other Firebase installation methods and manually adding it to the Xcode project.

**Comment by paulb777** [comment]
Please try adding the files in `Pods/FirebaseInAppMessaging/FirebaseInAppMessaging/Resources` to the Xcode project and target.

**Comment by laurenmarshallVS** [comment]
@paulb777 What more information do you need?

**Comment by paulb777** [comment]
@laurenmarshallVS Does adding the files in Pods/FirebaseInAppMessaging/FirebaseInAppMessaging/Resources to the Xcode project and target fix the build?

**Comment by laurenmarshallVS** [comment]
It does not because it's looking for a bundle.

**Comment by laurenmarshallVS** [comment]
Also, when I manually made my own bundle out of the resources, it would crash the app.

**Comment by paulb777** [comment]
OK thanks. I've reopened for investigation.

**Comment by christibbs** [comment]
Investigating... will follow up this week.

**Comment by christibbs** [comment]
Still looking into this, @laurenmarshallVS. Personally I'm having other issues with Rome setup as well. I'll update the instructions after resolving this.

**Comment by paulb777** [comment]
Is this still an issue?  With the emphasis on adding Swift Package Manager support, we're not investing too much in atypical package managers like Rome.

**Comment by laurenmarshallVS** [comment]
@paulb777 I haven't tried again since we decided to drop attempting to use FirebaseInAppMessaging in our application. It doesn't mean that it's still not a problem in general though. It would need to be fixed if you are supporting Rome, but if you are dropping support for Rome, then it wouldn't matter.

**Comment by paulb777** [comment]
OK thanks. We'll leave this open for now, but at a low priority.

**Comment by yinzara** [comment]
This definitely still needs attention and I don't think is related to Rome as I'm not even using it. 

I'm having this problem when using this with the cordova-plugin-firebase-inappmessaging@4.0.0 which is including Firebase/InAppMessaging ~> 7.0.0 pod.

There is also a corresponding bug in cordova-plugin-firebasex that seems identical (though I don't use that plugin):
https://github.com/dpa99c/cordova-plugin-firebasex/issues/326

There is no known work around that I can find.

I've also opened this issue with that plugin:
https://github.com/chemerisuk/cordova-plugin-firebase-inappmessaging/issues/15

```
PhaseScriptExecution [CP]\ Copy\ Pods\ Resources /Users/yinzara/Library/Developer/Xcode/DerivedData/1ST-grxrjkrkjhmnifeyevheojlmoinj/Build/Intermediates.noindex/ArchiveIntermediates/1ST/IntermediateBuildFilesPath/1ST.build/Debug-iphoneos/1ST.build/Script-79BB01CF8D01C621EE3F9B46.sh (in target '1ST' from project '1ST')
    cd /Users/yinzara/tsg/1st/client/1stbet-cordova/platforms/ios
    /bin/sh -c /Users/yinzara/Library/Developer/Xcode/DerivedData/1ST-grxrjkrkjhmnifeyevheojlmoinj/Build/Intermediates.noindex/ArchiveIntermediates/1ST/IntermediateBuildFilesPath/1ST.build/Debug-iphoneos/1ST.build/Script-79BB01CF8D01C621EE3F9B46.sh
error: Resource "/Users/yinzara/Library/Developer/Xcode/DerivedData/1ST-grxrjkrkjhmnifeyevheojlmoinj/Build/Intermediates.noindex/ArchiveIntermediates/1ST/BuildProductsPath/Debug-iphoneos/FirebaseInAppMessaging/InAppMessagingDisplayResources.bundle" not found. Run 'pod install' to update the copy resources script.

** ARCHIVE FAILED **


The following build commands failed:
        PhaseScriptExecution [CP]\ Copy\ Pods\ Resources /Users/yinzara/Library/Developer/Xcode/DerivedData/1ST-grxrjkrkjhmnifeyevheojlmoinj/Build/Intermediates.noindex/ArchiveIntermediates/1ST/IntermediateBuildFilesPath/1ST.build/Debug-iphoneos/1ST.build/Script-79BB01CF8D01C621EE3F9B46.sh
(1 failure)
```

**Comment by paulb777** [comment]
Closing for staleness. Rome is not a priority for us.
