### ISSUE TITLE
Carthage 6.24.0 misses PromisesObjC and FirebaseInstallations

### ISSUE THREAD

**Issue by choli** [firebase/firebase-ios-sdk#5664]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.24.0
  * Firebase Component: Core and Crashlytics (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 6.24.0
  * Installation method: Carthage

### [REQUIRED] Step 2: Describe the problem

When I installed Crashlytics through carthage Xcode showed me that FirebaseInstallations and PromisesObjC are missing. When downgrading to 6.23.0 this was not an issue anymore. Could it be that there was an issue when packaging FirebaseAnalyticsBinary?

#### Steps to reproduce:

carthage update FirebaseAnalyticsBinary and FirebaseCrashlyticsBinary

#### Relevant Code:

Cartfile:
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" == 6.24.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashlyticsBinary.json" == 6.24.0
```

**Comment by paulb777** [comment]
When downloading the https://dl.google.com/dl/firebase/ios/carthage/6.24.0/FirebaseAnalytics-20b215aa02a6bef3.zip specified in the json, I see both PromisesObjC.framework and FirebaseInstallations.framework.

Please check to make sure they were added to the Xcode project and build target

![Screen Shot 2020-05-21 at 9 36 05 AM](https://user-images.githubusercontent.com/73870/82582265-a4049080-9b46-11ea-846a-524fd6b5e6d3.png)

**Comment by choli** [comment]
Your are right, my bad, might have been some caching problems, as i used 6.9.0 first, when i checked for the newest sdk, and the json is sorted alphabetically. sorry, i'll close the issue
