### ISSUE TITLE
FR: Adds SDK Version call for frameworks (e.g. Crashlytics)

### ISSUE THREAD

**Issue by choli** [firebase/firebase-ios-sdk#5670]
### Feature proposal

* Firebase Component: Crashlytics (and for all others interesting as well maybe)

In our app we show all our third party dependencies with its version numbers. I don't find any possibility to get the FirebaseCrashlytics version number programmatically. It would be good for us to have something like `Crashlytics.crashlytics().sdkVersion` to not having to adapt this every time.

We include our dependencies with Carthage. Another approach we use sometimes is getting the version number from the Info.plist inside the framework. Unfortunately there is always version 6.0, even though 4.1.0 is the current crashlytics version. 

Edit: The AdMob Framework has this included: `GADRequest.sdkVersion()`

**Comment by morganchen12** [comment]
This is fixed in #6651 and will be available with the Firebase 7 major release.
