### ISSUE TITLE
iOS 10: APM random crash 

### ISSUE THREAD

**Issue by mouness2020** [firebase/firebase-ios-sdk#5671]
* Xcode version: 11.4.1
  * Firebase SDK version: 6.25.0
  * Firebase Component: i don't know i think analytics or firebase performance
  * Component version: 6.25.0
  * Installation method: `CocoaPods` 

What happened? How can we make the problem occur?
after updated the sdk i received random crashes happen in iOS 10 only.
the crash happen with any class or library  begin with APM  (see attached image)
it's seems this APM no longer support iOS 10.

![Screenshot at May 23 00-24-43](https://user-images.githubusercontent.com/4884141/82710828-85a8ad00-9c8c-11ea-817b-b9136cb2e829.png)

![Screenshot at May 23 00-29-32](https://user-images.githubusercontent.com/4884141/82710839-893c3400-9c8c-11ea-9d47-12e2245e9a12.png)

![Screenshot at May 23 00-28-02](https://user-images.githubusercontent.com/4884141/82710835-87727080-9c8c-11ea-8691-58552ae4ef30.png)

**Comment by paulb777** [comment]
@mouness2020 This looks like a variation of #5233 and other issues. The workaround is to use Xcode 11.3 or Xcode 11.5
