### ISSUE TITLE
gRPC-Core using 'pod install' is freeze

### ISSUE THREAD

**Issue by CarlosLadd** [firebase/firebase-ios-sdk#5672]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.24.0
  * Firebase Component: Firestore
  * Component version: 1.13.0
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

Using the pod install in a new project the 'gRPC-Core (1.28.0)' is freeze. I was waiting about two hours and the installation not done

#### Steps to reproduce:

What happened? How can we make the problem occur?
Installing BoringSSL-GRPC (0.0.7)
Installing Firebase (6.24.0)
Installing FirebaseAnalytics (6.5.0)
Installing FirebaseAuth (6.5.3)
Installing FirebaseAuthInterop (1.1.0)
Installing FirebaseCore (6.7.0)
Installing FirebaseCoreDiagnostics (1.3.0)
Installing FirebaseCoreDiagnosticsInterop (1.2.0)
Installing FirebaseFirestore (1.13.0)
Installing FirebaseInstallations (1.2.0)
Installing GTMSessionFetcher (1.4.0)
Installing GoogleAppMeasurement (6.5.0)
Installing GoogleDataTransport (6.1.0)
Installing GoogleDataTransportCCTSupport (3.1.0)
Installing GoogleUtilities (6.6.0)
Installing MDFInternationalization (2.0.0)
Installing MDFTextAccessibility (2.0.0)
Installing MaterialComponents (109.3.1)
Installing PromisesObjC (1.2.8)
Installing Realm (5.0.0)
Installing RealmSwift (5.0.0)
Installing abseil (0.20200225.0)
Installing gRPC-C++ (1.28.0)
Installing gRPC-Core (1.28.0) // this freeze ... zzz

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by dconeybe** [comment]
Hi @CarlosLadd. I'm sorry that you have run into this issue. Would you be able to create a sample project in a GitHub repository that I could clone to attempt to reproduce? Also, please let me know exactly what commands you ran in the repository to cause the issue to occur.

**Comment by CarlosLadd** [comment]
I have pod version 1.9.2:
1. Create a new blank Xcode project.
2. Navigate on terminal to the folder project and run 'pod init' to initialize the pod on the project
3. After I open the Podfile and I have these frameworks:
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'MaterialComponents/TextFields'
  pod 'RealmSwift'
4. I run 'pod install' and the terminal shows:
Installing BoringSSL-GRPC (0.0.7)
Installing Firebase (6.24.0)
Installing FirebaseAnalytics (6.5.0)
Installing FirebaseAuth (6.5.3)
Installing FirebaseAuthInterop (1.1.0)
Installing FirebaseCore (6.7.0)
Installing FirebaseCoreDiagnostics (1.3.0)
Installing FirebaseCoreDiagnosticsInterop (1.2.0)
Installing FirebaseFirestore (1.13.0)
Installing FirebaseInstallations (1.2.0)
Installing GTMSessionFetcher (1.4.0)
Installing GoogleAppMeasurement (6.5.0)
Installing GoogleDataTransport (6.1.0)
Installing GoogleDataTransportCCTSupport (3.1.0)
Installing GoogleUtilities (6.6.0)
Installing MDFInternationalization (2.0.0)
Installing MDFTextAccessibility (2.0.0)
Installing MaterialComponents (109.3.1)
Installing PromisesObjC (1.2.8)
Installing Realm (5.0.0)
Installing RealmSwift (5.0.0)
Installing abseil (0.20200225.0)
Installing gRPC-C++ (1.28.0)
Installing gRPC-Core (1.28.0)

so, after waiting about two hours the 'Installing gRPC-Core (1.28.0)' is freeze and not continue to installing, I have 100mb of internet connection and I have other project with Firestore but with an old version, I try to upgrade and the same error occur with news and old projects.

**Comment by paulb777** [comment]
The output of `pod install --verbose` may help to diagnose.

**Comment by CarlosLadd** [comment]
This is the log: https://pastebin.com/au2inP4S
But today I restart my computer and router, so after that the installation is completed.
Thank you for your help.

**Comment by frederic-gendebien** [comment]
I ran into the same problem! What do I have to do to resolve this annoying thing?

**Comment by var-const** [comment]
@frederic-gendebien Can you please post the output of `pod install --verbose`?
