### ISSUE TITLE
FR:About write data

### ISSUE THREAD

**Issue by SuperSG** [firebase/firebase-ios-sdk#5674]
### [READ] Guidelines

When filing a feature request please make sure the issue title starts with "FR:".

A good feature request ideally
* is either immediately obvious (i.e. "Add Sign in with Apple support"), or
* starts with a use case that is not achievable with the existing Firebase API and
  includes an API proposal that would make the use case possible. The proposed API
  change does not need to be very specific.

Once you've read this section, please delete it and fill out the rest of the template.

### Feature proposal

* Firebase Component: Storage (Auth, Core, Database, Firestore, Messaging, Storage, etc)

Why convert utf8 to hex to write to the buffer

**Comment by ryanwilson** [comment]
Hi @SuperSG - can you please link to the code you're referring to where this is happening, along with any use-cases you have that can help explain the request?

Thanks!

**Comment by SuperSG** [comment]
> Hi @SuperSG - can you please link to the code you're referring to where this is happening, along with any use-cases you have that can help explain the request?
> 
> Thanks!

static void FIRCLSUserLoggingWriteKeyValue(NSString *key,
                                           NSString *value,
                                           FIRCLSUserLoggingKVStorage *storage,
                                           uint32_t *counter) {
  FIRCLSFile file;

  if (!FIRCLSIsValidPointer(storage) || !FIRCLSIsValidPointer(counter)) {
    FIRCLSSDKLogError("Bad parameters\n");
    return;
  }

  if (!FIRCLSFileInitWithPath(&file, storage->incrementalPath, true)) {
    FIRCLSSDKLogError("Unable to open k-v file\n");
    return;
  }

  FIRCLSFileWriteSectionStart(&file, "kv");
  FIRCLSFileWriteHashStart(&file);
  FIRCLSFileWriteHashEntryHexEncodedString(&file, "key", [key UTF8String]);
  FIRCLSFileWriteHashEntryHexEncodedString(&file, "value", [value UTF8String]);
  FIRCLSFileWriteHashEnd(&file);
  FIRCLSFileWriteSectionEnd(&file);

  FIRCLSFileClose(&file);

  *counter += 1;
  if (*counter >= storage->maxIncrementalCount) {
    dispatch_async(FIRCLSGetLoggingQueue(), ^{
      FIRCLSUserLoggingCompactKVEntries(storage);
      *counter = 0;
    });
  }
}

Why call FIRCLSFileWriteHashEntryHexEncodedString convert utf8 to hex

**Comment by ryanwilson** [comment]
Thanks for linking the code - since this is an implementation detail and not a feature request or bug report, I'm going to close the issue but we can continue the conversation. If you're running into a bug because of this please fill out the bug report template.

I don't have enough context as to why this decision made, but @samedson could potentially have some context.

@samedson do you have any insight here?

Note for @SuperSG: it's a holiday in the US today so there likely won't be a response right away.

**Comment by SuperSG** [comment]
> Thanks for linking the code - since this is an implementation detail and not a feature request or bug report, I'm going to close the issue but we can continue the conversation. If you're running into a bug because of this please fill out the bug report template.
> 
> I don't have enough context as to why this decision made, but @samedson could potentially have some context.
> 
> @samedson do you have any insight here?
> 
> Note for @SuperSG: it's a holiday in the US today so there likely won't be a response right away.

Could you please tell me here why you need to convert utf8 to hex @samedson

**Comment by samedson** [comment]
Hey @SuperSG this was just a decision made early on in the SDK's lifetime to serialize keys and values via hex. I believe at the time it made the server implementation easier, but I don't remember the details exactly.
