### ISSUE TITLE
Unlinked email can still be used for authentication

### ISSUE THREAD

**Issue by vin047** [firebase/firebase-ios-sdk#5676]
### Step 0: Are you in the right place?
Yes

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.25.0
  * Firebase Component: Auth
  * Component version: 6.5.3
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem
Despite unlinking an email from a user, the email still authenticates for the same user. After unlinking, I'd expect signing in with the same email to generate a new user in firebase. Using email link login (passwordless) both for initial linking and subsequent sign in.

#### Steps to reproduce:
Using email link authentication (passwordless):
1. link email E to user A
2. unlink email E from user A
3. Sign in with email E

Expected: Creates new user B with email E
Actual: Signs in to existing user A

The only way to prevent this is to overwrite the email for user A by linking a new email F. Alternatively, according to https://github.com/firebase/firebase-ios-sdk/issues/3858#issuecomment-532002294, I should be able to call `updateEmail` and set it to nil but the SDK only allows a String value as the parameter, not optional. Attempting to set to empty String `""` throws error that the email is invalid.

#### Relevant code:
```swift
// link
let credential = EmailAuthProvider.credential(withEmail: email, link: verificationLink)
Auth.auth().currentUser!.link(with: credential) { (authResult, error) in
  ...
}

// later, unlink
Auth.auth().currentUser!.unlink(fromProvider: EmailAuthProviderID) { _, error in
  ...
}

// on fresh app install, sign in with the unlinked email from before
Auth.auth().sendSignInLink(toEmail: email, actionCodeSettings: actionCodeSettings) { error in
  ...
}

// complete sign in flow with the unlinked email from before
Auth.auth().signIn(withEmail: email, link: verificationLink) { (authResult, error) in
  ...
}
```

**Comment by rizafran** [comment]
Hi @vin047, apologies for not getting back to you on this issue. We appreciate the feedback and should have responded earlier. I'm currently taking a look on it, but I just want to clarify your reproducible steps so I could move forward with the replication using the latest SDK version. That being said, could you clarify if you're linking email E (email link auth) to user A (new email/password account) or you're using both email link auth?

**Comment by rizafran** [comment]
Closing this ticket for now until further details are provided.
