### ISSUE TITLE
Thrown exception in [FLevelDBStorageEngine runMigration]

### ISSUE THREAD

**Issue by gapl** [firebase/firebase-ios-sdk#5686]
### Environment

  * Xcode version: v11.4.1
  * Firebase SDK version: v6.24.0
  * Firebase Component: Database
  * Component version: v6.24.0
  * Installation method: `Carthage`

### Exception

We're seeing the following exception raised in our Crashlytics reporting.

We're aware that this issue has been raised a couple of times ([#4471](https://github.com/firebase/firebase-ios-sdk/issues/4471), [#1171](https://github.com/firebase/firebase-ios-sdk/issues/1171)), but they've been simply closed due to lack of additional information. We're happy to provide any additional information that might help. The crash is occurring since we added the Database dependency to the project. Users experiencing the crash are on non-jailbroken devices and are experiencing the crash in foreground.

These are not new users, but users who have updated from the previous version of the app that did not include Firebase Database, it did however include other components from Firebase.

```
Fatal Exception: NSInternalInconsistencyException
Unrecognized database version:

0  CoreFoundation                 0x1bfcb0794 (Missing)
1  libobjc.A.dylib                0x1bf9d2bcc (Missing)
2  CoreFoundation                 0x1bfba6b98 (Missing)
3  AppName                        0x10481cd5c -[FLevelDBStorageEngine runMigration]
4  AppName                        0x10481cc48 -[FLevelDBStorageEngine initWithPath:]
5  AppName                        0x1048362d4 -[FRepo deferredInit]
6  libdispatch.dylib              0x1bf9759a8 (Missing)
7  libdispatch.dylib              0x1bf976524 (Missing)
8  libdispatch.dylib              0x1bf9228a4 (Missing)
9  libdispatch.dylib              0x1bf923294 (Missing)
10 libdispatch.dylib              0x1bf92c78c (Missing)
11 libsystem_pthread.dylib        0x1bf9c7b74 (Missing)
12 libsystem_pthread.dylib        0x1bf9ca740 (Missing)
```

**Comment by schmidt-sebastian** [comment]
@gapl Thanks for filing this. Based on your error message, the "version" file is empty. This is a special file that the SDK uses to denote the database schema version. This file sometimes shows up in iCloud Drive and may have been edited by the user.

To mitigate the crash, I will add an exception to ignore empty version files.
