### ISSUE TITLE
Reached max OAuth Clients of iOS Project

### ISSUE THREAD

**Issue by stherold** [firebase/firebase-ios-sdk#5699]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.5
  * Firebase SDK version: 6.24
  * Firebase Component: Core / All
  * Component version: 
  * Installation method: Carthage

#### Steps to reproduce:

We use one Firebase project and have many iOS apps in it. We now reached the limit of OAuth Clients for that project since Firebase creates one per app in contrast to Android which has only one in the whole project. The OAuth Client Id is created in [GoogleCloudPlatform Credentials](https://console.cloud.google.com/apis/credentials) site and referenced in the Google-Services-Info.plist via the key `CLIENT_ID`. We had 30 IDs since the IDs of apps we already deleted from Firebase where not deleted on [GCP](https://console.cloud.google.com/apis/credentials).

My question is what this is actually for and what would happen if we delete the OAuth-Client ID?

**Comment by morganchen12** [comment]
In the future, these kinds of questions (non-SDK, console-only) should be directed to Firebase Support.

Maybe @MeghaB knows the answer?

**Comment by stherold** [comment]
Yeah we tried to contact the support first but this was maybe too technical. Thats why we try to formulate our concrete questions here.

**Comment by morganchen12** [comment]
Noted, can you provide me the support case number? You shouldn't have to worry about support cases being too technical; in that case the support staff will escalate those cases to the SDK team here anyway.

The reason I mentioned these cases should go through support is because we can much more easily look at your Firebase project with an open support case than we can through GitHub issues.

**Comment by Blackjacx** [comment]
So here we go: 
`Case 00060698: Adding App - Resource has been exhausted [ ref:_00D1Ux0Jq._5003p2PBZhZ:ref ]`

**Comment by morganchen12** [comment]
I wasn't able to find a satisfying answer from my relatively shallow digging around. If more people run into this, I'll re-open the issue and investigate further.

**Comment by stherold** [comment]
It was because deleting the Firebase app didn't delete the oAuth client from Google Cloud Platform. After purging them I was able to create a new FB app.
