### ISSUE TITLE
Upload file failed: Error Domain=NSPOSIXErrorDomain Code=100 "Protocol error"

### ISSUE THREAD

**Issue by thomasdao** [firebase/firebase-ios-sdk#5720]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 11.5 (11E608c)
  * Firebase SDK version: Version 6.25.0
  * Firebase Component: Auth, Core, Firestore, Storage, Functions
  * Component version: complete Pod.lock file is at https://drive.google.com/file/d/1GIz_tK5zr67hTvBz1dpSUJ7f6c1sj0A-/view?usp=sharing
  * Installation method: CocoaPods
  * My iPhone: iPhone 7, iOS 13.4.1

#### Steps to reproduce:
My app let user picks a file from UIDocumentPickerViewController and upload to Firebase storage. However:
- If I picked images, `.txt` or `.json` files, they can be uploaded successfully to Firebase Storage
- If I selected a custom file like `Home Improvement.numbers` file from `iCloud Drive/Numbers` folder, the upload failed with below error. This happened with other extensions like `.noto`.

Task <B5FBCC04-CBF6-49BB-9D6F-D8B0BA153D1B>.<1> finished with error [100] Error Domain=NSPOSIXErrorDomain Code=100 "Protocol error" UserInfo={_NSURLErrorFailingURLSessionTaskErrorKey=BackgroundUploadTask <B5FBCC04-CBF6-49BB-9D6F-D8B0BA153D1B>.<1>, _kCFStreamErrorDomainKey=1, NSErrorPeerAddressKey={length = 28, bytes = 0x1c1e01bb 00000000 24046800 40050801 ... 0000200a 00000000 }, _kCFStreamErrorCodeKey=100, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "BackgroundUploadTask <B5FBCC04-CBF6-49BB-9D6F-D8B0BA153D1B>.<1>",
    "LocalUploadTask <B5FBCC04-CBF6-49BB-9D6F-D8B0BA153D1B>.<1>"
)}

#### Relevant Code:
Pick file from UIDocumentPickerViewController:
```swift
    func pickFile() {
        let filePicker = UIDocumentPickerViewController(documentTypes: ["public.item"], in: .import)
        filePicker.allowsMultipleSelection = false
        filePicker.delegate = self
        present(filePicker, animated: true)
    }
```

Upload file to Firebase storage
```swift
    static func uploadFile(file: FileMeta) -> StorageUploadTask? {
        // Check if user is authenticated
        guard let currentUser = Auth.auth().currentUser else {
            return nil
        }
        // Check if the file exists
        let fileUrl = getLocalFileUrl(fileId: file.id)
        if !FileManager.default.fileExists(atPath: fileUrl.path) {
            return nil
        }
        // Check if existing file is being uploaded
        if let uploadTask = uploadTasks[file.id] {
            return uploadTask
        }
        // Upload file
        let imageRef = Storage.storage().reference(withPath: "users/\(currentUser.uid)/\(file.id)")
        let uploadTask = imageRef.putFile(from: fileUrl, metadata: nil) { (_, error) in
            // Mark current task had finished
            uploadTasks.removeValue(forKey: file.id)
            if error == nil {
                // Keep track of downloaded URL
                imageRef.downloadURL(completion: { (url, err) in
                    if err != nil {
                        print("downloadURL error", err!)
                        return
                    }
                    print("downloadURL", url!.absoluteString)
                    file.downloadURL = url!.absoluteString
                    try? DataStore.shared.saveFile(file)
                })
            }
        }
        
        // Keep track of running tasks
        uploadTasks[file.id] = uploadTask
        return uploadTask
    }
```

**Comment by maksymmalyhin** [comment]
@thomasdao Thank you for reporting the issue. 

According to the [docs](https://developer.apple.com/documentation/uikit/uidocumentpickerdelegate/2902364-documentpicker) `UIDocumentPickerViewController` in import mode provides URLs to temporary files that may become unavailable to your application. The error may occur when the file may become unavailable during the upload process for some reason. Could you please check if the file by  `fileUrl` is still accessible after the failure occurs. If it is not, please consider copying the file to a directory within you application sandbox before uploading to make sure its accessibility until the end of the process.

Please let us know the results.

**Comment by thomasdao** [comment]
Hi @maksymmalyhin I called `try fileManager.moveItem(at: tempURL, to: fileURL)` to move the temporary file into a folder in `documentDirectory`. As I mentioned, the upload works fine with image/json/text file, but other files like `.numbers` or `.noto` files always failed. I also checked the file in the internal folder, it exists when the file is uploaded

**Comment by thomasdao** [comment]
@maksymmalyhin I can reproduce this issue with a small sample code at https://github.com/thomasdao/TestFirebaseUpload

To run this sample code, first supply your own `GoogleService-Info.plist` file in `TestUpload` folder. Since this sample do not use authentication, please modify the Firebase storage security rules to allow public upload. As you can see in the sample, upload image is successful but `.numbers` file is failed

**Comment by ncooke3** [comment]
Hi @thomasdao ,

Thank you for the sample app! One important thing to note (that I just found out myself!) is `.numbers` files are actually directories. Try printing `fileURL.path` [here](https://github.com/thomasdao/TestFirebaseUpload/blob/a8907313e361d97568198ffef9f88f00a4535574/TestUpload/ViewController.swift#L38) and notice the trailing `/` at the end of the filePath. I believe this is also true for other Apple files like `pages`. Confusing indeed!

With this in mind, the error likely comes from trying to upload a directory when the `putFile` method expects a file.  Regardless, the error isn't very clear here so we will work on making it fail gracefully with a clearer message when the file URL provided links to a directory. I will attempt to create and provide a work around for now- one idea would be something like zipping the `.numbers` directory and attempting to upload that.

I hope this was helpful. We will keep you updated!

**Comment by thomasdao** [comment]
Thanks @ncooke3! I hope `putFile` can somehow detect these type of files and upload it transparently, that would be really convenient. Thanks and look forward to the fix :)

**Comment by ncooke3** [comment]
Hi @thomasdao, I'm working on adding some better error messages for this type of issue. In terms of a fix, I would consider looking at zipping a file and uploading that to storage. Currently, Firebase doesn't handle this kind of zipping functionality and uploading directories is not supported. I agree it would be a convenient feature and will bring it up with the team when discussing future product features.

**Comment by paulb777** [comment]
@ncooke @thomasdao If I read this right, the issue was resolved and delivered in Firebase 6.27.0. Let me know if that's not the case and we can reopen.

**Comment by thomasdao** [comment]
Hi @paulb777, the fix in 6.27.0 is about providing better error message. I was hoping that `putFile` can handle upload all types of files, that would be a lot more convenient, instead of the client needs to check for the file, zip it when upload and unzip it when download. Thank you :)

**Comment by paulb777** [comment]
Hi @thomasdao - Ah that makes sense. Would you open another feature request with that description to help us track and manage it separate from the confusing message issue that was addressed here?  It seems like the issue here was the inability to upload directories. Is that the capability you'd like to see added?

**Comment by thomasdao** [comment]
Hi @paulb777 I am only interested in uploading file, but surprisingly file like `.numbers` is not a single file but a packaged directory. So if Firebase can support directories, it would be great. Otherwise since I'm only interested in uploading file, it's also possible to zip the directory when upload and unzip it when download.

Would you prefer open another feature request or just change the title? I can do both. Thanks!

**Comment by paulb777** [comment]
@thomasdao Thanks for clarifying. My preference is opening another feature request now that we've more clearly defined the request.

**Comment by thomasdao** [comment]
@paulb777 I created a new feature request at https://github.com/firebase/firebase-ios-sdk/issues/5869. Thank you.
