### ISSUE TITLE
Dispatch queue: com.google.firebase.auth.globalWorkQueue   Thread crashed.

### ISSUE THREAD

**Issue by Sublustris** [firebase/firebase-ios-sdk#5721]
### Describe your environment

  * Xcode version:  10.1
  * Firebase SDK version: 0.16.0 (firebase_auth for Flutter)
  * Firebase Component: Auth
  * Component version:  firebase_auth: ^0.16.0

### Describe the problem
App is crashing on iPhone and iPad (IOS 13.5 13.5.1) when user is trying to login using existing account

Crash log:
[attachment_1779773927076952969crashlog_DEB8BBA5_31FA_4531_9280_B5402109D7E7.txt](https://github.com/firebase/firebase-ios-sdk/files/4716825/attachment_1779773927076952969crashlog_DEB8BBA5_31FA_4531_9280_B5402109D7E7.txt)

**Comment by ryanwilson** [comment]
Hi, thanks for the report and sorry for the troubles you're seeing.

Can you please symbolicate the crash report? It's going to be impossible to figure out what was going wrong without seeing what methods were called, and even then we're likely going to need some sample code that can reproduce this.

You can find more information about how to symbolicate crashes here: https://developer.apple.com/library/archive/technotes/tn2151/_index.html

Also this could be a flutter specific issue, in which case this should be opened against the flutterfire repo: https://github.com/FirebaseExtended/flutterfire

**Comment by Sublustris** [comment]
Thank you for response. I'll try.
The problem is -this logs are from apple review team, and that is only info i have.
On my own device i cant even reproduse this issue.
But apple team somehow can.
here are the other logs they provided. Problem is the same.
[attachment_1779773927076952969crashlog_DEB8BBA5_31FA_4531_9280_B5402109D7E7.txt](https://github.com/firebase/firebase-ios-sdk/files/4717662/attachment_1779773927076952969crashlog_DEB8BBA5_31FA_4531_9280_B5402109D7E7.txt)
[attachment_14194784670888038541crashlog_FD0DDC66_11FE_4556_9E29.txt](https://github.com/firebase/firebase-ios-sdk/files/4717663/attachment_14194784670888038541crashlog_FD0DDC66_11FE_4556_9E29.txt)
[attachment_4863837703299290265crashlog_A09E97FA_A82B_4674_AA32_9C3FE5C2C648.txt](https://github.com/firebase/firebase-ios-sdk/files/4717664/attachment_4863837703299290265crashlog_A09E97FA_A82B_4674_AA32_9C3FE5C2C648.txt)
[attachment_3367746561920500978crashlog_A4FC5CE9_65BC_454D_981E_75A45101DDCF.txt](https://github.com/firebase/firebase-ios-sdk/files/4717665/attachment_3367746561920500978crashlog_A4FC5CE9_65BC_454D_981E_75A45101DDCF.txt)

**Comment by morganchen12** [comment]
If you have the dSYM files for the build you uploaded to Apple, you should be able to symbolicate the crash log even if the crash was not generated on your machine.

**Comment by Sublustris** [comment]
![Снимок экрана 2020-06-02 в 21 49 48](https://user-images.githubusercontent.com/43444545/83553398-311ef080-a51c-11ea-9594-30376b340aac.png)

**Comment by morganchen12** [comment]
Can you share the exception message as well? It looks like it's probably crashing due to an unrecognized selector exception, which suggests the `request` variable has the wrong type.

**Comment by Sublustris** [comment]
> Can you share the exception message as well? It looks like it's probably crashing due to an unrecognized selector exception, which suggests the `request` variable has the wrong type.

Where can i find it? Sorry for the incompetence, I'm new to ios development.

**Comment by Sublustris** [comment]
![Снимок экрана 2020-06-02 в 22 24 35](https://user-images.githubusercontent.com/43444545/83555811-f028db00-a51f-11ea-85b4-a940e317cde2.png)

**Comment by Sublustris** [comment]
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY

**Comment by morganchen12** [comment]
If you disable all breakpoints and allow program execution to continue, there should be an exception message printed to console if the crash was caused by an exception.

Looking at the screenshot again, this is probably not the result of a thrown exception. Can you reproduce this crash in a project and share it with us?
