### ISSUE TITLE
Protobuf 3.12 causes a clang compilation error on Messaging pod v6.14

### ISSUE THREAD

**Issue by M1ke** [firebase/firebase-ios-sdk#5722]
### Step 1: Describe your environment

  * Xcode version: 10.3
  * Firebase SDK version: 6.14
  * Firebase Component: Messaging
  * Component version: 6.14
  * Installation method: `CocoaPods` (select one)

#### Steps to reproduce:

What happened? How can we make the problem occur?

See https://github.com/protocolbuffers/protobuf/issues/7587 for the full error message.

In short: using Pod 6.14 for Firebase messaging requires Protobuf with definition `Protobuf (>= 3.9.2, ~> 3.9)` which at present requires Protobuf pod `3.12`

The linked Protobuf compilation error above occurs with this version, potentially due to https://github.com/protocolbuffers/protobuf/pull/7026.

The fix is fairly simple; downgrade Protobuf to `3.11.x` which has to be done by hacking one's `Podfile.lock`

Would it be acceptable if I opened a PR to hard limit the Protobuf requirement to max out at `3.11.x` on the `6.14` branch for Messaging?

**Comment by paulb777** [comment]
@M1ke Thanks for the report.

Your proposal seems reasonable if there is a definite issue with 3.12.0.

However, first we'd need to confirm that with a reproducible example. Protobuf 3.12.0 has been out [for two weeks](https://github.com/CocoaPods/Specs/blob/master/Specs/1/4/6/Protobuf-C++/3.12.0/Protobuf-C++.podspec.json). Our testing does not show the problem and we haven't seen any other reports. It's possible you have a stale/corrupt Xcode state or some other environment issue.  Does `rm -rf ~/Library/Developer/Xcode/DerivedData/` make a difference?

Are you able to reproduce in https://github.com/firebase/quickstart-ios/tree/master/messaging?

**Comment by M1ke** [comment]
Thanks for getting back to me. As far as I could see I tried every possible way of clearing my environment:

* Xcode -> Product -> Clean
* Deleted `~/Library/Developer/Xcode/DerivedData`
* Cleared npm cache
* Cleared pods cache
* Deleted local `ios/build` and `ios/pods` directories
* Deleted `Podfile.lock`

The same result happened each time. My only other thought is that it could be happening with one of React Native's autolinked pods, which is quite hard to debug. I'm using the default React Native pods plus:

* rn-fetch-blob
* react-native-calendar-events
* react-native-custom-tabs
* react-native-vector-icons
* react-native-webview
* react-native-image-picker
* react-native-pdf
* react-native-splash-screen
* react-native-device-info
* react-native-async-storage

All of these are autolinked except `react-native-vector-icons` which is linked manually due to the resource font files it imports.

**Comment by paulb777** [comment]
Does the issue still occur with the latest release - 6.26.0?

It might be worth raising this on a react-native channel. Most people here aren't too familiar with that environment.

**Comment by xiao99xiao** [comment]
I got issue with Protobuf 3.12 too, but it's a bit different from @M1ke .
Building can succeed but app runs into the error below at start (on an iOS device)
```
dyld: Library not loaded: @rpath/Protobuf.framework/Protobuf
  Referenced from: /private/var/containers/Bundle/Application/A3DA9078-142C-4132-8AB4-D80902130D69/AppName.app/AppName
  Reason: image not found
```
Clearing cache does not help.
Downgrading to 3.11.x fixes it.

Environment:
Xcode 11.5, macOS 10.15.1, React Native 0.62.2, Firebase 6.25/6.26

**Comment by paulb777** [comment]
@xiao99xiao That issue sounds more like something caused by stale or corrupt Xcode state.

**Comment by morganchen12** [comment]
@xiao99xiao check your runtime search paths and make sure that Protobuf's build location is discoverable.

**Comment by danigv** [comment]
I'm having the same issue as @M1ke . Tried with this environment:

- Xcode version: 10.1
- Firebase Component: Messaging
- Component version: tried with 6.11 and 6.13
- Installation method: CocoaPods

I get the error when trying to archive, building and running are working ok. This is the error message:

> Clang frontend command failed with exit code 70

The problem seems to be in Protobuf 3.12.

The only quick-fix is manually editing Podfile.lock?

**Comment by paulb777** [comment]
@danigv Recent versions of Firebase require at least Xcode 10.3.

It should never be necessary to edit the Podfile.lock versus specifying constraints in the Podfile like `pod 'Protobuf', '< 3.12.0'`

**Comment by xiao99xiao** [comment]
@paulb777 @morganchen12 
Thanks fo reply. I'm using all default settings by cocoapods, and with my project, this issue could be replicate on multiple Macs.

One thing I noticed is, if I target at simulators, everything is ok, app starts properly, but if I target at a real iPhone, app runs into error at start.

I doubt maybe Protobuf fails to build but Xcode doesn't recognized that issue. Guess I need to check the build destination directory to see if Protobuf framework is there.

**Comment by paulb777** [comment]
We're likely going to need a reproducible test case to make progress on this issue.
