### ISSUE TITLE
Lot of problems after recent update 

### ISSUE THREAD

**Issue by Kanishka3** [firebase/firebase-ios-sdk#5729]
### Environment

  * Xcode version: 11.4.1
  * Firebase SDK version: 6.25.0
  * Firebase Component: gRPC core
  * Component version: 1.28.2
  * Installation method: CocoaPods

#### Steps to reproduce:
I updated the Firebase framework. Everything was working fine before the update. Now, I am getting like 6 problems in my pods/gRPC-Core. Four of the error says: 
`Unknown type name 'grpc_pollset_set'`
Other two error says: 
`No matching member function for call to 'Unref'`
I tried reinstalling Firebase pod but it didnt worked.

**Comment by morganchen12** [comment]
Hey @Kanishka3, are you able to share a project that reproduces this build issue? Can you also provide your CocoaPods version?

**Comment by paulb777** [comment]
There might be corrupt/stale Xcode state for the project. Try ` rm -rf ~/Library/Developer/Xcode/DerivedData/`

**Comment by Kanishka3** [comment]
@morganchen12 My current Cocoapods version is: cocoapods-1.9.0.beta.2

**Comment by Kanishka3** [comment]
The issue does not seems irreproducible since I don't know the reason this is happening. I updating the Firebase version and built the project, and their were bunch of error in Pod/gRPC-Core 

Would love to get some help! 🙏

**Comment by Kanishka3** [comment]
@paulb777 I just updated the Cocoapods version to the latest and now it's working totally fine 👍 

Thanks for the help :)
