### ISSUE TITLE
Firebase authentication issue - An internal error has occurred, print and inspect the error details for more information

### ISSUE THREAD

**Issue by qldinfotechs** [firebase/firebase-ios-sdk#5730]
I have used Firebase authentication to receive an OTP for the verification of the user. For that, I have used following method,

```
PhoneAuthProvider.provider().verifyPhoneNumber(phoneNumber, uiDelegate: nil) { (verificationID, error) in
      if let error = error {
        showAlert(error.localizedDescription)
        return
      }

      print(verificationID)
    }
```

Now, the issue is whenever we test release build from test flight in our devices, we are successfully authenticated but when we submit same build for the review team of Apple, they are facing following error,

`An internal error has occurred, print and inspect the error details for more information.`

Kindly help me how to regenerate above issue from my side, and solve it.

**Comment by paulb777** [comment]
See also https://stackoverflow.com/questions/62158892/firebase-authentication-issue-an-internal-error-has-occurred-print-and-inspec

**Comment by qldinfotechs** [comment]
> See also https://stackoverflow.com/questions/62158892/firebase-authentication-issue-an-internal-error-has-occurred-print-and-inspec

that has been posted by me.

**Comment by qldinfotechs** [comment]
I am not getting the error, we have tested a Test Flight build on multiple devices, on all devices it works fine but Apple testing team is getting the issue.

**Comment by morganchen12** [comment]
Unfortunately it will be difficult for the team to make progress without either the full error message or a way to reproduce the error.
