### ISSUE TITLE
[Firebase/Crashlytics][I-CLS000000] Failed to download settings Error 

### ISSUE THREAD

**Issue by zhouheAragon** [firebase/firebase-ios-sdk#5732]
Describe your environment

Xcode version: 11.5
Firebase SDK version: 6.15.0
Firebase Component: [Firebase/Crashlytics]
Component version:=Version 4.1.0
Describe the problem

6.15.0 - [Firebase/Crashlytics][I-CLS000000] Failed to download settings Error Domain=FIRCLSNetworkError Code=-6 "(null)" UserInfo={retryLimit=1, NSErrorFailingURLStringKey=https://firebase-settings.crashlytics.com/spi/v2/platforms/mac/gmp/x3/settings?build_version=5&display_version=6.1.2&instance=xxxxxxxxx&source=1}

The firebase project is not correctly initialized. I'm not seeing the Crashlytics console, but the setup screen. 

Steps to reproduce:

Run the  app on iOS and [FIRApp configure] which produces the error.

**Comment by ryanwilson** [comment]
Hi,

Is this an issue with Catalyst? If so, it's worth following along in #4690 to get Keychain sharing enabled. See https://github.com/firebase/firebase-ios-sdk/issues/4690#issuecomment-583514820 for more information as well.

It's also worth checking if there's a VPN / Adblocker / Pi-Hole that's refusing the connection.

Thanks
