### ISSUE TITLE
Latest versions have not been published to Carthage

### ISSUE THREAD

**Issue by sebskuse** [firebase/firebase-ios-sdk#5733]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 11.5 (11E608c)
  * Firebase SDK version: 6.24.0
  * Firebase Component: All
  * Component version: 6.24.0
  * Installation method: `Carthage`

#### Steps to reproduce:

- Run `carthage outdated` where `Cartfile.resolved` lists Firebase dependencies at `6.24.0`
- No updates are shown.

No versions of Firebase past 6.24.0 have been published to the Carthage json feed

**Comment by ryanwilson** [comment]
Thanks for the report and sorry for the trouble - we're running into some issues with our Carthage publishing tools but hope to get that resolved shortly. I'll leave this open until we get the latest version shipped.

**Comment by ryanwilson** [comment]
6.26.0 was just published this morning. Thanks for your patience!
