### ISSUE TITLE
Crash in FIRMessagingRmqManager.m on iOS 12

### ISSUE THREAD

**Issue by ricardohochman** [firebase/firebase-ios-sdk#5739]
### Step 1: Describe your environment

  * Xcode version: 11.5
  * Firebase SDK version: 6.26.0
  * Firebase Component: Messaging (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 6.26.0
  * Installation method: CocoaPods

#### Steps to reproduce:
Got a crash when opening the app on devices running iOS 12.X.X.
#### Relevant Code:

Crash in crashlytics:
```
FIRMessagingRmqManager.m - Line 534
-[FIRMessagingRmqManager createTableWithName:command:] + 534
```
<img width="829" alt="image" src="https://user-images.githubusercontent.com/10833188/83684383-51eb5280-a5bd-11ea-9214-065355dda6f8.png">

On version 6.25.0 of Firebase the app didn't crash, only on version 6.26.0.

**Comment by chliangGoogle** [comment]
@ricardohochman Are you sure it's only crashing in v 6.26.0? We haven't released a new version of messaging from 6.25.0 to 6.26.0.

**Comment by ricardohochman** [comment]
@chliangGoogle I'm not perfectly sure if the crash is only on 6.26.0, but it didn't exist before. It happened after I updated the pods

<img width="719" alt="image" src="https://user-images.githubusercontent.com/10833188/83687431-228b1480-a5c2-11ea-9308-a84c025fb197.png">

**Comment by ricardohochman** [comment]
And I'm also not sure if the crash is on Messaging, I only guessed because of the class that crashed: FIRMessagingRmqManager.m - Line 534

**Comment by paulb777** [comment]
@ricardohochman Are you able to reproduce locally?  Does the crash still occur if you remove other Firebase pods like Analytics and Crashlytics?

**Comment by ricardohochman** [comment]
Unfortunately no, I tried to download the same simulator that the crash occurred, but the app opened without a problem.

**Comment by ricardohochman** [comment]
Hi, we discover that this crash was happening because of the obfuscation that we're using on our application, so it wasn't a problem due to Firebase, I'm sorry for the wrong assignee. Thanks anyway.

**Comment by paulb777** [comment]
@ricardohochman Glad you resolved it and thanks for letting us know!
