### ISSUE TITLE
FirebaseInAppMessaging doesn't work.

### ISSUE THREAD

**Issue by yaminoma** [firebase/firebase-ios-sdk#5745]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.5
  * Firebase SDK version: 6.26.0
  * Firebase Component: In-App Messaging (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 6.26.0
  * Installation method: Carthage

#### Steps to reproduce:

When I put **FirebaseInAppMessaging** via Carthage, it doesn't work properly.

I looked into it and found that `FirebaseInAppMessaging.framework` doesn't include resource(bundle).

Using **FirebaseInAppMessagingDisplay** instead, it work properly because `InAppMessagingDisplayResources.bundle` is included in `FirebaseInAppMessagingDisplay.framework`.

The documentation doesn't write FirebaseInAppMessagingDisplay.
https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md

This isn't an issue with CocoaPods, but it is an issue that occurs in the case of Carthage.
https://github.com/CocoaPods/Specs/blob/master/Specs/2/a/8/FirebaseInAppMessaging/0.20.2/FirebaseInAppMessaging.podspec.json#L26-L32

ref #4899.

**Comment by maksymmalyhin** [comment]
@yaminoma Sorry you have an issue.

I could not reproduce the issue. The published [FirebaseInAppMessaging.framework] (https://dl.google.com/firebase/ios/carthage/6.26.0/FirebaseMessaging-57e44f42fecf02e8.zip) includes `InAppMessagingDisplayResources.bundle` in the `Resources` directory. It is successfully downloaded by  `carthage update` on my end as well. 

I wonder if the issue you experience may be related to a Carthage  version or maybe an error while copying the frameworks. Could you try to reinstall dependencies and check again. Sometimes you may need to [clean Carthage cache](https://stackoverflow.com/questions/45504896/how-to-clear-carthage-cache) to fix broken cache state.

Please let us know if the issue resolved for you.

**Comment by yaminoma** [comment]
@maksymmalyhin Clean and Add `${SRCROOT}/Carthage/Build/iOS/FirebaseInAppMessaging.framework/Resources/InAppMessagingDisplayResources.bundle` to make sure it works correctly.
Thanks for your response.
