### ISSUE TITLE
Multi-tenancy support

### ISSUE THREAD

**Issue by 2ZeroSix** [firebase/firebase-ios-sdk#5747]
### Feature proposal

* Firebase Component: Auth

Is there any plans to add multi-tenancy support?
It's available in js client/admin sdk https://cloud.google.com/identity-platform/docs/multi-tenancy-authentication

**Comment by rosalyntan** [comment]
Thanks for filing this feature request! Filed b/158507022 for internal tracking.

**Comment by rosalyntan** [comment]
This has been added in #6142
