### ISSUE TITLE
'GDTCORFlatFileStorage' does not conform to protocol

### ISSUE THREAD

**Issue by GabeJacobs** [firebase/firebase-ios-sdk#5751]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.5
  * Firebase SDK version: 7.60.0
  * Firebase Component: GoogleDataTransport (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version:
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

After calling "pod update" yesterday, I am now getting the error:

`Class 'GDTCORFlatFileStorage' does not conform to protocol 'GDTCORStorageProtocol'`
line 29 in GDTCORFlatFileStorage 2.m in GoogleDataTransport

This is a Objective-C project with the podfile as follows: 

  pod 'MBProgressHUD'
  pod 'Firebase/Core'
  pod 'Google-Mobile-Ads-SDK'
  pod 'GoogleAnalytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  pod 'GoogleMobileAdsMediationInMobi'
  pod 'GoogleMobileAdsMediationAppLovin'
  pod 'GoogleMobileAdsMediationMoPub'
  pod 'GoogleMobileAdsMediationUnity'
  pod 'GoogleMobileAdsMediationFacebook'
  pod 'OneSignal', '>= 2.11.2', '< 3.0'
  pod 'SCSiriWaveformView'
  pod 'LLSimpleCamera'
  pod "SDRecordButton"
  pod 'UISlider-TrackHeight', '~> 1.0.0'
  pod "IVSWebViewController"
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKPlacesKit'
  pod 'IAPHelper'

#### Steps to reproduce:

run pod install
build app

**Comment by mikehaney24** [comment]
This is very weird--what is the file `GDTCORFlatFileStorage 2.m`?

**Comment by GabeJacobs** [comment]
> This is very weird--what is the file `GDTCORFlatFileStorage 2.m`?

Wow weird, your question made me realize immediately that something must have been wrong with my pods. Sorry, I really should have realized. Somehow every file was duplicated. I deleted my pods, reinstalled, and it's fixed. I wonder how that happened? 

Thanks though for answering quickly, very appreciated!
