### ISSUE TITLE
Firestore connection delays when enables WiFi in background

### ISSUE THREAD

**Issue by shosokawa** [firebase/firebase-ios-sdk#5783]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.5 Build version 11E608c
  * Firebase SDK version: 6.25.0
  * Firebase Component: Firestore
  * Component version: 1.14.0
  * Installation method: `CocoaPods`

### [REQUIRED] Step 2: Describe the problem

After changing a connection from 4G to WiFi in the background, it seems that it spent long time (about 20 seconds) to reconnect to the server at when the app has become active.
Some documents are created while the app is in the background, then makes the app active: 
- `snapshotListener` isn't called until about 20 seconds after
- `query.getDocuments` with `FirestoreSource.server` is failed with the error:
```
Error Domain=FIRFirestoreErrorDomain Code=14 "Failed to get documents from server. (However, these documents may exist in the local cache. Run again without setting source to FirestoreSourceServer to retrieve the cached documents.)"
```
If it is called with `FirestoreSource.default`, it returns results from the cache. 

#### Steps to reproduce:

1. Activates an app with WiFi disabled. (4G is used)
2. Makes the app background.
3. Enables WiFi.
4. Creates some documents on firestore in order to make `snapshotListener` called.
4. Makes the app active
-> After about 20 seconds, `snapshotListener` is called

**Comment by schmidt-sebastian** [comment]
@shosokawa Thanks for reporting this.

We have seen similar reports for Transactions (https://github.com/firebase/firebase-ios-sdk/issues/4905) and believe that its fix (https://github.com/firebase/firebase-ios-sdk/pull/4985 ) should apply to all of our networking logic. 

It will take me a couple of days to look at this in more detail, which should allow us figure out why the code changes for #4905 don't apply in this case.  Please do bear with us.
