### ISSUE TITLE
Photos app extension on macOS crashing after integrating Firebase crashlytics with the crash "__CRASHING_DUE_TO_PRIVACY_VIOLATION__"

### ISSUE THREAD

**Issue by robosoft-vidyalaxmi** [firebase/firebase-ios-sdk#5784]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.2.1
  * Firebase SDK version: 6.25.0
  * Firebase Component: Firebase/Crashlytics
  * Component version: 4.1.0
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

Our macOS app uses the Photos app extension and we have recently integrated Firebase Crashlytics framework on our extension. This was working fine for a couple of days but recently we started observing crashes on launching the Photos extension. The crash log says "__CRASHING_DUE_TO_PRIVACY_VIOLATION__". This usually happens when we have missed Privacy - usage description key in our Info.plist but our Info.plist includes Privacy - Photo Library Additions Usage Description and Privacy - Photo Library Usage Description. And the crash happens before our app asks permission for using Photos library

We tried removing the Firebase crashlytics SDK from our app extension and crash was not observed on launching Photos extension. The crash occurs even if we have just included Firebase crashlytics SDK and not initialized crashlytics in our code

#### Steps to reproduce:
1. Integrate the firebase SDK to macOS app and Photos app extension using cocoapods
2. Launch the Photos extension and extension terminates

<img width="567" alt="Screenshot 2020-06-10 at 18 58 11" src="https://user-images.githubusercontent.com/6337981/84273709-9ee6a000-ab4c-11ea-9527-777267dca8cc.png">

**Comment by elenadoty** [comment]
Hi @robosoft-vidyalaxmi ,
Are you still experiencing this issue in the latest versions?
