### ISSUE TITLE
[Crashlytics] Not receiving crash reports

### ISSUE THREAD

**Issue by ghost** [firebase/firebase-ios-sdk#5785]
### Step 1: Describe your environment

  * Xcode version: 11.5 (11E608c)
  * Firebase SDK version: 6.26.0
  * Firebase Component: Auth, Core, Firestore, Messaging, Storage, Performance, Analytics, Crashlytics
  * Component version: 6.26.0
  * Installation method: CocoaPods

###  Step 2: 

Crash reports are correctly uploaded if the crash happens on simulator, but if I build the app and distribute it via App Distribution I see the following messages on the device console:

[Firebase/Crashlytics] Version 4.1.1
[Firebase/Crashlytics] Packaged report with id '4866658116d143c1b00b74820fdff9e4' for submission
[Firebase/Analytics][I-ACS031025] Analytics screen reporting is enabled. Call +[FIRAnalytics setScreenName:setScreenClass:] to set the screen name or override the default screen class name. To disable screen reporting, set the flag FirebaseScreenReportingEnabled to NO (boolean) in the Info.plist
[Firebase/Analytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
[Firebase/Analytics][I-ACS023007] Analytics v.60600000 started
[Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
[Firebase/Analytics][I-ACS025036] App Delegate Proxy is disabled
[Firebase/Analytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
[Firebase/Analytics][I-ACS023012] Analytics collection enabled

but NO crash reports are shown on the Crashlytics.

#### Steps to reproduce:

Just add an assertion failure or any other code to cause a crash (eg. array index out of range)

**Comment by developerTrex** [comment]
@morganchen12 ok
