### ISSUE TITLE
FR: Allow passing nil to Crashlytics.setUserID to match Firebase Analytics and old Fabric Crashlytics APIs

### ISSUE THREAD

**Issue by rpendleton** [firebase/firebase-ios-sdk#5792]
### Feature proposal

* Firebase Component: Crashlytics

Both Firebase and Fabric Crashlytics allow passing `nil` to clear the user identifier. It would be nice if Firebase Crashlytics allowed this as well, especially now that it's the recommended replacement for Fabric Crashlytics.

If this change was made, I'd expect to be able to clear a previously assigned user ID by calling:

```swift
Firebase.Crashlytics.crashlytics().setUserID(nil)
```

**Comment by kevinkokomani** [comment]
Thanks for your feature request and feedback!

I've logged this in our internal trackers that we look at to guide future work, and made a note to bring it up with the team.

**Comment by rpendleton** [comment]
After reading the [online documentation](https://firebase.google.com/docs/crashlytics/customize-crash-reports) (as opposed to the comments in the headers) for the new Firebase Crashlytics library, I found the following:

> If you ever need to clear a user identifier after you set it, reset the value to a blank string.

I was primarily concerned about being able to clear the identifier in an officially documented manner, so that fulfills my needs. You can keep this issue open if you want the library to be consistent with the other Firebase libraries, but I'm fine with the issues being closed otherwise.

**Comment by samedson** [comment]
Related to https://github.com/firebase/firebase-android-sdk/issues/1512.

Thanks @rpendleton - that's the right advice (pass an empty string). We're going to stick with this behavior for now.

**Comment by cvoronin** [comment]
As for me, it could be nice to have a method like `clearUserId()` - in this case there will be no need pass an empty string
