### ISSUE TITLE
Undefined symbols _GULResetLogger

### ISSUE THREAD

**Issue by vdharankar** [firebase/firebase-ios-sdk#5803]
* Xcode version: 11.4
  * Firebase SDK version: Latest through pods 
  * Firebase Component: (Auth, Core, Analytics)
  * Component version: Not sure 
  * Installation method: `CocoaPods 
I am receiving these linker errors 

`Undefined symbols for architecture x86_64:
  "_GULResetLogger", referenced from:
      _FIRResetLogger in FirebaseCore(FIRLogger.o)
  "_GULLoggerRegisterVersion", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_GULLoggerInitializeASL", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_GULLogBasic", referenced from:
      _FIRLogBasic in FirebaseCore(FIRLogger.o)
  "_GULLoggerEnableSTDERR", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_GULLoggerForceDebug", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_OBJC_CLASS_$_GULSceneDelegateSwizzler", referenced from:
      objc-class-ref in FirebaseAuth(FIRAuth.o)
  "_GULIsLoggableLevel", referenced from:
      _FIRIsLoggableLevel in FirebaseCore(FIRLogger.o)
  "_GULSetLoggerLevel", referenced from:
      _FIRSetLoggerLevel in FirebaseCore(FIRLogger.o)
  "_OBJC_CLASS_$_GULAppDelegateSwizzler", referenced from:
      objc-class-ref in FirebaseAuth(FIRAuth.o)
  "_OBJC_CLASS_$_GULAppEnvironmentUtil", referenced from:
      objc-class-ref in FirebaseCore(FIRApp.o)
      objc-class-ref in FirebaseAuth(FIRAuth.o)
      objc-class-ref in FirebaseAuth(FIRAuthAPNSTokenManager.o)
      objc-class-ref in FirebaseCore(FIRBundleUtil.o)
      objc-class-ref in FirebaseAuth(FIRAuthDefaultUIDelegate.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`
My Pod file looks like below

`target 'TestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestApp

pod 'Alamofire', '~> 5.0'
pod 'Bond'
pod 'Purchases', :git => 'https://github.com/daneal/RevenueCat.git'
 

pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'PromisedFuture'
pod 'GoogleUtilities', '~> 6.6.0'

end
`

I am building this for simulator currently.

**Comment by paulb777** [comment]
@vdharankar Thanks for the report. 

This is almost certainly a problem caused by stale project or Xcode state. We'll likely need a reproducible example to help beyond suggestions for related issues here and on stackoverflow.
