### ISSUE TITLE
FR: Add Download Progress for ML models

### ISSUE THREAD

**Issue by AndrewLauder** [firebase/firebase-ios-sdk#5808]
### Feature proposal

* Firebase Component: MLKit/Translate

Add updates to download progress. Right now, it only provides updates at 0.0 (started) and 1.0 (completed). Adding updates would allow developers to build a better user experience.

**Comment by AndrewLauder** [comment]
Is it possible to get this into the product?
I'm not sure why the dlProgress NSProgress object exists when it doesn't give any feedback besides 0.0 and 1.0.

**Comment by doctiger** [comment]
This has been a trouble to me as well. I'm actually creating Translator app, but eventually I just have ended up with endless progress bar while it doesn't provide me any progress sensitive solution.

At the same time, the downloading is very slow as well. In the document, it's said that the model size is about 30MB, but it's taking much more time than I expected.
I don't know if Firebase MLKit is used, but some other translator apps have got significant fast download speed for translation models.

Anyway the progress, and download are a headache to me.

**Comment by morganchen12** [comment]
@manjanac can you see if this issue is still present in the FirebaseML model download logic?

**Comment by AndrewLauder** [comment]
Please fix, this causes a very bad user experience.

**Comment by morganchen12** [comment]
Hey all, the MLNLTranslate pod is no longer a part of Firebase. We'll be revisiting the custom model download logic in ML soon and will make sure to address this there.

**Comment by paulb777** [comment]
Closing for staleness. Please comment or reopen if desired.
