### ISSUE TITLE
FR: Add Download Size for remote models

### ISSUE THREAD

**Issue by AndrewLauder** [firebase/firebase-ios-sdk#5809]
### Feature proposal

* Firebase Component: MLKit/Translate

Add size to MLKit download. Adding size would allow developers to build a better user experience by showing the user how much data will be used.

**Comment by morganchen12** [comment]
This would likely end up as part of a greater API for fetching model metadata, which could be done in advance of fetching the model itself.

**Comment by paulb777** [comment]
Closing for staleness. Please comment or reopen if desired.
