### ISSUE TITLE
firebase and kvo conflict

### ISSUE THREAD

**Issue by NanNanCHN** [firebase/firebase-ios-sdk#581]
my environment
  * Xcode version: __9.2___
  Using Firebase (4.8.0)
  Using FirebaseAnalytics (4.0.5)
  Using FirebaseCore (4.0.13)
  Using FirebaseInstanceID (2.0.8)
  Using GoogleToolboxForMac (2.1.3)

Describe the problem
Because our project performed kvo on [UIApplication sharedApplication] .delegate to hook a series of UIApplicationDelegate methods, but then call [FIRApp configure]; after this method, our hook failed.

#### Relevant Code:
Demo: https://github.com/NanNanCHN/FireBaseKVO

Please use the demo, you will find the focus of this issue.

This is the first time setDelegate has been called.
<img width="1263" alt="4b9965b7-233e-45cb-825e-a17bdecc8d83" src="https://user-images.githubusercontent.com/8380241/34239585-4c9f3116-e643-11e7-9d11-641c537abe25.png">

This is the second time setDelegate has been called.
<img width="1247" alt="0cddff69-2d6f-4abc-b44d-f66f5c629b88" src="https://user-images.githubusercontent.com/8380241/34239619-8bde4466-e643-11e7-8ad3-480cf200d229.png">

I think the issue with firebase is that it does not use the setDelegate method to change delegate.It is risky to do so.

This situation led us hook - (void)applicationDidBecomeActive:(UIApplication *)application failure

This conflict, we can not solve, also hope firebase help compatible.

**Comment by paulb777** [comment]
Thanks for the report. Would you send a github project or zip file that demonstrates the issue?

**Comment by morganchen12** [comment]
As a temporary workaround, can you hook into AppDelegate after Firebase is configured?

**Comment by NanNanCHN** [comment]
Hello, I'm very sorry for the project hook module code is too complicated, and company code protection, there is no way to provide demo;
But today in the testing process, found that the focus is on firebase twice [UIApplication sharedApplication] setDelegate; The first incoming parameter is nil The second parameter is FIRA_AppDelegate-1513771882565;
The problem is that the first setDelegate when the object is nil, [UIApplication sharedApplication] .delegate already FIRA_AppDelegate-1513771882565, I personally think this is not reasonable, I do not know what you think?

**Comment by NanNanCHN** [comment]
@morganchen12 [FIRApp configure] is executed in asynchronous threads

**Comment by NanNanCHN** [comment]
@paulb777 I guess firebase is passed in the first setDelegate nil, the delegate object has changed the isa pointer, which led to the problem is caused when we remove the kvo will be abnormal, so sad

**Comment by morganchen12** [comment]
Can you post the stack trace of the crash? It's possible moving the `[FIRApp configure]` call to the main thread will fix it.

**Comment by NanNanCHN** [comment]
@morganchen12 Removing kvo will not crash, but does cause other anomalies, such as hook UIApplication setDelegate method fails, [FIRApp configure] execution in the new thread, and this thread is not i open, I was called in the main thread [ FIRApp configure]

**Comment by NanNanCHN** [comment]
I don't understand that before the setDelegate method passes nil, it turns the ISA pointer of the delegate object to FIRA_AppDelegate-1513771882565, which doesn't seem to be reasonable

**Comment by NanNanCHN** [comment]
@paulb777 @morganchen12 Hello, I pulled out the main logic and made a demo. Although this demo logic is not perfect, it can see the problem.I hope you can have a look at the time.Thanks very much.
Demo: https://github.com/NanNanCHN/FireBaseKVO

**Comment by baolocdo** [comment]
There are several problems in your implementations:
1. Please see https://blog.newrelic.com/2014/04/16/right-way-to-swizzle/
2. Why do you swizzle UIAppDelegate class? If it's your SDK, the delegate class can have any name, not just "UIAppDelegate". For example: "MYCoolAppDelegate"
3. You should wait until the delegate is set instead of swizzling setDelegate. It's dangerous to do so as it may crash not only Firebase SDKs but other SDKs as well as the app that may change their delegate at some point in time. A good way to observe the delegate instance change is 
```
[[UIApplication sharedApplication]
      addObserver:self
         forKeyPath:@"delegate"
               options:NSKeyValueObservingOptionNew | NSKeyValueObservingOptionOld
               context:nil]
```
4. You should not swizzle out applicationDidBecomeActive: either. A more recommended way would be listening to the notification UIApplicationDidBecomeActiveNotification

**Comment by NanNanCHN** [comment]
Thank you for your reply.

1.I have finished reading this article. Thank you.
2.We hooked the object passed in by `setDelegate` ,I can understand your example, we are         compatible with this situation.
3.You introduce the use of kvo and swizzling setDelegate is essentially a hook means, so it does not matter what kind of use.
4.Because we have method calls before and after the needs, it can not use UIApplicationDidBecomeActiveNotification.

Please use the demo, you will find the focus of this issue.

This is the first time setDelegate has been called.
<img width="1263" alt="4b9965b7-233e-45cb-825e-a17bdecc8d83" src="https://user-images.githubusercontent.com/8380241/34239585-4c9f3116-e643-11e7-9d11-641c537abe25.png">

This is the second time setDelegate has been called.
<img width="1247" alt="0cddff69-2d6f-4abc-b44d-f66f5c629b88" src="https://user-images.githubusercontent.com/8380241/34239619-8bde4466-e643-11e7-8ad3-480cf200d229.png">

I think the issue with firebase is that it does not use the setDelegate method to change delegate.It is risky to do so.

**Comment by baolocdo** [comment]
Actually, we use the setDelegate to change the delegate and we avoid swizzling out important AppDelegate methods like this case. We also do not swizzle the entire class or swizzle at +load to avoid the issues you are facing. You shouldn't assume that other SDKs or apps don't set the AppDelegate instance to anything different in the entire life cycle of the app. There is nothing wrong with using KVO and we only observe the change in the app delegate instance and any SDKs or apps can legally do so. I'd recommend to revise your assumption about -setDelegate:.

**Comment by cxjwin** [comment]
https://stackoverflow.com/questions/11221110/my-isa-swizzling-breaks-kvo

**Comment by cxjwin** [comment]
Is firebase use custom isa-swizzling ?

**Comment by YahiaRagae** [comment]
have you tried to set the flag FirebaseAppDelegateProxyEnabled to false in info.plist ?
