### ISSUE TITLE
Veracode issue in GDTCCTNanopbHelpers.m - Unchecked Return Value

### ISSUE THREAD

**Issue by YessineM** [firebase/firebase-ios-sdk#5815]
**Environment**

Xcode version: 11.3.1
Firebase SDK version: 6.26.0
Firebase Component: GoogleDataTransport (6.2.1) 
Installation method: CocoaPods

**Description:**

Ignoring a method's return value can cause the program to overlook unexpected states and conditions.

**Relevant Code:**

.../GDTCCTNanopbHelpers.m 44
.../GDTCCTNanopbHelpers.m 112

**Comment by maksymmalyhin** [comment]
@YessineM Thank you for filing the issues. Could you please provide a bit more information on your concern. As far as I can see the return values are validated and used at the specified lines:
- [.../GDTCCTNanopbHelpers.m 44](https://github.com/firebase/firebase-ios-sdk/blob/3127b8cce15c8e2ce6dbe78c646f62a71bbe4f4d/GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m#L44)
- [.../GDTCCTNanopbHelpers.m 112](https://github.com/firebase/firebase-ios-sdk/blob/3127b8cce15c8e2ce6dbe78c646f62a71bbe4f4d/GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m#L112)
