### ISSUE TITLE
GoogleDataTransport CPU 6.26.0

### ISSUE THREAD

**Issue by xiaohuihui000** [firebase/firebase-ios-sdk#5816]
when applicationWillEnterForeground GDT consume  Large number of CPUs 

<img width="881" alt="截屏2020-06-15上午11 49 11" src="https://user-images.githubusercontent.com/24727182/84616582-01e68700-aeff-11ea-8595-5435d1fed5c3.png">

my phone is iPhone 8 and version is 13.4.1
it's not show on iphone 6s

thanks

**Comment by xiaohuihui000** [comment]
when applicationWillEnterForeground app stuck ,cpu more than 100%

<img width="442" alt="截屏2020-06-15下午1 18 29" src="https://user-images.githubusercontent.com/24727182/84620506-c782e700-af0a-11ea-9857-8018fe28c3c2.png">

by instruments , when  applicationWillEnterForeground GDT DecodeArchive 

on iphone 7P 13.4.1 , not show

on iphone 7 13.4.1, show


<img width="1280" alt="截屏2020-06-15下午1 47 48" src="https://user-images.githubusercontent.com/24727182/84622132-d7042f00-af0e-11ea-9131-1d4e48eba594.png">

i really need your help 

thanks

**Comment by maksymmalyhin** [comment]
@xiaohuihui000 Have you found a reason of the issue you described? If yes, would you like to share it - it may help other developers if they encounter a similar issue.

**Comment by maksymmalyhin** [comment]
Ah, I can see another ticket filed by you for the issue #5819
