### ISSUE TITLE
Consumes a lot of CPU  when appWillForeground 

### ISSUE THREAD

**Issue by xiaohuihui000** [firebase/firebase-ios-sdk#5819]
### Step 0: Are you in the right place?

Yes, I think so

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4.1
  * Firebase SDK version: 6.26.0
  * Firebase Component: FirebaseMLNLTranslate
  * Component version: 0.18.0
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem
Consumes a lot of CPU  when appWillForeground ,because GoogleDataTransport DecodeArchive

<img width="881" alt="截屏2020-06-15上午11 49 11" src="https://user-images.githubusercontent.com/24727182/84625296-91973000-af15-11ea-9c35-ee2617bdc23e.png">

<img width="442" alt="截屏2020-06-15下午1 18 29" src="https://user-images.githubusercontent.com/24727182/84625417-c86d4600-af15-11ea-8ebb-eded8d0d0c72.png">

#### Steps to reproduce:

after download models 

in foreground from background

demo: [https://github.com/xiaohuihui000/googleTranslate](https://github.com/xiaohuihui000/googleTranslate)

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by xiaohuihui000** [comment]
on some phone  will crash
![截屏2020-06-16下午4 59 05](https://user-images.githubusercontent.com/24727182/84754469-02604a00-aff3-11ea-8191-9b174939a476.png)
can you help me ?
thanks!

**Comment by maksymmalyhin** [comment]
@xiaohuihui000 Sorry you encountered the issue. This part was refactored and should not cause performance issues any more. The fix is expected to be available in Firebase 6.28.0 version that is scheduled for the release for the mid next week.
