### ISSUE TITLE
@DocumentId breaks JSONEncoder

### ISSUE THREAD

**Issue by mrackwitz** [firebase/firebase-ios-sdk#5820]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.5
  * Firebase SDK version: Firebase/Core (6.26.0)
  * Firebase Component: Firestore
  * Component version: FirebaseFirestore (1.15.0), FirebaseFirestoreSwift (0.3.0)
  * Installation method: CocoaPods

#### Steps to reproduce:

Try to encode a model, which is using `@DocumentId`, as JSON using Swift's `JSONEncoder`. 💥 

```
▿ FirestoreEncodingError
  - encodingIsNotSupported : "DocumentID values can only be encoded with Firestore.Encoder"
```

#### Relevant Code:

```
struct Model: Codable {
  @DocumentId var id: String? = nil
  var foo = "bar"
}
let model = Model()
try! JSONEncoder().encode(model)
```

**Comment by schmidt-sebastian** [comment]
@mrackwitz Thanks for filing this issue!

This is actually working as intended as DocumentReferences contain state that is not serializable to JSON. Please also see https://github.com/firebase/firebase-ios-sdk/issues/5438#issuecomment-619262231
