### ISSUE TITLE
api request

### ISSUE THREAD

**Issue by LaPrelle10** [firebase/firebase-ios-sdk#5833]
### [READ] Guidelines

When filing a feature request please make sure the issue title starts with "FR:".

A good feature request ideally
* is either immediately obvious (i.e. "Add Sign in with Apple support"), or
* starts with a use case that is not achievable with the existing Firebase API and
  includes an API proposal that would make the use case possible. The proposed API
  change does not need to be very specific.

Once you've read this section, please delete it and fill out the rest of the template.

### Feature proposal

* Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)

Describe your use case and/or feature request here.

**Comment by morganchen12** [comment]
Hey, please read the instructions and fill out the feature request template, then comment here and I'll re-open the issue.
