### ISSUE TITLE
Github tag altered for public release

### ISSUE THREAD

**Issue by mikehardy** [firebase/firebase-ios-sdk#5834]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.5
  * Firebase SDK version: 6.27.0
  * Firebase Component: all
  * Component version: current
  * Installation method: `CocoaPods`

### [REQUIRED] Step 2: Describe the problem

`pod spec which Firebase` == 6.27.0

previously scripts relying on the format 'Major.Minor.Patch' found the tag on github, the new release is 'CocoaPods-Major.Minor.Patch'

https://github.com/invertase/firestore-ios-sdk-frameworks/issues/5

#### Steps to reproduce:

What happened? How can we make the problem occur?

Look for a tag in the old format, response 404

#### Relevant Code:

https://github.com/invertase/firestore-ios-sdk-frameworks/runs/778172161?check_suite_focus=true

**Comment by paulb777** [comment]
@mikehardy Thanks for the report. We did not realize there were dependencies on the tagging scheme.

We intentionally made the tagging strategy change in anticipation of Swift Package Manager and its limited tagging flexibility.  We want to be able to check in a Package.swift and manage CocoaPods releases without Swift Package Manager making the assumption that version is available for it.

**Comment by mikehardy** [comment]
I'm not sure how you could have been aware :-), and how do you message a tag change? I made a PR to the one dependency I'm aware of. But either way - you guys are aware now. Cheers @paulb777
