### ISSUE TITLE
FR: Provide a way to dynamically enable/disable Screen Reporting

### ISSUE THREAD

**Issue by uson1x** [firebase/firebase-ios-sdk#5838]
### Feature proposal

* Firebase Component: Analytics

Right now you can only either enable screen reporting or disable it completely via `FirebaseScreenReportingEnabled` in app's .plist.

In our case, some clients don't want the data to be sent to 3rd parties. Others are ok with it. 
We would like to keep the screen reporting for those clients who are ok with it. 

However, clients can sign in/sign out without quitting the app. Therefore runtime enabling/disabling Screen Reporting policy change is required.

If you try to set the screen name while FirebaseScreenReportingEnabled is NO, it doesn't work:
`6.26.0 - [Firebase/Analytics][I-ACS031000] Ignoring call to setScreenName:screenClass:. Screen reporting is disabled.`

**Comment by uson1x** [comment]
I've done more tests and it looks like if we keep FirebaseScreenReportingEnabled = YES, then we can control the actual sending of data by setting:
```
Analytics.setAnalyticsCollectionEnabled(true/false)
FirebaseApp.app()?.isDataCollectionDefaultEnabled = true/false
```
is that right?

Like if we set FirebaseScreenReportingEnabled = YES and then call
```
Analytics.setAnalyticsCollectionEnabled(false)
FirebaseApp.app()?.isDataCollectionDefaultEnabled = false
```
we can still see log statements like
`6.26.0 - [Firebase/Analytics][I-ACS031010] Tracking view controller. Class, ID: LoginViewController, 1577283415790172807`.

But in Firebase DebugView, the screen_view events are no longer reported.

Could somebody, please, confirm that in that case Screen View events are not reported to Firebase servers?

Thanks!

**Comment by morganchen12** [comment]
We're working on a more selective screen reporting API that may met your needs. The workaround you listed is not recommended since it will stop all analytics events from sending (including screen recording events).

**Comment by uson1x** [comment]
@morganchen12 Thank you for information!

It happens that stopping all analytics events dynamically is exactly what we need, so I think that should work for us. Closing the issue.
