### ISSUE TITLE
MLKit, barcode scanning needs improvement when label is not flat

### ISSUE THREAD

**Issue by johnqh** [firebase/firebase-ios-sdk#5839]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.5
  * Firebase SDK version: 6.27.0
  * Firebase Component: MLVisionBarcodeModel
  * Component version: 6.27.0
  * Installation method: CocoaPods

#### Steps to reproduce:

Create a barcodeDetector with VisionBarcodeFormat.PDF417 in options
Scan the PDF417 barcode on FedEx packages.
If the FedEx label is not flat on the package, the barcode is often not recognized.

#### Relevant Code:

// image is an UIImage of a FedEx label with PDF417 barcode on it.
        let vision = Vision.vision()
        let detector vision.barcodeDetector(options: VisionBarcodeDetectorOptions(formats: VisionBarcodeFormat.PDF417))
let visionImage = VisionImage(image: image)
        detector.detect(in: visionImage) { features, error in
}

The code is fine. 
The issue is in real life, often the label is not neatly applied to the box, causing the detector to fail.

Sample file:
https://drive.google.com/file/d/1TWV5Bk-eiaNB3rSEolLczQgERWY4I54u/view?usp=sharing

**Comment by morganchen12** [comment]
The Firebase ML Kit barcode API has been deprecated since all on-device ML Kit features are no longer a part of Firebase. You should move to using the Google standalone ML Kit instead by following the migration guide [here](https://developers.google.com/ml-kit/migration).
