### ISSUE TITLE
Launch Time improvement

### ISSUE THREAD

**Issue by deekshithbellare** [firebase/firebase-ios-sdk#5845]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.7.1
  * Firebase Component: FirebaseMessaging, FirebaseCrashlytics, FirebaseAnalytics, FirebasePerformance
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

Firebase contributes significantly to the launch time. Takes average 500ms

#### Steps to reproduce:
pod 'FirebaseCore', '6.7.1'
pod 'FirebaseMessaging', '4.1.7'
pod 'FirebaseCrashlytics', '4.1.0'
pod 'FirebaseAnalytics', '6.5.1'
pod 'FirebasePerformance', '3.1.5'

Install and run the app. 
FirebaseApp.configure() - Observe the time contributed by firebase to launch time. It is around 500ms on an average.

#### Questions

Can we optimise firebase launch time?
Can we progressively launch or delay initialisation of some of the SDKS. 
Is Analytics needed for firebase crashlytics for better reporting? I observed that crash reporting was better with anayltics

**Comment by paulb777** [comment]
@deekshithbellare Thanks for the report. Does including FirebaseMessaging or not make a difference? Are you able to share a profile like https://github.com/firebase/firebase-ios-sdk/issues/2669#issuecomment-480079034?
