### ISSUE TITLE
'GoogleUtilities/GULAppEnvironmentUtil.h' file not found after Installing 'Firebase/Crashlytics' and 'Firebase/Analytics' pod file

### ISSUE THREAD

**Issue by kumareshsaran** [firebase/firebase-ios-sdk#5846]
Hi, I am trying to compile my project after installing the latest version the 'Firebase/Analytics' and 'Firebase/Crashlytics'. It's gives error like **'GoogleUtilities/GULAppEnvironmentUtil.h' file not found**

Help me to resolve this issue. Thanks in advance

![Screenshot 2020-06-18 at 6 21 13 PM](https://user-images.githubusercontent.com/20902842/85023659-ab917680-b192-11ea-9094-550dd993f82c.png)

Here I attached my pod file

`    use_frameworks!
pod 'AFNetworking'
pod 'BFTask-Extras'
pod 'Mantle'
#pod 'JSONKit'
pod 'MBProgressHUD'
pod 'FBSDKCoreKit'
#pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'FacebookLogin'
pod 'TwitterKit'
pod 'TwitterCore'
pod 'CryptoSwift'
#pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift.git", :branch => "develop"
#pod 'AWSCognito'
#pod 'AWSCore'
#pod 'AWSCognitoIdentityProvider'
#pod 'AWSSNS'
#pod 'AWSS3'
#pod 'AWSLambda'
pod 'AWSCognito', '2.4.16'
pod 'AWSCognitoIdentityProvider', '2.4.16'
pod 'AWSCore', '2.4.16'
pod 'AWSLambda', '2.4.16'
pod 'AWSS3', '2.4.16'
pod 'AWSSNS', '2.4.16'
pod 'GooglePlaces'
#pod 'Google/SignIn'
pod 'GoogleSignIn'
pod 'GoogleAnalytics'
pod 'GoogleUtilities'

pod 'Stripe', '~> 15.0.2'
#pod 'CardIO'

pod 'OpenCV', '3.3.1'

pod 'Firebase/Auth'
pod 'Firebase/Messaging'
pod 'Firebase/Storage'
pod 'Firebase/Firestore'

pod 'Firebase/Core'

#pod 'Firebase/Crash'
pod 'Firebase/Performance'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Crashlytics'
pod 'Firebase/Analytics'
#pod 'Fabric'
#pod 'Crashlytics'
pod 'FittedSheets'
#pod 'KWStepper'
pod 'TLPhotoPicker'
pod 'Alamofire', '~> 5.2'
pod 'SwiftyJSON'
pod 'Starscream', '~> 4.0.0'
pod 'RSMasterTableViewKit'
pod "ESPullToRefresh"
pod "SwiftRater"

`

Here I added my podfile.lock

`PODS:
  - AFNetworking (4.0.1):
    - AFNetworking/NSURLSession (= 4.0.1)
    - AFNetworking/Reachability (= 4.0.1)
    - AFNetworking/Security (= 4.0.1)
    - AFNetworking/Serialization (= 4.0.1)
    - AFNetworking/UIKit (= 4.0.1)
  - AFNetworking/NSURLSession (4.0.1):
    - AFNetworking/Reachability
    - AFNetworking/Security
    - AFNetworking/Serialization
  - AFNetworking/Reachability (4.0.1)
  - AFNetworking/Security (4.0.1)
  - AFNetworking/Serialization (4.0.1)
  - AFNetworking/UIKit (4.0.1):
    - AFNetworking/NSURLSession
  - Alamofire (5.2.1)
  - AWSCognito (2.4.16):
    - AWSCore (= 2.4.16)
  - AWSCognitoIdentityProvider (2.4.16):
    - AWSCore (= 2.4.16)
  - AWSCore (2.4.16)
  - AWSLambda (2.4.16):
    - AWSCore (= 2.4.16)
  - AWSS3 (2.4.16):
    - AWSCore (= 2.4.16)
  - AWSSNS (2.4.16):
    - AWSCore (= 2.4.16)
  - BFTask-Extras (1.7.5):
    - Bolts/Tasks
  - Bolts/Tasks (1.9.1)
  - CryptoSwift (1.3.1)
  - ESPullToRefresh (2.9.2)
  - FacebookCore (0.9.0):
    - FBSDKCoreKit (~> 5.0)
  - FacebookLogin (0.9.0):
    - FacebookCore (~> 0.9.0)
    - FBSDKCoreKit (~> 5.0)
    - FBSDKLoginKit (~> 5.0)
  - FBSDKCoreKit (5.15.1):
    - FBSDKCoreKit/Basics (= 5.15.1)
    - FBSDKCoreKit/Core (= 5.15.1)
  - FBSDKCoreKit/Basics (5.15.1)
  - FBSDKCoreKit/Core (5.15.1):
    - FBSDKCoreKit/Basics
  - FBSDKLoginKit (5.15.1):
    - FBSDKLoginKit/Login (= 5.15.1)
  - FBSDKLoginKit/Login (5.15.1):
    - FBSDKCoreKit (~> 5.0)
  - FBSDKShareKit (5.15.1):
    - FBSDKShareKit/Share (= 5.15.1)
  - FBSDKShareKit/Share (5.15.1):
    - FBSDKCoreKit (~> 5.0)
  - Firebase/Analytics (3.6.0):
    - FirebaseAnalytics (= 3.4.2)
  - Firebase/Core (3.6.0):
    - Firebase/Analytics
  - Firebase/CoreOnly (6.27.0):
    - FirebaseCore (= 6.8.0)
  - Firebase/Crashlytics (6.27.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 4.2.0)
  - Firebase/Performance (6.27.0):
    - Firebase/CoreOnly
    - FirebasePerformance (~> 3.1.11)
  - Firebase/RemoteConfig (6.27.0):
    - Firebase/CoreOnly
    - FirebaseRemoteConfig (~> 4.6.0)
  - FirebaseABTesting (3.3.0):
    - FirebaseCore (~> 6.8)
    - Protobuf (>= 3.9.2, ~> 3.9)
  - FirebaseAnalytics (3.4.2):
    - FirebaseInstanceID (~> 1.0)
    - GoogleInterchangeUtilities (~> 1.2)
    - GoogleSymbolUtilities (~> 1.1)
    - GoogleUtilities (~> 1.2)
  - FirebaseCore (6.8.0):
    - FirebaseCoreDiagnostics (~> 1.3)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
  - FirebaseCoreDiagnostics (1.4.0):
    - GoogleDataTransportCCTSupport (~> 3.1)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
    - nanopb (~> 1.30905.0)
  - FirebaseCrashlytics (4.2.0):
    - FirebaseCore (~> 6.8)
    - FirebaseInstallations (~> 1.1)
    - GoogleDataTransport (~> 6.1)
    - GoogleDataTransportCCTSupport (~> 3.1)
    - nanopb (~> 1.30905.0)
    - PromisesObjC (~> 1.2)
  - FirebaseInstallations (1.4.0):
    - FirebaseCore (~> 6.8)
    - GoogleUtilities/Environment (~> 6.6)
    - GoogleUtilities/UserDefaults (~> 6.6)
    - PromisesObjC (~> 1.2)
  - FirebaseInstanceID (1.0.9)
  - FirebasePerformance (3.1.11):
    - FirebaseCore (~> 6.6)
    - FirebaseInstallations (~> 1.1)
    - FirebaseRemoteConfig (~> 4.4)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/ISASwizzler (~> 6.2)
    - GoogleUtilities/MethodSwizzler (~> 6.2)
    - GTMSessionFetcher/Core (~> 1.1)
    - Protobuf (~> 3.9)
  - FirebaseRemoteConfig (4.6.0):
    - FirebaseABTesting (~> 3.1)
    - FirebaseCore (~> 6.8)
    - FirebaseInstallations (~> 1.1)
    - GoogleUtilities/Environment (~> 6.2)
    - "GoogleUtilities/NSData+zlib (~> 6.2)"
  - FittedSheets (1.4.6)
  - Google/Core (3.1.0):
    - FirebaseAnalytics (~> 3.2)
  - Google/SignIn (3.1.0):
    - Google/Core
    - GoogleSignIn (~> 4.0)
  - GoogleAnalytics (3.17.0)
  - GoogleDataTransport (6.2.1)
  - GoogleDataTransportCCTSupport (3.2.0):
    - GoogleDataTransport (~> 6.1)
    - nanopb (~> 1.30905.0)
  - GoogleInterchangeUtilities (1.2.2):
    - GoogleSymbolUtilities (~> 1.1)
  - GoogleMaps/Base (3.9.0)
  - GooglePlaces (3.9.0):
    - GoogleMaps/Base (= 3.9.0)
  - GoogleSignIn (4.4.0):
    - "GoogleToolboxForMac/NSDictionary+URLArguments (~> 2.1)"
    - "GoogleToolboxForMac/NSString+URLArguments (~> 2.1)"
    - GTMSessionFetcher/Core (~> 1.1)
  - GoogleSymbolUtilities (1.1.2)
  - GoogleToolboxForMac/DebugUtils (2.2.2):
    - GoogleToolboxForMac/Defines (= 2.2.2)
  - GoogleToolboxForMac/Defines (2.2.2)
  - GoogleToolboxForMac/Logger (2.2.2):
    - GoogleToolboxForMac/Defines (= 2.2.2)
  - "GoogleToolboxForMac/NSData+zlib (2.2.2)":
    - GoogleToolboxForMac/Defines (= 2.2.2)
  - "GoogleToolboxForMac/NSDictionary+URLArguments (2.2.2)":
    - GoogleToolboxForMac/DebugUtils (= 2.2.2)
    - GoogleToolboxForMac/Defines (= 2.2.2)
    - "GoogleToolboxForMac/NSString+URLArguments (= 2.2.2)"
  - "GoogleToolboxForMac/NSString+URLArguments (2.2.2)"
  - GoogleUtilities (1.3.2):
    - GoogleSymbolUtilities (~> 1.1)
  - GoogleUtilities/Environment (6.6.0):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/ISASwizzler (6.6.0)
  - GoogleUtilities/Logger (6.6.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (6.6.0):
    - GoogleUtilities/Logger
  - "GoogleUtilities/NSData+zlib (6.6.0)"
  - GoogleUtilities/UserDefaults (6.6.0):
    - GoogleUtilities/Logger
  - GTMSessionFetcher/Core (1.4.0)
  - JSONKit (1.4)
  - Mantle (2.1.1):
    - Mantle/extobjc (= 2.1.1)
  - Mantle/extobjc (2.1.1)
  - MBProgressHUD (1.2.0)
  - nanopb (1.30905.0):
    - nanopb/decode (= 1.30905.0)
    - nanopb/encode (= 1.30905.0)
  - nanopb/decode (1.30905.0)
  - nanopb/encode (1.30905.0)
  - OpenCV (3.3.1)
  - PromisesObjC (1.2.9)
  - Protobuf (3.12.0)
  - RSMasterTableViewKit (1.2)
  - Starscream (4.0.3)
  - Stripe (15.0.2)
  - SwiftRater (1.8.0)
  - SwiftyJSON (5.0.0)
  - TLPhotoPicker (2.0.11)
  - TwitterCore [(3.2.0)](url
 - TwitterKit (3.4.2):
    - TwitterCore (>= 3.2.0)
`

**Comment by paulb777** [comment]
It looks like a `pod update` is needed to update the change from `Google/SignIn` to `GoogleSignIn`. The `Podfile.lock` reflects the precommented out version.

More context at https://stackoverflow.com/a/51932677/556617

**Comment by paulb777** [comment]
We'll likely need a reproducible example if the above suggestions don't work and more help is needed.

**Comment by kumareshsaran** [comment]
Thank you paulb. Above solution is working fine.

**Comment by kumareshsaran** [comment]
Now i am closing this issue
