### ISSUE TITLE
Crash FBLPromises with CocoaPods/SwiftPM

### ISSUE THREAD

**Issue by basvankuijck** [firebase/firebase-ios-sdk#5855]
### Step 1: Describe your environment

  * Xcode version: 11.5
  * Firebase SDK version: 6.26.0
  * Firebase Component: Core
  * Component version: 6.26.0
  * Installation method: CocoaPods

### Step 2: Describe the problem
The app crashes
```
-[FBLPromise firebaseInstallationID]: unrecognized selector sent to instance 0x600003f5a430
```

#### Steps to reproduce:

I've got a SwiftPM dependency ([Promises](https://github.com/google/promises)) and Cocoapods dependency pointing to the Firebase iOS SDK.
After running a build I get a warning:
```
objc[93047]: Class FBLPromise is implemented in both
/xxx/SampleProject.app/Frameworks/FBLPromises.framework/FBLPromises (0x10b3f09a8) and 
/xxx/SampleProject.app/SampleProject (0x10af736f0).
One of the two will be used. Which one is undefined.
```

but after updating the SDK to v6.26.0 the app would also crash.

#### Relevant Code:
I made a sample project to illustrate the problem: https://github.com/basvankuijck/SampleProjectFirebaseCrash

---

I know there is a doc about [Firebase in libraries](https://github.com/firebase/firebase-ios-sdk/blob/master/docs/firebase_in_libraries.md) and another [GitHub issue](https://github.com/firebase/firebase-ios-sdk/issues/5467), but I can't seem to fix it without downgrading the Firebase SDK version.
Any pointers?

**Comment by paulb777** [comment]
@basvankuijck Thanks for the report. I'm not sure there are any good solutions for mixed CocoaPods and SwiftPM projects that share dependencies.  We're continuing to progress on SwiftPM support for Firebase but it's only a prototype so far. In the meantime, for a partial SwiftPM integration, it might be better to integrate Firebase via [Carthage](https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md) or the [zip download](https://github.com/firebase/firebase-ios-sdk/releases/tag/CocoaPods-6.27.0) and exclude SwiftPM - assuming the FBLPromise library versions are compatible.

**Comment by maksymmalyhin** [comment]
@basvankuijck Another option for you could be installing FBLPromises for Swift via Cocoapod (see an [example](https://github.com/basvankuijck/SampleProjectFirebaseCrash/pull/1)).

**Comment by maksymmalyhin** [comment]
Please let us know if any of the options solves your issue.

**Comment by basvankuijck** [comment]
Thanks for your response @maksymmalyhin, but for the sample project that would work. But the actual project has a SwiftPM dependency that has the google Promises dependency in it. Along with some other (internal) libraries that rely on google promises throught SwiftPM.
We could resolve it by removing the SwiftPM depdency for those libraries, but we would rather not. Since our goal is to phase out CocoaPods along the way.
I was just hoping if there would be a way for SwiftPM and CocoaPods to play along nicely with FBLPromises in the middle

**Comment by maksymmalyhin** [comment]
@basvankuijck Yeah, I see. I don't think there is a way for SwiftPM and CocoaPods to play along nicely with shared dependencies. Paul's suggestion to use [Carthage](https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md) or the [zip](https://github.com/firebase/firebase-ios-sdk/releases/tag/CocoaPods-6.27.0) to install Firebase looks like the most practical temporary workaround until Firebase SwiftPM support release to me.

**Comment by basvankuijck** [comment]
Yeah I was affraid of that.
I would have hoped there would be a (simple) trick to resolve this.
But untill Firebase will have SwiftPM support I'll add Carthage to the dependency managers to the list used for this project.
