### ISSUE TITLE
App Security issues found in Firebase iOS SDK 

### ISSUE THREAD

**Issue by Nookaraju** [firebase/firebase-ios-sdk#5865]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Xcode 11.4.1
  * Firebase SDK version: latest
  * Firebase Component: Analytics & crahlytics (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: _____
  * Installation method: `CocoaPods 

### [REQUIRED] Step 2: Describe the problem

We are using Firebase Analytics in our apps and there are a couple of security vulnerability issues found by our App Security Scanner (Data Theorem).

#### Steps to reproduce:

There too many security data leak issues finding from firebase.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

1. Data Dumped to 3rd Party OSS/SDK - AppMeasurement
Data Leakage to https://app-measurement.com
Data Leakage to https://firebaseinstallations.googleapis.com
Data Leakage to https://firebaselogging-pa.googleapis.com
Device Type was sent to https://firebaselogging-pa.googleapis.com
Device Model was sent to https://firebaselogging-pa.googleapis.com
Device Type was sent to https://app-measurement.com
Device Model was sent to https://app-measurement.com

Description: The App is dumping data to 3rd Party open source libraries (OSS) and/or commercial SDKs. Please note if the App was leaking NPI (Nonpublic Personal Information), PII (Personally Identifiable Information), hardware trackers, geolocation, etc., a separate issue would be published; thus, the raw data links above are a full summary of everything dumped from the App to third-party organizations.

During dynamic analysis, Data Theorem’s analyzer checks for leaks in several areas, including, but not limited to, the following items: OS Version, Device Manufacturer, Device Type, Device Model, Device Name, Device Platform, TimeZone, Locale, Build ID, Bootloader Version, Baseband Version, Fingerprint, MAC Address, IDFA, Android ID, IMEI, IMSI, Phone Number, Carrier Name, Carrier Code, Carrier ID, SIM Serial Number, Local IP Address, SSID, BSSID, etc

**Comment by morganchen12** [comment]
The endpoints you've listed are all Firebase endpoints used for Analytics and Crashlytics. Without logging data to those endpoints, the SDK would not be able to report data to console (i.e. crash device and OS version).

You should take care to avoid logging PII via Firebase APIs when adding Crashlytics or Analytics to your app, but otherwise this is working as intended.
