### ISSUE TITLE
Codabar barcode isn't recognized well

### ISSUE THREAD

**Issue by wfordev** [firebase/firebase-ios-sdk#5879]
### Environment
  * Xcode version: 11.5
  * Firebase SDK version: since 6.10.0
  * Firebase Component:MLVisionBarcodeModel
  * Component version: since 0.19.0
  * Installation method: CocoaPods

### Problem
Using MLVisionBarcodeModel version 0.18.0, I can scan Codabar barcodes smoothly.
But Using MLVisionBarcodeModel since version 0.19.0, I can't scan well the same Codabar barcode that version 0.18.0 can recognize. Latest version 0.20.0 too.
Since version 0.19.0 take so long time for recognizing the Codabar barcode or never recognize.

This Codabar barcode is I tried to scan actually. It's real size is 1cm x 1.75cm.
Since version 0.19.0 doesn't scan this real thing. However, It can scan this image displayed on PC.
![IMG_0388_copy](https://user-images.githubusercontent.com/39466849/85354081-b5c1c500-b544-11ea-8d39-3d9c48dd63ad.JPG)

#### Relevant Code:

```
FIRVisionImage *visionImage = [[FIRVisionImage alloc] initWithBuffer:sampleBuffer];
FIRVisionImageMetadata *metadata = [[FIRVisionImageMetadata alloc] init];
//...
visionImage.metadata = metadata;
FIRVisionBarcodeDetectorOptions *options = [[FIRVisionBarcodeDetectorOptions alloc] initWithFormats:FIRVisionBarcodeFormatCodaBar];
FIRVisionBarcodeDetector *detector = [self.vision barcodeDetectorWithOptions:options];
[detector detectInImage:visionImage
             completion:^(NSArray<FIRVisionBarcode *> *barcodes, NSError *error) {
    for (FIRVisionBarcode *barcode in barcodes) {
        NSLog(@"scan code %ld, %@", (long)barcode.valueType, barcode.rawValue
    }
}];
```

**Comment by morganchen12** [comment]
The Firebase ML Kit barcode API has been deprecated since all on-device ML Kit features are no longer a part of Firebase. You should move to using the Google standalone ML Kit instead by following the migration guide [here](https://developers.google.com/ml-kit/migration).
