### ISSUE TITLE
159827739: Dynamic Links - App crashes when a dynamic link is pressed for the second time while the app is on foreground

### ISSUE THREAD

**Issue by marqroldan** [firebase/firebase-ios-sdk#5880]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Xcode 11
  * Firebase SDK version: 6.13.0 ~ 6.25.0
  * Firebase Component: Dynamic Links
  * Component version: _____
  * Installation method: `CocoaPods` (select one)

#### Steps to reproduce:

What happened? How can we make the problem occur?
 - Simply press another or the same dynamic link for the second time when the app has been opened by a dynamic link (or a dynamic link has already been pressed beforehand); this would crash the app and the following is logged in Crashlytics 

```
FIRDynamicLinks.m line 458
__50-[FIRDynamicLinks handleUniversalLink:completion:]_block_invoke_2
```
https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseDynamicLinks/Sources/FIRDynamicLinkNetworking.m#L68

#### Relevant Code:

This issue has been raised here: https://github.com/invertase/react-native-firebase/issues/2807
With a solution by @rszalski  at https://github.com/invertase/react-native-firebase/issues/2807#issuecomment-557067373

Replacing 
`
NSURLSession *session = [NSURLSession sharedSession];`
with
```
NSURLSessionConfiguration *sessionConfig = [NSURLSessionConfiguration defaultSessionConfiguration];
NSURLSession *session = [NSURLSession sessionWithConfiguration:sessionConfig];
```

Fixes the issue, but is there any side effect to it?

**Comment by maksymmalyhin** [comment]
@markarndt Thank you for reporting the issue with a suggested fix! The proposed solution looks relevant and safe. Would you like to create a PR to apply the fix?

**Comment by ncooke3** [comment]
Hi @marqroldan, thanks for the contribution! 🙂  While trying to recreate the issue, I couldn't quite get the app to crash. I'm using the iOS12 simulator. So I have a dynamic links enabled app and also a dynamic link that links me to this app. With the app running, I switch to the Notes app where I have the dynamic link pasted. It brings me to the app. ✓ Then, without closing the app, I switch back to the Notes app and tap the same dynamic link again. This brings me back to the app, with no crashes. Does these sound like the same steps to reproduce?

**Comment by marqroldan** [comment]
Hi @ncooke3, I also tried it with the iOS 12.4 simulator and could not reproduce it there. But when done on a physical device, it does happen. I'd like to know how to help you more, as I'm not really knowledgable in native development
