### ISSUE TITLE
158784204: Dynamic link is handling latest dynamic link, created on firebase console, each time when installing app from App Store

### ISSUE THREAD

**Issue by pajtimid** [firebase/firebase-ios-sdk#5883]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.5
  * Firebase SDK version: 6.18.0
  * Firebase Component:DynamicLinks
  * Component version: 4.1.0
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem
I'm having issue with dynamic link on first installing app, after redirected from a dynamic link.

1. If user install app from app store, but before, not now, had clicked on dynamic link, it handled to have latest dynamic link created on firebase console. 
In 
`- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options`

is coming latest dynamic link created in firebase console, even if user didn't click on dynamic link.
We first detect this issue on Thursday (18.06.2020)

#### Steps to reproduce:

1. if i click on dynamic link,
2.  it redirects me to app store.
3.  I install the app. If i delete app,
4.  kill app store. 
5. open app store search for app, 
6. install app, it's handling clicked before dynamic link, every time 

I also updated firebase SDK, to the latest one, but this issue is still happening.

Firebase SDK version: 6.27.0.
Firebase Component: DynamicLinks
Component version: 4.1.0

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
    
    FIRDynamicLink *dynamicLink = [[FIRDynamicLinks dynamicLinks] dynamicLinkFromCustomSchemeURL:url];
    
    if (dynamicLink) {
        if (dynamicLink != nil) {
            [self handleIncomingDynamicLink:dynamicLink];
            return YES;
        }
    }
returne NO;
}

-(void)handleIncomingDynamicLink:(FIRDynamicLink * _Nullable) dynamicLink {
    //here I save dynamic link, if user don't have app installed
    if (![EAUser isUserAuthenticated]) {
        [SaveData save:dynamicLink.url forKey:dynamicLin];
        return;
    }
```

**Comment by rohandandavati** [comment]
Hello, 

Thanks for the bug report and the detailed reproduction steps. We'll work on prioritizing fixing this. Internal tracking: b/158784204.

**Comment by pajtimid** [comment]
Hi @rohandandavati 
Any updates regarding this issue?
Thanks

**Comment by MeghaB** [comment]
Hi @pajtimid - There is a period during which if a user uninstalls, then re-installs, the second install might still match the previous install - however, it's designed to be long enough for regular users/usage. Given the repro steps you described, it sounds like you're hitting the 'dev' edgecase vs 'real user' workflow.

If, however, you're seeing it happen very frequently in the wild (ie: your users), with varied uninstall->install time windows, please reach out to support and we can investigate - that *would* be a bug. 

Thanks!
