### ISSUE TITLE
150202244: Dynamic link always nil if added as Static framework

### ISSUE THREAD

**Issue by yogesh-nykaa** [firebase/firebase-ios-sdk#5898]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.5
  * Firebase SDK version: 6.25.0
  * Firebase Component: Dynamic Link
  * Component version: 4.1.0
  * Installation method: Zip file

### [REQUIRED] Step 2: Describe the problem
I am having an issue with dynamic link after redirected from a dynamic link. The dynamic link URL is always nil.
Earlier I have added the Dynamic Link via Cocoapods and it was working fine. The only thing I have changed is I have added the framework using Zip file.

#### Steps to reproduce:

1) Install the app.
2) Click on the dynamic link.
3) Check the dynamic link url in **application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void)** function.

#### Relevant Code:

```
func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
        let handled = DynamicLinks.dynamicLinks().handleUniversalLink(url) { (dynamiclink, error) in
            if let dynamiclink = dynamiclink, let dynamicLinkUrl = dynamiclink.url {
                    print(dynamicLinkUrl)
            }
        }
        return true
}
```

**Comment by ryanwilson** [comment]
Hi @yogesh-nykaa - thanks for the report.

Just to confirm, there are a few extra steps needed to get up and running in the zip file - particularly adding the `-ObjC` flag to "Other Linker Settings" (step 8 in the README). That, and ensuring that all the frameworks from `FirebaseAnalytics` are installed as well.

Are you still calling `FirebaseApp.configure()` as well?

Please let me know if those two things are set up appropriately and we can continue to debug this issue you're having.

Thanks!

**Comment by yogesh-nykaa** [comment]
Hi @ryanwilson , Yes we have done all the steps mentioned in README like`-ObjC` in "Other Linker Settings". 
Yes, we have added all frameworks from `FirebaseAnalytics` folder.
Yes, we are calling `FirebaseApp.configure()` in AppDelegate.

Also, other frameworks are working fine only DynamicLink is not working. and giving nil URL every time.
Let me know if any other info required.

Thanks!

**Comment by rohandandavati** [comment]
Internal tracking: b/150202244.

**Comment by yogesh-nykaa** [comment]
Hi Guys,

Any update on this?

**Comment by paulb777** [comment]
@yogesh-nykaa A reproducible example might help. Are you able to reproduce with https://github.com/firebase/quickstart-ios/tree/master/dynamiclinks?

**Comment by yogesh-nykaa** [comment]
@paulb777 Yes, it is reproducible using  https://github.com/firebase/quickstart-ios/tree/master/dynamiclinks with the static library. With pod everything works fine.

**Comment by yogesh-nykaa** [comment]
Hi Guys,

Any update on this?

**Comment by eldhosembabu** [comment]
I've tried and was not able to reproduce the issue with https://github.com/firebase/quickstart-ios/tree/master/dynamiclinks using static frameworks from https://firebase.google.com/docs/ios/setup#frameworks.

Could you please provide a sample app project which is having this issue. It would be better if you can provide the quick start app with your changes in a temporary branch.

**Comment by yogesh-nykaa** [comment]
@eldhosembabu It seems this issue has been fixed in the updated firebase sdk, but it was not working on older firebase sdk. We can close this now.
