### ISSUE TITLE
Cannot use pod 'Firebase/Crashlytics'

### ISSUE THREAD

**Issue by hrool20** [firebase/firebase-ios-sdk#5913]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase Component: Core, Analytics
  * Component version: 0.23.5, 3.17.0
  * Installation method: `CocoaPods (1.9.3)`

#### Steps to reproduce:
I try to migrate Crashlytics using:
```
pod 'Firebase/Crashlytics'
```

Instead of:
```
pod 'Fabric'
pod 'Crashlytics'
```

But, I get an error.
```
[!] CocoaPods could not find compatible versions for pod "Firebase/Crashlytics":
  In Podfile:
    Firebase/Crashlytics

None of your spec sources contain a spec satisfying the dependency: `Firebase/Crashlytics`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

My podfile is:
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'Parknina' do
   use_frameworks!
   
   pod 'Fabric'
   pod 'Crashlytics'
   pod 'Firebase/Core', '~> 6.10.0'
   pod 'Firebase/Analytics', '~> 6.10.0'
   pod 'GoogleTagManager'
end
```

**Comment by morganchen12** [comment]
Have you run `pod update`?

**Comment by paulb777** [comment]
`Firebase/Crashlytics` did not exist in Firebase 6.10.0.  Please remove the version specifiers from the Firebase pod or update them to the recent 6.27.0.

**Comment by hrool20** [comment]
> `Firebase/Crashlytics` did not exist in Firebase 6.10.0. Please remove the version specifiers from the Firebase pod or update them to the recent 6.27.0.

Thanks @paulb777! That was the solution for this problem.
