### ISSUE TITLE
Build failed with error "Undefined symbol: _GULResetLogger"

### ISSUE THREAD

**Issue by AVUshakov** [firebase/firebase-ios-sdk#5914]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.5
  * Firebase SDK version: 6.27.0
  * Firebase Component: Analytics, Messaging
  * Component version: 6.6.1, 4.5.0
  * Installation method: `CocoaPods` (select one)

### [REQUIRED] Step 2: Describe the problem
Good day. 
I installed pod file in the project according to the instructions "Adding Firebase to the iOS app". But i have a one error pops up when I building the project on simulator and also on physical device. Because of what the project does not compile.
Error notice:
Undefined symbols for architecture arm64:
"_GULResetLogger", referenced from:
_FIRResetLogger in FirebaseCore(FIRLogger.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
I reviewed different solutions for this problem, but nothing helps. Maybe you have encountered this question before and know a solution to such a problem?

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by morganchen12** [comment]
Can you share a sample project that reproduces this linker error? We're unable to reproduce it in our quickstarts.
