### ISSUE TITLE
getDocumentWithSource calls back on background thread

### ISSUE THREAD

**Issue by paulharter** [firebase/firebase-ios-sdk#5932]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.5
  * Firebase SDK version: FirebaseCore (6.8.0):
  * Firebase Component: FirebaseFirestore (1.16.0)
  * Component version: 1.16.0
  * Installation method: CocoaPods
 * iOS Catalyst on macOS 10.15.5

### [REQUIRED] Step 2: Describe the problem

On migrating from  FirebaseFirestore (1.7.0) to FirebaseFirestore (1.16.0) application crashes due to getDocumentWithSource sometimes calling back on background thread rather than main. 

This is then being caught by the UI thread checker 

`Main Thread Checker: UI API called on a background thread: -[UIViewController isViewLoaded]
PID: 25769, TID: 1562036, Thread name: (none), Queue name: com.google.firebase.firestore.user, QoS: 0`

Is this a known problem I cannot see anything in current issues?

#### Steps to reproduce:

It does not happen on every call to getDocumentWithSource but does happens at a deterministic point in my application but I don't have a good isolated test case. If you have no immediate idea I will try to create an isolated case.

#### Relevant Code:

```
    
    NSLog(@"*********************** IS ON MAIN before %hhd", [NSThread isMainThread]);
    NSLog(@"%@", [NSThread currentThread]);
    
    [docRef getDocumentWithSource:FIRFirestoreSourceDefault completion:^(FIRDocumentSnapshot *snapshot, NSError *error) {

    NSLog(@"*********************** IS ON MAIN after %hhd", [NSThread isMainThread]);
    NSLog(@"%@", [NSThread currentThread]);
```

```
2020-06-26 20:31:29.380732+0100 Edit Board[25769:1561562] *********************** IS ON MAIN before 1
2020-06-26 20:31:29.380845+0100 Edit Board[25769:1561562] <NSThread: 0x600001710140>{number = 1, name = main}
2020-06-26 20:31:29.917101+0100 Edit Board[25769:1562036] *********************** IS ON MAIN after 0
2020-06-26 20:31:29.917326+0100 Edit Board[25769:1562036] <NSThread: 0x6000017ea100>{number = 12, name = (null)}
```

**Comment by paulharter** [comment]
This seems to have gone away!  

I went back to earlier version 6.24.0 to see if that worked and it did. Then walking through versions back up to 6.27.0, which now seem ok too.

So some kind of transient problem, maybe caused by incomplete cleaning of pods when upgrading?

I'll close this now and reopen if it reappears and I can give a better notion of why

**Comment by wilhuff** [comment]
That's extremely surprising that you saw a reference to `com.google.firebase.firestore.user`, because that was added in a [PR that landed yesterday](https://github.com/firebase/firebase-ios-sdk/commit/ea71423c0962d14db7f575824d65abaee0e57af7) and that hasn't been released. Does your `Podfile` by chance have a reference to Firestore in a branch?

What are the contents of `Pods/FirebaseFirestore/Firestore/core/src/util/config.h`? This is the file that controls which implementations the library uses for the current platform. With Firebase 6.27.0, mine looks like this:

```c
// copyright, header guards, and explanation ...

#if COCOAPODS
#  define HAVE_ARC4RANDOM 1
#endif

#if COCOAPODS
#  define HAVE_LIBDISPATCH 1
#endif
```

**Comment by paulharter** [comment]
I have the same config.h

I think I know what happened:

Some pods in this project hadn't been updated for a while including Firestore. Updating pods one at a time was impossible and dependency checking was failing on everything.

So I thought I'd take the hit, delete the Pods and lockfile, do a clean install and fix everything that breaks. First attempt to install wasn't happy. Looking at pods several Firebase ones were pointing at master branch in source from a while back when I was first getting Firestore to build on Catalyst. I removed the github references and took the latest stable pods instead.

So I think I ending up with an install of 6.27.0 on top of a not fully cleaned out build from current master.
