### ISSUE TITLE
FirebaseCrashlytics - Symbol files not appearing on console, although getting "Successfull submitted symbols for architecture..."

### ISSUE THREAD

**Issue by GiladR1979** [firebase/firebase-ios-sdk#5948]
### Step 1: Describe your environment

  * Xcode version: 11.5
  * Firebase SDK version: 6.25.0
  * Firebase Component: Crashlytics
  * Component version: 6.25.0
  * Installation method: CocoaPods

#### Steps to reproduce:

Updated my project using FirebaseCrashlytics instead of Fabric using the guides.
Deleted all Fabric code and plist entries related to Fabric.
Updated script using the upload-symbols of FirebaseCrashlytics:
```
${PODS_ROOT}/FirebaseCrashlytics/upload-symbols" -gsp "${PROJECT_DIR}/GooglePlistPath/firebaseConfigFile.plist" -p ios "${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}"
```

Getting a success message on the script-

```
Successfully submitted symbols for architecture armv7 with UUID 650d65bd42113d14**************47 in dSYM: /path/Developer/Xcode/DerivedData/ProjectName-cxgxxkmvnajfcfadzpsliaukapok/Build/Intermediates.noindex/ArchiveIntermediates/****/BuildProductsPath/ReleaseProduction-No-DT-iphoneos/Filename.app.dSYM
```

dSym files do not appear on the console. Still getting "Missing dSym files" error. Waited for more than 24 hours for it to update. tried changing dsym folders in script. Nothing works.
Cleaned the project, deleted the app, installed, caused a crash, still nothing. 
Missing UUIDs in console are nowhere to be found, although I see dSyms files are created and sent successfully.
What's going on?

**Comment by kevinkokomani** [comment]
When you say "dSym files do not appear on the console," are you expecting the dSYMs themselves to appear on the console? Only dSYMs that are missing will show up in the missing dSYMs tab - if you're getting crash reports and you don't have any missing dSYMs, that means that the dSYMs have been uploaded correctly and no further action is required.

If you're still missing dSYMs, another thing we can recommend is to check is where you're getting the dSYMs. If your app is bitcode-enabled, try downloading the dSYMs directly App Store Connect and uploading those, if you haven't been already.

**Comment by GiladR1979** [comment]
> When you say "dSym files do not appear on the console," are you expecting the dSYMs themselves to appear on the console? Only dSYMs that are missing will show up in the missing dSYMs tab - if you're getting crash reports and you don't have any missing dSYMs, that means that the dSYMs have been uploaded correctly and no further action is required.
> 
> If you're still missing dSYMs, another thing we can recommend is to check is where you're getting the dSYMs. If your app is bitcode-enabled, try downloading the dSYMs directly App Store Connect and uploading those, if you haven't been already.

I meant to say that there are still missing dSYMs on the console, and I get no crash reports.
I get the dSYMs exactly from the same place Fabric used to get them, and it worked then, so I don't think the problem is finding the files.

**Comment by kevinkokomani** [comment]
Thanks for clarifying! I think the best next step here would be to submit a case to [Firebase support](https://firebase.google.com/support/troubleshooter/contact). Once we get to the stage where the logs say the dSYMs are being uploaded successfully, but the console doesn't reflect that success, it's best to bring directly to support so we can look into the backend for your app. That's better suited for a private thread.

**Comment by mars-lan** [comment]
@GiladR1979  any luck with Firebase support? We're seeing a similar issue from our side and are forced to downgrade to legacy Crashlytics for now.

**Comment by GiladR1979** [comment]
> @GiladR1979 any luck with Firebase support? We're seeing a similar issue from our side and are forced to downgrade to legacy Crashlytics for now.

Actually they replied with an unhelpful email, BUT somehow now the console doesn’t show any missing dSYM files like its all okay. But the number of crashes I see still doesn’t make sense. I need to check this further after I will finish with our release candidate this week.
