### ISSUE TITLE
macOS project will not archive when Firebase/Crashlytics is installed with CocoaPods

### ISSUE THREAD

**Issue by hipwelljo** [firebase/firebase-ios-sdk#5950]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.5 (11E608c)
  * Firebase SDK version: 6.27.0
  * Firebase Component: Crashlytics
  * Component version: 4.2.0
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

I have successfully set up Firebase Crashlytics with our macOS project, upgraded from Fabric. The app builds and runs, but attempting to archive the app results in an endless hang: Archiving AppName: AppName |  Building 787 of 800. It never proceeds. I've tried cleaning the build folder, no luck. The only thing that I've found to get it to archive is to remove Firebase Crashlytics from the project altogether.

#### Steps to reproduce:

1. Add pod 'Firebase/Crashlytics' to a macOS app
2. Try to archive the app
Result: It gets stuck building and never creates an archive

**Comment by morganchen12** [comment]
Is this reproducible with older versions of Crashlytics as well (or older versions of Xcode)?

**Comment by hipwelljo** [comment]
Hello! I have not tried older versions of Crashlytics nor older versions of Xcode. Just barely made the switch over from Fabric to Firebase. I can try older versions of Crashlytics, or Xcode, if needed. Would rather not install an old Xcode though. :)

**Comment by morganchen12** [comment]
I'll try to repro this and update the bug with my results.

**Comment by morganchen12** [comment]
Sorry for the slow update; I was able to archive a macOS app that includes Crashlytics without issue. Can you share the build log from your archive action or the project that's unable to archive?

**Comment by hipwelljo** [comment]
Sure thing thanks
[Archive.txt](https://github.com/firebase/firebase-ios-sdk/files/5004065/Archive.txt)

**Comment by morganchen12** [comment]
It looks like this is the action that's causing the hang:

```
Touch /Users/Jordan/Library/Developer/Xcode/DerivedData/The_MT_Pit-erypzuqtqtqezwgsvssaqudmbvkh/Build/Intermediates.noindex/ArchiveIntermediates/The\ MT\ Pit/IntermediateBuildFilesPath/UninstalledProducts/macosx/Pods_The_MT_Pit.framework (in target 'Pods-The MT Pit' from project 'Pods')
    cd /Users/Jordan/Dropbox/Developer/HQ/MTPit/themtpitmacapp/Pods
    /usr/bin/touch -c /Users/Jordan/Library/Developer/Xcode/DerivedData/The_MT_Pit-erypzuqtqtqezwgsvssaqudmbvkh/Build/Intermediates.noindex/ArchiveIntermediates/The\ MT\ Pit/IntermediateBuildFilesPath/UninstalledProducts/macosx/Pods_The_MT_Pit.framework
```

This build issue is likely not Crashlytics-specific, and may be a Swift issue as ported [here](https://developer.apple.com/forums/thread/115303).

Can you try upgrading your Xcode version and archiving again?

**Comment by hipwelljo** [comment]
Hm I am using the latest Xcode, Version 11.6 (11E708). Removing Crashlytics allows the project to archive.

**Comment by morganchen12** [comment]
Do you have any other pods included besides Crashlytics?

**Comment by hipwelljo** [comment]
Yes we have Apollo, KeychainSwift, and Firebase/Crashlytics

**Comment by morganchen12** [comment]
Are you able to share your project?

**Comment by hipwelljo** [comment]
Is there a way I can send it to you privately?

**Comment by morganchen12** [comment]
Sure, you can email it to me at morganchen at google.com.

**Comment by hipwelljo** [comment]
Ok I'll do that thanks!

**Comment by morganchen12** [comment]
The project also hung on archive, but did not hang at the same command as your build log indicated. When I removed the Crashlytics upload-symbols script, the hang went away. Are you able to archive if you remove the upload-symbols run script phase?

**Comment by morganchen12** [comment]
After re-adding the Crashlytics run script as described [here](https://firebase.google.com/docs/crashlytics/get-started?platform=ios#initialize-crashlytics), the project no longer hangs on archive.

**Comment by hipwelljo** [comment]
Confirmed, thanks @morganchen12!
