### ISSUE TITLE
Failed to subscribe to notifications after changing APNs Auth Key

### ISSUE THREAD

**Issue by IgorRosocha** [firebase/firebase-ios-sdk#5970]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.5
  * Firebase SDK version: 6.26.0
  * Firebase Component: Messaging
  * Component version: 6.26.0
  * Installation method: Carthage

### [REQUIRED] Step 2: Describe the problem

We were forced to change the APNs key for our production app notifications. Before that, notifications worked reliably. After providing a new APNs Auth Key in Firebase Console, the notifications are not received. We always keep getting error:

```
6.26.0 - [Firebase/Messaging][I-FCM004001] Failed to subscribe to topic Error Domain=com.google.fcm Code=0 "Invalid registration response :'Error=INVALID_PARAMETERS'. It is missing 'token' field." UserInfo={NSLocalizedFailureReason=Invalid registration response :'Error=INVALID_PARAMETERS'. It is missing 'token' field.}
```

Notifications are not received event when sent to a specific FCM token of user. Are there some steps we're missing, or is this some kind of a bug?

**Comment by chliangGoogle** [comment]
Looks like the client is missing token. Would you mind sharing the full debug log? 
To enable debug logging set the following application argument: --FIRDebugEnabled (see http://goo.gl/RfcP7r)

**Comment by IgorRosocha** [comment]
Actually, few days have passed since changing the APNs Auth Key and notifications seem to work. Do you have any idea, why notifications didn't work immediately after changing the key? Is there some cache for this, which needed to be cleaned/restarted? I have tried getting fresh FCM token at the time, but that didn't help.

But at the end of the dat, notifications work now without making any changes, so we can close the issue.

**Comment by chliangGoogle** [comment]
It's hard to speculate without debug log. your case is a bit strange as token seems to be missing on the client side but it should not happen since you are only updating auth key on the console. 

If you still have the debugLog when issue happened, would be great to share with us.
