### ISSUE TITLE
Documentation: update references to FIRInAppMessagingRendering

### ISSUE THREAD

**Issue by airspeed** [firebase/firebase-ios-sdk#5971]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.6 beta
  * Firebase SDK version: 6.27.0
  * Firebase Component: InAppMessaging
  * Component version: 0.21.0
  * Installation method: `CocoaPods`

#### Steps to reproduce:

Link: https://firebase.google.com/docs/in-app-messaging/customize-messages?platform=ios
Anchor: https://firebase.google.com/docs/in-app-messaging/customize-messages?platform=ios#create_your_own_message_display_library

Replace the following three sentences where the non existing protocol `FIRInAppMessagingRendering` is referenced with the correct `FIRInAppMessagingDisplay` (objc) / `InAppMessagingDisplay` (swift), as correctly referenced ex. in the `FirebaseInAppMessaging.messageDisplayComponent` docs: https://firebase.google.com/docs/reference/ios/firebaseinappmessaging/api/reference/Classes/FIRInAppMessaging#messagedisplaycomponent

1. Build a class that implements the FIRInAppMessagingRendering interface
2. That class, in turn, uses the FIRInAppMessagingRendering protocol to display the messages it receives. 
3. Even if you're not building with it directly, you'll probably find it helpful to take a look at the default Firebase In-App Messaging message displays to get a feel for how they implement FIRInAppMessagingRendering.

**Comment by morganchen12** [comment]
Googler-only change number: cl/319823894

**Comment by morganchen12** [comment]
This is a docs-only change, so it won't be tied to any particular release.

**Comment by morganchen12** [comment]
The docs have been updated.
