### ISSUE TITLE
FR: Make public API for StackFrame creation from address

### ISSUE THREAD

**Issue by segrey-profi** [firebase/firebase-ios-sdk#5975]
### Feature proposal

* Firebase Component: Crashlytics

Fabric SDK has public function `CLSStackFrame(address:)` which is needed for correct crash logging of Kotlin Multiplatform frameworks (see https://github.com/touchlab/CrashKiOS)

Firebase Crashlytics contains `FIRCLSSymbolResolver` class with `frameForAddress:` method which seems to do the same job, but it is private API so we cannot even check if it works for Kotlin frameworks.

Please make the same public API as `CLSStackFrame(address:)` in Fabric SDK.

**Comment by Thomas-Vos** [comment]
See also: https://github.com/firebase/firebase-ios-sdk/issues/5182

**Comment by elenadoty** [comment]
We've added this API to a branch that should be going out in the next release.
