### ISSUE TITLE
FIRUser.uid sometimes returns the email instead of uid

### ISSUE THREAD

**Issue by akshetpandey** [firebase/firebase-ios-sdk#598]
Happy holidays everyone. 🎅 🎁 🎄 🎉 🎉 

Unfortunately, I feel like I am writing down one of those issues which will eventually have a blogpost on how the bug was tracked down and fixed.

### [READ] Step 1: Are you in the right place?
Likely

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: **Version 9.2 (9C40b)**
  * Firebase SDK version: **4.6.0** (Has been happening for quite a while)
  * Firebase Component: **Auth**
  * Component version: **4.6.0**

### [REQUIRED] Step 3: Describe the problem

I have an event log that simply logs the logged in user's uid on app startup. Rarely, the log contains the email instead of the uid.

Here is the event log I see when the issue happens:
`User Id: thriller.anon.user+6b611f2acc10cfe040cf861b4cbf5133@[REDACTED_DOMAIN_NAME]`
Here is what the usual event log looks like:
`User Id: w3I1VcsO0CgABFtilZUnfLplDDh2`

Now the problematic part is that soon after that I also initialize a firebase rtdb ref with the uid and it crashes the app because the email contains characters that are not valid in a ref.

#### Steps to reproduce:
Log the [FIRUser uid] at startup... notice that rarely it logs the email instead. This isn't in the AppDelegate's appDidLaunch but soon afterwards. (~0.5-1s)

**PS**: My case isn't as trivial, because my app uses react-native and I am using react-native-firebase library and the FIRUser gets passed from native side through the react-native bridge to the library and anything along that path may be screwing it up, but all the code along that part is fairly trivial and I am fairly certain the problem is in the firebase library.

**PS2**: I am also seeing this issue on android, so the problem may be what the backend server is returning?

**Issue Repo Rate**: ~ 2/day with ~500K app starts a day. The issue isn't persistent so it fixes itself on the next startup. (Or those users never came back to my app 😭 )

#### Relevant Code:
N/A

**Comment by protocol86** [comment]
@akshetpandey 
If the UID is being logged upon app start-up then it should be coming from a cached Firebase user. I have not been able to reproduce this issue, but would like to rule out the backend as being the root cause.  Are you able to reproduce this issue without an internet connection?

**Comment by akshetpandey** [comment]
@protocol86 : Sorry I am unavailable due to personal reasons this week, Expect a response on this sometime next week (likely Wednesday)

**Comment by morganchen12** [comment]
@akshetpandey is this still an issue?

**Comment by akshetpandey** [comment]
@morganchen12 : Yes, sorry haven't had the time to add reproduction steps yet. Part of the reason is that its non-trivial another is that we added a new crash in our app 😓  and now all these tiny crashes are hidden in a butt-load of noise.

**Comment by akshetpandey** [comment]
Haven't been able to repo it or seen it in live since then. Closing the issue.
