### ISSUE TITLE
"Double-quoted" issue in latest version of Firebase

### ISSUE THREAD

**Issue by sukhoi360** [firebase/firebase-ios-sdk#5987]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0 beta (12A6159)
  * Firebase SDK version: 6.27.0
  * Firebase Component: Auth, Core, Database
  * Component version: Auth: 6.6.0 / Core: 6.8.0 / Database: 6.3.0
  * Installation method: CocoaPods

#### Steps to reproduce:

Hello,
I am using Xcode 12 beta (12A6159). I updated Firebase to the latest version (6.27.0) and I have a lot of errors from the nanopb-umbrella.h file. Here are the errors :

```
- Double-quoted include "pb.h" in framework header, expected angle-bracketed instead
- Double-quoted include "pb_common.h" in framework header, expected angle-bracketed instead
- Double-quoted include "pb_decode.h" in framework header, expected angle-bracketed instead
- Double-quoted include "pb_encode.h" in framework header, expected angle-bracketed instead
- Double-quoted include "pb.h" in framework header, expected angle-bracketed instead
- Double-quoted include "pb_decode.h" in framework header, expected angle-bracketed instead
- Double-quoted include "pb_common.h" in framework header, expected angle-bracketed instead
- Double-quoted include "pb.h" in framework header, expected angle-bracketed instead
- Double-quoted include "pb_encode.h" in framework header, expected angle-bracketed instead
- Double-quoted include "pb_common.h" in framework header, expected angle-bracketed instead

```
These errors result in a failure to build the 'nanopb' module and make the execution of the project impossible.
This issue came with the update to the latest version of Firebase. **It only occurs on Xcode 12 beta, everything works well on Xcode 11.**
Here is a project that reproduces the issue : 
[testProject.zip](https://github.com/firebase/firebase-ios-sdk/files/4885044/testProject.zip)

Looking forward for your response. 

Thanks.

**Comment by paulb777** [comment]
@sukhoi360 Thanks for the report.  The error comes from a new recommended Xcode 12 build setting. We'll investigate an update to nanopb.

In the meantime a workaround is disabling the option in the generate Pods project Build Settings:

![Screen Shot 2020-07-07 at 7 52 13 AM](https://user-images.githubusercontent.com/73870/86799874-46110700-c027-11ea-9ad5-a71462145473.png)

**Comment by paulb777** [comment]
Actually this looks like a problem with all CocoaPods generated umbrella headers. Reported at https://github.com/CocoaPods/CocoaPods/issues/9902

**Comment by sukhoi360** [comment]
Thanks for your response and the workaround.

**Comment by paulb777** [comment]
A fix is at https://github.com/CocoaPods/CocoaPods/pull/9905 and targeted for CocoaPods 1.10. I'll close this bug in favor of https://github.com/CocoaPods/CocoaPods/issues/9902.

Use the workaround described above with CocoaPods versions before 1.10
