### ISSUE TITLE
Firebase crashes on launch v6.27.0 for iOS 13.4 and up

### ISSUE THREAD

**Issue by bsarrazin** [firebase/firebase-ios-sdk#5990]
### [REQUIRED] Step 1: Describe your environment

| Item | Value |
| --- | --- |
| Xcode Version |`11.5 (11E608c)` |
| Firebase SDK version | Upgrading from `6.17.0` to  `6.27.0` |
| Firebase Component | Analytics, Crashlytics and Performance |
| Component version | Upgrading from `6.17.0` to  `6.27.0` |
| Installation method | CocoaPods `1.9.3` |

#### Steps to reproduce:

Since upgrading to Firebase `6.27.0`, our app crashes on launch.
Our app is iOS 13.4 and up. Firebase crashes on launch complaining that the app isn't configured yet. However, it crashes in the `configure()` method.
We have removed all the custom code we have around app delegate services and have called the `configure()` method directly in `application(_:didFinishLaunching)` and the same crash happens.

Please see stack trace:
![](https://user-images.githubusercontent.com/1077441/86812170-b41bf500-c04c-11ea-849b-f79cbfdba5cf.png)

Debugging the Firebase code seems to indicate that there are 2 instances of the Firebase app (different pointer addresses; none of which we are creating) and the unused seems to be the one that crashes. There is some funky objc in there, it would be really appreciated if we could get some help from the Firebase team.

**Comment by morganchen12** [comment]
Seems like an instance of this crash: https://stackoverflow.com/questions/60753233/the-default-firebaseapp-instance-must-be-configured-before-the-defaultfirebaseap/61352175#61352175

**Comment by bsarrazin** [comment]
@morganchen12 that makes total sense. We do have those warnings in the console, but I'm not sure how we ended up with them to be honest.
I will try to fix those and reopen the issue if we need to. Thank you for your prompt response on this!
