### ISSUE TITLE
GoogleAppMeasurement License information

### ISSUE THREAD

**Issue by illupo45** [firebase/firebase-ios-sdk#5994]
This may seem like an odd question, but I do work for an organization that inspects a lot of the dependencies included in the delivered source code. They care about the licensing information to the point where they conduct legal reviews, which I do feel is important.

Firebase in general includes a ton of dependencies. I am able to find licensing information for all of them except

**GoogleAppMeasurement** https://github.com/CocoaPods/Specs/blob/master/Specs/e/3/b/GoogleAppMeasurement/6.6.2/GoogleAppMeasurement.podspec.json

Most of Google's stuff is Apache 2.0 licensing. Do you guys have any insight to what **GoogleAppMeasurement** is licensed as?

**Comment by illupo45** [comment]
Sorry about not following the official template but this is such a one off, general question.

**Comment by morganchen12** [comment]
GoogleAppMeasurement is closed source and distributed under the same license as the FirebaseAnalytics module. @eburley FYI

**Comment by morganchen12** [comment]
We should probably update the [podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/e/3/b/GoogleAppMeasurement/6.6.2/GoogleAppMeasurement.podspec.json#L20-L23) to point at a more complete license.

**Comment by illupo45** [comment]
Thank you for the quick response. You guys confirming that it is distributed under the same license as the FirebaseAnalytics module is good enough for me to relay at this time 👍
