### ISSUE TITLE
Firebase.configure() and GADMobileAds.configure make (independently) app crash on simulator with iOS10

### ISSUE THREAD

**Issue by Alexeichua** [firebase/firebase-ios-sdk#601]
### [1] Environment

  * Xcode version: 9.2 and previous 9.x too
  * Firebase SDK version: 4.8.0
  * Firebase Component: Auth, Core, Database, AdMob
  * Component version: corresponding - 4.4.1, 4.0.13, 4.1.3

### [2] Description:

Firebase.configure() and GADMobileAds.configure make (independently) app crash on simulator with iOS10 at the very start. Only if not to use configure() (and, of course any other commands) app can start.
I've wrote to support and got advise to check out the issue on one of sample projects, and it was reproduced!

### [3] Steps to reproduce:

Take sample project, set it up with Firebase (using Pods file) and start on simulator or iPhone with iOS10
objc[5470]: Class PLBuildVersion is implemented in both /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 10.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x1253f44c) and /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 10.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x12380b78). One of the two will be used. Which one is undefined.
Dec 28 18:42:32  DatabaseExampleSwift[5470] <Notice>: [Firebase/Analytics][I-ACS023007] Firebase Analytics v.40005000 started
Dec 28 18:42:32  DatabaseExampleSwift[5470] <Notice>: [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2017-12-28 18:42:32.849862 DatabaseExampleSwift[5470:409304] [] __nwlog_err_simulate_crash_libsystem libsystem simulate crash unavailable "libsystem_network.dylib: nw_host_stats_add_src :: received error for SRC_ADDED: [22] Invalid argument"
2017-12-28 18:42:32.851078 DatabaseExampleSwift[5470:409304] [] nw_host_stats_add_src received error for SRC_ADDED: [22] Invalid argument, dumping backtrace:
        [i386] libnetcore-856.30.16
    0   libsystem_network.dylib             0x04e3d14d __nw_create_backtrace_string + 123
    1   libsystem_network.dylib             0x04e54637 nw_get_host_stats + 1049
    2   libnetwork.dylib                    0x051be48e nw_endpoint_resolver_start_next_child + 1560
    3   libdispatch.dylib                   0x04bdb396 _dispatch_call_block_and_release + 15
    4   libdispatch.dylib                   0x04c06cc3 _dispatch_client_callout + 14
    5   libdispatch.dylib                   0x04be33ae _dispatch_queue_serial_drain + 1619
    6   libdispatch.dylib                   0x04be3bc2 _dispatch_queue_invoke + 1109
    7   libdispatch.dylib                   0x04be65e4 _dispatch_root_queue_drain + 470
    8   libdispatch.dylib                   0x04be63a6 _dispatch_worker_thread3 + 143
    9   libsystem_pthread.dylib             0x04f85fdc _pthread_wqthread + 1356
    10  libsystem_pthread.dylib             0x04f85a6a start_wqthread + 34
2017-12-28 18:42:33.150878 DatabaseExampleSwift[5470:409292] [] __nwlog_err_simulate_crash_libsystem libsystem simulate crash unavailable "libsystem_network.dylib: nw_host_stats_add_src :: received error for SRC_ADDED: [22] Invalid argument"
2017-12-28 18:42:33.151841 DatabaseExampleSwift[5470:409292] [] nw_host_stats_add_src received error for SRC_ADDED: [22] Invalid argument, dumping backtrace:
        [i386] libnetcore-856.30.16
    0   libsystem_network.dylib             0x04e3d14d __nw_create_backtrace_string + 123
    1   libsystem_network.dylib             0x04e54637 nw_get_host_stats + 1049
    2   libnetwork.dylib                    0x051be48e nw_endpoint_resolver_start_next_child + 1560
    3   libdispatch.dylib                   0x04bdb396 _dispatch_call_block_and_release + 15
    4   libdispatch.dylib                   0x04c06cc3 _dispatch_client_callout + 14
    5   libdispatch.dylib                   0x04be33ae _dispatch_queue_serial_drain + 1619
    6   libdispatch.dylib                   0x04be3bc2 _dispatch_queue_invoke + 1109
    7   libdispatch.dylib                   0x04be65e4 _dispatch_root_queue_drain + 470
    8   libdispatch.dylib                   0x04be63a6 _dispatch_worker_thread3 + 143
    9   libsystem_pthread.dylib             0x04f85fdc _pthread_wqthread + 1356
    10  libsystem_pthread.dylib             0x04f85a6a start_wqthread + 34
2017-12-28 18:42:33.497519 DatabaseExampleSwift[5470:409292] [] __nwlog_err_simulate_crash_libsystem libsystem simulate crash unavailable "libsystem_network.dylib: nw_host_stats_add_src :: received error for SRC_ADDED: [22] Invalid argument"
2017-12-28 18:42:33.498277 DatabaseExampleSwift[5470:409292] [] nw_host_stats_add_src received error for SRC_ADDED: [22] Invalid argument, dumping backtrace:
        [i386] libnetcore-856.30.16
    0   libsystem_network.dylib             0x04e3d14d __nw_create_backtrace_string + 123
    1   libsystem_network.dylib             0x04e54637 nw_get_host_stats + 1049
    2   libnetwork.dylib                    0x051be48e nw_endpoint_resolver_start_next_child + 1560
    3   libdispatch.dylib                   0x04bdb396 _dispatch_call_block_and_release + 15
    4   libdispatch.dylib                   0x04c06cc3 _dispatch_client_callout + 14
    5   libdispatch.dylib                   0x04be33ae _dispatch_queue_serial_drain + 1619
    6   libdispatch.dylib                   0x04be3bc2 _dispatch_queue_invoke + 1109
    7   libdispatch.dylib                   0x04be65e4 _dispatch_root_queue_drain + 470
    8   libdispatch.dylib                   0x04be63a6 _dispatch_worker_thread3 + 143
    9   libsystem_pthread.dylib             0x04f85fdc _pthread_wqthread + 1356
    10  libsystem_pthread.dylib             0x04f85a6a start_wqthread + 34
2017-12-28 18:42:33.686690 DatabaseExampleSwift[5470:409304] [] __nwlog_err_simulate_crash_libsystem libsystem simulate crash unavailable "libsystem_network.dylib: nw_host_stats_add_src :: received error for SRC_ADDED: [22] Invalid argument"
2017-12-28 18:42:33.687432 DatabaseExampleSwift[5470:409304] [] nw_host_stats_add_src received error for SRC_ADDED: [22] Invalid argument, dumping backtrace:
        [i386] libnetcore-856.30.16
    0   libsystem_network.dylib             0x04e3d14d __nw_create_backtrace_string + 123
    1   libsystem_network.dylib             0x04e54637 nw_get_host_stats + 1049
    2   libnetwork.dylib                    0x051be48e nw_endpoint_resolver_start_next_child + 1560
    3   libdispatch.dylib                   0x04bdb396 _dispatch_call_block_and_release + 15
    4   libdispatch.dylib                   0x04c06cc3 _dispatch_client_callout + 14
    5   libdispatch.dylib                   0x04be33ae _dispatch_queue_serial_drain + 1619
    6   libdispatch.dylib                   0x04be3bc2 _dispatch_queue_invoke + 1109
    7   libdispatch.dylib                   0x04be65e4 _dispatch_root_queue_drain + 470
    8   libdispatch.dylib                   0x04be63a6 _dispatch_worker_thread3 + 143
    9   libsystem_pthread.dylib             0x04f85fdc _pthread_wqthread + 1356
    10  libsystem_pthread.dylib             0x04f85a6a start_wqthread + 34
2017-12-28 18:42:33.955698 DatabaseExampleSwift[5470:409380] [] __nwlog_err_simulate_crash_libsystem libsystem simulate crash unavailable "libsystem_network.dylib: nw_host_stats_add_src :: received error for SRC_ADDED: [22] Invalid argument"
2017-12-28 18:42:33.956429 DatabaseExampleSwift[5470:409380] [] nw_host_stats_add_src received error for SRC_ADDED: [22] Invalid argument, dumping backtrace:
        [i386] libnetcore-856.30.16
    0   libsystem_network.dylib             0x04e3d14d __nw_create_backtrace_string + 123
    1   libsystem_network.dylib             0x04e54637 nw_get_host_stats + 1049
    2   libnetwork.dylib                    0x051be48e nw_endpoint_resolver_start_next_child + 1560
    3   libdispatch.dylib                   0x04bdb396 _dispatch_call_block_and_release + 15
    4   libdispatch.dylib                   0x04c06cc3 _dispatch_client_callout + 14
    5   libdispatch.dylib                   0x04be33ae _dispatch_queue_serial_drain + 1619
    6   libdispatch.dylib                   0x04be3bc2 _dispatch_queue_invoke + 1109
    7   libdispatch.dylib                   0x04be65e4 _dispatch_root_queue_drain + 470
    8   libdispatch.dylib                   0x04be63a6 _dispatch_worker_thread3 + 143
    9   libsystem_pthread.dylib             0x04f85fdc _pthread_wqthread + 1356
    10  libsystem_pthread.dylib             0x04f85a6a start_wqthread + 34
2017-12-28 18:42:34.418738 DatabaseExampleSwift[5470:409304] [] __nwlog_err_simulate_crash_libsystem libsystem simulate crash unavailable "libsystem_network.dylib: nw_host_stats_add_src :: received error for SRC_ADDED: [22] Invalid argument"
2017-12-28 18:42:34.419438 DatabaseExampleSwift[5470:409304] [] nw_host_stats_add_src received error for SRC_ADDED: [22] Invalid argument, dumping backtrace:
        [i386] libnetcore-856.30.16
    0   libsystem_network.dylib             0x04e3d14d __nw_create_backtrace_string + 123
    1   libsystem_network.dylib             0x04e54637 nw_get_host_stats + 1049
    2   libnetwork.dylib                    0x051be48e nw_endpoint_resolver_start_next_child + 1560
    3   libdispatch.dylib                   0x04bdb396 _dispatch_call_block_and_release + 15
    4   libdispatch.dylib                   0x04c06cc3 _dispatch_client_callout + 14
    5   libdispatch.dylib                   0x04be33ae _dispatch_queue_serial_drain + 1619
    6   libdispatch.dylib                   0x04be3bc2 _dispatch_queue_invoke + 1109
    7   libdispatch.dylib                   0x04be65e4 _dispatch_root_queue_drain + 470
    8   libdispatch.dylib                   0x04be63a6 _dispatch_worker_thread3 + 143
    9   libsystem_pthread.dylib             0x04f85fdc _pthread_wqthread + 1356
    10  libsystem_pthread.dylib             0x04f85a6a start_wqthread + 34

### [4]  Relevant Code:

Firebase.configure()
GADMobileAds.configure(...)

**Comment by paulb777** [comment]
@Alexeichua Please share the project via github or a zipfile

**Comment by Alexeichua** [comment]
[database.zip](https://github.com/firebase/firebase-ios-sdk/files/1591828/database.zip)

**Comment by paulb777** [comment]
Running the DatabaseExampleSwift scheme doesn't crash for me on an iOS 10.0 iPhone 6s Plus simulator.  We'll have to investigate more deeply to understand what's different about your configuration.

**Comment by Alexeichua** [comment]
This gives me a little positivity. I've tested on iPhone 6s iOS 10.3.1 and iPhone 5 iOS 10.2 simulators.

**Comment by paulb777** [comment]
iPhone 5 iOS 10.2 succeeds for me:
![screen shot 2017-12-28 at 3 53 40 pm](https://user-images.githubusercontent.com/73870/34426041-534fecc2-ebe7-11e7-8918-78dad1d19e35.png)

**Comment by paulb777** [comment]
Closing for now. Please reopen if more information about reproducibility can be provided.
