### ISSUE TITLE
[Carthage] Archive IPA processing failed

### ISSUE THREAD

**Issue by Bruce9487** [firebase/firebase-ios-sdk#6017]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.1
  * Firebase SDK version:  6.27.0
  * Firebase Component:  like following pic
<img width="784" alt="截圖 2020-07-10 14 03 26" src="https://user-images.githubusercontent.com/19691907/87121786-2b07f680-c2b6-11ea-8f9f-61c82deb1da5.png">
  * Component version: 6.27.0
  * Installation method: Carthage

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

I got `IPA processing failed` when I archive the app.<br>

And check the log like this:

```
Scanning IPA...
2020-07-10 03:17:26 +0000  Assertion failed: Expected 1 archs in otool output:
Archive : /var/folders/ts/r7b0ghfd3z93gnb_1rdny8f1b70xc1/T/IDEDistributionOptionThinning.~~~k4I40G/Payload/TestFirebaseCrashlytics.app/Frameworks/FirebaseCore.framework/FirebaseCore
/var/folders/ts/r7b0ghfd3z93gnb_1rdny8f1b70xc1/T/IDEDistributionOptionThinning.~~~k4I40G/Payload/TestFirebaseCrashlytics.app/Frameworks/FirebaseCore.framework/FirebaseCore(FIRAnalyticsConfiguration.o):
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64   ARM64        ALL  0x00      OBJECT     5       1568 SUBSECTIONS_VIA_SYMBOLS
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 1432
  segname 
   vmaddr 0x0000000000000000
   vmsize 0x00000000000047f0
  fileoff 1600
 filesize 18400
  maxprot rwx
 initprot rwx
   nsects 17
    flags (none)
Section
  sectname __text
   segname __TEXT
      addr 0x0000000000000000
      size 0x00000000000002a4
    offset 1600
     align 2^2 (4)
    reloff 20000
    nreloc 86
      type S_REGULAR
attributes PURE_INSTRUCTIONS SOME_INSTRUCTIONS
 reserved1 0
 reserved2 0
Section
  sectname __cstring
   segname __TEXT
      addr 0x00000000000002a4
      size 0x0000000000000064
    offset 2276
     align 2^0 (1)
    reloff 0
    nreloc 0
      type S_CSTRING_LITERALS
attributes (none)
 reserved1 0
 reserved2 0
Section
```

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

Here is sample proj : https://github.com/Bruce9487/TestFirebaseCrashlytics

#### Relevant Code:

I try to add shell script like this

```
APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"

# This script loops through the frameworks embedded in the application and
# removes unused architectures.
find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
do
FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"

EXTRACTED_ARCHS=()

for ARCH in $ARCHS
do
echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
done

echo "Merging extracted architectures: ${ARCHS}"
lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"
rm "${EXTRACTED_ARCHS[@]}"

echo "Replacing original executable with thinned version"
rm "$FRAMEWORK_EXECUTABLE_PATH"
mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"

done
```

**Comment by paulb777** [comment]
@Bruce9487 Thanks for the report and the sample.

However, I'm not able to reproduce. I successfully archive the project with both Xcode 12 and Xcode 11.0:

![Screen Shot 2020-07-10 at 7 48 32 AM](https://user-images.githubusercontent.com/73870/87167467-d8ace280-c281-11ea-8715-23c5bd69ef7a.png)

**Comment by Bruce9487** [comment]
@paulb777 Thanks. So, do you success to produce the ipa? 
OMG, That's wired.

**Comment by morganchen12** [comment]
If you click the "Show logs" button, is there a more complete error?

**Comment by Bruce9487** [comment]
@morganchen12  I see the file `IDEDistribution.standard.log`

And here is the log: 
https://gist.github.com/Bruce9487/cf5e3804d05ca9426f203312ae602d40

**Comment by morganchen12** [comment]
Looks like this is the relevant error from the log:
```
2020-07-14 06:34:17 +0000  Assertion failed: Expected 1 archs in otool output:
Archive : /var/folders/ts/r7b0ghfd3z93gnb_1rdny8f1b70xc1/T/IDEDistributionOptionThinning.~~~VE3DDn/Payload/TestFirebaseCrashlytics.app/Frameworks/FirebaseCore.framework/FirebaseCore
/var/folders/ts/r7b0ghfd3z93gnb_1rdny8f1b70xc1/T/IDEDistributionOptionThinning.~~~VE3DDn/Payload/TestFirebaseCrashlytics.app/Frameworks/FirebaseCore.framework/FirebaseCore(FIRAnalyticsConfiguration.o):
```
Are you copying the Carthage frameworks into your app bundle? If so, you should avoid copying the frameworks into your app bundle. They will be linked statically into your app binary and do not need to be present in the app bundle.

**Comment by Bruce9487** [comment]
@morganchen12 So, do I need to change the "Emded & Sign" to "Do Not Embed" ?

![截圖 2020-07-17 15 15 18](https://user-images.githubusercontent.com/19691907/87759131-56538e00-c840-11ea-87da-db055fa37ada.png)

**Comment by morganchen12** [comment]
Yes, the Firebase frameworks should all be "Do Not Embed". Sub-dependencies like nanopb and GoogleUtilities should still be "Embed & Sign".

**Comment by paulb777** [comment]
Going to close now based on the answer from @morganchen12. We can reopen if there's still an issue.

**Comment by Bruce9487** [comment]
@morganchen12 @paulb777 Thanks. It's work. I figure out my question.
