### ISSUE TITLE
semantic issue in google datatransport file

### ISSUE THREAD

**Issue by kumareshsaran** [firebase/firebase-ios-sdk#6018]
### Step 0: Are you in the right place?

Hi Facing some issues in GDTCORStorage.m file pod in after installing the pod 'Firebase/Crashlytics' and pod 'Firebase/Analytics'

Below I attached the screen shot for your reference. Thanks in advance
<img width="1187" alt="Screenshot 2020-07-10 at 3 54 56 PM" src="https://user-images.githubusercontent.com/20902842/87145941-cf466900-c2c7-11ea-84b0-a2d5519a1a5b.png">

Here I attached my pod file.lock
`PODS:
  - AFNetworking (3.2.1):
    - AFNetworking/NSURLSession (= 3.2.1)
    - AFNetworking/Reachability (= 3.2.1)
    - AFNetworking/Security (= 3.2.1)
    - AFNetworking/Serialization (= 3.2.1)
    - AFNetworking/UIKit (= 3.2.1)
  - AFNetworking/NSURLSession (3.2.1):
    - AFNetworking/Reachability
    - AFNetworking/Security
    - AFNetworking/Serialization
  - AFNetworking/Reachability (3.2.1)
  - AFNetworking/Security (3.2.1)
  - AFNetworking/Serialization (3.2.1)
  - AFNetworking/UIKit (3.2.1):
    - AFNetworking/NSURLSession
  - Alamofire (4.8.2)
  - AppAuth (1.4.0):
    - AppAuth/Core (= 1.4.0)
    - AppAuth/ExternalUserAgent (= 1.4.0)
  - AppAuth/Core (1.4.0)
  - AppAuth/ExternalUserAgent (1.4.0)
  - AWSCognito (2.4.16):
    - AWSCore (= 2.4.16)
  - AWSCognitoIdentityProvider (2.4.16):
    - AWSCore (= 2.4.16)
  - AWSCore (2.4.16)
  - AWSLambda (2.4.16):
    - AWSCore (= 2.4.16)
  - AWSS3 (2.4.16):
    - AWSCore (= 2.4.16)
  - AWSSNS (2.4.16):
    - AWSCore (= 2.4.16)
  - BFTask-Extras (1.7.5):
    - Bolts/Tasks
  - Bolts/Tasks (1.9.0)
  - Crashlytics (3.12.0):
    - Fabric (~> 1.9.0)
  - CryptoSwift (1.0.0)
  - ESPullToRefresh (2.9)
  - Fabric (1.9.0)
  - FacebookCore (0.9.0):
    - FBSDKCoreKit (~> 5.0)
  - FacebookLogin (0.9.0):
    - FacebookCore (~> 0.9.0)
    - FBSDKCoreKit (~> 5.0)
    - FBSDKLoginKit (~> 5.0)
  - FBSDKCoreKit (5.15.1):
    - FBSDKCoreKit/Basics (= 5.15.1)
    - FBSDKCoreKit/Core (= 5.15.1)
  - FBSDKCoreKit/Basics (5.15.1)
  - FBSDKCoreKit/Core (5.15.1):
    - FBSDKCoreKit/Basics
  - FBSDKLoginKit (5.15.1):
    - FBSDKLoginKit/Login (= 5.15.1)
  - FBSDKLoginKit/Login (5.15.1):
    - FBSDKCoreKit (~> 5.0)
  - FBSDKShareKit (5.15.1):
    - FBSDKShareKit/Share (= 5.15.1)
  - FBSDKShareKit/Share (5.15.1):
    - FBSDKCoreKit (~> 5.0)
  - Firebase/Analytics (6.27.1):
    - Firebase/Core
  - Firebase/Core (6.27.1):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.6.2)
  - Firebase/CoreOnly (6.27.1):
    - FirebaseCore (= 6.8.1)
  - Firebase/Crashlytics (6.27.1):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 4.2.0)
  - Firebase/Performance (6.27.1):
    - Firebase/CoreOnly
    - FirebasePerformance (~> 3.1.11)
  - Firebase/RemoteConfig (6.27.1):
    - Firebase/CoreOnly
    - FirebaseRemoteConfig (~> 4.6.0)
  - FirebaseABTesting (3.3.0):
    - FirebaseCore (~> 6.8)
    - Protobuf (>= 3.9.2, ~> 3.9)
  - FirebaseAnalytics (6.6.2):
    - FirebaseCore (~> 6.8)
    - FirebaseInstallations (~> 1.4)
    - GoogleAppMeasurement (= 6.6.2)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 1.30905.0)
  - FirebaseCore (6.8.1):
    - FirebaseCoreDiagnostics (~> 1.3)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
  - FirebaseCoreDiagnostics (1.4.0):
    - GoogleDataTransportCCTSupport (~> 3.1)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
    - nanopb (~> 1.30905.0)
  - FirebaseCrashlytics (4.2.0):
    - FirebaseCore (~> 6.8)
    - FirebaseInstallations (~> 1.1)
    - GoogleDataTransport (~> 6.1)
    - GoogleDataTransportCCTSupport (~> 3.1)
    - nanopb (~> 1.30905.0)
    - PromisesObjC (~> 1.2)
  - FirebaseInstallations (1.4.0):
    - FirebaseCore (~> 6.8)
    - GoogleUtilities/Environment (~> 6.6)
    - GoogleUtilities/UserDefaults (~> 6.6)
    - PromisesObjC (~> 1.2)
  - FirebasePerformance (3.1.11):
    - FirebaseCore (~> 6.6)
    - FirebaseInstallations (~> 1.1)
    - FirebaseRemoteConfig (~> 4.4)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/ISASwizzler (~> 6.2)
    - GoogleUtilities/MethodSwizzler (~> 6.2)
    - GTMSessionFetcher/Core (~> 1.1)
    - Protobuf (~> 3.9)
  - FirebaseRemoteConfig (4.6.0):
    - FirebaseABTesting (~> 3.1)
    - FirebaseCore (~> 6.8)
    - FirebaseInstallations (~> 1.1)
    - GoogleUtilities/Environment (~> 6.2)
    - "GoogleUtilities/NSData+zlib (~> 6.2)"
  - FittedSheets (1.4.1)
  - GoogleAppMeasurement (6.6.2):
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 1.30905.0)
  - GoogleDataTransport (6.2.1)
  - GoogleDataTransportCCTSupport (3.2.0):
    - GoogleDataTransport (~> 6.1)
    - nanopb (~> 1.30905.0)
  - GoogleMaps/Base (3.9.0)
  - GooglePlaces (3.9.0):
    - GoogleMaps/Base (= 3.9.0)
  - GoogleSignIn (5.0.2):
    - AppAuth (~> 1.2)
    - GTMAppAuth (~> 1.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - GoogleToolboxForMac/Defines (2.2.2)
  - GoogleToolboxForMac/Logger (2.2.2):
    - GoogleToolboxForMac/Defines (= 2.2.2)
  - "GoogleToolboxForMac/NSData+zlib (2.2.2)":
    - GoogleToolboxForMac/Defines (= 2.2.2)
  - GoogleUtilities/AppDelegateSwizzler (6.6.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (6.6.0):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/ISASwizzler (6.6.0)
  - GoogleUtilities/Logger (6.6.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (6.6.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (6.6.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (6.6.0)"
  - GoogleUtilities/Reachability (6.6.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (6.6.0):
    - GoogleUtilities/Logger
  - GTMAppAuth (1.0.0):
    - AppAuth/Core (~> 1.0)
    - GTMSessionFetcher (~> 1.1)
  - GTMSessionFetcher (1.4.0):
    - GTMSessionFetcher/Full (= 1.4.0)
  - GTMSessionFetcher/Core (1.4.0)
  - GTMSessionFetcher/Full (1.4.0):
    - GTMSessionFetcher/Core (= 1.4.0)
  - JSONKit (1.4)
  - Mantle (2.1.0):
    - Mantle/extobjc (= 2.1.0)
  - Mantle/extobjc (2.1.0)
  - MBProgressHUD (1.1.0)
  - nanopb (1.30905.0):
    - nanopb/decode (= 1.30905.0)
    - nanopb/encode (= 1.30905.0)
  - nanopb/decode (1.30905.0)
  - nanopb/encode (1.30905.0)
  - OpenCV (3.3.1)
  - PromisesObjC (1.2.9)
  - Protobuf (3.12.0)
  - RSMasterTableViewKit (1.2)
  - Starscream (4.0.3)
  - Stripe (15.0.2)
  - SwiftRater (1.5.0)
  - SwiftyJSON (5.0.0)
  - TLPhotoPicker (2.0.11)
  - TwitterCore (3.2.0)
  - TwitterKit (3.4.2):
    - TwitterCore (>= 3.2.0)`

### [REQUIRED] Step 1: Describe your environment

  * Xcode version:  11.4.1
  * Firebase SDK version: 
  * Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: _____
  * Installation method: `CocoaPods

**Comment by maksymmalyhin** [comment]
@kumareshsaran I'm sorry you experience the issue. The set of errors looks pretty weird. First thing I would suggest to try is to make sure the pods were installed correctly. E.g. you may run `pod deintegrate` and `pod install` to reinstall all dependencies in your project. If you still have an issue, please provide a simple project to reproduce the issue (you may attach a zip archive to a comment) for us to investigate.

**Comment by kumareshsaran** [comment]
Hi tried above you mentioned. Now I am facing new issue

<img width="1147" alt="Screenshot 2020-07-13 at 10 59 15 AM" src="https://user-images.githubusercontent.com/20902842/87273952-12871e80-c4f8-11ea-8ea7-d4c0dde02b80.png">

 `Property 'customPrioritizationParams' not found on object of type 'GDTCOREvent *'`

**Comment by morganchen12** [comment]
You have some very weird errors in the left panel of Xcode. Can you try deleting DerivedData and rebuilding?

```
$ rm -rf ~/Library/Developer/Xcode/DerivedData
```

**Comment by kumareshsaran** [comment]
Hi I tried that also but it is not clearing the bug.please provide some fixes.  Thanks in advance

**Comment by morganchen12** [comment]
I'm unable to reproduce the build error locally, nor does it occur in any of our automated build systems. Can you create a new sample project and try to reproduce the build error there?
