### ISSUE TITLE
Carthage firebase, minimal used framework to use in device mobile text recognition and face detection

### ISSUE THREAD

**Issue by soufianee** [firebase/firebase-ios-sdk#6019]
Hi,

I download the firebase iOS framework fo mobile text recognition and face face detection using carthage.

it download a lot of others frameworks more than 40. unfortunately this makes my app size grow. can you help me with the minimal configuration to run in device text recognition and face detection.

**Comment by maksymmalyhin** [comment]
@soufianee You can try the following set:
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseMLVisionBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseMLVisionTextModelBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseMLVisionFaceModelBinary.json"
```

`binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"` contains core Firebase components required for Firebase to work. If you are not going to use Analytics, you may skip copying frameworks like `GoogleAppMeasurement.framework`, `FirebaseAnalytics.framework`, `FirebaseCoreDiagnostics.framework` to you project to save some space.

Please let us know if it is helpful.

**Comment by soufianee** [comment]
thank you for your response,

I try your solution, still get this errors 

<img width="467" alt="Capture d’écran 2020-07-10 à 20 32 54" src="https://user-images.githubusercontent.com/11293769/87191581-a1bfe680-c2ec-11ea-9f40-b68d21f71820.png">

here is the list of imported frameworks 

<img width="542" alt="Capture d’écran 2020-07-10 à 20 33 17" src="https://user-images.githubusercontent.com/11293769/87191637-b8fed400-c2ec-11ea-9a51-78f3aec246ca.png">


any idea please.

**Comment by soufianee** [comment]
also 
i have i delete the FIRAnalyticsConnector.framework. and still get this error and warnings 

<img width="426" alt="Capture d’écran 2020-07-10 à 20 38 47" src="https://user-images.githubusercontent.com/11293769/87192302-18a9af00-c2ee-11ea-828e-e5b9d93d13ef.png">

**Comment by morganchen12** [comment]
@soufianee what version of the Firebase frameworks are you using? FIRAEvent is a very old class that was renamed a while ago, so the symbols won't exist in the latest Firebase Analytics Carthage distribution.

**Comment by soufianee** [comment]
hi,

fine build working now with the 6.27.0 version.

but I get this erreur in text extraction.

-[GMVTextDetector initWith:size:angle:]: unrecognized selector sent to instance 0x60000112e040

any idea.

**Comment by morganchen12** [comment]
Can you share the full stack trace?

**Comment by soufianee** [comment]
hi,

here is the console trace 

<img width="380" alt="Capture d’écran 2020-07-13 à 18 40 31" src="https://user-images.githubusercontent.com/11293769/87335582-75000f00-c538-11ea-9b95-d22a2e6bf3dd.png">

**Comment by morganchen12** [comment]
It looks like you may have duplicate class definitions in your app's runtime, based on the multiple Clearcut warning log. Can you confirm if this is the case? If so, you should remove those as they can cause undefined behavior at runtime.
