### ISSUE TITLE
Database DataEventType.ChildChanged does not retrieve whole child

### ISSUE THREAD

**Issue by ggaabe** [firebase/firebase-ios-sdk#602]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.2
  * Firebase SDK version: 4.4.0
  * Firebase Component: Database
  * Component version: 4.1.1

### [REQUIRED] Step 3: Describe the problem
When a path is observed for ChildChanged events, it does not retrieve the whole data snapshot that's being observed. For instance, if I observe a path at: "/stores" for ChildChanged events, and a dictionary is inserted at "/stores/addresses/messages/new", the retrieved snapshot will only contain "messages/new" and downward.

Observing the path at "stores" .value once though, will retrieve the whole snapshot down.

#### Steps to reproduce:
What happened? How can we make the problem occur?

Create a database with data 4 levels deep. Observe for ChildChanged events at the top level. Make an insertion at the deepest level, and then print the snapshot that's obtained. It will only have levels 3 and 4 of your database

#### Relevant Code:
```
 Database.database().reference(withPath: "/stores").observe(DataEventType.childChanged, with: { (snapshot) in
            print("Data Updated")

            print(snapshot.value as! NSDictionary)
        }){ (error) in
            print(error.localizedDescription)
        }
```

**Comment by quanvo87** [comment]
I think I am seeing the same issue. However this may be intended behavior. Programming around this has been a little tricky.

**Comment by schmidt-sebastian** [comment]
`child_changed` events will point to the `DataSnapshot` that changed. They are explicitly not meant to fire for the entire tree and instead allow you to gradually extract and apply changes as they happen in your data tree. While it would be possible to also return the whole dataset , the  `DataSnapshot` contains the key of the value that has changed and provides the data that most applications need.
