### ISSUE TITLE
161728260: If FirebaseDynamicLinks.xcframework is linked, an error pops up on Mac Catalyst app

### ISSUE THREAD

**Issue by hohteri** [firebase/firebase-ios-sdk#6027]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.5
  * Firebase SDK version: 6.27.1
  * Firebase Component: DynamicLinks
  * Component version: 
  * Installation method: `Zip file`

### [REQUIRED] Step 2: Describe the problem

Link Mac Catalyst app to FirebaseDynamicLinks.xcframework

#### Steps to reproduce:

What happened? How can we make the problem occur?

On app launch an pop up shows up "There is no application set to open the URL <your bundle id here>://google/link/?dismiss=1&is_weak_match=1."

**Comment by hohteri** [comment]
If my analysis is correct, this link is generated when checking for pending dynamic links at app start up. The FDL code elsewhere expects dismiss URL to be of format "/link/dismiss" but (like in FDLUtilities#FIRDLMatchesShortLinkFormat, FIRDynamicLinks#shouldHandleDynamicLinkFromCustomSchemeURL) but is created by FIRDLRetrievalProcessResult as "://google/link/?dismiss=1&is_weak_match=1" which then isn't dismissed due to path mismatch. If I've assumed correctly, the fix could be as simple as fixing the URL in FIRDLRetrievalProcessResult to be "://google/link/dismiss?is_weak_match=1"

**Comment by paulb777** [comment]
Hi @hohteri DynamicLinks is not in the list of community supported Catalyst pods at https://github.com/firebase/firebase-ios-sdk#tvos-macos-watchos-and-catalyst.  

Assuming nothing fundamental is needed on the backend, we would definitely consider a PR to add SDK support.

**Comment by hohteri** [comment]
Hi @paulb777, I didn’t notice that. I use the official zip distribution, so I think it ‘just works’. I can verify later that there is indeed the mac catalyst framework inside the xcframework but I would have expected a linker error if that would not be the case.

**Comment by hohteri** [comment]
`macpro:~ hohteri$ ls -l Library/Developer/Firebase/FirebaseDynamicLinks/FirebaseDynamicLinks.xcframework/
Info.plist                 ios-armv7_arm64/           ios-i386_x86_64-simulator/ ios-x86_64-maccatalyst/ `

**Comment by paulb777** [comment]
Thanks @hohteri. We'll see if we can make the documentation about the Catalyst level of support clearer.

**Comment by hohteri** [comment]
No problem @paulb777. Do you guys want me to do the proposed change and do a PR? To me it seems an oversight but I do not have any insight to the purpose of the dismiss parameter so I would appreciate someone in knowledge of the FDL framework to provide input if that is in fact an oversight.

**Comment by paulb777** [comment]
@eldhosembabu Will you answer the question about the dismiss parameter and answer any other questions about the feasibility of a PR for Catalyst support?

**Comment by eldhosembabu** [comment]
I'm on it..will get back with answers soon

**Comment by hohteri** [comment]
Just wanted to check what is the status on this, thanks.

**Comment by aleclarson** [comment]
@paulb777 Could you ask the Dynamic Links backend team if any fundamental backend changes would be necessary to support Catalyst (or in my case, macOS w/o Catalyst)? I'm in the process of adding macOS support to Dynamic Links, and guidance on that front would be very appreciated.

**Comment by paulb777** [comment]
@eldhosembabu ping

**Comment by hohteri** [comment]
An update:

With Firebase 7.x.0, the original issue doesn't show up anymore. Also my primary goal was to use email link login and for some reason iOS recognises email link as a Dynamic Link and Catalyst doesn't. Current examples don't implicate that dynamic link validation is required for sign-in links: `DynamicLinks.dynamicLinks().handleUniversalLink`.

If you proceed as the current examples demonstrate and do only `Auth.auth().isSignIn` you are able to successfully validate the link and sign in.

Now, because dynamic links don't support macOS / Catalyst directly, you need to perform a few tricks to get email link auth working on macOS. As explained in [this video ](https://developer.apple.com/videos/play/wwdc2019/717/), macOS doesn't open universal links directly in the app as iOS does. Instead it requires the user to click on a Smart App Banner. The behaviour of Smart App Banner for Universal Links is [not well documented](https://developer.apple.com/forums/thread/105129?answerId=639849022#639849022) but it doesn't survive the redirect done by Dynamic Links and there is no known way to prompt that behaviour even if you'd use your app link domain as the continue url.

You can still achieve this by creating a duplicate Firebase Hosting site, assigning it as authentication and Dynamic Links domain, once done you need to modify the rewrite header to remove the dynamicLinks property to prevent Firebase from redirecting. Host a nice page explaining the user what to do, and you can serve both iOS and Catalyst users with a compilation conditional (swift) or preprocessor directive (objc)

`#if TARGET_OS_MACCATALYST
    [settings setDynamicLinkDomain:@"catalyst.domain"];
#else
    [settings setDynamicLinkDomain:@"ios.domain"];
#endif` 

From my side this issue can be closed.

**Comment by eldhosembabu** [comment]
Closing this issue since Firebase dynamic links doesn't support catalyst.
