### ISSUE TITLE
Unable to add Firebase using SPM

### ISSUE THREAD

**Issue by danishgct** [firebase/firebase-ios-sdk#6030]
<img width="1440" alt="Screenshot 2020-07-12 at 11 58 27 AM" src="https://user-images.githubusercontent.com/68178862/87240423-20289f80-c437-11ea-966f-6c2b65942632.png">

### [REQUIRED] Step 1: Create a new project using XCode.

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.26.0
  * Firebase Component: All
  * Component version: 6.26.0
  * Installation method: Swift Package Manager

#### Steps to reproduce:

1. Create a new project.
2. Go to 'File' -> 'Swift Packages' -> 'Add Package Dependency'
3. Add URL of SDK as "https://github.com/firebase/firebase-ios-sdk"
4. After verification version selected as "6.26.0"
5. Package resolution failed with error as "https://github.com/firebase/firebase-ios-sdk has no Package.swift manifest for version 6.26.0".
[Firebase_Demo.zip](https://github.com/firebase/firebase-ios-sdk/files/4908121/Firebase_Demo.zip)

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulb777** [comment]
Firebase does not yet support Swift Package Manager.  Details in the feature request at #3136.  

Implementation is in progress and you can track project details at https://github.com/firebase/firebase-ios-sdk/projects and try out development versions by specifying the `master` branch when adding the Swift package to the project.

**Comment by danishgct** [comment]
Thanks 👍
