### ISSUE TITLE
FR: Add native Snap Kit integration to Firebase Auth

### ISSUE THREAD

**Issue by nhurwitz** [firebase/firebase-ios-sdk#6046]
### Feature proposal

* Firebase Component: Auth

Describe your use case and/or feature request here.
Auth currently supports many identity solutions with different platforms. Snap Kit (https://kit.snapchat.com/) is a hugely popular platform and it would be great to have native, out-of-the-box support for login via Snap through Firebase.

**Comment by ryanwilson** [comment]
Thanks for the request, @nhurwitz. We have an open issue already tracking this (https://github.com/firebase/firebase-ios-sdk/issues/3195), so I'm going to close this one in favour of it. Please add a thumbs up reaction to the original issue so we can better track how many people are interested in the feature. Thanks!
