### ISSUE TITLE
Use of unresolved identifier 'FirebaseApp'

### ISSUE THREAD

**Issue by nguyencongthienvu** [firebase/firebase-ios-sdk#6056]
[REQUIRED] Step 1: Describe your environment

Xcode version: 11.5
Firebase SDK version: 6.28.1
Firebase Component: FirebaseApp config
Installation method: CocoaPods

[REQUIRED] Step 2: Describe the problem
Steps to reproduce:
Hi, I just update firebase v6.28.0 to v6.28.1, when update finish and build it said "Use of unresolved identifier 'FirebaseApp' ", and when I revert back to v6.28.0 it's normal. Do you know why ?

**Comment by nguyencongthienvu** [comment]
It has been resolved by import FirebaseCore.

**Comment by quickjeff** [comment]
Was literally having the same issue and scratching my head. Thanks @nguyencongthienvu

**Comment by sudhakar-varma** [comment]
@nguyencongthienvu Thanks

**Comment by paulb777** [comment]
Duplicate of #6066

**Comment by stanfeldman** [comment]
Could you please update the documentation at https://firebase.google.com/docs/crashlytics/get-started?platform=ios because it says `import Firebase` which is misleading?

**Comment by paulb777** [comment]
@stanfeldman `import Firebase` should still work and is supported. See the ongoing issue at #6066.

**Comment by nguyencongthienvu** [comment]
> Could you please update the documentation at https://firebase.google.com/docs/crashlytics/get-started?platform=ios because it says `import Firebase` which is misleading?

![Screen Shot 2020-07-22 at 9 51 01 AM](https://user-images.githubusercontent.com/38414692/88128908-0d655600-cc01-11ea-9006-65fef7e77a20.png)
![Screen Shot 2020-07-22 at 9 50 38 AM](https://user-images.githubusercontent.com/38414692/88128917-10f8dd00-cc01-11ea-9f69-3c31c04f84f7.png)
![Screen Shot 2020-07-22 at 9 50 28 AM](https://user-images.githubusercontent.com/38414692/88128919-11917380-cc01-11ea-8371-7dcfa90a006f.png)

**Comment by netgfx** [comment]
Please update documentation `Auth` also has the same issue until you `import FirebaseAuth` and `import FirebaseCore`

**Comment by rastorgaespinoza** [comment]
Hi all. I'm still in trouble from last week. I have tried what sdnetwork specifies, and it only works at few times. It mainly fails when working with a physical device. With the simulator it compiles well.

Firebase installed pods:
pod 'Firebase/Analytics'
pod 'Firebase/DynamicLinks'
pod 'Firebase/Crashlytics'
pod 'Firebase/Messaging'
pod 'Firebase/RemoteConfig'

log from pod install:
Installing Firebase (6.28.1)
Installing FirebaseABTesting (4.0.0)
Installing FirebaseAnalytics (6.6.2)
Installing FirebaseCore (6.9.1)
Installing FirebaseCoreDiagnostics (1.5.0)
Installing FirebaseCrashlytics (4.3.0)
Installing FirebaseDynamicLinks (4.2.0)
Installing FirebaseInstallations (1.5.0)
Installing FirebaseInstanceID (4.5.0)
Installing FirebaseMessaging (4.6.0)
Installing FirebaseRemoteConfig (4.7.0)

XCode version: 11.6
physical device: iPhone 11 Pro iOS 13.6
CocoaPod version: 1.8.4
MacOS Catalina version: 10.15.6

<img width="1288" alt="Captura de Pantalla 2020-07-28 a la(s) 10 41 01" src="https://user-images.githubusercontent.com/8573796/88683843-3fbff900-d0c2-11ea-92a7-6121f81c8762.png">

**Comment by netgfx** [comment]
@rastorgaespinoza for `FirebaseApp` use `import FirebaseCore` and I would assume for `Messaging` do `import FirebaseMessaging`

**Comment by uncvrd** [comment]
Just ran in to this issue myself when setting up `Firebase Dynamic Links`. It worked fine until I did a `Clean Build Folder` under `Product` tab in XCode...then for some reason I had to use `FirebaseCore` to initialize and then import `FirebaseDynamicLinks` for the Dynamic Links code. Anyone else have this type of scenario? I'd prefer to just `import Firebase` link the instructions say here: https://firebase.google.com/docs/ios/setup#analytics-enabled

**Comment by monsieurpooh** [comment]
no such module FirebaseCore

**Comment by ivanJovanovik** [comment]
No such module 'FirebaseAuth'

**Comment by paulb777** [comment]
See the resolution at https://github.com/firebase/firebase-ios-sdk/issues/6066#issuecomment-662580211. If that still doesn't work, we'll need a reproducible example to help with this issue.
