### ISSUE TITLE
import Firebase no longer works

### ISSUE THREAD

**Issue by Marcin951** [firebase/firebase-ios-sdk#6066]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0 beta 2
  * Firebase SDK version: 6.28.1
  * Firebase Component: Whole Firebase framework (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 6.28.1
  * Installation method: `CocoaPods` (select one)

#### Steps to reproduce:
Just install firebase with some components like functions and firestore, then try to use firestore/functions with imported Firesbase.

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
After the update, importing Firebase in not enough to use firestore/auth/functions, it looks like import Firebase now do nothing

![Zrzut ekranu 2020-07-17 o 14 32 20](https://user-images.githubusercontent.com/31135444/87786530-581a5300-c83a-11ea-88ae-6c34cb7c4807.png)

But after remove import firebase, and add import for each component then it works 
![Zrzut ekranu 2020-07-17 o 14 33 24](https://user-images.githubusercontent.com/31135444/87786594-7d0ec600-c83a-11ea-880b-d57516f65360.png)

That is a planned change or bug?

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
import Fireabse
let functions = Functions.functions() // this case doesn't work

////
import FirebaseFunctions
let functions = Functions.functions() // this one works

so it looks like the `import Firebase` is useless since new update right?
```

**Comment by ryanwilson** [comment]
Hi @Marcin951 - that certainly shouldn't be the case. In some cases I've seen this where Xcode is in a bad state - can you try a clean build, cleaning derived data, and re-launching Xcode?

Does this happen on the Xcode 12 beta 2 only, or also with Xcode 11? Just trying to figure out if this is a new issue related to the beta or something else going on.

If the above doesn't work, it's likely also worth trying to clean the CocoaPods folder and try rebuilding again.

**Comment by Marcin951** [comment]
Ya, I did it. I deleted the cocoa pods folder/cache and I did deinit cocoa pods. I deleted the derived data, cache and I cleaned the build. I tried a couple of times to build the project after clean build and always had the same issue. It looks like something went wrong in the latest version of the firebase. I also know that issue when sometimes Xcode can't detect firebase but always rebuild helps, so that definitely is the another issue

**Comment by paulb777** [comment]
Are you able to reproduce in a [quickstart sample](https://github.com/firebase/quickstart-ios)?

**Comment by pepejeria** [comment]
Not sure if related, but I am having similar issues since I updated to last version (6.28.1) using Cocoapods.

I tried removing derived data, cleaning and building. 

<img width="1035" alt="Screen Shot 2020-07-17 at 18 58 38" src="https://user-images.githubusercontent.com/1394550/87811859-983ffc80-c85f-11ea-8970-c7ed9f0ace9b.png">

**Comment by pepejeria** [comment]
Using `import FirebaseDatabase` fixes the issue. Is this a bug or expected behavior?

**Comment by Marcin951** [comment]
> Using `import FirebaseDatabase` fixes the issue. Is this a bug or expected behavior?

I'm pretty sure that is a bug, if they didn't mark it as change in the changelogs.
Tomorrow I'll create a brand new project to check if that is 100% issue

**Comment by paulb777** [comment]
It would be a bug, but it doesn't repro in our tests, so we'll like need a reproducible example to diagnose.

**Comment by Ihernandezpi** [comment]
I had the same issue with xcode 11.6,  and is not the only library that is broken. In fact AFNetworking, but it works importing extra modules like `import FirebaseDatabase`

**Comment by Marcin951** [comment]
![Zrzut ekranu 2020-07-20 o 13 17 42](https://user-images.githubusercontent.com/31135444/87932231-7460fe80-ca8b-11ea-9657-72625fe706f6.png)
Sample projects don't work, ofc i tried with cleaning build etc

**Comment by Marcin951** [comment]
on a brand new project, it looks like working 
![Zrzut ekranu 2020-07-20 o 13 26 30](https://user-images.githubusercontent.com/31135444/87932947-a757c200-ca8c-11ea-8606-1b56fa88da33.png)
But I don't know why, I also reinstalled pods on my main project, any clue? Cause bunch of developers has that issue

**Comment by Marcin951** [comment]
maybe I can run unit tests in any way on my project?

**Comment by sdnetwork** [comment]
Same behaviour, Xcode Version 11.5 (11E608c).

need to import FirebaseCore otherwise FirebaseApp is not defined

**Comment by Marcin951** [comment]
@paulb777 @ryanwilson How is going investigation? Can I help in any way?

**Comment by adriano-s** [comment]
Having the same issue as well with Xcode 12 / Firebase SDK version: 6.28.1 / Cocoapods

It works with Xcode 11.6, and it also works again with Xcode 12 if I add specific imports (the one's that are commented out here). 
![FirebaseIssue6066](https://user-images.githubusercontent.com/1815049/88055960-17834800-cb60-11ea-98d1-653c2c762ab8.png)

**Comment by paulb777** [comment]
@Marcin951 and others We still haven't been able to reproduce, so it would be really helpful to share an example that demonstrates the issue.

The other option would be to track down what is different about a working and broken environment.  Perhaps, diff'ing the Pods directory would provide some clues ...

**Comment by piobyz** [comment]
I have related issue with FirebaseCrashlytics.
I've installed it w/o Cocoapods, as described at https://firebase.google.com/docs/ios/setup#frameworks (including steps for  Firebase.h and module.modulemap)
Then, I followed instructions to upgrade from Fabric to FirebaseCrashlytics at https://firebase.google.com/docs/crashlytics/upgrade-sdk?platform=ios

import FirebaseCrashlytics and FirebaseApp.configure() resulted in "Use of unresolved identifier 'FirebaseApp'".

**Comment by sdnetwork** [comment]
i have fixed the problem :

1) close xcode
2) removing Pods directory
3) removing xcworkspace directory
4) launch pod install again
5) open myproject.xcworkspace

i suspect that during my first pod install xcode was open

**Comment by Marcin951** [comment]
Oh okay then if that is solved I can close the issue!

**Comment by Dfmarulanda** [comment]
Got unresolved identifier FirebaseApp; XCODE 11.6. Had to import FirebaseCrashlytics directly.

**Comment by paulb777** [comment]
See the resolution [above](https://github.com/firebase/firebase-ios-sdk/issues/6066#issuecomment-662580211). If that still doesn't work, we'll need a reproducible example to help with this issue.
