### ISSUE TITLE
GoogleDataTransportCCTSupport removed after update

### ISSUE THREAD

**Issue by mrddwikky** [firebase/firebase-ios-sdk#6074]
I got GoogleDataTransportCCTSupport had been removed after pod update with Cocoapods. So I can't be running my apps in XCode because GoogleDataTransportCCTSupport was missing.

Cocoapods version: 1.9.3
Any solution for that?

**Comment by paulb777** [comment]
GoogleDataTransportCCTSupport was merged into GoogleDataTransport and isn't needed.  Details in the [release notes](https://firebase.google.com/support/release-notes/ios). Any lingering Xcode project references should be removed.
