### ISSUE TITLE
upload-symbols fails to upload already uploaded dSYMs

### ISSUE THREAD

**Issue by ppamorim** [firebase/firebase-ios-sdk#6076]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.5
  * Firebase SDK version: 6.28.1
  * Firebase Component: Core, Crashlytics
  * Component version: 6.28.1
  * Installation method: CocoaPods

#### Steps to reproduce:

The script `upload-symbols` hangs if you try to upload dSYMs that are already uploaded. This is a major problem when using the script with Fastlane for example. Please check this issue: https://github.com/fastlane/fastlane/issues/16168

I did a test to assert this and I could replicate. when trying to upload a dSYMs that is already in the Firebase server with `upload-symbols`, I get this:

<img width="655" alt="Screenshot 2020-07-19 at 14 31 13" src="https://user-images.githubusercontent.com/5521682/87877668-78334900-c9d7-11ea-8855-899663c74454.png">

I and my team are also unable to know if a dSYM is uploaded since we have multiples apps to maintain. This is pretty confusing, we will never know if a dSYM will hang our script. Our script downloads all the dSYMs of a app version and upload them. This is a problem when we need to continuously send builds to TestFlight and upload the dSYMs for each build. Since the uploader script from `Fastlane` does not send them in order, we can get the script stuck anytime.

`upload-symbols` should inform that the dSYM is already uploaded and continue the script.

#### Relevant Code:

```
./Pods/FirebaseCrashlytics/upload-symbols -d -gsp ./Enviroments/MyApp/GoogleService-Info.plist -p ios ./com.myapp-1.0.0-1.dSYM.zip
```

**Comment by kevinkokomani** [comment]
Seems possible that this could be a network issue. It looks like you can't upload successfully because there's a network request issue in uploading to the endpoint for mapping files. This might also explain the behavior being different from Fabric Crashlytics, because the new Firebase Crashlytics SDK uploads to a different endpoint. Could you try checking any settings related to local network, firewall, VPN, etc?

**Comment by ppamorim** [comment]
@kevinkokomani It's not, the script always get stuck when I try to upload already uploaded dSYMs. I did multiple tests before opening this issue here.

**Comment by ppamorim** [comment]
@kevinkokomani Is there any update on this? I am still experiencing the issue and it's slowing down our development process. I am able to replicate in any env.

**Comment by philmartin83** [comment]
I'm also experiencing something similar but my error is
error: Could not fetch upload-symbols settings: Could not connect to the server.
This was working fine 6 days ago when I released 6 days ago an uploaded a dsyms to firebase

**Comment by glorysaber** [comment]
I have been having the same issue.

**Comment by elenadoty** [comment]
Hi all,
If anyone is still running into this issue: can you estimate about how many files you're trying to upload in each attempt, and over a 24 hour period during which you encounter this error?

**Comment by elenadoty** [comment]
I believe what's been happening is that we have a limit on uploads per app per day. The behavior of the script "hanging" is the script receiving 429 errors and backing off, so that it waits longer between attempted uploads (eventually it waits long enough that it seems like the script is no longer actually running). I've increased the quota, hopefully this helps resolve the issue.

**Comment by dhoskins** [comment]
Seeing this also. Appears to be hanging with messages like:

`Retrying symbol upload with number of retries: 1/10
Retrying symbol upload with number of retries: 2/10
Retrying symbol upload with number of retries: 3/10
Retrying symbol upload with number of retries: 4/10
Retrying symbol upload with number of retries: 5/10
Retrying symbol upload with number of retries: 6/10
Retrying symbol upload with number of retries: 7/10
Retrying symbol upload with number of retries: 8/10`

Please don't make us resort to having to grep the command line tool output for this string and manually abort!!

**Comment by dhoskins** [comment]
Could be related: https://github.com/firebase/firebase-ios-sdk/issues/6990

**Comment by elenadoty** [comment]
Hi @dhoskins,
Which version of Crashlytics are you using? We have a fix rolling out today that should address the issue.

**Comment by jh-gh** [comment]
Hi @elenadoty,
Is there any update on this?  My uploads were all failing yesterday.  I tried one again a few hours ago and it worked (no changes on my side).  Has something been fixed on the server side?
Thanks.

**Comment by elenadoty** [comment]
Hi @jh-gh,
This was a problem on our side. Glad to hear the fix seems to have solved it!

**Comment by jh-gh** [comment]
Hi @elenadoty,
That's awesome.  Thanks for confirming!
