### ISSUE TITLE
Best practice unified identifier, two different platforms

### ISSUE THREAD

**Issue by Patrick3131** [firebase/firebase-ios-sdk#6078]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Xcode 11.5
  * Firebase SDK version:  6.27
  * Firebase Component: Crashlytics (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 4.1.0
  * Installation method: `CocoaPods 

### [REQUIRED] Step 2: Describe the problem
Apple recently introduced the same bundle identifier feature.
We are supporting two different platforms: MacOS build via MacCatalyst and iPhone/iPad
What is the best practice for the Crashlytics/Firebase setup when using the same bundle identifier?

**Comment by kevinkokomani** [comment]
Best practice for a Firebase setup when the macOS and iOS apps must have the same bundle ID is to put them into two separate Firebase projects. Attempting to include them in the same Firebase projects will cause problems (and you can't have two separate apps in the same Firebase project with the same bundle ID).

**Comment by kevinkokomani** [comment]
For sure - assuming the actions you take are as follows:
1. You have a macOS and iOS app with the same bundle ID
2. You've integrated the iOS app into a Firebase project and it's reporting crashes
3. You drop the GoogleServices-Info.plist file into your macOS app to attempt to get crash reports from that as well

The crashes will stop reporting from your iOS app and will only report from your macOS app, or vice versa if you added the macOS app first. This is due to the requirement of the bundle identifier being unique on a per-project basis.

**Comment by Patrick3131** [comment]
Thanks for your answer. As Apple is promoting the unified bundle ID a lot, are there plans to also offer a unified GoogleService.plist on the Firebase platform?

One more thing I am curious about, we only talked about the implications on Crashlytics, does using the same GoogleService.plist also have affects on other event reporting services or for example RemoteConfig?

**Comment by morganchen12** [comment]
We're working on our Apple platforms unification story across all Firebase components, but don't have anything ready to announce at this time.

**Comment by mundue** [comment]
@kevinkokomani I ran into this problem by adding tvOS support to an existing iOS project, both sharing the same bundle identifier and GoogleServices-Info.plist. Now it's just report crashes for the tvOS app. Is there any way to "fix" the reporting so I can use the existing project for iOS again and properly add the tvOS project?

**Comment by morganchen12** [comment]
@mundue see [this comment](https://github.com/firebase/firebase-ios-sdk/issues/6154#issuecomment-667157387).
