### ISSUE TITLE
FR: Please add Calendar Support in iOS/Android Native SDK to query and manage events.

### ISSUE THREAD

**Issue by zyflovelam** [firebase/firebase-ios-sdk#6089]
### Feature proposal

* Firebase Component:  Google Calendar

Hope to add support for Google Calendar in Firebase SDK, can directly authorize and manage events in the calendar on the iOS/Android, like query or sync all events from the Google Calendar, insert or delete events via iOS/Android SDK.

Thanks

**Comment by paulb777** [comment]
@zyflovelam Thanks for the request. I'm not sure that this is something that would be in Firebase's scope. I see that there already is a developer API at https://developers.google.com/calendar. Does that meet your needs?

**Comment by morganchen12** [comment]
You'll need to use the [Google Objective-C client for REST](https://github.com/google/google-api-objectivec-client-for-rest). It's somewhat unintuitive, but ultimately it just makes calls to the Google Calendar REST api.

Unfortunately this falls out of the scope for Firebase, so we won't be adding this feature in the future.
