### ISSUE TITLE
[Firebase Crashlytic] Receive crash report on dev mode but could not receive crash from appstore 

### ISSUE THREAD

**Issue by anhbontb** [firebase/firebase-ios-sdk#6090]
### Step 0: Are you in the right place?

Hi !
We update from Fabric Crashlytic to Firebase Crashlytic.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.5
  * Firebase SDK version: Firebase/Crashlytics (6.24.0),  FirebaseCrashlytics (~> 4.1.0)
  * Firebase Component: Crashlytics
  * Component version: _____
  * Installation method: `CocoaPods` 

### [REQUIRED] Step 2: Describe the problem

Do not receive crash from app store app

#### Steps to reproduce:

When we test Fabric Crashlytic on dev device we can see crash from daskboard but we do not receive any crash after app upload to app store.

#### Relevant Code:

Firebase config

<img width="606" alt="Screen Shot 2020-07-21 at 14 56 55" src="https://user-images.githubusercontent.com/9130297/88029295-0805fe00-cb64-11ea-94db-82bb24b3d7aa.png">

<img width="872" alt="Screen Shot 2020-07-21 at 15 07 18" src="https://user-images.githubusercontent.com/9130297/88029311-0c321b80-cb64-11ea-9cd0-a16c9e7bc085.png">

We only see crash on dev device

<img width="1147" alt="Screen Shot 2020-07-21 at 15 09 09" src="https://user-images.githubusercontent.com/9130297/88029469-3f74aa80-cb64-11ea-9122-50cd2f5e5374.png">

**Comment by morganchen12** [comment]
You should file this issue at [Firebase Support](https://firebase.google.com/support). They'll be able to look at your Firebase project directly to identify issues such as missing dSYM files.
