### ISSUE TITLE
FR: Support custom domains for production environments on Cloud Functions

### ISSUE THREAD

**Issue by rencsaridogan** [firebase/firebase-ios-sdk#6092]
### Feature proposal

* Firebase Component: Cloud Functions

We would like to see the proper support of custom domains on client side SDK(s). Currently, there is:

https://github.com/firebase/firebase-ios-sdk/blob/d4a24bd5ecffec8eb1dc72f4d1d797fb5497124e/Functions/FirebaseFunctions/FIRFunctions.m#L140

available. However, this is documented for test purposes and Emulator usage. Therefore, it does not feel like the right way to move forward for such a need. 

We would like to see the same functionality to be able to configure our Cloud Functions to use a different domain for production environment.

Routing our [callable backend functions](https://firebase.google.com/docs/functions/callable) from a custom domain of ours, would be beneficial in terms of:

- Traffic on a designated domain for our business.
- Provide isolation for possible temporary blockages that might happen on any carrier or due to any specific software (ex: ad blockers), on a more generic domain if not customized, simply because used by many other services.

**Comment by paulb777** [comment]
@rencsaridogan Thanks for the request!

Here's a suggested approach from the Functions team:

- Switch from using callable functions to normal HTTPS functions
- Set up a hosting custom domain https://firebase.google.com/docs/hosting/custom-domain
- Set up a hosting redirect to the function (https://firebase.google.com/docs/hosting/functions#direct_requests_to_function)
- Call functions from the app by making HTTPS requests to {custom-domain}/{redirect-name}

**Comment by rencsaridogan** [comment]
@paulb777 thanks for your response.

Even though we are aware that we can do that, there are important things here to mention:

- We have applications live to this day using callable functions.
- We might want to use serverless NEGs and GCLB.
- This was mentioned as an improvement by GCP Support (Case: 24108749, mainly around the discussion of blocked domains).

For the last part, the fact that this was also mentioned from the GCP Support, we see a potential value for this to be supported officially within the Cloud Functions SDK.

Are there concerns for this support to be implemented or what are the thinking process behind suggesting to directly make HTTPS calls?

**Comment by rencsaridogan** [comment]
Is there any thought given into this? Please do kindly let me know.

**Comment by paulb777** [comment]
@rencsaridogan Sorry that I have no progress to report.

**Comment by rencsaridogan** [comment]
@paulb777 would it be possible to get a green light about the usefulness of this request? If so, we can contribute this functionality ourselves to the mobile SDK(s).

**Comment by rencsaridogan** [comment]
This is added with v7.1.0
