### ISSUE TITLE
Missing 6.28.2?

### ISSUE THREAD

**Issue by omarzl** [firebase/firebase-ios-sdk#6107]
**Version 6.28.2**

In the iOS Release Notes says there is a version 6.28.2 https://firebase.google.com/support/release-notes/ios but the podspec in the tag CocoaPods-6.28.2 still has the version set to 6.28.1:
https://github.com/firebase/firebase-ios-sdk/blob/CocoaPods-6.28.2/Firebase.podspec

**Comment by paulb777** [comment]
@omarzl Thanks for the report. We made a mistake in the release notes.

6.28.2 is a version that only applies to the zip distribution.  For CocoaPods, the fix available with 6.28.1 by running `pod update` to get version 3.2.1 of the FirebasePerformance pod.

**Comment by omarzl** [comment]
Perfect! Thank you!
