### ISSUE TITLE
FirebaseCrashlytics - Non-public API usage on Mac Catalyst

### ISSUE THREAD

**Issue by peterstojanowski** [firebase/firebase-ios-sdk#6128]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.6
  * Firebase SDK version: 6.28.1
  * Firebase Component: FirebaseCrashlytics
  * Component version: 4.3.0
  * Installation method: `CocoaPods`

#### Steps to reproduce:

After uploading a Mac Catalyst app, I received an email form Apple saying:

ITMS-90338: Non-public API usage - The app references non-public symbols in Contents/MacOS/Invoice: _NXGetArchInfoFromCpuType, _NXGetLocalArchInfo, _getsectbynamefromheader, _getsectbynamefromheader_64. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

I noticed that these methods are present in FirebaseCrashlytics code. I was able to successfully upload iOS version of my app which also uses FirebaseCrashlytics. This email is only being sent for my macOS app.

**Comment by siburb** [comment]
We've had exactly the same email. I was able to upload a build of the app a few weeks ago without receiving this email, but can't now. Had to remove Crashlytics in order to submit.

**Comment by morganchen12** [comment]
Thanks for the reports. Looks like something changed in Apple's symbol scanner autorejections that is now flagging Crashlytics code. We're working to resolve this issue.

**Comment by meroelyth** [comment]
> Thanks for the reports. Looks like something changed in Apple's symbol scanner autorejections that is now flagging Crashlytics code. We're working to resolve this issue.

Same here!

**Comment by morganchen12** [comment]
Due to the nature of this issue, it will be difficult to communicate progress. However, please feel free to continue leaving +1's on this issue, as it will help us gauge the severity of the issue.

**Comment by philipphofmann** [comment]
It's also flagging our code in [sentry-cocoa](https://github.com/getsentry/sentry-cocoa), not just Crashlytics code.

**Comment by samedson** [comment]
Hey folks wanna reach back out. Are people still running into this? Haven't heard an update yet from my end but want to see if this is still impacting folks to see if we should look into a workaround.

**Comment by elenadoty** [comment]
Closing as it seems this is no longer a problem.

**Comment by philipphofmann** [comment]
@elenadoty can you elaborate on why this is no longer a problem. Did Apple solve the issue on their side?

**Comment by elenadoty** [comment]
Hi @philipphofmann,
I think they may have changed what they were flagging, since we hadn't heard any reports of this error since September.
