### ISSUE TITLE
Firebase Crashlytics unusable after FirebaseApp.delete()

### ISSUE THREAD

**Issue by cooksimo** [firebase/firebase-ios-sdk#6130]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.5
  * Firebase SDK version: 6.20.0
  * Firebase Component: Crashlytics
  * Component version: 4.0.0
  * Installation method: CocoaPods

### Step 2: Describe the problem

This is a very similar problem to #3411. We allow the Firebase project in use to be changed at runtime, so we can switch between production, staging and sandbox environments. In trying to migrate to the Firebase Crashlytics SDK (from Fabric) we have run in to this issue, where recreating the Firebase app results in an error from Crashlytics: "Cannot instantiate more than one instance of Crashlytics."

#### Steps to reproduce:

- Initialise Firebase as usual (with Crashlytics present)
- Delete the app with FirebaseApp.delete
- Configure the app again
- See the error in the logs

#### Relevant Code:

This is caused by the following code in `FIRCrashlytics.m`
```
    if (!atomic_compare_exchange_strong(&_hasInitializedInstance, &expectedCalled, YES)) {
      FIRCLSErrorLog(@"Cannot instantiate more than one instance of Crashlytics.");
      return nil;
    }
```

Commenting this code out (obviously) fixes the issue, but I'm not sure what other implications it may have.

**Comment by Olegkodysh** [comment]
Thanks for the report. Could you please let me know how it is you're instantiating Firebase, and whether you're using different GoogleService files?

**Comment by demonar** [comment]
I'm experiencing the same issue, using the same GoogleService files, the only thing needed is to do

`FirebaseApp.app().delete { _ in
    FirebaseApp.configure()
}`

**Comment by demonar** [comment]
here's my console message:

`6.29.0 - [Firebase/Crashlytics][I-CLS000000] Cannot instantiate more than one instance of Crashlytics.`

**Comment by Olegkodysh** [comment]
Are you trying to delete this instance of the Firebase app when calling the .delete function, and then trying to configure it again? Does the error occur then?

**Comment by demonar** [comment]
> Are you trying to delete this instance of the Firebase app when calling the .delete function, and then trying to configure it again? Does the error occur then?

exactly

**Comment by anphanngocvn** [comment]
I am experiencing this issue. What was a solution for you @demonar ?

**Comment by elenadoty** [comment]
Hi @anphanngocvn @demonar ,
I believe that this is an internal bug with FirebaseApp (see also https://github.com/firebase/firebase-ios-sdk/issues/4072). A work around (albeit, not ideal and a bit hacky) is to use the `configure(name:options:)` method for the second configuration:

```FirebaseApp.configure(name: "newapp", options: FirebaseApp.app()!.options)```

I'll update this ticket if there are any fixes to report.
