### ISSUE TITLE
Cleanup: Refactor RCNConfigFetch to use promises for chained async operations

### ISSUE THREAD

**Issue by maksymmalyhin** [firebase/firebase-ios-sdk#6132]
Implementation of `RCNConfigFetch` requires chaining multiple async operations. The current implementation uses plain completion handlers which leads to hardly readable and modifiable code (e.g. [this method](https://github.com/firebase/firebase-ios-sdk/blob/c07c89ee7582e84da1c5aafaa94b38a53bcfbdc2/FirebaseRemoteConfig/Sources/RCNFetch.m#L308)). We should consider using [Promises](https://github.com/google/promises) to improve readability of the code (e.g. like in [FirebaseInstallations](https://github.com/firebase/firebase-ios-sdk/blob/0ed26aedb85f3f3fd37b0077133347183db5de7a/FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsAPIService.m#L103)).

Make sure the class is covered by unit tests.

Related to #6123.

**Comment by rizafran** [comment]
Closing this issue as the fix was merged into `master`.

**Comment by paulb777** [comment]
Reopening since we haven't actually started using Promises in the RemoteConfig implementation.

**Comment by paulb777** [comment]
I'm going to close since we'd now like to migrate the implementation to Swift before doing any major Objective C refactors.
