### ISSUE TITLE
"Enqueue methods cannot be called when we are already running on target executor "

### ISSUE THREAD

**Issue by RuiAAPeres** [firebase/firebase-ios-sdk#6143]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.6
  * Firebase Component: Firestore
  * Component version: 1.16.2
  * Installation method: `CocoaPods`

### [REQUIRED] Step 2: Describe the problem

I am getting the following crash:

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'FIRESTORE INTERNAL ASSERTION FAILED: Enqueue methods cannot be called when we are already running on target executor (this queue's executor: 'com.google.firebase.firestore.Firestore-Chat', current executor: 'com.google.firebase.firestore.Firestore-Chat') (expected !is_operation_in_progress_ || !executor_->IsCurrentExecutor())'
```

#### Steps to reproduce:

This happens when I am about to logout the user and the `FirebaseApp`'s `delete` method is called. 

#### Extra Info

This crash is not occurring before version `1.15.0`. For now I am locking the version to `1.14.0`, since it's not crashing.

**Comment by wilhuff** [comment]
Hi @RuiAAPeres, I'm sorry to hear you're having trouble.

Do you happen to have the stack trace associated with this crash message? In the meantime I'll try to reproduce based on your description.

**Comment by wilhuff** [comment]
I've tried to reproduce this by adding sign-out code to the quickstart but I can't trigger this exception. Based on your description, it seems like interacting with a Firestore instance and then destroying it by calling `delete` would be sufficient to reproduce this. Instead I'm seeing `delete` complete successfully:

```swift
let app = FirebaseApp.app()
app!.delete() { completed in
  NSLog("FirebaseApp deleted: \(completed)")
}
```

```
2020-07-29 17:51:17.988715-0700 FirestoreExample[64416:11815137] FirebaseApp deleted: true
```

The stack will help, but maybe there are more steps required to trigger the exception?
