### ISSUE TITLE
Provisioning profile for running the Dynamic Links example?

### ISSUE THREAD

**Issue by aleclarson** [firebase/firebase-ios-sdk#6147]
<img width="410" alt="image" src="https://user-images.githubusercontent.com/1925840/88716053-7448aa80-d0ec-11ea-965d-fd5a7123b056.png">

> "FDLBuilderTestAppObjC" requires a provisioning profile with the Associated Domains feature.

What's the recommended way to run the test app for Dynamic Links?
Perhaps a special provisioning profile can be provided?

Use case: I'm planning on making the necessary changes for the Dynamic Links framework to build for macOS.

**Comment by paulb777** [comment]
@aleclarson Thanks for investigating! 

We might not be able to share a provisioning profile, so your best bet might be to change the bundle ID and use your own.

**Comment by morganchen12** [comment]
Note that this requires you to be a member of the Apple Developer program.
