### ISSUE TITLE
FR: Add different behavior for DEBUG and RELEASE

### ISSUE THREAD

**Issue by brennobemoura** [firebase/firebase-ios-sdk#6148]
### Feature proposal

* Firebase Component: Analytics

On the firebase console, I would like to see events and the usage of the app separated by two types. For example, at Console > Analytics > "App usage" (pt-br: "Adoção da versão do aplicativo"), I would like to see something like this "2.0.0 (beta)". Firebase is assuming that the app is on release even when the app is compiled in DEBUG and submitted to "App Distribution".

I searched for a solution, but what I found was to create a different app in Firebase console only for dev versions, and I would have to switch all the configs for each version of app, when it is in production and when it is in development.

My idea for this FR is that Firebase should check if the app is in DEBUG or not, and developers can set on launch function that state if they want, maybe as a FirebaseOptions.

**Comment by paulb777** [comment]
@brennobemoura Thanks for the proposal. Are you specifically asking about Analytics events? Are you asking about any other Firebase functionality? Analytics could be a challenge since it is distributed as a binary so cannot process build time flags like `DEBUG`.

**Comment by brennobemoura** [comment]
Hmm, so I guess the only way is by using a enum case `.production` or `.development`.

About the Firebase functionality, I don't know exactly which part of Firebade is responsible for the data that we see at console, I am guessing that Analytics may be the only one that trace events and organize data at Firebase console.

Even though, this feature may benefit other structures in Firebase Core in the future, not only Analytics.

I suppose that the easy way, if it is possible, Firebase Console only needs to match data from app and from App Distribution. For example, I uploaded a build to App Distribution with `version:2.0.0` and `build_number:175`. When Analytics report some event at Firebase Console running this version, by logic, it should be assumed that version is a beta version. So, the admin can filter the events and only see the production ones.

**Comment by morganchen12** [comment]
Hey @brennobemoura, unfortunately this is part of a larger Firebase limitation and we recommend using separate projects for dev and prod. If you'd like to avoid doing that, you can filter out Analytics events from App Distribution builds by carefully choosing special build numbers for App Distribution only.
