### ISSUE TITLE
App Freezes on Main Thread on Xcode 11.6

### ISSUE THREAD

**Issue by over140** [firebase/firebase-ios-sdk#6150]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.6
  * iPhone OS version: 13.5.1
  * iPhone Model: iPhone 7 Plus
  * Firebase SDK version: 6.29.0
  * Firebase Component: (Core, Analytics, Performance, Crashlytics)
  * Component version: 6.9.2, 6.7.0, 3.2.1, 4.3.1
  * Installation method: `CocoaPods`

### [REQUIRED] Step 2: Describe the problem

After upgrading to latest version of Firebase, and using it on Xcode 11.6, sometimes the app freezes, and when I check the main thread appears this:
![image](https://user-images.githubusercontent.com/1852993/88769301-d2d65d00-d1ae-11ea-8e83-515e324ddbed.png)

**Comment by kevinkokomani** [comment]
Thanks for the report. Are you able to reproduce this with the Crashlytics sample quickstart app while on Xcode 11.6 and the most recent version of Crashlytics?
