### ISSUE TITLE
pod 'Firebase/Crashlytics' unable to install.

### ISSUE THREAD

**Issue by sujatha678** [firebase/firebase-ios-sdk#6153]
<img width="567" alt="Screenshot 2020-07-29 at 4 31 27 PM" src="https://user-images.githubusercontent.com/44140456/88792525-facabe00-d1b8-11ea-8495-f9e21e823563.png">

### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: _11.5____
  * Firebase SDK version: __5.15.0___
  * Firebase Component: _ pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Firebase/Auth'
    pod 'Firebase/Database', '5.15.0'
    pod 'Firebase/Firestore'
    pod 'Firebase/Storage'
    pod 'Firebase/Crashlytics'
    pod 'Firebase/Analytics'
    pod 'Firebase/RemoteConfig'____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: _____
  * Installation method: `CocoaPods 

#### Steps to reproduce:
while trying to install Firebase/Crashlytics through pods getting issue. I tried doing pod repo update, pod update. But No Luck. Can you help me to figure out the issue.
What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by ryanwilson** [comment]
Hi @sujatha678 - thanks for the report.

When specifying version `5.15.0` for Database, it's preventing the Firebase CocoaPod from updating to a newer version where Crashlytics is available. I believe you need at least `6.15.0` or above, but we recommend always staying up to date where possible to ensure you've got all the bug and performances fixes that come with regular updates. You can see updates from major version 5 to 6 at https://firebase.google.com/support/release-notes/ios#version_600_-_may_7_2019.

Updating to the newer version will resolve this issue.
