### ISSUE TITLE
Firebase Crashlytics didn't come crashes at console from iOS 

### ISSUE THREAD

**Issue by ClayPwr** [firebase/firebase-ios-sdk#6154]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.5
  * Firebase SDK version: 6.28.1
  * Firebase Component: FirebaseCrashlytcs
  * Component version: 4.3.0
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem
Hi, don't got crashes from iOS at firebase console, found look likes my issue #4798 but still can't resolve problem
#### Steps to reproduce:
I got two targets tvOS and iOS with same bundle identifiers. So this mean one GoogleService-info.plist. Crashes come from tvOS but not iOS target. At the console got message "Upload 1 missing dSYM required to process 55 crashes"

#### Relevant Code:
got this message when build iOS 
```
_iOS[21768:903927]  - <AppMeasurement>[I-ACS036001] Analytics screen reporting is disabled. UIViewController transitions will not be logged.
_iOS[21768:903001] GoogleCast framework version 4.4.5.19.01
_iOS[21768:903001] [Firebase/Crashlytics] Version 4.3.0
_iOS[21768:903935] [Firebase/Crashlytics] Packaged report with id 'f350e111fb1b409ba8983225795bacca' for submission
_iOS[21768:903960] 6.28.0 - [Firebase/Analytics][I-ACS023007] Analytics v.60602000 started
_iOS[21768:903960] 6.28.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
_iOS[21768:903927] 6.28.0 - [Firebase/Analytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
CoreData: annotation:  Failed to load optimized model at path
'/Users/tarabanovigor/Library/Developer/CoreSimulator/Devices/916A8DF5-BCF2-4D0B-903F-DF4A6B4227A3/data/Containers/Bundle/Application/4F9CB9A9-4507-4F11-A5DC-61701110E5FE/_iOS.app/GoogleCastCoreResources.bundle/CastFrameworkDB.momd/CastFrameworkDB05.omo'
_iOS[21768:903960] 6.28.0 - [Firebase/Analytics][I-ACS023012] Analytics collection enabled
```
when build tvOS no debug messages

its how look run script at iOS target they same with tvOS only one change at script "...-info.plist" -p tvos
![Снимок экрана 2020-07-29 в 14 50 16](https://user-images.githubusercontent.com/25775867/88797151-89d0d980-d1ab-11ea-8d16-48f8bab5a709.png)
![Снимок экрана 2020-07-29 в 14 54 45](https://user-images.githubusercontent.com/25775867/88797157-8c333380-d1ab-11ea-922c-959f3caf767b.png)

**Comment by ryanwilson** [comment]
Hi @ClayPwr - sorry for the issues you're seeing.

At the moment, in order to get Crashlytics for both tvOS and iOS the apps will need to be in separate projects. See  https://github.com/firebase/firebase-ios-sdk/issues/2009#issuecomment-537595911 for more information.

**Comment by ClayPwr** [comment]
Hi, @ryanwilson thanks for answer. Can i switch between tvOS and iOS?

**Comment by ryanwilson** [comment]
cc @samedson to answer that question.

**Comment by samedson** [comment]
@ClayPwr there is a way to switch it back to only iOS. Right now it's a manual process on our end.

Can you reach out to support so we can get your information and do the switch?

Just to clarify, right now Crashlytics will only work with either iOS or tvOS in your app, not both at the same time. When you start using tvOS in your app, it will switch the app to being tvOS and iOS crashes will stop processing. Switching back to iOS is the manual process. And again, we're hoping to improve this situation at some point.

**Comment by ClayPwr** [comment]
Hi @samedson, thanks for answer can we left now like that for testing tvOS app. But at future i will need switch back at iOS. Please write how I can do this?

**Comment by morganchen12** [comment]
@ClayPwr if you need both, the best option right now is to set up two separate Firebase projects (one for iOS, one for tvOS).

**Comment by ClayPwr** [comment]
@morganchen12 I understand this, but I have both project in App Store with the same ID

**Comment by morganchen12** [comment]
If it's a one-time switch from tvOS back to iOS, you can ask [Firebase Support](https://firebase.google.com/support) to do that for you.

**Comment by ClayPwr** [comment]
@morganchen12 ok, thanks

**Comment by morganchen12** [comment]
Closing this since it's no longer actionable in GitHub. Feel free to file a new issue if you run into more troubles.
