### ISSUE TITLE
Carthage installation of FirebaseAnalytics and FirebaseCrashlytics fails for 6.29.0

### ISSUE THREAD

**Issue by agirault** [firebase/firebase-ios-sdk#6158]
### Step 1: Describe your environment

  * Xcode version: Version 11.6 (11E708)
  * Firebase SDK version: 6.28.1/6.29.0 (source of the issue)
  * Firebase Component: Analytics, Crashlytics, Performance, Protobuf
  * Installation method: `Carthage` (0.35.0)

### Step 2: Describe the problem

Trying to use Carthage to install Firebase Analytics, Crashlytics, Performance, and Protobuf (required by Performance) resolves to different versions of Firebase (mix of `6.28.1` and `6.29.0`) which [isn't recommended](https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md#versioning), even though the `*Binary.json` files all have entries for `6.29.0`

#### Steps to reproduce:

Following [the documentation](https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md#carthage-usage), create this `Cartfile`:
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashlyticsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebasePerformanceBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseProtobufBinary.json"
```

Running `carthage update` generates mismatched versions in `Cartfile.resolved`:
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" "6.28.1"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashlyticsBinary.json" "6.28.1"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebasePerformanceBinary.json" "6.29.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseProtobufBinary.json" "6.29.0"
```

If we manually change all the versions to `6.29.0` in `Cartfile.resolved` then run `cartfile bootstrap`, `Carthage` will throw the following error:
```
No available version for binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" satisfies the requirement: == 6.29.0
```

However:
* [FirebaseAnalyticsBinary.json](https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json) has an entry for `6.29.0` ([FirebaseAnalytics-1339166ebecfac2a.zip](https://dl.google.com/dl/firebase/ios/carthage/6.29.0/FirebaseAnalytics-1339166ebecfac2a.zip))
* [FirebaseCrashlyticsBinary.json](https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashlyticsBinary.json) has an entry for `6.29.0` ([FirebaseCrashlytics-d0d6346298c14328.zip](https://dl.google.com/dl/firebase/ios/carthage/6.29.0/FirebaseCrashlytics-d0d6346298c14328.zip))

I was able to manually download the zip listed in the `Binary.json` files for `6.29.0` and place them, and everything worked fine, so I assume there is a problem with how Carthage resolves those Firebase `Binary.json` files?

----
Based on contributions and activity on other issues, I believe this might be a question for @paulb777?

**Comment by agirault** [comment]
Also, I'm curious why `run` and `upload-symbols` are in the `FirebaseCrashlytics-*.zip` file referenced by `FirebaseCrashlyticsBinary.json` along with the framework, but they are not present when letting `Carthage` grab them.

**Comment by paulb777** [comment]
@agirault Thanks for the report. I'm able to successfully `carthage update` to the 6.29.0 versions, so not able to reproduce.

For the second question, it's a result of Carthage being opinionated about only installing frameworks and nothing else.

Since you have a workaround and it's not obviously reproducible, I'll mark this `needs-info` to auto close unless we get other reports or additional information.

**Comment by agirault** [comment]
I just had a collaborator try it out without any issue on his end, just like you. I'm using the latest `carthage` so this is surprising. Thanks for the follow-up, good to let auto close.

**Comment by agirault** [comment]
I see my comment removed the `needs-info` tag so I'll simply close the issue. Thank you.
