### ISSUE TITLE
Failed to load Info.plist from bundle

### ISSUE THREAD

**Issue by akashnimare** [firebase/firebase-ios-sdk#6159]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.5
  * Firebase SDK version: latest
  * Firebase Component: Firebase cloud messaging 
  * Component version: Manual (Zip file)
  * Installation method: `Zip file`

### [REQUIRED] Step 2: Describe the problems
No issues in build but I get this error when I try to run it in the simulator

```
Could not install at this time.
Failed to load Info.plist from bundle at path /Users/XXX/Library/Developer/CoreSimulator/Devices/9A502C4B-960C-4015-AC91-4426C3K644EE0/data/Library/Caches/com.apple.mobile.installd.staging/temp.hLiR8W/extracted/Myapp.app/Frameworks/Protobuf.framework; Extra info about plist: ACL=<not found> 
```

I have tried all the fixes mentioned [here](https://stackoverflow.com/questions/40327935/failed-to-load-info-plist-from-bundle) but no luck. Could you help me figure out what's wrong here?

**Comment by morganchen12** [comment]
You should be able to add an empty framework plist into that directory and re-run your app without errors.

**Comment by akashnimare** [comment]
@morganchen12 `plist` file is already there in Finder. Do you mean I need to update the existing plist in `FirebaseMessaging.xcframework`?

![image](https://user-images.githubusercontent.com/2263909/88897805-800dab80-d269-11ea-904c-88b6f10446ea.png)

**Comment by paulb777** [comment]
Check #6 at https://github.com/firebase/firebase-ios-sdk/blob/master/ZipBuilder/Template/README.md#integration-instructions,

_Do not add the Firebase frameworks to the "Embed Frameworks" Xcode build phase. The Firebase frameworks are not embedded dynamic frameworks, but are static frameworks which cannot be embedded into your application's bundle._

**Comment by akashnimare** [comment]
Great. It worked. Thank you @paulb777 ❤️
