### ISSUE TITLE
Topics do not work with watchOS

### ISSUE THREAD

**Issue by jlandrum** [firebase/firebase-ios-sdk#6160]
If you attempt to sub to a topic, the callback never calls indicating a success or failure.

The reason is due to `self.pubsub` being undefined, and a message is being sent to `self.pubsub` with the completion without a null check:
https://github.com/firebase/firebase-ios-sdk/blob/ad06c605bf08d1649d266f41116f5b3c46345e99/FirebaseMessaging/Sources/FIRMessaging.m#L781

There's this line:
https://github.com/firebase/firebase-ios-sdk/blob/ad06c605bf08d1649d266f41116f5b3c46345e99/FirebaseMessaging/Sources/FIRMessaging.m#L273
Which blocks initialization of `self.pubsub` - however when this is removed, there appears to be no problems. Topics work fine on a standalone watchOS after removing these preprocessor statements. 

Is there any particular reason as to why? I'm assuming something else is not working properly with notifications is why - I will gladly help update the code if need be to get this working, as topics are something we need on our end.

**Comment by chliangGoogle** [comment]
Thanks @jlandrum Good catch on the issue. Yes the topic subscription should be working on watchOS and the macro is not correctly set.
The reason we set it for now is that to prevent direct channel from running as it's not available in watchOS, so uncomment it will have a lot of unexpected code from running the resources. Feel free to comment out the macro for the quick fix for now, I will kick off a PR that refactors the pubsub to be called without relying on direct channel logic.
