### ISSUE TITLE
Expected a field designator, such as '.field = 4' firebasecore.nanopb.c

### ISSUE THREAD

**Issue by HanzlaRafique** [firebase/firebase-ios-sdk#6166]
I was running in simulator as well as real device and getting this error.

<img width="1132" alt="Screenshot 2020-07-31 at 12 01 50 AM" src="https://user-images.githubusercontent.com/53652998/88964126-56cd3980-d2c2-11ea-980b-233404db30e8.png">

**Comment by HanzlaRafique** [comment]
@google-oss-bot  What is the proper solution?

**Comment by morganchen12** [comment]
Please fill out the issue template, or share an example project that clearly reproduces the issue.

**Comment by paulb777** [comment]
Duplicate of #5548 

- `pod deintegrate`
- `pod install`
