### ISSUE TITLE
FCM token refresh every ~10 min, losing notifications

### ISSUE THREAD

**Issue by pererasys** [firebase/firebase-ios-sdk#6167]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.5
  * Firebase SDK version: 6.27.0
  * Firebase Component: Messaging
  * Component version: 6.27.0
  * Installation method: CocoaPods

#### Steps to reproduce:

This is likely a configuration or APNS issue, but my FCM tokens get refreshed every 10 minutes or so, and I lose some notifications in between refreshing. I created the key with apple, running the application in a release build on a physical device, and have all the appropriate plist files in my project. Haven't found much online regarding this issue, but was hoping I could get some resources to figure this out.

#### Relevant Code:

All config, not an issue with code as far as I can tell.

**Comment by morganchen12** [comment]
Are you receiving a new APNS token once every ten minutes? Also, is this consistent across all devices that you're sending notifications (are you able to isolate the buggy behavior by device/OS version)?

**Comment by chliangGoogle** [comment]
Can you also share with us the debugLog and the implementation under:`application(_:didRegisterForRemoteNotificationsWithDeviceToken:)`?

**Comment by pererasys** [comment]
I revoked my APNS key and created a new one, seems to be working now so I'll go ahead and close this. Thanks!
