### ISSUE TITLE
FR: Any way to clear Google tag manager database?

### ISSUE THREAD

**Issue by sairamkotha-swiggy** [firebase/firebase-ios-sdk#6173]
### [READ] Guidelines

When filing a feature request please make sure the issue title starts with "FR:".

A good feature request ideally
* is either immediately obvious (i.e. "Add Sign in with Apple support"), or
* starts with a use case that is not achievable with the existing Firebase API and
  includes an API proposal that would make the use case possible. The proposed API
  change does not need to be very specific.

Once you've read this section, please delete it and fill out the rest of the template.

### Feature proposal

* Firebase Component: Firebase Analytics with Google Tag Manager.

We are seeing timeouts with Google tag manager hits because that endpoint is deprecated and due to that older app version users are not able to send newer data as Tag manager retrying same. 
Any public method to clear GTMV5.sql DB?

**Comment by morganchen12** [comment]
Hey @sairamkotha-swiggy, unfortunately the Firebase team continues to lack the bandwidth necessary to tackle this feature request. Closing this as it's not something we consider on adding in the future and has garnered minimal community support.
