### ISSUE TITLE
AppStore Rejected app because of UIWebView components still present in Firebase SDK

### ISSUE THREAD

**Issue by FahadSaleem907** [firebase/firebase-ios-sdk#6179]
* Xcode version: _____ 11.6
  * Firebase SDK version: _____ Latest Updated
  * Firebase Component: _____ DynamicLinks / Firebase-Auth/GeoFirestore
  * Component version: _____ Latest Updated
  * Installation method: CocoaPods 
-Date when tried : 31/7/2020

### [REQUIRED] Step 2: Describe the problem
Tried to submit App build, apple rejected with ITMS-90809

#### Steps to reproduce:
Install firebase pods or update them if needed, and tried to achieve it.

#### Pods being used
#For Firebase
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Firebase/Auth'
pod 'Firebase/DynamicLinks' #This is for sharing app/events
pod 'CodableFirebase' #This is for using codable/decodeable
#pod 'Geofirestore' #This is for implementing GeoLocation (Issue this has is it still uses UIWebView which has been depricated)
pod 'Geofirestore', :git => 'https://github.com/patpatchpatrick/GeoFirestore-iOS'
# Add the pod for Firebase Cloud Messaging
pod 'Firebase/Messaging' #This is for handling Cloud Messaging (Notifications in this apps case)
# For Image/Video/Other Media purpose
pod 'Firebase/Storage'
pod 'SDWebImage', '~> 5.0'

#### Actions taken to try fix it:
I updated pod 'GeoFirestore' to 'Geofirestore', :git => 'https://github.com/patpatchpatrick/GeoFirestore-iOS' as in some commend i read it fixes the issue

I went and got used the grep -r "UIWebView" . on my terminal and this is the result.

#### 
./Pods/FirebaseDynamicLinks/Firebase/DynamicLinks/FIRDLJavaScriptExecutor.m:// define below needed because nullability of UIWebViewDelegate method param was changed between
./Pods/FirebaseDynamicLinks/Firebase/DynamicLinks/FIRDLJavaScriptExecutor.m:@interface FIRDLJavaScriptExecutor () <UIWebViewDelegate, WKNavigationDelegate>
./Pods/FirebaseDynamicLinks/Firebase/DynamicLinks/FIRDLJavaScriptExecutor.m:  UIWebView *_uiWebView;  // Used in iOS 7 only.
./Pods/FirebaseDynamicLinks/Firebase/DynamicLinks/FIRDLJavaScriptExecutor.m:  // on UIWebView.
./Pods/FirebaseDynamicLinks/Firebase/DynamicLinks/FIRDLJavaScriptExecutor.m:    _uiWebView = [[UIWebView alloc] init];
./Pods/FirebaseDynamicLinks/Firebase/DynamicLinks/FIRDLJavaScriptExecutor.m:#pragma mark - UIWebViewDelegate
./Pods/FirebaseDynamicLinks/Firebase/DynamicLinks/FIRDLJavaScriptExecutor.m:- (void)webViewDidFinishLoad:(UIWebView *)webView {
./Pods/FirebaseDynamicLinks/Firebase/DynamicLinks/FIRDLJavaScriptExecutor.m:- (void)webView:(UIWebView *)webView
./Pods/FirebaseAuth/Firebase/Auth/Source/FIRAuthWebView.h:@property(nonatomic, weak) UIWebView *webView;
./Pods/FirebaseAuth/Firebase/Auth/Source/FIRAuthWebView.m:  UIWebView *webView = [self createWebView];
./Pods/FirebaseAuth/Firebase/Auth/Source/FIRAuthWebView.m:- (UIWebView *)createWebView {
./Pods/FirebaseAuth/Firebase/Auth/Source/FIRAuthWebView.m:  UIWebView *webView = [[UIWebView alloc] initWithFrame:CGRectZero];
./Pods/FirebaseAuth/Firebase/Auth/Source/FIRAuthErrorUtils.m:        UIWebView failed.
./Pods/FirebaseAuth/Firebase/Auth/Source/FIRAuthErrorUtils.m:        SFSafariViewController or UIWebView failed.
./Pods/FirebaseAuth/Firebase/Auth/Source/FIRAuthErrorUtils.m:    "within the SFSafariViewController or UIWebView.";
./Pods/FirebaseAuth/Firebase/Auth/Source/FIRAuthURLPresenter.h:    @brief A Class responsible for presenting URL via SFSafariViewController or UIWebView.
./Pods/FirebaseAuth/Firebase/Auth/Source/FIRAuthWebViewController.m:@interface FIRAuthWebViewController () <UIWebViewDelegate>
./Pods/FirebaseAuth/Firebase/Auth/Source/FIRAuthWebViewController.m:#pragma mark - UIWebViewDelegate
./Pods/FirebaseAuth/Firebase/Auth/Source/FIRAuthWebViewController.m:- (BOOL)webView:(UIWebView *)webView
./Pods/FirebaseAuth/Firebase/Auth/Source/FIRAuthWebViewController.m:                navigationType:(UIWebViewNavigationType)navigationType {
./Pods/FirebaseAuth/Firebase/Auth/Source/FIRAuthWebViewController.m:- (void)webViewDidStartLoad:(UIWebView *)webView {
./Pods/FirebaseAuth/Firebase/Auth/Source/FIRAuthWebViewController.m:- (void)webViewDidFinishLoad:(UIWebView *)webView {
./Pods/FirebaseAuth/Firebase/Auth/Source/FIRAuthWebViewController.m:- (void)webView:(UIWebView *)webView didFailLoadWithError:(NSError *)error {
./Podfile:#pod 'Geofirestore' #This is for implementing GeoLocation (Issue this has is it still uses UIWebView which has been depricated)

####

Please any views why I still get so many UIWebView related references ??? or is it just me having this problem ?

**Comment by morganchen12** [comment]
It looks like you're using a very old version of Firebase, since Geofirestore requires Firebase 5. Geofirestore isn't maintained by the Firebase team, but if you date your version of Firebase these errors should go away.
