### ISSUE TITLE
GDTCOREvent High CPU Usage Termination

### ISSUE THREAD

**Issue by YasinTian** [firebase/firebase-ios-sdk#6185]
144 seconds cpu time over 154 seconds (94% cpu average), exceeding limit of 80% cpu over 180 seconds

```
100.0%  _dispatch. ,call. ,block. ,and. _release libdispatch.dylib
100.0%  	__39-[GDTCCTPrioritizer appWillForeground:]_block_invoke
100.0%		GDTCORDecodeArchive
100.0%			+[NSKeyedUnarchiver unarchivedObjectOfClass:fromData:error:] Foundation
100.0%				_decodeObjectBinary Foundation
100.0%					-[GDTCCTPrioritizer initWithCoder:] Vostic
100.0%						-[NSKeyedUnarchiver decodeObjectOfClasses:forKey:] Foundation
81.8%							_decodeObjectBinary Foundation
81.8%								-[GDTCOREvent initWithCoder:] Vostic
81.8%									-[GDTCOREvent initWithMappingID:target:] Vostic
81.8%										+[GDTCOREvent nextEventID] Vostic
81.8%											_dispatch, ,lane. ,barrier. ,sync. ,invoke_ ,and_ ,complete libdispatch.dylib
81.8%												_dispatch, ,client. callout libdispatch.dylib
81.8%													__26+[GDTCOREvent nextEventID] ,block. ,invoke.9 Vostic
81.8%														writeStringToURLOrPath Foundation
```

**Comment by paulb777** [comment]
@YasinTian Please ensure you're using the latest version, share the `Podfile.lock` and let us know if there are any reproduction steps.

**Comment by YasinTian** [comment]
> @YasinTian Please ensure you're using the latest version, share the `Podfile.lock` and let us know if there are any reproduction steps.

I have this crash with 6.14.0 and 6.26.0 version。Crashlytics callback the crash in 'crashlyticsDidDetectReportForLastExecution' when app started, but no crash record found in the crashlytics console。Crash always happen with the app switch background

- Fabric (1.10.2)
  - Crashlytics (3.13.4):
    - Fabric (~> 1.10.2)

  - FBSDKCoreKit (5.15.1):
    - FBSDKCoreKit/Basics (= 5.15.1)
    - FBSDKCoreKit/Core (= 5.15.1)
  - FBSDKCoreKit/Basics (5.15.1)
  - FBSDKCoreKit/Core (5.15.1):
    - FBSDKCoreKit/Basics
  - FBSDKLoginKit (5.15.1):
    - FBSDKLoginKit/Login (= 5.15.1)
  - FBSDKLoginKit/Login (5.15.1):
    - FBSDKCoreKit (~> 5.0)
  - FBSDKShareKit (5.2.3):
    - FBSDKCoreKit (~> 5.0)
  - Firebase/Analytics (6.26.0):
    - Firebase/Core
  - Firebase/Core (6.26.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.6.0)
  - Firebase/CoreOnly (6.26.0):
    - FirebaseCore (= 6.7.2)
  - Firebase/Performance (6.26.0):
    - Firebase/CoreOnly
    - FirebasePerformance (~> 3.1.11)
  - FirebaseABTesting (3.1.1):
    - FirebaseAnalyticsInterop (~> 1.3)
    - FirebaseCore (~> 6.1)
    - Protobuf (~> 3.8)
  - FirebaseAnalytics (6.6.0):
    - FirebaseCore (~> 6.7)
    - FirebaseInstallations (~> 1.3)
    - GoogleAppMeasurement (= 6.6.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 1.30905.0)
  - FirebaseAnalyticsInterop (1.5.0)
  - FirebaseCore (6.7.2):
    - FirebaseCoreDiagnostics (~> 1.3)
    - FirebaseCoreDiagnosticsInterop (~> 1.2)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
  - FirebaseCoreDiagnostics (1.3.0):
    - FirebaseCoreDiagnosticsInterop (~> 1.2)
    - GoogleDataTransportCCTSupport (~> 3.1)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
    - nanopb (~> 1.30905.0)
  - FirebaseCoreDiagnosticsInterop (1.2.0)
  - FirebaseInstallations (1.3.0):
    - FirebaseCore (~> 6.6)
    - GoogleUtilities/Environment (~> 6.6)
    - GoogleUtilities/UserDefaults (~> 6.6)
    - PromisesObjC (~> 1.2)
  - FirebasePerformance (3.1.11):
    - FirebaseCore (~> 6.6)
    - FirebaseInstallations (~> 1.1)
    - FirebaseRemoteConfig (~> 4.4)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/ISASwizzler (~> 6.2)
    - GoogleUtilities/MethodSwizzler (~> 6.2)
    - GTMSessionFetcher/Core (~> 1.1)
    - Protobuf (~> 3.9)
  - FirebaseRemoteConfig (4.5.0):
    - FirebaseABTesting (~> 3.1)
    - FirebaseAnalyticsInterop (~> 1.4)
    - FirebaseCore (~> 6.2)
    - FirebaseInstallations (~> 1.1)
    - GoogleUtilities/Environment (~> 6.2)
    - "GoogleUtilities/NSData+zlib (~> 6.2)"
  - FLAnimatedImage (1.0.12)
  - FMDB (2.6.2):
    - FMDB/standard (= 2.6.2)
  - FMDB/standard (2.6.2)
  - FreeStreamer (3.9.3):
    - Reachability (~> 3.0)
  - GoogleAppMeasurement (6.6.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 1.30905.0)
  - GoogleDataTransport (6.2.1)
  - GoogleDataTransportCCTSupport (3.1.0):
    - GoogleDataTransport (~> 6.1)
    - nanopb (~> 1.30905.0)
  - GoogleSignIn (5.0.2):
    - AppAuth (~> 1.2)
    - GTMAppAuth (~> 1.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - GoogleToolboxForMac/Defines (2.2.2)
  - GoogleToolboxForMac/Logger (2.2.2):
    - GoogleToolboxForMac/Defines (= 2.2.2)
  - "GoogleToolboxForMac/NSData+zlib (2.2.2)":
    - GoogleToolboxForMac/Defines (= 2.2.2)
  - GoogleUtilities/AppDelegateSwizzler (6.6.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (6.6.0):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/ISASwizzler (6.6.0)
  - GoogleUtilities/Logger (6.6.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (6.6.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (6.6.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (6.6.0)"
  - GoogleUtilities/Reachability (6.6.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (6.6.0):
    - GoogleUtilities/Logger
  - GTMAppAuth (1.0.0):
    - AppAuth/Core (~> 1.0)
    - GTMSessionFetcher (~> 1.1)
  - GTMSessionFetcher (1.2.2):
    - GTMSessionFetcher/Full (= 1.2.2)
  - GTMSessionFetcher/Core (1.2.2)
  - GTMSessionFetcher/Full (1.2.2):
    - GTMSessionFetcher/Core (= 1.2.2)

**Comment by paulb777** [comment]
Thanks @YasinTian. Please update to the latest versions. `GoogleDataTransport` 7.x has several fixes that may address this issue.

**Comment by YasinTian** [comment]
Thank you. I will try it.
