### ISSUE TITLE
iOS framework with firebase Carthage binary, ask for firebase when deployed in ios app !!!

### ISSUE THREAD

**Issue by soufianee** [firebase/firebase-ios-sdk#6189]
* Xcode version: 11.6
  * Firebase Component: MLVision
  * Installation method: Carthage

Hi,

i have created a framework in Xcode using the  firebase Carthage binary to run the firebase in device text extraction. In my Mac it works fine with the test project.

unfortunately, when I shared with the integrator still get the error cam t find firebase framework. with is already linked with my framework in build time.

here is the capture of framework linked in my project : 

<img width="694" alt="Capture d’écran 2020-08-03 à 13 23 08" src="https://user-images.githubusercontent.com/11293769/89181991-a9417b00-d58c-11ea-81f7-d2065d0910f6.png">

<img width="798" alt="Capture d’écran 2020-08-03 à 13 23 52" src="https://user-images.githubusercontent.com/11293769/89182007-b1011f80-d58c-11ea-8a28-dfd3ad478a20.png">

**Comment by paulb777** [comment]
@soufianee Please make sure that your framework is statically linked. See https://github.com/firebase/firebase-ios-sdk/blob/master/docs/firebase_in_libraries.md

**Comment by soufianee** [comment]
hi, 

thank you for your response, I have to mention that I work with dynamique framework. all the setting required is set.

any idea please ??

**Comment by paulb777** [comment]
As documented in  https://github.com/firebase/firebase-ios-sdk/blob/master/docs/firebase_in_libraries.md, Firebase does not support linkage into a dynamic framework.

**Comment by soufianee** [comment]
hi,

i do the same thing but now I create a static library. but still same issues.

**Comment by soufianee** [comment]
<img width="1010" alt="Capture d’écran 2020-08-03 à 18 23 39" src="https://user-images.githubusercontent.com/11293769/89209589-86c45780-d5b6-11ea-985c-35b47769ebe4.png">

**Comment by morganchen12** [comment]
Can you share the build error from Xcode?

**Comment by soufianee** [comment]
<img width="1142" alt="Capture d’écran 2020-08-03 à 20 53 15" src="https://user-images.githubusercontent.com/11293769/89221626-7bc7f200-d5cb-11ea-81ec-bd995679c08d.png">

**Comment by morganchen12** [comment]
Can you export the full build log and share it here or upload a sample project?

**Comment by soufianee** [comment]
this is all I have in the build log.
I add the search path to the generated modules.

for information, is working for the framework creator.

here's the project folder :

<img width="605" alt="Capture d’écran 2020-08-03 à 21 34 43" src="https://user-images.githubusercontent.com/11293769/89224909-36a6be80-d5d1-11ea-828e-35298a00fca0.png">

**Comment by morganchen12** [comment]
You should be able to get the full build log by clicking the error in the left panel and then clicking the Export button at the top of the screen.

If you're unable to do so, can you share your project?

**Comment by soufianee** [comment]
here's the exported file  :

[x86_64-apple-ios-simulator.txt](https://github.com/firebase/firebase-ios-sdk/files/5018678/x86_64-apple-ios-simulator.txt)

also in the following we found the test project :

[sdkTest_v7.zip](https://github.com/firebase/firebase-ios-sdk/files/5018683/sdkTest_v7.zip)

**Comment by morganchen12** [comment]
There's a few issues here:
- The build log file you uploaded does not contain your target's build log.
- I could not build the project because the linked static framework was not built for iOS (arm64).
- The modulemap seems to contain Swift code, which is unsupported by Swift and will not work.

Since none of these issues are Firebase issues, you may have more success asking for help in a forum like StackOverflow.
