### ISSUE TITLE
6.29.0 doesn't respect minimumFetchInterval when set to 0 and always returns value from cache (except the first time)

### ISSUE THREAD

**Issue by shahzadmajeed** [firebase/firebase-ios-sdk#6208]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.5
  * Firebase SDK version: 6.29.0
  * Firebase Component: RemoteConfig & Analytics
  * Component version: 6.29.0
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

I need to refresh firebase remote configuration often (current refresh interval is 12 minutes) but apparently SDK fetches from remote server only the first time app is installed, doesn't matter which fetch function you use or whatever value you set for minimumFetchInterval. I also tried setting it to 0 but it didn't work. I updated Firebase Analytics & RemoteConfig to 6.29.0 hoping that this will fix the problem but still seeing this issue. I fail to understand why SDK won't fetch from remote server after expiration interval and what do I need to do in order to get it to working? What is your caching policy if `withExpirationDuration` or `minimumFetchInterval` is ignored and not respected? 

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:
```
let settings = RemoteConfigSettings()
settings.minimumFetchInterval = 0 // doesn't matter what you set here, it doesn't fetch from remote
frc.configSettings = settings

frc.fetchAndActivate { status, error in
      switch status {
            case .successFetchedFromRemote:
             // only enters here on first launch after installation
            case .successUsingPreFetchedData:
             // always enter here
           case .error:
            // so far I don't see it entering here
      }
}
```

**Comment by stevewilber** [comment]
Shahzad and I caught up on Slack regarding this issue. I believe he's been able to resolve it.

What was happening was that the SDK was going through the .successUsingPreFetchedData path because there were no changes made to the configuration on the server (I believe we return a 304). The naming of the enum is perhaps unclear in this case

**Comment by shahzadmajeed** [comment]
I agree, even if there is no change on backend `.successUsingPreFetchedData` is confusing when client requested a force refresh. Maybe return a `noChangeFound` or something?

Anyways, since this issue is resolved. I am going to close the thread. Thank you for your help!

-Shahzad
