### ISSUE TITLE
Firestore "no internet connection" error

### ISSUE THREAD

**Issue by HusamAamer** [firebase/firebase-ios-sdk#622]
* Xcode version: 9
  * Firebase SDK version: 4.8
  * Firebase Component: Firestore
  * Component version: 0.9.4

### The problem
When getting collection documents in offline, Firestore returns `error = nil` with empty snap, and the following error logged in the debug area .

> <Firebase/Network/ERROR> Encounter network error. Code, error: -1009, Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={NSUnderlyingError=0x1c025d700 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=https://play.googleapis.com/log, NSErrorFailingURLKey=https://play.googleapis.com/log, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, NSLocalizedDescription=The Internet connection appears to be offline.}

#### Is there a way to get no connection errors ??

I think It would be more convenient to have an error with no connection.
Even if data catches I prefer to have a cached snap with no connection error.

Regards,

**Comment by morganchen12** [comment]
If the Firestore error is nil, then it should mean the query returned a cached result successfully. The error printed to console references a domain that (from what I understand) isn't your Firestore database.

@wilhuff is this a bug, or intended behavior?

**Comment by wilhuff** [comment]
This is intended behavior. Firestore is supposed to work offline, so the fact that we can't connect to the server isn't an error case.

We recently added the log message to help developers understand why they weren't seeing any data (it's only logged if you're offline and have no data matching the query).

We recognize that there are some cases where you really care that you're talking to the server and really want to fail if you can't connect. We have a change forthcoming (https://github.com/firebase/firebase-ios-sdk/pull/655) that will allow you specify that you want the source to the server (and that you don't care about offline behavior) in which case you'll get the error you're expecting.

**Comment by tiagoalmeida** [comment]
@wilhuff sorry to comment after you closed this, but this issue is the closest I got with my current situation. Do you have any news on this?

I wasn't expecting that even with ```settings.isPersistenceEnabled = false``` I would get this behavior. I want to fetch documents and warn the user if he has no internet connection to try again. Is this possible with the current version?

**Comment by wilhuff** [comment]
The only update is that the ability to specify the source has since been released. If you want to get errors when the server is unavailable, pass `FirestoreSource.server` to data getting methods like `DocumentReference.getDocument(source:completion:)`.

**Comment by mikelehen** [comment]
@tiagoalmeida In general it would help if you elaborated on what you are trying to do and what you've tried.  Adding to @wilhuff's answer, I think you have a few possible approaches depending on what you're trying to do:

1. Use `query.getDocuments(source:.server)` and if you're offline you'll get an error.
2. Use `query.getDocuments()`) and check the returned snapshot for `snapshot.metadata.fromCache == true`. since by default getDocuments() will try to get an up-to-date snapshot from the server and only return from cache if that fails.
3. Use `query.addSnapshotListener(includeMetadataChanges:true, ...)` and check for `snapshot.metadata.fromCache == true` on the generated snapshots.  Any snapshots generated with fromCache==true indicate we haven't gotten data from the server yet, so you may be offline.

If you need more guidance, https://groups.google.com/forum/#!forum/google-cloud-firestore-discuss is a great place to ask Firestore usage questions.  And you can also open a brand new github issue if you have a specific bug or feature request for us to take a look at.  Thanks!

**Comment by jonalxh** [comment]
> The only update is that the ability to specify the source has since been released. If you want to get errors when the server is unavailable, pass `FirestoreSource.server` to data getting methods like `DocumentReference.getDocument(source:completion:)`.

Hi @wilhuff
Does it work with querySnapshots? How to do it?

**Comment by mikelehen** [comment]
@jonalxh Yes. `query.getDocuments(source:.server)`

**Comment by jonalxh** [comment]
@mikelehen Do you know if it works under Javascript SDK? I'm trying but it doesn't work.

**Comment by mikelehen** [comment]
@jonalxh It would help if you elaborated on what you tried and what happened, but yes, it should work on the JavaScript SDK as well.  `query.get({source: 'server'}).then(querySnap => ...)`

**Comment by tiagoalmeida** [comment]
Hi @mikelehen and sorry I didn't give any more context.

I am doing a simple thing: getting documents from a collection while I am offline. I totally missed ```source: .server```, but now with ```source: server``` I get the following:

```
Error Domain=FIRFirestoreErrorDomain Code=14 "Failed to get documents from server. (However, these documents may exist in the local cache. Run again without setting source to FIRFirestoreSourceServer to retrieve the cached documents.)" UserInfo={NSLocalizedDescription=Failed to get documents from server. (However, these documents may exist in the local cache. Run again without setting source to FIRFirestoreSourceServer to retrieve the cached documents.)}
```


And I can't seem to get the original Error (no connection). On the other hand, when I do a sign in while being online I can go to the Error's userInfo, in ```NSUnderlyingError``` and get the connection error.

**Comment by jonalxh** [comment]
@mikelehen Here is my code:

`firestore.collection("companies/" + id + "/files").where("foo", "==", bar) .orderBy("date").onSnapshot(async function (snapshotData) {...}`

It works fine, but I need to detect when Internet connection is lost. 
You suggested me to use **query.get({source: 'server'}).then(querySnap => ...)**, but the problem is that this kind of query just get the database info and does not listen for changes, if I change my code with `.onSnapshot({source: 'server'}).then(...)` it falls in the catch section and doesn't work. I've been searching through the firestore docs reference but there is not documentation about how to set options.

I hope you could help me.

**Comment by mikelehen** [comment]
@tiagoalmeida Can you elaborate on why you need the underlying connection error?

**Comment by mikelehen** [comment]
@jonalxh It sounds like you want option 3 from my post above.  Something like:

```
const query = firestore.collection("companies/" + id + "/files")
    .where("foo", "==", bar) .orderBy("date");
query.onSnapshot({includeMetadataChanges: true}, querySnap => {
  if (querySnap.metedata.fromCache) {
    console.log('Data is from cache. We aren't successfully connected to the backend right now.');
  }
  ...
});

**Comment by tiagoalmeida** [comment]
Hi, again @mikelehen. Thank you for your fast answers!

I need a way to inform the user that there isn't a connection to the internet, meaning the "problem" for the connection is on the user side, and I want to give him a way to retry later. This error is too generic for me to guarantee that this is an internet connection issue (contrary to the sign in, where I get the "specifics" of the error).

I am trying to avoid adding other connections to check "reachability" and cross-check this with Firebase, ideally when I try to establish a connection I would have a connection error that somehow, (either by its code or something else), informs me if it is a problem in the user's side or firebase side.

I am assuming this error would also occur in more scenarios other than an internet connection on the user side (eg, the collection path changed somehow, or firebase is down)

**Comment by mikelehen** [comment]
@tiagoalmeida You're welcome.  In general there's no sure way to know whether a user's internet is down or not. A connection error could mean that the internet is down, partially down, really slow, or as you note it could be an error on the Firebase side.  But all of these are likely indistinguishable, even if we provided the error message to you.

We can look into exposing more detailed signals about the SDK's online vs offline state, but for now the options described above are what we have. So if they end up being insufficient, you'll need to implement your own connection / reachability checks to meet your needs.  Sorry!

**Comment by tiagoalmeida** [comment]
@mikelehen Thank you once again.

Just wanted to know if it was possible and your answer is enough for me at the moment!

**Comment by jonalxh** [comment]
@mikelehen Thanks a lot for your help. It worked like a charm.

In my tests, after disconnecting WiFi it takes 30 seconds to browser to realize offline status, connecting again takes a little less time.
In my web app is very important to know quickly when the network is turned off. Is there an option to reduce this time?

**Comment by mikelehen** [comment]
@jonalxh No way to reduce this right now.  If this is critical for you, you may want to directly use the browser's online/offline events (https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/Online_and_offline_events). We have plans to better integrate with these in the Firestore SDK itself to make our offline logic a bit smarter, but I'm not sure when we will be able to tackle that.  cc/ @thebrianchen

**Comment by jonalxh** [comment]
@mikelehen I've tried it before comming here but it doesn't work as espected; it just works ok when I check the offline checkbox in Chrome DevTools, but if I disable my WiFi connection the online status is still true.

Thanks a lot for your help.

**Comment by mikelehen** [comment]
@jonalxh Huh, weird. Out of curiosity, what OS are you using?  On OSX, disabling Wifi triggers navigator.onLine to become false (and associated events to fire).

**Comment by jonalxh** [comment]
Hi @mikelehen and sorry for taking so long to answer.
When you wrote me the last comment I've checked on OSX and Windows, it worked, strangely there was a problem with my Linux distro.
I'm very grateful with you.

**Comment by mikelehen** [comment]
@jonalxh Ahh, interesting.  Well we've made improvements to integrate with navigator online/offline events (see https://github.com/firebase/firebase-js-sdk/pull/1809), but if linux Chrome isn't surfacing those events it won't help there. :-/
