### ISSUE TITLE
FR: Testers should be able to download to multiple devices from one account

### ISSUE THREAD

**Issue by brennobemoura** [firebase/firebase-ios-sdk#6220]
### Feature proposal

* Firebase Component: App Distribution

I am one hour trying to solve this problem with App distribution. One of the testers had already configured one cell phone on App Distribution and he can download the beta releases. But, he would like to set up a new cell phone and it is being tricky. Maybe I am doing it wrong, but I tried sending a new configuration link, and he try to access directly to  https://appdistribution.firebase.dev. All this possible solution didn't work.

I am wondering that the "right" way is revoking the access to App Distribution and send him a new configuration email.

This should be easier for those that already accepted and configured some phone. So, I would like to suggest that App Distribution uses the same link that it generate to configure a new device, but at the moment that the person type some email that already is accepted, App Distribution should allow the user to download again the Profile used to download test versions.

**Comment by brennobemoura** [comment]
I guess that this may be a bug report for devices running on iOS 10.3

**Comment by morganchen12** [comment]
@alexsinger is this a known limitation?

**Comment by alexsinger** [comment]
Hey, hmm something seems off. For example, if "tester A" accepts an invitation on their iPhone 8, at that point they're a tester of the app and can see the test app and release on their iPhone 8. "tester A" should then be able to go to their iPhone X, open appdistribution.firebase.dev, sign in, be taken through the flow to register their device be installing the profile, and then the tester should see the same test app and release they had access to on the iPhone 8.

@brennobemoura what did the tester experience when they visited appdistributiion.firebase.dev directly on their new device?

**Comment by willbattel** [comment]
I noticed this same behavior recently. I tried to have a tester register a second device but we couldn't get it to work.

We first tried using the same email, then tried with a second email. Even when using the second email it wouldn't work if the user signed into the same Google Account for both devices. We, the developers, never received the UUID for the second device but the tester sees "Waiting for Developer"

Please see my case with Firebase Support for more details, Case 00076371

**Comment by brennobemoura** [comment]
I think we may have more than one problem here that could be related to this FR.

---
### About downloading Profile on a new device
The first thing is about the profile download, which @alexsinger may suggest is to access appdistribution.firebase.dev to download the profile. This solution should be more clear on the Firebase Console, so we can tell the testers the right information. 

**What did work for me in the past, somehow, was to revoke the tester access and set again as a tester so firebase will send a new email to him.**

Something that we may have in mind is that Firebase App Distribution access doesn't mean that the device has permission to download the app, because Apple certificates are responsible for giving that permission. Revoking the access on App Distribution, will not remove that UUID on Apple development profile.

@willbattel not only you have this problem. When I google this "download profile firebase appdistribution", we all can check different cases of downloading the profile and getting the "Waiting for Developer" message. I think this should be another FR.

---
### About accessing appdistribution.firebase.dev

@alexsinger I confirmed with the tester that I was talking about and he tells me that accessing this URL works. When he opened it, the App Distribution shows the steps to configure a new device, so I guess it is working pretty well.

This information should be somewhere on Google documentation or in the Firebase console.

---
### About iOS 10.3

Accessing the appdistribution.firebase.dev on iOS 10.3 is not different, the website shows the steps to download the profile, but it doesn't work. The tester that have this problem couldn't download the profile. He said that he download the profile, but he couldn't install it on settings app. In fact, iOS doesn't recognize it as a profile, so the profile is not even listed in the settings app.

If firebase don't support iOS 10.3, this info should be somewhere too.

**Comment by morganchen12** [comment]
Thanks @brennobemoura, I'll discuss the other feature requests you filed with the team and update there instead of on this issue.
