### ISSUE TITLE
Can't build the project on XCode 12 beta 4

### ISSUE THREAD

**Issue by odarynakorolevych** [firebase/firebase-ios-sdk#6221]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12 beta 4
  * Firebase SDK version: 6.29.0
  * Firebase Component: DynamicLinks & Analytics
  * Component version: 6.29.0
  * Installation method: CocoaPods

#### Steps to reproduce:

Build the project

#### Relevant Code:

The following errors are shown: 
- Cannot find 'FirebaseApp' in scope
- Cannot find 'DynamicLinks' in scope

**Comment by DanMotataeanu** [comment]
Did you import them in the file you use them? 

I am building with the same Xcode version and having no issues with Analytics

**Comment by odarynakorolevych** [comment]
@DanMotataeanu I have the following import in the file:
### import Firebase

The problem is with Dynamic Links, not Analytics. Also on Xcode 11 I have no problems with it.

**Comment by paulb777** [comment]
This looks like a duplicate of #6066. Please try the [resolution](https://github.com/firebase/firebase-ios-sdk/issues/6066#issuecomment-662580211) there.

**Comment by odarynakorolevych** [comment]
@paulb777  Yes, 
### import FirebaseDynamicLinks
fixed the problem. Sorry for bugging you, I'm closing this issue.
