### ISSUE TITLE
Remote Config fetch fail 

### ISSUE THREAD

**Issue by MrNgoc** [firebase/firebase-ios-sdk#6242]
<img width="1340" alt="Screen Shot 2020-08-10 at 10 11 50" src="https://user-images.githubusercontent.com/19618530/89749742-3fc4ed80-daf3-11ea-8531-073737fadc79.png">

My app meets non-fatal error when fetch remote config.

Is it a bug? Or please advise how should I avoid it.

**Comment by martihag** [comment]
We are also seeing fetchAndActivate failing for some users the last few days.
By reinstalling they are able to fetch config again.

**Comment by morganchen12** [comment]
Are you able to provide any details or app logs around the failure?

**Comment by ivorsliide** [comment]
Hello Im also having issues on my app, we have also tested on old released versions, **RemoteConfig** is not coming back to us, On their page there is nothing about it... https://status.firebase.google.com/
I started facing this issue today but everything was working fine 3 days ago any ideas?

**Comment by danasilver** [comment]
Hi folks, I'm on the Remote Config team. We identified the issue and are rolling out a fix. Thanks for reporting the issue!

**Comment by morganchen12** [comment]
This is a backend-only fix and will not require a client SDK update.

**Comment by morganchen12** [comment]
Closing this issue as it should now be resolved. Please comment here if it regresses or open a new issue. Thanks all!
