### ISSUE TITLE
Invalid Token - Bug appears when creating duplicate apps with different Bundle ID's

### ISSUE THREAD

**Issue by PhilBelanger42** [firebase/firebase-ios-sdk#6268]
Okay, so I had developed an app (programmed in flutter) using the firebase_auth dart package, and that app is working perfectly fine, no issues.

The issue arrises when I try to duplicate the app for a second Bundle ID.  (Think same client, different end-user customer-base).  Every single time I boot up the app, authentication doesn't even let me enter in a phone number, just giving me an "Invalid Token" error.

flutter: Phone Auth Verification Failed: Invalid token.

I do start with a perfectly clear, clean copy of the app, that I have run on multiple devices, and it works.  I then replace the Bundle ID, download the new google-services.plist from Firebase (That has the correct Bundle ID and other information), (replacing the original, and making sure to include it in the runner directory through XCode, so the program knows), and replace the pertinent details such as the url in the info.plist, and the API Key in the AppDelegate.swift.

I've ensured that the Bundle ID I'm trying to develop on is covered via the Apple Provisioning Profiles in my Apple Developer Account.  

I've cleaned the build folder, updated to newer versions and various branches, but I keep getting stymied at this point in the project.  I've looked through all of the similar problems in your archives, but none of the advice or suggestions anyone has given has been able to help me.

I'm building on the following system:

Flutter (Channel master, 1.21.0-10.0.pre.70)
MacOS Catalina 10.15.6
XCode 11.6
VS Code 1.47.3

This app does have Push Notifications active, and requires them to work.

Again, to be clear, without changing ANY code, I have a fully function variant of the app.  But when changing to a new version of the Bundle ID, I get this error.

**Comment by morganchen12** [comment]
You should file this issue at the [FlutterFire repository](https://github.com/firebaseextended/flutterfire/issues). The maintainers there will have more context on the error, since it's being surfaced from the flutter layer.
