### ISSUE TITLE
Too much data Consumed by Firebase Crashlytics

### ISSUE THREAD

**Issue by dkalraYusata** [firebase/firebase-ios-sdk#6269]
Hello,
My app consuming two much dat on one min by Firebase crashylatcis. Its nearly 11 MB per min . After Killed the app from background also it called **cm.crashylatcis.com** and consume the data. Please help on it.
Firebase Pods :- pod 'Firebase/Crashlytics'
pod 'Firebase/Analytics'
pod 'GooglePlacePicker'
pod 'Firebase/Core'
pod 'Firebase/Messaging'

Pod Lock file
- Firebase/Analytics (6.20.0):
    - Firebase/Core
  - Firebase/Auth (6.20.0):
    - Firebase/CoreOnly
    - FirebaseAuth (~> 6.5.0)
  - Firebase/Core (6.20.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.3.1)
  - Firebase/CoreOnly (6.20.0):
    - FirebaseCore (= 6.6.4)
  - Firebase/Crashlytics (6.20.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 4.0.0-beta.5)
  - Firebase/Messaging (6.20.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 4.3.0)
  - FirebaseAnalytics (6.3.1):
    - FirebaseCore (~> 6.6)
    - FirebaseInstallations (~> 1.1)
    - GoogleAppMeasurement (= 6.3.1)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (= 0.3.9011)
  - FirebaseAnalyticsInterop (1.5.0)
  - FirebaseAuth (6.5.0):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 6.6)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.5)
    - GoogleUtilities/Environment (~> 6.5)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseAuthInterop (1.1.0)
  - FirebaseCore (6.6.4):
    - FirebaseCoreDiagnostics (~> 1.2)
    - FirebaseCoreDiagnosticsInterop (~> 1.2)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
  - FirebaseCoreDiagnostics (1.2.2):
    - FirebaseCoreDiagnosticsInterop (~> 1.2)
    - GoogleDataTransportCCTSupport (~> 2.0)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
    - nanopb (~> 0.3.901)
  - FirebaseCoreDiagnosticsInterop (1.2.0)
  - FirebaseCrashlytics (4.0.0-beta.5):
    - FirebaseAnalyticsInterop (~> 1.2)

**Comment by morganchen12** [comment]
Please fill out the issue template. It would be helpful to know how you're measuring data usage and any steps required to reproduce the issue.
