### ISSUE TITLE
Firestore not working, but everything else is

### ISSUE THREAD

**Issue by tomhicks** [firebase/firebase-ios-sdk#6272]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 11.3.1 (11C504)
  * Firebase SDK version: 6.30.0
  * Firebase Component: Firestore
  * Component version: 1.16.4 ??
  * Installation method: `CocoaPods` (select one)

#### Steps to reproduce:

What happened? How can we make the problem occur?
`Error: [firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.`

With a brand new project, using Firestore just results in this, on the simulator. I haven't tested on device yet.

I have seen other people have issues with API key restrictions and I have checked those (also have created multiple projects, and tested an old project with the new Firestore SDK (it breaks), and the new project with the old Firestore SDK (it works)).

Other parts of Firebase work (analytics, functions) so I reckon it's something to do with gRPC being blocked by something on my mac (I don't run antivirus or anything).

Interestingly, another project that uses a much older version of firebase works fine, and using the older firebase to connect to this new project works fine, too, so the issue has to be somewhere in the Firebase part.

Interestingly, the exact same issue is present on Android in the Emulator.

The Simulator and Emulator both definitely have network connections.

#### Relevant Code:

I am actually using React Native Firebase, but the issue is not in the translation layer, the error is produced in the native layer. So my call in RNFirebase is this:

```
firebase.firestore().collection('games').doc(id).get().then(console.log).catch(console.error)
```

**Comment by wu-hui** [comment]
You are right that there could be something blocking gRPC, but the fact that an older SDK works is interesting. 

Can you tell me the version of the older SDK that is working for you, i can try to see what has changed btw them.

**Comment by tomhicks** [comment]
Thanks for the reply.

From the old version's Podfile (working) bits that I think might be useful!:
```
- Firebase/Firestore (6.14.0):
    - Firebase/CoreOnly
    - FirebaseFirestore (~> 1.8.2)

...

  - "gRPC-C++ (0.0.9)":
    - "gRPC-C++/Implementation (= 0.0.9)"
    - "gRPC-C++/Interface (= 0.0.9)"
  - "gRPC-C++/Implementation (0.0.9)":
    - "gRPC-C++/Interface (= 0.0.9)"
    - gRPC-Core (= 1.21.0)
    - nanopb (~> 0.3)
  - "gRPC-C++/Interface (0.0.9)"
  - gRPC-Core (1.21.0):
    - gRPC-Core/Implementation (= 1.21.0)
    - gRPC-Core/Interface (= 1.21.0)
  - gRPC-Core/Implementation (1.21.0):
    - BoringSSL-GRPC (= 0.0.3)
    - gRPC-Core/Interface (= 1.21.0)
    - nanopb (~> 0.3)
  - gRPC-Core/Interface (1.21.0)

...

  - BoringSSL-GRPC (0.0.3):
    - BoringSSL-GRPC/Implementation (= 0.0.3)
    - BoringSSL-GRPC/Interface (= 0.0.3)
  - BoringSSL-GRPC/Implementation (0.0.3):
    - BoringSSL-GRPC/Interface (= 0.0.3)
  - BoringSSL-GRPC/Interface (0.0.3)
```

The new, not working one:

```
  - Firebase/Firestore (6.30.0):
    - Firebase/CoreOnly
    - FirebaseFirestore (~> 1.16.4)

...

  - "gRPC-C++ (1.28.2)":
    - "gRPC-C++/Implementation (= 1.28.2)"
    - "gRPC-C++/Interface (= 1.28.2)"
  - "gRPC-C++/Implementation (1.28.2)":
    - abseil/container/inlined_vector (= 0.20200225.0)
    - abseil/memory/memory (= 0.20200225.0)
    - abseil/strings/str_format (= 0.20200225.0)
    - abseil/strings/strings (= 0.20200225.0)
    - abseil/types/optional (= 0.20200225.0)
    - "gRPC-C++/Interface (= 1.28.2)"
    - gRPC-Core (= 1.28.2)
  - "gRPC-C++/Interface (1.28.2)"
  - gRPC-Core (1.28.2):
    - gRPC-Core/Implementation (= 1.28.2)
    - gRPC-Core/Interface (= 1.28.2)
  - gRPC-Core/Implementation (1.28.2):
    - abseil/container/inlined_vector (= 0.20200225.0)
    - abseil/memory/memory (= 0.20200225.0)
    - abseil/strings/str_format (= 0.20200225.0)
    - abseil/strings/strings (= 0.20200225.0)
    - abseil/types/optional (= 0.20200225.0)
    - BoringSSL-GRPC (= 0.0.7)
    - gRPC-Core/Interface (= 1.28.2)
  - gRPC-Core/Interface (1.28.2)

...

  - BoringSSL-GRPC (0.0.7):
    - BoringSSL-GRPC/Implementation (= 0.0.7)
    - BoringSSL-GRPC/Interface (= 0.0.7)
  - BoringSSL-GRPC/Implementation (0.0.7):
    - BoringSSL-GRPC/Interface (= 0.0.7)
  - BoringSSL-GRPC/Interface (0.0.7)
```

**Comment by wu-hui** [comment]
Hmm, I have found nothing meaning between the two versions..

I am wondering now if it works in a different network environment. I am suspecting something in your test environment is blocking the connections. Can you try to switch and test again, like maybe over hotspot over LTE or anything that is not affected by your current environment?
