### ISSUE TITLE
All user properties sent except Apple Search Ads events

### ISSUE THREAD

**Issue by sotrosh** [firebase/firebase-ios-sdk#6275]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.6
  * Firebase SDK version: 6.10.0
  * Firebase Component: Core (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 6.10.0
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

I'm trying to track Apple Search Ads campaign name, keywords etc. by saving it as user property values in Firebase. I setup Firebase attribution events tracking as mentioned in documentation below: https://support.google.com/firebase/answer/6317518?hl=en I attached iAd framework to the Xcode project and created property names in Firebase->User Properties menu.

The problem is that Firebase shows the list of user property names but they don't contain any values. In Firebase DebugMode it says that it sent Apple Search Ads events well:

> [Firebase/Analytics][I-ACS023087] User property set. Name, value: iad_conversion_type, Download
> [Firebase/Analytics][I-ACS023087] User property set. Name, value: iad_attribution, true
> [Firebase/Analytics][I-ACS023087] User property set. Name, value: iad_keyword, Keyword
> [Firebase/Analytics][I-ACS023087] User property set. Name, value: iad_country_or_region, US
> [Firebase/Analytics][I-ACS023087] User property set. Name, value: iad_org_name, OrgName
> [Firebase/Analytics][I-ACS023087] User property set. Name, value: iad_keyword_matchtype, Broad
> [Firebase/Analytics][I-ACS023087] User property set. Name, value: iad_adgroup_name, AdGroupName
> [Firebase/Analytics][I-ACS023087] User property set. Name, value: iad_campaign_name, CampaignName
> [Firebase/Analytics][I-ACS023087] User property set. Name, value: iad_creativeset_name, CreativeSetName
> [Firebase/Analytics][I-ACS023087] User property set. Name, value: iad_lineitem_name, LineName
> 

Additionally, even if user properties don't work Firebase should automatically track that data.
I'm running Apple Search Ads for the last 3 weeks and there are almost 1k downloads already.

P.S. Other user properties (I also tracking user settings) it displays well in Firebase.

#### Steps to reproduce:

```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool
{
    FirebaseApp.configure()
    ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)
    Utilities.recordAppleSearchAds()

    return true
}

...

static func recordAppleSearchAds()
{
    // for more details: https://developer.apple.com/documentation/iad/setting_up_apple_search_ads_attribution
    ADClient.shared().requestAttributionDetails { (dict, error) in
        
        do {
            
            if error == nil {
                
                for (_, attributionDetails) in dict! {
                    
                    for (key, value) in attributionDetails as! [String : NSObject] {
                        
                        // skip date and id values
                        if key.range(of: "-date") == nil && key.range(of: "-id") == nil {

                            let propertyNameUpdated = key.replacingOccurrences(of: "-", with: "_")
                            let propertyValue: String = value as! String
                            Analytics.setUserProperty(propertyValue, forName: propertyNameUpdated)
                            debugPrint("key: \(propertyNameUpdated), value \(value)")
                        }
                    }
                }
            }
        }
        catch {
            
            Analytics.logEvent("request_attribution_details_catch_crash", parameters: nil)
        }
    }
}
```

**Comment by paulb777** [comment]
Closing for staleness. Please comment or open a new issue to reopen.
