### ISSUE TITLE
Over 24 hours and still dSYMs files missing

### ISSUE THREAD

**Issue by hIUG** [firebase/firebase-ios-sdk#6277]
### [REQUIRED] Step 1: Describe your environment
  * Xcode version: 11.6 (11E708)
  * Firebase SDK version: NA (Refer to below components)
  * Firebase Components & Verison: 
	FirebaseCore - Version: 6.7.0
	Firebase/Messaging - Version: 6.24.0
	Firebase/Analytics - Version: 6.24.0
	Firebase/Crashlytics - Version: 6.24.0
  * Component versions: Above
  * Installation method: `CocoaPods 

### [REQUIRED] Step 2: Describe the problem
dSYMs are getting uploaded successfully with the below upload script from terminal but not reflecting on Firebase Crashlytics console. Tried uploading the zip file with all dSYM files and individually uploading the specific one dSYM file we're not being able to have insights into our crashes.

#### Steps to reproduce:
What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
Step 1: Downloaded dSYMs from AppStore connect.
Step 2: Run below upload script, upload is successful.
Step 3: Firebase Crashlytics console still shows dSYMs is missing even after more than 24 hours

#### Relevant Code:
dSYMs upload script:
/Users/xxxx/WorkSpace/ProjectRootDir/Pods/FirebaseCrashlytics/upload-symbols -gsp /Users/xxxx/WorkSpace/ProjectRootDir/xxxx/Firebase/Dev/GoogleService-Info.plist -p ios /Users/xxxx/dsyms/appDsyms.zip

#### Extra description:
Having the exact same issue as:
https://github.com/firebase/firebase-ios-sdk/issues/5327

At the end, the referenced issue was closed indicating a temporary delay but for our team crashes are still not being reported and it's been over 24 hours, even after trying uploading the zip file with all dSYM files and individually uploading the specific one dSYM file we're not being able to have insights into our crashes. This is a high priority for our team... We opened a Firebase support ticket but no response yet.
Could anyone assist on this?

> Hey all, the 24-hour delay was related to an outage and should be resolved now. If your dSYMs are still not listed as available or if you're having other migration troubles, please [file a support issue](http://firebase.google.com/support) so our staff can look at your project.
> 
> Closing this issue since it's not easily resolvable in GitHub comments; please file a support ticket instead of continuing to comment here.
> 
> _Originally posted by @morganchen12 in https://github.com/firebase/firebase-ios-sdk/issues/5327#issuecomment-616699688_

**Comment by morganchen12** [comment]
Hey @hIUG, sorry to hear you're still having trouble. Please follow the link in my original comment to file this issue with [Firebase Support](http://firebase.google.com/support) instead of on GitHub.
