### ISSUE TITLE
Mac APPS upgraded from Fabric to FirebaseCashkit, but a problem accessing a private folder in keychain was found in the new Mac system (10.15.5)! Cannot receive report when user is denied access!! This was not the case at Fabric before!

### ISSUE THREAD

**Issue by dingmriesgui** [firebase/firebase-ios-sdk#6288]
[REQUIRED] Step 1: Describe your environment

Xcode version: 11.6
Firebase SDK version: See below. Podfile just specifies unversioned Firebase/Crashlytics and Firebase/Analytics
Component version: See above
Installation method: CocoaPods
    pod 'FirebaseCore'
    pod 'Firebase/Crashlytics'
    pod 'FirebaseInstallations'
[REQUIRED] Step 2: Describe the problem

Steps to reproduce:

This is for a macOS application, running on macOS 10.15.4. I see the issue when signing my app with a Developer ID cert with the DEBUG flag, but I don't see it when running with a macOS Development certificate.

In applicationDidFinishLaunching, I have simply:

[FIRApp configure]

**Comment by ryanwilson** [comment]
Closing in favor of #6289 which appears to contain the same contents (plus screenshots).
