### ISSUE TITLE
Firebase Crashlytics not getting Enabled

### ISSUE THREAD

**Issue by arunlj561** [firebase/firebase-ios-sdk#6290]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 11.5 (11E608c)
  * Firebase SDK version:latest 
  * Firebase Crashyltics : 4.1.0 (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 4.1.0
  * Installation method: `CocoaPods 

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

I am not able to Enable Firebase-Crashlytics. 
Added Pods, Added Run Script
Crashed the apps still not able to Enable Crashlytics. 

![IMG_7395](https://user-images.githubusercontent.com/13132856/90506525-0d119980-e172-11ea-87af-39270c436b10.JPG)

Its loading since more than a week.

In AppDelegate.swift
FirebaseApp.configure()
Crashlytics.crashlytics().setCrashlyticsCollectionEnabled(true)

**Comment by ryanwilson** [comment]
Hi @arunlj561, a few questions to start off:

- Crashlytics is also on version 4.4.0 now, can you please update to the latest version and try again?
- Are you seeing any logs in the Xcode console? If so, can you please paste them here?
- Are other Firebase services working?

After you've updated, please share any logs in the Xcode console you're seeing, and if there are no logs please reach out to Firebase Support as we can't look into your project here, but Support can. If that's the case we'd close this issue.

Thanks!
