### ISSUE TITLE
Error 501 "Device ID and checkin info is not found. Will not proceed with subscription/unsubscription"

### ISSUE THREAD

**Issue by skipperprivate** [firebase/firebase-ios-sdk#6301]
### Environment

  * Xcode version: 12.0 beta 2
  * Firebase SDK version: 6.29.0
  * Firebase Component: Messaging

### Problem

I'm trying to implement the FCM topic mechanism for sending push notifications in a more balanced way.
To do this, I subscribe/ unsubscribe to the topics I need in the AppDelegate class in func `application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data)` method.
But if I need to make subscription/unsubscription at a random time while the app is running, I get an error Domain=com.google.fcm Code=501 "Device ID and checkin info is not found. Will not proceed with subscription/unsubscription".

#### Steps to reproduce:

I' m trying to subscribe to existing topic when Default Firapp is configured.

#### Relevant Code:

```
Messaging.messaging().unsubscribe(fromTopic: topicName) { error in
            guard error == nil else {
                print(String(perfect: error))
                return
            } 
            print( "Unsubscribed from \(topicName)")
        }
```
The use of such subscription attempts in the methods `application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil)` or `applicationDidBecomeActive(_ application: UIApplication)` causes the 501 error in the description.
Has anyone ever encountered such a problem and how to solve it?

**Comment by chliangGoogle** [comment]
You checkin data seems missing, did you check that you have a FCM token at at all? make sure you delete your token after unsubscribing because it still requires token to proceed.

**Comment by skipperprivate** [comment]
> You checkin data seems missing, did you check that you have a FCM token at at all? make sure you delete your token after unsubscribing because it still requires token to proceed.

I've added the subscribing method even to func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String) to be sure I have FCM token received - but nothing worked as I expected. What can it be?

**Comment by chliangGoogle** [comment]
Can you share with us the debugLog here?

**Comment by BouweCeunen** [comment]
I've also encountered this on an app in production, but not being able to reproduce it myself.

**Comment by skipperprivate** [comment]
> Can you share with us the debugLog here?
2020-08-26 14:23:33.368732+0300 appname[687:176018] 6.29.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
2020-08-26 14:23:33.494778+0300 appname[687:176018] 6.29.0 - [Firebase/Core][I-COR000001] Configuring the default app.
2020-08-26 14:23:33.507317+0300 appname[687:176015] 6.29.0 - [Firebase/Installations][I-FIS002000] -[FIRInstallationsIDController createGetInstallationItemPromise], appName: __FIRAPP_DEFAULT
2020-08-26 14:23:33.687361+0300 appname[687:176074] 6.29.0 - [Firebase/Installations][I-FIS002001] -[FIRInstallationsIDController installationWithValidAuthTokenForcingRefresh:0], appName: __FIRAPP_DEFAULT
 that's part of them after which it refuses to subscribe periodically

**Comment by morganchen12** [comment]
@skipperprivate are you calling `FirebaseApp.configure()` in your code? If so, and you're still getting the errors in these logs, you likely have duplicate Firebase classes in your app runtime.

**Comment by skipperprivate** [comment]
> @skipperprivate are you calling `FirebaseApp.configure()` in your code? If so, and you're still getting the errors in these logs, you likely have duplicate Firebase classes in your app runtime.
Yes, I am. Why do these duplicates cause errors?

**Comment by morganchen12** [comment]
See [this StackOverflow answer](https://stackoverflow.com/questions/60753233/the-default-firebaseapp-instance-must-be-configured-before-the-defaultfirebaseap/61352175?noredirect=1#comment111575298_61352175)

**Comment by skipperprivate** [comment]
> See [this StackOverflow answer](https://stackoverflow.com/questions/60753233/the-default-firebaseapp-instance-must-be-configured-before-the-defaultfirebaseap/61352175?noredirect=1#comment111575298_61352175)

This answer recommends to remove duplicate inits as I understand.
But in my logs there is no such situation.

**Comment by morganchen12** [comment]
Can you share a sample project that reproduces this issue?

**Comment by BouweCeunen** [comment]
I'm getting this from Sentry if it could help. 
![image](https://user-images.githubusercontent.com/5576686/92722487-fb35a780-f367-11ea-9658-7c74a90886f1.png)

Did not yet encounter it myself, this is from production users, so not sure how to reproduce it. In what cases can this occur?
