### ISSUE TITLE
No Google App ID or Google Services file provided

### ISSUE THREAD

**Issue by carlosdelamora** [firebase/firebase-ios-sdk#6306]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.6
  * Firebase SDK version: 6.30.0
  * Firebase Component: Crashlytics 
  * Component version: 4.4.0
  * Installation method: `CocoaPods` 

### [REQUIRED] Step 2: Describe the problem
I am not getting crash reports on firebase console. I assume that the issue is that I can not upload the dSYM files. However firebase console does not indicate that the dSYM files are missing.  When I try to upload the dSYM files to firebase running the script 
`/path/to/pods/directory/FirebaseCrashlytics/upload-symbols -gsp /path/to/GoogleService-Info.plist -p ios /path/to/dSYMs` on terminal. I get the following error, `No Google App ID or Google Services file provided`. 

The `GoogleService-info.plist` file is added and I receive other information on the console like `Users in last 30 minutes`, `Active users` etc. 

I do not know if this is relevant but I have two schemes, `dev` and `prod` but I am only interested on having `Crashlytics` integration with `prod`. So I am only using one `GoogleService-info.plist`. 

I would like to know if the reason why I am getting no reports is because my dSYM files are missing even though is not indicated by the firebase console and why I can not upload the dSYM files with the above script. 
#### Steps to reproduce:

add the following to your pod file 
```
pod 'Firebase/Crashlytics'
pod 'Firebase/Analytics'
```
include your `GoogleService-info.plist` into your project. 
run `pod install`
run `/path/to/pods/directory/FirebaseCrashlytics/upload-symbols -gsp /path/to/GoogleService-Info.plist -p ios /path/to/dSYMs` on terminal.

#### Relevant Code:
```
/Users/carlosdelamora/Desktop/swiftkick/all-world-ios/Pods/FirebaseCrashlytics/upload-symbols -gps /Users/carlosdelamora/Desktop/swiftkick/all-world-ios/AllWorld/Application/GoogleService-Info.plist -p ios /Users/carlosdelamora/Downloads/appDsyms
```
return `error: No Google App ID or Google Services file provided`

**Comment by cvaghela** [comment]
Can you reach out to [Firebase Support](https://firebase.google.com/support/troubleshooter/contact) with your GoogleService-info.plist and dSYM files that you're trying to upload?

**Comment by BrunooShow** [comment]
same error here similar scenario any update on it ? @carlosdelamora

**Comment by carlosdelamora** [comment]
I have contacted Firebase Support, they are helping me, but still have not figure it out.

**Comment by wtmoose** [comment]
> `/Users/carlosdelamora/Desktop/swiftkick/all-world-ios/Pods/FirebaseCrashlytics/upload-symbols -gps /Users/carlosdelamora/Desktop/swiftkick/all-world-ios/AllWorld/Application/GoogleService-Info.plist -p ios /Users/carlosdelamora/Downloads/appDsyms`

The correct argument is `-gsp`, not `-gps`

**Comment by wtmoose** [comment]
@TKBurner can we turn this into a feature request to improve the command-line parser? Then typically throw an error if you supply an unsupported argument
