### ISSUE TITLE
165847014:ios the app always goes to the appstore: having a previous version of the app in the market and adding dynamic links

### ISSUE THREAD

**Issue by pabloearg** [firebase/firebase-ios-sdk#6308]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.6 and 11.4
  * Firebase SDK version: 6.28.1
  * Firebase Component: Firebase/DynamicLinks
  * Component version: 6.28.1
  * Installation method: CocoaPods

### Step 2: Describe the problem

we have an app in the appstore right now that has branch.io, and we are replacing that for firebase dynamic links

But for some reason, in some ios devices and with a few apps  (messages, whatsapp and others...)  when opening our link , the link goes to safari directly, and then goes to the appstore, even if we have the app installed in the iphone or ipad.

i have installed ad-hoc versions of the ipa and even run the app directly from the xcode, but im getting different behaviours between iphones and applications that triggers the links

the link works great for example if a share the link through facebook messenger, of if i open mail mail on chrome and then click the link that ive send previously in the body of the email

when we create the links we are using this flag:

 ```
        forcedRedirectEnabled: true,
```
we followed every step in your documentation and in the  [firebase tutorial](https://youtu.be/KLBjAg6HvG0)

#### Steps to reproduce:

1. create a deep link send it through an  sms to another iphone
2. click the link
3. watch how the safari is opened an then it goes to the appstore

is this the expected behaviour? is apple checking if the app that is installed in the phone was downloaded from the store before? i didnt find any documentations that support this

**Comment by eldhosembabu** [comment]
Could you please provide the Firebase Dynamic Link which is causing this issue?

**Comment by pabloearg** [comment]
@eldhosembabu 
all links are causing this, (this link will no work in our production build, because now we are using branch.io)

[here is an example:](https://goalsettertest.page.link/dTh456BQPJfKUrvh6)

**Comment by MINISOCKS** [comment]
@pabloearg hello, have you solved this problem? We have same issue with you --A previous production version. When i type the url in safari, it will always go to app store first, even if we have our debug or release app on the phone. And have you upgraded your production app? Does it work?

**Comment by pabloearg** [comment]
@MINISOCKS  if you type the url in safari, according to the universal links documentations, you will always be redirected to the appstore.

Dynamic links are not supposed to be using like this. you have to "click them".

in my case after i've open them, for example in whatsapp, i got redirected to safari and then to the appstore, instead to my app

**Comment by ergunkocak** [comment]
Did you find a solution? In my case link always opens safari and then the app store as you. But if i type the link in chrome app and enter, it opens my app 😕

**Comment by ergunkocak** [comment]
For me it worked after releasing in Testflight 🤷‍♂️

**Comment by eldhosembabu** [comment]
Glad that it worked. Have you tried with forcedRedirectEnabled: false while creating the link?

**Comment by ergunkocak** [comment]
Strang after the app release the dynamic links is not working any more :( 
It is opening the app store app detail page while the app is installed.
- Info.plist contains the domains
- Firebase SDK is up to date and contains "Firebase/DynamicLinks" and "Firebase/Analytics" as per documentation : https://firebase.google.com/docs/dynamic-links/ios/receive?authuser=0
- apple-app-site-association url content is correct
- performDiagnostic completed successfully! No errors found.

Any suggestions?

Links are created in Firebase console so i have no idea about "forcedRedirectEnabled" :)

**Comment by paulb777** [comment]
Closing for staleness. Please comment or open a new issue to reopen.
