### ISSUE TITLE
iOS 14 App Clip SIGABRT crash - Library not loaded: @rpath/FBLPromises.framework/FBLPromises

### ISSUE THREAD

**Issue by thoughtcastapp** [firebase/firebase-ios-sdk#6311]
#### Steps to reproduce:

Have an app that uses Firestore for its DB (made a core app and an app clip as a separate ios target before app clips were available). Added an app clip and used cocoapods to add the firstore libraries to the app clip. Linked the app clip to my pre-built app/migrated the files over and tried to simulate it. Build compiled and ran, but it crashed before launching with the following message:

dyld: Library not loaded: @rpath/FBLPromises.framework/FBLPromises
  Referenced from: /Users/me/Library/Developer/CoreSimulator/Devices/DD041252-ED8B-4632-B820-632FBED68C6F/data/Containers/Bundle/Application/8F8F902B-CF66-4856-B6AE-F7C2F35B950B/AppClipCrashClip.app/AppClipCrashClip
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_SHARED_CACHE_DIR=/Users/me/Library/Developer/CoreSimulator/Caches/dyld/19G73/com.apple.CoreSimulator.SimRuntime.iOS-14-0.18A5351d
DYLD_ROOT_PATH=/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot
DYLD_LIBRARY_PATH=/Users/benjaminbudzak/Library/Developer/Xcode/DerivedData/AppClipCrash-ahhaaayjbotetccsbcrwnlrpbode/Build/Products/Debug-iphonesimulator:/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPh

#### Relevant Code:
None

```
// TODO(you): code here to reproduce the problem
```
To reproduce, make an a new ios app in xcode, add an app clip, make a new podfile and add firebase to it (I added Auth, Firestore and Database). Then, follow the stock instructions for initializing firebase in the app clip and run the app clip to a simulator or device...

**Comment by ryanwilson** [comment]
Hi, @thoughtcastapp sorry for the issues you're seeing.

Re: Library not loaded, this is the same issue as #4889. Specifically, the workaround here: https://github.com/firebase/firebase-ios-sdk/issues/4889#issuecomment-596147745

Unfortunately though, Firestore does not currently work in App Clips on device. You can follow along with progress at #6211, and I'll close this issue.

**Comment by thoughtcastapp** [comment]
gotcha, just a note for anyone reading this after the ticket was closed, I tried #4889, but there are some libraries that swift won't allow static linkage to in firebase (I believe boring ssl is one of them), so that solution will not work for this issue...here's to hoping you guys can figure out a solution :)
