### ISSUE TITLE
FR: Open-sourcing Crashlytics upload-symbols

### ISSUE THREAD

**Issue by michaeleisel** [firebase/firebase-ios-sdk#6322]
### Feature proposal

* Firebase Component: Crashlytics

The upload-symbols script has gotchas such as issues around parsing paths with spaces in them. I am facing a few additional ones myself right now. By open-sourcing it, it could reduce the number of issues coming in for people dealing with the tool, because they could potentially debug/fix it locally themselves. It could also lead to PRs for improvements. If cSYM conversion is involved/some other sensitive thing is going on, that could be split out, but the basic high-level argument parsing and file operations would be very nice to have open-source

**Comment by adamvduke** [comment]
Hi @michaeleisel,

Thanks for bringing this up. We are interested in open-sourcing upload-symbols in the future, but it is not on our current roadmap. We’re currently judging interest and will keep the community updated if things change.
