### ISSUE TITLE
Crashlytics website cant find app

### ISSUE THREAD

**Issue by bzhu9** [firebase/firebase-ios-sdk#6324]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.6
  * Firebase SDK version: 6.3.0
  * Firebase Component: Crashlytics 
  * Component version: 4.2.0
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem
I tried installing Firebase Crashlytics in my project following the steps listed in the docs. I brought in the Firebase/Crashlytics and Firebase/Analytics pods via podfile and then added in the run script "${PODS_ROOT}/FirebaseCrashlytics/run".

When I built and ran the code, the firebase console for crashlytics did not recognize that the app had connected and the spinner kept spinning. How do I get the console to recognize my app connecting to crashlytics.

I have been able to connect to firebase storage, database, and authentication without a problem in the app.
#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:
The following warning showed up when I added in the steps:

`Running upload-symbols in Build Phase mode
Validating build environment for Crashlytics...
warning: DEBUG_INFORMATION_FORMAT should be set to dwarf-with-dsym for all configurations. This could also be a timing issue, make sure the Fabric run script build phase is the last build phase and no other scripts have moved the dSYM from the location Xcode generated it. Unable to process BasicChat.app.dSYM at path /Users/zhu/Library/Developer/Xcode/DerivedData/BasicChat-axpmjgpqwbquaegtctljtvsnlpgz/Build/Products/Debug-iphonesimulator/BasicChat.app.dSYM
Make sure your project build settings are generating a dSYM file.

Validation succeeded. Exiting because upload-symbols was run in validation mode`

**Comment by bzhu9** [comment]
I called a pod update and crashlytics was updated to 4.4.0 but this did not fix the error. The firebase console still shows "We’ll be listening for your app to communicate with our servers."

**Comment by morganchen12** [comment]
Are there any errors from Crashlytics in your app's logs?

**Comment by bzhu9** [comment]
There are no errors in the logs, in fact the app is able to find the crashlytic pod and print its version
`2020-08-23 21:34:54.723241-0400 BasicChat[37996:4854519] [Firebase/Crashlytics] Version 4.4.0`

There are other messages in the logs related to Analytics, but I'm pretty sure it doesn't affect Crashlytics from connecting
`2020-08-23 21:34:56.382874-0400 BasicChat[37996:4854679] 6.30.0 - [Firebase/Analytics][I-ACS023007] Analytics v.60702000 started
2020-08-23 21:34:56.385014-0400 BasicChat[37996:4854679] 6.30.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2020-08-23 21:34:56.386149-0400 BasicChat[37996:4854679] 6.30.0 - [Firebase/Analytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
2020-08-23 21:34:57.476216-0400 BasicChat[37996:4854678] 6.30.0 - [Firebase/Analytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
2020-08-23 21:34:57.879705-0400 BasicChat[37996:4854678] 6.30.0 - [Firebase/Analytics][I-ACS023012] Analytics collection enabled`

**Comment by morganchen12** [comment]
Sounds like there's nothing wrong on your app's side. Can you [file a support ticket to look](https://firebase.google.com/support) into why it's not connecting to your app in Firebase console?

**Comment by Alaakhodor** [comment]
try to add Input Files to your Build script in Build phases, i think it will work.

![image](https://user-images.githubusercontent.com/34441403/91127625-518bc080-e6af-11ea-816f-41a92045c76c.png)

**Comment by bzhu9** [comment]
I was able to connect to the Firebase Console by forcing a crash as implemented here: https://firebase.google.com/docs/crashlytics/test-implementation?platform=ios#force_a_crash_to_test_your_implementation
