### ISSUE TITLE
FR: Add ServerTimestampBehavior option to FirebaseFirestoreSwift

### ISSUE THREAD

**Issue by nathanvogel** [firebase/firebase-ios-sdk#6328]
### Feature proposal

* Firebase Component: FirebaseFirestoreSwift.

These are the currently available methods to get data from a document, if FirebaseFirestoreSwift is installed:

![Screenshot 2020-08-25 at 11 16 03](https://user-images.githubusercontent.com/3106715/91156790-d503dc80-e6c4-11ea-98d3-04679fa4c044.png)

I would expect these additional methods, so that all use cases are covered: 
```swift
data(as: Decodable.Protocol, with: ServerTimestampBehavior) throws
data(as: Decodable.Protocol, with: ServerTimestampBehavior, decoder: Firestore.Decoder?) throws
``` 

This would also go towards feature parity with the Kotlin Android SDK.

Thank you, 
Cheers

**Comment by wilhuff** [comment]
This is an oversight and we'll put this together. Thanks for pointing it out!

**Comment by nathanvogel** [comment]
Glad to read it, thanks!
