### ISSUE TITLE
Error when archiving: Umbrella header for module 'GoogleUtilities' does not include header 'GULLoggerCodes.h'

### ISSUE THREAD

**Issue by rebello95** [firebase/firebase-ios-sdk#6339]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: `11.5`
  * Firebase SDK version: `6.31.0`
  * Firebase Component: `Auth` & `Core`
  * Component version: `FirebaseAuth (6.9.0)` & `Firebase/Core (6.31.0)`
  * Installation method: `CocoaPods` with `use_frameworks!` in the `Podfile`

#### Steps to reproduce:

I'm running into some compilation errors when archiving my application (see screenshot below):

```
/Users/mrebello/Development/path/ios/Pods/<module-includes>:1:1: Umbrella header for module 'GoogleUtilities' does not include header 'GoogleUtilities-00567490-umbrella.h'

/Users/mrebello/Development/path/ios/Pods/<module-includes>:1:1: Umbrella header for module 'GoogleUtilities' does not include header 'GULLoggerCodes.h'

/Users/mrebello/Development/path/ios/Pods/FirebaseCoreDiagnostics/GoogleUtilities/Logger/Private/GULLogger.h:22:9: Could not build module 'GoogleUtilities'

In file included from /Users/mrebello/Development/path/ios/Pods/FirebaseCoreDiagnostics/Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m:24:
```

I only hit this error when archiving for release. It works fine when building for debug.

This seems potentially related to https://github.com/firebase/firebase-ios-sdk/issues/4087. I was actually getting those warnings before switching back to the legacy build system based on suggestions in the issue.

Things I've tried:

- Cleaning, removing `DerivedData`, `pod deintegrate`, deleting `.xcworkspace`
- Upgrading CocoaPods
- Switching to Xcode 11.6 (11.5 also doesn't work)
- Adding a custom set of `google_utilities` as described [in this issue](https://github.com/firebase/firebase-ios-sdk/issues/4087#issuecomment-545841819)
- Adding a `post_install` rule as described [here](https://stackoverflow.com/a/35318277/1145804)
- Verified `Always Search User Paths` is set to `NO` for the app target
- Verified `DEFINES_MODULE` is set to `NO` for the app target

#### Relevant Code:

`Podfile.lock` file available in this gist: https://gist.github.com/rebello95/b4ee8265fa8e60b5c40da9a2c1678cf7

Screenshot of error:

<img width="1395" alt="Screen Shot 2020-08-26 at 12 01 24 PM" src="https://user-images.githubusercontent.com/2643476/91345221-dfd97280-e793-11ea-8d03-68a101964f6e.png">

**Comment by paulb777** [comment]
@rebello95 Thanks for the thorough report. I'm able to successfully archive https://github.com/firebase/quickstart-ios/tree/master/authentication with Xcode 11.6 which should have the same Firebase pods as your example.

The numeric suffix in your log `GoogleUtilities-00567490` makes it look like something prevented GoogleUtilities from consolidating into a single library.

Some suggestions.

- See if you have the same issue with the Quickstart
- Update the Podfile so GoogleUtilities library is unified. Maybe flushing DerivedData will do this?
- If you're still stuck, share a reproducible example

**Comment by rebello95** [comment]
Thanks for the response @paulb777! I was able to simplify my project and create a small app that reproduces this issue. I think the key is that I have both a framework _and_ the main app in my `Podfile` both depending on one more more Firebase/Google pods. 

**Here's the project: [GoogleUtilTest.zip](https://github.com/firebase/firebase-ios-sdk/files/5134038/GoogleUtilTest.zip)**

With the above project, the issue is reproducible after running `pod install` and attempting to archive the main app target:

<img width="583" alt="Screen Shot 2020-08-26 at 9 22 35 PM" src="https://user-images.githubusercontent.com/2643476/91384187-c9a6d300-e7e2-11ea-95ee-fe50749ffda7.png">

When using the new build system, I instead run into the same issue as https://github.com/firebase/firebase-ios-sdk/issues/4087:

<img width="563" alt="Screen Shot 2020-08-26 at 9 22 12 PM" src="https://user-images.githubusercontent.com/2643476/91384232-e7743800-e7e2-11ea-9083-8632cca727b7.png">
 
I attempted to pin `GoogleUtilities` and `GTMSessionFetcher` to the same version in both targets, but that didn't seem to help the issue. Any insights would be much appreciated!

**Comment by paulb777** [comment]
See the [resolution](https://github.com/firebase/firebase-ios-sdk/issues/4087#issuecomment-545841819) in #4087.  Make sure that the GoogleUtilities subspecs match across the target.

Once that is resolved depending upon the structure of the app, there may be issues with multiple copies of Firebase pods linked in. See https://github.com/firebase/firebase-ios-sdk/blob/master/docs/firebase_in_libraries.md

**Comment by rebello95** [comment]
Thank you @paulb777! I had tried that previously with no luck, but when attempting it again it looks like I had missed one of the static frameworks which also used a Firebase pod in my `Podfile`. Adding the following to my `Podfile` fixed the issue, based on the suggestion in that issue:

```
# Should be referenced for anything below that transitively uses GoogleUtilities
platform :ios, '12.0'
use_frameworks!

# https://github.com/firebase/firebase-ios-sdk/issues/6339
# Should be referenced for anything below that transitively uses GoogleUtilities
def google_utilites
  pod 'GoogleUtilities/AppDelegateSwizzler'
  pod 'GoogleUtilities/Environment'
  pod 'GoogleUtilities/ISASwizzler'
  pod 'GoogleUtilities/Logger'
  pod 'GoogleUtilities/MethodSwizzler'
  pod 'GoogleUtilities/NSData+zlib'
  pod 'GoogleUtilities/Network'
  pod 'GoogleUtilities/Reachability'
  pod 'GoogleUtilities/UserDefaults'
end

target 'MyFramework1' do
  google_utilites

  pod 'Firebase/Auth'
end

target 'MyFramework2' do
  google_utilites

  pod 'Firebase/Auth'
  pod 'Firebase/Core'
end

target 'MyApp' do
  google_utilites

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Crashlytics'
end
```

I also read through the `Firebase in libraries` doc you sent over, and it looks like my setup should be OK since I'm using static frameworks and do not have app extensions.

Thanks again for all your help on this! 🙏
