### ISSUE TITLE
Messaging.messaging().fcmtoken! today began to return the nil

### ISSUE THREAD

**Issue by ZubenkoIlya** [firebase/firebase-ios-sdk#634]
Hello everybody. I have a problem. Yesterday the code worked properly, the application was launched, but today it gives an error.

On this line:
`let user = Messaging.messaging().fcmToken!`

Here's the error:

> fatal error: unexpectedly found nil while unwrapping an Optional value

I do not know what the problem is.

**Comment by ZubenkoIlya** [comment]
I got some solution for this. Firebase will take some time to connect to FCM. So what I did is, I make my code to update after 5 seconds if FIRInstanceID.instanceID().token() returns nil. Within 5 seconds Firebase will connected to FCM. This is not the perfect solution but now this is the only way to solve it.

**Comment by morganchen12** [comment]
You should handle FCM token refreshes via the [`FIRMessagingDelegate` protocol](https://firebase.google.com/docs/reference/ios/firebasemessaging/api/reference/Protocols/FIRMessagingDelegate#/c:objc(pl)FIRMessagingDelegate(im)messaging:didReceiveRegistrationToken:).
