### ISSUE TITLE
Crashed: com.apple.main-thread EXC_BREAKPOINT 0x0000000104218738

### ISSUE THREAD

**Issue by Rushang007** [firebase/firebase-ios-sdk#6344]
I use Firebase crash reporting (latest) in my app and get lots of same crash report and I am not able to fix this issue.because while I'm testing in its I'm not getting any crash but Firebase Show that Crash report.

Here is that Crash report and that is no issue with iOS 

![Screenshot 2020-08-27 at 4 01 37 PM](https://user-images.githubusercontent.com/16713953/91431885-9f0a5800-e87e-11ea-9115-4e4e044aa556.png)

* Xcode version:  11.2.1
  * Firebase SDK version: 6.31.0
  * Firebase Component: Firebase/Crashlytics
  * Installation method: CocoaPods

**Comment by ryanwilson** [comment]
Hi @Rushang007,

It looks like this is an issue with your app and not the Firebase SDKs. It's possible (and very likely) that there are issues happening in your app that you are unable to reproduce. It's worth looking at the code mentioned in the crash report and see if there's anything that sticks out there, any assumptions you've made about data or a certain state of the app, etc.

Good luck in tracking down the issue and thanks for using Crashlytics!

**Comment by Rushang007** [comment]
@ryanwilson  Thanks for Quick Reply

 But I want to know that I tested in many phones but there is no crash So I can't Debug it Can you please help me exactly what line my app crash. it's Crash App or Just Crash Code

**Comment by morganchen12** [comment]
Hey @Rushang007, unfortunately Firebase staff does not have the bandwidth to provide personal debugging assistance into non-Firebase issues. You may find more help on a general programming forum like StackOverflow, but be aware that most other developers will not be able to effectively debug an issue in your code without any understanding of your codebase.

**Comment by Rushang007** [comment]
hey @morganchen12, thanks for Reply 

I can understand what you trying to say but I had check everywhere but some form have no answer that issues and also check in apple developer community but no answer found. what I think Crash means it will break some line on code in IDE, but this issue has no break anywhere also I tried in many devices but no breakdown. So why firebase increases that issue in Crashlytics. and no complaint from our Customer for the crash app.
