### ISSUE TITLE
FR: Excluding redundant packages

### ISSUE THREAD

**Issue by borut-t** [firebase/firebase-ios-sdk#6345]
### Feature proposal

I'm currently using a few packages from firebase (using cocoapods), here is the list:
```swift
pod 'Firebase/Auth'
pod 'Firebase/Messaging'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Crashlytics'
pod 'Firebase/Analytics'
pod 'Firebase/Storage'
pod 'FirebaseUI/Email'
```

Reviewing the `Podfile.lock` file reveals that there are multiple top-level packages installed that I didn't want. Just to name a few:
- FirebaseABTesting
- FirebaseInstallations
- FirebaseInstanceID
- GoogleAppMeasurement
- GoogleDataTransport
- ...

Now wondering if there is a way I can exclude some (probably not all) packages from my app? I would like to reduce the size of the app and every redundant package is well, redundant.

I completely understand that some of those packages are utility packages to the main libs. But probably not all of them are required, are they?

E.g. `FirebaseABTesting` is never used in my app so why bother bundling it in?

So, my proposal/feature request here is that you should be transparent on what is included besides the top-level packages and omit the ones that are not "required".

**Comment by paulb777** [comment]
@borut-t CocoaPods and Firebase do not install extra pods. If you search the `Podfile.lock` for any of the questioned pods, you'll see them indented under the pods that require them.

Firebase is architected with extra pods to increase code sharing, enable more granular installations, and decrease overall size.

**Comment by borut-t** [comment]
@paulb777 I wouldn't be so sure about it. Let's check the `Podfile.lock` file:

```
  - Firebase/Analytics (6.27.1):
    - Firebase/Core
  - Firebase/Auth (6.27.1):
    - Firebase/CoreOnly
    - FirebaseAuth (~> 6.6.0)
  - Firebase/Core (6.27.1):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.6.2)
  - Firebase/CoreOnly (6.27.1):
    - FirebaseCore (= 6.8.1)
  - Firebase/Crashlytics (6.27.1):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 4.2.0)
  - Firebase/Messaging (6.27.1):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 4.5.0)
  - Firebase/RemoteConfig (6.27.1):
    - Firebase/CoreOnly
    - FirebaseRemoteConfig (~> 4.6.0)
  - Firebase/Storage (6.27.1):
    - Firebase/CoreOnly
    - FirebaseStorage (~> 3.7.0)
  - FirebaseABTesting (3.3.0):
    - FirebaseCore (~> 6.8)
    - Protobuf (>= 3.9.2, ~> 3.9)
  - FirebaseAnalytics (6.6.2):
    - FirebaseCore (~> 6.8)
    - FirebaseInstallations (~> 1.4)
    - GoogleAppMeasurement (= 6.6.2)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 1.30905.0)
  - FirebaseAuth (6.6.0):
    - FirebaseCore (~> 6.8)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.5)
    - GoogleUtilities/Environment (~> 6.5)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseCore (6.8.1):
    - FirebaseCoreDiagnostics (~> 1.3)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
  - FirebaseCoreDiagnostics (1.4.0):
    - GoogleDataTransportCCTSupport (~> 3.1)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
    - nanopb (~> 1.30905.0)
  - FirebaseCrashlytics (4.2.0):
    - FirebaseCore (~> 6.8)
    - FirebaseInstallations (~> 1.1)
    - GoogleDataTransport (~> 6.1)
    - GoogleDataTransportCCTSupport (~> 3.1)
    - nanopb (~> 1.30905.0)
    - PromisesObjC (~> 1.2)
  - FirebaseInstallations (1.4.0):
    - FirebaseCore (~> 6.8)
    - GoogleUtilities/Environment (~> 6.6)
    - GoogleUtilities/UserDefaults (~> 6.6)
    - PromisesObjC (~> 1.2)
  - FirebaseInstanceID (4.4.0):
    - FirebaseCore (~> 6.8)
    - FirebaseInstallations (~> 1.0)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/UserDefaults (~> 6.5)
  - FirebaseMessaging (4.5.0):
    - FirebaseCore (~> 6.8)
    - FirebaseInstanceID (~> 4.3)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.5)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Reachability (~> 6.5)
    - GoogleUtilities/UserDefaults (~> 6.5)
    - Protobuf (>= 3.9.2, ~> 3.9)
  - FirebaseRemoteConfig (4.6.0):
    - FirebaseABTesting (~> 3.1)
    - FirebaseCore (~> 6.8)
    - FirebaseInstallations (~> 1.1)
    - GoogleUtilities/Environment (~> 6.2)
    - "GoogleUtilities/NSData+zlib (~> 6.2)"
  - FirebaseStorage (3.7.0):
    - FirebaseCore (~> 6.8)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseUI/Auth (8.4.2):
    - Firebase/Auth (~> 6.0)
    - GoogleUtilities/UserDefaults
  - FirebaseUI/Email (8.4.2):
    - FirebaseUI/Auth
  - GoogleAppMeasurement (6.6.2):
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 1.30905.0)
  - GoogleDataTransport (6.2.1)
  - GoogleDataTransportCCTSupport (3.2.0):
    - GoogleDataTransport (~> 6.1)
    - nanopb (~> 1.30905.0)
  - GoogleUtilities/AppDelegateSwizzler (6.6.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (6.6.0):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/Logger (6.6.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (6.6.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (6.6.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (6.6.0)"
  - GoogleUtilities/Reachability (6.6.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (6.6.0):
    - GoogleUtilities/Logger
  - GTMSessionFetcher/Core (1.4.0)
  - nanopb (1.30905.0):
    - nanopb/decode (= 1.30905.0)
    - nanopb/encode (= 1.30905.0)
  - nanopb/decode (1.30905.0)
  - nanopb/encode (1.30905.0)
  - PromisesObjC (1.2.10)
  - Protobuf (3.13.0)
```

So why I'm seeing root dependencies like`GoogleAppMeasurement` or `FirebaseABTesting` since I didn't specify them in Podfile?

**Comment by paulb777** [comment]
`GoogleAppMeasurement` is a dependency of `FirebaseAnalytics`. `FirebaseABTesting` is a dependency of `FirebaseRemoteConfig`.

**Comment by wilhuff** [comment]
Note that top-level entries in Podfile.lock don't necessarily correspond to root dependencies. What it shows you is a two-level listing capturing the pods included by the project and their dependencies. Many of these entries are not mentioned in your Podfile; they come in as dependencies of those entries.

None of the dependencies implied by adding a Firebase package to your Podfile are optional.

**Comment by borut-t** [comment]
I am aware of that but it still confuses me why `FirebaseABTesting` for an example is included as a dependecy of `FirebaseRemoteConfig`. It should be added as a standalone pod if needed, not as a dependency of another one.

AB testing is smth firebase offers, but we don't use it at all. So why bundling it with remote config?

**Comment by paulb777** [comment]
@borut-t The specific dependency of `FirebaseRemoteConfig` on `FirebaseABTesting` was done for expediency. It's been under consideration for separation, but hasn't been a priority since the `FirebaseABTesting` code is relatively small. Feel free to open another issue specifically for that one.

There is already an active project to remove the `FirebaseInstanceID` dependency from `FirebaseMessaging`, so that one is expected to go away in the next few months.

All of the other dependencies provide key functionality and are not likely to be removed.

**Comment by borut-t** [comment]
I'm just worried a bit how many other dependencies are included de-facto, but could be moved into standalone.

Thanks @paulb777 for detailed explanation.
