### ISSUE TITLE
Calling verifyPhoneNumber dismisses presented keyboard

### ISSUE THREAD

**Issue by Chesong-Lee-Hospii** [firebase/firebase-ios-sdk#6358]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.6 (11E708)
  * Firebase SDK version: 6.5.0
  * Firebase Component: Auth (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 6.5.0
  * Installation method: `CocoaPods`

### [REQUIRED] Step 2: Describe the problem
Calling `PhoneAuthProvider.provider().verifyPhoneNumber(...` when a keyboard is presented, dismisses the current keyboard, which also causes the next view controller to dismiss it's keyboard if you call `becomeFirstResponder` during `viewWillAppear`

#### Steps to reproduce:

What happened? How can we make the problem occur?
1) Have a phone number text field on a `ViewController`. Add an `inputAccessoryView` to the `textfield` (preferably a done button).
2) Call `PhoneAuthProvider.provider().verifyPhoneNumber` when done button is tapped.
3) You'll see that the keyboard becomes dismissed.
4) When you successfully authenticate the user, present a new `ViewController` with another `textfield` In the new `ViewController` on `viewWillAppear` call it's `textfield.becomeFirstResponder`. You'll see that the keyboard appears for a second or so before being dismissed.

**Comment by ryanwilson** [comment]
Hi @Chesong-Lee-Hospii - thanks for the report and sorry for the issues you're seeing!

Firebase has received quite a few updates since 6.5.0 - are you able to reproduce this issue on the latest Firebase version?

Thanks!

**Comment by Chesong-Lee-Hospii** [comment]
Hey @ryanwilson - updated to 6.31.0 - still seeing this issue.

**Comment by Chesong-Lee-Hospii** [comment]
Solved issue by playing `becomeFirstResponder` within the `viewDidAppear` code
