### ISSUE TITLE
Firebase ML: Support for Swift Package Manager

### ISSUE THREAD

**Issue by matthieuchappaz** [firebase/firebase-ios-sdk#6362]
### Step 1: Describe your environment

  * Xcode version: 12.0 beta 5
  * Firebase SDK version: Branch 6.31-spm-beta
  * Firebase Component: Firebase ML
  * Component version: 6.31
  * Installation method: Swift Package Manager

### Step 2: Describe the problem

As described by @paulb777 [here](https://github.com/firebase/firebase-ios-sdk/issues/3136#issuecomment-680060085), Firebase ML is not supported yet on SPM. It would be nice to have this

#### Steps to reproduce:

When you install Firebase with SPM, Firebase/ML is not available.

**Comment by joshuapoq** [comment]
Not quite the right place but is there an update on when Performance Monitoring (and the others) will be part of Swift Package Manager?

I'd be interested in knowing what issues there are - I assume that these frameworks rely on low level libraries or resources that are harder to package?

**Comment by paulb777** [comment]
@joshuapoq We don't have an update on timing.  We're planning to open source both ML and Performance and may wait until that happens to add SPM support to avoid the complexity and instability we're seeing with binary package support with Analytics. For Messaging, we're working to planning to remove the Protobuf dependency that relies on options unsupported by SPM.

Feel free to open separate issues for each of these and we may adjust priorities based on the thumbs-up indicators.

**Comment by ryanwilson** [comment]
The previous FirebaseML pods that this issue was referring to are now deprecated and will not be added to SwiftPM. The updated `FirebaseMLModelDownloader` is included, though: https://github.com/firebase/firebase-ios-sdk/blob/7048626173592a2a0ed963031add17c1c30d7772/Package.swift#L79

Thanks!
