### ISSUE TITLE
Wrong brief on field

### ISSUE THREAD

**Issue by long1eu** [firebase/firebase-ios-sdk#6371]
https://github.com/firebase/firebase-ios-sdk/blob/90a1aff41dbb45778e828b39cb51fe4fe7874631/FirebaseAuth/Sources/AuthProvider/GameCenter/FIRGameCenterAuthCredential.h#L53

I'm doing a port to Dart so I thought it would be nice to flag stuff that I found along the way. :D

**Comment by paulb777** [comment]
Thanks for the report! Fixing in #6372.
