### ISSUE TITLE
GoogleDataTransport: reduce public API to required minimum

### ISSUE THREAD

**Issue by maksymmalyhin** [firebase/firebase-ios-sdk#6383]
As originally to separate GoogleDataTransport SDKs where merged into one we can cleanup the public API surface to keep only API actually useful for clients and hide any implementation details such [GDTCORStorageProtocol](https://github.com/firebase/firebase-ios-sdk/blob/fa7b3f9e7e247edfdd79ef9054a5112285c88d28/GoogleDataTransport/GDTCORLibrary/Public/GoogleDataTransport/GDTCORStorageProtocol.h#L32) and most of the [GDTCORLibrary](https://github.com/firebase/firebase-ios-sdk/tree/master/GoogleDataTransport/GDTCORLibrary/Public/GoogleDataTransport) public API. This will simplify modifications of the SDK without major version bumps.

Also some private headers should be moved to internal if the headers are not used outside of GDT.

**Comment by ryanwilson** [comment]
Need to make sure copybara is finished. Internal header cleanup can be separated.

**Comment by maksymmalyhin** [comment]
Private headers cleanup deferred to #6696.
