### ISSUE TITLE
"upload-symbols" triggers security alert

### ISSUE THREAD

**Issue by mattia** [firebase/firebase-ios-sdk#6398]
* Xcode version: 11.6 (11E708)
  * Firebase SDK version: 6.31.0
  * Firebase Component: FirebaseCrashlytics (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 6.31.0
  * Installation method: `Carthage`

### [REQUIRED] Step 2: Describe the problem
Running the `upload-symbols` script trigger a Gatekeep alert and does not allow to continue.
Alert shows:
> “upload-symbols” can’t be opened because Apple cannot check it for malicious software.

This problem can be avoided by allowing the `upload-symbols` script in the security pane of System Preferences, but I don't think this is a good approach/solution.
I think that signing/notarizing the script should get rid of the problem.

#### Steps to reproduce:
Run
```
./MyProject/Firebase/upload-symbols -gsp ./MyProject/GoogleService-Info.plist -p ios dSYMs
```

**Comment by mattia** [comment]
Forgot to mention: the `upload-symbols` used is from the [master branch as of today](https://github.com/firebase/firebase-ios-sdk/blob/master/Crashlytics/upload-symbols)

**Comment by adamvduke** [comment]
Hi @mattia,

Can you provide the output of `codesign -dv --verbose=4 ./MyProject/Firebase/upload-symbols`?

**Comment by mattia** [comment]
```

**Comment by mattia** [comment]
Can I provide additional information to help the process?

Thanks! Have a nice day

**Comment by adamvduke** [comment]
Do you mind sharing your installation method, e.g. CocoaPods, Swift Package Manager, manual zip download, etc...?

**Comment by samedson** [comment]
Hey @mattia, based on that output, `upload-symbols` is codesigned (which is expected). I think ultimately we need to take the next step and Notarize the tool for macOS to accept it via Carthage / zip downloads. With Cocoapods it seems to be ok with just a signed binary.

I'll let you know when we pull the work to get it Notarized.

**Comment by mattia** [comment]
Thank you!

**Comment by elenadoty** [comment]
Just a quick update on this: we've pulled this work and should have an update on the expected timeline within the next few weeks.

**Comment by mattia** [comment]
> Just a quick update on this: we've pulled this work and should have an update on the expected timeline within the next few weeks.

Looking forward to the update!

Thanks! Have a nice day

**Comment by TofPlay** [comment]
> “upload-symbols” can’t be opened because Apple cannot check it for malicious software.

Same issue for me
I need to upload symbols from an xcarchive bundle (generated wit Xcode build archive)
Any update about this ticket?

**Comment by Kondamon** [comment]
> > “upload-symbols” can’t be opened because Apple cannot check it for malicious software.
> 
> Same issue for me
> I need to upload symbols from an xcarchive bundle (generated with Xcode build archive)
> Any update about this ticket?
Same issue for me! Any progress on this ticket?

**Comment by adamvduke** [comment]
I created https://github.com/firebase/firebase-ios-sdk/pull/7323 which updates the upload-symbols binary to hopefully avoid the security alert. The binary is signed with Google's developer certificate and has been notarized via Apple's notary service.

I will leave this ticket open until the PR is merged and folks have a chance to verify that this solves the issue.

**Comment by adamvduke** [comment]
Seems like this is resolved for the folks that were participating in the conversation.
