### ISSUE TITLE
Strange compilation errors when added to a project alongside Realm

### ISSUE THREAD

**Issue by kevboh** [firebase/firebase-ios-sdk#640]
This is a little squirrelly, but my situation is as follows: I wanted to add this SDK to an existing react native app, and that app has `realm` as a dependency. Adding this SDK seems to cause compilation issues inside Realm, I _think_ by clobbering certain system headers. Steps to reproduce are below, or you can clone https://github.com/kevboh/RealmFirebaseBugDemo.

### Environment

  * Xcode version: 9.2
  * Firebase SDK version: 4.8.0
  * Firebase Component: Core and Firestore
  * Component version: 4.0.13 and 0.9.4

### Problem

After adding both libraries, you get many compile errors like the following:

```
In file included from /Users/kevboh/RealmFirebaseBugDemo/node_modules/realm/react-native/ios/RealmReact/RealmReact.mm:25:
In file included from ../../src/object-store/src/shared_realm.hpp:22:
In file included from ../../src/object-store/src/execution_context_id.hpp:30:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/thread:96:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/chrono:303:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:60:9: error: no member named 'clock' in the global namespace; did you mean 'flock'?
using ::clock;
```

ctime here is...ctime, in llvm. I don't know a ton about this sort of stuff, but my gut feeling here is that Firebase or a dependency (grpc? it has a `time.h`) is clobbering a system header and getting Realm confused.

#### Steps to reproduce:

1. `react-native init MyProject`
2. `cd MyProject/`
3. `yarn add realm`
4. `react-native link realm`
5. `cd ios/`
6. `pod init` and add `pod 'Firebase/Core'` and `pod 'Firebase/Firestore'` to the Podfile
7. `react-native run-ios`

**Comment by wilhuff** [comment]
The gRPC-Core pod includes a time.h header as `include/grpc/support/time.h`. `::clock` is indeed defined by the system `<time.h>`. If you happened to include the grpc time.h then this wouldn't be defined and would cause the error you're seeing.

However, it seems as if grpc is already taking steps to avoid specifically this problem:

https://github.com/grpc/grpc/blob/2eb22fd67d73a210c1f41d79efcfe52285ccb2ec/gRPC-Core.podspec#L89

Can you confirm that USE_HEADERMAP is false for your project?

/cc @paulb777

**Comment by kevboh** [comment]
It's false for gprc-core, but not for the project or for RealmReact. Setting it to false in those two places doesn't seem to affect anything. This is a great lead, though—thank you!

**Comment by kevboh** [comment]
Your comment helped me find a workaround: https://github.com/realm/realm-js/issues/1607#issuecomment-356733283

realm-js is optimistically searching in the Pods/Public/** folder. Removing it as a search path avoids the errors. It doesn't necessarily seem like the _right_ fix, but it has everything compiling fine.

**Comment by paulb777** [comment]
Thanks for the report and investigation @kevboh 

From the discussion, it seems the root cause is react-native being overly expansive about adding to HEADER_SEARCH_PATHS. See https://github.com/realm/realm-js/issues/1607. 

I'm going to close because the fix looks outside the scope of Firebase and Firestore. Please reopen if it's found to be otherwise.

**Comment by CyrusZei** [comment]
Can somebody point me on where I can find this header search path and remove it?
I am opening my .xcworkspace and clicking on my project and then "build settings" and then where ?
I am a bit lost

**Comment by paulb777** [comment]
@CyrusZei See the links in the comments above. If you're still stuck, you might want to try stackoverflow.  I'm not sure many Realm users watch this repo's issues.
