### ISSUE TITLE
FIAM delegate calls messageDismissed instead of messageClicked if button action is to dismiss

### ISSUE THREAD

**Issue by willbattel** [firebase/firebase-ios-sdk#6405]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.6
  * Firebase SDK version: 6.30.0
  * Firebase Component: In-App Messaging
  * Component version: 0.23.0
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

When using a Card message with two buttons, both of which set in the Firebase Console to use dismiss as the action, FIAM never calls the `messageClicked` delegate function. Instead, FIAM calls the `messageDismissed` function when the button is clicked. I was expecting the former because, even though the button behavior was to dismiss, it was still a message click. I need to use the `messageClicked(_:with:)` function so that I can check if the primary action button was the one that was pressed.

For context see my related issue #6380.

#### Steps to reproduce:

Simple to reproduce, see screenshot and code below. Click the "View" (primary) button to trigger.

![fiam](https://user-images.githubusercontent.com/13490339/91813078-bbe4b980-ebf7-11ea-8fcd-77b3d7ef36a3.PNG)

#### Relevant Code:

```
class MyViewController: UIViewController {
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        InAppMessaging.inAppMessaging().delegate = self
        print("READY")
    }
}

extension MyViewController: InAppMessagingDisplayDelegate {
    func impressionDetected(for inAppMessage: InAppMessagingDisplayMessage) {
        print("IMPRESSION")
    }
    func messageClicked(_ inAppMessage: InAppMessagingDisplayMessage, with action: InAppMessagingAction) {
        // Workaround for https://github.com/firebase/firebase-ios-sdk/issues/6380
        if action.actionText == "View" {
            print("CLICK PRIMARY")
        }
        else {
            print("CLICK OTHER")
        }
    }
    func messageDismissed(_ inAppMessage: InAppMessagingDisplayMessage, dismissType: FIRInAppMessagingDismissType) {
        print("DISMISSED")
    }
}
```

With the above code, I expected the console to display:
```
READY
IMPRESSION
CLICK PRIMARY
```
but action behavior is:
```
READY
IMPRESSION
DISMISSED
```

**Comment by christibbs** [comment]
Hey Will, we're aware of this and handling it across both our SDKs-- another developer pointed it out on the [Android SDK](https://github.com/firebase/firebase-android-sdk/issues/1603).

**Comment by christibbs** [comment]
Closing this in favor of https://github.com/firebase/firebase-android-sdk/issues/1603. Please track progress via that issue.
