### ISSUE TITLE
Error archiving project with SPM: Symbols tool failed

### ISSUE THREAD

**Issue by lisindima** [firebase/firebase-ios-sdk#6407]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: `12.0 Beta 6`
  * Firebase SDK version: `6.31-spm-beta`
  * Firebase Component: `Crashlytics, Analytics`
  * Component version: `6.31.0`
  * Installation method: `Swift Package Manager`

### [REQUIRED] Step 2: Describe the problem

I installed Firebase via SPM using the [instruction](https://github.com/firebase/firebase-ios-sdk/blob/master/SwiftPackageManager.md), there are no compile-time errors, but I cannot load the application into Testflight for testing. The problem is only when I add Firebase via SPM, if I use CocoaPods then no problems arise and the application loads successfully.
The problem also persists with the branch: `6.32-spm-beta`

<img width="749" alt="Снимок экрана 2020-09-07 в 14 37 27" src="https://user-images.githubusercontent.com/43087859/92361140-245ff900-f118-11ea-8758-a5bb188c0cbf.png">

**Comment by deanPGM** [comment]
It doesn't fix the issue, but you can work around this step by unchecking the `Upload your app's symbols to receive symbolicated reports from Apple` option on the page prior.

**Comment by ryanwilson** [comment]
Can you please hit "Show Logs" and share whatever you can there? Without logs or a reproduction I'm not sure what else we can do to help debug. Thanks!

**Comment by paulb777** [comment]
Updating might fix if this has the same root cause as #6360. See https://github.com/firebase/firebase-ios-sdk/issues/6360#issuecomment-691271702
