### ISSUE TITLE
Dynamic link created by REST API always opens the app, not browser

### ISSUE THREAD

**Issue by coolcool1994** [firebase/firebase-ios-sdk#6410]
I created dynamic link successfully using Cloud Functions in index.ts environment, but it doesn't behaves correctly only in iOS platform.

Using below code, I get a dynamic link like "https://example.page.link/asdbaf. When I click on this, I want it to open the browser as the url or long link (https:/example.com) is a url in the website (it would make no sense to open the web url in the app). In Android and in browser, this created dynamic link all opens the browser correctly, but iOS always opens the app. This is clearly a bug in iOS platform.

You can see in by doing https://example.page.link/asdbaf?d=1, I can see the how dynamic link should behave. iOS is said to open website, but it doesn't. Only iOS platform has this bug. Android and web browser work correctly.

There is no good workaround until the fix from you guys - I currently implemented so it opens the app in iOS and then open a browser, BUMMER! Creating the dynamic link using longDynamicLink field and using different domainUriPrefix both result in the same bug only in iOS. I created the same issue 6 months ago (https://github.com/firebase/firebase-ios-sdk/issues/5376), and this bug still exists. This is an important feature in my app, and I need this fixed. I am ready to assist you in case you guys need my help identifying the issue, but I am not the only one who is experiencing this bug according to the post made 6 months ago. This bug may have resulted in from: "Note: the app preview page is only shown on iOS currently, but may eventually be shown on Android." This may be app preview bug. I do not show app preview page. 

<img width="883" alt="Screen Shot 2020-09-07 at 5 22 30 PM" src="https://user-images.githubusercontent.com/23645054/92421819-503aa900-f12f-11ea-9801-89b8e5537a6f.png">

```
const response = await request({
method: 'POST',
url: 'https://firebasedynamiclinks.googleapis.com/v1/shortLinks?key=API_KEY',
body: ({
dynamicLinkInfo: {
domainUriPrefix: "https://example.page.link",
link: "https:/example.com,
navigationInfo: {
enableForcedRedirect: false,
},
},
suffix: {
option: "UNGUESSABLE"
}
}),
json: true
}).catch (async (error) => {
console.log("sending text message failed " + error);
})
```

**Comment by paulb777** [comment]
Closing for staleness. Please comment or open a new issue to reopen.
