### ISSUE TITLE
Missing SCNReachability in Test Bundle

### ISSUE THREAD

**Issue by ryantstone** [firebase/firebase-ios-sdk#6413]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 12.0 beta 5 (12A8189h)
  * Firebase SDK version: 6.32-SPM-beta
  * Firebase Component: FireStore (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 6.32
  * Installation method: SPM

### [REQUIRED] Step 2: Describe the problem
When running the test bundle I get:
```
Undefined symbols for architecture x86_64:
  "_SCNetworkReachabilityCreateWithAddress", referenced from:
      firebase::firestore::remote::(anonymous namespace)::CreateReachability() in SubFramework(FirebaseFirestore.o)
  "_SCNetworkReachabilitySetCallback", referenced from:
      firebase::firestore::remote::ConnectivityMonitorApple::ConnectivityMonitorApple(std::__1::shared_ptr<firebase::firestore::util::AsyncQueue> const&) in SubFramework(FirebaseFirestore.o)
  "_SCNetworkReachabilityGetFlags", referenced from:
      firebase::firestore::remote::ConnectivityMonitorApple::ConnectivityMonitorApple(std::__1::shared_ptr<firebase::firestore::util::AsyncQueue> const&) in SubFramework(FirebaseFirestore.o)
      firebase::firestore::remote::ConnectivityMonitorApple::OnEnteredForeground() in SubFramework(FirebaseFirestore.o)
  "_SCNetworkReachabilitySetDispatchQueue", referenced from:
      firebase::firestore::remote::ConnectivityMonitorApple::ConnectivityMonitorApple(std::__1::shared_ptr<firebase::firestore::util::AsyncQueue> const&) in SubFramework(FirebaseFirestore.o)
      firebase::firestore::remote::ConnectivityMonitorApple::~ConnectivityMonitorApple() in SubFramework(FirebaseFirestore.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
The project runs fine, but the test bundle will fail if a specific combination of files is used.

#### Steps to reproduce:
I'm not sure of the steps, but I have an example project. Where it occurs.
https://github.com/ryantstone/Firebase-Bug-Example

If a single test is commented out (`ConvertTests.test_timeToPickerValue_convertsHoursAndMinutes_toNativePickerData`) the test suite will build and run, but if that test is in it will fail.

Steps to reproduce are in the Readme in the repo.

**Comment by morganchen12** [comment]
The test passes if commented out because the linker strips unused symbols. Can you try adding SystemConfiguration.framework to the Link Binary with Libraries part of your test target's Build Phases?

**Comment by ryantstone** [comment]
It does build when adding it. Thank you.

**Comment by morganchen12** [comment]
Closing this issue since it seems to be resolved, let me know if you need any more help.

**Comment by paulb777** [comment]
Going to reopen since this may have a similar resolution as #6408 with #6419.
