### ISSUE TITLE
I received many cpu resource fatal feedback

### ISSUE THREAD

**Issue by YasinTian** [firebase/firebase-ios-sdk#6424]
Cpu usage always high when 'Library/Caches/google-sdks-events/GDTCORFlatFileStorage' have too many files. 

Date/Time:        2020-09-06 01:37:14 +0800
End time:         2020-09-06 01:37:23 +0800
OS Version:       iPhone OS 13.2.3 (Build 17B111)
Architecture:     arm64
Report Version:   29
Incident Identifier: 1E8019B1-ED6C-4D72-84D4-7E34CE05CCE7

Data Source:      Microstackshots
Shared Cache:     0x302cc000 5707535A-A0F2-3A25-AEB1-12D791886979

Command:          Vostic
Path:             /private/var/containers/Bundle/Application/FC23A23E-A32F-43CA-86B1-0078F3CA4E3E/Vostic.app/Vostic
Identifier:       com.vostic.ios
Version:          1.27.2 (1272001)
Beta Identifier:  E84B6EE5-B301-4229-9B6E-4BFDF54A14AF
PID:              7583

Event:            cpu usage
Action taken:     Process killed
CPU:              9 seconds cpu time over 9 seconds (99% cpu average), exceeding limit of 60% cpu over 15 seconds
CPU limit:        9s
Limit duration:   15s
CPU used:         9s
CPU duration:     9s
Duration:         9.10s
Duration Sampled: 7.02s
Steps:            7

Hardware model:   iPhone10,5
Active cpus:      6

Heaviest stack for the target process:
  6  ??? (libsystem_pthread.dylib + 49032) [0x1b047af88]
  6  ??? (libdispatch.dylib + 275516) [0x1b041243c]
  6  ??? (libdispatch.dylib + 237864) [0x1b0409128]
  6  ??? (libdispatch.dylib + 235280) [0x1b0408710]
  6  ??? (libdispatch.dylib + 377220) [0x1b042b184]
  6  ??? (libdispatch.dylib + 374288) [0x1b042a610]
  5  ??? (Vostic + 25272512) [0x1045860c0]
  5  ??? (Foundation + 321980) [0x1b0a5c9bc]
  5  ??? (libsystem_kernel.dylib + 158516) [0x1b0557b34]

Powerstats for:   Vostic [7583]
Bundle ID:        com.vostic.ios
Adam ID:          1475080873
Is first party:   No
App version:      1.27.2
Build version:    1272001
Is Beta:          No
Share with Devs:  Yes
UUID:             94915467-A19F-3815-A8C8-2D2EDC485A7C
Path:             /private/var/containers/Bundle/Application/FC23A23E-A32F-43CA-86B1-0078F3CA4E3E/Vostic.app/Vostic
Architecture:     arm64
Footprint:        271.16 MB -> 645.20 MB (+374.05 MB)
Start time:       2020-09-06 01:37:15 +0800
End time:         2020-09-06 01:37:22 +0800
Num samples:      7 (100%)
CPU Time:         7.209s
Primary state:    4 samples Non-Frontmost App, Non-Suppressed, Kernel mode, Effective Thread QoS Default, Requested Thread QoS User Initiated, Override Thread QoS Unspecified
User Activity:    0 samples Idle, 0 samples Active, 7 samples Unknown
Power Source:     0 samples on Battery, 0 samples on AC, 7 samples Unknown
  6  ??? (libsystem_pthread.dylib + 49032) [0x1b047af88]
    6  ??? (libdispatch.dylib + 275516) [0x1b041243c]
      6  ??? (libdispatch.dylib + 237864) [0x1b0409128]
        6  ??? (libdispatch.dylib + 235280) [0x1b0408710]
          6  ??? (libdispatch.dylib + 377220) [0x1b042b184]
            6  ??? (libdispatch.dylib + 374288) [0x1b042a610]
              5  __44-[GDTCORFlatFileStorage checkForExpirations]_block_invoke (GDTCORFlatFileStorage.m:374 in Vostic + 25272512) [0x1045860c0]
                5  ??? (Foundation + 321980) [0x1b0a5c9bc]
                  5  ??? (libsystem_kernel.dylib + 158516) [0x1b0557b34]
                    1  <User mode>
              1  __44-[GDTCORFlatFileStorage checkForExpirations]_block_invoke (GDTCORFlatFileStorage.m:376 in Vostic + 25272252) [0x104585fbc]
                1  -[GDTCORFlatFileStorage eventComponentsFromFilename:] (GDTCORFlatFileStorage.m:716 in Vostic + 25281740) [0x1045884cc]
                  1  -[NSMutableArray hookSubarrayWithRange:] (NSObjectSafe.m:782) (NSObjectSafe.m:782 in Vostic + 10631428) [0x10378f904]
                    1  ??? (CoreFoundation + 129280) [0x1b0651900]
                      1  ??? (libobjc.A.dylib + 135816) [0x1b04a1288]
                        1  <User mode>
  1  ??? (libsystem_pthread.dylib + 45520) [0x1b047a1d0]
    1  ??? (libAudioToolboxUtility.dylib + 62712) [0x1bb8c84f8]
      1  ??? (libEmbeddedSystemAUs.dylib + 575404) [0x1ce1bc7ac]
        1  ??? (libAudioToolboxUtility.dylib + 71336) [0x1bb8ca6a8]
          1  ??? (libAudioToolboxUtility.dylib + 70296) [0x1bb8ca298]
            1  ??? (libEmbeddedSystemAUs.dylib + 886760) [0x1ce2087e8]
              1  ??? (libEmbeddedSystemAUs.dylib + 607412) [0x1ce1c44b4]
                1  ??? (libEmbeddedSystemAUs.dylib + 666716) [0x1ce1d2c5c]
                  1  ??? (libEmbeddedSystemAUs.dylib + 562932) [0x1ce1b96f4]
                    1  ??? (libEmbeddedSystemAUs.dylib + 53476) [0x1ce13d0e4]
                      1  ??? (AudioToolboxCore + 843044) [0x1bd6e8d24]
                        1  ??? (AudioToolboxCore + 154020) [0x1bd6409a4]
                          1  ??? (AudioToolboxCore + 269948) [0x1bd65ce7c]
                            1  ??? (AudioToolboxCore + 154020) [0x1bd6409a4]
                              1  ??? (AudioToolboxCore + 1742984) [0x1bd7c4888]
                                1  ??? (AudioToolboxCore + 154672) [0x1bd640c30]
                                  1  ??? (AudioToolboxCore + 276988) [0x1bd65e9fc]
                                    1  ??? (AudioToolboxCore + 270476) [0x1bd65d08c]
                                      1  ??? (libEmbeddedSystemAUs.dylib + 59056) [0x1ce13e6b0]
                                        1  ??? (libEmbeddedSystemAUs.dylib + 148964) [0x1ce1545e4]
                                          1  output_renderer (coreaudio_dev.c:1108 in Vostic + 39235064) [0x1052d6df8]
                                            1  output_renderer_new (coreaudio_dev.c:950 in Vostic + 39226316) [0x1052d4bcc]
                                              1  play_cb (sound_port.c:224 in Vostic + 39211256) [0x1052d10f8]
                                                1  pcc_port_get_frame + 807 (Vostic + 28954492) [0x104908f7c]
                                                  1  non-virtual thunk to PccInterface::OnPlayData + 83 (Vostic + 29036736) [0x10491d0c0]
                                                    1  PccInterface::OnPlayData + 339 (Vostic + 29036272) [0x10491cef0]
                                                      1  resample_common_int16 + 272 (Vostic + 32853668) [0x104cc0ea4]
                                                        1  <User mode, Effective Thread QoS Unspecified, Requested Thread QoS Unspecified>

  Binary Images:
           0x102d6c000 -                ???  com.vostic.ios 1.27.2 (1272001) <94915467-A19F-3815-A8C8-2D2EDC485A7C>  /private/var/containers/Bundle/Application/FC23A23E-A32F-43CA-86B1-0078F3CA4E3E/Vostic.app/Vostic
           0x1b03cf000 -        0x1b0443fff  libdispatch.dylib               <B7EED4C7-560D-3DA6-9B50-ED52A150AAC6>  /usr/lib/system/libdispatch.dylib
           0x1b046f000 -        0x1b047ffff  libsystem_pthread.dylib         <F8B082D8-24D9-3B1E-B80B-645FC8A88E14>  /usr/lib/system/libsystem_pthread.dylib
           0x1b0480000 -        0x1b04b0fff  libobjc.A.dylib                 <53ED9775-D85D-3A6F-B65B-C3101EC58643>  /usr/lib/libobjc.A.dylib
           0x1b0531000 -        0x1b055efff  libsystem_kernel.dylib          <AE4C3D7A-7D08-33E7-BCC6-11AC821B4E48>  /usr/lib/system/libsystem_kernel.dylib
           0x1b0632000 -        0x1b09a6fff  CoreFoundation                  <FF63481D-FB6A-353B-B2C1-AC4EAECF594D>  /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
           0x1b0a0e000 -        0x1b0cc7fff  Foundation                      <3C682044-3249-3938-8111-F2F12D066D2B>  /System/Library/Frameworks/Foundation.framework/Foundation
           0x1bb8b9000 -        0x1bb8eefff  libAudioToolboxUtility.dylib    <391F992B-3B09-3701-98CC-3E1DFCFC5346>  /usr/lib/libAudioToolboxUtility.dylib
           0x1bd61b000 -        0x1bd84ffff  AudioToolboxCore                <0C5CEE7C-1718-34CC-BE35-F22CD8DE7566>  /System/Library/PrivateFrameworks/AudioToolboxCore.framework/AudioToolboxCore
           0x1ce130000 -        0x1ce238fff  libEmbeddedSystemAUs.dylib      <E1A43641-A2E3-3BF1-9596-8E88634083C8>  /System/Library/Frameworks/AudioToolbox.framework/libEmbeddedSystemAUs.dylib

**Comment by YasinTian** [comment]
- Firebase/Analytics (6.31.0):
    - Firebase/Core
  - Firebase/Core (6.31.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.8.0)
  - Firebase/CoreOnly (6.31.0):
    - FirebaseCore (= 6.10.1)
  - Firebase/Crashlytics (6.31.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 4.5.0)
  - Firebase/Performance (6.31.0):
    - Firebase/CoreOnly
    - FirebasePerformance (~> 3.3.0)
  - FirebaseABTesting (4.2.0):
    - FirebaseCore (~> 6.10)
  - FirebaseAnalytics (6.8.0):
    - FirebaseCore (~> 6.10)
    - FirebaseInstallations (~> 1.6)
    - GoogleAppMeasurement (= 6.8.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.7)
    - GoogleUtilities/MethodSwizzler (~> 6.7)
    - GoogleUtilities/Network (~> 6.7)
    - "GoogleUtilities/NSData+zlib (~> 6.7)"
    - nanopb (~> 1.30906.0)
  - FirebaseCore (6.10.1):
    - FirebaseCoreDiagnostics (~> 1.6)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Logger (~> 6.7)
  - FirebaseCoreDiagnostics (1.6.0):
    - GoogleDataTransport (~> 7.2)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Logger (~> 6.7)
    - nanopb (~> 1.30906.0)
  - FirebaseCrashlytics (4.5.0):
    - FirebaseCore (~> 6.10)
    - FirebaseInstallations (~> 1.6)
    - GoogleDataTransport (~> 7.2)
    - nanopb (~> 1.30906.0)
    - PromisesObjC (~> 1.2)
  - FirebaseInstallations (1.7.0):
    - FirebaseCore (~> 6.10)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/UserDefaults (~> 6.7)
    - PromisesObjC (~> 1.2)
  - FirebasePerformance (3.3.0):
    - FirebaseCore (~> 6.9)
    - FirebaseInstallations (~> 1.5)
    - FirebaseRemoteConfig (~> 4.7)
    - GoogleDataTransport (~> 7.0)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/ISASwizzler (~> 6.2)
    - GoogleUtilities/MethodSwizzler (~> 6.2)
    - GTMSessionFetcher/Core (~> 1.1)
    - Protobuf (~> 3.12)
  - FirebaseRemoteConfig (4.9.0):
    - FirebaseABTesting (~> 4.2)
    - FirebaseCore (~> 6.10)
    - FirebaseInstallations (~> 1.6)
    - GoogleUtilities/Environment (~> 6.7)
    - "GoogleUtilities/NSData+zlib (~> 6.7)"

**Comment by YasinTian** [comment]
I write continuously 40M event data to Library/Caches/google-sdks-events/GDTCORFlatFileStorage/gdt_event_data, cpu will keep high usage when background switch foreground.

Test code

```
dispatch_async(dispatch_queue_create(0, 0), ^{
        while (1) {
            dispatch_sync(dispatch_get_main_queue(), ^{
                tabbar.selectedIndex = arc4random()%4;
            });
            usleep(100000);
        }
});
```

**Comment by maksymmalyhin** [comment]
@YasinTian Sorry you have the issue, thank you for the report. 

The method [checkForExpirations](https://github.com/firebase/firebase-ios-sdk/blob/802cb6a71678084bdff6d7b381cb474eae6b27ef/GoogleDataTransport/GDTCORLibrary/GDTCORFlatFileStorage.m#L343) currently may cause performance issue in the case of a big amount of events stored. I would like to ask you about your use case to understand why you have 40M event data. Do you use Firebase Performance Traces extensively?

**Comment by maksymmalyhin** [comment]
Note: this potentially will be partially mitigated by #6365.

**Comment by YasinTian** [comment]
40M is my test data, maybe my app always online at long time. 
I only import Firebase Performance, trace are not used. I will try to remove the Firebase Performance.

**Comment by paulb777** [comment]
@maksymmalyhin Is this still an issue with the recent GDT changes?

**Comment by maksymmalyhin** [comment]
@YasinTian Thank you for your patience and sorry for the delayed response. 

The PR #7014 Significantly reduces CPU and memory utilization for the problematic `-[GDTCORFlatFileStorage checkForExpirations]` method. The changes are scheduled for the next release (Firebase 7.3.0) but you may do a preliminary testing using GoogleDataTransport version from master. 

I'm closing the issue so far, but feel free comment or reopen if the issue still occurs or you have additional details to share.
