### ISSUE TITLE
FirebaseAnalytics symbols not found when installed via SPM

### ISSUE THREAD

**Issue by zeusent** [firebase/firebase-ios-sdk#6425]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: `12.0 beta 6 (12A8189n)`
  * Firebase SDK version: `6.32-spm-beta`
  * Firebase Component: `Analytics`
  * Component version: `6.32.0`
  * Installation method: `Swift Package Manager`

#### Steps to reproduce:

- I've installed Firebase via SPM using the instructions found at [this](https://github.com/firebase/firebase-ios-sdk/blob/master/SwiftPackageManager.md) page.
- I've also added the `-ObjC` flag as mentioned because I am using FirebaseAnalytics.

When compiling my project I get a bunch of errors like the ones bellow:

```
Undefined symbols for architecture arm64:
  "_kFIRParameterShipping", referenced from:
      {edited}
  "_kFIREventAddPaymentInfo", referenced from:
      {edited}
  "_kFIRParameterCheckoutOption", referenced from:
      {edited}
  "_kFIREventCheckoutProgress", referenced from:
      {edited}
  ...
ld: symbol(s) not found for architecture arm64
```

I get the same errors when trying to run on the simulator but the architecture is `x86_64` instead (obviously).

**Comment by ryanwilson** [comment]
Hi @zeusent - sorry for the troubles you're seeing.

Based on your reproduction steps, I'm unable to reproduce this. I created a new project and followed the instructions linked, added the `-ObjC` flag, using `import Firebase` or `import FirebaseAnalytics` and then calling `Analytics.logEvent("Test", [:])` succeeds in a simulator build as well as building for device (I tested via Archiving). 

A few other questions to try to make progress:
- Was it a blank project that you started with or an existing project?
- If it was an existing project, did you have Firebase integrated already? How did you remove it?

**Comment by zeusent** [comment]
Hi @ryanwilson! Thanks for your fast reply.

The project was an existing project and Firebase was added via CocoaPods. I've removed the lines in my Podfile and executed `pod update` to remove it.

I see in your example that you use a hardcoded string value for the event name and no parameters. Can you use one of the pre-defined events and parameters that Firebase provides? Something likes this:

```Analytics.logEvent(AnalyticsEventEcommercePurchase, parameters: [AnalyticsParameterShipping: 10.0])```

It seems that those events and parameters definitions are the issue while compiling...

**Comment by paulb777** [comment]
Hi @zeusent You might need to run `pod deintegrate` instead of `pod update` to fully eliminate the CocoaPods artifacts from the Xcode project.

**Comment by zeusent** [comment]
When @ryanwilson asked me how I removed it I went back and did just that. Ran `pod deintegrate`, deleted the workspace project and the `Podfile.lock` file and then ran `pod install` to  generate new ones. I still see the same errors

**Comment by ryanwilson** [comment]
Hmm, still no luck on my end when updating to the log event that you copied above. Still compiles okay for me. I suspect it's something to do with the previous setup. I'd be curious if you were to try in a blank project if you get the same issue - if you do, it's something with your machine, if you don't, it's something with the project.

**Comment by zeusent** [comment]
I've managed to do it... I've started from scratch and it worked with an empty project. I just added a call in my AppDelegate.

I then decided to recreate the old project. I did that and now it stopped working again. After a bit of fiddling with it I've made it.

Weirdest thing: I had to add `import UIKit` in the file I was using these... Maybe I'm missing something but I have no idea why that is mandatory...

**Comment by ryanwilson** [comment]
Very strange - glad it's tracked down. I wonder if it was some sort of false flag for some other issue in the file, or something else. The values are included in the public header file there (there's no `.m` file) so not sure what happened.

Sounds like things are resolved, but please do re-open if you run into issues again and thanks for checking out SwiftPM support!

**Comment by zeusent** [comment]
After a good night sleep things stopped working again out of the blue, without me changing anything :( I'll get back to investigating how I can fix this and why is this happening :(

**Comment by zeusent** [comment]
I think I found the issue in the end. I have no idea why running on the simulator sometimes works and sometimes doesn't but archiving didn't work for me at all...

Looking at the `Package.swift` file I see that the `FirebaseAnalyticsWrapper` target is defined as such:

```.target(
  name: "FirebaseAnalyticsWrapper",
  dependencies: [
    "FirebaseAnalytics",
    "FIRAnalyticsConnector",
    "GoogleAppMeasurement",
    "FirebaseCore",
    "FirebaseInstallations",
    "GoogleUtilities_AppDelegateSwizzler",
    "GoogleUtilities_MethodSwizzler",
    "GoogleUtilities_NSData",
    "GoogleUtilities_Network",
    .product(name: "nanopb", package: "nanopb"),
  ],
  path: "FirebaseAnalyticsWrapper",
  publicHeadersPath: "Public",
  linkerSettings: [
    .linkedLibrary("sqlite3"),
    .linkedLibrary("c++"),
    .linkedLibrary("z"),
    .linkedFramework("StoreKit"),
  ]
)
```

But looking in the folder structure that was downloaded I see that the header files are actually found at  `FirebaseAnalyticsWrapper/Public/FirebaseAnalytics`.

I've went ahead and manually moved them one level higher into the `Public` folder as specified in the `Package.swift` file and now I can archive my project.

Any idea if what I did is what's actually supposed to be done?

**Comment by ryanwilson** [comment]
Thanks @zeusent for the extra info! That's very interesting... re: why they are in a `Public/FirebaseAnalytics` directory as opposed to just the `Public` directory, the rest of Firebase [is structured this way](https://github.com/firebase/firebase-ios-sdk/blob/master/HeadersImports.md) due to being compatible with both CocoaPods and SwiftPM, otherwise we'd have to have a bunch of `#if` checks at the top of every header that wants to import something from Firebase. I also noticed an issue with our docs and opened #6454 to fix it.

I wonder though since this `FirebaseAnalyticsWrapper` directory is exclusively for Swift Package Manager and a binary, we may be able to fix the directory structure and see if that solves the issue. @paulb777 is the person who set all this up originally so I'd like to get his thoughts before making the change myself but I think that sounds reasonable to me if that solves the issues we're seeing!

I created a branch that updates the directory location if you want to test it out: `rw-spm-analytics-headers`. Let me know if that does solve the issue having it officially packaged like that.

**Comment by sjmueller** [comment]
I am running into this exact problem, I will try @zeusent hack to get around it for now..

**Comment by zeusent** [comment]
> I created a branch that updates the directory location if you want to test it out: `rw-spm-analytics-headers`. Let me know if that does solve the issue having it officially packaged like that.

Hey @ryanwilson ! Thanks for the test branch. I can confirm that with it I don't have the issue happening anymore no matter what my build type is: for simulator, for device, when archiving.

**Comment by sjmueller** [comment]
I used the test branch on Xcode 12 GM and while it was successful at building without errors, when copying to device there''s an error:

```
 Code: -402620388 No code signature found
```
More info here:
https://forums.swift.org/t/swiftpm-binarytarget-dependency-and-code-signing/38953

**Comment by paulb777** [comment]
The code signature issue is tracked at #6472 

I'll reopen to track the missing symbol issue. Can anyone confirm if it is still occurring with the Xcode 12 GM or later?

It would be great to get a reproducible example. It's a mystery to me about why moving the header files should impact linking versus compiling.  And I'd like to get a better understanding before applying a fix.

**Comment by zeusent** [comment]
Hey @paulb777. If I use the "normal" `6.32-spm-beta` branch I still see the same issue even with Xcode 12 GM, yes. Using the test branch that @ryanwilson made works fine (until I try uploading the archive that is - I get the Mach-O error described at #6472).

Unfortunately I haven't been able to create an empty project that does this. But I see it happening in 2 different projects that I've moved from CocoaPods to SPM. I even tried recreating one of my projects from scratch. It all worked out well until I've actually added all my old source files. The error showed up at that moment.

**Comment by paulb777** [comment]
@zeusent What does the `import` statement look like for Firebase in the file that is making the Analytics API call?

**Comment by paulb777** [comment]
Started discussion at https://forums.swift.org/t/binary-packages-and-non-deterministic-missing-symbol-errors/40410

**Comment by paulb777** [comment]
@zeusent I suspect the issue might be related to a redundant copy of the Analytics headers. It looks like the version embedded in the framework is sufficient. Would you try the branch pb-fix6425 with your testcase?  More detail in #6425.

**Comment by paulb777** [comment]
Based on https://github.com/firebase/firebase-ios-sdk/issues/6518#issuecomment-696800981, there might be something in the Xcode project causing this problem, perhaps something left over from Carthage?

**Comment by zeusent** [comment]
Hey @paulb777. Sorry for my late reply I was somewhat away. My two projects that experience this thing never used Cartage but CocoaPods. And as I've mentioned before I even recreated one of the projects from scratch only to hit the same problem once I've added all my implementation files into the project.

What is even weirder is that whenever that happen if I simply remove the FirebaseAnalytics library from the "Link with libraries" phase and re-add it manually, the project compiles until next time the packages are being resolved. This only worked for building for the simulator though and archiving never worked.

I now see that the `rw-spm-analytics-headers` branch is gone. I'll give this another shot with the latest `6.33-spm-beta` branch... I'll keep you posted in case I can find a way to replicate this in a new project that I can share

**Comment by zeusent** [comment]
I can confirm that I'm not seeing this happening anymore on branch `6.33-spm-beta`

**Comment by nikans** [comment]
`6.34-smp-beta`, clean integration, same issue. `Undefined symbols for architecture x86_64: "_OBJC_CLASS_$_FIRAnalytics"`

Though in my config, the static libs are linked to a dynamic target, which is embedded in other targets.
