### ISSUE TITLE
Unable to attach User Feedback to a crash report

### ISSUE THREAD

**Issue by fosterbrereton** [firebase/firebase-ios-sdk#6431]
### Step 1: Describe your environment

  * Xcode version: 11.6
  * Firebase SDK version: 6.31.0
  * Firebase Component: Crashlytics
  * Component version: 4.5.0
  * Installation method: zip file

### Step 2: Describe the problem

When a crash happens, we ask the user for feedback and/or steps that prove helpful in reproducing the crash. When a crash is detected, we present the user with a crash reporting dialog that solicits this feedback, as well as requesting consent from the user to submit the report. Once the user consents, we send the report and user feedback to Crashlytics. However, with the update to the most recent SDK, we're finding the user feedback doesn't get sent up until the _next_ crash report is sent by the same system. Hence, we always have an "off by one" error in our crash report user feedback.

#### Steps to reproduce:

1) Make sure `[FIRCrashlytics.crashlytics setCrashlyticsCollectionEnabled:NO];` is set, and/or the `FirebaseCrashlyticsCollectionEnabled` plist setting is set to `NO`.
2) Use `[FIRCrashlytics.crashlytics didCrashDuringPreviousExecution]` to detect if a crash happened.
3) Present the crash feedback dialog to the user.
4) Append data to the pending crash report via `[FIRCrashlytics.crashlytics setCustomValue:forKey:]`
5) Call `checkForUnsentReportsWithCompletion` to prompt sending the reports to Crashlytics
6) Within the `checkForUnsentReportsWithCompletion` callback, call `sendUnsentReports`.

Result: the user feedback from step 3 doesn't show up in the current crash report being sent; rather, it's sent up in the ensuing crash report (if there is one.)

**Comment by fosterbrereton** [comment]
I have updated to the Firebase 6.33.0 release, and am still seeing the same issues. I'm also looking at [the quickstart example](https://github.com/firebase/quickstart-ios/blob/master/crashlytics/CrashlyticsExample/ViewController.m) to try and glean help from there. Therein, note the `setValue:forKey` calls in that example are made in the _same_ session as the crash. In my case, the crash feedback is collected in the _ensuing_ session. So the example there isn't much help, either. Is there an example somewhere of a) asking for user permission to collect crash reports, and b) attaching information to these reports in ensuing sessions, prior to sending the report?

**Comment by fosterbrereton** [comment]
We have created a minimal test case that reproduces this issue here: https://github.com/lsavino/CrashlyticsUserFeedbackBug

**Comment by morganchen12** [comment]
Thanks for the clear repo @fosterbrereton. Our team is a little busy preparing changes for the Firebase 7 major release, so it may take us some time to properly respond to this issue, but we'll take a look at it in more detail soon.

6.13.0 goes beyond the open-source history of this library, so I'm unfamiliar with the changes made during that time period (@samedson can maybe provide some more context here), but there have been no changes to this part of the code from 6.14 until now, which suggests something more complex is going on.

**Comment by samedson** [comment]
Hey @fosterbrereton, we just submitted https://github.com/firebase/firebase-ios-sdk/pull/7503 that adds a new API to update crash reports from the previous run of the app. This should go out in the next Firebase release (est. March 9).

You can call [checkAndUpdateUnsentReportsWithCompletion](https://github.com/firebase/firebase-ios-sdk/blob/master/Crashlytics/Crashlytics/Public/FirebaseCrashlytics/FIRCrashlytics.h#L207) to get a [FIRCrashlyticsReport](https://github.com/firebase/firebase-ios-sdk/blob/master/Crashlytics/Crashlytics/Public/FirebaseCrashlytics/FIRCrashlyticsReport.h)
 object that you can use to modify the report from the last run of the app.


Here is an example code block using this API to help folks get started as we get the docs updated. I've put fake functions in upper snake case:

```objective-c

  // Checking for unsent reports requires automatic collection to be off.
  // This is sticky and will persist for future runs of the app.
  [[FIRCrashlytics crashlytics] setCrashlyticsCollectionEnabled:false];

  [[FIRCrashlytics crashlytics] checkAndUpdateUnsentReportsWithCompletion:^(FIRCrashlyticsReport * _Nullable report) {

    // Previous run had no crashes or non-fatals
    if (!report) {
      return;
    }

    NSLog(@"reportID%@", report.reportID);
    NSLog(@"dateCreated %@", report.dateCreated);
    NSLog(@"hasCrash %i", report.hasCrash);

    // Here we're only putting a popup asking for information if
    // there was a crash, because non-fatals can be noisy.
    if (!report.hasCrash) {

      // Check the user's default setting
      if (HAS_CRASH_COLLECTION_ENABLED()) {
        [[FIRCrashlytics crashlytics] sendUnsentReports];
      } else {
        [[FIRCrashlytics crashlytics] deleteUnsentReports];
      }
    }

    ASK_FOR_REPRO_CASE_AND_CONSENT(^(BOOL hasConsent) {
      // User doesn't want to send crash reports, so delete them.
      if (!hasConsent) {
        [[FIRCrashlytics crashlytics] deleteUnsentReports];
      }

      [report log:@"Log line"];
      [report logWithFormat:@"%@, %@", @"First", @"Second"];

      [report setUserID:@"ID"];

      [report setCustomValue:@"VALUE" forKey:@"KEY"];

      [report setCustomKeysAndValues:@{
        @"KEY_A": @"VALUE_A",
        @"KEY_B": @"VALUE_B",
      }];

      [[FIRCrashlytics crashlytics] sendUnsentReports];
    });
  }];

```

**Comment by ryanwilson** [comment]
Going to close this since the resolution landed but feel free to continue the conversation.
