### ISSUE TITLE
 Dynamic link on ios: the open in app button doesnt you app when you long press a link

### ISSUE THREAD

**Issue by pabloearg** [firebase/firebase-ios-sdk#6432]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.6
  * Firebase SDK version: 6.28.1
  * Firebase Component: Dynamic Link
  * Component version: 6.28.1
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

When i long press a link (for example on whatsapp), it must show you between the options "open with safari", "open with chrome".... the option Open with "my app name", but im not seeing this option in any device

![image](https://user-images.githubusercontent.com/29818262/92727431-7c2f7780-f345-11ea-9b3e-2d98f7657a57.png)

#### Steps to reproduce:

open a deep link on whatsapp long press the link watch that the open in "my app name" doesnt appear

#### Relevant Code:
 i have followed all instructions  to configure the app

add my associated domains:

```
applinks:myapp.page.link
applinks:myappTest.page.link
```

added URL types:

```
identifier: Bundle ID
URL Scheme: my bundle identifier
```

i have run 

`[FIRDynamicLinks performDiagnosticsWithCompletion:nil];
`
 and had the following result:

> ---- Firebase Dynamic Links diagnostic output start ----
Firebase Dynamic Links framework version 4.2.0
System information: OS iOS, OS version 13.6.1, model iPad
Current date 2020-09-10 14:27:21 +0000
Device locale en-US (raw en_US), timezone America/Argentina/Buenos_Aires
> ERROR: UIApplication delegate <AppDelegate: 0x283a42aa0> does not implements selector application:openURL:options:. FDL depends on this implementation to retrieve pending dynamic link.
> 	Specified custom URL scheme is co.myaapp and Info.plist contains such scheme in CFBundleURLTypes key.
> 	AppID Prefix: DW222222, Team ID: DW222222, AppId Prefix equal to Team ID: YES
> performDiagnostic detected 1 ERRORS.

but it doenst seem relevant for the issue

**Comment by rizafran** [comment]
Hi @pabloearg, I've tried to reproduce the issue, but I was able to see the "Open with <app_name>" in the option. This might be caused by any misconfigurations with your FDL. May I know if you're still encountering the issue?
