### ISSUE TITLE
Crashlytics crashes in WatchOS with sigaction on fatal signals is not supported

### ISSUE THREAD

**Issue by ecamacho** [firebase/firebase-ios-sdk#6434]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.6
  * Firebase SDK version: 6.31.0
  * Firebase Component: Crashlytics
  * Component version: 4.5.0
  * Installation method: `CocoaPods`

### [REQUIRED] Step 2: Describe the problem

After issue #4558 was closed thanks to PR #6262 I was looking forward to use it in my WatchApp but it doesn't work.

The Watch App Crashes with the message `sigaction on fatal signals is not supported` in file [FIRCLSSignal.c:96](https://github.com/firebase/firebase-ios-sdk/blob/d2482a5a8bde9247c2f7a28027237b5d037189ba/Crashlytics/Crashlytics/Handlers/FIRCLSSignal.c#L96).

A quick google search for that message leads to this relevant part of [Apple's open source code](https://opensource.apple.com/source/Libc/Libc-1244.1.7/sys/sigaction.c) that suggest WatchOS doesn't support the use of `sigaction`

#### Steps to reproduce:

1. Create an iOS app and add a WatchOS App
2. Add Crashlytics to the Watch Extension target
3. Initialise Crashlytics in the `WKExtensionDelegate` applicationDidFinishLaunching
4. Run the app on a device without debugging

#### Relevant Code:

Cocoapods file:
```ruby

target 'WatchOSCrashlytics' do
  platform :ios, '11.0'
  use_frameworks!
  pod 'FirebaseCrashlytics', '~> 4.5.0'
end

target 'WatchApp Extension' do
  use_frameworks!
  platform :watchos, '6.0'
  pod 'FirebaseCrashlytics', '~> 4.5.0'
end
```

Extension delegate

```swift
import FirebaseCore

class ExtensionDelegate: NSObject, WKExtensionDelegate {

    func applicationDidFinishLaunching() {
        FirebaseConfiguration.shared.setLoggerLevel(.debug)
        FirebaseApp.configure();
    }
    ...
}
```

**Comment by jostster** [comment]
I'll double check this but signals should of been disabled for AW. Thanks for the report!

**Comment by ecamacho** [comment]
@jostster thanks for the promptly response!
