### ISSUE TITLE
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[FIRAuthDataResult getIDTokenWithCompletion:]: unrecognized selector sent to instance 0x600002192000'

### ISSUE THREAD

**Issue by aneena-thomas** [firebase/firebase-ios-sdk#6441]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[FIRAuthDataResult getIDTokenWithCompletion:]: unrecognized selector sent to instance 0x600002192000'

**Comment by ryanwilson** [comment]
Hi @aneena-thomas - sorry for the trouble you're facing. Can you please fill out the [issue template](https://raw.githubusercontent.com/firebase/firebase-ios-sdk/master/.github/ISSUE_TEMPLATE/bug_report.md) so we can get a better understanding of what's going on? With only the given information we don't have much to start on and won't be able to make progress on solving your issue.

Thanks!

**Comment by aneena-thomas** [comment]
* Xcode version: 11.4.1
  * Firebase SDK version: 6.32
  * Firebase Component: FirebaseAuth(6.91.)(Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 6.9.1
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem
After installing the pod file with the latest version I got the following error

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[FIRAuthDataResult getIDTokenWithCompletion:]: unrecognized selector sent to instance 0x600002192000'

#### Steps to reproduce:

What happened? How can we make the problem occur?
I have used FirebaseAuth to verify the login, 


If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

**Comment by morganchen12** [comment]
Can you share a project that reproduces this issue?

**Comment by aneena-thomas** [comment]
Sorry its my client project I can't able to share it

**Comment by morganchen12** [comment]
Unfortunately we won't be able to help you effectively debug this issue without a reproducible sample. The selector referenced in the crash message is implemented in [`FIRUser`](https://github.com/firebase/firebase-ios-sdk/blob/bf0cb09d51adc83fa8a21217804c6413b9be2d42/FirebaseAuth/Sources/User/FIRUser.m#L858), not `FIRAuthDataResult`. Please check that you are not incorrectly casting `FIRAuthDataResult` pointers to the wrong type.

**Comment by aneena-thomas** [comment]
I changed this function to     

[[FIRAuth auth] signInWithCredential:credential completion:^(FIRUser * _Nullable firUser, NSError * _Nullable error) {
    }];
to this
    [[FIRAuth auth] signInWithCredential:credential completion:^(FIRAuthDataResult * _Nullable authResult, NSError * _Nullable error) {
        <#code#>
    }]
 I this is the issue,

**Comment by ryanwilson** [comment]
What was the old version of Firebase you were using? It could have been a major version or two ago, in which case this is an expected break. I believe the version used in the project previously was 4.X and we're on 6.X right now preparing for 7. 

It would be a good idea to take a look at the changelogs for the breaking changes: [5.0 breaking changes](https://firebase.google.com/support/release-notes/ios#_version_500_-_may_8_2018) and [6.0 breaking changes](https://firebase.google.com/support/release-notes/ios#version_600_-_may_7_2019).
