### ISSUE TITLE
Swift Package Manager: nanopb deployment target warning

### ISSUE THREAD

**Issue by aschuch** [firebase/firebase-ios-sdk#6449]
### Environment

  * Xcode version: Xcode 12 beta 6
  * Firebase SDK version: 6.32-spm-beta
  * Firebase Component: Analytics
  * Installation method: Swift Package Manager

### Problem

Firebase is dependent on the nanopb framework. This dependency shows the following warning in Xcode 12 beta 6 when integrating Firebase Analytics using Swift Package Manager:

```
The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.
```

<img width="328" alt="Screenshot 2020-09-12 at 12 51 31" src="https://user-images.githubusercontent.com/1506193/92994107-b476b780-f4f7-11ea-8ab2-3df72f351dd5.png">

#### Steps to reproduce:

1. Integrate the Firebase Analytics SDK into a new project following the documentation for [Firebase Swift Package Manager support](https://github.com/firebase/firebase-ios-sdk/blob/master/SwiftPackageManager.md)
1. Observe that there is a new warning related to the nanopb framework when building the project

**Comment by paulb777** [comment]
Thanks for the report. This is also a problem for other Firebase dependencies that support iOS 8 and earlier as well. I started a discussion at https://forums.swift.org/t/minimum-ios-version-xcode-12-and-build-warnings/40224 to explore solutions.

![Screen Shot 2020-09-12 at 7 12 35 AM](https://user-images.githubusercontent.com/73870/92997367-9d1fd600-f4c7-11ea-9b3b-1d5a6494f0dc.png)

**Comment by paulb777** [comment]
https://github.com/nanopb/nanopb/pull/585 is sent for nanopb. We'll follow up with the other dependency updates and updates to the Firebase Package.swift in the next week or so.
