### ISSUE TITLE
'FirebaseInstallations/FirebaseInstallations.h' file not found

### ISSUE THREAD

**Issue by jvigneshcs** [firebase/firebase-ios-sdk#6453]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.7
  * Firebase SDK version: 6.32.0
  * Firebase Component: Core, Crashlytics
  * Component version: Core (6.10.2), Crashlytics (4.6.0)
  * Installation method: `CocoaPods ✔️ | Carthage | Zip file | Swift Package Manager` (select one)

### [REQUIRED] Step 2: Describe the problem
Getting FirebaseInstallations/FirebaseInstallations.h file not found inside the file FirebaseInstallationsInternal.h

![Screenshot 2020-09-13 at 6 19 18 PM](https://user-images.githubusercontent.com/1597360/93047107-4b1eb200-f679-11ea-95bd-ba90d1c5678b.png)

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

I had to setup the Mac again, after doing and setup the Code and did pod install.
Then when I try to build I got this issue.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
FirebaseApp.configure()
```

**Comment by ryanwilson** [comment]
Sorry for the troubles you're seeing - typically this is a bad state of Xcode, CocoaPods, and some derived data.

Does the following help? Note this will delete derived data for all your projects - you can manually find and remove the derived data for just this project if it's preferred.

```
rm -rf ~/Library/Developer/Xcode/DerivedData/
pod deintegrate
pod update
```

**Comment by jvigneshcs** [comment]
@ryanwilson , The solution you mentioned worked for me.
