### ISSUE TITLE
Is FirebaseGoogleSignIn missing from the Swift Package Manager distribution?

### ISSUE THREAD

**Issue by puls** [firebase/firebase-ios-sdk#6477]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0 GM seed (12A7209)
  * Firebase SDK version: 6.32-spm-beta
  * Firebase Component: Auth (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: ?
  * Installation method: `Swift Package Manager`

#### Steps to reproduce:

With Xcode 12 now available as a GM, I'm looking into using SPM for integrating Firebase. I removed these five lines from my `Cartfile`:
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAuthBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseGoogleSignInBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseProtobufBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseRemoteConfigBinary.json"
```

Then I added the Swift package as described in [the docs](https://github.com/firebase/firebase-ios-sdk/blob/master/SwiftPackageManager.md). But I don't see GoogleSignIn available anywhere and my builds fail with it missing.

Sorry if I'm missing something, but is this just not supported yet?

#### Relevant Code:

Code is as seen at https://firebase.google.com/docs/auth/ios/google-signin.

**Comment by paulb777** [comment]
Right, GoogleSignIn does not yet have Swift PM support yet.

We're following up with the GoogleSignIn team and will update here when we have more detail.

**Comment by Xhale1** [comment]
Has there been any new information from the GoogleSignIn team?

**Comment by sugarpac** [comment]
[https://github.com/googlesamples/google-services/issues/484](url)

**Comment by sugarpac** [comment]
googlesamples/google-services#484

**Comment by piers12** [comment]
Any new update on this @paulb777 ?

**Comment by paulb777** [comment]
The GoogleSignIn team is investigating, but nothing specific I can share about future plans.

**Comment by sugarpac** [comment]
@paulb777 @piers12 

Though I am still waiting for the GoogleSignIn team's version, I've got along well with https://github.com/sugarpac/SwiftGoogleSignIn based on https://github.com/CocoaPods/Specs/blob/master/Specs/d/4/0/GoogleSignIn/5.0.2/GoogleSignIn.podspec.json. Inside it, https://github.com/sugarpac/GTMAppAuth is used instead of https://github.com/google/GTMAppAuth as a minimum platform update from iOS 8 to iOS 9 is requested for compiling.

Try adding `https://github.com/sugarpac/SwiftGoogleSignIn` to your package dependencies, and use `GoogleSignIn`.

**Comment by Bartozo** [comment]
Any new updates about GoogleSignIn version for swift package manager @paulb777 ?

**Comment by paulb777** [comment]
There is some progress described at https://stackoverflow.com/questions/65469685/using-google-sign-in-for-ios-with-swift-package-manager for a workaround

**Comment by malcommac** [comment]
I've the impression this framework is abandoned; is there an alternative to allow signin with Google in mobile app?

**Comment by paulb777** [comment]
GoogleSignIn continues to be distributed via CocoaPods and a binary distribution. Swift Package Manager support is being investigated.

**Comment by yoxisem544** [comment]
I've checked firebase sdk using swift pm, but I can't see GoogleSignIn be available to install via swift pm. When will GoogleSignIn can be install via swift pm?

**Comment by trusk89** [comment]
Still no updates on this @paulb777?

**Comment by paulb777** [comment]
@trusk89 Sorry, all I can say is there is active progress.

**Comment by trusk89** [comment]
@paulb777 thanks for the update!

**Comment by rromanchuk** [comment]
+1 if you can also just ask that team to just distribute via github.  If it helps the sale, and i'm not even kidding when i say this, i'm literally just going to drop google sign in as a federated provider on ios without spm, because i'm far far too lazy to manage downloading binaries and linking manually.

**Comment by rogerluan** [comment]
Is there any way the community can help make support to SPM be released any faster? I'm sure there's a lot at stake here, and many people would be willing to help, myself included. 
It's not just the lack of SPM, but also the lack of an arm64 distribution, which makes GoogleSignIn not available to be run on the simulator of M1 (Apple Silicon) machines:

```
ld: in /Users/redacted/Documents/Projects/redacted-ios/Pods/GoogleSignIn/Frameworks/GoogleSignIn.framework/GoogleSignIn(GIDEMMErrorHandler_3a47e13d8ca81b41e9cdb7ef5468004a.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/redacted/Documents/Projects/redacted-ios/Pods/GoogleSignIn/Frameworks/GoogleSignIn.framework/GoogleSignIn' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm scared to imagine why recompiling a lib in a different architecture (arm64, and distribute via XCFramework) would take over 9 months 🙀 
Any update here would be welcome!

**Comment by paulb777** [comment]
Sorry for the delay. The implementation is still in active development and we'll update here when we can share timing.

**Comment by BrentMifsud** [comment]
Thanks for the update on this. Look forward to SPM support.

This is one of the last pods we have left that we're waiting to move over to SPM.

**Comment by anatoliykant** [comment]
Hey, @paulb777 
Thanks for everything your team is doing. 🚀
There are some updates. 🤔
Maybe I can help if you can tell me where you got stuck with SPM? 😉

**Comment by vince1393** [comment]
Any progress on this? This is one of the last ones before we can fully migrate to SPM

**Comment by lahdekorpi** [comment]
> Any progress on this? This is one of the last ones before we can fully migrate to SPM

https://github.com/firebase/firebase-ios-sdk/issues/6528#issuecomment-857176072

**Comment by vince1393** [comment]
> [#6528 (comment)](https://github.com/firebase/firebase-ios-sdk/issues/6528#issuecomment-857176072)

Does this include Google Sign In? Looks like Performance is almost ready, will it include both?

**Comment by paulb777** [comment]
@vince1393 Possibly, but not necessarily. Both projects are ongoing from two different teams with different sets of release criteria.

**Comment by chessmyers** [comment]
I hate to add yet another follow-up about this, but would it be possible to give a rough estimate of the release date for this new SPM package? Even a general month range from now would be very helpful! @paulb777

**Comment by rogerluan** [comment]
Truth be told, I'm actively working towards getting rid of the 2 Google dependencies we use: Firebase Crashlytics (Sentry is MUCH better) and Google Sign In (low conversion rate). Soon I'll be able to finally unsubscribe from this issue 🤩 

Just shedding some light to some folks out there, in case you _think_ you need Google :)

**Comment by yoxisem544** [comment]
@rogerluan that's true. Sentry is good alternative choice.

**Comment by BrentMifsud** [comment]
> Truth be told, I'm actively working towards getting rid of the 2 Google dependencies we use: Firebase Crashlytics (Sentry is MUCH better) and Google Sign In (low conversion rate). Soon I'll be able to finally unsubscribe from this issue 🤩 
> 
> 
> 
> Just shedding some light to some folks out there, in case you _think_ you need Google :) 

Instabug is also pretty fantastic as a crashlytics alternative.

**Comment by vince1393** [comment]
> Truth be told, I'm actively working towards getting rid of the 2 Google dependencies we use: Firebase Crashlytics (Sentry is MUCH better) and Google Sign In (low conversion rate). Soon I'll be able to finally unsubscribe from this issue 🤩
> 
> Just shedding some light to some folks out there, in case you _think_ you need Google :)

Convincing the product side to let us drop sign-in sounds like a mountain I have no intention to climb. But I've planted the seed to switch from Crashlytics, Google has made it clear that we can't put all our eggs in one basket

**Comment by lahdekorpi** [comment]
> > Truth be told, I'm actively working towards getting rid of the 2 Google dependencies we use: Firebase Crashlytics (Sentry is MUCH better) and Google Sign In (low conversion rate). Soon I'll be able to finally unsubscribe from this issue 🤩
> > Just shedding some light to some folks out there, in case you _think_ you need Google :)
> 
> Convincing the product side to let us drop sign-in sounds like a mountain I have no intention to climb. But I've planted the seed to switch from Crashlytics, Google has made it clear that we can't rely on them enough to put all our eggs in one basket

I get the Crashlytics, as almost any alternative is better than what it offers. But dropping one of the SSOs that were available previously, especially if it has thousands of users, isn't really realistic.

**Comment by rogerluan** [comment]
Yup ☝️  we're quite lucky to be able to make that decision as of right now. Perhaps if we dragged this for longer, it wouldn't be as easy. 🙏

**Comment by vince1393** [comment]
On that note... Are we even remotely close to getting support for this?

**Comment by iGriever** [comment]
Any updates on this? I'm sure many people would be very interested in having at least a rough timeline, just to set expectations. Besides, there seems to be no current/reliable solution for #7208, when adding the SDK as a manual dependency (especially in a SPM + manual dependencies setup, without CocoaPods). Let's not mention running Xcode with Rosetta, please. The latest GoogleSignIn iOS SDK version dates back to 2019-11, which is... worrying, to say the least. If there's any sort of progress please, let us know, it would be very appreciated.

**Comment by petea** [comment]
I'm happy to be able to announce that next week we will be making a substantive update to Google Sign-In for iOS that will provide support for Swift Package Manager among other improvements.  It's taken longer than we would have liked, but the wait is nearly over.  I'll provide another update here as soon as the new release is available.

**Comment by petea** [comment]
Google Sign-In for iOS 6 has been released and is now open source on GitHub!

https://github.com/google/GoogleSignIn-iOS

**Comment by paulb777** [comment]
Thanks @petea!

**Comment by vvghost1** [comment]
> Google Sign-In for iOS 6 has been released and is now open source on GitHub!
> 
> https://github.com/google/GoogleSignIn-iOS

For iOS 9, not 6. Thank you!

**Comment by paulb777** [comment]
Actually version 6.0.0 of the GoogleSignIn SDK. :)

**Comment by petea** [comment]
> Actually version 6.0.0 of the GoogleSignIn SDK. :)

Yeah, that wording was a little confusing.  Updated.

**Comment by paulb777** [comment]
Closing for comments.  Please make any additional followups at https://github.com/google/GoogleSignIn-iOS
