### ISSUE TITLE
Including FirebaseCrashlytics causes automatic signing to fail

### ISSUE THREAD

**Issue by Baza207** [firebase/firebase-ios-sdk#6480]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0 (12A7209)
  * Firebase SDK version: 6.32.0
  * Firebase Component: Crashlytics
  * Component version: 4.6.0
  * Installation method: Zip file

### [REQUIRED] Step 2: Describe the problem

When I include the Firebase Crashlytics framework and archive and build my project when I'm trying to upload the build to App Store Connect it always fails asking me to select a provisioning profile which I don't have as the project is automatically signed.

It seems like the Crashlytics framework is bring pre-signed and so causing an issue with Xcode when it goes to automatically sign the app. It finds conflicting signatures and so just defaults back to manual signing, which then fails because when using fully automatic signing these days provisioning profiles don't show up in the list anymore, so it's an empty list and blocks uploading the app.

I've been contacting Apple Developer Technical Support about the issue and they've helped narrow it down to the Crashlytics framework.

To quote them:
> You’re being forced down the manual signing path because your app contains an x86_64 executable that was signed by a 3rd party:
> 
> $ file /<REDACTED>/upload-symbols 
> /<REDACTED>/upload-symbols: Mach-O 64-bit executable x86_64
> Itais-iMac-Pro:HighLevelTools itairom$ codesign -dvvv /<REDACTED>/upload-symbols 
> Executable=/<REDACTED>/upload-symbols
> Identifier=$(PRODUCT_BUNDLE_IDENTIFIER)
> Format=Mach-O thin (x86_64)
> CodeDirectory v=20200 size=2364 flags=0x0(none) hashes=66+5 location=embedded
> Hash type=sha256 size=<REDACTED>
> CandidateCDHash sha1=<REDACTED>
> CandidateCDHashFull sha1=<REDACTED>
> CandidateCDHash sha256=<REDACTED>
> CandidateCDHashFull sha256=<REDACTED>
> Hash choices=sha1,sha256
> CMSDigest=<REDACTED>
> CMSDigestType=<REDACTED>
> CDHash=<REDACTED>
> Signature size=<REDACTED>
> Authority=Developer ID Application: Crashlytics, Inc. (<REDACTED>)
> Authority=Developer ID Certification Authority
> Authority=Apple Root CA
> Signed Time=Mar 31, 2020 at 11:36:45 AM
> Info.plist entries=8
> TeamIdentifier=<REDACTED>
> Sealed Resources=none
> Internal requirements count=1 size=220

#### Steps to reproduce:

Create a project with Firebase Crashlytics which has automatic signing on and attempting to upload to App Store Connect.

#### Relevant Code:

NA

**Comment by ryanwilson** [comment]
Hi @Baza207, thanks for the report.

The `run` and `upload-symbols` binaries should not be included in your app, these are Mac utilities in order for you to upload symbols to the Crashlytics backend. It looks like you've added these to your Xcode project and are including it in your app's target. Once you remove it from the target, you should be able to proceed.

I'll close this for now since this should resolve your issue, feel free to keep commenting if you need a hand. Thanks!

**Comment by Baza207** [comment]
Oh wow. Looks like I missed them when drag and dropping the folder into my project. 🤦‍♂️ I'll give it a try next time I can and see if that fixes the issue. Thanks for the feedback. 🙇‍♂️

**Comment by ryanwilson** [comment]
No problem :) thanks for using Crashlytics and please open another issue if you see something else!
