### ISSUE TITLE
GoogleDataTransport build errors in Xcode 12.0 GM for file nanopb-umbrella.h

### ISSUE THREAD

**Issue by demo84** [firebase/firebase-ios-sdk#6484]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: __12.0___
  * Firebase SDK version: __6.32.2___
  * Firebase Component: ___Nanopb__ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: __1.30906.0___
  * Installation method: `CocoaPods` (select one)

#### Steps to reproduce:

What happened? How can we make the problem occur?
Xcode project fails to build in v12.0. multiple build errors for file nanopb-umbrella.h

Error on all of the imports. for example for the line 
#import "pb.h"
the error shows as
'Double-quoted include "pb.h" in framework header, expected angle-bracketed instead'

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by mattiosdev** [comment]
Same issue. Removed pod 'Firebase/Analytics' for now.

**Comment by ryanwilson** [comment]
Hey @demo84 and @mattiosdev - sorry for the troubles you're seeing.

I'm unable to reproduce this using the Analytics quickstart with the Xcode GM (I tested both the 12A7208 and 12A7209 versions just to be sure). Are either of you able to provide a sample project with this issue happening, or able to reproduce it in the quickstarts?

A cleaning of derived data, etc may help as well.

**Comment by paulb777** [comment]
See https://stackoverflow.com/questions/63646607/xcode-12-using-firebase-pods-lexical-or-preprocessor-issue-pb-h-file-not-fou/63648164#63648164

**Comment by mattiosdev** [comment]
Thanks Paul. This one works for me: https://stackoverflow.com/a/63650106/4440181

**Comment by paulb777** [comment]
I'm going to close based on the fix in CocoaPods 1.10 and workarounds available for earlier versions.

Potentially there is a more fundamental discussion about generating umbrella headers with brackets instead of quotes, but that should be taken up in the CocoaPods repo.

**Comment by saad522** [comment]
> See https://stackoverflow.com/questions/63646607/xcode-12-using-firebase-pods-lexical-or-preprocessor-issue-pb-h-file-not-fou/63648164#63648164
Thanks Pau 👍🏼

**Comment by saad522** [comment]
> See https://stackoverflow.com/questions/63646607/xcode-12-using-firebase-pods-lexical-or-preprocessor-issue-pb-h-file-not-fou/63648164#63648164
Thanks Paul.
