### ISSUE TITLE
Firebase Dynamic Links only working on iPhone devices 

### ISSUE THREAD

**Issue by jtbergman** [firebase/firebase-ios-sdk#6489]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1 (also 11.7)
  * Firebase SDK version: 6.32.0
  * Firebase Component: Firebase Dynamic Links
  * Component version: 4.3.0
  * Installation method: `Carthage`

### [REQUIRED] Step 2: Describe the problem
We have created an app to use Firebase Dynamic Links. For iPhone devices, pre-install and post-install dynamic links work without issue on all our required iOS versions (iOS 11+). However, for iPad devices only post-install dynamic links work.

All deferred dynamic links result in the following URL 
```
<bundle-id-based-url-scheme>://google/link/?request_ip_version=IP%5FV6&match_message=No%20pre%2Dinstall%20link%20matched%20for%20this%20device%2E
```

#### Steps to reproduce:
1. Delete app from device 
2. Click a dynamic link and receive redirect
3. Reinstall app using Xcode / TestFlight / AppStore
4. On all iPhones, the link will be handled in the app correctly. On all iPads, there is "no pre-install link matched"

I will try to update with a sample project. 

#### Relevant Code:
Here is roughly what the code looks like
```swift 
func application(
        _ app: UIApplication,
        open url: URL,
        options: [UIApplication.OpenURLOptionsKey : Any] = [:]
    ) -> Bool {
        print("1. \(url)")
        if let link = DynamicLinks.dynamicLinks().dynamicLink(fromCustomSchemeURL: url) {
            print("2. \(url)")
            if let url = link.url {
                // ... 
            }
            return false 
        }
        // ... 
}
```

Here is the output
```
1. <url-scheme>://google/link/?request_ip_version=IP%5FV6&match_message=No%20pre%2Dinstall%20link%20matched%20for%20this%20device%2E
2. <FIRDynamicLink: 0x283858840, url [(null)], match type: none, minimumAppVersion: N/A, match message: No pre-install link matched for this device.>
```

Just to re-iterate, the above only happens on iPads.

**Comment by eldhosembabu** [comment]
Hi @jtbergman ,

I've tried reproducing the issue on ipad and was able to get link matches. Could you please try to reproduce the issue in the [quick start app](https://github.com/firebase/quickstart-ios/tree/master/dynamiclinks)

**Comment by jtbergman** [comment]
Hi @eldhosembabu,

I was able to reproduce the issue with the quick start app and have more information / the cause of the issue. For our business use case, we want to skip the preview page. For links created via the console, "Skip the app preview page" is selected. Links created via the api will contain `"navigationInfo":{"enableForcedRedirect":true}`. This appears to be the cause of the issue. 

Steps for Correct Behavior
1. Create a link that does not have forced redirect
2. Select the link and be redirect to the preview page 
3. On the preview page, click open to be redirected to App Store
4. Install Quick Start Project via Xcode while in the App Store
5. The app will correctly display the dynamic link 

Reproduce the Incorrect Behavior
1. Modify the existing link or create a new link so that forced redirect is enabled 
2. Click the click and it will redirect either to the App Store or sometimes to the embedded link (inconsistent behavior) 
3. Install Quick Start Project via Xcode while on the page that was redirected to 
4. The alert will be empty and not contain the embedded link

Note that this only affects iPads. iPhones work fine with forced redirect enabled. 

If you need additional information let me know and I can provide GIFs or code.

**Comment by jtbergman** [comment]
Hi @eldhosembabu,

I was wondering if there were any updates on reproducing this or if the issue may need to be raised in another repo as well? 

Thanks!

**Comment by nahashsvb** [comment]
Could someone help to resolve this issue. We still have the same one and it is critical for us.
The Dynamic links don't work on the iPads, but work on the iPhone.
We will have to move to another non-free solution if the issue is not fixed soon. Something like https://branch.io.
Firebase, please do something with this!  I've read a lot of related closed issues, like this one: https://github.com/firebase/firebase-ios-sdk/issues/1244
And it is still observed on the latest iOS version.

NOTE: The case is related only to the **checked** box in the Firebase console: **_"Skip the app preview page (not recommended)"_**
The steps to reproduce:
1. Remove the app from the device if it is already installed.
2. Open the dynamic link on iPad.
3. Install the app from the AppStore
4. Open the app

Thanks!

**Comment by eldhosembabu** [comment]
Does that means for a Dynamic link with app preview disabled or navigationInfo":{"enableForcedRedirect":true};
the dynamic links are not retrieved in ipads but working for iphones?

I'm checking with backend teams on this and will keep you posted.

**Comment by eldhosembabu** [comment]
Could you please confirm whether the bundle id for ipad and iphone are same?

**Comment by nahashsvb** [comment]
Hey @eldhosembabu! Thank you for your response!

> Dynamic link with app preview disabled or navigationInfo":{"enableForcedRedirect":true};

Right, the  app preview is disabled

> The dynamic links are not retrieved in ipads but working for iphones?

Right

> Could you please confirm whether the bundle id for ipad and iphone are same?

Confirmed, the bundle id is the same

**Comment by zhahaoyu** [comment]
If I set false for `enableForcedRedirect`, there is no link detected on iPhone. I have ios 14.1

**Comment by RajanMaheshwari** [comment]
Even in iOS 14.6 iPhone, if the preview page is not skipped, means the checkbox is unchecked in the dashboard and the preview page comes. Still, the first app install is giving the same issue
```
<mybundleidscheme>://google/link/?request_ip_version=IP%5FV4&match_message=No%20pre%2Dinstall%20link%20matched%20for%20this%20device%2E

po dynamicLink.url
nil

(lldb) po dynamicLink
<FIRDynamicLink: 0x28098ca00, url [(null)], match type: none, minimumAppVersion: N/A, match message: No pre-install link matched for this device.>
```

**Comment by artalejo** [comment]
I am also facing the same issue when configuring a custom domain and custom deeplink. ( iOS version 14.6 as well as 14.7 )

Running the diagnosis tool `DynamicLinks.performDiagnostics(completion: nil)` prints that I do have the correct configuration but still when trying to get the deeplink passed on the first installation step it retrieves the following:

`<FIRDynamicLink: 0x281285680, url [(null)], match type: none, minimumAppVersion: N/A, match message: No pre-install link matched for this device.>
`
`[Firebase/Analytics][I-ACS023001] Deep Link does not contain valid required params. URL params: {
    "match_message" = "No pre-install link matched for this device.";
    "request_ip_version" = "IP_V4";
}`


If I do click on the deeplink after the app is installed it all works as expected, but not when being redirected to the Apple Store and installing the app. 

Could somebody please help out and solve this issue ?

**Comment by urthling** [comment]
This has now been an issue for months -- is there any planned fix for this?

**Comment by EmilKaczmarski** [comment]
I there any update? I'm facing the same issue

**Comment by martin-desimone-mission** [comment]
Facing same issue

**Comment by nberthelot** [comment]
Facing same issue

**Comment by h-unterp** [comment]
Kind of same. Except ```Could not find a generator for route RouteSettings("/link?request_ip_version=IP%5FV4&match_message=No%20pre%2Dinstall%20link%20matched%20for%20this%20device%2E", null) in the _WidgetsAppState.
Make sure your root app widget has provided a way to generate
this route.```

I just get this error when installing app fresh. Not even trying to click on any links

**Comment by thruthesky** [comment]
Facing the same issue

**Comment by brianschardt** [comment]
facing same issue

**Comment by lvjsdev** [comment]
facing same issue. 
Any updates?

**Comment by ruairioliverwv** [comment]
Same issue here, not just iPad but iPhone as well

**Comment by fullflash** [comment]
same issue
"google/link/?request_ip_version=IP_V4&match_message=No%20pre-install%20link%20matched%20for%20this%20device."

**Comment by jmgawecki** [comment]
Hi there, has anyone found the solution here? I am facing the same issue :(

**Comment by davefaliskie** [comment]
Also having this issue anyone find a fix?

**Comment by paulb777** [comment]
The Firebase Dynamic Links service will be shutdown on August 25, 2025.  In the meantime, only critical or security issues will be fixed in the SDK.

More at https://firebase.google.com/support/dynamic-links-faq
