### ISSUE TITLE
The Audiences not work. 

### ISSUE THREAD

**Issue by GuibinLu** [firebase/firebase-ios-sdk#6494]
The percentage of your users who are identified with each interest category.
Do we need to do other configuration in FireBase

I've seen the Predictive library documentation, but I'm not sure about that, because none of the previous programs have had additional offerings

**Comment by ryanwilson** [comment]
Hi @GuibinLu, hoping to get a bit more information to understand what's going on.

- Which products and SDKs are you using? Which versions?
- Is this a problem with the SDK? Or a general product question?

It sounds like this could be a better question for [support](https://firebase.google.com/support) - Issues are to report bugs and feature requests for the SDK but it doesn't look like this is an SDK specific issue.
