### ISSUE TITLE
Thanks for SPM support!

### ISSUE THREAD

**Issue by ekimia** [firebase/firebase-ios-sdk#6501]
I dont have an issue (no thanks tab in github), just wanted to say a major thank you to the Firebase team for SPM support! Especially with Carthage being super buggy with xcode 12, this saved the day for me.

**Comment by morganchen12** [comment]
The credit goes mostly to Paul for his work on SPM support 👍

**Comment by paulb777** [comment]
You're welcome! I appreciate the feedback. :) Kudos to @ryanwilson who also make several significant contributions to the Firebase Swift Package Manager project.

**Comment by jarrodrobins** [comment]
I'd definitely echo the thanks to the FIrebase team as well. I _really_ want to get off Cocoapods and Firebase is the last part of the plan. We'll be able to remove it completely once Firebase Messaging gets SPM support. Thanks for all your hard work thus far!

**Comment by paulb777** [comment]
👍
