### ISSUE TITLE
Deprecations: 'unarchiveObjectWithData:' is deprecated: first deprecated in iOS 12.0 - Use +unarchivedObjectOfClass:fromData:error: instead

### ISSUE THREAD

**Issue by KevinVladG** [firebase/firebase-ios-sdk#6502]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12
  * Firebase SDK version: 6.32.2
  * Firebase Component: Database
  * Component version: 6.6.0
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

Warning for Deprecations shows up:

/Users/{$CURRENT_USER}/{$PROJECT_FOLDER}/Pods/FirebaseDatabase/FirebaseDatabase/Sources/Persistence/FLevelDBStorageEngine.m:169:50: 'unarchiveObjectWithData:' is deprecated: first deprecated in iOS 12.0 - Use +unarchivedObjectOfClass:fromData:error: instead

#### Steps to reproduce:

- Updated to Xcode version 12
- Install/Update pods in working project
- Update pods to Swift 5.0 framework
- Applications Builds and Runs on iOS version 14
- Warning for Deprecations shows up for FirebaseDatabase pod

#### Relevant Code:

- Path to file: /Users/{$CURRENT_USER}/{$PROJECT_FOLDER}/Pods/FirebaseDatabase/FirebaseDatabase/Sources/Persistence/FLevelDBStorageEngine.m

- File name: FLevelDBStorageEngine.m

- Line number of error: 169:50

```
id pendingPut = [NSKeyedUnarchiver unarchiveObjectWithData:data];
```

**Comment by KevinVladG** [comment]
Temp. fix would be to set the "Deprecated Functions" setting in Pods to No. this will ignore the error but it's still exists.

**Comment by paulb777** [comment]
@KevinVladG Thanks for the report. What's the reason for changing the pods build optoins to Swift 5 and how exactly are you doing that?  Most of the Firebase pods are written in Objective C and support back to iOS 8 or 9.

We can potentially ifdef the code to address this, but I'm curious to get more context about the use case.

**Comment by KevinVladG** [comment]
@paulb777 I updated the Firebase pods using Xcode 12 Issues navigator. There was an option for my current project and for the pods and such. that would be great! I just wanted to be sure you guys were aware of it on this new release.

**Comment by KevinVladG** [comment]
@paulb777 Thank you Paul! I will keep checking for the merge.

**Comment by paulb777** [comment]
@KevinVladG Sorry, the fix was a bit more complicated than I initially thought and we haven't been able to prioritize yet

**Comment by KevinVladG** [comment]
@paulb777 no worries I have been following along. I've silenced the warning so no worries!

**Comment by garfieldmypet** [comment]
@paulb777 Our team is hitting the same issue and we are not able to compile our code in Xcode12. We are an online marketplace IOS app, can you please prioritise the fix. We need to push some features for our app, and couldn't do so due to this issue.
