### ISSUE TITLE
Swift Package Manager: FirebaseAnalyticsWrapper.modulemap Umbrella directory not found

### ISSUE THREAD

**Issue by aschuch** [firebase/firebase-ios-sdk#6503]
### Environment

  * Xcode version: Xcode 12 (12A7209)
  * Firebase SDK version: 6.33-spm-beta
  * Firebase Component: Analytics
  * Installation method: Swift Package Manager

### Problem

After installing Firebase Analytics version 6.33-spm-beta, a new warning started to appear. This warning was not present in earlier releases.

FirebaseAnalyticsWrapper.modulemap
```
/Users/[redacted]/Library/Developer/Xcode/DerivedData/[redacted]/Build/Intermediates.noindex/GeneratedModuleMaps-iphonesimulator/FirebaseAnalyticsWrapper.modulemap:2:10: Umbrella directory '/Users/[redacted]/Library/Developer/Xcode/DerivedData/[redacted]/SourcePackages/checkouts/firebase-ios-sdk/FirebaseAnalyticsWrapper/Public' not found
```

#### Steps to reproduce:

1. Integrate the Firebase Analytics SDK into a new project following the documentation for [Firebase Swift Package Manager support](https://github.com/firebase/firebase-ios-sdk/blob/master/SwiftPackageManager.md)
1. Observe that there is a new warning related to the path in FirebaseAnalyticsWrapper.modulemap when building the project

**Comment by paulb777** [comment]
@aschuch Thanks for the report. I've reproduced and will work on a fix. In the meantime I believe the warning is innocuous.

**Comment by aschuch** [comment]
Thanks for your quick support, appreciated!

**Comment by paulb777** [comment]
Should now be fixed with "Update to latest package versions"
