### ISSUE TITLE
AppMeasurement crash with iOS 14 on latest google mobile ads sdk

### ISSUE THREAD

**Issue by jjxtra** [firebase/firebase-ios-sdk#6505]
Using Xcode 12, iOS 14, iPhone 7 Plus. I am running a pi-hole for my dns which blocks most ad requests.

Upon launch of my application, google ad measurement crashes. Rolling back to the last 2019 app measurement framework eliminates the crash. It appears to be in a `[AdMeasurement protoBuf]` call. My guess is something is not checking for a blocked response and assuming valid binary data.

**Comment by paulb777** [comment]
@jjxtra Thanks for the report. Please share the backtrace and fill out the Issue template.

**Comment by jjxtra** [comment]
I've worked around this by reverting to 2019 version of app measurement. Just FYI for anyone else who comes across the problem.
