### ISSUE TITLE
SPM FirebaseApp.configure() taking over a minute to complete.

### ISSUE THREAD

**Issue by detectedstealth** [firebase/firebase-ios-sdk#6506]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 12.0 (12A7209)
  * Firebase SDK version: 6.33-spm-beta
  * Firebase Component:  FirebaseApp.configure() 
  * Component version: _____
  * Installation method: `Swift Package Manager` (select one)

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

`Create a new SwiftUI project add Firebase as a dependency with SPM select Auth, Analytics, Firestore, FirestoreSwift. In AppDelegate try to configure the app and run on Device. Takes over a minute to complete the configuration step holding up the rest of the app.`

#### Relevant Code:

```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    // Override point for customization after application launch.
    
    FirebaseApp.configure()
    print("Tried to configure firebase app")
    
    return true
}
```
[NOTE] To get things to install correctly on a physical device I set the following in scheme build post-actions:
```
rm -rf "${TARGET_BUILD_DIR}/MyApp.app/Frameworks/FirebaseAnalytics.framework"
rm -rf "${TARGET_BUILD_DIR}/MyApp.app/Frameworks/GoogleAppMeasurement.framework"
rm -rf "${TARGET_BUILD_DIR}/MyApp.app/Frameworks/FIRAnalyticsConnector.framework"

```

**Comment by paulb777** [comment]
@detectedstealth Thanks for the report. We'll investigate in the next few days. In the meantime, here are a few ideas that could help to isolate:

- What is showing up in the console log?
- Any different behavior with the `6.32-spm-beta` branch?
- Any different behavior with fewer Firebase dependencies?

**Comment by detectedstealth** [comment]
@paulb777 

- There is nothing in the console while the delay the app just shows a white empty screen once initialization is finally complete the console shows the following:
```
2020-09-19 17:38:55.176913-0700 Make It So[10863:1834047] 6.32.0 - [Firebase/Analytics][I-ACS023007] Analytics v.60803000 started
2020-09-19 17:38:55.177046-0700 Make It So[10863:1834047] 6.32.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2020-09-19 17:38:55.575574-0700 Make It So[10863:1834046] 6.32.0 - [Firebase/Analytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
2020-09-19 17:38:55.621084-0700 Make It So[10863:1834047] 6.32.0 - [Firebase/Analytics][I-ACS023012] Analytics collection enabled
2020-09-19 17:38:55.621532-0700 Make It So[10863:1834046] 6.32.0 - [Firebase/Analytics][I-ACS023220] Analytics screen reporting is enabled. Call +[FIRAnalytics logEventWithName:FIREventScreenView parameters:] to log a screen view event. To disable automatic screen reporting, set the flag FirebaseAutomaticScreenReportingEnabled to NO (boolean) in the Info.plist
```
- 6.32-spm-beta seems to have the exact same issue.
- Changing the dependancy to only be FirebaseAnalytics does not improve the delay time. 

Could it be related to iOS 14 and Xcode 12 (released version)?

**Comment by detectedstealth** [comment]
Also I just noticed when I don't even have an import for Firebase or use FirebaseApp.config() anywhere I'm still getting the output.

```
2020-09-19 17:56:45.938134-0700 Make It So[10908:1843443]  - <AppMeasurement>[I-ACS031025] Analytics screen reporting is enabled. Call +[FIRAnalytics logEventWithName:FIREventScreenView parameters:] to log a screen view event. To disable automatic screen reporting, set the flag FirebaseAutomaticScreenReportingEnabled to NO (boolean) in the Info.plist
2020-09-19 17:56:46.267268-0700 Make It So[10908:1843444]  - <AppMeasurement>[I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
```
Deleting the Firebase package completely prevents the printout. My question is why would that even be running without anything set on my end?

**Comment by ryanwilson** [comment]
@detectedstealth will also take a look at reproducing the startup issues. re: Analytics logging, filed b/169046349 internally for the Analytics team to figure out what's going on there.

**Comment by morganchen12** [comment]
Can you share a time profiler trace for the `FirebaseApp.configure()` call?

**Comment by ryanwilson** [comment]
It looks like this could be an Xcode 12 regression: https://twitter.com/DanielStormApps/status/1306588081865146368

While we're still trying to reproduce, can you try the workarounds in those tweets? Particularly:

1. Quit Xcode.
2. Unplug device.
3. Delete your device support files (Library/Developer/Xcode/iOS DeviceSupport). 
4. Relaunch.
5. Reconnect.

**Comment by detectedstealth** [comment]
@raymondlam I have tried the steps you have outlined prior to creating this issue. Didn't have any affect. However I did notice there is a slow up with any Package added to the package manager and running on a physical device so this possibly could be an issue with the current Xcode builds (release and 12.2 beta), as there seems to be a lot of open bugs since Xcode 12 GM was released.

**Comment by detectedstealth** [comment]
@morganchen12 I'll have to get back to you on the profile trace I updated all my devices to iOS 14.0.1 which isn't currently supported by Xcode keep getting the "Unable to install "FIrebaseTest"" error. Waiting for Apple to release a less buggy Xcode version as even 12.2 is a mess at the moment.

**Comment by paulb777** [comment]
Marking as needs-info pending additional data.

**Comment by detectedstealth** [comment]
@paulb777 after testing with the latest Xcode 12.2 beta 3 release it seems like it was an Xcode issue as I'm not seeing the issue anymore. Closing.
