### ISSUE TITLE
Client will not connect to local emulator if running on real device through Charles proxy

### ISSUE THREAD

**Issue by Daltron** [firebase/firebase-ios-sdk#6509]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.7
  * Firebase SDK version: 6.32.2
  * Firebase Component: I think Core/Firestore?
  * Component version: 6.32.2
  * Installation method: `CocoaPods

#### Steps to reproduce:

1. In my machines hosts file, I have an entry which points to localhost:
```
127.0.0.1	localhost host.local.com
```
2. After I initialize Firestore, I have the following code to connect to the local environment
```
let settings = Firestore.firestore().settings
settings.host = "host.local.com:8090"
settings.isPersistenceEnabled = false
settings.isSSLEnabled = false
Firestore.firestore().settings = settings
Functions.functions().useFunctionsEmulator(origin: "http://host.local.com:5001")
```
3. Configure proxy settings on iPhone
4. Run the app and observe the error messages:
```
FIRFirestoreErrorDomain Code=14 "Failed to get document because the client is offline." UserInfo={NSLocalizedDescription=Failed to get document because the client is offline.
6.32.0 - [Firebase/Firestore][I-FST000001] WriteStream (12df14938) Stream error: 'Unavailable: DNS resolution failed
```

If you do the exact same thing but on the simulator, it connects and works just fine. My proxy settings are properly configured because I am able to access the firestore emulator through safari just fine on my iPhone at `host.local.com:4000`.

**Comment by wilhuff** [comment]
Firestore uses gRPC to connect to its backend and gRPC does not consult on-device proxy configuration. You can configure a proxy by [setting environment variables](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md). You can do so in the Arguments tab of the Scheme settings or in code by calling `setenv(3)` (available in the `Darwin` module from Swift).

Functions is based (indirectly) on `NSURLSession` so it should honor the host proxy configuration.

**Comment by Daltron** [comment]
@wilhuff thanks for the response. What should be the value of the `grpc_proxy` environment variable set? I currently have it set to the ip address I want to proxy thorough (my computer) + the port (8888) and am still getting a
```
Stream error: 'Unavailable: DNS resolution failed
```
while Charles proxy is running using
```
grpc_proxy = 192.168.1.46:8888 
```

Thanks!

**Comment by Daltron** [comment]
When I set it like so in code:
```
setenv("grpc_proxy", "192.168.1.46:8090", 1)
```
I receive this error:
```
[Firebase/Firestore][I-FST000001] WriteStream (12bd0b108) Stream error: 'Unavailable: failed to connect to all addresses'
```

**Comment by wilhuff** [comment]
The value should be a URI, so something like `http://192.168.1.46:8888`.

You can observe what the library is doing by adjusting tracing (also with environment variables, documented on that same page). Set `GRPC_VERBOSITY` to `DEBUG` and then `GRPC_TRACE` to `http,http1` or possibly others.

**Comment by Daltron** [comment]
@wilhuff I have updated the value to now be

```
http://192.168.1.58:8888
```

and am now seeing this being printed after adding the following variables:

```
Error Domain=FIRFirestoreErrorDomain Code=14 "Failed to get document because the client is offline." UserInfo={NSLocalizedDescription=Failed to get document because the client is offline.}
2020-09-22 12:37:08.016342-0500 Channels Local[8286:10890004] 6.32.0 - [Firebase/Firestore][I-FST000001] WriteStream (113e24928) Stream error: 'Unavailable: failed to connect to all addresses'
I0922 12:37:08.079649000 6182678528 subchannel.cc:967]                 Failed to connect to channel, retrying
I0922 12:37:10.394689000 6170914816 http_connect_handshaker.cc:328]    Connecting to server 192.168.1.58:8090 via HTTP proxy ipv4:192.168.1.58:8888
I0922 12:37:10.408208000 6170914816 subchannel.cc:1003]                Connect failed: {"created":"@1600796230.407693000","description":"HTTP proxy returned response code 503","file":"/ios-mc/Pods/gRPC-Core/src/core/ext/filters/client_channel/http_connect_handshaker.cc","file_line":247}
```

Everything else (Safari, etc..) works perfect through the phone while being proxied

**Comment by Daltron** [comment]
![Screen Shot 2020-09-22 at 12 52 15 PM](https://user-images.githubusercontent.com/9689335/93918785-76854a80-fcd2-11ea-8378-599341b81522.png)

**Comment by Daltron** [comment]
I was able to get this to finally work with not using a proxy by changing my firebase.json config to include the following:

```
"emulators": {
    "firestore": {
     "host": "0.0.0.0",
     "port": 8090
    },
    "functions": {
     "host": "0.0.0.0",
     "port": 5001
    }
   },
```

Thanks again for all your help!
