### ISSUE TITLE
iOS 14 Simulator Debug Build Fails

### ISSUE THREAD

**Issue by 1oo7** [firebase/firebase-ios-sdk#6519]
* Xcode version: 12.0
  * Firebase SDK version: 6.32.0
  * Firebase Component: Crashlytics
  * Component version: Not sure, whatever comes with 6.32.0
  * Installation method: `Carthage`

### [REQUIRED] Step 2: Describe the problem

 ld: in /private/tmp/build/jenkins-mobile-pr-ios-Xcode12_TestBranch-11/ios/Carthage/Build/iOS/FirebaseCrashlytics.framework/FirebaseCrashlytics(FIRCLSApplicationIdentifierModel.o), building for iOS Simulator, but linking in object file built for iOS, file '/private/tmp/build/jenkins-mobile-pr-ios-Xcode12_TestBranch/ios/Carthage/Build/iOS/FirebaseCrashlytics.framework/FirebaseCrashlytics' for architecture arm64

#### Steps to reproduce:

set -o pipefail && xcodebuild -workspace REDACTED_iOS.xcworkspace -scheme REDACTED -configuration Debug -derivedDataPath /private/tmp/build/jenkins-mobile-pr-ios-Xcode12_TestBranch-11/ios/fastlane/output/derivedData -sdk 'iphonesimulator' -destination 'generic/platform=iOS Simulator' build | tee /private/tmp/build/jenkins-mobile-pr-ios-Xcode12_TestBranch-11/ios/fastlane/output/logs/REDACTED.log | xcpretty

#### Relevant Code:

```
import FirebaseCrashlytics
```

**Comment by paulb777** [comment]
@1oo7 Thanks for the report. Please see if any of the answers at https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios help.
