### ISSUE TITLE
Fatal Exception: NSInvalidArgumentException 

### ISSUE THREAD

**Issue by Rajeev09** [firebase/firebase-ios-sdk#6522]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

-  Xcode version: 12.0
- Firebase SDK version: 6.32.0
- Firebase 6.32.2
- FirebaseABTesting 4.2.0
- FirebaseAnalytics 6.8.2
- FirebaseCore 6.10.2
- FirebaseCoreDiagnostics 1.6.0
- FirebaseDatabase 6.6.0
- FirebaseInstallations 1.7.0
- FirebaseInstanceID 4.6.0
- FirebaseMessaging 4.6.2
- FirebasePerformance 3.3.0
- FirebaseRemoteConfig 4.9.0
- Installation method: CocoaPods

#### Steps to reproduce:

- (void)fetchWithExpirationDuration:(NSTimeInterval)expirationDuration
                  completionHandler:(void (^_Nullable)(FIRRemoteConfigFetchStatus status,
                                                       NSError *_Nullable error))completionHandler;
when this function is called, app is crashing sometimes.Please find crash log below

#### Relevant Code:

Crash  *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0] 
with following stack trace

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x190f66180 __exceptionPreprocess
1  libobjc.A.dylib                0x19013e9f8 objc_exception_throw
2  CoreFoundation                 0x190edfbec _CFArgv
3  CoreFoundation                 0x190e67898 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]
4  CoreFoundation                 0x190e58474 +[NSDictionary dictionaryWithObjects:forKeys:count:]
5  Connect                        0x10198feb0 __60-[RCNConfigFetch fetchWithUserProperties:completionHandler:]_block_invoke_2 + 413 (RCNConfigFetch.m:413)
6  libdispatch.dylib              0x1909a3a38 _dispatch_call_block_and_release
7  libdispatch.dylib              0x1909a47d4 _dispatch_client_callout
8  libdispatch.dylib              0x19094d324 _dispatch_lane_serial_drain$VARIANT$mp
9  libdispatch.dylib              0x19094de40 _dispatch_lane_invoke$VARIANT$mp
10 libdispatch.dylib              0x1909564ac _dispatch_workloop_worker_thread
11 libsystem_pthread.dylib        0x190b85114 _pthread_wqthread
12 libsystem_pthread.dylib        0x190b87cd4 start_wqthread

**Comment by paulb777** [comment]
Please make sure you're using a recent Firebase version and fill out the issue template with installation method and versions. Similar issues have been fixed in recent releases.

**Comment by Rajeev09** [comment]
Filled the template, Please help us with reason as to why it is crashing and how to fix this

**Comment by paulb777** [comment]
Thanks for the report. Are you able to reproduce locally? Does removing FirebasePerformance make a difference?

**Comment by Rajeev09** [comment]
not able to reproduce locally, this is actually a production crash
