### ISSUE TITLE
The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.

### ISSUE THREAD

**Issue by smamczak** [firebase/firebase-ios-sdk#6533]
I get a lot of warnings when building my app

```
Build target GoogleSignIn of project Pods with configuration Debug
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'GoogleSignIn' from project 'Pods')

Build target FirebaseAnalyticsInterop of project Pods with configuration Debug
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseAnalyticsInterop' from project 'Pods')

Build target InjectableLoggers with configuration Debug
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'InjectableLoggers' from project 'InjectableLoggers')

Build target Firebase of project Pods with configuration Debug
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'Firebase' from project 'Pods')

Build target FacebookLogin with configuration Debug
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'FacebookLogin' from project 'Facebook')

Build target FirebaseCoreDiagnosticsInterop of project Pods with configuration Debug
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseCoreDiagnosticsInterop' from project 'Pods')
```

  * Xcode version: 12.0
  * Firebase SDK version: 6.23.0
  * Firebase Component: Firebase/Crashlytics
  * Component version: 6.23.0
  * Installation method: CocoaPods

**Comment by paulb777** [comment]
@smamczak Thanks for the report. 

This is an Xcode 12 issue for libraries that support an earlier version than is supported by that Xcode version.  We'll address for Firebase in the next breaking change release coming in the next few months. See #6517.

In the meantime, a workaround is a Podfile post_install script. See details at https://github.com/CocoaPods/CocoaPods/issues/9884#issuecomment-696228403

The issue has been filed to Apple at FB8683743.

**Comment by praba269** [comment]
Me also having the same warning, kindly refer this
https://www.jessesquires.com/blog/2020/07/20/xcode-12-drops-support-for-ios-8-fix-for-cocoapods/

**Comment by tkirby** [comment]
+1

This is an error for me. Won't build

**Comment by moshTech** [comment]
I solve it with this code, thanks! Add it at the end of the PodFile

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end

**Comment by dappfuse** [comment]
This solved it for me:

https://github.com/flutter/flutter/issues/58200
