### ISSUE TITLE
 Firestore terminate() not invoking callback and crashes on signout

### ISSUE THREAD

**Issue by mobmad** [firebase/firebase-ios-sdk#6534]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0 (12A7209)
  * Firebase SDK version: 6.33
  * Firebase Component: Firestore
  * Component version: 1.18
  * Installation method: CocoaPods

#### Steps to reproduce:
```
Auth.auth().addStateDidChangeListener { [unowned self] (auth, user) in
    if let user = user {
        print("State changed -> logged in")
        
        // ...
        
    } else {
        print("State changed -> not logged in")
        
        let db = Firestore.firestore()
        db.terminate(completion: { error in
            if let error = error {
                print("Terminate error \(error)")
            }
            
            Firestore.firestore().clearPersistence(completion: { pError in
                if let pError = pError {
                    print("Clear error \(pError)")
                } else {
                    print("Cleared database")
                }
            })
        })
    }
}
```

### Works in Firebase 6.25 / Firestore 1.14:
* On launch and not logged in it prints "State changed -> not logged in" and then "Cleared database"
* On sign-out it also prints "State changed -> not logged in" and then "Cleared database"

### Breaks from Firebase 6.26 / Firestore 1.15 and newer:
* On launch and not logged in it prints "State changed -> not logged in". **The db.terminate completion handler is never called.**
* On signout it prints "State changed -> not logged in" and then **crashes with**:

```
2020-09-23 13:07:39.247786+0200 DemoApp[30070:7682127] *** Assertion failure in void firebase::firestore::util::AsyncQueue::VerifySequentialOrder() const(), .../demoapp/Pods/FirebaseFirestore/Firestore/core/src/util/async_queue.cc:156
2020-09-23 13:07:39.249140+0200 DemoApp[30070:7682127] *** Assertion failure in void firebase::firestore::util::AsyncQueue::VerifySequentialOrder() const(), .../demoapp/Pods/FirebaseFirestore/Firestore/core/src/util/async_queue.cc:156
2020-09-23 13:07:39.357718+0200 DemoApp[30070:7682127] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'FIRESTORE INTERNAL ASSERTION FAILED: Enqueue methods cannot be called when we are already running on target executor (this queue's executor: 'com.google.firebase.firestore', current executor: 'com.google.firebase.firestore') (expected !is_operation_in_progress_ || !executor_->IsCurrentExecutor())'

...

libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'FIRESTORE INTERNAL ASSERTION FAILED: Enqueue methods cannot be called when we are already running on target executor (this queue's executor: 'com.google.firebase.firestore', current executor: 'com.google.firebase.firestore') (expected !is_operation_in_progress_ || !executor_->IsCurrentExecutor())'
terminating with uncaught exception of type NSException
```

A related issue is: https://github.com/firebase/firebase-ios-sdk/issues/6143

Workaround: downgrade to 6.25 / 1.14.

**Comment by var-const** [comment]
Thank you for reporting this. I will try to reproduce and will post back once I have the results.

**Comment by var-const** [comment]
Unfortunately, I cannot reproduce the issue. What I have tried is to add the code snippet you posted to the [quickstart App]() and try starting the app/log out from it. I have tried both the latest version (`6.33.0`/`1.18.0`) and the earliest failing version you reported (`6.26.0`/`1.15.0`). In both cases, I get the `"Cleared database"` message printed out.

@mobmad It would be super helpful if you could create a small app that reproduces the issue and post it somewhere.

**Comment by mobmad** [comment]
Thanks for investigating this. I tried to reproduce this in a new app, but couldn't reproduce it. However, the problem is consistent in my primary app, so I guess there is something more complex that triggers this issue. I will investigate further and let you know. Due to limited time this week I won't be able to provide an update before next week.
