### ISSUE TITLE
Analytics not sending correct data about devices

### ISSUE THREAD

**Issue by Kaspik** [firebase/firebase-ios-sdk#6538]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12
  * Firebase SDK version: 6.33.0
  * Firebase Component: Analytics
  * Component version: 6.33.0
  * Installation method: `CocoaPods`

### [REQUIRED] Step 2: Describe the problem

When looking at Technology of the app in Google Analytics (connected to Firebase Analytics), the data about devices and platforms are not correct. Most of the device types are not set, *all* of screen sizes are not available, and some other data are not available too.

Is there some setup or configuration that needs to be done to get these?
Docs are not saying anything as well as this repo when trying to find relevant code.

![Screen Shot 2020-09-23 at 18 27 55](https://user-images.githubusercontent.com/7204168/94041707-e676fc00-fdca-11ea-95d7-97b97f84601e.png)

**Comment by Kaspik** [comment]
For reference point, here are data from our own logging we added to compare how wrong Analytics are. Seems like an issue?

![Screen Shot 2020-09-23 at 18 36 37](https://user-images.githubusercontent.com/7204168/94043544-60a88000-fdcd-11ea-861e-1f3c639f94a8.png)

**Comment by paulb777** [comment]
Closing for staleness. Please comment or open a new issue to reopen.

**Comment by Kaspik** [comment]
Seems like it's working recently.
