### ISSUE TITLE
Work with Firebase dependencies to prevent Xcode 12 min iOS version warnings

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#6549]
Get Firebase warning clean with everything installed in CocoaPods and SPM

**Comment by paulb777** [comment]
Sent https://github.com/google/gtm-session-fetcher/pull/206

**Comment by paulb777** [comment]
https://github.com/google/promises/pull/162

**Comment by paulb777** [comment]
The gRPC team has an outstanding PR to go to iOS 9 - https://github.com/grpc/grpc/pull/24247/files#diff-f89e5380663ea03001797de46a6ec086

**Comment by paulb777** [comment]
The Promises fix is in 1.2.11

**Comment by paulb777** [comment]
nanopb podspec pr at https://github.com/google/nanopb-podspec/pull/16

**Comment by paulb777** [comment]
I'm not sure the best strategy for managing leveldb. If we bump its podspec version to bump the minimum iOS version, it would be a breaking change for existing projects supporting iOS 8 - and our dependencies allow minor version updates.

Should we go to a metaVersioning scheme like we do for [nanopb](https://github.com/google/nanopb-podspec)? 

@wilhuff @schmidt-sebastian

**Comment by wilhuff** [comment]
Are we certain there's no way we can get SPM to suppress this warning for dependencies?

The reality here is that leveldb has made no changes that would drop support for iOS 8. Artificially pushing that project to bump its minimum just because of what seems like an Xcode bug doesn't seem awesome.

**Comment by paulb777** [comment]
This is only a CocoaPods issue.  SPM allows the outer specification to propagate down if unspecified. I've filed an Xcode issue. More details in https://forums.swift.org/t/minimum-ios-version-xcode-12-and-build-warnings/40224/4.

It could be fine to give that more time and to go with a [CocoaPods workaround](https://github.com/CocoaPods/CocoaPods/issues/9884#issuecomment-699828314) for now.

**Comment by paulb777** [comment]
Closing here since the dependencies have either been addressed, have an accepted PR pending a future release, a plan, or deferral like leveldb.

This is as far as we'll get for the Firebase 7 milestone.
