### ISSUE TITLE
error: module 'Firebase' was created for incompatible target arm64-apple-ios8.0

### ISSUE THREAD

**Issue by psaezcube** [firebase/firebase-ios-sdk#6551]
* Xcode version: 12
  * Firebase SDK version: Last
  * Firebase Component: Core, Messaging, InAppMessaging
  * Component version: Last
  * Installation method: CocoaPods 1.9.3

#### Steps to reproduce:

When I try to generate an .app bundle (representing a iOS Simulator build of your app) for uploading to Appetize ( https://support.appetize.io/help/how-to-upload-an-app-to-appetize-io ), using Xcode, it works perfectly if i press the Build & Run button and open the app in a Simulator, but when I try to generate it with command line xcodebuild command I'm getting this crash:

_error: module 'Firebase' was created for incompatible target arm64-apple-ios8.0 (the same for the other modules)_

This is the command for getting the crash:

_xcodebuild -sdk iphonesimulator -workspace Project.xcworkspace -scheme Appetize -configuration Debug_

This worked perfectly before updating to XCode 12 and cocoapods 1.9.3, when I was using XCode 11.X and cocoapods 1.9.1

PD: I tryed with the "warning workaround" (described here: https://github.com/CocoaPods/CocoaPods/issues/9884#issuecomment-696228403 )but the problem is exactly the same but writting arm64-apple-ios9.0 instead of arm64-apple-ios8.0

**Comment by morganchen12** [comment]
Are you able to install the resulting app bundle in the iOS Simulator?

**Comment by paulb777** [comment]
Based on https://stackoverflow.com/questions/64036180/error-module-was-created-for-incompatible-target-arm64-apple-ios8-0, this might not have anything to do with Firebase.  Perhaps, it should be reported to Appetize? Or perhaps an additional xcodebuild option is required related to the additional arm64 simulator target supported by Xcode 12?

**Comment by psaezcube** [comment]
> Based on https://stackoverflow.com/questions/64036180/error-module-was-created-for-incompatible-target-arm64-apple-ios8-0, this might not have anything to do with Firebase. Perhaps, it should be reported to Appetize? Or perhaps an additional xcodebuild option is required related to the additional arm64 simulator target supported by Xcode 12?

Hi, thanks.

Do you have more info about that additional arm64 simulator target supported by Xcode 12? can't find it

**Comment by psaezcube** [comment]
Solved using this: https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios/63955114#63955114
