### ISSUE TITLE
Delegate not called when try to signin Google account after prompt is displayed and the user lock screen

### ISSUE THREAD

**Issue by lorrainNicolas** [firebase/firebase-ios-sdk#6565]
### [REQUIRED] Step 1: Describe your environment

  * Xcode Version 11.7
  * Firebase SDK version: 6.31.0
  * Firebase Component: GoogleSignIn
  * Component version: 5.0.2
  * Installation method: Zip file

#### Steps to reproduce:
When we trigger the signin process, apple will show this box.
If the user lock his device and come back to the app while this box is shown, the box will be dismissed and no delegate method is being called.
This is annoying for us as we display a loading state as soon as the signin process begin.  Without a callback from the delegate, we cannot know that we need to remove this loading state.

![120143049_669950006975651_4588835420607103003_n](https://user-images.githubusercontent.com/53340213/94263255-0cb8ab00-ff35-11ea-8989-3a31e154b75a.jpg)

#### Relevant Code:

```
class GoogleAdapter: NSObject {
    static private let clientId = "clientId"
    private let signIn: GIDSignIn
    
    init(signIn: GIDSignIn = .sharedInstance()) {
        signIn.clientID = Self.clientId
        self.signIn = signIn
    }
    
    func getAuthCredentials(from viewController: UIViewController,
                            completion callback: @escaping (Result<GoogleCredentials, Error>) -> Void) {
        signIn.shouldFetchBasicProfile = true
        signIn.delegate = self
        signIn.presentingViewController = viewController
        signIn.signIn()
    }
}

extension GoogleAdapter: GIDSignInDelegate {
    func sign(_ signIn: GIDSignIn!, didSignInFor user: GIDGoogleUser!, withError error: Swift.Error!) {
        print("didSignIn") 
        //not called
    }
}

```

**Comment by morganchen12** [comment]
Hey @lorrainNicolas, can you confirm `signIn:didDisconnectWithUser:error:` also doesn't get called?

**Comment by lorrainNicolas** [comment]
Hello @morganchen12 
I have just added this to my code 

```
    func sign(_ signIn: GIDSignIn!, didDisconnectWith user: GIDGoogleUser!, withError error: Swift.Error!){
         print("didDisconnect")
    }
```

when I implement GIDSignInDelegate and it's look like is not call as well when I lock my screen

**Comment by morganchen12** [comment]
Thanks. We currently don't know of any callbacks provided by Apple's frameworks to handle this scenario, so this bug may have to wait for a fix from Apple.

Googler-only bug number: b/169437299

**Comment by jc-paris** [comment]
> Thanks. We currently don't know of any callbacks provided by Apple's frameworks to handle this scenario, so this bug may have to wait for a fix from Apple.
> 
> Googler-only bug number: b/169437299

It seems that Facebook Login can make it work though.. What do you advise us to do to handle this situation while waiting for a solution on apple side ?
We can't attempt to listen for didBecomeActive notification on our side as we don't know if the webview has been displayed yet or not.

**Comment by morganchen12** [comment]
Facebook's SDK tracks some additional state to try to determine if the login has been implicitly cancelled when the application becomes active. I haven't dug too much into their implementation, but you can take a closer look [here](https://github.com/facebook/facebook-ios-sdk/blob/5391abc1041a274b547d2ac783d377de64fa91c1/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginManager.m#L120).

**Comment by 3amoura** [comment]
@lorrainNicolas Do you use a custom domain built on google (ie, sample@example.com) where example is a google domain, or you use a google email?

**Comment by jc-paris** [comment]
@3amoura this issue is even before selecting a google account. It's when iOS ask permission to use Google Sign in.
If while this alert is shown by the OS you lock the device and come back, the GoogleSignIn delegates in not called..

**Comment by dturnq** [comment]
Any updates on this? I am having this very frustrating problem as well.

**Comment by paulb777** [comment]
GoogleSignIn 6.0.0 is now released and open source. Please try with 6.0.0 and follow up at https://github.com/google/GoogleSignIn-iOS/issues with any outstanding issues.
