### ISSUE TITLE
Error: Attempt to call prepareVerifyAssertionRequest: on a FIREmailPasswordAuthCredential.

### ISSUE THREAD

**Issue by adrianstrahan** [firebase/firebase-ios-sdk#6566]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0
  * Firebase SDK version: 6.28.1
  * Firebase Component: Auth (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 6.7.0
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem
Getting following error:
Attempt to call prepareVerifyAssertionRequest: on a FIREmailPasswordAuthCredential.

#### Steps to reproduce:

Use following Swift code:
```
if let currentUser = Auth.auth().currentUser {
    let credential = EmailAuthProvider.credential(withEmail: email, password: password)
    currentUser.link(with: credential, completion: handleSignUpResult)
}
```

What happened? How can we make the problem occur?
User is signed in anonymously then tries to sign up with their email and password. If they were not signed in anonymously I would call `Auth.auth().createUser(withEmail: email, password: password, completion: handleSignUpResult)` but I would like to link the accounts in this instance.

This looks very similar to https://github.com/firebase/firebase-ios-sdk/issues/2099

![Image 25-09-2020 at 17 27](https://user-images.githubusercontent.com/6716131/94292772-47324000-ff55-11ea-8e19-91e6ffe737e6.jpg)

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
if let currentUser = Auth.auth().currentUser {
    let credential = EmailAuthProvider.credential(withEmail: email, password: password)
    currentUser.link(with: credential, completion: handleSignUpResult)
}
```

**Comment by samhorlbeck** [comment]
Thanks for reaching out and detailing this issue. I've filed a bug internally to track this (b/169438804).

In the mean time, it looks like the issue you linked (https://github.com/firebase/firebase-ios-sdk/issues/2099) was due to a Cocoa pods configuration issue. Have you ruled that out as an issue in your case?
