### ISSUE TITLE
Could not find or use auto-linked framework 'FBLPromises'

### ISSUE THREAD

**Issue by abdelmajidrajad** [firebase/firebase-ios-sdk#6573]
[###](url
![Screenshot 2020-09-26 at 09 11 30](https://user-images.githubusercontent.com/12987448/94336200-2ad7e700-ffd9-11ea-9d84-430247b9bf6f.png)
) 

  * Xcode version: 11.7
  * Firebase SDK version:6.33.0
  * Firebase Component:  Firestore
  * Component version: 6.33.0
  * Installation method:  Manual

As photo show. after linking Firestore to my framework it can't compile even when all frameworks has the same target. 

to reproduce, create a framework drag frameworks from analytics and firestore .

**Comment by paulb777** [comment]
It looks like the C++ standard library is missing.

**Comment by abdelmajidrajad** [comment]
Right ! Thanks for quick response .
