### ISSUE TITLE
> Great find @pmfon - now to figure out why this will fail in App Store signed apps. Going to do some research

### ISSUE THREAD

**Issue by DarkYuanJs** [firebase/firebase-ios-sdk#6577]
> Great find @pmfon - now to figure out why this will fail in App Store signed apps. Going to do some research

Here’s what we found so far
- the difference seems to be between debug and release versions (not necessarily signed, since it can be reproduced in the simulator)
- disabled striping in the release build and the symbol still can’t be found though it’s in the binary if you check with ‘nm’
- only changed the main project settings, the Pods configs were not touched
- calling dlsym from the AppDelegate has the same effect
- the legacy SDK (integrated with CocoaPods), with the same project configuration, works

_Originally posted by @pmfon in https://github.com/firebase/firebase-ios-sdk/issues/5020#issuecomment-614601006_

**Comment by DarkYuanJs** [comment]
I also ran into the same problem，my firebase version is up to date,I am desperate！！

**Comment by ryanwilson** [comment]
Hi @DarkYuanJs, sorry you're having trouble. Can you please fill out the template? It's not immediately clear what the exact issue is, and we won't be able to help without more context. Also note that the thread you had linked mentions there's new logging in the SDK so logs would help, as well as a proposed fix here: https://github.com/firebase/firebase-ios-sdk/issues/5020#issuecomment-617914372 and second comment here: https://github.com/firebase/firebase-ios-sdk/issues/5020#issuecomment-619064697

**Comment by DarkYuanJs** [comment]
Hi，First of all thank you for receiving the reply，I have found the cause of the problem，The reason is that there are old versions of things in the Xcode settings in the old version.

**Comment by DarkYuanJs** [comment]
old fabric in xocde -> build Settings -> Linking -> Other Linker Flags has -WL,-exported_symbol,_il2cpp_* ，update to new version is not delete this，So I hope that the official will fix this in the next version to prevent other developers from having the same problem！

**Comment by paulb777** [comment]
Thanks for sharing. `pod deintegrate` might be a resolution.
