### ISSUE TITLE
watchOS SPM support

### ISSUE THREAD

**Issue by jostster** [firebase/firebase-ios-sdk#6584]
### Feature proposal

* Firebase Component: Crashlytics

Figured I would create a central place to talk about watchOS SPM support. One option is using the `platform` param for the SPM file which will allow some of the modules that support watchOS to be built for that platform.

**Comment by jostster** [comment]
https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html#target-dependency is in Swift5.3, might be helpful.

**Comment by paulb777** [comment]
Based on https://forums.swift.org/t/platform-specific-products/39186, looking for ideas about an approach to define watchOS support for some of the Firebase products without having to ifdef out all the rest for watchOS.

**Comment by jostster** [comment]
Would something like this work? https://forums.swift.org/t/package-manager-conditional-target-dependencies/31306/2?

**Comment by paulb777** [comment]
Thanks @jostster ! That approach is looking promising. I'll try to get a PR up in the next day or two ...
