### ISSUE TITLE
xcodebuild Linking error with FirebaseAnalytics breaking testing. Cocoapods

### ISSUE THREAD

**Issue by ApplebaumIan** [firebase/firebase-ios-sdk#6586]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0
  * Firebase SDK version: 6.33
  * Firebase Component: Analytics
  * Component version: 6.8.3
  * Installation method: CocoaPods 

#### Steps to reproduce:

You can clone my project here https://github.com/Capstone-Projects-2020-Spring/iASL-iOS 

In the shell execute `pod install` and then 
```
xcodebuild clean test -workspace ImageClassification.xcworkspace -scheme ImageClassification -destination "platform=iOS Simulator,OS=14,name=iPhone 11"  -enableCodeCoverage YES CODE_SIGNING_ALLOWED=NO ONLY_ACTIVE_ARCH=NO  -archivePath ./build -derivedDataPath ./build | xcpretty build

```

Using xcodebuild for testing produces this error:
```
> Linking iASL

[x] ld: in /tmp/Developer/jenkins/workspace/iASL-Testing/Pods/FirebaseAnalytics/Frameworks/FIRAnalyticsConnector.framework/FIRAnalyticsConnector(FIRAnalyticsConnector_8094107d82c527bf23f93e98c9db96d1.o), building for iOS Simulator, but linking in object file built for iOS, file '/tmp/Developer/jenkins/workspace/iASL-Testing/Pods/FirebaseAnalytics/Frameworks/FIRAnalyticsConnector.framework/FIRAnalyticsConnector' for architecture arm64



[x] clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Our App is **not** a Catalyst App. I've been Googling this issue and everyone that has this happen to them are are building a Catalyst App.

#### Relevant Code:

Our build command on Jenkins:
```
xcodebuild clean test -workspace ImageClassification.xcworkspace -scheme ImageClassification -destination "platform=iOS Simulator,OS=14,name=iPhone 11"  -enableCodeCoverage YES CODE_SIGNING_ALLOWED=NO ONLY_ACTIVE_ARCH=NO  -archivePath ./build -derivedDataPath ./build | xcpretty build

```

**Comment by paulb777** [comment]
The Firebase binary packages do not yet support arm64 simulator targets, so it needs to be excluded from Xcode12 build targets.

See https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios

**Comment by paulb777** [comment]
See also https://github.com/firebase/firebase-ios-sdk/issues/6520
