### ISSUE TITLE
Xcode 12, Undefined symbols __ubsan_handle_type_mismatch_v1 for architecture x86_64

### ISSUE THREAD

**Issue by pigfly** [firebase/firebase-ios-sdk#6593]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 12.0 (12A7209)
  * Firebase SDK version: 6.33.0
  * Firebase Component: FirebaseAnalytics
  * Component version: 4.7.0
  * Installation method: `Zip file`

#### Steps to reproduce:

What happened? How can we make the problem occur?

1. The project itself compiles successfully on Xcode 11.*
2. Switched to Xcode 12 (12A7209), fails to compile on simulator with the following
3. Followed the readme instructions on the [firebase zip file](https://firebase.google.com/download/ios), the issue still exists

```
ld: warning: Could not find or use auto-linked framework 'FBLPromises'
Undefined symbols for architecture x86_64:
  "___ubsan_handle_type_mismatch_v1", referenced from:
      -[BNDProtocolProxyBase setForwardTo:] in BNDProtocolProxyBase.o
      -[BNDMethodSignature getArgumentTypeAtIndex:] in BNDProtocolProxyBase.o
      -[BNDMethodSignature getReturnArgumentType] in BNDProtocolProxyBase.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

**Comment by paulb777** [comment]
These symbols are not from Firebase. A Google search shows http://cocoadocs.org/docsets/Bond/6.5.0/. It looks something is inconsistently build with the Xcode Undefined Behavior Sanitizer.

Closing since it does not seem to be a Firebase issue, but can reopen if there's evidence otherwise.
