### ISSUE TITLE
KSCrash conflict

### ISSUE THREAD

**Issue by bcondeskylinedynamics** [firebase/firebase-ios-sdk#6596]
Hi,

im new to posting issues but i have problem with  Firebase/Storage and Firebase/Firestore paired with `Ably v1.2.1` in pods, im getting error 'absl/base/internal/inline_variable.h' file not found in KSCrashAblyFork

Any idea how to fix this? Thank you

**Comment by ryanwilson** [comment]
Hi @bcondeskylinedynamics - if the error is coming from an `Ably` framework, please file an issue with that repo. They'll be able to manage and have knowledge about what's broken there. Based on the error  it seems like there could be a mismatch of `absl` versions but without knowing their product it's hard to tell. 

If you start getting errors from a Firebase framework itself, please re-open an issue and fill out the issue template so we can better track down the issue you're seeing and have a better chance at fixing it.

Thanks!
