### ISSUE TITLE
FR: Firestore support for macOS command line tool applications

### ISSUE THREAD

**Issue by botfantasy** [firebase/firebase-ios-sdk#6609]
### Feature proposal

* Firebase Component: Firestore

Swift programmers have no official Firestore support for non-mobile environments. Therefore, I'm requesting official Firestore support for at least macOS command line tool applications, the bare minimum of macOS applications.

**Comment by ryanwilson** [comment]
Hi @botfantasy - thanks for the request.

Firestore is [available via Swift Package Manager](https://github.com/firebase/firebase-ios-sdk/blob/2d7778cdfb43a9fe7e042f5beea89e8056fb74e7/Package.swift#L366), and also [supports macOS](https://github.com/firebase/firebase-ios-sdk/blob/2d7778cdfb43a9fe7e042f5beea89e8056fb74e7/Package.swift#L29). Is this usable for you, or were you looking at some other feature?

**Comment by botfantasy** [comment]
@ryanwilson thanks for the quick reply. The Swift Package Manager route was unsuccessful (for me) in getting Firebase to work with a macOS command line tool application. I was able to get it all the way past configuration and into a working runtime environment but could not make any connection with the server through Firestore. At first, I received network connection errors but mostly got nothing at all. Is this an issue worth posting? I don't want to pile on because my thinking is that it's in beta and it will get there when it gets there.

**Comment by ryanwilson** [comment]
@botfantasy definitely worth posting! Part of being "beta" means we need feedback from developers like yourself in order to fix and find these issues, so anything you can provide is extremely helpful! 😄 

Thanks!
