### ISSUE TITLE
Sporadic travis failures in FirebaseCore unit tests

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#661]
FIROptionsTest
  testAnalyticsOptions_combinatorial, ((options.analyticsOptionsDictionary) equal to (expectedAnalyticsOptions)) failed: ("{
  /Users/travis/build/firebase/firebase-ios-sdk/Example/Core/Tests/FIROptionsTest.m:430
  ```
                [expectedAnalyticsOptions addEntriesFromDictionary:mainDictionary];
                XCTAssertEqualObjects(options.analyticsOptionsDictionary, expectedAnalyticsOptions);
  ```
	 Executed 63 tests, with 1 failure (0 unexpected) in 0.985 (1.118) seconds

**Comment by ryanwilson** [comment]
This should be fixed now with #664!
