### ISSUE TITLE
Remote Config Crash: this class is not key value coding-compliant

### ISSUE THREAD

**Issue by julien-tamade** [firebase/firebase-ios-sdk#6625]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0.1
  * Firebase SDK version: 6.33
  * Firebase Component: Remote Config
  * Component version: 6.33
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem
I'm following the sdk setup instructions. calling
```
remoteConfig = RemoteConfig.remoteConfig()
remoteConfig.setDefaults(["test1" : NSString("test")])
let settings = RemoteConfigSettings()
settings.minimumFetchInterval = 0
remoteConfig.configSettings = settings
```
on viewDidLoad
and 
```
remoteConfig.fetchAndActivate { status, error in
guard error == nil else { print("Remote config fetch error..."); return }
print("Remote config successfully fetched & activated!")
DispatchQueue.main.async {
     print("remote config value: \(self.remoteConfig.value(forKey: "test1"))")
}
```
At viewDidAppear

But it crashes at the print line, saying **this class is not key value coding-compliant for the key test1.**
I've tried setting the defaults using a .plist too and it doesn't work, as well as trying in an empty project.

#### Steps to reproduce:

Create new Xcode project. Add FirebaseApp.Configure() in app delegate, add a var remoteConfig: RemoteConfig!  to the view controller. Call the code above.

#### Relevant Code:
Full View Controller:
```
import UIKit
import Firebase

class ViewController: UIViewController {
    
    var remoteConfig: RemoteConfig!

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        setupRemoteConfig()
        
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        fetchAndActivateRemoteConfig()
    }
    
    private func setupRemoteConfig() {
        remoteConfig = RemoteConfig.remoteConfig()
        remoteConfig.setDefaults(["test1" : NSString("test")])
        let settings = RemoteConfigSettings()
        settings.minimumFetchInterval = 0
        remoteConfig.configSettings = settings
    }
    
    private func fetchAndActivateRemoteConfig() {
      remoteConfig.fetchAndActivate { status, error in
        guard error == nil else { print("Remote config fetch error..."); return }
        print("Remote config successfully fetched & activated!")
        DispatchQueue.main.async {
            print("remote config value: \(self.remoteConfig.value(forKey: "test1"))")
            
        }
      }
    }
}


```

**Comment by morganchen12** [comment]
You should be calling [`configValueForKey`](https://cs.opensource.google/firebase-sdk/firebase-ios-sdk/+/master:FirebaseRemoteConfig/Sources/Public/FirebaseRemoteConfig/FIRRemoteConfig.h;l=270?q=FIRRemoteConfig.h), not `valueForKey`. The latter is a call used for KVO in Objective-C, which is why you're seeing this crash message.
