### ISSUE TITLE
[6.33-spm-beta] The repository could not be found. Make sure a valid repository exists at the specified location and try again.

### ISSUE THREAD

**Issue by zhihuitang** [firebase/firebase-ios-sdk#6631]
### Step 0: Are you in the right place?
YES

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 12.0.1
  * Firebase SDK version: 6.33-spm-beta
  * Firebase Component: Analytics
  * Component version:  6.31-spm-beta or 6.33-spm-beta
  * Installation method: `Swift Package Manager`

#### Steps to reproduce:

when I tried to add SPM: `https://github.com/firebase/firebase-ios-sdk` + `6.31-spm-beta`, it showed:
```
The repository could not be found. Make sure a valid repository exists at the specified location and try again.
```
The same error for the `6.33-spm-beta`
#### Relevant Code:
![image](https://user-images.githubusercontent.com/5066926/94832122-cd46fe80-040d-11eb-9cdb-cd1fe0b4b065.png)

**Comment by paulb777** [comment]
@zhihuitang This sounds strange and doesn't seem to be a problem for others. Does the issue continue? Are you able to see the GitHub repository and branch outside of SwiftPM?

**Comment by zhihuitang** [comment]
thanks @paulb777. yes it still happens on my MacMini, but doesn't happen my Macbook. seems it is my MacMini issue. I will close it. thank you.
