### ISSUE TITLE
Adding Firebase SPM creates IPA processing error when exporting an enterprise IPA

### ISSUE THREAD

**Issue by chrisvanbuskirk** [firebase/firebase-ios-sdk#6632]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0
  * Firebase SDK version: 6.31
  * Firebase Component: analytics, crashlytics
  * Component version: _____
  * Installation method: Swift Package Manager

### [REQUIRED] Step 2: Describe the problem

When creating a Enterprise IPA, a processing error occurs.  Removing firebase from SPM solves the problem.

#### Steps to reproduce:

Add the SPM version to Xcode project.  
Archive
Export for Enterprise IPA

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

IPA Processing Error

<img width="808" alt="Screen Shot 2020-09-22 at 1 30 38 PM" src="https://user-images.githubusercontent.com/3638007/94831693-415fb300-03ca-11eb-80b5-1c7db37057ad.png">

**Comment by morganchen12** [comment]
Can you share the logs from the IPA processing so we can see the error message?

**Comment by paulb777** [comment]
Might be related to #6472

**Comment by chrisvanbuskirk** [comment]
@paulb777 and @morganchen12 For some reason this is solved now.  It was happening last week, and I added the SPM again and created the IPA without incident.  It was happening with a few of our developers last week.  We have no idea what may have changed.  I'm closing this for now.
