### ISSUE TITLE
Provide a compatible version of FirebaseUI for Firebase 7

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#6646]
And reenable the disabled Firestore, Database, and Functions quickstart tests disabled in #6634

**Comment by morganchen12** [comment]
https://github.com/firebase/FirebaseUI-iOS/pull/887

**Comment by morganchen12** [comment]
quickstarts updated in https://github.com/firebase/quickstart-ios/pull/1065
