### ISSUE TITLE
Undefined symbols after installing through SPM

### ISSUE THREAD

**Issue by jeremangnr** [firebase/firebase-ios-sdk#6650]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0.1
  * Firebase SDK version: 6.33
  * Firebase Component: Analytics, Crashlytics
  * Component version: Not sure where is this?
  * Installation method: Swift Package Manager

#### Steps to reproduce:

After installing through SPM, the build keeps failing due to missing symbols from **libz** and **libc++** but it turns out it doesn't work even if you add those. It seems you need to use the latest ones:

Thought this might be of use to anyone

<img width="1283" alt="success" src="https://user-images.githubusercontent.com/1508415/94966127-19a84200-04d3-11eb-84f1-b17c7b791e74.png">
<img width="1374" alt="fail" src="https://user-images.githubusercontent.com/1508415/94966138-22007d00-04d3-11eb-8cd8-6cbbacec58c3.png">

**Comment by morganchen12** [comment]
Do the errors go away if you add `-lc++` to your build target's `Other Link Flags`?

**Comment by jeremangnr** [comment]
Hi @morganchen12 ! No, that didn't work for me. This was the only thing that did the trick

**Comment by paulb777** [comment]
@jeremangnr Thanks for sharing! I'm going to close since there's nothing actionable for us without a reproducible example.
