### ISSUE TITLE
Conflicts between Firebase/Crashlytics and Google/Analytics

### ISSUE THREAD

**Issue by rferbesa** [firebase/firebase-ios-sdk#6666]
**Step 1: Describe your environment**

  * Xcode version: 11.6
  * Firebase SDK version: 6.33.0
  * Firebase Component: Crashlytics
  * Component version: 6.33.0
  * Installation method: `CocoaPods

**Step 2: Describe the problem**

I'm unable to upgrade Crashlytics from Fabric to Firebase due to several conflict errors.

#### Steps to reproduce:

I'm working with an app that has uses Fabric Crashlytics and Google Analytics v3. These are the pods included in its podfile:

```
pod 'PromiseKit', '~> 4.4'
pod 'CryptoSwift', '~> 0.9.0'
pod 'Kingfisher', '~> 4.7.0'
pod 'KeychainAccess', '~> 3.1.1'
pod 'Google/Analytics', '~> 3.1.0'
pod 'Cosmos', '~> 15.0.0'
pod 'Alamofire', '~> 4.7.2'
pod 'FRHyperLabel', '~> 1.0.4'
pod 'RealmSwift', '~> 4.4.0'
pod 'Realm', '~> 4.4.0'
pod 'Fabric', '~> 1.9.0'
pod 'Crashlytics', '~> 3.12.0'
pod 'Bolts', '~> 1.9.0'
pod 'FBSDKCoreKit', '~> 4.36.0'
pod 'FacebookCore', '~> 0.3.3'
pod 'CleverTap-iOS-SDK', '~> 3.7.3'
pod 'Branch', '~> 0.29.3'
pod 'TPKeyboardAvoiding', '~> 1.3.2'
pod 'Firebase', '~> 3.17.0'
pod 'GoogleTagManager' , '~> 5.0.8'
```

I have to update Crahslytics from Fabric to Firebase before 15/November. I would like to change the app as less as possible, so I would like to keep using Google Analytics v3, the same versions, etc...

I've changed this:

```
pod 'Fabric', '~> 1.9.0'
pod 'Crashlytics', '~> 3.12.0'
```

to this:

`pod 'Firebase/Crashlytics'`

And run a pod update but got this error:

```
[!] CocoaPods could not find compatible versions for pod "Firebase/Crashlytics":
  In Podfile:
    Firebase/Crashlytics

None of your spec sources contain a spec satisfying the dependency: `Firebase/Crashlytics`.
```

This is due to a conflict with pod 'Firebase', '~> 3.17.0', so I removed the specific version and the podfile now looks like this:

```
pod 'Firebase/Crashlytics'
pod 'PromiseKit', '~> 4.4'
pod 'CryptoSwift', '~> 0.9.0'
pod 'Kingfisher', '~> 4.7.0'
pod 'KeychainAccess', '~> 3.1.1'
pod 'Google/Analytics', '~> 3.1.0'
pod 'Cosmos', '~> 15.0.0'
pod 'Alamofire', '~> 4.7.2'
pod 'FRHyperLabel', '~> 1.0.4'
pod 'RealmSwift', '~> 4.4.0'
pod 'Realm', '~> 4.4.0'
pod 'Bolts', '~> 1.9.0'
pod 'FBSDKCoreKit', '~> 4.36.0'
pod 'FacebookCore', '~> 0.3.3'
pod 'CleverTap-iOS-SDK', '~> 3.7.3'
pod 'Branch', '~> 0.29.3'
pod 'TPKeyboardAvoiding', '~> 1.3.2'
pod 'Firebase'
pod 'GoogleTagManager' , '~> 5.0.8'
```

Now the pod update works fine, it gives this log:

```
Analyzing dependencies
Downloading dependencies
Installing Bolts 1.9.1 (was 1.9.0)
Installing Firebase 3.6.0 (was 3.17.0)
Installing Firebase 6.33.0 (was 3.17.0)
Installing FirebaseAnalytics 3.4.2 (was 3.9.0)
Installing FirebaseCore 6.10.3 (was 3.6.0)
Installing FirebaseCoreDiagnostics (1.7.0)
Installing FirebaseCrashlytics (4.6.1)
Installing FirebaseInstallations (1.7.0)
Installing FirebaseInstanceID 1.0.9 (was 1.0.10)
Installing GoogleDataTransport (7.4.0)
Installing GoogleInterchangeUtilities (1.2.2)
Installing GoogleUtilities 1.3.2
Installing GoogleUtilities 6.7.2 (was 1.3.2)
Installing PromisesObjC (1.2.10)
Installing Realm 4.4.1 (was 4.4.0)
Installing RealmSwift 4.4.1 (was 4.4.0)
Installing SDWebImage 5.9.2 (was 5.6.1)
Installing TPKeyboardAvoiding 1.3.4 (was 1.3.3)
Installing nanopb (1.30906.0)
Removing Crashlytics
Removing Fabric
Removing GoogleToolboxForMac
Generating Pods project
Integrating client project
```

but when I compile the app I get the following error:

`googleutilities/gulloggerlevel.h file not found`

This error happens because Pods/GoogleUtilities has the content of its older version (1.3.2), not the newer one (6.7.2). How is this possible?

I've tried another thing:

- I've removed from the Podfile the all pods related to Firebase and GoogleAnalytics and run a pod update.
- I've added pod Firebase/Analytics and run a pod update. This creates the folder Pods/GoogleUtilities with the newer content (6.7.2 version).
- I've added the rest of pods related to GoogleAnalytics. This overwrites the folder Pods/GoogleUtilities with the older content (1.3.2 version), so the googleutilities/gulloggerlevel.h file is not found again.

So is this the normal behavior? Is it possible to have in the same podfile pod Google/Analytics and pod Firebase/Crashlytics?

**Comment by morganchen12** [comment]
Something strange is going on in your pod update output where it's specifying multiple versions of the same pod.

```
Installing Firebase 3.6.0 (was 3.17.0)
Installing Firebase 6.33.0 (was 3.17.0)
...
Installing GoogleUtilities 1.3.2
Installing GoogleUtilities 6.7.2 (was 1.3.2)
```

I'm not sure what's causing this, but if you're able to reproduce it in a sample project and share it I can help take a look.

**Comment by paulb777** [comment]
It's likely a CocoaPods but to install two versions of the same pod.

However, a fundamental issue that CocoaPods cannot solve is installing versions of pods with incompatible dependencies. For example, GoogleTagManager 5.0.8 is incompatible with recent versions of Firebase. There should be details about the dependencies in the generated `Podfile.lock`.

**Comment by rferbesa** [comment]
Thank you for the answers!
I've created a simple repository with an empty project and the initial pods installed:
https://github.com/rferbesa/FirebaseIssue

From this point it's easy to make the steps:
- Change Fabric and Crashlytics to Firebase/Crashlytics
- Remove version from Firebase.
- pod update.

To check if this could be a problema with GoogleTagManager version I've tried removing the version from pod GoogleTagManager and pod Google/Analytics and run a pod update with the same results (the pod update is correct but the GoogleUtilities folder has the old content).

**Comment by dmytro-me** [comment]
Same problem, I "resolved it" by temporary providing required version for Firebase/Analytics

```  pod 'Firebase/Analytics',  '~> 6.26'```

You probably need to specify version for Google/Analytics

**Comment by rferbesa** [comment]
@dmytro-me If I don't include Firebase/Analytics in my Podifle, should I specify the version for Firebase/Crashlytics? 

pod 'Firebase/Crashlytics', '~> 6.26'?

**Comment by dmytro-me** [comment]
Probably yes, look into Podfile.lock and search who needs  Firebase 3.6.0, in my case it was FirebaseAnalytics.

**Comment by rferbesa** [comment]
Sorry @dmytro-me but I'm a bit confused about how to get the Crashlytics version. 
With this podfile:

```
    pod 'Firebase/Crashlytics'
    pod 'PromiseKit', '~> 4.4'
    pod 'CryptoSwift', '~> 0.9.0'
    pod 'Kingfisher', '~> 4.7.0'
    pod 'KeychainAccess', '~> 3.1.1'
    pod 'Google/Analytics', '~> 3.1.0'
    pod 'Cosmos', '~> 15.0.0'
    pod 'Alamofire', '~> 4.7.2'
    pod 'FRHyperLabel', '~> 1.0.4'
    pod 'RealmSwift', '~> 4.4.0'
    pod 'Realm', '~> 4.4.0'
    pod 'Bolts', '~> 1.9.0'
    pod 'FBSDKCoreKit', '~> 4.36.0'
    pod 'FacebookCore', '~> 0.3.3'
    pod 'CleverTap-iOS-SDK', '~> 3.7.3'
    pod 'Branch', '~> 0.29.3'
    pod 'TPKeyboardAvoiding', '~> 1.3.2'
    pod 'Firebase'
    pod 'GoogleTagManager' , '~> 5.0.8'
```
I get this pod update log:

```
Analyzing dependencies
Downloading dependencies
Installing Firebase 3.6.0 (was 3.17.0 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
Installing Firebase 6.33.0 (was 3.17.0 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
Installing FirebaseAnalytics 3.4.2 (was 3.9.0 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
Installing FirebaseCore 6.10.3 (was 3.6.0 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
Installing FirebaseCoreDiagnostics (1.7.0)
Installing FirebaseCrashlytics (4.6.1)
Installing FirebaseInstallations (1.7.0)
Installing FirebaseInstanceID 1.0.9 (was 1.0.10 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
Installing GoogleDataTransport (7.4.0)
Installing GoogleInterchangeUtilities (1.2.2)
Installing GoogleUtilities 1.3.2 (source changed to `https://cdn.cocoapods.org/` from `trunk`)
Installing GoogleUtilities 6.7.2 (was 1.3.2 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
Installing PromisesObjC (1.2.10)
Installing nanopb (1.30906.0)
Removing Crashlytics
Removing Fabric
Removing GoogleToolboxForMac
Generating Pods project
Integrating client project
Pod installation complete! There are 19 dependencies from the Podfile and 34 total pods installed.
```
The GoogleUtilities folder has the older content.
And my Podfile.lock has this content:

```
PODS:
  - Alamofire (4.7.3)
  - Bolts (1.9.1):
    - Bolts/AppLinks (= 1.9.1)
    - Bolts/Tasks (= 1.9.1)
  - Bolts/AppLinks (1.9.1):
    - Bolts/Tasks
  - Bolts/Tasks (1.9.1)
  - Branch (0.29.3):
    - Branch/Core (= 0.29.3)
  - Branch/Core (0.29.3)
  - CleverTap-iOS-SDK (3.7.3):
    - SDWebImage (~> 5.1)
  - Cosmos (15.0.0)
  - CryptoSwift (0.9.0)
  - FacebookCore (0.3.3):
    - Bolts (~> 1.9)
    - FBSDKCoreKit (~> 4.36)
  - FBSDKCoreKit (4.36.0):
    - Bolts (~> 1.7)
  - Firebase (3.6.0):
    - Firebase/Core (= 3.6.0)
  - Firebase/Analytics (3.6.0):
    - FirebaseAnalytics (= 3.4.2)
  - Firebase/Core (3.6.0):
    - Firebase/Analytics
  - Firebase/CoreOnly (6.33.0):
    - FirebaseCore (= 6.10.3)
  - Firebase/Crashlytics (6.33.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 4.6.1)
  - FirebaseAnalytics (3.4.2):
    - FirebaseInstanceID (~> 1.0)
    - GoogleInterchangeUtilities (~> 1.2)
    - GoogleSymbolUtilities (~> 1.1)
    - GoogleUtilities (~> 1.2)
  - FirebaseCore (6.10.3):
    - FirebaseCoreDiagnostics (~> 1.6)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Logger (~> 6.7)
  - FirebaseCoreDiagnostics (1.7.0):
    - GoogleDataTransport (~> 7.4)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Logger (~> 6.7)
    - nanopb (~> 1.30906.0)
  - FirebaseCrashlytics (4.6.1):
    - FirebaseCore (~> 6.10)
    - FirebaseInstallations (~> 1.6)
    - GoogleDataTransport (~> 7.2)
    - nanopb (~> 1.30906.0)
    - PromisesObjC (~> 1.2)
  - FirebaseInstallations (1.7.0):
    - FirebaseCore (~> 6.10)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/UserDefaults (~> 6.7)
    - PromisesObjC (~> 1.2)
  - FirebaseInstanceID (1.0.9)
  - FRHyperLabel (1.0.4)
  - Google/Analytics (3.1.0):
    - Google/Core
    - GoogleAnalytics (~> 3.12)
  - Google/Core (3.1.0):
    - FirebaseAnalytics (~> 3.2)
  - GoogleAnalytics (3.17.0)
  - GoogleDataTransport (7.4.0):
    - nanopb (~> 1.30906.0)
  - GoogleInterchangeUtilities (1.2.2):
    - GoogleSymbolUtilities (~> 1.1)
  - GoogleSymbolUtilities (1.1.2)
  - GoogleTagManager (5.0.8):
    - FirebaseAnalytics (~> 3.0)
    - GoogleAnalytics (~> 3.0)
    - GoogleUtilities (~> 1.3.0)
  - GoogleUtilities (1.3.2):
    - GoogleSymbolUtilities (~> 1.1)
  - GoogleUtilities/Environment (6.7.2):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/Logger (6.7.2):
    - GoogleUtilities/Environment
  - GoogleUtilities/UserDefaults (6.7.2):
    - GoogleUtilities/Logger
  - KeychainAccess (3.1.2)
  - Kingfisher (4.7.0)
  - nanopb (1.30906.0):
    - nanopb/decode (= 1.30906.0)
    - nanopb/encode (= 1.30906.0)
  - nanopb/decode (1.30906.0)
  - nanopb/encode (1.30906.0)
  - PromiseKit (4.5.2):
    - PromiseKit/Foundation (= 4.5.2)
    - PromiseKit/QuartzCore (= 4.5.2)
    - PromiseKit/UIKit (= 4.5.2)
  - PromiseKit/CorePromise (4.5.2)
  - PromiseKit/Foundation (4.5.2):
    - PromiseKit/CorePromise
  - PromiseKit/QuartzCore (4.5.2):
    - PromiseKit/CorePromise
  - PromiseKit/UIKit (4.5.2):
    - PromiseKit/CorePromise
  - PromisesObjC (1.2.10)
  - Realm (4.4.1):
    - Realm/Headers (= 4.4.1)
  - Realm/Headers (4.4.1)
  - RealmSwift (4.4.1):
    - Realm (= 4.4.1)
  - SDWebImage (5.9.2):
    - SDWebImage/Core (= 5.9.2)
  - SDWebImage/Core (5.9.2)
  - TPKeyboardAvoiding (1.3.4)
```

Taking this into account, what version should I specify in my pod 'Firebase/Crashlytics'?

**Comment by dmytro-me** [comment]
I think your problem is Google/Analytics, Crashlytics resolves Firebase/Crashlytics (6.33.0) and  looks fine for me, although personally I'd upgrade to the latest firebase version.

``` 
  - Firebase/Analytics (3.6.0):
     - FirebaseAnalytics (= 3.4.2)

- Google/Analytics (3.1.0):
    - Google/Core
    - GoogleAnalytics (~> 3.12)
  - Google/Core (3.1.0):
    - FirebaseAnalytics (~> 3.2)

- FirebaseAnalytics (3.4.2):
    - FirebaseInstanceID (~> 1.0)
    - GoogleInterchangeUtilities (~> 1.2)
    - GoogleSymbolUtilities (~> 1.1)
    - GoogleUtilities (~> 1.2)
```

This is Google/Analytics which was deprecated years ago requires old firebase and old Google Utilities.

**Comment by rferbesa** [comment]
The problem is that my customer wants to maintain the old Google/Analytics library but he needs to update Crashlytics from Fabric to Firebase before 15/November. So, is not possible to have simultaneously Google/Analytics and Firebase/Crashlytics?

**Comment by paulb777** [comment]
It's possible to use the `GoogleAnalytics` pod, but not the deprecated `Google` pod that depends on an ancient version of FirebaseAnalytics as shown in @dmytro-me's snippet above.  

It might work for you to change the `Google/Analytics` to `GoogleAnalytics`.

**Comment by rferbesa** [comment]
I'm already working on this approach (using GoogleAnalytics instead of Google/Analytics) and it seems that it's the correct way to do it. So, thank you very much!!

**Comment by paulb777** [comment]
Great! I'll close the issue, but feel free to follow with additional questions.
