### ISSUE TITLE
ld: library not found for -lFirebaseCore on Xcode 12.0.1

### ISSUE THREAD

**Issue by erezhod** [firebase/firebase-ios-sdk#6673]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0.1
  * Firebase SDK version: latest
  * Firebase Component: Core, Messaging, Analytics
  * Component version: _____
  * Installation method: `CocoaPods`

### [REQUIRED] Step 2: Describe the problem

When installing latest Firebase SDK version through Cocoapods (tried 1.9.3 and 1.10.0.rc1) on a legacy Xcode Objective-C project targeting iOS 12 and up, compiler throws an `ld: library not found for -lFirebaseCore` error in build time.
The project itself does recognize Firebase when doing `@import Firebase`.

#### Steps to reproduce:

1. Open an Objective-C project with Xcode 12.0.1
2. Install Cocoapods
3. Import Firebase pods
4. Run an compile through .xcworksapce file
5. Error `ld: library not found for -lFirebaseCore` is thrown and build fails

#### Relevant Code:

Cocoapods file:
```
platform :ios, '12.0'

def common_project
    project 'eComerceApp.xcodeproj'
end

def common_pods
    pod 'Firebase/Analytics'
    pod 'Firebase/Messaging'
end

target 'MyCoolApp' do
    common_pods
end
```

**Comment by paulb777** [comment]
There is likely something corrupt about the Xcode project.  Try `pod deintegrate`, verify there is nothing about Firebase left in the project, and then `pod update`.

If you're still stuck, we'll likely need a reproducible example to help.

**Comment by aqeelaslam** [comment]
I am facing the same issue. The project used to compile alright. I just updated my XCode to Version 12.0.1 (12A7300) and its giving the same error when trying to build the project. 

`library not found for -lFirebaseCore`

I tried @paulb777's solution to `pod deintegrate` & then `pod install` but of no use. 

Did you find any solution @erezhod ?
