### ISSUE TITLE
Update ZipBuilder to include arm64 simulator slices

### ISSUE THREAD

**Issue by ryanwilson** [firebase/firebase-ios-sdk#6674]
Currently the ZipBuilder doesn't handle arm64 simulator slices that are required for Apple Silicon machines. We should update the zip build to ensure that's supported before the first Apple Silicon Macs come out.

https://github.com/firebase/firebase-ios-sdk/blob/5c236784ad64ea32ce5848f5bccd584375c02ba2/ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift#L35-L41

**Comment by paulb777** [comment]
Fixed in #6950
