### ISSUE TITLE
App fails to build once front guide is followed

### ISSUE THREAD

**Issue by RealTechyGod** [firebase/firebase-ios-sdk#6676]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: _____
  * Firebase SDK version: _____
  * Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: _____
  * Installation method: `CocoaPods | Carthage | Zip file | Swift Package Manager` (select one)

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

From what its see multiple people have had verations of this problem yet no attempt has been made to actually fix the issue.

Details

Unable to install ""
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620415
--
An unknown error has occurred.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620415
User Info: {
    DVTRadarComponentKey = 280331;
    MobileDeviceErrorCode = "(0xE8008001)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x000000011fb2d93f DTDKCreateNSErrorFromAMDErrorCode + 220
	1   DTDeviceKitBase                     0x000000011fb6c124 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 155
	2   DVTFoundation                       0x0000000102d54b43 DVTInvokeWithStrongOwnership + 71
	3   DTDeviceKitBase                     0x000000011fb6be65 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1440
	4   IDEiOSSupportCore                   0x000000011f9dcd28 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.292 + 3513
	5   DVTFoundation                       0x0000000102e832aa __DVT_CALLING_CLIENT_BLOCK__ + 7
	6   DVTFoundation                       0x0000000102e84ecc __DVTDispatchAsync_block_invoke + 1191
	7   libdispatch.dylib                   0x00007fff201cd52d _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff201ce717 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff201d454e _dispatch_lane_serial_drain + 606
	10  libdispatch.dylib                   0x00007fff201d501b _dispatch_lane_invoke + 375
	11  libdispatch.dylib                   0x00007fff201deb9b _dispatch_workloop_worker_thread + 819
	12  libsystem_pthread.dylib             0x00007fff2034d4f2 _pthread_wqthread + 314
	13  libsystem_pthread.dylib             0x00007fff2034c4c3 start_wqthread + 15
);
}
--

System Information

macOS Version 11.0 (Build 20A5374g)
Xcode 12.0.1 (17220)

**Comment by RealTechyGod** [comment]
removing or using other swift pac pages results in successful build only Firebase fails to build

**Comment by paulb777** [comment]
This is an Xcode 12 bug being tracked in this repo at #6472. See that issue's discussion for workarounds.

**Comment by RealTechyGod** [comment]
@paulb777 all solutions and workarounds in #6472 have not fixed this issue, this still provide the same error
