### ISSUE TITLE
Build errors when setting iOS Deployment Target to Pods project to iOS12

### ISSUE THREAD

**Issue by SlavcoPetkovski** [firebase/firebase-ios-sdk#6682]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0.1 (12A7300)
  * Firebase SDK version: 6.34.0
  * Firebase Component: GoogleDataTransport
  * Component version: 7.5.0
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem
When setting the iOS Deployment Target to Pods project to iOS12 and trying to build the project, it fails.
#### Steps to reproduce:

Set iOS Deployment Target to Pods project to iOS12 and build the project.
![Screen Shot 2020-10-07 at 10 44 56](https://user-images.githubusercontent.com/20534421/95308784-9ac45800-088a-11eb-81cc-119257afd0e3.png)

**Comment by ryanwilson** [comment]
Hi @SlavcoPetkovski, sorry for the issues. That's a warning that needs to be fixed. In the meantime in order to unblock you, you can disable the `Treat Warnings as Errors` build setting in Xcode for the GoogleDataTransport target.

**Comment by pstasiak** [comment]
@SlavcoPetkovski temp fix, that will survive `pod install`: add `inhibit_all_warnings!` to your podfile.

**Comment by victorvasilica** [comment]
I have encountered the same issue when trying to update to `Firebase` version `6.34.0` and `GoogleDataTransport` version `7.5.0`. Everything works well on version `7.4.0` though. Project deployment target is iOS 12.

**Comment by ryanwilson** [comment]
Thanks, we're working on a fix today. Stay tuned.

**Comment by maksymmalyhin** [comment]
The fix is available at ` release-6.34.0` branch. We will push the podspec update soon.

**Comment by maksymmalyhin** [comment]
GoogleDataTransport 7.5.1 with the fix is available on Cocoapods now. 

I'm closing the issue, but feel free to comment with feedback.

**Comment by jhomik** [comment]
works perfectly, thank you!

**Comment by victorvasilica** [comment]
Same for me, the project compiles without issues, thanks!

**Comment by kcw-grunt** [comment]
Thanks folks!
