### ISSUE TITLE
How to use Firebase Realtime Database in iOS 14 Widget Extension?

### ISSUE THREAD

**Issue by ashishkakkad8** [firebase/firebase-ios-sdk#6683]
Where I need to write the configuration of Firebase in widget extension application?

`FirebaseApp.configure()`

**Comment by ryanwilson** [comment]
Hi @ashishkakkad8 - I don't have a full solution for you (and my suggestion is untested at the moment) but I'm fairly certain we should be able to use a similar strategy as a full SwiftUI app and add an `init` function inside your widget's struct declared with `@main` that calls `FirebaseApp.configure()`:

```
@main
struct FirebaseStartupSequence: Widget {
  init() {
    FirebaseApp.configure()
  }

  let kind: String = "FirebaseStartupSequence"

  var body: some WidgetConfiguration {
    IntentConfiguration(kind: kind, intent: ConfigurationIntent.self, provider: Provider()) { entry in
      FirebaseStartupSequenceEntryView(entry: entry)
    }
    .configurationDisplayName("My Widget")
    .description("This is an example widget.")
  }
}
```

Let me know if that works for you!

**Comment by ashishkakkad8** [comment]
Thank You!
