### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by SValchyshyn** [firebase/firebase-ios-sdk#6695]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.7
  * Firebase SDK version: 6.34.0
  * Firebase Component: FirebaseAnalytics
  * Component version: 6.34.0
  * Installation method: Carthage

#### Steps to reproduce:

What happened? How can we make the problem occur?
The project compiles OK, no problem with that. I have added the FirebaseAnalytics to the project following your Carthage steps.
Here is my Cartfile:
`binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"`

And here is my Frameworks section:
![2020-10-08 at 14 36](https://user-images.githubusercontent.com/10653093/95453587-ca9b5a80-0973-11eb-864c-95c41b116a0c.png)

One of the error I'm receiving that's blocking the build:
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_GULSwizzler", referenced from:
      objc-class-ref in GoogleAppMeasurement(UIViewController+APMScreenClassName_d414992ede38c698bc9a23de180c8cb5.o)
```
Here is the full list:
![2020-10-08 at 14 38](https://user-images.githubusercontent.com/10653093/95453733-0e8e5f80-0974-11eb-83c0-3dfdd39b3677.png)

So, I have been trying to fix it by adding libc++.tbd, libsqlite3.tbd, and libz.tbd. Also, I have run through the Firebase frameworks adding everything I can find in `modulemap` to my Frameworks section and it didn't help.

Firebase frameworks have also been copied from the Carthage folder to the root proj folder.
Nothing of above helps. Do you have any ideas?

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

**Comment by paulb777** [comment]
@SValchyshyn  Sorry to hear about the issue. 

Make sure that `GoogleUtilities.framework` shows up in the `Link Binary With Libraries` build phase.

**Comment by SValchyshyn** [comment]
@paulb777 Hi, thanks for your reply. Yes, it is included in the phase.
![2020-10-08 at 20 04](https://user-images.githubusercontent.com/10653093/95490966-a9516300-09a1-11eb-89cc-78239a0db9f4.png)

**Comment by morganchen12** [comment]
Can you share your project?

**Comment by SValchyshyn** [comment]
Unfortunately not 🙁
I can provide you with any other screens like build settings or anything

**Comment by morganchen12** [comment]
If you're able to reproduce these linker errors in a blank project we'll be better equipped to provide support. Outside of that, the symbols missing in your target are present in the GoogleUtilities framework, so the only thing that comes to mind is maybe you've linked GoogleUtilities into the wrong build target.

**Comment by SValchyshyn** [comment]
I have managed to reproduce not exactly these but similar errors. Please, check it out:
https://github.com/SValchyshyn/FirebaseBugTest

I have not included `GoogleService-Info.plist` intentionally as it is not required for build phase.

**Comment by paulb777** [comment]
The test project looks like a different issue. It's linker failure is resolved by adding StoreKit to the `Link With Libraries` Build Phase:

![Screen Shot 2020-10-09 at 7 07 18 AM](https://user-images.githubusercontent.com/73870/95593241-480bad00-09fe-11eb-9909-1a3cd46bceb0.png)

**Comment by SValchyshyn** [comment]
I have found the issue on my project. We have a modular architecture and one of our modules is using MLKit that was manually built as `.xcframework`. It appeared that those errors are present when building the app with both Google services.

**Comment by SValchyshyn** [comment]
Works well now. Modules were fetching dependencies with different versions which results in compile confusion.
