### ISSUE TITLE
Phone Auth user not behaving as expected

### ISSUE THREAD

**Issue by eccfcco15** [firebase/firebase-ios-sdk#67]
### [READ] Step 1: Are you in the right place?

I really hope so, and am very sorry if not.

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 8.3.2
  * Firebase SDK version: 4.0.0
  * Library version: 4.0.0?
  * Firebase Product: auth (specifically, phone auth)

#### Steps to reproduce:

I have implemented phone auth, using the sample code provided in the docs.  When I call `            Auth.auth().signIn(with: credential) { user, error in ....`, the `user` seems to be valid, with a non-nil phoneNumber (I'm using phone auth).  Later, when I call `Auth.auth().currentUser`, the user I get back also has a non-nil phoneNumber.  However, when I kill my app, and restart it, if I call `Auth.auth().currentUser`, the user I get back has the .phoneNumber property set to nil.

I'm really sorry to bother you, and hope I haven't broken any rules.

**Comment by protocol86** [comment]
Hi @eccfcco15, I took a look at the issue and I am looking into fixing it right now.  In the mean-time you can obtain the user's phone number from provider data as follows:
`let phoneNumber = Auth.auth().currentUser!.providerData.first!.phoneNumber!`

The above snippet assumes that you only have a phone number provider linked to this account, if you have more providers you can always iterate the `providerData` array to find the phone auth provider.
