### ISSUE TITLE
Firebase configuration crash (FirebaseInstallations)

### ISSUE THREAD

**Issue by nikeshakya** [firebase/firebase-ios-sdk#6706]
### Step 0: Are you in the right place?
-> Yes

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0.1
  * Firebase SDK version: 6.34.0
  * Firebase Component:  Messaging, Analytics
  * Component version: Messaging (~> 4.7.1), Analytics (6.9.0)
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem
-> Cannot launch app because it fails in configuring firebase on AppDelegate. The error I am getting are of two types.
1) Terminating app due to uncaught exception 'com.firebase.installations', reason: 'FirebaseInstallations will not work correctly with current version of Firebase Instance ID. Please update your Firebase Instance ID version.'
terminating with uncaught exception of type NSException
2) Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[FIRInstanceIDCheckinPreferences preferencesFromKeychainContents:]: unrecognized selector sent to class 0x1023ce1d0'

-> I have one target with 2 configurations (dev and prod) and this target has 2 dependencies (NotificationServiceExtension and NotificationContentExtension)  

-> Tried clearing pod cache, deintegrate and reinstall but still crashing  

#### Steps to reproduce:
-> Crash on app delegate. FirebaseApp.configure()

#### Relevant Code:

podfile:
```
# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

def shared_pods
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for moneyTracker
  pod 'SideMenuSwift'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'lottie-ios'
  pod 'SkyFloatingLabelTextField'
  pod 'IQKeyboardManager'
  pod 'Kingfisher'
  pod 'Toast-Swift'
  pod 'Tabman'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'YPImagePicker'
  pod 'ImageViewer'
  pod 'KMPlaceholderTextView'
  pod 'MDatePickerView'
  pod 'Charts'
end

target 'moneyTracker' do
  shared_pods
  
  target 'moneyTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'moneyTrackerUITests' do
    # Pods for testing
  end
  
  target 'notifContentExtension' do
    inherit! :search_paths
  end
  
  target 'notifServiceExtension' do
    inherit! :search_paths
  end
  
end
```

**Comment by ryanwilson** [comment]
Hi @nikeshakya - sorry for the troubles. Can you please post your `Podfile.lock` so we can see which versions of all the pods you have? Thanks!

**Comment by nikeshakya** [comment]
hello @ryanwilson Thanks for the response. Here is the podfile.lock 

`PODS:
  - Alamofire (5.2.2)
  - Charts (3.6.0):
    - Charts/Core (= 3.6.0)
  - Charts/Core (3.6.0)
  - Firebase/Analytics (6.34.0):
    - Firebase/Core
  - Firebase/Core (6.34.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.9.0)
  - Firebase/CoreOnly (6.34.0):
    - FirebaseCore (= 6.10.4)
  - Firebase/Messaging (6.34.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 4.7.1)
  - FirebaseAnalytics (6.9.0):
    - FirebaseCore (~> 6.10)
    - FirebaseInstallations (~> 1.7)
    - GoogleAppMeasurement (= 6.9.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.7)
    - GoogleUtilities/MethodSwizzler (~> 6.7)
    - GoogleUtilities/Network (~> 6.7)
    - "GoogleUtilities/NSData+zlib (~> 6.7)"
    - nanopb (~> 1.30906.0)
  - FirebaseCore (6.10.4):
    - FirebaseCoreDiagnostics (~> 1.6)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Logger (~> 6.7)
  - FirebaseCoreDiagnostics (1.7.0):
    - GoogleDataTransport (~> 7.4)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Logger (~> 6.7)
    - nanopb (~> 1.30906.0)
  - FirebaseInstallations (1.7.0):
    - FirebaseCore (~> 6.10)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/UserDefaults (~> 6.7)
    - PromisesObjC (~> 1.2)
  - FirebaseInstanceID (4.8.0):
    - FirebaseCore (~> 6.10)
    - FirebaseInstallations (~> 1.6)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/UserDefaults (~> 6.7)
  - FirebaseMessaging (4.7.1):
    - FirebaseCore (~> 6.10)
    - FirebaseInstanceID (~> 4.7)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.7)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Reachability (~> 6.7)
    - GoogleUtilities/UserDefaults (~> 6.7)
    - Protobuf (>= 3.9.2, ~> 3.9)
  - GoogleAppMeasurement (6.9.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 6.7)
    - GoogleUtilities/MethodSwizzler (~> 6.7)
    - GoogleUtilities/Network (~> 6.7)
    - "GoogleUtilities/NSData+zlib (~> 6.7)"
    - nanopb (~> 1.30906.0)
  - GoogleDataTransport (7.5.1):
    - nanopb (~> 1.30906.0)
  - GoogleUtilities/AppDelegateSwizzler (6.7.2):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (6.7.2):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/Logger (6.7.2):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (6.7.2):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (6.7.2):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (6.7.2)"
  - GoogleUtilities/Reachability (6.7.2):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (6.7.2):
    - GoogleUtilities/Logger
  - ImageViewer (6.0.0)
  - IQKeyboardManager (6.5.6)
  - Kingfisher (5.15.5):
    - Kingfisher/Core (= 5.15.5)
  - Kingfisher/Core (5.15.5)
  - KMPlaceholderTextView (1.4.0)
  - lottie-ios (3.1.8)
  - MDatePickerView (1.2.3)
  - nanopb (1.30906.0):
    - nanopb/decode (= 1.30906.0)
    - nanopb/encode (= 1.30906.0)
  - nanopb/decode (1.30906.0)
  - nanopb/encode (1.30906.0)
  - Pageboy (3.6.1)
  - PromisesObjC (1.2.11)
  - Protobuf (3.13.0)
  - PryntTrimmerView (4.0.2)
  - SideMenuSwift (2.0.6)
  - SkyFloatingLabelTextField (3.8.0)
  - SteviaLayout (4.7.3)
  - SwiftyJSON (5.0.0)
  - Tabman (2.9.1):
    - Pageboy (~> 3.6.0)
  - Toast-Swift (5.0.1)
  - YPImagePicker (4.4.0):
    - PryntTrimmerView (~> 4.0.2)
    - SteviaLayout (~> 4.7.3)

DEPENDENCIES:
  - Alamofire
  - Charts
  - Firebase/Analytics
  - Firebase/Messaging
  - ImageViewer
  - IQKeyboardManager
  - Kingfisher
  - KMPlaceholderTextView
  - lottie-ios
  - MDatePickerView
  - SideMenuSwift
  - SkyFloatingLabelTextField
  - SwiftyJSON
  - Tabman
  - Toast-Swift
  - YPImagePicker

SPEC REPOS:
  trunk:
    - Alamofire
    - Charts
    - Firebase
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseInstallations
    - FirebaseInstanceID
    - FirebaseMessaging
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleUtilities
    - ImageViewer
    - IQKeyboardManager
    - Kingfisher
    - KMPlaceholderTextView
    - lottie-ios
    - MDatePickerView
    - nanopb
    - Pageboy
    - PromisesObjC
    - Protobuf
    - PryntTrimmerView
    - SideMenuSwift
    - SkyFloatingLabelTextField
    - SteviaLayout
    - SwiftyJSON
    - Tabman
    - Toast-Swift
    - YPImagePicker

SPEC CHECKSUMS:
  Alamofire: 814429acc853c6c54ff123fc3d2ef66803823ce0
  Charts: b1e3a1f5a1c9ba5394438ca3b91bd8c9076310af
  Firebase: c23a36d9e4cdf7877dfcba8dd0c58add66358999
  FirebaseAnalytics: 3bb096873ee0d7fa4b6c70f5e9166b6da413cc7f
  FirebaseCore: d3a978a3cfa3240bf7e4ba7d137fdf5b22b628ec
  FirebaseCoreDiagnostics: 770ac5958e1372ce67959ae4b4f31d8e127c3ac1
  FirebaseInstallations: 466c7b4d1f58fe16707693091da253726a731ed2
  FirebaseInstanceID: bd3ffc24367f901a43c063b36c640b345a4a5dd1
  FirebaseMessaging: 5eca4ef173de76253352511aafef774caa1cba2a
  GoogleAppMeasurement: a6a3a066369828db64eda428cb2856dc1cdc7c4e
  GoogleDataTransport: f56af7caa4ed338dc8e138a5d7c5973e66440833
  GoogleUtilities: 7f2f5a07f888cdb145101d6042bc4422f57e70b3
  ImageViewer: cb88ef1c0ba19161bc10702adfdcebc116a7a59d
  IQKeyboardManager: 2a6e97afdafc7becf0cb17a9a8d795e3a980717f
  Kingfisher: e3ec347a5ab8817b7585ef46923a2d2b9a7d8fbe
  KMPlaceholderTextView: 2206c3df39979e9396e2d96fa9f427a8951121b0
  lottie-ios: 48fac6be217c76937e36e340e2d09cf7b10b7f5f
  MDatePickerView: e26233885de2f13659c6101b3ed265eacf92c078
  nanopb: 59317e09cf1f1a0af72f12af412d54edf52603fc
  Pageboy: 29a2d474ad99404b4d77f325e0ab6d705930a4fb
  PromisesObjC: 8c196f5a328c2cba3e74624585467a557dcb482f
  Protobuf: 3dac39b34a08151c6d949560efe3f86134a3f748
  PryntTrimmerView: 6a43cc90df5d99addeabd33d4ba09b1365322130
  SideMenuSwift: f12ca1b11faad909bfc2878df37e0a1c40fa4570
  SkyFloatingLabelTextField: 5a338412114808e961fe2d14ea2c5452c8b6e4aa
  SteviaLayout: c2ecdcff57d44e38fd2f65e54ad52aeae28ca0c4
  SwiftyJSON: 36413e04c44ee145039d332b4f4e2d3e8d6c4db7
  Tabman: 085d89c65be9e883629bdaf5b1453a6397e57846
  Toast-Swift: 9b6a70f28b3bf0b96c40d46c0c4b9d6639846711
  YPImagePicker: 15aed8bcaa4dad976e11b6114126d731a2f9f3c9

PODFILE CHECKSUM: bac590f9b5f9431b4b144687da94f1536a9a251f

COCOAPODS: 1.10.0.rc.1
`

**Comment by paulb777** [comment]
This is likely the result of something corrupted in the Xcode project or state since that failure should only happen with a misconfigured installation. We'll likely need a reproducible example to provide more assistance.
