### ISSUE TITLE
Several typos of 'dimiss' -> 'dismiss'

### ISSUE THREAD

**Issue by jim-hays-root** [firebase/firebase-ios-sdk#6707]
### [REQUIRED] Step 1: Describe your environment
Global

### [REQUIRED] Step 2: Describe the problem
In the codebase there are multiple instances of 'dimiss' which should be 'dismiss'

#### Steps to reproduce:
Search for 'dimiss' in the repo.

#### Relevant Code:
To see the relevant portions of code that this fixes, see this proposed PR: https://github.com/firebase/firebase-ios-sdk/pull/6708

**Comment by ryanwilson** [comment]
Whoops! Thanks so much for reporting and for the PR. I've assigned it to the appropriate team to take a look.

**Comment by paulb777** [comment]
Fixed by #6708
