### ISSUE TITLE
Unable to see crashes on Firebase

### ISSUE THREAD

**Issue by hanumanAbacus** [firebase/firebase-ios-sdk#6716]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.6
  * Firebase SDK version: 6.23.0
  * Firebase Component: _____ Crashlytics
  * Component version: _____
  * Installation method: Carthage

#### Steps to reproduce:

app id: com.abacus.abacusPOS, com.kinnov.posskient

likely receive a faster response on your issue.

#### Relevant Code:
6.23.0 - [Firebase/Crashlytics][I-CLS000000] Failed to download settings Error Domain=FIRCLSNetworkError Code=-5 "(null)" UserInfo={status_code=403, type=2, request_id=, content_type=application/json; charset=utf-8}

**Comment by morganchen12** [comment]
Hey @hanumanAbacus, please file this issue at [Firebase Support](https://firebase.google.com/support). They'll be able to look at your Firebase project information.
