### ISSUE TITLE
FetchSignInMethods returns double nil

### ISSUE THREAD

**Issue by lorenzofiamingo** [firebase/firebase-ios-sdk#6717]
### Environment

  * Firebase Component:  Auth
  * Installation method: Swift Package Manager

### Problem
When you call `Auth.auth().fetchSignInMethods` and there are providers linked to this account they are returned in an Array. When there aren't providers linked it returns a nil value. I think it would more appropriate for it to return an empty array.
I think is no sense to return a `(nil, nil)` touple when there is no error and the providers (in this case none) are fetched.
Returning an empty array makes more sense also in the case of a future (as you planned in the GitHub projects) Result<[String], Error> return type.

By the way, using only these three methods I was able to port all Auth, Storage and Firestore methods to use Result closures:

``` swift
private func mapResult<T, E>(_ completion: @escaping (Result<T, E>) -> Void) -> ((T?, E?) -> Void) {
    {
        if let e = $1 { return completion(.failure(e)) }
        guard let t = $0 else { preconditionFailure() }
        completion(.success(t))
    }
}

private func mapResult<E>(_ completion: @escaping (Result<Void, E>) -> Void) -> ((E?) -> Void) {
    {
        if let e = $0 { return completion(.failure(e)) }
        completion(.success(()))
    }
}

private func mapResult<T0, T1>(_ completion: @escaping (Result<(T0, T1), Never>) -> Void) -> (T0, T1) -> Void {
    {
        completion(.success(($0, $1)))
    }
}
``` 
Then I simply used them in this way:

``` swift
func updateCurrentUser(_ user: User, completion: @escaping (Result<Void, Error>) -> Void) {
    updateCurrentUser(user, completion: mapResult(completion))
}
    
func fetchSignInMethods(forEmail email: String, completion: @escaping (Result<[String], Error>) -> Void) {
    fetchSignInMethods(forEmail: email, completion: mapResult(completion))
}
    
func signIn(withEmail email: String, password: String, completion: @escaping (Result<AuthDataResult, Error>) -> Void) {
    signIn(withEmail: email, password: password, completion: mapResult(completion))
}

...
```
As said this work for all methods, except for `fetchSignInMethods` where for now I have to do this strange custom closure:

  ``` swift
func fetchSignInMethods(forEmail email: String, completion: @escaping (Result<[String], Error>) -> Void) {
    fetchSignInMethods(forEmail: email) {
        if let e = $1 { return completion(.failure(e)) }
        let t = $0 == nil ? [] : $0!
        completion(.success(t))
    }
}
 ```
Moving towards from this point to Combine was even easier:

``` swift
func updateCurrentUserPublisher(_ user: User) -> Future<Void, Error> {
    Future { self.updateCurrentUser(user, completion: $0) }
}
    
func fetchSignInMethodsPublisher(forEmail email: String) -> Future<[String], Error> {
    Future { self.fetchSignInMethods(forEmail: email, completion: $0) }
}
    
func signInPublisher(withEmail email: String, password: String) -> Future<AuthDataResult, Error> {
    Future { self.signIn(withEmail: email, password: password, completion: $0) }
}

...
 ```

Waiting for Native Result and Combine support! Thanks

**Comment by paulb777** [comment]
@lorenzofiamingo Thanks for the ideas. Our team is currently busy with the next release, but after that we want to spend more bandwidth on improving the Swift APIs and usability. 

In case you're not aware, the[ FirebaseStorageSwift library](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseStorageSwift/Sources/SwiftAPIExtension.swift) already provides `Result` type wrappers for the FirebaseStorage APIs.  It would be great to do something similar for the Auth APIs.

And we'll be glad to consider PRs for additional improvements and extensions.

**Comment by paulb777** [comment]
Closing since `fetchSignInMethods` is now deprecated
