### ISSUE TITLE
Regression: RemoteConfig being installed with Performance

### ISSUE THREAD

**Issue by ppamorim** [firebase/firebase-ios-sdk#6723]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0.1
  * Firebase SDK version: 6.34.0
  * Firebase Component: Performance
  * Component version: 3.3.1
  * Installation method: CocoaPods

#### Steps to reproduce:

After the update of the `Performance` library to version 3.3.1, the `RemoteConfig` library was added as a dependency of the `Performance` library. I am not sure if this can create any conflict with any other `RemoteConfig` dependencies. Older versions of the Performance` library are not including it in the project.

If this change is expected, could you please add this to the documentation or changelog?

#### Relevant Code:

```
Not applicable
```

**Comment by morganchen12** [comment]
Hey @ppamorim, this is an expected change and was added to the changelog [here](https://firebase.google.com/support/release-notes/ios#performance-monitoring_20) in 2018. This should not create any conflicts with Remote Config.
