### ISSUE TITLE
#include <nanopb/pb.h> Could not build module 'nanopb'

### ISSUE THREAD

**Issue by replytoashish008** [firebase/firebase-ios-sdk#6740]
I know this has been answered previously on Stack however, the reason for this was outdated cocoapods (not being at least version 1.2.0)

I am currently running version 1.9.3 and using Xcode 12 and still getting this error.

I have done the usual steps to see if the following will solve the issue;

Cleaned Build Folder
Removed derived data
Restarted Xcode
Updated Cocoapods
Checked Cocoapods is on latest version
I believe this is a module pulled in along with Firebase/Firestore

pods used:-

pod 'Firebase/Auth'
pod 'Firebase/Messaging'
pod 'Firebase/Analytics'
pod 'FirebaseFirestoreSwift'
pod'Firebase/Database'
pod 'Firebase/Crashlytics'

`https://stackoverflow.com/questions/64378589/include-nanopb-pb-h-could-not-build-module-nanopb`

**Comment by paulb777** [comment]
Update to CocoaPods 1.10.0. Full answer at https://stackoverflow.com/a/63648164/556617
