### ISSUE TITLE
Firebase fetchWithExpirationDuration completion handler not called in release mode

### ISSUE THREAD

**Issue by tazihosniomar** [firebase/firebase-ios-sdk#6743]
Environment:

Xcode version: 11.6 (11E708)
Firebase SDK versions:
Firebase (6.32.2)
FirebaseABTesting (4.2.0)
FirebaseAnalytics (6.8.2)
FirebaseCore (6.10.2)
FirebaseCoreDiagnostics (1.6.0)
FirebaseInstallations (1.7.0)
FirebaseRemoteConfig (4.9.0) 

the problem:

When calling RemoteConfig.remoteConfig().fetch(withExpirationDuration: 5 * 60, completionHandler: { status, error in
// this bloc is not called .
            })
 in my SplashScreen, the completion handler is never called in release build for the first time and in debug build it works fine.

thank you in advance for your help.

**Comment by tazihosniomar** [comment]
Hello google-oss-bot which information do you want me to include ?

**Comment by morganchen12** [comment]
Hi @tazihosniomar, please fill out the issue template. Also, can you share the debug logs from your app when the bug occurs?

**Comment by tazihosniomar** [comment]
Hi @morganchen12 it occurs only when I download the app from TestFlight but when I launch the app from Xcode it works fine.

**Comment by tazihosniomar** [comment]
On AppDelegate I call :
```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
// MARK: Firebase
        FirebaseApp.configure()

}
```

and splashScreen I do:

```
private func loadRemoteConfig() -> Observable<Void> {
        return Observable<FirebaseRemoteConfigStatus>.create { observable -> Disposable in
            observable.onNext(.pending)
            RemoteConfig.remoteConfig().fetch(withExpirationDuration: 5 * 60, completionHandler: { status, error in
                if let _ = error {
                    if !Environment.current.sfccHost.isEmpty, !Environment.current.commerceCloudShopUrlPattern.isEmpty {
                        observable.onNext(.degraded)
                    } else {
                        observable.onNext(.error)
                    }
                } else {
                   RemoteConfig.remoteConfig().activate { _, _ in
                        observable.onNext(.ok)
                    }
                }
            })
            return Disposables.create()
        }
        .filter { $0 != .pending }
        .map { [weak self] status -> Void in
            if status == .ok || status == .degraded {
                self?.refreshServices()
                return
            } else {
                throw NSError(domain: "", code: 0, userInfo: nil)
            }
        }
    }
```

**Comment by paulb777** [comment]
@tazihosniomar Does the issue occur if you build the Release configuration locally? I'm not sure we'll be able to help without a reproducible example.

**Comment by i0sa** [comment]
Is there any update on this, could you define the root cause ? @tazihosniomar

**Comment by mtarekswvl** [comment]
We are experiencing the same issue @paulb777 

  * Xcode version: 12.2
  * Firebase SDK version: 7.1.0
  * Installation method: CocoaPods
  * Firebase Component: RemoteConfig

`remoteConfig.fetch withExpirationDuration` completion handler is not called randomly both in Debug and Release mode. Please let me know if I can provide you with more information.

Note that we get a lot of `Class is implemented in both targets` for some of firebase classes. I think it's because we're using firebase from dynamic frameworks. Could this be the issue here?

**Comment by morganchen12** [comment]
@mtarekswvl the duplicate class definitions problem is most likely causing the issue you're seeing. See [this documentation](https://firebase.google.com/docs/ios/link-firebase-static-dynamic) for more details on how to solve it.

**Comment by mtarekswvl** [comment]
> @mtarekswvl the duplicate class definitions problem is most likely causing the issue you're seeing. See [this documentation](https://firebase.google.com/docs/ios/link-firebase-static-dynamic) for more details on how to solve it.

I don't get the warning for `Class FIRApp is implemented in both` but I get it for other Firebase classes. Will this also cause issues?

**Comment by paulb777** [comment]
Yes, any `implemented in both` warnings have the potential to cause issues since they cause non-deterministic behavior for any static data.
