### ISSUE TITLE
Cannot find type 'GADInterstitial' in scope and SwiftUI Preview not working when add firebase product

### ISSUE THREAD

**Issue by phukhanhlee** [firebase/firebase-ios-sdk#6764]
### Step 0: Are you in the right place?
Yes

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: xcode12.0
  * Firebase SDK version: 6.34.0
  * Firebase Component: Analytics (6.9.0),Google-Mobile-Ads-SDK (7.66.0)
  * Installation method: `CocoaPods

#### Steps to reproduce:

Just add :   
pod 'Google-Mobile-Ads-SDK'  
pod 'Firebase/Analytics'

Then SwiftUI previews doesn't work anymore. 
I try to fix with by add : pod 'GoogleDataTransport', :git=>'https://github.com/firebase/firebase-ios-sdk.git', :commit=>'38be2cc -> seem just fix for firebase analytics.

App don't crash but working with SwiftUI without Previews UI is impossible :)

#### Relevant Code:

Do this bug related to Firebase product or it's also related to Xcode ?
Any idea to fix this issues ? 

<img width="1226" alt="Screen Shot 2020-10-19 at 5 33 09 PM" src="https://user-images.githubusercontent.com/943472/96439892-5d1fe180-1231-11eb-9eb0-6d5fcee57a44.png">

**Comment by phukhanhlee** [comment]
import Firebase //disable this code -> everything work well 

func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        FirebaseApp.configure() //disable this code -> everything work well  
        return true
    }

Seem the error related to Firebase

**Comment by morganchen12** [comment]
Possibly related to #6219

**Comment by phukhanhlee** [comment]
@morganchen12  Thanks !

We can install firebase via SPM:
https://github.com/firebase/firebase-ios-sdk/blob/master/SwiftPackageManager.md

But it will create another issue : duplicate object because it will confict with Admob SDK with install via cocoapods.
Example : Promises, nanopb

**Comment by phukhanhlee** [comment]
We can have a fix like this :
Add Admob sdk manually (only add necessary framework avoid  duplicated)
And add firebase still via cocoapod

**Comment by paulb777** [comment]
Is this still an issue with Google-Mobile-Ads-SDK 8.x?
