### ISSUE TITLE
 Showing Recent Issues Undefined symbol: _OBJC_CLASS_$_FIRApp  firebase Carthage ios

### ISSUE THREAD

**Issue by vijayvishesh** [firebase/firebase-ios-sdk#6765]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: _____ 11.3
  * Firebase SDK version: _____
  * Firebase Component: __auth,___ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: _____
  * Installation method: `CocoaPods | Carthage | Zip file | Swift Package Manager` (select one)

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FIRApp", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by paulb777** [comment]
@vijayvishesh Sorry that you're having problems. Please make sure that `FirebaseCore.xcframework` is linked into the app.  This is almost certainly a configuration issue. Please review that you have followed the instructions.

We'll likely need a reproducible example to provide more assistance.

**Comment by vijayvishesh** [comment]
> FirebaseCore.xcframework

Undefined symbols for architecture x86_64:
  "_GULIsLoggableLevel", referenced from:
      _FIRIsLoggableLevel in FirebaseCore(FIRLogger.o)
  "_GULSetLoggerLevel", referenced from:
      _FIRSetLoggerLevel in FirebaseCore(FIRLogger.o)
  "_GULLoggerRegisterVersion", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_GULLoggerInitializeASL", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_GULLogBasic", referenced from:
      _FIRLogBasic in FirebaseCore(FIRLogger.o)
  "_GULLoggerEnableSTDERR", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_GULLoggerForceDebug", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_OBJC_CLASS_$_GULAppEnvironmentUtil", referenced from:
      objc-class-ref in FirebaseCore(FIRApp.o)
      objc-class-ref in FirebaseCore(FIRBundleUtil.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by maksymmalyhin** [comment]
@vijayvishesh now GoogleUtilities.framework looks missing. Could you please double check the integration steps from the [guide](https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md) and let us know the result.
