### ISSUE TITLE
GitHub scheduled actions run on forks

### ISSUE THREAD

**Issue by mikehardy** [firebase/firebase-ios-sdk#6769]
I apologize profusely for deleting the template but please understand this is not really a bug with the SDK, per se, it is a meta bug because it only has to do with your GitHub actions configuration.

Invertase maintains a fork of firebase-ios-sdk - for reasons mostly unimportant here - but what happened when I resynced the main branch from you guys here is we got a bunch of Action definitions that run on schedules.

So now we are burning PILES of GitHub Action runner time on scheduled actions from our fork, for no real benefit.

Would you be okay with setting the Actions here to only run on the main repo and skip execution on forks? Seems like the neighborly thing to do for the poor Actions runners at GitHub ;-)

Cheers

**Comment by paulb777** [comment]
Good point - there's no reason for the `schedule` workflows to run on forks. Thanks for raising this @mikehardy !

Does #6770 address it for you?

**Comment by mikehardy** [comment]
@paulb777 yeah #6770 looks like it should be just the trick, thanks!
