### ISSUE TITLE
Crash on iOS 10: __NSCFLocalUploadTask was deallocated while key value observers were still registered with it

### ISSUE THREAD

**Issue by bearjaw** [firebase/firebase-ios-sdk#6782]
### Step 0: Are you in the right place?

- For issues or feature requests related to the code in this repository
file a Github issue.
If this is a feature request please use the Feature Request template.
- For general technical questions, post a question on StackOverflow
with the firebase tag.
- For general (non-iOS) Firebase discussion, use the firebase-talk
google group.
- For backend issues, console issues, and other non-SDK help that does not fall under one
of the above categories, reach out to
Firebase Support.
- Once you've read this section and determined that your issue is appropriate for
this repository, please delete this section

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Xcode 12.0.1
  * Firebase SDK version: 6.34.0
  * Firebase Component: Unknown (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: Latest
  * Installation method: `CocoaPods` (select one)

### [REQUIRED] Step 2: Describe the problem

Currently our app crashes on iOS 10 devices due to an issue related to KeyValue Observing. I removed all the Firebase pods we currently use in our app and it ran just fine. The latest stable build I tested was 6.29.0 and at least starting 6.30.0 this crash started to occur and it is not fixed in 6.34.0.

```
Firebase 6.34.0 (was 6.30.0)
FirebaseAnalytics 6.9.0 (was 6.7.2)
FirebaseCore 6.10.4 (was 6.10.0)
Firebase/Performance (6.34.0)
FirebaseCoreDiagnostics 1.7.0 (was 1.5.0)
FirebaseCrashlytics 4.6.2 (was 4.4.0)
GoogleAppMeasurement 6.9.0 (was 6.7.2)
GoogleDataTransport 7.5.1 (was 7.2.0)
nanopb 1.30906.0 (was 1.30905.0)
```

#### Steps to reproduce:

A short while after using the it terminates with the following exception:

```
 *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance xxxxx of class __NSCFLocalUploadTask was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo xxxxx > (
<NSKeyValueObservance xxxxx: Observer: xxxxx, Key path: state, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: xxxxx>
```

I don't really know which pod is causing the exception. We are not calling any uploading apis, or keyValueObserving methods ourself so it has to come from within the framework itself.

I assume the steps to reproduce is integrate all the Firebase pods mentioned above and use Remote Config and Crashlytics as well as Analytics but I can't really provide a sample project right now.

**Comment by ryanwilson** [comment]
Likely related to #6768 at first glance - can you reproduce the issue locally? If so, try removing Performance temporarily and see if that fixes your issue. I'll leave this open for now in case it's a different issue but if it's Performance that's causing the issue we'll close this one in favour of #6768.

**Comment by bearjaw** [comment]
I can reproduce it ever time. Seems related to #6768 . Removing the Performance works as a temporary workaround.
