### ISSUE TITLE
Characters not allowed in a properly URL when execute FIRDLDictionaryFromQuery function  

### ISSUE THREAD

**Issue by cjimenezpacho** [firebase/firebase-ios-sdk#6786]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0.1
  * Firebase SDK version: 6.34.0
  * Firebase Component: FirebaseDynamicLinks
  * Component version: 6.34.0
  * Installation method: `CocoaPods`

### [REQUIRED] Step 2: Describe the problem

If the parameter `link` contains diacritical characters deeplink cannot be processed correctly.

#### Steps to reproduce:

Using this sample link: 

https://XXXX.app.goo.gl/?link=https://DEEPLINK?latitude%3D41.404891232066234%26longitude%3D-3.2052324507419998%26last-name%3Dsjim%C3%A9nez

I use this method to process deeplink:

```
[[FIRDynamicLinks dynamicLinks] handleUniversalLink:url
                                             completion:^(FIRDynamicLink *_Nullable dynamicLink, NSError *_Nullable error) {
                                             }];

```

If I debug into `handleUniversalLink: completion` I can see at 414 line breakpoint:

![Captura de pantalla 2020-10-20 a las 16 57 14](https://user-images.githubusercontent.com/2428271/96604394-5a86c000-12f5-11eb-975f-30e0c904d79f.png)

following values:

- `url`: https://XXX/?link=https://ZZZZZZZ?latitude%3D41.404891232066234%26longitude%3D-3.2052324507419998%26last-name%3Dsjim%C3%A9nez
- `parameters`: 
![Captura de pantalla 2020-10-20 a las 16 59 03](https://user-images.githubusercontent.com/2428271/96604794-c8cb8280-12f5-11eb-84c9-1d9e3677aac0.png)

At this moment,`link`  has already removed percentage encoding (see `FIRDLDictionaryFromQuery` from `FDLUtilities.m`)
You can see an almost valid URL. I say almost because it has `\` character.
So, after these two lines:

```
NSString *urlString = parameters[kFIRDLParameterLink];
NSURL *deepLinkURL = [NSURL URLWithString:urlString];

```

`deepLinkURL` is `nil` because `URLWithString`, according to doc:  

> This method expects URLString to contain only characters that are allowed in a properly formed URL. All other characters must be properly percent escaped. The URL string with which to initialize the NSURL object. Must be a URL that conforms to RFC 2396. This method parses URLString according to RFCs 1738 and 1808.

If the parameter `link` is a URL, I must be able to form it with percentage encoding but at this point it has already been de-coded and I have a character that URLWithString method cannot understand.
As the parameter link is a URL I propose you to escape it before calling URLWithString in this way:

![Captura de pantalla 2020-10-20 a las 17 10 42](https://user-images.githubusercontent.com/2428271/96606178-48a61c80-12f7-11eb-909c-a697ebf89c14.png)

Kind regards

**Comment by eldhosembabu** [comment]
Thanks for pointing this out. We will check on this solution and get back. In the mean time, do you want to come up with a Pull Request for the same?

**Comment by k-o-d-e-n** [comment]
Good day, @eldhosembabu .
Why don't you use `NSURLComponents` instead of custom parsing? It would avoid `percentage encoding` at all. Moreover, Android library generates a URL without percentage encoding, and such URLs are not "universal".

**Comment by elenipapanik** [comment]
I have exactly the same issue and the solution proposed by @cjimenezpacho seems to work. Shouldn't this pull request proceed?

**Comment by paulb777** [comment]
Closing as not-to-be-fixed based on concerns about breaking existing behavior. See https://github.com/firebase/firebase-ios-sdk/pull/6956#issuecomment-1379357617

Please use the suggested workaround above.
