### ISSUE TITLE
FR: improve Crashlytics initialization fail message

### ISSUE THREAD

**Issue by iKleMiX** [firebase/firebase-ios-sdk#6794]
### Feature proposal

* Firebase Component: Crashlytics

Related to #5020. It says that `__mh_execute_header` is not found and recommends to add Exported symbols file. The problem is, we don't have such file and when added Crashlytics starts to work but does not display any our symbols which is logical. I've found out that we have this symbol hidden. 
We followed zld's (https://github.com/michaeleisel/zld) guide on making linking faster, since it takes around 50 seconds. So we added linker flag - `-Wl,-exported_symbols_list,/dev/null` which somehow hides `__mh_execute_header`.
Removing this flag allows Firebase Crashlytics to be initialized properly.
Info about this flag could be added to the message as well.

**Comment by samedson** [comment]
Hey @iKleMiX - thanks for letting us know about this! We've added this information to the error log in a PR.
