### ISSUE TITLE
[Firebase/Crashlytics][I-CLS000000] Failed to download settings in iOS 

### ISSUE THREAD

**Issue by dilipmishra907** [firebase/firebase-ios-sdk#6812]
Hello Team,
I am getting this issue when i am trying to implement firebase crashanlatics 
[Firebase/Crashlytics][I-CLS000000] Failed to download settings Error Domain=FIRCLSNetworkError Code=-5 "(null)" UserInfo={status_code=403, type=2, request_id=, content_type=application/json; charset=utf-8}

I have followed this steps correctly.
https://firebase.google.com/docs/crashlytics/get-started?authuser=1&platform=ios

Also facing another issue loading is appearing in firebase console and nothing is happening when i have enabled crashanalytics in left tab.

Please suggest me what i am doing wrong.

Thanks

**Comment by morganchen12** [comment]
@dilipmishra907 please file a [support ticket](https://firebase.google.com/support) instead.
