### ISSUE TITLE
Firebase/Crashlytics not working with SPM

### ISSUE THREAD

**Issue by vivek4292** [firebase/firebase-ios-sdk#6814]
### Trying to integrate crashlytics via Swift Package Manager

- Xcode version: 12.1 GM Seed
- Firebase SDK version: 6.34-spm-beta
- Firebase Component: Crashlytics
- Component version: [Firebase/Crashlytics] Version 6.34.0
- Installation method: Swift Package Manager

### Script:
${BUILD_DIR%Build/*}SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run

### Script input file.
${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
$(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)

firebase is n0t able to listen my app and its crashes. All I'm seeing is in screenshot below.

<img width="578" alt="Screenshot 2020-10-23 at 5 53 07 PM" src="https://user-images.githubusercontent.com/34335017/97004439-b605b780-155a-11eb-923d-7a999dc5ca2b.png">

Please help

**Comment by morganchen12** [comment]
Please file a ticket at [Firebase Support](https://firebase.google.com/support).

**Comment by ginesdeka** [comment]
The same issue

**Comment by Hamoonist** [comment]
Same here.

**Comment by Hamoonist** [comment]
> Please file a ticket at [Firebase Support](https://firebase.google.com/support).

Then why Firebase's Github is open for issues?
It is clearly a problem with SPM implementation and not limited to one user.

**Comment by ninjaproger** [comment]
Same here.

**Comment by morganchen12** [comment]
Hey all, apologies for closing this issue, I had thought it was a project-specific misconfiguration and not an issue with SPM. Please follow along at #6864.
