### ISSUE TITLE
Insecure SSL: Overly Broad Certificate Trust

### ISSUE THREAD

**Issue by Shakihassan** [firebase/firebase-ios-sdk#6821]
The call to dataTaskWithRequest:completionHandler:() in FIRInstanceIDTokenDeleteOperation.m on line 87 initiates an SSL/TLS connection using the default pre-loaded system Certificate Authorities (CAs) that might enable attackers to intercept encrypted communications by performing man-in-the-middle (MiTM) attacks using certificates signed with compromised root CAs.An SSL/TLS connection is created using the default pre-loaded system Certificate Authorities (CAs), that might enable attackers to intercept encrypted communications by performing man-in-the-middle (MiTM) attacks using certificates signed with compromised root CAs.

The call to dataTaskWithRequest:completionHandler:() in FIRInstanceIDTokenFetchOperation.m on line 120 initiates an SSL/TLS connection using the default pre-loaded system Certificate Authorities (CAs) that might enable attackers to intercept encrypted communications by performing man-in-the-middle (MiTM) attacks using certificates signed with compromised root CAs.An SSL/TLS connection is created using the default pre-loaded system Certificate Authorities (CAs), that might enable attackers to intercept encrypted communications by performing man-in-the-middle (MiTM) attacks using certificates signed with compromised root CAs.

Note : Reported by the Fortify on demand Team

**Comment by morganchen12** [comment]
Firebase doesn't allow for custom certificate pinning on iOS. If you would like to request this feature, please file a feature request.
