### ISSUE TITLE
JSON Injection

### ISSUE THREAD

**Issue by Shakihassan** [firebase/firebase-ios-sdk#6822]
On line 708 of RCNConfigDBManager.m, the method loadMetadataTableWithBundleIdentifier:() writes unvalidated input into JSON. This call could allow an attacker to inject arbitrary elements or attributes into the JSON entity.The method writes unvalidated input into JSON. This call could allow an attacker to inject arbitrary elements or attributes into the JSON entity.

On line 715 of RCNConfigDBManager.m, the method loadMetadataTableWithBundleIdentifier:() writes unvalidated input into JSON. This call could allow an attacker to inject arbitrary elements or attributes into the JSON entity.The method writes unvalidated input into JSON. This call could allow an attacker to inject arbitrary elements or attributes into the JSON entity.

On line 686 of RCNConfigDBManager.m, the method loadMetadataTableWithBundleIdentifier:() writes unvalidated input into JSON. This call could allow an attacker to inject arbitrary elements or attributes into the JSON entity.The method writes unvalidated input into JSON. This call could allow an attacker to inject arbitrary elements or attributes into the JSON entity.

On line 757 of RCNConfigDBManager.m, the method ^{}() writes unvalidated input into JSON. This call could allow an attacker to inject arbitrary elements or attributes into the JSON entity.The method writes unvalidated input into JSON. This call could allow an attacker to inject arbitrary elements or attributes into the JSON entity.

On line 693 of RCNConfigDBManager.m, the method loadMetadataTableWithBundleIdentifier:() writes unvalidated input into JSON. This call could allow an attacker to inject arbitrary elements or attributes into the JSON entity.The method writes unvalidated input into JSON. This call could allow an attacker to inject arbitrary elements or attributes into the JSON entity.

On line 701 of RCNConfigDBManager.m, the method loadMetadataTableWithBundleIdentifier:() writes unvalidated input into JSON. This call could allow an attacker to inject arbitrary elements or attributes into the JSON entity.The method writes unvalidated input into JSON. This call could allow an attacker to inject arbitrary elements or attributes into the JSON entity.

**Comment by morganchen12** [comment]
These fields are remote config state created and written by the RemoteConfig SDK, so no user input goes into them.
