### ISSUE TITLE
Insecure Storage: Lacking Data Protection

### ISSUE THREAD

**Issue by Shakihassan** [firebase/firebase-ios-sdk#6823]
On line 58 of FIRCLSFileManager.m, the method createFileAtPath:contents:attributes:() writes data to a file lacking sufficient encryption settings.The identified method writes data to a file lacking sufficient encryption settings.

**Comment by morganchen12** [comment]
Crashlytics uses this method to store crash data, which isn't inaccessible to the user for apps even where Crashlytics is not installed (a user can pull unsymbolicated crashes from their device through Xcode).
