### ISSUE TITLE
Insecure Storage: Lacking Data Protection

### ISSUE THREAD

**Issue by Shakihassan** [firebase/firebase-ios-sdk#6824]
On line 55 of GDTCOREvent.m, the method ^{}() writes data to a file lacking sufficient encryption settings.The identified method writes data to a file lacking sufficient encryption settings.

On line 136 of GULHeartbeatDateStorage.m, the method writeDictionary:forWritingURL:error:() writes data to a file lacking sufficient encryption settings.The identified method writes data to a file lacking sufficient encryption settings.

**Comment by morganchen12** [comment]
[The first line in question](https://cs.opensource.google/firebase-sdk/firebase-ios-sdk/+/master:GoogleDataTransport/GDTCORLibrary/GDTCOREvent.m;l=55?q=GDTCOREvent) doesn't write any data to a file. Please update your version of Firebase and let us know if there are any insecurities.
