### ISSUE TITLE
Insecure Transport: Weak SSL Protocol

### ISSUE THREAD

**Issue by Shakihassan** [firebase/firebase-ios-sdk#6825]
The SSLv2, SSLv23, and SSLv3 protocols contain several flaws that make them insecure, so they should not be used to transmit sensitive data.

In this file FIRCLSFABNetworkClient.m:45, FIRCLSNetworkClient.m:104,
FIRCLSNetworkClient.m:197

FIRInstallationsAPIService.m:74,FIRInstanceIDCheckinService.m:60,FIRInstanceIDTokenOperation.m:62, FIRMessagingExtensionHelper.m : 69,FIRMessagingTopicOperation.m : 67

GDTCCTUploader.m : 75,GULNetworkURLSession.m : 153 , GULNetworkURLSession.m : 145 ,GULNetworkURLSession.m : 198

**Comment by morganchen12** [comment]
Apple's ATS settings don't enable these protocols. (taken from [here](https://github.com/Alamofire/Alamofire/issues/3341#issuecomment-716223745))
