### ISSUE TITLE
Privacy Violation

### ISSUE THREAD

**Issue by Shakihassan** [firebase/firebase-ios-sdk#6826]
The function mutableRequestWithDefaultHTTPHeadersForURL:timeout:() in FIRCLSNetworkOperation.m mishandles confidential information on line 74. The program could compromise user privacy.The identified function mishandles confidential information. This program could compromise user privacy.

The function mutableRequestWithURL:timeout:() in FIRCLSReportUploader.m mishandles confidential information on line 327. The program could compromise user privacy.The identified function mishandles confidential information. This program could compromise user privacy.

The function ^{}() in FIRInstallationsAPIService.m mishandles confidential information on line 269. The program could compromise user privacy.The identified function mishandles confidential information. This program could compromise user privacy.

The function checkinWithExistingCheckin:completion:() in FIRInstanceIDCheckinService.m mishandles confidential information on line 92. The program could compromise user privacy.The identified function mishandles confidential information. This program could compromise user privacy.

The function performTokenOperation() in FIRInstanceIDTokenFetchOperation.m mishandles confidential information on line 101. The program could compromise user privacy.The identified function mishandles confidential information. This program could compromise user privacy.

The function performTokenOperation() in FIRInstanceIDTokenFetchOperation.m mishandles confidential information on line 101. The program could compromise user privacy.The identified function mishandles confidential information. This program could compromise user privacy.
The function performTokenOperation() in FIRInstanceIDTokenFetchOperation.m mishandles confidential information on line 101. The program could compromise user privacy.The identified function mishandles confidential information. This program could compromise user privacy.

The function requestWithAuthHeader:FISAuthToken:() in FIRInstanceIDTokenOperation.m mishandles confidential information on line 202. The program could compromise user privacy.The identified function mishandles confidential information. This program could compromise user privacy.
The function requestWithAuthHeader:FISAuthToken:() in FIRInstanceIDTokenOperation.m mishandles confidential information on line 202. The program could compromise user privacy.The identified function mishandles confidential information. This program could compromise user privacy.
The function requestWithAuthHeader:FISAuthToken:() in FIRInstanceIDTokenOperation.m mishandles confidential information on line 199. The program could compromise user privacy.The identified function mishandles confidential information. This program could compromise user privacy.

The function ^{}() in FIRInstallationsAPIService.m mishandles confidential information on line 269. The program could compromise user privacy.The identified function mishandles confidential information. This program could compromise user privacy.

The function performTokenOperation() in FIRInstanceIDTokenFetchOperation.m mishandles confidential information on line 101. The program could compromise user privacy.The identified function mishandles confidential information. This program could compromise user privacy.

The function performTokenOperation() in FIRInstanceIDTokenFetchOperation.m mishandles confidential information on line 101. The program could compromise user privacy.The identified function mishandles confidential information. This program could compromise user privacy.
The function performSubscriptionChange() in FIRMessagingTopicOperation.m mishandles confidential information on line 192. The program could compromise user privacy.The identified function mishandles confidential information. This program could compromise user privacy.
The function performSubscriptionChange() in FIRMessagingTopicOperation.m mishandles confidential information on line 162. The program could compromise user privacy.The identified function mishandles confidential information. This program could compromise user privacy.
The function performSubscriptionChange() in FIRMessagingTopicOperation.m mishandles confidential information on line 162. The program could compromise user privacy.The identified function mishandles confidential information. This program could compromise user privacy.

**Comment by morganchen12** [comment]
There's a lot of noise in this issue (for example, [the first warning](https://cs.opensource.google/firebase-sdk/firebase-ios-sdk/+/master:Crashlytics/Crashlytics/Settings/Operations/FIRCLSNetworkOperation.m;l=74?q=FIRCLSNetworkOperation) does not involve any user; it sets a constant value defined by Crashlytics to a known header field also defined by Crashlytics). Please examine the warnings and provide concrete explanations in cases where there are real privacy risks, and then file issues for those individually.
