### ISSUE TITLE
[!] Oh no, an error occurred.

### ISSUE THREAD

**Issue by Vamshi-krishna1194** [firebase/firebase-ios-sdk#6828]
Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=416%3A+unexpected+token+at+%27%7B%0A++++++%22name%22%3A+%22MLModelInterpreter%22%2C%0A++++++%22dependencies%22%3A+%7B%0A++++++++%22Firebase%2FCoreOnly%22%3A+%5B%0A%0A++++++++%5D%0A++++++%7D%2C%0A++++++%22ios%22%3A+%7B%0A++++++++%22dependencies%22%3A+%7B%0A++++++++++%22FirebaseMLModelInterpreter%22%27&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - Way to exclude paths in paths specifications in .podspec
   https://github.com/CocoaPods/CocoaPods/issues/65 [closed] [10 comments]
   14 Jun 2017

 - A Pod can have a directory as resource too
   https://github.com/CocoaPods/CocoaPods/issues/62 [closed] [1 comment]
   15 Nov 2011

 - Add more attributes to Specification
   https://github.com/CocoaPods/CocoaPods/issues/60 [closed] [1 comment]
   18 Mar 2012

and 10016 more at:
https://github.com/cocoapods/cocoapods/search?q=416%3A%20unexpected%20token%20at%20%27%7B%0A%20%20%20%20%20%20%22name%22%3A%20%22MLModelInterpreter%22%2C%0A%20%20%20%20%20%20%22dependencies%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22Firebase%2FCoreOnly%22%3A%20%5B%0A%0A%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%22ios%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22dependencies%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22FirebaseMLModelInterpreter%22%27&type=Issues&utf8=✓

[!] Smart quotes were detected and ignored in your Podfile. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.

[!] Automatically assigning platform `iOS` with version `12.0` on target `Danbro` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] Automatically assigning platform `iOS` with version `11.0` on target `DataManagerHelperRxSwift` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by ryanwilson** [comment]
Hi @Vamshi-krishna1194,

Can you please fill out the issue template provided? This looks like it's from a CocoaPods error, not a Firebase error. Without the proper error and other information that's provided in the issue template, we won't be able to make progress on the issue.

Thanks!

**Comment by paulb777** [comment]
Going to close. We can reopen with an updated template.
