### ISSUE TITLE
Facebook photoURL access token

### ISSUE THREAD

**Issue by fortmarek** [firebase/firebase-ios-sdk#6829]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0.1
  * Firebase SDK version: 6.34.0
  * Firebase Component: Auth
  * Component version: 6.0
  * Installation method: `Carthage`

#### Steps to reproduce:

1. Authenticate via Facebook with `FBSDKLoginKit`
2. After getting the access token, log in to Firebase: `FacebookAuthProvider.credential(withAccessToken: facebookAccessToken)`
3. Obtain `photoURL` from `providerData` after successfully logging in

The `photoURL` is then in the format of ` https://graph.facebook.com/{user_id}/picture` but, according to the [Facebook API documentation](https://developers.facebook.com/docs/graph-api/reference/user/picture), it should contain access token - otherwise we are not able to get the profile's profile picture. I believe this is something that should be fixed on the Firebase side - or are we expected to handle the access token manually?

**Comment by rosalyntan** [comment]
Hi @fortmarek -- Firebase does not hold on to the IDP access token, so you will have to handle the access token manually.

**Comment by fortmarek** [comment]
Ahh, OK, that makes sense - thanks for the response @rosalyntan!
