### ISSUE TITLE
FirebaseApp configuration fails after app update

### ISSUE THREAD

**Issue by ivanvecko** [firebase/firebase-ios-sdk#684]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.2
  * Firebase SDK version: 4.8.0
  * Firebase Component: Analytics, Core
  * Component version: FirebaseAnalytics 4.0.5, FirebaseCore 4.0.13

### [REQUIRED] Step 3: Describe the problem

The problem occurs on a first launch after app update (from old version of the app which did not use Firebase analytics, it used GoogleAnalytics).
When app is freshly installed the issue is not present.

#### Console output:

[Firebase/Analytics][I-ACS029010] Cannot create a URL to fetch a configuration with empty app instance ID or empty platform (app instance, platform): (nil), ios
[Firebase/Analytics][I-ACS023125] Unable to get configuration. Invalid server URL.

#### Relevant Code:

```
// Before init, notification listener is set, to listen for token/App instance refresh
// This notification is sent when app is updated
NotificationCenter.default.addObserver(self, selector: #selector(tokenRefresh), name: NSNotification.Name.InstanceIDTokenRefresh, object: nil)

// FirebaseApp init, Called on AppDelegate init
func initFirebaseWithPlist(name: String) {
        if let filePath = Bundle.main.path(forResource: name, ofType: "plist") {
            guard let fileopts = FirebaseOptions.init(contentsOfFile: filePath)
                else {
                    print("[ERROR] Failed to load \(name).plist, analytics will misbehave")
                    return
            }
            
            FirebaseApp.configure(options: fileopts)
        }
}

@objc func tokenRefresh() {
  
        if let app = FirebaseApp.app() {
           // Delete the current FirebaseApp so the new one can be created
            app.delete({ [weak self] (completion) in
                if completion {
                    let instanceID = FirebaseInstanceID.InstanceID.instanceID()
                    instanceID.getID(handler: { (newID, error) in
                        // Just to check new ID, error is not reported
                        // Call the init again, FirebaseInstace should be ok now?
                        self?.initFirebaseWithPlist(name: "Firebase")
                    })
                }
            })
        } 
 }

// 
```

**Comment by baolocdo** [comment]
How consistent is the error? Did you get it all the time? It would be really nice if we can reproduce this. Thank you.

**Comment by ivanvecko** [comment]
I did the update just before I wrote this issue and it updated to 4.0.5. Tried to update today and it updated to 4.0.7 and now it works ok. Thanks
