### ISSUE TITLE
FR: Background Thread Crashlytics Initialization

### ISSUE THREAD

**Issue by michaeleisel** [firebase/firebase-ios-sdk#6845]
### Feature proposal

* Firebase Component: Crashlytics

My recollection is that Crashlytics at some point in the past could be initialized on a background thread. However, I see that currently it's recommended to call `[FIRApp configure]` on a background thread. Considering that Crashlytics by itself can take 50ms+ during startup, I'd love to be able to initialize it on a background thread. This would also be a big advantage over other crash reporters that have a similarly high main thread delay.

**Comment by elenadoty** [comment]
Hi @michaeleisel,
We've implemented some improvements in https://github.com/firebase/firebase-ios-sdk/pull/7332 to speed up the startup time of the SDK. This doesn't move the initialization to the background thread, but should help a little with the delay.

**Comment by michaeleisel** [comment]
👍 any ballpark estimates on the reduction?

**Comment by elenadoty** [comment]
From some testing on an iPhone 7 running iOS 14.3, I saw a decrease of more than 50% in SDK start up time. Of course, this is an old phone and the improvements will definitely vary by device and application size.

**Comment by michaeleisel** [comment]
sounds great. it'd still be nice to have thread safety, but certainly less important. could close or not 🤷

**Comment by elenadoty** [comment]
I'll close this for now and reopen if there are any updates.
