### ISSUE TITLE
Suboptimal cache usage for the `check` workflow

### ISSUE THREAD

**Issue by Cyberbeni** [firebase/firebase-ios-sdk#6848]
### [REQUIRED] Step 1: Describe your environment
  GitHub Actions

### [REQUIRED] Step 2: Describe the problem
Each pull request uses its own separate cache for the check workflow

#### Steps to reproduce:
Open a pull request, it will take a long time to setup for the first time because loading from cache will miss even though the other pull requests are using the same version of swiftformat.
 
#### Relevant Code:
[Check workflow](https://github.com/firebase/firebase-ios-sdk/blob/202df4134d50a92b2149cdbc5f370eb374a284e3/.github/workflows/check.yml)
Other workflows might also be affected.

This is because of the [following restrictions](https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache).

The easiest solution is to also trigger the action when pushing to the default branch, like [this](https://github.com/Cyberbeni/TypedNotificationCenter/blob/32a5871bdd1c90177cf3f95c6a1add8b2a076adc/.github/workflows/lint.yml), so pull requests will find the cache from the default branch.

**Comment by Cyberbeni** [comment]
(Also macOS runners are pretty "expensive" for doing stuff like this, I'm pretty sure all tools needed for check work on Linux too but with proper caching, it shouldn't be that big of an issue)

**Comment by paulb777** [comment]
@Cyberbeni Thanks for the report.  Do you have more specifics on the delay times? Is the speedup worth running the check workflow on every push?

**Comment by Cyberbeni** [comment]
You only want to run the check workflow on pushing to the default branch (= merges) because that will make the cache available to all branches.
The `check` step could be skipped in this case, assuming that doesn't do anything that changes the cached directories.
And if restoring from cache is successful (and a push triggered the action), `setup check` can also be skipped as we only want to ensure the cache is kept alive in this case. (The `cache-hit` output of the cache action signals exact match for the cache key)

I'm using a GitHub Action to build SwiftFormat instead of Mint but they basically do the same thing (clone, build, export path) and cloning plus building SwiftFormat takes about 1m25s on Linux while restoring from cache takes about 2s.

[Run with successful cache restore](https://github.com/firebase/firebase-ios-sdk/runs/1316603570?check_suite_focus=true)
[Run where SwiftFormat is built inside Setup Check](https://github.com/firebase/firebase-ios-sdk/runs/1316520679?check_suite_focus=true)

**Comment by paulb777** [comment]
Thanks! I can see the difference of around a minute by comparing the first check run from a PR versus the later ones at https://github.com/firebase/firebase-ios-sdk/actions?query=workflow%3Acheck.
