### ISSUE TITLE
Target Integrity - MobileCoreServices has been renamed

### ISSUE THREAD

**Issue by gilrodar** [firebase/firebase-ios-sdk#6850]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.1
  * Firebase SDK version: 7.0.0
  * Installation method: CocoaPods
  * Firebase Component: Firestore, Storage

### [REQUIRED] Step 2: Describe the problem

After updating version 7 and trying to compile these two warnings appear.

<img width="271" alt="Captura de Pantalla 2020-10-27 a la(s) 13 37 19" src="https://user-images.githubusercontent.com/13817108/97353806-1c8c1d80-185a-11eb-97f7-4f6b0c8b40e7.png">

**Comment by paulb777** [comment]
@gilrodar Thanks for the report. I'm reproducing, but not yet sure about the right fix. According to https://developer.apple.com/documentation/coreservices?language=objc, CoreServices isn't supported until iOS 12, but we're still supporting iOS 10.

In the meantime, https://stackoverflow.com/questions/60162347/how-to-silence-xcode-11-4-warnings-about-mobilecoreservices-and-assetslibrary might be helpful.
