### ISSUE TITLE
Remove +load in GDTCCTUploader

### ISSUE THREAD

**Issue by shanksGuo** [firebase/firebase-ios-sdk#6855]
### Feature proposal

* Remove +load method in GDTCCTUploader, instead, use something like setup to do the same thing which controlled by developers.

I found +load method affect our app's launch time. see the image below, it blocked 56ms the run [GDTCCTUploader load]. so could it be possible to remove the +load?
<img width="2180" alt="Screen Shot 2020-10-28 at 17 40 31" src="https://user-images.githubusercontent.com/8662571/97419309-e081b700-1944-11eb-84a1-25b8902c734f.png">

**Comment by ryanwilson** [comment]
Thanks for the details @shanksGuo. @maksymmalyhin - can you check into what the side effects of moving the `+load` call to `+initialize` would be, or even `init`?

**Comment by maksymmalyhin** [comment]
Thank you for the report. We will consider refactoring GoogleDataTransport SDK to reduce amount of operations performed in `+load` methods. It may require some time to implement so I'm thinking of a quick fix for the particular issue you observe. 

It looks like there is a relatively expensive and not required initialization of `NSURLSession` [here](https://cs.opensource.google/firebase-sdk/firebase-ios-sdk/+/master:GoogleDataTransport/GDTCCTLibrary/GDTCCTUploader.m;l=105;drc=bde8e07844577ecc44799b82c88273ca96a93f2a) which can be deferred. I'll check this idea and post a PR if it has a positive impact.

**Comment by shanksGuo** [comment]
Thank you for your response. By the way, I cannot tell the exact effect between +load call and +initialize/init call of the same implement, but I moved lots of my own +load to launch phase or +initialize, the reduction of time cost was significant.
