### ISSUE TITLE
Including `Performance` and `Analytics` into Main target causes duplication of `GoogleUtilities` framework

### ISSUE THREAD

**Issue by jeromeDefReputation** [firebase/firebase-ios-sdk#6861]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 11.7 (11E801a)
  * Firebase SDK version: `Firebase/Crashlytics` = 4.4.0, `Firebase` = 6.30.0
  * Installation method: `CocoaPods`
  * Firebase Component: `Crashlytics`, `Performance`, `Analytics`

### [REQUIRED] Step 2: Describe the problem
Planned to deprecate Crashlytics/Fabric dependencies and updated to `Firebase/Crashlytics` by installing pod: `Firebase/Crashlytics` and encountered a `GoogleUtilities` framework issue.  The framework seems to be injecting some sort of number and appending it before the `.framework` causing it to fail at compile time.

I thought it may be a `Cocoapods` issue at first but one of our other 3rd party libraries imports to our targets just fine.

Our project has three targets (A, B and C) with C being an app extension embedded into A's target.

#### Steps to reproduce:
1) Create an app with two targets and an app extension as a third target
2) Integrate Firebase/Crashlytics, Firebase/Performance and Firebase/Analytics into (A, B) and only Firebase/Crashlytics into C (App extension)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

See attached screenshot: you'll see that instead of `GoogleUtilities` as a target in the Pods file, you see `GoogleUtilities-ac14cd06`
<img width="257" alt="GoogleUtilities" src="https://user-images.githubusercontent.com/45769254/97509709-4586de00-1940-11eb-860b-399512a5426a.png">

**Comment by paulb777** [comment]
This looks like a variation of https://github.com/CocoaPods/CocoaPods/issues/8206 and fundamentally an unaddressed Xcode bug.  The workaround is to make sure that all targets have the same GoogleUtilities subset of subspecs by explicitly adding the missing ones to each target. You should be able to see the details of what's needed by examining the `Podfile.lock`. 

More information at the [CocoaPods issue](https://github.com/CocoaPods/CocoaPods/issues/8206).

**Comment by jeromeDefReputation** [comment]
Thanks for the fast response @paulb777 , so tl;dr is include redundant dependencies in the targets.

**Comment by paulb777** [comment]
Yep. I'll close this here in favor to the CocoaPods issue, but feel free to continue to discuss with any additional questions or comments.
