### ISSUE TITLE
Auth not Shared Correctly with App Groups

### ISSUE THREAD

**Issue by ccjernigan** [firebase/firebase-ios-sdk#6876]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.1
  * macOS version: 10.15.7
  * Firebase SDK version: 7.0.0
  * Installation method: Swift Package
  * Firebase Component: Auth

### [REQUIRED] Step 2: Describe the problem
Firebase Auth is not properly shared between multiple bundles within the same app group.

I have a macOS app where the main app and a second process (in the same app bundle) share the same app group.  After the main app signs in, the second process launches via `SMLoginItemSetEnabled` as part of the setup process.  When the second process touches Firebase Auth, a system password prompt appears to grant keychain access (for a keychain item named for my API key).

#### Steps to reproduce:
1. Create an app that uses app groups and has a sub-bundle that runs in a second process
2. Sign into Firebase with the main app (call `Auth.auth().useUserAccessGroup(AppGroupId)` first)
3. Launch the second process, which should call `Auth.auth().useUserAccessGroup(AppGroupId)` and listens for auth changes `Auth.auth().addStateDidChangeListener({ (_, user) in
            ...
        })` 

Results:
Actual: Second process triggers a system keychain dialog asking for a password.
Expected: No keychain dialog should appear, since these are using a shared app group

I realize that macOS is "community supported" although this seems to be a bug that should be resolved to better support app extensions and other multiprocess use cases.

**Comment by malcolmdeck** [comment]
Hey there! I've filed b/172260275 to track this issue internally.

**Comment by ZComwiz** [comment]
@malcolmdeck could this be related to why on the Mac I am getting a token mismatch but on iOS with the same bundleID— it works fine when using Auth() for phone login?

**Comment by OGmetamonkey** [comment]
Did anything come of this? When you say "shared app group", does that include an extension within the main app? If so, I'm having the same issue.[]( https://stackoverflow.com/questions/68199352/ios-extension-authentication-in-firestore)

**Comment by OGmetamonkey** [comment]
> Hey there! I've filed b/172260275 to track this issue internally.

Any way you can tell me how I track this bug #?

**Comment by kamilpowalowski** [comment]
@OGmetamonkey I have the same issue in the macOS extension. Did you manage to solve it?

**Comment by rosalyntan** [comment]
Should be fixed in #9102.
