### ISSUE TITLE
Crashlytics upload-symbols

### ISSUE THREAD

**Issue by thomtomdup** [firebase/firebase-ios-sdk#6877]
### Step 1: Describe your environment

  * Xcode version: _12.1
  * Firebase SDK version: 7
  * Installation method: CocoaPods 
  * Firebase Component: Crashlytics 

### Step 2: Describe the problem
 Since today, i have this error :
`"
Validating build environment for Crashlytics...`
`Validation succeeded. Exiting because upload-symbols was run in validation mode
"`

I have also in the bubble info this message : 
`'Validation succeeded. Exiting because upload-symbols was run in validation mode 01/01/4001 01:OO'`

The run script has not changed since a long time and everything  worked fine.
I updated pods but nothing change.

The script is :
`"${PODS_ROOT}/FirebaseCrashlytics/run"`
`"${PODS_ROOT}/FirebaseCrashlytics/upload-symbols" -gsp "${PROJECT_DIR}/Info/GoogleService-Info.plist" -p ios "${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}"`

#### Question :
Has something changed for this or not ?
Thank you in advance.
Regards.

**Comment by thomtomdup** [comment]
I tried it to compile and waiting it. It's take 1022s to validate the build.

**Comment by wojczitsu** [comment]
any solution

**Comment by morganchen12** [comment]
@samedson, do you know what's causing the `validation mode` log?

**Comment by youweit** [comment]
Got this message too, I built the target with other build configuration instead of `Release`.

**Comment by julestburt** [comment]
Seeing the same issue also.

**Comment by elenadoty** [comment]
We've recently updated this validation log message to clarify the behavior, but this is expected behavior. The tool will run validation before executing in order to save time, and prints the validation message if successful before moving on to the upload steps.
