### ISSUE TITLE
Project Not Building GDTCORUploader.h: No such file found in directory (in target 'GoogleDataTransport' from project 'Pods')

### ISSUE THREAD

**Issue by halinebr** [firebase/firebase-ios-sdk#6879]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.1
  * Firebase SDK version: just updated to 7.0.0 from 6.34.0 when encountered this problem
  * Installation method: CocoaPods 
  * Firebase Component: GoogleDataTransport

### [REQUIRED] Step 2: Describe the problem
Updated all pods - GoogleDataTransport pod (which I think is implicitly added from some other Firebase dependency, not in my podfile) was updated from 7.5.0 to 8.0.0 
When I go to build my project - I receive the error: .../Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Public/GoogleDataTransport/GDTCORUploader.h: No such file or directory (in target 'GoogleDataTransport' from project 'Pods')

#### Steps to reproduce:

What happened? How can we make the problem occur?

I have Firebase pods
Firebase/Core
Firebase/Auth
Firebase/Database
Firebase/Messaging
Firebase/DynamicLinks
Firebase/Performance
Firebase/Analytics

in my podfile

other google related pods:
GoogleSignIn
GoogleMaps
GooglePlaces

This was not an issue until I updated my pods.

**Comment by paulb777** [comment]
@halinebr Sorry about the issue. This is likely the result of invalid Xcode project state. Please try `pod deintegrate` and then `pod update` again.

**Comment by halinebr** [comment]
Ultimately did that, ran into a bunch of weird Lexical/Preprocessor issues - I then updated Cocoapods to the latest version, and now all issues are gone I am able to build and run my project as expected. Thank you!
