### ISSUE TITLE
InstanceID token is invalid when saving test devices in Firebase ABTesting

### ISSUE THREAD

**Issue by seviu** [firebase/firebase-ios-sdk#6881]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.1 (12A7403)
  * Firebase SDK version: 6.32.2
  * Installation method: CocoaPods
  * Firebase Component: RemoteConfig, ABTesting

### [REQUIRED] Step 2: Describe the problem

I cannot add test devices for my AB testing experiments / Manage test devices. I get InstanceID token is invalid.

#### Steps to reproduce:

Use code snipped to retrieve the Instance ID Token (see next section) saving it into the Pasteboard so that I can easily fetch it form test devices / simulator.

Go in firebase console and enter. Tried to enter installationId  ìd` or token `token.authToken`. I get the following error:

<img width="586" alt="Screenshot 2020-11-02 at 10 25 10" src="https://user-images.githubusercontent.com/686080/97853572-8e4fe580-1cf8-11eb-9063-f0020024ff42.png">

#### Relevant Code:

```
Installations.installations().authTokenForcingRefresh(true) { token, error in
  if let error = error {
    print("Error fetching token: \(error)")
    return
  }
  guard let token = token else { return }
  Installations.installations().installationID { id, _ in
    UIPasteboard.general.string = "Auth token: \(token.authToken)\nExpiration date: \(token.expirationDate)\nInstallation id: \(id ?? "invalid")"
  }
}
```

**Comment by ryanwilson** [comment]
Hi @seviu, 

Are you pasting the entire string there? Based on your code snippet it looks like your clipboard is getting a string that includes "Auth token: ..... Expiration date " as well as the actual token. If you still want to use the clipboard and clipboard sync from the simulator, you could try changing the pasteboard line to:

```
UIPasteboard.general.string = id ?? "invalid"
```

**Comment by seviu** [comment]
I am not passing the whole string only one or the other field, I just copy everything to the clickboard

**Comment by seviu** [comment]
Attached screenshot

<img width="1236" alt="Screenshot 2020-11-02 at 15 03 41" src="https://user-images.githubusercontent.com/686080/97876922-c5d08900-1d1c-11eb-8f65-8878864cec7a.png">

**Comment by maksymmalyhin** [comment]
@seviu Could you please try a workaround suggested at the [comment](https://github.com/firebase/firebase-ios-sdk/issues/6892#issuecomment-721795650).

**Comment by seviu** [comment]
I will thanks!

**Comment by seviu2** [comment]
I can add the Instance ID now to the web UI, but I cannot control the variants. With the current implementation remote config is always returning the control group despite adding that specific device to a variant.

I need to make more tests but it might be that InstanceId is not good enough:

```
#if DEBUG
			InstanceID.instanceID().instanceID { (result, _) in
				if let result = result {
					UIPasteboard.general.string = result.token
				}
			}
#endif
```

**Comment by ivanesi** [comment]
Have the same issue. Could add tokens, and after a while (maybe two hours later) couldn't do it

**Comment by seviu** [comment]
Hei google bot, what more information is needed? I can add now tokens with InstanceID.instanceID but the targeting does not work, so I cannot decide which experiment my device is in

**Comment by ivanesi** [comment]
I confirm. Sometimes targeting doesn't work, and the same token can be invalid on existing experiment and valid for new.

**Comment by seviu** [comment]
ping so that this ticket does not die. Targeting does not work at all using the deprecated API

**Comment by paulb777** [comment]
We're continuing to investigate. I'm going to close this issue to consolidate discussion into the duplicate #6892
