### ISSUE TITLE
FR: Add RemoteConfig Decoder and Encoder

### ISSUE THREAD

**Issue by lorenzofiamingo** [firebase/firebase-ios-sdk#6883]
### Feature proposal

* Firebase Component: RemoteConfig

```swift
struct Configuration: Codable {
        
    var signinMethods: [String]
}
```
## Decoder
Would be great to have a Decoder like `Firestore.Decoder` to do something like this:
```swift
let remoteConfig = RemoteConfig.remoteConfig()
let decoder = RemoteConfig.Decoder()
let configuration = try! decoder.decode(Configuration.self, from: remoteConfig)
```
`RemoteConfig.Decoder` should be able to decode 'RemoteConfigValue' as well:
```swift
let remoteConfigValue = RemoteConfig.remoteConfig().configValue(forKey: "authentication")
let decoder = RemoteConfig.Decoder()
let configuration = try! decoder.decode(Configuration.self, from: remoteConfigValue)
```
## Encoder
Would be great to have also an Encoder to set defaults:

```swift
let remoteConfig = RemoteConfig.remoteConfig()
let configuration = Configuration(signiInMethods: ["email"])
let encoder = RemoteConfig.Encoder()
let defaults = try! encoder.encode(configuration)
remoteConfig.setDefaults(defaults)
```
or better, like for Firestore `ref.setValue(from: Encodable)`
```swift
let remoteConfig = RemoteConfig.remoteConfig()
let configuration = Configuration(signiInMethods: ["email"])
try! remoteConfig.setDefaults(from: configuration)
```

**Comment by paulb777** [comment]
This quickstart sequence should transform to a single line with Codable - https://github.com/firebase/quickstart-ios/blob/6c420f893cea50d319931451d9fe110c534f9fcf/config/ConfigExample/RemoteConfigViewController.swift#L128-L151

**Comment by paulb777** [comment]
#9084 now has an initial implementation of the 2nd(RCValue JSON decoding) and 3rd(setDefaults from Encodable) requests.

I'm not sure about the first one. It seems that RC does not have any APIs to get the full configuration, but I'm not sure why that is.  So I'm not sure that we should add only a Codable version to do that.

I suppose a workaround is for an app to do everything via a single JSON entry?

@karenyz or anyone else: Any thoughts/guidance on the above questions?

**Comment by paulb777** [comment]
I talked with the RC team and it turns out that Android already has an API that returns the full config as a dictionary. See https://firebase.google.com/docs/reference/android/com/google/firebase/remoteconfig/FirebaseRemoteConfig#getAll%28%29

So it looks like we should implement a `getAll` for Apple and then we can implement the third Codable API requested here on top of it.

**Comment by paulb777** [comment]
After more thought, a `getAll` API wouldn't be too useful for Objective C without type safety so I did a direct Swift decoder implementation. Details in #9084 which now has implementations for all three of the requests.
