### ISSUE TITLE
Messaging.messaging().token gives a request timed out in China 

### ISSUE THREAD

**Issue by Koronaa** [firebase/firebase-ios-sdk#6887]
### Environment

  * Xcode version: 12.1
  * Firebase SDK version: 7.0.0
  * Installation method: `CocoaPods`
  * Firebase Component: Messaging

### Problem

We have used following code snippet (as given in the doc) to get the FCM Token,

```
Messaging.messaging().token { token, error in
  if let error = error {
    print("Error fetching FCM registration token: \(error)")
  } else if let token = token {
    print("FCM registration token: \(token)")
  }
}
```

And this works as expected in US,SL, etc but it gives the following error for all the iOS devices in China,

```
Error fetching FCM registration token: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2103, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <22F1AB3C ...>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
"LocalDataTask <22F1AB3C ...>.<1>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://device-provisioning.googleapis.com/checkin, NSErrorFailingURLKey=https://device-provisioning.googleapis.com/checkin, _kCFStreamErrorDomainKey=4}
```

Appreciate any insights on this...

**Comment by rizafran** [comment]
Hi @Koronaa, sorry for the late reply here. May I know if you're still encountering an issue in getting the FCM token for all the devices in China? If not, have you tried it using VPN in order to isolate the issue?
