### ISSUE TITLE
FR: RemoteConfig watchOS support

### ISSUE THREAD

**Issue by chwo** [firebase/firebase-ios-sdk#6888]
### Feature proposal

* Firebase Component: RemoteConfig 
* Follow-up of https://github.com/firebase/firebase-ios-sdk/issues/269#issuecomment-568772670

### Motivation and Context
The Remote Config with its values serves as a source of truth for an app so it would be very useful if it were available on all mobile platforms that the app supports (including watchOS). Without watchOS support one have to built custom infrastructure to get the Remote Config values to an Apple Watch app and keep them in sync. Furthermore standalone Apple Watch apps cannot use Remote Config currently. 

### Outstanding issues 
* Are there technical limitations which block the implementation?
  * e.g. Is there possibly a dependency to #4557?  Because the [iOS Getting Started Guide](https://firebase.google.com/docs/remote-config/use-config-ios) mentions that Firebase Analytics is required for Remote Config in order to function fully.

> Note: When installing the iOS SDK, you have the option of adding the dependency for Analytics. Analytics is required for Remote Config's conditional targeting of app instances to user properties, audiences, and Firebase Predictions.

**Comment by chwo** [comment]
If I followed the release notes of [Version 7.7.0](https://firebase.google.com/support/release-notes/ios#version_770_-_february_23_2021) correctly this issue is partly resolved:

- https://github.com/firebase/firebase-ios-sdk/pull/7481 added watchOS support ✔️ 
- but Analytics watchOS support is still missing (which is required for RemoteConfig in order to function completely)

// cc @chliangGoogle

**Comment by chliangGoogle** [comment]
@chwo that is correct, Analytics is currently not available in watchOS so any analytics related features in remote config are still missing.

**Comment by ryanwilson** [comment]
I'm going to close this FR since there's no work required on the Remote Config side of things for watchOS support, and we have a FR for FirebaseAnalytics support at #4557 which would light up these missing features.

Thanks!
