### ISSUE TITLE
Firebase Auth Token showing invalid when entered in Firebase ABTesting test device

### ISSUE THREAD

**Issue by samarth220194** [firebase/firebase-ios-sdk#6892]
**[REQUIRED] Step 1: Describe your environment**

- Xcode version: Version 11.6 (11E708)
- Firebase SDK version: 6.27.0
- Firebase Component: RemoteConfig / ABTesting
- Installation method: file

**[REQUIRED] Step 2: Describe the problem**

- Steps to reproduce:
- Use code snipped to retrieve the Auth Token (see next section)
- Go in firebase console and enter this Instance ID Token in Manage test device for an A/B test.

See the following error:
<img width="442" alt="Screenshot 2020-11-04 at 3 55 32 PM" src="https://user-images.githubusercontent.com/17960987/98100474-e7657800-1eb6-11eb-92c9-8c83b80d6426.png">

Relevant Code:
 
     Installations.installations().authToken(completion: { (token, error) in
            if let error = error {
                print("Error fetching token: \(error)")
                return
            }
            guard let token = token else { return }
            print("Installation auth token: \(token.authToken)")
        })

**Comment by maksymmalyhin** [comment]
@samarth220194 Sorry you experience the issue. It looks like a bug on the Firebase Console side that still does validation against the old Firebase Instance ID token format not accepting the new Firebase Installations token. I'll pass the issue to the console team. 

In the meanwhile as a workaround you may install FirebaseInstanceID SDK for debug build variant only to get the token in the old format:
- [Podfile example](https://github.com/firebase/quickstart-ios/blob/e29db33a6b4b9fb5d217c3e53d9c50cb55a14621/abtesting/Podfile#L10)
- [get token example](https://github.com/firebase/quickstart-ios/blob/e29db33a6b4b9fb5d217c3e53d9c50cb55a14621/abtesting/ABTestingExample/ViewController.swift#L93)

**Comment by maksymmalyhin** [comment]
cc @egilmorez @morganchen12

**Comment by maksymmalyhin** [comment]
Tracked internally at b/172454592

**Comment by samarth220194** [comment]
@maksymmalyhin This happens when I edited a running experiment, and post that I tried to add new test devices.
It doesn't happen in a newly created experiment.
I hope this would help in further debugging.

**Comment by tgpsantos** [comment]
@maksymmalyhin is this happening with Android devices also? I'm getting a [similar issue in the Flutter plugin](https://github.com/FirebaseExtended/flutterfire/issues/4016). Tbh this was the first time I tried it so I might be missing something,

**Comment by maksymmalyhin** [comment]
> @maksymmalyhin is this happening with Android devices also? I'm getting a [similar issue in the Flutter plugin](https://github.com/FirebaseExtended/flutterfire/issues/4016). Tbh this was the first time I tried it so I might be missing something,

@tgpsantos As this is a console issue, I think yes, it most likely relevant for Android apps as well.

**Comment by kivraoskar** [comment]
I have the same problem as well. Is there any updates to this? 

> @maksymmalyhin This happens when I edited a running experiment, and post that I tried to add new test devices.
> It doesn't happen in a newly created experiment.
> I hope this would help in further debugging.

Tried making a completely new experiment but it still did not work for me

**Comment by kivraoskar** [comment]
> @samarth220194 Sorry you experience the issue. It looks like a bug on the Firebase Console side that still does validation against the old Firebase Instance ID token format not accepting the new Firebase Installations token. I'll pass the issue to the console team.
> 
> In the meanwhile as a workaround you may install FirebaseInstanceID SDK for debug build variant only to get the token in the old format:
> 
> * [Podfile example](https://github.com/firebase/quickstart-ios/blob/e29db33a6b4b9fb5d217c3e53d9c50cb55a14621/abtesting/Podfile#L10)
> * [get token example](https://github.com/firebase/quickstart-ios/blob/e29db33a6b4b9fb5d217c3e53d9c50cb55a14621/abtesting/ABTestingExample/ViewController.swift#L93)

Just tried this out, and it didn't solve the problem for me. Still get invalid token error.

**Comment by seviu** [comment]
@kivraoskar As I explained in https://github.com/firebase/firebase-ios-sdk/issues/6892#issuecomment-721795650 using the old format works in the firebase console, but to no effect because the device does not get the experiment I set.

**Comment by tgpsantos** [comment]
> 
> 
> > @maksymmalyhin is this happening with Android devices also? I'm getting a [similar issue in the Flutter plugin](https://github.com/FirebaseExtended/flutterfire/issues/4016). Tbh this was the first time I tried it so I might be missing something,
> 
> @tgpsantos As this is a console issue, I think yes, it most likely relevant for Android apps as well.

Thanks! Is there any issue/PR where I can track the fix release? Or ETA?

**Comment by paulb777** [comment]
@tgpsantos There is active investigation and we'll follow up here when there's something to report.

**Comment by maksymmalyhin** [comment]
@tgpsantos @samarth220194 Could you please try it again with a fresh Firebase Installations Auth Token? The token has expiration period around 1 week. Currently the expired token may be a reason of validation failure.

**Comment by samarth220194** [comment]
@maksymmalyhin I am working on some other project for now. Won't be able to help you with this right now. @tgpsantos can you please re-try and help @maksymmalyhin with the update?

**Comment by brandtnewww** [comment]
I just tested it with the current react-native-firebase package by Invertase (https://github.com/invertase/react-native-firebase) and with the AuthToken, it works. I get the token and on refreshing the device, I get the correct a/b test variant.

**Comment by kivraoskar** [comment]
@maksymmalyhin I just tried again with the Installations Auth token and it is still not working for me. 

Still getting `Error saving test devices: Instance ID token is invalid`

**Comment by sknopf** [comment]
@kivraoskar 👋 Firebase dev here. A few quick checks:
- Did you try generating a fresh token and re-registering it with ABT? Installation Auth Tokens expire after 7 days.
- Do you have multiple Firebase projects you're managing? If so, please double check you're registering with the same project your app is configured to.

Validation errors we commonly see often fall into one of those two categories. If those don't apply, let us know and we'd be happy to look into this further.

**Comment by kivraoskar** [comment]
@sknopf Sorry for slow answer. Been away on holiday vacation last two weeks. 

Just checked again and made sure I had the correct project selected and created a fresh ABT token via `Installations` (same code as mentioned in the first post). I'm unfortunately still getting the same error.
