### ISSUE TITLE
SPM duplicate symbol ___gcov_flush with GCC_INSTRUMENT_PROGRAM_FLOW_ARCS and GCC_GENERATE_TEST_COVERAGE_FILES

### ISSUE THREAD

**Issue by alexruperez** [firebase/firebase-ios-sdk#6894]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0.1 (12A7300)
  * Firebase SDK version: 7.0.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: Analytics

#### Steps to reproduce:

xcodebuild "-project" "....xcodeproj" "-scheme" "..." "clean" "build" "COMPILER_INDEX_STORE_ENABLE=NO" "test" "GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES" "GCC_GENERATE_TEST_COVERAGE_FILES=YES"

#### Relevant Code:

❌  duplicate symbol '___gcov_flush' in
> FirebaseAnalyticsTarget.o
> Firebase.o
❌  duplicate symbol '___gcov_flush' in
> FirebaseAnalyticsTarget.o
> nanopb.o
❌  duplicate symbol '___gcov_flush' in
> FirebaseAnalyticsTarget.o
> GoogleDataTransport.o
❌  duplicate symbol '___gcov_flush' in
> FirebaseAnalyticsTarget.o
> GoogleUtilities_Environment.o
❌  duplicate symbol '___gcov_flush' in
> FirebaseAnalyticsTarget.o
> FBLPromises.o
❌  duplicate symbol '___gcov_flush' in
> FirebaseAnalyticsTarget.o
> GoogleUtilities_Logger.o
❌  duplicate symbol '___gcov_flush' in
> FirebaseAnalyticsTarget.o
> FirebaseCoreDiagnostics.o
❌  duplicate symbol '___gcov_flush' in
> FirebaseAnalyticsTarget.o
> FirebaseCore.o
❌  duplicate symbol '___gcov_flush' in
> FirebaseAnalyticsTarget.o
> GoogleUtilities_UserDefaults.o
❌  duplicate symbol '___gcov_flush' in
> FirebaseAnalyticsTarget.o
> FirebaseInstallations.o
❌  duplicate symbol '___gcov_flush' in
> FirebaseAnalyticsTarget.o
> GoogleUtilities_NSData.o
❌  duplicate symbol '___gcov_flush' in
> FirebaseAnalyticsTarget.o
> GoogleUtilities_Reachability.o
❌  duplicate symbol '___gcov_flush' in
> FirebaseAnalyticsTarget.o
> GoogleUtilities_Network.o
❌  duplicate symbol '___gcov_flush' in
> FirebaseAnalyticsTarget.o
> GoogleUtilities_AppDelegateSwizzler.o
❌  duplicate symbol '___gcov_flush' in
> FirebaseAnalyticsTarget.o
> GoogleUtilities_MethodSwizzler.o
❌  duplicate symbol '___gcov_flush' in
> FirebaseAnalyticsTarget.o
> FirebaseAnalyticsWrapper.o
❌  duplicate symbol '___gcov_flush' in
> libclang_rt.profile_iossim.a(GCDAProfiling.c.o)
> FirebaseAnalyticsTarget.o
❌  duplicate symbol '___gcov_flush' in
> libclang_rt.profile_iossim.a(GCDAProfiling.c.o)
> Firebase.o
❌  duplicate symbol '___gcov_flush' in
> libclang_rt.profile_iossim.a(GCDAProfiling.c.o)
> nanopb.o
❌  duplicate symbol '___gcov_flush' in
> libclang_rt.profile_iossim.a(GCDAProfiling.c.o)
> GoogleDataTransport.o
❌  duplicate symbol '___gcov_flush' in
> libclang_rt.profile_iossim.a(GCDAProfiling.c.o)
> FBLPromises.o
❌  duplicate symbol '___gcov_flush' in
> libclang_rt.profile_iossim.a(GCDAProfiling.c.o)
> GoogleUtilities_Environment.o
❌  duplicate symbol '___gcov_flush' in
> libclang_rt.profile_iossim.a(GCDAProfiling.c.o)
> GoogleUtilities_Logger.o
❌  duplicate symbol '___gcov_flush' in
> libclang_rt.profile_iossim.a(GCDAProfiling.c.o)
> FirebaseCoreDiagnostics.o
❌  duplicate symbol '___gcov_flush' in
> libclang_rt.profile_iossim.a(GCDAProfiling.c.o)
> FirebaseCore.o
❌  duplicate symbol '___gcov_flush' in
> libclang_rt.profile_iossim.a(GCDAProfiling.c.o)
> GoogleUtilities_UserDefaults.o
❌  duplicate symbol '___gcov_flush' in
> libclang_rt.profile_iossim.a(GCDAProfiling.c.o)
> FirebaseInstallations.o
❌  duplicate symbol '___gcov_flush' in
> libclang_rt.profile_iossim.a(GCDAProfiling.c.o)
> GoogleUtilities_NSData.o
❌  duplicate symbol '___gcov_flush' in
> libclang_rt.profile_iossim.a(GCDAProfiling.c.o)
> GoogleUtilities_Reachability.o
❌  duplicate symbol '___gcov_flush' in
> libclang_rt.profile_iossim.a(GCDAProfiling.c.o)
> GoogleUtilities_Network.o
❌  duplicate symbol '___gcov_flush' in
> libclang_rt.profile_iossim.a(GCDAProfiling.c.o)
> GoogleUtilities_AppDelegateSwizzler.o
❌  duplicate symbol '___gcov_flush' in
> libclang_rt.profile_iossim.a(GCDAProfiling.c.o)
> GoogleUtilities_MethodSwizzler.o
❌  duplicate symbol '___gcov_flush' in
> libclang_rt.profile_iossim.a(GCDAProfiling.c.o)
> FirebaseAnalyticsWrapper.o

**Comment by paulb777** [comment]
It looks like this known Xcode issue - [https://developer.apple.com/forums/thread/663007](https://developer.apple.com/forums/thread/663007).

I see the issue still occurring in Xcode 12.2 beta 3.

**Comment by paulb777** [comment]
Going to close here since this is an Xcode issue.
