### ISSUE TITLE
+[FIRApp registerInternalLibrary:withName:] take too much time

### ISSUE THREAD

**Issue by shanksGuo** [firebase/firebase-ios-sdk#6902]
### Feature proposal

*   FIRApp: remove +load or reduce the time cost of [FIRApp registerInternalLibrary:withName:] 

As image shown below, [FIRApp registerInternalLibrary:withName:]  in App launch Initializing phase take 78ms, it is too much for our App launch! So, could you optimize this. 

Wish you accept this suggestion!
<img width="2407" alt="Screen Shot 2020-11-05 at 13 43 25" src="https://user-images.githubusercontent.com/8662571/98202756-a3817a00-1f6d-11eb-893c-2568d5b9715a.png">

**Comment by shanksGuo** [comment]
Sadlly, according to my  multi tests, the block time can be up to 100ms -_-

**Comment by shanksGuo** [comment]
The time cost is very important to our App, hope you can handle this ASAP. Thanks in advance!

**Comment by maksymmalyhin** [comment]
@shanksGuo Thank you for the detailed report pointing out to the exact place that causes issue for your application! We implemented some optimizations to avoid the slow part running from `+load` and running it from in a background queue. 

Unfortunately it's a bit too late to include the change to the next release, so it'll be include the the release after. In the meanwhile we will appreciate your feedback if you could test the #6919 changes from the branch.

**Comment by shanksGuo** [comment]
@maksymmalyhin Thank you. By the way, I have a question, I'm on release-7.0 now, if I want to fetch the code optimized, which branch can I use?

**Comment by maksymmalyhin** [comment]
@shanksGuo The changes have been merged to `master`.

**Comment by shanksGuo** [comment]
@maksymmalyhin Thank you, after checkout lastest code, it has been optimized.

**Comment by maksymmalyhin** [comment]
@shanksGuo Thank you for testing on you end!
