### ISSUE TITLE
Crashlytics causes SwiftUI to dismiss the sheet view the first time it is presented. 

### ISSUE THREAD

**Issue by paleksandrs** [firebase/firebase-ios-sdk#6908]
###  Step 1: Describe your environment

  * Xcode version: 12.1
  * iPhone running iOS 14.0.1 and 14.1
  * Firebase SDK version: 7.0.0
  * Installation method: CocoaPods
  * Firebase Component: Crashlytics

### Step 2: Describe the problem

After adding Crashlytics pod to the project, sheet view gets dismissed **first** time it is opened.

#### Steps to reproduce:

1. Create empty Xcode App project and set Deployment to iOS 14:
2. Add code:
```
struct ContentView: View {
   
    var body: some View {
       
        NavigationView {
            NavigationLink(destination: DetailsView()) {
                Text("Open Details View")
            }
        }
        .navigationViewStyle(StackNavigationViewStyle())
    }
}

struct DetailsView: View {
   
    @State var sheetIsPresented: Bool = false
   
    var body: some View {
        VStack {
            Button("Open") {
                sheetIsPresented.toggle()
            }
        }.sheet(isPresented: $sheetIsPresented, content: {
            SheetView()
        })
    }
}

struct SheetView: View {
   
    var body: some View {
        Color.red
    }
}
```
4. Run the app on a device (works on simulator) and swiftly navigate to details view and press on the button to open the sheet view.  Sheet view is opened and remains on the screen.

5. Install `Firebase/Crashlytics` using pods.
```
platform :ios, '14.0'
target 'SampleApp' do
  use_frameworks!
    pod 'Firebase/Crashlytics'
end
```
7. Run the app on a device and swiftly navigate to Details view and press on the button to open the sheet view.

Expected: Sheet should open and remain on the screen.
Actual: Sheet is opened and dismissed the same moment.  All future taps work as expected, the sheet is opened and remains on the screen.

Removing  `.navigationViewStyle(StackNavigationViewStyle())` everything works as expected.

**Comment by morganchen12** [comment]
This is a really interesting bug report. I can't think of any code in Crashlytics that would specifically trigger to dismiss a SwiftUI view, but only on the first presentation of that view. Do you have any other Firebase dependencies installed? cc @samedson

**Comment by samedson** [comment]
Yeah at first thought there's nothing in Crashlytics that would affect this, but maybe there's some sort of failure happening behind the scenes that's not visible?

Would you be able to reproduce this without Crashlytics installed (but keeping the rest of Crashlytics' dependencies)?

**Comment by paleksandrs** [comment]
@samedson the same thing happens if 'Firebase/Analytics' pod is used.

**Comment by paulb777** [comment]
@paleksandrs Thanks. What if only 'FirebaseCore' is used?

**Comment by paleksandrs** [comment]
Although after initial testing this bug looked like it was connected to the Firebase pods, after doing more testing I found out that I can also reproduce it without using pods (maybe not so regularly as with pods installed).

**Comment by paulb777** [comment]
OK, thanks for the follow up. I'll close since it sounds unlikely to be a Firebase issue. It might be better to start a discussion on an Apple forum. Feel free to share a link and/or continue the discussion here.
