### ISSUE TITLE
Update documentation about stack traces customizations

### ISSUE THREAD

**Issue by 7yon** [firebase/firebase-ios-sdk#6916]
### Feature proposal

- Firebase Component: Crashlytics

Referring to #5975  `StackFrame` has new init method `StackFrame(address: ...)`

Please add this information to https://firebase.google.com/docs/crashlytics/customize-crash-reports?authuser=0&platform=ios

**Comment by elenadoty** [comment]
Hi @7yon , 
This update should be rolling out soon. 
Thanks for bringing it to our attention!
