### ISSUE TITLE
How to use auth emulator in iOS?

### ISSUE THREAD

**Issue by NortromInsanlyDev** [firebase/firebase-ios-sdk#6918]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.6
  * Firebase SDK version: 7.0.0
  * Installation method: CocoaPods
  * Firebase Component: Auth

### [REQUIRED] Step 2: Describe the problem
Hello. I'd like to use firebase emulators for development. I've configured the code for it as described in the document and run emulators.

#### Steps to reproduce:

Unable to log in using the emulator.

Log: Task <C2C30257-D19E-4E4F-A133-530344761CF5>.<1> finished with error [-1004] Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo={_kCFStreamErrorCodeKey=61, NSUnderlyingError=0x282f6a100 {Error Domain=kCFErrorDomainCFNetwork Code=-1004 "(null)" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <C2C30257-D19E-4E4F-A133-530344761CF5>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <C2C30257-D19E-4E4F-A133-530344761CF5>.<1>"
), NSLocalizedDescription=Could not connect to the server., NSErrorFailingURLStringKey=http://localhost:9099/www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key=[API_KEY], NSErrorFailingURLKey=http://localhost:9099/www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key=[API_KEY], _kCFStreamErrorDomainKey=1}
Network error (such as timeout, interrupted connection or unreachable host) has occurred.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        FirebaseApp.configure()
        Auth.auth().useEmulator(withHost:"localhost", port:9099)
        let settings = Firestore.firestore().settings
        settings.host = "localhost:8080"
        settings.isPersistenceEnabled = false
        settings.isSSLEnabled = false
        Firestore.firestore().settings = settings
       
        return true
    }
```

**Comment by morganchen12** [comment]
Can you double check the port you're running the Auth emulator on?

**Comment by NortromInsanlyDev** [comment]
> Can you double check the port you're running the Auth emulator on?

Thanks for your reply. The port is 8080 exactly.

**Comment by rosalyntan** [comment]
Hi @NortromInsanlyDev -- from the error, it looks like your app is unable to connect to the emulator instance. A couple questions to help debug:

1. Can you confirm that you've started up the emulator with the `firebase emulators:start` command?
2. Are you running your app on a physical device, or using the iOS simulator? If you're running the emulator on your laptop's localhost and your application on a physical iOS device, you'll need to set the emulator host to be your laptop's IP address instead of localhost.
3. Are you able to connect to the other emulators (i.e. the Firestore, Realtime Database, Cloud Functions emulators)?

One other thing to check is to make sure you've allowed unencrypted (http://) connections in your Info.plist file.

**Comment by NortromInsanlyDev** [comment]
> Hi @NortromInsanlyDev -- from the error, it looks like your app is unable to connect to the emulator instance. A couple questions to help debug:
> 
> 1. Can you confirm that you've started up the emulator with the `firebase emulators:start` command?
> 2. Are you running your app on a physical device, or using the iOS simulator? If you're running the emulator on your laptop's localhost and your application on a physical iOS device, you'll need to set the emulator host to be your laptop's IP address instead of localhost.
> 3. Are you able to connect to the other emulators (i.e. the Firestore, Realtime Database, Cloud Functions emulators)?
> 
> One other thing to check is to make sure you've allowed unencrypted (http://) connections in your Info.plist file.

Hi @rosalyntan 
Sorry for replying late.
1. Yes
2. Used iPhone not simulator. I tried with both "localhost" and Iocal IP address. 
3. Didn't try to connect to other ones. Will try them.

The last thing: yes, of course.
Thanks.
