### ISSUE TITLE
SPM: unsafe build flags

### ISSUE THREAD

**Issue by weakfl** [firebase/firebase-ios-sdk#6923]
### Describe your environment

  * Xcode version: 12.1
  * Firebase SDK version: 7.0.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: Core

### Describe the problem

After switching from the `7.0-spm-beta` branch to version 7.0.0, package loading fails with `the target 'gRPC-Core' in product 'gRPC-cpp' contains unsafe build flags`. Reverting to the beta branch resolves the issue.

#### Steps to reproduce:

Switch from beta branch to 7.0.0 version and try to build.

**Comment by paulb777** [comment]
@weakfl I suspect something in the Xcode state is stale. In Xcode do, `File` -> `Swift Packages` -> `Reset Package Caches`.

The issue you're describing was resolved before the 7.0.0 tag with #6860 and https://github.com/firebase/grpc-SwiftPM/commit/91b62619e6c83bc5f1b99d9d60fe46b2862d3a5a

**Comment by weakfl** [comment]
Worked, thanks @paulb777
