### ISSUE TITLE
Unable to Build for Mac if Analytics target is added

### ISSUE THREAD

**Issue by Umar-M-Haroon** [firebase/firebase-ios-sdk#6926]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.2 RC
  * Firebase SDK version: 7.0.0
  * Installation method: `**Swift Package Manager**` (select one)
  * Firebase Component: Dynamic Links (Auth, Core, Database, Firestore, Messaging, Storage, etc)

### [REQUIRED] Step 2: Describe the problem
I'm attempting to move from Cocoapods to SPM and I'm having issues regarding Dynamic Links. In Cocoapods, I just chose to not have the analytics framework added to my project and ignored the warning, and was able to archive normally. As I'm working on the Mac Catalyst version, I am switching to SPM and as I tried to add Dynamic Links, the module for it wouldn't show up unless I add the analytics target, but if I add the analytics target, I get

```

Showing Recent Messages
While building for Mac Catalyst, no library for this platform was found in '/Users/[redacted]/Library/Developer/Xcode/DerivedData/[redacted]-gcjqsdhwgeioitbijpmjndrsymwc/SourcePackages/artifacts/Firebase/FirebaseAnalytics.xcframework'.

While building for Mac Catalyst, no library for this platform was found in '/Users/[redacted]/Library/Developer/Xcode/DerivedData/[redacted]-gcjqsdhwgeioitbijpmjndrsymwc/SourcePackages/artifacts/Firebase/FIRAnalyticsConnector.xcframework'.

While building for Mac Catalyst, no library for this platform was found in '/Users/[redacted]/Library/Developer/Xcode/DerivedData/[redacted]-gcjqsdhwgeioitbijpmjndrsymwc/SourcePackages/artifacts/Firebase/GoogleAppMeasurement.xcframework'.


```

I tried to set the analytics and dynamic links frameworks to only be for iOS instead of iOS + macOS, but still had the same error

#### Steps to reproduce:
- Create new project

- Add firebase package in SPM

- Add analytics and dynamic links target

- build

get the errors above

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
https://github.com/Umar-M-Haroon/DynamicLinksDemo
```

**Comment by paulb777** [comment]
@Umar-M-Haroon Sorry for the trouble but FirebaseAnalytics does not support macOS. More details at https://github.com/firebase/firebase-ios-sdk#tvos-macos-watchos-and-catalyst and issue tracking at #1732

**Comment by paulb777** [comment]
Sorry, I read the description more closely and understand that you're trying to exclude it. Reopening ....

**Comment by Umar-M-Haroon** [comment]
Sounds good, thank you! Do you know if there's a way to include dynamic links without having analytics paired with it in SPM? That would resolve things as that worked when done in cocoa pods previously (it would just give a warning)

**Comment by Umar-M-Haroon** [comment]
I kept messing around with things, but unfortunately haven't found a fix yet. I tried adding just the dynamiclinks static framework from [here](https://firebase.google.com/docs/ios/setup?authuser=0#frameworks) along with the analytics .xcframeworks and solely adding the dynamiclinks framework. This results in it building, but any use of the actual DynamicLinks classes or properties results in a symbol not found for architecture arm64. I committed the changes in the demo project, along with comments that mention where removing code will result in successful builds. 

I don't think im going about this the right way though...

**Comment by paulb777** [comment]
I haven't had a chance to look at the project yet, but neither DynamicLinks nor Analytics support arm64 macOS. As you've found, there is a DynamicLinks binary but that only includes Catalyst x86 mac support.

**Comment by Umar-M-Haroon** [comment]
I see. That makes sense, is there any way I could help build those frameworks? I do have the DTK

**Comment by ryanwilson** [comment]
@Umar-M-Haroon hmm, you should be able to use DynamicLinks without Analytics: https://github.com/firebase/firebase-ios-sdk/blob/90d3600c5606070d20dd4cc63eceb3af77f5024f/Package.swift#L359-L364

Perhaps the issue you're seeing is that only iOS is supported? 

When you say:
> As I'm working on the Mac Catalyst version, I am switching to SPM and as I tried to add Dynamic Links, the module for it wouldn't show up unless I add the analytics target

Can you please elaborate on what you mean by "the module for it wouldn't show up"?

**Comment by Umar-M-Haroon** [comment]
In the file where I use DynamicLinks, `import FirebaseDynamicLinks` will throw an error, the closest target in the import is `import FirebaseDynamicLinksTarget`

**Comment by ryanwilson** [comment]
Thanks for the info - seems like we need to evaluate our packaging structure but in the meantime to unblock you, `import Firebase` should work automatically and pull in the Dynamic Links APIs for you, which is the recommended way of using Firebase. If you want to import specific frameworks still, you can use the `import FirebaseDynamicLinksTarget` now which is an implementation detail that's leaking (specifically about handling different OS support in a single Package.swift manifest.

**Comment by Umar-M-Haroon** [comment]
Sounds good! using `import Firebase` did for for iOS, but not for macOS unfortunately. I ended up just commenting out my dynamiclinks related code on Mac for now though. If I figure anything out I'll be happy to provide the info!
