### ISSUE TITLE
Firebase Crashlytics Update not recording 

### ISSUE THREAD

**Issue by falipate** [firebase/firebase-ios-sdk#6927]
### Step 1: Describe your environment

  * Xcode version: 12.0.1
  * Firebase SDK version: 6.34.0
  * Installation method: `CocoaPods` 
  * Firebase Component:  FirebaseCrashlytics (4.6.2)

### Step 2: Describe the problem
I'm In the process of updating the Crashlytics SDK in our iOS project from Fabric to FirebaseCrashlytics. However I seem to be having issues with our test crashes not being properly recorded on the dashboard. It's possible that I may have missed something with the update, but I am having a hard trying to figure that out after successfully completing the update on another project. The only differences between the two projects is that this is in Swift with FirebaseSDK 6.34.0 while the other is ObjC with FirebaseSDK 6.31.1

#### Steps to reproduce:

In my ViewController I added a fatalError() on a button to force a test crash. The way I tested was to:
1. Run the project in Xcode and then disconnect the device once it was successful. 
2. Re open the app and press the button to trigger the crash.
3. Re open the app to send the crash report Crashlytics

At this point the dashboard in Firebase continues to show the orange coloured warning to update Firebase Crashlytics SDK and that there is a missing dSYM required to process the crashes that I have been testing. 

<img width="615" alt="Screen Shot 2020-11-09 at 10 12 08 am" src="https://user-images.githubusercontent.com/12621961/98487297-455adc80-2276-11eb-8e06-bb6f77364b0b.png">

#### Relevant Code:

I have added the following pods: 
```
    pod 'Firebase/Core', '~> 6'
    pod 'Firebase/Messaging', '~> 6'
    pod 'Firebase/Crashlytics', '~> 6'
    pod 'Firebase/Analytics', '~> 6'
```

I followed the steps in the documentation to configure Firebase on app launch: 
```
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        FirebaseApp.configure()
        return true
    }
```
My Run script
<img width="549" alt="Screen Shot 2020-11-09 at 10 12 32 am" src="https://user-images.githubusercontent.com/12621961/98487228-ef863480-2275-11eb-8f4f-7712db2b5267.png">

Output in the debugger
![Debugger](https://user-images.githubusercontent.com/12621961/98487369-ad112780-2276-11eb-8162-92d9784a1b1c.png)

Any help would be appreciated.

**Comment by morganchen12** [comment]
In Xcode's logs, do you see any warnings about Crashlytics not being able to find dSYMs?

**Comment by falipate** [comment]
@morganchen12 I don't see anything regarding dSYMS in the logs but I did notice this, could this possible be the problem?

 ```
6.34.0 - [Firebase/Core][I-COR000008] The project's Bundle ID is inconsistent with either the Bundle ID in 'GoogleService-Info.plist', or the Bundle ID in the options if you are using a customized options. To ensure that everything can be configured correctly, you may need to make the Bundle IDs consistent. To continue with this plist file, you may change your app's bundle identifier to
```

It's telling me to change the bundle ID to the production bundle ID even though I have both prod and dev bundle ID's setup in the Firebase console. The APP ID and bundle ID in the info plist (at the time of running) does match with the dev app in the Firebase console

**Comment by falipate** [comment]
Seemed to be resolved after manually uploading the dSYM file for me
