### ISSUE TITLE
Suspected Firebase SDK v6.34 crash from [APMMeasurement uploadData]

### ISSUE THREAD

**Issue by ChrisGarmanJD** [firebase/firebase-ios-sdk#6930]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0
  * Firebase SDK version: 6.34.0
  * Installation method: Carthage
  * Firebase Component: iOS SDK/Performance

### [REQUIRED] Step 2: Describe the problem

Since a recent app update, we are seeing a new number 1 crash in our Ecommerce app.  This occurred in the first build since I'd refreshed the Firebase SDK (and other dependencies) to the latest versions.  I am not certain it is caused by Firebase but from the stack trace it seems the most likely cause.  I do not have steps to reproduce the issue.

My analysis is:

1. The crashed thread (number 19) was calling back on a KVO change from CFNetwork-ing
2. Looking in our crash tracker (not Crashlytics for commercial reasons) I can see one of the last network calls before the crash was to https://app-measurement.com/a
3. Reviewing other background threads, I noticed thread 14 was doing a SQL-Lite delete initiated from [APMMeasurement uploadData]
4. Googling the method found in point 3 reveals historic Firebase issues (nothing applicable to this crash)

.crash file can be made available by email if required.

The complete stack trace is here:

Incident Identifier: 06FD8CD6-304B-4DF3-8894-E27C258C8A5A
CrashReporter Key:   0000000000000000000000000000000000000000
Hardware Model:      iPhone9,3
Code Type:           arm64

Date/Time:           2020-11-09T08:35:49+00:00
Launch Time:         2020-11-09T08:35:49+00:00
OS Version:          iOS 14.1 (18A8395)
Report Version:      105

Exception Type:  SIGSEGV
Exception Subtype: 

Thread 0 name:
Thread 0:
0   libsystem_kernel.dylib         	 0x00000001b9c948c4 mach_msg_trap (libsystem_kernel.dylib)
1   CoreFoundation                 	 0x000000018f2c074c __CFRunLoopServiceMachPort (CoreFoundation)
2   CoreFoundation                 	 0x000000018f2babd0 __CFRunLoopRun (CoreFoundation)
3   CoreFoundation                 	 0x000000018f2ba200 CFRunLoopRunSpecific (CoreFoundation)
4   GraphicsServices               	 0x00000001a53b5598 GSEventRunModal (GraphicsServices)
5   UIKitCore                      	 0x0000000191b80004 -[UIApplication _run] (UIKitCore)
6   UIKitCore                      	 0x0000000191b855d8 UIApplicationMain (UIKitCore)
7   JDBuild                        	 0x000000010022764c main (coreAppDelegate.swift:14)
8   libdyld.dylib                  	 0x000000018ef99598 start (libdyld.dylib)

Thread 1 name:
Thread 1:
0   libsystem_kernel.dylib         	 0x00000001b9c948c4 mach_msg_trap (libsystem_kernel.dylib)
1   CoreFoundation                 	 0x000000018f2c074c __CFRunLoopServiceMachPort (CoreFoundation)
2   CoreFoundation                 	 0x000000018f2babd0 __CFRunLoopRun (CoreFoundation)
3   CoreFoundation                 	 0x000000018f2ba200 CFRunLoopRunSpecific (CoreFoundation)
4   Foundation                     	 0x00000001904c4278 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] (Foundation)
5   Foundation                     	 0x00000001904c4158 -[NSRunLoop(NSRunLoop) runUntilDate:] (Foundation)
6   UIKitCore                      	 0x0000000191c2b9fc -[UIEventFetcher threadMain] (UIKitCore)
7   Foundation                     	 0x0000000190620c48 __NSThread__start__ (Foundation)
8   libsystem_pthread.dylib        	 0x00000001d4c22b70 _pthread_start (libsystem_pthread.dylib)
9   libsystem_pthread.dylib        	 0x00000001d4c27880 thread_start (libsystem_pthread.dylib)

Thread 2 name:
Thread 2:
0   libsystem_kernel.dylib         	 0x00000001b9cb772c __psynch_cvwait (libsystem_kernel.dylib)
1   libc++.1.dylib                 	 0x00000001a2c03e0c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) (libc++.1.dylib)
2   NewRelic                       	 0x0000000100d7d88c 0x100cf4000 + 563340
3   NewRelic                       	 0x0000000100d7db04 0x100cf4000 + 563972
4   NewRelic                       	 0x0000000100d7da1c 0x100cf4000 + 563740
5   libsystem_pthread.dylib        	 0x00000001d4c22b70 _pthread_start (libsystem_pthread.dylib)
6   libsystem_pthread.dylib        	 0x00000001d4c27880 thread_start (libsystem_pthread.dylib)

Thread 3 name:
Thread 3:
0   libsystem_kernel.dylib         	 0x00000001b9cb772c __psynch_cvwait (libsystem_kernel.dylib)
1   libc++.1.dylib                 	 0x00000001a2c03e0c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) (libc++.1.dylib)
2   NewRelic                       	 0x0000000100d7d88c 0x100cf4000 + 563340
3   NewRelic                       	 0x0000000100d7db04 0x100cf4000 + 563972
4   NewRelic                       	 0x0000000100d7da1c 0x100cf4000 + 563740
5   libsystem_pthread.dylib        	 0x00000001d4c22b70 _pthread_start (libsystem_pthread.dylib)
6   libsystem_pthread.dylib        	 0x00000001d4c27880 thread_start (libsystem_pthread.dylib)

Thread 4 name:
Thread 4:
0   libsystem_kernel.dylib         	 0x00000001b9c948c4 mach_msg_trap (libsystem_kernel.dylib)
1   CoreFoundation                 	 0x000000018f2c074c __CFRunLoopServiceMachPort (CoreFoundation)
2   CoreFoundation                 	 0x000000018f2babd0 __CFRunLoopRun (CoreFoundation)
3   CoreFoundation                 	 0x000000018f2ba200 CFRunLoopRunSpecific (CoreFoundation)
4   CoreFoundation                 	 0x000000018f2bb2c0 CFRunLoopRun (CoreFoundation)
5   CoreMotion                     	 0x0000000199ab2374 (null) (CoreMotion)
6   libsystem_pthread.dylib        	 0x00000001d4c22b70 _pthread_start (libsystem_pthread.dylib)
7   libsystem_pthread.dylib        	 0x00000001d4c27880 thread_start (libsystem_pthread.dylib)

Thread 5 name:
Thread 5:
0   libsystem_kernel.dylib         	 0x00000001b9c948c4 mach_msg_trap (libsystem_kernel.dylib)
1   CoreFoundation                 	 0x000000018f2c074c __CFRunLoopServiceMachPort (CoreFoundation)
2   CoreFoundation                 	 0x000000018f2babd0 __CFRunLoopRun (CoreFoundation)
3   CoreFoundation                 	 0x000000018f2ba200 CFRunLoopRunSpecific (CoreFoundation)
4   AudioSession                   	 0x00000001967b9158 GenericRunLoopThread::Entry(void*) (AudioSession)
5   AudioSession                   	 0x00000001967bb0b8 CAPThread::Entry(CAPThread*) (AudioSession)
6   libsystem_pthread.dylib        	 0x00000001d4c22b70 _pthread_start (libsystem_pthread.dylib)
7   libsystem_pthread.dylib        	 0x00000001d4c27880 thread_start (libsystem_pthread.dylib)

Thread 6 name:
Thread 6:
0   libsystem_kernel.dylib         	 0x00000001b9cb858c __workq_kernreturn (libsystem_kernel.dylib)
1   libsystem_pthread.dylib        	 0x00000001d4c27874 start_wqthread (libsystem_pthread.dylib)

Thread 7 name:
Thread 7:
0   libsystem_kernel.dylib         	 0x00000001b9cb772c __psynch_cvwait (libsystem_kernel.dylib)
1   libc++.1.dylib                 	 0x00000001a2c03e0c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) (libc++.1.dylib)
2   NewRelic                       	 0x0000000100d7d88c 0x100cf4000 + 563340
3   NewRelic                       	 0x0000000100d7db04 0x100cf4000 + 563972
4   NewRelic                       	 0x0000000100d7da1c 0x100cf4000 + 563740
5   libsystem_pthread.dylib        	 0x00000001d4c22b70 _pthread_start (libsystem_pthread.dylib)
6   libsystem_pthread.dylib        	 0x00000001d4c27880 thread_start (libsystem_pthread.dylib)

Thread 8 name:
Thread 8:
0   libsystem_kernel.dylib         	 0x00000001b9c948c4 mach_msg_trap (libsystem_kernel.dylib)
1   CoreFoundation                 	 0x000000018f2c074c __CFRunLoopServiceMachPort (CoreFoundation)
2   CoreFoundation                 	 0x000000018f2babd0 __CFRunLoopRun (CoreFoundation)
3   CoreFoundation                 	 0x000000018f2ba200 CFRunLoopRunSpecific (CoreFoundation)
4   CFNetwork                      	 0x000000018fb449a4 (null) (CFNetwork)
5   Foundation                     	 0x0000000190620c48 __NSThread__start__ (Foundation)
6   libsystem_pthread.dylib        	 0x00000001d4c22b70 _pthread_start (libsystem_pthread.dylib)
7   libsystem_pthread.dylib        	 0x00000001d4c27880 thread_start (libsystem_pthread.dylib)

Thread 9 name:
Thread 9:
0   libsystem_kernel.dylib         	 0x00000001b9c948c4 mach_msg_trap (libsystem_kernel.dylib)
1   CoreFoundation                 	 0x000000018f2c074c __CFRunLoopServiceMachPort (CoreFoundation)
2   CoreFoundation                 	 0x000000018f2babd0 __CFRunLoopRun (CoreFoundation)
3   CoreFoundation                 	 0x000000018f2ba200 CFRunLoopRunSpecific (CoreFoundation)
4   Foundation                     	 0x00000001904c4278 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] (Foundation)
5   Foundation                     	 0x00000001904f53e4 -[NSRunLoop(NSRunLoop) run] (Foundation)
6   JDBuild                        	 0x0000000100424210 +[GAI threadMain:]
7   Foundation                     	 0x0000000190620c48 __NSThread__start__ (Foundation)
8   libsystem_pthread.dylib        	 0x00000001d4c22b70 _pthread_start (libsystem_pthread.dylib)
9   libsystem_pthread.dylib        	 0x00000001d4c27880 thread_start (libsystem_pthread.dylib)

Thread 10 name:
Thread 10:
0   libsystem_kernel.dylib         	 0x00000001b9cb858c __workq_kernreturn (libsystem_kernel.dylib)
1   libsystem_pthread.dylib        	 0x00000001d4c27874 start_wqthread (libsystem_pthread.dylib)

Thread 11 name:
Thread 11:
0   libsystem_kernel.dylib         	 0x00000001b9cb858c __workq_kernreturn (libsystem_kernel.dylib)
1   libsystem_pthread.dylib        	 0x00000001d4c27874 start_wqthread (libsystem_pthread.dylib)

Thread 12 name:
Thread 12:
0   libsystem_kernel.dylib         	 0x00000001b9cb858c __workq_kernreturn (libsystem_kernel.dylib)
1   libsystem_pthread.dylib        	 0x00000001d4c27874 start_wqthread (libsystem_pthread.dylib)

Thread 13 name:
Thread 13:
0   libsystem_kernel.dylib         	 0x00000001b9cb858c __workq_kernreturn (libsystem_kernel.dylib)
1   libsystem_pthread.dylib        	 0x00000001d4c27874 start_wqthread (libsystem_pthread.dylib)

Thread 14 name:
Thread 14:
**0   libsystem_kernel.dylib         	 0x00000001b9cb6b18 __guarded_open_dprotected_np (libsystem_kernel.dylib)
1   libsqlite3.dylib               	 0x00000001a760d444 (null) (libsqlite3.dylib)
2   libsqlite3.dylib               	 0x00000001a7561d0c (null) (libsqlite3.dylib)
3   libsqlite3.dylib               	 0x00000001a75c33d4 (null) (libsqlite3.dylib)
4   libsqlite3.dylib               	 0x00000001a75c2c04 (null) (libsqlite3.dylib)
5   libsqlite3.dylib               	 0x00000001a75a2130 (null) (libsqlite3.dylib)
6   libsqlite3.dylib               	 0x00000001a759c46c sqlite3_step (libsqlite3.dylib)
7   JDBuild                        	 0x00000001005146f4 -[APMSqliteStore deleteRecordsFromTableWithName:condition:parameterValues:error:]
8   JDBuild                        	 0x00000001004e0454 -[APMDatabase deleteBundlesWithRowIDs:error:]
9   JDBuild                        	 0x00000001004f55e8 -[APMMeasurement removeBundlesFromDatabaseWithIDs:]
10  JDBuild                        	 0x00000001004f1cbc -[APMMeasurement networkUploadCompletionHandlerWithResponse:error:]
11  JDBuild                        	 0x00000001004f1670 __28-[APMMeasurement uploadData]_block_invoke**
12  libdispatch.dylib              	 0x000000018ef79298 _dispatch_call_block_and_release (libdispatch.dylib)
13  libdispatch.dylib              	 0x000000018ef7a280 _dispatch_client_callout (libdispatch.dylib)
14  libdispatch.dylib              	 0x000000018ef22fa8 _dispatch_lane_serial_drain$VARIANT$mp (libdispatch.dylib)
15  libdispatch.dylib              	 0x000000018ef23a84 _dispatch_lane_invoke$VARIANT$mp (libdispatch.dylib)
16  libdispatch.dylib              	 0x000000018ef2d518 _dispatch_workloop_worker_thread (libdispatch.dylib)
17  libsystem_pthread.dylib        	 0x00000001d4c245a4 _pthread_wqthread (libsystem_pthread.dylib)
18  libsystem_pthread.dylib        	 0x00000001d4c27874 start_wqthread (libsystem_pthread.dylib)

Thread 15 name:
Thread 15:
0   libsystem_kernel.dylib         	 0x00000001b9c94918 semaphore_timedwait_trap (libsystem_kernel.dylib)
1   libdispatch.dylib              	 0x000000018ef1d97c _dispatch_semaphore_wait_slow (libdispatch.dylib)
2   libdispatch.dylib              	 0x000000018ef2bef4 _dispatch_worker_thread (libdispatch.dylib)
3   libsystem_pthread.dylib        	 0x00000001d4c22b70 _pthread_start (libsystem_pthread.dylib)
4   libsystem_pthread.dylib        	 0x00000001d4c27880 thread_start (libsystem_pthread.dylib)

Thread 16 name:
Thread 16:
0   libsystem_kernel.dylib         	 0x00000001b9c94918 semaphore_timedwait_trap (libsystem_kernel.dylib)
1   libdispatch.dylib              	 0x000000018ef1d97c _dispatch_semaphore_wait_slow (libdispatch.dylib)
2   libdispatch.dylib              	 0x000000018ef2bef4 _dispatch_worker_thread (libdispatch.dylib)
3   libsystem_pthread.dylib        	 0x00000001d4c22b70 _pthread_start (libsystem_pthread.dylib)
4   libsystem_pthread.dylib        	 0x00000001d4c27880 thread_start (libsystem_pthread.dylib)

Thread 17 name:
Thread 17:
0   libsystem_kernel.dylib         	 0x00000001b9c94918 semaphore_timedwait_trap (libsystem_kernel.dylib)
1   libdispatch.dylib              	 0x000000018ef1d97c _dispatch_semaphore_wait_slow (libdispatch.dylib)
2   AirshipCore                    	 0x0000000100c2857c -[UADelay start] (UADelay.m:31)
3   AirshipCore                    	 0x0000000100c39a10 __34-[UADelayOperation initWithDelay:]_block_invoke (UADelayOperation.m:17)
4   Foundation                     	 0x00000001905ddcc8 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ (Foundation)
5   Foundation                     	 0x00000001904dab18 -[NSBlockOperation main] (Foundation)
6   Foundation                     	 0x00000001905dff80 __NSOPERATION_IS_INVOKING_MAIN__ (Foundation)
7   Foundation                     	 0x00000001904da7d4 -[NSOperation start] (Foundation)
8   Foundation                     	 0x00000001905e0978 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ (Foundation)
9   Foundation                     	 0x00000001905e0444 __NSOQSchedule_f (Foundation)
10  libdispatch.dylib              	 0x000000018ef2993c _dispatch_block_async_invoke2 (libdispatch.dylib)
11  libdispatch.dylib              	 0x000000018ef7a280 _dispatch_client_callout (libdispatch.dylib)
12  libdispatch.dylib              	 0x000000018ef1f56c _dispatch_continuation_pop$VARIANT$mp (libdispatch.dylib)
13  libdispatch.dylib              	 0x000000018ef1ecb0 _dispatch_async_redirect_invoke (libdispatch.dylib)
14  libdispatch.dylib              	 0x000000018ef2c11c _dispatch_root_queue_drain (libdispatch.dylib)
15  libdispatch.dylib              	 0x000000018ef2c8e4 _dispatch_worker_thread2 (libdispatch.dylib)
16  libsystem_pthread.dylib        	 0x00000001d4c24568 _pthread_wqthread (libsystem_pthread.dylib)
17  libsystem_pthread.dylib        	 0x00000001d4c27874 start_wqthread (libsystem_pthread.dylib)

Thread 18 name:
Thread 18:
0   libsystem_kernel.dylib         	 0x00000001b9cb858c __workq_kernreturn (libsystem_kernel.dylib)
1   libsystem_pthread.dylib        	 0x00000001d4c27874 start_wqthread (libsystem_pthread.dylib)

Thread 19 name:
**Thread 19 Crashed:**
0   libobjc.A.dylib                	 0x00000001a2b84df0 objc_release (libobjc.A.dylib)
1   Foundation                     	 0x00000001905bb57c NSKeyValuePopPendingNotificationLocal (Foundation)
2   Foundation                     	 0x00000001905bb4f8 NSKeyValueDidChange (Foundation)
3   Foundation                     	 0x00000001905baf64 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:maybeNewValuesDict:usingBlock:] (Foundation)
4   Foundation                     	 0x00000001904ff800 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:] (Foundation)
5   Foundation                     	 0x00000001905b63d8 _NSSetLongLongValueAndNotify (Foundation)
6   CFNetwork                      	 0x000000018f918470 (null) (CFNetwork)
7   CFNetwork                      	 0x000000018f9b06c8 (null) (CFNetwork)
8   CFNetwork                      	 0x000000018f91d630 (null) (CFNetwork)
9   CFNetwork                      	 0x000000018f91d4c0 (null) (CFNetwork)
10  libdispatch.dylib              	 0x000000018ef2993c _dispatch_block_async_invoke2 (libdispatch.dylib)
11  libdispatch.dylib              	 0x000000018ef7a280 _dispatch_client_callout (libdispatch.dylib)
12  libdispatch.dylib              	 0x000000018ef22fa8 _dispatch_lane_serial_drain$VARIANT$mp (libdispatch.dylib)
13  libdispatch.dylib              	 0x000000018ef23ab4 _dispatch_lane_invoke$VARIANT$mp (libdispatch.dylib)
14  libdispatch.dylib              	 0x000000018ef2d518 _dispatch_workloop_worker_thread (libdispatch.dylib)
15  libsystem_pthread.dylib        	 0x00000001d4c245a4 _pthread_wqthread (libsystem_pthread.dylib)
16  libsystem_pthread.dylib        	 0x00000001d4c27874 start_wqthread (libsystem_pthread.dylib)

Thread 21 name:
Thread 21:
0   libsystem_kernel.dylib         	 0x00000001b9c94918 semaphore_timedwait_trap (libsystem_kernel.dylib)
1   libdispatch.dylib              	 0x000000018ef1d97c _dispatch_semaphore_wait_slow (libdispatch.dylib)
2   libdispatch.dylib              	 0x000000018ef2bef4 _dispatch_worker_thread (libdispatch.dylib)
3   libsystem_pthread.dylib        	 0x00000001d4c22b70 _pthread_start (libsystem_pthread.dylib)
4   libsystem_pthread.dylib        	 0x00000001d4c27880 thread_start (libsystem_pthread.dylib)

#### Steps to reproduce:

Unknown

**Comment by paulb777** [comment]
This is likely #6734.  We're planning a fix this week in 7.1.0.

A 6.x Carthage workaround would be to install the 6.32.0 version of FirebasePerformance and replace FirebasePerformance.framework in the app.

**Comment by paulb777** [comment]
7.1.0 is now out. I'm going to close here. Please follow up if you find that it doesn't solve the crash.
