### ISSUE TITLE
FIAM Card Impression is Interacted with but continues to Spam users on next App Start/Session

### ISSUE THREAD

**Issue by EesaJacobs** [firebase/firebase-ios-sdk#6931]
# Step 1: Describe your environment

Xcode version: 12.0 (12A7209)
Firebase SDK version: 6.34.0
Firebase Component: In-App Messaging

# Step 2: Describe the problem

Our iOS campaigns are spamming our users. We've set the campaign to show _once per device_, after interacting with the FIAM Card, I can see the impression is being logged (logs below) but the next time the App is launched... the FIAM Card is shown again after interacting with the corresponding Component that sends the Firebase Event.

Everything works fine on Android BTW

# Steps to reproduce:

1. Create a FIAM Card Campaign with, set the Campaign to 'Once Per Device'
2. Associate the Campaign with a a Firebase Event
3. Navigate to the App and perform the action that will trigger the Firebase Event associated with #2 above
4. Observe the FIAM Card, dismiss the Card with the FIAM button that's accommodated with the FIAM Card
5. Close the App
6. Repeat steps 3 & 4... Observe the FIAM Card being shown again (this is the issue... it shouldn't show again for this device)

# Relevant Code:

Podfile

platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

inhibit_all_warnings!

target '{PROJECT_NAME}' do
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'AFNetworking', '~> 4.0.0'
    
    pod 'Firebase'
    pod 'Firebase/InAppMessaging'
    pod 'Firebase/Analytics'
    pod 'Firebase/Crashlytics'
    pod 'FirebaseMessaging'
    pod 'FirebasePerformance'
    pod 'FirebaseRemoteConfig'
    
    pod 'GoogleMaps'
    pod 'GoogleTagManager'
    pod 'DLRadioButton', '1.4.9'
    pod 'SWTableViewCell', '0.3.7'
    pod 'ZXingObjC', '3.2.1'
    
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    
    pod 'GRDB.swift'
    pod 'QBImagePickerController'
    pod 'NVActivityIndicatorView'
    pod 'UIImageViewAligned'
    pod 'SnapKit'
    pod 'Shimmer'
    pod 'Apollo', '0.30.0'
    pod 'AWSMobileClient'
    pod 'Apollo/WebSocket'
    
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = '$(inherited)'
                config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
                config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
            end
        end
    end
end

# Analytics Logs

2020-11-09 20:15:44.149640+0200 ProjectName Q[60182:2373460] GoogleTagManager info: Processing logged event: firebase_in_app_message_impression with parameters: {
    "_ndt" = "1604945744.140903";
    "_nmid" = 327518125635403776;
    "_nmn" = "Eesa Jacobs Campaign QA";
    "_o" = fiam;
    "_sc" = "ProjectName_Q.ProductListController";
    "_si" = "-2176478578679549284";
    "_sn" = "Product Search Result";
}
2020-11-09 20:15:44.810003+0200 ProjectName Q[60182:2374129] GoogleTagManager info: Processing logged event: firebase_in_app_message_dismiss with parameters: {
    "_ndt" = "1604945744.804209";
    "_nmid" = 327518125635403776;
    "_nmn" = "Eesa Jacobs Campaign QA";
    "_o" = fiam;
    "_sc" = "ProjectName_Q.ProductListController";
    "_si" = "-2176478578679549284";
    "_sn" = "Product Search Result";
}

**Comment by christibbs** [comment]
Looking into this.

**Comment by christibbs** [comment]
I was able to reproduce this once, but haven't been able to repro it again. Will continue investigating.

**Comment by christibbs** [comment]
Having trouble reproducing this. I saw it once, but haven't since. Is it 100% repro in your case? If so are there any unique things about the app or campaign? Like a large image for the campaign?

**Comment by EesaJacobs** [comment]
Hi @christibbs. We're reproducing this issue each time without any effort.

- The same campaign works perfectly on Android but has this issue on iOS.
- The image size being used for this campaign is 24 875 bytes (29 KB)
- 100% of potential users are eligible for this campaign:111
- I've attached a few screenshots that describes this campaign

<img width="1749" alt="Screenshot 2020-12-04 at 14 07 27" src="https://user-images.githubusercontent.com/5364753/101162259-c40b2580-363a-11eb-865a-4337ad72ac6a.png">
<img width="1749" alt="Screenshot 2020-12-04 at 14 06 13" src="https://user-images.githubusercontent.com/5364753/101162276-ca010680-363a-11eb-9440-9c0d331b8923.png">
<img width="1749" alt="Screenshot 2020-12-04 at 14 03 16" src="https://user-images.githubusercontent.com/5364753/101162280-ca999d00-363a-11eb-8c79-129c03df112b.png">

**Comment by EesaJacobs** [comment]
Hi @christibbs. I've found the cause of this issue. 

I realised that FIAM may use Native Local Storage Tech to store impressions. On startup of the App, we are clearing out UserDefaults.standard as we use a 3rd party lib for local storage.

Removing the functionality to clear out UserDefaults solves this issue.

**Comment by christibbs** [comment]
@EesaJacobs Ah, makes sense. Thought I was going crazy 😅
