### ISSUE TITLE
App preview page: Hide app name and icon

### ISSUE THREAD

**Issue by tallneil** [firebase/firebase-ios-sdk#6932]
### Feature proposal

https://firebase.google.com/docs/dynamic-links/link-previews

On app preview pages, is there a way to hide the app name and icon? 

![image](https://user-images.githubusercontent.com/7357971/98585375-30417600-2295-11eb-84b0-1606bea80255.png)

In the image above, it would be the Google Photos logo and name.

**Comment by paulb777** [comment]
Now that [Firebase DynamicLinks is planned to shut down](https://firebase.google.com/support/dynamic-links-faq), closing its feature requests.
