### ISSUE TITLE
Since version 7.0.0: Undefined symbols for architecture x86_64:   "_OBJC_CLASS_$_FIRAnalytics"

### ISSUE THREAD

**Issue by yusheng00** [firebase/firebase-ios-sdk#6951]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.7
  * Firebase SDK version: 7.1.0
  * Installation method: CocoaPods
  * Firebase Component: Core

#### Steps to reproduce:

  s.dependency 'Firebase/Analytics'
  s.dependency 'Firebase/Performance'
  s.dependency 'Firebase/Messaging'
  s.dependency 'Firebase/Crashlytics'

 pod install, build,  and then, xcode throws error

**Comment by morganchen12** [comment]
Please fill out the issue template. Based on the repro steps you're listing, it looks like you're trying to develop a CocoaPod. Make sure Analytics is correctly linked into your build target.

**Comment by yusheng00** [comment]
> Please fill out the issue template. Based on the repro steps you're listing, it looks like you're trying to develop a CocoaPod. Make sure Analytics is correctly linked into your build target.

yes, I am trying to develop a private pod. The pod provides some functions based on Firebase. Since I add  the firebase as 
a dependency in podspec file and build it, then Xcode throws the error.  I didn't do any other settings for Firebase in my project.

**Comment by morganchen12** [comment]
Can you share a sample project using a local podspec?
