### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_FIRApp

### ISSUE THREAD

**Issue by RuchiMakadia** [firebase/firebase-ios-sdk#6953]
I m using Xcode 12.1 and add firebase SDK using swift package 
after that import firebase in my AppDelegate like below 
```
 #import <FirebaseCore/FIRApp.h>
#import <Firebase.h>
```
Upto this All fine but when i m configure firebase app uisng this line `[FIRApp configure];` getting error 

> Undefined symbols for architecture arm64: "OBJC_CLASS$_FIRApp", referenced from: objc-class-ref in HWOFAppDelegate.o ld: symbol(s) not found for architecture arm64 clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by RuchiMakadia** [comment]
I just update my question

**Comment by maksymmalyhin** [comment]
@RuchiMakadia it is most likely and issue with project settings. Could you please provide a sample project for us where the issue is reproducible.

**Comment by RuchiMakadia** [comment]
here I share you link of sample project in that i just remove most of file, keep just AppDelegate [https://easyupload.io/6c7p6v](url) 
you can check the error in "HWOFAppDelegate.m" file line number 20(`[FIRApp configure];)`

**Comment by morganchen12** [comment]
The AppDelegate won't have any effect on the issue you're getting. Can you upload the entire project to a GitHub repository and share the link?

**Comment by RuchiMakadia** [comment]
did you get error like "Undefined symbol: _OBJC_CLASS_$_FIRApp" ?

**Comment by morganchen12** [comment]
We've been unable to reproduce this build error in our sample projects.

**Comment by RuchiMakadia** [comment]
Yes when I create new project I don't get error but because of old project I get error and also I agree with @maksymmalyhin i think some project setting issue and I tried a lot but no luck.

**Comment by paulb777** [comment]
Please share a reproducible example.
