### ISSUE TITLE
Update to version 7.0.0 on tvOS not working

### ISSUE THREAD

**Issue by laizaraujo** [firebase/firebase-ios-sdk#6962]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.1
  * Firebase SDK version: 7.0.0
  * Installation method: `CocoaPods `
  * Firebase Component: Analytics and Crashlytics

### [REQUIRED] Step 2: Describe the problem

I'm trying to update both Firebase/Analytics and Firebase/Crashlytics from version **6.34.0** to version **7.0.0** on tvOS.
But when running `pod install` the following problem happens:

![Screen Shot 2020-11-12 at 10 21 07](https://user-images.githubusercontent.com/14930710/98945113-cdd4b980-24d0-11eb-9bfd-c00c11b86a1f.png)

The `pod install` works well on the previous version (6.34.0) for tvOS.

**Comment by paulb777** [comment]
We have never supported Analytics for tvOS. See #2011.

**Comment by paulb777** [comment]
I'm going to close, but can reopen with more detail that makes this actionable for us.
