### ISSUE TITLE
didReceiveRegistrationToken Is being called on every app launch, this contradicts the android implementation.

### ISSUE THREAD

**Issue by nextdimension** [firebase/firebase-ios-sdk#6966]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.1
  * Firebase SDK version: 7.1.0
  * Installation method: cocoa pods
  * Firebase Component: Messaging

### [REQUIRED] Step 2: Describe the problem

In the documentation it states that this method “didReceiveRegistrationToken” is being called on every app launch and this is in fact the case on iOS.

After configuring firebase and setting the message delegate, the firebase SDK is calling didReceiveRegistrationToken on every app launch, which is unnecessary.

On android the fire base sdk correctly calls the onNewToken only on initial app launch and when the token is changed.

I think there is a problem with your documentation on iOS, as it contradicts itself as to how the above works.

Even your technical support seems to think that it should only be called on first launch and when the token has changed, as is the case on android unless there is something I am mis-understanding.

**Comment by ewfian** [comment]
FYI.

> Typically it will be called once per app start, but may be called more often, if token is invalidated or updated. 

Ref: https://firebase.google.com/docs/reference/ios/firebasemessaging/api/reference/Protocols/FIRMessagingDelegate



And, I would be very grateful if the behavior on both android and iOS could be clarified

**Comment by chliangGoogle** [comment]
This is by design and android and iOS are natively different, especially the FCM token can change if APNS token is updated from Apple, which is needed to be launched once every app launch.
