### ISSUE TITLE
Google SDK Breaks User Activities with Incorrect Swizzle Method Name

### ISSUE THREAD

**Issue by cyril-austin-macdonald** [firebase/firebase-ios-sdk#6968]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.7
  * Firebase SDK version: FirebaseCore (6.10.4)
  * Installation method: `CocoaPods`
  * Firebase Component: GoogleUtilities/AppDelegateSwizzler

#### Steps to reproduce:

Implement the iOS delegate for user activities in a Swift app:

func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([Any]?) -> Void) -> Bool

#### Relevant Code:

In the SDK code in GULAppDelegateSwizzler it swizzles in its own code and tries to look for the original "application:continueUserActivity:restorationHandler:". That's not what it's called in Swift, it's called "application:continue:restorationHandler:", so the original method is never called.

```
- (BOOL)application:(GULApplication *)application
    continueUserActivity:(NSUserActivity *)userActivity
      restorationHandler:(void (^)(NSArray *restorableObjects))restorationHandler {
  SEL methodSelector = @selector(application:continueUserActivity:restorationHandler:);
  NSValue *continueUserActivityIMPPointer =
      [GULAppDelegateSwizzler originalImplementationForSelector:methodSelector object:self];
...
```

**Comment by maksymmalyhin** [comment]
@cyril-austin-macdonald Thank you for the report. We will investigate the best suitable fix for it.  In the meanwhile you may disable swizzling by adding the flag `FirebaseAppDelegateProxyEnabled` to your app's Info.plist file and setting it to NO and follow integration guides without app delegate swizzling, e.g. [Authentication](https://firebase.google.com/docs/auth/ios/phone-auth#appendix:-using-phone-sign-in-without-swizzling) or [Cloud Messaging](https://firebase.google.com/docs/cloud-messaging/ios/client#token-swizzle-disabled).

**Comment by chliangGoogle** [comment]
@cyril-austin-macdonald This shouldn't be an issue. e.g. for messaging, we swizzling a `[notification](https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/1649501-usernotificationcenter?language=objc)` method which is also different in term of naming between swift/objC, and this should be swizzled under Firebase without issue.

**Comment by chliangGoogle** [comment]
@cyril-austin-macdonald This should not be a problem. e.g. Messaging has a [push notification method ](https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/1649518-usernotificationcenter) that has the same pattern with different function names between swift and objc, but swizzling should be able to detect the difference and manage to swizzle the method under the hood and still call your method if you implement it in swiftUI test app.

**Comment by paulb777** [comment]
Closing for staleness. Please comment or open a new issue to continue the discussion.
