### ISSUE TITLE
[NSProcessInfo isiOSAppOnMac] crash

### ISSUE THREAD

**Issue by shanksGuo** [firebase/firebase-ios-sdk#6969]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0
  * Firebase SDK version: master branch
  * Installation method: CocoaPods
  * Firebase Component: GoogleUtilities
  * iOS version: 14.0

### [REQUIRED] Step 2: Describe the problem
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSProcessInfo isiOSAppOnMac]: unrecognized selector sent to instance 0x2834ac5d0'
<img width="939" alt="Screen Shot 2020-11-14 at 16 55 24" src="https://user-images.githubusercontent.com/8662571/99143668-49359700-269a-11eb-820f-d6c96059a991.png">

#### Steps to reproduce:

It was generated from users, I have not find reproduce steps. I thinks the pic above will help.

#### Relevant Code:

```
//GULAppEnvironmentUtil.m
+ (NSString *)applePlatform {
  NSString *applePlatform = @"unknown";

  ...
#if defined(__IPHONE_14_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= 140000
  if (@available(iOS 14.0, *)) {
    applePlatform = [NSProcessInfo processInfo].isiOSAppOnMac ? @"ios_on_mac" : @"ios";
  } else {
    applePlatform = @"ios";
  }
...
}
```

**Comment by paulb777** [comment]
@shanksGuo Thanks for the report. Do you have device information for the crashes? And can you confirm that the crash occurs on iOS 14 and only iOS 14?

**Comment by shanksGuo** [comment]
So far, according to our owner crash collection system, this crash only happened only on iOS14. We are trying to reproduce this locally.

**Comment by ksloginov** [comment]
Experiencing the same crash - 100% on iPhone (0 crashes on iPad for some reason) w/ iOS14 (we got *plenty* of them). Can't repro it locally though :-/

**Comment by paulb777** [comment]
Could it be that the `isiOSAppOnMac` API wasn't available in the early iOS 14 betas?

**Comment by ryanwilson** [comment]
@paulb777 that's my guess as well, I think I recall seeing something similar. I'm not sure if the `@available` check allows, but if so we could check for `14.0.1` and that could resolve it?

**Comment by shanksGuo** [comment]
so far, I've only dicovered limited users of this type of crash, and cannot reproduce locally.

**Comment by hiko-prod** [comment]
> Could it be that the `isiOSAppOnMac` API wasn't available in the early iOS 14 betas?

I confirm your idea, I have a phone with first beta and the crash occure 100% on this device. But not on device without beta

**Comment by warpling** [comment]
Seeing this on an iPad running an older beta. Updating it now.

**Comment by paulb777** [comment]
Planning to release the fix in GoogleUtilities 7.1.1 to CocoaPods in the next few days. The other Firebase distributions will pick this up in 7.2.0

**Comment by paulb777** [comment]
Run `pod update` to get Google Utilities 7.1.1 that just published to CocoaPods

**Comment by shanksGuo** [comment]
Thanks, I will update this.

**Comment by qinzhe** [comment]
> Run `pod update` to get Google Utilities 7.1.1 that just published to CocoaPods

thank you
