### ISSUE TITLE
Crashlytics: Run script phase for Swift Package Manager

### ISSUE THREAD

**Issue by ginesdeka** [firebase/firebase-ios-sdk#6972]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.2
  * Firebase SDK version: 7.1.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: Crashlytics

### [REQUIRED] Step 2: Describe the problem
Run script phase for Swift Package Manager. I'm trying:
"${BUILD_DIR%Build/*}SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run"
#### Result:
The Firebase Console didn't appear the crash info page. Always said: "Add the Firebase iOS SDK...."

![Captura de pantalla 2020-11-16 a las 16 28 30](https://user-images.githubusercontent.com/60469629/99273042-cd1d8980-2828-11eb-97d3-d8c00b9640a1.png)

**Comment by jostster** [comment]
I noticed this issue as well when working on watchOS support. It seemed to go away after I forced a crash and it was processed by the backend.

**Comment by lukacs-m** [comment]
@ginesdeka have you managed to resolve this problem ? I'm facing the same issue with Crashlytics, SPM and watchOs.

**Comment by KhiProjects** [comment]
@jostster, could you tell me more on your settings and you tested it ?
I am having se same issue: 
Crashlytics (7.1.0) installed via SPM on my watch extension.

I created many forced crash but nothing appeared.

thanks 🙏

**Comment by jostster** [comment]
See https://github.com/firebase/firebase-ios-sdk/issues/6843

**Comment by KhiProjects** [comment]
Thanks @jostster,
Indeed I have seen this thread and tried  a div by zero and calling "fatal error", I gonna try "perform(Selector(("crash")))"

Could it be linked with the fact that I use Combine and Swift UI ?

**Comment by jostster** [comment]
That is correct, as mentioned in https://github.com/firebase/firebase-ios-sdk/issues/6843#issuecomment-730557274 SwiftUI crashes are recorded as Mach Exceptions which are not supported in watchOS. You could try and have your SwiftUI link to swift files and see if the crashes generated there are recorded.

**Comment by KhiProjects** [comment]
Hello @jostster,

I finally received some crash report in my view.
Indeed, if it's a component related to swift ui.. the errors wasn't seen.

Thanks, I hope that your main crash isn't swift ui related.
Will it be corrected in the next version ?

Thanks again for pinpointing my that specification.

**Comment by jostster** [comment]
@KhiProjects unfortunately due to watchOS restrictions we are unable to listen for mach exception and signal crashes. Mach exception support was removed in watchOS 3.

**Comment by paulb777** [comment]
I'm going to close to consolidate discussion in the duplicate #6843
