### ISSUE TITLE
Nightly Testing Report11/16/2020 10:25 AM

### ISSUE THREAD

**Issue by granluo** [firebase/firebase-ios-sdk#6973]
# Nightly testing report.

Failures are detected in workflow(s)

This issue is generated at 11/16/2020 10:25 AM
| Workflow |11/15|
| -------- | -------- |
[zip](https://github.com/firebase/firebase-ios-sdk/blob/master/.github/workflows/zip.yml)|[failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/365576620)|
[performance](https://github.com/firebase/firebase-ios-sdk/blob/master/.github/workflows/performance.yml)|[skipped](https://github.com/firebase/firebase-ios-sdk/actions/runs/365505241)|
[performance-integration-tests](https://github.com/firebase/firebase-ios-sdk/blob/master/.github/workflows/performance-integration-tests.yml)|[skipped](https://github.com/firebase/firebase-ios-sdk/actions/runs/366387022)|

**Comment by granluo** [comment]
This issue is for testing purpose.

**Comment by paulb777** [comment]
The zip failure building Database and Firestore is likely related to recent changes in the ZipBuilder. @ryanwilson is investigating.
