### ISSUE TITLE
Add non-fatal firebase storage init method

### ISSUE THREAD

**Issue by yura-hb** [firebase/firebase-ios-sdk#6974]
### Feature proposal

* Firebase Component: Storage (Auth, Core, Database, Firestore, Messaging, Storage, etc)

Add more swifty initialization for the reference on the firebase storage. At the moment Firebase Storage crashes the Swift app, if you provide link with incorrect domain to - (FIRStorageReference *)referenceForURL:(NSString *)string;

**Comment by morganchen12** [comment]
Can you describe what the desired behavior would be here if passing in an incorrect domain? Should we just return an optional instead?

**Comment by yura-hb** [comment]
@morganchen12 Hello, any behaviour with error handling is enough for this case. From my point of view, optional is enough, but you can consider for throwing a Swift error in such case.

**Comment by paulb777** [comment]
Adding for consideration for Firebase 10. At first thought, I think throwing a Swift error would be best so that the return value doesn't need to be unwrapped.

**Comment by paulb777** [comment]
Merged to master for the upcoming 10.0.0 release
