### ISSUE TITLE
The method -callWithObject:completion: throws an exception when trying to encode FIRTimestamp

### ISSUE THREAD

**Issue by PomegranateApps** [firebase/firebase-ios-sdk#6979]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.2
  * Firebase SDK version: Latest
  * Installation method: `CocoaPods`
  * Firebase Component: Functions

### [REQUIRED] Step 2: Describe the problem

When calling the method `-callWithObject:completion:` it throws an exception if the dictionary for the object contains an FIRTimestamp value.

It should be able to encode this value.

`Unsupported type: FIRTimestamp for value <FIRTimestamp: seconds=1605621091 nanoseconds=0>"`

#### Steps to reproduce:

What happened? How can we make the problem occur?

`FUNThrowInvalidArgument`

#### Relevant Code:

```
FIRFunctions *functions = [FIRFunctions functions];
FIRHTTPSCallable *function = [functions HTTPSCallableWithName:@"myfunction"];	
NSDictionary *object = @{@"postDate": [FIRTimestamp timestampWithDate:[NSDate now]]};
[function callWithObject:object completion:^(FIRHTTPSCallableResult * _Nullable result, NSError * _Nullable error) {

}];			
```

**Comment by paulb777** [comment]
@PomegranateApps Sorry for the trouble, but FirebaseFunctions does not support the `FIRTimestamp` type. There is an open feature request at #1738
