### ISSUE TITLE
InAppMessaging does not log expected Installation Id

### ISSUE THREAD

**Issue by kgooble** [firebase/firebase-ios-sdk#6980]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.2
  * Firebase SDK version: 6.32.0 (Unity SDK 6.16.0)
  * Installation method: `CocoaPods`, Firebase SDK installed through Unity package manager
  * Firebase Component: InAppMessaging
  * Unity Version: 2018.4.11f1
  * iOS Device: iPad Mini MK6J2CL/A running iOS 11.0.3

### [REQUIRED] Step 2: Describe the problem
Similar to https://github.com/firebase/firebase-ios-sdk/issues/4548, I'm having the following issues:
- Obtaining the installation ID on my iOS device.
- Displaying in app messages on other iOS devices where the installation ID was already retrieved in past versions of Firebase.

#### Steps to reproduce:

1. Add a file `InAppMessagingDependencies.xml` to `Assets/Firebase/Editor` in Unity:
```xml
<dependencies>
 <iosPods>
   <iosPod name="Firebase">
   </iosPod>
   <iosPod name="Firebase/InAppMessaging">
   </iosPod>
   <iosPod name="Firebase/Analytics">
   </iosPod>
 </iosPods>
 <androidPackages>
   <androidPackage spec="com.google.firebase:firebase-core:17.1.0">
   </androidPackage>
   <androidPackage spec="com.google.firebase:firebase-inappmessaging-display:19.0.0">
   </androidPackage>
 </androidPackages>
</dependencies>
```
2. Build the Xcode project using Unity.
3. Note that the Xcode project includes a bunch of Firebase libs, but not `InAppMessaging` for some reason; add manually for now.

Before:
![Screen Shot 2020-11-17 at 12 04 25 PM](https://user-images.githubusercontent.com/3249141/99422021-0ad3ee00-28cd-11eb-858c-4dfa2cc121a2.png)

After:
![Screen Shot 2020-11-17 at 12 04 44 PM](https://user-images.githubusercontent.com/3249141/99422045-158e8300-28cd-11eb-9466-e33bc0d1736e.png)

4. Add `-FIRDebugEnabled` flag to "Arguments passed on launch" in Xcode schema, following instructions [here](https://firebase.google.com/docs/in-app-messaging/get-started?platform=ios#get_your_apps)
5. Build and run the app using Xcode.
6. Open the console in Xcode, searching for messages with "Firebase" in the text
7. Note that no `Firebase/InAppMessaging` related logs show up in the Xcode console:
![Screen Shot 2020-11-17 at 12 07 51 PM](https://user-images.githubusercontent.com/3249141/99422508-a4030480-28cd-11eb-8319-3d6beba4127e.png)

#### Relevant Code:
From what I understand there's no code required except to call `CheckAndFixDependenciesAsync` for Unity projects, which is being called from a MonoBehaviour's `Start` lifecycle event at app launch:
```csharp
    FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task => {
      var dependencyStatus = task.Result;

      if (dependencyStatus == DependencyStatus.Available) {
        this.app = FirebaseApp.DefaultInstance;
      } else {
        Log.Error(string.Format("Could not resolve all Firebase dependencies: {0}", dependencyStatus));
      }
    });
```

**Comment by christibbs** [comment]
Internal bug number 174064193.
