### ISSUE TITLE
iOS Firebase Crashlytics stop working

### ISSUE THREAD

**Issue by vijayviswas** [firebase/firebase-ios-sdk#6984]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.2
  * Firebase SDK version: 4.0.0
  * Installation method: Carthage
  * Firebase Component:Crashlytics

### [REQUIRED] Step 2: Describe the problem
iOS Firebase Crashlytics stop working suddenly and I dont see the latest app version crash events in firebase dashboard

#### Steps to reproduce:

It used work before 
[FIRApp configure]; is called from didFinishLaunchingWithOptions

FYI -> I dont run script to upload DSYM file and everything worked fine before

**Comment by mschuetz72** [comment]
@vijayviswas as far as I know, you need to update to a Crashlytics version > 4.0. If you access the Crashlytics dashboard, you should see a warning regarding that update with a link having further information. Hope that helps.

**Comment by vijayviswas** [comment]
@mschuetz72  Thank you. I will try updating the sdk

**Comment by vijayviswas** [comment]
I upgraded to latest sdk and it works
