### ISSUE TITLE
Integrating FirebaseCrashlytics adds FirebaseAnalytics and breaks FirebaseRemoteConfig fetch in app with dynamic frameworks

### ISSUE THREAD

**Issue by anisimov-voir** [firebase/firebase-ios-sdk#6985]
### Step 1: Describe your environment

  * Xcode version: 12.2 (12B45b)
  * Firebase SDK version: 7.1
  * Installation method: `CocoaPods`
  * Firebase Component: Crashlytics, RemoteConfig

#### Steps to reproduce:

Hello everyone.
I'm using RemoteConfig (dynamic) in main app and going to use Crashlytics (dynamic) inside dynamic frameworks to log things for crash reporting.
When I adding Crashlytics to frameworks targets in podfile, it also installs FirebaseAnalytics with static framework inside and GoogleAppMeasurement. 
And I'm getting 
1) - "Class FIRAnalyticsConnector is implemented in both", and 
2) - RemoteConfig.fetch freezes inside private method `-[FIRAnalyticsInterop getUserPropertiesWithCallback:` call.

How to prevent installing FirebaseAnalytics, which I don't need, or get an dynamic version of this framework? Or maybe another advice how to fix this problem?
Thank you!

**Comment by anisimov-voir** [comment]
I don't have FirebaseAnalytics in my podfile, that's an problem.

My configuration:

```
App
- App target
  - Firebase/RemoteConfig (CocoaPods)
  - My logger framework (CocoaPods)
- Dynamic framework targets
  - My logger framework (CocoaPods)

My logger framework
- Firebase/Crashlytics in podspec dependency
- Firebase/Core in podspec dependency (for workaround, description below, adds Analytics)
```

In this configuration without Firebase/Core in logger framework CocoaPods generates two GoogleUtilites like in #4087.
To fix this I'm adding Firebase/Core to logger podspec, and all works fine, but im getting implicitly added FirebaseAnalytics :(

**Comment by paulb777** [comment]
`Firebase/Core` is deprecated since it is confusingly a synonym for `Firebase/Analytics`.

Note, however, that Crashlytics depends on Analytics for features like Crash-Free Users and Breadcrumbs. If you need it, it might work to add `Firebase/Analytics` to the app target so it's not in the framework.

**Comment by anisimov-voir** [comment]
But Analytics breaks all app because of static nature. I cannot add Crashlytics without Core/Analytics because of #4087...

**Comment by paulb777** [comment]
It should be ok to add a static framework to the main app. #4087 can be worked around by explicitly adding the right GoogleUtilities podspecs.

**Comment by anisimov-voir** [comment]
Yes, a min ago, I found workaround way, removed "Core" dependency from logger and added GoogleUtilities difference in my podfile:

```ruby
def logger
  pods_with_firebase_fix
  pod 'VoirLogger/Crashlytics', :podspec => 'VoirLogger.podspec'
end

def firebase
  pods_with_firebase_fix
  pod 'Firebase/RemoteConfig'
end

# Firebase fix (Crashlytics produces another version of GoogleUtilities, than RemoteConfig)
def pods_with_firebase_fix
  pod 'GoogleUtilities/ISASwizzler'
  pod 'GoogleUtilities/NSData+zlib'
end
```

Looks like it's works for now... thank you very much for help! 🙏
