### ISSUE TITLE
FirebaseFirestoreSwift not found SPM 7.0

### ISSUE THREAD

**Issue by rrozenv** [firebase/firebase-ios-sdk#6989]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.2
  * Firebase SDK version: 7.0-spm-beta
  * Installation method: `Swift Package Manager` 
  * Firebase Component: FirebaseFirestoreSwfit

#### Steps to reproduce:

When using SPM and specifying `.branch("7.0-spm-beta")` there is a package loading error which reads "product 'FirebaseFirestoreSwift' not found."

Specifying `.branch("6.34-spm-beta")` does not cause this error and everything works as expected. 

Below is my Package.swift file

#### Relevant Code:

```
let package = Package(
    name: "QuarkFirebase",
	platforms: [
		.iOS(.v14),
    ],
    products: [
        .library(
            name: "QuarkFirebase",
            targets: ["QuarkFirebase"])
    ],
    dependencies: [
		.package(
			name: "Firebase",
			url: "git@github.com:firebase/firebase-ios-sdk.git",
			.branch("7.0-spm-beta")
		)
    ],
    targets: [
        .target(
            name: "QuarkFirebase",
            dependencies: [
		.product(name: "FirebaseFirestore", package: "Firebase"),
	        .product(name: "FirebaseFirestoreSwift", package: "Firebase")
                .product(name: "FirebaseAuth", package: "Firebase"),
                .product(name: "FirebaseStorage", package: "Firebase"),
                .product(name: "FirebaseDatabase", package: "Firebase"),
		.product(name: "FirebaseDynamicLinks", package: "Firebase"),
            ]
		)
    ]
)
```

**Comment by paulb777** [comment]
Starting with the 7.0.0 release, `FirebaseFirestoreSwift` was renamed to `FirebaseFirestoreSwift-Beta` to more clearly indicate its beta status.

Also note that both 7.0.0 and 7.1.0 are now available as Swift Package Manager versioned releases. See https://github.com/firebase/firebase-ios-sdk/blob/master/SwiftPackageManager.md
