### ISSUE TITLE
Add the ability to see Apple silicon specific crashes in Crashlytics

### ISSUE THREAD

**Issue by icecrystal23** [firebase/firebase-ios-sdk#6999]
We just shipped support for Apple silicon macs in our app, and we'd like to clearly see crashes for these users in Crashlytics. Currently these users are reported as being on iPad devices, so we can't see or filter on mac specific crashes.

You can do this check at runtime using `NSProcessInfo.processInfo.isiOSAppOnMac`

**Comment by skuske** [comment]
As long as this is not officially supported, we solve this by setting a custom property:

```
    if (@available(iOS 14.0, *)) {
            [[FIRCrashlytics crashlytics] setCustomValue:@([NSProcessInfo processInfo].isiOSAppOnMac) forKey:@"IsOnMac"];
    }
    else
    {
        [[FIRCrashlytics crashlytics] setCustomValue:@(false) forKey:@"IsOnMac"];
    }
```

Maybe that helps someone ...

**Comment by hjh5696** [comment]
Hi, is it now officially supported in Crashlytics?

**Comment by samedson** [comment]
Hey @hjh5696, crashlytics now supports filtering on Apple Silicon in the console now. If you go down to your filters you should see "Desktop" in the Device filter:
<img width="902" alt="Screen Shot 2022-02-03 at 1 51 14 PM" src="https://user-images.githubusercontent.com/555046/152409268-73aa42d9-4afa-42a9-a251-6cd4ab705eba.png">
