### ISSUE TITLE
firebase carthage not working 

### ISSUE THREAD

**Issue by vijayvishesh** [firebase/firebase-ios-sdk#7006]
Hello team 
i have try to install the firebase carthage in my system  but i am getting the issue
<img width="691" alt="Screenshot 2020-11-21 at 1 34 31 PM" src="https://user-images.githubusercontent.com/34429705/99871288-0c6c2180-2bff-11eb-836b-9f57c3f96b5b.png">
<img width="263" alt="Screenshot 2020-11-21 at 1 34 55 PM" src="https://user-images.githubusercontent.com/34429705/99871291-0f671200-2bff-11eb-999c-056c04622ef2.png">
<img width="443" alt="Screenshot 2020-11-21 at 1 35 52 PM" src="https://user-images.githubusercontent.com/34429705/99871293-10983f00-2bff-11eb-8428-4c34f60b803d.png">

**Comment by morganchen12** [comment]
Make sure the FirebaseCore framework is linked into the app target (Link Binary with Libraries, under "Build Phases").

**Comment by paulb777** [comment]
@vijayvishesh If you're running on a new Apple Mac, see #7007

**Comment by ryanwilson** [comment]
@vijayvishesh another thing to check - are you using a new Apple silicon run Mac? If so, we cannot support arm64 simulator slices with Carthage since it doesn't support `.xcframework`s yet. See https://github.com/Carthage/Carthage/issues/2799 for more information.
