### ISSUE TITLE
FR: Add missing support for Apple Silicon Mac Catalyst apps when integrating Firebase manually with xcframeworks.

### ISSUE THREAD

**Issue by stephanejais** [firebase/firebase-ios-sdk#7007]
### Feature proposal

* Add the missing Apple Silicon slices to the maccatalyst variant of the xcframeworks in Firebase.zip.

The Release 7.1.0 of Firebase.zip containing all the .xcframeworks for manual integration does not contain an arm64 slice for the maccatalyst variant.
As a result, when creating an archive for "Any Mac (Apple Silicon, Intel)", linking fails with the following errors:
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FIRApp", referenced from:
      objc-class-ref in XXX
  "_OBJC_CLASS_$_FIRCrashlytics", referenced from:
      objc-class-ref in XXXX
  "_OBJC_CLASS_$_FIRDatabase", referenced from:
      objc-class-ref in XXX
  "_OBJC_CLASS_$_FIRRemoteConfig", referenced from:
      objc-class-ref in XXX
  "_OBJC_CLASS_$_FIRTransactionResult", referenced from:
      objc-class-ref in XXX
...
```

**Comment by paulb777** [comment]
@stephanejais We currently have no plans to enable Apple Silicon simulator support via Catalyst primarily because Carthage does not support `.xcframeworks`. See https://github.com/Carthage/Carthage/issues/2799

**Comment by stephanejais** [comment]
> @stephanejais We currently have no plans to enable Apple Silicon simulator support via Carthage primarily because Carthage does not support `.xcframeworks`. See [Carthage/Carthage#2799](https://github.com/Carthage/Carthage/issues/2799)

@paulb777 That's not what I'm asking: I just want to ship Firebase in my Mac Catalyst universal app and I need to link for the Apple Silicon arch.

**Comment by paulb777** [comment]
@stephanejais Oops, sorry for the misunderstanding. I juxtaposed your issue with the previous one. 

It should be feasible to add the catalyst arm64 simulator slice. We'll investigate.

**Comment by ryanwilson** [comment]
Hmm this isn't as straightforward as I would have hoped, but still working on it. 

Using this build command: 

```
/Applications/Xcode_12.0.1.app/Contents/Developer/usr/bin/xcodebuild build -configuration release -workspace /var/folders/qc/rcfpdrfj7694bf2fjgx90yq800_dx3/T/ZipRelease/2020-11-25T11-45-55/project/FrameworkMaker.xcworkspace -scheme nanopb GCC_GENERATE_DEBUGGING_SYMBOLS=NO ARCHS=arm64 VALID_ARCHS=arm64 ONLY_ACTIVE_ARCH=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES SUPPORTS_MACCATALYST=YES BUILD_DIR=/var/folders/qc/rcfpdrfj7694bf2fjgx90yq800_dx3/T/ZipRelease/2020-11-25T11-45-55/project/macosx -sdk macosx "OTHER_CFLAGS=$(value) -DFIREBASE_BUILD_ZIP_FILE" CODE_SIGN_IDENTITY=-
```

Results in a warning: 
```
warning: There are no architectures to compile for because all architectures in VALID_ARCHS (arm64) are also in EXCLUDED_ARCHS (arm64, arm64e). (in target 'nanopb' from project 'Pods')
```

I'm wondering if the `SUPPORTS_MACCATALYST` is internally overriding the `arm64` flag. I'll keep digging and see what I can find out. Thanks for the report!

**Comment by carlo-** [comment]
@ryanwilson I believe you have to use Xcode 12.2 to build for Apple Silicon, and it looks like you're using 12.0.1

**Comment by ryanwilson** [comment]
@carlo- thanks I'll give that a go - I do believe I tried with 12.2 before and saw the same results, but I'll try it again.

**Comment by ryanwilson** [comment]
Would you look at that - looks like it was another case of having too many Xcode versions installed, I must have forgotten to run `xcode-select` in my testing. Thanks for pointing it out! It brings up a bit of a challenge since the majority of developers are still using an older Xcode version and it's not backwards compatible, but we'll chat within the team and figure something out.

**Comment by ryanwilson** [comment]
#7044 to fix the technical issue, still need to sort out the distribution and Xcode version challenge.

**Comment by paulb777** [comment]
While we still need to support Xcode 12.0 binaries in the default distribution, one approach would be providing instructions for self-building with newer Xcode versions.

**Comment by steipete** [comment]
I've given enabling Crashlytics for Catalyst another chance with the 7.6 release, but above is a blocker. I'm unable to run our app in the Simulator on Apple Silicon anymore, so have to remove Crashlytics again for now.

**Comment by paulb777** [comment]
Thanks for letting us know. We'll consider bumping the minimum supported version with the zip distribution to Xcode 12.2 in the Firebase 7.7.0 release. @ryanwilson What do you think?

**Comment by ryanwilson** [comment]
SGTM - let's build with Xcode 12.2 for the zip to ensure this use case is supported. Thanks for revisiting @steipete!

**Comment by steipete** [comment]
Thanks folks, much appreciated!!
