### ISSUE TITLE
port_stdcxx.h line 77 error with LevelDB

### ISSUE THREAD

**Issue by kanishk-watt** [firebase/firebase-ios-sdk#7010]
* Xcode version:  12.2
  * Firebase SDK version: Firebase - 6.22.0, FirebaseCore - 6.6.6, FirebaseDatabase - 6.1.4, FirebaseCrashlytics - 4.0.0, LevelDB-library - 1.22
  * Installation method: CocoaPods
  * Firebase Component:  Database, LevelDB

Not sure how this error is occurring but found the following crash reports in Crashlytics

```
> Thread
> 0  libsystem_kernel.dylib         0x1cf96672c __psynch_cvwait + 8
> 1  libsystem_pthread.dylib        0x1eab32c88 _pthread_cond_wait$VARIANT$armv81 + 1180
> 2  libc++.1.dylib                 0x1b8701e0c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
> 3  Watt                           0x100ec049c leveldb::(anonymous namespace)::PosixEnv::BackgroundThreadMain() + 77 (port_stdcxx.h:77)
> 4  Watt                           0x100ec044c leveldb::(anonymous namespace)::PosixEnv::BackgroundThreadMain() + 779 (env_posix.cc:779)
> 5  Watt                           0x100ec0530 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(leveldb::(anonymous namespace)::PosixEnv*), leveldb::(anonymous namespace)::PosixEnv*> >(void*) + 181 (tuple:181)
> 6  libsystem_pthread.dylib        0x1eab35b70 _pthread_start + 288
> 7  libsystem_pthread.dylib        0x1eab3a880 thread_start + 8


> com.apple.uikit.eventfetch-thread
> 0  libsystem_kernel.dylib         0x1cf9438c4 mach_msg_trap + 8
> 1  libsystem_kernel.dylib         0x1cf942cc8 mach_msg + 72
> 2  CoreFoundation                 0x1a4d4874c __CFRunLoopServiceMachPort + 376
> 3  CoreFoundation                 0x1a4d42bd0 __CFRunLoopRun + 1176
> 4  CoreFoundation                 0x1a4d42200 CFRunLoopRunSpecific + 572
> 5  Foundation                     0x1a5f50278 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 228
> 6  Foundation                     0x1a5f50158 -[NSRunLoop(NSRunLoop) runUntilDate:] + 88
> 7  UIKitCore                      0x1a76b7748 -[UIEventFetcher threadMain] + 504
> 8  Foundation                     0x1a60acc48 __NSThread__start__ + 848
> 9  libsystem_pthread.dylib        0x1eab35b70 _pthread_start + 288
> 10 libsystem_pthread.dylib        0x1eab3a880 thread_start + 8


> com.google.firebase.crashlytics.MachExceptionServer
> 0  Watt                           0x100b22de0 FIRCLSProcessRecordAllThreads + 392 (FIRCLSProcess.c:392)
> 1  Watt                           0x100b231c4 FIRCLSProcessRecordAllThreads + 423 (FIRCLSProcess.c:423)
> 2  Watt                           0x100b19b88 FIRCLSHandler + 34 (FIRCLSHandler.m:34)
> 3  Watt                           0x100b1c4bc FIRCLSMachExceptionServer + 524 (FIRCLSMachException.c:524)
> 4  libsystem_pthread.dylib        0x1eab35b70 _pthread_start + 288
> 5  libsystem_pthread.dylib        0x1eab3a880 thread_start + 8
```

Please help with this as many users faced this crash on prod.

**Comment by paulb777** [comment]
Please share the full crash report.  It may help to update to a more recent Firebase version.

**Comment by kanishk-watt** [comment]
here is the further crash report... 

> com.apple.NSURLConnectionLoader
> 0  libsystem_kernel.dylib         0x1cf9438c4 mach_msg_trap + 8
> 1  libsystem_kernel.dylib         0x1cf942cc8 mach_msg + 72
> 2  CoreFoundation                 0x1a4d4874c __CFRunLoopServiceMachPort + 376
> 3  CoreFoundation                 0x1a4d42bd0 __CFRunLoopRun + 1176
> 4  CoreFoundation                 0x1a4d42200 CFRunLoopRunSpecific + 572
> 5  CFNetwork                      0x1a55cf9a4 _CFURLStorageSessionCopyCache + 59740
> 6  Foundation                     0x1a60acc48 __NSThread__start__ + 848
> 7  libsystem_pthread.dylib        0x1eab35b70 _pthread_start + 288
> 8  libsystem_pthread.dylib        0x1eab3a880 thread_start + 8


> com.squareup.SocketRocket.NetworkThread
> 0  libsystem_kernel.dylib         0x1cf9438c4 mach_msg_trap + 8
> 1  libsystem_kernel.dylib         0x1cf942cc8 mach_msg + 72
> 2  CoreFoundation                 0x1a4d4874c __CFRunLoopServiceMachPort + 376
> 3  CoreFoundation                 0x1a4d42bd0 __CFRunLoopRun + 1176
> 4  CoreFoundation                 0x1a4d42200 CFRunLoopRunSpecific + 572
> 5  Foundation                     0x1a5f50278 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 228
> 6  Watt                           0x100b81394 -[_FSRRunLoopThread main] + 1845 (FSRWebSocket.m:1845)
> 7  Foundation                     0x1a60acc48 __NSThread__start__ + 848
> 8  libsystem_pthread.dylib        0x1eab35b70 _pthread_start + 288
> 9  libsystem_pthread.dylib        0x1eab3a880 thread_start + 8


> com.apple.CFSocket.private
> 0  libsystem_kernel.dylib         0x1cf966c10 __select + 8
> 1  libsystem_kernel.dylib         0x1cf966c10 select$DARWIN_EXTSN + 8
> 2  CoreFoundation                 0x1a4d54af4 __CFSocketManager + 620
> 3  libsystem_pthread.dylib        0x1eab35b70 _pthread_start + 288
> 4  libsystem_pthread.dylib        0x1eab3a880 thread_start + 8

> com.apple.CoreMotion.MotionThread
> 0  libsystem_kernel.dylib         0x1cf9438c4 mach_msg_trap + 8
> 1  libsystem_kernel.dylib         0x1cf942cc8 mach_msg + 72
> 2  CoreFoundation                 0x1a4d4874c __CFRunLoopServiceMachPort + 376
> 3  CoreFoundation                 0x1a4d42bd0 __CFRunLoopRun + 1176
> 4  CoreFoundation                 0x1a4d42200 CFRunLoopRunSpecific + 572
> 5  CoreFoundation                 0x1a4d432c0 CFRunLoopRun + 60
> 6  CoreMotion                     0x1af56a374 CLClientCreateIso6709Notation + 176400
> 7  libsystem_pthread.dylib        0x1eab35b70 _pthread_start + 288
> 8  libsystem_pthread.dylib        0x1eab3a880 thread_start + 8


> AVAudioSession Notify Thread
> 0  libsystem_kernel.dylib         0x1cf9438c4 mach_msg_trap + 8
> 1  libsystem_kernel.dylib         0x1cf942cc8 mach_msg + 72
> 2  CoreFoundation                 0x1a4d4874c __CFRunLoopServiceMachPort + 376
> 3  CoreFoundation                 0x1a4d42bd0 __CFRunLoopRun + 1176
> 4  CoreFoundation                 0x1a4d42200 CFRunLoopRunSpecific + 572
> 5  AudioSession                   0x1ac24b158 GenericRunLoopThread::Entry(void*) + 156
> 6  AudioSession                   0x1ac24d0b8 CAPThread::Entry(CAPThread*) + 88
> 7  libsystem_pthread.dylib        0x1eab35b70 _pthread_start + 288
> 8  libsystem_pthread.dylib        0x1eab3a880 thread_start + 8


> Thread
> 0  libsystem_kernel.dylib         0x1cf96758c __workq_kernreturn + 8
> 1  libsystem_pthread.dylib        0x1eab375f0 _pthread_wqthread + 348
> 2  libsystem_pthread.dylib        0x1eab3a874 start_wqthread + 8

> Thread
> 0  libsystem_kernel.dylib         0x1cf96758c __workq_kernreturn + 8
> 1  libsystem_pthread.dylib        0x1eab375f0 _pthread_wqthread + 348
> 2  libsystem_pthread.dylib        0x1eab3a874 start_wqthread + 8

> Thread
> 0  libsystem_kernel.dylib         0x1cf96758c __workq_kernreturn + 8
> 1  libsystem_pthread.dylib        0x1eab375f0 _pthread_wqthread + 348
> 2  libsystem_pthread.dylib        0x1eab3a874 start_wqthread + 8


Thanks in advance

**Comment by morganchen12** [comment]
There's no exception/crash in either of these stacks. Are you sure this is the full stack trace?

**Comment by kanishk-watt** [comment]
Yeah , this is all I have in Crashlytics

**Comment by morganchen12** [comment]
@kanishk-watt unfortunately there's not enough information in just this stack trace for us to identify a crash or effectively debug it. If you have more information, like a reproducible example, please feel free to share and we'll re-open this issue.
