### ISSUE TITLE
FR: Firebase Dynamic Links directly open the App Clips

### ISSUE THREAD

**Issue by DanMotataeanu** [firebase/firebase-ios-sdk#7027]
### Feature proposal

* Firebase Component: Dynamic Links

Hello,

I was trying to create a dynamic link for one of my apps, and under Android in the Firebase Console I can find the option if the user does not have the app installed to be sent to Instant App page. 

Unfortunately, creating the same behaviour on iOS is not working.

**Comment by chliangGoogle** [comment]
@DanMotataeanu Just to clarify, is the dynamic link not able to trigger your App Clips or your main iOS app's Apple store page?

**Comment by pot2mayo** [comment]
I'm having the same issue here.
Anyone found a way to have the firebase dynamic link feature to trigger an app clip?

**Comment by enes-get-local** [comment]
@chliangGoogle Hi, any update on this ?

**Comment by sirwes** [comment]
We also want Firebase Dynamic Links to point to the app clip. Not having this functionality is pretty debilitating for our use case.

**Comment by jjjeeerrr222** [comment]
Any update on this? Seems like we just need to edit the apple-app-site-association file to include the appclip information we need.

**Comment by sirwes** [comment]
A bad workaround would be to have the FDL redirect to a webpage that has a smart app banner, then the user clicks that banner which redirects them to the app clip

**Comment by jjjeeerrr222** [comment]
Yea that’s what I did but it’s not ideal

**Comment by charlotteliang** [comment]
@sirwes and @jjjeeerrr222 We brought this issue to the team and in the meantime please upvote the Original Post to help the team prioritize.

**Comment by cavalos0086** [comment]
Thanks for the comments and sorry for the inconvenient. As of now, the workaround mentioned above is the best workaround. As mentioned by Charlotte, please upvote the original post to help prioritize. 

Thanks

**Comment by jjjeeerrr222** [comment]
Adding the appclip key to the apple-app-site-association file on my website worked properly so if I’m not mistaken doing the same the FB AASA file should work as well

**Comment by jjjeeerrr222** [comment]
The only issue with this workaround is that the dynamic link always opens to the preview page even though i tried to disable it.

So user clicks DL -> preview page -> opens my own website -> open app clip. This can be streamlined to go right into the app clip link with instant apps on android

**Comment by paulb777** [comment]
Now that [Firebase DynamicLinks is planned to shut down](https://firebase.google.com/support/dynamic-links-faq), closing its feature requests.
