### ISSUE TITLE
"___darwin_check_fd_set_overflow", referenced from:

### ISSUE THREAD

**Issue by RaknasAvis** [firebase/firebase-ios-sdk#7040]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.2.1
  * Firebase SDK version: 7.1.0
  * Installation method: Zip file
  * Firebase Component: FirebaseCrashlytics and FirebaseAnalytics 

#### Steps to reproduce:

Recently we moved crashlytics to firebase framework. In Xcode 11.2.1, we faced this problem "___darwin_check_fd_set_overflow", referenced from:

But if i use Xcode 12 then not able to see the compiler error, for some reasons we need to use Xcode 11.2.1 only 
Is there any workaround to resolve this issue?

#### Relevant Code:

```
 FirebaseApp.configure()
```

**Comment by morganchen12** [comment]
Looks like this may be caused by a bad build config, possibly from another pod. Do you see the `FD_SET` macro set anywhere in your project?

**Comment by paulb777** [comment]
Also, please let us know the full error message.  Where is `___darwin_check_fd_set_overflow` referenced from?

**Comment by RaknasAvis** [comment]
Hi,

The "FD_SET" macro is not set anywhere in the project.
The "___darwin_check_fd_set_overflow" is referenced from third party
library which i cant reveal.

But if I don't add firebase to the project then I am able to build the
project.

**Comment by paulb777** [comment]
My best guess is that the third party library was built with Xcode 12 and it only happens to get linked when Firebase is added to the project.

We'll likely need a repro or more specific details about a Firebase issue to help more.
