### ISSUE TITLE
FR: [FirebaseFirestoreSwift] Add new propertyWrapper for updatedAt.

### ISSUE THREAD

**Issue by fummicc1** [firebase/firebase-ios-sdk#7041]
### Feature proposal

* Firebase Component: FirebaseFirestoreSwift

I usually use FirebaseFirestoreSwift to encode/decode Model and communicate with Firestore easily like the following.

```swift
protocol FirestoreModel: Codable {
    static var collectionName: String { get }
    var ref: DocumentReference? { get }
    var updatedAt: Timestamp? { get set }
}

extension Entity {
    struct User: FirestoreModel {       

        static var collectionName: String = "users"
        
        @DocumentID
        var ref: DocumentReference?
        @ServerTimestamp
        var createdAt: Timestamp?
        var updatedAt: Timestamp?
    }
}
```

All I suffer from is how to handle `updatedAt` which knows when model is stored lastly in Cloud Firestore.
I try using `FieldValue.serverTimestamp()` but it is not well because type is `FieldValue`.

```swift
func write<Model: FirestoreModel>(_ model: Model, merge: Bool, success: @escaping () -> Void, failure: @escaping (Error) -> Void) {        
    do {
        let ref: DocumentReference
        if let modelRef = model.ref {
            ref = modelRef
        } else {
            ref = firestore.collection(Model.collectionName).document()
        }
        var model = model
        model.updatedAt = FieldValue.serverTimestamp() // This line has an error...!
        try ref.setData(from: model, merge: merge) { (error) in
            if let error = error {
                failure(error)
                return
            }
            success()
        }
    } catch {
        failure(error)
    }
}
```

I want a new propertywrapper to automatically store when model has been stored lastly.

**Comment by dconeybe** [comment]
Hi @fummicc1. I believe the functionality that you're looking for already exists. You just need to annotate the `updatedAt` field with `@ServerTimestamp` and set it to `nil` prior to calling `setData()`. This will cause the server to set the value to its current timestamp.

See the comment here for details: https://github.com/firebase/firebase-ios-sdk/blob/eb21690b803cbbad83a8ad2fa51d43fd1f3fa2b4/Firestore/Swift/Source/Codable/ServerTimestamp.swift#L57-L72
Does this address your request?

**Comment by fummicc1** [comment]
Hello, @dconeybe. I was understanding `ServerTimeStamp` is used for `createdAt` which is updated at the first time when document creates, but ,as you refer, it is also possible for `ServerTimeStamp` to be used for `updatedAt` by setting `nil` as `updatedAt` prior to calling `setData()`...

Thank you for your reply. That addreddes my request:).

**Comment by dconeybe** [comment]
That's great! I wish all issues were this easy to resolve :) All the best.
