### ISSUE TITLE
Multiple commands produce error GTMSessionFetcher

### ISSUE THREAD

**Issue by DieGlueckswurst** [firebase/firebase-ios-sdk#7046]
### Step 0: Are you in the right place?
yes
  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: ___12.2__
  * Firebase SDK version: ___6.5.0__
  * Installation method: `CocoaPods | Carthage | Zip file | Swift Package Manager` (select one)
  * Firebase Component: ___Auth, Core, Database, Firestore, Storage, Analytics, Crashlytics__ (Auth, Core, Database, Firestore, Messaging, Storage, etc)

### [REQUIRED] Step 2: Describe the problem

I am trying to `archive` my project so I can upload it to the App-Store but it fails with this message:

> Multiple commands produce '/Users/chris/Library/Developer/Xcode/DerivedData/Wishlist-dfzwspzvafhpoveskdfxsqijlbtl/Build/Intermediates.noindex/ArchiveIntermediates/Wishlists/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GTMSessionFetcher.framework':
1) Target 'GTMSessionFetcher-Core' has create directory command with output '/Users/chris/Library/Developer/Xcode/DerivedData/Wishlist-dfzwspzvafhpoveskdfxsqijlbtl/Build/Intermediates.noindex/ArchiveIntermediates/Wishlists/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GTMSessionFetcher.framework'
2) Target 'GTMSessionFetcher.default-Core' has create directory command with output '/Users/chris/Library/Developer/Xcode/DerivedData/Wishlist-dfzwspzvafhpoveskdfxsqijlbtl/Build/Intermediates.noindex/ArchiveIntermediates/Wishlists/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GTMSessionFetcher.framework'

I also get these warning when building the project:

> Multiple targets match implicit dependency for linker flags '-framework GTMSessionFetcher'. Consider adding an explicit dependency on the intended target to resolve this ambiguity. (in target 'Wishlists' from project 'Wishlists')

> Target 'GTMSessionFetcher-Core' (in project 'Pods')

> Target 'GTMSessionFetcher.default-Core' (in project 'Pods')

And the same for my other target `ShareExtension`.

#### Steps to reproduce:

I have a Main-App and Share extension with this `podfile`:

```
# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Wishlists' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wishlists

	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
	pod 'Firebase/Core'
	pod 'Firebase/Firestore'
	pod 'Firebase/Database'
	pod 'Firebase/Crashlytics'
	#pod 'TextFieldEffects'
	pod 'Hero'
	pod 'RevealingSplashView'
	pod 'LBTAComponents'
	pod 'lottie-ios'
	pod 'SwiftEntryKit', '1.2.3'
	pod 'FBSDKCoreKit'
	pod 'FBSDKShareKit'
	pod 'FBSDKLoginKit'
	pod 'GoogleSignIn'
	pod 'SkeletonView'
	pod 'SwiftSoup'
	pod 'Firebase/Storage'
	pod 'Kingfisher', '~> 5.0'
	pod 'KeychainAccess'

end

target 'ShareExtension' do 
 
 use_frameworks!

	pod 'SwiftSoup'
	pod 'URLEmbeddedView'
	pod 'lottie-ios'
	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
	pod 'Firebase/Core'
	pod 'Firebase/Firestore'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'
	pod 'Kingfisher', '~> 5.0'	

end
```

Try building it (will result in warning)  and try archiving it to see the error.

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulb777** [comment]
Looks like a variation of #6983 with GTMSessionFetcher instead of GoogleUtilities. The workaround should be simillar.

**Comment by paulb777** [comment]
Going to close based on other issues open and known workarounds. Feel free to continue the discussion here if you have additional questions.
