### ISSUE TITLE
Security Issues

### ISSUE THREAD

**Issue by FelipeABastos** [firebase/firebase-ios-sdk#7047]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.2
  * Firebase SDK version: 6.33.0
  * Installation method: CocoaPods
  * Firebase Component: Analytics

### [REQUIRED] Step 2: Describe the problem

After going through a battery of tests, security problems have returned. I'll quote them below.

#### (SAST - BufferOverflow.BufferSizeOutOfBounds)
```
\Pods\GoogleDataTransportCCTSupport\GoogleDataTransportCCTSupport\GDTCCTLibrary\GDTCCTNanopbHelpers.m:144
```
#### (SAST - PathTraversal)
```
\Pods\FirebaseCore\FirebaseCore\Sources\FIRApp.m:69
\Pods\FirebaseCore\FirebaseCore\Sources\FIRLogger.m:41
\Pods\GoogleUtilities\GoogleUtilities\Network\GULNetwork.m:46
```
#### (SAST - Cryptography.InsecureAlgorithm)
```
\Pods\FirebaseInstallations\FirebaseInstallations\Source\Library\IIDMigration\FIRInstallationsIIDStore.m:87
\Pods\FirebaseInstallations\FirebaseInstallations\Source\Library\IIDMigration\FIRInstallationsIIDStore.m:91
```
#### (SAST - PathTraversal)
```
\Pods\FirebaseCore\FirebaseCore\Sources\FIRApp.m:69
\Pods\FirebaseCore\FirebaseCore\Sources\FIRLogger.m:41
\Pods\GoogleUtilities\GoogleUtilities\Network\GULNetwork.m:46
```
#### (CWE-131 - Incorrect Calculation of Buffer Size)
```
\Pods\GoogleDataTransportCCTSupport\GoogleDataTransportCCTSupport\GDTCCTLibrary\GDTCCTNanopbHelpers.m:144
```

**Comment by maksymmalyhin** [comment]
@FelipeABastos Thank you for the report.

I briefly reviewed the highlighted code and didn't notice any issues for most of the cases, so it mostly looks like false positive cases which is possible for static analysis tools. Could you please provide more detailed explanation why the mentioned code may have the security issue to better understand if there is an actual issue there. 

The notes with questions per case: 
- \Pods\FirebaseInstallations\FirebaseInstallations\Source\Library\IIDMigration\FIRInstallationsIIDStore.m: I guess usage of SHA1 was highlighted as a problem. [Explanation of why it is used and why it is not an issue in this particular case](https://github.com/firebase/firebase-ios-sdk/blob/eb21690b803cbbad83a8ad2fa51d43fd1f3fa2b4/FirebaseInstallations/Source/Library/IIDMigration/FIRInstallationsIIDStore.m#L86) has been added to the comments in recent version. Please let us know if you still have any concerns on it.

- [\Pods\FirebaseCore\FirebaseCore\Sources\FIRApp.m:69](https://github.com/firebase/firebase-ios-sdk/blob/release-6.33.0/FirebaseCore/Sources/FIRApp.m#L69), [\Pods\FirebaseCore\FirebaseCore\Sources\FIRLogger.m:41](https://github.com/firebase/firebase-ios-sdk/blob/release-6.33.0/FirebaseCore/Sources/FIRLogger.m#L41): the lines contain  keys to be used to store data in user default. Could you please clarify what `(SAST - PathTraversal)` means in this context and why it may be a problem for this use case? 

- [\Pods\GoogleUtilities\GoogleUtilities\Network\GULNetwork.m:46](https://github.com/firebase/firebase-ios-sdk/blob/release-6.33.0/GoogleUtilities/Network/GULNetwork.m#L46): it's just a string to be to mark logs from the particular library. I guess presence `/` of symbol made it looking like a file system path. Do you have any details why it may be an issue?

- [\Pods\GoogleDataTransportCCTSupport\GoogleDataTransportCCTSupport\GDTCCTLibrary\GDTCCTNanopbHelpers.m:144](https://github.com/firebase/firebase-ios-sdk/blob/release-6.33.0/GoogleDataTransport/GDTCCTLibrary/GDTCCTNanopbHelpers.m#L144): the buffer size calculation looks correct to me. Do you have any details on why it is marked as an issue?
