### ISSUE TITLE
[Crashlytics] Failed uploading cSYMs due to an unknown error when trying to archive the app

### ISSUE THREAD

**Issue by Gustavo-Shotl** [firebase/firebase-ios-sdk#7048]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0
  * Firebase SDK version:
    - Firebase/Crashlytics (6.18.0):
      - Firebase/CoreOnly
      - FirebaseCrashlytics (~> 4.0.0-beta.4)
  * Installation method: CocoaPods
  * Firebase Component: Crashlytics

### [REQUIRED] Step 2: Describe the problem
    error: Failed uploading cSYMs due to error: Error Domain=com.google.firebase.crashlytics.FIRCLSCompoundOperation.error Code=4294967293 "(null)" UserInfo={com.google.firebase.crashlytics.FIRCLSCompoundOperation.error.user-info-key.underlying-errors=(
    "Error Domain=com.crashlytics.mac.error-domain.submit-csym Code=0 \"Failed to submit cSYM for architecture arm64 with uuid fc1a92ef14a93eb7a2afbbf49311f2dd in dSYM: /Users/user/Library/Developer/Xcode/DerivedData/shotl-gbfvqguszkynebccbahbqntcdtzz/Build/Intermediates.noindex/ArchiveIntermediates/elMeuBus/BuildProductsPath/Release-iphoneos/elMeuBus.app.dSYM\" UserInfo={NSLocalizedFailureReason=Failed to submit cSYM for architecture arm64 with uuid fc1a92ef14a93eb7a2afbbf49311f2dd in dSYM: /Users/user/Library/Developer/Xcode/DerivedData/shotl-gbfvqguszkynebccbahbqntcdtzz/Build/Intermediates.noindex/ArchiveIntermediates/elMeuBus/BuildProductsPath/Release-iphoneos/elMeuBus.app.dSYM, NSUnderlyingError=0x7f805800f600 {Error Domain=FIRCLSNetworkError Code=-6 \"(null)\" UserInfo={retryLimit=10, NSErrorFailingURLStringKey=https://cm.crashlytics.com/api/v3/platforms/ios/code_mappings}}}",
    "Error Domain=com.crashlytics.mac.error-domain.submit-csym Code=0 \"Failed to submit cSYM for architecture armv7 with uuid 1675c522d3673c489b932050251833f6 in dSYM: /Users/user/Library/Developer/Xcode/DerivedData/shotl-gbfvqguszkynebccbahbqntcdtzz/Build/Intermediates.noindex/ArchiveIntermediates/elMeuBus/BuildProductsPath/Release-iphoneos/elMeuBus.app.dSYM\" UserInfo={NSLocalizedFailureReason=Failed to submit cSYM for architecture armv7 with uuid 1675c522d3673c489b932050251833f6 in dSYM: /Users/user/Library/Developer/Xcode/DerivedData/shotl-gbfvqguszkynebccbahbqntcdtzz/Build/Intermediates.noindex/ArchiveIntermediates/elMeuBus/BuildProductsPath/Release-iphoneos/elMeuBus.app.dSYM, NSUnderlyingError=0x7f8058018710 {Error Domain=FIRCLSNetworkError Code=-6 \"(null)\" UserInfo={retryLimit=10, NSErrorFailingURLStringKey=https://cm.crashlytics.com/api/v3/platforms/ios/code_mappings}}}")}

    error: Could not complete submission of dSYM at /Users/user/Library/Developer/Xcode/DerivedData/shotl-gbfvqguszkynebccbahbqntcdtzz/Build/Intermediates.noindex/ArchiveIntermediates/elMeuBus/BuildProductsPath/Release-iphoneos/elMeuBus.app.dSYM: Error Domain=com.google.firebase.crashlytics.FIRCLSCompoundOperation.error Code=4294967293 "(null)" UserInfo={com.google.firebase.crashlytics.FIRCLSCompoundOperation.error.user-info-key.underlying-errors=(
    "Error Domain=com.crashlytics.mac.error-domain.submit-csym Code=0 \"Failed to submit cSYM for architecture arm64 with uuid fc1a92ef14a93eb7a2afbbf49311f2dd in dSYM: /Users/user/Library/Developer/Xcode/DerivedData/shotl-gbfvqguszkynebccbahbqntcdtzz/Build/Intermediates.noindex/ArchiveIntermediates/elMeuBus/BuildProductsPath/Release-iphoneos/elMeuBus.app.dSYM\" UserInfo={NSLocalizedFailureReason=Failed to submit cSYM for architecture arm64 with uuid fc1a92ef14a93eb7a2afbbf49311f2dd in dSYM: /Users/user/Library/Developer/Xcode/DerivedData/shotl-gbfvqguszkynebccbahbqntcdtzz/Build/Intermediates.noindex/ArchiveIntermediates/elMeuBus/BuildProductsPath/Release-iphoneos/elMeuBus.app.dSYM, NSUnderlyingError=0x7f805800f600 {Error Domain=FIRCLSNetworkError Code=-6 \"(null)\" UserInfo={retryLimit=10, NSErrorFailingURLStringKey=https://cm.crashlytics.com/api/v3/platforms/ios/code_mappings}}}",
    "Error Domain=com.crashlytics.mac.error-domain.submit-csym Code=0 \"Failed to submit cSYM for architecture armv7 with uuid 1675c522d3673c489b932050251833f6 in dSYM: /Users/user/Library/Developer/Xcode/DerivedData/shotl-gbfvqguszkynebccbahbqntcdtzz/Build/Intermediates.noindex/ArchiveIntermediates/elMeuBus/BuildProductsPath/Release-iphoneos/elMeuBus.app.dSYM\" UserInfo={NSLocalizedFailureReason=Failed to submit cSYM for architecture armv7 with uuid 1675c522d3673c489b932050251833f6 in dSYM: /Users/user/Library/Developer/Xcode/DerivedData/shotl-gbfvqguszkynebccbahbqntcdtzz/Build/Intermediates.noindex/ArchiveIntermediates/elMeuBus/BuildProductsPath/Release-iphoneos/elMeuBus.app.dSYM, NSUnderlyingError=0x7f8058018710 {Error Domain=FIRCLSNetworkError Code=-6 \"(null)\" UserInfo={retryLimit=10, NSErrorFailingURLStringKey=https://cm.crashlytics.com/api/v3/platforms/ios/code_mappings}}}")}

Two weeks ago I did a deploy and everything was fine, today I tried to archive the application but this error won't let me do it

#### Steps to reproduce:

I have a build script phase called "Firebase Crashlytics" with the following statements:

    ${PODS_ROOT}/FirebaseCrashlytics/run

    ${PODS_ROOT}/FirebaseCrashlytics/upload-symbols" -gsp "${PROJECT_DIR}/elMeuBus/GoogleService-Info.plist" -p ios ${DWARF_DSYM_FOLDER_PATH}"

This phase runs last, after the other phases have run.

**Comment by morganchen12** [comment]
This looks like a network error, which could have been caused by a backend issue. If you try again now, does the error persist?

@samedson are you aware of any symbol-upload outages recently?

**Comment by Gustavo-Shotl** [comment]
Hello, I tried again and the error persist

**Comment by samedson** [comment]
@Gustavo-Shotl apologies for the confusion. To resolve this, you can upgrade to a non-beta Crashlytics SDK (any version above 4.0.0 or above 7.0.0), and make sure you update upload-symbols too if you're not using CocoaPods.

This beta version of upload-symbols sends symbols to an endpoint that has been shut down. In addition, the beta version of the Crashlytics SDK will no longer work.
