### ISSUE TITLE
Firebase Data Notification not being received

### ISSUE THREAD

**Issue by aruffolo** [firebase/firebase-ios-sdk#7072]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.1
  * Firebase SDK version: 7.1.0
  * Installation method: `CocoaPods `
  * Firebase Component: Crashlytics, Analytics, MLVision, Messaging, MLVisionTextModel

#### Steps to reproduce:

You can use the [quickstart](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Ffirebase%2Fquickstart-ios%2Ftree%2Fmaster%2Fmessaging&sa=D&sntz=1&usg=AFQjCNGonv7TT5_Vx85IF-bXhR-nzfMCfA) project for firebase messaging.

Read the token and then send this notification payload 20 times in a row

`{
  "content_available": true,
  "priority": "high",
  "data": {
    "pushCategory": "ALEXA",
    "body": "body",
    "message": "message",
    "title": "status/update",
    "updateStatus": {
      "operationId": "7fc0e1ff-cc0d-4045-8b30-69710bf80c24",
      "status": 0,
      "action": "makecoffee",
      "description": "",
      "stock": {
        "remaining": "91",
        "threshold": "10",
        "depletion": false
      }
    }
  },
  "to": "eKUNwaw8OEXgkjJVzWqgKs:APA91bEnA1tnG4dFtnjS_Djhu0PPk7L4iz7ZUY0EdUtl9hdGScmGc0cwBFW06ToXylPwmFxT-ioD9q9vTuj05-o4G9WQTNmq-rIaDkVz627IH1Noix-7glYaKUEiFG8T_ViVwdiUqW5A"
}`

What happens is that only the first four or five notifications will be received, after that a notification with some minutes delay will be received and all others notifications are lost.
We don't understand if we're not complying with something with the doc reference of the payload: [reference](https://firebase.google.com/docs/cloud-messaging/http-server-ref) or there is a bug somewhere between the server or the client SDK.
Specifically we see that this is a `Data` payload but we want it to be sent immediately, setting the `priority` has not effect.

If we use the same payload but we add the `notification` object all the 20 notifications are received immediately as we would expect:

`{
  "content_available": true,
  "priority": "high",
  "time_to_live": 600,
  "data": {
    "pushCategory": "ALEXA",
    "body": "body",
    "message": "message",
    "title": "status/update",
    "updateStatus": {
      "operationId": "9394cef4-e86b-4608-a605-311cbc68d930",
      "status": 0,
      "action": "makecoffee",
      "description": "",
      "stock": {
        "remaining": "0",
        "threshold": "10",
        "depletion": true
      }
    }
  },
  "notification": {
    "title": "Capsule Lavazza in esaurimento",
    "body": "Ti restano solo 0. Controlla la tua scorta e non restare senza. Ordina subito."
  },
  "to": "eKUNwaw8OEXgkjJVzWqgKs:APA91bEnA1tnG4dFtnjS_Djhu0PPk7L4iz7ZUY0EdUtl9hdGScmGc0cwBFW06ToXylPwmFxT-ioD9q9vTuj05-o4G9WQTNmq-rIaDkVz627IH1Noix-7glYaKUEiFG8T_ViVwdiUqW5A"
}`

Thanks

**Comment by morganchen12** [comment]
Based on your description, it sounds like the background notifications are being [throttled by the system](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app). If you wait some time and then send a new background notification, is it received as expected?

**Comment by aruffolo** [comment]
@morganchen12 thanks for the follow up. Yes if I wait some time then they are received as expected.
This is not what happens by using the rest calls of Apple API.
If I use this payload with Apple APNS servers:

```
{
 "aps": {
   "category": "SECRET",
   "badge": 0,
   "sound": 1
 },
 "pushCategory": "-----"
}
```
there is no throttling by the system. All of the 20 notifications sent in a row are delivered using the above payload by not setting any priority or by setting an high priority.

A notification without the `alert` field is not a background notification, it is also required to have (from Apple doc):
> Additionally, the notification’s POST request should contain the apns-push-type header field with a value of background, and the apns-priority field with a value of 5.

There is a way to sent a notification by using firebase without having throttling as it is possible with the Apple REST services?
Note that the above payloads have the field `priority` set to `high`, so they should not be background notifications.

Do you know if there is a way using Firebase to send a notification without the `alert/notification` field (i.e. so that there is no banner displayed by the system) that isn't a background notification?

Thanks again

**Comment by chliangGoogle** [comment]
@aruffolo a notification without the alert field will be considered a background notification by Apple since it's not displayed. Have you tried with "content-available" field in?

**Comment by aruffolo** [comment]
Hi @chliangGoogle 
The "content-available" is in the payload. (it's above in my example payload)

From my reading of Apple doc and my tests I believe that this:
> a notification without the alert field will be considered a background notification by Apple since it's not displayed
It not 100% accurate

I quote from Apple [doc](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app)

> Additionally, the notification’s POST request should contain the apns-push-type header field with a value of background, and the apns-priority field with a value of 5.

So the fact that is not displayed does not mean is a background notification.
I've also tested using this CURL:

`curl -v \
-d '{"Simulator Target Bundle":"com.---.---","aps":{"category":"SECRET","badge":0,"sound":1},"pushCategory":"---","updateStatus":"{\"operationId\":\"ios-opid\",\"status\": 0,\"action\":\"makeCoffee\",\"description\":\"action-ios-des\",\"stock\": {\"remaining\":\"7\",\"threshold\":\"10\",\"depletion\": false}}"}' \
-H "apns-topic: com.-.-" \
-H "apns-priority: 10" \
--http2 \
--cert-type P12 --cert /Users/ruffoloan/Desktop/pushDev.p12 \
https://api.development.push.apple.com/3/device/940CC9FFE0BFCB7297D18CB95E8F38755F730751616E1B6B705B9AA2917674CF`

This notification is not displayed but is also not throttled. I've sent 20 notifications in a row and the payload was always immediately received. With the firebase notification I will be throttled at the fifth notification sent.

There is a way to send the equivalent of the above CURL using Firebase?

**Comment by chliangGoogle** [comment]
@aruffolo did you try overwrite the apns-priority to 10 using our v1 API?

**Comment by chliangGoogle** [comment]
Let me clarify again: In your first payload example you didn't have badge or sound in it, which is a background notification. As @morganchen12 said, apple will throttle your message. And we can't control the throttle rate even though you try with Apple send API and they succeed. That might be just luck.

The second example you gave with badge or sound, which is considered a display notification. The apns priority is required to be 10 which explains why it didn't get throttled.

**Comment by aruffolo** [comment]
@chliangGoogle 
I've added
`    "apns": {
       "headers": {
         "apns-priority": "10"
       }
    },`
but the notifications is still throttled.

This is the full payload:
`{
  "to": "---",
  "content_available": true,
  "data": {
    "pushCategory": "---",
    "updateStatus": {
      "operationId": "ios-opid",
      "status": 0,
      "action": "makeCoffee",
      "description": "action-ios-des",
      "stock": {
        "remaining": "50",
        "threshold": "10"
      }
    },
  },
    "apns": {
       "headers": {
         "apns-priority": "10"
       }
    },
  "priority": "high",
  "time_to_live": 600
}
`

And the CURL

`curl --location --request POST 'https://fcm.googleapis.com/fcm/send' \
--header 'Authorization: key=-------' \
--header 'Content-Type: application/json' \
--data-raw '{
  "to": "---",
  "content_available": true,
  "data": {
    "pushCategory": "---",
    "updateStatus": {
      "operationId": "ios-opid",
      "status": 0,
      "action": "makeCoffee",
      "description": "action-ios-des",
      "stock": {
        "remaining": "50",
        "threshold": "10"
      }
    },
  },
    "apns": {
       "headers": {
         "apns-priority": "10"
       }
    },
  "priority": "high",
  "time_to_live": 600
}
'`

**Comment by chliangGoogle** [comment]
because it is a background notification (your latest payload only contains data no badge or icon), in Apple's documentation, they recommend not send more than 2 or 3 per hour, while you send 20 in a row so even if overwriting the priority will not help as the system identifies this as background notification and throttles when total number becomes excessive. 

https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app
