### ISSUE TITLE
Build error in FirebaseCoreDiagnostics >= 7.2.0

### ISSUE THREAD

**Issue by mikehardy** [firebase/firebase-ios-sdk#7098]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.2
  * Firebase SDK version: 7.1.0, 7.2.0
  * Installation method: CocoaPods
  * Firebase Component: FirebaseCoreDiagnostics dependents (Auth, InAppMessaging, RemoteConfig etc)

#### Steps to reproduce:

I think there may be two issues, related. Both have the same ultimate build error

1) Pod dependency issues: 

 When 7.1.0 was originally released, everything built fine. Now with 7.2.0 out, 7.1.0 no longer builds correctly.

I believe some of the podspecs allow a few of the transitive dependencies to slip the bonds of the requested version (7.1.0) and move to 7.2.0. Specifically, these pods will go to 7.2.0 on a fresh install of 7.1.0 `Firebase/*` pods - here's a snippet from where I was pinning them in my test app Podfile to see what Podfile.lock would look like - each would go to 7.2.0 (or 7.2.0-beta for FirebaseMLCommon) despite a request for the related 7.1.0 Pods (e.g. `'Firebase/InstanceID', $FirebaseSDKVersion` with 7.1.0 would get me `FirebaseInstanceID of 7.2.0. In fact, this seems to happen even if I try 7.0.0 now because it is still semver compatible with 7.2.0 according to the version constraints.

```
  #pod 'FirebaseABTesting', $FirebaseSDKVersion
  #pod 'FirebaseCoreDiagnostics', $FirebaseSDKVersion
  #pod 'FirebaseInstallations', $FirebaseSDKVersion
  #pod 'FirebaseInstanceID', $FirebaseSDKVersion
  #pod 'FirebaseMLCommon', "#{$FirebaseSDKVersion}-beta"
```

2. Build error in FirebaseCoreDiagnostics >= 7.2.0

```

❌  /Users/mike/work/Invertase/react-native-firebase/tests/ios/Pods/FirebaseCoreDiagnostics/Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m:20:9: 'GoogleDataTransport/GDTCORLibrary/Internal/GoogleDataTransportInternal.h' file not found

#import "GoogleDataTransport/GDTCORLibrary/Internal/GoogleDataTransportInternal.h"
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Normally I would trust the internal versioning to be okay, but in this case the rest of the internal 7.2.0 changes are fine except FirebaseCoreDiagnostics. That one has a build error as above. 

When I try to use 7.2.0 completely - which I was testing after fixing a firestore compile issue this morning - it still fails.

I maintain a fully scripted react-native-firebase demonstrator where you can see how we construct a clean project and add our dependencies, then investigate the resulting Podfile - it fails to compile now with 7.x.x

https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

You'll need node + yarn installed to run it, plus a 'GoogleServices-plist.json' and 'google-services.json' to your favorite example project (they're unused unless you run the demo and even then the demo doesn't actually do anything other than prove it builds and runs, if you're curious)

I'm not sure what the root cause of the error is but I reproduce it in FlutterFire (where I'm trying to get firebase-ios-sdk >=7 supported - https://github.com/FirebaseExtended/flutterfire/pull/4249), my work app, and react-native-firebase which I maintain and normally know what I'm doing, except when a hit a build error and feel lost ;-). [Our test app](https://github.com/invertase/react-native-firebase/tree/master/tests) no longer works unless I use 7.1.0 and in our app Podfile pin FirebaseCoreDiagnostics to 7.1.0

Help?

**Comment by mikehardy** [comment]
@paulb777 / @ryanwilson not in the habit of tagging people in lightly but I know you just worked on the release since I collaborated a moment with Paul this morning, and I did as much pre-diagnostics as I could. This blocks use of 7.2.0 for me in react-native-firebase and flutterfire where I would otherwise work to advance your new APIs :-), and the only workaround for 7.x.x at all is to use an unexpected version override of an internal pod. 

Thought you might want to take a look since I think I may be trailblazing on adoption of 7.2.0 here

**Comment by paulb777** [comment]
@mikehardy Appreciate the heads-up. I'll take a look this afternoon.

**Comment by paulb777** [comment]
@mikehardy Would you share the generated `Podfile.lock`

**Comment by mikehardy** [comment]
Sure, to be precise, you would like to see the generated Podfile.lock with 7.1.0 specified (to see the 7.2.0s that slip in?). I'm guessing yes and will start executing that

**Comment by paulb777** [comment]
It should be ok for 7.2.0's to slip in, but yes - I'd like to see the exact problem.

Meanwhile I'm trying to run the script you sent ...

**Comment by mikehardy** [comment]
Here's what my Podfile.lock looks like from that script
[Podfile.lock.txt](https://github.com/firebase/firebase-ios-sdk/files/5639071/Podfile.lock.txt)

**Comment by mikehardy** [comment]
Here is just the diff that shows what happens if I delete Podfile.lock then re-run pod install on my work project. Previous lock was done on Nov 30 according to git history

```

mike@osxvm:~/work/Kullki/ksocialscore/packages/public-app/ios (rebranding *) % git diff --text Podfile.lock
diff --git a/packages/public-app/ios/Podfile.lock b/packages/public-app/ios/Podfile.lock
index 3ed49678..f852db81 100644
--- a/packages/public-app/ios/Podfile.lock
+++ b/packages/public-app/ios/Podfile.lock
@@ -72,7 +72,7 @@ PODS:
   - Firebase/Storage (7.1.0):
     - Firebase/CoreOnly
     - FirebaseStorage (~> 7.1.0)
-  - FirebaseABTesting (7.1.0):
+  - FirebaseABTesting (7.2.0):
     - FirebaseCore (~> 7.0)
   - FirebaseAnalytics (7.1.0):
     - FirebaseCore (~> 7.0)
@@ -92,7 +92,7 @@ PODS:
     - FirebaseCoreDiagnostics (~> 7.0)
     - GoogleUtilities/Environment (~> 7.0)
     - GoogleUtilities/Logger (~> 7.0)
-  - FirebaseCoreDiagnostics (7.1.0):
+  - FirebaseCoreDiagnostics (7.2.0):
     - GoogleDataTransport (~> 8.0)
     - GoogleUtilities/Environment (~> 7.0)
     - GoogleUtilities/Logger (~> 7.0)
@@ -115,12 +115,12 @@ PODS:
     - FirebaseInstallations (~> 7.0)
     - GoogleUtilities/Environment (~> 7.0)
     - nanopb (~> 2.30906.0)
-  - FirebaseInstallations (7.1.0):
+  - FirebaseInstallations (7.2.0):
     - FirebaseCore (~> 7.0)
     - GoogleUtilities/Environment (~> 7.0)
     - GoogleUtilities/UserDefaults (~> 7.0)
     - PromisesObjC (~> 1.2)
   FirebaseMessaging: 076054895c9260f82c7304cc7709dbf19b8f3e4a
   FirebasePerformance: 70f4ea16062512a57a084ed4ae0925b6af1e3884
   FirebaseRemoteConfig: 04cd72851dad51780aa66f05b01a7dd0b85cdbf5
@@ -1033,7 +1033,7 @@ SPEC CHECKSUMS:
   Permission-Notifications: 9c6b5cc4f0e6599e9fc3395b77cebddc48f1be41
   Permission-Reminders: f1bddb60953645830289f9b00977b11e2b62fbf8
   PromisesObjC: 8c196f5a328c2cba3e74624585467a557dcb482f
-  Protobuf: 3dac39b34a08151c6d949560efe3f86134a3f748
+  Protobuf: 0cde852566359049847168e51bd1c690e0f70056
   RCTRequired: 082f10cd3f905d6c124597fd1c14f6f2655ff65e
   RCTTypeSafety: 8c9c544ecbf20337d069e4ae7fd9a377aadf504b
   React: b0a957a2c44da4113b0c4c9853d8387f8e64e615
@@ -1103,6 +1103,6 @@ SPEC CHECKSUMS:
   Yoga: 4bd86afe9883422a7c4028c00e34790f560923d6
   YogaKit: f782866e155069a2cca2517aafea43200b01fd5a
 
-PODFILE CHECKSUM: ffd6025b0e9ba8737c000fe5f64e9c74f6a3bd6d
+PODFILE CHECKSUM: e41d004836e9ad82c59ae8de2005a602b0650621
 
 COCOAPODS: 1.10.0
```

**Comment by paulb777** [comment]
I'm still trying to get your repro set up. Nothing should have changed in the those versions that changed from 7.1 to 7.2. It might be interesting to compare the two Pods directories. 

The missing file should be at `Pods/FirebaseCoreDiagnostics/GoogleDataTransport/GDTCORLibrary/Internal/GoogleDataTransportInternal.h` in both versions.

**Comment by paulb777** [comment]
After installing some stuff, the script runs for awhile and fails with:
```
+ cp -r ../rnfbdemo.xcodeproj ios/
cp: ../rnfbdemo.xcodeproj: No such file or directory
```

A Podfile.lock is generated but doesn't include any Firebase pods.

**Comment by mikehardy** [comment]
Indeed, the header file appears to exist, it's confounding. I saw some PRs and all sorts of noise about moving GoogleDataTransport headers internal and stuff, but that seems like a red herring. I believe it was prior to this problem and the header ref is already internal.

...that error is odd, I mostly run the script on macOS or Linux and I'd assume your macOS since it's a firebase-ios-sdk issue ;-). I just spun up a new Big Sur VM last night so this was all clean runs for me this morning from a fresh checkout of `git@github.com:mikehardy/rnfbdemo.git` - I'm normally in the business of clean repro so I thought a fully scripted one would be perfect.

You can also try cloning react-native-firebase and following the instructions for it https://github.com/invertase/react-native-firebase/blob/master/tests/README.md

for the purposes of demonstration it should just be, from root level there, post checkout:
```
yarn
yarn tests:ios:pod:install
yarn tests:ios:build
```

**Comment by wilhuff** [comment]
There's a related question here about how our podspecs express our dependencies though, e.g. https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseABTesting.podspec#L43. Why would we want to allow a 7.2.0 FirebaseABTesting to be used with a 7.0.0 FirebaseCore? This isn't a configuration we ever test so we can't verify this configuration would actually work.

In prior major versions, we only allowed patch-level floating, which seems more defensible/sustainable. We explicitly don't allow changes to interfaces in patches which makes it far more likely these will be compatible.

This also means that when customers request 7.1.0 of something they'll never accidentally get 7.2.0 of a dependent pod. Assuming this issue has to do with version mixing, tighter bounds on dependency floating would have prevented this issue in the first place.

**Comment by paulb777** [comment]
It's not clear this issue is related, but the loose versioning allowing minor version floating is how Firebase has always released in CocoaPods and we decided not to change in 7.0.0 to minimize the disruption and it can be changed at any minor revision. I'm open to revisiting since it's a testing hole, albeit not a new one.

**Comment by mikehardy** [comment]
@wilhuff that is the core of issue 1, unfortunately you have what I think is a guess embedded which is that it is version mixing, when I go pure 7.2.0 (which I was attempting to fuzz-bust today) I get issue 2 which is the compile error

**Comment by paulb777** [comment]
Running the repro script in the repo itself made a difference and I now have simulators kicked off and a build proceeding.

**Comment by paulb777** [comment]
FirebaseCoreDiagnostics.m successfully compiles for me and the script later fails 

```
The following build commands failed:
	CopyPlistFile /Users/paulbeusterien/Library/Developer/Xcode/DerivedData/rnfbdemo-btvwotfutmhelrbrcbfpdiyujams/Build/Products/Debug-iphonesimulator/rnfbdemo.app/GoogleService-Info.plist /Users/paulbeusterien/bugs/7098/rnfbdemo/rnfbdemo/ios/rnfbdemo/GoogleService-Info.plist
(1 failure)
```

I'll try moving the plist down a directory level but it looks like I'm not reproducing what you're seeing.  What Xcode version are you using?

**Comment by paulb777** [comment]
@ mikehardy Would you zip up the Xcode workspace that fails to build and send?

**Comment by mikehardy** [comment]
the plist should be in the root of the rnfbdemo clone, and the make-demo.sh script will copy it into the expected place. Funny, I've always done the equivalent of `cd <into clone directory root> && ./make-demo.sh` so perhaps I have some `$CWD` assumption buried in there. I'll shave that yak later.

Definitely looks like we've varied on reproduction. I'll pick up a different macOS machine and try as clean as I can from there in parallel with attempting to zip Xcode workspace and send. Pre-emptive apology if this is a wild goose chase - 3 repos failing the same I was sure I was on to something and still think I am.

**Comment by mikehardy** [comment]
Oh, and

```
mike@osxvm:~ % xcodebuild -version
Xcode 12.2
Build version 12B45b
```

**Comment by mikehardy** [comment]
I have it zipped and uploaded but on a separate machine I may not be able to reproduce either so holding off on sharing the link while I dig more locally.

On my secondary machine (slower, but macOS on an old MBP) it works fine.
The source of the problem that had me file the issue is my main machine which is much faster but where most of my work is VM based and this is on a fresh VM. I haven't had problems in the past but now there is a difference between the machines. It's either that there is a new problem that only shows up from pristine conditions or something else.

I'm going to push it through Github Actions infrastructure to see if there's a reproduction in a neutral space.

**Comment by mikehardy** [comment]
How frustrating, @paulb777 I think I owe you your beverage of choice. There is perhaps the lower-priority issue of allowing minors to come in transitively as discussed above but that's nothing compared to a build error and right now we've got you, Github Actions, and one machine next to me building, and only one machine not building. Which means this is likely a personal problem on the one machine not building and I need to handle that myself. Apologies for any time spent, but I guess (hunting for a silver lining...) you have a react-native-firebase clean build script to throw at people if that's ever a thing you need.

I'll re-open if it turns out to be something concrete I can point out but with 3 to 1 odds against I'll bet that won't happen

**Comment by paulb777** [comment]
@mikehardy Don't worry about it! We appreciate the many contributions you've made to the Firebase eco-system, especially the [high-quality participation in this repo](https://github.com/firebase/firebase-ios-sdk/issues?q=involves%3Amikehardy+).

I'm curious to know what you find. Please let us know. :)

**Comment by mikehardy** [comment]
Found it. Corrupt local cocoapods cache. 

Caught me out despite [some history with pod local state learnt while helping others fix build errors](https://github.com/pmadruga/react-native-clean-project/pulls?q=+is%3Apr+author%3Amikehardy)

Never seen this cache go corrupt before.

So frustrating! 

I was aware of `~/.cocoapods` but not of `~/Library/Caches/CocoaPods` - found it referenced here https://guides.cocoapods.org/using/troubleshooting and investigated

```
mike@osxvm:~/work/Invertase/rnfbdemo/rnfbdemo/ios (master) % find ~/Library/Caches/CocoaPods/Pods/|grep FirebaseCoreDiagnostics
/Users/mike/Library/Caches/CocoaPods/Pods//Specs/Release/FirebaseCoreDiagnostics
/Users/mike/Library/Caches/CocoaPods/Pods//Specs/Release/FirebaseCoreDiagnostics/7.1.podspec.json
/Users/mike/Library/Caches/CocoaPods/Pods//Specs/Release/FirebaseCoreDiagnostics/7.2.podspec.json
/Users/mike/Library/Caches/CocoaPods/Pods//Specs/External/FirebaseCoreDiagnostics
/Users/mike/Library/Caches/CocoaPods/Pods//Specs/External/FirebaseCoreDiagnostics/bf497d1f52025bbd84aebbbf16eac062-bbf30.podspec.json
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.2.0-2d508
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.2.0-2d508/Interop
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.2.0-2d508/Interop/CoreDiagnostics
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.2.0-2d508/Interop/CoreDiagnostics/Public
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.2.0-2d508/Interop/CoreDiagnostics/Public/FIRCoreDiagnosticsData.h
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.2.0-2d508/Interop/CoreDiagnostics/Public/FIRCoreDiagnosticsInterop.h
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.2.0-2d508/README.md
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.2.0-2d508/Firebase
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.2.0-2d508/Firebase/CoreDiagnostics
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.2.0-2d508/Firebase/CoreDiagnostics/FIRCDLibrary
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.2.0-2d508/Firebase/CoreDiagnostics/FIRCDLibrary/Public
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.2.0-2d508/Firebase/CoreDiagnostics/FIRCDLibrary/Public/FIRCoreDiagnostics.h
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.2.0-2d508/Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.2.0-2d508/Firebase/CoreDiagnostics/FIRCDLibrary/Protogen
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.2.0-2d508/Firebase/CoreDiagnostics/FIRCDLibrary/Protogen/nanopb
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.2.0-2d508/Firebase/CoreDiagnostics/FIRCDLibrary/Protogen/nanopb/firebasecore.nanopb.c
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.2.0-2d508/Firebase/CoreDiagnostics/FIRCDLibrary/Protogen/nanopb/firebasecore.nanopb.h
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/LICENSE
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/GoogleDataTransport
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/GoogleDataTransport/GDTCORLibrary
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/GoogleDataTransport/GDTCORLibrary/Internal
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/GoogleDataTransport/GDTCORLibrary/Internal/GDTCORRegistrar.h
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/GoogleDataTransport/GDTCORLibrary/Internal/GDTCORStorageEventSelector.h
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/GoogleDataTransport/GDTCORLibrary/Internal/GoogleDataTransportInternal.h
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/GoogleDataTransport/GDTCORLibrary/Internal/GDTCORDirectorySizeTracker.h
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/GoogleDataTransport/GDTCORLibrary/Internal/GDTCORPlatform.h
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/GoogleDataTransport/GDTCORLibrary/Internal/GDTCORStorageProtocol.h
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/GoogleDataTransport/GDTCORLibrary/Internal/GDTCORUploader.h
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/GoogleDataTransport/GDTCORLibrary/Internal/GDTCORAssert.h
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/GoogleDataTransport/GDTCORLibrary/Internal/GDTCORLifecycle.h
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/GoogleDataTransport/GDTCORLibrary/Internal/GDTCORReachability.h
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/Example
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/Example/CoreDiagnostics
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/Example/CoreDiagnostics/Tests
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/Example/CoreDiagnostics/Tests/FIRCoreDiagnosticsTest.m
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/Interop
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/Interop/CoreDiagnostics
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/Interop/CoreDiagnostics/Public
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/Interop/CoreDiagnostics/Public/FIRCoreDiagnosticsData.h
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/Interop/CoreDiagnostics/Public/FIRCoreDiagnosticsInterop.h
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/README.md
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/Firebase
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/Firebase/CoreDiagnostics
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/Firebase/CoreDiagnostics/FIRCDLibrary
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/Firebase/CoreDiagnostics/FIRCDLibrary/Public
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/Firebase/CoreDiagnostics/FIRCDLibrary/Public/FIRCoreDiagnostics.h
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/Firebase/CoreDiagnostics/FIRCDLibrary/Protogen
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/Firebase/CoreDiagnostics/FIRCDLibrary/Protogen/nanopb
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/Firebase/CoreDiagnostics/FIRCDLibrary/Protogen/nanopb/firebasecore.nanopb.c
/Users/mike/Library/Caches/CocoaPods/Pods//Release/FirebaseCoreDiagnostics/7.1.0-872cd/Firebase/CoreDiagnostics/FIRCDLibrary/Protogen/nanopb/firebasecore.nanopb.h
```

7.1.0 is correct, 7.2.0 on this machine is for some reason incomplete, and looking in the Library cache is where it is visible.

`cd ios && pod cache clean --all && rm -fr Pods` purges everything from cache and my project install, `pod install` results in sanity 

(I suppose you could snipe it with `pod cache clean FirebaseCoreDiagnostics --all` to get just that pod but all versions but I didn't trust it)

Quite a time-costly piece of wisdom re: pods picked up right there.

**Comment by ryanwilson** [comment]
Happy you found it, and TIL about that cache too! Thanks for the detailed write-ups, glad things are back in a good state :)
