### ISSUE TITLE
Repository license

### ISSUE THREAD

**Issue by hithomasmorelli** [firebase/firebase-ios-sdk#7105]
I'm working on an acknowledgements file for an app I'm developing. I noticed that the [license file](https://github.com/firebase/firebase-ios-sdk/blob/2354cce7dd9325cf059f7ca29f0188e994374f3b/LICENSE) referred to "Firebase, Inc." in the license appendix. Looking at the commit history shows that this was introduced in #6044.

I've got pretty much no idea how the Apache 2.0 license should be applied to an open source repository - i.e. whether or not the appendix at the end should be filled with the name of the copyright holder of the repository. Going off a quick search, the Google [open source docs](https://opensource.google/docs/releasing/preparing/#license-file) suggest that the appendix *shouldn't* be filled:

> There must also be a file named LICENSE in the top-level directory that contains a copy of the license. For the Apache License, simply copy the official 2.0 license into your LICENSE file verbatim (do not edit the Copyright section in the template, only when you use that template in the header of your source code files.)
> 
> Why shouldn't I edit the template in the Apache License? The "LICENSE" file is supposed to be our inclusion of an exact copy of https://www.apache.org/licenses/LICENSE-2.0.txt as required by section 4(a) of the Apache 2 license, so we shouldn't modify it in any way, such as by adding our copyright notice. Also, the Appendix (lines 179-202) represents a notice to third-parties informing them of how *they* should apply the Apache 2 license to their own works, so inserting our copyright notice in place of the template text renders those instructions incorrect. Many projects insert copyright notices into their LICENSE file at line 190 because this is a common and understandable misinterpretation of the license's instructions. We should attempt to fix this wherever we find it, particularly for first-party projects.

I will happily admit that I don't know much about how to apply the Apache 2.0 license to a piece of work. However, I thought that it was probably something that I should bring to your attention.

**Comment by paulb777** [comment]
@hithomasmorelli Thanks for the issue. Your analysis looks right to me that we shouldn't have merged #6044. I'll send a PR to fix.
