### ISSUE TITLE
FR: RTDB Query get 

### ISSUE THREAD

**Issue by jmwski** [firebase/firebase-ios-sdk#7109]
### Feature proposal

* Firebase Component: Database

[go/rtdb-get](https://docs.google.com/document/d/1T6GSAkLU4y45lxm_8qJMAoc00b5m8bX7y_II4aA7xoM/edit?usp=sharing)

**Comment by paulb777** [comment]
Thanks! Is it possible to make the document link publicly visible - or at least visible internally at Google?

**Comment by IanWyszynski** [comment]
> Thanks! Is it possible to make the document link publicly visible - or at least visible internally at Google?

I've made the link publicly visible within alphabet.
