### ISSUE TITLE
FBLPromises.framework missing "ld: file not found: FBLPromises for architecture arm64" 

### ISSUE THREAD

**Issue by pieomy** [firebase/firebase-ios-sdk#7112]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.7
  * Firebase SDK version: 7.2.0
  * Installation method:  Zip file
  * Firebase Component: FirebaseCrashlytics.framework

### [REQUIRED] Step 2: Describe the problem
I am use Delphi IDE and trying to add FirebaseCrashlytics.framework to my app, "FirebaseCore.framework" pushing this error 
"ld: file not found: FBLPromises for architecture arm64"
(this error is common and will be gone when I add FBLPromises.framework to my framework search path but I can not find FBLPromises.framework in Firebase.zip )

**Comment by ryanwilson** [comment]
Hi @pieomy - sorry for the issue you're seeing. Can you please try adding `PromisesObjC.xcframework` to your project and see if that resolves the issue?

Also please note, in 7.2.0 we had to change the minimum supported Xcode version to 12.0. You may see issues during archive/submission to the App Store since Xcode doesn't have backwards compatibility for bitcode.

**Comment by pieomy** [comment]
Hi, thanks for answer but did not work. 
I added PromisesObjC framework but still requesting FBLPromises as file, I tried simple hack changed all PromisesObjC file name to FBLPromises but did not work :)

also thanks for tip, I won't be publish on store my app yet

**Comment by paulb777** [comment]
Nothing about the name should need to be changed. It should be just a matter of linking `PromisesObjC.xcframework` included in the distribution.

Something about the build settings might be causing an issue. You could try searching for references to `Promises`.

We might not be able to help additionally without a reproducible example.

**Comment by pieomy** [comment]
I already add "PromisesObjC.framework" but still I have same error
"ld: file not found: FBLPromises for architecture arm64"

if sdk is requesting "FBLPromises" why this sdk dosen't inside .zip file? I don't understand this.

**Comment by paulb777** [comment]
Where is the reference to FBLPromises coming from?

**Comment by pieomy** [comment]
I think "FirebaseCore"


-I created new empty project
-added my linker to: "-ObjC -framework FirebaseCrashlytics"
-set up my framework search path and added only "FirebaseCrashlytics.framework"
-after compile I got this error "ld: file not found: FirebaseCore for architecture arm64"
-added "FirebaseCore.framework" to my framework folder and this error fixed.
-after 2. compile I got this error "ld: file not found: FBLPromises for architecture arm64"
(after this error, added PromisesObjC.framework but dosen't work)

and now I stuck here.

Video:
https://drive.google.com/file/d/19HqaleJEY64DUernHMhcpLLsxsUcOdn0/view?usp=sharing

My IDE (Delphi) is use this tool for link iOS-64bit;
Apple's ld64.exe (ld.exe)
http://docwiki.embarcadero.com/RADStudio/Sydney/en/External_Linkers_used_by_Delphi_(and_C%2B%2B)
https://opensource.apple.com/source/ld64/ld64-274.2/doc/design/linker.html

and linker command list here, maybe should I add some extra commands like "-ObjC" ? (but I don't have any idea about that)
https://www.manpagez.com/man/1/ld64/

**Comment by paulb777** [comment]
Our zip instructions are in the README in the zip you downloaded and [here](https://github.com/firebase/firebase-ios-sdk/blob/master/ReleaseTooling/Template/README.md).

We might not be able to help with Delphi and you might want to reach out to the Delphi for help in adapting our Xcode-based instructions.

**Comment by paulb777** [comment]
I'm going to close since this seems to be a Delphi integration issue and not a Firebase issue.  We can continue the discussion and/or reopen with more information.

**Comment by pieomy** [comment]
This is simple issue, FirebaseCore.framework (or any other dependency) requesting FBLPromises and this file is missing. (or changed name PromisesObjC but still FirebaseCore codes have FBLPromises ) 
Delphi reading this information from FirebaseCore.framework how can be delphi integration issue? +30 SDKs working on Delphi without any problem.

if firebase don't use FBLPromises anymore then they should be remove all dependency or if they sill need this dependency they should deploy this file inside zip, I think this is simple.

**Comment by paulb777** [comment]
`FBLPromises` is the module name associated with the PromisesObjC.framework. See [here](https://github.com/google/promises/blob/master/PromisesObjC.podspec#L20).

Firebase uses the FBLPromises headers provided by the PromisesObjC framework.

**Comment by pieomy** [comment]
thanks but I need FBLPromises as a file. 
anyway I think we can not fix this
thanks for everything, I have to find another tool

**Comment by paulb777** [comment]
Here's where they are in the zip distribution:

```
$ ls Firebase/FirebaseAnalytics/PromisesObjC.xcframework/ios-arm64_armv7/PromisesObjC.framework/Headers/
FBLPromise+All.h	FBLPromise+Async.h	FBLPromise+Delay.h	FBLPromise+Recover.h	FBLPromise+Testing.h	FBLPromise+Validate.h	FBLPromiseError.h
FBLPromise+Always.h	FBLPromise+Await.h	FBLPromise+Do.h		FBLPromise+Reduce.h	FBLPromise+Then.h	FBLPromise+Wrap.h	FBLPromises.h
FBLPromise+Any.h	FBLPromise+Catch.h	FBLPromise+Race.h	FBLPromise+Retry.h	FBLPromise+Timeout.h	FBLPromise.h		PromisesObjC-umbrella.h
```

**Comment by pieomy** [comment]
we don't use .h files, only adding 1 file to project (for each framework) and this file is for example: FirebaseCore, we don't use Headers and Modules folders (I don't know why but we added all sdks like this way and never see alternative way) 

probably your header files working good with xcode. I think delphi searching FBLPromises but file name is PromisesObjC and does not recognize this. I think we can not fix this because this headers&sdk working on your side without any problem and there is no way to find my problem source.

thank you for your interest and effort, and sorry for wasted time. we can close this issue
