### ISSUE TITLE
Realm realm::_impl::ExternalCommitHelper::listen() + 160

### ISSUE THREAD

**Issue by s4worldus** [firebase/firebase-ios-sdk#7115]
### [REQUIRED] Step 1: Describe your environment
Realm framework version: 'RealmSwift', '3.20.0'
  * Xcode version: Xcode 11.7
  * Firebase SDK version: 7.1.0
  * Installation method: `CocoaPods`
  * Firebase Component: Core, Performance, RemoteConfig, Analytics, Crashlytics, etc

#### Steps to reproduce:

Can't reproduce, crash happen and logs on production crashlytics
It's really weird that I didn't upgrade realm recently, only firebase crashlytics so far
[](url)
Realm notification listener
```
0  libsystem_kernel.dylib         0x19e5068d0 kevent + 8
1  Realm                          0x107945084 realm::_impl::ExternalCommitHelper::listen() + 160
2  Realm                          0x107945b58 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >(void*) + 52
3  libsystem_pthread.dylib        0x19e423914 _pthread_start + 168
4  libsystem_pthread.dylib        0x19e42b9d4 thread_start + 8

com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x19e4e2784 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x19e4e1ba8 mach_msg + 76
2  CoreFoundation                 0x19e698538 __CFRunLoopServiceMachPort + 152
3  CoreFoundation                 0x19e693364 __CFRunLoopRun + 1140
4  CoreFoundation                 0x19e692bc8 CFRunLoopRunSpecific + 480
5  Foundation                     0x19e9e9598 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 232
6  Foundation                     0x19e9e9470 -[NSRunLoop(NSRunLoop) runUntilDate:] + 92
7  UIKitCore                      0x1a28ebb74 -[UIEventFetcher threadMain] + 156
8  Foundation                     0x19eb22e38 __NSThread__start__ + 852
9  libsystem_pthread.dylib        0x19e423914 _pthread_start + 168
10 libsystem_pthread.dylib        0x19e42b9d4 thread_start + 8

com.google.firebase.crashlytics.MachExceptionServer
0  FirebaseCrashlytics            0x10630b96c FIRCLSProcessRecordAllThreads + 180
1  FirebaseCrashlytics            0x10630bd50 FIRCLSProcessRecordAllThreads + 1176
2  FirebaseCrashlytics            0x106302274 FIRCLSHandler + 48
3  FirebaseCrashlytics            0x106304cc4 FIRCLSMachExceptionServer + 1156
4  libsystem_pthread.dylib        0x19e423914 _pthread_start + 168
5  libsystem_pthread.dylib        0x19e42b9d4 thread_start + 8

com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x19e4e2784 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x19e4e1ba8 mach_msg + 76
2  CoreFoundation                 0x19e698538 __CFRunLoopServiceMachPort + 152
3  CoreFoundation                 0x19e693364 __CFRunLoopRun + 1140
4  CoreFoundation                 0x19e692bc8 CFRunLoopRunSpecific + 480
5  CFNetwork                      0x1a1996ebc (Missing)
6  Foundation                     0x19eb22e38 __NSThread__start__ + 852
7  libsystem_pthread.dylib        0x19e423914 _pthread_start + 168
8  libsystem_pthread.dylib        0x19e42b9d4 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x19e5059a8 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x19e425764 _pthread_wqthread + 352
2  libsystem_pthread.dylib        0x19e42b9c8 start_wqthread + 8
```
[AVAudioSession Notify Thread.txt](https://github.com/firebase/firebase-ios-sdk/files/5657231/AVAudioSession.Notify.Thread.txt)
[Realm notification listener.txt](https://github.com/firebase/firebase-ios-sdk/files/5657232/Realm.notification.listener.txt)

**Comment by morganchen12** [comment]
@s4worldus there's no exception in this stack trace and also no indication that Firebase is causing the crash. Can you try to isolate a crash repro and share it with us?

**Comment by maksymmalyhin** [comment]
@s4worldus From the first glance I cannot see any connection between the crash and recent Firebase changes, so I would recommend to file an issue for Real to investigate as well.

Could you also provide a couple additional details that may give some ideas:
1. Does the crash happed on specific iOS versions or devices? 
2. Is the exception available at the crash report? 
3. Could you share the stack traces for other threads?

**Comment by s4worldus** [comment]
hi @maksymmalyhin, @morganchen12, 

I didn't get any exception from crash report, Could you please check the whole stack trace as follows:

https://github.com/firebase/firebase-ios-sdk/files/5657231/AVAudioSession.Notify.Thread.txt
https://github.com/firebase/firebase-ios-sdk/files/5657232/Realm.notification.listener.txt

Thanks a lot for your supporting

**Comment by paulb777** [comment]
It's not clear there's anything about Firebase in those traces. Without more info or a repro, we're not likely to be able to help.
