### ISSUE TITLE
GenericRunLoopThread::Entry(void*)

### ISSUE THREAD

**Issue by s4worldus** [firebase/firebase-ios-sdk#7116]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.7
  * Firebase SDK version: 7.1.0
  * Installation method: `CocoaPods
  * Firebase Component: Core, Performance, RemoteConfig, Analytics, Crashlytics, etc

#### Steps to reproduce:

Can't reproduce, it happens on Firebase Crashlytics production only after migrating Crashlytics from the Fabric 

Stack trace:
AVAudioSession Notify Thread
0  libsystem_kernel.dylib         0x1ace60dd0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1ace60184 mach_msg + 76
2  CoreFoundation                 0x180c9ecf8 __CFRunLoopServiceMachPort + 380
3  CoreFoundation                 0x180c98ea8 __CFRunLoopRun + 1216
4  CoreFoundation                 0x180c984bc CFRunLoopRunSpecific + 600
5  AudioSession                   0x1885482ac GenericRunLoopThread::Entry(void*) + 164
6  AudioSession                   0x18854a390 CAPThread::Entry(CAPThread*) + 92
7  libsystem_pthread.dylib        0x1c8c11ca8 _pthread_start + 320
8  libsystem_pthread.dylib        0x1c8c1a788 thread_start + 8

com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x1ace60dd0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1ace60184 mach_msg + 76
2  CoreFoundation                 0x180c9ecf8 __CFRunLoopServiceMachPort + 380
3  CoreFoundation                 0x180c98ea8 __CFRunLoopRun + 1216
4  CoreFoundation                 0x180c984bc CFRunLoopRunSpecific + 600
5  Foundation                     0x181f19e30 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 232
6  Foundation                     0x181f19d08 -[NSRunLoop(NSRunLoop) runUntilDate:] + 92
7  UIKitCore                      0x1836f5a4c -[UIEventFetcher threadMain] + 516
8  Foundation                     0x1820840f0 __NSThread__start__ + 864
9  libsystem_pthread.dylib        0x1c8c11ca8 _pthread_start + 320
10 libsystem_pthread.dylib        0x1c8c1a788 thread_start + 8

com.google.firebase.crashlytics.MachExceptionServer
0  FirebaseCrashlytics            0x1044f396c FIRCLSProcessRecordAllThreads + 180
1  FirebaseCrashlytics            0x1044f3d50 FIRCLSProcessRecordAllThreads + 1176
2  FirebaseCrashlytics            0x1044ea274 FIRCLSHandler + 48
3  FirebaseCrashlytics            0x1044eccc4 FIRCLSMachExceptionServer + 1156
4  libsystem_pthread.dylib        0x1c8c11ca8 _pthread_start + 320
5  libsystem_pthread.dylib        0x1c8c1a788 thread_start + 8

com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x1ace60dd0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1ace60184 mach_msg + 76
2  CoreFoundation                 0x180c9ecf8 __CFRunLoopServiceMachPort + 380
3  CoreFoundation                 0x180c98ea8 __CFRunLoopRun + 1216
4  CoreFoundation                 0x180c984bc CFRunLoopRunSpecific + 600
5  CFNetwork                      0x181554050 _CFURLStorageSessionCopyCache + 63240
6  Foundation                     0x1820840f0 __NSThread__start__ + 864
7  libsystem_pthread.dylib        0x1c8c11ca8 _pthread_start + 320
8  libsystem_pthread.dylib        0x1c8c1a788 thread_start + 8

Realm notification listener
0  libsystem_kernel.dylib         0x1ace864e4 kevent + 8
1  Realm                          0x105b2d084 realm::_impl::ExternalCommitHelper::listen() + 160
2  Realm                          0x105b2db58 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >(void*) + 52
3  libsystem_pthread.dylib        0x1c8c11ca8 _pthread_start + 320
4  libsystem_pthread.dylib        0x1c8c1a788 thread_start + 8

JavaScriptCore bmalloc scavenger
0  libsystem_kernel.dylib         0x1ace8475c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x1c8c15550 _pthread_cond_wait + 1192
2  libc++.1.dylib                 0x194eaec8c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  JavaScriptCore                 0x18ad780f8 void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&) + 108
4  JavaScriptCore                 0x18ad7c698 bmalloc::Scavenger::threadRunLoop() + 196
5  JavaScriptCore                 0x18ad7c2d4 bmalloc::Scavenger::Scavenger(std::__1::scoped_lock<bmalloc::Mutex> const&) + 14
6  JavaScriptCore                 0x18ad7d798 std::__1::__thread_specific_ptr<std::__1::__thread_struct>::set_pointer(std::__1::__thread_struct*) + 46
7  libsystem_pthread.dylib        0x1c8c11ca8 _pthread_start + 320
8  libsystem_pthread.dylib        0x1c8c1a788 thread_start + 8

WebThread
0  libsystem_kernel.dylib         0x1ace60dd0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1ace60184 mach_msg + 76
2  CoreFoundation                 0x180c9ecf8 __CFRunLoopServiceMachPort + 380
3  CoreFoundation                 0x180c98ea8 __CFRunLoopRun + 1216
4  CoreFoundation                 0x180c984bc CFRunLoopRunSpecific + 600
5  WebCore                        0x18e06b8a0 RunWebThread(void*) + 656
6  libsystem_pthread.dylib        0x1c8c11ca8 _pthread_start + 320
7  libsystem_pthread.dylib        0x1c8c1a788 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x1ace855bc __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1c8c13954 _pthread_wqthread + 352
2  libsystem_pthread.dylib        0x1c8c1a77c start_wqthread + 8

Thread
0  libsystem_pthread.dylib        0x1c8c1a774 start_wqthread + 6

Thread
0  libsystem_kernel.dylib         0x1ace855bc __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1c8c13954 _pthread_wqthread + 352
2  libsystem_pthread.dylib        0x1c8c1a77c start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1ace855bc __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1c8c13954 _pthread_wqthread + 352
2  libsystem_pthread.dylib        0x1c8c1a77c start_wqthread + 8

Thread
0  libsystem_pthread.dylib        0x1c8c1a774 start_wqthread + 6

Thread
0  libsystem_kernel.dylib         0x1ace855bc __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1c8c13954 _pthread_wqthread + 352
2  libsystem_pthread.dylib        0x1c8c1a77c start_wqthread + 8

Thread
0  libsystem_pthread.dylib        0x1c8c1a774 start_wqthread + 6

Thread
0  libsystem_pthread.dylib        0x1c8c1a774 start_wqthread + 6

Thread
0  libsystem_kernel.dylib         0x1ace855bc __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1c8c13954 _pthread_wqthread + 352
2  libsystem_pthread.dylib        0x1c8c1a77c start_wqthread + 8

Thread
0  libsystem_pthread.dylib        0x1c8c1a774 start_wqthread + 6

does anyone experience same problem and advice, please?

**Comment by paulb777** [comment]
Same comments as in #7115 apply here.
