### ISSUE TITLE
FirebaseAnalytics cannot be added via SwiftPM, FIRAnalytics+Consent.h is missing from FirebaseAnalytics.h

### ISSUE THREAD

**Issue by MapaX** [firebase/firebase-ios-sdk#7117]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.2
  * Firebase SDK version: 7.2.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: FirebaseAnalytics

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

I tried to integrate Firebase analytics to our project via SwiftPM. I cannot get this to compile correctly without modifying FirebaseAnalytics.h 
I need to add the #import FIRAnalytics+Consent.h to "Headers/FirebaseAnalytics.h" file and it starts working.
Here is the compile error:

```
<module-includes>:1:1: error: umbrella header for module 'FirebaseAnalytics' does not include header 'FIRAnalytics+Consent.h'
#import "Headers/FirebaseAnalytics.h"
^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Firebase.h"
        ^
/Library/Developer/Xcode/DerivedData/NB-cuvmemeqtkotjpaqssemwrepumry/SourcePackages/checkouts/firebase-ios-sdk/CoreOnly/Sources/Firebase.h:22:13: error: could not build module 'FirebaseAnalytics'
    #import <FirebaseAnalytics/FirebaseAnalytics.h>
            ^
/Src/Analytics/Firebase/ErrorAnalytics.swift:10:8: error: could not build Objective-C module 'Firebase'
import Firebase
```

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by MapaX** [comment]
Seems that I am not only one who noticed this. This is now duplicate to https://github.com/firebase/firebase-ios-sdk/issues/7114

**Comment by ryanwilson** [comment]
Thanks for the report and workaround! Since the other issue was filed earlier, I'll close this one as a duplicate and we'll update everything there (#7114).
