### ISSUE TITLE
Language in license(s) seemingly contains unintended text?

### ISSUE THREAD

**Issue by PoseidonTechnologies** [firebase/firebase-ios-sdk#7121]
### [REQUIRED] Step 1: Describe your environment

  Answers to questions omitted, does not pertain to technical issue.

### [REQUIRED] Step 2: Describe the problem

I'm using a dependency that scrapes the licenses of the dependencies that are used within my project. During this process I noticed the following text in the license of this SDK (and at other places in the repo): 

> Comment from <a href="http://iphonedevwiki.net/index.php/Crack_prevention">iPhone Dev Wiki
Crack Prevention</a>:
App Store binaries are signed by both their developer and Apple. This encrypts the binary so
that decryption keys are needed in order to make the binary readable. When iOS executes the
binary, the decryption keys are used to decrypt the binary into a readable state where it is
then loaded into memory and executed. iOS can tell the encryption status of a binary via the
cryptid structure member of LC_ENCRYPTION_INFO MachO load command. If cryptid is a non-zero
value then the binary is encrypted.
>
> 'Cracking' works by letting the kernel decrypt the binary then siphoning the decrypted data into
a new binary file, resigning, and repackaging. This will only work on jailbroken devices as
codesignature validation has been removed. Resigning takes place because while the codesignature
doesn't have to be valid thanks to the jailbreak, it does have to be in place unless you have
AppSync or similar to disable codesignature checks.
>
> More information at <a href="http://landonf.org/2009/02/index.html">Landon Fuller's blog</a>

This text shows up in the main license [here](https://github.com/firebase/firebase-ios-sdk/blob/master/GoogleUtilities/LICENSE), the license [here](https://github.com/firebase/firebase-ios-sdk/blob/master/GoogleUtilities/Environment/third_party/LICENSE) and as a comment in the code [here](https://github.com/firebase/firebase-ios-sdk/blob/master/GoogleUtilities/Environment/third_party/GULAppEnvironmentUtil.m). Text might also be present elsewhere, but I didn't bother to check. 

The text itself is inoffensive and obviously has no bearing on the functioning of the SDK, I just thought it was a bit odd so I figured I should bring it to the attention of someone to make sure that this is intended.

**Comment by paulb777** [comment]
@PoseidonTechnologies Thanks for checking. This is intended. Full context in https://github.com/firebase/firebase-ios-sdk/blob/master/GoogleUtilities/Environment/third_party/GULAppEnvironmentUtil.m
