### ISSUE TITLE
Firestore 7.2 fails to build on Apple M1

### ISSUE THREAD

**Issue by akopanev** [firebase/firebase-ios-sdk#7125]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: `12.2 (12B45b)`
  * Firebase SDK version: `7.2.0`
  * Installation method: `CocoaPods`
  * Firebase Component: `Firestore`
  * Laptop Chip: `Apple M1`

Podfile
```# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# Uncomment this line if you're using Swift
#use_frameworks!

def core
  pod 'Bolts', '1.9.0'
end

$firebase_version = '7.2-M1'
def firebase_sdk
  pod 'Firebase/Core', $firebase_version

  pod 'Firebase/Analytics', $firebase_version
  pod 'Firebase/Crashlytics', $firebase_version
  pod 'Firebase/Performance', $firebase_version
  pod 'Firebase/Auth', $firebase_version
  pod 'Firebase/DynamicLinks', $firebase_version

  pod 'Firebase/Messaging', $firebase_version
  pod 'Firebase/RemoteConfig', $firebase_version
  pod 'Firebase/Storage', $firebase_version
  pod 'Firebase/Functions', $firebase_version

  pod 'Firebase/Firestore', $firebase_version
end

target 'Project' do
  core
  firebase_sdk
end
```

### [REQUIRED] Step 2: Describe the problem

Firestore build fails.

#### Steps to reproduce:

Build fails with an error:
```
/Pods/gRPC-Core/src/core/ext/filters/client_channel/xds/xds_api.cc:37:10: fatal error: 'envoy/api/v2/cds.upb.h' file not found
```

Part of that header:
```
#include "src/core/lib/iomgr/error.h"
#include "src/core/lib/iomgr/sockaddr_utils.h"

#include "envoy/api/v2/cds.upb.h"
#include "envoy/api/v2/core/address.upb.h"
```

I noticed that missed files actually located at `$(GRPC_SRC_ROOT)/src/core/ext/upb-generated` path, added the path to the User Header Paths for gRPC-Core target.

After that Pods were completed successfully, but another errors appear during project compilation:
```
Showing Recent Errors Only
/Pods/Headers/Public/abseil/absl/time/time.h:77:10: 'chrono' file not found
Could not build Objective-C module 'Darwin'
```

Everything works fine if Firebase is removed from the podfile.
Also the project compiles OK on Intel based laptop.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by ryanwilson** [comment]
Hi @akopanev, sorry for the troubles you're seeing. I just tested on my M1 Mac mini and was unable to reproduce (using a clean project and the Podfile you provided).

Perhaps this is something wrong in Xcode's cache, can you clear derived data and try a clean build? If that doesn't work, we'll likely need a project that can reproduce the issue to make any further progress.

Thanks!

**Comment by akopanev** [comment]
@ryanwilson thanks for swift reply!

I've also created an [empty project](https://github.com/akopanev/ios-firestore-m1-issue), added podfile and reproduced the error.

**Comment by ryanwilson** [comment]
Hmm, even with your sample project (thanks for providing) I'm unable to reproduce. It could be a CocoaPods cache issue. Can you try using the [`pod cache clean`](https://guides.cocoapods.org/terminal/commands.html#pod_cache_clean) command? You may also need to clean the cache at ~/Library/Caches/CocoaPods/

**Comment by akopanev** [comment]
Thanks a lot @ryanwilson, cleaning the pods cache resolved the issue.

**Comment by ryanwilson** [comment]
Happy to hear, thanks!
