### ISSUE TITLE
FirebaseMessagingDependencies as a separate library for SPM

### ISSUE THREAD

**Issue by TizianoCoroneo** [firebase/firebase-ios-sdk#7134]
### Feature proposal

* Firebase Component: Messaging

I'm trying out the SPM integration for Firebase, but I need to have FirebaseMessaging alongside with other few Firebase libraries. FirebaseMessaging does not support SPM yet, and it's unclear how long will it take to implement support.

An easy workaround is to expose all the FirebaseMessaging dependencies as their own library, so that we can import them with SPM, and integrate manually FirebaseMessaging on top of those. I have a PR ready for this.

```swift
    // Only used to support manual integration of FirebaseMessaging, while pulling its dependencies through SPM
    .library(
        name: "FirebaseMessagingDependencies",
        targets: [
            "FirebaseCore",
            "FirebaseInstanceID",
            "GoogleUtilities_AppDelegateSwizzler",
            "GoogleUtilities_Environment",
            "GoogleUtilities_Reachability",
            "GoogleUtilities_UserDefaults",
        ]
    ),
```

Of course this extra library should be removed from the Package.swift file once FirebaseMessaging supports SPM. If this is on the horizon, let's close this issue, as it would only be a temporary workaround.

**Comment by ryanwilson** [comment]
Hi there @TizianoCoroneo - thanks for the report.

FirebaseMessaging does support SwiftPM already: https://github.com/firebase/firebase-ios-sdk/blob/2efbb1047d6f4cd9baa7bd417674c51d908790f8/Package.swift#L75-L78

I see our docs are out of date there, I'll fix them.

Let us know if you're having other issues getting up and running. Thanks!

**Comment by TizianoCoroneo** [comment]
Well, that simplifies things considerably 😂

I tried to add Messaging with SPM (7.1.0) and I was getting an error like "no symbol for Messaging": it was adding the module correctly, but it couldn't find the class name for some reason.
I assumed this was a known bug because of the outdated documentation, and proceeded to open this issue.

I'm trying again using 7.2.0, I'll let you know how it goes 🙏

**Comment by ryanwilson** [comment]
Hmm, both `import Firebase` and `import FirebaseMessaging` should make the `Messaging` symbol available. Let me know if that's not the case and I can look into it. Thanks!

**Comment by TizianoCoroneo** [comment]
Using 7.2.0 everything works fine 👍 I think the error I encountered was related to having Carthage frameworks still around after the migration from Carthage to SPM. Thank you anyway 🙏
