### ISSUE TITLE
Firebase Analytics in a library Cocoapod podspec causes pod lint to fail

### ISSUE THREAD

**Issue by tengelmeier** [firebase/firebase-ios-sdk#7136]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.2
  * Firebase SDK version: 7.1
  * Installation method: `CocoaPods`
  * Firebase Component: FIRAnalytics
### [REQUIRED] Step 2: Describe the problem

Using Firebase Analytics in a library PodSpec causes pod lint to fail

#### Steps to reproduce:

If you include Firebase/Analytics as a dependency in a Cocoapod podspec,
 `pod lint --allow-warnings` fails when trying to validate the simulator build 

#### Relevant Code:
Add the following to newly created Cocoapods library podspec (sample at [https://github.com/tengelmeier/PodLintErrorSample] )

```
    s.static_framework = true             # required as firebase is static
    s.dependency 'Firebase/Analytics' 
```

Result: 

```ruby
pod lib lint --allow-warnings --verbose


>[...]
  	ld: in .../FIRAnalyticsConnector(FIRAnalyticsConnector_a8eeba373b74508311b8b22b8d3202a6.o), building for iOS Simulator, but linking in object file built for iOS, file '.../FIRAnalyticsConnector' for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
...
	[!] PodLintErrorSample did not pass validation, due to 1 error.
	You can use the `--no-clean` option to inspect any issue.

```

**Comment by paulb777** [comment]
@tengelmeier Thanks for the report. This is a result of Xcode 12 requiring an arm64 simulator slice in binary pods. There are three workarounds:

- Use Xcode 11
- Add the `--skip-import-validation` option
- Use the M1 variant of the release. See https://github.com/firebase/firebase-ios-sdk/blob/master/AppleSilicon.md

I'll close the issue, but feel free to ask any follow up questions here.

**Comment by tengelmeier** [comment]
Thanks for the comment. 

While 

`pod lib lint --allow-warnings --verbose --skip-import-validation`

still failed, 

`pod repo push --allow-warnings --verbose --skip-import-validation`

worked.
