### ISSUE TITLE
v7.3.0 Release notes (missing)

### ISSUE THREAD

**Issue by skuske** [firebase/firebase-ios-sdk#7143]
Don't know where else to post this, but the release notes for v7.3.0 are missing. Can someone post the changes, please? Many thanks and sorry for posting this as an issue ... Please close if required.

**Comment by paulb777** [comment]
@skuske Sorry about the delay. We'll try to get them out later today.

**Comment by skuske** [comment]
@paulb777 No worries + many thanks!

**Comment by paulb777** [comment]
Published now. https://firebase.google.com/support/release-notes/ios

Thanks for the heads-up!
