### ISSUE TITLE
Firebase/Installations and FirebaseFirestoreSwift dependency conflict

### ISSUE THREAD

**Issue by ARDeploy** [firebase/firebase-ios-sdk#7148]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.2
  * Firebase SDK version: 7.3.0
  * Installation method: `CocoaPods` (select one)
  * Firebase Component: Installations (Auth, Core, Database, Firestore, Messaging, Storage, etc)

### [REQUIRED] Step 2: Describe the problem

Dependency issues between FirebaseFirestoreSwift and Firebase/Installations

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Add pods and try install:

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Installations'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Functions'

Error:

[!] CocoaPods could not find compatible versions for pod "nanopb":
  In Podfile:
    Firebase/Installations was resolved to 7.0.0, which depends on
      Firebase/CoreOnly (= 7.0.0) was resolved to 7.0.0, which depends on
        FirebaseCore (= 7.0.0) was resolved to 7.0.0, which depends on
          FirebaseCoreDiagnostics (~> 7.0) was resolved to 7.3.0, which depends on
            nanopb (~> 2.30906.0)

    FirebaseFirestoreSwift was resolved to 0.4.0, which depends on
      FirebaseFirestore (>= 1.6.1, ~> 1.6) was resolved to 1.12.1, which depends on
        nanopb (~> 0.3.901)

Alternatively, add Installations to existing repo:

[!] CocoaPods could not find compatible versions for pod "FirebaseCore":
  In Podfile:
    Firebase/Installations was resolved to 7.0.0, which depends on
      Firebase/CoreOnly (= 7.0.0) was resolved to 7.0.0, which depends on
        FirebaseCore (= 7.0.0)

    FirebaseFirestoreSwift was resolved to 0.4.0, which depends on
      FirebaseFirestore (>= 1.6.1, ~> 1.6) was resolved to 1.19.0, which depends on
        FirebaseCore (~> 6.10)

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Installations'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Functions'
```

**Comment by paulb777** [comment]
Change the Podfile to `pod 'FirebaseFirestoreSwift', '~> 7.0-beta'`.  More details at https://stackoverflow.com/a/64671117/556617
