### ISSUE TITLE
Crashlytics cron CI failure

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#7154]
It looks like something about the Friday changes to Crashlytics exposed a test failure the last three nights running the macos static framework pod lib lint test.

It doesn't reproduce locally for me running `./scripts/pod_lib_lint.rb FirebaseCrashlytics.podspec --platforms=macos --use-static-frameworks --no-clean`

From #7149, the failure is 

`- NOTE | [OSX] xcodebuild: /Users/runner/work/firebase-ios-sdk/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSProcessReportOperationTests.m:89: error: -[FIRCLSProcessReportOperationTests testExceptionSymbolication] : (([fileManager copyItemAtPath:[self pathForResource:FIRCLSReportExceptionFile] toPath:[report pathForContentFile:FIRCLSReportExceptionFile] error:nil]) is true) failed`

The nightly test disabled in #7191 can be reenabled when this is resolved.

**Comment by samedson** [comment]
Apologies for this. Let me roll back and get the change correctly working.

**Comment by samedson** [comment]
I believe it's a flake - seems we're not cleaning up a file and somehow the changes have caused the flake to come out more.

The changes are completely unrelated, but CI passed when I reverted the change.

**Comment by paulb777** [comment]
Yeah - it seems like it could be a flake since it only happens on macos with static frameworks and isn't locally reproducible for me. 

Note that it's only the cron test that fails, so this line would need to be commented to test separate from the nightly scheduled job - https://github.com/firebase/firebase-ios-sdk/blob/master/.github/workflows/crashlytics.yml#L106
