### ISSUE TITLE
iOS app 'com.' lacks App ID Prefix. UniversalLinks is not enabled for the app

### ISSUE THREAD

**Issue by wangxingxing123654** [firebase/firebase-ios-sdk#7164]
have setting the teamid ,App Store ID, package id in the firebase console, but the dynamic links preview always show the warning   `iOS app 'com.' lacks App ID Prefix. UniversalLinks is not enabled for the app`

**Comment by morganchen12** [comment]
Hey @wangxingxing123654, please fill out the issue template. Note that your app ID prefix may be different from your team ID.

**Comment by wangxingxing123654** [comment]
> Hey @wangxingxing123654, please fill out the issue template. Note that your app ID prefix may be different from your team ID.

i have seen it from the appstore, i copy it  from appstore,and paste it

**Comment by paulb777** [comment]
@wangxingxing123654 We still need the template filled out with information about your Firebase installation.
