### ISSUE TITLE
 [[NSAssertionHandler currentHandler] Last Exception Backtrace (0)

### ISSUE THREAD

**Issue by jignesh123** [firebase/firebase-ios-sdk#7166]
![Screenshot 2020-12-15 at 10 20 59 AM](https://user-images.githubusercontent.com/3581813/102172838-a3a35c80-3ebf-11eb-972b-d1f94f677679.png)

Hello,

I am getting this issue on iOS 14.2 mainly. Please help me.

Thanks

**Comment by morganchen12** [comment]
Please fill out the issue template and share the full crash stack trace.

**Comment by jignesh123** [comment]
I get this in crash report of apple and it is redirect to here in my code. 
Please see screenshot below for more details.
![Screenshot 2020-12-15 at 11 37 56 AM](https://user-images.githubusercontent.com/3581813/102177773-35b06280-3eca-11eb-8f32-dfd00da91b7e.png)

**Comment by wilhuff** [comment]
Since you're able to see the exception under Xcode, you should be able to see the error message in the debug console. Please include that as well.

Based on what I can see of the stack it looks like Firestore is failing to open its underlying database. There are a variety of reasons why this might happen, the most common of which is that you already have Firestore open--you can't open the same Firestore instance more than once. This may or may not be the issue--the error message will help figure this out.

Another clue that may help is examining what your other threads are doing at the time of the crash. If you type `bt all` at the lldb prompt you'll get a full stack trace involving all the threads.

**Comment by jignesh123** [comment]
NSException* MakeException(ExceptionType type, const std::string& message) {
  return [[NSException alloc] initWithName:ExceptionName(type)
                                    reason:MakeNSString(message)
                                  userInfo:nil];
}

}  // namespace

ABSL_ATTRIBUTE_NORETURN void ObjcThrowHandler(ExceptionType type,
                                              const char* file,
                                              const char* func,
                                              int line,
                                              const std::string& message) {
  if (type == ExceptionType::AssertionFailure) {
    [[NSAssertionHandler currentHandler]
        handleFailureInFunction:MakeNSString(func)
                           file:MakeNSString(file)
                     lineNumber:line
                    description:@"%@: %s", ExceptionName(type),
                                message.c_str()];
    std::terminate();
  } else {
    @throw MakeException(type, message);  // NOLINT
  }
}

**Comment by jignesh123** [comment]
I dont get this in when testing but in app-store crash report this is showing.

**Comment by schmidt-sebastian** [comment]
@jignesh123 Do you see a log message? Unfortunately, the stacktrace shows the "generic" path for our exception handling. We would need the error message that is associated with the stacktrace to look at this in more detail.

**Comment by jignesh123** [comment]
@schmidt-sebastian  I only get this when I redirect to my project code. Please check it in attached image and try to solve my problem.
Thanks
![102172838-a3a35c80-3ebf-11eb-972b-d1f94f677679](https://user-images.githubusercontent.com/3581813/103258727-52659380-49bc-11eb-9c60-e5aa2c904d38.png)

**Comment by jignesh123** [comment]
Hello,
this is the crash report I have get from apple.

**Comment by schmidt-sebastian** [comment]
Thank you for the stacktrace. The assertion that triggers this crash seem to be https://github.com/firebase/firebase-ios-sdk/blob/eb21690b803cbbad83a8ad2fa51d43fd1f3fa2b4/Firestore/core/src/core/firestore_client.cc#L186

This likely indicates that we are not able to open LevelDB persistence on the user's device. Unfortunately, the actual underlying error is not available in the crash report. My wild guesses are that the app doesn't have access to the file system at the time (i.e. it was just backgrounded). 

We have some outstanding work items to handle LevelDB failures more gracefully, but this is a major effort that we have not yet started. Are you able to use Firestore with [persistence disabled](https://firebase.google.com/docs/reference/swift/firebasefirestore/api/reference/Classes/FirestoreSettings#/c:objc(cs)FIRFirestoreSettings(py)persistenceEnabled)?
