### ISSUE TITLE
Building on M1 Mac leads to Incorrect Architecture Linking

### ISSUE THREAD

**Issue by kevinchau** [firebase/firebase-ios-sdk#7175]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.2
  * Firebase SDK version: 7.3.0
  * Installation method: `CocoaPods`
  * Firebase Component: RemoteConfig, Analytics

#### Steps to reproduce:

On an M1 Mac (Apple Silicon), running my project for the iOS Simulator results in the following:

```
ld: in /Users/kevinchau/Documents/dev/radioapp-ios/Pods/FirebaseAnalytics/Frameworks/FIRAnalyticsConnector.framework/FIRAnalyticsConnector(FIRAnalyticsConnector_a8eeba373b74508311b8b22b8d3202a6.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/kevinchau/Documents/dev/radioapp-ios/Pods/FirebaseAnalytics/Frameworks/FIRAnalyticsConnector.framework/FIRAnalyticsConnector' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

If I add `arm64` into Excluded Architectures for the target, then I will get `No Such Module: FirebaseRemoteConfig`

**Comment by kevinchau** [comment]
Seems related to building for the simulator. Running on a debug device via USB works fine.

**Comment by ryanwilson** [comment]
Hi @kevinchau, sorry for the trouble. I believe this is a CocoaPods 1.9 issue and it was resolved in 1.10. Can you check which version of CocoaPods you have installed?

**Comment by paulb777** [comment]
Also make sure you're following the CocoaPods instructions for using an M1 Mac. See https://github.com/firebase/firebase-ios-sdk/blob/master/AppleSilicon.md

**Comment by kevinchau** [comment]
@ryanwilson I'm running 1.10.0

@paulb777 When I run `pod install` after adding the -M1 version tag, I'm getting this issue.

```
[!] CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
  In snapshot (Podfile.lock):
    GoogleAppMeasurement (= 7.3.0, ~> 7.0)

  In Podfile:
    Firebase/Analytics (= 7.3.0-M1) was resolved to 7.3.0-M1, which depends on
      Firebase/Core (= 7.3.0-M1) was resolved to 7.3.0-M1, which depends on
        FirebaseAnalytics (= 7.3.0-M1) was resolved to 7.3.0-M1, which depends on
          GoogleAppMeasurement (= 7.3.0-M1)

Specs satisfying the `GoogleAppMeasurement (= 7.3.0, ~> 7.0), GoogleAppMeasurement (= 7.3.0-M1)` dependency were found, but they required a higher minimum deployment target.
```

I have my podfile with this as the first line:

`platform :ios, '10.0'`

I've tried everything all the way up to 13.0 - I'm getting the same error message calling for a higher minimum deployment target.

**Comment by ryanwilson** [comment]
@kevinchau  I'll reach out to the Ads team and find out what I can.

**Comment by davidhodge** [comment]
FYI: The excluded architecture approach doesn't seem to work in some cases. It's telling me that the simulator needs an ARM64 binary.

**Comment by paulb777** [comment]
I'm going to close since the OP's question was resolved.

Please open another Issue if you have additional questions on any of the tangential topics in this issue thread.
