### ISSUE TITLE
FR: Firebase Crashlytics needs better support for iOS SwiftUI

### ISSUE THREAD

**Issue by corban123** [firebase/firebase-ios-sdk#7186]
### Feature proposal

* Firebase Component: crashlytics (Auth, Core, Database, Firestore, Messaging, Storage, etc)

Describe your use case and/or feature request here.

Current crashes in SwiftUI that are tracked by crashlytics are generally useless. A current stack trace will look like

```
0
SwiftUI
_LayoutTraits.Dimension.init(min:ideal:max:) + 52
1
SwiftUI
Image.Resolved.layoutTraits() + 308
66
UIKitCore
UIApplicationMain + 1936
```

Being able to successfully track crashes for those that happen in SwiftUI code should be prioritized as SwiftUI becomes more prominently used.

**Comment by themiswang** [comment]
Hey folks,

This have been improved in Apple side for macOS 15, iOS 18, tvOS 18, or visionOS 2, for details check Xcode 16 [release note](https://developer.apple.com/documentation/xcode-release-notes/xcode-16-release-note)
![Screenshot 2024-11-21 at 2 21 08 PM](https://github.com/user-attachments/assets/39423f6d-2c89-4329-906d-3e0a84a387b9)

Now on iOS 18 stack trace for SwiftUI will be like:
![image](https://github.com/user-attachments/assets/386a9ead-4152-4bd4-aa48-d47ef3d425ca)

Gonna close this feature request🎉
