### ISSUE TITLE
Transfer iOS app that uses Apple Sign in and Firebase to a new developer account

### ISSUE THREAD

**Issue by fangyuxi** [firebase/firebase-ios-sdk#7190]
We are in the process of transferring an app from one Apple developer account to another one as part of an app acquisition. The app uses Apple Sign in and Firebase authentication and it seems that there are a few steps to complete related to generating transfer identifiers for users that have signed up using Apple Sign in. This is documented here:

https://developer.apple.com/documentation/sign_in_with_apple/transferring_your_apps_and_users_to_another_team

However, because we use Firebase as the backend for our app we don't have direct control of the authentication process and the user ids generated by Apple sign in and how they are stored in Firebase Auth and how to update them after app transfer.

Thank you.

**Comment by fangyuxi** [comment]
@paulb777 Hello, Any Updates? I want to confirm as soon as possible whether I can transfer the App, and I need to sign an agreement with the customer.

**Comment by morganchen12** [comment]
You will likely need to file a [support ticket](https://firebase.google.com/support) for this type of issue.

**Comment by fangyuxi** [comment]
@morganchen12 
OK, Thank you.
