### ISSUE TITLE
Cocoapod doesn't install/update Firebase Components to latest versions.

### ISSUE THREAD

**Issue by AlbertoMalavasi** [firebase/firebase-ios-sdk#7195]
Environment
  * Xcode version: 12.3
  * Firebase SDK version: 6.34 updating to -> latest
  * Installation method: CocoaPods
  * Firebase Component: 
                    * 'Firebase/Auth'
                    * 'Firebase/Firestore'
                    * 'Firebase/Storage'
                    * 'FirebaseFirestoreSwift'
                    * 'FirebaseUI/Storage'

### [REQUIRED] Step 2: Describe the problem

Following the documentation, Cocoapods doesn't install/update Firebase to latest stable version. 
Lead also to multiple warnings: 
The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99.

#### Steps to reproduce:

Following the official documentation, run pod install/update

#### Relevant Code:

------- Podfile -------

Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target *** do
  Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  Pods for ***
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'FirebaseFirestoreSwift'
  pod 'FirebaseUI/Storage'
  
end

------- Terminal -------

Installing Alamofire (5.4.0)
Installing BoringSSL-GRPC (0.0.7)
Installing **Firebase (6.34.0)**
Installing FirebaseAuth (6.9.2)
Installing FirebaseCore (6.10.4)
Installing FirebaseCoreDiagnostics (1.7.0)
Installing FirebaseFirestore (1.19.0)
Installing FirebaseFirestoreSwift (0.4.0)
Installing FirebaseStorage (3.9.1)
Installing FirebaseUI (9.0.0)
Installing GTMSessionFetcher (1.5.0)
Installing GoogleDataTransport (7.5.1)
Installing GoogleUtilities (6.7.2)
Installing PromisesObjC (1.2.11)
Installing SDWebImage (5.10.0)
Installing abseil (0.20200225.0)
Installing gRPC-C++ (1.28.2)
Installing gRPC-Core (1.28.2)
Installing leveldb-library (1.22)
Installing nanopb (1.30906.0)

**Comment by paulb777** [comment]
@AlbertoMalavasi Thanks for the report

We changed to explicit beta versioning in the 7.0.0 release.

Change the Podfile to pod 'FirebaseFirestoreSwift', '~> 7.3-beta'. More details at https://stackoverflow.com/a/64671117/556617 and the [Release Notes](https://firebase.google.com/support/release-notes/ios).

**Comment by paulb777** [comment]
Not that 8.x is out, it should be `pod 'FirebaseFirestoreSwift', '~> 8.0-beta'.`
