### ISSUE TITLE
Storage - listAllWithCompletion calls the completion helper twice if an error occured 

### ISSUE THREAD

**Issue by TPXP** [firebase/firebase-ios-sdk#7197]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.3
  * Firebase SDK version: 7.2.0
  * Installation method: `CocoaPods`
  * Firebase Component: Storage

#### Steps to reproduce:

* Create a ref for a cloud storage folder the current user cannot list items.
* Call `listAllWithCompletion` on this StorageRef  
* Notice the completion helper is called twice: once with the `permission denied` error, the other time with an empty directory result.

#### Relevant Code:
Sorry, I suck at ObjC, here's a reproduction with the RNFirebase SDK https://github.com/invertase/react-native-firebase/pull/4688

This issue can be summed up in one question: Is there a missing `return` here:
https://github.com/firebase/firebase-ios-sdk/blob/14764b8d60a6ad023d8fa5b7f81d42378d92e6fe/FirebaseStorage/Sources/FIRStorageReference.m#L417

... Or did you intend to call the completion helper with the files you got so far if an error occurs?

Since this seems to differ with the behaviour on Android (where the `Task` class will not allow you to reject and resolve the same task, I think?), I think adding a warning in the documentation could help anyway.

**Comment by paulb777** [comment]
@TPXP Thanks for the thorough report and analysis. I believe that your assumption is correct and a `return` should be added after the callback. We'll confirm with the Storage team and, if so, make the fix.
