### ISSUE TITLE
[CocoaPods] Undefined symbols for architecture x86_64 error when compile

### ISSUE THREAD

**Issue by Blurzschyter** [firebase/firebase-ios-sdk#7198]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.2
  * Firebase SDK version: 6.11.0
  * Installation method: `CocoaPods`
  * Firebase Component: Core, Analytics

### [REQUIRED] Step 2: Describe the problem

After doing pod install on my project, i encountered this "Undefined symbols for architecture x86_64" error when trying to compiled it using the Simulator.

![error_img](https://user-images.githubusercontent.com/23515008/102749480-0f456800-439f-11eb-8cb3-a86057cee604.jpg)

I already tried to add -Objc at Build Setting > Other Linker Flags, removed derived data, & run project cleanup, but it doesn't solved the error.

#### Steps to reproduce:

1. You may clone the sample project from here : [https://bitbucket.org/Blurzschyter/projectxyz/src/master/](https://bitbucket.org/Blurzschyter/projectxyz/src/master/)
2. Uncomment the firebase pod line on podfile.
3. Run pod install

Thank you in advance ^_^

**Comment by paulb777** [comment]
@Blurzschyter Those missing symbols are not related to Firebase. It looks like a problem related to lightWebiOS.a and VmxCutInterface.

The binary archive `./EXTSDK/libs/libViewRightWebiOS.a` does not have a simulator slice:

```
$ file ./EXTSDK/libs/libViewRightWebiOS.a
./EXTSDK/libs/libViewRightWebiOS.a: Mach-O universal binary with 2 architectures: [arm_v7:current ar archive random library] [arm64]
./EXTSDK/libs/libViewRightWebiOS.a (for architecture armv7):	current ar archive random library
./EXTSDK/libs/libViewRightWebiOS.a (for architecture arm64):	current ar archive random library
```
