### ISSUE TITLE
All Paths to Custom Domain Dynamic Link Opens the App

### ISSUE THREAD

**Issue by coolcool1994** [firebase/firebase-ios-sdk#7216]
Issue is described here by another person: https://stackoverflow.com/questions/64321804/firebase-dynamic-links-opening-all-of-my-domain-links-in-the-app.
I followed the steps described in https://firebase.google.com/docs/dynamic-links/custom-domains very carefully (also read it multiple times).
This bug only exists in iOS. Android works perfectly.

BUG:
- Let's say you have a custom domain dynamic link: https://example.com/app (I created this from the Firebase console) and have website https://example.com through Firebase Hosting.
- After you install the app, only "https://example.com/app" should open the app, and "https://example.com" should open the website. Right now the bug is they both open the app. In fact, any path that follows and including https://example.com will be a dynamic link no matter what you set as "rewrites" in the Firebase Hosting's "firebase.json" file. When the app isn't installed, everything works as expected. The problem is when the app is downloaded.
- To help you guys fix the bug, I think the bug is https://example.com/apple-app-site-association returns in the browser : {"applinks":{"apps":[],"details":[{"appID":"**hidden***","paths":["NOT /_/*","/*"]},{"appID":"***hidden**","paths":["NOT /_/*","/*"]}]}}
- Only https://example.com/app/apple-app-site-association  should return that json object, not https://example.com (actual is the other way around: currently https://example.com/app/apple-app-site-association doesn't return the json object and instead returns "Dynamic Link Not Found" error screen).

I hope you guys fix it. Right now when you set a dynamic link with custom domain, the entire domain (no matter what the rest of the path is) becomes dynamic link and become useless for other purposes, which is a HUGE bug and should be prioritized. Please don't ask for more info just to delay the inevitable! You guys have all the info you need.

**Comment by coolcool1994** [comment]
This is the same iOS issue that I created several months ago: https://github.com/firebase/firebase-ios-sdk/issues/5376

Still not fixed!

**Comment by paulb777** [comment]
Closing for staleness. Please comment or open a new issue to reopen.
