### ISSUE TITLE
GoogleDataTransport caused crash

### ISSUE THREAD

**Issue by Zhangyanshen** [firebase/firebase-ios-sdk#7234]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.1
  * Firebase SDK version: 7.1.0
  * Installation method: CocoaPods
  * Firebase Component: Core, Analytics, Crashlytics

#### Steps to reproduce:

I don't know how to reproduce this problem,I saw this problem in the Firebase console and it happens every day.It happens in the GoogleDataTransport.It seems that crashed while processing and uploading files.Below is the stack information at the time of the crash.

```
com.google.GDTCORFlatFileStorage
0  libsystem_kernel.dylib         0x190cd3a60 write + 8
1  Foundation                     0x1912a89e8 _NSWriteToFileDescriptorWithProgress + 216
2  Foundation                     0x1912aa074 ___NSWriteDataToFileWithExtendedAttributes_block_invoke + 76
3  Foundation                     0x1911d7740 -[NSData(NSData) enumerateByteRangesUsingBlock:] + 124
4  Foundation                     0x1912a9bec _NSWriteDataToFileWithExtendedAttributes + 556
5  AXXStudentApp                  0x1031f164c __71-[GDTCORFlatFileStorage libraryDataForKey:onFetchComplete:setNewValue:]_block_invoke + 325 (GDTCORFlatFileStorage.m:325)
6  libdispatch.dylib              0x190ba09a8 _dispatch_call_block_and_release + 24
7  libdispatch.dylib              0x190ba1524 _dispatch_client_callout + 16
8  libdispatch.dylib              0x190b4d8a4 _dispatch_lane_serial_drain$VARIANT$mp + 608
9  libdispatch.dylib              0x190b4e294 _dispatch_lane_invoke$VARIANT$mp + 416
10 libdispatch.dylib              0x190b5778c _dispatch_workloop_worker_thread + 588
11 libsystem_pthread.dylib        0x190bf2b74 _pthread_wqthread + 272
12 libsystem_pthread.dylib        0x190bf5740 start_wqthread + 8
```

Here is the stack information for another crash

```
com.apple.uikit.backgroundTaskAssertionQueue
0  libsystem_kernel.dylib         0x1abcf877c __ulock_wait + 8
1  libsystem_platform.dylib       0x1abc07ef0 _os_unfair_lock_lock_slow + 192
2  AssertionServices              0x1b06a48d4 -[BKSAssertion _invalidateSynchronously:] + 40
3  AssertionServices              0x1b06a9254 -[BKSProcessAssertion invalidate] + 92
4  UIKitCore                      0x1affd5458 __36-[UIApplication _endBackgroundTask:]_block_invoke.3402 + 272
5  UIKitCore                      0x1affa9068 -[_UIObjectReferenceCounter decrementReferenceForObject:invalidationHandler:] + 288
6  UIKitCore                      0x1affd5314 __36-[UIApplication _endBackgroundTask:]_block_invoke + 320
7  libdispatch.dylib              0x1abbc8524 _dispatch_client_callout + 16
8  libdispatch.dylib              0x1abb7b0b0 _dispatch_lane_barrier_sync_invoke_and_complete + 56
9  UIKitCore                      0x1affd5070 -[UIApplication _endBackgroundTask:] + 864
10 AXXStudentApp                  0x10150a03c -[GDTCORApplication endBackgroundTask:] + 512 (GDTCORPlatform.m:512)
11 AXXStudentApp                  0x1014ff164 __46-[GDTCCTUploader uploadTarget:withConditions:]_block_invoke + 228 (GDTCCTUploader.m:228)
12 libdispatch.dylib              0x1abbc79a8 _dispatch_call_block_and_release + 24
13 libdispatch.dylib              0x1abbc8524 _dispatch_client_callout + 16
14 libdispatch.dylib              0x1abb748a4 _dispatch_lane_serial_drain$VARIANT$mp + 608
15 libdispatch.dylib              0x1abb75294 _dispatch_lane_invoke$VARIANT$mp + 416
16 libdispatch.dylib              0x1abb7e78c _dispatch_workloop_worker_thread + 588
17 libsystem_pthread.dylib        0x1abc19b74 _pthread_wqthread + 272
18 libsystem_pthread.dylib        0x1abc1c740 start_wqthread + 8
```

**Comment by paulb777** [comment]
@Zhangyanshen Thanks for the report.  We'll investigate. In the meantime, it could be worth checking if updating to Firebase 7.3.x addresses the issue since there have been a few fixes to GoogleDataTransport.

**Comment by Zhangyanshen** [comment]
> @Zhangyanshen Thanks for the report. We'll investigate. In the meantime, it could be worth checking if updating to Firebase 7.3.x addresses the issue since there have been a few fixes to GoogleDataTransport.

Thanks for your reply. I'll give it a try. I have another question. Can Firebase capture OOM？

**Comment by morganchen12** [comment]
Hey @Zhangyanshen, from what I understand Firebase Crashlytics currently cannot capture OOM crashes (@samedson or @elenadoty to confirm).

**Comment by elenadoty** [comment]
Hi @Zhangyanshen, @morganchen12 is correct - Crashlytics does not currently support OOM crashes.

**Comment by Zhangyanshen** [comment]
> Hey @Zhangyanshen, from what I understand Firebase Crashlytics currently cannot capture OOM crashes (@samedson or @elenadoty to confirm).

@morganchen12 Thank you for your answer.👍

**Comment by Zhangyanshen** [comment]
> Hi @Zhangyanshen, @morganchen12 is correct - Crashlytics does not currently support OOM crashes.

@elenadoty Thank you for your answer. Do you have any plans to add this feature?

**Comment by morganchen12** [comment]
We do not currently have plans to add this feature. Adding OOM crash capture with the same degree of accuracy as Crashlytics' normal crash capture is potentially not possible due to app sandbox and platform limitations.

**Comment by Zhangyanshen** [comment]
> We do not currently have plans to add this feature. Adding OOM crash capture with the same degree of accuracy as Crashlytics' normal crash capture is potentially not possible due to app sandbox and platform limitations.

Thank you!

**Comment by Akanksha-nuclei** [comment]
@elenadoty Is there any way I can resolve this issue? @Zhangyanshen  Did you find any solution??

**Comment by morganchen12** [comment]
@maksymmalyhin can you take a look at the stack traces? It's not immediately clear to me what's causing these crashes, but at least one of them is related to background processes.

**Comment by maksymmalyhin** [comment]
@Zhangyanshen Could you please a full crash report to understand the issue better? It is very hard to understand the source of the issue from the information provided. The following information will be helpful: 
- the exception/reason of the crash reported by the OS
- other threads stack traces: the root reason may be not visible in the crashed thread
- could you please make sure the provided stack traces are for the crashing threads?
- can you see any patterns, e.g. all crashes happen on iOS 14+/beta version/etc., crashes happen more likely on old devices, etc. ?
- a sample app with where the crash can be reproduces would be significantly speedup the investigation
- anything else you noticed that may look relevant

**Comment by Zhangyanshen** [comment]
> I am also facing the same issue. @elenadoty Is there any way I can resolve this issue? @Zhangyanshen Did you find any solution??

@Akanksha-nuclei  After I upgraded to 7.3.0, these issues disappeared. You can try it.

**Comment by Zhangyanshen** [comment]
> @Zhangyanshen Could you please a full crash report to understand the issue better? It is very hard to understand the source of the issue from the information provided. The following information will be helpful:
> 
> * the exception/reason of the crash reported by the OS
> * other threads stack traces: the root reason may be not visible in the crashed thread
> * could you please make sure the provided stack traces are for the crashing threads?
> * can you see any patterns, e.g. all crashes happen on iOS 14+/beta version/etc., crashes happen more likely on old devices, etc. ?
> * a sample app with where the crash can be reproduces would be significantly speedup the investigation
> * anything else you noticed that may look relevant

After I upgraded to 7.3.0, these issues disappeared. Thank you!
