### ISSUE TITLE
Rename / delete branch `combine-master` in favour of `combine-main`

### ISSUE THREAD

**Issue by peterfriese** [firebase/firebase-ios-sdk#7238]
We've received a couple of PRs agains `combine-master`. Since we decided to use `combine-main` for developing Combine support, I suggest to either delete `combine-master` or rename it (e.g. to `archived-combine-master`) to avoid any further confusion.

**Comment by peterfriese** [comment]
There are two open PRs:
- #7237 - I've asked the author to retarget this one to [`peterfriese-combine-main`](https://github.com/firebase/firebase-ios-sdk/tree/peterfriese/combine-main)
- #5484 - which I think is obsolete

**Comment by peterfriese** [comment]
Ok, we're clear to go now. #7237 was retargeted.

**Comment by ryanwilson** [comment]
Deleted, thanks!
