### ISSUE TITLE
Firebase Cloud Messaging Notifications Delay

### ISSUE THREAD

**Issue by erickogi** [firebase/firebase-ios-sdk#7239]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 12.2 (12B45b)
  * Firebase SDK version: 6.10.4
  * Installation method: CocoaPods
  * Firebase Component:  Core,  Messaging, Analytics, InAppMessaging ,Performance ,Crashlytics ,DynamicLinks

### [REQUIRED] Step 2: Describe the problem

The firebase notification once sent from the server takes a long while to be received on the IOS app and sometimes is not received at all.

The response received from firebase is a success.

{ multicast_id: 8379552369605958000,
  success: 1,
  failure: 0,
  canonical_ids: 0,
  results: [ { message_id: '1609436035476335' } ] }

#### Steps to reproduce:

You can use the [quickstart](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Ffirebase%2Fquickstart-ios%2Ftree%2Fmaster%2Fmessaging&sa=D&sntz=1&usg=AFQjCNGonv7TT5_Vx85IF-bXhR-nzfMCfA) project for firebase messaging.

                **REQUEST** 
               
                      to: “TOKENHERE,
                       notification: {
                                title: "my title",
                                body: “My message here”,
                                badge: "1"
                        },
                        data: {
                                title: "my title",
                                message: “My message here”,
                                pin: “***”
                        },
                        android: {
                                ttl: 60 * 60 * 3,
                                priority: 10
                        },
                        priority: "high",
                        content_available: true,
                        time_to_live: 6000,
                        apns: {
                                payload: {
                                        aps: {
                                                contentAvailable: true,
                                                badge : 1
                                        }
                                }
                               }
                      }

         **RESPONSE**

                { multicast_id: 8379552369605958000,
                  success: 1,
                  failure: 0,
                  canonical_ids: 0,
                  results: [ { message_id: '1609436035476335' } ] }

Thank you.

**Comment by xiuwangthoughtworks** [comment]
Same issue

**Comment by chliangGoogle** [comment]
@erickogi Looks like you are using the direct channel from the response. Would you switch to APNS channel in FCM because [direct channel has been removed since last I/O breaking change](https://github.com/firebase/firebase-ios-sdk/pull/4710).

Please use HTTP v1 API to send the push notifications using APNS channel to receive notification on FCM iOS SDKs.
