### ISSUE TITLE
"GDTCORRegistrar appWillTerminate"  marked as uiblock issue

### ISSUE THREAD

**Issue by aiquantong** [firebase/firebase-ios-sdk#7280]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version:  12.2
  * Firebase SDK version: 6.34.0
  * Installation method: CocoaPods 
  * Firebase Component:
  pod 'Firebase/Analytics', '6.34.0'
  pod 'Firebase/Crashlytics', '6.34.0'
  pod 'Firebase/Performance', '6.34.0'

### [REQUIRED] Step 2: Describe the problem
Recently, My app integrate the bugly [https://bugly.qq.com/] for crash and uiblock detection. 
I notice the "GDTCORRegistrar appWillTerminate" is marked as  uiBlock issue for many times.
There are call-stack captured by the bugly

```
libsystem_kernel.dylib | kevent_id + 8
-- | --
1 libdispatch.dylib | __dispatch_kq_poll + 232
2 libdispatch.dylib | __dispatch_event_loop_wait_for_ownership$VARIANT$mp + 436
3 libdispatch.dylib | ___DISPATCH_WAIT_FOR_QUEUE__ + 292
4 libdispatch.dylib | __dispatch_sync_f_slow + 140
5 ShihuoIPhone | -[GDTCORRegistrar appWillTerminate:] + 596
6 ShihuoIPhone | -[GDTCORLifecycle applicationWillTerminate:] + 468
7 CoreFoundation | ___CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
8 CoreFoundation | ____CFXRegistrationPost_block_invoke + 48
9 CoreFoundation | __CFXRegistrationPost + 400
10 CoreFoundation | _CFXNotificationPost + 696
11 Foundation | -[NSNotificationCenter postNotificationName:object:userInfo:] + 60
12 SHIPhone | -[GDTCORApplication iOSApplicationWillTerminate:] + 104
13 CoreFoundation | ___CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
14 CoreFoundation | ____CFXRegistrationPost_block_invoke + 48
15 CoreFoundation | __CFXRegistrationPost + 400
16 CoreFoundation | _CFXNotificationPost + 696
17 Foundation | -[NSNotificationCenter postNotificationName:object:userInfo:] + 60
18 UIKitCore | -[UIApplication _terminateWithStatus:] + 296
19 UIKitCore | -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 124
20 UIKitCore | -[_UISceneLifecycleMultiplexer forceExitWithTransitionContext:scene:] + 216
21 UIKitCore | -[UIApplication workspaceShouldExit:withTransitionContext:] + 208
22 FrontBoardServices | -[FBSUIApplicationWorkspaceShim workspaceShouldExit:withTransitionContext:] + 84
23 FrontBoardServices | ___63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke_2 + 76
24 FrontBoardServices | -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 232
25 FrontBoardServices | ___63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke + 104
26 libdispatch.dylib | __dispatch_client_callout + 16
27 libdispatch.dylib | __dispatch_block_invoke_direct$VARIANT$mp + 224
28 FrontBoardServices | ___FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 40
29 FrontBoardServices | -[FBSSerialQueue _targetQueue_performNextIfPossible] + 404
30 FrontBoardServices | -[FBSSerialQueue _performNextFromRunLoopSource] + 28
31 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
32 CoreFoundation | ___CFRunLoopDoSource0 + 204
33 CoreFoundation | ___CFRunLoopDoSources0 + 356
34 CoreFoundation | ___CFRunLoopRun + 776
35 CoreFoundation | CFRunLoopRunSpecific + 572
36 GraphicsServices | GSEventRunModal + 160
37 UIKitCore | -[UIApplication _run] + 1052
38 UIKitCore | UIApplicationMain + 164
39 SHIPhone | _main + 636
40 libdyld.dylib | _start + 4
```

**Comment by maksymmalyhin** [comment]
@aiquantong Thank you for the report. Could you please share a bit more what UIBlock issue is meant in this context?

`-[GDTCORRegistrar appWillTerminate:]` does block UI thread to delay the app termination until GoogleDataTransport state is saved to disk to prevent data loses. GoogleDataTransport SDK provides transport layer for Firebase Crashlytics and Performance SDKs, so delaying the app termination to reduce possibility of data losses seems to be justified. I see a room for optimization in GoogleDataTransport SDK but a better understanding of your issue will help to define the optimization vector.
