### ISSUE TITLE
Topic Subscription: calling subscribe() right after unsubscribe() is ignored

### ISSUE THREAD

**Issue by AzaAsim** [firebase/firebase-ios-sdk#729]
### Description
It seems like calling both subscribe() and unsubscribe() one after another confuses the topic subscription queue.

### Environment

  * Xcode version: 9.2 (9C40b)
  * Firebase SDK version: 4.8.2
  * Firebase Component:  Messaging

#### Code Example (subscribe is called before unsubscribe)
```
//When the device is subscribed to "lang-en" but not subscribed to "lang-ku":

Messaging.messaging().subscribe(toTopic: "lang-ku") // This operation works        
Messaging.messaging().unsubscribe(fromTopic: "lang-en") // This operation is Ignored
```

#### Code Example (unsubscribe is called before subscribe)
```
//When the device is subscribed to "lang-ku" but not subscribed to "lang-en":

Messaging.messaging().unsubscribe(fromTopic: "lang-ku") // This operation works
Messaging.messaging().subscribe(toTopic: "lang-en") // This operation is Ignored
```

**Comment by AzaAsim** [comment]
#### Update:
It doesn't seem to be about timing at all.
In fact, calling one method completely disables all subsequent calls to the other

My first thought was that the error occurs when the SDK syncs the topics and has both operations queued: topics to **subscribe to** and topics to **unsubscribe from**.

So I gave a 45 seconds wait time between the two operations.
After this 45 seconds, the first call is long synced with the FCM server. Yet the second still doesn't work.

#### Code:
```
// This is the first call to a FCM topic subscription operation
Messaging.messaging().subscribe(toTopic: "lang-ku") // This call works

//Run after 45 Seconds, or any other time after calling subscribe
DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 45) {
    print("Unsubscribing from 'lang-en'")
    Messaging.messaging().unsubscribe(fromTopic: "lang-en") // This call is ignored
}
```
Having above code, stop and run the app as many times, the device doesn't unsubscribe from "lang-en".


What's interesting though, "lang-en" is kept on the queue.
If you change the code and make the first call on the app to **unsubscribe** and re-run the app, then "lang-en" will be unsubscribed.

#### Modified Code:
```
// This is the first call to a FCM topic subscription operation
Messaging.messaging().unsubscribe(fromTopic: "lang-ku") 

// Above code not only unsubscribes from "lang-ku", it also unsubscribes from "lang-en" 
// Though unsubscribe(fromTopic: "lang-en") was never called on this launch.

```

**Comment by AzaAsim** [comment]
#### Update

This issue is gone now.

**Comment by paulb777** [comment]
Strange. Thanks for the update. Please reopen if it becomes reproducible.

**Comment by AzaAsim** [comment]
Thanks for the quick response.

I made sure to spend an entire day testing before I posted this issue.
And now I'm running the same code on the same environment but the issue is gone.
