### ISSUE TITLE
App crashed on failed to fetch InAppMessaging image

### ISSUE THREAD

**Issue by tanyuantj** [firebase/firebase-ios-sdk#7299]
### Step 0: Are you in the right place?
Yes

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.3 (12C33)
  * Firebase SDK version: 7.3.0
  * Installation method: CocoaPods
  * Firebase Component:  Messaging

### [REQUIRED] Step 2: Describe the problem
I published a test campaign but app crashed when the event fired. I guess it should be silent even if the image is invalid.
#### Steps to reproduce:

Error in fetching image: Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={NSUnderlyingError=0x283ba2af0 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={NSErrorPeerAddressKey=<CFData 0x281791c70 [0x1e707b730]>{length = 16, capacity = 16, bytes = 0x100201bb98c726720000000000000000}, _kCFStreamErrorCodeKey=53, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=https://techcrunch.com/wp-content/uploads/2019/05/Screen-Shot-2019-05-22-at-8.43.37-AM.jpg, NSErrorFailingURLKey=https://techcrunch.com/wp-content/uploads/2019/05/Screen-Shot-2019-05-22-at-8.43.37-AM.jpg, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=53, NSLocalizedDescription=The network connection was lost.}

Error in loading image data for the message.

The callstack exception message is: Image data should never nil for a valid card message.

#### Relevant Code:

No code

**Comment by christibbs** [comment]
@tanyuantj Thanks for reporting. For a test message it should pop up a system alert to show you that there was an error. It would fail silently if it happens in production, though. Will look into this and fix.

**Comment by tanyuantj** [comment]
> @tanyuantj Thanks for reporting. For a test message it should pop up a system alert to show you that there was an error. It would fail silently if it happens in production, though. Will look into this and fix.

@christibbs the fix sounds great and thanks!
