### ISSUE TITLE
#30006 NotSmoothFrameException There are some notsmooth frames in the main thread xxx -[APMIdentity appInstanceID]

### ISSUE THREAD

**Issue by welljobs** [firebase/firebase-ios-sdk#7300]
```

libsystem_kernel.dylib | kevent_id + 8
-- | --
1 libdispatch.dylib | __dispatch_kq_poll + 232
2 libdispatch.dylib | __dispatch_event_loop_wait_for_ownership$VARIANT$mp + 436
3 libdispatch.dylib | ___DISPATCH_WAIT_FOR_QUEUE__ + 292
4 libdispatch.dylib | __dispatch_sync_f_slow + 140
5 xxx | -[APMIdentity appInstanceID] + 144
6 xxx | -[APMIdentifiers appInstanceID] + 188
7 xxx | GADAnalyticsAdRequestDictionary + 132
8 xxx | GADAnalyticsSettingsSignalSource + 168
9 xxx | GAD_GADSignals_arm64_7_63_0 + 4344
10 libdispatch.dylib | __dispatch_call_block_and_release + 24
11 libdispatch.dylib | __dispatch_client_callout + 16
12 libdispatch.dylib | __dispatch_main_queue_callback_4CF$VARIANT$mp + 896
13 CoreFoundation | ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
14 CoreFoundation | ___CFRunLoopRun + 2480
15 CoreFoundation | CFRunLoopRunSpecific + 572
16 GraphicsServices | GSEventRunModal + 160
17 UIKitCore | -[UIApplication _run] + 1052
18 UIKitCore | UIApplicationMain + 164
19 mipci | main + 128
20 libdyld.dylib | _start + 4


```
Caton test 1: I enter the interface, and the interface is not only the request of the advertisement, but also other things. For example, if you cut to the background and then cut back to the foreground before loading your own request, you may get stuck
Caton test 2: I try to enter the interface, exit again, enter the interface again, the third time to enter the interface must be stuck
I hope Google engineer brother can help me see this problem.

**Comment by paulb777** [comment]
This might be related to #6392

**Comment by welljobs** [comment]
The main thread is stuck

**Comment by htcgh** [comment]
We've been having a lot of difficulty trying to reproduce this hang. If you can provide an example project that consistently reproduces it, that would be a huge help.

**Comment by welljobs** [comment]
Task <9C1AE3C1-5EC3-4779-94E3-93B3BDDEFC03>.<4> finished with error [-1200] Error Domain=NSURLErrorDomain Code=-1200 "发生了SSL错误，无法建立与该服务器的安全连接。" UserInfo={NSErrorFailingURLStringKey=https://firebaseinstallations.googleapis.com/v1/projects/firebase-xxx/installations/, NSLocalizedRecoverySuggestion=您仍要连接此服务器吗？, _kCFStreamErrorDomainKey=3, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <9C1AE3C1-5EC3-4779-94E3-93B3BDDEFC03>.<4>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <9C1AE3C1-5EC3-4779-94E3-93B3BDDEFC03>.<4>"
), NSLocalizedDescription=发生了SSL错误，无法建立与该服务器的安全连接。, NSErrorFailingURLKey=https://firebaseinstallations.googleapis.com/v1/projects/firebase-vimtag/installations/, NSUnderlyingError=0x2826f7210 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9816, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9816}}, _kCFStreamErrorCodeKey=-9816}

**Comment by welljobs** [comment]
Task <9C1AE3C1-5EC3-4779-94E3-93B3BDDEFC03>.<4> finished with error [-1200] Error Domain=NSURLErrorDomain Code=-1200 "发生了SSL错误，无法建立与该服务器的安全连接。" UserInfo={NSErrorFailingURLStringKey=https://firebaseinstallations.googleapis.com/v1/projects/firebase-xxx/installations/, NSLocalizedRecoverySuggestion=您仍要连接此服务器吗？, _kCFStreamErrorDomainKey=3, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <9C1AE3C1-5EC3-4779-94E3-93B3BDDEFC03>.<4>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <9C1AE3C1-5EC3-4779-94E3-93B3BDDEFC03>.<4>"
), NSLocalizedDescription=发生了SSL错误，无法建立与该服务器的安全连接。, NSErrorFailingURLKey=https://firebaseinstallations.googleapis.com/v1/projects/firebase-xxx/installations/, NSUnderlyingError=0x2826f7210 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9816, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9816}}, _kCFStreamErrorCodeKey=-9816}

**Comment by welljobs** [comment]
@google-oss-bot How to solve the problem that the main thread is stuck.please help to have a look.

**Comment by morganchen12** [comment]
@welljobs the error you've posted is an SSL failure and is likely unrelated to the main thread being stuck.

**Comment by welljobs** [comment]
@morganchen12 @google-oss-bot @paulb777 This is the thread where I load the Google AD card immediately  and I wonder if it has anything to do with SSL.
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x00000001c4fc4504 libsystem_kernel.dylib`kevent_id + 8
    frame #1: 0x000000010314def8 libdispatch.dylib`_dispatch_kq_poll + 228
    frame #2: 0x000000010314e998 libdispatch.dylib`_dispatch_event_loop_wait_for_ownership + 436
    frame #3: 0x000000010313cb4c libdispatch.dylib`__DISPATCH_WAIT_FOR_QUEUE__ + 308
    frame #4: 0x000000010313c598 libdispatch.dylib`_dispatch_sync_f_slow + 176
    frame #5: 0x0000000101bb5af0 xxx`-[APMIdentity appIDFromGMP] + 132
    frame #6: 0x0000000101bcd30c xxx`-[APMIdentifiers analyticsAppID] + 228
    frame #7: 0x0000000101d5ae24 xxx`___lldb_unnamed_symbol4384$$xxx + 76
    frame #8: 0x0000000101d59474 xxx`GADAnalyticsAdRequestDictionary + 104
    frame #9: 0x0000000101d199f4 xxx`___lldb_unnamed_symbol3074$$xxx + 104
    frame #10: 0x0000000101d4aff4 xxx`___lldb_unnamed_symbol4068$$xxx + 36
    frame #11: 0x000000010312bdb8 libdispatch.dylib`_dispatch_call_block_and_release + 24
    frame #12: 0x000000010312d5fc libdispatch.dylib`_dispatch_client_callout + 16
    frame #13: 0x000000010313ba6c libdispatch.dylib`_dispatch_main_queue_callback_4CF + 972
    frame #14: 0x000000019a6dbc30 CoreFoundation`__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
    frame #15: 0x000000019a6d60e8 CoreFoundation`__CFRunLoopRun + 2480
    frame #16: 0x000000019a6d5200 CoreFoundation`CFRunLoopRunSpecific + 572
    frame #17: 0x00000001b07d0598 GraphicsServices`GSEventRunModal + 160
    frame #18: 0x000000019cf9b004 UIKitCore`-[UIApplication _run] + 1052
    frame #19: 0x000000019cfa05d8 UIKitCore`UIApplicationMain + 164
    frame #20: 0x0000000100ebcb00 xxx`main(argc=1, argv=0x000000016ef47770) at main.m:15:16
    frame #21: 0x000000019a3b4598 libdyld.dylib`start + 4
  thread #3, name = 'gputools.smt_poll.0x28337cde0'
    frame #0: 0x00000001c4fc2d00 libsystem_kernel.dylib`__semwait_signal + 8
    frame #1: 0x00000001a33a3714 libsystem_c.dylib`nanosleep + 212
    frame #2: 0x00000001a33a35ec libsystem_c.dylib`usleep + 64
    frame #3: 0x00000001032db754 GPUToolsCore`smt_poll_thread_entry(void*) + 144
    frame #4: 0x00000001e0002b70 libsystem_pthread.dylib`_pthread_start + 288
  thread #4, name = 'gputools.smt_poll.0x28337d4e0'
    frame #0: 0x00000001c4fc2d00 libsystem_kernel.dylib`__semwait_signal + 8
    frame #1: 0x00000001a33a3714 libsystem_c.dylib`nanosleep + 212
    frame #2: 0x00000001a33a35ec libsystem_c.dylib`usleep + 64
    frame #3: 0x0000000103075644 libMTLCapture.dylib`___lldb_unnamed_symbol2216$$libMTLCapture.dylib + 104
    frame #4: 0x00000001e0002b70 libsystem_pthread.dylib`_pthread_start + 288
  thread #8, name = 'com.apple.uikit.eventfetch-thread'
    frame #0: 0x00000001c4f9f8c4 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #1: 0x00000001c4f9ecc8 libsystem_kernel.dylib`mach_msg + 72
    frame #2: 0x000000019a6db74c CoreFoundation`__CFRunLoopServiceMachPort + 376
    frame #3: 0x000000019a6d5bd0 CoreFoundation`__CFRunLoopRun + 1176
    frame #4: 0x000000019a6d5200 CoreFoundation`CFRunLoopRunSpecific + 572
    frame #5: 0x000000019b8df278 Foundation`-[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 228
    frame #6: 0x000000019b8df158 Foundation`-[NSRunLoop(NSRunLoop) runUntilDate:] + 88
    frame #7: 0x000000019d0469fc UIKitCore`-[UIEventFetcher threadMain] + 504
    frame #8: 0x000000019ba3bc48 Foundation`__NSThread__start__ + 848
    frame #9: 0x00000001e0002b70 libsystem_pthread.dylib`_pthread_start + 288
  thread #24, name = 'MNNetworking'
    frame #0: 0x00000001c4f9f8c4 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #1: 0x00000001c4f9ecc8 libsystem_kernel.dylib`mach_msg + 72
    frame #2: 0x000000019a6db74c CoreFoundation`__CFRunLoopServiceMachPort + 376
    frame #3: 0x000000019a6d5bd0 CoreFoundation`__CFRunLoopRun + 1176
    frame #4: 0x000000019a6d5200 CoreFoundation`CFRunLoopRunSpecific + 572
    frame #5: 0x000000019b8df278 Foundation`-[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 228
    frame #6: 0x000000019b9103e4 Foundation`-[NSRunLoop(NSRunLoop) run] + 88
    frame #7: 0x00000001012195bc xxx`+[MNURLConnectionOperation networkRequestThreadEntryPoint:](self=MNHTTPRequestOperation, _cmd="networkRequestThreadEntryPoint:", object=0x0000000000000000) at MNURLConnectionOperation.m:148:9
    frame #8: 0x000000019ba3bc48 Foundation`__NSThread__start__ + 848
    frame #9: 0x00000001e0002b70 libsystem_pthread.dylib`_pthread_start + 288
  thread #26, name = 'AVAudioSession Notify Thread'
    frame #0: 0x00000001c4f9f8c4 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #1: 0x00000001c4f9ecc8 libsystem_kernel.dylib`mach_msg + 72
    frame #2: 0x000000019a6db74c CoreFoundation`__CFRunLoopServiceMachPort + 376
    frame #3: 0x000000019a6d5bd0 CoreFoundation`__CFRunLoopRun + 1176
    frame #4: 0x000000019a6d5200 CoreFoundation`CFRunLoopRunSpecific + 572
    frame #5: 0x00000001a1bd4158 AudioSession`GenericRunLoopThread::Entry(void*) + 156
    frame #6: 0x00000001a1bd60b8 AudioSession`CAPThread::Entry(CAPThread*) + 88
    frame #7: 0x00000001e0002b70 libsystem_pthread.dylib`_pthread_start + 288
  thread #27
    frame #0: 0x00000001c4fc2c10 libsystem_kernel.dylib`__select + 8
    frame #1: 0x00000001017edd54 xxx`netx_wait + 468
    frame #2: 0x0000000101769cc4 xxx`mmbc__schedule + 80
    frame #3: 0x000000010176b414 xxx`mmbc_thread_routine + 48
    frame #4: 0x00000001e0002b70 libsystem_pthread.dylib`_pthread_start + 288
  thread #32, name = 'com.apple.NSURLConnectionLoader'
    frame #0: 0x00000001c4f9f8c4 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #1: 0x00000001c4f9ecc8 libsystem_kernel.dylib`mach_msg + 72
    frame #2: 0x000000019a6db74c CoreFoundation`__CFRunLoopServiceMachPort + 376
    frame #3: 0x000000019a6d5bd0 CoreFoundation`__CFRunLoopRun + 1176
    frame #4: 0x000000019a6d5200 CoreFoundation`CFRunLoopRunSpecific + 572
    frame #5: 0x000000019af5f9a4 CFNetwork`___lldb_unnamed_symbol11120$$CFNetwork + 552
    frame #6: 0x000000019ba3bc48 Foundation`__NSThread__start__ + 848
    frame #7: 0x00000001e0002b70 libsystem_pthread.dylib`_pthread_start + 288
  thread #52
    frame #0: 0x00000001dfffd8d4 libsystem_pthread.dylib`pthread_mutex_lock$VARIANT$mp + 56
    frame #1: 0x00000001016d46a0 xxx`fhevc_task_run_routine + 44
    frame #2: 0x00000001e0002b70 libsystem_pthread.dylib`_pthread_start + 288
  thread #61, queue = 'com.google.fira.worker'
    frame #0: 0x00000001c4fc4504 libsystem_kernel.dylib`kevent_id + 8
    frame #1: 0x000000010314def8 libdispatch.dylib`_dispatch_kq_poll + 228
    frame #2: 0x000000010314e998 libdispatch.dylib`_dispatch_event_loop_wait_for_ownership + 436
    frame #3: 0x000000010313cb4c libdispatch.dylib`__DISPATCH_WAIT_FOR_QUEUE__ + 308
    frame #4: 0x000000010313c598 libdispatch.dylib`_dispatch_sync_f_slow + 176
    frame #5: 0x0000000101bb5710 xxx`-[APMIdentity resettableDeviceID] + 144
    frame #6: 0x0000000101bf273c xxx`-[APMMeasurement(Event) createRawEventMetadataWithUserAttributes:] + 1908
    frame #7: 0x0000000101bf4b70 xxx`-[APMMeasurement(Event) writeEvent:isPublicEvent:isRealtime:] + 796
    frame #8: 0x0000000101bf1f84 xxx`__49-[APMMeasurement(Event) writeEventOnWorkerQueue:]_block_invoke + 604
    frame #9: 0x0000000101be0300 xxx`-[APMSqliteStore performTransactionWithError:block:] + 176
    frame #10: 0x0000000101ba7f88 xxx`-[APMDatabase performTransaction:] + 48
    frame #11: 0x0000000101bf1c48 xxx`-[APMMeasurement(Event) writeEventOnWorkerQueue:] + 820
    frame #12: 0x0000000101bf17a4 xxx`-[APMMeasurement(Event) handleEventOnWorkerQueue:] + 540
    frame #13: 0x0000000101bbdc1c xxx`-[APMMeasurement logEventOnWorkerQueue:notifyEventListeners:] + 84
    frame #14: 0x0000000101bbdbc4 xxx`-[APMMeasurement logEventOnWorkerQueueWithOrigin:isPublicEvent:name:parameters:timestamp:enabled:ignoreEnabled:ignoreInterceptor:interceptor:addedScreenParameters:] + 708
    frame #15: 0x0000000101bbd8a0 xxx`__151-[APMMeasurement logEventWithOrigin:isPublicEvent:name:parameters:timestamp:enabled:ignoreEnabled:ignoreInterceptor:interceptor:addedScreenParameters:]_block_invoke + 68
    frame #16: 0x0000000101bcb2a0 xxx`__51-[APMScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke + 44
    frame #17: 0x000000010312bdb8 libdispatch.dylib`_dispatch_call_block_and_release + 24
    frame #18: 0x000000010312d5fc libdispatch.dylib`_dispatch_client_callout + 16
    frame #19: 0x0000000103134680 libdispatch.dylib`_dispatch_lane_serial_drain + 748
    frame #20: 0x0000000103135308 libdispatch.dylib`_dispatch_lane_invoke + 452
    frame #21: 0x0000000103140b34 libdispatch.dylib`_dispatch_workloop_worker_thread + 1456
    frame #22: 0x00000001e00045a4 libsystem_pthread.dylib`_pthread_wqthread + 272
  thread #64
    frame #0: 0x00000001dfffd90c libsystem_pthread.dylib`pthread_mutex_lock$VARIANT$mp + 112
    frame #1: 0x00000001016d46a0 xxx`fhevc_task_run_routine + 44
    frame #2: 0x00000001e0002b70 libsystem_pthread.dylib`_pthread_start + 288
  thread #66
    frame #0: 0x00000001dfffd70c libsystem_pthread.dylib`pthread_mutex_unlock$VARIANT$mp + 112
    frame #1: 0x00000001016d4704 xxx`fhevc_task_run_routine + 144
    frame #2: 0x00000001e0002b70 libsystem_pthread.dylib`_pthread_start + 288
  thread #77
    frame #0: 0x00000001c4f9f900 libsystem_kernel.dylib`semaphore_wait_trap + 8
    frame #1: 0x00000001db4e729c caulk`caulk::mach::semaphore::wait_or_error() + 24
    frame #2: 0x00000001db4dc010 caulk`caulk::semaphore::timed_wait(double) + 176
    frame #3: 0x00000001db4e0f24 caulk`caulk::concurrent::details::worker_thread::run() + 40
    frame #4: 0x00000001db4e10bc caulk`void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 56
    frame #5: 0x00000001e0002b70 libsystem_pthread.dylib`_pthread_start + 288
  thread #79
    frame #0: 0x00000001e000786c libsystem_pthread.dylib`start_wqthread
  thread #85, queue = 'APMIdentityWorkerQueue'
    frame #0: 0x00000001c4f9f8c4 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #1: 0x00000001c4f9ecc8 libsystem_kernel.dylib`mach_msg + 72
    frame #2: 0x0000000103146634 libdispatch.dylib`_dispatch_mach_send_and_wait_for_reply + 528
    frame #3: 0x00000001031469c8 libdispatch.dylib`dispatch_mach_send_with_result_and_wait_for_reply + 52
    frame #4: 0x00000001e0023440 libxpc.dylib`xpc_connection_send_message_with_reply_sync + 236
    frame #5: 0x000000019bae5e9c Foundation`__NSXPCCONNECTION_IS_WAITING_FOR_A_SYNCHRONOUS_REPLY__ + 12
    frame #6: 0x000000019b8ea9d4 Foundation`-[NSXPCConnection _sendInvocation:orArguments:count:methodSignature:selector:withProxy:] + 2428
    frame #7: 0x000000019a75e440 CoreFoundation`___forwarding___ + 648
    frame #8: 0x000000019a7606cc CoreFoundation`_CF_forwarding_prep_0 + 92
    frame #9: 0x000000019aa2b708 CoreServices`-[LSApplicationWorkspace deviceIdentifierForAdvertising] + 164
    frame #10: 0x00000001c8da4d00 AdSupport`-[ASIdentifierManager advertisingIdentifier] + 168
    frame #11: 0x0000000101be2a20 xxx`-[APMASIdentifierWrapper resettableDeviceIDStringIfAvailable] + 140
    frame #12: 0x0000000101be2ad4 xxx`-[APMASIdentifierWrapper limitedAdTracking] + 72
    frame #13: 0x0000000101bb6804 xxx`__32-[APMIdentity updateIdentifiers]_block_invoke + 304
    frame #14: 0x000000010312bdb8 libdispatch.dylib`_dispatch_call_block_and_release + 24
    frame #15: 0x000000010312d5fc libdispatch.dylib`_dispatch_client_callout + 16
    frame #16: 0x0000000103134680 libdispatch.dylib`_dispatch_lane_serial_drain + 748
    frame #17: 0x0000000103135308 libdispatch.dylib`_dispatch_lane_invoke + 452
    frame #18: 0x0000000103140b34 libdispatch.dylib`_dispatch_workloop_worker_thread + 1456
    frame #19: 0x00000001e00045a4 libsystem_pthread.dylib`_pthread_wqthread + 272
  thread #87
    frame #0: 0x00000001e000786c libsystem_pthread.dylib`start_wqthread
  thread #88
    frame #0: 0x00000001dfffd8c0 libsystem_pthread.dylib`pthread_mutex_lock$VARIANT$mp + 36
    frame #1: 0x00000001016d46a0 xxx`fhevc_task_run_routine + 44
    frame #2: 0x00000001e0002b70 libsystem_pthread.dylib`_pthread_start + 288
  thread #89
    frame #0: 0x00000001c4fc2d00 libsystem_kernel.dylib`__semwait_signal + 8
    frame #1: 0x00000001a33a3714 libsystem_c.dylib`nanosleep + 212
    frame #2: 0x00000001a33a35ec libsystem_c.dylib`usleep + 64
    frame #3: 0x00000001017edef4 xxx`netx_wait + 884
    frame #4: 0x000000010179e3a0 xxx`rtmp_wait + 96
    frame #5: 0x00000001016f16c4 xxx`frtmp_thread_factory + 44
    frame #6: 0x00000001e0002b70 libsystem_pthread.dylib`_pthread_start + 288
  thread #90
    frame #0: 0x00000001c4fc2c10 libsystem_kernel.dylib`__select + 8
    frame #1: 0x00000001017edd54 xxx`netx_wait + 468
    frame #2: 0x0000000101733948 xxx`p2pex__schedule + 156
    frame #3: 0x000000010174d254 xxx`p2pex_schedule + 104
    frame #4: 0x00000001016e3ad0 xxx`frtdp_thread_factory + 68
    frame #5: 0x00000001e0002b70 libsystem_pthread.dylib`_pthread_start + 288
  thread #91
    frame #0: 0x00000001c4fc272c libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001dfffc330 libsystem_pthread.dylib`_pthread_cond_wait$VARIANT$mp + 1180
    frame #2: 0x000000010181157c xxx`mosal_unix_event_wait + 152
    frame #3: 0x00000001017e290c xxx`mevent_wait + 44
    frame #4: 0x0000000101705c0c xxx`aud_mixer_get_frame + 696
    frame #5: 0x00000001016b096c xxx`mec_aud_play_routine + 188
    frame #6: 0x00000001e0002b70 libsystem_pthread.dylib`_pthread_start + 288
  thread #92
    frame #0: 0x00000001c4fc2d00 libsystem_kernel.dylib`__semwait_signal + 8
    frame #1: 0x00000001a33a3714 libsystem_c.dylib`nanosleep + 212
    frame #2: 0x00000001a33a35ec libsystem_c.dylib`usleep + 64
    frame #3: 0x00000001017c86a4 xxx`media__sample_queue_run + 356
    frame #4: 0x00000001017c84e4 xxx`media_istream_sample_queue_thread_routine + 88
    frame #5: 0x00000001e0002b70 libsystem_pthread.dylib`_pthread_start + 288
  thread #93
    frame #0: 0x00000001c4fc2d00 libsystem_kernel.dylib`__semwait_signal + 8
    frame #1: 0x00000001a33a3714 libsystem_c.dylib`nanosleep + 212
    frame #2: 0x00000001a33a35ec libsystem_c.dylib`usleep + 64
    frame #3: 0x00000001017c86a4 xxx`media__sample_queue_run + 356
    frame #4: 0x00000001017c84e4 xxx`media_istream_sample_queue_thread_routine + 88
    frame #5: 0x00000001e0002b70 libsystem_pthread.dylib`_pthread_start + 288
  thread #94
    frame #0: 0x00000001c4fc272c libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001dfffc330 libsystem_pthread.dylib`_pthread_cond_wait$VARIANT$mp + 1180
    frame #2: 0x000000010181157c xxx`mosal_unix_event_wait + 152
    frame #3: 0x00000001017e290c xxx`mevent_wait + 44
    frame #4: 0x00000001017c8764 xxx`media__sample_queue_run + 548
    frame #5: 0x00000001017c84e4 xxx`media_istream_sample_queue_thread_routine + 88
    frame #6: 0x00000001e0002b70 libsystem_pthread.dylib`_pthread_start + 288
  thread #95
    frame #0: 0x00000001c4fc272c libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001dfffc330 libsystem_pthread.dylib`_pthread_cond_wait$VARIANT$mp + 1180
    frame #2: 0x000000010181157c xxx`mosal_unix_event_wait + 152
    frame #3: 0x00000001017e290c xxx`mevent_wait + 44
    frame #4: 0x00000001017c8764 xxx`media__sample_queue_run + 548
    frame #5: 0x00000001017c84e4 xxx`media_istream_sample_queue_thread_routine + 88
    frame #6: 0x00000001e0002b70 libsystem_pthread.dylib`_pthread_start + 288
  thread #96, queue = 'com.apple.runningboardservices.callout-workloop'
    frame #0: 0x00000001c4fc1418 libsystem_kernel.dylib`__bsdthread_ctl + 8
    frame #1: 0x00000001e0005ff4 libsystem_pthread.dylib`_pthread_set_properties_self + 120
    frame #2: 0x000000010312f294 libdispatch.dylib`_dispatch_set_priority_and_mach_voucher_slow + 160
    frame #3: 0x000000010312f424 libdispatch.dylib`_dispatch_set_priority_and_voucher_slow + 200
    frame #4: 0x0000000103136a34 libdispatch.dylib`_dispatch_workloop_invoke + 2832
    frame #5: 0x0000000103140b34 libdispatch.dylib`_dispatch_workloop_worker_thread + 1456
    frame #6: 0x00000001e00045a4 libsystem_pthread.dylib`_pthread_wqthread + 272
  thread #99
    frame #0: 0x00000001e000786c libsystem_pthread.dylib`start_wqthread
  thread #100
    frame #0: 0x00000001e000786c libsystem_pthread.dylib`start_wqthread
  thread #101, queue = 'com.apple.root.default-qos'
    frame #0: 0x00000001c4fc33a0 libsystem_kernel.dylib`__ulock_wait + 8
    frame #1: 0x000000010312e0a0 libdispatch.dylib`_dlock_wait + 52
    frame #2: 0x000000010312e41c libdispatch.dylib`_dispatch_group_wait_slow + 56
    frame #3: 0x0000000101d50e54 xxx`___lldb_unnamed_symbol4196$$xxx + 32
    frame #4: 0x0000000101d5cb00 xxx`___lldb_unnamed_symbol4422$$xxx + 436
    frame #5: 0x0000000101d64fe4 xxx`___lldb_unnamed_symbol4568$$xxx + 160
    frame #6: 0x000000010312bdb8 libdispatch.dylib`_dispatch_call_block_and_release + 24
    frame #7: 0x000000010312d5fc libdispatch.dylib`_dispatch_client_callout + 16
    frame #8: 0x000000010312fd98 libdispatch.dylib`_dispatch_queue_override_invoke + 888
    frame #9: 0x000000010313f120 libdispatch.dylib`_dispatch_root_queue_drain + 376
    frame #10: 0x000000010313fa48 libdispatch.dylib`_dispatch_worker_thread2 + 152
    frame #11: 0x00000001e0004568 libsystem_pthread.dylib`_pthread_wqthread + 212
  thread #102
    frame #0: 0x00000001e000786c libsystem_pthread.dylib`start_wqthread
  thread #103
    frame #0: 0x00000001c4fc3350 libsystem_kernel.dylib`__thread_selfid + 8
    frame #1: 0x00000001e0004728 libsystem_pthread.dylib`_pthread_wqthread_setup + 236
    frame #2: 0x00000001e00044c4 libsystem_pthread.dylib`_pthread_wqthread + 48

**Comment by morganchen12** [comment]
This is unrelated to SSL and is the same issue as #6392.

**Comment by morganchen12** [comment]
Marking it as a duplicate #6392, please continue discussion in the linked issue.
