### ISSUE TITLE
When the FirebaseUI will update the linked FBSDKLoginKit version to 8.0 ?

### ISSUE THREAD

**Issue by fangyuxi** [firebase/firebase-ios-sdk#7308]
### Step 1: Are you in the right place?

FirebaseUI

### Step 2: Describe your environment

  * Objective C or Swift: Objective C
  * iOS version: 14.2
  * Firebase SDK version:7.4.0
  * FirebaseUI version: 9.0.0
  
### Step 3: Describe the problem:

Now FirebaseUI Linked to FBSDKLoginKit version is 7.0
But the FBSDKLoginKit SDK 8.2.0 has been released for a long time

Due to the iOS 14 privacy policy, Facebook has made adjustments in their latest SDK (8.2.0). Now that we are using FirebaseUI, we cannot upgrade the Facebook SDK to the latest version.

So When the FirebaseUI will update the linked FBSDKLoginKit version to 8.0 ?

- FirebaseUI/Facebook (9.0.0):
    - FBSDKLoginKit (~> 7.0)

**Comment by fangyuxi** [comment]
Duplicate of #7308

**Comment by fangyuxi** [comment]
https://github.com/firebase/FirebaseUI-iOS/issues/931

**Comment by paulb777** [comment]
Closing in favor off firebase/FirebaseUI-iOS#931 cc: @morganchen12
