### ISSUE TITLE
Deadlock caused by call to objc_copyImageNames in FIRPopulateProtoWithNumberOfLinkedFrameworks

### ISSUE THREAD

**Issue by SquaredTiki** [firebase/firebase-ios-sdk#7310]
### Environment

  * Xcode version: 12.1
  * Firebase SDK version: 6.34.0
  * Installation method: `CocoaPods` (select one)
  * Firebase Component: Crashlytics

### Problem

Firebase's call to `objc_copyImageNames` within `FIRPopulateProtoWithNumberOfLinkedFrameworks` can sometimes trigger a deadlock on launch (if another thread is performing a `dlopen`, e.g. CFNetwork) resulting in the app being terminated by the system watchdog. This has been filed as a bug report with Apple (FB8971497) and discussed on the developer forums [here ](https://developer.apple.com/forums/thread/671497?answerId=657367022&page=1#657354022) however it's worth raising here as well to see if there's any workarounds.

Is it possible to disable diagnostics including the number of linked frameworks to remove the call to `objc_copyImageNames`? 

#### Steps to reproduce:

In an app that makes a network request at launch, with a reasonable number of dynamic libraries linked (~5+), it may trigger a deadlock (timing dependant) resulting in the app being terminated by the system watchdog. Crash report can be found [here](https://gist.github.com/SquaredTiki/11a58e6837029e44da6098b34486658d).

**Comment by ryanwilson** [comment]
Thanks for the report and sorry for the issue. It looks like the right approach here is to just remove this as it's not needed anymore. I'll put a PR shortly for it.
