### ISSUE TITLE
177930107: Dynamic links trowing error 

### ISSUE THREAD

**Issue by VladislavShergin** [firebase/firebase-ios-sdk#7318]
### Step 1: Environment details

  * Xcode version: 12.3 （12C33）
  * Firebase SDK version: - Firebase/Analytics (7.4.0):    - Firebase/Core  - Firebase/Auth (7.4.0):    - Firebase/CoreOnly    - FirebaseAuth (~> 7.4.0) - Firebase/Core (7.4.0):   - Firebase/CoreOnly   - FirebaseAnalytics (= 7.4.0)
  * Installation method: `CocoaPods
  * Firebase Component: Dinamic Links

### [REQUIRED] Step 2: Problem details
There is an error appearing with the text: Thread 1: EXC_BAD_ACCESS (code-1, address=0x40925bac0) after integrating the Google Dinamic links into our project. We've tried different versions of Dinamic Links SDK, for example: v.7.4.0, 7.3.1, 4.0.0, 3.1.1, they are all showing the same error.

We've also tried to switch the FirebaseDeepLinkAutomaticRetrievalEnabled parameter to NO, after that the error is not appearing, however the feature stop work after that.

Screenshot attached:
![image](https://user-images.githubusercontent.com/47073046/104891082-6db83300-59ab-11eb-9a0e-2d9f31812532.png)

NOTE: The same problem has been opened in the link https://github.com/firebase/firebase-ios-sdk/issues/3945 before, however no-one resolved it after, due to the lack of the details the issue were closed.

**Comment by ryanwilson** [comment]
Hi @VladislavShergin - sorry for the troubles you're seeing.

Do you have a set of steps that can be used to reproduce this? Does it reproduce in the Quickstart, or only in your project? Hopefully we'll be able to reproduce this and track it down this time. 

Also is this happening in the simulator or on device? Any particular iOS version?

Thanks!

**Comment by VladislavShergin** [comment]
Hi Ryan, first of all thank you very much for quick respond.

1 The exact reproducing steps are simple, we used Cocoa to integrate FirebaseDynamicLinks, right after it we press on RUN and it shows Thread and Crashing, project cannot proceed at this step.

2 This happening right in the Xcode with connected Simulator Device and Real Phone, both cases are showing this thread.

Additional info: We've found out other people have this problem also, and we found out that if we disable FirebaseDeepLinkAutomaticRetrievalEnabled with a value NO to the Info.plist the error is disappearing, unfortunately the whole feature stops working. The link for this method is https://github.com/firebase/firebase-ios-sdk/issues/4308

Screenshot:
![image](https://user-images.githubusercontent.com/47073046/104976173-8e2dcf00-5a37-11eb-8490-8dd142018443.png)

3 We would like to know for which features FirebaseDeepLinkAutomaticRetrievalEnabled is responsible exactly, it seems after we disable it it do not pass any data for Firebase. And there is no any additional information or guide to get whole explanation for this online.

Hope you can help us with this problem, it is very important for us to have this feature in our application.

**Comment by VladislavShergin** [comment]
Dear Ryan, we also have additional question.

The main reason we've integrated Google Dynamic links is to get Source/Medium for tracking orders through the dynamic link. We would like to saw conversion of each order with Source/Medium in Google Analytics associated project. The project is directly connected to ur Firebase.

We've integrated Dynamic links in Android and it works perfectly, example screenshot:
![image](https://user-images.githubusercontent.com/47073046/105018373-d96bd000-5a7f-11eb-853a-ce3a75056807.png)
And for the IOS we did the same, but data of the source and medium is not showing in any case, example screenshot:
![image](https://user-images.githubusercontent.com/47073046/105018418-eb4d7300-5a7f-11eb-8db5-05f98caf659e.png)
As you can see from a screenshot for IOS, and as a result the source showing as (direct), we've followed all procedure explained on official site and youtube guide.

Our main goal is not to resolve a Thread for SDK, but to have the main source and medium regarding to the order in GA - conversions.

Please tell us is there any way to check or trace the medium/source for dynamic links or is there is something what we did wrong while implementing the feature.

Thank you.

**Comment by morganchen12** [comment]
@VladislavShergin can you share a full stack trace and try to reproduce this crash in the [quickstart](https://github.com/firebase/quickstart-ios/tree/master/dynamiclinks)?

**Comment by eldhosembabu** [comment]
I've tried in [firebase-quick-start app](https://github.com/firebase/quickstart-ios/tree/master/dynamiclinks) and was not able to reproduce this issue. 

Could you please try to reproduce this issue in our quick start app and let us know?

**Comment by Heidan34** [comment]
I have a similar issue, same kind of exception but on the line 79 `  _wkWebView = [[WKWebView alloc] init];` of the file FIRDLJavaScriptExecutor.m.

This issue only happens when I compile with Xcode 12 for an iOS 11.X simulator. It works properly with an iOS 14.X simulator.

@VladislavShergin are you using an M1 mac ? Just tried on an Intel based mac and can't seem to reproduce.

**Comment by VladislavShergin** [comment]
Hi everyone, thank you very much for your respond. @Heidan34 @eldhosembabu @ryanwilson We found out that Dynamic Links SDK is conflicting with NewRelic's SDK, the NewRelic has a script file which blocks the Dynamic Links code and creating this issue. After we disable NewRelic the issue resolved, however In our situation we really need to use both NewRelic and Dynamic Links.

**Comment by VladislavShergin** [comment]
I would like to emphasize after we disable the NewRelic the issue was not found, however we are having a new issue, we cannot get source/medium regarding to the conversion in Google Analytics. I've created a separate issue linked here: https://github.com/firebase/firebase-ios-sdk/issues/7336

**Comment by mobee-bill** [comment]
@VladislavShergin Wow awesome I spent a few hours today trying to figure this out and ended up working around it by commenting out the problem lines in the podfile.  Using NewRelic in my project as well.

**Comment by asowers1** [comment]
I am seeing the exact same scenario as @Claes34, and I'm on M1. Any suggestions on how to resolve this?

**Comment by Claes34** [comment]
@asowers1 unfortunatly this is a bug known to Apple that impact old simulators only. Apple should fix this someday... Keep big sur and xcode updated until it is

**Comment by nmalancea** [comment]
I've also encountered this and had to comment out line 121 in `FIRDLJavaScriptExecutor.m`.

![image](https://user-images.githubusercontent.com/3107683/126484412-f5503c00-a1cd-49e6-9c62-befb5007924b.png)

**Comment by tuliot** [comment]
I've been having this same issue for weeks as well, and it's held us from releasing an implementation of DynamicLinks because we also absolutely need NewRelic. 

We are using
```
pod 'Firebase/DynamicLinks', '~> 8.1'
pod 'NewRelicAgent', '7.3.2'
```

> I tried adding the `FirebaseDeepLinkAutomaticRetrievalEnabled = NO` but even though this did prevent the crash, it also prevented the DynamicLinks from opening.


## The solution that worked for us
Believe it or not, placing the `NewRelic.start()` call at the very top of `didFinishLaunchingWithOptions` made it work for me. It seems that somehow NewRelic and Firebase are competing for resources and NewRelic being initialized first makes them both work well. 

### This breaks
```swift
FirebaseApp.configure()
NewRelic.start("key")
```

### This works
```swift
NewRelic.start("key")
FirebaseApp.configure()
```



Ironically, the NewRelic setup guide *does* warn that we absolutely must place their init code in the first line of `didFinishLaunchingWithOptions` unless we want bad things to happen. Apparently these are the bad things?

![image](https://user-images.githubusercontent.com/5385681/126598950-d13dab43-2396-4eba-a758-693b1b026a86.png)


If you try this, i'd love to know if it works for you


@nmalancea tagging you because you seem to still be running into this!

**Comment by lucasecf** [comment]
Just to share that I had the same issue/crash when adding the `Firebase/DynamicLinks` through Cocoapods, and the above suggestion about initialising the `NewRelic` Before `Firebase` fixes the issue 🤷‍♂️

**Comment by bogdan-razvan** [comment]
I can confirm this change fixes the issue. I had the same crash, where DynamicLinks conflicted with NewRelic

**Comment by paulb777** [comment]
The Firebase Dynamic Links service will be shutdown on August 25, 2025.  In the meantime, only critical or security issues will be fixed in the SDK.

More at https://firebase.google.com/support/dynamic-links-faq

**Comment by daxfrost** [comment]
Hi there,

I understand [this is a good fix](https://github.com/firebase/firebase-ios-sdk/issues/7318#issuecomment-884689527) if the native layer is firing the call.

Considering the [latest documentation](https://docs.newrelic.com/docs/mobile-monitoring/new-relic-monitoring-react-native/monitor-your-react-native-application/) shows `NewRelic.startAgent(appToken,agentConfiguration);` and is done on the JS layer, how can we control the timing of this effectively?
