### ISSUE TITLE
Dynamic link Source in Conversions for iOS is always unset or (direct). Dynamic link Source/Medium doesn't work on IOS, but works on Android.

### ISSUE THREAD

**Issue by VladislavShergin** [firebase/firebase-ios-sdk#7336]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.3 （12C33）
  * Firebase SDK version: - Firebase/Analytics (7.4.0): - Firebase/Core - Firebase/Auth (7.4.0): - Firebase/CoreOnly - FirebaseAuth (~> 7.4.0) - Firebase/Core (7.4.0): - Firebase/CoreOnly - FirebaseAnalytics (= 7.4.0)
  * Installation method: `CocoaPods
  * Firebase Component: Dinamic Links, Analitycs

### [REQUIRED] Step 2: Describe the problem
We've been using Google Analytics for a long time, 2 month ago we've started to implement Dynamic Links for tracking Source and Medium for our orders in Google Analytics through the dynamic link. We would like to saw our conversion of each order with Source/Medium in Google Analytics's associated project. The project is directly connected to ur Firebase.

We've integrated Dynamic links in Android and it works perfectly, example screenshot:
![105018373-d96bd000-5a7f-11eb-853a-ce3a75056807](https://user-images.githubusercontent.com/47073046/105271498-8ce4d980-5bd2-11eb-9cf2-1d3e68871ed0.jpg)
And for the IOS we did the same, but data of the source and medium is not showing in any case, example screenshot:
![105018418-eb4d7300-5a7f-11eb-8db5-05f98caf659e](https://user-images.githubusercontent.com/47073046/105270030-03340c80-5bd0-11eb-8fbd-890254899fa8.jpg)
We've setup and debug all possible variations we can find in the internet however it doesn't work.
![image](https://user-images.githubusercontent.com/47073046/105268403-23ae9780-5bcd-11eb-8ca1-72d76dbcdefa.png)
The conversions for the dynamic link event is open:
![image](https://user-images.githubusercontent.com/47073046/105269013-1fcf4500-5bce-11eb-9107-1c0efe1fc7e7.png)
The ecommerce_purchase event we use for the conversion is also setup properly:
![image](https://user-images.githubusercontent.com/47073046/105269162-5dcc6900-5bce-11eb-9fdd-aad81599cbdf.png)
As you can see from a screenshot for IOS, and as a result the source showing as (direct), we've followed all procedure explained on official site and youtube guide.
#### Steps to reproduce:
The setup was done the same as for Android, the only difference is we used the way to integrate IOS SDK according to the IOS  Guide.

We've found there are at least 4 people posted this problem on Github and other sources, however no-one is resolving it and case closed. The example we found is: https://github.com/firebase/firebase-ios-sdk/issues/4132

Hope we can resolve this problem ASAP,
Thank you

**Comment by VladislavShergin** [comment]
Hi everyone, I am adding some additional info regarding to this case.

I would like to show that we setup deep link correctly, the data from deep link is coming to the firebase, however it is not showing in the conversions connected to the order. The same data is coming for android, and it is not working for IOS.

Dynamic link app open - source
![image](https://user-images.githubusercontent.com/47073046/105433332-5ec7ce00-5c94-11eb-9e63-bb355a82c5a7.png)
Dynamic link app open - medium
![image](https://user-images.githubusercontent.com/47073046/105433359-68513600-5c94-11eb-8c14-e3be138fbd46.png)
The same event triggered in the debug mode, we can see source/medium parameters for the dynamic link.

**Comment by riverRoad** [comment]
i have the same issue

**Comment by paulb777** [comment]
Closing for staleness. Please comment or open a new issue to reopen.
