### ISSUE TITLE
Year and Copyright Owner values not supplied in LICENSE file

### ISSUE THREAD

**Issue by richardsimkins** [firebase/firebase-ios-sdk#7340]
In the file:
https://github.com/firebase/firebase-ios-sdk/blob/master/LICENSE

There is the line:
`Copyright [yyyy] [name of copyright owner]`

Previously this had been filled in as:
`Copyright 2020 Firebase, Inc.`

This issue is also present in the android repo:
https://github.com/firebase/firebase-android-sdk/blob/master/LICENSE

**Comment by paulb777** [comment]
Thanks for the report. However, this is the intended behavior. See #7105 for the explanation.
