### ISSUE TITLE
FR: Less dependencies, Please!

### ISSUE THREAD

**Issue by rawandahmad698** [firebase/firebase-ios-sdk#7353]
### Feature proposal

* Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)

Describe your use case and/or feature request here.

Why do i have to install over 16+ dependencies for **just** two firebase features? It eats up space, ram, build time. Firebase really needs to work on this: 

Podfile: 

 

- pod 'Firebase/Firestore'
- pod 'Firebase/Analytics'

And ** pod install **: 

- Installing BoringSSL-GRPC (0.0.7)
- Installing Firebase (7.3.0)
- Installing FirebaseAnalytics (7.3.0)
- Installing FirebaseCore (7.3.0)
- Installing FirebaseCoreDiagnostics (7.3.0)
- Installing FirebaseFirestore (7.3.0)
- Installing FirebaseInstallations (7.3.0)
- Installing GoogleAppMeasurement (7.3.0)
- Installing GoogleDataTransport (8.1.0)
- Installing GoogleUtilities (7.1.1)
- Installing PromisesObjC (1.2.12)
- Installing abseil (0.20200225.0)
- Installing gRPC-C++ (1.28.2)
- Installing gRPC-Core (1.28.2)
- Installing leveldb-library (1.22)
- Installing nanopb (2.30906.0)

**Comment by paulb777** [comment]
Actually the number of dependencies allows Firebase to be smaller and faster. Architecting the library structure with smaller, more granular components allows the installation of exactly what is needed to support any subset of the available top-level feature libraries.  See the related discussion at #6345

**Comment by wilhuff** [comment]
There really isn't anything in here to cut, unfortunately, especially when you consider that we need to maintain compatibility with data that's on existing users' devices. None of these dependencies are optional--they're all providing critical features of these SDKs.
