### ISSUE TITLE
adding `firebase-ios-sdk` to Xcode Swift Packages, as well as depending on it in a local Swift Package causes packages to fail to resolve consistently.

### ISSUE THREAD

**Issue by jondwillis** [firebase/firebase-ios-sdk#7363]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.3
  * Firebase SDK version: 7.4.0 (also affects at least 7.3.x)
  * Installation method: `Swift Package Manager`
  * Firebase Component: Analytics, FirebaseCrashlytics, perhaps all.

#### Steps to reproduce:

_(See example project linked at the bottom)_

adding `firebase-ios-sdk` to Xcode Swift Packages, as well as depending on it in a local Swift Package causes packages to fail to resolve consistently.

#### The Results:

![firebase-ios-sdk displays as greyed out](https://user-images.githubusercontent.com/906671/105614568-3d500a80-5d98-11eb-967b-5b82a2aa0466.png)
![the underlying error](https://user-images.githubusercontent.com/906671/105614574-45a84580-5d98-11eb-894e-ebfd2ea0f276.png)

```
artifact of binary target 'FirebaseAnalytics' failed extraction: The operation couldn’t be completed. (TSCBasic.StringError error 1.)
artifact of binary target 'GoogleAppMeasurement' failed extraction: The operation couldn’t be completed. (TSCBasic.StringError error 1.)
```

#### The (Workaround) Solution:

Some combination of closing Xcode, Resetting Package Cache, and Updating Package Dependencies can resolve it temporarily.

#### Relevant Code:
https://github.com/jondwillis/FirebaseSPMBug

**Comment by paulb777** [comment]
Thanks for the report.

It's almost certainly a Swift Package Manager bug and I recommend reporting there also. It looks similar to https://forums.swift.org/t/problem-in-xcode-project-to-get-all-dependencies/42287.

**Comment by jondwillis** [comment]
@paulb777 Thanks, I agree. I added to the thread that you linked to. Overall the SPM<>Xcode integration seems quite buggy.

**Comment by paulb777** [comment]
Thanks @jondwillis. I would add the distinction about SPM <> Xcode integration bugginess specifically for binary packages.  The source package integration has been more stable.

**Comment by paulb777** [comment]
@jondwillis Does Xcode 12.5 address this?

**Comment by jondwillis** [comment]
@paulb777 ...sort of! ... with some changes, thanks to improved Xcode-SPM error messaging.

For context, this was my local swift package's Package.swift:

```
    dependencies: [
        .package(url: "https://github.com/Quick/Quick.git", from: "3.0.0"),
        .package(url: "https://github.com/Quick/Nimble.git", from: "9.0.0"),
        .package(url: "https://github.com/firebase/firebase-ios-sdk", from: "7.4.0"),
    ],
    targets: [
        .target(
            name: "Analytics",
            dependencies: [
                .product(name: "FirebaseAnalytics", package: "Firebase"),
                .product(name: "FirebaseCrashlytics", package: "Firebase"),
            ]),
            ...
```

Without any changes to my example project in Xcode 12.5 beta, I received the following error when resolving packages:

```
unknown package 'Firebase' in dependencies of target 'Analytics'; valid packages are: 'Quick', 'Nimble', 'firebase-ios-sdk'
```

I decided to bump to version to 7.6.0 at this time, and remove the firebase dependency from my project's Swift packages. Then I tried changing the local dependency's dependencies package name to `firebase-ios-sdk`, e.g.:

```
..product(name: "FirebaseCrashlytics", package: "firebase-ios-sdk"),
```

Which allowed the dependency's dependency to resolve. However, when re-adding Firebase to my project's Swift package, I got another error:

```
product dependency 'FirebaseAnalytics' in package 'firebase-ios-sdk' not found
```

Seems circular! That then led me to the solution, removing the project's Firebase dependency again, then adding an explicit name to my local dependency's product dependencies, and re-adding my projects Firebase dependency (including in case the order here matters):


```
dependencies: [
        .package(url: "https://github.com/Quick/Quick.git", from: "3.0.0"),
        .package(url: "https://github.com/Quick/Nimble.git", from: "9.0.0"),
        .package(name: "Firebase", url: "https://github.com/firebase/firebase-ios-sdk", from: "7.6.0"),
    ],
    targets: [
        .target(
            name: "Analytics",
            dependencies: [
                .product(name: "FirebaseAnalytics", package: "Firebase"),
                .product(name: "FirebaseCrashlytics", package: "Firebase"),
            ]),

```

[I updated my test project repo ](https://github.com/jondwillis/FirebaseSPMBug/commit/06f4789d7df2de1a86f5162f336f7025ad79290a) with the working solution. 

⚠️ for future people, I did notice while going back and replaying these steps, the previous broken behavior appeared again unexpectedly, so maybe this needs to all happen in a really specific order, or can still occur transiently.

**Comment by paulb777** [comment]
@jondwillis Thanks for sharing your journey and solution. I'm going to close since the sporadic functionality is almost certainly a Swift Package Manager and not specifically the Firebase implementation.
