### ISSUE TITLE
First_open event missing.

### ISSUE THREAD

**Issue by seanLee** [firebase/firebase-ios-sdk#7370]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 12.3
  * Firebase SDK version: 7.3.0
  * Installation method: CocoaPods
  * Firebase Component: 
```-> Using FacebookSDK (7.1.1)

-> Using Firebase (7.3.0)

-> Using FirebaseABTesting (7.4.0)

-> Using FirebaseAnalytics (7.3.0)

-> Using FirebaseAuth (7.3.0)

-> Using FirebaseCore (7.3.0)

-> Using FirebaseCoreDiagnostics (7.3.0)

-> Using FirebaseCrashlytics (7.3.0)

-> Using FirebaseDynamicLinks (7.3.1)

-> Using FirebaseInAppMessaging (7.3.0-beta)

-> Using FirebaseInstallations (7.4.0)

-> Using FirebaseInstanceID (7.4.0)

-> Using FirebaseMessaging (7.3.0)

-> Using FirebasePerformance (7.3.0)

-> Using FirebaseRemoteConfig (7.4.0)

-> Using FirebaseUI (9.0.0)
```

#### Steps to reproduce:
Our marketing workmates found that the first_open event missing after we update firebase from ```6.34.0``` to ```7.3.0```.

**Comment by seanLee** [comment]
t he

**Comment by allenktv** [comment]
Thanks for the issue @seanLee. Do you have debug logs from a fresh install/startup that show the first_open event isn't firing?
