### ISSUE TITLE
Stuck at Firebase Crashlytic verification loading...

### ISSUE THREAD

**Issue by Blurzschyter** [firebase/firebase-ios-sdk#7378]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.2
  * Firebase SDK version: 6.34
  * Installation method: CocoaPods
  * Firebase Component: Crashlytics

### [REQUIRED] Step 2: Describe the problem

In my new project, i have successfully setup Firebase Crashlytic and placed the testing crash "fatalError()" in the button action. However after do all the necessary step, when I go back to Firebase Crashlytic console page and it still loading the verification process. I also wait for after 30 minutes, and the page still appear to be same(nothing change).

<img width="439" alt="Screenshot 2021-01-26 at 10 43 36 AM" src="https://user-images.githubusercontent.com/23515008/105793649-7a004980-5fc4-11eb-8fe8-bccbb0e84094.png">

When i check the xcode log, it seem the crashlytic setup was successful.

![crashlytic ss](https://user-images.githubusercontent.com/23515008/105795218-66a2ad80-5fc7-11eb-9169-969d75915b52.png)

Appreciate anyone help on this matter. Thank you ^_^

#### Steps to reproduce:

Here is my podfile setup:-
  pod 'Firebase/Analytics', '~> 6.34.0'
  pod 'Firebase/Crashlytics'

**Comment by morganchen12** [comment]
Hey @Blurzschyter, please file this issue at [Firebase Support](https://firebase.google.com/support). They'll be able to look at the state of your project and tell you why it's stuck.
