### ISSUE TITLE
Migrate unit tests to use CocoaPods test spec feature

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#740]
See https://guides.cocoapods.org/using/test-specs.html

Then consider removing xcodeproj's from git

**Comment by paulb777** [comment]
Started in #1864. Blocked on CocoaPods 1.6.x static framework support for test specs. Will continue once 1.6.x is official

**Comment by morganchen12** [comment]
@paulb777 this is completed now, right?

**Comment by paulb777** [comment]
Mostly, but still needs to be done for InAppMessaging and maybe Firestore.

**Comment by paulb777** [comment]
Also need to migrate coverage from the xcode projects to the `pod gen` projects.

**Comment by paulb777** [comment]
Closing, leaving for InAppMessaging and Firestore to do when ready and appropriate. Everything else is done.
