### ISSUE TITLE
Anonymous sign-in failing on macOS Catalyst app (FIRAuthErrorDomain Code=17995)

### ISSUE THREAD

**Issue by matthewwilson** [firebase/firebase-ios-sdk#7408]
### Step 1: Describe your environment

  * Xcode version: Version 12.4 (12D4e)
  * Firebase SDK version: 7.5.0
  * Installation method: CocoaPods
  * Firebase Component: Auth

### Step 2: Describe the problem

We have a cross platform iOS and macOS (Catalyst) app with the following code that gets called when a button is tapped.

```
Auth.auth().signInAnonymously() { (authResult, error) in
    ...
}
```

On iOS our `authResult` is fine and we can get the information out of it that we need. But on macOS we get a nil `authResult` and the error contains `FIRAuthErrorDomain Code=17995`

We have tried on a few different machines and also tried archiving the build but we are constantly getting the same error.

**Comment by ryanwilson** [comment]
Thanks for the report. To save folks some searching: this is a keychain error.

https://github.com/firebase/firebase-ios-sdk/blob/289e093f89f5dd4ba44377cf57dbf6062e8354c3/FirebaseAuth/Sources/Public/FirebaseAuth/FIRAuthErrors.h#L419

Did a keychain login ever pop up, and was it rejected?

**Comment by matthewwilson** [comment]
We haven't had any popups, but we have managed to solve the issue by adding this entitlement:

![Screenshot 2021-02-01 at 14 40 21](https://user-images.githubusercontent.com/7092887/106473319-8fc9af00-649b-11eb-8cae-240c4e8e4c86.png)

And then adding the keychain group with the default value

**Comment by paulb777** [comment]
It's documented at https://github.com/firebase/firebase-ios-sdk#additional-catalyst-notes

**Comment by matthewwilson** [comment]
My bad! Will close this issue!

**Comment by ryanwilson** [comment]
Thanks Paul! Makes me wonder if we should have an extra warning log for Catalyst apps that have keychain errors somewhere like this: 
https://github.com/firebase/firebase-ios-sdk/blob/e7b32af7feb99a7797efb6f08d18f7d79f488fa5/FirebaseAuth/Sources/Utilities/FIRAuthErrorUtils.m#L1379
