### ISSUE TITLE
[[NSProcessInfo isiOSAppOnMac] crash #6969 ] reproduces on 14.0 beta(18A5301v)

### ISSUE THREAD

**Issue by tianwwMT** [firebase/firebase-ios-sdk#7413]
[[NSProcessInfo isiOSAppOnMac] crash #6969 ](https://github.com/firebase/firebase-ios-sdk/issues/6969)
This crash still reproduces on 14.0 beta(18A5301v) after we updated GoogleUtilities to 7.2.0.
Will it be fixed on 14.0 beta(18A5301v)?

**Comment by paulb777** [comment]
I've confirmed that the fix is still in the 7.2.0 release. 

Please share the installation and if CocoaPods, the Podfile.lock. Also, please share the backtrace of the crash.

**Comment by tianwwMT** [comment]
> I've confirmed that the fix is still in the 7.2.0 release.
> 
> Please share the installation type and if CocoaPods, the Podfile.lock. Also, please share the backtrace of the crash.

Yes, the fix is in the 7.2.0 release indeed, I checked the code inside  Pods/GoogleUtilities/GoogleUtilities/Environment/third_party/GULAppEnvironmentUtil.m.

Here is the Podfile.lock and backstrace. I'm not sure what is the "installation type".
### Podfile.lock
PODS:
  - AppLovinMediationByteDanceAdapter (3.2.6.2.0):
    - AppLovinSDK
    - Bytedance-UnionAD (= 3.2.6.2)
  - AppLovinMediationFacebookAdapter (5.9.0.0):
    - AppLovinSDK
    - FBAudienceNetwork (= 5.9.0)
  - AppLovinMediationGoogleAdapter (7.69.0.1):
    - AppLovinSDK
    - Google-Mobile-Ads-SDK (= 7.69.0)
  - AppLovinMediationUnityAdsAdapter (3.4.8.3):
    - AppLovinSDK
    - UnityAds (= 3.4.8)
  - AppLovinSDK (6.14.3)
  - Bytedance-UnionAD (3.2.6.2)
  - FBAudienceNetwork (5.9.0):
    - FBSDKCoreKit/Basics (>= 5.6.0)
  - FBSDKCoreKit (8.2.0):
    - FBSDKCoreKit/Basics (= 8.2.0)
    - FBSDKCoreKit/Core (= 8.2.0)
  - FBSDKCoreKit/Basics (8.2.0)
  - FBSDKCoreKit/Core (8.2.0):
    - FBSDKCoreKit/Basics
  - FBSDKGamingServicesKit (8.2.0):
    - FBSDKCoreKit (~> 8.2.0)
  - FBSDKLoginKit (8.2.0):
    - FBSDKLoginKit/Login (= 8.2.0)
  - FBSDKLoginKit/Login (8.2.0):
    - FBSDKCoreKit (~> 8.2.0)
  - FBSDKShareKit (8.2.0):
    - FBSDKShareKit/Share (= 8.2.0)
  - FBSDKShareKit/Share (8.2.0):
    - FBSDKCoreKit (~> 8.2.0)
  - Firebase/Analytics (7.0.0):
    - Firebase/Core
  - Firebase/Core (7.0.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 7.0.0)
  - Firebase/CoreOnly (7.0.0):
    - FirebaseCore (= 7.0.0)
  - Firebase/Crashlytics (7.0.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 7.0.0)
  - Firebase/Messaging (7.0.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 7.0.0)
  - Firebase/RemoteConfig (7.0.0):
    - Firebase/CoreOnly
    - FirebaseRemoteConfig (~> 7.0.0)
  - FirebaseABTesting (7.4.0):
    - FirebaseCore (~> 7.0)
  - FirebaseAnalytics (7.0.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleAppMeasurement (= 7.0.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.0)
    - GoogleUtilities/MethodSwizzler (~> 7.0)
    - GoogleUtilities/Network (~> 7.0)
    - "GoogleUtilities/NSData+zlib (~> 7.0)"
    - nanopb (~> 2.30906.0)
  - FirebaseCore (7.0.0):
    - FirebaseCoreDiagnostics (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/Logger (~> 7.0)
  - FirebaseCoreDiagnostics (7.3.0):
    - GoogleDataTransport (~> 8.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/Logger (~> 7.0)
    - nanopb (~> 2.30906.0)
  - FirebaseCrashlytics (7.0.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleDataTransport (~> 8.0)
    - nanopb (~> 2.30906.0)
    - PromisesObjC (~> 1.2)
  - FirebaseInstallations (7.4.0):
    - FirebaseCore (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/UserDefaults (~> 7.0)
    - PromisesObjC (~> 1.2)
  - FirebaseInstanceID (7.0.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/UserDefaults (~> 7.0)
  - FirebaseMessaging (7.0.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstanceID (~> 7.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/Reachability (~> 7.0)
    - GoogleUtilities/UserDefaults (~> 7.0)
  - FirebaseRemoteConfig (7.0.0):
    - FirebaseABTesting (~> 7.0)
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - "GoogleUtilities/NSData+zlib (~> 7.0)"
  - Google-Mobile-Ads-SDK (7.69.0):
    - GoogleAppMeasurement (~> 7.0)
    - GoogleUserMessagingPlatform (~> 1.1)
  - GoogleAppMeasurement (7.0.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.0)
    - GoogleUtilities/MethodSwizzler (~> 7.0)
    - GoogleUtilities/Network (~> 7.0)
    - "GoogleUtilities/NSData+zlib (~> 7.0)"
    - nanopb (~> 2.30906.0)
  - GoogleDataTransport (8.1.0):
    - nanopb (~> 2.30906.0)
  - GoogleUserMessagingPlatform (1.4.0)
  - GoogleUtilities/AppDelegateSwizzler (7.2.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (7.2.0):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/Logger (7.2.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (7.2.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (7.2.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.2.0)"
  - GoogleUtilities/Reachability (7.2.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (7.2.0):
    - GoogleUtilities/Logger
  - nanopb (2.30906.0):
    - nanopb/decode (= 2.30906.0)
    - nanopb/encode (= 2.30906.0)
  - nanopb/decode (2.30906.0)
  - nanopb/encode (2.30906.0)
  - PromisesObjC (1.2.12)
  - UnityAds (3.4.8)

DEPENDENCIES:
  - AppLovinMediationByteDanceAdapter (= 3.2.6.2.0)
  - AppLovinMediationFacebookAdapter (= 5.9.0.0)
  - AppLovinMediationGoogleAdapter (= 7.69.0.1)
  - AppLovinMediationUnityAdsAdapter (= 3.4.8.3)
  - AppLovinSDK (= 6.14.3)
  - FBSDKCoreKit (~> 8.0)
  - FBSDKGamingServicesKit (~> 8.0)
  - FBSDKLoginKit (~> 8.0)
  - FBSDKShareKit (~> 8.0)
  - Firebase/Analytics (= 7.0.0)
  - Firebase/Core (= 7.0.0)
  - Firebase/Crashlytics (= 7.0.0)
  - Firebase/Messaging (= 7.0.0)
  - Firebase/RemoteConfig (= 7.0.0)
  - FirebaseInstanceID (= 7.0.0)

### crash backtrace
`CrashType: UncaughtException
CrashReason: -[NSProcessInfo isiOSAppOnMac]: unrecognized selector sent to instance 0x283158210
Crash Stack:
0 CoreFoundation 0x000000019dae94f8 D3AFD0BA-F0B6-31BD-B65D-2DE422745537 + 1152248 
1 libobjc.A.dylib 0x000000019d80c26c objc_exception_throw + 56 
2 CoreFoundation 0x000000019d9fac4c D3AFD0BA-F0B6-31BD-B65D-2DE422745537 + 175180 
3 CoreFoundation 0x000000019daebb24 D3AFD0BA-F0B6-31BD-B65D-2DE422745537 + 1162020 
4 CoreFoundation 0x000000019daeda9c _CF_forwarding_prep_0 + 92 
5 UnityFramework 0x0000000100cc13a8 GADTransparencyAuthorizationStatus + 524 
6 UnityFramework 0x0000000100cc1258 GADTransparencyAuthorizationStatus + 188 
7 libdispatch.dylib 0x000000019d7a96d8 174B8B8A-283C-32C8-A283-8DF63F76835F + 390872 
8 libdispatch.dylib 0x000000019d74e218 174B8B8A-283C-32C8-A283-8DF63F76835F + 16920 
9 UnityFramework 0x0000000100cc1234 GADTransparencyAuthorizationStatus + 152 
10 UnityFramework 0x0000000100d04a04 GADEnvironmentIsSupported + 3664 
11 libdispatch.dylib 0x000000019d7a86f0 174B8B8A-283C-32C8-A283-8DF63F76835F + 386800 
12 libdispatch.dylib 0x000000019d7a96d8 174B8B8A-283C-32C8-A283-8DF63F76835F + 390872 
13 libdispatch.dylib 0x000000019d758f04 174B8B8A-283C-32C8-A283-8DF63F76835F + 61188 
14 CoreFoundation 0x000000019da692e0 D3AFD0BA-F0B6-31BD-B65D-2DE422745537 + 627424 
15 CoreFoundation 0x000000019da63bb8 D3AFD0BA-F0B6-31BD-B65D-2DE422745537 + 605112 
16 CoreFoundation 0x000000019da63030 CFRunLoopRunSpecific + 540 
17 GraphicsServices 0x00000001a94b4598 GSEventRunModal + 160 
18 UIKitCore 0x00000001a211b570 8C7158E2-3F37-3B7E-81BA-D084E36C5DD8 + 11433328 
19 UIKitCore 0x00000001a2121330 UIApplicationMain + 1864 
20 UnityFramework 0x0000000100626388 UnityFramework + 107400 
21 mansion 0x0000000100383e00 mansion + 32256 
22 libdyld.dylib 0x000000019d8f79d0 B0000CCF-C56D-3662-8631-1B4831962316 + 6608`

**Comment by paulb777** [comment]
From the backtrace, this is a similar crash in a different library - Google-Mobile-Ads-SDK. I'll relay the issue to that team. Filed at b/178938154

**Comment by tianwwMT** [comment]
> From the backtrace, this is a similar crash in a different library - Google-Mobile-Ads-SDK. I'll relay the issue to that team. Filed at b/178938154

Thanks buddy :)

**Comment by paulb777** [comment]
@tianwwMT The Ads team does not plan to address the issue and instead recommends updating the device to a non-beta version.
