### ISSUE TITLE
Undefined symbol "_OBJC_CLASS_$_GIDSignIn"

### ISSUE THREAD

**Issue by hixfield** [firebase/firebase-ios-sdk#7414]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4 (12D4e)
  * Firebase SDK version: 7.5.1
  * Installation method: `Swift Package Manager`
  * Firebase Component: all but issue related to auth I believe

#### Steps to reproduce:

I included Firebase using Swift Package Manager and upon compilation of my project I get the error:

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GIDSignIn", referenced from:
      objc-class-ref in VCReauthenticate.o
      objc-class-ref in AppDelegate.o
      objc-class-ref in VCLogin.o
      objc-class-ref in VCAccount.o
ld: symbol(s) not found for architecture arm64

**Comment by paulb777** [comment]
The missing symbol is from GoogleSignIn which does not yet have a Swift Package Manager distribution. See #6477.  In addition to the discussion there, a potential workaround could be using the GoogleSignin.framework bundled with the [Firebase zip distribution](https://github.com/firebase/firebase-ios-sdk/releases/tag/7.5.0).

**Comment by hixfield** [comment]
I managed to fix with following:

- download the  [Firebase zip distribution](https://github.com/firebase/firebase-ios-sdk/releases/tag/7.5.0)
- unzip it and notice the folder `GoogleSignIn`
- moved this complete folder under my project, I already had a folder "external" (for other not-own-written-stuff), put it under there (this makes sure its made a part of your project's files e.g. stored in git)
- Out of this folder drag over ONLY the following items to your Xcode project navigator (this makes Xcode to include them in your build process):
   - `GoogleSignIn.bundle`
   - `GTMAppAuth.xcframework`
   - `AppAuth.xcframework`
   - `GoogleSignIn.framework`
 - do not drag everything otherwise you will get compiler error "duplicate symbols" while building!

(@paulb777 thanks for the help)

**Comment by hixfield** [comment]
@paulb777 FYI, I noticed that the Firebase zip distribution contains possible a cut / past / rename duplicate: notice `GoogleSignIn.bundle` and `GoogleSignIn.bundle.bundle` (same size, same contents) 
<img width="749" alt="image" src="https://user-images.githubusercontent.com/9302613/106377129-15b20100-639b-11eb-91c9-584d60c43eca.png">

**Comment by paulb777** [comment]
@hixfield Thanks for sharing the step-by-step instructions!

And thanks for pointing out the zip distribution duplicate bundle. I'll reopen this issue and take a look ...
