### ISSUE TITLE
iOS14 App-Store Review rejections: IDFA collection can not be disabled while keeping AdSupport framework

### ISSUE THREAD

**Issue by Kondamon** [firebase/firebase-ios-sdk#7417]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.3.1
  * Installation method: `Swift Package Manager`
  * Firebase Component: Core (+Analytics)

### [REQUIRED] Step 2: Describe the problem

By default Firebase is trying to access IDFA when the AdSuport Framework is implemented in a project. We want to manually attribute app downloads with the AdSupport framework that is required for this task. However, this is not possible with the current implementation because IDFA is automatically accessed by Firebase (Google) when the AdSupport framework is used in a project.

A solution would be to ask permission to track via the AppTrackingTransparency framework but we don't want to track the user. And we don't need tracking allowance for download attribution. However with out asking permission to track what we don't need, our app is rejected in the App Review.

#### Steps to reproduce:

1. Embed AdSupport Framework into XCode project for usage of Apple Search Ads Attribution: https://developer.apple.com/documentation/iad/setting_up_apple_search_ads_attribution/
2. Submit app to Apple App Store Review
3. Receive rejection from App Store Review since Firebase Analytics is accessing IDFA

**Comment by eburley** [comment]
It looks like you're trying to setup Apple Search Ads Attribution, which uses the iAd framework, not the AdSupport framework. Can you try just linking the iAd framework? The only API in AdSupport is for IDFA access.

**Comment by Kondamon** [comment]
@eburley Thanks for clarification. We have mixed those two things up! So when I remove AdSupport I can achieve the expected behavior.
