### ISSUE TITLE
Archive failed: "IPA processing failed

### ISSUE THREAD

**Issue by lowki93** [firebase/firebase-ios-sdk#7418]
### Step 1: Describe your environment

  * Xcode version: !@.4
  * Firebase SDK version: 7.4.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: Analytics, Crashlytics (Auth, Core, Database, Firestore, Messaging, Storage, etc)

#### Steps to reproduce:

When I want to create a build

#### Relevant Code:

<img width="2045" alt="Capture d’écran 2021-02-01 à 19 19 43" src="https://user-images.githubusercontent.com/5473017/106500988-c6ff8680-64c2-11eb-97e9-080118d53804.png">

Do you have any idea how to fix it please ?

**Comment by ryanwilson** [comment]
Although the error isn't the same, there's a known Xcode 12 bug with Analytics using Swift Package Manager and I'm guessing that's what you're hitting: https://github.com/firebase/firebase-ios-sdk/issues/6472

You can verify by archiving in Xcode and inspecting the .ipa. If that's not the case, please re-open and provide steps to reproduce so we can make further progress. Thanks!
