### ISSUE TITLE
[Remote Config] Local conf randomly empty even with successful fetch

### ISSUE THREAD

**Issue by marabid** [firebase/firebase-ios-sdk#7424]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.2
  * Firebase SDK version: 7.3.0
  * Installation method: CocoaPods
  * Firebase Component: RemoteConfig

### [REQUIRED] Step 2: Describe the problem
We use the 3rd loading strategy (Load new values for next startup) as described here https://firebase.google.com/docs/remote-config/loading
Our application fetches the required configuration on the splash screen.

On the first launch, this fetch succeed and the app behaves normally.
For some reason, on other launch the local configuration sometimes returns empty values.
The Firebase app is configured and the logs doesn't identify any issue even if set to max.

**The problem isn't easily reproducible on all devices, but some of them are failing almost 1 on 3 times.**

We Unfortunately couldn't narrow the devices concerned, neither the OS concerned.

When the content is empty :
- The last fetch status is `succeed`
- `defaultExpiration: TimeInterval = 600`

- When we print the value of :

RemoteConfig.remoteConfig().allKeys(from: .remote)
RemoteConfig.remoteConfig().allKeys(from: .static)
RemoteConfig.remoteConfig().allKeys(from: .default)

It returns 0 (no key was found)

#### Steps to reproduce:

Please find below the link to the sample where you can reproduce : 

https://drive.google.com/file/d/1LG4fbE4FCW4Ts61vGgvzQLUW0l6jSH4s/view?usp=sharing

To reproduce, simply install the sample, kill & launch it multiple times. Once the background is red, it means that the local conf is empty.

**Comment by nrj** [comment]
- FirebaseRemoteConfig (7.4.0)

Not sure if related, but I am having a similar issue with defaults not being available. After looking at the source code, I see that the `setDefaults` is asynchronous and invoked on the same serial queue as `fetchAndActivateWithCompletion:`. When calling both in order as the documentation states, the completion block of the latter would be invoked when both are complete. In my application I implement a blocking loading screen which I use to call both `setDefaults` and `fetchAndActivateWithCompletion:` but I set a maximum timeout of 6 seconds. If the completion block is not invoked within 6 seconds, then I dismiss the loading screen and open the app anyways. The operation will finish at some point, but until then I expect the default values from the plist to be available and return when queried. On older phones however, specifically iPhone 6s and older iPads, I am seeing that quite often the default values are _not_ available and the values are all null. The `source` property is 3, and the values are static uninitialized values, 0's and empty strings.

**Comment by marabid** [comment]
@nrj thank you for your reply.

Indeed, it seems to be easier to reproduce on old phones and iPads.

The only workaround we've found at this point, is to downgrade to `FirebaseRemoteConfig 7.0.0` which seems to work a bit better, even if we were able to reproduce on this version as well.

Please let me know if you find any better workaround.

**Comment by bachtrong43** [comment]
I'm facing this issue with newest version 7.7.0 on iOS.
Firebase seems not to save the values after fetched.
Steps:
First launch:
1. Call fetchAndActivate()
2. print keysWithPrefix(null).size: always 0
3. In callback of 1 print allKeys.size: get correct result.

Kill app and launch again with the same steps. The result is always 0 in step 2 (expected correct result with fetched values before)

**Comment by bachtrong43** [comment]
Downgraded to 7.0.0 and got the expected result.

**Comment by sethdeckard** [comment]
I'm seeing the same thing on `7.6.0` and it does seem to affect older devices for the most part (many iPhone 6/6s, some iPhone 7).

**Comment by ThibautRichez** [comment]
We are encountering this issues for a while now and this have a huge impact on our AppStore rating / reviews.
As said above, we reproduced it on other Firebase/RemoteConfig versions and mostly on older phones (5S, 6, 6S, …. but some of our customers had this issues with iPhone X though).

Please up this issues and share any thoughts/workaround you have.

Thanks

**Comment by lucasvercelot** [comment]
Hello,

I have the same problem. It happens from time to time, no idea why.
I don't know if the problem comes from the SDK or from a server-side issue.

Please fix this, thanks.

**Comment by karenyz** [comment]
Thanks for all the detailed reports!! Sorry it took some time to track down the problem. Put in a fix that will be in the next release, feel free to re-open if this issue still persists after that
