### ISSUE TITLE
'TARGET_OS_WATCHOS' is not defined, evaluates to 0

### ISSUE THREAD

**Issue by richiehopedbt** [firebase/firebase-ios-sdk#7425]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5 beta (12E5220o)
  * Firebase SDK version: 7.5.1
  * Installation method:  Swift Package Manager
  * Firebase Component:Auth

### [REQUIRED] Step 2: Describe the problem
Issue arises on build
#### Steps to reproduce:
Build to deploy on device
What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

"'TARGET_OS_WATCHOS' is not defined, evaluates to 0" error shown in FIRAuthDefaultUIDelegate.h file

**Comment by ryanwilson** [comment]
Thanks for the report and sorry for the trouble! This was just resolved this morning in #7423 and should be included in the next update. I'll close this for now since there's no other action needed.
