### ISSUE TITLE
handleUniversalLink does not correctly handle password reset links

### ISSUE THREAD

**Issue by adamduren** [firebase/firebase-ios-sdk#743]
### [READ] Step 1: Are you in the right place?
I think so.

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.2
  * Firebase SDK version: 4.8.2
  * Firebase Component: DynamicLinks
  * Component version: 4.8.2

### [REQUIRED] Step 3: Describe the problem
`handleUniversalLink` completion handler returns a `nil` dynamicLink and a `nil` error. I would expect one or the other but not for both to be `nil`. I am able to parse it with `dynamicLinkFromUniversalLinkURL` without issue but my understanding is that `handleUniversalLink` should work for link dynamic links.
 
#### Steps to reproduce:

1. Send a password reset link via the JS SDK with the below configuration.
1. Click on email mobile iOS device
1. Observe that the URL is not parsed by `handleUniversalLink` but is by `dynamicLinkFromUniversalLinkURL`

#### Relevant Code:

```typescript
this.services.auth.sendPasswordResetEmail(email, {
  url: `http://golfer.teeboxnow.com/password-reset/?email=${email}`,
  iOS: {
    bundleId: 'com.teeboxnow.golfer',
  },
  handleCodeInApp: true,
}),
```

```objective-c
// userActivity.webpageURL is the value from the email sent from Firebase using the JS-SDK as shown below. The URL was sent with

// https://g2dx5.app.goo.gl?link=https://teeboxnow-test.firebaseapp.com/__/auth/action?apiKey%3DAIzaSyALYlIavrojW6PX1xns4X7sgQav7P72WfU%26mode%3DresetPassword%26oobCode%3D-ApyTAhhNs-fftrFytXGx5oB3hLoe5xYKYhePwLoVkEAAAFhU-l26Q%26continueUrl%3Dhttp://golfer.teeboxnow.com/password-reset/?email%253Dadamduren@gmail.com&ibi=com.teeboxnow.golfer&ifl=https://teeboxnow-test.firebaseapp.com/__/auth/action?apiKey%3DAIzaSyALYlIavrojW6PX1xns4X7sgQav7P72WfU%26mode%3DresetPassword%26oobCode%3D-ApyTAhhNs-fftrFytXGx5oB3hLoe5xYKYhePwLoVkEAAAFhU-l26Q%26continueUrl%3Dhttp://golfer.teeboxnow.com/password-reset/?email%253Dadamduren@gmail.com

BOOL handled = [[FIRDynamicLinks dynamicLinks]
    handleUniversalLink:userActivity.webpageURL
    completion:^(FIRDynamicLink * _Nullable dynamicLink, NSError * _Nullable error) {
        if (dynamicLink) {
            [dl postDynamicLink:dynamicLink];
        }
    }];
// HANDLED is YES
// error is nil
// dynamicLink is nil

FIRDynamicLink *link = [[FIRDynamicLinks dynamicLinks]
       dynamicLinkFromUniversalLinkURL:userActivity.webpageURL
```

**Comment by adamduren** [comment]
It's possible that something is going wonky with the URL encoding/decoding causing the method not to recognize it. Not sure but just a thought.

**Comment by adamduren** [comment]
Also this is approaching feature request territory but is there any way to tame that URL (shorten it via short links) before it's sent off? It's a bit of a monster.

**Comment by adamduren** [comment]
NVM on the long URL comment. I can modify the email template to workaround that.

**Comment by morganchen12** [comment]
It's most likely, as you said, something wonky with the URL logic in DynamicLinks.

I'm not entirely sure if this is a bug yet, but the way the SDK handles errors is not ideal both for us debugging issues and third-party devs trying to understand where their failures originate. I'll take a look at changing our link handling logic to return more descriptive errors instead of returning `nil` in most cases.

**Comment by adamduren** [comment]
@morganchen12 thank you for the response. Let me know if there is anything I can do to help. I wanted to inspect the `handleUniversalLink` to see where things are going wrong but the source for that doesn't appear to be available. On the JS side of things it doesn't appear to be doing anything special such as URL Encoding. It creates a RPC request with the params specified to the Firebase Backend and it returns the URL posted in the issue above.

**Comment by adamduren** [comment]
```objective-c
FIRDynamicLink *link = [[FIRDynamicLinks dynamicLinks]
       dynamicLinkFromUniversalLinkURL:userActivity.webpageURL
```
Also I noticed that when using the above code with the below link (which was generated by the Firebase backend):
> http://golfer.teeboxnow.com/password-reset/?email%253Dadamduren@gmail.com

I get the link:
> http://golfer.teeboxnow.com/password-reset/?email%3Dadamduren@gmail.com

It appears that the `=` gets encoded twice `encodeURIComponent(encodeURIComponent('=')) === '%253D'` . So something is going wrong there as well as you would expect to get the original URL without any additional manipulation.

**Comment by dmandar** [comment]
Thanks for the feedback. Will ensure that the codepath returns back an error if the link is nil. Also have filed a bug to investigate the double encodeURIComponent.

**Comment by liyu0013** [comment]
Any updates on this? I'm also having a similar issue with SDK 5.2.0 and 5.4.0. Our app works fine if it's already running background or foreground. But it's killed and then I trigger a dynamic link, dynamicLink and error will be both nil.

**Comment by ryanwilson** [comment]
@dmandar is this still an issue?

**Comment by paulb777** [comment]
Closing for staleness. Please open a new issue and reference this one if it reoccurs.
