### ISSUE TITLE
Firebase/CoreOnly/Source/Firebase.h not found

### ISSUE THREAD

**Issue by osman-kocak** [firebase/firebase-ios-sdk#7441]
ı have same folder but ıts can not find it

ı am try reinstall Cocoapods and Im edit podfile like that  install! 'cocoapods', :generate_multiple_pod_projects => false, :incremental_installation => false 
![Screenshot 2021-02-02 at 16 15 25](https://user-images.githubusercontent.com/57155882/106759156-12d53b80-663b-11eb-96a6-28eb93b2bde5.png)

**Comment by osman-kocak** [comment]
![Screenshot 2021-02-03 at 16 19 46](https://user-images.githubusercontent.com/57155882/106759729-c2121280-663b-11eb-8530-1dbe95182951.png)

FLT Firebase Messaging Plugin.m

**Comment by paulb777** [comment]
`#import <Firebase/CoreOnly/Source/Firebase.h>` is not the correct way to import `Firebase.h`. 

`FLTFirebaseMessagingPlugin.m` is not part of this project and I don't see it in git@github.com:flutter/flutter.git.

Please remove that import and/or report to the project that it comes from.
