### ISSUE TITLE
SPM: Framework not found FBLPromises

### ISSUE THREAD

**Issue by Michaelcraun** [firebase/firebase-ios-sdk#7448]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.5.1
  * Installation method: Swift Package Manager
  * Firebase Component: Using Auth, Firestore, and Storage -- unsure which is the problem

#### Steps to reproduce:

Installed the SDK via SPM, built and received the the following error in Xcode:

```
ld: framework not found FBLPromises
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The application was working perfectly before updating to SPM... If you need any more information, please let me know.

**Comment by paulb777** [comment]
This is likely related to stale project metadata. Please try File -> Swift Packages -> Reset Package Caches

**Comment by Michaelcraun** [comment]
After completing this process, the error remains...

**Comment by paulb777** [comment]
There might be lingering options in the Xcode project settings. Try searching for FBLPromises in the settings.

Are you able to share a reproducible example?

**Comment by Michaelcraun** [comment]
When I search for `FBLPromises` in the Project's Build Settings, nothing is found. 

However, when I search for it in the Target's Build Settings, it shows up under `Other Linker Flags`.

I'll work on getting a test project to reproduce the issue and upload it when it's done and if I can reproduce it.

**Comment by Michaelcraun** [comment]
With a fresh and empty project, adding the same packages via SPM does not cause any issues...

**Comment by Michaelcraun** [comment]
I'm not sure what was causing this, but I copied all files from the old project into the new project that wasn't encountering any errors and everything seems to be working fine...

Very odd, but thank you for your time!
