### ISSUE TITLE
How to clear dynamic link on iOS after first launch the app

### ISSUE THREAD

**Issue by kyweng** [firebase/firebase-ios-sdk#7452]
Hi all,

My app has success to grab the dynamic link during the first install and open the app. However, the dynamic link keep detected after re-install the app.

Is there any solution?

**Comment by kyweng** [comment]
> I found a few problems with this issue:
> 
> * I couldn't figure out how to label this issue, so I've labeled it for a human to triage. Hang tight.
> * This issue does not seem to follow the issue template. Make sure you provide all the required information.

How to add label?

**Comment by ryanwilson** [comment]
Hi @kyweng, sorry for the troubles. Can you please fill out the issue template so we have more information about what version of Firebase, and iOS you're using? Also can you reproduce this in the quickstart app? If so, that'll help us tremendously in seeing the issue and fixing it. Thanks!
