### ISSUE TITLE
iOS Firebase ML / MLKit (MLModelInterpreter pod not working)

### ISSUE THREAD

**Issue by mobee-bill** [firebase/firebase-ios-sdk#7456]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.5.0
  * Installation method: CocoaPods
  * Firebase Component: FirebaseML / ML Kit

### [REQUIRED] Step 2: Describe the problem
I am following the guide: https://firebase.google.com/docs/ml/ios/use-custom-models
I am using cocoapods 1.10.1 and xcode 12.4.

Using cocoapods (I reproduce my problem with a simple new test project):

- POD FILE-
```
platform :ios, '12.0'

target 'test_app' do
  use_modular_headers!
  
  pod 'TensorFlowLiteSwift'
  pod 'Firebase/MLModelInterpreter'

end
```

#### Steps to reproduce:

Attempting to build the project I end up with the following error:
Module map file '/Users/.../test_app/Pods/Headers/Private/TFLTensorFlowLite/TensorFlowLiteObjC.modulemap' not found

pod 'Firebase/MLModelInterpreter' is the culprit here. Am I missing some configuration?  The guides for using this are extremely straightforward and simple

**Comment by paulb777** [comment]
Sorry about the trouble.

The Podfile option `use_modular_headers!` does not work with `TensorFlowLiteSwift`.

Use `use_frameworks! :linkage => :static` instead.
