### ISSUE TITLE
FR: Include GOOGLE_ANALYTICS_IDFV_COLLECTION_ENABLED in debug logs

### ISSUE THREAD

**Issue by rzulkoski** [firebase/firebase-ios-sdk#7467]
### Feature proposal

* Firebase Component: Analytics

When including the `GOOGLE_ANALYTICS_IDFV_COLLECTION_ENABLED` key in an app's Info.plist, there is no confirmation that Firebase recognized the presence of the key. It would be helpful if Firebase/Analytics could reference the presence of the key and its current value in the debug logs shown in the console similar to how other keys are handled. This would give users confidence that they have added the key correctly.

**Comment by mikehardy** [comment]
@paulb777 looks like this was included in release 8.8.0? https://firebase.google.com/support/release-notes/ios#analytics
Always fun to hit the "close" button when the resolution is "we shipped it"

**Comment by morganchen12** [comment]
Yep, thanks @mikehardy!
