### ISSUE TITLE
test_coverage workflow fails on external PRs

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#7476]
See #7472 

The `test_coverage` workflow should either be disabled or made to work for PRs from forked repos.

**Comment by granluo** [comment]
If secrets are not able to be accessed, then Metrics Service cannot be used and so code coverage report is not able to be created. To avoid failing test workflows, we might need to disable this workflows under certain situations.
I made some experiments and it looks like the sdk repo can run workflows from a forked repo, not sure if secrets can be used or not yet. Will make more experiments.

**Comment by paulb777** [comment]
Reopening. Still seeing failures in #7507

**Comment by paulb777** [comment]
@granluo Still seeing failures in https://github.com/firebase/firebase-ios-sdk/pull/7549/checks?check_run_id=1921393904

Please test in a fork.

**Comment by granluo** [comment]
Have test on a fork repo. The corresponding step is in the step `check files` of the job `Check changed files` 
https://github.com/firebase/firebase-ios-sdk/runs/1929701292?check_suite_focus=true

The failure is probably caused by that fork repo not syncing to the upstream yet.

**Comment by paulb777** [comment]
I see thanks.

**Comment by paulb777** [comment]
Reopening - the issue looks back in #7955

**Comment by paulb777** [comment]
@granluo This is still failing in #8483 and #8484.  Please test on a forked PR. Reopening.

**Comment by paulb777** [comment]
There is still a post-submit issue, but that's not a big deal. I'll close since presubmits are now working.
