### ISSUE TITLE
Multiple commands produce - updating from 7.4.0 to 7.5.0

### ISSUE THREAD

**Issue by guidev** [firebase/firebase-ios-sdk#7486]
### Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.5.0
  * Installation method: `CocoaPods`
  * Firebase Component: Analytics

#### Steps to reproduce:

I get the following error when updating from Firebase 7.4.0 to Firebase 7.5.0

```
    Multiple commands produce '/Users/redacted/Library/Developer/Xcode/DerivedData/MyApp-anpbtbokxviinkeqjaakixizzscs/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/FirebaseAnalytics':
    1) That command depends on command in Target 'FirebaseAnalytics-iOS12.0' (project 'Pods'): script phase “[CP] Copy XCFrameworks”
    2) That command depends on command in Target 'FirebaseAnalytics-iOS14.0' (project 'Pods'): script phase “[CP] Copy XCFrameworks”
```

My App (min. iOS 12.0) has a AppClip target (min. iOS 14.0).

#### Relevant Code:

Podfile

```
    inhibit_all_warnings!
    use_frameworks!
    
    def shared_pod
      pod 'GoogleUtilities' #Or else iMessage crashes
      pod 'GTMSessionFetcher'
      pod 'Firebase/Auth'
      pod 'Firebase/RemoteConfig'
      pod 'Firebase/Core'
      pod 'Firebase/Analytics'
      pod 'Firebase/Crashlytics'
    end
    
    target 'AppClip' do
      platform :ios, '14.0'
      shared_pod
    end
    
    target 'MyApp' do
      platform :ios, '12.0'
      pod 'Firebase/Performance'
      pod 'Firebase/AdMob'
      shared_pod
    end
       
    
    post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
        end
      end
    end

```

**Comment by paulb777** [comment]
This is almost certainly a CocoaPods issue exposed by FirebaseAnalytics switching to an xcframework distribution in 7.5.0. See https://github.com/CocoaPods/CocoaPods/issues/10106 and https://github.com/CocoaPods/CocoaPods/issues/9670

**Comment by ryanwilson** [comment]
Since there's no workarounds or changes we can make in this repo to make this work, we'll close this in favour of the CocoaPods issue you have commented in: https://github.com/CocoaPods/CocoaPods/issues/9973.

Thanks again for the report!
