### ISSUE TITLE
FirebasePerformance SDK warns that FirebaseAnalytics should be included

### ISSUE THREAD

**Issue by kaganriedel** [firebase/firebase-ios-sdk#7487]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.5
  * Installation method: CocoaPods
  * Firebase Component: Performance, though I also have Crashlytics installed.

### [REQUIRED] Step 2: Describe the problem
`Firebase.h` generates a warning when `FirebasePerformance` is included but `FirebaseAnalytics` isn't included in the project. This contradicts the SDK's documentation.

The table in [this section](https://firebase.google.com/docs/ios/setup#available-pods) does not list Analytics as required for the Performance SDK. Additionally my experience so far has been that the Performance SDK has been working just fine without Analytics included.

#### Steps to reproduce:

1. Include the Firebase Performance SDK in a project that does not include the Analytics SDK.
2. In case it matters, I installed the SDK using CocoaPods and also have the Crashlytics SDK included in the project.
3. Build the app.
4. Note the warning `"FirebaseAnalytics.framework is not included in your target. Please add the \
FirebaseAnalytics dependency to your project to ensure Firebase Performance works as intended."`

#### Relevant Code:

It seems like these lines are incorrect and should be removed, or the documentation in the SDK is incorrect.
```
  #if __has_include(<FirebasePerformance/FirebasePerformance.h>)
    #import <FirebasePerformance/FirebasePerformance.h>
    #if TARGET_OS_IOS && !__has_include(<FirebaseAnalytics/FirebaseAnalytics.h>)
      #ifndef FIREBASE_ANALYTICS_SUPPRESS_WARNING
        #warning "FirebaseAnalytics.framework is not included in your target. Please add the \
FirebaseAnalytics dependency to your project to ensure Firebase Performance works as intended."
      #endif // #ifndef FIREBASE_ANALYTICS_SUPPRESS_WARNING
    #endif
  #endif
```

**Comment by paulb777** [comment]
Reopening. This still occurs in 7.8.0 because of the FirebasePerformance dependency RemoteConfig. It reproduces in the performance quickstart after removing Analytics from the Podfile

**Comment by paulb777** [comment]
Firebase 8 will eliminate all the build time warnings from Firebase.h about the missing Analytics frameworks.
