### ISSUE TITLE
Fix Performance and coverage

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#7494]
It looks like the necessary environment variables are not set up for the unit tests.

See https://github.com/firebase/firebase-ios-sdk/runs/1865898722?check_suite_focus=true

**Comment by granluo** [comment]
Firestore seems to not have unit test_spec in the podspec. Performance does not trigger unit test in its podspec. Will fix it.

**Comment by granluo** [comment]
Performance unit tests are running but some of tests get errors. It looks like Performance needs additional setup for the test if pod tests run through podspecs. Wonder if @visumickey has any ideas.

**Comment by visumickey** [comment]
Just added inputs on this offline. We need to set a specific MACRO for the unit tests to pass. 

https://github.com/firebase/firebase-ios-sdk/blob/master/scripts/build.sh#L562

Once this is set, the unit tests should pass.

**Comment by granluo** [comment]
Thanks! That fixed the unit test.
Just got another [error](https://github.com/firebase/firebase-ios-sdk/runs/1874469294?check_suite_focus=true) 
`
    - NOTE  | [iOS] xcodebuild:  2021-02-10 20:41:44.226863+0000 AppHost-FirebasePerformance-Unit-Tests[4948:25758] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
 `
Found a related [issue](https://github.com/firebase/firebase-ios-sdk/issues/1965) and tried to turn off the log but it cannot work before a simulator got launched. Wonder if I missed any setup for the tests?

**Comment by granluo** [comment]
Have update the testing approach from pod_lib_lint test to running `scripts/build.sh Performance iOS unit`, which is consistent with [performance.yml](https://github.com/firebase/firebase-ios-sdk/blob/master/.github/workflows/performance.yml#L35-L37) workflow.
It seems to be running right now.
https://github.com/firebase/firebase-ios-sdk/actions/runs/556282804
