### ISSUE TITLE
clang: error: -fobjc-weak is not supported on the current deployment target

### ISSUE THREAD

**Issue by neeboo** [firebase/firebase-ios-sdk#750]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: Version 9.2 (9C40b)
  * Firebase SDK version: Latest Pod version
  * Firebase Component:Auth
  * Component version:Latest Pod version

### [REQUIRED] Step 3: Describe the problem
Build with Xcode Failure

> clang: error: -fobjc-weak is not supported on the current deployment target

#### Steps to reproduce:

Standard procedure ,see [Add Firebase to your iOS Project ](https://firebase.google.com/docs/ios/setup?authuser=0)

#### Relevant Code:

none

**Comment by paulb777** [comment]
Thanks for the report. 

This is https://github.com/CocoaPods/Xcodeproj/issues/544 for which a fix was released last night.  Update the Xcodeproj gem from 1.5.5 to 1.5.6.

**Comment by neeboo** [comment]
thanks @paulb777
