### ISSUE TITLE
GoogleTagManager on Apple Silicon (M1)

### ISSUE THREAD

**Issue by voidless** [firebase/firebase-ios-sdk#7509]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.6.0
  * Installation method: `CocoaPods`
  * Firebase Component: GoogleTagManager
  * Apple Silicon (M1) Macmini

#### Steps to reproduce:

Add `pod 'GoogleTagManager'` to `Podfile`
Run `pod install`
Compile project for iOS Simulator

Build fails with error:
```
ld: in <redacted>/Pods/GoogleAnalytics/Libraries/libGoogleAnalytics.a(GAIUtil.o), building for iOS Simulator, but linking in object file built for iOS, file '<redacted>/Pods/GoogleAnalytics/Libraries/libGoogleAnalytics.a' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It seems that iOS simulator on Apple Silicon requires vendored libraries to be bundled in xcframeworks with arm64 arch for mac

This seems to be the same issue as https://github.com/firebase/firebase-ios-sdk/issues/7208 but with different pod from different Google team

I know that there is a workaround with EXCLUDED_ARCHS, but this issue still needs to be fixed to fully support M1

**Comment by ramunasjurgilas** [comment]
In out team it becomes one of the biggest problem as all Macs are M1. And we are not willing to by legacy Macs only to build Firebase projects. 

Some updates regarding this issue would be very good.

**Comment by lucasecf** [comment]
Any one has a decent workaround for this? Sad to see it's taking so long, and there's no feedback

**Comment by paulb777** [comment]
Sorry about the delay. I created the internal issue b/182789346 to ask the Google Tag Manager for an update.

**Comment by ramunasjurgilas** [comment]
@paulb777 AdMob SDK have the same problem. Do I need to report this bug separately?

**Comment by paulb777** [comment]
@ramunasjurgilas AdMob added Apple silicon support in 7.69. See https://developers.google.com/admob/ios/rel-notes

**Comment by sbo-nemlig** [comment]
Any updates on this ?

**Comment by jestemnawakacjach** [comment]
BUMP

**Comment by AnarionII** [comment]
Hi everyone, 

I would love as well to see a proper fix from Google, but in the mean time here is a workaround pretty straightforward. I add  GTM and his dependencies only in Release, I can do that because I have no Swift code that imports them. That way I can build for simulator in Debug on Apple Silicon.

```ruby
target :'MyTarget' do
  project 'MyProject/MyProject.xcodeproj'

  pod 'GoogleTagManager', '7.2.0', :configuration => 'Release'
  pod 'GoogleAnalytics', :configuration => 'Release'
  pod 'GoogleUtilitiesLegacy', :configuration => 'Release'
  pod 'GoogleSymbolUtilities', :configuration => 'Release'
end

**Comment by john-crossley** [comment]
Any updates? 🙏🏻

**Comment by john-crossley** [comment]
https://cocoapods.org/pods/GoogleTagManager 🥳 just waiting on `GoogleAnalytics` now!

**Comment by xlcod** [comment]
Any updates on this?, also happening on Flutter with IOS.

**Comment by quintonpryce** [comment]
Any updates on this issue?

**Comment by jperezes** [comment]
driving me mad, anything new? God why on earth I did decide to go for an M1 computer...

**Comment by gscalzo** [comment]
Any news here?

**Comment by lucasecf** [comment]
Any news[n] ?

**Comment by john-crossley** [comment]
Not happening this is it... 😢

**Comment by AlexNsbmr** [comment]
Any updates on this ? Really waiting this as Google Sign In SDK now fixes this issue

**Comment by cameroncooke** [comment]
Just adding my +1. This is becoming a real pain and might force us to migrate away from GA faster.

**Comment by elusivestudio** [comment]
Will there be any update? Or is it going to be discontinued?

**Comment by tsunghung** [comment]
Sorry for the long wait. We are working on it. There will be an update, hopefully, within a few weeks.

**Comment by tsunghung** [comment]
GoogleTagManager (7.4.0) is published. It supports developing with Apple Silicon devices.
- Cocoapods 1.10.2+ is required.
