### ISSUE TITLE
Flutter App, cannot build IOS. fatal error: 'FirebaseCore/FIRLogger.h' file not found

### ISSUE THREAD

**Issue by miamee** [firebase/firebase-ios-sdk#7513]
Do we have solution with this error for firebase?

Xcode build done.                                            7.6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    In file included from
    /Users/liux21/Desktop/cc/flutter_application/ios/Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/Installati
    onsStore/FIRInstallationsStoredItem.m:19:
    /Users/liux21/Desktop/cc/flutter_application/ios/Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/FIRInstall
    ationsLogger.h:19:9: fatal error: 'FirebaseCore/FIRLogger.h' file not found
    #import <FirebaseCore/FIRLogger.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    In file included from
    /Users/liux21/Desktop/cc/flutter_application/ios/Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/Installati
    onsStore/FIRInstallationsStoredAuthToken.m:19:
    /Users/liux21/Desktop/cc/flutter_application/ios/Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/FIRInstall
    ationsLogger.h:19:9: fatal error: 'FirebaseCore/FIRLogger.h' file not found
    #import <FirebaseCore/FIRLogger.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

**Comment by maksymmalyhin** [comment]
@miamee Sorry you experience the issue. It looks like an outdated version of Firebase is used in your project.  The issue should not be reproducible in recent Firebase versions. Could you please try to update Firebase and let us know if you still have issues.

**Comment by paulb777** [comment]
Similar to https://github.com/invertase/react-native-firebase/issues/2193, resetting the environment should help.
