### ISSUE TITLE
No Google App ID or Google Services file provided - SPM Crashlytics

### ISSUE THREAD

**Issue by PiotrStepien** [firebase/firebase-ios-sdk#7514]
Hi I am trying to update **dSYM** files to Firebase Console, but each time when I try to execute **upload-symbol** script I receive an information _No Google App ID or Google Services file provided_. Script is located in _script_ folder directly in _.xcodeproj_ location. GoogleService-Info.plist is located in project. Is there any other solution to upload dSYM files? In old Fabric Console user had a possibility to manually upload file and it was really helpful method.

**Comment by samedson** [comment]
Hey @PiotrStepien - I believe this just means you need to explicitly pass it the GoogleService file.

Can you try:

```
/scripts/upload-symbols --gsp /path/to/GoogleService-Info.plist <path-to-dSYM>
```

**Comment by PiotrStepien** [comment]
@samedson Thx its working, but I'm my case I hade to add additional flag `/scripts/upload-symbols --gsp /path/to/GoogleService-Info.plist -p ios <path-to-dSYM>`
