### ISSUE TITLE
Use of undeclared identifier 'FIRAnalytics' (Xcode 12.4,  Firebase 7.6.0)

### ISSUE THREAD

**Issue by yoasha** [firebase/firebase-ios-sdk#7521]
- I'm using standard cocoapods setup.
- I just run 'pod update', which installed 7.6.0 (was 7.2.0)
- Xcode now shows `Use of undeclared identifier 'FIRAnalytics'`

The odd thing is that my project is built successfully, but any line contains `[FIRAnalytics logEventWithName:]` appears with the above error in the Xcode editor (see screenshot below)

I am using `#import <Firebase/Firebase.h>` in my code and `pod 'Firebase/Analytics'` in the pod file as instructed at https://firebase.google.com/docs/ios/setup#objective-c

If I add `#import <FirebaseAnalytics/FirebaseAnalytics.h>` below `#import <Firebase/Firebase.h>` then issue is gone.

Any ideas what is going on?

![image](https://user-images.githubusercontent.com/5601548/107792907-5c6e0680-6d5e-11eb-9ddf-17f64ad77385.png)

**Comment by paulb777** [comment]
@yoasha Thanks for the report.

It looks like CocoaPods is not properly updating FirebaseAnalytics to the recent `.xcframework` version of the pod. A workaround is to run `pod deintegrate` and then `pod install` or `pod update` again.

That just worked for me on what looks like a similar issue.

Please try that and let us know if that solves it.

**Comment by yoasha** [comment]
Thanks for the quick reply.

I did as suggested but it didn't fix the issue. 

I should probably have pointed out that my iOS app is based on a static library project. Now, the reported issue was detected while building the iOS app (which depends on the static library and builds it first). However, I just tried to build the static library alone and the issue didn't appear there. It seems that the issue is related to my projects configuration and appears only on the top level app project, but I'm not sure how to check this out.

**Comment by paulb777** [comment]
Hmm, in that case, something about how that static library shares its transitive dependency might need to change now that FirebaseAnalytics is packaged as an `.xcframework` instead of a `.framework`.

**Comment by yoasha** [comment]
Thank you for pointing about this change! I was wondering if there were recent changes that could create this effect and this sounds like a good candidate. 

Can you please specify in which version this package change introduced? I have no idea what this change means, but at least I know where to start.

**Comment by paulb777** [comment]
The change occurred in the 7.5.0 release. More background in https://github.com/firebase/firebase-ios-sdk/blob/master/AppleSilicon.md

**Comment by yoasha** [comment]
@paulb777 Thanks a lot for all your help!
