### ISSUE TITLE
After upgrading to 7.6.0: GoogleDataTransport has no Package.swift manifest

### ISSUE THREAD

**Issue by madsodgaard** [firebase/firebase-ios-sdk#7523]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.6.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: Core

### [REQUIRED] Step 2: Describe the problem
After updating the iOS SDK to `7.6.0` from `7.5.1` we started experiencing issues with building our project in CI.
This is the error we get when building our project in CI:
```
[16:30:54]: ▸ xcodebuild: error: Could not resolve package dependencies:
261
[16:30:54]: ▸   https://github.com/google/GoogleDataTransport.git has no Package.swift manifest for version 8.2.0
262
[16:30:54]: ▸   https://github.com/google/GoogleDataTransport.git has no Package.swift manifest for version 8.2.0
```
\
We currently have a workaround by downgrading to `7.5.1`.

**Comment by paulb777** [comment]
Sorry about the issue and thanks for the report.

Would you see if File-> Swift Packages -> Reset Package Caches addresses the issue.

The 8.2.0 tag is here - https://github.com/google/GoogleDataTransport/releases/tag/8.2.0

**Comment by madsodgaard** [comment]
Hey!

Yes. We have already tried that step, did not seem to do any changes to our resolved package files or the dependencies. So therefore it did not fix the issue for us.

**Comment by paulb777** [comment]
Hmm, we're not able to reproduce and will likely need a reproducible example to help ...

**Comment by NealArthur5** [comment]
doesn't works for me neither.
I pasted this url https://github.com/firebase/firebase-ios-sdk.git and shows me this error:


Showing All Messages
The repository could not be found. Make sure a valid repository exists at the specified location and try again.

**Comment by ryanwilson** [comment]
@NealArthur5 can you share which version of Xcode you're using, along with steps? I'm unable to reproduce this either. I created a brand new project, went to `File -> Swift Packages -> Add Package Dependency...` and was able to proceed.

<img width="727" alt="Screenshot of the Swift Package Manager screen working as expected" src="https://user-images.githubusercontent.com/1097316/108231944-44a4d280-7110-11eb-950d-5e0b88999dda.png">

**Comment by BobbyRohweder** [comment]
I see this issue as well.
I usually see it happening on CircleCI since the packages get refetched when they are not cached.
Using Xcode 12.4

Error:
```
xcodebuild: error: Could not resolve package dependencies:
  https://github.com/google/GoogleDataTransport.git has no Package.swift manifest for version 8.2.0
```

Produced from Fastlane build and test step
```
Command line invocation:
    /Applications/Xcode-12.4.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -scheme AppScheme -project ./AppProject.xcodeproj -clonedSourcePackagesDirPath SourcePackages
```

This does seem to be intermittent, occurring about roughly 60% of the time.

**Comment by paulb777** [comment]
I strongly suspect a Swift Package Manager bug because of the indeterminism. Hopefully, there will be some insights here or at https://forums.swift.org/t/swift-package-manager-fails-to-locate-the-package-swift-file/45490
