### ISSUE TITLE
Use of FirebaseCrashlytics Pod (7.6.0) results in AppStore-rejection due to usage of UIWebview

### ISSUE THREAD

**Issue by aherbig** [firebase/firebase-ios-sdk#7543]
When using the Firebase/Crashlytics pod, these pods get installed:

> Installing Firebase (7.6.0)
> Installing FirebaseCore (7.6.0)
> Installing FirebaseCoreDiagnostics (7.6.0)
> Installing FirebaseCrashlytics (7.6.0)
> Installing FirebaseInstallations (7.6.0)
> Installing GoogleDataTransport (8.2.0)
> Installing GoogleUtilities (7.2.2)
> Installing PromisesObjC (1.2.12)
> Installing nanopb (2.30907.0)

When I try to upload my app to the AppStore, it gets rejected with the message that UIWebview is used.
I already checked alot of similar issues regarding this, but all mention that this should no longer be the case in the version of firebase I am using....
Any ideas on why this issue might arise?

>  ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

**Comment by ryanwilson** [comment]
Hi @aherbig - sorry for the trouble you're seeing. 

There are no references to `UIWebView` in this repo, and shouldn't be in any of the above pods you've listed. Are there other pods that are being included? You could use `grep` to try to find references there, or `git grep` if you're managing these files in `git`. The only references I see here are CHANGELOG mentions:

```
git grep UIWebView
FirebaseDynamicLinks/CHANGELOG.md:- [fixed] Removed references to UIWebViewDelegate to comply with App Store Submission warning. (#3722)
FirebaseDynamicLinks/CHANGELOG.md:- [fixed] Removed references to UIWebView to comply with App Store Submission warning. (#3722)
```

**Comment by aherbig** [comment]
I used the grep command like this for my app: (ZZZZ001 being the app-name)

> grep -r "UIWebView" .                                                                             
Binary file ./AppStore.xcarchive/Products/Applications/ZZZZ001.app/ZZZZ001 matches
Binary file ./AppStore.xcarchive/dSYMs/FirebaseCrashlytics.framework.dSYM/Contents/Resources/DWARF/FirebaseCrashlytics matches
Binary file ./AppStore.xcarchive/dSYMs/FirebaseInstallations.framework.dSYM/Contents/Resources/DWARF/FirebaseInstallations matches
Binary file ./AppStore.xcarchive/dSYMs/GoogleUtilities.framework.dSYM/Contents/Resources/DWARF/GoogleUtilities matches
Binary file ./AppStore.xcarchive/dSYMs/GoogleDataTransport.framework.dSYM/Contents/Resources/DWARF/GoogleDataTransport matches
Binary file ./AppStore.xcarchive/dSYMs/FirebaseCore.framework.dSYM/Contents/Resources/DWARF/FirebaseCore matches
Binary file ./AppStore.xcarchive/dSYMs/ZZZZ001.app.dSYM/Contents/Resources/DWARF/ZZZZ001 matches
Binary file ./AppStore.xcarchive/dSYMs/FirebaseCoreDiagnostics.framework.dSYM/Contents/Resources/DWARF/FirebaseCoreDiagnostics matches

**Comment by ryanwilson** [comment]
Hmm, something strange is going on here. `FirebaseCoreDiagnostics` doesn't even import or depend on UIKit. @paulb777 any ideas?

**Comment by ryanwilson** [comment]
Can you grep for code references in your project? I notice these are all dSYMs but the app binary itself has references too.

**Comment by aherbig** [comment]
First of all thanks for trying to help me out a bit ;-)

Yeah, the code in the project does not contain any references to UIWebview any more. I already removed other frameworks that were using the deprecated methods too, like the facebook sdk, or appsflyer...

I just tried without any firebase reference in the last hour and the grep also found a reference in my binary... But I have no clue where this might be coming from.

Btw, I,m still using XCode 12.3 right now. You think that might pose an issue?

**Comment by paulb777** [comment]
Does the project have a pch?

It might help to narrow to use the `nm` tool with `grep` on the binary objects in DerivedData.

**Comment by aherbig** [comment]
I think the reason why I am seeing the firebase dsyms popping up is the same as explained in this thread: https://github.com/mapbox/ios-sdk-examples/issues/373
seems like somewhere I have a reference to an older UIKit version that still includes UIWebview.

Im gonna recheck

**Comment by aherbig** [comment]
@paulb777 

indeed, the project uses a .pch file (from 2014)

`
#import <Availability.h>

#ifndef __IPHONE_3_0
#warning "This project uses features only available in iOS SDK 3.0 and later."
#endif

#ifdef __OBJC__
    #import <UIKit/UIKit.h>
	#import <Foundation/Foundation.h>
    #import "StringConstants.h"
#endif
`

**Comment by aherbig** [comment]
All the grep calls did not provide me with any information where this issue comes from...

I kept removing frameworks/libraries from my project and created archives - and the greps on those archives always found matches for "UIWebView"...  I decided to once again upload an archive to the appstore - and voila.... this time it got accepted even though my terminal still finds matches..... 

I will readd dependencies tomorrow bit by bit and give you an update if I still have issues when including the Firebase frameworks.

Still - thank you so much for your support @ryanwilson & @paulb777

**Comment by ryanwilson** [comment]
Strange, thanks for working with us on it! Keep us in the loop 😄

**Comment by aherbig** [comment]
Hey again.

I almost spent the whole day uploading my app again to see where things went south... seems like my Application still included an old framework dependency (Bolts.framework) that was needed by the facebook sdk that I had already removed.

My grep call still says that it finds a match - but Upload to App-Store works fine now.

> grep -r "UIWebView" .
> Binary file ./AppStore.xcarchive/dSYMs/MyApp.app.dSYM/Contents/Resources/DWARF/MyApp matches

Best Regards
Andy
