### ISSUE TITLE
Adding firebase analytics using cocoapods to xcode project will not build

### ISSUE THREAD

**Issue by smileatom** [firebase/firebase-ios-sdk#7551]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: _____12.3
  * Firebase SDK version: ___current__
  * Installation method: `CocoaPods ` (select one)
  * Firebase Component: _____Firebase Analytics with or without Crashlytics
#### Steps to reproduce:
Close xcode 
add pod 'Firebase/Analytics' to pod file
run pod install
What happened? How can we make the problem occur?
error: unable to spawn process (Argument list too long) trying to run Check Pod Manifest Lock
also even if you disable that script swiftc will fail similarly

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulb777** [comment]
Thanks for the report. We'll likely need a reproducible example to provide help since we thoroughly validate the described use case. 

Also, the version of CocoaPods might be relevant - `pod --version`

**Comment by smileatom** [comment]
Its basically this.  Cocoapods 10.1 as required by firebase
https://stackoverflow.com/questions/53226087/error-unable-to-spawn-process-argument-list-too-long-in-xcode-build

Note that in this SO there is no actual fix, the top rated comment simply says to not use custom xcconfig files by disabling them.  The only workaround I found is to use the "legacy build system" in xcode which is deprecated.

To be clear I dont have that many pod dependencies.  Its not in the category of FAT app.  One of my apps which has custom xccode configs works fine and another with essentially the same setup blows up with the error.

It might be a cocoapods issue but I doubt it since I havent had any issues with cocoapods in these projects going on years.
if I remove firebase the issue goes away.  For now since I would like to be able to use Crashlytics Im using the legacy build system and hoping that doesnt cause other issues.  I think this has come up enough that someone should fix it.

**Comment by paulb777** [comment]
Thanks for the link.

The issue also reported at https://github.com/CocoaPods/CocoaPods/issues/9450. Some of the comments there might help.

I'm willing to investigate more deeply in either CocoaPods or the Firebase Analytics podspec, but would need a reproducible example to do so.

**Comment by smileatom** [comment]
So that issue I will say "sort of", its not just that script, swiftc fails as well if you disable the manifest check.  Also in the other SO you will see that other scripts fail with the same error. There is likely a recursion issue in handling the inputs to any script, as I said my app is not FAT or even close to it.

**Comment by smileatom** [comment]
if I can give you a sanitized project example that reproduces it I will.  The problem with empty projects is that issues like this could fly under the radar due to having just a couple source files.

**Comment by paulb777** [comment]
Agreed - that's why we'll need an example to be able to investigate.

**Comment by smileatom** [comment]
I know it makes me wish I had 100,000 employees
