### ISSUE TITLE
App preview doesn't display app's name, icon, and description based on App Store

### ISSUE THREAD

**Issue by fanbaoyuanbees360** [firebase/firebase-ios-sdk#7578]
I have correctly set the Firebase project's TeamID, BundleID, and App Store ID, and my app is already on the App Store, but app preview doesn't display app's name, icon, and description based on App Store. 

The attached file is Preview with no app name and icon displayed

How should I set it to display APP icon and name in preview?

![IMG_6990 PNG](https://user-images.githubusercontent.com/42194060/108688019-63e99880-7532-11eb-86b0-2f3f848be6f1.JPG)

**Comment by ryanwilson** [comment]
Hi @fanbaoyuanbees360, sorry for the trouble you're seeing.

Can you please fill out the issue template so we can get more information like what SDK version you're using, how you're integrating the SDKs, and ideally iOS versions you're seeing this on?

**Comment by fanbaoyuanbees360** [comment]
Hi @ryanwilson , I created the link using the firebase console, without using any SDK.

Can you tell me what causes the APP name and icon not to be displayed so that I can fix this problem? I have correctly filled in teamId, BundleID and App Store ID. And the "Open" click event will work as usual.

**Comment by ryanwilson** [comment]
Thanks for the info. I'm unfamiliar with this process myself but tagging @eldhosembabu - any idea what's going on here?

**Comment by fanbaoyuanbees360** [comment]
Hi, @eldhosembabu , my project id is "beespilot-test".
Could you please verify my app's configuration?

I'm just using the Firebase Console, without any SDK, to create the link that the preview didn't display the app icon and name, instead a title "Open link in app?"

**Comment by fanbaoyuanbees360** [comment]
Hi, @ryanwilson , I use ios sdk create a link that the preview didn't display the app icon and name, instead a title "Open link in app?".

You can git check from [https://github.com/fanbaoyuanbees360/firebaseDynamicLinkTest.git](url) to run "DynamicLinksExampleSwift".

**Comment by fanbaoyuanbees360** [comment]
The preview can display app icon、name and description normaly.
I haven't done anything. It may take some time to update before displaying the information of the app in the App Store in Preview.
The documentation doesn't mention the time it takes to update the App Store.

I'll close it.
