### ISSUE TITLE
Integrate Firebase inside a pod - No such module 'Firebase'

### ISSUE THREAD

**Issue by CarlSarkisS** [firebase/firebase-ios-sdk#7579]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4 (12D4e)
  * Firebase SDK version: 7.1.0
  * Installation method: CocoaPods
  * Firebase Component: Core / Analytics

### [REQUIRED] Step 2: Describe the problem

_I found a lot of occurrences of this issue on the web, and also on the github issues of this repository. There was never a sample project and no final answer, so the issues were closed after some time of inactivity. I am bringing a sample project here._

I am trying to integrate Firebase Analytics in a pod framework. Client applications will call Firebase exclusively through this pod.

The integration inside the framework is OK.

If y make a pod from it and try to integrate it into an app, i get the error:

> No such module 'Firebase'

If I open the pod framework target build settings and add in the header search path:

> ${PODS_ROOT}/Firebase/CoreOnly/Sources

The error disappears. Then if I try to use Analytics or Crashlytics, I have the error:

> Undefined symbols for architecture x86_64: "_OBJC_CLASS_$_FIRAnalytics"

It was not happening with the previous version 6.32.2

#### Steps to reproduce:

- Create a project with a framework and an app
- create a podspec for the framework
- add Firebase/Analytics as a dependency for the pod
- add your pod as dependency for the app.

Sample project: https://github.com/CarlSarkisS/TestPodFA
The first commit reproduces the "No such module 'Firebase'" issue.
The second one fixes it.
The 3rd one reproduces the "Undefined symbols for architecture x86_64: _OBJC_CLASS_$_FIRAnalytics" issue.

**Comment by maksymmalyhin** [comment]
@CarlSarkisS Thank you for the detailed issue report. 

I can see one issue with your current setup. You are trying to add Firebase Analytics as a dependency to both the framework and the application directly. Firebase Analytics SDK is distributed as a static framework, so this type of integration will lead to symbol duplication and unexpected Firebase behaviour (you can find a bit more details on this issue at the [doc](https://github.com/firebase/firebase-ios-sdk/blob/master/docs/firebase_in_libraries.md)). It becomes even more complicated because open source SDKs are dynamic frameworks by default since Firebase 7. I think this difference leads to the compilation issues you experience. 

The setup I could suggest for your case is:
1. Integrate Firebase only with your framework. If you need to call Firebase from your app (e.g. to log an Analytics event) you can forward calls to Firebase through your framework
2. Make sure all Firebase frameworks are linked statically with your framework by adding `use_frameworks! :linkage => :static` to your podfile. Note, that this will affect linkage behaviour for all Cocoapods dependencies. 

Please let us know if it's helpful.

**Comment by CarlSarkisS** [comment]
Hi Maksym,

If you look at my sample project, Firebase Analytics is integrated only in the pod "PodFA" (target "TestPodFA"). As mentioned in the issue,
> Client applications will call Firebase exclusively through this pod.

I was expecting to be able to use dynamic frameworks with the version 7. I don't get it, why should I get back to static linkage? Do I need then to set back _static_framework=true_ in my podspec?

~~~ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'

target 'TestPodFA' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Firebase/Analytics', '~> 7.1.0'
  pod 'Firebase/Crashlytics', '~> 7.1.0'

end

target 'TestPodFAApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'PodFA', :path => './'

end
~~~

**Comment by maksymmalyhin** [comment]
Ah, sorry, I think I missed a couple details in the sample you provided. Let me take a closer look and get back to you.

**Comment by paulb777** [comment]
One clarification: Only the open source pods in 7.0.0 now support dynamic linking.

FirebaseAnalytics is the exception that is still distributed as a binary static framework and any dependents still need `static_framework=true`

**Comment by maksymmalyhin** [comment]
Here are my observations so far. It looks like currently Cocoapods cannot properly create project for your dynamic framework that depends on static Analytics framework which in its turn depends on dynamic Firebase Core. The only fast and safe workaround for this I could find so far is to add `static_framework=true` in your podspec as you mentioned.

**Comment by CarlSarkisS** [comment]
> One clarification: Only the open source pods in 7.0.0 now support dynamic linking.
> 
> FirebaseAnalytics is the exception that is still distributed as a binary static framework and any dependents still need `static_framework=true`

Oh! That is why. I will try again in static mode then. Thank you for your answer!

It would be probably interesting to mention that on the documentation. Is there a plan to make it also available as a dynamic framework?

**Comment by paulb777** [comment]
We just recently updated the documentation in #7574.  We have no current plans to make Analytics available as a dynamic framework. Feel free to create an issue for that to help us track the interest.

I'll close this now but feel free to continue the conversation.

**Comment by csarkis** [comment]
I still have the issue "No such module Firebase", quite randomly.

It is fixed if I replace it with:
~~~swift
import FirebaseCore
import FirebaseAnalytics
import FirebaseCrashlytics
~~~

Is there any potential issue in doing this?

**Comment by paulb777** [comment]
The Firebase module is a convenience wrapper to allow clients to import all the installed Firebase modules without needing to specify them individually.  So no issue with excluding it if you do the imports individually.
