### ISSUE TITLE
Unable to run my app on Xcode 12 due to conflicting names

### ISSUE THREAD

**Issue by rs658726** [firebase/firebase-ios-sdk#7582]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.6.0
  * Installation method: CocoaPods
  * Firebase Component: Core, Analytics, Crashlytics, Performance

### [REQUIRED] Step 2: Describe the problem

I'm unable to run my app in Xcode 12.4. I'm getting the following types of warnings which I believe lead to a crash on launch:

`Class Event is implemented in both /private/var/containers/Bundle/Application/A0D715D1-7AB6-4647-814B-5A03440B3114/APP.app/Frameworks/Protobuf.framework/Protobuf (0x116f42488) and /private/var/containers/Bundle/Application/A0D715D1-7AB6-4647-814B-5A03440B3114/APP.app/Frameworks/SquareReaderSDK.framework/SquareReaderSDK (0x114517e60). One of the two will be used. Which one is undefined.`

#### Steps to reproduce:

Install Firebase and the SquareReaderSDK frameworks and run the project.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

**Comment by paulb777** [comment]
I'm not totally sure what is going on here, but here's some info that may help:

- There does not seem to be a SquareReaderSDK CocoaPod.  We'll likely need an example to reproduce.
- I don't see an Event class in the Protobuf pod.
- We're planning to remove the Protobuf dependency from Firebase in an upcoming release
- Even before that, the enabling of dynamic frameworks due out in Firebase 7.8.0 may help. See #7570

**Comment by rs658726** [comment]
Thanks for the quick reply, Paul. 
After investigating this further, the crash is due to another warning unrelated to Firebase. It's the same kind of warnings but it pertains to 2 other frameworks.
