### ISSUE TITLE
Combine Support: Test testLinkAndRetrieveDataProviderAlreadyLinked fails

### ISSUE THREAD

**Issue by peterfriese** [firebase/firebase-ios-sdk#7587]
This test fails: 
https://github.com/firebase/firebase-ios-sdk/blob/0144cf0850b82f994eb28b6aee536e1c25a4a532/FirebaseCombineSwift/Tests/Unit/Auth/UserTests.swift#L323

It looks like the mock return condition
https://github.com/firebase/firebase-ios-sdk/blob/0144cf0850b82f994eb28b6aee536e1c25a4a532/FirebaseCombineSwift/Tests/Unit/Auth/UserTests.swift#L359

and the assertion don't match:

https://github.com/firebase/firebase-ios-sdk/blob/0144cf0850b82f994eb28b6aee536e1c25a4a532/FirebaseCombineSwift/Tests/Unit/Auth/UserTests.swift#L371

@ziadtamim can you take a look?

**Comment by ziadtamim** [comment]
@peterfriese Fixed under https://github.com/firebase/firebase-ios-sdk/pull/7592

**Comment by paulb777** [comment]
Closing now that #7592 has merged
