### ISSUE TITLE
Storage metadata returns full path for name

### ISSUE THREAD

**Issue by gvillenave** [firebase/firebase-ios-sdk#761]
When uploading a file to storage, the resolved file object contains metadata such as the name and bucket of the file. However, what I found was that on iOS the name property contains the full path to the file in the bucket, as opposed to just the file name.
Example: for a file uploaded in a bucket to `foo/bar.jpg`, the metadata will give:
```
name: bar.jpg
fullPath: foo/bar.jpg
```
on Android and Web SDK, but 
```
name: foo/bar.jpg
fullPath: foo/bar.jpg
```
on iOS.

From https://github.com/invertase/react-native-firebase/issues/785

**Comment by schmidt-sebastian** [comment]
Thank you for filing this issue. While this is an easy fix, we can't fix this in the current release as this constitutes a breaking change. We will try to get this fixed with the next major release.

**Comment by gvillenave** [comment]
Sounds good, thanks!

**Comment by schmidt-sebastian** [comment]
I started looking at this today. The ReactNative SDK for iOS gets the data for the metadata from `[StorageMetadata dictionaryRepresenation]`. The metadata returned by this function is expressed in the format of Google Cloud Storage - it uses "name" to store the full path. We use the metadata dictionary internally to initialize FIRStorageMetadata and hence we need to make sure that our format and the format of GCS matches. 

The API that directly exposes these properties (`FIRStorageReference.fullPath` and `FIRStorageReference.name`) correctly return either the path or just the name. 

The correct fix is for ReactNative to not rely on the dictionary representation. The Android wrapper already handles this correctly: https://github.com/invertase/react-native-firebase/blob/master/android/src/main/java/io/invertase/firebase/storage/RNFirebaseStorage.java#L505
