### ISSUE TITLE
An internal error has occurred print and inspect the error details for more information

### ISSUE THREAD

**Issue by parthbarot10** [firebase/firebase-ios-sdk#7616]
While verifying phone number Just once face this error for OTP Verification

**Comment by parthbarot10** [comment]
I have integrated Firebase OTP Verification code in my app.
`PhoneAuthProvider.provider().verifyPhoneNumber(fullPhoneNumber, uiDelegate: nil) { verificationID, error in
            stopSpinner()
            if error != nil {
                DLog(error?.localizedDescription as Any)
                showAlert(title: OOPS, message: error!.localizedDescription)
                self.checkAndEnableButton()
                return
            }
}`
Here, I have registered no. many times but once I faced the error "An internal error has occurred print and inspect the error details for more information" and it was faced randomly not every time facing it.

**Comment by paulb777** [comment]
Similar to #5730

**Comment by morganchen12** [comment]
@parthbarot10 can you print out the whole error object instead of just the localized description? That should contain the underlying internal error.
