### ISSUE TITLE
v7.7 crashes at runtime

### ISSUE THREAD

**Issue by trr-amsiq** [firebase/firebase-ios-sdk#7620]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.7
  * Installation method: `Swift Package Manager`
  * Firebase Component: Analytics, Crashlytics, RemoteConfig, Messaging

### [REQUIRED] Step 2: Describe the problem

The application crashes at startup with following error
FIRAnalyticsVersionMismatch: Google Analytics for Firebase version (70500000) does not match with Google App Measurement (70400000) version. Please update.

**Comment by paulb777** [comment]
Hmm, that seems likely to be a stale/inconsistent project state issue.

Would you try **File -> Swift Packages -> Reset Package Caches**

**Comment by trr-amsiq** [comment]
It did not help.

Could it be conflicting with `GoogleAppMeasurement.xcframework` from the `GoogleMobileAds` library?

I have Firebase, GoogleSignIn and GoogleMobileAds in my project.

**Comment by morganchen12** [comment]
Yes, both GoogleMobileAds and FirebaseAnalytics use GoogleAppMeasurement, and they must be resolved to the same version.

**Comment by trr-amsiq** [comment]
So when I update Firebase I need to update GoogleMobileAds at the same time or can I just remove the one oldest one?

**Comment by morganchen12** [comment]
You should update both at the same time (though we're somewhat violating semantic versioning here and it's understandably confusing).

**Comment by paulb777** [comment]
If you use the same package manager for both (CocoaPods or Swift Package Manager), the package manager will make sure they're in sync. If you install them differently, you'll need to make sure the versions match. We don't keep the release cycles between Firebase and GoogleMobileAds sync'ed enough to just always grab latest with different package managers.

**Comment by trr-amsiq** [comment]
I use SPM for Firebase and manually drag GoogleMobileAds into the workspace.
Just updated GoogleMobileAds to 8.1.0 and it is stil conflicting

**Comment by paulb777** [comment]
Likely, you'll need to explicitly install Firebase 7.4.0 (based on the 70400000 message) with SPM to use it with that GoogleMobileAds binary distribution.

Once GoogleMobileAds addresses https://github.com/googleads/googleads-mobile-unity/issues/1125, SPM would then be able to handle the version coordination automatically

**Comment by trr-amsiq** [comment]
I understand.
Thanks for the quick feedback
