### ISSUE TITLE
Unable to upload image to Firebase Storage

### ISSUE THREAD

**Issue by shemishe** [firebase/firebase-ios-sdk#7624]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: **12.4**
  * Firebase SDK version: **7.7.0**
  * Installation method: **CocoaPods**
  * Firebase Component: **Storage**

### [REQUIRED] Step 2: Describe the problem

Unable to upload image to Firebase Storage, I am receiving an error message, "An unknown error occurred, please check the server response."

Prior to this, my app was working perfectly fine, I was able to upload images to multiple references within Storage as well and simultaneously uploading data to Realtime Database. Now after revisiting the app after a day off I am unable to upload images to Storage. Through error handling, I am only getting this error message from the Storage side. I haven't changed any code prior to getting this message nor did I update the pod (previously I was working with Firebase 7.4.0 but have now since updated to 7.7.0), I also did not change any security rules or settings prior to the error message.

#### Steps to reproduce:

Uploading an image to Storage resulting in an unknown error.

#### Relevant Code:

        imageReference.putData(imageData, metadata: nil) { [weak self] metadata, error in
            guard error == nil else {
                print("FAILED TO UPLOAD IMAGE TO STORAGE \(error?.localizedDescription)")
                completion(.failure(StorageError.failedToUpload))
                return
            }

**Comment by choibles** [comment]
Hey, we recently just started seeing this in a production app, along with intermittent "unauthenticated" errors. Admittedly, I am coming from react-native-firebase but we learned that turning off WiFi actually solved the issue (which led me to [this Github issue](https://github.com/firebase/firebase-ios-sdk/issues/4913), which led me to search this repo for more info and finding your issue).

Not sure if it's related to the WiFi security issue, though. Have you tried turning off wifi and attempting to upload again?

**Comment by shemishe** [comment]
Hi @choibles, thanks for the suggestion! You're right! It totally works when I turn off WiFi. I'm not sure what to make of this either. Were you able to find any solutions or work-arounds for this? 

I will try and debug this, hopefully I can produce something useful to bring back!

**Comment by choibles** [comment]
@shemishe what internet provider do you use? The only report I've gotten was in San Francisco using Sonic Internet (and turning off WiFi worked in their case).

I'm sending in a message to Sonic support and linking [this Github issue](https://github.com/firebase/firebase-ios-sdk/issues/4913). It appears Comcast resolved this issue on their side last year.

Also tagging @justkd-google and @morganchen12 as they appear to be representing Firebase in the aforementioned thread. I'm sure a swift resolution will be much more probable if Google/Firebase can contact Sonic. Thanks in advance!

**Comment by shemishe** [comment]
@choibles Thank you for the swift replies. It seems you're much closer to cracking this case than I am haha, because I am using Sonic Internet as well (I am also in the SF area). 

Thanks for linking that Github issue, reading through it as I type this. Hopefully a resolution will come with soon with Sonic.

**Comment by choibles** [comment]
Great! So at least for now it appears this issue may be localized to users of Sonic Internet.

Also started seeing the issue just yesterday. I was actually going insane trying to reproduce the issue on all of my environments, devices, etc. But here I am on AT&T, with zero issues at all. We use a CDN for content delivery from our Firebase storage bucket, so we didn't see any issue in the app pulling down documents, but I asked my friend (on Sonic) to try to access a direct Firebase storage link on WiFi (w/ access token, generated via Firebase storage dashboard), and he wasn't able to load the resource in his browser.

<img width="1251" alt="Screen Shot 2021-02-27 at 2 26 18 PM" src="https://user-images.githubusercontent.com/366828/109402085-c57d7e80-7907-11eb-80da-b33050f9ea3d.png">

Nail in the coffin for issue diagnosis, by my reckoning. Appears all requests to https://firebasestorage.googleapis.com/ may be being blocked for these users.

**Comment by choibles** [comment]
@shemishe Already heard back from Sonic and they said the domain was indeed blocked and they've gone ahead and unblocked it. (Love it! Wasn't expecting that fast and helpful a response, especially on a weekend).

My friend is offline right now, but would be great if you could test and confirm that the issue is fixed? Thanks!

**Comment by shemishe** [comment]
@choibles My apologies, had to step away for a bit. I just did some testing and it indeed works now on WiFi through Sonic, thanks for your help and glad Sonic got back to you so quickly! Let me know if you need anymore testing to confirm.

**Comment by paulb777** [comment]
@shemishe and @choibles Thanks for working through this and sharing with the rest of us! 🥳
