### ISSUE TITLE
duplicate symbol _kSwizzlerAssociatedObjectKey

### ISSUE THREAD

**Issue by luna-moonfang** [firebase/firebase-ios-sdk#7635]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.7.0
  * Installation method: `CocoaPods`
  * Firebase Component: Google Utilities

### [REQUIRED] Step 2: Describe the problem

duplicate symbol '_kSwizzlerAssociatedObjectKey'

Some other library uses this name too. Since it is defined in class `GULSwizzledObject`, a `GUL` prefix could be added and make it become `GULSwizzlerAssociatedObjectKey`.

**Comment by ryanwilson** [comment]
@luna-moonfang thanks for the report.

We'll take a look at renaming the variable. Just out of curiosity, can you please share which framework also declares that symbol? Thanks!
