### ISSUE TITLE
Remote Config won't return the correct values based on a set user property value

### ISSUE THREAD

**Issue by zeusent** [firebase/firebase-ios-sdk#7648]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: > 7.1.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: RemoteConfig

#### Steps to reproduce:

If I update Firebase to any version bigger than 7.1.0 then RemoteConfig stops working as expected.
My app uses an user property value to grab different values from RemoteConfig.

With any version bigger than 7.1.0 this user property value is ignored and RemoteConfig always returns the same
values no matter what. Whenever I rollback to 7.1.0 then everything works as expected.

If I look in the analytics debug view I can see my user property being set correctly.

#### Relevant Code:

On app start, before grabbing any RemoteConfig values I do this:
```
Analytics.setUserProperty("dummy_value", forName: "dummy_property")
```

Immediately after that I call `fetchAndActivate`. This works as expected on 7.1.0 but fails on any newer versions.

**Comment by paulb777** [comment]
@zeusent Sorry about the trouble and thanks for the report and narrowing down the version.

@karenyz Please take a look. I suspect a regression related to #6692.

**Comment by jklein24** [comment]
Hi folks, I believe this is affecting us still. Was there any progress here?

**Comment by jklein24** [comment]
So It's been a bit unreliable and tricky to reproduce, but what we're seeing is essentially the following setup is inconsistent:

- We have one param which has its value set conditionally to true based on a user property
- We have an experiment whose allocation *excludes* users with that user property
- Somehow we're still seeing users with this user property get the param set to false sometimes (but not always). It also seems to change arbitrarily on occasion.

To make it more concrete with an example:
- In remoteconfig, we have a condition setting paramA to true if user property prop1 is true
- We have an experiment config where the targeting explicitly *excludes* prop1 = true, but has variants with paramA true or false

For some reason, we still have users with prop1 true who are getting paramA set to false.

**Comment by MichaelVerdon** [comment]
Hi there, as this is a very old issue with no updates, I am going to be closing this. If you come across anymore issues with remote-config using the latest firebase version, feel free to open a new ticket.
