### ISSUE TITLE
Upgrade to firebase-admin@9.2.0 

### ISSUE THREAD

**Issue by shwetha-mugeraya24** [firebase/firebase-ios-sdk#7657]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.3
  * Firebase SDK version: 7.7.0
  * Installation method: `CocoaPods`
  * Firebase Component: Auth

#### Steps to reproduce:

Vulnerability is found in current firebase-admin through node-forge 0.7.4. Remedy for this to  Upgrade to firebase-admin@9.2.0. But the latest firebase SDK 7.7.0 uses  firebase-admin@8.0.0 version. Can you provide a Firebase release which uses latest firebase-admin@9.2.0 ?
Ref link : https://app.snyk.io/test/npm/firebase-admin/6.5.1

#### Relevant Code:

https://github.com/firebase/firebase-ios-sdk/blob/7.7.0/Functions/Backend/package.json

**Comment by ryanwilson** [comment]
Thanks for the report @shwetha-mugeraya24. From an SDK standpoint we're safe since this is only used for local integration tests using the emulator, but we should still get this resolved for CI and local dev purposes.

**Comment by shwetha-mugeraya24** [comment]
@ryanwilson  So Can I expect a release soon with  firebase-admin@9.2.0 ?

**Comment by ryanwilson** [comment]
@shwetha-mugeraya24 we should be able to do make this change soon and it would be included in not the upcoming release but the one after, likely ~3 weeks away.

That being said - are you using these Functions integration tests locally? Just using the SDK in your product does not use any `npm` modules or the `firebase-admin` SDK at all.
