### ISSUE TITLE
Firestore: Query using equality ("whereField") possible cause of memory leak

### ISSUE THREAD

**Issue by suhabaobaid** [firebase/firebase-ios-sdk#7674]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 12.4 (12D4e)
  * Firebase SDK version: Firebase/CoreOnly (6.34.0), Firebase/Firestore (6.34.0), FirebaseCore (6.10.4), FirebaseFirestore (1.19.0), FirebaseFirestoreSwift (0.4.0)
  * Installation method: `CocoaPods`
  * Firebase Component: `Firestore`

### [REQUIRED] Step 2: Describe the problem
When performing a simple query to firestore involving equality using the `whereField` with either getDocuments or addSnapshotListener, it results in a memory leak and the responsible frame is `firebase::firestore::nanopb::MakeBytesArray(void const*, unsigned long)`

#### Steps to reproduce:

What happened? How can we make the problem occur?

using `db.collection("").whereField("", isEqualTo: "")` causes the leak. Monitoring in a simulator iPhone 11 ios 14.4 (equally leak occuring when monitoring a real device)

<img width="776" alt="Screenshot 2021-03-08 at 9 19 07 AM" src="https://user-images.githubusercontent.com/13656710/110333701-e91f8380-7fef-11eb-8e89-567e58f2fc3f.png">
<img width="416" alt="Screenshot 2021-03-08 at 9 18 55 AM" src="https://user-images.githubusercontent.com/13656710/110333709-ecb30a80-7fef-11eb-93e5-3b97c3c201bf.png">
<img width="1017" alt="Screenshot 2021-03-08 at 8 50 09 AM" src="https://user-images.githubusercontent.com/13656710/110333716-f0469180-7fef-11eb-8c7a-06fdc56821b1.png">

#### Relevant Code:

``` swift
func fetchTasks(for categoryTitle: String, completion: @escaping (Result<Void, TaskError>) -> Void) {
        self.tasks = []
        
        db.collection(K.FStore.Tasks.collectionName)
            .whereField(K.FStore.Tasks.categoryField, isEqualTo: categoryTitle)
            .getDocuments { [weak self] (querySnapshot, error) in
                if let _ = error {
                    completion(.failure(.fetchTasksError))
                    return
                    
                } else {
                    guard let documents = querySnapshot?.documents else {
                        completion(.failure(.fetchTasksEmpty))
                        return
                    }
                    
                    self?.tasks = documents.compactMap { queryDocumentSnapshot -> Task? in
                        return try? queryDocumentSnapshot.data(as: Task.self)
                    }
                    completion(.success(()))
                }
            }
    }
```

Here is a [link to the project](https://github.com/suhabaobaid/Task-Killer). Files where the query is `TaskManager` in the function `fetchTasks`

**Comment by ryanwilson** [comment]
Hi @suhabaobaid - sorry for the issues you're seeing.

Firestore has received many updates since the version you're currently using, including a major version change and an update to nanoPB where it looks like this issue is coming from. Can you please update to the latest version of Firebase (`7.7.0` as of this writing) and see if the leak still occurs?

Thanks!

**Comment by suhabaobaid** [comment]
@ryanwilson Thanks for the swift reply 😃 Leak is gone as per the update

**Comment by ryanwilson** [comment]
@suhabaobaid happy to hear, thanks again for the detailed report and happy Firebase-ing :D
