### ISSUE TITLE
The UI of In-App Messaging popup is broken when system popup is showing

### ISSUE THREAD

**Issue by MichaleTuan** [firebase/firebase-ios-sdk#7692]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: FirebaseInAppMessaging SDK v0.24.0
  * Installation method: `CocoaPods`
  * Firebase Component: Messaging

### [REQUIRED] Step 2: Describe the problem
If the system popup is showing, and then when In-App Messaging come to our app. The UI of In-App Messaging will be broken

Image: https://drive.google.com/file/d/1q4yZ9j5FZXk0fi2sxAtH9Z8LmvSM98cb/view?usp=sharing

#### Steps to reproduce:
- Create In-App Messaging Campaign which is triggered by "view_abc_screen" event
- Making IDFA permission popup is showing (or any other system popup such as asking camera permission,... ) and then send the event named "view_abc_screen"

![Issue](https://user-images.githubusercontent.com/58023771/110615793-60a70b80-81c6-11eb-8558-55e97b098a20.PNG)

#### Relevant Code:

```
[ATTrackingManager requestTrackingAuthorizationWithCompletionHandler:^(ATTrackingManagerAuthorizationStatus status) {
            switch (status) {
                case ATTrackingManagerAuthorizationStatusAuthorized:
                    break;
                default:
                    break;
            }
            completion();
        }];

    [FIRAnalytics logEventWithName:@"view_abc_screen" parameters:@{}];

```

**Comment by christibbs** [comment]
@MichaleTuan thanks for the report. We fixed a similar issue [late last year](https://github.com/firebase/firebase-ios-sdk/issues/6803). Try `pod update`-ing to the latest in-app messaging SDK. Re-open it if it persists.
