### ISSUE TITLE
Swift Package Manager support current state

### ISSUE THREAD

**Issue by gevartosky** [firebase/firebase-ios-sdk#7701]
I noticed the SPM project last update was Dec 11, 2020. I'm sure there is a good reason, but is there any ETA on it? Thank you :)

**Comment by morganchen12** [comment]
Hey @gevartosky, I don't have a lot of specifics to share, but we're working on expanding SPM support and hopefully bringing it out of beta. Are there any particular questions you have?

**Comment by gevartosky** [comment]
Thanks @morganchen12 

@ryanwilson  Yess!! I found it this morning. I was able to install it without issues. Thank you very much 🙏🏻

**Comment by ryanwilson** [comment]
Great, happy to hear! I'll close this since it sounds like we've answered your question. Keep an eye out for any doc updates if you're curious, but should be pretty smooth sailing hopefully :) Thanks!
