### ISSUE TITLE
Propagate signals after handling

### ISSUE THREAD

**Issue by armcknight** [firebase/firebase-ios-sdk#7702]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.3
  * Firebase SDK version: 7.8.0
  * Installation method: `CocoaPods`
  * Firebase Component: Crashlytics

#### Steps to reproduce:

- Initialize Crashlytics
- Register a signal handler to write a simple file for a signal that Crashlytics also handles
- Cause the signal to be issues, like `SIGABRT` with an `abort()` call

##### Expected results

Crashlytics should output its crash logs, and my handler should also output a file.

##### Actual results

- If Crashlytics is registered first, then only Crashlytics receives the signal. It doesn't propagate it, which must be done manually.
- If my handler is registered first, then both my handler and Crashlytics' handler receive the signal. This is because I've implemented signal propagation.

### Solution

I have already implemented and tested a change that works. It tests cases where Crashlytics is the both the first and last component to register a signal handler, and in both cases its ability to write its crash report files is unimpeded. However, my component only receives the signal when it's registered first (it propagates the signal correctly using the fix I'd propose for Crashlytics.)

There were a few other fixes I made as I was in the code, including a log statement that doesn't log the correct signal integer value.

#### Relevant Code:

The target fix is in this part of the code: https://github.com/firebase/firebase-ios-sdk/blob/58eca9695d6dd29d8f6578c85e60f888641ddf04/Crashlytics/Crashlytics/Handlers/FIRCLSSignal.c#L188

You can see how I changed it in my fork: https://github.com/specto-dev/firebase-ios-sdk-1/blob/ac8837fd1c28b8777d02a3ff58ea511098fb928a/Crashlytics/Crashlytics/Handlers/FIRCLSSignal.c#L192-L205

Let me know if this is something you're interested in, it would help it to interact with other software that needs to use signals.

**Comment by elenadoty** [comment]
Hi @armcknight, thanks for the feature request. This isn’t something we think we have the bandwidth to take on soon, but I’ll leave this issue open to gauge interest in it and will comment if there’s any updates.

**Comment by armcknight** [comment]
Thanks @elenadoty! I assume you mean bandwidth for acceptance testing the signal propagation change. Would you like me to split out the other fixes I made, into a separate PR? Of special interest might be the logging and integer signedness fixes. Sorry I didn't link a full diff, here is a draft PR in my fork: https://github.com/specto-dev/firebase-ios-sdk-1/pull/1. I can also open a separate issue for those.

**Comment by elenadoty** [comment]
Hi @armcknight,
The testing was what I meant, yes. We'd be happy to take the other changes though (a separate issue would be best)!

**Comment by elenadoty** [comment]
Implemented proposed fix in #8120. Thanks for the suggestion!
