### ISSUE TITLE
Firebase 7.8.1 direct download `Not Found` error

### ISSUE THREAD

**Issue by marekpridal** [firebase/firebase-ios-sdk#7714]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.8.1
  * Installation method: `Zip file`
  * Firebase Component: Firebase SDK
### [REQUIRED] Step 2: Describe the problem
Unable to download latest Firebase 7.8.1 as zip file from [setup guide](https://firebase.google.com/docs/ios/setup#frameworks). [Provided link doesn't work.](https://github.com/firebase/firebase-ios-sdk/releases/download/7.8.1/Firebase.zip)
#### Steps to reproduce:
Try to download Firebase SDK zip file from [provided link](https://github.com/firebase/firebase-ios-sdk/releases/download/7.8.1/Firebase.zip)

**Comment by ryanwilson** [comment]
Hey @marekpridal - sorry about the troubles here. Version 7.8.1 doesn't have a zip file associated with it, so you can use the 7.8.0 zip link: https://github.com/firebase/firebase-ios-sdk/releases/download/7.8.0/Firebase.zip

Looks like we need to re-evaluate how these patches are made and ensure a zip is provided each time or come up with an alternative. I'll leave this open until we get it resolved.

**Comment by ryanwilson** [comment]
I've uploaded a zip file to the latest release so the link should be resolved now.

Thanks for reporting, we appreciate it and will make sure this doesn't happen in the future!

**Comment by marekpridal** [comment]
Hey @ryanwilson, it seems fine now, thanks a lot for solving this issue even on Sunday!
