### ISSUE TITLE
In-App Messaging via SPM missing resource bundle

### ISSUE THREAD

**Issue by khuffie** [firebase/firebase-ios-sdk#7715]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.8.1
  * Installation method: Swift Package Manager
  * Firebase Component: Analytics, Crashlytics, InAppMessaging, Messaging

#### Steps to reproduce:

I have Firebase integrated via SPM. I am trying to send a test message for In-App Messaging. The device receives the message but I get an error when it attempts to display:

`7.8.1 - [Firebase/InAppMessaging][I-IAM400009] Display ran into error for message 592562000580575232: Error Domain=com.firebase.inappmessaging.display Code=1 "Resource bundle is missing." UserInfo={NSLocalizedDescription=Resource bundle is missing.}
`

#### Relevant Code:

N/A

**Comment by paulb777** [comment]
It looks like the path to the Resources is wrong at https://github.com/firebase/firebase-ios-sdk/blob/master/Package.swift#L595. It should be `../Resources`.

@christibbs Would you validate and if possible, add a regression test to CI?

**Comment by raspu** [comment]
We are facing the same issue here, any workaround? I will try to integrate manually...

**Comment by christibbs** [comment]
@raspu @khuffie I'm working on this currently. When it's resolved we'll likely make a quick patch release for all of our Swift Package Manager users.

**Comment by raspu** [comment]
Thanks @christibbs. I was able to integrate manually, so we are going that way for now. But we would love to move to SPM when available :).

**Comment by ncooke3** [comment]
Hi @khuffie & @raspu,

We've implemented a fix for the issue and it will officially release in Firebase 7.11
Thank you for your patience and don't hesitate to reach out if you run into any further issues! 🙂
