### ISSUE TITLE
Flutter: Unable to build iOS archive after adding "pod 'Firebase/Firestore' " (app runs well though)

### ISSUE THREAD

**Issue by jdeltoft** [firebase/firebase-ios-sdk#7720]
I recently added firebase/firestore to my Flutter app and it worked beautifully on ios and Android to upload files to firebase storage.  But when I went to archive my app to put on the app store, it failed.  I have looked around all over and can't find any way to get the linker to pass successfully.  Here is a quick look at the failures:

![image](https://user-images.githubusercontent.com/4506303/111187548-176a0980-8582-11eb-9604-4ee2fd5892d2.png)

I think the failure has to do with the pods(?) pulled in for firebase and arm64 vs arm7?  But I'm not sure of how to fix this.  I've tried legacy build system, no luck.  I've tried adding armv7 to excluded architectures, no luck.  I've tried just removing the one line in the Podfile:

pod 'Firebase/Firestore'

and after running 'pod update' then it builds.  But of course that's just removing firebase/firestore and I need that for my app to upload files.

**Comment by jdeltoft** [comment]
* Xcode version: Version 12.4 (12D4e)
  * Firebase SDK version: _____
  * Installation method: CocoaPods 
  * Firebase Component: Core, Firestore, Storage

**Comment by jdeltoft** [comment]
In pubspec I pulled in this:

dependencies:
  firebase_core: 0.4.0+8
  firebase_storage: 3.0.4

**Comment by jdeltoft** [comment]
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)

• No issues found!

**Comment by paulb777** [comment]
Perhaps stale Xcode state? Try `rm -rf ~/Library/Developer/Xcode/DerivedData/` and rebuild.

**Comment by jdeltoft** [comment]
does 'flutter clean' work for that?  such as:

```
$ flutter clean
Cleaning Xcode workspace...                                         4.5s
Deleting build...                                                  287ms
Deleting .dart_tool...                                               6ms
Deleting .packages...                                                0ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
Deleting Flutter.podspec...                                          0ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms
```

**Comment by jdeltoft** [comment]
Ok, just deleted everything in that folder, and then xcode wasn't able to build.  Couldn't find the file:

```
Showing Recent Messages
~/AndroidStudioProjects/creamcity/ios/Flutter/Debug.xcconfig:2: could not find included file 'Generated.xcconfig' in search paths
```

build build and test app worked from android studio still. Then after that build I was able to start an archive again.  And this time it worked!!!!  

Thank you @paulb777 !!!!
