### ISSUE TITLE
SwiftUI Phone Auth Error: ERROR_WEB_CONTEXT_ALREADY_PRESENTED

### ISSUE THREAD

**Issue by nidegen** [firebase/firebase-ios-sdk#7743]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4 / Simulator
  * Firebase SDK version: 7.8.1
  * Installation method: `Swift Package Manager`
  * Firebase Component: Auth

### [REQUIRED] Step 2: Describe the problem

When registering a phone number for auth, I get following error message: 
```
 some : Error Domain=FIRAuthErrorDomain Code=17057 "User interaction is still ongoing, another view cannot be presented." UserInfo={NSLocalizedDescription=User interaction is still ongoing, another view cannot be presented., FIRAuthErrorUserInfoNameKey=ERROR_WEB_CONTEXT_ALREADY_PRESENTED}
```

I think this is a bug, but if not it is very misleading, as no web context is shown. Also, I have no explanation what it is that caused an error..

#### Steps to reproduce:

In a SwiftUI view, I have a text field for the phone number and a continue button.

Once the user presses the continue button (enabled when phone number is valid) i call the code below:

#### Relevant Code:

```
 PhoneAuthProvider.provider().verifyPhoneNumber(formattedNumber, uiDelegate: nil) { (verificationID, error) in
      if let error = error {
        print(error.localizedDescription)
        completion(.failure(error))
      } else {
        completion(.success(()))
        UserDefaults.standard.set(verificationID, forKey: self.echoUserVerificationIdKey)
      }
    }
  }
```

**Comment by nidegen** [comment]
It seems to appear when `verifyPhoneNumber` gets called twice. This is a bade usage, but the error seems strange anyways..

**Comment by rizafran** [comment]
Hi @nidegen, could you please share a minimal repro of your issue?
