### ISSUE TITLE
Memory Leak in GoogleDataTransport 

### ISSUE THREAD

**Issue by ibeleliev** [firebase/firebase-ios-sdk#7780]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.9.0
  * Installation method: `CocoaPods`
  * Firebase Component: Crashlytics

#### Steps to reproduce:

Using the profiling instrument - "Leaks" i saw memory leaks regarding GoogleDataTransport.
I'm using the version 8.3.0 . 

#### Relevant Code:
![Screenshot 2021-03-24 at 15 10 49](https://user-images.githubusercontent.com/21360208/112332718-e42a2780-8cb1-11eb-97b2-6642b2cddd75.png)

**Comment by maksymmalyhin** [comment]
Thank you for reporting the issue! The updated GoogleDataTransport version is expected to be released within a couple days after testing.

**Comment by maksymmalyhin** [comment]
The should be fixed on GoogleDataTransport 8.3.1. Please try to update and let us know if you still have the issue.

**Comment by ibeleliev** [comment]
Thanks @maksymmalyhin the issue doesn't appear anymore.
