### ISSUE TITLE
Thread Sanitizer found Data Race in GDTCCTUploadOperation.m:508 in -[GDTCCTUploadOperation finishOperation]

### ISSUE THREAD

**Issue by Jange1l** [firebase/firebase-ios-sdk#7794]
Hello everyone, I am in the process of uploading my app to the app store and there are some bugs that are not caught in the simulator but when I upload my archived version the apple testers say that it crashes after logging in. 

After a deeper look into my code, I noticed that there is a race condition related to some Google code for firebase dependencies.

I could really use some help interpreting what is going on here. I have tried many things to synchronize my code and everything seems to be working perfectly in the simulator.

I don't know if this race condition is the error that is preventing my app from being approved, but I still want to understand what is going on. 

![Screen Shot 2021-03-26 at 3 03 27 PM](https://user-images.githubusercontent.com/31481440/112680967-6d716380-8e44-11eb-83b4-49f654a0ee36.png)

![Screen Shot 2021-03-26 at 3 03 44 PM](https://user-images.githubusercontent.com/31481440/112681003-77936200-8e44-11eb-856f-4d0a59496171.png)

**Comment by rizafran** [comment]
Thanks for reporting, @Jange1l. It seems like the issue you encountered is related here #7771.

**Comment by maksymmalyhin** [comment]
The should be fixed in GoogleDataTransport 8.3.1. Please try to update and let us know if you still have the issue.
