### ISSUE TITLE
'FIRPhoneAuthCredential.h' file not found, tvOS/iOS shared pod

### ISSUE THREAD

**Issue by tooolbox** [firebase/firebase-ios-sdk#780]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.2
  * Firebase SDK version: 4.8.1
  * Firebase Component: Auth
  * Component version: 4.8.1?

### [REQUIRED] Step 3: Describe the problem

The tvOS-target in the Auth podspec excludes files which are needed for the iOS target.

#### Steps to reproduce:

1. Install with CocoaPods, targeting tvOS.
2. Add an iOS target and do another `pod install`.
3. Build for your tvOS target (builds fine).
4. Build for your iOS target, fails on `'FIRPhoneAuthCredential.h' file not found`

#### Relevant Code:

Podfile:
```podspec
use_frameworks!

def shared_pods
    pod 'FirebaseCore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :tag => '4.8.1'
    pod 'FirebaseAuth', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :tag => '4.8.1'
    pod 'FirebaseDatabase', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :tag => '4.8.1'
end

target 'iOS' do
    platform :ios, '9.0'
    shared_pods
    pod 'Hero'
end

target 'tvOS' do
    platform :tvos, '10.0'
    shared_pods
    pod 'ParallaxView'
    pod 'Re-Lax'
end
```

There's a couple of offending import statements; they were different ones the two times I replicated this.  Second time it was FIRPhoneAuthCredential_Internal.h:
```c
#import "FIRPhoneAuthCredential.h"
```
Which was imported by FIRUser.m:
```c
#if TARGET_OS_IOS
#import "FIRPhoneAuthProvider.h"
#import "AuthProviders/Phone/FIRPhoneAuthCredential_Internal.h"
#endif
```

Seems like this issue is caused by the Auth module's podspec excluding these files for a tvOS target.  That's all fine and dandy, but if you have both targets in your project, and the tvOS one was put into CocoaPods first, then those files will be missing when you switch to your iOS target and compile.

As far as I can tell, the podspec should just be edited to include these headers back in because the preprocessor statements exclude the offending files from compiling when you're targeting tvOS.  Have a pull request coming momentarily...

**Comment by paulb777** [comment]
Thanks for the issue and PR.  I don't have too much time to investigate now, but a quick thought   based on the description of adding targets between `pod install` runs:  I suspect you're running into a CocoaPods issue of needing to do a `pod deintegrate` before adding a new target to a Xcode workspace.  CocoaPods names targets differently depending upon if the workspace is mono- or multi-targeted.

**Comment by tooolbox** [comment]
Thanks, that actually solved it.  No need to merge the PR I assume?

**Comment by paulb777** [comment]
👍 Glad it worked! I'll close the PR - #781.
