### ISSUE TITLE
AB testing exclude user 

### ISSUE THREAD

**Issue by AndriyGo** [firebase/firebase-ios-sdk#7800]
### Feature proposal

* Firebase Component: AB testing

Suppose I want to A/B test onboarding redesign for my app. It is easy to set up a RemoteConfig A/B test, and let's suppose that I have two variants: "new" and "old", with "old" being the default one.

I can postpone the loading of my app until remote config fetch is complete. But, if there is no internet, my user will not receive any information about a test group where he/she belongs. Whatever variant I decide to present – my experiment data will get corrupted once a user enlists into some group.

In my opinion, there needs to be a way to exclude a user from experiment, by letting Firebase know that for whatever reason – this user is not a suitable candidate for a test.

**Comment by rizafran** [comment]
Hi @AndriyGo, thanks for filing. It seems that you may use the activation event. As per [docs](https://firebase.google.com/docs/ml/ios/ab-test-models), an activation event is an event the user must trigger before they are considered to be part of the experiment. This looks like a flag that determines if the user will be included in the experiment. To setup, make sure that the fetchAndActivate should be called first before the activation event.

In your use case, if the user is unable to connect, the event shouldn’t be logged even if the user fetches the data, it won’t count. However, the downside is you can still get the value of the experiment when the fetch call was successful.

Let me know if this is the case.
