### ISSUE TITLE
crash in Firebase Crashlytics

### ISSUE THREAD

**Issue by sanjayhub** [firebase/firebase-ios-sdk#7804]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4

  * Firebase SDK version: 7.6.0
  * Installation method: `CocoaPods` 
  * Firebase Component: Crashlytics

#### Steps to reproduce:

crash found in store build 
<img width="1236" alt="Screenshot 2021-03-30 at 9 51 12 AM" src="https://user-images.githubusercontent.com/7887251/112987589-8483be80-9180-11eb-98f0-eb10df8bfd7b.png">
<img width="1234" alt="Screenshot 2021-03-30 at 9 50 47 AM" src="https://user-images.githubusercontent.com/7887251/112987639-95cccb00-9180-11eb-8a66-d1bab16d0968.png">

**Comment by rizafran** [comment]
Thanks for reporting, @sanjayhub. Is the issue reproducible on your end? Also, can you share the full stack trace so we could take a look on what's causing it, and when/which part did the crash occur (e.g app launch, device offline)?
