### ISSUE TITLE
Thread sanitizer detected Data Race in [FPRNetworkTrace responseSize] at 7.9.0

### ISSUE THREAD

**Issue by pot8os** [firebase/firebase-ios-sdk#7805]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.9.0
  * Installation method: `CocoaPods`
  * Firebase Component: See the following list 👇 
 
```ruby
# Podfile
    pod 'Firebase/Core', '~> 7.0'
    pod 'Firebase/Crashlytics'
    pod 'Firebase/Analytics'
    pod 'Firebase/Auth'
    pod 'Firebase/Messaging'
    pod 'Firebase/Functions'
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Performance'
    pod 'Firebase/AdMob'
```

#### Steps to reproduce:

Just running an app that implements the above and configuring them properly. I believe we can regard this as a general issue as far as I read relevant code... probably. Attached a whole stacktrace:

<img width="650" alt="Screen Shot 2021-03-30 at 22 14 29" src="https://user-images.githubusercontent.com/5249113/112995465-384b7500-91a6-11eb-86a1-7ee84afdaac0.png">

`FirebasePerfomance` version is also 7.9.0.

```ruby
# Podfile.lock
  - Firebase/Performance (7.9.0):
    - Firebase/CoreOnly
    - FirebasePerformance (~> 7.9.0)
```

Thanks!

**Comment by rizafran** [comment]
Thanks for reporting, @pot8os. I've tried to reproduce the issue, but it's working fine on my end. Can you share an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) so I could reproduce the issue and check what's causing it?

**Comment by pot8os** [comment]
@rizafran Hello, I tried to reproduce today however it didn't show up again after I've updated several libraries (including Firebase to 7.10.0). So I'm ok to close it.
Sorry for bothering you and thanks for the great library!

**Comment by rizafran** [comment]
No worries, @pot8os. It's good to hear that the issue is not showing up after updating your SDKs. Feel free to reopen if you encountered the issue again. Thanks!
