### ISSUE TITLE
Build Firestore 7.9.0 failed

### ISSUE THREAD

**Issue by jsding** [firebase/firebase-ios-sdk#7815]
### [REQUIRED] Step 1: Describe your environment
  * OSX: 10.15.7
  * Xcode version: 12.4
  * Firebase SDK version: 7.9.0
  * Installation method: CocoaPods
  * Firebase Component: Auth, Core, Firestore, Messaging, RemoteConfig

### [REQUIRED] Step 2: Describe the problem

<path>/Pods/BoringSSL-GRPC/src/crypto/x509/x_name.c:69:10: '../asn1/asn1_locl.h' file not found

#### Steps to reproduce:

Make a empty app, use Firestore 7.9.0

#### Relevant Code:

```
s.dependency 'Firebase/Firestore', 7.9.0
```

**Comment by rizafran** [comment]
Thanks for reporting, @jsding. I've tried to reproduce the issue, but I was able to successfully build my project. Could you share the complete logs you encountered when building the project? You could also try using the [Quickstart for iOS ](https://github.com/firebase/quickstart-ios/tree/master/firestore)and see if the issue will persist.

**Comment by jsding** [comment]
pod deintegrate and pod install not work.

../asn1/asn1_locl.h not found in BoringSSL-GPRC module.

**Comment by paulb777** [comment]
Another possibility is the `sed` command has been changed on the Mac installing the Pods.

See #5623 and #736 for more details and solutions.

**Comment by jsding** [comment]
Thanks for the info. I did not changed sed to gnu-sed. so this should not be the case.

**Comment by paulb777** [comment]
Those issues contain other ideas about investigating.

Ultimately, we'll likely need a reproducible example to help since we don't see the problem in our tests.

**Comment by jsding** [comment]
After upgrading MacOs to 11.2.3 (10.15.7 -> 11.2.3), this build error disappeared.
