### ISSUE TITLE
Add FirebaseFirestoreSwift to Carthage and binary zip package

### ISSUE THREAD

**Issue by GZaccaroni** [firebase/firebase-ios-sdk#7819]
### Feature proposal

* Firebase Component: Firestore (Auth, Core, Database, Firestore, Messaging, Storage, etc)

Describe your use case and/or feature request here.

I want to ask if it is possible to add FirebaseFirestoreSwift to Carthage and binary zip packages added to each release ( https://github.com/firebase/firebase-ios-sdk/releases/tag/CocoaPods-7.2.0 Firebase.zip).

**Comment by paulb777** [comment]
Thanks for the request.  Until we get to this, a workaround is to build it yourself using the ZipBuilder tool at https://github.com/firebase/firebase-ios-sdk/tree/master/ReleaseTooling.

**Comment by GZaccaroni** [comment]
Thank you @paulb777 can I help in the implementation? With ZipBuilder it works like a charm!

**Comment by paulb777** [comment]
@GZaccaroni You're welcome to send a PR. Here are my current thoughts about what an implementation would look like:

- Add a `hasSwift` boolean to https://github.com/firebase/firebase-ios-sdk/blob/master/ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift that is true for Firestore.
- If the flag is true, add FirebaseFirestoreSwift to the generated Podfile that is used to construct the Firestore folder.
- Validate that the only difference when building the Firebase zip and Carthage distributions is the addition of the FirebaseFirestoreSwift.xcframework - ` swift run zip-builder --update-pod-repo --keep-build-artifacts`
- Validate that the new xcframeworks works correctly

**Comment by paulb777** [comment]
Added to the Firebase 9 milestone, even though It doesn't necessarily need to wait for that.

**Comment by paulb777** [comment]
Merged implementation today into v9 branch and will be available in Firebase 9.0.0 due out in the next few months.
