### ISSUE TITLE
184767764: FR: Make Dynamic Links work on macOS

### ISSUE THREAD

**Issue by alobaili** [firebase/firebase-ios-sdk#7829]
### Feature proposal

* Firebase Component: Dynamic Links

Currently [Firebase Dynamic Links is not supported in native macOS apps](https://github.com/firebase/firebase-ios-sdk/discussions/7826#discussioncomment-563096). It would be great to make it supported so that I can use the convenience of the Dynamic Links feature to support Universal Links for my macOS app without having to set up my own server.

**Comment by eldhosembabu** [comment]
Tracking internal bug: https://b.corp.google.com/issues/184767764

**Comment by deimantasa** [comment]
Any updates on this one?

**Comment by paulb777** [comment]
Now that [Firebase DynamicLinks is planned to shut down](https://firebase.google.com/support/dynamic-links-faq), closing its feature requests.
