### ISSUE TITLE
Firebase* Swift imports not working on integrating framework depending upon Firebase itself

### ISSUE THREAD

**Issue by mohsinulhaq** [firebase/firebase-ios-sdk#7856]
### Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.2.0
  * Installation method: `CocoaPods`
  * Firebase Component: (Auth, Core, Database, Firestore, Messaging, Storage, etc)

### Describe the problem
I have a Cocoapods Swift framework that depends on Firebase (Core, Database, Storage, and a few others). I'm trying to add that framework to my app that also depends on Firebase via `react-native-firebase`. After I added the framework to my app and tried to build the app, I get the following error for all `Firebase*` imports in the Framework's Swift code:

```
No such module 'FirebaseCore'
No such module 'FirebaseAuth'
...
```
I tried cleaning everything, from node_modules to build folder to derived data.
I also tried using `$RNFirebaseAsStaticFramework = true`.
But nothing worked for me.

Please point me in the right direction.

**Comment by rizafran** [comment]
Thanks for reporting, @mohsinulhaq. Can you try to update your SDK to the latest one and see if that would fix the issue? If not, can you share your Podfile or a project that reproduces this issue?

**Comment by mohsinulhaq** [comment]
https://github.com/mohsinulhaq/Swift-Firebase-Framework-error
@rizafran here's a repro for the issue, for easy development, I have put the Framework in the `ios/TestFramework` folder instead of another GitHub repo.

Run `yarn`. post-install hook handles the pod installation.

Once installation completes, building the app will produce the above error of it not able to compile the Swift files in the framework (test.swift in my framework):
![image](https://user-images.githubusercontent.com/7688231/114032753-3c5c4e80-989a-11eb-8815-67bafb3c75ed.png)


I also tried the same process by using various versions all the way up to the latest (7.9.0).
For all versions from my current one (7.2.0) to 7.8.0, the error I get is the same. But weirdly for 7.9.0, the error changes to failing on some random Firebase pod everytime I try to build the app, like FirebaseInstallations or FirebaseStorage, as shown in the screenshot:
<img width="573" alt="Screenshot 2021-04-08 at 6 20 08 PM" src="https://user-images.githubusercontent.com/7688231/114032579-120a9100-989a-11eb-8003-248931fb6752.png">
<img width="572" alt="Screenshot 2021-04-08 at 6 20 35 PM" src="https://user-images.githubusercontent.com/7688231/114032596-15058180-989a-11eb-80b4-77867a691e67.png">

**Comment by morganchen12** [comment]
@mohsinulhaq this looks like you may just need to update the header search paths in the xcconfig of the pod you're creating.
