### ISSUE TITLE
Firebase support for AdServices Framework? 

### ISSUE THREAD

**Issue by ssense-eric** [firebase/firebase-ios-sdk#7860]
Reopening discussion from: https://github.com/firebase/firebase-ios-sdk/issues/7369

Apple released a new framework for iOS 14.3+, aimed to attribute app-download campaigns that originate from the App Store, Apple News, or Stocks on iOS devices. 

From my understanding, this new framework that will be replacing the iAd framework. I'm wondering if the Firebase SDK will be adopting it with firebase_campaign and conversion event attribution integrated just like iAd. 

Doc: https://developer.apple.com/documentation/adservices

**Comment by Harween-TZ** [comment]
Hello,

we have received the same email from Apple Services. We would also like to know if AdServices is or will be managed by Firebase SDK.

Thank you very much in advance.

**Comment by RRomainK** [comment]
Same concern here.

**Comment by htcgh** [comment]
Thanks all for reporting. Our team is working on an integration w/ the AdServices framework, but we don't have an ETA yet.

**Comment by timbo-tj** [comment]
Is there an update on this? The deadline has passed and now we all of our attribution and conversion tracking will stop working until this is resolved - is this correct?

We've stopped running Google Ads targeting iOS devices since we can't track conversions any more.  Hoping for a fix soon.

**Comment by htcgh** [comment]
We added support for AdServices in version 10.6.0.

**Comment by nyapster** [comment]
@htcgh is there any documentation about what fields Firebase tracks? Is it everything listed in the [AdServices payload](https://developer.apple.com/documentation/ad_services/aaattribution/3697093-attributiontoken#3697463)? Can’t seem to find any docs on this.
