### ISSUE TITLE
Custom UI based InAppMessaging does not event correctly

### ISSUE THREAD

**Issue by henryglendening-hh** [firebase/firebase-ios-sdk#7866]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.9.0
  * Installation method: `CocoaPods `
  * Firebase Component: InAppMessaging/ABTesting

### [REQUIRED] Step 2: Describe the problem

When using a custom view controller to present in-app messages, the delegate will effectively receive the callbacks when buttons are tapped (by calling those functions on the delegate, from within the button actions of the custom VC), however Firebase does not record any events.

This presents an issue in two ways:
1. The A/B Test experiment does not indicate that any impressions/users/data exists or has been recorded.
2. When trying to trigger another event for an in-app message to be delivered, the message is not received by the app and the following error is logged: `7.9.0 - [Firebase/InAppMessaging][I-IAM400008] An in-app message display is in progress, do not check analytics event based message for now` 

#### Steps to reproduce:

1. Assign `messageDisplayComponent` to custom class
2. Implement `displayMessage(_ messageForDisplay: InAppMessagingDisplayMessage, displayDelegate: InAppMessagingDisplayDelegate)` in custom class, where implementation creates and presents a custom view controller (for `InAppMessagingCardDisplay` messages that contain 'dismiss' actions for each button)
3. As a user, run the app and tap on one of the buttons when the custom view controller is presented.

**Comment by christibbs** [comment]
@henryglendening-hh Thanks for reporting. Could you provide example code for how you're handling a click or dismiss?

Just a snippet from the `UIButton`s' assigned actions will suffice.

**Comment by henryglendening-hh** [comment]
@christibbs Thank you for taking a look at this. 

Essentially, I'm just calling `firebaseInAppMessaging.triggerEvent("myEvent")` when a button is pressed, in order to trigger displaying a successive message/screen. When a message is received from Firebase in `func displayMessage(_ messageForDisplay: InAppMessagingDisplayMessage, displayDelegate: InAppMessagingDisplayDelegate)`, I create a new custom VC for displaying the message, and then push it on a navigation controller.

As context, I'm using navigation controller presented modally, and the custom VC's that are used for displaying in-app messages are pushed to this navigation controller.

That being said, Firebase thinking that the first in-app message display is still in progress makes sense - technically it is, as I haven't done anything to indicate to Firebase that I'm done with the message display other than my attempt to trigger a new message/event. Unfortunately, I've been unable to find any functionality in the SDK to otherwise communicate to Firebase that the message's display is no longer "in progress". I've tried having the button action call functions on the `InAppMessagingDisplayDelegate` directly (`messageDismissed(:)` or `messageClicked(:)`), but I still get error `I-IAM400008` (and I'm pretty sure it's not intended for me to call the `InAppMessagingDisplayDelegate` functions directly anyhow).

**Comment by christibbs** [comment]
You actually do need to call the delegate methods within your custom VC. Aside from metrics, that resets the flag that you're getting tripped up at (see [dismiss flow](https://github.com/firebase/firebase-ios-sdk/blob/6eaf76142b670c0bb35869ef1cbb8e064b74ac93/FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayExecutor.m#L170), for example but the same thing happens for a click).

In your implementation of `displayMessage(_ :displayDelegate:)`, hold a **strong** reference to the `displayDelegate` object that gets passed. Then call `messageDismissed(:)` or `messageClicked(:)` on it. This should log metrics and reset the message displayed flag.

**Comment by henryglendening-hh** [comment]
Ah, perfect thank you! I did not realize that the `displayDelegate` inside of `displayMessage(_ :displayDelegate:)` is different than the `displayDelegate` that I assigned to `InAppMessaging.inAppMessaging().delegate` (when initially configuring Firebase). Using the `displayDelegate` from the `displayMessage(:)` parameter now triggers the event appropriately.

Thank you for your support!

**Comment by christibbs** [comment]
Anytime. 

BTW, if you have any SwiftUI projects check out our extension for building custom in-app messages in SwiftUI: https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseInAppMessagingSwift.podspec.
