### ISSUE TITLE
Deprecated properties in FPRProtoUtils.m 

### ISSUE THREAD

**Issue by ashvinajadiya** [firebase/firebase-ios-sdk#7873]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.10.0
  * Installation method: CocoaPods
  * Firebase Component: Analytics

### [REQUIRED] Step 2: Describe the problem
Properties are deprecated,
'**subscriberCellularProvider**' is deprecated: first deprecated in iOS 12.0
'**currentRadioAccessTechnology**' is deprecated: first deprecated in iOS 12.0
#### Steps to reproduce:
This deprecated properties if from many versions

#### Relevant Code:
  NSString *networkString = FPRNetworkInfo().currentRadioAccessTechnology;
  CTCarrier *provider = networkInfo.subscriberCellularProvider;

**Comment by paulb777** [comment]
Note that Firebase still supports iOS 10 and higher and changing the minimum versions on the build settings in the Pods Xcode project generated by CocoaPods can expose warnings liked this.

**Comment by visumickey** [comment]
Give the nature of backward compatibility of Firebase SDKs, it is hard to go away from this deprecated warning. We can include a "no warning tag" for the compiler to ignore that message, but that would make the users unaware of the usage.

So, closing this bug without a fix.
