### ISSUE TITLE
fetchAndActivateWithCompletionHandler does not return FIRRemoteConfigFetchAndActivateStatusSuccessUsingPreFetchedData when activateWithCompletion detects last fetched config is already activated

### ISSUE THREAD

**Issue by khaptonstall** [firebase/firebase-ios-sdk#7877]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.9.0
  * Installation method: `CocoaPods`
  * Firebase Component: RemoteConfig

#### Steps to reproduce:
Call `.fetchAndActivate` 2+ times while being under the `minimumFetchInterval`.

What happened? How can we make the problem occur?
I'm using the `fetchAndActivate` method and it's completing without an error, however I'm seeing that the status being returned is **always** `successFetchedFromRemote`. This makes sense for the first call to `fetchAndActivate`, but not for each subsequent call within the `minimumFetchInterval`.

When debugging inside `FIRRemoteConfig.m`, I see I'm hitting the following block of code in `activateWithCompletion`:
```
  // Check if the last fetched config has already been activated. Fetches with no data change are
    // ignored.
    if (strongSelf->_settings.lastETagUpdateTime == 0 ||
        strongSelf->_settings.lastETagUpdateTime <= strongSelf->_settings.lastApplyTimeInterval) {
      FIRLogDebug(kFIRLoggerRemoteConfig, @"I-RCN000069",
                  @"Most recently fetched config is already activated.");
      if (completion) {
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
          completion(NO, nil);
        });
      }
      return;
    }
```

which then triggers the following block of code in `fetchAndActivateWithCompletionHandler`:
```
          [strongSelf activateWithCompletion:^(BOOL changed, NSError *_Nullable activateError) {
            if (completionHandler) {
              FIRRemoteConfigFetchAndActivateStatus status =
                  activateError ? FIRRemoteConfigFetchAndActivateStatusSuccessUsingPreFetchedData
                                : FIRRemoteConfigFetchAndActivateStatusSuccessFetchedFromRemote;
              dispatch_async(dispatch_get_main_queue(), ^{
                completionHandler(status, nil);
              });
            }
          }];
```

It looks like the `changed` boolean is never checked, and instead `FIRRemoteConfigFetchAndActivateStatusSuccessUsingPreFetchedData` is only returned if an activation error occurred.

Should this also return a status of `FIRRemoteConfigFetchAndActivateStatusSuccessUsingPreFetchedData` if `changed == NO`? Or am I misinterpreting the meaning of `FIRRemoteConfigFetchAndActivateStatusSuccessUsingPreFetchedData`?

#### Relevant Code:

Here's the code I'm running:
```
let settings = RemoteConfigSettings()
settings.minimumFetchInterval = 3600

let remoteConfig = RemoteConfig.remoteConfig()
remoteConfig.configSettings = settings
remoteConfig.setDefaults(fromPlist: "plist-file-name")

remoteConfig.fetchAndActivate { status, error in
    // Status is always `.successFetchedFromRemote`
}
```

**Comment by antonjn** [comment]
+1 On this one (I have same issue and same questions).

**Comment by rizafran** [comment]
Thanks for reporting this issue. To isolate, could you try reproducing the issue using the latest version of SDK?

**Comment by khaptonstall** [comment]
@rizafran Just confirmed the issue originally reported is still occurring in Firebase 8.1.1.
