### ISSUE TITLE
Custom In App Messaging Shown Multiple Times

### ISSUE THREAD

**Issue by AdamBCo** [firebase/firebase-ios-sdk#7878]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.8.0
  * Installation method: cocoapods
  * Firebase Component: InAppMessaging

### [REQUIRED] Step 2: Describe the problem

I recently followed the documentation found [here](https://firebase.google.com/docs/in-app-messaging/customize-messages?platform=ios) to create a custom UI for Firebase In App Messaging.

When I create a campaign whose **Per-device frequency limit** is set to **Once per device for this campaign** I see the In App Message every-time I launch the application.

The documentation is limited on how to achieve this result, so I'm wondering if there's anything wrong with the sample code below. For example, I don't think my code is properly communicating impressions and clicks to the Firebase SDK, which could be the culprit. 

Any help on this issue would greatly be appreciated.

#### Steps to reproduce:

- Using the code below in my iOS Application, I create an In App Messaging campaign whose **Per-device frequency limit** is set to **Once per device for this campaign**.
- I launch the campaign and open my device to see the in app message appear.
- I kill the application and open it again to see the in app message again.

#### Relevant Code:

```swift

import UIKit
import FirebaseInAppMessaging
import FirebaseAnalytics

class TestViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        InAppMessaging.inAppMessaging().messageDisplayComponent = self
    }
}

// MARK: - InAppMessagingDisplay

extension TestViewController: InAppMessagingDisplay {

    public func displayMessage(_ messageForDisplay: InAppMessagingDisplayMessage, displayDelegate: InAppMessagingDisplayDelegate) {
        if let message = messageForDisplay as? InAppMessagingCardDisplay {
            let modalViewController = TestCardViewController(messageForDisplay: message, displayDelegate: self)
            UIApplication.shared.keyWindow?.rootViewController?.present(modalViewController, animated: true)
        }
    }
}

// MARK: - InAppMessagingDisplayDelegate

extension TestViewController: InAppMessagingDisplayDelegate {

    func messageClicked(_ inAppMessage: InAppMessagingDisplayMessage, with action: InAppMessagingAction) {
        guard let url = action.actionURL else { return }
        UIApplication.shared.open(url)
    }
    
    func impressionDetected(for inAppMessage: InAppMessagingDisplayMessage) {
        print("Impression")
    }

    func displayError(for inAppMessage: InAppMessagingDisplayMessage, error: Error) {
        log.errorMessage(error.localizedDescription)
    }

}
```
```swift

import UIKit
import FirebaseInAppMessaging
import FirebaseAnalytics

class TestCardViewController: UIViewController {

    // MARK: - Data Properties

    private let inAppMessagingCardDisplay: InAppMessagingCardDisplay
    private weak var inAppMessagingDisplayDelegate: InAppMessagingDisplayDelegate?

    // MARK: - Initializer

    init(messageForDisplay: InAppMessagingCardDisplay, displayDelegate: InAppMessagingDisplayDelegate) {
        self.inAppMessagingCardDisplay = messageForDisplay
        self.inAppMessagingDisplayDelegate = displayDelegate
        super.init(nibName: nil, bundle: nil)
        self.modalTransitionStyle = .crossDissolve
        self.modalPresentationStyle = .overCurrentContext
    }

    @available(*, unavailable)
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let label = UILabel(frame: CGRect(x: 0, y: 0, width: 200, height: 40))
        label.text = inAppMessagingCardDisplay.title
        view.addSubview(label)
        
        let button = UIButton(frame: CGRect(x: 0, y: 40, width: 200, height: 40))
        button.setTitle(inAppMessagingCardDisplay.primaryActionButton.buttonText, for: .normal)
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        inAppMessagingDisplayDelegate?.impressionDetected?(for: inAppMessagingCardDisplay)
    }

    // MARK: - Actions

    @objc private func onPrimaryButtonPressed() {
        dismiss(animated: true, completion: nil)
        
        let action = InAppMessagingAction(actionText: inAppMessagingCardDisplay.primaryActionButton.buttonText, actionURL: inAppMessagingCardDisplay.primaryActionURL)
        inAppMessagingDisplayDelegate?.messageClicked?(inAppMessagingCardDisplay, with: action)
    }

}
```

**Comment by christibbs** [comment]
@AdamBCo My intuition here, just looking at the code is that the retain count on your `inAppMessagingDisplayDelegate` object goes to 0  after the dust settles [here](https://github.com/firebase/firebase-ios-sdk/blob/6eaf76142b670c0bb35869ef1cbb8e064b74ac93/FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayExecutor.m#L673). Since it goes to 0, it will end up being released from memory, making it `nil` by the time you need it for reporting impressions in `viewDidLoad`. This will result in the impression not being logged, and the SDK assuming that the message hasn't been shown.

To fix this, you'd need to have a strong reference (which will keep the retain count for the delegate at 1 while `TestCardViewController` is still in the heap). Just remove `weak` to make it a strong reference.

`private var inAppMessagingDisplayDelegate: InAppMessagingDisplayDelegate?`

I'm going to do a full smoke test of the custom UI implementation since we got another report on that flow (#7866) but try this in the meantime. It's the rare occasion when you use a strong reference on something called a delegate in Apple development 😃.

**Comment by AdamBCo** [comment]
@christibbs Thanks so much for taking the time to help me with this issue! I definitely appreciate it. 😁

I just removed the **weak** reference from the inAppMessagingDisplayDelegate and still running into issues where the In App Message continues to show even though it's now a **strong** reference.

I'm also seeing the following message in the terminal, which may or may not be helpful.
`[Firebase/InAppMessaging][I-IAM270005] No impression records update due to no change after applying the server message list`

If you have any other recommendations, please let me know. I'd also love to see what your implementation of a CustomInApp MessagingViewController looks like, so please keep me posted on your smoke test.

**Comment by christibbs** [comment]
@AdamBCo 

So I made the most basic of basic implementations and it seemed to work (shows the alert only once).

```
func displayMessage(_ messageForDisplay: InAppMessagingDisplayMessage,
                      displayDelegate: InAppMessagingDisplayDelegate) {
    guard let modalMessage = messageForDisplay as? InAppMessagingModalDisplay,
          let bodyText = modalMessage.bodyText else {
      return
    }
    
    let alert = UIAlertController(title: modalMessage.title,
                                  message: bodyText,
                                  preferredStyle: .alert)
    alert.addAction(UIAlertAction(title: "Dismiss", style: .cancel, handler: { _ in
      displayDelegate.messageDismissed?(messageForDisplay, dismissType: .typeUserTapClose)
    }))
    
    present(alert, animated: true) {
      displayDelegate.impressionDetected?(for: messageForDisplay)
    }
  }
```

You seem to be doing all of the things I'm doing here, though-- calling the impression callback and the dismiss callbacks. I did notice one strange log though. Do you get this? Could explain the "No impression record" log you're getting.

`7.10.0 - [Firebase/InAppMessaging][I-IAM280002] Firebase In App Messaging was not configured with FirebaseAnalytics.`

**Comment by AdamBCo** [comment]
@christibbs After looking at your code, I **MIGHT** have figured out the issue.

In my sample code, you can see that I am passing **self** as the displayDelegate for the TestCardViewController. In your code, you are using the displayDelegate passed via the displayMessage function. Once I changed **self** to **displayDelegate**, I stopped seeing the In App Message repeatedly. Any idea why?


    public func displayMessage(_ messageForDisplay: InAppMessagingDisplayMessage, displayDelegate: InAppMessagingDisplayDelegate) {
        if let message = messageForDisplay as? InAppMessagingCardDisplay {
            let modalViewController = TestCardViewController(messageForDisplay: message, displayDelegate: self)
            UIApplication.shared.keyWindow?.rootViewController?.present(modalViewController, animated: true)
        }
    }

vs 


    public func displayMessage(_ messageForDisplay: InAppMessagingDisplayMessage, displayDelegate: InAppMessagingDisplayDelegate) {
        if let message = messageForDisplay as? InAppMessagingCardDisplay {
            let modalViewController = TestCardViewController(messageForDisplay: message, displayDelegate: displayDelegate)
            UIApplication.shared.keyWindow?.rootViewController?.present(modalViewController, animated: true)
        }
    }

**Comment by christibbs** [comment]
Ah... yeah I totally missed that. So the `displayDelegate` that comes in from `displayMessage(_:displayDelegate)` is responsible for reporting metrics. It's a class that's internal to the SDK (ends up being [this class](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayExecutor.m)). Your 2nd code block is correct.

Now that you mention it, the naming is kind of confusing. Might be better to call it `metricsHandler` or something like that. I'll consider changing it with the next breaking release.

**Comment by christibbs** [comment]
Closing this for now, since you have the right idea.
