### ISSUE TITLE
Preview in Swift is broken

### ISSUE THREAD

**Issue by maxiedaniels** [firebase/firebase-ios-sdk#7879]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  *  Firebase SDK version: 7.10
  * Installation method: `CocoaPods
  * Firebase Component: importing Firebase, so Core?

#### Steps to reproduce:

What happened? How can we make the problem occur?
Once I imported Firebase, previews stopped working. The error is in 'FirebaseCoreDiagnostics', a bunch of 'Umbrella header for module 'GoogleDataTransport' does not include header 'GDTCOR[Registrar/StorageEventSelector/etc].h'. Lastly, it says parse issue: 'could not build module GoogleDataTransport'.

#### Relevant Code:
All previews fail, doesn't matter if it's my own code or a hello world.

**Comment by paulb777** [comment]
I'm not able to reproduce. It's possible something about your installation has been corrupted.  I recommend `pod deintegrate` and `pod install` and clearing DerivedData.

If that doesn't help, please send a reproducible example.

![Screen Shot 2021-04-11 at 7 17 19 AM](https://user-images.githubusercontent.com/73870/114307799-fec41500-9a95-11eb-98e0-f0cca0f606f1.png)

**Comment by adamcumiskey** [comment]
@maxiedaniels Had a similar issue in my project that was solved by this: https://stackoverflow.com/a/58973469
