### ISSUE TITLE
Collection <__NSArrayM: XXX> was mutated while being enumerate

### ISSUE THREAD

**Issue by ZsIsMe** [firebase/firebase-ios-sdk#7882]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: __6.34.0___
  * Installation method: `CocoaPods ` 
  * Firebase Component: ___Core, Messaging, RemoteConfig,_ DynamicLinks, Performance, Crashlytics, FirebaseAnalytics_ 

### [REQUIRED] Step 2: Describe the problem
I got  [**Collection <__NSArrayM: 0x280f557d0> was mutated while being enumerate**] every day from firebase Crashlytics but I don't know why. Maybe you have fixed this bug but I don't know which Component should I update., please help.Thank you.
Crash stack 1:
Fatal Exception: NSGenericException  
0  CoreFoundation                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 0x1bbb29344&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; __exceptionPreprocess  
1  libobjc.A.dylib                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1bb83ecc0 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;objc_exception_throw
2  CoreFoundation                 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1bbb28ca0 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-[__NSSingleObjectEnumerator initWithObject:collection:]
3  car8891                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x100abbdc4 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;GADJSONSafeDictionary
4  car8891                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x100abbc4c &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;GADJSONSafeDictionary
5  libswiftCore.dylib             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1c95bcf30 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;specialized _SwiftDeferredNSDictionary.enumerateKeysAndObjects(options:using:)
6  libswiftCore.dylib             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1c9381f74 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@objc _SwiftDeferredNSDictionary.enumerateKeysAndObjects(options:using:)
7  car8891                       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 0x100abbb48 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;GADJSONSafeDictionary
8  car8891                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x100abbd04 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;GADJSONSafeDictionary
9  car8891                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x100abbc4c &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;GADJSONSafeDictionary
10 CoreFoundation                 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1bbb79958 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;__NSDICTIONARY_IS_CALLING_OUT_TO_A_BLOCK__
11 CoreFoundation                 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1bb9fa2b0 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]
12 car8891                       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 0x100abbb48 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;GADJSONSafeDictionary
13 car8891                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x100b0c680 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;GAD_GADSignals_arm64_7_64_0
14 car8891                       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 0x100b0c8dc &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;GAD_GADSignals_arm64_7_64_0
15 libdispatch.dylib              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1bb7ca134 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_dispatch_call_block_and_release
16 libdispatch.dylib              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1bb7cb5ac&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _dispatch_client_callout
17 libdispatch.dylib              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1bb7cda1c&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _dispatch_queue_override_invoke
18 libdispatch.dylib              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1bb7da724 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_dispatch_root_queue_drain
19 libdispatch.dylib              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1bb7daed0 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_dispatch_worker_thread2
20 libsystem_pthread.dylib        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1bb8316dc &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_pthread_wqthread
21 libsystem_pthread.dylib        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1bb8379c8 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;start_wqthread

Crash stack 2:
Crashed: com.google.firebase.crashlytics.ios.exception
0  car8891                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1008bd0ec &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FIRCLSProcessRecordAllThreads + 392 (FIRCLSProcess.c:392)
1  car8891                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1008bd4d0 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FIRCLSProcessRecordAllThreads + 423 (FIRCLSProcess.c:423)
2  car8891                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1008b3e80&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; FIRCLSHandler + 34 (FIRCLSHandler.m:34)
3  car8891                       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 0x1008afb3c &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;__FIRCLSExceptionRecord_block_invoke + 218 (FIRCLSException.mm:218)
4  libdispatch.dylib              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1bb7cb5ac &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_dispatch_client_callout + 20
5  libdispatch.dylib              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1bb7d8360 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_dispatch_lane_barrier_sync_invoke_and_complete + 60
6  car8891                       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1008af2d4 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FIRCLSExceptionRecord + 225 (FIRCLSException.mm:225)
7  car8891                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1008af5cc &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FIRCLSExceptionRecordNSException + 111 (FIRCLSException.mm:111)
8  car8891                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;x1008aeeb4 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FIRCLSTerminateHandler() + 279 (FIRCLSException.mm:279)
9  libc++abi.dylib                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1bb8e340c &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::__terminate(void (*)()) + 20
10 libc++abi.dylib                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1bb8e3398 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::terminate() + 44
11 libobjc.A.dylib                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1bb83ef24 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_objc_terminate() + 14
12 libdispatch.dylib              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1bb7cb5c0 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_dispatch_client_callout + 40
13 libdispatch.dylib              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1bb7cda1c&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _dispatch_queue_override_invoke + 672
14 libdispatch.dylib              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1bb7da724 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_dispatch_root_queue_drain + 348
15 libdispatch.dylib              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1bb7daed0 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_dispatch_worker_thread2 + 116
16 libsystem_pthread.dylib        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1bb8316dc &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_pthread_wqthread + 216
17 libsystem_pthread.dylib        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x1bb8379c8 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;start_wqthread + 8

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

My Pod.lock info :
`- Firebase/Core (6.34.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.9.0)
  - Firebase/CoreOnly (6.34.0):
    - FirebaseCore (= 6.10.4)
  - Firebase/Crashlytics (6.34.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 4.6.2)
  - Firebase/DynamicLinks (6.34.0):
    - Firebase/CoreOnly
    - FirebaseDynamicLinks (~> 4.3.1)
  - Firebase/Messaging (6.34.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 4.7.1)
  - Firebase/Performance (6.34.0):
    - Firebase/CoreOnly
    - FirebasePerformance (~> 3.3.1)
  - Firebase/RemoteConfig (6.34.0):
    - Firebase/CoreOnly
    - FirebaseRemoteConfig (~> 4.9.1)
  - FirebaseABTesting (4.2.0):
    - FirebaseCore (~> 6.10)
  - FirebaseAnalytics (6.9.0):
    - FirebaseCore (~> 6.10)
    - FirebaseInstallations (~> 1.7)
    - GoogleAppMeasurement (= 6.9.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.7)
    - GoogleUtilities/MethodSwizzler (~> 6.7)
    - GoogleUtilities/Network (~> 6.7)
    - "GoogleUtilities/NSData+zlib (~> 6.7)"
    - nanopb (~> 1.30906.0)
  - FirebaseCore (6.10.4):
    - FirebaseCoreDiagnostics (~> 1.6)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Logger (~> 6.7)
  - FirebaseCoreDiagnostics (1.7.0):
    - GoogleDataTransport (~> 7.4)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Logger (~> 6.7)
    - nanopb (~> 1.30906.0)
  - FirebaseCrashlytics (4.6.2):
    - FirebaseCore (~> 6.10)
    - FirebaseInstallations (~> 1.6)
    - GoogleDataTransport (~> 7.2)
    - nanopb (~> 1.30906.0)
    - PromisesObjC (~> 1.2)
  - FirebaseDynamicLinks (4.3.1):
    - FirebaseCore (~> 6.10)
  - FirebaseInstallations (1.7.0):
    - FirebaseCore (~> 6.10)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/UserDefaults (~> 6.7)
    - PromisesObjC (~> 1.2)
  - FirebaseInstanceID (4.8.0):
    - FirebaseCore (~> 6.10)
    - FirebaseInstallations (~> 1.6)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/UserDefaults (~> 6.7)
  - FirebaseMessaging (4.7.1):
    - FirebaseCore (~> 6.10)
    - FirebaseInstanceID (~> 4.7)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.7)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Reachability (~> 6.7)
    - GoogleUtilities/UserDefaults (~> 6.7)
    - Protobuf (>= 3.9.2, ~> 3.9)
  - FirebasePerformance (3.3.2):
    - FirebaseCore (~> 6.9)
    - FirebaseInstallations (~> 1.5)
    - FirebaseRemoteConfig (~> 4.7)
    - GoogleDataTransport (~> 7.0)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/ISASwizzler (~> 6.2)
    - GoogleUtilities/MethodSwizzler (~> 6.2)
    - GTMSessionFetcher/Core (~> 1.1)
    - Protobuf (~> 3.12)
  - FirebaseRemoteConfig (4.9.1):
    - FirebaseABTesting (~> 4.2)
    - FirebaseCore (~> 6.10)
    - FirebaseInstallations (~> 1.6)
    - GoogleUtilities/Environment (~> 6.7)
    - "GoogleUtilities/NSData+zlib (~> 6.7)"`
If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by rizafran** [comment]
Hi @ZsIsMe, could you try updating your SDK to the latest version (as this contains bug fixes and new features), and see if the issue will persist?

**Comment by paulb777** [comment]
The symbol `GADJSONSafeDictionary` is from `Google-Mobile-Ads-SDK`

**Comment by ZsIsMe** [comment]
> Hi @ZsIsMe, could you try updating your SDK to the latest version (as this contains bug fixes and new features), and see if the issue will persist?
YES, I should try....



> The symbol `GADJSONSafeDictionary` is from `Google-Mobile-Ads-SDK`

Thanks for your information!
