### ISSUE TITLE
Catalyst Crash

### ISSUE THREAD

**Issue by alelordelo** [firebase/firebase-ios-sdk#7890]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 12.4 (12D4e)
  * Firebase SDK version: Firebase 7.9.1
  * Installation method:  Swift Package Manager
  * Firebase Component: Auth, Core, Database, Firestore, Messaging, Storage

### [REQUIRED] Step 2: Describe the problem

When build on Catalyst, Firebase crashes

#### Steps to reproduce:

What happened? How can we make the problem occur?

1- Selected iOS Catalyst build targeting MacOS 11

2- Catalyst App builds fine on MacOS 11

3- When user signs in, App gives following error:

"An error occurred when accessing the keychain. The NSLocalizedFailureReasonErrorKey field in the NSError.userInfo dictionary will contain more information about the error encountered"

Relevant log bellow:

[Firebase/InstanceID][I-IID007004] Unable to save checkin info, resetting checkin preferences in memory.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by alelordelo** [comment]
solved with this:
https://stackoverflow.com/questions/39597277/error-when-accessing-keychain-with-firebase-ios-10

**Comment by paulb777** [comment]
Yep. That's documented at https://github.com/firebase/firebase-ios-sdk#additional-catalyst-notes
