### ISSUE TITLE
[FR] Importing public headers should fail presubmit

### ISSUE THREAD

**Issue by ryanwilson** [firebase/firebase-ios-sdk#7897]
In the https://github.com/firebase/firebase-ios-sdk/blob/master/scripts/check_imports.swift script, we should fail if there's an attempt to import a Public header (like FIRVersion.h) from a different Firebase SDK, instead it should be the internal private header. See #7896 for reasoning.

**Comment by paulb777** [comment]
Closing as low priority since infrastructure priorities are now Swift oriented
