### ISSUE TITLE
FirebaseAnalytics can't update from 7.1.0 to 7.10.0

### ISSUE THREAD

**Issue by salyasev** [firebase/firebase-ios-sdk#7922]
### [REQUIRED] Step 1: Describe your environment

Xcode version: Version 12.4 (12D4e)
Firebase SDK version: 7.1.0
Installation method: Pod binary
Firebase Component: FirebaseAnalytics 

#### Steps to reproduce:

Trying to update Firebase pods from 7.1.0 to 7.10.0 
from:
```
pod 'Firebase/Crashlytics', '7.1.0', binary: true, inhibit_warnings: true
pod 'Firebase/Core', '7.1.0', binary: true, inhibit_warnings: true
pod 'Firebase/Performance', '7.1.0', binary: true, inhibit_warnings: true
pod 'Firebase/Analytics', '7.1.0', binary: true, inhibit_warnings: true
```
to:
```
pod 'Firebase/Crashlytics', '7.10.0', binary: true, inhibit_warnings: true
pod 'Firebase/Core', '7.10.0', binary: true, inhibit_warnings: true
pod 'Firebase/Performance', '7.10.0', binary: true, inhibit_warnings: true
pod 'Firebase/Analytics', '7.10.0', binary: true, inhibit_warnings: true
```

Faced with an issue: "Can't import FirebaseAnalytics framework"

**Comment by paulb777** [comment]
`FirebaseAnalytics` is now distributed as an `.xcframework` and that looks to be unsupported by https://github.com/leavez/cocoapods-binary. 

A workaround might be to remove `binary: true` from `Firebase/Analytics` since the CocoaPod is already distributed as a binary.

**Comment by salyasev** [comment]
@paulb777 Oh, Thanks!
but still are not available 
`import FirebaseAnalytics` in swift and `@import FirebaseAnalytics;` in objc

and using simple `import Firebase` or `#import "Firebase.h` don't have an access to `[FIRAnalytics logEventWithName:...`

**Comment by paulb777** [comment]
Perhaps something about cocoapods-binary and mixing pods from the Firebase umbrella pod is causing trouble? Another suggestion would be to stop using the umbrella pod (remove the `/`s from all the `pod Firebase/*` directives in the Podfile).

**Comment by salyasev** [comment]
@paulb777 Cool. Your suggestion helped to link the FirebaseAnalytics (it's possible to import now).

But now there is another issue: 
`Undefined symbols for architecture arm64:
  "_kGULNetworkHTTPStatusCodeNotModified", referenced from:
      -[APMMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in GoogleAppMeasurement(APMMeasurement.o)
      ___46-[APMMeasurement(URL) requestDeferredDeepLink]_block_invoke in GoogleAppMeasurement(APMMeasurement+URL.o)
  "_kGULNetworkHTTPStatusCodeNotFound", referenced from:
      -[APMMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in GoogleAppMeasurement(APMMeasurement.o)
  "_kGULNetworkHTTPStatusNoContent", referenced from:
      -[APMMeasurement networkUploadCompletionHandlerWithResponse:error:] in GoogleAppMeasurement(APMMeasurement.o)
      -[APMMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in GoogleAppMeasurement(APMMeasurement.o)
      -[APMETaskManager handleFetchingExperimentsResponse:data:error:] in GoogleAppMeasurement(APMETaskManager.o)
      ___46-[APMMeasurement(URL) requestDeferredDeepLink]_block_invoke in GoogleAppMeasurement(APMMeasurement+URL.o)
  "_kGULNetworkHTTPStatusCodeUnavailable", referenced from:
      -[APMMeasurement networkUploadCompletionHandlerWithResponse:error:] in GoogleAppMeasurement(APMMeasurement.o)
      -[APMMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in GoogleAppMeasurement(APMMeasurement.o)
      -[APMETaskManager handleFetchingExperimentsResponse:data:error:] in GoogleAppMeasurement(APMETaskManager.o)
  "_kGULNetworkHTTPStatusOK", referenced from:
      -[APMMeasurement networkUploadCompletionHandlerWithResponse:error:] in GoogleAppMeasurement(APMMeasurement.o)
      -[APMMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in GoogleAppMeasurement(APMMeasurement.o)
      -[APMETaskManager handleFetchingExperimentsResponse:data:error:] in GoogleAppMeasurement(APMETaskManager.o)
      ___46-[APMMeasurement(URL) requestDeferredDeepLink]_block_invoke in GoogleAppMeasurement(APMMeasurement+URL.o)
  "_OBJC_CLASS_$_GULMutableDictionary", referenced from:
      objc-class-ref in GoogleAppMeasurement(APMEExperiment.o)
      objc-class-ref in GoogleAppMeasurement(APMEExperimentRequestBuilder.o)
      objc-class-ref in GoogleAppMeasurement(APMEManager.o)
      objc-class-ref in GoogleAppMeasurement(APMRemoteConfig.o)
      objc-class-ref in GoogleAppMeasurement(APMESnapshot.o)
  "_OBJC_CLASS_$_GULNetwork", referenced from:
      objc-class-ref in GoogleAppMeasurement(APMAnalytics.o)
      objc-class-ref in GoogleAppMeasurement(APMAppDelegateInterceptor.o)
      objc-class-ref in GoogleAppMeasurement(APMMeasurement.o)
      objc-class-ref in GoogleAppMeasurement(APMETaskManager.o)
  "_kGULNetworkHTTPStatusCodeCannotAcceptTraffic", referenced from:
      -[APMMeasurement networkUploadCompletionHandlerWithResponse:error:] in GoogleAppMeasurement(APMMeasurement.o)
      -[APMMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in GoogleAppMeasurement(APMMeasurement.o)
      -[APMETaskManager handleFetchingExperimentsResponse:data:error:] in GoogleAppMeasurement(APMETaskManager.o)
  "_OBJC_CLASS_$_GULAppDelegateSwizzler", referenced from:
      objc-class-ref in GoogleAppMeasurement(APMAnalytics.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

we also have a podspec with dependencies 
```
  s.dependency 'FirebaseCore'
  s.dependency 'FirebaseRemoteConfig'
  s.dependency 'FirebasePerformance'
  s.dependency 'FirebaseCrashlytics'
  s.dependency 'FirebaseAnalytics'
```

Looks like something with auto-linked framework 'GoogleUtilities' ?

**Comment by paulb777** [comment]
It looks like some of the GoogleUtilities subspecs are not being linked. 

One approach would be to examine the generated Podfile.lock from without using `binary: true` and then explicitly add all the necessary GoogleUtilities subspecs to the Podfile.

**Comment by salyasev** [comment]
@paulb777 Many thanks! I'm succeeded with updating Firebase dependencies without using binary.
