### ISSUE TITLE
Veracode issue CWE252 - Unchecked Return Value in FIRCLSMultipartMimeStreamEncoder.m

### ISSUE THREAD

**Issue by rdportillo** [firebase/firebase-ios-sdk#7923]
Environment:

  * Xcode version: 12.3
  * Firebase SDK version: 7.3.0
  * Installation method: CocoaPods
  * Firebase Component: FirebaseCrashlytics

Description:

According to Veracode static scan, there are issues related to the following file: 
- FIRCLSMultipartMimeStreamEncoder.m - lines 102 and 110

The Veracode issue is "Unchecked Return Value": The result of this call to close() is not captured, so it cannot be checked for success. This can result in application instability or crashing if memory is not available.
<img width="1741" alt="Veracode-Crashlytics" src="https://user-images.githubusercontent.com/48093773/115440321-fed6ba00-a1e5-11eb-976c-eb5f773945be.png">

Relevant Code: https://github.com/firebase/firebase-ios-sdk/blob/master/Crashlytics/Shared/FIRCLSNetworking/FIRCLSMultipartMimeStreamEncoder.m

Thank you!

**Comment by morganchen12** [comment]
[Here's](https://cs.opensource.google/firebase-sdk/firebase-ios-sdk/+/master:Crashlytics/Shared/FIRCLSNetworking/FIRCLSMultipartMimeStreamEncoder.m;l=102-110?q=FIRCLSMultipartMimeStreamEncoder.m) the lines of code in question. The `open` and `close` methods referenced are `NSStream` instance methods, and do not produce a return value.
