### ISSUE TITLE
import Firebase no longer works related w/6066

### ISSUE THREAD

**Issue by emretufekci** [firebase/firebase-ios-sdk#7927]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 12.4 (12D4e)
  * Firebase SDK version: 7.11
  * Installation method: `CocoaPods `
  * Firebase Component: Crashlytics, Analytics
 
### [REQUIRED] Step 2: Describe the problem
Similar to #6066 and the solution for #6066 does not work for this one.

AppDelegate.swift file cannot find Firebase _No such module 'Firebase'_

But however it can find other Firebase Modules
![Screen Shot 2021-04-21 at 15 25 02](https://user-images.githubusercontent.com/23323000/115553186-cb636080-a2b5-11eb-8210-13f443f88439.png)

#### Steps to reproduce:

1. Go to project directory
2. run 'pod init'
3. change Podfile like following

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for MyProject
pod 'Firebase/Crashlytics'
# Recommended: Add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
end


```

4. run 'pod install'
5. open MyProject.xcworkspace

I can build with FirebaseCore but in this case i can't see my project under the Crashlytics section in Firebase.

**Comment by paulb777** [comment]
@emretufekci Sorry about the trouble, if the suggestions in #6066 don't work, we'll likely need a reproducible example to help.

On first install, make sure you do a build in Xcode to make sure the modules get updated in the Xcode cache so they can be found by the editor's parser.

**Comment by emretufekci** [comment]
@paulb777 

I can see the modules installed.
![Screen Shot 2021-04-22 at 11 19 16](https://user-images.githubusercontent.com/23323000/115680820-9827dc80-a35c-11eb-9b51-f594c6fe6e5b.png)

Actually, i've just downloaded cocoapods to be able to use firebase even to avoid caching i removed everything in the DerivedData folder but even i build removing the line and then try rebuild with it no chance.

By the way, not sure it is the case but i am using c++ & swift via bridge in the project and i suspect the bridging might be cause of error. 

Following is Framework Search Path
`$(inherited) "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseCore" "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseCoreDiagnostics" "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseCrashlytics" "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseInstallations" "${PODS_CONFIGURATION_BUILD_DIR}/GoogleDataTransport" "${PODS_CONFIGURATION_BUILD_DIR}/GoogleUtilities" "${PODS_CONFIGURATION_BUILD_DIR}/PromisesObjC" "${PODS_CONFIGURATION_BUILD_DIR}/nanopb" "${PODS_ROOT}/FirebaseAnalytics/Frameworks" "${PODS_ROOT}/GoogleAppMeasurement/Frameworks" "${PODS_XCFRAMEWORKS_BUILD_DIR}/FirebaseAnalytics" "${PODS_XCFRAMEWORKS_BUILD_DIR}/GoogleAppMeasurement"`

I've tried reproduce the error with the fresh project, it's working well unlike the my own project. 
I'll try to reproduce by repeating my own project steps, if i can i'll share source code of it.

**Comment by emretufekci** [comment]
I've solved the issue by adding "$(inherited)" under Header Search Path (Release & Debug).
Thanks.
