### ISSUE TITLE
Archiving fails after adding performance monitoring SDK but build succeeds

### ISSUE THREAD

**Issue by uchiha-itachi95** [firebase/firebase-ios-sdk#7929]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 12.3 (12C33)
  * Firebase SDK version: Firebase Performance 3.2.0
  * Installation method: CocoaPods
  * Firebase Component: Performance Monitoring

### [REQUIRED] Step 2: Describe the problem
Archiving fails after adding performance monitoring SDK but build for normal device succeeds.
#### Steps to reproduce:
Add firebase performance monitoring SDK and try to archive with generic iOS device scheme.
What happened? How can we make the problem occur?
![Screenshot 2021-04-21 at 8 38 45 PM](https://user-images.githubusercontent.com/67323673/115576980-a389f200-a2e1-11eb-9e89-1615cb5fe2d7.png)

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulb777** [comment]
Are you able to update to the latest version - 7.11.0?

If not or you're still seeing the problem, please share the Podfile and Podfile.lock.

**Comment by raymondlam** [comment]
This could be related to #6597 which is already fixed in the latest version.

**Comment by uchiha-itachi95** [comment]
thanks for the super fast reply.
I was able to solve this issue by following this solution [here](https://medium.com/%E5%BD%BC%E5%BE%97%E6%BD%98%E7%9A%84-swift-ios-app-%E9%96%8B%E7%99%BC%E6%95%99%E5%AE%A4/archive-fails-in-firebasecorediagnostics-with-could-not-build-module-googleutilities-6726004587e7)

All I needed to do is removing the `FIRCoreDiagonstics.m` file from the `FirebaseDiagnostics Target`. That fixed the problem.
