### ISSUE TITLE
Crashed: com.google.fira.worker

### ISSUE THREAD

**Issue by perumal1216** [firebase/firebase-ios-sdk#7935]
### [REQUIRED] Step 1: Describe your environment

1. Xcode version: 12.4
2. Firebase SDK version: 7.6.0
3. Firebase Component: (Performance, Crashlytics, Analytics, DynamicLinks, Core)
4. Installation method: `CocoaPods

### [REQUIRED] Step 2: Describe the problem

Crashlytics is reporting crashes. The crash rate is so high, so it is difficult to reproduce it. Can you help sort it out, since tool is needed for us?

### Steps to reproduce:

I have not been able to reproduce it so far.

Output of cat Podfile.lock | grep Firebase:

 - Firebase/Analytics (7.6.0):
    - Firebase/Core
  - Firebase/Core (7.6.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 7.6.0)
  - Firebase/CoreOnly (7.6.0):
    - FirebaseCore (= 7.6.0)
  - Firebase/Crashlytics (7.6.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 7.6.0)
  - Firebase/DynamicLinks (7.6.0):
    - Firebase/CoreOnly
    - FirebaseDynamicLinks (~> 7.6.0)
  - Firebase/Performance (7.6.0):
    - Firebase/CoreOnly
    - FirebasePerformance (~> 7.6.0)
  - FirebaseABTesting (7.6.0):
    - FirebaseCore (~> 7.0)
  - FirebaseAnalytics (7.6.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleAppMeasurement (= 7.6.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.0)
    - GoogleUtilities/MethodSwizzler (~> 7.0)
    - GoogleUtilities/Network (~> 7.0)
    - "GoogleUtilities/NSData+zlib (~> 7.0)"
    - nanopb (~> 2.30907.0)
  - FirebaseCore (7.6.0):
    - FirebaseCoreDiagnostics (~> 7.4)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/Logger (~> 7.0)
  - FirebaseCoreDiagnostics (7.6.0):
    - GoogleDataTransport (~> 8.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/Logger (~> 7.0)
    - nanopb (~> 2.30907.0)
  - FirebaseCrashlytics (7.6.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleDataTransport (~> 8.0)
    - nanopb (~> 2.30907.0)
    - PromisesObjC (~> 1.2)
  - FirebaseDynamicLinks (7.6.0):
    - FirebaseCore (~> 7.0)
  - FirebaseInstallations (7.6.0):
    - FirebaseCore (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/UserDefaults (~> 7.0)
    - PromisesObjC (~> 1.2)
  - FirebasePerformance (7.6.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - FirebaseRemoteConfig (~> 7.0)
    - GoogleDataTransport (~> 8.2)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/ISASwizzler (~> 7.0)
    - GoogleUtilities/MethodSwizzler (~> 7.0)
    - Protobuf (~> 3.12)
  - FirebaseRemoteConfig (7.6.0):
    - FirebaseABTesting (~> 7.0)
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - "GoogleUtilities/NSData+zlib (~> 7.0)"

 Firebase: e1e089d9aac215a52442583f818ab61de3c4581b
  FirebaseABTesting: 8d7f24fdf94cd10f06a84c879262a1159e22db28
  FirebaseAnalytics: 9f8f4feab1f3fddf4e4515f8f022fe6aa9e51043
  FirebaseCore: 0a43b7f1c5b36f3358cd703011ca4c7e0df55870
  FirebaseCoreDiagnostics: ee1184d51da3293335b83355aad20f537acc24cf
  FirebaseCrashlytics: 1e87b25303b1840b3c99c37ee427c3e9564a4be1
  FirebaseDynamicLinks: 1ba27bcead0c55cb3fa48db7e1ca75005f8123d0
  FirebaseInstallations: 6e4e77396559bc2ae0504823837ed737b1c7e47f
  FirebasePerformance: bd70a911919ab62b6a4a51728fadb901406b0a13
  FirebaseRemoteConfig: f805089c5c383c17d68bcc0799d8a3622f9ae28f

//stacktrace

Crashed: com.google.fira.worker
0  libobjc.A.dylib                0x1bd284de0 objc_release + 16
1  libobjc.A.dylib                0x1bd286574 AutoreleasePoolPage::releaseUntil(objc_object**) + 200
2  libobjc.A.dylib                0x1bd286450 objc_autoreleasePoolPop + 208
3  libdispatch.dylib              0x1a8b37260 _dispatch_last_resort_autorelease_pool_pop + 40
4  libdispatch.dylib              0x1a8ae0908 _dispatch_lane_invoke$VARIANT$mp + 520
5  libdispatch.dylib              0x1a8aea338 _dispatch_workloop_worker_thread + 712
6  libsystem_pthread.dylib        0x1f16335a4 _pthread_wqthread + 272
7  libsystem_pthread.dylib        0x1f1636874 start_wqthread + 8

com.apple.main-thread
0  libsystem_kernel.dylib          0x1d4db2644 mach_msg_trap + 8
1  libsystem_kernel.dylib          0x1d4db1a48 mach_msg + 72
2  CoreFoundation                  0x1a8e7e0fc __CFRunLoopServiceMachPort + 376
3  CoreFoundation                  0x1a8e78570 __CFRunLoopRun + 1176
4  CoreFoundation                  0x1a8e77ba0 CFRunLoopRunSpecific + 572
5  GraphicsServices                0x1bfbb5598 GSEventRunModal + 160
6  UIKitCore                       0x1ab7673d8 -[UIApplication _run] + 1052
7  UIKitCore                       0x1ab76c958 UIApplicationMain + 164
8  ConsumerMobileAppNonClinical    0x1006ed80c main + 35 (AppDelegate.swift:35)
9  libdyld.dylib                   0x1a8b56568 start + 4

**Comment by perumal1216** [comment]
> I found a few problems with this issue:
> 
> * I couldn't figure out how to label this issue, so I've labeled it for a human to triage. Hang tight.
> * This issue does not seem to follow the issue template. Make sure you provide all the required information.

**Comment by perumal1216** [comment]
Thanks for the update . could you please tell me the what are required information to help your investigation.

**Comment by rizafran** [comment]
Thanks for reporting, @perumal1216. Could you try updating your SDK to the latest one and see if the issue still occurs?

**Comment by paulb777** [comment]
Related issue at #6802. This may be related to issues that have been fixed in FirebasePerformance.

**Comment by perumal1216** [comment]
> Thanks for reporting, @perumal1216. Could you try updating your SDK to the latest one and see if the issue still occurs?

thanks for your update @rizafran   .  we are already having Firebase SDK version: 7.6.0 and  Firebase/Performance (7.6.0)

**Comment by paulb777** [comment]
The current release is 7.11.0

**Comment by perumal1216** [comment]
Do we have a any potential fix on release 7.11.0 version related to above defined issue . if yes please provide details that could be great help to us.

**Comment by morganchen12** [comment]
@perumal1216 this kind of crash can also be caused by memory corruption in your app, consider debugging your app with some memory diagnostic tools (like asan, zombies) enabled.
