### ISSUE TITLE
Firebase SDK crashes on FBLPromise with unrecognized selector.

### ISSUE THREAD

**Issue by jobnte** [firebase/firebase-ios-sdk#7939]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.11.0
  * Installation method: CocoaPods
  * Firebase Component: RemoteConfig, DynamicLinks, Firestore, Auth, Analytics.

#### Steps to reproduce:

We just updated the Firebase SDK from **6.34.0** to **7.11.0**.
 
Dependencies:
* Firebase Analytics
* Firebase RemoteConfig
* Firebase DynamicLinks
* Firebase Firestore
* Firebase Auth

We're also using **`use_frameworks! :linkage => :static`**

When we run the project after the update we get a crash in the `FirebaseApp.configure(options: options)` method. Logs:
```2021-04-22 11:45:48.323682-0500 MainApp[79727:979382] -[FBLPromise HTTPBody]: unrecognized selector sent to instance 0x600003281590
2021-04-22 11:45:48.339458-0500 MainApp[79727:979385] 7.11.0 - [Firebase/Analytics][I-ACS023007] Analytics v.7.11.0 started
2021-04-22 11:45:48.340266-0500 MainApp[79727:979380] 7.11.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2021-04-22 11:45:48.343676-0500 MainApp[79727:979382] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[FBLPromise HTTPBody]: unrecognized selector sent to instance 0x600003281590'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20421af6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff204306f7 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   CoreFoundation                      0x00007fff20426036 ___forwarding___ + 1489
	4   CoreFoundation                      0x00007fff20428068 _CF_forwarding_prep_0 + 120
	5   MainApp                     0x0000000114223bc8 -[GDTCCTUploadOperation updateNextUploadTimeWithResponse:forTarget:] + 88
	6   MainApp                     0x0000000114222f79 __64-[GDTCCTUploadOperation sendURLRequestWithBatch:target:storage:]_block_invoke + 105
	7   MainApp                     0x0000000113b7318e __56-[FBLPromise chainOnQueue:chainedFulfill:chainedReject:]_block_invoke.67 + 94
	8   MainApp                     0x0000000113b726ad __44-[FBLPromise observeOnQueue:fulfill:reject:]_block_invoke_2 + 109
	9   libdispatch.dylib                   0x000000011b77d7ec _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x000000011b77e9c8 _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x000000011b785440 _dispatch_lane_serial_drain + 1222
	12  libdispatch.dylib                   0x000000011b785f67 _dispatch_lane_invoke + 439
	13  libdispatch.dylib                   0x000000011b791de2 _dispatch_workloop_worker_thread + 882
	14  libsystem_pthread.dylib             0x00007fff61167499 _pthread_wqthread + 314
	15  libsystem_pthread.dylib             0x00007fff61166467 start_wqthread + 15
)
2021-04-22 11:45:48.343915-0500 MainApp[79727:979373] [] nw_protocol_get_quic_image_block_invoke dlopen libquic failed
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[FBLPromise HTTPBody]: unrecognized selector sent to instance 0x600003281590'
terminating with uncaught exception of type NSException
CoreSimulator 757.3 - Device: iPhone SE (2nd generation) (914256F3-F16E-4784-892A-340594ACE352) - Runtime: iOS 14.4 (18D46) - DeviceType: iPhone SE (2nd generation)
```

Also, the structure of our project is like this:
[MainApp] depends on [CoreProject] (Dynamic framework) which uses all the third-party dependencies including Firebase.

Thanks in advance for any help!

**Comment by paulb777** [comment]
I suspect this might be a corrupted environment. Try `pod deintegrate`, clearing DerivedData, reinstalling and rerunning.

**Comment by jobnte** [comment]
> I suspect this might be a corrupted environment. Try `pod deintegrate`, clearing DerivedData, reinstalling and rerunning.

Hi @paulb777 , thanks for your answer. Unfortunately, it didn't work and still crashing.

**Comment by paulb777** [comment]
Hmm, it sounds a bit strange to use `use_frameworks! :linkage => :static` and link into a dynamic library.  Do you get any duplicate library warnings on load?

**Comment by jobnte** [comment]
> Hmm, it sounds a bit strange to use `use_frameworks! :linkage => :static` and link into a dynamic library. Do you get any duplicate library warnings on load?

Yes, I’m getting duplicate warnings but even before I update to 7.11.0

**Comment by paulb777** [comment]
The duplicate warnings are indicative of non-deterministic behavior. When there are multiple copies of a library, the right one may or may not be chosen.

**Comment by jobnte** [comment]
> The duplicate warnings are indicative of non-deterministic behavior. When there are multiple copies of a library, the right one may or may not be chosen.

We have been using it like that even with 6.34 and never had any issue. We would totally appreciate it If you have any article about how to fix those duplicate warnings because we have tried everything with no success.

**Comment by paulb777** [comment]
Do the warnings reduce or go away with `use_frameworks!` instead of `use_frameworks! :linkage => :static`?

**Comment by jobnte** [comment]
> 
> 
> Do the warnings reduce or go away with `use_frameworks!` instead of `use_frameworks! :linkage => :static`?

No, but I can run the project without the runtime error. The problem now is `RemoteConfig.remoteConfig().fetchAndActivate ` closure is never called and my our depends of that call. This is only happening when there is a previous build installed with 6.34 because If make a fresh install everything works.

**Comment by jobnte** [comment]
We fixed our issue by running a script that will avoid duplicate issues. We also are using just `use_frameworks!`. Thanks for the help @paulb777 .
