### ISSUE TITLE
Carthage versioning 

### ISSUE THREAD

**Issue by icedice** [firebase/firebase-ios-sdk#7946]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.11.0
  * Installation method:  Carthage

### [REQUIRED] Step 2: Describe the problem

The Carthage usage document (https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md#carthage-usage) clearly states that 

> All Firebase components share the same version. Mixing and matching components with different versions may cause linker errors.

The newest version available seems to be 7.11 however for FirebaseAnalyticsBinary which always needs to be included the newest version is 7.4

What's going on here?

**Comment by ryanwilson** [comment]
Hi @icedice - sorry for the trouble. You can see an explanation at https://github.com/firebase/firebase-ios-sdk/issues/7698#issuecomment-799023908, but the tl;dr is that Analytics switched to distribute the binary as an `xcframework` so we could support Apple silicon, but carthage doesn't have a release that supports `xcframework`s yet. 

We have another issue tracking Apple silicon support for Carthage that is tracked at #7039 that would solve this issue as well.

Thanks!
