### ISSUE TITLE
Firebase Analytics cause Terminated due to signal 9 

### ISSUE THREAD

**Issue by hazemMaher** [firebase/firebase-ios-sdk#7947]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: latest 7.11.0
  * Installation method: `CocoaPods`
  * Firebase Component: `Core, RemoteConfig, Messaging, Analytics, Crashlytics`
  * Podfile:  
 ```
def pods
pod 'Firebase/Core'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Messaging'
pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'
pod 'GoogleTagManager'
end
```
  * Background Modes:  
 
<img width="306" alt="image" src="https://user-images.githubusercontent.com/13917231/115847819-9aa13980-a423-11eb-81fd-e941187e67fc.png">

### [REQUIRED] Step 2: Describe the problem

Our app is is using some background modes since we need to do some background processing in addition we have a VOIP to enable the customers to contact the customer support, 
Firebase Analytics is highly impacting the app performance/CPU especially when the app in the background and eventually it cause the app to crash `Terminated due to signal 9`, The OS terminate the app since its doing too much work in the background.

#### Relevant Code:
The code we are using to configure Firebase
NOTE: We enable and disable Firebase Analytics programmatically based on the user preference
```
FirebaseApp.configure()
Analytics.setAnalyticsCollectionEnabled(true)
Analytics.logEvent(firebaseEventName, parameters: someParameters)
```

#### Steps to reproduce:
  * Device: iPhoneX OS 14.4
  * Same exact flow and building configuration
  * App in Background  

Firebase Analytics Enabled while the app in background you can see the threads still processing till the app crash due to `Terminated due to signal 9`
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/13917231/115850042-cc1b0480-a425-11eb-9852-71498c5d9d02.png">

Firebase Analytics Disabled while the app in background
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/13917231/115850805-87dc3400-a426-11eb-840b-f64a83f7bd76.png">

#### What we have tried to do:
I have tried to disable analytics before the app goes to the background to prevent crashing.

```
Analytics.resetAnalyticsData()
Analytics.setAnalyticsCollectionEnabled(false)
```
But it still have the same impact on the CPU and cause the app to crash eventually since I can see the in console that firebase try to send the events but fail.

### [REQUIRED] Step 3: Expected
Is there a way to completely disable analytics from doing any tasks in the background ?

**Comment by morganchen12** [comment]
Can you run a time profiler trace to determine what's causing the CPU usage?
