### ISSUE TITLE
Xcode build error when including pods "Firebase/Analytics" 7.11.0 and "Google-Mobile-Ads-SDK" 8.4.0 across targets

### ISSUE THREAD

**Issue by lotz** [firebase/firebase-ios-sdk#7958]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4 (12D4e)
  * Firebase SDK version: 7.11.0
  * Installation method: `CocoaPods`
  * Firebase Component: Analytics
  * Cocoapods version: 1.10.1

### [REQUIRED] Step 2: Describe the problem

I have multiple targets in my project, all of which use `Firebase/Analytics`. Some are ad-supported, and some are not, so some of the targets also include `Google-Mobile-Ads-SDK`. With this setup, where different targets have different dependencies, I am now getting a "duplicate output file" build error with `Firebase/Analytics` version 7.11.0 and `Google-Mobile-Ads-SDK` version 8.4.0. Please see the example `Podfile` below.

**NOTE:** This is _new_ behavior as of these versions. Installing `Firebase/Analytics` version 7.9.0 and `Google-Mobile-Ads-SDK` version 8.3.0 works fine, as I have been using this setup for a while, and have published apps using it. Additionally, including the _same_ pods across all targets also works fine and builds successfully (obviously, not what I want, since I don't need ads in some targets).

#### Steps to reproduce:

1. Download the sample project (attached).
2. Run `pod install` to install the pods (see `Podfile` below for what will be installed).
3. Open the `TestApp.xcworkspace` in Xcode and attempt to build the project.

Expected: Workspace should build without errors.
Actual: Workspace fails to build with these errors:
* `duplicate output file '/Users/<redacted>/Library/Developer/Xcode/DerivedData/TestApp-fhswfeghpooyswbrtkbhozwdghko/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/GoogleAppMeasurement' on task: PhaseScriptExecution [CP] Copy XCFrameworks /Users/<redacted>/Library/Developer/Xcode/DerivedData/TestApp-fhswfeghpooyswbrtkbhozwdghko/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/GoogleAppMeasurement-AdIdSupport.build/Script-381CCA5859BC027B4F5B71494753428B.sh`
* `Multiple commands produce '/Users/<redacted>/Library/Developer/Xcode/DerivedData/TestApp-fhswfeghpooyswbrtkbhozwdghko/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/GoogleAppMeasurement':`
  * `1) That command depends on command in Target 'GoogleAppMeasurement' (project 'Pods'): script phase “[CP] Copy XCFrameworks”`
  * `2) That command depends on command in Target 'GoogleAppMeasurement-AdIdSupport' (project 'Pods'): script phase “[CP] Copy XCFrameworks”`

#### Relevant Code:

Example Xcode workspace: [**TestApp.zip**](https://github.com/firebase/firebase-ios-sdk/files/6371078/TestApp.zip)

Example Podfile (same as in example project attached):

```ruby
platform :ios, '13.0'
use_frameworks!
inhibit_all_warnings!

# Ad-supported target
target 'TestApp' do
  pod 'Firebase/Analytics', '7.11.0'
  pod 'Google-Mobile-Ads-SDK', '8.4.0'
end

# Ad-free target
target 'TestApp2' do
  pod 'Firebase/Analytics', '7.11.0'
  # Error goes away when all targets include 'Google-Mobile-Ads-SDK' (uncomment to verify)
  # pod 'Google-Mobile-Ads-SDK', '8.4.0'
end
```

**Comment by paulb777** [comment]
@lotz Sorry about the trouble and thanks for the report.

This is likely a side-effect of the 7.11.0 to change to split the AdSupport and AppTrackingTransparency from Firebase/Analytics. See the [release notes](https://firebase.google.com/support/release-notes/ios) in order to address to new Appstore requirements.

I'll follow up with the team on this use case this week. In the meantime, a workaround should be to stay on 7.10.0.

**Comment by lotz** [comment]
Thanks for the prompt response and for looking into it.

**Comment by lotz** [comment]
This is not directly related to this issue, but some people reading this thread may be interested. I have [posted in the Google Mobile Ads SDK Developers forum](https://groups.google.com/u/0/g/google-admob-ads-sdk/c/dHjMnBxZtmw) asking about a version of that SDK that does not require the IDFA or AdSupport.framework, similar to `Firebase/AnalyticsWithoutAdIdSupport`.

**Comment by sipersso** [comment]
@paulb777 I don't have the Ads SDK installed but get the same issue. Are there more incompatible pods?

My current firebase dependencies:

```
  pod 'GoogleSignIn'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/AnalyticsWithoutAdIdSupport'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Functions'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
```

**Comment by paulb777** [comment]
@sipersso There shouldn't be any other incompatible Pods. Please check the Podfile.lock to make sure all the Firebase versions are at least 7.11.0.  Otherwise, there may be some stale Xcode state.

**Comment by lotz** [comment]
This no longer appears to be an issue with `Firebase/Analytics` 8.0.0 and `Google-Mobile-Ads-SDK` 8.5.0. I assume something was changed with the subspec to sort this out.

The issue still appears when using `Firebase/AnalyticsWithoutAdIdSupport` and `Google-Mobile-Ads-SDK`, but I assume that is expected (until there's a `Google-Mobile-Ads-SDK-Without-Ad-Id-Support`, hopefully 🙂).

**Comment by paulb777** [comment]
@lotz Glad to hear it! Thanks for letting us know.  We did make the interface more flexible in those latest releases.
