### ISSUE TITLE
crash on CFXNotificationTokenRegistration keyCallbacks

### ISSUE THREAD

**Issue by bluelagon** [firebase/firebase-ios-sdk#7961]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.10.0
  * Installation method: `CocoaPods` (select one)
  * Firebase Component: Analytics, Crashlytics, Performance 

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Hi, I update the Firebase SDK in my podfile from 7.4.0 to 7.10.0. And one of my users gets this crash:

<img width="1022" alt="Capture d’écran 2021-04-26 à 12 20 37" src="https://user-images.githubusercontent.com/32433902/116068008-01279100-a68a-11eb-8aad-d795576bbb72.png">

The user is on iPad with iOS 12.5.2.

The error log doesn't look very clear to me, do you have any idea to help me understand what is happening ? 

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

No sample code

**Comment by morganchen12** [comment]
The crashing stack trace doesn't include any symbols from Firebase (aside from the Crashlytics crash recorder thread), which means this crash is likely not caused by Firebase. Looks like the crash is caused by an index out of bounds error in one of your collection views.

**Comment by bluelagon** [comment]
Thank you for your explanation.
