### ISSUE TITLE
Flaky installation of GoogleAppMeasurement in 7.11 with SwiftPM

### ISSUE THREAD

**Issue by ryanwilson** [firebase/firebase-ios-sdk#7962]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5
  * Firebase SDK version: 7.11.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: Analytics

#### Steps to reproduce:

From a blank project in Xcode 12.5, attempt to add Firebase via SwiftPM.
Occasionally, this fails to reproduce with the message:

```
artifact of binary target 'GoogleAppMeasurement' failed extraction: The operation couldn't be completed. (TSCBasic.StringError error 1.)
artifact of binary target 'GoogleAppMeasurementWithoutAdIdSupport' failed extraction: The operation couldn't be completed. (TSCBasic.StringError error 1.)
```

#### Relevant Code:

No code needed, error occurs in Xcode during installation.

![Screenshot of error in Xcode](https://user-images.githubusercontent.com/1097316/116090266-ac781c00-a671-11eb-9168-f244a9c35d1e.png)

**Comment by ryanwilson** [comment]
This is likely the underlying implementation of the unzipping: 
https://github.com/apple/swift-tools-support-core/blob/435a2708a6e486d69ea7d7aaa3f4ad243bc3b408/Sources/TSCUtility/Archiver.swift#L65

Will try to work off that and reproduce.

**Comment by ryanwilson** [comment]
Using the `unzip` command an extra directory `__MACOSX` shows up. I suspect this is due to an incorrect compression of the release artifacts, and Xcode gets confused when there are 2 `XCFramework`s nested there. This could also explain the flakiness in that sometimes the proper `XCFramework` gets selected.

![Duplicate folders in finder](https://user-images.githubusercontent.com/1097316/116103047-3a0d3900-a67d-11eb-9187-a9b8a219ef87.png)

**Comment by ryanwilson** [comment]
7.11.1 for SwiftPM was released and this appears to be resolved.

**Comment by morganchen12** [comment]
@ryanwilson does this warrant a release note?

**Comment by ryanwilson** [comment]
> @ryanwilson does this warrant a release note?

Probably - but let's hold off momentarily as I just had the issue happen again.

**Comment by paulb777** [comment]
This seems to have stabilized with some combination of recent Xcodes and Firebase releases. I'll close for now and we can reopen if it reoccurs.
