### ISSUE TITLE
watchOS FCM notifications not being received

### ISSUE THREAD

**Issue by jovanovski** [firebase/firebase-ios-sdk#7963]
### Environment

  * Xcode version: 12.4
  * Firebase SDK version: 8.0.0
  * Installation method: CocoaPods
  * Firebase Component: Messaging

### Describe the problem
I am trying to get a standalone watchOS app to receive a FCM notification sent from the console. I tried following the [example app](https://github.com/firebase/firebase-ios-sdk/tree/master/Example/watchOSSample), to the point, line per line, but nothing is being received by the watchOS app.

- Exact code from example
- Exact import libraries from example (both latest versions from CocoaPods and the local ones from the repo)
- Generated APN key and uploaded to Firebase project
- Registered `. watchkitextension` bundle with Push Notification capabilities
- Turned off method swizzling
- Working on real device

#### Steps to reproduce:
On launch, the app registers, gets a FCM token, and successfully subscribes to a topic (as in the example). But no matter what I do, foreground or background, the app will receive any notifications. I've been trying to add different methods that may be missing from the example (like `userNotificationCenter` from `UNUserNotificationCenterDelegate`, but that doesn't seem to do anything. No error on both FCM console nor debugger. FCM console seems to detect the newly registered topic, so that means at least some communication is being made, but no notification. Kinda going crazy over here as to where the issue can be.

#### Relevant Code:
[watchOS example app](https://github.com/firebase/firebase-ios-sdk/tree/master/Example/watchOSSample)

### Extra methods tried

```
    func didReceiveRemoteNotification(_ userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (WKBackgroundFetchResult) -> Void) {
      print("Test 1")
      Messaging.messaging().appDidReceiveMessage(userInfo)
      completionHandler(.noData)
    }
    
    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                willPresent notification: UNNotification,
      withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
      print("Test 2")

      let userInfo = notification.request.content.userInfo

      Messaging.messaging().appDidReceiveMessage(userInfo)

      // Change this to your preferred presentation option
      completionHandler([[.alert, .sound]])
    }

    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                didReceive response: UNNotificationResponse,
                                withCompletionHandler completionHandler: @escaping () -> Void) {
      print("Test 3")
      let userInfo = response.notification.request.content.userInfo
      Messaging.messaging().appDidReceiveMessage(userInfo)
      completionHandler()
    }
```

**Comment by chliangGoogle** [comment]
@jovanovski Which bundle ID do you register with Firebase console? Are you using the one suffix with .WatchKitApp?

**Comment by jovanovski** [comment]
@chliangGoogle The one that ends with `.watchkitapp.watchkitextension`. Should I be registering the one that ends just with `.watchkitapp` instead?

**Comment by chliangGoogle** [comment]
Yes that is the bundle ID of watch app.

**Comment by jovanovski** [comment]
Registering that ID, grabbing a new `GoogleService-Info.plist`, cleaning everything and rebuilding made it work. Thank you Chen for your help!
