### ISSUE TITLE
Deadlock caused by RemoteConfig fetch

### ISSUE THREAD

**Issue by 1oo7** [firebase/firebase-ios-sdk#7977]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.3
  * Firebase SDK version: 7.11
  * Installation method: `Zip file` (select one)
  * Firebase Component: RemoteConfig (Auth, Core, Database, Firestore, Messaging, Storage, etc)

### [REQUIRED] Step 2: Describe the problem

We are experiencing a deadlock when performing a "fetch" RemoteConfig operation on a fresh install of the app.

On the main thread we have:

```
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x00000001b1c10404 in kevent_id ()
#1	0x000000010f6a5ee0 in _dispatch_kq_poll ()
#2	0x000000010f6a6988 in _dispatch_event_loop_wait_for_ownership ()
#3	0x000000010f694a74 in __DISPATCH_WAIT_FOR_QUEUE__ ()
#4	0x000000010f6944c0 in _dispatch_sync_f_slow ()
#5	0x0000000109736960 in -[FIRRemoteConfig configValueForKey:] ()
#6	0x0000000109805368 in __41-[FPRRemoteConfigFlags cacheConfigValues]_block_invoke ()
#7	0x00000001863e2cc8 in __NSDICTIONARY_IS_CALLING_OUT_TO_A_BLOCK__ ()
#8	0x00000001863610bc in -[__NSFrozenDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] ()
#9	0x00000001098052e4 in -[FPRRemoteConfigFlags cacheConfigValues] ()
#10	0x0000000109805128 in __30-[FPRRemoteConfigFlags update]_block_invoke ()
#11	0x000000010f683ce4 in _dispatch_call_block_and_release ()
#12	0x000000010f685528 in _dispatch_client_callout ()
#13	0x000000010f693994 in _dispatch_main_queue_callback_4CF ()
#14	0x00000001863f75e0 in __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ ()
#15	0x00000001863f1a88 in __CFRunLoopRun ()
#16	0x00000001863f0ba0 in CFRunLoopRunSpecific ()
#17	0x000000019d159598 in GSEventRunModal ()
#18	0x0000000188ce22f4 in -[UIApplication _run] ()
#19	0x0000000188ce7874 in UIApplicationMain ()
#20	0x0000000100a18370 in main at /Users/REDACTED/code/ios-12-3/REDACTED/REDACTED/main.swift:9
#21	0x00000001860cf568 in start ()
```

Meanwhile on a background thread we have:

```
Thread 6 Queue : com.google.GoogleConfigService.FIRRemoteConfig (serial)
#0	0x00000001b1c0e61c in __psynch_cvwait ()
#1	0x00000001cdea945c in _pthread_cond_wait$VARIANT$mp ()
#2	0x000000018768b144 in -[NSOperation waitUntilFinished] ()
#3	0x00000001863d9370 in _CFXNotificationPost ()
#4	0x000000018760f0a0 in -[NSNotificationCenter postNotificationName:object:userInfo:] ()
#5	0x00000001097471d4 in -[RCNUserDefaultsManager setInstanceUserDefaultsValue:forKey:] ()
#6	0x0000000109746bcc in -[RCNUserDefaultsManager setLastETagUpdateTime:] ()
#7	0x0000000109742bc0 in -[RCNConfigSettings setLastETag:] ()
#8	0x000000010974206c in __60-[RCNConfigFetch fetchWithUserProperties:completionHandler:]_block_invoke_2 ()
#9	0x000000010f683ce4 in _dispatch_call_block_and_release ()
#10	0x000000010f685528 in _dispatch_client_callout ()
#11	0x000000010f68c5ac in _dispatch_lane_serial_drain ()
#12	0x000000010f68d234 in _dispatch_lane_invoke ()
#13	0x000000010f698a5c in _dispatch_workloop_worker_thread ()
#14	0x00000001cdeb15a4 in _pthread_wqthread ()
Enqueued from com.apple.NSURLSession-delegate (Thread 0) Queue : com.apple.NSURLSession-delegate (serial)
#0	0x000000010f689a20 in dispatch_async ()
#1	0x00000001097416ac in __60-[RCNConfigFetch fetchWithUserProperties:completionHandler:]_block_invoke ()
#2	0x0000000109801440 in __InstrumentDataTaskWithRequestCompletionHandler_block_invoke_2 ()
#3	0x0000000109801440 in __InstrumentDataTaskWithRequestCompletionHandler_block_invoke_2 ()
#4	0x0000000186a6d728 in ___lldb_unnamed_symbol531$$CFNetwork ()
#5	0x0000000186a7e1f8 in ___lldb_unnamed_symbol921$$CFNetwork ()
#6	0x000000010f683ce4 in _dispatch_call_block_and_release ()
#7	0x000000010f685528 in _dispatch_client_callout ()
#8	0x000000010f68c5ac in _dispatch_lane_serial_drain ()
#9	0x000000010f68d268 in _dispatch_lane_invoke ()
#10	0x000000010f698a5c in _dispatch_workloop_worker_thread ()
#11	0x00000001cdeb15a4 in _pthread_wqthread ()
#12	0x00000001cdeb4874 in start_wqthread ()
```

#### Steps to reproduce:

```
        FirebaseApp.configure()
        RemoteConfig.remoteConfig().ensureInitialized { error in
            RemoteConfig.remoteConfig().setDefaults(OurDefaultValues)
            if isFirstLaunch {
                UserDefaults.standard.setValue(true, forKey: isNotFirstLaunchKey)
                RemoteConfig.remoteConfig().fetch() { ... }
            } else {
                RemoteConfig.remoteConfig().activate() { 
                   RemoteConfig.remoteConfig().fetch() { ... }
                    ... 
                }
             }
        }
```

What happened? How can we make the problem occur?

The app freezes and becomes unresponsive due to this apparent deadlock.

**Comment by 1oo7** [comment]
I notice the logs usually end like this: 

```
 7.11.0 - [Firebase/Analytics][I-ACS002001] APMExperimentAlarm fired
 7.11.0 - [Firebase/Analytics][I-ACS002003] APMExperimentAlarm canceled
 7.11.0 - [Firebase/Analytics][I-ACS002002] APMExperimentAlarm scheduled to fire in approx. (s): 14399.97326385975
 [tcp] tcp_input [C4.1:3] flags=[R] seq=1755433504, ack=0, win=0 state=LAST_ACK rcv_nxt=1755433505, snd_una=1622841800
 [tcp] tcp_input [C4.1:3] flags=[R] seq=1755433505, ack=0, win=0 state=LAST_ACK rcv_nxt=1755433505, snd_una=1622841800
 [tcp] tcp_input [C4.1:3] flags=[R] seq=1755433505, ack=0, win=0 state=CLOSED rcv_nxt=1755433505, snd_una=1622841800
```

**Comment by 1oo7** [comment]
In testing different possible fixes for this issue and googling various sections of the logs, eventually at long last, we found this old github issue from 2019 about the same exact problem: https://github.com/firebase/firebase-ios-sdk/issues/3929

I found this by googling ([FIRRemoteConfig configValueForKey:]_block_invoke freeze)[https://www.google.com/search?client=safari&rls=en&q=%5BFIRRemoteConfig+configValueForKey:%5D_block_invoke+freeze&ie=UTF-8&oe=UTF-8].

In that old issue, @ryanwilson's [recommendation](https://github.com/firebase/firebase-ios-sdk/issues/3929#issuecomment-535950392) was to unlink the Firebase Performance module from the installation. 

I tried that, and it worked—unlinking Firebase Performance from our build has resolved the deadlock. 

So it seems safe to conclude that we are seeing a regression of the same issue where Firebase Performance deadlocks the main thread. Fortunately we weren't relying on Firebase Performance in our app to actually do anything important, so removing it was not really a problem.

That being said, I'm going to leave this issue open and await a response. If you come up with a possible fix for this issue, please let me know and I would be happy to test whether indeed it's fixed.

**Comment by paulb777** [comment]
Thanks for sharing the analysis. It should help with our investigation.

**Comment by visumickey** [comment]
@1oo7 We did fix this issue in the past and we made design changes where we do not deadlock with Remote Config. So, sounds like a regression. We will dig on this further.

Curious on how easy is it to reproduce the issue? I tried this on using Firebase version 11.0 and could not reproduce this. Will continue to try this out. But If you could share details about the version of XCode, iOS Version and your Podfile.lock, that could help immensely in figuring out the root cause of this issue.

**Comment by paulb777** [comment]
Could this one be related to #7975?

**Comment by visumickey** [comment]
Yes, at the look of it. It feels like this could be the cause of the issue. Let me take a look at the perf SDK to see how it acts for that change in remote config and see how we can move ahead on this.

**Comment by 1oo7** [comment]
>  But If you could share details about the version of XCode, iOS Version and your Podfile.lock, that could help immensely in figuring out the root cause of this issue.

Xcode 12.3, iOS 14.4.1, don't use CocoaPods. 

We were using Carthage for Firebase for awhile, but then Google stopped releasing new binaries via Carthage. When Carthage 0.37.0 came out with the ability to build XCFrameworks, we transitioned all our dependencies to XCFrameworks. However Firebase can't be built from source, and while Carthage 0.37.0 can now build XCFrameworks, sadly its ability to fetch remote binaries has yet to be updated to support fetching XCFrameworks from remote servers.

So in the meantime, as a temporary measure, we have added the Firebase XCFrameworks directly into our repo. 

We link the Firebase binaries to our app via a dynamic wrapper framework, which links to the static Firebase XCFrameworks that we use: 

- FirebaseABTesting.xcframework
- FirebaseAnalytics.xcframework
- FirebaseAppDistribution.xcframework
- FirebaseCore.xcframework
- FirebaseCoreDiagnostics.xcframework
- FirebaseCrashlytics.xcframework
- FirebaseDynamicLinks.xcframework
- FirebaseInstallations.xcframework
- ~~FirebasePerformance.xcframework~~ (removed to fix this bug)
- FirebaseRemoteConfig.xcframework
- GoogleAppMeasurement.xcframework
- GoogleDataTransport.xcframework
- GoogleToolboxForMac.xcframework
- GoogleUtilities.xcframework
- GTMSessionFetcher.xcframework
- nanopb.xcframework
- PromisesObjC.xcframework
- ~~Protobuf.xcframework~~ (removed because only FirebasePerformance needs it)

Before XCFrameworks, we employed the exact same scheme except with the "xc" removed from the file extensions of these.

Our approach had apparently been working fine up until sometime recently—possibly after we switched to XCFrameworks but I'm honestly not sure—when our QA found the deadlock issue, which only affects the initial launch of the app (but, oddly, not subsequent launches). 

I don't see why it being the XCFrameworks or Frameworks should matter because an XCFramework is just a folder full of Frameworks, and when we moved to XCFrameworks we did not change the version of Firebase we were using.

We'd hoped that updating to Firebase 7.11 would resolve the deadlocks, as there were some promising-sounding patch notes, but unfortunately not. 

Let me know if you need any other details of our setup.
