### ISSUE TITLE
Firebase 7.11.0 for Carthage

### ISSUE THREAD

**Issue by henrikix** [firebase/firebase-ios-sdk#7979]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.4.0
  * Installation method: Carthage
  * Firebase Component: Auth, Analytics etc

### [REQUIRED] Step 2: Describe the problem

I would like to update Firebase SDKs to make sure I'm up to date and avoid any possible issues with app privacy.
The provided `https://dl.google.com/dl/firebase/ios/carthage/...` links only seem to provide older versions (mostly 7.8.0 but 7.4.0 for analytics) and there is no mention of the `AnalyticsWithoutAdIdSupport` and Carthage anywhere

**Comment by ryanwilson** [comment]
Hi @henrikix - sorry for the trouble. You can see an explanation at https://github.com/firebase/firebase-ios-sdk/issues/7698#issuecomment-799023908, but the tl;dr is that Analytics switched to distribute the binary as an xcframework so we could support Apple silicon, but Carthage doesn't have a release that supports xcframeworks yet.

We have another issue tracking Apple silicon support for Carthage that is tracked at #7039 that would solve this issue as well. I'll close this for now to track things in a single location (#7039).

Thanks!

**Comment by paulb777** [comment]
In the meantime, the best workaround is to use the zip distribution - https://github.com/firebase/firebase-ios-sdk/releases/tag/7.11.0
