### ISSUE TITLE
OAuthProvider with tenant support

### ISSUE THREAD

**Issue by Busta117** [firebase/firebase-ios-sdk#7990]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version:  12.4
  * Firebase SDK version: 7.10.0
  * Installation method: `CocoaPods ` 
  * Firebase Component: Auth

#### Steps to reproduce:

there is a problem when we try to signin with a specific tenant and specific provider using OAuthProvider(see code below for a better understand)

in the file `FIROAuthProvider.m` line `311` where the params are added in the URL, the param `tid` is missed, and in some cases this param is needed to the correct functionality of the authentication, don't know if it's missed in the other providers, but in this case of the oauth provider is needed with a multi tenant implementation.

something to add is that Android SDK create the url in a right way when we use the tenant id in the same way.

#### Relevant Code:

let's use this code to perform the signin...
```
let auth = Auth.auth()
auth.tenantID = "tenant_id"
let provider = OAuthProvider(providerID: "provider_id", auth: auth)

auth.signIn(with: provider, uiDelegate: nil) { authResult, error in
// handle here the result
}
```

**Comment by rizafran** [comment]
Hi @Busta117, may I know if you're getting any error when signing in / can you share the expected vs actual behavior of your use case? Thanks.

**Comment by Busta117** [comment]
hi @rizafran 

there is no error at login, cuz login is never presented, this is the error when i try to load the webview of the login

```
Error Domain=FIRAuthErrorDomain Code=17063 "The app verification process has failed, print and inspect the error details for more information" UserInfo={FIRAuthErrorUserInfoNameKey=ERROR_WEB_USER_INTERACTION_FAILURE, NSLocalizedFailureReason=[auth/operation-not-allowed] - The identity provider configuration is not found., NSLocalizedDescription=The app verification process has failed, print and inspect the error details for more information}
```

and as i said, adding that `tid` param login webview is loaded normally, but sdk don't add that param

**Comment by weixifan** [comment]
Thank you for the information. I've filed an internal issue b/188421113 to track.
