### ISSUE TITLE
Incorrect comment in code.

### ISSUE THREAD

**Issue by mortenbekditlevsen** [firebase/firebase-ios-sdk#7992]
The comment on the referred line specifies that the order of `supportedAuthDomains` matters. But the outer loop is the authorized domains from the web request, so actually the first match in the authorized domains list 'wins'.
The inner and outer loops should be switched for the comment to be correct.

https://github.com/firebase/firebase-ios-sdk/blob/31307cdf7e2e7f0cf931ccf30f54fb409cad037d/FirebaseAuth/Sources/Utilities/FIRAuthWebUtils.m#L107

**Comment by mortenbekditlevsen** [comment]
Just to make my initial comment a bit clearer:

Currently, the `supportedAuthDomains` order does not matter (as opposed to what's stated in the comment) - the returned domain will be determined by the order of `response.authorizedDomains`.

If `response.authorizedDomains` contains `["my.web.app", "my.firebaseapp.com"],` then we would first look to see if `my.web.app` matched any of `["firebaseapp.com", "web.app"]`, which it does and then `"my.web.app"` will be used.

If the response order was different: `["my.firebaseapp.com", "my.web.app"]`, then the first match would be for `my.firebaseapp.com`.

And thus, contrary to the comment, it's not the order of `supportedAuthDomains` that matters, but the order of `response.authorizedDomains` that matters. And the latter is not controlled by the library, so that seems like an error - if indeed the order of `supportedAuthDomains` matters.

**Comment by paulb777** [comment]
@rosalyntan Should the comment be fixed or the code updated to match the comment?

cc: @renkelvin

**Comment by paulb777** [comment]
The code is updated in the release-11.0 branch: https://github.com/firebase/firebase-ios-sdk/blob/release-11.0/FirebaseAuth/Sources/Swift/Utilities/AuthWebUtils.swift#L117

**Comment by mortenbekditlevsen** [comment]
Well, on line 130 and 131 the iteration of supportedAuthDomains is still nested in the iteration of the response domains, so the order or supportedAuthDomains still doesn't matter, does it?

**Comment by paulb777** [comment]
Oops. Good catch, Morten! I'll reopen the issue and send a PR.
