### ISSUE TITLE
building for iOS Simulator, but linking in object file built for iOS

### ISSUE THREAD

**Issue by squm** [firebase/firebase-ios-sdk#8009]
> ld: in Pods/FirebaseAnalytics/Frameworks/FIRAnalyticsConnector.framework/FIRAnalyticsConnector(FIRAnalyticsConnector_.o),
> 
> building for iOS Simulator, but linking in object file built for iOS, file
> 
> 'Pods/FirebaseAnalytics/Frameworks/FIRAnalyticsConnector.framework/FIRAnalyticsConnector' for architecture arm64

hello, what is this?

**Comment by morganchen12** [comment]
Hey @squm, please fill out the issue template. Looks like you're using an older version of Firebase that doesn't support xcframeworks.

**Comment by squm** [comment]
> Hey @squm, please fill out the issue template. Looks like you're using an older version of Firebase that doesn't support xcframeworks.

I'm using cocoapods

**Comment by paulb777** [comment]
@squm Please share the Podfile and Podfile.lock.

**Comment by squm** [comment]
> @squm Please share the Podfile and Podfile.lock.


[Podfile.lock.zip](https://github.com/firebase/firebase-ios-sdk/files/6456634/Podfile.lock.zip)
[Podfile.zip](https://github.com/firebase/firebase-ios-sdk/files/6456639/Podfile.zip)

**Comment by squm** [comment]
that didn't change anything

**Comment by paulb777** [comment]
Try updating the minimum version to 10.0:

`platform :ios, '10.0'`

**Comment by squm** [comment]
updating ios version is lame solution @paulb777 and with your suggestion to run pod update or requesting a Podfile you are just wasting time pretending to solve issues

I hope any other maintainers will look into this, post is almost year old

https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios

> You have to do the same for the Pod project until all the cocoa pod vendors are done adding following in their Podspec.

**Comment by paulb777** [comment]
@squm As pointed out above, the `Podfile.lock` indicates that Firebase 6.x is being installed. We have no plans to support M1 simulators with Firebase 6.x.  At least Firebase 7 is required.

**Comment by morganchen12** [comment]
Closing as won't fix. @squm remember to abide by the [code of conduct](https://github.com/firebase/firebase-ios-sdk/blob/master/CODE_OF_CONDUCT.md) when interacting with other individuals in this repository.
