### ISSUE TITLE
Dynamic links sometimes not working

### ISSUE THREAD

**Issue by jesus-verse** [firebase/firebase-ios-sdk#8011]
### Step 1: Describe your environment

Xcode version: 12.2
iOS version: 14.3
Firebase SDK version: 7.1
Installation method: CocoaPods
Firebase Component: Dynamic Links

### Step 2: Describe the problem

Sometimes when a user tap a Dynamic Link and the app is not installed on the device, the application:openURL:options method does not receive the dynamic link url. It seems this is happening for 30% of our users without reason.

**Steps to reproduce:**

1. App not installed
2. Navigate to a dynamic link, like https://verse.me/event/DDfmSDto5hudo
3. Device show App Store page for app
4. From Xcode build and run app
5. application:openURL:options is not handled

Is there any way to debug or how to know why those users are not receiving the dynamic link ?

**Comment by rizafran** [comment]
Hi @jesus-verse, have you tried debugging your dynamic link by appending the `d=1` parameter to your link? You may check this [page](https://firebase.google.com/docs/dynamic-links/debug) for reference on debugging dynamic links. Thanks.

**Comment by jesus-verse** [comment]
I've tried to check with d=1 parameter and all seems fine.
I think the problem is related to some users don't receive the dynamic link. We are trying to find the reason why some users receive and some users don't receive the dynamic deeplink.

![Screenshot 2021-05-04 at 15 58 20](https://user-images.githubusercontent.com/52409139/117014917-901f5380-acf1-11eb-9b99-5ea1c596c664.png)
