### ISSUE TITLE
GoogleUtilities installed twice, impossible to archive app on Xcode 12.5

### ISSUE THREAD

**Issue by MaxiJunkie** [firebase/firebase-ios-sdk#8012]
Hello, everyone. I have updated Firebase libs from 7.0.1 to 7.11.0

 This is my Podfile:

<img width="496" alt="Снимок экрана 2021-04-30 в 14 18 52" src="https://user-images.githubusercontent.com/22434221/116688186-00129e80-a9bf-11eb-819b-09034d824e5d.png">

And I have a local pod with podspec (this pod is lowest pod in dependency hierarchy):

<img width="438" alt="Снимок экрана 2021-04-30 в 14 20 21" src="https://user-images.githubusercontent.com/22434221/116688305-34865a80-a9bf-11eb-83ee-3e82609919f6.png">

Xcode can compile project, but can't make archive, because GoogleUtilities installed twice.

<img width="394" alt="Снимок экрана 2021-04-30 в 14 27 06" src="https://user-images.githubusercontent.com/22434221/116688981-271da000-a9c0-11eb-8c59-9f6da59ed3fd.png">

**Comment by MaxiJunkie** [comment]
If I will drop FirebasePerformance problem will go away, but I need FBPerformance

**Comment by MaxiJunkie** [comment]
There is another solution. I can drop all Firebase dependencies from Local pod and this make help me

**Comment by paulb777** [comment]
@MaxiJunkie  Sorry about the trouble. This looks related to #6861. Please see the discussion there.
