### ISSUE TITLE
Duplicate symbols when using new AnalyticsWithoutAdIdSupport subspec

### ISSUE THREAD

**Issue by willbattel** [firebase/firebase-ios-sdk#8023]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 12.5 (12E262)
  * Firebase SDK version: 7.11.0
  * Installation method: CocoaPods
  * Firebase Component: Analytics

#### Steps to reproduce:

After switching from the `Firebase/Analytics` pod to the new `Firebase/AnalyticsWithoutAdIdSupport` pod, my build fails due to "_527 duplicate symbols for architecture arm64_".

```
...
duplicate symbol '_APMIncludeNSStringUTF32Category' in:
    /path/to/deriveddata/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/GoogleAppMeasurement/GoogleAppMeasurement.framework/GoogleAppMeasurement(NSString+UTF32.o)
    /path/to/deriveddata/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/GoogleAppMeasurementWithoutAdIdSupport/GoogleAppMeasurementWithoutAdIdSupport.framework/GoogleAppMeasurementWithoutAdIdSupport(NSString+UTF32.o)
duplicate symbol '_APMIncludeAPMScreenClassNameViewControllerCategory' in:
    /path/to/deriveddata/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/GoogleAppMeasurement/GoogleAppMeasurement.framework/GoogleAppMeasurement(UIViewController+APMScreenClassName.o)
    /path/to/deriveddata/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/GoogleAppMeasurementWithoutAdIdSupport/GoogleAppMeasurementWithoutAdIdSupport.framework/GoogleAppMeasurementWithoutAdIdSupport(UIViewController+APMScreenClassName.o)
duplicate symbol '_APMIncludeAPMScreenClassNameWindowCategory' in:
    /path/to/deriveddata/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/GoogleAppMeasurement/GoogleAppMeasurement.framework/GoogleAppMeasurement(UIWindow+APMScreenClassName.o)
    /path/to/deriveddata/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/GoogleAppMeasurementWithoutAdIdSupport/GoogleAppMeasurementWithoutAdIdSupport.framework/GoogleAppMeasurementWithoutAdIdSupport(UIWindow+APMScreenClassName.o)
ld: 527 duplicate symbols for architecture arm64
```

It looks to me like one or more of the modules (probably `Google-Mobile-Ads-SDK`) is still pulling in the original "with ad support" files (i.e., `GoogleAppMeasurement`) in addition to the "without ad support" files I was expecting (i.e., `GoogleAppMeasurementWithoutAdIdSupport`). I've tried `pod deintegrate` and `pod install` to no avail. Maybe I misunderstood how to use the new `AnalyticsWithoutAdIdSupport` subspec, but the release notes only mention its introduction and nothing more about using it. The Firebase docs also don't mention the new subspec - https://firebase.google.com/docs/ios/setup#available-pods.

If I switch back from `AnalyticsWithoutAdIdSupport` to `Analytics` and run `pod install` again, the project builds fine.

**Is `AnalyticsWithoutAdIdSupport` not compatible with `Google-Mobile-Ads-SDK`?**

#### Relevant Code:

Podfile:
```
# Uncomment the next line to define a global platform for your project
platform :ios, '11.2'

target 'myapp' do
  use_frameworks! :linkage => :static
  
  pod 'Firebase', '~> 7.11.0', :subspecs => ['AnalyticsWithoutAdIdSupport', 'Auth', 'Crashlytics', 'Firestore', 'Functions', 'Messaging', 'Performance', 'RemoteConfig', 'Storage']
  pod 'FirebaseUI', '~> 10.0.0', :subspecs => ['Auth', 'Phone', 'Storage']
  pod 'Google-Mobile-Ads-SDK', '~> 7.69.0'

  target 'myappTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'myappUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

EDIT: Just to be thorough, I tried with both `'Google-Mobile-Ads-SDK', '~> 7.69.0'` and `'Google-Mobile-Ads-SDK', '~> 8.4.0'`

**Comment by maksymmalyhin** [comment]
@willbattel Sorry for the trouble. Could you please post content of your Podfile.lock file to help understand why both `GoogleAppMeasurement` and `GoogleAppMeasurementWithoutAdIdSupport` are installed in your app.

**Comment by lotz** [comment]
This seems to be related to https://github.com/firebase/firebase-ios-sdk/issues/7958. I would love a version of `Google-Mobile-Ads-SDK` like `Google-Mobile-Ads-SDK-Without-Ad-Id-Support`. I've posted [a feature request here](https://groups.google.com/u/0/g/google-admob-ads-sdk/c/dHjMnBxZtmw).

**Comment by paulb777** [comment]
Yes - `Google-Mobile-Ads-SDK` is currently incompatible with `Firebase/AnalyticsWithoutAdIdSupport`. I'll close this in favor of #7958.
