### ISSUE TITLE
Possible integer overflow and other minor code quality opportunities

### ISSUE THREAD

**Issue by armcknight** [firebase/firebase-ios-sdk#8026]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: N/A
  * Firebase SDK version: latest (instances present on `master` `HEAD` as of this filing)
  * Installation method: N/A
  * Firebase Component: Crashlytics

### [REQUIRED] Step 2: Describe the problem

As mentioned in https://github.com/firebase/firebase-ios-sdk/issues/7702, I found a few possible code quality issues. You can see my [draft PR](https://github.com/specto-dev/firebase-ios-sdk-1/pull/1) for proposed solutions.

#### Relevant Code:

- comparison of signed and unsigned integers can lead to possible integer overflow on implicit cast: https://github.com/firebase/firebase-ios-sdk/blob/master/Crashlytics/Crashlytics/Helpers/FIRCLSFile.m#L240
- passing the wrong variable to a log statement: https://github.com/firebase/firebase-ios-sdk/blob/master/Crashlytics/Crashlytics/Handlers/FIRCLSSignal.c#L189
- dead function with a hardcoded return value: 
    - https://github.com/firebase/firebase-ios-sdk/blob/master/Crashlytics/Crashlytics/Components/FIRCLSProcess.c#L60-L62 
    - https://github.com/firebase/firebase-ios-sdk/blob/master/Crashlytics/Crashlytics/Components/FIRCLSProcess.h#L35
    - the sole callsite where it doesn't actually do anything: https://github.com/firebase/firebase-ios-sdk/blob/master/Crashlytics/Crashlytics/Handlers/FIRCLSHandler.m#L51

**Comment by elenadoty** [comment]
Hi @armcknight,
Thanks for the suggestions! We've incorporated them as well as the signal propagation feature request, and the changes should go out in the next release.
