### ISSUE TITLE
page.link domain should be listed in the public suffix list

### ISSUE THREAD

**Issue by callionica** [firebase/firebase-ios-sdk#8027]
I know this isn't iOS specific, but seems like a security issue, so...

It appears that your product/company owns the page.link domain. I believe you allow subdomains of page.link to be used by mutually-untrusting parties. As a result, you should ensure separation of cookies, storage, passwords saved in the browser, etc for separate subdomains. The way to do that is to list your domain in the public suffix list: https://github.com/publicsuffix/list

**Comment by rizafran** [comment]
Hi @callionica, thanks for sharing your feedback. I've found similar request internally, but we can't share any details or timeline as to when this could be materialized. I'll keep this issue open and we will let you know of any updates regarding this. Thanks!

**Comment by gsakakihara** [comment]
The page.link domain is used for Firebase Dynamic Links and doesn't host third party content and doesn't allow third parties to access anything like cookies, storage, or passwords so I don't think that this would apply.
