### ISSUE TITLE
Use buildcache to speed up CI

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#8052]
See https://github.com/marketplace/actions/buildcache-action and https://twitter.com/fastsquatch/status/1390465013983367176

There is potentially a 40-50% speedup opportunity

**Comment by paulb777** [comment]
Next step is to verify that the merged #9055 makes a difference.

**Comment by paulb777** [comment]
A minimal random survey of about 10 before and after shows some nice speedups - like 9 minutes to 6 minutes. 

There is likely another project for a deeper investigation to look at more data and understand why some jobs look to be unchanged.  

But I'll close this one here. cc: @granluo 

Thanks @a-25

**Comment by a-25** [comment]
Hello, @paulb777. Glad to hear.
Could you post examples of unchanged jobs? I used buildcache not in all of them, only in those who needed building.

**Comment by paulb777** [comment]
@a-25 See the spm job in https://github.com/firebase/firebase-ios-sdk/runs/4531139622?check_suite_focus=true and https://github.com/firebase/firebase-ios-sdk/runs/4604330680?check_suite_focus=true.  The Swift build went from 5 minutes to 1 minute, but the iOS Unit Tests - which is also primarily a build  - stayed about the same.

**Comment by a-25** [comment]
I see, thanks. Possibly I could suggest adding statistics (`...buildcache -s`) after each build job instead of an aggregate one. It could help speed debugging.
