### ISSUE TITLE
API key is missing

### ISSUE THREAD

**Issue by iharandreyev** [firebase/firebase-ios-sdk#8062]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5
  * Firebase SDK version: 6.34.0
  * Installation method: `CocoaPods
  * Firebase Component: DynamicLinks

### [REQUIRED] Step 2: Describe the problem

Building for iOS 9.3.5. `DynamicLinkComponentsOptions` `shorten` method results with error:
`Error Domain=com.firebase.durabledeeplink Code=0 "API key is missing." UserInfo={NSLocalizedFailureReason=API key is missing.}`
I've tried re-downloading and replacing GoogleService-Info.plist, but it didn't help

#### Steps to reproduce:

Here's the pod configuration I use: [Podfile.zip](https://github.com/firebase/firebase-ios-sdk/files/6466050/Podfile.zip)

**Comment by rizafran** [comment]
Thanks for reporting, @iharandreyev. First thing to check here is the SDK version you're using. To isolate any dependency issues, I would suggest updating to the [latest SDK version](https://firebase.google.com/support/release-notes/ios) available to ensure that old known bugs are fixed and it has up-to-date features.

**Comment by iharandreyev** [comment]
pod update Firebase/Core causes several versions of Firebase to be installed

Here're logs

Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing Firebase 3.6.0 (was 6.25.0)
Installing Firebase 8.0.0 (was 6.25.0)
Installing FirebaseAnalytics 3.4.2 (was 6.5.1)
Installing FirebaseCore 8.0.0 (was 6.7.1)
Installing FirebaseCoreDiagnostics 8.0.0 (was 1.3.0)
Installing FirebaseCrashlytics 8.0.0 (was 4.1.0)
Installing FirebaseDynamicLinks 1.3.0 (was 4.0.8)
Installing FirebaseInstallations 8.0.0 (was 1.2.0)
Installing FirebaseInstanceID (1.0.9)
Installing GoogleDataTransport 9.0.0 (was 6.1.1)
Installing GoogleInterchangeUtilities (1.2.2)
Installing GoogleSymbolUtilities (1.1.2)
Installing GoogleUtilities 1.3.2 (was 6.6.0)
Installing GoogleUtilities 7.4.1 (was 6.6.0)
Installing PromisesObjC 1.2.12 (was 1.2.8)
Installing nanopb 2.30908.0 (was 1.30905.0)
Removing FirebaseAnalyticsInterop
Removing FirebaseCoreDiagnosticsInterop
Removing GoogleAppMeasurement
Removing GoogleDataTransportCCTSupport
Generating Pods project
Integrating client project
Pod installation complete! There are 29 dependencies from the Podfile and 47 total pods installed.

[!] Unable to read the license file `LICENSE` for the spec `Firebase (8.0.0)`

[!] Unable to read the license file `LICENSE` for the spec `GoogleUtilities (7.4.1)`

[!] Unable to read the license file `LICENSE` for the spec `Firebase (8.0.0)`

[!] Unable to read the license file `LICENSE` for the spec `GoogleUtilities (7.4.1)`

[!] Unable to read the license file `LICENSE` for the spec `Firebase (8.0.0)`

[!] Unable to read the license file `LICENSE` for the spec `GoogleUtilities (7.4.1)`

[!] Unable to read the license file `LICENSE` for the spec `Firebase (8.0.0)`

[!] Unable to read the license file `LICENSE` for the spec `GoogleUtilities (7.4.1)`

[!] Unable to read the license file `LICENSE` for the spec `Firebase (8.0.0)`

[!] Unable to read the license file `LICENSE` for the spec `GoogleUtilities (7.4.1)`

[!] Unable to read the license file `LICENSE` for the spec `Firebase (8.0.0)`

[!] Unable to read the license file `LICENSE` for the spec `GoogleUtilities (7.4.1)`

[!] Unable to read the license file `LICENSE` for the spec `Firebase (8.0.0)`

[!] Unable to read the license file `LICENSE` for the spec `GoogleUtilities (7.4.1)`

[!] Unable to read the license file `LICENSE` for the spec `Firebase (8.0.0)`

[!] Unable to read the license file `LICENSE` for the spec `GoogleUtilities (7.4.1)`

[!] [Xcodeproj] Generated duplicate UUIDs:

PBXFileReference -- Pods.xcodeproj/mainGroup/children/children:children:|,|,|,|,|,|,|,|,|,displayName:Action,isa:PBXGroup,name:Action,path:Action,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:Alamofire,isa:PBXGroup,name:Alamofire,path:Alamofire,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,displayName:AlamofireImage,isa:PBXGroup,name:AlamofireImage,path:AlamofireImage,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,displayName:CardIO,isa:PBXGroup,name:CardIO,path:CardIO,sourceTree:<group>,,children:|,|,|,displayName:CocoaLumberjack,isa:PBXGroup,name:CocoaLumberjack,path:CocoaLumberjack,sourceTree:<group>,,children:|,|,|,displayName:FBSDKCoreKit,isa:PBXGroup,name:FBSDKCoreKit,path:FBSDKCoreKit,sourceTree:<group>,,children:|,|,displayName:FBSDKLoginKit,isa:PBXGroup,name:FBSDKLoginKit,path:FBSDKLoginKit,sourceTree:<group>,,children:|,|,displayName:Firebase,isa:PBXGroup,name:Firebase,path:Firebase,sourceTree:<group>,,children:|,|,displayName:FirebaseAnalytics,isa:PBXGroup,name:FirebaseAnalytics,path:FirebaseAnalytics,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:FirebaseCore,isa:PBXGroup,name:FirebaseCore,path:FirebaseCore,sourceTree:<group>,,children:|,|,|,|,|,|,|,displayName:FirebaseCoreDiagnostics,isa:PBXGroup,name:FirebaseCoreDiagnostics,path:FirebaseCoreDiagnostics,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:FirebaseCrashlytics,isa:PBXGroup,name:FirebaseCrashlytics,path:FirebaseCrashlytics,sourceTree:<group>,,children:|,|,displayName:FirebaseDynamicLinks,isa:PBXGroup,name:FirebaseDynamicLinks,path:FirebaseDynamicLinks,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:FirebaseInstallations,isa:PBXGroup,name:FirebaseInstallations,path:FirebaseInstallations,sourceTree:<group>,,children:|,|,displayName:FirebaseInstanceID,isa:PBXGroup,name:FirebaseInstanceID,path:FirebaseInstanceID,sourceTree:<group>,,children:|,|,displayName:Flurry-iOS-SDK,isa:PBXGroup,name:Flurry-iOS-SDK,path:Flurry-iOS-SDK,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:GoogleDataTransport,isa:PBXGroup,name:GoogleDataTransport,path:GoogleDataTransport,sourceTree:<group>,,children:|,|,displayName:GoogleInterchangeUtilities,isa:PBXGroup,name:GoogleInterchangeUtilities,path:GoogleInterchangeUtilities,sourceTree:<group>,,children:|,|,|,displayName:GoogleMaps,isa:PBXGroup,name:GoogleMaps,path:GoogleMaps,sourceTree:<group>,,children:|,|,displayName:GoogleSymbolUtilities,isa:PBXGroup,name:GoogleSymbolUtilities,path:GoogleSymbolUtilities,sourceTree:<group>,,children:|,|,displayName:GoogleUtilities,isa:PBXGroup,name:GoogleUtilities,path:GoogleUtilities,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:InputBarAccessoryView,isa:PBXGroup,name:InputBarAccessoryView,path:InputBarAccessoryView,sourceTree:<group>,,children:|,|,|,displayName:MBProgressHUD,isa:PBXGroup,name:MBProgressHUD,path:MBProgressHUD,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:MessageKit,isa:PBXGroup,name:MessageKit,path:MessageKit,sourceTree:<group>,,children:|,|,|,|,|,displayName:PromiseKit,isa:PBXGroup,name:PromiseKit,path:PromiseKit,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:PromisesObjC,isa:PBXGroup,name:PromisesObjC,path:PromisesObjC,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,displayName:PureLayout,isa:PBXGroup,name:PureLayout,path:PureLayout,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,displayName:QRCodeReader.swift,isa:PBXGroup,name:QRCodeReader.swift,path:QRCodeReader.swift,sourceTree:<group>,,children:|,displayName:R.swift,isa:PBXGroup,name:R.swift,path:R.swift,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:R.swift.Library,isa:PBXGroup,name:R.swift.Library,path:R.swift.Library,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:Realm,isa:PBXGroup,name:Realm,path:Realm,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:RealmSwift,isa:PBXGroup,name:RealmSwift,path:RealmSwift,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:RxCocoa,isa:PBXGroup,name:RxCocoa,path:RxCocoa,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,displayName:RxGoogleMaps,isa:PBXGroup,name:RxGoogleMaps,path:RxGoogleMaps,sourceTree:<group>,,children:|,|,displayName:RxKeyboard,isa:PBXGroup,name:RxKeyboard,path:RxKeyboard,sourceTree:<group>,,children:|,|,|,|,|,displayName:RxRelay,isa:PBXGroup,name:RxRelay,path:RxRelay,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:RxSwift,isa:PBXGroup,name:RxSwift,path:RxSwift,sourceTree:<group>,,children:|,|,|,|,|,|,displayName:SAMKeychain,isa:PBXGroup,name:SAMKeychain,path:SAMKeychain,sourceTree:<group>,,children:|,|,|,displayName:SCrypto,isa:PBXGroup,name:SCrypto,path:SCrypto,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:SSZipArchive,isa:PBXGroup,name:SSZipArchive,path:SSZipArchive,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,displayName:Sica,isa:PBXGroup,name:Sica,path:Sica,sourceTree:<group>,,children:|,displayName:SwiftLint,isa:PBXGroup,name:SwiftLint,path:SwiftLint,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:Swinject,isa:PBXGroup,name:Swinject,path:Swinject,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,displayName:nanopb,isa:PBXGroup,name:nanopb,path:nanopb,sourceTree:<group>,,children:|,|,|,|,displayName:youtube-ios-player-helper,isa:PBXGroup,name:youtube-ios-player-helper,path:youtube-ios-player-helper,sourceTree:<group>,,displayName:Pods,isa:PBXGroup,name:Pods,sourceTree:<group>,/Pods/children/children:children:|,displayName:Frameworks,isa:PBXGroup,name:Frameworks,sourceTree:<group>,,children:|,|,|,|,displayName:Support Files,isa:PBXGroup,name:Support Files,path:../Target Support Files/GoogleUtilities,sourceTree:<group>,,displayName:GoogleUtilities,isa:PBXGroup,name:GoogleUtilities,path:GoogleUtilities,sourceTree:<group>,/Pods/GoogleUtilities/children/children:displayName:GoogleUtilities.debug.xcconfig,includeInIndex:1,isa:PBXFileReference,lastKnownFileType:text.xcconfig,path:GoogleUtilities.debug.xcconfig,sourceTree:<group>,,displayName:GoogleUtilities.release.xcconfig,includeInIndex:1,isa:PBXFileReference,lastKnownFileType:text.xcconfig,path:GoogleUtilities.release.xcconfig,sourceTree:<group>,,displayName:GoogleUtilities.debug.xcconfig,includeInIndex:1,isa:PBXFileReference,lastKnownFileType:text.xcconfig,path:GoogleUtilities.debug.xcconfig,sourceTree:<group>,,displayName:GoogleUtilities.release.xcconfig,includeInIndex:1,isa:PBXFileReference,lastKnownFileType:text.xcconfig,path:GoogleUtilities.release.xcconfig,sourceTree:<group>,,displayName:Support Files,isa:PBXGroup,name:Support Files,path:../Target Support Files/GoogleUtilities,sourceTree:<group>,/Pods/GoogleUtilities/Support Files/children/displayName:GoogleUtilities.debug.xcconfig,includeInIndex:1,isa:PBXFileReference,lastKnownFileType:text.xcconfig,path:GoogleUtilities.debug.xcconfig,sourceTree:<group>,/Pods/GoogleUtilities/Support Files/GoogleUtilities.debug.xcconfig
PBXFileReference -- Pods.xcodeproj/mainGroup/children/children:children:|,|,|,|,|,|,|,|,|,displayName:Action,isa:PBXGroup,name:Action,path:Action,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:Alamofire,isa:PBXGroup,name:Alamofire,path:Alamofire,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,displayName:AlamofireImage,isa:PBXGroup,name:AlamofireImage,path:AlamofireImage,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,displayName:CardIO,isa:PBXGroup,name:CardIO,path:CardIO,sourceTree:<group>,,children:|,|,|,displayName:CocoaLumberjack,isa:PBXGroup,name:CocoaLumberjack,path:CocoaLumberjack,sourceTree:<group>,,children:|,|,|,displayName:FBSDKCoreKit,isa:PBXGroup,name:FBSDKCoreKit,path:FBSDKCoreKit,sourceTree:<group>,,children:|,|,displayName:FBSDKLoginKit,isa:PBXGroup,name:FBSDKLoginKit,path:FBSDKLoginKit,sourceTree:<group>,,children:|,|,displayName:Firebase,isa:PBXGroup,name:Firebase,path:Firebase,sourceTree:<group>,,children:|,|,displayName:FirebaseAnalytics,isa:PBXGroup,name:FirebaseAnalytics,path:FirebaseAnalytics,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:FirebaseCore,isa:PBXGroup,name:FirebaseCore,path:FirebaseCore,sourceTree:<group>,,children:|,|,|,|,|,|,|,displayName:FirebaseCoreDiagnostics,isa:PBXGroup,name:FirebaseCoreDiagnostics,path:FirebaseCoreDiagnostics,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:FirebaseCrashlytics,isa:PBXGroup,name:FirebaseCrashlytics,path:FirebaseCrashlytics,sourceTree:<group>,,children:|,|,displayName:FirebaseDynamicLinks,isa:PBXGroup,name:FirebaseDynamicLinks,path:FirebaseDynamicLinks,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:FirebaseInstallations,isa:PBXGroup,name:FirebaseInstallations,path:FirebaseInstallations,sourceTree:<group>,,children:|,|,displayName:FirebaseInstanceID,isa:PBXGroup,name:FirebaseInstanceID,path:FirebaseInstanceID,sourceTree:<group>,,children:|,|,displayName:Flurry-iOS-SDK,isa:PBXGroup,name:Flurry-iOS-SDK,path:Flurry-iOS-SDK,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:GoogleDataTransport,isa:PBXGroup,name:GoogleDataTransport,path:GoogleDataTransport,sourceTree:<group>,,children:|,|,displayName:GoogleInterchangeUtilities,isa:PBXGroup,name:GoogleInterchangeUtilities,path:GoogleInterchangeUtilities,sourceTree:<group>,,children:|,|,|,displayName:GoogleMaps,isa:PBXGroup,name:GoogleMaps,path:GoogleMaps,sourceTree:<group>,,children:|,|,displayName:GoogleSymbolUtilities,isa:PBXGroup,name:GoogleSymbolUtilities,path:GoogleSymbolUtilities,sourceTree:<group>,,children:|,|,displayName:GoogleUtilities,isa:PBXGroup,name:GoogleUtilities,path:GoogleUtilities,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:InputBarAccessoryView,isa:PBXGroup,name:InputBarAccessoryView,path:InputBarAccessoryView,sourceTree:<group>,,children:|,|,|,displayName:MBProgressHUD,isa:PBXGroup,name:MBProgressHUD,path:MBProgressHUD,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:MessageKit,isa:PBXGroup,name:MessageKit,path:MessageKit,sourceTree:<group>,,children:|,|,|,|,|,displayName:PromiseKit,isa:PBXGroup,name:PromiseKit,path:PromiseKit,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:PromisesObjC,isa:PBXGroup,name:PromisesObjC,path:PromisesObjC,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,displayName:PureLayout,isa:PBXGroup,name:PureLayout,path:PureLayout,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,displayName:QRCodeReader.swift,isa:PBXGroup,name:QRCodeReader.swift,path:QRCodeReader.swift,sourceTree:<group>,,children:|,displayName:R.swift,isa:PBXGroup,name:R.swift,path:R.swift,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:R.swift.Library,isa:PBXGroup,name:R.swift.Library,path:R.swift.Library,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:Realm,isa:PBXGroup,name:Realm,path:Realm,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:RealmSwift,isa:PBXGroup,name:RealmSwift,path:RealmSwift,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:RxCocoa,isa:PBXGroup,name:RxCocoa,path:RxCocoa,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,displayName:RxGoogleMaps,isa:PBXGroup,name:RxGoogleMaps,path:RxGoogleMaps,sourceTree:<group>,,children:|,|,displayName:RxKeyboard,isa:PBXGroup,name:RxKeyboard,path:RxKeyboard,sourceTree:<group>,,children:|,|,|,|,|,displayName:RxRelay,isa:PBXGroup,name:RxRelay,path:RxRelay,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:RxSwift,isa:PBXGroup,name:RxSwift,path:RxSwift,sourceTree:<group>,,children:|,|,|,|,|,|,displayName:SAMKeychain,isa:PBXGroup,name:SAMKeychain,path:SAMKeychain,sourceTree:<group>,,children:|,|,|,displayName:SCrypto,isa:PBXGroup,name:SCrypto,path:SCrypto,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:SSZipArchive,isa:PBXGroup,name:SSZipArchive,path:SSZipArchive,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,displayName:Sica,isa:PBXGroup,name:Sica,path:Sica,sourceTree:<group>,,children:|,displayName:SwiftLint,isa:PBXGroup,name:SwiftLint,path:SwiftLint,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:Swinject,isa:PBXGroup,name:Swinject,path:Swinject,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,displayName:nanopb,isa:PBXGroup,name:nanopb,path:nanopb,sourceTree:<group>,,children:|,|,|,|,displayName:youtube-ios-player-helper,isa:PBXGroup,name:youtube-ios-player-helper,path:youtube-ios-player-helper,sourceTree:<group>,,displayName:Pods,isa:PBXGroup,name:Pods,sourceTree:<group>,/Pods/children/children:children:|,displayName:Frameworks,isa:PBXGroup,name:Frameworks,sourceTree:<group>,,children:|,|,|,|,displayName:Support Files,isa:PBXGroup,name:Support Files,path:../Target Support Files/GoogleUtilities,sourceTree:<group>,,displayName:GoogleUtilities,isa:PBXGroup,name:GoogleUtilities,path:GoogleUtilities,sourceTree:<group>,/Pods/GoogleUtilities/children/children:displayName:GoogleUtilities.debug.xcconfig,includeInIndex:1,isa:PBXFileReference,lastKnownFileType:text.xcconfig,path:GoogleUtilities.debug.xcconfig,sourceTree:<group>,,displayName:GoogleUtilities.release.xcconfig,includeInIndex:1,isa:PBXFileReference,lastKnownFileType:text.xcconfig,path:GoogleUtilities.release.xcconfig,sourceTree:<group>,,displayName:GoogleUtilities.debug.xcconfig,includeInIndex:1,isa:PBXFileReference,lastKnownFileType:text.xcconfig,path:GoogleUtilities.debug.xcconfig,sourceTree:<group>,,displayName:GoogleUtilities.release.xcconfig,includeInIndex:1,isa:PBXFileReference,lastKnownFileType:text.xcconfig,path:GoogleUtilities.release.xcconfig,sourceTree:<group>,,displayName:Support Files,isa:PBXGroup,name:Support Files,path:../Target Support Files/GoogleUtilities,sourceTree:<group>,/Pods/GoogleUtilities/Support Files/children/displayName:GoogleUtilities.release.xcconfig,includeInIndex:1,isa:PBXFileReference,lastKnownFileType:text.xcconfig,path:GoogleUtilities.release.xcconfig,sourceTree:<group>,/Pods/GoogleUtilities/Support Files/GoogleUtilities.release.xcconfig

[!] [Xcodeproj] Generated duplicate UUIDs:

PBXAggregateTarget -- 8D7F5D5DD528D21A72DC87ADA5B12E2D

**Comment by iharandreyev** [comment]
Solution proposed [here](https://github.com/CocoaPods/CocoaPods/issues/8206) doesn't help

**Comment by iharandreyev** [comment]
Okay, here's the deal: the error only occurs when running under simulator environment. It would be great if you replaced the error message with something more concrete.

**Comment by paulb777** [comment]
See #7782.  Firebase 7.0.0 dropped support for iOS 9.
