### ISSUE TITLE
Functions: httpsCallable().call() doesn't make a request in iOS app

### ISSUE THREAD

**Issue by aledap** [firebase/firebase-ios-sdk#8079]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5
  * Firebase SDK version: 8.0.0
  * Installation method: CocoaPods
  * Firebase Component: Functions

### [REQUIRED] Step 2: Describe the problem
iOS code using Functions.functions().httpsCallable(...).call(...) doesn't make a call.

#### Steps to reproduce

- Deploy a simple HTTPS callable function
- Call said function from iOS client app using Firebase emulator. 
- Calling the functions return an error
- There seems to be no log output on the console.

#### Relevant Code:

HTTP callable function:
```
exports.addMessage = functions.https.onCall((data, context) => {
  const text = data.text;
  console.log(text)
  
  return {
      text: "100"
    };
  })
```

Swift code to call function:
In my AppDelegate.swift class:
`Functions.functions().useEmulator(withHost:"localhost", port:5001)`

In my View Controller class:
```
lazy var functions = Functions.functions()
functions.httpsCallable("addMessage").call(["text": "test"]) { (result, error) in
            self.actionButton.toggleLoadingIndicator(false)
            if let error = error {
                print("Firebase error: \(error)")
                
            }
            if let text = (result?.data as? [String: Any]) {
                print("SUCCESS: \(text)")  
            }
        }
```
The above functions return the following error:
`Firebase error: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}`

Edit: It's also worth nothing that other Cloud Functions (Firestore triggers) are also deployed within the same project, and they run without issues on the emulator. The issue is only for HTTP callable functions.

**Comment by paulb777** [comment]
This might be related to #7783

**Comment by aledap** [comment]
> #7783

Already tried setting my local instance of functions to use the emulator. It returns a different error.

Xcode console logs:
` [Firebase/Performance][I-PRF100009] Logging network request trace - http://localhost:5001/copper-bot-289211/us-central1/addMessage, Response code: 404, 36.0950ms`

Error returned in callback 
```
Firebase error: Error Domain=com.firebase.functions Code=5 "NOT FOUND" UserInfo={NSLocalizedDescription=NOT FOUND}
2021-05-14 18:57:22.841356+0500 HairS[10632:196725] 8.0.0 - [Firebase/Installations][I-FIS002001] -[FIRInstallationsIDController installationWithValidAuthTokenForcingRefresh:0], appName: __FIRAPP_DEFAULT
```

**Comment by morganchen12** [comment]
@aledap is this issue reproducible in Firebase 7.11?
