### ISSUE TITLE
InAppMessagingDisplayMessage shows incorrect type for imageOnly 

### ISSUE THREAD

**Issue by fumito-ito** [firebase/firebase-ios-sdk#8081]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.3.0
  * Installation method: `Carthage`
  * Firebase Component: InAppMessaging

### [REQUIRED] Step 2: Describe the problem

ImageOnly message shows incorrect message type. It may be a bug of parsing passing data.

#### Steps to reproduce:

1. add new message as `Image Only` message at Firebase Console
2. send test message
3. open app with following code

#### Relevant Code:

```swift
class Sample: InAppMessagingDisplay {
    func displayMessage(_ messageForDisplay: InAppMessagingDisplayMessage, displayDelegate: InAppMessagingDisplayDelegate) {
        switch messageForDisplay.type {
        case .banner, .card:
            break
        case .modal:
            print("When set `imageOnly` message at firebase console, message will be received with `modal` type")
        case .imageOnly:
            print("This line will be never called.")
        @unknown default:
            break
        }
    }
}

// at AppDelegate
InAppMessaging.inAppMessaging().messageDisplayComponent = Sample()
```

**Comment by yakovmanshin** [comment]
There’s this issue indeed. I’ve faced it myself, and I think I’ll look into it.

@fumito-ito As a quick fix, you can determine message type by type-casting the `messageForDisplay` instance, like that:

```swift
switch messageForDisplay {
    case let bannerMessage as InAppMessagingBannerDisplay:
        print(bannerMessage)
    case let cardMessage as InAppMessagingCardDisplay:
        print(cardMessage)
    case let imageOnlyMessage as InAppMessagingImageOnlyDisplay:
        print(imageOnlyMessage)
    case let modalMessage as InAppMessagingModalDisplay:
        print(modalMessage)
    default:
        break
}
```

In fact, that’s the way message type is determined in the original implementation of IAM.

**Comment by christibbs** [comment]
This is a one-liner fix that will go out with the next release.

Bug is [here](https://github.com/firebase/firebase-ios-sdk/blob/e789676eaee39adfeb0ddb19abb2b72bb03c93d8/FirebaseInAppMessaging/Sources/RenderingObjects/FIRInAppMessagingRenderingDataClasses.m#L272).

**Comment by christibbs** [comment]
Thanks for the report @fumito-ito.
