### ISSUE TITLE
Firebase SDK在FBLPromise上崩溃   Firbase 7.11.0     CocoPods

### ISSUE THREAD

**Issue by junjunHappyEvenTwo** [firebase/firebase-ios-sdk#8091]
-[FBLPromise HTTPBody]: unrecognized selector sent to instance 0x2812e26a0
2021-05-13 18:28:05.128681+0800 ProductName[4278:1156379] Uncaught exception: NSInvalidArgumentException: -[FBLPromise HTTPBody]: unrecognized selector sent to instance 0x2812e26a0
(
	0   CoreFoundation                      0x00000001a44fd880 935533F2-35EE-314E-A760-E74521F68435 + 1202304
	1   libobjc.A.dylib                     0x00000001b946cc50 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001a440495c 935533F2-35EE-314E-A760-E74521F68435 + 182620
	3   CoreFoundation                      0x00000001a4500438 935533F2-35EE-314E-A760-E74521F68435 + 1213496
	4   CoreFoundation                      0x00000001a4502740 _CF_forwarding_prep_0 + 96
	5   NeoSDK                              0x00000001061239e4 -[GDTCCTUploadOperation updateNextUploadTimeWithResponse:forTarget:] + 112
	6   NeoSDK                              0x0000000106122eac __64-[GDTCCTUploadOperation sendURLRequestWithBatch:target:storage:]_block_invoke + 76
	7   NeoSDK                              0x000000010638bc6c __56-[FBLPromise chainOnQueue:chainedFulfill:chainedReject:]_block_invoke.67 + 92
	8   NeoSDK                              0x000000010638b574 __44-[FBLPromise observeOnQueue:fulfill:reject:]_block_invoke_2 + 100
	9   libdispatch.dylib                   0x00000001a40f024c 0F3905E0-6720-3D08-9AE0-A43A8DA244C0 + 8780
	10  libdispatch.dylib                   0x00000001a40f1db0 0F3905E0-6720-3D08-9AE0-A43A8DA244C0 + 15792
	11  libdispatch.dylib                   0x00000001a40f920c 0F3905E0-6720-3D08-9AE0-A43A8DA244C0 + 45580
	12  libdispatch.dylib                   0x00000001a40f9c5c 0F3905E0-6720-3D08-9AE0-A43A8DA244C0 + 48220
	13  libdispatch.dylib                   0x00000001a4103d78 0F3905E0-6720-3D08-9AE0-A43A8DA244C0 + 89464
	14  libsystem_pthread.dylib             0x00000001efccf804 _pthread_wqthread + 276
	15  libsystem_pthread.dylib             0x00000001efcd675c start_wqthread + 8
)
2021-05-13 18:28:05.168385+0800 ProductName[4278:1156379] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[FBLPromise HTTPBody]: unrecognized selector sent to instance 0x2812e26a0'
*** First throw call stack:
(0x1a44fd86c 0x1b946cc50 0x1a440495c 0x1a4500438 0x1a4502740 0x1061239e4 0x106122eac 0x10638bc6c 0x10638b574 0x1a40f024c 0x1a40f1db0 0x1a40f920c 0x1a40f9c5c 0x1a4103d78 0x1efccf804 0x1efcd675c)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[FBLPromise HTTPBody]: unrecognized selector sent to instance 0x2812e26a0'

**Comment by rizafran** [comment]
Thanks for rerporting, @junjunHappyEvenTwo. The error you encountered seems to be related to issue #7939. With this, please try the solution provided on that issue, and see if the issue will persist. Thanks.

**Comment by maksymmalyhin** [comment]
Could be related to #8005.

**Comment by paulb777** [comment]
@junjunHappyEvenTwo Please share the `Podfile.lock` file.
