### ISSUE TITLE
Update to Firebase 8.0.0 triggers CocoaPods warning on `EXCLUDED_ARCHS` from GoogleTagManager 7.3.0

### ISSUE THREAD

**Issue by mvandervelden** [firebase/firebase-ios-sdk#8092]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5
  * Firebase SDK version: 8.0.0
  * Installation method: `CocoaPods v. 1.10.1`
  * Firebase Component: GoogleTagManager

#### Steps to reproduce:

_tl;dr: Use this [demo project](https://github.com/mvandervelden/GTMPodIssueTest), and follow the readme._

Our app uses a number of Google/Firebase pods, and I tried to update all of them to the latest version (Firebase 8.0.0):
```
pod 'Firebase/Analytics'
pod 'GoogleTagManager'
#...
pod 'Usabilla'
```

But, Cocoapods triggers a warning:
`[!] Can't merge user_target_xcconfig for pod targets: ["GoogleTagManager", "Usabilla"]. Singular build setting EXCLUDED_ARCHS[sdk=iphonesimulator*] has different values.` Once for each target & build configuration we have.

Our previous version of Firebase was 7.11.0, GoogleTagManager was on 7.2.0.

I noticed that the [old GTM version](https://github.com/CocoaPods/Specs/blob/master/Specs/9/5/6/GoogleTagManager/7.2.0/GoogleTagManager.podspec.json) did not set a fixed `EXCLUDED_ARCHS` value, but [the new one does](https://github.com/CocoaPods/Specs/blob/master/Specs/9/5/6/GoogleTagManager/7.3.0/GoogleTagManager.podspec.json).

I believe that pods should not set this build setting on `user_target_xcconfig` in the podspec, but only on `pod_target_xcconfig`. (no other pod we're using is doing this).

I realize this conflict only exists because one of our other dependencies (Usabilla) also violated this setting, using a different set of excluded architectures, but as this might create issues with other pods or build configurations as well, I wanted to to raise this as a bug.

**Comment by paulb777** [comment]
Thanks for the report. GoogleTagManager does not yet support the Apple M1 simulator and I believe this is related.

@tsunghung Please take a look.

**Comment by tsunghung** [comment]
Thanks a lot for the report!
I removed the `user_target_xcconfig ` and `pod_target_xcconfig ` workaround. Please update GoogleTagManager to [7.3.1](https://github.com/CocoaPods/Specs/blob/master/Specs/9/5/6/GoogleTagManager/7.3.1/GoogleTagManager.podspec.json).

**Comment by mvandervelden** [comment]
@tsunghung Thanks for the quick response! I verified that it's no longer an issue with the latest version 🙇
