### ISSUE TITLE
Duplicate symbols - AnalyticsWithoutAdIdSupport & GoogleTagManager

### ISSUE THREAD

**Issue by lennartstolz** [firebase/firebase-ios-sdk#8099]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: `12.4`
  * Firebase SDK version: `8.0.0` (also happens for `7.11.0`)
  * Installation method: `CocoaPods` (`1.10.x`)
  * Firebase Component: `Analytics` (precisely: `AnalyticsWithoutAdIdSupport`)

### [REQUIRED] Step 2: Describe the problem

Thanks a lot for providing the possibility to use `Firebase/Analytics` without the Ad-Id. 
Unfortunately, it causes compilation errors (`duplicate symbols`) in projects additionally using `GoogleTagManager`.

#### Steps to reproduce:

We created a [demo project](https://github.com/lennartstolz/FirebaseAnalyticsWithoutAdIdSupport-and-GoogleTagManager) to showcase the issue. (It's an empty iOS project using CocoaPods with the specified setup).

Additionally, we set up a workflow to build the project so you can see the compilation errors, without the need to execute the code by yourself: [Result](https://github.com/lennartstolz/FirebaseAnalyticsWithoutAdIdSupport-and-GoogleTagManager/runs/2609293368?check_suite_focus=true)

#### Relevant Code:

`Podfile`:

```
pod 'GoogleTagManager', '7.3.0'
pod 'Firebase/AnalyticsWithoutAdIdSupport', '8.0.0'
```

Result of Building this Application:

<img width="455" alt="duplicate-symbols-github" src="https://user-images.githubusercontent.com/3264231/118649616-fe7d0f00-b7e3-11eb-99f8-4553c8666f96.png">

#### Investigations

`GoogleTagManager` links this library as a dependency in their [.podspec.json](https://github.com/CocoaPods/Specs/blob/723d14978ebc9a23a2c93d8063b6fdaed7bc8c8b/Specs/9/5/6/GoogleTagManager/7.3.1/GoogleTagManager.podspec.json#L3-L7). We expect that this double linking of the "full version" of `FirebaseAnalytics` used by `GoogleTagManager` doesn't work with the specific usage of `Firebase/AnalyticsWithoutAdIdSupport`.

Do you see any way how this combination can be supported without the compilation errors?

Best,
Lennart

**Comment by lennartstolz** [comment]
Minor follow-up:

I updated the project to use the latest `GoogleTagManager` release and the issue still persists: [Result](https://github.com/lennartstolz/FirebaseAnalyticsWithoutAdIdSupport-and-GoogleTagManager/runs/2610399762?check_suite_focus=true)

**Comment by paulb777** [comment]
@lennartstolz Thanks for the report. `GoogleTagManager` depends on the full `FirebaseAnalytics` so it is not currently a supported configuration to use `AnalyticsWithoutAdIdSupport` together with `GoogleTagManager` 

cc: @tsunghung

**Comment by lennartstolz** [comment]
Thanks, @paulb777 for your fast reply 🙇 , and looking forward to @tsunghung's response.

**Comment by tsunghung** [comment]
Thanks a lot for the report! Unfortunately, I don't have an immediate solution. I will bring this issue to my team and see what we can do. Will update this issue when we have a solution.

**Comment by tsunghung** [comment]
`GoogleTagManager` itself relies on the `AdSupport` framework. Thus, to have an ad-id free build is more than a dependency change from `FirebaseAnalytics` to `FirebaseAnalyticsWithoutAdIdSupport`.
Just like @paulb777 mentioned, it is not currently a supported configuration to use `FirebaseAnalyticsWithoutAdIdSupport` together with `GoogleTagManager`.

**Comment by lennartstolz** [comment]
Thanks a lot, @tsunghung for your fast reply and the insights you shared.

But this means that we do need to show the iOS 14.5 "ATT prompt" to be ATT compliant when using the `GoogleTagManager` dependency, although we are not using any of the features which make use of the `AdSupport` framework?
Or do I miss sth.?

**Comment by tsunghung** [comment]
As far as I know, it's not required to show the "ATT prompt" to pass Apple's review today. `GoogleTagManager` can still work as ad-id disabled.
We do encourage App developers to show the "ATT prompt" to be ATT compliant and get the most features out of `GoogleTagManager` and `FirebaseAnalytics `.

**Comment by paulb777** [comment]
Going to close as working as expected.
