### ISSUE TITLE
FirebaseInstanceID file not found Objective c

### ISSUE THREAD

**Issue by aleemrazzaq** [firebase/firebase-ios-sdk#8100]
Recently I reintegrated, reinstalled and updated my pods, and Xcode start throwing following error on compile time.

'FirebaseInstanceID/FirebaseInstanceID.h' file not found 

<img width="829" alt="Screen Shot 2021-05-18 at 5 31 56 PM" src="https://user-images.githubusercontent.com/5242797/118661711-cfc55f80-b808-11eb-8f43-7e0cde39538d.png">

I noticed that FirebaseInstanceID was there but when I tried to newly install pods but it got skipped while installing

<img width="565" alt="Screen Shot 2021-05-18 at 5 33 03 PM" src="https://user-images.githubusercontent.com/5242797/118661747-d6ec6d80-b808-11eb-8327-46fcaab11206.png">

Is there any Alternate of this as I looked into firebase and its looks like it already obsoleted https://developers.google.com/android/reference/com/google/firebase/iid/FirebaseInstanceId

So I want to know is there any Alternate for this class ? as I have few code base on this class for notification e.g. kFIRInstanceIDTokenRefreshNotification ?

Please suggest me on this so that I'll resolve issue .

**Comment by maksymmalyhin** [comment]
@aleemrazzaq FirebaseInstanceID functionality have been migrated into Firebase Messaging.

@chliangGoogle Could you please confirm what notification in messaging can be instead? [FIRMessagingRegistrationTokenRefreshedNotification](https://github.com/firebase/firebase-ios-sdk/blob/429bac463c7ac20861d807a8a5dbe2eb1840ed6d/FirebaseMessaging/Sources/Public/FirebaseMessaging/FIRMessaging.h#L66) looks like the one, is it correct?

**Comment by chliangGoogle** [comment]
@maksymmalyhin You are right. @aleemrazzaq  Please migrate to Firebase Messaging and use FIRMessagingRegistrationTokenRefreshedNotification  instead.

**Comment by chliangGoogle** [comment]
Here's our migration guide: https://firebase.google.com/docs/projects/manage-installations#fid-iid
