### ISSUE TITLE
Race condition in FIRCLSUserLogging.m

### ISSUE THREAD

**Issue by tifroz** [firebase/firebase-ios-sdk#8102]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5 (12E262)
  * Firebase SDK version: 8.0.0.
  * Installation method: `Swift Package Manager` 
  * Firebase Component: Crashlytics

#### Steps to reproduce:

While troubleshooting a memory-related crash, we exercised the app with the Thread Sanitizer tool from Xcode and detected a race condition in `FIRCLSUserLogging.m` where the `activePath` pointer is being written in the `FIRCLSUserLoggingCheckAndSwapABFiles()` method `line 491` by one thread while it is being read in the `FIRCLSUserLoggingWriteAndCheckABFiles()` method `line 501` by another thread (see screenshot attached)

We think this may be the root cause of our memory-related crash - though there is no way to be sure until the race condition is fixed

#### Relevant Code:

The race condition (and the crash) happen very early in the app's lifecycle: the call to `Crashlytics.crashlytics().log()` which in turn exercises FIRCLSUserLoggingWriteAndCheckABFiles() is triggered after a failed network call from the app delegate's `didFinishLaunchingWithOptions()`

<img width="1484" alt="Screen Shot 2021-05-17 at 10 39 20 PM" src="https://user-images.githubusercontent.com/150367/118688702-2310c100-b7bb-11eb-8842-33e992c25ef4.png">

**Comment by elenadoty** [comment]
Hi @tifroz,
Thanks for bringing this to our attention! We haven't been able to reproduce but I've put up a PR with a potential fix, would you be willing to try it out and let us know if it solves the issue?

**Comment by tifroz** [comment]
Will do, thanks!

**Comment by tifroz** [comment]
Looks good! I am no longer reproducing the race condition after applying #8127
