### ISSUE TITLE
Error when launching app from Xcode into device

### ISSUE THREAD

**Issue by GZaccaroni** [firebase/firebase-ios-sdk#8106]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: > 12.5
  * Firebase SDK version: 8.0
  * Installation method: `Zip file` (select one)
  * Firebase Component: All

### [REQUIRED] Step 2: Describe the problem
When I try to run the app on a real device from Xcode I receive an error message:
```

Unable to install "Facebrity"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620375
--
The code signature version is no longer supported.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620375
```
If I set all Firebase frameworks to "Do not embed" the app runs correctly on the device (but I don't think it is correct doing so). 

The error happens only on Xcode 12.5 . 

#### Steps to reproduce:
1. Create new iOS project 
2. Build dependencies with `ReleaseTooling`
```
swift run zip-builder \
  --platforms "ios" \
  --zip-pods "$cwd/firebase_deps_specs.json" \
  --output-dir "$cwd/Frameworks/Firebase/" \
  --minimum-ios-version "11.2" \
;
```
3. Add output xcframeworks to "Frameworks, Libraries and Embedded Content" and set "Embed" as "Embed & Sign" 
4. Try to run app on an external device

**Comment by morganchen12** [comment]
This doesn't appear to be a Firebase issue. Avoid embedding unsigned static frameworks (or static frameworks in general) into your app bundle.

https://stackoverflow.com/questions/63147969/unable-to-run-app-error-while-installing-app-to-device-xcode-11-6
https://developer.apple.com/forums/thread/656382

**Comment by GZaccaroni** [comment]
@morganchen12 Thank you for the fast reply. 

What is the correct way to add built XCFrameworks to the project? Sorry if I reopen the issue, but it is not documented anywhere.

**Comment by morganchen12** [comment]
You should be able to drag them to your target's "Link Binaries with Libraries" section under Build Phases and Xcode will do the right thing automatically. Make sure they're **not** in the "Copy Bundle Resources" section.
