### ISSUE TITLE
After Updating code from InstanceID to Installation ID, my App is keep on Crashing [FBLPromise HTTPBody]  unrecognized selector sent to instance

### ISSUE THREAD

**Issue by aleemrazzaq** [firebase/firebase-ios-sdk#8108]
After updating my code from InstanceID to Installation my code is keep on crashing with error message 
[FBLPromise HTTPBody]: unrecognized selector sent to instance

**Code Changes**
**From:** [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(tokenRefreshNotification:)
                                                 name:kFIRInstanceIDTokenRefreshNotification object:nil];
                                                 
**To:**     [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(tokenRefreshNotification:)
                                                 name:FIRMessagingRegistrationTokenRefreshedNotification object:nil];

**From**
                [[FIRMessaging messaging] connectWithCompletion:^(NSError * _Nullable error) {
                    [[NSNotificationCenter defaultCenter] postNotificationName:FCMCONNECTED object:nil];
                    if (error != nil) {
                        NSLog(@"Unable to connect to FCM. %@", error);
                    } else {
                        NSLog(@"Connected to FCM.");
                    }
                }];
**To:** 
        [[FIRInstallations installations] installationIDWithCompletion:^(NSString *identifier, NSError *error) {
          if (error != nil) {
            NSLog(@"Error fetching Installation ID %@", error);
            return;
          }
          NSLog(@"Installation ID: %@", identifier);
            self->_refreshedTokenString = identifier;
        }];

**Here is my Pod file for Firebase:**

    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    # Add the pod for Firebase Crashlytics
    pod 'Firebase/Crashlytics'

**Comment by aleemrazzaq** [comment]
@rizafran 
Xcode Version = 12.1
Firebase = Installing Firebase (8.0.0)
iOS Version = 14.1
Is there any thing else you want to know ? I'm stuck over here from long time and tried multiples solution available on internet.
Thanks in Advance

**Comment by maksymmalyhin** [comment]
@aleemrazzaq Thank you for the provided details. We haven't been able to reproduce it on our end yet. A sample project where the issue can be reproduced will significantly help the investigation.
