### ISSUE TITLE
Uploading image to Storage Emulator is uploading file to Firebase Remote Project instead

### ISSUE THREAD

**Issue by MarcelBreska** [firebase/firebase-ios-sdk#8109]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5
  * Firebase SDK version: 8.0.0
  * Installation method: `Swift Package Manager` (select one)
  * Firebase Component:  Storage (Auth, Core, Database, Firestore, Messaging, Storage, etc)

### [REQUIRED] Step 2: Describe the problem

I'm trying to upload an image from iOS with the FirebaseSDK 8.0.0 to my Firebase Storage emulator, but the app is instead uploading the file to the Firebase Project Storage. The Authentication and Firestore setup with the emulator ist working without problems, only the Storage is not redirecting to the emulator.

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil) -> Bool {
    
    FirebaseApp.configure()
    
    Auth.auth().useEmulator(withHost: "localhost", port: 9099)
    Storage.storage().useEmulator(withHost: "localhost", port: 9199)
    
    let settings = Firestore.firestore().settings
    settings.host = "localhost:8080"
    settings.isPersistenceEnabled = false
    settings.isSSLEnabled = false
    Firestore.firestore().settings = settings
    
    return true
}

func uploadProfilePicture(imageData: Data, imageId: String) -> AnyPublisher<String, Error> {
    return Future<StorageReference, Error> { promise in
        let metaDataConfig = StorageMetadata()
        metaDataConfig.contentType = "image/jpg"
        
        let storageRef = Storage.storage().reference(withPath: "profiles/\(imageId)")
        
        storageRef.putData(imageData, metadata: metaDataConfig) { (_, error) in
            if let error = error {
                promise(.failure(error))
            } else {
                promise(.success(storageRef))
            }
        }
    }
    .compactMap { [weak self] storageRef in
        self?.donwloadUrl(storageRef: storageRef)
    }
    .switchToLatest()
    .eraseToAnyPublisher()
}
```

**Comment by morganchen12** [comment]
Hey Marcel, is this reproducible in Firebase 7.11?

**Comment by MarcelBreska** [comment]
Hey Morgan! The emulator feature for Storage was introduced with version 8.0.0. 

Storage.storage().useEmulator(withHost: "localhost", port: 9199) ´<- not available with 7.1.1

**Comment by morganchen12** [comment]
Ah, that's right. I'll take a look.

**Comment by schmidt-sebastian** [comment]
I am able to reproduce this only when calling `Storage.storage()` explicitly once to configure the Emulator and once to schedule the upload. In my repro, we seem to be returning different instances from both calls. This should not happen - but you should be able to work around this for now by storing the storage instance in an instance variable and using the same instance to configure the emulator and perform the upload.
