### ISSUE TITLE
Firestore Carthage installation is missing gRPC-C++ in 8.0.0

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#8112]
Opened to track issue raised at https://github.com/firebase/firebase-ios-sdk/issues/7576#issuecomment-843774872

**Comment by icedice** [comment]
> This looks like a Carthage issue. I reported at [Carthage/Carthage#3185](https://github.com/Carthage/Carthage/issues/3185).
> 
> In the meantime, you can get the missing `gRPC-C++.xcframework` by manually downloading `https://dl.google.com/dl/firebase/ios/carthage/8.0.0/FirebaseFirestore-6c7035fccbea27c0.zip` in the browser and unzipping

While this will work for local builds it's not going to work on our CI, but I could of cause setup a custom step to download and extract the file...

**Comment by paulb777** [comment]
Thanks to @elliottwilliams (in Carthage/Carthage#3185) for isolating this to an issue with the Firebase ZipBuilder in how it constructs xcframeworks for Carthage.

I'lll investigate a fix and follow up here.

**Comment by paulb777** [comment]
This issue and fix also applies to In App Messaging since it also has Resources. See https://github.com/Carthage/Carthage/issues/3185#issuecomment-859902901.
