### ISSUE TITLE
Unable to install Firebase iOS Pod

### ISSUE THREAD

**Issue by Sunrise17** [firebase/firebase-ios-sdk#8121]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5
  * Firebase SDK version: 8.0.0
  * Installation method: `CocoaPods` (select one)
  * Firebase Component: Auth, Core, Database, Firestore, Messaging, Storage, Functions, Admob, Analytics, Google-Mobile-Ads-SDK

#### Steps to reproduce:

During installation of pods to Firebase version 8.0.0, i have received following error. I have deintegrated pod, removed Podfile.lock, Pods folder, Project.xcworkspace and all Derived Data. Then i have installed pods as in following below. However, i have received 'Unable to read the license file' errors. Moreover, when i have built the project, it gives an error (<GoogleUtilities/GULURLSessionDataResponse.h>) as follows.

user@user-MacBook-Pro Project % pod deintegrate

Deintegrating `Project.xcodeproj`
Deleted 1 'Check Pods Manifest.lock' build phases.
Deleted 1 'Embed Pods Frameworks' build phases.
- Pods_Project.framework
- Pods-Project.debug.xcconfig
- Pods-Project.release.xcconfig
Removing `Pods` directory.

Project has been deintegrated. No traces of CocoaPods left in project.
Note: The workspace referencing the Pods project still remains.

user@user-MacBook-Pro Project % pod install --repo-update

Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing BoringSSL-GRPC (0.0.7)
Installing FBAudienceNetwork (6.5.0)
Installing FBSDKCoreKit (9.3.0)
Installing FBSDKLoginKit (9.3.0)
Installing FBSDKShareKit (9.3.0)
Installing Firebase (3.6.0)
Installing Firebase (8.0.0)
Installing FirebaseAnalytics (3.4.2)
Installing FirebaseAuth (8.0.0)
Installing FirebaseCore (8.0.0)
Installing FirebaseCoreDiagnostics (8.0.0)
Installing FirebaseDatabase (8.0.0)
Installing FirebaseFirestore (8.0.0)
Installing FirebaseFunctions (8.0.0)
Installing FirebaseInstallations (8.0.0)
Installing FirebaseInstanceID (1.0.9)
Installing FirebaseMessaging (8.0.0)
Installing FirebaseStorage (8.0.0)
Installing GTMSessionFetcher (1.5.0)
Installing Google-Mobile-Ads-SDK (7.11.0)
Installing GoogleDataTransport (9.0.0)
Installing GoogleInterchangeUtilities (1.2.2)
Installing GoogleSymbolUtilities (1.1.2)
Installing GoogleUtilities (1.3.2)
Installing GoogleUtilities (7.4.1)
Installing PromisesObjC (1.2.12)
Installing abseil (0.20200225.0)
Installing gRPC-C++ (1.28.2)
Installing gRPC-Core (1.28.2)
Installing leveldb-library (1.22.1)
Installing nanopb (2.30908.0)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `Project.xcworkspace` for this project from now on.
Pod installation complete! There are 13 dependencies from the Podfile and 31 total pods installed.

[!] Unable to read the license file `LICENSE` for the spec `Firebase (8.0.0)`

[!] Unable to read the license file `LICENSE` for the spec `GoogleUtilities (7.4.1)`

[!] Unable to read the license file `LICENSE` for the spec `Firebase (8.0.0)`

[!] Unable to read the license file `LICENSE` for the spec `GoogleUtilities (7.4.1)`

[!] [Xcodeproj] Generated duplicate UUIDs:

PBXFileReference -- Pods.xcodeproj/mainGroup/children/children:children:|,|,|,displayName:BoringSSL-GRPC,isa:PBXGroup,name:BoringSSL-GRPC,path:BoringSSL-GRPC,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:FBAudienceNetwork,isa:PBXGroup,name:FBAudienceNetwork,path:FBAudienceNetwork,sourceTree:<group>,,children:|,|,|,display
.
.
.
.

<img width="1383" alt="Ekran Resmi 2021-05-20 12 23 34" src="https://user-images.githubusercontent.com/26038249/118954248-41ff8680-b966-11eb-8122-7664e6f8fa55.png">

#### Relevant Code:

Content of Podfile of the Project;

platform :ios, '12.4'

target 'Project' do
  use_frameworks!

  # project 'Project.xcodeproj'

  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'Firebase/Functions'
  pod 'Firebase/AdMob'
  pod 'Firebase/Analytics'
  pod 'Google-Mobile-Ads-SDK'

  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'FBAudienceNetwork'

end

post_install do |pi|
    pi.pods_project.targets.each do |t|
          t.build_configurations.each do |bc|
              if bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
                bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
              end
          end
     end
end

**Comment by Sunrise17** [comment]
Following commands has solved the issue!

pod cache clean --all
pod spec lint again

**Comment by paulb777** [comment]
Another issue is that `pod 'Firebase/AdMob'` was removed from Firebase 8.0.0 in favor of `pod 'Google-Mobile-Ads-SDK'`.

If it's still included in the Podfile, an update to 8.0.0 won't be successful.
