### ISSUE TITLE
open_notification event not being triggered when app is not in background.

### ISSUE THREAD

**Issue by khuffie** [firebase/firebase-ios-sdk#8128]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5
  * Firebase SDK version: [8.0.0](url)
  * Installation method: SPM
  * Firebase Component: Messaging

#### Steps to reproduce:

1. Force quit the app
2. Send a push notification to the app
3. Tap on the push notification
4. Observe Debug View

Expected: notification_open event gets triggered
Actual: No notification_event gets triggered

We are noticing that iOS is severely undercounting the push notification open rate. On Android, our open rate is around 12%. On iOS, our open rate is around 0.29%. However, evidence suggests that users ARE receiving push notifications and opening them on iOS (we see similar surges in traffic as Android), but just that the notification_open event is not getting triggered.

We have confirmed that swizzling is ON.

We have tested the following scenarios, each 5 times, and each reproduced 100%

- App is in the background, notification is received, notification_open is triggered
- App is closed, notification is received, notification_open is NOT triggered
- App is open in foreground, notification is received, notification_foreground is triggered correctly

We are monitoring the events via the DebugView.

Note that we recently updated to v8.0.0. However, we saw the same issue in the previous version of the SDK which was manually integrated.

**Comment by chliangGoogle** [comment]
@khuffie Thank you for filing the issue. Please remind me again if you are using Unity/C++ or just iOS SDK?

If it's iOS SDK, do you have `- (void)userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:` implemented as mentioned in our [guide](https://firebase.google.com/docs/cloud-messaging/ios/receive#handle_alert_notifications).

**Comment by khuffie** [comment]
@chliangGoogle we are using just the iOS SDK. We have a native Swift app.

And yep, we do implement that method as described.

Additional context: we send additional metadata with the push to deeplink users to specific sections of the app. Even in the cold start scenario, the deeplinking logic works as expected. It's just that the event isn't triggered so our open rate is completely off.
