### ISSUE TITLE
Query limited to last 100 always return exactly 3 elements

### ISSUE THREAD

**Issue by maximkhatskevich** [firebase/firebase-ios-sdk#814]
ENVIRONMENT

  * Xcode version: 9.2 (stable)
  * Firebase SDK version: 4.6.0
  * Firebase Component: Database
  * Component version: 4.1.1

WHAT I DO

Setting up a Realtime Databse query on a collection of objects, order by child path and limit to last 100 elements. Then setup event observers for add, move, remove, change. I'm sure I have 5 elements in the collection total, they all satisfy to this query. 

WHAT I EXPECT

Get all the 5 elements that I have in this collection in result set (the "add" event should be triggered 5 times).

WHAT I GET

Only get exactly 3 elements in result set (the "add" event is being triggered 3 times).

OTHER THINGS TO NOTE

Query works fine (as expected when limit is ANY number except "100", including 99 and 101.

CODE SAMPLE

```swift
import Firebase

let query = Database
    .database()
    .reference()
    .child("publications")
    .queryOrdered(byChildPath: "createdAt") // Date
    .queryLimited(toLast: 100)

query.observe(.childAdded)
{
    // display child in the app...
}

// here subscribe for other events in similar way...

```

**Comment by morganchen12** [comment]
If you listen for a `.value` event, do you get all 100 elements, or does that also return 3?

**Comment by maximkhatskevich** [comment]
Not sure. I didn't use the 'value', only 'add', 'change', 'move' and 'remove'.

By the way, seems like the issue does not appear anymore for me. I've changed my data since then and not sure what was the real cause. Probably, just disregard this issue at all, I'll re-open it if got more evidence.
