### ISSUE TITLE
gRPC-Core and gRPC-C-C++ get Semantic issue after Update Xcode to 12.5 (12E262)

### ISSUE THREAD

**Issue by YcReal** [firebase/firebase-ios-sdk#8141]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5
  * Firebase SDK version: 8.0.0
  * Installation method: CocoaPods 
  * Firebase Component: Firestore

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
gRPC-Core  framework have this problem 

typedef struct {.         // This line have problem.  Anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here  

  grpc_mdelem* md = nullptr;
  size_t size = 0;
} grpc_credentials_mdelem_array;



// TODO(you): code here to reproduce the problem
```

**Comment by dconeybe** [comment]
These warnings can probably be suppressed using the techniques already in place here:

https://github.com/firebase/firebase-ios-sdk/blob/38b4592cd939a482f1095bdbdceb447940a25346/Firestore/core/src/util/warnings.h#L20-L36.

I'll look into this.

**Comment by dconeybe** [comment]
After investigation, I found that the offending code is not directly or indirectly included from Firestore's source code. As a result, these warnings cannot be fixed here in this GitHub repository. As a result, I'm going to close this issue. I believe the correct place to open a ticket is against grpc (https://github.com/grpc).
