### ISSUE TITLE
Remote config App Crash due to SQLite exception

### ISSUE THREAD

**Issue by ramirlazatinmclinica** [firebase/firebase-ios-sdk#8147]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.11.0
  * Installation method: CocoaPods 
  * Firebase Component: Remote Config, Core, Database, Messaging, Storage

#### Steps to reproduce:

We are experiencing reports of app crash in relation with Remote Config after updating to version 7.11.0

**Crash Log:**

`
Crashed: com.google.GoogleConfigService.database

0  libsystem_platform.dylib       0x1f403120c _os_unfair_lock_unowned_abort + 36

1  libsystem_platform.dylib       0x1f402f25c _os_unfair_lock_unlock_slow + 136

2  libsqlite3.dylib               0x1c226dba0 sqlite3_randomness + 3764

3  libsqlite3.dylib               0x1c224fe40 sqlite3_value_text + 24048

4  libsqlite3.dylib               0x1c224f874 sqlite3_value_text + 22564

5  libsqlite3.dylib               0x1c221b4c0 sqlite3_finalize + 3788

6  libsqlite3.dylib               0x1c2248af8 sqlite3_step + 64904

7  libsqlite3.dylib               0x1c2238e9c sqlite3_step + 300

8  FirebaseRemoteConfig           0x106b355fc -[RCNConfigDBManager insertMainTableWithValues:fromSource:] + 459 (RCNConfigDBManager.m:459)

9  FirebaseRemoteConfig           0x106b353b4 __77-[RCNConfigDBManager insertMainTableWithValues:fromSource:completionHandler:]_block_invoke + 410 (RCNConfigDBManager.m:410)

10 libdispatch.dylib              0x1a80e9a54 _dispatch_call_block_and_release + 32

11 libdispatch.dylib              0x1a80eb7ec _dispatch_client_callout + 20

12 libdispatch.dylib              0x1a80f2fd4 _dispatch_lane_serial_drain + 620

13 libdispatch.dylib              0x1a80f3bd0 _dispatch_lane_invoke + 404

14 libdispatch.dylib              0x1a80fe48c _dispatch_workloop_worker_thread + 764

15 libsystem_pthread.dylib        0x1f40367a4 _pthread_wqthread + 276

16 libsystem_pthread.dylib        0x1f403d74c start_wqthread + 8
`

**Steps to reproduce:**
`
FirebaseApp.configure()

let settings: RemoteConfigSettings = RemoteConfigSettings()

settings.minimumFetchInterval =  TimeInterval(1800)

settings.fetchTimeout = 30.0

self.config.configSettings = settings

self.config.fetchAndActivate { [weak self] (status: RemoteConfigFetchAndActivateStatus, error: Error?) -> Void in

   // Handling configs here

}

`

**What happened? How can we make the problem occur?**
- App crash after calling fetchAndActivate function

**Comment by ramirlazatinmclinica** [comment]
@morganchen12 thanks for the quick response, yes one of our third party pod is also using SQLite

**Comment by morganchen12** [comment]
Do the crashes go away if you remove the other third party pod?

**Comment by ramirlazatinmclinica** [comment]
@morganchen12 unfortunately we are unable to replicate this during development which make it a bit tricky to test if removing the other third party pod could fix the crash. Though it is rampantly occurring on random users in production.

One thing we've observe is that it is only happening once per user and does not occur again based on the crash logs.

Might this be an issue of SQLite collision? I've saw other SQLite related tickets that might be related
https://github.com/firebase/firebase-ios-sdk/issues/6039

Any chance the new version 8.0.0 somehow include the fix for this?

**Comment by paulb777** [comment]
I'm not aware of any 8.0.0 changes that may have fixed this. As you can see with other issues in this repo, we've often seen sqlite crashes when apps include a customized sqlite implementation that is incompatible with the system version used by Firebase.

**Comment by ramirlazatinmclinica** [comment]
We have opted to make the adjustment on the conflicting 3rd party pod to prevent the SQLite issue
