### ISSUE TITLE
Firebase Storage download error Error Domain=FIRStorageErrorDomain Code=-13000

### ISSUE THREAD

**Issue by ilyon** [firebase/firebase-ios-sdk#8148]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: __12.4___
  * Firebase SDK version: __7.4.0___
  * Installation method: `CocoaPods`
  * Firebase Component: Auth, Core, Storage, etc)

#### Steps to reproduce:

Recently I upgraded the SDK from 6.15.0 to 7.4.0, and collected a lot of download failures caused by the following error, but my self-test did not find this problem.

> Error Domain=FIRStorageErrorDomain Code=-13000 "An unknown error occurred, please check the server response." UserInfo={_kCFStreamErrorDomainKey=12, _kCFStreamErrorCodeKey=8, NSErrorFailingURLStringKey=https://firebasestorage.googleapis.com/v0/b/api-project-xxxxxxxxxxx.appspot.com/o/xxxxxxxxxxx%2Fdata.xx?alt=media, NSUnderlyingError=0x28116cf90 {Error Domain=kCFErrorDomainCFNetwork Code=-1003 "(null)" UserInfo={_kCFStreamErrorCodeKey=8, _kCFStreamErrorDomainKey=12}}, NSErrorFailingURLKey=https://firebasestorage.googleapis.com/v0/b/api-project-xxxxxxxxxxx.appspot.com/o/xxxxxxxxxxx%2Fdata.xx?alt=media, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDownloadTask <12050C7C-8D7A-4C37-BC0D-0595CBD87A0E>.<2>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDownloadTask <12050C7C-8D7A-4C37-BC0D-0595CBD87A0E>.<2>, bucket=api-project-xxxxxxxxxxx.appspot.com, object=xxxxxxxxxxx/data.xx, ResponseErrorDomain=NSURLErrorDomain, ResponseErrorCode=-1003, NSLocalizedDescription=An unknown error occurred, please check the server response.}

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
NSURL *localURL = [NSURL fileURLWithPath:DocumentPath(kFIREBASE_STORAGE_NAME)];
self.storageTask = [islandRef writeToFile:localURL completion:^(NSURL *URL, NSError *error) {
            
}];
```

**Comment by morganchen12** [comment]
Some Google searches for `kCFErrorDomainCFNetwork Code=-1003` imply it's a result of an unreachable server. Do you know what sort of internet conditions these failures are occurring in?

**Comment by ilyon** [comment]
> Some Google searches for `kCFErrorDomainCFNetwork Code=-1003` imply it's a result of an unreachable server. Do you know what sort of internet conditions these failures are occurring in?

I’m not sure about the user’s network, but I receive more feedback like this.

**Comment by morganchen12** [comment]
@ilyon were you able to reproduce this issue or identify the network conditions that caused the request to fail?

**Comment by ilyon** [comment]
> @ilyon were you able to reproduce this issue or identify the network conditions that caused the request to fail?

It should be a network problem. The users with this problem are concentrated in the Philippines.

**Comment by morganchen12** [comment]
Thanks for investigating. If you believe this is a non-SDK issue with Firebase, please file a ticket [here](https://firebase.google.com/support).

In the past we've seen some internet service providers blocking access to Firebase Storage due to third-party hosted content. If this is the case, you may be able to file an issue to the internet service provider.
