### ISSUE TITLE
Cannot set User.displayName to null

### ISSUE THREAD

**Issue by rrousselGit** [firebase/firebase-ios-sdk#8149]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.3 (12C33)
  * Firebase SDK version: 8.0.0
  * Installation method: Flutter plugins
  * Firebase Component: Auth

#### Steps to reproduce:

While fixing an issue on FlutterFire (https://github.com/FirebaseExtended/flutterfire/pull/6213), it was revealed that it is apparently not possible to set a user's displayName to null when using `FIRUserProfileChangeRequest`

This is inconsistent with Android/web, where it is possible to set displayName to `null`. 

#### Relevant Code:

```
FIRUserProfileChangeRequest *changeRequest = [currentUser profileChangeRequest];
changeRequest.displayName = nil;

<commit the change request>

// the display name is not updated
```

**Comment by paulb777** [comment]
Closing for staleness. Please comment or open a new issue to reopen.
