### ISSUE TITLE
GoogleSignIn crash

### ISSUE THREAD

**Issue by Montura** [firebase/firebase-ios-sdk#8154]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: `12.4 (12D4e)`
  * Firebase SDK version: `6.34.0 (the same behavior on 8.0.0)`
  * Installation method: `Zip file`
  * Firebase Component: `Auth`

### [REQUIRED] Step 2: Describe the problem

iPad Air (3rd gen) running iOS 14.0.1

1. App works fine when sign in with _basic_ google account.
2. App crashes when sign in with _google workspace_ account.

`Assertion failure in +[UIAlertAction _actionWithTitle:descriptiveText:image:style:handler:shouldDismissHandler:], UIAlertAction.m:42`
`2021-05-25 17:49:53.950251+0300 GoogleSignIn[16264:9133478] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Actions added to UIAlertController of style UIAlertActionStyleCancel must have a title when running in UIUserInterfaceIdiomPad'
`

Full backtrace is here (https://github.com/Montura/GoogleSignInDemo/blob/main/lldb_bt_all_log.txt)

P.S. It works fine on iOS-simulator

#### Steps to reproduce:

Login with credentials. There is a simple demo with Firebase 6.34.0 (https://github.com/Montura/GoogleSignInDemo)

The same problem was discussed here (https://github.com/firebase/firebase-ios-sdk/issues/6406)

#### Relevant Code:

```
// AppDelegate.m
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    [FIRConfiguration.sharedInstance setLoggerLevel:FIRLoggerLevelWarning];
    [FIRApp configure];
    
    [FIRAnalytics setAnalyticsCollectionEnabled:true];

    GIDSignIn * gidSignIn = [GIDSignIn sharedInstance];
    gidSignIn.clientID = [FIRApp defaultApp].options.clientID;
    gidSignIn.delegate = self;
    
    // Override point for customization after application launch.
    return YES;
}

// ViewController.m
- (void)buttonPressed:(UIButton *)button {
    [GIDSignIn sharedInstance].presentingViewController = self;
    [[GIDSignIn sharedInstance] signIn];
}
```

### [OPTIONAL] Step 3: The expected workflow
   1. To get an alert message when sign in with **google workspace** account
![image](https://user-images.githubusercontent.com/4503006/119644039-1f1d1880-be25-11eb-8b14-a90de9f6dc87.png)

**Comment by morganchen12** [comment]
What version of GoogleSignIn are you using? Also, can you set an exception breakpoint and then print the stack trace again?

**Comment by Montura** [comment]
Version is 6.34.0. Also it crashes on version 8.0.0.

Full backtrack is here:

https://github.com/Montura/GoogleSignInDemo/blob/main/lldb_bt_all_log.txt

**Comment by morganchen12** [comment]
Can you share your full `Podfile.lock`? The code responsible for causing the crash no longer exists on the most recent version of GoogleSignIn (not Firebase). Note that GoogleSignIn is a separate CocoaPod and is versioned separately from Firebase.

**Comment by Montura** [comment]
I don't use any installations from (https://github.com/firebase/firebase-ios-sdk#installation) including CocaPods so I don't have a `Podfile.lock`.

I've just downloaded `ZIP` file from release (https://github.com/firebase/firebase-ios-sdk/releases/tag/8.0.0) and that is it.

Then I set up manually **Header Search Path** and **Framework search Path** for the Xcode project.

![image](https://user-images.githubusercontent.com/4503006/119959282-874a3680-bfac-11eb-96ef-93f92ce77514.png)

**Comment by Montura** [comment]
@morganchen12, I found the problem. There is a `GoogleSignIn.Bundle` inside FirebaseSDK. I've added it into the **Frameworks** group in the app. Then everything works fine!

It seems `GoogleSignIn` try to get some string from `GoogleSignIn.bundle` in runtime and got **NULL** when there is no the bundle.

![image](https://user-images.githubusercontent.com/4503006/120185231-9cc49800-c21a-11eb-8936-a14d7cbb2828.png)

![image](https://user-images.githubusercontent.com/4503006/120185397-d1d0ea80-c21a-11eb-82b6-87087d13e436.png)

**Comment by sainttail** [comment]
@Montura 

I don't think this is the my problem but based on your finding I think I found the root problem in my comment [#8164(Comment)](https://github.com/firebase/firebase-ios-sdk/issues/8164#issuecomment-851776485)

**Comment by paulb777** [comment]
@Montura Thanks for sharing your solution. Note that this should be covered by Step 7 in the Zip README:


```
7. If the SDK has resources, go into the Resources folders, which will be in
   the SDK folder. Drag all of those resources into the Project Navigator, just
   like the frameworks, again making sure that the target you want to add these
   resources to has a checkmark next to it, and that you've selected "Copy items
   if needed".
```
