### ISSUE TITLE
Firebase Crashed at intializing FIRApp.configure() 

### ISSUE THREAD

**Issue by moontecholabs** [firebase/firebase-ios-sdk#816]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.2
  * Firebase SDK version: 3.17.0
  * Firebase Component: _____ (Auth, Core, RemoteConfig, Messaging, FirebaseAnalytics, FirebaseInstanceID)

### [REQUIRED] Step 3: Crashed at FIRApp.configure() 

We intializing Firebase in appdelegate didfinishlaunching
FIRApp.configure()  at this line we are getting Crash

#### Steps to reproduce:
Following is Crash Trace

iFax iOS | -[FIRInstanceIDAuthService scheduleCheckin:] + 4303095044
-- | --
1 | iFax iOS | -[FIRInstanceID(FIRApp) configureInstanceIDWithApp:] + 4303066316
2 | iFax iOS | +[FIRInstanceID(FIRApp) didReceiveConfigureSDKNotification:] + 4303065916
3 | CoreFoundation | __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
4 | CoreFoundation | _CFXRegistrationPost + 420
5 | CoreFoundation | ___CFXNotificationPost_block_invoke + 60
6 | CoreFoundation | -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1408
7 | CoreFoundation | _CFXNotificationPost + 380
8 | Foundation | -[NSNotificationCenter postNotificationName:object:userInfo:] + 68
9 | iFax iOS | +[FIRApp sendNotificationsToSDKs:] + 4302970736
10 | iFax iOS | +[FIRApp configureDefaultAppWithOptions:sendingNotifications:] + 4302965924
11 | iFax iOS | +[FIRApp configure] + 4302965148
12 | iFax iOS | AppDelegate.swift line 581specialized  AppDelegate.application(UIApplication, didFinishLaunchingWithOptions :  [UIApplicationLaunchOptionsKey : Any]?) -> Bool
13 | iFax iOS | AppDelegate.swift line 0@objc AppDelegate.application(UIApplication, didFinishLaunchingWithOptions : [UIApplicationLaunchOptionsKey : Any]?) -> Bool
14 | UIKit | -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 384
15 | UIKit | -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 3428
16 | UIKit | -[UIApplication _runWithMainScene:transitionContext:completion:] + 1712
17 | UIKit | __111-[__UICanvasLifecycleMonitor_Compatability   _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke  + 800
18 | UIKit | +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 160
19 | UIKit | -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 252
20 | UIKit | -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 748
21 | UIKit | __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 260
22 | UIKit | -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 448
23 | UIKit | __125-[_UICanvasLifecycleSettingsDiffAction   performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke  + 220
24 | UIKit | _performActionsWithDelayForTransitionContext + 112
25 | UIKit | -[_UICanvasLifecycleSettingsDiffAction   performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]  + 252
26 | UIKit | -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 364
27 | UIKit | -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 540
28 | UIKit | -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 364
29 | FrontBoardServices | -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 364
30 | FrontBoardServices | __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 224
31 | libdispatch.dylib | _dispatch_client_callout + 16
32 | libdispatch.dylib | _dispatch_block_invoke_direct$VARIANT$mp + 288
33 | FrontBoardServices | __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 36
34 | FrontBoardServices | -[FBSSerialQueue _performNext] + 404
35 | FrontBoardServices | -[FBSSerialQueue _performNextFromRunLoopSource] + 56
36 | CoreFoundation | __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
37 | CoreFoundation | __CFRunLoopDoSource0 + 88
38 | CoreFoundation | __CFRunLoopDoSources0 + 204
39 | CoreFoundation | __CFRunLoopRun + 1048
40 | CoreFoundation | CFRunLoopRunSpecific + 436
41 | GraphicsServices | GSEventRunModal + 100
42 | UIKit | UIApplicationMain + 208
43 | iFax iOS | AppDelegate.swift line 113main
44 | libdyld.dylib | start + 4

0 | iFax iOS | -[FIRInstanceIDAuthService scheduleCheckin:] + 4303095044
-- | -- | --
1 | iFax iOS | -[FIRInstanceID(FIRApp) configureInstanceIDWithApp:] + 4303066316
2 | iFax iOS | +[FIRInstanceID(FIRApp) didReceiveConfigureSDKNotification:] + 4303065916
3 | CoreFoundation | __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
4 | CoreFoundation | _CFXRegistrationPost + 420
5 | CoreFoundation | ___CFXNotificationPost_block_invoke + 60
6 | CoreFoundation | -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1408
7 | CoreFoundation | _CFXNotificationPost + 380
8 | Foundation | -[NSNotificationCenter postNotificationName:object:userInfo:] + 68
9 | iFax iOS | +[FIRApp sendNotificationsToSDKs:] + 4302970736
10 | iFax iOS | +[FIRApp configureDefaultAppWithOptions:sendingNotifications:] + 4302965924
11 | iFax iOS | +[FIRApp configure] + 4302965148
12 | iFax iOS | AppDelegate.swift line 581specialized  AppDelegate.application(UIApplication, didFinishLaunchingWithOptions :  [UIApplicationLaunchOptionsKey : Any]?) -> Bool
13 | iFax iOS | AppDelegate.swift line 0@objc AppDelegate.application(UIApplication, didFinishLaunchingWithOptions : [UIApplicationLaunchOptionsKey : Any]?) -> Bool
14 | UIKit | -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 384
15 | UIKit | -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 3428
16 | UIKit | -[UIApplication _runWithMainScene:transitionContext:completion:] + 1712
17 | UIKit | __111-[__UICanvasLifecycleMonitor_Compatability   _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke  + 800
18 | UIKit | +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 160
19 | UIKit | -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 252
20 | UIKit | -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 748
21 | UIKit | __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 260
22 | UIKit | -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 448
23 | UIKit | __125-[_UICanvasLifecycleSettingsDiffAction   performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke  + 220
24 | UIKit | _performActionsWithDelayForTransitionContext + 112
25 | UIKit | -[_UICanvasLifecycleSettingsDiffAction   performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]  + 252
26 | UIKit | -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 364
27 | UIKit | -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 540
28 | UIKit | -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 364
29 | FrontBoardServices | -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 364
30 | FrontBoardServices | __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 224
31 | libdispatch.dylib | _dispatch_client_callout + 16
32 | libdispatch.dylib | _dispatch_block_invoke_direct$VARIANT$mp + 288
33 | FrontBoardServices | __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 36
34 | FrontBoardServices | -[FBSSerialQueue _performNext] + 404
35 | FrontBoardServices | -[FBSSerialQueue _performNextFromRunLoopSource] + 56
36 | CoreFoundation | __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
37 | CoreFoundation | __CFRunLoopDoSource0 + 88
38 | CoreFoundation | __CFRunLoopDoSources0 + 204
39 | CoreFoundation | __CFRunLoopRun + 1048
40 | CoreFoundation | CFRunLoopRunSpecific + 436
41 | GraphicsServices | GSEventRunModal + 100
42 | UIKit | UIApplicationMain + 208
43 | iFax iOS | AppDelegate.swift line 113main
44 | libdyld.dylib | start + 4

#### Relevant Code:
   
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions:
        [UIApplicationLaunchOptionsKey : Any]? = nil) -> Bool {
          FIRApp.configure()
        FIRMessaging.messaging().remoteMessageDelegate = self
}

**Comment by morganchen12** [comment]
Can you upload an example that reproduces this crash?

**Comment by moontecholabs** [comment]
> Consider updating to Firebase 4.x

We are already using 4.x
 - Firebase (4.8.1):
    - Firebase/Core (= 4.8.1)
  - Firebase/Core (4.8.1):
    - FirebaseAnalytics (= 4.0.7)
    - FirebaseCore (= 4.0.14)
  - Firebase/Messaging (4.8.1):
    - Firebase/Core
    - FirebaseMessaging (= 2.0.8)
  - Firebase/RemoteConfig (4.8.1):
    - Firebase/Core
    - FirebaseRemoteConfig (= 2.1.1)
  - FirebaseABTesting (1.0.0):
    - FirebaseCore (~> 4.0)
    - Protobuf (~> 3.1)
  - FirebaseAnalytics (4.0.7):
    - FirebaseCore (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
    - nanopb (~> 0.3)
  - FirebaseCore (4.0.14):
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseInstanceID (2.0.8):
    - FirebaseCore (~> 4.0)
  - FirebaseMessaging (2.0.8):
    - FirebaseAnalytics (~> 4.0)
    - FirebaseCore (~> 4.0)
    - FirebaseInstanceID (~> 2.0)

**Comment by moontecholabs** [comment]
> Can you upload an example that reproduces this crash?

we are unable to produce this case but our user facing this case.we found above crash trace from fabrics.

**Comment by morganchen12** [comment]
@moontecholabs are you able to share the exception message when the app crashes?

**Comment by moontecholabs** [comment]
We have provided exception message/logs above, now updated latest pod not facing again.
