### ISSUE TITLE
Crash with Google Sign In when no gmail app

### ISSUE THREAD

**Issue by sainttail** [firebase/firebase-ios-sdk#8164]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.11
  * Installation method: `Zip file`
  * Firebase Component: Analytics, Crashlytics, Firestore, Functions, GoogleSignIn

#### Steps to reproduce:

What happened? How can we make the problem occur?

Login with Google SSO on some account on some particular device (test device) is always crash.
However after install Gmail app on that device and login that Gmail app the crash is gone. After Gmail is installed removing it also don't make the Google SSO crash anymore.

The stack trace look something like this
<img width="1296" alt="Screen Shot 2021-05-28 at 15 17 13" src="https://user-images.githubusercontent.com/3015139/119974666-24be5e00-bfdf-11eb-84e3-0bd301c28e60.png">

Any idea why this happen?

**Comment by sainttail** [comment]
yes I try personally account it works fine but company account crash like in #8154

**Comment by Montura** [comment]
@sainttail, look at https://github.com/firebase/firebase-ios-sdk/issues/8154#issuecomment-851463342

I found the solution

**Comment by rizafran** [comment]
Thanks for sharing the solution, @Montura.

@sainttail, please try the suggested solution, and continue the thread in #8154 in case the issue persists. With this, I'll be closing this issue now. Thanks.

**Comment by sainttail** [comment]
@Montura 

I have already added `GoogleSignIn.bundle` into the project otherwise all the devices will crash.

But for my case, only this device crash and I got report from customer that someone crash but it is very rare and we ignore it before until our qa found this crash on their one of their test device.

If the bundle is not there then all the devices should crash right from my understanding?

**Comment by sainttail** [comment]
@rizafran 

However base on your answer I found this in `GoogleSignIn.bundle`. The `en.lproj` has less key than other language files.

This could be the problem?

<img width="1680" alt="Screen Shot 2021-06-01 at 10 20 50 (2)" src="https://user-images.githubusercontent.com/3015139/120261896-1021e480-c2c3-11eb-8cbf-92f0f6d9aebb.png">

**Comment by Montura** [comment]
> @Montura 
> 
> 
> 
> I have already added `GoogleSignIn.bundle` into the project otherwise all the devices will crash.
> 
> 
> 
> But for my case, only this device crash and I got report from customer that someone crash but it is very rare and we ignore it before until our qa found this crash on one of their test device.
> 
> 
> 
> If the bundle is not there then all the devices should crash right from my understanding?

Yes, you are right. I got a crash on different devices without the bundle.

**Comment by Montura** [comment]
@sainttail, do you have one more file `en_GB.lproj` it contains other titles. By the way, I'm looking into Firebase 8.0.0. You have 7.1.1. Maybe it is the difference?

![image](https://user-images.githubusercontent.com/4503006/120302658-ca6f1700-c2d6-11eb-9dff-0f3cfc8ebbec.png)


![image](https://user-images.githubusercontent.com/4503006/120302804-e8d51280-c2d6-11eb-8367-be8e77132857.png)

**Comment by paulb777** [comment]
Reopening since this looks different than #8154 and is unresolved.

It would be interesting to investigate if a CocoaPods installation has the same problem.

**Comment by sainttail** [comment]
@Montura Yeah, I just fix it myself (I install firebase by manual installation) by copy all the text in `en_GB.lproj` to `en.lproj`

**Comment by paulb777** [comment]
There might be something related to Xcode 12.5 changes like https://forums.swift.org/t/swift-package-localization-always-using-english-localization/48988.

**Comment by paulb777** [comment]
GoogleSignIn 6.0.0 is now released and open source. Please try with 6.0.0 and follow up at https://github.com/google/GoogleSignIn-iOS/issues with any outstanding issues.
