### ISSUE TITLE
Firebase Flooding Project with Build Schemes

### ISSUE THREAD

**Issue by ericpalyan** [firebase/firebase-ios-sdk#8167]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5
  * Firebase SDK version: 8.0.0
  * Installation method: Swift Package Manager
  * Firebase Component: Crashlytics

### [REQUIRED] Step 2: Describe the problem

As soon as the SPM is done resolving the framework the project gets flooded with almost 30 different build schemes all coming from the Firebase framework. I have autocreate schemes disabled and deleting them does not help. They return once SPM runs automatically. I use many other frameworks and have never had this issue and could not locate a fix for it. How can this be prevented?

#### Steps to reproduce:

Add the framework to the project via SPM.

**Comment by elenadoty** [comment]
Hi @ericpalyan,
Are you experiencing this behavior only with Crashlytics, or with other Firebase products as well?

**Comment by paulb777** [comment]
8.1.0 should be better than 8.0.0 thanks to the deletion of several schemes in #8060, but I still see:

![Screen Shot 2021-06-04 at 3 02 00 PM](https://user-images.githubusercontent.com/73870/120867102-170c5980-c546-11eb-91bc-0b423920957e.png)

**Comment by paulb777** [comment]
I raised the issue in the Swift Forums at https://forums.swift.org/t/swiftpm-and-library-unit-testing/26255/21

**Comment by paulb777** [comment]
The issue still exists in the Xcode 13 beta 1
