### ISSUE TITLE
Crashlytics uploading but missing in UI 

### ISSUE THREAD

**Issue by daihovey** [firebase/firebase-ios-sdk#8168]
### Describe your environment

  * Xcode version: Version 12.4 (12D4e)
  * Firebase SDK version: 7.11.1
  * Installation method: CocoaPods
  * Firebase Component: Core

#### Steps to reproduce:

I run the Build phase script `"${PODS_ROOT}/FirebaseCrashlytics/upload-symbols" -bp`

And on Archive logs I see a success message (although also a warning)

```
Running upload-symbols in Build Phase mode
Validating build environment for Crashlytics...
Processing dSYMs...
warning: File to delete does not exist at path: /Users/d/Library/Developer/Xcode/DerivedData/Z-bmsgpbwaxmiqmhbmzchcsxmeojlm/Build/Intermediates.noindex/ArchiveIntermediates/Z/BuildProductsPath/Release-iphoneos/arm64-6bad620d672b3c6e9b8bb0213385a31a.csym
Successfully submitted symbols for architecture arm64 with UUID 6bad620d672b3c6e9b8bb0213385a31a in dSYM: /Users/d/Library/Developer/Xcode/DerivedData/Z-bmsgpbwaxmiqmhbmzchcsxmeojlm/Build/Intermediates.noindex/ArchiveIntermediates/Z /BuildProductsPath/Release-iphoneos/Z.app.dSYM
Successfully uploaded Crashlytics build event and symbols
```

And yet Crashlytics UI (within https://console.firebase.google.com/) always complains of "Missing dSYM files"

**Comment by rizafran** [comment]
Hi @daihovey, do you get the same error if you run the command [here](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=ios#upload-dsyms) manually and pass the dSYMs file and the .plist file?

**Comment by daihovey** [comment]
I get:
```
Successfully submitted symbols for architecture arm64 with UUID 4923f986ab843d5abcadf810ac9e0a5d in dSYM: /Users/d/dsyms/4923f986-ab84-3d5a-bcad-f810ac9e0a5d.dSYM
warning: Crashlytics found an invalid dSYM without any symbols at path: dsyms. This will result in missing stack frames for that library in Crashlytics. This can happen in some cases when a code obfuscator is used, or when symbols are stripped from the library / app. For more information, please visit the Crashlytics docs. To silence this warning, pass the --skip-dsym-validation flag to upload-symbols / run.
Successfully uploaded Crashlytics symbols
```

**Comment by rizafran** [comment]
Sorry to hear that you're still having issues, @daihovey. I think the best next step here is to file through [Firebase support](https://firebase.google.com/support) so they can look into the backend of your project and check your configurations. With this, I'll be closing this issue. Thanks.
