### ISSUE TITLE
 Showing All Messages Undefined symbol: _OBJC_CLASS_$_FIRMessaging

### ISSUE THREAD

**Issue by TomAshTee** [firebase/firebase-ios-sdk#8180]
REQUIRED] Step 1: Describe your environment

Xcode version: Version 12.5 (12E262)
Firebase SDK version: 8.0
Installation method: CocoaPods
Firebase Component: firebase messaging

[REQUIRED] Step 2: Describe the problem

Building the project fails due to the following error. 

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FIRMessaging", referenced from:
      objc-class-ref in RNFBMessaging+AppDelegate.o
      objc-class-ref in RNFBMessaging+FIRMessagingDelegate.o
      objc-class-ref in RNFBMessagingModule.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by paulb777** [comment]
@TomAshTee Sorry about the trouble this looks like a react-native integration issue and might be better addressed at https://github.com/invertase/react-native-firebase/issues

**Comment by paulb777** [comment]
I'm going to close since this isn't the best place for React Native integration issues.
