### ISSUE TITLE
GTM tags not sent when when a variable from "Fields to Set" is not defined

### ISSUE THREAD

**Issue by vladwhd** [firebase/firebase-ios-sdk#8190]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: using via `@react-native-firebase/analytics@^11.3.3`. Here is what I have in my `Manifest.lock`: 
GoogleTagManager (7.2.0):
    - FirebaseAnalytics (~> 7.0)
    - GoogleAnalytics (~> 3.17)
    - GoogleUtilitiesLegacy (~> 1.3)

  * Installation method: `CocoaPods`
  * Firebase Component: `Analytics` (`GoogleTagManager` Pod)

#### Steps to reproduce:

1. Create a GTM container and add a variable in a `Fields to Set` (cd6 on screenshot, corresponding to userId).
![image](https://user-images.githubusercontent.com/58254981/120787247-701cc300-c52f-11eb-95fb-7a6a1de1d481.png)
2. Include the GTM container json into the project, as described here https://developers.google.com/tag-manager/ios/v5#add-gtm-to-project
3. Try to send a custom tag without specifying the variable from "Fields to Set" (cd6 in my case).
4. See that the tag is sent to Firebase, but not to GTM. And get the error in console like this: `GoogleTagManager error: Error executing tag 0: TypeError: cannot access property of null.` (this is coming from the `TAGRuntime.js.dat` file).
5. Set any value to the variable in question and see that the tag is successfully sent to GTM (check console output)

Sorry, as I'm using react-native, I don't think that the code sending the tag is relevant. 
By the way, sending the same tag causes no issues on android.

**Comment by paulb777** [comment]
Please redirect this issue to Tag Manager support [here](https://support.google.com/tagmanager/community?hl=en)
