### ISSUE TITLE
Crash: [FBLPromise HTTPBody]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by elefantel** [firebase/firebase-ios-sdk#8191]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 8.0.0
  * Installation method: `CocoaPods`
  * Firebase Component: GoogleDataTransport

#### Steps to reproduce:
Launching the app causes a crash: `[FBLPromise HTTPBody]: unrecognized selector sent to instance`. It does not happen all the time, but we get it very often when running unit tests locally on a development machine and on a Jenkins server.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

Crash happens on line 290 of `GDTCCTUploadOperation.m`: `if (response.HTTPBody) `
```
/** Parses server response and update next upload time for the specified target based on it. */
- (void)updateNextUploadTimeWithResponse:(GULURLSessionDataResponse *)response
                               forTarget:(GDTCORTarget)target {
  GDTCORClock *futureUploadTime;
  if (response.HTTPBody) {
    NSError *decodingError;
    gdt_cct_LogResponse logResponse = GDTCCTDecodeLogResponse(response.HTTPBody, &decodingError);
    if (!decodingError && logResponse.has_next_request_wait_millis) {
      GDTCORLogDebug(@"CCT: The backend responded asking to not upload for %lld millis from now.",
                     logResponse.next_request_wait_millis);
      futureUploadTime =
          [GDTCORClock clockSnapshotInTheFuture:logResponse.next_request_wait_millis];
    } else if (decodingError) {
      GDTCORLogDebug(@"There was a response decoding error: %@", decodingError);
    }
    pb_release(gdt_cct_LogResponse_fields, &logResponse);
  }
```

Crash log:
```
2021-06-04 10:38:47.744960+0200 AppDev[27637:442327] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[FBLPromise HTTPBody]: unrecognized selector sent to instance 0x600003633cc0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20421af6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff204306f7 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   CoreFoundation                      0x00007fff20426036 ___forwarding___ + 1489
	4   CoreFoundation                      0x00007fff20428068 _CF_forwarding_prep_0 + 120
	5   AppDev                             0x0000000108d48d1d -[GDTCCTUploadOperation updateNextUploadTimeWithResponse:forTarget:] + 109
	6   AppDev                             0x0000000108d47fce __64-[GDTCCTUploadOperation sendURLRequestWithBatch:target:storage:]_block_invoke + 126
	7   AppDev                             0x0000000108d95e67 __56-[FBLPromise chainOnQueue:chainedFulfill:chainedReject:]_block_invoke.67 + 135
	8   AppDev                             0x0000000108d95586 __44-[FBLPromise observeOnQueue:fulfill:reject:]_block_invoke_2 + 166
	9   libdispatch.dylib                   0x00007fff2010532f _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x00007fff20106508 _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x00007fff2010c540 _dispatch_lane_serial_drain + 1042
	12  libdispatch.dylib                   0x00007fff2010cf74 _dispatch_lane_invoke + 403
	13  libdispatch.dylib                   0x00007fff20117577 _dispatch_workloop_worker_thread + 782
	14  libsystem_pthread.dylib             0x00007fff61167499 _pthread_wqthread + 314
	15  libsystem_pthread.dylib             0x00007fff61166467 start_wqthread + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[FBLPromise HTTPBody]: unrecognized selector sent to instance 0x600003633cc0'
terminating with uncaught exception of type NSException
CoreSimulator 732.18.6 - Device: iPhone 12 Pro Max (448F89C9-C3E9-406E-B254-DF56A211EC0B) - Runtime: iOS 14.4 (18D46) - DeviceType: iPhone 12 Pro Max
```

**Comment by rizafran** [comment]
Thanks for rerporting, @elefantel. The logs you shared looks related to issue #7939. With this, could you please try the solution provided on that issue, and see if the issue will persist?

**Comment by elefantel** [comment]
Sorry, been out for a bit. @rizafran yes, using dynamic frameworks fixed the issue for us, thanks! We ran into some issues and had to change the xcode config a bit but once that was sorted it has consistently worked fine. Thanks!

**Comment by morganchen12** [comment]
Closing this issue since it appears to be resolved. Thanks for the follow-up @elefantel!
