### ISSUE TITLE
When will you open android and unity sdk?

### ISSUE THREAD

**Issue by Thaina** [firebase/firebase-ios-sdk#82]
Sorry that this is not relate to ios sdk. But I don't know where can I get this answer

Why no unity sdk and android sdk be opensourced?

**Comment by paulb777** [comment]
As described in the [announcement blog](https://opensource.googleblog.com/2017/05/open-sourcing-firebase-sdks.html),  it's under investigation.

**Comment by Thaina** [comment]
@paulb777 Thanks but there are nothing mention about unity sdk at all

**Comment by paulb777** [comment]
@Thaina You're right. Unity is implicitly referred to in the first sentence - "we are taking our first steps towards open sourcing our client libraries", but not explicitly called out.

I'm sorry that I can't say anything more definitive than our intent is to continue towards open sourcing more and more of the Firebase client libraries.
