### ISSUE TITLE
Crash on app restart after force-killing it

### ISSUE THREAD

**Issue by glaurent** [firebase/firebase-ios-sdk#8204]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5
  * Firebase SDK version: 7.10
  * Installation method: CocoaPods
  * Firebase Component: Performance

#### Steps to reproduce:

In an app using Firebase Performance 7.10 :

- start app, let it display its first screen
- force-kill it
- restart app
- > crash

```
Last Exception Backtrace (0)#0	(null) in __exceptionPreprocess ()
#1	(null) in objc_exception_throw ()
#2	(null) in 0x19d5e3000 ()
#3	0x1040ea1d0 in __InstrumentDataTaskWithRequestCompletionHandler_block_invoke at /Users/glaurent/Development/Work/Symphony/SIOS-Client-App/Pods/FirebasePerformance/FirebasePerformance/Sources/Instrumentation/Network/FPRNSURLSessionInstrument.m:305
#4	0x1040ea1d0 in __InstrumentDataTaskWithRequestCompletionHandler_block_invoke at /Users/glaurent/Development/Work/Symphony/SIOS-Client-App/Pods/FirebasePerformance/FirebasePerformance/Sources/Instrumentation/Network/FPRNSURLSessionInstrument.m:305
#5	0x104183d08 in __60-[NSURLSession(GULPromises) gul_dataTaskPromiseWithRequest:]_block_invoke at /Users/glaurent/Development/Work/Symphony/SIOS-Client-App/Pods/GoogleUtilities/GoogleUtilities/Environment/URLSessionPromiseWrapper/NSURLSession+GULPromises.m:32
#6	0x1041c3100 in __44+[FBLPromise(AsyncAdditions) onQueue:async:]_block_invoke at /Users/glaurent/Development/Work/Symphony/SIOS-Client-App/Pods/PromisesObjC/Sources/FBLPromises/FBLPromise+Async.m:33
#7	(null) in _dispatch_call_block_and_release ()
```

**Comment by maksymmalyhin** [comment]
@glaurent Sorry for the trouble. I was not able to reproduce the issue based on the provided information. Could you please provide more information for us to be able to make progress on the issue:
- stack traces of other thread from the crash report
- a sample project where the issue is reproducible

**Comment by glaurent** [comment]
> @glaurent Sorry for the trouble. I was not able to reproduce the issue based on the provided information.

It turned out to be caused by a configuration issue in our app, which we've fixed.
