### ISSUE TITLE
In App messaging doesn't compile with last Xcode 12.5

### ISSUE THREAD

**Issue by angelmic** [firebase/firebase-ios-sdk#8205]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5(12E262)
  * Firebase SDK version:  8.1.0
  * Installation method: `CocoaPods` (select one)
  * Firebase Component: In App Messaging (Auth, Core, Database, Firestore, Messaging, Storage, etc)

### [REQUIRED] Step 2: Describe the problem
![image](https://user-images.githubusercontent.com/721674/120968787-e1f94480-c79b-11eb-9374-2b6ebd690fe2.png)

- 1 missing file 
> Pods/FirebaseInAppMessaging/FirebaseInAppMessaging/iOS/Resources/FIRInAppMessageDisplayStoryboard.storyboard:1:1: close-with-transparency.png not found 
- 3 constrains error
> Pods/FirebaseInAppMessaging/FirebaseInAppMessaging/iOS/Resources/FIRInAppMessageDisplayStoryboard.storyboard:1:1: UIView (Aft-rr-icV) has ambiguous constraints
> Pods/FirebaseInAppMessaging/FirebaseInAppMessaging/iOS/Resources/FIRInAppMessageDisplayStoryboard.storyboard:1:1: UIButton (aZE-3x-WHk) has ambiguous constraints
> Pods/FirebaseInAppMessaging/FirebaseInAppMessaging/iOS/Resources/FIRInAppMessageDisplayStoryboard.storyboard:1:1: UIButton (Feg-VM-jUf) has ambiguous constraints

#### Steps to reproduce:
1. Add 'Firebase/InAppMessaging' to Podfile
2. `pod install`
3. open xcode workspace
4. compile and run

#### Relevant Code:
pod version: 1.10.0
```ruby
  pod 'Firebase/Analytics', '8.1.0'
  pod 'Firebase/Crashlytics', '8.1.0'
  pod 'Firebase/InAppMessaging', '8.1.0'
```

**Comment by christibbs** [comment]
@angelmic Thanks for reporting. I'm not able to reproduce the failed compilation or the missing image, but I did see the missing constraints issues you mentioned. I sent #8243 to fix those. Is your project treating warnings as errors? Perhaps that's what's causing the failed compilation.
