### ISSUE TITLE
App Store rejecting binaries due to Non-public API usage

### ISSUE THREAD

**Issue by Alexsilvacodes** [firebase/firebase-ios-sdk#8222]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5
  * Firebase SDK version: 8.1.0 / 7.11.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: Analytics / Crashlytics / RemoteConfig - not 100% sure

### [REQUIRED] Step 2: Describe the problem
We are using Firebase Analytics, RemoteConfig and Crashlytics importing this SDK via SPM, since two days ago our binaries are getting rejected by Apple with the following message
```
ITMS-90338: Non-public API usage - The app references non-public selectors in <app>: determineAppInstallationAttributionWithCompletionHandler:, didLongPress:, didPan:, didTap, didTouchUpInside, lookupAdConversionDetails:, resetState, sendMessage, textDidChange, transform:.
``` 
Our app doesn't use any of those methods, but checking our `symbolmap` we discovered that Firebase SDK is using the method `lookUpAdConversionDetails`.
We are having this issues without changing any dependency version or Xcode configuration, so looks like Apple changed their API-usage process.

We are investigating if this is an Apple issue or is something that Firebase should take action on, if you can provide more info about this it will be much appreciated.

**Comment by ryanwilson** [comment]
Hey @Alexsilvacodes - thanks for the report. We'll look into this ASAP to get it resolved. At first glance, it looks like this it was a public API that was deprecated and is now removed from the public headers in iOS 15.

**Comment by ryanwilson** [comment]
Filed internally at b/190661518. Note: for the `beta-software` label it's to acknowledge this is due to iOS 15 changes, I recognize that this happens still with publicly released versions.

**Comment by Alexsilvacodes** [comment]
Hi @ryanwilson, thank you for your quick response! Right now we are not using anything related with iOS 15, our target is iOS 14 and in fact we got this using Firebase `7.11.0`, then we tried `8.1.0` just to see if there was any change on the SDK to fix that.

**Comment by ryanwilson** [comment]
Thanks @Alexsilvacodes, this is definitely a change on the App Store side. My suspicion is they now updated the "private APIs" list, and since the API being used was in a public header before and removed, it's now on the private API list and being flagged (regardless if you're supporting any iOS 15 features or not).

We'll hopefully have another update in a few hours, a lot of the team is in California so it's still quite early there before they'll see this and we can evaluate the impact. Stay tuned, and thanks again for the report.

**Comment by Alexsilvacodes** [comment]
Amazing @ryanwilson , thank you so much for the quick and thoughtful response!

**Comment by paulb777** [comment]
Firebase 8.1.1 is now published for CocoaPods and Swift Package Manager. The zip and Carthage distributions are planned to be updated tomorrow (Friday)

**Comment by paulb777** [comment]
8.1.1 is now available for zip and Carthage distributions as well.
