### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_OBJC_CLASS_$_FIRApp", referenced from:       objc-class-ref in PushPlugin.o

### ISSUE THREAD

**Issue by mbdeme** [firebase/firebase-ios-sdk#8226]
Hello 
I have this error : Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FIRApp", referenced from:
      objc-class-ref in PushPlugin.o

project Cordova IOS firebase plugin push in Xcode 12.
Have you any idea please?
Thanks

**Comment by catman-19** [comment]
Hi @mbdeme, it seems that your inquiry doesn't follow the template. With this, I'll be closing this ticket for now.

In order for me to get a better understanding of this issue, you may file another ticket that uses the issue template.

Thanks.
