### ISSUE TITLE
[Firebase/Core][I-COR000003] The default Firebase app has not yet been configured.

### ISSUE THREAD

**Issue by taihnguyen1210** [firebase/firebase-ios-sdk#8227]
### [REQUIRED] Step 1: Describe your environment

   * Platform: Macbook Pro M1
  * Xcode version: 12.0.1
  * Firebase SDK version: 7.11.0
  * Installation method: Carthage
  * Firebase Component: DynamicLinks, Crashlytics, Auth, Database, Remote Config, Analytics

### [REQUIRED] Step 2: Describe the problem

My app was crashed at "FirebaseApp.configure()" when I start to run it.

Here is the console log:
```[Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization.```

Especially It was crashed when I run it on iOS 12.0, 12.4, and iOS 13.7 but it works on iOS 14.0. However, It's not crashed for all the above cases when I test on another laptop (is not M1) with Xcode 12.0.0.

How can I find the problem, please?

It's crashed at
```
FirebaseApp.configure()
```

**Comment by maksymmalyhin** [comment]
@taihnguyen1210 Sorry for the trouble. It looks like a symptom of Firebase SDK symbols being included twice(or multiple) times in you app binary. Can you see console messages like the following? 
```
objc[40943]: Class FIRApp is implemented in both
~/Library/Developer/Xcode/DerivedData/FrameworkTest-apqjxlyrxvkbhhafhaypsbdquref/Build/Products/Debug-iphonesimulator/DynamicFramework.framework/DynamicFramework
(0x10b2a87f8) and
~/Library/Developer/CoreSimulator/Devices/4821F959-24A6-4D78-A102-4C5703103D99/data/Containers/Bundle/Application/F017D210-113A-4DAF-9E17-BDE455E71E06/FrameworkTest.app/FrameworkTest
(0x10ad2d348). One of the two will be used. Which one is undefined.
```

See more details on this type of issues and solutions [here](https://github.com/firebase/firebase-ios-sdk/blob/master/docs/firebase_in_libraries.md#using-firebase-sdks-from-dynamic-frameworks).

**Comment by taihnguyen1210** [comment]
> @taihnguyen1210 Sorry for the trouble. It looks like a symptom of Firebase SDK symbols being included twice(or multiple times) in you app binary. Can you see console messages like the following?
> 
> ```
> objc[40943]: Class FIRApp is implemented in both
> ~/Library/Developer/Xcode/DerivedData/FrameworkTest-apqjxlyrxvkbhhafhaypsbdquref/Build/Products/Debug-iphonesimulator/DynamicFramework.framework/DynamicFramework
> (0x10b2a87f8) and
> ~/Library/Developer/CoreSimulator/Devices/4821F959-24A6-4D78-A102-4C5703103D99/data/Containers/Bundle/Application/F017D210-113A-4DAF-9E17-BDE455E71E06/FrameworkTest.app/FrameworkTest
> (0x10ad2d348). One of the two will be used. Which one is undefined.
> ```
> 
> See more details on this type of issues and solutions [here](https://github.com/firebase/firebase-ios-sdk/blob/master/docs/firebase_in_libraries.md#using-firebase-sdks-from-dynamic-frameworks).

Thanks for your reply. Sorry, I don't see it in the console messages. It just show "[Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization."
Btw, Should I clear the DerivedData folder?

**Comment by taihnguyen1210** [comment]
> @taihnguyen1210 You can try clearing the DerivedData folder. If it doesn't solve your issue we most likely will need a sample project where you issue is reproducible to make any progress on the it.

I cleared the DerivedData folder but it does not work. I am trying to create a sample project to reproduce it. Thanks

**Comment by dezudas** [comment]
I am facing the same issue +1

**Comment by taihnguyen1210** [comment]
I try to run on an iOS 12 real device then It works. I think there are some problems with simulators.

**Comment by paulb777** [comment]
@taihnguyen1210 Interesting. There may be a race condition in the app so the timing works differently. Can you share a backtrace of the simulator crash?
