### ISSUE TITLE
fetchRemoteConfige compltionhander not called sometime

### ISSUE THREAD

**Issue by moontecholabs** [firebase/firebase-ios-sdk#824]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.3
  * Firebase SDK version: 3.17.0
  * Firebase Component:Auth, Core, RemoteConfig, Messaging, FirebaseAnalytics, FirebaseInstanceID))
  

### [REQUIRED] Step 3: We have Implemented firebase  RemoteConfig.
while testing we have noticed some time compltionhandler of fetchremoteConfig not called.

#### Steps to reproduce:

we don't facing this everytime but it occurs randomly

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```
var expirationDuration = 3600
var remoteConfig: RemoteConfig!
 remoteConfig = RemoteConfig.remoteConfig()
let remoteConfigSettings = RemoteConfigSettings(developerModeEnabled: false)
        remoteConfig.configSettings = remoteConfigSettings!
 remoteConfig.fetch(withExpirationDuration: TimeInterval(expirationDuration)) { (status, error) -> Void in
            if status == .success {
                self.remoteConfig.activateFetched()
                completion()
            } else {
                completion()
            }
        }

**Comment by morganchen12** [comment]
Does this only happen on subsequent fetches? Looks like your expiration behavior may be causing infrequent refreshes.

**Comment by moontecholabs** [comment]
Does this only happen on subsequent fetches? 
Looks like your expiration behavior may be causing infrequent refreshes.
-> Yes, we are calling multiple times this function.

**Comment by morganchen12** [comment]
Try setting the `expirationDuration` to `0` and seeing if you get refreshes immediately. 

If not, please enable debug logging via `FIRConfiguration.sharedInstance().setLoggerLevel(.debug)` and post any relevant logs here.
