### ISSUE TITLE
'FirebaseInstallations will not work correctly with current version of Firebase Instance ID xCode 12.5 and iOS V 14.5

### ISSUE THREAD

**Issue by shoaibhassan1** [firebase/firebase-ios-sdk#8251]
I am also facing same issue as app getting crash each time after i run pod update statement.
Using xcode 12.5 with OS  version 14.5
Please investigate as i already spent many hours on it for searching and could't find any solution
Thanks in advance.

### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: _____
  * Firebase SDK version: _____
  * Installation method: `CocoaPods | Carthage | Zip file | Swift Package Manager` (select one)
  * Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulb777** [comment]
@shoaibhassan1 Sorry about the trouble. Please fill out the issue template and share a backtrace of the crash.

**Comment by shoaibhassan1** [comment]
Xcode version: 12.5
Firebase SDK version: 8.1
Installation method: CocoaPods 
Firebase Component: as follows

   pod 'Firebase/Core'
    pod 'FirebaseMessaging'
    pod 'FirebaseInstanceID'
    pod 'Firebase/Database'
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Analytics'
    
    
    I just recently updated all pods, and it start crashing on following line of code
           
  `   FirebaseApp.configure()`

    and crash logs are as follows
    'FirebaseInstallations will not work correctly with current version of Firebase Instance ID"

**Comment by paulb777** [comment]
FirebaseInstanceID is no longer available with Firebase 8.x. See the documentation for the related API updates for FirebaseMessaging and FirebaseInstallations.

**Comment by paulb777** [comment]
I'm going to close, but feel free to continue the discussion here if you have additional questions.
