### ISSUE TITLE
Price is multiplied by one million in analytics

### ISSUE THREAD

**Issue by Ricardo1980** [firebase/firebase-ios-sdk#8280]
### Step 0: Are you in the right place?

  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 12.3 (12C33)
  * Firebase SDK version: Firebase/AnalyticsWithoutAdIdSupport (8.0.0):
  * Installation method: CocoaPods
  * Firebase Component: Analytics

### [REQUIRED] Step 2: Describe the problem

I see that when sending £70 in the purchase parameters, the debug view shows 70.000.000.
Is that expected or a bug?
See screenshots:

<img width="680" alt="Screenshot 2021-06-20 at 19 02 57" src="https://user-images.githubusercontent.com/738681/122683996-d32e7b00-d1fa-11eb-9ccc-9248f9cb1d69.png">
<img width="1069" alt="Screenshot 2021-06-20 at 19 02 23" src="https://user-images.githubusercontent.com/738681/122683998-d4f83e80-d1fa-11eb-9649-eec8887a8353.png">

#### Relevant Code:

```
Not needed
```

**Comment by rizafran** [comment]
Sorry for the late reply, @Ricardo1980. I see that there are trailing zeros on your price parameter in the DebugView. Per checking, I found an internal bug (b/179015589) similar to your issue, which appears to be a bug on the backend. With this, you may file to [Firebase support](https://firebase.google.com/support) if you have any questions regarding this or you want to follow up the progress in the investigation. Thanks.
