### ISSUE TITLE
Crashlytics requiring dSYM UUID that isn't found.

### ISSUE THREAD

**Issue by Josiah-Agosto** [firebase/firebase-ios-sdk#8293]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5
  * Firebase SDK version: 7.10.0
  * Installation method: CocoaPods
  * Firebase Component: Crashlytics

### [REQUIRED] Step 2: Describe the problem
I've encountered an issue with dSYM files. Currently Crashlytics tells me I have 3 files that have to be fixed, it provides the version for the file. After many different avenues of searching for these dSYM files, it seems there is an issue with the file or UUID. These UUID's cannot be found anywhere inside those versions and any version that was every published.
<img width="941" alt="Screen Shot 2021-06-23 at 4 38 13 PM" src="https://user-images.githubusercontent.com/22554016/123164844-7670d180-d441-11eb-839c-82ab55427291.png">

For a little background information to if these files are being generated, they are. I have uploaded a few before, and the app does use, DWARF with dSYM File. Bitcode is also enabled for all builds.

Things I've tried:
- Downloading dSYM files through App Store connect. In fact I've downloaded every version that is out.
- Checked through Xcode derived data for devices that may save dSYM files.
- Checked my local computer for any remaining files.
- Used, "mdfind -name .dSYM | while read -r line; do dwarfdump -u "$line"; done", "mdfind "com_apple_xcode_dsym_uuids == UUID"".

Nothing!

**Comment by elenadoty** [comment]
Hi @Josiah-Agosto ,
Is it possible that the plist file for this app was included in a different app (accidentally or not) at any point? If so, any crashes from that app would be sent to the one above, and since we wouldn't have the dSYM files for the second app they would show up as missing. If you don't see any missing frames in your crashes and aren't noticing any decrease in the number of expected crashes, the warnings are probably okay to ignore (and will age out after 90 days).

**Comment by Josiah-Agosto** [comment]
Thanks @elenadoty for looking into this. I actually did check to make sure the plist files were the same throughout the project and contained the correct information, but I will check in with the team to make sure that didn't happen. I'll get back to you as soon as possible.

**Comment by Josiah-Agosto** [comment]
So after further investigation the Google Plist was only used for one app. Actually there is only one app attached to the account in Firebase. I know I've seen an issue before with Crashlytics referencing the wrong UUID, I am sure this is the case, but don't know why.

**Comment by elenadoty** [comment]
Thanks for the update @Josiah-Agosto . 

There are a couple other things that might help us figure out what's going on here:
1. Can you check if the missing dSYMs are present in the app archives in Xcode Organizer (if you haven't already)?
2. How recently did you notice the missing dSYMs, and did you download the dSYMs from Apple before or after noticing them? I'm wondering if Apple may have recompiled the app for some reason.

**Comment by Josiah-Agosto** [comment]
Hey, so since I have bitcode enabled for the app and any debug information to be sent to App Store connect It should be sending all dSYM's to App Store connect where I can download them after a build was sent. Also, I have checked the Xcode Organizer, but since I don't usually do check there I delete any remaining builds I don't need. As I mentioned before I did download every single dSYM file for every version in App Store connect which will, I hope, give me the same as in Xcode archives.

Out of three of them, 2 are very recent, like a few days ago I noticed I can't find them. One on the other hand is just lost, it's been there for a few weeks.

**Comment by elenadoty** [comment]
Hi @Josiah-Agosto ,
Would you be willing to file a ticket with our support team so that we can get more details about your project and app? The link to do so is [here](https://firebase.google.com/support/troubleshooter/contact).
Thanks!

**Comment by Josiah-Agosto** [comment]
Hello @elenadoty, I would have to consult with the team to see, but, I just checked crashlytics and the required files disappeared. As in seemed to fix itself. Is this something that occurs after it alerted me it was required?

**Comment by elenadoty** [comment]
Hi @Josiah-Agosto ,
That isn't the usual behavior of dSYM alerts, no. They will disappear 90 days after the associated crash occurred since we delete all crashes after that time period has passed. It's possible that a crash occurred a while ago but wasn't uploaded because the user didn't reopen the app until recently, and then that crash was deleted from our systems because the 90 day threshold was reached. This is probably unlikely since you weren't able to find the dSYMs anywhere, unless Apple recompiled the app and deleted the old dSYM. If this happens again feel free to reach out directly to support and we can pick up the investigation from there!

**Comment by Josiah-Agosto** [comment]
Hey @elenadoty, yeah it's only been like a week or so since those dsym files were telling me to upload them so it definitely didn't reach the 90 days. When I look through the file history it shows them in there as the file was uploaded. Very weird and I don't understand how it did it, but if it happens again I know where to come. Thank you!

**Comment by Josiah-Agosto** [comment]
Hey, so it occurred again the day before yesterday and I've checked around and there are no indications for these dsym files. In fact the files they are requesting are from an older version a while ago.
<img width="939" alt="Screen Shot 2021-07-02 at 1 32 39 PM" src="https://user-images.githubusercontent.com/22554016/124310447-2e853500-db3a-11eb-93d3-019e85fc81d9.png">

**Comment by elenadoty** [comment]
Hi @Josiah-Agosto ,
Sorry to hear this has showed up again! Would you mind filing a ticket with support so that we can get your app and project information and do some investigation in our backend?

**Comment by Josiah-Agosto** [comment]
Hey @elenadoty, yeah weird things are happening with those dsym files. In fact all those you see in the above image have disappeared and seemed to resolve themselves. There have been others that have popped up and also disappeared or resolved themselves days after. I will be creating the ticket for this, thanks!
