### ISSUE TITLE
Latest GTMSessionFetcher's new deprecation breaks Storage CI

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#8294]
See https://github.com/firebase/firebase-ios-sdk/pull/8292/checks?check_run_id=2898960029 and 

![Screen Shot 2021-06-23 at 1 47 16 PM](https://user-images.githubusercontent.com/73870/123165802-87154d80-d429-11eb-903a-f3fc93f3d28b.png)

From GTMsessionFetcherService.h:
// DEPRECATED: Callers should use XCTestExpectation instead.
//
// Spin the run loop and discard events (or, if not on the main thread, just sleep the thread)
// until all running and delayed fetchers have completed.
//
// This is only for use in testing or in tools without a user interface.
//
// Synchronous fetches should never be done by shipping apps; they are
// sufficient reason for rejection from the app store.

Given that comment, it seems we might need a more significant refactor than most warnings require.

cc: @thomasvl

**Comment by schmidt-sebastian** [comment]
@morganchen12 - Can you take care of this?

**Comment by thomasvl** [comment]
@mwyman fyi also

I believe the api docs have always said it should only be used in tests (or tools without UI).
