### ISSUE TITLE
pod spec lint test issue

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#8299]
In #8296, the `pod spec lint` test used the tagged FirebaseStorage instead of tagging the Storage version in the PR and testing that. See https://github.com/firebase/firebase-ios-sdk/runs/2908089966

**Comment by granluo** [comment]
The workflow should catch the changes when [checkout](https://github.com/firebase/firebase-ios-sdk/blob/master/.github/workflows/storage.yml#L178). If we `pod spec lint` a local podspec , I expect it is testing the local changes, will investigate.

**Comment by paulb777** [comment]
Closing as low priority
