### ISSUE TITLE
observe single event returning cached data

### ISSUE THREAD

**Issue by spandana-batchu** [firebase/firebase-ios-sdk#83]
We are facing the below issue on our iOS app that uses firebase iOS SDk. 
To give you some context, the users of our app are part of Groups. Each of these groups have some group information. 
In the database we have user who is mapped with a list of group IDs. Using these Group Ids Further we fetch group’s info. Below is the structure. 
```
+User1
    +GroupID1
        +timestamp
    +GroupID2
        +timestamp
+GroupID1
    +groupName:
    +groupInfo:
    +groupCount:……
    +timestamp
```
Whenever there is a change in group’s info, we have a firebase cloud fuction that updates the timestamp at both the places. Hence any change to group’s info would notify the observers at both references `database\GroupID1` and `database\User1`
The issue we are facing is that we have a continuous observer at reference `database\User1` using the method observe event type. 
Changes to group info is notifying that continuous observer as expected. After which we are fetching group info using observe single event method. But that group info returned is the cached info. 
The info returned at reference `database\GroupID1` is always one step old data. 
Is there anything we are missing here.

**Comment by paulb777** [comment]
Replaced by #84
