### ISSUE TITLE
FR: Support array / dictionary values in remote config defaults

### ISSUE THREAD

**Issue by jakekrog** [firebase/firebase-ios-sdk#8306]
### Feature proposal

* Firebase Component: Remote Config

JSON arrays / objects are supported as remote config parameter values, but are not currently supported as values in the property list provided to `setDefaults(fromPlist:)`

**Comment by paulb777** [comment]
@jakekrog Would you explain in more detail what you are looking for? JSON is not a valid type for plist fields. Although I suspect a workaround would be to set the default as a String and read it back as JSON.

**Comment by paulb777** [comment]
Oops, looks like I mistakenly closed this one while there's an open PR to address. Sorry. I'll follow up with the team again
