### ISSUE TITLE
Firebase version not getting updated to latest v8

### ISSUE THREAD

**Issue by jharsh1202** [firebase/firebase-ios-sdk#8312]
I have no options to install firebase v8, it's installing 7.3.1 in Xcode 13 beta I tried the same way in Xcode 12 it install v8 as expected. 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41900044/123575175-d0311d00-d7ee-11eb-8851-a809f1e81d14.png">

**Comment by rizafran** [comment]
I'll be closing this issue since it's a duplicate of #8313. Thanks.
