### ISSUE TITLE
Couldn't install v8 of firebase iOS SDK to Xcode 13 beta Same is possible with Xcode 12

### ISSUE THREAD

**Issue by jharsh1202** [firebase/firebase-ios-sdk#8313]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Xcode 13 beta
  * Firebase SDK version: Latest
  * Installation method: Swift Package Manager
  * Firebase Component: All

### [REQUIRED] Step 2: Describe the problem
I couldn't install firebase iOS SDK v8 to my Xcode 13 beta but same is possible on Xcode 12. it's installing with 7.3.1 and not upgrading to v8 anyway.

#### Steps to reproduce:

Couldn't get the latest version 8.3 of firebase to my Xcode 13 beta, but it's being integrated to Xcode 12 the same way with SPM

![](https://user-images.githubusercontent.com/41900044/123575175-d0311d00-d7ee-11eb-8851-a809f1e81d14.png)

#### Relevant Code:
Na
```
Just integrate it with SPM in your project.
```

**Comment by paulb777** [comment]
I'm not sure what is going on here, but here are some points worth following up on:

- Why is the 7.x version 7.3.1 instead of the latest 7.11.0?
- Why are there two firebase-ios-sdk packages in the screenshot? Is one a fork?
- The app name FirebaseAuth might be a problematic conflict with the FirebaseAuth product
- A reproducible example would be helpful

**Comment by jrcrespoh** [comment]
Here’s a workaround: 

When first adding the Firebase SDK using Swift Package Manager through Xcode13 beta, you will see a similar screen.
![image](https://user-images.githubusercontent.com/8367227/124168330-9bc99500-da6a-11eb-93c4-57fef1cc2bf4.png)
The dependency rule dropdown allows you to customize the compatibility of your app with Firebase versions. Despite what is shown, you can use versions beyond 8.0.0. I then select the dependency rule Up to Next Minor Version and type in 8.2.0 into the text field to indicate that I want my app to be compatible up to Firebase version 8.3.0.
![image](https://user-images.githubusercontent.com/8367227/124168404-b3a11900-da6a-11eb-8bc5-94e1825836d8.png)
After pressing Add Package by the lower right of the screen, you will see a similar progress bar. Let the process finish.
![image](https://user-images.githubusercontent.com/8367227/124168441-c582bc00-da6a-11eb-870f-86e2abbffadb.png)
You will then be presented with a screen asking you to choose the specific Firebase libraries you want to use.
![image](https://user-images.githubusercontent.com/8367227/124168475-d3384180-da6a-11eb-8ef9-84fde51d7492.png)
Select the libraries you want to use and then press Add Package. You will then be able to verify that the correct version of Firebase was installed under Swift Package Dependencies in the Project Navigator on the left hand side bar. Additionally, under the Info section of your project, you should see the dependency rule you selected under Version Rules.
![image](https://user-images.githubusercontent.com/8367227/124168570-f662f100-da6a-11eb-9f78-30e2effb64fc.png)

**Comment by jharsh1202** [comment]
Thanks @Jesus Crespo
