### ISSUE TITLE
Firebase is calculating crash free users but not showing any crashes

### ISSUE THREAD

**Issue by BarryDuggan** [firebase/firebase-ios-sdk#8330]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment
  * Xcode 12.4
  * Firebase/Crashlytics (7.1.0)

### [REQUIRED] Step 3: Describe the problem
After our most recent release firebase console is showing that we 98.9% crash free users.
Simultaneously firebase is also reporting that we have 0 crashes and 0 user affected.
Firebase isn't reporting any required DSYM's 
#### Steps to reproduce:

We haven't changed anything in our app related to firebase for a long time.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by rizafran** [comment]
Hi @BarryDuggan. If there are no crashes being reported but the crash-free number has changed, it means that Crashlytics is misconfigured or not sending crashes for whatever reasons while the Analytics integration is working correctly. The following scenarios would be the possible cause of this:

1. A user crashes during a session.
2. The crash event is sent up to Analytics automatically, which then makes the calculation that a crash happened and adjusts the crash-free user number accordingly.
3. The user doesn't relaunch the app for some time, causing the crash report to not be sent to Crashlytics at the same time as the crash-free percentage is shifted.
4. The app is relaunched at a later time, causing the crash report to come through to Crashlytics but looks like there's a delay in data.

You could test the given scenario and see if you're able to reproduce the same issue. You could cause a test crash in your in-house test build and see if the crash-free user percentage changes before you even relaunch the app and send up the crash report. In case the issue persists, please file a ticket to [Firebase support](https://firebase.google.com/support/troubleshooter/crashlytics) so they can take a look into your project and configuration. Thanks.

**Comment by BarryDuggan** [comment]
@rizafran 

Thanks for the detailed explanation of what the cause might me.
I will do as you suggest and reply back with my findings.
