### ISSUE TITLE
Unit Test build fail

### ISSUE THREAD

**Issue by AlexanderPan** [firebase/firebase-ios-sdk#8333]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5.1
  * Firebase SDK version: 8.2.0
  * Installation method: Swift Package Manager
  * Firebase Component: Auth, Firestore

### [REQUIRED] Step 2: Describe the problem

Can't write unit test if my class contains firebase class.

like this: https://developer.apple.com/forums/thread/110880

![截圖 2021-07-02 下午5 45 30](https://user-images.githubusercontent.com/12975432/124255932-4c17c600-db5d-11eb-93e8-22dd9ca3112f.png)

**Comment by paulb777** [comment]
@AlexanderPan Thanks for the report. Please share a reproducible example.

**Comment by AlexanderPan** [comment]
After delete DerivedData it work.
