### ISSUE TITLE
When build on MacOS, I get a message saying, "[App] wants to use your confidential information stored in 'com.firebase.FIRInstallations.installations' in your keychain."

### ISSUE THREAD

**Issue by alelordelo** [firebase/firebase-ios-sdk#8335]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5.1 (12E507)
  * Firebase SDK version: 7.11.1
  * Installation method:  Swift Package Manager
  * Firebase Component: Auth, Core, Database, Firestore, Messaging, Storage

### [REQUIRED] Step 2: Describe the problem
When build on MacOS, I get a message saying, "[App] wants to use your confidential information stored in 'com.firebase.FIRInstallations.installations' in your keychain."

#### Steps to reproduce:

Build on MacOS

**Comment by paulb777** [comment]
Does it help to add `Keychain Sharing Capability` to Build Settings like it's documented here for Catalyst - https://github.com/firebase/firebase-ios-sdk#additional-catalyst-notes

**Comment by alelordelo** [comment]
thanks so much @paulb777 , this solver the issue! : )

**Comment by paulb777** [comment]
@alelordelo Great to hear! I'll send a PR to improve the docs.
