### ISSUE TITLE
waitForCompletionWithTimeout: is deprecated: Use XCTestExpectation instead

### ISSUE THREAD

**Issue by lefdilia** [firebase/firebase-ios-sdk#8347]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: _____
  * Firebase SDK version: _____
  * Installation method: `CocoaPods | Carthage | Zip file | Swift Package Manager` (select one)
  * Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```
![Screen Shot 2021-07-07 at 16 05 54](https://user-images.githubusercontent.com/17814540/124784347-bf468100-df3d-11eb-9fa5-331c893b3025.png)

Error on : FIRStorageDownloadTask.m

**Comment by rizafran** [comment]
Hi @lefdilia, please follow the template by including the Xcode and SDK version used, installation method, and steps to reproduce. Thanks.

**Comment by paulb777** [comment]
@lefdilia This issue is fixed in #8296 and will release in Firebase 8.3.0 that is due out later this week.

It's result of the recent GTMSessionFetcher 1.6.x release. 

The warning should be safe to ignore or it could be disabled by downrevving to  GTMSessionFetcher 1.5.x
