### ISSUE TITLE
Allow creating multiple apps with the same Bundle identifier to better distinguish cross-platform apps

### ISSUE THREAD

**Issue by Moriquendi** [firebase/firebase-ios-sdk#8355]
_This is not strictly SDK-related so I'm sorry for putting it here but I wasn't sure where to pitch it._

Right now, Firebase Console won't allow registering multiple apps with the same bundle identifier.
However, Apple allows (and even recommend) using the same bundle ID for the same app across different platforms (macOS, iOS, tvOS,...).

It leads to some issues. 
For example, because we can't distinguish apps on Firebase, all of the crashes are grouped under the same app.

What're your thoughts on that? :)

**Comment by ryanwilson** [comment]
Thanks for the question, @Moriquendi! 

I'm curious as to what you think is a better solution: being able to create multiple apps with the same bundle identifier (differentiated by platform), or having Crashlytics (or other products) have the ability to split out and filter crashes / other data by platform while keeping one app (similar to Apple's setup in App Store Connect)?

As a side note, if you're using Firebase on multiple platforms already we're working on some improvements and would love if you could sign up for early access to releases and have further conversations with us:  https://forms.gle/odseGnshb3Jq8wuz5

Thanks!

**Comment by Moriquendi** [comment]
@ryanwilson That's a good question. 
Personally I don't have any preference. On the other hand, it's inevitable that some people will forget to create a second Firebase App for their app on another platform. This should be somehow handled by Firebase so maybe it's better that all apps share the same config-files and the SDK/console itself should distinguish events/crashes/etc based on the User Agent.
And in the console, distinguishing those platforms would be done on a UI-level rather than on different setup/configs.

So - "Apple-like setup" is probably better.

Thanks for linking to the Firebase early access form :) I've signed up.

**Comment by elenadoty** [comment]
Hi @Moriquendi,
Since Apple multi-platform support is now rolled out, I'm going to close this issue. Feel free to re-open if it hasn't solved your use-case.

**Comment by Moriquendi** [comment]
> Hi @Moriquendi,
> Since Apple multi-platform support is now rolled out, I'm going to close this issue. Feel free to re-open if it hasn't solved your use-case.

Hey @elenadoty, can you explain what do you mean "multi-platform support" rolled out by Apple? I haven't heard any related news.

**Comment by elenadoty** [comment]
Hi @Moriquendi 
Sorry for the vagueness - I mean that Crashlytics has rolled out support for filtering crashes and other data by Apple platform while keeping one app (what Ryan had described above as the setup similar to App Store Connect).
