### ISSUE TITLE
Notification service extension linking error

### ISSUE THREAD

**Issue by weakfl** [firebase/firebase-ios-sdk#8359]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5.1
  * Firebase SDK version: 8.2.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: Messaging

### [REQUIRED] Step 2: Describe the problem

Linking of a notification service extension fails with `Undefined symbol: _OBJC_CLASS_$_FIRMessaging` when building for arm64/armv7. Building for simulator works as expected.

I've added `FirebaseMessaging` to the notification service extension target and, as mentioned, it's working fine when building for simulator:

<img width="600" alt="Screenshot 2021-07-08 at 16 56 13" src="https://user-images.githubusercontent.com/614985/124944846-f2584580-e00d-11eb-8f6e-94ff82962468.png">

**Comment by paulb777** [comment]
Thanks for the report. A reproducible example would be helpful for an investigation.

**Comment by weakfl** [comment]
@paulb777 While trying to replicate the problem I noticed that it only happens with a deployment target of iOS 10. iOS 11+ seems to work fine.

[Here](https://github.com/firebase/firebase-ios-sdk/files/6789505/TestProject.zip)'s a sample project...

**Comment by chliangGoogle** [comment]
@weakfl I'm not able to reproduce with your project under iOS 10 deployment target.
![Screen Shot 2021-07-09 at 2 34 32 PM](https://user-images.githubusercontent.com/27706281/125138070-d4005180-e0c2-11eb-95b4-99bba0d24806.png)

**Comment by weakfl** [comment]
@chliangGoogle Don't use an actual device but try to compile for `Any iOS Device (arm64, armv7)`.

Your device is probably `arm64` and the linker complains about `armv7`: `ld: symbol(s) not found for architecture armv7`

**Comment by paulb777** [comment]
@weakfl Thanks for the details. I'm able to reproduce.  This looks like an Xcode issue of failing to build the SPM dependency of the extension for armv7.

A workaround is to only build for arm64 (in both the TestProject and Extension Target Build Settings:

![Screen Shot 2021-07-10 at 7 53 27 AM](https://user-images.githubusercontent.com/73870/125167144-eb3b4f80-e153-11eb-81da-04e21ec85697.png)

**Comment by weakfl** [comment]
> This looks like an Xcode issue of failing to build the SPM dependency of the extension for armv7.

I've filed a bug report with Apple but I wouldn't hold my breath for a bugfix ;)

> A workaround is to only build for arm64 (in both the TestProject and Extension Target Build Settings)

Thanks for the suggestion @paulb777. I think we'll just drop iOS 10 support sooner than planned as I'm not expecting Apple to fix the issue in reasonable time.

I think we can close here as it's apparently not a Firebase issue.
