### ISSUE TITLE
Audit `isKeyWindow` iOS 15 SDK change for Auth

### ISSUE THREAD

**Issue by ryanwilson** [firebase/firebase-ios-sdk#8376]
As mentioned in the [beta release notes](https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-15-beta-release-notes),  the `isKeyWindow` property changes functionality.

> `isKeyWindow` returns true if the window is key in its scene instead of the app.

We have one usage of `isKeyWindow` in Firebase:

https://github.com/firebase/firebase-ios-sdk/blob/bd64ba6f8a649ace7f6dfa8dd5fa846df1a2700e/FirebaseAuth/Sources/Utilities/FIRAuthDefaultUIDelegate.m#L87

This should be audited to make sure it's still working as intended.

Thanks @steipete for [surfacing this on Twitter](https://twitter.com/steipete/status/1413743244769439746)!

**Comment by paulb777** [comment]
Bumping since Xcode 13 is now RC

**Comment by rosalyntan** [comment]
Verified with our test app on iOS 15 that this still works properly. There may be implications for multi-window apps, but closing this out for now and will keep an eye out for any reported issues regarding multi-window apps.
