### ISSUE TITLE
Source formatting for Swift

### ISSUE THREAD

**Issue by wilhuff** [firebase/firebase-ios-sdk#839]
`scripts/style.sh` is based on `clang-format` and we have it set up to format our Objective-C, Objective-C++, and C++ code. Extending this to format `.swift` files broke them horribly.

[SwiftFormat](https://github.com/nicklockwood/SwiftFormat) looks promising. We should integrate it into `scripts/style.sh` for swift sources.

**Comment by ryanwilson** [comment]
There's a bunch of work being done right now on [`libSyntax`](https://github.com/apple/swift/tree/master/lib/Syntax) that we should be able to take advantage of, too.
