### ISSUE TITLE
Update abseil and BoringSSL-GRPC dependency

### ISSUE THREAD

**Issue by robm92** [firebase/firebase-ios-sdk#8391]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13 beta 3
  * Firebase SDK version: 8.3.1
  * Installation method: `Swift Package Manager`
  * Firebase Component: Crashlytics

### [REQUIRED] Step 2: Describe the problem

In Xcode 13 beta 3 there are 21 warnings related to 'invalid exclude' in the below dependencies.
These have since been fixed but the package versions are not updated in Firebase SPM.

Dependencies:
abseil - https://github.com/firebase/abseil-cpp-SwiftPM/releases/tag/0.20200225.4
BoringSSL-GRPC - https://github.com/firebase/boringSSL-SwiftPM/releases/tag/0.7.2

**Comment by schmidt-sebastian** [comment]
We are working on validating this update.

**Comment by schmidt-sebastian** [comment]
@robm92 Can you share your build settings? I am not getting any build warnings with the current release on XCode 13 Beta 3. This is also what another engineer on my team told me. I need to verify that the warnings go away when we perform the update.

**Comment by robm92** [comment]
@schmidt-sebastian I've tried removing and re-adding the 8.3.1 swift package but the versions of abseil and GRPC are still 0.20200225.3 and 0.7.1 respectively.
What build settings can I provide you? Is there an export?

**Comment by paulb777** [comment]
@robm92 The 0.20200225.4 and 0.7.2 versions that you first referenced fixed several warnings.  Does `Update to Latest Package Versions` update to those?

**Comment by schmidt-sebastian** [comment]
We have not yet updated any dependencies. Can you share a screenshot of your warnings? I will try to see how I can get my XCode build to spit out the same warnings.

**Comment by robm92** [comment]
<img width="765" alt="Screenshot 2021-07-20 at 17 52 22" src="https://user-images.githubusercontent.com/11296167/126364241-8931d906-ca60-4f15-8219-af56acfda396.png">
@schmidt-sebastian

**Comment by robm92** [comment]
> @robm92 The 0.20200225.4 and 0.7.2 versions that you first referenced fixed several warnings. Does `Update to Latest Package Versions` update to those?

Aha! that did it!
