### ISSUE TITLE
Firebase iOS 8.3.1 is missing Firebase.zip

### ISSUE THREAD

**Issue by MarcoEidinger** [firebase/firebase-ios-sdk#8395]
### [REQUIRED] Step 1: Describe your environment

  * Firebase SDK version: 8.3.1
  * Installation method: `Zip file`

#### Steps to reproduce:

GitHub release Firebase iOS 8.3.1 is missing Firebase.zip. See https://github.com/firebase/firebase-ios-sdk/releases/tag/8.3.1

**Comment by paulb777** [comment]
8.3.1 was a Swift Package Manager only release since the only change was SPM specific tagging.

See https://firebase.google.com/support/release-notes/ios
