### ISSUE TITLE
Can not receive push notification when change APNS to FCM

### ISSUE THREAD

**Issue by nguyentuanvu90** [firebase/firebase-ios-sdk#842]
When my application using APNS in version 1.0 and in version 2.0 I change to FCM.
I update application without delete version 1.0, my application can not receive push notification.
But I install after deleted version 1.0 my application can receive notification.

**Comment by morganchen12** [comment]
Hey, there's not enough information in this ticket to debug your issue. Please answer the following questions, then reopen the ticket.

- How are you sending notifications? Are you targeting a bundle ID through Firebase Console? If so, make sure your bundle ID didn't change between app versions
- Is your app's team ID different from the app ID prefix?

**Comment by nguyentuanvu90** [comment]
- I'm sending notifications by Firebase Console.
- I config bundle ID in Firebase Console. And my application bundle ID didn't change between app versions
- My app's team ID same app ID prefix.
- When I deleted old version and install new version my app can receive notification. But I update app without deleted app, my app can not receive notification.
- In old app version I using APNS to push notification. And I change to use FCM in new version.

**Comment by morganchen12** [comment]
@nguyentuanvu90 can you share the code you're using to integrate FCM? Most importantly, how are you handling FCM token refreshes?

Also, what versions of the Firebase SDKs are you using?

**Comment by Lunziyuan** [comment]
The same with you.Have you solved this problem? @nguyentuanvu90

**Comment by Lunziyuan** [comment]
I  solved it by this! [https://github.com/invertase/react-native-firebase/issues/1972](url)
