### ISSUE TITLE
CORS "Origin" header is null

### ISSUE THREAD

**Issue by html-rulez-d00d** [firebase/firebase-ios-sdk#8421]
### Step 0: Are you in the right place?

  I was directed here by the FlutterFire support. Original issue listed here: https://github.com/FirebaseExtended/flutterfire/issues/6663

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.2
  * Firebase SDK version: 28.1.0 (set via Flutter Firebase Core)
  * Installation method: `CocoaPods` (Flutter)
  * Firebase Component: firebase_core: 1.3.0 & firebase_messaging: 10.0.2

#### Steps to reproduce:

There is concern on the use of the Origin header for the Firebase installation process. Our group had a penetration test run on our project's code and they flagged this issue as moderate. From the security teams findings, it appears the POST request for installation uses an "Origin" header with a value of null. Their expectation is that either CORS should be disabled if same-origin policy is not blocking or to provide the Origin's value with the proper domain (ex: `Origin: https://firebaseinstallations.googleapis.com`).

1. Run any Flutter project with Firebase Core and Firebase Messaging as dependencies. Note: this issue was witnessed on an iOS device (with our Flutter iOS app).
2. Capture the server request and response.

#### Relevant Code:

https://github.com/firebase/firebase-ios-sdk/blob/04ab074265633049d5518866515e3bd7fc0de246/FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsAPIService.m#L133-L160

**Comment by maksymmalyhin** [comment]
@html-rulez-d00d Thank you for the report. 

I tried to reproduce the issue on a [quickstart app](https://github.com/firebase/quickstart-ios/tree/master/installations). I cannot see the header `Origin` to be set for Firebase Installations requests. There is a header `vary: Origin` in the response, but it doesn't look related.

In Firebase SDKs we don't set the header `Origin` explicitly and it doesn't looks like [NSURLSession](https://developer.apple.com/documentation/foundation/nsurlsession) adds it silently. 

Based on above it looks like the issue you described either is introduced by Flutter or is an issue of the penetration test methodology used.

I'm closing the Firebase SDK issue so far, but feel free to reopen it if you find a way to reproduce it or you find out additional details.

**Comment by html-rulez-d00d** [comment]
Thank you @maksymmalyhin for a quick response!

I am forwarding your information to my security contact to see if there is anything else that can be done to narrow down the root cause. I do recall him saying it was odd that the Origin header value was set to "null". It would almost signify it being added unintentionally but I'm not sure where else this action could occur. I would also like to clarify I am not an iOS developer (Flutter/dart) so this makes things even more complicated form my angle.
