### ISSUE TITLE
Card view stuck at run time, in debug works perfectly

### ISSUE THREAD

**Issue by MakwanaMaulik** [firebase/firebase-ios-sdk#8427]
I have check all simulators and many devices, but when the device/ simulator is on debug then it works perfectly, but in run time it stuck,

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-07-23 at 12 08 27](https://user-images.githubusercontent.com/74096570/126745909-9ddf3c50-25f5-4381-9594-cf8732b51ff7.png)

Xcode 12.3
iOS 13+

**Comment by rizafran** [comment]
Thanks for reporting, @MakwanaMaulik. Can you provide more details like the Firebase product you're using, SDK version, installation method or detailed steps to reproduce it? Thanks.

**Comment by MakwanaMaulik** [comment]
pod 'Firebase/InAppMessaging' version 6.34.0
install using a pod, 

steps to reproduce

-add campaign in firebase dashboard with any button event like login event
-run the app in device or simulator iOS 13+
-when an event fires and your device/simulator is in debugging mode it will open perfectly and work perfecly
-now disconnect the device/simulator from debugging and try to get a new event with the login event, now as we are not in debugging mode the app will be stuck.

**Comment by MakwanaMaulik** [comment]
> Thanks for reporting, @MakwanaMaulik. Can you provide more details like the Firebase product you're using, SDK version, installation method or detailed steps to reproduce it? Thanks.

pod 'Firebase/InAppMessaging' version 6.34.0
install using a pod, 

steps to reproduce

-add campaign in firebase dashboard with any button event like login event
-run the app in device or simulator iOS 13+
-when an event fires and your device/simulator is in debugging mode it will open perfectly and work perfectly
-now disconnect the device/simulator from debugging and try to get a new event with the login event, now as we are not in debugging mode the app will be stuck.

**Comment by paulb777** [comment]
Please try with a more recent version of Firebase. The most recent release is 8.4.0.

**Comment by MakwanaMaulik** [comment]
> Please try with a more recent version of Firebase. The most recent release is 8.4.0.

I have updated all pods now my version is 8.4.0 still facing the same issue.

**Comment by MakwanaMaulik** [comment]
can anyone solve this problem?

**Comment by MakwanaMaulik** [comment]
it's been 10 days now, is there anyone who can solve this problem?

**Comment by eldhosembabu** [comment]
Hi @MakwanaMaulik ,

Could you please try to reproduce this in our [quick-start FIAM app](https://github.com/firebase/quickstart-ios/tree/master/inappmessaging)?

**Comment by MakwanaMaulik** [comment]
> Hi @MakwanaMaulik ,
> 
> Could you please try to reproduce this in our [quick-start FIAM app](https://github.com/firebase/quickstart-ios/tree/master/inappmessaging)?

the new demo is working perfectly I have a problem with my project. so what can be a problem? I am doing the same step as the demo project.

**Comment by morganchen12** [comment]
@MakwanaMaulik unfortunately we can't tell you what's going on without debugging your project.

**Comment by maulikm235** [comment]
> @MakwanaMaulik unfortunately we can't tell you what's going on without debugging your project.

tell me in which way you prefer to debug?

**Comment by morganchen12** [comment]
It's unlikely given our current staffing that a team member will have time for 1:1 debugging (although it's not impossible). If you [set the logger level](https://firebase.google.com/docs/reference/ios/firebasecore/api/reference/Classes/FIRConfiguration#/c:objc(cs)FIRConfiguration(im)setLoggerLevel:) to Debug and share the logs here, we may be able to help.

**Comment by maulikm235** [comment]
> It's unlikely given our current staffing that a team member will have time for 1:1 debugging (although it's not impossible). If you [set the logger level](https://firebase.google.com/docs/reference/ios/firebasecore/api/reference/Classes/FIRConfiguration#/c:objc(cs)FIRConfiguration(im)setLoggerLevel:) to Debug and share the logs here, we may be able to help.

[log.txt](https://github.com/firebase/firebase-ios-sdk/files/6973433/log.txt)
please check this log file and let me know what is the issue.

**Comment by morganchen12** [comment]
I don't see anything wrong with the logs. @chliangGoogle do you know what could be going on here?

**Comment by eldhosembabu** [comment]
Are you using other firebase SDK(s) other than FIAM in your project? If yes could you please try removing the other SDK(s) from the project and see whether the issue really happens with the FIAM SDK or not. From the log, we can see that you are using other SDK(s) like Firebase/Performance etc. Let us know your findings

**Comment by maulikm235** [comment]
> Are you using other firebase SDK(s) other than FIAM in your project? If yes could you please try removing the other SDK(s) from the project and see whether the issue really happens with the FIAM SDK or not. From the log, we can see that you are using other SDK(s) like Firebase/Performance etc. Let us know your findings

I had tried to remove other pod and try to add all pod in the demo project, but demo project works and the main project still have issues. can you please check what is issue with FIAM SDK?

**Comment by maulikm235** [comment]
is anyone there who can check this issue?

**Comment by paulb777** [comment]
@maulikm235 As discussed above, please share a reproducible example of the issue.  Alternatively, you could try to binary search the differences between the working quickstart and your non-working example.

**Comment by maulikm235** [comment]
the issue is not solved yet.

**Comment by chliangGoogle** [comment]
@maulikm235 The debugLog looks normal to me. Can you double check how you call the API to see if you ever assign a different thread calling display the UI and not coming back to main thread in call back function? This is usually causing UI freeze.

**Comment by maulikm235** [comment]
as i mentioned before, it stuck at run time only, when i try to run in debug mode then it will work perfectly. so how can i give you log for run time issue? also all is managed from SDK. if there is a thread issue then it is from SDK side because i am not handling that thread. please check issue from SDK side.

**Comment by maulikm235** [comment]
> Right but did you call FIAM API in another thread in your app? Can you share with us a piece of sample code how you call it

### **Pod files**

```
pod 'Firebase'
pod 'Firebase/Analytics'
pod 'Firebase/InAppMessaging'
pod 'Firebase/DynamicLinks'
pod 'Firebase/Crashlytics'
pod 'Firebase/Performance'
pod 'Firebase/RemoteConfig'
```

### **Import Firebase**

```
@_exported import Firebase
@_exported import FirebaseAnalytics
@_exported import FirebaseDynamicLinks
```

### **Appdelegate**

```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {        
	FirebaseConfiguration.shared.setLoggerLevel(.debug)
    FirebaseApp.configure()
    return true
}
```

### **Viewcontroller**

```
@IBAction func btnAddItem(_ sender: UIButton) {
Analytics.logEvent(AnalyticsEventAddToCart, parameters: [
                        AnalyticsParameterCurrency: displayCurrncySymbol,
                        AnalyticsParameterItemCategory: cell.arraySubItems[row].categoryId,
                        AnalyticsParameterItemID: cell.arraySubItems[row].id,
                        AnalyticsParameterItemLocationID: "\(GLocation.shared.cordinate.latitude),\(GLocation.shared.cordinate.longitude)",
                        AnalyticsParameterItemName: cell.arraySubItems[row].title,
                        AnalyticsParameterPrice: cell.arraySubItems[row].price,
                        AnalyticsParameterQuantity: cell.arraySubItems[row].itemCount ?? 0,
                        AnalyticsParameterValue: cell.arraySubItems[row].status
                        ])
}
```

**Please check and let me know where is the issue? also if FIAM not using code in the main thread then it is an SDK bug, it needs to be solved, this issue is for a long time now.**

**Comment by maulikm235** [comment]
did you find the issue?

**Comment by maulikm235** [comment]
waiting for SDK issue solution from your side.

**Comment by maulikm235** [comment]
I didn't hear for long time

> Right but did you call FIAM API in another thread in your app? Can you share with us a piece of sample code how you call it

**Comment by maulikm235** [comment]
> @maulikm235 Looks like what I was worried is not the case for FIAM, so I agree with the comment [above](https://github.com/firebase/firebase-ios-sdk/issues/8427#issuecomment-897884711) that if you can reproduce in quickstart that would be helpful.

As I mentioned before the issue is happening in real projects, not in demo.

**Comment by morganchen12** [comment]
@maulikm235 can you isolate the cause of the issue in your project or create a project that repros the issue? There's nothing in the code you shared that could affect the views of your app.

**Comment by maulikm235** [comment]
> @maulikm235 can you isolate the cause of the issue in your project or create a project that repros the issue? There's nothing in the code you shared that could affect the views of your app.

if there is nothing wrong in code, then it should work, as I do not handle any view from firebase, so it should be done from your side, if SDK handles every view then it is SDK responsibility.
