### ISSUE TITLE
Weird logs display in Xcode console after including Google Sign In as a dependency

### ISSUE THREAD

**Issue by konekoya** [firebase/firebase-ios-sdk#8446]
### Step 1: Describe your environment

  * Xcode version: 12.5.1 (12E507)
  * Firebase SDK version: 6.0.1
  * Installation method: `CocoaPods`
  * Firebase Component: GoogleSignIn (Auth, Core, Database, Firestore, Messaging, Storage, etc)

### Step 2: Describe the problem

Weird logs are displayed in Xcode console:

> objc[4856]: Class CSAudioFileManager is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SpeakerRecognition.framework/SpeakerRecognition (0x13c10c288) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreSpeech.framework/CoreSpeech (0x13aeeea08). One of the two will be used. Which one is undefined.
objc[4856]: Class CSNNVADEndpointAnalyzer is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SpeakerRecognition.framework/SpeakerRecognition (0x13c10ccd8) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreSpeech.framework/CoreSpeech (0x13aeeef58). One of the two will be used. Which one is undefined.
objc[4856]: Class CSAudioRecordContext is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SpeakerRecognition.framework/SpeakerRecognition (0x13c10cd28) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreSpeech.framework/CoreSpeech (0x13aeef048). One of the two will be used. Which one is undefined.
objc[4856]: Class CSSelectiveChannelAudioFileWriter is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SpeakerRecognition.framework/SpeakerRecognition (0x13c10cf08) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreSpeech.framework/CoreSpeech (0x13aeef228). One of the two will be used. Which one is undefined.
objc[4856]: Class CSPlainAudioFileWriter is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SpeakerRecognition.framework/SpeakerRecognition (0x13c10c1e8) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreSpeech.framework/CoreSpeech (0x13aeef958). One of the two will be used. Which one is undefined.
objc[4856]: Class CSRemoteRecordClient is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SpeakerRecognition.framework/SpeakerRecognition (0x13c10c788) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreSpeech.framework/CoreSpeech (0x13aef0a38). One of the two will be used. Which one is undefined.
objc[4856]: Class CSServerEndpointFeatures is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SpeakerRecognition.framework/SpeakerRecognition (0x13c10ca08) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreSpeech.framework/CoreSpeech (0x13aef10c8). One of the two will be used. Which one is undefined.

#### Steps to reproduce:
1. Create a new iOS app with these settings:

![Screen shot 2021-07-28 at 4.10.10 pm image](https://i.imgur.com/twPDp1r.png)

2. Use CocoaPods to install Google Sign In as a dependency, see the following steps:

Add Cocoapods to the project
```
pod init
```

Includes `GoogleSignIn` in the `podfile`
```
pod 'GoogleSignIn', '~> 6.0'
```

And then run:
```
pod install
```
3. Build and run the App with a simulator (I'm using iPhone 12)
4. Warnings will display in the Xcode console

#### Relevant Code:
I have prepared a [Repo](https://github.com/konekoya/GoogleSignInWarnings) that can reproduce the described issue

**Comment by paulb777** [comment]
See https://stackoverflow.com/questions/62970821/xcode-12-beta-and-ios-14-weird-console-logs-objc5551-class-is-implement that might help.  Otherwise, if you're still stuck, please report to https://github.com/google/GoogleSignIn-iOS/issues which has it's GitHub issue channel now.
