### ISSUE TITLE
Unaligned pointer warning building MessagingUnit target

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#8448]
When building the MessagingUnit target with Xcode 13 beta 4 in Swift Package Manager:

`ld: warning: pointer not aligned at address 0x179466 (_fm_MessagingClientEventExtension_fields + 6 from /Users/paulbeusterien/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-dzxqfpowrkksnfdbrdsjzildavlw/Build/Products/Debug-iphonesimulator/FirebaseMessaging.o)`

The warning should be fixed or at least tested on device to make sure it does not cause runtime crashes on ARM hardware.

**Comment by maksymmalyhin** [comment]
Seems like the [proto code](https://github.com/firebase/firebase-ios-sdk/blob/3a5bdd881672f752b50d8111f11c7b617556687b/FirebaseMessaging/Sources/Protogen/nanopb/me.nanopb.c#L18) was generated for older nanopb version. Currently we install 2.30908.0 with SPM.

**Comment by maksymmalyhin** [comment]
never mind, I tried to generate with 2.30908.0 version from https://github.com/firebase/nanopb but there were no code changes.

**Comment by paulb777** [comment]
Fixed via missing defines in Package.swift in #8460
