### ISSUE TITLE
Insecure source code functions have been used in the binary

### ISSUE THREAD

**Issue by HariIDPal** [firebase/firebase-ios-sdk#8454]
Environment
Xcode version: 12.5
Firebase Pod version: 8.1.0
Firebase Component: FirebaseCrashlytics
Language: Swift

Problem
We are using the firebase for push notifications in our application.
Our penetration testing team have found out that some insecure source code functions are being used in the application(strlen, memcpy and malloc) which is found in the firebase library in the below functions:
strlen:
FIRCLSBinaryImage
FIRCLSDataParsing
FIRCLSDwarfUnwind
FIRCLSFile
FIRCLSInternalLogging
FIRCLSMachOBinary
FIRCLSUtility
FIRCLSMachO
FIRCLSReportAdapter
FIRCLSUtility
pb_decode.c

Could you remove these from the Firebase library in your upcoming release or if it is required, could you let us know why it is required?

**Comment by paulb777** [comment]
The answer at https://github.com/firebase/firebase-ios-sdk/issues/905#issuecomment-372387613 likely still applies

**Comment by morganchen12** [comment]
@HariIDPal can your team elaborate on where uses of these functions may be insecure?

**Comment by HariIDPal** [comment]
I will update more information.
