### ISSUE TITLE
com.google.firebase.crashlytics.ios.exception

### ISSUE THREAD

**Issue by xsgoing** [firebase/firebase-ios-sdk#8462]
0
MTAppProduction
FIRCLSProcess.c - 第 397 行
FIRCLSProcessRecordAllThreads + 397
1
MTAppProduction
FIRCLSProcess.c - 第 428 行
FIRCLSProcessRecordAllThreads + 428
2
MTAppProduction
FIRCLSHandler.m - 第 34 行
FIRCLSHandler + 34
3
MTAppProduction
FIRCLSException.mm - 第 218 行
__FIRCLSExceptionRecord_block_invoke + 218
4
libdispatch.dylib
_dispatch_client_callout + 20
5
libdispatch.dylib
_dispatch_lane_barrier_sync_invoke_and_complete + 60
6
MTAppProduction
FIRCLSException.mm - 第 225 行
FIRCLSExceptionRecord + 225
7
MTAppProduction
FIRCLSException.mm - 第 111 行
FIRCLSExceptionRecordNSException + 111
8
MTAppProduction
FIRCLSException.mm - 第 279 行
FIRCLSTerminateHandler() + 279
9
libc++abi.dylib
std::__terminate(void (*)()) + 20
10
libc++abi.dylib
__cxa_get_exception_ptr + 34
11
libc++abi.dylib
__cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) + 138
12
MTAppProduction
__cxa_throw + 348
13
libobjc.A.dylib
objc_exception_throw + 360
14
Foundation
+[NSUserDefaults(NSUserDefaults_NSURLExtras) _web_defaultsDidChange] + 202
15
TextInput
-[TIDocumentState(StateTransitions) documentStateAfterReplacingText:withText:] + 364
16
UIKitCore
-[UIKeyboardImpl setDocumentStateForAutocorrection:] + 188
17
UIKitCore
__82-[UIKeyboardImpl acceptAutocorrection:executionContextPassingTIKeyboardCandidate:]_block_invoke_2 + 48
18
UIKitCore
-[UIKeyboardImpl acceptAutocorrection:executionContextPassingTIKeyboardCandidate:] + 824
19
UIKitCore
-[UIKeyboardImpl acceptAutocorrectionForWordTerminator:executionContextPassingTIKeyboardCandidate:] + 240
20
UIKitCore
__56-[UIKeyboardImpl acceptAutocorrectionForWordTerminator:]_block_invoke + 148
21
UIKitCore
-[UIKeyboardTaskEntry execute:] + 188
22
UIKitCore
-[UIKeyboardTaskQueue continueExecutionOnMainThread] + 336
23
UIKitCore
-[UIKeyboardTaskQueue performTaskOnMainThread:waitUntilDone:] + 284
24
UIKitCore
-[UIKeyboardImpl acceptAutocorrectionForWordTerminator:] + 196
25
UIKitCore
-[UIKeyboardImpl acceptAutocorrection] + 344
26
UIKitCore
__38-[UIKeyboardImpl acceptAutocorrection]_block_invoke + 36
27
UIKitCore
-[UIKeyboardTaskEntry execute:] + 188
28
UIKitCore
-[UIKeyboardTaskQueue continueExecutionOnMainThread] + 336
29
UIKitCore
-[UIKeyboardImpl acceptAutocorrection] + 752
30
UIKitCore
-[UIKeyboardImpl setDelegate:force:] + 2252
31
UIKitCore
-[UIInputResponderController _reloadInputViewsForKeyWindowSceneResponder:] + 2040
32
UIKitCore
-[UIInputResponderController _reloadInputViewsForResponder:] + 164
33
UIKitCore
-[UIResponder(UIResponderInputViewAdditions) reloadInputViews] + 132
34
WebKit
-[WKContentView(WKInteraction) _hideKeyboard] + 116
35
WebKit
-[WKContentViewAccessibility _hideKeyboard]
36
WebKit
-[WKContentView(WKInteraction) _elementDidBlur] + 296
37
WebKit
WebKit::WebPageProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&) + 56536
38
WebKit
IPC::MessageReceiverMap::dispatchMessage(IPC::Connection&, IPC::Decoder&) + 124
39
WebKit
WebKit::WebProcessProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&) + 40
40
WebKit
IPC::Connection::dispatchMessage(std::__1::unique_ptr<IPC::Decoder, std::__1::default_delete<IPC::Decoder> >) + 656
41
WebKit
IPC::Connection::dispatchIncomingMessages() + 460
42
JavaScriptCore
WTF::RunLoop::performWork() + 484
43
JavaScriptCore
WTF::RunLoop::performWork(void*) + 36
44
CoreFoundation
__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
45
CoreFoundation
__CFRunLoopDoSource0 + 208
46
CoreFoundation
__CFRunLoopDoSources0 + 268
47
CoreFoundation
__CFRunLoopRun + 820
48
CoreFoundation
CFRunLoopRunSpecific + 600
49
GraphicsServices
GSEventRunModal + 164
50
UIKitCore
-[UIApplication _run] + 1072
51
UIKitCore
UIApplicationMain + 168
52
MTAppProduction
main.m - 第 14 行
main + 14
53
libdyld.dylib
start + 4

**Comment by rizafran** [comment]
Hi @xsgoing, please provide the information indicated in the issue template like the SDK version used, installation method, and detailed steps to reproduce the issue. Thanks.
