### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_MLKModelDownloadConditions

### ISSUE THREAD

**Issue by BesartH** [firebase/firebase-ios-sdk#8475]
I have an issue with my app. When I run it on a real device or on a simulator it, works fine, but when I try to archive it the error below is thrown:

> Undefined symbols for architecture armv7:
> "OBJC_CLASS$_MLKModelDownloadConditions", referenced from:
> objc-class-ref in CustomFirebaseTranslator.o
> "OBJC_CLASS$_MLKTranslator", referenced from:
> objc-class-ref in CustomFirebaseTranslator.o
> "OBJC_CLASS$_MLKTranslatorOptions", referenced from:
> objc-class-ref in CustomFirebaseTranslator.o
> ld: symbol(s) not found for architecture armv7
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have integrated MLKitTranslate using pod

> pod 'GoogleMLKit/Translate'
> pod 'Firebase/Core'

I have tried 'pod deintegrate' and then 'pod install', but didn't solve the issue.

**Comment by morganchen12** [comment]
Hey Besart, the ML Kit feature you're referencing is no longer part of Firebase so this is no longer the right place to seek support for it.

With that in mind, the issue you're likely running into is the binary disrtributions for ML Kit do not include an architecture slice for armv7. All [Apple devices after the iPhone 5s (including the 5s itself)](https://developer.apple.com/library/archive/documentation/DeviceInformation/Reference/iOSDeviceCompatibility/DeviceCompatibilityMatrix/DeviceCompatibilityMatrix.html) are capable of running arm64 apps, so you do not need to include an armv7 architecture slice in your archive unless you are targeting very old device versions.

From my limited knowledge ML Kit does not have plans to add armv7 support, so I'd recommend you remove armv7 from your archive builds.
