### ISSUE TITLE
Firebase Cloud Messaging guide for macOS

### ISSUE THREAD

**Issue by ARTWINPRO** [firebase/firebase-ios-sdk#8479]
* Firebase Component: Messaging 
 

Hello, dears maybe someone is has some simple work example how to integrate FCM for Mac OS app ?

**Comment by morganchen12** [comment]
Hey @ARTWINPRO, we're currently working on expanding our documentation and sample coverage to all Apple platforms (where applicable). In the meantime, the best reference for FCM for now is the sample app located [here](https://github.com/firebase/firebase-ios-sdk/tree/master/FirebaseMessaging/Apps/AdvancedSample).

**Comment by ARTWINPRO** [comment]
A lot of thanks. You was do amazing works guys! 🙏
