### ISSUE TITLE
Xcode12.2 use Carthage install Firebase crashlytics and build error

### ISSUE THREAD

**Issue by Bruce9487** [firebase/firebase-ios-sdk#8481]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version:  12.2
  * Firebase SDK version:  8.4.0
  * Installation method: Carthage
  * Firebase Component: 
  
![截圖 2021-07-29 16 56 01](https://user-images.githubusercontent.com/19691907/127965317-db506583-d14c-44d0-8947-582faf507d40.png)

And I want to use Crashlytics in Xcode12, What's wrong with my issue?

#### Steps to reproduce:

What happened? How can we make the problem occur?
Build the APP and got an error
```
ld: in /Users/xx/Desktop/xx/xx/xx/xx/xx/xx/xx/xx/Carthage/Build/iOS/FirebaseRemoteConfig.framework/FirebaseRemoteConfig(FIRConfigValue.o), building for iOS Simulator, but linking in object file built for Mac Catalyst, file '/Users/xx/xx/xx/xx/xx/xx/xx/xx/xx/xx/Carthage/Build/iOS/FirebaseRemoteConfig.framework/FirebaseRemoteConfig' for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

And I use these commands to install frameworks.<br>
> carthage update --platform iOS --no-use-binaries --use-xcframeworks<br>
or <br>
> carthage update --platform iOS --no-use-binaries<br>

**Comment by gronico** [comment]
And the error is?

**Comment by paulb777** [comment]
`--no-use-binaries` might be an issue since Firebase only supports binaries.

Duplicate question at https://stackoverflow.com/questions/68630216/xcode12-2-use-carthage-install-firebase-crashlytics-and-build-error
