### ISSUE TITLE
Invalid image URL crashes the client app

### ISSUE THREAD

**Issue by yakovmanshin** [firebase/firebase-ios-sdk#8482]
### Step 1: Describe your environment

  * Xcode version: 12.5.1
  * Firebase SDK version: 8.4.0
  * Installation method: CocoaPods
  * Firebase Component: IAM

#### Steps to reproduce:

1. Compose a new in-app message in the Firebase Console, and leave a trailing whitespace in the image URL;
2. Make the message appear in the app (send a test message or publish the campaign).

#### Why the crash happens:

1. In `FIRIAMFetchResponseParser`’s `convertToMessageDefinitionWithMessageDict:`, [`[NSURL URLWithString:imageURLStr]`](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseInAppMessaging/Sources/Data/FIRIAMFetchResponseParser.m#L290) returns `nil` because of the whitespace;
2. The `msgData` object is [created with `nil` in `imageURL`](https://github.com/firebase/firebase-ios-sdk/blob/26b561aba60422f99e90f64ba4e9e6fcb9e349d7/FirebaseInAppMessaging/Sources/Data/FIRIAMFetchResponseParser.m#L338);
3. `nil` URLs [produce no image data](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseInAppMessaging/Sources/Data/FIRIAMMessageContentDataWithImageURL.m#L98);
4. The `imageData` parameter in `FIRInAppMessagingDisplayMessage` initializer is not `nullable`, so the entire `displayMessage` object [becomes `nil`](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayExecutor.m#L666);
5. `FIRInAppMessagingDisplay`’s `displayMessage:displayDelegate:` method assumes `messageForDisplay` is not optional, so when a `nil` is received in the Swift runtime, a crash occurs.

### Next Steps

In addition to the check introduced in the associated pull request, a new method could be added to `FIRIAMFetchResponseParser` to sanitize URL strings by handling common errors, such as whitespaces.

Filed in #8485. Implemented in #8486.

### Images

<img width="437" src="https://user-images.githubusercontent.com/4648742/127999838-74992be0-4021-4c3c-85f2-4acfce86b92d.png">
<img width="842" src="https://user-images.githubusercontent.com/4648742/127999930-50236d7b-65bb-4d38-acc0-76b27f313ee3.png">
<img width="857" src="https://user-images.githubusercontent.com/4648742/127999995-25b144d4-24ee-4ff9-9ab7-317161acfbbc.png">
<img width="328" src="https://user-images.githubusercontent.com/4648742/127999967-c6ec353c-81f3-46da-a767-1afbcd228d68.png">

### Stack Trace

```
Crashed: com.apple.main-thread
0  libswiftCore.dylib             0x1b68d45b8 swift_getObjectType + 60
1  <REDACTED>                     0x10358a344 closure #1 in <REDACTED>.displayMessage(_:displayDelegate:) + 4390806340 (<compiler-generated>:4390806340)
2  <REDACTED>                     0x1021a89b0 thunk for @escaping @callee_guaranteed () -> () + 4369959344 (<compiler-generated>:4369959344)
3  libdispatch.dylib              0x1a8de69a8 _dispatch_call_block_and_release + 24
4  libdispatch.dylib              0x1a8de7524 _dispatch_client_callout + 16
5  libdispatch.dylib              0x1a8d995b4 _dispatch_main_queue_callback_4CF$VARIANT$mp + 904
6  CoreFoundation                 0x1a909f6bc __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
7  CoreFoundation                 0x1a909a590 __CFRunLoopRun + 1724
8  CoreFoundation                 0x1a9099ba8 CFRunLoopRunSpecific + 424
9  GraphicsServices               0x1b3209344 GSEventRunModal + 160
10 UIKitCore                      0x1ad1d53e4 UIApplicationMain + 1932
11 <REDACTED>                     0x10215cb2c main + 15 (<REDACTED>.swift:15)
12 libdyld.dylib                  0x1a8f218f0 start + 4
```

**Comment by morganchen12** [comment]
It'd be nice as well if we can check for common errors when the IAM is being created in console.
