### ISSUE TITLE
Firebase performance crashes with objc_msgSend in method updateTraceWithCurrentSession of class FPRNetworkTrace

### ISSUE THREAD

**Issue by AbhishekBB** [firebase/firebase-ios-sdk#8495]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: _12.4____
  * Firebase SDK version: _8.4.0____
  * Installation method: `CocoaPods`
  * Firebase Component: _Performance____ 

### [REQUIRED] Step 2: Describe the problem

We are unable to reproduce this, We are seeing this crash in our production app in crashlytics.

<img width="1276" alt="Screenshot 2021-08-05 at 5 11 02 PM" src="https://user-images.githubusercontent.com/15157308/128344167-485e2cb2-ef17-4bb3-b2c8-b8c0951fb307.png">

What happened? How can we make the problem occur?
We are unable to reproduce this.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

NO

**Comment by paulb777** [comment]
This looks like one of the traces reported in #8321

**Comment by AbhishekBB** [comment]
Can we downgrade to any firebase version to avoid this crash?

**Comment by luan-sala** [comment]
+1

I have the same crash.

![image](https://user-images.githubusercontent.com/38911319/128401069-ac01a424-590b-4276-8d17-d2b8355337b3.png)

<details>
<summary>2 other threads</summary>

![image](https://user-images.githubusercontent.com/38911319/128401178-06fbeb68-9879-4ef4-bf35-e363fe08cba9.png)

![image](https://user-images.githubusercontent.com/38911319/128401208-da14dab9-be3b-4478-8995-ac2a91b2e44c.png)

</details>

**Comment by jposuna** [comment]
Thanks for reporting this! We are having some trouble reproducing the issue, but we have a theory about what could be going wrong and will submit a fix as soon as possible.

**Comment by jposuna** [comment]
We just submitted a PR which should make it to the next iOS SDK release (scheduled for August 17th). Please feel free to reopen if that version still has this error.

**Comment by caffieneToCode** [comment]
We too are getting these crashes, is Firebase version 8.6.0 released?
<img width="1256" alt="Screenshot 2021-08-13 at 12 01 05 PM" src="https://user-images.githubusercontent.com/11851138/129314821-a42b1a77-0224-4e09-9090-e96510535792.png">
