### ISSUE TITLE
App Check with Swift Package Manager

### ISSUE THREAD

**Issue by Tapestes** [firebase/firebase-ios-sdk#8504]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5.1
  * Firebase SDK version: 8.5.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: App Check

### [REQUIRED] Step 2: Describe the problem
I'm getting "Cannot find type 'AppCheckProviderFactory' in scope".  First, I tried importing FirebaseAppCheck, but that wasn't recognized.  I can import Firebase fine (and I'm using that in my app already), but that doesn't seem get me  hooked into App Check.   When I look in the downloaded Firebase package, I see FirebaseAppCheck.  I reset my package cache and cleaned the build folder, neither of which resolved the issue.  Is App Check intended to work with SPM, or should I be importing the framework manually?  Or, (probably more likely), am I missing something obvious here? 

Following code returns two errors: Cannot find type 'AppCheckProviderFactory' in scope & Cannot find type 'AppCheckProvider' in scope.

```
import Firebase

class SimpleAppCheckProviderFactory: NSObject, AppCheckProviderFactory {
  func createProvider(with app: FirebaseApp) -> AppCheckProvider? {
    return AppAttestProvider(app: app)
  }
}

```

If anyone can point in the right direction, I'd greatly appreciate it.

**Comment by rizafran** [comment]
Thanks for reporting, @Tapestes. I've tried to install the FirebaseAppCheck via SPM, but I wasn't able to get the same error. If you haven't done so, you may add the FirebaseAppCheck in your target's general pane > Build Phases tab > Link Binary With Libraries (see the sample screenshot).

<img width="1112" alt="Screen Shot 2021-08-07 at 12 55 02 AM" src="https://user-images.githubusercontent.com/56452638/128545494-26fbd9e5-7411-4127-9ac6-8655dab38234.png">

**Comment by Tapestes** [comment]
@rizafran, that was the magic.  Appreciate it.
