### ISSUE TITLE
Jailbroken flag is not working in firebase sdk

### ISSUE THREAD

**Issue by jaderYang** [firebase/firebase-ios-sdk#8509]
### Step 0: Are you in the right place?

  * I found that the firebase SDK cannot detect the jailbroken device correctly

### [REQUIRED] Step 1: Describe your environment

  * Xcode version:  12.5
  * Firebase SDK version: 7.8.0
  * Installation method: CocoaPods 
  * Firebase Component: Crashlytics, Analytics

#### Steps to reproduce:

I saw a lot of crashes on the crash dashboard of firebase that are definitely caused by the jailbroken machine, but the Jailbroken flag of firebase is false, and the value of operating_system.modification_state in the data in BigQuery is also UNMODIFIED.

So I think there may be a problem with the code.

#### Relevant Code:
Here is the code in our repo.
```
fileprivate lazy var bannerPageControl: UIPageControl = {
        let control = UIPageControl()
        control.translatesAutoresizingMaskIntoConstraints = false
        control.numberOfPages = 3
        control.currentPage = 0
        control.currentPageIndicatorTintColor = UIColor.init(hexString: "#458500")
        control.pageIndicatorTintColor = UIColor.init(hexString: "#e0e0e0")
        if #available(iOS 14.0, *) {
            control.allowsContinuousInteraction = false
        }
        return control
    }()
```

And the image shows the crash stacks information.
![image](https://user-images.githubusercontent.com/13029870/128653114-275e90ef-acbc-45f5-8c0f-dddb5d14034b.png)

**Comment by rizafran** [comment]
Thanks for reporting this issue, @jaderYang. To isolate it, is it possible for you to try reproducing the issue using the [latest SDK version](https://firebase.google.com/support/release-notes/ios#version_850_-_august_03_2021) (as this contains bug fixes and latest features), and try another test crash particularly on the jailbroken device?

**Comment by jaderYang** [comment]
@rizafran  Thanks for the quick response.  I will update the version on my end.  But I can't try a test because the crashes happened on the release version and I don't have any Jailbroken device in my hand.  
Have you made any code updates to the jailbreak detection in the latest code? Or do I need to do something in my repo to help your SDK do the detection?

**Comment by rizafran** [comment]
Hi @jaderYang, let me check this with the Crashlytics team, and will provide an update. Thanks.

**Comment by rizafran** [comment]
Hi @jaderYang, as discussed, please file a ticket to [Firebase Support](https://firebase.google.com/support) in order to investigate your Crashlytics info and see what's causing the issue. Thanks.

**Comment by jaderYang** [comment]
@rizafran Ok will do.   Thanks again.
