### ISSUE TITLE
Carthage instruction for Apple Silicon are missing. Page not found error. 

### ISSUE THREAD

**Issue by alok-dks** [firebase/firebase-ios-sdk#8514]
### Step 0: Are you in the right place?
Yes

### [REQUIRED] Step 1: Describe your environment

  * Github

#### Steps to reproduce:

Page not found on  link https://github.com/firebase/firebase-ios-sdk/blob/master/AppleSilicon.md 
Which is in Carthage section.

<img width="882" alt="Screen Shot 2021-08-10 at 6 12 15 AM" src="https://user-images.githubusercontent.com/70213416/128849525-b33c6730-0ca7-4253-bf88-0dc2408fb314.png">

#### Relevant Code:

```
none
```

**Comment by paulb777** [comment]
@alok-dks Thanks for the report! When we eliminated the need for a special distribution for M1 Mac development, we forgot to remove this reference. It's fixed now via #8515.
