### ISSUE TITLE
GoogleAppMeasurement code signature is invalid when running iPhone app on M1 Mac

### ISSUE THREAD

**Issue by KyLeggiero** [firebase/firebase-ios-sdk#8517]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 12.4 (12D4e)
  * Firebase SDK version: 7.11.1
  * Installation method: `Swift Package Manager`
  * Firebase Component: Crashlytics, GoogleAppMeasurement

#### Steps to reproduce:

0. Using a Mac with an M1 SoC
1. Create an Xcode project which targets iPhone
2. Include the Firebase package in that Xcode project
3. Include `FirebaseAnalytics` and `FirebaseCrashlytics` in the iPhone Target
4. Select the iPhone Target as the target and "My Mac (Designed for iPhone)" as the run destination
5. Run the project

##### Expected result:

6. The app runs in an iPhone-size window on the Mac

##### Actual result:

6. The following error dialog appears:

![A screenshot of the dialog.](https://i.imgur.com/uR2G6OB.png)

The dialog above reads:

> APP NAME Needs To Be Updated. The developer of this app needs to update it to work with this version of macOS.
Failed to verify code signature of /var/db/appinstalld/Library/Caches/com.apple.mobile.installd.staging/temp.7n4Kth/extracted/APP NAME.app/Frameworks/GoogleAppMeasurement.framework : 0xe8008029 (The code signature version is no longer supported.)

#### Relevant Code:

No code required

**Comment by paulb777** [comment]
Does updating to Firebase 8.x help?

**Comment by paulb777** [comment]
Also Analytics does not yet support macOS or Catalyst targets. See #4563 and #1732.

**Comment by KyLeggiero** [comment]
@paulb777 I can try updating Firebase on Monday.

And, this is neither a macOS nor Catalyst target; this is an iOS target running on an M1 Mac.

**Comment by paulb777** [comment]
Hmm, Catalyst is running an iOS target on a Mac -  FirebaseAnalytics is only supported for iOS Simulators and iOS Devices.

**Comment by KyLeggiero** [comment]
@paulb777 

Mac Catalyst is using UIKit to compile and run native macOS apps.

I'm talking about taking iOS apps, compiled for iOS, doing literally nothing different with them, and running them on macOS. This is only possible on M1 Macs because they have the same exact processor architecture as iPhones and iPads.
