### ISSUE TITLE
Unable to link anonymous user with Apple account

### ISSUE THREAD

**Issue by rudsberg** [firebase/firebase-ios-sdk#8520]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5.1
  * Firebase SDK version: 8.5.0
  * Installation method: Swift Package Manager
  * Firebase Component: Auth

### [REQUIRED] Step 2: Describe the problem

I am having problem to link an anonymous account with "Sign in with Apple". I have read this issue [#4434](https://github.com/firebase/firebase-ios-sdk/issues/4434) and tried the described flow mentioned [here](https://github.com/firebase/firebase-ios-sdk/issues/4434#issuecomment-564776016) but the error object received after failing to link does not contain `error.userInfo[FIRAuthErrorUserInfoUpdatedCredentialKey]` which makes it impossible to proceed and sign in the user. For me, the error object only contains the following: 

`["NSLocalizedDescription": Duplicate credential received. Please try again with a new credential., "FIRAuthErrorUserInfoNameKey": ERROR_MISSING_OR_INVALID_NONCE]`

#### Steps to reproduce:

Sign in anonymously, then get the credential by using apple as the provider, then perform the linking to get the error object with the missing value for key `FIRAuthErrorUserInfoUpdatedCredentialKey`. 

#### Relevant Code:
The code to retrieve the `credential` is directly taken from the [Sign in with Apple tutorial](https://firebase.google.com/docs/auth/ios/apple). Thereafter, the actual linking code comes:

```swift
Auth.auth().currentUser?.link(with: credential) { result, error in
                    if let error = error {
                        if let newCredential = (error as NSError).userInfo[AuthErrorUserInfoUpdatedCredentialKey] as? AuthCredential {
                            // Does not succeed
                        } else {
                            // Dictionary only contains keys "NSLocalizedDescription" and "FIRAuthErrorUserInfoNameKey"
                            print("No userInfo with key AuthErrorUserInfoUpdatedCredentialKey, user info was", (error as NSError).userInfo)
                        }
                    }
                }
```

Note that the key used in the proposed flow was `FIRAuthErrorUserInfoUpdatedCredentialKey` but the code above uses `AuthErrorUserInfoUpdatedCredentialKey` since according to Xcode it has been renamed.

**Comment by rizafran** [comment]
Thanks for reporting, @rudsberg. I'll try this on my end, and will let you know of my findings.

**Comment by rudsberg** [comment]
Thank you for your help, @rizafran. Any progress?

**Comment by rizafran** [comment]
Sorry for the late reply, @rudsberg. I'm still in the process of reproducing the issue. If possible, you may share a sample project that reproduces the issue. Thanks.

**Comment by rizafran** [comment]
Hi @rudsberg, I've tried to reproduce the issue, but I was able to successfully link an anonymous account to my Apple account. With this, could you try using the [Auth quickstart for iOS](https://github.com/firebase/quickstart-ios/tree/master/authentication) and see if the issue is reproducible?

**Comment by rudsberg** [comment]
@rizafran Weirdly enough, I am unable to reproduce this issue now. Well, I am happy at least. Thank you for your help.

**Comment by rudsberg** [comment]
@rizafran Couldn't reproduce it in the quickstart project, and when I went back to my code and after updating all packages it suddenly worked. Magic. Either way, thank you for quick support.
