### ISSUE TITLE
Firebase Auth does not work on macOS (SwiftUI)

### ISSUE THREAD

**Issue by Fateh-Alam** [firebase/firebase-ios-sdk#8522]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.0 Beta 4
  * Firebase SDK version: 8.5.0
  * Installation method: Swift Package Manager
  * Firebase Component: Auth (Auth, Core, Database, Firestore, Messaging, Storage, etc)

#### Steps to reproduce:

Note: This issue is for a macOS app which I am building.

I wrote a simple code file. In which I implemented Firebase Authentication with Email and Password.
But when I hit "Login Button" in the simulator for macOS. But it just gave me the error

**Network error (such as timeout, interrupted connection or unreachable host) has occurred.**

I have checked and diagnosed that there is not problem with my code and internet connection. So there must be a problem with the SDK, itself. I really need to use firebase but it won't work.

#### Relevant Code:

```
func logInAction() {
        Auth.auth().signIn(withEmail: email, password: password) { result, err in
            if err != nil {
                self.showAlert = true
                self.alertMsg = err?.localizedDescription ?? "An Error Occured!"
            } else {
                
                print("Logged In Successfully!")
            }
        }
    }
```

<img width="1012" alt="Screenshot 2021-08-12 at 09 41 24" src="https://user-images.githubusercontent.com/76555603/129139321-3eec6b9c-2b31-4ceb-bb8c-5dd86391ef32.png">

**Comment by rizafran** [comment]
Hi @Fateh-Alam, just to confirm, have you tried to test your app on a real device or tried using other networks to see how it behaves? Thanks.

**Comment by Fateh-Alam** [comment]
yes, I tried testing my app on a real MacBook and tried other networks as well. but the problem persisted and still persists

**Comment by paulb777** [comment]
Did you update the entitlements as described at https://github.com/firebase/firebase-ios-sdk/issues/7408#issuecomment-770906752?

**Comment by Fateh-Alam** [comment]
yes I did.

**Comment by Fateh-Alam** [comment]
Please, I need follow up with this issue. I require the use of Firebase Auth. 

Firebase Auth is still not working in my macOS App.

**Comment by paulb777** [comment]
@Fateh-Alam Please share a reproducible example in a GitHub repo or zip and we can see if we can reproduce.

**Comment by Fateh-Alam** [comment]
That won't be necessary now, since I have gone very deep into the internet and have found a solution.

Thanks for the time and help!

**Comment by paulb777** [comment]
@Fateh-Alam Great to hear! If you like, please share what you what you found here to help others if they run into the same issue.

**Comment by Fateh-Alam** [comment]
I found the solution on Firebase Open Source Website.

![Screenshot_20210820-010323_Samsung Internet.png](https://user-images.githubusercontent.com/76555603/130136552-b0e5ceea-07b6-4afd-aa93-03a46dfa48fb.png)

**Comment by Fateh-Alam** [comment]
The website 

[Firebase Open Source](https://firebaseopensource.com/projects/firebase/firebase-ios-sdk/)
