### ISSUE TITLE
FR: Add support for Swift object serialization in Cloud Functions

### ISSUE THREAD

**Issue by EthanLozano** [firebase/firebase-ios-sdk#8528]
Please add Swift Codable support to Cloud Functions in a FirebaseFunctionsSwift module (or within FirebaseCombineSwift). This request is similar to https://github.com/firebase/firebase-ios-sdk/issues/627 except for Cloud Functions rather than for Firestore.

More specifically, please add Encodable support when calling a function:
```
functions.httpsCallable("myCloudFunction").call(from: encodableObject)
```

Similarly, please add Decodable support to the function result:
```
functions.httpsCallable("myCloudFunction").call() { result, error in
    ...
    let obj = try result?.data(as: DecodableObject.self)
    ...
}
```

**Comment by paulb777** [comment]
@EthanLozano Thanks for the Feature Request.  My preference would be an implementation in a new FirebaseFunctionsSwift library comparable to the Codable implementation for Firestore and the Codable implementation in FirebaseDatabaseSwift added in #6568.

**Comment by paulb777** [comment]
@mortenbekditlevsen Good point! We definitely don't want to repeat code, so my preference would be to factor into another module. In Swift Package Manager, it could be a target, but not a product.

**Comment by paulb777** [comment]
Closing now that #8854 has merged to master
