### ISSUE TITLE
My Project crashes on FBLPromise with unrecognized selector

### ISSUE THREAD

**Issue by hupengfei-hinterstellar** [firebase/firebase-ios-sdk#8536]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 12.5 (12E262)
  * Firebase SDK version: 7.11.0
  * Installation method:  CocoaPods
  * Firebase Component:  Core, Messaging, Analytics, Database, RemoteConfig, Crashlytics

### [REQUIRED] Step 2: Describe the problem

```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[FBLPromise HTTPBody]: unrecognized selector sent to instance 0x283b62c40'
*** First throw call stack:
(0x1a041f180 0x19f5f79f8 0x1a033b9bc 0x1a04249c8 0x1a042665c 0x1088f1704 0x1088f0b88 0x107e39930 0x107e39218 0x10c2f36f4 0x10c2f4c78 0x10c2fcdd4 0x10c2fd8b4 0x10c30777c 0x1a003e114 0x1a0040cd4)
libc++abi.dylib: terminating with uncaught exception of type NSException
```
![image](https://user-images.githubusercontent.com/70873849/129655847-db847bea-6541-4051-b823-d58037bf0b8b.png)

#### Steps to reproduce:
My bug is similar to  [#7939](https://github.com/firebase/firebase-ios-sdk/issues/7939), but a little different.
At first, my project can run very well. When I add another Google SDK [recaptcha](https://cloud.google.com/recaptcha-enterprise/docs/instrument-ios-apps#cocoapods) and run, this crash will occur in a few seconds without any operation. 

I also find some runtime duplicate warning like : `Class GDTCCTCompressionHelper is implemented in both /private/var/containers/Bundle/Application/B990FD3A-0B41-44A2-9818-E98C6BDCB97D/xxxx.app/Frameworks/GoogleDataTransport.framework/GoogleDataTransport (0x108919f30) and /var/containers/Bundle/Application/B990FD3A-0B41-44A2-9818-E98C6BDCB97D/xxxx.app/xxxx (0x1041a3d00). One of the two will be used. Which one is undefined.`.  So I think recaptcha SDK has some frameworks that are the same as Firebase, because of dynamic load, the system choose one , but the one impl is different with another. 

Both SDKs are binary files，I cannot modify them。 How can I Fix it.

**Comment by hupengfei-hinterstellar** [comment]
I had solved it by install recaptcha sdk use cocoapods, so that I got the spec file.

The last version of recaptcha SDK should be iOS 12.0, so I use 16.0.3 and modify spec file dependencies `"Protobuf": "~> 3.14.0"`, then I install and run successfully.

The  recaptcha SDK doc is like shit, it doesn't tell me how to use SDK via manual installation，IOS 12 is also not mentioned. My account is an administrator, but I still can't access cocopods and the download page. Finally, I got the pod through our sales representative's account.

**Comment by maksymmalyhin** [comment]
Note that messages like `Class <class name> is implemented in both ...` is an indicator of a library being linked twice which in most of the cases is an actual issue and will lead to undefined behaviour. Some relevant information can be found at [here](https://github.com/firebase/firebase-ios-sdk/blob/master/docs/firebase_in_libraries.md).
