### ISSUE TITLE
Value of type 'Auth' has no member 'useEmulator'

### ISSUE THREAD

**Issue by StephanTe** [firebase/firebase-ios-sdk#8541]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 9.11.0
  * Installation method: `CocoaPods` (select one)
  * Firebase Component: Auth, Firestore (Auth, Core, Database, Firestore, Messaging, Storage, etc)

### [REQUIRED] Step 2: Describe the problem
Xcode cannot find the method "useEmulator(...)". 
Auth.auth().useEmulator(withHost:"localhost", port:9099)
#### Steps to reproduce:

What happened? How can we make the problem occur?

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulb777** [comment]
9.11.0 is not a valid version. The most recent Firebase version is 8.5.0.   

Please verify you have a recent version.

**Comment by StephanTe** [comment]
solved

**Comment by GoranLilja** [comment]
@StephanTe, I ran into the same issue yesterday, how was it solved?

**Comment by StephanTe** [comment]
@GoranLilja Installed Firebase again, make sure you use these versions:
Installing Firebase (8.5.0)
Installing FirebaseAuth (8.5.0)
And also you have to import Firebase in your class.
