### ISSUE TITLE
Crash: CoreFoundation -[NSArray initWithArray:range:copyItems:]

### ISSUE THREAD

**Issue by MaddyCoder** [firebase/firebase-ios-sdk#8545]
[REQUIRED] Step 1: Describe your environment
Xcode version: 12.4, iOS: 14.6.0
Firebase SDK version: Firebase/Crashlytics v8.1.1
Installation method: CocoaPods
Firebase Component: Performance v8.1.1

[REQUIRED] Step 2: Describe the problem
Steps to reproduce:
What happened? How can we make the problem occur?
Not reproducible

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.
No Sample project

Relevant Code:
Not reproducible

Crashed: com.google.perf.sessionIds.trace
0  libobjc.A.dylib                0x1b5061c80 objc_retain + 16
1  CoreFoundation                 0x1a0572150 __NSArrayI_new + 220
2  CoreFoundation                 0x1a04352f4 -[NSArray initWithArray:range:copyItems:] + 408
3  FirebasePerformance            0x107e5ffc0 __20-[FIRTrace sessions]_block_invoke + 56
4  libdispatch.dylib              0x1a014781c _dispatch_client_callout + 20
5  libdispatch.dylib              0x1a0156910 _dispatch_lane_barrier_sync_invoke_and_complete + 60
6  FirebasePerformance            0x107e5ff10 -[FIRTrace sessions] + 148
7  FirebasePerformance            0x107e750a0 FPRGetTraceMetric + 740
8  FirebasePerformance            0x107e62f40 __22-[FPRClient logTrace:]_block_invoke + 132
9  libdispatch.dylib              0x1a0145a84 _dispatch_call_block_and_release + 32
10 libdispatch.dylib              0x1a014781c _dispatch_client_callout + 20
11 libdispatch.dylib              0x1a014f118 _dispatch_lane_serial_drain + 896
12 libdispatch.dylib              0x1a014fc00 _dispatch_lane_invoke + 404
13 libdispatch.dylib              0x1a015a4bc _dispatch_workloop_worker_thread + 764
14 libsystem_pthread.dylib        0x1ec2e67a4 _pthread_wqthread + 276
15 libsystem_pthread.dylib        0x1ec2ed74c start_wqthread + 8

**Comment by paulb777** [comment]
Please update to 8.6.0. This is similar to issues like #8139 that have been fixed in recent releases.
