### ISSUE TITLE
Can´t use FirebaseFirestoreSwift with FirebaseAuth 8.5.0

### ISSUE THREAD

**Issue by StephanTe** [firebase/firebase-ios-sdk#8546]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version:
  * Installing Firebase (8.5.0)
  *Installing FirebaseAuth (8.5.0)
    Installing FirebaseCore (8.5.0)
    Installing FirebaseCoreDiagnostics (8.6.0)
I.  Installing FirebaseFirestore (8.5.0)
  * Installation method: CocoaPods
  * Firebase Component: Auth, Firestore 

### [REQUIRED] Step 2: Describe the problem
I want to use the Function "Auth.auth().useEmulator(....)" from Firebase. This works totally fine. 
One the other hand I want to use FirebaseFirestoreSwift for inserting, reading and updating data from Firestore.
For installing the pod FirebaseFirestoreSwift, automatically these versions will be downloaded:
Installing Firebase (6.34.0)
Installing FirebaseAuth (6.9.2)
Installing FirebaseCore (6.10.4)
Installing FirebaseCoreDiagnostics (1.7.0)
Installing FirebaseFirestore (1.19.0)
Installing FirebaseFirestoreSwift (0.4.0)

As a consequence I'm able to use FirebaseFirestoreSwift but not anymore the Function  "Auth.auth().useEmulator(....)" from Firebase. 

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by StephanTe** [comment]
I used that. Is it fixed with this?

https://github.com/firebase/firebase-ios-sdk/issues/7195
Not that 8.x is out, it should be pod 'FirebaseFirestoreSwift', '~> 8.0-beta'.

**Comment by paulb777** [comment]
Yes. See https://github.com/firebase/firebase-ios-sdk/issues/7195#issuecomment-873210631
