### ISSUE TITLE
Crash: -[__NSArrayI_Transfer isVerbose]: unrecognized selector sent to instance 0x281731020 -[NSOrderedSet initWithSet:copyItems:]

### ISSUE THREAD

**Issue by alphazhe** [firebase/firebase-ios-sdk#8548]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4, iOS: 14.6.0
  * Firebase SDK version: Firebase/Crashlytics v8.1.1
  * Installation method: CocoaPods
  * Firebase Component: Performance v8.1.1

#### Steps to reproduce:

Steps to reproduce:
What happened? How can we make the problem occur?
Not reproducible, crash reported on firebase.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.
No Sample project

This issue though looks similar to #4166, not sure if this is the same.  
Adding stack trace below.

Stack trace 1
Fatal Exception: NSInvalidArgumentException
-[__NSArrayI_Transfer isVerbose]: unrecognized selector sent to instance 0x281731020
```
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x18d6ca708 __exceptionPreprocess
1  libobjc.A.dylib                0x1a21d47a8 objc_exception_throw
2  CoreFoundation                 0x18d5cdbfc -[NSOrderedSet initWithSet:copyItems:]
3  CoreFoundation                 0x18d6cd260 ___forwarding___
4  CoreFoundation                 0x18d6cf560 _CF_forwarding_prep_0
5  FirebasePerformance            0x108601f00 (Missing)
6  CoreFoundation                 0x18d648564 __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__
7  CoreFoundation                 0x18d5a33d0 -[__NSArrayI enumerateObjectsWithOptions:usingBlock:]
8  FirebasePerformance            0x108601258 (Missing)
9  FirebasePerformance            0x1086010bc (Missing)
10 FirebasePerformance            0x1085eef40 (Missing)
11 libdispatch.dylib              0x18d2b5a84 _dispatch_call_block_and_release
12 libdispatch.dylib              0x18d2b781c _dispatch_client_callout
13 libdispatch.dylib              0x18d2bf118 _dispatch_lane_serial_drain
14 libdispatch.dylib              0x18d2bfc00 _dispatch_lane_invoke
15 libdispatch.dylib              0x18d2ca4bc _dispatch_workloop_worker_thread
16 libsystem_pthread.dylib        0x1d94567a4 _pthread_wqthread
17 libsystem_pthread.dylib        0x1d945d74c start_wqthread
```

Stack trace 2
Crashed: com.google.firebase.crashlytics.ios.exception
SIGABRT ABORT 0x00000001bb9cf334
```
Crashed: com.google.firebase.crashlytics.ios.exception
0  FirebaseCrashlytics            0x10850c31c FIRCLSProcessRecordAllThreads + 180
1  FirebaseCrashlytics            0x10850c700 FIRCLSProcessRecordAllThreads + 1176
2  FirebaseCrashlytics            0x1085054c4 FIRCLSHandler + 48
3  FirebaseCrashlytics            0x1084ffc40 __FIRCLSExceptionRecord_block_invoke + 92
4  libdispatch.dylib              0x18d2b781c _dispatch_client_callout + 20
5  libdispatch.dylib              0x18d2c6910 _dispatch_lane_barrier_sync_invoke_and_complete + 60
6  FirebaseCrashlytics            0x1084ff3d8 FIRCLSExceptionRecord + 212
7  FirebaseCrashlytics            0x1084ff6d0 FIRCLSExceptionRecordNSException + 536
8  FirebaseCrashlytics            0x1084fefb8 FIRCLSTerminateHandler() + 400
9  libc++abi.dylib                0x1a22b4fa0 std::__terminate(void (*)()) + 20
10 libc++abi.dylib                0x1a22b4f2c std::terminate() + 48
11 libobjc.A.dylib                0x1a21d491c objc_terminate + 16
12 libdispatch.dylib              0x18d2b7830 _dispatch_client_callout + 40
13 libdispatch.dylib              0x18d2bf118 _dispatch_lane_serial_drain + 896
14 libdispatch.dylib              0x18d2bfc00 _dispatch_lane_invoke + 404
15 libdispatch.dylib              0x18d2ca4bc _dispatch_workloop_worker_thread + 764
16 libsystem_pthread.dylib        0x1d94567a4 _pthread_wqthread + 276
17 libsystem_pthread.dylib        0x1d945d74c start_wqthread + 8
```

**Comment by paulb777** [comment]
Please update to 8.6.0. There's a good chance that this issue has been solved in recent releases.

**Comment by raymondlam** [comment]
Hi @alphazhe, for the stack traces you provided, are they related to each other or do these stack traces occur separately?

**Comment by alphazhe** [comment]
@raymondlam These stack traces occurred separately, not related to each other.

**Comment by raymondlam** [comment]
Thanks @alphazhe, do you mind creating a separate issue for the Crashlytics stacktrace? We can use this issue to focus on the performance stacktrace and whether it still occurs with the most recent SDK.

**Comment by alphazhe** [comment]
@raymondlam I think I misunderstood your first question. Both stack traces are from same crash. Added second one as an additional information which I thought might be helpful.

**Comment by raymondlam** [comment]
Thanks, could you try out the latest SDK and see if the issue has already been fixed?

**Comment by alphazhe** [comment]
Thanks @raymondlam @paulb777 for the reply, we will update the SDK to 8.6.0, will let you know here if the issue still persists or not.
