### ISSUE TITLE
Error uploading dsyms

### ISSUE THREAD

**Issue by buscarini** [firebase/firebase-ios-sdk#8552]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 12.5.1 (12E507)
  * Firebase SDK version: 8.6.0
  * Installation method: CocoaPods
  * Firebase Component: Core, Analytics, Crashlytics, Performance, DynamicLinks

### [REQUIRED] Step 2: Describe the problem

I can't upload dsyms. I have tried to update the pod, I tried with fastlane and manually, but nothing has worked so far.

#### Steps to reproduce:

Pods/FirebaseCrashlytics/upload-symbols appDsyms.zip -ai bundle_id -p ios

Response:

`error: Failed uploading cSYMs due to error: Error Domain=com.google.firebase.crashlytics.FIRCLSCompoundOperation.error Code=4294967293 "(null)" UserInfo={com.google.firebase.crashlytics.FIRCLSCompoundOperation.error.user-info-key.underlying-errors=(
    "Error Domain=com.crashlytics.mac.error-domain.submit-csym Code=0 \"Failed to submit cSYM for architecture arm64 with uuid 6496bf98760d3e66834dc60667b50104 in dSYM: /var/folders/xg/84xdzlf962xcp8ljktxf3b0m0000gn/T//appDsyms.zip.unzipped/6496bf98-760d-3e66-834d-c60667b50104.dSYM\" UserInfo={NSLocalizedFailureReason=Failed to submit cSYM for architecture arm64 with uuid 6496bf98760d3e66834dc60667b50104 in dSYM: /var/folders/xg/84xdzlf962xcp8ljktxf3b0m0000gn/T//appDsyms.zip.unzipped/6496bf98-760d-3e66-834d-c60667b50104.dSYM, NSUnderlyingError=0x7fce31d22ec0 {Error Domain=FIRCLSNetworkError Code=-5 \"(null)\" UserInfo={status_code=400, type=2, request_id=, content_type=application/json; charset=utf-8}}}"
)}
error: Could not complete submission of dSYM at /var/folders/xg/84xdzlf962xcp8ljktxf3b0m0000gn/T//appDsyms.zip.unzipped/6496bf98-760d-3e66-834d-c60667b50104.dSYM: Error Domain=com.google.firebase.crashlytics.FIRCLSCompoundOperation.error Code=4294967293 "(null)" UserInfo={com.google.firebase.crashlytics.FIRCLSCompoundOperation.error.user-info-key.underlying-errors=(
    "Error Domain=com.crashlytics.mac.error-domain.submit-csym Code=0 \"Failed to submit cSYM for architecture arm64 with uuid 6496bf98760d3e66834dc60667b50104 in dSYM: /var/folders/xg/84xdzlf962xcp8ljktxf3b0m0000gn/T//appDsyms.zip.unzipped/6496bf98-760d-3e66-834d-c60667b50104.dSYM\" UserInfo={NSLocalizedFailureReason=Failed to submit cSYM for architecture arm64 with uuid 6496bf98760d3e66834dc60667b50104 in dSYM: /var/folders/xg/84xdzlf962xcp8ljktxf3b0m0000gn/T//appDsyms.zip.unzipped/6496bf98-760d-3e66-834d-c60667b50104.dSYM, NSUnderlyingError=0x7fce31d22ec0 {Error Domain=FIRCLSNetworkError Code=-5 \"(null)\" UserInfo={status_code=400, type=2, request_id=, content_type=application/json; charset=utf-8}}}"
)}
`

**Comment by paulb777** [comment]
Perhaps related to #8464? See the discussion there.
