### ISSUE TITLE
Refreshing token crashing the app

### ISSUE THREAD

**Issue by grounch** [firebase/firebase-ios-sdk#8554]
Hi

Xamarin.Forms 4.8.0.1364
Xamarin.Firebase.iOS.CloudMessaging 4.7.1
"".iOS.Core 6.10.4
"".iOS.InstanceID 4.8.0

I tried to refresh / regenerate the token in different ways, and all makes the app crash with this error:

Error Domain=com.firebase.iid "Code=7" (null)

Code:

```
NSDictionary<NSString, NSObject> options = new NSDictionary<NSString, NSObject>
        (
            new NSString("apns_token"), _apns_token
        );

string scope = Firebase.InstanceID.InstanceId.ScopeFirebaseMessaging;
var token = Firebase.InstanceID.InstanceId.SharedInstance.GetTokenAsync(_authorizedEntity, scope, options);
```

Problem is i have no idea what is supposed to be _authorizedEntity. The doc about is inexistant.

I tried  GCM_SENDER_ID, CLIENT_ID from googleservice-info.plist. Same error.

Found this issue which is a bit similar but didn't solved anything for me. Cannot even use Messaging as it was mentioned there
https://github.com/firebase/firebase-ios-sdk/issues/7194

Which method should i use for the? GetTokenAsync but with what params? RetrieveFcmToken which i can't find anywhere?

Thanks

**Comment by morganchen12** [comment]
The version of Firebase you're using is very old. InstanceID has been deprecated for a while now; can you try updating to the latest version of Firebase?

**Comment by grounch** [comment]
@morganchen12 My packages are up to date, do you mean the whole InstanceID nuget is obsolete and not necessary?

I cannot remove it from the project because of a dependency with CloudMessaging:

> Unable to uninstall 'Xamarin.Firebase.iOS.InstanceID.4.8.0' because 'Xamarin.Firebase.iOS.CloudMessaging.4.7.1' depends on it.


I actually found RetrieveFCMTokenAsync usage, and it seems to be working for me with those 2 lines:
```

await Firebase.CloudMessaging.Messaging.SharedInstance.DeleteFcmTokenAsync("SENDERID");
var tok = await Firebase.CloudMessaging.Messaging.SharedInstance.RetrieveFcmTokenAsync("SENDERID");

```
The only thing is i have to put the sender id value from googleservice-info.plist manually and hardcode it, which is not optimal to handle dev/prod environments dynamically. Is there a way to access the .plist values from code?

**Comment by morganchen12** [comment]
Yes, you can read plist values at runtime: https://stackoverflow.com/questions/24045570/how-do-i-get-a-plist-as-a-dictionary-in-swift
