### ISSUE TITLE
InAppMessaging: App doesn't receive any messages

### ISSUE THREAD

**Issue by mamilov** [firebase/firebase-ios-sdk#8562]
* Xcode version: 12.5.1
  * Firebase SDK version: 8.6.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: InAppMessaging

#### Steps to reproduce:

What happened? How can we make the problem occur?
I'm trying to get InAppMessaging to work in my app, but the app never receives normal or test messages.
- Start the App with FirDebugEnabled
- Copy/Paste the InAppMessaging Installation-ID into Firebase Campaign 'test on devide'
- Trigger the test and wait for the 'Success:Campaign is ready for testing' message
- Close the App on the simulator/device and reopen or restart the app

**Expected:** Test message is shown 
**Actual:** Nothing happens. Received log is 'There are 0 test messages and 0 regular messages and 0 Firebase Analytics events to watch after resetting the message cache'.

**Comment by paulb777** [comment]
@mamilov Is `FirebaseAnalytics` added as a dependency in addition to `FirebaseInAppMessaging-Beta`?

**Comment by mamilov** [comment]
![image](https://user-images.githubusercontent.com/62982104/130458605-8a28003e-cf6e-4e71-8aed-5e5a16c6eb67.png)
![image](https://user-images.githubusercontent.com/62982104/130458662-63038a64-c575-4440-a592-577abbb73456.png)

Yes, they are all added as dependency

**Comment by mamilov** [comment]
@paulb777 I tested it again today and now it works. Don't know what changed 🤷‍♂️
