### ISSUE TITLE
FIRIdentityToolkitRequest has hardcoded access to default FIRApp instance

### ISSUE THREAD

**Issue by tpetri** [firebase/firebase-ios-sdk#8564]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5.1
  * Firebase SDK version: 8.4.0
  * Installation method: `CocoaPods`
  * Firebase Component: Auth

#### Steps to reproduce:

I have an app that only uses named instances of Firebase.
I found a place inside FirebaseAuth that wrongly accesses the default app instance (that correctly does not exist in my case).

The error is in FIRIdentityToolkitRequest.m  in the function initWithEndpoint:requestConfiguration, there is a hardcoded access to [FIRAuth auth] independent whether the default instance or a named instance is used:

```
    // Automatically set the tenant ID. If the request is initialized before FIRAuth is configured,
    // set tenant ID to nil.
    @try {
      _tenantID = [FIRAuth auth].tenantID;
    } @catch (NSException *e) {
      _tenantID = nil;
    }
```
In my case everything happens to work, but the error message about the not initialized default instance is shown due to the call [FIRAuth auth], which is wrong and misleading. I am asking to make a code change to avoid the message.
I have no idea what tenants are and what their ID might be used for but it feels that this will be a bug when multiple FIRApp instances are used and different tenantIDs should be used depending on the instances.

#### Relevant Code:

To reproduce, create a named instance without creating the default instance and call signIn(withEmail):

```
    let options = FirebaseOptions(googleAppID: applicationId, gcmSenderID: gcmSenderId)
    options.projectID = projectId
    options.apiKey = apiKey
    FirebaseApp.configure(name: "myAppName", options: options)

    if let app = FirebaseApp.app(name: "myAppName") {
      let auth = FirebaseAuth.Auth.auth(app: app)

      // The (wrong) error message is printed when calling signIn(withEmail):
      auth.signIn(withEmail: "something", password: "something", completion: { result, error in
                    return })
    }
```

**Comment by paulb777** [comment]
This issue was fixed in Firebase 10.6.0 via #10805
