### ISSUE TITLE
Dynamic Links crash on iOS 9

### ISSUE THREAD

**Issue by locone** [firebase/firebase-ios-sdk#8565]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5.1
  * Firebase SDK version: 8.6.0
  * Installation method: Zip file
  * Firebase Component: Dynamic Links

### [REQUIRED] Step 2: Describe the problem
Dynamic Links crash on iOS 9

#### Steps to reproduce:
Integrate Dynamic Links, run on iOS 9, crash.

#### Relevant Code:
FIRDLDefaultRetrievalProcessV2.m

- (NSString *)retrievePasteboardContents {
  if (![self isPasteboardRetrievalEnabled]) {
    // Pasteboard check for dynamic link is disabled by user.
    return @"";
  }

  NSString *pasteboardContents = @"";
  if (@available(iOS 10.0, *)) {
    if ([[UIPasteboard generalPasteboard] hasURLs]) {
      pasteboardContents = [UIPasteboard generalPasteboard].string;
    }
  } else {
    pasteboardContents = [UIPasteboard generalPasteboard].string;
  }
  return pasteboardContents;
}

@available(iOS 10.0, *) is not working correctly on iOS 9 and iOS 10, which cause "hasURLs" will be called on iOS 9.

**Comment by paulb777** [comment]
@locone Sorry about the trouble. From the [Release Notes](https://firebase.google.com/support/release-notes/ios), Firebase dropped support for iOS 9 in Firebase 7.x for everything except Crashlytics and Analytics.

Using Dynamic Links with iOS 9 requires Firebase 6.x or earlier.
