### ISSUE TITLE
Cannot add the `-ObjC` linker flag when integrating Firebase Analytics via SPM

### ISSUE THREAD

**Issue by yakovmanshin** [firebase/firebase-ios-sdk#8567]
## Step 1: Describe your environment

  * Xcode version: 12.5.1
  * Firebase SDK version: 8.6.0
  * Installation method: Swift Package Manager
  * Firebase Component: Analytics

## Step 2: Describe the problem

The [SPM integration guide](https://github.com/firebase/firebase-ios-sdk/blob/master/SwiftPackageManager.md) mentions the `-ObjC` linker flag which must be added when Firebase Analytics is used.

However, when Firebase is integrated via a Swift package and once this flag is added to the package’s target, it’s no longer possible to use the package in the iOS app due to the `The package product 'MyPackage' cannot be used as a dependency of this target because it uses unsafe build flags` error.

### Steps to reproduce:

1. Declare a Swift package in an iOS app project and add it to the app target;
2. In `Package.swift`, add Firebase Analytics as one of the package’s targets’ dependency;
3. Specify the `-ObjC` flag in `linkerSettings` for that target (see below);
4. The app target builds with the aforementioned error.

```swift
.target(
    name: "MyAnalyticsTarget",
    dependencies: [
        .product(name: "FirebaseAnalytics", package: "Firebase"),
    ],
    linkerSettings: [.unsafeFlags(["-ObjC"])]
),
```

**Comment by paulb777** [comment]
The `-ObjC` option needs to be added to the app's build settings. It should not be added to a `Package.swift`. See the screenshot in https://github.com/firebase/firebase-ios-sdk/blob/master/SwiftPackageManager.md
