### ISSUE TITLE
Can we update Google Utilities to 7.5.1

### ISSUE THREAD

**Issue by mohdabdurraafay** [firebase/firebase-ios-sdk#8571]
### Feature proposal

* Firebase Component: Auth

FirebaseAuth uses Google utilities. It seems to be using 7.4. Can we please upgrade that to v7.5.1? It seems to have fixes for a heartbeat that could be useful with the latest Xcode versions.

**Comment by rizafran** [comment]
Hi @mohdabdurraafay, could you confirm if you're using CocoaPods to install your Firebas SDK? I've tried to update my sdk to the latest one, and saw that GoogleUtilities is already 7.5.1 (see screenshot for reference).
<img width="878" alt="Screen Shot 2021-08-25 at 9 02 30 PM" src="https://user-images.githubusercontent.com/56452638/130795993-788e19d9-613f-4187-b648-8382f3d96732.png">
