### ISSUE TITLE
Two firebase installations with swift package manager

### ISSUE THREAD

**Issue by smrfeld** [firebase/firebase-ios-sdk#8591]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5.1
  * Firebase SDK version: 8.6.1
  * Installation method: `Swift Package Manager`
  * Firebase Component: All

### [REQUIRED] Step 2: Describe the problem

Firebase gives the warnings/errors:
```
objc[6654]: Class CSServerEndpointFeatures is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SpeakerRecognition.framework/SpeakerRecognition (0x1456fda08) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreSpeech.framework/CoreSpeech (0x1444e20c8). One of the two will be used. Which one is undefined.
```
and many more `One of the two will be used. Which one is undefined.`.

Additionally, despite running `FirebaseApp.configure()` in `application(_:didFinishLaunchingWithOptions:)`, I still get the warning:
```
2021-08-30 09:58:58.404351-0700 iOS-App[6654:112906] 8.6.1 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `FirebaseApp.configure()` to your application initialization. This can be done in in the App Delegate's application(_:didFinishLaunchingWithOptions:)` (or the `@main` struct's initializer in SwiftUI). Read more: https://goo.gl/ctyzm8.
```

I believe it is related to [this issue](https://stackoverflow.com/a/61352175/1427316) about firebase having been linked twice, but since I am using Swift package manager to install and I believe (?) this is already linked statically, it does not resolve my issue.

#### Steps to reproduce:

1. I added firebase with swift package manager. I chose the latest version, in this case `8.6.1`. I also tried this with an earlier version such as `8.5.0` with the same result.
2. Inside `func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {` I slap the configure command `FirebaseApp.configure` (having already added the `GoogleService-Info.plist` file).
3. I build and run the app in the simulator & the errors above pop up.

#### Relevant Code:

I get this on a totally clean Xcode ios app project. The configuration is just:
```
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        
        FirebaseApp.configure()

        return true
    }
```

**Comment by maksymmalyhin** [comment]
@smrfeld Sorry for the trouble. I was not able to reproduce the issue on my end integrating Firebase SDKs with the app target using Swift Package Manager. To make progress on the issue we will need a sample project where the issue is reproducible.
