### ISSUE TITLE
fbsdkviewhierarchy.h file not found 

### ISSUE THREAD

**Issue by askari01** [firebase/firebase-ios-sdk#8598]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 5.15.1
  * Installation method: `CocoaPods`
  * Firebase Component: Core

### [REQUIRED] Step 2: Describe the problem
pod install, pod update reproduce same error. 

#### Steps to reproduce:
add in pod file
pod install

What happened? How can we make the problem occur?
'AppEvents/Codeless/FBSDKViewHierarchy.h' file not found

In file included from /Users/askari/Projects/ios-app/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/FBSDKAccessToken.m:21

In file included from /Users/askari/Projects/ios-app/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/Network/FBSDKGraphRequestPiggybackManager.h:19

**Comment by rizafran** [comment]
Hi @askari01, based on the info you provided, the SDK version you're using is 5.15.1. Also, I've tried to reproduce the issue, but I wasn't able to get an error. With this, could you confirm if you have tried running the `pod update` command to update your SDK? Thanks.

**Comment by rizafran** [comment]
Hi @askari01, as discussed with the team, the file is from Facebook SDK, and it seems that there's an issue with it. Please report it [here](https://cocoapods.org/pods/FBSDKCoreKit). We can reopen if the issue is about Firebase triggering it. Thanks.
