### ISSUE TITLE
Obj-C to Swift auto translation Cocoa violation

### ISSUE THREAD

**Issue by mortenbekditlevsen** [firebase/firebase-ios-sdk#8599]
For Cocoa API in Objective-C there's a convention, that an API that returns a nullable value and updates an NSError reference only returns nil when it also sets the error value.
(I haven't found an official source for this, but it's discussed here: https://stackoverflow.com/questions/34187188/using-an-objective-c-function-that-returns-an-optional-or-throw-in-swift)

The API: 
```
- (nullable FIRUser *)getStoredUserForAccessGroup:(NSString *_Nullable)accessGroup
                                            error:(NSError *_Nullable *_Nullable)outError {
```
is translated to:
```
func getStoredUser(forAccessGroup accessGroup: String?) throws -> User
```
following those Cocoa conventions - but in the code you can see that the intention is to return an optional `User` (meaning that it's perfectly fine and not an error to return nil).

This unfortunately can't be expressed through the automatic Objective-C/Cocoa bridging, so the API ends up being a bit weird, where the absence of a user (even though not really an error) ends up throwing a `nilError`.

https://github.com/firebase/firebase-ios-sdk/blob/0d90f2f12d18235dc6ac5131de5c8326243f0d33/FirebaseAuth/Sources/Auth/FIRAuth.m#L2233

I don't know of any good way to clean up such API, but perhaps it would be worthwhile documenting this bridging behavior somewhere.

**Comment by mortenbekditlevsen** [comment]
I'm not exactly certain what could be done to fix this to import correctly to Swift, but if there is anything that could be done, then it could perhaps be worth doing in the v9 release, since it might be a slight API-break.

One way to fix it would be to mark the method `NS_SWIFT_NOTHROW` and then have a Swift overlay that implements the correct behavior that may return an optional `User`. But since there's currently no Swift overlay for auth, that may also be a bit cumbersome...

@ryanwilson @paulb777

**Comment by paulb777** [comment]
Thanks @mortenbekditlevsen. I'll add to the Firebase 9 milestone for us to take a look.

**Comment by morganchen12** [comment]
This is another instance of the underlying issue fixed in https://github.com/firebase/firebase-ios-sdk/pull/9502. We'll likely have to do the same thing here.

**Comment by morganchen12** [comment]
Looking at the issue more closely, there's unfortunately no `FirebaseAuthSwift` module for us to patch this into, so our options are:

- Just remove the `async throws` api and make users use the completion closure, and then add back the async version when we add a Swift SDK later.
- Mess with the return value so there can be no `nil` on success.
  - Consider no user to be an error case and return `nil` with a `UserNotFound` or similar error
  - Return `NSNull(), nil`

**Comment by morganchen12** [comment]
Oops, I've misread the constraints of this issue a bit--we should be able to fix this with an annotation (`swift_error(nonnull_error)`), which the llvm docs state will leave the return value explicitly unmodified.
