### ISSUE TITLE
App Distribution FIRAppDistributionRelease.releaseNotes may be null, documented as non-null

### ISSUE THREAD

**Issue by mikehardy** [firebase/firebase-ios-sdk#8602]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5.1
  * Firebase SDK version:8.6.0
  * Installation method: `CocoaPods`
  * Firebase Component: App Distribution (Auth, Core, Database, Firestore, Messaging, Storage, etc)

#### Steps to reproduce:

The documentation for the releaseNotes property on FIRAppDistributionRelease indicates it is non-null https://firebase.google.com/docs/reference/ios/firebaseappdistribution/api/reference/Classes/FIRAppDistributionRelease#releasenotes

However, in practice the property may be null? https://github.com/invertase/react-native-firebase/pull/5667

Now, it may well be this is my incorrect interpretation of what non-null means in objective-c as a modifier on a property, perhaps what it means is that you cannot attempt to set it to null, but if accessed (without ever being set) it is potentially null.

If so, apologies for the noise, please close, and I've learned something (and thank you)

But if this is an issue it should be fixed either in documentation or code or where ever the data is initiall provided I guess 

#### Relevant Code:

Crash report in linked react-native-firebase issue, but:

```objective-c
resolve(@{
      @"displayVersion" : release.displayVersion,
      @"buildVersion" : release.buildVersion,
      @"releaseNotes" : release.releaseNotes,
      @"isExpired" : [NSNumber numberWithBool:release.isExpired],
      @"downloadURL" : release.downloadURL
    });
```

If you do that, the releaseNotes property will potentially be nil

**Comment by mikehardy** [comment]
For ecosystem comparison, I know firebase-android-sdk hasn't released app distribution yet, but they are working hard on it, and they are marked as nullable:

https://github.com/firebase/firebase-android-sdk/blob/82b02af331d4674682bfb90c195da45543b808c3/firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/AppDistributionRelease.java#L46-L48

**Comment by paulb777** [comment]
This may be addressable earlier, but I'll mark for the next major release to review when we do a thorough nullability review at that point.

**Comment by ryanwilson** [comment]
Fixed in the Firebase 9 branch which will be merged soon. Closing now, thanks for the report and sorry for the troubles!
