### ISSUE TITLE
Carthage binary contains Firebase.framework instead of xcframework

### ISSUE THREAD

**Issue by iamszabo** [firebase/firebase-ios-sdk#8637]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.3
  * Firebase SDK version: 8.7.0
  * Installation method: `Carthage` (select one)
  * Firebase Component: FirebaseAnalyticsBinary

#### Steps to reproduce:

What happened? How can we make the problem occur?
Download the binary from https://dl.google.com/dl/firebase/ios/carthage/8.6.0/FirebaseAnalytics-17512c102cfe19b6.zip
If you take a look the Firebase is not wrapped in xcframework as the others, hence doesn't contain the correct architecture slice (arm64 simulator).

**Comment by bruce-ios** [comment]
I have the same issue. How to fix it?

![截圖 2021-09-17 14 24 15](https://user-images.githubusercontent.com/86638966/133734617-983205a0-5a17-46d7-9176-a2f59d69f6cf.png)

**Comment by paulb777** [comment]
`Firebase.framework` should not be embedded. See the `Delete Firebase.framework from the Link Binary With Libraries Build Phase` step at https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md
