### ISSUE TITLE
Firebase performance, Realm usage together lead to sporadic crashes

### ISSUE THREAD

**Issue by alanf** [firebase/firebase-ios-sdk#8639]
* Xcode version: 12.5.1
  * Firebase SDK version: 6.33.0
  * Installation method: `CocoaPods`
  * Firebase Component: Performance

#### Steps to reproduce:

What happened? How can we make the problem occur?

Adding performance instrumentation to a codebase with Realm causes the crash to sporadically occur, likely due to swizzling conflicts.

See discussion [here](https://github.com/realm/realm-cocoa/issues/5618)

Since this issue only manifests when the libraries are combined together, ideally the maintainers of each would find a fix together so users don't have to choose one library over the other :)

**Comment by ncooke3** [comment]
Hi @alanf,

Thanks for reporting this and linking the to that discussion thread. We'll have the performance team take a closer took at the issue and report back with our findings.
cc: @maksymmalyhin @visumickey

**Comment by yalunqin** [comment]
Hi @alanf 

Thanks for reporting this issue. Can you also provide the Firebase Performance SDK version (you can find it in Podfile.lock) and Realm version that have this issue?

**Comment by alanf** [comment]
@yalunqin sure, thanks for following up. Here's the relevant Firebase portion of our Podfile:

```
  - Firebase/Analytics (6.33.0):
    - Firebase/Core
  - Firebase/Core (6.33.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.8.3)
  - Firebase/CoreOnly (6.33.0):
    - FirebaseCore (= 6.10.3)
  - Firebase/Crashlytics (6.33.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 4.6.1)
  - Firebase/Performance (6.33.0):
    - Firebase/CoreOnly
    - FirebasePerformance (~> 3.3.0)
  - FirebaseABTesting (4.2.0):
    - FirebaseCore (~> 6.10)
  - FirebaseAnalytics (6.8.3):
    - FirebaseCore (~> 6.10)
    - FirebaseInstallations (~> 1.6)
    - GoogleAppMeasurement (= 6.8.3)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.7)
    - GoogleUtilities/MethodSwizzler (~> 6.7)
    - GoogleUtilities/Network (~> 6.7)
    - "GoogleUtilities/NSData+zlib (~> 6.7)"
    - nanopb (~> 1.30906.0)
  - FirebaseCore (6.10.3):
    - FirebaseCoreDiagnostics (~> 1.6)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Logger (~> 6.7)
  - FirebaseCoreDiagnostics (1.7.0):
    - GoogleDataTransport (~> 7.4)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Logger (~> 6.7)
    - nanopb (~> 1.30906.0)
  - FirebaseCrashlytics (4.6.1):
    - FirebaseCore (~> 6.10)
    - FirebaseInstallations (~> 1.6)
    - GoogleDataTransport (~> 7.2)
    - nanopb (~> 1.30906.0)
    - PromisesObjC (~> 1.2)
  - FirebaseInstallations (1.7.0):
    - FirebaseCore (~> 6.10)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/UserDefaults (~> 6.7)
    - PromisesObjC (~> 1.2)
  - FirebasePerformance (3.3.2):
    - FirebaseCore (~> 6.9)
    - FirebaseInstallations (~> 1.5)
    - FirebaseRemoteConfig (~> 4.7)
    - GoogleDataTransport (~> 7.0)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/ISASwizzler (~> 6.2)
    - GoogleUtilities/MethodSwizzler (~> 6.2)
    - GTMSessionFetcher/Core (~> 1.1)
    - Protobuf (~> 3.12)
- FirebaseRemoteConfig (4.9.1):
    - FirebaseABTesting (~> 4.2)
    - FirebaseCore (~> 6.10)
    - FirebaseInstallations (~> 1.6)
    - GoogleUtilities/Environment (~> 6.7)
    - "GoogleUtilities/NSData+zlib (~> 6.7)"
```

and Realm:

```
  - Realm (10.10.0):
    - Realm/Headers (= 10.10.0)
  - Realm/Headers (10.10.0)
  - RealmSwift (10.10.0):
    - Realm (= 10.10.0)
```

Let me know if I can send any other info!

**Comment by morganchen12** [comment]
Hi @alanf, the version of Firebase you're using is over two years old. Can you try upgrading to the latest version of Firebase?

**Comment by yalunqin** [comment]
Hi @alanf , I didn't see any crash using Firebase 8.7.0 + RealmSwift 10.15.0 (The Realm Swift code was [this](https://docs.mongodb.com/realm/sdk/ios/quick-start/#complete-example)).  Can you upgrade to those versions and try again? If it still crashes, can you provide the sample code (especially the Realm part)?

**Comment by alanf** [comment]
@yalunqin thank you for calling this out, we will get on an up-to-date version of Firebase and report back.

**Comment by alanf** [comment]
We have the changes on a branch ready to go out, the next step is to see how it performs once it's released (may take 1-2 weeks to be live)

**Comment by paulb777** [comment]
I close this issue here since multiple crashes have been fixed since 6.x. Please open another issue if you still see crashes with 8.x.
