### ISSUE TITLE
FR: Add readTime property to Firestore DocumentSnapshot

### ISSUE THREAD

**Issue by willbattel** [firebase/firebase-ios-sdk#8641]
### Feature proposal

* Firebase Component: Firestore

My team has a use case where our clients are frequently reading from a particular collection that we don't need kept fully up to date on the client- but we want to periodically refresh. We want to cache the snapshot data on the device, and only perform a server read if the cached document is beyond some defined TTL.

We can use an alternative mechanism to perform the caching, such as Core Data, but we first wanted to see if it was possible with the already-available Firestore cache. To do this we need to know how old the cached document is, but I noticed that the `readTime` property (as well as `createTime` and `updateTime`) are present only in the Admin SDKs (i.e., [Node](https://googleapis.dev/nodejs/firestore/latest/DocumentSnapshot.html), [Python](https://googleapis.dev/python/firestore/latest/document.html#google.cloud.firestore_v1.base_document.DocumentSnapshot)). Is there a specific reason that the client SDKs do not provide these properties?

**Comment by wu-hui** [comment]
I think you could try to use [getDocuments with source](https://firebase.google.com/docs/reference/swift/firebasefirestore/api/reference/Classes/Query#/c:objc(cs)FIRQuery(im)getDocumentsWithSource:completion:). 

You can do `getDocument(source:.server)` or `default`, and save the local device time as your read time. Within your TTL, you could then do `getDocument(source:cache)`, and only get from server when you are out of the TTL.

Regarding exposing readTime and others, they are mainly used to keep the SDK's cache consistent, we simply have not seen use cases that demand them. Please give above a try, if this does not work for you, maybe it can be a use case to support exposing them.

**Comment by willbattel** [comment]
> I think you could try to use [getDocuments with source](https://firebase.google.com/docs/reference/swift/firebasefirestore/api/reference/Classes/Query#/c:objc(cs)FIRQuery(im)getDocumentsWithSource:completion:). 
> 
> 
> 
> You can do `getDocument(source:.server)` or `default`, and save the local device time as your read time. Within your TTL, you could then do `getDocument(source:cache)`, and only get from server when you are out of the TTL.
> 
> 
> 
> Regarding exposing readTime and others, they are mainly used to keep the SDK's cache consistent, we simply have not seen use cases that demand them. Please give above a try, if this does not work for you, maybe it can be a use case to support exposing them.

Sorry, I wasn't clear enough in my request. I meant that we already use the `source` API, and we just want the `readTime` exposed on the snapshot so that we don't have to save and lookup the read time ourselves in an auxiliary cache. What you describe is what we already plan to do as the **workaround**, we're requesting this feature as a convenience so that developers don't have to save the `readTime` themselves- and can just check it on the snapshot returned from the Firestone cache before fetching again with the `source` as `server` if it's too old.

Since it's already used for maintaining the cache internally, simply exposing it to the the public API would allow developers to better make use of the cache.

**Comment by wu-hui** [comment]
Actually, exposing `readTime` would not help as much here, because you would then compare `readTime` to the local device time to calculate if it is out of TTL, wouldn't you? This is bad because the two time stamps are from two different source, and are not meant to be compared against each other. 

Note although `readTime` in snapshots generally reflects read world time, it is not a guarantee, and exposing it would be making such a guarantee. But at the end of the day, it is only used to resolve inconsistencies between local cache and backend.

**Comment by willbattel** [comment]
> Actually, exposing `readTime` would not help as much here, because you would then compare `readTime` to the local device time to calculate if it is out of TTL, wouldn't you? This is bad because the two timestamps are from two different source, and are not meant to be compared against each other.

Yes, that's right. In our case, this wouldn't be a problem because our TTLs are fairly long and we don't require much precision- but I can see how that could be a source of flakiness for other scenarios. You would probably have to add an entirely new API to fetch the current "Firestore time" in order to perform the comparison.

> Note although `readTime` in snapshots generally reflects real world time, it is not a guarantee, and exposing it would be making such a guarantee. But at the end of the day, it is only used to resolve inconsistencies between local cache and backend.

In our case this would be nice to have, but I understand the potential problem for others. Is the `readTime` exposed in the Admin SDKs because the server environment is expected to be more suitable for comparing time- or is there another reason why these are exposed in the Admin SDKs?

**Comment by wu-hui** [comment]
Well, the "reason" was we forgot to remove them from API, it was an oversight...
