### ISSUE TITLE
FR: Firebase License

### ISSUE THREAD

**Issue by res0nance** [firebase/firebase-ios-sdk#8642]
### Feature proposal

* Remove the APPENDIX section within the license
* https://github.com/firebase/firebase-ios-sdk/blob/11b1a353e1d2a93b1583f56481df5a09391561ab/LICENSE#L179-L202

Issues stems from installing firebase via cocoapods, this causes the entire appendix to be added to the acknowledgements file. 
Perhaps the appendix should be added to a separate file instead of the main `LICENSE` file as it  technically is not part of the license

**Comment by paulb777** [comment]
The Google open source guidance is that the appendix should be included. See #7105 and https://opensource.google/docs/releasing/preparing/#license-file

What exactly is the issue you're seeing?  Perhaps there is a CocoaPods issue here?

**Comment by res0nance** [comment]
In the case of cocoapods, what happens is that the autogenerated acknowledgements file includes the appendix, since its included in your license file.

With multiple firebase components this bloats the file considerably.

From my understanding this appendix is not required to be compliant with the license. So I was proposing it be removed. Though if google is of the opinion that they want the appendix included, we can close this issue.

**Comment by paulb777** [comment]
Yep. Thanks for the report. Ideally there would be a way for multiple pods to share a license, but I'm not sure that's going to happen for CocoaPods.
