### ISSUE TITLE
leveldb has been to checking out when i use SwiftPM install Firebase SDK

### ISSUE THREAD

**Issue by spirit-jsb** [firebase/firebase-ios-sdk#8643]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: `12.5.1 (12E507)`
  * Firebase SDK version: `8.7.0`
  * Installation method: `Swift Package Manager` (select one)
  * Firebase Component: `leveldb`

#### Steps to reproduce:
leveldb has been to checking out when i use SwiftPM install Firebase SDK

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by spirit-jsb** [comment]
oh no.... it's work! i don't know why leveldb checking out so much slow

**Comment by morganchen12** [comment]
Slowness may be caused by your network, or by GitHub if there's a service degradation. You can try checking out leveldb manually with the `--verbose` flag for more details.
