### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_FIRApp 

### ISSUE THREAD

**Issue by tringuyen623** [firebase/firebase-ios-sdk#8648]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5.1
  * Firebase SDK version: _____
  * Installation method: `Carthage` (select one)
  * Firebase Component: Core, Auth (Auth, Core, Database, Firestore, Messaging, Storage, etc)

### [REQUIRED] Step 2: Describe the problem
I'm using Carthage for install Firebase follow step by step from this: https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md
I can import Firebase/FirebaseAuth ... and run without any problem, but when I'm using FirebaseApp.configure().... it built failed: 
ld: warning: Could not find or use auto-linked framework 'Firebase'
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FIRApp", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by tringuyen623** [comment]
Does anyone have the same issue like me?

**Comment by rizafran** [comment]
Hi @tringuyen623, it is usually an issue with the project settings. Could you please provide a sample project reproducing the issue? Thanks.

**Comment by tringuyen623** [comment]
> Hi @tringuyen623, it is usually an issue with the project settings. Could you please provide a sample project reproducing the issue? Thanks.

This is sample project: https://gitlab.com/tringuyen623/sample-project-with-firebase.git

**Comment by rizafran** [comment]
Thanks for sharing your project @tringuyen623. Per checking, the project is only accessible if there's a GitLab account. With this, is it possible for you to share your sample project publicly?

**Comment by tringuyen623** [comment]
I'm sorry, I already public it

**Comment by rizafran** [comment]
@tringuyen623, could you try to link the other needed frameworks from the Carthage/Build folder to your Xcode project and see if the issue will persist?

**Comment by tringuyen623** [comment]
@rizafran  I already tried, but it still happen.
I use Mac M1 chip

**Comment by rizafran** [comment]
Thanks for letting me know, @tringuyen623. I just want to confirm if you have followed the "Delete Firebase.framework from the Link Binary With Libraries Build Phase." step in the [Carthage instructions](https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md#carthage-usage)? Also, you may try to `import FirebaseCore` as a workaround.

**Comment by Afinque** [comment]
> Does anyone have the same issue like me?

Yes, I'm seeing the same error. I used Swift Package Manager, though, not sure if that's relevant or not.

**Comment by tringuyen623** [comment]
@rizafran I tried but nothing change, issue still exist

**Comment by tringuyen623** [comment]
@paulb777 I do follow the instructions. 
It still error.
![Screen Shot 2021-10-06 at 21 31 21](https://user-images.githubusercontent.com/57216076/136224153-4ca5a5be-4ae0-4fe4-8ed8-d29c66635eb1.png)
![Screen Shot 2021-10-06 at 21 31 34](https://user-images.githubusercontent.com/57216076/136224172-a637227e-ca4f-4129-b330-3685de59fb9c.png)
![Screen Shot 2021-10-06 at 21 31 40](https://user-images.githubusercontent.com/57216076/136224177-f1e2c9e5-ede0-42de-b298-d07c3a4acaf3.png)
![Screen Shot 2021-10-06 at 21 31 45](https://user-images.githubusercontent.com/57216076/136224183-737b101e-4a7c-483d-ae19-069191ff3fbd.png)
![Screen Shot 2021-10-06 at 21 32 01](https://user-images.githubusercontent.com/57216076/136224188-c0d66be8-21ee-4e13-a2cc-db8830645af7.png)

**Comment by tringuyen623** [comment]
> @tringuyen623 Please follow the instructions in https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md.
> 
> The sample you attached does not include all of the xcframeworks installed by Carthage nor does it add them to the `Link Binaries with Libraries` linker phase.

I do follow the instructions
this is all file when I run carthage update:
![Screen Shot 2021-10-06 at 22 08 45](https://user-images.githubusercontent.com/57216076/136231372-ddbfaec4-132b-45ab-baf1-96dc8eed3859.png)
