### ISSUE TITLE
The DebugView shows the user property even if the app has removed it.

### ISSUE THREAD

**Issue by chauhan130** [firebase/firebase-ios-sdk#8651]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5.1
  * Firebase SDK version: Analytics (7.5.0) 
  * Installation method: `CocoaPods`
  * Firebase Component: Analytics

### [REQUIRED] Step 2: Describe the problem
The DebugView shows the user property even if the app has removed it. The firebase debug logs claims the same.

#### Steps to reproduce:
1. Add a user property with Firebase Analytics like `referred_by`.
2. The debug view would show the added property.
3. Remove the property from the app, like: `Analytics.setUserProperty(nil, forName: "referred_by")`.
The firebase debug logs should confirm the property is removed:
`2021-09-13 16:29:24.107639+0530 Application[6767:644301] 7.5.0 - [Firebase/Analytics][I-ACS023078] User property removed. Name: referred_by`
4. Notice the Debug View still shows the user property for consecutive events.

Not sure if this is related, but there is an outstanding issue #4856 which looks exactly the same.

**Comment by rizafran** [comment]
Hi @chauhan130, I've tried to reproduce the issue, and I was able to get the same behavior. I've made a follow up in the existing bug found on the issue #4856. I'll let you know once I've got an update from them. Thanks.

**Comment by chauhan130** [comment]
Thank you @rizafran.

**Comment by paulb777** [comment]
Closing in favor of the duplicate #4856
