### ISSUE TITLE
FCM flaky tests

### ISSUE THREAD

**Issue by maksymmalyhin** [firebase/firebase-ios-sdk#8652]
FCM test `-[FIRMessagingTokenManagerTest testResetCredentialsWithNoCachedCheckin]` is regularly fails in nightly builds. Sometimes (but not always) the test passes after re-run. See failure examples: 
- https://github.com/firebase/firebase-ios-sdk/runs/3587412371?check_suite_focus=true#step:4:10085
- https://github.com/firebase/firebase-ios-sdk/runs/3578204793?check_suite_focus=true#step:4:677

**Comment by chliangGoogle** [comment]
hmm I'm having trouble reproduce. I tried resetting the simulator and cleaning the project build and test results. And I tested SPM and nonSPM as well.
I wonder what nightly build setup is different than mine.

**Comment by maksymmalyhin** [comment]
seems like it's flaky internally as well, see cl/397422878.

**Comment by maksymmalyhin** [comment]
FCM tests are still flaky in nightly builds: #8663.
