### ISSUE TITLE
Auth fails to insert item in keychain with error "securityd insert failed for item"

### ISSUE THREAD

**Issue by domagojstankovic** [firebase/firebase-ios-sdk#8662]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5.1 (12E507)
  * Firebase SDK version: 7.10.0
  * Installation method: `CocoaPods`
  * Firebase Component: Auth, Firestore

Note: this is a legacy app so it's not easy for us to update to the latest version since it will require major refactor.

#### Steps to reproduce:

We have issues when signing-in using Firebase Auth. On sign in, we try to create a user using Firestore.
We are unable to reproduce it locally, but it happens very often lately and it's causing significant user drop-off.
We managed to get a log from one of the users though. This is the relevant line that we suspect that it's causing sign-in issues:
> default	11:46:18.056554-0400	securityd	insert failed for item <genp,acct=firebase_auth_1___FIRAPP_DEFAULT_firebase_user,svce=firebase_auth_1:733358412247:ios:a281fcfae6b1b7741e3b92,agrp=CW8552PJP5.ai.bunch.coach,sync=0,musr=, |otherAttr,tomb=0,cdat=2021-09-10 15:46:18 +0000,mdat=2021-09-10 15:46:18 +0000,pdmn=cku,sha1=E3AB636AB07A682A3C013E5A29CB1DA9D98E5052,v_Data=<?>,UUID=B0513600-8E3A-413C-9856-970751BF1E9D,persistref=,clip=0> with Error Domain=com.apple.utilities.sqlite3 Code=19 "finalize: 0x1090d07f0: [19->2067] UNIQUE constraint failed: genp.acct, genp.svce, genp.agrp, genp.sync, genp.vwht, genp.tkid, genp.musr" UserInfo=\{numberOfErrorsDeep=1, NSDescription=finalize: 0x1090d07f0: [19->2067] UNIQUE constraint failed: genp.acct, genp.svce, genp.agrp, genp.sync, genp.vwht, genp.tkid, genp.musr, NSUnderlyingError=0x1037cc440 \{Error Domain=com.apple.utilities.sqlite3 Code=19 "step: [19->2067] UNIQUE constraint failed: genp.acct, genp.svce, genp.agrp, genp.sync, genp.vwht, genp.tkid, genp.musr" UserInfo=\{numberOfErrorsDeep=0, NSDescription=step: [19->2067] UNI\

#### Relevant Code:

Simplified code:
```
func createUser(completion: @escaping (Result<Void, Error>) -> Void) {
    Auth.auth().addStateDidChangeListener { auth, user in
        if let user = user {
            let db = Firestore.firestore()
            let userRef = db.collection("users").document(user.uid)
            userRef.getDocument { document, error in
                if let error = error {
                    completion(.failure(error))
                    return
                }
                guard let document = document else {
                    fatalError("error and document nil")
                }
                if !document.exists {
                    userRef.setData(["Likes": [], "signUpDate": Date()]) { error in
                        if let error = error {
                            completion(.failure(error))
                        } else {
                            completion(.success(()))
                        }
                    }
                } else {
                    completion(.success(()))
                }
            }
        } else {
            completion(.success(()))
        }
    }
}
```

**Comment by morganchen12** [comment]
This error will be difficult to debug without repro steps, since something in the security framework is causing Auth to not be able to save data to the keychain. Can you try isolating repro steps from the user who experienced this issue?

**Comment by domagojstankovic** [comment]
> This error will be difficult to debug without repro steps, since something in the security framework is causing Auth to not be able to save data to the keychain. Can you try isolating repro steps from the user who experienced this issue?

Unfortunately not, we are unable to reproduce it, it happens randomly.
It would help a lot even if we knew if this error is caught and handled by Firebase SDK or does it bubble up to the surface and reaches our code.

**Comment by paulb777** [comment]
Closing for staleness. Please comment or open a new issue to reopen.
