### ISSUE TITLE
FirebaseFirestoreSwift is not working when installed via Swift Package Manager

### ISSUE THREAD

**Issue by kou-yamamoto** [firebase/firebase-ios-sdk#8666]
### My Environment

  * Xcode version: 12.5.1
  * Firebase SDK version: 8.7.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: FirestoreSwift

### Describe the problem

- When I installed FirebaseFirestoreSwift via Swift Package Manager, `Type Firestore has no member Dedocer` error is shown.

<img src="https://user-images.githubusercontent.com/71382628/133821854-64c4dbe0-6fd4-4b01-9759-88899733f8a3.png">

#### Steps to reproduce:

1. Inatall Firebase via Swift Package Manager, and select `Firestore` and `FirebaseFirestoreSwift`

**Comment by paulb777** [comment]
This may be an Xcode cache issue. Please try cleaning and rebuilding.
