### ISSUE TITLE
The code signature version is no longer supported. Firebase no supported xcframework

### ISSUE THREAD

**Issue by bruce-ios** [firebase/firebase-ios-sdk#8667]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * MacOS version:  11.6
  * Xcode version:  12.5.1
  * iOS version: 15.0
  * Firebase SDK version: 8.7.0
  * Installation method: Carthage
  * Carthage version: 0.38.0
  * Firebase Component: 
<img width="737" alt="截圖 2021-09-18 21 35 45" src="https://user-images.githubusercontent.com/86638966/133890748-cb621222-81fe-4a9b-aafe-9353fc55c277.png">

#### Steps to reproduce:

I use `carthage update --platform iOS --use-xcframeworks`
And find the Firebase alse `.framework`, not xcframework.
Next when I run in real device and got an error. 
```
Unable to install "xxx"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620375
User Info: {
    IDERunOperationFailingWorker = IDEInstalliPhoneLauncher;
}
--
The code signature version is no longer supported.
Domain: com.apple.dt.MobileDeviceErrorDomain
......
......
```

When I do not embed Firebase.framework and run my device, it's work fine. 
But my crashlytic report don't get any crash error data in the firebase console.

When I embed Firebase.framework and run in simulator,
I can get the crash error data in the firebase console. 

How to fix this issue?

**Comment by paulb777** [comment]
`Firebase.framework` should not be embedded. See the `Delete Firebase.framework from the Link Binary With Libraries Build Phase.` step at https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md

Please review related issues or open another issue if you're still having trouble with Crashlytics when it is excluded.
