### ISSUE TITLE
Crash with null reason in NSException doesn't appear on the dashboard

### ISSUE THREAD

**Issue by RishatShamsutdinov** [firebase/firebase-ios-sdk#8671]
### Step 1: Describe your environment

  * Xcode version: 12.5.1
  * Firebase SDK version: 8.6.0
  * Installation method: `CocoaPods`
  * Firebase Component: Crashlytics

#### Steps to reproduce:

Throw a NSException with null reason and this crash will not appear on the dashboard.

#### Relevant Code:

```
@throw [NSException exceptionWithName:@"SyntheticCrash" reason:nil userInfo:nil];
```

**Comment by rizafran** [comment]
Hi @RishatShamsutdinov, per checking, it seems that the Firebase Support team is currently handling and investigating your issue. I'll be closing this now so you can continue getting updates from them. Thanks.
