### ISSUE TITLE
GoogleAppMeasurement code signature is invalid when running iPhone app built for iPhone iOS on M1 Mac. . 🔴 NOT MAC CATALYST!! 🔴

### ISSUE THREAD

**Issue by KyLeggiero** [firebase/firebase-ios-sdk#8681]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 12.4 (12D4e)
  * Firebase SDK version: 7.11.1
  * Installation method: `Swift Package Manager`
  * Firebase Component: Crashlytics, GoogleAppMeasurement

#### Steps to reproduce:

0. Using a Mac with an M1 SoC
1. Create an Xcode project which targets iOS on iPhone. **🔴 NOT MAC CATALYST!! 🔴**
2. Include the Firebase package in that Xcode project
3. Include `FirebaseAnalytics` and `FirebaseCrashlytics` in the iPhone Target
4. Select the iPhone Target as the target and "My Mac (Designed for iPhone)" as the run destination. **🔴 NOT MAC CATALYST!! 🔴**
5. Run the project

##### Expected result:

6. The app runs in an iPhone-size window on the Mac

##### Actual result:

6. The following error dialog appears:

![A screenshot of the dialog.](https://i.imgur.com/uR2G6OB.png)

The dialog above reads:

> APP NAME Needs To Be Updated. The developer of this app needs to update it to work with this version of macOS.
Failed to verify code signature of /var/db/appinstalld/Library/Caches/com.apple.mobile.installd.staging/temp.7n4Kth/extracted/APP NAME.app/Frameworks/GoogleAppMeasurement.framework : 0xe8008029 (The code signature version is no longer supported.)

#### Relevant Code:

No code required

**Comment by paulb777** [comment]
Firebase Analytics does not currently support macOS. See #1732

**Comment by KyLeggiero** [comment]
@paulb777 This isn't targeting macOS, though...

**Comment by paulb777** [comment]
The bug description says the target is "My Mac" which implies either Mac or Catalyst - neither of which is supported.

**Comment by KyLeggiero** [comment]
No, the target is "My Mac (Designed for iPhone)", meaning it's building an iOS app for iPhone, just the same as any other `ipa` that you would run on iPhone, and running that on a Mac. The build process, even down to the compiler and linker, and the final executable, are the exact same as when targeting a physical iPhone; it cannot tell the difference. It's not a Mac app, and it's not a Mac Catalyst app. It's an iPhone app, pure and simple. In fact, using this process, it's **impossible** to tell at compile time whether this will be running on a Mac, since it's 100% entirely a runtime determination; there's no precompiler flags anywhere which you could use to be able to tell that this is how the app will run.

Skip to 1:30 in this video to learn more: https://developer.apple.com/videos/play/wwdc2020/10114/

**Comment by paulb777** [comment]
I see. Sorry about the confusion. 

Perhaps something related to those binaries being built with Xcode 12.2?

**Comment by KyLeggiero** [comment]
It's alright; Apple didn't communicate this very well.

I encountered this when building with Xcode 12.4, since our app had a library which didn't link with 12.5. I've since removed that library and I can test on 12.5 or 12.2 if you think that will being us better information. Which would you prioritize?

**Comment by bdrelling** [comment]
May not be related, but I get build failures intermittently all the time still with `FirebaseAnalytics`/`GoogleAppMeasurement` when running `xcodebuild`. Breaks probably 20% of the time and I have to re-run a build.

Not sure what the deal is with this package in particular, but I don't build on an M1 and I don't build for Mac or Mac Catalyst. Based on other issues like https://github.com/firebase/firebase-ios-sdk/issues/7043 and https://github.com/firebase/firebase-ios-sdk/issues/7363, it feels like this package is really fragile.

**Comment by 1oo7** [comment]
`(The code signature version is no longer supported)` indicates that you're not using DER-encoded provisioning profiles. See https://developer.apple.com/documentation/xcode/using-the-latest-code-signature-format

**Comment by ncooke3** [comment]
Thanks for sharing @1oo7, I was not aware of those changes and that's good info to know! I'm going to mark this issue as closed since that article seems to explain that a re-sign is needed. @KyLeggiero, please ping this issue if you run into any more trouble.
