### ISSUE TITLE
Unable to Integrate Firebase on New Xcode13 via SPM.

### ISSUE THREAD

**Issue by lalkrishna** [firebase/firebase-ios-sdk#8683]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Xcode 13
  * Firebase SDK version: _____
  * Installation method: `Swift Package Manager`
  * Firebase Component: Auth, Core, Messaging

#### Steps to reproduce:

Unable to Integrate Firebase on New Xcode13 via SPM.
Latest version is 8.7, but SPM tries for 7.11.1 version.

Error Message: 

> artifact of binary target 'FirebaseAnalytics' failed download: The operation couldn’t be completed. (TSCBasic.FileSystemError error 1.)

**Comment by ryanwilson** [comment]
Thanks for the report @lalkrishna - I'm not sure why Xcode is only picking up the major version 7, but you can manually update the version number like I've circled here and I've confirmed that works.

Re: binary target failing to download, I've seen that happen with Xcode a few times and clearing my package cache and updating typically resolves it. Can you please try upgrading and let us know if you have any issues with it? Thanks!

![Manual_Version_Upgrade](https://user-images.githubusercontent.com/1097316/134373432-26a02b61-8f6c-4b01-bc21-18d3e862c2fc.png)
