### ISSUE TITLE
Firebase Storage for scripting broke after Xcode 13.0 (Swift 5.5) update

### ISSUE THREAD

**Issue by denandreychuk** [firebase/firebase-ios-sdk#8685]
I use Firebase Storage Package inside SPM script. After Xcode 13.0 update, especially Swift 5.5, i got

Cannot find type 'CheckedContinuation' in scope
Cannot find 'withCheckedThrowingContinuation' in scope

Inside AsyncAwait file (FirebaseStorageSwift)

**Comment by ryanwilson** [comment]
Thanks for the report - we have a fix ready in https://github.com/firebase/firebase-ios-sdk/pull/8676 that's planned for next week but I'll chat with the team about getting it out earlier. As a temporary workaround, pointing to `master` should work as the change has landed there.

**Comment by paulb777** [comment]
An easier workaround might be to manually change the one line in AsyncAwait.swift to `#if compiler(>=5.5) && canImport(_Concurrency)`.

Closing since the fix is staged for 8.8.0
