### ISSUE TITLE
-[FBLPromise HTTPBody]: unrecognized selector sent to instance 0x281829f50'

### ISSUE THREAD

**Issue by kapilkiwi** [firebase/firebase-ios-sdk#8687]
App gets crash randomly.

**Comment by paulb777** [comment]
Please send the full backtrace of the crash.

**Comment by kapilkiwi** [comment]
<img width="1253" alt="Screenshot 2021-09-22 at 10 28 49 PM" src="https://user-images.githubusercontent.com/16382672/134388333-aaae09f1-5606-4b68-8f20-c85340fa273b.png">

**Comment by kapilkiwi** [comment]
pod i am using

 pod 'Reachability', '~> 3.2'
  pod 'Alamofire', '~> 5.4.3'
  pod 'SDWebImage', '~> 5.11.0'
  pod 'IQKeyboardManagerSwift', '~> 6.5.6'
  pod 'DateToolsSwift', '~> 5.0.0'
  pod 'GoogleMaps', '~> 4.0.0'
  pod 'GooglePlaces','~> 4.0.0'
  pod 'GoogleMLKit/BarcodeScanning'
  pod 'GoogleMLKit/TextRecognition'
  pod 'SwiftyRSA','~> 1.6.0'
  pod 'OpenCV', '~> 2.4'
  pod 'SwiftLint', '~> 0.43.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Crashlytics'

**Comment by paulb777** [comment]
sorry about the trouble. Please see #7939 for suggestions. If you need more assistance, please add the full Podfile and Podfile.lock to the report
