### ISSUE TITLE
Firebase crashes when release build used in xCode 13

### ISSUE THREAD

**Issue by sarsonj** [firebase/firebase-ios-sdk#8693]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.0
  * Firebase SDK version: 8.7.0
  * Installation method: `CocoaPods`
  * Firebase Component: Core 

### [REQUIRED] Step 2: Describe the problem

When upgraded to XCode 13, the Firebase crashes in release build on iOS 15 on firebase initialisation `FirebaseApp.configure()`
<img width="1081" alt="Screenshot 2021-09-23 at 10 01 25" src="https://user-images.githubusercontent.com/925756/134473378-270f970b-598d-4bf4-8997-8c4328261275.png">

**Comment by foxware00** [comment]
I am seeing the same thing

**Comment by paulb777** [comment]
Thanks for the reports. What is the exception thrown? What version of CocoaPods is being used?

**Comment by foxware00** [comment]
@paulb777 It's a little hard to give more info my reports are all "Missing" when viewed in the console (dsyms are uploaded, it's only these crashes that are effected, the rest are successfully symbolicated0. I made an issue which might be more appropriate as @sarsonj 's issue might be different. My crashlytics crashes, seem to align with Testflight feedback which is correctly symbolicated. Looks like pref is locked and another thread crashes as a result.

As for cocoapods I am using `1.11.2`

Issue: #8710 

Please let me know if I should move this thread over to the other issue or if it's better in one place?

![Screenshot 2021-09-27 at 12 19 31](https://user-images.githubusercontent.com/4174528/134898733-a0045fe3-896e-438d-8a9b-24d4da66c5d5.png)

**Comment by paulb777** [comment]
OK, I'll close based on needing more info from @sarsonj  and @foxware00 's issue being discussed at #8710.  Feel free to comment with more info about the `topLevelVersion` crash and we can reopen.

**Comment by RajanMaheshwari** [comment]
I am having the same crash when the release scheme build is installed from Testflight. 

<img width="427" alt="Screenshot 2021-10-01 at 11 39 44 PM" src="https://user-images.githubusercontent.com/6380389/135667371-92fd625b-b852-449c-855f-a7b0563807e3.png">

Also the crash report:
[FirebaseCrash.txt](https://github.com/firebase/firebase-ios-sdk/files/7269277/FirebaseCrash.txt)

Probably crashing on initialization as soon as the app is launched

cocoapods - 1.11.2
