### ISSUE TITLE
Unused function 'processIsTranslated' warning

### ISSUE THREAD

**Issue by AaoIi** [firebase/firebase-ios-sdk#8694]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13,12
  * Firebase SDK version: 8.7
  * Installation method: `CocoaPods `
  * Firebase Component: FirebaseDynamicLinks

#### Steps to reproduce:

Building the project will result to show this warning since 8.6 SDK.

#### Relevant Code:

Pods/FirebaseDynamicLinks/FirebaseDynamicLinks/Sources/FIRDLJavaScriptExecutor.m:158:12: 
Unused function 'processIsTranslated'

**Comment by paulb777** [comment]
@AaoIi  Thanks for the report. I've staged a fix in #8696 that will go out in the next release or two.
