### ISSUE TITLE
Deeplink from Firebase Invite not coming through for New Install

### ISSUE THREAD

**Issue by richardliveraise** [firebase/firebase-ios-sdk#870]
* Xcode version: 9.2
  * Firebase SDK version: 4.8.1
  * Firebase Component: Firebase Invites
  * Component version: 2.0.2

#### Steps to reproduce:

1. Send app invite via Firebase Invite
2. Open the invitation link from email
3. Link redirect to app store to download
4. Open app
5. Received this: <app bundle id>://google/link/?dismiss=1&is_weak_match=1

Note that if I generated the link from Firebase Dynamic Links, it works (deep link is passed after new install). Only Firebase Invite link not working. Thanks!

**Comment by morganchen12** [comment]
Is there a difference between the links Invites and Dynamic Links generates?

**Comment by richardliveraise** [comment]
@morganchen12 : Yes. The Invites URL is longer and has extra /i/

Dynamic Links URL:
<My Dynamic Link Domain>/GUNJ6JvHtwq5KyCp2
Invites URL:
<My Dynamic Link Domain>/i/209151496987-f4f2b971-c929-465d-b4d5-f0c362964e1f

Also, with the dynamic links url, we can easily debug with adding ?d=1, I can't do the same with invites url.
This issue is only happening on iOS, Android was able to retrieve the data after install

**Comment by morganchen12** [comment]
Got it. This is most likely a bug on our end. I can't provide a timeline for a fix unfortunately.

**Comment by richardliveraise** [comment]
@morganchen12 : Any idea why it works on Android but not iOS ?

**Comment by PeeGee85Spil** [comment]
@richardliveraise Deferred deeplinks are handled differently on iOS and Android. Apparently the Google Play store can "hold" a deeplink for an app and pass the link after the app is installed. For Apple there is no such mechanism so developers have to store some identifying information on a back-end the moment the user clicks on a link, then on app start send that same identifying information to see if a deeplink was clicked by this user. That's how I understand it anyway, so a big difference between platforms.

**Comment by paulb777** [comment]
FirebaseInvites has been deprecated and we don't plan to fix this.

More at https://firebase.google.com/docs/invites/deprecation
