### ISSUE TITLE
xcode 13 presents multiple warnings using SPM

### ISSUE THREAD

**Issue by chrisvanbuskirk** [firebase/firebase-ios-sdk#8703]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.0
  * Firebase SDK version: Latest
  * Installation method: Swift Package Manager
  * Firebase Component: Crashlytics, Analytics

### [REQUIRED] Step 2: Describe the problem

Multiple warnings in xcode 13 for several firebase packages.  

#### Steps to reproduce:

What happened? How can we make the problem occur?

Adding SPM in xcode 13

This could be a description, log/console output, etc.

Warnings

firebase-ios-sdk
Invalid Exclude '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/firebase-ios-sdk/Firestore/core/src/api/input_validation_std.cc': File not found.Invalid Exclude '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/firebase-ios-sdk/Firestore/core/src/util/hard_assert_stdio.cc': File not found.Invalid Exclude '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/Data': File not found.Invalid Exclude '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/Protos': File not found.

GoogleDataTransport
Invalid Exclude '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/GoogleDataTransport/GoogleDataTransport/README.md': File not found.

GoogleUtilities
Invalid Exclude '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/GoogleUtilities/GoogleUtilities/README.md': File not found.Invalid Source '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/GoogleUtilities/GoogleUtilities/SceneDelegateSwizzler': File not found.Invalid Source '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/GoogleUtilities/GoogleUtilities/Common/*.h': File not found.

abseil-cpp-SwiftPM
Invalid Exclude '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/abseil-cpp-SwiftPM/absl/base/internal/exception_testing.h': File not found.Invalid Exclude '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/abseil-cpp-SwiftPM/absl/container/internal/unordered_map_lookup_test.h': File not found.Invalid Exclude '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/abseil-cpp-SwiftPM/absl/container/internal/unordered_set_constructor_test.h': File not found.Invalid Exclude '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/abseil-cpp-SwiftPM/absl/types/internal/conformance_testing.h': File not found.Invalid Exclude '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/abseil-cpp-SwiftPM/absl/container/internal/unordered_map_modifiers_test.h': File not found.Invalid Exclude '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/abseil-cpp-SwiftPM/absl/container/internal/hash_generator_testing.h': File not found.Invalid Exclude '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/abseil-cpp-SwiftPM/absl/base/internal/exception_safety_testing.h': File not found.Invalid Exclude '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/abseil-cpp-SwiftPM/absl/container/internal/unordered_set_members_test.h': File not found.Invalid Exclude '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/abseil-cpp-SwiftPM/absl/container/internal/unordered_map_constructor_test.h': File not found.Invalid Exclude '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/abseil-cpp-SwiftPM/absl/base/internal/inline_variable_testing.h': File not found.Invalid Exclude '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/abseil-cpp-SwiftPM/absl/container/internal/unordered_set_modifiers_test.h': File not found.Invalid Exclude '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/abseil-cpp-SwiftPM/absl/hash/hash_testing.h': File not found.Invalid Exclude '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/abseil-cpp-SwiftPM/absl/container/internal/hash_policy_testing.h': File not found.Invalid Exclude '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/abseil-cpp-SwiftPM/absl/container/btree_test.h': File not found.Invalid Exclude '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/abseil-cpp-SwiftPM/absl/container/internal/unordered_map_members_test.h': File not found.Invalid Exclude '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/abseil-cpp-SwiftPM/absl/container/internal/unordered_set_lookup_test.h': File not found.

boringssl-SwiftPM
Invalid Exclude '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/boringssl-SwiftPM/.build': File not found.Invalid Exclude '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/boringssl-SwiftPM/src/crypto/trust_token/trust_token_test.cc': File not found.Invalid Exclude '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/boringssl-SwiftPM/.swiftpm': File not found.Invalid Exclude '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/boringssl-SwiftPM/src/crypto/fipsmodule/rand/fork_detect_test.cc': File not found.Invalid Source '/Users/administrator/Library/Developer/Xcode/DerivedData/checklist-edrbqekeytkxzyeixpdkenkbduvw/SourcePackages/checkouts/boringssl-SwiftPM/src/table': File not found.

**Comment by ryanwilson** [comment]
Hi there, these issues were fixed a couple of versions ago. We're seeing issues with Xcode 13 picking up the latest version of Swift packages. Can you please make sure you're on version 8.7.0 (the latest as of today) and see if the warnings are gone?

**Comment by chrisvanbuskirk** [comment]
@ryanwilson I have the exact version set to 8.7.0.  I am only seeing warnings in abseil, BoringSSL-GRPC and Google Utilities.  So that's less warnings, but still 3 of the packages are having issues.

**Comment by ryanwilson** [comment]
Since they're different repos, can you check the versions of those? boringSSL-SwiftPM should be version 0.7.2. abseil-cpp-SwiftPM should be version 0.20200225.4, and GoogleUtilities should be 7.5.2.

**Comment by chrisvanbuskirk** [comment]
Looks like the versions are not updated.

<img width="438" alt="Screen Shot 2021-09-27 at 10 05 36 AM" src="https://user-images.githubusercontent.com/3638007/134944666-ee37959c-77bc-45b4-af79-9a50e21492ab.png">

**Comment by ryanwilson** [comment]
Can you please try updating them by using Xcode's "File -> Packages -> Update to Latest Package Version"?

**Comment by chrisvanbuskirk** [comment]
Yes, that worked.  Closing...
