### ISSUE TITLE
‘GoogleUtilities/GULLoggerLevel.h’ file not found

### ISSUE THREAD

**Issue by AhmedRajib** [firebase/firebase-ios-sdk#8709]
## [REQUIRED] Step 1: Describe my environment
Xcode version: 12.5.1
Installation method: CocoaPods (1.11.2)

## [REQUIRED] Step 2: Describe the problem
Steps to reproduce:
I try to migrate Crashlytics using:

```
pod 'Firebase/Crashlytics'
```

Instead of:

```
pod 'Fabric'
pod 'Crashlytics'
```

But, I get an error.

<img width="1280" alt="Screenshot 2021-09-27 at 12 50 02 PM" src="https://user-images.githubusercontent.com/45696624/134860010-d715a9e3-2f6d-4429-9ce1-56ec38459ea1.png">

Thats my pod files 

```
  pod ‘Bolts’
  pod ‘ExpandingMenu’
  pod ‘AMPopTip’, ‘~> 3.5.0’
  pod ‘FirebaseCore’
  pod ‘Firebase/Database’
  pod ‘Firebase/Firestore’
  pod ‘Firebase/Auth’
  pod ‘Firebase/Storage’
  pod ‘Firebase/Invites’
  pod ‘Firebase/Messaging’
  pod ‘Firebase/Performance’
  pod ‘Firebase/Functions’
  pod ‘Firebase/Crashlytics’
  pod ‘GoogleUtilities’
  pod ‘FirebaseCoreDiagnostics’
  pod ‘GoogleDataTransport’
  pod ‘SDWebImage’, ‘~> 4.0’
  pod ‘SideMenuController’, :git => ‘https://github.com/cjlarsen/SideMenuController.git’
  pod ‘MBAutoGrowingTextView’
  pod ‘JVFloatLabeledTextField’
  pod ‘FMMosaicLayout’
  pod ‘ReadMoreTextView’, ‘~> 3.0.0’
  pod ‘NVActivityIndicatorView’, ‘~> 4.6.1’
  pod ‘FBSDKCoreKit’
  pod ‘FBSDKLoginKit’
  pod ‘FBSDKShareKit’
  pod ‘UPCarouselFlowLayout’
  pod ‘ImageViewer’, :git => ‘https://github.com/MailOnline/ImageViewer.git’, :tag => ‘5.1.0’
  pod ‘DZNEmptyDataSet’
  pod ‘HockeySDK’
  pod ‘BTNavigationDropdownMenu’, :git => ‘https://github.com/PhamBaTho/BTNavigationDropdownMenu.git’
  pod ‘FXPageControl’
  pod ‘IQKeyboardManagerSwift’, ‘~> 6.0.4’
  pod ‘Reveal-SDK’, :configurations => [‘Debug’]
  pod ‘ReachabilitySwift’, ‘4.3.0’
  pod ‘Helpshift’, ‘7.6.3-withCampaigns’
```

How may i solved this issues ,

**Comment by ryanwilson** [comment]
Sorry for the trouble @AhmedRajib, can you please share your `Podfile.lock` so we can see which versions are getting installed, and try clearing derived data and doing a clean build? We typically see this when Xcode is in a bad state.

**Comment by AhmedRajib** [comment]
> Sorry for the trouble @AhmedRajib, can you please share your `Podfile.lock` so we can see which versions are getting installed, and try clearing derived data and doing a clean build? We typically see this when Xcode is in a bad state.

thanks @ryanwilson 
Here is my podfile.lock text file

[https://docs.google.com/document/d/1Oq9-84vDzjSwDCNicZRpDoaKfDWBnZ7z-f-x4uEtb-8/edit?usp=sharing
](url)


i cleaned derived data , clean build folder and try to solved this problem this way but unsuccess 

[https://github.com/firebase/firebase-ios-sdk/issues/6462](url)

**Comment by ryanwilson** [comment]
Thanks. A couple of things I noticed: The Firebase version being pulled in is 6.X which is 2 major versions old now. Also `Firebase/Invites` is no longer supported (and is preventing the other Firebase SDKs from updating). We recommend updating to the latest Firebase version, or trying a combination of `pod deintegrate` and `pod update` with the existing versions if you can't update.
