### ISSUE TITLE
FIAM View stuck at run time only

### ISSUE THREAD

**Issue by maulikm235** [firebase/firebase-ios-sdk#8715]
![126745909-9ddf3c50-25f5-4381-9594-cf8732b51ff7](https://user-images.githubusercontent.com/69245102/135042483-33ea0406-9589-4ebf-b1eb-2fa9a03db5d8.png)

**Xcode 12.3
iOS 13+**

**pod 'Firebase/InAppMessaging' version 8.7.0**
install using a pod

steps to reproduce

_-add campaign in firebase dashboard with any button event like login event
-run the app in device or simulator iOS 13+
-when an event fires and your device/simulator is in debugging mode it will open perfectly and work perfectly
-now disconnect the device/simulator from debugging and try to get a new event with the login event, now as we are not in debugging mode the app will be stuck._

**the only demo is working, it is not working in a real app.**

[log.txt](https://github.com/firebase/firebase-ios-sdk/files/7242000/log.txt)
Please check this log file.

https://user-images.githubusercontent.com/69245102/129157031-419e7a8f-2d18-4bb5-b57f-8969dd875052.mov
also please see this video, this happens only when the application is not in debugging mode.

### Pod files
```
pod 'Firebase'
pod 'Firebase/Analytics'
pod 'Firebase/InAppMessaging'
pod 'Firebase/DynamicLinks'
pod 'Firebase/Crashlytics'
pod 'Firebase/Performance'
pod 'Firebase/RemoteConfig'
```
### Import Firebase
```
@_exported import Firebase
@_exported import FirebaseAnalytics
@_exported import FirebaseDynamicLinks
```
### Appdelegate
```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {        
	FirebaseConfiguration.shared.setLoggerLevel(.debug)
    FirebaseApp.configure()
    return true
}
```
### Viewcontroller
```
@IBAction func btnAddItem(_ sender: UIButton) {
Analytics.logEvent(AnalyticsEventAddToCart, parameters: [
                        AnalyticsParameterCurrency: displayCurrncySymbol,
                        AnalyticsParameterItemCategory: cell.arraySubItems[row].categoryId,
                        AnalyticsParameterItemID: cell.arraySubItems[row].id,
                        AnalyticsParameterItemLocationID: "\(GLocation.shared.cordinate.latitude),\(GLocation.shared.cordinate.longitude)",
                        AnalyticsParameterItemName: cell.arraySubItems[row].title,
                        AnalyticsParameterPrice: cell.arraySubItems[row].price,
                        AnalyticsParameterQuantity: cell.arraySubItems[row].itemCount ?? 0,
                        AnalyticsParameterValue: cell.arraySubItems[row].status
                        ])
}
```

**if there is nothing wrong with the code, then it should work, as I do not handle any view from the firebase, so it should be solved by the firebase team, As SDK handles every view then it is SDK responsibility.**

**Comment by morganchen12** [comment]
Hi @maulikm235, can you share your whole project?

**Comment by maulikm235** [comment]
> Hi @maulikm235, can you share your whole project?

I can give you anydesk id to check the project.

**Comment by morganchen12** [comment]
You can also email a zip to me at morganchen at google.com if it's easier.

**Comment by maulikm235** [comment]
> You can also email a zip to me at morganchen at google.com if it's easier.

I can not give you the source code, as is my company's policy. we can take a zoom call or anydesk whatever you prefer.

**Comment by maulikm235** [comment]
can we check with anydesk or zoom call?

> You can also email a zip to me at morganchen at google.com if it's easier.

**Comment by maulikm235** [comment]
> You can also email a zip to me at morganchen at google.com if it's easier.

can we take zoom call?

**Comment by rizafran** [comment]
Hi @maulikm235, just want to check if you have tried isolating the bug in a sample fresh app?
