### ISSUE TITLE
Messages not received after installing the app

### ISSUE THREAD

**Issue by muredan** [firebase/firebase-ios-sdk#8716]
Environment

  * Xcode version: Version 13.0 (13A233)
  * Firebase SDK version: 8.7.0
  * Installation method:  Swift Package Manager
  * Firebase Component: Messaging

Describe the problem

Steps to reproduce:

When the application starts for the first time (after installation), the app does not receive notifications send throw Firebase Messaging. After closing the app from the background and reopening it, I am receiving notifications. 
When I tested my app using Firebase v7.11.0, it worked properly after installation.

**Comment by paulb777** [comment]
We'll likely need a reproducible example to help. Does the problem occur for you with the [messaging quickstart](https://github.com/firebase/quickstart-ios/tree/master/messaging)?

**Comment by rizafran** [comment]
Thanks for reporting, @muredan. In this case, it looks like there's no need for an mcve/reproducible sample as I encountered the same issue.

Based on my findings, I tried reproducing it with the messaging quickstart using SPM and SDK version 8.7.0, but I didn't receive any notification after installing the app (I need to quit and reopen the app first to make it work). I also tried it on 7.11.0 with the same steps, but I received the message successfully.

**Comment by chliangGoogle** [comment]
hmmm I'm not able to reproduce the issue.  Assign to our oncall to take a look at.

**Comment by chliangGoogle** [comment]
I'm  still not able to reproduce. @rizafran Can you try out sample app to see if it works for you? https://github.com/firebase/firebase-ios-sdk/tree/master/FirebaseMessaging/Apps/Sample

**Comment by rizafran** [comment]
Hi @chliangGoogle, I just tried that sample app from firebase-ios-sdk, and it's working fine. I used the [messaging quickstart](https://github.com/firebase/quickstart-ios/tree/master/messaging) on my first repro, and I encountered the issue there.
