### ISSUE TITLE
Crashed: com.apple.main-thread EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x000000000000013b

### ISSUE THREAD

**Issue by sspogra** [firebase/firebase-ios-sdk#8721]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5.1
  * Firebase SDK version:8.6.1
  * Installation method: `CocoaPods 
  * Firebase Component: Core, Database, Firestore, Messaging, Storage

### [REQUIRED] Step 2: Describe the problem

```
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x000000000000013b
0
FirebaseFirestore
-[FSTListenerRegistration remove] + 4
1
AppName
<compiler-generated> - Line 4370872752
DbQuery.dispose() + 4370872752
2
AppName
<compiler-generated> - Line 4371630016
DataUploadManager.addUploadListener() + 4371630016
3
AppName
<compiler-generated> - Line 4371499784
closure #1 in AppDelegate.checkNetworkRechability() + 4371499784
4
Reachability
$s12ReachabilityAAC06notifyA7Changed33_40784B9DE2E4DD004D0E5525CB465FEDLLyyFyycfU_ + 164
14
UIKitCore
UIApplicationMain + 168
15
AppName
AppDelegate.swift - Line 21
main + 21
16
libdyld.dylib
start + 4
```

#### Steps to reproduce:
We are calling the dispose() function of below code when network connection reachable.

#### Relevant Code:

```
class DbQuery: NSObject {
    private var firebaseListener: ListenerRegistration?
    private var realtimeQuery: DatabaseQuery?
    private var realtimeRef:DatabaseReference?
    private var realtimeEventListener: UInt?
    
    init(listener: ListenerRegistration? = nil, query: DatabaseQuery? = nil , ref:DatabaseReference? = nil, realTimelistener: UInt? = nil) {
        firebaseListener = listener
        realtimeQuery = query
        realtimeRef = ref
        realtimeEventListener = realTimelistener
    }
    
    func dispose() {
        firebaseListener?.remove()
        firebaseListener = nil
        
        if realtimeEventListener != nil{
            realtimeQuery?.removeObserver(withHandle: realtimeEventListener ?? 0)
            realtimeRef?.removeObserver(withHandle: realtimeEventListener ?? 0)
        }else{
            realtimeQuery?.removeAllObservers()
            realtimeRef?.removeAllObservers()
        }
    }
}

    
    
```

**Comment by morganchen12** [comment]
Hi @sspogra, is this reproducible on the latest version of Firestore?

**Comment by sspogra** [comment]
@morganchen12 Unable to reproduce on latest firestore.

**Comment by paulb777** [comment]
@sspogra Thanks for checking. I'll close since the issue was likely fixed recently.
