### ISSUE TITLE
Seeing potential issue in GoogleDataTransport that is blocking unit tests from running on Xcode 13

### ISSUE THREAD

**Issue by brandtdaniels** [firebase/firebase-ios-sdk#8725]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: __13___
  * Firebase SDK version: __8.8___
  * Installation method: `**CocoaPods** | Carthage | Zip file | Swift Package Manager` (select one)
  * Firebase Component: __GoogleDataTransport___ (Auth, Core, Database, Firestore, Messaging, Storage, etc)

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

Several people on the internet/twitter are complaining that unit tests aren't running on Xcode 13. For others the solution was to update a 3rd party dependecy after reviewing the spindump file or taking samples from the simulator before the test runner times out.

While I was reviewing the spindump file, in my case, it appears to be related to GoogleDataTransport

                491  __52-[GDTCORUploadCoordinator uploadTargets:conditions:]_block_invoke + 535 (GDTCORUploadCoordinator.m:112,7 in GoogleDataTransport + 157303) [0x112324677] 1-491

I'm attaching a copy of the spindump for review.

[Bootstrap Hang_0_65A9B5E4-AD68-453C-A455-C53F5E93CF7C.spindump.zip](https://github.com/firebase/firebase-ios-sdk/files/7255703/Bootstrap.Hang_0_65A9B5E4-AD68-453C-A455-C53F5E93CF7C.spindump.zip)

**Comment by foxware00** [comment]
@brandtdaniels I think the issue lies in the Texture lib you're using. Please see this thread and see if it's helpful

https://github.com/TextureGroup/Texture/pull/2032

**Comment by brandtdaniels** [comment]
@foxware00 How were you able to come to this conclusion? Spindump files are not very easy to understand. 

I do see some mentions of Texture, but it doesn't look like anything significant.

```
      1    CA::OGL::Context::bind_image(unsigned int, CA::Render::Texture*, unsigned int, CA::OGL::TextureFilter, CA::OGL::TextureFilter, float, CA::OGL::TextureEdgeMode, CA::OGL::ContentsGeometry const*, float*, char const*) + 547 (QuartzCore + 486559) [0x7fff26c9dc9f] 74
                                                          1    CA::OGL::MetalContext::bind_image_impl(unsigned int, CA::Render::Texture*, unsigned int, CA::OGL::TextureFilter, CA::OGL::TextureFilter, float, CA::OGL::TextureEdgeMode, float*, char const*) + 609 (QuartzCore + 490359) [0x7fff26c9eb77] 74
                                                            1    CA::OGL::MetalContext::update_surface(CA::OGL::MetalImage*, CA::Render::Surface*, unsigned int, char const*) + 4560 (QuartzCore + 1852444) [0x7fff26deb41c] 74
                                                              1    -[BronzeMtlDevice newTextureWithDescriptor:iosurface:plane:] + 107 (AMDMTLBronzeDriver + 1156323) [0x7fff6dda74e3] 74
                                                                1    -[BronzeMtlTexture initIOSurfaceWithDevice:descriptor:iosurface:plane:field:] + 320 (AMDMTLBronzeDriver + 675477) [0x7fff6dd31e95] 74
                                                                  1    -[MTLIOAccelTexture initWithDevice:descriptor:iosurface:plane:field:args:argsSize:] + 813 (Metal + 77982) [0x7fff2835809e] 74
```

**Comment by foxware00** [comment]
Have you read through the issue I linked? Lots of people seeing the same. I've also got a spindump with a similar issue which I reported to Apple. There is also a link to an Apple forum link into which we go into more detail about a spindump.

There is a workaround on that thread, if that works. You'll know it's Texture and the same issue people are seeing. If not, then it's more likely something else in the spindump. Let me know if the workaround doesn't work and we can get into how to read spindumps.

**Comment by brandtdaniels** [comment]
I'll read through it. We're not using Texture directly, so I would have to determine what is using it.

**Comment by foxware00** [comment]
@brandtdaniels 

These are the lines that look very similar to the issues raises. 

 ```
501  ASInitializeFrameworkMainThread + 35 (Pendo + 1761119) [0x1176fcf5f] 1-501
 501  ??? [0x7fff20112ca5] 1-501
501  ??? [0x7fff20111a56] 1-501
501  __ASInitializeFrameworkMainThread_block_invoke + 69 (Pendo + 1761190) [0x1176fcfa6] 1-501
```

**Comment by brandtdaniels** [comment]
So that looks like it would be with Pendo

**Comment by brandtdaniels** [comment]
I have determined my issue to be with a Pendo dependency, which depends on a Facebook library, which may depend on Texture. I am closing this issue. Thank you for the help.
