### ISSUE TITLE
FR: Add an API to configure the URLSession

### ISSUE THREAD

**Issue by ilyathewhite** [firebase/firebase-ios-sdk#8727]
### Feature proposal

Add an API to configure the URLSession that is used by Firebase

* Firebase Component: _Storage____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)

If Firebase is used in an extension, right now there is no way to specify a shared container, and this is necessary when sending local files:

From Apple's extension programming guide:
If your app extension initiates a background NSURLSession task, you must also set up a shared container that both the extension and its containing app can access. Use the sharedContainerIdentifier property of the NSURLSessionConfiguration class to specify an identifier for the shared container so that you can access it later.

**Comment by moriax** [comment]
Hello Team,

any news about this Topic ?
Somebody already created a fork to make the "sharedContainerIdentifier" configurable via PLIST Entry:
https://github.com/blancham/firebase-ios-sdk/commit/f4b9dc4e9f033e16a2c7c21d1331c09db4a22b93
Without this change, its not possible to upload a file from IOS Share Extension. Is it somehow possible, that you can merge this change to the official repo? 
Should I create a extra issue for this ?

**Comment by paulb777** [comment]
We would need a PR, signed CLA, and approved review to merge the fork.

Otherwise, please adds thumbs-up to this FR to help us prioritize.

**Comment by chliangGoogle** [comment]
@ilyathewhite Thank you for filling the request. The Apple programming guide you linked is for sharing data with your containing app. The great thing about Firebase Storage is your extension can fetch data directly from backend without talking to your containing app. One great use case is like Independent watch app.

However currently Firebase Storage doesn't provided functionality to support sharing data between extensions and containing app, but what you can do is to create your own data sharing storage using app groups.

**Comment by nidegen** [comment]
@chliangGoogle Thanks for your comment. I do not quite get what you mean however. Does this mean one can use shared containers without configuring NSURL Sessions of Firebase Cloud Storage? My use case is that I want to upload data from the extension.

**Comment by chliangGoogle** [comment]
@nidegen You can [upload file using Firebase storage](https://firebase.google.com/docs/storage/ios/upload-files) from the extension. You do not need to setup a shared NSURL session.

**Comment by nidegen** [comment]
@chliangGoogle yes but I encounter the issue #8941 then... any suggestions how to fix that maybe?

**Comment by chliangGoogle** [comment]
Can you share with me a sample project how you use Firebase storage on extensions? You can send it to chliang@google.com

**Comment by nidegen** [comment]
Yes but It will take some time to create it. Meanwhile, this is the significant error log section I think:
```
2022-01-20 07:37:20.518719+0100 Share Dev[8262:52161] Task <AA40E6F5-767F-4EE7-B6C6-AA1E9DF19BA8>.<1> finished with error [-995] Error Domain=NSURLErrorDomain Code=-995 "(null)" UserInfo={_NSURLErrorRelatedURLSessionTaskErrorKey=(
    "BackgroundUploadTask <AA40E6F5-767F-4EE7-B6C6-AA1E9DF19BA8>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=BackgroundUploadTask <AA40E6F5-767F-4EE7-B6C6-AA1E9DF19BA8>.<1>}
2022-01-20 07:37:20.521535+0100 Share Dev[8262:51237] GTMSessionFetcher invoking fetch callbacks, data (null), error Error Domain=NSURLErrorDomain Code=-995 "(null)" UserInfo={_NSURLErrorRelatedURLSessionTaskErrorKey=(
    "BackgroundUploadTask <AA40E6F5-767F-4EE7-B6C6-AA1E9DF19BA8>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=BackgroundUploadTask <AA40E6F5-767F-4EE7-B6C6-AA1E9DF19BA8>.<1>}
An unknown error occurred, please check the server response.
An unknown error occurred, please check the server response.
```

**Comment by nidegen** [comment]
I found out how to fix the issue: use 'putData' instead of 'putFile'

https://stackoverflow.com/questions/57181574/swift-uploading-a-file-to-firebase-storage-from-a-share-extension

Would be nice to have a warning in the docs:)

**Comment by paulb777** [comment]
Planning to update docs for next release.
