### ISSUE TITLE
Password data is not encrypted

### ISSUE THREAD

**Issue by Nicepose** [firebase/firebase-ios-sdk#873]
I'm using authentication with email and password 
```swift 
Auth.auth().signIn(withEmail: email, password: password) { (user, error) in
```
but doing some security test with Burp Suite I noticed that the login/signup data are plaintext into headers.

<img width="769" alt="screen shot 2018-03-05 at 20 44 43" src="https://user-images.githubusercontent.com/16580320/36997306-7d9f905c-20b9-11e8-884a-0088e7dfc604.png">

**Comment by bojeil-google** [comment]
Hey @Nicepose, actually we don't send this in the header. It is sent in the POST body of the request.
Firebase Auth uses TLS/SSL encryption to ensure no eavesdropping on the request in flight.
The Firebase Auth backend will then hash and salt the password using SCRYPT.

**Comment by andermoran** [comment]
What if the request is being sent from a mobile device that has an SSL proxy configured? Couldn't an attacker who has installed a certificate on an iOS device be able to see this sensitive information? Seems like a big security concern.
