### ISSUE TITLE
FR: Support watchOS platform in xcframework, Carthage distribution

### ISSUE THREAD

**Issue by tiepvuvan** [firebase/firebase-ios-sdk#8731]
### Issue
Downloading frameworks from Firebase distribution (https://firebase.google.com/download/ios) is not included watchOS platform support.
watchOS support is included in SPM and Cocoapods. 

### Proposal
Add support watchOS in the xcframework.

**Comment by paulb777** [comment]
Thanks for the feature request. Our [ZipBuilder tool](https://github.com/firebase/firebase-ios-sdk/tree/master/ReleaseTooling) needs to be updated to generate a watchOS and watchOS simulator slice.

**Comment by asendra** [comment]
Is there any work being done on this front? I tried to generate them myself, but so far no luck. Currently we are using it through CocoaPods, which is working. But we are trying to migrate everything to SPM / XCFrameworks

**Comment by paulb777** [comment]
@asendra Your question is unclear. This issue is about binary distribution, and your question seems to be about SPM which supports watchOS for all the Firebase products that support it. Please open another issue to describe what isn't working.

**Comment by asendra** [comment]
I was talking about binary distribution, should not have mentioned SPM, sorry.
