### ISSUE TITLE
Catalyst 15.0 with Swift Package Manager: No such module 'FirebasePerformance'

### ISSUE THREAD

**Issue by rowungiles** [firebase/firebase-ios-sdk#8734]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 13.0 beta 5 (13A5212g)
  * Firebase SDK version: 8.8.0 (also tried 8.6.1)
  * Installation method: `Swift Package Manager`
  * Firebase Component: Performance
  * M1 Mac
  * Catalyst 15.0 (macOS Monterey) target

### [REQUIRED] Step 2: Describe the problem
With the above environment, building after placing an `import FirebasePerformance` results in an error `No such module 'FirebasePerformance'`.

Switching the target to be an iOS App on M1 and building, the module is found. Appears to be specific to Catalyst.

#### Steps to reproduce:
To build Catalyst 15.0 apps, Xcode 13.0 beta 5 is required.

Set project support to iPhone, iPad, Mac.

iOS deployment target to 15.0. macOS deployment target to 12.0.

Use Swift Package Manager to include FirebaseCrashlytics and FirebasePerformance 8.8.0.

Place `import FirebasePerformance` in a Swift file.

Set target to `Mac`. 

Build

Observe `No such module 'FirebasePerformance'`.

#### Relevant Code:
```
import FirebasePerformance
```

**Comment by paulb777** [comment]
Sorry, but FirebasePerformance does not yet support Catalyst. See https://firebase.google.com/docs/ios/learn-more#firebase_library_support_by_platform

**Comment by rowungiles** [comment]
Thank you for the status update and the link to the matrix @paulb777.  I hope the team reaches the roadmap goal of filling the support matrix soon.
