### ISSUE TITLE
Inconsistent behaviour of Dynamic Links on App Open

### ISSUE THREAD

**Issue by shaibt** [firebase/firebase-ios-sdk#875]
* Xcode version: 9.2
  * Firebase SDK version: 4.9.0
  * Firebase Component: Dynamic Links
  * Component version: 2.3.2

Have setup dynamic links for my project for both iOS and Android apps and all is working well expect for the following:

On iOS 10 device (10.3.2) I can observe:
1) When app is first opened after user receives a dynamic link, AppDelgate's `application:open:options:` function is called with the expected link
2) When app is in background and user hits dynamic link AppDelegate's `application:continue:restorationHandler` as expected
3) When app is closed and opened normally (no dynamic link) neither of the above functions is called.
This is all as expected from the docs

However on iOS 11 device (11.2.6):
1) When app is first opened after user receives a dynamic link, AppDelgate's `application:open:options:` function is called with the expected link
2) When app is closed and opened normally (no dynamic link) `application:open:options:` **is always called** with a url:  "my_custom_scheme://google/link/?dismiss=1&is_weak_match=1"	

According to documentation call to  `application:open:options:` should happen only after 1st time open after install. 
Now my code can handle this by ignoring the `nil` url returned by `dynamicLink(fromCustomSchemeURL: url)` but this is unexpected behaviour and I'm concerned about the predictability of user experience across devices and use cases as it is inconsistent.

Important to note that my dynamic link is configured with `efr=1` as its used primary on web landing pages.

Any insight would be appreciated. I don't know if this is an iOS compatibility problem, a device fingerprinting problem or otherwise

**Comment by morganchen12** [comment]
This looks like a bug on our end, but even if it's not, it's probably something we should be documenting.

**Comment by dmandar** [comment]
Sounds like your app had a pending DL. Am not able to repro it atm on 11.2.6. Is this always repro for you? Please reopen if still happening.

**Comment by dyegos** [comment]
Hi,

This issue is happening with me on iOS 11.4.2 and also iOS 10. I'm always getting "my_custom_scheme://google/link/?dismiss=1&is_weak_match=1" when the App is killed and I open it via dynamic link. How can we know where's the problem?
