### ISSUE TITLE
[FIRApp configure] opens app by different bundleID when called

### ISSUE THREAD

**Issue by adamduren** [firebase/firebase-ios-sdk#876]
### Describe your environment

  * Xcode version: 9.2
  * Firebase SDK version: 4.8.2
  * Firebase Component: Core / DynamicLinks
  * Component version: 4.0.14

### Describe the problem
I have a dev build as well as a prod build for my project that uses two separate Firebase projects. The prod build has a bundle ID of the following format: `com.adamduren.project` and the dev build: 'com.adamduren.project-dev'. They each have a separate `GoogleService-Info.plist`. Both Apps are installed on my devices & simulators. In the dev build if I call `[FIRApp configure]` and the prod build is installed on the device then the dev build is backgrounded and the prod app is opened. If I remove the call to configure this no longer happens.

#### Steps to reproduce:

The bug only presents with the presence of the `Firebase/DynamicLinks` pod installed. Simply removing the pod resolves the issue.

Some possible clues is that initially before I had two Firebase Projects. I had both apps configured under one Firebase Project (the now prod). I deleted the dev app and created a new Firebase Project for the dev build. Maybe there's a reference in Firebase that when it loads remote configuration it pulls data for the other build and attempts to open the app with the correct bundle identifier. Also, the problem goes away

#### Relevant Code:

N/A

**Comment by adamduren** [comment]
A workaround that appears to work for the time being is registering a new app with iTunes Connect and Firebase with a different bundle ID such as `com.adamduren.project-dev-2` although this is not desirable.

**Comment by dmandar** [comment]
Can you confirm that you have the correct entitlements in each of the apps?
