### ISSUE TITLE
Know when NSNumber is nil or zero.

### ISSUE THREAD

**Issue by NikKovIos** [firebase/firebase-ios-sdk#8768]
**Example**
We have two cases:
1) There are no setting in Firebase Config for key.
2) There is "0" in Firebase Config for key.

**Problem:**
With last change, that it's always NSNumber exists can't figure out is setting exist or just setted to "0".

**Want:**
Return optional value.

**Comment by karenyz** [comment]
Discussed with the team, the recommendation for now is to check [FIRRemoteConfigSource](https://firebase.google.com/docs/reference/ios/firebaseremoteconfig/api/reference/Enums/FIRRemoteConfigSource.html) which will indicate whether the value is user-defined or not (`FIRRemoteConfigSourceStatic` indicates no value exists)

Hope that helps!
