### ISSUE TITLE
crash  -[GDTCCTUploader uploadTarget:withConditions:] + 124 (GDTCCTUploader.m:124) 

### ISSUE THREAD

**Issue by 170warship** [firebase/firebase-ios-sdk#8780]
I found this crash only happend in ios 10 ,   and  80% in arm32 .

com.google.GDTCORUploadCoordinator
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000e1e56bec8

Crashed: com.google.GDTCORUploadCoordinator
0  libobjc.A.dylib                0x21704 objc_object::release() + 8
1  GoogleDataTransport            0x7654 -[GDTCCTUploader uploadTarget:withConditions:] + 124 (GDTCCTUploader.m:124)
2  GoogleDataTransport            0x17b54 __52-[GDTCORUploadCoordinator uploadTargets:conditions:]_block_invoke + 113 (GDTCORUploadCoordinator.m:113)
3  libdispatch.dylib              0x1200 _dispatch_call_block_and_release + 24
4  libdispatch.dylib              0x11c0 _dispatch_client_callout + 16
5  libdispatch.dylib              0xf444 _dispatch_queue_serial_drain + 928
6  libdispatch.dylib              0x49a8 _dispatch_queue_invoke + 652
7  libdispatch.dylib              0x1138c _dispatch_root_queue_drain + 572
8  libdispatch.dylib              0x110ec _dispatch_worker_thread3 + 124
9  libsystem_pthread.dylib        0x12c8 _pthread_wqthread + 1288
10 libsystem_pthread.dylib        0xdb4 start_wqthread + 4

================
Podfile.lock

- FBRetainCycleDetector (0.1.4)
  - FBSDKCoreKit (9.1.0):
    - FBSDKCoreKit/Basics (= 9.1.0)
    - FBSDKCoreKit/Core (= 9.1.0)
  - FBSDKCoreKit/Basics (9.1.0)
  - FBSDKCoreKit/Core (9.1.0):
    - FBSDKCoreKit/Basics
  - FBSDKLoginKit (9.1.0):
    - FBSDKLoginKit/Login (= 9.1.0)
  - FBSDKLoginKit/Login (9.1.0):
    - FBSDKCoreKit (~> 9.1.0)
  - FBSDKShareKit (9.1.0):
    - FBSDKShareKit/Share (= 9.1.0)
  - FBSDKShareKit/Share (9.1.0):
    - FBSDKCoreKit (~> 9.1.0)
  - Firebase/Analytics (7.9.0):
    - Firebase/Core
  - Firebase/Core (7.9.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 7.9.0)
  - Firebase/CoreOnly (7.9.0):
    - FirebaseCore (= 7.9.0)
  - Firebase/Crashlytics (7.9.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 7.9.0)
  - Firebase/Performance (7.9.0):
    - Firebase/CoreOnly
    - FirebasePerformance (~> 7.9.0)
  - FirebaseABTesting (7.11.0):
    - FirebaseCore (~> 7.0)
  - FirebaseAnalytics (7.9.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleAppMeasurement (= 7.9.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.0)
    - GoogleUtilities/MethodSwizzler (~> 7.0)
    - GoogleUtilities/Network (~> 7.0)
    - "GoogleUtilities/NSData+zlib (~> 7.0)"
    - nanopb (~> 2.30907.0)
  - FirebaseCore (7.9.0):
    - FirebaseCoreDiagnostics (~> 7.4)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/Logger (~> 7.0)
  - FirebaseCoreDiagnostics (7.9.0):
    - GoogleDataTransport (~> 8.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/Logger (~> 7.0)
    - nanopb (~> 2.30907.0)
  - FirebaseCrashlytics (7.9.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleDataTransport (~> 8.0)
    - nanopb (~> 2.30907.0)
    - PromisesObjC (~> 1.2)
  - FirebaseInstallations (7.11.0):
    - FirebaseCore (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/UserDefaults (~> 7.0)
    - PromisesObjC (~> 1.2)
  - FirebasePerformance (7.9.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - FirebaseRemoteConfig (~> 7.0)
    - GoogleDataTransport (~> 8.2)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/ISASwizzler (~> 7.0)
    - GoogleUtilities/MethodSwizzler (~> 7.0)
    - Protobuf (~> 3.12)
  - FirebaseRemoteConfig (7.11.0):
    - FirebaseABTesting (~> 7.0)
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - "GoogleUtilities/NSData+zlib (~> 7.0)"
  - FMDB (2.7.5):
    - FMDB/standard (= 2.7.5)
  - FMDB/standard (2.7.5)
  - FSPagerView (0.8.3)
  - GCDWebServer (3.5.4):
    - GCDWebServer/Core (= 3.5.4)
  - GCDWebServer/Core (3.5.4)
  - GCDWebServer/WebDAV (3.5.4):
    - GCDWebServer/Core
  - GCDWebServer/WebUploader (3.5.4):
    - GCDWebServer/Core
  - GoogleAppMeasurement (7.9.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.0)
    - GoogleUtilities/MethodSwizzler (~> 7.0)
    - GoogleUtilities/Network (~> 7.0)
    - "GoogleUtilities/NSData+zlib (~> 7.0)"
    - nanopb (~> 2.30907.0)
  - GoogleDataTransport (8.3.1):
    - GoogleUtilities/Environment (~> 7.2)
    - nanopb (~> 2.30907.0)
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/AppDelegateSwizzler (7.5.2):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (7.5.2):
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/ISASwizzler (7.5.2)
  - GoogleUtilities/Logger (7.5.2):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (7.5.2):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (7.5.2):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.5.2)"
  - GoogleUtilities/Reachability (7.5.2):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (7.5.2):
    - GoogleUtilities/Logger

**Comment by 170warship** [comment]
I found GDTCCTUploadOperation  "main" function change name to "start" can fixed this crash

**Comment by maksymmalyhin** [comment]
> I found GDTCCTUploadOperation "main" function change name to "start" can fixed this crash

@170warship thank you for your investigation! Yes, I think this is the issue. Based on the [NSOperation docs](https://developer.apple.com/documentation/foundation/nsoperation/1416837-start) `start` method must be used for async operations instead of `main` but the newer iOS versions appeared to be tolerant to this error. We will test and release a fix.
