### ISSUE TITLE
Documentation mentions non-existing constant 'kFIRMessagingRegistrationTokenRefreshNotification'

### ISSUE THREAD

**Issue by EddyVerbruggen** [firebase/firebase-ios-sdk#88]
[Documentation](https://firebase.google.com/docs/cloud-messaging/ios/client#monitor-token-generation) mentions: `kFIRMessagingRegistrationTokenRefreshNotification`, but I think it should be this one, which I found [in the code](https://github.com/firebase/firebase-ios-sdk/blob/31a2acb7497eaaeae38b7ceb17edcab09d7f2866/Firebase/Messaging/FIRMessagingConstants.m#L48): `kFIRMessagingInstanceIDTokenRefreshNotification`.

**Comment by rsattar** [comment]
Nice catch, @EddyVerbruggen! This is my fault. The notification name wasn't correctly written in the code. I'll be adding `kFIRMessagingRegistrationTokenRefreshNotification` to the source to match the docs. You can use `kFIRMessagingInstanceIDTokenRefreshNotification` for now. When I add the correct name, I'll mark this one as deprecated, and nudge people to move over to this name.

**Comment by EddyVerbruggen** [comment]
Awesome, thanks @rsattar!

**Comment by rsattar** [comment]
The change is in which has the correct constant. I'm going to close this issue for now, but FYI the change will be available in the next release of Messaging. Thanks again @EddyVerbruggen!
