### ISSUE TITLE
Storage SDK will crash when Swizzle URLSession.dataTask(with:completionHandler:)

### ISSUE THREAD

**Issue by alexliuf5** [firebase/firebase-ios-sdk#8801]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12
  * Firebase SDK version: 8.8.0
  * Installation method: CocoaPods
  * Firebase Component: Storage

#### Steps to reproduce:

Add some Swift code to swizzle URLSession.dataTask with completion, then make sure this function `swizzleURLSessionDataTask` is called to initialize method Swizziling feature
Then try to call Firebase storage API to upload a file to firebase.
Crash will happen
#### Relevant Code:

```
//Method swizzling in Swift 
extension URLSession {
    @objc func swizzledMethod(with request: URLRequest, completionHandler: @escaping (Data?, URLResponse?, Error?) -> Void) -> URLSessionDataTask {
        // Will only Intercept report endpoint
        if let url = request.url?.absoluteString, url.contains("report") {
            // do something here for this endpoint
        }

        return swizzledMethod(with: request, completionHandler: completionHandler)
    }

    private static let swizzleDesriptionImplementation: Void = {
            let originalMethod = class_getInstanceMethod(URLSession.self, #selector((URLSession.dataTask(with:completionHandler:)) as (URLSession) -> (URLRequest, @escaping (Data?, URLResponse?, Error?) -> Void) -> URLSessionDataTask))
            let swizzledMethod = class_getInstanceMethod(URLSession.self, #selector(swizzledMethod(with:completionHandler:)))
            if let originalMethod = originalMethod, let swizzledMethod = swizzledMethod {
            method_exchangeImplementations(originalMethod, swizzledMethod)
        }
    }()

    static func swizzleURLSessionDataTask() {
        _ = self.swizzleDesriptionImplementation
    }
}

```

Function that are used to upload data with Firebase Storage API

```
@objc func save(){
        let storage = Storage.storage(url:"gs://xxxx.appspot.com")
        // Create a root reference for result.json
        let storageRef = storage.reference()
        // Create a reference to the file we want to upload
        let resultRef = storageRef.child("iOS/testpath/" + "result.json")

        let data = Data(base64Encoded: "data")!
        let _ = resultRef.putData(data, metadata: nil) { (metadata, error) in
        guard let _ = metadata else {
                return
            }
        }
    }
```

Crash will happen on iOS 11.x, please see the screenshot
<img width="1040" alt="Screen Shot 2021-10-13 at 4 49 47 PM" src="https://user-images.githubusercontent.com/66632259/137210703-852e6a1d-8a1d-4307-ae47-6a5ac1c43b2e.png">
.

**Comment by maksymmalyhin** [comment]
@alexliuf5 From the first glance it looks like it is most likely a bug with the swizzling implementation. I'm pretty sure that Firebase Storage is not the only broken URLSession user, but rather the first discovered one. If Firebase Storage SDK works for you without swizzling then I unlikely see any reasonable actions from Firebase side. Please let us know if it is the case.

A general suggestion - I would recommend avoid using swizzling when possible, because it is almost impossible to implement without breaking other class users.

**Comment by maksymmalyhin** [comment]
@alexliuf5 Some swizzling have been used in Firebase and we keep discovering different issues when our implementation breaks the host app code and assumption. Currently we are trying to get rid of any swizzling to avoid the issues in the future. So my suggestion comes from our poor experience with swizzling. 

If you are interested, there is an implementation in Firebase Performance that seems somehow  similar to what you are trying to do (see [FPRNSURLSessionInstrument.m](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebasePerformance/Sources/Instrumentation/Network/FPRNSURLSessionInstrument.m) file). This implementation works fine in most of the cases but we keep discovering corner cases when it doesn't work as expected.

**Comment by maksymmalyhin** [comment]
I am going to close the ticket as it doesn't look like an issue on the Firebase SDK side. Feel free to file another if you have other problems with Firebase SDKs.
