### ISSUE TITLE
Crash inside RLMIsObjectSubclass when using Firebase and Realm together

### ISSUE THREAD

**Issue by alanf** [firebase/firebase-ios-sdk#8823]
Xcode version: 12.5.1 (now moved to 13.0 for versions moving ahead)
Firebase SDK version: 8.7.0
Installation method: CocoaPods
Firebase Component: Performance
Steps to reproduce:
What happened? How can we make the problem occur?

Adding performance instrumentation to a codebase with Realm causes the crash to sporadically occur, likely due to swizzling conflicts. We don't have any steps to reproduce unfortunately, we only see this in our Crashlytics reports.

Although we opened this issue before and closed it since it was reported with an old version of Cocoapods, we just saw this crash under [8.7.0](https://console.firebase.google.com/project/masterclass-production-apple/crashlytics/app/ios:com.masterclass.production/issues/d855d123dcef8a73915e5c0b39f31bda?versions=10.17.0%20(18075);10.17.0%20(17609)&time=last-seven-days&sessionEventKey=babfa8c5ec20440dba633228c7d9c5b8_1597823767907243993) as well (the link may not be accessible, but will help me find it again if need be).

The previously closed issue is [here](https://github.com/firebase/firebase-ios-sdk/issues/8639), and the Realm discussion is [here](https://github.com/realm/realm-cocoa/issues/5618)

Since this issue only manifests when the libraries are combined together, ideally the maintainers of each would find a fix together so users don't have to choose one library over the other :)

**Comment by visumickey** [comment]
I've been trying to reproduce this issue (atleast once) for a while now. But I'm unable to reproduce this issue. I picked up the [Realm task tracker sampler app](https://docs.mongodb.com/realm/tutorial/ios-swift/#std-label-ios-swift-tutorial-local) and integrated with Firebase Performance using Swift Package Manager.

When run on device or simulator for about few hundred runs, I'm unable to reproduce this. It might be very hard for us understand and provide a fix until we have a way to reproduce this issue (atleast once).

Can you please provide a sample app where you are able to reproduce this issue?

Also, if you have a detailed stack trace (all threads) showing Firebase performance, can you please share it? That would be greatly helpful for us head towards exploring this further.

**Comment by alanf** [comment]
@visumickey I unfortunately don't know how to repro this issue either. But I was able to attach full stack traces from Firebase here:

[Full crash logs of RLMUtil.hpp and RLMObject.mm.zip](https://github.com/firebase/firebase-ios-sdk/files/7542430/Full.crash.logs.of.RLMUtil.hpp.and.RLMObject.mm.zip)

**Comment by visumickey** [comment]
@alanf Thanks for sharing the stack traces. On a detailed look, we could not get anything obvious and trivially useful. So, we will continue to investigate this issue further. Considering the gnarliness of this issue, I guess it is going to take sometime for us to get to the bottom of it.

In addition to that, Realm is not one of the well supported libraries by Firebase Performance. So, we will take sometime to make sure we are creating this compatibility in the right way possible (Finding alternatives to swizzling). Please bear with us as we get to this soon.

**Comment by julianD77** [comment]
In case of any use, a similar ticket (now also closed) was raised [here](https://github.com/firebase/firebase-ios-sdk/issues/5469)

**Comment by alanf** [comment]
Unfortunately we did remove Firebase performance from our app since it was (along with Realm) a cause of our top crash. Since removing Firebase performance, we have not seen this crash occurring.

**Comment by jeremyjiang-dev** [comment]
It's sad to see you leaving. We will  make sure to support more libraries in the near future.
