### ISSUE TITLE
Cloud Messaging Push Notification Not working

### ISSUE THREAD

**Issue by rehannali** [firebase/firebase-ios-sdk#8845]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13
  * Firebase SDK version: 8.8.1
  * Installation method: `Swift Package Manager` (select one)
  * Firebase Component: `Messaging` (Auth, Core, Database, Firestore, Messaging, Storage, etc)

### [REQUIRED] Step 2: Describe the problem

Push notification is not working. I got bad URL error.

#### Steps to reproduce:

1. Install Firebase SDK install using SPM. 
2. Generate Auth key from Developer Account
3. Add key to Firebase account
4. Add plist to project
5. `FirebaseAppDelegateProxyEnabled` to `NO`
4. Initialize Firebase Project

#### Relevant Code:

> Appdelegate `didFinishLaunchingWithOptions`
```swift
FirebaseApp.configure()
FirebaseConfiguration.shared.setLoggerLevel(.min)
Messaging.messaging().delegate = self

UNUserNotificationCenter.current().delegate = self
            
let authOptions: UNAuthorizationOptions = [.alert, .badge, .sound]
UNUserNotificationCenter.current().requestAuthorization(
                options: authOptions,
                completionHandler: {_, _ in })
            
 application.registerForRemoteNotifications()
```

> Appdelegate `didRegisterForRemoteNotificationsWithDeviceToken`
```swift
Messaging.messaging().apnsToken = deviceToken
```

> Appdelegate `didReceiveRegistrationToken`
```swift
debugPrint("FCM : \(fcmToken ?? "")")
```

#### Logs

Logs can be find [here](https://pastebin.com/xeYx61Bn).

**Comment by rehannali** [comment]
> @rehannali are you able to reproduce this issue with the quickstart, or can you share a project that reproduces this issue?

Yes, i create new project and did exact same steps in demo project. Again got same error of bad URL.

P.S. now i resolved the issue of bad URL which is strange. I need to add certificate as well with auth key and got FCM token. But now I'm unable to get any notification even i can't get it from push notification console.

**Comment by hardikdevios** [comment]
I am having the same 
Xcode 13 iOS 15, It's broken now.
The same code working perfectly for Firebase 7 SDK but seems like with SPM something is not right.

**Comment by morganchen12** [comment]
@rehannali are you able to receive notifications sent directly via APNs (without FCM)?

**Comment by rehannali** [comment]
@morganchen12 It is working now. I didn't the exact issue but a few days back, it worked automatically without modifying it.
