### ISSUE TITLE
In-App Message doesn't handle a links

### ISSUE THREAD

**Issue by kolosov507** [firebase/firebase-ios-sdk#8870]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5.1
  * Firebase SDK version: 8.8.0
  * Installation method: `CocoaPods`
  * Firebase Component: In-App Messaging

### [REQUIRED] Step 2: Describe the problem

I set up In-App Message in Firebase Console with a button that contains a link.
![Screenshot 2021-10-27 at 11 39 23](https://user-images.githubusercontent.com/17815149/139031934-94c4ac2e-acdd-4bc0-b00c-c8d5847bc011.png)

This In-App Message shows successfully in my app, but when I press the button this message only hides without opening the link in the appropriate app.

A similar situation with images that contain links, when you click on them, the browser does not open.

**Comment by kolosov507** [comment]
I caught this problem in React Native project.

This problem occurs when I add code for universal links to `project/ios/project/AppDelegate.m`:
```
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity
 restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
 return [RCTLinkingManager application:application
                  continueUserActivity:userActivity
                    restorationHandler:restorationHandler];
}
```
Which I take from a [React Navigation docs](https://reactnavigation.org/docs/deep-linking#ios).

https://github.com/kolosov507/firebase-in-app-messaging-test - this is an example of how this can be reproduced. The last commit breaks the action of the button.

**Comment by rizafran** [comment]
Thanks for the details, @kolosov507. I've noticed that you are using react-native libraries. This seems like a react-native integration issue. With this, I'll be closing the issue as this might be better to report on https://github.com/invertase/react-native-firebase/issues.
