### ISSUE TITLE
Release artifacts not include a LICENSE file

### ISSUE THREAD

**Issue by thii** [firebase/firebase-ios-sdk#8882]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.0
  * Firebase SDK version: 8.6.0
  * Installation method: Custom
  * Firebase Component: Analytics, Crashlytics, Messaging

### [REQUIRED] Step 2: Describe the problem

The release binaries (for example: https://dl.google.com/firebase/ios/analytics/5c7aebede686658a/FirebaseAnalytics-8.9.0.tar.gz) don't contain a LICENSE file. We need a LICENSE file for the compliance purpose. Please include a LICENSE file even its content is just `Copyright 2021 Google`.

**Comment by thii** [comment]
Can you please also include a LICENSE file with that same content? We don't use CocoaPods, only take the URLs from the podspecs and integrate them manually.

**Comment by paulb777** [comment]
Sorry, but we'll likely need a more compelling case to add complexity to our release process and duplicate information in the artifacts. Can you extract the copyright at the same time the zip is extracted?
