### ISSUE TITLE
crashes on FIRCLSContext.m -- FIRCLSContextInitialize --- __FIRCLSContextInitialize_block_invoke -- [NSString stringWithUTF8String:]

### ISSUE THREAD

**Issue by 170warship** [firebase/firebase-ios-sdk#8883]
![image](https://user-images.githubusercontent.com/2245961/139371014-d08830df-5b4b-402b-a2c1-9b2aaf0d5e28.png)

2021-10-29 10:48:32.563387+0800 YoHo[49412:21422570] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSString stringWithUTF8String:]: NULL cString'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010f06fbb4 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x0000000111adbbe7 objc_exception_throw + 48
	2   Foundation                          0x00000001124afe49 +[NSString stringWithBytes:length:encoding:] + 0
	3   FirebaseCrashlytics                 0x00000001105373f2 __FIRCLSContextInitialize_block_invoke.28 + 50
	4   libdispatch.dylib                   0x0000000119727a28 _dispatch_call_block_and_release + 12
	5   libdispatch.dylib                   0x0000000119728c0c _dispatch_client_callout + 8
	6   libdispatch.dylib                   0x000000011972b23f _dispatch_queue_override_invoke + 1466
	7   libdispatch.dylib                   0x000000011973ab44 _dispatch_root_queue_drain + 403
	8   libdispatch.dylib                   0x000000011973b5ec _dispatch_worker_thread2 + 196
	9   libsystem_pthread.dylib             0x000000011b29247a _pthread_wqthread + 244
	10  libsystem_pthread.dylib             0x000000011b291493 start_wqthread + 15
)
libc++abi: terminating with uncaught exception of type NSException

------------------------------------------------------
The code is:

FIRCLSContext.m --  FIRCLSContextInitialize  -- 

dispatch_group_async(group, queue, ^{
    NSString* rootPath = [NSString stringWithUTF8String:initData->previouslyCrashedFileRootPath];
    NSString* fileName = [NSString stringWithUTF8String:FIRCLSCrashedMarkerFileName];
    _firclsContext.readonly->previouslyCrashedFileFullPath =
        FIRCLSContextAppendToRoot(rootPath, fileName);
  });

-------------------------------------
The  initData->previouslyCrashedFileRootPath is  zero

I found the initData is a pointer to stack object,   if the stack is change by others,  the 'previouslyCrashedFileRootPath' may be zero or somethingelse.   

- FBRetainCycleDetector (0.1.4)
  - FBSDKCoreKit (9.1.0):
    - FBSDKCoreKit/Basics (= 9.1.0)
    - FBSDKCoreKit/Core (= 9.1.0)
  - FBSDKCoreKit/Basics (9.1.0)
  - FBSDKCoreKit/Core (9.1.0):
    - FBSDKCoreKit/Basics
  - FBSDKLoginKit (9.1.0):
    - FBSDKLoginKit/Login (= 9.1.0)
  - FBSDKLoginKit/Login (9.1.0):
    - FBSDKCoreKit (~> 9.1.0)
  - FBSDKShareKit (9.1.0):
    - FBSDKShareKit/Share (= 9.1.0)
  - FBSDKShareKit/Share (9.1.0):
    - FBSDKCoreKit (~> 9.1.0)
  - Firebase/Analytics (7.9.0):
    - Firebase/Core
  - Firebase/Core (7.9.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 7.9.0)
  - Firebase/CoreOnly (7.9.0):
    - FirebaseCore (= 7.9.0)
  - Firebase/Crashlytics (7.9.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 7.9.0)
  - Firebase/Performance (7.9.0):
    - Firebase/CoreOnly
    - FirebasePerformance (~> 7.9.0)
  - FirebaseABTesting (7.11.0):
    - FirebaseCore (~> 7.0)
  - FirebaseAnalytics (7.9.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleAppMeasurement (= 7.9.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.0)
    - GoogleUtilities/MethodSwizzler (~> 7.0)
    - GoogleUtilities/Network (~> 7.0)
    - "GoogleUtilities/NSData+zlib (~> 7.0)"
    - nanopb (~> 2.30907.0)
  - FirebaseCore (7.9.0):
    - FirebaseCoreDiagnostics (~> 7.4)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/Logger (~> 7.0)
  - FirebaseCoreDiagnostics (7.9.0):
    - GoogleDataTransport (~> 8.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/Logger (~> 7.0)
    - nanopb (~> 2.30907.0)
  - FirebaseCrashlytics (7.9.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleDataTransport (~> 8.0)
    - nanopb (~> 2.30907.0)
    - PromisesObjC (~> 1.2)
  - FirebaseInstallations (7.11.0):
    - FirebaseCore (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/UserDefaults (~> 7.0)
    - PromisesObjC (~> 1.2)
  - FirebasePerformance (7.9.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - FirebaseRemoteConfig (~> 7.0)
    - GoogleDataTransport (~> 8.2)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/ISASwizzler (~> 7.0)
    - GoogleUtilities/MethodSwizzler (~> 7.0)
    - Protobuf (~> 3.12)
  - FirebaseRemoteConfig (7.11.0):
    - FirebaseABTesting (~> 7.0)
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - "GoogleUtilities/NSData+zlib (~> 7.0)"

**Comment by 170warship** [comment]
- FirebaseCore (7.9.0):
    - FirebaseCoreDiagnostics (~> 7.4)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/Logger (~> 7.0)
  - FirebaseCoreDiagnostics (7.9.0):
    - GoogleDataTransport (~> 8.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/Logger (~> 7.0)
    - nanopb (~> 2.30907.0)
  - FirebaseCrashlytics (7.9.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleDataTransport (~> 8.0)
    - nanopb (~> 2.30907.0)
    - PromisesObjC (~> 1.2)
  - FirebaseInstallations (7.11.0):
    - FirebaseCore (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/UserDefaults (~> 7.0)
    - PromisesObjC (~> 1.2)
  - FirebasePerformance (7.9.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - FirebaseRemoteConfig (~> 7.0)
    - GoogleDataTransport (~> 8.2)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/ISASwizzler (~> 7.0)
    - GoogleUtilities/MethodSwizzler (~> 7.0)
    - Protobuf (~> 3.12)
  - FirebaseRemoteConfig (7.11.0):
    - FirebaseABTesting (~> 7.0)
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - "GoogleUtilities/NSData+zlib (~> 7.0)"

**Comment by morganchen12** [comment]
@170warship can you try the latest version?

**Comment by Overcot** [comment]
We also see this crash in the same place, but we are on 8.9.1 Firebase SDK Version
We only experienced it once on testFlight version of our app
<img width="386" alt="Screenshot 2021-11-28 at 14 11 00" src="https://user-images.githubusercontent.com/13967242/143765406-6a4e210b-35c1-4312-b534-62da46a7010e.png">
