### ISSUE TITLE
com.google.iid error -25244 - what does it mean?

### ISSUE THREAD

**Issue by wasauce** [firebase/firebase-ios-sdk#8884]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.1
  * Firebase SDK version: 8.7.0
  * Installation method: `CocoaPod
  * Firebase Component: Messaging

### [REQUIRED] Step 2: Describe the problem

Problem: I am attempting to generate a push token for my specific device and i am consistently getting the following error. Messaging.messaging().token error: The operation couldn’t be completed. (com.google.iid error -25244.)

#### Steps to reproduce:

I am running Firebase messaging and attempting to get a push token.

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Messaging.messaging().token error: The operation couldn’t be completed. (com.google.iid error -25244.)

This is only happening on one device (that we know of) if the same user uses a different device, no problem. Other users are not encountering this error.

#### Relevant Code:

```
    func sendTokenToServer(complete: ((_ log: String) -> Void)? = nil) {
        if PushNotificationManager.isNewFCMTokenSent || PushNotificationManager.isNewFCMTokenSending {
            return
        }
        PushNotificationManager.isNewFCMTokenSending = true
        var logStr = "\(Date()): Deleting current token now\n"
        Messaging.messaging().deleteToken { error in
            if let error = error {
                logStr += "\(Date()): Messaging.messaging().deleteToken error: \(error.localizedDescription)\n"
                DDLogError("Messaging.messaging().deleteToken: \(error.localizedDescription)")
                PushNotificationManager.isNewFCMTokenSending = false
            }
            logStr += "\(Date()): Getting new token now\n"
            Messaging.messaging().token { newToken, error in
                PushNotificationManager.isNewFCMTokenSent = true
                PushNotificationManager.isNewFCMTokenSending = false
                if let error = error {
                    DDLogError("Messaging.messaging().token: \(error.localizedDescription)")
                    logStr += "\(Date()): Messaging.messaging().token error: \(error.localizedDescription)\n"
                }
                if let token = newToken {
                    logStr += "\(Date()): Got new token \(token), sending to server\n"
                    DDLogInfo("sendTokenToServer fcmToken: \(token)")
                    JCKAPIClient.uploadFCMToken(token: token, identifier: Helper.serialNumber) { _ in
                    }
                }
                complete?(logStr)
            }
        }
    }
```

**Comment by wasauce** [comment]
@maksymmalyhin Thank you for the reply.

I removed the firebase keys from Keychain, deleted the app and re-installed and I am still running into this issue.

Note -- I am on a MacOSX machine. 10.15.7 (19H15)

2021-11-02 05:29:39 +0000: Messaging.messaging().token error: The operation couldn’t be completed. (com.google.iid error -25244.)

Do you have any new guidance, please?

**Comment by chliangGoogle** [comment]
@wasauce thank you for reaching out. Just in case we miss something, is this an iOS app or macOS/catalyst app?

**Comment by wasauce** [comment]
@chliangGoogle - this is a macOS app. Not catalyst.

**Comment by chliangGoogle** [comment]
You need to clean your keychain cache since you made some critical changes on certificates.
Go to Keychain Access -> login -> Passwords 
and make sure you removed all below items.

- [your firebase project number.*]
- [your app bundle ID]
- com.google.iid.checkin

**Comment by wasauce** [comment]
@chliangGoogle - thanks very much this worked!
