### ISSUE TITLE
Fatal Crash on ARKit with 8.9.0 (not with 8.8.0)

### ISSUE THREAD

**Issue by nidegen** [firebase/firebase-ios-sdk#8895]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.1
  * Firebase SDK version: 8.9
  * Installation method: `Swift Package Manager`
  * Firebase Component: not sure (Auth, Core, Database, Firestore, Messaging, Storage, etc)

#### Steps to reproduce:

Launch ARKit while using: Auth, Firestore Listeners

#### Relevant Code:

Unfortunately, I am not sure where the bug gets triggered. It seems to originate in some App Check code.

What I am doing is launch a view controller for an ARKit Session. If i go back to 8.8 it works without issues.

Also what I have noticed is that `tokenDidChangeNotificationName`'s notification observer gets called very often before the crash happens. I'd say a few dozen times per second.

![Screenshot 2021-11-01 at 15 30 56](https://user-images.githubusercontent.com/8779423/139694576-3ce1ae3e-b9c2-4714-8057-07dbe64461d2.png)
![Screenshot 2021-11-01 at 15 30 43](https://user-images.githubusercontent.com/8779423/139694581-87478890-a279-483c-bc96-858d0380dc3c.png)
`

**Comment by paulb777** [comment]
@nidegen Thanks for the report. The issue is likely related to the Firestore AppCheck integration that was introduced in 8.9.0

**Comment by nidegen** [comment]
That's what I was also thinking, but was unable to trace the exact origin. The often called AppCheck Notification Observer of `tokenDidChangeNotificationName` did always have `if (![[contents->app name] isEqual:notified_app_name]) { return }` return in FirebaseAppCheckCredentialsProvider.

**Comment by nidegen** [comment]
(Line 52 of firebase_app_check_credentials_provider_apple.mm)

**Comment by maksymmalyhin** [comment]
@nidegen Do you install App Check SDK as well?

I guess the issue may be due to `app_check == nil` [here](https://github.com/firebase/firebase-ios-sdk/blob/71fa12f4133d74eb6c972ffdc133e3ffdb4b8b69/Firestore/core/src/credentials/firebase_app_check_credentials_provider_apple.mm#L37)  so `nil` is passed as a notification name to the [method](https://developer.apple.com/documentation/foundation/nsnotificationcenter/1411723-addobserverforname) which means the class subscribes to basically all possible notifications.

cc @schmidt-sebastian

**Comment by nidegen** [comment]
Nope, I do not use it or link to it!

**Comment by schmidt-sebastian** [comment]
The underlying issue seems to be that the AppCheck callback is processing a notification whose `userInfo` is not an NSDictionary. While this does not conform to the NSNotification  API, this can easily happen in Objective C. 8.9.1 will start to ignore these notifications.

**Comment by paulb777** [comment]
@nidegen Firebase 8.9.1 is now available.  We would appreciate your confirmation that it fixes the issue.
