### ISSUE TITLE
InApp message is shown every new session (timestamp of the impression record is always 0 seconds)

### ISSUE THREAD

**Issue by alien190** [firebase/firebase-ios-sdk#8907]
* Xcode version: 13.1
  * Firebase SDK version: 8.8.0 (Flutter plugin firebase_in_app_messaging: ^0.5.0+11)
  * Installation method: `CocoaPods` 
  * Firebase Component: InAppMessaging

The problem description:

InAppMessages are shown every new session even though the scheduling is set to 'No more than one message every day'.

![2021-11-02_11-57](https://user-images.githubusercontent.com/32253712/139789967-576c6392-1df8-4ffe-ba4a-f40f2380d45f.png)

The problem is reasoned by incorrect timestamp of the impression record. It's always 0 seconds.
Here is the line from log:

`[Firebase/InAppMessaging][I-IAM270002] Insert the first impression record for message 3223183152453255168 with timestamp in seconds as 0.000000`

I think the bug is located in this line
https://github.com/firebase/firebase-ios-sdk/blob/6176fb1fc18d39d66ab181da2ce971e658668705/FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayExecutor.m#L320

This code: 
`[self.displayBookKeeper recordNewImpressionForMessage:messageID
                              withStartTimestampInSeconds:self.lastDisplayTime];`

probably should be fixed as:

`[self.displayBookKeeper recordNewImpressionForMessage:messageID
                              withStartTimestampInSeconds: [self.timeFetcher currentTimestampInSeconds ] ];`

**Comment by eldhosembabu** [comment]
Closing this issue since PR is merged.
