### ISSUE TITLE
Crashlytics upload-symbols error

### ISSUE THREAD

**Issue by aplr** [firebase/firebase-ios-sdk#8910]
### Environment

  * Xcode version: 13.1 (13A1030d)
  * Firebase SDK version: 8.9.0
  * Installation method: Swift Package Manager
  * Firebase Component: Crashlytics
  * macOS 12.0 (21A344)
  * MacBook Pro 2021 w/ M1 Pro

### Problem

```
rosetta error: /var/db/oah/279281322164224_279281322164224/7329775f7f0087d8f3266cf25f8b13cc9a42bb210fc6ab7aeb44a36ef7a71e4a/upload-symbols.aot: attachment of code signature supplement failed: 1
/Users/andreas/Library/Developer/Xcode/DerivedData/App-bfbjtawlpazjjnhfeynaesqndxej/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run: line 57: 81662 Trace/BPT trap: 5       "/Users/andreas/Library/Developer/Xcode/DerivedData/App-bfbjtawlpazjjnhfeynaesqndxej/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/upload-symbols" --build-phase --validate
```

#### Steps to reproduce:

The crashlytics build phase fails with the error above. I've already cleaned up DerivedData, reset the package cache and restarted Xcode.

Build phase script:

```
"${BUILD_DIR%Build/*}SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run"
```

**Comment by rizafran** [comment]
Hi @aplr, based on the [docs](https://firebase.google.com/docs/ios/installation-methods#crashlytics), it seems that your build phase script doesn't have '/' before the `SourcePackages`. Could you try using `${BUILD_DIR%/Build/*}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run` and see if that would fix the issue?

**Comment by grevolution** [comment]
I am also facing the same issue on my m1 MacBook pro.

**Comment by rizafran** [comment]
HI all, it looks like the issue is related to #8965.

**Comment by Djallil14** [comment]
I'm facing the same issue:
Macbook Air M1
Xcode 13.1
