### ISSUE TITLE
GoogleTagManager - App Killed in the Background 

### ISSUE THREAD

**Issue by ceichin-peya** [firebase/firebase-ios-sdk#8929]
### Step 1: Describe your environment

  * Xcode version:  Xcode 13
  * Firebase SDK version: See listed pods below
  * Installation method: CocoaPods
  * Firebase Component: GoogleTagManager

### Step 2: Describe the problem

Not sure if this is the channel to report a GTM bug, please let me know if not. 

We are trying to solve a bug: our app is being killed in the background. After a lot of testing, we see that the issue comes from the `GoogleTagManager` pod.

This happens because background tasks are being created, but `UIApplication.endBackgroundTask(_:)` are not being called afterwards properly, and, because of this, the operating system kills the app after 30 seconds. For more information, please refer to https://developer.apple.com/documentation/uikit/uiapplication/1623051-beginbackgroundtask. 

It's not straight forward to reproduce, but I will do my best to explain.

**Steps:**
1. Create a simple Xcode project with GoogleTagManager, GoogleAnalytics, Firebase:
```
  pod 'Firebase/Performance' (resolved to 8.9.0)
  pod 'Firebase/Core' (resolved to 8.9.0)
  pod 'Firebase/Analytics' (resolved to 8.9.0)
  pod 'Firebase/DynamicLinks' (resolved to 8.9.0)
  pod 'GoogleTagManager' (resolved to 7.4.0)
  pod 'GoogleAnalytics' (resolved to 3.20.0)
```

 - In AppDelegate didFinishWithOptions: `FirebaseApp.configure()`
 - Add Firebase's `GoogleService-Info.plist`. 
 - Add the Tag Manager container JSON (I used the one that our project uses, a new simple json didn't work to reproduce the issue).
 - I also added some code to easily see if the app is launching or if it was already launched.

2. Deploy app on a device. Stop Debugger.
3. Open app without debugger. 
4. Open any other app and come back. Repeat this for at least 30 times *quickly* (because it's not consistent, I can consistently reproduce this using a XCUITest in a simulator though, doing it only 2 times).
5. Quickly send the app to background and wait for more than 30 seconds.
6. Reopen app.

**Expected:** App should still be alive.
**Actual:** App re-launches. App was killed in the background.

**Log Error Message when app is killed:**
```Background task still not ended after expiration handlers were called: <_UIBackgroundTaskInfo: 0x6000034f0200>: taskID = 24, taskName = Called by BackgroundKillTest, from __37-[TAGDispatchScheduler checkHitStore]_block_invoke, creationTime = 16183 (elapsed = 30). This app will likely be terminated by the system. Call UIApplication.endBackgroundTask(_:) to avoid this.```

I have a video reproducing the issue. Also, a minimal example project as described above. But these contain some sensitive data… I might send it privately.

Thank you.

**Comment by paulb777** [comment]
Tag Manager support is [here](https://support.google.com/tagmanager/community?hl=en)

@tsunghung Is it useful to get issue reports here as well?

**Comment by tsunghung** [comment]
Yes, Tag Manager support is a better fit for GTM bug reports.

**Comment by paulb777** [comment]
Thanks @tsunghung. I'll close this one then.

**Comment by ceichin-peya** [comment]
In case someone has the same issue, reference: https://support.google.com/tagmanager/thread/133775212/googletagmanager-app-killed-in-the-background?hl=en
