### ISSUE TITLE
Already setted user properties not sent after analytics collection activation

### ISSUE THREAD

**Issue by sebbbbbb** [firebase/firebase-ios-sdk#8937]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.0 13A233
  * Firebase SDK version: 8.9.1
  * Installation method: CocoaPods 
  * Firebase Component: Analytics

#### Steps to reproduce:

Hello, i'm currently working on app with tracking consent and I have some issues with custom user properties.

We are using `FIREBASE_ANALYTICS_COLLECTION_ENABLED` with `NO`value in App .plist since consent is not given when user is doing a fresh install.

When user launch the app for the first time and accept consent, we enable tracking with `Analytics.setAnalyticsCollectionEnabled(true)` method. 
After that, even if hits are correctly sent we have an issue : previously setted (before consent change) custom user properties are not sended it look like they were erased.
If app is killed then restarted user property are correctly sended.

I was able to fix the issue by setting user properties again after analytics collection activation, but I think it would be easier if Analytics SDK could handle this case.

**Comment by rizafran** [comment]
Hi @sebbbbbb, it seems that your use case is an intended behavior. If the value of `FIREBASE_ANALYTICS_COLLECTION_ENABLED` is `NO`, then the entire analytics collection won't work and not just the specific user property. With this, your user property will send after enabling the `FIREBASE_ANALYTICS_COLLECTION_ENABLED`. You may check this [page](https://firebase.google.com/docs/analytics/configure-data-collection?platform=ios#disable_data_collection) for more info. Thanks.

**Comment by rizafran** [comment]
@sebbbbbb, I'll be closing this issue for now due to inactivity. If the issue persists, let me know so we can reopen the ticket and continue the investigation.
