### ISSUE TITLE
Uploading From iOS Share extension returns  NSURLErrorDomain Code=-995

### ISSUE THREAD

**Issue by nidegen** [firebase/firebase-ios-sdk#8941]
* Xcode version: 13.1
  * Firebase SDK version: 8.8.0
  * Installation method: Swift Package Manager
  * Firebase Component: Storage

#### Steps to reproduce:

From an iOS Share extension, I am starting a bunch of `putData` that I observe with a `FIRStorageUploadTask`. What follows is a bit confusing, as some uploads seem to work but the task observers do not get called, or maybe erroneously. If I understand right, the background task callbacks are sometimes pushed to the main app instead of the extension.

I am not sure if there is any way to make it work, but if not it would still be good for the API to behave more meaningfully.

**Comment by paulb777** [comment]
Related feature request at #8727

**Comment by paulb777** [comment]
Thanks @nidegen .  I'm not completely following - the OP says "I am starting a bunch of putData".  Did you actually mean `putFile` instead of `putData`?

**Comment by nidegen** [comment]
`putFile(url)` somehow throws the Error with code -995. Doing 'let data = try? Data(url)' and then `putData(data)` works as expected. I should have found the SO answer earlier, but it would still be nice to have a warning in the docs or during runtime:)

**Comment by nidegen** [comment]
note: I edited my comment and linked the "parent" SO article

**Comment by nidegen** [comment]
Answered by https://stackoverflow.com/a/39693142/5727960
