### ISSUE TITLE
crash on iOS 14 due to [[UIPasteboard generalPasteboard] hasURLs]

### ISSUE THREAD

**Issue by haozhutw** [firebase/firebase-ios-sdk#8942]
### Step 1: Describe your environment

  * Xcode version: 12.5.1
  * Firebase SDK version: 7.4.0
  * Installation method: `CocoaPods`
  * Firebase Component: DynamicLinks

#### Steps to reproduce:

app crashes 100% on iOS 14.7.0, iPad Pro (12.9-inch, 3rd generation). The crash is reported by Firebase Crashlytics

#### Relevant Code:

`FIRDLDefaultRetrievalProcessV2.m`

```
- (NSString *)retrievePasteboardContents {
  if (![self isPasteboardRetrievalEnabled]) {
    // Pasteboard check for dynamic link is disabled by user.
    return @"";
  }

  NSString *pasteboardContents = @"";
  if (@available(iOS 10.0, *)) {
    if ([[UIPasteboard generalPasteboard] hasURLs]) {
      pasteboardContents = [UIPasteboard generalPasteboard].string;
    }
  } else {
    pasteboardContents = [UIPasteboard generalPasteboard].string;
  }
  return pasteboardContents;
}
```

### Crash log
```
Fatal Exception: NSGenericException
*** -[NSURL isFileURL]: object was not initialized

Fatal Exception: NSGenericException
0  CoreFoundation                 0x101824 (Missing)
1  libobjc.A.dylib                0x140a8 (Missing)
2  Foundation                     0xbab0 (Missing)
3  UIKitCore                      0xbbcbec (Missing)
4  UIKitCore                      0xbbd050 (Missing)
5  MyApp                          0x51164 -[FIRDLDefaultRetrievalProcessV2 retrievePasteboardContents] + 211 (FIRDLDefaultRetrievalProcessV2.m:211)
6  MyApp                          0x50fb8 -[FIRDLDefaultRetrievalProcessV2 uniqueMatchLinkToCheck] + 177 (FIRDLDefaultRetrievalProcessV2.m:177)
7  MyApp                          0x50b8c -[FIRDLDefaultRetrievalProcessV2 retrievePendingDynamicLinkInternal] + 112 (FIRDLDefaultRetrievalProcessV2.m:112)
8  MyApp                          0x509ac -[FIRDLDefaultRetrievalProcessV2 javaScriptExecutor:completedExecutionWithResult:] + 90 (FIRDLDefaultRetrievalProcessV2.m:90)
9  MyApp                          0x51704 -[FIRDLJavaScriptExecutor handleExecutionResult:] + 86 (FIRDLJavaScriptExecutor.m:86)
10 MyApp                          0x51ae8 __55-[FIRDLJavaScriptExecutor webView:didFinishNavigation:]_block_invoke_2 + 125 (FIRDLJavaScriptExecutor.m:125)
11 WebKit                         0x357c94 (Missing)
12 WebKit                         0x585a1c (Missing)
13 WebKit                         0x357920 (Missing)
14 WebKit                         0x2e85bc (Missing)
15 WebKit                         0x5ee80 (Missing)
16 WebKit                         0x5e538 (Missing)
17 JavaScriptCore                 0xf6e084 (Missing)
18 JavaScriptCore                 0xf6f054 (Missing)
19 CoreFoundation                 0x83694 (Missing)
20 CoreFoundation                 0x835e0 (Missing)
21 CoreFoundation                 0x832cc (Missing)
22 CoreFoundation                 0x81c54 (Missing)
23 CoreFoundation                 0x811a8 (Missing)
24 HIToolbox                      0x2fb40 (Missing)
25 HIToolbox                      0x2f8b4 (Missing)
26 HIToolbox                      0x2f674 (Missing)
27 AppKit                         0x41660 (Missing)
28 AppKit                         0x40000 (Missing)
29 AppKit                         0x31e4c (Missing)
30 AppKit                         0x3878 (Missing)
31 AppKit                         0x2f2ad0 (Missing)
32 UIKitMacHelper                 0x4e18 (Missing)
33 UIKitCore                      0x2b1c (Missing)
34 MyApp                          0x55d0 main + 14 (main.m:14)
35 libdyld.dylib                  0x18430 (Missing)
```

### screenshot
![Screen Shot 2021-11-08 at 4 57 58 PM](https://user-images.githubusercontent.com/66658218/140712801-46397a59-7460-4443-8c52-6b29464aa90d.png)

**Comment by rizafran** [comment]
Thanks for reporting, @haozhutw. It seems that you're using an outdated SDK version. Could you try updating it first to the [latest one](https://firebase.google.com/support/release-notes/ios) (as this contains bug fixes and new features), and see if you'll still encounter the issue?

**Comment by haozhutw** [comment]
@rizafran  Thanks for your response. I've read the code of the latest SDK version, the relevant code that cause this crash is not changed, so updating the SDK to the latest one doesn't help. Have you really read my crash log and relevant code as attached?

**Comment by paulb777** [comment]
This issue looks very similar to #8565. Please double check the iOS version of the device

**Comment by haozhutw** [comment]
> This issue looks very similar to #8565. Please double check the iOS version of the device

You really don't read the report, I have noted that this crash happens on iOS 14.7.0 iPad Pro. Why do I have to check the iOS version?? #8565 doesn't resolve any problem, even through Firebase dropped support for iOS 9, but my app is built on iOS 11 and above, and this crash I reported here is happening on iOS 14.

**Comment by 1oo7** [comment]
@haozhutw When does the crash happen? I.e. how many seconds precisely between tapping the app icon, and the crash?

**Comment by paulb777** [comment]
Some additional questions: How many different devices does the crash occur on? Are the devices jail broken?

**Comment by haozhutw** [comment]
> Some additional questions: How many different devices does the crash occur on? Are the devices jail broken?

It's hard to tell whether the devices are jail broken, this report is from Firebase. This crash happens 11 times for only 1 user in last 90 days, so I think this should not be a big problem. We just need to keep an eye on this in case this issue happens to more users.

**Comment by morganchen12** [comment]
@haozhutw can you symbolicate the whole stack trace? The `NSGenericException` is unusual for a crash when fetching pasteboard contents.
