### ISSUE TITLE
SwiftUI/macOS Auth: "[App] wants to use your confidential information stored in 'com.firebase.FIRInstallations.installations' in your keychain." 

### ISSUE THREAD

**Issue by alelordelo** [firebase/firebase-ios-sdk#8950]
### Step 1: Describe your environment

Xcode version: Version 13.1 (13A1030d)
Firebase SDK version: 8.9.1
Installation method: Swift Package Manager
Firebase Component: Auth

#### Steps to reproduce:

What happened? How can we make the problem occur?
When build on MacOS, user sees permissions popup saying, "[App] wants to use your confidential information stored in 'com.firebase.FIRInstallations.installations' in your keychain." 

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by ncooke3** [comment]
Running certain Firebase SDKs on macOS will present this prompt if the SDK requests keychain access. This occurs because these platforms do not use a sandboxed keychain (like iOS) and instead use the primary keychain. To dismiss the prompt, enter the requested password and select `Always allow`. 

This prompt should only appear during development builds and shouldn't appear to a user using a release build of your app.

Usually, this prompt can be avoided by signing your application, could you verify that your app is signed? 
Also, are you seeing this prompt during SwiftUI preview loads or building/running the app?

**Comment by alelordelo** [comment]
_Running certain Firebase SDKs on macOS will present this prompt if the SDK requests keychain access._ 
Which ones? Maybe I could disable those...

_To dismiss the prompt, enter the requested password and select Always allow._
Tried that, but then  when the password is stored the App crashes every time I open again.

_This prompt should only appear during development builds and shouldn't appear to a user using a release build of your app._
I tested on 2 distributions, and both had those prompts:
TestFlight for MacOS
Direct  packaged distribution (notarised and signed)

_Usually, this prompt can be avoided by signing your application, could you verify that your app is signed?_
I'm using "Automatically manage signing". Is that what you mean?

_Also, are you seeing this prompt during SwiftUI preview loads or building/running the app?_
Building/running  and also distribution via TestFlight

**Comment by alelordelo** [comment]
Update @ncooke3 ,

After fixing this:
https://github.com/firebase/firebase-ios-sdk/issues/8947#event-5598755618

I then tested again via TestFlight for Mac, and the problem persists.
We are preparing App Store submission and need to get this fixed. Any idea what could be causing this?

**Comment by alelordelo** [comment]
**_What Firebase SDKs are you using in your app? Are you using Firebase Analytics?_**
<img width="620" alt="Screenshot 2021-11-11 at 16 12 21" src="https://user-images.githubusercontent.com/17708751/141321828-3878d307-b867-44d2-a3dd-bc38621e98bc.png">


**_Additionally, are you testing your mac app from TestFlight on the same machine you are developing it on?_**
Tested on different machine

.

**Comment by ncooke3** [comment]
Thanks for the info! Another question: do all the keychain prompts say "[App] wants to use your confidential information stored in *'com.firebase.FIRInstallations.installations'* in your keychain." or are you seeing other prompts with other messages.

**Comment by kamilpowalowski** [comment]
@alelordelo Hey, did you manage to fix that? I have the same issue (+ additionally keychain access prompt from Share Extension).

**Comment by alelordelo** [comment]
I don't remember, but believe  I fixed with this:
https://github.com/firebase/firebase-ios-sdk/issues/8947#event-5598755618

**Comment by kamilpowalowski** [comment]
@alelordelo Thank you. I don't have scenePhase used in the app, so that's not a solution for me. But thank you for your time.
