### ISSUE TITLE
Firebase/Performance crash in CoreFoundation CFDictionaryGetValue + 100

### ISSUE THREAD

**Issue by radhakrishnapai** [firebase/firebase-ios-sdk#8954]
### Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 6.27.0
  * Installation method: `CocoaPods`
  * Firebase Component: Performance

### Step 2: Describe the problem
Getting a crash when integrating pod  `pod 'Firebase/Performance', '= 6.27.0'`

Stack trace screenshot:
<img width="785" alt="Screenshot 2021-11-10 at 1 18 54 PM" src="https://user-images.githubusercontent.com/5534291/141072380-3b396e51-d4b6-46bf-917a-d7bc3b98cddb.png">

Stack trace log:
[Firebase-Performance-Crash.txt](https://github.com/firebase/firebase-ios-sdk/files/7510824/Firebase-Performance-Crash.txt)

#### Steps to reproduce:

What happened? How can we make the problem occur?
Integrate pod `pod 'Firebase/Performance', '= 6.27.0'`

**Comment by rizafran** [comment]
Thanks for reporting this, @radhakrishnapai. Your issue looks related on #6922, and the fix was included on **7.1.0**. Could try updating your SDK, and see if you'll still encounter the issue?

**Comment by radhakrishnapai** [comment]
@rizafran thanks for the update. I will check on your suggestion and get back if still facing the issue.
