### ISSUE TITLE
Firebase/RTDB crash in [FChildrenNode getPriority]

### ISSUE THREAD

**Issue by mortenbekditlevsen** [firebase/firebase-ios-sdk#8956]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5
  * Firebase SDK version: 7.4.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: Database

### [REQUIRED] Step 2: Describe the problem

We experience a crash in FirebaseWorker
EXC_BAD_ACCESS KERN_INVALID_ADDRESS

with the following stack trace:

Crashed: FirebaseWorker
0  libobjc.A.dylib                0x25c78 objc_retain + 8
1  POS                            0xccbfc0 -[FChildrenNode getPriority] + 2027588
2  POS                            0xccd980 -[FChildrenNode enumerateChildrenAndPriorityUsingBlock:] + 2034180
3  POS                            0xcd418c +[FSnapshotUtilities estimateSerializedNodeSize:] + 2060816
4  POS                            0xcd42c0 __49+[FSnapshotUtilities estimateSerializedNodeSize:]_block_invoke + 2061124
5  POS                            0xcdfddc __67-[FTreeSortedDictionary enumerateKeysAndObjectsReverse:usingBlock:]_block_invoke.58 + 2109024
6  POS                            0xcdd7f0 -[FLLRBValueNode inorderTraversal:] + 2099316
7  POS                            0xcdd798 -[FLLRBValueNode inorderTraversal:] + 2099228
8  POS                            0xcdd798 -[FLLRBValueNode inorderTraversal:] + 2099228
9  POS                            0xcdd798 -[FLLRBValueNode inorderTraversal:] + 2099228
10 POS                            0xcdd798 -[FLLRBValueNode inorderTraversal:] + 2099228
11 POS                            0xcdd798 -[FLLRBValueNode inorderTraversal:] + 2099228
12 POS                            0xcdd798 -[FLLRBValueNode inorderTraversal:] + 2099228
13 POS                            0xcdd824 -[FLLRBValueNode inorderTraversal:] + 2099368
14 POS                            0xcdfd1c -[FTreeSortedDictionary enumerateKeysAndObjectsReverse:usingBlock:] + 2108832
15 POS                            0xccdbd4 -[FChildrenNode enumerateChildrenUsingBlock:] + 2034776
16 POS                            0xccd9bc -[FChildrenNode enumerateChildrenAndPriorityUsingBlock:] + 2034240
17 POS                            0xcd418c +[FSnapshotUtilities estimateSerializedNodeSize:] + 2060816
18 POS                            0xc9cb40 -[FListenContainer includeCompoundHash] + 1833924
19 POS                            0xc8909c -[FPersistentConnection sendListen:] + 1753376
20 POS                            0xc8ae64 __37-[FPersistentConnection restoreState]_block_invoke + 1761000
21 CoreFoundation                 0x8da18 __NSDICTIONARY_IS_CALLING_OUT_TO_A_BLOCK__ + 24
22 CoreFoundation                 0x21b8 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 208
23 POS                            0xc8a810 -[FPersistentConnection restoreState] + 1759380
24 POS                            0xc876dc __62-[FPersistentConnection sendAuthAndRestoreStateAfterComplete:]_block_invoke + 1746784
25 POS                            0xc86334 -[FPersistentConnection onDataMessage:withMessage:] + 1741752
26 POS                            0xcca14c -[FConnection onDataMessage:] + 2019792
27 POS                            0xcca068 -[FConnection onMessage:withMessage:] + 2019564
28 POS                            0xccb520 -[FWebSocketConnection appendFrame:] + 2024868
29 POS                            0xccb5f4 -[FWebSocketConnection handleIncomingFrame:] + 2025080
30 POS                            0xce329c __31-[FSRWebSocket _handleMessage:]_block_invoke + 2122528
31 libdispatch.dylib              0x2a84 _dispatch_call_block_and_release + 32
32 libdispatch.dylib              0x481c _dispatch_client_callout + 20
33 libdispatch.dylib              0xc004 _dispatch_lane_serial_drain + 620
34 libdispatch.dylib              0xcc00 _dispatch_lane_invoke + 404
35 libdispatch.dylib              0x174bc _dispatch_workloop_worker_thread + 764
36 libsystem_pthread.dylib        0x37a4 _pthread_wqthread + 276
37 libsystem_pthread.dylib        0xa74c start_wqthread + 8

#### Steps to reproduce:

I'm afraid that we have not got enough knowledge about the issue yet, but we are continuing the investigation.

We hope that you are perhaps able to use the stack trace already.

#### Relevant Code:

The issue appears to be server initiated - as is evident in the trace.

**Comment by rizafran** [comment]
Hi @mortenbekditlevsen, please make sure that you're using the [latest SDK version](https://firebase.google.com/support/release-notes/ios) as this includes bug fixes and new features. If the issue persists, is it possible for you to share a sample app that reproduces the issue? Thanks.

**Comment by mortenbekditlevsen** [comment]
I'll close this as I can't in reasonable time get an update out to our customers with an updated sdk version. We are generally a bit cautious with upgrading dependencies as updating also introduces risk.
