### ISSUE TITLE
Remote Config Fetch persistently fails on iOS 15

### ISSUE THREAD

**Issue by andrewalexanderbalogh** [firebase/firebase-ios-sdk#8964]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 13.1 (13A1030d)
  * Firebase SDK version: 8.9.1
  * Installation method: `CocoaPods`
  * Firebase Component: Remote Config

### [REQUIRED] Step 2: Describe the problem
On iOS OS of \>= 15.*

Use of any of the Swift RemoteConfig fetch methods
- [fetch(completionHandler:)](https://firebase.google.com/docs/reference/swift/firebaseremoteconfig/api/reference/Classes/RemoteConfig#fetchcompletionhandler:)
- [fetch(withExpirationDuration:completionHandler:)](https://firebase.google.com/docs/reference/swift/firebaseremoteconfig/api/reference/Classes/RemoteConfig#fetchwithexpirationduration:completionhandler:)
- [fetchAndActivate(completionHandler:)](https://firebase.google.com/docs/reference/swift/firebaseremoteconfig/api/reference/Classes/RemoteConfig#fetchandactivatecompletionhandler:)

Now always returns an **error** in the **completionHandler**, and does NOT apply the Remote-Configs from the Firebase Server.

This is a print out of the error object of the completionHandler
```
print error
(Error?) $R0 = domain: "com.google.remoteconfig.ErrorDomain" - code: 8003 {
  _userInfo = 0x0000000282111680 1 key/value pair
}

print error?.localizedDescription
(String?) $R1 = "Failed to get installations token. Error : Error Domain=com.firebase.installations Code=0 \"Underlying error: A server with the specified hostname could not be found.\" UserInfo={NSLocalizedFailureReason=Underlying error: A server with the specified hostname could not be found., NSUnderlyingError=0x282f12610 {Error Domain=NSURLErrorDomain Code=-1003 \"A server with the specified hostname could not be found.\" UserInfo={_kCFStreamErrorCodeKey=8, NSUnderlyingError=0x282f127f0 {Error Domain=kCFErrorDomainCFNetwork Code=-1003 \"(null)\" UserInfo={_NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: en0, ipv4, dns, _kCFStreamErrorCodeKey=8, _kCFStreamErrorDomainKey=12}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <115E7856-5F69-4B04-8FA1-98EB1727F9AE>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(\n    \"LocalDataTask <115E7856-5F69-4B04-8FA1-98EB1727F9AE>.<1>\"\n), NSLocalizedDescription=A server with the specified hostname could not be found., NSErrorFailingURLStringKey=https://firebaseinstallation"
```

The status object of the completionHandler will always be;
- for  fetch(completionHandler:), fetch(withExpirationDuration:completionHandler:): `FIRRemoteConfigFetchStatus == .failure`
- for fetchAndActivate(completionHandler:)  `FIRRemoteConfigFetchAndActivateStatus == .error`

#### Steps to reproduce:

Running the code (see below) on iOS devices with OS \< 15  ( e.g. iOS 14.8.1 on iPhone XR )
there would be no issue, and the Remote Config fetch methods would work as expected

Running the code (see below) on iOS devices with OS \>= 15 ( e.g. iOS 15.1 on iPhone 8)
the problem would persistently occur. 

#### Relevant Code:
 
```swift
import Firebase


func fetchConfigs() -> Void {
    let remoteConfig = RemoteConfig.remoteConfig()
    remoteConfig.fetchAndActivate { status, error in
         if let error = error {
                print(error)
                print(error.localizedDescription)
         }

         switch status {
              case .successFetchedFromRemote:
                    // "The remote fetch succeeded and fetched data was activated."
                    break;
              case .successUsingPreFetchedData:
                     // "The fetch and activate succeeded from already fetched but yet unexpired config data. You can control this using minimumFetchInterval property in FIRRemoteConfigSettings."
                    break;
                case .error:
                    // "The fetch and activate failed."
                    break;
                @unknown default:
                    // "Some yet unmapped result"
                    break;
         }

    }
}

```

**Comment by 1oo7** [comment]
RemoteConfig is working just fine in our app, on iOS 15. Just thought I'd mention it.

**Comment by paulb777** [comment]
The problem could be related to FirebaseInstallations failing.   Are there any other relevant messages in the console log?

**Comment by andrewalexanderbalogh** [comment]
Testing again today on the original iPhone 8 device, and on another device updated to iOS 15.1 (iphone XR),
the issue is no longer reproducing for me.

I don't recall other messages shown in the log at the time.

I did publish new Remote Config changes through the Firebase Console, just before the errors began occurring.
Perhaps that had something to do with it.

**Comment by paulb777** [comment]
Glad it's working for you now.  I'll close for now, but feel free to comment or open a new issue if it reoccurs.
