### ISSUE TITLE
upload-dsyms requires Rosetta 2 on M1 machines

### ISSUE THREAD

**Issue by Yonom** [firebase/firebase-ios-sdk#8965]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.1
  * Firebase SDK version: 8.9
  * Installation method: `CocoaPods` (select one)
  * Firebase Component: Crashlytics

### [REQUIRED] Step 2: Describe the problem

As part of our builds, we are running a step involving calling `upload-dsyms`. Unfortunately, this binary is not universal and does not run on M1 macs without Rosetta 2

#### Steps to reproduce:

- try to run upload-dsyms on an M1 mac without Rosetta 2

```
line 57: /Pods/FirebaseCrashlytics/upload-symbols: Bad CPU type in executable
```

**Comment by kismet-** [comment]
Do we have the source for upload-symbols binary?

**Comment by samedson** [comment]
Hey folks,

I just pushed up a Universal upload-symbols with native M1/Arm support. If you'd like to try it out, download it here: [upload-symbols 3.10](https://github.com/firebase/firebase-ios-sdk/blob/upload-symbols-3-10/Crashlytics/upload-symbols)

**Comment by samedson** [comment]
Hello, the new version of upload-symbols is going out in the next release. Going to close this, but if you still have any issues please comment here!
