### ISSUE TITLE
Crash in GoogleCommon. [FIRApp configure] 

### ISSUE THREAD

**Issue by PavelGnatyuk** [firebase/firebase-ios-sdk#8966]
* Xcode version: 13.1

Notification Service Extension of the app crashes on start. The back trace shows that GoogleCommon goes to the StoreKit, to the payment queue. 

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000020
VM Region Info: 0x20 is not in any region.  Bytes before following region: 4342890464
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                   102db4000-102e1c000 [  416K] r-x/r-x SM=COW  ...viceExtension

Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [8457]
Triggered by Thread:  2

Thread 2 name:
Thread 2 Crashed:
0   libobjc.A.dylib               	0x000000019c0bdac0 objc_retain + 16 (objc-object.h:260)
1   AppStoreDaemon                	0x000000019e00e104 -[ASDStoreKitServiceBroker storeKitServiceWithErrorHandler:] + 60 (ASDStoreKitServiceBroker.m:47)
2   StoreKit                      	0x00000001a4d4fba8 -[SKPaymentQueue _checkServerQueue] + 156 (SKPaymentQueue.m:1052)
3   StoreKit                      	0x00000001a4d4ba90 -[SKPaymentQueue addTransactionObserver:] + 328 (SKPaymentQueue.m:318)
4   GoogleCommon                  	0x00000001046aba0c __46+[APMAnalytics startWithAppID:origin:options:]_block_invoke + 1532
5   libdispatch.dylib             	0x0000000187f63298 _dispatch_client_callout + 16 (object.m:559)
6   libdispatch.dylib             	0x0000000187f06f8c _dispatch_once_callout + 28 (once.c:52)
7   GoogleCommon                  	0x00000001046ab404 +[APMAnalytics startWithAppID:origin:options:] + 1160
8   GoogleCommon                  	0x000000010476790c +[FIRAnalytics startWithConfiguration:options:] + 532
9   GoogleCommon                  	0x0000000104676864 -[FIRApp configureCore] + 252
10  GoogleCommon                  	0x0000000104676554 +[FIRApp addAppToAppDictionary:] + 100
11  GoogleCommon                  	0x0000000104675cd0 +[FIRApp configureWithName:options:] + 704
12  GoogleCommon                  	0x000000010467594c +[FIRApp configureWithOptions:] + 96
13  GoogleCommon                  	0x00000001046758d8 +[FIRApp configure] + 124
14  VIBAnalytics                  	0x00000001034d42a8 specialized FirebaseEventsReporter.start(analyticsEnabled:) + 44 (FirebaseEventsReporter.swift:18)
15  NotificationServiceExtension  	0x0000000102dcc2cc Injector.init() + 1876 (Injector.swift:153)
16  NotificationServiceExtension  	0x0000000102de05dc Injector.__allocating_init() + 28 (ServiceExtensionDelegate.swift:26)

GOOGLE_ANALYTICS_REGISTRATION_WITH_AD_NETWORK_ENABLED as Boolean with value 0 added to the info.plist of the notification service extension. StoreKit framework added to the list of the linked library.  The crash still happens and appears pretty often on the App Store analytics.

**Comment by paulb777** [comment]
@PavelGnatyuk Thanks for the report. Firebase Analytics is not currently supported for extensions. See #2896.  However, this is the first report we've seen of a crash versus incorrect behavior. Please provide the information requested in the issue template including Firebase versions installed and installation method and we can check with the Analytics team.
