### ISSUE TITLE
FIRAuth.auth().currentUser.displayName returns nil

### ISSUE THREAD

**Issue by milligator** [firebase/firebase-ios-sdk#897]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.2
  * Firebase SDK version: 
Using Firebase (3.17.0)
Using FirebaseAnalytics (3.9.0)
Using FirebaseAuth (3.1.1)
Using FirebaseCore (3.6.0)
Using FirebaseDatabase (3.1.2)
Using FirebaseInstanceID (1.0.10)
Using FirebaseRemoteConfig (1.3.4)
Using FirebaseStorage (1.1.0)
Using GTMOAuth2 (1.1.6)
Using GTMSessionFetcher (1.1.13)
Using Google (3.1.0)
Using GoogleSignIn (4.1.2)

### [REQUIRED] Step 3: Describe the problem
While trying to link an anonymous user to a google account the displayName is nil while on registring a user with google account the displayName does exist. 
#### Steps to reproduce:

FIRAuth.auth()?.currentUser?.link(with: credentials, completion: { (user, error) in
 print(FIRAuth.auth().currentUser.displayName) //returns nil
})

FIRAuth.auth()?.signIn(with: credentials, completion: { (user, error) in
print(FIRAuth.auth().currentUser.displayName) //returns displayName
})

What happened? How can we make the problem occur?
App Crashes

**Comment by paulb777** [comment]
Does the issue occur with a recent Firebase 4.x?

**Comment by paulb777** [comment]
Closing for lack of recent activity. Please reopen if still an issue with >= Firebase 5.x
