### ISSUE TITLE
Firebase.Crashlytics FOr Xamarin Forms / MAUI

### ISSUE THREAD

**Issue by jrahma** [firebase/firebase-ios-sdk#8970]
### Feature proposal

* Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)

Describe your use case and/or feature request here.

A cross-platform package for Xamarin and MAUI.

Currently, we have to install iOS package and Android package separately in every Xamarin project but it will be great if you add Firebase.Crashlytics which will be installed on the PCL project without having to worry about installing again in every project and without we need to create project dependency or interface.

**Comment by samedson** [comment]
Hey @jrahma - thank you for the feature request. We don't currently have plans to support Xamarin. I think for Crashlytics to go this route, we'd want the rest of Firebase SDKs to come too.
