### ISSUE TITLE
Migrate FirebaseCore Private to a new FirebaseCoreInternal library

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#8973]
To enable Swift libraries to call internal methods like `registerInternalLibrary`

**Comment by paulb777** [comment]
Alternatively, we may want to move the public APIs to a Swift implemented library that depends on a FirebaseCoreObj, in which the current private headers are now public - but the FirebaseCoreObj is only supported for internal use.

**Comment by ryanwilson** [comment]
Pretty sure this is done in the `functions-swift-main` branch already.

**Comment by paulb777** [comment]
This is merged in the v9 branch. It will likely be renamed FirebaseCoreExtensionInternal
