### ISSUE TITLE
Como solucionar error 501 flutter

### ISSUE THREAD

**Issue by caporrass** [firebase/firebase-ios-sdk#8984]
Using the postman tool to verify the operation of the api with connection to posgrest throws me the following error.
`{
    "success": false,
    "message": "Error al Registar el usuario",
    "error": {
        "length": 145,
        "name": "error",
        "severity": "ERROR",
        "code": "42703",
        "position": "115",
        "file": "parse_target.c",
        "line": "1066",
        "routine": "checkInsertTargets"
    }
}`
how can I solve it?

**Comment by paulb777** [comment]
Please fill out the issue template and translate to English.
