### ISSUE TITLE
Manual logged screen_view events sometimes have screen_name - (not set)

### ISSUE THREAD

**Issue by Venteor** [firebase/firebase-ios-sdk#8988]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5.1
  * Firebase SDK version: 7.3.0
  * Installation method: CocoaPods 
  * Firebase Component: Core 

### [REQUIRED] Step 2: Describe the problem
Hello!
My project consist of obj-c and swift classes. 

I manually log screen_view event for my screens. I call this method in viewWillAppear or viewDidAppear like this:

```
@objc class MyAnalyticConstants: NSObject { 
    static let myScreenName = "AwesomeScreen"
}

class MyViewController: UIViewController {
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        MyAnalyticsClass().logScreenViewEvent(name: MyAnalyticConstants.myScreenName)
    } 
}

class MyAnalyticsClass {
    func logScreenViewEvent(name: String, parameters: [String: Any]? = nil) {
        var param = [String: Any]()

        if let parameters = parameters {
            param = parameters
        }

        param[AnalyticsParameterScreenName] = name
        logEvent(name: AnalyticsEventScreenView, parameters: param)
    }

    func logEvent(name: String, parameters: [String: Any]?) {
        analytics.logEvent(name, parameters: parameters)
    } 
}
```

I turned off automatic screenview reporting by setting FirebaseAutomaticScreenReportingEnabled to NO (Boolean) in the Info.plist. I use struct with static names for my screens.

However, sometimes I see (not set) value for "screen_view" event inside my google analytics path exploration for production. I can't catch this while using DebugView. 

I swizzled firebase method

```
 + (void)xxx_logEventWithName:(NSString *)name
          parameters:(nullable NSDictionary<NSString *, id> *)parameters {
[self xxx_logEventWithName:name parameters:parameters];
if ([name isEqualToString:@"screen_view"] && [parameters[@"screen_name"] length] <= 3) {
    NSLog(@"%@", @[][1]);
}
```
and jumped through app during 30 min. I didn't catch up crash. Any other ideas?

#### Steps to reproduce:

![image](https://user-images.githubusercontent.com/40053942/142639050-c84836a7-f934-430e-ba2d-ffeff1f223b8.png)

Also I have sometimes my custom events with parameters (not set).

I would really appreciate it, if somebody could help me to fix or explain it.

**Comment by rizafran** [comment]
Hi @Venteor. Based on my understanding, it seems like you're experiencing the "not set" value in your screen_views. You will get a (not set) value in your parameters if you've met the following conditions:

- A particular event is logged in previous versions of the app and the parameters were not yet supplied. This will result in "not set" values for those parameters.
- If the custom parameter is an empty string, it will be treated as (not set). Also note that the default value of the custom parameter is an empty string which will also be evaluated as (not set).

For now, you may try to double check your code implementation if you are satisfying the 2 conditions above. Also, considering that this is an intended behavior, eliminating the (not set) value is not possible as of the moment. Thanks.

**Comment by Venteor** [comment]
Hi @rizafran. Thaks you for your reply. Unfortunately the screenshot shows only one source - new app version. It means that all parameters are supplied. We have run regression tests during 2 days to catch up in what situation not_set could be provided by our code. Using swizzled Analytics method (it's illustrated in issue) we tried to catch the crash. However we didn't catch anything.
It seems like something in Analytics changes value for parameter "screen_name" in "screen_view" event to empty string. Or maybe "screen_view" are sent automatically (or duplicated) without parameters despite the fact that this behavior is disabled in info.plist.

**Comment by rizafran** [comment]
Thanks for the info, @Venteor. I noticed that you're still using an outdated SDK. Is it possible for you to update your SDK to the current one (as this includes bug fixes and new features), and see if that would fix the issue? Also, could you enable the debug mode, and double check if the `screen_view` has a value?

**Comment by Venteor** [comment]
I think we could update SDK after holidays. Everything is okay in debug mode.

**Comment by Venteor** [comment]
Hello! The issue is still reproducible. We are going to release new version of app in week with Firebase 8.10.0. I will share more information soon.
