### ISSUE TITLE
Cannot upload symbols for Crashlytics

### ISSUE THREAD

**Issue by KemalPajevic** [firebase/firebase-ios-sdk#8997]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.1
  * Firebase SDK version: 8.9.1
  * Installation method: `CocoaPods`
  * Firebase Component: Crashlytics
  * Target platform(s): `iOS`

### [REQUIRED] Step 2: Describe the problem

When trying to upload symbols as part of my project, I get the following error:
`File no longer exists at (null)`

#### Steps to reproduce:

I have added the GoogleService-Info.plist to the project. I have then added a run-script build phase with
```
"${PODS_ROOT}/FirebaseCrashlytics/run"
"${PODS_ROOT}/FirebaseCrashlytics/upload-symbols" -gsp "${PROJECT_DIR}/${PROJECT_NAME}/GoogleService-Info.plist" -p ios "${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}"
```

If I run `upload-symbols` with the `--debug` flag I get this output:
```
upload-symbols 3.9 build 28

Arguments:
[1mDebug mode enabled[0m
Google App ID: 1:966119265531:ios:debbab51630033a7
Platform: ios
DSYM Paths: ["/Users/kemal/Library/Developer/Xcode/DerivedData/JBKids-dhlisyvsnhmaqzerhebhvnqwehmm/Build/Products/Debug-iphonesimulator/JBKids.app.dSYM"]

Inspecting next path: /Users/kemal/Library/Developer/Xcode/DerivedData/JBKids-dhlisyvsnhmaqzerhebhvnqwehmm/Build/Products/Debug-iphonesimulator/JBKids.app.dSYM
Found dSYM at path: /Users/kemal/Library/Developer/Xcode/DerivedData/JBKids-dhlisyvsnhmaqzerhebhvnqwehmm/Build/Products/Debug-iphonesimulator/JBKids.app.dSYM
Begin processing dSYM at (null)
[31merror: Could not complete submission of dSYM at /Users/kemal/Library/Developer/Xcode/DerivedData/JBKids-dhlisyvsnhmaqzerhebhvnqwehmm/Build/Products/Debug-iphonesimulator/JBKids.app.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=2 "File no longer exists at (null)" UserInfo={NSLocalizedFailureReason=File no longer exists at (null)}[0m
```
As you can see, it seems to find the dSYM file at the correct location, but when it tries to process it something goes wrong.

**Comment by rizafran** [comment]
Thanks for reporting, @KemalPajevic. This could be related to the way the run script build phase was configured. Could you confirm if you have tried the steps [here](https://firebase.google.com/docs/crashlytics/get-started?platform=ios#set-up-dsym-uploading) specifically in number 4?

**Comment by KemalPajevic** [comment]
> Thanks for reporting, @KemalPajevic. This could be related to the way the run script build phase was configured. Could you confirm if you have tried the steps [here](https://firebase.google.com/docs/crashlytics/get-started?platform=ios#set-up-dsym-uploading) specifically in number 4?

With my current setup I am not able to get to step 4 (forcing a crash) at all, since the scrip fails at build time.

**Comment by rizafran** [comment]
Sorry for the confusion, @KemalPajevic. It means on step 3, number 4:

> c. In the script field (located under the Shell label), add the following run script.This script processes your project's dSYM files and uploads the files to Crashlytics.
> - "${BUILD_DIR%/Build/*}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run"
>
> d. In the Input Files section, add the paths for the following files.
>- Add the path to your project's dSYM files
>- This enables Crashlytics to process dSYMs for large apps more quickly.
>   - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
>
> 
>- Add the path to your project's built Info.plist file
>- This enables Crashlytics to associate an app version with the dSYMs.
>    - $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)

**Comment by KemalPajevic** [comment]
Ah, sorry I misunderstood. Yes, I have tried this, and if I do I do not get any build errors, but I also do not seem to receive any symbol fies, at least from our build server. That's why I think I need to use `upload-symbols` as described [here](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=ios).

**Comment by rizafran** [comment]
No worries, @KemalPajevic. Based on the error message you provided, it looks like a config-related issue. To isolate, could you confirm if it's working fine when uploading the dSYMs [manually](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=ios#upload-dsyms)?
