### ISSUE TITLE
issues with GoogleUtilities/UserDefaults 

### ISSUE THREAD

**Issue by rideflag-minh-huynh** [firebase/firebase-ios-sdk#8998]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13
  * Firebase SDK version: not sure
  * Installation method: CocoaPods
  * Firebase Component: Messaging 
  * Target platform(s):  iOS`

#### Steps to reproduce:

Have MLKit and Messaging pods installed. 

Then do pod install with: In pod file, put in GoogleUtilities, ~> '7.5.0'. 

here is the error I get:

`CocoaPods could not find compatible versions for pod "GoogleUtilities/UserDefaults":
  In snapshot (Podfile.lock):
    GoogleUtilities/UserDefaults (= 6.7.2, ~> 6.0, ~> 6.7)

  In Podfile:
    Firebase/Messaging was resolved to 6.34.0, which depends on
      FirebaseMessaging (~> 4.7.1) was resolved to 4.7.1, which depends on
        GoogleUtilities/UserDefaults (~> 6.7)

    GoogleMLKit/FaceDetection was resolved to 0.64.0, which depends on
      MLKitFaceDetection (~> 0.64.0) was resolved to 0.64.0, which depends on
        MLKitCommon (~> 0.64) was resolved to 0.64.0, which depends on
          GoogleUtilities/UserDefaults (~> 6.0)

    GoogleUtilities (~> 7.5.0) was resolved to 7.5.0, which depends on
      GoogleUtilities/UserDefaults (= 7.5.0)`

**Comment by paulb777** [comment]
The old version of GoogleMLKit is not compatible with GoogleUtilities 7.x. Run `pod update` to update.

**Comment by rideflag-minh-huynh** [comment]
I had done a pod update, and mlkit is GoogleMLKit/FaceDetection (0.64.0).

**Comment by rideflag-minh-huynh** [comment]
as a follow up to this issue: 

CocoaPods could not find compatible versions for pod "nanopb":
  In Podfile:
    FirebaseFirestoreSwift was resolved to 0.4.0, which depends on
      FirebaseFirestore (>= 1.6.1, ~> 1.6) was resolved to 1.12.1, which depends on
        nanopb (~> 0.3.901)

    GoogleMLKit/FaceDetection (= 2.3.0) was resolved to 2.3.0, which depends on
      GoogleMLKit/MLKitCore (= 2.3.0) was resolved to 2.3.0, which depends on
        MLKitCommon (~> 3.1.0) was resolved to 3.1.0, which depends on
          GoogleDataTransport (~> 9.0) was resolved to 9.1.2, which depends on
            nanopb (~> 2.30908.0)

**Comment by rideflag-minh-huynh** [comment]
so I think its saying, I can't update mlkit because of my dependency to nanopb which is version 0.3, because  FirebaseFirestoreSwift was resolved to 0.4.0, which depends on
FirebaseFirestore (>= 1.6.1, > 1.6)

**Comment by paulb777** [comment]
See https://stackoverflow.com/a/64671117 to update FirebaseFirestoreSwift.

**Comment by rideflag-minh-huynh** [comment]
ah thank so much.  Best.
