### ISSUE TITLE
upload-symbols crashes if Xcode is not registered by Application Services

### ISSUE THREAD

**Issue by biboran** [firebase/firebase-ios-sdk#9002]
### Step 1: Describe your environment

  * Xcode version: see below
  * Firebase SDK version: 8.9.1
  * Installation method: `CocoaPods`
  * Firebase Component: upload-symbols executable
  * Target platform(s): `All`

### Step 2: Describe the problem

We recently updated to Xcode 13 on our CI machines and found that `upload-symbols` sometimes wouldn't work. It would crash with `SIGILL` and log `*** CFRelease() called with NULL ***` in the crash report. It turns out that this crash occurred because Xcode 13 was above the Mac OS version on some of the CI machines, which resulted in Xcode.app not being registered by Applications Services with a subsequent upload-symbols crash. The issue was not immediately apparent, since we rarely use UI to manage CI machines and other Xcode facilities worked fine.

The expected behavior of `upload-symbols` would be that it outputs some sort of error that Xcode.app was expected but was not found instead of crashing.

#### Steps to reproduce:

1. Remove Xcode
2. Make sure `lsappinfo | grep 'com.apple.dt.Xcode'` doesn't return anything
3. Run `upload-symbols --google-service-plist "${plist_path}" --platform ios "${path_to_dsym}"`

#### Relevant Code:

It seems that upload-symbols work in the following way:
```
CFArrayRef xcodeURLs = LSCopyApplicationURLsForBundleIdentifier(@"com.apple.dt.Xcode", &error);
...
CFRelease(xcodeURLs)
```
and thus CFRelease crashes in case `LSCopyApplicationURLsForBundleIdentifier` returns NULL.

**Comment by rizafran** [comment]
Thanks for reporting, @biboran. To have a better understanding, could you provide the following details:
- Complete crash logs 
- Confirmation if you're using M1 machine

**Comment by biboran** [comment]
* Here is the crash - [upload-symbols.crash.zip](https://github.com/firebase/firebase-ios-sdk/files/7692791/upload-symbols.crash.zip)
* This crash is from an Intel machine

**Comment by rizafran** [comment]
Thanks for the info, @biboran. Based on your post, you mentioned that the expected behavior of `upload-symbols` would be that it outputs some sort of error that Xcode.app was expected but was not found instead of crashing.

Just to clarify, does it mean that the `upload-symbols` script tool is not returning the expected error if Xcode is not installed?

**Comment by biboran** [comment]
Here is the output I was getting from `upload-symbols`:

![Screenshot 2021-12-13 at 23 19 14](https://user-images.githubusercontent.com/8717108/145882667-d16846ab-63ae-4dba-ac93-ca4247bbfd17.png)

**Comment by rizafran** [comment]
Thanks for sharing your output, @biboran. I tried running the `upload-symbols` script you're using but I wasn't able to get an error. Could you confirm if your Xcode is not installed when you run the script based on the screenshot provided?
