### ISSUE TITLE
Firebase/Analytics: Data loss. Cannot record event metadata

### ISSUE THREAD

**Issue by softavail** [firebase/firebase-ios-sdk#9010]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.0 (13A233)
  * Firebase SDK version: 8.8.0
  * Installation method: `CocoaPods`
  * Firebase Component: Analytics
  * Target platform(s): `iOS`
  * Swift version: 4.2

#### Steps to reproduce:
 - Integrate Firebase/Analytics in swift project as described in the docs. 
 - FirebaseApp().configure()
 - Run the app
 - Observed the console with the following error messages:

[Firebase/Analytics][I-ACS023068] Data loss. Cannot record event metadata. Error: Error Domain=com.google.gmp.measurement.ErrorDomain Code=3 "Received empty measurement bundle metadata for getting dictionary representation" UserInfo={NSLocalizedDescription=Received empty measurement bundle metadata for getting dictionary representation}
[Firebase/Analytics][I-ACS012056] Transaction failed. Transaction failed

**Comment by paulb777** [comment]
Based on https://github.com/firebase/quickstart-ios/issues/229, this could be an issue with the nanopb library linked into the app.  Are there any duplicate symbol warnings in the console at app startup? Is the app linking a version of nanopb different from the version required by Firebase?
