### ISSUE TITLE
Need to publish new podspec for GoogleUtilitiesComponents

### ISSUE THREAD

**Issue by jacobg** [firebase/firebase-ios-sdk#9021]
The latest podspec published to Cocoapods contains an IOS platform version of 8:
https://cocoapods.org/pods/GoogleUtilitiesComponents
https://github.com/CocoaPods/Specs/blob/master/Specs/e/a/f/OpenCV2/4.3.0/OpenCV2.podspec.json

However, this repo source code has contained version 10 since last year:
https://github.com/firebase/firebase-ios-sdk/blob/master/GoogleUtilitiesComponents.podspec
This update needs to be published. Version 8 is just so old, and breaks other tooling that has higher minimum versions, e.g., cordova.

**Comment by paulb777** [comment]
@jacobg Thanks for the report. I've started a PR and plan to publish an update this week.

**Comment by jacobg** [comment]
Thank you @paulb777 !

**Comment by paulb777** [comment]
Published today:

--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  GoogleUtilitiesComponents (1.1.0) successfully published
 📅  November 29th, 06:46
 🌎  https://cocoapods.org/pods/GoogleUtilitiesComponents
 👍  Tell your friends!
--------------------------------------------------------------------------------
