### ISSUE TITLE
Xcode 13 - Please make sure it is a package collection URL.

### ISSUE THREAD

**Issue by Echecivuole** [firebase/firebase-ios-sdk#9024]
Hi, While I am trying tin stall the https://github.com/firebase/firebase-ios-sdk.git package via Xcode, I get this error message:

**Received invalid response at https://github.com/firebase/firebase-ios-sdk.git. Please make sure it is a package collection URL.**

Please help
thanks

**Comment by Echecivuole** [comment]
solved :)

**Comment by cheneva99** [comment]
Hi, how did you solve it ?

**Comment by gSoheila** [comment]
I am getting the same message. Could you please let me know how you solved it? 
Thanks
