### ISSUE TITLE
FR: Add support for interruptionLevel on iOS 15

### ISSUE THREAD

**Issue by nomyzs** [firebase/firebase-ios-sdk#9036]
### Feature proposal

* Firebase Component: Messaging

Add support for specifying interruption-level in FCM messages payload.

With iOS 15, Apple introduced Focus Modes that can be bypassed by apps with time-sensitive capabilities selected and notifications that has either timeSensitive or critical interruption level.
https://developer.apple.com/documentation/usernotifications/unnotificationcontent?changes=la

I couldn't find any information about it in regards to FCM supporting this. 
Tried enabling this capability in my project and sending FCM notifications with `'interruption-level': 'time-sensitive',` key-value - no luck.

Do you plan to support this?

Thank you! :)

**Comment by gooson** [comment]
any plan?

**Comment by JoniVR** [comment]
To everyone here, this seems already supported (and working just fine) on our end. 

You need to configure it correctly in your iOS project, regenerate certificates etc

and then in your backend or where you send the message, add:

`"interruption-level": "time-sensitive"` under the `aps` property. 

If you're using the `firebase-admin` sdk (whichever platform), use the `CustomData` Dictionary under `aps`:
https://firebase.google.com/docs/reference/admin/dotnet/class/firebase-admin/messaging/aps#class_firebase_admin_1_1_messaging_1_1_aps_1a59098a4d657d5fc5d596bcb9e2c2a774

**Comment by paulb777** [comment]
Thanks @JoniVR ! I'll close this for now, but can continue the discussion here and reopen if there's something missing.
