### ISSUE TITLE
The 'email' field in the 'password' providerData doesn't match the new one after 'updateEmail' succeeds.

### ISSUE THREAD

**Issue by spacen** [firebase/firebase-ios-sdk#9041]
The 'email' field in the 'User' changes right away, but not the one in the providerData.
Event after restarting the app.

I'm currently using Firebase/Core 8.1.0

**Comment by argzdev** [comment]
Hi @spacen, thanks for reporting. Could you provide me steps to reproduce this issue?

**Comment by spacen** [comment]
1. Sign in anonymously
2. Link with email/password credentials
3. Update email
4. Refesh user info (Doesn’t matter if you restart the app or not)
5. Now you can see that email fields differ

**Comment by argzdev** [comment]
Thanks for the steps @spacen. I noticed you're using an old version of the SDK. Can you confirm if this issue still persists when using the latest version of the SDK (8.10.0)?
