### ISSUE TITLE
Binary make use of strlen and memcpy

### ISSUE THREAD

**Issue by sathishgodbtech** [firebase/firebase-ios-sdk#905]
Environment
  * Xcode version: 9.2
  * Firebase SDK version: 4.5
  * Firebase Component: FirebaseInstanceId

Problem
	We are using the firebase for push notification in our cordova application.
	Our penetration testing team have found out that banned APIs are being used in the application(strlen and memcpy)
	Further to out testing we found out that "strlen" or "memcpy" was used in the following files
	1. FTestAuthTokenGenerator.m
	2. StringUtilities.m
	3. FSTPath.mm
	4. raw_logging.cc
	5. ascii_test.cc
	6. numbers_test.cc
	7. string_view_test.cc
	8. FSRWebSocket.m
	9. comparison.cc
	10.endian_test.cc
	11.escaping.cc
	12.memutil.cc
	13.numbers.cc
	14.str_cat.cc

	We have update the code, recompiled the files and updated the same in our application.
	
	Then we found out that library file called "FirebaseInstanceId" contains _strlen and _memcpy.
	Source code for the same is not available. We refered the following likns for the reference.
	https://github.com/firebase/firebase-ios-sdk/issues/186
	
	Can you please tell me when these issues will be fixed or will the source code for the same will be available for us to edit.

**Comment by wilhuff** [comment]
Hi thanks for your writing in. We don't currently consider these functions to be banned and don't consider addressing this to be a high priority. If you'd like to send a pull request for the changes you'd like you're welcome to do so.

Note that some of these files are actually pulled from an upstream source and we can't accept changes directly here. All the files under `Firestore/third_party/abseil-cpp` come from the [Abseil project](https://github.com/abseil/abseil-cpp):
4. raw_logging.cc
5. ascii_test.cc
6. numbers_test.cc
7. string_view_test.cc
10.endian_test.cc
11.escaping.cc
12.memutil.cc
13.numbers.cc
14.str_cat.cc

We won't accept changes to these files directly, but if you can get these changes accepted upstream we'll merge the changes here.

This file is pending deletion, so I wouldn't bother fixing it:

3. FSTPath.mm

For the other files, you're welcome to propose a change:

1. FTestAuthTokenGenerator.m
2. StringUtilities.m
8. FSRWebSocket.m
9. comparison.cc

I can't speak to the InstanceId usage.

**Comment by morganchen12** [comment]
InstanceID doesn't consider these APIs banned or unsafe either. InstanceID is still closed-source, and uses `strlen` in a single location to get the length of an ascii string, but does not reference memcpy.

This is unlikely to change in the near future.
