### ISSUE TITLE
SwiftUI: No such Module 'FirebaseAuth'

### ISSUE THREAD

**Issue by willtucker42** [firebase/firebase-ios-sdk#9053]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13
  * Firebase SDK version: 8.10.0
  * Installation method:  Swift package manager (select one)
  * Firebase Component: auth (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Target platform(s): ios

### [REQUIRED] Step 2: Describe the problem

When I try importing FirebaseAuth it I get the error : "No such Module 'FirebaseAuth'". I have added the package dependencies with package manager and FirebaseAuth is there... but it still gives the error. See screenshot: https://prnt.sc/21wm6mf

#### Steps to reproduce:
Install firebase ios sdk via SPM. 
Select every single installation option. 
Try importing FirebaseAuth

#### Relevant Code:

```
// import FirebaseAuth
```
<img width="1427" alt="firebasetrouble" src="https://user-images.githubusercontent.com/29614012/144765584-f6e36d05-519d-4cdd-9920-e6f6f2cbb4b7.png">

**Comment by paulb777** [comment]
This is likely a duplicate of #9014. Please see the discussion there and confirm that you've added FirebaseAuth as a build dependency.

**Comment by willtucker42** [comment]
Issue was solved following answer from this discussion: https://github.com/firebase/firebase-ios-sdk/issues/9014. Thanks to @paulb777
