### ISSUE TITLE
Problem with new way of open Deeplinks in IOS 15

### ISSUE THREAD

**Issue by carl0shd** [firebase/firebase-ios-sdk#9054]
### Step 1: Describe your environment

  * Xcode version: 13.1
  * Firebase SDK version: 8.8.0
  * Installation method: CocoaPods
  * Firebase Component: Deeplinks
  * Target platform(s): IOS

#### Steps to reproduce:

When scan a Deeplink with the native camera in IOS 15, if i tap the name of the app behind the QR, works perfectly, but if i tap the icon in the lower right corner and choose: Open with *App Name*, the app opens but not detect any deeplink.

i attach and example with Instagram:
![Group 1](https://user-images.githubusercontent.com/8359234/144497169-d572900c-302c-4e72-8628-dc885149bc3c.png)

**Comment by andreascruz** [comment]
Any updates on this? I'm also having this problem.

**Comment by rizafran** [comment]
Thanks for reporting the issue. I've informed our engineers to see what we can do here.

**Comment by morganchen12** [comment]
For people running into this issue, are you able to get the original deep link from the [universal link URL](https://firebase.google.com/docs/reference/ios/firebasedynamiclinks/api/reference/Classes/FIRDynamicLinks#-dynamiclinkfromuniversallinkurl:completion:)?
