### ISSUE TITLE
Memory Leak on FIRApp Config. SDK version - 6.34.0

### ISSUE THREAD

**Issue by pushparajakln** [firebase/firebase-ios-sdk#9059]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: _13.1____
  * Firebase SDK version: _6.34.0____
  * Installation method: `CocoaPods | Carthage | Zip file | Swift Package Manager` (select one) - CocoaPods
  * Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Target platform(s): `All | iOS | Catalyst | macOS | tvOS | watchOS` - iOS

#### Steps to reproduce:

What happened? How can we make the problem occur?
Getting memory leaks on FIRApp Configuration. 

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```
<img width="511" alt="Screenshot 2021-12-07 at 4 13 20 PM" src="https://user-images.githubusercontent.com/1279615/145015379-1d8f3f10-4f46-4be4-b602-127a91dc9d4e.png">
<img width="1273" alt="Screenshot 2021-12-07 at 4 17 01 PM" src="https://user-images.githubusercontent.com/1279615/145015392-20e5b2a6-3ea1-46de-b290-13d85da373a7.png">
<img width="1262" alt="Screenshot 2021-12-07 at 4 17 09 PM" src="https://user-images.githubusercontent.com/1279615/145015405-821d111a-7ca8-4bb5-b780-a9a4445e9554.png">

**Comment by rizafran** [comment]
Hi @pushparajakln, is the issue also reproducible when upgrading the SDK version (as this contains bug fixes)?

**Comment by pushparajakln** [comment]
> Hi @pushparajakln, is the issue also reproducible when upgrading the SDK version (as this contains bug fixes)?

Yes @rizafran. I am using latest version

**Comment by paulb777** [comment]
The latest issue is 8.10.0.  The issue is specifying 6.34.0

**Comment by pushparajakln** [comment]
> 

Sorry. I thought it is a latest version. We cannot update to latest. Could you please check this issue in 6.34.0

**Comment by paulb777** [comment]
Sorry, we're not likely to prioritize a fix to 6.x.
