### ISSUE TITLE
Notification not received on First Launch, Need Force Kill and ReLaunch to work

### ISSUE THREAD

**Issue by MohamedJaffer-24** [firebase/firebase-ios-sdk#9062]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13
  * Firebase SDK version: 8.10
  * Installation method: `CocoaPods 
  * Firebase Component: Messaging 
  * Target platform: iOS 

### [REQUIRED] Step 2: Describe the problem
                      Background notifications not received on first app open. You have to hard close and re-open the app before they start working. Already the same description problem was raised and fixed in Firebase version in 7.0

#### Steps to reproduce:

What happened? How can we make the problem occur?

This was my process:

Built and deployed the iOS  app to device.
firebase configured
Allowed notifications and fcm token received and sent to our server
Pushed the Notification from our server.
Not Received in Device.

Force quit the app.
Re-open the app.
Send another notification message to the device
Notification received

I could find the apns token recieved after fcm token generated . and then after settings apns token to messaging deleagte. Again a new fcm token is received.  My time based testing are as follows. And this happens only for the first launch. Successive launch of the app results in only one fcm token. 

Traces: 

 17:17:00:701  Configuring Firebase In App    

 17:17:01:109  FCMTOKENTEST/AppDelegate: "e30cfPrRnU6_ijUIRAGtD6:APA91bFP2Vzb-xahHPrz2avQZzFMYgvbZgua70U-aASgJUXkDJhUtze_h4kBmOizvM12SfwmnTv8w1yBeXAVmWwNNNfdVeoRfWaI8EmOQh4Is01yJdlGvTluOsnzaooQ4MBgKxkirasO"

  17:17:01:194  application(_:didRegisterForRemoteNotificationsWithDeviceToken:) called and device token is assigned to Messaging delegate    
                     Messaging.messaging().apnsToken = deviceToken

  17:17:02:679  FCMTOKENTEST/AppDelegate: "cRUaTt4Kfk4bgkuAI7V2Bq:APA91bHS9GE62bGsTCxutrMd9s_2iZdiswmF2oHKyfJToI6LvQ8UfCZBF6gb_7W8adP14dVFkuUZw6zDFrKfzTGpCX6vazJFK1i9KSTEbiecpU8ZH4HYhRCrYkfRo0_NPB3VebjKRaLl"

**Comment by rizafran** [comment]
Thanks for reporting, @MohamedJaffer-24. The issue seems related to #9003.

**Comment by MohamedJaffer-24** [comment]
Another Info :
I am having it working good in 6.34 Version.
When i update my pod to 8.0.0 Version, Issue is starting

@rizafran

**Comment by rizafran** [comment]
Noted on this, @MohamedJaffer-24. Thanks for the additional info.

**Comment by KangByeongjun** [comment]
i have same issue.
is there some update?

**Comment by rizafran** [comment]
Hi @KangByeongjun, we're currently investigating the issue. You may also check the issue above for the updates. Thanks.

**Comment by rizafran** [comment]
Hi @MohamedJaffer-24, based on the updates from the above issue, it has been fixed at #9152, so I'll now close this ticket. Please wait for the next SDK release and let us know if the issue will persist. Thanks.
