### ISSUE TITLE
Firebase Dynamic Links not working when open from facebook SwiftUI

### ISSUE THREAD

**Issue by dhimansham** [firebase/firebase-ios-sdk#9068]
I'm using firebase dynamic links for creating links and share it from my app to social media platforms, I tried to share on WhatsApp and messenger and it's working great no problems.

The only exception when trying to open a link from Facebook, it opens the InAppBrowser first after that it's working perfectly some time and show popup to leave the Browser and open app but some time show preview page in case the app already installed. Some time show direct web page which backend team set in the redirection.

Here's the code for sharing and initiate:

    
    func createLinkShare1(dynamicLinksDomainURIPrefix:String,link:URL) {

    let appBundleID = AppInformation.AppBundleId

    if let linkBuilder = DynamicLinkComponents(link: link, domainURIPrefix: dynamicLinksDomainURIPrefix) {

        linkBuilder.navigationInfoParameters = DynamicLinkNavigationInfoParameters()

        linkBuilder.navigationInfoParameters?.isForcedRedirectEnabled = true

        linkBuilder.iOSParameters = DynamicLinkIOSParameters(bundleID: appBundleID)

        linkBuilder.iOSParameters?.appStoreID = AppInformation.AppStoreId

        linkBuilder.iOSParameters?.minimumAppVersion = AppInformation.AppMinimumVersion

        linkBuilder.androidParameters = DynamicLinkAndroidParameters(packageName: appBundleID)

        linkBuilder.androidParameters?.minimumVersion = 0

        linkBuilder.socialMetaTagParameters = DynamicLinkSocialMetaTagParameters()

        linkBuilder.socialMetaTagParameters!.title = "Testing "

        linkBuilder.socialMetaTagParameters!.descriptionText = "Invite You"

        guard let longDynamicLink = linkBuilder.url else {

            print("ERROR in linkBuilder")

            return

        }

        DynamicLinkComponents.shortenURL(longDynamicLink, options: nil) { url, warnings, error in

            if let error = error {

                print("error shortening link: \(error.localizedDescription)")

                return

            }

            if let url = url {

                print("Share Url = ",url)

                return

              }

           }

        }
     }

Output:-

iOS 14.5
[Screenshot](https://i.stack.imgur.com/PUSo5.png)

iPhone X (iOS 15.0.1)
[ScreenShot](https://i.stack.imgur.com/FgDNz.png)

In Second case already app installed, i don't know why the preview page open instead of popup

iPhone XR (iOS 15.1)
[ScreenShot](https://i.stack.imgur.com/t3uHP.png)

Sorry For hidden details.

I have tested with multiple devices and different version. Only the Deep linking working in below iOS15.

Can someone please explain to me how to show popup or deep working as expected in the Facebook case, I've tried to with above code but no results yet.

Any help would be greatly appreciated.

Thanks in advance.

**Comment by rizafran** [comment]
Hi @dhimansham, per checking, there are known issues with FDL involving the Facebook app. Unfortunately, we don't have a workaround for this issue, as it's up to Facebook to determine how URLs are handled inside their app. See also this related issue #3699.

I'll be closing this as there isn't much we can do about Facebook's in-app browser behavior. If you have other related questions, you may file a ticket via our [Firebase support channel](https://firebase.google.com/support). Thanks.
