### ISSUE TITLE
Deprecate Firebase pod, Firebase module, and Firebase.h

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#9074]
Firebase has historically enabled all public APIs for all installed products to be available via importing the Firebase module or Firebase.h.  This is implemented via preprocessor commands in Firebase.h along with some fake module infrastructure.

As Firebase becomes more Swift-centric, it's not clear we can continue supporting that functionality since Swift does not allow similar preprocessor logic and its modules would require all dependencies to be built - defeating the purpose of only installing/building what is needed.

As a result, starting the next major release, Firebase users will need to import a Firebase module for each Firebase product used.

Let us know if you have any concerns about this proposal or suggestions for alternatives.

**Comment by emmanuel-montoya** [comment]
Could you add some screenshots or snippets for future references?

**Comment by paulb777** [comment]
@emmanuel-montoya Yep, we'll do a full docs/samples/snippets scrub if we implement this.

**Comment by a-25** [comment]
Hello, @paulb777. Are you planning to implement this feature?
I replaced internal links to several Firebase/<framework>s so let me know if it is good to go on.

**Comment by paulb777** [comment]
Thanks @a-25! We do plan to implement, but not until our next major release, which isn't yet scheduled.  It will likely be sometime between the spring and fall of this year.  Once we get closer, we'll evaluate and merge these changes.

**Comment by paulb777** [comment]
Perhaps, we should keep the Firebase pod even without the module to ease transition and beta version specification?  cc: @ryanwilson

**Comment by paulb777** [comment]
Based on experimentation and https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_swift_into_objective-c, I'm not able to find a way to check for existence from Swift Package Manager. `#import "FirebaseFunctions-Swift.h"` is only visible from the current module. Otherwise a module import is needed and there doesn't seem to be a corresponding directive in Objective C to the Swift `canImport`

**Comment by paulb777** [comment]
Swift Forum question at https://forums.swift.org/t/canimport-for-objective-c-clients-of-swift-packages/55294

**Comment by a-25** [comment]
> #9333 demonstrates a way to use the Firebase pod for CocoaPods with its Firebase.h. If we can find a similar solution for Swift PM, we may be able to keep the Firebase pod. cc: @a-25

@paulb777, do you see any advantage of keeping Firebase pod? I think it could be technically removed.

**Comment by paulb777** [comment]
@a-25 The major advantage to keeping it is to avoid disruption to existing Firebase users who reference it in their Podfiles and import statements.

**Comment by a-25** [comment]
@paulb777 
As I suppose, it will still available for the last released version. So if it is a reference in a Podfile, and the last released version is X, one will have the maximum X version in Podfile.lock. To upgrade further Firebase pod should be removed. So I wonder what disruption could occur. Do I miss anything?

**Comment by paulb777** [comment]
True, but we want to make it as easy as possible for everyone to keep using the latest version.

Requiring edits to Podfiles and many `.m` files will likely keep more people on old versions.

One option is to continue support for CocoaPods, but not for Swift Package Manager.

**Comment by paulb777** [comment]
We now expect to keep these working for the most part in Firebase 9. CocoaPods should maintain support. Swift Package Manager won't support them for libraries whose APIs are in Swift (Storage, Functions, MLModelDownloader).

We should still scrub our docs and samples to top using the Firebase pod, the Firebase module and Firebase.h. Assigning to @morganchen12 to review.

**Comment by morganchen12** [comment]
List of places that need to be updated, off the top of my head:
- [ ] Import snippets across getting started guides
- [ ] Imports in Console getting started flow
- [ ] Imports in quickstarts and FirebaseUI

**Comment by paulb777** [comment]
@morganchen12 Please update the check boxes above.

**Comment by morganchen12** [comment]
Docs CLs submitted.
