### ISSUE TITLE
Firebase Performance has revealed that calling "iid.googleapis.com/iid/register" takes unusually longer than expected

### ISSUE THREAD

**Issue by thanakij** [firebase/firebase-ios-sdk#9078]
### Step 0: Are you in the right place?

  * At first I think this would be a backend issue. But for some reason, I couldn't see the same URL being logged as slow on Android side in Firebase Console's Performance. So I decide to report an issue here.

### Step 1: Describe your environment

  * Xcode version: 13.0
  * Firebase SDK version: 8.10.0 (I constantly keep updating the SDK!)
  * Installation method: `CocoaPods`
  * Firebase Component: Core, Messaging, Crashlytics, Analytics, Performance
  * Target platform(s): `iOS`

#### Steps to reproduce:

I have noticed that in Firebase Console's Performance, it is showing that `iid.googleapis.com/iid/register` calls are taking unusually slow so that it is now consistently appeared in the top.

I believe this could be a temporary backend issue but it simply didn't go away and when I check on Android side, I couldn't find the same URL being logged as slow too.

Recently, there is a warning in the top of Firebase Console saying that there could be an exclusion in some app start measurement due to iOS15 starting on Dec 9, so this urges me to report it now before the issue disappears unexpectedly.

Please see the image below:
![](https://i.imgur.com/JXMtPWX.png)

**Comment by ryanwilson** [comment]
Thanks for the report, this is the endpoint use to register for push notifications. cc @chliangGoogle for more insight.

**Comment by zwu52** [comment]
Thanks for reporting. 
Given this is a request process time increase on a endpoint, let me have our Backend team to take a peak to see if this within the normal fluctuation.

**Comment by zwu52** [comment]
BE response: "1% response time increase seems normal. I don't think there is anything we should do."
Closing. Thanks @thanakij  for report.
