### ISSUE TITLE
Errors when archiving project

### ISSUE THREAD

**Issue by mpmartimbianco** [firebase/firebase-ios-sdk#9082]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.0 and 13.1
  * Firebase SDK version: 8.7.0 and 8.10.0
  * Installation method: Swift Package Manager
  * Firebase Component: only FirebaseAnalytics
  * Target platform(s): iOS

### [REQUIRED] Step 2: Describe the problem

I'm having some errors just when trying to archive the project, it works when build to simulator and device.

Tried to:

clean build folder many times
reset/resolve packages many times
update firebase sdk version (was using 8.7.0)
update xcode version (was using 13.0)
uninstall and reinstall xcode (removed using AppCleaner)

I'm trying to understand why this is happening.

<img width="670" alt="error" src="https://user-images.githubusercontent.com/10996602/144492523-57c1ccf3-ed69-48c8-893b-224b4db54be5.png">
.

**Comment by paulb777** [comment]
@mpmartimbianco Thanks for the report. Perhaps, `rm -rf ~/Library/Developer/Xcode/DerivedData/` might help? Otherwise, we'll take a look this week.

**Comment by mpmartimbianco** [comment]
@paulb777 Thank you for your reply, I tried to delete all DerivedData but Im still with this error.

Before I reinstall xcode I deleted all folders with AppCleaner and some manually to see if it solve but not luck.

**Comment by paulb777** [comment]
@mpmartimbianco I'm able to successfully archive https://github.com/firebase/quickstart-ios/tree/master/analytics after integrating Firebase via SPM. 

Would you see if you can? If so, there may be something about your app's Xcode project causing the problem.

**Comment by mpmartimbianco** [comment]
@paulb777 I can archive the https://github.com/firebase/quickstart-ios/tree/master/analytics.

But I don't have any idea of what in my project can cause this issue. Maybe a build settings option?

**Comment by paulb777** [comment]
We're going to need a reproducible example to help.
