### ISSUE TITLE
Carthage Firebase.framework does not contain bitcode.

### ISSUE THREAD

**Issue by mpaulsonco** [firebase/firebase-ios-sdk#911]
When installed through Carthage, `Firebase.framework/Firebase' does not contain bitcode.`

#### My Environment
 
  * Xcode version: 9.2
  * Firebase SDK version: 4.9.0 (Carthage)
  * Firebase Component: Core, Analytics, Messaging
  * Component version: 4.9.0

#### Steps to reproduce:

1. Install Firebase from Carthage following the steps outlined in the [guide](https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md). 
2. Try and build to a physical device or create an Archive 
3. Encounter error:
```
ld: '........../Carthage/Build/iOS/Firebase.framework/Firebase' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '........./Carthage/Build/iOS/Firebase.framework/Firebase' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

#### Additional Details:
- This is only a problem with Firebase.framework (the other Carthage-installed dependencies I have in the same project do not have this issue)

**Comment by paulb777** [comment]
@mpaulsonco Thanks for the report! The Firebase.framework is only needed to provide build time access to the Firebase module and Firebase.h. It is not needed for linking. Thus a workaround is to delete Firebase.framework from the Link Binary With Libraries Build Phase.

I'll leave this open until I make this requirement clearer in the documentation or update the Firebase framework.

![screen shot 2018-03-12 at 1 38 41 pm](https://user-images.githubusercontent.com/73870/37308306-d5bc6f58-25fa-11e8-93ee-e320487670e5.png)

**Comment by mpaulsonco** [comment]
@paulb777 I can confirm this solved it for me, thanks!

**Comment by npocmo** [comment]
Hello!

I run into same issue, so I also deleted Firebase.framework from the Link Binary With Libraries Build Phase. 

I am still getting errors like:
`Ld .../Library/Developer/Xcode/DerivedData/CarthageFirebaseTest-gcmfvqeteiovpadbjrrhdofxjsbi/Build/Products/Debug-iphoneos/CarthageFirebaseTest.app/CarthageFirebaseTest normal arm64
    cd .../carthage_firebase_test/CarthageFirebaseTest`

`Undefined symbols for architecture arm64:
  "___cxa_guard_acquire", referenced from:
      leveldb::crc32c::Extend(unsigned int, char const*, unsigned long) in leveldb-library(crc32c.o)
  "___cxa_guard_abort", referenced from:
      leveldb::crc32c::Extend(unsigned int, char const*, unsigned long) in leveldb-library(crc32c.o) ...`

I tried to add additional Linker Flags, which were suggested in another threads and also added libraries like "libicucore.dylib" but it didnt helped. I am only getting different errors.

I am using Xcode 9.2 and macOS Sierra 10.12.6.

 @paulb777, Do you have any suggestion to fix this problem?

**Comment by paulb777** [comment]
@npocmo Try adding libc++ to the Link Binary With Libraries Build Phase.

<img width="645" alt="screen shot 2018-03-13 at 7 01 07 am" src="https://user-images.githubusercontent.com/73870/37346411-7d895908-268c-11e8-8191-a96f29909c0c.png">

**Comment by npocmo** [comment]
libc++ resolved some errors, but not all of them. I also added libssqlite3.tbd and some others libraries which helped but I still couldnt build my sample project successfuly.

After a while I decided to only use frameworks I absolutely needed and for a build to be successful.
![image](https://user-images.githubusercontent.com/23473411/37347355-ef7ea87a-26d1-11e8-831b-31e57bfe22e1.png)

And it worked.

**Comment by unixb0y** [comment]
I would like to mention that I had this error:
![Screenshot 2019-04-16 at 01 45 53](https://user-images.githubusercontent.com/6874233/56172357-618a8f00-5fe9-11e9-826b-bd86441f402d.png)

This is the content of my `Cartfile`:  
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseMessagingBinary.json"
```

I resolved it by adding "StoreKit" in "Link Binary With Libraries":  
![Screenshot 2019-04-16 at 01 47 37](https://user-images.githubusercontent.com/6874233/56172422-a9a9b180-5fe9-11e9-81f2-c7ac292e7cd0.png)

**Comment by paulb777** [comment]
@unixb0y Thanks for sharing. I've seen another report that this same issue was resolved by `rf ~/Library/Developer/Xcode/DerivedData/ `. Presumably the Xcode ModuleCache wasn't properly updating.

**Comment by unixb0y** [comment]
> @unixb0y Thanks for sharing. I've seen another report that this same issue was resolved by `rm -rf ~/Library/Developer/Xcode/DerivedData/ `. Presumably the Xcode ModuleCache wasn't properly updating.

You're right! No need for StoreKit, then 😊 I was just following the error message, but the classic "clean caches" worked, thanks man 👍

**Comment by Reggian** [comment]
@paulb777 Thank you for putting an effort into Carthage solution. Much appreciated.
But there is a problem combining Firebase with Crashlytics. 
After I add the Crashlytics/Fabric frameworks I get the error:

    Could not find auto-linked framework 'Firebase'

Any ideas here?

**Comment by paulb777** [comment]
@Reggian From https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md, Delete Firebase.framework from the Link Binary With Libraries Build Phase.

**Comment by Reggian** [comment]
@paulb777 Maybe I forgot to mention, I did and Firebase alone works 👍 
But after I add the Crashlytics/Fabric frameworks I get the error:

    Could not find auto-linked framework 'Firebase'

**Comment by paulb777** [comment]
It looks like missing the Firebase framework is only a warning. The error is not linking the C++ library. See https://github.com/firebase/firebase-ios-sdk/issues/911#issuecomment-372675694 above.

**Comment by Reggian** [comment]
@paulb777 I am sorry I missed that and have wasted your time.
Thanks a lot for your help and patience.
