### ISSUE TITLE
Can't add Firebase Swift Package to project

### ISSUE THREAD

**Issue by zappyad** [firebase/firebase-ios-sdk#9110]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.2
  * Firebase SDK version: 8.10.0
  * Installation method:  Swift Package Manager
  * Firebase Component: Auth
  * Target platform(s): iOS

### [REQUIRED] Step 2: Can't add firebase via swift package manager.  

I follow the instructions here:  https://github.com/firebase/firebase-ios-sdk/blob/master/SwiftPackageManager.md

and add package from git but when I press Add Package XCode hangs trying to validate.  I never get to see the list of firebase components in the package.

Also XCode gives a message that it is unable to load the Read Me from the git project

#### Steps to reproduce:

Try to add firebase to a project using package manager.  The project previously used cocoapods and this was deintegrated as per instructions

**Comment by rizafran** [comment]
Hi @zappyad, did you get an error about the "Missing Package Description Module"? If so, it might be related to this [thread](https://developer.apple.com/forums/thread/696504) wherein Xcode 13.2 has some issues with SwiftPM.

**Comment by zappyad** [comment]
> 

No error message just a progress bar at 0% 

Verifying firebase-ios-sdk...

Preparing to validate...

Left it a few hours and nothing happens...

**Comment by rizafran** [comment]
Hi @zappyad. Is the issue still happening after re-downloading Xcode 13.2 from the Apple Developer site?

**Comment by zappyad** [comment]
Downloading and installing v 13.2 from the Apple developer site fixed this issue and I have been able to add packages to projects.
