### ISSUE TITLE
Can't render SwiftUI previews with Code Coverage Enabled

### ISSUE THREAD

**Issue by farzinfaghihi** [firebase/firebase-ios-sdk#9115]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5.1
  * Firebase SDK version: 7.1
  * Installation method: CocoaPods 
  * Firebase Component: Core 
  * Target platform(s): | iOS 

### [REQUIRED] Step 2: Describe the problem

I am currently experiencing this issue that was closed previously. https://github.com/firebase/firebase-ios-sdk/issues/6219

The solution for me was also to turn off code coverage as mentioned in the comments.

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

This is the error occurring:

```
linker command failed with exit code 1 (use -v to see invocation)

LinkDylibError: Failed to build ... .swift

Linking failed: linker command failed with exit code 1 (use -v to see invocation)

ld: warning: directory not found for option '-F/Applications/Xcode-12.5.1.app/Contents/SharedFrameworks-iphonesimulator'
Undefined symbols for architecture x86_64:
  "___llvm_profile_runtime", referenced from:
```

I am unable to determine exact specific of how firebase is causing this issue. Firebase is just included in the project, but no firebase methods are called in the swift ui files.

**Comment by rizafran** [comment]
Thanks for reporting, @farzinfaghihi. Could you share the detailed steps on how the issue occurred?

**Comment by paulb777** [comment]
Also, please update to an 8.x version of Firebase if you're still having trouble.
