### ISSUE TITLE
Crashed: com.google.fira.worker

### ISSUE THREAD

**Issue by softavail** [firebase/firebase-ios-sdk#9129]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.0
  * Firebase SDK version: 8.8.0
  * Installation method: `CocoaPods`
  * Firebase Component: Analytics
  * Target platform(s): `iOS`

#### Steps to reproduce:

There is no specific steps to reproduce. The  app crashes when I am switching between screens but randomly. 
I know that when FirebaseAnalytics is enabled and when I navigate from screen to screen it captures events. Then sometimes later the app crashes randomly. Sometimes it crashes when the app goes into background.

Here is the crashlog

```
Crashed: com.google.fira.worker
0  libsystem_platform.dylib       0xae0 _platform_memmove + 144
1  AppSDK                         0x31a640 pb_field_set_to_default + 348
2  AppSDK                         0x318e80 pb_message_set_to_defaults + 56
3  AppSDK                         0x318e1c pb_decode + 36
4  App                            0x959d0c apmpb_decode_measurement_config + 4348878092
5  App                            0x96466c -[APMPBMeasurementConfig initWithBuffer:] + 4348921452
6  App                            0x937864 __71-[APMMeasurement networkRemoteConfigFetchCompletionHandler:data:error:]_block_invoke + 4348737636
7  App                            0x98d0fc -[APMSqliteStore performTransactionWithError:block:] + 4349087996
8  App                            0x900d7c -[APMDatabase performTransaction:] + 4348513660
9  App                            0x937824 -[APMMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] + 4348737572
10 App                            0x937048 __35-[APMMeasurement fetchRemoteConfig]_block_invoke + 4348735560
11 libdispatch.dylib              0x2924 _dispatch_call_block_and_release + 32
12 libdispatch.dylib              0x4670 _dispatch_client_callout + 20
13 libdispatch.dylib              0xbdf4 _dispatch_lane_serial_drain + 672
14 libdispatch.dylib              0xc968 _dispatch_lane_invoke + 392
15 libdispatch.dylib              0x171b8 _dispatch_workloop_worker_thread + 656
16 libsystem_pthread.dylib        0x10f4 _pthread_wqthread + 288
17 libsystem_pthread.dylib        0xe94 start_wqthread + 8
```

I noticed the crash call stack goes via AppSDK's `pb_decode`. `AppSDK` is  my own framework I developed for the purposes of the application. I wonder what functions are `pb_decode`, `pb_message_set_to_defaults` and `pb_field_set_to_default `? Maybe `protobuf` related?

#### Relevant Code:
I initialize in app's delegate `didFinishLaunchingWithOptions` with options by
```
Firebase.configure()
```

**Comment by paulb777** [comment]
@softavail The `pb_` symbols are from nanopb and this looks like a crash related to a version of nanopb linked into the app that is inconsistent with the nanopb CocoaPod used by Firebase. See #8505 for more context.

**Comment by kilirushi** [comment]
![Screen Shot 2022-01-08 at 11 37 53](https://user-images.githubusercontent.com/17327812/148631594-d9bda865-b779-49de-ae24-63e355852a8f.png)
Does Alamofire conflict with Firebase?.

**Comment by paulb777** [comment]
@kilirushi As far as I know, Alamofire does not use nanopb and does not conflict with Firebase.
