### ISSUE TITLE
Firebase  Query Return Duplicates

### ISSUE THREAD

**Issue by Smiller193** [firebase/firebase-ios-sdk#913]
So I have a function which supposed to grab entries from my firebase database and sort them by creationDate(a key in my firebase tree/node that has a timestamp). The function that I use to accomplish all this is this.

       static func fetchUserNotif(for user: User = User.current,currentNotifCount: Int,lastKey: String, isFinishedPaging: Bool,withCompletion completion: @escaping ( [Notifications],Bool) -> Void){
            //array of user notifications
            var currentNotifsArray = [Notifications]()
            //instance of a notification
            var currentNotif:Notifications!
            //bool value to know when pagination is done
           var isFinishedPagingTemp = isFinishedPaging
            //2
            //ref to point in database i want to query
            let notifRef = Database.database().reference().child("notifications").child(user.uid)
            //query function with key I want to order results by
            var query = notifRef.queryOrdered(byChild: "creationDate")
            //variable that changes the the query up depending on whether this is the first call or a subsequent one (useful for pagiantion)
            if currentNotifCount > 0 {
                print(lastKey)
                query = query.queryEnding(atValue: lastKey)
                
            }
            
            
            query.queryLimited(toLast: 10).observeSingleEvent(of: .value, with: { (notifSnapshot) in
                guard var allUserNotifs = notifSnapshot.children.allObjects as? [DataSnapshot] else {
                    return completion( [],true)
                }
                allUserNotifs.reverse()
                
                
                if currentNotifCount > 0 && allUserNotifs.count > 0{
                    allUserNotifs.removeFirst()
                    
                }
                
                if allUserNotifs.count < 1 {
                    isFinishedPagingTemp = true
                    return completion([],true)
                }
                
                for userNotifs in allUserNotifs{
                    if userNotifs.childrenCount == 8 {
                        //  print("comment notification")
                        currentNotif = Notifications(snapshot:userNotifs)
                        currentNotifsArray.append(currentNotif)
                    }
                    if userNotifs.childrenCount == 6 {
                        //    print("follow notification")
                        print(userNotifs.children.allObjects)
                        currentNotif = Notifications(followSnapshot: userNotifs)
                        currentNotifsArray.append(currentNotif)
                    }
                    // print(userNotifs.childrenCount)
                }
                if currentNotifsArray.count == allUserNotifs.count && !isFinishedPagingTemp{
                    completion(currentNotifsArray,false)
                }else{
                    return completion([],true)
                }
            }) { (err) in
                print("Couldn't find comments in DB", err)
            }
            
        }

Alot of the setup for this function is created to make sure pagination works as can be seen in the comments. My firebase database structure for the notifications node looks like so.

    "notifications" : {
        "nbmheFEPmBerm5avZwnriGJkaK12" : {
          "-L7KHqrgkltCE7qkH9sE" : {
            "commentId" : "",
            "content" : "ron12345 has replied to your comment",
            "creationDate" : 1.520775681936579E9,
            "eventKey" : "BEVT",
            "notiType" : "comment",
            "profilePic" : "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667",
            "repliedBy" : "htG1dw4cSiebE9M12T8SOqKXrdU2",
            "repliedTo" : "nbmheFEPmBerm5avZwnriGJkaK12"
          },
          "-L7KJI3ONV7l37IX99jK" : {
            "commentId" : "",
            "content" : "ron12345 has replied to your comment",
            "creationDate" : 1.5207760626541219E9,
            "eventKey" : "BEVT",
            "notiType" : "comment",
            "profilePic" : "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667",
            "repliedBy" : "htG1dw4cSiebE9M12T8SOqKXrdU2",
            "repliedTo" : "nbmheFEPmBerm5avZwnriGJkaK12"
          },
          "-L7KJM3s1lpdgLgBpl1w" : {
            "commentId" : "",
            "content" : "ron12345 has replied to your comment",
            "creationDate" : 1.520776078298729E9,
            "eventKey" : "BEVT",
            "notiType" : "comment",
            "profilePic" : "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667",
            "repliedBy" : "htG1dw4cSiebE9M12T8SOqKXrdU2",
            "repliedTo" : "nbmheFEPmBerm5avZwnriGJkaK12"
          },
          "-L7KJOdTRbgB38E5co2w" : {
            "commentId" : "",
            "content" : "ron12345 has replied to your comment",
            "creationDate" : 1.520776089588284E9,
            "eventKey" : "BEVT",
            "notiType" : "comment",
            "profilePic" : "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667",
            "repliedBy" : "htG1dw4cSiebE9M12T8SOqKXrdU2",
            "repliedTo" : "nbmheFEPmBerm5avZwnriGJkaK12"
          },
          "-L7KJQdgIYYYqZIhjpUP" : {
            "commentId" : "",
            "content" : "ron12345 has replied to your comment",
            "creationDate" : 1.520776095666703E9,
            "eventKey" : "BEVT",
            "notiType" : "comment",
            "profilePic" : "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667",
            "repliedBy" : "htG1dw4cSiebE9M12T8SOqKXrdU2",
            "repliedTo" : "nbmheFEPmBerm5avZwnriGJkaK12"
          },
          "-L7KJTAH5RJu_s4MsB5d" : {
            "commentId" : "",
            "content" : "ron12345 has replied to your comment",
            "creationDate" : 1.520776107363553E9,
            "eventKey" : "BEVT",
            "notiType" : "comment",
            "profilePic" : "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667",
            "repliedBy" : "htG1dw4cSiebE9M12T8SOqKXrdU2",
            "repliedTo" : "nbmheFEPmBerm5avZwnriGJkaK12"
          },
          "-L7KLKehPNuMiYSQ_rKu" : {
            "commentId" : "",
            "content" : "ron12345 has replied to your comment",
            "creationDate" : 1.5207765954725971E9,
            "eventKey" : "BEVT",
            "notiType" : "comment",
            "profilePic" : "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667",
            "repliedBy" : "htG1dw4cSiebE9M12T8SOqKXrdU2",
            "repliedTo" : "nbmheFEPmBerm5avZwnriGJkaK12"
          },
          "-L7KLe1U-nsb1RkL6MOf" : {
            "commentId" : "",
            "content" : "ron12345 has replied to your comment",
            "creationDate" : 1.520776680113779E9,
            "eventKey" : "BEVT",
            "notiType" : "comment",
            "profilePic" : "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667",
            "repliedBy" : "htG1dw4cSiebE9M12T8SOqKXrdU2",
            "repliedTo" : "nbmheFEPmBerm5avZwnriGJkaK12"
          },
          "-L7KLgq_4zlUK1aAIMif" : {
            "commentId" : "",
            "content" : "ron12345 has replied to your comment",
            "creationDate" : 1.520776692109429E9,
            "eventKey" : "BEVT",
            "notiType" : "comment",
            "profilePic" : "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667",
            "repliedBy" : "htG1dw4cSiebE9M12T8SOqKXrdU2",
            "repliedTo" : "nbmheFEPmBerm5avZwnriGJkaK12"
          },
          "-L7KLji4FjNch_lVMm7A" : {
            "commentId" : "",
            "content" : "ron12345 has replied to your comment",
            "creationDate" : 1.520776703408979E9,
            "eventKey" : "BEVT",
            "notiType" : "comment",
            "profilePic" : "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667",
            "repliedBy" : "htG1dw4cSiebE9M12T8SOqKXrdU2",
            "repliedTo" : "nbmheFEPmBerm5avZwnriGJkaK12"
          },
          "-L7KLmcUwrBI5X7mwMiX" : {
            "commentId" : "",
            "content" : "ron12345 has replied to your comment",
            "creationDate" : 1.520776716339134E9,
            "eventKey" : "BEVT",
            "notiType" : "comment",
            "profilePic" : "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667",
            "repliedBy" : "htG1dw4cSiebE9M12T8SOqKXrdU2",
            "repliedTo" : "nbmheFEPmBerm5avZwnriGJkaK12"
          }
        }

 Following the first call I recieve a snapshot back from firebase with 10 pieces of data.

        [Snap (-L7KJI3ONV7l37IX99jK) {
        commentId = "";
        content = "ron12345 has replied to your comment";
        creationDate = "1520776062.654122";
        eventKey = BEVT;
        notiType = comment;
        profilePic = "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667";
        repliedBy = htG1dw4cSiebE9M12T8SOqKXrdU2;
        repliedTo = nbmheFEPmBerm5avZwnriGJkaK12;
    }, Snap (-L7KJM3s1lpdgLgBpl1w) {
        commentId = "";
        content = "ron12345 has replied to your comment";
        creationDate = "1520776078.298729";
        eventKey = BEVT;
        notiType = comment;
        profilePic = "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667";
        repliedBy = htG1dw4cSiebE9M12T8SOqKXrdU2;
        repliedTo = nbmheFEPmBerm5avZwnriGJkaK12;
    }, Snap (-L7KJOdTRbgB38E5co2w) {
        commentId = "";
        content = "ron12345 has replied to your comment";
        creationDate = "1520776089.588284";
        eventKey = BEVT;
        notiType = comment;
        profilePic = "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667";
        repliedBy = htG1dw4cSiebE9M12T8SOqKXrdU2;
        repliedTo = nbmheFEPmBerm5avZwnriGJkaK12;
    }, Snap (-L7KJQdgIYYYqZIhjpUP) {
        commentId = "";
        content = "ron12345 has replied to your comment";
        creationDate = "1520776095.666703";
        eventKey = BEVT;
        notiType = comment;
        profilePic = "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667";
        repliedBy = htG1dw4cSiebE9M12T8SOqKXrdU2;
        repliedTo = nbmheFEPmBerm5avZwnriGJkaK12;
    }, Snap (-L7KJTAH5RJu_s4MsB5d) {
        commentId = "";
        content = "ron12345 has replied to your comment";
        creationDate = "1520776107.363553";
        eventKey = BEVT;
        notiType = comment;
        profilePic = "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667";
        repliedBy = htG1dw4cSiebE9M12T8SOqKXrdU2;
        repliedTo = nbmheFEPmBerm5avZwnriGJkaK12;
    }, Snap (-L7KLKehPNuMiYSQ_rKu) {
        commentId = "";
        content = "ron12345 has replied to your comment";
        creationDate = "1520776595.472597";
        eventKey = BEVT;
        notiType = comment;
        profilePic = "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667";
        repliedBy = htG1dw4cSiebE9M12T8SOqKXrdU2;
        repliedTo = nbmheFEPmBerm5avZwnriGJkaK12;
    }, Snap (-L7KLe1U-nsb1RkL6MOf) {
        commentId = "";
        content = "ron12345 has replied to your comment";
        creationDate = "1520776680.113779";
        eventKey = BEVT;
        notiType = comment;
        profilePic = "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667";
        repliedBy = htG1dw4cSiebE9M12T8SOqKXrdU2;
        repliedTo = nbmheFEPmBerm5avZwnriGJkaK12;
    }, Snap (-L7KLgq_4zlUK1aAIMif) {
        commentId = "";
        content = "ron12345 has replied to your comment";
        creationDate = "1520776692.109429";
        eventKey = BEVT;
        notiType = comment;
        profilePic = "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667";
        repliedBy = htG1dw4cSiebE9M12T8SOqKXrdU2;
        repliedTo = nbmheFEPmBerm5avZwnriGJkaK12;
    }, Snap (-L7KLji4FjNch_lVMm7A) {
        commentId = "";
        content = "ron12345 has replied to your comment";
        creationDate = "1520776703.408979";
        eventKey = BEVT;
        notiType = comment;
        profilePic = "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667";
        repliedBy = htG1dw4cSiebE9M12T8SOqKXrdU2;
        repliedTo = nbmheFEPmBerm5avZwnriGJkaK12;
    }, Snap (-L7KLmcUwrBI5X7mwMiX) {
        commentId = "";
        content = "ron12345 has replied to your comment";
        creationDate = "1520776716.339134";
        eventKey = BEVT;
        notiType = comment;
        profilePic = "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667";
        repliedBy = htG1dw4cSiebE9M12T8SOqKXrdU2;
        repliedTo = nbmheFEPmBerm5avZwnriGJkaK12;
    }]

Upon calling the reverse function the snapshot changes to this

    [Snap (-L7KLmcUwrBI5X7mwMiX) {
        commentId = "";
        content = "ron12345 has replied to your comment";
        creationDate = "1520776716.339134";
        eventKey = BEVT;
        notiType = comment;
        profilePic = "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667";
        repliedBy = htG1dw4cSiebE9M12T8SOqKXrdU2;
        repliedTo = nbmheFEPmBerm5avZwnriGJkaK12;
    }, Snap (-L7KLji4FjNch_lVMm7A) {
        commentId = "";
        content = "ron12345 has replied to your comment";
        creationDate = "1520776703.408979";
        eventKey = BEVT;
        notiType = comment;
        profilePic = "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667";
        repliedBy = htG1dw4cSiebE9M12T8SOqKXrdU2;
        repliedTo = nbmheFEPmBerm5avZwnriGJkaK12;
    }, Snap (-L7KLgq_4zlUK1aAIMif) {
        commentId = "";
        content = "ron12345 has replied to your comment";
        creationDate = "1520776692.109429";
        eventKey = BEVT;
        notiType = comment;
        profilePic = "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667";
        repliedBy = htG1dw4cSiebE9M12T8SOqKXrdU2;
        repliedTo = nbmheFEPmBerm5avZwnriGJkaK12;
    }, Snap (-L7KLe1U-nsb1RkL6MOf) {
        commentId = "";
        content = "ron12345 has replied to your comment";
        creationDate = "1520776680.113779";
        eventKey = BEVT;
        notiType = comment;
        profilePic = "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667";
        repliedBy = htG1dw4cSiebE9M12T8SOqKXrdU2;
        repliedTo = nbmheFEPmBerm5avZwnriGJkaK12;
    }, Snap (-L7KLKehPNuMiYSQ_rKu) {
        commentId = "";
        content = "ron12345 has replied to your comment";
        creationDate = "1520776595.472597";
        eventKey = BEVT;
        notiType = comment;
        profilePic = "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667";
        repliedBy = htG1dw4cSiebE9M12T8SOqKXrdU2;
        repliedTo = nbmheFEPmBerm5avZwnriGJkaK12;
    }, Snap (-L7KJTAH5RJu_s4MsB5d) {
        commentId = "";
        content = "ron12345 has replied to your comment";
        creationDate = "1520776107.363553";
        eventKey = BEVT;
        notiType = comment;
        profilePic = "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667";
        repliedBy = htG1dw4cSiebE9M12T8SOqKXrdU2;
        repliedTo = nbmheFEPmBerm5avZwnriGJkaK12;
    }, Snap (-L7KJQdgIYYYqZIhjpUP) {
        commentId = "";
        content = "ron12345 has replied to your comment";
        creationDate = "1520776095.666703";
        eventKey = BEVT;
        notiType = comment;
        profilePic = "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667";
        repliedBy = htG1dw4cSiebE9M12T8SOqKXrdU2;
        repliedTo = nbmheFEPmBerm5avZwnriGJkaK12;
    }, Snap (-L7KJOdTRbgB38E5co2w) {
        commentId = "";
        content = "ron12345 has replied to your comment";
        creationDate = "1520776089.588284";
        eventKey = BEVT;
        notiType = comment;
        profilePic = "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667";
        repliedBy = htG1dw4cSiebE9M12T8SOqKXrdU2;
        repliedTo = nbmheFEPmBerm5avZwnriGJkaK12;
    }, Snap (-L7KJM3s1lpdgLgBpl1w) {
        commentId = "";
        content = "ron12345 has replied to your comment";
        creationDate = "1520776078.298729";
        eventKey = BEVT;
        notiType = comment;
        profilePic = "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667";
        repliedBy = htG1dw4cSiebE9M12T8SOqKXrdU2;
        repliedTo = nbmheFEPmBerm5avZwnriGJkaK12;
    }, Snap (-L7KJI3ONV7l37IX99jK) {
        commentId = "";
        content = "ron12345 has replied to your comment";
        creationDate = "1520776062.654122";
        eventKey = BEVT;
        notiType = comment;
        profilePic = "https://firebasestorage.googleapis.com/v0/b/eventful-3d558.appspot.com/o/profile_images%2FBF2D19DF-CCAB-4CFE-8FCF-20F8E022A798.PNG?alt=media&token=336a1837-3e44-414a-a0bd-4a0fcca7d667";
        repliedBy = htG1dw4cSiebE9M12T8SOqKXrdU2;
        repliedTo = nbmheFEPmBerm5avZwnriGJkaK12;
    }]

Which is valid based off of what I have done? The error comes when I attempt to paginate for the second collection of data. At the time that I try to pull for the next bit of data. The currentNotifCount is 10, and  the last key is a timestamp with the value 1520776062.65412 to give a little bit of insight. But based off what I print to the console i get the same exact data in the same exact order and i can't figure out why.This causes my app to crash.

Is it my query, Is it my Key? I have debugged it for a while and just can't figure out what is wrong and pagination is very central to my app.

**Comment by morganchen12** [comment]
What's your code for paginating/fetching the second batch of data? At first glance, the code you posted here doesn't have any issues.

**Comment by Smiller193** [comment]
NotificationService.fetchUserNotif(currentNotifCount: self.notifs.count, lastKey: String((self.notifs.last?.timeStamp?.timeIntervalSince1970)!), isFinishedPaging: self.isFinishedPaging, withCompletion: { ( noti,boolValue) in
                        print("user has \(noti.count) notifications")
                       self.isFinishedPaging = boolValue
                        self.notifs.append(contentsOf: noti)
                        self.adapter.performUpdates(animated: true)
                    })

**Comment by Smiller193** [comment]
@morganchen12

**Comment by morganchen12** [comment]
Do you ever change the database query? If not, it will always return the same contents (which is why you're getting the same data on the second fetch).

**Comment by Smiller193** [comment]
well I change the query in the event that the currenntEventCount is greaer than 10 as can been in the previous code block with this line right here.

if currentNotifCount > 0 {
            print(lastKey)
            query = query.queryEnding(atValue: lastKey)
            
        }

**Comment by morganchen12** [comment]
I see. Given you're sorting by increasing timestamp, you should probably use `query.queryStarting(atValue: lastKey)` instead. [`Query.queryEnding(atValue:)`](https://firebase.google.com/docs/reference/ios/firebasedatabase/api/reference/Classes/FIRDatabaseQuery#/c:objc(cs)FIRDatabaseQuery(im)queryEndingAtValue:) will give you children where the field is less than or equal to the provided value, which will include previous results given your query is sorted by increasing value.

Also, the functions here take snapshot values, not keys.

**Comment by Smiller193** [comment]
wait what do you mean by snapshot values. Is passing a string in for the timestamp that i pull from the notification object bad practice?

**Comment by Smiller193** [comment]
so if im trying to get values listed from the earliest time say 1pm to the latest time say 3pm I would use queryStarting?

**Comment by morganchen12** [comment]
You'll want to use the Notification object's values rather than the key of the node.

```swift
guard let value = notifications.lastObject?.creationDate else { return }
let key = "creationDate"
query = query.queryStarting(atValue: value, childKey: key)
```

**Comment by Smiller193** [comment]
so for the function I would change the argument for last key to from a string to a dataSnapshot

**Comment by Smiller193** [comment]
thanks solved it

**Comment by morganchen12** [comment]
Glad you were able to resolve your problem. For future reference, questions like this one are better suited to StackOverflow. :)

**Comment by Smiller193** [comment]
yeah I tried to but everyone kept ignoring me sorry :(
