### ISSUE TITLE
The protocols used is insecure

### ISSUE THREAD

**Issue by limyeewee** [firebase/firebase-ios-sdk#9154]
Can the client use only the most secure protocols?

https://github.com/firebase/firebase-ios-sdk/blob/902adf8b5bfd9c0b4032b155f083a8666dedf81e/FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsAPIService.m#L72

**Comment by rizafran** [comment]
Hi @limyeewee, it seems like your issue is related to #5594.
