### ISSUE TITLE
[GDTCORFlatFileStorage batchWithEventSelector:batchExpiration:onComplete:] takes too much time

### ISSUE THREAD

**Issue by SandeepAggarwal** [firebase/firebase-ios-sdk#9156]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.0 (13A233)
  * Firebase SDK version: 8.10.0
  * Installation method: `CocoaPods 
  * Firebase Component: `FirebaseCoreDiagnostics`
  * Target platform(s): `iOS`

#### Steps to reproduce:

What happened? How can we make the problem occur?
In https://github.com/google/GoogleDataTransport (an internal tool used by Firebase)
The  method `+ (void)load`  in `GDTCCTUploader` of `GoogleDataTransport` calls the method `GDTCORDecodeArchive()` as evident from the image attached below from the instruments app.
It happens during the app launch phase which degrades the app launch time by >117 ms
![image](https://user-images.githubusercontent.com/7570299/147936591-80416c1a-4a5d-4491-86a8-87ab6f2a3756.png)

#### Relevant Code:
Since the `+ (void)load`  method gets triggered during the class load itself, there is no developer-related code available.
This call is made by the iOS system itself while the pre-main period of app initilization

Please find attached the image from the instruments app
![image](https://user-images.githubusercontent.com/7570299/147937263-78d10046-e573-4c8d-89b9-c75d45e047a8.png)

#### Similar issues
https://github.com/firebase/firebase-ios-sdk/issues/6902 got solved in https://github.com/firebase/firebase-ios-sdk/pull/6919

**Comment by rizafran** [comment]
Hi @SandeepAggarwal, could you share a screenshot or full stack trace of the error you're getting? Your issue might be related to #9119.

**Comment by SandeepAggarwal** [comment]
This is different from #9119, since, I am facing the issue of an increase in app launch time due to the `load` method

<img width="1277" alt="Screenshot 2022-01-05 at 9 44 57 PM" src="https://user-images.githubusercontent.com/7570299/148251344-464199d8-93b6-47b1-9427-3a2023e6d867.png">

**Comment by morganchen12** [comment]
@SandeepAggarwal, in this second screenshot the GDT calls are responsible for <15ms of launch delay, or about a single frame. Are there other GDT calls out of frame that are contributing to the 100+ ms delay in your first screenshot? (Alternatively, can you share the instruments trace?)
