### ISSUE TITLE
Crash reported on crashlytics: libc++abi.dylib

### ISSUE THREAD

**Issue by zocario** [firebase/firebase-ios-sdk#9163]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.1 
  * Firebase SDK version: 8.9.1
  * Installation method: `CocoaPods`
  * Firebase Component: Core, Crashlytics, DynamicLinks, RemoteConfig, Performance, Analytics
  * Target platform(s): `iOS`

### [REQUIRED] Step 2: Describe the problem
We do have a crash reported on crashlytics with the following stack:

```
Crashed: com.google.firebase.crashlytics.ios.exception
0  FinalcadOne                    0x11ace5c FIRCLSProcessRecordAllThreads + 393 (FIRCLSProcess.c:393)
1  FinalcadOne                    0x11ad23c FIRCLSProcessRecordAllThreads + 424 (FIRCLSProcess.c:424)
2  FinalcadOne                    0x11a453c FIRCLSHandler + 34 (FIRCLSHandler.m:34)
3  FinalcadOne                    0x119ebc0 __FIRCLSExceptionRecord_block_invoke + 218 (FIRCLSException.mm:218)
4  libdispatch.dylib              0x481c _dispatch_client_callout + 20
5  libdispatch.dylib              0x13910 _dispatch_lane_barrier_sync_invoke_and_complete + 60
6  FinalcadOne                    0x119e35c FIRCLSExceptionRecord + 225 (FIRCLSException.mm:225)
7  FinalcadOne                    0x119e0a0 FIRCLSTerminateHandler() + 295 (FIRCLSException.mm:295)
8  libc++abi.dylib                0x12fa0 std::__terminate(void (*)()) + 20
9  libc++abi.dylib                0x12f2c std::terminate() + 48
10 libobjc.A.dylib                0x2891c objc_terminate + 16
11 libdispatch.dylib              0x4830 _dispatch_client_callout + 40
12 libdispatch.dylib              0xc004 _dispatch_lane_serial_drain + 620
13 libdispatch.dylib              0xcc00 _dispatch_lane_invoke + 404
14 libdispatch.dylib              0x174bc _dispatch_workloop_worker_thread + 764
15 libsystem_pthread.dylib        0x37a4 _pthread_wqthread + 276
16 libsystem_pthread.dylib        0xa74c start_wqthread + 8
```

It impacts iOS 14 and iOS 15 users, and also indicates `Fatal Exception: OdError`.

#### Steps to reproduce:

No steps to reproduce at the moment.

#### Relevant Code:

No relevant code known at the moment.

**Comment by rizafran** [comment]
Hi @zocario, thanks for reporting. Could you provide the full stack trace of the crash to see if the issue is related to Firebase? This might be related to #8886.

**Comment by zocario** [comment]
Thanks for the answer @rizafran I think you're right on this one this is not related to Firebase, it's just confusing that crashlytics is pointing to com.google.firebase.crashlytics.ios.exception but there is an other fatal exception on an other library we use. I'm closing the ticket.
