### ISSUE TITLE
Library and app has the same Firebase dependency causing an error

### ISSUE THREAD

**Issue by alekkania** [firebase/firebase-ios-sdk#9164]
Step 1: Describe your environment

  * Xcode version:  13.2.1
  * Firebase SDK version: 8.5.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: Firestore, Storage
  * Target platform(s): ` iOS `

Step 2: Describe the problem

I have added Firebase by SPM but also one of my SPM library use the same firebase version.
The problem is if the SPM library is linked then my app not build. I have this kind of error:
<img width="581" alt="Screenshot 2022-01-05 at 13 31 20" src="https://user-images.githubusercontent.com/29798202/148218572-242bfabc-c022-4564-a5e3-5ad711c0630c.png">

**Steps to reproduce:**

No steps to reproduce at the moment.

**Relevant Code:**

No relevant code known at the moment.

**Comment by ryanwilson** [comment]
Hi @alekkania - sorry for the troubles you're seeing. Is this a SPM library that you own, or an external one? We have some documentation on using Firebase in libraries here: https://github.com/firebase/firebase-ios-sdk/blob/master/docs/firebase_in_libraries.md

If that doesn't help, getting a better understanding of your use case (if it's your library or an external one) will help us provide some more guidance. Note that we also saw a similar error with SwiftUI Previews and code coverage enabled in the past (#6219).
