### ISSUE TITLE
Crashlytics auto launches the app

### ISSUE THREAD

**Issue by davidengler** [firebase/firebase-ios-sdk#9203]
### Discussed in https://github.com/firebase/firebase-ios-sdk/discussions/9194

<div type='discussions-op-text'>

<sup>Originally posted by **davidengler** January 11, 2022</sup>
After adding Crashlytics to apple watch application, I notice that the app is automatically launched every 5-15 minutes. Is this an expected behavior ?
</div>

**Comment by morganchen12** [comment]
@davidengler is this reproducible in an empty project with nothing but Crashlytics?

**Comment by davidengler** [comment]
@morganchen12 I don't know. I'm just wondering how can this be happening, because there is no way to programmatically start the watch app, just wondering does firebase have a way to start the watch app?
