### ISSUE TITLE
Usage of weak crypto algorithms like SHA1 in Firebase/Crashlytics iOS SDK

### ISSUE THREAD

**Issue by KishanLal** [firebase/firebase-ios-sdk#9205]
### Feature proposal

Our Penetration testing team has identified usage of weak crypto algorithms like SHA1 in Firebase iOS SDK and logged security vulnerability. What are the plans to migrate to latest crypto algorithms? Can you please migrate to latest crypto algorithms to mitigate this?

Recommendation:
Do not use weak cryptographic algorithms to protect information and processes such as RC4, DES, DES3, MD5, SHA1, MD4, ECB, & CBC as well as algorithms discussed here. For guidance on best practices in picking strong cryptography, please see OWASP's Cryptographic Storage Cheat_Sheet. Details and code snippets can be found at https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/encrypting_your_app_s_files(https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/encrypting_your_app_s_files).

**Comment by paulb777** [comment]
Please identify the specific code that is of concern and search this issue list to see if it has been addressed before.

**Comment by KishanLal** [comment]
- (NSData *)sha1WithData:(NSData *)data; method in FIRInstallationsIIDStore.m.
- Also attaching usage shared by security team:
[Firebase_SHA1-Usage.txt](https://github.com/firebase/firebase-ios-sdk/files/7881702/Firebase_SHA1-Usage.txt)

**Comment by paulb777** [comment]
This is a duplicate of #5447. Please see the analysis there.
