### ISSUE TITLE
[FPRNetworkTrace networkTraceFromObject:] Crashed

### ISSUE THREAD

**Issue by yusheng00** [firebase/firebase-ios-sdk#9208]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.2
  * Firebase SDK version: 8.1.0
  * Installation method: CocoaPods
  * Firebase Component: Core ,Performance, Messaging, Analytics, Crashlytics
  * Target platform(s): iOS 

### [REQUIRED] Step 2: Describe the problem

We used the FirebaseCrashlytics SDK and received such a crash report on the online platform. The probability of crashes is extremely low, please help to check, thanks

```
SIGSEGV 0x000000000000001c
0 libobjc.A.dylib lookUpImpOrForward + 59
1 (Missing)
2 libobjc.A.dylib _class_lookupMethodAndLoadCache3 + 26
3 libobjc.A.dylib _objc_msgSend_uncached + 14
4 Develop +[FPRNetworkTrace networkTraceFromObject:] + 22403101
5 Develop __InstrumentURLSessionTaskDidSendBodyDataTotalBytesSentTotalBytesExpectedToSend_block_invoke + 22416015
6 CFNetwork __86-[NSURLSession delegate_task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:]_block_invoke + 58
7 Foundation <redacted> + 8
8 Foundation <redacted> + 146
9 Foundation <redacted> + 770
10 Foundation <redacted> + 190
11 libdispatch.dylib _dispatch_queue_serial_drain + 854
12 libdispatch.dylib _dispatch_queue_invoke + 886
13 libdispatch.dylib _dispatch_root_queue_drain + 326
14 libdispatch.dylib _dispatch_worker_thread3 + 106
15 libsystem_pthread.dylib _pthread_wqthread + 1040
16 libsystem_pthread.dylib start_wqthread + 8
```

**Comment by paulb777** [comment]
It might help to update to a more recent version. I don't see this particular crash, but other crashes have been fixed since 8.1.0 that may be related.
