### ISSUE TITLE
Dynamic link install attribution matching fails without the clipboard on iOS

### ISSUE THREAD

**Issue by hsource** [firebase/firebase-ios-sdk#9219]
### Step 1: Describe your environment

  * Xcode version: 13.2.1
  * Firebase SDK version: 8.8.0
  * Installation method: `CocoaPods`
  * Firebase Component: Dynamic Links
  * Target platform(s): `iOS`

### [REQUIRED] Step 2: Describe the problem

The weak implicit matching for app deeplinks seem to never work.

#### Steps to reproduce:

1. Open a link for our app at [preview.page.link](https://preview.page.link/fb.wanderlog.com/?link=https://app.wanderlog.com/deepLink/?affiliateKey%3Dtest&apn=com.wanderlog.android&isi=1476732439&ibi=com.wanderlog.ios&ifl=https://apps.apple.com/app/apple-store/id1476732439?pt%3D120319851%26ct%3D%26mt%3D8&mt=8&pt=120319851) on iOS
2. Do NOT check the "Save my place in the app. A link will be copied" checkbox (attribution)
3. Inside the app, on-load, call `retrievePendingDynamicLink` and log the output using NSLog.

We expect to see a weak match, but we don't see a match at all.

#### Relevant Code:

[FIRDynamicLinkNetworking](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseDynamicLinks/Sources/FIRDynamicLinkNetworking.m#L209) makes the network request to the server, but the server may be where the error is

**Comment by rizafran** [comment]
Thanks for reporting, @hsource. Could you provide a sample project reproducing the behavior so that we can identify what's causing this?
