### ISSUE TITLE
Update minimum iOS version to 11

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#9222]
Also macOS to 10.13 and tvOS to 12

We're considering bumping minimum supported versions in the next major release. Please reply if you'd like future Firebase versions to continue supporting the older releases.

**Comment by Trite8Q1** [comment]
Hi @paulb777, 
I think an increase should be justified, there should be enough devices on the specified versions by now.

**Comment by paulb777** [comment]
One reason to update is that FirebaseFirestoreSwift.podspec requires 11

**Comment by paulb777** [comment]
After more consideration, there are not enough compelling reasons to make a breaking change on the minimum version support and it's relatively straight forward to leave it alone, along with some exceptions for a few newer libraries that need iOS 11 or 13.
