### ISSUE TITLE
AppCheck support for different Google Cloud Storage buckets

### ISSUE THREAD

**Issue by Semty** [firebase/firebase-ios-sdk#9228]
### Feature proposal

* Firebase Component: AppCheck

I'm not sure whether the question is actually correct, but we've encountered the following issue: 
- After enforcing Firebase AppCheck for Firebase Storage some content appears to be available even without correct AppCheck token
- It turned out that this content is not actually on our Firebase Storage bucket, but on an another one (still within our organisation though)
- Initially we thought that AppCheck enforcement would work for all buckets within our organisation (we even see the stats for all of them inside our firebase console), but as it is not the case the question rises: how could this issue be resolved and is there a workaround? The goal we have is to prevent minor fraud using AppCheck not only for our main bucket, but for others as well because we use them together in our apps

Thank you

**Comment by weixifan** [comment]
Thank you for your report. I have a few questions:

> "It turned out that this content is not actually on our Firebase Storage bucket, but on an another one (still within our organisation though)"

Is this other bucket in another project within your organization? (I want to be clear that the term **organization** has a special meaning in Google Cloud as an entity type. Please clarify whether you mean this kind of organization.) Or do you mean that there are some storage buckets that are being accessed directly through Cloud Storage (GCS), but not through the Cloud Storage for Firebase API? (The Firebase SDKs go through the latter.) The answer is different depending on what you mean here. I do want to point out that **Cloud Storage** and **Cloud Storage for Firebase** are different; they have different backends. The latter is protected by App Check, while the former is not directly protected, but see below for options.

If you have GCS buckets in other projects (that are already imported into Firebase) in your organization: consider protecting your Cloud Storage for Firebase service for all those other projects as well, and use **multiple App objects** in your SDK to access the buckets in the corresponding projects.

If you want to protect non-Firebase traffic to GCS buckets, there are some options. In a typical case, a non-Firebase traffic path uses a GCS bucket through **a server that the developer has full control over**. If so, consider following instructions in our [public docs](https://firebase.google.com/docs/app-check/custom-resource-backend) to protect that server from unwanted clients.

> Initially we thought that AppCheck enforcement would work for all buckets within our organisation (we even see the stats for all of them inside our firebase console)

App Check only works at the project level and not at the organization level. If you are sure that these buckets are all within the same Firebase project that is configured with App Check, and that they are exclusively accessed through Cloud Storage for Firebase (this condition is satisfied if, for example, all accesses are through the Firebase SDKs), then all these buckets should be protected. If not, please file a ticket with Firebase support and we will be able to investigate in more detail. Hope this helps!
