### ISSUE TITLE
Convert FIRAuthProvider.m constants into enum

### ISSUE THREAD

**Issue by Idomo** [firebase/firebase-ios-sdk#9236]
### Feature proposal

* Firebase Component: Auth

#### Description
Currently the file [FIRAuthProvider.m](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseAuth/Sources/AuthProvider/FIRAuthProvider.m) contains auth provider ids, as `constants`.
My request is to replace these with an `enum`, so it'll be easier to make `switch-case` block when needed.

It just makes a lot more sense than creating my own enum by manually copying the values from the file or make some non-convenience long and unnecessary `else-if`.
P.S. You may add as well case for `AppleProviderID` as `"apple.com"`.

#### Usage case example
Generate the correct credential for `reauthenticate(with: credential)` based on `Auth.auth().currentUser?.providerData.first?.providerID`.

**Comment by paulb777** [comment]
Implemented in `auth-swift` branch.
