### ISSUE TITLE
FR: upload-dsyms: tmp folder path argument

### ISSUE THREAD

**Issue by GermanVelibekovHouzz** [firebase/firebase-ios-sdk#9238]
Currently, the tool uses a constant default path placed in OS root for some temporary folder while processing dsyms. 
Ex: `/var/folders/2s/c8z_jl_j0r14sh5nzq1gtwq80000gn/T/F37BB83E-EFF5-4B47-B7C8-658C7E7F1184-67713-00034F35884D1DDD.zip`

It might be that our CI doesn't allow access to the root so we end up with dsyms still missing in Crashlytics:
![image](https://user-images.githubusercontent.com/81903043/150534161-afa41efd-0e24-4bb4-b372-15d595f3cef5.png)

Can you please provide an additional argument for the tool to define the path above?

Regards

**Comment by elenadoty** [comment]
Hi @GermanVelibekovHouzz,
Thanks for the feature request - this would be a useful flag to have. We'll look into adding it and let you know.

**Comment by themiswang** [comment]
This should be changed in [Crashlytics 10.12.0](https://firebase.google.com/support/release-notes/ios#version_10120_-_july_11_2023), related pr https://github.com/firebase/firebase-ios-sdk/pull/11463

Gonna close the feature request 🎉
