### ISSUE TITLE
FirebaseAppDelegateProxyEnabled breaks Facebook Swift login on Facebook SDK 4.42

### ISSUE THREAD

**Issue by vinayakpal** [firebase/firebase-ios-sdk#924]
Im working on an iOS app where I've provide 2 option for login into the app for user( Google & Facebook) by using Firebase SDK. Now I successfully integrate both login in my app which work perfectly in iOS-11 based app. But when I tried to login from iOS-10 device it never login from both Facebook as well as google. please help I'm suffering from this issue for very long.

**Comment by morganchen12** [comment]
There's not enough information in this issue to debug. Please fill out the issue template and include the version of Firebase Auth, the code you're using to integrate Firebase, and any errors in console, then re-open this issue.

**Comment by vinayakpal** [comment]
Currently I'm using Below mentioned version firebase pods in my project:
Using Firebase (4.10.1)
Using FirebaseABTesting (1.0.0)
Using FirebaseAnalytics (4.1.0)
Using FirebaseAuth (4.4.4)
Using FirebaseCore (4.0.17)
Using FirebaseInstanceID (2.0.9)
Using FirebaseRemoteConfig (2.1.2)

[google_signin.txt](https://github.com/firebase/firebase-ios-sdk/files/1822529/google_signin.txt)

Please check the above mention link where code file attached. I simply follows the firebase login step but it hasn't responding

**Comment by vinayakpal** [comment]
Kindly reopen this issue as it not has been solved

**Comment by vinayakpal** [comment]
is there any progress to solve this issue. please help urgently

**Comment by baolocdo** [comment]
Can you try using the flag **FirebaseAppDelegateProxyEnabled=NO** in the Info.plist and see if it solves the problem (Please follow the instruction in FIRAnalytics+AppDelegate.h if you decide to do so).
If it is still not working, can you try unlink one of Analytics or Auth from your app? We would like to determine which Firebase SDK is causing the issue. Thanks

**Comment by morganchen12** [comment]
@vinayakpal there are a number of issues with your implementation, including issues not specifically related to Firebase.

Please move your question to StackOverflow and make sure to include any relevant error messages when running your project.

**Comment by vinayakpal** [comment]
@morganchen12  I recently found that i forgot to enable keychain sharing in App Capability section. But later on I enable that but still no progress found in login. can you please help this regarding this keychain issue.

**Comment by tapannathvani** [comment]
We are facing the same issue, Just update the POD file and enabled key chain sharing also. Google sign in not coming back to the App. And it works well in iOS 11 but not in iOS 10.2.1. Any update ?

**Comment by nikhilbhalwankar** [comment]
Hi,

We are also facing the same issue. If we use FirebaseUI for Login via Google, browser page gets opened in iOS 10. Once login is completed, redirection does not happen. The user logs in browser wondow and control stays there only.

**Comment by pepasflo** [comment]
FWIW we appear to have just run into this issue when upgrading our cocoapods.

We had been using Facebook iOS SDK 4.34, then upgraded to 4.39 and a little bit later realized that we got hit by the "unknown error building URL" issue (https://github.com/facebook/facebook-swift-sdk/issues/298).  We then upgraded to 4.42, which caused Facebook login to work when using Safari, but not when using the Facebook app.

It appears that `FirebaseAppDelegateProxyEnabled=NO` fixed this issue.

Did something change regarding app delegate proxies between 4.34 and 4.42?

**Comment by morganchen12** [comment]
Hey all, sorry for the slow response here. The goal of the `FirebaseAppDelegateProxyEnabled` flag was to allow developers to choose between easy or simple, but it's woefully missing from our docs. I'll take a look at fixing that soon.

In the meantime, is this still an issue in Firebase 6+ and Facebook SDK 5+?
