### ISSUE TITLE
Could not resolve package dependencies: GoogleAppMeasurement

### ISSUE THREAD

**Issue by AhmedMorra1** [firebase/firebase-ios-sdk#9243]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.1
  * Firebase SDK version: 8.10.0
  * Installation method: Swift Package Manager
  * Firebase Component: Analytics
  * Target platform(s): iOS 

#### Steps to reproduce:

I am trying to add firebase to the iOS version of my flutter app 
and in the firebase site they said use the swift package manager, which they didn't before, I think before we used cocoapods to install the sdk but I followed the guideline
now when I try to run my app I get the following error

> Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           37.1s
Failed to build iOS app
Error output from Xcode build:
↳
    xcodebuild: error: Could not resolve package dependencies:
      failed extracting 'https://dl.google.com/firebase/ios/swiftpm/8.9.1/GoogleAppMeasurement.zip' which is required by binary target 'GoogleAppMeasurement': /Users/ahmedmorra/Library/Developer/Xcode/DerivedData/Runner-crhhpcrmwykqxpatmcfdjiwymsco/SourcePackages/artifacts/extract/GoogleAppMeasurement is not a directory
      fatalError
Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.

I looked on stackoverflow but got nothing, and I can't develop my app for iOs until I solve this

**Comment by ncooke3** [comment]
Hi @AhmedMorra1, sorry for the trouble. There could be something wrong with Xcode's configuration. Here are some simple troubleshooting steps to try:

1. Reset Swift PM package cache (In Xcode:  File → Packages → Reset Package Caches)
2. Resolve Swift PM package versions (In Xcode:  File → Packages → Resolve Package Versions)
3. Delete derived data (Xcode → Preferences → Locations → Click the small arrow next to the derived data path → Delete the folder in Finder)  Swift PM should try to reload your project's packages after doing this.

Try re-building your project after each of these steps and let me know if any of them work. Thanks!

**Comment by AhmedMorra1** [comment]
> Hi @AhmedMorra1, sorry for the trouble. There could be something wrong with Xcode's configuration. Here are some simple troubleshooting steps to try:
> 
> 1. Reset Swift PM package cache (In Xcode:  File → Packages → Reset Package Caches)
> 2. Resolve Swift PM package versions (In Xcode:  File → Packages → Resolve Package Versions)
> 3. Delete derived data (Xcode → Preferences → Locations → Click the small arrow next to the derived data path → Delete the folder in Finder)  Swift PM should try to reload your project's packages after doing this.
> 
> Try re-building your project after each of these steps and let me know if any of them work. Thanks!

Thanks for your help.
I tried everything but it didn't work, here is how i solved it.
I reverted to a previous commit where I didn't add the firebase sdk
then added just the googleservice_info.plist and didn't follow any other instruction on the firebase guide.
I ran the app and it worked
I just had to run flutter clean after adding Firebase Analytics so everything can work smoothly.

**Comment by paulb777** [comment]
Looks like the original post was mistakenly marked Swift Package Manager instead of CocoaPods for installation method.
