### ISSUE TITLE
Mark Auth `getStoredUser(forAccessGroup)` as unavailable for tvOS. 

### ISSUE THREAD

**Issue by ncooke3** [firebase/firebase-ios-sdk#9245]
This may be irrelevant by Firebase 9 pending updates in #8878

**Comment by paulb777** [comment]
If the API doesn't work now for tvOS, I don't think we need to wait for a breaking change release to mark it unavailable.

**Comment by paulb777** [comment]
@ncooke3 Should this be closed given the requirement to share on a single device?

**Comment by ncooke3** [comment]
Yes, thanks– I had not considered that case when I created this issue. Closing.
