### ISSUE TITLE
No such module 'FirebaseFirestoreSwift' in Xcode 13.2.1

### ISSUE THREAD

**Issue by GrosserStuhl** [firebase/firebase-ios-sdk#9246]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 13.2.1 (13C100)
  * Firebase SDK version: 8.11.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: Firestore
  * Target platform(s): `iOS`

### [REQUIRED] Step 2: Describe the problem
I need to serialize my custom objects, as described in the [official guide](https://firebase.google.com/docs/firestore/query-data/get-data#swift_3). For that, I need to add `FirebaseFirestoreSwift` to my class. And I believe I was able to build my code at least once without issues.
But then 1-2 days later I re-open my project and keep getting the error **`No such module 'FirebaseFirestoreSwift'`**.

What I already did:
- I have cleaned and re-build the project
- I have removed all Firebase packages, cleaned the project and added them again
- Added the `FirebaseFirestore` module too, which works fine, but it did not change anything

The error persists.

If I uncomment `import FirebaseFirestoreSwift`, it all works. But Xcode itself is suggesting this module for import when I start typing, so it must be present in the project:  

![This is an image](https://i.stack.imgur.com/zrFPU.png)

Any ideas what might be causing this error?

**Comment by paulb777** [comment]
Make sure that FirebaseFirestoreSwift is a dependency of the build target. See #9105. Also you may need to build to update Xcode's module cache.

**Comment by GrosserStuhl** [comment]
@paulb777 I followed the linked article. This is how it looks for me:

![image](https://user-images.githubusercontent.com/6041146/150695106-291a2b5a-85dc-43fb-9b2a-55c9c0ff5755.png)

It seems only `FirebaseFirestoreSwift-Beta` is available. The same was the case when I was adding the package initially, but I didn't add it because I assumed it only contains some fancy beta features that I don't need.

**Comment by GrosserStuhl** [comment]
I added `FirebaseFirestoreSwift-Beta` as a test and it seems to compile and run normally now. 

Weird because as seen in the image of my original post, the normal and beta part are two different modules that can be imported. So it surprises me that they would be contained in the beta branch.
