### ISSUE TITLE
In Notification Composer there is no "content_available" field

### ISSUE THREAD

**Issue by dariagss** [firebase/firebase-ios-sdk#925]
I need to put "content_available" : true in the aps payload, using Notification Composer. The problem is there is no such field and writing it into custom data as key value pair results in it being written not in the aps, but into the whole received data.
So here is content_available, but not in the aps.
`["content_available": true, "google.c.a.e": 1, "google.c.a.ts": 1521119125, "google.c.a.udt": 0, "gcm.notification.sound2": default, "gcm.n.e": 1,

 "aps": {
    alert = Test1;
    badge = 1;
    sound = default;
}`
How can I make it appear in the "aps" using Notification Composer?
Thank you in advance!

**Comment by paulb777** [comment]
Asked at https://stackoverflow.com/questions/49299142/how-to-add-content-available-to-firebase-notification-composer

**Comment by dariagss** [comment]
You mean there is no possibility to add content_available in notification composer?
That is my question as well and it is not answered(

**Comment by paulb777** [comment]
I added the link to save the bandwidth of answering the same question twice. I agree it is currently not answered.

**Comment by morganchen12** [comment]
This isn't likely to be supported soon. If you need the `mutable_content` flag, you'll have to use the HTTP protocol or one of the Admin SDKs.

Closing as it's not an iOS SDK issue.

**Comment by dariagss** [comment]
ok, thank you for answering.

**Comment by SVyatoslavG** [comment]
I'm having the same issue.
`mutable-content` would be a very useful feature in the Notification Composer because it allows to do A/B tests, target countries, languages etc, which is not a trivial task using HTTP protocol.
