### ISSUE TITLE
Dynamiclink url created from iOS not working when opened from Android

### ISSUE THREAD

**Issue by dsb92** [firebase/firebase-ios-sdk#926]
### Environment: 

  * Xcode version: 9.2
  * Firebase SDK version: 4.10.1
  * Firebase Component: Dynamic Link
  * Component version: 2.3.2

### Describe the problem:

When I'm using the SDK to shorten a link the link itself works perfectly on iOS. It opens the app and does everything as expected. But when sharing it to an android user, a webpage will open with the follow message "The requested URL was not found on this server. That’s all we know." from Google
This is only a problem when shorten a link from iOS. Everything works fine on both platforms when creating a long dynamic link. 

#### Steps to reproduce:

Shorten the follow link...
https://avxw5.goo.gl/?link=http://happenings-app.com?eventId%3DB68324A1-84FB-46E2-9B14-F46287E9C048&apn=com.app.happenings&ibi=com.happenings.events&isi=1284372989&dfl=http://happenings-app.com&st=DMA+Folk+2017&sd=GRATIS&amv=48&si=https://api.happenings-app.com/api/happenings/image?id%3D5259787B-9432-4409-AEC7-C30EF62A6AD8%26type%3D1%26scale%3D2

...with this method from the SDK:

components.shorten { (shortURL, warnings, error) in
  // Handle shortURL.
  if let error = error {
    print(error.localizedDescription)
    return
  }
  self.shortLink = shortURL
  print(self.shortLink?.absoluteString ?? "")
  // ...
}

#### Relevant Code:

Openings this shorten link
https://avxw5.app.goo.gl/EQfLEDGznK9xOzwe2

When not shorten the link becomes on iOS:
https://avxw5.app.goo.gl/?link=http://happenings-app.com?eventId%3DB68324A1-84FB-46E2-9B14-F46287E9C048&apn=com.app.happenings&ibi=com.happenings.events&isi=1284372989&dfl=http://happenings-app.com&st=DMA+Folk+2017&sd=GRATIS&amv=48&si=https://api.happenings-app.com/api/happenings/image?id%3D5259787B-9432-4409-AEC7-C30EF62A6AD8%26type%3D1%26scale%3D2

When and Android user opens the shorten link the link becomes 
https://goo.gl/app/avxw5/?link=http://happenings-app.com?eventId%3D1F1BEBC1-DB79-45E8-9C7E-280B01D705EA&apn=com.app.happenings&ibi=com.happenings.events&isi=1284372989&dfl=http://happenings-app.com&st=Sort+Sol+/+Train&sd=350+DKK&amv=48&si=https://api.happenings-app.com/api/happenings/image?id%3DEB21CE4F-BE94-4381-BDC1-55DB76175E1C%26type%3D1%26scale%3D2

Notice the baseUrl differences from iOS: https://avxw5.app.goo.gl and Android: https://goo.gl/app/avxw5.

It looks like the shorten method is broken.

**Comment by morganchen12** [comment]
Do shortened links on Android work on iOS as expected?

**Comment by dmandar** [comment]
This looks like the short link fails to redirect correctly on android. Following up with the team. Are links created in the console working for you across all platforms?

**Comment by dsb92** [comment]
@dmandar Nope, unfortunately it does not work from console either.

**Comment by dmandar** [comment]
To confirm, do dynamic links created in the console work on android for you?

**Comment by dmandar** [comment]
You can debug the link by appending ?d=1.  https://avxw5.app.goo.gl/EQfLEDGznK9xOzwe2?d=1 to check if android is enabled for the link. Pls reopen if still an issue.
