### ISSUE TITLE
CLS_BINARY_IMAGE_RUNTIME_NODE_COUNT is no longer enough for typical apps

### ISSUE THREAD

**Issue by saagarjha** [firebase/firebase-ios-sdk#9261]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Xcode Version 13.2 (13C100)
  * Firebase SDK version: Firebase Apple 8.11.0
  * Installation method: `Zip file`
  * Firebase Component: Crashlytics
  * Target platform(s): `All`

#### Steps to reproduce:

Firebase keeps around a static array of `CLS_BINARY_IMAGE_RUNTIME_NODE_COUNT` elements to track images loaded into the current process. The current value for this is 512, as it assumes that a typical app loads approximately 300 images. However, this limit has fallen out of date and is no longer sufficient for most apps, as even a "hello world" app that links just UIKit will load almost 400 images and a typical one will load over 700. Once Firebase goes over this limit, it stops tracking images and also logs a very expensive warning, hurting startup performance. I feel that it would be appropriate to increase this limit so that this is no longer an issue for most apps.

#### Relevant Code:

https://github.com/firebase/firebase-ios-sdk/blob/52890bfe7e3f3605e10039ccf4b5157376df0bbb/Crashlytics/Crashlytics/Components/FIRCLSBinaryImage.m#L411

Here is a sample fix: https://github.com/saagarjha/firebase-ios-sdk/commit/f18c38ae8f286d943268202c5f052545a664e713

**Comment by paulb777** [comment]
Merged fixed PR #9267 for upcoming 8.12.0 release
