### ISSUE TITLE
boringssl_metrics_log_metric_block_invoke(151) Failed to log metrics

### ISSUE THREAD

**Issue by andyjriley** [firebase/firebase-ios-sdk#9262]
### Step 0: Are you in the right place?

I believe so from the criteria that was mentioned.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.2.1
  * Firebase SDK version: 8.10.0
  * Installation method: Swift Package Manager
  * Firebase Component: Crashlytics, Core, Messaging
  * Target platform(s): iOS

#### Steps to reproduce:

I'm not sure what is happening or what is causing this issue. But I have seen this alert flood my logs and I am unable to determine what is causing it. This appears to happen when there is network request being made.  

2022-01-25 15:19:55.804767-0600 ReleaseLync[7254:3104026] [boringssl] boringssl_metrics_log_metric_block_invoke(151) Failed to log metrics
2022-01-25 15:19:55.997037-0600 ReleaseLync[7254:3104023] [boringssl] boringssl_metrics_log_metric_block_invoke(151) Failed to log metrics
2022-01-25 15:19:56.228541-0600 ReleaseLync[7254:3104104] [boringssl] boringssl_metrics_log_metric_block_invoke(151) Failed to log metrics

This log issue has appeared on multiple support sites with no solution. Any additional information on the problem would be very helpful.

**Comment by rizafran** [comment]
Thanks for reporting, @andyjriley. As mentioned on #9127, the boringssl warning may be harmless. Did you encounter any issues with the product you're using when this warning appeared?

**Comment by andyjriley** [comment]
There are no observable issues with the product with regards to this logged message. The problem that I am having is that it is very chatty which floods my console while developing and logging files in production. If there is a way to silence this alert that would be acceptable to me.

**Comment by paulb777** [comment]
I'm not sure we can do anything about this from a Firebase perspective since it looks like an Apple issue. See https://developer.apple.com/forums/thread/697026

**Comment by paulb777** [comment]
I'm going to close, but feel free to continue the discussion.
