### ISSUE TITLE
Cannot install the latest Firebase iOS SDK to Xcode 13.2 with SPM

### ISSUE THREAD

**Issue by emretopcu1234** [firebase/firebase-ios-sdk#9264]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.2
  * Firebase SDK version: Latest (or anything else)
  * Installation method: Swift Package Manager
  * Firebase Component: Cannot reach here unfortunately.
  * Target platform(s): iOS

### [REQUIRED] Step 2: Describe the problem
I cannot install Firebase to my app. I tried many different versions of Firebase iOS SDK, but none of them was installed. The progress bar remains stable at 0%.

<img width="2240" alt="Ekran Resmi 2022-01-27 02 34 26" src="https://user-images.githubusercontent.com/77531348/151265315-723c7e24-fca4-4841-a032-b340944d7b45.png">

**Comment by rr-matthew-benjamin** [comment]
I'm having a similar issue. I was able to clone the repo just fine but can't find the package in the SPM menu
![Untitled](https://user-images.githubusercontent.com/69278191/151427805-6740f705-6f6b-4224-ab26-1f3b9c411763.png)

**Comment by emretopcu1234** [comment]
I have made some research, and I have discovered that the problem was not because of Firebase, it was because of Xcode version 13.2. At that version, there was a bug about adding package dependencies. Now I updated my Xcode to 13.2.1 and the problem did not occur again. Sorry to open this issue about Firebase. I am closing it.

**Comment by rr-matthew-benjamin** [comment]
@emretopcu1234 I'm on `13.2.1`

**Comment by emretopcu1234** [comment]
Can you try "https://github.com/firebase/firebase-ios-sdk" or "github.com/firebase/firebase-ios-sdk" without .git suffix?
