### ISSUE TITLE
`kFirebaseInstallationsErrorDomain` missing `NS_SWIFT_NAME`

### ISSUE THREAD

**Issue by ryanwilson** [firebase/firebase-ios-sdk#9275]
https://github.com/firebase/firebase-ios-sdk/blob/bdac2b87f6d6e604deae914a970a75136b3a62b5/FirebaseInstallations/Source/Library/Public/FirebaseInstallations/FIRInstallationsErrors.h#L19

This is missing the `NS_SWIFT_NAME`, unfortunately fixing it is a breaking change. It should be named `InstallationsErrorDomain`.

**Comment by paulb777** [comment]
Merged #9395 into v9
