### ISSUE TITLE
Event parameters not reported in Crashlytics nor in Analytics

### ISSUE THREAD

**Issue by arielelkin** [firebase/firebase-ios-sdk#9285]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.2.1
  * Firebase SDK version: 8.10.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: Analytics
  * Target platform(s): `macOS`

#### Steps to reproduce:

Calling `FirebaseAnalytics.Analytics.logEvent(event.rawValue, parameters: properties)` logs the event in Firebase Crashlytics console, but doesn't log any of the attached parameters passed in `properties`:
![image](https://user-images.githubusercontent.com/1756909/152149863-bead126e-9ca8-4b04-86c6-0cb5bce18874.png)

Same happens in Analytics dashboard, the event is logged but none of the parameters appear:
![image](https://user-images.githubusercontent.com/1756909/152150756-e41064e8-b2e9-4f91-a09b-da6dc1b00ec0.png)

#### Relevant Code:

```swift
let properties = ["one": "uno", "two": "dos"]
FirebaseAnalytics.Analytics.logEvent(event.rawValue, parameters: properties)
```

**Comment by rizafran** [comment]
Thanks for reporting, @arielelkin. The event parameters must have custom dimensions or metrics created in order for them to appear in the report. Upon creating the custom dimension/metric of your event parameter, a data card with the details of your custom dimension/metric will appear in your event reporting. You may check this [link](https://support.google.com/firebase/answer/10075209?hl=en) for more details. Let me know if you have questions.

**Comment by arielelkin** [comment]
@rizafran thanks for your response. 

I realise i need to create new dimensions and metrics for these event parameters to show up in the analytics console. I've looked at the link you sent but it's not clear how to create them. When I try to create a custom metric, none of the event parameters prepopulated in the list correspond to the custom parameters I've tracked. 

[The docs seem to suggest that event logging is not yet supported on macOS](https://firebase.google.com/docs/analytics/events?platform=ios#log_events_2). Could that have anything to do with this?

**Comment by paulb777** [comment]
I believe those docs are out of date and macOS should now be supported. I'll reopen to investigate.

**Comment by ryanwilson** [comment]
Unrelated to the docs, I wasn't able to reproduce this. 

It's likely worth trying in a different project if possible to see if you have the same issue, and if not, contacting support to get a better view into the project.

![Screenshot showing parameters appearing](https://user-images.githubusercontent.com/1097316/152238434-62f475fe-7e35-4871-a13f-95def4e0d123.png)

**Comment by paulb777** [comment]
Thanks @ryanwilson! I'll assign to @morganchen12 to take a look at removing the macOS exception from the docs.

**Comment by morganchen12** [comment]
Done in internal cl 427008494.
