### ISSUE TITLE
Remove `FIRAppAssociationRegistration` class.

### ISSUE THREAD

**Issue by ryanwilson** [firebase/firebase-ios-sdk#9291]
This is no longer used in any Firebase SDK. I'm not sure when the last usage was removed, so it's safest to wait until the next breaking change to do so.

https://github.com/firebase/firebase-ios-sdk/blob/78b9b7fb10fa10d8605c865eb660b921afe0a27c/FirebaseCore/Sources/FIRAppAssociationRegistration.h#L27

**Comment by paulb777** [comment]
Merged into v9 branch
