### ISSUE TITLE
Test Messages not sent for 24 hours if already fetched

### ISSUE THREAD

**Issue by gaberogan** [firebase/firebase-ios-sdk#9293]
Are you in the right place?

Yes

Describe your environment

  * Xcode version: 13.0
  * Firebase SDK version: 14.2.2
  * Installation method: CocoaPods
  * Firebase Component: InAppMessaging
  * Target platform(s): iOS (React Native)

Describe the problem

The "Send a Test Message" documentation is broken and/or misleading. If you follow the instructions and install firebase + in app messaging and run your app, it will fetch messages and then give you an installation ID. So by the time you have your installation ID, it's decided it's not going to fetch for another 24 hours. So when you send a "Test on Device" message, it will not know to go into test mode. After 24 hours, it will fetch and your issue will go away until you delete your installation ID or use a different simulator device.

As a temporary fix I would suggest adding something like below to [the documentation](https://firebase.google.com/docs/in-app-messaging/get-started?platform=ios) page in a troubleshooting section. I have tested this and it works.

```objc
[[NSUserDefaults standardUserDefaults] setObject:[NSNumber numberWithInteger:1] forKey: @"firebase-iam-sdk-mode"];
[FIRApp configure];
```

As a more permanent solution, I would suggest detecting a development environment or allow the user to specify dev mode in a config. In that case there is no good reason to break everyone's testing on a new device for 24 hours.

#### Steps to reproduce:

See steps above

#### Relevant Code:

https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseInAppMessaging/Sources/Flows/FIRIAMFetchFlow.m#L141
read to the end

**Comment by rizafran** [comment]
Thanks for reporting, @gaberogan. Could you clarify on what you mean by "so when you send a "Test on Device" message, it will not know to go into test mode"?

I tried to follow the [documentation](https://firebase.google.com/docs/in-app-messaging/get-started?platform=ios#send_a_test_message) on sending a test message, and I was able to send and receive the notification multiple times. Could you confirm if we're on the same page?

**Comment by gaberogan** [comment]
Hi @rizafran, by "Test on Device" I mean this test on device feature screenshotted below. By "test mode", I am referring the SDK mode [found here](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseInAppMessaging/Sources/Runtime/FIRIAMSDKModeManager.m), one of "Testing Instance", "Regular", "Newly Installed".

I could have been more clear about how to reproduce the error.
1. In Firebase, create an in app message to send to everyone.
2. Start the app with user defaults set to "Regular" mode with a recent fetch timestamp. If you want to get into this mode naturally, you can probably just run your app and you'll receive the message you created. Otherwise, running your app with something like this should work:
```objc
[[NSUserDefaults standardUserDefaults] setValue: @"Regular" forKey: @"firebase-iam-sdk-mode"];
[[NSUserDefaults standardUserDefaults] setValue: [NSDate date] forKey: @"firebase-iam-last-fetch-timestamp"]; // not tested
[FIRApp configure];
```
3. Click "Test on Device" to send a test message.
4. Restart your app to receive the message. You won't receive the message because the app thinks you're a normal device in production and won't fetch your test message. However as a developer this breaks your test flow.

<img width="963" alt="Screen Shot 2022-02-10 at 1 55 25 PM" src="https://user-images.githubusercontent.com/58148287/153477166-8c093ad6-7545-4b07-8982-970e195e565e.png">

**Comment by rizafran** [comment]
Same, I'm unable to reproduce it as well. I'm getting this in my logs "OK to fetch due to current SDK mode being Testing Instance" when clicking the "Test on device" button to send a test message.

**Comment by morganchen12** [comment]
@gaberogan is this still an issue?
