### ISSUE TITLE
Crashed: com.google.fira.worker [APMMeasurement fetchRemoteConfig

### ISSUE THREAD

**Issue by EugeneGordin2303** [firebase/firebase-ios-sdk#9308]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.2.1
  * Firebase SDK version: 8.11.0
  * Installation method: CocoaPods 
  * Firebase Component:  Core
  * Target platform(s): iOS

### [REQUIRED] Step 2: Describe the problem

Got a crash report, here is the stack:

```
Crashed: com.google.fira.worker
0  libdyld.dylib                  0x1df0 dyld3::closure::Image::containsAddress(void const*, void const*, unsigned char*) const + 44
1  libdyld.dylib                  0xd254 invocation function for block in dyld3::AllImages::infoForNonCachedImageMappedAt(void const*, void (dyld3::LoadedImage const&, unsigned char) block_pointer) const + 88
2  libdyld.dylib                  0xd254 invocation function for block in dyld3::AllImages::infoForNonCachedImageMappedAt(void const*, void (dyld3::LoadedImage const&, unsigned char) block_pointer) const + 88
3  libdyld.dylib                  0xd13c dyld3::AllImages::infoForNonCachedImageMappedAt(void const*, void (dyld3::LoadedImage const&, unsigned char) block_pointer) const + 228
4  libdyld.dylib                  0xce58 dyld3::AllImages::infoForImageMappedAt(void const*, dyld3::MachOLoaded const**, unsigned long long*, char const**) const + 388
5  libdyld.dylib                  0x11b2c dyld3::dyld_image_header_containing_address(void const*) + 72
6  libsystem_trace.dylib          0xe820 _os_log_impl_flatten_and_send + 2016
7  libsystem_trace.dylib          0x11168 _os_log_with_args_impl + 400
8  CoreFoundation                 0x11eee4 _CFLogvEx3 + 188
9  CoreFoundation                 0x11f3d4 CFLog + 80
10 CFNetwork                      0x40e0 (Missing UUID 32dfbf260bc43fb89aeb35182c8b35fa)
11 CFNetwork                      0x3e48 (Missing UUID 32dfbf260bc43fb89aeb35182c8b35fa)
12 CFNetwork                      0x3c374 _CFHTTPMessageSetResponseProxyURL + 26776
13 CFNetwork                      0x25ff8 CFNetServiceBrowserSearchForServices + 91440
14 GoogleUtilities                0xeb8c -[GULNetworkURLSession sessionIDFromAsyncGETRequest:completionHandler:] + 312
15 GoogleUtilities                0xd298 -[GULNetwork getURL:headers:queue:usingBackgroundSession:completionHandler:] + 456
16 MyApp12345                 0x2c8034 -[APMMeasurement fetchRemoteConfig] + 652
17 MyApp12345                 0x2c39bc -[APMMeasurement uploadData] + 3084
18 MyApp12345                 0x2c282c __32-[APMMeasurement updateSchedule]_block_invoke_2 + 36
19 MyApp12345                 0x3082a0 __51-[APMScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke + 44
20 libdispatch.dylib              0x1bb0 _dispatch_call_block_and_release + 32
21 libdispatch.dylib              0x300c _dispatch_client_callout + 20
22 libdispatch.dylib              0x9484 _dispatch_lane_serial_drain + 568
23 libdispatch.dylib              0x9eb0 _dispatch_lane_invoke + 368
24 libdispatch.dylib              0x12f20 _dispatch_workloop_worker_thread + 580
25 libsystem_pthread.dylib        0x3aa0 _pthread_wqthread + 280
26 libsystem_pthread.dylib        0x9c78 start_wqthread + 8
```

#### Steps to reproduce:

Don't have the steps unfortunately.

**Comment by EugeneGordin2303** [comment]
Update: after couple more days I see more crashes, but all of them are from iOS 13.1.3. Hope this helps.

**Comment by EugeneGordin2303** [comment]
Here is another log from the same user that has more crashes.
Crashed: com.google.fira.worker
0  libdyld.dylib                  0x33d0 dyld3::closure::ObjCStringTable::hash(char const*, unsigned long) const + 16
1  libdyld.dylib                  0x3a60 dyld3::closure::ObjCStringTable::getIndex(char const*) const + 56
2  libdyld.dylib                  0x38d4 dyld3::closure::ObjCClassOpt::forEachClass(char const*, dyld3::Array<std::__1::pair<unsigned long, unsigned long> > const&, void (void*, bool, bool*) block_pointer) const + 56
3  libdyld.dylib                  0x10d48 dyld3::AllImages::forEachObjCClass(char const*, void (void*, bool, bool*) block_pointer) const + 140
4  libobjc.A.dylib                0x21f98 getPreoptimizedClass + 164
5  libobjc.A.dylib                0xcec0 getClassExceptSomeSwift(char const*) + 24
6  libobjc.A.dylib                0xdd20 look_up_class + 96
7  CoreFoundation                 0x11454 -[__NSCFNumber description] + 52
8  CoreFoundation                 0x11aa4 -[NSArray componentsJoinedByString:] + 272
9  MyApp12345                 0x314e30 -[APMSqliteStore monitorContextForDatabaseOperation:] + 544
10 MyApp12345                 0x314ee0 -[APMSqliteStore setDatabaseError:operation:] + 92
11 MyApp12345                 0x312b44 -[APMSqliteStore numberForQuery:parameterValues:error:] + 444
12 MyApp12345                 0x3055b8 -[APMRemoteConfig lastRemoteConfigUpdateTimestamp] + 140
13 MyApp12345                 0x3054b8 -[APMRemoteConfig isExpired] + 176
14 MyApp12345                 0x2c2ee8 -[APMMeasurement uploadData] + 312
15 MyApp12345                 0x2c282c __32-[APMMeasurement updateSchedule]_block_invoke_2 + 36
16 MyApp12345                 0x3082a0 __51-[APMScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke + 44
17 libdispatch.dylib              0x1bb0 _dispatch_call_block_and_release + 32
18 libdispatch.dylib              0x300c _dispatch_client_callout + 20
19 libdispatch.dylib              0x9484 _dispatch_lane_serial_drain + 568
20 libdispatch.dylib              0x9eb0 _dispatch_lane_invoke + 368
21 libdispatch.dylib              0x12f20 _dispatch_workloop_worker_thread + 580
22 libsystem_pthread.dylib        0x3aa0 _pthread_wqthread + 280

could be related

**Comment by morganchen12** [comment]
The top lines of these stack traces indicate something crashing in the Objective-C runtime, which are likely not caused by Analytics (at least not directly). Can you reproduce this crash by running your app with memory diagnostics enabled?
