### ISSUE TITLE
Uploading Image Data to Firebase Storage returns FIRStorageErrorDomain Code=-13000 error

### ISSUE THREAD

**Issue by EverglowingComet** [firebase/firebase-ios-sdk#9312]
#### Relevant Code:

```

    public func uploadImageFileToStorage(id: String, type: String, uiImage: UIImage, listener: FirebaseStorageListener) {
        guard let data = uiImage.pngData() else {
            listener.onFailure(nil)
            return
        }
        
        let metaData = StorageMetadata()
        metaData.contentType = "image/png"
        
        let fileRef = storageRef.child("image").child(type).child(id + ".image")
        
        let _ = fileRef.putData(data, metadata: metaData) { (metadata, error) in
            
            guard let _ = metadata else {
                listener.onFailure("no MetaData Returned")
                return
            }
            
            fileRef.downloadURL { (url, error) in
                guard let downloadURL = url else {
                    listener.onFailure("no downloadURL Returned")
                    return
                }
                listener.onSuccess(downloadURL)
            }
            
        }
        
    }
    
```

  * I have code using put file also but it gives same error

putData function callback gives error as following

```
Error Domain=
FIRStorageErrorDomain Code=-13000 "An unknown error occurred, please check the server response." 
UserInfo={
NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9820, NSErrorFailingURLStringKey=https://firebasestorage.googleapis.com/v0/b/live-edb25.appspot.com/o/image%2Fprofile%2Fphoto%2F-MhamDZFNw6eA7sNz3wt.image?uploadType=resumable&name=image%2Fprofile%2Fphoto%2F-MhamDZFNw6eA7sNz3wt.image&upload_id=ADPycdsjYPoOU3fW7GlalKSlEyDjEa4Nfw6JLBjlElCD3cOG9g_KGMzHS506mTKQ-wkTXastvmiM3OahwLDJcDCu44mbAdF-YA&upload_protocol=resumable, NSErrorFailingURLKey=https://firebasestorage.googleapis.com/v0/b/live-edb25.appspot.com/o/image%2Fprofile%2Fphoto%2F-MhamDZFNw6eA7sNz3wt.image?uploadType=resumable&name=image%2Fprofile%2Fphoto%2F-MhamDZFNw6eA7sNz3wt.image&upload_id=ADPycdsjYPoOU3fW7GlalKSlEyDjEa4Nfw6JLBjlElCD3cOG9g_KGMzHS506mTKQ-wkTXastvmiM3OahwLDJcDCu44mbAdF-YA&upload_protocol=resumable, NSUnderlyingError=0x281609650 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9820, _kCFNetworkCFStreamSSLErrorOriginalValue=-9820}}, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalUploadTask <BA67EBC2-75DD-4A85-9B6E-44B0092304A2>.<1>"
),
 _NSURLErrorFailingURLSessionTaskErrorKey=LocalUploadTask <BA67EBC2-75DD-4A85-9B6E-44B0092304A2>.<1>, bucket=live-edb25.appspot.com, ResponseErrorDomain=NSURLErrorDomain, object=image/profile/photo/-MhamDZFNw6eA7sNz3wt.image, ResponseErrorCode=-1200, NSLocalizedDescription=An unknown error occurred, please check the server response.
}
```
Can you guys help me to get rid of this?

**Comment by rizafran** [comment]
Thanks for reporting @EverglowingComet. It seems like the error you shared is related to #8148. One possible cause for this is due to the network problems, the connection was interrupted and the upload process couldn't be completed. Could you verify if the issue is reproducible using a different network?

**Comment by EverglowingComet** [comment]
Thank you @rizafran for answering.
But I guess it is not network problem.
I am facing it everytime and everywhere I use firebase storage upload function.
And my partner tested on Canada, he experience same issue. so I don't think this is network issue.

**Comment by rizafran** [comment]
@EverglowingComet, could you share what SDK version you're using?

**Comment by 66pig** [comment]
I have the same question when I upload a video

`Failed upload of video: Error Domain=FIRStorageErrorDomain Code=-13000 "An unknown error occurred, please check the server response." UserInfo={bucket=gameofchats-7fb31.appspot.com, _NSURLErrorFailingURLSessionTaskErrorKey=BackgroundUploadTask <67A7DCE9-1A46-4962-AFAD-0011C2D4AD30>.<1>, object=message_movies/9DC757CB-2BA9-4265-B102-62015D6E24B6.mov, _NSURLErrorRelatedURLSessionTaskErrorKey=(
`

my code:
`
let filename = UUID().uuidString + ".mov"
let storageRef = Storage.storage().reference().child("message_movies").child(filename)
storageRef.putFile(from: videoUrl, metadata: nil) { _, error in
    if let error = error {
        print("Failed upload of video:", error)
        return
    }
    
    storageRef.downloadURL { downloadUrl, error in
        if let error = error {
            print(error)
            return
        }
        
        guard let url = downloadUrl?.absoluteString else { return }
        print(url)
    }
}
`

**Comment by 66pig** [comment]
> 我上传视频时也有同样的问题
> 
> `Failed upload of video: Error Domain=FIRStorageErrorDomain Code=-13000 "An unknown error occurred, please check the server response." UserInfo={bucket=gameofchats-7fb31.appspot.com, _NSURLErrorFailingURLSessionTaskErrorKey=BackgroundUploadTask <67A7DCE9-1A46-4962-AFAD-0011C2D4AD30>.<1>, object=message_movies/9DC757CB-2BA9-4265-B102-62015D6E24B6.mov, _NSURLErrorRelatedURLSessionTaskErrorKey=( `
> 
> 我的代码：
> 
> ```
> let filename = UUID().uuidString + ".mov"
> let storageRef = Storage.storage().reference().child("message_movies").child(filename)
> storageRef.putFile(from: videoUrl, metadata: nil) { _, error in
>     if let error = error {
>         print("Failed upload of video:", error)
>         return
>     }
>     
>     storageRef.downloadURL { downloadUrl, error in
>         if let error = error {
>             print(error)
>             return
>         }
>         
>         guard let url = downloadUrl?.absoluteString else { return }
>         print(url)
>     }
> }
> ```

But, putData to upload Image has no question for me
