### ISSUE TITLE
Crash on launch, SIGABRT Crashed: com.google.firebase.crashlytics.ios.exception

### ISSUE THREAD

**Issue by avadhutredekar** [firebase/firebase-ios-sdk#9316]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.2.1 
  * Firebase SDK version: 8.9.0
  * Installation method: `CocoaPods`
  * Firebase Component: FirebaseCrashlytics
  * Target platform(s): `iOS`

### [REQUIRED] Step 2: Describe the problem

We are observing 33 crashes affecting 33 users (within 2 days after release). All on iOS 14+ devices.
`Fatal Exception: std::bad_alloc` is the reason for crash it seems.
I think another thread is crashing, but I'm not sure which one.

#### Steps to reproduce:
I only have the Crashlytics logs. This is not reproducible while debugging.

#### Crashlytics stack trace:

<pre><code>Fatal Exception: std::bad_alloc
</code></pre>

<pre><code>Crashed: com.google.firebase.crashlytics.ios.exception
0  GoPartner                      0x18c0f0 FIRCLSProcessRecordAllThreads + 393 (FIRCLSProcess.c:393)
1  GoPartner                      0x18c4d0 FIRCLSProcessRecordAllThreads + 424 (FIRCLSProcess.c:424)
2  GoPartner                      0x183840 FIRCLSHandler + 34 (FIRCLSHandler.m:34)
3  GoPartner                      0x17df64 __FIRCLSExceptionRecord_block_invoke + 218 (FIRCLSException.mm:218)
4  libdispatch.dylib              0x4670 _dispatch_client_callout + 20
5  libdispatch.dylib              0x138c4 _dispatch_lane_barrier_sync_invoke_and_complete + 56
6  GoPartner                      0x17d700 FIRCLSExceptionRecord + 225 (FIRCLSException.mm:225)
7  GoPartner                      0x17d39c FIRCLSTerminateHandler() + 285 (FIRCLSException.mm:285)
8  libc++abi.dylib                0x12f58 std::__terminate(void (*)()) + 20
9  libc++abi.dylib                0x15efc __cxa_rethrow + 148
10 libobjc.A.dylib                0x17cac objc_exception_rethrow + 44
11 CoreFoundation                 0x1f554 CFRunLoopRunSpecific + 836
12 GraphicsServices               0x138c GSEventRunModal + 164
13 UIKitCore                      0x51a088 -[UIApplication _run] + 1100
14 UIKitCore                      0x298958 UIApplicationMain + 2092
15 libswiftUIKit.dylib            0x30fa0 UIApplicationMain(_:_:_:_:) + 104
16 GoPartner                      0x8c18 main + 4311223320 (SplashScreenViewController.swift:4311223320)
17 ???                            0x105455aa4 (Missing)</code></pre>

<pre><code>com.apple.root.default-qos
0  libsystem_kernel.dylib         0x4b44 poll + 8
1  GoPartner                      0x1569cb4 pollset_work(grpc_pollset*, grpc_pollset_worker**, long long) + 101328
2  GoPartner                      0x158d110 cq_next(grpc_completion_queue*, gpr_timespec, void*) + 31616
3  GoPartner                      0x137f86c __33-[GMTDx_GRPCCompletionQueue init]_block_invoke_2 + 280192
4  libdispatch.dylib              0x2924 _dispatch_call_block_and_release + 32
5  libdispatch.dylib              0x4670 _dispatch_client_callout + 20
6  libdispatch.dylib              0x7798 _dispatch_queue_override_invoke + 792
7  libdispatch.dylib              0x15de0 _dispatch_root_queue_drain + 396
8  libdispatch.dylib              0x16608 _dispatch_worker_thread2 + 164
9  libsystem_pthread.dylib        0x10b8 _pthread_wqthread + 228
10 libsystem_pthread.dylib        0xe94 start_wqthread + 8</code></pre>

<pre><code>com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x1504 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b9c mach_msg + 76
2  CoreFoundation                 0x7738 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xba2c __CFRunLoopRun + 1212
4  CoreFoundation                 0x1f468 CFRunLoopRunSpecific + 600
5  Foundation                     0x18c94 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236
6  Foundation                     0x59dc8 -[NSRunLoop(NSRunLoop) runUntilDate:] + 92
7  UIKitCore                      0x493230 -[UIEventFetcher threadMain] + 524
8  Foundation                     0x6840c __NSThread__start__ + 808
9  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
10 libsystem_pthread.dylib        0xea0 thread_start + 8</code></pre>

<pre><code>com.google.firebase.crashlytics.MachExceptionServer
0  libsystem_kernel.dylib         0x1504 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b9c mach_msg + 76
2  GoPartner                      0x1860fc FIRCLSMachExceptionServer + 194 (FIRCLSMachException.c:194)
3  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
4  libsystem_pthread.dylib        0xea0 thread_start + 8</code></pre>

<pre><code>AVAudioSession Notify Thread
0  libsystem_kernel.dylib         0x1504 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b9c mach_msg + 76
2  CoreFoundation                 0x7738 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xba2c __CFRunLoopRun + 1212
4  CoreFoundation                 0x1f468 CFRunLoopRunSpecific + 600
5  AudioSession                   0x6308 CADeprecated::GenericRunLoopThread::Entry(void*) + 164
6  AudioSession                   0xfd64 CADeprecated::CAPThread::Entry(CADeprecated::CAPThread*) + 92
7  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
8  libsystem_pthread.dylib        0xea0 thread_start + 8</code></pre>

<pre><code>com.google.Maps.LabelingBehavior
0  libsystem_kernel.dylib         0x1504 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b9c mach_msg + 76
2  CoreFoundation                 0x7738 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xba2c __CFRunLoopRun + 1212
4  CoreFoundation                 0x1f468 CFRunLoopRunSpecific + 600
5  Foundation                     0x18c94 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236
6  GoPartner                      0x1d28e68 -[GMSx_GTMSimpleWorkerThread main] + 552532
7  Foundation                     0x6840c __NSThread__start__ + 808
8  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
9  libsystem_pthread.dylib        0xea0 thread_start + 8</code></pre>

<pre><code>com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x1504 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b9c mach_msg + 76
2  CoreFoundation                 0x7738 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xba2c __CFRunLoopRun + 1212
4  CoreFoundation                 0x1f468 CFRunLoopRunSpecific + 600
5  CFNetwork                      0x27a3f0 _CFURLStorageSessionCopyIdentifier + 59784
6  Foundation                     0x6840c __NSThread__start__ + 808
7  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
8  libsystem_pthread.dylib        0xea0 thread_start + 8</code></pre>

<pre><code>com.apple.CFStream.LegacyThread
0  libsystem_kernel.dylib         0x1504 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b9c mach_msg + 76
2  CoreFoundation                 0x7738 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xba2c __CFRunLoopRun + 1212
4  CoreFoundation                 0x1f468 CFRunLoopRunSpecific + 600
5  CoreFoundation                 0x107b20 _legacyStreamRunLoop_workThread + 300
6  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
7  libsystem_pthread.dylib        0xea0 thread_start + 8</code></pre>

<pre><code>com.apple.CFSocket.private
0  libsystem_kernel.dylib         0x21d0 select$DARWIN_EXTSN + 8
1  libsystem_kernel.dylib         0x21d0 __select + 8
2  CoreFoundation                 0xaa7f0 __CFSocketManager + 648
3  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
4  libsystem_pthread.dylib        0xea0 thread_start + 8</code></pre>

<pre><code>default-executor
0  libsystem_kernel.dylib         0x1f90 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8254 _pthread_cond_wait + 1228
2  GoPartner                      0x182504c GMTDx_absl::synchronization_internal::Waiter::Wait(GMTDx_absl::synchronization_internal::KernelTimeout) + 2528
3  GoPartner                      0x17eb788 GMTDx_AbslInternalPerThreadSemWait + 7780
4  GoPartner                      0x1e7f490 GMTDx_absl::CondVar::WaitCommon(GMTDx_absl::Mutex*, GMTDx_absl::synchronization_internal::KernelTimeout) + 949844
5  GoPartner                      0x1790fb0 GMTDx_gpr_cv_wait + 6392
6  GoPartner                      0x156c51c GMTDx_grpc_core::Executor::ThreadMain(void*) + 5352
7  GoPartner                      0x179fa64 (anonymous namespace)::ThreadBodyWithCleanup(void (*)(void*), void*, (anonymous namespace)::ThreadInternalsGoogleThread*) + 264
8  GoPartner                      0x17bf644 GMTDx_Thread::ThreadBody(void*) + 12876
9  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
10 libsystem_pthread.dylib        0xea0 thread_start + 8</code></pre>

<pre><code>resolver-executor
0  libsystem_kernel.dylib         0x1f90 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8254 _pthread_cond_wait + 1228
2  GoPartner                      0x182504c GMTDx_absl::synchronization_internal::Waiter::Wait(GMTDx_absl::synchronization_internal::KernelTimeout) + 2528
3  GoPartner                      0x17eb788 GMTDx_AbslInternalPerThreadSemWait + 7780
4  GoPartner                      0x1e7f490 GMTDx_absl::CondVar::WaitCommon(GMTDx_absl::Mutex*, GMTDx_absl::synchronization_internal::KernelTimeout) + 949844
5  GoPartner                      0x1790fb0 GMTDx_gpr_cv_wait + 6392
6  GoPartner                      0x156c51c GMTDx_grpc_core::Executor::ThreadMain(void*) + 5352
7  GoPartner                      0x179fa64 (anonymous namespace)::ThreadBodyWithCleanup(void (*)(void*), void*, (anonymous namespace)::ThreadInternalsGoogleThread*) + 264
8  GoPartner                      0x17bf644 GMTDx_Thread::ThreadBody(void*) + 12876
9  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
10 libsystem_pthread.dylib        0xea0 thread_start + 8</code></pre>

<pre><code>grpc_global_timer
0  libsystem_kernel.dylib         0x1f90 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8254 _pthread_cond_wait + 1228
2  GoPartner                      0x182504c GMTDx_absl::synchronization_internal::Waiter::Wait(GMTDx_absl::synchronization_internal::KernelTimeout) + 2528
3  GoPartner                      0x17eb788 GMTDx_AbslInternalPerThreadSemWait + 7780
4  GoPartner                      0x1e7f490 GMTDx_absl::CondVar::WaitCommon(GMTDx_absl::Mutex*, GMTDx_absl::synchronization_internal::KernelTimeout) + 949844
5  GoPartner                      0x1790fb0 GMTDx_gpr_cv_wait + 6392
6  GoPartner                      0x157ccf0 timer_thread(void*) + 45756
7  GoPartner                      0x179fa64 (anonymous namespace)::ThreadBodyWithCleanup(void (*)(void*), void*, (anonymous namespace)::ThreadInternalsGoogleThread*) + 264
8  GoPartner                      0x17bf644 GMTDx_Thread::ThreadBody(void*) + 12876
9  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
10 libsystem_pthread.dylib        0xea0 thread_start + 8</code></pre>

<pre><code>grpc_global_timer
0  libsystem_kernel.dylib         0x1f90 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8254 _pthread_cond_wait + 1228
2  GoPartner                      0x1825018 GMTDx_absl::synchronization_internal::Waiter::Wait(GMTDx_absl::synchronization_internal::KernelTimeout) + 2476
3  GoPartner                      0x17eb788 GMTDx_AbslInternalPerThreadSemWait + 7780
4  GoPartner                      0x1e7f490 GMTDx_absl::CondVar::WaitCommon(GMTDx_absl::Mutex*, GMTDx_absl::synchronization_internal::KernelTimeout) + 949844
5  GoPartner                      0x1790fa0 GMTDx_gpr_cv_wait + 6376
6  GoPartner                      0x157ccf0 timer_thread(void*) + 45756
7  GoPartner                      0x179fa64 (anonymous namespace)::ThreadBodyWithCleanup(void (*)(void*), void*, (anonymous namespace)::ThreadInternalsGoogleThread*) + 264
8  GoPartner                      0x17bf644 GMTDx_Thread::ThreadBody(void*) + 12876
9  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
10 libsystem_pthread.dylib        0xea0 thread_start + 8</code></pre>

<pre><code>com.apple.coreaudio.AQClient
0  libsystem_kernel.dylib          0x1504 mach_msg_trap + 8
1  libsystem_kernel.dylib          0x1b9c mach_msg + 76
2  CoreFoundation                  0x7738 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                  0xba2c __CFRunLoopRun + 1212
4  CoreFoundation                  0x1f468 CFRunLoopRunSpecific + 600
5  AudioToolbox                    0x1cfe10 <redacted> + 164
6  libAudioToolboxUtility.dylib    0x140f8 CADeprecated::CAPThread::Entry(CADeprecated::CAPThread*) + 92
7  libsystem_pthread.dylib         0x19a4 _pthread_start + 148
8  libsystem_pthread.dylib         0xea0 thread_start + 8</code></pre>

<pre><code>Thread
0  libsystem_kernel.dylib         0x1b2c __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1140 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xe94 start_wqthread + 8</code></pre>

There are also a few more threads like the one above which I don't think are relevant.

Thanks!

**Comment by morganchen12** [comment]
The Crashlytics thread is _probably_ not causing the exception that crashes your app, since the code in the stack trace only runs when a crash has already been triggered in order to capture crash information.

The error message `std::bad_alloc` suggests a C++ allocation failed, possibly due to memory pressure. None of the other threads are particularly suspect, so this seems likely. Can you profile your app for memory leaks and high memory usage?
