### ISSUE TITLE
didReceiveRemoteNotification not called in ios 15.3

### ISSUE THREAD

**Issue by abdoh476** [firebase/firebase-ios-sdk#9317]
* Xcode version: 13.2.1
  * Firebase SDK version: 8.11
  * Installation method: CocoaPods 
  * Firebase Component: Messaging
  * Target platform(s): iOS

Now i am sending an voip notification to ios devices 
i can receive it in didReceiveRemoteNotification with all ios versions but in ios 15.3 I can't get didReceiveRemoteNotification called to report for the incoming call 
#### Steps to reproduce:
I am sending this aps with nodeJs backend to ios device
`AnyHashable("aps"): {
    alert =     {
        body = "body";
        title = title;
    };
    badge = 1;
    "content-available" = 1;
    "mutable-content" = 1;
    sound = "Ringtone.caf";
}`

I can get didReceiveRemoteNotification called and everything being normal but not in ios 15.3

what I can do now ?

**Comment by rizafran** [comment]
Hi @abdoh476, I've tried to reproduce this using iOS 15.3, but I was able to receive a notification and `didReceiveRemoteNotification` was also called. Could you confirm if you have encountered any errors? Also, is it possible for you to try [sending a test message](https://firebase.google.com/docs/cloud-messaging/ios/first-message#send_a_notification_message) in order to isolate the issue?

**Comment by abdoh476** [comment]
Hi @rizafran , first of all thanks for your replay.
First I receive an notification from firebase console as a test notification but it's not called inside 
`func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any],
                     fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void){}`
 it gets called inside 
 `func userNotificationCenter(_ center: UNUserNotificationCenter,
                                didReceive response: UNNotificationResponse,
                                withCompletionHandler completionHandler: @escaping () -> Void) {}`
and the notification sent don't have the content-available flag that needed to wake up the device and then I can report incoming call to the callKit 

So it's already working only with any version below 15.3

So the problem is still exist and don't know what to do next ....

**Comment by chliangGoogle** [comment]
@abdoh476 Based on your original description, you use node.js to send notification and payload contains "content-available" = 1. That is a different scenario with your last comment that you use console to send. 
if you use Firebase console to send, you are sending a display notification that is expected to be called inside `func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void) {}`

Can you confirm for your original description that you can still reproduce it?

**Comment by abdoh476** [comment]
@chliangGoogle 
He asked me to send via console so I did, but I know that I have to send it via nodeJS to send the "content-available" value.

As the original description says, I can't receive a remote notification on IOS version 15.3 inside 
`func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void){}`
it only received at the `userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void) {}`
which is not my point 

what can I do ?? @chliangGoogle

**Comment by chliangGoogle** [comment]
Did you enable remote notifications in the background mode? https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app

**Comment by abdoh476** [comment]
@chliangGoogle 
Yes I did

**Comment by ewfian** [comment]
It seems that this issue related to https://developer.apple.com/forums/thread/692029

We are facing the some issue here. after restart iPhone, it can be worked in a short time.

Someone said that the issue caused by throttling mechanism tighten up in iOS 15.3. 

There are reports that iOS 15.4 (beta) solved this.

**Comment by abdoh476** [comment]
I contacted one of apple engineers and they said that voip notifications is not intended to be received at this function and I should use pushkit instead
