### ISSUE TITLE
Firebase In App Messaging Not Displaying in Specific Screen

### ISSUE THREAD

**Issue by Adekunle77** [firebase/firebase-ios-sdk#9343]
**[REQUIRED] Describe the problem**

I am trying to test In-App Messaging from a specific screen on a real device, however, it is not displaying the message. 

In the `AppDelegate`, in the function `didFinishLaunchingWithOptions`  have put this code; 
```swift
        FirebaseApp.configure()
        let myFiamDelegate = CardActionFiamDelegate()
        InAppMessaging.inAppMessaging().delegate = myFiamDelegate
        InAppMessaging.inAppMessaging().messageDisplaySuppressed = false
```
and in the screen's ViewController where I want to display the Firebase In-App Message, I have put this code in the `viewDidLoad` method;

 ```swift
        InAppMessaging.inAppMessaging().messageDisplaySuppressed = true
        InAppMessaging.inAppMessaging().triggerEvent("TestingInAppMessagingPublishedCampaign")
```
** the string _TestingInAppMessagingPublishedCampaign_ is the name of the published campaign

This is how I have set it up on the console. 
![Screenshot 2022-02-14 at 15 15 48](https://user-images.githubusercontent.com/14952997/154097674-f1e94e19-1913-4435-88c2-e99a57b63e6b.png)

Please could you show me what to do, thank you

**Comment by Adekunle77** [comment]
> 

@ryanwilson @christibbs It didn't work 

I removed all the code In the `AppDelegate` that was associated with the In-App Messaging functionality.

I changed the code in the `viewDidLoad` method, in the screen's ViewController where I want the Firebase In-App Message to be displayed to this;

```swift
       InAppMessaging.inAppMessaging().triggerEvent("TestingInAppMessagingPublishedCampaign")
```

**Comment by Adekunle77** [comment]
@ryanwilson @christibbs Do you have a demo project that I can study, so can I get a clearer understanding of what I need to do and what I am doing wrong, please?

**Comment by rizafran** [comment]
Hi @Adekunle77, you may try using the [In-App Messaging quickstart](https://github.com/firebase/quickstart-ios/tree/master/inappmessaging) in order to troubleshoot the issue.

**Comment by Adekunle77** [comment]
@rizafran @ryanwilson I have tried that. I get In-App Messages when I run a test, pressing on the 'Test on Device' button. This works fine.
<img width="482" alt="Screenshot 2022-02-15 at 11 56 14" src="https://user-images.githubusercontent.com/14952997/154057551-8ada0b94-7e0b-429c-b56b-df99c68dbb86.png">

However, when I publish the campaign it does not work, the message is not being displayed.

**Comment by rizafran** [comment]
I tried to reproduce the issue and published a campaign, but it's working fine. I also noticed in your first screenshot that your target seems like an Android app. Have you tried changing it to an iOS app?

**Comment by Adekunle77** [comment]
@rizafran I have got it to work, but still can not display an In-App Message on a specific screen

**Comment by Adekunle77** [comment]
@rizafran Also, the buttons are not working

**Comment by morganchen12** [comment]
Can you share an example that reproduces this issue? Also, when this issue occurs, have you tried examining the view hierarchy in Xcode's view debugger to see if there's any view issues preventing user interaction?

**Comment by Adekunle77** [comment]
@morganchen12 and @rizafran I have checked the view hierarchy and there is no view above it. 
When I click the button on the In-App Message, nothing happens apart from the In-App Message disappearing from the screen. 
I have three lines of code within the project; 

first one in the `AppDelegate` 

```swift
     InAppMessaging.inAppMessaging().messageDisplaySuppressed = true
```
and in the screen's viewController I have these 2 lines codes;

```swift
     InAppMessaging.inAppMessaging().messageDisplaySuppressed = false
     InAppMessaging.inAppMessaging().triggerEvent("podcastScreen")
```
I also get this message in the console
<img width="676" alt="Screenshot 2022-02-16 at 13 02 58" src="https://user-images.githubusercontent.com/14952997/154270157-08a02bc7-d12b-4016-b285-0c2f597d4dfc.png">

**Comment by rizafran** [comment]
Can you share the SDK version you're using? Also, since it's not reproducible on our end using the quickstart, it would be helpful if you could provide a sample reproducible project.
