### ISSUE TITLE
Some events are missing

### ISSUE THREAD

**Issue by DanielZanchi** [firebase/firebase-ios-sdk#9344]
I am facing this issue with different apps.
The events get logged from the Xcode console, but then they are not visibile in DebugView (Firebase / Analytics) or in BigQuery (with the intraDay export).

Using Firebase 8.12.1 and sending the different events with:
`        Analytics.logEvent(name, parameters: parameters)
`
In the attached log we can see at line _1036_ the event named _ce_paywall_view_ getting logged
<img width="434" alt="Screenshot 2022-02-14 at 18 37 47" src="https://user-images.githubusercontent.com/6886116/153923098-8182ab07-36e6-4b9a-9a5a-7d27c41a2e20.png">

[even_logs.txt](https://github.com/firebase/firebase-ios-sdk/files/8063071/even_logs.txt)

**Comment by rizafran** [comment]
Hi @DanielZanchi, it seems like you're having an issue with showing the logs in the DebugView. With this, please file a ticket via our [Firebase support channel](https://firebase.google.com/support) so the team can take a look into the issue. Thanks.

**Comment by DanielZanchi** [comment]
@rizafran   I think this needs more investigation since I am facing this issue with several apps.
Closing the issue will help solving this problem of missing events being logged correctly.

**Comment by OlimjoniTranslate** [comment]
I am also facing this issue, did you find any solution @DanielZanchi?

**Comment by DanielZanchi** [comment]
> I am also facing this issue, did you find any solution @DanielZanchi?

No solution :( 
For now I'm thinking to switch to another service since analytics events are very important for the app. 
I am facing the same issue with different apps of mine.

**Comment by saurabh12317** [comment]
@DanielZanchi  , @OlimjoniTranslate - Any update or work around that you found on this? Facing the same issue.

**Comment by DanielZanchi** [comment]
No, in using a third service for important events that I can't randomly miss.
