### ISSUE TITLE
Why would deleting a user on a button press cause persistence error?

### ISSUE THREAD

**Issue by carlo190101martin** [firebase/firebase-ios-sdk#9349]
*** Terminating app due to uncaught exception 'FIRDatabaseAlreadyInUse', reason: 'Calls to setPersistenceEnabled must be made before any other usage of FIRDatabase instance.'

In App Delegate I have

```
Database.database().isPersistenceEnabled = true
```
/This above line is where I am redirected after the error, even if I delete that line, it goes to app delegate

The below delete causes the persistence error

```
   @ IBAction func deleteAccount(_ sender: Any) {
  Auth.auth().currentUser?.delete()
            { error in
                if error != nil {
                  print("an error deleting")
                // An error happened.
              } else {
                  print("deleted")
                  self.performSegue(withIdentifier: "delete", sender: nil)

                // Account deleted.
              }
            }
}

```

**Comment by morganchen12** [comment]
Do you have duplicate class definitions in your app's runtime? Also, you can set a symbolic breakpoint in `-[FIRDatabase setPersistenceEnabled:]` to find when the method is being called in order to make sure it's not being called twice.

**Comment by carlo190101martin** [comment]
@morganchen12  Very good call. There was a duplicate method call. So isPersistenceEnabled was set to true in App Delegate and in viewDidLoad on the first page of the app. I didn't use a symbolic breakdown but I checked in each page if the method was called, and as mentioned it was called on the app's first page. I must have done this a long time ago. Would there be any legitimate reason to set isPersistenceEnabled to true in App Delegate and another page? I don't know if there was maybe a reason that I did this.

**Comment by morganchen12** [comment]
No, it only needs to be called once and cannot be changed once any other database methods are invoked. The app delegate is usually the best location for this, since that way if you decide to change the root view controller of your app you haven't coupled your database lifecycle to it.

**Comment by morganchen12** [comment]
Hey @carlo190101martin, were you able to resolve this crash?

**Comment by carlo190101martin** [comment]
@morganchen12 Yes you were correct. I will close with comment
