### ISSUE TITLE
SPM: Firebase Database doesn't depend on FirebaseCore

### ISSUE THREAD

**Issue by freak4pc** [firebase/firebase-ios-sdk#9354]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.2
  * Firebase SDK version: 8.12.1
  * Installation method: Swift Package Manager
  * Firebase Component: Database
  * Target platform(s): `iOS`

### [REQUIRED] Step 2: Describe the problem

Adding FirebaseDatabase via SPM doesn't depend on FirebaseCore, which means you can't seem to call FirebaseApp.configure().
~~Only method around this is to grab the entirety of FirebaseAnalytics~~ (Actually doesn't seem like this works), even though it seems it shouldn't be needed for Database:

![image](https://user-images.githubusercontent.com/605076/154279037-19c5933d-5ae0-46be-bf94-f26295470a6d.png)

#### Steps to reproduce:

- Try to add https://github.com/firebase/firebase-ios-sdk.git as a depenendcy via SPM (on Xcode).
- Pick `FirebaseDatabase`
- There is no way to configure the app

Would be super happy if this is just my misunderstanding of this, somehow.

Thank you!

**Comment by ncooke3** [comment]
Hi @freak4pc, 

Sorry for the trouble. When you say "which means you can't seem to call FirebaseApp.configure()", are you getting a build error or runtime error?

I tried reproducing with SPM and 8.12.1 but was unable to. My repro steps:
- I created a new project
- Added Firebase via SPM
- Picked only `FirebaseDatabase`
- Added the following code to my app's entry point
```swift
import SwiftUI
import FirebaseCore // 🔥

@main
struct Firebase_9354App: App {

  init() {
    FirebaseApp.configure() // 🔥
  }

    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
```

And the project built successfully.

I could verify that, in my instance, FirebaseDatabase depended on FirebaseCore was 
building FirebaseCore first:
<img width="800" alt="image" src="https://user-images.githubusercontent.com/36927374/154282322-0f153a0d-ac9c-4bc5-9ae4-56a3c8f419be.png">

**Comment by freak4pc** [comment]
Hey @ncooke3 - I just removed and reinstalled it and it seems to work now 🤔 
I'm extremely confused, but relieved ;) sorry for wasting your time!

**Comment by ncooke3** [comment]
No worries at all– glad it resolved itself! 😄

**Comment by freak4pc** [comment]
> No worries at all– glad it resolved itself! 😄 

Wish all my bugs would self-resolve 🤣
Thank you 🙏
