### ISSUE TITLE
Add CI to detect public API changes in Swift

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#9356]
- Update Danger to turn on GitHub public tag
- Generate a report in PR for public API changes

Both of these are likely using DocC to get the API docs

**Comment by ryanwilson** [comment]
Update: DocC likely isn't necessary for this.

```
# Generate symbol graphs from Swift Package manifest. From the root of the repo:
mkdir -p .build/symbol-graphs
swift build --target FirebaseMLModelDownloader -Xswiftc -emit-symbol-graph -Xswiftc -emit-symbol-graph-dir -Xswiftc .build/symbol-graphs
```

A JSON file will exist at `.build/symbol-graphs/FirebaseMLModelDownloader.symbols.json` that contains the API surface.

**Comment by sunmou99** [comment]
@yifanyang Please take a look at this issue

**Comment by paulb777** [comment]
Fixed by @sunmou99
