### ISSUE TITLE
End Beta period for Swift libraries

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#9367]
We plan to end the beta period for the Firebase Swift libraries in the 9.0.0 release.  Please let us know if there is any feedback.

**Comment by paulb777** [comment]
Will do once v9 is merged to master

**Comment by mortenbekditlevsen** [comment]
Hi @paulb777 ,
Do you have plans to look into #9465 (formerly #8858) for v9?
It may have slight behavior breaking changes that are mainly internal, but formally part of the public API (since FirestoreEncoder and FirestoreDecoder are public and _could_ be used for custom encoding and decoding).

**Comment by paulb777** [comment]
Hi @mortenbekditlevsen Thanks for bringing this up. Let's try to get #9465 resolved and done in time for the breaking change release.
