### ISSUE TITLE
libc++abi.dylib std::__terminate(void (*)()) 

### ISSUE THREAD

**Issue by Shatha-Naami** [firebase/firebase-ios-sdk#9369]
* For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

  * Xcode version:  13.0 (13A233)
  * Firebase SDK version: firebase_crashlytics: ^2.5.0
  * Installation method: CocoaPods
  * Firebase Component: Auth, Core, Database, Firestore, Messaging, Storage
  * Target platform(s): iOS

### [REQUIRED] Step 2: Describe the problem

I have reported on firebase_crashlytics, and I don't what is error !!

<img width="1790" alt="Screen Shot 2022-02-20 at 2 59 06 PM" src="https://user-images.githubusercontent.com/60509531/154843775-662ced73-0010-44a4-95be-6ead07d52183.png">

**Comment by paulb777** [comment]
Sorry about the trouble. The report looks similar to #7677. Please share all the stack frames in the trace.
