### ISSUE TITLE
Missing dSYMs 

### ISSUE THREAD

**Issue by yuvrajvaluelabs20222** [firebase/firebase-ios-sdk#9372]
I have integrated the firebase crashlytics. dSYMs are uploading before but right now i can see error showing dSYMs are missing. I haven't changed anything. Also I can see the alert message on dashboard, **"Customers with bitcode-enabled apps have reported that some dSYMs required for crash reporting are not available for download on App Store Connect. This may prevent crashes from appearing on the dashboard. We are looking into this issue. 
"**

**Comment by rizafran** [comment]
Hi @yuvrajvaluelabs20222, thanks for reporting this issue. I see that this banner is displaying in the Crashlytics dashboard. 
Please file a ticket via our support channel in order for us to get your app and project details and investigate it in our backend. With this, I'll now close the ticket.
