### ISSUE TITLE
[in-AppMessaging][Crash] FIRIAMRenderingWindowHelper.m

### ISSUE THREAD

**Issue by limaAniceto** [firebase/firebase-ios-sdk#9376]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.2.1
  * Firebase SDK version: 12.9.3
  * Installation method: CocoaPods
  * Firebase Component: Messaging
  * Target platform(s): iOS

### [REQUIRED] Step 2: Describe the problem
Seeing firebase crashes spike since we started a campaign 
This campaign uses a `card` and it has a button/images
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/2905749/155210197-fe2fd5e0-f35c-4697-a9de-25adee310116.png">
<img width="862" alt="image" src="https://user-images.githubusercontent.com/2905749/155210251-ba764bd6-1e1a-4684-9bf7-5d77cdfcc1dd.png">
<img width="831" alt="image" src="https://user-images.githubusercontent.com/2905749/155210285-0ebad646-74aa-4540-bcd6-31c5c1fc7054.png">

#### Steps to reproduce:
1. Create a campaign with a card and target iOS

I could not reproduce this locally but seen it on firebase crashlytics

**Comment by morganchen12** [comment]
Based on the presence of [CPTemplateApplicationScene](https://developer.apple.com/documentation/carplay/cptemplateapplicationscene), this is likely a crash occurring when Firebase tries to present messages with CarPlay connected. For the time being, you can probably work around this crash by [suppressing messages until CarPlay is disconnected](https://firebase.google.com/docs/reference/swift/firebaseinappmessaging/api/reference/Classes/InAppMessaging#/c:objc(cs)FIRInAppMessaging(py)messageDisplaySuppressed).

**Comment by limaAniceto** [comment]
Thank you for the quick response @morganchen12 🙏 

We'll follow your advice, have a great day 👋

**Comment by EmDee** [comment]
Oh wow! We've seen this crash for quite a while now, but never connected it to Firebase, because the Sentry crash logs were very cryptic:

```
NSInvalidArgumentException

-[CPTemplateApplicationScene coordinateSpace]: unrecognized selector sent to instance 0x153e709c0
```

I wouldn't be surprised if a lot of others ran into this without noticing.
