### ISSUE TITLE
[Auth] "APP_NOT_VERIFIED" Error 

### ISSUE THREAD

**Issue by mtfum** [firebase/firebase-ios-sdk#9378]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Xcode13.2
  * Firebase SDK version: 6.34.0
  * Installation method: `CocoaPods`
  * Firebase Component: Auth(6.9.0)
  * Target platform(s): `iOS`

### [REQUIRED] Step 2: Describe the problem

When inputting the phone number for authentication, firebase return back the error `APP_NOT_VERIFIED`.
But it's not always happened, so I'm not sure how to reproduce.
My app has been working for more than a year though, it happened suddenly a few days ago.

according to [appNotVerified](https://firebase.google.com/docs/reference/unity/namespace/firebase/auth#namespace_firebase_1_1_auth_1aef1e65c370d8edb018dc417ae73ec11cab5be67103e8845158b2d5c4dc930c45c), `APP_NOT_VERIFIED` happens only in iOS. So I issue this here.
What is this? and How can I fix this?

#### Relevant links

- [appNotVerified](https://firebase.google.com/docs/reference/unity/namespace/firebase/auth#namespace_firebase_1_1_auth_1aef1e65c370d8edb018dc417ae73ec11cab5be67103e8845158b2d5c4dc930c45c)
- https://github.com/firebase/firebase-ios-sdk/issues/8972 
-  [Firebase phone auth error "APP_NOT_VERIFIED" in StackOverflow](https://stackoverflow.com/q/70093036/8550321)

**Comment by rizafran** [comment]
Thanks for the report, @mtfum. It seems that updating the SDK version to at least v8.8.0 will fix the issue. The new SDK has certain security improvements and we've started to enforce SDK upgrades. If the issue persists, please file through our [Firebase support](https://firebase.google.com/support) so the team could investigate it further in the backend.

**Comment by RyanMan56** [comment]
@rizafran I was struggling with this issues for the last few hours and your suggestion fixed it for me, thank you!
