### ISSUE TITLE
Github Slack integration

### ISSUE THREAD

**Issue by alrocha** [firebase/firebase-ios-sdk#9380]
**Request**

Hello, when trying to add the slack notifications for github repo using
`/github subscribe firebase/firebase-ios-sdk releases` I get the following error saying that the app is not installed in the repo.

![image](https://user-images.githubusercontent.com/8307263/155231492-bd185dd7-96cd-4964-8940-d26558c91f39.png)

Could be possible to install it? I think just using this link as I could see in the docs https://github.com/apps/slack/installations/new
Thanks in advance!

**Comment by morganchen12** [comment]
Slack is installed on this repo now.
