### ISSUE TITLE
Uploads fail with -13000, server failures -1017, -1200, -1700 so far

### ISSUE THREAD

**Issue by dhoerl** [firebase/firebase-ios-sdk#9385]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.2.1
  * Firebase SDK version: 7.11.0
  * Installation method: CocoaPods
  * Firebase Component: Storage
  * Target platform(s):  iOS

### [REQUIRED] Step 2: Describe the problem

My company recently started logging FirebaseStorage errors, and we are concerned about the number of of them - 1861 in the past week.

The FIRStorageErrorCode is -13000, and the ResponseErrorCode varies:

| Error  | Count |
|------|------|
| 2      | 5     |
| 4      | 10    |
| 89     | 5     |
| 260    | 5     |
| 400    | 6     |
| 500    | 1     |
| 503    | 3     |
| -999   | 332   |
| -1017  | 433   |
| -1200  | 1024  |
| -13020 | 43    |

Our URLS are similar to this:
  https://firebasestorage.googleapis.com/v0/b/<redacted>/o/acb69980-fa33-4788-a28b-b442803a6b6a_R0010102.JPG?...

Steps to reproduce:

Unknown. The uploads always succeed when done by our developers and QA team.

What happened? How can we make the problem occur?

Our customers experience failures when they attempt to upload their images. A cursory look at our logs shows they succeed when attempted immediately after the failure.

#### Steps to reproduce:

Schedule thousands of image uploads spread all over the USA (via our client base), then record a hundred or more failures per day.

What happened? How can we make the problem occur?

Of course I as the iOS dev never see a failure (although today I did see a -1200 in the console!).

This could be a description, log/console output, etc.

The bucket is redacted, I can provide that directly if needed.

Four so far today:

"error": "FirebaseCode: FIRStorageErrorCode CODE=-13000: An unknown error occurred, please check the server response. UserInfo: [ { NSLocalizedDescription: An unknown error occurred, please check the server response. ResponseErrorDomain: NSURLErrorDomain ResponseErrorCode: -1017 bucket: <redacted> _kCFStreamErrorCodeKey: -1 _NSURLErrorRelatedURLSessionTaskErrorKey: (\n    \"BackgroundUploadTask <5D6F9F29-A41B-4E17-8C67-02A612F8C1F5>.<1>\",\n    \"LocalUploadTask <5D6F9F29-A41B-4E17-8C67-02A612F8C1F5>.<1>\"\n) NSErrorFailingURLStringKey: https://firebasestorage.googleapis.com/v0/b/`<redacted>`/o/acb69980-fa33-4788-a28b-b442803a6b6a_R0010102.JPG?uploadType=resumable&name=acb69980-fa33-4788-a28b-b442803a6b6a_R0010102.JPG&upload_id=ADPycdsfUyev0vrDemIIA9zCeRrc7p8hL5_mHRjosmH8loub9v8HeCFnxdvOia01519-2V0JrPOTujRMRTNg28ycjzw&upload_protocol=resumable NSErrorFailingURLKey: https://firebasestorage.googleapis.com/v0/b/<redacted>/o/acb69980-fa33-4788-a28b-b442803a6b6a_R0010102.JPG?uploadType=resumable&name=acb69980-fa33-4788-a28b-b442803a6b6a_R0010102.JPG&upload_id=ADPycdsfUyev0vrDemIIA9zCeRrc7p8hL5_mHRjosmH8loub9v8HeCFnxdvOia01519-2V0JrPOTujRMRTNg28ycjzw&upload_protocol=resumable object: acb69980-fa33-4788-a28b-b442803a6b6a_R0010102.JPG _kCFStreamErrorDomainKey: 4 _NSURLErrorFailingURLSessionTaskErrorKey: BackgroundUploadTask <5D6F9F29-A41B-4E17-8C67-02A612F8C1F5>.<1> } ] ", "uuid": "acb69980-fa33-4788-a28b-b442803a6b6a", "external_camera_manufacturer": "RICOH", "external_camera_firmware_version": "1.80.1", "pin_uuid": "0be436d4-ee19-4216-a07e-43b50884d31c", "name": "R0010102.JPG"]) : appVersion=1.86.0

Another

 "error": "FirebaseCode: FIRStorageErrorCode CODE=-13000: An unknown error occurred
 please check the server response. UserInfo: [ { _NSURLErrorRelatedURLSessionTaskErrorKey: (\n    \"LocalDataTask <B04C563A-88C0-44CB-A1B8-A32748314C0B>.<52>\"\n) _NSURLErrorFailingURLSessionTaskErrorKey: LocalDataTask <B04C563A-88C0-44CB-A1B8-A32748314C0B>.<52> 

ResponseErrorCode: -1200 NSErrorFailingURLKey: https://firebasestorage.googleapis.com/v0/b/<redacted>/o/debef551-4b8c-4a48-95d4-39db8c34fd28_IMG_20220222_141455_00_053.jpeg?

uploadType=resumable&name=debef551-4b8c-4a48-95d4-39db8c34fd28_IMG_20220222_141455_00_053.jpeg ResponseErrorDomain: NSURLErrorDomain NSErrorFailingURLStringKey: https://firebasestorage.googleapis.com/v0/b/<redacted>/o/debef551-4b8c-4a48-95d4-39db8c34fd28_IMG_20220222_141455_00_053.jpeg?uploadType=resumable&name=debef551-4b8c-4a48-95d4-39db8c34fd28_IMG_20220222_141455_00_053.jpeg _kCFStreamErrorCodeKey: -9816 NSLocalizedRecoverySuggestion: Would you like to connect to the server anyway? NSLocalizedDescription: An unknown error occurred
 please check the server response. bucket: <redacted> _kCFStreamErrorDomainKey: 3 CODE=-1200: The operation couldn’t be completed. (kCFErrorDomainCFNetwork error -1200.) UserInfo: [ { _kCFStreamErrorCodeKey: -9816 _kCFStreamPropertySSLClientCertificateState: 0 _kCFStreamErrorDomainKey: 3 _kCFNetworkCFStreamSSLErrorOriginalValue: -9816 } ] object: debef551-4b8c-4a48-95d4-39db8c34fd28_IMG_20220222_141455_00_053.jpeg } ] "

"error": "FirebaseCode: FIRStorageErrorCode CODE=-13000: An unknown error occurred, please check the server response. UserInfo: [ { bucket: <redacted> object: 2d757313-1008-49f0-bfce-e3bd62569de4_IMG_20220222_144905_00_281.jpeg NSLocalizedDescription: An unknown error occurred, please check the server response. _kCFStreamErrorCodeKey: -1 _NSURLErrorRelatedURLSessionTaskErrorKey: (\n    \"BackgroundUploadTask <A89EC5D0-B951-4A56-8CAC-978059E1F1FC>.<1>\",\n    \"LocalUploadTask <A89EC5D0-B951-4A56-8CAC-978059E1F1FC>.<1>\"\n) _NSURLErrorFailingURLSessionTaskErrorKey: BackgroundUploadTask <A89EC5D0-B951-4A56-8CAC-978059E1F1FC>.<1> ResponseErrorCode: -1017 NSErrorFailingURLStringKey: https://firebasestorage.googleapis.com/v0/b/<redacted>/o/2d757313-1008-49f0-bfce-e3bd62569de4_IMG_20220222_144905_00_281.jpeg?uploadType=resumable&name=2d757313-1008-49f0-bfce-e3bd62569de4_IMG_20220222_144905_00_281.jpeg&upload_id=ADPycdvO0pfEVSe_dfB8K96yBvU3n9G2S3po7zANsD4WKS2QsgJENpZAyQyr6yP7eKqoGdCvFeV73MEXIiwoKTKQlX50ypMQcQ&upload_protocol=resumable NSErrorFailingURLKey: https://firebasestorage.googleapis.com/v0/b/<redacted>/o/2d757313-1008-49f0-bfce-e3bd62569de4_IMG_20220222_144905_00_281.jpeg?uploadType=resumable&name=2d757313-1008-49f0-bfce-e3bd62569de4_IMG_20220222_144905_00_281.jpeg&upload_id=ADPycdvO0pfEVSe_dfB8K96yBvU3n9G2S3po7zANsD4WKS2QsgJENpZAyQyr6yP7eKqoGdCvFeV73MEXIiwoKTKQlX50ypMQcQ&upload_protocol=resumable _kCFStreamErrorDomainKey: 4 ResponseErrorDomain: NSURLErrorDomain } ] "]) : appVersion=1.86.0
If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

-13000 , -1200, -1700
```
// TODO(you): code here to reproduce the problem
```

**Comment by morganchen12** [comment]
Hey, apologies for the slow response. The underlying failure reasons are [NSURLErrorSecureConnectionFailed](https://www.osstatus.com/search/results?platform=all&framework=all&search=-1200), [NSURLErrorCannotParseResponse](https://www.osstatus.com/search/results?platform=all&framework=all&search=-1017), and [errAECoercionFail](https://www.osstatus.com/search/results?platform=all&framework=all&search=-1700), which are all generic network failure messages (except the latter, which warrants further investigation if reproducible). Do you have any information on the network conditions at time of failure? Also, have you noticed more user complaints in the past two weeks?

**Comment by dhoerl** [comment]
Morgan, I'm now sorry for the slow response! 

If you look above in "Step 2", I broke down the ResponseErrorCode by number and count.

Really, when I started this, I jumped when I looked online at the logs, and saw hundreds of our users experiencing upload failures every day. It really spooked me and I was concerned something was very wrong.

However, after a weeks worth of logging, I was able to get a count of all uploads attempted  in relation to failures: while I wouldn't swear that my analysis was correct (long story), it appears that the errors are only 0.5% of the total - so pretty low.

There is no way to get much more context from the failures. The only items available would be the WiFi SSD (and or indiction the transfer was over cellular), and the IP address (which probably would be NATed).

A great question at this point is: what is the expected failure rate?

**Comment by morganchen12** [comment]
>A great question at this point is: what is the expected failure rate?

This is a hard question to answer because it depends on a number of factors (how large are your uploads? where are your users located? do they use your app predominantly on wifi or on cellular?). It may make more sense to determine how users are experiencing your errors--if your user base is experiencing intermittent upload errors uniformly but successfully retrying failed uploads, there's likely nothing to worry about, but if it's a handful of users running into upload errors that persist on retry, that warrants further investigation.

**Comment by dhoerl** [comment]
Morgan, well some uploads are large many are just large JPEGs. But these failure are all connection failures (well, I assumed they all were, but hmmmm maybe not).

In any case, from a cursory look, they always succeed if the user retries.

We just never thought to add say 3 retries with an exponential backoff. Because of that, if they queued 10 items, and one fails, our app stalls and they have to restart the upload. Its jus annoying and frankly I was shocked no client called into Support to complain!

I guess people are so conditioned to network failures they just don't blink.

Thanks again for your help!

**Comment by morganchen12** [comment]
No problem! Feel free to re-open or file a new issue if you start getting a wave of support issues.
