### ISSUE TITLE
Switching from emulator to Firestore results in Unauthenticated error on device and simulator

### ISSUE THREAD

**Issue by kalmicka** [firebase/firebase-ios-sdk#9396]
[REQUIRED] Step 1: Describe your environment

Xcode version: 13.2.1
Firebase SDK version: Firebase (8.12.1)
Installation method: SPM
Firebase Component: Functions
[REQUIRED] Step 2: Describe the problem

My problem is calling a callable function. Using the emulator (DEBUG) everything works fine in my iOS app. However, as soon as I switch to regular Firestore (QA) I get the following error:

Error Domain=com.firebase.functions Code=16 "UNAUTHENTICATED" UserInfo={NSLocalizedDescription=UNAUTHENTICATED}

There are no logs from the emulator when the error is returned so i am guessing the request doesn't even reach the function. This issue seems to be related to this issue, at least I think it is. [(#7783 )](https://github.com/firebase/firebase-ios-sdk/issues/7783)

Steps to reproduce:

Start emulators
Start ios app with emulators configured
call the callable function - this works
switch from the emulator to Firestore - this does not work
Actual result: fails with error: Unauthenticated.

Expected result: The callable function is executed successfully.

Relevant Code:

(Swift)

Inside AppDelegate
```
 func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {

#if targetEnvironment(simulator)
        let providerFactory = AppCheckDebugProviderFactory()
#else
        let providerFactory = MyAppCheckProviderFactory()
#endif
        AppCheck.setAppCheckProviderFactory(providerFactory)
        
#if DEBUG
        print("_________DEBUG___________")
        
        FirebaseApp.configure()
        let db = Firestore.firestore()
        //This is for testing
        Auth.auth().useEmulator(withHost:"localhost", port:9099)
        Functions.functions().useEmulator(withHost: "localhost", port: 5001)
        let settings = db.settings
        settings.host = "localhost:8080"
        settings.isPersistenceEnabled = false
        settings.isSSLEnabled = false
        db.settings = settings
        //This is for testing
        
        
#else
        print("__________QA______________")
        
        FirebaseApp.configure()
        let db = Firestore.firestore()
        let settings = db.settings
        settings.isPersistenceEnabled = true
        db.settings = settings

#endif        
```

Inside a class that uses callable functions to setup a user after anonymous signin

`Functions.functions().httpsCallable("setupUser").call(dictToSubmit) { (result, error) in`

Here the log that gets produced

```
2022-02-27 11:07:35.095163+0100 GameOn[67751:5263840] 8.12.1 - [Firebase/Auth][I-AUT000002] Token auto-refresh enabled.
2022-02-27 11:07:35.095841+0100 GameOn[67751:5263840] 8.12.1 - [Firebase/Auth][I-AUT000004] Token auto-refresh scheduled in 55:00 for the new token.
2022-02-27 11:07:35.096272+0100 GameOn[67751:5263840] 8.12.1 - [Firebase/Auth][I-AUT000017] Has valid access token. Estimated expiration date: 2022-02-27 11:07:34 +0000, current date: 2022-02-27 10:07:35 +0000
2022-02-27 11:07:35.177849+0100 GameOn[67751:5263857] [boringssl] boringssl_metrics_log_metric_block_invoke(151) Failed to log metrics
Something went wrong: Error Domain=com.firebase.functions Code=16 "UNAUTHENTICATED" UserInfo={NSLocalizedDescription=UNAUTHENTICATED}
```

**Comment by wu-hui** [comment]
It looks like a functions issue, I can investigate if it turns out to be false.

**Comment by kalmicka** [comment]
I did try to log the function but it nothing shows up. Because of this I thought it would have nothing to do with the function.

**Comment by morganchen12** [comment]
@kalmicka to make sure it's not a regression of https://github.com/firebase/firebase-ios-sdk/issues/7783, can you log the `Functions.functions()` object when it's invoked and share the logs here?

**Comment by kalmicka** [comment]
Glad to do it. Can you let me know how I can log the object in Xcode? Simple "print" just gives me the reference to the object.

**Comment by morganchen12** [comment]
Yep, that's fine--in the issue I linked above, the root cause of the bug was the Functions object was being recycled, so emulator configuration state on it wasn't persisting between invocations. If the reference to the object is the same (it isn't being recycled), then the root cause of the bug here is different.

**Comment by kalmicka** [comment]
Just to clarify, you said to log the functions object when it is invoked and that it might get recycled. Should I then log the Functions object in my AppDelegate AND in the class where I use the Functions object again? For completeness I add my callable function and what I would log here.

`

 let functions = Functions.functions()  
       #if DEBUG
        print("__________DEBUG___________")
        functions.useEmulator(withHost: "http://localhost", port: 5001)
        
        #else
        print("No need to do anything")
       
        #endif
        
        print("________LOG THIS ITEM____________")
        print(functions)
        print("________LOG THIS ITEM____________")
        
        let dictToSubmit:[String:Any] = ["someKey":"someValue"]
        
        functions.httpsCallable("userPreferences-setupUser").call(dictToSubmit) { (result, error) in

`

**Comment by morganchen12** [comment]
Based on your implementation this does not seem to be a regression. I'll try to reproduce it locally and investigate from there.

**Comment by kalmicka** [comment]
Any update on this?

**Comment by morganchen12** [comment]
Hey @kalmicka, sorry for the slow response. I'll get to this today.

**Comment by morganchen12** [comment]
I've been able to reproduce this bug. The way backend emulators are currently implemented in the SDK, enabling and then later disabling emulation during your app's lifecycle is not supported universally (see [here](https://github.com/firebase/firebase-ios-sdk/blob/master/Firestore/Source/Public/FirebaseFirestore/FIRFirestore.h#L170) for example, though some products currently handle this better than others.

Have you been able to reproduce this error when restarting the app without emulation?

**Comment by kalmicka** [comment]
Sorry for the delay, I tried everything. I removed the code and erased the whole simulator. The error still persists. Any idea on what else I can do?

**Comment by morganchen12** [comment]
Does this bug reproduce:
- without ever connecting to the emulator
- in a **separate** app target
- using the same Firebase project?

If so, it may be caused by misconfigured security rules or some other project-specific issue (though the SDK should be providing logs when this happens).

This kind of testing may involve some lengthy back and forth, so if you're comfortable sharing your project you can email it to me at morganchen at google.com and I'll try to see what's going on.

**Comment by kalmicka** [comment]
Ok so I tried this. I introduced another configuration file for another firebase project. So the logic is now:

Debug: Use Emulator for testing
QA: Use Firestore (Cloud) for quality assurance <<---- Firebase project 1
Release: Use Firestore (Cloud) for production <<---- Firebase project 2

As you can see in the code below, the implementation is the same for QA and RELEASE. However, the Release version seems to work. When I switch the scheme back to QA I do get the error again.

```
#if DEBUG        
        print("_________DEBUG___________")
        
        FirebaseApp.configure()
        let db = Firestore.firestore()
        //This is for testing
        Auth.auth().useEmulator(withHost:"localhost", port:9099)
        Functions.functions().useEmulator(withHost: "localhost", port: 5001)
        let settings = db.settings
        settings.host = "localhost:8080"
        settings.isPersistenceEnabled = false
        settings.isSSLEnabled = false
        db.settings = settings
        //This is for testing
        
        AppColor.oColor = .alizarin
        
#elseif QA
        print("__________QA______________")
        
        FirebaseApp.configure()
        let db = Firestore.firestore()
        
        let settings = db.settings
        settings.isPersistenceEnabled = true
        db.settings = settings
        
        AppColor.oColor = .peterRiver
        
#elseif RELEASE
        print("________Release___________")
        
        FirebaseApp.configure()
        let db = Firestore.firestore()
        print("config Firebase")
        
        let settings = db.settings
        settings.isPersistenceEnabled = true
        db.settings = settings
        
#else
        print("_________UNKNOWN___________")
        
#endif

```


Here is the script I am using to switch between the different googleService-info.plist files. This is the only thing that should be different. Everything else is the same. I deployed the same functions, rules etc. to both firebase projects. 
Kind of clueless what it could be.

```
# Type a script or drag a script file from your workspace to insert its path.
# Name of the resource to copy
INFO_PLIST_FILE=GoogleService-Info.plist

# Get references to debug and release versions of the plist file
DEBUG_INFO_PLIST_FILE=${PROJECT_DIR}/${TARGET_NAME}/Firebase/Development/${INFO_PLIST_FILE}
QA_INFO_PLIST_FILE=${PROJECT_DIR}/${TARGET_NAME}/Firebase/Development/${INFO_PLIST_FILE}
RELEASE_INFO_PLIST_FILE=${PROJECT_DIR}/${TARGET_NAME}/Firebase/Release/${INFO_PLIST_FILE}

# Make sure the debug version exists
echo "Looking for ${INFO_PLIST_FILE} in ${DEBUG_INFO_PLIST_FILE}"
if [ ! -f $DEBUG_INFO_PLIST_FILE ] ; then
    echo "File GoogleService-Info.plist (debug) not found."
    exit 1
fi

# Make sure the debug version exists
echo "Looking for ${INFO_PLIST_FILE} in ${QA_INFO_PLIST_FILE}"
if [ ! -f $QA_INFO_PLIST_FILE ] ; then
    echo "File GoogleService-Info.plist (qa) not found - Same as debug."
    exit 1
fi

# Make sure the release version exists
echo "Looking for ${INFO_PLIST_FILE} in ${RELEASE_INFO_PLIST_FILE}"
if [ ! -f $RELEASE_INFO_PLIST_FILE ] ; then
    echo "File GoogleService-Info.plist (release) not found."
    exit 1
fi

# Get a reference to the destination location for the plist file
PLIST_DESTINATION=${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app
echo "Copying ${INFO_PLIST_FILE} to final destination: ${PLIST_DESTINATION}"

echo "Selected Configuration is: ${CONFIGURATION}"

# Copy the appropiate file to app bundle
if [ ${CONFIGURATION} == "Debug" ] ; then
    echo "USING DEBUG"
    echo "File ${DEBUG_INFO_PLIST_FILE} copied"
    cp "${DEBUG_INFO_PLIST_FILE}" "${PLIST_DESTINATION}"

elif [ "${CONFIGURATION}" == "QA" ] ; then
    echo "USING QA"
    echo "File ${QA_INFO_PLIST_FILE} copied"
    cp "${QA_INFO_PLIST_FILE}" "${PLIST_DESTINATION}"
else
    echo "USING PROD"
    echo "File ${RELEASE_INFO_PLIST_FILE} copied"
    cp "${RELEASE_INFO_PLIST_FILE}" "${PLIST_DESTINATION}"
fi
```

**Comment by kalmicka** [comment]
Just realised that the second project still is not enforcing App Check. So that would be a difference between both of them. I will enable App Check for it and see if the error resurfaces for that project as well.

**Comment by kalmicka** [comment]
Ok, so I did enable AppCheck in the other project and everything was still ok. This really is kind of odd as the only change is the GoogleService-Info.plist which gets chosen depending on the build configuration I am running. I compared both Google plist files and they do have different attributes in them. Can this even be the error? Everything else seems odd or would mean that this is a bug on the firebase project side.

**Comment by morganchen12** [comment]
You can try re-downloading the GoogleService-Info.plist from the project that isn't working correctly.

If that doesn't fix it, apologies in advance for the redirection, but you'll need to file a [support ticket](https://firebase.google.com/support) for Firebase staff to look directly at your project info. Link to this issue in the ticket and let me know if it doesn't get escalated correctly.

**Comment by kalmicka** [comment]
Thanks for the hint. I will open up a ticket and see if they can figure it out. Thanks for all the support!
