### ISSUE TITLE
Geopoint query gives weird results

### ISSUE THREAD

**Issue by macoapps** [firebase/firebase-ios-sdk#941]
### Step 2: Describe your environment
  * Xcode version: 9.2
  * Firebase SDK version: 4.10.1
  * Firebase Component: Firestore
  * Component version: 0.10.3

### Step 3: Describe the problem
I need to make a "nearby" query, and use a similar way as described in SO : https://stackoverflow.com/questions/46630507/how-to-run-a-geo-nearby-query-with-firestore
But results do not respect my lat/lon ranges ... 
Any update on geoqueries ?

**Comment by wilhuff** [comment]
The accepted answer to that question is "As of today, there is no way to do such a query." and that's still correct.

The second answer attempts to create a bounding box, but this approach doesn't work (and there's a comment there indicating the behavior you're probably seeing: "we are running the same query as you do, but the results we are getting are ignoring longitude. So all the documents we get are within the lat range, but not within the lon range").

Native support for geoqueries is something we're going to build but we're not working on it yet.

In a perfect world we wouldn't have published the GeoPoint type before we had full support for manipulating them, but we needed to establish this as a fundamental type for compatibility with other systems. This creates a circumstance where these seem like they should be useful, but the reality is that today, you can't use them for much.
