### ISSUE TITLE
Firebase Remote Config is missing the required GCMSenderID - Flutter Project

### ISSUE THREAD

**Issue by giederloreto** [firebase/firebase-ios-sdk#9414]
### Step 0: Are you in the right place?

  I can't build my Flutter project on IOS, because FIREBASE REMOTE CONFIG crash just in IOS. Because in Android works normaly.
 I add the "GoogleService-Info.plist" normaly.

 
### [REQUIRED] Step 1: FLUTTER Project - 

  * Xcode version: _____
  * Firebase SDK version: Last version
  * Installation method: `CocoaPods | Carthage | Zip file | Swift Package Manager` (select one)
  * Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Target platform(s): `All | iOS | Catalyst | macOS | tvOS | watchOS`

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```'Terminating app due to uncaught exception 'com.firebase.config', reason: 'Firebase Remote Config is missing the required GCMSenderID property from the configured FirebaseApp and will not be able to function properly. Please fix this issue to ensure that Firebase is correctly configured.'

**Comment by rizafran** [comment]
Thanks for reporting this, @giederloreto. First off, could you provide the SDK version you're using, code snippet or steps to reproduce the issue?

**Comment by paulb777** [comment]
There's a good chance updating to Firebase 8.x will fix this problem.
