### ISSUE TITLE
Number of real-time events is over the real-time event count daily limit

### ISSUE THREAD

**Issue by safa-ads** [firebase/firebase-ios-sdk#9423]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.1
  * Firebase SDK version: 7.6.0
  * Installation method: CocoaPods
  * Firebase Component: Analytics
  * Target platform(s):  iOS

### [REQUIRED] Step 2: Describe the problem

This message appeared in our console from Firebase

`2022-03-02 19:54:19.234758+0200 [52202:263299] 7.6.0 - [Firebase/Analytics][] Number of real-time events is over the real-time event count daily limit. Event is no longer real-time. Event name, parameters: ***, {
    "_c" = 1;
    "_o" = app;
    "_sc" = **;
    "_si" = **;
    type = phone;
    "user_id" = **;
}`
`2022-03-02 19:54:19.625243+0200 [52202:263299] 7.6.0 - [Firebase/Analytics][] Number of real-time events is over the real-time event count daily limit. Event is no longer real-time. Event name, parameters: ***, {
    "_c" = 1;
    "_o" = app;
    "_sc" = **;
    "_si" = "-**";
    type = phone;
    "user_id" = **;
}`
`2022-03-02 19:54:20.126305+0200 [52202:263299] 7.6.0 - [Firebase/Analytics][] Number of real-time events is over the real-time event count daily limit. Event is no longer real-time. Event name, parameters: ***, {
    "_c" = 1;
    "_o" = app;
    "_sc" = ***;
    "_si" = **;
    category = "";
    source = "";
    trigger = "";`

**Comment by rizafran** [comment]
HI @safa-ads, the error you encountered means that you have hit the limit of daily conversion events logged. Once the limit has exceeded, the data logged after that will be treated as a normal event. See this [page](https://firebase.google.com/docs/analytics/errors) (error 10) for reference.
