### ISSUE TITLE
Crashlytics contains usage of insecure API calls like memcpy.

### ISSUE THREAD

**Issue by romanhu-bb** [firebase/firebase-ios-sdk#9424]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.2.1
  * Firebase SDK version: 8.5.0
  * Installation method: `CocoaPods`
  * Firebase Component: Crashlytics
  * Target platform(s): `iOS`

### [REQUIRED] Step 2: Describe the problem

Our security team was using static code scanner MobSF for checking our app binary. They have found high secure issue, that _.ipa_ contains memcpy. This is hight vulnerability. Any comments/deadline when it will be fixed?

#### Steps to reproduce:

1. Add firebase to your app (we use cocoapods).
2. Archive
3. Scan .ipa using mobSF

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulb777** [comment]
This is a duplicate of #8454. We haven't see evidence of a vulnerability with those usages of `memcpy`. Please read #8454 and associated links for additional context.
