### ISSUE TITLE
No such module 'Firebase' in XCode 13.2.1

### ISSUE THREAD

**Issue by PROCW** [firebase/firebase-ios-sdk#9440]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.2.1
  * Firebase SDK version: 8.13.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: Auth, Core, Database, Firestore, Messaging, Storage, etc
  * Target platform(s): `iOS`
  * Target version iOS `15.2 `

#### Steps to reproduce:

I add the Firebase iOS SDK using Xcode->File->Package... (github link)
add the screenshots.

#### Relevant Code:

```
import SwiftUI
import Firebase


struct LoginView: View {
    @State var isLoginMode = false
    @State var email = ""
    @State var password = ""

    init() {
        
    }
```
![Screen Shot 2022-03-10 at 5 50 40 PM](https://user-images.githubusercontent.com/57867146/157768321-4fbb1550-20e0-456b-8d0b-8c9cb058f0f6.png)

**Comment by rizafran** [comment]
Hi @PROCW, could you try the following to see if that would fix the issue:
- Delete your Xcode's derived data
- Open `File` > `Packages` then click ` Reset package caches`

If the issue persists, it might be related to this current [stack post](https://stackoverflow.com/questions/70581075/xcode-13-2-1-unable-to-resolve-swift-package-manager) wherein Xcode 13.2.1 is unable to resolve SPM.

**Comment by PROCW** [comment]
Thanks your help, I fixed them, so I removed the package and import using github url in repository of project.
When I import it, I can see the option for importing setting dialog, so I changed the branch with "next to mirror".
I think, we need to update the doc about Step 4 of setup. (https://firebase.google.com/docs/ios/setup)

**Comment by rizafran** [comment]
I'm glad that the issue has been fixed, @PROCW. Also, thanks for sharing your feedback. Could you confirm if you're referring to the step that says "_Select the SDK version that you want to use._", then add the _change the branch with "next to minor"_?
