### ISSUE TITLE
Value of type 'QuerySnapshot' has no member 'data'

### ISSUE THREAD

**Issue by PROCW** [firebase/firebase-ios-sdk#9444]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.2.1
  * Firebase SDK version: 8.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: Auth, Core, Database, Firestore, Storage
  * Target platform(s): `iOS`

### [REQUIRED] Step 2: Describe the problem

[](https://stackoverflow.com/posts/59548819/timeline)11

I've been trying to convert the document retrieved from the Firebase's Cloud Firestore to a custom object in Swift 5. I'm following the documentation:

https://firebase.google.com/docs/firestore/query-data/get-data#custom_objects
However, Xcode shows me the error Value of type 'NSObject' has no member 'data' for the line try $0.data(as: JStoreUser.self). I've defined the struct as Codable.

#### Relevant Code:
```
private func fetchCurrentUser() {
        guard let uid = FirebaseManager.shared.auth.currentUser?.uid else { return }
        FirebaseManager.shared.firestore.collection(uid).getDocuments{snapshot, error in
            if let error = error {
            print("Failed to fetch current user", error)
            return
        }
            guard let data = snapshot?.data() else {return}
        }
    }
```
The screenshot:
![Screen Shot 2022-03-14 at 9 27 36 AM](https://user-images.githubusercontent.com/57867146/158217052-f5a65386-0c16-46d0-81a5-d0150258613c.png)

**Comment by PROCW** [comment]
I found the solution from StackOverflow.
https://stackoverflow.com/questions/59548819/how-to-convert-document-to-a-custom-object-in-swift-5
but this needs to pod installed.
I imported the FirebaseFirestoreSwift in libraries using package manager without the pod of my project. But error appeared yet. Could you explain that?

**Comment by peterfriese** [comment]
Check out [Mapping Firestore Data in Swift - The Comprehensive Guide | Peter Friese](https://peterfriese.dev/posts/firestore-codable-the-comprehensive-guide/) for an in-depth blog post about how to map Firestore documents from/to Swift.

Specifically, it contains code that shows how to safely map data using Codable and handle errors that might occur. As for fetching the current user, I'd recommend setting up an [authentication state change listener](https://firebase.google.com/docs/auth/ios/start#listen_for_authentication_state) instead.

**Comment by PROCW** [comment]
![Screen Shot 2022-03-14 at 11 34 09 AM](https://user-images.githubusercontent.com/57867146/158238375-f9d4e15f-cc23-414f-b510-30889e619ee0.png)
sorry, this wasn't worked for me.

**Comment by peterfriese** [comment]
It seems like you're fetching a collection of documents, and then try to deal with them as if they're a single document.

**Comment by PROCW** [comment]
I tried following the article but I didn't get anything.
https://peterfriese.dev/posts/swiftui-firebase-fetch-data/
![Screen Shot 2022-03-14 at 12 25 26 PM](https://user-images.githubusercontent.com/57867146/158246342-0b8d5970-08a3-4595-8c68-942b915c020e.png)

**Comment by PROCW** [comment]
![Screen Shot 2022-03-14 at 12 33 19 PM](https://user-images.githubusercontent.com/57867146/158247489-81bdab81-c492-48e1-a864-5f367aa8ab9a.png)
I can't get the values of documents using the following method.
```
FirebaseManager.shared.firestore.collection(uid).addSnapshotListener {(querySnapshot, error) in
            guard let documents = querySnapshot?.documents else {
                print("No documents")
                return
            }
            self.chatUser = documents.map {
                queryDocumentSnapshot -> ChatUser in
                let data = queryDocumentSnapshot.data()
                let uid = data["uid"] as? String ?? ""
                let email = data["email"] as? String ?? ""
                let profileImageUrl = data["profileImageUrl"] as? String ?? ""
                let chatUser = ChatUser(uid: uid, email: email, profileImageUrl: profileImageUrl)
                self.errorMessage = chatUser.profileImageUrl
                print(chatUser.profileImageUrl)
                return chatUser
            }
        }
```

**Comment by dconeybe** [comment]
@PROCW Can you enable debug logging and provide the debug logs? To do this, call `Firestore.enableLogging(true)`. Also, I hate to ask the obvious but can you also confirm that the collection in question is indeed non-empty?

**Comment by PROCW** [comment]
thanks, guys
I solved this problem
```
FirebaseManager.shared.firestore.collection("users").addSnapshotListener {(querySnapshot, error) in
            guard let documents = querySnapshot?.documents else {
                print("No documents")
                return
            }
            self.chatUser = documents.map {
                queryDocumentSnapshot -> ChatUser in
                let data = queryDocumentSnapshot.data()
                let uid = data["uid"] as? String ?? ""
                let email = data["email"] as? String ?? ""
                let profileImageUrl = data["profileImageUrl"] as? String ?? ""
                let chatUser = ChatUser(uid: uid, email: email, profileImageUrl: profileImageUrl)
                self.userData = chatUser
                self.errorMessage = chatUser.profileImageUrl
                print(chatUser.profileImageUrl)
                return chatUser
            }
```

**Comment by dconeybe** [comment]
That's great! I'll mark this issue as closed then.
