### ISSUE TITLE
FirebaseFirestoreSwift creates invalid ios 14 bundle from version 8.11.0-beta and later

### ISSUE THREAD

**Issue by ptxmac** [firebase/firebase-ios-sdk#9468]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.3
  * Firebase SDK version: 8.11.0
  * Installation method: `CocoaPods`
  * Firebase Component: Firestore (Swift extension)
  * Target platform(s): `iOS`

#### Steps to reproduce:

After upgrading `FirebaseFirestoreSwift` from `8.10.0-beta` to `8.11.0-beta` (or later) IPA's build for ios 14 is no longer accepted by Appstore connect. After uploading the follow mail is sent by apple:

> ITMS-90562: Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.

Unfortunately, the error doesn't manifest until the build is uploaded, so it's very slow to debug.

When setting the deployment target to ios 15.0 the build is correctly approved by apple, but on ios 14.0 the above mail is sent, and the build marked as "invalid binary"

#### Relevant Code:

From `Podfile`

```
target "AppExp" do 
    platform :ios, '14.0'. # Note: this only change the version for the pods, the version set in xcode for the primary target is the important one.
    use_frameworks!

    pod 'FirebaseFirestoreSwift' , '~> 8.11.0-beta'

end
```

**Comment by paulb777** [comment]
This looks like an Apple issue with Xcode 13.3. See https://developer.apple.com/forums/thread/701949

Does using Xcode 13.2.1 resolve it?

**Comment by ptxmac** [comment]
Great catch, thank you!

I'll downgrade to xcode 13.2.1 and post an update

**Comment by ptxmac** [comment]
I can confirm that the older version of XCode solves this issue

**Comment by DanielZanchi** [comment]
I installed via SPM. Same issue, downloading another version of Xcode is quite heavy :(
