### ISSUE TITLE
I'm facing same issue at the moment & wished you could share which file in the project should I add this code?

### ISSUE THREAD

**Issue by codemickey78** [firebase/firebase-ios-sdk#9484]
I had the same problem as well. I used this method at app initialization and it works with Ionic and Capacitor:

```
init() {
    const app = initializeApp(environment.firebase);
    if (Capacitor.isNativePlatform) {
      initializeAuth(app, {
        persistence: indexedDBLocalPersistence
      });
    }
    this.firestore = getFirestore(app);
  }
```

`indexedDBLocalPersistence` was not exposed in angular/fire, but there may be a way to do it, I was having issues with angular fire, but this above worked fine using firebase 9 exclusively. There may be a way to do it with angular/fire - I will look into it later.

_Originally posted by @jayordway in https://github.com/firebase/firebase-js-sdk/issues/5552#issuecomment-929580662_

**Comment by rizafran** [comment]
Hi @codemickey78, please note that we're limited to troubleshooting issues related to native iOS SDK. I'll be closing this ticket since the issue seems related to `capacitorjs`, and you may address the issue on the original thread. Thanks.
