### ISSUE TITLE
FirebaseAnalyticsSwift not included with Carthage binary?

### ISSUE THREAD

**Issue by jostster** [firebase/firebase-ios-sdk#9494]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.2
  * Firebase SDK version: 8.13
  * Installation method: `Carthage ` 
  * Firebase Component: Analytics
  * Target platform(s): `iOS`

### [REQUIRED] Step 2: Describe the problem
Unable to access FirebaseAnalyticsSwift components like `.analyticsScreen` because it doesn't seem the FirebaseAnalyticsSwift is built for Carthage binary support.

**Comment by paulb777** [comment]
@jostster Thanks for the request. We just merged support for this today in #9471 for our next major release that should be available in the next few months. In the meantime, a workaround would be adding the source at https://github.com/firebase/firebase-ios-sdk/tree/master/FirebaseAnalyticsSwift/Sources
