### ISSUE TITLE
[Docs] SwiftSample Firebase Auth Links Broken in Documentation

### ISSUE THREAD

**Issue by dweekly** [firebase/firebase-ios-sdk#9505]
https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseAuth/Tests/Sample/README.md

links to several resources that are 404 like https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseAuth/Tests/Sample/SwiftSample/AuthCredentialsTemplate.swift

**Comment by morganchen12** [comment]
Thanks for reporting!
