### ISSUE TITLE
Issue on watch, Firebase data upload not working on watch app while iPhone not connect to the watch app

### ISSUE THREAD

**Issue by ankitpanchotiya-simformsolutions** [firebase/firebase-ios-sdk#9518]
I facing an issue with the watch app. I update child value data using updateChildValues while my iPhone is switched off and the watch is not connected to the iPhone at that time my wifi connection to my watch app only. At that time I have a get an internet connection but still, data was not updated or uploaded on firebase. I have to try uploading data on other servers with the same scenario but it's working fine. 

Can anyone help with this issue? 
Watch OS: - 8.4.2
Firebase Version: - 8.14.0

```
   let hrRef = dbRef?.child("LocationHistory").child("\(userId)").child(sessionKey).child(uuid)
                .child("stepsData")
                hrRef?.keepSynced(true)
                hrRef?.updateChildValues(historyData.toDictionary()) { error, ref in
                    if error != nil {
                        success(false)
                        print("error while updating firebase steps: \(error.debugDescription)")
                    } else {
                        print("===>Online inside record firebase helper")
                        success(true)
                    }
                }
```

Thanks.

**Comment by ryanwilson** [comment]
Thanks for the report @ankitpanchotiya-simformsolutions - we'll try to reproduce on our end and see what's going on. When you say you've tried uploading data on other servers, you mean with the iPhone switched off but Watch still connected to WiFi?

**Comment by ankitpanchotiya-simformsolutions** [comment]
> Thanks for the report @ankitpanchotiya-simformsolutions - we'll try to reproduce it on our end and see what's going on. When you say you've tried uploading data on other servers, you mean with the iPhone switched off but the Watch still connected to WiFi?

Yes, the Watch connected to the WIFI, at that time I am able to download the app from the AppStore and play music from Spotify etc..

**Comment by ankitpanchotiya-simformsolutions** [comment]
@ryanwilson  Any update on this?

**Comment by ryanwilson** [comment]
Sorry for the delay, hoping to take a look this week or early next week. We're working on a major version update at the moment (https://github.com/firebase/firebase-ios-sdk/milestone/84) that's taking up a lot of bandwidth right now.

**Comment by pradeepchakoriya-simformsolutions** [comment]
@ryanwilson  is there any update on this? we are eagerly waiting on this fixes.

**Comment by paulb777** [comment]
I'm going to close this as infeasible based on #10195
