### ISSUE TITLE
Cannot install latest version SDK (8.14.0)

### ISSUE THREAD

**Issue by ChurikiTenna** [firebase/firebase-ios-sdk#9533]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.2
  * Firebase SDK version: 6.34
  * Installation method: CocoaPods
  * Firebase Component: -
  * Target platform(s): iOS

### [REQUIRED] Step 2: Describe the problem

I am trying to install latest SDK version, but no matter how I try it, it shows error below.

```
[!] CocoaPods could not find compatible versions for pod "FirebaseAnalytics":
  In snapshot (Podfile.lock):
    FirebaseAnalytics (= 6.9.0)

  In Podfile:
    Firebase (~> 8.14.0) was resolved to 8.14.0, which depends on
      Firebase/Core (= 8.14.0) was resolved to 8.14.0, which depends on
        FirebaseAnalytics (~> 8.14.0)

    FirebaseAnalytics

Specs satisfying the `FirebaseAnalytics, FirebaseAnalytics (= 6.9.0), FirebaseAnalytics (~> 8.14.0)` dependency were found, but they required a higher minimum deployment target.
```

#### Steps to reproduce:

Run
`arch -x86_64 pod install`
with podfile below.

I tried:
- Deleting pod.lock, and run pod install

- sudo arch -x86_64 gem install ffi -> pod repo update 

- pod repo remove master -> cd ~/.cocoapods/repos -> git clone https://github.com/CocoaPods/Specs.git master -> pod setup -> pod install 

But none of them worked. 

#### Relevant Code:

```
platform :ios, '15.0'

target 'weddingSearch' do

  use_frameworks!

  pod 'Firebase', '~> 8.14.0'
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseStorage'
  pod 'FirebaseFirestore'
  pod 'FirebaseFirestoreSwift'
  pod 'GoogleSignIn'
  pod 'FirebaseMessaging'

end
```

Thank you for your time.

**Comment by rizafran** [comment]
Thanks for reporting, @ChurikiTenna. It looks like you need to use `pod 'FirebaseFirestoreSwift', '~> 8.14.0-beta'` instead. The following steps worked for me:

1. Run `pod deintegrate`
2. Run `pod init`
3. Add the dependencies in Podfile:
      ```
         pod 'Firebase'
         pod 'FirebaseAnalytics'
         pod 'FirebaseAuth'
         pod 'FirebaseStorage'
         pod 'FirebaseFirestore'
         pod 'FirebaseFirestoreSwift', '~> 8.14.0-beta'
         pod 'GoogleSignIn'
         pod 'FirebaseMessaging' ```
4. Run `arch -x86_64 pod install` or `pod install`

**Comment by ChurikiTenna** [comment]
Hi, thank you of the reply.

I had to manually deleted Podfile.lock after `pod deintegrate`.
And it worked!!!

Thank you always for your support!
