### ISSUE TITLE
Firebase InAppMessaging messageClicked not calling for ios

### ISSUE THREAD

**Issue by guoqianglaien** [firebase/firebase-ios-sdk#9536]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.2.1
  * Firebase SDK version:  8.10.0
  * Installation method: `CocoaPods
  * Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Target platform(s): iOS 

### [REQUIRED] Step 2: 

Firebase InAppMessaging onClickListener not calling when user clicked 
   func messageClicked(_ inAppMessage: InAppMessagingDisplayMessage) {
    }

Firebase InAppMessaging only  
func impressionDetected(for inAppMessage: InAppMessagingDisplayMessage) {
}
can call back

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by rizafran** [comment]
Thanks for the report, @guoqianglaien. I'm able to trigger the `messageClicked` function. Could you share the detailed steps or sample app reproducing the issue?

**Comment by abiesteves** [comment]
you can check by deleting messageClicked and try typing it again. You will see the right properties for the delegate. For Xcode 13.0+ it should have, `with action : InAppMessagingAction` in the func.

**Comment by rizafran** [comment]
Hi @abiesteves, when I click the button in the popup message, the following function is being called properly:
`func messageClicked(_ inAppMessage: InAppMessagingDisplayMessage, with action: InAppMessagingAction){
}`

To make sure we're on the same page, could you provide the detailed steps you made to reproduce the issue?
