### ISSUE TITLE
Crash On Application Launch 

### ISSUE THREAD

**Issue by niljaisw** [firebase/firebase-ios-sdk#9545]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.3
  * Firebase SDK version: 7.8.1
  * Installation method: `CocoaPods | Carthage | Zip file | Swift Package Manager` (select one)
  * Firebase Component: Core (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Target platform(s): `All | iOS | Catalyst | macOS | tvOS | watchOS`

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```

Application crashing on launch intermittently: 


Crash Logs: 


Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Last Exception Backtrace:
0   CoreFoundation                	0x1814c6d3c __exceptionPreprocess + 216 (NSException.m:200)
1   libobjc.A.dylib               	0x1988406a8 objc_exception_throw + 56 (objc-exception.mm:565)
2   CoreFoundation                	0x181596768 -[NSObject(NSObject) doesNotRecognizeSelector:] + 140 (NSObject.m:147)
3   CoreFoundation                	0x181460f6c ___forwarding___ + 1440 (NSForwarding.m:3577)
4   CoreFoundation                	0x1814601dc _CF_forwarding_prep_0 + 92
5   Cisco UDN                     	0x1028128f0 +[FIRMessagingTokenOperation HTTPAuthHeaderFromCheckin:] + 36 (FIRMessagingTokenOperation.m:223)
6   Cisco UDN                     	0x102812598 -[FIRMessagingTokenOperation tokenRequest] + 60 (FIRMessagingTokenOperation.m:163)
7   Cisco UDN                     	0x10280e2b0 -[FIRMessagingTokenFetchOperation performTokenOperation] + 48 (FIRMessagingTokenFetchOperation.m:55)
8   Cisco UDN                     	0x1027dd390 __55-[FIRInstallations authTokenForcingRefresh:completion:]_block_invoke_2 + 24 (FIRInstallations.m:232)
9   Cisco UDN                     	0x10285c24c 0x102760000 + 1032780
10  libdispatch.dylib             	0x1811921a4 _dispatch_call_block_and_release + 24 (init.c:1517)
11  libdispatch.dylib             	0x1811931a8 _dispatch_client_callout + 16 (object.m:560)
12  libdispatch.dylib             	0x181174508 _dispatch_main_queue_callback_4CF$VARIANT$armv81 + 988 (inline_internal.h:2587)
13  CoreFoundation                	0x181482888 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12 (CFRunLoop.c:1795)
14  CoreFoundation                	0x181440188 __CFRunLoopRun + 2528 (CFRunLoop.c:3144)
15  CoreFoundation                	0x181452e1c CFRunLoopRunSpecific + 572 (CFRunLoop.c:3268)
16  GraphicsServices              	0x1a17f59a0 GSEventRunModal + 160 (GSEvent.c:2200)
17  UIKitCore                     	0x183c86b90 -[UIApplication _run] + 1080 (UIApplication.m:3493)
18  UIKitCore                     	0x183a1c16c UIApplicationMain + 332 (UIApplication.m:5047)
19  Cisco UDN                     	0x102769c6c main + 148 (main.m:41)
20  dyld                          	0x103d64250 start + 444 (dyldMain.cpp:879) 


```

**Comment by rizafran** [comment]
Hi @niljaisw, is the issue reproducible using the latest version? Also, it would be helpful for investigation if you could provide the detailed steps or reproducible sample app. Thanks.

**Comment by niljaisw** [comment]
I will try to reproduce on latest version, this issue is intermittent issue not frequently reproducible. This happens as soon as you launch the application.

**Comment by morganchen12** [comment]
Frame 2 of the stack trace indicates it's in unrecognized selector crash, which is extremely strange since this method has always been defined in the class implementation itself (not an extension) and should always be available at runtime. Are you doing any dynamic class/method modification in your app's runtime?

**Comment by niljaisw** [comment]
Hello,

No, I am not doing any dynamic class/method modification.

**Comment by morganchen12** [comment]
Got it, let us know if you can reproduce the crash and we'll continue investigation from there.
