### ISSUE TITLE
[AppCheck] 403 Error thrown when trying to obtain debug token via /exchangeDebugToken endpoint

### ISSUE THREAD

**Issue by IljaDaderko** [firebase/firebase-ios-sdk#9547]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.3 (13E113)
  * Firebase SDK version: 8.14.0
  * Installation method: `CocoaPods`
  * Firebase Component: AppCheck
  * Target platform(s): `iOS`

#### Steps to reproduce:

I'm closely following app check documentation in order to use debug token, however instead of seeing it logged out in the console I see following error (when running in debug simulator from xcode)

NOTE: Everything works as expected in testflight / real device build

```zsh
[Firebase/AppCheck][I-FAA004002] Failed to exchange debug token to app check token: Error Domain=com.firebase.appCheck Code=0 "The server responded with an error: 
 - URL: https://firebaseappcheck.googleapis.com/v1beta/projects/[my-project-id]/apps/1:[sensitive-data]:ios:[sensitive-data]:exchangeDebugToken 
 - HTTP status code: 403 
 - Response body: {
  "error": {
    "code": 403,
    "message": "App attestation failed.",
    "status": "PERMISSION_DENIED"
  }
}
```

**Thus far I've implemented following steps, but had no luck**

 1. Enabled both attestation providers for my ios project (App Attest got enabled automatically when I added my team id)
![](https://i.stack.imgur.com/Ztbuz.png)

---

 2. Added `FIRAppCheckDebugProviderFactory` in my code i.e.
```objc
  #if DEBUG
    FIRAppCheckDebugProviderFactory *providerFactory = [[FIRAppCheckDebugProviderFactory alloc] init];
    [FIRAppCheck setAppCheckProviderFactory:providerFactory];
  #endif
  
  [FIRApp configure];
```

---

 3. Added `-FIRDebugEnabled` to my debug run launch arguments in schema
![](https://i.stack.imgur.com/rYYcs.png)
---

 4. Added AppCheck capability to my target and set .entitlements App Attest environment to production
![](https://i.stack.imgur.com/ZgjER.png)

**Comment by IljaDaderko** [comment]
@ncooke3 

* iOS 15.4
* Yep, happens every time
* Error happens prior to the step that logs the debug token to XCode console i.e I am on `Launch the app. A local debug token will be logged when the SDK tries to send a request to the backend. For example:` step and instead of logging the debug token I receive that error

**Comment by IljaDaderko** [comment]
Just to give you an update, I removed any app check related logic from my app besides setting debug factory in dev environment i.e. (so I'm no longer trying to read debug token or do anything with it)

```objc
#if DEBUG
    FIRAppCheckDebugProviderFactory *providerFactory = [[FIRAppCheckDebugProviderFactory alloc] init];
    [FIRAppCheck setAppCheckProviderFactory:providerFactory];
#endif
```

This still causes an error on app launch. Pretty sure there is a bug preventing me to call that `/exchangeDebugToken` endpoint from ios simulator or I am missing something in my project that allows to do that.

That said, other services like auth and crashlytics are working fine and as expected. I also double verified I am using correct plist config file and everything. 

The only difference from documentation that I can think of is that I don't use any app check protected services (firestore, storage etc...) due to using my own backend (but I actually didn't even get to this bit since I can't retrieve debug token)

**Comment by ncooke3** [comment]
Hi @IljaDaderko,

Sincere apologies for the delay here! I've been taking a closer look into the issue and I think I may know what is going on. 

When the debug token is generated by the SDK, it is then cached in local storage for future retrieval. Currently, the SDK's behavior only prints the debug token when it is created. 

There are two options here to try and retrieve the debug token:
1. add a breakpoint [here](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseAppCheck/Sources/DebugProvider/FIRAppCheckDebugProvider.m#L90). This code path should be hit when the debug provider is configured. Then, in the Xcode debugger:
```console
po [self storedDebugToken]
```
If the token is cached, it will be printed to the console!

2. delete the app and re-install a fresh copy. Then be careful to inspect the logs on the first run (as that is when the debug token is printed!)

**Comment by IljaDaderko** [comment]
Gotcha, I'll try this out soon, so am I correct in understanding that my issue is due to following

1. The very first time app is installed / started it logs debug token
2. Once debug token is logged it should be added in firebase dashboard
3. After this all subsequent launches of the app reuse debug token that was logged initially
4. If initial token was not added to firebase console a 403 error will be thrown as app is using unverified token?

**Comment by IljaDaderko** [comment]
Seems like that was indeed the issue 👍 I think it's worth mentioning this in the docs, but other than that feel free to close this whenever you are ready. Thank you for your help :)

**Comment by ncooke3** [comment]
Glad to hear! I opened a PR with improved documentation regarding this issue.

**Comment by ncooke3** [comment]
For completeness, I wanted to leave a note for future readers of this thread that are trying to find their local debug token:
There are two ways to get the debug token _from the AppCheck SDK_ depending on how you configure the Firebase App Check instance.

- If you've configured AppCheck with a default `AppCheckDebugFactory` instance:
```swift
AppCheck.setAppCheckProviderFactory(AppCheckDebugProviderFactory())
```
Then the debug token should be printed to the console. You can search the console logs for:
```console
Firebase App Check debug token:
```
Note that there may be several error messages in the logs since you have not yet uploaded the debug token to the Firebase console.

--- 

- If you've implemented a custom `AppCheckProviderFactory` that returns an `AppCheckDebugProvider` within your factory's implementation, you can access the debug token by using the `AppCheckDebugProvider.localDebugToken` API.
```swift
class YourAppCheckProviderFactory: NSObject, AppCheckProviderFactory {
  func createProvider(with app: FirebaseApp) -> AppCheckProvider? {
#if DEBUG
     let debugProvider = AppCheckDebugProvider(app: app)
     // You can access debug token using the debugProvider.localDebugToken API!
     return debugProvider
#endif  // DEBUG

    // Return other providers.
  }
}
```

--- 

If you're running into issues, you can use the debugger to inspect the debug token:
- Add a breakpoint [here](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseAppCheck/Sources/DebugProvider/FIRAppCheckDebugProvider.m#L90). This code path should be hit when the debug provider is configured. Then, in the Xcode debugger:
```console
po [self storedDebugToken]
```
If the token is cached, it will be printed to the console.

Of course, please open an issue if you have further questions!

cc: @weixifan
