### ISSUE TITLE
`FIRFunctionsErrorCode` shouldn't have `FIR` prefix in Swift

### ISSUE THREAD

**Issue by ryanwilson** [firebase/firebase-ios-sdk#956]
`FIRFunctionsErrorCode` still has the `FIR` prefix in Swift, but it should have been removed. 

The fix is easy, I've made PR #955, but we have to wait for a major release now.

https://github.com/firebase/firebase-ios-sdk/blob/d924771453d000e708bd5d239da3bae4feb489ac/Functions/FirebaseFunctions/Public/FIRError.h#L31

**Comment by bklimt** [comment]
Ugh. I wonder if there's some way to set up a lint to catch this issue.

**Comment by paulb777** [comment]
Closed by #955
