### ISSUE TITLE
[Firestore] Undocumented change in behaviour of `data(as:)` returning `nil` to throwing an error

### ISSUE THREAD

**Issue by simonmitchell** [firebase/firebase-ios-sdk#9564]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: _____
  * Firebase SDK version: 8.14.0
  * Installation method: `Swift Package Manager` (select one)
  * Firebase Component: Database
  * Target platform(s): `iOS/All (Potentially)`

### [REQUIRED] Step 2: Describe the problem

Between v 8.6.0 and 8.14.0 there has been a breaking change to the `Firestore.Decoder` which means that the code in `DocumentSnapshot+ReadDecodable.swift` and potentially other locations has a breaking change for users.

When we were on 8.6.0 if a record wasn't present the function would return `nil` as the documentation suggests, now instead we get an error thrown:

▿ DecodingError
  ▿ valueNotFound : 2 elements
    - .0 : Swift.KeyedDecodingContainer<LumenateApp.Profile.CodingKeys>
    ▿ .1 : Context
      - codingPath : 0 elements
      - debugDescription : "Cannot get keyed decoding container -- found null value instead."
      - underlyingError : nil

#### Steps to reproduce:

1. Get reference to a document that is not present in firebase using `getDocument`
2. Call `data(as: SomeDecodableStruct)`

See that on 8.6.0 this will return nil
See that on 8.14.0 this will throw an error

I have managed to resolve this by changing `SomeDecodableStruct` to `Optional<SomeDecodableStruct>` which changes it back to returning `nil` which is probably expected behaviour, but this was a breaking change introduced in a non-breaking version bump that as far as I can see was undocumented!

**Comment by paulb777** [comment]
Thanks for the report @simonmitchell and sorry about the trouble.

This is likely the result of #9101 we released in 8.13.0 to improve the API. I believe we discuss the possibility of breaking in the PR discussion, but it didn't make it to the release notes. 

Note, that since FirebaseFirestoreSwift is still in beta, it is acceptable to change APIs in semantic versioning. However, we should still provide clear documentation about the break.

cc: @schmidt-sebastian, @mortenbekditlevsen @morganchen12

**Comment by peterfriese** [comment]
As mentioned in [this comment](https://github.com/firebase/firebase-ios-sdk/pull/9101#issuecomment-1024519806) on PR 9101, we updated the docs, blog post, and sample code. This is also mentioned in the [release notes](https://firebase.google.com/support/release-notes/ios#cloud-firestore_1)


- [Get data with Cloud Firestore  |  Firebase Documentation](https://firebase.google.com/docs/firestore/query-data/get-data#custom_objects)
- [Mapping Firestore Data in Swift - The Comprehensive Guide | Peter Friese](https://peterfriese.dev/posts/firestore-codable-the-comprehensive-guide/#mapping-simple-types-using-codable)
- [Quick Start for iOS](https://github.com/firebase/quickstart-ios/blob/master/firestore/FirestoreSwiftUIExample/ViewModels/RestaurantListViewModel.swift#L53)

We are also working on turning [Mapping Firestore Data in Swift - The Comprehensive Guide | Peter Friese](https://peterfriese.dev/posts/firestore-codable-the-comprehensive-guide/#mapping-simple-types-using-codable) into an official guide in the Firestore section in the docs.

**Comment by simonmitchell** [comment]
Apologies! I had not managed to find any of that info myself but I did have a lot to get through and think of today so that probably rests on me ☺️ And totally fair enough that it’s still in beta and thus breaking changes can be expected!

Thank you both for following up so swiftly! I’ll close this out now.
