### ISSUE TITLE
Add Custom Time support in Firebase Cloud Storage Metadata

### ISSUE THREAD

**Issue by NathanFallet** [firebase/firebase-ios-sdk#9575]
### Feature proposal

* Firebase Component: Storage (Auth, Core, Database, Firestore, Messaging, Storage, etc)

Add a way to set/get Custom Time Metadata in Firebase Cloud Storage

**Comment by NathanFallet** [comment]
@paulb777 Do you know if there is anything new on the backend? Or maybe I can help?

**Comment by paulb777** [comment]
@NathanFallet Sorry, I don't think anything on the backend has changed and its code is not open.
