### ISSUE TITLE
Xcode 13.2 - iOS 15 error message appears in Xcode console

### ISSUE THREAD

**Issue by Sara08101995** [firebase/firebase-ios-sdk#9585]
**[REQUIRED] Step 1: Describe your environment**

1.  Xcode version: 13.2
2. Firebase SDK version: 8.11.0
3. Installation method: CocoaPods

**[REQUIRED] Step 2: Describe the problem**

While minimising the iOS app then it goes to crash and logs throws like below

2022-04-06 17:35:27.318267+0530 Mobile[2539:1073043] [] nw_hash_table_apply called with null table
2022-04-06 17:35:27.318853+0530 Mobile[2539:1073043] [] nw_hash_table_apply called with null table, dumping backtrace:
        [arm64] libnetcore-2736.12.1
    0   libnetwork.dylib                    0x000000018301a9c0 __nw_create_backtrace_string + 120
    1   libnetwork.dylib                    0x000000018279487c nw_hash_table_apply + 2808
    2   libnetwork.dylib                    0x0000000182d1c1e4 D810C689-1339-3FC6-96E8-196B9901E4DC + 6300132
    3   libnetwork.dylib                    0x0000000182d19cc0 D810C689-1339-3FC6-96E8-196B9901E4DC + 6290624
    4   CFNetwork                           0x00000001824c5ff4 _CFURLStorageSessionCopyIdentifier + 20652
    5   libnetwork.dylib                    0x00000001828b9da4 D810C689-1339-3FC6-96E8-196B9901E4DC + 1703332
    6   libdispatch.dylib                   0x0000000101eaca20 _dispatch_call_block_and_release + 32
    7   libdispatch.dylib                   0x0000000101eae700 _dispatch_client_callout + 20
    8   libdispatch.dylib                   0x0000000101eb8e34 _dispatch_workloop_invoke + 2960
    9   libdispatch.dylib                   0x0000000101ec3fa0 _dispatch_workloop_worker_thread + 916
    10  libsystem_pthread.dylib             0x00000001f1f0d1b0 _pthread_wqthread + 288
    11  libsystem_pthread.dylib             0x00000001f1f0cf50 start_wqthread + 8
2022-04-06 17:35:27.495501+0530 Mobile[2539:1073034] [] __nwlog_err_simulate_crash simulate crash already simulated "nw_hash_table_apply called with null table"
2022-04-06 17:35:27.496016+0530 Mobile[2539:1073034] [] nw_hash_table_apply called with null table, dumping backtrace:
        [arm64] libnetcore-2736.12.1
    0   libnetwork.dylib                    0x000000018301a9c0 __nw_create_backtrace_string + 120
    1   libnetwork.dylib                    0x000000018279487c nw_hash_table_apply + 2808
    2   libnetwork.dylib                    0x0000000182d1c1e4 D810C689-1339-3FC6-96E8-196B9901E4DC + 6300132
    3   libnetwork.dylib                    0x0000000182d19cc0 D810C689-1339-3FC6-96E8-196B9901E4DC + 6290624
    4   CFNetwork                           0x00000001824c5ff4 _CFURLStorageSessionCopyIdentifier + 20652
    5   libnetwork.dylib                    0x00000001828b9da4 D810C689-1339-3FC6-96E8-196B9901E4DC + 1703332
    6   libdispatch.dylib                   0x0000000101eaca20 _dispatch_call_block_and_release + 32
    7   libdispatch.dylib                   0x0000000101eae700 _dispatch_client_callout + 20
    8   libdispatch.dylib                   0x0000000101eb8e34 _dispatch_workloop_invoke + 2960
    9   libdispatch.dylib                   0x0000000101ec3fa0 _dispatch_workloop_worker_thread + 916
    10  libsystem_pthread.dylib             0x00000001f1f0d1b0 _pthread_wqthread + 288
    11  libsystem_pthread.dylib             0x00000001f1f0cf50 start_wqthread + 8
    
    Message from debugger: Terminated due to signal 9

 **Steps to reproduce:**

While minimising the app then app goes to crash.(iOS 15 versions)

Note: app working in iOS14 versions

**Relevant Code:**

I checked the code and tried to comment out **NSURLSessionUploadTask** api call in GULNetworkURLSession.m class. Then app working fine without crash.

**Method**: - (nullable NSString *)sessionIDFromAsyncPOSTRequest:(NSURLRequest *)request
                                   completionHandler:(GULNetworkURLSessionCompletionHandler)handler;

**Framework**: GoogleUtilities   

Please help on this .

**Comment by Sara08101995** [comment]
Xcode 13 - iOS 15

**Comment by rizafran** [comment]
Hi @Sara08101995, your issue seems related to #8744. Based on the discussion, it is an Apple issue, so this should be filed or followed up on Apple forums about resolution timing.

**Comment by paulb777** [comment]
Note the crash may be unrelated to the log message.  If you can provide a backtrace and/or reproducible example for the crash, please open another issue.
