### ISSUE TITLE
Analyze error: Dereference of null pointer - Update Firebase when nanopb releases fix

### ISSUE THREAD

**Issue by afern247** [firebase/firebase-ios-sdk#9587]
I have installed via SPM Analytics and Crashlytics. There are 2 warnings coming up:

![image](https://user-images.githubusercontent.com/34192856/162020427-11fb9ff9-0368-4561-9a26-80274b24e784.png)

They are flagged as logic error:

![image](https://user-images.githubusercontent.com/34192856/162020127-8902d837-1979-4738-8140-6ecd6c553a0c.png)

**Comment by rizafran** [comment]
Hi @afern247, please provide all the details needed from the issue template. Thanks.

**Comment by paulb777** [comment]
This is https://github.com/nanopb/nanopb/issues/667. The fix has been merged to the nanopb release branch, but has not yet been released.  Also referenced at #8134.  

A Firebase resolution needs to wait for the nanopb release. I'll leave this issue open to track.

**Comment by paulb777** [comment]
nanopb 0.3.9.9 published yesterday. It will be likely be too late for 9.0.0, so I'll target Firebase's update to 9.1.0

**Comment by Eric-Catalyst** [comment]
Is there a public date for 9.1.0?

**Comment by paulb777** [comment]
It's currently targeted for the week of May 23rd.
