### ISSUE TITLE
SPM firebase-ios-sdk 8.15.0 fails due to dependency on googleappmeasurement

### ISSUE THREAD

**Issue by guidedways** [firebase/firebase-ios-sdk#9597]
I'm not sure if this is a false positive but I've been unsuccessful in adding `firebase-ios-sdk` 8.15.0 to our project:

1) `git clone https://github.com/firebase/firebase-ios-sdk.git;pushd firebase-ios-sdk;git checkout v8.15.0;popd`
2) Drag `firebase-ios-sdk` as a local file reference to your workspace in Xcode
3) On command line run:

```
xcodebuild -resolvePackageDependencies -workspace ... -scheme "..."
```

This results in:

```
xcodebuild: error: Could not resolve package dependencies:
  Dependencies could not be resolved because no versions of 'googleappmeasurement' match the requirement 8.15.0 and root depends on 'googleappmeasurement' 8.15.0.
  artifact not found for target 'FirebaseAnalytics'
```

If I switch to 8.14.0, I see no more errors and the packages resolve:

`git clone https://github.com/firebase/firebase-ios-sdk.git;pushd firebase-ios-sdk;git checkout v8.14.0;popd`

Not sure if I'm doing something wrong?

**Comment by rizafran** [comment]
Thanks for reporting, @guidedways. It looks like `8.15.0` is not yet published. Based on this related [ticket](https://github.com/google/GoogleAppMeasurement/issues/20), you may refer to published tags instead of the master branch.
