### ISSUE TITLE
Overview of open source intention; roadmap

### ISSUE THREAD

**Issue by mhuusko5** [firebase/firebase-ios-sdk#96]
It would be very valuable to see the README amended, or perhaps a separate document in the repo added, to cover the intention of this open sourcing effort and where it might (I imagine things are still in flux) be going. If applicable (based on that intention), this document could expand to include a roadmap for the SDK, providing possible areas of community contribution.

**Comment by paulb777** [comment]
Good suggestion! 

I'll add something more specific later this week. In the meantime, see the announcement blog - https://opensource.googleblog.com/2017/05/open-sourcing-firebase-sdks.html

**Comment by paulb777** [comment]
Added [Roadmap](https://github.com/firebase/firebase-ios-sdk/blob/master/ROADMAP.md)
