### ISSUE TITLE
Crash on application launch

### ISSUE THREAD

**Issue by mmdock** [firebase/firebase-ios-sdk#9602]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.1
  * Firebase SDK, install method, and components:
```
  pod 'Firebase/Analytics', '~> 8.6.1'
  pod 'Firebase/Crashlytics', '~> 8.6.1'
  pod 'Firebase/Performance', '~> 8.6.1'
  pod 'Firebase/RemoteConfig', '~> 8.6.1'
```
  * Target platform(s): `iOS` (minimum target iOS 12)

#### Steps to reproduce:
I install via cocoapods
recently, these versions have sub dependencies that changed, specifically, 
FirebaseInstallations
FirebaseABTesting
FirebaseCoreDiagnostics

were upgraded up to 8.14.0,  This seems to be causing a crash in simulator **only**, but _only_ if you install the application to simulator twice. (install, stop it via xcode, install again) 

I reproduced this on simulator iOS 14 and 15.  I was unable to reproduce with a physical device.  I did not check for earlier OS versions having this issue.

I actually attempted to set these dependency pods manually via:
```
  pod 'FirebaseInstallations', '~> 8.6.0'
  pod 'FirebaseABTesting', '~> 8.6.0'
  pod 'FirebaseCoreDiagnostics', '~> 8.6.0'
```

which seems to resolve it for pre-ios 15 installations in simulator but not for iOS 15. 

'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff203fbbb4 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff2019ebe7 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2047bf38 _CFThrowFormattedException + 194
	3   CoreFoundation                      0x00007fff20479bcd -[__NSArrayM insertObject:atIndex:].cold.2 + 0
	4   CoreFoundation                      0x00007fff202f7a9e -[__NSArrayM insertObject:atIndex:] + 1095
	5   DBDebugToolkit                      0x000000010692d58d +[NSURLSessionConfiguration(DBURLProtocol) db_defaultSessionConfiguration] + 173
	6   GoogleDataTransport                 0x00000001071b4dba -[GDTCCTUploadOperation uploaderSessionCreateIfNeeded] + 58
	7   GoogleDataTransport                 0x00000001071b7445 __56-[GDTCCTUploadOperation sendURLRequestWithBatch:target:]_block_invoke.110 + 69
	8   FBLPromises                         0x00000001060c92e5 __56-[FBLPromise chainOnQueue:chainedFulfill:chainedReject:]_block_invoke.67 + 85
	9   FBLPromises                         0x00000001060c88ca __44-[FBLPromise observeOnQueue:fulfill:reject:]_block_invoke_2 + 106
	10  libdispatch.dylib                   0x000000010729aa28 _dispatch_call_block_and_release + 12
	11  libdispatch.dylib                   0x000000010729bc0c _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x00000001072a278a _dispatch_lane_serial_drain + 1237
	13  libdispatch.dylib                   0x00000001072a32fe _dispatch_lane_invoke + 436
	14  libdispatch.dylib                   0x00000001072af59b _dispatch_workloop_worker_thread + 900
	15  libsystem_pthread.dylib             0x00007fff6bff2074 _pthread_wqthread + 326
	16  libsystem_pthread.dylib             0x00007fff6bff0ffb start_wqthread + 15
)
libc++abi: terminating with uncaught exception of type NSException

**Comment by ryanwilson** [comment]
Thanks for the report - based on the call stack I believe the issue is with DBDebugToolkit (https://github.com/dbukowski/DBDebugToolkit) not Firebase. 

GoogleUtilities attempts to get the `NSURLSessionConfiguration`'s `defaultSessionConfiguration` here:

https://github.com/google/GoogleDataTransport/blob/1a65c30db4fc841e06586441682c2dda036d9db3/GoogleDataTransport/GDTCCTLibrary/GDTCCTUploadOperation.m#L105

but it looks like the DBDebugToolkit swizzles it, intercepting the call and then crashing.

If you can reproduce the crash without `DBDebugToolkit` in the stack trace, please re-open the issue and provided an updated stack trace. Thanks!

**Comment by mmdock** [comment]
@ryanwilson  i thought that too, but removing DBDebugtoolkit does not fix the crash, only downgrading firebase

**Comment by morganchen12** [comment]
@mmdock what's the stack trace after you remove `DBDebugToolkit`? Frame 5 of the crash has a category that only exists in that framework, so if your app is still crashing it's likely a different crash.

```
5 DBDebugToolkit 0x000000010692d58d +[NSURLSessionConfiguration(DBURLProtocol) db_defaultSessionConfiguration] + 173
```
