### ISSUE TITLE
Domain=FIRAuthErrorDomain Code=17999

### ISSUE THREAD

**Issue by ravipappyogi** [firebase/firebase-ios-sdk#9608]
* Xcode version: 13.3
* Firebase SDK version: 8.14.0
* Firebase Component: Authentication
* Component version: 8.14.0

I'm trying to authenticate using phone number but some arab countries we getting following errror. 

`Error Domain=FIRAuthErrorDomain Code=17999 "An internal error has occurred, print and inspect the error details for more information." UserInfo={FIRAuthErrorUserInfoNameKey=ERROR_INTERNAL_ERROR, NSLocalizedDescription=An internal error has occurred, print and inspect the error details for more information., NSUnderlyingError=0x2822341e0 {Error Domain=FIRAuthInternalErrorDomain Code=3 "(null)" UserInfo={FIRAuthErrorUserInfoDataKey={length = 1623, bytes = 0x3c21444f 43545950 45206874 6d6c3e0a ... 2e3c2f69 6e733e0a }, NSUnderlyingError=0x28221a400 {Error Domain=com.google.HTTPStatus Code=403 "(null)" UserInfo={data={length = 1623, bytes = 0x3c21444f 43545950 45206874 6d6c3e0a ... 2e3c2f69 6e733e0a }, data_content_type=text/html; charset=UTF-8}}}}}`

The app was working in production but only facing issue with some counties only.

So can you please check and give solution for it?

**Comment by rizafran** [comment]
Hi @ravipappyogi, upon checking, it seems that the Firebase Support team is currently handling and checking your issue. I'll be closing this for now so you can continue getting updates from them. Thanks.
