### ISSUE TITLE
Feature: Support dynamic targets

### ISSUE THREAD

**Issue by guidedways** [firebase/firebase-ios-sdk#9609]
### Feature proposal

* Firebase Component: **FirebaseCrashlytics** (Auth, Core, Database, Firestore, Messaging, Storage, etc)

Can we support dynamic targets for Crashlytcs / Analytics by adding an additional library target in `Package.swift` such as this?

```
.library(
      name: "FirebaseCrashlyticsDynamic",
      type: .dynamic,
      targets: ["FirebaseCrashlytics"]
    ),
```

This way we'll be able to ship a single dynamic framework for all the targets of the app that wish to link with Crashlytics (if crash reporting will still work when it's loaded dynamically?) This would considerably shrink the size of our app bundle as currently each target that links with crashlytics, does so statically, resulting in a much larger overall .app bundle.

Clients could then wish to link against `FirebaseCrashlyticsDynamic` instead. 

Most Swift Packages support dynamic targets now, such as RxSwift: https://github.com/ReactiveX/RxSwift/blob/main/Package.swift

**Comment by guidedways** [comment]
I realize the risks / issues of linking with Firebase libraries dynamically so the above suggestion may simply not work. Having said that, is there an easy way to produce or distribute Firebase (Crashlytics / Analytics etc) as pre-compiled, static libraries so we could link with these once? I'd love to be able to use a `xcframework` ideally to avoid having to build Firebase as part of a clean build each time. 

Right now 50% of the overall compilation time in our projects is spent compiling and linking against Firebase.

**Comment by paulb777** [comment]
We have two distributions that distribute via static xcframeworks - [Carthage](https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md) and a [binary zip](https://github.com/firebase/firebase-ios-sdk/releases/tag/v8.14.0).

**Comment by guidedways** [comment]
Wow how did I miss that! Thank you!

**Comment by guidedways** [comment]
@paulb777 Thanks again - I noticed there's no `FirebaseAnalyticsWithoutAdIdSupport` target and just one `FirebaseAnalytics`. Do I need to do anything special to make sure we don't get `AdId` support inadvertently added to the app?

**Comment by paulb777** [comment]
Don't copy and include `GoogleAppMeasurementIdentitySupport.xcframework` to disable `AdId` support.
