### ISSUE TITLE
Firestore rules failing with custom claims within tokens

### ISSUE THREAD

**Issue by stevejcox** [firebase/firebase-ios-sdk#961]
* Xcode version: 9.2
  * Firebase SDK version: 4.11
  * Firebase Component: Auth / Firestore
  * Component version: 4.5 / 0.10.4

I have a system where the user is able to 'step up' their credentials by approving a code emailed / sent via sms. The endpoint is a http cloud function with code that ultimately creates a claim using:

```
let claim = new Claim()
claim.deviceApproved = deviceApproved
claim.ssnApproved = ssnApproved
claim.ownershipApproved = ownershipApproved
return this.admin.auth().setCustomUserClaims(userKey, claim)
```

Once the claim claim is set, the iOS app refreshes the token using getIDTokenForcingRefresh.

I can confirm he claim is coming back and has the relevant credentials. Now both read and writes to the database that use these credentials _sometimes_ fail, with no apparent reason as to why.

I've included an example read, but various writes do the same thing. 

Using Charles proxy I can see the requests being made to get the id token and can confirm relevant claims are included there. 

Rules are included below for reference.

#### Steps to reproduce:

I am finding it hard to create an example where I can get this to reoccur, unfortunately trying to simplify the app for demo I have been unable to recreate the issue, yet it persists in the main app.

#### Relevant Code:
Rules:
```
service cloud.firestore {
  match /databases/{database}/documents {

    function notAnonymous() {
      return request.auth.uid != null
    }

    function signedIn(uid) {
      return request.auth.uid != null && request.auth.uid == uid;
    }

    function deviceApproved(uid) {
      return signedIn(uid) && request.auth.token.deviceApproved == true;
    }

    function deviceOwner(uid) {
      return signedIn(uid) && deviceApproved(uid) && request.auth.token.ownershipApproved == true;
    }

    match /settings/public {
      allow read;
    }

    match /stocks/{stockId} {
      allow read: if notAnonymous();
    }

    match /bonds/{bondId} {
      allow read: if notAnonymous();
    }

    match /users/{uid} {
      allow read, write: if signedIn(uid);

      match /device/token {
        allow read, write: if signedIn(uid)
      }

      match /accounts/{accountId=**} {
        allow read: if deviceApproved(uid);
        allow write: if deviceOwner(uid);
      }
    }

  }
}
```

One of the reads that fails. Note I am using RxSwift, but the listen is just a wrapper. This sometimes throws. 
```
func observeOutstandingTransferTotal(withUserKey userKey: String, andAccountKey accountKey: String) -> Observable<Double> {
    return Firestore.firestore()
        .collection("users").document(userKey)
        .collection("accounts").document(accountKey)
        .collection("current").document("pending")
        .rx.listen()
        .flatMapLatest({ (snapshot) -> Observable<Double> in
            guard let data = snapshot.data(),
                let total = data["total"] as? Double
                else { return Observable.just(0) }

            return Observable.just(total)
        })
        .catchError({ (error) -> Observable<Double> in
            throw TransferError.failedObservingPendingTransfer
        })
}
```

**Comment by stevejcox** [comment]
This morning the following path cannot be written to:

```
/databases/(default)/documents/users/f6F2Nd6aeubS0IYtb909RrBNj5B3/accounts/ce8213ac-15ea-4086-80be-d87c8855b1d9
```

Perhaps I am doing something wrong in the rules? I can't see anything and have confirmed the claims are correct.

**Comment by mikelehen** [comment]
The iOS client treats custom claims exactly the same as any other auth token so this is likely an issue with your rules. This probably isn't the best place for rules questions and without a more complete example (including all of the data that your rules depend on) it will probably be difficult for somebody to help you.  If you're still stuck, perhaps post on the [google-cloud-firsetore-discuss](https://groups.google.com/forum/#!forum/google-cloud-firestore-discuss) google group with a full example or as much detail as you can provide.  Thanks, and sorry I can't help you here!
