### ISSUE TITLE
Async/await violation for Dynamic Links

### ISSUE THREAD

**Issue by ryanwilson** [firebase/firebase-ios-sdk#9612]
If a dynamic link can't be parsed, the completion handler is called with `(nil, nil)` which crashes when used with async/await. It should be changed to an error.

https://github.com/firebase/firebase-ios-sdk/blob/d4fc906e787dff9f4b292c4099ded7794cc66188/FirebaseDynamicLinks/Sources/FIRDynamicLinks.m#L443

**Comment by ryanwilson** [comment]
This crashes:

```swift
class ViewController: UIViewController {
  override func viewDidLoad() {
    super.viewDidLoad()
    Task { await testing() }
  }

  func testing() async {
    do {
      let _ = try await DynamicLinks.dynamicLinks().dynamicLink(fromUniversalLink: URL(string: "https://www.google.com")!)
    } catch {
      // Do nothing.
    }
  }
}
```

**Comment by eldhosembabu** [comment]
Added a fix here : https://github.com/firebase/firebase-ios-sdk/pull/9637

**Comment by eldhosembabu** [comment]
Closing this issue since PR is merged.
