### ISSUE TITLE
Crash after remoteconfig cache expires 

### ISSUE THREAD

**Issue by danielCarlosCE** [firebase/firebase-ios-sdk#962]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.2
  * Firebase SDK version: Firebase/RemoteConfig (~> 4.0.0)
  * Firebase Component: Firebase/RemoteConfig (~> 4.0.0)
  * Component version: Firebase/RemoteConfig (~> 4.0.0)

### [REQUIRED] Step 3: Describe the problem
I'm tracking an issue in my app that is not reproducible by us. My current clue is that's the majority of users that face that issue had just had the firebase cache expired and is hitting the server again. This is the crash:
`-[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]` 
I checked that our local plist doesn't have all the keys that are in the server and there are even ones without values on them. My question is, can that be a problem somehow? I know it's not always a problem since I've reproduced the cache timeout locally and still didn't get any error. 

Thanks in advance

**Comment by morganchen12** [comment]
Can you post the full stack trace?

**Comment by danielCarlosCE** [comment]
This's all I have

Fatal Exception: NSInvalidArgumentException
*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]

0 | CoreFoundation | __exceptionPreprocess
-- | -- | --
1 | libobjc.A.dylib | objc_exception_throw
2 | CoreFoundation | _CFArgv
3 | CoreFoundation | -[__NSPlaceholderArray initWithObjects:count:]
13 | UIKit | UIApplicationMain

**Comment by morganchen12** [comment]
Can you share the codebase that this occurs in? There's no Firebase symbols here, so we want to rule out the possibility of an unrelated crash occurring at the same time.

**Comment by danielCarlosCE** [comment]
I actually can't, since I don't know exactly which point the app crashes. My intention here was just to know if there's any possibility that an incomplete local plist could  generate that kind of error.

**Comment by morganchen12** [comment]
It sounds unlikely, though I can't tell for sure. You could check your logic for any bugs when handling nil values returned by RemoteConfig, though this won't help if it's an issue within RemoteConfig.

It looks like there's 10 missing frames of the stack trace that you posted above. Is there no way for you to either obtain the full stack trace or reproduce the issue locally?
