### ISSUE TITLE
"GDTCORRegistrar appWillTerminate" marked as uiblock issue

### ISSUE THREAD

**Issue by liushong** [firebase/firebase-ios-sdk#9651]
- Xcode version: 12.2
- Firebase SDK version: 6.34.0
- Installation method: CocoaPods
- Firebase Component:
- pod 'Firebase/Analytics', '6.34.0'
- pod 'Firebase/Crashlytics', '6.34.0'
- pod 'Firebase/Performance', '6.34.0'

My app integrate the [bugly](https://bugly.qq.com/) for crash and uiblock detection.
I notice the "GDTCORRegistrar appWillTerminate" is marked as uiBlock issue for many times.
There are call-stack captured by the bugly

Same issue as [#7280](https://github.com/firebase/firebase-ios-sdk/issues/7280).

[Caton stack information is as follows](https://github.com/liushong/LLCategoryDemo/blob/master/94ed880a7ce8b86cd94473fd2481da9b.png?raw=true)

**Comment by paulb777** [comment]
Please answer the question that was asked in #7280. https://github.com/firebase/firebase-ios-sdk/issues/7280#issuecomment-758035433
