### ISSUE TITLE
Remote Config Fetch fails on iOS 

### ISSUE THREAD

**Issue by BaluNaik** [firebase/firebase-ios-sdk#9671]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a GitHub issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.1 (13A1030d)
  * Firebase SDK version: 8.13.0
  * Installation method: `CocoaPods` (select one)
  * Firebase Component: `Remote Config`
  * Target platform(s): `iOS`

#### Steps to reproduce:

Use of any of the Swift RemoteConfig fetch methods

* [fetch(completionHandler:)](https://firebase.google.com/docs/reference/swift/firebaseremoteconfig/api/reference/Classes/RemoteConfig#fetchcompletionhandler:)
* [fetch(withExpirationDuration:completionHandler:)](https://firebase.google.com/docs/reference/swift/firebaseremoteconfig/api/reference/Classes/RemoteConfig#fetchwithexpirationduration:completionhandler:)
* [fetchAndActivate(completionHandler:)](https://firebase.google.com/docs/reference/swift/firebaseremoteconfig/api/reference/Classes/RemoteConfig#fetchandactivatecompletionhandler:)

Now always returns an error in the completionHandler, and does NOT apply the Remote-Configs from the Firebase Server.

This is a print out of the error object of the completionHandler

`
Failed to get installations token. Error : Error Domain=com.firebase.installations Code=0 "Underlying error: اتصال البيانات غير مسموح به حاليًا." UserInfo={NSLocalizedFailureReason=Underlying error: اتصال البيانات غير مسموح به حاليًا., NSUnderlyingError=0x280b9ea90 {Error Domain=NSURLErrorDomain Code=-1020 "اتصال البيانات غير مسموح به حاليًا." UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x280b9fde0 {Error Domain=kCFErrorDomainCFNetwork Code=-1020 "(null)" UserInfo={_NSURLErrorNWPathKey=unsatisfied (No network route), _kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <26E9BE02-FF19-45A0-BE9D-DAC77E5E9F80>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=( "LocalDataTask <26E9BE02-FF19-45A0-BE9D-DAC77E5E9F80>.<1>" ), NSLocalizedDescription=اتصال البيانات غير مسموح به حاليًا., NSErrorFailingURLStringKey=https://firebaseinstallations.googleapis.com/v1/projects/xxxxxxx-xxxxx-prod/installations/eLG8mxJwhjg/authTokens:generate, NSErrorFailingU
`

#### Relevant Code:

```
        let remoteConfig : RemoteConfig = RemoteConfig.remoteConfig()
        let settings = RemoteConfigSettings()
        settings.minimumFetchInterval = 900
        settings.fetchTimeout = 10
        remoteConfig.configSettings = settings

        remoteConfig.fetchAndActivate(completionHandler: { status, error in
            if status == .error {
                NMSCrashlyticsLogger.sharedInstance.logNonFatalError(info: ["RemoteConfig": error?.localizedDescription ?? "No error available."])
            }
        })
```

**Comment by paulb777** [comment]
Translating `اتصال البيانات غير مسموح به حاليًا."` shows "Data connection is not currently allowed".

Please check the connection on the test device.

**Comment by arshedg** [comment]
```
RemoteConfig.remoteConfig().activate(completion: { change , error in
                    if let error = error {
                        print("Remote config ERROR ACTIVATE : \(error.localizedDescription) ")
                        listner?.onError(error: error)
                        return;
                    }
                    print("Remote config change : \(change)")
                    listner?.onSuccess(change: change)
                })
```
The completion handler is getting called only once (may be once per cache interval).
Earlier completion used to get called irrespective of cache interval.

**Comment by BaluNaik** [comment]
> Translating `اتصال البيانات غير مسموح به حاليًا."` shows "Data connection is not currently allowed".
> 
> Please check the connection on the test device.

@paulb777 Thanks for response. Let me check and get back on this.

**Comment by BaluNaik** [comment]
@paulb777 it seems a network glitch on app launch and its failing to load remote config. Now adding an additional condition to check? network is available or not along with status check. For now closing this and we will monitor our app in next release.
