### ISSUE TITLE
Null pointer deference which will cause app crashes if triggered

### ISSUE THREAD

**Issue by Eric-Catalyst** [firebase/firebase-ios-sdk#9672]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.3.1
  * Firebase SDK version: 8.15.0
  * Installation method: Swift Package Manager
  * Firebase Component: nanopb
  * Target platform(s): iOS |  macOS 

#### Steps to reproduce:

Add Firebase Analytics, Messaging, Crashlytics to project with Add Package.
From Project menu, Analyze project, null pointer deference will be reported in two locations

#### Relevant Code:

Source code from nanopb here. pItem can be null, which when referenced, will cause app crash.
```
static void initialize_pointer_field(void *pItem, pb_field_iter_t *iter)
{
    if (PB_LTYPE(iter->pos->type) == PB_LTYPE_STRING ||
        PB_LTYPE(iter->pos->type) == PB_LTYPE_BYTES)
    {
        *(void**)pItem = NULL;
    }
    else if (PB_LTYPE(iter->pos->type) == PB_LTYPE_SUBMESSAGE)
    {
        /* We memset to zero so that any callbacks are set to NULL.
         * Then set any default values. */
        memset(pItem, 0, iter->pos->data_size);
        pb_message_set_to_defaults((const pb_field_t *) iter->pos->ptr, pItem);
    }
}
```

Google has forked the nanopb project, but has not kept it current with the original project. Currently, Google is 130 commits behind the origin project, which has already fixed this issue. Recommend either keeping the fork current or replacing the reference to the fork with a reference to the original project.

Screen shots:
![Screen Shot 2022-04-12 at 5 08 40 PM](https://user-images.githubusercontent.com/98613724/164250762-90341fff-ed64-47cf-a8d9-9a1d0d92bced.png)

**Comment by paulb777** [comment]
Sorry about the trouble. Firebase has avoided forking nanopb and is at the latest nanopb 0.3 release.  The fix is waiting for nanopb to do update a tag. See https://github.com/nanopb/nanopb/issues/667.

The Firebase tracking issue is at #9587

**Comment by Eric-Catalyst** [comment]
Check again, I just added the package with Swift Package Manager. You are clearly pulling this from your own fork.

**Comment by Eric-Catalyst** [comment]
From package file:
    .package(
      name: "nanopb",
      url: "https://github.com/firebase/nanopb.git",
      "2.30908.0" ..< "2.30909.0"
    ),

**Comment by paulb777** [comment]
Yes, sorry for the confusion. I missed that you were using Swift Package Manager. We have a fork for Swift Package Manager in order to provide semantic versioning support. However, we don't change any code and the latest release matches. 2.030908.0 maps directly to 0.3.9.8 in the unforked repo. See https://github.com/firebase/nanopb/releases/tag/2.30908.0.  As soon as there is a 0.3.9.9, we'll update the fork and update Firebase to that.

**Comment by Eric-Catalyst** [comment]
When I look at your fork, it reports you are 130 commits behind the origin. You are in no way up-to-date. The issue reported in this ticket has been resolved in the origin repo.

**Comment by paulb777** [comment]
See https://github.com/nanopb/nanopb/tags. nanopb releases both 0.3 and 0.4 streams. Google and Firebase are on the latest 0.3 release.

The nanopb is resolved but not yet released. See the discussion on https://github.com/nanopb/nanopb/issues/667.

**Comment by Eric-Catalyst** [comment]
> See https://github.com/nanopb/nanopb/tags. nanopb releases both 0.3 and 0.4 streams. Google and Firebase are on the latest 0.3 release.
> 
> The nanopb is resolved but not yet released. See the discussion on [nanopb/nanopb#667](https://github.com/nanopb/nanopb/issues/667).

So you are going to stay on a known bad release when a fixed version is available? I read the discussion on the referenced issue, and it is clear the package author thinks this issue will not occur in the field. Unfortunately, he is wrong in that assumption.

**Comment by Eric-Catalyst** [comment]
nanopb has been updated to 0.3.9.9, google needs to pull and update the local clone at this point to resolve the issue.
