### ISSUE TITLE
Package.swift references out of date nanopb, causing app crashes

### ISSUE THREAD

**Issue by Eric-Catalyst** [firebase/firebase-ios-sdk#9674]
### [REQUIRED] Step 1: Describe your environment

Xcode version: 13.3.1
Firebase SDK version: 8.15.0
Installation method: Swift Package Manager
Firebase Component: nanopb
Target platform(s): iOS | macOS

#### Steps to reproduce:

Add Firebase Analytics, Messaging, Crashlytics to project with Add Package.
From Project menu, Analyze project, null pointer deference will be reported in two locations due to package file referencing out of date local fork of nanopb rather than origin project which has resolved the issue

#### Relevant Code:

```
    .package(
      name: "nanopb",
      url: "https://github.com/firebase/nanopb.git",
      "2.30908.0" ..< "2.30909.0"
    ),
```

Note, original issue report https://github.com/firebase/firebase-ios-sdk/issues/9672 was closed incorrectly due to misunderstanding of what projects Google is using in Firebase by Google engineer.

**Comment by paulb777** [comment]
See discussion at #9672
