### ISSUE TITLE
Completion handler of firebase remote config activate is getting called only once

### ISSUE THREAD

**Issue by arshedg** [firebase/firebase-ios-sdk#9676]
```
RemoteConfig.remoteConfig().activate(completion: { change , error in
                    if let error = error {
                        print("Remote config ERROR ACTIVATE : \(error.localizedDescription) ")
                        listner?.onError(error: error)
                        return;
                    }
                    print("Remote config change : \(change)")
                    listner?.onSuccess(change: change)
                })
```
The completion handler is getting called only once. Subsequent calls to activate the method is not triggering the completion.
Earlier completion used to get called any number of times

The issue is reproducible in all ios versions with remoteconfig version '7.11.0'
The issue started occurring by around 20th April,4 PM Indian time.

**Comment by rizafran** [comment]
Thanks for reporting, @arshedg. I tried reproducing the issue, but the `remoteConfig().activate` completion handler was being called multiple times. Could you confirm if you have followed the steps on the [docs](https://firebase.google.com/docs/remote-config/get-started?platform=ios#fetch-and-activate-values_3) by calling the `remoteConfig().fetch` before the `remoteConfig().activate` completion handler? If so, are you seeing any logs after calling the `remoteConfig().fetch`?

**Comment by arshedg** [comment]
Yes, we are using the same code from the docs. 
The live app is updated months ago and was running fine till today afternoon.
I guess some changes at the remote config backend broke it.
Did you check with the version '7.11.0' ?

**Comment by rizafran** [comment]
Thanks for the info, @arshedg. Yes, I tried using version 7.11.0 and the [latest one](https://firebase.google.com/support/release-notes/ios#version_8150_-_april_12_2022) but I'm unable to reproduce the issue.

**Comment by arshedg** [comment]
```
  private func fetchRC(listner:RCListners?){
        print("Remote config fetch")
        RemoteConfig.remoteConfig().fetch() { status , error in
            if status == .success {
                RemoteConfig.remoteConfig().activate(completion: { change , error in
                    if let error = error {
                        print("Remote config ERROR ACTIVATE : \(error.localizedDescription) ")
                        listner?.onError(error: error)
                        return;
                    }
                    print("Remote config change : \(change)")
                    listner?.onSuccess(change: change)
                })
            } else {
                if let error = error {
                    print("Remote config ERROR FETCH : \(error.localizedDescription) ")
                    listner?.onError(error: error)
                }
            }
            self.callNext()
        }
    }
```
This is our complete code. The completion handler of activate is not getting called only once, not on subsequent calls

**Comment by arshedg** [comment]
This issue is occurring due to the overflow of the dispatch queue in the client app.
Closing the ticket.
