### ISSUE TITLE
Firebase not configuring

### ISSUE THREAD

**Issue by Mcrich23** [firebase/firebase-ios-sdk#9687]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.3.1
  * Firebase SDK version: 18.15.0
  * Installation method: `Swift Package Manager` (select one)
  * Firebase Component: Firebase (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Target platform(s): `iOS`

### [REQUIRED] Step 2: Describe the problem
Every time I launch my app, I call `FirebaseApp.configure()` and I have the plist in my project, and then this happens:
```
Thread 1: "Failed to get FirebaseApp instance. Please call FirebaseApp.configure() before using Firestore"
```
#### Steps to reproduce:

What happened? How can we make the problem occur?

1. Update to new version
2. Run FirebaseApp.config() in delegate for a SwiftUI app

#### Relevant Code:

```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        FirebaseApp.configure()
        return true
}
```

**Comment by rizafran** [comment]
Hi @Mcrich23, it seems like you need to call the `Firestore.firestore()` after the `FirebaseApp.configure()` based on the [docs](https://firebase.google.com/docs/firestore/quickstart#initialize). You may check the response [here](https://github.com/firebase/firebase-ios-sdk/issues/3032#issuecomment-493697008) for more info.

**Comment by Mcrich23** [comment]
Right! However, I call it in the correct place, and it still fails.

**Comment by rizafran** [comment]
@Mcrich23, I tried to reproduce the issue, but I'm unable to get the same error. It's possible that you're getting the error because of calling Firebase code first before calling the [FirebaseApp.configure()](https://firebase.google.com/docs/reference/swift/firebasecore/api/reference/Classes/FirebaseApp#configure). Could you share how you integrate Firebase?

**Comment by morganchen12** [comment]
@Mcrich23, do you have warnings of duplicate class definitions in console when your app is running? They should be at the very top of the console logs.

**Comment by Mcrich23** [comment]
I don't unfortunately, I have no clue whats going on.

**Comment by Mcrich23** [comment]
Update: Turns out I was being stupid and accidentally was referencing firebase on init of AppDelegate

**Comment by paulb777** [comment]
That would do it. Thanks for the follow up.
