### ISSUE TITLE
App Getting Crash on Startup in appDidFinishLaunchingOptions

### ISSUE THREAD

**Issue by hcpabbathi** [firebase/firebase-ios-sdk#9697]
App Getting Crash on StartUp in iOS 15.3.1 devices

Reproduce Steps:
1.App Launches for the first time perfectly
2.on Second time launch app and Quickly quit the app and relaunch immediately will see the issue. 

Xcode 13.2.1
iOS 15.3.1 devices
Firebase Pod Version: 8.11.0

*** Terminating app due to uncaught exception 'com.firebase.perf', reason: 'The default Firebase app has not yet been configured. Add [FirebaseApp configure] to your application initialization.'
*** First throw call stack:
(0x1808f10fc 0x199141d64 0x180948230 0x1071caa54 0x1045fe524 0x104400158 0x1043d4c98 0x1043d67cc 0x182eae620 0x182eb10d4 0x182fb142c 0x182fad9f4 0x1831da424 0x1830af3c0 0x182fd5994 0x182e8e474 0x1845f1794 0x182ef2a1c 0x1044c1910 0x1044c140c 0x1044c1468 0x182eae620 0x182eb10d4 0x182e83bf0 0x183216320 0x1832c5bc0 0x18302998c 0x183211a60 0x1831fa3a0 0x183057940 0x182eafaf0 0x182fdb438 0x1830fc104 0x18333d2f8 0x1832c8818 0x182eb08f4 0x182f71160 0x182eb2804 0x182f9d448 0x1834255cc 0x182ee113c 0x182f24a50 0x18305c86c 0x182f9b708 0x1925588d4 0x19257e824 0x19253906c 0x19253a6ac 0x180563670 0x180567128 0x19253a9c4 0x192539d8c 0x19253e414 0x1809130d0 0x180923d90 0x18085e098 0x1808638a4 0x180877468 0x19c41b38c 0x18321a5d0 0x182f98f74 0x19815cfa0 0x104099a3c 0x105b0daa4)

**Comment by rizafran** [comment]
Thanks for reporting, @hcpabbathi. Looks like it's caused by Firebase SDK symbols being included twice in you app binary. Could you check if you're seeing the warning message similar [here](https://github.com/firebase/firebase-ios-sdk/blob/master/docs/firebase_in_libraries.md#using-firebase-sdks-from-dynamic-frameworks) in your console?
