### ISSUE TITLE
MLDownloader doesn't support TensorFlowLiteSwift

### ISSUE THREAD

**Issue by connermccraw** [firebase/firebase-ios-sdk#9698]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a GitHub issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.3.1
  * Firebase SDK version: 8.10
  * Installation method:  Swift Package Manager
  * Firebase Component: Machine Learning
  * Target platform(s): iOS

#### Steps to reproduce:

What happened? How can we make the problem occur?

Install Firebase-ios-sdk with SPM. In swift file, "import TensorFlowLite".  Does not recognize module. 

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
import FirebaseMLModelDownloader
import TensorFlowLite

**Comment by rizafran** [comment]
Thanks for reporting this, @connermccraw. It seems that the module was not being recognized because [`FirebaseMLModelDownloader` doesn't depend](https://github.com/firebase/firebase-ios-sdk/blob/master/Package.swift#L872-L878) on `TensorFlowLite`. With this, you need to install the `TensorFlowLiteSwift` via pods since it's [currently not available in SPM](https://github.com/tensorflow/tensorflow/issues/44609).
