### ISSUE TITLE
iOS app crashing at GULMutableDictionary

### ISSUE THREAD

**Issue by KrishanDew** [firebase/firebase-ios-sdk#9701]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a GitHub issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.2.1
  * Firebase SDK version:  8.4.0
  * Installation method: `CocoaPods | Carthage | Zip file | Swift Package Manager` (select one)
  * Firebase Component: Messaging,DynamicLinks,Installations,Crashlytics (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Target platform(s): `iOS `

#### Steps to reproduce:

This was produced for live users of my app.

#### Relevant Code:
```
Crashed: GULMutableDictionary
0  MyApp                         0x1f928c -[APMPBFlag dealloc] + 1 (MyApp:1)
1  CoreFoundation                 0x44ff4 cow_cleanup + 172
2  CoreFoundation                 0xd55c -[__NSDictionaryM dealloc] + 148
3  libobjc.A.dylib                0x82f0 object_cxxDestructFromClass(objc_object*, objc_class*) + 116
4  libobjc.A.dylib                0x5144 objc_destructInstance + 80
5  libobjc.A.dylib                0xe9b4 _objc_rootDealloc + 80
6  libobjc.A.dylib                0x82f0 object_cxxDestructFromClass(objc_object*, objc_class*) + 116
7  libobjc.A.dylib                0x5144 objc_destructInstance + 80
8  libobjc.A.dylib                0xe9b4 _objc_rootDealloc + 80
9  CoreFoundation                 0x44ff4 cow_cleanup + 172
10 CoreFoundation                 0xd544 -[__NSDictionaryM dealloc] + 124
11 libobjc.A.dylib                0x82f0 object_cxxDestructFromClass(objc_object*, objc_class*) + 116
12 libobjc.A.dylib                0x5144 objc_destructInstance + 80
13 libobjc.A.dylib                0xe9b4 _objc_rootDealloc + 80
14 libobjc.A.dylib                0x82f0 object_cxxDestructFromClass(objc_object*, objc_class*) + 116
15 libobjc.A.dylib                0x5144 objc_destructInstance + 80
16 libobjc.A.dylib                0xe9b4 _objc_rootDealloc + 80
17 libdispatch.dylib              0x1e68 _dispatch_call_block_and_release + 32
18 libdispatch.dylib              0x3a2c _dispatch_client_callout + 20
19 libdispatch.dylib              0xb124 _dispatch_lane_serial_drain + 668
20 libdispatch.dylib              0xbc80 _dispatch_lane_invoke + 392
21 libdispatch.dylib              0x16500 _dispatch_workloop_worker_thread + 648
22 libsystem_pthread.dylib        0x10bc _pthread_wqthread + 288
23 libsystem_pthread.dylib        0xe5c start_wqthread + 8


com.apple.main-thread
0  libsystem_kernel.dylib         0x14e0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b24 mach_msg + 76
2  CoreFoundation                 0x7820 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xbcac __CFRunLoopRun + 1180
4  CoreFoundation                 0x1f6b8 CFRunLoopRunSpecific + 600
5  GraphicsServices               0x1374 GSEventRunModal + 164
6  UIKitCore                      0x513e88 -[UIApplication _run] + 1100
7  UIKitCore                      0x2955ec UIApplicationMain + 364
8  MyApp                         0x29a3bb8 main + 39 (AppDelegate.swift:39)
9  ???                            0x10ab1dce4 (Missing)
```

**Comment by rizafran** [comment]
Thanks for filing this, @KrishanDew. Is the issue reproducible on your end? If so, could you provide the steps to reproduce? Also, could you provide a full symbolicated stack trace of the issue?

**Comment by KrishanDew** [comment]
Hi @rizafran Thanks for quick reply. This issue was generated at live app end user so I don't know actual steps to reproduce.
I am pasting whole stracktrace of firebase analytics here.

Crashed: GULMutableDictionary
0  TCPApp                         0x1f928c -[APMPBFlag dealloc] + 1 (TCPApp:1)
1  CoreFoundation                 0x44ff4 cow_cleanup + 172
2  CoreFoundation                 0xd55c -[__NSDictionaryM dealloc] + 148
3  libobjc.A.dylib                0x82f0 object_cxxDestructFromClass(objc_object*, objc_class*) + 116
4  libobjc.A.dylib                0x5144 objc_destructInstance + 80
5  libobjc.A.dylib                0xe9b4 _objc_rootDealloc + 80
6  libobjc.A.dylib                0x82f0 object_cxxDestructFromClass(objc_object*, objc_class*) + 116
7  libobjc.A.dylib                0x5144 objc_destructInstance + 80
8  libobjc.A.dylib                0xe9b4 _objc_rootDealloc + 80
9  CoreFoundation                 0x44ff4 cow_cleanup + 172
10 CoreFoundation                 0xd544 -[__NSDictionaryM dealloc] + 124
11 libobjc.A.dylib                0x82f0 object_cxxDestructFromClass(objc_object*, objc_class*) + 116
12 libobjc.A.dylib                0x5144 objc_destructInstance + 80
13 libobjc.A.dylib                0xe9b4 _objc_rootDealloc + 80
14 libobjc.A.dylib                0x82f0 object_cxxDestructFromClass(objc_object*, objc_class*) + 116
15 libobjc.A.dylib                0x5144 objc_destructInstance + 80
16 libobjc.A.dylib                0xe9b4 _objc_rootDealloc + 80
17 libdispatch.dylib              0x1e68 _dispatch_call_block_and_release + 32
18 libdispatch.dylib              0x3a2c _dispatch_client_callout + 20
19 libdispatch.dylib              0xb124 _dispatch_lane_serial_drain + 668
20 libdispatch.dylib              0xbc80 _dispatch_lane_invoke + 392
21 libdispatch.dylib              0x16500 _dispatch_workloop_worker_thread + 648
22 libsystem_pthread.dylib        0x10bc _pthread_wqthread + 288
23 libsystem_pthread.dylib        0xe5c start_wqthread + 8


com.apple.main-thread
0  libsystem_kernel.dylib         0x14e0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b24 mach_msg + 76
2  CoreFoundation                 0x7820 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xbcac __CFRunLoopRun + 1180
4  CoreFoundation                 0x1f6b8 CFRunLoopRunSpecific + 600
5  GraphicsServices               0x1374 GSEventRunModal + 164
6  UIKitCore                      0x513e88 -[UIApplication _run] + 1100
7  UIKitCore                      0x2955ec UIApplicationMain + 364
8  TCPApp                         0x29a3bb8 main + 39 (AppDelegate.swift:39)
9  ???                            0x10ab1dce4 (Missing)



com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x14e0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b24 mach_msg + 76
2  CoreFoundation                 0x7820 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xbcac __CFRunLoopRun + 1180
4  CoreFoundation                 0x1f6b8 CFRunLoopRunSpecific + 600
5  Foundation                     0x18414 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236
6  Foundation                     0x59cac -[NSRunLoop(NSRunLoop) runUntilDate:] + 92
7  UIKitCore                      0x48dfb0 -[UIEventFetcher threadMain] + 524
8  Foundation                     0x6855c __NSThread__start__ + 808
9  libsystem_pthread.dylib        0x19ac _pthread_start + 148
10 libsystem_pthread.dylib        0xe68 thread_start + 8



Thread
0  libsystem_kernel.dylib         0x1f64 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8298 _pthread_cond_wait + 1236
2  libc++.1.dylib                 0xd2d4 std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 100
3  TCPApp                         0x18e1fbc std::__1::__function::__func<AdobeMarketingMobile::Timer::StartTimerThread()::$_0, std::__1::allocator<AdobeMarketingMobile::Timer::StartTimerThread()::$_0>, void ()>::operator()() + 1 (TCPApp:1)
4  TCPApp                         0x18a3620 AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&)
5  TCPApp                         0x18dee50 std::__1::__function::__func<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2::operator()() const::'lambda0'(), std::__1::allocator<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2::operator()() const::'lambda0'()>, void ()>::operator()()
6  TCPApp                         0x18a3620 AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&)
7  TCPApp                         0x18d0a3c AdobeMarketingMobile::TrySwallow(std::__1::function<void ()> const&)
8  TCPApp                         0x18de518 std::__1::__function::__func<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2, std::__1::allocator<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2>, void ()>::operator()() + 1 (TCPApp:1)
9  TCPApp                         0x18a3620 AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&)
10 TCPApp                         0x18d0a3c AdobeMarketingMobile::TrySwallow(std::__1::function<void ()> const&)
11 TCPApp                         0x18dd4fc void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, AdobeMarketingMobile::CreateWorkerThread(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&)::$_1> >(void*) + 1 (TCPApp:1)
12 libsystem_pthread.dylib        0x19ac _pthread_start + 148
13 libsystem_pthread.dylib        0xe68 thread_start + 8


com.google.firebase.crashlytics.MachExceptionServer
0  FirebaseCrashlytics            0xd5b4 FIRCLSProcessRecordAllThreads + 393 (FIRCLSProcess.c:393)
1  FirebaseCrashlytics            0xd994 FIRCLSProcessRecordAllThreads + 424 (FIRCLSProcess.c:424)
2  FirebaseCrashlytics            0xd340 FIRCLSHandler + 34 (FIRCLSHandler.m:34)
3  FirebaseCrashlytics            0x231fc FIRCLSMachExceptionServer + 524 (FIRCLSMachException.c:524)
4  libsystem_pthread.dylib        0x19ac _pthread_start + 148
5  libsystem_pthread.dylib        0xe68 thread_start + 8

com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x14e0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b24 mach_msg + 76
2  CoreFoundation                 0x7820 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xbcac __CFRunLoopRun + 1180
4  CoreFoundation                 0x1f6b8 CFRunLoopRunSpecific + 600
5  CFNetwork                      0x2774d8 _CFURLStorageSessionDisableCache + 59988
6  Foundation                     0x6855c __NSThread__start__ + 808
7  libsystem_pthread.dylib        0x19ac _pthread_start + 148
8  libsystem_pthread.dylib        0xe68 thread_start + 8



APMEExperimentSerialQueue
0  libsystem_kernel.dylib         0x1bdc kevent_id + 8
1  libdispatch.dylib              0x261fc _dispatch_kq_poll + 228
2  libdispatch.dylib              0x26c20 _dispatch_event_loop_wait_for_ownership + 444
3  libdispatch.dylib              0x12f54 __DISPATCH_WAIT_FOR_QUEUE__ + 328
4  libdispatch.dylib              0x12b28 _dispatch_sync_f_slow + 144
5  GoogleUtilities                0xf3c8 -[GULMutableDictionary objectForKeyedSubscript:] + 84 (GULMutableDictionary.m:84)
6  TCPApp                         0x279528 __44-[APMEManager flagValueForFlagName:SDKName:]_block_invoke
7  TCPApp                         0x27765c __41-[APMEManager dispatchSyncOnSerialQueue:]_block_invoke
8  libdispatch.dylib              0x3a2c _dispatch_client_callout + 20
9  libdispatch.dylib              0x12c90 _dispatch_lane_barrier_sync_invoke_and_complete + 56
10 TCPApp                         0x277590 -[APMEManager dispatchSyncOnSerialQueue:]
11 TCPApp                         0x275a08 -[APMEManager flagValueForFlagName:SDKName:]
12 TCPApp                         0x280f50 -[APMEClient objectForKeyedSubscript:]
13 TCPApp                         0x184c6c -[APMRemoteConfig currentRandomGeneratorStudyEnabledFlag] + 1 (TCPApp:1)
14 TCPApp                         0x181f54 -[APMRemoteConfig activateNewSnapshot] + 1 (TCPApp:1)
15 TCPApp                         0x226a3c -[APMMeasurement uploadData]
16 TCPApp                         0x230b18 __49-[APMMeasurement handleAppWillResignActiveEvent:]_block_invoke_3
17 TCPApp                         0x180e0c __51-[APMScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke + 1 (TCPApp:1)
18 libdispatch.dylib              0x1e68 _dispatch_call_block_and_release + 32
19 libdispatch.dylib              0x3a2c _dispatch_client_callout + 20
20 libdispatch.dylib              0xb124 _dispatch_lane_serial_drain + 668
21 libdispatch.dylib              0xbc80 _dispatch_lane_invoke + 392
22 libdispatch.dylib              0x16500 _dispatch_workloop_worker_thread + 648
23 libsystem_pthread.dylib        0x10bc _pthread_wqthread + 288
24 libsystem_pthread.dylib        0xe5c start_wqthread + 8


Thread
0  libsystem_kernel.dylib         0x1f64 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8298 _pthread_cond_wait + 1236
2  libc++.1.dylib                 0xd2d4 std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 100
3  TCPApp                         0x18d9608 std::__1::cv_status std::__1::condition_variable::wait_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&)
4  TCPApp                         0x18de48c std::__1::__function::__func<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2, std::__1::allocator<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2>, void ()>::operator()() + 1 (TCPApp:1)
5  TCPApp                         0x18a3620 AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&)
6  TCPApp                         0x18d0a3c AdobeMarketingMobile::TrySwallow(std::__1::function<void ()> const&)
7  TCPApp                         0x18dd4fc void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, AdobeMarketingMobile::CreateWorkerThread(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&)::$_1> >(void*) + 1 (TCPApp:1)
8  libsystem_pthread.dylib        0x19ac _pthread_start + 148
9  libsystem_pthread.dylib        0xe68 thread_start + 8


Thread
0  libsystem_kernel.dylib         0x1f64 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8298 _pthread_cond_wait + 1236
2  libc++.1.dylib                 0xd2d4 std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 100
3  TCPApp                         0x18d9608 std::__1::cv_status std::__1::condition_variable::wait_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&)
4  TCPApp                         0x18de48c std::__1::__function::__func<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2, std::__1::allocator<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2>, void ()>::operator()() + 1 (TCPApp:1)
5  TCPApp                         0x18a3620 AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&)
6  TCPApp                         0x18d0a3c AdobeMarketingMobile::TrySwallow(std::__1::function<void ()> const&)
7  TCPApp                         0x18dd4fc void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, AdobeMarketingMobile::CreateWorkerThread(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&)::$_1> >(void*) + 1 (TCPApp:1)
8  libsystem_pthread.dylib        0x19ac _pthread_start + 148
9  libsystem_pthread.dylib        0xe68 thread_start + 8



Thread
0  libsystem_kernel.dylib         0x1f64 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8298 _pthread_cond_wait + 1236
2  libc++.1.dylib                 0xd2d4 std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 100
3  TCPApp                         0x18d9608 std::__1::cv_status std::__1::condition_variable::wait_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&)
4  TCPApp                         0x18de48c std::__1::__function::__func<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2, std::__1::allocator<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2>, void ()>::operator()() + 1 (TCPApp:1)
5  TCPApp                         0x18a3620 AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&)
6  TCPApp                         0x18d0a3c AdobeMarketingMobile::TrySwallow(std::__1::function<void ()> const&)
7  TCPApp                         0x18dd4fc void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, AdobeMarketingMobile::CreateWorkerThread(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&)::$_1> >(void*) + 1 (TCPApp:1)
8  libsystem_pthread.dylib        0x19ac _pthread_start + 148
9  libsystem_pthread.dylib        0xe68 thread_start + 8


Thread
0  libsystem_kernel.dylib         0x1f64 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8298 _pthread_cond_wait + 1236
2  libc++.1.dylib                 0xd2d4 std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 100
3  TCPApp                         0x18d9608 std::__1::cv_status std::__1::condition_variable::wait_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&)
4  TCPApp                         0x18de48c std::__1::__function::__func<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2, std::__1::allocator<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2>, void ()>::operator()() + 1 (TCPApp:1)
5  TCPApp                         0x18a3620 AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&)
6  TCPApp                         0x18d0a3c AdobeMarketingMobile::TrySwallow(std::__1::function<void ()> const&)
7  TCPApp                         0x18dd4fc void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, AdobeMarketingMobile::CreateWorkerThread(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&)::$_1> >(void*) + 1 (TCPApp:1)
8  libsystem_pthread.dylib        0x19ac _pthread_start + 148
9  libsystem_pthread.dylib        0xe68 thread_start + 8


Thread
0  libsystem_kernel.dylib         0x1f64 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8298 _pthread_cond_wait + 1236
2  libc++.1.dylib                 0xd2d4 std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 100
3  TCPApp                         0x18d9608 std::__1::cv_status std::__1::condition_variable::wait_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&)
4  TCPApp                         0x18de48c std::__1::__function::__func<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2, std::__1::allocator<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2>, void ()>::operator()() + 1 (TCPApp:1)
5  TCPApp                         0x18a3620 AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&)
6  TCPApp                         0x18d0a3c AdobeMarketingMobile::TrySwallow(std::__1::function<void ()> const&)
7  TCPApp                         0x18dd4fc void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, AdobeMarketingMobile::CreateWorkerThread(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&)::$_1> >(void*) + 1 (TCPApp:1)
8  libsystem_pthread.dylib        0x19ac _pthread_start + 148
9  libsystem_pthread.dylib        0xe68 thread_start + 8


Thread
0  libsystem_kernel.dylib         0x1f64 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8298 _pthread_cond_wait + 1236
2  libc++.1.dylib                 0xd2d4 std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 100
3  TCPApp                         0x18d9608 std::__1::cv_status std::__1::condition_variable::wait_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&)
4  TCPApp                         0x18de48c std::__1::__function::__func<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2, std::__1::allocator<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2>, void ()>::operator()() + 1 (TCPApp:1)
5  TCPApp                         0x18a3620 AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&)
6  TCPApp                         0x18d0a3c AdobeMarketingMobile::TrySwallow(std::__1::function<void ()> const&)
7  TCPApp                         0x18dd4fc void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, AdobeMarketingMobile::CreateWorkerThread(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&)::$_1> >(void*) + 1 (TCPApp:1)
8  libsystem_pthread.dylib        0x19ac _pthread_start + 148
9  libsystem_pthread.dylib        0xe68 thread_start + 8


Thread
0  libsystem_kernel.dylib         0x1f64 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8298 _pthread_cond_wait + 1236
2  libc++.1.dylib                 0xd2d4 std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 100
3  TCPApp                         0x18d9608 std::__1::cv_status std::__1::condition_variable::wait_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&)
4  TCPApp                         0x18de48c std::__1::__function::__func<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2, std::__1::allocator<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2>, void ()>::operator()() + 1 (TCPApp:1)
5  TCPApp                         0x18a3620 AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&)
6  TCPApp                         0x18d0a3c AdobeMarketingMobile::TrySwallow(std::__1::function<void ()> const&)
7  TCPApp                         0x18dd4fc void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, AdobeMarketingMobile::CreateWorkerThread(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&)::$_1> >(void*) + 1 (TCPApp:1)
8  libsystem_pthread.dylib        0x19ac _pthread_start + 148
9  libsystem_pthread.dylib        0xe68 thread_start + 8

**Comment by morganchen12** [comment]
The `dealloc` method this is crashing in has not changed for a while and simply checks if a buffer is nonnull, and if so, frees it. This usually indicates some kind of memory corruption is happening--likely the buffer being freed is a bad pointer. Unfortunately, without repro steps we won't be able to make much progress on this crash. Can you try to reproduce the crash with memory diagnostics enabled?

**Comment by KrishanDew** [comment]
> The `dealloc` method this is crashing in has not changed for a while and simply checks if a buffer is nonnull, and if so, frees it. This usually indicates some kind of memory corruption is happening--likely the buffer being freed is a bad pointer. Unfortunately, without repro steps we won't be able to make much progress on this crash. Can you try to reproduce the crash with memory diagnostics enabled?
As I told earlier this issue happens to live app user. So repro steps I don't know.

**Comment by morganchen12** [comment]
Can you try updating your version of Firebase and seeing if your production crashes still occur?

**Comment by mculha** [comment]
I am facing same issue. Any Progress?

**Comment by KrishanDew** [comment]
Hi @mculha  Do you have steps to reproduce it?
