### ISSUE TITLE
[BoringSSL] Function boringssl_context_get_peer_sct_list: line 1754 received sct extension length is less than sct data length

### ISSUE THREAD

**Issue by meaning-matters** [firebase/firebase-ios-sdk#971]
I have the exact same issue as #314 

Xcode 9.2, deployment target iOS 11.0 in a new project. I just call `FirebaseApp.configure()` in `AppDelegate` and have no messaging (yet).

Using Firebase (4.11.0)
Using FirebaseAnalytics (4.1.0)
Using FirebaseCore (4.0.18)
Using FirebaseInstanceID (2.0.10)
Using GoogleToolboxForMac (2.1.3)
Using nanopb (0.3.8)

**Comment by paulb777** [comment]
Closing due to lack of recent activity. Please open a new issue if this is occurring on Firebase 5.x.
