### ISSUE TITLE
Crashed: com.google.fira.worker

### ISSUE THREAD

**Issue by b3think3r** [firebase/firebase-ios-sdk#9710]
iOS 15.3.1
iPhone 11
SDK Version 7.8.0

Crashed: com.google.fira.worker
0  Porte                          0xbf0c88 -[APMEvent shouldValidateParams] + 112
1  Porte                          0xbf0ac8 -[APMEvent initWithOrigin:isPublic:name:timestamp:previousTimestamp:parameters:] + 576
2  Porte                          0xc15c50 -[APMMeasurement logEventOnWorkerQueueWithOrigin:isPublicEvent:name:parameters:timestamp:enabled:ignoreEnabled:ignoreInterceptor:interceptor:addedScreenParameters:] + 240
3  Porte                          0xc15b00 __151-[APMMeasurement logEventWithOrigin:isPublicEvent:name:parameters:timestamp:enabled:ignoreEnabled:ignoreInterceptor:interceptor:addedScreenParameters:]_block_invoke + 68
4  Porte                          0xc3cb94 __51-[APMScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke + 44
5  libdispatch.dylib              0x2924 _dispatch_call_block_and_release + 32
6  libdispatch.dylib              0x4670 _dispatch_client_callout + 20
7  libdispatch.dylib              0xbdf4 _dispatch_lane_serial_drain + 672
8  libdispatch.dylib              0xc968 _dispatch_lane_invoke + 392
9  libdispatch.dylib              0x171b8 _dispatch_workloop_worker_thread + 656
10 libsystem_pthread.dylib        0x10f4 _pthread_wqthread + 288
11 libsystem_pthread.dylib        0xe94 start_wqthread + 8

**Comment by rizafran** [comment]
Hi @b3think3r, could you provide the steps to reproduce the issue? Also, is the issue reproducible on a newer SDK version? If so, can you share the details about other threads during the crash?

**Comment by morganchen12** [comment]
There's not enough information in this stack trace to diagnose the crash accurately, and it may have been fixed on a newer version of Firebase. Can you try upgrading to the latest version and if the crash persists providing more information? A full stack trace will all threads and the crash message, if not full repro steps, would be helpful.
