### ISSUE TITLE
Firebase Auth error generating ID Token

### ISSUE THREAD

**Issue by JoeToeniskoetter** [firebase/firebase-ios-sdk#9713]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.3.1 
  * Firebase SDK version: 8.0.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: Auth
  * Target platform(s): `iOS`

### [REQUIRED] Step 2: Describe the problem

when calling `Auth.auth().currentUser?.getIDToken` throws the following error on my real iOS device only. This error does not occur when running with the iOS simulator. 

This error also only occurs with the GoogleService-Info.plist generated from my project with bundle id `com.joetoeniskoetter.ag-market-news` if I create a new bundle id in Firebase, generate a new plist file, and rebuild on my real device, everything functions correctly. 

```
GTMSessionFetcher invoking fetch callbacks, data {length = 111, bytes = 0x7b0a2020 22657272 6f72223a 207b0a20 ... 220a2020 7d0a7d0a }, error Error Domain=com.google.HTTPStatus Code=400 "(null)" UserInfo={data={length = 111, bytes = 0x7b0a2020 22657272 6f72223a 207b0a20 ... 220a2020 7d0a7d0a }, data_content_type=application/json; charset=UTF-8}
Optional("An internal error has occurred, print and inspect the error details for more information.")
GTMSessionFetcher invoking fetch callbacks, data {length = 111, bytes = 0x7b0a2020 22657272 6f72223a 207b0a20 ... 220a2020 7d0a7d0a }, error Error Domain=com.google.HTTPStatus Code=400 "(null)" UserInfo={data={length = 111, bytes = 0x7b0a2020 22657272 6f72223a 207b0a20 ... 220a2020 7d0a7d0a }, data_content_type=application/json; charset=UTF-8}
``` 

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

I'm not sure this will be reproducible on other devices as this seems to be device specific. 

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

I will not be able to provider a reproducible example since this seems to be specific to my device and info.plist file which is sensitive information.

**Comment by morganchen12** [comment]
Does redownloading the GoogleService-Info.plist for your app with the problematic bundle id from Firebase also reproduce the issue?

**Comment by JoeToeniskoetter** [comment]
@morganchen12 yes, unfortunately the problem remains after re-downloading.  This issue seems to be exclusively on my personal device. Running the app from test flight on my wife's iPhone does not reproduce the issue.

**Comment by morganchen12** [comment]
Ah, that's not great. A couple thoughts:
- Enabling debug logs on both devices may give us a hint on what's going wrong.
- More directly, the error you're getting is an HTTP 400 error, so proxying both devices and inspecting the outgoing request may also provide some clues.

**Comment by JoeToeniskoetter** [comment]
@morganchen12 The error I posted was all I could see from the logs in xcode. Is there some way to enable a more detailed logo output?

**Comment by JoeToeniskoetter** [comment]
Also, I proxied the device throwing the 400 error. I can share the request here but I'm not sure which bits of the request may be sensitive

**Comment by morganchen12** [comment]
Do you notice any differences between the requests from the device that receives an error and requests from the device that works?

Also, you can enable debug logs with the [`setLoggerLevel(_:)`](https://firebase.google.com/docs/reference/swift/firebasecore/api/reference/Classes/FirebaseConfiguration#setloggerlevel_:) method.

**Comment by JoeToeniskoetter** [comment]
Nothing looks obviously different besides the refresh token being passed in the request body. The API Key, url, grant_type all look the same. I did find something interesting when changing the log level to `.debug` though. 

It looks like there is an old token from 11/23/2021 that is found when the app starts up??

`[Firebase/Auth][I-AUT000017] Does not have valid access token. Estimated expiration date: 2021-11-23 02:35:19 +0000, current date: 2022-04-29 00:37:49 +0000`

This same log is output each time I build and rerun the app.

**Comment by JoeToeniskoetter** [comment]
Wow..... I just called `Auth.auth().signOut()` on start up, relaunched the app and it was able to get a new token. I guess there was a stale refresh token saved to my device and apparently associated with the bundle ID. Since the refresh token was expired, it wasn't able to exchange it for a new access token. Once I cleared out the old token via `Auth.auth().signOut()`, it was able to authenticate anonymously again and get a new token.

Even more frustrating, I bought a new iPhone last year and this token was even apparently transferred from the old phone since this issue was happening on the old one as well. Yes, I've been fighting this issue since last year..

**Comment by morganchen12** [comment]
Seems like we should improve the error message in this case so reauth is more obvious. Glad you were able to figure it out!

**Comment by paulb777** [comment]
Closing for staleness. Please comment or open a new issue to continue the discussion.
