### ISSUE TITLE
Missing StorageTask API

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#9716]
another Swift-related issue, this time in Storage. In our current SDK, we use FIRStorageTaskSnapshot.task as a FIRStorageObservableTask<FIRStorageTaskManagement>, so we can resume from the pause callback. But now it seems that .task returns just a FIRStorageTask that does not implement the resume selector, so we are getting an invalid selector error calling [task resume].
basically, if you have a task of type FIRStorageObservableTask<FIRStorageTaskManagement>, and you do [task observeStatus:], the callback that runs gets a FIRStorageTaskSnapshot that only contains a FIRStorageTask, not the original FIRStorageObservableTask
the old version: https://github.com/firebase/firebase-ios-sdk/blob/v8.15.0/FirebaseStorage/Sources/Public/FirebaseStorage/FIRStorageTaskSnapshot.h

I think because it has __kindof it works?
oh no that's not it - it's because FIRStorageTask had a resume selector in 8.15.0
https://github.com/firebase/firebase-ios-sdk/blob/v8.15.0/FirebaseStorage/Sources/Public/FirebaseStorage/FIRStorageTask.h
whereas the Swift bridged version of FIRStorageTask does not have the enqueue pause resume or cancel selectors
```
@interface FIRStorageTask : NSObject
/// An immutable view of the task and associated metadata, progress, error, etc.                                                                            
@property(nonatomic, readonly, strong) FIRStorageTaskSnapshot *_Nonnull snapshot;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end
```
this appears to be a breaking change

**Comment by jonsimantov** [comment]
Here is a specific breakdown of what's happening.

In 8.15.0, given a FIRStorageDownloadTask or FIRStorageUploadTask, if you call [task observeStatus:...], the block that gets called on a status event receives a FIRStorageTaskSnapshot containing the a task object of the original class type (DownloadTask or UploadTask), which you can then call resume, pause, or cancel on.

In 9.0.0, when the observer block is called, the snapshot it receives contains a task object of type FIRStorageTask, which does not allow you to call pause, resume, or cancel, even though the original controller's class would have allowed it.

**Comment by paulb777** [comment]
@jonsimantov Let us know if there is still an issue after #9717

**Comment by paulb777** [comment]
Closing since this issue seems to be resolved now.
