### ISSUE TITLE
Database QuickStart UITests failing

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#9725]
The zip nightly tests have been failing the last several days because of a UITest infrastructure problem running the Database UITests.  To repro, download the database archive from the nightly zip run and add a GoogleService-Info.plist to the Xcode project

![Screen Shot 2022-04-28 at 7 12 24 AM](https://user-images.githubusercontent.com/73870/165772507-a1bf70ae-a533-4459-ad4a-a4e7b8baff24.png)

**Comment by granluo** [comment]
One thing I found was 
[`FIRDataEventTypeValue`](https://github.com/firebase/quickstart-ios/blob/09d330b71f4267cd5f19e4c568c723231581d95c/database/DatabaseExample/SignInViewController.m#L52) was not observed and `performSegueWithIdentifier` was not able to perform. That results in the UITests stops at tapping the signing button, and cannot access the view after sign in.

**Comment by paulb777** [comment]
So there's potentially an SDK issue that the Database SDK isn't calling the `observeEventType` API correctly?

**Comment by granluo** [comment]
Yep I think so. The block does not run. 
According to the [doc](https://firebase.google.com/docs/reference/ios/firebasedatabase/api/reference/Enums/FIRDataEventType#/c:@E@FIRDataEventType@FIRDataEventTypeValue), the block for`FIRDataEventTypeValue` seems to be triggered when data are changed, but I am not sure those data are changed. Anyway, the block should be accessed to pass tests.

**Comment by ncooke3** [comment]
Gran and I investigated and we were able to fix a local failure by manually editing the Firebase console. I think a flaky test failure left the console RTDB data in an unexpected state. 

We are going to wait for the nightlies to verify the fix.

**Comment by ncooke3** [comment]
While testing GDT 9.1.4 in #9771, I was able to get a clean run of the RTDB QS zip tests: https://github.com/firebase/firebase-ios-sdk/runs/6330570152?check_suite_focus=true

Therefore, I think that confirms that the issue has been resolved.
