### ISSUE TITLE
Firebase database Codable not working with empty arrays

### ISSUE THREAD

**Issue by jiachenyee** [firebase/firebase-ios-sdk#9742]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.3
  * Firebase SDK version: 8.15.0
  * Installation method: Swift Package Manager
  * Firebase Component: Database
  * Target platform(s): iOS

#### Steps to reproduce:

What happened? How can we make the problem occur?
1. Create a struct (conforming to Codable) with 1 or more array properties
2. Create an instance with one or more of the arrays empty.
3. Using `FirebaseDatabaseSwift`, write the sample data using `ref.setValue(from: sampleData)`.
4. In the Firebase console, the empty array does not show up
5. Read the value from the database using `snapshot.data(as: SampleData.self)`. It throws back an error `The data couldn’t be read because it is missing.`.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

Sample Project: [Test Project.zip](https://github.com/firebase/firebase-ios-sdk/files/8604774/Test.Project.zip)
- Tap on the **Write Sample 1** button
  - It writes `SampleData(value: [], moreValue: [])`
  - Nothing would appear on the Firebase console 
- Tap on the **Write Sample 2** button
  - It writes `SampleData(value: ["aa"], moreValue: [])`
  - Only the `value` parameter appears on the Firebase console
  - ![image](https://user-images.githubusercontent.com/36725840/166290264-90d7ae13-63ed-424c-b1fc-953a663d0336.png)
- Tap on the **Write Sample 3** button
  - It writes `SampleData(value: [], moreValue: ["a"])`
  - Only the `moreValue` parameter appears on the Firebase console
  - ![image](https://user-images.githubusercontent.com/36725840/166290588-f79e96c5-4500-46e7-a4a0-c58a2a5a1514.png)

Sample Data Struct
```swift
struct SampleData: Codable {
    var value: [String]
    var moreValue: [String]
}
```

Writing Data
```swift
// Sample 1
try ref.setValue(from: SampleData(value: [], moreValue: []))

// Sample 2
try ref.setValue(from: SampleData(value: ["aa"], moreValue: []))

// Sample 3
try ref.setValue(from: SampleData(value: [], moreValue: ["a"]))
```

Reading Data
```swift
ref.getData { data, snapshot in
    do {
        print(try snapshot.data(as: SampleData.self))
    } catch {
        print(error.localizedDescription)
    }
}
```

**Comment by mortenbekditlevsen** [comment]
The Real-time database does not store empty objects (Dictionaries) nor empty arrays.
It's thus not an error with library, but rather a limitation with the underlying storage which you have to work around. For instance by storing a dummy value rather than an empty array.

**Comment by rizafran** [comment]
Thanks for sharing the answer, @mortenbekditlevsen. 

@jiachenyee, you may also refer to [this answer](https://stackoverflow.com/a/48463446) provided by one of the engineers. I'll now close this issue but feel free to reopen if you have additional questions.
