### ISSUE TITLE
Firebase DynamicLinks does not receive dynamic link after fresh Install

### ISSUE THREAD

**Issue by Botz** [firebase/firebase-ios-sdk#976]
* Xcode version: 9.2
  * Firebase SDK version: 4.11.0
  * Firebase Component: DynamicLinks
  * Component version: 2.3.2

Steps to reproduce:
1. Create a Dynamic Link
2. Open the link on the phone(tried it with a click on the link in notes, or scanning a QR code, or click in the browser)
3. Link redirects to app store to download
4. Build and install the app via XCode
Received this: schema://google/link/?dismiss=1&is_weak_match=1

I tried it in our project and afterwards created a new clean project following the instructions from https://firebase.google.com/docs/dynamic-links/ios/receive

Afterwards, I downgraded the Firebase SDK version to a version which worked for me(which was 4.5.0 where Component Version was 2.1.0). Starting from SDK version 4.6.0 Component Version 2.2.0 the DynamicLink handling after new installs was broken for me.

**Comment by dmandar** [comment]
This should now be fixed. Please retest.

**Comment by Botz** [comment]
Do i have to update the SDK? Because the new version(4.12) isn't available with cocoapods

**Comment by morganchen12** [comment]
The fix hasn't been released yet. We'll close the ticket when the next binary is released.

**Comment by dmandar** [comment]
@Botz this is now working for me with the currently available version (FDL 2.3.2)..sorry should have mentioned that. Can you try again?

**Comment by paulb777** [comment]
@morganchen12 Any reason this is still open. Reopen if so.
