### ISSUE TITLE
Error ITMS-90049

### ISSUE THREAD

**Issue by traktor74** [firebase/firebase-ios-sdk#9801]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.3.1
  * Firebase SDK version: 8.14.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: ?
  * Target platform(s): `iOS`

### [REQUIRED] Step 2: Describe the problem

Error ITMS-90049: GoogleUtilities_Environment replaced with GoogleUtilities\u005fEnvironment- after trying to upload ipa file to TestFlight (using fastlane) getting error - Transporter transfer failed.

**Comment by paulb777** [comment]
This might be a recent Apple issue - See https://forums.swift.org/t/itms-90562-invalid-binary-when-uploading-build-to-testflight/57317

**Comment by jackgmarch** [comment]
Upon further investigation we cannot repro with a demo app, so I'll do some more investigation to see what in our environment is causing this error.
