### ISSUE TITLE
SPM: Updating to Firebase iOS SDK 9.0.0 fails (Invalid diagnostics signature)

### ISSUE THREAD

**Issue by SKuhlemann** [firebase/firebase-ios-sdk#9806]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: `13.3.1`
  * Firebase SDK version: `9.0.0`
  * Installation method: `Swift Package Manager`
  * Firebase Component: `Auth, Core, FirestoreSwift, Messaging, Storage, AnalyticsWithoutAdIdSupport, Crashlytics)`
  * Target platform(s): `iOS | macOS (not Crashlytics) | iOS-Widget (only Storage)`

### [REQUIRED] Step 2: Describe the problem

As discussed with Paul on Stackoverflow, I am opening this ticket.

My iOS-App worked like a charm with Firebase 8.15.0.

Now I changed the Firebase package dependencies to version "9.0.0 - Next major" and get a lot of XCode-errors while compiling, which I can't link to the breaking changes related to this major release.

What I already did:

- Updated the "import" statements and Swift packages according to the patch notes
- Cleaned the build folder and deleted the whole DerivedData folder
- I even uninstalled XCode and reinstalled it
- Restarted my Intel-MacBook

#### Steps to reproduce:

The problem can only be reproduced by compiling the whole project.
I am willing to share my whole project folder with you if necessary, but it would be great if I do not have to upload it here accessible for everyone...

Attached you find the build error created by Xcode after a fresh compiling with a cleaned DerivedData folder.

#### Relevant Code:

```
See above / Whole code needed.
```

[Build target PoliApp_2022-05-16T18-57-20.txt](https://github.com/firebase/firebase-ios-sdk/files/8701979/Build.target.PoliApp_2022-05-16T18-57-20.txt)

**Comment by ncooke3** [comment]
Hi @SKuhlemann, 

Thanks for filing an issue and sorry for the trouble.

I looked at the attachment and I'm not seeing anything pop out to me.

Based on the screenshot in the [SO post](https://stackoverflow.com/questions/72229625/updating-to-firebase-ios-sdk-9-0-0-fails-invalid-diagnostics-signature), it looks like `BoardViewModel.swift` is not compiling. Could you try addressing that error and build again?

**Comment by SKuhlemann** [comment]
Hi @ncooke3,

thank you for your reply.

There are 73 compiling errors in a lot of my project files since 9.0.0. 
The screenshot in my SO post just shows a small snippet.
These are so "real" errors, because all files compile correctly under Firebase 8.15.0.

All errors relate to the Firebase libraries:
<img width="1188" alt="BoardViewModel" src="https://user-images.githubusercontent.com/67631466/168652094-577ae0c4-6f4e-41d6-b64b-8ee531aa2027.png">

The needed libraries are included in my project:
<img width="842" alt="FrameWorks" src="https://user-images.githubusercontent.com/67631466/168652416-f0e736fb-64d9-4f09-9a0a-5918ceb91ab8.png">

**Comment by ncooke3** [comment]
Gotcha, thanks for the info– I better understand the issue.

Are you using an M1 or Intel Mac?

**Comment by SKuhlemann** [comment]
It's an Intel Mac: MacBook Pro (16", 2019)

Just out of curiosity I tried "Archive" instead of "Build" in Xcode:
Then I don't get any "Could not read serialized diagnostics file: error("Invalid diagnostics signature")"-warnings, but the Compiler Errors stay the same.

**Comment by ncooke3** [comment]
@SKuhlemann, could you try explicitly importing `FirebaseFirestore`. 

Sorry for the confusion, but `FirebaseFirestoreSwift` does not transitively import `FirebaseFirestore`. 

So add:
```swift
import FirebaseFirestore
```
and try re-building.

**Comment by SKuhlemann** [comment]
Thank you @ncooke3 that solved most of the errors!

There is just one type of error left:

<img width="1173" alt="AuthErrorCodes" src="https://user-images.githubusercontent.com/67631466/168675383-8a47e4cb-5957-446b-ac6c-5d50dbf102bf.png">

Exactly the same code worked with 8.15.0.

Am I missing another "import" or has there been a breaking change with these AuthErrorCodes which are not listed in the Patch Notes?

**Comment by ryanwilson** [comment]
@SKuhlemann apologies for missing that one in the CHANGELOG - there were very few scenarios where this breaks so it was mostly seamless to developers. We'll make sure it gets documented somewhere though (likely the CHANGELOG).

We changed `AuthErrorCode` to use `NS_ERROR_ENUM`, which makes catching errors significantly better in Swift. A direct translation would be replacing `extension AuthErrorCode` with `extension AuthErrorCode.Code`, as `AuthErrorCode` is now a struct and has a subtype called `Code` that's the enum that contains all the codes. We know the naming is... _not ideal_ 🙃  but it does enable some nicer error handling. We do plan on revamping Auth error handling in the future as well.

**Comment by SKuhlemann** [comment]
"Build Succeeded" 🥇 

Thanks a lot for this fast and qualified support!
