### ISSUE TITLE
Crashed: FPRProtoUtils.m line 332 FPRGetApplicationInfoMessage

### ISSUE THREAD

**Issue by siddew201** [firebase/firebase-ios-sdk#9814]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a GitHub issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: ___ 13.2.1 (13C100)__
  * Firebase SDK version: ___8.4.0__
  * Installation method:  CocoaPods
  * Firebase Component: _____ (Messaging, DynamicLinks, Installations, Analytics, Crashlytics)
  * Target platform(s): iOS

#### Steps to reproduce:

This was produced for live users of our app.

#### Relevant Code:
Crashed: com.google.perf.FPREventsQueue
0  libsystem_kernel.dylib         0x7b78 __pthread_kill + 8
1  libsystem_pthread.dylib        0x73bc pthread_kill + 268
2  libsystem_c.dylib              0x2051c abort + 168
3  libsystem_malloc.dylib         0x1ca04 _malloc_put + 550
4  libsystem_malloc.dylib         0x1cc9c malloc_zone_error + 100
5  libsystem_malloc.dylib         0x1c790 free_list_checksum_botch + 40
6  libsystem_malloc.dylib         0x30dc tiny_free_list_remove_ptr + 676
7  libsystem_malloc.dylib         0x4454 tiny_free_no_lock + 476
8  libsystem_malloc.dylib         0x50c8 free_tiny + 432
9  libnetwork.dylib               0x14df20 -[NWConcrete_nw_endpoint dealloc] + 888
10 libnetwork.dylib               0x3f98 -[NWOSAddressEndpoint dealloc] + 76
11 libnetwork.dylib               0xe2b28 -[OS_nw_array dealloc] + 84
12 libnetwork.dylib               0xcd838 -[NWConcrete_nw_path .cxx_destruct] + 96
13 libobjc.A.dylib                0x82f0 object_cxxDestructFromClass(objc_object*, objc_class*) + 116
14 libobjc.A.dylib                0x5144 objc_destructInstance + 80
15 libobjc.A.dylib                0xe9b4 _objc_rootDealloc + 80
16 libnetwork.dylib               0x109bc8 -[NWConcrete_nw_path dealloc] + 100
17 libnetwork.dylib               0x11a0f0 -[NWConcrete_nw_path_evaluator .cxx_destruct] + 72
18 libobjc.A.dylib                0x82f0 object_cxxDestructFromClass(objc_object*, objc_class*) + 116
19 libobjc.A.dylib                0x5144 objc_destructInstance + 80
20 libobjc.A.dylib                0xe9b4 _objc_rootDealloc + 80
21 libnetwork.dylib               0xbb080 -[NWConcrete_nw_path_evaluator dealloc] + 1176
22 SystemConfiguration            0x5cb4 SCNetworkReachabilityGetFlags + 392
23 FirebasePerformance            0x1d0b8 FPRGetApplicationInfoMessage + 332 (FPRProtoUtils.m:332)
24 FirebasePerformance            0x1cef4 FPRGetPerfMetricMessage + 48 (FPRProtoUtils.m:48)
25 FirebasePerformance            0xbd68 __29-[FPRClient logNetworkTrace:]_block_invoke + 224 (FPRClient.m:224)
26 libdispatch.dylib              0x1e68 _dispatch_call_block_and_release + 32
27 libdispatch.dylib              0x3a2c _dispatch_client_callout + 20
28 libdispatch.dylib              0xb204 _dispatch_lane_serial_drain + 892
29 libdispatch.dylib              0xbc80 _dispatch_lane_invoke + 392
30 libdispatch.dylib              0x16500 _dispatch_workloop_worker_thread + 648
31 libsystem_pthread.dylib        0x10bc _pthread_wqthread + 288
32 libsystem_pthread.dylib        0xe5c start_wqthread + 8

```
// TODO(you): code here to reproduce the problem
```

**Comment by rizafran** [comment]
Thanks for reporting, @siddew201. Is the issue reproducible on your end? If so, could you provide the steps in reproducing it?

**Comment by siddew201** [comment]
Thanks @rizafran for responding. Actually the issue is appearing at user's side and not at our end. Can't help in reproducing it. Just have this stack trace from firebase crashlytics which we have already shared with you.

**Comment by rizafran** [comment]
Thanks for the info, @siddew201. Is it possible for you to update the SDK to a later version and see if the issue will be fixed?
