### ISSUE TITLE
The target gRPC-cpp in product gRPC-cpp contains unsafe build flags

### ISSUE THREAD

**Issue by Nahatakyan** [firebase/firebase-ios-sdk#9818]
* MacOS version: 12.4 (21F79)
  * Xcode version: 13.4 (13F17a)
  * Firebase SDK version: 8.15.0, 9.0.0
  * Installation method: Swift Package Manager
  * Firebase Component: Analytics, Crashlytics
  * Target platform(s): iOS

Hi. I am trying to add Firebase to my app with SPM and getting these errors.
```
The target gRPC-cpp in product gRPC-cpp contains unsafe build flags
The target gRPC-Core in product gRPC-cpp contains unsafe build flags
```

I have reset caches, delete derived data, update all other packages, then install Firebase. Still can't install the package.

**Comment by gilroykilroy** [comment]
I got this issue too. I had the SPM config as 9.0.0 - up to next major version. The package listing in Xcode read "firebase-is-sdk 9.0.0". Now it is reading "Firebase 9.0.0" and generating those build errors (and more:  Missing package product 'FirebaseAnalyticsWithoutAdIdSupport',  Missing package product 'FirebaseCrashlytics'). Even when setting the version to be exactly 9.0.0 it still fails as above.

**Comment by hiryanbautista** [comment]
https://github.com/grpc/grpc-ios/issues/86#issue-1240493740

**Comment by dennycd** [comment]
issue now resolved from gRPC/iOS side. Please reset your SPM local cache or reinstall.

**Comment by Nahatakyan** [comment]
@dennycd Thanks. it's fixed
