### ISSUE TITLE
AnalyticsParameterScreenClass higher priories than AnalyticsParameterScreenName in SwiftUI

### ISSUE THREAD

**Issue by liangwangcm** [firebase/firebase-ios-sdk#9823]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: __13.2___
  * Firebase SDK version: __8.1___
  * Installation method: `CocoaPods`
  * Firebase Component: Analytics, RemoteConfig, Crashlytics
  * Target platform(s): `iOS`

#### Steps to reproduce:

In a SwiftUI project,  try to log an event with valid `AnalyticsParameterScreenName` and `AnalyticsParameterScreenClass`. Then In Firebase analysis, only `AnalyticsParameterScreenClass` value can be found. 

It this designed by purpose? 

#### Relevant Code:

```
Analytics.logEvent(AnalyticsEventScreenView,
                           parameters: [AnalyticsParameterScreenName: name,
                                        AnalyticsParameterScreenClass: screenClass])
```

**Comment by rizafran** [comment]
Hello @liangwangcm, to clarify this line:

> Then In Firebase analysis, only AnalyticsParameterScreenClass value can be found.

 Could you confirm if you're referring to the `DebugView` page in Analytics dashboard? 

 I tried logging an event with `AnalyticsParameterScreenName` and `AnalyticsParameterScreenClass` on SwiftUI project, but I'm able to get the logs for both parameters. Could you try enabling your Analytics debugging by adding the [`-FIRAnalyticsDebugEnabled`](https://firebase.google.com/docs/analytics/get-started?platform=ios#start_logging_events_2) in your app scheme to see if both parameters are being logged?

**Comment by liangwangcm** [comment]
I found the root cause and it's my fault to choose here

![image](https://user-images.githubusercontent.com/103400893/169947115-77481a32-3614-4c1e-8363-80b5bdef6f2d.png)

I should have chosen other options :)
