### ISSUE TITLE
Problem getting current instance of Firestore without a dependency manager

### ISSUE THREAD

**Issue by PomegranateApps** [firebase/firebase-ios-sdk#9827]
* Xcode version: Version 13.4 (13F17a)
  * Firebase SDK version: 9.0.0
  * Installation method: Manual
  * Firebase Component: Auth, Core, Firestore
  * Target platform(s): iOS

### [REQUIRED] Step 2: Describe the problem

I've previously used Firebase through Swift Package Manager. I'm attempting to add the SDK manually and integrate it into my project without a dependency manager.
https://firebase.google.com/docs/ios/setup#objective-c_1

I am able to authenticate users, but I'm not able to access Firestore. When I try to get the current instance it returns nil.

#### Relevant Code:

```
// This returns nil
FIRFirestore *store = [FIRFirestore firestore];
```

**Comment by paulb777** [comment]
Please share the console log including when the error occurs.
