### ISSUE TITLE
Command ./Crashlytics/generate_project.sh failed

### ISSUE THREAD

**Issue by wangjiejacques** [firebase/firebase-ios-sdk#9832]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a GitHub issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.4
  * Firebase SDK version: 9.0.0
  * Installation method: CocoaPods 
  * Firebase Component: Crashlytics
  * Target platform(s): `All`

### [REQUIRED] Step 2: Describe the problem
I'm following [this](https://github.com/firebase/firebase-ios-sdk/tree/master/Crashlytics) to generate `gen/FirebaseCrashlytics/FirebaseCrashlytics.xcworkspace`

After running 
`brew install protobuf nanopb-generator`
`brew install protobuf`, 
command `Crashlytics/generate_project.sh` failed
#### Steps to reproduce:
What happened? How can we make the problem occur?

On macbook m1
running 
`brew install protobuf nanopb-generator`
`brew install protobuf`, 
`./Crashlytics/generate_project.sh`
I have the following error
```
Removing existing CCT protos...
Generating CCT protos...
command failed:  protoc -I=/Users/jie.wang/Developer/Projects/ContentSquare/firebase-ios-sdk/Crashlytics/ProtoSupport/Protos/ --plugin=protoc-gen-nanopb=/Users/jie.wang/Developer/Projects/ContentSquare/firebase-ios-sdk/Crashlytics/ProtoSupport/nanopb_objc_generator.py --nanopb_out=--extension=.nanopb --source-extension=.c --no-timestamp -I/Users/jie.wang/Developer/Projects/ContentSquare/firebase-ios-sdk/Crashlytics/ProtoSupport/Protos/:/Users/jie.wang/Developer/Projects/ContentSquare/firebase-ios-sdk/Crashlytics/Protogen/nanopb /Users/jie.wang/Developer/Projects/ContentSquare/firebase-ios-sdk/Crashlytics/ProtoSupport/Protos/crashlytics.proto
```
If I run this protoc code myself, I have this error `Unknown flag: --source-extension`
```
protoc -I=/Users/jie.wang/Developer/Projects/ContentSquare/firebase-ios-sdk/Crashlytics/ProtoSupport/Protos/ --plugin=protoc-gen-nanopb=/Users/jie.wang/Developer/Projects/ContentSquare/firebase-ios-sdk/Crashlytics/ProtoSupport/nanopb_objc_generator.py --nanopb_out=--extension=.nanopb --source-extension=.c --no-timestamp -I/Users/jie.wang/Developer/Projects/ContentSquare/firebase-ios-sdk/Crashlytics/ProtoSupport/Protos/:/Users/jie.wang/Developer/Projects/ContentSquare/firebase-ios-sdk/Crashlytics/Protogen/nanopb /Users/jie.wang/Developer/Projects/ContentSquare/firebase-ios-sdk/Crashlytics/ProtoSupport/Protos/crashlytics.proto
```

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
./Crashlytics/generate_project.sh
```

**Comment by paulb777** [comment]
There is likely something about your python configuration causing this problem.

Unless you're working on changing nanopb protos, line 20 of `./Crashlytics/generate_project.sh` is not needed. The `pod gen` command is sufficient for most development.  See also https://github.com/firebase/firebase-ios-sdk#development for additional development information.

**Comment by wangjiejacques** [comment]
Thanks

> There is likely something about your python configuration causing this problem.

I'm using `Python 3.9.13`, do you know what python configuration does it need?
