### ISSUE TITLE
Remote Config - support multiple projects - for more than 24 running tests

### ISSUE THREAD

**Issue by ElaineSchwner** [firebase/firebase-ios-sdk#9871]
### Step 0: Are you in the right place?

I can't have more than 24 running tests. Firebase Remote Config does not support multiple projects.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: _____
  * Firebase SDK version: _____
  * Installation method: `CocoaPods | Carthage | Zip file | Swift Package Manager` (select one)
  * Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Target platform(s): `All | iOS | Catalyst | macOS | tvOS | watchOS`

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulb777** [comment]
@ElaineSchwner Please fill out the issue template and describe reproduction steps.
