### ISSUE TITLE
bug: Twitter access token missing

### ISSUE THREAD

**Issue by robingenz** [firebase/firebase-ios-sdk#9878]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.4
  * Firebase SDK version: 9.1.0
  * Installation method: `CocoaPods` 
  * Firebase Component: Auth
  * Target platform(s): `iOS`

#### Steps to reproduce:

I require the Twitter Access Token after the user logs in.
Unfortunately, the Access Token is never available.

1. Sign in with Twitter on iOS (see code below)

-> `credential.accessToken` is `nil`

#### Relevant Code:

```swift
var provider = OAuthProvider(providerID: "twitter.com")
provider.getCredentialWith(nil) { credential, error in
	  if let error = error {
		// Handle error.
	  }
	  if let credential = credential {
	 	 // credential.accessToken is `nil`
	  }
}
```

Related to https://github.com/robingenz/capacitor-firebase/issues/99

**Comment by rizafran** [comment]
Thanks for reporting, @robingenz. I've tried to reproduce the issue, and based on my findings, I noticed that I'm getting an error "_Value of type 'AuthCredential' has no member 'accessToken_" when trying to get the access token. Instead, I tried to get the access token by setting `result.credential` as `OAuthCredential`:
`let cred:OAuthCredential = result?.credential as! OAuthCredential`

I'm currently checking with the engineer if this is the proper way on getting the access token so we could update the docs if needed.

**Comment by robingenz** [comment]
> Thanks for reporting, @robingenz. I've tried to reproduce the issue, and based on my findings, I noticed that I'm getting an error "_Value of type 'AuthCredential' has no member 'accessToken_" when trying to get the access token. Instead, I tried to get the access token by setting `result.credential` as `OAuthCredential`: `let cred:OAuthCredential = result?.credential as! OAuthCredential`
> 
> I'm currently checking with the engineer if this is the proper way on getting the access token so we could update the docs if needed.

Thank you for your response @rizafran! 
I already access the AccessToken this way:

![grafik](https://user-images.githubusercontent.com/13857929/171414178-a4d1249c-c9ad-4688-9d37-6b6cd6d103a2.png)
Unfortunately it is always `nil`.

**Comment by robingenz** [comment]
Thanks for the tip! I will test it again and get back to you.

**Comment by robingenz** [comment]
@rizafran Thank you very much! It works now! 🎉
