### ISSUE TITLE
Extremely slow compile time of Objective-C files and dependencies

### ISSUE THREAD

**Issue by Kaspik** [firebase/firebase-ios-sdk#9883]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 14.0 Beta 1
  * Firebase SDK version: 9.1.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: Promises - dependency, Crashlytics
  * Target platform(s): `iOS`

### [REQUIRED] Step 2: Describe the problem

When building the app in new Xcode 14.0 Beta 1 - new Build Timeline is available to show you the build and compile times. Firebase and mainly it's dependencies we didn't choose to use are the biggest slowdown of our compile times. (see an attachment)

It would be nice to either:
1. Improve compile time of the dependency
2. Try to find a way how to release the framework without these dependencies

Build environment: MacBook Pro M1 Max, 32GB, Xcode 14.0 Beta 1, iOS 16 beta 1 simulator of iPhone 13 Pro

<img width="1236" alt="Screenshot 2022-06-07 at 15 50 13" src="https://user-images.githubusercontent.com/7204168/172400344-8b22aa25-b467-4b3e-9b67-c1b4983c5aaf.png">

#### Steps to reproduce:

Include Crashlytics + Analytics + Messaging in your project via SPM and run Build (Compile) with new Xcode - then check the Build Timeline.

### Additional notes

I did open an issue in the dependency itself ([promises](https://github.com/google/promises/issues/186)), but wanted to cross-link it here for shared knowledge - but it's also Crashlytics problem.

I do think this is related to the new and still better Swift-optimized compiler and build system, but maybe it's the right time to migrate relevant Objective-C code to Swift too?

Let me know if I can be helpful here somehow. Thanks for looking into this!

**Comment by ryanwilson** [comment]
Thanks the for the report! We're keen to dig into this more - one strange thing in particular is `GULNSData+zlib.m` seemingly taking 13+ seconds when it's less than 200 lines of code: https://github.com/google/GoogleUtilities/blob/main/GoogleUtilities/NSData%2Bzlib/GULNSData%2Bzlib.m

Hunch: maybe it has to do with the ObjC categories, as FBLPromises also is longer than expected.

**Comment by Kaspik** [comment]
It's importing `zlib` which is probably little big bigger, right?

**Comment by ryanwilson** [comment]
Okay I ran it locally and saw really strange results. My hunch: some of these long times include waiting time until the next file can build. Example: `dummy.m` took 439 seconds to build... which is [an empty file](https://github.com/firebase/firebase-ios-sdk/blob/master/CoreOnly/Sources/dummy.m). I'll try to dig into the WWDC sessions to see if this is explained further, or maybe it's time to file some Feedback.


My build:
![My Local Build](https://user-images.githubusercontent.com/1097316/172446226-891cb3e2-a51e-4f11-8cdc-3eb362ba1ff2.png)

**Comment by Kaspik** [comment]
That's really long time. 😄 I'll keep an eye on this and the files that take longer than expected. Thanks for digging into this, every build time improvement is huge improvement for everyone!

**Comment by ryanwilson** [comment]
> Thanks for digging into this, every build time improvement is huge improvement for everyone!

Sure thing, thanks again for the report! We're excited to see how we can improve our build times.

**Comment by morganchen12** [comment]
Hey @Kaspik, I built PromisesObjC with clang's `-ftime-trace` and found that all of the files that took a while in your screenshot built in ~100ms.
<img width="1680" alt="Screen Shot 2022-06-08 at 3 37 22 PM" src="https://user-images.githubusercontent.com/4529021/172729048-eec44f22-88fe-4f75-aa24-7d29a80977bb.png">

I did this via CocoaPods by setting `-ftime-trace` in the `Other C Flags` build setting of the generated Pods project, and then examining the generated json in `chrome://tracing`. The build time trace can be found in

```
DerivedData/${PROJECT}/Build/Intermediates.noindex/Pods.build/${DESTINATION}/PromisesObjC.build/Objects-normal/${ARCH}/${FILENAME}.json
```
Where in my case PROJECT was the FirebaseUI sample project, DESTINATION was `Debug-iphonesimulator`, ARCH was `x86_64`, and FILENAME was `FBLPromise+Race`.

It does seem like Xcode 14 is including waiting time as build time for files, which is resulting in inaccurate graphs.

**Comment by Kaspik** [comment]
Hey @morganchen12, interesting!

FILENAME was `FBLPromise+Race` - so did you compile just the one file, or the project itself completely?
And did you try that without CocoaPods but via SPM?

**Comment by MartinStrambach** [comment]
@Kaspik Thumbs up for raising this.
@ryanwilson Any updates? We're seeing the same behavior. The slowest parts are FBLPromises, GoogleDataTransport, and FirebaseCrashlytics.
Slow compile times can be also observed with GoogleSignIn dependency.
![Screenshot 2022-06-22 at 14 44 31](https://user-images.githubusercontent.com/11178869/175032786-d179183f-57ea-47ce-b4fe-cfba360605d1.png)

Let me know if I can help somehow.

**Comment by morganchen12** [comment]
@MartinStrambach, have you tried compiling your project with the `-ftime-trace` flag to identify bottlenecks in the built dependencies? Our investigation suggests Xcode is including time spent waiting to compile a file as total compile time, which is resulting in misleading build times for some dependencies.

**Comment by dingtianran** [comment]
I'm seeing these strange things across other hybrid project which objective-c compiling is super slow.

As we now have P cores/E cores on apple silicons and they have shockingly performance differences, I'm suspecting that Xcode will strategically assign objective-c source code to E cores to compile for some reason.

I agree with @MartinStrambach that this strategy could have been introduced for very long but we couldn't see it until Xcode14

**Comment by MartinStrambach** [comment]
@dingtianran The same happens on Intel macs as well, not just Apple Silicons.

**Comment by paulb777** [comment]
Is this still an issue with the Xcode 14 GA?

**Comment by Kaspik** [comment]
It got better! But yes, it's still an issue as it's still the slowest compiled files that in total (together even in parallel) make a big chunk of compile time.

Promises take about 2 sec each file, GoogleDataTransport the same. Firebase Crashlytics, similar.

```
GDTCORUploadCoordinator.m 1.8 seconds
GDTCORTransformer.m 1.9 seconds
GDTCORTransport.m 2.1 seconds
```

```
FIRCrashlytics.m 2.3 seconds
```
<img width="2345" alt="Screenshot 2022-12-02 at 10 27 38" src="https://user-images.githubusercontent.com/7204168/205260966-e6c40ca5-89a3-45ef-b7b3-4b7fe5587d65.png">

Overall, I don't think there is much to improve or do except really try to port those files into swift or divide them into separate modules / less cross-dependent modules. Not sure where the Swift rewrite lays down at your roadmap, but curious to hear your thoughts and ideas :)

**Comment by paulb777** [comment]
Going to close since there's not a clear action. We are gradually migrating our implementations from Objective C to Swift.
