### ISSUE TITLE
FIRAuthErrorDomain: Code: 17062

### ISSUE THREAD

**Issue by zhiyao92** [firebase/firebase-ios-sdk#9893]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.2.1
  * Firebase SDK version: 9.0.0
  * Installation method: `Swift Package Manager` 
  * Firebase Component: Auth
  * Target platform(s): `iOS`

### [REQUIRED] Step 2: Describe the problem

There has been an inconsistent behaviour where we get FIRAuthErrorDomain: Code: 17062 based on the [Firebase Error](https://firebase.google.com/docs/reference/ios/firebaseauth/api/reference/Enums/FIRAuthErrorCode) where it
indicates that an internal error occurred within a SFSafariViewController or WKWebView.

We notice this problem affect a minority group of our users of at least 69 users with over 200 events in the last 30 days. 

I've checked on the usage quote and we are still below the cap. 

I've saw a problem raised on another [issue](https://github.com/firebase/firebase-ios-sdk/issues/849) and have follow the replies and re-check the implementation of push notification and have verify that the implementation is correct. 

#### Steps to reproduce:

The issue is quite intermittent, but is there a way to debug it through SFSafariViewController as the error indicates that there is an internal error.

I do not have a downloadable sample project as this requires a large number of user logging in with phone number with a small percentage facing this issue.

#### Relevant Code:

No relevant code but happy to be able to provide anything that is useful to debug this.

**Comment by rizafran** [comment]
Thanks for reporting, @zhiyao92. To understand the root cause of the issue, is it possible for you to provide the complete error message?

**Comment by morganchen12** [comment]
You should file a [support issue](https://firebase.google.com/support) so our staff can look at your project and provide more insight on why your app's traffic is restricted.
