### ISSUE TITLE
Crash in abseil (symbol not found) when binary compiled on xcode 14 beta 1 is run on ios 15 device

### ISSUE THREAD

**Issue by quantamrhino** [firebase/firebase-ios-sdk#9895]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a GitHub issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 14 beta 1
  * Firebase SDK version: 8.15.0
  * Installation method: `Swift Package Manager` (select one)
  * Firebase Component: abseil (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Target platform(s): `iOS`

### [REQUIRED] Step 2: Describe the problem

Xcode 14 beta 1 compiles fine, then when run on an ios15 device crashes immediately with this. Looks like an issue in abseil, but that repo had no way to submit an issue.

dyld[75682]: Symbol not found: (_$sSo6CGRectV12CoreGraphicsE9__divided5slice9remainder10atDistance4fromySpyABG_AiC7CGFloatVSo0A4EdgeVtF)
  Referenced from: '/private/var/containers/Bundle/Application/020BEBE0-2DEE-4E97-A090-DDD32109549C/My.app/My'
  Expected in: '/usr/lib/swift/libswiftCoreGraphics.dylib'
Symbol not found: (_$sSo6CGRectV12CoreGraphicsE9__divided5slice9remainder10atDistance4fromySpyABG_AiC7CGFloatVSo0A4EdgeVtF)
  Referenced from: '/private/var/containers/Bundle/Application/020BEBE0-2DEE-4E97-A090-DDD32109549C/My.app/My'
  Expected in: '/usr/lib/swift/libswiftCoreGraphics.dylib'

#### Steps to reproduce:

What happened? How can we make the problem occur?
Crash. Just running a binary using firebase + crashlytics + analytics compiled on xcode 14 beta 1, on ios 15 real device crashes.

**Comment by rizafran** [comment]
Thanks for filing this, @quantamrhino. I tried to reproduce the issue but I wasn't able to get the same crash. Is the issue only happening on Xcode 14 beta and iOS 15 device?

**Comment by morganchen12** [comment]
@quantamrhino Your app is crashing because a Swift library is missing. Can you try setting the `Always Embed Swift Standard Libraries` build setting to YES and seeing if it still crashes?

**Comment by quantamrhino** [comment]
It's already on, both on the target and on the project as well... 
It's not happening on a simulator running 15.5, but on a 15.5 real device it happens every time. Weird, right? 
The app didn't change (it was working great on xcode 13 and 15.5... so i'm trying to figure out why :-)
clean build, same issue. it crashes on 2 different devices running 15.5 (12 pro max and 7)
deleting derived data didn't help either.

I'm sure this is an issue with Xcode - i was wondering if there's a workaround to get unblocked. 
Thanks for responding so fast to me.

Aloha!

**Comment by quantamrhino** [comment]
I figured it out. Since it was complaining about libswiftCoreGraphics, which was super odd, I just added that as optional to the build phases:
No crash. Closing.

<img width="738" alt="Screenshot 2022-06-10 at 10 38 41 AM" src="https://user-images.githubusercontent.com/67089425/172994471-1a53ad31-3675-4e16-998b-9dbe2a051b9a.png">
