### ISSUE TITLE
Firebase In app messaging Compiling issue

### ISSUE THREAD

**Issue by vict1108** [firebase/firebase-ios-sdk#9897]
/Users/*****/Library/Developer/Xcode/DerivedData/***/Build/Products/Debug-iphonesimulator/Firebase_FirebaseInAppMessaging_iOS.bundle: No such file or directory

**Comment by vict1108** [comment]
I added firebase In app  messaging through swift packages after adding this package I am not able compile my project.

**Comment by vict1108** [comment]
<!-- DO NOT DELETE
  * Xcode version: _Version 13.4.1 ____
  * Firebase SDK version: __9.1.0___
  * Installation method:  Swift Package Manager
  * Firebase Component: FirebaseInAppMessaging-Beta 
  * Target platform(s):  iOS

### [REQUIRED] Step 2: I added firebase In app messaging through swift packages after adding this package I am not able to compile my project.

#### Steps to reproduce:

just add firebase In-app messaging through swift packages. it will through a compiler error like below

/Users/**/Library/Developer/Xcode/DerivedData//Build/Products/Debug-iphonesimulator/Firebase_FirebaseInAppMessaging_iOS.bundle: No such file or directory

#### Relevant Code:

/Users/**/Library/Developer/Xcode/DerivedData//Build/Products/Debug-iphonesimulator/Firebase_FirebaseInAppMessaging_iOS.bundle: No such file or directory

```
// TODO(you): code here to reproduce the problem
```

**Comment by ryanwilson** [comment]
@vict1108 can you please share some of the information that I requested in the comment above? Right now we don't have enough information to reproduce or debug the issue.

**Comment by morganchen12** [comment]
@vict1108 you likely need to remove the InAppMessaging bundle references from your project. Look around in your app's Build Phases tab and remove any red highlighted lines you see.

**Comment by vict1108** [comment]
>

**Comment by vict1108** [comment]
> @vict1108 you likely need to remove the InAppMessaging bundle references from your project. Look around in your app's Build Phases tab and remove any red highlighted lines you see.

I did't see any red Line in build phase tab

**Comment by vict1108** [comment]
> @vict1108 sorry for the troubles you're seeing - can you please fill out the issue template so we can get more information like the SDK version, platform, etc?
> 
> Also, since it's pointing at derived data, this could be a bad state. Have you tried a clean build, deleting derived data, and relaunching Xcode?

SDK version - 9.1.0
platform - IOS
Xcode version - 13.4.1
