### ISSUE TITLE
Internal server error 

### ISSUE THREAD

**Issue by dsngeu** [firebase/firebase-ios-sdk#9929]
- We have valid fcm token at server and when we tried to send push notification to fcm token we received **internal server error**, after sometime it start working fine for the same FCM token and it happened for 20-30 tokens on 20th Jun 2022.
Would you please help us to find out the reason ?

**Comment by rizafran** [comment]
Hi @dsngeu, this seems to be a backend issue. That being said, please file a ticket through the [support channel](https://firebase.google.com/support) so the team could investigate the issue. Thanks.
