### ISSUE TITLE
com.google.firebase.crashlytics.ios.exception

### ISSUE THREAD

**Issue by siddew201** [firebase/firebase-ios-sdk#9930]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a GitHub issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

Xcode version: ___ 13.2.1 (13C100)__
Firebase SDK version: _8.4.0
Installation method: CocoaPods
Firebase Component: _____ (Messaging, DynamicLinks, Installations, Analytics, Crashlytics)
Target platform(s): iOS

#### Steps to reproduce:

Crash is appearing at user's end. We are unable to reproduce it at our side.

#### Relevant Code:

Crash Item	:	 _hidden#18779 line 159
Issue Details	:	Crashed: com.google.firebase.crashlytics.ios.exception
0  FirebaseCrashlytics            0x1cd90 FIRCLSProcessRecordAllThreads + 393 (FIRCLSProcess.c:393)
1  FirebaseCrashlytics            0x1d170 FIRCLSProcessRecordAllThreads + 424 (FIRCLSProcess.c:424)
2  FirebaseCrashlytics            0x15f88 FIRCLSHandler + 34 (FIRCLSHandler.m:34)
3  FirebaseCrashlytics            0x10954 __FIRCLSExceptionRecord_block_invoke + 218 ([FIRCLSException.mm:218](http://firclsexception.mm:218/))
4  libdispatch.dylib              0x64094 _dispatch_client_callout + 16
5  libdispatch.dylib              0x46464 _dispatch_lane_barrier_sync_invoke_and_complete + 52
6  FirebaseCrashlytics            0x10110 FIRCLSExceptionRecord + 225 ([FIRCLSException.mm:225](http://firclsexception.mm:225/))
7  FirebaseCrashlytics            0x103fc FIRCLSExceptionRecordNSException + 111 ([FIRCLSException.mm:111](http://firclsexception.mm:111/))
8  FirebaseCrashlytics            0xfcf4 FIRCLSTerminateHandler + 279 ([FIRCLSException.mm:279](http://firclsexception.mm:279/))
9  libc++abi.dylib                0x10274 std::__terminate(void ()()) + 16
10 libc++abi.dylib                0x1021c std::terminate() + 60
11 libobjc.A.dylib                0x2846c objc::DenseMapBase<objc::DenseMap<objc_class, PendingInitialize*, objc::DenseMapValueInfo<PendingInitialize*>, objc::DenseMapInfo<objc_class*>, objc::detail::DenseMapPair<objc_class*, PendingInitialize*> >, objc_class*, PendingInitialize*, objc::DenseMapValueInfo<PendingInitialize*>, objc::DenseMapInfo<objc_class*>, objc::detail::DenseMapPair<objc_class*, PendingInitialize*> >::FatalCorruptHashTables(objc::detail::DenseMapPair<objc_class*, PendingInitialize*> const*, unsigned int) const + 10
12 libdispatch.dylib              0x640a8 _dispatch_client_callout + 36
13 libdispatch.dylib              0x45858 _dispatch_main_queue_drain + 888
14 libdispatch.dylib              0x454d0 _dispatch_main_queue_callback_4CF$VARIANT$armv81 + 36
15 CoreFoundation                 0x4e0c4 CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE + 12
16 CoreFoundation                 0xb5e8 __CFRunLoopRun + 2544
17 CoreFoundation                 0x1e240 CFRunLoopRunSpecific + 572
18 GraphicsServices               0x1988 GSEventRunModal + 160
19 UIKitCore                      0x4e541c -[UIApplication _run] + 1080
20 UIKitCore                      0x27eb88 UIApplicationMain + 336
21 TCPApp                         0xa34528 main + 39 (AppDelegate.swift:39)
22 ???                            0x1062183d0 (Missing)
Crash Events	:	1 crash event affecting 1 user
Device For Max count	:	iPhone 8 Plus
OS for Max count	:	ios15

**Comment by rizafran** [comment]
Thanks for reaching out, @siddew201. Based on the stack trace you shared, Crashlytics sometimes blames its own crash processing thread, but the crash is not actually caused by Crashlytics. To identify the root cause, could you share the full stack trace of your issue?

**Comment by siddew201** [comment]
Hi @rizafran thanks for your response. There are 51 threads on Crashlytics alongside the thread I have shared with you. are you asking for all 51 threads stack trace? Thanks

**Comment by rizafran** [comment]
Hi @siddew201, yes it's fine. You may add it in a `.txt` file instead. Thanks.
