### ISSUE TITLE
Data written to device storage can be accessed through several attack vectors

### ISSUE THREAD

**Issue by FranciscoPereira** [firebase/firebase-ios-sdk#9934]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.2.1
  * Firebase SDK version: 8.13.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: Crashlytics
  * Target platform(s): `iOS`

### [REQUIRED] Step 2: Describe the problem
Our security team scanned our code and dependencies for vulnerabilities and found that the Password specified in the Findings Evidence table has been found within local application folders or external storage locations on the device. Data written to device storage can be accessed through several attack vectors. An attacker who is able to access the charging port may be able to access this data if the user acknowledges the trust or if the device is rooted. Data backup utilities are often able to export local files and, if not encrypted, can be accessed by an attacker in possession of the backup file(s). While malware is also a concern, it is less common than attacks concerning physical device access.
If sensitive data is exposed, the data can be used by an adversary to track and phish users, access their account, or circumvent protections within the app.

#### Risk and Regulatory Information
Severity: medium
CVSS: 4.4
CWE: [312](https://cwe.mitre.org/data/definitions/312.html)
FISMA MED: [SC-28 PROTECTION OF INFORMATION AT REST](https://csrc.nist.gov/Projects/risk-management/sp800-53-controls/release-search#!/control?version=5.1&number=SC-28)
Risk OWASP: [Mobile Top 10: M2-Insecure Data Storage](https://owasp.org/www-project-mobile-top-10/2016-risks/m2-insecure-data-storage), [MASVS 2.1](https://github.com/OWASP/owasp-masvs/blob/master/Document/0x07-V2-Data_Storage_and_Privacy_requirements.md)
GDPR: [Risks violating Article 25](https://gdpr-info.eu/art-25-gdpr/), [Risks violating Article 32](https://gdpr-info.eu/art-32-gdpr/)
FFIEC: [May violate D3.PC.Am.A.1](https://www.ffiec.gov/pdf/cybersecurity/FFIEC_CAT_May_2017.pdf)
PCI: [May violate requirement 3.1 through 3.4](https://www.pcisecuritystandards.org/document_library?document=pci_dss)
HIPAA: [May violate §164.312(a)(1): Standard: Access control.](https://www.hhs.gov/sites/default/files/ocr/privacy/hipaa/administrative/securityrule/techsafeguards.pdf?language=es)
CCPA: [Risks violating CCPA: exfiltration, theft, or disclosure of PII](https://ccpa-info.com/home/1798-150-civil-actions/)
CWE Top 25: [2020 CWE Top 25 Most Dangerous Software Errors](https://cwe.mitre.org/top25/archive/2020/2020_cwe_top25.html)

#### Steps to reproduce:
Using a jailbroken iOS device, data can be extracted and analyzed from the file paths mentioned in the Findings Evidence table. The extraction can be performed using SSH or other file transfer protocols. These will need to be installed through the jailbreak APT (Cydia or Sileo). Another option is to use the simulator tool that is included with Xcode to extract data from the file storage container.
Our automated testing examines local application files and storage locations for sensitive data after the app is exercised.

#### Relevant Code:
```
{
  "data_value_type": "automation:password",
  "sensitive data value": "313231323132",
  "encoded format": "hex",
  "file_name": "/private/var/mobile/Containers/Data/Application/7B3B230A-462C-4AF7-9B8A-9C21FAC33697/Library/Caches/com.crashlytics.data/***/v5/reports/active/6c7623c69dd2451fbf35deb2d13caf4/log a.clsrecord",
  "offset in file": "0x26f",
  "backup": "false",
  "protection": "NSFileProtectionNone"
}
```

**Comment by samedson** [comment]
Hi @FranciscoPereira, do you know what Crashlytics data this pertains to? Is this a bug specific to Crashlytics?

**Comment by morganchen12** [comment]
> An attacker who is able to access the charging port may be able to access this data if the user acknowledges the trust or if the device is rooted

This effectively means they have the device in hand and know the device passcode to unlock it, right? If a user plugs their device into a trusted laptop, they can extract crash data through Xcode directly without having to copy Firebase's `.clsrecord` files from the app.

> Using a jailbroken iOS device, data can be extracted and analyzed from the file paths mentioned in the Findings Evidence table

Can you share the Findings Evidence table?
