### ISSUE TITLE
Zip: `No such module 'GoogleSignInSwift'` on import

### ISSUE THREAD

**Issue by ionothanus** [firebase/firebase-ios-sdk#9937]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.4.1
  * Firebase SDK version: 9.2.0
  * Installation method: `Zip file`
  * Firebase Component: Google Sign In
  * Target platform(s): `iOS`

### [REQUIRED] Step 2: Describe the problem
I've attempted to use the new `GoogleSignInSwiftSupport` xcframework in Firebase.zip in version 9.2.0. I can't get the compiler to import the module `GoogleSignInSwift`. Additionally, attempting to import `GoogleSignInSwiftSupport` (as the xcframework is named) produces additional errors.

I removed all other installations of Firebase dependencies from alternate sources, cleaned my build folder, and restarted Xcode, but the issue persists. If I remove the `GoogleSignInSwift` import, my project builds fine (i.e., all my other imports from this installation method are working).
#### Steps to reproduce:
1. Add the `GoogleSignInSwiftSupport` xcframework from the Firebase zip to an iOS project, along with the GoogleSignIn framework & dependencies + resources
2. Add any other Firebase frameworks as needed
3. Attempt to `import GoogleSignInSwift` in the project
4. Build

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

The error `No such module 'GoogleSignInSwift'` is produced.

If instead you attempt to import `GoogleSignInSwiftSupport`, in addition to the error `No such module 'GoogleSignInSwiftSupport'`, you'll also receive a handful of other errors multiple times:
`Redefinition of module 'GoogleSignInSwift'`
`Redefinition of module 'Swift'`

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
import GoogleSignInSwift
```

**Comment by rizafran** [comment]
Thanks for reporting this, @ionothanus. I was able to reproduce the issue. I'll inform the engineers about this and see what we can do.

**Comment by paulb777** [comment]
I've reproduced.  It looks like there are various inconsistencies in the CocoaPods/Xcode/Zip Builder tooling when the module name is different from the pod name.

We can do a bit more investigation, but as it looks now, we may need to drop GoogleSignInSwiftSupport from the zip as long as its module name does not match the pod name.

Sorry about the misfire in the 9.2.0 release.

cc: @petea
