### ISSUE TITLE
ios15 install fail when Embed&Sign GoogleAppMeasurementOnDeviceConversion framework

### ISSUE THREAD

**Issue by Breeze048** [firebase/firebase-ios-sdk#9938]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version:13.4.1 
  * Firebase SDK version: 9.1.0
  * Installation method: `Zip file` 
  * Firebase Component: FirebaseAnalyticsOnDeviceConversion、FirebaseAnalytics、FirebaseMessaging
  * Target platform(s): `iOS `

### [REQUIRED] Step 2: Describe the problem
When I Embed & Sign GoogleAppMeasurementOnDeviceConversion framework, the app cannot be installed on ios15 devices， error msg is :
The code signature version is no longer supported.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620375
User Info: {
    DVTRadarComponentKey = 261622;
    MobileDeviceErrorCode = "(0xE8008029)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x00000001211e5614 DTDKCreateNSErrorFromAMDErrorCode + 272
	1   DTDeviceKitBase                     0x000000012121edd8 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 160
	2   DVTFoundation                       0x000000010662dbd0 DVTInvokeWithStrongOwnership + 76
	3   DTDeviceKitBase                     0x000000012121eb30 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1336
	4   IDEiOSSupportCore                   0x000000011ce51590 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.301 + 2916
	5   DVTFoundation                       0x0000000106754f50 __DVT_CALLING_CLIENT_BLOCK__ + 16
	6   DVTFoundation                       0x0000000106756068 __DVTDispatchAsync_block_invoke + 364
	7   libdispatch.dylib                   0x000000019949e5f0 _dispatch_call_block_and_release + 32
	8   libdispatch.dylib                   0x00000001994a01b4 _dispatch_client_callout + 20
	9   libdispatch.dylib                   0x00000001994a78a8 _dispatch_lane_serial_drain + 668
	10  libdispatch.dylib                   0x00000001994a8404 _dispatch_lane_invoke + 392
	11  libdispatch.dylib                   0x00000001994b2c98 _dispatch_workloop_worker_thread + 648
	12  libsystem_pthread.dylib             0x0000000199660360 _pthread_wqthread + 288
	13  libsystem_pthread.dylib             0x000000019965f080 start_wqthread + 8
);
}

I found that the codesign version is 20200 after the dynamic library signature of GoogleAppMeasurementOnDeviceConversion

#### Steps to reproduce:

1、Add any other Firebase frameworks as needed
2、Embed & Signed GoogleAppMeasurementOnDeviceConversion
3、Build

**Comment by rizafran** [comment]
Hi @Breeze048, I was able to reproduce the behavior when I embedded any of the Firebase frameworks. Based on the instructions from the `README` file, it looks like an intended behavior: 
> Do not add the Firebase frameworks to the `Embed Frameworks` in `Xcode Build Phase`. The Firebase frameworks are not embedded dynamic frameworks, but are [static frameworks](https://www.raywenderlich.com/65964/create-a-framework-for-ios) which cannot be embedded into your application's bundle.

**Comment by Breeze048** [comment]
The GoogleAppMeasurementOnDeviceConversion Framework in Firebase zip file is a dynamic framework, Don't need Embed&Sign it?
GoogleAppMeasurementOnDeviceConversion Framework in FirebaseAnalyticsOnDeviceConversion/GoogleAppMeasurementOnDeviceConversion.xcframework/ios-arm64_armv7/GoogleAppMeasurementOnDeviceConversion.framework
