### ISSUE TITLE
Does FirebaseOptions work with Crashlytics ?

### ISSUE THREAD

**Issue by VivekTate** [firebase/firebase-ios-sdk#9939]
Hey Folks,
I am using FirebaseOptions in my project for firebaseApp configuration. I get the firebaseOptions data at runtime via an API call. For the first time, when I don't have any firebaseOptions data (before API call), I configure the firebaseApp as defaultApp with GoogleService-info.plist file stored in my source code initially. Once I get the firebaseOptions data from API (which is totally different for the stored GoogleService-info.plist file). I delete the earlier instance of FirebaseApp and configure new FirebaseApp as defaultApp with new firebaseOptions.
It works fine on firebase-android-sdk.

So does firebaseOptions work with crashlytics in iOS?

**Comment by rizafran** [comment]
Sorry for the late reply, @VivekTate. Per checking,`firebaseOptions` works in Crashlytics, and this behavior should also work in iOS.
