### ISSUE TITLE
In Firebase Functions iOS, a Cloud function error 'already-exists' gets treated as 'notFound'

### ISSUE THREAD

**Issue by tciuro** [firebase/firebase-ios-sdk#9942]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.4.1
  * Firebase SDK version: 9.3.0
  * Installation method: CocoaPods
  * Firebase Component: Functions
  * Target platform(s): iOS

### [REQUIRED] Step 2: Describe the problem

Functions that throw `already-exists` generate the right HTTP response (seen in Postman as `HTTP 409 Conflict`). However, in the iOS client bubbles the error to the client as `notFound`. The commit mentioned below shows the affected areas and includes a fix.

#### Steps to reproduce:

Simple. Just throw the following from a Cloud Function:

`throw new functions.https.HttpsError('already-exists', 'Resource exists')`

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
https://github.com/firebase/firebase-ios-sdk/commit/3e758246f6c25001cb9f36ac9b429101a59219c7
```

**Comment by paulb777** [comment]
Thanks for the report and suggested fix!

The error code problem is a regression from Firebase 8 to Firebase 9.  The 409 processing looks like it has always been an issue.  We'll follow up on a fix for 9.3.0.

**Comment by paulb777** [comment]
@tciuro Do you want to turn the fix into a PR to get the credit for the fix in the repo history?

**Comment by tciuro** [comment]
I'd love to! Coming up. Thank you!
