### ISSUE TITLE
Deep Link does not contain valid required params.

### ISSUE THREAD

**Issue by satyarthiroshni** [firebase/firebase-ios-sdk#9945]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.4
  * Firebase SDK version: 8.11.0
  * Installation method: `CocoaPods
  * Firebase Component: Firebase/DynamicLinks (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Target platform(s):  iOS

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

when app is in background state and tried to open with deep link. It is showing below error but working fine when app is in not running or suspended state.
used universal dynamiclink  https://preview.page.link/vdb.page.link?link=https://appname.customvirtual.app/client/deep/diamond/1/item_request/48035/?request_type%3Dmemo%26view_type%3Dbuyer_view&apn=com.vdbsalesapp.android&isi=1477954444&ibi=com.vdb.sales
getting below error 
Deep Link does not contain valid required params. URL params: {
    "_cpb" = 1;
    "_cpt" = cpit;
    "_fpb" = "CJsFEPcCGgVlbi1VUw==";
    "_iumchkactval" = 1;
    "_iumenbl" = 1;
    "_plt" = 2185;
    "_uit" = 1715;
    apn = "com.vdbsalesapp.android";
    cid = 9060306397093604022;
    ibi = "com.vdb.sales";
    isi = 1477954444;
    link = "https://appname.customvirtual.app/client/deep/diamond/1/item_request/48506/?request_type=memo&view_type=buyer_view";
}

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

Below are the code used to open deeplink:- 

- (BOOL)handleUniversalLink:(NSURL *)universalLinkURL
                 completion:(FIRDynamicLinkUniversalLinkHandler)completion {
  if ([self matchesShortLinkFormat:universalLinkURL]) {
    __weak __typeof__(self) weakSelf = self;
    [self resolveShortLink:universalLinkURL
                completion:^(NSURL *url, NSError *error) {
                  __typeof__(self) strongSelf = weakSelf;
                  if (strongSelf) {
                    FIRDynamicLink *dynamicLink = [strongSelf dynamicLinkFromCustomSchemeURL:url];
                    dispatch_async(dispatch_get_main_queue(), ^{
                      completion(dynamicLink, error);
                    });
                  } else {
                    completion(nil, nil);
                  }
                }];
    return YES;
  } else {
    [self dynamicLinkFromUniversalLinkURL:universalLinkURL completion:completion];
    BOOL canHandleUniversalLink =
        [self canParseUniversalLinkURL:universalLinkURL] && universalLinkURL.query.length > 0 &&
        FIRDLDictionaryFromQuery(universalLinkURL.query)[kFIRDLParameterLink];
    return canHandleUniversalLink;
  }
}
///
- (nullable FIRDynamicLink *)
    dynamicLinkInternalFromUniversalLinkURL:(NSURL *)url
                                 completion:
                                     (nullable FIRDynamicLinkUniversalLinkHandler)completion {
  // Make sure the completion is always called on the main queue.
  FIRDynamicLinkUniversalLinkHandler mainQueueCompletion =
      ^(FIRDynamicLink *_Nullable dynamicLink, NSError *_Nullable error) {
        if (completion) {
          dispatch_async(dispatch_get_main_queue(), ^{
            completion(dynamicLink, error);
          });
        }
      };
  if ([self canParseUniversalLinkURL:url]) {
    if (url.query.length > 0) {
      NSDictionary *parameters = FIRDLDictionaryFromQuery(url.query);
      if (parameters[kFIRDLParameterLink]) {
        FIRDynamicLink *dynamicLink = [[FIRDynamicLink alloc] init];
        NSString *urlString = parameters[kFIRDLParameterLink];
        NSURL *deepLinkURL = [NSURL URLWithString:urlString];
        if (deepLinkURL) {
          dynamicLink.url = deepLinkURL;
          dynamicLink.matchType = FIRDLMatchTypeUnique;
          dynamicLink.minimumAppVersion = parameters[kFIRDLParameterMinimumAppVersion];
          // Call resolveShortLink:completion: to do logging.
          // TODO: Create dedicated logging function to prevent this.
          [self.dynamicLinkNetworking
              resolveShortLink:url
                 FDLSDKVersion:FIRFirebaseVersion()
                    completion:^(NSURL *_Nullable resolverURL, NSError *_Nullable resolverError) {
                      mainQueueCompletion(dynamicLink, resolverError);
                    }];
#ifdef GIN_SCION_LOGGING
          FIRDLLogEventToScion(FIRDLLogEventAppOpen, parameters[kFIRDLParameterSource],
                               parameters[kFIRDLParameterMedium],
                               parameters[kFIRDLParameterCampaign], _analytics);
#endif
          return dynamicLink;
        }
      }
    }
  }
  mainQueueCompletion(nil, nil);
  return nil;
}

///
NSDictionary *FIRDLDictionaryFromQuery(NSString *queryString) {
  NSArray<NSString *> *keyValuePairs = [queryString componentsSeparatedByString:@"&"];

  NSMutableDictionary *queryDictionary =
      [NSMutableDictionary dictionaryWithCapacity:keyValuePairs.count];

  for (NSString *pair in keyValuePairs) {
    NSArray *keyValuePair = [pair componentsSeparatedByString:@"="];
    if (keyValuePair.count == 2) {
      NSString *key = keyValuePair[0];
      NSString *value = [keyValuePair[1] stringByRemovingPercentEncoding];
      [queryDictionary setObject:value forKey:key];
    }
  }
  return [queryDictionary copy];
}

**Comment by rizafran** [comment]
Thanks for reporting, @satyarthiroshni. Based on the error you provided, it's possible that your link structure is not properly configured. With this, you may try the following suggestions: 
- Make sure that your [link parameter](https://firebase.google.com/docs/dynamic-links/create-manually) is correct and [URL encoded](https://en.wikipedia.org/wiki/Percent-encoding)
- Debug your dynamic link as mentioned [here](https://firebase.google.com/docs/dynamic-links/debug) and make sure that your link doesn’t have any error or warning because it might affect the behavior of your links
- You may try enabling the [iOS self-diagnostic tool](https://firebase.google.com/docs/dynamic-links/debug#ios_self-diagnostic_tool) to see if there's any warning or errors in the logs

You may also check this [related issue](https://github.com/firebase/quickstart-ios/issues/774).

**Comment by satyarthiroshni** [comment]
Hi @rizafran 
i have added the above code to handle deep link. It is not working for only one condition i.e when app is in background and through deep link tried to open particular screen of the app.
I have checked the parameter those are ok and properly encoded. can you suggest me what exact info needs to be update here to help me to solve this issue.

**Comment by rizafran** [comment]
Hi @satyarthiroshni, as discussed with the team, there's a recent bug that might be related to this issue. But first, could you provide the following details:
- Affected device + OS version
- Copy or screenshot of console logs

**Comment by satyarthiroshni** [comment]
Hi @rizafran 
issue is not on specific device. issue tried to reproduced on iphone 7, iphone 6s plus, iphone 8s plus, iphone x,
os version - 14.4, 15.5
Below log is for "**Device** -  8s plus" and "**iOS version** - 15.5" , mac OS version -12.4.
<img width="1025" alt="Screenshot 2022-07-11 at 11 39 15 AM" src="https://user-images.githubusercontent.com/31504684/178200452-00bfa5e2-70d1-45ed-9340-d36c17d5c3ab.png">

**Comment by rizafran** [comment]
Thanks for clarifying, @satyarthiroshni. Looks like it's not related to the recent bug. I think the best next step here is to file a ticket through our [support channel ](https://firebase.google.com/support) so the team would be able to check your project info and FDL config. With this, I'll now be closing this issue.
