### ISSUE TITLE
Email Accounts in Firebase Authentication are automatically deleted

### ISSUE THREAD

**Issue by aydin90** [firebase/firebase-ios-sdk#9950]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.3.1
  * Firebase SDK version: 6.34.0
  * Installation method: CocoaPods
  * Firebase Component: Auth
  * Target platform(s): iOS

#### Steps to reproduce:

Our users could use our app with an anonymous account until now. Last week we introduced registration with the email address. During registration, the "linkWithCredential" function links the email addresses to the Anonymous accounts. In testing, everything worked fine. After we launched registration, some users (iOS: 15.5.0, 15.3.1, 14.8.1 ) reported to us that they had to log in again after opening the app (even though they had not logged out) because their email addresses were not present. When I searched for their email addresses under authentication, I couldn't find them. So that means their email addresses were deleted even though we haven't implemented account deletion yet.

This is really strange because the accounts should not be deleted just like that. 

```
// TODO(you): code here to reproduce the problem
Unfortunately I could not reproduce it

**Comment by rizafran** [comment]
Hi @aydin90, based on the info you shared, it seems that you're using an older SDK version which might be causing the issue. First off, is it possible for you to try using a [later version](https://firebase.google.com/support/release-notes/ios) of your SDK?

**Comment by aydin90** [comment]
Hello  @rizafran, thank you for your quick reply. We have now run an update. Now we have to wait and see if the same error occurs again.
