### ISSUE TITLE
Firestore 9.2.0 - XCode 13.4.1 Warnings in Firestore

### ISSUE THREAD

**Issue by Sunrise17** [firebase/firebase-ios-sdk#9953]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.4.1
  * Firebase SDK version: 9.2.0
  * Installation method: `CocoaPods`
  * Firebase Component: Firestore
  * Target platform(s): `iOS`

### [REQUIRED] Step 2: Describe the problem

After updating pods to new version (9.2.0) in my iOS Project, i have received following warnings as seen in attached screenshot of following file.

<img width="1542" alt="Ekran Resmi 2022-06-27 17 00 36" src="https://user-images.githubusercontent.com/26038249/175973243-5390d388-0927-4f24-b0eb-6df8b136d3e3.png">

<img width="1915" alt="Ekran Resmi 2022-06-27 17 01 19" src="https://user-images.githubusercontent.com/26038249/175973266-06a13cd7-2042-488b-b81b-ddc669aa482b.png">

**Comment by dconeybe** [comment]
I'll fix this

**Comment by dconeybe** [comment]
The fix will be included in one of the next two releases. Thank you for reporting.

**Comment by dconeybe** [comment]
The fix was released in 9.3.0.
