### ISSUE TITLE
FBSSerialQueue calling ApplicationWillTerminate

### ISSUE THREAD

**Issue by BarryDuggan** [firebase/firebase-ios-sdk#9967]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a GitHub issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.4
  * Firebase SDK version: 9.0.0
  * Installation method: `CocoaPods 
  * Firebase Component: Core, Performance, Analytics, Crashlytics
  * Target platform(s): ` iOS

### [REQUIRED] Step 2: Describe the problem
I've gotten a crash on iOS 15.
Logging is enabled in my app but there are no logs in the crash report.
Also device orientation for the crash is reported as unknown.
The only thing I can see in the stack trace to point a finger at is FBSSerialQueue

#### Steps to reproduce:

I've no Idea how to reproduce this because there are no logs being reported

#### Relevant Code:

```
Crashed: com.apple.main-thread
0  TOFS_AppStore                  0x49c384 specialized AppDelegate.applicationWillTerminate(_:) + 4378362756 (AppDelegate.swift:4378362756)
1  TOFS_AppStore                  0x49a258 @objc AppDelegate.applicationWillTerminate(_:) + 4378354264 (<compiler-generated>:4378354264)
2  UIKitCore                      0xf50e64 -[UIApplication _terminateWithStatus:] + 244
3  UIKitCore                      0x63bd14 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 128
4  UIKitCore                      0x830c5c -[_UISceneLifecycleMultiplexer forceExitWithTransitionContext:scene:] + 224
5  UIKitCore                      0xf4dae4 -[UIApplication workspaceShouldExit:withTransitionContext:] + 212
6  FrontBoardServices             0x4fc38 __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke_2 + 80
7  FrontBoardServices             0xa6b4 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 240
8  FrontBoardServices             0x4fbd0 __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke + 132
9  libdispatch.dylib              0x4660 _dispatch_client_callout + 20
10 libdispatch.dylib              0x8118 _dispatch_block_invoke_direct + 264
11 FrontBoardServices             0xbf94 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 48
12 FrontBoardServices             0xb3d4 -[FBSSerialQueue _targetQueue_performNextIfPossible] + 220
13 FrontBoardServices             0xf9e4 -[FBSSerialQueue _performNextFromRunLoopSource] + 28
14 CoreFoundation                 0xbb020 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
15 CoreFoundation                 0xcbce0 __CFRunLoopDoSource0 + 208
16 CoreFoundation                 0x5fe8 __CFRunLoopDoSources0 + 268
17 CoreFoundation                 0xb7f4 __CFRunLoopRun + 820
18 CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
19 GraphicsServices               0x138c GSEventRunModal + 164
20 UIKitCore                      0x5196a8 -[UIApplication _run] + 1100
21 UIKitCore                      0x2987f4 UIApplicationMain + 2092
22 TOFS_AppStore                  0x9bf0 main + 20 (AppDelegate.swift:20)
23 ???                            0x1012c9a24 (Missing)
```

**Comment by rizafran** [comment]
Hi @BarryDuggan, it looks like the provided information isn't related to Firebase SDK. Could you share the full stack trace of your crash?

**Comment by BarryDuggan** [comment]
I found a similar post on this [stackoverlfow question](https://stackoverflow.com/a/70077366/264273)
The theory is that in some cases `applicationWillTerminate` can get called before `applicationDidLaunch`.
If you reference any objects in the terminate method that relies on applicationDidLaunch to instantiate there a chance the object may be nil in the terminate method.

In my case I have an object in the app delegate that is nil and gets instantiated in `applicationDidLaunch`.
This object is referenced in my `applicationWillTerminate`.

Is there any credence to this in your opinion?

**Comment by paulb777** [comment]
That seems possible. Here's another related discussion https://developer.apple.com/forums/thread/707714

**Comment by morganchen12** [comment]
`FBSSerialQueue`, and the `FBS`-prefixed classes in general, belong to a private OS framework called FrontBoardServices, not Firebase. Since there's no Firebase symbols in the stack trace this crash is almost definitely not caused by Firebase.

**Comment by BarryDuggan** [comment]
Thanks for that @morganchen12

**Comment by BarryDuggan** [comment]
closing due to @morganchen12 observation that this issue has nothing to do with firebase
