### ISSUE TITLE
AnalyticsParameterQuantity always 0

### ISSUE THREAD

**Issue by philmartin83** [firebase/firebase-ios-sdk#9983]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a GitHub issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.4
  * Firebase SDK version: 9.2.0
  * Installation method: `Swift Package Manager` (select one)
  * Firebase Component: Analytics
  * Target platform(s): iOS 

#### Steps to reproduce:

What happened? How can we make the problem occur?
I've been sending AnalyticsParameterQuantity: 1. in my AnalyticsParameterItems and no matter the Int value sent its always 0 in the debug view.

#### Relevant Code:

```swift
Analytics.logEvent(AnalyticsEventPurchase, parameters: [
      AnalyticsParameterTransactionID:"2cf44ddd-1c4e-4a7c-9536-f5b1cbb1dd36",
      AnalyticsParameterAffiliation: "My Test Analytics",
      AnalyticsParameterValue: 9.99,
      AnalyticsParameterCurrency: "GBP",
      AnalyticsParameterItems: data?.JourneyProducts.compactMap({ item in
                  [AnalyticsParameterItemID: item.ProductId,
                    AnalyticsParameterItemBrand: "My Test Analytics",
                    AnalyticsParameterPrice: 9.99,
                    AnalyticsParameterQuantity: 1]
        }) ?? [:]
])
```

**Comment by rizafran** [comment]
Thanks for reporting, @philmartin83. I can't reproduce the same behavior. May I know if you're [modifying event](https://support.google.com/analytics/answer/10085872?hl=en&ref_topic=9756175#zippy=%2Cin-this-article) that may affect any purchase event through Analytics dashboard?
