### ISSUE TITLE
Deprecate unintentional public API `foo` in FIAM Swift

### ISSUE THREAD

**Issue by ryanwilson** [firebase/firebase-ios-sdk#9998]
https://github.com/firebase/firebase-ios-sdk/blob/8467858fc4cee858511380ac0f9ea5a17d007b5d/FirebaseInAppMessaging/Swift/Source/SwiftUIPreviewHelpers.swift#L23

😢

**Comment by paulb777** [comment]
Oops, good catch.  Related to #8416.
