### ISSUE TITLE
 iOS : FPRNetworkTrace.m line 144 : __48-[FPRNetworkTrace updateTraceWithCurrentSession]_block_invoke

### ISSUE THREAD

**Issue by siddew201** [firebase/firebase-ios-sdk#9999]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a GitHub issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: __13.2.1___
  * Firebase SDK version: __8.4.0___
  * Installation method: `CocoaPods 
  * Firebase Component: _____ (DynamicLinks, Installations, Analytics, RemoteConfig, Messaging, Crashlytics)
  * Target platform(s): iOS 

### [REQUIRED] Step 2: Describe the problem
The app is getting crash at user's end 

#### Steps to reproduce:

Since the app is getting crash at user's end, we don't have a way to reproduce it

#### Relevant Code:
Crash Item	:	  Ios: FPRNetworkTrace.m line 144 : __48-[FPRNetworkTrace updateTraceWithCurrentSession]_block_invoke
Issue Details	:	Crashed: com.google.perf.sessionIds.networkTrace
0  libobjc.A.dylib                0x1f40 objc_msgSend + 32
1  FirebasePerformance            0x14544 __48-[FPRNetworkTrace updateTraceWithCurrentSession]_block_invoke + 144 (FPRNetworkTrace.m:144)
2  libdispatch.dylib              0x1e6c _dispatch_call_block_and_release + 32
3  libdispatch.dylib              0x3a30 _dispatch_client_callout + 20
4  libdispatch.dylib              0xb124 _dispatch_lane_serial_drain + 668
5  libdispatch.dylib              0xbc80 _dispatch_lane_invoke + 392
6  libdispatch.dylib              0x16500 _dispatch_workloop_worker_thread + 648
7  libsystem_pthread.dylib        0x10bc _pthread_wqthread + 288
8  libsystem_pthread.dylib        0xe5c start_wqthread + 8Crash Events

```
// TODO(you): code here to reproduce the problem
```

**Comment by rizafran** [comment]
Thanks for reporting, @siddew201. The issue looks related to #8495 and already fixed on v8.6.0. Could you try updating your SDK version?
